### ISSUE TITLE
Don't supports anonymous classes from php7

### ISSUE THREAD

**Issue by galillei** [magento/magento2#5038]
**Steps to reproduce**
I use Magento 2.0.5 on php 7.0.2 and try it use with anonymous classes. It's work correctly before i try to use production mode with di compile. 
for example

``` php
    public function getDebug()
    {
        return (new class($this->_loadOrder){
            protected $loadOrder;
            public function __construct($loadOrder)
            {
                $this->_loadOrder = $loadOrder;
            }
            public function getOrderStatus()
            {
                return $this->_loadOrder->getStatus();
            }
        });
    }
```

And try to run follow command ./bin/magento setup:di:compile  
i get error
`[ReflectionException]                               
  Class \Rcklss\ShipWorks\Model\$this does not exist`

**Expected:**
Code works same in developer and production mode and compiles without errors.

**Actual**
Error on compilation

**Comment by xi-ao** [comment]
This is a nasty limitation of the compiler indeed.

**Comment by YevSent** [comment]
Hi, @Galillei, thanks for reporting. I've created internal ticket (MAGETWO-66828).

**Comment by dangron** [comment]
@joni-jones any update on this? Finding this open issue has ruined my day somewhat.

**Comment by YevSent** [comment]
Hi, @dank00, I'm not sure if it will be done before Magento 2.3 release. This issue was converted to feature because requires refactoring of a lot of functionality which includes code auto generation, pluginization, etc.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Don-t-supports-anonymous-classes-from-php7/idi-p/73602).

**Comment by kanduvisla** [comment]
Any chance this will be backported to 2.2.5?
