### ISSUE TITLE
Add to cart doesn't work inside an iframe in IE

### ISSUE THREAD

**Issue by MidnightDesign** [magento/magento2#5039]
## Steps to reproduce
1. Load an M2 store inside an Iframe in IE11
2. Try to add a product to the cart
## Expected result

The product is added to the cart
## Actual result

The product isn't added to the cart and the "Add to cart" button stays grayed out saying "Adding...".

I've tracked the problem down to [the form key `Validator` returning false](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Data/Form/FormKey/Validator.php#L32) because the request's `form_key` is different from the session's.

Some additional info:
- The Iframe is on a different origin than the page that contains it. (I commented out `Header set X-Frame-Options SAMEORIGIN` in pub/.htaccess)
- Both the containing page and the Magento store inside the Iframe are served via HTTPS.
- In Chrome it works fine.

I know we're doing something pretty particular here, but maybe someone can help me anyway.

**Comment by MidnightDesign** [comment]
What's the MX label?

**Comment by piotrekkaminski** [comment]
@MidnightDesign Merchant eXperience, internal label as to which team/group the issue belongs.

**Comment by Stas94** [comment]
@MidnightDesign We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by iztan** [comment]
Hi @MidnightDesign , are you able to solve this issue? I am facing the similar experience.
