### ISSUE TITLE
Change 'select' to 'query' in AbstractSearchResult

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#5040]
Hello,

there is protected property "select" in [AbstractSearchResult](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Data/AbstractSearchResult.php#L62) that is never used 

```
/**
 * @var \Magento\Framework\DB\Select
 */
protected $select;
```

... and there is 'query' property in the constructor that is not defined:

```
public function __construct(
    \Magento\Framework\DB\QueryInterface $query,
    ...
) {
    $this->query = $query;
    ...
}
```

I suppose this code:

```
/**
 * @var \Magento\Framework\DB\Query
 */
protected $query;
```

should be instead of 'select' property.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Change-select-to-query-in-AbstractSearchResult/idi-p/45102).

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67408
