### ISSUE TITLE
JS jasmine spec grunt-contrib-less dependency version broken

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#5044]
## Steps to reproduce
1. Install Magento 2.0.7
2. run `npm install`
3. run `bin/magento setup:static-content:deploy`
4. run `grunt spec`
## Expected result

Jasmine tests found in `dev/tests/js/jasmine/tests/` being executed
## Actual result

``` bash
$ grunt spec
Running "spec" task

Running "connect:blank" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "jasmine:blank" (jasmine) task
Warning: Unable to read "/Volumes/CaseSensitive/Workspace/mediawave/m2ce/node_modules/grunt-contrib-jasmine/tasks/lib/../../node_modules/es5-shim/es5-shim.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```
## Further information

Reference https://github.com/gruntjs/grunt-contrib-jasmine/issues/193
Reference https://github.com/yeoman/generator-backbone/issues/387

After upgrading the dependency the tests start running but they fail due to `Magento_Ui/js` code that can't be found, but that should be a separate issue.

**Comment by anton-huz** [comment]
Just a notice: internal ticket MAGETWO-55344 has been created.

**Comment by VladimirZaets** [comment]
Hi @Vinai, we've updated this library in scope of our internal task, you can see this in current mainline. 
Thanks for your contribution.
