### ISSUE TITLE
The value of custom category image attribute is not removed properly

### ISSUE THREAD

**Issue by TamasJozsefSzabo** [magento/magento2#5046]
## Steps to reproduce
1. Add a custom image attribute to the category entity:
   `$catalogSetup->addAttribute(\Magento\Catalog\Model\Category::ENTITY, 'menu_image', array(
           'label'                      => 'Menu Image',
           'note'                       => 'Image that is shown for the menu item of current category',
           'input'                      => 'image',
           'backend'                    => \Magento\Catalog\Model\Category\Attribute\Backend\Image::class,
           'required'                   => false,
           'global'                     => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_STORE,
           'group'                      => 'Menu',
           'sort_order'                 => 30,
       ));
   `
2. Add/upload an image to a category via admin.
3. Remove the image via admin. (Using the "Delete image" check box.)
## Expected result

The image and the attribute value is removed.
## Actual result

The image is removed, but the attribute value is not.
<img width="733" alt="screen shot 2016-06-15 at 16 15 15" src="https://cloud.githubusercontent.com/assets/12332079/16085605/777bb37a-3314-11e6-96e6-61fd5fe2094b.png">
## Further info

In \Magento\Catalog\Controller\Adminhtml\Category\Save::_filterCategoryPostData method the logic is based on $data['image'](the default image attribute). This should probably take care of any image type attribute.

**Comment by oserediuk** [comment]
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by Sharmilasrini95** [comment]
Hello!We are using Magento2.0.7
