### ISSUE TITLE
Behavioral bug in CustomerRepositoryInterface::save() implementation

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#5050]
The behavior of the interface method mentioned in the title does not match the method signature.

Note: I already opened [an issue on this](https://github.com/magento/magento2/issues/4256) before, but it was closed without an response to the actual issue. The comment only was on the current implementation.

This is another attempt at raising the actual issue because I think it is important.

I want to start this quote from J.B. Rainsberger that he gave in an interview in [episode 38 of the FullStackRadio podcast](http://www.fullstackradio.com/38) (23. March 2016, "Unit Testability and the Universal Architecture"), because it so nicely describes the issue (transcript of spoken language):

> If you want modularity, the only way modularity works, is you have to have confidence in what that module does in the interface, in the contract of that module; so that **you don't have to look inside to see what it does**; to verify what it does.  
> You can just say "Look, okay, it says that it's gonna behave like this, I can depend on those behaviors, when I put the two things together they'll just work". That's what modularity is.  
> **So if you are not prepared to articulate the contract with that level of precision you're never going to achieve modularity**; you're not going to get the benefits of modularity.

~~~ J.B. at minute 49:10

Given this context, please have a look at the following method of the  `CustomerRepositoryInterface`

``` php
public function save(CustomerInterface $customer, $newPasswordHash = null);
```

What does it communicate?  
I can infer the following:
- The class is a repository for customers
- The `save` method will persist the given `CustomerInterface` instance
- The second argument `$passwordHash` is optional
- If it is present, the given customers password hash will be set to the specified value

Any other behavior **is not** communicated by the interface method.

The actual behavior regarding the password hash is quite different:
- If the customer is a new customer, the password hash is set.
- If the customer already exists, it is silently discarded.

This behavior is quite surprising and it requires a lot of digging in order to figure out what is going on.  
The way it stands, it will be the cause of weeks of wasted developer time over the coming years and is going to cause a lot of frustration along the way.  

I go so far as to say that given what the interface communicates, the actual behavior is buggy (see the issue title).
## So what to do about it?

I see more or less two options to fix this issue. Maybe you see more, which would be cool.
These are my thoughts oh it:
1. Fix the behavior so it matches what the interface communicates (always set the password hash if present)
2. Declare the current `save()` method as `@deprecated` and "articulate the contract with a level of precision" that conveys the actual behavior.  

Option 2 probably would require two separate methods, maybe something like `saveNewCustomer(CustomerInterface $newCustomer, $passwordHash)` and `saveCustomerInsecureData(CustomerInterface $customer)`. I'm sure you can come up with better names.  

My favorite solution would be to combine both options: change the `save()` method to always set the password, and provide two new methods (or a facade class) to impose the secure password setting policy. Only the facade methods could be exposed through the webapi, and module developers would have access to a `@api` blessed, stable, method to set a customer password without emails flying around.

This will be my last attempt to bring this issue to attention. It isn't only me who has already stumbled over the current implementation. Please take a moment to reflect about it and see if you really don't think it's worth fixing.

**Comment by pboisvert** [comment]
@antonkril not sure of you are the right person to investigate this one but if not hoping you might know who should review

**Comment by Alkar778** [comment]
@Vinai internal ticket was created MAGETWO-54615

**Comment by Vinai** [comment]
Thank you @Alkar778!

**Comment by slavvka** [comment]
Hi @Vinai, the issue has been fixed and delivered to mainline. Please see 4c03aad and 491a101
