### ISSUE TITLE
'Miscellaneous Scripts' being included in Admin Area

### ISSUE THREAD

**Issue by justindocanto** [magento/magento2#5051]
## Steps to reproduce
1. Head to Stores -> Configuration
2. Click 'Design' Tab & scroll down to 'HTML Head' section
3. Add any html to 'Miscellaneous Scripts' section & save store settings
## Expected result
1. Correct me if I'm wrong, but I think the contents of the 'Miscellaneous Scripts' field is only supposed to be added to the <head> of the front end (e.g. The customer facing site) and NOT the admin area (e.g. The dashboard)
## Actual result
1. The HTML is added to the admin area AND the front-end

**Comment by tkacheva** [comment]
@justindocanto please provide the detailed instruction (+screenshot if possible) where is  'Miscellaneous Scripts' section.

**Comment by RG-1** [comment]
>  the contents of the 'Miscellaneous Scripts' field is only supposed to be added to the of the front end

I agree.

![miscellaneous_scripts](https://cloud.githubusercontent.com/assets/17853402/16273549/574d12cc-38a2-11e6-8fd3-a62abebb6c79.png)

**Comment by justindocanto** [comment]
I'm doing a single store and single URL on my current implementation, meaning im able to hard code the URL in this box, so i dont have the 404 error you're having above

HOWEVER, and repeating my original issue, this shouldnt show up on the backend at all in the first place

Thanks @rg-1 for submitting a screenshot. Didnt have time to get to it

**Comment by RG-1** [comment]
There is 404 error because, I didn't create that file.
I just wanted to show that, any code from "Miscellaneous Scripts" is also added to admin panel.

I hope that this issue is easy to fix.

Best

**Comment by piotrekkaminski** [comment]
@tkacheva  @justindocanto @RG-1  this is no longer reproducible in 2.1. Note that the section was moved from Configuration to Content->Design.
