### ISSUE TITLE
[Suggestion] Improve theme file structure

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5052]
## Steps to reproduce
1. Install the [uber theme](https://github.com/ubertheme/crafts-magento-2-theme).
## Expected result
1. I'm expecting all the files for each theme are self-contained, meaning they should not pollute the general file structure in any way so there is a clear separation of code.
## Actual result
1. The theme installs a bunch of files in [pub/media](https://github.com/ubertheme/crafts-magento-2-theme/tree/master/pub/media). After installing multiple themes, files from different themes will start to get mixed up, potentially overwriting each other as well.

Suggestion: All files required by a theme should wholly exist only in that theme's directory and nowhere else, including those that currently go in `pub/media`.

**Comment by tkacheva** [comment]
@thdoan, Thanks for bringing the issue
 MAGETWO-54593 is created. @eug123 please take a look

**Comment by eug123** [comment]
@thdoan 
Thank you for submitting an issue.
But this is a 3d party theme and all additional files like `.sql` or `pub/media` contents are provided for example/sample purpose and are not required for the theme to be applied and functioning.

**Comment by thdoan** [comment]
@MomotenkoNatalia Thanks for the info -- closing ticket...
