### ISSUE TITLE
Deprecate/remove persistence methods in data models

### ISSUE THREAD

**Issue by tux-rampage** [magento/magento2#5054]
Persistence methods like `save()`, `load()` or `delete()` should be marked deprecated and in the next step they should be removed from data models (and all its abstract classes).

Magento 2 (finally) use the repository pattern. But the persistence methods in the data models violate this pattern. The models should be completely agnostic to the persistence layer.

Even though the public api interfaces do not define these persistence methods for the data models, extension developers - especially the ones coming from Magento 1.x - may (and surely will) fall for it and use these methods.

Also it should be stated more clearly in the devdocs that extension developers should never rely on the underlying resource model implementations since they are not part of the public api and the only valid way to fetch, save or delete models from the database (or perform any other persistence action) is the related repository. Consider a repository replacement may break a poorly coded extension and may kill the entire store setup.

Developers should also be advised to use caret deps on magento core modules (i.e. "^100.0.0") when their code is interacting with the public api only, and tilde deps to the micro-version (i.e. "~100.0.0") when interacting with classes/methods that are not part of the public api.

**Comment by maghamed** [comment]
Hi
@tux-rampage , your message is correct.

Nearest time methods  load/save/delete would be marked as deprecated in Magento\Framework\Model\AbstractModel as Magento propagates to use RepositoryInterface.
For those entities which don't have corresponding RepositoryInterface (aka Public APIs for retrieval/save/delete operations) - Resource models should be used directly for  load/save/delete operations.

We are working on corresponding blog post regarding this issue.
@benmarks @antonkril @alankent

**Comment by antonkril** [comment]
Load/save/delete were deprecated on model in 2.1

**Comment by antonkril** [comment]
Feel free to reopen issue if you still have questions/concerns
