### ISSUE TITLE
[Gallery] Color swatches ajax response while empty product

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5055]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create configurable product(visual swatch) without images
3. Open gallery page
4. Click on swatch option without images
## Expected result
1. Ajax response return default set of gallery(double items in gallery)
## Actual result
1. Ajax response must be empty array without gallery object.

Links: 
https://github.com/magento/magento2ce/blob/develop/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js#L862

**Comment by tkacheva** [comment]
currently  gallery returns images from configurable product. issues doesn't exist anymore.
