### ISSUE TITLE
[CE 2.0.7] Invoice and creditmemo bundle product [Dynamic Price] bug

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5057]
## Steps to reproduce
1. Install Magento CE 2.07
2. [Example] Add Bundle Product [Dynamic Price] to the cart and place order.
3. Go to admin interface & invoice this order
4. Magento will give you the hand to edit the products quantities of the bundle product, [illogical]
5. if i choose to not invoice all products of the bundle product, when i save the invoice. there is no way to invoice the rest. it considered totally invoiced. [i think the logical concept that we can't edit quantities of the products of bundle product in the invoice]
- Other issue : I can't invoice just 1 bundle product like the shipment

![snapshot1](https://cloud.githubusercontent.com/assets/13301885/16114715/390a79d4-33b2-11e6-900c-836061bc8d00.png)
- Other invoice issue is The subtotal is 0
  ![snapshot4](https://cloud.githubusercontent.com/assets/13301885/16115165/08e42766-33b5-11e6-883d-a5a26c40290c.png)
- Other issue with the credit memo of the bundle product .. The amount is 0 (zéro)

![snapshot2](https://cloud.githubusercontent.com/assets/13301885/16114955/aa91f93c-33b3-11e6-854e-ce2b15ca026d.png)
![snapshot3](https://cloud.githubusercontent.com/assets/13301885/16114956/aab9c57a-33b3-11e6-92ec-dfb88ccb4d54.png)

**Comment by Ctucker9233** [comment]
I agree with @Dayssam that the way bundles are handled is illogical. The idea behind a bundled product IMHO is that the items are supposed to be sold all together, not parceled out.

**Comment by smoskaluk** [comment]
@Dayssam Unfortunately, I could not reproduce the issue as you described it. Please provide the detailed steps I must follow to reproduce this issue. In addition, identify the OS and the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
