### ISSUE TITLE
magento 2 product import section(General system exception happened)

### ISSUE THREAD

**Issue by radhagobinda** [magento/magento2#5061]
## It always shows "General system exception happened"

Additional data: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'min_qty' cannot be null, query was: INSERT INTO `cataloginventory_stock_item` (`manage_stock`,`use_config_manage_stock`,`qty`,`min_qty`,`use_config_min_qty`,`min_sale_qty`,`use_config_min_sale_qty`,`max_sale_qty`,`use_config_max_sale_qty`,`is_qty_decimal`,`backorders`,`use_config_backorders`,`notify_stock_qty`,`use_config_notify_stock_qty`,`enable_qty_increments`,`use_config_enable_qty_inc`,`qty_increments`,`use_config_qty_increments`,`is_in_stock`,`low_stock_date`,`stock_status_changed_auto`,`is_decimal_divided`,`product_id`,`website_id`,`stock_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `manage_stock` = VALUES(`manage_stock`), `use_config_manage_stock` = VALUES(`use_config_manage_stock`), `qty` = VALUES(`qty`), `min_qty` = VALUES(`min_qty`), `use_config_min_qty` = VALUES(`use_config_min_qty`), `min_sale_qty` = VALUES(`min_sale_qty`), `use_config_min_sale_qty` = VALUES(`use_config_min_sale_qty`), `max_sale_qty` = VALUES(`max_sale_qty`), `use_config_max_sale_qty` = VALUES(`use_config_max_sale_qty`), `is_qty_decimal` = VALUES(`is_qty_decimal`), `backorders` = VALUES(`backorders`), `use_config_backorders` = VALUES(`use_config_backorders`), `notify_stock_qty` = VALUES(`notify_stock_qty`), `use_config_notify_stock_qty` = VALUES(`use_config_notify_stock_qty`), `enable_qty_increments` = VALUES(`enable_qty_increments`), `use_config_enable_qty_inc` = VALUES(`use_config_enable_qty_inc`), `qty_increments` = VALUES(`qty_increments`), `use_config_qty_increments` = VALUES(`use_config_qty_increments`), `is_in_stock` = VALUES(`is_in_stock`), `low_stock_date` = VALUES(`low_stock_date`), `stock_status_changed_auto` = VALUES(`stock_status_changed_auto`), `is_decimal_divided` = VALUES(`is_decimal_divided`), `product_id` = VALUES(`product_id`), `website_id` = VALUES(`website_id`), `stock_id` = VALUES(`stock_id`)

**Comment by pboisvert** [comment]
@radhagobinda can you follow the template provided in terms of providing steps to reproduce and also which version you are using? this will help speed any investigation

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
