### ISSUE TITLE
data-migration-tool converts utf8 characters to `?`

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#5062]
when migrating data from magento 1 to magento 2, some utf characters are converted to `?`

example:

can't view orders because when migrating data from `sales_flat_order_item` to `sales_order_item` table, `product_options` column contains serialized data. In my case product name contains character `č`, after migration `s:34:"Nohavičky HP25 ružovočierna S/M"` becomes `s:34:"Nohavi?ky HP25 ružovo?ierna S/M"` since `č` is 2 bytes long and `?` is only 1 byte, string is no longer 34 bytes long and that throws notice, which cause fatal error, because product options can't be unserialized.

**Comment by mslabko** [comment]
Hi @kandrejevs ,
Please use https://github.com/magento/code-migration repository for issues relate to migration from M1 to M2

**Comment by kandrejevs** [comment]
That repository is for code migration...

**Comment by mslabko** [comment]
Sorry, repository for data migration is https://github.com/magento/data-migration-tool

**Comment by palamar** [comment]
Please use  https://github.com/magento/data-migration-tool for issues related to data migration
