### ISSUE TITLE
Dynamic Tier Pricing for Configurable Products

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#5064]
## **Steps to reproduce**
1. Choose a configurable product.
2. Select one visual swatch color. 
3. Then select another visual swatch color with a separate tier pricing structure.
## **Expected result**
1. The tier pricing and price will dynamically change based on the color attribute’s pricing.
## **Actual result**
1. The price changes dynamically, but tier pricing does not change. 
2. This was functional in 1.9 but is lacking in Magento 2.

**Related**
—

This seems to be related to not being able to create tier pricing for configurable products. In order to add any sort of tier pricing to a configurable product, you must first create a simple product with tier pricing and then add it’s configurations after the fact. This method only displays the tier pricing that was configured with the initial simple product and doesn’t change even when tier pricing is configured for a separate color.

(See attached screenshot of it working in 1.9)
![screen-shot1](https://cloud.githubusercontent.com/assets/19981272/16131273/6c32cab8-33db-11e6-92ca-af1007d250af.jpg)
![screen-shot2](https://cloud.githubusercontent.com/assets/19981272/16131272/6c32bdb6-33db-11e6-84d1-27dc9702021b.jpg)

**Comment by antboiko** [comment]
Hi @pioneerathletics , thanks for reporting. We already have internal ticket MAGETWO-54411 to fix the issue with tier prices not being displayed on Configurable Product details page.

https://github.com/magento/magento2/issues/3759

Best,
Anton.

**Comment by jonsaf** [comment]
I am on Magento 2.1 and I can not get any tier pricing to display on Configurable Product Page.  Only the first tier simple price displays as you go to each option, nothing else.  The cart displays the correct pricing, but no indication from the product page why a customer just got a discount for ordering more quantity.

**Comment by olysenko** [comment]
This issue duplicates [3759](https://github.com/magento/magento2/issues/3759). Closed as the duplicate

**Comment by NAVEEN456** [comment]
Hi Everyone,
                   I am using magento 1.9, i have created the configurable product which has simple products with the combinations of size and color. i have added the tier price to configurable product which is working fine. But My concern is i am not able to display tier price on the product page.
Can anyone suggest me how to solve this problem?

**Comment by Jeeva-Rathinam** [comment]
Anyone have the solution???

**Comment by Squawk1** [comment]
Hi @pioneerathletics
Sorry to bother you but do you have any info/example of how to get a Dynamic Tier Pricing for Configurable Products working in 1.9 (1.9.2.4 to be precise) as you said you had it working in 1.9?
Many Thanks

**Comment by jonsaf** [comment]
Sorry. I only know version 2 and above.

**Comment by pioneerathletics** [comment]
Hi @Squawk1 ,

Not a bother at all. I think the template I used, had some sort of dynamic tier pricing already built into it. You can find it at www.templatemonster.com - https://www.templatemonster.com/magento-themes/55765.html

**Comment by pioneerathletics** [comment]
@Squawk1 -Also keep in mind that as of Magento 2.1.12, dynamic tier pricing is already integrated in the core Magento code, so you don't need a separate template. I would suggest testing the latest 2.1 or 2.2 version instead, because it actually gives a better user experience.
