### ISSUE TITLE
Exception #0 (Exception): Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php on line 324

### ISSUE THREAD

**Issue by wangyonglin** [magento/magento2#5069]
# http://www.domain.com/adminhtml/cms/page/edit/page_id/1/key/75cbb9ce851059a821a9aed1c0c2fe756dc3f20280ccb439b8533d612f1b548f/

`Exception #0 (Exception): Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php on line 324

Exception #0 (Exception): Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php on line 324
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'DOMDocument::lo...', '/var/www/magent...', 324, Array)
#1 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php(324): DOMDocument->loadXML('')
#2 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php(393): Magento\Framework\View\Element\UiComponent\Config\DomMerger->createDomDocument('')
#3 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/Reader.php(60): Magento\Framework\View\Element\UiComponent\Config\DomMerger->merge('')
#4 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/Reader.php(47): Magento\Framework\View\Element\UiComponent\Config\Reader->readFiles(Array)
#5 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\View\Element\UiComponent\Config\Reader->__construct(Object(Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector), Object(Magento\Framework\View\Element\UiComponent\Config\Converter), Object(Magento\Framework\View\Element\UiComponent\Config\DomMerger))
#6 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Framewo...', Array)
#7 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Framewo...', Array)
#8 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/ReaderFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Framewo...', Array)
#9 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/Provider/Template.php(104): Magento\Framework\View\Element\UiComponent\Config\ReaderFactory->create(Array)
#10 /var/www/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Xhtml.php(78): Magento\Framework\View\Element\UiComponent\Config\Provider\Template->getTemplate(false)
#11 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/ContentType/Xml.php(66): Magento\Framework\View\TemplateEngine\Xhtml->render(Object(Magento\Ui\Component\Listing), false)
#12 /var/www/magento2/app/code/Magento/Ui/Component/AbstractComponent.php(155): Magento\Framework\View\Element\UiComponent\ContentType\Xml->render(Object(Magento\Ui\Component\Listing), 'templates/listi...')
#13 /var/www/magento2/app/code/Magento/Ui/Component/Wrapper/UiComponent.php(72): Magento\Ui\Component\AbstractComponent->render()
#14 /var/www/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(659): Magento\Ui\Component\Wrapper\UiComponent->_toHtml()
#15 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(555): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(516): Magento\Framework\View\Layout->_renderUiComponent('cms_page_listin...')
#17 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cms_page_listin...')
#18 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cms_page_listin...')
#19 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cms_page_listin...', true)
#20 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cms_page_listin...')
#21 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#22 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#23 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#24 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#25 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#26 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#27 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#28 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#29 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#30 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#31 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#32 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#33 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#34 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#35 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#36 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#37 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#38 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#39 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#40 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#41 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#42 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#43 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#44 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#45 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#46 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#47 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#48 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#49 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#50 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#51 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#52 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#53 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#54 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#55 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#56 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#57 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#58 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#59 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#60 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#61 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#62 /var/www/magento2/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#63 /var/www/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#64 /var/www/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#67 /var/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#68 {main}

`

**Comment by wert2all** [comment]
To allow us research the issue, please, provide description according to the template and provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
