### ISSUE TITLE
Can't sign licence/cla — Contributor License Agreement.

### ISSUE THREAD

**Issue by bordeo** [magento/magento2#5070]
I tried many times to sign in the licence/cla — Contributor License Agreement but it doesn't work.

licence/cla — Contributor License Agreement is not signed yet.

**Comment by orlangur** [comment]
What exactly does not work? Could you record a screen cast maybe. As there is nothing special with it - it is just a usual GitHub OAuth application.

**Comment by bordeo** [comment]
This is what happen

http://sendvid.com/bcxcdjtz

**Comment by evgk** [comment]
@bordeo, did you do any force-push there? I had a similar issue here:
https://github.com/magento/magento2/pull/4864
At first I could sign it, think it broke after I did a force push - but I'm not sure
They're using that one it seems:
https://github.com/cla-assistant/cla-assistant
So maybe its a bug there

**Comment by bordeo** [comment]
I don't make any force-push. Is very strange

**Comment by hostep** [comment]
I've also seen it happen when you commit something using an e-mail address which isn't associated with your github account, maybe that's the problem?

**Comment by ghost** [comment]
Guys, 
I have implemented solutions for REST API for Review/Rating  and REST API for Wishlist but whenever i try to sign CLA  it always return with "licence/cla — Contributor License Agreement is not signed yet".

[ Added Review APi #5079](https://github.com/magento/magento2/pull/5079) and [ Addition of wishlist functionality to api #4877](https://github.com/magento/magento2/pull/4877)

**Comment by ajay-ipragmatech** [comment]
#5079 
and 
#4877

**Comment by hostep** [comment]
@ajay-ipragmatech: can you read my comment above? In your case, your commits aren't made with an email address associated to your github account, so this is most likely the issue.
I'm not sure what the best way to solve this is, either assign that email address to your github account (it can have multiple ones associated at once). Or recreate your commits using the email address associated to your @ajay-ipragmatech account, or create a new github account for that particular email address and sign the CLA while you are logged in with that new github account.

**Comment by ghost** [comment]
**@hostep:** I have recommitted my changes with the same id but i am still not able to sign the document still having the same issue.Could you please look at this again and suggest me any other way to resolve the issue ?

**Comment by bordeo** [comment]
@hostep i made the commit via github site for not making mistake. 
I had 2 email associated to my account so i delete the secondary but i can't still accept the CLA

**Comment by hostep** [comment]
For your information: I'm not a member of the Magento 2 team, so I can't verify anything. Just wanted to share my experience from a couple of months ago :)

@ajay-ipragmatech: I think you'll have to delete your older commits somehow (because they still belong to your PR), or just create a new PR.

**Comment by iazel** [comment]
Same problem here! I've made the PR trough github, so the ID should be the same

**Comment by andimov** [comment]
@bordeo
Thank you for reporting!
Do you have got a solution for this issue?

**Comment by bordeo** [comment]
@andimov 
no i didn't find any solution. One week ago my pull request got Contributor Licence Signed. I think magento started process all pull request and issue.

**Comment by andimov** [comment]
@bordeo
Ok, thank you!

**Comment by ghost** [comment]
Need add local git config email to github account (git config --global user.email)
