### ISSUE TITLE
Exception during refund an order that contains Physical and Virtual Gift Cards

### ISSUE THREAD

**Issue by virtual97** [magento/magento2#5074]
## Steps to reproduce
1. Install 2.0.6 Magento version.
2. Add Physical Gift Card to the cart (sku=243-MB04).
3. Add Virtual Gift Card to the cart (sku=243-MB09).
4. Place order using "PayPal Express Checkout".
5. Go to Admin panel and create an invoice for this order.
6. Create online refund for the order.
## Expected result
1. The Credit Memo was created successfully for the order with an appropriate successfully message.
## Actual result
1. The Credit Memo was created, but exception message appeared: 
   [exception_refund.txt](https://github.com/magento/magento2/files/320166/exception_refund.txt).

**Comment by orlangur** [comment]
GiftCard module does not seem to be a part of Community Edition. Please report this issue in partner portal.

**Comment by wert2all** [comment]
Please report this issue in partner portal.
