### ISSUE TITLE
[ CE 2.0.7] Sales order item -Configurable product  Qty_Invoiced issue

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5076]
## Steps to reproduce
1. Install Magento  `2.0.7` .
2. Add a Configurable Product to the cart.
3. Place an order with 2 quantities
- **First Step :** 

invoice just 1 quantity
- **Second Step :** 

invoice the remaining quantity
## Expected result
1. in the table sales_order_item there are 2 sales order items of products ( The configurable and the sample)
- **First step :**
- ... the qty_invoiced of the configurable product is 1 and the qty_invoiced of the sample product is 1
- **Second step :** 
-  the qty_invoiced of the configurable product is 2 and the qty_invoiced of the sample product is 2
## Actual result
1. in the table sales_order_item there are 2 sales order items of products ( The configurable and the sample)
- **First step :** 
1. ... the qty_invoiced of the configurable product is 1 and the qty_invoiced of the sample product is 2
- **Second step :** 
1. the qty_invoiced of the configurable product is 2 and the qty_invoiced of the sample product is 4

![snapshot5](https://cloud.githubusercontent.com/assets/13301885/16149602/83115dfc-3481-11e6-9585-87f0e8ae1ba7.png)

**Comment by Andrii-Deineha** [comment]
@Dayssam Hi, unfortunately, I can not reproduce this issue. Is this issue actual for you?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
