### ISSUE TITLE
Store View (language) switch leads to 404

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5077]
## Steps to reproduce
1. Install Magento 2.0.7
2. Add several store views e.g. "English", "French", "German"
3. Create a CMS page for "English" store view - e.g. "About Us" with Url Key `about-s`
4. Now create the same CMS page for "French" store view e.g. "À propos de nous" with Url Key `a-propos-de-nous`
## Expected result
1. I can open "About Us" page
2. I am redirected to homepage when I switch store view (language) as CMS pages are not linked n any way
## Actual result
1. I can open "About Us" page
2. 404 page is show when I switch store view (language)

Product categories are general with possibility to translate them in each store view but CMS pages does not work like that. For CMS pages I would expect that user is redirected to homepage as Magento2 can't know which pages represent the same content in different store view.

One way to resolve this would be to use the same Url Key in all store views for the same page but that's a hack rather then a solution (also SEO suffers).

Is there at least a way how to fix this for now?

**Comment by Ctucker9233** [comment]
I've had a similar issue, so I am wondering if you have tried enabling add store code to url and disabling redirect to base url. This way magento knows what content to display.

**Comment by slopukhov** [comment]
Hi @werdlv 

Thank you for reporting the issue. It is reported as `MAGETWO-57337` internally.

**Comment by magento-engcom-team** [comment]
@werdlv, thank you for your report.
We've created internal ticket(s) MAGETWO-57337 to track progress on the issue.

**Comment by tolyantrain** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
Hi @werdlv

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@werdlv, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by jayanta88** [comment]
Any solutions here? I'm facing the same issue in Magento 2.3.3
If you are on a product page and that product is not visible in other store views, then it will show a 404 page.

Please let me know.

Thanks

**Comment by mnowakCode** [comment]
I have the same problem, is there anyone who can help us?

**Comment by DegrizNet** [comment]
This problem is still in latest version. Workaround is to create url rewrites but manually doing that for couple of thousand sku is impossible.
