### ISSUE TITLE
I can't subscribe on admin user delete event

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#5080]
## Steps to reproduce
1. M 2.0.7
2. create listener of event "delete admin user"
   `<event name="admin_user_delete_after">
       <observer name="salesrep_delete_user" instance="IWD\SalesRep\Observer\Backend\AdminUserDeleteAfterObserver"/>
   </event>`
## Expected result
1. I should have opportunity to subscribe on event of deleting admin user using event prefix "admin_user" and base event name "_delete_after"
## Actual result
1. event "admin_user_delete_after" is not dispatched, cause delete() method of User's resource model is overriden from base resource model AbstractDb, and methods beforeDelete() and afterDelete() of User model are not being called.
2. https://drive.google.com/file/d/0B6jlEIvY3J2OUl85SXlwckR0Q0E/view?usp=drivesdk

**Comment by mhabou** [comment]
I think i have the same problem with the model **sales_creditmemo_item**

with the 2 events : **_save_before** & **_save_after**

**Comment by orlangur** [comment]
In general, it is not recommended to create Event Observer whenever it is possible to implement an interceptor.

Do you see why interceptor is not applicable in this scenario? Me not, but I didn't look deeply.

**Comment by katesuykovskaya** [comment]
@orlangur yes, I used plugin to subscribe on event "user after delete" since "admin_user_delete_after" event is not dispatched. 
However if this event is skipped on some purpose, I would like to know the reason why

**Comment by orlangur** [comment]
Mentioned events are only dispatched in model, not resource model: `\Magento\Framework\Model\AbstractModel::beforeDelete`.
