### ISSUE TITLE
[ CE 2.0.7 ] - Cancel order with Bundle product

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5086]
## Preconditions
1. Install Magento 2.0.7

## Steps to reproduce
1. Add bundle Product to the cart.
2. Place the order
3. Cancel the order
## Expected result
1. In the table sales_order_item .. the qty_canceled must changed
## Actual result
1. In the table sales_order_item qty_canceled still 0

**Comment by Mulderua** [comment]
Hi @Dayssam !
Internal ticket MAGETWO-54626 was created.
Thank you for the report.

**Comment by magento-engcom-team** [comment]
@Dayssam, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
