### ISSUE TITLE
Faulty Inventory Management 

### ISSUE THREAD

**Issue by ankitce** [magento/magento2#5088]
## Steps to reproduce
1. Start two different sessions 
2. Whole product quantity added in to cart from both end
3. Go to Check out & place order
## Expected result

One of the orders should be failed Or one of the shipments should be failed.
## Actual result
1. Both could successfully place orders
2. Shipments for both of the orders were generated successfully

How is it possible to fulfill both of the orders, considering the store manages stock ?

**Comment by mhabou** [comment]
@ankitce 
I can't understand Magento Stock Management

When you place the order Magento automatically decrements the  product quantity
When you make a shipment there is no stock movement.
When you cancel the order there is no stock movement.

**Comment by aoldoni** [comment]
Hi @ankitce / @Dayssam ,

I just tested this in default Magento 2.0.5, with simple products, default attribute set, and could not reproduce both issues above.
- For "Faulty Inventory Management":
  1) Start two different sessions.
  2) Whole product quantity added in to cart from both end. In my case the backend quantity was 2, so each frontend session had 2 items in the cart.
  2) Go to Check out & place order.
  **RESULT**: The first order could be placed, but not the second. The second one failed with insufficient inventory.
- For the "When you cancel the order there is no stock movement.":
  **RESULT**: Items returned to the inventory after the order was cancelled.

Thanks.

**Comment by ankitce** [comment]
We tested it with Magento version 2.0.7 with default attribute set and default configurations (i.e. manage stock = Yes). 
We added a product with quantity '1'.
When we placed orders from two different systems, both could place order. 
Also, shipments for both of the orders could be generated successfully.

**Comment by mhabou** [comment]
Hi @aoldoni ,
- For "When you cancel the order there is no stock movement.", i tested the configurable product " Cassius Sparring Tank-S-Blue " 

When you cancel the order there is no stock return.

Magento CE 2.0.7

**Comment by aoldoni** [comment]
Hi,

Just a note, my test was using a single website.
Are you using multiple websites setup in Magento?

Thanks.

**Comment by mhabou** [comment]
@aoldoni 

i'm using a single website

**Comment by aoldoni** [comment]
I was able to reproduce the problem with multiple Websites configured, due to the problem reported in https://github.com/magento/magento2/issues/1002

**Comment by mhabou** [comment]
i'm using the default sample data

**Comment by jonpday** [comment]
@aoldoni @ankitce thanks for taking the time to raise and verify this issue. just wondering whether you've seen the same behaviour in 2.1.0 or 2.1.1 ? I don't see anything relevant in the release notes (http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.1EE.html and http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.0EE.html). thanks!

**Comment by smoskaluk** [comment]
@ankitce Unfortunaly I could not reproduce this issue.  May you plese advise if this problem is still relevant for latest release Magento 2?
