### ISSUE TITLE
confusing message when trying to update from M2 2.0.7 to M2 2.1.0-rc3

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5093]
I am getting the following confusing message when trying to update from M2 2.0.7 to M2 2.1.0-rc3:

Completed! You need to resolve these issues to continue. Check Updater Application Availability Updater application is available.

Check Cron Scripts Cron script readiness check passed.

Check Component Dependency We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages.

Problem 1 - Installation request for magento/product-community-edition 2.1.0-rc3 -> satisfiable by magento/product-community-edition[2.1.0-rc3]. - magento/product-community-edition 2.1.0-rc3 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version does not satisfy that requirement.

For additional assistance, see component dependency help .

PHP Version Check Your PHP version is correct (7.0.7-4+deb.sury.org~trusty+1).

PHP Settings Check Your PHP settings are correct.

PHP Extensions Check You meet 15 out of 15 PHP extensions requirements. Show detail

As you can see my php 7.07 version check passes and all necessary extensions are available, but, the component dependency check is barfing on my php version. Not sure how to address this.

As an aside, the same php version worked just fine with upgrading to 2.0.7 and all upgrades to this point. I haven't made any changes to any php related files at all.

Any help would be greatly appreciated.

**Comment by buskamuza** [comment]
Hi @dgarbe , the issue is that your current PHP version satisfies installed Magento, but new version of Magento requires a higher version of PHP.
So to be able to upgrade you need PHP version that is 5.6.x, 7.0.2 or >=7.0.6

**Comment by ghost** [comment]
So it would seem. However, my php version is 7.0.7 and the updater verifies that version and that all 15 required extensions are installed.

**Comment by ghost** [comment]
> So to be able to upgrade you need PHP version that is 5.6.x, 7.0.2 or **>=7.0.6**
> 
> PHP Version Check Your PHP version is correct (**7.0.7**-4+deb.sury.org~trusty+1).

So what  am I not understanding here? Is composer calling a different version of php? And, if so, how would I verify that?
