### ISSUE TITLE
Cybersource X-Frame denied issue

### ISSUE THREAD

**Issue by nagrgk** [magento/magento2#5094]
I have enabled cybersource , adding only merchant Id and secret key. It will start loading secureacceptance in iframe.

questions: When I have not added profile id, why secureacceptance loaded?
why iframe - denied ? Is ajax requests tested ? when will wsdl request works?
what we dont want SA and need wsdl? any config for that?

![cybersource_issue](https://cloud.githubusercontent.com/assets/2674815/16182607/a08c3af4-36da-11e6-8302-62da50f3205b.PNG)

Confusing magento2

**Comment by alena-marchenko** [comment]
Hi @nagrgk 

You need to enter Merchant ID and Access Key for cybersource in Magento configuration in order to be able to use it.  Please report Enterprise Edition issues through [support ticket](https://magento.com/support/enterprise-edition) to ensure faster resolution.

**Comment by nagrgk** [comment]
this is non-sence answer. Who will try without merchant id and access key ?

FYI, I have already entered these information. Looks like some issue with your implementation. Please look into this asap. I have raised support ticket and they waiting for some tech support from 2 weeks which is not good support enterprise purchase.

**Comment by nagrgk** [comment]
You didnt know how to answer or dont know answer, thats why closed issue? Can you please reopen? Its very critical issue and need to be resolved asap.

**Comment by YevSent** [comment]
This issue is closed because public Github only for CE version of Magento. As said my colleague, to resolve your problem, please, report via [EE Support](https://magento.com/support/enterprise-edition) this issue.
