### ISSUE TITLE
Wrong tax calculation?

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5098]
![screen](https://cloud.githubusercontent.com/assets/16196483/16187366/1e1bfee2-36d0-11e6-801c-4ca3eee2296f.png)
## Steps to reproduce

Tax settings: Incl. Tax
Tax rate: 19% (Germany)
## Expected result
1. Order total incl. tax: 80 Euros
2. Tax: 12,77310 Euros
## Actual result
1. Order total incl. tax: 80 Euros
2. Tax: 12,80 Euros

The tax must be 12,77 Euros not 12,80 Euros.

This bug also is related to the table rates shipping:
If we have a table rate for DEU (Germany 19% tax):

Country,Region/State,"Zip/Postal Code","Order Subtotal (and above)","Shipping Price"
DEU,_,_,0.0000,3.7500
DEU,_,_,67.2269,0.0000

Meaning all orders with 80 Euros (incl. 19% tax) and bigger have the shipping costs 0,00 Euros this does not work properly.
A order with 80 Euros total (incl 19% tax) is not shown with the right shipping fee of 0,00 Euro but 3.75 in this case.

**Comment by choukalos** [comment]
Hi @andidhouse what is your tax calculation set to?  Are you using 'Calculate on Total'?  It looks like you're using calculate on Unit.  Can you share your tax configuration?

For the interaction with table rates that seems only related to the excluding tax amount that the system sees.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
