### ISSUE TITLE
Upgrade magento - freeze

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5099]
Hi,

I currently have 2.0.4 version of magneto 2 on localhost, when i am trying to upgrade it to 2.0.6 via websetup wizard system upgrade, it passed all the readiness check and when i click on next for upgrade, it does not show any progress on console log and just shows me update pending?. How long does it take? or does it shows any progress on console log?.
![system upgrade](https://cloud.githubusercontent.com/assets/19605497/16189838/4207cad0-36d4-11e6-9c5a-1715dc93e1ae.png)

attaching a image for ref.

**Comment by WebWeave** [comment]
Your running it at localhost maybe your enviroment doesnt have enough cpu speed or something?

**Comment by nmallepally** [comment]
No, its i7 processor with 16 GB ram. I have allocated 2gb for php memory.

**Comment by ghost** [comment]
The setup cron job might not be running. Do you have logging enabled? If so check the log.

`crontab -u <magento file system owner> -l` shows the current cron job defined for the Magento file system owner. Please paste the output here.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by nmallepally** [comment]
Hi ,
Sorry for delay, i was trying to update to magento 2.1 it freezes again and i rolled back to 2.0.7 due to incomplete upgrade, when i click on web setup wizard , it still shows me a freezed output page.(attaching an image for reference)
![freezes websetup wizard](https://cloud.githubusercontent.com/assets/19605497/17099047/c674a802-525d-11e6-8cf3-c03d0fa62afa.png)

I ran crontab, here is the result.
1 \* \* \* \* /opt/plesk/php/7.0/bin/php -C /opt/plesk/php/7.0/etc/php.ini /var/www/vhosts/edwia.eu/httpdocs/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/vhosts/edwia.eu/httpdocs/var/log/magento.cron.log
1 \* \* \* \* /opt/plesk/php/7.0/bin/php -C /opt/plesk/php/7.0/etc/php.ini /var/www/vhosts/edwia.eu/httpdocs/update/cron.php >> /var/www/vhosts/edwia.eu/httpdocs/var/log/update.cron.log
1 \* \* \* \* /opt/plesk/php/7.0/bin/php -C /opt/plesk/php/7.0/etc/php.ini /var/www/vhosts/edwia.eu/httpdocs/bin/magento setup:cron:run >> /var/www/vhosts/edwia.eu/httpdocs/var/log/setup.cron.log
