### ISSUE TITLE
Category page produces notice about swatches attributes

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#5103]
## Steps to reproduce
1. Install Magento 2.0.7 or earlier
2. Make sure that you have any attributes as text swatches
3. Visit category page where this product belongs and observe notice
## Expected result
1. Category page with products displayed
2. ...
## Actual result
1. Error message appears: "Notice: Undefined variable: result in vendor/magento/module-swatches/Block/Product/Renderer/Listing/Configurable.php on line 49".

Actual code is

``` php
protected function getSwatchAttributesData()
    {
        $swatchAttributeData = parent::getSwatchAttributesData();
        foreach ($swatchAttributeData as $attributeId => $item) {
            if (!empty($item['used_in_product_listing'])) {
                $result[$attributeId] = $item;
            }
        }
        return $result;
    }
```

where it should be 

``` php
protected function getSwatchAttributesData()
    {
       $result = [];
        $swatchAttributeData = parent::getSwatchAttributesData();
        foreach ($swatchAttributeData as $attributeId => $item) {
            if (!empty($item['used_in_product_listing'])) {
                $result[$attributeId] = $item;
            }
        }
        return $result;
    }
```

**Comment by redboxmarcins** [comment]
Looks like it is fixed in develop branch but not in 2.0 branch

**Comment by redboxmarcins** [comment]
Actually it was fixed here 
MAGETWO-47959: Prevent getSwatchAttributesData() function from triggering a PHP notice

but never merged into 2.0

See commit: 60c587ec92aed8d421c5fbb48337409fcf0e3153

**Comment by wert2all** [comment]
Thank for reporting. We created internal ticket MAGETWO-56976.

**Comment by magento-engcom-team** [comment]
@redboxmarcins, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
