### ISSUE TITLE
translate error sales_rule_form.xml

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5104]
app/code/Magento/SalesRule/view/adminhtml/ui_component/sales_rule_form.xml

line 54:
<item name="label" xsi:type="string">Currently Active</item>

miss: translate="true"

**Comment by Mulderua** [comment]
Hi @ideirj, thank you for the report.
Internal ticket MAGETWO-54609 was created.

**Comment by magento-engcom-team** [comment]
@ideirj, thank you for your report.
The issue is already fixed in 2.2.0
