### ISSUE TITLE
Admin panel not working fine after installation of custom module...

### ISSUE THREAD

**Issue by ShubhSikarwar** [magento/magento2#5108]
Steps to reproduce
1. Install Magento 2.1 rc3 and install any custom module

Expected result
1. It should display in proper design but not displaying.
Actual result
1. Displaying all fields label in single line (Meta title , Meta Keywords all are coming in single line).
   How to fix this issue?
   ![screenshot from 2016-06-20 16 51 13](https://cloud.githubusercontent.com/assets/8413090/16192487/4412b28a-3707-11e6-8acf-c9a7ddaf9c91.png)

**Comment by andimov** [comment]
@ShubhSikarwar 
Thank you for reporting this issue!

Do you have any update for it?
It's look like broken template or js.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
