### ISSUE TITLE
Content pages and block admin panel just loading not showing content

### ISSUE THREAD

**Issue by awwm** [magento/magento2#5109]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by wert2all** [comment]
To allow us research the issue, please, provide concrete steps for re-producing this bug.

**Comment by awwm** [comment]
sorry i forgot to close the issue i have fixed
