### ISSUE TITLE
"Consumer is not authorized to access %resources" after some hours of Magento 2.0.5 Setup

### ISSUE THREAD

**Issue by mohanbmahajan** [magento/magento2#5110]
For Magento ver. 2.0.5 I am having following issue,

I am using following endpoint to list the customers,
For this I am using Postman - REST Client 0.8.4.17 of crome using OAuth 1.0 Authorization
http://< magento_host >/rest/V1/customers/search?searchCriteria[page_size]=100

Along with the above request I am providing,
1. Consumer Key
2. Consumer Secret
3. Token
4. Token Secret
These I get from Integrations Extensions of System in Admin Panel of Magento.

The problem I come across is I am able to get the list of customers for some time (~= 2 hrs) & after this I am continuously getting following,
{
    "message": "Consumer is not authorized to access %resources",
    "parameters": {
        "resources": "Magento_Customer::customer"
    }
}

**Comment by oleg-onufer** [comment]
Hi @mohanbmahajan.
Please add more details to your description of the steps you followed when identifying this issue. 
Screenshots would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
