### ISSUE TITLE
Reference Cm_Cache_Backend_Redis

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#5113]
Hi,

Cm Cache Backend Redis is installed into lib\internal. I want to make use of it in my code but the class is not found.

$cmCache = new \Cm\Cache\Backend\Redis($options);

How do I go about referencing something in lib\internal?

**Comment by melnikovi** [comment]
@craigcarnell what version of Magento do you use? In latest release this library removed from code base and being installed as package. Anyway, try this $redis = new Cm_Cache_Backend_Redis($options). Let me know if it doesn't work

**Comment by cscd98** [comment]
@melnikovi That didn't work but:

$cmCache = new \Cm_Cache_Backend_Redis($options);

worked fine! Cheers 👍
