### ISSUE TITLE
[ CE 2.0.7] - Reorder bug with Configurable product

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5114]
## Steps to reproduce
1. Install Magento 2.0.7
2. Add 2 Configurable Products to the cart
- MJ01-XS-Orange
- MJ01-M-Red

3 / Place the order

![snapshot8](https://cloud.githubusercontent.com/assets/13301885/16196926/7c2235e6-36ef-11e6-8274-9fc8483e222a.png)
1. Click on Reorder
## Expected result
1. Have the same order with 2 products
- MJ01-XS-Orange
- MJ01-M-Red
## Actual result
- 1st result: 

![snapshot10](https://cloud.githubusercontent.com/assets/13301885/16197263/f2f116fa-36f0-11e6-8e79-ebc85db4ed84.png)
- 2nd result: 

When i go back and reorder it again ( It takes the 2 products above in the cart (but hidden) & add the actual order)

![snapshot11](https://cloud.githubusercontent.com/assets/13301885/16197516/e7f75e8e-36f1-11e6-9880-8c671c3e04de.png)

**Comment by shlaing** [comment]
Hello Everyone ! I got this problem too. Magento Version - 2.0.7

It is not only Configurable Products but also Products with Option Value.

**Comment by IlnitskiyArtem** [comment]
@Dayssam, Thanks for the feedback.
I reproduced your case just on Magento 2.0.7 version, but on the latest Magento released versions this issue was fixed.

**Comment by veloraven** [comment]
I'm closing this issue as it was fixed.
If you can still reproduce this issue, please create a new GitHub issue report.
