### ISSUE TITLE
User update first name it not reflect on welcome header.

### ISSUE THREAD

**Issue by wattanak** [magento/magento2#5117]
When user login and update their first name it should reflect on welcome header. It will work after use log out and login again. That is a bug. Please fix it.

Thank you.
<img width="934" alt="screen shot 2016-06-20 at 11 32 47 am" src="https://cloud.githubusercontent.com/assets/3372666/16205889/cf0df232-36da-11e6-8bc9-02ae51f9d5d2.png">

**Comment by duhon** [comment]
Hello @wattanak 

To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
