### ISSUE TITLE
category url not saving after changes

### ISSUE THREAD

**Issue by fgpasa** [magento/magento2#5118]
Hi

Im using 2.06 version;

When I created category urls on a development folder in my hosting account I made a mistake and include

https://www.sitename.com/catergory-name

instead of just putting

category-name

When I changes it to the second it gives me a message stating the url already exist and does not let me save it.  See screen shot. 
<img width="1188" alt="screen shot 2016-06-19 at 6 31 41 pm" src="https://cloud.githubusercontent.com/assets/16530868/16213853/9fb56a6a-3720-11e6-848a-b52eb7d963a0.png">

**Comment by lijithmg** [comment]
Try some of the solutions added to https://github.com/magento/magento2/issues/1471

**Comment by slopukhov** [comment]
@fgpasa 
Thank you for reporting!
I can't reproduce this issue.
Can you check this issue on 2.0.last version, and can you check that you does not have other category with same url?

**Comment by andimov** [comment]
@fgpasa 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
