### ISSUE TITLE
Products per Page on List Allowed Values does not work

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#5119]
## Steps to reproduce
1. Go to Stores > Configuration > Catalog  > Catalog 
2. In the Products per Page on List Allowed Values field, enter 25,60,90 for the value.
3. Click Save Config
4. Go to a product list on the front end.  Switch to list mode.
## Expected result
1. On the product list page in list mode, the "Show per page" drop down menu should display the values 25, 60, and 90.
## Actual result
1.  On the product list page in list mode, the "Show per page" drop down menu displays the values 10, 20, and 50.

I believe Magento 2 is pulling these values from defaultAvailableLimit which is found in this file

vendor/magento/module-catalog/Helper/Product/ProductList.php

**Comment by antboiko** [comment]
Hi @orbitrod , thanks for reporting. The issue was fixed internally and should be included in 2.1 release.

https://github.com/magento/magento2/issues/3861

Best,
Anton.

**Comment by orbitrod** [comment]
OK great.  I went ahead and applied the fix in commit   895efff and it fixed the problem.

**Comment by bernykosh** [comment]
i am having the same issue
