### ISSUE TITLE
Magento 2.0.7 version icons are not working properly if you click any icons nothing as working please helpme out of this.

### ISSUE THREAD

**Issue by shintow123** [magento/magento2#5120]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by mhabou** [comment]
@shintow123
Reinstall it and make sure you followed the installation instructions

**Comment by wert2all** [comment]
To allow us research the issue, please, provide description according to the template.

Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
