### ISSUE TITLE
Network error : 504 Gateway timeout 

### ISSUE THREAD

**Issue by viken-tops** [magento/magento2#5121]
Steps to reproduce

Install Magento 2.0.7 CE

Expected result
magento 2 admin should work without any issue

Actual result

magento 2 admin is having issue with .js & .css files loading. showing 504 gateway timeout error

**Comment by wert2all** [comment]
To allow us research the issue, please, provide more concrete steps for reproduce.

Looks like your infrastructure issue.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
