### ISSUE TITLE
Backend Admin missing CSS

### ISSUE THREAD

**Issue by commalex** [magento/magento2#5124]
Create a new Magento store.
Add an additional admin user.
Login with new user credentials.

Expected result
Admin backend to look like initial install user

Actual result
Backend is all text based, missing CSS etc

**Comment by commalex** [comment]
Oh, I have checked permissions and the same happens on a clean install.  Running v2.0.7

**Comment by magento-engcom-team** [comment]
@commalex, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
