### ISSUE TITLE
Issue with setting fields in payload for POST "/v1/invoices" api

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#5125]
Hi there, 
I have an issue regarding setting fields in invoice create API
POST "V1/invoices" 
with payload 
{
"entity": {
"base_discount_tax_compensation_amount": null,
"base_shipping_discount_tax_compensation_amnt": null,
"discount_tax_compensation_amount": null,
"order_id": 58,
"shipping_discount_tax_compensation_amount": 0,
"total_qty": 2,
"grand_total": 155,
"subtotal": 150,
"items": [
{
"base_discount_tax_compensation_amount": null,
"discount_tax_compensation_amount": null,
"order_item_id": 74,
"sku": null,
"qty": 56,
"row_total": 150,
"tax_amount": 152,
"discount_amount": 23,
"price": 154
}
]
}
}

 Here I am setting fields "grand_total", "subtotal" on body level and fields "qty", "row_total", "tax_amount", "discount_amount" inside items array.
As a API user, I am expected to pass Magento API with orderId, Items object array with order_item_id and qty, shipping cost ( again validation where this cost should be less then order shipping cost ) , 
but if I just provide these fields , they are displayed as '0' in invoice created on admin panel

**Comment by karanbhomiagit** [comment]
I am facing the same issue. This is definitely a bug in the code.

**Comment by srinivasanithin** [comment]
Those fields should be picked up from the magento sales order rather than we giving it on API. There are serious issues leaving these fields to be given by API user. Once an order is capture for full order with incorrect amount(less than order amount) then there is no way to capture again without re-authorizing the card for customer. Please fix this bug. Magento should be pulling price from order and calculating the row total, grand total rather than api user giving those details

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Issue-with-setting-fields-in-payload-for-POST-quot-v1-invoices/idi-p/45086).
