### ISSUE TITLE
Cannot load resource element 'AN'  in Catalog > Products 

### ISSUE THREAD

**Issue by bhaveshsurani** [magento/magento2#5127]
Magento 2.0.7
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Do login to admin panel.
3. Navigate to Catalog > Products
## Expected result
1. It will going to show product listing
## Actual result
1. Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in F:\xampp\htdocs\magento27-v1\vendor\magento\framework\Locale\TranslatedLists.php on line 206
2. [Screenshot, logs]
   Here attached screenshot for the same.
   ![magento27-v1_dev_admin_2j3w1s_catalog_product_index](https://cloud.githubusercontent.com/assets/1414787/16227347/ab9c3306-37cd-11e6-9e77-78523a80467e.png)

**Comment by duhon** [comment]
Hello @bhaveshsurani 

Please clarify you are using version 2.0.7 or latest version from branch develop?

**Comment by bhaveshsurani** [comment]
I have used 2.0.7

**Comment by pyrostriker** [comment]
When installing magento 2 what php version were you using?

I had this exact error because when I was installing magento 2 my wamp server was running php 7.0.6.  I then downgraded to php 5.6.23 and started receiving this error.  Restoring php version 7.0.6 fixed the problem.

**Comment by bhaveshsurani** [comment]
i am using php 5.6.21

**Comment by mani-repos-link** [comment]
I have same issue on latest version  CE-2.1.0... Please help me.. save my life

**Comment by kumatozz** [comment]
Any update? I have the same issue and I have been trying to fix it for 2 days - no luck.... We are using PHP 7.0.9 and Magento 2.0.7

**Comment by mani-repos-link** [comment]
I have resolved this problem.. reinstalling magento2.7 after full installation...then  i run following commands in magento root directory : 

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

**Comment by kumatozz** [comment]
We changed version of PHP back to 7.0.5 and the problem was gone.... the reason we wanted to use higher version of PHP was that we were going to update magento to 2.1 snd the checker said us that 7.0.5 is not suitable version...

**Comment by henk-webleads** [comment]
Probably NOT the best temporary fix but from the table 'directory_country' I removed the record with country id='AN' (MySql).  'AN' = Netherlands Antilles. I even could not configure the stores in the Backend of Magento so that's why I removed this record.

I did this with Magento V2.1 CE. I'm running WAMP, PHP 5.6.25 and MySql 5.6.17.

**Comment by PaulodoPorto** [comment]
Hello Guys, 
Today is 13:11 09.03.2017 and i use:

Magento CE Ver: 2.1.5 Apache 2.4, Win 7, MySQL 5.7.17 with sample data is installed.
magento deploy:mode:set developer

As @henk-webleads mentioned, i don´t know if it is the perfect solution, but for me it´s the ideal solution.
It Works!

Befor i couldn´t acess Adminpanel > Produts > Catalog and Adminpanel > Stores > Configuration

Thank you!

**Comment by melwinVincent** [comment]
Hey guys,
@henk-webleads : This solution worked for me.
I'm not sure whether this is the right solution or not, but it just simply worked.

**Comment by magento-engcom-team** [comment]
@bhaveshsurani, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by jatinkumar09** [comment]
Hi 
I am facing same issue installed magento 2.2.5 using php 7.1.19

**Comment by kovvadayogesh** [comment]
I am facing the same issues for Magento ver. 2.2.9

**Comment by elrosi** [comment]
I am facing the same issues for Magento ver. 2.3.3, Win 10, Xampp, PHP: 7.2.16, 10.3.14-MariaDB
Help from henk-webleads has helped.
