### ISSUE TITLE
Possibility of a short route with address bar of the browser

### ISSUE THREAD

**Issue by 12th** [magento/magento2#513]
Hello. I apologize in advance if this functionality is. I would like to make a suggestion on the routes. It is very lacking in the short address with address bar of your browser. Now addressing Magenta works of principle:
http:// domain.com / module / controller / action
http:// domain.com / checkout / cart / updatePost
It would be great if  had the opportunity to register routes for specific modules, as is done, for example, in the framework Kohana:

Route::set('default', '(controller(/action(/id)))')
->defaults(array(
    'controller' => 'welcome',
    'action'     => 'index',
));

Route::set('cart', 'cart(/param1)')
->defaults(array(
    'directory' => 'checkoutDirectory',
    'controller' => 'cartController',
    'action'     => 'indexAction',
));

PS: example is slightly modified in order to convey the essence

And then when you click on the address:
http:// domain.com / cart

working out the controller
http:// domain.com / checkout / cart / index

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23155

**Comment by piotrekkaminski** [comment]
This proposal is currently not our priority. It was added to the backlog. Similar functionality can be achieved with server rewrites if needed.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Possibility-of-a-short-route-with-address-bar-of-the-browser/idi-p/46799).
