### ISSUE TITLE
Add module version for module dependencies

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#5130]
Feature request:

Also provide a minimum module version when you declare module dependencies. For example:

```
<module name="Vendor_Module" setup_version="1.0.0">
    <sequence>
        <module name="Vendor_Dependency" setup_version="1.0.12"/>
    </sequence>
</module>
```

This way you can make sure that the module your module depends on is (at least) the correct version.

**Comment by mhabou** [comment]
@kanduvisla : great suggestion

**Comment by Vinai** [comment]
The `<sequence>` nodes in the `module.xml` are soft dependencies and (as far as I know) only affect the module load order in `app/etc/config.php`.
Hard dependencies and versions should be listed in the `composer.json` file.

**Comment by Vinai** [comment]
Closing as the feature already exists in a different form.
