### ISSUE TITLE
[CE 2.1 RC2] Product prices not scoped to Website - scoping seems to be at store view level

### ISSUE THREAD

**Issue by develpr** [magento/magento2#5133]
## Steps to reproduce
1. Install Magento CE 2.1 RC2.
2. Install Magento CE 2.1 Sample Data
3. Create a second Website, Store, and 2x Store View (in my case **Canada Website, Canada Store, Canada English**, and **Canada French**)
4. Go to **Stores > Configuration > Catalog > Catalog** and set the **Store Price Scope** from _Global_ to _Website_
5. Edit any simple product (I used 24-WG084 which is the Yoga Brick from the sample product data) and enable the product on both websites (on the product edit admin page, undernear the **Product in Websites** options select both websites (i.e. both the default and Canada Website)
6. Switch to one of the new second store view scopes (i.e. Canada English) and change the price to something DIFFERENT from the value in the default store and note this price. Then change to the other store scope (i.e. Canada French) and change the price to something different then the first change. i.e. something like **Default OOTB store view:** $5, **Canada English:** $6, **Canada French:** $7
7. _Optional: Run the indexer / clear cache / etc just to make sure it's not an index issue - this won't have any effect though, but mentioning it here just to cover bases and let you know I did try this_
8. Switch between the different scopes available for the product and note that the price is different for each store view
## Expected result
1. Price for the default store view scope should be different then the price for the new 2 x store views. I.e. the "default" price would be $5 in our case, and both Canada English and Canada French woudl both have the same price, regardless of which numbers you entered.
2. Changing the price in any scope under website should update the price across the board for any stores / store views in that website scope
3. **Tested on Magento 1.x and this works as expected - i.e. it works correctly, and differently then Magento 2.1 RC2**
## Actual result
1. Price is different on the store view level. Entering a price of $6 for Canada English in my example, and a price of $7 for Canada French, results in the prices being 6 and 7. i.e. they are different on the store view level. 
2. ![show_price_differences_magento2_store_view](https://cloud.githubusercontent.com/assets/3022076/16233331/99fe2af8-3793-11e6-8b5b-1e8080c199db.jpg)
3. Re-indexing / etc doesn't fix this issue
## Other thoughts / use case / comments

For a store with multiple languages in a particular country, we believe the store view level should not allow price modifications. Perhaps the ability to set prices at this granular level is a "feature" of Magento 2, in which case I guess we can live with that but the interfaces / scoping indications throughout the site should be updated to indicate that the price is either Global or Store View, _NOT_ website scoped. Ideally though I think the pricing should at least have the option of a properly working Website scoped, as Magento 1.x did, and as the interface elements indicate should be happening.

**Comment by duhon** [comment]
Hi @develpr , thanks for reporting this issue. Internal ticket MAGETWO-54704

**Comment by develpr** [comment]
Is an issue like this something likely to be fixed soon, with a RC type release for 2.1? It seems critical for a multi-currency store.

**Comment by ronnybremer** [comment]
Unfortunately, the issue has not been fixed even in CE 2.1.1. We experience exactly the issue described.
Just one small addition. Depending on which way you look at a product, it does behave differently.
Let take your example with the three prices set.
If I visit the Canadian French store and look at a product category listing of all products (grid), it will show the correct Canadian English price ($ 6). However, as soon as you click on a product to open the detail view, the price changes to the $ 7. That wrong price does also end up in the shopping cart, no matter if you add the product through the grid or detail page.

This is a show stopper for us, as we deal with multiple websites and multiple stores, so rolling out CE 2.1.1 is currently not possible.

**Comment by ronnybremer** [comment]
To me it looks like a more serious issue than I originally thought. When looking at the table: catalog_product_entity_decimal
you ill see the column: store_id

I was expecting to see: website_id

Screams like someone mixed up the scope not just in the upper block php files, but all the way down to the DB layer....

**Comment by tandih** [comment]
Hi guys,
Any update to fix that issue ? That serious issue may :(

**Comment by develpr** [comment]
I've seen no updates so far (including on other support channels).

**Comment by mattador** [comment]
This is probably one of the more cryptic issues I've come across in Magento 2. I ran into it while working on a multi-website setup using different base currencies. I managed to work around the problem with a plugin that overrides the configurable price resolver functionality.

**Comment by nigelbolton** [comment]
We are seeing the same issue, exactly as detailed by others above.

**Comment by hanhpv** [comment]
I have same problem with product status. The status attribute has a website scope, but I can set different product status for stores.

**Comment by cscd98** [comment]
Magento - update on this issue please?

**Comment by yaronish** [comment]
Fixed.

**Comment by scientic** [comment]
Magento 2.1.4 wholesale/retail multistore. Different prices are set, but very annyoing. Only after several attempts, sometimes like 6 times, the store updates the price. But then default settings are changed too (sometimes). So have to go back and forth to check. I don't recall this issue before upgrading to 1.2.4. Just to be sure it has nothing to do with cronjobs I run them through the command line.
