### ISSUE TITLE
What a algorithm to create a order via rest API?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#5134]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Auth with admin. `[POST]` http://springimport.net/rest/V1/integration/admin/token
3. Creating cart. `[POST]` http://springimport.net/rest/V1/customers/2/carts
4. Add items to cart `[POST]` http://springimport.net/rest/V1/carts/59/items
5. Add ship info `[POST]` http://springimport.net/rest/V1/carts/59/shipping-information

``` json
{
  "addressInformation": {
    "shippingAddress": {
      "region": "New York",
      "regionId": 43,
      "regionCode": "NY",
      "countryId": "US",
      "street": [
        "Main St"
      ],
      "telephone": "64868564631",
      "city": "New York",
      "firstname": "Tom",
      "lastname": "Sawyer",
      "customerId": 2
    },
    "shippingCarrierCode": "ups",
    "shippingMethodCode": "gnd"
  }
}
```
1. Place order. `[PUT]` http://springimport.net/rest/V1/carts/59/order
## Expected result
1. Placed order.
## Actual result

Step 5: "`Carrier with such method not found: %1, %2`". All delivery methods in the admin panel is active.
Why I get an error?

**Comment by springimport** [comment]
Any news?

**Comment by mbrinton01** [comment]
What is the result for `[GET] http://springimport.net/rest/V1/carts/59/shipping-methods`?

**Comment by springimport** [comment]
```
{
    "message": "Shipping address not set.",
    "trace": "#0 [internal function]: Magento\\Quote\\Model\\ShippingMethodManagement->getList(59)\n#1 ......."
}
```

**Comment by mbrinton01** [comment]
@akaplya are you able to reproduce this issue?

**Comment by sdzhepa** [comment]
@springimport Hello
It seems value for "postcode" is missed. This field is required for UPS.

Payload Example with "postcode": 

>  5.Add ship info [POST] http://springimport.net/rest/V1/carts/59/shipping-information 

``` json
{
  "addressInformation": {
    "shippingAddress": {
      "region": "New York",
      "regionId": 43,
      "regionCode": "NY",
      "countryId": "US",
      "street": [
        "Main St"
      ],
      "telephone": "64868564631",
      "city": "New York",
      "firstname": "Tom",
      "lastname": "Sawyer",
      "customerId": 2,
      "postcode": "10022"
    },
    "shippingCarrierCode": "ups",
    "shippingMethodCode": "03"
  }
}
```

**Additional information**
 "shippingCarrierCode" and "shippingMethodCode" we can get using service:

> [POST] rest/V1/carts/1/estimate-shipping-methods

Payload:

``` json
{"address":
{
"region": "New York",
      "regionId": 43,
      "regionCode": "NY",
      "countryId": "US",
      "street": [
        "Main St"
      ],
      "telephone": "64868564631",
      "city": "New York",
      "firstname": "Tom",
      "lastname": "Sawyer",
      "customerId": 2,
      "postcode": "10022"
}}
```

Response Example:

``` xml
<response>
...
  <item>
    <carrier_code>ups</carrier_code>
    <method_code>03</method_code>
    <carrier_title>United Parcel Service</carrier_title>
    <method_title>UPS Ground</method_title>
    <amount>347.76</amount>
    <base_amount>347.76</base_amount>
    <available>true</available>
    <error_message></error_message>
    <price_excl_tax>347.76</price_excl_tax>
    <price_incl_tax>347.76</price_incl_tax>
  </item>  
  ...
</response>
```

@springimport did it help You to resolve the issue?

**Comment by springimport** [comment]
Thanks for the answers, I will try.

**Comment by andimov** [comment]
@springimport 
Did you try the solution above?

**Comment by springimport** [comment]
Yes.

Thanks, all worked well.

**Comment by mbrinton01** [comment]
Thank you @springimport, glad to know it's working for you now. Closing the issue
