### ISSUE TITLE
Add to cart for swatch and drop down attributes

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5135]
On the products,The Add to cart does not work if I have a color attribute as swatch and density as drop down, But if i have both as Drop down , the add to cart works. Is this code issue or a bug??.

attached a image for ref.
![atc swatch](https://cloud.githubusercontent.com/assets/19605497/16235300/407cffe8-37cc-11e6-8314-54e926ae3abd.png)

**Comment by antboiko** [comment]
Hi @nmallepally , what Magento version are you using?

Thanks,
Anton.

**Comment by nmallepally** [comment]
2.0.4 version @antboiko

**Comment by antboiko** [comment]
Hi @nmallepally , we cannot reproduce this issue on 2.0.4, 2.0.7 and 2.1-rc3. 
Please try to disable third party extensions, do composer update, clear cache and try to reproduce it again. 
Notice that the last Magento version is 2.0.7, so you can upgrade your system and check your scenario after that.

Best,
Anton.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
