### ISSUE TITLE
magento 2 import product from csv and attribute variation change automatially

### ISSUE THREAD

**Issue by ravinama** [magento/magento2#5136]
Hello Dear,

I have faced issue when import product in magento 2.When i have add more then one product in then product variation automatically.

From:Ravi Nama

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
