### ISSUE TITLE
Add ability to insert additional checkout success buttons

### ISSUE THREAD

**Issue by navarr** [magento/magento2#5138]
# Feature Request:

Rather than override the success.phtml file, add the ability to create child blocks that can add buttons to the toolbar after checkout success.
## Steps to reproduce
1. Install Magento 2.1 (in any shape)
2. Decide that you want to add an additional button in the toolbar on Checkout Success
3. Investigate [the template](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/templates/success.phtml#L25) to see if it is looking for additional blocks
## Expected result
1. Become overjoyed with the ability to add blocks and insert additional buttons in this very handy space (through server-side rendering) for having them
## Actual result
1. Become saddened with the lack of such an ability, and instead add a block to appear after the success block, rendering your button awkwardly underneath the other button - or alternatively change the entire success template

**Comment by oserediuk** [comment]
Hello! Please, use this template https://github.com/magento/magento2/wiki/Issue-reporting-guidelines to create issue. Thanks!

**Comment by navarr** [comment]
This was more a feature request so I wasn't sure it would read right, but I've updated the issue with the template.

**Comment by navarr** [comment]
I updated the ticket as requested @oserediuk

**Comment by navarr** [comment]
Should this be moved to the forums as a feature request?

**Comment by pboisvert** [comment]
@asemenenko heads up on a feature request for Checkout customization

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-ability-to-insert-additional-checkout-success-buttons/idi-p/45958).
