### ISSUE TITLE
Api interface for product swatches

### ISSUE THREAD

**Issue by paales** [magento/magento2#5139]
Currently using 2.1-rc3.

There is no API available for product option swatches. It makes sense if we are able to use the `ProductAttributeOptionManagementInterface` to add new swatch texts to products.

Maybe to have better separation of concerns we could have a `ProductAttributeOptionSwatchManagementInterface` to add swatch information to an existing option.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Api-interface-for-product-swatches/idi-p/45085).
