### ISSUE TITLE
Error in Topmenu.php?

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#5140]
I'm using Magento 2.0.7 to create my own theme basing on blank and I needed to adjust the top navi. Now it is possible to set classes for the top ul in topmenu.phtml though it seems the Topmenu.php is not correctly using the second value $childrenWrapClass. It is simply not used in function _addSubMenu and instead manually there is the standard value in the code.

Anyway, be it like it be. For what I need it seems I can't use the template or design files since I need to set some things for the a tag and that tag is only sat in the php file. Something like `<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">`

So now how to overwrite that php file? Adjusting the function? Is there an easy way to copy the file into a directory in my theme?

Thank you!

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by Onkovat** [comment]
Thanks for the hint though I think there is a bug in magento 2. In topmenu.php the var $childrenWrapClass is not used for wrapping submenus. Instead in the function where it should use the class submenu in the html code this class is hardcoded into.

**Comment by Onkovat** [comment]
Ok, I will open a new ticket since I do not know how to reopen this one
