### ISSUE TITLE
After Migration : Product type saves as Simple.

### ISSUE THREAD

**Issue by djes240285** [magento/magento2#5149]
Steps to reproduce
## After migration:
1. Edit any products (not simple)
2. To change anything in products
3. Save
## Expected result
1. [Example] Configurable product should not change your type.
## Actual result
1. [Example] Type configurable, virtual, etc.  - changed to simple
2. http://take.ms/58JvN
3. http://take.ms/Y2Naa

What to do?!!!

Thanks.

**Comment by palamar** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): 
- with steps to reproduce
- actual result
- expected result

For your case the most possible place of issue is a migration process

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one.
