### ISSUE TITLE
<adminurl>/catalog/category/index/ sits in spinning circle of death 2.1

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#5150]
## Steps to reproduce
1. Install Magento from `develop` branch. 2.1
2. proceed to admin url /catalog/category/index
## Expected result
1. screen should clear away and allow data entry for categories. 
## Actual result
1. screen sits on spinning wheel. 

I believed it was due to fpc due to log files displaying xml error, however with fpc turned off. it still sits on error screen

**Comment by commcad** [comment]
Don't know, could be related https://github.com/magento/magento2/issues/4635

Try clearing the browser cache and try again

**Comment by dmcmillin** [comment]
Cleared and tried again still erroring, even turned off ssl and set everything http only, still erroring.. Downgraded to 2.0.7 and the error cleared up entirely. I am going to run debug once away from office.

**Comment by seanvandermolen** [comment]
Upgraded Magento 2.0.5 to 2.1 using the Web Setup Wizard.  Having this same problem with the products, catalog, customer ... basically all the views.  Just getting a spinning wheel.

...Updated, read through 4635 and clearing the cache fixed the problem.

**Comment by veloraven** [comment]
@dmcmillin thank you for your report.
This issue was connected with browser cache: it should be cleaned.
To avoid the same issue in future you can turn on the following option in admin area: 
_Stores -> Configuration -> Advanced -> Developer -> Static Files Settings -> **Sign Static Files = Yes**_

**Comment by andimov** [comment]
@dmcmillin 
Have you tried the solution from the comment above?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
