### ISSUE TITLE
Toolbar Amount Catalog Page / Product Visibility

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#5151]
I have configurable products and simple products in the same category.

The page for the category states that there are five products available. I have a configurable product and four simple products used as variants inside it.

However, the issue may be irrelevant to this. The toolbar amount at the top of the page states that there are five products in the category (one is displayed, the rest are hidden).

Has this been addressed? Should it count products that aren't/cannot be visible to the user?

**Comment by Ctucker9233** [comment]
I'm interested in this as well. Are there any updates?

**Comment by pboisvert** [comment]
@tkacheva not sure if this is you or Anton.

**Comment by tkacheva** [comment]
@LiamFielding Please report the issue with all the details about magento version and your environment. 
I didn't manage to reproduce it on 2.1
![swatch_catalog](https://cloud.githubusercontent.com/assets/5603216/16685377/71e2a976-4513-11e6-95a8-6bbb2de3f88b.png)

**Comment by andimov** [comment]
@LiamFielding 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by pjw345** [comment]
I have the same issue and I've managed to reproduce the issue on 2.1.4,  Fresh download, create 3 products, add them to a category, 3 products shown,

Now disable one product, and 2 products will be shown, but the toolbar still says 3 products
