### ISSUE TITLE
Filtering by store view doesn't work

### ISSUE THREAD

**Issue by cozzamara** [magento/magento2#5152]
## Steps to reproduce
1. Install Magento 2.0.7
2. Upgrade to Magento 2.1.0
3. Set up multiple store views
4. Navigate to Products -> Catalog 
5. Apply filter by Store View
## Expected result

Products are filtered by store view
## Actual result

Filter is ignored; products for all store views are still shown. 

This was not a problem in 2.0.7

**Comment by cozzamara** [comment]
Not sure if that matters, but this was happening on 2.0.7 CE upgraded using command-line to 2.1.0.RC3 - not on freshly installed RC3.

**Comment by cozzamara** [comment]
This is still a problem in 2.1.0 release upgraded from 2.0.7. 
Fresh new installation of 2.1.0 doesn't suffer from this problem

**Comment by sevos1984** [comment]
I can't recreate it after upgrading from 2.0.9 to 2.1.1. Is this still actual?

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
