### ISSUE TITLE
addCategoryFilter root category doesn't work

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#5153]
$id = $this->_storeManager->getStore()->getRootCategoryId();
$_category =  $this->_categoryFactory->create()->load($id);

$collection = $this->_productCollectionFactory->create()->addCategoryFilter($_category);

When i filter with categories not root category, It work fine. But when i try filter with root category, it doesn't work. Anybody have solution? Thanks.

**Comment by andimov** [comment]
To allow us research the issue, please, provide description according to the template.
Please, provide the used version also. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by duongquyet** [comment]
Hi,
I use "\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory" for colection and magento 2.0.6.

**Comment by andimov** [comment]
@duongquyet Thank you for version number. Maybe it's not a bug. Please, provide description according to the template:
Steps to reproduce
..
Expected result
..
Actual result
..

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by duongquyet** [comment]
Hi,
How can i reopen it or i need create a new ticket?

**Comment by andimov** [comment]
@duongquyet 
Create new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
