### ISSUE TITLE
Incorrect Request URL with Form Key on the product import.

### ISSUE THREAD

**Issue by maxhopei** [magento/magento2#5154]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to Admin Panel
3. Go to System -> Import.
4. Select "Products" in Entity Type field.
5. Set: Import Behavior: "Add/Update", select valid file to import.
6. Click "Check Data", wait for validation to complete.
7. Click "Import".
## Expected result
1. The request is sent to http://obo-demo.testing.cgi-labs.de/admin/admin/import/start/key/[some-key]/?form_key=[form-key] OR
2. The request URL doesn't contain form key as form key is present in the POST payload.
## Actual result
1. Request URL is: http://obo-demo.testing.cgi-labs.de/admin/admin/import/start/key/[some_key]/&form_key=[form-key] (**note the "&" instead of "?"**). Form key is also in the payload.

**Comment by shiftedreality** [comment]
Hi @Radio 

Thank you for your submission.
We've created internal ticket MAGETWO-58250 to fix this issue.

**Comment by magento-engcom-team** [comment]
@Radio, thank you for your report.
We've created internal ticket(s) MAGETWO-58250 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#58
