### ISSUE TITLE
IndexerHandlerFactory: Indexer Object cast to String

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#5155]
The IndexerHandlerFactory casts the indexer Object to string if an error occurs:

https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Indexer/IndexerHandlerFactory.php#L78
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Indexer/IndexerHandlerFactory.php#L83

Since the $indexer should be an Object of type IndexerInterface and the IndexerInterface does not have the __toString() method, this cannot work.

**Comment by veloraven** [comment]
@davidverholen , please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template.

**Comment by davidverholen** [comment]
it's from the develop branch, so pretty much up to date I think

**Comment by veloraven** [comment]
@davidverholen develop version - is Ok.
Please format this issue according to the template: with steps to reproduce, actual result and expected result.

**Comment by davidverholen** [comment]
There is nothing to reproduce. It's just an error in the code. 
It can't be assumed that the indexer Object in the highlighted positions can be converted to string.

**Comment by veloraven** [comment]
@davidverholen I created an internal ticket for this issue - MAGETWO-55154 and linked it to this one.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to develop. See 9d7fe88.

**Comment by Ctucker9233** [comment]
@slavvka will the fix in 9d7fe88 be included in 2.1.3?
