### ISSUE TITLE
Not use email_order_set_template_vars_before observer in OrderSender class

### ISSUE THREAD

**Issue by dunghangnuakhong** [magento/magento2#5158]
## Steps to reproduce
1. I create event observer in etc/events.xml of my module.
   <event name="email_order_set_template_vars_before">
       <observer name="ss_sales_email_order_set_template" instance="Ss\Sales\Observer\SetTemplateVars" />
   </event>
2. I create SetTemplateVars class in my Observer
   <?php
   namespace Ss\Sales\Observer;
   class SetTemplateVars implements \Magento\Framework\Event\ObserverInterface
   {
   
   public function execute(\Magento\Framework\Event\Observer $observer)
   {
       $transport = $observer->getTransport();
       $transport['test'] = 'this is a test';
   
   }
   }
## Actual result
1. Cannot add $transport['test'] to prepareTemplate function in vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php class.
2. I make sure my observer create correct.
3. Please help me. I want to know this is bug magento 2 or not.

**Comment by fooman** [comment]
$transport is a `\Magento\Framework\DataObject`  and not an array. Use it as `$transport->setTest('TESTING');`

**Comment by NadiyaS** [comment]
Hi @dunghangnuakhong ,
the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you have encountered a real bug in Magento 2.
Thanks
