### ISSUE TITLE
Middle table rates never evaluated

### ISSUE THREAD

**Issue by karlsminton** [magento/magento2#5159]
When using magento2's in-built table rates, my first and last rates (in the csv) are evaluated fine, but the middle rate is always ignored.
The contents of the csv are;

Country,Region/State,"Zip/Postal Code","Order Subtotal (and above)","Shipping Price"
_,_,_,0.0000,4.9900
*,_,_,50.0000,2.9900
*,_,*,100.0000,0.0000

However when the order value exceeds £50, it still costs the user £4.99

The csv does upload correctly and when I download it, it looks exactly the same as the version I uploaded.

I'm currently running magento 2.0.7 on php 5.6.5

**Comment by oleg-onufer** [comment]
Hi @karlsminton.
Please add next screenshots:
-- tablerates.csv
-- Shipping method -> tables rates
-- Frontend -> Shopping Cart

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
