### ISSUE TITLE
ImportExport: Tier price product import requires multiple rows.

### ISSUE THREAD

**Issue by paales** [magento/magento2#5160]
### Preconditions
1. Magento 2.1.2 (all versions)

### Steps to reproduce
1. Try and import products with multiple prices.

### Expected result
1. A single row is required per product and thus a single field is required for all tier prices.

### Actual result
1. To import tier prices the import model requires multiple rows at this moment. This breaks the single-row-per-product strategy that is used for the M2 Import/Export functionality

### Feature requests:
1. The method to explode implode the collapsed multi row format should be abstracted ([Usages](https://github.com/magento/magento2/search?utf8=%E2%9C%93&q=PSEUDO_MULTI_LINE_SEPARATOR)).

2. Maybe it would be easier to move to json, the values are not writable by a human as it is? I have never seen customers using the csv file format directly. But don't know what your vision about this is?

**Comment by paales** [comment]
A side note:
Methods/properties should be protected not private, causing me problems with extending.

``` PHP
private $productEntityLinkField;
private $productEntityIdentifierField;
private function getProductEntityLinkField()
private function getProductIdentifierField()
```

**Comment by paales** [comment]
@vzabaznov The usage of the value delimiters, row delimiters and category delimiters cause problems in the import format. The characters `, | /` are now reserved symbols that can't be used in the values.

The exploding of values should be done by a `preg_split` instead of `explode`. For an example see http://stackoverflow.com/questions/8519793/php-explode-but-ignore-escaped-delimiter

We solved this issue with categories in AvS_FastSimpleImport by this (gross) code:
https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Category.php#L304-L333

**Comment by Vinai** [comment]
The only thing going for CSV is that it can be built by humans (kinda) using Excel.
If the Excel factor is taken away JSON or YAML would be superior.
I don't know of a generic tool that allows to export JSON that could be used in place of Excel by end-users though.

Regarding protected/private, I'm pretty firmly on the private side of things.
Better to keep code simple, composed of different classes working together, and then replace individual classes as a whole.
Using private leads to more maintainable and flexible code in my experience.
Protected visibility tends to lead to big rigid inheritance graphs.

**Comment by veloraven** [comment]
@paales is this issue still actual?
If it is please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
if it is rather improvement than an issue please move it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by paales** [comment]
@veloraven Yes, this issue is still actual. I've updated the original issue to follow the issue reporting guidelines.

**Comment by magento-engcom-team** [comment]
Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
