### ISSUE TITLE
Magento 2.0.7 topmenu.php probable error.

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#5161]
I think there is a bug in magento 2. In topmenu.php, which is in module-theme/Block/Html the var $childrenWrapClass is not used for wrapping submenus. Instead in the function, where the class submenu should be used in, the class "submenu" is hardcoded into the html. Which is the standard text for that variable too. The var is only not used then.

**Comment by vzabaznov** [comment]
Hi @Onkovat 
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.
To allow us research the issue, please, provide description according to the template.
It would be great if you'll highlight the problem place

**Comment by Onkovat** [comment]
I mentioned the used version in the title only... it's 2.0.7 so I think it should be the most actual official magento 2 version.
If I'm wrong let me know but as far as I see it the classes for submenus does not work with that .php file yet.
In order to be more specific. The template file for the top-navi is in module-theme/view/frontend/templates/html/topmenu.phtml. On line 18 it calls the function $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) and the second var is the one it is about.

It then goes to the class in module-theme/Block/Html/Topmenu.php on line 70. public function getHtml($outermostClass = '', $childrenWrapClass = '', $limit = 0)

From there, on line 80 to $html = $this->_getHtml($this->_menu, $childrenWrapClass, $limit); and still drawing the childrenwrapclass around.

On line 193 it goes into protected function _getHtml(
        \Magento\Framework\Data\Tree\Node $menuTree,
        $childrenWrapClass,
        $limit,
        $colBrakes = []
    )

and on line 233 into function $this->_addSubMenu(
                $child,
                $childLevel,
                $childrenWrapClass,
                $limit
            )

$childrenWrapClass is still drawn around though on line 162 at protected function _addSubMenu($child, $childLevel, $childrenWrapClass, $limit)

it fails at line 174: $html .= '<ul class="level' . $childLevel . ' submenu">'; where it puts in the class for the submenu into hardcoded without consultiing the variable. Which is the same class specified in the template file. Only that editing the class in template file does not affect anything.

Let me know if Iam mistaken.

By the way... when I need to adjust Topmenu.php anyway for the sole purpose of a theme, shouldn't it be possible then to add a module in the theme directory?

**Comment by magento-engcom-team** [comment]
@Onkovat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
