### ISSUE TITLE
[CE 2.0.7 ] Invoice,Ship & Cancel an order of [Bundle or configurable product]

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5163]
## Steps to reproduce
1. Install Magento 2.0.7
2. Add bundle Product to the cart [Quantity = 2].

**\- Grouped Product :**

Pack 
SKU: Pack-WSH12-32-Red-MH04-XL-
Yellow 

**\- Items of the bundle product:**

**2 x** Erika Running Short-32-Red   + MAD0.00

**1 x** Frankie Sweatshirt-XL-Yellow   + MAD0.00 

**Place the order :** 
2 Qty of Bundle product
- 4 x Erika Running Short-32-Red
- 2 x Frankie Sweatshirt-XL-Yellow

**Then**
- invoice just 1 quantity
- ship just 1 quantity
- Cancel the order

In the table **sales_order_item**
## Expected result

![grouped_product_expected](https://cloud.githubusercontent.com/assets/13301885/16266734/db6e88ec-3875-11e6-81f9-043be794bc12.png)
## Actual result

![grouped_product](https://cloud.githubusercontent.com/assets/13301885/16266749/e7f37802-3875-11e6-8fa9-a4a301457d00.png)

**Comment by NadiyaS** [comment]
Hi @Dayssam ,
thanks for reporting this issue. It is already being tracked by MAGETWO-54626 ticket.
This issue will be closed as duplicate of #5086.

**Comment by mhabou** [comment]
@NadiyaS 
Also a problem with qty_shipped.

**Comment by NadiyaS** [comment]
We added these additional conditions to existed MAGETWO-54626 ticket.

**Comment by mhabou** [comment]
@NadiyaS 
There is an other issue with qty_shipped of the bundle product (If the bundle product shipment type is partially),

If i shipped the items of the bundle product partially , the qty_shipped value of the bundle product is wrong
