### ISSUE TITLE
2.0.7 Can't save more than 124 swatches in custom attribute

### ISSUE THREAD

**Issue by JDavidVR** [magento/magento2#5166]
## Steps to reproduce
1. Install Magento 2.0.7
2. Go to Backend: Stores > Attributes > Product
3. Create a new attribute: 
   code: size, 
   name: Size, 
   type: Text Swatch, 
   scope: Global
4. Add more than 124 Swatches (in my case 125)
5. Save
## Expected result
1. All swatches should be saved
## Actual result
1. It only saves upto 124 swatches, instead all created (in my case it can't save 125)

**Comment by piatrouski** [comment]
Could you increase your memory_limit & max_input_vars php values? It help you.

**Comment by JDavidVR** [comment]
thankyou @piatrouski, I have similar issue with magento 1 and increasing values for max_input_vars, solved my problem on both, magento 1 and 2

My main doubt is if this is normal?

**Comment by andimov** [comment]
@JDavidVR 
Thank you for reporting!
Increasing values for max_input_vars is normal for this issue.
I'm closing this issue. Please feel free to reopen if you need.
