### ISSUE TITLE
Configuration Store View collapse on scroll

### ISSUE THREAD

**Issue by alex-koepke** [magento/magento2#5167]
## Steps to reproduce
1. Install Magento.
2. Create 10+ store views
3. Click "Default Config" 
4. Scroll to reach bottom of list. (after the fold/below bottom of screen.)
5. Default Config dropdown is hidden. (the bug)
## Expected result
1. Page scrolls and you can reach the bottom of the drop down
2. (or) The menu is limited in height and `overflow: scroll;` is added to `.store-switcher .dropdown .dropdown-menu`
## Actual result
1. Install Magento.
2. Create 10+ store views
3. Click "Default Config" 
4. Scroll to reach bottom of list. (after the fold/below bottom of screen.)
5. Default Config dropdown is hidden. (the bug)
6. can't reach bottom of list or "Stores Configuration" menu item.
   ![drop down bug](https://cloud.githubusercontent.com/assets/10850217/16277327/73ca710a-3880-11e6-9e9b-1d6ca14c8fe1.png)

**Comment by alex-koepke** [comment]
Hi @MomotenkoNatalia,
Thanks for putting this issue in your queue! Please, let me know if you need more information.
Cheers,
Alex

**Comment by vil11** [comment]
Hi @alex-koepke 
This issue is fixed & delivered, so could you please update your M2 version & retest? I believe you won't face this bug again :smile: 

You may find details [here](https://github.com/magento/magento2/issues/2896).

## 

:sunny: dvilchynskyi, M2 QA

**Comment by andimov** [comment]
@alex-koepke
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
