### ISSUE TITLE
Static block doesnt work in WYSIWYG Editor on Product Detail Page

### ISSUE THREAD

**Issue by Talisa85** [magento/magento2#5168]
Hi guys,
i just try to implement a cms block in WYSIWYG Editor on product detail page. But there is no button for that. Using the code doesnt work - it show cms but isnt working in frontend.

When i do the same with my tab extension (itoris custom Tab) i have the button and it works well.

![image](https://cloud.githubusercontent.com/assets/19840780/16277580/d3ef1ff8-38b3-11e6-94dd-601a0c2fa3c0.png)

![image](https://cloud.githubusercontent.com/assets/19840780/16277657/2f350a6c-38b4-11e6-91a3-06fa5ab377d3.png)

is there a solution for that - can anyone help?

**Comment by palamar** [comment]
@Talisa85 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Also please provide information about your:
- browser and it version
- OS
- list of plugins that installed in browser

**Comment by Talisa85** [comment]
hi palamar,
i use magento version 2.0.7 - and it doesnt work with all browsers. the problem isnt a bug or a specific tag. it is more the editor on the product detail page. i cant put a cms static block into the editor, so that is visible in the front. i cant understand why cause it works when i put it in the custom product tab

**Comment by oserediuk** [comment]
Hi @Talisa85 ! The special button like 'Insert Widget' is absent in WYSIWYG Editor on product detail page in native magento functionality. You can create widget, add CMS block to it and assign widget to products.

**Comment by tkacheva** [comment]
@Talisa85 MAgento doesn't support widgets on Product page yet.

**Comment by magefan** [comment]
You can use this solution [magefan/module-catalog](https://github.com/magefan/module-catalog).
