### ISSUE TITLE
Data Migration Tool failing on Settings

### ISSUE THREAD

**Issue by qozmiq** [magento/magento2#5169]
## Steps to reproduce
1. Install Magento 2.0.7
2. Install data-migration-tool
3. Setup server 'Source' and 'Destination' in config.xml and place in /vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.1.0/
4. Migrate Setttings using following code:   `php -f bin/magento migrate:settings /home/absolute/path/to/config.xml`
## Expected result
1. Settings migration from old server to new
## Actual result
1. Error message appears: "[Zend_Db_Adapter_Exception]
   SQLSTATE[28000] [1045] Access denied for user 'fpins'@'sassyboutique.com' (
   using password: YES)
   ".
2. Error message appears: " [PDOException]
   SQLSTATE[28000] [1045] Access denied for user 'fpins'@'sassyboutique.com' (
   using password: YES)
   ".
3. The think is, sassyboutique isn't our domain, and the host (Nexcess) thinks this isn't their problem.  I feel otherwise.

**Comment by Ganginator** [comment]
+1
I'm dealing with this same issue, and on Nexcess as well.
I've tried the IP of host, and name as well as localhost all with same error...

Error:
[Zend_Db_Adapter_Exception]
SQLSTATE[28000] [1045] Access denied for user 'extdevon_mm_u'@'localhost' (using password: YES)
[PDOException]
SQLSTATE[28000] [1045] Access denied for user 'extdevon_mm_u'@'localhost' (using password: YES)

The connection must work as the Magento 2 store is running with the same credentials.

**Comment by qozmiq** [comment]
It was probably GoDaddy blocking this.  I tried a workaround where I moved the DB from my old host, transfered it to Nexcess server, and then ran source as 127.0.0.1 and destination 127.0.0.1 and it worked.

**Comment by andimov** [comment]
@qozmiq @Ganginator 
Thank you for reporting this issue!
Please, adress all issues regarding Migration Tool to https://github.com/magento/data-migration-tool repository.
