### ISSUE TITLE
__ function returns Phrase object. Could this return string?

### ISSUE THREAD

**Issue by bentideswell** [magento/magento2#5170]
The __ function returns a \Magento\Framework\Phrase object that when echo'd, is converted to a string via the __toString method. This breaks several integrations I am working on and also doesn't work properly with json_encode (its saved as an object rather than a string).

Is it possible to have have this method return a string? The majority of time this method is used, it will be echo'd straight away, meaning the object isn't required anyway. A second function could be created that returns the object and the __ function could call this second function and cast the result to a string.

Here is a rough example:

```
function __O()
{
    $argc = func_get_args();

    $text = array_shift($argc);
    if (!empty($argc) && is_array($argc[0])) {
        $argc = $argc[0];
    }

    return new \Magento\Framework\Phrase($text, $argc);
}

function __()
{
    return (string)__(func_get_args())
}
```

This is needed as the __ function cannot be overwritten or extended like all other publicly available methods in Magento.

**Comment by adragus-inviqa** [comment]
I don't mind the request, but I'm guessing changing the return value of `__()` would break things.

**Comment by bentideswell** [comment]
I have done some limited testing and I have been unable to find an occurence where the object that __ returns isn't cast into a string. By using grep, I have searched for occurences of the function that are printed straight out and occurences that are assigned to a variable. Of the latter, these are always assigned to a variable with the word 'title' or 'label' in and are always then printed to the screen.

**Comment by Vinai** [comment]
One exception is the `\Magento\Framework\Exception\LocalizedException`, which takes a `Phrase` as a constructor dependency.  
It even exposes Phrase internals like the arguments. The question is if that is really needed functionality. I would also much prefer to be dealing with plain strings, as having the `Phrase` in there just adds another dependency to all tests for code using `__()`.  
I find myself not using the `LocalizedException` for that reason.

**Comment by bentideswell** [comment]
Thanks for spotting that Vinai, I missed that one.

Would it be possible to modify the LocalizedException so that a plain string is passed in the constructor rather than a Phrase object. The constructor could then use the plain string to instantiate a Phrase object and store it is an protected variable of the class. This gives the LocalizedException class access to the Phrase object while allowing the __ function to return a string.

**Comment by Vinai** [comment]
Passing in a string would not give it access to the `Phrase` arguments, so that refactoring would not really be possible without changing the interface of the [`LocalizedException` class](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Exception/LocalizedException.php).  
There are several non-test places in the core where the methods `getParameters()`, `getRawMessage()` and `getLogMessage()` are called. So it's not that simple sadly.
The exception class has an `@api` tag which means that change would require a major version bump.
Maybe the core team (or a PR) can decouple the exception rendering though, and then the `Phrase` returned by `__()` could become a string.
It would be cool if that change could then be scheduled to be included in the next major version.

**Comment by bentideswell** [comment]
Agreed, it would be awesome if it could be implemented as it's currently stopping me porting a few extensions to M2. I will look into alternative ways of doing what I need to do and hopefully the core team can look at this.

**Comment by vkublytskyi** [comment]
@bentideswell, would you provide more information what exactly issues you have in your integrations? Also please provide some code or steps to reproduce that 

> doesn't work properly with json_encode  (its saved as an object rather than a string)

`Magento\Framework\Phrase` implements [`JsonSerializable`](http://php.net/manual/en/class.jsonserializable.php) interface so it is represented as a string in json_encode output.

As changing return type of `__` function is a backward incompatible change we should have very strong reasons to do that.

---

Regarding `LocalizedException`. We acknowledged that it is not well-designed and general approach of  it usage have drawbacks so we will review it in a near future.

**Comment by bentideswell** [comment]
@vkublytskyi, thank you for your reply.

The main issue I have is related to my Magento WordPress Integration extension. Magento and WordPress both use the __ function as a translation function. I get around this issue by wrapping the WordPress __ function with a call to function_exists and only allow the declaration of the function if it hasn't already been defined (by Magento). This worked perfectly and when integrated, WordPress relied on the Magento translation system to translate strings. This was acceptable as my extension also ported the WordPress translation file to a valid Magento translation file so translation could still occur in both Magento and WordPress.

In M2 I tried the same approach and the __ function was correctly not declared by WordPress and the M2 __ function was used. This triggered errors in WordPress though as a lot of WordPress core code uses the __ function around array keys.

Consider the following code:

```
$archives = array();
$archives[ __('January') ] = '01';
$archives[ __('February') ] = '02';
```

The above code is an example but there's multiple instances of similar code scattered through the WordPress core code.

In M1, this code worked fine as __ returned a string. In M2, an object is returned and an object cannot be used as an array key. Unfortunately, PHP doesn't automatically try to convert the object to a string, which would resolve the issue.

Hopefully this explains the issue fully but if not, feel free to ask as many questions as you need.

As for the json_encode issue, I may have made a mistake there and I haven't tested it as much as I should. That was more of a side issue for me anyway, with the main issue being the WordPress integration issue.

**Comment by vkublytskyi** [comment]
@bentideswell, thank you for explanation. We will investigate this use case to find solution or a work around.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/function-returns-Phrase-object-Could-this-return-string/idi-p/45075).
