### ISSUE TITLE
Free Shipping coupon times usage - bug?

### ISSUE THREAD

**Issue by mrVrAlex** [magento/magento2#5171]
Hello, guys.
You know about functional which can make shopping cart rule with coupon on free shipping only?
I don't understand logic here - https://github.com/magento/magento2/blob/2.1/app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php#L60
Why you check only discount amount in order? Because of coupon on free shipping change only shipping order amount. I think need additional check coupon code in order for increment "times usage" field for coupons.
BTW: This bug also have in magento 1.x code.

---
## Steps to reproduce
1. Install Magento from `any` branch.
2. Create shopping cart rule with coupon and set free shipping option.
3. Apply this coupon during checkout process and make a order.
## Expected result
1. In coupon admin statistic should see increasing "times usage".
## Actual result
1. Do not incrementing "times usage" for coupon.

**Comment by SerhiyShkolyarenko** [comment]
@shandyDev thank you for the report! We reproduced the issue and created internal MAGETWO-58388.

**Comment by pboisvert** [comment]
thanks @danslo for spotting the duplicates  closing as a duplicate of #3506
