### ISSUE TITLE
Unable to link existing simple products to configurable products

### ISSUE THREAD

**Issue by cgaffney099** [magento/magento2#5172]
I'm using magento 2.0.7 CE I am trying to create a configurable product by CSV using simple products I have already Imported.  This was possible in magento 1.x, but now in version 2.x I can't get it to work.  It creates the products as configurable products, but doesn't include any of the variations. 

The configurable products I am trying to create are T-shirts.  They are based on size as the configurable attribute.  The Skus and pricing information already exist for the simple products, but I'm just trying to link them all together with a configurable product.

Steps to Reproduce:
1. Have Exisiting SImple products in magento 
2. Have a product attribute (in this case size)
3. Generate a CSV file with configurable products
4. Upload to website

Expected Result
1. Simple Products linked to Configurable Products

Actual Result
2. Simple products not linked to configurable product

Example CSV:

https://drive.google.com/file/d/0B7uWXdhFXQCdRHJraHlLOEkzRUk/view?usp=sharing

**Comment by andimov** [comment]
@cgaffney099 
Thank you for reporting!
Please change description according to the template. It helps us clarify and research the issue.

**Comment by cgaffney099** [comment]
I updated the description

**Comment by shiftedreality** [comment]
Hi @cgaffney099 

This bug was already fixed in `2.0.9` version.
Please confirm.

**Comment by cgaffney099** [comment]
@shiftedreality  I have since updated to magento 2.1  I tried it again with the existing csv file, it didn't update as expected.  please advise.  thanks!

**Comment by mamsincl** [comment]
(a) run indexer and (b) clear cache (not just M2 but browser)

**Comment by IlnitskiyArtem** [comment]
Hi, @cgaffney099. I tried to reproduce your issue on latest develop branch and observed strange behavior, don't know was it my fault or something else. Firstly I'm added simple products by hand, then imported your csv (but just with first 5 products). In result, my simples just earn new categories, any configurable were created. Same result with importing simples based on your csv. Can you provide more information to reproduce this issue as it was in your case?

**Comment by xtremevision** [comment]
Bug present in Magento 2.1.7 and Magento 2.2.3. To reproduce:

- Create simple products using configurable attributes (size, color, whatever)
- Create new configurable product. Link to "Add products manually" is missing.

To circumvent:
- Click on Edit Configurations
- Choose Attributes
- Click all the way to choose products, and one or two
- When back in main page, remove added products and add the ones already created

**Comment by devkokov** [comment]
Has this been fixed in 2.3 then? Or still not released?

**Comment by rabraga** [comment]
I have version 2.3.2 and the link does not appear. What's the fix?

**Comment by OvalMedia** [comment]
2.4 and problem still persists.

**Comment by nkajic** [comment]
2.4.2-p1 and problem still persists.

**Comment by xtremevision** [comment]
2.4.3-p1 and having the same issue. created simple, and trying to create configurable but the add products link is missing.
