### ISSUE TITLE
After settings migration, admin 404

### ISSUE THREAD

**Issue by bch80** [magento/magento2#5174]
## Steps to reproduce
1. Install Magento from webinstaller or git (2.0.7)
2. Migrate settings from 1.6.0.0 store with data-migration-tool
## Expected result
1. Working shop with settings migrated
## Actual result
1. Working frontend, non accessible backend (404)
2. logs and details as following:

Hello,

I installed M 2.0.7 on Apache 2.4, PHP 5.6 (Lubuntu dev machine) (on port 80, nothing special there).
Frontend and backend were working fine.

Then I used the data-migration-tool to migrate from 1.6.0.0 - settings worked fine as well, the process went through, I can see my 1.6.0.0 settings in my 2.0.7 core_config_data.
**But** I could not access my admin panel anymore (404)
I tried this whole process now 5 times in different orders and it always resulted into admin 404 - so I moved on, migrated data which went smooth as well.
I reindexed everything from CLI, worked smooth as well - I can access all products, categories, see the filtered navigation etc. I just can't access the admin panel.

Then I migrated everything to a testing machine. Nginx 1.8.1, PHP 7.0.7-1~dotdeb+8.1
Like before, everything is running smooth, images, products, SEO URLs, contact us page, categories - Just not the control panel (404).

So far I tried:
(after each step:
`rm -rf var/di var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:static-content:deploy
`
and cleaned browser cache for a good measure).

Checked mod_rewrite / .htaccess (which was working before settings migration and shouldn't influence Nginx anyway).
http://magento.stackexchange.com/questions/96439/magento2-installation-admin-page-404-during-installation

`UPDATE core_config_data SET value = '0' WHERE core_config_data.config_id = 1;`
Frontend is working completely, backend 404 with and without index.php
https://github.com/magento/magento2/issues/2614#issuecomment-174527195

Updated `/app/etc/env.xml` set frontName from myadmin to myadmin2
https://github.com/magento/magento2/issues/2614#issuecomment-166347482

Updated `/app/etc/di.xml` set Symlink to Copy in `name="view_preprocessed"`
http://magento.stackexchange.com/questions/63117/magento-2-problem-in-admin-login/64809#64809

I checked the DB for `store_id` and `website_id` - but those are as suggested here:
http://magento.stackexchange.com/questions/87038/magento-2-error-404-not-found-at-magento-2-admin-login-page/87040#87040

Nginx error.log doesn't show anything.
access.log got it right: `"GET /myadmin2 HTTP/1.1" 404 8982 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36`
and then all the other files are correctly loaded:
`"GET /pub/static/frontend/Magento/luma/en_US/css/styles-m.css HTTP/1.1" 304 0`
(probably 304 because the 404 redirects me or sth.?) But css and js are all fine on the 404 page.
var/log/system.log doesn't show anything on this admin page load.
var/log/debug.log shows some of those:
`[2016-06-23 03:11:26] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://www.shop.de/myadmin2","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []`

Any idea what else I should try?

Thanks,
Chris

**Comment by andimov** [comment]
@Chris8080 
Thank you for reporting!
Please change description according to the template. It helps us clarify and research the issue.

**Comment by bch80** [comment]
I added the template - maybe not very useful in this case since I've got a lot of details and probably it's just one small thing that prevents my installation (backend) from working fine.

**Comment by bch80** [comment]
@andimov Please double check the issue now - still needs an update or is it good to go now?

**Comment by magento-engcom-team** [comment]
Hi @Chris8080 For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool. Thank You.

**Comment by gtrocks** [comment]
Hi @magento-engcom-team ,

i have followed the correct repository but still getting this issue . https://github.com/magento/data-migration-tool.

**Comment by davidbayley80** [comment]
Did this issue get a resolution? I'm experiencing the same issue: Post migration of the settings, the admin url is in accessible

Thanks,

**Comment by Horbarz** [comment]
Pls I'm also getting same issue, I have spent over 24 hours debugging

**Comment by Horbarz** [comment]
Pls I'm also getting same issue, I have spent over 24 hours debugging
