### ISSUE TITLE
SQL Error from console upgrading to M2.1.0-rc3

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#5175]
[Zend_Db_Statement_Exception]  
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-Images' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: U  
  PDATE `eav_attribute_group` SET `attribute_group_name` = ? WHERE (`attribute_group_id`=10)

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/4627

I have this error too...

**Comment by salelsol** [comment]
Issue related with migration from Magento 1.9, just go to table eav_attribute_group and remove row "Images" in table attribute_group_name.

**Comment by veloraven** [comment]
@salelsol if this issue is specific to migration process, please, create a ticket in corresponding repository: https://github.com/magento/data-migration-tool/issues
