### ISSUE TITLE
404 Forbidden sounds not right 

### ISSUE THREAD

**Issue by plewandowski** [magento/magento2#5176]
## Steps to reproduce
1. Login into admin area
2. Call non existing admin action with ajax. 
## Actual result

I get 404 as expected, but why it says forbidden instead not found? In my opinion it may be confusing. Is it a bug or feature?

https://madcoders-monosnap.s3.amazonaws.com/piotr/New_Product__Products__Inventory__Products__Magento_Admin_2016-06-23_08-15-47.png

**Comment by stamster** [comment]
Somewhere in a codebase, Magento sets HTTP header code to 404, but message is 'Forbidden'. If you omit string description - HTTP code, and return only numeric, your browser will handle the message, in this case 404 would became Not found as expected.

i.e.
`header("HTTP/1.1 404 Forbidden");`

**Comment by veloraven** [comment]
@plewandowski is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
