### ISSUE TITLE
WEBAPI: integration Bearer authentication is not working anymore in 2.07

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#5179]
Magento 2.07

Integration made, token entered in ERP, integration set to active in Magento, allowed all resources.

I receive always this error for each request:

env:Sender  Consumer is not authorized to access %resources

This was working in previous versions, access token is ok, request is also ok.

C:\wamp\www\magento207\vendor\magento\module-webapi\Controller\Rest.hp

slashing out this line on 286, solves the problem:

//$this->checkPermissions();

**Comment by andimov** [comment]
@tinxit 
Thank you for reporting!
To allow us research the issue, please, provide description according to the template.

**Comment by ericahoekerd** [comment]
always default template wehne testing API, we never use custom templates
default installation of Magento

**Comment by andimov** [comment]
@tinxit Please, provide description according to the template: https://github.com/magento/magento2/issues/new

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
