### ISSUE TITLE
No visual feedback when missing field in customer detail in back office

### ISSUE THREAD

**Issue by valibus** [magento/magento2#5185]
## Steps to reproduce
1. Do the next steps on magento 2.0.7 version
2. edit a customer in back office
3. leave blanck a mandatory field in account information tab (for example)
4. go to an other tab, edit some information (for example in addresses tab)
5. click on save
## Expected result
1. Display a visual feedback on the tab summary on the left to tell user that something is wrong in an other tab (different from the active one).
2. Automaticaly active the tab where the error is detected
   The feature was available in Magento 1.9 for example and is still available in product management in magento 2.0.7
   (look at screenshot below)
   ![image](https://cloud.githubusercontent.com/assets/6961470/16303594/c63827da-3951-11e6-92ea-cf5035598c14.png)
## Actual result
1. Product doesn't save
2. Magento doen't display any error or visual feedback
   ![image](https://cloud.githubusercontent.com/assets/6961470/16303666/2937a234-3952-11e6-973a-c1ea3485489c.png)

**Comment by oleg-onufer** [comment]
Hi @valibus.
Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2

**Comment by oleg-onufer** [comment]
Hi @valibus.
Thanks for reporting this issue.
Internal ticket MAGETWO-70229 was created.

**Comment by magento-engcom-team** [comment]
@valibus, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
