### ISSUE TITLE
Annoying when trying to move categories

### ISSUE THREAD

**Issue by loomdecor** [magento/magento2#5189]
In magento 1, you could move multiple categories at one time - which I can't seem to do anymore.

Also every time I move a category I get a warning message.  I get it - it takes a long time.  But it takes even longer if I have to close it all the time.  This should be something where I can say "don't show me again"

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Annoying-when-trying-to-move-categories/idi-p/45074).
