### ISSUE TITLE
[ CE 2.1.0 RC3] - qty_invoiced & qty_refunded of bundle product

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5193]
## Steps to reproduce
1. Install Magento CE 2.1.0 RC3
2. Add Bundle Product to the cart.
3. Place Order
   ![bundle_product_1](https://cloud.githubusercontent.com/assets/13301885/16310781/79d04042-395d-11e6-9619-b9a8706e57a3.png)
4. invoice
   ![bundle_product_2](https://cloud.githubusercontent.com/assets/13301885/16310829/a7b750fe-395d-11e6-86c8-b5b13f4dbdcf.png)

![bundle_product_3](https://cloud.githubusercontent.com/assets/13301885/16310967/1efd637e-395e-11e6-9045-9192cc3dc10e.png)

invoice the rest

![bundle_product_4](https://cloud.githubusercontent.com/assets/13301885/16311006/45df6ce4-395e-11e6-8164-686de5e832ea.png)

The problem in the qty_invoiced of bundle product
## Expected result

![bundle_product_6](https://cloud.githubusercontent.com/assets/13301885/16311084/9f12c0cc-395e-11e6-89c4-1e8707a36097.png)
## Actual result

![bundle_product_5](https://cloud.githubusercontent.com/assets/13301885/16311062/87c5df94-395e-11e6-8153-e0798e6188fa.png)

When i refund the order
## Expected result

![bundle_product_8](https://cloud.githubusercontent.com/assets/13301885/16311276/6fa07540-395f-11e6-9b3b-9089c0c29b1e.png)
## Actual result

![bundle_product_7](https://cloud.githubusercontent.com/assets/13301885/16311264/5e9c0804-395f-11e6-8a40-e48b6ad3b6a0.png)

**Comment by AVoskoboinikov** [comment]
Hi @Dayssam,

Thank you for your report. I have created tickets (#MAGETWO-57881 and #MAGETWO-57882) in our internal jira to fix this. This issue will be closed after fix.

**Comment by magento-engcom-team** [comment]
@Dayssam, thank you for your report.
We've created internal ticket(s) MAGETWO-57881, MAGETWO-57882 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@Dayssam, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
