### ISSUE TITLE
Updating attributes of products in the Catalog view doesn't work 

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#5195]
Running the latest version of Magento2. When you go to Products/Catalog, select either one or multiple products using the checkbox inputs on the left and go to Update Attributes using the dropdown in the top left. In my case I tried to change an attribute called "Manufacturer" and even though after I save the UI displays a confirmation that I was able to save the change, when I go to edit the product and validate that the change was made properly, it was not. 

Note that the attribute is a multi select attribute.

**Comment by elenleonova** [comment]
hi @samleeiii, which version of Magento do you use? 2.1.0?

**Comment by zerobrapsgiven** [comment]
Sorry it was the latest as far as I knew, but it's 2.0.7. I'll try upgrading to 2.1.0 to see if the issue is still persisting.

**Comment by andimov** [comment]
@samleeiii 
Thank you for reporting!
Did you check that issue exist in 2.1?
