### ISSUE TITLE
Unable to upgrade to Magento 2.1.0 GA via command line

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#5197]
I've already applied the patch MDVA-532.
I installed Magento originally via `composer create-project`.

I tried to upgrade from 2.0.6 to 2.1.0 GA via command line:

```
composer require magento/product-community-edition 2.1.0 --no-update
composer update
```

But I got this error:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)  
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for magento/data-migration-tool ~2.0.0 -> satisfiable by magento/data-migration-tool[2.0.5, 2.0.0, 2.0.2, 2.0.7].
>     - Conclusion: don't install magento/framework 100.1.0
>     - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
>     - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
>     - Conclusion: don't install magento/framework 100.1.0
>     - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].

**Comment by stevekarwacki** [comment]
I am having similar issues with EE:

composer require magento/product-enterprise-edition 2.1.0 --no-update
composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-enterprise-edition 2.1.0 exists as magento/product-enterprise-edition[2.0.7] but these are rejected by your constraint.

**Comment by andimov** [comment]
@lgarridoj, @stevekarwacki Please report this issue to the partner portal.

**Comment by pascaladriaansen** [comment]
@andimov Correct me if i'm wrong, but I believe you closed this issue because you thought this was an EE related issue.

I'm having a similar issue as @lgarridoj when trying to upgrade Magento CE 2.0.7 to 2.1.0. This is the error I get:

```
Problem 1
    - adwise/language-nl_nl 1.2.0 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.9, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8].
    - adwise/language-nl_nl 1.2.0 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.9, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8].
    - Can only install one of: magento/framework[100.1.0, 100.0.9].
    - Can only install one of: magento/framework[100.1.0, 100.0.2].
    - Can only install one of: magento/framework[100.1.0, 100.0.3].
    - Can only install one of: magento/framework[100.1.0, 100.0.4].
    - Can only install one of: magento/framework[100.1.0, 100.0.5].
    - Can only install one of: magento/framework[100.1.0, 100.0.6].
    - Can only install one of: magento/framework[100.1.0, 100.0.7].
    - Can only install one of: magento/framework[100.1.0, 100.0.8].
    - Can only install one of: magento/framework[100.1.0, 100.0.9].
    - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
    - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
    - Installation request for adwise/language-nl_nl ^1.2 -> satisfiable by adwise/language-nl_nl[1.2.0].
```

Is this because some modules say they depend on magento/framework of another version?

**Comment by andimov** [comment]
@pascaladriaansen 
To allow us research your issue, please, create new issue according to the template.

**Comment by qrider** [comment]
I am seeing a similar issue when trying to run the data migration tool:
`composer require magento/data-migration-tool:2.1`
`The requested package magento/data-migration-tool 2.1 exists as magento/data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7] but these are rejected by your constraint`
