### ISSUE TITLE
No sorting orders in API

### ISSUE THREAD

**Issue by springimport** [magento/magento2#5198]
## Steps to reproduce
1. Auth using integration.
2. `[GET]` _/V1/rest/V1/orders_ with params

```
searchCriteria[pageSize] = 100
searchCriteria[currentPage] = 1
searchCriteria[sortOrders][0][field] = increment_id
searchCriteria[sortOrders][0][direction] = asc
```
## Expected result
1. Sorted list of orders
## Actual result
1. List of orders without sorting.

**Comment by ghost** [comment]
For sorting any list following parameters need to be added with the url:
searchCriteria[page_size] = 100
searchCriteria[current_page] = 1
searchCriteria[sortOrders][0][field] = order_date (It is the field value on which sorting is to apply e.g. amount,order_date etc.)
searchCriteria[sortOrders][0][direction] = ASC

**Comment by springimport** [comment]
Yes, I use these parameters in query, but "sortOrders" doesn't work.

**Comment by springimport** [comment]
Any news?

**Comment by mbrinton01** [comment]
Hello @springimport I just tried to replicate this issue and was not able to do so.  I used the following:

```
"http://m2github.dev/index.php/rest/V1/orders?searchCriteria[pageSize]=100&searchCriteria[currentPage]=1&searchCriteria[sortOrders][0][field]=increment_id&searchCriteria[sortOrders][0][direction]=ASC"
```

which runs on my local machine install (not a public instance). I am using the latest code in the _develop_ branch.  Are you using the same version?

It returns the orders sorted by `increment_id`.  When I change the sort order to `DESC` the sort order is reversed.

**Comment by springimport** [comment]
I have a "version": "2.0.7" of Magento.
`http://domain.net/rest/V1/orders?searchCriteria[pageSize]=100&searchCriteria[currentPage]=1&searchCriteria[sortOrders][0][field]=increment_id&searchCriteria[sortOrders][0][direction]=ASC`

no difference

`http://domain.net/rest/V1/orders?searchCriteria[pageSize]=100&searchCriteria[currentPage]=1&searchCriteria[sortOrders][0][field]=increment_id&searchCriteria[sortOrders][0][direction]=DESC`

**Comment by mbrinton01** [comment]
@springimport can you check against `develop` branch?

**Comment by springimport** [comment]
@mbrinton01 Now I can't do it.

**Comment by mbrinton01** [comment]
What result do you get?

**Comment by springimport** [comment]
@mbrinton01 The same for different options.

**Comment by mbrinton01** [comment]
Thank you @springimport. I cannot replicate this bug but have created MAGETWO-55228 for our teams to look at the issue.

**Comment by cspruiell** [comment]
I am also unable to reproduce this bug in develop or 2.0.

**Comment by springimport** [comment]
@cspruiell Yes, I too don't see. I think this bug reproduce only in `<=2.0.7`.

**Comment by shilpsauce** [comment]
I'm seeing a sorting issue with increment id, on 2.2.2. I have 2 recent orders with the following order numbers: 1000210924 and 1000210933. When I use the API to get the orders >= 1000210924 && <= 1000210933, I'm also getting a really old order from before migration with increment id: 100021093 (note that there is 1 less digit in this increment id).

**Comment by mbrinton01** [comment]
@shilpsauce please create a new issue for the problem you are seeing in 2.2.2.
