### ISSUE TITLE
There are no commands defined in the “cache” namespace

### ISSUE THREAD

**Issue by elieobeid7** [magento/magento2#5201]
**Update**

Everything is working now but `There are no commands defined in the "cache" namespace` is still there. I tried `chmod 777 -R var/generation`, didn't fix a thing. AFAIK no module is enabled

```
   public_html]# bin/magento module:status
List of enabled modules:
Nosto_Tagging

List of disabled modules:
Magento_Store
Magento_AdvancedPricingImportExport
Magento_Directory
Magento_Theme
Magento_Backend
Magento_Backup
Magento_Eav
Magento_Customer
Magento_BundleImportExport
Magento_AdminNotification
Magento_CacheInvalidate
Magento_Indexer
Magento_Cms
Magento_CatalogImportExport
Magento_Catalog
Magento_Rule
Magento_Msrp
Magento_Search
Magento_Bundle
Magento_Quote
Magento_CatalogUrlRewrite
Magento_Widget
Magento_SalesSequence
Magento_CheckoutAgreements
Magento_Payment
Magento_Downloadable
Magento_CmsUrlRewrite
Magento_Config
Magento_ConfigurableImportExport
Magento_CatalogInventory
Magento_SampleData
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_CatalogSearch
Magento_CustomerImportExport
Magento_CustomerSampleData
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_Authorization
Magento_User
Magento_ImportExport
Magento_Sales
Magento_CatalogRule
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_Checkout
Magento_GoogleAnalytics
Magento_GoogleOptimizer
Magento_GroupedImportExport
Magento_GroupedProduct
Magento_Tax
Magento_DownloadableImportExport
Magento_Braintree
Magento_Integration
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_ConfigurableProduct
Magento_MsrpSampleData
Magento_Multishipping
Magento_NewRelicReporting
Magento_Newsletter
Magento_OfflinePayments
Magento_SalesRule
Magento_OfflineShipping
Magento_PageCache
Magento_Captcha
Magento_Paypal
Magento_Persistent
Magento_ProductAlert
Magento_Weee
Magento_ProductVideo
Magento_CatalogSampleData
Magento_Reports
Magento_RequireJs
Magento_Review
Magento_BundleSampleData
Magento_Rss
Magento_DownloadableSampleData
Magento_Authorizenet
Magento_OfflineShippingSampleData
Magento_ConfigurableSampleData
Magento_SalesSampleData
Magento_ProductLinksSampleData
Magento_ThemeSampleData
Magento_ReviewSampleData
Magento_SendFriend
Magento_Ui
Magento_Sitemap
Magento_CatalogRuleConfigurable
Magento_Swagger
Magento_Swatches
Magento_SwatchesSampleData
Magento_GroupedProductSampleData
Magento_TaxImportExport
Magento_TaxSampleData
Magento_GoogleAdwords
Magento_CmsSampleData
Magento_Translation
Magento_Shipping
Magento_Ups
Magento_UrlRewrite
Magento_CatalogRuleSampleData
Magento_Usps
Magento_Variable
Magento_Version
Magento_Webapi
Magento_WebapiSecurity
Magento_SalesRuleSampleData
Magento_CatalogWidget
Magento_WidgetSampleData
Magento_Wishlist
Magento_WishlistSampleData
Sm_BasicProducts
Sm_Categories
Sm_Deals
Sm_ImageSlider
Sm_ListingTabs
Sm_Market
Sm_MegaMenu
Sm_QuickView
```

The issue was there long before I installed nosto, I initially installed SM quickstart then upgraded it the latest magento version. if I clear the cache from admin area, I see no error. I need to fix it otherwise I'll never be able to install any module or [fix this](http://magento.stackexchange.com/questions/123015/configuration-for-db-connection-is-absent)

now I disabled nosto

**Comment by veloraven** [comment]
@elieobeid7 thank you very much for your efforts, but could you please add description of steps, actual result and expected result to this ticket? It will help other community members to find this problem when they use GitHub, which is unfortunately impossible when full description is placed on the external resource.

**Comment by orlangur** [comment]
@elieobeid7 for me such issue appeared from time to time on 2.0.x without any custom module, was related to `/var/generation` permissions (something like Magento generated some files on the fly which it was not able to read then).

**Comment by elieobeid7** [comment]
@veloraven will do so tomorrow i promise

**Comment by elieobeid7** [comment]
@orlangur are you suggesting `chmod 777 -R /var/generation`?

but var is already 777 -R so I don't know, but if that what you suggest then i'll have to give it another go

**Comment by orlangur** [comment]
First of all please try to spot reproducible steps. As for me this issue was quite occasional.

**Comment by elieobeid7** [comment]
@veloraven done, as promised

**Comment by elieobeid7** [comment]
@orlangur tried to chmod it, didn't fix it

**Comment by veloraven** [comment]
@elieobeid7 , thank you for update. 
Unfortunately, now it's not easy to understand what is it about, and what is your actual problem is.
So I have to ask you once more to format your issue according to templates: specifying exact steps to reproduce, actual result, and expected result. 
Additional please specify exact versions or tags you used.

**Comment by andimov** [comment]
@elieobeid7 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by ghost** [comment]
I'm having this issue after pulling down a project. After running `composer install`, I can run `bin/magento` but the cache commands are not available.
