### ISSUE TITLE
Unable to install sampledata in Magento 2.1.0

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#5202]
Tried to install sample data using:
`php bin/magento sampledata:deploy`
resulted in the following error:

> ...
> Your requirements could not be resolved to an installable set of packages.
> ...
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

**Comment by roma84** [comment]
Was able to install Sample Data after adding `repo.magento.com` in `composer.json`

```
"repositories": {
    "magento": {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
}
```

**Comment by stamster** [comment]
Setting repository in composer is mandatory, how CLI tool is suppose to fetch (from where) those packages if you don't set repo.

**Comment by MagePsycho** [comment]
Yeah, adding repository fixed the issue. But why it's not there in composer.json by default. In the prior version, I have never added that repo manually in order to install sample data. Is it a #bug ?

**Comment by ytorbyk** [comment]
Hi  @andimov 
Are you sure it is a question only?
I almost sure that the `sampledata:deploy` command has to add magento repo to the composer.json file (as it adds dependancies), hasn't it?
If yes, then it's a bug.

**Comment by BaDos** [comment]
Hi @MagePsycho 
Are you using Magento from Composer or Git?

If Magento was installed from Composer, then `sampledata:deploy` works correctly.
But if Magento was installed from Git, you should install Sample Data from [magento2-sample-data](https://github.com/magento/magento2-sample-data)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
