### ISSUE TITLE
Product CSV Import - Case-Sensitive URL Key Duplicates Check

### ISSUE THREAD

**Issue by lstellway** [magento/magento2#5203]
When importing Product CSV file: If a URL request path exists in a different case than the the url being imported, the import data will not validate and a vague exception error is shown.
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a product and specify a URL key
3. Create a product import file and specify an existing url_key for the product, but in a different case than the existing one
4. Import the file
## Expected result
1. After clicking "Check Data", an error "General system exception happened" should occur with no more specific details
## Actual result
1. Error message appears: "General system exception happened"

**Comment by lstellway** [comment]
Commit e1743fd41b038f19cb2bf0fdf4ba6a04ecd5cd69 fixes this

**Comment by wert2all** [comment]
@loganstellway can I close this issue now?

**Comment by lstellway** [comment]
@wert2all yes please, thank you!
