### ISSUE TITLE
Table "rule_customer" does not existe

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#5205]
Trying to get promo rule usage by customer.

Table "rule_customer" doesn't exist (https://github.com/magento/magento2/blob/59671558ecdab652b40db2d1a7c63d5b1dea0a92/app/code/Magento/SalesRule/Model/ResourceModel/Rule.php#L181)

The correct name is "salesrule_customer".

**Comment by veloraven** [comment]
Internal ticket MAGETWO-54781.

**Comment by ishakhsuvarov** [comment]
@bvboas Fix for this issue has now been delivered into the `develop` branch with the PR #5207
Thank you for reporting!
