### ISSUE TITLE
Not able to create customers, products etc.

### ISSUE THREAD

**Issue by SolPin** [magento/magento2#5206]
Installed Magento 2.1 from the downloaded package without the sample data

result: beside the store settings none of the other data is accessible and the loader i running without any result.

**Comment by JesseEnd** [comment]
I'm having this same issue after upgrading to 2.1.0 from 2.0.7

Additionally, Products -> Categories has a full window modal that never closes

edit:  The Categories issue was reported a few days ago - https://github.com/magento/magento2/issues/5150

**Comment by veloraven** [comment]
@SolPin thank you for your report.
This issue was connected with browser cache: it should be cleaned.
To avoid the same issue in future you can turn on the following option in admin area: 
_Stores -> Configuration -> Advanced -> Developer -> Static Files Settings -> **Sign Static Files = Yes**_

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
