### ISSUE TITLE
Unable to upgrade to Magento 2.1.0 CE via Web Wizard

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#5208]
## Steps to reproduce
1. Upgrade Magento 2.0.6 to 2.1.0 using web wizard
2. I have installed the MVDA-532.\* patch
## Actual result
1. The update wizard continues to run with following message, no success appears even after a long time:

```
[2016-06-24 04:23:01 UTC] Job "maintenance_mode {"enable":true}" has been started
[2016-06-24 04:23:01 UTC] Magento maintenance mode is enabled.
[2016-06-24 04:23:01 UTC] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-06-24 04:23:01 UTC] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.1.0"}]}" has been started
[2016-06-24 04:23:01 UTC] Starting composer update...
[2016-06-24 04:23:02 UTC] ./composer.json has been updated

```

**Comment by andimov** [comment]
@arvind07 
Thank you for reporting!
Please check:
- logs for errors
- cron is running
- timeout and memory limits (biggest value can fix this issue).

Also try to upgrade Magento through CLI.

**Comment by webspeaks** [comment]
@andimov 
Upgrade only works through cli. It never goes through web wizard. I have been observing this since 2.0.1.

Thanks

**Comment by oserediuk** [comment]
Hi, @arvind07! Did you resolve your issue?

**Comment by webspeaks** [comment]
@oserediuk Yes. Upgrade works through command line but not through web wizard.

**Comment by oserediuk** [comment]
Could you provide your some error logs, your timeout and memory limits? Seems that this configuration issue

**Comment by webspeaks** [comment]
I changed my memory limit to -1.
Then I used following commands:

```
composer require magento/product-community-edition 2.1.0 --no-update
composer update
rm -rf var/di var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex
```

**Comment by BaDos** [comment]
Hi @webspeaks 

I have upgraded Magento 2.0.6 to 2.1.0 via Web Wizard.

Just Magento 2.0.6 doesn't write anything during composer update via Web Setup Wizard.
It was fixed.
For example, Magento 2.0.10 every minute writes a message "Update is already in progress." during composer update.

If you have the same problem with 2.0.10, please reopen this issue.

Thank you.
