### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ramiaros** [magento/magento2#5209]
Step 6: Install

Installing... 92%
Installation is incomplete.
Check the console log for errors before trying again.

Module 'Magento_Swatches':
Installing data.. 
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Wrong attribute group ID' in /home/magento/public_html/vendor/magento/module-eav/Setup/EavSetup.php:622
Stack trace:
#0 /home/magento/public_html/vendor/magento/module-eav/Setup/EavSetup.php(1200): Magento\Eav\Setup\EavSetup->getAttributeGroupId('4', '10', 'General')
#1 /home/magento/public_html/vendor/magento/module-eav/Setup/EavSetup.php(799): Magento\Eav\Setup\EavSetup->addAttributeToSet('4', '10', 'General', 'swatch_image', 3)
#2 /home/magento/public_html/vendor/magento/module-swatches/Setup/InstallData.php(66): Magento\Eav\Setup\EavSetup->addAttribute('catalog_product', 'swatch_image', Array)
#3 /home/magento/public_html/setup/src/Magento/Setup/Model/Installer.php(821): Magento\Swatches\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#4 /home/magento/public_html/setup/src/Magento/Setup/Model/Installer.php(772): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#5 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#6 /home/magento/public_html/setup/src/Magento/Setup/Model/Installer.php(333): call_user_func_array(Array, Array)
#7 /home/magento/public_html/setup/src/Magento/Setup/Controller/Install.php(103): Magento\Setup\Model\Installer->install(Array)
#8 /home/magento/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /home/magento/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /home/magento/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /home/magento/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /home/magento/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /home/magento/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /home/magento/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /home/magento/public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /home/magento/public_html/setup/index.php(31): Zend\Mvc\Application->run()
#19 {main}

**Comment by tinelps** [comment]
is this error log from `var/log` ?

**Comment by wert2all** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by ramiaros** [comment]
Magento-CE-2.0.7+sample_data-2016-05-24-12-05-08.zip

**Comment by tinelps** [comment]
@ramiaros you don't seem to be very care about the problem >.<

**Comment by NadiyaS** [comment]
Hi @ramiaros ,
we can not reproduce this bug. Magento_Swatches module installs correctly with all its sample data.
Please check this installation again. Is this problem still actual for you?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
