### ISSUE TITLE
Pages with same URL key can't be saved for translation 

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#5210]
## Steps to reproduce
1. I do have pages in different languages
2. In old magento I used the same url key for different stores like this:
   http://stackoverflow.com/questions/32677845/magento-translation-and-url-key
## Expected result
1. Magento 2 should save pages with same URL key and different store.
## Actual result
1. Warning appears: "URL key for specified store already exists."

**Comment by wert2all** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by flipflap** [comment]
It is version Magento 2.0.7

**Comment by blizam** [comment]
I face this same issue trying to create pages on different websites/store views with the same URL key... the Pages Admin (bot from the main List and from within a Single Page) lacks a configuration scope setting letting Magento know you're not on the Default Store

**Comment by magento-engcom-team** [comment]
@flipflap, thank you for your report. Please make sure that you set up "Page in Websites" field with different store-views for both pages. 
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
