### ISSUE TITLE
Unable to install Latest Magento EE using composer

### ISSUE THREAD

**Issue by janagiram** [magento/magento2#5211]
## Steps to reproduce
1. Install Magento EE 2.0.1-rc3 using composer.
2. I have tried the following command "composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.0.1-rc3 magento2"
## Actual result
1. [Example] Error message appears: [InvalidArgumentException]
   Could not find package magento/project-enterprise-edition with version 2.0.1-rc3.

**Comment by wert2all** [comment]
Please report this issue in partner portal.
