### ISSUE TITLE
Area code is already set while upgrading to Magento EE 2.1.0

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#5214]
## Steps to reproduce
1. Upgrade **Magento EE 2.0.7** to **Magento EE 2.1.0** through command-line. (Patch MDVA-532 already applied)
2. Remove `var/di`, `var/generation`, `var/cache`, `var/page_cache`
3. Execute `bin/magento setup:upgrade`
## Expected result
1. The `setup:upgrade` command must running without any troubles
## Actual result

Throws an exception:

```
[Magento\Framework\Exception\LocalizedException]
  Area code is already set
```

![screenshot 2016-06-24 14 11 44](https://cloud.githubusercontent.com/assets/3891429/16330744/c0bc2260-3a15-11e6-9b3c-52356266dc7b.png)

**Comment by wert2all** [comment]
Please report this issue to the partner portal.
