### ISSUE TITLE
when i checked product custom option at that time each custom product option price add in real price as well as related price

### ISSUE THREAD

**Issue by mekiran16** [magento/magento2#5215]
Hi
I  am making one new store in magento 2, 
In which i created more then 10 products with custom option, then after view open any product with custom option, then after i will checked any custom option at that time i face one price issue, in magento 1x , when i checked custom option at that time change only current product price but not any change price of related product as well as upsell product, But in magento 2x, its  effect on all product show related product As well as upsell product  in current view product, so please can  give me some solution as soon as possible

please see below link.
http://45.79.161.105/catstructure/weisse-herzballons-1.html

before checked custom option see price for all place
http://45.79.161.105/catstructure/pub/before%20checked%20custom%20option.png
And after checked custom option see price for all place
http://45.79.161.105/catstructure/pub/after%20checked%20custom%20option.png

Thank You.

**Comment by mekiran16** [comment]
Hello every one please give me some solution
Thanks

**Comment by andimov** [comment]
@mekiran16 
Thank you for reporting this issue!
To allow us research the issue, please, provide description according to the template.

**Comment by mekiran16** [comment]
i have used Magento 2 default luma theme, i created new product with one custom option , And this product in which i assign 4 to 5 related products, then after i open this product in front end , then after i have checked custom option of this product, then after custom price value is added with original product as well as added of related product. And also you have to see above link, please checked it,

Thank You.

**Comment by andimov** [comment]
@mekiran16  Please, provide description according to the template: https://github.com/magento/magento2/issues/new

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by chiragayartops** [comment]
I use magento2 custom theme and i have same problem please give me some solution
Thanks.
