### ISSUE TITLE
Swatch does not show on product listing page

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#5216]
## Steps to reproduce
1. Install Magento version 2.1
2. Add configurable product has text swatch or visual swatch
## Expected result
1. Swatches should show on product listing page
## Actual result
1. Swatches do not show on product listing page
   See attached
   ![2016-06-24_16-15-57](https://cloud.githubusercontent.com/assets/1607243/16333708/f96cbbc2-3a26-11e6-841d-6d76a37f416e.jpg)
   ![2016-06-24_16-12-45](https://cloud.githubusercontent.com/assets/1607243/16333710/fc30d776-3a26-11e6-8850-b052aae1a74a.jpg)

**Comment by phuc128t** [comment]
It seems "jsonSwatchConfig" has no data.
![2016-06-24_16-37-44](https://cloud.githubusercontent.com/assets/1607243/16334285/2ae61754-3a2a-11e6-8c16-3a157a51b2cc.jpg)

**Comment by wert2all** [comment]
Thanks for reporting.  Internal ticket MAGETWO-54767 was created.

**Comment by phuc128t** [comment]
Sorry, this is not a bug. We need to turn "Used in Product Listing" on to show swatch attributes on listing page.

**Comment by koenner01** [comment]
This is indeed not a bug, but the functionality of 'Use in Product Listing' should not be coupled with showing the swatch on the product listing.

If you turn of the 'use in listing', you will lose the attribute in the flat collection.

Imho there should be an extra yes/no to decide if the swatch should be shown on product listing. That way you can keep the functionality on the filters & product detail.

**Comment by unihosiery** [comment]
I have a same issue and checked source code. Datas for swatch rendering is there but still not showing color swatches. How can I solve thhis?
![img1](https://cloud.githubusercontent.com/assets/25332272/22266691/d195c276-e235-11e6-97f9-882c65af8d8d.jpg)
