### ISSUE TITLE
js-translation.json bugs | Issues when translating validation js messages

### ISSUE THREAD

**Issue by Pigau** [magento/magento2#5217]
Hello,

I am on a Magento 2.0.2. My locale is french (fr_FR).

I have a custom theme which have its js-translation.json file.

I noticed two distinct errors.
- First, a sentence which exists in the file is not translated on the front. But others sentences in this file are translated.
  Sentence not translated : "Please enter a valid email address (Ex: johndoe@domain.com)."
  Sentence translated : "This is a required field."
- Second error : I have another JS validation sentence which is "Please select one of the options." and I don't know why but it is not in the js-translation.json file.

I created a language package (which is working) and I added in this those lines : 
"Please select one of the options.","Veuillez choisir une des options.",module,Magento_Translation
"Please select one of the options.","Veuillez choisir une des options.",component,Magento2_Base
"Please select one of the options.","Veuillez choisir une des options.",lib,lib/web/mage/validation.js

I tried reploying static content, even after removing the js-translation.json in app/design/mynamespace/mytheme/js-translation.json. This file is regenerated but unchanged.

So I read this ticket :https://github.com/magento/magento2/issues/2056
And then I followed this page : http://www.vanderboon.net/wiki/Install_Test_Magento_2_Translation
But now, after I did the symlink, my file is not regenerating in app/design/mynamespace/mytheme/.
But the files in pub/static are regenerated, but they are still wrong.

Do you guys have any idea ?
Thanks

**Comment by dimasch** [comment]
+1 the same issue on 2.0.7 for generate theme translations. For separate modules is ok.

**Comment by veloraven** [comment]
@Pigau is this issue still actual?
If it is and you think it to be an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it was just a question please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
