### ISSUE TITLE
Any admin grid does not load after upgrade to 2.1.0

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#5219]
## Steps to reproduce
1. Upgraded to 2.1.0 from 2.0.7
2. Go to admin grid (products, cms or any other grid)
## Actual result
1. Grid does not load, following JavaScript error found in JS console:
   `Uncaught Error: You cannot apply bindings multiple times to the same element.      knockout.js:2908`

Screenshot: http://joxi.ru/n2Ykn50hjzEW9r

**Comment by andimov** [comment]
@arvind07
This is similar that old files are loaded from the cache
Clean cache in browser(ctrl+shift+del in Chrome) and server-side cache, e.g. varnish and try again.

**Comment by webspeaks** [comment]
Hi,
Obviously I cleared all caches properly. But the issue still persists.

**Comment by webspeaks** [comment]
I even cleared the static files for admin and regenerated all static content. No success though.

**Comment by webspeaks** [comment]
I opened the admin panel in incognito mode and it worked!

Sorry, my fault. This is not a bug.

**Comment by aupong** [comment]
Clearing the browser cache can help

**Comment by RSrail** [comment]
Clearing browser cache worked for me. Cleared last 4h (firefox)
