### ISSUE TITLE
cannot save the customer issue

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#522]
I have installed Magento 2 And i got this issue ..
while registering new customer from front end i got the message cannot save customer 
![customersave](https://f.cloud.github.com/assets/6836510/2306924/bd9106f4-a29c-11e3-9af7-24af8e4d217d.png)

**Comment by vishveskrish** [comment]
This issue resolved by  put session to 'db' instead of 'files'

**Comment by vishveskrish** [comment]
Please find app/etc/env.php  and change "'session_save' => array('save' => 'files')" to "session_save' => array('save' => 'db')" for the magento 2 bug

**Comment by OZZlE** [comment]
I debugged this and got this "Email template '23' is not defined." using 2.1.7, have used the migration tool if that has to do with anything.

Happens every time you try to register a new customer.. He/she is saved in DB but no email is sent out and the response is only "Cannot save the customer"

**Comment by OZZlE** [comment]
![image](https://user-images.githubusercontent.com/893783/28452450-13df69c2-6df3-11e7-9926-884572cb6f1c.png)

**Comment by OZZlE** [comment]
Tried with a clean database and could not reproduce it then.. so it seems it's somehow related to the database.. maybe the migration tool..

**Comment by deepshik** [comment]
Hello, when i register new customer on magento 2, it gives error We can\'t save the customer
how to solve

**Comment by OZZlE** [comment]
If you have a custom theme with templates containing `<form>`, verfiy that those contain the formkey also! That was my issue, page was just reloading without any error (but no signup either).

E.g:
`<form><?php /* @noEscape */ echo $block->getBlockHtml('formkey'); ?>`

**Comment by deepshik** [comment]
i have change
on /vendor/magento/module-customer/Controller/Account/createpost.php file
here is my code
$this->messageManager->addException($e, __('We can\'t save the customer.'));

it gives error we cant save the customer

**Comment by OZZlE** [comment]
@deepshik you modified core to throw an exception and now you are surprised that it does? Or what are you trying to say?

My post was about if you have made your theme for an older version of magento and haven't added the formkeys then you need to do that. Otherwise the create account form just reloads the page when you submit it.

**Comment by deepshik** [comment]
everything working fine with my magento 2 theme , only issue in user
registration , i have already change in my core file , but there was no any
changes on registration .
so how to solve i m using magento 2.2.2 version

**Comment by deepshik** [comment]
Hello,
i have registred in magento 2 , registration sucess but gives error cant
save the customer
how to solve

**Comment by deepshik** [comment]
i have also  put session to 'db' instead of 'files' in env.php but there is
no any changes , it gives cant save the customer

**Comment by AdminAngel** [comment]
I just upgraded from 2.4.1 to 2.4.2 and started to have the same problem...
On front end customers can't register, getting "We can't save the customer." Error...
Please help!

**Comment by engcom-Golf** [comment]
@AdminAngel I have Created a Customer via Frontend on **Magento 2.4.2** & **2.4-develop branch**. Which successfully created and redirected me on the Dashboard Page.

**Comment by AdminAngel** [comment]
What is the difference between 2.4.2 and 2.4.2-p1?
