### ISSUE TITLE
Unable to reindex

### ISSUE THREAD

**Issue by rushabhrakholiya** [magento/magento2#5224]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by andimov** [comment]
@rushabhrakholiya 
please, provide description according to the template.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
