### ISSUE TITLE
API GET cart billing-address is without address data

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#5227]
## Steps to reproduce
- Magento v.2.0.5
- REST API
- customer logged, created cart, added product to cart, created customer address

address from GET customers/me
{
            "id": 6,
            "customer_id": 4,
            "region": {
                "region_code": null,
                "region": null,
                "region_id": 0
            },
            "region_id": 0,
            "country_id": "SK",
            "street": [
                "test 10"
            ],
            "telephone": "1234567890",
            "postcode": "91790",
            "city": "City Ten",
            "firstname": "Rasto druha adresa",
            "lastname": "test 2"
        }
- selected billing address POST V1/carts/mine/billing-address
## Expected result
- the same address data as they are in GET customer/me
## Actual result

{
    "id": 6,
    "region": null,
    "region_id": null,
    "region_code": null,
    "country_id": null,
    "street": [
        ""
    ],
    "telephone": null,
    "postcode": null,
    "city": null,
    "firstname": null,
    "lastname": null,
    "customer_id": 4,
    "email": "test3@gmail.com",
    "same_as_billing": 1,
    "save_in_address_book": 0
}

**Comment by SerhiyShkolyarenko** [comment]
@RUjmiak could you please clarify which data you post to /V1/carts/mine/billing-address?

**Comment by RUjmiak** [comment]
@SerhiyShkolyarenko it was just
{
  "address": {
    "id": addressId
  }
}

**Comment by SerhiyShkolyarenko** [comment]
@RUjmiak customer address and quote billing address are two **different** entities in magento. To set billing address you have to send the whole data set. It may look like:
`{
  "address": {
    "region_code": "LA",
    "country_id": "US",
    "street": [
      "some street"
    ],
    "company": "user company",
    "telephone": "58585733",
    "fax": "",
    "postcode": "345344",
    "city": "Comfortable city",
    "firstname": "Sam",
    "lastname": "Smart",
    "middlename": "",
    "prefix": "",
    "suffix": "",
    "vat_id": "",
    "email": "smartsam@magento.com",
    "save_in_address_book": 0,
    "extension_attributes": {},
    "custom_attributes": [
    ]
  },
  "useForShipping": false
}`

**Comment by SerhiyShkolyarenko** [comment]
As far as it was expected behavior, i close the issue. Please, feel free to add your notes for reopening.
