### ISSUE TITLE
No Migration Tool available for Magento 2.1

### ISSUE THREAD

**Issue by SolPin** [magento/magento2#5228]
Tried to install the Migration Tool for 2.1, but getting the following error:
- The requested package magento/data-migration-tool 2.1 exists as magento/data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7] but these are rejected by your constraint.

Installation failed, reverting ./composer.json to its original content.

Doesn't matter if you type in 2.1 or 2.1.0 - the result is the same.

**Comment by andimov** [comment]
@SolPin 
To allow us research the issue, please, provide description according to the template.

**Comment by andimov** [comment]
Please, adress all issues regarding Migration Tool to https://github.com/magento/data-migration-tool repository.
