### ISSUE TITLE
Upgrading from 2.0.7 to 2.1.0 from Setup Wizard failed due to data-migration-tool  version

### ISSUE THREAD

**Issue by SolPin** [magento/magento2#5232]
## Steps to reproduce
1. upgrading from 2.0.7 to 2.1.0 from Setup Wizard
## Expected result

Steps to reproduce

upgrading from 2.0.7 to 2.1.0 from Setup Wizard
Expected result

Magento 2.1 installed
## Actual result

**Step 2:** Readiness Check could not be completed because of the following error.

**Check Component Dependency**
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1

Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
magento/data-migration-tool 2.0.7 requires magento/framework ~100.0.0 -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
Can only install one of: magento/framework[100.1.0, 100.0.2].
Can only install one of: magento/framework[100.1.0, 100.0.3].
Can only install one of: magento/framework[100.1.0, 100.0.4].
Can only install one of: magento/framework[100.1.0, 100.0.5].
Can only install one of: magento/framework[100.1.0, 100.0.6].
Can only install one of: magento/framework[100.1.0, 100.0.7].
Can only install one of: magento/framework[100.1.0, 100.0.8].
Can only install one of: magento/framework[100.1.0, 100.0.9].
magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
Installation request for magento/data-migration-tool 2.0.7 -> satisfiable by magento/data-migration-tool[2.0.7].
For additional assistance, see component dependency help .

**Comment by kandrejevs** [comment]
Same result when upgrading via composer. removing magento/data-migration-tool from composer.json allows updating magento to 2.1, but does not allow to install data-migration-tool afterwards.

**Comment by Caprico85** [comment]
Data migration tool for Magento 2.1 is not available yet. Can take a few weeks according to https://github.com/magento/data-migration-tool/issues/97.

**Comment by andimov** [comment]
@SolPin
Thank you for reporting!
But I closed it as Migration Tool issue.
If this issue is still actual for you, please create a ticket here https://github.com/magento/data-migration-tool/issues
