### ISSUE TITLE
Trying update 2.0.7 to 2.1 with Web Setup Wizard

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5235]
## Steps to reproduce

Logged in admin and navigate to `System > Tools > Web Setup Wizard`
## Expected result

Open Web Setup Wizard to upgrade.
## Actual result

Redirected to `/setup/index.php/session/unlogin` with 401 status.

**Comment by andimov** [comment]
@rbostan 
Thank you for reporting!
Looks like upgrade is already started.
This issue is still actual?

**Comment by cizgidekiadam** [comment]
@andimov 
I have no success to upgrade. So made a clean install.
But at new install, problem still exists. Can not access Web Setup Wizard in 2.1

**Comment by ghost** [comment]
Is your docroot `pub`? If so, then this is expected behavior. `pub` and `setup` are on the same level so that no one can run the Web Setup Wizard in production. (We recommend you set your Magento docroot to `pub` in production.)

To work around it, set your docroot to the Magento install dir and the wizard should work.

**Comment by cizgidekiadam** [comment]
Docroot is not /pub. 

Also if it is, in 2.1, "The Web Setup Wizard now works when Magento is installed in /pub. [GITHUB-4159](https://github.com/magento/magento2/issues/4159)"

**Comment by ghost** [comment]
Sorry, I didn't know that. What web server are you using?
Is the `setup` directory readable by the web server user?

**Comment by cizgidekiadam** [comment]
/setup is readable and server is CentOS with apache

**Comment by NadiyaS** [comment]
Hi @rbostan ,
seems like your session was expired or value of 'admin/security/session_lifetime' less than 60. To check this value go to Stores > Settings > Configuration > Advanced > Admin > Security > Admin Session Lifetime. Default value for session lifetime is 900.

**Comment by cizgidekiadam** [comment]
Hi @NadiyaS 
I don't think so.
I have tried that right after the login. So it was not took 20secs.

But doesn't matter, I have made a clean install to 2.1 and update 2.1.1 via composer.
It is working fine now.

**Comment by NadiyaS** [comment]
Ok, so I close this issue as not reproducible. Feel free to reopen it if you encounter with the same problem.
