### ISSUE TITLE
Upgrade from 2.0.7 to 2.1.0 gives many errors 

### ISSUE THREAD

**Issue by richardreen** [magento/magento2#5236]
After upgrading from 2.0.7 to 2.1.0 there are several errors:
1. Categories don't show no products anymore [frontend}
2. Tried to update a configurable products results in errors
   - Can't create directory /srv/www/webshop2/var/generation/Magento/Catalog/Model/Product/Attribute/Backend/Tierprice/. 
   
   I manual added this directory
   Second try results in error again
   -"Can't create directory /srv/www/webshop2/var/generation/Magento/Catalog/Model/Product/Attribute/Backend/Boolean/.

Also added this directory.
Third try results also in error again
"The configuration parameter "componentType" is a required for "advanced_pricing_button" component."

Back to admin page, now also error
-"The configuration parameter "componentType" is a required for "advanced_pricing_button" component."

Error stuck now....

**Comment by paales** [comment]
@richardreen Looks like a permission problem. Please take a look at this article first. http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by Protazy21** [comment]
It is happening to me also after upgrade from 2.0.7 to 2.1. I don't have permissions problem, however products aren't displaying in any category. When I want to edit any product I'm getting "There has been an error processing your request" in report file I can find:
a:4:{i:0;s:98:"The configuration parameter "componentType" is a required for "advanced_pricing_button" component.";i:1;s:8025:"#0 /var/www/html/devel.test.com/vendor/magento/framework/View/Element/UiComponentFactory.php(360): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)

**Comment by mreichh** [comment]
same for me. Also followed http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html, step 4.

Any idea why this issue occurs?

**Comment by Protazy21** [comment]
I've managed to fix editing products, here is what I've done

Class vendor/magento/module-configurable-product/Ui/DataProvider/Product/Form/Modifier/ConfigurablePrice.php

@@ -92,7 +92,7 @@ class ConfigurablePrice extends AbstractModifier
                             self::$advancedPricingButton => [
                                 'arguments' => [
                                     'data' => [
                                         '~~config' => $visibilityConfig,~~
                                         'config' => ['componentType'=>'container',$visibilityConfig],
                                     ],
                                 ],
                             ],

pull request can be found here #5411

**Comment by rudik99** [comment]
Hi @Protazy21 I tried the above and it didnt work. did you do anything else? 

I got this:  

Notice: Undefined offset: 118 in /usr/local/lsws/test/magento21/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

**Comment by Protazy21** [comment]
Is your database migrated by any chance? I've faced this issue but with id 119 and few more. In your case 118 is attribute id, check your database table eav_attribute, I believe that the attribute with this id doesn't exist but it is still part of your product. If the attribute doesn't exist find all references to it in other tables and delete records where column attribute_id = 118. Repeat for other ids if necessary

**Comment by developer-lindner** [comment]
Hi @Protazy21 thanks for the hint! Can't believe that such an error flows into a 2.1.0 release... After changing the file it worked! Had a look and just thought the grid layout is broken, but they've just changed it to accordion style?!

**Comment by mreichh** [comment]
@Protazy21: Thanks for that. Solves the backend error "The configuration parameter "componentType" is a required for "advanced_pricing_button" component."

"Categories don't show no products anymore" error still there though...

**Comment by rudik99** [comment]
@mreichh try re-indexing the database a couple of times and clear the cache, i find that fixes that issue for me on the odd occasion i have it.

**Comment by quynhvv** [comment]
@Protazy21: 
I get this issue too after migrated data from Magento 1.9.2.x to Magento 2.1.0 via migrate tool at
https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/
and solved by your shared.
Hope Magento will has fixes to handle this in next version ASAP.
Thanks.

**Comment by rudik99** [comment]
@Protazy21 Whats the best way to find the those attributes in the Database and remove?

**Comment by rou9e** [comment]
Hey there,
I did the update suggested by @Protazy21 : 

`'config' => ['componentType'=>'container',$visibilityConfig],`

But now I get this error : 

`The configuration parameter "componentType" is a required for "" component.`

Any clue ?

**Comment by Protazy21** [comment]
@nowayyy36 sorry it doesn't say for which element so no clue, however the exception is thrown from class Magento\Framework\View\Element\UiComponentFactory Line 341

<pre>
if (!isset($data['arguments']['data']['config']['componentType'])) {
                    throw new LocalizedException(new Phrase(
                        'The configuration parameter "componentType" is a required for "%1" component.',
                        [$name]
                    ));
                }
</pre>

Run it through debugger or place var_dump on data to get some information.

**Comment by Protazy21** [comment]
Fix for showing products in category
Magento\CatalogInventory\Model\Configuration
function getDefaultScopeId() always returns 0 (admin id)
converting to this helps:
public function getDefaultScopeId()
    {
        // TODO: should be fixed in MAGETWO-46043
        // "0" is id of admin website, which is used in backend during save entity
        $scopeId = $this->storeManager->getWebsite()->getId();
        return $scopeId;
    }
In this case if you do any actions in admin 0 will be returned, if on frontend current website id.

Other issues I've found, can't open any product on frontend (404), in backend even though I've managed show edit product form, it shows only half of information, for example products have no name, title etc, can't edit variations, saving products doesn't help and newly saved changes aren't displaying. Looks like issues are related to configurable products.

**Comment by Ctucker9233** [comment]
After updating to Magento 2.1 from 2.0.7 I can't see my catalog navigation anymore. Anyone experience this issue? If not, I'll open a new issue. I know my products are still there and I can search and find products in the frontend. Anyone have a fix for this?

**Comment by davidbilly** [comment]
@Ctucker9233 , we're same boat :( upgraded from 2.0.4 CE

<img width="1915" alt="screen shot 2016-07-03 at 5 24 43 am" src="https://cloud.githubusercontent.com/assets/3938103/16542522/ae367a26-40de-11e6-9a77-869c20db51f6.png">

**Comment by Ctucker9233** [comment]
@davidbilly I can see all my products in the backend just fine. In the frontend, it's missing the nav bar that the customer would use to browse through products. It's strange though that the products show up when a customer searches for something. That's the only way products can be viewed on the frontend right now. I'm currently reverting to 2.0.7. :(

**Comment by davidbilly** [comment]
@Ctucker9233  It's weird, my front-end look good. Just back-end screw up :(  The reason I upgrade to 2.1.0 because it has fix for sub-product set price 0 issue lol

Is it composer require magento/product-community-edition 2.0.7 --no-update Can reverse back?

**Comment by Ctucker9233** [comment]
I'm afraid that doesn't work. I just tried it. Looks like I'm stuck with 2.1 for now. The old magento had a way to roll it back. _Feature Request: version rollback_

**Comment by Ctucker9233** [comment]
Well, at least i'm back to where I was. Magento, why doesn't the catalog nav bar show up in the frontend any more? WTH?

**Comment by davidbilly** [comment]
@Ctucker9233 using 2.1.0 DB data? Mine 2.1.0 after add cart not updating checkout.

**Comment by Ctucker9233** [comment]
@davidbilly Not sure what you mean. I went through the documented method for upgrading so I would assume i'm using the upgraded DB.

**Comment by ruud3007** [comment]
After upgrading I still have the following error:
Notice: Undefined offset: 88 in /home/tm/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

I checked in the database, but this attribute does exist... In fact it is Media Gallery

![screen shot 2016-07-04 at 00 22 30](https://cloud.githubusercontent.com/assets/20240863/16547929/6cd52664-417d-11e6-9e98-0568e3260174.png)

**Comment by AntonEvers** [comment]
@uinique-ruud I have the same problem, but all attributes that have this problem are missing from `catalog_eav_attribute` while they are product/category attributes. They are indeed present in `eav_attribute`

**Comment by ruud3007** [comment]
@ajpevers in my case it is even in that table...
![screen shot 2016-07-04 at 11 38 51](https://cloud.githubusercontent.com/assets/20240863/16556743/f9ef076e-41db-11e6-9bc7-f8f0c16bb75a.png)

**Comment by AntonEvers** [comment]
Can you find it in the backend in the product attribute management? I couldn't find mine there either.

**Comment by ruud3007** [comment]
Yes I can also find it there...

![screen shot 2016-07-04 at 11 50 15](https://cloud.githubusercontent.com/assets/20240863/16557008/933ad730-41dd-11e6-86f7-29c182b14044.png)

But when I open a product page in the admin:

![screen shot 2016-07-04 at 11 51 16](https://cloud.githubusercontent.com/assets/20240863/16557026/a8779692-41dd-11e6-9dfc-3410d42bbaa2.png)

**Comment by AntonEvers** [comment]
I think we can then conclude we have different problems with the same outcome. I added a row to `catalog_eav_attribute` for the faulty attribute id and with all the default column values, reindexed, flushed cache and the error went away in my case.

**Comment by ruud3007** [comment]
I think there is only one solution for me, which is install version 2.0.7 again...
Do a new data migration and start over.

What I know for sure is that I am not happy at all with Magento 2, which is causing way more issues than it did with Magento 1. Also I hate them awefull frontend framework. I have to look for another platform in the future.

**Comment by Ctucker9233** [comment]
@magento-team Someone please check this stuff out

**Comment by andimov** [comment]
@Ctucker9233 @davidbilly 
Did you clean all kind of cache from server and browsers?
If you have varnish you need to restart it to.
@richardreen 
Did you check permissions as @paales adviced?

**Comment by ruud3007** [comment]
@andimov and what about my issue?
I did everything you said above...

**Comment by Ctucker9233** [comment]
@andimov I cleared var/view_preprocessed, var/page_cache, var/cache and pub/static/frontend. I cleared my siteground (web host) caches as well. Am I missing anything?

**Comment by Ctucker9233** [comment]
Also browser caches

**Comment by andimov** [comment]
@uinique-ruud 
Thank you for reporting! You have different issue, so it would be correct to create a new issue according to the template to allow us investigate and process it with more attention.
For first look it seems to broken db data structure.

**Comment by Ctucker9233** [comment]
@andimov See also Issue #5423 for more information on my particular issue.

**Comment by lucscu** [comment]
Why do you continue to release bugged software? I'm working to magento2 from january and every day and every update new issues.
Do you like this?

**Comment by developer-lindner** [comment]
@LucScu Same here. Code Quality suffers hardly...

**Comment by ruud3007** [comment]
@LucScu I totally agree. Even I want to add the following. Coding in Magento 2 became much harder than with the old version. Specially the frontend is a big disaster. I am scared what the future will bring.

**Comment by developer-lindner** [comment]
@uinique-ruud frontend is fine, the backend is the big problem obviously...

**Comment by ruud3007** [comment]
@developer-lindner than you are the first one I hear that the overload of XML in the frontend is fine...

**Comment by developer-lindner** [comment]
@uinique-ruud well, you did not mention what exactly is wrong with the frontend. could you give some more detail?

**Comment by ruud3007** [comment]
@developer-lindner as I said above, the overload of XML is really hard to work with. I am working as a frontend dev since 1994, but what I see here is the worst I ever worked with.
Since mage 2 I need 3 x more time than with mage 2. Even simple tasks are hard to do.

A frontend developer wants more control in direct html/php files.

Als the AJAX cart resolves in a lot of JS errors.

**Comment by ruud3007** [comment]
@developer-lindner and also, the power of Magento 1 was that rookies could also install a Mage shop. This is why the mage community has grown so huge. With this big community you attracted a lot of developers, which concludes in more modules for a reasonable price.

With Mage2 it is impossible for a beginner to install his own webshop.

**Comment by developer-lindner** [comment]
@uinique-ruud mage community has grown so huge because of the professional, open-source base, the features it has, it's extensibility and the money one can earn with it.

In my opinion Magento 1 or 2 was never meant to be used by bloody rookies.
It's a professional e-commerce system for professional companies / users / developers.
If it's too hard for you, you may have to improve your skills first, before blaming without understanding what the MageDev Team achieves here. Such a system can't be made for rookies without lacking of best practices.

If you want simple 1-click solution go to Wordpress + Woocommerce.

**Comment by Tjitse-E** [comment]
I have the same problem as Protazy21 (no products on the frontend + unable to edit products  in the backend), although his fix doesn't work for me. I've used the data migration tool on Magento 2.0.4 and upgraded to 2.0.7 and 2.1 afterwards.

New error, after applying the fix from @Protazy21:
Notice: Undefined offset: 118 in /vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

**Comment by Protazy21** [comment]
@Tjitse-E 

I’ve solved all my problems and all is working for me OK. 

Undefined offset: 118 means that you have attributes that either need to be deleted or if you don’t want to delete anything then add them to correct tables - can't tell you which one atm.

Problematic attributes for me as far as I remember were msrp_default, for second one don’t remember the label but value was index,follow, third one don’t remember atm 😊 

Check tables like catalog_product_entity_varchar, catalog_product_entity_text, catalog_product_entity_int for attribute_id 118 and delete all records where they exists  like this example (change table name for correct one ;) )

<pre>
DELETE FROM catalog_product_entity_varchar WHERE attribute_id = 118 ;
</pre>

Repeat for other attributes if needed changing table and attribute_id.

They are easy to find using phpmyadmin, just search all tables for exact value 118, if you have a lot of products affected then it will be the table with most results 

Once all attributes are deleted your frontend will show up.

Check logs, it will tell you all problematic attribute ids you need to sort out.

**Comment by ruud3007** [comment]
@developer-lindner I don't think this is the place to discuss my qualities and knowledge, but saying that a developer with 8 year Magento experience and 20 year frontend development is not good enough is not up to you. The only thing I notice is that simple changes take way more time than before...

I agree with you that they have a meaning with this, but it doesn't make me agree with them. But future will see...

**Comment by developer-lindner** [comment]
@uinique-ruud True, what i've wanted to say is that we, as developer, have to develop as the system develops and rookies have to do the same. I also don't agree with everything which is introduced by now, like Less + server-side compilation of it for example...

**Comment by Tjitse-E** [comment]
@Protazy21, thanks for you help! This solved my issue.

Steps that i've taken:
1. Appy pull request #5411 
2. Try to edit a product and correct the database if necessary
`DELETE FROM catalog_product_entity_varchar WHERE attribute_id = xxxx ;`
3. Apply the fix for showing products in category (Magento\CatalogInventory\Model\Configuration)
4. Reindex and clean cache.

**Comment by ruud3007** [comment]
@developer-lindner with less I can live, with the service side compilation I can live as well (although I don't really like it, there are solutions for the developers), but for me the biggest issue is de XML templating... I know it is best practice regarding the designer guides, but that is not always reallity.

If they wanted to create a better frontend, I would have chosen something different. I would prefer Angular JS as frontend....

**Comment by developer-lindner** [comment]
@uinique-ruud well, but than you need a solution for SEO. And AngularJS is even harder for some people if you go for version 2 of it.

**Comment by thomasnordkvist** [comment]
I have this issue when i try to create or edit a bunde product after upgrading to 2.1.0
"The configuration parameter "componentType" is a required for "tier_price" component

Any ideas on that?

**Comment by thomasnordkvist** [comment]
My issue was that i had moved the tier_price attribute to the Product Details group in the attribute set.
I moved it back to the group Advanced Pricing and then the bundle product seem to work again.

**Comment by developer-lindner** [comment]
@Protazy21 I've got the same issue and tried to find this attribute_id as you mentioned above
but couldn't find any entry?!

Any idea how to fix it?
The exception looks like that:
Notice: Undefined offset: 63 in /vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

Btw how comes that it worked in 2.0.7 and now it's not?

**Comment by lucscu** [comment]
DELETE FROM catalog_product_entity_varchar WHERE attribute_id = 63 ;

**Comment by developer-lindner** [comment]
@LucScu there is no entry with attribute_id 63 ?!

**Comment by lucscu** [comment]
try to check others catalog_product_entity_\* in base of which type of attribute is your eav 63

**Comment by developer-lindner** [comment]
@LucScu i already did, and that's the fun part... i couldn't find anything where attribute_id is 63 ?!

**Comment by Protazy21** [comment]
@developer-lindner have you got phpmyadmin? search all tables in phpmyadmin for exact value 63, if you have a lot of products with this attribute it will be the table with most results. If not open each table where you get results and see if there is column attribute_id with value 63. In search set find as Exact phrase, inside table - select all click go

> @LucScu

 i already did, and that's the fun part... i couldn't find anything where attribute_id is 63 ?!
Cache??

**Comment by developer-lindner** [comment]
@Protazy21 I've deleted var/cache, var/page_cache, var/generation, couldn't find any entry in any table.
I don't get it what's going on... Any help / hint highly appreciated!

**Comment by Protazy21** [comment]
@developer-lindner  how about about log file? does it complain about any other attribute_id which hasn't been deleted yet?

**Comment by developer-lindner** [comment]
@Protazy21 just getting this report:

```
a:4:{i:0;s:134:"Notice: Undefined offset: 63 in /app/code/Magento/Eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:6937:"#0 /app/code/Magento/Eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/Users/thomas/S...', 166, Array)
#1 /lib/internal/Magento/Framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#2 /lib/internal/Magento/Framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /lib/internal/Magento/Framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Category\Interceptor), 2, Array)
#4 /app/code/Magento/Catalog/Model/ResourceModel/Category.php(996): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Category\Interceptor), 2)
#5 /var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(336): Magento\Catalog\Model\ResourceModel\Category->load(Object(Magento\Catalog\Model\Category\Interceptor), 2, NULL)
#6 /lib/internal/Magento/Framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Category\Interceptor->load(Object(Magento\Catalog\Model\Category\Interceptor), 2, NULL)
#7 /var/generation/Magento/Catalog/Model/Category/Interceptor.php(1480): Magento\Framework\Model\AbstractModel->load(2, NULL)
#8 /app/code/Magento/Catalog/Controller/Adminhtml/Category.php(40): Magento\Catalog\Model\Category\Interceptor->load(2)
#9 /app/code/Magento/Catalog/Controller/Adminhtml/Category/Edit.php(75): Magento\Catalog\Controller\Adminhtml\Category->_initCategory(true)
#10 /var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#11 /lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute()
#12 /app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /lib/internal/Magento/Framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#15 /lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#16 /app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#19 /app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /lib/internal/Magento/Framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /lib/internal/Magento/Framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 /lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /lib/internal/Magento/Framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#31 /pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#32 {main}";s:3:"url";s:106:"/admin_17z3bf/catalog/category/index/key/69935eb4900b8ee2309cdab614537852a2faf049bef234d3d47987ba588ca909/";s:11:"script_name";s:10:"/index.php";} 
```

**Comment by Protazy21** [comment]
@developer-lindner 
Do following
1. bin/magento cache:clean
2. bin/magento indexer:reindex
3. Class Magento\Eav\Model\ResourceModel\ReadHandler

line 161

$unionSelect = new \Magento\Framework\DB\Sql\UnionExpression(
                $selects,
                \Magento\Framework\DB\Select::SQL_UNION_ALL
            );

$selects consists of 5 tables
1. catalog_product_entity_varchar
2. catalog_product_entity_text
3. catalog_product_entity_decimal
4. catalog_product_entity_datetime
5. catalog_product_entity_int

$connection→fetchAll($unionSelect) returns array - attribute_ids and corresponding values

$entityData[$attributesMap[]] - holds all valid attributes ids

Check all 5 tables, the attribute must be there

It can be helpful to var_dump($connection→fetchAll($unionSelect)) or debug it using debugger, just see what is the value of attribute_id 63 so you can find it easier 

If you still can’t find it, just ignore it in the code ;)

something like if(isset($entityData[$attributesMap[$attributeValue['attribute_id']]]
)) should do the trick :)

I don't have more ideas...

**Comment by developer-lindner** [comment]
@Protazy21 Thank you!

There seem to be a lot more problematic attributes, but in the end it was just the 63 one... this is the var_dump:

```
array (size=19)
  0 => 
    array (size=2)
      'value' => string 'Default Category' (length=16)
      'attribute_id' => string '42' (length=2)
  1 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '46' (length=2)
  2 => 
    array (size=2)
      'value' => string 'PRODUCTS' (length=8)
      'attribute_id' => string '49' (length=2)
  3 => 
    array (size=2)
      'value' => string '' (length=0)
      'attribute_id' => string '57' (length=2)
  4 => 
    array (size=2)
      'value' => string '' (length=0)
      'attribute_id' => string '60' (length=2)
  5 => 
    array (size=2)
      'value' => string '1' (length=1)
      'attribute_id' => string '43' (length=2)
  6 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '50' (length=2)
  7 => 
    array (size=2)
      'value' => string '0' (length=1)
      'attribute_id' => string '51' (length=2)
  8 => 
    array (size=2)
      'value' => string '1' (length=1)
      'attribute_id' => string '66' (length=2)
  9 => 
    array (size=2)
      'value' => string '1' (length=1)
      'attribute_id' => string '68' (length=2)
  10 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '44' (length=2)
  11 => 
    array (size=2)
      'value' => string 'Schuhe,  Arbeitsschuhe,  Sicherheitsschuhe,  Küchenschuhe,  Entenschuhe,  Jacoform,  Birkenstock, Berkemann,  Schuhe online, Duckfeet, Puma' (length=155)
      'attribute_id' => string '47' (length=2)
  12 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '48' (length=2)
  13 => 
    array (size=2)
      'value' => string '' (length=0)
      'attribute_id' => string '61' (length=2)
  14 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '63' (length=2)
  15 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '64' (length=2)
  16 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '57' (length=2)
  17 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '58' (length=2)
  18 => 
    array (size=2)
      'value' => null
      'attribute_id' => string '59' (length=2)
```

**Comment by developer-lindner** [comment]
@Protazy21 well, obviously it's in the catalog_category_entity_\* tables... makes sense if the error occurs when entering the category management in the backend.

I can access the category management now, but don't see any products in frontend anymore -.-
Last time i've managed to fix by updating every product (update attribute), but mass action seems to have an issue too (Allowed memory size.... although it's set to 4G).

Any idea how to fix the association ?

**Comment by Protazy21** [comment]
@developer-lindner 
Have you made the changes described above?

> Fix for showing products in category
> Magento\CatalogInventory\Model\Configuration
> function getDefaultScopeId() always returns 0 (admin id)
> converting to this helps:
> public function getDefaultScopeId()
> {
> // TODO: should be fixed in MAGETWO-46043
> // "0" is id of admin website, which is used in backend during save entity
> $scopeId = $this->storeManager->getWebsite()->getId();
> return $scopeId;
> }
> In this case if you do any actions in admin 0 will be returned, if on frontend current website id.

If you did, then have no clue. Your case is a bit different than I had.

**Comment by lucscu** [comment]
which EAV is attribute_id = 63? 
post your entire record from eav_attribute table.

**Comment by developer-lindner** [comment]
@Protazy21 unfortunately this doesn't helps me. Frontend still shows "We can't find products matching the selection."

In 2.0.7 they were shown... wtf changed in 2.1.0? :/

@LucScu 
The table -> https://www.dropbox.com/s/6jqs81hfqcm6cwk/eav_attribute.sql?dl=0

@andimov Any idea what i can do?

**Comment by developer-lindner** [comment]
Okay guys @Protazy21 @LucScu my issue was that the Catalog Search index didn't went through probably. I've tweaked my mysql settings (my.cnf) to have it pass through.

Now i see products again. Didn't thought that this Index would be necessary to show products,
but it is...

Does anyone of you have an idea for this issue #5414 maybe?
Or an idea how to do it better?

mysql settings:

```
[mysqld]
max_connections       = 10

key_buffer_size       = 16K
max_allowed_packet    = 200M
table_open_cache      = 250
sort_buffer_size      = 64K
read_buffer_size      = 256K
read_rnd_buffer_size  = 256K
net_buffer_length     = 2K
thread_stack          = 128K
wait_timeout          = 10
```

And how comes that the layered navigation is sometimes set with a few filters, but in sub-category it's not ?

**Comment by avra911** [comment]
Thanks to: https://github.com/magento/magento2/issues/5645 I had to change the attribute group name to `Advanced Pricing` from ~~Migration_Pricing~~. I also had to change the `attribute_group_code` and `tab_group_code` in `eav_attribute_group` table to make the edit product work again (see: https://nimbus.everhelper.me/client/notes/share/523802/gflibimm42igvlrh49yd).
R

**Comment by malaiselvan** [comment]
@Protazy21 After changing the code, I am getting a weird problem when I try to edit the product from backend `Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist`.  Any idea what went wrong??

**Comment by andimov** [comment]
@richardreen 
According to contributor guide, tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
@anyone 
Please create a separate ticket for other issues and provide detailed steps according to the template. This will help us to process issues. I'm closing this one.

**Comment by sehajmathur** [comment]
@Protazy21 Any idea how you fixed 404 issue and missing product information (for example products have no name, title etc) in the admin product edit form?

**Comment by flexxus** [comment]
@sehajmathur  i am having the same issues.

**Comment by josh--** [comment]
@sehajmathur @flexxus I had the same issue you are referring to specifically it was happening with group products. It ended up being an undefined index error as described in previous posts. 

The error just doesn't propagate to the frontend. You should be able to see the exceptions thrown in the exception log. I simply deleted references to the attribute in the DB and the products re-appeared and are again editable.

**Comment by lalitmalav** [comment]
Please let me know  has resolved this issue ????

a:4:{i:0;s:164:"Notice: Undefined offset: 63 in /home/69807-54179.cloudwaysapps.com/ssasmthybt/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:7654:"#0 /home/69807-54179.cloudwaysapps.com/ssasmthybt/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/home/69807-541...', 166, Array)
#1 /home/69807-54179.cloudwaysapps.com/ssasmthybt/public_html/vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\Catalog...', Array, Array)
#2 /home/69807-54179.cloudwaysapps.com/ssasmthybt/public_html/vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /home/69807-54179.cloudwaysapps.com/ssasmthybt/public_html/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Category\Interceptor), 2, Array)
#4

**Comment by andimov** [comment]
@lalitmalav
Please create a new ticket for this issue and provide detailed description according to the template.

**Comment by rip057** [comment]
the attribute_id 63, from what i can tell, and this is only due to my self made api that only interfaces with the mysql db to create categories, products, pictures, etc.  i digress, while i dont know specifically what table attribute_id 63 is in, 61 is in catalog_category_entity_varchar , 62 & 65 are in catalog_category_entity_text , 60 is in catalog_category_entity_text , so instead of the catalog_product_entity_\* tables i would search the catalog category entity tables.  but just like i saw that the attribute_id 118 was some benign notation of what level of stores the product was in, try to figure out what the attribute_id 63 is for you, idk. 

i realize this is closed, but i thought i would at least make the contribution for anyone that gets sent here by google, or anywhere else

**Comment by qrider** [comment]
for me it was a migrated default category. Lucky for me I planned to rebuild the categories anyway. 

To fix it I added error handling to the core file temporarily around line 166 in module-eav/Model/ResourceModel/ReadHandler.php. I was then able to load the page and delete the category through the admin interface. You have to create and set a new default in your store else Magento will not let you delete the category.  

Below is the temp patch to get the page to load. For what ever reason the formatting did not like my copy & paste.

`
                    $attr_id = $attributeValue['attribute_id'];
                    $attr_val = $attributeValue['value'];

```
                if (!array_key_exists($attr_id, $attributesMap)) {
                    continue;
                }

                $attr_map = $attributesMap[$attr_id];
                $entityData[$attr_map] = $attr_val;
```

`

**Comment by ubedarab** [comment]
I got same error after upgrade to 2.1.1 to 2.1.5 and I apply solution mention by @Protazy21

Class vendor/magento/module-configurable-product/Ui/DataProvider/Product/Form/Modifier/ConfigurablePrice.php

replace argument value on line 92 
-  'config' => $visibilityConfig
with ,
+ 'config' => ['componentType'=>'container',$visibilityConfig],

its work for me, :)

**Comment by mgeoffray** [comment]
I had the same error but the reason was that I create a new product attribute with the type `Price`   
I place it under a new tab `Price` in my attribute set then I had the error with `advanced_pricing_button`.  I had to move my new attribute under `Advanced Pricing` tab and then the error was gone.    
I did not test yet if that is a native bug or not, but if that can help someone!

**Comment by JosephMaxwell** [comment]
I put your solutions for the `advanced_pricing_button` issue into a small composer package: https://github.com/SwiftOtter/AdvancedPricingBug

This solves the problem for me. This is not a permanent fix, but until a official fix for this is released.

**Comment by yogendrabmishra** [comment]
Can someone help me with this issue? 

https://github.com/magento/magento2/issues/9734

--Yogi--
