### ISSUE TITLE
Exception thrown when user clicks Back to Shopping Cart from Multicheckout Shipping page

### ISSUE THREAD

**Issue by mcspronko** [magento/magento2#5237]
## Steps to reproduce
1. Configure Gift Options on Order level
2. Create a customer account with 2 shipping addresses
3. Add 2 products to cart as a logged in user
4. Click "Proceed with Multi Checkout" button on Checkout Cart page
5. Select different shipping address for second product.
6. Click "Update QTY and Addresses" button
7. Click Back to shopping cart link
8. Observe results.

## Expected result
1. Add a Gift Options link opens form to add From,To,Message values.

## Actual result
1. Exception is thrown and logged in var/log/exception.log / Exception is shown on the page.

> Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`theirishstore`.`quote_shipping_rate`, CONSTRAINT `QUOTE_SHIPPING_RATE_ADDRESS_ID_QUOTE_ADDRESS_ADDRESS_ID` FOREIGN KEY (`address_id`) REFERENCES `quote_address` (`address_id`) ON DELETE CASCA), query was: INSERT INTO `quote_shipping_rate` (`address_id`, `carrier`, `carrier_title`, `code`, `method`, `method_description`, `price`, `method_title`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
1. No gift options form is shown at Checkout Cart page. User is unable to select.

## Preconditions
Magento 2.0.x, Magento 2.1

## Observations

The problem exists due to a fact that after user is redirected from multicheckout page all shipping addresses are removed from quote. In order to fix the problem, quote should be reloaded before it's actual usage on checkout/cart page.

Hope it helps.

**Comment by thiagolima-bm** [comment]
I wasn't able to reproduce this bug.
branch 2.1 develop

**Comment by magento-engcom-team** [comment]
Hi @mcspronko 
We are closing this now due to inactivity and "cannot reproduce" report in the comment above.
Please feel free to reopen and provide more information if you think that issue still exists.

Thank you
