### ISSUE TITLE
Adding another language pack

### ISSUE THREAD

**Issue by nevvermind** [magento/magento2#524]
I guess this could be labeled "minor-ask".
If someone were to add another translation for every module (the "i18n" folder), would it be added in the default Magento2 package? Or it's settled that it would come out with just those 7 language packs?

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23158

**Comment by ctubio** [comment]
just saying, I would love to push my language (Catalan) to the original repo too.

**Comment by piotrekkaminski** [comment]
Translations will be available separately. If you want to contribute, please go to https://crowdin.com/project/magento-2

**Comment by ctubio** [comment]
so sad.. https://crowdin.com/project/magento-2 says that you only need translations for a few languages.. ca_ES not included.

anyway, thanks for give us an answer.
