### ISSUE TITLE
Configurable Product - Cannot use "Create Configurations" feature -  "Invalid Form Key"

### ISSUE THREAD

**Issue by duffner** [magento/magento2#5242]
Steps to reproduce

Magento 2.1.0 CE installed with Sample data

Issues occurs in Chrome / Firefox. I have not tested in other browsers
## 
1. Begin Creating new Configurable product from Admin Catalog Grid 
2. Set SKU, Weight, Price.. etc 
3. Click "Create Configurations" button 
4. Select Desired Attributes for configuration - Click Next (Note Selected 3 From Sample Data)
5. Select Desired Attribute values for configuration - Click Next (Note Selected all options From Sample Data) 480 Total Products
6. Set Bulk Images, Price and Quantity to "Skip" - Click Next
7. View Summary - Click Next 

_Note - At this step in 2.0.7 it used to have a button instead of next called "Generate Products"_ 
1. Then Click Save product 
2. Magento asks "Choose Affected Attribute Set"  select Add configurable attributes to the current Attribute Set
3. Press Confirm 
## Expected result
1. The product will save and create all child configurations
## Actual result
1. Invalid Form Key. Please refresh the page.

During this process, I also tried created a configurable product first and clicking save, which worked..  I then went back into the product and went to Create Configurations when through the above process and once again received the same error.   

Recent Note:  It appears the issue with the "form key" relates to the quantity of children products created during the process at one time.  Tried 480, 360, 120, 80, 60 all didn't work..  But when we tried a combination that had 40 possible combinations it worked!!!!     Tried 20, it worked!! ...   So we have a client that has a 4 dimensional matrix that will need to create approx 960 products.  Hopefully, we can get this resolved as quickly as possible. 

Thank you 

Robert 

<img width="875" alt="screen shot 2016-06-24 at 3 24 20 pm" src="https://cloud.githubusercontent.com/assets/7387019/16349682/c3f7a03a-3a1f-11e6-81cc-314f4c0eea07.png">

**Comment by veloraven** [comment]
@duffner thank you for reporting the issue. 
We already have internal ticket MAGETWO-51772 with the same problem, so I mentioned your report in that ticket.

**Comment by PieterCappelle** [comment]
Same problem still exists in 2.1. In my case problem was fixed updating max_input_vars to 5000 in PHP7.

**Comment by duffner** [comment]
@veloraven  Has this issue been resolved?

**Comment by duffner** [comment]
Updating max_input_vars, while this does fix the problem.  This is an improper solution and is purely a bandaid fix.

**Comment by okorshenko** [comment]
Backport ticket for 2.1-develop: MAGETWO-57410

**Comment by orlangur** [comment]
Closing as the fix for this issue is already available on Magento 2.2.0 branch (https://github.com/magento/magento2/commit/b75fc4f83aa2fdf093ceae25449fa0b95bbc4020).

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.
