### ISSUE TITLE
Useless method addChild in Configurable WebAPI?

### ISSUE THREAD

**Issue by piatrouski** [magento/magento2#5243]
## Steps to reproduce
1. Install Magento 2.1.0
2. Add Simple product
3. Add Configurable product which based on Simple
4. Add another Simple to Configurable by WebAPI

or just check these code lines:

https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/etc/webapi.xml#L29
https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable.php#L636
## Expected result
1. Simple product will be associated to configurable
## Actual result
1. Nope
2. Developer silently weeps

**Comment by veloraven** [comment]
@piatrouski , thank you for your report,
We have internal ticket created for such problem: MAGETWO-55126, I have linked it to your ticket.

**Comment by svines** [comment]
Have you tried it with Virtual children instead of simple ones?  This route works for me in 2.0.7 and 2.1 using Virtual children.

**Comment by svines** [comment]
No dice.  This time I associated the children first and ran the steps above, but I still get the same error when adding the second option to the parent.  Also, if I had been adding a duplicate option it would have been a different error ("product already has this option").

**Comment by kcarm8** [comment]
Any updates on this issue?  I'm having the same problem.

**Comment by sammarcus** [comment]
@kcarm8 it looks like this was highlighted as [fixed](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.2CE.html) in 2.1.2 CE, is it still an issue for you?

**Comment by olysenko** [comment]
Hi all,  this issue was  fixed in 2.1.2. Close as fixed
