### ISSUE TITLE
Unable to upgrade from 2.0.6 to 2.1.0 GA via command line

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#5244]
## Steps to reproduce
1. Installed Magento 2.0.0 using composer create-project. Since then I've been upgrading to each new version to 2.0.6.
2. Then I tried to upgrade to 2.1.0 (MDVA-532 patch is installed) using the following commands:

```
composer require magento/product-community-edition 2.1.0 --no-update
composer update
```
## Expected result

Succesful upgrade to 2.1.0.
## Actual result

Error:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> 
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for magento/data-migration-tool ~2.0.0 -> satisfiable by magento/data-migration-tool[2.0.5, 2.0.0, 2.0.2, 2.0.7].
> - Conclusion: don't install magento/framework 100.1.0
> - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
> - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
> - Conclusion: don't install magento/framework 100.1.0
> - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].

I had already opened an issue for this problem but it was closed by mistake I believe, since no solution has been provided. [https://github.com/magento/magento2/issues/5197](https://github.com/magento/magento2/issues/5197)

**Comment by robfico** [comment]
Did you apply the MDVA-532 patch first?

MDVA-532  Patch MDVA-532 fixes an issue with the Magento composer-installer component that causes upgrades to fail. For details, see Upgrade to Magento version 2.1 (June 22, 2016)

http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_21-upgrade.html

I believe it's required for a composer update.

**Comment by jibrandlr** [comment]
@robfico Yes I installed the patch MDVA-532 before trying to upgrade

**Comment by paales** [comment]
It seems the Data Migration tool isn't available for 2.1.0 yet.
https://github.com/magento/data-migration-tool/tags

Maybe uninstall the data migration tool first and then reinstall the data migration tool with dev-master after you've upgraded.

```
composer require magento/data-migration-tool:dev-master
```

**Comment by maksek** [comment]
@lgarridoj Data migration tool will be updated in next two weeks. So, you may want to uninstall it for upgrade.

**Comment by SolPin** [comment]
Does somebody know the command how to uninstall the Data Migration Tool in 2.0.7?

**Comment by SolPin** [comment]
Try and error found it: 
composer remove magento/data-migration-tool

**Comment by jibrandlr** [comment]
Tried to uninstall data-migration-tool but got this error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package magento/product-community-edition == 2.0.6.0 could not be found.
>   Problem 2
>     - Installation request for braintree/braintree_php == 2.39.0.0 -> satisfiable by braintree/braintree_php[2.39.0].
>     - magento/product-community-edition 2.1.0 requires braintree/braintree_php 3.7.0 -> satisfiable by braintree/braintree_php[3.7.0].
>     - magento/product-community-edition 2.1.0 requires braintree/braintree_php 3.7.0 -> satisfiable by braintree/braintree_php[3.7.0].
>     - Conclusion: don't install braintree/braintree_php 3.7.0
>     - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.
> 
> Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
> 
> Removal failed, reverting ./composer.json to its original content.

**Comment by oshmyheliuk** [comment]
Please, try return to magento version 2.0.6 (or 2.0.7 - last installed version)

`composer require magento/product-community-edition 2.0.6 --no-update`

And then remove data migration tool

`composer remove magento/data-migration-tool`

After that you can upgrade to 2.1.0

```
composer require magento/product-community-edition 2.1.0 --no-update
composer update
```

**Comment by jibrandlr** [comment]
@oshmyheliuk That solved the issue for me. I also had to run `php bin/magento setup:upgrade`
