### ISSUE TITLE
Magento 2.1 PHP 5.5

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#5248]
I am getting an error message that I require PHP 5.6 or higher to run Magento 2 now. Will PHP 5.5 be supported again?

**Comment by paales** [comment]
@bondimedical3 As far as I know, it wont be supported. PHP5.5 is almost End of Life, time to upgrade. 
http://php.net/supported-versions.php

**Comment by maksek** [comment]
HI @bondimedical3, @paales is right. PHP 5.5 is EOL, so no support for this version.
