### ISSUE TITLE
Create product programmatically, addImageToMediaGallery throws exception (v2.1.0)

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5249]
## Steps to reproduce
1. Install Magento with composer `create-project`
2. Create custom script for create sample product.
3. All images in pub/media/jpg folder
4. Code:
```php
$product = $objectManager->create(Magento\Catalog\Model\Product::class);
   $product->setTypeId(Type::TYPE_SIMPLE)
   ->setAttributeSetId($attributeSetId)
   ->setWebsiteIds([1])
   ->setName($name)
   ->setSku($sku)
   ->setPrice(100)
   ->setStatus(Status::STATUS_ENABLED)
   ->setStockData(['use_config_manage_stock' => 1, 'qty' => 100, 'is_qty_decimal' => 0, 'is_in_stock' => 1]);
   $imagePath = "jpg/SKU.jpg";
   $product->addImageToMediaGallery($imagePath, array('image', 'small_image', 'thumbnail'), false, false);
   $productRepository->save($product);
```
## Expected result
1. Product with image and a cup of coffee 😒 
## Actual result

Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'There is no MediaGalleryEntryConverter for given type' in vendor/magento/module-catalog/Model/Product/Attribute/Backend/Media/EntryConverterPool.php:48

**Comment by cizgidekiadam** [comment]
It seems exception throws when a saved product object not exists. Save product once before add images, then add images and re-save same object fixed that issue.

```php
$product->setTypeId(Configurable::TYPE_CODE)
    ->setAttributeSetId($attributeSetId)
    ->setWebsiteIds([1])
    ->setName($p["name"])
    ->setSku($p["sku"])
    ->setVisibility(Visibility::VISIBILITY_BOTH)
    ->setStatus(($p["status"]==1?Status::STATUS_ENABLED:Status::STATUS_DISABLED))
    ->setStockData(['use_config_manage_stock' => 1, 'is_in_stock' => 1]);
$product=$productRepository->save($product);
$imagePath = "jpgs/".$p["sku"].".jpg"; // path of the image
$product->addImageToMediaGallery($imagePath, array('image', 'small_image', 'thumbnail'), false, false);
$product->save();
```

**Comment by YasinUzn** [comment]
I have same issue without image its working but when I try to this solution $product->save();

Throws an error:
Fatal error: Uncaught InvalidArgumentException: Required parameter 'theme_dir' was not passed in .../vendor/magento/framework/View/Design/Fallback/Rule/Simple.php:61

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-84698 to track progress on the issue.

**Comment by dmanners** [comment]
Hey @rbostan I am going to close this as I beleave this to be a duplicate of https://github.com/magento/magento2/issues/6803. If you feel this is not a duplicate of your issue please let me know and reopen this issue.

Thank you.
