### ISSUE TITLE
Missing webapi-security translate file

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5250]
I don't find the admin section's (Magento Web API) translate file
This is what I think:

"Web API Security","Web API Security"
"Allow Anonymous Guest Access","Allow Anonymous Guest Access"
"This feature applies only to CMS, Catalog and Store APIs. Please consult your developers for details on potential security risks.","This feature applies only to CMS, Catalog and Store APIs. Please consult your developers for details on potential security risks."

**Comment by veloraven** [comment]
@ideirj  please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
