### ISSUE TITLE
Unintelligible characters Varnish cache admin's note text

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5251]
![magento210-git01](https://cloud.githubusercontent.com/assets/2940012/16356076/4641a2f0-3acc-11e6-8c1d-b6d273dcdecb.jpg)

So, the translate can't work:
"IPs access list separated with \',\' that can purge Varnish configuration for config file generation.
                            If field is empty default value localhost will be saved."

**Comment by veloraven** [comment]
@ideirj thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
