### ISSUE TITLE
Magento 2.1 Configuration" --> "Design" --> No theme dropdown

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5256]
## Steps to reproduce
1. Install Magento 2.1 via download /FTP
2. PHP7 / Nginx / MariaDB
   Go to "Configuration" --> "Design" tab
## Expected result
1. To see the option to switch a theme (magento luma or custom theme uploaded)
## Actual result

There is just one tab here: "Search engine robots".

Did you guys move the theme dropdown?
![screen](https://cloud.githubusercontent.com/assets/16196483/16357934/f61a27fa-3b04-11e6-9c84-370e319d793f.png)

**Comment by maksek** [comment]
Thanks for reporting @andidhouse, we are going to investigate this ASAP.

**Comment by hostep** [comment]
It has been moved in M2.1, see this duplicate ticket:
https://github.com/magento/magento2/issues/5240

**Comment by maksek** [comment]
Thanks @hostep, @andidhouse we are going to rename the section to avoid confusion in future.

**Comment by andidhouse** [comment]
Thanks! Found it there. 
Renaming the section makes sense i think.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. Please see 55f4138, 5a28491, dcc73dd, 43676a5 and bdf2d49.
