### ISSUE TITLE
2.1 on editing customer screen, gray out the entire screen with a spinning icon

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#5257]
## Steps to reproduce
1. Install M2.1
2. Choose a customer
3. Click edit the customer
## Expected result
1. be able to edit the customer fields
2. ...
## Actual result
1. the entire screen is grayed out with a spinning icon
2. 
3. ...

**Comment by maksek** [comment]
@sheldonli999, which mode are you using? 
Can you recheck permissions on pub/static, pub/media folders?

**Comment by sheldonli999** [comment]
dev mode, i set all to 777 under pub.  i see many js errors

**Comment by sheldonli999** [comment]
![screen shot 2016-06-25 at 11 18 33 am](https://cloud.githubusercontent.com/assets/18491705/16358387/8cca1c9e-3ac6-11e6-8dc2-2e0d8c361bf1.png)

**Comment by sheldonli999** [comment]
also as you see, the address fields are not right

**Comment by sheldonli999** [comment]
![screen shot 2016-06-25 at 11 21 32 am](https://cloud.githubusercontent.com/assets/18491705/16358394/b9cb84c6-3ac6-11e6-8fbb-e59788e6a714.png)

please see js errors

**Comment by maksek** [comment]
More details needed - how did you install 2.1 (websetup, CLI, download)? 
If you are on developer mode, try to do next steps in console:
- remove everything from pub/static
- remove var/cache
- chmod 777 var and pub/static
- clean browser cache and open admin again

**Comment by sheldonli999** [comment]
After clearing the browser cache, i am able to edit.  Thanks

But the address fields still show address template.  please the screen shot.
![screen shot 2016-06-25 at 11 31 19 am](https://cloud.githubusercontent.com/assets/18491705/16358468/211db8a0-3ac8-11e6-9b7d-4b72d9dc89ad.png)

**Comment by veloraven** [comment]
@sheldonli999 I'm going to close this issue as original problem was solved.
Please create separate issue for the second problem if it is still actual so that other users can easily find it.
Please format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
