### ISSUE TITLE
2.1 Can't select theme

### ISSUE THREAD

**Issue by JDavidVR** [magento/magento2#5259]
## Steps to reproduce
1. Install Magento 2.0.1.
2. Open backend, go to: STORES > Configuration > GENERAL > Design
## Expected result
1. Should display list of themes available 
## Actual result
1. Is not displaying the option

![configuration settings stores magento admin](https://cloud.githubusercontent.com/assets/4760084/16358711/9e922070-3ae9-11e6-8e2f-5d3b5697cd42.png)
![screen shot 2016-06-25 at 3 30 52 pm](https://cloud.githubusercontent.com/assets/4760084/16358718/d70dead8-3ae9-11e6-86f5-7f53ac13084d.png)

**Comment by JDavidVR** [comment]
there are another issues, that reports same problems

**Comment by hostep** [comment]
Duplicate: https://github.com/magento/magento2/issues/5240

Guys, this is the third issue in two days about this, can you please first search in the existing issues before creating a new one

Thank you :)
