### ISSUE TITLE
error create credit memo in configurable product

### ISSUE THREAD

**Issue by dunghangnuakhong** [magento/magento2#5261]
## Steps to reproduce

I am trying to create a Credit Memo in Configurable product with qty 2 or more but Return to Stock only 1 although I checked all
## Actual result

I checked Return to Stock checkbox with qty 2 or more but in stock of that product only return 1
This is error magento 2.0.4 EE right?

**Comment by filipp-kucheriavenko** [comment]
I have the same problem.

### Steps to reproduce
1. Create configurable product with 100 items in stock for each variation.
**Product state:** base product has 0 qty and each variation has 100 qty.
2. Create order with 5 items of specific variation.
**Product state:** base product has 0 qty and each variation has 100 qty except ordered which has 95 qty.
3. Create Credit Memo. There is no difference what qty administrator will refund. For example, qty would be 3.
**Product state:** base product has 3 qty (???) and each variation has 100 qty except ordered and refunded variation which has 96 qty, not 100.

### Actual result
Base product has 3 qty, all variations have 100 qty, refunded variation has qty 96.

### Expected result
Base product has 0 qty, all variations have 100 qty.

### Environment
Magneto 2.0.9
nginx 1.9.15
PHP 7.0.10
MySQL 5.7.15

P.S. Bug seems to be in `createByOrder` method of `\Magento\Sales\Model\Order\CreditmemoFactory` class from `magento/module-sales` package. There are hardcoded `$qty = 1` for items that are "dummy". Calling method `isDummy()` for base product returns `false` but for variations it returns `true`.
Code of this method is same in 2.1.2.

**Comment by Biomaj** [comment]
I'm seeing exactly this same issue :

when order is placed :
configurable qty_ordered = 2, simple qty_ordered  = 2

when invoice is created :
configurable qty_invoiced = 2, simple qty_invoiced = 2

when credit memo is created :
configurable qty_refunded = 2, simple  qty_refunded = 1

Surely this is fundamental to using Magento 2 in a live environment ? What can be done to get this issue more attention ?

**Comment by smoskaluk** [comment]
@dunghangnuakhong Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by smoskaluk** [comment]
Internal ticket MAGETWO-71000 created

**Comment by magento-engcom-team** [comment]
@dunghangnuakhong, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by tuyennn** [comment]
@dunghangnuakhong  @magento-engcom-team 
"We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9"

I still could reproduce this on 2.1.9, any bug fix commit or reference link for this issue.
 1. Check QTY and stock status before check out.
![image](https://user-images.githubusercontent.com/4010395/44206140-04e98280-a183-11e8-9b95-a112eefbc527.png)
 2. Check out order and payment success.
![image](https://user-images.githubusercontent.com/4010395/44206156-129f0800-a183-11e8-9e03-000e625ccede.png)
 3. Check QTY and stock status after check out order.
![image](https://user-images.githubusercontent.com/4010395/44206171-22b6e780-a183-11e8-8752-f1e17eca7f9e.png)
 4. Credit memo this order.
![image](https://user-images.githubusercontent.com/4010395/44206175-2cd8e600-a183-11e8-9d5e-dfb8b32ce718.png)
![image](https://user-images.githubusercontent.com/4010395/44206179-31050380-a183-11e8-9e00-07cc26885093.png)
5. Check QTY and stock status after credit memo order success.
SKU : L9620800 QTY should be 47
SKU : L6597900 QTY should be 94
return wrong qty to stock.
![image](https://user-images.githubusercontent.com/4010395/44206195-3a8e6b80-a183-11e8-8086-0eca5aaa1454.png)
