### ISSUE TITLE
Performance issue in 2.1 compared to 2.0.7

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5263]
## Steps to reproduce
1. Install Magento 2.1 fresh install via download
2. MariaDB/Nginx/Debian/Varnish/Redis

Expected result
1. Same or performance on front- and backend as Version 2.0.7
## Actual result
1. Very low performance also varnish and redis is installed and running, also without varnish and redis our system is much slower then on the 2.0.7 version which was really fast.

Does anyone have the same issue?

Thanks!

**Comment by andidhouse** [comment]
Our fault due to wrong configuration!

**Comment by bery** [comment]
@andidhouse Could you please share what was wrong with your configuration with others in case someone else has similar issues? We are struggling with the server performance as well and any sort of help/inspiration is welcome!
