### ISSUE TITLE
All title and description of the cache can not be translated

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5264]
Magento 2.1 admin panel
All title and description of the cache can not be translated

![magento210-git02](https://cloud.githubusercontent.com/assets/2940012/16361401/f90b6f24-3b8f-11e6-828e-d08111bdf143.jpg)

**Comment by veloraven** [comment]
@ideirj thank you for this report.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
