### ISSUE TITLE
Fresh 2.1.0 installation issue with Design section

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#5265]
## Steps to reproduce
1. Set permissions and Install Magento 2.1.0 unzipping and run web setup wizard
2. Login to backend and navigate to Stores -> Configuration -> General -> Design
3. Cron settings available but no section for header, footer etc.
## Expected result
1. Being able to edit all settings for magento 2 design
## Actual result
1. Only Cron settings available
2. 

![2016-06-26_120426](https://cloud.githubusercontent.com/assets/17181901/16361900/d447495e-3b96-11e6-97f3-7cde79e4591d.png)

**Comment by andidhouse** [comment]
Hi @GlobalOutsourcing ,

we had the same problem.
Solution: The design tab is moved to "Content" --> "Design" --> "Configuration"

Think it can be closed

**Comment by GlobalOutsourcing** [comment]
Hi @andidhouse ,

Thanks so much for your response in such a short time.

Truly appreciate it.

Will close it now, yes.

Thanks again.

**Comment by refaelgold** [comment]
need to change it on documention http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/templates/template-email.html

**Comment by tanberry** [comment]
@refaelgold , thanks so much, we will correct this in the docs!
