### ISSUE TITLE
We cannot retrieve the payment method code (/rest/default/V1/carts/mine/shipping-information 400 Bad Request)

### ISSUE THREAD

**Issue by woei66** [magento/magento2#5267]
## Steps to reproduce
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.0.6 magento2.0.6
2. installed a customized payment module
3. add a product to the shopping cart
4. click the "go to checkout" button
5. fill my shipping address and all fields are filled and the shipping address is different to my billing address.
6. click the "Next" button to go to the next step
## Expected result
1. the next page is selecting my available payment methods
## Actual result
1. Got a error message "We cannot retrieve the payment method code."
2. Got a error message "/rest/default/V1/carts/mine/shipping-information" 400 Bad Request 
   ![2](https://cloud.githubusercontent.com/assets/5770807/16362641/f5100c48-3be6-11e6-894e-9148f65449b6.jpg)

I put my ajax content debug information in a blog post. http://david.firstbiz.cc/blog_detail.php?id=123
I am not sure whether these ajax information is useful or now.
If yes, please let me know and I can attached the log.

**Comment by woei66** [comment]
as I rewrite my source code and this bug is not there. so, I closed this ticke.t

**Comment by vishveskrish** [comment]
Hello,

We are facing same issue after upgrade from 2.0.2 to 2.1.0.

Let me know if you found any solution.

Thanks,
Vishves Shah
