### ISSUE TITLE
Assign products to category bug - Magento 2.1

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5268]
## Steps to reproduce
1. Install Magento 2.1 via download
2. Nginx/MariaDB/Varnish/Redis/PHP7
3. Install Sample data small
4. Go to category page
5. Go to products in category
6. Click reset filter
7. Click dropdown to "no"
8. Click search
9. Click qty dropdown to show "200" products
10. Assign all products by clicking the checkbox
11. Click save button
## Expected result
1. The 200 products are assigned to the categroy with a success massage
## Actual result
1. There is an javascript error
   http://www.domain.com
   ![bildschirmfoto 2016-06-26 um 16 23 07](https://cloud.githubusercontent.com/assets/16196483/16362923/48acf234-3bbb-11e6-8ac3-cf0643f3af32.png)
   /admin/catalog/category/validate/?isAjax=trueFailed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by andimov** [comment]
@andidhouse 
Thank you for reporting this issue!
Please restart varnish, then login in incognito mode or after hard reset for browser cache and try again.

**Comment by andidhouse** [comment]
Restarted Varnish, Redis and all other services of course and also deleted all browser caching and data.
Same problem remains.

**Comment by andimov** [comment]
@andidhouse 
Thank you for fast response!
Please, check your [permission sets](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)
How long the query is executed?(maybe it doesn't pass time limit)
What is written in the errors logs?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
