### ISSUE TITLE
2.1 getDefaultShippingAddress returns non-complete address fields

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#5269]
## Steps to reproduce
1. Install Magento 2.1
2. call webapi: /rest/V1/customers/me/shippingAddress
3. ...
## Expected result
1. complete address object
2. ...
## Actual result
1. only region object is returned
2. no city, street, etc are returned.
3. ...

**Comment by veloraven** [comment]
@sheldonli999 could you please provide some more information on this issue? For example, exact address which you have problem with, or some additional settings. As I was not able to reproduce it: I tried with different addresses (US and non-US), and I always get full info including street, city, telephone number.

**Comment by sheldonli999** [comment]
The address is US address.  However, I set the default country to China.  Please see the attached.
Also see the request and response:
magento url: http://121.41.108.11/index.php/rest/V1/customers/me/shippingAddress
2016-07-03 10:43:34.659 Tour[464:127348] {
    "Accept-Language" = "en_US";
    Authorization = "Bearer 09t2ge3b4k8ttexf23urj5hf57yg0d0m";
    "Content-Type" = "application/json; charset=utf-8";
}
2016-07-03 10:43:37.895 Tour[464:127348] {"id":42,"customer_id":122,"region":{"region_code":"CA","region":"California","region_id":24},"default_shipping":true,"default_billing":true}

As you see from the response, I dont see the city and street address.

![screen shot 2016-07-03 at 10 46 51 am](https://cloud.githubusercontent.com/assets/18491705/16546807/63c52c08-410b-11e6-9698-6f82b7f0a7a3.png)

**Comment by veloraven** [comment]
@sheldonli999 
Thank you for details.
But I still can not reproduce this issue locally.
I wanted to create new customer at your site but I was not able to add address to it. So I'm afraid that this test customer's account was corrupted (email omoyseyenko@magento.com). I'm really sorry for it.
Could you please provide me with login/password of some test customer?
And did you install clear Magento 2.1 or upgraded from some previous version?

**Comment by sheldonli999** [comment]
Hi Olga:
  https://www.mtraveler.com/mtraveler
admin/april9

It is upgraded from 2.0.7.

Thanks

Sheldon

**Comment by sheldonli999** [comment]
Hi Olga:
  https://www.mtraveler.com/mtraveler
admin/april9

It is upgraded from 2.0.7

**Comment by RomanKrut** [comment]
@sheldonli999 Hi. Unfortunately, I could not reproduce the issue as you described it. I was check it on clean instance. Can you please recheck it on clean instance, too?
