### ISSUE TITLE
Hi - can we enable trigger coupon via URL in Magento 2?

### ISSUE THREAD

**Issue by seansan** [magento/magento2#527]
Hi - can we enable trigger coupon via URL in Magento 2?

http://www.drewgillson.com/blog/how-to-apply-magento-coupon-codes-automatically/

see https://github.com/magento/magento2/issues/120 which was closed too fast without reading the replies

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23160

**Comment by tkacheva** [comment]
Thanks for the example. It's a valuable point! We will consider this feature in the promotion backlog

**Comment by mbrinton01** [comment]
Change in internal ticket to MAGETWO-38709

**Comment by mbrinton01** [comment]
@seansan we have made this change. You can test it:

* Create a price rule with a specific coupon code
* Use a URL link in the format: http://example.com/index.php/checkout/cart/CouponPost/coupon_code/couponcode
* Replace example.com and couponcode in the URL with your values

If you add a product to the cart that meets the conditions of the rule after entering from the URL, the rule will be applied and the user notified.

The rule conditions must be met in a single add to cart step. For example, consider a rule that has a condition that quantity must be > 1. If you enter through the URL with code and then add 1 to cart and add 1 to cart in two steps, the coupon will not be applied.  We are looking at enhancing this feature to account for these cases.

**Comment by seansan** [comment]
I understand

So the "stored" cart coupon is not checked for indefinitely? but only the
first cart visit

BTW: great work!

**Comment by mbrinton01** [comment]
You are correct. We are considering adding a feature called "persistent" coupons that would extend the current functionality.

**Comment by seansan** [comment]
Ok!






Sent from my iPhone.

On 27 Jul 2015, at 19:28, Mark Brinton <notifications@github.com> wrote:

You are correct. We are considering adding a feature called "persistent" coupons that would extend the current functionality.

**Comment by seansan** [comment]
@verklov 

I was browsing thru M2.3.1. but cant find this functionality. 

- Is there a reference in the documentation? 
- Can we turn it on/off via settings?

Did you implement the persistent function? This is quite important! It should handle the use cases for real customers ... often via email where they click a link, start with an empty cart ...might visit the empty cart ... then add a product .. but they may also first check a product add it to cart .. then go to cart .... ot they may add a product to cart, then remove it to cart, then add another product and go to cart
In all cases : the coupon code via the link should work and be applied

**Comment by seansan** [comment]
Reference to similar functionality https://marketplace.magento.com/wsnyc-module-couponlink.html

**Comment by seansan** [comment]
@mbrinton01 

** Mark con you confirm this functionality is in 2.3.1?

** Also what is the result from below? This would be very good to have

>> You are correct. We are considering adding a feature called "persistent" coupons that would extend the current functionality.

** Another function we have seen before is to add a "redirect" variable. This way the link "http://example.com/index.php/checkout/cart/CouponPost/coupon_code/couponcode" would like "http://example.com/index.php/checkout/cart/CouponPost/coupon_code/couponcode?redirect=http://example.com" => in this case the coupn would be applied, the customer would be redirected to the page http://example.com and a message would be shown "Coupon code was activated"

**Comment by mbrinton01** [comment]
Adding @tkacheva as this relates to promotions

**Comment by crankycyclops** [comment]
I've implemented this functionality in a free and open source module. If anyone wants to use it in the meantime until this is fully implemented by the Magento team, you can find it here: https://github.com/crankycyclops/DiscountCodeUrl

Hope it's useful to someone :)

My module is still pretty new and needs more testing (if you want to help me out, I would greatly appreciate it!)
