### ISSUE TITLE
Unable to upgrade from 2.0.6 to 2.1.0 via command line

### ISSUE THREAD

**Issue by zhiyicai** [magento/magento2#5271]
## Steps to reproduce

composer require magento/product-community-edition 2.1.0 --no-update
composer update
## Actual result

<img width="1150" alt="2016-06-27 01 11 17" src="https://cloud.githubusercontent.com/assets/13891311/16365568/3a49f5b8-3c04-11e6-8d74-03b3366a9627.png">

  Problem 1
    - The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by andimov** [comment]
@zhiyicai 
Thank you for reporting this issue!
Please, check you composer.json for this section:
`"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
`

**Comment by zhiyicai** [comment]
I have checked them,existence the code,but is still not upgrade.

**Comment by zhiyicai** [comment]
#5275

**Comment by zhiyicai** [comment]
Possibly related issue #5275

**Comment by tanya-soroka** [comment]
@zhiyicai Could you please check the proposed solution under the published a Technical Bulletin to address this issue.

http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_tls-repo.html

**Comment by andimov** [comment]
@zhiyicai According to contributor guide, tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
