### ISSUE TITLE
/lib/internal/Magento/Framework/View/DesignExceptions.php - preg_match issue. 

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#5274]
## Steps to reproduce
1. Install Magento from `2.0.7` branch.
2. run migration
3. system states it from there on out. 
## Expected result
1. site should run fine.
2. ...
## Actual result

Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /lib/internal/Magento/Framework/View/DesignExceptions.php on line 70
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'preg_match(): D...', '/home/vasaripl/...', 70, Array)
#1 /lib/internal/Magento/Framework/View/DesignExceptions.php(70): preg_match('Googlebot-Mobil...', 'Mozilla/5.0 (Wi...')
#2 /app/code/Magento/PageCache/Model/App/CacheIdentifierPlugin.php(43): Magento\Framework\View\DesignExceptions->getThemeByRequest(Object(Magento\Framework\App\Request\Http))
#3 /lib/internal/Magento/Framework/Interception/Interceptor.php(150): Magento\PageCache\Model\App\CacheIdentifierPlugin->afterGetValue(Object(Magento\Framework\App\PageCache\Identifier\Interceptor), '92abe4ddb8e2b9c...')
#4 /var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(26): Magento\Framework\App\PageCache\Identifier\Interceptor->___callPlugins('getValue', Array, Array)
#5 /home/vasaripl/public_html/magento2/lib/internal/Magento/Framework/App/PageCache/Kernel.php(51): Magento\Framework\App\PageCache\Identifier\Interceptor->getValue()
#6 /app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\PageCache\Kernel->load()
#7 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#9 /lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#10 /app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#11 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /home/vasaripl/public_html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#13 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /public_html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#16 /public_html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main}

**Comment by veloraven** [comment]
@dmcmillin thank you for your report.
But if this issue is specific to migration process, please, create a ticket in corresponding repository: https://github.com/magento/data-migration-tool/issues.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
