### ISSUE TITLE
ERROR - Magento Marketplace SSL connect error

### ISSUE THREAD

**Issue by zhiyicai** [magento/magento2#5275]
## Steps to reproduce

Magento Marketplace
## Actual result

Magento Marketplace SSL connect error
![error](https://cloud.githubusercontent.com/assets/13891311/16372402/9edd1814-3c4c-11e6-861d-551adc6d961f.PNG)

**Comment by ghost** [comment]
What is your environment? OS and version? Web server and version, etc? Thanks

**Comment by zhiyicai** [comment]
Linux,  Centos 6 :  Nignx + Mysql + Php7 .
Thanks

**Comment by ghost** [comment]
Try this: `curl --version`. What version do you have?

**Comment by zhiyicai** [comment]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

**Comment by ghost** [comment]
That could be the issue. I just upgraded to CentOS 6.8 and the error went away. I got the idea from this [TLS bulletin for PayPal](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements_tls1-2.html). Can you try it?

**Comment by tanya-soroka** [comment]
@zhiyicai Please see the possible solutions under the http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_tls-repo.html

**Comment by andimov** [comment]
@zhiyicai 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by ghost** [comment]
hello, im already using CentOS 6.8 with Magento 2.1....but im still getting the ssl connect error. please help
![magento2](https://cloud.githubusercontent.com/assets/12715229/20384732/746f974e-ace7-11e6-8c8b-0387e2f5cd9d.PNG)
