### ISSUE TITLE
Grouped product media gallery in collection

### ISSUE THREAD

**Issue by wkaminsk** [magento/magento2#5276]
### Preconditions
Magento 2.0.7 via composer

## Steps to reproduce
1. Install Magento 2.0.7 via composer
2. Have two products in catalog - one simple and one grouped product
3. Add more than two images for each product
4. Prepare product collection (PC1) where only grouped product is fetched from catalog
5. Prepare second product collection (PC2) where all products are fetched from catalog
## Expected result
1. During collection item loop, get media gallery list (\Magento\Catalog\Model\Product\Gallery\GalleryManagement:: getList) should return all gallery images for specified product
## Actual result
1. During looping second collection (PC2) for grouped product media gallery is empty.

**Comment by magento-engcom-team** [comment]
@wkaminsk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
