### ISSUE TITLE
Translation does not work from js ($.mage.__())

### ISSUE THREAD

**Issue by Aquarvin** [magento/magento2#5278]
I have Magento 2.1.0
It has custom theme app/design/frontend/SR/lumartl
it has own translation file app/design/frontend/SR/lumartl/i18n/he_IL.csv
`"Submit", "שלח"`
`"Shop All", "לכל המוצרים בקטגוריה"`
Translation works good on template files (phtml), forexample in 
app/design/frontend/SR/lumartl/Magento_Customer/templates/form/forgotpassword.phtml
`<?php /* @escapeNotVerified */ echo __('Submit') ?>`
correctly translated 'Submit' into 'שלח'

It works fine. But:
Theme has one more js-file app/design/frontend/SR/lumartl/web/mage/menu.js
It is lib [menu.js](https://github.com/magento/magento2/blob/develop/lib/web/mage/menu.js#L286)
where 286  line `.text($.mage.__('All ') + category);` was changed to `.text($.mage.__('Shop All'));`
On frontend 'All ' is changed to 'Shop All', but it's giving no translation at all.

**Comment by MindConflicts** [comment]
Same for me on develop branch (pl_PL)
Magento CLI version 2.2.0-dev

https://s32.postimg.org/pz2pplgg5/translations_bug.gif

**Comment by cuiyang000** [comment]
Having the same issue here.

A dirty&temporary way to solve this is to copy the menu.js file to your theme's folder, under web/js folder, and hardcode the text there. And you have to add line:
`'menu':'js/menu'`
to requirejs-config.js 

See here: https://github.com/magento/magento2/issues/5509#issuecomment-244964654

**Comment by veloraven** [comment]
I'm closing this issue as it was already fixed in develop branch.
For more information please see #7593.

**Comment by korostii** [comment]
Hi @veloraven, are there any plans to backport the fix (see #5725) to 2.1.x?
There seem to be multiple issues depending from it.
