### ISSUE TITLE
Unable to add more than 1 product to a cart from Wishlist

### ISSUE THREAD

**Issue by mcspronko** [magento/magento2#5282]
## Steps to reproduce
1. Create an account on frontend
2. Navigate to any product
3. Click "Add to Wishlist" button
4. Go to "My wishlist" page from customer account.
5. Update QTY of a product to 5
6. Click add to cart / Try same with "Add all items to cart" button.
7. Observer the result.
## Expected result
1. 5 Products are added to a shopping cart
## Actual result
1. 1 Product is added.
## Magento Versions

Magento 2.1 and develop branch.

**Comment by mhabou** [comment]
No problem in Magento ver. 2.1.0-rc3

Did you click on "update wish list" button ?

![wish](https://cloud.githubusercontent.com/assets/13301885/16379218/c42c6ac6-3c5f-11e6-9e58-22d83fed4d91.png)

**Comment by mcspronko** [comment]
Hi @Dayssam 

When you hover over the product, popup will appear with QTY, Add To Cart button.
From this pop up user is able to change QTY and immediately click "Add To Cart" button.

Hope it helps.

**Comment by mhabou** [comment]
@mcspronko 

I tested it also , & it works for me  in Magento ver. 2.1.0-rc3

**Comment by mcspronko** [comment]
Hi @Dayssam 

Does it work for you when you hit "Update wish list" button or when you hit "Add to cart" button?

**Comment by mhabou** [comment]
@mcspronko :  Both

**Comment by veloraven** [comment]
Hi @mcspronko !
I was able to reproduce your issue. I have created an internal ticket MAGETWO-56077.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 as of today.
