### ISSUE TITLE
UK Catalog, Goods excluding VAT - rounding issues on front end display

### ISSUE THREAD

**Issue by PushEngineering** [magento/magento2#5283]
On M2 7.0.7

We are storing catalog values without tax. We want the front end display to show £9.99 inc tax - as the product price.

I enter the prices ex-VAT in the backend, and have front-end display price+tax.

What value do i have to enter to get a price of £9.99 (front end)?
Answer: £9.99/1.2 (VAT @ 20%) = £8.325

So i have to put £8.325 into the back end so that:

£8.325*1.2 = £9.99.

OK - so i do that......

But Magento only seems to store the price to 2DP. - so it stores

£8.33 (rounded up without me wanting it to)

so taking Magento's £8.33

£8.33*1.2 = £10.00 (displayed on front-end) <--- WRONG!!

because to achieve a £9.99 inc VAT price you need to store £8.325 - 3DP, but Magento 2 doesn't.

**Comment by stevewinni** [comment]
We are also facing this issue, M2 v2.1.2

Value in backend for product 24.16 desired front end price 29.00, First Item in cart = 29.00 second item in card 29.01 thus totalling,  58.01.

We cannot launch without this fix as a lot of product with error in this way.

Thanks

**Comment by punkstar** [comment]
We investigated this on behalf of @PushEngineering and came up with this solution - https://github.com/meanbee/magento2-tax-rounding, rounding to three decimal places.  Thanks to @PushEngineering for recommending we release our solution.

**Comment by orlangur** [comment]
@PushEngineering thanks for bug report! Closing as duplicate in favor of another ticket with `G2 Passed`.
