### ISSUE TITLE
Installing magento 2 with composer --dev gives error about Stopwatch

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#5284]
## Steps to reproduce
1. Install Magento using composer install --dev.
2. run bin/magento (with executable permission)
## Expected result
1. List of commands from bin/magento with no error.
## Actual result
1. Error message appears: 
   We're sorry, an error occurred. Try clearing the cache and code generation directories. By default, they are: var/cache, var/di, var/generation, and var/page_cache.
   
   [ReflectionException]
   Class Symfony\Component\Stopwatch\Stopwatch does not exist
   ![screen shot 2016-06-27 at 14 42 52](https://cloud.githubusercontent.com/assets/17834386/16380125/7b829820-3c75-11e6-89fe-f9d8fe778bfa.png)

**Comment by mhabou** [comment]
Did you clear the cache and generation directories ???

`rm -rf var/cache/* var/di/* var/generation/* var/page_cache/*`

**Comment by PascalBrouwers** [comment]
nevermind, a 3rd party module was using Stopwatch in a Console command.
