### ISSUE TITLE
FPC issue on CMS pages

### ISSUE THREAD

**Issue by kilis** [magento/magento2#5286]
## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Add CMS block
3. Turn on FPC
4. Write observer that redirects page this one http://pastebin.com/y50r41QR
5. Clear all cache
6. Open page 2 times
## Expected result
1. Open first time page, then it redirects 
2. Open second time page, then it redirects again
## Actual result
1. Open first time page, then it redirects
2. Open second time page, it opens

Basally after cache disable it all works perfectly, but when it is enabled it first time it triggers and in second time my code is bypassed by FPC.

**Comment by veloraven** [comment]
@kilis thank you for your report.
Could you please clarify what exactly you do at Step 5?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
