### ISSUE TITLE
Shipping Country Selector Not Sending Correct Country ID on Change to Shipping Methods

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#5289]
## Steps to reproduce
1. Install Magento from latest `develop` branch
2. Enable onepage checkout
3. Change shipping country (not signed in)
## Expected result
1. country_id is set correctly and passed to shipping methods example : "CA" when selecting Canada
## Actual result
1. country_id is always sent as US regardless of selection

Request Body on estimate-shipping-methods
{"address":{"region_id":"0","country_id":"US","postcode":"A1B 2C2"}}

**Comment by mcspronko** [comment]
Hi @asemenenko and @ishakhsuvarov  

Do you have any update regarding this Critical issue?

Thanks,
Max

**Comment by mcspronko** [comment]
Some investigation:

Quote Shipping address is not updated when user changes Country/State/Postcode on Your Shopping Cart page.

estimate-service.js file, information passed to estimate totals is outdated.

```
    quote.shippingMethod.subscribe(function () {
        totalsDefaultProvider.estimateTotals(quote.shippingAddress());
    });
```

**Comment by SerhiyShkolyarenko** [comment]
Thank you for reporting! Internal issue MAGETWO-55037.

**Comment by SerhiyShkolyarenko** [comment]
@caesarcxiv @mcspronko could you please add some details? We cannot reproduce wrong country_id setting.

**Comment by magnetic5355** [comment]
@SerhiyShkolyarenko 
1. While not logged in on /checkout/ change ship to country to a different country than USA. Notice no AJAX request is made.
2. Change zip code - an ajax request is made to /rest/us/V1/guest-carts/8ec0a1dd6ec6b137b20e8f95f54e8dd5/estimate-shipping-methods with the following parameters.
   {address: {region_id: "0", country_id: "US", postcode: "444444"}}

Notice the country_id is still "US".

This impacts 2.1 and basically makes international checkout impossible depending on the shipping methods that are enabled.

**Comment by SerhiyShkolyarenko** [comment]
@caesarcxiv on the first step i do have an AJAX request.

**Comment by SerhiyShkolyarenko** [comment]
Changed country from United States to Thailand

**Comment by mcspronko** [comment]
@SerhiyShkolyarenko it won't work if you just change country and select shipping method. Old Shipping Address will be used (one which was loaded during page load). In case you refresh page, yes, you will get your new Country ID.

**Comment by SerhiyShkolyarenko** [comment]
@mcspronko could you please write detailed step-by-step instruction how to reproduce it?

**Comment by mcspronko** [comment]
@SerhiyShkolyarenko maybe i should record a video for you guys showing how it can be reproduced? My assumption is that self explanatory with the information and steps described in this ticket. Please correct me if i am wrong and it is really impossible to reproduce this simple scenario.

Thanks

**Comment by irenelagno** [comment]
This issue was fixed. You can find solution in 4dcfce26 and 6b4db36f.

**Comment by franckgarnier21** [comment]
Same problem on Magento 2.1.7

**Comment by MaxKonstructive** [comment]
Just a side note if anyone comes across this, we had this issue on our international store and the default shipping rates estimation calculations are based on the country that comes from the default tax destination, if it isn't set in store view scope the default will be used, which means it won't load correctly on initial page load.

**Comment by usman786cs** [comment]
Hi, I've a weird issue,
On checkout page I've address United Kingdom in Country input field but when I check address request to calculate shipping amount, it shows US as country id, any suggestions pls.


Thanks

**Comment by Berkelder** [comment]
Hi all, even though it's closed, I have the same issue as @usman786cs . The checkout page picks a different country id to select the shipping methods from table shipping then the country by default shown on the checkout page.

**Comment by usman786cs** [comment]
Hi @Berkelder  
if you are working on multistore website to go store>config>sales>tax>Default Tax Destination Calculation 
and set store country there.
Let me know if it works for you

**Comment by alfredogama** [comment]
> Hi @Berkelder
> if you are working on multistore website to go store>config>sales>tax>Default Tax Destination Calculation
> and set store country there.
> Let me know if it works for you

It works, many thanks
