### ISSUE TITLE
configuration for DB connection is absent

### ISSUE THREAD

**Issue by elieobeid7** [magento/magento2#5292]
Full details here

http://magento.stackexchange.com/questions/123015/configuration-for-db-connection-is-absent

Any help is appreciated

**Comment by mhabou** [comment]
My advice is to make a fresh install of Magento,

**Comment by veloraven** [comment]
@elieobeid7 could you please copy problem's description to this ticket following template (steps, expected result, actual result)? It will be much easier for other users who may have the same issue to find it.

**Comment by elieobeid7** [comment]
@veloraven  my client did not pay me and I have left the project, you can close the ticket or delete it, if he ever pays and if i work for him again I'll create a new ticket or open this one.
