### ISSUE TITLE
Module Magento_Catalog: Block in layout have not name

### ISSUE THREAD

**Issue by thangnhpk** [magento/magento2#5298]
block  <block class="Magento\Framework\View\Element\Template" template="Magento_Catalog::catalog/wysiwyg/js.phtml" /> in layout catalog_product_new.xml have not name

**Comment by veloraven** [comment]
@thangnhpk thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
