### ISSUE TITLE
Argument 1 passed to Magento\App\Response\Http::__construct()

### ISSUE THREAD

**Issue by poly-glot** [magento/magento2#530]
Catchable fatal error: Argument 1 passed to Magento\App\Response\Http::__construct() must be an instance of Magento\Stdlib\Cookie, none given, called in /Applications/MAMP/htdocs/capen/pub/errors/report.php on line 30 and defined in /Applications/MAMP/htdocs/capen/lib/Magento/App/Response/Http.php on line 49

**Comment by vishveskrish** [comment]
![m2-bug](https://cloud.githubusercontent.com/assets/6836510/10045923/9586929e-6223-11e5-9d7d-e6d2263e15ad.png)

We are still getting this error .

Kindly look in to this

**Comment by mazhalai** [comment]
@vishveskrish can you clear your var/generation folder and try again? Also can you please give us steps to reproduce?
