### ISSUE TITLE
2.1 : category_form.xml general fieldset has no sortOrder

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#5300]
`catalog/view/adminhtml/ui_component/category_form.xml`: the fieldset `general` has no sortOrder, which causes it to always render below any custom modifications to the layout done by other modules. The following example has a `sortOrder` of 50:

![screen shot 2016-06-28 at 08 47 52](https://cloud.githubusercontent.com/assets/346681/16406239/532cb2b4-3d0d-11e6-9fd2-9e3dae256776.png)

To fix this, simply add a `sortOrder` of 0 to the general fieldset.

**Comment by bartek9007** [comment]
Is it really necessary to disable possiblity to create and fill custom attributes' groups for categories? It was really working well.

**Comment by slopukhov** [comment]
@kanduvisla thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by ghost** [comment]
Hi,

When I creat new module, I'll create Block From and I can define fieldset->setType() but on category, I can't define it. You can ask for me on category_form.xml I can define it?

Thanks

**Comment by andimov** [comment]
@kanduvisla 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
@dungntifi 
In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.

**Comment by versdivers** [comment]
This is exactly what is happening to me also and i have no idea why. This is my category_form.xml 

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="designit_megamenu">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">Mega Menu</item>
                <item name="collapsible" xsi:type="boolean">true</item>
                <item name="sortOrder" xsi:type="number">1000</item>
            </item>
        </argument>
        <field name="enable_megamenu">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="sortOrder" xsi:type="number">10</item>
                    <item name="dataType" xsi:type="string">boolean</item>
                    <item name="formElement" xsi:type="string">checkbox</item>
                    <item name="label" xsi:type="string" translate="true">Enable MegaMenu</item>
                    <item name="prefer" xsi:type="string">toggle</item>
                    <item name="valueMap" xsi:type="array">
                        <item name="true" xsi:type="string">1</item>
                        <item name="false" xsi:type="string">0</item>
                    </item>
                    <item name="default" xsi:type="number">0</item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>
```
