### ISSUE TITLE
Custom Payment gateway not working in the Magento2 front end.

### ISSUE THREAD

**Issue by nmohanan** [magento/magento2#5303]
Hi,

I have tried to create new custom offline payment gateway like cash on delivery. it is coming in Magento2 admin backend, but in front-end it is not coming, any one knows any fixes please let me know, 

Thanks

**Comment by orlangur** [comment]
Hi @nmohanan, this GitHub is intended for bug reports, to find a solution for your issue it's better to fill a question at http://magento.stackexchange.com/

Also, it's hard to guess what went wrong with your code without the code itself. Try to spot the difference between your own method and another (working) one or provide a reproducible sample.

**Comment by nmohanan** [comment]
I have raised a question with code in magento.stackexchange.com

**Comment by orlangur** [comment]
Thanks, I see http://magento.stackexchange.com/questions/123102/magento-2-custom-payment-method-not-showing-in-front-end now, so, let's continue discussion there.

**Comment by nmohanan** [comment]
Yes Sure

**Comment by YevSent** [comment]
Closed, because discussion moved to stackexchange.
