### ISSUE TITLE
Magento 2.1.0 some configuration information disappeared

### ISSUE THREAD

**Issue by Krapulat** [magento/magento2#5307]
After upgrading to Magento 2.1.0, when I enter to Stores > Configuration > General > Design I only see this:

![screen shot 2016-06-28 at 13 37 52](https://cloud.githubusercontent.com/assets/4441564/16414236/d00dcfe2-3d36-11e6-947c-d39855686358.png)

All the other information has disappeared.

**Comment by hostep** [comment]
Duplicate of https://github.com/magento/magento2/issues/5240

@Krapulat: it has been moved to Content => Configuration

Please try to search for an issue first before creating a new one, this has been reported like 5 times already.

**Comment by Krapulat** [comment]
Ok, thanks. I close it.
