### ISSUE TITLE
Insert widget in block/page content - conditions missing

### ISSUE THREAD

**Issue by fchalet69** [magento/magento2#5308]
## Steps to reproduce
1. Install Magento 2.0.7
2. Go to Content -> Pages or Blocks.
3. Edit a page or a block.
4. In the content (wysiwyg), insert widget with conditions (e.g Catalog Products List)
5. Add condition(s) in "Conditions" section
6. Insert the widget
## Expected result
1. Conditions are saved in the widget.
## Actual result
1. Conditions are not saved

**Comment by PieterCappelle** [comment]
Having the same problem in version v2.1.0.

**Comment by tkacheva** [comment]
@PieterCappelle, @fchalet69  Thanks for reporting. Managed to reproduce MAGETWO-54913

**Comment by PieterCappelle** [comment]
@tkacheva: any ideas when this will be fixed?

**Comment by tkacheva** [comment]
PR has been already merged https://github.com/magento/magento2ce/pull/145
Please update.

**Comment by allanpaiste** [comment]
Conditions are actually saved, but not restored correctly when you re-edit the widget

Related issue: https://github.com/magento/magento2/issues/5398

**Comment by PieterCappelle** [comment]
Hallo,

Ik ben vader geworden op 7 augustus van Lisa. Een zusje voor Emma.
Hierdoor ben ik van 7 augustus tem 21 augustus minder bereikbaar.
Mijn mails lees ik wel, maar in veel mindere mate. Het kan dus wat
langer dan 24u duren voor je een antwoord krijgt. Je krijgt ten
laatste antwoord op maandag 22 augustus.

Voor technische zaken kan je contact opnemen met support@newance.be.
Voor commerci�le vragen kan je contact opnemen met Matthieu Voet via
matthieu@newance.be of via het algemeen telefoonnummer 09 391 46 26.

Met vriendelijke groeten,
Pieter Cappelle
pieter@newance.be

**Comment by tkacheva** [comment]
@allanpaiste could you provide steps to reproduce? I added conditions, saved, opened again added new conditions, saved, opened once again. Conditions are in place

**Comment by allanpaiste** [comment]
Ah yes. It's an issue in the stable 2.1, but was indeed fixed with 3ff19bf, commented on that on https://github.com/magento/magento2/issues/5398, forgot to do same here as well. 

Also had repeatability steps there, but - again - this is no longer an issue :)

**Comment by tkacheva** [comment]
@allanpaiste closing then. Thank you for your input :-)
