### ISSUE TITLE
Magento2.1.0 Configuration->Design   can't select theme

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#5310]
## Steps to reproduce
1. Magento2.1.0 was downloaded at  https://www.magentocommerce.com/download;
   2.Command-line installed successfully.
2. Select Store at the backend STORE -> Configuration -> General -> Design , there is only one Search Engine Robots , theme can't be selected.
## Actual result

![magento2 1 0](https://cloud.githubusercontent.com/assets/15027055/16414659/7803c268-3d6b-11e6-98cb-7e7177184c66.jpg)

**Comment by hostep** [comment]
Duplicate of #5240

@cfcnn: it has been moved to Content => Configuration

Please try to search for an issue first before creating a new one, this has been reported like 6 times already.

**Comment by cfcnn** [comment]
@hostep Thanks, I got it.  But  Content => Configuration   no response after click, please see the picture.

![design configuration](https://cloud.githubusercontent.com/assets/15027055/16416444/db95f144-3d74-11e6-9a56-b79a88d8c61a.gif)

Under CONTENT , "Widgets" "Themes" "Schedule"  are normally working. 
"Pages" "Blocks" "Configuration"   are keeping " loading", no upcoming response. 

Magento2.1.0 was newly installed, cache was cleaned. There is no such problem in 2.0.7 

My environment: Centos 6.8 PHP 7.0.7 NGINX 1.10.0 MariaDB 10.0.23

**Comment by cfcnn** [comment]
@hostep Thanks a lot. It's solved after cleaning chrome cache.
