### ISSUE TITLE
Admin: style issue for disabled checkbox in grid

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#5311]
## Steps to reproduce
1. M 2.0.4 EE
2. in Admin panel create custom page with grid, or (in my case) - add new tab to admin/user/edit with grid 
3. add column to grid with type "checkbox", and set "disabled_values" there to have disabled checkboxes
## Actual result
1. desktop - label is a little over the checkbox
   ![kate s users permissions system magento admin](https://cloud.githubusercontent.com/assets/10142848/16415696/32c12c5a-3d47-11e6-8e82-1350d5ea8acf.png)
2. mobile - cherbox stays on fixed position, if page is scrolled to right
   ![kate s users permissions system magento admin1](https://cloud.githubusercontent.com/assets/10142848/16415701/37d24c88-3d47-11e6-936e-5f12ac3d5f29.png)

**Comment by MomotenkoNatalia** [comment]
Hi @katesuykovskaya ! Thanks for reporting this issue! Internal ticket MAGETWO-55169

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
