### ISSUE TITLE
Authorizenet payment method can not going to success page

### ISSUE THREAD

**Issue by nileshpatelifuturz** [magento/magento2#5312]
I have try to place order using Authorizenet payment method (Test Mode) but every time I can not go to success page. No any error occur but all the script executed and after loader continue loading not going to success page and in the background order successfully placed. When I have go to success page using url it will showing Order successfully placed. 

I have checked all the magento 2 versions including latest version 2.0.7.

Can you please check and resolve it.
![authorizenet](https://cloud.githubusercontent.com/assets/18419009/16416059/0087854c-3d5e-11e6-8d54-52559862866d.png)

**Comment by nileshpatelifuturz** [comment]
Can you please help me ? 
How I can resolve it ?

**Comment by mverstraete** [comment]
Does it flash an error that says "No such entity with cartId = ##" briefly above the Payment heading?  If so, it may be related to this:  https://github.com/magento/magento2/issues/4813

**Comment by alena-marchenko** [comment]
Hi @nileshpatelifuturz 

Do you use Authorize.net test mode with test or production account credentials?

**Comment by nileshpatelifuturz** [comment]
Hi **@alena-marchenko** 

Yes, I have used Authorize.net test mode with test account credentials.

**Comment by alena-marchenko** [comment]
Hi @nileshpatelifuturz 

Please set Test Mode to "No" and try to place order. Test Mode in Authorize.net is intended for testing with production credentials.

**Comment by nileshpatelifuturz** [comment]
Hi **@alena-marchenko** 

I have setup Authorize.net Test Mode to "No" and checked then one error alert like "Please enter a transaction ID to authorize this payment".

Also please see screenshot for the same.
![authorize_error](https://cloud.githubusercontent.com/assets/18419009/16518463/8c2137a8-3fa0-11e6-855a-04801ed4b9a9.png)

**Comment by alena-marchenko** [comment]
Hi @nileshpatelifuturz 

Please provide us with screenshot of Authorize.net payment method configuration in Magento for us to be able to assist further.

**Comment by nileshpatelifuturz** [comment]
Hi @alena-marchenko 

Actually I have setup Authorize.net Gateway Url with live site url that's why it was return transaction id empty. Now I have setup Test Mode gateway url and it was work.

**Comment by wakar** [comment]
> Please set Test Mode to "No" and try to place order. Test Mode in Authorize.net is intended for testing with production credentials.

Thankyou so much,it works for me.
