### ISSUE TITLE
LESS-Code doesnt appear in style-l.css - probably a bug?

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5315]
We are using Magento 2.0.6 on one of our Stages. 

We are using a theme that uses Luma as parent. 

In our theme folders we have 

> web/css/source

Within that folder we have:
- _extend.less
- _theme.less
- owl/_owl.less

_owl.less gets imported at _theme.less. 

In _owl.less I change a specific line from "display: block" to "display: inline-flex". Now I do the following:

$ rm -rf pub/static/frontend/{NAME}/{namespace}/de_DE/*

as descriped in the LESS Debuging Page of Magento, and:

$ rm -rf var/page var/page_cache var/view_preprocessed

WHAT DO I EXPECT HERE:
The desired class should have swapped from "display: block" to "display: inline-flex"

WHAT HAPPEND:
It stays the same.

Am I doing something wrong here, or is this a bug with encapsulated .less-files? Somehow the less file didn't get imported again if the user compiles the less file again in his browser. 

Additional edit: 

It seems like that I forgot to clear view_preprocessed, if I rm this directory and $ rm -rf pub/static/frontend/{NAME}/{namespace}/de_DE/\* it generates the correct new CSS. 

Just a wild guess, but wouldn't it be useful to add view_preprocessed to the cache:flush command, or generally add a command that clears all CSS-related folders? Close it if you like, but maybe others want to commit their thoughts to this idea.

**Comment by eug123** [comment]
Hi @grasdaggel, 

There is a button `Flush Static Files Cache` in the bottom of the Admin -> System -> Cache Management page.

Thank you

**Comment by grasdaggel** [comment]
Hi @eug123 - while its true that the button is there, I would like to disable this caching temporarily, but its not possible - i have to flush the cache manually all the time, why can't I disable this cache as well, like full page cache or config cache?

**Comment by eug123** [comment]
@grasdaggel, please check [client-side less compilation](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css-preprocess.html#less_modes), or more advanced workflow - compiling your less files [with nodejs](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html#css_debug_server).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
