### ISSUE TITLE
Refund report does not show right date

### ISSUE THREAD

**Issue by webartistse** [magento/magento2#5317]
## Steps to reproduce
1. An order was created at 9th june.
2. A credit memo was created 17th june and refund has been made.
3. Accountant generates a report 27th june.
## Expected result
1. The refund in report should appear under 17th june.
## Actual result
1. The refund in report should appear under 9th june.

**Comment by veloraven** [comment]
@webartistse please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by webartistse** [comment]
@veloraven Im using Magento 2.0.7.

For an accountant its hard do accounting right reports since the Magento report shows refund on 9th june and the actual refund from bank account has been made 17th june.

**Comment by slopukhov** [comment]
@webartistse thank you for your feedback. 
Internal issue created: MAGETWO-60628

**Comment by veloraven** [comment]
This issue was fixed for develop branch.
Closed.
