### ISSUE TITLE
500 Response: "Unable to clear session lock record" during checkout when using Memcached for sessions

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5319]
Red Hat Enterprise Linux Server release 6.8 (Santiago)
php-common-7.0.8-1.el6.remi.x86_64
php-pecl-memcached-3.0.0-0.1.20160217git6ace07d.el6.remi.7.0.x86_64
memcached-1.4.27-1.el6.remi.x86_64
## Steps to reproduce using PHP 7.0.8 with Memcached 1.4.27 for Session Storage on RHEL 6.8 x64
1. Install Magento from `2.0`, `2.1` and `develop` CE branch.
2. Ensure PHP Memcached Session Lock Wait Minimum is default value of ``0``<br/>
   `php -i|grep sess_lock_wait_min`<br/>
   `memcached.sess_lock_wait_min = 0;`
3. Add Configurable Product to the cart.
4. Attempt to complete checkout
## Expected result
1. Checkout completes without any error responses from server.
## Actual result
1. Occasionally, Error occurs: "500 Response" During AJAX Checkout Steps, No UI feedback.
2. Error is logged in var/report/$(date +%s)<br/>
   `a:4:{i:0;s:187:"Warning: SessionHandler::read(): Unable to clear session lock record in /var/www/magento2/demo_example_com/lib/internal/Magento/Framework/Session/SaveHandler/Native.php on line 22";i:1;s:6232:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '/var/www/magent...', 22, Array)`
## Possible Workaround
1. Edit /etc/php.d/50-memcached.ini<br/>
   `- memcached.sess_lock_wait_min = 0;`</br>
   `+ memcached.sess_lock_wait_min = 250;`
2. Restart PHP-FPM

As this setting was not identified as required in the following documents, I am curious if 250 milliseconds is a good value and if it may impact any other areas of functionality.
http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements.html
http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html

**Comment by martiGIT** [comment]
same issue at Magento 2.1 with memcached 1.4.21-1.1 at debian 8. Also changing memcached.sess_lock_wait_min to 250
`memcached.sess_lock_wait_min = 250` 
does not resolve this issue. 

`a:4:{i:0;s:167:"Warning: SessionHandler::read(): Unable to clear session lock record in (...)/magento/framework/Session/SaveHandler/Native.php on line 22";i:1;s:5977:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '(...)/publi...', 22, Array)
`

**Comment by hendywijaya** [comment]
Hi Guys, 
I found the similar issue with Magento EE 1.14 setup
PHP 7.0.9
php-pecl-memcached-3.0.0-0.1.20160217git6ace07d.el6.remi.7.0.x86_64
libmemcached-0.31-1.1.el6.x86_64
memcached-1.4.25-1.el6.remi.x86_64

In Magento 1.14, this issue prevents the user to even login to the site, I managed to get this working by setting `memcached.sess_locking = Off` which is far from ideal, since this would be catastrophic during race / concurrent condition (trust me I've been there watching my quote session went haywire). 

This may not be Magento 2 specific issue, but more of PHP7 + memcached session storage

**Comment by hendywijaya** [comment]
Hi Guys,

a bit of update, this happens on
php-pecl-memcached-3.0.0-0.1.20160217git6ace07d.el7.remi.7.0.x86_64

but **not** on 
php-pecl-memcached-2.2.0-3.el6.remi.5.6.x86_64

so it's seems issue is related to pecl itself, haven't been able to replicate the issue using non-magento php script, but if you are to, you can report the issue to : https://github.com/php-memcached-dev/php-memcached

**Comment by tim-reynolds** [comment]
I wanted to add that I have a client on EE 2.1 and downgrading to the previous version of the module worked for us, as recommended by @hendywijaya

**Comment by peec** [comment]
Same issue here. Using memcached cluster client from AWS (memcached 2.1.0). 

This error happens occasionally, and is very important to fix. The error can happen in both frontend and backend.  
- Magento: 2.1.1
- Amazon linux ( EC2 )
- Nginx
- PHP 7 & php-fpm
- Memcached: https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php ( which is in fact  based on memcached 2.1.0 - https://github.com/php-memcached-dev/php-memcached. )

#### One of the methods that last caused this error:
1. Add a new configurable product
2. Add some data to the product, including some simple products in the configurable.
3. Try to save the product.
4. After a bit of waiting for the request to finish.. 500 error and "Unable to clear session lock record" in the log files.

#### Our temporary fix:

Use database for sessions, ugh..

**Comment by joates-ldg** [comment]
I'm running the same setup as @peec but with 2.1.3 and experiencing the same issue.

However I can login to the admin, we are instead receiving an error on the product overview page of the admin while trying to load an ajax page.

I've switched to DB for sessions, which has resolved the issue, however again I don't think this is a long term fix.

**Comment by ghost** [comment]
We had a recurrence of this issue with a client and, as @hendywijaya recommended, were unable to find a packaged 2.2.0 branch of PHP-Pecl-Memcached for PHP7 (without compiling). In order to resolve this issue we decided to implement Redis for session storage [using the Magento 2 docs](http://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-session.html). The issue has not recurred since switching session storage to Redis. We will monitor this for a few days an post an update, but we believe we are simply avoiding memcache to avoid this issue.

**Comment by ghost** [comment]
needless to say, this has not recurred

**Comment by elyobo** [comment]
Probably caused by https://github.com/php-memcached-dev/php-memcached/pull/266; workaround is to explicitly set `memcached.sess_lock_expire` (with the same value as `max_execution_time` being a sane default).

**Comment by ewbarnard** [comment]
We see the problem while upgrading Magento EE 1.14.0.1 using PHP 7.2 and the latest pecl memcached extension. Has "unable to clear session lock record" been solved? I've tried tweaking various php ini settings as described elsewhere to no avail.
