### ISSUE TITLE
Configuration admin screen error report after upgrading to 2.1 with sample data

### ISSUE THREAD

**Issue by robfico** [magento/magento2#5320]
## Steps to reproduce
1. Upgrade from 2.0.6 to latest 2.1.0 version with sample data (using php 7.0.7)
2. Go to: Stores -> Configuration
## Expected result
1. Admin page appears
## Actual result
1. Error report (attached)
   [mag2_error_report.txt](https://github.com/magento/magento2/files/337579/mag2_error_report.txt)

I tried flushing cache, flushing OpCode cache, reindexing, etc... but no change in behavior.

**Comment by dthampy** [comment]
Based on the error report attached, it looks like the upgrade failed.
There is an internal jira ticket MAGETWO-55229 that addresses this issue.

**Comment by magento-engcom-team** [comment]
@robfico, thank you for your report.
We've created internal ticket(s) MAGETWO-62025 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@robfico, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
