### ISSUE TITLE
Object DOMDocument should be created

### ISSUE THREAD

**Issue by kishanpatadia** [magento/magento2#5323]
After upgrading to Magento 2.1 CE from 2.0.7, when I click on product in backend from grid, I got dialog with: Attention Something went wrong.
Error says like following:

**Object DOMDocument should be created**

**Comment by orbitrod** [comment]
I am having the same issue.

**Comment by orbitrod** [comment]
There are several stack exchange posts about this, but no solution so far.  
http://magento.stackexchange.com/questions/123022/attention-something-went-wrong-on-backend-product-page
http://magento.stackexchange.com/questions/109224/magento-2-attention-something-went-wrong-clicking-contentblocks-page-doesnt/111218
http://magento.stackexchange.com/questions/109224/magento-2-attention-something-went-wrong-clicking-contentblocks-page-doesnt

**Comment by kishanpatadia** [comment]
May be following can help. But not sure.
http://magento.stackexchange.com/questions/123022/attention-something-went-wrong-on-backend-product-page

Let me know if it works.
Thanks

**Comment by kodmaskinen** [comment]
We had disabled the output of the review module (Configuration -> Advanced -> Advanced), when we enabled it again, the problem went away.

**Comment by kishanpatadia** [comment]
Thanks a lot. I will try it.

**Comment by Choufourax** [comment]
I enabled again the review module as mentionned by @AndreasSundstrom and the error went away.
But if I disabled it again, the error comes back.

**Comment by hostep** [comment]
@piotrekkaminski, @guz-anton, can you guys please review this bug?
We also run into this on Magento 2.1.0 if we disable the Reviews module in the Advanced section.

**Comment by kishanpatadia** [comment]
After enabling review module, this error will not occur.

**Comment by GordonLesti** [comment]
From my point of view, not a valid reason to close this issue.

> After enabling review module, this error will not occur.

**Comment by davidbilly** [comment]
@GordonLesti Yeah, It's seem Magento System force us to us review module.  Should be fix it :(

**Comment by GordonLesti** [comment]
https://github.com/magento/magento2/pull/5663 fixes this

**Comment by davidbilly** [comment]
@GordonLesti Thanks for your hard work mate :D

**Comment by SchumacherFM** [comment]
We need this also, hope it gets merged within the next 3 months ...

**Comment by andimov** [comment]
We already have internal ticket MAGETWO-56794  in our backlog.

**Comment by jstoel** [comment]
The "Something went wrong" error isn't always fixed by enabling the review module. I'm having this error pop up when I try an access the back end product list and this module is active.

**Comment by miakusha** [comment]
Closed as already fixed in #6704

b046944

**Comment by bubeamos** [comment]
when i search for a product on a megento 2.0 store I get 
"There has been an error processing your request

Object DOMDocument should be created.
Error log record number: 998986072482". Please what is the possible cause and how can i fix it.

**Comment by anton-huz** [comment]
@Chidiebube 
When you get a message _"Error log record number: 998986072482"_ it means, that you can find a stack trace on disk storage under `<path/to/Magento>/var/report/998986072482`.

It would be handy if you attach a screenshot with browser console and content of `998986072482` file.

**Comment by bubeamos** [comment]
@guz-anton I have attached the file 998986072482 below. Also the same error occurs if I  click on the checkout button and I have attached the report 1218900441657. The browser console was blank. Thanks..

[998986072482.txt](https://github.com/magento/magento2/files/511101/998986072482.txt)

[1218900441657.txt](https://github.com/magento/magento2/files/511120/1218900441657.txt)

**Comment by trilokgupta** [comment]
I have same issue in log file what can i do. if it  fixed then please let me know

Thanks

**Comment by dreamdev21** [comment]
I am using magento 2.1.5
Same error occurs to go click on the checkout button.

**Comment by Anshu-Mishra** [comment]
I am facing this issue on Magento 2.1.9
