### ISSUE TITLE
Can't Use a Symlinked Module During Development

### ISSUE THREAD

**Issue by astorm** [magento/magento2#5326]
Steps to reproduce
1. Create a simple module in `app/code` using the instructions below, or using the [attached zip file](https://github.com/magento/magento2/files/339488/Pulsestorm_Symlinkbug.zip) (or via your own means, adjusting the URLs mentioned below)
2. Confirm module is created and installed by accessing URL `http://example.magento.com/pulsestorm_symlinkbug`
3. Navigate to `Stores -> Configuration -> Developer -> Template` and set "Allow Symlinks" to `1`
4. Move the `app/code/Pulsestorm/Symlinkbug` folder to _a place outside the Magento root_
5. Create a symlink at `app/code/Pulsestorm/Symlinkbug` which points to _a place outside the Magento root_ (ex. `~/Documents/magento-modules/Symlinkbug`)
6. Access the URL at `http://example.magento.com/pulsestorm_symlinkbug` again
## Expected result: 
1. Page loads identically both times
## Actual result
1. The controller action endpoint responds, but without rendering the `phtml` template
## Context

This bug impacts developers who use symlinks in their deployment setups, and in their development workflows.  Magento added the "Allow Symlinks" setting explicitly to enable these workflows.  The problem appears to be the code that validates the templates in 

```
#File: vendor/magento/framework/View/Element/Template/File/Validator.php
public function isValid($filename)
{
    $filename = str_replace('\\', '/', $filename);
    if (!isset($this->_templatesValidationResults[$filename])) {
        $this->_templatesValidationResults[$filename] =
            ($this->isPathInDirectories($filename, $this->_compiledDir)
                || $this->isPathInDirectories($filename, $this->moduleDirs)
                || $this->isPathInDirectories($filename, $this->_themesDir)
                || $this->_isAllowSymlinks)
            && $this->getRootDirectory()->isFile($this->getRootDirectory()->getRelativePath($filename));
    }

    return $this->_templatesValidationResults[$filename];
}
```

The `$this->getRootDirectory()->isFile($this->getRootDirectory()->getRelativePath($filename))` check fails -- and confusingly based on the names, seems to be a check that explicitly runs counter to the `$this->_isAllowSymlinks` check. 

How to handle this is a policy decision that's best left to the framework/platform owner, but removing the ability to symlink components in Magento 2 runs counter to an early stated goal of Magento 2 (formalizing components so they could run anywhere), and regardless of current goals is hostile to developer experience. 
## Module Creation Instructions

Using [pestle](https://github.com/astorm/pestle), generate and enable the module with the following commands.  Generated module is also attached.

```
pestle.phar generate_module Pulsestorm Symlinkbug 0.0.1

pestle.phar generate_route Pulsestorm_Symlinkbug frontend pulsestorm_symlinkbug

pestle.phar generate_view Pulsestorm_Symlinkbug frontend pulsestorm_symlinkbug_index_index Main content.phtml 1column

php bin/magento module:enable Pulsestorm_Symlinkbug

php bin/magento setup:upgrade
```

**Comment by veloraven** [comment]
@astorm thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by snez** [comment]
@veloraven I can't tell about @astorm but in my case this is an issue that appeared in Magento 2.1 (works fine in 2.0.7) and manifests itself in the admin area for a certain adminhtml template file but not on other symlinked module files. It occurs at the same place as @astorm:

```
$this->getRootDirectory()->isFile($this->getRootDirectory()->getRelativePath($filename)
```

$filename in my case points to a file that is outside the Magento root directory. The module symlink is at app/code/Vendor/ModuleName and the actual file is under app/code/Vendor/ModuleName/view/adminhtml/templates/form/filename.phtml

I'm on Mac OS X 10.10.5 using PHP 7.0.8 configured as fastcgi under nginx 1.8.0

**Comment by astorm** [comment]
Closing out due to lack of response from core team.

**Comment by snez** [comment]
@astorm the issue was acknowledged as a bug, that's good enough of a response no?

**Comment by pboisvert** [comment]
@snez actually the "bug" label means we are investigating as a possible bug. When we reproduce an issue then we add the "acknowledged" label. 

@piotrekkaminski Can you review and reopen (or clone) if a valid issue, or if more of a dev experience improvement, file in Jira and add the jira ticket here (or to the clone)?

**Comment by seyuf** [comment]
Hi guys,
Any updates on this? I'm unable to get my .pthtml to be displayed when the symlink is outside of magento2 root directory. 
Ex:
```
 app/design/[Mevendor]/[metheme] --> pointing to /var/www/magento2/metheme (works fine)
 
but

 app/design/[Mevendor]/[metheme] --> pointing to ~/Document/metheme (not processing overrided templates)
```

Magento 2.1.6
Nginx
Debian Jessie

**Comment by adam-paterson** [comment]
@pboisvert Has nobody been able to replicate this yet? Just as @snez mentioned this stems from:
`\Magento\Framework\View\Element\Template\File\Validator::isValid` with the line `$this->getRootDirectory()->isFile($this->getRootDirectory()->getRelativePath($filename));`.

Unless the mage root is defined in the requested path it is prepended. See @seyuf's comment for an example.

**Comment by adamof** [comment]
Any chance this is going to get fixed soon? :(

**Comment by LiamKarlMitchell** [comment]
In my case, I needed to ensure the whole directory structure had execute on directories.

Plesk uses same user for apache as it does terminal/sftp/ssh.

```bash
cd ~/httpdocs
chmod -R o+X .```
