### ISSUE TITLE
Normal PayPal Checkout Taking to Review Page with "We can't place the order." while Skip Review Page Has been Enabled

### ISSUE THREAD

**Issue by s00071609** [magento/magento2#5327]
## Steps to reproduce
1. Install Magento 2.1
2. Add any product to cart
3. Hit Go TO Checkout
   Select Checkout with Paypal Option
   Login and Hit PayNow
## Expected result
1. After Hitting PayPal Pay Now button - success page should display (Skip Review Page is Enabled in PayPal Website Payment Method")
2. There should be option to CREATE an account on success page
## Actual result
1. Takes to Review Page - with "We can't place the order." in RED
2. Surprisingly - The Order will already been placed by now "Before you hit - Place Order at bottom of Rewiew Page. You can basically do nothing on this page as the order is already placed, and "we cant place the order continues"
3. With Magento 2.1, the PayPal checkout does not provide option to create account - unsure if it would have provided this option if I could go beyond the Review Page -----to success page

**Comment by Nerogee** [comment]
I have the same issue "We can't place the order". Need help.

**Comment by s00071609** [comment]
Well, the order goes through when PayNow button is Hit, and order emails start to come from PayPal but the review page shows up with the error. If you submit order in review page, it does nothing just repeats the error. Also with magento 2.1 the cart items show up even after checkout. Hope someone out there is able to help

**Comment by Nerogee** [comment]
I encountered this issue when upgrade from 2.0.7 to 2.1. Suspecting I do something wrong that causes this issue. Then I have a fresh installation via composer. but still there is error. Both Paypal and Braintree is not able to checkout. 

magento 2.1
php 7.0.7
libcurl 7.49.1

**Comment by s00071609** [comment]
Could it be issue with SSL - but when you have said "YES" to Skip Review Page,- doesnt make sense that paypal takes to Review Page. Even when you say NO to skip Review Page. It gives the same error. The only difference is - in the first case the error occurs before Review Page loads. In second case, Error Occurs when you hit Order Now - This will put off many from using 2.1. If its a bug, then it makes this release unusable if you rely on PayPal.

**Comment by s00071609** [comment]
Looks like its the upgrade process from 2.0.7 to 2.1 that is causing the issue. Clean install in an unused domain works fine - Just added a test product and checked out as usual using paypal. It then goes to the success page without going to review page. Something from old install might that is causing issue in new install. Hope this gets fixed as there may be many moving from 2.0.7 to 2.1. Its upgrade issue...

**Comment by alena-marchenko** [comment]
Hi @s00071609 

Please specify what Payment Action do you use for PayPal (Sale or Authorization) ?

**Comment by s00071609** [comment]
I am using Sale as Payment Action at the moment. Either way they go through same steps. I am using exactly same setting as in the 2.1 version in another site with 2.0.7. 
Please let me know if there is any fix for it - as its crucial to have working paypal checkout

**Comment by alena-marchenko** [comment]
Hi @s00071609 ,

thanks for reporting this issue. It is already being tracked by MAGETWO-54787 ticket and fix will be delivered soon.
This issue will be closed as duplicate of #4785.

**Comment by Nerogee** [comment]
@alena-marchenko My case is not a simple ALTER query can fixed. btw, as I said my magento2.1 is fresh installed. There is no any error except that I found the **PAYMENTREQUEST_0_INVNUM** is always 000000001. So it means that order id is not auto increased. What a shame error it is! What should I do?

**Comment by lucscu** [comment]
REPLY AND FIX THIS ISSUE PLEASE!

**Comment by lucscu** [comment]
THERE IS AN ERROR WITH CONFIGURABLE PRODUCTS OR PRODUCTS WITH OPTIONS.
Please fix it!

**Comment by lfritsche** [comment]
@alena-marchenko please reopen ticket as same behaviour persists in 2.1.5.

Although PayPal Review Step is disabled, I get redirected to it and placing an order is not possible.
I could resolve the redirect issue by re-enabling some checkout fields, as I had them disabled previously. (Company, Telephone, Country = always DE)

I followed the official docs to completely remove checkout fields (JSON,...).
Is there a possibility to remove fields without braking the whole checkout process?

Thank you!

**Comment by almarchenko** [comment]
HI @lfritsche! I'm from the Magento docs team. Could you give us the link, which doc did you follow?If I got it right and it led you to having problems with checkout, we would like to verify the doc, thank you.

**Comment by lfritsche** [comment]
Hi! I have read the following Issue: https://github.com/magento/magento2/issues/4425
and wrote a Plugin according to: http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_customize.html#remove-a-component

```
public function aroundProcess(
        \Magento\Checkout\Block\Checkout\LayoutProcessor $subject,
        \Closure $proceed, $jsLayout
    ) {
        $ret = $proceed($jsLayout);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']
            ['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['region_id']);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']
            ['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['region']);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']
            ['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['country_id']);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']
            ['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['prefix']);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']
            ['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['care_of']);
        return $ret;
    }
```

**Comment by almarchenko** [comment]
@lfritsche  Thanks, we'll take a look at the doc (internal issue MAGETWO-69158)

**Comment by almarchenko** [comment]
@lfritsche  We've verified the doc and it is correct, so there's something else that's causing the issue.
Thank you.

**Comment by jer23jk** [comment]
Any solution for this bug?

Magento 2.1.7 > Order Variable product with custom option Date > Pay with Paypal

Transaction in successful, but after redirecting from paypal there is a red statement We can't place the order.

**Comment by ghost** [comment]
We are on Magento 2.1.6 and have the same bug.
Any solutions yet?

**Comment by NiteshKuyate** [comment]
We are on Magento 2.1.5 but we get that exception sometimes.
Any solutions yet?
