### ISSUE TITLE
Luma Theme bugs Magento 2.1 on iPhone 6s ios 9.3.2 (maybe all mobiles)

### ISSUE THREAD

**Issue by HRR1337** [magento/magento2#5328]
## Steps to reproduce
1. Install Magento 2.1 from website magento.com with sample products
2. I have configured magento with minify / bundle js and css
3. Use (in my case) an iPhone on the Luma theme
## Expected result
1. When clicking on a product with multiple images, see first image on screen
2. When clicking on 'Cart' icon, dont move the cart and search icon to new row
3. When clicking on 'add to cart' see message and see also first image of product.
## Actual result

**1. Clicking on a product shows second 'image' (only its empty).** 

![no-image-second-product](https://cloud.githubusercontent.com/assets/4428675/16442494/521609e0-3dd3-11e6-8cb5-c2c53b10e39c.jpg)

**2. Clicking on cart will move the cart icon and search icon to second row.**

![cart-second-row](https://cloud.githubusercontent.com/assets/4428675/16442501/5b4fd2de-3dd3-11e6-8fd1-ad55a97e9201.jpg)

**3. Clicking on add to cart will give you a message but wont show you the product image.** 

![add-to-cart-no-image](https://cloud.githubusercontent.com/assets/4428675/16442508/64934a42-3dd3-11e6-9c0e-ff3e173f318d.jpg)

**Comment by undefined-olha** [comment]
Thank you! Internal issue MAGETWO-54218.

**Comment by MomotenkoNatalia** [comment]
Hi @HRR1337 !  Internal ticket MAGETWO-54218 is closed and delivered to mainline. Please let us know if you still have an issue

**Comment by HRR1337** [comment]
Hi there. Does it mean i have to install m2 dev. version to see the result? Thanks!
