### ISSUE TITLE
In a CMS Page, can I call a custom phtml with custom attributes? Example inside.

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5329]
Hi there,

the standard way to call a PHTML file inside a Page CMS is this:

> {{block class="Magento\Framework\View\Element\Template" name="test_file" template="Magento_Theme::html/test.phtml"}}

What I want to do is for example pass several arguments to that block. Example:

> {{block class="Magento\Framework\View\Element\Template" name="test_file" template="Magento_Theme::html/test.phtml" data-title="New Products" data-productamount="5"}}

What I generally want to achieve is to make PHTML files more dynamically. Is this possible? On Stackexchange I've found nothing for this matter, so maybe this could be a feature for future Magento2 releases. 

What do you think about that? Is something like this already possible?

**Comment by veloraven** [comment]
@grasdaggel is this issue still actual?
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
As GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
