### ISSUE TITLE
Issues regarding default or null values for attributes

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#5331]
Recently we started experiencing two significant issues with one of our Magento 2 installations regarding the default (or null) values of product attributes. One of those has been reported before and is well documented within the following GitHub issue:
https://github.com/magento/magento2/issues/3545
The second problem seems to be caused by the very same issue and has been described (more or less) by two GitHub tickets as well:
https://github.com/magento/magento2/issues/2810
https://github.com/magento/magento2/issues/4111

The main issue here seems to be the wrong setting of default values on dropdown (or selectable) attributes, causing not only unwanted product attributes to be rendered on the PDP anyway (since resetting values or setting “null” over the backend is impossible) but having product attributes, which are not even assigned to the attribute sets used by the listed products, presenting unset values within the layered navigation upon viewing product category pages (for example: “color” is not added to the attribute sets used by the products within the requested category, yet the default option value “white” is listed within the layered navigation and returns all products – even when they cannot even have any value set for that very attribute).

Luckily both issues seem to have been fixed within release 2.1 of the Magento 2 platform, since all tickets were confirmed to be resolved the last couple of weeks. Only thing we are missing here is a solid confirmation of the assumption the fixes are within 2.1, assuring us an upgrade will solve both problems (and avoiding unnecessary efforts into upgrading our installation).

Thanks in advance for looking up in which releases the fixes have been or will be merged and thus assisting us in correcting the presentation of the product catalog as soon as possible!

With kind regards,

Sidney Billiet
Project Manager / e-Commerce architect
Magento Certified Solution Specialist
Studio Emma

**Comment by andimov** [comment]
@SidneyBilliet 
Thank you for reporting!
We already have internal ticket MAGETWO-50123 to fix it.

**Comment by magento-engcom-team** [comment]
@SidneyBilliet 
The issue has been fixed in 2.2.0 release
