### ISSUE TITLE
Cannot change date format in checkout date fields

### ISSUE THREAD

**Issue by ddattee** [magento/magento2#5335]
I have a french/arabe website to customize and I need to display dates in "dd/mm/yyyy" format in the checkout instead of default format displayed.
## Steps to reproduce
1. Install Magento from `2.0.7` branch.
2. Add a product to cart and go to checkout onepage
## Expected result

Date displayed and formated in french format in the checkout.
## Actual result

No possibility to change format and even if I update everything for it to work I still run into side bugs.
## What I have tried : 
1. Set `dateFormat` to 'dd/mm/yy' on calendar on date fields throught a LayoutProcessor and by extending "$.calendarConfig.dateFormat".
2. Override `validate-date` function to allow to use a given format to validate date
3. Override `jquery-ui-datepicker-addon::_setDateDatepicker` function with an updated version from the original repo (https://github.com/trentrichardson/jQuery-Timepicker-Addon) 
4. Updated the ajax save functions to reformat date into Magento back end friendly date format (mm/dd/yyyy).

With all this I can display my dates properly formated and sometimes go throught the checkout process. 
But I have sides bug happening like 
- I can only select a date once after that no change is possible
- sometimes validation fails and I don't know why, my validate-date function doesn't seem to be called
- some dates cannot be selected

In a word changing date format in the checkout is a real pain so I was wondering if there was native solution that I had missed.

**Comment by ddattee** [comment]
Here is the code of what I tried : 
- LayoutProcessor.php
  
  <pre>
  ...
  'birth_date' => [
  'options' => [
    'dateFormat'  => 'dd/mm/yy',
  ],
  'config' => [
      'validation' => [
         'validate-date' =>  'dd/mm/yy'
      ],
  ],
  ]
  ...
  </pre>
- calendar-config.js
  
  <pre>
  $.extend(true, $, {
  calendarConfig: {
      dateFormat  : 'dd/mm/yy',
  }
  }); 
  </pre>
- validate-date.js
  
  <pre>
  validator.addRule(
  'validate-date',
  function(value, param) {
      var test = !utils.isValidFormat(param) ? new Date(value) : $.datepicker.parseDate(param, value);
      return utils.isEmptyNoTrim(value) || !isNaN(test);
  },
  $.mage.__('Please enter a valid date.')
  );
  </pre>
- jquery-ui-timepicker-addon.js
  
  <pre>
  $.datepicker._mage_setDateDatepicker = $.datepicker._setDateDatepicker;
  $.datepicker._setDateDatepicker = function (target, date) {
  var inst = this._getInst(target);
  if (!inst) {
      return;
  }
  if (typeof(date) === 'string') {
      var test = date;
      test = new Date(date);
      if (!test.getTime()) {
          this._base_setDateDatepicker.apply(this, arguments);
          date = $(target).datepicker('getDate')
      }
  }
  this._mage_setDateDatepicker.apply(this, arguments);
  }
  </pre>
- utils.js (before ajax save functions)
  
  <pre>
  formatDateToSend: function (date, dateFormat) {
  dateFormat = !dateFormat ? 'DD/MM/YYYY' : dateFormat;
  return moment(date, dateFormat).format('MM/DD/YYYY');
  }
  </pre>

**Comment by magento-engcom-team** [comment]
@ddattee, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
