### ISSUE TITLE
Magento 2 Server Requirements

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5336]
Hi,

I am trying to move to new live server.
I have a query, as Magento recommends upto 7.0.6, Ubuntu and Centos Oracle and Percona for MySQL.
But the server provides fork Maria DB, PHP 7.0.7, Debian 8 and Apache 2.4.10. WIll it be compatibel with 2.0.7 Magneto 2 ??.

Regards,
Navya

**Comment by southerncomputer** [comment]
Yes! Should use 2.1.0 though!

**Comment by ghost** [comment]
I think PHP 7.0.5 doesn't work, the rest should work.

**Comment by pboisvert** [comment]
closing issue as the question has been answered

**Comment by nmallepally** [comment]
Thank you :+1:  i'm using php 7.0.7 and its working good with 2.0.7 as well.
