### ISSUE TITLE
WebAPI REST POST /V1/products gives a generic error in response, without any details.

### ISSUE THREAD

**Issue by karanbhomiagit** [magento/magento2#5338]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Try creating a simple product by making a call to REST API POST /V1/products.
3. [Example] 
   `{
   "product": {
       "sku": "atoi-item",
       "name": "atoi-item",
       "status": "1",
       "type_id": "simple",
       "visibility": "4",
       "attribute_set_id": "4",
       "price": "3",
       "custom_attributes": [
           {
               "attribute_code": "description",
               "value": "descreeeeeeption"
           },
           {
               "attribute_code": "category_ids",
               "value": [
                   "1",
                   "2"
               ]
           }
       ]
   }
   }`

I get a response : Status code 400.
Body : {
  "message": "Unable to save product"
}
## Expected result
1. Error message in the response body should be more specific.
   There are so many field values that are required to be set on the request JSON, there is no way for the person making the request to identify where the request went wrong.
## Actual result
1. [Example] Error message appears: "Unable to save product".

**Comment by srinivasanithin** [comment]
Error messages needs to enhanced otherwise much time is getting wasting in these troubleshoot this cause for failure.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/WebAPI-REST-POST-V1-products-gives-a-generic-error-in-response/idi-p/45065).

**Comment by signalprime** [comment]
This issue is not resolved here or in the forums.  I also have the same problem, everything looks fine.  But perhaps with some Magento2 upgrade, things have changed and we don't know what is wrong with our requests.
