### ISSUE TITLE
Cant export orders except 20 first orders

### ISSUE THREAD

**Issue by webartistse** [magento/magento2#5344]
## Steps to reproduce
1. Navigate to Sales > Orders
2. Filter on status cancel and show 200
3. Click export > CSV
## Expected result
1. Downloading CSV-file with 38 orders sorted by my selected order
## Actual result
1. Downloading CSV-file with 20 first orders

Using Magento 2.0.7

**Comment by philipecasarotte** [comment]
2.1 fixes this issue.

**Comment by AVoskoboinikov** [comment]
Hi @webartistse 

I've just checked it on 2.1.1 and it worked fine for me. Can you upgrade your installation to 2.1.1 and recheck if it works for you?

Thanks for contributing!

**Comment by Bartlomiejsz** [comment]
Do you know which commit fixes it? Or which files was changed to fix this issue?

**Comment by SilvanLaroo** [comment]
I'm also wondering which commit fixes this issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
