### ISSUE TITLE
Credit memo list with wrong currency

### ISSUE THREAD

**Issue by webartistse** [magento/magento2#5345]
## Steps to reproduce
1. I have several stores with its own currency
2. Sales > Credit memos
3. Filter by Sweden Store
## Expected result
1. Listed credit memos should be in SEK
## Actual result
1. Listed credit memos is in USD. The amount is right but wrong currency prefix. Example 1000 USD instead of 1000 SEK
2. When I click on a credit memo its right in detailed view.

Using Magento 2.0.7

**Comment by yuklia** [comment]
`priceFormat()` method set currency  either from `base_currency_code` column or from base currency in system (`core_config_data` table) in case of @webartistse is USD.
Since grid gets results from `sales_creditmemo_grid` table there are no such column.

**Comment by oleg-onufer** [comment]
Hi @webartistse. 
I cannot reproduce this issue.
If this problem is still relevant Please add more details to your description of the steps you followed when identifying this issue. Screenshots ("currency option" for different Scope") would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
