### ISSUE TITLE
Catelog Search not showing result for less than 3 character

### ISSUE THREAD

**Issue by aditya-makwana** [magento/magento2#5346]
## Steps to reproduce
1. Set **Minimal Query Length**  to 1 in admin panel under Catalog Search.
   Search in Magento 2.0 default catalog search with less than 3 character in search field.

**2.  Set Minimal Query Length  to 10 in admin panel under Catalog Search.
       Search in Magento 2.0 default catalog search with less than 3 character in search field.**
## Expected result
1. List of searched product which having phrase entered in catalog search box.

**2 "Minimum Search query length is 10" warning message**
## Actual result
1. "Your search returned no results." warning message with zero result come.

**2 If there is products available having any phrase entered in search box, then it will give list of products. When there is no result found with matching phrase in search box it will give you "Minimum Search query length is 10"**

**Comment by maderlock** [comment]
1. It's worth noting that mysql has a minimum word length when doing fulltext indexing. It certainly used to default to 3, which no amount of Magento 2 settings will change. If this is the issue then have a look at http://dev.mysql.com/doc/refman/5.6/en/fulltext-fine-tuning.html for how to adjust this.

**Comment by maghamed** [comment]
This bug has already been fixed in mainline internal ticket number - MAGETWO-50704
Fix exists in 2.1.\* branch
But fix didn't get into any patch release in 2.0.\* branch yet.
@choukalos seems we could  deliver current fix in nearest patch release

**Comment by choukalos** [comment]
Added to the queue for 2.1.x patch.

**Comment by apurv-anand** [comment]
Is this in 2.1.1? I don't think it works.

**Comment by magento-engcom-team** [comment]
Hi @aditya-makwana 
This issue is already fixed in `2.1` and `2.2`. Please refer to the [commits mentioning MAGETWO-50704](https://github.com/magento/magento2/search?q=MAGETWO-50704&type=Commits) for the reference.
Thank you.
