### ISSUE TITLE
Unable to export a list of current stock

### ISSUE THREAD

**Issue by webartistse** [magento/magento2#5347]
## Steps to reproduce
1. Reports > Low stock
2. interval of qty: 0 to 999
3. Search
## Expected result
1. Show all products that has smaller than 999
## Actual result
1. Only show products with 0

Data for warehouse location
Should be support for location in warehouse and see this on packling list, product stock report etc. Its very common you have a marked slot/section in warehouse to find the product.

Import/export inventory list
Option to export stock/inventory list. Lets say the list has name, sku, warehouse location and qty. During inventory staff can manually change the file after counting and import easy to update the qty.

**Comment by veloraven** [comment]
@webartistse thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
