### ISSUE TITLE
Unable to export product data in a good way

### ISSUE THREAD

**Issue by webartistse** [magento/magento2#5348]
## Steps to reproduce
1. System > Export
2. Entity Type > products
3. Several configs to somehow export useful data
## Expected result
1. Select what products I want
2. Deselect some columns
3. Export as Excel XML
4. Support for saving a filter option set. 
## Actual result
1. Total mess of everything
2. This export function is not even useful in any way
3. We have 4 stores but same product catalog. We have config prouct with variants. In export file every product appear 4 times. One row is store blank but seems to have all info. 3 other rows has many empty fields but same SKU as the first one.

This exclude thing is all wrong. Lets say I want to export all product for a specific store. Its not possible. I tried to exclude products thats missing info in some fields since its duplicates but export does not apply the exclude filter if the field is empty. Tried many many ways in 30 minutes without any luck with something useful.

Using Magento 2.0.7

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-export-product-data-in-a-good-way/idi-p/45064).
