### ISSUE TITLE
Cache Files Ignoring magento_umask Setting

### ISSUE THREAD

**Issue by astorm** [magento/magento2#5355]
## Steps to reproduce
1. Install Magento 2.1
2. Clear Magento's cache
3. Create a `magento_umask` file with the contents `000`
4. Load any page in the Magento system
5. Examine the permissions on any cache file (`find var/cache/ -type f -exec ls -lh '{}' +`)
## Expected result
1. Files have `-rw-rw-rw-`/`666` permissions, obeying the umask
## Actual result
1. Files have `-rw-rw----`/`660` permissions, obeying the umask

**Comment by dsikkema-magento** [comment]
Internal ticket: MAGETWO-55294

**Comment by atsareva** [comment]
Hi! Any updates there?
