### ISSUE TITLE
2.1 Cannot refer to less files outside extension

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#5357]
## Preconditions

1. Magento 2
2. grunt

## Steps to reproduce
1. Install Magento 2.1.0
2. Create module that has frontend less file
3. Add import in that less file to "source/lib/_lib.less" or "source/_theme.less" so that theme variables can be used e.g. @primary__color
## Expected result
1. compiled css for extension (as in 2.0.7)
2. ...
## Actual result
1. Error on static deployment:

```
=== frontend -> Magento/blank -> en_GB ===
..............................................................
[Magento\Framework\View\Asset\ContentProcessorException]
  Compilation from source:
  frontend/Magento/blank/en_GB/My_Module/css/mystyling.less
  Unable to get content for 'frontend/Magento/blank/en_GB/My_Module/css/source/_theme.less'
```

There is the mechanism of using source/_extend.less, but that stops anyone using gulp so that's out. We could avoid these includes if we just hard-coded size, font and colors into our module, but that's not a very extensible approach. We just would like to be able to use this as we could in 2.0.7

**Comment by jessetaverne** [comment]
I experience a similar issue after upgrading to M2.1, specifically while @importing _dropdowns.less and _rating.less (default Magento lib files)

In my custom theme i override the web/css/source/_sources.less set by Magento/blank.
The 2 extra files i add here (dropdowns and rating) to import are causing these issues:

> > [InvalidArgumentException]
> > Verify entered values of the argument and options. Unable to get content for 'frontend/[VENDOR]/[theme]/nl_NL/css/source/_dropdowns.less'

and

> > [InvalidArgumentException]
> > Verify entered values of the argument and options. Unable to get content for 'frontend/[VENDOR]/[theme]/nl_NL/css/source/_rating.less'

The only real cause i can think of is that these files aren't in my own theme?
But aren't these just supposed to fallback to lib?

**Comment by maderlock** [comment]
That appeared to be the case in 2.0

**Comment by lucasalfaro** [comment]
Hi,

I am also experiencing this issue. Everything was working fine, untill I started having this issue after clearing cache and redeploying.

>  [Magento\Framework\View\Asset\ContentProcessorException]  
>   Compilation from source:  
>   frontend/Emthemes/everything_shoes/en_US/css/styles-m.less  
>   Unable to get content for 'frontend/Emthemes/everything_shoes/en_US/css/source/_dropdowns.less'  <

I am using:

Magento 2.1
Nexcess share server
Developer mode
template bought (and working fine untill now)

L.

EDIT: Apparently it was a genuine error of my bought template provoked after changing some settings. Therefore I can consider this issue solved.

**Comment by anton-huz** [comment]
The investigation is doing under MAGETWO-48840 internal issue.

**Comment by giacmir** [comment]
A similar issue was already reported in the past, see #4218

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
We've created internal ticket(s) MAGETWO-84635 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @maderlock 
Unfortunately, this ticket pretty much duplicates #4218 mentioned above. You may see the resolution in this comment: https://github.com/magento/magento2/issues/4218#issuecomment-255830934

Closing as duplicate. Thanks.
