### ISSUE TITLE
Image import broken when using pub documentroot

### ISSUE THREAD

**Issue by markalston** [magento/magento2#5359]
When trying to import with images when document root is set to pub it fails.

I added some logging per issue #4711 and received the following error:

> [2016-06-29 15:34:27] main.CRITICAL: Exception: Unable to create directory 'pub/media/catalog/product'. in /var/www/beernut/deploy/live/vendor/magento/framework/File/Uploader.php:579
> Stack trace:
> # 0 /var/www/beernut/deploy/live/vendor/magento/framework/File/Uploader.php(252): Magento\Framework\File\Uploader->_createDestinationFolder('pub/media/catal...')
> # 1 /var/www/beernut/deploy/live/vendor/magento/framework/File/Uploader.php(195): Magento\Framework\File\Uploader->validateDestination('pub/media/catal...')

If I set the document root to the magento directory import works fine.

It looks like it is trying to create the pub/media directory inside of pub.   This could be fixed by giving magento write permissions in the pub main directory but I think that importing should write to the same files regardless of the documentroot.  Seems silly to have magento/pub/pub/media as well as magento/pub/media.

**Comment by davidnguyen2205** [comment]
So what is a solution? I got the same problem in 2.1.0 GA

**Comment by veloraven** [comment]
@markalston thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by alexgoodey** [comment]
This is still present in 2.1.0.

A temporary solution is to create a symlink in pub called pub back to itself. e.g.

cd pub/
ln -s ./ pub
