### ISSUE TITLE
2.0.7 System backup does not work due to JS error

### ISSUE THREAD

**Issue by flnative** [magento/magento2#5360]
## Steps to reproduce
1. Go to admin panel, system, backups
2. Select any option to backup.
3. Click OK to begin backup
## Expected result
1. backup magento
## Actual result
1. The OK button does not click or shows signs of trigger

Nexcess host provider gave me this as the error:
Uncaught TypeError: this.modal.find(...).validation is not a functionAdminBackup.backupConfig.backup-options.actionOk @ backup.js:148modal.jQuery.attr.html.modal.buttons.click @ backup.js:205jQuery.event.dispatch @ jquery.js:4624elemData.handle @ jquery.js:4292

**Comment by miakusha** [comment]
@flnative 
Unfortunately, I could not reproduce the issue as you described it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ikhattaab** [comment]
same problem here !
