### ISSUE TITLE
Customers Online not showing

### ISSUE THREAD

**Issue by crantron** [magento/magento2#5363]
![screen shot 2016-06-29 at 10 55 04 am](https://cloud.githubusercontent.com/assets/3859969/16462854/04e762da-3de8-11e6-82f6-c35bdbd16f3b.png)

Looked everywhere for enabling logs like 1.9 but I could not find anything.

**Comment by mehh** [comment]
Sir - Can you please provide a screenshot that references the "Last Logged In" column?

Regards,

**Comment by crantron** [comment]
![screen shot 2016-06-29 at 11 32 54 am](https://cloud.githubusercontent.com/assets/3859969/16464037/42aa89da-3ded-11e6-9eb2-90be82b70204.png)

**Comment by crantron** [comment]
those are all the columns available.

**Comment by crantron** [comment]
![screen shot 2016-06-29 at 11 34 10 am](https://cloud.githubusercontent.com/assets/3859969/16464080/73a7ab9e-3ded-11e6-83b9-a433b39655a4.png)

**Comment by crantron** [comment]
![screen shot 2016-06-29 at 11 36 19 am](https://cloud.githubusercontent.com/assets/3859969/16464164/c0f3493a-3ded-11e6-873a-7bb66de4616b.png)
- after california , that is the last logged in column

**Comment by wert2all** [comment]
@crantron Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by crantron** [comment]
Current version 2.1.0

**Comment by crantron** [comment]
@wert2all

**Comment by colyield** [comment]
Same problem here. Only shows last activity time and type for visitors.

**Comment by sevos1984** [comment]
Try to run 'bin/magento indexer:reindex'.

**Comment by crantron** [comment]
2.1 fixed this. I'm closing the issue.

**Comment by mdruguet** [comment]
Hello,

Same problem on magento 2.1.8, have u found any solution to solve it?

Best regards
