### ISSUE TITLE
Unable to update the Logo(Header, Footer etc.) in Magento 2.1.0

### ISSUE THREAD

**Issue by prackky** [magento/magento2#5365]
## Steps to reproduce
1. Login to admin.
2. Go to Stores --> Configuration -- General --> Design
## Expected result

Header, Footer and other tabs should be visible.
## Actual result

Only Search Engine Robots tab is visible.

![image](https://cloud.githubusercontent.com/assets/9517618/16464285/190adaf2-3e57-11e6-80ea-490ec2f70517.png)

**Comment by maksek** [comment]
Duplicate - https://github.com/magento/magento2/issues/5256
