### ISSUE TITLE
Data Migration Tool will not install for 2.1

### ISSUE THREAD

**Issue by qrider** [magento/magento2#5368]
I seem to be getting an error when installing the data migration tool through composer.

`composer require magento/data-migration-tool:2.1`
'Your requirements could not be resolved to an installable set of packages.'
`Problem 1
    - The requested package magento/data-migration-tool 2.1 exists as magento/data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7] but these are rejected by your constraint.`

**Comment by Caprico85** [comment]
Data Migration Tool for 2.1 is available since a few days. Please try again.

**Comment by andimov** [comment]
@qrider 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
