### ISSUE TITLE
Working demo project as an equivalent for developers 

### ISSUE THREAD

**Issue by 12th** [magento/magento2#537]
It would be good to check with the latest release from the working demo project. For example, the release was issued, the developer downloaded it and started testing it is not correct work and in this case it would be good to have a platform from which to verify functionality.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23174

**Comment by piotrekkaminski** [comment]
We are currently considering providing a default development environment image that would help with such use case. Currently it is recommended to have a local installation and git pull the latest code (only for contributing/core development purposes, end users should use composer or ZIP download).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Working-demo-project-as-an-equivalent-for-developers/idi-p/46246).
