### ISSUE TITLE
2.0.7 : Product attributes (also names and stuff) get missing

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#5370]
I don't know if anyone encountered this too, and I'm still not sure if it has something to do with some custom code of ours but ...

Sometimes, and it seems completely at random, products get erased of all their attributes. This also includes things like name, visibility, status, etc. Prices and some other attributes are kept. I looked at all the processes that our custom code has (events, cronjobs, etc.), but none of them seem to affect the products in question. I also haven't been able to reproduce the problem myself.

Another interesting fact is that lately it seems to happen during office hours, which suggest that it happens sometimes when a client saves a product from the admin.

I've been trying to put my finger on it for days, if not weeks now, but I still can't find out where it's happening. Now the only question I have here is if anyone else encountered a problem like this as well. Perhaps with your own code, perhaps with a plugin, perhaps while developing Magento itself. I just don't know where to look anymore.

**Comment by antboiko** [comment]
Hi @kanduvisla , the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
