### ISSUE TITLE
Magento 2.1 Rest API  configurableProductOptionRepositoryV1 Post

### ISSUE THREAD

**Issue by philipburrell** [magento/magento2#5371]
This is not updating the values
I send this as the body
{"option":{"attribute_id": "140","label": "Dropdown1", "position": 0,"values": [ { "value_index": 9}, {"value_index": 10 } ],"product_id": 7}}

And it returns 9
The get method returns 
[  {    "id": 9,    "attribute_id": "140",    "label": "Dropdown1",    "position": 0,    "values": [],  
"product_id": 7  }]

See values is empty

**Comment by philipburrell** [comment]
I can confirm that this works in version 2.0.7

**Comment by choukalos** [comment]
Hi @philipburrell what version did you have the original issue in?

**Comment by philipburrell** [comment]
2.1 (it worked on 2.0.7)

**Comment by andimov** [comment]
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
