### ISSUE TITLE
Magento keeps pinging NewRelic faulty?

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#5373]
## Steps to reproduce

Installed two Magento 2.1 installations via Composer on a dev server (Apache, PHP 7.0.7)
## Actual result

The server overloads sporadically and without reason. On little to no action on the server at night, it manages to choke and overload. I've been sparring with our hostingpartner to find the cause and a possible solution, and next to obvious things like memory-limits we saw that NewRelic get's pinged like every twenty seconds. These pings are the only thing pointing to a cause in the whole server/error logs;

`xx.xxx.34.67 - - [30/Jun/2016:10:00:03 +0200] "GET / HTTP/1.0" 200 67524 "-" "NewRelicPinger/1.0 (1012445)"`

The referIP changes some of the instances. I checked the NewRelic settings on two dev-installations and both are disabled and never used. I wonder why NewRelic keeps pinging if it's disabled; maybe a bug in 2.1? Haven't noticed or thought of looking for these pings in other, earlier, 2.x installations.

**Comment by rgoncharuk** [comment]
Internal issue MAGETWO-54946

**Comment by palamar** [comment]
@Asitis 
According to New Relic [documentattion ](https://docs.newrelic.com/docs/alerts/alert-policies/downtime-alerts/availability-monitoring), this is a feature that allows monitor accessibility of a website for customers.
Do you have New Relic account configured to monitor your server?

**Comment by Asitis** [comment]
I know what New Relic is and does (I do use it for other projects), but no, as I said: "I checked the NewRelic settings on two dev-installations and both are disabled and never used. I wonder why NewRelic keeps pinging if it's disabled"

**Comment by palamar** [comment]
It's a feature of New Relic server and according to [doc](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/add-edit-monitors#monitor-type-ping), it configured on the server side. 
Magento's extension doesn't have any relation to this configuration.
You can disable pinging from New Relic settings page or configure your firewall to drop requests from IPs listed on this [page  ](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/networks)

**Comment by Asitis** [comment]
I think you don't understand me, I think. I **never** configured it, on the installations nor on the servers they are on, I **never** made a NewRelic account and never set **any** settings whatsoever **_everrrrr_** - and still it pings, out of the box on a fresh server.

I never did anything at all to configure it whatsoever.

**Comment by rgoncharuk** [comment]
According to the provided log, a NewRelic customer with identifier 1012445 configured pinger.
In our conversation with New Relic support team turned out that owner of pinged server should not confirm that. To clarify the reason why 1012445 desided to ping your server the following support issue is reported https://support.newrelic.com/tickets/200781/ 

Alex, which URL is being hosted on Magento server? The answer to this will help NewRelic corroborate solution.

**Comment by Asitis** [comment]
Well this is getting very weird then. The server in question is shop.webber.nl - it's a new VPS set up by our hosting party and never hold any configuration before..

**Comment by rgoncharuk** [comment]
According to New Relic support team, IP of shop.webber.nl is used by one more host configured for the pinger.  The issue is caused by environment configuration and is not related with Magento.
