### ISSUE TITLE
<lastmod> in sitemap is not being updated when any modification on product or category

### ISSUE THREAD

**Issue by Whaaaaat** [magento/magento2#5374]
If you do any changes on a product or category like changing the meta data or the description, then go and regenerate the sitemap from the Marketing tab, after that check the sitemap you will still find the date of creation of that product or category

**Comment by veloraven** [comment]
@Whaaaaat , thank you for your report.
Please provide description according to the template: with steps, actual result and expected result. 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
