### ISSUE TITLE
Are typos considered bugs too?

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#5375]
In case typos in function names are considered bugs then www.example.com\vendor\magento\module-catalog\Model\Product.php contains a function getFormatedPrice() on line 1130 though Formatted is written with 2 t.

**Comment by stamster** [comment]
If it works, I guess not. In any case refactor of entire code base is needed to change method name.

**Comment by orlangur** [comment]
Of course typos in method or class names are bugs, even more annoying than in comments, not so easy to fix though and not of big priority/severity.

Method cannot be just renamed though to not break backward compatibility. The new method/class with proper name should be added and mistaken one marked as `@deprecated` to be removed with major version bump.

**Comment by stamster** [comment]
Annoying - yes, but typos = bugs? If it doesn't break any functionallity I don't see how could it be defined as a bug. Nevertheless, @orlangur , good comment regarding backward compatibility and marking it @deprecated.

**Comment by orlangur** [comment]
@stamster just like typo in caption on Admin UI is not a big issue, but impairs merchant experience, typo in method or comment impairs developer experience. Ideally literacy must be enforced by some test but I'm not sure this will ever happen for M2.
