### ISSUE TITLE
Installation is incomplete. Need help

### ISSUE THREAD

**Issue by hesamy** [magento/magento2#5378]
Hello,
I'm completely new to coding and my boss has asked me to affiliate myself with Magento for future work. I was installing Magento when it stopped at 51% and told me to check the error log before restarting. I have no idea what the log is saying so I was hoping someone could help me out.
Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':

Module 'Magento_Bundle':

Module 'Magento_Quote':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_SampleData':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Downloadable':

Module 'Magento_CatalogSearch':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_User':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_CatalogInventory':

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_Sales':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Vault':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Weee':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_CatalogSampleData':

Module 'Magento_ProductVideo':

Module 'Magento_Captcha':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_BundleSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_Integration':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_SalesSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':

Module 'Magento_WishlistSampleData':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_Quote':
Running schema recurring...

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_SampleData':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Downloadable':

Module 'Magento_CatalogSearch':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_User':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_Sales':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Vault':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_CatalogSampleData':

Module 'Magento_ProductVideo':

Module 'Magento_Captcha':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_BundleSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_SalesSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_WishlistSampleData':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [eav] => 1 [customer_notification] => 1 [full_page] => 1 [config_integration] => 1 [config_integration_api] => 1 [translate] => 1 [config_webservice] => 1 ) 

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':
Installing data... 
[ERROR] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array) #5 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(452): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`cu...', Array) #6 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(507): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array) #7 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`cu...', Array) #8 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(1781): Zend_Db_Adapter_Abstract->insert('customer_group', Array) #9 C:\Xamp\htdocs\Magento\vendor\magento\module-customer\Setup\InstallData.php(50): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array) #10 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(843): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #11 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(795): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #12 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #13 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(344): call_user_func_array(Array, Array) #14 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #15 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #17 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #18 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #20 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #22 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #23 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 C:\Xamp\htdocs\Magento\setup\index.php(31): Zend\Mvc\Application->run() #26 {main} Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `customer_group` (`customer_group_id`, `customer_group_code`, `tax_class_id`) VALUES (?, ?, ?) in C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array) #4 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(452): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`cu...', Array) #5 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(507): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array) #6 C:\Xamp\htdocs\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`cu...', Array) #7 C:\Xamp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(1781): Zend_Db_Adapter_Abstract->insert('customer_group', Array) #8 C:\Xamp\htdocs\Magento\vendor\magento\module-customer\Setup\InstallData.php(50): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array) #9 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(843): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #10 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(795): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #11 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #12 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(344): call_user_func_array(Array, Array) #13 C:\Xamp\htdocs\Magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #14 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #16 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #17 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #21 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #22 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 C:\Xamp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 C:\Xamp\htdocs\Magento\setup\index.php(31): Zend\Mvc\Application->run() #25 {main}

**Comment by orlangur** [comment]
Did you try to install over clean database? Looks like something is present in `customer_group` table.

**Comment by hesamy** [comment]
@orlangur I didn't really touch anything. I just downloaded the file and followed the steps. Is there a way for me to clear that table?

**Comment by mhabou** [comment]
@hesamy 

Delete the database,& recreate it & launch the setup again
Don't use database table prefix

**Comment by hesamy** [comment]
@Dayssam  I did that but when i typed localhost/magento into my browser it just goes to a blank page that just writes "An error has happened during application run. See exception log for details.". I'm guessing I shouldnt have left the installation page?

**Comment by mhabou** [comment]
@hesamy you have to finish the installation then go to magento home page

**Comment by hesamy** [comment]
@Dayssam  the issue is that I can't access the installation page to complete it. localhost/magento takes me to a blank page that says "An error has happened during application run. See exception log for details.".

**Comment by mhabou** [comment]
delete the folder of magento code source then download it again or paste it in the server folder if you had it already

**Comment by orlangur** [comment]
> localhost/magento takes me to a blank page that says "An error has happened during application run. See exception log for details.".

Check `/var/log` and `/var/report` for errors.

**Comment by Ctucker9233** [comment]
@hesamy  You should be able to finish the installation with a Command Line Interface (CLI). Like Putty, for example. I don't know if you found a solution yet, but if you need the steps to do this, just ask.

**Comment by wert2all** [comment]
@hesamy Did You try to clean cache?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
