### ISSUE TITLE
view.xsd image type restrictions should not be there

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#5379]
**Description**  
There is a validation in [view.xsd](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Config/etc/view.xsd#L69)  that prohibits users from creating configurations for newly added media image attributes.  

**Steps to reproduce**
1. Create a module that adds a new media image to the product.
2. Try to set in that module in the `etc/view.xml` the default settings for that image

**Expected result**
I should be able to set width and height as I want with this markup

```
        <image id="category_page_list" type="my_image_attribute_code_here">
            <width>240</width>
            <height>300</height>
        </image>
```

**Actual result**
I get an xml validation error saying that the `type` attribute for my image tag is not valid.

**Comment by gordonknoppe** [comment]
Internal issue MAGETWO-55279

**Comment by MomotenkoNatalia** [comment]
@tzyganu  Internal ticket MAGETWO-55279 is closed and delivered to mainline. Please let us know if you still have an issue

**Comment by jzahedieh** [comment]
@MomotenkoNatalia I can see the fix is in the develop branch, do you have any timeline for when this will be included in an release?

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Config/etc/view.xsd#L61
