### ISSUE TITLE
When creating / updating a link the mediabrowser opens

### ISSUE THREAD

**Issue by 11mb** [magento/magento2#5380]
## Steps to reproduce
1. Install Magento 2.1
2. Login to admin
3. Goto Content >> Pages 
4. Click Edit button for homepage
5. Edit content
6. Select text and click insert link
7. Click browse
## Expected result
1. A list of links to cms pages, categories and products
## Actual result
1. The mediabrowser opens

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/When-creating-updating-a-link-the-mediabrowser-opens/idi-p/45268).

**Comment by 11mb** [comment]
Thanks for your answer.. So how can I establish the difference between an improvement and a bug? Clicking on an icon which is obvious intended to include a link and not for including a media item does seem as a bug to me. Removing that icon would be a solution..
