### ISSUE TITLE
Cronjobs defined in group "default" still not running properly

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5382]
Original issue #2672 was closed so I'm opening a new one to raise awareness. This issue is still present using version 2.0.7

In fact not only custom cronjobs are affected. E.g. [magento_newrelicreporting_cron](https://github.com/magento/magento2/blob/2.0/app/code/Magento/NewRelicReporting/etc/crontab.xml#L9-L13) which should run every 2 minutes acts the same.

**Comment by atvvarna** [comment]
Actually in 2.1 it is still the same.

**Comment by veloraven** [comment]
@werdlv thank you for your report.
Please provide description according to the template: with steps, actual result and expected result. 
It will help other users to find this issue in case when they have the same one.

**Comment by jsakars** [comment]
@veloraven all the steps are already given in referenced issue which was closed even though it hasn't been fixed

**Comment by veloraven** [comment]
@werdlv please describe steps you do as well as actual result and expected result.
As I can see there were unanswered comment from @eddielau in that issue.
Thus if you have exactly the same case most likely you will get the same comment.
Additionally it's hard to understand from the original case if it was description of a bug or a question. 
So we need clear steps, expected result and actual result described to understand what exact problem do you have and if it is a bug.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
