### ISSUE TITLE
timestamp() of \Magento\Framework\Stdlib\DateTime\DateTime is not localized

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#5383]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Call method timestamp() (without parameter) of \Magento\Framework\Stdlib\DateTime\DateTime which says it will give back a localized timestamp.
## Expected result
1. A localized timestamp.
## Actual result
1. A GMT timestamp.

The problem is the line in https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L176. 

If you change it to something like this, it works:

``` php
return (new \DateTime(date('Y-m-d H:i', $date), new \DateTimeZone($timezone)));
```

**Comment by demidov-i-a** [comment]
It seems the problem at https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/DateTime.php#L141

Must be 

$timestamp = $date->getTimestamp() + $date->getOffset();

instead 

$timestamp = $date->getTimestamp();

Magento 1 code
$timestamp = $date->get(Zend_Date::TIMESTAMP) + $date->get(Zend_Date::TIMEZONE_SECS);

**Comment by sidealice** [comment]
Should this added to Unit Test with a test case?

**Comment by magento-engcom-team** [comment]
@bh-ref, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Comment by magento-engcom-team** [comment]
This issue was reopened without clear comment. Please provide reasoning and reopen again, if needed.

**Comment by arjundhi** [comment]
> It seems the problem at https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/DateTime.php#L141
> 
> Must be
> 
> $timestamp = $date->getTimestamp() + $date->getOffset();
> 
> instead
> 
> $timestamp = $date->getTimestamp();
> 
> Magento 1 code
> $timestamp = $date->get(Zend_Date::TIMESTAMP) + $date->get(Zend_Date::TIMEZONE_SECS);

Hi,
After doing this fix in DateTime.php ...we are getting correct date value but now in admin grid date value are showing incorrect -6 hours from the created_at date. Any idea on this?
