### ISSUE TITLE
Typo in Developer Documentation

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5386]
I think that there is a small mistake in Developer Documentation.
## Steps to reproduce
1. Go to http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html
2. Find "Tasks for one Magento file system owner" and reveal "Click to show/hide content"
3. Find "Make files and directories writable:"

> Make files and directories writable:
> 
> To make files and directories writable so you can update components and upgrade the Magento software:
> 
> Log in to your Magento server.
> Change to your Magento installation directory.
> Enter the following commands:
> chmod -R u+x .
## Expected result
1. `chmod -R u+w .`
## Actual result
1. `chmod -R u+x .`

**Comment by orlangur** [comment]
Thanks for the report, @RG-1! It should be reported in https://github.com/magento/devdocs I believe, or even as a pull request with changed https://github.com/magento/devdocs/blob/develop/guides/v2.0/config-guide/prod/prod_file-sys-perms.md file.

**Comment by RG-1** [comment]
Thank you @orlangur , I moved it.
Sorry for creating an issue in the wrong place.
