### ISSUE TITLE
Sitemap.xml file not generating

### ISSUE THREAD

**Issue by navarr** [magento/magento2#5387]
## Steps to reproduce
1. Create new directory for housing Magento 2.1 installation
2. Install Magento 2.1 through Composer Create-Project and bin/magento setup:install (setup permissions as written in documentation)
3. Setup bin/magento cron:run to run every minute
4. Login to the admin panel and, in General settings, set the timezone to your local timezone
5. In Catalog > XML Sitemap, enable the sitemap, set it to "start time" in 5 minutes, frequency daily, specify an error email recipient, and enable submission to Robots.txt
6. Flush Cache
7. Wait until 5 minutes after scheduled start time

In my testing It was 12:24, I set the generation to start at 12:30, and checked for the file at 12:35 and 12:40
## Expected result
1. Sitemap.xml file is generated in pub/ (or in the home directory, or pub/static/ or anywhere really)
## Actual result
1. No sitemap.xml file is available in the home directory or the pub directory, no email is sent

I will happily admit it's entirely possible I'm doing this wrong - but I have no idea how to even start figuring out what that is.

**Comment by antboiko** [comment]
Hi @navarr , did you create sitemap.xml first using Add Sitemap in Marketing > SEO & Search > Site Map? 

Thanks,
Anton.

**Comment by navarr** [comment]
Nope, that's my problem.  Thank you.

**Comment by priti-rathee** [comment]
I also followed the same steps 
1. Setup sitmap from catalog>Xml Sitemap.
2. Generated sitemap at first.
3. Ran Cron using sudo bin/magetno cron:run command.
4. Flushed cache.
5. Created a product for testing.
refreshed page https://xxxxx.com/sitemap.xml. Found no change the file
Expected Result: Product link should be seen in the xml file.

Please refer the screen shot of the setting in the below link and help me to find where  have gone wrong.
https://screenshots.firefox.com/GPcxMsKNPWXol7Ma/hindustansupply.com

**Comment by Ctucker9233** [comment]
@priti-rathee Try this. Put Magento 2 into production mode and then rerun cron.
