### ISSUE TITLE
M2.1 Excessive processes every day

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#5388]
Every day at around 4am I am receiving a warning message from my server "Excessive processes running under extende"

User:extende PID:24285 PPID:24266 Run Time:255(secs) Memory:4300(kb) exe:/usr/local/cpanel/bin/jailshell cmd:jailshell (extende) [init] hell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24290 PPID:24285 Run Time:254(secs) Memory:312716(kb) exe:/home/virtfs/extende/usr/local/bin/php cmd:/usr/local/bin/php /home/extende/public_html/bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1
User:extende PID:24337 PPID:24327 Run Time:195(secs) Memory:4300(kb) exe:/usr/local/cpanel/bin/jailshell cmd:jailshell (extende) [init] hell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24343 PPID:24337 Run Time:194(secs) Memory:312716(kb) exe:/home/virtfs/extende/usr/local/bin/php cmd:/usr/local/bin/php /home/extende/public_html/bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1
User:extende PID:24356 PPID:24352 Run Time:136(secs) Memory:4300(kb) exe:/usr/local/cpanel/bin/jailshell cmd:jailshell (extende) [init] hell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24368 PPID:24356 Run Time:134(secs) Memory:312716(kb) exe:/home/virtfs/extende/usr/local/bin/php cmd:/usr/local/bin/php /home/extende/public_html/bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1
User:extende PID:24465 PPID:24388 Run Time:40(secs) Memory:4300(kb) exe:/usr/local/cpanel/bin/jailshell cmd:jailshell (extende) [init] hell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24466 PPID:24465 Run Time:40(secs) Memory:106068(kb) exe:/home/virtfs/extende/bin/bash cmd:/usr/local/cpanel/bin/jailshell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24467 PPID:24466 Run Time:40(secs) Memory:312988(kb) exe:/home/virtfs/extende/usr/local/bin/php cmd:/usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run
User:extende PID:24488 PPID:24482 Run Time:15(secs) Memory:4300(kb) exe:/usr/local/cpanel/bin/jailshell cmd:jailshell (extende) [init] hell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24489 PPID:24488 Run Time:15(secs) Memory:106068(kb) exe:/home/virtfs/extende/bin/bash cmd:/usr/local/cpanel/bin/jailshell -c /usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run > /dev/null
User:extende PID:24490 PPID:24489 Run Time:15(secs) Memory:312988(kb) exe:/home/virtfs/extende/usr/local/bin/php cmd:/usr/local/bin/php -c /usr/local/lib/php.ini /home/extende/public_html/bin/magento cron:run

**Comment by andimov** [comment]
@bondimedical3 
Thank you for reporting.
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
