### ISSUE TITLE
If current connection is https, all links are under https. There is no way to get out.

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#5389]
## Steps to reproduce
1. Install Magento EE 2.1
2. Setup https and use secure URLs on storefront
3. Click shopping cart or any https connection
## Expected result
1. The secure connection links works fine and should don't have https connection for menu items, product/caterory links,...
## Actual result
1. All links are under https and there is no way to get out including menu items, product/category links...

I'm running Ubuntu server, PHP 7.0.7-4+deb.sury.org~xenial+1 (cli) ( NTS ) and mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

Some attached screens:
![2016-07-01_9-14-14](https://cloud.githubusercontent.com/assets/1607243/16510038/e90a12de-3f6c-11e6-9ba8-3a4d035f265c.jpg)
![2016-07-01_9-24-41](https://cloud.githubusercontent.com/assets/1607243/16510176/0289af3e-3f6e-11e6-87ed-cf609917ba97.jpg)

**Comment by tobias-forkel** [comment]
If **Secure URLs** are enabled, Magento will use it for menu, category, product links, form actions (post, get), ajax requests etc. to prevent [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content?hl=en). What is the technical reason to go back from **https** to **http**?

**Comment by phuc128t** [comment]
I think you are not correct. Mixed content only an issue with resources (images, css, js,...), ajax requests, form action,.. not link. When "use secure URLs on storefront" is enabled, it should only affect to some pages like login, register, cart, checkout, ... the other pages like menu, category, product links,... still should be http. I meant when go to https from http page, it should have a way to go back to http. Now there is no way. 
You have to change the url on browser to go back to http. This works fine with magento 2.0.7

**Comment by phuc128t** [comment]
I think the previous image is not clear. Here is another one.
![2016-07-01_13-45-38](https://cloud.githubusercontent.com/assets/1607243/16513884/691d5f88-3f92-11e6-82ce-b69c38919780.jpg)

**Comment by stamster** [comment]
If you enable HTTPS on storefront, it is expected to be all HTTPS links, I don't see an issue there.

**Comment by pboisvert** [comment]
This is not an issue. If you select to use secure urls on storefront then all urls will use HTTPS--not just cart, checkout, or login pages. Google has already signaled they will use all HTTPS as a ranking signal and this is the setting that allows for such configuration. We will make sure this is clear in documentation that this is the expected behavior for the setting. Closing issue.

**Comment by phuc128t** [comment]
Ok, this is a different from previous versions (from magento 2.0.7 and magento 1.x).
