### ISSUE TITLE
Magento 2 EE Cybersource Module Bug in "Declined Payment"

### ISSUE THREAD

**Issue by rameshpushparaj** [magento/magento2#5390]
## Steps to reproduce
1. Install Magento 2.0.7 Enterprise Edition
2. Configure the Cybersource payment credentials (sandbox credentials)
3. Do a Cybersource Test Credit Card Payment 
## Expected result
1.  For Positive scenario once the order is placed the success page with Thank you message will be displayed
2. For Failure Scenario (Say the Credit Card is declined) the error message has to be displayed stating the actual reason for failure.
## Actual result
1. Thank you page appears for successful payment
2.  For failed payment the below error message is displayed.

{"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5773e3728984b"}

Error Log:-

report.CRITICAL: Exception: Report ID: webapi-5773e3728984b; Message: Notice: Undefined index: reasonCode in /src/vendor/magento/module-cybersourc
e/Gateway/Validator/DecisionValidator.php on line 74 in /src/vendor/magento/framework/Webapi/ErrorProcessor.php:194

It Seems the reasonCode is not there in cybersource response.

![cybersourcesalog](https://cloud.githubusercontent.com/assets/19649012/16512522/0db57724-3f7a-11e6-85f8-38dd51df6e0c.png)

![cybersourcemodulecode](https://cloud.githubusercontent.com/assets/19649012/16512530/22c3fba4-3f7a-11e6-8387-10986345abc2.png)
![cybersourcemodulecodeerrorhandling](https://cloud.githubusercontent.com/assets/19649012/16512531/22ca6f84-3f7a-11e6-95ed-d36bac37ba27.png)

**Comment by YevSent** [comment]
The public Github is only for CE version of Magento. To solve your problem, please, create a ticket via [EE support](https://magento.com/support/enterprise-edition), thanks, for your reporting.

**Comment by nagrgk** [comment]
Hi guys,

I have built complete full functional cybersourse module from scratch, if you are planning to buy or looking for alternative to current cybersourse, please contact me. Cybersourse has all basic functionality including save card feature. Delete, add card functionality also been implemented from customer account section.

You can see my website cosinefreelance.com or contact me on nagrgk@gmail.com or call me on +65 86509548
