### ISSUE TITLE
Magento 2.1 Installation - Missing resources

### ISSUE THREAD

**Issue by juuce** [magento/magento2#5392]
NOTE: Install on xampp 1.8.2, PHP 5.6.15, (MySQL) Server type: MariaDB, Server version: 10.1.9-MariaDB
Possible issue with Windows...?
## Steps to reproduce
1. Install Magento from 2.1 from zip file in apache virtual host environment (magento-21.localtest.me)
2. Navigate to admin login
3. notice 404 on resources (images/css/js) (see below)
4. Login
5. Notice 404 on resources (images/css/js)
## Expected result

Show images and addtional resources
## Actual result

Missing Resources

Failed to load resource: the server responded with a status of 404 (Not Found)
e.g. http://magento-21.localtest.me/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js

The files are not in the source filesystem...? This has happened on 2 clean installs.
a) magento.localtest.me/magento-2.1/
b) magento-21.localtest.me 

![magenotlogin](https://cloud.githubusercontent.com/assets/8197867/16512968/eb8f109a-3fa3-11e6-98dc-2c44d23bb7c3.png)

![magenotadmin](https://cloud.githubusercontent.com/assets/8197867/16513032/7a58bba0-3fa4-11e6-967a-2d5bffe1f58e.png)

**Comment by buskamuza** [comment]
@juuce , please, ensure you have rewrites enabled (see http://devdocs.magento.com/guides/v2.1/install-gde/prereq/apache.html#apache-help-rewrite)

**Comment by vivek201** [comment]
You can get around this by using the command `php bin/magento setup:static-content:deploy`. The frontend and backend will be working after that. But there seems to be issue while changing the theme.

**Comment by oserediuk** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by shyandsy** [comment]
@buskamuza 
my installation running on nginx, and I copied the nginx.sample configuration file to nginx vhost

i also run the commend successfully: php bin/magento setup:static-content:deploy

but I also suffer this problem

**Comment by buskamuza** [comment]
@shyandsy , do you have the same resources missing or different ones?

**Comment by shyandsy** [comment]
@buskamuza yes  i do, bueaty girl

**Comment by lgoudriaan** [comment]
You need to run xampp as administrator

**Comment by juuce** [comment]
Thanks for your replies. I believe the command
`php bin/magento setup:static-content:deploy`
is the best answer for this.

**Comment by lojasmarques** [comment]
I can not fix this error with the command line quoted above, it appears "Could not open input file: bin / magento" if anyone can help me, contact me by email --- suporte@lojasmarques.com

**Comment by lojasmarques** [comment]
I can not fix this same error with the command line quoted above, it appears "Could not open input file: bin / magento" if anyone can help me, contact me:
by email --- suporte@lojasmarques.com ---
by WhatsApp - (53)981426029 ---

**Comment by buskamuza** [comment]
@lojasmarques ,
1. do you have such file in Magento folder?
2. is it executable? If not, please give it executable rights `chmod +x bin/magento`
