### ISSUE TITLE
Client less compilation not working

### ISSUE THREAD

**Issue by Ankitase35** [magento/magento2#5393]
I am trying to set workflow to Client less compilation mode .After that when I execute static content deploy command, I get errors for syles-m.css,stylse-l.css on fronteend & styles.css & styles-old.css in backend.
Can anyone help me with this?

**Comment by paales** [comment]
@Bakhtawar7 Please note that GitHub is not a support forum to ask for help. If you are actually running into bugs you can report them here, but for help, ask the question here: http://magento.stackexchange.com/

**Comment by Ankitase35** [comment]
Hello Paul,
              I already raised this question on stackexchange but I didn't
get any help so I asked the question on github.

On Sun, Jul 3, 2016 at 7:25 PM, Paul Hachmang notifications@github.com
wrote:

> @Bakhtawar7 https://github.com/Bakhtawar7 Please note that GitHub is
> not a support forum to ask for help. If you are actually running into bugs
> you can report them here, but for help, ask the question here:
> http://magento.stackexchange.com/
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/magento/magento2/issues/5393#issuecomment-230154671,
> or mute the thread
> https://github.com/notifications/unsubscribe/AMlSVHz-kKM3v_22b8V0bK3HGE1GOvUUks5qR79ogaJpZM4JC3v1
> .

## 

Regards,
Bakhtawar Khan.

**Comment by paales** [comment]
@Bakhtawar7 If you'd like to get help. Please post your errors and detailed steps otherwise no one can help.

**Comment by Ankitase35** [comment]
I have followed all the steps from this tutorial:
http://www.thienphucvx.com/magento-2-frontend-development/

**Comment by eug123** [comment]
@Bakhtawar7 
You don't need to run `setup:static-content:deploy` command in developer or default modes after cleaning the cache and contents of the `pub/static/` folder. All static resources for the particular page will be published automatically as [symlinks](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html#css_debug_client).

What exact errors do you get?

**Comment by developer-lindner** [comment]
@eug123 Got also trouble deploying static content. Will be the same issue... seems like another bug introduced with 2.1.0 release.

```
[Magento\Framework\View\Asset\ContentProcessorException]     
  Compilation from source:                                     
  frontend/Test/custom/de_DE/css/bootstrap/mixins/alerts.less  
  Compilation from source:                                     
  frontend/Test/custom/de_DE/css/bootstrap/mixins/alerts.less
```

grunt exec:theme_name
grunt less:theme_name

"works" although i don't see the styles applied in frontend.
If you're using a copy of the luma theme you ll have to apply this as well:
http://magento.stackexchange.com/questions/107375/lib-popup-button-close-icon-is-undefined

2.1.0 release is a really bad joke.

Even the grunt deploy is bugged. It should take the locale setting from themes.js but instead defaults to en_US. or do i miss here something?

Edit: Interesting... somehow it works when first static-content:deploy was executed and later grunt  exec + grunt less:theme_name

**Comment by Ankitase35** [comment]
Hello,
     I followed this link :
http://www.thienphucvx.com/magento-2-frontend-development/

& I also faced same design issues of admin panel so I had to run deploy
command as mentioned in the tutorial but that caused missing of
styles-m.less & other files.

Even without executing deploy command, my design changes are never
reflected.

On Wed, Jul 13, 2016 at 7:02 PM, Evgeniy Kolesov notifications@github.com
wrote:

> @Bakhtawar7 https://github.com/Bakhtawar7
> You don't need to run setup:static-content:deploy command in developer or
> default modes after cleaning the cache and contents of the pub/static/
> folder. All static resources for the particular page will be published
> automatically as symlinks
> http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html#css_debug_client
> .
> 
> What exact errors do you get?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/magento/magento2/issues/5393#issuecomment-232355615,
> or mute the thread
> https://github.com/notifications/unsubscribe/AMlSVOEKkCdkFJ_zNQT1r-QNtBnAG4fbks5qVOj4gaJpZM4JC3v1
> .

## 

Regards,
Bakhtawar Khan.

**Comment by tkacheva** [comment]
@Bakhtawar7 we can help only if have all the details on the issue you are facing. Please provide information according to the guideline https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by andimov** [comment]
@Bakhtawar7 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
