### ISSUE TITLE
Product save page in admin does not scroll down to attribute containing wrong data

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#5394]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Adding products programatically
3. Trying to edit added product and save it.
4. One of required attribute is null
## Expected result
1. If I try to save product with required attribute Magento should abort it and point out which attribute is empty.
2. If it is not visible on menu it should automatically scroll down to its group.
## Actual result
1. Button 'save' freezes out.
2. Attribute is pointed out with red triangle but if its group is out of current scope of view Magento doesn't scroll down to its group. 
3. I have to scroll down in search of the group and attribute with error.

So it's quite uncomfortable and not intuituive if there is an error in very low sort order group becauce button 'save' just freeze and in the begining you don't know why it's not saving results.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-save-page-in-admin-does-not-scroll-down-to-attribute/idi-p/45267).
