### ISSUE TITLE
Translations not working in product view

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5396]
## Steps to reproduce
1. Install Magento 2.0.7
2. Have some translations for corresponding store view - Latvian in this case
## Expected result
1. Translations are working properly after adding product to the cart from **category** view
2. Translations are working properly after adding product to the cart from **product** view
## Actual result
1. Translations are working properly after adding product to the cart from **category** view - http://screencast.com/t/YSamz0qMaDm
2. Default translations for button are show after adding product to the cart from **product** view - http://screencast.com/t/E0jTpJPnlyR

**Comment by antboiko** [comment]
Hi @werdlv , this has been fixed in 2.1. The fix will be also available in one of the future patches.

https://github.com/magento/magento2/issues/4181

Best,
Anton.
