### ISSUE TITLE
Can Not View / Edit product added to the shopping cart

### ISSUE THREAD

**Issue by didineedthis** [magento/magento2#5397]
## Steps to reproduce
1. Install Magento 2.0.7 I upgrade to 2.1.0
2. Add Products to the cart.
3. Click the View/Edit product added to the shopping cart.
## Expected result

1.View/Edit product added to the shopping cart
![screenshot 20](https://cloud.githubusercontent.com/assets/10882960/16516383/afdb0240-3f6f-11e6-9909-47bcc5a85991.png)
## Actual result

1.Summary box is empty
![screenshot 21](https://cloud.githubusercontent.com/assets/10882960/16516378/ab55ad88-3f6f-11e6-9fdb-705c077c3f11.png)

**Comment by pboisvert** [comment]
Not an answer to this specific issue but have you tried with a fresh install and if so do you see the same?

**Comment by didineedthis** [comment]
Hi,
I have just done a fresh install on local and imported my categories and products and all seems ok so far. i will upload the site to my server tomorrow after i do some more testing . i will update this thread with my findings but it looks like it maybe a corrupt upgrade from 2.0.7 to 2.1

regards

**Comment by pboisvert** [comment]
thanks for checking and do let us know if same or different results as this greatly narrows scope of the issue.

**Comment by didineedthis** [comment]
deleted comment wrong post

**Comment by didineedthis** [comment]
Problem resolved with fresh install. More than likely upgrade error !
Thanks for your imput, appreciated.
Regards

**Comment by Deepthi57** [comment]
![2016-07-06_1429](https://cloud.githubusercontent.com/assets/17591809/16612729/12e51adc-4386-11e6-889e-7dc6a8c69620.png)
Hi, 
I encounter the same problem where the view and edit cart page is empty. I have done fresh installation of the version 2.1.0. Kindly provide me with an update on the same
