### ISSUE TITLE
Transparency of .png image gone

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#5401]
Similar issue to #2312 
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add new attribute with 'wysiwyg_enabled' and 'is_html_allowed_on_front' set to true
3. Add .png image with transparent background.
## Expected result
1. Image shows in front with background same as in original (transparent)
## Actual result
1. Image shows with white background

**Comment by pboisvert** [comment]
Can you provide version where observed? Also providing the png image may also help with troubleshooting.

**Comment by eug123** [comment]
@Bartlomiejsz,
While related ticket (MAGETWO-45264) is still not resolved. Please, try to set 
`Use Static URLs for Media Content in WYSIWYG for Catalog` value to `yes` (_Stores->Configuration->General->Content Management->WYSIWYG Options_) and update your attribute content.

Thank you

**Comment by Bartlomiejsz** [comment]
@pboisvert observed on 2.0.7. This bug isn't connected with one image, all transparent .png files loaded this way are showing exactly same.

@eug123 thank you for answer, hope you will be able to fix it soon, static url option is something I wanted to avoid.

**Comment by tkacheva** [comment]
Issue MAGETWO-45264

**Comment by okorshenko** [comment]
Closing this issue. PR https://github.com/magento/magento2ce/pull/875 was delivered to develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69238
