### ISSUE TITLE
Rest Api - GET /V1/carts/mine/items not giving product row total and image in response

### ISSUE THREAD

**Issue by qwerty7869** [magento/magento2#5404]
## Steps to reproduce
1. Add products in cart 
2. Hit api GET /V1/carts/mine/items
3. Response will be

[
  {
    "item_id": 244,
    "sku": "24-WB04",
    "qty": 2,
    "name": "Push It Messenger Bag",
    "price": 45,
    "product_type": "simple",
    "quote_id": "202"
  },
  {
    "item_id": 245,
    "sku": "MSH03-33-Black",
    "qty": 1,
    "name": "Meteor Workout Short",
    "price": 32.5,
    "product_type": "configurable",
    "quote_id": "202",
    "product_option": {
      "extension_attributes": {
        "configurable_item_options": [
          {
            "option_id": "90",
            "option_value": 49
          },
          {
            "option_id": "138",
            "option_value": 177
          }
        ]
      }
    }
  }
]
## Expected result

Response should have product row total and image which is the basic functionality required in all the sites.

**Comment by mbrinton01** [comment]
@qwerty7869 totals can be found using other calls such as `GET /V1/carts/{cartId}/totals`.  `GET /V1/carts/mine/items` does not return images.  Are you making a feature request for images in this call?

**Comment by qwerty7869** [comment]
@mbrinton01 Thanks for the reply. 
I checked cart totals api and getting itemwise row total in response so that is resolved. But require images for the cart page and I think this is not a fetaure but a basic functionality which will be required in all the sites.

**Comment by oserediuk** [comment]
@qwerty7869 do you confirm that you want to report future request?

**Comment by mbrinton01** [comment]
@qwerty7869 another question to understand your request.  It is possible to get images now for a product, but are you requesting this be possible from a `carts` API call?

**Comment by qwerty7869** [comment]
@oserediuk Yes I confirm to report it as a future request.

**Comment by qwerty7869** [comment]
@mbrinton01 Yes requesting that will it be possible from Cart Api call. If it is possible than please help me how to add that functionality in my project.

**Comment by mackelito** [comment]
+1

**Comment by mackelito** [comment]
is there any update on this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-Api-GET-V1-carts-mine-items-not-giving-product-row-total/idi-p/44706).

**Comment by eugenbg** [comment]
this is so obvious that you need the image for a cart item in the api, you people are amazing

**Comment by nagrgkgc** [comment]
@eugenbg 
Your statements are 100% correct. these people are amazing.

they want you to search product with ID and get IMAGE. World has gone so much advanced but these API's are so old style.

**Comment by babaxdz** [comment]
try this
/rest/V1/carts/mine/items
