### ISSUE TITLE
Query insert on duplicate update won't work

### ISSUE THREAD

**Issue by bordeo** [magento/magento2#5406]
After update magento to 2.1 and making a fresh db install, i try to update and create product programmatically.
All query "insert on duplicate update" remain stuck for certain time with no error.
An example is in Magento\Eav\Model\Entity\AbstractEntity on method _processAttributeValues.

For create product i'm using productRepository
`
$product = $this->_productFactory->create();
$product->setData('data'.$value);
$this->productRepository->save($product);
`

I try with mysql server 5.7 on osx and ubuntu systems.

**Comment by andimov** [comment]
@bordeo 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
