### ISSUE TITLE
Database privilege issues for System Upgrade Readiness Check 

### ISSUE THREAD

**Issue by emoruzzi** [magento/magento2#5410]
## Steps to reproduce

Using Version 2.0.0 (seems to be the same for 2.1) . In the admin panel, navigate to  System > Tools > Web Setup Wizard > System Upgrade > Choose any CE newer version > Next > Start Readiness Check. Continue (Next) to Readiness Check
## Expected result

Assuming everything is setup properly, all passes.
## Actual result

Everything passes except for "Check Cron Scripts". I'm getting the following error on my configuration.

```
Check Cron Scripts
Cron script readiness check failed. Hide detail

Error from Setup Application Cron Script:
Database user does not have enough privileges. Please make sure SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER privileges are granted to table 'magento2'.

For additional assistance, see cron scripts help.
```
## Additional Information

The server is running Percona Server 5.6.27-76.0. When Magento 2 checks for user/database privileges it's looking up the 'USER_PRIVILEGES' table which returns "USAGE" resulting in a failure. On my configuration, the user has all the privileges required for that specific database but not globally, which seems to be why this is failing.

When Magento does the privileges check, it sees:

```
mysql> SELECT * FROM information_schema.USER_PRIVILEGES;
+---------------------+---------------+----------------+--------------+
| GRANTEE             | TABLE_CATALOG | PRIVILEGE_TYPE | IS_GRANTABLE |
+---------------------+---------------+----------------+--------------+
| 'mag_user'@'%' | def           | USAGE          | NO           |
+---------------------+---------------+----------------+--------------+
1 row in set (0.00 sec)
```

The user privileges for the database meet requirements

```
mysql> SHOW GRANTS FOR CURRENT_USER();
+---------------------------------------------------------------------------+
| Grants for mag_user@%                                                |
+---------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'mag_user'@'%' IDENTIFIED BY PASSWORD <secret> |
| GRANT ALL PRIVILEGES ON `magento2`.* TO 'mag_user'@'%'      |
+---------------------------------------------------------------------------+
3 rows in set (0.00 sec)

mysql> use information_schema;
mysql> SELECT * FROM db WHERE User = 'mag_user' AND Db = 'magento2'\G
*************************** 1. row ***************************
                 Host: %
                   Db: magento2
                 User: mag_user
          Select_priv: Y
          Insert_priv: Y
          Update_priv: Y
          Delete_priv: Y
          Create_priv: Y
            Drop_priv: Y
           Grant_priv: N
      References_priv: Y
           Index_priv: Y
           Alter_priv: Y
Create_tmp_table_priv: Y
     Lock_tables_priv: Y
     Create_view_priv: Y
       Show_view_priv: Y
  Create_routine_priv: Y
   Alter_routine_priv: Y
         Execute_priv: Y
           Event_priv: Y
         Trigger_priv: Y
1 row in set (0.00 sec)
```

For security concerns, we'd like to minimize the amount of privileges provided. The current checking method for Magento 2 essentially requires 'root' privileges; is that necessary? What are my options to work around this issue without providing full access to the database?

**Comment by oshmyheliuk** [comment]
Hi @emoruzzi 
Here is the list of required privileges.

```
$requiredPrivileges = [
            'SELECT',
            'INSERT',
            'UPDATE',
            'DELETE',
            'CREATE',
            'DROP',
            'REFERENCES',
            'INDEX',
            'ALTER',
            'CREATE TEMPORARY TABLES',
            'LOCK TABLES',
            'EXECUTE',
            'CREATE VIEW',
            'SHOW VIEW',
            'CREATE ROUTINE',
            'ALTER ROUTINE',
            'EVENT',
            'TRIGGER'
        ];
```

Please run next query to check what privileges have user on concrete schema:
`SELECT PRIVILEGE_TYPE FROM information_schema.SCHEMA_PRIVILEGES WHERE 'magento2' LIKE TABLE_SCHEMA AND GRANTEE = 'mag_user@%';`

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
