### ISSUE TITLE
Product grid not loading in admin, only error about ID already existing (2.1.0)

### ISSUE THREAD

**Issue by samuellinde** [magento/magento2#5412]
## Steps to reproduce
1. Export products as csv (around 1500 products).
2. Re-import products, no major changes.
3. Load product catalog in admin.
## Expected result
1. Should display the product grid as usual.
## Actual result
1. No product grid loaded, only the following error message `Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1487" already exists.`
2. <img width="1496" alt="screen shot on 2016-07-01 at 23-48-14" src="https://cloud.githubusercontent.com/assets/57992/16535263/60011490-3fe6-11e6-900f-0603e02f228e.png">

**Comment by kristjan-h** [comment]
See #5418 for a temporary fix.

**Comment by samuellinde** [comment]
@OnTapKristjan Yep, that did the trick.

**Comment by afavata** [comment]
I did the same... Exported a range of items and reimported them. Now  I cannot browse item catalog grid.
File in report says:
a:4:{i:0;s:87:"Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "567" already exists.";i:1;s:6983:"#0..... etc.

Thanks

**Comment by afavata** [comment]
Ok I deleted the 10 database rows that were duplicated during the importing process. Now catalog grid shows all items without any issue.

**Comment by shiftedreality** [comment]
Hi @samuellinde 

Thank you for reporting.
This issue will be fixed in scope of https://github.com/magento/magento2/issues/5418

Closed
