### ISSUE TITLE
Tax calculated wrongly when Atomatic group assignment of users is used

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#5415]
Hi,

There seems to be a problem with Magento when the utomatic Assignemnt to Groups is enabled. 
Tax Calculation is set on Billling Address here and at tax calculation section as well, and user is having the proper billing address assigned and VAT number.
-> The user is assigned to proper Customer group based on its VAT number but the tax seems to be calculated all the time only when the shipping address is selected on the checkout, although we have specified to use on Billing Address.  This might not be a huge problem because at the final order placement it would take the proper tax, only is causing confusion on cart, **_BUT if we have only downloadable products and here we don't have shipping selection,  the tax is not calculated properly_**

We are having issues because of this, can you give me feedback on it?

Thanks,
Szabi

**Comment by veloraven** [comment]
@ksz2013 thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
@ksz2013 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
