### ISSUE TITLE
[2.1] Store View Language switch leads to 404 on some cases

### ISSUE THREAD

**Issue by Krapulat** [magento/magento2#5416]
In Magento 2.1, when you are in a top category, for example: example.com/fashion and you switch to another language, it works ok.

But when you are inside a child category, like: example.com/fashion/men and you switch to another language, it leads to 404 not found. 

In child category, the url becomes: example.es/fashion/fashion/men (main category duplicated in url) so it returns a 404.

**Comment by andimov** [comment]
@Krapulat 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by Krapulat** [comment]
In Magento 2.1:
-Add a new language (Stores > All Stores > Create Store View). For example spanish.
-Translate an existing category (fashion) and its subcategories (men, women) (Products > Categories). Select new Store View and change the name of the category (moda) and subcategories (hombre, mujer). Also change the "url".
-Go to this subcategory in frontend and change the language with the switcher in the top. It leads to a 404 error not found.

For example, if you are in example.com/fashion/men and you switch to spanish, it goes to "example.com/fashion/moda/hombre" (404). The correct URL would be "example.com/moda/hombre"

**Comment by Krapulat** [comment]
Any news in this bug?

**Comment by tanvandinh** [comment]
That issues relate with Magento cache. Any news in this bug?

**Comment by slopukhov** [comment]
@Krapulat thank you for your feedback,
Please, recheck it on the latest 2.1 version of Magento with configured cron job.

**Comment by lucasalfaro** [comment]
Hi,

I am having the same issue on 2.1. I have 2 different view (one spanish - one english) and when on a product with different url key, I get a 404 switching views.

L.

**Comment by SilvanLaroo** [comment]
This issue still exists in Magento 2.1.2.

**Comment by paknauer** [comment]
@slopukhov Are there any news on this issue? Or is there a workaround to avoid this behavior? I'm still having this problem with Magento 2.1.6

**Comment by IlnitskiyArtem** [comment]
Hi, @Krapulat. I've linked this GitHub issue to internal ticket MAGETWO-70726.

**Comment by codesource** [comment]
This issue still exists in Magento 2.1.8. 
Does anyone has a workaround?

**Comment by HedonieBrazil** [comment]
I am having the same issue... how is it possible, that magento have a so huge community... and there is still so many bugs...

Well it is possible to fix the problem manually adding redirect rules, but it is a real fix.

**Comment by magento-engcom-team** [comment]
@Krapulat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@Krapulat, thank you for your report.
We've created internal ticket(s) MAGETWO-70726 to track progress on the issue.

**Comment by appicsandbox** [comment]
Same issue here! @Krapulat are you still having this issue? If so, can you open this issue again?
