### ISSUE TITLE
Cache tags does not get created for widgets.

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#5417]
Since Magento\Cms\Block\Widget\Block class does not implement from Magento\Framework\DataObject\IdentityInterface, X-Magento-Tags related to widgets does not get created. This will effect to widgets & static blocks created from admin panel. Once you update static block contents or widgets, the changes will not get effected in the front end because of the missing cache tags.
Refer: Magento\PageCache\Model\Layout\LayoutPlugin::afterGetOutput()

**Comment by ilol** [comment]
MDVA-764

**Comment by andimov** [comment]
@bgkavinga
Thank you for reporting!
Did you try to use MDVA-764 as a fix for your issue?

**Comment by bgkavinga** [comment]
@andimov what you mean by MDVA-764?

**Comment by andimov** [comment]
@bgkavinga
Sorry, I made a mistake assuming that support patch already released.
It is our internal ticket for this issue.

**Comment by koenner01** [comment]
Any news on this ?

**Comment by magento-engcom-team** [comment]
@bgkavinga, thank you for your report.
We've created internal ticket(s) MAGETWO-83661 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @bgkavinga

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by rodrigowebjump** [comment]
@magento-engcom-team Hi, do you have any update on this?

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump 
Unfortunately, we do not have any updates regarding this ticket.

**Comment by rodrigowebjump** [comment]
@magento-engcom-team I am working on it.

**Comment by magento-engcom-team** [comment]
@bgkavinga, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
