### ISSUE TITLE
After upgrade from 2.0.7 to 2.1.0 admin grids are not displaying.

### ISSUE THREAD

**Issue by amanuni** [magento/magento2#5421]
I have recently upgraded magento 2.0.7 to 2.1.0 from terminal using below mentions commands.

```
composer update
composer require magento/magento-composer-installer
composer require magento/product-community-edition 2.1.0 --no-update
composer update
php bin/magento setup:upgrade
```

After success full upgraded and after running successful setup upgrade i have checked frontend looks good but in backend grids are not loading i have checked product grid and sales order grid its not loading. I have checked console and seen below mentioned error.

```
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
jquery-migrate.js:21 JQMIGRATE: Logging is active
VM2699:1 Uncaught TypeError: Cannot read property 'provider' of undefined

```

Please look into this.

**Comment by davidbilly** [comment]
@amanuni just upgrade to 2.1.0 CE from 2.0.4 CE. And have same exactly issue as you. 
1) Missing all the Filter function.
2) Go to Product detail page forever loading. 
3) Go to invoice , show Notice: Undefined index: base_grand_total in /vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php on line 55
4) And more 

<img width="1913" alt="screen shot 2016-07-03 at 5 21 40 am" src="https://cloud.githubusercontent.com/assets/3938103/16542520/40dbae24-40de-11e6-899c-3f389cd9cd3f.png">

WTH with this system. Are you guys really test it before release to public? 
#4747

**Comment by amanuni** [comment]
Thanks @davidbilly i have gone through this but no luck. I had observed that repose are returning in data but not displaying it admin grid.

`VM2699:1 Uncaught TypeError: Cannot read property 'provider' of undefined`

**Comment by davidbilly** [comment]
@amanuni i fix the Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

Just go ur nginx config and remove add_header 'X-XSS-Protection' '1; mode=block'; 

They did change some code on nginx.conf.sample for V2.1.0 

anyway, i still have those JS error :(

**Comment by amanuni** [comment]
I am still having issue with grid even i have same issue with new installation also. I have tried it in my local on my test server but same issue.

**Comment by Ctucker9233** [comment]
I get this error also...

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

I'm using apache, so how to fix for this?

**Comment by amanuni** [comment]
@Ctucker9233 unfortunately their is not a good fix i have fixed X-XSS-Protection issue by commenting some lines  and modifying some lines.
`vendor/magento/framework/App/Response/HeaderProvider/XssProtection.php`

Commented line 14

`//protected $headerName = 'X-XSS-Protection';`

Modified line line 20

`const HEADER_ENABLED = '1; mode=block';`

to 

`const HEADER_ENABLED = '1';`

And also commented 2 lines in.

`vendor/magento/framework/App/Response/HeaderProvider/XContentTypeOptions.php`

Commented line 12 and 16

```
//protected $headerValue = 'nosniff';
//protected $headerName = 'X-Content-Type-Options';
```

**Comment by amanuni** [comment]
However my grid problem still not resolved.

**Comment by davidbilly** [comment]
@amanuni you may try my solution? refer #5426

**Comment by amanuni** [comment]
I have tried but no luck i have installed on both apache and nginx server and getting same issue. Even after new installation.

**Comment by amanuni** [comment]
After very much resolving of previous on now getting 

`knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.`

**Comment by kanduvisla** [comment]
Is Magento 2.1 applying knockout bindings on all elements? I have a similar issue (#5514) and I'm thinking there's been added some knockout logic to the admin that breaks other knockout logic.

**Comment by amanuni** [comment]
Guys still having this this issue and grids are not working can someone tell me the proper fix i have tried in each browser also in icognitio mode also but still getting same error.

`knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.`

**Comment by deangite** [comment]
Its browser caching issue. Try to clear browsing data. I had the same issue with loading forever in product->catalog

**Comment by andimov** [comment]
@amanuni
Thank you for reporting!
Do you have any update for this issue?
Was it related to the cache?

**Comment by amanuni** [comment]
Hi @andimov 

`Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.`

Above errors are still persist however, displaying product grid and sales grid is resolved by applying below mentioned solution.

I have replaced below mentioned line.

app/etc/di.xml

Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink
to
Magento\Framework\App\View\Asset\MaterializationStrategy\Copy

and deleted all data from.

var/cache
var/page_cache
var/generation
pub/static

After everything looks good except "Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied."

**Comment by andimov** [comment]
@amanuni 
Thanks for the reply! I will investigate this issue.

**Comment by andimov** [comment]
@amanuni 
Can't reproduce it.
 X-XSS-Protection header string must be shortened to "X-XSS-Protection: 1; mode=block
But for some reasons value for this header duplicated.

Please provide additional info:
- What web server are you using? (with full version name) 
- What browser do you use? (with full version name) 
- HTTP Headers which you received with this error.

**Comment by JerVoo** [comment]
Having the same issue.

Running Ubuntu 14.04.4 LTS, Apache 2.4.7, PHP 7.0.8-4+deb.sury.org~trusty+1 with Zend OPcache enabled. The problem exists in all browsers (currently using Firefox 47.0 on Linux Mint).

**Request headers**
Host: xxx.xxx.nl
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://xxx.xxx.nl/admin/admin/dashboard/
Cookie: mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; admin=tevmqu3l17dhnb1mbpg17gjak6; guest_token=IndBNGRaLVMta0ZVRlJfWWU1VVVhanci--d541f74ea8838c2257144019a2c58f053670100c
Connection: keep-alive
Cache-Control: max-age=0

**Response headers**
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 13213
Content-Type: text/html; charset=UTF-8
Date: Mon, 08 Aug 2016 08:41:04 GMT
Expires: Sat, 08 Aug 2015 08:41:04 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: admin=tevmqu3l17dhnb1mbpg17gjak6; path=/admin; domain=xxx.xxx.nl; HttpOnly
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
x-ua-compatible: IE=edge

**Console output**

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
            knockout.js:72:9
Error: You cannot apply bindings multiple times to the same element.
      applyBindingsToNodeInternal()
             knockout.js:2908
      applyBindingsToNodeAndDescendantsInternal()
             knockout.js:2854
      ko.applyBindings()
             knockout.js:3065
      .wrap/</_super()
             wrapper.js:73
      .applyBindings()
             bound-nodes.js:116
      .wrap/<()
```

**Comment by andimov** [comment]
@JerVoo 
You have different issue https://github.com/magento/magento2/issues/4449

**Comment by andimov** [comment]
@amanuni 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by grasdaggel** [comment]
Ticket has its reason to be here - I have the same someproblem on Magento 2.1.0 when trying to access a product page with a requirejs-config.js in the Theme. When this file is not there it _seems_ that the bug is not there.

We have the following setup according to your questions and I can reproduce it. 

However, my console out put differs a little:

```
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
jquery-migrate.js:21 JQMIGRATE: Logging is active
knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.
```

Server is an Apache2, but I cannot find out which version. Its managed hosting, so I have no access to this data right now.

Browser Information: `$_ENV['HTTP_USER_AGENT']  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36`

How can I find out the HTTP Headers that I get combined with this request?

**Comment by toddliningerdesign** [comment]
@andimov wrote:

> > X-XSS-Protection header string must be shortened to `X-XSS-Protection: 1; mode=block` but for some reason the value for this header is duplicated.
> 
> Please provide additional info:
> 
> What web server are you using? (with full version name)

Apache/2.2.31 (Unix)

> What browser do you use? (with full version name)

I get this error in the latest version of Chrome (Mac) and Safari 10.

> HTTP Headers which you received with this error.

X-XSS-Protection:"1; mode=block, 1; mode=block"

I am using Magento 2.1.0.

**Comment by amanuni** [comment]
Guys its still not resolved. On my server i am still getting this issue.

Regards,
Irsad

**Comment by Sunilkanigalupula** [comment]
Recently I updated 2.0.6 to 2.1.2 after that my admn panel doesn't show anything on blocks and pages and configurations.
I was updated following conditions:
1)PHP bin/magneto setup:upgrade
2)PHP bin/magneto setup:static-content:deploy
3)file permissions

But still I am facing problem
Please any one help me to figure out this
Thanks in advance

**Comment by alexnos88** [comment]
Exactly the same issue. M2.1.0

> WTH with this system. Are you guys really test it before release to public? 

+

**Comment by romeof1980** [comment]
hi, there!
same for us after upgrading to 2.1.2
we tried to delete all cache and redeploy static content with no avail.
we tried to disable CDN too and then cleared browser cache, tried to disable minifying js, always with no avail.

most weird thing: always works on a laptop (no matter with which browser) but does not work on other devices. I thought due to browser cache but after clearing all caches the behaviour does not change.

Am I missing something?
I took a look at #5426 but it isn't of much help.
hi @andimov , could you kindly tell us if there is any update about this issue?

We're stuck and short of ideas...
many thanks

by the way, no errors appear in the console...

**Comment by romeof1980** [comment]
hi there..
hi @andimov ... never mind
cloudflare... and my head in the clouds...
my fault.
was absolutely a cache-related issue (particularly to the CDN)

I forgot that beeing in multisite I was supposed to clear the CDN of the main website if I have got problem in the backend... what the helll.. I'd better be more careful.... wasted a lot of time... :)

thanks,
solved for me as CDN-cache related

cheers,
romeo
