### ISSUE TITLE
Sampledata forced upon database with own data

### ISSUE THREAD

**Issue by elmosgot** [magento/magento2#5425]
## I upgraded from 2.0.7 to 2.1RC3
1. Install Magento from `2.0.7` branch without sampledata
2. Add some custom data
3. Upgrade Magento to `2.1.0 RC3` using the web setup wizard
## Expected result
1. Not install sampledata during upgrade or when data exists in the database
## Actual result
1. Custom data gets overwritten by sampledata during upgrade

**Comment by shiftedreality** [comment]
Hi @elmosgot 

Could you please clarify how did you install sample data?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed.
