### ISSUE TITLE
Adding Product To Compare not working

### ISSUE THREAD

**Issue by lucasng13** [magento/magento2#5427]
## Steps to reproduce
1. Install Magento 2.0.x or 2.1.
2. Add a product to compare.
## Expected result
1. Product should be added to compare.
## Actual result
1. Product can't be added to compare.
2. Compare button only works after adding any product to cart
3. If you test this bug, you should clear all cookies on Magento site.

**Comment by pboisvert** [comment]
Not able to reproduce. Using 2.1 build with sample data i added 3 products from one of the product listing pages to "compare" using the compare icon when hovering over a specific products. All products were added to the "Compare Products" list as seen here:

<img width="521" alt="screen shot 2016-07-03 at 10 25 22 am" src="https://cloud.githubusercontent.com/assets/5807369/16546697/aa898c28-4107-11e6-92b1-a45e12b8dfa6.png">

then when clicking "compare" button i am taken to the Compare Products page with those 3 products selected as seen here

<img width="1355" alt="screen shot 2016-07-03 at 10 25 43 am" src="https://cloud.githubusercontent.com/assets/5807369/16546699/ae01719a-4107-11e6-9c61-978850cf0c55.png">

Did you follow different steps to compare? If so please be specific about the steps so we can try to reproduce.

**Comment by lucasng13** [comment]
I installed clean Magento 2.0.7 with sample data. Then, I add a product to compare (on category page or on homepage Luma theme)
![compare](https://cloud.githubusercontent.com/assets/19704072/16550393/44db46dc-41d4-11e6-970e-c6f050e8fad5.png)

As I said, compare product only works after I add a product to cart. Otherwise, I only see message "You added product Breathe-Easy Tank to the comparison list."
Is it a bug ?

**Comment by Pigau** [comment]
I have a similar bug in Magento 2.0.7.
The products are actually added to the comparator, but the sidebar works only if you have a product in your cart.

To reproduce : 
- Clear your session
- Be unlogged or with a new customer
- From result page add a product to comparator
- Reload the page -> no product in comparator sidebar
- Add a product to your cart
- Reload the page -> one product in comparator sidebar

**Comment by veloraven** [comment]
@lucasng13 thank you for your report.
Can you confirm that this issue reproduces without sample data on clear install? On any version.
As I was able to reproduce only **following case:**
1. Open frontend;
2. Clean all cookies and sessions;
3. Add some product to compare
**Actual Result:**
- Page reloads and nothing happens: no product in compare list, no success message about adding the product to the compare list. 
- If you try to add the product once more it will be added successfully.

But such case does not seem to be correct as customer already gets some cookies and sessions when he just opens Magento site.

In case when I cleared everything and then opened a page and added a product to the comparison everything was ok, and the product was added successfully to the comparison list.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by clivewalkden** [comment]
This is also happening on my 2.0.7 production store without sample data. I'll do some testing on a brand new version without sample data in the next couple of days. I would appreciate the ticket being re-opened.

**Comment by clivewalkden** [comment]
Seems to only happen when caching disabled, works fine when caching enabled.

**Comment by Techytt** [comment]
Need to re-open as we are facing the same issue on Magento ver. 2.1.4 even if system have enabled caching.

**Comment by Techytt** [comment]
Finally resolved an issue for me:
I have unselected system value for Magento cache configuration setting.
See attached screenshot for reference.

![cache-issue](https://user-images.githubusercontent.com/23012268/31389152-ca2785f4-aded-11e7-8a50-6696716e9c6a.png)
