### ISSUE TITLE
Magento 2.1 no table rates upload button

### ISSUE THREAD

**Issue by Nerogee** [magento/magento2#5429]
## Steps to reproduce
1. magento 2.1
2. go to shipping method -> table rates
## Expected result
1. a function to upload table rates
## Actual result
1. there is no such a function / button to upload the table rates file

**Comment by pboisvert** [comment]
Check that you have the right store view scope selected. I am not able to reproduce this error as the Import button is shown in my version of 2.1
<img width="1321" alt="screen shot 2016-07-03 at 10 07 38 am" src="https://cloud.githubusercontent.com/assets/5807369/16546619/251b6ca2-4105-11e6-8f23-058cf2feedc2.png">

**Comment by Nerogee** [comment]
yes, change the scope to **Main Website** (only this one) solve my problem. Thanks

**Comment by Nerogee** [comment]
@pboisvert I got error message **Something went wrong while importing table rates**. Do you have any idea about this? thanks

**Comment by Nerogee** [comment]
@pboisvert forget it. I found out the reason already.

**Comment by skyperthefirst1** [comment]
Hello @Nerogee I am facing the same issue now. Do you remember what was the reason in your case for this error: "Something went wrong while importing table rates"?

**Comment by ghost** [comment]
@pboisvert Magento is a open source platform, GitHub is to help each other with open source related things, issues and advice. I hop you can help us with your solution on this matter. That is where this Githup platform is mentioned for. Thank you. I have the same issue.
