### ISSUE TITLE
Admin grid paging options. 

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#543]
I think that the admin grids should support custom number of items per page.  
Right now they are hard coded in `app/code/Magento/Backend/view/adminhtml/widget/grid.phtml` to `20,30,50,100,200`. I think the `Grid` class should have a method called `getLimits` (or something similar) that can be overwritten in the child classes to support custom values.

**Comment by Tiurnikova** [comment]
Hey everyone, 
Thank you for your participation. We're making some significant changes to Data Grids already and there is a ticket in our internal backlog to support custom number of items per page. It will be handled according to the priorities.
Thanks
