### ISSUE TITLE
2.1 Can't change customer group

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#5430]
## Steps to reproduce
1. Install Magento 2.1
2. Select a customer
3. Edit the customer
4. Change the customer group from Retailer to something else
## Expected result
1. The customer new group info is saved
2. ...
## Actual result
1. The customer is saved and redirected to the customer list page
2. Click the edit on the customer
3. The group is NOT changed, back to Retailer

**Comment by JDavidVR** [comment]
@sheldonli999  I'm using the 2.1 with sample data, and I changed customer group as your instructions, but I'm not having the issue you mentioned. maybe is an issue with file permission on var folder

**Comment by wert2all** [comment]
@sheldonli999  I cannot reproduce this issue. To allow us research the issue, please, provide more concrete steps for reproducing.

**Comment by Part-A** [comment]
I to am having this same problem. Additionally, because the Customer Group is not stored, special pricing and tiered pricing is not applied appropriately.

**Comment by flnative** [comment]
I have the same issue with 2.1. This is very important. Please provide an update on this as I cannot proceed to sell to my wholesale customers. 

You cannot update customer group from the Customer tab or from the option of changing the group when doing an ADMIN order. What is the permission for the Var folder?

**Comment by oserediuk** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
