### ISSUE TITLE
Creating too many product variations causes unpredictable results, appears to have cut data off in submission.

### ISSUE THREAD

**Issue by mattquest** [magento/magento2#5431]
## Steps to reproduce

Try creating product variations with 20 colors and 6 sizes each.
## Expected result
1. Creates the product variations and leaves the main configurable product alone.
2. ...
## Actual result
1. creates some of the configurable products and strips data out of the main products, like the name, sku, url key, etc all become blank.

**Comment by tobias-forkel** [comment]
I had similar issues with Bundle Products in M1 before. The amount of data for each POST is limited and managed by PHP. So it could be related with your hosting and the values such as `post_max_size=20M` and `max_input_vars=1000`. Can you increase the values and try again?

Source: http://magento.stackexchange.com/questions/48241/magento-bundle-products-problem-with-the-option-to-add-new

**Comment by heyitsroberthe** [comment]
The limiting factor is the max_input_vars. Each product variation takes at least 20 input vars. There is some overhead so I recommend 25 times the number of variations to be safe.

**Comment by mattquest** [comment]
It was php settings, I updated the max_input_vars and post_max_size because I was uploading 2 images per color as well
