### ISSUE TITLE
[QUESTION] Where does _rootDirectory come from?

### ISSUE THREAD

**Issue by centerax** [magento/magento2#5434]
here https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Option/Type/File.php#L452 who fills $this->_rootDirectory?

**Comment by vkorotun** [comment]
Good question @centerax !
Internal ticket: MAGETWO-56370

**Comment by slavvka** [comment]
The issue has been fixed and delivered to mainline

**Comment by Ctucker9233** [comment]
Is this fix safe to integrate into a 2.1.1 production environment or is there a patch pending?

**Comment by irenelagno** [comment]
@Ctucker9233 This fix will be delivered to 2.1 in the scope of  MAGETWO-59036 and to 2.0 MAGETWO-59035

**Comment by Ctucker9233** [comment]
@irenelagno Thanks. I don't suppose there's an estimate of when it might be delivered?

**Comment by pboisvert** [comment]
currently targeted to 2.1.3 which will be next release--no date to publish now but ASAP
