### ISSUE TITLE
Newsletter subscription

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#5439]
## Preconditions
1. Magento 2.1

## Steps to reproduce
1. Create customer
2. Subscribe customer to a Newsletter
3. Verify that customer is subscribed to the newsletter and received email notification about subscription.
4. Subscribe same customer to the same email again.

## Expected result
1. Customer does not receive another email on subscribing to newsletter

## Actual result
1 Customer keeps receiving emails on every newsletter subscription.

## Description
No onscreen confirmation of sign up. No error message when trying to subscribe an existing subscriber

Getting message on subscribing newsletter as well as e-mail.

You have been successfully subscribed to our newsletter. 

It should generate an error if i am subscribing with the same email address again and again but it won't

**Comment by antboiko** [comment]
Hi @ednacool , please provide detailed steps to reproduce the issue in an appropriate format with Expected and Actual results. What Magento version are you running? 

Best,
Anton.

**Comment by orlangur** [comment]
@antboiko provided steps are sufficient. At least I don't see any obscurity.

> No error message when trying to subscribe an existing subscriber

This is correct behavior. Same as for registering or password recovery - system should not reveal excessive information about emails to avoid their grabbing for spam or something.

> Getting message on subscribing newsletter as well as e-mail.

And this does not seem OK. Basically, you should not receive more than one email until you confirm subscription I believe. So that you cannot bother somebody with tons of same messages by just having his email.

**Comment by antboiko** [comment]
Hi @ednacool , thanks for reporting. We've created internal ticket MAGETWO-55106 to investigate this.

**Comment by hezide** [comment]
same issue here, magento CE 2.1.2.

**Comment by PGLDK** [comment]
same 2.1.4

**Comment by lhsatch** [comment]
Just after line 429 add:
`$checkGuest = $this->loadByEmail($email);
		if($checkGuest->getSubscriberId()){
			 throw new \Magento\Framework\Exception\LocalizedException(
          __('This email address has already subscribed.')
            );
		}`

**Comment by magento-engcom-team** [comment]
@ednacool, thank you for your report.
We've created internal ticket(s) MAGETWO-78293 to track progress on the issue.

**Comment by osrecio** [comment]
@okorshenko Can you assign me this issue?

**Comment by okorshenko** [comment]
#SQUASHTOBERFEST

**Comment by osrecio** [comment]
Created PR for 2.1 and 2.2

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81326

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82942
