### ISSUE TITLE
Wishlist Comment Box

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#5440]
Wishlist comment box displaying but unable to add a comment would anyone let me know how this feature get work

**Comment by antboiko** [comment]
Hi @ednacool , click Update Wish List after you added the comment.

I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 

Best,
Anton.

**Comment by ednacool** [comment]
Hi antboiko,

It's a issue if you login in Magento 2 customer account and add any item to wishlist then navigate to My wishlist here you see comment box with now add comment button. 

Please let me know if i am wrong over this

**Comment by antboiko** [comment]
Hello @ednacool , I replied you within this ticket https://github.com/magento/magento2/issues/5516. Click Update Wish List button after you added a comment and it will be saved.
