### ISSUE TITLE
Rest Api - GET /V1/products not giving color hash code in response

### ISSUE THREAD

**Issue by qwerty7869** [magento/magento2#5442]
## Steps to reproduce
1. Use /V1/products api which will give products with its attribute of a specific category.
## Expected result
1. Api should also give color hash code in response which is the basic functionality as Magento 2 desktop site provide this functionality.

**Comment by veloraven** [comment]
@qwerty7869 thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide more detailed steps, with full header and body of your request, and actual result as well.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
