### ISSUE TITLE
Magento CE 2.1 Catalog Admin Page cannot parse media url in html content

### ISSUE THREAD

**Issue by hugh-optoma** [magento/magento2#5444]
Magento CE 2.1 + PHP 56 + nginx + varnish
## Steps to reproduce
1. Product -> Catalog -> Select a catalog to edit
2. Content -> Description -> Raw html mode
3. Input the html content: &lt;img src="{{media url="wysiwyg/LOGO.png"}}" alt="" /&gt;
4. Save
5. View the raw html shown in the page
## Expected result

&lt;img src="{{media url="wysiwyg/LOGO.png"}}" alt="" /&gt;
## Actual result

&lt;p>&lt;img src="{{media url=" alt="" /&gt;&lt;/p&gt;
## Remarks

The actual value saved in DB: &lt;img src="{{media url="wysiwyg/LOGO.png"}}" alt="" /&gt;

**Comment by veloraven** [comment]
@hugh-optoma thank you for your report.
Internal ticket MAGETWO-56414 was created for this issue.

**Comment by pantaoran** [comment]
I believe this is a duplicate of the following issues:
https://github.com/magento/magento2/issues/5811
https://github.com/magento/magento2/issues/6851
https://github.com/magento/magento2/issues/7215

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435

**Comment by magento-engcom-team** [comment]
The issue has been fixed in 2.1.8
@hugh-optoma please let us know if you still have an issue
