### ISSUE TITLE
[M 2.1] Coupon Code doesn't work sometimes

### ISSUE THREAD

**Issue by Krapulat** [magento/magento2#5452]
In Magento 2.1.0, sometimes the coupon code doesn't work.

Not always, it happens sometimes when I open a new private browser. I apply the coupon and I get: "The coupon code "XXX" is not valid." And without private browser the same coupon and same products on cart, the coupon works perfectly.

Maybe something with sessions or varnish?

Thanks.

**Comment by Ctucker9233** [comment]
You said with a private browser it says "not valid" and without private browser the coupon is "valid". Is that correct? It could be something to do with your browser cookies as well.

**Comment by veloraven** [comment]
@Krapulat thank you for your report.
Could you please provide more detailed steps? Your price rule options, typed of product added to the cart, etc.
Also please provide information about your environment: PHP, MySQL, web server versions, with browser do you use.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
