### ISSUE TITLE
Crons dont seem to be running

### ISSUE THREAD

**Issue by didineedthis** [magento/magento2#5454]
## Steps to reproduce
1. Install Magento from `develop` branch.
   2.My hosts set up crons as per documentation.
## Expected result
1. crons to run.
## Actual result

1.No crons are updating.

File paths are set correct also checked by my hosts

php -c /usr/local/lib/php.ini /home/xxxxxxxx/public_html/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /home/xxxxxxxx/public_html/var/log/magento.cron.log

php -c /usr/local/lib/php.ini /home/xxxxxxxx/public_html/update/cron.php >> /home/xxxxxxxx/public_html/var/log/update.cron.log

php -c /usr/local/lib/php.ini /home/xxxxxxxx/public_html/bin/magento setup:cron:run >> /home/xxxxxxxx/public_html/var/log/setup.cron.log

Any idea why they are not running.

magento cron log
bin/magento must be run as a CLI application
Content-type: text/html; charset=UTF-8

update cron.log
Content-type: text/html; charset=UTF-8
<br />
Fatal error</b>:  Class 'Magento\Update\PermissionInfo' not found in /home/XXXXXX/public_html/update/app/code/Magento/Update/CronReadinessCheck.php</b> on line 156

setup cron.log
bin/magento must be run as a CLI applicationContent-type: text/html; charset=UTF-8

bin/magento must be run as a CLI application

**Comment by commcad** [comment]
Give it your php cli path and see if it helps. For instance, mine are setup like;

*/1 \* \* \* \* php -c /etc/php/7.0/cli/php.ini /var/www/mydomain.com/bin/magento cron:run >/dev/null
*/1 \* \* \* \* php -c /etc/php/7.0/cli/php.ini /var/www/mydomain.com/update/cron.php >/dev/null
*/1 \* \* \* \* php -c /etc/php/7.0/cli/php.ini /var/www/mydomain.com/bin/magento setup:cron:run >/dev/null

**Comment by didineedthis** [comment]
I Ran this command and it shows my php path 

# php -i |grep php.ini

Configuration File (php.ini) Path => /usr/local/lib
Loaded Configuration File => /usr/local/lib/php.ini

does not mention cli?

**Comment by wert2all** [comment]
@didineedthis Thanks for report.
Please provide output of command here
`echo "<?php echo PHP_SAPI .\"\n\";" | php -c /usr/local/lib/php.ini`

**Comment by didineedthis** [comment]
# echo "<?php echo PHP_SAPI .\"\n\";" | php -c /usr/local/lib/php.ini

cli

**Comment by wert2all** [comment]
@didineedthis Can You update Magento because I cannot find class Magento/Update/CronReadinessCheck.php in current develop.

**Comment by didineedthis** [comment]
what version should i update to? i am running 2.1 from github

**Comment by didineedthis** [comment]
can i just upload the update folder?  from
Magento-CE-2.1.0.zip

**Comment by wert2all** [comment]
You need to install Magento to a clean folder from Magento-CE-2.1.0.zip for the purity of the experiment.

**Comment by didineedthis** [comment]
Then i will loose my website and all products?

**Comment by wert2all** [comment]
1. Create a backup of magento database
2. Create new database, m2second example.
3. Import dump from first step to new database ( m2second )
4. unpack Magento-CE-2.1.0.zip to another folder, /home/XXXXXX/public_html/m2test example
5. Install Magento from /home/XXXXXX/public_html/m2test folder and use m2second database during installation  for this instance
6. reproduce this issue in /home/XXXXXX/public_html/m2test  instance.

**Comment by didineedthis** [comment]
Ok thanks for the info, appreciated.
 I will update shortly

**Comment by didineedthis** [comment]
i have followed the steps outlined but the installation is


 failing at 49%
Installation is incomplete. 
Check the console log for errors before trying again.


`<span class="text-info">Starting Magento installation:</span><br><span class="text-info">File permissions check...</span><br><span class="hidden">[Progress: 1 / 421]</span><br><span class="text-info">Required extensions check...</span><br><span class="hidden">[Progress: 2 / 421]</span><br><span class="text-info">Enabling Maintenance Mode...</span><br><span class="hidden">[Progress: 3 / 421]</span><br><span class="text-info">Installing deployment configuration...</span><br><span class="hidden">[Progress: 4 / 421]</span><br><span class="text-info">Installing database schema:</span><br><span class="text-info">Schema creation/updates:</span><br><span class="text-info">Module 'Magento_Store':</span><br><span class="hidden">[Progress: 5 / 421]</span><br><span class="text-info">Module 'Magento_AdvancedPricingImportExport':</span><br><span class="hidden">[Progress: 6 / 421]</span><br><span class="text-info">Module 'Magento_Directory':</span><br><span class="hidden">[Progress: 7 / 421]</span><br><span class="text-info">Module 'Magento_Theme':</span><br><span class="hidden">[Progress: 8 / 421]</span><br><span class="text-info">Module 'Magento_Backend':</span><br><span class="hidden">[Progress: 9 / 421]</span><br><span class="text-info">Module 'Magento_Backup':</span><br><span class="hidden">[Progress: 10 / 421]</span><br><span class="text-info">Module 'Magento_Eav':</span><br><span class="hidden">[Progress: 11 / 421]</span><br><span class="text-info">Module 'Magento_Customer':</span><br><span class="hidden">[Progress: 12 / 421]</span><br><span class="text-info">Module 'Magento_BundleImportExport':</span><br><span class="hidden">[Progress: 13 / 421]</span><br><span class="text-info">Module 'Magento_CacheInvalidate':</span><br><span class="hidden">[Progress: 14 / 421]</span><br><span class="text-info">Module 'Magento_AdminNotification':</span><br><span class="hidden">[Progress: 15 / 421]</span><br><span class="text-info">Module 'Magento_Indexer':</span><br><span class="hidden">[Progress: 16 / 421]</span><br><span class="text-info">Module 'Magento_CatalogImportExport':</span><br><span class="hidden">[Progress: 17 / 421]</span><br><span class="text-info">Module 'Magento_Cms':</span><br><span class="hidden">[Progress: 18 / 421]</span><br><span class="text-info">Module 'Magento_Rule':</span><br><span class="hidden">[Progress: 19 / 421]</span><br><span class="text-info">Module 'Magento_Catalog':</span><br><span class="hidden">[Progress: 20 / 421]</span><br><span class="text-info">Module 'Magento_Search':</span><br><span class="hidden">[Progress: 21 / 421]</span><br><span class="text-info">Module 'Magento_CatalogUrlRewrite':</span><br><span class="hidden">[Progress: 22 / 421]</span><br><span class="text-info">Module 'Magento_Widget':</span><br><span class="hidden">[Progress: 23 / 421]</span><br><span class="text-info">Module 'Magento_Quote':</span><br><span class="hidden">[Progress: 24 / 421]</span><br><span class="text-info">Module 'Magento_CheckoutAgreements':</span><br><span class="hidden">[Progress: 25 / 421]</span><br><span class="text-info">Module 'Magento_SalesSequence':</span><br><span class="hidden">[Progress: 26 / 421]</span><br><span class="text-info">Module 'Magento_CmsUrlRewrite':</span><br><span class="hidden">[Progress: 27 / 421]</span><br><span class="text-info">Module 'Magento_Config':</span><br><span class="hidden">[Progress: 28 / 421]</span><br><span class="text-info">Module 'Magento_ConfigurableImportExport':</span><br><span class="hidden">[Progress: 29 / 421]</span><br><span class="text-info">Module 'Magento_Msrp':</span><br><span class="hidden">[Progress: 30 / 421]</span><br><span class="text-info">Module 'Magento_Contact':</span><br><span class="hidden">[Progress: 31 / 421]</span><br><span class="text-info">Module 'Magento_Cookie':</span><br><span class="hidden">[Progress: 32 / 421]</span><br><span class="text-info">Module 'Magento_Cron':</span><br><span class="hidden">[Progress: 33 / 421]</span><br><span class="text-info">Module 'Magento_CurrencySymbol':</span><br><span class="hidden">[Progress: 34 / 421]</span><br><span class="text-info">Module 'Magento_Bundle':</span><br><span class="hidden">[Progress: 35 / 421]</span><br><span class="text-info">Module 'Magento_CustomerImportExport':</span><br><span class="hidden">[Progress: 36 / 421]</span><br><span class="text-info">Module 'Magento_Deploy':</span><br><span class="hidden">[Progress: 37 / 421]</span><br><span class="text-info">Module 'Magento_Developer':</span><br><span class="hidden">[Progress: 38 / 421]</span><br><span class="text-info">Module 'Magento_Dhl':</span><br><span class="hidden">[Progress: 39 / 421]</span><br><span class="text-info">Module 'Magento_Authorization':</span><br><span class="hidden">[Progress: 40 / 421]</span><br><span class="text-info">Module 'Magento_Downloadable':</span><br><span class="hidden">[Progress: 41 / 421]</span><br><span class="text-info">Module 'Magento_ImportExport':</span><br><span class="hidden">[Progress: 42 / 421]</span><br><span class="text-info">Module 'Magento_Payment':</span><br><span class="hidden">[Progress: 43 / 421]</span><br><span class="text-info">Module 'Magento_Email':</span><br><span class="hidden">[Progress: 44 / 421]</span><br><span class="text-info">Module 'Magento_User':</span><br><span class="hidden">[Progress: 45 / 421]</span><br><span class="text-info">Module 'Magento_Fedex':</span><br><span class="hidden">[Progress: 46 / 421]</span><br><span class="text-info">Module 'Magento_Sales':</span><br><span class="hidden">[Progress: 47 / 421]</span><br><span class="text-info">Module 'Magento_CatalogInventory':</span><br><span class="hidden">[Progress: 48 / 421]</span><br><span class="text-info">Module 'Magento_GoogleAnalytics':</span><br><span class="hidden">[Progress: 49 / 421]</span><br><span class="text-info">Module 'Magento_Ui':</span><br><span class="hidden">[Progress: 50 / 421]</span><br><span class="text-info">Module 'Magento_GroupedImportExport':</span><br><span class="hidden">[Progress: 51 / 421]</span><br><span class="text-info">Module 'Magento_GroupedProduct':</span><br><span class="hidden">[Progress: 52 / 421]</span><br><span class="text-info">Module 'Magento_DownloadableImportExport':</span><br><span class="hidden">[Progress: 53 / 421]</span><br><span class="text-info">Module 'Magento_Checkout':</span><br><span class="hidden">[Progress: 54 / 421]</span><br><span class="text-info">Module 'Magento_Security':</span><br><span class="hidden">[Progress: 55 / 421]</span><br><span class="text-info">Module 'Magento_LayeredNavigation':</span><br><span class="hidden">[Progress: 56 / 421]</span><br><span class="text-info">Module 'Magento_Marketplace':</span><br><span class="hidden">[Progress: 57 / 421]</span><br><span class="text-info">Module 'Magento_MediaStorage':</span><br><span class="hidden">[Progress: 58 / 421]</span><br><span class="text-info">Module 'Magento_CatalogRule':</span><br><span class="hidden">[Progress: 59 / 421]</span><br><span class="text-info">Module 'Magento_Multishipping':</span><br><span class="hidden">[Progress: 60 / 421]</span><br><span class="text-info">Module 'Magento_ConfigurableProduct':</span><br><span class="hidden">[Progress: 61 / 421]</span><br><span class="text-info">Module 'Magento_Newsletter':</span><br><span class="hidden">[Progress: 62 / 421]</span><br><span class="text-info">Module 'Magento_OfflinePayments':</span><br><span class="hidden">[Progress: 63 / 421]</span><br><span class="text-info">Module 'Magento_SalesRule':</span><br><span class="hidden">[Progress: 64 / 421]</span><br><span class="text-info">Module 'Magento_PageCache':</span><br><span class="hidden">[Progress: 65 / 421]</span><br><span class="text-info">Module 'Magento_Captcha':</span><br><span class="hidden">[Progress: 66 / 421]</span><br><span class="text-info">Module 'Magento_Vault':</span><br><span class="hidden">[Progress: 67 / 421]</span><br><span class="text-info">Module 'Magento_Persistent':</span><br><span class="hidden">[Progress: 68 / 421]</span><br><span class="text-info">Module 'Magento_ProductAlert':</span><br><span class="hidden">[Progress: 69 / 421]</span><br><span class="text-info">Module 'Magento_ProductVideo':</span><br><span class="hidden">[Progress: 70 / 421]</span><br><span class="text-info">Module 'Magento_Authorizenet':</span><br><span class="hidden">[Progress: 71 / 421]</span><br><span class="text-info">Module 'Magento_Reports':</span><br><span class="hidden">[Progress: 72 / 421]</span><br><span class="text-info">Module 'Magento_RequireJs':</span><br><span class="hidden">[Progress: 73 / 421]</span><br><span class="text-info">Module 'Magento_Review':</span><br><span class="hidden">[Progress: 74 / 421]</span><br><span class="text-info">Module 'Magento_Rss':</span><br><span class="hidden">[Progress: 75 / 421]</span><br><span class="text-info">Module 'Magento_CatalogRuleConfigurable':</span><br><span class="hidden">[Progress: 76 / 421]</span><br><span class="text-info">Module 'Magento_Paypal':</span><br><span class="hidden">[Progress: 77 / 421]</span><br><span class="text-info">Module 'Magento_OfflineShipping':</span><br><span class="hidden">[Progress: 78 / 421]</span><br><span class="text-info">Module 'Magento_GoogleAdwords':</span><br><span class="hidden">[Progress: 79 / 421]</span><br><span class="text-info">Module 'Magento_SampleData':</span><br><span class="hidden">[Progress: 80 / 421]</span><br><span class="text-info">Module 'Magento_CatalogSearch':</span><br><span class="hidden">[Progress: 81 / 421]</span><br><span class="text-info">Module 'Magento_Integration':</span><br><span class="hidden">[Progress: 82 / 421]</span><br><span class="text-info">Module 'Magento_SendFriend':</span><br><span class="hidden">[Progress: 83 / 421]</span><br><span class="text-info">Module 'Magento_Shipping':</span><br><span class="hidden">[Progress: 84 / 421]</span><br><span class="text-info">Module 'Magento_Sitemap':</span><br><span class="hidden">[Progress: 85 / 421]</span><br><span class="text-info">Module 'Magento_NewRelicReporting':</span><br><span class="hidden">[Progress: 86 / 421]</span><br><span class="text-info">Module 'Magento_Swagger':</span><br><span class="hidden">[Progress: 87 / 421]</span><br><span class="text-info">Module 'Magento_Swatches':</span><br><span class="hidden">[Progress: 88 / 421]</span><br><span class="text-info">Module 'Magento_SwatchesLayeredNavigation':</span><br><span class="hidden">[Progress: 89 / 421]</span><br><span class="text-info">Module 'Magento_Tax':</span><br><span class="hidden">[Progress: 90 / 421]</span><br><span class="text-info">Module 'Magento_TaxImportExport':</span><br><span class="hidden">[Progress: 91 / 421]</span><br><span class="text-info">Module 'Magento_GiftMessage':</span><br><span class="hidden">[Progress: 92 / 421]</span><br><span class="text-info">Module 'Magento_Translation':</span><br><span class="hidden">[Progress: 93 / 421]</span><br><span class="text-info">Module 'Magento_GoogleOptimizer':</span><br><span class="hidden">[Progress: 94 / 421]</span><br><span class="text-info">Module 'Magento_Ups':</span><br><span class="hidden">[Progress: 95 / 421]</span><br><span class="text-info">Module 'Magento_UrlRewrite':</span><br><span class="hidden">[Progress: 96 / 421]</span><br><span class="text-info">Module 'Magento_EncryptionKey':</span><br><span class="hidden">[Progress: 97 / 421]</span><br><span class="text-info">Module 'Magento_Usps':</span><br><span class="hidden">[Progress: 98 / 421]</span><br><span class="text-info">Module 'Magento_Variable':</span><br><span class="hidden">[Progress: 99 / 421]</span><br><span class="text-info">Module 'Magento_Braintree':</span><br><span class="hidden">[Progress: 100 / 421]</span><br><span class="text-info">Module 'Magento_Version':</span><br><span class="hidden">[Progress: 101 / 421]</span><br><span class="text-info">Module 'Magento_Webapi':</span><br><span class="hidden">[Progress: 102 / 421]</span><br><span class="text-info">Module 'Magento_WebapiSecurity':</span><br><span class="hidden">[Progress: 103 / 421]</span><br><span class="text-info">Module 'Magento_Weee':</span><br><span class="hidden">[Progress: 104 / 421]</span><br><span class="text-info">Module 'Magento_CatalogWidget':</span><br><span class="hidden">[Progress: 105 / 421]</span><br><span class="text-info">Module 'Magento_Wishlist':</span><br><span class="hidden">[Progress: 106 / 421]</span><br><span class="text-info">Schema post-updates:</span><br><span class="text-info">Module 'Magento_Store':</span><br><span class="hidden">[Progress: 107 / 421]</span><br><span class="text-info">Module 'Magento_AdvancedPricingImportExport':</span><br><span class="hidden">[Progress: 108 / 421]</span><br><span class="text-info">Module 'Magento_Directory':</span><br><span class="hidden">[Progress: 109 / 421]</span><br><span class="text-info">Module 'Magento_Theme':</span><br><span class="hidden">[Progress: 110 / 421]</span><br><span class="text-info">Module 'Magento_Backend':</span><br><span class="hidden">[Progress: 111 / 421]</span><br><span class="text-info">Module 'Magento_Backup':</span><br><span class="hidden">[Progress: 112 / 421]</span><br><span class="text-info">Module 'Magento_Eav':</span><br><span class="hidden">[Progress: 113 / 421]</span><br><span class="text-info">Module 'Magento_Customer':</span><br><span class="hidden">[Progress: 114 / 421]</span><br><span class="text-info">Module 'Magento_BundleImportExport':</span><br><span class="hidden">[Progress: 115 / 421]</span><br><span class="text-info">Module 'Magento_CacheInvalidate':</span><br><span class="hidden">[Progress: 116 / 421]</span><br><span class="text-info">Module 'Magento_AdminNotification':</span><br><span class="hidden">[Progress: 117 / 421]</span><br><span class="text-info">Module 'Magento_Indexer':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 118 / 421]</span><br><span class="text-info">Module 'Magento_CatalogImportExport':</span><br><span class="hidden">[Progress: 119 / 421]</span><br><span class="text-info">Module 'Magento_Cms':</span><br><span class="hidden">[Progress: 120 / 421]</span><br><span class="text-info">Module 'Magento_Rule':</span><br><span class="hidden">[Progress: 121 / 421]</span><br><span class="text-info">Module 'Magento_Catalog':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 122 / 421]</span><br><span class="text-info">Module 'Magento_Search':</span><br><span class="hidden">[Progress: 123 / 421]</span><br><span class="text-info">Module 'Magento_CatalogUrlRewrite':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 124 / 421]</span><br><span class="text-info">Module 'Magento_Widget':</span><br><span class="hidden">[Progress: 125 / 421]</span><br><span class="text-info">Module 'Magento_Quote':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 126 / 421]</span><br><span class="text-info">Module 'Magento_CheckoutAgreements':</span><br><span class="hidden">[Progress: 127 / 421]</span><br><span class="text-info">Module 'Magento_SalesSequence':</span><br><span class="hidden">[Progress: 128 / 421]</span><br><span class="text-info">Module 'Magento_CmsUrlRewrite':</span><br><span class="hidden">[Progress: 129 / 421]</span><br><span class="text-info">Module 'Magento_Config':</span><br><span class="hidden">[Progress: 130 / 421]</span><br><span class="text-info">Module 'Magento_ConfigurableImportExport':</span><br><span class="hidden">[Progress: 131 / 421]</span><br><span class="text-info">Module 'Magento_Msrp':</span><br><span class="hidden">[Progress: 132 / 421]</span><br><span class="text-info">Module 'Magento_Contact':</span><br><span class="hidden">[Progress: 133 / 421]</span><br><span class="text-info">Module 'Magento_Cookie':</span><br><span class="hidden">[Progress: 134 / 421]</span><br><span class="text-info">Module 'Magento_Cron':</span><br><span class="hidden">[Progress: 135 / 421]</span><br><span class="text-info">Module 'Magento_CurrencySymbol':</span><br><span class="hidden">[Progress: 136 / 421]</span><br><span class="text-info">Module 'Magento_Bundle':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 137 / 421]</span><br><span class="text-info">Module 'Magento_CustomerImportExport':</span><br><span class="hidden">[Progress: 138 / 421]</span><br><span class="text-info">Module 'Magento_Deploy':</span><br><span class="hidden">[Progress: 139 / 421]</span><br><span class="text-info">Module 'Magento_Developer':</span><br><span class="hidden">[Progress: 140 / 421]</span><br><span class="text-info">Module 'Magento_Dhl':</span><br><span class="hidden">[Progress: 141 / 421]</span><br><span class="text-info">Module 'Magento_Authorization':</span><br><span class="hidden">[Progress: 142 / 421]</span><br><span class="text-info">Module 'Magento_Downloadable':</span><br><span class="hidden">[Progress: 143 / 421]</span><br><span class="text-info">Module 'Magento_ImportExport':</span><br><span class="hidden">[Progress: 144 / 421]</span><br><span class="text-info">Module 'Magento_Payment':</span><br><span class="hidden">[Progress: 145 / 421]</span><br><span class="text-info">Module 'Magento_Email':</span><br><span class="hidden">[Progress: 146 / 421]</span><br><span class="text-info">Module 'Magento_User':</span><br><span class="hidden">[Progress: 147 / 421]</span><br><span class="text-info">Module 'Magento_Fedex':</span><br><span class="hidden">[Progress: 148 / 421]</span><br><span class="text-info">Module 'Magento_Sales':</span><br><span class="hidden">[Progress: 149 / 421]</span><br><span class="text-info">Module 'Magento_CatalogInventory':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 150 / 421]</span><br><span class="text-info">Module 'Magento_GoogleAnalytics':</span><br><span class="hidden">[Progress: 151 / 421]</span><br><span class="text-info">Module 'Magento_Ui':</span><br><span class="hidden">[Progress: 152 / 421]</span><br><span class="text-info">Module 'Magento_GroupedImportExport':</span><br><span class="hidden">[Progress: 153 / 421]</span><br><span class="text-info">Module 'Magento_GroupedProduct':</span><br><span class="hidden">[Progress: 154 / 421]</span><br><span class="text-info">Module 'Magento_DownloadableImportExport':</span><br><span class="hidden">[Progress: 155 / 421]</span><br><span class="text-info">Module 'Magento_Checkout':</span><br><span class="hidden">[Progress: 156 / 421]</span><br><span class="text-info">Module 'Magento_Security':</span><br><span class="hidden">[Progress: 157 / 421]</span><br><span class="text-info">Module 'Magento_LayeredNavigation':</span><br><span class="hidden">[Progress: 158 / 421]</span><br><span class="text-info">Module 'Magento_Marketplace':</span><br><span class="hidden">[Progress: 159 / 421]</span><br><span class="text-info">Module 'Magento_MediaStorage':</span><br><span class="hidden">[Progress: 160 / 421]</span><br><span class="text-info">Module 'Magento_CatalogRule':</span><br><span class="hidden">[Progress: 161 / 421]</span><br><span class="text-info">Module 'Magento_Multishipping':</span><br><span class="hidden">[Progress: 162 / 421]</span><br><span class="text-info">Module 'Magento_ConfigurableProduct':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 163 / 421]</span><br><span class="text-info">Module 'Magento_Newsletter':</span><br><span class="hidden">[Progress: 164 / 421]</span><br><span class="text-info">Module 'Magento_OfflinePayments':</span><br><span class="hidden">[Progress: 165 / 421]</span><br><span class="text-info">Module 'Magento_SalesRule':</span><br><span class="hidden">[Progress: 166 / 421]</span><br><span class="text-info">Module 'Magento_PageCache':</span><br><span class="hidden">[Progress: 167 / 421]</span><br><span class="text-info">Module 'Magento_Captcha':</span><br><span class="hidden">[Progress: 168 / 421]</span><br><span class="text-info">Module 'Magento_Vault':</span><br><span class="hidden">[Progress: 169 / 421]</span><br><span class="text-info">Module 'Magento_Persistent':</span><br><span class="hidden">[Progress: 170 / 421]</span><br><span class="text-info">Module 'Magento_ProductAlert':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 171 / 421]</span><br><span class="text-info">Module 'Magento_ProductVideo':</span><br><span class="hidden">[Progress: 172 / 421]</span><br><span class="text-info">Module 'Magento_Authorizenet':</span><br><span class="hidden">[Progress: 173 / 421]</span><br><span class="text-info">Module 'Magento_Reports':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 174 / 421]</span><br><span class="text-info">Module 'Magento_RequireJs':</span><br><span class="hidden">[Progress: 175 / 421]</span><br><span class="text-info">Module 'Magento_Review':</span><br><span class="hidden">[Progress: 176 / 421]</span><br><span class="text-info">Module 'Magento_Rss':</span><br><span class="hidden">[Progress: 177 / 421]</span><br><span class="text-info">Module 'Magento_CatalogRuleConfigurable':</span><br><span class="hidden">[Progress: 178 / 421]</span><br><span class="text-info">Module 'Magento_Paypal':</span><br><span class="hidden">[Progress: 179 / 421]</span><br><span class="text-info">Module 'Magento_OfflineShipping':</span><br><span class="hidden">[Progress: 180 / 421]</span><br><span class="text-info">Module 'Magento_GoogleAdwords':</span><br><span class="hidden">[Progress: 181 / 421]</span><br><span class="text-info">Module 'Magento_SampleData':</span><br><span class="hidden">[Progress: 182 / 421]</span><br><span class="text-info">Module 'Magento_CatalogSearch':</span><br><span class="hidden">[Progress: 183 / 421]</span><br><span class="text-info">Module 'Magento_Integration':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 184 / 421]</span><br><span class="text-info">Module 'Magento_SendFriend':</span><br><span class="hidden">[Progress: 185 / 421]</span><br><span class="text-info">Module 'Magento_Shipping':</span><br><span class="hidden">[Progress: 186 / 421]</span><br><span class="text-info">Module 'Magento_Sitemap':</span><br><span class="hidden">[Progress: 187 / 421]</span><br><span class="text-info">Module 'Magento_NewRelicReporting':</span><br><span class="hidden">[Progress: 188 / 421]</span><br><span class="text-info">Module 'Magento_Swagger':</span><br><span class="hidden">[Progress: 189 / 421]</span><br><span class="text-info">Module 'Magento_Swatches':</span><br><span class="hidden">[Progress: 190 / 421]</span><br><span class="text-info">Module 'Magento_SwatchesLayeredNavigation':</span><br><span class="hidden">[Progress: 191 / 421]</span><br><span class="text-info">Module 'Magento_Tax':</span><br><span class="hidden">[Progress: 192 / 421]</span><br><span class="text-info">Module 'Magento_TaxImportExport':</span><br><span class="hidden">[Progress: 193 / 421]</span><br><span class="text-info">Module 'Magento_GiftMessage':</span><br><span class="hidden">[Progress: 194 / 421]</span><br><span class="text-info">Module 'Magento_Translation':</span><br><span class="hidden">[Progress: 195 / 421]</span><br><span class="text-info">Module 'Magento_GoogleOptimizer':</span><br><span class="hidden">[Progress: 196 / 421]</span><br><span class="text-info">Module 'Magento_Ups':</span><br><span class="hidden">[Progress: 197 / 421]</span><br><span class="text-info">Module 'Magento_UrlRewrite':</span><br><span class="hidden">[Progress: 198 / 421]</span><br><span class="text-info">Module 'Magento_EncryptionKey':</span><br><span class="hidden">[Progress: 199 / 421]</span><br><span class="text-info">Module 'Magento_Usps':</span><br><span class="hidden">[Progress: 200 / 421]</span><br><span class="text-info">Module 'Magento_Variable':</span><br><span class="hidden">[Progress: 201 / 421]</span><br><span class="text-info">Module 'Magento_Braintree':</span><br><span class="hidden">[Progress: 202 / 421]</span><br><span class="text-info">Module 'Magento_Version':</span><br><span class="hidden">[Progress: 203 / 421]</span><br><span class="text-info">Module 'Magento_Webapi':</span><br><span class="hidden">[Progress: 204 / 421]</span><br><span class="text-info">Module 'Magento_WebapiSecurity':</span><br><span class="hidden">[Progress: 205 / 421]</span><br><span class="text-info">Module 'Magento_Weee':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 206 / 421]</span><br><span class="text-info">Module 'Magento_CatalogWidget':</span><br><span class="hidden">[Progress: 207 / 421]</span><br><span class="text-info">Module 'Magento_Wishlist':</span><br><span class="text-info">Running schema recurring...</span><br><span class="hidden">[Progress: 208 / 421]</span><br><span class="hidden">[Progress: 209 / 421]</span><br><span class="text-info">Installing user configuration...</span><br>`

**Comment by didineedthis** [comment]
OK Some progress. i got this reply from my hosts if this is any help.

The -c specifies the path to your php.ini which you don't necessarily need if you haven't changed the .ini yourself. As for the cli, all the php versions/types you can call are located at /usr/bin/ and they are :

php         php5        php5-cgi    php5-cli    php-cgi     php-cli

So basically if you wish to call a .php file it would be like this:
/usr/bin/php5-cli -f /home/user/public_html/path/to/phpfile.php

I set them up like so

/usr/bin/php5-cli -f /home/xxxxxxxxx/public_html/mage21/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /home/xxxxxxxxx/public_html/mage21/var/log/magento.cron.log

/usr/bin/php5-cli -f /home/xxxxxxxxx/public_html/mage21/update/cron.php >> /home/xxxxxxxxx/public_html/mage21/var/log/update.cron.log

/usr/bin/php5-cli -f /home/xxxxxxxxx/public_html/mage21/bin/magento setup:cron:run >> /home/xxxxxxxxx/public_html/mage21/var/log/setup.cron.log

i have made a couple of test orders and made some changes to the products etc and the indexes are now getting updated so it looks like the problem is the missing update directory in 2.1

**Comment by didineedthis** [comment]
I have just updated the crons on my live site and they seem to be running too. i changed the stock levels and the indexes got updated even without the update folder! Do we really need the update folder or can i remove this cron all together?

/usr/bin/php5-cli -f /home/xxxxxxxxx/public_html/update/cron.php >> /home/xxxxxxxxx/public_html/var/log/update.cron.log

this is the error from update.cron.log before i changed the cron

No input file specified.
Status: 404 Not Found
Content-type: text/html; charset=UTF-8

this is the error from update.cron.log after i changed the update cron
No input file specified.
Could not open input file: /home/xxxxxxxx/public_html/update/cron.php

**Comment by ghost** [comment]
The update cron is used during upgrades and component updates.

**Comment by didineedthis** [comment]
Seeing now my crons are running
can i just upload the "update" folder? from
Magento-CE-2.1.0.zip to my live site?
will this cause problems?

**Comment by oserediuk** [comment]
@didineedthis if this is the only your issue, go ahead. If you find some issues in future, please, report here.

If this issue is resolved, can we close a ticket?

**Comment by didineedthis** [comment]
yes issue is now resolved thanks to wert2all . I did install and upgraded in a subfolder and once everything was ok i then moved to a live store,  and crons are running 100%
Thanks again for taking the time to help me resolve my issue.
Regards
