### ISSUE TITLE
Magento 2.1 Theme option not available in Store > Configuration > Design

### ISSUE THREAD

**Issue by sonimanthan228** [magento/magento2#5455]
I installed Magento 2.1 successfully.But When I go Store > Configuration > Design,theme option not avaiable.I tried pub deploy and flush cache and reindex command but theme option not available in Magento 2.1.

Regards,
Manthan Soni

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/5310

**Comment by tkacheva** [comment]
it's been moved to Content => Configuration
