### ISSUE TITLE
[2.1] New theme does not appear in Content > Design > Themes

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5456]
## Steps to reproduce
1. Create new theme with corresponding composer.json, registration.php and theme.xml
## Expected result
1. New theme appears in list in Content > Design > Themes
## Actual result
1. Theme does not appear
## 

I tried adding the same theme/code to an instance of Magento 2.0.7 and it appeared without problems.

Checked both Magento and PHP logs, but they don't show any errors related to this issue.

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/5310

**Comment by ghost** [comment]
Not a duplicate, this is a separate issue.

**Comment by quienti** [comment]
I have created my own custom theme on Magento 2.1.0 and It works well

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/16577941/39f1554e-4298-11e6-9def-5e4b35e33e2e.jpg)

I think you have a error somewhere...

**Comment by ghost** [comment]
Installing a fresh copy of 2.1 fixed the issue, I had upgraded from 2.0.7.

**Comment by Ctucker9233** [comment]
@rasmuswikman You might want to reopen this. If themes can't transfer, that is a critical oversight that @magento-team should look at in my opinion.

**Comment by hayabusajerry** [comment]
I have the same issue after upgrading from 2.0.8 to 2.1.0 
Is there a way to fix this without a fresh install? As I don't want to lose my data.

I also have nothing displaying in the orders or component manager, I guess it is possibly linked.

**Comment by magento-engcom-team** [comment]
@rasmuswikman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
