### ISSUE TITLE
Magento 2.1 admin session expired for logged in user  when another user login in admin

### ISSUE THREAD

**Issue by sonimanthan228** [magento/magento2#5457]
I installed magento 2.1 successfully.one arise issue in magento 2.1.suppose one user logged in admin it means that if another user try to login by another browser in admin and when second user logged in then first user who is logged in it will automatically logout and throw message "Someone logged into this account from another device or browser. Your current session is terminated."

**Comment by mhabou** [comment]
Yes this is for Security Proposed if one user login than other User Login with same id than your current session is terminated.

> To disable this feature go to "Stores > Configuration > Advance > Admin > Security" and change value of "Admin Account Sharing" to "Yes".

[Reference](http://magento.stackexchange.com/questions/124264/magento-2-1-admin-logged-in-issue-in-session)

**Comment by JDavidVR** [comment]
as @Dayssam said, this is a new feature, I tested it too, looks like a new amazing feature. This is not be considered as an issue, because you have the option to disable or enable it.

**Comment by pboisvert** [comment]
closing as non-issue.
