### ISSUE TITLE
Remove index.php from admin url

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#546]
Will be great remove index.php from admin url.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23469

**Comment by fernandoneto** [comment]
+1

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Remove-index-php-from-admin-url/idi-p/46790).
