### ISSUE TITLE
Cart Price Rule saving not work.

### ISSUE THREAD

**Issue by kalpeshchavada** [magento/magento2#5460]
## Steps to reproduce
1. Go to Marketing->Cart Price Rules->Add New Cart Price Rule
2. Fill All the form details and Click on Save or Save and Edit.
3. It will show this error in console of browser: form.js:144 Uncaught TypeError: $.validator.validateSingleElement is not a function
## Expected result
1. It should save that new rule
## Actual result
1. It showing this error in consol: form.js:144 Uncaught TypeError: $.validator.validateSingleElement is not a function

In Magento 2.1.0 version there are lots of bugs and issues. Please fix them ASAP.

Thank you

**Comment by tkacheva** [comment]
@guz-anton please check is this issue with js validation? I didn't manage to reproduce it

**Comment by kalpeshchavada** [comment]
@tkacheva I am sorry for this.

I was using Magento 2.0.7 and after that i upgraded version to 2.1.0

I can send you senp shot if you want.

THakn you

**Comment by MomotenkoNatalia** [comment]
@kalpeshchavada Yes please, it would be helpful!

**Comment by anton-huz** [comment]
Dear @kalpeshchavada could describe the way how you  _install_ and _upgrade_ Magento?
It's important to understand the root of issue.

**Comment by kalpeshchavada** [comment]
I have upgraded it by composer.

Any way I fixed issue.

Thanks

**Comment by toddliningerdesign** [comment]
@kalpeshchavada Can you please share what fixed it? I am experiencing the same problem.

**Comment by kalpeshchavada** [comment]
I have restore Magento 2's file.

And that was working fine.

Thanks

**Comment by neildavey** [comment]
I am having the same issue and I am using Magento 2.1.0 - when you save - the wheel goes round and then it just goes to the Dashboard
Does anyone have a fix for this?
