### ISSUE TITLE
Can't checkout with Braintree on Magento 2.1

### ISSUE THREAD

**Issue by ln8711** [magento/magento2#5462]
## Steps to reproduce
1. Install Magento 2.1
2. Configure and enable Braintree payment method
3. Create a new order in frontend (using Visa card)
## Expected result
1. The order should be created 
## Actual result
1. Error message: Unable to place order. Please try again later

**Comment by darragh1001** [comment]
If you enable cash on delivery do you also get this error? I am on Magento 2.1 but I get this error on all payment options

**Comment by YevSent** [comment]
@hoanglan87, could you attach debug log? Also, do you have any errors in browser console? Is fresh Magento installation or upgrade from some previous release?

**Comment by ln8711** [comment]
Hi, sorry for the delay, this is the request sent when place the order. I clean the debug log before add the product into cart and there is nothing in there.
![fbug1](https://cloud.githubusercontent.com/assets/3814503/16644421/0e0a8d8c-4447-11e6-881e-9406322aab70.png)

**Comment by YevSent** [comment]
Without any logs, we haven't ability to find the reason of your problem.
Could you enable xdebug and set break points in the [exception throwing](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83) for guest customers or in the [exception throwing](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71) for registered customers and post the `\Exception` message to this issue?

**Comment by Nerogee** [comment]
@hoanglan87 Hi, do you mind enable the paypal debug mode and check the webroot/var/log/debug.log file. My case is the invoice ID is always 000000001 when sending checkout data through paypal API. Just want to make sure I'm not alone.

**Comment by ln8711** [comment]
@Nerogee Paypal works for me, no issue with it.
@joni-jones look like the issue from the server, I reinstalled the OS and it works now, sorry for this problem, I'm closing this issue. Thanks for you help

**Comment by romeof1980** [comment]
hi there,
we've got the same issue on giustoacquisto.com:
1) 'Express Paypal' does not work (the Paypal pop-up opens then breaks before loading and closes unexpectedly) - THAT'S TURNED OUT TO BE A CORS ISSUE ON FIREFOX: we're working on it
2) 'Paypal through Braintree' does not work (on click on "Proceed on checkout" nothing happen)
3) on 'Credit Card (Braintree)' we experience the same issue as @hoanglan87 

IMPORTANT: cash on delivery works as expected
Note: we're not using Sandbox

Debugging; with regard to points 2) and 3) nothing appears in the Firebug's Error Console.

Magento ver. 2.1.0
Software version: 5.6.28-76.1 - Percona Server (GPL), Release 76.1, Revision 5759e76
Database client version: libmysql - 5.5.45-37.4

thanks,
romeo

**Comment by romeof1980** [comment]
hi there,
our issue can be related to #5511
it's a set up issue (Braintree/Paypal set up) and not a Magento issue.
We'll post a confirmation of that as soon as we complete the process.

thanks

**Comment by juanmrad** [comment]
I have the same problem and it is when the user is login.

**Comment by outpacdesigns** [comment]
I have same problem on magento 2.1 and this is mess: 
Unable to place order. Please try again later.SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES ()"
Can anyone help me ? 
See detail here: 

message
"Unable to place order. Please try again later.  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES ()"
trace
:
"#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('8d36c5ad3140660...', 'tan.dinh@blueco...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#1 /var/www/html/var/generation/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#2 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('8d36c5ad3140660...', 'tan.dinh@blueco...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#3 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)↵#4 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()↵#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#6 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵#7 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#8 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()↵#9 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))↵#10 {main}"

**Comment by tanvandinh** [comment]
I have the same problem on magento 2.1 and this is the message: 
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES ()"
can anyone help me? Detail error is below:
message:
"Unable to place order. Please try again later.SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES ()"
trace:
"#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('8d36c5ad3140660...', 'tan.dinh@blueco...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#1 /var/www/html/var/generation/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#2 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('8d36c5ad3140660...', 'tan.dinh@blueco...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#3 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)↵#4 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()↵#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#6 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵#7 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#8 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()↵#9 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))↵#10 {main}"

**Comment by kienmba** [comment]
I also encountered similar problems.
Please can you help me.
http://prntscr.com/c6saqw
Thank you so much :) :)

**Comment by romeof1980** [comment]
hi @ttkien175 ,
sure I can if you have set up correctly your Braintree account and you still get the error "unable to place order:please try again later". 
We just solved the issue deleting table prefixing and updating table sales_sequence_meta as detailed in #5902
Note that table prefixing can easily be edited from phpMyadmin (see zsd solution here: http://stackoverflow.com/questions/6404158/how-to-remove-a-prefix-name-from-every-table-name-in-a-mysql-database ).
Don't forget to edit env.php in order to modify the table prefixing.
Then you should delete static content (see here: http://magento.stackexchange.com/questions/94502/magento2-re-generate-css-file-in-pub-static-folder) and redeploy it for every language present in your shop.

that worked for us and fixed the issue.
Note: we experienced the issue in Production Mode after upgrading to 2.0.6 (issue persisted after another upgrade to 2.1.0)

**Comment by kienmba** [comment]
hi @romeof1980  thank you so much. :) :)

**Comment by tandih** [comment]
Hi there,

I also encountered similar problems before and root cause is when i try to create new store by script php and sales_sequence_\* table is not update after run reindex. You can fix by trigger event store_edit when create store by script. Hope this is helpful for some guys like me before.

**Comment by Weltpixel** [comment]
Hi,

Until now this are the measures that we took and seams to significantly improve the transaction decline rate. After applying all 3 solutions, we didn't receive any reports of other users not being able to checkout using Braintree on our Magento 2.1 store. 

Hope this helps:
https://support.weltpixel.com/hc/en-us/articles/115007753688-How-we-solved-Braintree-Magento-2-checkout-issues-with-our-Magento-2-1-store

Regards,
WeltPixel Team
