### ISSUE TITLE
Backend system configuration Design tab

### ISSUE THREAD

**Issue by hitumca** [magento/magento2#5466]
Steps to reproduce
--Magento 2.1.0
1. Login Backed admin part.
2. Click on Stores ->Configuration->General->Design tab
3. ...
![design tab issue](https://cloud.githubusercontent.com/assets/5170946/16581580/dc4f4ff6-42c7-11e6-9227-7ad942ce76dd.png)
## Expected result
1. Its should be Theme selection option there.

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/5455

**Comment by pboisvert** [comment]
Functionality for Design tab has been moved to Content > Configuration. Closing as a non-issue
