### ISSUE TITLE
base_url - something like app/etc/local.xml in M2?

### ISSUE THREAD

**Issue by samc2810** [magento/magento2#5468]
I asked this question in the community already but no one seems to know the solution. so I ll try my luck here:
Magento 1 had a very cool feature that one could configure store-config in the app/etc/local.xml instaed of the DB. e.g.

```
<stores>
        <admin>
            <web>
                <unsecure>
                    <base_url>http://admin.localhost.de/</base_url>
                </unsecure>
                <secure>
                    <base_url>http://admin.localhost.de/</base_url>
                </secure>
            </web>
        </admin>
        <de>
            <web>
                <unsecure>
                    <base_url>http://store-de.localhost.de/</base_url>
                </unsecure>
                <secure>
                    <base_url>http://store-de.localhost.de/</base_url>
                </secure>
            </web>
        </de>
        <en>
            <web>
                <unsecure>
                    <base_url>http://store-en.localhost.de/</base_url>
                </unsecure>
                <secure>
                    <base_url>http://store-en.localhost.de/</base_url>
                </secure>
            </web>
        </en>
</store>
```

is there any way to achieve this in M2? The reason is that we want to use the same DB for our dev and local systems. but, it seems that one can save the base_url in the db only. 

Thanx and Cheers
Sam

**Comment by samc2810** [comment]
is there no Magento-Developer who cares about answering?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/base-url-something-like-app-etc-local-xml-in-M2/idi-p/64464).
