### ISSUE TITLE
Add Js/Css in default.xml in custom module

### ISSUE THREAD

**Issue by SasiKiranK** [magento/magento2#5473]
Steps to reproduce
If i add  css/js file in default.xml in my custom module
< head >
        < css src="xx::css/xx.css" / >
        < script src="xx::js/xx.js" /  >
    < /head >
Expected result
new js file should render after the require js.
Actual result
but it is rendering before require js or at the top the head files

Thanks

**Comment by commcad** [comment]
In your default.xml, add this before/above your js/css:

**< script src="require js" / >**
< css src="xx::css/xx.css" / >
< script src="xx::js/xx.js" / >

That should force it. Works here anyway.

**Comment by zanilee** [comment]
Hi, @SasiKiranK!
Can't reproduce this behavior on the latest Magento2 develop
Do you still have this issue?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
