### ISSUE TITLE
Category image can be uploaded with the same name without error

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5474]
## Steps to reproduce
1. Magento 2.1 via download
2. Upload a category image in one category
3. Upload the same image in another category
## Expected result
1. There is an error shown saying that the same image is already uploaded
## Actual result
1. There is no error shown and the new picture with the same nam uploaded after the first picture is not taken into account.

**Comment by antboiko** [comment]
Hello @andidhouse , this works as expected. 

Could you please explain what is the reason to not allow using images with the same name?

Thanks.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
