### ISSUE TITLE
Update to 2.1.0 - no access to products and categories

### ISSUE THREAD

**Issue by narcisipopescu** [magento/magento2#5476]
Hi,

After upgrading to 2.1.0 when I need to either see catalog products, or access categories, or add a product to cart I get the following error:

Uncaught Error: You cannot apply bindings multiple times to the same element.

**Comment by taylordipentino** [comment]
I am having a similar issue. Not getting an error, but in the admin panel nothing in Products/\* or Sales/\* is loading. I'm just getting the perpetual spinning wheel icon after the page loads. This happened immediately after upgrading to 2.1 this morning.

**Comment by narcisipopescu** [comment]
Hi, the problem was solved by removing the browser cache.

But, there are other problems after the upgrade, i.e. stock is not
decreasing. If I buy a product in frontend, the stock is not decreasing at
all, having the option to decrease stock set to yes in bakend
configuration...

**Comment by kandrejevs** [comment]
with 200 000 products I get this error when trying to access admin/catalog/product.

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/var/www/topankovo-magento-2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 291

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 24576 bytes) in /usr/local/var/www/topankovo-magento-2/vendor/magento/framework/Session/SessionManager.php on line 139

**Comment by veloraven** [comment]
@narcisipopescu please create a new issue for the second problem, but be sure to check if similar issue is not created yet. Please provide description according to the template: with steps, actual result and expected result.

**Comment by veloraven** [comment]
@kandrejevs your problem seems to be different than the original one. Please check if an issue is already exists for the same problem as yours and if no, create a separate issue. Please provide description according to the template: with steps, actual result and expected result. Please also specify used version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
