### ISSUE TITLE
2.1 Cannot upload a .ico as favicon

### ISSUE THREAD

**Issue by matthijsleenen** [magento/magento2#5478]
## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Go to Content / Configuration
3. Edit Default theme
4. Go to Other Settings / HTML Head
5. Click on 'Upload' button for Favicon
6. Select .ico file
## Expected result
1. .Ico file can be uploaded
2. ...
## Actual result
1. Error message appears: "Attention, We don't recognize or support this file extension type.".

In /vendor/magento/module-config/Model/Config/Backend/Image/Favicon.php there is a method _getAllowedExtensions which allows the ico format.

Other filetypes like svg can be uploaded.

**Comment by antboiko** [comment]
Hi @matthijsleenen , thanks for reporting this issue. We've created internal ticket MAGETWO-55110 to fix it.

Thanks,
Anton.

**Comment by pratikkamani** [comment]
I have same issue ..
Can we direct replace this icon from FTP . and after compile magento it will effect ?

**Comment by lewisvoncken** [comment]
@antboiko 
Is it possible that this problem is not solved yet?

I found the same problem that not all of the Favicon formats are support. The supported formats in as quoted in de the description are ico, png, gif, jpg, jpeg, apng, svg but actually the supported formats are jpg jpeg gif png svg . The problem can be solved by changing line 70 in module-theme/view/adminhtml/ui_component/design_config_form.xml from 
`<item name="allowedExtensions" xsi:type="string">jpg jpeg gif png svg</item>` 
to 
`<item name="allowedExtensions" xsi:type="string">ico jpg jpeg gif png svg apng</item>` .

**Comment by antboiko** [comment]
Hi @matthijsleenen  @lewisvoncken ,
This issue was fixed and delivered to the develop branch. c9c4882
Please check if the issue is still reproducible for you on the develop branch
Thank you.

**Comment by lewisvoncken** [comment]
@antboiko I installed M2 Enterprise but I got the error there. Is it possible that Enterprise can be udated with this bugfix?

**Comment by cuiyang000** [comment]
Can confirm, and @lewisvoncken 's solution works!

**Comment by noodlenood** [comment]
@lewisvoncken 
I'm having the same issue, the ico file is not being recognized.
I am also a noob: could you tell me where to exactly enter "line 70"?

Thank you,

**Comment by lewisvoncken** [comment]
@noodlenood,

You can find it in the develop branch on github
https://github.com/magento/magento2/commit/c9c4882dea9544cb867d76c5d962ef5de6ccf122

_Met vriendelijke groet / Best regards,_

Lewis Voncken
Developer
Arthur van Schendelstraat 650
030 - 8200 238
www.experius.nl

**Comment by keyurshah** [comment]
what is the best way to merge changes from a develop branch into the current master branch? 

or do you just use the entire develop branch?

thanks.

**Comment by timbaker1991** [comment]
Is there any estimate of which CE version this would be released in?

**Comment by GuidoHub** [comment]
Problem is still there in release 2.1.3

**Comment by slackerzz** [comment]
6 months, no fix :confused:

**Comment by springimport** [comment]
I had the same problem.

For solve a problem you can [Add custom favicons manually](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/favicon.html#add-custom-favicons-manually) from your theme or can use my module with a bugfix.

https://packagist.org/packages/springimport/magento2-module-favicon-bugfix

**Comment by lano-vargas** [comment]
lewisvoncken Sugestion worked for me Thank's. Yet no updates in the latest release magento 2.1.4.
Does that means if I update magento to 2.1.5 in the very near future the fix I applied will be overwritten? 👎 
J

**Comment by lewisvoncken** [comment]
Hello Juliano,

Great to hear but it is only a temporary fix and it will be overwritten
with the next update.

*Met vriendelijke groet / Best regards,*


Lewis Voncken
Developer
Arthur van Schendelstraat 650
030 - 8200 238
www.experius.nl

**Comment by robbanl** [comment]
It has been almost 10 month ago since this was reported. Still not fixed. Ping @antboiko

**Comment by simonsaysforcepush** [comment]
This is STILL broken in 2.1.7... Why? There's no reason for this. This is basic functionality, as .ico is the standard accepted format.

**Comment by korostii** [comment]
@veloraven, could you please an official response regarding.. what takes so long? 
The issue is reportedly "fixed", what are the steps for a merchant in order to apply this fix to his Magento instance (if it's not in any of the versions released, as of yet)?

**Comment by lingwooc** [comment]
For the love of god! Can you guys actually FIX anything? @antboiko

**Comment by hostep** [comment]
@lingwooc: this fix is available on the `2.1.8-preview` branch, so you'll get the fix in the next release :)
See: https://github.com/magento/magento2/commit/406c81796c938a76abed39bf5e5a9dda9218e534

**Comment by lingwooc** [comment]
At least that's something. Its not really ok it took over a year to add 3 characters to a release though.

**Comment by JerryLosey** [comment]
Holy crap this is awful.  A year to fix favicon without even giving current users a fix?  When will 2.1.8 release?  ...Probably a year from now.

**Comment by scottsb** [comment]
@JerryLosey, the 2.1.x series is releasing fairly regularly: about once a month.

**Comment by slackerzz** [comment]
Better late than never! :smile:

**Comment by allininfosystems** [comment]
I want to upload logo from admin panel in svg format. I have changed the given your code in that file but it showing a message "Disallowed file type.". Please help me. What I do for fix it

**Comment by hostep** [comment]
@allininfosystems: uploading of svg files was removed in Magento 2.0.16 and 2.1.9 due to the possibility that svg files can have embedded malicious code, read more over here: https://magento.com/security/patches/magento-2016-and-219-security-update (search for APPSEC-1673).

You can take a look [over here](https://github.com/magento/magento2/commit/2c952e7e620e743049771321d333a74ec9116d57) (search for 'svg') how it got removed and try to restore that functionality again, but please make sure you double check all your uploaded svg files if the code contents contains nothing malicious.

**Comment by allininfosystems** [comment]
I am using Magento2.2.2 version and I have checked function _getAllowedExtensions in Logo.php inside core directory there is not available 'svg'. In Magento2.2.2 we can upload svg format header logo from admin or not can you please clarify it?

**Comment by lewisvoncken** [comment]
@allininfosystems 

It is not possible any more to upload svg files for security reasons.

**Comment by lano-vargas** [comment]
@allininfosystems you will have to update from your theme just place an image named logo.svg inside image/ folder.
More info cam be found here:http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html#theme_logo
