### ISSUE TITLE
Can't edit products after csv import [Magento 2.1.0]

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5480]
## Steps to reproduce
1. I am using Magento 2.1.0 (after update form Magento 2.0.7 using Setup Wizard + MDVA-532 patch).
2. Before the update I had products created by import from csv file.
3. After Magento update, I downloaded the same file from "System > Import History" and tried to import it (once without any change and once with changed names).
4. Now I tried to see and edit products - "Products > Inventory: Catalog".

This is the first line from my csv file:

``` csv
"sku","store_view_code","attribute_set_code","product_type","categories","product_websites","name","description","short_description","weight","product_online","tax_class_name","visibility","price","url_key","base_image","base_image_label","display_product_options_in","additional_attributes","qty","use_config_min_qty","use_config_backorders","use_config_min_sale_qty","use_config_max_sale_qty","is_in_stock","use_config_notify_stock_qty","use_config_manage_stock","use_config_qty_increments","use_config_enable_qty_inc","is_decimal_divided","website_id","additional_images","additional_image_labels","meta_title","meta_keywords","meta_description"
```
## Expected result
1. Products list should be accessible - "Products > Inventory: Catalog".
## Actual result
1. Products are not loaded and this is displayed: 

> Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1" already exists.
1. Same error is in system.log: 

> [date time] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1" already exists. [] []
1. Products are re-indexed, updated and displayed on the front end. 
2. There are no errors in the browser console.

---

I imported same file with changed "Import Behavior" to "Replace" and "Products > Inventory: Catalog" worked fine. After this I imported same file one more time with "Import Behavior" set to "Add/Update" and it worked too.

**Comment by kristjan-h** [comment]
See #5418 for a temporary fix.

**Comment by shiftedreality** [comment]
Hi @RG-1 

Thank you for reporting this issue.
I have created internal ticket MAGETWO-58075 to fix this issue.

**Comment by shiftedreality** [comment]
This issue will be fixed in scope of https://github.com/magento/magento2/issues/5418
Closed as duplicate.
