### ISSUE TITLE
content ->design->configuration faulty

### ISSUE THREAD

**Issue by cadoworld** [magento/magento2#5481]
Magento Communauty Edition 2.1

Just trying to create a new design theme but ...
Missing the design, got instead search engine robots 

content ->design->configuration 

![screenshot 2](https://cloud.githubusercontent.com/assets/20308662/16601964/592cfcfe-4308-11e6-9612-5240397d37a0.png)

**Comment by acidreian666** [comment]
The new Magento 2.1 the Design has been relocated to
backend-> Content-> Configuration.

**Comment by pboisvert** [comment]
please refer to documentation http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html

closing since this is not a report of an issue
