### ISSUE TITLE
Attribute mapping to specific product types is missing

### ISSUE THREAD

**Issue by rcbharath** [magento/magento2#5482]
## Steps to reproduce
1. Create attribute in magento admin
## Expected result
1. Need to know how to map this attribute to specific product types (as like in magento 1.x)
## Actual result
1. No option available to map

**Comment by veloraven** [comment]
@rcbharath if this issue still actual please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
