### ISSUE TITLE
After creating custom attribute from the admin side, i can't able to choose the empty value while adding the product.

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#5485]
## Steps to reproduce
1. Creates Custom Attribute.
2. Added custom values and selected first option as default.
## Expected result
1. While adding the product, i want to assign the empty value for the created attribute.
## Actual result
1. After saving the product, the custom attribute takes the default value that was selected when we created the custom attribute.

For ex: Attribute -> Color.
Attribute Values: blue, black, etc.
i have set blue as default color.

While create new product, i haven't assigned the color attribute. But it takes the default color after saving the product.

**Comment by antboiko** [comment]
Hello @sasilinux , thanks for reporting. We already have internal ticket MAGETWO-50123 to fix this issue. 

Best,
Anton.

**Comment by dcabrejas** [comment]
@antboiko Hello, any update on when this will be resolved ? Thanks, Diego.

**Comment by sasilinux** [comment]
@antboiko Hello, Please update us once the problem will be resolved? we are waiting for the update. Thanks, Sasikumar

**Comment by okorshenko** [comment]
MAGETWO-57144 has been delivered with 2.1.8

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
The issue is already fixed in 2.2.0
