### ISSUE TITLE
Custom Attribute frontend display not working in Magento 2.1

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#5486]
## Steps to reproduce
1. After assigning the custom attribute in the admin side.
2. I have get the data and display it in frontend product view page.
3. In magento 2.0.x getAttributeText('color') is working fine. But Magento 2.1 it's not working. 
## Expected result
1. I need to display the chosen value. for ex: Color: Blue
## Actual result
1. It shows empty result.

**Comment by veloraven** [comment]
@sasilinux thank you for your report.
Could you please provide more detailed steps?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by sasilinux** [comment]
ok thanks. resolved this issue.

**Comment by sasilinux** [comment]
Need update on this ticket #5485

**Comment by wavegirl23** [comment]
Hi! Can you please share how you solved the issue?
