### ISSUE TITLE
Magento 2.0.6 - cart is not functional

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5487]
We are using Magento 2.0.6 on a staging Environment. Mode is set to Developer mode.

Adding items to the cart in general is functional, but as soon as a customer clicks on "To the cart" in the minicart, the page only loads 2 header elements and then aborts. 

Does anyone else is having this problem? Is it maybe a unique problem on my side? If no, whats the next Version that fixes this bug?

**Comment by antboiko** [comment]
Hi @grasdaggel , I cannot reproduce the issue on 2.0.7 version following your description. 
- I added 5 items to the cart
- clicked on mini cart and all 5 items are displayed correctly
- clicked "View and Edit Cart" and went to Shopping Cart page 
- all 5 items are loaded and displayed there

Could you provide detailed steps?

Thanks,
Anton.

**Comment by grasdaggel** [comment]
Dear @antboiko. I did the very same, except that when I click on View and Edit Cart-Link I receive a page with loaded footer and header, but no content in between.

When I click on "Checkout", I only receive the a white page with a loaded logo and our first, right positioned, navigation, no content loaded after that point.

**Comment by antboiko** [comment]
@grasdaggel Do you have any additional preconditions or other errors in the browser console, exception or debug log?

**Comment by grasdaggel** [comment]
Console:

```
JQMIGRATE: Logging is active
jquery-migrate.js:41 JQMIGRATE: jQuery.browser is deprecated
jquery-migrate.js:43 console.trace()migrateWarn @ jquery-migrate.js:43get @ jquery-migrate.js:58(anonymous function) @ jquery.ba-hashchange.min.js:9(anonymous function) @ jquery.ba-hashchange.min.js:9(anonymous function) @ jquery.ba-hashchange.min.js:9
```

No other error output.

Last call in error_log (obviously not cart-related):

```
[05-Jul-2016 13:17:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /home/reisebil/public_html/206/app/design/frontend/Atropos/kunth/Magento_Catalog/templates/product/price/final_price.phtml:54
Stack trace:
#0 /home/reisebil/public_html/206/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 /home/reisebil/public_html/206/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Pricing\Render\FinalPriceBox), '/home/reisebil/...', Array)
#2 /home/reisebil/public_html/206/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/reisebil/...')
#3 /home/reisebil/public_html/206/vendor/magento/framework/Pricing/Render/PriceBox.php(65): Magento\Framework\View\Element\Template->_toHtml()
#4 /home/reisebil/public_html/206/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php(31): Magento\Framework\Pricing\Render\PriceBox->_toHtml()
#5 /home/reisebil/public_html/206/ in /home/reisebil/public_html/206/app/design/frontend/Atropos/kunth/Magento_Catalog/templates/product/price/final_price.phtml on line 54
[06-Jul-2016 09:07:03 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 199245824 bytes) in /home/reisebil/public_html/206/app/design/frontend/Atropos/kunth/Magento_Catalog/templates/product/list/items.phtml on line 212
[06-Jul-2016 09:07:15 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 199245824 bytes) in /home/reisebil/public_html/206/app/design/frontend/Atropos/kunth/Magento_Catalog/templates/product/list/items.phtml on line 212
[06-Jul-2016 12:04:21 UTC] PHP Parse error:  syntax error, unexpected '<' in /home/reisebil/public_html/206/app/design/frontend/Atropos/kunth/Magento_LayeredNavigation/templates/layer/filter.phtml on line 39

```

Anything else you need?

**Comment by antboiko** [comment]
@grasdaggel , I cannot reproduce this issue.

You could disable all third party extensions, update your version of Magento (2.0.7 ). Do composer install/update. Clear Magento cache.
If scenario will be reproducing again please let me know.

Thanks,
Anton.

**Comment by grasdaggel** [comment]
The problem was a fault in my CSS. :/ 

Sorry for wasting your time.

**Comment by antboiko** [comment]
Hi @grasdaggel , thanks for the update, I'm glad the issue is solved.

Best,
Anton.
