### ISSUE TITLE
Wording: Please re-run Magento compile command - Incorrect command name

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#5488]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. After all Modules are installed, a message is shown in green letters on the last line. Read that message.

The message says:

> Please re-run Magento compile command

It can be greatly improved by removing the inaccuracy as there is no such command named "`compile`". The command name is "`setup:di:compile`".

This should be trivial to fix.

**Comment by grasdaggel** [comment]
Isn't the setup:static-content:deploy command meant with that? For developer envs its not mandatory to run di:compile each time you setup:upgrade.

**Comment by tkn98** [comment]
@grasdaggel: The command named "`setup:static-content:deploy`" does not contain the word _"compile"_, so by wording alone already I would assume it is not meant by that.

**Comment by didineedthis** [comment]
No need to run "bin/magento setup:di:compile" if your developing your site just run the upgrade and  "bin/magento setup:static-content:deploy" then run "bin/magento indexer:reindex" you only have to decompile when you set production mode

**Comment by grasdaggel** [comment]
So we are even that there is no need to run di:compile on developer environments, right? Maybe Devs can add a check which mode is set, and if its Dev, hide this message (since it doesn't do anything useful on Dev Mode), while its necessary to do so on live systems.

**Comment by didineedthis** [comment]
run this to check what mode you are in
bin/magento deploy:mode:show

you will more than likely be in Default mode.

then set either developer or production

1.bin/magento deploy:mode:set production
2. bin/magento deploy:mode:set developer

Once you leave default mode there is no going back to it.

**Comment by tkn98** [comment]
It's all fine what you guys write here, but I'm more concerned about the message given and that it is not showing the concrete command intended to run. The discussion shows, that there are diverse scenarios in which the one or other command, also additionally, needs to be (not) run (at all). But please do not derail this report which is about the message missing the concrete command name.

**Comment by tkn98** [comment]
And just a short note: `setup:di:compile` performs checks on your di configuration. I guess this is useful in development mode, too from time to time.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Wording-Please-re-run-Magento-compile-command-Incorrect-command/idi-p/45257).
