### ISSUE TITLE
\Magento\Catalog\Model\Product\ReservedAttributeList should not be a dependency for \Magento\Eav\Model\Entity\Attribute

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#5489]
The class `\Magento\Eav\Model\Entity\Attribute` has as a dependency an instance of `\Magento\Catalog\Model\Product\ReservedAttributeList`.  
This is wrong in my opinion.  
Besides the fact that it introduces a circular dependency because EAV module now depends on the Catalog module and the Catalog module already depends on the EAV module.  
But this circular dependency is not the main problem here (others might disagree).  
The main problem is that the Catalog Product is not the only EAV entity in the application.  
There are also Categories, Customers and Customer addresses.  
This means that when I add an attribute for these entities Magento checks if there is a getter for that attribute name in the product model class.  
This also restricts me when creating my own EAV entity to have attributes like `price` (and others).  

I think the dependecy `\Magento\Catalog\Model\Product\ReservedAttributeList` should be replace with an interface `ReservedAttributeListInterface` that should reside in the EAV module with a single method `isReservedAttribute` and I can specify via `di.xml` the implementation used as dependency for each class that extends `\Magento\Eav\Model\Entity\Attribute`.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-Catalog-Model-Product-ReservedAttributeList-should-not/idi-p/48452).
