### ISSUE TITLE
Translatable or changable URLs / named routes

### ISSUE THREAD

**Issue by FiveDigital** [magento/magento2#549]
Right now, there is not possibility to translate (or change) the routes generated for the frontend. The route to the basket is always /checkout/cart and it would be nice if we could configure or change the routes on a store view base. So that we can have /warenkorb in the German store view and /basket in the English one. Other frameworks like Symfony take the route in the templates and look up how to generate the URL for the frontend in the config (see http://symfony.com/doc/current/book/routing.html). Perhaps this could be a way for Magento too. The route name for the checkout could remain /checkout/cart but it resolves to whatever I have configured for in my store view and have a fallback to a default URL.

Are there any plans to change the routing / URL behavior in Magento 2? If not, perhaps you might think of taking it into your backlog.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23631

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Translatable-or-changable-URLs-named-routes/idi-p/46240).
