### ISSUE TITLE
Mobile navigation submenus need two clicks to open

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#5495]
## Steps to reproduce
1. Open the site on a mobile device
2. Click on the Women menu item
3. Click on the Men menu item
4. Click on the Men menu item again
## Expected result
1. Men opens on the first click (step 3), Women closes simultaneously
## Actual result
1. Women closes at the first click (step 3)
2. Men opens at the second click (step 4)
## Expected fix
1. Functionality as in the expected result
2. Clicking on an open menu item will still close it

**Comment by ravibhalodia** [comment]
Above solution doesn't worked. I tried in 2.1 version, however user still need to click 2 times to view sub categories. Any workaround for this issue?

**Comment by kanduvisla** [comment]
Why is this issue closed without any comment? I am curious about if this is intended behavior or if there is any workaround for this. I agree with the original issue that the result is not what you would expect.
