### ISSUE TITLE
[2.1] Get stuck in Products > Catalog

### ISSUE THREAD

**Issue by Krapulat** [magento/magento2#5500]
I'm trying to access to Products > Catalog inside Magento Administration and I can't. It gets stuck. It shows nothing. No error neither.

I attach two screenshots. The second one is after 20 seconds. It gets stuck in that part.

![screen shot 2016-07-06 at 15 48 43](https://cloud.githubusercontent.com/assets/4441564/16620079/5f9457a2-4391-11e6-9c21-64390a80fe16.png)
![screen shot 2016-07-06 at 15 49 33](https://cloud.githubusercontent.com/assets/4441564/16620080/5fd77ef6-4391-11e6-8bca-fac05bad84e7.png)

**Comment by quienti** [comment]
I had this problem after updated Magento 2.0.7 to 2.1.0
And my problem was because my custom modules added "Mass Action " .

And the system to add actions are different between the 2 versions .

I see you outside of Magento modules , checking that they are updated for Magento 2.1

**Comment by shanevbg** [comment]
I had this same problem,
Seems problem was fixed for me by 
going under configuration/developer and
Minifying Javascript files

**Comment by andimov** [comment]
@Krapulat 
Thanks for reporting!
Sorry for the late reply.
Do you have any update for this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
