### ISSUE TITLE
Changing Attribute Sets clears value of attributes [Magento 2.1.0]

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5505]
## Steps to reproduce
1. Magento 2.1.0
2. Go to Stores > Attribute: Product and create two attributes (type: dropdown or swatches, scope: global, just admin values: e.g. alpha and beta, no default value) (e.g. A-1 and A-2)
3. Go to Stores > Attribute: Attribute Sets and create two new sets (e.g. S-1 and S-2)
4. Edit S-1 and S-2 > Assign A-1 and place it under sku > Create Group > Assign A-2 and place it in created Group
5. Create a product using S-1 > set A-1 and A-2 to alpha
6. Edit product > change attributes set to S-2
## Expected result
1. A-1 and A-2 should be still set to alpha
## Actual result
1. A-1 is untouched and still alpha, but A-2 is now empty

---
## Steps to reproduce
1. Edit values of created attributes A-1 and A-2 > add value for the storefront (e.g. Alpha Front and Beta Front) (I got just one storefront)
2. Go to product edit page
3. Notice the value of A-1 and A-2. It should be admin value
4. Change attributes set
## Expected result
1. A-1 and A-2 should still have admin value
## Actual result
1. A-1 and A-2 are now empty
2. From dropdown you can choose value, but storefront value

**Comment by Tristan-N** [comment]
I have the same problem. Also the loadingscreen isn't stopping. 
It says Price is a required field. Even when I enter a number there, select another Attributeset in the dropdown it clears the value, keeps loading and gives an error. 

![schermafbeelding 2016-07-07 om 15 13 24](https://cloud.githubusercontent.com/assets/19165453/16654313/870259aa-4455-11e6-9ec9-71d5bab9716e.png)

**Comment by Tristan-N** [comment]
@RG-1 
Is it possible that you used a data migration tool and the attribute set you are selecting is migrated from Magento 1? 
I did the following: 
Check if the attribute set Default has the same structure as the set you are trying to select. If not, that's your problem. 

Create a new attribute set based on the Default set that Magento 2 delivers and update that new one as you would like it. Update all products in the backend (I did that with SQL).

`SELECT entity_id as product_id, sku FROM eav_attribute_set WHERE attribute_id = value_here`

`UPDATE eav_attribute_set SET attribute_id=old_value_here WHERE attribute_id=new_value_here`

**Comment by real34** [comment]
@Tristan-N we are facing a kind of similar issues with attributes added to an attribute set migrated from Magento 1 with the data migration tool (v2.1.3).
Do you know where we could find further information (issues, SO answers, forums...) about the known problems with migrated attribute sets?

**Comment by Tristan-N** [comment]
@real34 I don't have actual links to other documentation about it. I stopped searching because the things I suggested in my comment worked for me, but similar issues are found here: https://github.com/magento/magento2/issues/7825, https://github.com/magento/magento2/issues/5350, https://github.com/magento/magento2/issues/5999 and https://github.com/magento/magento2/issues/7579.

Hope this helps!

**Comment by real34** [comment]
Thanks a lot for the pointers!

**Comment by Andrii-Deineha** [comment]
Unfortunately, I could not reproduce the issue as you described it. Please provide more information about your Magento installation, including the versions of PHP and MySQL you are using as well as the web server.

**Comment by kzozulya** [comment]
Hi all,
I have the same issue as Topic Started wrote (exactly the same)
We have a Migration_Default Attribute set.
Solution for me (may be project specified solution but maybe useful for someone else):
In Admin Panel relocate attribute  quantity_and_stock status to Migration Prices attribute group (group with code advanced-pricing):
https://monosnap.com/file/0H3dl34HyBXlI2tDqtvBtg6NlLIRuI
https://monosnap.com/file/M9Iv1g7neSKqMdRZAbl3SGNpLSEA9S
