### ISSUE TITLE
Fresh install Magento 2.1.0 from Softaculous - Unable login to admin site

### ISSUE THREAD

**Issue by kimmanwky** [magento/magento2#5506]
I have no problem accessing the homepage. However, this is the error message show when i type the admin username and password.

> There has been an error processing your request
> 
> Warning: is_dir(): open_basedir restriction in effect. File(/etc/pki/tls/certs) is not within the allowed path(s): (/home/myhairse:/usr/lib/php:/usr/php4/lib/php:/usr/local/lib/php:/usr/local/php4/lib/php:/tmp) in /home/myhairse/public_html/staging2/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914
> 
> Error log record number: 631161798195

**Comment by acidreian666** [comment]
@nomood89 that's Softaculous issue. If your looking to run local easy install of magento2. See https://bitnami.com/stack/magento they only have 2.0.7 I believe but if you go to system upgrade to 2.1 it works well. But this is no means a way to use magento 2 for production because of bitnami is very limited as a real server.

**Comment by Ctucker9233** [comment]
@nomood89 I remember having a similar issue. If I recall, softaculous defaults to admin123 for the backend url. For some reason, Magento didn't like it. I changed it to something else and then everything worked fine.

**Comment by andimov** [comment]
@nomood89
Do you have any updates for this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
