### ISSUE TITLE
Magento homepage shows PHP warning after upgrading php from 5.5.9 to 7.0.8

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#5507]
1. I upgraded php 5.5.9 to 7.0.8 before upgrading Magento from 2.0.6 to 2.1.0.

Magento was originally installed via composer create project, and upgrading to 2.1.0 was made also via composer.
1. After upgrading php version and making sure all extensions are correctly installed, I tried to enter my homepage and got this message:

> Magento supports PHP 5.6, 7.0.2, and 7.0.6 or later. Please read Magento System Requirements. 

Same happens when trying to access the back end.

To check the php version installed, run `php --version`:

> PHP 7.0.8-3+deb.sury.org~trusty+1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.8-3+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies

**Comment by stamster** [comment]
Well, you can't be obsolete but you can't be too latest either if you want to use Magento2. xD

You can try to modify bootstrap(.php) where Magento check PHP version and to see whenever it will work w/o issues with your PHP 7.0.8 stack.

```
// PHP version validation 
if (version_compare(phpversion(), '5.5.0', '<') === true) 
```

**Comment by stamster** [comment]
I just deployed fresh instance with Magento 2.1.0. 
Even in CLI it complains:
Magento supports PHP 5.6, 7.0.2, and 7.0.6 or later.

I'm running PHP 7.0.4, which is default Ubuntu 16.04 LTS repo version. This is just plain stupid. What exactly is the problem in those specific versions, they're all based on PHP 7.0.x stack (using SemVer), so no API changes are introduced!

**Comment by stamster** [comment]
Official page states: 

> PHP
> 7.0.2–7.0.6 except for 7.0.5 (supported by Magento version 2.0.1 and later only)
> 
> There is a known PHP issue that affects our code compiler when using PHP 7.0.5. We recommend you not use PHP 7.0.5; instead, use PHP 7.0.2–7.0.4 or 7.0.6.

So the only troubles are specific to 7.0.5 only. 

Bootstrap does not seem to follow these requirements: 

```
/* PHP version validation */
//if (!defined('PHP_VERSION_ID') || !(PHP_VERSION_ID >= 50600 && PHP_VERSION_ID < 50700 || PHP_VERSION_ID === 70002 || PHP_VERSION_ID >= 70006)) {
```

Now I wonder how you @lgarridoj have hit the wall with your setup since this must return true PHP_VERSION_ID >= 70006 with your ID 70008.

On the other hand, composer.json has following dependency: 

```
"require": {
        "php": "~5.6.0|7.0.2|~7.0.6",
```

xD

Just change bootstrap.php and composer.json and it won't complain anymore.

**Comment by hostep** [comment]
@stamster: check discussion over here, it should work on PHP 7.0.4, the Magento guys will fix the issues in an upcoming release: https://github.com/magento/magento2/issues/5131

**Comment by lgarridoj** [comment]
@stamster My composer.json file does not include that code:

```
"require": {
        "php": "~5.6.0|7.0.2|~7.0.6",
```

**Comment by jibrandlr** [comment]
@stamster I changed composer.json but the result is the same. And bootstrap.php does not need to be changed since the condition is true already.

**Comment by stamster** [comment]
@lgarridoj try to `var_dump` contents of that check, it will return false perhaps?

**Comment by hostep** [comment]
@lgarridoj: my guess is that your php-cli version is 7.0.8, but the version which your webserver uses is probably still 5.5.9. Maybe it's best to contact your hosting company about this. This doesn't seem to be a bug in Magento itself.

**Comment by andimov** [comment]
@lgarridoj 
Thank you for reporting!
Did you check your php version in web?

**Comment by jibrandlr** [comment]
@andimov I didn't check the php version in web. Since it's a small store I rebuilt the server using PHP 7.0.8 from the very beginning.

**Comment by oserediuk** [comment]
Hello @lgarridoj ! Please, try to check in web which PHP version do you use.

**Comment by jibrandlr** [comment]
@oserediuk Currently my installation is working fine since I created a new server and installed PHP 7.0.8.
The problem was on the previous server when I tried to upgrade php version from 5.5.9 to 7.0.8. On that server I confirm the php-cli version was 7.0.8, but I didn't check the version which the webserver used, maybe it was still 5.5.9

**Comment by andimov** [comment]
@lgarridoj
Thank you! If you do not mind, I close this issue.  Please feel free to reopen if you need.
