### ISSUE TITLE
The order confirmation email was not sent and orders does not show up under sales-orders. 

### ISSUE THREAD

**Issue by Tellfjord** [magento/magento2#5508]
## Steps to reproduce
1. Upgrade från 2.02 to Magento 2.1 using composer
2. Add configuration in backend, add some products, set up server with cron Jobs and all the req. 
3. ...
## Expected result
1. A working magento store with standard functionallity add products to cart, register and so on works,
## Actual result
1. A magento store that doesent add orders under sales--Orders i can see the new orders in the dashboard, if i click on one of them i can see all the details, and in the top it says order number and (The order confirmation email was not sent. Click send Order e-mail but no email is sent, if i add a comment on the order and check notify costumer by email an email i sent with the ordercomment. My store is able to send mail but not the order email when a order is cerated. And the orders does not show up under Sales -- Orders. 

Anyone who can help me?

**Comment by Tellfjord** [comment]
Managed to get the latest orders to show up under Sales - Orders by changing the Asynchronous indexing from Enable to Disable under Stores - Advanced - Developer. Now I can see the orders in the list (finaly). But the problem with Order Mail Not sent is still there. Anyone else with this problem?

**Comment by Tellfjord** [comment]
No one else with the problem that order confirmation e-mail not is sent? All the other e-mail comunication works great.

**Comment by oshmyheliuk** [comment]
Hi @Tellfjord
Does this issue still exist? 
I can't reproduce it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by vasilii-b** [comment]
@veloraven  oppened new [issue](https://github.com/magento/magento2/issues/7289) regarding the same problem.
