### ISSUE TITLE
Swatch attributes is not sorted by position

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#5510]
## Steps to reproduce
1. Install Magento 2.1
2. Add configurable product have swatch attributes
3. Set attribute position in Store > Attribute > Product
## Expected result

Swatch attribute is sorted by position
## Actual result

The position in jsonConfig is wrong and Swatch attribute is not sorted.
![2016-07-07_8-27-03](https://cloud.githubusercontent.com/assets/1607243/16639791/05009d14-441d-11e6-8a13-872f00a77b5b.jpg)

**Comment by phuc128t** [comment]
As a fix, go to file  app/code/Magento/ConfigurableProduct/Model/ConfigurableAttributeData.php line 38 change to `'position' => $productAttribute->getPosition(),`

**Comment by magenizr** [comment]
@erictrn Still working 9 years later
