### ISSUE TITLE
TypeError: Braintree.checkout.paypal is undefined in magento 2.1 Braintree.checkout.paypal.initAuthFlow()

### ISSUE THREAD

**Issue by viken-tops** [magento/magento2#5511]
steps to reproduce for magento 2.1 braintree paypal configuration.
enviroment : production
payment action : authorize
public key
private key
merchant ID
Enable PayPal through Braintree
Vault enabled : no
Country Specific Credit Card Types  
Country     Allowed Credit Card Types   Action
PayPal through Braintree : 
Payment Action : authorize
Payment from Applicable Countries : all
Require Customer's Billing Address : no
Allow to Edit Shipping Address Entered During Checkout on PayPal Side : yes

TypeError: Braintree.checkout.paypal is undefined in magento 2.1 Braintree.checkout.paypal.initAuthFlow()

**Comment by YevSent** [comment]
Hi @viken-tops, thanks for reporting. Could you reproduce this issue on the latest develop?

**Comment by YevSent** [comment]
**UPD** On a  fresh installation of Magento 2.1 can't reproduce your issue, the place order via Braintree and Braintree PayPal works fine. Do you have any additional preconditions or another errors in the browser console, exception or debug log?

**Comment by viken-tops** [comment]
hi  joni-jones,
thanks for yr response. actually i just came to know that it's working in sandbox environment but not in production. on production getting error like paypal is not enabled braintree.2.17.6.min.js in console.

i am wondering why this happen.

**Comment by asemenenko** [comment]
@viken-tops it seems that you need to activate PayPal on your Brantree account, see doc https://articles.braintreepayments.com/guides/paypal/setup-guide

**Comment by YevSent** [comment]
Closing this issue due to no response, please reopen when you have an update.
