### ISSUE TITLE
Product > Product in Websites > "Changes have been made to this Section" Pencil Icon always present

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5512]
Ever since upgrading to 2.1.0 all my Products have this Pencil Icon present on the "Product in Websites" option

**Comment by antboiko** [comment]
Hi @blizam , thanks for reporting this issue. We've created internal ticket MAGETWO-55157.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@blizam, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by blizam** [comment]
sweet!

**Comment by C4rter** [comment]
Can somebody show me the commit that fixed this? We are having a similar issue with a custom tab and don't know the reason or how to fix it.
