### ISSUE TITLE
Rest api - PUT /V1/customers/password api used to get password reset link in email not working

### ISSUE THREAD

**Issue by qwerty7869** [magento/magento2#5513]
## Steps to reproduce
1. Use the api to get password reset link in email using admin token key.
## Expected result
1. Email should be received to reset password.
## Actual result
1. Getting below response on using api
   {
   "message": "No such entity with %fieldName = %fieldValue, %field2Name = %field2Value",
   "parameters": {
     "fieldName": "email",
     "fieldValue": "xyz@xyz.com",
     "field2Name": "websiteId",
     "field2Value": 0
   }
   }

**Comment by veloraven** [comment]
@qwerty7869 

Thank you for your report.
But I would like to clarify one detail: which website is your customer assigned to? As "0" - is id for Admin website. 
Please check that you use correct "websiteId" value. If customer is attached to Main Website it probably has id = 1.

**Comment by qwerty7869** [comment]
@veloraven Thanks for the reply. 
I tried with website id 1 and that problem is resolved but now not getting which value to feed in Template variable of api. Kindly help for this issue.

**Comment by veloraven** [comment]
@qwerty7869 You can use '/V1/store/websites' REST API command to get the list of all your websites with their ids.
Also without using API, you can open an existing website in backend (Stores -> Settings -> All Stores -> Website) and you will the its id in the URL.
Please let me know if you have any additional questions with this issue.

**Comment by andimov** [comment]
@qwerty7869
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by RUjmiak** [comment]
@andimov And where is solution? What should be in template? Where is documentation to it? What is email type? In request is template but in error is field email type.

Try to help people not to close as much tickets as it is possible

**Comment by RUjmiak** [comment]
@qwerty7869 this is working

{
  "email": "email@email.com",
  "template": "email_reset",
  "websiteId": 1
}

@andimov template - "email_reset" is not real template which you can create in admin. It is constant which I found in AccountManagenet.php.. Great work guys...

**Comment by kartikasodariya17** [comment]
Also, I have facing this issue. can you please help me to resolve the issue.

**Comment by degaray** [comment]
I have the same issue

**Comment by ivan2304** [comment]
working in me
{
   "email": "email@gmail.com",
   "template": "email_reset",
   "websiteId":  1
}

after debug error because can`t sending email

**Comment by thunderwin** [comment]
3 years, the bug still here?  ,  You can only use email_reset.
