### ISSUE TITLE
Owl Carousel and Flex slider JS stops

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#5521]
Hi,

First load site work fine all slider working on second load every thing fine suddenly all sliders stops working then on reload everything get back to normal then after 2 or 3 load ajax get stopped

i.e sometimes load slider sometime not sometime loads ajax sometime not weird issue

Console error when everything get stopped

```

> (index):550 Uncaught TypeError: $(...).owlCarousel is not a function(anonymous function) @ (index):550fire @ jquery.js:3099fireWith @ jquery.js:3211ready @ jquery.js:3423completed @ jquery.js:3453

> jquery-migrate.js:21 JQMIGRATE: Logging is active


> (index):421 Uncaught TypeError: $(...).flexslider is not a function(anonymous function) @ (index):421fire @ jquery.js:3099add @ jquery.js:3145jQuery.fn.ready @ jquery.js:3379(anonymous function) @ (index):414execCb @ require.js:1650check @ require.js:866(anonymous function) @ require.js:1113(anonymous function) @ require.js:132(anonymous function) @ require.js:1156each @ require.js:57emit @ require.js:1155check @ require.js:917enable @ require.js:1143init @ require.js:774callGetModule @ require.js:1170completeLoad @ require.js:1564onScriptLoad @ require.js:1671


> dataPost.js:13 Uncaught TypeError: $.widget is not a function


```

Same issue on default Magento ajax stop after some load

**Comment by mrkhoa99** [comment]
It's better if you post your question on http://magento.stackexchange.com/

**Comment by Igloczek** [comment]
Remember that everything related to RequireJS works asynchronously, so probably you miss that and depending on load times everything might load in proper order or not.

BTW. Also you may be able to try get DOM elements, before DOM is ready - be aware it's common issue within devs new in async world 😉

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by ednacool** [comment]
May be i am unable to explain properly that is the issue i am referencing which i am getting on fronthand sometimes JS loads sometime returns error. If possible i will also try to reference you my nginix configuration but it seems to be the same configuration in my website 

#5583
