### ISSUE TITLE
Error in Magento Checkout

### ISSUE THREAD

**Issue by Rheikan** [magento/magento2#5523]
## Steps to reproduce

1.install a module of Payment 
2. add a product to cart
3. put the information of Checkout
## Expected result
1. Appear Payment section(the gif of loading stay infinitly)
## Actual result
1. When push "NEXT" y page CheckOut the gif of loading stay infinitly
2. IN THE LOGS : [2016-07-07 13:48:22] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_14fe68b6700db5ef57a5b4237dfe75f45: Please correct the XML data and try again.  [] []

Please can HelpMe? the XML has validate whit PhpStorm but, the problem persist.

**Comment by andimov** [comment]
@Rheikan 
Thanks for reporting!
Sorry for a late reply.
Do you have any updates for this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
