### ISSUE TITLE
Minicart does not synchronise across multiple devices

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5524]
## Steps to reproduce
1. Create a customer account
2. Log in on Browser 1 with your newly created customer account
3. Add an item to your basket
4. Log in on Browser 2 with the above created customer account  
5. Add an item to your basket in Browser 2
6. Refresh Browser 1
7. Observe the Minicart in Browser 1
## Expected result
1. Minicart show correct items and totals on all browser on all devices when logged in with the same customer account when adding or removing cart items on **any** of the devices on all platforms **without** logging out and logging in to your customer account.
## Actual result
1. Minicart does not update on the new location/browser without logging out and logging back in
## Observations
1. Please note that Minicart will show correct results on the new location/browser if you log out and log back in on your customer acoount
2. Please note that the Cart/Checkout pages will always show correct data, only the Minicart being affected
## Magento Versions

Magento 2.0+, Magento 2.1 and **develop** branch

**Comment by andimov** [comment]
@alexgifts 
Thank you for reporting!
I've created an internal ticket for this issue - MAGETWO-56539

**Comment by ghost** [comment]
@alexgifts, thanks for reporting this!

@andimov, is there any update on the status of this issue? My development team have come across this issue and we're keen to know if we're going to need to resolve it ourselves or if there is a patch that can be provided.

Thanks,
David.

**Comment by magento-engcom-team** [comment]
@alexgifts, thank you for your report.
The issue is already fixed in 2.2.0
