### ISSUE TITLE
Remove Feature Request: Do not autopopulate Meta Description field with Product Name

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5525]
The Meta Description field gets autopopulated by the Product Name field AND the Product Description field... more often than not this will create a messy Meta Description field at best.

Honestly, I think ALL auto population of all the meta fields should be removed... when you're duplicating products it gets messy and when you go back and forth and make edits in the Product Name and Descriptions fields (prior to saving/creating) it gets messy.

I get wanting to set it for people people who don't look at it/don't care... but most people in the eCom space care very much... and people that care are going to want to set very custom values anyways and it's super annoying to "compete" with your software for what values you want in a field

**Comment by antboiko** [comment]
Hello @blizam , you can easily remove this template by navigating Stores > Configuration > Catalog > Product Fields Auto-Generation section. http://docs.magento.com/m2/ce/user_guide/catalog/product-fields-autogenerated.html

I'm closing this one as it's not a technical issue. Please feel free to reopen if you have any additional questions.

Thanks,
Anton.
