### ISSUE TITLE
sales_rule_form is not defined on attempt to select category for cart price rule condition

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#5526]
## Steps to reproduce
1. Log in to admin panel
2. Go to Marketing -> "Cart Price Rules"
3. Click "Add New Rule" button
4. Expand actions fieldset
5. Under "Apply the rule only to cart items matching the following conditions" add "Category" condition
6. Open category chooser
7. Select any category (see js error in console)
8. Click Apply icon
## Expected result
1. No js errors.
2. Category is added to condition
## Actual result
1. "Uncaught ReferenceError: sales_rule_form is not defined" js error message
2. Selected Category is not added to condition

**Comment by dthampy** [comment]
@sivaschenko , thank you for your bug report. An internal jira Ticket(MAGETWO-55184) is created.

**Comment by Andranikbaghdasaryan** [comment]
Does this problem already solved? @dthampy

**Comment by miakusha** [comment]
Issue was fixed. Closed.
