### ISSUE TITLE
COPYING.txt contains placeholder text

### ISSUE THREAD

**Issue by navarr** [magento/magento2#5528]
Line 7:

> &lt;insert file name of the MEE license&gt;

Should be replaced with the file name of the Magento2 Enterprise Edition License.

**Comment by veloraven** [comment]
@navarr thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by navarr** [comment]
branch develop, Line 7...

https://github.com/magento/magento2/blob/develop/COPYING.txt#L7

**Comment by veloraven** [comment]
@navarr internal ticket MAGETWO-56532 was created and linked with this issue.
