### ISSUE TITLE
Store View reverts to default after any action.

### ISSUE THREAD

**Issue by djahnsag** [magento/magento2#5531]
## Steps to reproduce
1. Install Magento 2 (we have version 2.0.7, because 2.1.0 doesn't work due to an exception when running the static-content deploy command!!)
2. Create two Store Views (we have one in English and one in German [default])
3. Go to the shop front and switch the store view => the store view changes (in our case, the store appears in English)
4. Navigate to any other page => the store view reverts back to default (in our case, the store appears in German)
## Expected result

Magento remembers the store view and serves it for every request.
## Actual result

After every request, the store view reverts back to default.

**Comment by stamster** [comment]
We have exact same setup, and switch does work, i.e. language choice is respected until user switches again.
Do you use Varnish and Apache? We only use nginx.

**Comment by djahnsag** [comment]
It's a WAMP setup on my local dev machine and LAMP on our QA server. Both have the same problem.

**Comment by gewaechshaus** [comment]
Same here... Feel free to test here: https://www.makerdise.com

**Comment by stamster** [comment]
@gewaechshaus You're using sub-domain for 'eu' (English) store. That's another story. 
When I switch on your site, this is set via `Set-Cookie` HTTP header in server response:

```
domain=www.makerdise.com store=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0;
```

Store is `deleted`, check your configuration, since I doubt you have named your store view `deleted`?

On my setup, this is what I got from nginx while switching from default local language to English:

```
domain=mydomain.com store=en; expires=Mon, 17-Jul-2017 22:11:19 GMT; 
```

That cookie is present through my client session.

**Comment by veloraven** [comment]
@djahnsag thank you for your report.
Could you please provide more detailed steps and more information about settings you have made? As I was not able to reproduce this issue.
Please also provide information about your environment: versions of PHP, MySQL and web server.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by djahnsag** [comment]
Like I mentioned above, the dev machine is a WAMP stack (XAMPP), server is LAMP: ~~I am currently unable to SSH to it right now, so I can't give you more details on that right now.~~

Linux version 2.6.32-042stab112.15 (root@kbuild-rh6-x64.eng.sw.ru) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue Oct 20 17:22:56 MSK 2015
Php 7
Server version: Apache/2.4.6
mysql  Ver 15.1 Distrib 5.5.50-MariaDB

We use megamenu and our theme is based on the Smartwave Porto theme.

What I noticed is: when you switch to a language, the URL has "?___store=en&___from_store=default" appended to it. Every other link doesn't have that, so it switches back to default.

@andimov can you please reopen the issue with the new information?
