### ISSUE TITLE
Untranslatable strings in Admin -> Products -> Inventory -> Catalog

### ISSUE THREAD

**Issue by mcjwsk** [magento/magento2#5532]
I translate **Magento 2.1.0 (stable)** using the Crowdin service and I noticed there are some untranslatable strings (or the strings are not available to translate at Crowdin). 
Please see the following screenshots to get more details.

![2016-07-08_0915](https://cloud.githubusercontent.com/assets/284649/16680262/aaaf5d60-44ed-11e6-8f07-af85f06a1456.png)
![2016-07-08_0916](https://cloud.githubusercontent.com/assets/284649/16680260/aaac0bec-44ed-11e6-8111-3c22b7a8bf26.png)
![2016-07-08_0919](https://cloud.githubusercontent.com/assets/284649/16680259/aaabe752-44ed-11e6-97b4-f5d43fa9e656.png)
![2016-07-08_0921](https://cloud.githubusercontent.com/assets/284649/16680261/aaaf2fd4-44ed-11e6-89af-8e98f4572ac8.png)

**Comment by ideirj** [comment]
put this lines in your translate file:
"Simple Product","Simple Product",module,Magento_Catalog
"Configurable Product","Configurable Product",module,Magento_Catalog
"Grouped Product","Grouped Product",module,Magento_Catalog
"Virtual Product","Virtual Product",module,Magento_Catalog
"Bundle Product","Bundle Product",module,Magento_Catalog
"Downloadable Product","Downloadable Product",module,Magento_Catalog
"Apply Filters","Apply Filters",module,Magento_Ui

these are works...

but
Save View As...
from
to
Columns
Save all changes (right arrow alt text, when you want to save the custom view)

are really problems...

**Comment by magento-engcom-team** [comment]
@DariuszMaciejewski, thank you for your report.
We've created internal ticket(s) MAGETWO-82402 to track progress on the issue.

**Comment by ilnytskyi** [comment]
#distributed-cd

**Comment by ilnytskyi** [comment]
This problem is actual for only for 2.1 it is fixed in further versions.
The real issue is in the incorrect generations of js-translations.json (is does not contain necessary lines) and solved for 2.2 in
https://github.com/magento/magento2/issues/3771
