### ISSUE TITLE
Create New Order fails with Interface Locale German/Germany

### ISSUE THREAD

**Issue by aunts** [magento/magento2#5533]
## Steps to reproduce
1. Magento ver. 2.0.7
2. Create new User with Interface Locale = German/Germany
3. Login in with new User
4. Umsatz -> Bestellungen -> Neue Bestellung erstellen
5. Click on "Neuen Kunden hinzufügen" or on existing customer directly
6. Nothing is happening

Expected result
Step 6, new page to create new order is opened

Actual result
Nothing is happening

I can reproduce the problem with fresh Magento Installation Version 2.0.2 AND 2.0.7.

Thanks for help!

**Comment by mktudock** [comment]
I can confirm this with 2.1.

**Comment by veloraven** [comment]
@aunts thank you for your report.
Could you please provide more detailed steps?
1. Which translations do you use and how do you add it?
2. Was it clear Magento install or upgrade from previous version?

**Comment by mktudock** [comment]
I don't know about @aunts but we have the same problem and use the German/Germany locale from https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE and we upgraded from 2.0.7.

The translation was added via composer and set for the admin user. All admin users using an english locale can create new orders, those using the german locale can not. Switching to an english locale "solves" the issue.

**Comment by antboiko** [comment]
Hi @aunts  @mktudock . Can you please provide us with detailed step for reproducing this issue?

Thanks,
Anton.

**Comment by mktudock** [comment]
1. Install Magento 2.1 with PHP7 [although 2.0.x also has this issue]
2. Install splendidinternet/mage2-locale-de-de via Composer
3. Switch admin locale to de_de
4. Try to create an order via Admin (Umsatz -> Bestellungen -> Neue Bestellung erstellen)
5. Click on "Neuen Kunden hinzufügen" or on existing customer directly
6. Nothing is happening

**Comment by dthampy** [comment]
Thanks for the bug report. Internal jira ticket MAGETWO-59962

**Comment by dthampy** [comment]
#6855

**Comment by dthampy** [comment]
Similar to [#6855](url)

**Comment by SerhiyShkolyarenko** [comment]
Fix is delivered to the develop branch in scope of MAGETWO-59962. Closing the issue.
