### ISSUE TITLE
[2.1] Invalid block type "Magento\Braintree\Block\Paypal\Button"

### ISSUE THREAD

**Issue by acharrex** [magento/magento2#5534]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add a product to the cart
3. Go to the shopping cart
## Expected result
1. Shopping cart page shown without any error
## Actual result
1. Error message appears: "Invalid block type: Magento\Braintree\Block\Paypal\Button"

**Comment by acharrex** [comment]
Fix:
Rename the folder "vendor/magento/module-braintree/Block/**PayPal**" by "vendor/magento/module-braintree/Block/**Paypal**".

**Comment by YevSent** [comment]
The same problem as in #5535.
The Magento repo contains the correct folder name https://github.com/magento/magento2/tree/develop/app/code/Magento/Braintree/Block. Try to clear your vendor directory and composer cache, and run compose update again.
