### ISSUE TITLE
[2.1] Invalid block type "Magento\Braintree\Block\Adminhtml\Form\Field\CountryCreditCard"

### ISSUE THREAD

**Issue by acharrex** [magento/magento2#5535]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to the Magento admin panel
3. Go to the menu "Stores > Configuration > Sales > Payment Methods"
## Expected result
1. Page shown without any error
## Actual result
1. Error message appears: "Invalid block type "Magento\Braintree\Block\Adminhtml\Form\Field\CountryCreditCard"

**Comment by acharrex** [comment]
Fix:

Rename "vendor/magento/module-braintree/Block/Adminhtml/Form/Field/**Countrycreditcard.php**" by "vendor/magento/module-braintree/Block/Adminhtml/Form/Field/**CountryCreditCard.php**"

The same for "vendor/magento/module-braintree/Block/Adminhtml/Form/Field/**Cctypes.php**" to rename by "vendor/magento/module-braintree/Block/Adminhtml/Form/Field/**CcTypes.php**"

**Comment by YevSent** [comment]
Hi @acharrex, looks like a problem in your vendor directory because Magento repo contains correct files: https://github.com/magento/magento2/tree/develop/app/code/Magento/Braintree/Block/Adminhtml/Form/Field also for 2.1 composer package, that files are also have correct names.

**Comment by ahofstetter** [comment]
I have this exact same issue/error. Updated from 2.0.7 to 2.1.0 using composer. Guess I will  download the files from the repo and add them manually. Thanks

**Comment by ovekeryk** [comment]
I have the same issue too.

**Comment by YevSent** [comment]
Try to remove this package from vendor directory, clear composer cache and update.

**Comment by mikelevy300** [comment]
I had this issue as well after running the update via composer.  The root cause that got my working copy not right was Windows' pretty path.  My dev environment is on Windows 10 and it didn't register the name change in the update.  A manual name change was all it took to resolve things.

**Comment by YevSent** [comment]
@mikelevy300, please, read [Installation requirements](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/prereq-overview.html), the Windows doesn't support as OS.
