### ISSUE TITLE
Backorders Magento 2.1

### ISSUE THREAD

**Issue by philipburrell** [magento/magento2#5538]
With inventory qty =0 
and Backorders = Allow qty Below 0 and Notify customer

If stock status - Out of stock - Then the product does not appear on the front end.
If stock status - In stock - The product is available to buy but the customer is not notified/warned.

**Comment by antboiko** [comment]
Hi @philipburrell , I cannot reproduce the issue. When I click "View and Edit Cart" I see the message saying "We don't have as many "Test Product" as you requested, but we'll back order the remaining 1."
Please Flush the Cache and let me know if you still have this issue appearing.

Thanks,
Anton.

**Comment by philipburrell** [comment]
The problem is if you add the item to the cart and go straight to checkout, you do not see this.
You will only see this if you go to view edit cart first.

**Comment by andimov** [comment]
@philipburrell 
Thank you reporting!
Do you have any updates for this issue? 
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by EGrasso87** [comment]
Hi 
I have this same issue as @philipburrell  reported
news?
many thanks

**Comment by george-vlahakis** [comment]
This is still an issue in 2.1.7
The customer can order item above stock but no message is shown when adding to cart and if they go directly to checkout they will never see it.

Is there a patch at least?

**Comment by Kimmagento** [comment]
The same issue persists in ver 2.1.9 so I think it should not be closed.

**Comment by Kimmagento** [comment]
Preconditions :
Magento ver 2.1.9.

Steps to reproduce :
set product quantity to 0
set product 'in stock'
set Backorders to 'allow qty below 0 and notify customer'

Actual result : 
product can be added to cart - no message is shown
customer goes to checkout - no message is shown

backorder message is only shown if customer edits cart

Expected result : show backorder message to customer upon clicking add to cart or/and in the mini-cart so that message has been shown before customer can place order.

**Comment by Kimmagento** [comment]
Please reopen

**Comment by andimov** [comment]
@Kimmagento 
Could you please create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)?
