### ISSUE TITLE
Layout catalog_category_view can't call children block or container in template

### ISSUE THREAD

**Issue by kubjnit** [magento/magento2#5539]
<referenceBlock name="category.products.list">
            <container name="test">
            <block class="Magento\Catalog\Block\Product\ListProduct\Test" name="product.info.test" as="product.info.test" template="Module_Test::product/view/test.phtml"/>
            </container>
        </referenceBlock>

**Comment by Ctucker9233** [comment]
@kubjnit I had a similar issue where the template couldn't call the catalog navigation. Given that you haven't describe the issue in detail, what magento version are you using? Did you upgrade from a previous version?

**Comment by kubjnit** [comment]
@Ctucker9233 I used Magento version 2.0.9. I try reference to Block "category.products.list" to add custom block but in template no support calling renderer children blocks.

**Comment by Ctucker9233** [comment]
@kubjnit Then it's different than the problem I was having. In my issue it had to do with Magento core code in 2.1.0.

**Comment by veloraven** [comment]
@kubjnit thank you for your report.
Please provide description according to the template: with steps, actual result and expected result.

**Comment by andimov** [comment]
@kubjnit 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
