### ISSUE TITLE
I can´t import product in magento 2.1. Always says "General system exception happened"

### ISSUE THREAD

**Issue by enriquetarazona** [magento/magento2#5540]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a csv file with the template columns.
3. Get a "General system exception happened"
4. Export sample template and import it.
5. Get a "General system exception happened"
## Expected result
1. Import Succesfully
## Actual result
1. Error message appears: General system exception happened".

**Comment by acidreian666** [comment]
@enriquetarazona 
- Step one is to make sure your template columns match that sample .csv export that you get under System/Import-Export
- Step Two make sure your saving your CSV as MS-Dos (.csv) format if using Excel or open with Notepad+ and check encoding UTF-8-BOM.

If your still having an issue could be your not using correct Field Seperators.

**Comment by andimov** [comment]
@enriquetarazona 
Do you have any updates for this issue?
Did you check steps as @acidreian666 advised?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by spontaneousdinesh** [comment]
I had this and after doing random 1 line imports, I found it was some characters in the descriptions. I had to open the csv in Notepad++ and go Encoding> Convert to UTF-8-BOM then save it as a copy. Went straight on then.

**Comment by shyang292** [comment]
@spontaneousdinesh your method works for me.
