### ISSUE TITLE
Layered Navigation - setting `filterable (no results)` programatically doesn't work

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#5543]
This case is connected with that one:
https://github.com/magento/magento2/issues/3209

1) I am working on Magento 2.1
2) I add attribute and its options - it's multiselect. 
If I set `filterable => 2` it value doesn't change - it is ok because I add some options later. 
3) After adding options I want to update attribute programatically and set it `filterable (no results)`, so I next version of module in UpgradeData i add line `$eavSetup->updateAttribute(Product::ENTITY, 'supported_software', 'is_filterable', 2);`. What is the most strange it works - it changes the value so it can be visible in admin - but in frontend layered navigation doesn't appear for this attribute. Value in db changes.
4) If I change value for `filterable` from adminhtml insetad of doing it programatically it WORKS!

**Comment by magento-engcom-team** [comment]
@bartek9007 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@bartek9007 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
