### ISSUE TITLE
memory_get_peak_usage() with Magento 2 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5545]
How to use memory_get_peak_usage() with Magento 2 queries or is there other ways for debugging?

**For example:**
            $attributeSet = $this->scopeConfig->getValue('..');
            $attributes = $this->_objectManager->create('Magento\Eav\Api\AttributeManagementInterface')->getAttributes($attributeSet);

Issue in stackexchange.com: http://magento.stackexchange.com/questions/124781/magento-2-attribute-set-return-empty-array

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
