### ISSUE TITLE
Cannot create invoices after upgrading

### ISSUE THREAD

**Issue by Jacob-Affinity** [magento/magento2#5546]
## Steps to reproduce
1. Install Magento 2.0.0.
2. Upgrade to Magento 2.1.0
3. Try to create a new invoice in admin via sales > Orders > [order] > Invoice > Submit Invoice
## Expected result
1. A new invoice to be created
## Actual result
1. Error saying "We can't save the invoice right now."
   ![magento2_missing_columns_pretty](https://cloud.githubusercontent.com/assets/17255597/16693250/3d8cc81e-452c-11e6-8ce2-03cbcb0591ed.png)
2. Removing the last catch(\Exception) in [Magento\Sales\Controller\Adminhtml\Order\Invoice\Save](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Save.php) reveals a more detailed error: 
   ![magento2_missing_columns](https://cloud.githubusercontent.com/assets/17255597/16693269/616c01be-452c-11e6-9b97-7c2df5508a9f.png)
3. The base_grand_total column is not present in sales_invoice_grid
## The problem
1. base_grand_total was added to Magento\Sales\Setup\InstallSchema [after Magento2 was released](https://github.com/magento/magento2/commit/2bdb35eb2d90ef8f89ac54c7c3f7469c14190934?diff=split).
2. InstallSchema files are not run when upgrading Magento
3. People installing Magento from scratch today will have base_grand_total in sales_invoice_grid, but people who upgraded Magento from lower versions will not.
## The solution
1. Given that base_grand_total is an upgrade to the Schema, it should be in  Magento\Sales\Setup\UpgradeSchema so that people upgrading can get it.
2. In general InstallSchema files should never be edited once included in a release.

**Comment by hostep** [comment]
This has been reported at least 3 times before, please first try searching for an issue before creating a new one :)

Duplicate: https://github.com/magento/magento2/issues/4785

**Comment by mauromm** [comment]
Hi @Jacob-Affinity, I solved it here: https://github.com/magento/magento2/issues/5324

**Comment by Jacob-Affinity** [comment]
What's the rationale for putting upgrade tasks in InstallShema in the first place?

**Comment by maderlock** [comment]
@hostep, sadly it'll probably continue to be reported until it's patched. 2.1.1 anyone?

**Comment by navarr** [comment]
According to #4785 the fix is in the develop branch, so this ticket should be closed.

**Comment by JacobDrummond** [comment]
Thanks @navarr, [your're right](https://github.com/magento/magento2/commit/7f5b6443c8aad774bb3389fca9c4d372aaa3f1af?diff=split). Fix is in develop, and #5546 can be closed.

**Comment by andimov** [comment]
I'm closing this issue as fixed and duplicate. Please feel free to reopen if you need.
