### ISSUE TITLE
Switch to BCMath

### ISSUE THREAD

**Issue by CodeMonkey90** [magento/magento2#555]
Currently, Magento uses floats to represent prices internally. This is a very bad design decision, as binary floating point numbers cannot accurately represent decimal values, which means you have to manually correct the resulting loss of precision after complex calculations. This process is error-prone. Fortunately, the BCMath extension, which is enabled by default, provides arbitrary-precision decimal math.

I'd suggest that Magento moves from floating point calculations to BCMath calculations in the long term. Since PHP converts numeric strings to floats automatically when necessary, the code can be slowly migrated on a module-per-module basis.

**Comment by czettnersandor** [comment]
I have an issue when implementing a finance extension which would normally require precision floats as the 3rd party system is very picky about it. As BCMath is not a Magento dependency, we can't use it and we have float conversion issues.

Now, we are converting to strings, which is not the best solution and bad for my sleep.

This works as expected for rounding down to 2 digits:

`$amount += intval((string) ($price * 100)) / 100;`

This not for certain values:

`floor($price * 100) / 100;`
