### ISSUE TITLE
Incorrect language on swatch error

### ISSUE THREAD

**Issue by Sanfam** [magento/magento2#5550]
While attempting to add a new swatch, I received the following error:

> Admin is a required field in the each row

This is a bit odd and should instead read

> Admin is a required field in each row"

**Comment by dthampy** [comment]
MAGETWO-55230 has been created

**Comment by magento-engcom-team** [comment]
@Sanfam, thank you for your report.
We've created internal ticket(s) MAGETWO-55230 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @Sanfam. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1117 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - a975698726721488ab14c5f6a03b517f2a690f00

The fix will be available with the upcoming patch release.
