### ISSUE TITLE
REST routing precedence

### ISSUE THREAD

**Issue by nickmarx12345678** [magento/magento2#5553]
Would like some clarification with regards to how URL matching on the rest API occurs on URL's that developers create in their routes.xml

For example if:
route1 = `GET /V1/myResource/:customerId`
route2 = `GET /V1/myResource/:customerId/subResource`

It's not clear if requesting the url `/V1/myResource/12345/subResource` will map to route1 with a customerId parameter of `12345/subResource` or if it will map to route2 with a customerId parameter of `12345`

Similar permutations of this would be helpful to know as well such as:
route1 = `GET /V1/myResource/:customerId`
route2 = `GET /V1/myResource/subResource`
route3 = `GET /V1/myResource/subResource/:subResourceId`

It's unclear which will be called with what argument if I request `/V1/myResource/subResource`

**Comment by nickmarx12345678** [comment]
Alternatively, it would be very helpful to add some sort of debug logging indicating what method is being routed to for a given rest request url

**Comment by choukalos** [comment]
Please move your question to the Forum or Stack Exchange.

@piotrekkaminski suggestion to improve debugging.

**Comment by nickmarx12345678** [comment]
@choukalos -- where would be the correct place to request improvements to the official documentation?

**Comment by mbrinton01** [comment]
@tanberry Please advise

**Comment by tanberry** [comment]
Thanks @mbrinton01 .  Hi @nickmarx12345678 , please do share your thoughts and suggestions (and maybe even a PR with some contributions!) to our docs. For more info, see http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing_docs.html. 

You can also click on the "Edit this page on GitHUb" link at the top of every page in devdocs.magento.com (excluding auto-generated Swagger docs).

And, @keharper  is our API writer, hit him up, please. ;-)

**Comment by mbrinton01** [comment]
@nickmarx12345678 please let us know if this issue can be closed or you need additional support.

**Comment by nickmarx12345678** [comment]
Close it
