### ISSUE TITLE
Admin Timeout

### ISSUE THREAD

**Issue by epadmin** [magento/magento2#5557]
## Steps to reproduce

While working on adding categories in the admin panel, Magento times out without notification or giving ability to extend.  When saving new categories after adding all the information, the login page comes up and none of the information is saved.
## Expected result

Expect a notification prior to timing out while updating/adding information.  If you are logged in and try to save, there should be a way to restore the information you entered if you have to log in again, whether it is a setting allowing the information to be cached so you can go back after logging in or temporarily saving it while you re-authenticate and then committing the change.  At the very least there should be a reminder that says you are about to be logged out.
## Actual result

Try to save information after entering the required info to setup a new category is resulting in the information being lost because it goes to a login page instead of saving the data.   Presumably this is a timeout issue

**Comment by springimport** [comment]
For temporary solution, increase the Admin Session Lifetime.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-Timeout/idi-p/45216).
