### ISSUE TITLE
can`t login into magento admin

### ISSUE THREAD

**Issue by johanDev19** [magento/magento2#5559]
hi,

i cant login into magento admin after install magento 2.1... can someone help me?
not error show.. the login admin page just reload and ask me for username and password over and over again

**Comment by commcad** [comment]
Try: close your browser and restart it. The session should kill itself doing that.

I had the same problem a few days ago when I've set "Use Web Server Rewrites" to yes. Problem goes away once you've restarted the browser (in my case anyway). If not then have a look at your rewrite code. Wild guess mate, not Magento Inc affiliated here

e.g. Use Web Server Rewrites in: M2 Admin > Stores > Configuration > Web > Search Engine Optimization

**Comment by Crossmotion** [comment]
In magento 1.9 its a known bug. You have to remove the session cookie from your browser to fix this.
I think I have also had this with Magento 2 a few times already.

**Comment by andimov** [comment]
@johanDev19 
Thank you for reporting!
Do you have any updates for this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
