### ISSUE TITLE
Disable minicart popup

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5560]
I didn't want to ask this hear as its technically not an issue that needs addressing, but after waiting for someone to chime in on stackexchange I figured there was nothing to lose. 
~
Is there any documentation or known methods to disable the popup you recieve when clicking mini cart link? I just need a way that still allows the cart to be updated when adding a product via ajax, but on click sends you directly to the cart page without giving you the popup. Any help is appreciated.

**Comment by ghost** [comment]
Found the option to disable right in the configuration. Was over thinking this.

**Comment by totneschap** [comment]
Where abouts is the option in the config?

**Comment by ghost** [comment]
Maybe it is fair to share your solution? Others would be delighted to give answer too...

**Comment by ghost** [comment]
Stores > Configuration > Sales > Checkout > Shopping Cart Sidebar
--
Change Display Shopping Cart Sidebar to No

**Comment by nicoflemming** [comment]
mmd
