### ISSUE TITLE
Tax Calculation seems buggy

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5562]
We are using Magento 2.0.6. We have all prices incl. tax, and so do we create them. 

**Our settings in the backend.**
<img width="847" alt="bildschirmfoto 2016-07-10 um 04 15 38" src="https://cloud.githubusercontent.com/assets/13021579/16711324/9626ac0e-4655-11e6-8367-d385f69a1f99.png">

**This is a example product in the backend.**
<img width="768" alt="bildschirmfoto 2016-07-10 um 04 16 12" src="https://cloud.githubusercontent.com/assets/13021579/16711331/d0e56ac4-4655-11e6-97a7-3c51a6de93c9.png">

**And this is the output on the frontend.** 
<img width="291" alt="bildschirmfoto 2016-07-10 um 04 16 20" src="https://cloud.githubusercontent.com/assets/13021579/16711337/26edd050-4656-11e6-9a5b-83dd2c653dda.png">

I have no idea whats wrong here. On a slider I echoed as well the following both outputs:

```
<?php echo number_format($_product->getPrice(), 2, ',', '.'); ?> € 
// 50,00 €
```

and

```
<?php echo $_product->getPriceInfo()->getPrice('final_price')->getAmount(); ?>
// 53.5
```

which looks like this on the frontend:

<img width="145" alt="bildschirmfoto 2016-07-10 um 04 27 59" src="https://cloud.githubusercontent.com/assets/13021579/16711342/aa135572-4656-11e6-8e53-058f02b441fb.png">

Whats wrong here? Why does $_product->getPrice output the correctly taxed price, and Magento core file outputs the wrongly taxed price? Im pretty sure that the settings are correct set, and that we configured the tax settings equal to what I expect. Am I insane, or is something wrong here?

**Comment by choukalos** [comment]
What's your Store/Config/Sales/Tax/Default Tax Destination Calculation set to?  What's the customer's address set to in your example?

**Comment by grasdaggel** [comment]
Only Tax rules we have are 19% and 7%, both for Germany. Since we do not have any user infos on those pages it can't really matter, since Magento is told to calculate a tax which is included to the price configured, or am I wrong here? Anyway, all customers are in Germany. 

If proceeded in the checkout, taxes are pressed upon the configured price, which should include them. 

Example product has configured price: 10€.
Expected Output (7% Tax): 
Price (Gross): 10€
Price (Net): 9.30€
Tax: 0.70€

Output:
Price (Gross): 10.70€
Price (Net): 10 €
Tax: 0.70€

See this screenshots:

<img width="1176" alt="bildschirmfoto 2016-07-11 um 16 50 34" src="https://cloud.githubusercontent.com/assets/13021579/16734945/91d4e2e6-4787-11e6-9f81-05ff64286dfd.png">

<img width="1100" alt="bildschirmfoto 2016-07-11 um 16 50 26" src="https://cloud.githubusercontent.com/assets/13021579/16734949/93e700aa-4787-11e6-96db-0696b7e2a0d6.png">

7% rules are applied the very same, just the amount is changed. Products are using 7%. Sorry for the inconsistence.

**Comment by grasdaggel** [comment]
Any updates on this already?

**Comment by grasdaggel** [comment]
We fixed it on our own. The problem was that the shop has the basic setting that the Shipping Origin is located in America. We changed it and now the outputted prices are correctly outputted.

Thanks anyway. This could be a little easier to fix, to be honest. :/
