### ISSUE TITLE
Error to open design Theme: Content-->Design-->Configuration

### ISSUE THREAD

**Issue by wallabit** [magento/magento2#5563]
## Steps to reproduce
1. I have upgrade from version 2.1 rc3 to 2.1
2. Navidate to: Content-->Design-->Configuration
3. Click on Edit (screen 1)
4. Open an erron page (screen 2)
5. Log 1046770404185 attached

a:4:{i:0;s:107:"Can't create directory /var/www/html/magento/var/generation/Magento/Theme/Model/Design/Backend/Exceptions/.";i:1;s:11461:"#0 /var/www/html/magento/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\Theme\M...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\Theme\M...')
#2 [internal function]: spl_autoload_call('Magento\Theme\M...')
#3 /var/www/html/magento/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\Theme\M...')
#4 /var/www/html/magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Theme\M...')
#5 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\Theme\M...')
#6 /var/www/html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Theme\M...', Array)
#7 /var/www/html/magento/vendor/magento/module-theme/Model/Design/BackendModelFactory.php(91): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Theme\M...', Array)
#8 /var/www/html/magento/vendor/magento/module-theme/Model/Design/BackendModelFactory.php(103): Magento\Theme\Model\Design\BackendModelFactory->getNewBackendModel('Magento\Theme\M...', Array)
#9 /var/www/html/magento/vendor/magento/module-theme/Model/Design/Config/ValueProcessor.php(45): Magento\Theme\Model\Design\BackendModelFactory->createByPath('design/theme/ua...', Array)
#10 /var/www/html/magento/vendor/magento/module-theme/Model/Design/Config/Storage.php(83): Magento\Theme\Model\Design\Config\ValueProcessor->process(NULL, 'websites', '1', Array)
#11 /var/www/html/magento/vendor/magento/module-theme/Model/DesignConfigRepository.php(71): Magento\Theme\Model\Design\Config\Storage->load('websites', '1')
#12 /var/www/html/magento/var/generation/Magento/Theme/Model/DesignConfigRepository/Interceptor.php(24): Magento\Theme\Model\DesignConfigRepository->getByScope('websites', '1')
#13 /var/www/html/magento/vendor/magento/module-theme/Model/Design/Config/DataProvider/MetadataLoader.php(73): Magento\Theme\Model\DesignConfigRepository\Interceptor->getByScope('websites', '1')
#14 /var/www/html/magento/vendor/magento/module-theme/Model/Design/Config/DataProvider.php(66): Magento\Theme\Model\Design\Config\DataProvider\MetadataLoader->getData()
#15 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Theme\Model\Design\Config\DataProvider->__construct('design_config_f...', 'scope', 'scope', Object(Magento\Theme\Model\Design\Config\DataProvider\DataLoader), Object(Magento\Theme\Model\Design\Config\DataProvider\MetadataLoader), Object(Magento\Theme\Model\ResourceModel\Design\Config\CollectionFactory), Array, Array)
#16 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Theme\M...', Array)
#17 /var/www/html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Theme\M...', Array)
#18 /var/www/html/magento/vendor/magento/framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php(60): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Theme\M...', Array)
#19 /var/www/html/magento/var/generation/Magento/Framework/Data/Argument/InterpreterInterface/Proxy.php(95): Magento\Framework\View\Element\UiComponent\Argument\Interpreter\ConfigurableObject->evaluate(Array)
#20 /var/www/html/magento/vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\Data\Argument\InterpreterInterface\Proxy->evaluate(Array)
#21 /var/www/html/magento/vendor/magento/module-ui/Model/Manager.php(188): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#22 /var/www/html/magento/vendor/magento/module-ui/Model/Manager.php(192): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#23 /var/www/html/magento/vendor/magento/module-ui/Model/Manager.php(172): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#24 /var/www/html/magento/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('design_config_f...')
#25 /var/www/html/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('design_config_f...', NULL, Array)
#26 /var/www/html/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'design_config_f...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#27 /var/www/html/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#28 /var/www/html/magento/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#29 /var/www/html/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#30 /var/www/html/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#31 /var/www/html/magento/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#32 /var/www/html/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#33 /var/www/html/magento/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#34 /var/www/html/magento/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#35 /var/www/html/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#36 /var/www/html/magento/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#37 /var/www/html/magento/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Theme::...')
#38 /var/www/html/magento/vendor/magento/module-theme/Controller/Adminhtml/Design/Config/Edit.php(69): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Theme::...')
#39 /var/www/html/magento/var/generation/Magento/Theme/Controller/Adminhtml/Design/Config/Edit/Interceptor.php(24): Magento\Theme\Controller\Adminhtml\Design\Config\Edit->execute()
#40 /var/www/html/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->execute()
#41 /var/www/html/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /var/www/html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->___callParent('dispatch', Array)
#44 /var/www/html/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Theme\C...', 'dispatch', Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Array, 'adminAuthentica...')
#45 /var/www/html/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#46 /var/www/html/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Theme\C...', 'dispatch', Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Array, 'adminMassaction...')
#48 /var/www/html/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#49 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /var/www/html/magento/var/generation/Magento/Theme/Controller/Adminhtml/Design/Config/Edit/Interceptor.php(39): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#51 /var/www/html/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#52 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /var/www/html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#54 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#55 /var/www/html/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#56 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#57 /var/www/html/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#58 /var/www/html/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#59 /var/www/html/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#60 /var/www/html/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#61 {main}";s:3:"url";s:134:"/admin_rvzrtj/theme/design_config/edit/scope/websites/scope_id/1/key/5fe4da89f09f9f1c3b4c28bb30e48f3e807a3422bd636a8507f191a43305036e/";s:11:"script_name";s:10:"/index.php";}
## Expected result

1.Open the theme design configuration to change the theme.
## Actual result

![screen 1](https://cloud.githubusercontent.com/assets/20377330/16711495/f07714f6-462c-11e6-82aa-0b73a530fdda.png)
![screen 2](https://cloud.githubusercontent.com/assets/20377330/16711496/f0775ccc-462c-11e6-876a-d0fcdf01ac99.png)

**Comment by AVoskoboinikov** [comment]
Hi @wallabit 

Is this issue still actual to you? 
If yes - check this steps:
1. clean Magento cache in System -> Cache Management 
2. check that your web server user has writable permissions in "/var/www/html/magento/" folder
3. try again.

Looking forward to getting response from you.

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed.
