### ISSUE TITLE
Import product csv not adding quantity for product even though it's in the csv.

### ISSUE THREAD

**Issue by serge20** [magento/magento2#5564]
N/A

**Comment by nes710** [comment]
I've been experiencing this same issue on Magento 2.0.6 and Magento 2.1.

When doing a product import and putting 1 into the quantity column the products import with 0 quantity. 

Also when doing a bulk update attributes in the products Catalog you cannot bulk change quantity on multiple products to 1, nothing happens.  When you click on individual products one by one and change quantity you can change to 1.

Anyone else experiencing this?  I tried changing product quantity to decimal but had no effect.

**Comment by shekharS7** [comment]
I have the exactly same problem. I am also looking for the solution.
