### ISSUE TITLE
Magento 2.1 Product Filter fails to load after product import

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#5565]
## Steps to reproduce
1. Install Magento CE 2.1 with sample data.
2. System > Import - Import this CSV file http://www.sharecsv.com/s/03019e6bb511194c0f148764b81708db/m2_import_test_demo.csv
3. Products > Catalog - filter for sku "test-01"
## Expected result
1. Filter loads with filtered product test-01
## Actual result
1. Filter fails to load and shows message "Attention - Something went wrong."
   ![screen shot 2016-07-10 at 2 12 02 pm](https://cloud.githubusercontent.com/assets/19744729/16711613/4e5a75ba-46a8-11e6-8f96-1452abe24e83.png)

**Comment by atIOCrON** [comment]
@antboiko thanks for the tags. Any reason the bug tag wasn't added?

**Comment by antboiko** [comment]
Hello @atIOCrON , it will be added once it's reproduced and validated.

Best,
Anton.

**Comment by atIOCrON** [comment]
@antboiko Am I correct in assuming that you followed the steps and were unable to reproduce?

**Comment by duhon** [comment]
Thanks for reporting this issue.
Unfortunately, I was not able to reproduce the issue you described.
Could you please provide more information? Like versions of PHP, MySQL and web server.
Also, it can be helpful if you describe settings of your Magento instance: was it the fresh install or upgrade from the previous version?
Do you have many store views? Maybe some other settings.

**Comment by atIOCrON** [comment]
@duhon please find PHP Info here:

https://dl.dropboxusercontent.com/u/5781539/php-info.pdf

Let me know if there is any other info needed. I replaced the real site value with "example.com".

There are very few changed settings as this was a demo instance. No new store views, not many new products. Only a few things changed in admin panel. I found the same bug in the Magento 2.1 demo as in our Magento 2.1 staging site. When I encountered the issue in staging I went to the demo to test it there to eliminate extensions being the cause as we use extensions on the staging site.

It was an upgrade from 2.0.7 to 2.1.

**Comment by atIOCrON** [comment]
@duhon @antboiko our developer took a look and the problem has been identified.

The database table cataloginventory_stock_item had multiple records with the same product_id e.g.

"Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "33" already exists."

Once the duplicate rows were deleted from cataloginventory_stock_item the error when filtering in Magento admin was resolved.

To fix it our developer ran three commands:

```
mysql> SELECT product_id, count(item_id) FROM cataloginventory_stock_item GROUP BY product_id HAVING count(item_id) > 1;
+------------+----------------+
| product_id | count(item_id) |
+------------+----------------+
|         33 |              2 |
|         34 |              2 |
|         35 |              2 |
|       2046 |              2 |
|       2048 |              2 |
+------------+----------------+
5 rows in set (0.00 sec)
```

```
mysql> SELECT item_id, product_id FROM cataloginventory_stock_item WHERE product_id IN (33, 34, 35, 2046, 2048);
+---------+------------+
| item_id | product_id |
+---------+------------+
|    2050 |         33 |
|      33 |         33 |
|    2051 |         34 |
|      34 |         34 |
|    2052 |         35 |
|      35 |         35 |
|    2053 |       2046 |
|    2046 |       2046 |
|    2049 |       2048 |
|    2048 |       2048 |
+---------+------------+
10 rows in set (0.00 sec)
```

```
mysql> DELETE FROM cataloginventory_stock_item where item_id in (2049, 2050, 2051, 2052, 2053);
Query OK, 5 rows affected (0.00 sec)
```

His guess is that the Magento 2 import script inserted the duplicate rows as we'd only added products by import.

He identified similar issues already reported but not quite the same issue:

https://github.com/magento/magento2/issues/3905
https://github.com/magento/magento2/commit/c5cc0b55b6c52d327dfcab412a33b5bd6b5a98d7

If I encounter the issue again I will report the exact steps to reproduce the bug. In the meantime someone else might be able to reproduce it by importing products, deleting them from admin, importing again etc. etc. At some point in the import process the duplicate rows must have been added.

**Comment by shiftedreality** [comment]
Hi @atIOCrON 

Thank you for your response.
I was also unable to reproduce it on 2.1.1
If you face with any other problems-please open a new issue.
Closed.

**Comment by crantron** [comment]
on 2.1.2 have this exact issue. Clients are updating inventory via import and products keep getting duplicated

**Comment by atIOCrON** [comment]
Hi @antboiko @shiftedreality @duhon, where to from here since @crantron has the same issue but this has been marked as closed?
