### ISSUE TITLE
Magento 2 admin Sales sidebar breaks with 13 links in two sections

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#5566]
## Steps to reproduce
1. Install Magento 2.1
2. Add 13 links to Sales menu under two sections (in my case they came from Amasty and Mirasvit extensions.
3. In admin click Sales to display meny
## Expected result
1. 12 links appear first column, 1 link appears in second column
## Actual result
1. First column is blank, 13 links appear in second column

![screen shot 2016-07-10 at 2 42 23 pm](https://cloud.githubusercontent.com/assets/19744729/16711698/91cec96e-46ac-11e6-8020-f0125e6f9fd8.png)
## Additional comments

This is a Magento bug because we can disable any one Amasty or Mirasvit module (to remove one item from sales menu) and the menu is back to one column.

**Comment by undefined-olha** [comment]
@atIOCrON, thank you for reporting this issue. Internal ticket MAGETWO-58238 created.

**Comment by atIOCrON** [comment]
@olgalytvynenko thanks very much. This was reported two months ago, why has it taken so long to verify?

**Comment by magento-engcom-team** [comment]
@atIOCrON, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@atIOCrON, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
