### ISSUE TITLE
Slow backup restore [Magento 2.1.0]

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5567]
## Steps to reproduce
1. Magento 2.1.0
2. Make a backup of db: `bin/magento setup:backup --db`
3. Import a lot of data or generate it: `bin/magento setup:performance:generate-fixtures <your Magento install dir>/setup/performance-toolkit/profiles/ce/large.xml`
4. Restore the backup: `bin/magento setup:rollback --db-file <your backup name>_db.sql`
## Expected result
1. Backup restoring should be pretty quick.
2. The process should use full CPU speed.
## Actual result
1. Backup restoring takes a lot of time.
2. The process uses just 10% of CPU.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Slow-backup-restore-Magento-2-1-0/idi-p/45215).
