### ISSUE TITLE
Backup fails with no error while upgrading from Magento CE 2.0.7 to Magento CE 2.1

### ISSUE THREAD

**Issue by abdulsofts** [magento/magento2#5568]
## Steps to reproduce
1. Install magento CE version 2.0.7
2. Go to System-->System Upgrade
3. Select Magento 2.1 (Latest) version
4. Go through readiness check as it is the second step in the upgrade process
5. After readiness check is successful, go to the next step to Create Backup
6. Click on 'Create Backup'
7. All the checks are passed except the 'Backup'
## Expected result
1. 'Backup' process should be passed to proceed further
## Actual result
1. 'Backup' process failed with no error message in the description as shown in the screenshot below.
   ![image](https://cloud.githubusercontent.com/assets/20385476/16715116/cb276f8e-46f4-11e6-819f-8e5e95389e95.png)

**Comment by vzaporozhets** [comment]
Hello @abdulsofts,
Can you please check logs (system.log and/or debug.log) and reply with some additional information. Also, we need more details about your environment. 
Thanks

**Comment by flipflap** [comment]
Hi, I do have the same issue while installing an Extension on Magento 2.0.7.  I checked my permissions and it should be correct. error_log doesn't show anything. Where can I find system.log and debug.log??

I found the log files in var/log, but there is nothing logged about this error.

Backups are stored in var/backups and it stops at around 220 MB

**Comment by abdulsofts** [comment]
Hi @flipflap,

You can instead find some error logs in the web server log file location i.e., var/log/apache2...

Also, to resolve this issue:
1. Manually backup the code base files and database.
2. Uncheck the database backup and code backup while installing the theme.

Your upgrade should succeed now.

Thanks,
Abdul

**Comment by flipflap** [comment]
Hi @abdulsofts 
How can I uncheck backup when installing extensions?

**Comment by abdulsofts** [comment]
You can do so if you are upgrading from the Component Manager. After the
readiness check, you will be asked to select options for Backup. Please
uncheck the database option from there.

Regards,
Abdul

**Comment by oserediuk** [comment]
Hello @abdulsofts ! Did you resolve you issue?

**Comment by abdulsofts** [comment]
Yes...the thing I did is, I simply unchecked the backup option and
proceeded with upgrade process.

Regards,
Abdul

**Comment by flipflap** [comment]
No, I didn't solve this. I used composer. 

Unfortunathely there is no possibility to uncheck the backup option!

Regars - Oli

**Comment by abdulsofts** [comment]
Can you try using Component Manager?

**Comment by shiftedreality** [comment]
Hi @abdulsofts 

I was unable to reproduce this on 2.0.9 -> 2.1.1 
Could you please try to reproduce this variant on your machine?
Also please open Developer console in your browser, press 'Try Again' and paste here response of XHR request named 'check'.

**Comment by apurv-anand** [comment]
Check for the Varnish 503 back end fetch issue. You might have to increase the http_resp_hdr_len size.

http://devdocs.magento.com/guides/v2.0/config-guide/varnish/tshoot-varnish-503.html

**Comment by flipflap** [comment]
Thanks apurv-anand, I will try this...

**Comment by frostshoxx** [comment]
I have the same issue. I don't see anything on the log files. However, I notice on Chrome console, it showed the following 503 status errors on the following web requests:
http://{website}/setup/index.php/backup-action-items/create
and
http://{webiste}/setup/index.php/session/prolong

At the end when it has a call to "create", there seems to be no response except just the 503 as well. However, the backup did get created, so I ended up clicking back and deselect back up in order to continue with the upgrade.

**Comment by magento-engcom-team** [comment]
@abdulsofts, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
