### ISSUE TITLE
M2.1 "This is a required field" wrong position

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#5569]
the position of "This is a required field." message in configurable product is in wrong place
![this-is-required](https://cloud.githubusercontent.com/assets/8407530/16716021/8eb068b4-4701-11e6-846e-83f183e4d13a.PNG)

**Comment by JDavidVR** [comment]
having same problem, weird in early version it was working well

**Comment by pboisvert** [comment]
closing as this is a duplicate of #5428
