### ISSUE TITLE
How can i select theme?

### ISSUE THREAD

**Issue by sonnguyen089** [magento/magento2#5572]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by sonnguyen089** [comment]
I just install 2.2-dev version. There is Search Engine Robots in Design tab only.

**Comment by grasdaggel** [comment]
Shop -> Config -> Web -> Theme 

Sorry, was wrong. Its Shop -> Config -> Design -> Theme

**Comment by sonnguyen089** [comment]
There is not theme tab in magento 2.2.

**Comment by sonnguyen089** [comment]
I go to Stores->Configuration->General->Design
![2016-07-11_141512](https://cloud.githubusercontent.com/assets/20393194/16722610/f8ed4056-4771-11e6-9718-c1d5c25f571f.jpg)

**Comment by grasdaggel** [comment]
Your Screenshot is showing:
Shop -> Config -> Design

Please go to:
Shop -> Config -> Web -> Theme

**Comment by sonnguyen089** [comment]
Pls check. i am using magento 2.07, the theme tab bellow config->design
![web](https://cloud.githubusercontent.com/assets/20393194/16722846/99530d2c-4773-11e6-8998-9e1fdc650352.jpg)

**Comment by antboiko** [comment]
Hi @sonnguyen089 , in 2.1 this was moved to Content > Design > Configuration.

Best,
Anton.

**Comment by sonnguyen089** [comment]
I got it.
Thank you very much.
Is there any tutorial for magento 2.2?

**Comment by antboiko** [comment]
@sonnguyen089 
Not yet, User Guide is going to be updated for 2.1.

Best,
Anton.

**Comment by sonnguyen089** [comment]
Some extension work good with version 2.0, but it does not work with version 2.1 or 2.2
What is the diffirent?

**Comment by antboiko** [comment]
@sonnguyen089 please create a separate ticket for another issue and provide detailed steps. 

I'm closing this one. Please feel free to reopen if you have any additional questions about theme selection.

Thanks,
Anton.
