### ISSUE TITLE
Fail to import custom options

### ISSUE THREAD

**Issue by Nerogee** [magento/magento2#5573]
## Steps to reproduce
1. Install magento2.1 from composer
2. Add configured product A
3. Add custom options C1 and C2 for A
4. Add configured product B
5. Import custom option from A to B
## Expected result
1. Product B has custom option C1 and C2
## Actual result
1. Fail to load the custom option from product A after click import
   ![customoptions](https://cloud.githubusercontent.com/assets/12842026/16723325/dbe05252-477e-11e6-874f-22f859d3e607.png)

**Comment by veloraven** [comment]
@Nerogee , thank you for your report.

But could you please provide more detailed steps? Like custom options types, parameters of the product, exact steps during import, etc.
As I was not able to reproduce this issue. I successfully imported custom options from one configurable product to another.

**Comment by Nerogee** [comment]
Two options are dropDown type. The configured product has two custom attributes. one is **racket color** and another is **grip size** . These two custom attributes are **Text Swatch**. The steps are simple as already mentioned above. 
1. Create configured A and **saved**.
2. Go to Product A admin page and created **Two** custom options (both are Drop Down type)
3. Save
4. Created configured B and saved.
5. Go to Product B and click import option
6. Select Product A on prompt.
7. continue but options doesn't show and cant save product at this moment.

**Comment by Nerogee** [comment]
I just checked and found there are JS error
1. too much recursion (registry.js (line 413, col 13))
2. TypeError: path.split is not a function (objects.js (line 115, col 27))

thank you.

**Comment by Nerogee** [comment]
@veloraven , Do you have any updates for me? Yesterday I installed again magento2.1 via composer. The issue is confirmed to be there and easy to reproduce. Please update me thanks

**Comment by SewHappy58** [comment]
I can confirm I have the same issue with a fresh install of Magento 2.1 RC3.  I had a variety of options added to a particular product.  When I went to select based on a product, I get a list of products, I select and press import.  Nothing happens.  I get the same final screenshot Nerogee gets.  I don't even know why Yellow is showing and nothing else under Pets Name or Additional Options (grouped)

![screen shot 2016-07-16 at 12 16 30 pm](https://cloud.githubusercontent.com/assets/7072324/16896089/2da32a5a-4b4f-11e6-83e4-b62cbd7f899f.png)

**Comment by veloraven** [comment]
@Nerogee thank you for additional details.
I was able to reproduce this issue now. I created an internal ticket - MAGETWO-56018 and linked it to this one.

**Comment by Nerogee** [comment]
@veloraven Do you know when would this be live?

**Comment by SewHappy58** [comment]
Still a problem in 2.1.1

**Comment by SewHappy58** [comment]
Any updates on this?

**Comment by onakonechna** [comment]
Target version is 2.1.3

**Comment by andrei4mag** [comment]
The same happens with the Simple products. No custom options imported

**Comment by elenleonova** [comment]
The issue has been delivered to 2.1.3
