### ISSUE TITLE
magento 2.0.7 don't change exchange rate after changing base currency

### ISSUE THREAD

**Issue by yuklia** [magento/magento2#5575]
## Steps to reproduce
1. Change base currency from admin panel. Stores > Configuration > General > Currency setup
2. indexer:reindex
## Expected result
1. All prices were converted due to new currency
## Actual result
1. Only currency sign was changed.
2. Price was calculated by old exchange rate

**Comment by antboiko** [comment]
Hi @yuklia , this is a correct behavior. 

Could you please provide a specific use case for product prices being automatically converted due to currency change in Admin?

Thanks.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
Please take into account that described behavior does not seem to be an issue.
