### ISSUE TITLE
Cart checkout: Free shipping doesn't work anymore.

### ISSUE THREAD

**Issue by slorenx** [magento/magento2#5576]
**Magento 1.9.xx  + Webkul multivendor extension + 2 plugins to manage shipping rates**
I have a problem to my multivendor marketplace. The support of plugins developper fixed an issue to their module and since that an other issue came and they are not able to fix it. ( i mean they can restore the old code, but doing that, new issue disappear and old one come back)
Problem is:
in a cart we can have a mix of products sold with paid shipping and products sold with free shipping.
indeed, free shipping must be applied only to those specific products listed by vendor.
That is not anymore happening. All products are now considered as paid shipping at checkout.
Free shipping was managed by attributes and cart rules and now the modification to code is doing this.
I think everything is due to the attached php file, from line 45 to 205
[free shipping.zip](https://github.com/magento/magento2/files/356885/free.shipping.zip)
, I am attaching also an explanation concerning how cart must process free shipping items

 from line 45 to 205. Is there anyone that can help me?

**Comment by pboisvert** [comment]
@slorenx seems like you are reporting an issue against Magento 1.x. If so then this Github location is the wrong place to do so as this is dedicated to reporting Magento 2 issues only. Even if this was Magento 2 it sounds like the issue is not with the core code but rather with incompatibility of extensions.
