### ISSUE TITLE
Class VaultPaymentValueHandlerPool does not exist in /magento/vendor/magento/framework/Webapi/ErrorProcessor.php:195

### ISSUE THREAD

**Issue by NisaKH** [magento/magento2#5577]
## Steps to reproduce

call api {{host}}/rest/V1/carts/{{cart_id}}/shipping-information
## Expected result

API return available payment method 
## Actual result

Next Exception: Report ID: webapi-5783a7c0c96e8; Message: Class VaultPaymentValueHandlerPool does not exist in /magento/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /magento/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(ReflectionException))
#1 /magento/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(ReflectionException))
#2 /magento/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /magento/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by YevSent** [comment]
Hi, @NisaKH, please, specify the version of Magento, request body and the list of enabled payments methods.
**UPD:** On the latest develop branch this API request works correctly.

**Comment by YevSent** [comment]
Closing this issue due to no response, please reopen when you have an update.

**Comment by tweetyx** [comment]
Go to your Back office, and active Enable Magento_Vault in your component manager.

**Comment by PieterCappelle** [comment]
I was having the same problem. The problem was the module was not enabled. No idea why the module was not enable. Maybe because we did an upgrade from 2.0 to 2.1?

```
vagrant@magento2box:/var/www/****$ php bin/magento module:status
List of enabled modules:
Magento_Store
........
Magento_WebapiSecurity
Magento_Weee
Magento_CatalogWidget
Magento_Wishlist

List of disabled modules:
Magento_Security
Magento_Vault
Magento_SwatchesLayeredNavigation
```

To fix you need to do: 

```
php bin/magento module:enable Magento_Security Magento_Vault Magento_SwatchesLayeredNavigation
php bin/magento setup:upgrade
php bin/magento cache:clean
```
