### ISSUE TITLE
Can't open images from the Product Details

### ISSUE THREAD

**Issue by loomdecor** [magento/magento2#5578]
## Steps to reproduce
1. Go to products and select a product
2. Click on Product Details (if not already there)
3. Go to Images & Videos Section
4. Try to click on an image - you can't get the details to show up
5. The only way to get the details of an image to show up / enter details is to go to the Images & Videos link on the left.  This is not intuitive -- every time I try to do this I try to click in Product Details and get annoyed that I can't open from there.

Expected result

Should be able to open Image from Images & Videos section under Product Details

**Comment by antboiko** [comment]
Hi @loomdecor , thanks for your feedback and suggestion. 
This behavior has been already improved in 2.1.

Please check and let me know if this is what you expect.

Best,
Anton.

**Comment by andimov** [comment]
@loomdecor 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
