### ISSUE TITLE
Magento's DI ignores the Preference when using Plugins.

### ISSUE THREAD

**Issue by mktudock** [magento/magento2#5579]
## Steps to reproduce

**_A:**_
1. Override a class via DI preference 
   
   ``` xml
   <preference for="Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable" type="Vendor\Module\...Configurable" />
   ```
2. Create a plugin for this type (in our case another module added a plugin for all blocks like this:) 
   
   ``` xml
     <type name="Magento\Framework\View\Element\Template">
         <plugin name="foo" type="Vendor\Module\...Plugin" sortOrder="1" />
     </type>
   ```
3. Run setup:di:compile

**_B:**_
1. Do all steps from A and delete the var/di folder
## Expected result

**_A/B:**_
1. I open the page on which the block is placed on
2. I see the output that results of the original block, my preference, as well as the defined plugin.
## Actual result

**_A:**_
1. I see the output that results of the original block and the defined plugins, **but not my preference.**

**_B:**_
1. Same as expected
## What happens?

**A:** 
What happens is that, in this case Magento tries to load `Magento\ConfigurableProduct\Block\Cart\Item\Renderer\ConfigurableInterceptor`, which isn't at all what is expected to happen. Instead Magento should load the Interceptor of the Class defined in the Preference: `Vendor\Module\...ConfigurableInterceptor`. 

This should load the interceptor of my custom preference, which should run my class and all plugins.

This is a real issue for us, because some module creator thought it was a great idea to add a plugin for all blocks, which breaks all of our custom blocks we added via preferences.

**B:** 
**When deleting var/di Magento loads the correct interceptor! (`Vendor\Module\...ConfigurableInterceptor`)** 

Because of this I'm pretty sure, this is a bug. Our current workaround is to delete the var/di folder before deployment, but this is far from optimal.

**Comment by adragus-inviqa** [comment]
Slightly counter-intuitive, yes, but I don't think this is a bug. It's documented: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/code-generation.html.

Tbh, I would always prefer to empty the var/di folder and compile before every release. Otherwise, M2 will have to lookup DI stuff _dynamically, on production_, which would considerably slow it down. Why is that far from optimal?

**Comment by mktudock** [comment]
I **would** compile before going to production, but that's exactly the problem I can't,because the compilation tool acts different from Magento doing DI on runtime. 

Again, when using di:compile Magento loads the interceptor class of the original class when plugins are defined, which is not what I want. What I want, and what I expect to happen, is what happens when clearing the var/di folder: Magento loads the interceptor class of the **preference** when plugins are defined. 

The current behavior of di:compile makes it impossible to use plugins and preferences at the same time. All modules that use plugins break all modules that use preferences (see example in original post). 

And as I said, this only applies to di:compile not to dynamic DI.

**Comment by davidalger** [comment]
@mktudock So others on the core team can try and reproduce, what version of Magento and PHP are you using?

**Comment by mktudock** [comment]
I'm sorry, we were still using a RC of 2.1.0. Yesterday we upgraded to 2.1.0, and I just tested di:compile again, and the issue seems to be resolved.
setup:di:compile now sets the correct interceptor classes.

I don't know if the update itself fixed the issue, or if something else was the reason, but I'm happy it's working now. :)

**Comment by davidalger** [comment]
@mktudock Sounds great, thanks for the update! Let us know if the issue comes back.
