### ISSUE TITLE
Why the bad selectors in css?

### ISSUE THREAD

**Issue by mackelito** [magento/magento2#5581]
I have been looking at the blank theme and find lots of selectors of plain elements eg h-tags, p-tags, ul/li, a etc etc.. 

Normally I would just rant on how this is a really bad practice but.. I´m assuming that there is a good reason for this!(?).

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by mackelito** [comment]
AH.. you are correct my best sir! :)
Sorry if this sounded like just negative complaints.. I was just a bit frustrated and.. well .. you know!.. ;)

Will take a look at the other places!

Cheers!
/Markus
