### ISSUE TITLE
How add custom attributes in "Sale Order" REST API?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#5582]
## Steps to reproduce
1. Install Magento (2.0.7).
2. Enable my module with adding attributes:
   `$salesSetup->addAttribute(Order::ENTITY, 'date', ...`
3. Write a Di:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Sales\Api\Data\OrderInterface" type="Company\OrderAttributes\Di\Sales\Api\Data\OrderInterface" />
    <preference for="Magento\Sales\Model\Order" type="Company\OrderAttributes\Di\Sales\Model\Order" />
</config>
```

_OrderInterface_:

```
<?php

namespace Company\OrderAttributes\Di\Sales\Api\Data;

interface OrderInterface extends \Magento\Sales\Api\Data\OrderInterface
{
    const DATE = 'date';

    /**
     * Sets the date
     *
     * @param st $date
     * @return string
     */
    public function setOrderDate($date);

    /**
     * Gets the date
     *
     * @return string
     */
    public function getOrderDate();
}

```

_Order_

```
<?php

namespace Company\OrderAttributes\Di\Sales\Model;

use Company\OrderAttributes\Di\Sales\Api\Data\OrderInterface;

class Order extends \Magento\Sales\Model\Order implements OrderInterface
{
    //public $date;

    /**
     * {@inheritdoc}
     */
    public function getOrderDate()
    {
        return $this->getData(OrderInterface::DATE);
    }

    /**
     * {@inheritdoc}
     */
    public function setOrderDate($date)
    {
        return $this->setData(OrderInterface::DATE, $date);
    }
}

```
## Expected result
1. **date** property in API response:

```
{
    "applied_rule_ids": "2",
    "base_currency_code": "USD",
    "base_discount_amount": 0,
    ...

    "date": "my date",
    ...
}
```
## Actual result
1. The date is not visible.

Could you help me with it, what is wrong?

**Comment by springimport** [comment]
Any news?

**Comment by MagePsycho** [comment]
Any news on the same?

**Comment by mbrinton01** [comment]
Hello @springimport, GitHub issues are intended for bug reporting only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to open another issue if you think you have encountered a bug in Magento 2.

**Comment by MagePsycho** [comment]
@springimport were you able to fix the issue without using `extension_attributes`?

**Comment by springimport** [comment]
@MagePsycho you can see https://github.com/magento/magento2/issues/5747
