### ISSUE TITLE
Multiple JS errors in the backend

### ISSUE THREAD

**Issue by DevXeni** [magento/magento2#5583]
Hi,
I have a fresh installation of Magento 2.1, got with composer (create-project), was installed via CLI command, was switched to developer mode. Nginx(1.10.0)+php-fpm(7.0.8), correct filesystem permissions.

But in the backend (admin) on all pages, excluding dashboard,  the multiple js errors occuring permanently. In production mode (and setup:static-content:deploy), in developer mode - errors still exists.
![screenshot from 2016-07-11 23-43-51](https://cloud.githubusercontent.com/assets/6112347/16746875/7e8b667e-47cd-11e6-9536-2380284239bb.png)

**Comment by crantron** [comment]
@DevXeni have to deployed static content?

**Comment by DevXeni** [comment]
Yes.

**Comment by DevXeni** [comment]
Today, I've done all steps, as in docs (there http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html and http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-mode.html)
nothing helped - js errors still there. On dashboard page also appeared!
![screenshot from 2016-07-12 12-33-09](https://cloud.githubusercontent.com/assets/6112347/16762373/448b282a-4835-11e6-9765-1ee0b590a355.png)

**Comment by DevXeni** [comment]
Sometimes, some of js files randomly not found -
"NetworkError: 404 Not Found - http://magento-2.local/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/i18n.js"
i18n.js
"NetworkError: 404 Not Found - http://magento-2.local/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/scope.js"
scope.js
"NetworkError: 404 Not Found - http://magento-2.local/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/resizable.js"
resizable.js
"NetworkError: 404 Not Found - http://magento-2.local/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/range.js"
Not only in list above, also it's maybe http://magento-2.local/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/registry/dom_observer.js or another file

But, sometimes all files founded. Then js TypeError occurs 
TypeError: utils.extend is not a function
child.defaults = utils.extend({}, parent.defaults || {}); 

Current mode : developer.
Static content deploy: repeated many times (including manually deleting files in pub/static and var folders)

**Comment by DevXeni** [comment]
Very strange. This is my nginx conf. maybe problem is there 
`server {
    listen 80;

```
server_name magento-2.local;

index index.php;

set $MAGE_MODE developer;

set $MAGE_ROOT /var/www/html/magento2;

root $MAGE_ROOT/pub;

autoindex off;

charset off;

location /setup {

    root $MAGE_ROOT;

    location ~ ^/setup/index.php {

        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;

        fastcgi_index index.php;

        fastcgi_read_timeout 3600;

        fastcgi_connect_timeout 3600;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi_params;

    }

}

location / {

    proxy_set_header X-Forwarded-Proto $scheme;

    try_files $uri $uri/ /index.php?$args;

}

location /pub {

    proxy_set_header X-Forwarded-Proto $scheme;

    alias $MAGE_ROOT/pub;

}

location /static/ {

    proxy_set_header X-Forwarded-Proto $scheme;

    if ($MAGE_MODE = "production") {

        expires max;

    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {

        add_header Cache-Control "public";

        expires +1y;

        if (!-f $request_filename) {

            rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;

        }

    }

    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {

        add_header Cache-Control "no-store";

        expires off;

        if (!-f $request_filename) {

           rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;

        }

    }

    if (!-f $request_filename) {

        rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;

    }

}

location /media/ {

    proxy_set_header X-Forwarded-Proto $scheme;

    try_files $uri $uri/ /get.php?$args;

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {

        add_header Cache-Control "public";

        expires +1y;

        try_files $uri $uri/ /get.php?$args;

    }

    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {

        add_header Cache-Control "no-store";

        expires  off;

        try_files $uri $uri/ /get.php?$args;

    }

}

location /media/customer/ {deny all;}

location /media/downloadable/ {deny all;}

location ~ /media/theme_customization/.*\.xml$ {deny all;}

location /errors/ {try_files $uri =404;}

location ~ ^/errors/.*\.(xml|phtml)$ {deny all;}

location ~ cron\.php {deny all;}

location ~ (index|get|static|report|404|503)\.php$ {

    proxy_set_header X-Forwarded-Proto $scheme;

    try_files $uri =404;

    fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;

    fastcgi_param PHP_FLAG "session.auto_start=off \n suhosin.session.cryptua=off";

    fastcgi_param PHP_VALUE "memory_limit=256M \n max_execution_time=0";

    fastcgi_read_timeout 3600;

    fastcgi_connect_timeout 3600;

    fastcgi_param MAGE_MODE $MAGE_MODE;

    fastcgi_index index.php;

    fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;

    include fastcgi_params;

}
```

}

server {

```
server_name www.magento-2.local;

proxy_set_header X-Forwarded-Proto $scheme;

rewrite ^ http://magento-2.local$request_uri? permanent;
```

}`

**Comment by Igloczek** [comment]
Are you 100% sure that this files exist in `/pub/static/...`? 
Did you chceck files permissions?

**Comment by DevXeni** [comment]
Hi!
Permissions - OK! 
As I wrote earlier:

> Hi,
> I have a fresh installation of Magento 2.1, got with composer (create-project), was installed via CLI command, was switched to developer mode. Nginx(1.10.0)+php-fpm(7.0.8), **correct filesystem permissions.**

Deploy static content  - OK

> Static content deploy: **repeated many times** (including manually deleting files in pub/static and var folders)

**/pub/static:**

By path /var/www/html/magento2/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/ have only bound-nodes.js  and observable_array.js
Nothing more. (Why? I've done setup:static-content:deploy without errors!)

By path /var/www/html/magento2/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/registry/ have only registry.js. Nothing more. (Why? I've done setup:static-content:deploy without errors!)

**Comment by DevXeni** [comment]
Where are the missing files js - location? They can be copied to the proper locations, and maybe it would solve the problem.
However, I do not understand why it all happened.  If that files need for magento, why they could not created automatically during setup:static-content:deploy process?

**Comment by Igloczek** [comment]
`vendor/magento/module-ui/view/base/web/js/lib` - here you should have source files.

**Comment by DevXeni** [comment]
Thank you

**Comment by DevXeni** [comment]
In /var/www/html/magento2/vendor/magento/module-ui/view/base/web/js/lib/registry only registry.js is. No others.
in /var/www/html/magento2/vendor/magento/module-ui/view/base/web/js/lib/knockout/extender/ only bound-nodes.js  and observable_array.js. No others.

Well.
As I understand the missing files does not downloaded by composer from repository. Sad. Will download archive from official website. Maybe there will be the correct magento package.

**Comment by Igloczek** [comment]
It's your instance problem - I just end creating project via `composer create` and everything is in place.

**Comment by DevXeni** [comment]
Just now, I've  downloaded  the archive from official website, I've checked locations of missing files, there are no required js files. Well... very strange.

**Comment by Igloczek** [comment]
Did you get this errors on some view or just globally? My panel works fine and I don't have these files too.

**Comment by DevXeni** [comment]
On backend, also on frontend -  everywhere js errors. Different but still there.
Admin panel does not work properly, on frontend - I have no sample data there but in firebug I see errors.

**Comment by Igloczek** [comment]
Do you have names of this files mentioned somewhere inside`pub/static/_requirejs/`? (without `.js` suffix)

**Comment by DevXeni** [comment]
/var/www/html/magento2/pub/static/_requirejs/adminhtml/Magento/backend/en_US
requirejs-config.js
only.

**Comment by Igloczek** [comment]
As far as I understand how JS is working in M2, you shouldn't have it here.
I'm out, It's too weird for me 😉

**Comment by DevXeni** [comment]
Ok,
Right now. I open same magento on  laptop (ubuntu 14, without updates after installation. firefox 31!) and wow all is OK! On my RedHat7 desktop (with latest updates and newest firefox) I've got errors. I use the exact same virtual machine on laptop and desktop. WOW, Magento team  - this js solution is very unsuitable!

**Comment by DevXeni** [comment]
Thank you,  Igloczek and crantron, for your replies and time.

**Comment by kuldeepdaffodil** [comment]
I am also facing same issue in fresh magento install, I try with apache and nginx both web server and try with php version 5.6.28 and 7.0. 

Js error are still occur after  magento install and static content deploy. I am using magento 2.1.2 and also checked same in magento 2.1.1 community edition. 
![jserror](https://cloud.githubusercontent.com/assets/12231089/20267366/66eee866-aaa0-11e6-95ff-304ed028c75f.png)

**Comment by crantron** [comment]
@DevXeni clear your browser cache -_-

**Comment by kuldeepdaffodil** [comment]
Yes I clear browser cache but still same issue. Its very strange. I try this in another system with same magento zip file and its working fine. Mod_rewrite is already enabled and allow override is all in apache setting. 
![js](https://cloud.githubusercontent.com/assets/12231089/20294308/2da3e84e-ab23-11e6-8caa-165dcf1c1559.png)

**Comment by DevXeni** [comment]
I suppose it is a browser version.

**Comment by murtuza5253** [comment]
I have same issue with the firefox, I just disable my firebug extension and now its work normally
