### ISSUE TITLE
Unable to change product attribute set, unless user has full resource access

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#5584]
## Steps to reproduce
1. Login as user with role that has custom resource access to Products --> Inventory --> Catalog
2. Edit product in admin
3. Attempt to change attribute set of product
## Expected result
1. Attribute AJAX menu will "popup" and display list of attribute sets that user can choose from.
## Actual result
1. Attribute AJAX menu does not "popup".
## More information

I also attempted to manually check all the resources for this user role.  Which in theory would mimic the "all" resource access option.  But even with all resources manually checked, I was still unable to change the attribute set of a product.

However when I changed the resource access option to "all", I was able to change the attribute set of a product.

**Comment by antboiko** [comment]
Hi @orbitrod , what Magento version are you using?

Thanks,
Anton.

**Comment by orbitrod** [comment]
I am using Community Edition 2.0.7

**Comment by antboiko** [comment]
@orbitrod  thanks. We already have internal ticket MAGETWO-53557 to fix this issue.

Best,
Anton.

**Comment by rganin** [comment]
Fixed in 2.0 branch. Not reproduced in 2.1 and develop.
