### ISSUE TITLE
Magento 2.1 Customer custom attribute not present in Customer address edit and registration form

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5586]
Adding a customer custom attribute and assigning it to the forms:
['adminhtml_customer_address', 'customer_address_edit', 'customer_register_address']

The new attribute is visible and runs for admin, onepagecheckout (both shipping and biling address) and this is ok.

When a customer edit his address from his profile or add a new address, form related to the file magento_customer/view/frontend/templates/address/edit.phtml, this attribute is not present even if correctly inserted in customer_form_attribute form_code (used_in_forms)

Is this a bug or have i to add something else, somewhere?
Sorry but i didn't find any useful documentation or tutorial about this.

InstallData.php

namespace Namespace\Module\Setup;

use Magento\Framework\Module\Setup\Migration;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

/**
- @codeCoverageIgnore
  _/
  class InstallData implements InstallDataInterface
  {
  /_*
  - Customer setup factory
    *
  - @var CustomerSetupFactory
    */
    private $customerSetupFactory;
  
  /**
  - Init
    *
  - @param CustomerSetupFactory $customerSetupFactory
    */
    public function __construct(\Magento\Customer\Setup\CustomerSetupFactory $customerSetupFactory)
    {
    $this->customerSetupFactory = $customerSetupFactory;
    }
  
  /**
  - {@inheritdoc}
  - @SuppressWarnings(PHPMD.ExcessiveMethodLength)
    _/
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
    /_\* @var CustomerSetup $customerSetup */
    $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);
    
    $setup->startSetup();
    
    // insert attribute
    $customerSetup->addAttribute('customer_address', 'attr_code',  [
        'label' => 'My attribute',
        'type' => 'varchar',
        'input' => 'text',
        'position' => 45,
        'visible' => true,
        'required' => false,
        'system' => 0
    ]);
    
    $MyAttribute = $customerSetup->getEavConfig()->getAttribute('customer_address', 'attr_code');
    $MyAttribute->setData(
        'used_in_forms',
        ['adminhtml_customer_address', 'customer_address_edit', 'customer_register_address']
    );
    $MyAttribute->save();
    
    $setup->endSetup();
    }
    }

**Comment by Umfi** [comment]
I have the same problem with Magento 2.0.4.

I created custom EAV Attributes, added them to the edit.phtml.

on submit of the form, i got the response that the custom-field is required.
if i check the network section of my browser, i see that the value is posted correctly, but when the error message appears the field is empty.

**Comment by PierAlex** [comment]
@Umfi:
Is this correct to add the Attribute to the edit phtml? I expected it was already present because of use_in_forms.
However, how do you added the EAV Attribute to the form? I don't know how to get and set data. Can you pls. post your code as an example?

**Comment by Umfi** [comment]
@PierAlex 

I think you have to override the phtml in your theme or module.
This works for me for customer edit form:

`
        <div class="field">
            <label for="custom_attribute" class="label"><span><?php /* @escapeNotVerified */ echo __('custom_attribute') ?></span></label>
            <div class="control">
                <input type="text" name="custom_attribute" id="custom_attribute" title="<?php /* @escapeNotVerified */ echo __('custom_attribute') ?>" class="input-text" data-validate="{required:false}" autocomplete="off" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("custom_attribute"))) { echo $block->getCustomer()->getCustomAttribute("custom_attribute")->getValue(); } ?>">
            </div>
        </div>
`

I did it the same way with EAV created for following forms:
adminhtml_customer_address, customer_register_address, customer_address_edit, customer_address

but i'm not able to get and save the value of that attribute

### so to be clear, i have problems with custom attributes for: customer_address

```
        $used_in_forms_address = array();
        $used_in_forms_address[]="adminhtml_customer_address";
        $used_in_forms_address[]="customer_register_address";
        $used_in_forms_address[]="customer_address_edit";
        $used_in_forms_address[]="customer_address";

$attribute = $customerSetup->getEavConfig()->getAttribute('customer_address', 'my_attribute')
                ->addData([
                    'attribute_set_id' => $attributeSetId,
                    'attribute_group_id' => $attributeGroupId,
                    'used_in_forms' => $used_in_forms_address,
                    'is_used_for_customer_segment' => true,
                    'is_system' => 0,
                    'is_user_defined' => 1,
                    'is_visible' => 1,
                    'sort_order' => 100
                ]);

$attribute->save();
```

**Comment by PierAlex** [comment]
@Umfi 
just to understand, does it works for you in edit.phtml form also for reading and saving data?
Because for me
<?php if (!empty($block->getCustomer()->getCustomAttribute("my_attribute"))) { echo $block->getCustomer()->getCustomAttribute("my_attribute")->getValue(); } ?>
does not return anything.

**Comment by Umfi** [comment]
@PierAlex 

it does work for me for customer attribute (example registration form) but not for attributes on "customer_address"

for "customer_address" i do have the same problems

looks like somebody has the same problem here: http://magento.stackexchange.com/questions/125194/magento-2-1-how-to-add-a-customer-custom-attribute-in-the-customer-address-edit

**Comment by oserediuk** [comment]
Hello @PierAlex ! Could your provide your code base version?

**Comment by PierAlex** [comment]
Hello @oserediuk,
maybe i need some instructions on how to do it.
I have done only InstallData.php.
I created, before that, an attribute for customer:
$customerSetup->addAttribute('customer', 'attr_code'...
and only with installdata and 'used in forms' it appears in customer registration form during the checkout process. I Thought it should be the same for a 'customer_address' attribute and used in forms = .., 'customer_address_edit', 'customer_register_address'.
I think i have to write more code but i'm new on magento2 and it is not so clear for me, with devdocs and other samples, what are steps to do it.
Ale

**Comment by oserediuk** [comment]
@PierAlex Do you use CE version?

**Comment by PierAlex** [comment]
@oserediuk, Yes, I use CE version.

**Comment by magento-engcom-team** [comment]
@PierAlex please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by Styopchik** [comment]
Facing issue in 2.3.2
I suggest, that in Magento_Customer::address/edit.phtml should be at least

`echo $this->getChildHtml('additional_data');`

inside of `<form>` for having possibility to display custom attributes inputs without overriding core template.

**Comment by sdzhepa** [comment]
Hello @Styopchik 

May I ask you to create new Issue with details about how it can be reproduced on the 2.3.x Magento Open Sorce  version according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)?

It will really help to confirm the issue and fix much faster
