### ISSUE TITLE
Getting attribute by group (REST api)

### ISSUE THREAD

**Issue by CodeGlitcher** [magento/magento2#5588]
You can get all attributes in a attribute set with
http://{baseurl}/index.php/rest/V1/products/attribute-sets/{attribute_set_id}/attributes
This works, but i would like to know to which group the attributes belongs to. 

Something like:
http://{baseurl}/index.php/rest/V1/products/attribute-sets/groups/7/attributes
This would then return all the attributes in group 7

Or is there already an other option to get the attributes of an group?

**Comment by Serhiy-Nazarov** [comment]
I have this problem too.
@veloraven, when I can expect a response?
Thanks!

**Comment by Serhiy-Nazarov** [comment]
the solution is simple - append group_id to respond for 
/V1/products/attribute-sets/{attributeSetId}/attributes

**Comment by veloraven** [comment]
@robg66 
I'm closing this issue as GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
eature Requests and Improvements should now be submitted to the new[ Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by VireshRajvansh** [comment]
@Serhiy-Nazarov 
how can we append group_id to reponse for
/V1/products/attribute-sets/{attributeSetId}/attributes  
please explain

**Comment by VireshRajvansh** [comment]
@Serhiy-Nazarov 
how can we append group_id to reponse for
/V1/products/attribute-sets/{attributeSetId}/attributes

please explain....

**Comment by Serhiy-Nazarov** [comment]
@VireshRajvansh 
In the current version Magento2 API it does not work. It's just a suggestion for core.
On our projects, we have created a module that expands the API

**Comment by madmichael** [comment]
This endpoint /V1/products/attribute-sets/{attributeSetId}/attributes does work in the current version of Magento.
