### ISSUE TITLE
Magento 2 Wrong base grand total and grand total response of save shipping info

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#5589]
Hello,
When i go from step1 to step2 in checkout before saveshipping response is :
{"payment_methods":[{"code":"test","title":"test"},{"code":"free","title":"No Payment Information Required"}],"totals":{"grand_total":31,"base_grand_total":33.17,"subtotal":31,"base_subtotal":31,"discount_amount":0,"base_discount_amount":0,"subtotal_with_discount":31,"base_subtotal_with_discount":31,"shipping_amount":0,"base_shipping_amount":0,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":2.17,"base_tax_amount":2.17,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":33.17,"shipping_incl_tax":0,"base_shipping_incl_tax":0,"base_currency_code":"USD","quote_currency_code":"USD","items_qty":5,"items":[{"item_id":3912,"price":5,"base_price":5,"qty":2,"row_total":10,"base_row_total":10,"row_total_with_discount":0,"tax_amount":0.7,"base_tax_amount":0.7,"tax_percent":7,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":5.35,"base_price_incl_tax":5.35,"row_total_incl_tax":10.7,"base_row_total_incl_tax":10.7,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"BBQ Chicken Skewers"},{"item_id":3913,"price":7,"base_price":7,"qty":3,"row_total":21,"base_row_total":21,"row_total_with_discount":0,"tax_amount":1.47,"base_tax_amount":1.47,"tax_percent":7,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":7.49,"base_price_incl_tax":7.49,"row_total_incl_tax":22.47,"base_row_total_incl_tax":22.47,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"Beef Satay w\/Asian Sesame BBQ Sauce"}],"total_segments":[{"code":"subtotal","title":"Subtotal","value":31},{"code":"shipping","title":"Shipping & Handling","value":0},{"code":"tax","title":"Tax","value":2.17,"area":"taxes","extension_attributes":{"tax_grandtotal_details":[{"amount":2.17,"rates":[{"percent":"4","title":"GA STATE TAX"},{"percent":"3","title":"GA COUNTY TAX"}],"group_id":1}]}},{"code":"grand_total","title":"Grand Total","value":33.17,"area":"footer"}}}

Here you can see base 

grand_total":31,"base_grand_total":33.17
both are different value.

when i debug this :
Magento\Quote\Api\CartTotalRepository
= > $amount = $quoteTotals->getGrandTotal() - $quoteTotals->getTaxAmount();
why this above statement added? here should be some condition if order total without tax then need to do this?

**Comment by grasdaggel** [comment]
I have had the same issue. Can you check if $_product->getPrice() gives you back the "correct" price?

**Comment by veloraven** [comment]
@sunilit42 thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also provide description according to the template: with steps, actual result and expected result, otherwise it's hard to understand where is description of the problem itself and where it is some additional information like logs, debugs, etc. 
Also it could be useful if you describe which settings for taxes are used in your system.

**Comment by grasdaggel** [comment]
Dear @sunilit42. The solution for this problem is to configure the "origin of products" in the Magento Backend. By default its set to US. Magento therefore calculates the configured tax on top of the output.

Things will be as expected once you've configured the specific things in Shop-Settings.

**Comment by andimov** [comment]
@sunilit42 
Did you try to use solution from @grasdaggel ?

**Comment by andimov** [comment]
@sunilit42 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by kumarA8** [comment]
@grasdaggel i tried your solution, this doesn't work and hence the issue is still where it was :(

**Comment by sunilit42** [comment]
@grasdaggel @andimov 
nops it is not woking.

 Magento\Quote\Model\Cart\CartTotalRepository

 $amount = $quoteTotals->getGrandTotal() - $quoteTotals->getTaxAmount();
	  $amount = $amount > 0 ? $amount : 0;
        $quoteTotals->setCouponCode($this->couponService->get($cartId));
        $quoteTotals->setGrandTotal($amount);
Here amount set directly grand total, it should be cal tax here then need to set as grand total.

**Comment by woxxy** [comment]
This is not working, the Grand Total and Base Grand Total are different even when they should not be.

vendor/magento/module-quote/Model/Cart/CartTotalRepository.php:112 has a line arbitrarily removing the tax amount:
```
$amount = $quoteTotals->getGrandTotal() - $quoteTotals->getTaxAmount();
[...]
$quoteTotals->setGrandTotal($amount);
```

There's no way to get around this via admin panel apparently.

**Comment by ghost** [comment]
Pretty sure this is still an issue. 

Request: 

    rest/default/V1/guest-carts/f5b1ae18723d2ea95d5b0e9cf74d977d/shipping-information 

Partial result: 

"totals":
  
  `{"grand_total":99.99,"base_grand_total":106.61,"subtotal":99.99,"base_subtotal":99.99,"discount_amount":0,"base_discount_amount":0,"subtotal_with_discount":99.99,"base_subtotal_with_discount":99.99,"shipping_amount":0,"base_shipping_amount":0,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":6.62,"base_tax_amount":6.62,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":106.61,"shipping_incl_tax":0,"base_shipping_incl_tax":0,"base_currency_code":"USD","quote_currency_code":"USD","items_qty":1....`


you can see base currency and currency are identical, one includes tax however.


That's happening on a clean 2.2 install.

**Comment by reillo** [comment]
I can't believe that this issue is still on latest Magento 2.2.3. Do we have any updates on how to Resolve this issue?

**Comment by lano-vargas** [comment]
Same issue here 2.2.2 Customer complains about amount charged form their bank account differs from what they see in their order history and with all the right reasons have a look at this order screen shoot :
![screen shot 2018-09-12 at 20 26 31](https://user-images.githubusercontent.com/3495481/45448520-7822dd80-b6ca-11e8-9e36-f9b17ad1aa3c.png)
 
Customer used voucher code for £ 150.00 Credit so £176.37-£150.00=£26.37 Correct 
Grand Total	£26.37 Correct
Total Paid	£121.23 Wrong 

Because of this we have to refund.

Anyone have any idea what is going on here.

Thank you in advance
