### ISSUE TITLE
Use Underscore.php

### ISSUE THREAD

**Issue by colinmollenhour** [magento/magento2#559]
PHP lacks a lot when it comes to syntax sugar, especially when working with arrays. Maybe someday this will be addressed (PHP 6?), but in the meantime there are useful tools to work around these shortcomings. One such tool is Underscore.php which is a PHP port of underscore.js.

One simple example:

```php
$options = array(
  array('label' => 'Foo', 'value' => 'foo'),
  array('label' => 'Foo', 'value' => 'foo'),
);

// PHP standard
$values = array();
foreach ($options as $option) {
  $values = $option['value'];
}

// Underscore.php
$values = __::pluck($options, 'value');
```

Sure, one can include this in their own code, but by including it in core it prevents conflicts and ensures that using it is "ok". Also it could be used to clean up some existing core code.

http://brianhaveri.github.io/Underscore.php/

Just a thought. ;)

**Comment by TexanHogman** [comment]
@colinmollenhour -- good suggestion but we did not rework any core code to leverage underscore in our platform work for the initial M2 release.  As you mentioned community can be innovative now and we'll consider core changes post 2.0.

**Comment by Vinai** [comment]
:+1:

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23851

**Comment by vpelipenko** [comment]
@colinmollenhour, as it was mentioned by @TexanHogman 'underscore' is not in our nearest plans.
