### ISSUE TITLE
Configurable Products swatch

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#5591]
Configurable product visual swatch not showing out of stock swatch it is only showing swatches of product which are in stock it has to be like and cross line or anything else at least show some difference

**Comment by antboiko** [comment]
Hi @ednacool , thanks for reporting this issue, we already have internal ticket MAGETWO-54361 to fix it.

Thanks,
Anton.

**Comment by ednacool** [comment]
Hi antboiko,

Is this possible we can check status of Internal ticket so we can give some time frame to our merchants or anything which is help full for company as well as clients

**Comment by magento-engcom-team** [comment]
@ednacool, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
