### ISSUE TITLE
Re-Index link or button not available

### ISSUE THREAD

**Issue by sunny-brevity** [magento/magento2#5592]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to Index Management page
3. There not available re-index button or link
## Expected result
1. In Index Management page should be available re-index option
## Actual result
1. In Index Management page no any re-index option available

![screenshot-localhost 2016-07-12 16-54-13](https://cloud.githubusercontent.com/assets/20418548/16765381/56c817de-4851-11e6-9106-79211684e720.png)

**Comment by Ctucker9233** [comment]
This is not a bug it is the behavior of Magento 2. It is designed to re-index by cron jobs only. Though I do wish they would bring the reindex button back (it's there in Magento 1).

**Comment by sunny-brevity** [comment]
Thank you for the update. I don't know what is the reason behind it. If it possible then please tell me what is the reason.

**Comment by ismaeljhon** [comment]
that's why every time I re-index it's on CLI ...
