### ISSUE TITLE
Issue in multistore with subdomain

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#5593]
Issue afther migrating a multistore with multidomain from M2.07 to M2.1  we can´t access to english store website subdomain in en.salelsol.eu [http://en.salelsol.eu] because always redirect to a PHPsession SID like: http://wwwsalelsol.com/?SID=oc8puthrk2v203n7usnmrtea64 [http://wwwsalelsol.com/?SID=oc8puthrk2v203n7usnmrtea64] this link running in M2.07 and works fine whe go to english store website http://en.wwwsalelsol.com.

**Comment by trasek** [comment]
We got the same problem like this.

**Comment by salelsol** [comment]
- Hi, this .htacces code works fine in Magento 2.0.7 but not in Magento 2.1
  
  RewriteCond %{HTTP_HOST} en.salelsol.eu [NC]
  RewriteRule .\* - [E=MAGE_RUN_CODE:english]
  RewriteCond %{HTTP_HOST} en.salelsol.eu [NC]
  RewriteRule .\* - [E=MAGE_RUN_TYPE:website]

I´m triyng with second method:
Method 1: Separate directories for each store using secondary domains

Verify your desired domain name points to the server.

Create a secondary domain https://docs.nexcess.net/article/how-to-add-a-secondary-domain.html for your new store.

Using either  about:blankFTP <> or  about:blankSSH <>, copy the .htaccess and index.php <> files from your Magento installation to the document root of your new domain.

Open the index.php <> file that you just copied and edit the last lines of the file as follows: 

Attention: Change newstore to the code that you wrote down when you created the new website above.

Replace:

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);

/*\* @var \Magento\Framework\App\Http $app */

$app = bootstrap->createApplication('Magento\Framework\App\Http');

$bootstrap->run($app);

With:

require **DIR** . '/app/bootstrap.php <>';

$params = $_SERVER;

$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'newstore';

$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);

/*\* @var \Magento\Framework\App\Http $app */

$app = $bootstrap->createApplication('Magento\Framework\App\Http');

$bootstrap->run($app);

Using SSH <>, create the following symbolic links in the document root of your new domain, and replace the path below with the full path to the document root of your Magento Installation:

ln -s /home/example/example.com/html/app/ app 

ln -s /home/example/example.com/html/lib/ lib 

ln -s /home/example/example.com/html/pub/ pub 

ln -s /home/example/example.com/html/var/ var 

If you have successfully configured your secondary domain to work with Magento, your new domain will load in your browser, and you may begin developing your new store.

Best Regards
Toni

**Comment by stepzerosolutions** [comment]
HI

I've set up a multistore site with to domains

http://australian.fc5.forge.co.nz
http://multidomain.fc5.forge.co.nz

Links are working fin with one luma theme and one blank theme.

However If you try http://multidomain.fc5.forge.co.nz/admin/

It gives you page isn't redirecting error

here is the Error Log

<code>
[Wed Aug 17 11:44:18.774693 2016] [access_compat:error] [pid 23] [client 172.18.0.3:33971] AH01797: client denied by server configuration: /var/www/html/public/app/etc/config.php
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.16. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 17 11:45:59.040698 2016] [:notice] [pid 19] FastCGI: process manager initialized (pid 19)
[Wed Aug 17 11:45:59.054321 2016] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.7 (Ubuntu) mod_fastcgi/mod_fastcgi-SNAP-0910052141 configured -- resuming normal operations
[Wed Aug 17 11:45:59.054653 2016] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
</code>

index.php
<code>
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'base';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'australia';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
</code>


.htaccess
<code>
SetEnvIf Host .*multidomain.fc5.forge.co.nz.* MAGE_RUN_CODE=base
SetEnvIf Host .*multidomain.fc5.forge.co.nz.* MAGE_RUN_TYPE=website

SetEnvIf Host .*australian.fc5.forge.co.nz.* MAGE_RUN_CODE=australia
SetEnvIf Host .*australian.fc5.forge.co.nz.* MAGE_RUN_TYPE=website

</code>

After Rewrite
<code>
RewriteCond %{HTTP_HOST} ^(.*)multidomain\.fc5\.forge\.co\.nz
RewriteRule .* – [E=MAGE_RUN_CODE:base]
RewriteCond %{HTTP_HOST} ^(.*)multidomain\.fc5\.forge\.co\.nz
RewriteRule .* – [E=MAGE_RUN_TYPE:website]

RewriteCond %{HTTP_HOST} ^(.*)australian\.fc5\.forge\.co\.nz
RewriteRule .* – [E=MAGE_RUN_CODE:australia]
RewriteCond %{HTTP_HOST} ^(.*)australian\.fc5\.forge\.co\.nz
RewriteRule .* – [E=MAGE_RUN_TYPE:website]
</code>

**Comment by IlnitskiyArtem** [comment]
Hi, @salelsol, thanks for the feedback.
Please add more details to your description of the steps you followed when identifying this issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
