### ISSUE TITLE
After enable full page cache customer session data not found.

### ISSUE THREAD

**Issue by hitumca** [magento/magento2#5594]
## Steps to reproduce
1. Magento 210
2. Magento Backend System-> Cache Management -> enable all cache type enable.
## Expected result
1. if($customerSession->isLoggedIn()) {
    echo "logged in Customer";
   }else
   {
      echo "Not Logged In Customer";
   }
   After enable cache every time if condition not true .
2. ...
## Actual result
1.  It should be return true in customer logged in case.

**Comment by sevos1984** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by timbaker1991** [comment]
To add to this I am able to replicate:
**Preconditions:**
Magento Version CE 2.1.1
PHP version 7.0.7
Full Page Caching Enabled
Chrome Version 53.0.2785.143 m

**Steps to reproduce with Actual and Expected Result**
When Full Page Caching is enabled this always results $customerId as null, disabling full page caching means the customerId is correctly returned.

```
$customerId = $this->_customerSession->getId();
            /**
             * Check the user is logged in
             */
            if (!$customerId) {
                return "User not logged in";
            }
```

This appears to only happen in Google Chrome. Firefox works as expected.

**Comment by Mohammed8960** [comment]
me also face same issue. is there any result ?

**Comment by anthonyherve** [comment]
I have also this issue. I try to add some custome values in CustomSession, but when I do a getCustomValue, I have nothing.
If I disable Fulle page, it's OK.
Have you an explanation please ?

Thank you.

**Comment by daniel-kratohvil** [comment]
Same here.

Setting a session using `\Magento\Framework\Session\Generic` on a custom Controller returns NULL on the Block when cache is enabled. With cache disabled it works fine.

**Comment by lucscu** [comment]
IT'S NOT A ISSUE! SEE HERE https://github.com/magento/magento2/issues/3294#issuecomment-328464943

**Comment by ritwikdatta** [comment]
I am having the same problem in Magento 2.2.1 as well .. I tried following code in a .phtml file...

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
echo $customerSession->isLoggedIn();

it did not return anything when Page Cache is ON, and when OFF I can see a value (1) printed.

**Comment by cpjeanpaul** [comment]
What about this: https://magento.stackexchange.com/a/167112/62952

**Comment by neutronixx** [comment]
If you have a custom template just put: cacheable="false" in ypur block declaration in layout: example: 

`<block class="Custom\Theme\Block\Customheader" name="custom_header" as="custom_header" 	template="Magento_Theme::html/customheader.phtml"  before="-"  cacheable="false" />`

**Comment by kazimnoorani8704** [comment]
You can try by creating an object of objectManager and **should not use objectManager directly**.

Use something like,

    class Example extends \Magento\Framework\View\Element\Template
    {
        private $_objectManager;
        public function __construct(
            \Magento\Framework\ObjectManagerInterface $objectmanager
        ){
            $this->_objectManager = $objectmanager;
        }
    
        public function getExample()
        {
            $customerSession = $this->_objectManager->create("Magento\Customer\Model\Session");
            if ($customerSession->isLoggedIn()) {
                $customerData = $customerSession->getCustomer()->getData();
                /*Your logic*/
            }
        }
    }

**Comment by aartipatel6495** [comment]
I have already added cacheable="false"  but it is not working in my custom block.
I have to clear cache then it is working.
