### ISSUE TITLE
Broken mobile menu when initializing multiple mage.menu widgets

### ISSUE THREAD

**Issue by bramvanderholst** [magento/magento2#5595]
## Steps to reproduce
1. Initialize a new mage.menu in a .phtml `<ul data-mage-init='{"menu":{"responsive":false, "expanded":true, "delay":0, "position":{"my":"left top","at":"left bottom"}}}'>`  
   (I wanted to split mobile and desktop navigation into 2 templates)
2. View website in < 768px browser
3. Open and close default mobile menu.
## Problem

Menu will close, but opens again right after.
## Possible cause

This seems to be due to setting the same onClick event multiple times on `$('[data-action="toggle-nav"]')` and `$('.nav-sections')` (in lib/web/mage/menu.js) when initializing the widget.
## Quick fix

Change

```
toggle: function () {
    if ($('html').hasClass('nav-open')) {
        $('html').removeClass('nav-open');
        setTimeout(function () {
            $('html').removeClass('nav-before-open');
        }, 300);
    } else {
        $('html').addClass('nav-before-open');
        setTimeout(function () {
            $('html').addClass('nav-open');
        }, 42);
    }
},
```

to 

```
toggle: function () {
    if ($('html').hasClass('nav-open')) {
        $('html').removeClass('nav-open');
        setTimeout(function () {
            $('html').removeClass('nav-before-open');
        }, 300);
    } else if(!$('html').hasClass('nav-before-open')) {
        $('html').addClass('nav-before-open');
        setTimeout(function () {
            $('html').addClass('nav-open');
        }, 42);
    }
},
```

**Comment by veloraven** [comment]
@bramvanderholst thank you for your report.
Please specify the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by casiandaniel** [comment]
@veloraven Please re-open the ticket! The bug is still alive (Magento ver. 2.1.4) and the related possible fix is the one proposed from @bramvanderholst!

**Comment by dfelton** [comment]
@casiandaniel per @veloraven's own recommendation, open a brand new ticket if you want to report this as an open issue.

**Comment by parveen12345** [comment]
i have some issue in my site nav toggle is not working in magento2 please help me

**Comment by ghost** [comment]
Same in magento 2.3.2
