### ISSUE TITLE
static content deployment

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5597]
Hello guys,

I have magento 2.0.7 and php 7.0.8 running on my website.
im unable to run php magento static:content-content:deploy command. everytime it gives me an error.
Despite all the folders have 755 permission and files 644. Can you give me some insight.
attaching an image for ref.
![error_static_file](https://cloud.githubusercontent.com/assets/19605497/16773785/2d0e77bc-4851-11e6-8822-d083076a0f8f.png)

Thanks a mil

**Comment by quienti** [comment]
There is an error in theme "Emthemes", it is not an error from Magento

**Comment by quienti** [comment]
There is an error in theme "Emthemes", it is not an error from Magento

**Comment by davidalger** [comment]
The issue reported appears to be with a 3rd-party component. Please work with the vendor (where applicable) to resolve the issue. Alternatively, please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical assistance. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
