### ISSUE TITLE
sql state error on magento 2.0.7

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5598]
Hi,

After i updated to 2.0.7 successfully,  it started giving me a few errors, one of them is after a customer logs in and then places a order , he gets an sql state error. only for that customer, rest dont see this error.
Can you give some advise on this. attached a ref image
![error_sales_order_key](https://cloud.githubusercontent.com/assets/19605497/16774409/b552748c-4853-11e6-8ee6-9415e5e92b35.png)

Thank you

**Comment by nmallepally** [comment]
i see series of errors like above, even when i modify the product by adding an image or call a widget as well on magento 2.0.7, iam using php 7.0.7, debian linux, Maria DB . attached some more images.
![sql state error](https://cloud.githubusercontent.com/assets/19605497/16843841/c514b4f6-49da-11e6-9294-6035c10a25f1.png)

**Comment by andimov** [comment]
@nmallepally 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by nmallepally** [comment]
Fixed when updated to magento 2.1v. Thanks @andimov

**Comment by andimov** [comment]
@nmallepally 
Thank you!
I'm closing this issue. Please feel free to reopen if you need.
