### ISSUE TITLE
Feature Request: Debug Log should not report cache_invalidate

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#5600]
## Steps to reproduce
1. Install Magento 2.1
2. Setup cron jobs as per official documentation.
## Expected result

Working installation with running cron jobs and no errors in debug log
## Actual result

Working installation with running cron job, but every time the jobs are run, a main.DEBUG: cache_invalidate: is thrown.

The way I see it, there are two ways to fix it. Code it in a way so that "notifications" (which is what this seems like) are not reported in the debug log, or create a notification.log where things like this can be written. On a side note, it would be nice to have some automated way to clear these logs.

**Comment by Ctucker9233** [comment]
Does anyone have any input on this?

**Comment by Ctucker9233** [comment]
@magento-team @magento-cicd2 @magento-admin 
Is this a reasonable feature request? Feel free to close it if it is not possible. Thanks.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Debug-Log-should-not-report-cache-invalidate/idi-p/44703).

**Comment by Ctucker9233** [comment]
@piotrekkaminski Great! Kick it to the forum where no one will ever see it.
