### ISSUE TITLE
Add new product showing error “Required parameter 'theme_dir' was not passed” magento 2.1

### ISSUE THREAD

**Issue by QuangAn** [magento/magento2#5602]
Add new product with images showing error “Required parameter 'theme_dir' was not passed”
Screenshot : http://prntscr.com/bs8ev8

**Comment by refaelgold** [comment]
how you fix it?

**Comment by refaelgold** [comment]
duplicate.. 
https://github.com/magento/magento2/issues/5294

**Comment by QuangAn** [comment]
hi, it was fixed

**Comment by abhisheks4** [comment]
When you are adding or editing product then Go to Design section and change layout option from no layout option to 1 column.

**Comment by saiful54** [comment]
Commenting out the line
vendor/magento/framework/View/Design/Fallback/Rule/Simple.php

if (in_array($placeholder, $this->optionalParams)) {
    return [];
} else {
    return [];
    //throw new \InvalidArgumentException("Required parameter '{$placeholder}' was not passed");
}

**Comment by vtransy** [comment]
I got same issue, please read here for more detail about the cause and solution

https://mrvts.wordpress.com/2018/08/21/magento-2-required-parameter-theme_dir-was-not-passed-after-manually-adding-theme-remove-theme-delete-theme/
