### ISSUE TITLE
Magento_SendFriend still shows Email link on product page when disabled

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5603]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to Admin / Stores / Configuration / Advanced
3. Set `Magento_SendFriend` to "Disable" and save config
## Expected result
1. There should be no traces of the "send to friend" functionality on the front end.
## Actual result
1. The "Email" link remains on the product page.
2. When you click on it, it goes to a blank page (probably because that functionality has been disabled)

**Comment by sevos1984** [comment]
Duplicate of https://github.com/magento/magento2/issues/6313
