### ISSUE TITLE
Bundle product customization won't update if product has just one option.

### ISSUE THREAD

**Issue by wendydek** [magento/magento2#5604]
## Steps to reproduce
1. Open a bundle product (example product: sprite-yoga-companion-kit)
2. Click on "Customize and Add to Cart"
3. Change the quantity of a bundle product with one option
## Expected result
1. The quantity should update in the "Your Customization" column.
## Actual result
1. The quantity does not update
2. https://cloud.githubusercontent.com/assets/6807650/16795608/9557ed20-48de-11e6-842b-6f0bd7e12f44.jpg

**Comment by oserediuk** [comment]
Hello @wendydek ! Could you provide your code base version?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
