### ISSUE TITLE
Can't change product suffix - SQL error

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5606]
When trying to change the product suffix in Magento 2.0.6 we get an SQL error.

Reproduce:

In Magento 2.0.6. login in to backend and move to
Shop -> Configure -> Catalog -> Catalog -> SEO Settings

**Change the suffixes here (just delete the input forms content)**
![bildschirmfoto 2016-07-13 um 10 02 28](https://cloud.githubusercontent.com/assets/13021579/16796078/060ba88e-48e1-11e6-8d68-7b7e6944f277.png)

**Output on save**
![bildschirmfoto 2016-07-13 um 10 02 37](https://cloud.githubusercontent.com/assets/13021579/16796079/060c34a2-48e1-11e6-937b-42570d008acd.png)

Seems like theres a bug with this database row? Anyone else is having this Bug?

**Comment by grasdaggel** [comment]
Any updates on this already?

**Comment by grasdaggel** [comment]
*\* friendly reminder *\* nobody has taken a look at this ticket for 10 days straight. Any Idea when we can expect an update on this?

**Comment by grasdaggel** [comment]
The problem and the problem is documented here: http://magento.stackexchange.com/questions/97130/magento2-unable-to-save-catalog-config

**Comment by veloraven** [comment]
@grasdaggel thank you for your report.
Could you please explain what is the difference from #5520?
We created internal ticket MAGETWO-56810 for this issue, but please note that it is already fixed in version 2.1.

**Comment by grasdaggel** [comment]
Oh, it seems like that I've made a mistake by creating it twice. Seems I forgot that I've reported it already. Sorry for the hassle! Closed!
