### ISSUE TITLE
Shipping Address is being ignored for flat rate Shipping, showing nothing

### ISSUE THREAD

**Issue by leechilli** [magento/magento2#5608]
## Steps to reproduce
1. Navigate to Admin -> Stores -> Configuration -> Sales -> Shipping Method
2. Setup Flat Rate Shipping
3. Use UK Full Postcodes in the Postcode fields(PO2 2PD) 
4. Set Applicable Countries to "United Kingdon"
5. Save Configuration
6. Navigate to Frontend
7. Add any Simple of Configurable product to a shopping
8. Click "Prodceed to Checkout" Button from mini shopping cart
9. Fill all required fields in the shipping form
10. Enter UK Postcode entered for Table Rate
11. Observe results 
## Expected result
1. Shipping will show price for customer's postcode
## Actual result
1. Nothing happen, doesn't display shipping Only gives "No Quote available at this time".
## Version

Magento 2.1 (Viewable here: https://188.166.170.101)
## Additional Notes

Similar to the issue  https://github.com/magento/magento2/issues/5181#issuecomment-230280405

**Comment by ghost** [comment]
I am also facing same issue in table rate shipping. 
It is working fine with registered customer but only with guest user it is not updating shipping methods based on address and zip code changes.

**Comment by neilrd** [comment]
I am experiencing the same issue with regards to table rate shipping. I am using Magento ver. 2.0.2. Similarly to @dhavalsolankidrc, it works fine with registered customers. However, for guest users, the shipping method does not update when the address is added or updated.

If the address is added and then the page is refreshed, then the shipping method does seem to be updated.

**Comment by leechilli** [comment]
Any news on this, it's affecting how I run my current magento store.

**Comment by SerhiyShkolyarenko** [comment]
@leechilli please confirm that the issue is reproducible on 2.0.0 or 2.1.1.
I tried 2.0.9 with attached [tablerates.zip](https://github.com/magento/magento2/files/524970/tablerates.zip) and didn't reproduce the issue. I've got different rates for Alabama and California.
Please add your own table rates if you manage to reproduce.

**Comment by leechilli** [comment]
@SerhiyShkolyarenko Can still reproduce the problem on 2.0.0 and 2.1.1.

You can find the zip here: http://digital-dev.co.uk/home/UK-Tablerates.zip I wasn't able to upload it as an attachment with this comment

**Comment by wsagen** [comment]
I believe the issue is because the full address details for guests are not being passed in shipping method requests - so the table rate shipping requests will not return accurate rates. 
Related to issue 
https://github.com/magento/magento2/issues/5812

**Comment by leechilli** [comment]
Hi, Any news on this?

**Comment by smoskaluk** [comment]
@leechilli Unfortunately, I could not reproduce this bug. May you please advise if this problem still relevant for latest version of Magento2?
