### ISSUE TITLE
"Store Credit" link still displayed after disabling functionality

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5609]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to Admin / Stores / Configuration / Customers / Customer Configuration.
3. Set Store Credit Options / Enable Store Credit Functionality to "No" and save.
## Expected result
1. There should be no traces of the store credit functionality on the front end.
## Actual result
1. The "Store Credit" link is still displayed in My Account.

**Comment by veloraven** [comment]
@thdoan thank you for your report.
Internal issue MAGETWO-56706 was created.
However, please, next time connect Support team for issues connecting with EE functionality.

**Comment by ishakhsuvarov** [comment]
@thdoan, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
