### ISSUE TITLE
Order comment history shows current date & time

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5611]
## Steps to reproduce
1. Install Magento 2.0.7
2. Place an order
3. Add some comments to the order
## Expected result
1. Order comment history shows date & time when comment was added
## Actual result
1. Order comment history shows **current** date & time
2. Screenshots below
- http://screencast.com/t/awvM3AGMLr4
- http://screencast.com/t/xsfWR49KC

**Comment by quienti** [comment]
Already fixed here : https://github.com/magento/magento2/commit/87f27afb8e581f47292303ac16c4685ca12e7f14

**Comment by andimov** [comment]
@werdlv
Is this fix helps you?

**Comment by jsakars** [comment]
@andimov hard to say, we are still on 2.0.7 as 2.1 is not so easy to upgrade to :)

**Comment by andimov** [comment]
@werdlv 
You can also use only this commit without upgrade.

**Comment by jsakars** [comment]
@andimov sure but doing so we would also get changes prior to given commit

**Comment by AVoskoboinikov** [comment]
Hi @werdlv 
So have you tried this fix https://github.com/magento/magento2/commit/87f27afb8e581f47292303ac16c4685ca12e7f14 ? 

I am closing this issue because of existing fix. If you have any questions feel free to create new one.

Thanks for contributing!
