### ISSUE TITLE
getInfoInstance() deprecated in MethodInterface

### ISSUE THREAD

**Issue by rikterbeek** [magento/magento2#5613]
Hi Magento,

I see in the code that the getInfoInstance() is deprecated in the MethodInterface.
This is used in many core code of magento. I am using Magento\Payment\Model\Method\Adapter class for the payment method. I use getInfoInstance() to retrieve the order to set the parameter setCanSendNewEmailFlag to false, how can I do this if this is not going to be possible in the next release of magento2 ?

Regards,
Rik

**Comment by dkvashninbay** [comment]
Hi @rikterbeek ,
Currently, there are few cases/methods where getInfoInstance can be/is used. These places were left from the legacy point of view, that MethodInterface is not a service but a model which has a state over the Payment entity. 

Now all valuable methods in MethodInterface get Payment entity as a method parameter, so MethodInterface becomes a service, meaning it can be used for most operations without reinitialization of Payment service object.

setCanSendNewEmailFlag may be accessed in gateway response handler (or in the body of authorise/capture/void/refund/etc method) without any problem, as any operation receives Payment entity as an argument.
