### ISSUE TITLE
Minicart uses module-weee template instead of module-tax

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5616]
https://github.com/magento/magento2/blob/2.1/app/code/Magento/Tax/Plugin/Checkout/CustomerData/Cart.php#L69

When prices are set to show both excl. and incl. VAT the template used is:
`$this->itemPriceRenderer->setTemplate('checkout/cart/item/price/sidebar.phtml');`

It uses the template from the WEEE module although I don't have WEEE enabled in the backend. They both share the same path and filename so I guess the WEEE module gets used as it is instantiated later than the tax module.

Is this intentional or will it be corrected in future versions?

**Comment by veloraven** [comment]
@rasmuswikman thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ghost** [comment]
We're using Magento 2.1 CE.

**Comment by magento-engcom-team** [comment]
@rasmuswikman, thank you for your report.
The issue is already fixed in develop branch, 2.1.10, 2.2.1
