### ISSUE TITLE
Product view page refresh when Click "Add to Cart" button in magento 2.1.0 ,before that not refresh in magento 2.0.X.

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#5619]
Go To product view page and click on button "Add to Cart".

**Comment by veloraven** [comment]
@pareshe thank you for your report.
Please provide description according to the template: with steps, actual result and expected result.

**Comment by pareshe** [comment]
Go to any product view page and click on button "Add to Cart". 
So in browser page is refresh, and that not have to refresh can check in magento version 2.0.X.

So in magento 2.1.0 product view page not have refresh in browser whole page when add to cart

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate of #5266
