### ISSUE TITLE
Invalid sort passed to applySorting() on Content -> Configuration page

### ISSUE THREAD

**Issue by quickshiftin** [magento/magento2#5622]
## Steps to reproduce
1. Install Magento 2.1.
2. In the admin interface, navigate to Content -> Configuration
## Expected result
1. Page loads without error
## Actual result
1. Error dialog appears "Something went wrong"

In the file _vendor/magento/module-ui/Component/Listing/Columns/Column.php_ the `applySorting` function sets the `$sorting` variable to

`array(2) { ["field"]=> string(14) "theme_theme_id" ["direction"]=> array(3) { [0]=> string(5) "false" [1]=> string(5) "false" [2]=> string(5) "false" } }`

Then tries to call `strtoupper($sorting['direction'])` which is an array in this case.

```
    /**
     * Apply sorting
     *
     * @return void
     */
    protected function applySorting()
    {
        $sorting = $this->getContext()->getRequestParam('sorting');
        $isSortable = $this->getData('config/sortable');
        if ($isSortable !== false
            && !empty($sorting['field'])
            && !empty($sorting['direction'])
            && $sorting['field'] === $this->getName()
        ) {
            $this->getContext()->getDataProvider()->addOrder(
                $this->getName(),
                strtoupper($sorting['direction'])
            );
        }
    }
```

**Comment by AVoskoboinikov** [comment]
Hi @quickshiftin,
Can you upgrade your installation to 2.1.1 and recheck if this issue is still actual? I've just checked it on my side on 2.1.1 and $sorting['direction'] always has 'asc' or 'desc' value, no arrays, no errors.

Thanks for contributing!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
