### ISSUE TITLE
No incl tax when not logged in

### ISSUE THREAD

**Issue by alcantera** [magento/magento2#5623]
## Steps to reproduce
1. did set alle tax rates and groups and so on. working als retailer,wholesale and general

only NOT LOGGED IN is not changeble
## Expected result
1. See the incl tax (119 euro ) and excl tax ( 100 euro ) when not logged in
## Actual result
1. Excl tax is show as incl en excl price.
2. ![tax](https://cloud.githubusercontent.com/assets/20442513/16809535/f7f3ffe0-4920-11e6-8739-9f23858e5078.png)

any ideas tryed a lot but it won't show the right prices

**Comment by PascalBrouwers** [comment]
Got the same issue for Magento 2.1.0
Logged in users get tax correctly. Not logged in users don't get tax (yet the customer group 'not logged in' has the same tax class as logged in users).

![screen shot 2016-09-07 at 14 49 59](https://cloud.githubusercontent.com/assets/17834386/18312601/ddd137ca-750a-11e6-8854-497943e30559.png)
![screen shot 2016-09-07 at 14 50 39](https://cloud.githubusercontent.com/assets/17834386/18312602/ddd19350-750a-11e6-85f5-3182c44a93b6.png)

**Comment by PascalBrouwers** [comment]
I did some checking. On a clean install of Magento 2.1.0 and 2.1.1 I don't have this problem.

**Comment by PascalBrouwers** [comment]
Never mind my comment. I forgot the set the product in the correct tax class. Taxes are working correctly on my 2.1.0 installation.

**Comment by IlnitskiyArtem** [comment]
@alcantera is this issue still actual?
We were not able to reproduce it on 2.1.7.
