### ISSUE TITLE
Products displayed in a random order when a filter is active

### ISSUE THREAD

**Issue by acharrex** [magento/magento2#5626]
## Steps to reproduce
1. Install Magento from `develop` branch
2. Install sample data (easy way) or create products, one category and one filterable attribute
3. Go to a product category (by example "Women > Tops")
4. Select a filter (by example "Climate > Indoor")
5. Sort products by position
## Expected result
- Products position should stay the same across page loads
## Actual result
- Products position are not persistent across page loads (when the page is reloaded, different products are displayed)
- When a list of products (filtered by one or more attributes) is displayed on several pages, same products are displayed several times
## Example

Category "Tops > Women" filtered by "Climate > Indoor":

![init](https://cloud.githubusercontent.com/assets/1983908/16812545/e0173f24-492d-11e6-8a8f-2ea4639ee473.png)

The same page but after pressing F5:

![refresh](https://cloud.githubusercontent.com/assets/1983908/16812582/03f6808a-492e-11e6-9599-856347c3a8b7.png)

The same page after a second refresh:

![refresh2](https://cloud.githubusercontent.com/assets/1983908/16812617/2c646334-492e-11e6-9e85-ad3695ea4083.png)

**Comment by SerhiyShkolyarenko** [comment]
@acharrex thank you for reporting.
I tried current magento develop branch and release 2.1.3 but didn't reproduce this issue. Both in Firefox and Chrome all goods are displayed in persistent order.
Is it still reproducible for you on current develop? Could you hint the steps from the clean installation with sample data?

**Comment by acharrex** [comment]
Thanks for your feedback.
I will check that today.

**Comment by acharrex** [comment]
I confirm.
Everything is ok with Magento 2.1.1+.

**Comment by SerhiyShkolyarenko** [comment]
Closing issue as far at it has been fixed in 2.1.x branch.
