### ISSUE TITLE
data-order-config values not properly escaped in admin panel

### ISSUE THREAD

**Issue by razoyodev** [magento/magento2#5628]
This was noticed when attempted to edit an order to add a coupon code. The issue is that the key value pairs are not being properly escaped to be placed within the content of an html attribute on an element. 
## Steps to reproduce
1. Create a customer from the admin panel. Add an address to this customer. Use a company name with an apostrophe in it such as Marcia's Flight Of Fancy. (Other fields will most probably exemplify this issue but for the sake of my test, the company name was used)
2. Create an order using this customer
3. Return to the created order, click edit. 
4. Attempt to add a coupon code. You will receive a message stating that  '"%1" coupon code was not applied. Do not apply discount is selected for item(s)',
5. Viewing the page source shows that that data in the data-order-config attribute is not properly escaped thus prematurely ending the data that is available to be passed back to the server when attempted to execute the add coupon action. 

But the issue is not that do not apply discount is selected. This message is simply the error that is noticed. This error is thrown because there is no store_id passed back to be used for getting the quote in play here due to the premature ending of the data added to the data-order-config attribute on the form element which is caused by the data not being properly escaped when echoed in the template.

This template builds this form : vendor/magento/module-sales/view/adminhtml/templates/order/create/form.phtml 

and contains this line: /\* @escapeNotVerified */ echo $block->getOrderDataJson(). You can even see in the code a comment stating that the escape has not been verified. 

This was tested in both 2.0.7 and 2.1.0

**Comment by southerncomputer** [comment]
So does it work when you wrap that with $block->escapeHtml($block->getOrderDataJson()) ?

I'm surprised a single apostrophe is causing so much trouble in address record! single quote not being quoted properly!

**Comment by southerncomputer** [comment]
data-order-config=' <--- single apostrophe so even with $block->escapeHtml($block->getOrderDataJson()) - apostrophe's will still be present!

We need to hack escapeHtml to escape apostrophe, or change the data-order-config=" double quote? but that won't stop a double quote from being present! so I think we need a better escapeHtml that will escape apostrophe's!

**Comment by southerncomputer** [comment]
ahh just upgrade to developer branch of Escaper.php, should fix that error but add more encoding to emails!

`<form id="edit_form" data-order-config='<?php echo $block->escapeHtmlAttr($block->getOrderDataJson()) ?>' `

you'll need to upgrade your AbstractBlock.php in vendor/magento/framework/View/Element/AbstractBlock.php
to developer version too.

or change the single quoting around data-order-config=".." if you want a cheap fix!

**Comment by southerncomputer** [comment]
So wouldn't this be a potential XSS scripting vulnerability? like Magento 2.1.6 and below: Cross Site Request Forgery Vulnerability

**Comment by magento-engcom-team** [comment]
@razoyodev, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
