### ISSUE TITLE
CMS Issue  - Ticket -  565353

### ISSUE THREAD

**Issue by sanchikhandelwal** [magento/magento2#5631]
Hello Team,

I want solution on priority as client is waiting for my answer.

thanks , sanchi k

**Comment by tkacheva** [comment]
@sanchikhandelwal what is the issue?

**Comment by stamster** [comment]
Ticket - 565353
So, it's Magento EE release, and internal ticketing system (help desk).

**Comment by tkacheva** [comment]
Please contact support in this case.
