### ISSUE TITLE
checkout_agreement Magento 2.1 only first entry is required

### ISSUE THREAD

**Issue by vjournal** [magento/magento2#5632]
I have made 3 Entries under store->"Terms and Conditions"
after upgrade from magento 2.0.6 to 2.1 there is only the first one an required checkbox.
On Magento 2.0.6 every Enty were required checkboxes. 
I think this must be a bug on Magento 2.1

**Comment by jcccg2016** [comment]
I´ve got exactly the same Problem. Please solve this.

**Comment by kushtra24** [comment]
Does anyone have the fix yet?

**Comment by jwittorf** [comment]
@kushtra24 try this fix, worked for me: https://magento.stackexchange.com/a/166679

P.S.: Issue still present in 2.1.6

**Comment by Bartlomiejsz** [comment]
@kushtra24, @jwittorf this is actually my code, taken from PR #6390 referenced before

**Comment by unifiedarts** [comment]
@jwittorf which magento version do you use, i tried the fix mentioned and i cannot get working

**Comment by veloraven** [comment]
@vjournal this issue is fixed in develop branch by PR #6390 mentioned by @Bartlomiejsz

**Comment by korostii** [comment]
Hi @veloraven, I see that you've added a `needs update` label.
Would you please care to explain, what kind of information you need from community in order to proceed with backporting an existing fix to the 2.1.x branch?

**Comment by keinereiner** [comment]
still not fixed in 2.1.7 !!!

**Comment by kanduvisla** [comment]
This problem still persist in 2.1.9 👎

**Comment by kanduvisla** [comment]
So I guess we can conclude that the 2.1.x-branch will never get a fix for this issue then?

**Comment by ishakhsuvarov** [comment]
@kanduvisla While fix is not available you may speed up the process and submit a Pull Request with the backport of https://github.com/magento/magento2/commit/4d89955ed19884df308fbecedb612b782bf0a88d
