### ISSUE TITLE
Not able to change currency

### ISSUE THREAD

**Issue by panneerselvam-vit** [magento/magento2#5634]
Not able to change currency in magento 2.   I tried to change it from USD to SGD.   But it is not reflected

**Comment by andimov** [comment]
@panneerselvam-vit 
Thank you for reporting!
Please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
