### ISSUE TITLE
attribute value fields

### ISSUE THREAD

**Issue by miguel-fcmoto** [magento/magento2#5636]
when you have many store-views, the fields for attribute values are very small and you need to drag the scroll bar to reach all store views. 
![attribute-value-issue](https://cloud.githubusercontent.com/assets/20454811/16832965/3873ac96-49ad-11e6-8ff6-62e4aea0d20d.jpg)

**Comment by tkacheva** [comment]
@fcmoto did you have labels on your storeviews?

**Comment by miguel-fcmoto** [comment]
yes! I only made them invisible with Photoshop

**Comment by tkacheva** [comment]
@fcmoto ok, thanks

internal ticket MAGETWO-55393

**Comment by veloraven** [comment]
I'm closing this report as the issue has been fixed.
If you can still reproduce this issue, please create new GitHub issue report.

**Comment by korostii** [comment]
Hi @veloraven, 
The commits referencing the issue seem to show up on `develop` branch only, but maybe I'm missing something.

Could you please reference the version in which this fix was released (if any)? If there isn't one, I'd say it seems a bit premature to close the issue.
