### ISSUE TITLE
magento 2 EE upgrade to 2.1.0 composer can only install

### ISSUE THREAD

**Issue by etessari** [magento/magento2#5637]
Hi,
I'm trying to upgrade from magento 2 EE 2.0.7 to 2.1.0
I'have already applied the patch **MDVA-532**, but I got some errors here's the details:
## **Steps to reproduce**
1. composer update
## **Actual result**

> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - magento/magento2-ee-base 2.1.0 requires magento/composer ~1.0.0 -> satisfiable by magento/composer[1.0.2, 1.0.0, 1.0.1].
>     - magento/composer 1.0.2 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - magento/composer 1.0.2 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - magento/composer 1.0.2 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - magento/composer 1.0.0 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - magento/composer 1.0.1 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - magento/composer 1.0.2 requires composer/composer 1.0.0-alpha10 -> satisfiable by composer/composer[1.0.0-alpha10].
>     - Can only install one of: composer/composer[1.0.0-beta1, 1.0.0-alpha10].
>     - Can only install one of: composer/composer[1.0.0-beta1, 1.0.0-alpha10].
>     - magento/product-enterprise-edition 2.1.0 requires magento/magento2-ee-base 2.1.0 -> satisfiable by magento/magento2-ee-base[2.1.0].
>     - magento/product-enterprise-edition 2.1.0 requires composer/composer 1.0.0-beta1 -> satisfiable by composer/composer[1.0.0-beta1].
>     - Installation request for magento/product-enterprise-edition 2.1.0 -> satisfiable by magento/product-enterprise-edition[2.1.0].

**Comment by vzaporozhets** [comment]
Hello Enrico,

Can you please try to contact support on this issue as it is related to EE version. Do not hesitate to write back to me if it doesn't work for you.

Thanks,
Volodymyr

**Comment by etessari** [comment]
Hi @vzaporozhets ,

I have already contacted the EE support but unfortunately they didn't provided a solution.

So I decided to workaround the problem by starting with a new installation of magento 2.1 from scratch, instead of upgrading it.
Thanks
