### ISSUE TITLE
Email validation hostname with .video TLD not working

### ISSUE THREAD

**Issue by Frits1980** [magento/magento2#5640]
## Steps to reproduce
1. Install Magento 2.1.0
2. Try to add a customer with an emailaddress ending with .video as TLD
## Expected result
1. Customer succesfully added
## Actual result
1. Get errors:
   "Email" is not a valid hostname.
   'domain.video' looks like a DNS hostname but we cannot match the TLD against known list.
   'domain.video' looks like a local network name, which is not an acceptable format.

Which is weird, because in vendor/zendframework/zend-validator/src/Hostename.php on line 805 is the .video TLD appended to the array of valid TLD's.

**Comment by hostep** [comment]
Possible duplicate: https://github.com/magento/magento2/issues/4547

**Comment by Frits1980** [comment]
Definitely duplicate. Closing this one. Thank you for the notice.
