### ISSUE TITLE
Upgrade to Magento 2.1.0 Face issue with error "Area code is already set  "

### ISSUE THREAD

**Issue by simxu** [magento/magento2#5643]
I just uploaded the code to the magento2 install directory, my old version is EE 2.0.7.
Then I do follow the instruction like below:
1、 tar -zxf Magento-EE-2.1.0-2016-06-23-02-44-02.tar.gz
2、php bin/magento  maintenance:enable
3、composer require magento/product-enterprise-edition 2.1.0 --no-update
4、composer update
5、 php bin/magento setup:upgrade

then I face below issue
 [Magento\Framework\Exception\LocalizedException]  
Area code is already set

**Comment by simxu** [comment]
any updates?

**Comment by dthampy** [comment]
@simxu, There is a patch available for customers who are facing this issue  while upgrading. Not sure if you got a chance to look at it. (MDVA-532)
http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_21-upgrade.html#tb-upgr-samp
