### ISSUE TITLE
How customize the admin email templates with filesystem?

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5644]
The frontend email templates (order_new, header, footer, etc) are ok
I create app/design/frontend/vendor/newtheme/Module/email/xxxxx.html and the template show in admin panel

but what about the backend email templates (contact submitted_form, sitemap generate_warnings, etc)?
I didn't find any information about these...

**Comment by andimov** [comment]
@ideirj 
Thank you for reporting!
Please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by pratikmage** [comment]
@ideirj  you found any solution for this issue?
