### ISSUE TITLE
Upgrade to Magento 2.1.0 do not support split database

### ISSUE THREAD

**Issue by simxu** [magento/magento2#5646]
I am using split database, I just commented areacode exception in the code(which I raised in another ticket issue 'area code is already set'.)

Then I run the php bin/magento setup:upgrade.
I got below error 

  [PDOException]  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'storewat_upgradedev2.sales_bestsellers_aggregated_daily' doesn't exist

**Comment by simxu** [comment]
any updates?

**Comment by andimov** [comment]
@simxu 
Thank you for reporting this issue!
Sorry for late reply!
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
