### ISSUE TITLE
Can't Add a new UI Component Type

### ISSUE THREAD

**Issue by astorm** [magento/magento2#5647]
## Steps to reproduce
1. Install Magento 2.1
2. Create a new module with a `definition.xml` file (see below)
3. Clear cache and reload a backend page
## Expected result
1. Configuration loads without issue
## Actual result
1. Configuration halts with Exception

> `Element 'hello_world': This element is not expected. Expected is one of ( range, tab, dataSource, paging, massaction, listing, form, fieldset, field, filters ).`
## Context

As the UI Component system is currently implemented, it is (or seems to be?) impossible for third party developers to add a new UI Component type to the system.  It's not clear if this is the intended design of the system, or an early oversight. 

The above referenced `definition.xml` file.

```
#File: app/code/Pulsestorm/SimpleUiComponent/view/base/ui_component/etc/definition.xml
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <hello_world/>
</components>
```

The exception executes because the `definition.xml` files are merged into a tree with a schema definition.

```
xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_definition.xsd"
```

The existence of this schema definition implies third party module and theme developers **should not** add a new UI Component type to the system.  However, the merging of `definition.xml` implies third party module and theme developers **can** add a new UI Component type to the system. 

Based on the current system design, it's unclear if this is a bug, or an intended restriction on to the system, or an unconsidered oversight.

**Comment by davemacaulay** [comment]
The Magento DevDocs also suggests that this file could be utilised by developers:
http://devdocs.magento.com/guides/v2.0/ui-components/ui-component.html

> UI components configuration reader searches through all active modules and read files
> <your module root dir>/<vendor>/<module>/view/<area>/ui_component/etc/definition.xml

Then later on:

> You can configure existing component and all filter types in the following ways:
> 
> Globally: using any module’s view/*/ui_component/etc/definition.xml file. All settings declared in this file will be applied to all component’s instances

**Comment by astorm** [comment]
Closing out due to lack of activity. Please reopen if this is still a priority.

**Comment by etessari** [comment]
Still have this issue on magento 2.1.5, any suggest?

**Comment by WJdeBaas** [comment]
It appears that the validation only occurs when Magento is in developer mode, see  vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php , method createDomDocument.
So, what you could do is modify the method validateDomDocument in your local development to skip the validation and return an array immediately. 
The custom component will work in the live site if that site is in production mode.
