### ISSUE TITLE
Magento 2.1 newsletter feature request: ability to manage recipients.

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5650]
It would be useful to have the ability to send newsletter selecting one or more customer groups and or adding and deleting single customers from the 'mailing list'.
Thanks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-1-newsletter-feature-request-ability-to-manage/idi-p/44702).
