### ISSUE TITLE
Empty Bestsellers Collection 

### ISSUE THREAD

**Issue by developer-lindner** [magento/magento2#5652]
## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Have some Bestsellers Data in DB.
## Expected result
1. Bestsellers Collection is not empty
2. Dashboard: Bestellers Tab shows results
## Actual result
1. Bestsellers Collection is empty
2. Dashboard: Bestellers Tab shows no results

**Comment by andimov** [comment]
@developer-lindner 
Thanks for reporting. 
Unfortunately, now it's not easy to understand what is it about, so I have to ask you provide more information.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by developer-lindner** [comment]
@andimov Just closing the tickets won't help anyone...
