### ISSUE TITLE
Magento 2.1.0 db rollback not working: Cannot execute multiple queries

### ISSUE THREAD

**Issue by flecxie** [magento/magento2#5653]
Getting the following error when trying to do a database rollback on Magento 2.1.0:

```
php bin/magento setup:rollback --db-file=1468453218_db.sql
Enabling maintenance mode
You are about to remove current code and/or database tables. Are you sure?[y/N]y
DB rollback is starting...
Cannot execute multiple queries
Disabling maintenance mode
```

I have I have MySQL 5.6.3 & PHP 5.6.22 on a Debian jessie.
Do I need any special configuration in my.cnf to allow executing multiple instructions?

Seems related to the following code in MysqlTest.php:

```
    /**
     * @expectedException \Magento\Framework\Exception\LocalizedException
     * @expectedExceptionMessage Cannot execute multiple queries
     */
    public function testMultipleQueryException()
    {
        $sql = "SELECT COUNT(*) AS _num FROM test; ";
        $sql.= "INSERT INTO test(id) VALUES (1); ";
        $sql.= "SELECT COUNT(*) AS _num FROM test; ";
        $this->_mockAdapter->query($sql);
    }
```

**Comment by flecxie** [comment]
FYI: the following WAR worked for me:
`cat var/backups/1468453218_db.sql | mysql -u MagentoUser -pMagentoPasswd MagentoDBname`

**Comment by wigman** [comment]
exact same error here

**Comment by BaDos** [comment]
Hi, @flecxie!

Thank you for your feedback.

Please, provide more detailed information about your environment.
Write list of installed php extensions.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
