### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [magento/magento2#5654]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _magento2_, deleted their software history.

https://github.com/magento/magento2/commit/4bdbf6b6ebc4b53dbde9483df745cfca7e864a36

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask magento2 developers the following four brief questions:
1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by choukalos** [comment]
Hi @gustavopinto let me introduce you to @alankent and @antonkril.  I'm sure either one of them can provide a detailed answer to this question.  This is better taken to the forum or on the side as a blog post we can link to/etc then putting in Github so I'll close the issue.

**Comment by alankent** [comment]
I only had a quick look, but I think this one may have been moving between source code repository technologies (SVN to Git) and the tools did not work well enough. But it was 5 years ago (well before I got here). The old code is also available in SVN (with history I believe), so the history has not been lost. But honestly I am half guessing since its 2 years before I joined the team.

**Comment by gustavopinto** [comment]
Hi @alankent and @choukalos, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
