### ISSUE TITLE
Product image takes too long to update when clicking on color swatches

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5655]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to /caesar-warm-up-pant.html
3. Click the different color swatches.
## Expected result
1. The product image should update immediately (or close to it) upon selecting a different color.
## Actual result
1. It takes an average of 4-5 seconds before the product image updates to reflect the new color, which I don't think is acceptable in a modern ecommerce platform. It took so long that initially I thought the functionality was broken.

This can probably be resolved by caching images for all articles after the page is loaded.

**Comment by choukalos** [comment]
Hello @thdoan can you provide some more info?
- What mode are you running in?
- Have you enabled minification and JS bundling?
- Is this the very first page you clicked on?  What happens if you click the page the 2nd time?

Thanks!

**Comment by thdoan** [comment]
@choukalos To answer your questions in order...
1. Developer mode with all caches disabled in Admin.
2. I don't recall specifically enabling or disabling this feature, so we can assume it's the default behavior in developer mode.
3. It is slow to update the product image regardless of whether it's the first time or subsequent times.

**Comment by thdoan** [comment]
UPDATE: I noticed every time you click on a swatch, there is this request:

`/swatches/ajax/media/?product_id=743&attributes%5Bcolor%5D=52&isAjax=true`

The problem is, it takes 4-5 seconds to get a response when it should be immediate since all the data that is returned is already available on the page in the `jsonConfig` object.

To fix this, I had to override the swatch click handler to look inside `jsonConfig` and update the product images accordingly. This bypasses having to wait for a response, and now the product images update almost immediately even in developer mode. The full solution is provided here:

http://magento.stackexchange.com/questions/126697/magento-2-how-to-improve-response-time-when-changing-colors/126758#126758

**Comment by antboiko** [comment]
Hi @thdoan , thanks for reporting this. We've created internal ticket MAGETWO-55815 to fix this issue.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@thdoan thank you for report. MAGETWO-55815 was closed as Won't fix. with the comment:
`Work around for customer - use Default mode with caching and selectively flush cache types as needed; production mode hits performance targets.`

**Comment by Stefan933** [comment]
@thdoan hey,i just encounted same issue,and your solution helped me for product page. Did you mabye found solution in meanwhile for /module-swatches/view/frontend/templates/product/listing/renderer.phtml 
this file is in charge for rendering images on category/list view.

**Comment by thdoan** [comment]
@Stefan933 sorry I haven't worked in Magento in years.

**Comment by Stefan933** [comment]
@thdoan Np,when i find a solution i will post it here.

**Comment by kestraly** [comment]
@Stefan933 - I guess that means no solution ha
