### ISSUE TITLE
Current article (color) not pre-selected on product page

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5656]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to /caesar-warm-up-pant.html
## Expected result
1. The current article (gray in this case) should be pre-selected on initial page load.
## Actual result
1. None of the color swatches is selected by default.

**Comment by andimov** [comment]
![screenshot_20160803_193631](https://cloud.githubusercontent.com/assets/1677746/17373617/a5e05d42-59b1-11e6-8c3c-5e3dbe11fa82.png)

**Comment by thdoan** [comment]
FYI for the time being I've patched it with this code:

**Magento_Swatches/templates/product/view/renderer.phtml**

```
// Select default color (article)
var sActiveImage = fotorama.activeFrame.img.replace(/^.+\/([^\/]+)/, '$1'),
  sActiveColorId;
for (var attributeId in oJsonConfig.attributes) {
  var oAttribute = oJsonConfig.attributes[attributeId];
  if (oAttribute.code==='color') {
    for (var i=0; i<oAttribute.options.length; ++i) {
      var oOptions = oAttribute.options[i],
        aImages = oJsonConfig.images[oOptions.products[0]];
      for (var j=0; j<aImages.length; ++j) {
        if (aImages[j].isMain && aImages[j].img.indexOf(sActiveImage)>-1) {
          // Main image (first position)
          sActiveColorId = oOptions.id;
          break;
        }
      }
      if (sActiveColorId) break;
    }
    break;
  }
}
// Click on the active color swatch
$('[option-id=' + sActiveColorId + ']').click();
```

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Current-article-color-not-pre-selected-on-product-page/idi-p/45212).
