### ISSUE TITLE
Bug fix against unintended empty categories

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#5658]
https://github.com/magento/magento2ee/pull/89

When I apply multiple rules in sequence I see that the attribute options of the first loaded rule maintain present on all the rules.
So:

I apply rule one that adds products that match dropdown attribute A's options
I apply rule two that adds products that match dropdown attribute B's options
Rule two will never match because $this->_attribute->getSource()->getAllOptions() still contains the options of attribute A.

This problem is not visible in the current setup of the visual merchandiser, but if (or when) you build a cron job that re-applies all smart category rules in sequence you will run into this problem. Since Magento 1 has such a cron job I have rebuilt it. If you are interested I could make a pull request for that. Now I was running into categories that were suddenly empty and this was the fix.
It has no impact on the current functionality.

I would really appreciate it if this fix could be applied in the next EE version.

**Comment by andimov** [comment]
@ajpevers 
Thanks for reporting this issue.
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by AntonEvers** [comment]
@andimov request to reopen this issue.

**Preconditions:**
- Magento EE 2.0.7 or higher
- Several smart categories with a few different dropdown options as smart attribute

**Steps to reproduce:**
- 1. Create a cron job that runs all smart categories in sequence, like in Magento 1.

``` php
<?php

namespace Kega\VisualMerchandiser\Model\SmartCategory;

/**
 * Class Rebuild
 * @package Kega\VisualMerchandiser\Model\SmartCategory
 */
class Rebuild
{
    /**
     * @var \Magento\VisualMerchandiser\Model\ResourceModel\Rules\Collection
     */
    protected $rules;

    /**
     * @var \Magento\Framework\Event\ManagerInterface
     */
    protected $eventManager;

    /**
     * @var \Magento\Catalog\Model\CategoryFactory
     */
    protected $categoryFactory;

    /**
     * Rebuild constructor.
     * @param \Magento\VisualMerchandiser\Model\ResourceModel\Rules\Collection $rules
     * @param \Magento\Framework\Event\ManagerInterface $eventManager
     * @param \Magento\Catalog\Model\CategoryFactory $categoryFactory
     */
    public function __construct(
        \Magento\VisualMerchandiser\Model\ResourceModel\Rules\Collection $rules,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\Catalog\Model\CategoryFactory $categoryFactory
    ) {
        $this->rules = $rules;
        $this->eventManager = $eventManager;
        $this->categoryFactory = $categoryFactory;
    }

    /**
     * Rebuild the smart category products
     */
    public function run()
    {
        /** @var \Magento\VisualMerchandiser\Model\Rules $rule */
        foreach ($this->rules as $rule) {
            /** @var \Magento\Catalog\Model\Category $category */
            $category = $this->categoryFactory->create();
            $category->load($rule->getCategoryId());
            $rule->setIsActive(1)->save();
            $this->eventManager->dispatch(
                'kega_visual_merchandiser_smart_category_rebuild',
                ['data_object' => $category]
            );
            $category->save();
        }
    }
}
```

``` xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="kega_visual_merchandiser_smart_category_rebuild">
        <observer name="category_save_merchandiser_data" instance="Magento\VisualMerchandiser\Observer\CatalogCategorySaveBefore"/>
    </event>
</config>
```

**Expected result:**
All smart categories are filled

**Actual result:**
The smart categories are filled until the category that is configured with the second dropdown attribute. From there all smart categories are empty.

**Solution:**
The `Magento\VisualMerchandiser\Observer\CatalogCategorySaveBefore` observer uses a singleton for the smart category matching attribute. The options of the first attribute it encounters are stored and cached. This model is not made to be reused for several smart categories in a row, but just for saving one category.
Because Magento 1 dod have the functionality to add new products automatically by running a smart category cron job I suspect that this functionality will be added by Magento later on or people will build it themselves as I have. To support this, use a factory to create the smart category matching attribute. It has no impact on the current functionality, but it facilitates creating a stable cron job that updates all smart categories in sequence.

https://github.com/magento/magento2ee/pull/89/commits/b2131d6bce7f4b75e190a2b62d0e83235ded75d6

**Comment by AntonEvers** [comment]
@andimov, @magento-team could you please reopen this issue

**Comment by veloraven** [comment]
@ajpevers thank you for your update.
But unfortunately this issue was reopened by mistake.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
Anyway we can not treat this issue as GitHub issue because this functionality is absent in CE.
