### ISSUE TITLE
REST API Associative Array Not Supporting

### ISSUE THREAD

**Issue by jimuldesai** [magento/magento2#5659]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create custom module with API and respond associative array like below
   $response=[];
   $response["price_format''] =[
   "pattern"=> "$%s",
   "precision"=> "2",
   "requiredPrecision"=> "2",
   "decimalSymbol"=> ".",
   "groupSymbol"=> ",",
   "groupLength"=> "3",
   "integerRequired"=> "1"
   ];

Expected result

"price_format": {
    "pattern": "$%s",
    "precision": "2",
    "requiredPrecision": "2",
    "decimalSymbol": ".",
    "groupSymbol": ",",
    "groupLength": "3",
    "integerRequired": "1"
  }
## Actual result

"price_format": [
    "$%s",
    "2",
    "2",
    ".",
    ",",
    "3",
    "1"
  ]

It can be possible by making small change in class Magento\Framework\Reflection\DataObjectProcessor as below, but unsure if it affect to other API SOAP or in core methods etc.

public function buildOutputDataArray($dataObject, $dataObjectType)
{
.
.
.
.
      foreach ($value as $elmKey =>$singleValue) {
             if (is_object($singleValue) && !($singleValue instanceof Phrase)) {
                   $singleValue = $this->buildOutputDataArray($singleValue, $arrayElementType);
             }
            $valueResult[$elmKey] = $this->typeCaster->castValueToType($singleValue, $arrayElementType)
      }
.
.
}

**Comment by develpr** [comment]
I can confirm this behavior, but FWIW I just create a simple "Map" class with a "key" and "value" to solve this myself. A few extra steps but possibly necessary with the typed nature of API results?

**Comment by jimuldesai** [comment]
Yes, with MAP class it is possible but map class changes actual keys of array. For example  in above example key "requiredPrecision" will replace with "required_precision" which in result require to make update in client(API consumer) system. Also, there are hundreds of such values require to respond in one call. 

If just maintain  key of array for type associative array, then it can save lots of efforts.

**Comment by YevSent** [comment]
Hi, @jimuldesai, thanks for reporting and sorry for so long delay. I've created the internal ticket (`MAGETWO-70164`).

**Comment by skoshpaev** [comment]
Hi, whats new for now?

**Comment by YevSent** [comment]
Hi, @daddyStan, we fixed this issue for REST API but found an issue with SOAP API and could not find the solution for it, so now it's not fixed for both APIs.

**Comment by magento-engcom-team** [comment]
@jimuldesai, thank you for your report.
We've created internal ticket(s) MAGETWO-70164 to track progress on the issue.

**Comment by mespinosaz** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@mespinosaz thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sidolov** [comment]
Hi @jimuldesai , this issue cannot be fixed because any changes to response format can break all Magento integrations and 3d party extensions and will be backward incompatible. 
Thank you for your contribution!
