### ISSUE TITLE
Dashboard Most Viewed Products Tab in admin - prices issue 

### ISSUE THREAD

**Issue by farior** [magento/magento2#5660]
## Steps to reproduce
1. Make a few configurable products
2. Give some price to configurations
3. View this products
4. Go to admin area
## Expected result
1. Most Viewed Products tab should display correct prices for products
## Actual result
1. Prices for products in Most Viewed Products tab are obtained from configurable product
2. ![86e7ed5232](https://cloud.githubusercontent.com/assets/10270387/16867602/5d3c311e-4a7b-11e6-8d3c-967cd8e99b36.jpg)
## 

Product views is stored in report_event table with configurable product ID's
Since we have no opportunity to change configurable product price, this prices will never update

**Comment by antboiko** [comment]
Hi @farior , thanks for reporting this. We've created internal ticket MAGETWO-56014.

Thanks,
Anton.

**Comment by farior** [comment]
Any update on this?

**Comment by magicbunneh** [comment]
Fix for this issue was merged:
- [magento2/develop](https://github.com/magento/magento2/tree/develop) - repo/branch
- [e82ba2e4a8491ad7b3bad36b2d8cf7e3a5a9883c](https://github.com/magento/magento2/commit/e82ba2e4a8491ad7b3bad36b2d8cf7e3a5a9883c) - commit

**Comment by veloraven** [comment]
Closed.
This issue was already fixed for develop branch.
It should be fixed soon for previous versions.
Internal ticket for ver. 2.0 - MAGETWO-64144
Internal ticket for ver. 2.1 - MAGETWO-63818

**Comment by korostii** [comment]
I've heard closed tasks are not being monitored by the Community Engineering team no more, see [here](https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/ba-p/60088#M15). Does that mean these internal tickets for 2.0 and 2.1 won't be a priority neither?

If that the case, could you please keep the issue open? It would be a pity to see it being forgotten about, and lost, and reported again.

**Comment by veloraven** [comment]
@korostii I will not reopen this issue but we have the new one with the same problem but better description - #9768. It will stay open for now.

**Comment by korostii** [comment]
Thanks @veloraven, glad to hear that.
