### ISSUE TITLE
Bundle products being added as upsells but not being shown in admin panel.

### ISSUE THREAD

**Issue by ErikPel** [magento/magento2#5665]
## Steps to reproduce
1. Make bundle product and add options to it.
2. If I understand correctly the bundle product is being added as upsell by Magento\Bundle\Observer\AppendUpsellProductsObserver (? correct me if I'm mistaken)
3. check the simple products page and go to advanced settings -> upsells
## Expected result
1. All the upsells are being shown in  advanced settings -> upsells
2. I could edit/delete these upsells in  advanced settings -> upsells
## Actual result
1.  The upsells grid is empty
2. Only way I know I have upsells is when I go to the simple product set as option page is that I can see the bundle product in "We found other products you might like!" box (frontend)

**Comment by pboisvert** [comment]
@ErikPel can you provide version information for where this issue was observed? Was this a clean install or an upgrade to latest version?

**Comment by ErikPel** [comment]
2.0.6

I think it's upgraded from 2.0.2

**Comment by JoshuaSoileau** [comment]
Any update on this issue? I'm seeing this as well.

**Comment by pboisvert** [comment]
@antboiko can you have the team check into this one?

**Comment by JoshuaSoileau** [comment]
I am on EE 2.0.7 for the record.

**Comment by JamesonNetworks** [comment]
I am seeing this as well

**Comment by magento-engcom-team** [comment]
@ErikPel, thank you for your report.
We've created internal ticket(s) MAGETWO-82987 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @ErikPel

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@ErikPel, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by ChrHartwig** [comment]
I found out, that this is not a bug, it's a magento feature.

Magentos bundle module has an observer (frontend/events.xml) who listenes to the event called 'catalog_product_upsell'. See here:

`<event name="catalog_product_upsell">
        <observer name="bundle_observer" instance="Magento\Bundle\Observer\AppendUpsellProductsObserver"/>
    </event>`

The observer (magento/module-bundle/Observer/AppendUpsellProductsObserver.php) loads all bundles, the product is applied to, and adds these bundles to the collection of upselling products.

To disable this feature, just disable the observer in the xml.

Greetings,
Christoph

**Comment by jajajaime** [comment]
Thanks, @Neusta-Hartwig. Your solution works as expected!

**Comment by adarshkhatri** [comment]
> catalog_product_upsell

How do I do it without editing the core file?
I know I could do this in my module:

```
    <event name="catalog_product_upsell">
        <observer name="bundle_observer" disabled="true"/>
    </event>
```

But I see there is another observer given same name `bundle_observer` 

```
<event name="catalog_product_upsell">
        <observer name="bundle_observer" instance="Magento\Bundle\Observer\AppendUpsellProductsObserver"/>
    </event>
    <event name="product_option_renderer_init">
        <observer name="bundle_observer" instance="Magento\Bundle\Observer\InitOptionRendererObserver"/>
    </event>
```

**Can anyone confirm disabling as I mentioned above will not break anything else.**

**Comment by jajajaime** [comment]
@adarshkhatri You do it exactly like that. In your module you just disable the observer for the event you want on your events.xml file.
Observer names are per event definition, so disabling the one for `catalog_product_upsell` won't affect the one in `product_option_renderer_init`.
You can read more about it on this section of the docs https://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html#subscribing-to-events
