### ISSUE TITLE
Design Menu does not work.

### ISSUE THREAD

**Issue by futuralis** [magento/magento2#5667]
## Steps to reproduce
1. Install Magento using composer
2. Login to Admin
3. Go to Stores->Settings->Configuration->Design
## Expected result
1. View Design Menu with ability to change Theme.
## Actual result
1. Design options do not show. The tab is incorrectly pointing to the wrong option. Instead Search Engine Robots form is being shown.
2. Attached is a screenshot.
   <img width="1668" alt="screenshot 2016-07-15 11 09 06" src="https://cloud.githubusercontent.com/assets/4015550/16879585/3b3475be-4a7f-11e6-823c-857e6d1a3c69.png">

**Comment by pboisvert** [comment]
This area has been moved under the Content top-level menu item (see Content > Design ) and we will be relabeling the Stores > Configuration > Design tab to reflect the content. Closing as this is not a code issue

**Comment by southerncomputer** [comment]
Are you using 2.1.0? Because design has been moved (it caught me too!) to Content->design->configuration in 2.1.0 :-1: 

It's a bug the menu is still there ! yes!

**Comment by futuralis** [comment]
Thanks for letting me know.

Thanks,
Aravind Pamula

Consultant
Coretechs Consulting Inc.
301-949-2553 x711
www.coretechs.com
