### ISSUE TITLE
Invalid apostrophes in search_synonyms_form.xml

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5669]
search_synonyms_form.xml invalid apostrophe characters:

`<item name="description" xsi:type="string" translate="true">Comma-separated list of synonyms. The terms entered (separated by commas) will be used as an “OR” search query to search your entire store. For example, if you enter “shoes,footwear”, and user were to search for "shoes", the search results will include any product or content with term “shoes" or "footwear.”</item>`

so why the translation doesn't work fine...

**Comment by pboisvert** [comment]
It is not clear the problem you are reporting or the version in which you are finding an issue. Please follow the issue reporting template and describe the version, the expected result, and the actual problem you are seeing.

**Comment by ideirj** [comment]
magento 2.1
see the search_synonyms_form.xml file 
 “OR” 
 “shoes,footwear” 
 "shoes" 
“shoes"  
"footwear.”

the apostrophes are not the standard " " characters

**Comment by andimov** [comment]
@ideirj 
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
