### ISSUE TITLE
https://github.com/magento/magento2/issues

### ISSUE THREAD

**Issue by dhavalkaneriya** [magento/magento2#5673]
## Steps to reproduce

I have installed fresh magento 2.1.0 in my wamp server 3.0 I have done with all changes required to install magento 2.1.0 in wamp and it's work fine.

Now I have created my theme on below path : D:\wamp\www\magento2.1\app\design\frontend\Ecommerce\m2-theme

In my theme I have copied whole D:\wamp\www\magento2.1\vendor\magento\theme-frontend-luma folder and change 3 important files theme.xml , registration.xml and composer.json.

Now I go to admin > content > design > configuration and my theme is showing there for Globle , Main website and main website store 

Expected result

 when I assign my theme and do save it's should be save changes and show my theme in front end.

Actual result

I get below error when I save changes.

Cannot read contents from file "D:/wamp/www/magento2.1/" Warning!file_get_contents(D:/wamp/www/magento2.1/): failed to open stream: No such file or directory

**Comment by maderlock** [comment]
This sounds like you need help with your installation permissions rather than this being a Magento bug. Please try http://magento.stackexchange.com/ or the Magento forums. Not sure how well windows environments are supported. Feel free to come back here if it turns out to be a Magento bug.

**Comment by dhavalkaneriya** [comment]
I have already asked question on http://magento.stackexchange.com/questions/125994/admin-design-configuration-does-not-save-in-magento-2-1-0.

Please check this. and this issue is not some think that I'm only facing I show other questions that are same on magento2 issues github.

**Comment by andimov** [comment]
@magemagic7 
Thanks for reporting!
To allow us to research the issue in github, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by shashankitsoft** [comment]
I was also facing the same issue. This issue was also reported earlier #5288 . 
The solution and explanation here http://magento.stackexchange.com/questions/125994/admin-design-configuration-does-not-save-in-magento-2-1-0 perfectly helped. Need to be fixed by Magento guys.

**Comment by oserediuk** [comment]
Hello @magemagic7 ! Do you use this guide http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html?

**Comment by andimov** [comment]
@magemagic7 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
@shashankitsoft 
Thank you for solution!
