### ISSUE TITLE
[2.1] Order status labels for stores not saving

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#5675]
## Preconditions
1. Install Magento 2.1.0
## Steps to reproduce
1. Create multiple stores (uncertain this is required for the issue)
2. Edit order status and set labels per store.
3. Save and click of status again.
## Expected result
1. To see the statuses I just entered
## Actual result
1. Blank status labels

**Comment by rarango** [comment]
I have the same issue. I thought it could be some kind of cache problem, but it is not. It is the same if you fill just one or several store labels.

Any clue?

**Comment by AVoskoboinikov** [comment]
Hi guys!

Thank you for your contribution. I have created internal ticket for this bug #MAGETWO-58297. This issue will be closed after fix.

Have a nice day!

**Comment by oefterdal** [comment]
I am experiencing the same bug.

**Comment by stephan-cream** [comment]
This issue is still there.
Using Magento version 2.1.6.

**Comment by palvinder03** [comment]
How we can solve by create file or by adding any kind of code?
Using Magento version 2.1.7.

**Comment by springerin** [comment]
Magento 2.1.9 still having the issue

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
