### ISSUE TITLE
[M2.1] - No CLI option to exclude patterns on setup:di:compile and other inflexibilities

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#5676]
```
php bin/magento
Magento CLI version 2.1.0
```

On previous versions, we've been told to use `setup:di:compile-multi-tenant` instead of `setup:di:compile`. K. Now [we're told](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-compiler.html) to get back to using `setup:di:compile`. Ugh, fine.

But whilst you were fixing (?) `setup:di:compile`, we've gotten accustomed to `setup:di:compile-multi-tenant`'s [various and useful CLI options](https://github.com/magento/magento2/blob/2.0/setup/src/Magento/Setup/Console/Command/DiCompileMultiTenantCommand.php#L128-L159), which - yep - `setup:di:compile` does _not_ have. And now that `setup:di:compile-multi-tenant` is gone, we're left with no.. option:

```
php bin/magento help setup:di:compile
Usage:
 setup:di:compile

Options:
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question
```

One of the more useful options which is now kaput was `--exclude-pattern`. That allowed us to omit certain files which we didn't want compiled, ofc. [But now we're stuck with whatever you thought it was good for your scenarios](https://github.com/magento/magento2/blob/989af631d7ea7365f694e5cb0003a94ab49eb54d/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php#L143-L154).

Can we get `setup:di:compile` to be as flexible as `multi-tenant` was? If not the _same_, at least allow us to inject our own exclude patterns. 

PS: I hope I won't be asked "Can you give me an example of a scenario in which you need to exclude something?". Just trust me on this one, mkay?

**Comment by choukalos** [comment]
Why are you asking for this - is the primary purpose to improve performance?  Or is there another purpose?

If performance and we can save significant time by not re-compiling something, shouldn't we just automatically detect and skip if at all possible?  Would that work or as mentioned above there's another reason for keeping exclude patterns?

I'm tracking improvements in compiler performance internally as (MAGETWO-54054).  If exclude patterns then that'd need to be another ticket.

Thanks!
Chuck

**Comment by adragus-inviqa** [comment]
Hi, @choukalos. Not performance, but an edge case. 

I've created a custom installer, emulating the M1-style upgrade scripts. Those scripts _are not in a class_ (but included), and the compiler breaks. I consider the exclusion pattern CLI option to be quite necessary, not only for my own particular scenario, but because there could be many in my situation who want to be able to exclude certain files, _for various reasons_.

Again, I think it's a little unfair that you [hard-code exclusions](https://github.com/magento/magento2/blob/989af631d7ea7365f694e5cb0003a94ab49eb54d/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php#L143-L154) without giving us a point of extension.

**Comment by choukalos** [comment]
Hi @adragus-inviqa that's for the update.  

@piotrekkaminski looks like this one is in your area.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/M2-1-No-CLI-option-to-exclude-patterns-on-setup-di-compile-and/idi-p/48447).
