### ISSUE TITLE
[Feature request] Add search boxes for some elements in admin

### ISSUE THREAD

**Issue by qmarlats** [magento/magento2#5678]
For some elements in admin, it's (really) difficult to find what we search for. For example, in list of countries like "Top Destinations" (see picture), we have to look for one country at a time and select what we want slowly and without any error (otherwise we have to begin again). Even more horrible is time zones: the first time I searched for Paris I've spent about 3 minutes.
So I think it would be a great usability improvement to use [something like that](https://harvesthq.github.io/chosen/#multiple-select)!

![capture d ecran de 2016-07-17 20-39-13](https://cloud.githubusercontent.com/assets/3251811/16902457/26933b90-4c5f-11e6-8f11-5f2631e336cb.png)

**Comment by tkacheva** [comment]
Hi @qmarlats,
Is this about custom attribute input type only or there are places in default configuration that seems to have similar issues?

**Comment by qmarlats** [comment]
There are these kind of forms everywhere, starting at the installation for the time zone selection, then after in Magento configuration (like on the screenshot in my first post).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Add-search-boxes-for-some-elements-in-admin/idi-p/45202).
