### ISSUE TITLE
Magento 2: Product Advanced Options tab is not visible

### ISSUE THREAD

**Issue by flpavoncelli** [magento/magento2#5679]
I have a recent installation of Magento 2.1 and the Advanced tab on the product page does not appear.  I was trying to set the Description and Short Description, but I cannot access that tab therefore I am stuck.

**Comment by onakonechna** [comment]
Description and Short Description are inside of Content collapsible panel

**Comment by andimov** [comment]
@flpavoncelli 
Thanks for reporting!
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
