### ISSUE TITLE
Media gallery loading broken by 2.1 update

### ISSUE THREAD

**Issue by moloughlin** [magento/magento2#5680]
We'd like to be able to use the media gallery of a product within the category and search pages. In Magento 2.0 (and M1), we could load the gallery onto a product reasonably cheaply using the following:

`$product->getResource()->getAttribute('media_gallery')->getBackend()->afterLoad($product);`

In 2.1 this no longer works due to _media_gallery_ being changed into a static attribute, without it's own backend. I've attempted to add it onto the collection instead using `addAttributeToSelect('media_gallery')`, but so far the only way I've been able to force the load is by invoking the load function on each product individually (which is obviously terrible performance on a PLP):

```
foreach($products as $product){
    $product->load();
    $images = $product->getMediaGalleryImages();
}
```

Diving into the AbstractCollection::_loadAttributes method, I found that the attribute will be excluded from loading because it's defined as a static type:

```
if ($attribute && !$attribute->isStatic()) {
    $tableAttributes[$attribute->getBackendTable()][] = $attributeId;
    if (!isset($attributeTypes[$attribute->getBackendTable()])) {
        $attributeTypes[$attribute->getBackendTable()] = $attribute->getBackendType();
    }
}
```

Is there a correct way to get this attribute onto the collection load which I'm not seeing, or is this a bug in the 2.1 release?

**Comment by franckgarnier21** [comment]
Hello,

You are right, the way to retrieve product gallery images has changed in Magento 2.1

You need to follow these instructions : http://magento.stackexchange.com/questions/112497/magento-2-get-all-product-images-in-on-product-list-page

To sum up:
1.  You need to inject this class : 
`Magento\Catalog\Model\Product\Gallery\ReadHandler as $galleryReadHandler`
2. Then you need to execute this method : 
`$this->galleryReadHandler->execute($product);`
3. Then retrieve the gallery images : 
`$galleryImage = $product->getMediaGalleryImages();`

Thanks,

**Comment by patrick-bigbridge** [comment]
Thanks for the explanation. The DataObject objects returned by getMediaGalleryImages() provide many interesting facts, but not the "roles" of the image (i.e. base, small, thumbnail, swatch). I would like to filter just the swatch image, if possible.

**Comment by veloraven** [comment]
@moloughlin is this issue still actual?
Please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) with questions as GitHub issue tracker is intended for technical issues only.
