### ISSUE TITLE
getModuleName() doesn't return correct module name

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#5683]
Ok, I was trying to retireve name of module in custom Helper class, basing on  received request from controller:
Method getModuleName() for controller doesn't return right dir:

`$test = $this->getRequest()->getModuleName();
       print_r($test);`

Method is used inside controller - path is `[vendor][module_name]\Controller\Test\Test.php` and method return `test`, so the name of action. I think it should return `[vendor][module_name]`.

Moreover similar method called on base of Helper `Context` class works as it should be, name of module is correct:
`private function getXmlPath()
    {
        $filePath = $this->dirReader->getModuleDir('etc', $this->_getModuleName());
        $this->_xmlPath = $filePath;
        return $this;
    }
`

**Comment by andimov** [comment]
@bartek9007 
Thanks for reporting!
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by bartoszkubicki** [comment]
@andimov updated.

**Comment by veloraven** [comment]
@bartek9007 is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by bartoszkubicki** [comment]
In Magento 2.1.1. it works fine. Thank you for your support!
