### ISSUE TITLE
[CE 2.1.0] pb on cache for method loadAllAttributes

### ISSUE THREAD

**Issue by spipu** [magento/magento2#5684]
hi,

in this class https://github.com/magento/magento2/blob/develop/app/code/Magento/Eav/Model/Entity/AttributeLoader.php#L68

the used cache key is directly the entity type code of the object, but the method $this->config->getEntityAttributeCodes use the attribute set of the current object to build the cache => it could be a good think to add the id if the attribute set in the cache key.

for example:

```
    {
        $typeCode = $resource->getEntityType()->getEntityTypeCode();
        $cacheKey = $typeCode;
        if (!is_null($object) && $object->getAttributeSetId()) {
            $cacheKey.= '-'.$object->getAttributeSetId();
        }
        $attributes = $this->cache->getAttributes($cacheKey);

        ...

        $this->cache->saveAttributes($cacheKey, $attributes);
        return $resource;
    }
```

**Comment by andimov** [comment]
@spipu 
Thanks for reporting!
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by spipu** [comment]
it has been fixed, thanks

https://github.com/magento/magento2/commit/e431f61887d785f0e993fd45c6c5f294b24a1c0b
