### ISSUE TITLE
getRemoveParams() missing wishlist item id

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5685]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Register and log in.
3. Navigate to any product page and add it to the wishlist; return to the product page.
4. Add the following code to `Magento_Catalog/templates/product/view/addto.phtml`:

```
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
print_r($wishlistHelper->getRemoveParams($_product));
```
## Expected result
1. If the product is in the wishlist, `getRemoveParams()` should populate the `item` property in the returned object with the product's wishlist id.
## Actual result
1. The `item` property in the returned object is null, e.g.:

```
{"action":"...","data":{"item":null,"uenc":"aHR0cHM6Ly9tdWNrYm9vdHVzZGV2MDIuc3BlY29tLmlvL2NhZXNhci13YXJtLXVwLXBhbnQuaHRtbA,,"}}
```

Right now we have to do a hack whereby we manually set the `item` value by doing something like this:

```
$_wishlistItem = $wishlistHelper->getWishlistItemCollection()->addFieldToFilter('product_id', $_product->getId());
if (count($_wishlistItem)) $wishlistId = $_wishlistItem->getFirstItem()->getId();
```

If `getRemoveParams()` works as intended, then we wouldn't have to implement this workaround.

**Comment by SerhiyShkolyarenko** [comment]
Hi @thdoan! Thank you for reporting issues!
I performed steps 1-4, cleaned cache(both server and browser), refreshed page. On click "Add to cart" I've got an error like "Undefined variable: $_product" once.
Could you please clarify the steps to reproduce?

**Comment by thdoan** [comment]
@SerhiyShkolyarenko At the top you should have something like this:

```
<?php
$_product = $block->getProduct();
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
```

**Comment by SerhiyShkolyarenko** [comment]
@thdoan getRemoveParams() is very old method and annotations seems deprecated. Product model shouldn't contain info about wishlist item id. Please, try to pass wishlist item to getRemoveParams().

**Comment by thdoan** [comment]
"Please, try to pass wishlist item id to getRemoveParams()" -- Sorry, I don't understand this. My original issue was in regards to using `getRemoveParams()` to retrieve the wishlist item id -- if I already have the id then I wouldn't need to pass it to `getRemoveParams()`.

Are you saying that my current workaround is the best method for getting the wishlist item id on the product page right now?

```
$_wishlistItem = $wishlistHelper->getWishlistItemCollection()->addFieldToFilter('product_id', $_product->getId());
if (count($_wishlistItem)) $wishlistId = $_wishlistItem->getFirstItem()->getId();
```

**Comment by SerhiyShkolyarenko** [comment]
According to modularity approach entities from Catalog module(category, product) shouldn't know _anything_ about inventory, rules, taxes, wishlists, etc. getRemoveParams() method relies on $item->getWishlistItemId(). It means product object is implied to be initialized somewhere. It's not a reliable way. Your approach is more stable.
As far as we clarified the situation I close the issue. If you have additional questions please write here, the issue will be reopened.
