### ISSUE TITLE
inserting URL rewrites fails

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#5687]
## Steps to reproduce
1. Install Magento 2.1.
2. Add around 50000 visible products.
3. Add around 1000 visible categories in a tree.
4. Make sure that one of the categories (say A) has around 20000 products.
5. Change the URL key of category A, making sure that "Create Permanent Redirect for old URL
   " is checked. Save the category.
6. Keep changing the URL key of category A (with "Create Permanent Redirect for old URL
   " checked) until saving does not work anymore.
## Underlying problem

In the class `\Magento\UrlRewrite\Model\Storage\DbStorage` in method `doReplace()` all the URL rewrites are inserted at once. Depending on number of products in the category and the number of previous URL keys, the amount of URL rewrites to insert can become huge. The MySQL-Database should be configured to only allow limited packet sizes, so when too many URL rewrites get inserted at once, you get the following error:

```
[Zend_Db_Statement_Exception]                                                
  SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than   
  'max_allowed_packet' bytes, query was: INSERT INTO `url_rewrite` (`redirect  
  _type`,`is_autogenerated`,`metadata`,`description`,`store_id`,`entity_type`  
  ,`entity_id`,`request_path`,`target_path`) VALUES (?, ?, ?, ?, ?, ?, ?, ?,   
  ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), ...
```
## Possible fix

Insert the URL rewrites in chunks.

**Comment by Yonn-Trimoreau** [comment]
+1

**Comment by bh-ref** [comment]
issue is still present in 2.1.4

**Comment by orlangur** [comment]
So, what is the "issue" here? `max_allowed_packet` needs to be configured according to your Magento instance needs, just like exception message says.

> Insert the URL rewrites in chunks

All inserts must be performed in one transaction to avoid data corruption in case you met collision. And increasing size of data infinitely you have no way to not reach some configuration limit: http://dba.stackexchange.com/a/19580

**Comment by bh-ref** [comment]
@orlangur thank you for your hint. we are now using a "chunk solution", but will have look at your solution.

**Comment by vrann** [comment]
@ktruehl I agree, this is a known issue and solution proposed by @orlangur should work.

``max_allowed_packet`` is a MySQL configuration which determines the size of the input data allowed by the query. If it is too low, MySQL just rejects the query which causes issues you see. Here is documentation: https://devdocs.magento.com/guides/v2.1/install-gde/prereq/mysql.html

Please reopen if it does not.
