### ISSUE TITLE
Fist Image Change Only. In Color Attributes Select.

### ISSUE THREAD

**Issue by kongkiat** [magento/magento2#5691]
## Steps to reproduce
1.  Admin->Products->Catalog
2.  Press new product  
3.  Add New product and Image
4.  Add Configurable product and Image many image 
## Expected result
1. Select Product in product detail
2. All Imange change.
## Actual result
1. First Image Change Only

Magento Version 2.0.7. No Problem. Buy Mangeto 2.1.0 RC 3 Have this problem.

![front](https://cloud.githubusercontent.com/assets/2352144/16922231/f8f7c008-4d3e-11e6-91ad-4c785abd9ff4.jpg)

![black](https://cloud.githubusercontent.com/assets/2352144/16922164/af9e00d4-4d3e-11e6-9174-d0669b92c421.jpg)

**Comment by antboiko** [comment]
Hi @kongkiat , thanks for reporting. We've created internal ticket MAGETWO-55702 to track this issue.

Thanks,
Anton.

**Comment by vivek201** [comment]
Just checked it on a sample Magento 2.1. Any update on this issue?

**Comment by ritschi72** [comment]
We still face that problem with Magento version 2.1.2

**Comment by magento-engcom-team** [comment]
@kongkiat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
