### ISSUE TITLE
adminhtml_customer_save_after event not dispatching from admin grid customer update Magento 2.1.0

### ISSUE THREAD

**Issue by sky4git** [magento/magento2#5692]
## Steps to reproduce
1. Go to admin > Customers > All Customers
2. Try to update/change customer info[inline edit] from grid. 
3. Save customer. Which will fire Ajax event and update customer info.
4. Use custom observer to cache '**adminhtml_customer_save_after**' event.
## Expected result
1. In above case, the event '**adminhtml_customer_save_after**' never actually being fired. It only works if we actually click **edit** and **save customer** after changing info. 
## Actual result
1. Inline edit actually saves the customer, but do not fire 'adminhtml_customer_save_after' event, so any custom observer depends on that event never actually get chance to run.
2. In my case, I am sending email using the observer.
## Images 

![customer-update-from-admin-grid](https://cloud.githubusercontent.com/assets/8438024/16939820/63c93bbc-4dc8-11e6-8bc4-22f408e3b1c0.JPG)

**Comment by slavvka** [comment]
Hi @sky4git, This is not a bug. **adminhtml_customer_save_after** event is fired in \Magento\Customer\Controller\Adminhtml\Index\Save and must not be used for customer persisting purposes, while you are talking about different controller \Magento\Customer\Controller\Adminhtml\Index\InlineEdit. Please use plugins or common model events.like **customer_save_after**
