### ISSUE TITLE
setup:static-content:deploy should bust browser cache by using unique filesnames

### ISSUE THREAD

**Issue by kweij** [magento/magento2#5694]
When performing a deployment, `bin/magento setup:static-content:deploy` needs to be executed to deploy the new static view files. These files also include `.js` and `.css` resource files that will be cached by browsers.

It's ok that browsers cache these files, but when these files are re-created on a next execution of `bin/magento setup:static-content:deploy`, there is **new** content in files with **the same** filename. This causes the browser not to update the cached files and the site will no longer function properly or at all because old `.js` files are used by clients.

I can't tell all clients to clear their browser cache. The command `setup:static-content:deploy` should generate new files (new content) using a unique filename zo browser cache will be busted.

**Comment by Zaylril** [comment]
The main reason being that requireJS includes files via their filename in the module definition. If you were to change the names of the files, it would not be able to load these files in as they would no longer be there.

You would have to match each instance of each file in the module definition and update the config file and each file internally as well with the new file name. Including custom files. Which would be very error prone.

I agree they need to fix the issue of caching and also intelligent bundling - which by proxy would fix this issue as you could modify the packaged bundle file name quite easily, providing the cache busting you needed.

The best way to fix this currently is to deploy the files to a new folder each time and rewrite this via ngnix - so it would serve the files from /static/frontend/Magento/default/en_GB/static_v1.00/ - just as an example

**Comment by kweij** [comment]
Deploying the files to a new folder is a workaround that I may try, thanks.

**Comment by nagno** [comment]
That is why the static file signing is implemented, it will generate a version number in your URLs.
You can turn it on in system > stores > advanced > developer > static file settings > sign static files => yes

**Comment by kweij** [comment]
Thanks @nagno, that is indeed the solution to the problem I stated.

**Comment by lucscu** [comment]
Is your versionXXXXXX folder created automatically when run deploy?

**Comment by nagno** [comment]
@LucScu nope, it should be handled by your web server configuration via URL rewrites.

**Comment by lucscu** [comment]
@nagno so after any deploy have i to change also webserver conf?

**Comment by nagno** [comment]
@LucScu 
nope, we are using nginx, and the relevant lines are already in the config file:
https://github.com/magento/magento2/blob/2.0.10/nginx.conf.sample
92, 101, 105

However if you are using apache, please check it

**Comment by lucscu** [comment]
@nagno So have i to create the versionXXXXXX folder where XXXXXX is the "deployed number version"? And after any deploy have i to rename the version folder?

**Comment by nagno** [comment]
As far as I know, you don't have to.
The mentioned lines in the web server configuration should match any of the versionXXXXXX directories and should send the traffic to the correct path

**Comment by lucscu** [comment]
Is your magento setted to `production mode`?
Do you know that in production mode magento returns 404 for files not present on file system?
So if nginx enters in

```
location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
        expires +1y;

        if (!-f $request_filename) {
            rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last; // HERE
        }
    }
```

magento returns 404.
i'm wrong?

**Comment by nagno** [comment]
We have a production instance as well however that is managed by our hosting partner and it is using apache. I have no idea, what are the settings there, because we don't have SSH access to that box.

Regarding the production mode: In production mode you have to run the static content deployment, so the file should be there physically without the versionXXXXXX directory.
The `//HERE` line rewrites your request to use the static.php to find it's location if the file is not available in the requested path.
If that rewrite doesn't work for you and don't want to use static.php to figure out the location, then you can use a rewrite something like this (I'm not 100% sure this is a working one, but it should be similar to this):

```
rewrite ^/static/version\d*/(.*)$ /static/$1 last;
```

So again: you don't have to create the directory, you can handle it via your web server configuration.

**Comment by lucscu** [comment]
Thx @nagno.
I think my problem is webserver redirect, because even if `pub/static/_requirejs/adminhtml/Magento/backend/en_US/secure/requirejs-config.js` exists on filesystem, if i link it from browser
`https://mydomian.com/static/version1479296115/_requirejs/adminhtml/Magento/backend/en_US/secure/requirejs-config.js`
it returns

```
Unable to resolve the source file for '_requirejs/adminhtml/Magento/backend/en_US/secure/requirejs-config.js'
#0 /usr/share/nginx/kamiceria/htdocs/vendor/magento/framework/App/StaticResource.php(97): Magento\Framework\View\Asset\File->getSourceFile()
#1 /usr/share/nginx/kamiceria/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch()
#2 /usr/share/nginx/kamiceria/htdocs/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#3 {main}
```

**Comment by nagno** [comment]
yes, probably you have to fix that rewrite.

**Comment by lucscu** [comment]
@nagno thx you very much, you help me to find the problem, now i could try yo fix it.

**Comment by bvboas** [comment]
@LucScu  Did you manage to fix this?

I'm having the same problem.
