### ISSUE TITLE
${magento_host}/rest/V1/customers/me does not return the requesting Customer

### ISSUE THREAD

**Issue by mohanbmahajan** [magento/magento2#5695]
## Steps to reproduce
1. Started magento from https://hub.docker.com/r/alexcheng/magento2/
2. Created access token using rest/V1/integration/admin/token api
3. Get signed in users details
## Expected result
1. Should get details for the signed in User
## Actual result
1. Getting,
   {
   "message": "%fieldName is a required field.",
   "parameters": {
       "fieldName": "customerId"
   }
   }

**Comment by mbrinton01** [comment]
@mohanbmahajan please provide the call you are using in Step 3.

**Comment by mohanbmahajan** [comment]
@mbrinton01 I was using /rest/V1/customers/me using admin token.

**Comment by mbrinton01** [comment]
Hello @mohanbmahajan the admin token is not required.  The route `rest/V1/customers/me` can be used by a logged in user without a token to return information about that customer.  Please try the following:
1. Go to storefront in browser
2. Create user account
3. Login to user account
4. Enter URL `http://<hostname>/rest/V1/customers/me`, replacing `<hostname>` with the server you are using

This will return information about the logged in customer directly to your browser.  If you want to get information about any other customer, you will need to generate an admin token and use it with the route `GET /V1/customers/{customerId}`

Please let me know if this resolves your issue.

**Comment by mohanbmahajan** [comment]
I wanted to retrieve the customer info using rest APIs not using web interface.
I think I was doing it wrongly.. I have to get token of the customer & then fetch /rest/V1/customers/me using that token.
Thanx @mbrinton01
