### ISSUE TITLE
[2.1.0] In Stock/Out of Stock state not updating when changing quantity of item

### ISSUE THREAD

**Issue by peec** [magento/magento2#5696]
When changing the quantity of a product from any number to 0, the state is automatically changed to **Out of Stock** upon saving. However, when changing an out of stock product to any number and saving, the product is still listed as **Out of Stock**.
## Steps to reproduce
1.  Access an active, out of stock product through Products > Catalog
2.  Change Quantity to any number and save
## Expected result

The product’s state is automatically changed to **In Stock**
## Actual result

The product is still listed as **Out of Stock** despite the quantity change.

One must manually remember to also set **In Stock** which is a inconvenient step and not working as one would expect because the other way the state is changed.

**Comment by Ctucker9233** [comment]
I have noticed this as well.

**Comment by antboiko** [comment]
Hi @peec , thanks for the suggestion. I've added internal ticket MAGETWO-55823 to our backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/2-1-0-In-Stock-Out-of-Stock-state-not-updating-when-changing/idi-p/45966).

**Comment by danipolo** [comment]
I'm with 2.1.2 and have the same problem.

**Comment by r-martins** [comment]
In 2.1.8 its not a problem. I think they've fixed on 2.1.0.
I compared vendor/magento/module-configurable-product/view/adminhtml/web/js/configurable-type-handler.js from 2.0.12 with 2.1.8 and realize they've made the required change there by commenting the entire _init method, and just added `this.show();` there.
[Take a look](https://github.com/magento/magento2/blob/909a2d7e8c2ac5ca55359827c22cea93fdb719df/app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/configurable-type-handler.js#L86) and apply the change properly by creating your own module to overwrite this; or update Magento.
Applying the above change re-enabled the Out of stock dropdown but will not update the field automatically (I think it shouldn't be automatically updated to in stock, only when is out of stock).

**Comment by adarshkhatri** [comment]
Also, in my 2.3.3 I have to run indexer for it to update instantly. Any idea how do I make it work without indexing?
