### ISSUE TITLE
[2.1.0] Misleading feedback when sending tracking information email

### ISSUE THREAD

**Issue by peec** [magento/magento2#5697]
When clicking the “Send Tracking Information” button when viewing the shipment info the response is “You sent the shipment”.
## Steps to reproduce
1.  Sales -> Shipments -> View (any shipment)
2.  Click Send Tracking Information
## Expected result

Notification telling the user that the email confirming the order is underway has been sent.

E.g. "An email confirming the order is underway has been sent to the customer.".
## Actual result

Notification telling the user “You sent the shipment”.

**Comment by andimov** [comment]
@peec 
Thank you for reporting! Please, specify used version.

**Comment by peec** [comment]
Version 2.1.0 GA.

**Comment by AVoskoboinikov** [comment]
Hello. Thank you, we will review your suggestion!

**Comment by magento-engcom-team** [comment]
@peec, thank you for your report.
We've created internal ticket(s) MAGETWO-81938 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @peec. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1245 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - f03e6148d14ec0839626ac5705a5aa9e6eeef6b8

The fix will be available with the upcoming patch release.
