### ISSUE TITLE
Dev-docs on installing and configuring Grunt incomplete 

### ISSUE THREAD

**Issue by kweij** [magento/magento2#5698]
Following the documentation on http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html I could not get `grunt` compilation of less-file to work. I figured out that copying `./package.json.sample` to `./package.json` and `./Gruntfile.js.sample` to `./Gruntfile.js` and _then_ following the steps resulted in actually installing `grunt`. However, I don't dare to make a pull-request for it because I'm not sure if I'm actually using the tools as intended.

Please review this documentation.

**Comment by almarchenko** [comment]
@kweij  I created the internal issue Magetwo-55613 to review the doc.
If you have more feedback about docs, you can create issues in the [magento/devdocs repo](https://github.com/magento/devdocs/issues)
Thank you for letting us know!

**Comment by almarchenko** [comment]
@kweij Thank you!
This info was initially in docs, but got lost when we published the docs for Magento v.2.1((
I added the info again, thank you!
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html

**Comment by kweij** [comment]
Thanks, this confirms I did it right :)
