### ISSUE TITLE
Additional information about cron jobs in admin

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#570]
In Magento 1 we have really great custom module - [AOE Scheduler](http://www.magentocommerce.com/magento-connect/aoe-scheduler.html). This module  is [open source](https://github.com/fbrnc/Aoe_Scheduler) and it allow see what cron job is planned, ability to start, schedule, disable some jobs from admin, etc. I think something similar should be inside magento 2 from box.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-24409

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Additional-information-about-cron-jobs-in-admin/idi-p/46235).

**Comment by DominicWatts** [comment]
Did this happen?  In my opinion this is a missing feature?
