### ISSUE TITLE
Fixes for Issue #5666 - Global Design Configuration Not Saving

### ISSUE THREAD

**Issue by vivek201** [magento/magento2#5703]
#5666

Hello,
I may have found the issue that is stopping the configuration from being saved. If you look at the if condition in [https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/AbstractTemplate.php#L672]
You will see that if the `$storeId` is 0, then false will be returned, which is the case here for global configuration. If I change the condition to `($storeId !== false)`, I can successfully save the configuration.

Please suggest.

**Comment by andimov** [comment]
@vivek201 
Thank you for reporting! Could you please provide this solution using pull request?

**Comment by andrewsladen** [comment]
You're a champion, @vivek201

**Comment by vivek201** [comment]
@andrewsladen Glad it helped someone. :)

**Comment by magento-engcom-team** [comment]
@vivek201, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by minhluan259** [comment]
@magento-engcom-team 
The issue fixed in 2.2.0, 2.1.9 but it still in magento 2.2.2
https://prnt.sc/ho0wn8

**Comment by Vikram0811** [comment]
Correct. How could I resolve this issue ?
