### ISSUE TITLE
[CE 2.1 bug] Braintree payment method - error printed in sent order email

### ISSUE THREAD

**Issue by kishanpatadia** [magento/magento2#5704]
I upgraded to Magento 2.1 CE from Magento 2.0.7 and tested order process. Order email is working in chque/money order and other payment method. But when I pay using Braintree credit card, order email is received but it has following content in email.

"We're sorry, an error has occurred while generating this email."

I tried many solution but unable to resolve it. Can you please help solving it ?

**Comment by andimov** [comment]
@kishanpatadia 
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by kishanpatadia** [comment]
Using Magento 2 and Braintree Payments. When payment is by credit card email copy of invoice fails to generate as per attached picture.
![email_invoice](https://cloud.githubusercontent.com/assets/4959946/18410065/6188d660-7775-11e6-9a05-59fdc7e7f7e7.jpg)

**Steps to reproduce:**
Navigate to store front-end
Add any product to cart
Go to checkout page
Select braintreee credit card payment method
Place order by completing other steps

**Expected result:**
Order invoice mail is generated successfully and customer receives it in email.

**Actual result:**
Invoice order email is failed to generate and customer gets that error message in email
