### ISSUE TITLE
Magento 2.0.7 is not creating certain files in pub/static and pub/media

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#5706]
I surely can't give the steps to reproduce since I work on that installation since some time now. So it is a general question about what could make magento 2 fail to do so since it creates other files in those dirs just fine. Not sure if it should stay here as a potential bug or be moved to chat. Though I do not know how to move it anyway.

Disabling my own and another extension did not change that. As well as changing the theme doesn't.

For example there is a file http://dev.domain.co.uk/pub/media/catalog/productno_selection requested but a 404 is delivered because it is not there. I guess that might be a file containing the amount of items in basket since my top right corner does not state the products amount and I can't reach the basket without going directly in there via url. The top right basket doesn't let me in, stating that no products are in basket... which is wrong.

Going to that url directly delivers an empty page.

The other files missing are javascript-files that should be created by mage2 in pub/static too, it seems. For example I mapped the right filename (.js is not needed or allowed) to the left handle

'jquery_191':           'js/jquery-1.9.1.min',
Then mage2 requests the filename http://dev.domain.co.uk/pub/static/frontend/company/celo_theme/de_DE/jquery_191.js but this file does not exist.

Going to that file directly gives some mage bugs claiming that the file does not exist.

What's wrong? Why are these files not created? I think it brings certain problems to my installation.

**Comment by abdel1220** [comment]
Hello,

try to deploy static content via command: setup:static-content:deploy

**Comment by Onkovat** [comment]
Thanks for the tip @akacemy . Though I get

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /web/vendor/oyejorge/less.php/lib/Less/Visitor/processExtends.php on line 420

for now. Restarting it let it move a bit more forward but at one point it does not go further. Need to wait until the allowed memory size was raised.

I have read a bit about that command and it seems it is creating static content. Though since I'm in developer mode, shouldn't the static files be created automatically? But still worth a try... really hope it helps since this problem already took enough time again. So many bugs in magento 2 where you have to find a fix... no fun... :/

**Comment by abdel1220** [comment]
yeah,

you are write if you are on developer mode static file should not be created.

for the PHP memory error i think you should increase the php memory limit to 768M.

try to run on production mode and generate static files using the command. 

can you provide more info about the issue: web server, step to reproduce

**Comment by Onkovat** [comment]
It's strange... the phpinfo.php shows that the memory_limit is higher now. Though the error message still claims php could not get the needed amount. The cli though has a different php.ini and in there the memory_limit is even unrestricted. I'm not sure where this limit comes from. I mean it has to do with php, right? I think it's a virtual server to allow php in the version area that mage 2 needs. Can the limit come from there somehow?

**Comment by ghost** [comment]
`phpinfo.php` shows the PHP configuration for the web server plug-in. `php --ini` shows the configuration for the PHP CLI. If they are different, use the same settings in both `php.ini` files. You should at least try to set `memory_limit` to a value other than `-1` to see if it makes any difference.

**Comment by Onkovat** [comment]
It was really an error in chosing the wrong php.ini. The deploying runs through fine now though even when running setup:upgrade before and then running the deploy with the correct language... it does not change a little bit. It still shows these errors in chrome console:

`Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
(index):366 GET http://dev.domain.co.uk/pub/media/catalog/productno_selection 404 (Not Found)
productno_selection:1 GET http://dev.domain.co.uk/pub/media/catalog/productno_selection 404 (Not Found)
jquery-migrate.js:21 JQMIGRATE: Logging is active
require.js:1895 GET http://dev.domain.co.uk/pub/static/frontend/company/celo_theme/en_GB/jquery_191.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774(anonymous function) @ require.js:1416
require.js:166 Uncaught Error: Script error for: jquery_191
http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:166onScriptError @ require.js:1681
require.js:1895 GET http://dev.domain.co.uk/pub/static/frontend/company/celo_theme/en_GB/script_code_header.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774(anonymous function) @ require.js:1416
require.js:166 Uncaught Error: Script error for: script_code_header
http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:166onScriptError @ require.js:1681`

 Are these files created by a special user that might be missing writing rights or something?

I'm not sure what to do. I think about trying to upgrade to mage 2.0.8 but I wonder if it will change the issue.

Version 2.1 would be a choice too but I'm worried that it break things I coded already. Heard such things about that version.

**Comment by Onkovat** [comment]
Maybe those missing files do not belong to the real static content like the require_js- folder in pub/static? It does not get deleted when deleting static content cache so maybe those files would not be created by deploying and the error lies in the engine that handles code files?

**Comment by veloraven** [comment]
@Onkovat 
I'm closing this issue as GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue which requires fix please create new GitHub issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
