### ISSUE TITLE
Integrity constraint violation error in Magento 2.1

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#5709]
## Steps to reproduce
1. Install Magento 2.1
2. Go to admin -> Stores -> Configuration -> Sales -> Google API section
3. Change the configuration **Enable Content Experiments** to "Yes"
4. Save a configurable product and its child product consecutively.
## Expected result
1. We can save the product successfully with any number of times.
## Actual result
1. Product is not saving properly.
2. Gives an error:

**SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-1383-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ? WHERE (code_id='50')**

**Comment by duhon** [comment]
Thanks for reporting @vipin-eglobeits

Unfortunately, I was not able to reproduce the issue you described.
Could you please provide more information? Like versions of PHP, MySQL and web server.
Also, it can be helpful if you describe settings of your Magento instance: was it a fresh install or upgrade from the previous version?
Do you have many store views? Maybe some other settings.

**Comment by moderncodes** [comment]
Having a similar problem editing product
PRODUCTS > CATALOG > [ITEM] > SAVE
message:
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-143-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: INSERT INTO`googleoptimizer_code`(`entity_id`,`entity_type`,`store_id`,`experiment_script`) VALUES (?, ?, ?, ?)`

PHP - 5.6.17
MySQL - 5.6.31
Upgraded from 2.0.2 to 2.1.0

**Comment by andimov** [comment]
@vipin-eglobeits
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
@moderncodes
Please, create new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by bhcosmetics** [comment]
@duhon 
To reproduce this issue please enable the below option:

1. Store > Configuration > Sales > Google API 
2. Enable Content Experiments field set as 'Yes".

**Comment by jvreeken** [comment]
I also had a similar error that was only able to be resolved by turning off experiments..

Error:
Something went wrong while saving the category. 

main.CRITICAL: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-350-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE

**Comment by ooples** [comment]
I'm having this issue as well

**Comment by jeo4long** [comment]
We are having this issue as well.  Magento 2.1.1.   Here's the link to the screenshot:  [https://s20.postimg.org/lboixbvh9/8_BDBB3_DD409260_F33457_B990_DC24_D8_AA9017_E3_D35_C9_A63_B.png](url)

**Comment by Gorkyman** [comment]
Same here. Migrated from M1 to M2 2.1.1, on some products, when having "Enable Content Experiments" set to "Yes", we get the "Integrity constraint violation: 1062 Duplicate entry 'x-xxx-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE" on Save. If we disable the Experiements, product saving works as expected.

**Comment by Will-I4M** [comment]
Did you created your products by duplicating another one ?
You maybe forgot to change the url key in SEO optimmisation tab..
in that case, change your url key for those products, and delete the wrongs records in googleoptimiser_code and it should be ok.

**Comment by ghost** [comment]
I faced same issue with configurable product.
To fix this issue I edit configurations options and its worked for me. please refer this link http://prntscr.com/e7px78

**Comment by DripperCoffee** [comment]
I am also getting the following error code when trying to update and save a configurable product.

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-2057-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `store_id` = ? WHERE (code_id='287')

@lalitkaushikgithub Could you please elaborate how you managed to resolve the error? I cannot get any information out of your screenshot.

Running Magento 2.1.7, PHP 7.0.21, Apache 2.4.18

**Comment by DripperCoffee** [comment]
I was able to resolve the error by repairing Magento database with the integrated database tools.

More info [here](https://magento.stackexchange.com/a/167875).

**Comment by chrisputnam9** [comment]
We've been able to reproduce this fairly regularly by doing the following:
1. Enable Google Experiments
2. Add a product to two categories
3. Remove the product from one category
4. Remove the product from the other category
5. Repeat steps 2-4 as needed until error occurs.

**Key piece of error:** 
Duplicate entry '1-161-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `entity_type` = ?, `store_id` = ? WHERE (code_id='10904')

Looking in the database, the row of googleoptimizer_code with code_id = 10904 is for the product.  So, this seems like a bug - the query is written as though it's updating the category data, but the ID is targeting the existing product.  Thus, it results in a duplicate.

**Full error sample:**
[2020-06-17 15:24:10] main.CRITICAL: Could not save product "7" with position 0 to category 161 - Unique constraint violation found {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): Could not save product \"7\" with position 0 to category 161 - Unique constraint violation found at /home/doverjew/site/vendor/magento/module-catalog/Model/CategoryLinkRepository.php:118, Magento\\Framework\\Exception\\AlreadyExistsException(code: 0): Unique constraint violation found at /home/doverjew/site/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:425, Magento\\Framework\\DB\\Adapter\\DuplicateException(code: 1062): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-161-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `entity_type` = ?, `store_id` = ? WHERE (code_id='10904') at /home/doverjew/site/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:580, Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-161-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `entity_type` = ?, `store_id` = ? WHERE (code_id='10904') at /home/doverjew/site/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-161-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE' at /home/doverjew/site/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []

**Comment by BreezeMaxWeb-NS** [comment]
I just updated from Magento 2.3.4 to 2.3.5-p1 and now I started getting this.

It happens every time I use the Edit Configuration on a simple product and try to either add images or adjust products assigned to the configurable product.

**Comment by mgarrido90** [comment]
Same error in Magento 2.3.4p-2 as @chrisputnam9 mentioned.

var/log/exception.log:[2021-05-31 22:28:56] report.CRITICAL: Could not save product "54559" with position 85 to category 5136 {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): Could not save product \"54559\" with position 85 to category 5136 at /app/33idfz6fzbmmy_stg/vendor/magento/module-catalog/Model/CategoryLinkRepository.php:90, Magento\\Framework\\Exception\\AlreadyExistsException(code: 0): Unique constraint violation found at /app/33idfz6fzbmmy_stg/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:431, Magento\\Framework\\DB\\Adapter\\DuplicateException(code: 1062): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-5136-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `entity_type` = ?, `store_id` = ? WHERE (code_id=119) at /app/33idfz6fzbmmy_stg/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:585, Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-5136-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE `googleoptimizer_code` SET `entity_id` = ?, `entity_type` = ?, `store_id` = ? WHERE (code_id=119) at /app/33idfz6fzbmmy_stg/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-5136-category' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE' at /app/33idfz6fzbmmy_stg/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

**Comment by bartoszkubicki** [comment]
Still an issue in 2.3.5 (Commerce Edition)
