### ISSUE TITLE
Magento 2.1 where is the products return and RMA management?

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5710]
I'm surprised to discover that on Magento 2.1 there is not this functionaliy. Let me say that is a basic functionality for an e-commerce platform.
Really Magento 2.1 CE doesn't have it or am I not able to find it?
Must be considered as a feature request?

**Comment by pboisvert** [comment]
Magento CE does not have this capability now which is reserved for Enterprise edition for now. There may be extensions available for portions of this functionality and of course with Magento being extensible this could be added through customization.

**Comment by stamster** [comment]
This is really basic feature. @PierAlex is correct, 100%.

We should switch to OpenCart, which has all those features by default and is much more lightweight then M2.

**Comment by orlangur** [comment]
@PierAlex @stamster are you not satisfied with 3rd party extensions or just there is no free extension available?

RMA functionality was always a part of Enterprise Edition as far as I know, so, it does not look like a feature request but a request for EE module moved to CE.

**Comment by stamster** [comment]
@orlangur The thing is, if something is normal to be expected to be present in a core of a product, such as RMA management, then that's what it is. Why would we need 3rd party solutions, the entire point of Magento is to offer e-commerce solution with all the **basic** components. We don't require something really uncommon like very specific API gateway integration for payment, local country shipping services etc.

**Comment by PierAlex** [comment]
@orlangur 
Hi Vlad,
I think you are out of scope.
RMA is part of the basic lifecycle of modern commerce. So, Magento2 pretends to be the best platform for the e-commerce, and i'm almost more than happy  to have chosen it but this is not something that has to be moved from EE to CE, this is a feature that you expect to find for sure. In fact, i was surprised to discover that it is not included. For example, if you choose a car you expects that the reverse gear is included and that you don't have to buy an option for that. We are not talking about a mini-fridge, we are talking about the reverse gear, That's it. I didn't want to light a flame, I was only surprised and I really hoped I wasn't able to find this functionality.
I found an extension for 49$ to cover this lack, I'll buy it. and I will be satisfied 

Peace and love!

Ale

**Comment by ovidiucaramida** [comment]
An easy to use and cheap solution for returns is this extension
https://webpanda-solutions.com/easy-returns.html
