### ISSUE TITLE
Invalid block type : Magento\\Braintree\\Block\\Paypal\\Button"

### ISSUE THREAD

**Issue by vjacquemin-sqli** [magento/magento2#5712]
On product page, Console Error : "message":"Invalid block type : Magento\Braintree\Block\Paypal\Button"

Case error in Magento\Braintree\Block\Paypal...
Folder name is Pay**P**al (with upper 'p')

**Comment by ErikPel** [comment]
While you wait for magento 2 devs response (I'm not one). Maybe this will help you:

https://github.com/magento/magento2/issues/553

**Comment by YevSent** [comment]
Hi @vjacquemin-sli, if you look to [Braintree Module](https://github.com/magento/magento2/tree/develop/app/code/Magento/Braintree/Block), you will see what the correct name is `Paypal`.
Try to remove Braintree module from vendor directory and run composer update again.
Also, if you use Windows it is not supported OS for Magento.
