### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by perryzak82** [magento/magento2#5713]
When adding products i get the below error ?

Attention

Something went wrong.

**Comment by pboisvert** [comment]
Can you please follow the template for reporting issues in terms of providing version information and detailed steps to reproduce the issue you are seeing? https://github.com/magento/magento2/issues/new

**Comment by perryzak82** [comment]
## Steps to reproduce
1. When adding products, and saving,
2. edit a product and save

## Expected result
1. save and then OK? 

## Actual result

![image](https://cloud.githubusercontent.com/assets/8169255/17006207/05bb2dcc-4ed7-11e6-8aa9-e1db2955e3d1.png)

**Comment by ClaudiuCreanga** [comment]
This is not enough info to replicate the error. Can you include more info about what you did previously? I am getting the same error, but inconsistently.

**Comment by ClaudiuCreanga** [comment]
For me it was related to #5418 
Gone into table cataloginventory_stock_item and delete duplicates.
It is solved in develop branch so we have to wait for next release.

**Comment by oserediuk** [comment]
Hello @perryzak82 ! Could you provide which Magento code base version do you use? What product type do you try to save?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by hyperwebmedia** [comment]
a:4:{i:0;s:94:"Initialization error component, check the spelling of the name or the correctness of the call.";i:1;s:6175:"#0 /home/truewholesale/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(139): Magento\Ui\Model\Manager->prepareData(NULL)  

This is the error Im reading in the reports. Can anyone advise?

Edit : This is painfully annoying.

**Comment by ghost** [comment]
I got the same error for a shipment module. 

It tooks me 2 days to find what the problem was. 

It was ... coding type of my registration.php was UTF-8 but all files must be UTF-8 (without BOM) and this problem was solved :) 

So the shipping module was showing up in admin even with this UTF-8 problem, but in showing the product list I got this error (no relation, no attributes) but somewhere is something going wrong .. but solved now!
