### ISSUE TITLE
vault_payment_token_order_payment_link' doesn't exist

### ISSUE THREAD

**Issue by pstoute** [magento/magento2#5714]
## Steps to reproduce
1. Install Magento from zip or composer
2. set up braintree payment method
3. add product to cart
4. checkout
5. enter credit card for payment
6. place order.
## Expected result
1. Braintree to process payment and Magento order generated
## Actual result
1. Braintree processes payment
2. Magento Error  "Could not process order. Try again later"
   2a. Debug Data:
   `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.vault_payment_token_order_payment_link' doesn't exist, query was: SELECT`vault_payment_token_order_payment_link`.* FROM`vault_payment_token_order_payment_link`WHERE (order_payment_id = 23) AND (payment_token_id =7)SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.vault_payment_token_order_payment_link' doesn't exist, query was: SELECT`vault_payment_token_order_payment_link`.* FROM`vault_payment_token_order_payment_link`WHERE (order_payment_id = 24) AND (payment_token_id =8)`
## Notes

The error message states that the table is missing, however it's not including the table prefix for this query. There should be `table.mg1_vault...` not just `table.vault...`

**Comment by pstoute** [comment]
got this "fixed" well, hacked to work for us... it seems that /vendor/magento/module-vault/Setup/InstallScheme.php doesn't utilize the install's table prefix.

Hacked lines (21-23):

```
 const PAYMENT_TOKEN_TABLE = 'mg1_vault_payment_token';

    const ORDER_PAYMENT_TO_PAYMENT_TOKEN_TABLE = 'mg1_vault_payment_token_order_payment_link';
```

**Comment by pstoute** [comment]
This doesn't resolve the issue on the admin create order area though. Just client side.

**Comment by YevSent** [comment]
Try to reinstall Magento, seems to `\Magento\Vault\Setup\InstallSchema` didn't run.

**Comment by pstoute** [comment]
@joni-jones I installed a fresh copy on our server to be sure the install went through successfully and the second install had the same errors. 

Installed the second copy from the .tar.gz and the web installer.

Is there a way to run just that section? everything else seems to function perfectly.

**Comment by YevSent** [comment]
Do you try to install 2.1 version or develop? On the installation step, did you use table prefixes? If, yes, try to install without them.

**Comment by pstoute** [comment]
2.1
I've tried the following two files. Not including the original install from before this latest update... the original install took place back on 06/23/2016 but the main install was without the sample data.

Magento-CE-2.1.0_sample_data-2016-06-23-02-32-34.tar.gz
Magento-CE-2.1.0_sample_data-2016-06-23-02-32-34.zip

**Comment by YevSent** [comment]
Created internal ticket MAGETWO-56344.

**Comment by pstoute** [comment]
Not to be pushy, but do we have an ETA on this update as of yet?

**Comment by pstoute** [comment]
More data on this bug... it seems that if you're using a cPanel server, one that requires a table prefix, the installation for this payment method will fail because it's not currently allowing the use of table prefixes.

If we install this on another server that doesn't require table prefixes, my guess is that it'll work without any modification to the core code.

**Comment by alena-marchenko** [comment]
Hi @pstoute 

Fix for MAGETWO-56344 ticket is already merged to develop branch.
Closing the issue, please feel free to reopen if the issue still reproducible for you.
