### ISSUE TITLE
Upgrade command causes Magento 2.1.0 to crawl

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#5716]
## Steps to reproduce
1. Install Magento 2.1.0
2. Run php bin/magento setup:upgrade
## Actual result
1. Causes entire site to crash to halt. CPU drops to 0% on server. Developer says server is being overwhelmed with GET requests that overloads it. 

Debian 8.5 
PHP 7.0.8
MySQL 5.6

**Comment by piotrekkaminski** [comment]
Did you disable traffic to site/put it in maintenance mode during upgrade @stevekem ?

**Comment by piotrekkaminski** [comment]
cc @choukalos

**Comment by stevekem** [comment]
This is a test site so only I am accessing it, no other traffic.  I didn't enable maintenance mode when running upgrade but now after trying it, it seems by doing so prevents the issue from happening (only tried twice though).  Thanks for the heads up.

If this isn't a bug, maybe consider it a feature request as none of the extensions we installed mentioned enabling maintenance mode first or we would have done that so not sure how many others are experiencing the same problem.

**Comment by hostep** [comment]
Magento should clearly define all steps in the documentation to deploy to a production server and when to enable maintenance mode and when to disable it.

Relates to: https://github.com/magento/devdocs/issues/419

**Comment by pboisvert** [comment]
closing issue as there is not specific issue here other than the documentation which already has an open ticket against referenced in the devdocs issue referenced above. We need to push that one along.
