### ISSUE TITLE
Magento 2.1.0 - Can't edit (save) products that have been csv imported

### ISSUE THREAD

**Issue by Stylish015** [magento/magento2#5717]
## Steps to reproduce
1. Upgraded Magento from 2.0.5 to 2.1.0
2. Imported new products from csv using the Magento Product Importer.
3. Can't edit those newly imported products... go to save them (after making changes) using the Save and Exit, and the saving wheel comes up and goes away but the page doesn't refresh or go back to the product listing page. Just stays on the product I was trying to edit.
4. BTW - there are no errors during the product import, it shows the message that all products were imported successfully.
## Expected result
1. To save the changes made to the product.
2. Works fine with all the other existing products... just won't work with the new imported ones.
## Actual result
1. No error message... the saving wheel comes up and goes away but the page doesn't refresh or go back to the product listing page.
2. Doesn't save any of the made changes to the imported products.

**Comment by antboiko** [comment]
Hi @Stylish015 , thanks for your inquiry. We've created internal ticket MAGETWO-55749 to investigate this issue.

Best,
Anton.

**Comment by Stylish015** [comment]
We have now managed to have this fixed!

It ended up being a "POST ?isAjax=true 404 Not Found" error when saving changes with a product.

With Google searching and help from the our hosting company we found that it was an issue with the mod_security settings. They changed the settings to allow the page to be saved. Now all is working fine with this.

Thanks.
