### ISSUE TITLE
Braintree payment method does not work with multiple addresses

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#5718]
## Steps to reproduce
1. Install Magento 2.0.8
2. Setup sandbox Braintree
3. Add products to cart and process to checkout with multiple addresses
4. Select at least 2 address at the Multiple Addresses step.
5. Select Braintree at Billing step and enter test creditcard
6. Press Place Order at review step
## Expected result

Payment should go through.
## Actual result

You will be redirect back to Billing step with "Order place error" message.

**Comment by phuc128t** [comment]
Braintree works fine with onepage checkout.

**Comment by phuc128t** [comment]
I checked the log and see this:

Merchant account does not support payment instrument.
Cannot provide both payment_method_token and credit_card attributes.
Cannot use a payment_method_nonce more than once.
Credit card must include number, payment_method_nonce, or venmo_sdk_payment_method_code.
Cannot use a payment_method_nonce more than once.

I missed anything?

**Comment by YevSent** [comment]
Hi, @eric128, please, enabled debug and attach debug log for transactions to this issue.
Also, Magento version <= 2.1 uses deprecated version of Braintree.

**Comment by phuc128t** [comment]
See attached. I shipped to two addresses in this case. The first one went through but the second was not.
[debug.txt](https://github.com/magento/magento2/files/377299/debug.txt)

The man from Braintree said below:
"Unfortunately, a payment method nonce can only be used once. And even if not used, it will expire after 3 hours. There is no setting to override this.
Generally if what you’re trying to accomplish to be able to store and reuse a payment method, you’ll want to use a payment method token instead as those are persistent."

Can we upgrade Braintree version for 2.0.7 or 2.0.8?

**Comment by YevSent** [comment]
> Can we upgrade Braintree version for 2.0.7 or 2.0.8?

No. Current implementation of Braintree not compatible Magento versions  <= 2.1.

But, in the case, if you will upgrade to Magento 2.1, Braintree won't be available as a payment method for Multi Address Checkout, because payment nonce can't use twice.

**Comment by alena-marchenko** [comment]
Hi @eric128 

Closing this issue due to no response, please reopen when you have an update.
