### ISSUE TITLE
Order comment history  status time is updating to current time whenever refreshing order view page,It should be the time when comment has been added or status has been changed

### ISSUE THREAD

**Issue by hina-patidar** [magento/magento2#5719]
## Steps to reproduce
1. Place order in Magento 2
2. Now go to Magento admin panel and view that order.
3.  Change the order status from drop down and submit comment.
4.  Now history will be added (E.g. - "**21 Jul, 2016 5:37:28 AM**" Processing Customer Not Notified)
## Expected result
1. This given time should be time when status has been changed or when comment has been submitted.
## Actual result
1.  Currently time is updating every time to current time when we are refreshing page.
2. So in this case history is always getting updated by current time.

**Comment by tiwarimukesh** [comment]
Same behaviour is happening in Magento 2.0.8 also

**Comment by kanduvisla** [comment]
Confirmed in 2.0.8. Adding a comment changes the dates of all comments. It's not updated in the database though, so it looks like a templating issue

**Comment by kanduvisla** [comment]
The problem seems to be in line 75-76 of `vendor/magento/module-sales/view/adminhtml/templates/order/view/history.phtml`.

This uses `$_item->getCreatedAtDate()` but this should be `$_item->getCreatedAt()`.

Changing this line fixes the issue. The same seems to be happening on line 56-57 of `vendor/magento/module-sales/view/adminhtml/templates/order/comments/view.phtml`, with the comments.

**Comment by kanduvisla** [comment]
I've created a pull request for the 2.0 branch that addresses this issue.

**Comment by kanduvisla** [comment]
On a sidenote: this problem only seems to exist on the 2.0 branch. 2.1 and develop were already fixed

**Comment by ArthurTransoftgroup** [comment]
@hina-patidar Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2?
