### ISSUE TITLE
post telephone number in cash on delivery method for otp

### ISSUE THREAD

**Issue by nanda1990** [magento/magento2#5720]
post telephone number in cash on delivery method for otp

**Comment by oserediuk** [comment]
Please, provide description according to the template.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
