### ISSUE TITLE
Rest Api rest/<store_code>/V1/products giving products from all store not from defined store_code

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#5723]
## Steps to reproduce
1. Magento 2.1.0
2. Multistore
3. rest/store_code/V1/categories - giving categories which are in defined store_code
4. rest/<store_code>/V1/products - giving all products without filtering it by store_code
5. rest/<store code which not exists>/V1/products - giving error. So store_code is checked but with changing store_code still receiving all products
## Expected result
1. Products which are turned on in defined store_code
## Actual result
1. all products from all stores

**Comment by veloraven** [comment]
@RUjmiak thank you for your report.
Please update description or add as a comments following information:
1. Please do not use angle brackets as GitHub does not show text inside them, so I see the same requests in steps 4 and 5.
2. Specify expected and actual results for both steps 4 and 5.
3. Provide an error you get on step 5.
4. Provide full requests for steps 4 and 5 as _V1/products_ requires _searchCriteria_ so I can not reproduce your issue following currently provided steps.

**Comment by RUjmiak** [comment]
@veloraven here is added information

for searchCriteria we can use just searchCriteria[pageSize]=20
1. rest/store_code_1/V1/products - giving all products without filtering it by store_code. Where store_code_1 is ID of one of active store in multistore. Result is the same products as rest/V1/products event when some products not in store_code_1
2. rest/store_code_which_not_exists/V1/products - giving error. So store_code is checked but with changing store_code still receiving all products
   {
   "message": "Request does not match any route.",
   "trace": null
   }

**Comment by RomanKrut** [comment]
@RUjmiak Hi. Thanks for reporting this issue. The internal ticket was created MAGETWO-70508

**Comment by magento-engcom-team** [comment]
@RUjmiak, thank you for your report.
We've created internal ticket(s) MAGETWO-70508 to track progress on the issue.

**Comment by RomaKis** [comment]
Based on comment https://github.com/magento/magento2/pull/6130#issuecomment-301897858 it seems to be the correct Magento behavior and you can get products by store with a help of searchCriteria. Also I found one more comment https://github.com/magento/magento2/pull/6095#issuecomment-301894105 it describeв where this functionality was implemented.

**Comment by magento-engcom-team** [comment]
@RUjmiak, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by danrcoull** [comment]
Change vendor/magento/module-catalog/Model/ProductRepository.php LINE 531  getList function to look like below.  To do the same as category


```
public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria)
    {

        $storeCode = \Magento\Framework\App\ObjectManager::getInstance()
            ->get(\Magento\Framework\App\ScopeResolverInterface::class)->getScope()->getCode() ?? 'all';
        
        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $collection */
        $collection = $this->collectionFactory->create();
        $this->extensionAttributesJoinProcessor->process($collection);

        $collection->addAttributeToSelect('*');
        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
        $collection->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner');

        $this->collectionProcessor->process($searchCriteria, $collection);
        $collection->addStoreFilter($storeCode);
        $collection->load();

        $collection->addCategoryIds();
        $searchResult = $this->searchResultsFactory->create();
        $searchResult->setSearchCriteria($searchCriteria);
        $searchResult->setItems($collection->getItems());
        $searchResult->setTotalCount($collection->getSize());

        foreach ($collection->getItems() as $product) {
            $this->cacheProduct(
                $this->getCacheKey(
                    [
                        false,
                        $product->hasData(\Magento\Catalog\Model\Product::STORE_ID) ? $product->getStoreId() : null
                    ]
                ),
                $product
            );
        }

        return $searchResult;
    }

```
