### ISSUE TITLE
Magento 2.1 There is not a standard for displaying dates and inputs does not respect the local format

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5724]
The correct locale date format is dd/mm/yyyy

Magento
![image](https://cloud.githubusercontent.com/assets/17165819/17017759/0876e19c-4f35-11e6-8ea5-83616717ea8e.png)

in Magento standard modules, the date is not always displayed in the same way. E.g. in the order grid, the purchase date is  mmm dd, yyyy. ,..
![image](https://cloud.githubusercontent.com/assets/17165819/17018567/a172e492-4f38-11e6-8ce5-53cd13453b3b.png)

but if I edit the same order that date is in dd/mmm/yyyy format.
![image](https://cloud.githubusercontent.com/assets/17165819/17018595/bb7403a8-4f38-11e6-8181-ea6badb183a1.png)

For products,  'Set Product as New From' and 'to' dates are in the format mm/dd/yyyy and the calendar picker provide the date in this format.
![image](https://cloud.githubusercontent.com/assets/17165819/17018087/6ec31d02-4f36-11e6-9d01-07466b512320.png)
For catalog price rules, in the grid, the date fields displays dd/mmm/yyyy
![image](https://cloud.githubusercontent.com/assets/17165819/17018725/67ab13fa-4f39-11e6-8754-aae1a0c8c130.png)

 but in edit, dates are in mm/dd/yyyy and the calendar picker provide this format
![image](https://cloud.githubusercontent.com/assets/17165819/17018196/f193d0d2-4f36-11e6-80b5-b2569528177e.png)

For query filters such as orders reporting, the picker provide the date in the dd/mm/yyyy but those fields doesn't need to be saved.
![image](https://cloud.githubusercontent.com/assets/17165819/17018393/d3f71a74-4f37-11e6-892c-c90153932fe5.png)

So it appears that there is not a standard, or that a standard is not respected in Maento standard modules, to display dates but there is a standard for date input: mm/dd/yyyy that not consider locales. 

Ale

**Comment by oserediuk** [comment]
Hello @PierAlex ! I cannot reproduce your issue. I have same format of all my date control which you mentioned on the Front-end and Beck-end. Please, provide more details.

**Comment by PierAlex** [comment]
Hello @oserediuk,
Can you please help me to understand which details can I provide you more? Is there any place where I can look for configuration settings?
Ale

**Comment by oserediuk** [comment]
@PierAlex , I observed all control which you mentioned here and didn't see difference of format date on the fresh installation Magento 2.1.0 I cannot reproduce you issue. If you could add some more information, it would be useful to reproduce this case. It could be some non-default setting or special commit code base.

**Comment by PierAlex** [comment]
@oserediuk 
It also happens on a fresh installation. I'm expecting to manage dates in my locale format (dd/mm/yyyy).

![image](https://cloud.githubusercontent.com/assets/17165819/17215086/070bd11c-54dc-11e6-8617-1dac65bf7361.png)

To set date input format in my locale format, I set Timezone in stores->configuration->General Tab. Is this the right place? It does not take effects for date fields. Inputs must be entered as mm/dd/yyyy.

As additional info,
Stores->Configuration->General->Country settings-> Default country = Italy.

Magento2 runs on plesk 12.5 ubuntu 14 php 7.08.
Ubuntu date format is "Fri Jul 29 06:36:14 CEST 2016"

**Comment by AVoskoboinikov** [comment]
Hi @PierAlex 

Thanks for helping us. I've managed to reproduce this issue so I created internal ticket for it #MAGETWO-58253. This ticket will be closed after fix.

Thanks again!

**Comment by janeblonde** [comment]
Also looking for the date fix, is it coming soon?

**Comment by magento-engcom-team** [comment]
@PierAlex, thank you for your report.
We've created internal ticket(s) MAGETWO-58253 to track progress on the issue.

**Comment by sergiomendonca** [comment]
Many filters still not working by locale, Like order filters date, invoice filters date, customers filters date and many other filters by date.

**Comment by afavata** [comment]
Any progress on this issue.... 
It's very urgent considering this ticket was opened in 2016.
Cart rules, catalog rules, cms rules do not work properly when conditions use dates.

**Comment by WinstonN** [comment]
@magento-engcom-team could you post an update on this issue please
As of 2.2.9 default if I set my locale in my admin account, to dd/mm/YYYY and using the date picker in the grid filters, filter by a date, the date that the picker populates in the input is right, but the filter on the collection is wrong. Filters by mm/dd/YYYY instead of dd/mm/YYYY

**Comment by asim-vax** [comment]
This is also affecting magento 2.3.2, would be nice to get an update, as filtering large order sets is required for providing swift customer support and reporting.
