### ISSUE TITLE
Totals for invoices can all be set to exclusive except discount

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#5727]
## Steps to reproduce
1. Install 2.1.0
2. Set discount to be applied to inclusive total and customer tax to be calculated after discount
3. Set invoice, order display settings to display all as exclusive of VAT
4. Place an order with a discount
5. View invoice
## Expected result
1. Subtotal + shipping - discount = grand total (excl tax) 
## Actual result
1. Subtotal + shipping - discount = slightly less than excl grand total as discount includes amount applied to inclusive subtotal

I would suggest there is a similar option to display discount incl/excl of VAT. The latter would add back the discount_tax_compensation amount so that the totals add up.

See example for why this currently is rather unintuitive:
![screenshot 2016-07-21 12 18 08](https://cloud.githubusercontent.com/assets/630320/17021152/dd332348-4f3d-11e6-8f8f-e2202514674c.png)

**Comment by maderlock** [comment]
I should note that the same issue exists in pdf. Looking at the discount values in module-sales/Block/Adminhtml/Totals.php, the correct value would be $this->getSource()->getDiscountAmount() + $this->getSource()->getDiscountTaxCompensationAmount() and similar for base. However, if I do this I end up with a 1p error in the order, though not the invoice! I thought the rounding since 1.8.1 sorted this?

e.g.
![screenshot 2016-07-21 12 46 46](https://cloud.githubusercontent.com/assets/630320/17021636/325baa04-4f41-11e6-893b-204cf4183272.png)

v.s.

![screenshot 2016-07-21 12 47 25](https://cloud.githubusercontent.com/assets/630320/17021656/520834d0-4f41-11e6-9d3f-8d292f89f6c8.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Totals-for-invoices-can-all-be-set-to-exclusive-except-discount/idi-p/45200).

**Comment by maderlock** [comment]
I still believe that this is a bug. Please reopen.
