### ISSUE TITLE
REST API Product Images not saving in Magento 2.1(latest stable version)

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#5728]
## Steps to reproduce
1. for adding the product: [POST] http://127.0.0.1/{megentohost}/index.php/rest/V1/products/{sku}/media.
## Expected result
1. Images not storing. [Expected Http code: 200]
## Actual result
1. Error Message: Cannot save product.
   HTTP Code: 400

**Comment by oserediuk** [comment]
Hello! Please, clarify expected result, looks like 'not' is extra here)

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by yuklia** [comment]
I have the same issue

{
  "message": "Cannot save product.",
  "trace": "#0 [internal function]: Magento\Catalog\Model\Product\Gallery\GalleryManagement->create('Test-Simple-99', Object(Magento\Catalog\Model\Product\Gallery\Entry))\n#1 /var/www/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)\n#2 /var/www/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()\n#3 /var/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))\n#4 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)\n#5 /var/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Webapi\\...', 'dispatch', Object(Magento\Webapi\Controller\Rest\Interceptor), Array, 'front-controlle...')\n#6 /var/www/app/code/VOID/Website/Model/ContextPlugin.php(166): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))\n#7 /var/www/vendor/magento/framework/Interception/Interceptor.php(142): VOID\Website\Model\ContextPlugin->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))\n#8 /var/www/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(39): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)\n#9 /var/www/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#10 /var/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()\n#11 /var/www/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))\n#12 {main}"
}

**Comment by srinathweb** [comment]
I have same Issue

my Images updating but I put some images It have this issue.
for example  I grab random images from web.
for example http://mobshield.com/wp-content/uploads/2016/01/Free-Shipping-Beautiful-Cooking-Kitchenware-Set-Flower-Motive.jpg  image give that issue  

{"message":"Cannot save product.","trace":"#0 [internal function]: Magento\\Catalog\\Model\\Product\\Gallery\\GalleryManagement->create('maybrayz3', Object(Magento\\Catalog\\Model\\Product\\Gallery\\Entry))\n#1 \/home\/web4\/public_html\/shop\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#2 \/home\/web\/public_html\/shop\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 \/home\/web4\/public_html\/shop\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/home\/web4\/public_html\/shop\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/home\/web\/public_html\/shop\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 \/home\/web4\/public_html\/shop\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"}"

**Comment by cherreman** [comment]
I had the same issue. After investigation, it seemed that the product did not have a price. After adding a price, saving the image worked as expected.

The error message could have been more clear in this case. "Could not save product" is not very helpful.

**Comment by craignelson** [comment]
hello

**Comment by abuvanth** [comment]
i have same issue... even that product contain price field properly

**Comment by s-oliver** [comment]
same here
