### ISSUE TITLE
new PDF templates method in Mage2

### ISSUE THREAD

**Issue by seansan** [magento/magento2#573]
Is it possible to add a new PDF generation mechanism in Magento 2 in CORE?

Maybe based on HTML -> PDF or using advanced PDF editors?

Something like: 
http://www.aromicon.de/magento-download-extensions-modules/en/aromicon-invoice-pdf-pro.html

or 

http://www.magentocommerce.com/magento-connect/html2pdf.html

Now it is almost impossible to change anything about the PDF documents without very advanced programming and changing complex files

Many thanks

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-24799

**Comment by IvanChepurnyi** [comment]
Just a good alternative to use existing HTML5 to PDF library. Saves a lot of hassle for merchants who'd like custom invoices design: 
Maybe library is not good in architecture, but proved to save so many clients from PDF class override madness: (can be included into Magento as composer dependency)
https://github.com/dompdf/dompdf

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/new-PDF-templates-method-in-Mage2/idi-p/46740).
