### ISSUE TITLE
FPT label not translatable in the totals on the cart page.

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#5731]
Add a product to the cart with a the fpt option, it will show the label and the total, but the label is not translate able.

**Comment by veloraven** [comment]
@basselalaraaj thank you for your report.
We already have internal ticket for this issue - MAGETWO-56469.
I have mentioned this one in it.
Please, provide description according to the template and specify exact version used next time.

**Comment by okorshenko** [comment]
@basselalaraaj thank you for reporting and fixing the issue!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67323
