### ISSUE TITLE
HTTP ClientInterface does not allow sending of raw body data

### ISSUE THREAD

**Issue by navarr** [magento/magento2#5733]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Begin writing code that interacts with an API that takes, for example, JSON as the body request
3. Investigate the \Magento\Framework\HTTP\ClientInterface to see how to send this body within the Magento framework
## Expected result
1. `post` method, or another method allows the sending of raw json or other raw data to the server
## Actual result
1. No such functionality exists, making it impossible to send raw data over the HTTP ClientInterface

As a potential fix, I've opened Pull Request #5407.  This enables the `post` method to send raw data as well as the previously accepted array of data.

**Comment by adragus-inviqa** [comment]
I still don't know why they haven't settled for a 3rd party (Guzzle et al). Too many, maybe?

**Comment by navarr** [comment]
@adragus-inviqa You probably wouldn't want a 3rd party as the Interface.  Using PSR-7 perhaps - but it'd take some pretty rough refactoring, I imagine.

**Comment by adragus-inviqa** [comment]
Didn't meant as an interface, but yeah, I forgot about PSR7. That's a no-go, indeed.

**Comment by stamster** [comment]
Another very basic function missing. On Magento 1.x, anyone has idea whenever this was possible? I can bet it was.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/HTTP-ClientInterface-does-not-allow-sending-of-raw-body-data/idi-p/45195).
