### ISSUE TITLE
Paypal checkout error: 10413-The totals of the cart item amounts do not match order amounts.

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#5735]
## Steps to reproduce
1. Install Magento 2.0.8 on LXC VPS with php 7 and 6 GB memory Debian 8
2. Add 97 different Configurable Products to the cart.

![rejectcart](https://cloud.githubusercontent.com/assets/16857667/17024966/d4891b32-4f27-11e6-8241-1a0b6506753a.PNG)
1. Checkout with Paypal

Expected result

Checkout should proceed
## Actual result
1. Error message appears: "The PayPal gateway rejected the request. Field format error: 10413-The totals of the cart item amounts do not match order amounts.".

![paypalreject](https://cloud.githubusercontent.com/assets/16857667/17024977/e19a1d3a-4f27-11e6-82d9-9eca85988a40.PNG)

Let me know what if any logs could help.

**Comment by YevSent** [comment]
Hi, @joebusby, please, enable debug and attach debug log to this issue.

**Comment by joebusby** [comment]
I have looked around but don't see instructions for a "debug" mode.  Only developer and production.  Can you be more specific?  How to enable debug?

**Comment by YevSent** [comment]
Each payment has `Debug` option.

**Comment by joebusby** [comment]
Okay.  Thanks.  In looking for the Debug option, I found "Transfer Cart Line Items" and disabling that made the problem go away.  When I get some time I will enable it and post the debug log.  It seems checkout is faster with out the line items transfer anyway.

**Comment by alena-marchenko** [comment]
Hi @joebusby 

Does the issue still reproducible for you?

**Comment by joebusby** [comment]
Disabling "Transfer cart items" seems to have fixed the problem, and
since our instance is live and I would have to re-enable that and put
large dummy orders in to test it,  so I have elected to just leave
"Transfer cart items" off.  If you have a system set up on the
"Sandbox", you might want to test it.   Otherwise, you could close this
thread and wait to see if someone else has the problem.  If I find the
time, I will set up a test system using the sandbox and try it out.

**Comment by alena-marchenko** [comment]
Hi @joebusby 

I was unable to reproduce this issue on 2.0 and on latest develop branch, closing the issue.
Please feel free to reopen the issue if it still occurs.

**Comment by ghost** [comment]
I got this reply from Paypal Team for this issue.

> Unfortunately, the problem you're experiencing may be caused by technical issues with the PayPal system.
>  
> I have escalated this ticket to our internal engineering team for resolution.

This is paypal default issue. And paypal technical team working on it.

**Comment by oviliz** [comment]
I have the suspect that this is rather an extension issue.

**Comment by germaike** [comment]
HI,
Any luck on fixing this issue. I have this on a 2.1.4 installation.
Turned of passing cart line items without any luck.
Other suggestions?

Kind regards

**Comment by pradeepnew** [comment]
Hi,
I have added additional fee and its working with other payment gateway but not working with Paypal express payment option. I am getting below error

> PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

Any solution?

**Comment by milch-shake** [comment]
Hi, 

i've got the same Problem here. 

My Problem was, that we had two shooping cart rules on the same priority - one with 3% discount and second with 4% discount. 
M2 will collect them to 7% and the paypal module will first take 3% and after that 4% - because of this, the total value and the collected shipping-/tax- & item-values are not the same. 

to fix this, (VERY QUICK AND DIRTY):
goto module-paypal/Model/Apiu/Nvp.php

function callSetExpressCheckout at Line 812
add before "$response = $this->call(self::SET_EXPRESS_CHECKOUT, $request);" this snipped:

$request['ITEMAMT'] = $request['AMT'] - $request['TAXAMT'] - $request['SHIPPINGAMT'];
