### ISSUE TITLE
REST API Product create very slow

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [magento/magento2#5739]
Hi! I am develop integration with ERP. But have many problem with import large product catalog to Magento (2.1 from composer metapackage.)
REST API Product create very slow - import one thousand products more 15 min.
(post request to /rest/V1/products).
Internal csv import work fast, but I can't start him remote. Also this way, there is no way to create the attributes and attribute_sets.

Solve the problem with the speed REST API, please

**Comment by choukalos** [comment]
Hi @MrSena,

What product creation api response time are you looking for?
How many products are you trying to sync at one time (assume initial sync)?
Have you used the scheduled import/export function in Enterprise edition?  If that could be defined via XML for an extension would that address your need?

Thanks,
Chuck

CC'ing @mbrinton01

**Comment by Serhiy-Nazarov** [comment]
Hi @mbrinton01 
I am use Community Edition.
Now I have a directory with more than 20,000 products
put /V1/products /{sku} for about 1 second for each item
In my case, the price update for all products takes more than 5 hours.
If I use CSV import from admin, the import time is a few seconds, but I can not initiate this process remotely.
Initial sync I can run manually. But regular update need automatic mode - csv import unsuitable in the current implementation
Thanks!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/REST-API-Product-create-very-slow/idi-p/45192).
