### ISSUE TITLE
Magento 2.1 Error queuing a newsletter. Unrecognized date format

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5740]
Magento 2.1 Locale Options:
![image](https://cloud.githubusercontent.com/assets/17165819/17028974/ad8ac250-4f69-11e6-858a-edaa460ff5b6.png)

Steps to reproduce
1. In marketing->Communications: Create a newsletter template ore use an existing one
2. From "Action" select: Queue Newsletter
3. Fill the form. The Calendar datetime picker fill the "Queue Date Start" field with the format dd/mmm/yyyy ...
![image](https://cloud.githubusercontent.com/assets/17165819/17029081/1201ebf0-4f6a-11e6-991d-74f03d22cf08.png)
4. Click on Save Newsletter

Expected Result
The newsletter is queued

Actual result
Exception:
1 exception(s):
Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (28/lug/2016 17:37:42) at position 0 (2): Unexpected character

Workaround:
Go back to the edit queue form and fill the date with the format mm/dd/yyyy hh:mm:ss. Save and the newsletter is queued.

See: #5724

**Comment by veloraven** [comment]
I'm closing this issue as duplicate for #4642.
Internal ticket MAGETWO-59954
