### ISSUE TITLE
Magento Multi-Store Sample Data CMS Block Not Working in One of the Stores

### ISSUE THREAD

**Issue by s00071609** [magento/magento2#5743]
We have 2 websites running from same installation. Installed sample data which worked fine. Products were installed but cmspages and blocks from sample store was not installed. When i manually copied a sample block code to the second store (not default), it worked but the same static block when inserted into the default store, it could not recognize the block codes/buttons etc.

The strange thing is that the sample products were installed to Default Store/Webiste, but the blocks are not working in Default store/website, however its working in next store.

Would anyone have an answer to this? I checked the if cms sample folder exists insinde magento folder, it does, and the config php file has all the sample data entries.

**Comment by Ctucker9233** [comment]
Check the scope of the static block. Is it set to global, website or store? Check the store view of the pages. Make sure the static block or page doesn't have an incorrect theme applied to it. Without more information (screenshot would be nice), this is the best I could come up with.

**Comment by veloraven** [comment]
@s00071609 GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
