### ISSUE TITLE
When tier price qty above 1000 adds a thousand separator in the Admin Panel

### ISSUE THREAD

**Issue by paales** [magento/magento2#5745]
# Steps to reproduce
1. Install Magento 2.1
2. Set the language to something european (dutch in this case)
3. Create product with a tierprice with qty `1000`.
4. Save the product
# Expected result

The tier qty field should have qty `1000`
# Actual result
1. The tier qty field has a qty `1.000`
2. Saving the product sets the qty to `1`

**Comment by antboiko** [comment]
Hi @paales , thanks for reporting this issue. We've created internal ticket MAGETWO-55847 to fix it.

Best,
Anton.

**Comment by senthilengg** [comment]
Not able to save the product, System throws duplicate error **We found a duplicate website, tier price, customer group and quantity.** with the below tier prices configured then edit and click save.
![tir_price](https://cloud.githubusercontent.com/assets/395212/17925992/d2a1fb36-6a0c-11e6-8f44-8e09a4b6c082.png)

**Comment by xmav** [comment]
Issue has been fixed

**Comment by paales** [comment]
@xmav Thanks!

**Comment by manojind** [comment]
We found a duplicate website, tier price, customer group and quantity magento 2   


SOLVED : 
https://gist.github.com/manojind/49479d60a2592acb70da5db10dd4a476 




Just edit the product -> Tier price -> remove the duplicate tier price option ( Customer group , Website and qty ) , 
Like   .
You set site1 -> QTY 10 -> Customer group retailer -> price $10  

Now next price :-> You set site1 -> QTY 10 -> Customer group general  -> price $10   

Problem : Genral and retailer group will work same so remove anyone , If you need wholesaler customer then you can add next option .
