### ISSUE TITLE
Error when saving product with image - Magento 2

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#5746]
Not able to save any products with images. Clean Magento 2.1 install.

Here is the error I'm getting

Warning: DOMXPath::query(): Invalid expression in /chroot/home/customb1/custom.breweryapparel.com/html/vendor/magento/framework/Config/Dom.php on line 273

Products with no images save fine. Any help would be greatly appreciated.

**Comment by maderlock** [comment]
I suspect that you have not completed installation, with this error. Have you run both composer install and bin/magento setup:install?

(btw, I do not think that this is a bug with Magento, so please ask for help on Stack Exchange if you need further help on this)

**Comment by oserediuk** [comment]
Hello! Could you provide more details? I cannot reproduce this issue on the fresh installed instance version 2.1

**Comment by dapdx** [comment]
I was able to fix this issue. It was caused by an incorrect line in the 
view.xml file in a custom theme.

Thank you

**Comment by oserediuk** [comment]
You are welcome!

**Comment by mengbo123456** [comment]
me too

Warning: DOMXPath::query(): Invalid expression in E:\web work\wwwroot\appweb\vendor\magento\framework\Config\Dom.php on line 273

![image](https://user-images.githubusercontent.com/29748690/27901964-8d5437a8-6266-11e7-867b-fbb1ecea05cf.png)

![image](https://user-images.githubusercontent.com/29748690/27902007-aa30f6a4-6266-11e7-84fc-d424a45fafed.png)
view.xml 
![image](https://user-images.githubusercontent.com/29748690/27902722-465c8fbe-6269-11e7-9a79-791db92d0f0f.png)
