### ISSUE TITLE
How can I add a custom attribute in REST API?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#5747]
### Question 1:

I'm trying place an order using Magento 2 API.  I have a custom attribute that I want to submit along with this.
I tried submitting the custom attribute.

```
{
  "paymentMethod": {
    "poNumber": "1234567",
    "method": "purchaseorder"
  },
  "billingAddress": {
    "firstname": "Tom",
    "lastname": "Sawyer",
    "region": {
        "region_code": "NY",
        "region": "New York",
        "region_id": 43
    },
    "region_id": 43,
    "country_id": "US",
    "street": [
        "Main St"
    ],
    "telephone": "64868564631",
    "postcode": "11011",
    "city": "New York"
  },



  "order_date": "2003-01-16 23:12:01" // my custom attribute
}
```

But it comes back with the error below:

```
Property \"OrderDate\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\PaymentInterface\
```
### Question 2:

I'm trying to add a custom field to the following:
1) `[GET] /V1/orders/{id}`
2) `[GET] /V1/orders`

How can I extend `Magento\Sales\Api\Data\OrderInterface`?

**Comment by SerhiyShkolyarenko** [comment]
@springimport to declare custom attribute to interface please look through http://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html
You can find examples at code/Magento/GiftCardAccount/etc/extension_attributes.xml and code/Magento/Quote/etc/extension_attributes.xml

For examples of payload please refer to http://devdocs.magento.com/swagger/index.html => 
salesOrderRepositoryV1 => POST /V1/orders

**Comment by springimport** [comment]
> You can find examples at code/Magento/GiftCardAccount/etc/extension_attributes.xml and code/Magento/Quote/etc/extension_attributes.xml

I have `Vendor\OrderAttributes\etc\extension_attributes.xml`

``` xml
<?xml version="1.0"?> 
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Sales\Api\Data\OrderInterface">
        <attribute code="order_date" type="string"/>
    </extension_attributes>
</config>

```

> For examples of payload please refer to http://devdocs.magento.com/swagger/index.html => 
> salesOrderRepositoryV1 => POST /V1/orders

``` json
{
    "message": "Request does not match any route.",
    "trace": null
}
```

**Comment by springimport** [comment]
> ``` json
> {
>     "message": "Request does not match any route.",
>     "trace": null
> }
> ```

I solved this problem upgraded magento to 2.1.0.

**Comment by springimport** [comment]
I still don't understand how to add attributes. In your link "orders" do not participate in EAV attributes.

I guess I need to use an interface, but how?

**Comment by SerhiyShkolyarenko** [comment]
@springimport, I created a module with etc/extension_attributes.xml file equivalent to yours and passed checkout. \Magento\Sales\Api\Data\OrderExtensionInterface was autogenerated in var/generation/Magento/Sales/Api/Data/OrderExtensionInterface.php
It has getOrderDate() and setOrderDate() methods. Don't you have the same?

**Comment by SerhiyShkolyarenko** [comment]
To generate this extension interface you may also use ./bin/magento setup:di:compile

**Comment by springimport** [comment]
@SerhiyShkolyarenko Придется объяснить так.

Этого файла в системе нет.
`\Magento\Sales\Api\Data\OrderExtensionInterface`

Этот есть, да, с нужными методами `getOrderDate()` and `setOrderDate()`.
`var/generation/Magento/Sales/Api/Data/OrderExtensionInterface.php`

Я уже понял что API требует интерфейс для понимания какие поля нужно возвращать, в данном случае он получает `\Magento\Sales\Api\Data\OrderInterface` который по определению не имеет моих методов и константы `const ORDER_DATE = 'order date';` Поэтому в ответе не будет моего атрибута.

Как [временное решение](https://github.com/magento/magento2/issues/6236) я пофиксил `@return` в паре классов на мой интерфейс, это помогло.

Так же я так и не понял как `OrderExtensionInterface` может повлиять на ситуацию.

**Comment by SerhiyShkolyarenko** [comment]
@springimport  Sorry we can use here english only as an international language.
`\Magento\Sales\Api\Data\OrderExtensionInterface` is autogenerated interface, so corresponding class is located at var/generation directory.
Full documentation is here: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html
As an example please investigate `code/Magento/GiftMessage/etc/extension_attributes.xml` and `code/Magento/GiftMessage/etc/di.xml`. In the first file `gift_message` option is added to `Magento\Sales\Api\OrderRepositoryInterface` and in the second two plugins are added to this interface for `gift_message` option processing on save and load.
