### ISSUE TITLE
How to increase the quality of product photos JPG (Magento 2.1)

### ISSUE THREAD

**Issue by zhiyicai** [magento/magento2#5748]
The JPG compression on Magento 2.1 is very strong, so that the quality of product images get really bad in Catalog and Product view. How can I change the Image compression for JPG's in Magento 2.1 ?

**Comment by neilrd** [comment]
@zhiyicai @MomotenkoNatalia  . I would be keen to know if you figured this one out. I also want to increase the quality of product images.

**Comment by jibrandlr** [comment]
same here, it has been an issue for some store owners since Magento 1. They invest enough time/money to make the images look good but Magento reduces their quality after being uploaded

**Comment by hostep** [comment]
This should help you guys out I think:
1. Make sure you have the php extension `imagick` installed on your server
2. Go in the Magento backend to Stores => Configuration => Advanced => Developer => Image Processing Settings
3. Change `PHP GD2` to `ImageMagick` and Save
4. Go to System => Cache Management
5. Click the `Flush Catalog Images Cache` button

Bonus: for Magento 1, you can install the [Perfect_Watermarks](https://github.com/magento-hackathon/Perfect_Watermarks) extension to add the Imagemagick option to your M1 shop.

**Comment by jibrandlr** [comment]
@hostep thank you, it worked for me on Magento 2. 
Someone suggested an alternative on [this page](http://magento.stackexchange.com/questions/113165/how-to-increase-the-quality-of-product-photos-jpg-magento-2) In case anyone wants to test it.

**Comment by mbrinton01** [comment]
@zhiyicai please let us know if these suggestions provide a suitable solution for you.  I'm adding the feature request label so we can log your request: "Adjust the JPG compression quality setting in the admin panel."

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/How-to-increase-the-quality-of-product-photos-JPG-Magento-2-1/idi-p/45745).
