### ISSUE TITLE
[2.1] Magento Web Setup Wizard Missing Buttons and CSS Rendering Broken

### ISSUE THREAD

**Issue by flnative** [magento/magento2#5749]
## Steps to reproduce
1. Upgrade from 2.07 to 2.1 thru Web Setup Wizard
2. Launch Web Setup Wizard
## Expected result
1. Display the Web Setup Wizard page
## Actual result
1. Missing buttons (no component update button, upgrade button or configuration button)
2. Top menu repeats itself (Firefox)
   ![fireshot capture 45 - - http___dutchhar nextmp net_setup_](https://cloud.githubusercontent.com/assets/4807042/17038540/2db01792-4f64-11e6-95e5-4ae7742da201.png)

Chrome browser is worse. No top menu shows.

UPDATE: I had host provider disable OP Cache. This fixed the issue in displaying the page correctly. So, should this 2.1 version work with this cache enabled or is that a big NO? (using Nexcess shared hosting for Magento). However, I click on Component Manager and it just spins and spins.

**Comment by shiftedreality** [comment]
Hi @flnative 

Is this issue still reproducible?
Could you please provide browser console log?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
