### ISSUE TITLE
Deployment of sample data

### ISSUE THREAD

**Issue by angelorgoc** [magento/magento2#5752]
Hi All,

I've experienced an error while deploying the sample data using the CLI command.

Below is a screenshot
![image](https://cloud.githubusercontent.com/assets/20515215/17050960/6f2821fa-5028-11e6-9088-4b123af5d4f3.png)

Thank you in advance.

**Comment by ghost** [comment]
See issue #2604

**Comment by angelorgoc** [comment]
thanks @xcomSteveJohnson

**Comment by oserediuk** [comment]
Hello @angelorgoc ! Did you resolve your issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
