### ISSUE TITLE
Split up large checkout templates to allow adding more content

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#5753]
Surprisingly, given the proliferation of files in the checkout's frontend interface, it's hard to insert new blocks. Taking the shipping step as an example, the only options are points already specified within the _single_ shipping template that outputs the shipping address form, shipping method form and the next button. Therefore while you can insert content within the shipping method block (as that's where the insert points are), there's no way of adding an extra block before shipping, between shipping and shipping method or between the methods and the buttons.

This is very limiting for anyone wanting to customise the checkout. My recommendation for improvement would be to split this current template into three - shipping address, shipping method, and buttons. Then layout can be used to insert extra content without having to override a single large template.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Split-up-large-checkout-templates-to-allow-adding-more-content/idi-p/45191).
