### ISSUE TITLE
Improve Categories Tree

### ISSUE THREAD

**Issue by addison74** [magento/magento2#5756]
Please change how Categories Tree looks. It is like Windows 10 at the beginning with Windows 7 features. Give up gradients in folders icon, just plain color. Make the icons bigger without magnifying glass. Use colors which fit in the current theme (those yellow's, blue's are not in color wheel as options). 

See image bellow how this feature is now:

![category_tree](https://cloud.githubusercontent.com/assets/8360474/17051965/09dd8af2-5004-11e6-90e3-68b0597dcbe9.jpg)

**Comment by antboiko** [comment]
Hi @ADDISON74 ,thanks for the feedback. We already have internal ticket MAGETWO-50647 in our backlog to improve Categories Tree design.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improve-Categories-Tree/idi-p/46308).
