### ISSUE TITLE
Product Reviews section in Product

### ISSUE THREAD

**Issue by addison74** [magento/magento2#5757]
1) The number of columns is pretty big. You can get rid off Visibility, Product, SKU columns

2) If you still want keeping those columns, there is an issue with special characters in Product column. ™ appears incorrect &trade

![product_review](https://cloud.githubusercontent.com/assets/8360474/17052249/5351f8ca-5005-11e6-9299-548deedcaf3c.jpg)

**Comment by antboiko** [comment]
Hi @ADDISON74 
Sorry, I didn't get the first concern. Could you please clarify and provide expected result?

Thanks,
Anton.

**Comment by addison74** [comment]
Column named Product is useless, because it is clear you're reading reviews related to that product. But it is a feature from Magento 1.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-Reviews-section-in-Product/idi-p/45188).
