### ISSUE TITLE
Single page checkout fatal error in 2.1.0

### ISSUE THREAD

**Issue by OwenRay** [magento/magento2#5761]
## Steps to reproduce
1. Install Magento from `2.1.0` branch.
2. I've got two shipping methods
3. Add products to cart
4. Go to the cart page
5. Go to the single page checkout
## Expected result
1. Page loads
## Actual result
1. Page freezes with a spinner
2. Console error: validator.js:38 Uncaught TypeError: rule.handler is not a function

---

When going to the checkout page directly, the issue does not occur.
I found out this is because of the local storage: "mage-cache-storage"
When going to checkout directly, it's null, and everything goes well.

When going to edit cart first, it's filled with the following data: (modified for privacy)
{"postcode":"12345","country_id":"AB","region":null,"region_code":null,"customer_id":"1","street":{"0":"street 1"},"telephone":"+123456789","city":"smallvile","firstname":"super","lastname":"man"},"newCustomerShippingAddress":null,"selectedShippingRate":"freeshipping_freeshipping","selectedPaymentMethod":null,"selectedBillingAddress":null,"billingAddressFormData":null,"newCustomerBillingAddress":null}

**Comment by OwenRay** [comment]
For anyone facing this issue:
I've fixed for now by overwriting validator.js in my theme, 
using the original file and adding 

```
36. if(!rule.handler)
37.      return result;
```

**Comment by AVoskoboinikov** [comment]
Hello,

Thanks for request but I didn't managed to reproduce your issue with C.E. 2.1.0. I had tried both cases and both of them worked fine. Moreover, going to checkout right after adding product to cart didn't lead to null "mage-cache-storage". 

Can you check if you still can reproduce issue and provide more detailed steps to do this? 

Will appreciate your help. Thanks!

**Comment by AVoskoboinikov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
We will close this issue as not updated more than 2 weeks if this issue still reproducible please feel free to create the new one.
