### ISSUE TITLE
Bug: Double products getting added to the cart

### ISSUE THREAD

**Issue by coolocean** [magento/magento2#5763]
1.  Using Php 5.6
2. Magento 2.1.0
### Steps to reproduce
1. Click on add to cart button for any product. 
2. The product gets added to the cart and cart icon on top of page shows 1.
3. When you click on the cart icon on top of page it shows the product which was added and another product which was not added in the cart. 
4. The second product is added by random.
### Expected result
1. Only 1 product should be added to the cart
### Actual result

1. Product which was to be added was added successfully. However another random product was added to the cart.

**Comment by coolocean** [comment]
<img width="393" alt="screen shot 2016-07-26 at 11 47 54 am" src="https://cloud.githubusercontent.com/assets/13269053/17127940/d8bee8d2-5326-11e6-9c68-f4037f6e0d33.png">

As can be seen in the screenshot. Cart shows 1 item but there are 2 items added to the cart.

**Comment by AVoskoboinikov** [comment]
Hi @coolocean 

Thanks for reporting. Are still experiencing this issue?

**Comment by coolocean** [comment]
Hi,

Have not seen this for sometime. Checked it now also. Cart seems to be working fine.

**Comment by AVoskoboinikov** [comment]
Ok, thanks, I will close it then. Fill free to reopen it or create new if you will need.
