### ISSUE TITLE
Notice: Undefined index: fieldsets when change category

### ISSUE THREAD

**Issue by debreak** [magento/magento2#5765]
When i change an existing category or ad a new one, i get this error! Can anybody help?
It's magento 2.07

Notice: Undefined index: fieldsets in /html/magento2/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandler.php on line 187

**Comment by oserediuk** [comment]
Hello! What do you change exactly?

**Comment by debreak** [comment]
Hi,
the update to magento 2.1 solved the problem! thanks
i think the problem comes from the theme which is installed! this one makes one failure after another ...

**Comment by oserediuk** [comment]
Great! I closed this issue. Feel free if you have questions
