### ISSUE TITLE
Unexpected Preprocessor Behavior  

### ISSUE THREAD

**Issue by crantron** [magento/magento2#5766]
- Branch 2.1 
- Custom theme proprossor folder structure overrode magento2-base vendor folder. 

**Preconditions**
- Centos 7.2
- PHP 7 
- Apache 2.4

**Steps to reproduce**

```
|- root
|  |- app
|    |-design
|      |- frontend
|        |- <Vendor>
|           |- <Theme>
|             |- web
|               |- css
|                  |- source
|                     |- *lib*
|
|  |- vendor
|    |- magento 
|      |- magento2-base 
|        |- lib
|           |- web 
|              |- css 
|                 |- source 
|                   |- *lib*
```

**Expected result**
Theme `<lib>`should inherit vendor `<lib>s'` files as long as they're not named the same. 

**Actual result**
Vendor `<lib>s'` files are not included in the Preprocess Fallback Process, thus random less errors.

This took me 6 HOURS to figure out. SMH.

**Comment by oserediuk** [comment]
Hello! Please, clarify steps to reproduce.

**Comment by crantron** [comment]
Just make a `lib` folder with .less files within the `css` folder of the Theme. When you do that Magento 2 Base vendor css source `lib` folder gets overridden not inherited or extended.

**Comment by crantron** [comment]
Im closing this due to the docs. 

`css/source/lib: Contains view files that override the UI library files stored in lib/web/css/source/lib.`
