### ISSUE TITLE
[2.1] Receiving new order email

### ISSUE THREAD

**Issue by asrob** [magento/magento2#5769]
### Preconditions

1. Fedora 24 Server Edition, Apache 2.4.23, PHP 5.6.23, MariaDB 10.1.14
2. Magento 2.1.0, installed via composer

or
1. CentOS 7.2.1511, Nginx 1.10.1 (latest stable from nginx.org), PHP 7.0.8, Percona 5.6 (latest stable from percona.com)
2. Magento 2.1.0, installed via web installer
### Steps to reproduce

1. Install Magento 2.1 CE
2. Create a simple product
3. Order it (e.g. flat rate shipping and cod or flat rate shipping and bank transfer)
### Expected result

1. Receive new order email as admin. (Customer receives it.)
### Actual result

1. I don't receive new order email as admin. (Customer receives it.)

I couldn't find any relevant in log files but I'm not sure I look for it in the right place.

**Comment by blizzardengle** [comment]
I have the same issue. I even went into the configuration and added my personal email as a CC and I still don't get sent an email to warn me a new order was placed.

Any update in this. I am using the Magento 2.1

**Comment by slopukhov** [comment]
@asrob thank you for your feedback.
Please, recheck it on the latest 2.1 version of Magento.
Also make sure that you enter your email in the field "Send Order Email Copy To" in the Stores - Configuration - Sales - Sales Emails. 
After that a letter for new order will be sent to the customer and to you (as added to a copy)

**Comment by vzabaznov** [comment]
Hi @asrob , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Comment by asrob** [comment]
@slopukhov,

Thanks, tested with Magento 2.1.3. If I enter my email address in the field "Send Order Email Copy To", it will work. But it's weird for me, why do I need to enter an admin or custom email address to get a copy of order?
I think it should notify admin user (or general / sales contact email address) when a new order has placed.

**Comment by terenzeyuen** [comment]
Still not working Magento 2.2
