### ISSUE TITLE
Website is not getting during product GET Api and no website field for Product POST Api

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#5773]
Steps to reproduce
For Product GET:-
1. Create a product in magento 2
2. Pull the product using REST Api
For Product POST:-
1. Try creating a product using REST Api in magento2

Expected result
For Product GET:-
1. There should be field called 'website_id' to know which website_id in linked with that particular product.
For Product POST:-
1.There should be field called 'website_id' to link that product with that particular website.

Actual result
For Product GET:-
1. website_id field missing
For Product POST:-
1.website_id field missing
![product_website2](https://cloud.githubusercontent.com/assets/16597334/17076139/7cbe93bc-50c8-11e6-91f0-8f136afe92e6.JPG)

![product_website](https://cloud.githubusercontent.com/assets/16597334/17076136/f71a5822-50c7-11e6-85a2-6e3f21cb3cec.JPG)

**Comment by veloraven** [comment]
@arijit-insync thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by arijit-de93** [comment]
Hello @veloraven 

Thanks for looking into it. I am using magento 2.1.0.

**Comment by bartlubbersen** [comment]
Hello @veloraven,

I have the exact same issue, I want to export the products to a remote system but can't get the website id a product is assigned to which I need. However if I look in the API documentation the website field is not in the productRepository request so it makes sense that it's missing. However at this moment there is no way of telling which websites a product is assigned to through the API, which seems to me like data that every connector will need.

Could you please let me know when a fix is expected? If it will take to long I will have to create a module that will add the data myself, but hopefully that won't be necessary.

**Comment by warnaa** [comment]
In the version 2.1.2 this is still not fixed. In _catalogProductRepositoryV1_ call, the field _website_id_ (or rather _website_ids_) is still missing and it is not possible to tell to which websites a product is assigned to.

@veloraven could you please provide us with any information regarding the fix?

**Comment by warnaa** [comment]
After almost 8 months, this bug is still present in 2.1.7.

**Comment by RomanKrut** [comment]
@arijit-insync Hi. Thanks for the feedback. The internal ticket MAGETWO-70891 was created to address this issue.

**Comment by Tjab** [comment]
Any more info on when MAGETWO-70891 will be worked on/fixed?

**Comment by magento-engcom-team** [comment]
@arijit-insync, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by Ctucker9233** [comment]
@magento-engcom-team and backported to 2.1 I hope?
