### ISSUE TITLE
Separate fields for allow billing countries, and allow shipping countries

### ISSUE THREAD

**Issue by mustdobetter** [magento/magento2#5775]
In mulit-store, multi-locale setups, often merchants need to limit the the shipping destinations of orders to specific countries, whilst allowing any billing country to be chosen. As Magento only supports the filtering of both shipping and billing countries from one field, this is currently not possible.

**Comment by pboisvert** [comment]
@mustdobetter want to make sure we clarify the intent of your report here. Your description implies that it is not possible to specify specific shipping countries and a different set of billing countries. That is not accurate. Shipping methods and payment methods can specify applicable countries under Stores > Configuration > Sales > Shipping methods  / Payment methods.

If instead your report is actually a feature request for the ability to specify a global value that then cascades to all shipping and payment methods that would be new.

Can you specify which is true?

**Comment by antboiko** [comment]
Hi @mustdobetter , do you have an update on this?

Thanks,
Anton.

**Comment by antboiko** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. 

Please feel free to reopen or create a new one with adding more details.

Thanks,
Anton.

**Comment by mustdobetter** [comment]
Apologies for the belated reply. To clarify, I am not talking about the limiting of shipping or payment methods via country. I am talking about the control and limitation of the shipping address country list within the checkout, separate to the billing address. Although I understand you can limit the shipping methods based on country, it is still not desirable to allow the customer to view and be able to select from a list of countries for their shipping address which are not supported. 

For example, we may wish to allow billing from all countries (fairly typical), but limit shipping to countries within the EU. In this case, there is no way to limit the shipping address country options to just EU countries, as there is only one global list to control both billing and shipping country lists.

As it currently stands, we can only limit the shipping methods to the EU countries, however this will result in the customer being able to select from any country from the shipping address country drop-down, indicating that we do in fact support delivery here. It's only when the shipping methods area in the checkout refreshes that the customer is then told there are no delivery options available. This can and does cause confusion to the customer, as we are indicating one thing with the available country list, and another when presenting the available shipping options. It's much more sensible and intuitive, to  limit the country list to only those countries the that can actually be shipped to.

Thanks,

Jamie

**Comment by mpont91** [comment]
Any update of this?

**Comment by hmib** [comment]
Hey guys,

Im also trying to figure out how to have limited countries in shipping address and all countries in billing address if customer selects to specify a different address for billing.
Is this expected in a future update or is it already there in magento 2.2.x

**Comment by franckgarnier21** [comment]
Any updated on this feature request ?

**Comment by alex5513** [comment]
Any updated on this feature request ?

**Comment by AllanBerlin** [comment]
Did anyone ever find a solution or workaround for this issue? Maybe @franckgarnier21

**Comment by mebbopakko** [comment]
Does anyone found out how to solve/bypass this problem? Personally I can't even find a 3rd party extension that does this "separation".

**Comment by thomascharbit** [comment]
On M1 this module did the job: https://www.mexbs.com/magento-blog/allow-shipping-and-billing-countries-free-magento-extension/
Maybe you can get inspired for a Magento 2 version

**Comment by sergiypop** [comment]
Hello,
Did any one found a solution for this problem. it would be very helpful.

**Comment by kknsenthil** [comment]
Finally Got the solution and it's working as expected 
https://magento.stackexchange.com/questions/283571/magneto-2-different-countries-in-billing-and-shipping-address

**Comment by Crissov** [comment]
Just for the record, for anti-discrimination reasons due to geo-blocking, it has been a legal requirement in the European Union since 3 December 2018 (see [Regulation (EU) 2018/302](http://data.europa.eu/eli/reg/2018/302/oj)) that shops need to accept _billing_ addresses from _every_ EU member country (actually even EEA, i.e. EU+IS+NO+LI, but not CH and no longer UK) if they accept _shipping_ addresses in _any_ EU member country.
