### ISSUE TITLE
Not showing catalog module and not able to add product or view imported products.

### ISSUE THREAD

**Issue by chintan1988** [magento/magento2#5776]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

![image](https://cloud.githubusercontent.com/assets/19305093/17078449/ef538796-5110-11e6-8cc4-de45f4c33765.png)

**Comment by oserediuk** [comment]
Hello! Please, update your description, it looks like not full enough. Also, please, provide your code base version

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
