### ISSUE TITLE
problem while importing product with file more than 100 lines

### ISSUE THREAD

**Issue by valibus** [magento/magento2#5780]
### Preconditions
1.  Using magento 2.1.0 and php 7.0.8
2. having a shop with 2 storeview (for example 1 FR and 1 EN)
3. having a data file with declined version of sames skus in default level, fr level and en level

for example your file will look something like this
sku|name|website
sku1|name1default|
sku1|name1FR|FR_WEBSITE
sku1|name1EN|EN_WEBSITE
sku2|name2default|
sku2|name2FR|FR_WEBSITE
sku2|name2EN|EN_WEBSITE
### Steps to reproduce

1. try to import the file 
### Expected result

1. It should create only 2 products 
### Actual result

1. Actualy if the 3 line declarating my product are around the 100th line of the product, the 3 lines will be splited and it will create 2 products with the same sku.
   If i put this product at the beginning of my files there is note a duplicate creation, if i put it in the first 100th line of the file it's ok.

I guess magento try to split the file in a group of product/entity but does not check if he split in a middle of product.

By the way, why did the sku field not be used as a uniq key to group update received from import?

best regards and thanks for you help, feedback update and bug fix ! :)

**Comment by mimarcel** [comment]
@valibus I did create a PR with a possible fix https://github.com/magento/magento2/pull/6380.
@oserediuk This seems to be a critical product import issue. It would be great to have a look at it asap.

**Comment by NadiyaS** [comment]
Hi @valibus ,
thank you for reporting this issue. It was already fixed and delivered to develop branch. 
This fix will be delivered in 2.1.3 release version.
I close this issue as resolved. 
Feel free to reopen it if you encounter with the same problem in 2.1.3.
