### ISSUE TITLE
Theme developement in magento 2.1 and fall back is not working

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#5781]
Hi, 
I am creating a new theme. My theme has no css, js files. I have just added theme.xml and registration.php files. I have set parent theme magento/blank (in theme.xml).  But my theme is not inheriting files (css,js, images) from parent theme. It was working in  previous versions of magento 2. But its not working in 2.1. Please suggest.

**Comment by mrkhoa99** [comment]
Hi @baltechies 

I think your question should post on Magento Stack Exchange: http://magento.stackexchange.com/

**Comment by baltechies** [comment]
I don't think so. Its seems the issue of magento 2.1. Is magento 2 is not stable yet? or Do you have any documentation of magento 2.1?
