### ISSUE TITLE
Paypal  redirecting to https://www.paypal.com/webapps/hermes/bridge

### ISSUE THREAD

**Issue by liquidia** [magento/magento2#5782]
### Steps to reproduce
1. Enable paypal express checkout (it might be happening with enabling it)
2. Enable In-Context Checkout Experience (it might be happening with enabling it)
3. On checkout page (step 2) try to go back to previous (chrome's top left arrow button )
### Expected result

1. No redirect to  https://www.paypal.com/webapps/hermes/bridge
### Actual result

1. Website (front-end) redirects to  https://www.paypal.com/webapps/hermes/bridge (infrequently)
   when on checkout page (step 2) try to go back to previous (chrome's top left arrow button )
   Other details:
2.  Magento 2.1
3. Php7/Nginx
4. 3rd Party theme

Installed Extensions: 
Gmail SMTP
https://github.com/magepal/magento2-gmailsmtpapp

Image Gallery 
http://landofcoder.com/magento-2-image-gallery.html/

P.S: This redirct happens randomly so may not be easy to reproduce.
Thanks

**Comment by dyushkin** [comment]
Hi @liquidia!

Sorry, but we can't reproduce this issue. Maybe you can specify some new details, or try to reproduce this issue on latest develop branch?

regards,

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
