### ISSUE TITLE
Importing products via the Magento Importer csv doesn't create path url's correctly

### ISSUE THREAD

**Issue by Stylish015** [magento/magento2#5786]
Using Magento 2.1.0

Uploaded new products using the Magento Importer:
System -> Import

All products are uploaded correctly with no errors shown.

It doesn't generate the url paths correctly, for example the url from a category (on the frontend) is:
www.website-url.com//catalog/product/view/id/2154/s/product-name/category/5/

I expect the url path to be:
www.website-url.com/main-cateory/sub-category/product-name

I've tired importing products to only one website or multiple and the urls aren't correct either way.

Is this a bug, or does anyone know how to fix/correct?

When I create products manually the url's work as expected, ie:
www.website-url.com/main-cateory/sub-category/product-name

Also, when I edit a product that has been imported; 
and un-select the "Website" it is in, and then save the product, 
and then re-select the "Website" that it's in and re-save the product. 
The url then is saved correctly and works as expected. However, I don't want to manually do this to 1000's of products.

Any help would be great, thanks!

**Comment by AlexWorking** [comment]
Helllo, @Stylish015. We could not reproduce Your issue on the develop version that for now is 2.1.7 in Your case (2.1.x). If Your are still able to reproduce it on that version, please let us know. Thank You for reporting.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
