### ISSUE TITLE
Cart item price and total mismatch issue

### ISSUE THREAD

**Issue by rcbharath** [magento/magento2#5787]
Magento2.1 cart price mismatch issue
### Preconditions

1. Magento 2.1 community edition
2. 
### Steps to reproduce

1. Add configurable product item to cart
2. Goto magento2 admin and change simple product(which is in cart) price
3. Now refresh frontend cart page. Item price updated to new price But total is not updated.
### Expected result

1. Porudtc price and total price should be same
### Actual result

1. [Screenshot, logs]
   ![magento-2 1-cart-bug](https://cloud.githubusercontent.com/assets/9864656/17092204/8dcf157c-525e-11e6-8b07-87790579438a.jpg)

**Comment by SerhiyShkolyarenko** [comment]
@rcbharath thank you for reporting! Our internal issue is MAGETWO-42655.

**Comment by magento-engcom-team** [comment]
internal issue MAGETWO-42655

**Comment by magento-engcom-team** [comment]
@rcbharath, thank you for your report.
We've created internal ticket(s) MAGETWO-42655 to track progress on the issue.

**Comment by MelissaEbizmarts** [comment]
This issue is already solved on Magento 2.2-develop branch.

**Comment by mikewhitby** [comment]
@MelissaEbizmarts what was the reason for re-opening this? Is it definitely fixed on 2.2?

**Comment by AndreyRozumny** [comment]
also can't reproduce on 2.2

**Comment by MelissaEbizmarts** [comment]
@mikewhitby I had reo-opened the issue, just in case you want to add a fix for 2.1.

**Comment by ishakhsuvarov** [comment]
@MelissaEbizmarts As long as it's fixed in `2.2` ticket may be closed. Someone may still port it to `2.1`.
Thanks!
