### ISSUE TITLE
Magento2.1 Setup Compile Error

### ISSUE THREAD

**Issue by prabhumano** [magento/magento2#5789]
### Preconditions

Magento version : 2.1.0
Server : Ubuntu 14.04.4 LTS
### Steps to reproduce

 I felt Magento2 runs dead slow so i decided to check the mode, which has been set as default while installation itself. I tried to change production mode by entering the command 
php bin/magento deploy:mode:set production
### Expected result

Mode should set as production.
### Actual result

Getting run time exception

Compilation was started.
%message% 0/7 [>---------------------------]   0% 1 sec 54.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 54.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 54.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 60.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 60.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 57 secs 198.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 57 secs 198.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 57 secs 198.0 MiB
Application code generator... 3/7 [============>---------------]  42% 57 secs 198.0 MiB
Application code generator... 4/7 [================>-----------]  57% 3 mins 218.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 3 mins 218.0 MiB

  **[RuntimeException]
  Class Magento\Framework\Pricing\Object\SaleableInterface does not exist**

**Note: Same issue exist in Enterprise 2.1.0 version also. But unfortunately i had no option to log in partner portal which was notified to magento team already.**

**Comment by shiftedreality** [comment]
Hi @prabhumano 

Did you clean var/ folder before the upgrade?
Also, do you use any 3rd-party extensions?

**Comment by prabhumano** [comment]
Hi,
I cleaned var folder and I used plain Magento. 

FYI: Magento\Framework\Pricing\Object\SaleableInterface this class didn't exist in core files.

**Comment by NadiyaS** [comment]
Hi @prabhumano ,
Magento\Framework\Pricing\**Object**\SaleableInterface really does not exist in Magento 2. So you have some cache or maybe 3rd-party extensions which can use this class with old namespase.
[Here is a location of SaleableInterface ](https://github.com/magento/magento2/blob/2.1.0/lib/internal/Magento/Framework/Pricing/SaleableInterface.php), if you install Magento from composer you can find it in vendor/magento/framework/Pricing/SaleableInterface.php

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
