### ISSUE TITLE
Issue with response of getting Shipping Method

### ISSUE THREAD

**Issue by adnan-jamil** [magento/magento2#5790]
http://www.example.com/rest/default/V1/carts/mine/estimate-shipping-methods-by-address-id

from this Webapi, i'm getting response null, if there is permission issue you can guide me. 

thanks

**Comment by veloraven** [comment]
@adnan-jamil is this issue still actual?
If it is please describe detailed steps, actual result and expected result according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
If it is not, please close it.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.
