### ISSUE TITLE
Magento dataflow profiles import isnt working

### ISSUE THREAD

**Issue by saadjawaid** [magento/magento2#5794]
Hi Im trying to import products to magento store by dataflow profile, import all products. For safe side, I exported all products from dataflow profile, and than I edited that exported sheet, so that no fields are misplaced. When I import all products from dataflow profile, it stays on 0% process and doesnt increase. Im using magento 1.8.1. 
After this, I installed magento on my localhost, and installed new fresh magento 1.8, and tried importing that same excel sheet. It worked successfully fine.

**NOTE: The website where im trying to import the sheet is the live website not localhost.**

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues with Magento 2 only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions or issues with Magento 1.
