### ISSUE TITLE
Configurable product price changes affect all elements with the class 'priceBox'

### ISSUE THREAD

**Issue by ntoombs19** [magento/magento2#5798]
### Preconditions

Magento version 2.0.6 CE
### Steps to reproduce
1. Create a configurable product with options that, when selected, can change the final price.
2. Set upsell/crossell/related products on this configurable product. The idea is to get several elements on the page that have the class 'priceBox'.
3. Navigate to that product on the frontend and review all the prices on the page.
4. Select the configurable option that will change the final price.
5. Notice how not just the product price changed but the prices of all other products on the page as well.
### Expected result

Only the price of the product being viewed should be changed.
### Actual result

All prices contained in an element with the class 'priceBox' are changed.
### Proposed solution

**File**: [app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js](https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js)
**Line**: [21](https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js#L21)
**Change To**: `priceHolderSelector: '.product-info-main .price-box',`

This should work because on line [415](https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js#L415) the updatePrice event will only be triggered on the priceBox in the product-info-details element on the page rather than every priceBox on the page.

**Comment by veloraven** [comment]
@ntoombs19 thank you for your report.
However, this issue is duplicate for #4588 and we already have internal ticket MAGETWO-53135.
I have linked it with this issue as well.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.

**Comment by Muhamann** [comment]
I have this issue at 2.3.5-p1

On PDP, when selecting a size / simple-product in configurable-select, it changes all prices on the page, including upselling and related products.

How can i fix this?
