### ISSUE TITLE
magento2 Catalog not showing in Frontend

### ISSUE THREAD

**Issue by wangyonglin** [magento/magento2#5804]
Magento2 Catalog not showing in Frontend？

**Comment by pboisvert** [comment]
@wangyonglin Please provide more details following the template for reporting issues including the version you are using, how installed, and what steps are needed to reproduce the issue.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
