### ISSUE TITLE
The possibility to use html in the translations

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#5805]
The translation module is converting special characters to HTML entities when saving the translations. By moving the converting method to a separate public function, it will be possible to create a plugin, if someone wants to use html code in the translations.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/The-possibility-to-use-html-in-the-translations/idi-p/44701).
