### ISSUE TITLE
About ByPercent.php under different currencies

### ISSUE THREAD

**Issue by tmp2000** [magento/magento2#581]
I found since magento 1.7 to 2.0 ,the logic is the same for ByPercent shopping cart rule for 
$discountData->setBaseOriginalAmount(($qty * $baseItemOriginalPrice - $item->getDiscountAmount()) * $_rulePct);
The problem exists for mutli currencies:
If quote currency is different with web currency,and there is already one shopping cart price rule applied before for the item in the shopping cart,then the $item->getDiscountAmount() would be the discount value under the quote currency,while $baseItemOriginalPrice is web currency ,so it would be wrong for this substract logic.

**Comment by vpelipenko** [comment]
Ticket: MAGETWO-25084

**Comment by mcspronko** [comment]
@tmp2000, fix will be delivered with next publication. 
Thank you for your contribution.

**Comment by vpelipenko** [comment]
This issue is fixed and available in 0.42.0-beta5.
