### ISSUE TITLE
Admin new order: 'Recently Viewed Products' has 0 price value

### ISSUE THREAD

**Issue by farior** [magento/magento2#5810]
### Preconditions

1. Magento 2.0.7 with sample data
### Steps to reproduce

1. Create customer
2. View products
3. Go to admin area > Sales > Orders > Create New Order > Choose Customer > Choose Store
4. Recently Viewed Products in sidebar has 0 price
### Expected result

1. Recently Viewed Products will display correct prices
### Actual result

1. ![5060d7b27a](https://cloud.githubusercontent.com/assets/10270387/17131424/17d74bb4-5326-11e6-8daa-a9513f912f38.jpg)

**Comment by dthampy** [comment]
Internal jira ticket MAGETWO-56054 has been created

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
Closed.

**Comment by korostii** [comment]
Hi @veloraven, are there any plans to backport the fix to 2.1.x and 2.0.x branches?
