### ISSUE TITLE
wysiwyg is destroying inline styles

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#5811]
### Preconditions

1. M2.1 CE & EE
### Steps to reproduce

1. Create CMS block or CMS page
2. Disable Editor 
3. Insert content

```
<div style="background:url({{media url="whatever.jpg"}})">
&nbsp;
</div>
```
1. Enable editor 
### Expected result

`<div style="background: url('{{media url="whatever.jpg"}}');">&nbsp;</div>`
### Actual result
1. `<div style="background: url('{{media url=;">&nbsp;</div>`
2. It can destroy look of all page in some conditions

### Note

If you use this HTML code in one row, it wont be damaged by editor validation.

**Comment by ronnybremer** [comment]
Issue still exists, verified in 2.1.1 CE using both Safari and Firefox ESR 45.3.

Extremely unpleasant during major customization tasks ... Every time you load back a safe block the url get garbled.

**Comment by miakusha** [comment]
@magexo thank you for your report.
We've created internal ticket MAGETWO-58387 to address this issue.

**Comment by piotrekkaminski** [comment]
@miakusha the referenced ticket does not relate any way to this problem

**Comment by miakusha** [comment]
@piotrekkaminski , oh sorry, correct issue number MAGETWO-58617

**Comment by SahakTadevosyan** [comment]
I tried @mmansoorebay solution, but it is not working for me. Any suggestion for this ?

**Comment by tomasinchoo** [comment]
I also tried @mmansoorebay solution, but it is not working on 2.1.1.

**Comment by gboz17** [comment]
I tried @mmansoorebay solution and it does not work on 2.1.3.

**Comment by piotrekkaminski** [comment]
@gboz17  @tomasinchoo - did you apply this https://github.com/magento/magento2ce/pull/626/files and it did not help?

**Comment by pantaoran** [comment]
@piotrekkaminski your link results in a 404 on github

**Comment by veloraven** [comment]
I'm closing this issue as it was fixed in develop branch and there are no plans to backport it to version 2.1 at the moment.
