### ISSUE TITLE
Unable to void an order due to not using the payment method instance to check canVoid.

### ISSUE THREAD

**Issue by ninex** [magento/magento2#5816]
### Preconditions

1. Magento 2.0.7
2. PHP 7
3. MySQL 5.6
### Steps to reproduce

1. Create payment method with $_canVoid = true;
2. Place order
3. Navigate to Sales order grid and open order
4. Notice void button is not present
### Expected result

1. When $_canVoid is set to true you should be able to void an order.
   <img width="1123" alt="screen shot 2016-07-26 at 13 22 10" src="https://cloud.githubusercontent.com/assets/1432503/17136185/3f81f232-5334-11e6-9dbb-ec65feb2e985.png">
### Actual result

1. Void is not an option
   <img width="782" alt="screen shot 2016-07-26 at 13 24 32" src="https://cloud.githubusercontent.com/assets/1432503/17136198/507aaaac-5334-11e6-843d-593dd58adafa.png">
### How to fix issue

In vendor/magento/module-sales/Model/Order.php canVoidPayment() is not using the methodInstance.

Current:
`return $this->_canVoidOrder() ? $this->getPayment()->canVoid() : false;`
Fixes problem:
`return $this->_canVoidOrder() ? $this->getPayment()->getMethodInstance()->canVoid() : false;`

**Comment by YevSent** [comment]
Hi @ninex, if you open [Payment::canVoid](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Payment.php#L545) method, you will see that method already checks `canVoid` for payment implementation, also it checks a status of authorization transaction.
Try to debug this code for your payment, this could be useful to find a reason why the `canVoidPayment()` return false.

**Comment by ninex** [comment]
@joni-jones thanks. It was because I created an Order transaction instead of an Auth.
