### ISSUE TITLE
Magento contact form not showing success message in front end

### ISSUE THREAD

**Issue by nmohanan** [magento/magento2#5818]
please fill the details with the contact form and submit it. it will successfully submit but the success message wont be shown in frontend.

**Comment by oserediuk** [comment]
Hello @nmohanan ! Please, provide the used version. Also format this issue according to the template: with steps to reproduce, actual result and expected result.

**Comment by nmohanan** [comment]
_ I am using Firefox browser, when i submit the magento default contact us form the success message and error message not appearing in the front end, used magento version is 2.0.7_

**Comment by xmav** [comment]
@nmohanan 
I cannot reproduce the issue.
It can be helpful if you describe settings of your Magento instance: was it the fresh install or upgrade from the previous version?
Could you please try to clear browser's cache and  reproduce the issue again?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by rfapinkesh** [comment]
Newsletter validation error msg is not working in magento 2 and not see the 
 success msg...
