### ISSUE TITLE
Documentation-Issue: How to configure Cronjob when running magento2 on multiple Frontends

### ISSUE THREAD

**Issue by ludwig-gramberg** [magento/magento2#5821]
Hi, this is more of a question, but i could not find answers on the net.

When running Magento 2 on multiple frontend nodes is it enough to have one node run the magento-cron? or do all nodes have to do that?

imho, anything in cron that affects the database only, can run on one node, but stuff that involves local files, for instance synching media to disk from the db (does cron even do that?) would have to run on all nodes i guess

so if anyone could shed some light on this or point me to the documentation that'll be great

**Comment by veloraven** [comment]
@ludwig-gramberg is this issue still actual?
If it is please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.
if it is not please close this issue.

**Comment by ludwig-gramberg** [comment]
well, it's a lack of documentation, which magento provides on its website. so this is a request to complete the documentation for this common use case.

**Comment by KrystynaKabannyk** [comment]
hello @ludwig-gramberg, thank you for this report! Your request is directed to the documentation team. Once any actions are made from their side, we will notify you.
Btw, there is the public repository where you can ask any questions about documentation https://github.com/magento/devdocs

**Comment by ghost** [comment]
@ludwig-gramberg  According to engineering, you must run cron on one node. We have no centralized job queue management at the moment.

**Comment by magento-engcom-team** [comment]
Hi @ludwig-gramberg Thank you for reporting
Please consider posting documentation related issues to https://github.com/magento/devdocs

Thank you
