### ISSUE TITLE
Cannot edit BLOCKS - Class BlockGridDataProvider does not exist

### ISSUE THREAD

**Issue by skhell** [magento/magento2#5822]
### Preconditions

1. PHP 7.0.6
2. MySQL CE 5.6.30
3. Magento 2.1.0
### Steps to reproduce

1. Login to the backend
2. Click on Content --> Blocks from sidebar
### Expected result

1. Open the block page
### Actual result

![screen shot 2016-07-26 at 23 17 45](https://cloud.githubusercontent.com/assets/20488700/17155874/3d4ad6d4-5387-11e6-9ced-de90994918a3.png)
### Things I have tried to solve the issue but none have work

1. Removing all blocks from Database cms_block and cms_block_store tables
2. From /var folder rm -rf cache/\* di/\* generation/\* page_cache/*
3. php bin/magento setup:upgrade

**Comment by skhell** [comment]
Was a problem related with the template

**Comment by robkor** [comment]
I got the exact same issue in my 2.1 store (the result is identical).
I contacted de vendor of my template, but I don't have a solution yet.
Can you share the solution you got or can you tell what template caused the issue?
