### ISSUE TITLE
magento2.1/Can't find the “add to cart“ button in English storeview

### ISSUE THREAD

**Issue by coyhom** [magento/magento2#5824]
Hi ,everyone! I can' t find the "add to cart" button in English storeview after I upgrade system from magento2.0 to magento2.1 , but it's normal in other storeview like Chinese . I don'n know why......I didn‘t change any system code. When I use the system theme---blank theme, the problem same!
It is the setting problem in adminPanel? Please tell me what should I do. Thanks 
### Preconditions

1.  Version: php5.6.8 ; appache2.5, magento code:Magento-CE2.1.0-Without samples(72M)

**Comment by oserediuk** [comment]
Hello! Could your provide which Magento version you upgrade?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by coyhom** [comment]
my version is magento2.0，I want to upgrade magento2.1
