### ISSUE TITLE
Cannot change cms block values

### ISSUE THREAD

**Issue by kilis** [magento/magento2#5826]
### Preconditions

1. Magento 2.1
2. PHP 7
3. MYSQL 5.7.13
### Steps to reproduce

1. Load cms block by title
2. Set new store id
3. Save it

`foreach ($cmsBlocks as $cmsBlockItems) {`
 `$block = clone $this->_blockResource;`
 `$block->load($cmsBlockItems, 'title')`
 `->setStoreId([$storeId])`
 `->save();`
 `}`
### Expected result

1. Change block store id
### Actual result

1. [Mysql error](http://imgur.com/a/75OBa)

**Comment by magento-engcom-team** [comment]
@kilis, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0, 2.1.12
