### ISSUE TITLE
Problem in Product Add Edit using REST API

### ISSUE THREAD

**Issue by radhagobinda** [magento/magento2#5827]
I cannot add or edit product using REST Api . Its always through message "<b>Consumer is not authorized to access %resources</b>". I have checked several times but i con't. Access token is fine.
### Share my code

$adminUrl="http://192.168.1.23/magento2/index.php/rest/V1/integration/admin/token";
    $ch = curl_init();  
        $data = array("username" => "super_admin", "password" =>"admin123");
    $data_string = json_encode($data);  
    $ch = curl_init($adminUrl); 
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");  
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);  
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);  
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(  
        'Content-Type: application/json',  
        'Content-Length: ' . strlen($data_string))  
    );  
    $token = curl_exec($ch);
    $token=  json_decode($token);

$headers = array("Authorization: Bearer $token"); 

```
$requestUrl='http://192.168.1.23/magento2/index.php/rest/V1/products';

$ch = curl_init($requestUrl); 
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);   
curl_setopt($ch, CURLOPT_POST, true);
```

   $post ='{
  "product": {
    "sku": "MY_SKU",
    "name": "My Product",
    "attributeSetId": "4",
    "price": 20,
    "status": 1,
    "visibility": 4,
    "typeId": "virtual",
    "weight": 0,
    "extensionAttributes": {
      "stockItem": {
        "stockId": 1,
        "qty": 20,
        "isInStock": true,
        "isQtyDecimal": false,
        "useConfigMinQty": true,
        "minQty": 0,
        "useConfigMinSaleQty": 0,
        "minSaleQty": 0,
        "useConfigMaxSaleQty": true,
        "maxSaleQty": 0,
        "useConfigBackorders": false,
        "backorders": 0,
        "useConfigNotifyStockQty": true,
        "notifyStockQty": 20,
        "useConfigQtyIncrements": false,
        "qtyIncrements": 0,
        "useConfigEnableQtyInc": false,
        "enableQtyIncrements": false,
        "useConfigManageStock": true,
        "manageStock": true,
        "lowStockDate": "string",
        "isDecimalDivided": true,
        "stockStatusChangedAuto": 0,
        "extensionAttributes": {}
      }
    },
    "options": [],
    "tierPrices": [],
    "customAttributes": [
    ]
  },
  "saveOptions": true
}';

```
$options = array(
    //CURLOPT_URL=>$requestUrl,
    CURLOPT_HTTPHEADER=>array(                                                                          
    'Content-Type: application/json',                                                                                
    'Content-Length: ' . strlen($post)),
    CURLOPT_VERBOSE=>0,
    CURLOPT_RETURNTRANSFER=>true,
    CURLOPT_USERAGENT=>"Mozilla/4.0 (compatible;)",
    CURLOPT_POST=>true,
    CURLOPT_POSTFIELDS=>$post,

);
curl_setopt_array($ch, $options);
$result = curl_exec($ch);
$result=  json_decode($result);
return $result;
```
### Actual result

**It's returned**
stdClass Object
(
    [message] => Consumer is not authorized to access %resources
    [parameters] => stdClass Object
        (
            [resources] => Magento_Catalog::products
        )

) 

Please anyone tell me what wrong with my code. And user role is **administrator**.

**Comment by CodeGlitcher** [comment]
try adding the following header:
Content-Type: application/json

I have not problems with creating or updating products. (Magento 2.1.0)

**Comment by radhagobinda** [comment]
I have already put it in options array.

$options = array(
    //CURLOPT_URL=>$requestUrl,
    CURLOPT_HTTPHEADER=>array(  
    'Content-Type: application/json',  
    'Content-Length: ' . strlen($post)),
    CURLOPT_VERBOSE=>0,
    CURLOPT_RETURNTRANSFER=>true,
    CURLOPT_USERAGENT=>"Mozilla/4.0 (compatible;)",
    CURLOPT_POST=>true,
    CURLOPT_POSTFIELDS=>$post,

);

This is not working.

**Comment by CodeGlitcher** [comment]
I did not see that but then I  think you are setting the headers twice. Overriding the first.
try it like this
`CURLOPT_HTTPHEADER=>array(
'Content-Type: application/json',
Authorization: Bearer $token
'Content-Length: ' . strlen($post))`

**Comment by radhagobinda** [comment]
Thank you @robg66  now it's working. I have removed the **CURLOPT_HTTPHEADER** from $options array. Thank you so much.
