### ISSUE TITLE
Asymetric Transaction Rollback exception

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#5829]
Hello,  I use Magento 2.1.
Steps to reproduce:
1.I have custom data migration module, as I have to transfer all staff from non-magento staff. The point in which Exception occurs is loop, where I am addding, using `ProductFactory` products to new store, using parsed data. After some amount of time, always on the same product, exception occurs:

`Exception: Asymmetric transaction rollback. in /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:272
Stack trace:
#0 /var/www/magento/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(99): Magento\Framework\DB\Adapter\Pdo\Mysql->rollBack()
#1 /var/www/magento/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(791): Magento\Framework\Model\ResourceModel\AbstractResource->rollBack()
#2 /var/www/magento/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(57): Magento\Catalog\Model\ResourceModel\Product\Interceptor->rollBack()
#3 /var/www/magento/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(24): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#4 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#5 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'clean_cache')
#6 /var/www/magento/vendor/magento/framework/App/Cache/FlushCacheByTags.php(60): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#7 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#8 /var/www/magento/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#9 /var/www/magento/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#10 /var/www/magento/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2351): Magento\Framework\Model\AbstractModel->save()
#11 /var/www/magento/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(110): Magento\Catalog\Model\Product\Interceptor->save()
#12 /var/www/magento/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#13 /var/www/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute()
#14 /var/www/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent('dispatch', Array)
#17 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Array, 'adminAuthentica...')
#18 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Array, 'adminMassaction...')
#21 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/magento/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /var/www/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#28 /var/www/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /var/www/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#33 /var/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))`

Errors don't occurs on every instance of Magento installed, what is more it doesn't really tells us why this exception occcurs and what is really wrong.
1. What is more, sometimes, if later I edit product I get the same error, like this:

![4qh3k](https://cloud.githubusercontent.com/assets/20238194/17169464/d689f4e6-53e7-11e6-83f5-51160441f2b8.png)

**Comment by oserediuk** [comment]
Hello! Please, provide more details: your code version, more clear steps to reproduce. Also, your can use our template to report issue. https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by bartoszkubicki** [comment]
Hello, I have updated my answer.

**Comment by oserediuk** [comment]
Hello @bartek9007 ! Could you provide which data exactly I tried to migrate? If you try to migrate customer or product data, you can use Magento import functionality. If you migrate some specific data that cannot be migrated by Magento native functionality, please, ask question here http://magento.stackexchange.com/

**Comment by bartoszkubicki** [comment]
I am migrating data from non magento database - so I am not sure If I can use it.

I have noticed that it happens only with products and it's most common for example when I change branch in my project, but db of course remains the same. Maybe that's the clue?

Also, sometimes I have to do some operations on db during development, manually because sometimes it's much faster - maybe this is cause?

**Comment by bartoszkubicki** [comment]
And also these appears often after the exception:
`Customer Grid index has been rebuilt successfully in 00:00:00
Design Config Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '132-1115-1-1109' for key 'PRIMARY', query was: INSERT INTO`catalog_product_index_eav_idx`(`entity_id`,`attribute_id`,`store_id`,`value`) VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?)
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
`

But I am not sure if these things are connected. This integrity constrain violation dissapeard after a few reindextions.

**Comment by oserediuk** [comment]
@bartek9007 , if you use Magento functionality itself, please, clarify you steps to reproduce and reopen this ticket. If you change code or database directly or use some specified third-party tool, please, ask question here http://magento.stackexchange.com/

**Comment by piuga** [comment]
Same happens in my case for Magento version 2.1.5
I have a script that will update products: 
// \Magento\Catalog\Api\ProductRepositoryInterface
$productModel = $this->_productRepository->getById($productData['id'], true, 0);
// here data is prepared
$productModel->addData($productData);
$this->storeManager->setCurrentStore('admin');              
$productModel->save($productModel);

and I get same error:
Exception: Asymmetric transaction rollback. in .../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:27

It seems pretty random, because sometimes for the same product it works and brakes for others (this after I put back the old DB).

Example of data for one product:
array (
  'id' => 5028,
  'materiaal' => 1321,
  'afmeting' => 4343,
  'description' => NULL,
  'short_description' => NULL,
  'sku' => 'Kartell Comback stoel-Blauw 5950/20',
  'weight' => 1000,
  'herroepingsrecht' => 2833,
  'outdoor' => 2824,
  'meta_title' => 'Kartell Comback Chair stoel met slede | Gratis verzending',
  'meta_description' => 'Kartell Comback Chair stoel met slede is een kunststof stoel met hoge rugleuning. Luxe comfortabele stoel ontworpen door Patricia Urquiola. De stoel is verkrijgbaar in meerdere kleuren.',
  'stoelen_filter_opties' => 
  array (
    0 => 4110,
  ),
  'cjm_stockmessage' => 4317,
  'onderstel' => 2626,
  'zitdiepte' => NULL,
  'zithoogte' => '48,5 cm ',
  'draaibaar' => 2826,
  'quickshipment' => 2829,
  'armleuningen' => 2830,
  'stoelen_stapelbaar' => 2863,
  'stoelen_koppelbaar' => 2866,
  'hoogteinstelling' => 2855,
  'stoelen_materiaal_onderstel' => 
  array (
    0 => 2871,
  ),
  'stoelen_zitting' => 
  array (
    0 => 2882,
  ),
)
