### ISSUE TITLE
Product import skip on error entries not working

### ISSUE THREAD

**Issue by skhell** [magento/magento2#5831]
### Preconditions

1. PHP 7.0.6
2. MySQL CE 5.6.30
3. Magento 2.1.0
### Steps to reproduce

1. Login to the backend
2. Click on sidebar System --> Import
3. Select as entity type Products
4. Select as a Import Behavior Add or Update or Delete
5. Select skip error entries
### Expected result

1. Magento should ignore errors and execute the import
### Actual result

![screen shot 2016-07-27 at 11 38 09](https://cloud.githubusercontent.com/assets/20488700/17170939/b0714cd0-53ee-11e6-83a8-8f26d79e62a7.png)

**Comment by dthampy** [comment]
Internal ticket created-MAGETWO-56263

**Comment by WaterSlide** [comment]
Confirmed that this is still a problem in version 2.1.3

**Comment by MattDelac** [comment]
Yes this is still an issue in version 2.1.2 and 2.1.3
It would be nice to fix it expecially when you import a lot of product in one file ...

Thank you

**Comment by iagdesign** [comment]
Still a problem with version 2.1.4

**Comment by ioliinyk** [comment]
Closed as duplicate to #5334
Int ticket is MAGETWO-62947
