### ISSUE TITLE
Cannot copy "web/template" files to local theme -> no result

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5832]
On the checkout theres a out put for the responsive version of the checkout.

File:  `vendor/magento/module-checkout/view/frontend/web/template/estimation.html`

If I copy this file to `app/design/frontend/Vendor/Name/Magento_Checkout/web/template/estimation.html` changes have no effect on the output. Deleting the cache or whatsoever does not proc a change as well.

Since those files are in the view/frontend-Folder in the corresponding vendor-module-Folder they should be replaceable by the theme. Any workaround for this, or am I forced to edit core files here? 

Problem is existent in Mage 2.0.6.

**Comment by oserediuk** [comment]
Do you try to create custom theme? If yes, look to this guide http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html

Did you use this guide during your changes?

**Comment by grasdaggel** [comment]
Yes, we are using our custom theme, as you might see from the folder names. Magento_Checkout has to be used if you want to modify parents phtml files. Registered parent for our theme is Luma.

**Comment by oserediuk** [comment]
Did you create you custom theme according to guide from previous comment?

**Comment by grasdaggel** [comment]
Yes. By the way, are there any other possibilities to use a custom theme? As far as I know all steps are absolutely mandatory in order to use a custom theme... :P

**Comment by oserediuk** [comment]
Yes, you are rignt

**Comment by grasdaggel** [comment]
Thanks for taking care of that! Would be great if you could sort that out. Bug is reproduceable by simply copying the desired .html templates into the corresponding Theme-folders.

**Comment by tkacheva** [comment]
@grasdaggel  are you still have issue with overriding estimation.html

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by OZZlE** [comment]
Still an issue in 2.1.12, I tried to copy `minicart/content.html` from the parent theme to my own theme using the same folder structure. A note to add is that the parent theme already has a mixin for the minicart.js .

A workaround that I found though is this:

Copy the html template to: `[theme_path]/Magento_Theme/web/template/minicart/content.html`

and in requirejs-config.js =>

```
var config = {
    "map": {
        "*": {
            'Magento_Checkout/template/minicart/content.html': 'Magento_Theme/template/minicart/content.html'
        }
    }
};
```

**Comment by ghost** [comment]
@grasdaggel, @OZZlE, we were not able to reproduce this issue by following the provided steps. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
![1](https://user-images.githubusercontent.com/40756187/44271997-455d0500-a244-11e8-9487-76bd29f7e2cb.gif)

**Comment by OZZlE** [comment]
2.1.12

**Comment by ghost** [comment]
@OZZlE, same behavior on Magento ver. 2.1.14. Please update steps to reproduce.

**Comment by OZZlE** [comment]
I experienced the issue in 2.1.12, using a custom parent theme that also overrides this template + other things in checkout, perhaps you can reproduce the issue by overriding everything checkout frontend related knockout js files and templates.. but I guess that would take considerable time. (I mean there is probably a certain case it happens in but this might be the only way without more info)

I reported this so long ago I don't remember the exact scenario, but lets just close it until someone can report the exact steps / scenario it happens in.
