### ISSUE TITLE
Cannot place order due to duplicate key in database 

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5833]
We are currently experiencing a weird bug where we do get a error msg from Magento that a specific Key would already exists. We are using different shipping methods (Table Rates, Free of Charge and basic shipping for domestics). 

![bildschirmfoto 2016-07-27 um 13 21 21](https://cloud.githubusercontent.com/assets/13021579/17173786/20d367e8-53fd-11e6-8974-1f7338c10523.png)

We are currently using Magento 2.0.6. Any ideas what could cause this? Not sure whether its a bug with the payments or with the shipping settings, however, a setting that creates such a error message should not be configurable in the backend for more stability.

When getting this error theres a 500 Server Error from this DIR: 
`jquery.js:9666 POST http://domain.tld/mage2/rest/default/V1/carts/mine/payment-information 500 (Internal Server Error)`

Response/Content of POST:

```
send    @   jquery.js:9666
ajax    @   jquery.js:9211
post    @   storage.js:39
(anonymous function)    @   place-order.js:46
_super  @   wrapper.js:73
(anonymous function)    @   place-order-mixin.js:30
(anonymous function)    @   wrapper.js:78
validateSuccess @   saferpaycw_visa-method.js:81
proxy   @   jquery.js:556
(anonymous function)    @   checkout.js:175
proxy   @   jquery.js:556
cwValidateFieldssaferpaycw_visa @   VM33117:66
Form.Validation.validate    @   checkout.js:113
Form.validate   @   checkout.js:167
validate    @   saferpaycw_visa-method.js:72
placeOrder  @   default.js:127
(anonymous function)    @   knockout.js:3863
dispatch    @   jquery.js:4624
elemData.handle
```

We are using Magento 2.0.6

**Comment by oserediuk** [comment]
Hello @grasdaggel ! Could you provide more details: with steps to reproduce, actual result and expected result.

**Comment by grasdaggel** [comment]
Well, I try to place an order. I get this error message instead of the actual redirect to the payment page. 

We configured the shipping settings. 2 Shipping settings are for germany, table rates are for EU countries (if you want the table rate file, just tell me).
1. put something in cart
2. register or login in checkout (or proceed as guest)
3. select payment method from third party payment vendor (tested before, has worked before)
4. try to place order
5. get error message

Hope that helps. You need a more detailed information from the Shipping section?

**Comment by oserediuk** [comment]
It is enough to try to reproduce! Thanks!

**Comment by grasdaggel** [comment]
Disabling Table Rates does not solve this problem, maybe the shipping module isn't a problem here. Third Party Module does not trigger this error, since Magento built in payment functions getting the same error (Money Order/Check).

**Comment by grasdaggel** [comment]
Error is not reproduceable if you are _not a logged in cusotmer_

**Comment by mktudock** [comment]
We can reproduce this issue in Magento 2.1. I can also confirm that this happens for built in payment methods.

**Comment by TKlement** [comment]
Same problem with Magento 2.1. No matter if you are in developer or production mode.

**Comment by mktudock** [comment]
An update:
We had the issue because a module used a deprecated PHP functionality which threw an exception AFTER the order was placed but still displayed the "Unable to place order message".

When trying to place the order again the issue described in this ticket happens - Magento tries to create another order with the same ID.
At least that's what we think happened after debugging both exceptions.

**Comment by magento-engcom-team** [comment]
@grasdaggel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@grasdaggel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
