### ISSUE TITLE
Magento 2 Configurable Products Improvements

### ISSUE THREAD

**Issue by Arkyden** [magento/magento2#5834]
I want to first congratulate the developers on the new variations within configurable products.

However there are 2 huge improvements that could be made.

Firstly, you cannot edit quantities on the parent product on existing variations and it would be nice to see a customise columns on this grid. Whilst on the subject, it would be nice if we customise SKU formatting (I have all Sku's in capital letters) - apart from this it's perfect.

Secondly, when you add another variation.. for example the manufacturers release a new colour of the product and when you add it to existing variations, the images are lost even if you select "skip".

**Comment by antboiko** [comment]
Hi @Arkyden , thanks for your feedback.

For the first item, you can edit quantities from inside the Wizzard by clicking Edit Configurations.

For the second item, I was able to reproduce this issue. I've created internal ticket MAGETWO-56029 to fix it.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@Arkyden, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
