### ISSUE TITLE
Backoffice freeze on large number of customer groups

### ISSUE THREAD

**Issue by Cornoud** [magento/magento2#5837]
Backoffice freeze on large number of customer groups
this happend when editing products and within the customer grid.
### Preconditions

Magento 2.1, CE, PHP 7, MYSQL 5.6, Firefox latest version on Ubuntu 16.04
### Steps to reproduce
1.  Create 2400 customer groups
2.  Goto the backoffice customer grid, the browser shows a javascript error as processing the javascript takes too long. 
3. Goto the backoffice, catalog-product, edit a product, add some tierprices for the product
   4 Save the product
   5 try to edit the product again
### Expected result

1. Backoffice should work fine with a lot of customergroups without having problems editing/showing customers and products
### Actual result

1.![2016-07-27_1515](https://cloud.githubusercontent.com/assets/12034941/17176460/21eb4b5e-540d-11e6-94ef-ed03d4a1de90.png)

**Comment by southerncomputer** [comment]
In general that spinner AJAX junk doesn't work well for large # of anything (products w/lots of attributes) , it is slow for customers (when you don't even have that many).

Any ideas why the spinner takes so long to work (2.1.0 in production mode with bundling/minifying deployed)?

**Comment by choukalos** [comment]
Hi @Cornoud,

How many products do you have loaded in the system?  
Why do you have so many customer groups - are you using each group as a price book for one or more customers (B2B business)?

This looks like a bug - tracking internally as MAGETWO-58352

**Comment by magento-engcom-team** [comment]
@Cornoud, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
