### ISSUE TITLE
Text strings difficult to translate properly

### ISSUE THREAD

**Issue by mcjwsk** [magento/magento2#5838]
There is a bunch of text strings difficult to translate.
### 1. records found

**Problem**: The text string doesn't contain the value, so it's very difficult to translate it correctly in some languages.
**Solution**: It should be changed to `%1 records found` in this case (include the value).
**Location**: All admin grids
![2016-07-27_1436](https://cloud.githubusercontent.com/assets/284649/17175527/63101178-5408-11e6-87ed-59cb1cf7bd36.png)
### 2. selected

**Problem**: The text string doesn't contain the value, so it's very difficult to translate it correctly in some languages.
**Solution**: It should be changed to `%1 selected` in this case (include the value).
**Location**: All admin grids after a row selection
![2016-07-27_1440](https://cloud.githubusercontent.com/assets/284649/17175528/63112bee-5408-11e6-9f88-42e9b379d291.png)
### 3. Items in Cart

**Problem**: The text string doesn't contain the value, so it's very difficult to translate it correctly in some languages.
**Solution**: It should be changed to `%1 Items in Cart` in this case (include the value).
**Location**: Checkout
![2016-07-27_1510](https://cloud.githubusercontent.com/assets/284649/17176346/8bfceaee-540c-11e6-8f00-f8b472f10063.png)
### 4. Item

**Problem**: The text string doesn't contain the value, so it's very difficult to translate it correctly in some languages.
**Solution**: It should be changed to `%1 Item` in this case (include the value).
**Location**: Customer Panel -> My Orders and probably another grids at front-end 
![2016-07-27_1516](https://cloud.githubusercontent.com/assets/284649/17176484/39ad7046-540d-11e6-9a3d-98167a6acc46.png)

I think there is more similar issues, but I can't find right now. Please keep it open.

**Comment by hostep** [comment]
I also ran into problem nr 3. a couple of weeks ago.
After a bit of researching, this looked to me like a limitation of the knockout.js system.
I didn't spend a lot of time trying to fix it (maybe an hour) and haven't found a solution.
I'm curious to see if Magento or somebody else can come up with some kind of solution to this.

**Comment by jibrandlr** [comment]
Regarding number 3, I was able to translate that phrase using the following entries in the CSV file:

"%1 items in cart" (when 2 or more items are added to cart)
"Item in Cart" (when there is only 1 item in cart)

(Magento 2.1.0)

**Comment by magento-engcom-team** [comment]
@DariuszMaciejewski, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
