### ISSUE TITLE
list function in prepareColumnsLIst in PHP 7

### ISSUE THREAD

**Issue by chris-huffman** [magento/magento2#5842]
### Preconditions

1. Magento 2.0.7
2. PHP 7
### Steps to reproduce

1. call prepareColumnsList() in Magento\Framework\DB\Helper line 199.

`list($correlationName, $column, $alias) = $columnEntry;`
### Expected result

1. In PHP 7, calling list() starts with the left-most parameter (as stated in the [php manual](http://php.net/manual/en/function.list.php))
### Actual result

1. The method still works, but the values for $correlationName and $alias are reversed and this could result in unexpected errors or confusion.

**Comment by magento-engcom-team** [comment]
@chris-huffman, thank you for your report.
We've created internal ticket(s) MAGETWO-82398 to track progress on the issue.

**Comment by MikeParkin** [comment]
Having a look at this as part of the distributed-cd day, I think there is maybe some confusion regarding the change for the list construct in PHP7.

It is not the order of the values from the array that is changed, just the order of the variable creation. 

For example, this script always gives the same result on PHP 5 or 7

```php
<?php
list($a, $b, $c) = array('a','b','c');

var_dump($a);
var_dump($b);
var_dump($c);
```

```
php test.php 
string(1) "a"
string(1) "b"
string(1) "c"
```

The change in PHP7 is the *order* that the variables $a, $b and $c get defined. 

This only causes an issue if you are assigning into an array, for example:

```php
<?php 

list($a[], $a[], $a[]) = array(1,2,3);
```

In this case the order of assignment is important as they all push into the same variable.

With this in mind I do not think there is any issue within Magento\Framework\DB\Helper.

There is more information available here: http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.list.order
