### ISSUE TITLE
Product import doesn't import all products, but still gives success message

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#5846]
### Preconditions

1. Magento default product importer
2. Simple products in a Magento-format CSV
### Steps to reproduce

1. Run Check Data on product CSV.  Check Data returns valid
2. Import products. Magento shows success
### Expected result

1. Products are imported
### Actual result

1. Not all products are imported

When `Check Data` is run, it parses and batches product data into groups of 100 records, and stores them in the `importexport_importdata` table using https://github.com/magento/magento2/blob/develop/app/code/Magento/ImportExport/Model/ResourceModel/Import/Data.php#L159.

However, there is no check to see that `$this->jsonHelper->jsonEncode($data)` returns valid data. When it returns null, this is entered into `importexport_importdata`. At https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L868, this null data is returned, which causes the `while()` to end.

Magento thinks the product import was a success as it reached the end of the data to import, when in fact it hit a null value, and there was additional data to import after. This is how this bug was discovered, as it was failing in random batches of 100. The first four data bunches appeared as JSON in `importexport_importdata`, but five and six were null; there was valid JSON in bunches seven and eight but these were never hit.

This is particularly dangerous as a merchant could update product prices, get a message they went in, and they haven't gone in.

Ultimately the fault is in the data passed to the JSON encoder, but an error should be thrown here so merchants know the product data couldn't be imported.

**Comment by oserediuk** [comment]
Hello! Please, add your code base version

**Comment by jameswithers** [comment]
Enterprise 2.1.0

**Comment by dthampy** [comment]
can you send the data file( the batch which has the invalid data) ? 
you can send it to dthampy@magento.com. 
Also it'd be great if you could scramble any sensitive information.

**Comment by jameswithers** [comment]
@dthampy have emailed

**Comment by IlnitskiyArtem** [comment]
Hi, @jameswithers. Can you provide your csv file to reproduce your issue as it was in your case?

**Comment by jameswithers** [comment]
@IlnitskiyArtem I sent this to @dthampy nearly one year (!) ago. The problem is not in the file, it's in the code (which returns null, rather than throwing an exception if a batch of records couldn't convert to JSON). This issue is so old that the links in the opening post are now out of date.

**Comment by IlnitskiyArtem** [comment]
@jameswithers I understand, but when tried to reproduce it on latest Magento branches (2.2.0, 2.1.7) I didn't observed this behavior. I will try it on 2.1.0 too.

**Comment by jameswithers** [comment]
@IlnitskiyArtem The error is still present in the code:

https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1539 stops product imports when it encounters a non-true value e.g. `null`. `null` is being entered into the import data tables by 
https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/ImportExport/Model/ResourceModel/Import/Data.php#L159, as it does not check that `$this->jsonHelper->jsonEncode($data)` returns a response other than `null`, so it enters `null` into the tables. This `null` value is then returned by https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/ImportExport/Model/ResourceModel/Import/Data.php#L131, which causes the import to end prematurely when this value is returned by the database (https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1539).

As in the opening of this ticket a year ago, the fundamental issue is that `$this->jsonHelper->jsonEncode($data)` is not checked for a value before being used in https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/ImportExport/Model/ResourceModel/Import/Data.php#L159. If  `$this->jsonHelper->jsonEncode($data)` returns `null`, Magento should notify the user that there was a problem processing that bunch as the data could not be JSON encoded. Instead, users see a message that the import was successful, even though not all records have processed.

**Comment by IlnitskiyArtem** [comment]
@jameswithers I tried to reproduce it importing 100+ simple products about 20 times, each time changing price and quantity but still cannot cannot observe this behavior. Please, provide more information about your .csv's sensitive data, with my .csv everything works fine. Without reproducing the case i can't create internal ticket.

**Comment by jameswithers** [comment]
@IlnitskiyArtem the problem is not the file (I no longer have access to this as it was over a year ago), it's in Magento not raising an error. If you unit test this, you should be able to make `jsonEncode` return `null` once, and you will see the behaviour in action.

**Comment by IlnitskiyArtem** [comment]
@jameswithers Created internal issue MAGETWO-70963 to investigate and track this issue. Thanks for your help.

**Comment by magento-engcom-team** [comment]
@jameswithers, thank you for your report.
We've created internal ticket(s) MAGETWO-70963 to track progress on the issue.

**Comment by lewisvoncken** [comment]
@okorshenko @magento-engcom-team  @maksek  
My college has already created a fix for this. I will  come back to you this week with a pull request with his fix.

**Comment by tools-utrecht-hh** [comment]
A pull request with a fix has been made for branch 2.1-develop in the partner Github

**Comment by WilXP** [comment]
I'm working on it #SQUASHTOBERFEST 2017

**Comment by WilXP** [comment]
I'm working on it #SQUASHTOBERFEST 2017

**Comment by vkublytskyi** [comment]
Thank you all who participated in the discussion on the issue.  @experius-nl created a PR in partners repository to add handling of JSON encoding error. We are going to accept and merge these changes.

However, such fix cannot be counted as a full as any invalid data should be detected before  `Magento\ImportExport\Model\ResourceModel\Import\Data::saveBunch` call. So if some data lead to failure in `json_encode` (e.g. `JSON_ERROR_UTF8`) this also shows that there is some issue with validation in earlier stages that should be found and fixed. The help of the Community in this highly welcome and appreciated.

**Comment by piotrekkaminski** [comment]
The issue was moved to: https://github.com/magento-engcom/import-export-improvements/issues/93

**Comment by okorshenko** [comment]
Hi @jameswithers. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1343 by @vkublytskyi in 2.3-develop branch
Related commit(s):
 - 268b0c9a6d1e2038421e625bd9d40218843a6153
 - 5fcde49b3175e54ebba0b250996f9ee48d2b2ab8
 - 18b716e40aa9d56edb4978c6efa446f7efd2fd0e
 - c20ed34d1a1b1930fe4aac42e1039d931ed11dec
 - 2f38a65d8fdc4f6faea775e99997ab6ec360698d
 - 767305ad2e8c5c795b4ef561536c3cba52f4bb26
 - 97fac9f67b8e3201c469a9ab7283b0f63eb2c440
 - 14a4df89ab6aebec1a669ecf99aac50a8a07e553
 - d57fcb04cb2643aca96efc8876bbf1d7e3a4d78a
 - 0f4ffba46698151e4662036d15c77dd9e57ba76d

The fix will be available with the upcoming 2.3.0 release.
