### ISSUE TITLE
Encountered end of file Magento Marketplace

### ISSUE THREAD

**Issue by MisterPat** [magento/magento2#5848]
Hello, for some reason i'm unable to use the marketplace when entering my public & private key I get the error message: Encountered end of file in a red box. (actualy it does not matter what I enter, message appears before keys are verified)

![image](https://cloud.githubusercontent.com/assets/20693836/17198933/6caa66ae-5479-11e6-9c21-9de7100fcabd.png)

I'm using a shared server running Directadmin (Custombuild 2.0), with all requirements PHP7, MariaDB 10. I have this error while upgrading an existing store, but also with a clean fresh install from 2.10 with demo data,

I suspect the problem hides in the server configuration. On another server from another supplier with seemingly the same setup but lower system specifications I do not have this issue.

**Comment by dthampy** [comment]
An internal Jira Ticket ->MAGETWO-54717 exists for this issue.

**Comment by boovi-raywe** [comment]
I have a same problem, anyone can help? pls

**Comment by zohlandt** [comment]
Anyone has been able to solve this? I have the same problem and unfortunately I  can't Find a solution anywhere

**Comment by zohlandt** [comment]
**YES, I found the solution!!!!!**

https://github.com/magento/magento2/commit/b5700fe2da786e8615d10a77647397382804c37c

Hope I can help someone else with this. please let me know if this was helpful!

**Comment by magento-engcom-team** [comment]
@MisterPat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9
