### ISSUE TITLE
Add to cart not working for Configurable product in product listing page

### ISSUE THREAD

**Issue by tbenny** [magento/magento2#5850]
The add to cart  is not working  for Configurable product in product listing page

### Preconditions

1. Magento version is 2.0.7 , php 7.0.4 and mysql 5.6
### Steps to reproduce

1. Go to the product listing page in magento2.0.7 and try to add a configurable product
2. select the configurable product options and try to add to cart
3. the cart is not updated and when click on the mini cart icon it will redirect to product detail page with no cart items and we can add product only from the product details page
### Expected result

1. The Configurable products need to be get added to cart in the product listing page rather than redirecting to product detail page when click on the mini cart icon.
### Actual result

1. [Screenshot, logs]

**Comment by oserediuk** [comment]
Hello! Please, update your description, it looks like not full

**Comment by tbenny** [comment]
we have updated the steps to reproduce @oserediuk

**Comment by tbenny** [comment]
This issue is handled well in magento 2.1.0

**Comment by AVoskoboinikov** [comment]
Hi, @tbenny 

Thanks for reporting. We already have this issue here https://github.com/magento/magento2/issues/2574 so I will close this one because of duplication. You can watch progress on https://github.com/magento/magento2/issues/2574 if you need.

**Comment by twistedatrocity** [comment]
Is this fix in the 2.1.6 release?  It's definitely not in 2.1.5
