### ISSUE TITLE
Checkout button not displayed when "One Page Checkout" option selected as "No" 

### ISSUE THREAD

**Issue by juelghosh1** [magento/magento2#5855]
Check out option is not available in Magento Customer Website for setting "One Page Checkout" as No in Magento admin.

Version: Magento 1.9

Steps:
1. Login to Magento 1.9 Admin
2. Click on "System" from top menu bar and Select "Configuration"
3. Select "Checkout" setting option from the left menu bar under "SALES"  
4. Select "Enable Onepage Checkout" option as "No"
5. Now launch Magento customer website 
6. Search for Product and Add to Cart
7. Go to Shopping Cart and check that Checkout option is not available

Expected Result: When One Page Checkout is selected as "No", Checkout option should be available and Checkout should be Multi page checkout.

Actual Result: Checkout option gets disabled for selecting One Page Checkout as No.

**Comment by YevSent** [comment]
Hi @juelghosh1 , this repo only for Magento 2.x versions. That's why I'm close this issue.
