### ISSUE TITLE
New Order Status config in payment method is useless

### ISSUE THREAD

**Issue by hiephm** [magento/magento2#5860]
### Preconditions

Magento CE 2.1.0
### Problem

In payment module that is gateway (support authorize, capture command), setting New Order Status config does not have any effect, new orders still have default status of processing state.
### Reason

In `\Magento\Sales\Model\Order\Payment::place`, the status is get from config:

```
$orderStatus = $methodInstance->getConfigData('order_status');
```

which is assumed to be set to order later:

```
$this->processAction($action, $order);
$orderState = $order->getState() ? $order->getState() : $orderState;
$orderStatus = $order->getStatus() ? $order->getStatus() : $orderStatus;
```

but in current code, this will never happen since in `processAction` there is a chain of calls which eventually call:

```
$message = $this->stateCommand->execute($payment, $amount, $order);
```

This `stateCommand` can be either `\Magento\Sales\Model\Order\Payment\State\AuthorizeCommand` or `\Magento\Sales\Model\Order\Payment\State\CaptureCommand`, which in its `execute` method having a code like this:

```
        $state = Order::STATE_PROCESSING;
        $status = false;
...
        if ($payment->getIsFraudDetected()) {
            $status = Order::STATUS_FRAUD;
        }
        $this->setOrderStateAndStatus($order, $status, $state);
```

This will always set status to `$order` (either fraud or default) and cause the above $orderStatus never been set.
### Suggestion fix:

I still not sure which place should be fixed, may be eliminate the call to `setOrderStateAndStatus` will do the job since the order state/status will be set later in `Payment::place()`

**Comment by hiephm** [comment]
Here is a work around using around plugin for \Magento\Sales\Model\Order\Payment\State\CommandInterface:

```
    public function aroundExecute(CommandInterface $subject, \Closure $proceed, OrderPaymentInterface $payment, $amount, OrderInterface $order)
    {
        $result = $proceed($payment, $amount, $order);
        if ($payment->getMethod() == '<our payment method code>') {
            $orderStatus = $this->config->getValue('order_status');
            if ($orderStatus && $order->getState() == Order::STATE_PROCESSING) {
                $order->setStatus($orderStatus);
            }
        }

        return $result;
    }
```

**Comment by alena-marchenko** [comment]
Ho @hiephm 

We've created MAGETWO-57846 internal ticket regarding this issue,
Thank you!

**Comment by mcspronko** [comment]
Hi @alena-marchenko 
This will be a great fix and contribution into all payment methods including built-in and custom ones.

**Comment by ctadlock** [comment]
@alena-marchenko @hiephm This similar/same issue is happening with offline payments (chech, cash on delivery...); they are always set to `pending` regardless of what the default status with state=new is.

**Comment by YevSent** [comment]
Hi, @hiephm, the fix merged into the develop branch.

**Comment by leoquijano** [comment]
Hi guys,

I see this is in branch 2.3-developed, and it was backported to 2.1-develop. Is this going to be backported to 2.2 as well?

Thanks!

**Comment by JMLucas96** [comment]
Hi, @hiephm I tried to execute your solution but any breakpoint stops on function when I purchase a new item and an order is created, I need to create a di.xml or something else? 
I have this class:
```
<?php
namespace Compsaonline\OrderState\Model\Order\State;

use Magento\Sales\Api\Data\OrderInterface;
use Magento\Sales\Api\Data\OrderPaymentInterface;
use Magento\Sales\Model\Order;
use Magento\Sales\Model\Order\Payment\State\CommandInterface as BaseCommandInterface;

class CommandInterface
{
    /**
     * Set pending order status on order place
     * see https://github.com/magento/magento2/issues/5860
     *
     * @todo Refactor this when another option becomes available
     *
     * @param BaseCommandInterface $subject
     * @param \Closure $proceed
     * @param OrderPaymentInterface $payment
     * @param $amount
     * @param OrderInterface $order
     * @return mixed
     */
    public function aroundExecute(BaseCommandInterface $subject, \Closure $proceed, OrderPaymentInterface $payment, $amount, OrderInterface $order)
    {
        $result = $proceed($payment, $amount, $order);
        if ($payment->getMethod() === '') {
            $orderStatus = Order::STATE_NEW;
            if ($orderStatus && $order->getState() == Order::STATE_PROCESSING) {
                $order->setState($orderStatus)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_NEW));
            }
        }
        return $result;
    }
}
```
And I have this structure in my module:

--Compsaonline
---OrderState
---etc
-----module.xml
---Model
-----State
-------CommandInterface.php
---registration.php

I have Magento2.1.8 CE

**Comment by vincentwinkel** [comment]
@JMLucas96 creating a plugin requires to set up a `di.xml` containing at least something like:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Sales\Model\Order\Payment\State\CommandInterface">
         <plugin name="your_name" type="Your\Module\path\CommandInterface"/>
    </type>
</config>
```

But this workaround doesn't work neither for me. And because I know flushing 100 times the cache + removing generated files is often not enough to see code updates, I directly put some `die(`) in all the `Magento\Sales\Model\Order\Payment\State` commands, but vainly.

Magento 2.0 for me (I know...).

**Comment by duccnttk39c** [comment]
This error is too easy, I can help you enlighten in 30 minutes

**Comment by ant-workaholic** [comment]
This issue is still present in Magento 2.3.3. I am not sure that this should be just closed.
