### ISSUE TITLE
[Magento 2.1.0] Translation

### ISSUE THREAD

**Issue by vjacquemin-sqli** [magento/magento2#5861]
Dynamic translations does not work in customer registration page (password strength indicator)

**Comment by andidhouse** [comment]
It also does not work in some other parts of the checkout as well. Also some codes are used more then once. If you change it on one place it is also changed at another place - for example step 1 checkout title is used at the cart page totals as well which makes no sense at all.

Also: The translation (inline frontend) does not work for the checkout user data? street address/city/zip code etc.

The inline translation seems very buggy at this stage :/

**Comment by andimov** [comment]
@vjacquemin-sqli 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the template.

**Comment by andidhouse** [comment]
Magento 2.1 / Nginx / phh7 / varnish / redis
1. Turn inline translation on for frontend in the backend
2. Go to registration page in the frontend
3. Try to edit password strength indicator

Expected Results:

The password strength indicator can be edited

Results:

The password strength indicator can NOT be edited

The translation also does not work as i wrote for some checkout parts. It is kind of not consistent - for some parts it works for some it does not at all.

**Comment by vjacquemin-sqli** [comment]
Magento 2.1 / Apache / phh7 / varnish

Write password in customer registration
Expected Results:

error message is not translated

Results:

Error message is not translated

Same as andidhouse. Some error message translation work and for some, it does not work.

**Comment by pboisvert** [comment]
@antboiko not sure why this was labeled as "prod" but passing to you since you own translations

**Comment by andimov** [comment]
@antboiko Sorry if this was incorrect. Should we implement the translations of these messages?

**Comment by antboiko** [comment]
Hi @vjacquemin-sqli , thanks for reporting. We have already created internal ticket MAGETWO-55900 to fix this issue.

Best,
Anton.

**Comment by olysenko** [comment]
Fix for the issue was delivered to develop branch in commit 14028aa
Backports for 2.1 and 2.0 are scheduled and will be delivered later

**Comment by Ctucker9233** [comment]
@olysenko any commit references for the backports?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250
