### ISSUE TITLE
Braintree are broken in French Language

### ISSUE THREAD

**Issue by quienti** [magento/magento2#5862]
### Preconditions
1. Magento 2.1.0
2. PHP 5.6
### Steps to reproduce
1. Admin in French language
2. Go to System => Config => Sales => Payement => Braintree
3. Error in payment_fr_braintree_section_braintree_braintree_country_specific_specificcountry
### Expected result
1. No error in JS
### Actual result
1. SyntaxError: missing ) after argument list
   2.

`
<select name="groups[braintree_section][groups][braintree][groups][braintree_country_specific][fields][countrycreditcard][value][<%- _id %>][country_id]" id="" class="" title="" ><option value="AF" <%= option_extra_attrs.option_1330155825 %> >Afghanistan</option><option value="ZA" <%= option_extra_attrs.option_2015022856 %> >Afrique du Sud</option><option value="DZ" <%= option_extra_attrs.option_641612091 %> >Algérie</option><option value="DE" <%= option_extra_attrs.option_2872456398 %> >Allemagne</option><option value="AD" <%= option_extra_attrs.option_2705780765 %> >Andorre</option><option value="AO" <%= option_extra_attrs.option_915679637 %> >Angola</option><option value="AI" <%= option_extra_attrs.option_3757542560 %> >Anguilla</option><option value="AQ" <%= option_extra_attrs.option_3432715510 %> >Antarctique</option><option value="AG" <%= option_extra_attrs.option_944742823 %> >Antigua-et-Barbuda</option><option value="AN" <%= option_extra_attrs.option_1100159235 %> >Antilles néerlandaises</option><option value="SA" <%= option_extra_attrs.option_2849535041 %> >Arabie saoudite</option><option value="AR" <%= option_extra_attrs.option_1435649356 %> >Argentine</option><option value="AM" <%= option_extra_attrs.option_3633989817 %> >Arménie</option><option value="AW" <%= option_extra_attrs.option_637055427 %> >Aruba</option><option value="AU" <%= option_extra_attrs.option_3421950191 %> >Australie</option><option value="AT" <%= option_extra_attrs.option_3169968249 %> >Autriche</option><option value="AZ" <%= option_extra_attrs.option_1531563390 %> >Azerbaïdjan</option><option value="BS" <%= option_extra_attrs.option_163063321 %> >Bahamas</option><option value="BH" <%= option_extra_attrs.option_2212360181 %> >Bahreïn</option><option value="BD" <%= option_extra_attrs.option_2322310110 %> >Bangladesh</option><option value="BB" <%= option_extra_attrs.option_1661470443 %> >Barbade</option><option value="BE" <%= option_extra_attrs.option_4251751240 %> >Belgique</option><option value="BZ" <%= option_extra_attrs.option_1885642429 %> >Belize</option><option value="BM" <%= option_extra_attrs.option_4088863610 %> >Bermudes</option><option value="BT" <%= option_extra_attrs.option_2547823546 %> >Bhoutan</option><option value="BO" <%= option_extra_attrs.option_498694742 %> >Bolivie</option><option value="BW" <%= option_extra_attrs.option_248898048 %> >Botswana</option><option value="BN" <%= option_extra_attrs.option_1790855872 %> >Brunéi Darussalam</option><option value="BR" <%= option_extra_attrs.option_2126452367 %> >Brésil</option><option value="BG" <%= option_extra_attrs.option_325251684 %> >Bulgarie</option><option value="BF" <%= option_extra_attrs.option_1684390642 %> >Burkina Faso</option><option value="BI" <%= option_extra_attrs.option_4107984739 %> >Burundi</option><option value="BJ" <%= option_extra_attrs.option_1842581209 %> >Bénin</option><option value="KH" <%= option_extra_attrs.option_1377785020 %> >Cambodge</option><option value="CM" <%= option_extra_attrs.option_3937151547 %> >Cameroun</option><option value="CA" <%= option_extra_attrs.option_3810158096 %> >Canada</option><option value="CV" <%= option_extra_attrs.option_1623843799 %> >Cap-Vert</option><option value="CL" <%= option_extra_attrs.option_2645236397 %> >Chili</option><option value="CN" <%= option_extra_attrs.option_1940224897 %> >Chine</option><option value="CY" <%= option_extra_attrs.option_4034330182 %> >Chypre</option><option value="CO" <%= option_extra_attrs.option_77744919 %> >Colombie</option><option value="KM" <%= option_extra_attrs.option_578134067 %> >Comores</option><option value="KR" <%= option_extra_attrs.option_2944249286 %> >Corée du Sud</option><option value="CR" <%= option_extra_attrs.option_1738811342 %> >Costa Rica</option><option value="HR" <%= option_extra_attrs.option_2219900421 %> >Croatie</option><option value="CU" <%= option_extra_attrs.option_4190155373 %> >Cuba</option><option value="DK" <%= option_extra_attrs.option_1284381129 %> >Danemark</option><option value="DJ" <%= option_extra_attrs.option_998844767 %> >Djibouti</option><option value="DM" <%= option_extra_attrs.option_2783821052 %> >Dominique</option><option value="SV" <%= option_extra_attrs.option_705425798 %> >El Salvador</option><option value="ES" <%= option_extra_attrs.option_1190768862 %> >Espagne</option><option value="EE" <%= option_extra_attrs.option_2989294991 %> >Estonie</option><option value="FJ" <%= option_extra_attrs.option_163531741 %> >Fidji</option><option value="FI" <%= option_extra_attrs.option_2427853415 %> >Finlande</option><option value="FR" <%= option_extra_attrs.option_450089867 %> >France</option><option value="GA" <%= option_extra_attrs.option_2272699156 %> >Gabon</option><option value="GM" <%= option_extra_attrs.option_2395008831 %> >Gambie</option><option value="GH" <%= option_extra_attrs.option_4272561072 %> >Ghana</option><option value="GI" <%= option_extra_attrs.option_2309827366 %> >Gibraltar</option><option value="GD" <%= option_extra_attrs.option_4145829787 %> >Grenade</option><option value="GL" <%= option_extra_attrs.option_4190625705 %> >Groenland</option><option value="GR" <%= option_extra_attrs.option_63496906 %> >Grèce</option><option value="GP" <%= option_extra_attrs.option_3989210086 %> >Guadeloupe</option><option value="GU" <%= option_extra_attrs.option_2645325673 %> >Guam</option><option value="GT" <%= option_extra_attrs.option_3937093631 %> >Guatemala</option><option value="GG" <%= option_extra_attrs.option_1846871585 %> >Guernesey</option><option value="GN" <%= option_extra_attrs.option_399097477 %> >Guinée</option><option value="GQ" <%= option_extra_attrs.option_2596385648 %> >Guinée équatoriale</option><option value="GW" <%= option_extra_attrs.option_1940002373 %> >Guinée-Bissau</option><option value="GY" <%= option_extra_attrs.option_2484747074 %> >Guyana</option><option value="GF" <%= option_extra_attrs.option_420624055 %> >Guyane française</option><option value="GE" <%= option_extra_attrs.option_2149279501 %> >Géorgie</option><option value="GS" <%= option_extra_attrs.option_1959776860 %> >Géorgie du Sud et les îles Sandwich du Sud</option><option value="HT" <%= option_extra_attrs.option_1832082224 %> >Haïti</option><option value="HN" <%= option_extra_attrs.option_2421269066 %> >Honduras</option><option value="HU" <%= option_extra_attrs.option_439643046 %> >Hongrie</option><option value="IN" <%= option_extra_attrs.option_2303365899 %> >Inde</option><option value="ID" <%= option_extra_attrs.option_1772059157 %> >Indonésie</option><option value="IE" <%= option_extra_attrs.option_513297027 %> >Irlande</option><option value="IS" <%= option_extra_attrs.option_3930914770 %> >Islande</option><option value="IL" <%= option_extra_attrs.option_1732571687 %> >Israël</option><option value="IT" <%= option_extra_attrs.option_1948805745 %> >Italie</option><option value="JM" <%= option_extra_attrs.option_997101938 %> >Jamaïque</option><option value="JP" <%= option_extra_attrs.option_1483275691 %> >Japon</option><option value="JE" <%= option_extra_attrs.option_901060928 %> >Jersey</option><option value="JO" <%= option_extra_attrs.option_3579899998 %> >Jordanie</option><option value="KZ" <%= option_extra_attrs.option_2712020468 %> >Kazakhstan</option><option value="KE" <%= option_extra_attrs.option_749611009 %> >Kenya</option><option value="KG" <%= option_extra_attrs.option_3265284397 %> >Kirghizistan</option><option value="KI" <%= option_extra_attrs.option_622355498 %> >Kiribati</option><option value="KW" <%= option_extra_attrs.option_3742849353 %> >Koweït</option><option value="LA" <%= option_extra_attrs.option_1686272735 %> >Laos</option><option value="LS" <%= option_extra_attrs.option_2537229207 %> >Lesotho</option><option value="LV" <%= option_extra_attrs.option_3880910616 %> >Lettonie</option><option value="LY" <%= option_extra_attrs.option_2012144265 %> >Libye</option><option value="LI" <%= option_extra_attrs.option_1784279789 %> >Liechtenstein</option><option value="LT" <%= option_extra_attrs.option_157261364 %> >Lituanie</option><option value="LU" <%= option_extra_attrs.option_2119741090 %> >Luxembourg</option><option value="MG" <%= option_extra_attrs.option_2499473067 %> >Madagascar</option><option value="MY" <%= option_extra_attrs.option_1861604296 %> >Malaisie</option><option value="MW" <%= option_extra_attrs.option_2303590095 %> >Malawi</option><option value="MV" <%= option_extra_attrs.option_4266315353 %> >Maldives</option><option value="ML" <%= option_extra_attrs.option_52967203 %> >Mali</option><option value="MT" <%= option_extra_attrs.option_272936821 %> >Malte</option><option value="MA" <%= option_extra_attrs.option_2107198366 %> >Maroc</option><option value="MQ" <%= option_extra_attrs.option_1613650938 %> >Martinique</option><option value="MU" <%= option_extra_attrs.option_1732485091 %> >Maurice</option><option value="MR" <%= option_extra_attrs.option_4180085312 %> >Mauritanie</option><option value="YT" <%= option_extra_attrs.option_1055553568 %> >Mayotte</option><option value="MX" <%= option_extra_attrs.option_435348318 %> >Mexique</option><option value="MD" <%= option_extra_attrs.option_234077969 %> >Moldavie</option><option value="MC" <%= option_extra_attrs.option_2476157618 %> >Monaco</option><option value="MN" <%= option_extra_attrs.option_3978712591 %> >Mongolie</option><option value="MS" <%= option_extra_attrs.option_2384476886 %> >Montserrat</option><option value="MZ" <%= option_extra_attrs.option_4160520818 %> >Mozambique</option><option value="NA" <%= option_extra_attrs.option_1454643293 %> >Namibie</option><option value="NR" <%= option_extra_attrs.option_3523893635 %> >Nauru</option><option value="NI" <%= option_extra_attrs.option_1483706479 %> >Nicaragua</option><option value="NE" <%= option_extra_attrs.option_1373232196 %> >Niger</option><option value="NG" <%= option_extra_attrs.option_3218586984 %> >Nigéria</option><option value="NU" <%= option_extra_attrs.option_1282329632 %> >Niue</option><option value="NO" <%= option_extra_attrs.option_2970367322 %> >Norvège</option><option value="NC" <%= option_extra_attrs.option_3099228529 %> >Nouvelle-Calédonie</option><option value="NZ" <%= option_extra_attrs.option_3704738225 %> >Nouvelle-Zélande</option><option value="NP" <%= option_extra_attrs.option_1006909615 %> >Népal</option><option value="OM" <%= option_extra_attrs.option_1176069431 %> >Oman</option><option value="UG" <%= option_extra_attrs.option_383874802 %> >Ouganda</option><option value="UZ" <%= option_extra_attrs.option_1978079787 %> >Ouzbékistan</option><option value="PK" <%= option_extra_attrs.option_1646317212 %> >Pakistan</option><option value="PW" <%= option_extra_attrs.option_1981911763 %> >Palaos</option><option value="PA" <%= option_extra_attrs.option_2197104514 %> >Panama</option><option value="PG" <%= option_extra_attrs.option_1805025975 %> >Papouasie-Nouvelle-Guinée</option><option value="PY" <%= option_extra_attrs.option_2442772436 %> >Paraguay</option><option value="NL" <%= option_extra_attrs.option_671442144 %> >Pays-Bas</option><option value="PH" <%= option_extra_attrs.option_4213808934 %> >Philippines</option><option value="PN" <%= option_extra_attrs.option_306854419 %> >Pitcairn</option><option value="PL" <%= option_extra_attrs.option_4232338239 %> >Pologne</option><option value="PF" <%= option_extra_attrs.option_479310369 %> >Polynésie française</option><option value="PT" <%= option_extra_attrs.option_4012426089 %> >Portugal</option><option value="PE" <%= option_extra_attrs.option_2241389467 %> >Pérou</option><option value="QA" <%= option_extra_attrs.option_2616071875 %> >Qatar</option><option value="HK" <%= option_extra_attrs.option_3761985221 %> >R.A.S. chinoise de Hong Kong</option><option value="MO" <%= option_extra_attrs.option_2585880217 %> >R.A.S. chinoise de Macao</option><option value="RO" <%= option_extra_attrs.option_1467705351 %> >Roumanie</option><option value="GB" <%= option_extra_attrs.option_511701678 %> >Royaume-Uni</option><option value="RU" <%= option_extra_attrs.option_2853802365 %> >Russie</option><option value="RW" <%= option_extra_attrs.option_1142419537 %> >Rwanda</option><option value="CF" <%= option_extra_attrs.option_2105471923 %> >République centrafricaine</option><option value="DO" <%= option_extra_attrs.option_1273224656 %> >République dominicaine</option><option value="CZ" <%= option_extra_attrs.option_1769975804 %> >République tchèque</option><option value="RE" <%= option_extra_attrs.option_3081666841 %> >Réunion</option><option value="EH" <%= option_extra_attrs.option_3432806706 %> >Sahara occidental</option><option value="BL" <%= option_extra_attrs.option_2226138092 %> >Saint-Barthélémy</option><option value="KN" <%= option_extra_attrs.option_3145527689 %> >Saint-Kitts-et-Nevis</option><option value="SM" <%= option_extra_attrs.option_2691577962 %> >Saint-Marin</option><option value="MF" <%= option_extra_attrs.option_3825065533 %> >Saint-Martin</option><option value="PM" <%= option_extra_attrs.option_2336451497 %> >Saint-Pierre-et-Miquelon</option><option value="VC" <%= option_extra_attrs.option_983687464 %> >Saint-Vincent-et-les Grenadines</option><option value="SH" <%= option_extra_attrs.option_3489975525 %> >Sainte-Hélène</option><option value="LC" <%= option_extra_attrs.option_2324438003 %> >Sainte-Lucie</option><option value="WS" <%= option_extra_attrs.option_1041088525 %> >Samoa</option><option value="AS" <%= option_extra_attrs.option_580220378 %> >Samoa américaines</option><option value="ST" <%= option_extra_attrs.option_3288699050 %> >Sao Tomé-et-Principe</option><option value="SC" <%= option_extra_attrs.option_1205212525 %> >Seychelles</option><option value="SG" <%= option_extra_attrs.option_1086050676 %> >Singapour</option><option value="SK" <%= option_extra_attrs.option_1225629023 %> >Slovaquie</option><option value="SI" <%= option_extra_attrs.option_2802056307 %> >Slovénie</option><option value="SO" <%= option_extra_attrs.option_1314937158 %> >Somalie</option><option value="LK" <%= option_extra_attrs.option_2220331969 %> >Sri Lanka</option><option value="CH" <%= option_extra_attrs.option_2596724404 %> >Suisse</option><option value="SR" <%= option_extra_attrs.option_761673119 %> >Suriname</option><option value="SE" <%= option_extra_attrs.option_2931142744 %> >Suède</option><option value="SJ" <%= option_extra_attrs.option_1040887241 %> >Svalbard et Île Jan Mayen</option><option value="SZ" <%= option_extra_attrs.option_599637421 %> >Swaziland</option><option value="SN" <%= option_extra_attrs.option_963078608 %> >Sénégal</option><option value="TJ" <%= option_extra_attrs.option_1900755726 %> >Tadjikistan</option><option value="TZ" <%= option_extra_attrs.option_1828465514 %> >Tanzanie</option><option value="TW" <%= option_extra_attrs.option_307058647 %> >Taïwan</option><option value="TD" <%= option_extra_attrs.option_2532513289 %> >Tchad</option><option value="TF" <%= option_extra_attrs.option_2029877029 %> >Terres australes françaises</option><option value="IO" <%= option_extra_attrs.option_4266501021 %> >Territoire britannique de l'océan Indien</option><option value="PS" <%= option_extra_attrs.option_1900828362 %> >Territoire palestinien</option><option value="TH" <%= option_extra_attrs.option_2672122402 %> >Thaïlande</option><option value="TL" <%= option_extra_attrs.option_2552798779 %> >Timor oriental</option><option value="TG" <%= option_extra_attrs.option_268060595 %> >Togo</option><option value="TK" <%= option_extra_attrs.option_105647000 %> >Tokelau</option><option value="TO" <%= option_extra_attrs.option_18993025 %> >Tonga</option><option value="TT" <%= option_extra_attrs.option_2336491117 %> >Trinité-et-Tobago</option><option value="TN" <%= option_extra_attrs.option_1982267159 %> >Tunisie</option><option value="TM" <%= option_extra_attrs.option_4012879533 %> >Turkménistan</option><option value="TR" <%= option_extra_attrs.option_1646764888 %> >Turquie</option><option value="TV" <%= option_extra_attrs.option_1699374913 %> >Tuvalu</option><option value="UA" <%= option_extra_attrs.option_4286763975 %> >Ukraine</option><option value="UY" <%= option_extra_attrs.option_3975039889 %> >Uruguay</option><option value="VU" <%= option_extra_attrs.option_3463795833 %> >Vanuatu</option><option value="VE" <%= option_extra_attrs.option_3552723997 %> >Venezuela</option><option value="VN" <%= option_extra_attrs.option_1141939605 %> >Viêt Nam</option><option value="WF" <%= option_extra_attrs.option_1406149862 %> >Wallis-et-Futuna</option><option value="YE" <%= option_extra_attrs.option_1415207122 %> >Yémen</option><option value="ZM" <%= option_extra_attrs.option_1907131171 %> >Zambie</option><option value="EG" <%= option_extra_attrs.option_1545823395 %> >Égypte</option><option value="AE" <%= option_extra_attrs.option_3594633355 %> >Émirats arabes unis</option><option value="EC" <%= option_extra_attrs.option_1531879610 %> >Équateur</option><option value="ER" <%= option_extra_attrs.option_838762568 %> >Érythrée</option><option value="VA" <%= option_extra_attrs.option_3568271364 %> >État de la Cité du Vatican</option><option value="FM" <%= option_extra_attrs.option_2547768958 %> >États fédérés de Micronésie</option><option value="US" <%= option_extra_attrs.option_205234831 %> >États-Unis</option><option value="ET" <%= option_extra_attrs.option_3634177405 %> >Éthiopie</option><option value="BV" <%= option_extra_attrs.option_2043859606 %> >Île Bouvet</option><option value="CX" <%= option_extra_attrs.option_2272382672 %> >Île Christmas</option><option value="NF" <%= option_extra_attrs.option_3369111038 %> >Île Norfolk</option><option value="IM" <%= option_extra_attrs.option_272876209 %> >Île de Man</option><option value="KY" <%= option_extra_attrs.option_951022670 %> >Îles Caïmans</option><option value="CC" <%= option_extra_attrs.option_219416380 %> >Îles Cocos - Keeling</option><option value="CK" <%= option_extra_attrs.option_63934222 %> >Îles Cook</option><option value="FO" <%= option_extra_attrs.option_2044051282 %> >Îles Féroé</option><option value="HM" <%= option_extra_attrs.option_156824560 %> >Îles Heard et MacDonald</option><option value="FK" <%= option_extra_attrs.option_2126019403 %> >Îles Malouines</option><option value="MP" <%= option_extra_attrs.option_388590444 %> >Îles Mariannes du Nord</option><option value="MH" <%= option_extra_attrs.option_71693114 %> >Îles Marshall</option><option value="UM" <%= option_extra_attrs.option_4130643948 %> >Îles Mineures Éloignées des États-Unis</option><option value="SB" <%= option_extra_attrs.option_819013115 %> >Îles Salomon</option><option value="TC" <%= option_extra_attrs.option_144147370 %> >Îles Turks et Caïques</option><option value="VG" <%= option_extra_attrs.option_1036789041 %> >Îles Vierges britanniques</option><option value="VI" <%= option_extra_attrs.option_3665037366 %> >Îles Vierges des États-Unis</option><option value="AX" <%= option_extra_attrs.option_3041373266 %> >Îles Åland</option></select>'`
### What is the problem
1. In option, there are `Territoire britannique de l'océan Indien`, and this option have an ', so, JS are breaken

**Comment by YevSent** [comment]
Hi, @quienti, could you attach your localization file? Do this issue is reproducible on the latest develop?

**Comment by quienti** [comment]
Hi @joni-jones , where I can find this file ?
And, I do not know if is reproducible on develop branch and I can not test :/

**Comment by YevSent** [comment]
If translation related to Braintree module this file should in the corresponded folder.

**Comment by alena-marchenko** [comment]
Hi @quienti 

Closing this issue due to no response, please reopen when you have an update.

**Comment by quienti** [comment]
Sorry for the delay.
I don't find this file, could you tell me where is it ?
