### ISSUE TITLE
Custom chekcout field

### ISSUE THREAD

**Issue by rlaa** [magento/magento2#5864]
### Preconditions

1. I installed this module https://github.com/rlaa/custom-checkout-fields/blob/master/Test_attr.zip
### Steps to reproduce

1. php bin/magento setup:upgrade
2. php bin/magento cache:clean
3.  php bin/magento cache:flush
### Expected result

1.The custom checkout field is installed in table eav_attribute and it is assigned to necessary forms.
2.The custom checkout field shows up in both frontend and admin address form and it is saved in db.
### Actual result

1.The custom checkout field is installed in table eav_attribute and it is assigned to necessary forms.
2.The custom checkout field shows up in both frontend and admin address form, but it is saving in the db only from admin panel, I need to be able to save it also from the frontend.
### Additional

1.I think the problem appears when I click the next button, custom checkout field is not sent in post data request.
![post-request](https://cloud.githubusercontent.com/assets/20533568/17212433/f5872850-54d7-11e6-871e-baacacf9eb5b.png)

**Comment by andimov** [comment]
@rlaa 
What version do you use?
Why do you think that this is a magento bug?
Where did you find this module?

**Comment by rlaa** [comment]
1. Magento 2 version
2. Because the custom field is installed properly with no errors but it is not saving in the db from frontend, only from admin panel.
3. It is my module.

**Comment by oserediuk** [comment]
Hello @rlaa ! Please, clarify exactly which Magento version do you use

**Comment by rlaa** [comment]
Hello, magento 2.7 CE

**Comment by davidalger** [comment]
The issue reported appears to be with a 3rd-party component. Please work with the vendor (where applicable) to resolve the issue. Alternatively, please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical assistance. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
