### ISSUE TITLE
Product import

### ISSUE THREAD

**Issue by garpik** [magento/magento2#5865]
### Preconditions

Magento ver. 2.1.0, php 7.0.6
### Steps to reproduce

Import product with name 'Bonus'.
### Expected result

Product was created properly.
### Actual result

Error without description:
Maximum error count has been reached or system error is occurred!
### Additional

Possible magento can't create url 'bonus', because it reserved somewhere.

**Comment by andimov** [comment]
@garpik 
Thank you for reporting!

I have reproduced this issue. We will investigate it further.

**Comment by pboisvert** [comment]
@garpik have you tried creating the product manually? Do you get the same error? Have you tried the same import with a different product name? Any errors?

**Comment by garpik** [comment]
@pboisvert I tried to import a product with a different name and it's works. 
If I'm trying to create a product with the name 'Bonus' and a different SKU(like 'Bonus_1') I get this error:'URL key for specified store already exists.'

**Comment by pboisvert** [comment]
@garpik Did you try manually to eliminate the possibility that the product exists already or narrow down the problem to import with that name vs any product creation with that name. if so then should be easy enough to reproduce.

**Comment by garpik** [comment]
Oh, I've found where the problem is.
The store already has a category with name "Bonus" and the product 'Bonus" is a child of this category. There is a conflict  between the category and the product urls.
