### ISSUE TITLE
<script type="text/x-magento-init"> [data-gallery-role=gallery-placeholder] ... -> too broad

### ISSUE THREAD

**Issue by ClaudiuCreanga** [magento/magento2#5870]
On the product page you include this script near product image:

`<script type="text/x-magento-init"> [data-gallery-role=gallery-placeholder] ...`
and then when `mage.apply()` runs those scripts are evaluated. At this point you run `document.querySelectorAll("[data-gallery-role=gallery-placeholder]") ..`

This will make magento re-evaluate all `[data-gallery-role=gallery-placeholder]` elements on the page. Which is fine if you only have one of those elements.

But say you want to grab other products via ajax into the product page (for example if you want to build a next/previous product functionality without refreshing the page) then `$("#gallery).trigger('contentUpdated')` will reevaluate all `[data-gallery-role=gallery-placeholder]` on that page which is not the behaviour you would want because the image of the last product loaded will replace every image. 

So I think it would be better if that selector `[data-gallery-role=gallery-placeholder]` will be more specific. Or another solution is to be able to run `mage.apply()` on a specifc element. At the moment only the body has `contentUpdated` event attached to it. 

### Preconditions

Any magento installation, it is a js issue
### Steps to reproduce

Load on the product page via ajax other products and then run `.trigger('contentUpdated')`

```
$.when(ajaxCall(productUrl)).done(function(response){
        //parse response

        container.append(parsedResponse); //append in container
        container.trigger('contentUpdated'); //trigger update
})
```
### Expected result

1. update content only inside that element not the whole page.  
### Actual result

1. content gets updated for the whole page, every product's image is changed to the last product loaded via ajax.

**Comment by magento-engcom-team** [comment]
@ClaudiuCreanga, thank you for your report.
We've created internal ticket(s) MAGETWO-84605 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ClaudiuCreanga, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
