### ISSUE TITLE
[CE 2.1.0] Fatal issue on BO edit page if a media has been directly deleted on the server

### ISSUE THREAD

**Issue by spipu** [magento/magento2#5871]
Hi,

The steps are : 
- Create a product and add a media in the "Images and Videos" tab.
- Go on the product view page in BO : it works
- Delete the image **directly** on the server to simulate a accidental lost of data 
- Go on the product view page in BO : the following error occurs without the possibility to edit the product : 

> Cannot gather stats! Warning!stat(): stat failed for /var/www/xxxx/pub/media/catalog/product/w/s/ws02-green_main.jpg

It is because there is no protection here: 

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery/Content.php#L135

I think it could be a good think to do something like this : 

```
    public function getImagesJson()
    {
        $value = $this->getElement()->getImages();
        if (is_array($value) &&
            array_key_exists('images', $value) &&
            is_array($value['images']) &&
            count($value['images'])
        ) {
            $directory = $this->_filesystem->getDirectoryRead(DirectoryList::MEDIA);
            $images = $this->sortImagesByPosition($value['images']);
            foreach ($images as &$image) {
                $image['url'] = $this->_mediaConfig->getMediaUrl($image['file']);
                try {
                    $fileHandler = $directory->stat($this->_mediaConfig->getMediaPath($image['file']));
                    $image['size'] = $fileHandler['size'];
                } catch (\Exception $e) {
                    $image['size'] = 0;
                    // @todo add some log
                }
            }
            return $this->_jsonEncoder->encode($images);
        }
        return '[]';
    }
```

**Comment by erikhansen** [comment]
I'm seeing the same issue on 2.1.

**Comment by pboisvert** [comment]
Anton--can you take a look at this? While marked as "improvement" i think the impact here feels like a bug in terms of missing protection from scenario of one or more product images being deleted from the server. We must fix to ensure product edit page still available.

**Comment by antboiko** [comment]
Hi @spipu , thanks for reporting. We already have internal ticket MAGETWO-54718 for fixing this issue and we're working on it.

Best
Anton.

**Comment by KevinMace** [comment]
I'm seeing the same issue on 2.1.1 EE

**Comment by elenleonova** [comment]
The issue has been delivered to 2.1.3

**Comment by spipu** [comment]
tested, ok
