### ISSUE TITLE
"Send Welcome Email From" : storeview doesnt change in multisite 

### ISSUE THREAD

**Issue by kaieleshop** [magento/magento2#5874]
I've got a multisite installation: 2 websites: "Europe" and "Asia". Europe has 2 stores: "France" and "Germany". And "Asia" has only one store: "China". "France" store as one storeview: "French". "Germany" has one storeview: "German". And "China" has 2 storviews: "Chinese" and "English".

The problem is when a new customer account is created in frontend in "Chinese" storeview, I've got in the backend site in "Account Information" tab "Send Welcome Email from "French" and if I change it to "Chinese" it does not change after saving the modification and the welcome email is sent to the customer in french language. Also "Associted to website" is "China" so it is ok. And in "Customer view" tab I've got "account created in chinese" which is ok. The same issue occures if the customer is created in "German storeview" or in "English". The system always displays in "Account Information" tab: "Send Welcome Email from the first storeview name according alphabetical order.

**Comment by crantron** [comment]
@kaieleshop did you solve this? what was the issue? Having the same problem.

**Comment by sja87** [comment]
@kaieleshop @crantron 
same problem. How do you fix the issue?

**Comment by Ctucker9233** [comment]
@kaieleshop ditto

**Comment by crantron** [comment]
@sja87 @kaieleshop , its a core bug -- no fix yet.

**Comment by JesKingDev** [comment]
Can someone link to the related core bug or provide more information? This is a pretty big deal and is a major impediment to proper localization of Magento stores. :(
