### ISSUE TITLE
Can't checkout with product that has a File custom option.

### ISSUE THREAD

**Issue by mverstraete** [magento/magento2#5875]
### Preconditions

Magento 2.1
PHP 5.6.22
### Steps to reproduce
1.  Checkout with a product that has an attached file as part of a custom option.
### Expected result
1. Checkout functions as normal
### Actual result
1. Server returns 500 error.
2. PHP error log contains: PHP Fatal error:  Call to a member function isFile() on null in .../vendor/magento/module-catalog/Model/Product/Option/Type/File.php on line 452

In module-catalog/Model/Product/Option/Type/File.php , on line 452, $this->_rootDirectory is used, but is never initialized anywhere and is therefore null.  I believe you need to inject an instance of \Magento\Framework\Filesystem\Directory\ReadInterface in the constructor and assign it to $this->_rootDirectory

**Comment by andimov** [comment]
@mverstraete 
Thank you for reporting!
Please, check your permissions or run commands in magento dir:
`find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \; && chown -R :apache . && chmod u+x bin/magento`

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
