### ISSUE TITLE
Multi-select option attribute values do not appear in admin

### ISSUE THREAD

**Issue by billcornell** [magento/magento2#5877]
A multi-select attribute with option values does not show any of the values in the product page in admin.

### Preconditions

1.   Magento 2.1, PHP 5.6.23
### Steps to reproduce

1.  Products -> Catalog, then Add Product (simple)
2.  Add product and save it
3.  Add Attribute.  " Catalog Input Type for Store Owner" value is "Multiple Select"
4.  Add 2 or more attribute values.  Save the attribute and save the product.
### Expected result

1.   Attribute option values should appear
### Actual result

1.   Attribute values do NOT appear, but can be seen in source code.

![attribute-option-values-in-source](https://cloud.githubusercontent.com/assets/80064/17229864/6548ee76-54ce-11e6-88ba-27773955d56d.png)
![attribute-properties](https://cloud.githubusercontent.com/assets/80064/17229865/654acde0-54ce-11e6-9185-8c70b60dfb75.png)

**Comment by veloraven** [comment]
@billcornell thank you for your report.
Internal ticket was created for the issue: MAGETWO-56489
But could you please provide more detailed steps? As I was able to reproduce similar issue but it seems to be not exactly the one you described.
Do you have one Store view or several ones?
Do you create new attribute from the product page?
Which values did you fill during attribute creation? Default Store View / Admin / Specific Store View?
"Does not appear in Admin" - do you mean product page or attribute itself (I can see it on screenshot) or both?
So could you please provide steps with each button click and each value entering specified?

**Comment by okorshenko** [comment]
Internal ticket for the fix in develop branch: MAGETWO-56487

**Comment by magento-engcom-team** [comment]
@billcornell  The fix will be available with release 2.2.0 soon
