### ISSUE TITLE
URL Indexer doesn't honor catalog/seo/product_use_categories

### ISSUE THREAD

**Issue by paales** [magento/magento2#5878]
### Preconditions

1. Magento 2.1
### Steps to reproduce

1. Set 'Use Categories Path for Product URLs' to No (Default value)
2. Save a category with products.
### Expected result

1. No category specific url keys are made
### Actual result

1. Category specific url keys are made.

**Comment by paales** [comment]
This line should be conditional (or somewhere deeper, because it doesn't take storeId in account)
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogUrlRewrite/Observer/AfterImportDataObserver.php#L266

This should also be conditional depending on the config:
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php#L171-L176

**Comment by valibus** [comment]
same problem here.
Our canonical became : `http://www.domain.com/catalog/product/view/_ignore_category/1/id/10028/s/name-of-product-6119/`
So it's realy bad in SEO, when will you fix it ?

**Comment by slopukhov** [comment]
@paales thank you for your feedback.
Please, recheck it on the latest 2.1 version of Magento.

**Comment by vzabaznov** [comment]
Hi @paales , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Comment by JMLucas96** [comment]
Same problem, magento2.1.8, 
my url became 
http://www.domain.com/catalog/product/view/_ignore_category/1/id/70102/s/product-name/
