### ISSUE TITLE
Welcome email is sent to customer in wrong language

### ISSUE THREAD

**Issue by kaieleshop** [magento/magento2#5879]
### Preconditions

1. MAGENTO 2.1
2. PHP 7.0.9
### Steps to reproduce

1. New storeview ----> With other language then the default storeview (of course the new language has been installed)
2. Customer/ New customer / Send welcome email from "new storeview"
3. 
### Expected result

1. Welcome email sent to customer in new storeview language
### Actual result

1. In Customer info / Account info: no change the storeview in "Send welcome email from" is still the default storeview.
2. Welcome email is sent to customer in default language not in the new storeview language

**Comment by kaieleshop** [comment]
Same problem occurs with multi websites. The storeview for "Send welcome email from" is always the  first storeview in term of alphabetical order of the default website. Result : welcome message always sent in the same language whatever the storeview or the website in which the customer has been registered. In my case the welcome email is always sent in German language even if my customer is registered in "Royaume-Uni" with english as default language.

![01](https://cloud.githubusercontent.com/assets/17073756/17233996/fa2db772-5534-11e6-85e0-3b3ca1348a57.jpg)
![02](https://cloud.githubusercontent.com/assets/17073756/17234000/007c6934-5535-11e6-8af7-d4ffc25e623e.jpg)

**Comment by sevos1984** [comment]
Duplicates https://github.com/magento/magento2/issues/6240
