### ISSUE TITLE
Untranslatable string "Minimum length of this field must be equal..."

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#5883]
### Preconditions

1. Version: _Magento 2.1_
### Steps to reproduce

1. Use a _magento i18n:collect-phrases_ tool to collect all phrases. 
2. Go to page: _my-domain/customer/account/create/_
3. There is a _"Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored."_ string, which I can not find in a csv file, produced by _collect-phrases_ tool.
### Expected result

1. I should be able to find a phrase "Minimum length" in a file, generated with _magento i18n:collect-phrases_ tool 
### Actual result

![capture](https://cloud.githubusercontent.com/assets/282687/17243961/adf6ba2a-557f-11e6-83bc-4f6c22fada95.JPG)

**Comment by antboiko** [comment]
Hi @jernejh , we have already created ticket MAGETWO-55900 to fix this. 

https://github.com/magento/magento2/issues/5509

Thanks,
Anton.

**Comment by olysenko** [comment]
Fix for the issue  was delivered to develop branch in commit [14028aa](https://github.com/magento/magento2/commit/14028aad37ee7435d89eb3b647e6d03ecd8e2e13)
Backports for 2.1 and 2.0 are scheduled and will be delivered later

**Comment by Ctucker9233** [comment]
@olysenko any idea when we can expect the backports?

**Comment by olysenko** [comment]
hi, expectation is the last month of autamn

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250
