### ISSUE TITLE
Minicart KnockoutJS-Template not loading on iOS Safari and IE11

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5892]
Currently we are experiencing a bug on Magento 2.0.6 where IE11 and iOS Safari are unable to load knockoutJS templates, for example the minicart. 
### Preconditions
- Magento Version used: Magento 2.0.6.
- PHP Version: PHP7
- Problem: Minicart-Wrapper-DOM not loading via KnockoutJS on IE11 and iOS Safari
### Steps to reproduce
- Use IE or Safari and click on the Minicart Icon
### Expected result
- Expected Result: DOM is loaded
### Actual result
- Actual Result: DOM Is not loaded
- Console error:  ![bildschirmfoto 2016-08-02 um 17 24 10](https://cloud.githubusercontent.com/assets/13021579/17334220/b3ef1d88-58d5-11e6-894a-ff68337ee748.png)
- Bug has been appeared in the following browsers: Safari 9.0.1, Safari 9.1.1, Mac Chrome Version 51.0.2704.103 (64-bit), Safari for iOS

_DOM in Chrome/Mac:_
![bildschirmfoto 2016-07-29 um 16 42 52](https://cloud.githubusercontent.com/assets/13021579/17252084/7c205da4-55ab-11e6-936d-1bdb43e3da66.png)

_DOM on IE11:_
![image001](https://cloud.githubusercontent.com/assets/13021579/17252117/a63593de-55ab-11e6-9474-634f010e53cd.png)

If you click on the minicart, it loads the wrapper, but nothing more, as you might know when taking a closer look at the IE-DOM. 

We have the very same issue on Safari/iOS (DOM not loading content), but I cannot debug iOS Safaris DOM (no functions for that :(). 

How can we fix this issue _OR_ is this a bug? Any workaround for that?

**Comment by andimov** [comment]
@grasdaggel 
Thanks for reporting this issue!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by grasdaggel** [comment]
@andimov Seems like the formatting of my ticket makes things unclear, however, any information I could give is already given? 
- Used Version: Magento 2.0.6
- How to reproduce: Use IE11 or any iPhone to reproduce the Bug
- expected Result: DOM for Cart is there
- actual result: no DOM (or Templates) for Cart is there/gets loaded
- actual problem: DOM is not loaded in IE11, IE10 and Safari on iOS

If anything is missing here, just give me a short feedback and I'll be happy to provide it to you.

**Comment by andimov** [comment]
@grasdaggel 
Please, format the description (your first message in this issue) in accordance with the [template](https://github.com/magento/magento2/issues/new) 
It will allow us to process it.

**Comment by grasdaggel** [comment]
@andimov Done.

**Comment by grasdaggel** [comment]
Problem exists in Safari 9.0.1 and 9.1.1, but not in Safari 9.1 - its getting weird. I've updated the first post equal.

**Comment by andimov** [comment]
@grasdaggel 
Try to clear cache, cookie, etc. in Safari 9.0.1

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by grasdaggel** [comment]
The things you have suggested are not doing anything. Please note that we also cleared everything on iOS and so on to, but it hasen't fixed the problem.

**Comment by magento-engcom-team** [comment]
@grasdaggel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
