### ISSUE TITLE
WYSIWYG editor does not update styles of image set in dialog

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5895]
### Precondition
1. CMS page with image in content is present in system
### Steps to reproduce

1. Log in to admin panel
2. Go to Content -> Pages
3. Edit page from preconditions
4. Select image (from preconditions)
5. Open Edit image dialog (using wysiwyg toolbar button)
6. Change any styles on "Appearance" tab of dialog
7. Update image and save page
8. Reopen page
### Expected result

1. Styles are applied to image
### Actual result

1. Styles are not saved

**Comment by pboisvert** [comment]
@spinestalker can you provide which version you are using?

**Comment by Ctucker9233** [comment]
@spinestalker Have you cleared your static cache? Sometimes that is necessary in order to view the style changes.

**Comment by ghost** [comment]
@pboisvert 2.1

**Comment by ghost** [comment]
@Ctucker9233 clearing cache won't do anythign after the edit as changes to style are not saved at all. clearing cache does nothing in this case. tested.

**Comment by oserediuk** [comment]
Hello @spinestalker ! I tried to reproduce your case on the fresh installation Magento 2.1.0 and I didn't reproduce. Styles changes applied successfully and saved. Try to refresh cache after save changes and check again.

**Comment by andimov** [comment]
@spinestalker 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
