### ISSUE TITLE
Web API missing services/corrupt product updates

### ISSUE THREAD

**Issue by AirmanAJK** [magento/magento2#5896]
The issue does not occur in a fresh setup of CE 2.0.8, and does occur in a fresh setup of CE 2.1.0.

To reproduce:
Set Stores > Configuration > Services > Web API > Web API Security > Allow Anonymous Guest Access = Yes

Visit {store url}/swagger
In CE 2.0.8, catalogProductRepositoryV1 would have several verb types shown (post, put, delete). In CE 2.1.0, only two GET methods are available. The same items are missing when viewing all wsdl services as well.

Create and activate a new Integration with permission to access All resources.
Create a category and simple product with enough info to show up as a product page on the storefront.

Test the integration with an authorized call to {store url}/rest/V1/products/{sku}
Now try to change the visibility value to a 1 with a POST call. The response will be "OK", but the value will not be updated, and the entries for the product in the table url_rewrite will be missing!

The product delete REST call works despite not showing up in /swagger.

These issues are only a problem in 2.1.0.

My two main questions are:
1) Does anyone with a CE 2.1.0 build see the POST, PUT, DELETE items on the /swagger page for catalogProductRepositoryV1?
2) Is anyone else seeing their url_rewrite entries disappear when making product updates in REST?

**Comment by AirmanAJK** [comment]
UPDATE
The missing url_rewrite records seem to be caused by a product POST update in REST to set visibility = 1. When 2, 3 or 4 is used, the change doesn't happen, but at least the url_rewrite rows are left untouched. When only sku and visibility are provided for the update call, and visibility = 1, the url_rewrite rows go missing and the visibility is still left untouched in Magento.

**Comment by CodeGlitcher** [comment]
When visibility is set to 1 the url_rewrite are removed. (I think because the product is no longer visible on the website)
But attribute value is updated, only on the page for a storeview.
If you have selected **Store View:  All Store Views** the value for visibility stays the same. 
If you select your default store view the value is changed.
Even if you only have 1 storeview. Attributes with scope store view can be different between All Store Views and your storeview. 
A product is always updated for a storeview.  So attributes with scope on storeview do not change on the **All Store Views** view

**Comment by AirmanAJK** [comment]
Deleting url_rewrite records appears to be a bug rather than intended for the following reasons.
1) It doesn't happen when changing visibility on the backend directly (only REST updates).
2) It doesn't reinsert the url_rewrite rows when the product is set back to visible. Visiting the product page will forever after have a nasty url similar to "/catalog/product/entity/8/categoryid/20"
3) Deleting the url_rewrite rows wouldn't make sense since they do no harm.
4) This still happens no matter what the scope of the visibility attribute is set to (global, website, store).

I haven't had time to try and debug this problem, but I'm wagering that for the REST update, the resource that stores rewrite records for a product is getting initialized to an empty collection which causes deletions during the save.

**Comment by AirmanAJK** [comment]
Another Update.
When taking Magento out of Single Store Mode, the url_rewrite rows do disappear when changing visibility. If Single Store Mode is set to true, the records don't get changed, but they also don't get updated when the url key is changed in Search Engine Optimization section. This seems to be a pretty nasty bug.

**Comment by AirmanAJK** [comment]
Okay. I've found a way to get this to work.

To get url_rewrites to properly update/disappear/appear when dealing with single store mode, you must set the scope of both "visiblity" and "url_key" attributes to global, and edit the product attributes in "Default Store View" (NOT "All Store Views").

If you edit these now global attributes for the product with "All Store Views", the url_rewrite records won't update properly.

If you leave the attributes scopes as "Store View" for visibility and url_key and update with "All Store Views", visibility will update, but the url_rewrites won't be updated/deleted/added when you change the url_key value or make the product visible/invisible.

The problem seems to be updating url_rewrite records when in single-store mode (or in the product edit scope of "All Store Views").

**Comment by ps1dr3x** [comment]
Same here. I see only Get methods for catalogProductRepositoryV1 in:

{baseurl}/soap/default?wsdl&services=catalogProductRepositoryV1

I confirm that it seems to be a 2.1 problem, with 2.07 i see all methods.

**Comment by magento-engcom-team** [comment]
@AirmanAJK, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
