### ISSUE TITLE
Magento 2.0.7 - Newsletter Email not sent out

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#5898]
### Preconditions
1. Magento 2.0.7
### Steps to reproduce
1. Setup the newsletter queue and wait for the cron job to sent out the newsletter.
### Expected result
1. Newsletter is sent out.
### Actual result
1. Newsletter are not sent out.

In the cron_schedule table, I can see newsletter_send_all task is schedule, but with messages: 

**Validation error: {"message":{"from_email":"An email address must contain a single @"}}**

I am really sure that my email is valid and not missing any @ sign. Please help.

**Comment by andimov** [comment]
@dexteritycc 
Could you please provide more information?
What settings do you have for a newsletter? Maybe some other settings.

**Comment by oserediuk** [comment]
Hello @dexteritycc ! Looks like this is problem with your email sending server. Could you check?

**Comment by dexterityzx** [comment]
Hello,

Only the newsletter is not working. The transactional email, subscription email are working.

Here is my setting for newsletter,
![capture](https://cloud.githubusercontent.com/assets/13892193/17409227/45442bfe-5a3c-11e6-8afe-6c084e1709a4.PNG)

**Comment by sevos1984** [comment]
Not reproducible for me. Check all of your customer emails, maybe one them is incorrect?

**Comment by dexterityzx** [comment]
We solved the issue by installing  SMTP extensions.

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by yogeshraghav-dev** [comment]
iam also facing same issue.kindly help

**Comment by hostep** [comment]
Looks like this was recently fixed by https://github.com/magento/magento2/pull/6354

**Comment by yogeshraghav-dev** [comment]
like how its been fixed and how cna i check?

**Comment by hostep** [comment]
Well, the Pull Request was accepted, so this fix is now in the develop branch. I hope this change will be included in Magento 2.2 and it might get backported to 2.0.x and 2.1.x, but that's up to Magento to decide this.
