### ISSUE TITLE
Route listing command/debugger

### ISSUE THREAD

**Issue by nickmarx12345678** [magento/magento2#5899]
I've encountered repeated difficulty creating and debugging new routes on custom modules, especially as a newcomer to Magento and Magento 2, where documentation is very limited. 

One example of problems faced was deciphering the url matching scheme, especially for adminhtml routes, because of the number of problems thats can cause a redirect to the homepage with no logging or feedback to revise from.

It would save significant amounts of time for new developers if you were to include sort of route listing command with the standard codebase. This might include:

A mapping of urls to what Magento thinks is their action controller (similar to Ruby on Rails `rake routes` command). I made the quickest progress when I finally went into the `Base` router and started printing `$this->actions` during the request flow and dieing.

`adminhtml/somecontroller/someaction => \Company\Module\Controllers\Adminhtml\Somecontroller\Someaction`

Further, I would highly suggest not swallowing, but logging errors that cause a route to redirect to `*/*`. I've run into several issues when setting up pages that would've been quickly solved by logging the issue, but instead were hidden and found via process of elimination

**Comment by andimov** [comment]
@nickmarx12345678 
Thanks for reporting this issue!

To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by oserediuk** [comment]
Hello @nickmarx12345678 ! Looks like this is problem with your email sending server. Could you check?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
