### ISSUE TITLE
Can not save attribute

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5907]
### Preconditions

1. Magento v2.1
2. PHP 5.6.14
3. MySQL 5.6.31-77.0-log Percona Server 
### Steps to reproduce

1. Add options an dropdown attribute which is used in configurable products or change any other storefront options
2. Save
3. It says saved.
### Expected result

1. Attribute options added
### Actual result

1. Nothing changed

**Comment by cizgidekiadam** [comment]
An addition, trying save adding empty option rows. If i try three times save (even adding option or not) at last refresh, seems like here: http://prntscr.com/bzhgi0

**Comment by SerhiyShkolyarenko** [comment]
Hi @rbostan! Sorry, I cannot understand that steps to reproduce.
If you update attributes on backend, please, clarify the sequence of forms you fill and controls used.
If you send REST requests, please clarify the address and payload(data) utilized. Please look at #5963, it seems similar to yours issue.

**Comment by cizgidekiadam** [comment]
I'm adding via backend. For example, create a 'dimension' attribute and add some options (about 800 :)

After a time, if you try adding new options or changing storefront options (ex. Use in layered nav) it says 'saved' but actually not. Also it reset storefront properties to default values.

**Comment by SerhiyShkolyarenko** [comment]
Managed to reproduce with 248 options :)
Created internal issue MAGETWO-58966. Thank you for reporting!

**Comment by cizgidekiadam** [comment]
No needs to thanks. That's what i do ;)

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-58966 to track progress on the issue.

**Comment by chingulito** [comment]
Magento 2.2.2
I am facing same situation Added Attribute brand
 - Does not save the attributes
- Does not index them
- Does not save the Store Front conditions either like stated by  OP
SSH
Cleaned, Flushed, forced  permissions /var and /pub and ownership, aldo index them
No luck

have anyone resolved this?
Thank you

**Comment by rogan-son** [comment]
We experienced same error in v2.1.5. and had fixed this problem after updating a value in PHP configuration as below.

```
; How many GET/POST/COOKIE input variables may be accepted
max_input_vars = 10000

```

https://magento.stackexchange.com/questions/215308/php-max-input-vars-prevents-attribute-options-saving-in-m2?rq=1

**Comment by leoquijano** [comment]
I was having the same issue in v2.2.4, and the fix by @rogan-son fixed it for me.

This is more of a server configuration issue, but maybe Magento could present a warning to the admin. This is especially critical for those of us who are importing attribute option values from external data sources. If many values are configured, any administrator that goes in to update an attribute, could break the other options.

**Comment by aasim110** [comment]
Getting issue in Magento 2.2.3
facing same situation Added Attribute Size with 1300 options

    Not able to save attributes
    Also tried @rogan-son's fix but its not working for me.
    Cleaned, Flushed, forced permissions /var and /pub and ownership, also index them
    Still No luck

have anyone resolved this?
Thank you

**Comment by lennartbee** [comment]
I had to use @rogan-son solution with a bigger number 

> PHP Warning:  Unknown: Input variables exceeded 10000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0

**Comment by magento-engcom-team** [comment]
Hi @rbostan 

Fix for this issue is expected to be delivered with the patch 2.2.6. Meanwhile this commit may be sued as a reference: 3845d9d34636c3c2604887e103e2034d082bdc50

Thank you
