### ISSUE TITLE
Error: Call to a member function getValues() on null (adminhtml event - adminhtml_block_salesrule_actions_prepareform)

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#5909]
In Magento 2.1, `adminhtml_block_salesrule_actions_prepareform` event is not working

```
<event name="adminhtml_block_salesrule_actions_prepareform">
        <observer name="magepsycho_cartrule_adminhtml_block_salesrule_actions_prepareform" instance="MagePsycho\Cartrule\Observer\AdminhtmlBlockSalesruleActionsPrepareform" />
    </event>
```

which results in

> Error: Call to a member function getValues() on null in app/code/MagePsycho/Cartrule/Observer/AdminhtmlBlockSalesruleActionsPrepareform.php on line 41

This used to work in prior to 2.1 and similar approach in Magento 1 as well.
Have Magento2 team changed the way of injecting custom form fields for Cart Rules?

**Comment by andimov** [comment]
@MagePsycho 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
