### ISSUE TITLE
Product visibility helper column in Category / Product overview

### ISSUE THREAD

**Issue by paales** [magento/magento2#5911]
> I just added 19 products to my category. The frontend doesn't show any products. It would be really helpful to give a hint why a product isn't visible on the shop. (After being a Magento developer for years, I still struggle with such a basic thing..)

In an effort to improve the usability of the system and greatly improve the merchant experience, context aware hints are crucial. Explain what is going on and how should the merchant fix their 'mistakes'.

The idea is to add a visibility-helper-icon to product grids so that it is clear why products aren't shown and suggestions how to fix this.

With this, we can collapse the Visibility, Status and maybe Websites column into one 'Visibility Helper' column (or just an icon behind the name of the product). The visibility helper icon will have a popover with additional information why this is happening:
### Not visible:

Icon: http://fontawesome.io/icon/eye-slash/

Product isn't visible anywhere //one or more applicable
- Product is disabled [Enable Product]
- Inventory is set to 0 [Set inventory] //when the setting is enabled
- Product is set to _Not Visible Individually_ and isn't part of a composite product [Make visible]
- Product is set to _Catalog_ but isn't connected to a visible category
### Limited

The product has limited visibility
- Product is set to _Not Visible Individually_ but part of a composite product.
- Product is set to _Search_ [Set Catalog Search]
- OR Product is set to _Catalog, Search_ but isn't attached to a visible category. [Add Category]
- Product is set to Visibility: Catalog but isn't connected to a visible category [Assign to Category]
### Visible

Conditions:
- The above conditions don't match

Tooltip:
- Gives a link to the category and product view page.
## Questions:
- How are we going to handle store view / website specific values without having huge popovers?
- Might it be a good idea to include salable information as well?

**Comment by pboisvert** [comment]
Thanks for the feature request/improvement.  Will pass to the UX team for review

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-visibility-helper-column-in-Category-Product-overview/idi-p/44695).

**Comment by benvansteenbergen** [comment]
Little late, but hey, maybe still relevant:

This module will give you insights about why/if a product is showing https://github.com/Itonomy/magento2-product-visibillitygrid. Its still work in progress but might help.
