### ISSUE TITLE
\Magento\Quote\Model\QuoteManagement::createEmptyCartForCustomer return not Empty Cart

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#5913]
There is expected to receive an empty Cart (or Quote) due calling "createEmptyCartForCustomer" method. It says the method name. But it's not always true.

### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
1. Call the API method /V1/customers/:customerId/carts
   `<route url="/V1/customers/:customerId/carts" method="POST">
       <service class="Magento\Quote\Api\CartManagementInterface" method="createEmptyCartForCustomer"/>
       <resources>
           <resource ref="Magento_Cart::manage" />
       </resources>
   </route>`
2. Notice response (in my case 2)
![image](https://user-images.githubusercontent.com/51680850/71363629-6523dc00-25a2-11ea-8d32-406775a39790.png)
3. Send request again
4. Check response 

### Expected result (*)
1. The really new empty cart (quote) will be created and returned. All further changes applied to the cart will not impact the customer on the front-end.

### Actual result (*)
1. The method returns current active quote. If you change the cart it will change cart of the logged in customer.
![image](https://user-images.githubusercontent.com/51680850/71363649-74a32500-25a2-11ea-8540-ef9d4cb5c337.png)

**Comment by SerhiyShkolyarenko** [comment]
Sorry Yuriy, that expected result is wrong in case of Magento. Our user has only **one** active cart, if admin resets that cart from API, user will see empty cart on frontend.

**Comment by SerhiyShkolyarenko** [comment]
To create order not impacting current user's cart you may utilize Sales module service:
`<route url="/V1/orders/create" method="PUT">
        <service class="Magento\Sales\Api\OrderRepositoryInterface" method="save"/>
        <resources>
            <resource ref="Magento_Sales::sales" />
        </resources>
    </route>
`
It requires huge amount of data, but creates order in one step.

**Comment by SerhiyShkolyarenko** [comment]
Created internal issue MAGETWO-58190 for updating annotation for createEmptyCartForCustomer() and creating new service supporting old behavior: create new cart for customer and leave it inactive.
Thank you for the report.

**Comment by duffner** [comment]
@SerhiyShkolyarenko , I believe Yurii to be correct.  The intent of this method is to return a quote from the "quote" table with the column "is_active" boolean set to "0".  Preparing a quote object for conversion to a transaction via API or other external methods should be able to bypass the current active session. This is a feature of Magento 1, and all Magento 1 features were to be included with Magento 2 this is not an annotation issue, this is missing / not completed functionality. @benmarks, I'd like to involve you in this issue / broken / missing feature.  This is a major issue for any customers who want to be able to create an order for a customer, without deleting their existing cart, I'm hoping you can see that this major Enterprise feature is not lost in Magento 2.

**Comment by duffner** [comment]
@SerhiyShkolyarenko, I am aware of the `<route url="/V1/orders/create" method="PUT"> <service class="Magento\Sales\Api\OrderRepositoryInterface" method="save"/> <resources> <resource ref="Magento_Sales::sales" /> </resources> </route>` However, creating an order directly doesn't always make sense as you may need to manipulate the object prior to an order.

**Comment by SerhiyShkolyarenko** [comment]
@duffner thank you for explanation. In Magento 1 that was undocumented feature and in services we lost it. Now we promoted priority of MAGETWO-58190 in order to restore that lost feature and fix our docs.

**Comment by duffner** [comment]
@SerhiyShkolyarenko thank you!!

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.
We've created internal ticket(s) MAGETWO-58190 to track progress on the issue.

**Comment by duffner** [comment]
@magento-engcom-team, has there been any updates on the status of resolving the core issue?

**Comment by duffner** [comment]
Team, a couple more months have passed and years since the original issue.  This is a critical issue for any extension writers who want to work with the Magento cart for marketing reasons.

**Comment by bydrei** [comment]
@duffner do you currently have any work around for this?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30045` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mmihalev** [comment]
So ... 4 years later issue is still open? Is this serious? Come on guys ....

**Comment by duffner** [comment]
Team, 
This is still a valid issue.  While I understand it's stale, it's still wrong :)

**Comment by ytorbyk** [comment]
What activity is required here? Please, work on it.

**Comment by duffner** [comment]
Just because I'm thinking about a 7 year old issue, maybe I should see if it can get some love :)
