### ISSUE TITLE
Magento 2.1 transactional email uploaded logo not showing in admin.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5916]
**In Magento 2.1**  when I upload a logo in admin , After a save image, it is not showing there.

I have upload logo in admin below path and after a save date, showing no image icon.

`Admin > Content > Design > Configuration > Edit any record -> Transactional Emails`

When inspect element is showing 

> /pub/media/email/logo/stores/1/email_logo.png

 but currently email logo saved in directory 

> /pub/media/logo/websites/1/email_logo.png

how to fixed it.

**Comment by hostep** [comment]
This has reported a couple of times before, so please first try searching for an issue instead of creating a new one :)

Duplicate: https://github.com/magento/magento2/issues/5352 (has been fixed on the develop branch and will probably be released in an upcoming update I hope)

**Comment by oserediuk** [comment]
Hello @hiteshvaghasiya83 ! I closed this one as a duplicate. Free to reopen if you have any additional questions about theme selection.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
