### ISSUE TITLE
getLastViewedUrl() always returns null

### ISSUE THREAD

**Issue by alexander-kozlyuk-ism** [magento/magento2#5917]
Hi,

I've tried to reuse getLastViewedUrl() method (vendor/magento/module-catalog/Helper/Data.php) and found that it doesn't return last viewed category URL.

Possible fix:
![selection_019](https://cloud.githubusercontent.com/assets/14270279/17581428/7581c246-5fae-11e6-80c7-7c598c463992.png)

Thanks!

**Comment by oserediuk** [comment]
Hello! Please, add your code base version

**Comment by alexander-kozlyuk-ism** [comment]
Hi,
M2 CE 2.1.

**Comment by alexander-kozlyuk-ism** [comment]
Another problem is that getLastViewedUrl() doesn't work with caches enabled.

This also should be fixed. Thanks!

**Comment by oserediuk** [comment]
Hello, @nosferix ! Could you create for another case another one ticket? Please, use this guide https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by alexander-kozlyuk-ism** [comment]
Done, https://github.com/magento/magento2/issues/6047

**Comment by magento-engcom-team** [comment]
Closing, as different ticket was created.
