### ISSUE TITLE
[2.0.7] Configurable Product - Wrong image order when changing swatches

### ISSUE THREAD

**Issue by Hawk30100** [magento/magento2#5918]
When using a configurable product, the image order changes when clicking on swatches.
### Preconditions
1. Magento CE 2.0.7 OR Magento CE 2.0.8
2. PHP 7.0.6
### Steps to reproduce
1. Create Simple Product (necessary workaround to set attribute_set) and fill out informations and upload many images (e.g. 6 images)
2. Create configuration for this simple product and upload many images (e.g. 6 images)
3. Navigate to product on storefront
4. Click on color swatch and click on the same swatch again
5. => image order changed
### Expected result
1. The image order set on admin backend should be the same order shown on storefront.
### Actual result
1. The image order set on admin backend is DIFFERENT compared to the image order on storefront.
#### My procedure (with screenshots):
1. Create simple product and upload images
   ![](https://abload.de/img/bildschirmfoto2016-080dy9j.png)
2. Simple product on storefront:
   ![](https://abload.de/img/bildschirmfoto2016-08jla41.png)
3. Create configuration for this simple product:
   ![](https://abload.de/img/bildschirmfoto2016-08tmzd8.png)
4. Pick one virtual product of this configuration and upload images for this:
   ![](https://abload.de/img/bildschirmfoto2016-080lzpv.png)
5. Configurable Product on storefront:
   ![](https://abload.de/img/bildschirmfoto2016-0841lve.png)
6. Choose specific color:
   ![](https://abload.de/img/bildschirmfoto2016-08q9x69.png)
7. Click on this color again to un-select it
   ![](https://abload.de/img/bildschirmfoto2016-08v6x65.png)
   => Order of images changed! Compare steps 5 and 7
#### Another example:

Image order of virtual product in configurable product is different in backend and frontend:

Backend:
![](https://abload.de/img/bildschirmfoto2016-08o8xww.png)

Frontend:
![](https://abload.de/img/bildschirmfoto2016-08mxlef.png)

In this example it is not necessary to change colors or other options. The order of a specific virtual / simple product in configurable product is wrong.

We tried to clean cache, image cache, etc... but nothing helped.

**Comment by Hawk30100** [comment]
Do you need any further information from me? We would like to get this working as soon as possible on our website :)  

Some of our customers told us that they are very confused about the image order, especially on mobile devices when they only have bullet points indicating the number of images instead of an overall view of all images.

Thanks.

**Comment by Hawk30100** [comment]
We upgraded version CE 2.0.7 to CE 2.0.8 and the problem is still there.

It seems like the problem only occurs when adding or reordering images of an existing image set. (Simple Product in Configurable Product!)

Steps to reproduce (adding):
1) Create configurable product X with images and save: A B C D E
2) Add simple product Z with images and save: A B C D E
3) Add new image to product Z and move it to correct position and save. Backend showing: A B **F** C D E
4) Frontend displays: A B C D E **F**  (images are added at the end, regardless of the order)
=> So the added image is always added at the last position of the image set.

Steps to reproduce (reordering):
1) Create configurable product X with images and save: A B C D E
2) Add simple product Z with images and save: A B C D E
3) Rearrange image order of product Z and save: E D C B A
4) Frontend will show: A B C D E    (OR!  E A B C D if you set E as base image)
=> So the reorder doesn't do anything. It has no effect.

So if you use a simple product in configurable product the problem occurs.
If you display the same simple product you use in configurable product alone (e.g. direct url link to product) then the correct image order is shown.

Workaround for us:
If new images should be added or the image order should be changed of a simple product used in configurable product:
1) Delete all images of simple product
2) Upload all images in the exact order you want to display them. (If you uploaded accidentally a wrong image, better start again with step 1)

Hopefully this will help you to identify the problem faster :)

**Comment by Hawk30100** [comment]
I just installed a fresh Magento 2.1.1 on our development environment. The problem seems to be solved in 2.1.1.

**Comment by veloraven** [comment]
@Hawk30100 thank you for your update.
I'm closing this issue as it was resolved.
If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by rakeshvarma90** [comment]
I am facing same problem in magento 2.2.7

**Comment by rakeshvarma90** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @rkvarma19. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rkvarma19, here is your [Magento instance](https://i-5918-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-5918-2-2-7.instances.magento-community.engineering/admin](https://i-5918-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rakeshvarma90** [comment]
I have checked in your given instance and I confirmed that this issue is still in 2.2.7.
Check this product.
https://i-5918-2-2-7.instances.magento-community.engineering/swatch-issue.html

**Comment by mzenner1** [comment]
I have also confirmed that this is broken in 2.2.7
