### ISSUE TITLE
Category ID's

### ISSUE THREAD

**Issue by Arkyden** [magento/magento2#5919]
Hi,

In Magento 2.1 Category ID's on Category Pages have been removed :+1: wasn't sure if it was intentional but some people need this for various reasons and many people dont have time to access the database ever time they need to know the id for a certain category :)

**Comment by Hawk30100** [comment]
+1

Instead of looking for id in database you could do:
Admin Backend -> Products -> Categories; choose a category; have a look at the end of the URL
example: https://domain.com/admin_83k87ndm/catalog/category/index/key/3520cd00d234123ea994856a0ba25f47f2cf47abddfff194123b4b9e944083e7c/id/17/

**Comment by Arkyden** [comment]
Hi,

Yeah just realised this as I was looking around.

Thanks for the help anyways :+1:
