### ISSUE TITLE
Module name pattern

### ISSUE THREAD

**Issue by tim-bezhashvyly** [magento/magento2#592]
Currently according to `Magento/Framework/Module/etc/module.xsd` the pattern for module name is the following:

```
 [A-Z]+[a-z0-9]{1,}_[A-Z]+[A-Z0-9a-z]{1,}
```

Which means neither package name nor module name can not contain from caps only or even have a camel case. Is there any reason for this?

**Comment by ashwani-dlt** [comment]
I have a module name which does not work during DI and other function calls like controller & actions.

Module Name: **ABCDElephant**

This does not give any error instead it just doesn't work properly like other modules
And due to this issue I had to rename it to **Abcd**
