### ISSUE TITLE
Media attributes scope settings (use default)

### ISSUE THREAD

**Issue by Corefix** [magento/magento2#5920]
### Preconditions

1. Magento 2.1
### Steps to reproduce

1. Go to Admin
2. Go to Products > Catalog 
3. Select a Product
4. Go to Images And Videos
5. From here their is no way setting use default for images
### Expected result

1. Their should be a use default for images, otherwise it is hard for admins to see if an image is associated on store view or not. 
### Actual result

1. No use default settings or anyway to determine this.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Media-attributes-scope-settings-use-default/idi-p/44688).
