### ISSUE TITLE
Javascript workflow is way too slow

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#5921]
When rewriting or adding new javascript files work in them is way too slow. After each change I have to delete var and pub static folders and then run setup:static-content:deploy to see my changes in frontend. This results in a lot of time wasted for waiting when static content deployment finishes.
### Steps to reproduce
1.  add new javascript file in custom theme folder or rewrite existing
2.  edit file and reload browser
### Expected result
1. Your changes should be visible right away when working with disabled cache and in development mode
### Actual result
1. magento serves previously generated file. to be able to see your changes you have to delete var and pub/static folders and perform full static content deployment which takes a lot of time compared to just reloading web browser.

This is a huge issue in development workflow by slowing down developers and making development process almost unusable. For me this process takes about 4 minutes, 4 minutes is way too long for 1 iteration in debuging, changing, adding content to javascript files.

**Comment by anton-huz** [comment]
@kandrejevs please describe how you install Magento.

**Comment by kandrejevs** [comment]
I install magento via composer.

the environment is OS X with nginx/php7/mysql installed from brew

**Comment by anton-huz** [comment]
Common workflow with Magento in _Default_, _Developer_ modes:
1. You add a JavaScript file
2. You make a request from the page: in any way. Magento will create symlink to real file.

That's all.

When you need to edit file:
1. Make changes.
2. Refresh page (or do direct request from browser).

That's all.  
Your experience is unusual. So I'm trying to understand where is a pitfall.

**Comment by kandrejevs** [comment]
Thanks, this resolved issue with editing files, I was not aware magento creates simlinks only if you delete pub/static and refresh page without static content deployment.

what happens if I change requirejs-config.js? I have to delete pub/static and refresh page?

**Comment by vkorotun** [comment]
Unfortunately in this case you need manually wipe out pub/static/_requirejs directory only, but not entire pub/static directory!
There is a related internal ticket: MAGETWO-53822 to address the issue with necessaty of manual cleaning of '_requirejs' directory, so after it will be executed in developer/default modes developer experience will become even better.

**Comment by travisdetert** [comment]
I'm currently deploying static content with 13 themes enabled.  Can anyone explain why it's even remotely possible that this can take over an hour?  This is absolute insanity.

**Comment by ishakhsuvarov** [comment]
Hi @kandrejevs 
From the comments it looks like described problem is solved and this ticket is inactive now.
We are closing the report now.
Please reopen if you still have any problems with this.

Thank you for collaboration
