### ISSUE TITLE
missing sales_invoice_grid.base_grand_total in upgradeschema to 2.1

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#5922]
Column isn't in CE 2.0.8 in magento sale installscheme.php
But is in CE 2.1 in magento sale installscheme.php

It is missing in upgradescheme.php to 2.1 and it fails when creating any invoice from order in admin.

**Comment by andimov** [comment]
@magexo 
Thanks for reporting.
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by krejcif** [comment]
### Preconditions




1. CE or EE 2.0.8

### Steps to reproduce


1. upgrade to 2.1
2. create invoice from order in admin 

### Expected result


1. invoice should be created

### Actual result


1. It says: "We can't save the invoice right now"  - http://prnt.sc/by6suo  



Fix upgradescheme to 2.1

**Comment by kitsor** [comment]
#4785

**Comment by andimov** [comment]
@magexo
Thank you! But this is a duplicate issue. I'm closing this one.
Bug with base_grand_total was fixed and delivered to develop branch.
