### ISSUE TITLE
2.1 upgrade from 2.07 customer group can not be updated

### ISSUE THREAD

**Issue by flnative** [magento/magento2#5925]
### Steps to reproduce
1. Create a new customer in 2.07
2. Upgrade to 2.1
3. Create a new customer group 
   3b. Update the existing customer to the new group
4. Create new customer in 2.1
5. Change that customer to another customer group.
### Expected result
1. Any existing customer in 2.07 should be able to update to new customer group in 2.1
### Actual result
1. Customer who were setup in 2.07 could not updated to a new customer group in 2.1
2. Customers who were created in 2.1 could be updated to a new customer group.
3. Note: I never tried updating an existing customer in 2.07 to a new group.

Notes from my host provider:
I've reviewed the two customers on the database, and there are some differences between the two, however, when changing both of them to a different group, I am able to replicate the issue with only the user that I did not create.  These changes made the test user have a group ID change from 1 to 2 when switching from General to Wholesale, while the other customer remained at 1.

Manually changing this database value to 2 had no effect on the customer in the backend.  Additionally, there are a number of differences by default between the two users.  The user that existed before the update has a variety of columns populated with content that the new user does not, such as a password hash and gender.  You can see this yourself in the customer_entity table.

This definitely appears to be an issue only with the user that existed before the update.

**Comment by miakusha** [comment]
Hi @flnative, I cannot reproduce this issue. We need more information about your configuration

**Comment by flnative** [comment]
I have since updated to 2.1.1 and I still have this issue. Tell me what information you need. I can provide access to the admin if need be.

**Comment by sevos1984** [comment]
Have you run customer grid index after upgrade?

**Comment by slavvka** [comment]
Closed since there no reply.

**Comment by flnative** [comment]
Please reopen. I cannot edit any customer group. I try to change from General to wholesale or retail and the system says saved but the value is still the same. This is new customers created after the upgrade. I now have 2.1.2 installed. Previously, it was just the customers that were created in 2.0 that I could not edit and save. Now it is anything cannot be edit saved.

I use Nexcess shared hosting plan. 

Is this a simple permissions issue or something?

**Comment by flnative** [comment]
I did run reindex on the terminal for all indexes... Still cannot change customer group.

Please note that two indexes did NOT re-index when checking status in the admin back-end as they show old status dates - (Product Categories and catalog Product Rule); the rest showed today's date.

Command: php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
**Product Categories index has been rebuilt successfully in 00:00:00**
Product Price index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
**Catalog Product Rule index has been rebuilt successfully in 00:00:00**

**Comment by flnative** [comment]
Here is the issue and it resolved for me. This sounds like a bug to me. "Solved! I had to tick the 'Disable Automatic Group Change Based on VAT ID' box under customer group dropdown under the Account Information tab when you edit a particular customer's information."

http://stackoverflow.com/questions/23255545/magento-ce-customer-groups-changing-not-saving
