### ISSUE TITLE
Unable to change the product type if added wrong type

### ISSUE THREAD

**Issue by chandanbhanopa** [magento/magento2#5926]
### Preconditions

1. I have created a product , by mistake it product was created in Virtual category, now I went to product catalogue and click on edit link for that product, but not able to change the  product category. 
   2
### Steps to reproduce

1. Create a simple product.
2. Edit the product and try to change it to simple to virtual product or any other type.
### Expected result

1. I did not fine anything on product edit page for changing the category type like Simple product --> Virtual product
### Actual result

1. [Screenshot, logs]

**Comment by antboiko** [comment]
Hi @chandanbhanopa , you can change product type from Simple to Virtual and vice versa using an option "This item has weight" for Simple product type/"This item has no weight" for Virtual.

I'm closing this ticket as it's not a technical issue. Please feel free to reopen or create a new one if you have some technical issue.

Thanks,
Anton.
