### ISSUE TITLE
Notifications issues

### ISSUE THREAD

**Issue by pradeepsparx** [magento/magento2#5932]
When we register or compare production 

notifications of that event comes after 5 or 10 minutes

Please see this http://awesomescreenshot.com/0ca62bfw4f

**Comment by veloraven** [comment]
@pradeepsparx thank you for your report.
Please provide description according to the template: with steps, actual result and expected result. 
Please also provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
@pradeepsparx 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
