### ISSUE TITLE
Custom options for product can't have a floating price

### ISSUE THREAD

**Issue by arthursp** [magento/magento2#5933]
### Preconditions
1. Magento 2.1 CE withtout sample data is installed
2. Virtual product is created
### Steps to reproduce
1. Add an custom option to a product with a floating price ( ex: 13,74 )
2. Edit this option and look a the price
### Expected result
1. The price need to be floating
### Actual result
1. rounded to inferior integer

**Comment by dthampy** [comment]
Internal jira ticket - MAGETWO-56352 has been created for this issue

**Comment by SilvanLaroo** [comment]
What is the status of this issue? We also face this issue on Magento 2.1.5.

**Comment by thlassche** [comment]
I'm facing this too. When will this be fixed?

**Comment by magento-engcom-team** [comment]
@arthursp, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
