### ISSUE TITLE
Untranslatable string "Sorry, but something went wrong. Please contact the seller."

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#5934]
### Preconditions

Version: _Magento 2.1_
### Steps to reproduce

1. Enter wrong card number in _Authorize.net_ payment method.
### Expected result

1. The message _Sorry, but something went wrong. Please contact the seller._ should be translatable, but is not - no such string was generated with _magento i18n:collect-phrases_  tool
### Actual result

![capture](https://cloud.githubusercontent.com/assets/282687/17327844/a5e3bafc-58ba-11e6-823d-c4e6c4555b52.JPG)

**Comment by YevSent** [comment]
Hi, @jernejh, thanks for reporting.
Created internal ticket MAGETWO-56345.

**Comment by nagrgk** [comment]
is this fixed ? are we fixing it soon ?

**Comment by YevSent** [comment]
Hi, @nagrgk, this issue didn't fix yet and will be fixed according to issue rank and priority (now, it has not critical priority).

**Comment by nagrgk** [comment]
Guys its critical. Payment not working and its not critical? Are you kidding? Magento is big joke now.

**Comment by YevSent** [comment]
@nagrgk, how translation affects place order action via Authorize.net payment?

**Comment by alena-marchenko** [comment]
Hi @jernejh 

Fix for MAGETWO-56345 tickets is merged to develop branch, closing the issue.
Thank you.
