### ISSUE TITLE
Cart page not showing any item and summary

### ISSUE THREAD

**Issue by Nehace40** [magento/magento2#5935]
After Migration 2.0.7 to 2.1.0 My cart page is not showing any items.

Its only display title of cart and summary and in console i check that any of cart phtml is not loading 

How to solve?

**Comment by veloraven** [comment]
@MagentoTest1111 thank you for your report, it's a known issue. Please clean all your browser's cache.
To avoid the same issue in future you can turn on the following option in admin area: 
_Stores -> Configuration -> Advanced -> Developer -> Static Files Settings -> **Sign Static Files = Yes**_

**Comment by andimov** [comment]
@Nehace40 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
