### ISSUE TITLE
Magento 2 - discount bases on Payment Method does not work?

### ISSUE THREAD

**Issue by vigoss-ru** [magento/magento2#5937]
## **Preconditions:**
1. Have Magento 2.1.
2. Install the sample data
3. I go to Magento 2 Admin > Marketing > Promotions > Cart Price Rules and create a new Rule: Bank Transfer Payment.
## **Steps to reproduce**
- Tab Rule Information:
  Rule Name: Bank Transfer Payment
  Status: Active
  Websites: Main Website
  Customer Groups: select all
  Coupon: No Coupon
  Uses per Customer: 0
  From: blank
  To: blank
  Priority: 0
  Public in RSS Feed: No
- Conditions tab:
  If ALL of these conditions are TRUE :
  Payment Method is Bank Transfer Payment
- Actions Tab:
  Apply: percent of product price discount
  Discount Amount: 2
  Maximum Qty Discount is Applied To: 0
  Discount Qty Step (Buy X): 0
  Apply to Shipping Amount: No
  Discard subsequent rules: No
  Free Shipping: No
  Apply the rule only to cart items matching the following conditions (leave blank for all items): nothing

Then I enable Bank Transfer Payment method, go to checkout page
## **Expected result**
- When click on option Bank Transfer Payment, Discount Price should show up in Order Summary
## **Actual result**
- click on Bank Transfer Payment but the Discount Percent Price does not show up in Order Summary.

![4](https://cloud.githubusercontent.com/assets/2011139/17329404/c92cd75c-58c2-11e6-81d1-2bc829c897eb.png)

Please give me an advice. How can make a discount on payment method on Magento 2. For Magento 1, it works well.

Thanks very much

**Comment by cizgidekiadam** [comment]
This issue seems resolved. 
http://magento.stackexchange.com/questions/128580/magento-2-discount-depend-on-payment-method-does-not-work

**Comment by DJ0815** [comment]
@rbostan it is not a 100% solution, it only works with a single domain.
I have a multi store with multidomains, www.domain.de, www.domain.com ....

when i try to checkout at www.domin.com (which is the standard domain) everything is working great, but when i try to checkout at www.domain.de i get the following script error:

`XMLHttpRequest cannot load http://www.domain.com/mycart_updatepayment/checkout/applyPaymentMethod/?SID=52ad6cea0d0b55534a3817a0209639c2. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.domain.de' is therefore not allowed access.`

The error is quite logical, but how can i avoid loading the script from standard domain? Any help would be apreciated. Thanks in advance.

**Comment by cizgidekiadam** [comment]
@DJ0815,
 in server headers, you may set allowed origins something like that:

For apache, you should add to <IfModule mod_headers.c> section in .htaccess file
<pre>
SetEnvIf Origin "http(s)?://(www\.)?(domain.com|domain.de)$" AccessControlAllowOrigin=$0
Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
</pre>
ref: [https://stackoverflow.com/a/1850482](https://stackoverflow.com/a/1850482)

For nginx:
<pre>
location /{
    # this will echo back the origin header
    if ($http_origin ~ "domain.de$") {
        add_header "Access-Control-Allow-Origin" $http_origin;
    }
}
</pre>
ref: https://stackoverflow.com/a/12414239

**Comment by DJ0815** [comment]
Thanks for your fast reply, but i still get the error:

> Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.

For me with my bad english it sounds like, that there has been a disallowance before?

**Comment by cizgidekiadam** [comment]
@DJ0815 we all not Englishman, so could not be perfect in speaking :) 
We are Magento people in here. It is fine with your English. 

As in https://stackoverflow.com/a/40193633 , you should add more headers to be working.

For example apache
<pre>
Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
</pre>

And nginx of course
<pre>
add_header "Origin, X-Requested-With, Content-Type, Accept";
</pre>

But i suggest that, you should do more research about headers. That headers usage might be dependent on your configuration/situation. It may be insecurable or unexpected behaviours for you.

**Comment by DJ0815** [comment]
It's getting more curious (for me). As i thought i had set all headers correctly, i have changed all webistes to the same domain, so I could exclude this problem.

But the Disount still was updated only at the default website, although you could see that the price was reloaded on checkout page on all websites.

- The cart price rule is activated for all websites and all customer groups.
- When i change the default website at Store->All Stores , the dicsount is working only for the new default webiste
- All other cart price rules (which are activated in the cart) work as expected.

**Comment by mukdam** [comment]
Getting the same issue when we create for specifying payment method Magento, not recalculated rule which created in backend.

But know I am using http://magento.stackexchange.com/questions/128580/magento-2-discount-depend-on-payment-method-does-not-work but this not Magento Specified solution

**Comment by oleg-onufer** [comment]
Hi @vigoss-ru.
Thanks for reporting this issue.
Internal ticket MAGETWO-70501 was created.

**Comment by keinereiner** [comment]
this issue is more than one year old and still not fixed... many other issues too.... why??? because of so many not fixed issues, we have many trouble with our clients.

**Comment by EvanRijn** [comment]
In 2.1.8 the option is also not available in backend of magento.

**Comment by magento-engcom-team** [comment]
@vigoss-ru, thank you for your report.
We've created internal ticket(s) MAGETWO-70501, MAGETWO-81449 to track progress on the issue.

**Comment by NikZh** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@NikZh thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@NikZh Thank you for investigating.

@vigoss-ru thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by shansari25** [comment]
any solution so far

**Comment by HendyIvan** [comment]
how about this issues? its happens on magento 2.3.0

**Comment by dbashyal** [comment]
![sales_rule](https://user-images.githubusercontent.com/833986/61345631-4d308980-a899-11e9-9388-6479d65ae31b.jpg)

Unable to create sales (cart price) rule as value of payment options is blank.
