### ISSUE TITLE
Paypal checkout not possible with products that have custom options

### ISSUE THREAD

**Issue by mktudock** [magento/magento2#5938]
### Preconditions
1. Have Magento 2.1. (with PHP 7)
2. Install the sample data and create a new store view
3. Go to any (configurable) product and create a custom option as a dropdown with some options (for global)
### Steps to reproduce

1. Go to checkout with that product in cart, checkout with Amazon
### Expected result
1. The order gets created
### Actual result

1. An error message tells us that the order couldn't be created.

Due to a missing check in getOptionById of the Product model (removed in 0f0063045b50e1dafa260b97a1a00bf9fa92e74b), the product model tries to iterate over null when trying to create the order, because getOptions() returns null.

Seriously, how did you screw up custom options so badly in 2.1.? They are not functional at all!

**Comment by commcad** [comment]
+1

Having the same issue here with 2.1.0GA.
- Configurable product with swatches + any custom options as a dropdown
- Paypal checkout > error order couldn't be created

Works fine for Simple product with the custom options only (no swatches). Custom options onto Configurable Products (with swatches) fails big time however. Unfortunate

Workaround "until a fix" is to kill the swatches and only use the custom options. Meaning you have to create an individual product for each configurations. That's a lot in our case :/

**Comment by mktudock** [comment]
You can also install the following plugin, which restores the check:

``` php
namespace Vendor\Module\Plugin;

class ProductPlugin
{
    public function aroundGetOptionById(
        \Magento\Catalog\Model\Product $subject,
        callable $proceed,
        $option
    ) {
        if ($subject->getOptions() == null) {
            return null;
        }

        return $proceed($option);
    }
}
```

di.xml:

``` xml
    <type name="Magento\Catalog\Model\Product">
        <plugin name="prevent-empty-array" type="Vendor\Module\Plugin\ProductPlugin" sortOrder="10"/>
    </type>
```

**Comment by commcad** [comment]
Sweet man, I appreciate this.

Is this how you get around the custom options 'cannot create order' error?

Not at the shell PC atm but will be in a few hours. I'll give it a go.

**Comment by mktudock** [comment]
@commcad Yes, after debugging we found out that was what caused the issue. In 2.0.7. the method worked differently and pretty much did what the plugin does now.

**Comment by commcad** [comment]
too kind bud, sure many could do with a temp fix. 

Silly question (to you); do we need to create a whole new custom module for this to work or it needs amending code somewhere. If so which *.php your code needs pasting into? Same question RE the di.xml - amending required? where

Sure a few others who will soon experience this bug will feel like asking, but won't dare lolll

**Comment by mktudock** [comment]
Afaik you need to place this in a module (or the global shop di.xml).

The di.xml is placed in %module%/etc/di.xml and it's structure is described here http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html

You can also use the global shop di.xml under %shop%/app/etc/di.xml, but you have to place the class I posted above somewhere where the shop can find it...

I didn't try it yet but you might want to try this if you don't want to use a new module:
1. Insert the di.xml bit I posted above into %shop%/app/etc/di.xml - replace the plugin type with "Tudock\Plugins\Product"
2. Create the folder app/code/Tudock/Plugins
3. Place the class I posted above as Product.php in that folder
4. Replace the namespace in that file with Tudock\Plugins
5. Remove the var/di and var/generation folders
6. Run bin/magento setup:di:compile

This might work if the autoloading finds the class. Otherwise it's propably easiest to create a new module.

**Comment by commcad** [comment]
Quality Tweaks! Thanks for pointing us in the correct direction. 

I-will-try. Need it badly as this bugs brings little over 100 more products to our catalog here :/ This invasion of thumbnails is terrifying our customer base I've recently heard lollll

Top man, thanks again

**Comment by duhon** [comment]
@mktudock Thanks for reporting this issue.
We've created internal ticket MAGETWO-56695 to fix it.

**Comment by Nerogee** [comment]
+1 @mktudock 

> Seriously, how did you screw up custom options so badly in 2.1.? They are not functional at all!

**Comment by commcad** [comment]
@duhon @mktudock 

Was this bug fix abandoned? Any quick fix available in the meantime? We've failed implementing Mktudock custom module fix, hence why I ask.

Anyone have a link to MAGETWO-56695 so I can compare the code of 2.1.1 to the patched code? maybe this would work?

thanks

**Comment by SerhiyShkolyarenko** [comment]
@mktudock @commcad we delivered MAGETWO-56699 fix to develop branch. Thank you for cooperation.

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko Will MAGETWO-56699 be included in 2.1.3?

**Comment by skiwithpete** [comment]
@mktudock 
Using your instructions I get this error: 
```
php bin/magento setup:di:compile
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 18.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 1 sec 22.0 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 22.0 MiB
Fatal error: Class 'Magento\Eav\Model\Entity\Attribute\Source\Boolean' not found in /home/oneupkey/public_html/vendor/magento/module-catalog/Model/Product/Attribute/Source/Boolean.php on line 14
Segmentation fault
```

**Comment by audexpro** [comment]
News on this issue?

**Comment by benyanke** [comment]
Any luck on this?
