### ISSUE TITLE
Special Price being use instead of Price on Configurable and Simple Products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5939]
We are having an issue on a clients website Magento 2 version 2.0.7

Got a strange issue in Magento 2 on a Configurable Product:

All size 4,5 and 6’s should be £289.00 and have no VAT attached All size 7’s should be 249.167 and have VAT attached

So I’ve se the config as the 4/5/6 price with not VAT and gone into the size 7’s simples and changed the price and clicked None VAT.

However on the front end the price is going funny, it is showing it as a special price ‘was £289.00 now £249.17’ when it should just be showing £289.00 then on the dropdown when you pick a 7 size it should change to £299.00.

I have checked in the back-end and there is no product using special price. Could this be a Magento 2 bug?

**Comment by veloraven** [comment]
@RobertBroley thank you for your report.
Could you please provide description according to the template: with more detailed steps, actual result and expected result?

**Comment by ghost** [comment]
Hello,

We have created a configurable product with simple products attached to it. The price however seems to disappear on the back-end of Magentom on the configurable. Also the price that is being used for some reason is using the special price, rather than just the price. There is nothing in the special price.

Product is: http://www.chelfordfarmsupplies.co.uk/konig-youngster-jump-leather-riding-boots-black

**Comment by oserediuk** [comment]
Hello @RobertBroley ! Could you check does simple product have special price? Also, please, check if the some catalog price rule have been applied to this product?

**Comment by ghost** [comment]
Hi @oserediuk I have checked the Catalog Price rules and that brand is not listed, also the configurable and simple products only use Price. Non of the products use Special Price.
