### ISSUE TITLE
"Something went wrong" when disabling Magento_Review from the backend

### ISSUE THREAD

**Issue by fsspencer** [magento/magento2#5940]
Hello. I've just find out that when you go to the backend and disable the module Magento_Review, flush cache and then you go to edit a Product, you receive the following error:

![screen shot 2016-08-02 at 12 00 08](https://cloud.githubusercontent.com/assets/7492090/17333428/bc2e4794-58a8-11e6-8f74-98c1d21e0897.png)

If you close the alert message, and go to expand the Product Reviews section, it will be loading forever

![screen shot 2016-08-02 at 12 01 03](https://cloud.githubusercontent.com/assets/7492090/17333449/d4e30586-58a8-11e6-833c-0ae143ed60e3.png)

Steps to reproduce:
1. In the Admin panel, go to Stores > Configuration > Advanced > Advanced > Disable Magento_Review
2. Go to Products > Catalog > Open any product to edit
3. Alert message will appear

Expected result: 
- Message shouldn't appear
- Product Reviews section shouldn't appear

Thanks

**Comment by hostep** [comment]
Was already reported over here: https://github.com/magento/magento2/issues/5323

**Comment by andimov** [comment]
@fsspencer 
Thank you for reporting!
This is a duplicate issue. I'm closing this one.
Please, feel free to reopen if you need.

**Comment by hostep** [comment]
@andimov: can you assign a MAGETWO number to #5323, otherwise it will probably never going to be picked up?

**Comment by andimov** [comment]
@hostep 
I will process #5323
