### ISSUE TITLE
The setup "This is only a demo store. You can browse and place orders, but nothing will be processed" is impossible to be removed!

### ISSUE THREAD

**Issue by camilagoetze** [magento/magento2#5944]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@camilagoetze thank you for your report.
Please provide description according to the template: with steps, actual result and expected result described. 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
@camilagoetze 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
