### ISSUE TITLE
tag 2.0.7 doesnt have update directory or required files. 

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#5947]
Seems its missing when I went to setup cron.

**Comment by andimov** [comment]
@dmcmillin 
Thank you for report!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
@dmcmillin 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
