### ISSUE TITLE
Magento Checkout Payment Page Issue

### ISSUE THREAD

**Issue by nikulprajapati** [magento/magento2#5951]
I am using Magento 2 for site. In checkout page giving Below error after Click on Proceed to checkout.
I cant see Payment Method in Cart Page.
## Expected result

1. Getting Below error at the time in console log.

TypeError: value is undefined
    return value.length <= +params;

![payment](https://cloud.githubusercontent.com/assets/4286585/17355813/f1f399ba-5970-11e6-8c37-aa4747dc4701.png)
### Actual result

1. [Screenshot, logs]

**Comment by andimov** [comment]
@nikulprajapati 
Thank you for reporting!
Please, check Magento log files.

**Comment by andimov** [comment]
@nikulprajapati 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
