### ISSUE TITLE
Placing Order doesn't redirect to success page

### ISSUE THREAD

**Issue by nikulprajapati** [magento/magento2#5953]
I have a little problem with placing order button on magento. For some reasons when I complete a order and click "Place Order" it doesn't redirect the page in a success page (or even elsewhere) it just stays in the checkout page with all the products still inside and showing just loading image.

Order should be placed and displayed in admin section but checkout page not redirect to success page.

I have check browser console here i have see below error.

> TypeError: path is undefined
> if (path.indexOf(baseUrl) != -1) {

**Comment by pboisvert** [comment]
@nikulprajapati can you please follow the [submission guidelines](https://github.com/magento/magento2/blob/develop/CONTRIBUTING.md) and provide version and other system information per the template

**Comment by Cacasapo** [comment]
+1 on this with live credit card checkout
In my case:
Magento 2.0.8 upgraded to 2.1
Paypal Payments Pro

Paypal express goes through, but credit card orders just site there after "place order" is pressed.
No errors on console.

Doesn't redirect to success or failure, or create order in system, but debug.log shows:
Paypal syuff Blah blah
  'respmsg' => 'Approved',
    'result_code' => '0',
  ),
) {"is_exception":false} []

More info: Traansactions are showing amt=0 and "Success" even with invalid card data. 
 'amt' => 0,

EDIT: My issue is related to https://github.com/magento/magento2/issues/3509

**Comment by andimov** [comment]
@Cacasapo 
Looks like you have another issue.
Please, create new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by Cacasapo** [comment]
@andimov It's 3509 and the solution is https://github.com/magento/magento2/issues/3509#issuecomment-192383123 , or at least I hope so. Will only be able to test once the site's owner is back from vacation.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one, but follow the [template ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)please

**Comment by ashvinim0003** [comment]
Getting mail from paypal for success payment but order is not created in magento.After success payment customer is not redirecting back to success page.
anyone can suggest any solution ?
