### ISSUE TITLE
Does the select attribute in customer checkout address form support "optgroup"?

### ISSUE THREAD

**Issue by rickyvv** [magento/magento2#5955]
I found the attribute cannot show the sub-options under "optgroup". The array used for testing is 
[
            [
                'label' => 'optgroup 1',
                'value' => [
                    [
                        'label' => 'in opt group 1-1',
                        'value' => 'value 1-1'
                    ],
                    [
                        'label' => 'in opt group 1-2',
                        'value' => 'value 1-2'
                    ],
                    [
                        'label' => 'in opt group 1-3',
                        'value' => 'value 1-3'
                    ],
                ]
            ],
            [
                'label' => 'optgroup 2',
                'value' => [
                    [
                        'label' => 'in opt group 2-1',
                        'value' => 'value 2-1'
                    ],
                    [
                        'label' => 'in opt group 2-2',
                        'value' => 'value 2-2'
                    ],
                    [
                        'label' => 'in opt group 2-3',
                        'value' => 'value 2-3'
                    ],
                ]
            ],
            [
                'label' => 'optgroup 3',
                'value' => [
                    [
                        'label' => 'in opt group 3-1',
                        'value' => 'value 3-1'
                    ],
                    [
                        'label' => 'in opt group 3-2',
                        'value' => 'value 3-2'
                    ],
                    [
                        'label' => 'in opt group 3-3',
                        'value' => 'value 3-3'
                    ],
                ]
            ]
        ]

The above array is in correct format since I tried to use it in another function, and a select menu with "optgroup" displayed correctly.
But when I used the array in checkout address form, the select menu only displayed the "optgroup" but without the sub-options of the "optgroup".
Besides, I found that the class responsible for rendering the select menu is \Magento\Customer\Model\AttributeMetadataConverter , it seems the class does not put the sub-options into the $options[].

**Comment by andimov** [comment]
@rickyvv 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
@rickyvv 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
