### ISSUE TITLE
Untranslatable string "Please enter the same value again."

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#5956]
### Preconditions

Version: _Magento 2.1_
### Steps to reproduce

1. When creating new user account in the storefront, if a user does not enter the same password twice, this untranslatable string occurs.
### Expected result

1. The message _Please enter the same value again._ should be translatable, but is not - no such string was generated with _magento i18n:collect-phrases_  tool
### Actual result

![capture](https://cloud.githubusercontent.com/assets/282687/17357235/11cb2fd8-595c-11e6-9d29-071d140b6ed5.JPG)

**Comment by grasdaggel** [comment]
This bug is existent as early of 2.0.6 and 2.0.4 at least.

**Comment by magento-engcom-team** [comment]
@jernejh, thank you for your report.
We've created internal ticket(s) MAGETWO-80318 to track progress on the issue.

**Comment by Jeroenll** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by dan-advantec** [comment]
Thanks @JeroenVanLeusden - how did you get on with this? It still appears to be an issue in 2.2.0

**Comment by Jeroenll** [comment]
@dan-advantec I see merging of the PR started earlier today. Once merged, it will be released in 2.2.1 or 2.2.2.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81970

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by sadon** [comment]
I've reproduced it in 2.2.2

**Comment by jlnarvaez** [comment]
I can't translate it in Magento 2.2.2

**Comment by LKarklins** [comment]
Reproduced in 2.2.8

**Comment by angelo983** [comment]
Reproduced in 2.1.18

**Comment by zaheerbadi** [comment]
reproduced in 2.4 too
