### ISSUE TITLE
ImportExport override imported values with `Use Import Values`

### ISSUE THREAD

**Issue by paales** [magento/magento2#5958]
> I want to have all product information imported but I want to be able to override the description of a certain product, but the prices and stock should import like normal.

Just like the new core config values, it would be nice to have a scope above the default scope. This would solve the problem that a Merchant needs to overrides the values on each store-view (which is undoable with a Multi Store Setup).

If the Use Import Values is unchecked the Merchant is able to change the value. A new flag gets created in a new `catalog_product_import_export_overrides` (or some other table) table. When importing the system checks this table to skip certain import-values.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/ImportExport-override-imported-values-with-Use-Import-Values/idi-p/44687).
