### ISSUE TITLE
web setup wizard freeze

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5960]
Web setup wizard freeze
- Did an upgrade from 2.0.7 to 2.1
- Didn't go through 100% , got stuck.
- Rollback and did an update from composer on console
- Update success and updated to 2.1v, but inside admin, web setup wizard displays freezed page
- cleared all cache and still it exists.
  attaching an image for reference.
  ![system upgrade - web setup wizard](https://cloud.githubusercontent.com/assets/19605497/17361557/0b113392-5969-11e6-9321-a01964d93bef.png)

**Comment by nmallepally** [comment]
@vkorotun any update on the above issue? Thanks.

**Comment by andimov** [comment]
@nmallepally 
Thank you for reporting!
Try to increase time and memory limits for php, web server and proxy.

**Comment by nmallepally** [comment]
@andimov memory value limit is 2GB and execution time is 18000.
The error occurred during an update to 2.1 from 2.0.7
It showed this error.
But Rolled back and did an update to 2.1 via composer
2.1 was installed successfully, but when clicked on system->web setup wizard-> it shows the above screen
freezed , does not even go to the page showing component manager,system upgrade options page.

**Comment by andimov** [comment]
@nmallepally 
Did you have any errors in browser console?

**Comment by nmallepally** [comment]
@andimov it works now after again cleaning all cache and setup upgrade.
I think it must be some weird cache.  You can close this issue, but error was persisting for quite a number of days irrespective of clearing caches so many times. May be a bad browser cache.

Can you respond this isssues [[production]](https://github.com/magento/magento2/issues/6017) repsond to [translation ](https://github.com/magento/magento2/issues/6022#issuecomment-238235765)

**Comment by lokeshrathore** [comment]
Hi i have face issues on setup wizard in magento 2.3.0 version.
I got this error on network 
Fatal error: Out of memory (allocated 198180864) (tried to allocate 9437184 bytes) in /vendor/composer/composer/src/Composer/Repository/ComposerRepository.php on line 583

Got error in console :
angular.js:533 TypeError: Cannot read property 'responseType' of null
    at successCallback (select-version.js:34)
    at angular.js:6988
    at m.$digest (angular.js:8414)
    at m.$apply (angular.js:8817)
    at l (angular.js:11306)
    at t (angular.js:12295)
    at XMLHttpRequest.A.onload (angular.js:12410) "Possibly unhandled rejection: {}"

Can anyone help me, I have tried to increase memory limit in root folder .htaccess file, But unable to solve this problem
