### ISSUE TITLE
Created configurable product out of an existing product. Can't edit parent product anymore.

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#5964]
### Preconditions

I use magento 2.0.7.
### Steps to reproduce

Installing, creating a simple product. Saving it, then at the bottom add configurations. I added color black, red and green, swatched and mandatory to chose. Then size 34 and 36. Mandatory also.
After that creating products. 6 New products appeared. Then saving the parent product and the child products are seeable in the product list.
After that I needed to edit the description of the parent product. I changed something and saved. Page loaded, content in backend showed the right thing but not the frontend. After some searching I found that the product has not been saved. The error message only was hidden at the top of the page so that I was not aware of it (why can it hide there?). It claimed I have to chose a color and a size.
At the bottom of the description there are both fields where I could chose them. On the right the word global.
### Expected result

I set a color and a size and can save it.
### Actual result

The dropdownboxes for color and size are there... only they are greyed out, have the red star but... I can't change anything there.
![image](https://cloud.githubusercontent.com/assets/12331722/17366611/6f818110-598c-11e6-8aee-3fc3e1575412.png)

Not sure if the image will show up though something happened.

I'm not sure what happens there. I think there should be the default setting be sat. But it does not allow it so I can't edit the parent product anymore. Probably I would have to delete the child products for that to happen but... this is no solution for the editors everytime they have to edit the main product.

Edit: A workaround was to make the attributes non required. Though still...

**Comment by orlangur** [comment]
From business logic perspective configurable product obviously does not have to contain any values for Color and Size.

I remember such bug, so it's either a regression of old problem or was never fixed for 2.0.x.

Could you check it on develop or 2.1? If the fix is present, not sure it's severe enough to be backported to 2.0.x, especially taking into account Product Creation was reworked significantly in 2.1 and most likely would not allow simple patching for 2.0.x.

**Comment by Onkovat** [comment]
Maybe I have to switch to 2.1 anyway because I have alot of trouble with the instalation of 2.0.7. requirejs is not finding the static js files that should have been created by magento, magento does not find a file /pub/media/catalog/productno_selection is not to be found, is not created with deploy and I do not find info about that file on the net at all.
The end result is that alot of normal functions of mage 2 does not work. the minibasket shows nothing so one can't reach the normal basket, the proceed to checkout button has no functionality and and and...

**Comment by orlangur** [comment]
All you described should work fine on 2.0.7 clean installation. There could be some issue with file permissions, cusomizations or incomplete installation process on your instance.

**Comment by Onkovat** [comment]
I would think so too though there are no errors in serverlog nor magento log that could explain it. And when I disable all modules through cli and use blank instead of my theme then the problems still persist.
I thought about creating another installation on the same hosting to see if the problem exists there also but maybe it's best to do this other installation with mage 2.1 from the start. I already searched weeks for the problems with numerours threads everywhere and nobody could help till now. :/ So when it works that way then I will be happy. Hopefully mage 2.1 won't destory my theme. :D

**Comment by veloraven** [comment]
@Onkovat please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. If you describes an issue.
Questions should be posted to a question and answer site, such as [Stack Exchange](https://magento.stackexchange.com/) and the [Magento Forums](https://community.magento.com/), where Magento community members can quickly provide recommendations and advice. As the Magento 2 GitHub repository is used to capture code and documentation issues.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
