### ISSUE TITLE
Catalog navigation menu is not display after upgrading to magento 2.1.0

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#5975]
I upgraded the magento 2.0.4 to 2.1.0 successfully. but now there catalog navigation is missing on front end side. can any one have idea what is the issue ?

**Comment by Ctucker9233** [comment]
@jigar48 I had this exact issue. See #5423 for how to fix it.

**Comment by jigar48** [comment]
I also face the other issue after upgrading to magento 2.1.0. There are Web Section is missing under store->configuration. also when I click on any menu in the back end side that will redirect to dashboard and not working proper.

http://prntscr.com/c1tdnb

@Ctucker9233 I changed the vendor directory with the fresh magento 2.1.0 vendor directory but its not working for me and the nab bar is still not appeard

**Comment by Ctucker9233** [comment]
@jigar48 just to clarify you completely deleted your old vendor directory and reloaded the fresh one?

**Comment by jigar48** [comment]
Yes I replaced with the new vendor directory

**Comment by andimov** [comment]
@jigar48 
Thank you for reporting!
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
@jigar48 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
