### ISSUE TITLE
can't get minicart value (price, qty) in PDP (Product Detail Page)

### ISSUE THREAD

**Issue by ragum** [magento/magento2#5976]
I add an item in minicart and I tried to get minicart value like price and qty in PDP and it show empty, but when I get minicart value in other page except PDP it show the value
anybody can help me how to get minicart value in PDP?
Thanks before

here's my code:
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cartlist = $objectManager->create('\Magento\Checkout\Helper\Cart')->getQuote()->getAllItems();
?>
<?php
    foreach ($cartlist as $item) {
        $productSku      = $item->getSku();
        $productQty     = explode(".",$item->getQty());
        $productPrice   = explode(".",$item->getPrice());
        $itemCart[]        = "{item: "."'".$productSku."'".", "."price: ".$productPrice[0].", "."quantity: ".$productQty[0]."}";
        $newitemCart       = implode(", ",$itemCart);
    }  
?>

**Comment by grasdaggel** [comment]
Ask your question on Stackexchange, there you will get most likely an answer.

**Comment by andimov** [comment]
@ragum
Thank you for reporting!
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
@ragum 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
