### ISSUE TITLE
New registration account confirmation link sets "back url" to checkout-cart page

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5981]
### Preconditions
1.  Mage2.0.6
### Steps to reproduce

1.  Register new account via Startpage of Mage Shop
2. Register and click on the link in the E-Mail
### Expected result

1. The customer gets sent to the startpage 
### Actual result

1. the customer gets redirected to %2Fcheckout%2Findex%2Findex%2F&id=8&key=XXXXXXXXXXXXXXXXXXXXXXXXXX

The E-Mail Template contains this string:

```
<a href="{{var this.getUrl($store,'customer/account/confirm/',[_query:[id:$customer.id,key:$customer.confirmation,back_url:$back_url],_nosid:1])}}" target="_blank">{{trans "Confirm Your Account"}}</a>
```

I'd expect Magento to send a URL without parameters (in this case: back_url), instead it sends the Cart, which is wrong. When a user registers himself with password, the only logical site to redirect him is the account index page. Doesn't seem to be intentional this way.

**Comment by sevos1984** [comment]
Could you try upgrading to latest release version?

**Comment by grasdaggel** [comment]
I could, but the customer doesn't allow it, so basically we are stuck on that. Or short: no. :(

**Comment by sevos1984** [comment]
We can't release patch for certain versions, you can patch your code by yourself using 2.0 latest release or upgrade to version you need. Thanks.
