### ISSUE TITLE
Admin Order Grid running out of memory

### ISSUE THREAD

**Issue by karmalis** [magento/magento2#5982]
### Preconditions

1. Magento 2.1.0 dev/production
2. PHP 2.6.\* (tested on 2.6.0 and 2.6.24)
### Steps to reproduce

This one is a bit tricky as it might be very difficult to reproduce. We have a very large database with many (over 130k orders and almost 1 million items in them) that we need to migrate. So it might be a 1 off, or it might be something else very specific.
1. Install a clean version of Magento 2.1.0
2. Migrate the data from the old site using the Data Migration Tool
### Expected result

1. Log into the admin
2. Go to Sales -> Orders
3. See the orders in the grid view
### Actual result

1. Log into the admin
2. Go to Sales -> Orders
3. Page error 500 shows up. The logs say, the system has run out of memory (1024M). 

Some notes:
- Increasing  the memory does not help (2GB of memory basically just prolongs the error 500
- Invoices, of which the number is similar to orders work just fine. So do shipments.
- Everything else on the site works

Is there anything we can do to test/trace/debug/source to find the issue?

**Comment by karmalis** [comment]
On an additional note, using xdebug I've traced that the running out of memory happens when the page (grid) is being rendered.

**Comment by karmalis** [comment]
Another note: Seems that sales_order_grid is causing the issue and crashing on \Magento\Framework\Data\Collection\AbstractDb loadWithFilter function where it tries to add the items to the so called "collection". Again, this is not an issue with sales_invoice_grid, which has a similar amount of items.

**Comment by askarbin** [comment]
same issue here

**Comment by askarbin** [comment]
In my case the problem was related to 3rd party extension. Product listing grid wasn't properly extended by an xml file located at:
`<module root dir>/<vendor>/<module>/view/adminhtml/ui_component/product_listing.xml`
The pager component was missing which caused the listing to load the whole collection of products along with eav entities.

**Comment by karmalis** [comment]
Very interesting, will investigate if that might be the case. Thanks @askarbin

**Comment by karmalis** [comment]
Indeed this seems like the case as well. Again many thanks @askarbin .
