### ISSUE TITLE
Special Price From Date to Date

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#5984]
Special Price From Date to Date not coming on configurable products at backhand i wanna show deal price via this but unfortunately this is not coming Magento ver 2.1.0

**Comment by MageX-C** [comment]
You can only setup special price on child product of configurable product

**Comment by ednacool** [comment]
Is this possible i can set it up for configurable product

**Comment by MageX-C** [comment]
Two way:
1. Go to **product edit page**, select child product and edit special price in advanced pricing option.
2. Filter all child product from **admin-catalog**, select all and choose **Update attributes** action. Now u can edit special price of all child product at once

**Comment by andimov** [comment]
@ednacool 
Thank you for reporting!
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by rramiii** [comment]
I installed 2.1.0 ee and can't find special from/to date in advanced pricing, only special price field is available. this is happening for all products
![ftdates](https://cloud.githubusercontent.com/assets/18686612/17508965/a46dcadc-5e28-11e6-8187-f0825433767b.jpg)
.

**Comment by chamath** [comment]
I have found following error when adding special prices

`Warning: strtotime() expects parameter 1 to be string, object given in <project_path>\vendor\magento\framework\Stdlib\DateTime\DateTime.php on line 138`

Any solution for this?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Special-Price-From-Date-to-Date/idi-p/45016).

**Comment by mpchadwick** [comment]
@rramiii Magento actually intentionally removed special price from and special price to in Magento 2 enterprise. See vendor/magento/module-catalog-staging/etc/adminhtml/di.xml

```xml
<type name="Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav">
    <arguments>
        <argument name="attributesToEliminate" xsi:type="array">
            <item name="news_from_date" xsi:type="string">news_from_date</item>
            <item name="news_to_date" xsi:type="string">news_to_date</item>
            <item name="custom_design_from" xsi:type="string">custom_design_from</item>
            <item name="custom_design_to" xsi:type="string">custom_design_to</item>
            <item name="special_from_date" xsi:type="string">special_from_date</item>
            <item name="special_to_date" xsi:type="string">special_to_date</item>
        </argument>
    </arguments>
</type>
```

Per their documentation, they want you to use Scheduled Updates for special price

http://docs.magento.com/m2/ee/user_guide/catalog/product-price-special.html

**Comment by RDXSportsCom** [comment]
I installed 2.2.2 ee and can't find special from/to date in advanced pricing, only special price field is available. with a cost field, this is happening for all products.

Any solution guys?
