### ISSUE TITLE
Is a Models' _afterLoad()-method deprecated as well?

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#5986]
I've got some functionality in my Models' `_afterLoad()`-method (not the resource model), but it's not fired. I load my Model by using a repository and a `get()`-method, since Models' `save()` and `load()`-methods are deprecated since 2.1.

But is `_afterLoad()` deprecated as well? It doesn't have the `@deprecated`-tag in its docblock.

**Comment by orlangur** [comment]
Looks like `after_load` event is [preserved](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/EntityManager/Operation/Read.php#L119) but `_afterLoad` call not. Your implementation must not rely on internals like `_afterLoad` or `afterLoad` methods not marked with `@api` anyway.

**Comment by veloraven** [comment]
@kanduvisla if you think it to be an issue please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is just a question please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
