### ISSUE TITLE
Product Export csv doesn't contain configurable products.

### ISSUE THREAD

**Issue by rajabharathi22** [magento/magento2#5987]
I am using Magento 2.1.0. When I was trying to export all products from my magento installation it left the configurable products in the csv.

If i try to export the specific sku its exporting the configurable products as well as simple products associated with it.

**Comment by andimov** [comment]
@rajabharathi22 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by senthilengg** [comment]
@andimov 

### Preconditions

Magento 2.1 
Cent OS + Nginx

### Steps to reproduce

i) Install Magento
ii) Install Sample Data
iii) Login to Admin And export all products
iv) Look for configurable product types.

### Expected result

Configurable products should be there in the csv with associated products.

### Actual result

Child products are there in the csv but not the parent configurable products.

Let me know if you need further details.

**Comment by AVoskoboinikov** [comment]
Hi, @senthilengg 

Thanks for provided steps, but I can not reproduce this issue. I am using CE 2.1 with Sample Data and generated csv contains all configurable products that I need (they are displayed at the bottom of the csv file). Please look at the attached screenshot. There is configurable product with sku MH01 and you can find it in csv file too. 

So, could you please recheck you steps and generated csv file and tell me if you are still experiencing this issue?

Thanks!

[pic1]
![pic1](https://cloud.githubusercontent.com/assets/17980272/18045533/ec249adc-6ddb-11e6-83c3-69fcc23784ab.png)

**Comment by AVoskoboinikov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please create new as needed.
