### ISSUE TITLE
Disable email communication set to yes: email did get sent. 

### ISSUE THREAD

**Issue by Tristan-N** [magento/magento2#5988]
After installing a data migration tool I disabled all Email communication for all store-views. However, people who are subscribed to the newsletter received a confirmation e-mail with the basic Luma template without any data (see screenshot). Sender of email turned out to be owner@example.com. 
### Preconditions
1.  Magento CE 2.1.0
2. PHP 7.0.9
### Steps to reproduce
1. Installed module for data migration. 
2. Went to Store -> Configuration -> Advanced -> System -> Email Sending Settings
3. Set Disable Email Communications to Yes. 
4. Checked on all store views if setting was disabled. 
5. Migrated Customers from Magento 1.9.2.4 to Magento 2.1.0.
6. Received confirmation e-mail for subscription to a newsletter. Mails were sent to subscribers of 1 particular store view. 
7. Search for loggs or mailhistory to see what happend. There are no logs anywhere that tells me any email were sent.
### Expected result
1. After migration no persons should receive any email when the option Disable Email Communication is set to Yes. Email wasn't even configured yet. 
### Actual result
1. Owner@example.com sent an email to all customers subscribed to the newsletter of the Magento 1 store, only showing (in Dutch) "You successfully subscribed to our newsletter." 
   See screenshot (red marks are because of the store data there). 
   ![newsletter_confirmation_jpg](https://cloud.githubusercontent.com/assets/19165453/17400871/ada58a54-5a4a-11e6-90ed-5a312464cc09.jpg)

**Comment by drwebbe** [comment]
Same here :
Set Disable Email Communications to Yes.
But order confirmation mails are being sent.

**Comment by ghost** [comment]
I've checked the magento 2 source. The only module wich seems the be looking a the value of the smtp_disable config is the newsletter module. It uses the isValidForSend method. The rest of the Magento 2 Emails does not use the setting and therefore always sends out emails. Not ideal in development type situations!! Please fix. Thanks

**Comment by victor-v-rad** [comment]
@Tristan-N 
what exactly the tool do you use? Is it official Data Migration Tool from Magento or it is third party extension?

**Comment by ilol** [comment]
Did you use Magento`s [Data Migration Tool](https://github.com/magento/data-migration-tool) ?

**Comment by ghost** [comment]
@Tristan-N I've created a email catcher. Wich also makes it possible to disable all email communication https://github.com/experius/Magento-2-Email-Catcher-Module

**Comment by Tristan-N** [comment]
@ilol @victor-v-rad  I did it once with the Migration tool from Magento and suffered this problem so I reinstalled the entire Magento installation and used LitExtension Cart Migration. With both migration tools the same problem. 

@dheesbeen Thanks!

**Comment by ilol** [comment]
@victor-v-rad can you please check it?

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59146. Thanks for reporting

**Comment by slavvka** [comment]
The issue has been fixed and delivered to mainline

**Comment by Ctucker9233** [comment]
@slavvka Is this fix safe to integrate into a 2.1.1 production environment or is there a patch pending?

**Comment by slavvka** [comment]
Hi @Ctucker9233, I think it is safe to apply the fix for both 2.0 and 2.1. Please see 34257ca and   5b5fd02 commits.

**Comment by Ctucker9233** [comment]
@magento-engcom-team This is fixed for 2.1x now correct? Has it been released in a particular version?

**Comment by hostep** [comment]
@Ctucker9233: by quickly looking at the class `Magento\Email\Model\Plugin\TransportInterfacePlugin` in various versions of 2.1, and I can see the class was introduced in version 2.1.8, and the [release notes for 2.1.8](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html) also mention this:
> Magento no longer sends email when the Disable email communication setting is set to yes. Previously, Magento sent email even when this setting was enabled. GitHub-5988

So should be fixed in 2.1.x indeed! :)
