### ISSUE TITLE
Store groups - Add sorting field

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#599]
For now we have sorting store groups by store group name only. We should add sort_order field(like for store views) and sort by it. It's needed if we have few store groups and switcher between store groups on our website, now we haven't ability manage orders.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-25647

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Store-groups-Add-sorting-field/idi-p/47079).
