### ISSUE TITLE
Magento 2.1 CE Password Reset Logo.

### ISSUE THREAD

**Issue by tomsonnemans** [magento/magento2#5991]
### Steps to reproduce
1. Log in into backend and send a reset password mail to a customer.
2. Logo in mail is not matching front-end locale, but backend.
### Expected result
1. If the customer is registered to a store with language nl_NL, the logo should be from nl_NL, and not the language the backend is set to.
### Actual result
1. The backend language is used to show the logo. In my case en_US.

**Comment by AVoskoboinikov** [comment]
Hi, @Tohmn 

Thanks for reporting this issue. We will try to reproduce it and give you feedback as soon as we can.

**Comment by AVoskoboinikov** [comment]
Bug confirmation is blocked right now with internal ticket #MAGETWO-57291

**Comment by magento-engcom-team** [comment]
@tomsonnemans, thank you for your report.
The fix for this issue is already available in 2.1 and 2.2. See commit https://github.com/magento/magento2/commit/e63ad75b56b498d14610216244c7425ef484a0ca
