### ISSUE TITLE
JS translation not working for some fields

### ISSUE THREAD

**Issue by Umfi** [magento/magento2#5995]
Please have a look at this:

http://magento.stackexchange.com/questions/128699/magento-2-form-validation-translation

I can't translate the following texts, everything else works. Could this be a magento core bug?

"Please enter a date.", "Gib bitte ein Datum ein."
"Please enter a valid full date.", "Gib bitte ein gültiges Datum ein."
"Please enter a valid month (1-12).","Bitte gültiges Monat eingeben (1-12)."

(On Magento 2.0.8)

**Comment by andimov** [comment]
@Umfi
Thanks for reporting.
This is a duplicate issue of the https://github.com/magento/magento2/issues/5509. I'm closing this one. 
We have already created internal ticket MAGETWO-55900 to fix this issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250
