### ISSUE TITLE
Loop shipping methods

### ISSUE THREAD

**Issue by bachlee89** [magento/magento2#5996]
Preconditions
1. On Magento 2.1 backend
2. Go to Stores -> Configuration -> Sales -> Shipping Method : Disable all shipping method

Expected result:
No shipping method on checkout page

Actual result:
Shipping method still display:
![image](https://cloud.githubusercontent.com/assets/5562316/17410053/3c74c532-5a9c-11e6-9862-adeb1f6449ca.png)

**Comment by Choufourax** [comment]
We had the same issue. 
Checking some xhr request we saw some warning message "$HTTP_RAW_POST_DATA is deprecated"

1/ Edit the php.ini of your server and **set always_populate_raw_post_data** to **-1**

`always_populate_raw_post_data = -1`

2/ Restart your server

See also :
http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_php-set.html#trouble-php-always

This will fix some other issues like Wizard update problem

**Comment by magento-engcom-team** [comment]
@bachlee89, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
