### ISSUE TITLE
Wrong Tax calculation on HHVM

### ISSUE THREAD

**Issue by ju2kr** [magento/magento2#5997]
I'm running Magento 1.9.1.0 at HHVM 3.14.4

I added `hhvm.enable_zend_sorting = 1` to /etc/hhvm/php.ini file and  /etc/hhvm/server.ini, but the tax calculation is actually wrong.
![bildschirmfoto 2016-08-04 um 22 17 59](https://cloud.githubusercontent.com/assets/8549484/17417117/fc55c2b2-5a91-11e6-9fd7-1152281daa2e.png)
34,90*0,07 = 2,429 and not 2,28 like Magento show it.

Has anyone an idea how I can solve my problem?

**Comment by springimport** [comment]
![capture](https://cloud.githubusercontent.com/assets/18581994/17448041/0c52ee9a-5b20-11e6-90fe-ce515c0a3373.PNG)

**Comment by pboisvert** [comment]
@escapestring this GitHub is intended for Magento 2 issues only. You can try to get an answer to your question on Stackexchange or report a ticket [here](https://www.magentocommerce.com/bug-tracking)
