### ISSUE TITLE
Translation -  $block->escapeHtml($_option->getTitle()) does not get translated

### ISSUE THREAD

**Issue by srenon** [magento/magento2#5998]
They are  alot of instances where text are be escape but not translated.

```
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?php /* @escapeNotVerified */ echo $class; ?>">
    <label class="label" for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
```

> <?php echo  $block->escapeHtml($_option->getTitle()) ?>

Need to change to 

> <?php echo  $block->escapeHtml(__($_option->getTitle())) ?>

Example

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/view/frontend/templates/product/view/options/type/default.phtml#L12

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/view/frontend/templates/product/view/options/type/select.phtml#L18

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/composite/fieldset/options/type/date.phtml#L15

**Comment by IlnitskiyArtem** [comment]
@srenon, thanks for reporting this issue
We've created internal ticket MAGETWO-70109 to address this issue.

**Comment by magento-engcom-team** [comment]
@srenon, thank you for your report.
We've created internal ticket(s) MAGETWO-70109 to track progress on the issue.

**Comment by zamoroka** [comment]
#mageconf

**Comment by dmanners** [comment]
@srenon for me I think this is ok. The title of an option can be controlled on store view level in the product data. This sort of value should not be translated via the translation function but rather in the product data.

**Comment by tdgroot** [comment]
I agree with @dmanners. This issue should be closed.

**Comment by okorshenko** [comment]
Hi @dmanners @tdgroot 
Thank you for your collaboration. Closing the issue
