### ISSUE TITLE
Magento 2.1 CE, Cannot change attribute set for bundled product

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#5999]
### Preconditions

1. Magento ver. 2.1.0 CE
2. PHP 7.0.9 
### Steps to reproduce

1. Find/Create bundled product in admin with attribute set of "Default"
2. Edit bundled product and change attribute set from "Default" to another set.
### Expected result

1. Page should refresh with new attributes from newly assigned set. 
### Actual result

1. Page attempts to refresh, but hangs with the Please wait overlay.  
   ![capture](https://cloud.githubusercontent.com/assets/13354171/17423360/d1de7fd6-5a7f-11e6-9bd6-a65e51956e8f.PNG)
2. Chrome console reports "Uncaught TypeError: Cannot read property 'length' of undefined"
   ![capture](https://cloud.githubusercontent.com/assets/13354171/17423402/ffc08700-5a7f-11e6-8242-5bc0be560fdc.PNG)

**Comment by sean-breeden** [comment]
I have the same problem.  Same specs and error.

**Comment by s00071609** [comment]
Same issue. So many bugs

**Comment by orbitrod** [comment]
Does anybody know if there is a way to change the attribute set of a product, other than doing it on the edit product page?  

I tried creating new bundle products with the correct attribute set, but I get the same error when trying to  create a new product.

**Comment by mikelevy300** [comment]
I'm having the same issue with simple products.  The error occurs both when editing an existing product and when creating a new product.  I'm on Magento CE 2.1.0 with PHP 5.6.20

**Comment by orbitrod** [comment]
@sean-jamersan @s00071609 @mikelevy300 Have any of you guys, been able to figure out  solution or workaround for this error?  Or are you still having the same problem?

I tried creating new bundle products with the correct attribute set at the outset.  But I get the same hanging error when created a new bundled product, that I get when trying to edit the attribute set of an existing product.

As a last resort, I tried manually changing the attribute set in the database.  Which at first, seems to have solved the problem.  After manually changing the attribute set, I see that the product reflects the new set.  But when I try to make changes to the product and save it, I get a lot of errors.  So I don't think manually changing the attribute set, in the db, is the way to go.

**Comment by TClilMouse** [comment]
I have the same issue but here is my console error message.

TypeError: $data.recordData(...) is undefined
knockout.js%20line%202624%20%3E%20Function:1:69

**Comment by mikelevy300** [comment]
I think I found a workaround.  For me it seems like the root issue was the price attribute not being in the 'Product Details' group of my destination attribute set.  

Before I started tinkering, my destination attribute set had a 'Prices' group where the price attribute was located.  When I moved the price attribute out of the 'Prices' group back into the 'Product Details' group and deleted the 'Prices' group, I was able to change the attribute set for my product to the destination attribute set without any problem.  

Not sure if that's just a very specific example relevant to just me, but wanted to share that finding nonetheless.

**Comment by TClilMouse** [comment]
Thank you for the direction. No more issue after adding the "Bundle Items" group in my destination attribute set.

**Comment by AVoskoboinikov** [comment]
Hi guys,

Do you still experiencing this issue? I've tried it on new CE version 2.1.1 with sample data and it works fine for me from the scratch. Can anyone of you recheck it and provide detailed steps how I can reproduce it?

Thanks!

**Comment by TClilMouse** [comment]
Same issue in 2.1.1.
Just delete the "bundle Items" group in your attribute and you can reproduce it.

**Comment by AVoskoboinikov** [comment]
Hi there,

Thanks for help. I've managed to reproduce it so I created internal ticket (#MAGETWO-58212) for it. This issue will be closed after fix.

Thanks for contributing!

**Comment by flipflap** [comment]
Hi  there, for me it works without "bundle items". But it fails if I move "price type" out of "product details.

**Comment by Achitakayoh** [comment]
Same as flipflap. You should avoid moving "price type AND price" out of "product details".

**Comment by cchamikara** [comment]
I had the same issue with 2.1.7 EE , in my case we have upgraded our store from 2.0.15 EE to 2.1.7 EE and with 2.1.x versions I noticed that there is a new attribute Group called "Bundle Items" which wrapped "shipment_type" attribute.

So to resolve the issue I have manually "Bundle Items" group wrapped with "shipment_type" attribute to each custom Attribute sets and it resolved the issue 

<img width="229" alt="screen shot 2017-07-22 at 9 55 19 pm" src="https://user-images.githubusercontent.com/5801721/28492868-842027fe-6f28-11e7-8494-3f7c662fc995.png">

**Comment by magento-engcom-team** [comment]
@orbitrod, thank you for your report.
We've created internal ticket(s) MAGETWO-58212 to track progress on the issue.

**Comment by davidverholen** [comment]
same problem here with 2.1.9
Although the target attribute set has the Bundle Items group including the shipment_type and also the price attributes are still under the Product Details group

**Comment by davidverholen** [comment]
actually this seems to happen with any attribute from the default attribute set, which is missing in the custom target attribute set

**Comment by colinwolff** [comment]
I'm also having the same issue but with a simple product. When trying to switch from Default to another custom attribute set the page just hangs.

Magento 2.1.9 CE

Console error shown below:
![image](https://user-images.githubusercontent.com/1562545/31679473-0743e9cc-b326-11e7-8dbc-019fd7dc5acb.png)
Has anyone found a workaround till a bugfix is released? I've tried everything mentioned above.
Thanks!

**Comment by davidverholen** [comment]
@colinwolff are you sure that your custom attributeset has (at least) every attribute from the default attribute set? That "solved" it for us immediately

**Comment by OmegaPT** [comment]
Hi guys  need some help magento 2       version 2.1.9 cannot change to my new attribute, only loading loading. :(

http://prntscr.com/hqr532

**Comment by orbitrod** [comment]
@TClilMouse's and @cchamikara's solution worked for me.   My destination attribute set did not have a "Bundle Items" group even though it had the "shipment_type" attribute.  The "shipment_type" was located under a different group.  I added the "Bundle Items" group to my destination attribute set and put the "shipment_type" attribute under and it worked.

**Comment by kzozulya** [comment]
Hi all,
I have the same issue as Topic Started wrote (exactly the same)
We have a Migration_Default Attribute set.
Solution for me (may be project specified solution but maybe useful for someone else):
In Admin Panel relocate attribute  quantity_and_stock status to Migration Prices attribute group (group with code advanced-pricing):
https://monosnap.com/file/0H3dl34HyBXlI2tDqtvBtg6NlLIRuI
https://monosnap.com/file/M9Iv1g7neSKqMdRZAbl3SGNpLSEA9S

**Comment by Jeeva-Rathinam** [comment]
> I think I found a workaround. For me it seems like the root issue was the price attribute not being in the 'Product Details' group of my destination attribute set.
> 
> Before I started tinkering, my destination attribute set had a 'Prices' group where the price attribute was located. When I moved the price attribute out of the 'Prices' group back into the 'Product Details' group and deleted the 'Prices' group, I was able to change the attribute set for my product to the destination attribute set without any problem.
> 
> Not sure if that's just a very specific example relevant to just me, but wanted to share that finding nonetheless.

I did the same what you suggest still getting the same error, any other possibilities of error?
