### ISSUE TITLE
Share wishlist email is not working

### ISSUE THREAD

**Issue by Nehace40** [magento/magento2#6003]
After Migration 2.0.7 to 2.1.0 When i share wishlist email than in email shows We're sorry, an error has occurred while generating this email.

IN exception i am getting this error  Warning: htmlspecialchars() expects parameter 1 to be string, object given in app/code/Magento/Email/Model/Template/Filter.php on line 653

**Comment by andimov** [comment]
@MagentoTest1111 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by Nehace40** [comment]
In magento 1 For customer name use {{var customer.name}} but in magento 2 for customer name {{var customer.name}} returns empty so i changed to {{var customerName}} and its working now

**Comment by mgomma** [comment]
This issue exists in 2.1.3

**Comment by SamB-GB** [comment]
This issue still exists on 2.3.1
