### ISSUE TITLE
ImportExport: Indexers should be locked when importing

### ISSUE THREAD

**Issue by paales** [magento/magento2#6004]
### Preconditions

1. Magento 2.1
2. 
### Steps to reproduce

1. Run an import
2. Run an import again while the cron indexers have just triggered.
### Expected result

1. Indexers should be halted / killed and the importer should run
2. After the importer has ran the importer should resume.
### Actual result

1. Deadlocks occur because the indexer is trying to do stuff (with insert from select, which might a bad idea in itself)

```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `catalog_category_product` WHERE (product_id IN ('3855', '3856', '3857', '3858', '3859', '3860', '3861', '3862', '3863', '3864', '3865', '3866', '3867', '3868', '3869', '3870', '3871', '3872', '3873', '3874', '3875', '3876', '3877', '3878', '3879', '3880', '3881', '3882', '3883', '3884', '3885', '3886', '3887', '3888', '3889', '3890', '3891', '3892', '3893', '3894', '3895', '3896', '3897', '3898', '3899', '3900', '3901', '3902', '3903', '3904', '3905', '3906', '3909', '3910', '3911', '3912', '3913', '3914', '3915', '3916', '3917', '3918', '3919', '3920', '3921', '3922', '3923', '3924', '3925', '3927', '3928', '3929', '3930', '12908', '3931', '3932', '3933', '3934', '3935', '3936', '3937', '3938', '3939', '3940', '3941', '3942', '3943', '3944', '3945', '3946', '3947', '3948', '3949', '3950', '3951', '3952', '3953', '3954', '3955', '3956'))
```

**Comment by southerncomputer** [comment]
Here here - when importing say 100k - to 1 MIL products- cron reindexing can cause database failure of import due to DEADLOCKS - which seem to not bother the indexer. It would be nice to be able to disable indexers via CLI or during product import routines!

Now my both my importer and indexer runs via cron - so we need a lockout routine to detect if another separate cron process happens to be indexing to wait!

**Comment by slopukhov** [comment]
Hi @paales 

Thank you for reporting the issue. It is reported as `MAGETWO-57344` internally.

**Comment by choukalos** [comment]
CC'ing @okobchenko & @vrann & @kandy ; we likely need to work to the indexers to support B2B performance goals.  One item we've talked about is using alias tables... 1 table is the index and used by the store front.  2nd table is used when we're re-runing the index and is the 'build' table.  Only when the index run is finished do you swap tables.  That way there's always 1 table in use and 1 table for building the index on.  I think if we were doing that we wouldn't have this issue.  This was proposed by Ivan C.  Please coordinate with Oleh on proposed fix so we're in alignment with work done in 2.2

**Comment by hostep** [comment]
Any chance this is already in the pipeline of being fixed in the near future? We also run into this.

Thanks!

**Comment by kandy** [comment]
@hostep, yes, we plan improvements in indexers, but looks like it will be available only in next major release

**Comment by koenner01** [comment]
Currently we are bypassing this problem by using a lock file during our import and using a plugin on the tryLockJob function on the Cron\Schedule

```
public function __construct(
    \Magento\Cron\Model\ConfigInterface $cronConfig,
    ...
){
    $this->cronConfig = $cronConfig;
    ...
}

public function aroundTryLockJob(
    $subject,
    $proceed
){
    $jobConfig = $this->getJobConfig($subject->getJobCode());
    if (isset($jobConfig['group']) AND $jobConfig['group'] === 'index') {
        try {
            // Check if the import lock is currently locked (to see if the import is running)
            ...
        }
        catch (\Exception $e) {
            throw new \Exception("Cronjob {$job['name']} should not run while import is running");
        }
    }

    $result = $proceed();
    return $result;
}

private function getJobConfig($jobCode)
{
    foreach ($this->cronConfig->getJobs() as $jobGroupCode => $jobGroup) {
        foreach ($jobGroup as $job) {
            if ($job['name'] == $jobCode) {
                $job['group'] = $jobGroupCode;
                return $job;
            }
        }
    }

    return [];
}
```

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#55
