### ISSUE TITLE
Magento 2 installation hangs at 53% 224 / 421

### ISSUE THREAD

**Issue by melnikovis** [magento/magento2#6008]
Magento 2, version 2.1.0-22

Installation fails at 53% 224 / 421 with:

[Progress: 224 / 421]
Module 'Magento_Cms':
Installing data... Upgrading data...

[Magento\Framework\Exception\LocalizedException]
The page URL key contains capital letters or disallowed symbols.

This happens regardless of php version (tried 5.6.23 and 7.0.9)

Installation script hangs at vendor/magento/module-cms/Model/ResourceModel/Page.php line 119

function isValidPageIdentifier return false

return preg_match('/^[a-z0-9][a-z0-9_\/-]+(.[a-z0-9_-]+)?$/', $object->getData('identifier'));

reason is that $object->getData('identifier') is empty

changing regular expression into /^[a-z0-9]*[a-z0-9_\/-]*(.[a-z0-9_-]+)?$/ helps to solve the issue, and installation completes normally.

CMS Page Table though contains NULL in identifier column for Privacy Policy page
![magento](https://cloud.githubusercontent.com/assets/193415/17432970/b4ee0064-5b0a-11e6-8862-4798daec0d72.png)

Webserver is based on ISPConfig 3.1 multiserver installation with Mariadb Galera cluster and GlusterFS as storage, mounted via NFS

This error happens regardless of installation method, tried CLI, GUI

Looks like sample data is corrupted, but strangely no one else seems to had this problem, since we wasn't able to google any similar case.

**Comment by andimov** [comment]
@melnikovis
Thank you for reporting!
Please, try to increase memory and time limits for php, web server and proxy(if you use it).

**Comment by melnikovis** [comment]
We did that, as it was suggested in forums/issues, however that did not help at all, currently we have:
memory_limit 2048M
proxy idle-timeout 3600
max_execution_time 18000
max_input_time 3600

Installation keep hangs at 53%

And what is most important is that changing regular expression isValidPageIdentifier to accept empty identifier helps to solve the problem.
I guess if that would be memory/timing related then installation would fail anyway after tweeking regexp, but it doesn't.

Any ideas?

**Comment by NadiyaS** [comment]
Hi @melnikovis ,
as I see from your DB you have strange ids for pages (3, 5, 7, 9, 11). Usually they should be 1, 2, 3, 4. and in Magento we really have a bug where we expect exactly the same ids sequence and CMS Upgrade Data tries to upgrade page by id = 4. 
Please use the latest released magento version (2.1.1) or branch 2.1 where you won't have this problem in install, but content of privacy-policy-cookie-restriction-mode page won't be updated. We created internal ticked about this MAGETWO-57928.

**Comment by mudithae** [comment]
I had the same issue with 2.1.1. CE. (stopped at 53%)
However once I delete the .maintenance.flag and refresh the page the installation was continued from where it stopped.
However I doubt whether my installation is correct now. But Frontend and admin seems OK for now.

**Comment by magento-engcom-team** [comment]
@melnikovis Looks like this issue is already fixed in the `2.2` and `develop` branches. Please refer to https://github.com/magento/magento2/commit/0700c5d3426477c1d8d783239ca245c0019ac2c5

Thank you
