### ISSUE TITLE
Magento 2 variation save issue (ver 2.1.0-rc2)

### ISSUE THREAD

**Issue by ajaysolskjaer** [magento/magento2#6010]
Magento 2, ver 2.1.0-rc2

There seem to be an issue when trying to save the products once the variations are added to it. It saves fine at first but when trying to save it the second time I get the JS error.
Also, It saves fine when we have 3 or less variations but if there are more than 3, the product doesn't get saved and shows a JS error in the console.

POST http://ringring.nextmp.net/admin/catalog/product/validate/id/54/type/config…b9cfbe69e39239f145fa61448afe3938b8c6cdd33aef1eae070f8a1a18961/?isAjax=true 403 (Forbidden)
![js error](https://cloud.githubusercontent.com/assets/20857170/17433599/41935114-5b23-11e6-9e98-d0d51a1778c8.png)

I am not able to make any changes in the product once I set the variation and save them.

Also, while creating product configurations, the Summary step should be showing "Generate Products" as the next step but rather it shows "Next" instead.

Screenshot (ver 2.1.0-rc2)
![create product config next](https://cloud.githubusercontent.com/assets/20857170/17433739/01228f72-5b24-11e6-8d60-e2efc9a84cf4.png)

Screenshot (ver 2.0.5)
![magento ver 2 0 5](https://cloud.githubusercontent.com/assets/20857170/17433756/196897d4-5b24-11e6-991c-69dc99e00d59.png)

**Comment by paales** [comment]
@ajaysolskjaer Could you try and see what exceptions the var/log/exception.log report when the ajax request is made?

**Comment by ajaysolskjaer** [comment]
I don't see anything logged here today. The file was last updated on the 22nd of last month.

**Comment by andimov** [comment]
@ajaysolskjaer 
Thank you for reporting!
Please, check why do you get 403 on http://ringring.nextmp.net/admin/catalog/product/validate/id/54/type/config…b9cfbe69e39239f145fa61448afe3938b8c6cdd33aef1eae070f8a1a18961/?isAjax=true 
Enable developer mode and look for a reason in log files.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
