### ISSUE TITLE
How to get swatch attribute value and image in magento 2 ? 

### ISSUE THREAD

**Issue by w786zid1** [magento/magento2#6013]
I am able to get option values from any product attribute . My code is 

protected $eavConfig;
public function __construct(
    ...
    \Magento\Eav\Model\Config $eavConfig,
    ...
){
    ...
    $this->eavConfig = $eavConfig;
    ...
}

then i use this code in my class

$attribute = $this->eavConfig->getAttribute('catalog_product', 'attribute_code_here');
$options = $attribute->getSource()->getAllOptions();

but using this i can only get attribute value. But how can i get swatch attribute value and image ?

**Comment by farior** [comment]
You can use methods of swatches helper `\Magento\Swatches\Helper\Data`

**Comment by w786zid1** [comment]
Thanks a lot. After using this helper its working.

**Comment by andimov** [comment]
@w786zid1 
Please, close this issue if you received the answer.
