### ISSUE TITLE
AbstractSearchResult createIterator faulty implementation -> unusable

### ISSUE THREAD

**Issue by ludwig-gramberg** [magento/magento2#6014]
currently it is not possible to use createIterator on any class that extends because it does not call its factories create method properly

class Magento\Framework\Data\AbstractSearchResult

```
    /**  
     * @return \Magento\Framework\Data\SearchResultIterator  
     */  
    public function createIterator()  
    {  
        return $this->resultIteratorFactory->create(
            [
                'searchResult' => $this,
                'query' => $this->query,
            ]
        );
    }
```

and the iteratorfactory expects the first parameter to be a classname which is not provided

class Magento\Framework\Data\SearchResultIteratorFactory

```
    /**
     * Create SearchResultIterator object
     *
     * @param string $className
     * @param array $arguments
     * @return SearchResultIterator
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function create($className, array $arguments = [])
    {
        $resultIterator = $this->objectManager->create($className, $arguments);
        if (!$resultIterator instanceof \Traversable) {
            throw new \Magento\Framework\Exception\LocalizedException(
                new \Magento\Framework\Phrase('%1 should be an iterator', [$className])
            );
        }
        return $resultIterator;
    }

```

it sure would be nice to be able to use the iterator on huge collections in order to fetch the items one by one, instead of being forced to dump everything into memory via getList

resulting exception:

```
Exception: Warning: ltrim() expects parameter 1 to be string, array given in /var/www/html/mage/vendor/magento/framework/ObjectManager/ObjectManager.php on line 56 in /var/www/html/mage/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'ltrim() expects...', '/var/www/html/m...', 56, Array)
#1 /var/www/html/mage/vendor/magento/framework/ObjectManager/ObjectManager.php(56): ltrim(Array, '\\')
#2 /var/www/html/mage/vendor/magento/framework/Data/SearchResultIteratorFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create(Array, Array)
#3 /var/www/html/mage/vendor/magento/framework/Data/AbstractSearchResult.php(166): Magento\Framework\Data\SearchResultIteratorFactory->create(Array)
#4 /var/www/html/mage/app/code/***/Api/Model/Service/Stock/StockList.php(49): Magento\Framework\Data\AbstractSearchResult->createIterator()
#5 /var/www/html/mage/app/code/***/Api/Model/Response.php(22): ***\Api\Model\Service\Stock\StockList->getResponseBegin()
#6 /var/www/html/mage/vendor/magento/framework/App/Http.php(165): ***\Api\Model\Response->sendResponse()
#7 /var/www/html/mage/vendor/magento/framework/App/Http.php(136): Magento\Framework\App\Http->handleDeveloperMode(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#8 /var/www/html/mage/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#9 /var/www/html/mage/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#10 {main}
```

magento version: 2.0.7
but by the looks of it its still broken in the current master
https://github.com/magento/magento2/blob/f2d309a88298886460351c04973a4ff95c7a91c0/lib/internal/Magento/Framework/Data/AbstractSearchResult.php#L161

**Comment by ludwig-gramberg** [comment]
oh, ok... it looks to me that this was never tested, nor is it used anywhere in the code... so no wonder its not functioning at all...

https://github.com/magento/magento2/search?utf8=%E2%9C%93&q=-%3EcreateIterator%28

**Comment by ludwig-gramberg** [comment]
I ended up just changing the factory, since its never used anywhere I cant really break anything...

```
    /**
     * Create SearchResultIterator object
     *
     * @param array $arguments
     * @return SearchResultIterator
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function create(array $arguments = [])
    {
        $className = '\Magento\Framework\Data\SearchResultIterator';
        $resultIterator = $this->objectManager->create($className, $arguments);
        if (!$resultIterator instanceof \Traversable) {
            throw new \Magento\Framework\Exception\LocalizedException(
                new \Magento\Framework\Phrase('%1 should be an iterator', [$className])
            );
        }
        return $resultIterator;
    }
```

**Comment by Vinai** [comment]
Maybe we should be encouraged to write tests for issues we open that will pass once the bug is fixed. The test coverage would increase over time and the core team would be motivated to pick up testing again. I don't know why, but I get the impression they abandoned TDD.

**Comment by ludwig-gramberg** [comment]
i'm not involved enough (yet) to write tests...

**Comment by ludwig-gramberg** [comment]
another related fix thats necessary:

in vendor/magento/framework/Data/SearchResultIterator.php

```
/**
     * @return void
     */
    public function next()
    {
        ++$this->key;
        $fetchResult = $this->query->fetchItem();
        $this->current = $fetchResult ? $this->searchResult->createDataObject(['data' => $fetchResult]) : null;
    }
```

here were 2 bugs
1. the valid method could never yield false because it was never checked wether or not the query returned anything, so you end up in an endless loop
2. cerateDatObject was called wrong so the data was never injected into the object

**Comment by ludwig-gramberg** [comment]
bug still exists in 2.1.2

**Comment by ludwig-gramberg** [comment]
bug still exists in 2.1.7

**Comment by ludwig-gramberg** [comment]
and at least as of 2.1.7 the prior unused class is now used in production code... unfixed... 👎

**Comment by magento-engcom-team** [comment]
@ludwig-gramberg, thank you for your report.
We've created internal ticket(s) MAGETWO-84865 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ludwig-gramberg, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
