### ISSUE TITLE
production mode error on magento 2.1v

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6017]
Magento 2.1v
PHP 7.0.9
Debian 8
Mysql5.6(MariaDB)

:~$ php -d memory_limit=6G httpdocs/bin/magento deploy:mode:set production
Enabled maintenance mode
Starting compilation
sh: line 1: 10837 Segmentation fault      /opt/plesk/php/7.0/bin/php -f /var/www/vhosts/magento2/httpdocs/bin/magento setup:di:compile 2>&1
Something went wrong while compiling generated code. See the error log for details.
Command returned non-zero exit code:
`/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/magento2/httpdocs/bin/magento setup:di:compile

Memory limit is given 6G, yet error arises. Is this a bug in magento 2.1?

**Comment by nmallepally** [comment]
@andimov Any update on above Issue?

**Comment by choukalos** [comment]
What version of 2.1 specifically - is this 2.1.1 ?  
What themes or extensions are you using?  
What memory usage are you seeing doing a compile and static asset deploy?

**Comment by nmallepally** [comment]
Hi @choukalos  appreciate for the response.

I have a 2.1.0 now and i updated to 2.1.1. which it did successfully via composer.
then I was putting my store into production mode.
I ran php -d memory=2G bin/magento deploy:mode:set production
It compile successfully, generates static content and then gives me an error.

New version of deployed files: 1474387324
..
Successful: 2384 files; errors: 3
Command returned non-zero exit code 
php -f /var/www/magento2 /test123/bin/magento setup:static-content:deploy en_US fr_FR 2>&1`
and it stays in development mode.

**Comment by kandy** [comment]
Hi @nmallepally, Can you run commond like
php -f /var/www/magento2 /test123/bin/magento -vvv setup:static-content:deploy en_US fr_FR
and post  full stack of error here

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
