### ISSUE TITLE
Magento 2.0.7 - Authorize .net payment option not shows in multishipping

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#6020]
### Preconditions
1. Magento 2.0.7
### Steps to reproduce

1. go through the multiple shipping process
2. in the billing information page. only check/money order option shows up. Authorize. net options is missing
### Expected result
1. when we are in billing formation page, we should have all payment methods we set up.
### Actual result
1. missing authorize .net payment method.
   ![capture](https://cloud.githubusercontent.com/assets/13892193/17441319/845f5986-5afe-11e6-97a8-df46ac997bf6.PNG)

I have tried using authorize .net in single address shipping and it worked. Therefore the authorize .net setting should be correct. Please help.

**Comment by dexterityzx** [comment]
Also, after I checkout with multiple shipping, the error shows up.
[466120272987.txt](https://github.com/magento/magento2/files/404141/466120272987.txt)

`a:4:{i:0;s:177:"Warning: array_keys() expects parameter 1 to be array, null given in /var/www/magento-demo1/vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php on line 816";i:1;s:11391:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'array_keys() ex...', '/var/www/magent...', 816, Array)
#1 /var/www/magento-demo1/vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php(816): array_keys(NULL)
#2 /var/www/magento-demo1/var/generation/Magento/Multishipping/Model/Checkout/Type/Multishipping/Interceptor.php(194): Magento\Multishipping\Model\Checkout\Type\Multishipping->getOrderIds(false)
#3 /var/www/magento-demo1/vendor/magento/module-multishipping/Controller/Checkout/Success.php(26): Magento\Multishipping\Model\Checkout\Type\Multishipping\Interceptor->getOrderIds()
#4 /var/www/magento-demo1/var/generation/Magento/Multishipping/Controller/Checkout/Success/Interceptor.php(24): Magento\Multishipping\Controller\Checkout\Success->execute()
#5 /var/www/magento-demo1/vendor/magento/framework/App/Action/Action.php(102): Magento\Multishipping\Controller\Checkout\Success\Interceptor->execute()
#6 /var/www/magento-demo1/vendor/magento/module-multishipping/Controller/Checkout.php(149): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\Multishipping\Controller\Checkout->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#9 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Multishipping\Controller\Checkout\Success\Interceptor->___callParent('dispatch', Array)
#10 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'designLoader')
#11 /var/www/magento-demo1/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#14 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'storeCheck')
#15 /var/www/magento-demo1/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#18 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'customer-app-ac...')
#19 /var/www/magento-demo1/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#22 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'contextPlugin')
#23 /var/www/magento-demo1/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#26 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'tax-app-action-...')
#27 /var/www/magento-demo1/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#30 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Multish...', 'dispatch', Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Array, 'weee-app-action...')
#31 /var/www/magento-demo1/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Multishipping\Controller\Checkout\Success\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Multishipping\Controller\Checkout\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#34 /var/www/magento-demo1/var/generation/Magento/Multishipping/Controller/Checkout/Success/Interceptor.php(39): Magento\Multishipping\Controller\Checkout\Success\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/magento-demo1/vendor/magento/framework/App/FrontController.php(55): Magento\Multishipping\Controller\Checkout\Success\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#38 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#40 /var/www/magento-demo1/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#43 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#44 /var/www/magento-demo1/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#47 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#48 /var/www/magento-demo1/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /var/www/magento-demo1/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#51 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#52 /var/www/magento-demo1/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#53 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /var/www/magento-demo1/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#55 /var/www/magento-demo1/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#56 /var/www/magento-demo1/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#57 /var/www/magento-demo1/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#58 /var/www/magento-demo1/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#59 {main}";s:3:"url";s:32:"/multishipping/checkout/success/";s:11:"script_name";s:10:"/index.php";}
`

**Comment by asemenenko** [comment]
@dexteritycc Authorize.net Direct Post implementation send credit card data directly from browser to the Auth.net. Current architecture of multi address checkout creates multiple sales orders, each needs it own authorization transaction which does not allow seamlesly integrate with an Auth.net API due to the fact that we will need to ask for a payment details for every single order which is not possible. We have item in the backlog to improve this part of the multiaddress checkout that will allow us to properly integrate Auth.net DP by having a single payment transaction only. I added this ticket number to notification list and it will be updated once it gets resolved.

**Comment by dexterityzx** [comment]
@asemenenko  how about other payment gateway like paypal, etc. Does any payment gateway support multiple shipping now?

**Comment by asemenenko** [comment]
@dexteritycc for now only 3rd party extensions can implement their custom way to support it. OOTB implementations do not support until a single transaction approach is implemented as a part of the checkout module.

**Comment by zuristeph** [comment]
@asemenenko Do you have recommendations on 3rd party extensions? We need a quick resolution to multi-shipping address. Thanks

**Comment by dexterityzx** [comment]
@zuristeph  this works fine with me. 
https://store.paradoxlabs.com/store/m2/magento2-authorize-net-cim-payment-module.html

**Comment by dmitrii-fediuk** [comment]
@zuristeph
My [**Stripe** extension](https://mage2.pro/c/stripe) does support multishipping: [an example of a multishipping checkout with Stripe payment](https://mage2.pro/t/4411).

**Comment by impunkj** [comment]
How to Get correct this issues. I am running  Magento ver. 2.1.7.

**Comment by impunkj** [comment]
Where to get updated code for this issues ?

**Comment by impunkj** [comment]
Not working in magento 2.1.7. Any update on this ?
