### ISSUE TITLE
Translation Issue on Magento 2.1v

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6022]
Magento 2.1v with Imaginaerum language pack
Does not translate subject on all transaction mails 
Does not translate password strength.
Add to cart is inconsistent after update from 2.0.7
Is there any fix for above issues?.
![password not good enought](https://cloud.githubusercontent.com/assets/19605497/17442790/783854ec-5b2f-11e6-9760-79e8ec8acf21.png)
![title email error](https://cloud.githubusercontent.com/assets/19605497/17442793/7c5fbf7e-5b2f-11e6-8cae-6f9595b3842c.png)

**Comment by andimov** [comment]
@nmallepally 
Thanks for reporting.
This is a duplicate issue of the https://github.com/magento/magento2/issues/5509. I'm closing this one. 
We have already created internal ticket MAGETWO-55900 to fix this issue.

**Comment by nmallepally** [comment]
@andimov  Thanks, Is there any Temporary solution for above issue??.
Can we change the text manually to french. where can we find the templates of orders sent to customers?. If you can advise it will be helpful until it is fixed.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250
