### ISSUE TITLE
Why are there static assets in the Magento_Braintree2 Directory?

### ISSUE THREAD

**Issue by maxbucknell** [magento/magento2#6023]
The Blank theme has a [stylesheet](https://github.com/magento/magento2/blob/2.1/app/design/frontend/Magento/blank/Magento_BraintreeTwo/web/css/source/_module.less) in the Magento_Braintree2 directory, even though this does not correspond to any real module. This breaks the mental model of how theme overrides for `web` assets can be overridden by themes.

These styles are inconsequential, so my recommendation would be that [this file](https://github.com/magento/magento2/blob/2.1/app/design/frontend/Magento/blank/Magento_BraintreeTwo/web/css/source/_module.less) be moved somewhere else. The `Magento_Braintree` directory seems a good choice to me.

**Comment by YevSent** [comment]
Hi @maxbucknell, if you open latest develop repository, there are now styles related to BraintreeTwo module. https://github.com/magento/magento2/tree/develop/app/design/frontend/Magento/blank. This styles are already removed.
