### ISSUE TITLE
Reports issue with always_populate_raw_post_data being deprecated when it isn't even defined.

### ISSUE THREAD

**Issue by JamesColeman-SH** [magento/magento2#6025]
In our environment, we are aware that always_populate_raw_post_data is being deprecated and we leave the configuration commented out to let PHP do its default behavior of not populating the HTTP_RAW_POST_DATA variable. So what I am wondering is. Why does Magento 2 complain about this default setting and why even check if it doesn't use this option.
### Preconditions>
1. Comment out always_populate_raw_post_data in php.ini.
### Steps to reproduce
1. Comment out always_populate_raw_post_data in php.ini.
2. Run readiness check.
### Expected result
1. No issues reported as we have a deprecated variable not set.
### Actual result
1. Magento complains about it not being set and wants us to set a deprecated variable to -1.

**Comment by magento-engcom-team** [comment]
@JamesColeman-SH, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
