### ISSUE TITLE
Edit Product: Reviews tab displaying with spinning/loading icon in when reviews disabled

### ISSUE THREAD

**Issue by digitalredefined** [magento/magento2#6026]
Magento 2.10 Running Homestead VM with Ubuntu 14.04, PHP 5.6
Reviews are disabled via the advanced section of admin

Imported site(single site) from 1.9.5 to 2.0.7 and product page worked fine - was able to edit, review section was not displayed.  I updated to 2.1 and the first issue I hist was the ConfigurablePrice.php  Once I patched this issue, the page loads and displays the "Attention/Something went wrong error message".  Scrolled down and saw this:
<img width="1328" alt="screen shot 2016-08-05 at 3 47 46 pm" src="https://cloud.githubusercontent.com/assets/913850/17448958/378c8a4e-5b25-11e6-8f2a-fb434208b5f1.png">

When viewing the browser console, I see the following message:
<img width="1436" alt="screen shot 2016-08-05 at 3 48 12 pm" src="https://cloud.githubusercontent.com/assets/913850/17448970/510c2786-5b25-11e6-9cd9-9bf038b1aaf5.png">

Able to reproduce on multiple products.  I've tried clearing cache, rebuilding static content and still able to reproduce.

**Comment by andimov** [comment]
@digitalredefned 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by thomvanderboon** [comment]
@andimov Please close this issue. Opened https://github.com/magento/magento2/issues/6264
