### ISSUE TITLE
Incorrect min and max price in index with multiple websites and stores

### ISSUE THREAD

**Issue by mustdobetter** [magento/magento2#6030]
### Preconditions

1. Magento 2.1
2. MySQL 5.7.13
3. PHP 7.0.8
### Steps to reproduce

1. Create two websites with a different store in each (Website A => Store A, Website B => Store B).
2. Set catalog price scope to 'Website'.
3. Create a configurable product with one simple product association and a price of 10.00, keeping the same price on both configurable and simple products.
4. Set the price of the simple product to 20.00 in the Store A scope.
5. Set the price of the simple product to 30.00 in the Store B scope.
### Expected result

1. The min and max price for the product in Website A should be 20.00 (within catalog_product_index_price).
2. The min and max price for the product in Website B should be 30.00 (within catalog_product_index_price).
### Actual result

1. The min and max price for the product in Website A is 20.00 (within catalog_product_index_price).
2. The min and max price for the product in Website B is 20.00 (within catalog_product_index_price).

The issue seems to be due to the following indexer code, with a hardcoded store value when retrieving associated simple product prices. Therefore, regardless of the website ID for which the min and max prices are being stored, they are always being retrieved using a store ID of 0 (zero).

**Magento\ConfigurableProduct\Model\ResourceModel\Product\Indexer\Price\Configurable::_applyConfigurableOption [192]**

``` php
$priceColumn = $this->_addAttributeToSelect($select, 'price', 'l.product_id', 0, null, true);
```

**Comment by mustdobetter** [comment]
Suggested fix attached as patch file. This joins in the store_website, and store_group tables to allow specification of the store_id when selecting the simple product prices. This technique was taken from:

`Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice::_prepareDefaultFinalPriceTable.`

[patch.txt](https://github.com/magento/magento2/files/405142/patch.txt)

**Comment by ronnybremer** [comment]
these two could be related: [https://github.com/magento/magento2/issues/5133](url)

**Comment by veloraven** [comment]
I'm closing this issue as it has already been fixed.
Internal ticket MAGETWO-54704

**Comment by korostii** [comment]
Hi @veloraven, 
I found 5 commits referencing a (duplicate?) issue #5133, one of them marked with MAGETWO-54704 and already on `2.1-develop` indeed: 95daeec

Can you confirm whether the other four marked with MAGETWO-56978 are also required for proper prices' functioning in a multi-website setup? Here they are: a8dc219, 64f2769, 2a573cc, 36b8852
These commits don't seem to be present on `2.1-develop` just yet.
