### ISSUE TITLE
Product weight rounded to 2 decimal places

### ISSUE THREAD

**Issue by GreenImp** [magento/magento2#6031]
### Preconditions
1. Magento CE 2.0.5 without sample data is installed
2. Weight unit is set to "kgs"
### Steps to reproduce
1. Create a product
2. Assign a weight to it, with three decimal places (ie. 0.095)
3. Save the product
### Expected result
1. The weight to remain at the specified 3 decimal places (ie. 0.095)
### Actual result
1. The weight is rounded to 2 decimal places (ie. 0.10)

I'm working on a site that deals with very light items, where everything is weighed in grams.

**Comment by JacobDrummond** [comment]
Magento 2.1 supports four decimal places by default:

![mag-1](https://cloud.githubusercontent.com/assets/8377620/17463331/2e2c0172-5cbb-11e6-9129-216873b1e39b.png)

Is upgrading a viable option for you? (Or are you perilously-close to deployment, and don't want to break anything?)

**Comment by andimov** [comment]
@GreenImp
Thank  you for reporting!
It was fixed by MAGETWO-52701 in 2.1.

**Comment by GreenImp** [comment]
Thanks both of you. I've just upgraded to v2.1 and the issue is resolved.
