### ISSUE TITLE
Admin catalog image thumbnail 404

### ISSUE THREAD

**Issue by thagxt** [magento/magento2#6033]
### Preconditions

1. CentOS cPanel, Apache
2. Magento: 2.1.0, PHP: 5.6.15
### Steps to reproduce

1. Install Magento via Composer
2. Set up a multi-store/website 
3. Create product, make it available in both websites
4. See 404 error message all over the place
### Expected result

1. Should not return 404 errors
### Actual result

1.  ![screen shot 2016-08-07 at 15 08 45](https://cloud.githubusercontent.com/assets/7128602/17462547/37045cea-5cb1-11e6-88e2-e3e6790b8075.png)
2. ![screen shot 2016-08-07 at 15 05 38](https://cloud.githubusercontent.com/assets/7128602/17462549/442d780c-5cb1-11e6-8964-1c727cbd8dc8.png)
3. ![screen shot 2016-08-07 at 14 58 32](https://cloud.githubusercontent.com/assets/7128602/17462551/4d119c3c-5cb1-11e6-8cb4-6b126f3693d2.png)
4. ![screen shot 2016-08-07 at 14 58 44](https://cloud.githubusercontent.com/assets/7128602/17462555/56649442-5cb1-11e6-93c0-754d0f81e9f9.png)

**Comment by tkacheva** [comment]
Internal issue MAGETWO-61248

**Comment by magento-engcom-team** [comment]
@thagxt, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
