### ISSUE TITLE
Styles and Scripts in Admin return 404 when in delevoper mode

### ISSUE THREAD

**Issue by thagxt** [magento/magento2#6034]
### Preconditions

1. CentOS, Cpanel::Easy::Apache v3.32.5 rev9999, Apache/2.4.16 (Unix)
2. Magento CE: 2.1.0, PHP: 5.6.15
### Steps to reproduce

1. Install Magento in Default mode
2. Switch to developer mode `php bin/magento deploy:mode:set developer`
3. _Backend styles and scripts result in 404_
4. Switch to Production mode everything works again after 
### Expected result

1. Expected to work properly
### Actual result

1. ![screen shot 2016-08-07 at 16 40 26](https://cloud.githubusercontent.com/assets/7128602/17463043/5bca0338-5cbe-11e6-8ec6-6eebd109b6a3.png)
2. ![screen shot 2016-08-07 at 16 40 50](https://cloud.githubusercontent.com/assets/7128602/17463044/611b54cc-5cbe-11e6-99a5-3a47d8b62f0a.png)

**Comment by thagxt** [comment]
after deploying with `php magento setup:static-content:deploy` backend started working. 
But it isn't stated in the [devdocs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) that you need to do it.

**Comment by magento-engcom-team** [comment]
@thagxt, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
