### ISSUE TITLE
Free Shipping on Cart Price Rules not working when update qty on Checkout Cart page

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#6040]
Hi,

I already set cart price rules with below : 
![test free shipping promotions marketing magento admin](https://cloud.githubusercontent.com/assets/4571528/17467762/e207cc0e-5d4b-11e6-8558-d6134761ff5a.png)

On Checkout page :
![shopping cart 1](https://cloud.githubusercontent.com/assets/4571528/17467903/f6483018-5d4c-11e6-9edf-4b8292fd92db.png)
![shopping cart](https://cloud.githubusercontent.com/assets/4571528/17467904/f64aa550-5d4c-11e6-849b-2f62bd57d10b.png)
In 2 images above, look like is working for Free Shipping.

But when i'm update qty to 4, Free Shipping still showing up. Free Shipping should appear when qty equals or greater than 5
![shopping cart 2](https://cloud.githubusercontent.com/assets/4571528/17467968/817337a0-5d4d-11e6-8a4d-9aaf55d4b072.png)

whether this is a bug in Magento 2.1 ?

Thankss

**Comment by andimov** [comment]
@ivansuharyadi 
Thank you for reporting!
To allow us to research the issue, please, provide format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by andimov** [comment]
@ivansuharyadi 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by Tapin1** [comment]
I have the same issue.

"Free shipping" method still visible (available) when you change cart (below free shipping threshold) during checkout.
For ex.
1) set free shipping amount to $50 (or any value you like)
2) Go to your store and add to cart any 2 items total cost of ABOVE 50$ ($45+$45 for example)
3) Go to check out. Complete checkout form
4) You'll see free shipping method - it's OK
5) No Go back to your cart and remove one item (so you card gonna be below $50)
6) Go to checkout again
7) Free shipping is still there (You can't remove it ever!)

**Comment by vikassankla** [comment]
@andimov Here's the same issue https://github.com/magento/magento2/issues/8614 reported by another user

**Comment by i95devdivya** [comment]
@Tapin1 I have an issue #8614 similar to issue which is posted by you.
I resolved the issue by using **checkout_cart_update_items_after**, **checkout_cart_save_after** events.
In that observer i wrote the following code inside execute() method.
public function execute(\Magento\Framework\Event\Observer $observer) {
$cart = $observer->getData('cart');
$quote = $cart->getData('quote');
$quote->getShippingAddress()->setFreeShipping(false);
$quote->save();
}

Now it's working fine for me.

**Comment by Turv** [comment]
Whilst the above hacks works, this is still an issue for me in the latest development branch.. a year since it was first reported.
