### ISSUE TITLE
related product

### ISSUE THREAD

**Issue by chiragayartops** [magento/magento2#6041]
Hi
I am making one new store in magento 2, 
In which i created more then 10 products with custom option, then after view open any product with custom option, then after i will checked any custom option at that time i face one price issue, in magento 1x , when i checked custom option at that time change only current product price but not any change price of related product as well as upsell product, But in magento 2x, its effect on all product show related product As well as upsell product in current view product, so please can give me some solution as soon as possible

**Comment by sergei-sss** [comment]
It's true.

Magento 2.1.0 / Sample Data

http://awesomescreenshot.com/03262q4ua7

**Comment by chiragayartops** [comment]
When i change color from dropdown it is change related product price so what can I do?

**Comment by chiragayartops** [comment]
This is default magento2 problem? if yes then how to solve it?

**Comment by andimov** [comment]
@chiragayartops 
Thank you for reporting!
To allow us to research the issue, please, provide format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by chiragayartops** [comment]
Hi,
When i change color swatch product images does not change into configurable in magento2.
Thanks.

**Comment by oserediuk** [comment]
Hello @chiragayartops ! Which code base version do you use?

**Comment by chiragayartops** [comment]
My magento version is 2.1.0.
please see following url:-
http://buy.fellmarine.com/xband.html
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
![swatch error](https://cloud.githubusercontent.com/assets/20859792/17543315/5c8993b6-5eed-11e6-8f84-7051d70d4ed7.png)
My magento version is 2.1.0.
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by veloraven** [comment]
@chiragayartops thank you for your report.
Next time please follow template during an issue creating: with steps to reproduce, actual result and expected result.
Please also check if another customers have already created issues with the same problems. As we already have two issues in GitHub for the first problem described: #4588 and #5798. If I understood correctly and the problem in the first comment is that upsell/crossell/related products change their prices when customer selects some custom option for the product.
So we already have internal ticket for such issue: MAGETWO-53135.
For the second problem (with swatches and pictures) please create separate issue (if it is not created yet by someone else).

**Comment by chiragayartops** [comment]
actual result
![swatch error](https://cloud.githubusercontent.com/assets/20859792/17589474/ad00702a-5ff2-11e6-9b9a-1192298a1d9b.png)

expected result
![swatch_accepted_result](https://cloud.githubusercontent.com/assets/20859792/17589484/b9202b16-5ff2-11e6-84a2-d68de87c5e6d.png)

My magento version is 2.1.0.
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by veloraven** [comment]
@chiragayartops please, create a separate issue for this problem as it differs from the original problem with prices.

**Comment by chiragayartops** [comment]
![minus-price](https://cloud.githubusercontent.com/assets/20859792/17589995/6b1dd5b4-5ff5-11e6-9e44-0c84979809f7.png)

When i change color value product price change also related product price change but it should not be minus.
I already check https://github.com/magento/magento2/issues/5798 but it is not working
please give me proper solution.

**Comment by chiragayartops** [comment]
![minus-price](https://cloud.githubusercontent.com/assets/20859792/17590067/cb6efdbc-5ff5-11e6-9329-21757ae5509e.png)

When i change color value product price change also related product price change but it should not be minus.
I already check #5798 but it is not working
please give me proper solution.

**Comment by chiragayartops** [comment]
please check it https://github.com/magento/magento2/issues/6065. I create a separate issue.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.
