### ISSUE TITLE
Custom Options 2.1

### ISSUE THREAD

**Issue by Corefix** [magento/magento2#6042]
### Preconditions

1. Magento 2.1
2. Chrome 51.x
3. Mac OS 10.11
### Steps to reproduce

1. Go to Magento product admins
2. Add product with 9 custom options (I haven't tested with less on a clean install but on an install with customisations it seems to be a problem with any number of options)
3. Add another product and try to import custom options from previously created product
4. Javascript Error: Uncaught RangeError: Maximum call stack size exceeded dynamic-rows.js:231 (the file varies)
### Expected result

1. For Magento to import custom options selected
### Actual result

1. Javascript Error: Uncaught RangeError: Maximum call stack size exceeded dynamic-rows.js:231 (the file varies)

So the new import custom options was an awesome feature in Magento 2.0 and working we were using it for a project, but after upgradering to 2.1, this feature appears to have broken both with large and small quantities of custom options.

As a side note, great as this feature is. I wouldn't mind this feature to only be available when a product was saved, and for this to be as much a server side change as a frontend change. Meaning that when you clicked on import options it would actually copy the fields to the selected product including translations from other stores, since this is missing now.

**Comment by victor-v-rad** [comment]
Thank you for posting this issue
Internal ticket MAGETWO-56018 to fix it
Here is the same one #5573

**Comment by veloraven** [comment]
I'm closing this issue as it was already fixed in MAGETWO-56018 created for #5573
