### ISSUE TITLE
Update from 2.0.7 to 2.1 Bundle Product Messed Up

### ISSUE THREAD

**Issue by s00071609** [magento/magento2#6046]
Update bundle product from 2.0.7, the update goes successfully, The store initially looked fine but there is a lot of mess that is being discovered.

The bundle product does have bundle option in admin for products that came from 2.0.7. Its completely missing. But, the front end has the options available.

I have seen that on many occasions when options are added to order from these bundle products - the order received in backend has no Items - although transaction went through fine.

When trying to save these bundle products - throws an error:
Notice: Undefined index: delete in /home/couponc1/public_html/vendor/magento/module-bundle/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Bundle.php on line 130

![bundle](https://cloud.githubusercontent.com/assets/19631643/17477103/99e39a1a-5da6-11e6-8ab7-781e7427dfd0.PNG)

See the Backend ORDER Received (Email was sent with Ordered Items but Backend is blank)

![order_backend](https://cloud.githubusercontent.com/assets/19631643/17478721/1d1a17e2-5db1-11e6-9f0a-36b9a36cdb68.PNG)

**Comment by andimov** [comment]
@s00071609 
Thank you for reporting!
To allow us to research the issue, please, provide format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
