### ISSUE TITLE
getLastViewedUrl() doesn't work with caches enabled

### ISSUE THREAD

**Issue by alexander-kozlyuk-ism** [magento/magento2#6047]
Unable to retrieve last viewed URL using getLastViewedUrl() method (vendor/magento/module-catalog/Helper/Data.php)

### Preconditions
1. Magento CE 2.1.0 without sample data is installed.
2. Custom plugin created for \Magento\Checkout\Block\Cart > getContinueShoppingUrl()
3. getLastViewedUrl() used in this plugin to improve "Continue Shopping URL" functionality
![selection_018](https://cloud.githubusercontent.com/assets/14270279/17581478/cde685fc-5fae-11e6-9055-f23b7774f519.png)

### Steps to reproduce
1. Enable caches
2. Add something to cart
3. Visit some product page
4. Refresh cart page
5. Check "Continue Shopping" URL

### Actual result
"Continue Shopping" URL leads to homepage

### Expected result
"Continue Shopping" URL should lead to the last visited product page

### Note
it works fine if caches disabled

**Comment by andimov** [comment]
@nosferix 
Thank you for reporting this issue.
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by alexander-kozlyuk-ism** [comment]
**[Title]**
Unable to retrieve last viewed URL using getLastViewedUrl() method (vendor/magento/module-catalog/Helper/Data.php)

**[Issue Description]**
**[Preconditions]**
1. Magento CE 2.1.0 without sample data is installed.
2. Custom plugin created for \Magento\Checkout\Block\Cart > getContinueShoppingUrl()
3. getLastViewedUrl() used in this plugin to improve "Continue Shopping URL" functionality
![selection_018](https://cloud.githubusercontent.com/assets/14270279/17581478/cde685fc-5fae-11e6-9055-f23b7774f519.png)

**[Steps to reproduce]**
1. Enable caches
2. Add something to cart
3. Visit some product page
4. Refresh cart page
5. Check "Continue Shopping" URL

**[Actual result]**
"Continue Shopping" URL leads to homepage

**[Expected result]**
"Continue Shopping" URL should lead to the last visited product page

**Note: it works fine if caches disabled**

**Comment by PascalBrouwers** [comment]
As a workaround you could set the block to be non-cachable. See my comment here: https://github.com/magento/magento2/issues/6745#issuecomment-250724082

**Comment by magento-engcom-team** [comment]
@nosferix, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
