### ISSUE TITLE
Getting PDOException while creating a Product or altering a product in Magento 2.0.8 in the magento/admin

### ISSUE THREAD

**Issue by GiriManas** [magento/magento2#6051]
0
down vote
favorite

In Magento admin I am trying to create a product where I am getting so many exceptions, while I am updating a product I am getting the exception too. Can any one help me out.

Presently I am using 2.0.8

exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND tad_special_to_date.store_id = 0 LEFT JOIN catalog_product_entity AS tas' at line 17' in C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTOca...', Array) #5 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO ca...', Array) #6 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTOca...', Array) #7 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(344): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO ca...') #8 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(228): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->prepareFinalPriceDataForType(Array, 'simple') #9 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(179): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->_prepareFinalPriceData(Array) #10 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(168): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->reindex(Array) #11 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price\AbstractAction.php(403): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->reindexEntity(Array) #12 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price\Action\Row.php(30): Magento\Catalog\Model\Indexer\Product\Price\AbstractAction->_reindexRows(Array) #13 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price.php(80): Magento\Catalog\Model\Indexer\Product\Price\Action\Row->execute('2061') #14 C:\xampp\htdocs\magento\vendor\magento\module-indexer\Model\Indexer.php(433): Magento\Catalog\Model\Indexer\Product\Price->executeRow('2061') #15 C:\xampp\htdocs\magento\vendor\magento\framework\Indexer\AbstractProcessor.php(51): Magento\Indexer\Model\Indexer->reindexRow('2061') #16 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Product.php(964): Magento\Framework\Indexer\AbstractProcessor->reindexRow('2061') #17 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\Product\Interceptor.php(401): Magento\Catalog\Model\Product->priceReindexCallback() #18 [internal function]: Magento\Catalog\Model\Product\Interceptor->priceReindexCallback() #19 C:\xampp\htdocs\magento\vendor\magento\framework\Model\ResourceModel\AbstractResource.php(92): call_user_func(Array) #20 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\ResourceModel\Product\Interceptor.php(713): Magento\Framework\Model\ResourceModel\AbstractResource->commit() #21 C:\xampp\htdocs\magento\vendor\magento\module-eav\Model\Entity\AbstractEntity.php(1156): Magento\Catalog\Model\ResourceModel\Product\Interceptor->commit() #22 [internal function]: Magento\Eav\Model\Entity\AbstractEntity->save(Object(Magento\Catalog\Model\Product\Interceptor)) #23 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array) #24 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array) #25 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'catalogsearchFu...') #26 C:\xampp\htdocs\magento\vendor\magento\module-catalog-search\Model\Indexer\Fulltext\Plugin\Product.php(28): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Catalog\Model\Product\Interceptor)) #27 [internal function]: Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor)) #28 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array) #29 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'apply_catalog_r...') #30 C:\xampp\htdocs\magento\vendor\magento\module-catalog-rule\Plugin\Indexer\Product\Save\ApplyRules.php(40): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Catalog\Model\Product\Interceptor)) #31 [internal function]: Magento\CatalogRule\Plugin\Indexer\Product\Save\ApplyRules->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor)) #32 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array) #33 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\ResourceModel\Product\Interceptor.php(650): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array) #34 C:\xampp\htdocs\magento\vendor\magento\framework\Model\AbstractModel.php(615): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor)) #35 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\Product\Interceptor.php(2351): Magento\Framework\Model\AbstractModel->save() #36 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Controller\Adminhtml\Product\Save.php(84): Magento\Catalog\Model\Product\Interceptor->save() #37 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Save->execute() #38 C:\xampp\htdocs\magento\vendor\magento\framework\App\Action\Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute() #39 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #40 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #41 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array) #42 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent('dispatch', Array) #43 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Array, 'adminAuthentica...') #44 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http)) #45 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #46 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array) #47 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Array, 'designLoader') #48 C:\xampp\htdocs\magento\vendor\magento\framework\App\Action\Plugin\Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http)) #49 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #50 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array) #51 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Array, 'adminMassaction...') #52 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http)) #53 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #54 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array) #55 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins('dispatch', Array, Array) #56 C:\xampp\htdocs\magento\vendor\magento\framework\App\FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #57 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #58 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array) #59 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #60 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install') #61 C:\xampp\htdocs\magento\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http)) #62 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #63 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array) #64 C:\xampp\htdocs\magento\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #65 C:\xampp\htdocs\magento\vendor\magento\framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #66 C:\xampp\htdocs\magento\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch() #67 C:\xampp\htdocs\magento\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #68 {main} Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND tad_special_to_date.store_id = 0 LEFT JOINcatalog_product_entityAStas' at line 17, query was: INSERT INTO catalog_product_index_price_final_tmp SELECT e.entity_id, cg.customer_group_id, cw.website_id, IF(IFNULL(tas_tax_class_id.value_id, -1) > 0, tas_tax_class_id.value, tad_tax_class_id.value) AS tax_class_id, IFNULL((ta_price.value), 0) AS orig_price, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value)) <= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND ta_special_price.value < ta_price.value, ta_special_price.value, ta_price.value)), 0) AS price, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value)) <= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND ta_special_price.value < ta_price.value, ta_special_price.value, ta_price.value)), 0) AS min_price, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value)) <= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND ta_special_price.value < ta_price.value, ta_special_price.value, ta_price.value)), 0) AS max_price, tp.min_price AS tier_price, tp.min_price AS base_tier FROM catalog_product_entity AS e CROSS JOIN customer_group AS cg CROSS JOIN store_website AS cw INNER JOIN catalog_product_index_website AS cwd ON cw.website_id = cwd.website_id INNER JOIN store_group AS csg ON csg.website_id = cw.website_id AND cw.default_group_id = csg.group_id INNER JOIN store AS cs ON csg.default_store_id = cs.store_id AND cs.store_id != 0 INNER JOIN catalog_product_website AS pw ON pw.product_id = e.entity_id AND pw.website_id = cw.website_id LEFT JOIN catalog_product_index_tier_price AS tp ON tp.entity_id = e.entity_id AND tp.website_id = cw.website_id AND tp.customer_group_id = cg.customer_group_id INNER JOIN catalog_product_entity_int AS tad_status ON tad_status.entity_id = e.entity_id AND tad_status.attribute_id = 94 AND tad_status.store_id = 0 LEFT JOIN catalog_product_entity_int AS tas_status ON tas_status.entity_id = e.entity_id AND tas_status.attribute_id = 94 AND tas_status.store_id = cs.store_id LEFT JOIN catalog_product_entity_int AS tad_tax_class_id ON tad_tax_class_id.entity_id = e.entity_id AND tad_tax_class_id.attribute_id = 129 AND tad_tax_class_id.store_id = 0 LEFT JOIN catalog_product_entity_int AS tas_tax_class_id ON tas_tax_class_id.entity_id = e.entity_id AND tas_tax_class_id.attribute_id = 129 AND tas_tax_class_id.store_id = cs.store_id LEFT JOIN catalog_product_entity_decimal AS ta_price ON ta_price.entity_id = e.entity_id AND ta_price.attribute_id = 74 AND ta_price.store_id = 0 LEFT JOIN catalog_product_entity_decimal AS ta_special_price ON ta_special_price.entity_id = e.entity_id AND ta_special_price.attribute_id = 75 AND ta_special_price.store_id = 0 LEFT JOIN catalog_product_entity_datetime AS tad_special_from_date ON tad_special_from_date.entity_id = e.entity_id AND tad_special_from_date.attribute_id = 76 AND tad_special_from_date.store_id = 0 LEFT JOIN catalog_product_entity_datetime AS tas_special_from_date ON tas_special_from_date.entity_id = e.entity_id AND tas_special_from_date.attribute_id = 76 AND tas_special_from_date.store_id = cs.store_id LEFT JOIN catalog_product_entity AS tad_special_to_date ON tad_special_to_date.entity_id = e.entity_id AND tad_special_to_date.attribute_id = AND tad_special_to_date.store_id = 0 LEFT JOIN catalog_product_entity AS tas_special_to_date ON tas_special_to_date.entity_id = e.entity_id AND tas_special_to_date.attribute_id = AND tas_special_to_date.store_id = cs.store_id WHERE (e.type_id = 'simple') AND (IF(IFNULL(tas_status.value_id, -1) > 0, tas_status.value, tad_status.value)=1) AND (e.entity_id IN(2061))' in C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO ca...', Array) #4 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTOca...', Array) #5 C:\xampp\htdocs\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO ca...', Array) #6 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(344): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTOca...') #7 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(228): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->prepareFinalPriceDataForType(Array, 'simple') #8 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(179): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->_prepareFinalPriceData(Array) #9 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice.php(168): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->reindex(Array) #10 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price\AbstractAction.php(403): Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice->reindexEntity(Array) #11 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price\Action\Row.php(30): Magento\Catalog\Model\Indexer\Product\Price\AbstractAction->_reindexRows(Array) #12 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Indexer\Product\Price.php(80): Magento\Catalog\Model\Indexer\Product\Price\Action\Row->execute('2061') #13 C:\xampp\htdocs\magento\vendor\magento\module-indexer\Model\Indexer.php(433): Magento\Catalog\Model\Indexer\Product\Price->executeRow('2061') #14 C:\xampp\htdocs\magento\vendor\magento\framework\Indexer\AbstractProcessor.php(51): Magento\Indexer\Model\Indexer->reindexRow('2061') #15 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Model\Product.php(964): Magento\Framework\Indexer\AbstractProcessor->reindexRow('2061') #16 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\Product\Interceptor.php(401): Magento\Catalog\Model\Product->priceReindexCallback() #17 [internal function]: Magento\Catalog\Model\Product\Interceptor->priceReindexCallback() #18 C:\xampp\htdocs\magento\vendor\magento\framework\Model\ResourceModel\AbstractResource.php(92): call_user_func(Array) #19 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\ResourceModel\Product\Interceptor.php(713): Magento\Framework\Model\ResourceModel\AbstractResource->commit() #20 C:\xampp\htdocs\magento\vendor\magento\module-eav\Model\Entity\AbstractEntity.php(1156): Magento\Catalog\Model\ResourceModel\Product\Interceptor->commit() #21 [internal function]: Magento\Eav\Model\Entity\AbstractEntity->save(Object(Magento\Catalog\Model\Product\Interceptor)) #22 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array) #23 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array) #24 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'catalogsearchFu...') #25 C:\xampp\htdocs\magento\vendor\magento\module-catalog-search\Model\Indexer\Fulltext\Plugin\Product.php(28): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Catalog\Model\Product\Interceptor)) #26 [internal function]: Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor)) #27 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array) #28 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'apply_catalog_r...') #29 C:\xampp\htdocs\magento\vendor\magento\module-catalog-rule\Plugin\Indexer\Product\Save\ApplyRules.php(40): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Catalog\Model\Product\Interceptor)) #30 [internal function]: Magento\CatalogRule\Plugin\Indexer\Product\Save\ApplyRules->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor)) #31 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array) #32 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\ResourceModel\Product\Interceptor.php(650): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array) #33 C:\xampp\htdocs\magento\vendor\magento\framework\Model\AbstractModel.php(615): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor)) #34 C:\xampp\htdocs\magento\var\generation\Magento\Catalog\Model\Product\Interceptor.php(2351): Magento\Framework\Model\AbstractModel->save() #35 C:\xampp\htdocs\magento\vendor\magento\module-catalog\Controller\Adminhtml\Product\Save.php(84): Magento\Catalog\Model\Product\Interceptor->save() #36

**Comment by andimov** [comment]
@GiriManas 
Thank you for reporting!
To allow us to research the issue, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
