### ISSUE TITLE
Additional info in issues

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6052]
What about add `Additional info` section in new issue template? [Example](https://github.com/yiisoft/yii2/issues/new).
### Additional info

| Q | A |
| --- | --- |
| Magento version | 2.1.0 |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Additional-info-in-issues/idi-p/45008).
