### ISSUE TITLE
The customer_id isn't saved in REST API

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6055]
### Steps to reproduce
1. Send request to `[PUT] /rest/V1/carts/1/shipping-information`

``` json
{
  "addressInformation": {
    "shippingAddress": {
      "region": "New York",
      "regionId": 43,
      "regionCode": "NY",
      "countryId": "US",
      "street": [
        "Main St2.1"
      ],
      "telephone": "64868564631",
      "city": "New York",
      "firstname": "Tom",
      "lastname": "Sawyer",
      "customerId": 4,
      "postcode": 12323
    },
    "billingAddress": {
      "region": "New York",
      "regionId": 43,
      "regionCode": "NY",
      "countryId": "US",
      "street": [
        "Main St2.1"
      ],
      "telephone": "64868564631",
      "city": "New York",
      "firstname": "Tom",
      "lastname": "Sawyer",
      "customerId": 4,
      "postcode": 12323
    },
    "shippingCarrierCode": "ups",
    "shippingMethodCode": "GND"
  }
}
```
### Expected result

Table: _sales_order_address_

| entity_id | parent_id | ... | customer_id |
| --- | --- | --- | --- |
| 1 | 1 | ... | 4 |
### Actual result

Table: _sales_order_address_

| entity_id | parent_id | ... | customer_id |
| --- | --- | --- | --- |
| 1 | 1 | ... | NULL |
### Additional info

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by mbrinton01** [comment]
Can you provide more detail on when this call is made?  Are you making it:
- When the cart exists and the order has not been placed
- After the order has been placed

**Comment by springimport** [comment]
> - When the cart exists and the order has not been placed

**Comment by RomanKrut** [comment]
@springimport Hi. Thank you for feedback. The internal ticket was created MAGETWO-70855 to address this issue.

**Comment by magento-engcom-team** [comment]
@springimport, thank you for your report.
We've created internal ticket(s) MAGETWO-70855 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @springimport

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@springimport thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
