### ISSUE TITLE
catalogProductAttributeMediaGalleryManagementV1 - Image do not shows on product page.

### ISSUE THREAD

**Issue by pyostrike** [magento/magento2#6056]
1. Magento 2.1
2. PHP 7.0.9
3. Adding product via REST API call catalogProductRepositoryV1 
4. Adding image via REST API call catalogProductAttributeMediaGalleryManagementV1 with following code:
   `curl_setopt($client, CURLOPT_URL, $job['dealer']['m_url'].'index.php/rest/V1/products/'.urlencode($data['sku']).'/media');
                               curl_setopt($client, CURLOPT_POST, true);
                               curl_setopt($client, CURLOPT_POSTFIELDS, json_encode(array('entry' => array(
                                                                                                       'label' => $data['name'],
                                                                                                       'position' => 1,
                                                                                                       'types' => array('image', 'small_image', 'thumbnail', 'swatch_image'),
                                                                                                       'media_type' => 'image',
                                                                                                       'content' => array(
                                                                                                                       'base64_encoded_data' => base64_encode(file_get_contents($config['rootpath'].$path)),
                                                                                                                       'type' => $imageinfo['mime'],
                                                                                                                       'name' => preg_replace('/[^a-z0-9]+/i', '', $data['model'])
                                                                                                                   )
                                                                                                   ))));
   `
### Expected result
1. Image must appear on product page.
### Actual result
1. Image is not shown on product page:

![_2016-08-08_22-44-41](https://cloud.githubusercontent.com/assets/4225100/17493735/b60e00e2-5dc2-11e6-8c74-1cd91a854b3e.png)
![_2016-08-08_22-45-13](https://cloud.githubusercontent.com/assets/4225100/17493734/b609e598-5dc2-11e6-978b-6f3e81c4c059.png)
![_2016-08-08_22-48-07](https://cloud.githubusercontent.com/assets/4225100/17493733/b6028852-5dc2-11e6-9b70-7dba36078cd3.png)

**Comment by cherreman** [comment]
We are having the same issue.

However, the types seem to be saved in a PUT operation via /products/{sku}/media/{entryId}

**Comment by magento-engcom-team** [comment]
@pyostrike, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
