### ISSUE TITLE
Magento 2 -- themes not working

### ISSUE THREAD

**Issue by McD3ad** [magento/magento2#6057]
Site installed on subdomain don't display any theme. Not front, not backend.

**Comment by andimov** [comment]
@McD3ad 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
