### ISSUE TITLE
Moving Category Listing Toolbar

### ISSUE THREAD

**Issue by christian-walker** [magento/magento2#6059]
### Preconditions

1.  Magento 2.1
2.  PHP 7 & MySQL
### Steps to reproduce

1. When trying to move the toolbar it doesn't update like it does with the breadcrumbs.
2. I'm in developer mode so changes should be seen right away.  Cache isn't the issue.
3. 
### Expected result

1. The toolbar should be moved to the designated area using the <move  name="" destination/> tag.
   Ex: 
   `
   <move element="product_list_toolbar" destination="category.description" as="product_list_toolbar" after="-" />
   `
### Actual result

1. Result is that it doesn't move from its default location in the category.products.list block

**Comment by Delta-40** [comment]
Any update on this? Its still not working.

**Comment by springimport** [comment]
I have same problem. See https://github.com/magento/magento2/issues/7253

**Comment by posttechguy** [comment]
I want to be able to move the toolbar as well
`<move element="product_list_toolbar" destination="sidebar.main" before="-" />`

Any movement on this ticket? Magento 2.1.8

**Comment by magento-engcom-team** [comment]
@ChristianWalker19, thank you for your report.
We've created internal ticket(s) MAGETWO-82523 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @christian-walker

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@christian-walker thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
