### ISSUE TITLE
Error editing Terms and Conditions

### ISSUE THREAD

**Issue by woakley** [magento/magento2#6062]
Magento Version 2.1.0

In the admin area I click on a condition to edit it:
admin/checkout/agreement/edit/id/1/

But I get the error:
Exception #0 (Exception): Warning: htmlspecialchars() expects parameter 1 to be string, array given in /public_html/vendor/magento/framework/Data/Form/Element/AbstractElement.php on line 286

**Comment by andimov** [comment]
@woakley 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
