### ISSUE TITLE
Magento 2.1.0 issue with method "getAreaCode" & "setAreaCode"

### ISSUE THREAD

**Issue by thietdv-doan** [magento/magento2#6063]
### Preconditions

1. Magento version 2.1.0
### Steps to reproduce

1. Open file "vendor/magento/framework/App/State.php"
2. Check 2 methods "getAreaCode" (line 136) & "setAreaCode" (line 119)
### Expected result

1. There should be a fix for this 2 methods to allow us to check if "$this->_areaCode" has been set or not then we can set if it has not been set.
2. But the method "getAreaCode" always throw an exception
### Suggestion

1. Just return null / false if "$this->_areaCode" has not been set instead of throw exception in "getAreaCode" method

**Comment by jakobfdev** [comment]
+1
This is especially annoying with commands, where you need to check if the area code is set before executing and you have to catch unnecessary exceptions upon execute.
Any progress? No need?

**Comment by Morgon** [comment]
To change this request a little, I wouldn't mind if an exception was thrown if there is an attempt to set the area code to a different area. So, if code gets set for ``frontend`` multiple times, it should return null/false, but an unexpected change to another area would indicate possibly-undesired behavior and should be noted

**Comment by magento-engcom-team** [comment]
@thietdv-doan, thank you for your report.
We've created internal ticket(s) MAGETWO-84622 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@thietdv-doan Thanks for reporting this issue. Considering that area should be set initially and can not be changed, current behavior is correct.
