### ISSUE TITLE
Tier prices are not created if custom attribute with required parameter exists

### ISSUE THREAD

**Issue by Xebi4i** [magento/magento2#6064]
Product's tier prices cannot be created in Magento if exist custom attribute(s) with is_required parameter that established to <YES>. No matter was this attribute included to product’s attribute set or not.
If we want to create tier price for product, we either should update value for such attributes or make such attributes not required. 
### Preconditions
1. Magento 2.1 EE 
2. Preconfigured product (custom) attributes. Some of them (>= 1 ) should have attribute with established required parameter. 
### Steps to reproduce
1.  Choose product that will be updated with tier price.
2. Make sure that in system exist custom attribute that is required.
3. Create tier price within Magento BackOffice or using catalogProductTierPriceManagementV1 interface
### Expected result
1. Tier price should be created.
### Actual result

In Magento BO the <Save> button in product Edit page does not work.
If we use SOAP or REST API interfaces we get next response:
"The value of attribute "attribute_code" must be set"

[Screenshot, logs]
![tier_price](https://cloud.githubusercontent.com/assets/3149168/17510644/80b39cd4-5e28-11e6-824f-34c81e832676.png)

**Comment by oleg-onufer** [comment]
Hi @Xebi4i.
If this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
