### ISSUE TITLE
swatch image

### ISSUE THREAD

**Issue by chiragayartops** [magento/magento2#6065]
When I change swatch image main product image cant change in magento2.
It is showing error like''TypeError: context.find(...).data(...) is undefined'
how to solve this error?
thanks.

**Comment by andimov** [comment]
@chiragayartops 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by chiragayartops** [comment]
please see following url:-
http://buy.fellmarine.com/xband.html
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
My magento version is 2.1.0.
please see following url:-
http://buy.fellmarine.com/xband.html
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
My magento version is 2.1.0.
please see following url:-
http://buy.fellmarine.com/xband.html
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
My magento version is 2.1.0.
please see following url:-
http://buy.fellmarine.com/xband.html
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
![swatch error](https://cloud.githubusercontent.com/assets/20859792/17543271/ff35a10a-5eec-11e6-94e0-15fac45984fe.png)
My magento version is 2.1.0.
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
actual result
![swatch error](https://cloud.githubusercontent.com/assets/20859792/17589474/ad00702a-5ff2-11e6-9b9a-1192298a1d9b.png)

expected result
![swatch_accepted_result](https://cloud.githubusercontent.com/assets/20859792/17589484/b9202b16-5ff2-11e6-84a2-d68de87c5e6d.png)

My magento version is 2.1.0.
when i change swatch image product main image cant change please give me suggestion for this.
Thanks.

**Comment by chiragayartops** [comment]
Hi,
Any update?

**Comment by veloraven** [comment]
@chiragayartops please provide more detailed steps and describe actual result and expected result.
It is hard to understand now what exactly you do, what you get and what you expect to get. Screenshots without description and any additional marks do not help much unfortunately.
Please also provide information if it was clear install of 2.1 or upgrade from previous version

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
