### ISSUE TITLE
Why so many JS error

### ISSUE THREAD

**Issue by Nerogee** [magento/magento2#6066]
### Preconditions

1. Magento 2.1
2. php 7.0.7, Nginx, MariaDB 10.1
### Steps to reproduce

1. Actually I don't by what pattern JS error pops up.
2. I do a few testing order and when one is finished there is always JS error that prevent the second to proceed
3. Error is versatile 
   ![screenshot from 2016-08-09 17 16 56](https://cloud.githubusercontent.com/assets/12842026/17511512/c060d482-5e55-11e6-9805-a9e212ffd48f.png)
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by andimov** [comment]
@Nerogee 
Thanks for reporting!
Did you upgrade Magento before?
Try to clean browser or server cache.

**Comment by Nerogee** [comment]
No, this is fresh installed. This error is not always happen. Clean cache doesn't work at all. But there is a known issue https://github.com/magento/magento2/issues/4921. After apply this solution, seem it works fine so far

**Comment by andimov** [comment]
@Nerogee 
Thank you!
Glad that you have found a solution. 
 I'm closing this issue as duplicate. Please feel free to reopen if you need.

**Comment by Nerogee** [comment]
@andimov I'm afraid the issue is still there. After fail to place the order, I think it's because some error in JS which result in the shipping address doesn't show properly under the **cash on delivery**. order is successfully placed after I refresh the page. But then lots of JS error is coming again. This is most confusing part for me. How could this even be possible related to each other??

**Comment by Nerogee** [comment]
I'm not sure what happen to Magento2.1. But from what I know by using it, seem it's a half finished product. Tons of issues and among which most of them are about JS. at least it's true for me. Both requireJS and Knockout.JS are new. I'm wondering do they work perfect together under magento system.  if you could give me some insight of what's going on that would be nice.
