### ISSUE TITLE
Clear Persistence on Sign Out	 not working in Magento 2.1

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6069]
Clear Persistence on Sign Out   option is not working. I have set to "Yes". However when customer logged out - their added products are still associated with their account. So once they come back - they would able to see their old added product. while it should be removed as Clear Persistence on Sign Out set to "YES".

Anyone else face this issue?

**Comment by andimov** [comment]
@ravibhalodia 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by ghost** [comment]
Title - Clear Persistence on Sign Out option is not working.

Steps to produce
1) Login to admin
2) Go to stores >> configuration >> customers >> persistent shopping cart 
3) Set Enable Persistent to YES
4) Set Clear Persistence on Sigh Out to YES and SAVE
5) In storefront, logged in using a customer and add product to shopping cart
6) When customer sign out, added product should be cleared.
7) When customer login again, added product is appearing instead of empty cart.

let me know if any other information required.

**Comment by oserediuk** [comment]
Hello @ravibhalodia ! Could you provide which code base version do you use?

**Comment by ghost** [comment]
Hello, i am using Magento 2.1.

**Comment by ghost** [comment]
did you able to generate issue?

**Comment by ghost** [comment]
Does this issue resolved in new release?

**Comment by Szymon-GP** [comment]
I'm using 2.1.4 and it's still an issue

**Comment by ArthurTransoftgroup** [comment]
@ravibhalodia Unfortunately, I could not reproduce the issue as you described it. Please pay attention to Remember Me area and see if the problem is there. And please let us know, is this Issue is still relevant?

**Comment by rajatkar104** [comment]
Hi Team,

I am also facing the same issue on the Magento version 2.1.5.
Title - Clear Persistence on Sign Out option is not working.

Steps to produce

Login to admin

1. Go to stores >> configuration >> customers >> persistent shopping cart
2. Set Enable Persistent to YES.
3. Set Clear Persistence on Sigh Out to YES and SAVE
4. In storefront, logged in using a customer and add product to shopping cart
5. When customer sign out, the added product should be cleared.
6. When customer login again, the added product is appearing instead of the empty cart.

**Comment by MaxKonstructive** [comment]
Hello @magento-engcom-team , 
Same thing is happening on 2.1.7, 2.1.9 & 2.1.11.

Am I correct in thinking this should stop the basket being reformed on customer login?

Enable Persistence -> Yes
Enable "Remember Me" -> No
"Remember Me" Default Value -> No
Clear Persistence on Sign Out -> Yes
Persist Shopping Cart -> No

Many thanks

Max

**Comment by Russellmd** [comment]
Hi,

For Magento 2.2, even if "Enable Persistence" is set to No, the Cart is not cleared when login again

**Comment by clicks-kodet** [comment]
Same issue on 2.3.5
