### ISSUE TITLE
PayPal Express Checkout "Display on Shopping Cart  -> NO" does not work in Magento 2.1.0

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#6073]
hi there,
we've got an issue with the PayPal Express Checkout after upgrading Magento from 2.0.7 to **2.1.0**
Software version: 5.6.28-76.1 - Percona Server (GPL), Release 76.1, Revision 5759e76
Database client version: libmysql - 5.5.45-37.4
www.giustoacquisto.com
### Steps to reproduce

1) Payments methods -> PayPal Express Checkout -> Enable this solution (works fine)
2) set "Display on Product Details Page -> NO" (woks as expected: the button does not appear anymore on the product detail page)
3) set "Display on Shopping Cart (Also affects mini-shopping cart)" -> NO  
IMPORTANT: step 3 DOES NOT work as expected: Express Checkout button still appears in the cart and in the mini cart: it shouldn't after step 3 settings have been applied.

Note: cache has been cleared -> yes
Note: it works as expected in Magento 2.0.7

thanks,
romeo

**Comment by dapdx** [comment]
Yah, same behavior for me. Not able to get rid of the button on the cart or minicart on 2.1

**Comment by dyushkin** [comment]
@romeof1980 Thanks for reporting this issue.
We've created internal ticket MAGETWO-56745 to fix it.

**Comment by alena-marchenko** [comment]
Hi @romeof1980 

Fix for MAGETWO-56745 ticket is already merged to develop branch.
Closing the issue, please feel free to reopen if the issue still reproducible for you.

**Comment by erfanimani** [comment]
It's still not working in CE 2.1.3

**Comment by zsoerenm** [comment]
+1

**Comment by Jacob-Wilsons** [comment]
Hello, 

I can confirm that this bug is still present in Magento 2.1.3.

It is exactly as described above.

**Comment by ctadlock** [comment]
@alena-marchenko Please reopen this issue

**Comment by mpont91** [comment]
same here with 2.1.3 impossible to remove this button. Also on view cart

**Comment by twistedatrocity** [comment]
Not working in CE 2.1.5

**Comment by twistedatrocity** [comment]
@alena-marchenko What exactly is the fix? Point us to a commit associated with this so we can at least manually patch our release installs.

**Comment by twistedatrocity** [comment]
@dyushkin I manually applied https://github.com/magento/magento2/commit/b4b721444be8c6257d64059b3b0b5d0f1fb1466b to my 2.1.5 and it fixes half the problem. The button is finally gone from the cart however the minicart popup is still not honoring the setting and showing the button.

**Comment by zsoerenm** [comment]
I had the same problem some time ago. It did however vanish by its own after a while. It was probably a cache problem. Try to clear all caches and check again.
Edit: Also clear the browser cache: Strg + F5

**Comment by twistedatrocity** [comment]
@zsoerenm You're right, I tried a different browser and it's no longer showing. Chrome doesn't like to let go even on a shift-reload it seems. Thank you!

**Comment by twistedatrocity** [comment]
While the button may be gone, the paypal JS is still being loaded on every page. I'm assuming because of the minicart and this fix not addressing the JS injection. How do we make it so the paypal JS only loads on checkout page with the button where it's only needed? I don't want this JS loaded on every page and firing events on mouse movements or clicks.

**Comment by erfanimani** [comment]
@twistedatrocity The minicart contents might even be a localstorage thing, so you would need to reset your session to refresh the top right minicart.

JS loading on every page is annoying.. It's not even minified/compressed and Pagespeed insights is complaining about it..

**Comment by twistedatrocity** [comment]
@erfanimani Yeah it's not a browser thing. It's placing markup right before the page-wrapper, just after the google analytic block, on every page, it's also loaded up in requirejs-config.js. I have even disabled the minicart entirely and it still insists on injecting this into every page on the site. The only way to get rid of it is to disable paypal entirely, however my client has a need for paypal checkout.

```
require.config(config);
})();
(function() {
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

var config = {
    map: {
        '*': {
            orderReview:            'Magento_Paypal/order-review',
            paypalCheckout:         'Magento_Paypal/js/paypal-checkout'
        }
    },
    paths: {
        paypalInContextExpressCheckout: 'https://www.paypalobjects.com/api/checkout'
    },
    shim: {
        paypalInContextExpressCheckout: {
            exports: 'paypal'
        }
    }
};
```

html markup:

```
<div style="display: none;" id="paypal-express-in-context-checkout-main"></div>
<script type="text/x-magento-init">
    {"*":{"Magento_Paypal\/js\/in-context\/express-checkout":{"id":"paypal-express-in-context-checkout-main","path":"https:\/\/www.redacted.com\/paypal\/express\/gettoken\/","merchantId":"redacted","button":true,"clientConfig":{"locale":"en_US","environment":"production","button":["paypal-express-in-context-checkout-main"]}}}}</script>
```

and again further down the page it's mixed in this snippet with other things, which btw some of those other things are not even enabled... eg braintree, authorize.net:

```
<script type="text/x-magento-init">
{"*":{"Magento_Customer\/js\/section-config":{"sections":{"stores\/store\/switch":"*","directory\/currency\/switch":"*","*":["messages"],"customer\/account\/logout":"*","customer\/account\/loginpost":"*","customer\/account\/createpost":"*","customer\/ajax\/login":["checkout-data","cart"],"catalog\/product_compare\/add":["compare-products"],"catalog\/product_compare\/remove":["compare-products"],"catalog\/product_compare\/clear":["compare-products"],"sales\/guest\/reorder":["cart"],"sales\/order\/reorder":["cart"],"checkout\/cart\/add":["cart"],"checkout\/cart\/delete":["cart"],"checkout\/cart\/updatepost":["cart"],"checkout\/cart\/updateitemoptions":["cart"],"checkout\/cart\/couponpost":["cart"],"checkout\/cart\/estimatepost":["cart"],"checkout\/cart\/estimateupdatepost":["cart"],"checkout\/onepage\/saveorder":["cart","checkout-data","last-ordered-items"],"checkout\/sidebar\/removeitem":["cart"],"checkout\/sidebar\/updateitemqty":["cart"],"rest\/*\/v1\/carts\/*\/payment-information":["cart","checkout-data","last-ordered-items"],"rest\/*\/v1\/guest-carts\/*\/payment-information":["cart","checkout-data"],"rest\/*\/v1\/guest-carts\/*\/selected-payment-method":["cart","checkout-data"],"rest\/*\/v1\/carts\/*\/selected-payment-method":["cart","checkout-data"],"multishipping\/checkout\/overviewpost":["cart"],"authorizenet\/directpost_payment\/place":["cart","checkout-data"],"review\/product\/post":["review"],"paypal\/express\/placeorder":["cart","checkout-data"],"paypal\/payflowexpress\/placeorder":["cart","checkout-data"],"braintree\/paypal\/placeorder":["cart","checkout-data"],"wishlist\/index\/add":["wishlist"],"wishlist\/index\/remove":["wishlist"],"wishlist\/index\/updateitemoptions":["wishlist"],"wishlist\/index\/update":["wishlist"],"wishlist\/index\/cart":["wishlist","cart"],"wishlist\/index\/fromcart":["wishlist","cart"],"wishlist\/index\/allcart":["wishlist","cart"],"wishlist\/shared\/allcart":["wishlist","cart"],"wishlist\/shared\/cart":["cart"]},"clientSideSections":["checkout-data"],"baseUrls":["https:\/\/www.redacted.com\/"]}}}</script>
```

I believe this is what is causing paypals checkout.js to be loaded on every page, which btw is loading directly from paypal.com. It then fires off an api logger that is tracking mouse movement. I counted half a dozen POSTS to paypal.com on a single page load. If I click any link on my site it fires off two POSTS just before the browser loads the new link.

This is a performance issue as well as a privacy issue. I do not want a third party collecting metrics like this without my explicit consent and control.

As a sidenote, in the headers being transacted in these logger POSTS, there is an X-Recruit (sp) header that says "If you can read this maybe you should work for paypal". Um, no thanks.

**Comment by sadeeshmca** [comment]
It's still not working in CE 2.1.6

**Comment by r-martins** [comment]
The same looks to happen on Website Payments Standard.
Express checkout button appears on minicart, even when Website Payments Standard is enabled and Express checkout disabled.
v. 2.1.2 EE

**Comment by isacsg** [comment]
It's still not working in CE 2.1.6 ²

**Comment by phuongnd** [comment]
@alena-marchenko It's still NOT working in CE 2.1.8

**Comment by BenGlassAtlas** [comment]
It's rather disappointing how this was first missed, then the fix doesn't work, and it's now been over a year with no fix.

**Comment by twistedatrocity** [comment]
Still an issue in 2.1.9. Also the prior commit https://github.com/magento/magento2/commit/b4b721444be8c6257d64059b3b0b5d0f1fb1466b  that fixes part of the problem is not in 2.1.9 either.

**Comment by BenGlassAtlas** [comment]
How long will this go on for 😱  I can see it now:

"Still an issue is Magento 4.3.12"

**Comment by raymond62** [comment]
PayPal Express Button shown on Product Page although disabled

Preconditions: Magento 2.2.3., PHP 7.0, MySql 5.6

Expected result: No PP Express Button

![grafik](https://user-images.githubusercontent.com/29265078/39299485-16b5e932-4949-11e8-9837-59207adee369.png)

**Comment by JRhyne** [comment]
This is still an issue in Commerce 2.2.5

**Comment by Ctucker9233** [comment]
@JRhyne It appears to be fixed in 2.2.6. If you can confirm, this issue can be closed.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
This issue is fixed on 2.3.0.

**Comment by tillemann98** [comment]
This issue is still not fixed. 
Magento 2.3.1

**Comment by Clud7** [comment]
Any update about that issue?

**Comment by ghost** [comment]
@engcom-backlog-tomash  

Issue is certainly not fixed, and we see it in 2.3.1. OSE

**Comment by BenGlassAtlas** [comment]
@satellite1 @Clud7 @tillemann98 Can you re-produce the error on a vanilla instance of 2.3.x?

**Comment by Clud7** [comment]
Hello @BenSpace48 , the trick here is to disable the In-Context Checkout Exprerience. If you enable that then the Display on Shopping Cart and every option to hide the Paypal untill the Checkout doesn't work.

https://i.imgur.com/v4ZMGut.png

**Comment by vitmarks** [comment]
this is still an issue on 2.3.4
Cannot disable paypal buttons on mini-cart

**Comment by johncarlson21** [comment]
Something needs to be done with this to be able to remove the in-context loading on every page.
I shouldn't have to go into every section and add an xml layout update to remove it
Maybe I'm missing something. I'm using the mini-cart in the menu, but I'm not loading the buttons.
