### ISSUE TITLE
Catalog Prices including tax

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#6074]
### Preconditions

1. Magento 2.1.0
2. PHP 5.6.22-0+deb8u1
### Steps to reproduce

1. Add product. Set all data.
2. in configuration Set "Catalog Prices" to "Including tax", and all other settings to "including tax" too.
   ![4](https://cloud.githubusercontent.com/assets/884525/17517187/e2cb1a1a-5e4a-11e6-83a4-892905360d64.png)
### Expected result

1.  Product price in catalog should display same as in admin. F.e. test product: in admin price set to 1000 Euro (incl. tax). On product page it should display 1000 Euro too.
### Actual result

1. On product page it adds tax over product price. (like in admin product price entered excl. tax)
   ![5](https://cloud.githubusercontent.com/assets/884525/17517264/4b341afc-5e4b-11e6-982a-8637fc0a36e0.png)
   ![6](https://cloud.githubusercontent.com/assets/884525/17517265/4b372e86-5e4b-11e6-83d2-2edc15b6130c.png)

**Comment by oserediuk** [comment]
Hello @Styopchik ! Do you try to clear cache?

**Comment by Styopchik** [comment]
Cache is disabled

9 Авг 2016 г. 18:56 пользователь "Oleksii Serediuk" <
notifications@github.com> написал:

**Comment by oserediuk** [comment]
It is strange, I could not reproduce this case on the fresh installation Magento 2.1

**Comment by oserediuk** [comment]
Thanks for the report! We've created internal ticket MAGETWO-56751 to fix it.

**Comment by choukalos** [comment]
It's not clear this is a bug.

What's your shipping origin set for that website/store view?  Is it set to Germany just like the default tax calculation setting?  Is there a tax rule/rate that's non-zero and applies?  Can you confirm?
