### ISSUE TITLE
Size not appearing on listing Page 

### ISSUE THREAD

**Issue by renu2jcommerce** [magento/magento2#6075]
Hi,
For Size Attribute 
We set Catalog Input Type for Store Owner set as DropDown ,We found sizes are  in dropdown on product page , but no sizes has appearing on listing page
Is there any setting for this ?

Thanks
Renu

**Comment by andimov** [comment]
@renu2jcommerce 
Thanks for reporting. 
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by renu2jcommerce** [comment]
Hi Andimov,

I am working on Community Version 2.0.7 

 We need to show the sizes in dropdown hence we made the changes accordingly in admin.
  we set Catalog Input Type for Store Owner set as DropDown
Result :Size attribute not appearing on listing page 

Expected Result :
Need the swatch size on listing page

**Comment by AVoskoboinikov** [comment]
Hi. @renu2jcommerce 

Could you please look at this issue https://github.com/magento/magento2/issues/6099 ? It seams that you have the same problem with configuration. Try to use example from that issue, it should help you.

**Comment by renu2jcommerce** [comment]
Hi,
I have gone through this solution ,i tired but if size is selected as dropdown it is not working .
can you please look into this again ?

Thanks

**Comment by AVoskoboinikov** [comment]
Hi @renu2jcommerce 

Unfortunately we have no such option. We can't show dropdowns on product listing, only swatches. 
I will close this issue then. Feel free to reopen it or create any new issues if you still have questions.
