### ISSUE TITLE
Segmentation fault (core dumped) in PHP7.0.8

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#6077]
I'm experiencing a similar issue to this https://github.com/magento/magento2/issues/2880 on php version 7.0.8 with a CE installation of Magento 2.1

php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.                                                                                                                    0 MiBPHP Fatal error:  Class 'Magento\Braintree\Controller\Paypal\AbstractAction'                                                                                                                     not found in /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/ma                                                                                                                    gento/module-braintree/Controller/PayPal/PlaceOrder.php on line 18
Segmentation fault

Can anyone offer any help? This is preventing me from successfully setting the mode to production on our server.

Thanks,

Sophie

**Comment by piotrekkaminski** [comment]
@sma09sjb did you tried clearing all your cached files manually first?

**Comment by sma09sjb** [comment]
Hello,

Yes i tried clearing the following directories:

```
var/cache
var/di
var/generation
var/view_preprocessed
pub/static
```

**Comment by YevSent** [comment]
Hi @sma09sjb.

The `vendor/magento/module-braintree/Controller/PayPal/PlaceOrder.php` it's not correct path, should be `vendor/magento/module-braintree/Controller/Paypal/PlaceOrder.php`. Try to clear vendor path, composer cache and run composer update again.

Which OS do you use?

**Comment by sma09sjb** [comment]
Hi i've changed the file name and i'm now able to run the compile command, however i'm now having issues deploying static content.

I'm trying to switch to production mode

```
bin/magento setup:upgrade

bin/magento indexer:reindex

bin/magento deploy:mode:set production -s

bin/magento setup:di:compile 

bin/magento setup:static-content:deploy
```

The final command throws the following error, and as a consequence non of the css/js is loaded, the site is unstyled.

```
Uncaught Error: Class 'Magento\Indexer\Model\Config\Reader' not found in /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#1 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Indexer...')
#2 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/app/code/Manadev/Core/Registries/ConfigurationReaders.php(32): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Indexer...')
#3 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Manadev\Core\Registries\ConfigurationReaders->__co in /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
```

 I'm not sure what i'm doing wrong here?

**Comment by YevSent** [comment]
Hi @sma09sjb, please, create separate Github issue, because new problem not related to the original problem.

Close this issue as solved, please, be free to reopen it.
