### ISSUE TITLE
Product collection final price for configurables is 0

### ISSUE THREAD

**Issue by bjoern-quast** [magento/magento2#6080]
### Preconditions
1. Magento CE 2.1.0 without sample data is installed.
### Steps to reproduce
1. Add a configurable product with the price 0
2. Add simples to the configurable with their prices
3. Get a product collection with the configurable, e.g. _getProductCollection() in \Magento\Catalog\Block\Product\ListProduct
### Expected result

Final price for our configurable is based on the simples's prices 
### Actual result

Final price for the configurable is 0

The collection joins the table catalog_product_index_price, where the respective rows for the configurable hold the value 0 for columns `price` and `final_price`.
Reindexing doesn't help.

**Comment by magento-engcom-team** [comment]
@bjoern-quast, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
