### ISSUE TITLE
Table Rate: whatever weight I choose (Magento 2.1) displays the lowest !

### ISSUE THREAD

**Issue by Whaaaaat** [magento/magento2#6084]
This is my CSV file:

`Country    Region/State    Zip/Postal Code Weight (and above)  Shipping Price

GBR \*   \*   0   25
GBR \*   \*   1   33
GBR \*   \*   2   42
GBR \*   \*   3   50
GBR \*   \*   4   58
GBR \*   \*   5   95
GBR \*   \*   6   105
GBR \*   \*   7   113
GBR \*   \*   8   124
GBR \*   \*   9   133
GBR \*   \*   10  138
GBR \*   \*   11  141
GBR \*   \*   12  145
GBR \*   \*   13  151
USA \*   \*   0   30
USA \*   \*   1   43
USA \*   \*   2   53
USA \*   \*   3   66
USA \*   \*   4   78
USA \*   \*   5   102
USA \*   \*   6   112
USA \*   \*   7   122
USA \*   \*   8   133
USA \*   \*   9   144
USA \*   \*   10  153
USA \*   \*   11  163
USA \*   \*   12  173
USA \*   \*   13  183
`

after importing the file, whatever weight I choose, Magento 2.1 shows the lowest rate...  for example, if the product's weight is [3] and I'm buying from USA, Magento always shows the rate [30]!!!!

**Comment by oserediuk** [comment]
Hello @Whaaaaat ! Where does Magento show this rate? Also, please, provide setting of buying product, checkout method etc.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
