### ISSUE TITLE
Admin WYSIWYG editor link opens media popup

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6086]
### Preconditions

1. Magento 2.1
### Steps to reproduce

1. In editor toolbar click 'Insert/Edit Link' button to set a link for an object
2. Click 'Link Url' browse button
### Expected result

1. May be opens link like Widgets popup which we can select cms pages, links etc.
### Actual result

1. Opens Media popup

**Comment by sevos1984** [comment]
This is desired behavior. For cms pages you should use cms page link widget, product link widget for products etc.

**Comment by cizgidekiadam** [comment]
http://prntscr.com/clulvj - I want to add a link to any object (text, image etc..)
http://prntscr.com/clum9e - Link popup opens as expected
http://prntscr.com/clumw9 - Instead of media popup, it 'can' be link widget (cms page, product, account etc...)

It is just an advice, not a big deal.
I'm trying to tell like this :)
