### ISSUE TITLE
Can't use an admin configurable product page when many simple associated

### ISSUE THREAD

**Issue by f-gueguen** [magento/magento2#6087]
Hello,

I use magento 2.1, maria db 10.1.14, nginx 1.11.2, varnish 4.1, php 7.0.7 with an architecture nginx http2->varnish->nginx->magento

I have a store where I need to have hundreds of simple products associated to some configurable products (I sell sofa, you can change some colors, corner side, material, etc, and I need a stock per variation, so I have to use the configurable). The fact is I understand it's pretty long to generate the simple products, but then each time I need to edit the configurable, it loads and save the list of simple products, which sometimes breaks my page and takes forever.
Would it be possible to have the "simple product" part of the page loaded only when needed?
Same scenario, would it be possible to change the attributes to select order without loading the simple product list itself, as we could do in Magento 1? It's not possible to change this order by csv if I'm right.

Thank you for your time and for this wonderful tool :)

François

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Can-t-use-an-admin-configurable-product-page-when-many-simple/idi-p/45007).
