### ISSUE TITLE
Customize Product creation form Not Working.

### ISSUE THREAD

**Issue by juanmrad** [magento/magento2#6089]
### Preconditions
Magento 2.1.0 

### Steps to reproduce
I Created a Custom module and I need to disable some fieldsets on the product creation form.

I followed the guide : http://devdocs.magento.com/guides/v2.1/howdoi/customize_product.html

and Created my product_form.xml file like this:

```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <modal name="advanced_inventory_modal">
        <fieldset name="stock_data">
            <field name="qty">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="imports" xsi:type="array">
                        <item name="readonly" xsi:type="string">readonly</item>
                    </item>
                </item>
            </argument>
            </field>
        </fieldset> 

        <container name="container_is_in_stock">
            <argument name="data" xsi:type="array">
                        <item name="visible" xsi:type="string">false</item>
            </argument>
        </container>
    </modal>
</form>
```

I've tried several different ways even using the `<item name="disabled" xsi:type="boolean">true</item>` and it doesn't work.

I need to hide the option to add a product qty and to also say if the item is out of stock or in stock since this is handled in a separate module I created.

I'm running Magento 2.1.0 on a Nginx server. Is a clean build Only has my custom module.
### Expected result

1. Disable or hide qty fieldset and in stock fieldset.
### Actual result

1. Nothing happens.

**Comment by magento-engcom-team** [comment]
@juanmrad , thank you for your report. 
Actually you are trying to change advanced_inventory_modal - this modal window for advanced inventory.
As we understood, you needed to change fields on product form. Please, look Magento\CatalogInventory\Ui\DataProvider\Product\Form\Modifier\AdvancedInventory::modifyMeta().

**Comment by magento-engcom-team** [comment]
@juanmrad, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
