### ISSUE TITLE
Front-end performance optimization

### ISSUE THREAD

**Issue by nodkrot** [magento/magento2#609]
Most JS should move at the end of the body.
JS/CSS should be concatenated to one file and uglified with deployment versioning.
If possible optimize/compress the images. Minify HTML.

Consider using grunt and bower.

Also update the google analytics to the Universal one.

These featured should be at the core level. I went through many plugins that try to help with that for Magento 1, they all cause issues with the website.

**Comment by maksek** [comment]
@nodkrot Closing ticket due long inactivity from creator. Feel free to reopen if there is open question.
