### ISSUE TITLE
Configurable products id vs code in API routes

### ISSUE THREAD

**Issue by petersg83** [magento/magento2#6094]
I've spent hours struggling to find how I can have the **attribute_code** from the **attribute_id** in order to use this route : `GET /V1/products/attributes/{attributeCode}/options`
For exemple the **attribute_code** is "color" and the **attribute_id** is "93".

It finally appears that putting the **attribute_id** instead of the **attribute_code** in the route works. It is not suggested by the documentation at all. Please precise in your documentation when it is possible to put different values for a route parameter so no one else lose so much time on it. It's really misleading.

Documentation's here: http://devdocs.magento.com/swagger/index.html

**Comment by mbrinton01** [comment]
Hello @petersg83, please let us know what version you are using. I'm using the `develop` branch and am not able to reproduce this issue.  Steps:
1. Get admin token
   `POST http://<hostname>/index.php/rest/V1/integration/admin/token`
   with body of `{"username":"admin", "password":"<password>"}`
   Result should be admin token
2. Get attribute options
   `GET http://<hostname>/index.php/rest/V1/products/attributes/color/options`
   with header of `Authorization = bearer <token from step 1>`
   Result should be the options for the `color` attribute:

```
[
  {
    "label": " ",
    "value": ""
  },
  {
    "label": "Black",
    "value": "49"
  },
  {
    "label": "Blue",
    "value": "50"
  },
  {
    "label": "Brown",
    "value": "51"
  },
  {
    "label": "Gray",
    "value": "52"
  },
  {
    "label": "Green",
    "value": "53"
  },
  {
    "label": "Lavender",
    "value": "54"
  },
  {
    "label": "Multi",
    "value": "55"
  },
  {
    "label": "Orange",
    "value": "56"
  },
  {
    "label": "Purple",
    "value": "57"
  },
  {
    "label": "Red",
    "value": "58"
  },
  {
    "label": "White",
    "value": "59"
  },
  {
    "label": "Yellow",
    "value": "60"
  }
]
```

I see `{attributeCode}` in both Swagger and the Admin Panel:

<img width="436" alt="screen shot 2016-09-20 at 6 14 45 pm" src="https://cloud.githubusercontent.com/assets/10635536/18692226/6960965c-7f5e-11e6-91cb-a25630257606.png">

<img width="235" alt="screen shot 2016-09-20 at 6 15 07 pm" src="https://cloud.githubusercontent.com/assets/10635536/18692227/6961efa2-7f5e-11e6-96fc-a4839ebc999f.png">

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
