### ISSUE TITLE
magento 2 configurable product dropdown products changes related products value

### ISSUE THREAD

**Issue by viken-tops** [magento/magento2#6097]
![related_product](https://cloud.githubusercontent.com/assets/20060851/17551282/c632870e-5f16-11e6-8d35-5b1a1765d0bf.png)

in magneto 2.1.0 configurable products have dropdown products & same prdoucts in related products.
while i am change dropdown products it changes prices in related products block too. which is weird.

please help me out. as i am in deep trouble now.

thanks

**Comment by veloraven** [comment]
@viken-tops thank you for your report.
We already have internal ticket MAGETWO-53135 as this issue is described #5798 and #6041.
I have added a link to this issue as well from the internal one.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.
