### ISSUE TITLE
Admin dashboard Most Viewed Products Tab statistics not updating

### ISSUE THREAD

**Issue by praful-rajput** [magento/magento2#6098]
Most Viewed Products tab records not being updating while visit to many products with guest user or even registered user.
### Preconditions

We are using Magento CE 2.1.0 with sample data.
### Steps to reproduce
1. Logged in admin panel.
2. Go to "Most Viewed Products" tab just under graph.
### Expected result

It should update the viewed products
### Actual result

It's showing message "We couldn't find any records."
![most-viewed](https://cloud.githubusercontent.com/assets/648859/17551734/6a6b61c2-5f19-11e6-9279-af45c9ecc0e5.png)

**Comment by picamator** [comment]
@vasuscoin thank you for reporting issue.
We already have internal ticket MAGETWO-46160 in our backlog.

**Comment by apurv-anand** [comment]
+1 
Please fix

**Comment by technoquo** [comment]
same I have a issue about Most Viewed Products tab records not being updating while visit to many products with guest user or even registered user. Please help me this issue..

**Comment by magento-engcom-team** [comment]
@vasuscoin, thank you for your report.
We've created internal ticket(s) MAGETWO-46160 to track progress on the issue.

**Comment by osrecio** [comment]
investigating to try fix the issue

**Comment by duongquyet** [comment]
Hi,
I have a same problem.

**Comment by osrecio** [comment]
This problem was solved and is available in 2.2.2: https://github.com/magento/magento2/pull/12139

**Comment by VikasSingh1694** [comment]
I am facing the same issue.

**Comment by rabraga** [comment]
here is also an error in 2.4.1, in the amount of revenue value
