### ISSUE TITLE
Magento 2.1.0 - No Color Swatches at product list item

### ISSUE THREAD

**Issue by abubner** [magento/magento2#6099]
### Preconditions

1. Magento 2.1.0
2. PHP 7
3. MySQL 5.7
4. Apache 2
### Steps to reproduce

1. As follow:
2. We checkout fresh sources from git repo
3. We switch to 2.1 ( git checkout 2.1.0 )
4. We install with composer install
5. We install all node_modules
6. We activate all gulp features
7. We finish the installation with the webfrontend successfully
8. We log in and verything seems fine
9. We switch to developer mode and adjust the directories for this
10. We add 2 configurable attributes ( color_bettwaesche and size_bettwaesche)
11. Now we reindex
12. We add categories
13. We add 2 products one simple and one configurable product with its variants ( color_bettwaesche and size_bettwaesche)
14. We go to the frontend and navigate to the product list
15. We see the color_bettwaesche  attribute on filter container, but we do not see the color swatch at the configurable product
16. We navigate to the pds from the conf. product and see the color swatches!
### Expected result

1. We understand, that "if enabled by add the attribute" that we should see the swatches UNDER each possible config. product ( the result from its values ) on the product list. This do not work!
### Actual result

![swatch-frontend01](https://cloud.githubusercontent.com/assets/4447556/17552823/8d5b3386-5f02-11e6-9d30-05637ca1eb78.png)
![swatch01](https://cloud.githubusercontent.com/assets/4447556/17552824/8d5c0414-5f02-11e6-8cf0-2b4af3bd3788.png)
![swatch02](https://cloud.githubusercontent.com/assets/4447556/17552822/8d582808-5f02-11e6-893d-f1238e6d3b45.png)
![swatch-frontend02-pds](https://cloud.githubusercontent.com/assets/4447556/17553016/b8c3d978-5f03-11e6-99b0-8969c0bcf72f.png)

Is this a known bug? - What we have to do, to solve this ?

Thanks
Andre

**Comment by AVoskoboinikov** [comment]
Hello, Andre
Could you please try the same configuration on attribute as is described on Pic 1? After using it you should able to see your swatch at the configurable product.

Looking forward to hearing from you if it helps.
Thanks

Pic 1
![pic1](https://cloud.githubusercontent.com/assets/17980272/17771357/2ef4ef54-654b-11e6-91d7-3c26174312fb.png)

**Comment by AVoskoboinikov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
We will close this issue as not updated more than 2 weeks if this issue still reproducible please feel free to create the new one.

**Comment by gediminaskv** [comment]
@AzVo Your solution didn't help:/ Can you check my situation https://magento.stackexchange.com/questions/198740/swatches-in-product-list-issue-magento-2 ?
