### ISSUE TITLE
IE8 is not supported

### ISSUE THREAD

**Issue by woei66** [magento/magento2#6100]
### Preconditions

1. magento 2.0.8
2. php7.0
3. IE8
### Steps to reproduce

1. install magento 2.0.8
2. open IE 8 browser and view the homepage
3. it will display incorrect like a mobile style
### Expected result

1. correct product display of homepage
### Actual result

1. [Screenshot, logs]
   ![2016-08-10 9 09 20](https://cloud.githubusercontent.com/assets/5770807/17554701/c2bfd36a-5f3e-11e6-975a-85bdca1e326d.png)

I got a workaround solution is modify the vendor/magento/module-theme/view/base/templates/root.phtml file and add below lines

![2016-08-10 9 03 29](https://cloud.githubusercontent.com/assets/5770807/17554608/4447f5bc-5f3e-11e6-9ad2-a2c6fe0ea0b4.png)

**Comment by hostep** [comment]
http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html

**Comment by davidalger** [comment]
@woei66 IE8 is an unsupported browser. Closing.
