### ISSUE TITLE
Unclear how to install an extension using 2.1.

### ISSUE THREAD

**Issue by hickscorp** [magento/magento2#6102]
We are trying to understand how Magento works, as we developed a Shopify extension that registers itself for callbacks to our API and want to port it to Magento (Products and Orders CRUD callbacks). We therefore decided to install an instance of Magento as we were clueless in front of all the contradictory information we found on the web.

We're using Magento 2.1.0 via a docker-compose playbook. The Serup is automatically done for us. We are trying to get [this extension](https://www.magentocommerce.com/magento-connect/web-hook.html) to install as a starting point for us to understand how things work.

As far as we understand, we would have to develop an "Extension" for Magento allowing our API to register itself as an endpoint to receive CRUD events for Orders / Products.

There is nowhere to install extensions in our setup. The admin panel doesn't show any "Component Manager" as the docs suggest. When going to "System", there is really nothing usefull.

How do you get support for things like this? How do you install an extension? Up to date documentation? Clear procedures about how things work, what versions are supported, etc?

**Comment by rickwhitehead** [comment]
@hickscorp have you visited `system->Web Setup Wizard`? to find the Component Manager?
![image](https://cloud.githubusercontent.com/assets/19778455/17555945/6d8072d6-5f09-11e6-96b3-1ebfb808a1ad.png)

**Comment by hickscorp** [comment]
@rickwhitehead Thanks for helping. We have no such thing as "Web Setup Wizard" in the "System" tab...

**Comment by rickwhitehead** [comment]
@hickscorp Can I suggest you provide some system info e.g. OS details + Mag version CE/EE, plus how you installed, whether you're in default/developer/production mode etc, and screen-grabs as necessary to help others help you?

**Comment by hickscorp** [comment]
I don't want to polute my system with PHP and friends, so I'm using docker. There is a setup container that takes care of everything for me, using Mag 2.1.0.

[Here is a screenie](http://i.imgur.com/qKdq1mo.png) of the end result. I basically started from a docker compose and a set of images provided by this [dude](https://github.com/mageinferno/magento2-docker-compose), as we initially didn't want to put too much man/hour on this task...

**Comment by rickwhitehead** [comment]
@hickscorp I suggest you remove this issue from here as it's not relevant and instead repost it with: [your dude at mageinferno](https://github.com/mageinferno/magento2-docker-compose/issues), as this issue queue is for pure Mag2 installs not somebody else's docker version

**Comment by hickscorp** [comment]
@rickwhitehead Thanks.
