### ISSUE TITLE
Product image not showed on product page when using a custom page layout

### ISSUE THREAD

**Issue by dangelion** [magento/magento2#6103]
I'm creating a custom theme on Magento 2.1. I create a custom layout for the product page in `app/design/frontend/<theme_name>/base/Magento_Catalog/layout/catalog_product_view.xml`, here it is:

```
<?xml version="1.0"?>

<page layout="layout-1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

  <body> 
  </body>

</page>
```

where `layout-1` is

```
<?xml version="1.0"?>

<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">

  <update handle="1column"/>

</layout>
```

The problem is that when I navigate to a product page the product image/gallery is not displayed. 

If I set `catalog_product_view.xml` with `layout="1column"` all works right.

Someone can confirm this is a bug? Thanks

---

Below some screenshots:

**With layout `1column` ==> Product image is showed**
[![Product image](http://i.stack.imgur.com/1xrKS.png)](http://i.stack.imgur.com/1xrKS.png)

**With layout `layout-1` ==> Product image is missing**
[![Image missing](http://i.stack.imgur.com/uOxOI.png)](http://i.stack.imgur.com/uOxOI.png)

**Comment by nobuttsalex** [comment]
Having the same issue in 2.1.7, is there are workaround for the time being?

**Comment by magento-engcom-team** [comment]
@dangelion, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by vrej** [comment]
I am having the same issue in 2.2  did anyone found any solution for this?

**Comment by babyasishhira** [comment]
I am also having same issue

**Comment by prabhasunyscape** [comment]
Have any one get fixed this issue ?
