### ISSUE TITLE
URLS with parameters o Woo-commerce does not redirect on Magento 2.1

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6105]
Using Magento 2.1 CE
Woo Commerce URLS mapped to Magento 2 product urls  as 301.
They do not redirect to target path instead to home page.
Format /?product_cat=mat-de-yaar to /examplexyz/abc - Home page - error
If format like /new to /exampleabc - Goes to target path.

**Comment by nigelcopley** [comment]
how are you redirecting the urls?

**Comment by nmallepally** [comment]
@caleoroco I tried redirecting from Admin->Marketing->URL rewrites -> Custom URL ->301
I also did a import onto database table url_rewrite according to the fields specified.
Neither of them works
![db url](https://cloud.githubusercontent.com/assets/19605497/17589498/13293dd0-5fcd-11e6-81e7-fd359142a6fb.png)
![url error](https://cloud.githubusercontent.com/assets/19605497/17589502/1921b6d6-5fcd-11e6-815b-5a1a76afba2f.png)

**Comment by nigelcopley** [comment]
Personally i would never use magento to try and redirect external url's

have you tried using your htaccess file to 301 redirect?

**Comment by piotrekkaminski** [comment]
@nmallepally @caleoroco for larger number of rewrites it's highly recommended to use .htaccess or similar way for your web server. It will be faster/less load on Magento. And do 301 redirects to make sure search engines update their indexes. Magento rewrites system was not designed to work with paremeters.

**Comment by dimple-vasoya** [comment]
Facing the same issue. Redirect is not working if parameters present in request path.
What can be done to achieve this?

**Comment by nigelcopley** [comment]
Use htaccess to rewrite url's

**Comment by nmallepally** [comment]
@caleoroco Thanks, worked on htaccess.
