### ISSUE TITLE
Reset password error on magento 2.1 CE 

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6109]
Updated from 2.0.7 to 2.1 CE
2.1CE from developer mode to Production mode successfully
Imported customers list into Admin -> imports ->customer accounts
Reset password for imported customer account
We cannot send email now
![email error](https://cloud.githubusercontent.com/assets/19605497/17574203/2c809f38-5f57-11e6-996b-92e5fca804e4.png)

**Comment by picamator** [comment]
@nmallepally  Thanks for reporting.

Unfortunately we can not reproduce this issue.
1. Could you please put a sample of your import file with fake data?
2. Do you have any connected errors in your log files? If you have please put that information as well.
3. Do you choose "Customers Main File" during import?
4. How do you generate customer import file?

**Comment by nmallepally** [comment]
HI @picamator 
I have attached the file which shows errors on system log file.
I chose customer and address file to import customers.
It works fine when i choose customer mail file without address.
[customer error.txt](https://github.com/magento/magento2/files/456807/customer.error.txt)
[sample content.xlsx](https://github.com/magento/magento2/files/456814/sample.content.xlsx)

**Comment by picamator** [comment]
@nmallepally Thank you for files. It's extremely helpful. We have managed to reproduce issue.
It turns out that the problem is with required "State/Province" for Customer.
We have created internal ticket MAGETWO-58189 to fix it.

**Comment by magento-engcom-team** [comment]
@nmallepally, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
