### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by waynetheisinger** [magento/magento2#611]
Hi Guys, (apologies if this has been raised before but I can't find it anywhere) presumably as you are developing you've got some sample products, categories and media that you work with? Can you put the data somewhere we can grab it from?

**Comment by htollefsen** [comment]
I were unable to get SampleData to work on 0.74.0-beta2 but were able to locate some performance scripts that provide some samples.

```
cd dev/tools/performance-toolkit && php generate.php --profile profiles/ce/small.xml && cd -
```
You may change small.xml with larges profiles if you want, eq: extra_large.xml, large.xml or medium.xml.
