### ISSUE TITLE
addCategoryFilter root category doesn't work on root category

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#6110]
When i filter with categories not root category, It work fine. But when i try filter with root category, it doesn't work. Please fix it.

Here my code:
$id = $this->_storeManager->getStore()->getRootCategoryId();
$_category = $this->_categoryFactory->create()->load($id);

$collection = $this->_productCollectionFactory->create()->addCategoryFilter($_category);

I use "\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory" for colection and magento 2.0.6.

**Comment by paales** [comment]
This is because all products are added to the root of the shop. The product-category-association is joined by the index and alle the products are in the index.

So you have to apply a custom filter to your collection

``` PHP
$this->_productCollection = $layer->getProductCollection();
if ($this->_storeManager->getStore()->getRootCategoryId() == $this->getCategoryId()) {
    $this->_productCollection->getSelect()->join(
        ['cp' => $this->_productCollection->getTable('catalog_category_product')],
        'e.entity_id = cp.product_id',
        ['product_id']
    );
}
```

**Comment by duongquyet** [comment]
Hi,
I don't think so. We don't see filter root category in your code. We have some root categories, not one.
We need filter products follow root categories, not all product.

Best regards,

PT Team

**Comment by veloraven** [comment]
@duongquyet please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
