### ISSUE TITLE
custom option price value can't be more than 1000

### ISSUE THREAD

**Issue by ladonenko** [magento/magento2#6116]
After saving product with custom option price value more than 1000.00 it is cut to 1.00.
It happens only after second save.

**Comment by veloraven** [comment]
@ladonenko thank you for your report.
Please, provide the used Magento version and information if it was clear install or update from some previous version.
Please also update description according to template: with steps, expected result and actual result.

**Comment by ladonenko** [comment]
magento version 2.1. installed from scratch
Steps for reproduce
- create configurable product
- create custom option, type = dropdown
- add couple values with price more that 1000 euro in my case
- save product, you will see actual price amount
- save product again and look at the custom option price value. in my case
  it is different and euqal 1euro
  if i enter original price 4000 it will 4.00

2016-08-15 15:27 GMT+03:00 Olga Moyseyenko notifications@github.com:

**Comment by katmoon** [comment]
Hi @ladonenko 

Thank you for reporting the issue. It is reported as `MAGETWO-56866` internally.

Thanks,
Kateryna.

**Comment by sdzhepa** [comment]
@ladonenko Fix for this issue was delivered to develop branch. Pls feel free to chech it in develop and reopen if need
- Fix for Magento 2.1 will be delivered late in scope of internal ticket `MAGETWO-58571`

**Comment by senders** [comment]
This patch seems to work fine in magento 2.1.5:

https://github.com/magento/magento2/commit/496c24d58a0624a865c78b5da63f138bd279ea01

But why it isn't still integrated in one of the latest magento versions 2.1.3, 2.1.4 or 2.1.5. ???
