### ISSUE TITLE
My installation is also a problem, I would like to ask who can help me

### ISSUE THREAD

**Issue by joanpeng** [magento/magento2#6124]
My virtual host is also encountered when installing the is incomplete. Installation
The console log for Check errors before trying again. I let the method on the Internet to modify but still did not solve this problem

![a1](https://cloud.githubusercontent.com/assets/20981529/17610837/b8b1be60-6074-11e6-992a-b4e3eb067f63.png)
![a2](https://cloud.githubusercontent.com/assets/20981529/17610839/b8b47a88-6074-11e6-9f54-a85909b32492.png)
![a3](https://cloud.githubusercontent.com/assets/20981529/17610838/b8b27f30-6074-11e6-85eb-6d5c9cf0e2be.png)

**Comment by palamar** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): 
- with steps to reproduce
- actual result 
- expected result

Also please check <Magento root>/var/report for error logs, it can contain more information about possible problem.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
