### ISSUE TITLE
Checkout with Braintree does not work if shipping is not required

### ISSUE THREAD

**Issue by hummerh2** [magento/magento2#6125]
Ubuntu, PHP 7.0.9, Magento 2.1

When checking out with a product that does not have shipping with the Braintree Payment method returns "the server responded with a status of 400". 

Steps to recreate. 
- Fresh install of Magento 2 enable Braintree payment module and input sandbox api information.
- Disable all shipping or create a downloadable product that does not have any shipping
- Add only the downloadable product to the cart an begin to check out (make sure no shipping is applied to the product). After inputting credit card details click submit. Firebug shows "the server responded with a status of 400"

My work around to get the checkout working is to set Flat Rate shipping to "0.00" and set all my software products to require shipping. The downside is any products created as downloadable must be changed to require shipping.

![screen shot 2016-08-11 at 9 09 20 pm](https://cloud.githubusercontent.com/assets/14918418/17611353/7e59e40a-6014-11e6-8de0-ff3df44eff5d.png)

![screen shot 2016-08-11 at 10 11 02 pm](https://cloud.githubusercontent.com/assets/14918418/17611347/737dd83e-6014-11e6-9b3b-2aa741010e68.png)

**Comment by YevSent** [comment]
Hi, @hummerh2, thanks for reporting.

On your second screenshot, I see `Country` and `Phone` fields above Braintree credit card form, did you press `Update` button after entering billing address details?
This fields should not look like input, but should look like this:
![screenshot from 2016-08-12 10-34-14](https://cloud.githubusercontent.com/assets/2736528/17615704/902c957e-6078-11e6-9862-a0138eeeb0bf.png)

Also, could you reproduce it on the latest develop?

**Comment by hummerh2** [comment]
Hi @joni-jones ,

I have tried both with clicking update first and without clicking update. Get the same 400 error. I will try on the latest develop this evening. 

Thanks!

Mac OS X 10.11.6, Chrome Version 52.0.2743.116 (64-bit), Safari Version 9.1.2 (11601.7.7),  Firefox Ver 48

**Comment by YevSent** [comment]
Without clicking `Update` won't work, because only after that action billing address will be added to quote and payment.
You can use xdebug to find main reason of this error. Try to set breakpoint in [PaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71) or [GuestPaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83) for guest customers.

**Comment by alena-marchenko** [comment]
Hi @hummerh2 

Closing this issue due to no response, please reopen when you have an update.
