### ISSUE TITLE
REST API product listing with currentPage and pageSize does not include category_ids

### ISSUE THREAD

**Issue by dnadle** [magento/magento2#6127]
### Preconditions

1.  Magento 2.1.0
### Steps to reproduce

1.  Do an API product paginated search query with `/V1/products/?searchCriteria[currentPage]=1&searchCriteria[pageSize]=100`
2. Look at returned JSON content.
3. Do an API product GET with /V1/products/{sku}
4. Look at returned JSON content.
### Expected result

1. Products returned by paginated search should include "category_ids" as a member of "custom_attributes".
### Actual result

1. The listed products using the paginated search criteria exclude "category_ids" from the "custom_attributes" array.
2. Loading the SKU with /V1/products/{sku} includes the "category_ids" attribute.

**Comment by mbrinton01** [comment]
Thank you @dnadle for this report. We are tracking it under the internal issue MAGETWO-59130.

**Comment by PaulBoss** [comment]
Is there an update or timeframe for this issue? We also want to sync the product data and we are waiting for a fix for this. A workaround would be to do an API call for /product/{sku} for every product but that will add a significant load to the store.

**Comment by SerhiyShkolyarenko** [comment]
The fix is delivered to develop branch. Closing the issue.

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko Will MAGETWO-59130 be included in 2.1.3?

**Comment by gehirnstuerm** [comment]
I fear MAGETWO-59130 is not included in 2.1.6?
Is there an ETA for this?

**Comment by misha-kotov** [comment]
@gehirnstuerm the fix will be backported in one of the upcoming 2.1.x releases.

**Comment by PaulBoss** [comment]
So when will this be backported?
