### ISSUE TITLE
Simplify the System configuration Catalog > Catalog

### ISSUE THREAD

**Issue by paales** [magento/magento2#6133]
### Preconditions

1. 2.1
2. 
### Steps to reproduce

1. Go to store configuration Catalog > Catalog
### Expected result

1. Catalog does not exist and we have the following items in the left navigation:

Catalog > Product: [Product Image Placeholders, Product Video, Recently Viewed/Compared Products]
Catalog > Reviews: [Product Reviews, ..]
Catalog > Categories: [Category Top Navigation, Storefront, Layered Navigation]
Catalog > Search: [Catalog Search]
Catalog > Product Alerts: [Product Alerts, Product Alerts Run Settings]
Catalog > Search Engine Optimization: [Product Fields Auto-Generation, Search Engine Optimizations]
Catalog > Downloadable Products: Downloadable Product Options

_Price_ should be moved to somewhere else altogether, is such a fundamental setting it should be somewhere else. Or maybe even better, it should be removed completely and the attribute scope for price should be used.

_Date & Time Custom Options_ should be removed somewhere else altogether or I don't understand the configuration
### Actual result

1. We have a huge list that makes configuring things unclear.

**Comment by pboisvert** [comment]
Passing along to the UX team and closing as this is not a code issue but rather a UX request. Agreed that Date and Time options seem to be an outlier in this grouping. UX team will review if Price should be moved elsewhere. Card sort exercises were done with new and existing merchants so this grouping was based on M1 with feedback.

**Comment by pboisvert** [comment]
created UX story https://jira.corp.magento.com/browse/MAGETWO-56817 to track this request for UX review

**Comment by paales** [comment]
Thanks for the response. Is there a better place to leave UX feedback? I'm not really clear about the things you guys want on GitHub and thing you don't want on GitHub. :)
