### ISSUE TITLE
Product relations deleted after update from M2.0.8 to M2.1.0

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6134]
When I updated from M2.0.8 to M2.1.0 I found out that all my configurable products were broken. They were no longer linked in the admin under 'Configurations' and the frontend showed the error that the product did not have any sub-products.

A little bit of investigation showed that during the update, the `catalog_product_relation`-table and the `catalog_product_super_link`-table where both truncated. Strange...

Restoring the data in these tables fixed my problem, but I'm not sure what caused it in the first place that they got flushed. Hence this bug report.

**Comment by victor-v-rad** [comment]
Tried to update M2.0.8 to M2.1.0 and can't reproduce. Have you figured out the cause of the issue?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
