### ISSUE TITLE
Braintree error with credit card

### ISSUE THREAD

**Issue by chiragayartops** [magento/magento2#6136]

**Comment by chiragayartops** [comment]
Hello,
![braintree-error](https://cloud.githubusercontent.com/assets/20859792/17620592/048fd5ca-60ab-11e6-9144-718fc4b4a9b2.png)

My magento version is 2.1.0.
I use braintree payment method with credit cart payment it showing error like 'Unable to place order. Please try again later'. 
please give me suggestion for this.

**Comment by chiragayartops** [comment]
Hello,
![braintree-error](https://cloud.githubusercontent.com/assets/20859792/17620611/2c1430b4-60ab-11e6-91f7-472968a172e7.png)

My magento version is 2.1.0.
I use braintree payment method with credit cart payment it showing error like 'Unable to place order. Please try again later'. 
please give me suggestion for this.

**Comment by YevSent** [comment]
Hi, @chiragayartops, thanks for reporting.

Please, attach debug or exception log. Also, you can use xdebug to find main reason of this error. Try to set breakpoint in [PaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71) or [GuestPaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83) for guest customers.

**UPD**: please, format your issue according to Magento 2 issues template from [docs](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html#report) .

**Comment by pstoute** [comment]
@chiragayartops This is probably the same issue that I was having. Same exact description. https://github.com/magento/magento2/issues/5714

**Comment by alena-marchenko** [comment]
Hi @chiragayartops 

Closing this issue due to no response, please reopen when you have an update.
