### ISSUE TITLE
Ability to assign CMS Block to Category Missing from Category Display Settings

### ISSUE THREAD

**Issue by Harrington77** [magento/magento2#6139]
The ability to assign a CMS Block to a Category is missing from the Category's Display Settings option in Magento version 2.1. The screen shot at bottom is from sites hosted with Nexcess and viewed with Chrome browser. I've noticed this feature is missing from both CE and EE 2.1 versions.
### Steps to reproduce
1. Within admin, navigate to Products > Categories.
2. Select any Category.
3. View selected Category's Display Settings menu and notice ability to assign CMS Block is missing.
### Expected result
1. There should be an option to select a static block. 
   This feature was present in both CE and EE 1.x versions, and present in 2.0.2 version.
### Actual result
1. Navigating to Category's Display Settings does not present option to assign CMS Block. See attachment.

![category view changed - 2](https://cloud.githubusercontent.com/assets/17125403/17624144/165812be-6069-11e6-9a76-d01f79088b1d.png)

**Comment by heldchen** [comment]
it is in the "Content" section now:

![image](https://cloud.githubusercontent.com/assets/299636/17659597/ee8e154a-62d3-11e6-9cad-5d6de30b59c9.png)

**Comment by Harrington77** [comment]
Thanks @heldchen.
I've been noticing a number of admin things have moved from version 2.0 to 2.1.

**Comment by pawanguleria911** [comment]
But is is not not working on my website. When assigned the static block to the category and only static block .
But it will not show my static block it only display the  We can't find products matching the selection. please help me.
  why this happen?
