### ISSUE TITLE
validation strings In lib/web/mage/validation.js are not translatable

### ISSUE THREAD

**Issue by Rickywils** [magento/magento2#6141]
1.  Magento version 2.0.7
### Steps to reproduce

1. Try to translate these strings
### Expected result

1. Make all the strings translatable with $.mage__(' ')
### Actual result

1. Strings are not translatable at all.

Made a pull request for "validate-email".

https://github.com/magento/magento2/pull/6140

**Comment by BeatDirector** [comment]
Magento 2.1.1
I tried $.mage.**('Please enter a valid email address (Ex: johndoe@domain.com).') and it works with de_DE.csv. 
Adding $.mage.**() should be added by default in js core files.

**Comment by tkn98** [comment]
X-Ref: 
- Magento Enterprise Support Case #03191452
- Duplicate of: #4883

**Comment by maksek** [comment]
The fixed will be delivered in 2.0.15 and 2.1.7, 2.2.0.

**Comment by tkn98** [comment]
@maksek: What is the ETA of these releases?

**Comment by tkn98** [comment]
And can you provide the commits where this went in for reference? Thanks for all your efforts.

**Comment by grasdaggel** [comment]
Is there any hotfix for this? We cannot go live with several shops due to this fatal bug.

**Comment by tkn98** [comment]
If the commits would be linked, this would be the patch (hotfix). Still not yet. Commits anyone?

**Comment by tkn98** [comment]
@maksek: Ping :)

**Comment by mavr1982** [comment]
Commits?

**Comment by mavr1982** [comment]
any news?

**Comment by magento-engcom-team** [comment]
@Rickywils, thank you for your report.
We've created internal ticket(s) MAGETWO-82815 to track progress on the issue.

**Comment by MikeParkin** [comment]
Looking at this as part of  #distributed-cd

**Comment by magento-engcom-team** [comment]
@MikeParkin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by MikeParkin** [comment]
Checking the history of lib/web/mage/validation.js it appears that translations for all of the strings has been added on 2.1, 2.2 and 2.3:

2.1-develop bd63082191de
2.2-develop/2.3 3109c8e96bcd 

Going to close this issue.
