### ISSUE TITLE
Configurable products: custom options for associated simple products

### ISSUE THREAD

**Issue by qmarlats** [magento/magento2#6142]
Do you planned to allow custom options for simple products associated with configurable products like [this extension](https://www.magentocommerce.com/magento-connect/simple-configurable-products.html) did? Since there are no any alternative extension for Magento 2 it would be really usefull.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-products-custom-options-for-associated-simple/idi-p/44978).

**Comment by biotech** [comment]
We did that customisation and offer it as part of commerce extension https://firebearstudio.com/blog/add-custom-options-to-magento-2-configurable-products.html
