### ISSUE TITLE
Braintree error with credit card

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6148]
Hi,
 I using magento 2.1.0 version and I have using braintree(with credit card) payment method.
It is working fine using paypal but it is not working in credit card.
Some time working and some time not working.

please give me solution for this

**Comment by YevSent** [comment]
Hi, @Aartitops, please, format your issue according to Magento 2 issues template from [docs](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html#report).

Also, check browser console errors and attach Magento debug and exception log.

**Comment by Aartitops** [comment]
Hello,
When i try to pay using braintree(credit card) it showing this error.
![braintree-error](https://cloud.githubusercontent.com/assets/20356638/17688052/0cc7d364-6399-11e6-80bf-d6ca151b7e18.png)

**Comment by Aartitops** [comment]
Hello,
When i try to pay using braintree(credit card) it showing this  console error.
![braintre](https://cloud.githubusercontent.com/assets/20356638/17688721/6a6baa26-639f-11e6-90b1-8a6007ea51cf.png)

**Comment by Aartitops** [comment]
Hello,
When i try to pay using braintree(credit card) it showing console error.

Excepted result:-
Order with braintree(Credit card)

Actual result

![braintre](https://cloud.githubusercontent.com/assets/20356638/17688945/4dc68ba0-63a1-11e6-8633-8d7079fdb562.png)

**Comment by YevSent** [comment]
Please, attach debug or exception log. Also, you can use xdebug to find main reason of this error. Try to set breakpoint in [PaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71) or [GuestPaymentInformationManagement](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83) for guest customers.

**Comment by Aartitops** [comment]
Hi,
I can't unble to post debug.log file it's very long file.
![comment](https://cloud.githubusercontent.com/assets/20356638/17690886/12d6aaee-63af-11e6-90ba-75f8d056a33d.png)

**Comment by YevSent** [comment]
Then post just request/response for last Braintree transaction. And original exception message from PaymentInformationManagement service.

**Comment by Aartitops** [comment]
Hi,
This is braintree code:-

'client' => 'Magento\Braintree\Gateway\Http\Client\TransactionSale',
  'response' => 
  array (
    'success' => false,
    '' . "\0" . '_' . "\0" . '_attributes' => 
    array (
      'errors' => 
      Braintree\Error\ErrorCollection::__set_state(array(
         '_errors' => 
        Braintree\Error\ValidationErrorCollection::__set_state(array(
           '_errors' => 
          array (
          ),
           '_nested' => 
          array (
          ),
           '_collection' => 
          array (
          ),
        )),
      )),
      'params' => 
      array (
        'transaction' => 
        array (
          'type' => 'sale',
          'customer' => 
          array (
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'phone' => '704-315-7675',
            'email' => 'aarti.patel@tops-int.com',
          ),
          'amount' => '59.98',
          'paymentMethodNonce' => 'f62cb44f-215f-404e-8c88-4fce7433dbc6',
          'orderId' => '000000116',
          'channel' => 'Magento2_Cart_Community_BT',
          'billing' => 
          array (
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'streetAddress' => '7250 Kinley Commons Lane',
            'extendedAddress' => NULL,
            'locality' => 'Charlotte',
            'region' => 'NC',
            'postalCode' => '28278',
            'countryCodeAlpha2' => 'US',
          ),
          'shipping' => 
          array (
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'streetAddress' => '7250 Kinley Commons Lane',
            'extendedAddress' => NULL,
            'locality' => 'Charlotte',
            'region' => 'NC',
            'postalCode' => '28278',
            'countryCodeAlpha2' => 'US',
          ),
          'options' => 
          array (
            'storeInVaultOnSuccess' => 'true',
            'submitForSettlement' => 'true',
          ),
        ),
      ),
      'message' => 'No Account',
      'transaction' => 
      Braintree\Transaction::__set_state(array(
         '_attributes' => 
        array (
          'id' => '1jw9kyhm',
          'status' => 'processor_declined',
          'type' => 'sale',
          'currencyIsoCode' => 'USD',
          'amount' => '59.98',
          'merchantAccountId' => 'fellmarineUSD',
          'subMerchantAccountId' => NULL,
          'masterMerchantAccountId' => NULL,
          'orderId' => '000000116',
          'createdAt' => 
          DateTime::__set_state(array(
             'date' => '2016-08-13 13:23:46.000000',
             'timezone_type' => 3,
             'timezone' => 'UTC',
          )),
          'updatedAt' => 
          DateTime::__set_state(array(
             'date' => '2016-08-13 13:23:47.000000',
             'timezone_type' => 3,
             'timezone' => 'UTC',
          )),
          'customer' => 
          array (
            'id' => NULL,
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'email' => 'aarti.patel@tops-int.com',
            'website' => NULL,
            'phone' => '704-315-7675',
            'fax' => NULL,
          ),
          'billing' => 
          array (
            'id' => NULL,
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'streetAddress' => '7250 Kinley Commons Lane',
            'extendedAddress' => NULL,
            'locality' => 'Charlotte',
            'region' => 'NC',
            'postalCode' => '28278',
            'countryName' => 'United States of America',
            'countryCodeAlpha2' => 'US',
            'countryCodeAlpha3' => 'USA',
            'countryCodeNumeric' => '840',
          ),
          'refundId' => NULL,
          'refundIds' => 
          array (
          ),
          'refundedTransactionId' => NULL,
          'partialSettlementTransactionIds' => 
          array (
          ),
          'authorizedTransactionId' => NULL,
          'settlementBatchId' => NULL,
          'shipping' => 
          array (
            'id' => NULL,
            'firstName' => 'Aarti',
            'lastName' => 'patel',
            'company' => NULL,
            'streetAddress' => '7250 Kinley Commons Lane',
            'extendedAddress' => NULL,
            'locality' => 'Charlotte',
            'region' => 'NC',
            'postalCode' => '28278',
            'countryName' => 'United States of America',
            'countryCodeAlpha2' => 'US',
            'countryCodeAlpha3' => 'USA',
            'countryCodeNumeric' => '840',
          ),
          'customFields' => NULL,
          'avsErrorResponseCode' => NULL,
          'avsPostalCodeResponseCode' => 'U',
          'avsStreetAddressResponseCode' => 'U',
          'cvvResponseCode' => 'N',
          'gatewayRejectionReason' => NULL,
          'processorAuthorizationCode' => NULL,
          'processorResponseCode' => '2007',
          'processorResponseText' => 'No Account',
          'additionalProcessorResponse' => '14',
          'voiceReferralNumber' => NULL,
          'purchaseOrderNumber' => NULL,
          'taxAmount' => NULL,
          'taxExempt' => false,
          'creditCard' => 
          array (
            'token' => NULL,
            'bin' => '450060',
            'last4' => '0061',
            'cardType' => 'Visa',
            'expirationMonth' => '05',
            'expirationYear' => '2017',
            'customerLocation' => 'US',
            'cardholderName' => NULL,
            'imageUrl' => 'https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=production',
            'prepaid' => 'No',
            'healthcare' => 'No',
            'debit' => 'No',
            'durbinRegulated' => 'No',
            'commercial' => 'No',
            'payroll' => 'No',
            'issuingBank' => 'Canadian Imperial Bank of Commerce',
            'countryOfIssuance' => 'CAN',
            'productId' => 'P',
            'uniqueNumberIdentifier' => NULL,
            'venmoSdk' => false,
          ),
          'statusHistory' => 
          array (
            0 => 
            Braintree\Transaction\StatusDetails::__set_state(array(
               '_attributes' => 
              array (
                'timestamp' => 
                DateTime::__set_state(array(
                   'date' => '2016-08-13 13:23:47.000000',
                   'timezone_type' => 3,
                   'timezone' => 'UTC',
                )),
                'status' => 'processor_declined',
                'amount' => '59.98',
                'user' => 'fredrik.eriksen@fell.no',
                'transactionSource' => 'api',
              ),
            )),
          ),
          'planId' => NULL,
          'subscriptionId' => NULL,
          'subscription' => 
          array (
            'billingPeriodEndDate' => NULL,
            'billingPeriodStartDate' => NULL,
          ),
          'addOns' => 
          array (
          ),
          'discounts' => 
          array (
          ),
          'descriptor' => 
          Braintree\Descriptor::__set_state(array(
             '_attributes' => 
            array (
              'name' => NULL,
              'phone' => NULL,
              'url' => NULL,
            ),
          )),
          'recurring' => false,
          'channel' => 'Magento2_Cart_Community_BT',
          'serviceFeeAmount' => NULL,
          'escrowStatus' => NULL,
          'disbursementDetails' => 
          Braintree\DisbursementDetails::__set_state(array(
             '_attributes' => 
            array (
              'disbursementDate' => NULL,
              'settlementAmount' => NULL,
              'settlementCurrencyIsoCode' => NULL,
              'settlementCurrencyExchangeRate' => NULL,
              'fundsHeld' => NULL,
              'success' => NULL,
            ),
          )),
          'disputes' => 
          array (
          ),
          'paymentInstrumentType' => 'credit_card',
          'processorSettlementResponseCode' => NULL,
          'processorSettlementResponseText' => NULL,
          'threeDSecureInfo' => NULL,
          'creditCardDetails' => 
          Braintree\Transaction\CreditCardDetails::__set_state(array(
             '_attributes' => 
            array (
              'token' => NULL,
              'bin' => '450060',
              'last4' => '0061',
              'cardType' => 'Visa',
              'expirationMonth' => '05',
              'expirationYear' => '2017',
              'customerLocation' => 'US',
              'cardholderName' => NULL,
              'imageUrl' => 'https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=production',
              'prepaid' => 'No',
              'healthcare' => 'No',
              'debit' => 'No',
              'durbinRegulated' => 'No',
              'commercial' => 'No',
              'payroll' => 'No',
              'issuingBank' => 'Canadian Imperial Bank of Commerce',
              'countryOfIssuance' => 'CAN',
              'productId' => 'P',
              'uniqueNumberIdentifier' => NULL,
              'venmoSdk' => false,
              'expirationDate' => '05/2017',
              'maskedNumber' => '450060_*****0061',
            ),
          )),
          'customerDetails' => 
          Braintree\Transaction\CustomerDetails::__set_state(array(
             '_attributes' => 
            array (
              'id' => NULL,
              'firstName' => 'Aarti',
              'lastName' => 'patel',
              'company' => NULL,
              'email' => 'aarti.patel@tops-int.com',
              'website' => NULL,
              'phone' => '704-315-7675',
              'fax' => NULL,
            ),
          )),
          'billingDetails' => 
          Braintree\Transaction\AddressDetails::__set_state(array(
             '_attributes' => 
            array (
              'id' => NULL,
              'firstName' => 'Aarti',
              'lastName' => 'patel',
              'company' => NULL,
              'streetAddress' => '7250 Kinley Commons Lane',
              'extendedAddress' => NULL,
              'locality' => 'Charlotte',
              'region' => 'NC',
              'postalCode' => '28278',
              'countryName' => 'United States of America',
              'countryCodeAlpha2' => 'US',
              'countryCodeAlpha3' => 'USA',
              'countryCodeNumeric' => '840',
            ),
          )),
          'shippingDetails' => 
          Braintree\Transaction\AddressDetails::__set_state(array(
             '_attributes' => 
            array (
              'id' => NULL,
              'firstName' => 'Aarti',
              'lastName' => 'patel',
              'company' => NULL,
              'streetAddress' => '7250 Kinley Commons Lane',
              'extendedAddress' => NULL,
              'locality' => 'Charlotte',
              'region' => 'NC',
              'postalCode' => '28278',
              'countryName' => 'United States of America',
              'countryCodeAlpha2' => 'US',
              'countryCodeAlpha3' => 'USA',
              'countryCodeNumeric' => '840',
            ),
          )),
          'subscriptionDetails' => 
          Braintree\Transaction\SubscriptionDetails::__set_state(array(
             '_attributes' => 
            array (
              'billingPeriodEndDate' => NULL,
              'billingPeriodStartDate' => NULL,
            ),
          )),
        ),
      )),
      'creditCardVerification' => NULL,
      'subscription' => NULL,
      'merchantAccount' => NULL,
    ),
  ),
) {"is_exception":false} []
[2016-08-13 13:23:04] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://buy.fellmarine.com/rest/default/V1/carts/mine/payment-information","invalidateInfo":{"tags":["catalog_product_24","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-08-13 13:23:04] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://buy.fellmarine.com/rest/default/V1/carts/mine/payment-information","invalidateInfo":{"tags":["catalog_product_9","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-08-13 13:23:04] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://buy.fellmarine.com/rest/default/V1/carts/mine/payment-information","invalidateInfo":{"tags":["catalog_product_1","FPC"],"mode":"matchingTag"},"is_exception":false} []

**Comment by YevSent** [comment]
Braintree gateway declines your transaction:
`'success' => false` and `'message' => 'No Account'`

Please, check [Braintree errors](https://articles.braintreepayments.com/control-panel/transactions/declines) to find the reason of transaction declining.

**Comment by Aartitops** [comment]
Hello,
I check document for braintree errors:-

![error](https://cloud.githubusercontent.com/assets/20356638/17691313/761e4038-63b1-11e6-8392-b4f0dc60c89d.png)
and i check my error is 'No Account' right? So for this i need to contact bank. but can you give me please give me demo credit card detail which working properly? So I can check properly.

Thanks

**Comment by YevSent** [comment]
Braintree has [list](https://developers.braintreepayments.com/reference/general/testing/php#credit-card-numbers) for testing.

Close this issue as not related to Magento code, please, be free to reopen it.

**Comment by Aartitops** [comment]
Hi,
I have already use but it is not working.
Card number: - 4111111111111111
Expiration Date :- 05/17
Card Verification Number:- 100

Thanks.

**Comment by YevSent** [comment]
Check your debug log.

**Comment by Aartitops** [comment]
Hi,
I check my debug log and i have get this error.
![debug1](https://cloud.githubusercontent.com/assets/20356638/17692685/b518761c-63b8-11e6-9086-f7d5f34e5bca.png).

What I doing?
Thanks.

**Comment by Aartitops** [comment]
Hello,
Any update?

**Comment by Aartitops** [comment]
Hi,
When i place order with braintree With credit card it showing console error like '{"message":"Unable to place order. Please try again later."}' so Now I want to error like 'unable to place order' if customer can't place order so he/she show this error and use proper bank detail.

So can you please tell me  how to print this error message?
Thanks.

**Comment by YevSent** [comment]
The error message is the same as in previous response. Try to check your configuration and contact with Braintree support.

> So can you please tell me how to print this error message?

You can't customize error message and show the original error message from payment gateway because it's less safe and allow to research some vulnerabilities.

**Comment by Aartitops** [comment]
Hi,
How can I get error message from braintree? 
I check my debug.log file i get 'No Account' error from braintree so i want to display error  already braintree error list 'The submitted card number is not on file with the card-issuing bank. The customer will need to contact their bank' instead of  'Unable to place order. Please try again later'.

**Comment by Aartitops** [comment]
Hi,
Any update?
