### ISSUE TITLE
Image handling in the media folder

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/magento2#6149]
Following is **not a bug** it can be considered as an improvement or a feature.

In Magento 1 over long time of use media folder size keep growing and it become too huge.(If there a frequent updates of images).

This happens especially for the website having very large catalog. It becomes difficult to identify the unused images and remove them. As an image can be used for multiple products or on multiple pages.

Is there any road map of any feature which will provide a functionality for optimal handling of images in media folder?

**Comment by Ctucker9233** [comment]
Is your issue with Magento 1 or Magento 2. This github is only for Magento 2. To answer your question though, it seems Magento 2 has self cleaning behavior. Any time a product is deleted or any single image is removed, the image(s) is/are removed from the media folder.

**Comment by tiwarimukesh** [comment]
Hi @Ctucker9233 
My question is related to Magento 2. If your answer mean to say that when we import new images to products, previously used images are removed from media folder then I think you can close this ticket.
I will try to check if it happens on local system.(I have not tried it yet.)

**Comment by Ctucker9233** [comment]
@tiwarimukesh I have noticed the self-cleaning behavior when I go into a specific product in the catalog, delete the images i don't want (using the little trashcan symbol) and then loading the ones I want. It may not be exactly the same for importing products with images.

**Comment by tiwarimukesh** [comment]
@Ctucker9233 Yes, I tried in my local set up what you mentioned is correct. I will check for the importing product with images.

**Comment by tiwarimukesh** [comment]
@Ctucker9233  I tried the image import using the import functionality of Magento. It assign a new image to the product but keep the original image intact (Original image is not deleted) in admin as well as on \pub\media\catalog\product\w\t location.

Tested on  : Magento 2.0.0
csv format used >>
"sku","base_image"
"WT09-XS-Purple","wt09-white_back-test.jpg"

**Comment by Ctucker9233** [comment]
@tiwarimukesh Interesting! Thanks for investigating that.

**Comment by veloraven** [comment]
@tiwarimukesh thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by tiwarimukesh** [comment]
Hi @veloraven 

I am aware of feature request section of the Magento forums. I know most of the feature requests has been already moved to the Community forums _Magento 2 Feature Requests and Improvements_ section. If this topic also qualify for the new feature request then your team can move it to Forums.

Otherwise if you suggest I can my self post this to the _Magento 2 Feature Requests and Improvements_ section of forums.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Image-handling-in-the-media-folder/idi-p/54660).
