### ISSUE TITLE
magento 2.1 related products add to cart button not working

### ISSUE THREAD

**Issue by viken-tops** [magento/magento2#6152]
magento 2.1 related products add to cart button on product page sidebar is not working

**Comment by veloraven** [comment]
@viken-tops thank you for your report.
Please provide more detailed steps. 
Please also provide information if it was clear install or upgrade from some previous version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
