### ISSUE TITLE
Configurable Products incorrect pricing

### ISSUE THREAD

**Issue by justinahsnyder** [magento/magento2#6156]
In Magento 2.1.0 I migrated from 1.8x using Ubertheme migration tool. 

Problem: The configurable product pricing is not behaving correctly.

If you visit ([http://cheapsuperfoods.com/raw-organic-mesquite-powder-buy-online-australia.html.html]) you will see that the the price shows $43 (the correct price) then when you select the configurable option the price changes to $38.5.

There is no $38.5 in the simple or configurable product backend (see below). There is no tax enabled and I have cleared cache and reindexed many times

<img width="1217" alt="screen shot 2016-08-14 at 10 16 05 am" src="https://cloud.githubusercontent.com/assets/7115149/17646333/2e5ed820-6208-11e6-8406-31df70e0c549.png">
<img width="1292" alt="screen shot 2016-08-14 at 10 16 17 am" src="https://cloud.githubusercontent.com/assets/7115149/17646334/2ea42736-6208-11e6-9774-810f41a91d40.png">

**Comment by wert2all** [comment]
Sorry, we cannot support Ubertheme migration tool.
