### ISSUE TITLE
Admin user receives en_US interface locale by default regardless of store language

### ISSUE THREAD

**Issue by techteamus** [magento/magento2#6157]
Affected version: Community 2.1.0

During test deployments of my Magento 2 setup I continually ran into problems if I used a language other than en_US.

After running the setup and a 'bin/magento setup:static-content:deploy en_GB' the front end files would display just fine but the admin interface was missing all the CSS etc.

I eventually traced the problem back to how the initial admin user is created. Regardless of what language is chosen during setup the admin user is always setup with the interface locale as en_US. To me this seems counter intuitive, the initial admin user should be configured with the same language as the store configuration.

Changing the admin user interface locale to en_GB in the database (not recommended) solves the problem instantly and the admin interface displays as expected.

If the initial admin user was correctly configured this would have saved me time and I have no doubt other people are trudging around in circles try to resolve what looks like a complex issue but is in fact a simple configuration problem.

**Comment by wert2all** [comment]
Please provide a version of Magento too.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-user-receives-en-US-interface-locale-by-default-regardless/idi-p/44976).
