### ISSUE TITLE
Address book - Fax not getting saved to DB.

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#6158]
### Preconditions

1. Magento 2.1, Luma theme activated
2. PHP 5.6 , Nginx+PHP-Fpm 
### Steps to reproduce

1. Create an account.
2. Place an order with shippable product. 
3. Edit Shipping address from the my account address page and Key in fax there.
### Expected result

1. Fax number should be saved.
### Actual result

1. Getting the successfully saved message but the fax is not there in the DB nor in the UI as well.
2. Same happens with the Billing address .

**Comment by katmoon** [comment]
Hi @senthilengg 

Thank you for reporting the issue. It is reported as `MAGETWO-57146` internally.

Thanks,
Kateryna.

**Comment by priyanjali27** [comment]
MAGETWO-57146 is still open. Fax is not getting saved. Please help

**Comment by manithiruit** [comment]
Hi @senthilengg,

Go to Mysql  "customer_eav_attribute" table. As per "eav_attribute" table, Fax attribute id is 35. So search attribute id 35 in "customer_eav_attribute", then change column **is_visible** to 1.

**Comment by magento-engcom-team** [comment]
@senthilengg, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
