### ISSUE TITLE
php bin/magento i18n:collect-phrases BUG

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#6160]
Hello,
we still stay on magento root directory and try to run 

`php bin/magento i18n:collect-phrases -o "all_phrases.csv" -m`

But we get the error: 

> [InvalidArgumentException]
>   Specified path is not a Magento root directory

We don't know what going wrong. If we try with 

`php bin/magento i18n:collect-phrases -o "all_phrases.csv" "."`

It will woking but after that we missing extension name on csv. As we know, it will only work if we are using "-m" instead of "."
But with "-m" or "--magento" it won't work.... 

Could you help?

We are using Magento 2.1.0

**Comment by antboiko** [comment]
Hi @klarlichter , please check http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.html . In your case, please run the command in the following way `php <your Magento install dir>/bin/magento <command name>`

Best,
Anton.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
