### ISSUE TITLE
Product custom option price scope issue

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#6165]
It is not possible to change the price of custom options at different scopes. If you change the scope when editing a product and change the price of a custom option the value is changed across all scopes. This functionality was present in Magento 1.
### Steps to reproduce
1. Create a Magento environment with multiple websites and store views
2. Create a simple product
3. Add a custom option to the product with different values with different pricing
4. Save the product
5. Change the store view scope you are editing in and change the pricing of the custom options
6. Save
7. Review the custom option pricing at default and other storeview scopes
### Expected result

Price of the custom option should be different at the storeview scope.
### Actual result

Price of the custom option is changed to the new value at all scope levels

**Comment by wert2all** [comment]
@alexgoodey Please, provide the used Magento version.

**Comment by alexgoodey** [comment]
Magento CE 2.1.0

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-custom-option-price-scope-issue/idi-p/44973).

**Comment by SahakTadevosyan** [comment]
@piotrekkaminski @antboiko  Is this problem solved ?
I have the same problem when editing  the product.
My magento version is Magento CE 2.1.0
Thanks

**Comment by sshymko** [comment]
@piotrekkaminski 
We've reproduced the issue on the latest Magento 2.1.7 and upcoming 2.2 (and latest Magento 1.x).
This is a major problem especially for multi-currency websites, not a feature request.
Imagine USD and EUR websites selling the same SKU with custom option w surcharge.
Obviously, the price amount needs to be different in different currencies.
This bug prevents saving unique surcharge amount for each website.

Please reopen the ticket.
Thanks.

**Comment by sshymko** [comment]
@alexgoodey 
The following **Precondition** is necessary to reproduce the test case:
Configuration > Catalog > Price > Catalog Price Scope: Website

Otherwise the prices are Global and don't vary per Website.

**Comment by sshymko** [comment]
**The workaround** in a form of a custom module.
Tested on Magento 2.1.4.

File `app/code/Example/CatalogOptionFix/Model/ResourceModel/Product/Option/Value.php`:
```php
<?php
namespace Example\CatalogOptionFix\Model\ResourceModel\Product\Option;

class Value extends \Magento\Catalog\Model\ResourceModel\Product\Option\Value
{
    protected function _saveValuePrices(\Magento\Framework\Model\AbstractModel $object)
    {
        $originalStoreId = $object->getStoreId();
        $storeId = $originalStoreId === null ? true : $originalStoreId;
        $object->setStoreId($storeId);
        try {
            parent::_saveValuePrices($object);
        } finally {
            $object->setStoreId($originalStoreId);
        }
    }
}
```

File `app/code/Example/CatalogOptionFix/etc/di.xml`:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Catalog\Model\ResourceModel\Product\Option\Value" type="Example\CatalogOptionFix\Model\ResourceModel\Product\Option\Value"/>
</config>
```
