### ISSUE TITLE
Configurable product slow saving or time out

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#6167]
### Preconditions

1.  Magento CE 2.1
2. PHP 7.09
3. MYSQL 5.7
4. Database migrated from 1.9 to 2.0, upgraded until 2.0.9 then to 2.1 (in test environment)
### Steps to reproduce

1. Saving a configurable product with 200 simple product variations - for example 20 colours & 10 sizes
### Expected result

1.  Product should save < 30 seconds with no errors
### Actual result

1. Request Timeout
   This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.
2. for smaller product, it will save, but may take 1-2 minutes
3. Simple product save instantly
   4 the same issue is NOT present in 2.0.9

**Comment by wert2all** [comment]
May be fixed into internal ticket MAGETWO-54682

**Comment by rudik99** [comment]
@wert2all is the updated code in the development branch? I could test to see if it works ?

**Comment by fendowuk** [comment]
I'm experiencing the same issue, I've tried to change lots of server setting to no avail.

**Comment by wert2all** [comment]
@rkhoury82 I cannot answer this question. Maybe we need a couple of day to sync.

**Comment by rudik99** [comment]
@wert2all any news ?

**Comment by wert2all** [comment]
I can't say anything, but I think this fix will be merged after 2.1.x release.

**Comment by RonXS** [comment]
I can second this on 2.1, the performance loss is mainly there when it comes to image saving. When i save a product with 3x10 variations, each having 10 images, the saving times out. If i save the exact same subset of products without additional images, the problem does not exist for me and the configurable product with all its variations saves in a matter of seconds.

**Comment by RonXS** [comment]
Extra note: I've created a mass importer of products for M2.1 and also there the speed significantly reduces to almost impossibly slow, where the images are already in pub/media/import. So i do not think its the action of "uploading" itself, but related to the logics handling the media gallery.

**Comment by SewHappy58** [comment]
I'm experiencing the same issue.  Extremely slow or crashes.

**Comment by rudik99** [comment]
I wish someone could help us with a short term fix, I'm stuck with bugs re configurable product in 2.0.9 and this error in 2.1

**Comment by SewHappy58** [comment]
@rkhoury82 my work around was to create everything as normal, save and it will lose the children.  Reopen and add manually since the children were created from the first attempt.  It seems to work for now.

**Comment by ajaymscit** [comment]
Any solution on this issue?

I am running Magento 2, having 900 Configurable products ( 113 associated products with each configurable product)
Magento2 speed is too slow. We are loading 40-60 configurable products and page shows blank. Earlier it was 24 products in listing, at that time it was taking too much time. Now page looking totally dead.

We tried to enable varnish with it but most of the time it gives 503 error.

Any solution for fixing slow speed issue?

**Comment by pboisvert** [comment]
@choukalos is there a pointer to the commit for this issue as I believe it is fixed and awaiting a release

**Comment by veloraven** [comment]
Fix for MAGETWO-54682 includes following commits:
df200939528ca54119e23c02d19e1fdc8a707745
cd102ba9dbab3d06be34cfff68e0e212552a0479
4a4e5e3d28e7fcec47dbd1d8ab89fd9631f05012
feccbc6379c2789517ec0e79d2feba130ea539d2
3c3d612dbdcbb550689a22de612160ff1d44c77b
cf195e720cd48e6da93716f33a9731c0b4564081
3c51b12113690d79d7456cf403a25e67b3c1a0b3

**Comment by franckgarnier21** [comment]
I have the same problem with a configurable with 4 variations but only 1 configurable and 3 simple product. The product creation is more than 120sec !

**Comment by boldbart** [comment]
We are experiencing the exact same issue on 2.1.2. Saving configurables with simples is painfully slow (with lots of timeouts as a result), especially when you choose to add images to the simples. When will this be released?

**Comment by pmathbliss** [comment]
Comment out
 `$collection->addMediaGalleryData();`
 vendor/magento/module-configurable-product/Model/Product/Type/Configurable.php
 line 589
Page loads return to normal.
This code adds every image in the entire site to every configurable product.

**Comment by rudik99** [comment]
This is fixed in 2.1.3 and can be closed

**Comment by veloraven** [comment]
@rkhoury82 thank you for update.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by tuancrystal** [comment]
@veloraven It seems fixed for save configurable product but when I duplicate configurable product it still slow saving or time out. Please recheck.

**Comment by devenkuswa** [comment]
@veloraven I am facing same issues on 2.1.7. 
There are approx 1000 associate product with 7 attribute. It does not allow to save product after a limit and crash, eventually it even not allow to open that edit screen.
On save it shows "413 Request Entity Too Large" and on hitting product edit URL it shows "503 Service Unavailable". I have already made changes in server configuration. 
I have tried on 2.1.10 and 2.2.2 as well but same issue...

**Comment by jgodart** [comment]
@devenkuswa I'm also in the same situation( M2-2.1.7) as you at a difference, users put at least 10 minutes before registering their configurable product. 
This is a serious problem when users need to enter a new product catalog.
The problem does not seem solved.

Corrections or solutions available?

**Comment by devenkuswa** [comment]
@jgodart I am still looking for feasible solution. I have generated a ticket regarding this and report to Magento.
https://github.com/magento/magento2/issues/13254#issuecomment-359410647

**Comment by jgodart** [comment]
@devenkuswa  Great thanks for your response.

**Comment by psapoznik** [comment]
same problem, angry customers.

**Comment by stellasoft-matt** [comment]
Any update on this, we are having the same issues with configurable products?

**Comment by crysix** [comment]
Problem still exists in 2.2.5, please reopen this issue (if it is not already fixed in 2.3).
If you create the config product without images, everything ist "fast" (10-20s), but if you use images it's getting really slow. In our tests, creating 60 products, it took about 10 minutes to save!

**Comment by Adel-Magebinary** [comment]
It's still slow in 2.3. 22835 products is taking 10 hours to save and locking up frontend.

**Comment by ssmadsen** [comment]
I can confirm. Not fixed in 2.3

Saving a configurable product with 4 associated products takes 3 minutes.

**Comment by gondas33** [comment]
Issue still messing up 2.3.2. When I'm trying to create like 14 pages of variations ( 280 products ) , with no image or anything, I'd getting a request timeout after 120 seconds.

**Comment by maxq** [comment]
2.3.4 duplicating configurable products takes forever if it actually completes.
The M2 admin is just too slow they need to fix this asap.

**Comment by LathropPreston** [comment]
I am experiencing the same general issue. Simple products save in nominal time, however if I try to do even a simple configurable product. This is for a book store, we are wanting configureable products where the customer can choose the format of the text (Paperback, Hardcover, etc -there are a few-) but for any given product on that one option type there are only 2 in many cases and I think 6 max on some. It is taking absurdly long for the product to save. There is NO reason this should be the case unless there is something very odd in what the model is doing. This is mission critical and I find it very odd that you are taking so long to truly address such a core issue.

**Comment by stupachenko** [comment]
Reopened https://github.com/magento/magento2/issues/34678

**Comment by eliacimdavila** [comment]
I am facing this in 2.3.4. The customer wants to create/update 30,000 configurable products, and each one takes so long. It will need two weeks of an uninterrupted process to finish.

**Comment by maxq** [comment]
Make sure your indexing is set to update by schedule then it should fix that. That was our issue it was index on save so it was indexing for a very long time. Once we switched to updated by schedule it was down to seconds to save.

**Comment by rudracomputech** [comment]
Hello! I am having same issue, after adding 50 associate products the admin product edit page shows time out. I am using Magento ver. 2.4.4.

Thanks
Rudra Computech
[www.rudracomputech.com](http://www.rudracomputech.com/)
