### ISSUE TITLE
Make bin/magento setup:upgrade less verbose

### ISSUE THREAD

**Issue by paales** [magento/magento2#6169]
### Preconditions

1. Magento 2.1
### Steps to reproduce

1. Run `bin/magento setup:upgrade`
### Expected result

1. It only shows what it actually modifies
### Actual result

1. It shows the names of all modules, making it hard to pick anything up what has changed.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Make-bin-magento-setup-upgrade-less-verbose/idi-p/44972).
