### ISSUE TITLE
Product attributes - Ability to update on website scope

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#617]
For now in Magento 1 and Magento 2 when we editing product we have 3 scopes attributes: global, website and store view, but we have select only can select global and store view scope. 
As result - we have only two levels in value fallback:
Global -> Website or Global -> Store view.

Would be great have three levels in value fallback, like in config:
Global -> Website -> Store view

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-27038

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-attributes-Ability-to-update-on-website-scope/idi-p/46231).
