### ISSUE TITLE
[ReflectionException] Class ...\weightedRate\Collection does not exist

### ISSUE THREAD

**Issue by quan-ntekka** [magento/magento2#6172]
### Preconditions
1. Magento 2.0.7
2. PHP 7.0.6
### Steps to reproduce
1. run php/magento setup:di:compile-multi-tenant 
### Expected result
1.  compile successfully
### Actual result

![magento class not found](https://cloud.githubusercontent.com/assets/15749378/17683153/70725fa4-6305-11e6-8caa-9faf0ae57cd6.PNG)

Has anyone seen this odd behavior before? My class name is changed to lowercasing, it should be WeightedRate.  It works when i'm in "developer" mode, but as soon as I run setup:di:compile-multi-tenant, it gives me that error.

I'm baffled as how this could happen, none of my code uses the lower case class name, Please help!!

**Comment by AVoskoboinikov** [comment]
Hello,

Are you sure that all file names and namespaces has correct file name? It looks like you have wrong file name in namespace somewhere.

**Comment by quan-ntekka** [comment]
I'm 100% absolutely sure it's not incorrect namespace or spelling mistake.  I've double and triple check, with multiple co-workers reviewing themselves.  

It works just fine on my local and "developer" mode.  It would only break when I try to compile or put it in production mode.

My assumption for this cause is either:
- encoding issue in an XML somewhere
- composer class loader is not parsing something correctly
- Magento object manager is not parsing class correctly but I don't know where.

I can email the module to you if you want a copy to inspect.

**Comment by quan-ntekka** [comment]
Sorry, I feel stupid, it was a spelling mistake....

**Comment by AVoskoboinikov** [comment]
It is good that everything is ok :)
