### ISSUE TITLE
Luma theme missing JS files for older branches

### ISSUE THREAD

**Issue by Umfi** [magento/magento2#6177]
Hey, there seems to be a problem with the 2.0.8 branch with JS files

for the customer registration area i got a 404 for 

/static/frontend/Magento/luma/de_AT/passwordStrengthIndicator.js

according to: https://github.com/magento/magento2/tree/2.0.8/app/code/Magento/Customer/view/frontend/web/js

the needed files are only available in the 2.1 releases.

**Comment by Khaleel** [comment]
Can you not just download them and add them in?

**Comment by Umfi** [comment]
I'm note sure if this is an good idea, some other files in the same folder have also changed and maybe there are dependencies. and i'm sure this would cause more errors than it would fix. 

EDIT: hm i think i found the problem, i override the form/register.phtml and somehow i used the code from 2.1 release as base. so this ain't a bug.

**Comment by andimov** [comment]
@Umfi 
Thank you for reporting!
Glad that you have found a solution. 
Please recheck that your problem is solved, and I will close this issue as 'not a bug'.

**Comment by Umfi** [comment]
problem was fixed. so ticket can be closed.
