### ISSUE TITLE
get braintree error if order won't place in magento

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6178]
Hello,

I using magento 2.1.0 version.
And I using braintree payment method but it is not working with credit card it showing console error like 'unable to place order. please try again later'.
So i want to  braintree error if user cant able to place order so what can i do?

Thanks.

**Comment by alena-marchenko** [comment]
hi @Aartitops 

We should not show response from Braintree directly to the customer, since it may cause potential security issue. You can find error in response from Braintree in var/log/debug.log under magento root folder. For this you need to enable debug for Braintree (Debug = Yes at Stores > Configuration > Sales > Payment Methods > Braintree > Advanced Braintree Settings).

**Comment by Aartitops** [comment]
Hi,
I have already check debug.log and i see my braintree error is 'No account'. 
So now i want show this 'No account' error from braintree error list on click on 'place order' button so, customer can't confused.
Thanks.

**Comment by alena-marchenko** [comment]
@Aartitops ,

We do not show error messages received from payment gateway directly to customer, since they can contain sensitive information. Also, response like "No account" is not informative for customers.

**Comment by Aartitops** [comment]
Hi,
I want to show No account means 'The submitted card number is not on file with the card-issuing bank. The customer will need to contact their bank.'  instead of 'unable to pleace order. try again later'.
It is possible or not?
Thanks.

**Comment by alena-marchenko** [comment]
@Aartitops ,

We do not receive error "The submitted card number is not on file with the card-issuing bank. The customer will need to contact their bank." in response from Braintree so Magento don't have detailed error description for displaying it to customer or in logs. Also, displaying errors from Braintree response to customer can cause security issues.

**Comment by Aartitops** [comment]
Hi,
So what can i do for solve this issue because with this error customer can't place order.
and it is working also live but it is not working in local server.
Can you give me please demo credit card detail for braintree?
Thanks.

**Comment by alena-marchenko** [comment]
@Aartitops ,

You can find detailed information regarding Braintree testing on their website https://developers.braintreepayments.com/reference/general/testing/php
Please inform us if this helped you.
If you still experience the issue, provide us with detailed description of it for us to be able to investigate it further:
- exact steps to reproduce the issue
- exception, debug logs
- screenshot of Braintree configuration in Magento

**Comment by Aartitops** [comment]
Hi,
I want to print only braintree error insted of 'unable to place order. please try again later' if order can't place into checkout page.
It is possible?
Thanks.

**Comment by Aartitops** [comment]
Hi,
I want to print only braintree error insted of 'unable to place order. please try again later' if order can't place into checkout page.
It is possible?
Thanks.

**Comment by alena-marchenko** [comment]
@Aartitops 

No, since these error messages can contain sensitive information.
Closing the issue, please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for technical questions.
Also, take a look at our [Issue Reporting Guidliness](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by Weltpixel** [comment]
Hi,

Until now this are the measures that we took and seams to significantly improve the transaction decline rate. After applying all 3 solutions, we didn't receive any reports of other users not being able to checkout using Braintree on our Magento 2.1 store. 

Hope this helps:
https://support.weltpixel.com/hc/en-us/articles/115007753688-How-we-solved-Braintree-Magento-2-checkout-issues-with-our-Magento-2-1-store

Regards,
WeltPixel Team

**Comment by Weltpixel** [comment]
Hi,

Until now this are the measures that we took and seams to significantly improve the transaction decline rate. After applying all 3 solutions, we didn't receive any reports of other users not being able to checkout using Braintree on our Magento 2.1 store. 

Hope this helps:
https://support.weltpixel.com/hc/en-us/articles/115007753688-How-we-solved-Braintree-Magento-2-checkout-issues-with-our-Magento-2-1-store

Regards,
WeltPixel Team

**Comment by korostii** [comment]
Hi @Weltpixel, please stop spamming multiple threads. If your comment is related to this specific issue, please just post here. If you believe other threads report the same issue, just write that it's a possible duplicate and note # of this issue, nothing more.
