### ISSUE TITLE
Problem with configurable option that out of stock

### ISSUE THREAD

**Issue by Omar-Oleh** [magento/magento2#6180]
Hello,

I am using Magento ver. 2.1.0 .
Precondition:
1) I have create configurable product with some options
2)One of option is out of stock
Steps:
1)Open configurable product on frontend
2)Try select option that out of stock

Expected result
http://clip2net.com/s/3BfHIhC (worked in Magento ver. 2.0.0)
If some option is out of stock them must be disabled

Actual result
http://clip2net.com/s/3BfHj5M
This option is out of stock but I can selected it. After click to add to cart I have message that such product is out of stock

Thanks.

**Comment by andidhouse** [comment]
This is a bug happening in 2.1 and reported here in different reports. 
I think this is very important as we also have many sizes... hope this is solved in 2.1.1.

Can a magento member pls tell us if it is fixed in 2.1.1. as this is major!

**Comment by wert2all** [comment]
If you find a copy of this issue,  please add a link to  the ticket and close this one.

**Comment by andidhouse** [comment]
Here is the other post:

https://github.com/magento/magento2/issues/5948

**Comment by andidhouse** [comment]
I can not close this one as it is not my ticket.

**Comment by wert2all** [comment]
@andidhouse Thank you for help. 

Closed as a copy.

**Comment by deepak-netwin** [comment]
hi,

I'm facing the issue, the associated product of configurable product is still showing at frontend in dropdown even if it is out of stock and qty=0. 
Does anyone knows the fix for this?
