### ISSUE TITLE
php indexer:reindex catalogsearch_fulltext unknow error

### ISSUE THREAD

**Issue by Vico1993** [magento/magento2#6181]
### Preconditions

1. PHP 5.6 / Mysql server 5.6.16 / Magento 2.1 
### Steps to reproduce

1. I try cmd : bin/magento indexer:reindex catalogsearch_fulltext
### Expected result

1. 
### Actual result

1. Error while sending QUERY packet. PID=8438 in /magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php on line 307
2. I have try to change my.conf, max_allowed_packet=64M but same error. 

Did I forgot something ?

**Comment by dthampy** [comment]
@Vico1993 , what did you change in the my.cnf file?
Also can you please try to  increase wait_timeout, connect_timeout and delayed_insert_time out values in addition to the max_allowed_packet and see if the error shows up ?

**Comment by Vico1993** [comment]
When I searched on google, I found that could be the max_allowed_packet, so i added this. 

```

[mysqld]
max_allowed_packet=64M

```

I will try with wait_timeout, connect_timeout and delayed_insert_time.

**Comment by Vico1993** [comment]
Ok @dthampy, now with something like this in my file /etc/mysql/my.cnf, i have the same issue. 

```
[mysqld]
max_allowed_packet=64M
wait_timeout=57600
connect_timeout=20
delayed_insert_timeout=600
```

**Comment by Vico1993** [comment]
Ok i found solution. It's my mysql server installation, with this params, indexer works perfectly :)

`[mysqld]
max_allowed_packet=64M
wait_timeout=57600
connect_timeout=20
delayed_insert_timeout=600`

thanks @dthampy  for your help

**Comment by dthampy** [comment]
Thanks for the update.
