### ISSUE TITLE
Notification shows so many time after refresh page or redirect to other page

### ISSUE THREAD

**Issue by Nehace40** [magento/magento2#6182]
![screen_shot_2016-08-04_at_5 08 02_pm](https://cloud.githubusercontent.com/assets/12808582/17697083/48e02ee6-63d0-11e6-95aa-382423689697.png)

Notification of 'AAA' product add to cart if i am add 'BBB' product to cart that time also both product notification showing but as expected result it should be shown only last product add notification. see attached image 

if i am refreshing page than notification won't go away. How to solve this in magento 2.1?

**Comment by andimov** [comment]
@Nehace40 
Thank you for reporting!
We already have this issue #5657. 
So I'm closing this one as duplicate. Please feel free to reopen if you need.
