### ISSUE TITLE
Switching to production mode - deploying static content

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#6185]
I'm trying to switch to production mode on our live server.

Running CE 2.1.

```
bin/magento setup:upgrade

bin/magento indexer:reindex

bin/magento deploy:mode:set production -s

bin/magento setup:di:compile 

bin/magento setup:static-content:deploy
```

The final command throws the following error, and as a consequence non of the css/js is loaded, the site is unstyled.

```
Uncaught Error: Class 'Magento\Indexer\Model\Config\Reader' not found in /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#1 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Indexer...')
#2 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/app/code/Manadev/Core/Registries/ConfigurationReaders.php(32): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Indexer...')
#3 /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Manadev\Core\Registries\ConfigurationReaders->__co in /chroot/home/amritanu/amritanutrition.uat.quba.co.uk/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
```

I've tried deploying static content before running the compile command but this doesn't work either. 
After running compile all subsequent commands throw this error. 

I'm not sure what i'm doing wrong here?

**Comment by BaDos** [comment]
Hi, sma09sjb!

Do you have the same issue on the latest version?
Cannot reproduce on 2.1.2.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by baltechies** [comment]
Hi,
I have same error while enabling production mode. Magento version is 2.1.5


PHP Fatal error:  Uncaught Error: Class 'Magento\Indexer\Model\Config\Reader' not found in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Indexer...')
#2 /opt/bitnami/apps/magento/htdocs/app/code/Manadev/Core/Registries/ConfigurationReaders.php(32): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Indexer...')
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Manadev\Core\Registries\ConfigurationReaders->__construct(Object(Magento\Framework\ObjectManager\ObjectManager), Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/fram in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 [] []

**Comment by korostii** [comment]
@baltechies, there is one small yet important clue common to both yours and @sma09sjb's traces, which is the `app/code/Manadev/Core/Registries/ConfigurationReaders.php` file. I would guess that whichever of the Manadev's modules you happen to be using are probably the root cause of the issue and are either buggy or outdated. 
I'd suggest you try to disable those in order to confirm the 3rd-party code is the cause of the issue and contact Manadev for an update/fix.

**Comment by baltechies** [comment]
@korostii  Yes. app/code/Manadev/Core/Registries/ConfigurationReaders.php is causing the issue. If I am disabling this module then it cause the issue on site. 
Now I am trying to create a site from scratch.

**Comment by korostii** [comment]
Wow, "from scratch" sound like a lot of work. If the module vendor (which seems to be https://www.manadev.com/ in this case, right?) is unable to provide you with a fix, it might turn out to be more cost-effective for you to create a small local workaround yourselves. 
It might just be enough to update the usages of this old class name manually like this http://take.ms/W16EN
Good luck.

**Comment by baltechies** [comment]
@korostii Great man. I am looking for this solution. Thank you for the link ([ http://take.ms/W16EN](http://take.ms/W16EN)).  Now I can use old modules in my project.

Create a site from scratch was the requirement of the project.
