### ISSUE TITLE
Date creation not consistent with Magento/DateTime with french format

### ISSUE THREAD

**Issue by ChristopheFerreboeuf** [magento/magento2#6187]
### Preconditions
Magento `develop` branch

When you try to create a date with magento datetime the format is forgotten during the process. 
The function date calls $this->timestamp($input) that contains a strtotime when the input is a string. Therefore, the function strtotime returns false because it does not take in account the format given.
We need to consider whether we change the description of the function to tell that the input string must be a valid **string containing an English date format** as [strtotime](http://php.net/manual/en/function.strtotime.php) needs or to try to find a more general workaround.
### Steps to reproduce

Try to format a date using \Magento\Framework\Stdlib\DateTime\DateTime->date("d/m/y", "15/08/2016")
### Expected result

Should return "15/08/16"
### Actual result

Returns "16/08/16" 
### Workaround

A workaround for french date can be found there : http://stackoverflow.com/questions/2891937/strtotime-doesnt-work-with-dd-mm-yyyy-format

**Comment by magento-engcom-team** [comment]
@ChristopheFerreboeuf, thank you for your report.
We've created internal ticket(s) MAGETWO-82303 to track progress on the issue.

**Comment by MelissaEbizmarts** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@MelissaEbizmarts thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by simon-letch** [comment]
#mmuk2019

**Comment by magento-engcom-team** [comment]
@simon-letch thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@ChristopheFerreboeuf, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
