### ISSUE TITLE
Single Magento installation with multiple websites and domains. Customer Login session.

### ISSUE THREAD

**Issue by AlfredoGH** [magento/magento2#6188]
How to have a single Customer Login in differents Domains?
I had read a lot but not found a concrete solution about how to keep Logged in a customer that goes from site www.abc.com to www.xyz.com
What is the best solution to do this?
- I have one Magento installation. 2 Websites created with different domain names.
- I'm already Sharing the Customers Users, it is set it up as Global.

There is not any link to send any parameter. The user switches from site 1 to site 2 writting the URL directly.

**Comment by veloraven** [comment]
@AlfredoGH please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As the GitHub issue tracker is intended for technical issues only.
