### ISSUE TITLE
A final "@" in Magento 2 admin address leads to static files links error

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#6189]
In version 2.0.2 , 2.0.6, 2.1.0 we'd advise to not use a final "@" in your Magento 2 admin address:
i.e. with a final "@" in env.php you could see (correctly):

array (
    'frontName' => 'myadmin@',
  ),

That will lead to a modification of some links that point to the static files (in Production).
i.e. mysite.com/myadmin@  will become the follow link:  mysite.com/myadmin@mysite.com/
leading to the impossibility to reach some static files (for us, see attachment, are the js static files of the tiny_mce plugin)

Tested with Magento 2.0.2 , 2.0.6, 2.1.0 - Production mode
### Steps to reproduce

Just use a final "@" in your Magento admin address. 
Then go to Content ->  Pages -> Privacy Policy -> **click on** "Show/Hide editor"
### Expected result

Toggle of tiny_mce wysiwyg editor
### Actual result

IT WON'T WORK and you'll see static files link errors in the console.
![2 0 7 tiny_mce error](https://cloud.githubusercontent.com/assets/11228308/17714649/7d05e0aa-63b5-11e6-825b-a558632d4654.jpg)

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-58284, thanks for reporting

**Comment by piotrekkaminski** [comment]
@romeof1980  http://www.ietf.org/rfc/rfc1738.txt @ is a reserved character and cannot be used in URL.
