### ISSUE TITLE
Html validator

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#619]
Good solution integrate HTML Purifier into Magento. It help validate html code for unclosed tags. Sometimes in static blocks and pages html code not clear.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-27039

**Comment by tkacheva** [comment]
@Den4ik Just wonder if you have any updates?

**Comment by kandy** [comment]
https://github.com/Masterminds/html5-php - look like applicable html5 validation library

**Comment by cluppeer** [comment]
hi,
I have problems with unclosed html tags, thousands of html contents needs to be validate. Other static blocks doesnt show up properly. I need someone advise me something. 
thanks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Html-validator/idi-p/46218).
