### ISSUE TITLE
Product Attribute Delete Button not found.

### ISSUE THREAD

**Issue by juanmrad** [magento/magento2#6190]
I can't delete any product attribute since I can't select them or click any delete button. Also when editing them there is no delete option.

![screen shot 2016-08-16 at 4 37 22 pm](https://cloud.githubusercontent.com/assets/5447733/17716783/d3ae79c0-63cf-11e6-9a86-f2f10301196b.png)

**Comment by juanmrad** [comment]
This is not a question is an issue you are supposed to be able to delete attributes from the backend.

**Comment by pboisvert** [comment]
@juanmrad To delete a product attribute, click on the one you wish to delete and once that loads you will see a "Delete Attribute" option at the top. Closing as not an issue

**Comment by juanmrad** [comment]
Look.
![screen shot 2016-08-18 at 10 56 10 am](https://cloud.githubusercontent.com/assets/5447733/17780846/787d4d42-6532-11e6-940c-e3f68ec90a7d.png)

**Comment by pboisvert** [comment]
Can you provide system information such as Magento version and system configuration per the reporting guidelines? Also have you upgraded from an earlier version to a newer version?

**Comment by juanmrad** [comment]
Magento 2.1.0
Nginx Server.
No I haven't done any upgrades

**Comment by allanpaiste** [comment]
Certain attributes can not be deleted as they're part of system-critical processes. A good example of this is the "sku" attribute, which is listed in product attributes, but can't be removed. 

auto_bill is probably similar to that.

Things that you can delete via admin are usually the ones marked as "user defined" in DB in eav_attribute table. So if you, say, switch is_user_defined flag for "sku" attribute to be '1' and reload the attribute admin page for "sku", you'll get your delete button.

I would be cautious removing attributes that have it set to 0, but it might be just a mistake from whoever defined it in the 3rd party module installation scripts. In that case, you can fix it by manipulating the value in eav_attribute, but be sure absolutely sure that it does not break any module logic :)

Everything added via admin gets this flag automatically set to '1' which you can test by creating an attribute and editing it right after the creation.

**Comment by rip057** [comment]
![nodeleteattribute](https://cloud.githubusercontent.com/assets/10294642/21410016/6d8e5808-c7a3-11e6-9f6b-fa33f6c70647.jpg)

see how where it says add attribute it should say delete?

also  last five lines of magento2/var/log/system.log say
[2016-12-21 23:22:43] main.CRITICAL: Broken reference: No element found with ID 'delete'. [] []
[2016-12-21 23:25:01] main.CRITICAL: Broken reference: No element found with ID 'delete'. [] []
[2016-12-21 23:30:10] main.CRITICAL: Broken reference: No element found with ID 'before.body.end'. [] []
[2016-12-21 23:30:10] main.CRITICAL: Broken reference: No element found with ID 'delete'. [] []
[2016-12-21 23:30:59] main.CRITICAL: Broken reference: No element found with ID 'delete'. [] []

**Comment by allanpaiste** [comment]
Looks like unrelated issue when compared with the OP's description.

But. It does look like something that deserves it's own ticket :)

**Comment by rip057** [comment]
"I can't delete any product attribute since I can't select them or click any delete button. Also when editing them there is no delete option."  --op original statement

I'm willing to bet if he would look at his magento2/var/log/system.log there would be an enormous amount of 

main.CRITICAL: Broken reference: No element found with ID 'delete'. [] []

I see that the delete element is in magento2/app/etc/di.xml. Do I not have correct permissions?  I guarantee he and I are experiencing the exact same problem just on different pages.  We both don't have a delete element,. There is only one delete element in magento2 amiright?

**Comment by veloraven** [comment]
@juanmrad is this issue still actual?
We are not able to reproduce it. And as I see on the screenshot from the first message 'auto_bill' attribute is marked as system, so you should not have possibility to delete it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by Nolwennig** [comment]
@juanmrad 

1. Go to MySQL CLI and run: 
`update eav_attribute set is_user_defined = 1 where attribute_code = 'auto_bill';`

2. Go to admin panel: _Stores > Attributes: Products_ > Select `auto_bill` and **delete** it with top button

**Comment by tuanhai363** [comment]
after delete attribute  create on magento admin, I create module new to add attribute product
after that I go to admin and add new product happen error : 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento3.catalog_product_entity_number' doesn't exist, query was: DESCRIBE `catalog_product_entity_number`
anything idea help me
