### ISSUE TITLE
content:deploy Error zendframework

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#6192]
Hello,
we get the following error message while content:deploy:

```
  [Exception]
  Warning: Error while sending QUERY packet. PID=31459 in /var/www/vhosts/***/magento2/vendor/magento/zendframework1/library/Zend
  /Db/Statement/Pdo.php on line 228
```

How we can solve the issue?

We are using Magento 2.1.0

**Comment by wert2all** [comment]
This is an issue of Mysql. You can read about this  [here](http://stackoverflow.com/questions/30753674/error-while-sending-query-packet)

**Comment by klarlichter** [comment]
Hello, we had change like your page but we still get that error. How we can solve that bug?
