### ISSUE TITLE
Magento 2.0.7 Import Products sets default behaviour as append, need add_update

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#6193]
I am importing the products using array instead of csv, And using [FireGento_FastSimpleImport2](https://github.com/firegento/FireGento_FastSimpleImport2) Module to pass the product array to the import model. I have set the behavior of import to be  'add_append', but [getBehavior() method](https://github.com/magento/magento2/blob/develop/app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php#L513-L525) in the `Magento/ImportExport/Model/Import/Entity/AbstractEntity` class checks the condition and sets behavior as 'append'. I need to know why the product import does not allow `add_update` behavior? i believe that the `append`  is responsible for multiple stock item entries in the table `cataloginventory_stock_item` for same item, which generates error in the catalog product grid.

**Comment by shiftedreality** [comment]
Hi @Taral-Patoliya 

Looks like an error to me.
Created internal ticket MAGETWO-58210 to investigate and fix.
Thank you for reporting.

**Comment by sylvainraye** [comment]
Also into **Magento 2.1.7** and **Magento 2.2**

Looks like an issue into the method `\Magento\ImportExport\Model\Import\Entity\AbstractEntity::getBehavior` which doesn't allow other behavior as append, replace and delete. Using custom or add_update is not allowed and fallback to append which is the default behavior

Need a PR ?

Patch in attachment


[patch_behavior_add_update_import.patch.txt](https://github.com/magento/magento2/files/1314250/patch_behavior_add_update_import.patch.txt)

**Comment by sylvainraye** [comment]
Why **G1 Failed** label ?

-> found myself the answer => https://github.com/magento/magento2/wiki/Magento-Issue-Gates

**Comment by magento-engcom-team** [comment]
Hi @diglin 
PR would be always helpful. If you wish to work on that please provide clear testing scenarios and link to this issue.

Thank you for collaboration

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#54
