### ISSUE TITLE
Magento 2 Payment Gateway Integration issue

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#6194]
### Preconditions

1. Magento 2.1.0
2. 
### Steps to reproduce

1. Go to <magento base folder>/app/
2. if "code" folder is already exists, then copy the "Ebs" folder and paste it inside "code" folder else create "code" folder and copy it.
3. Once "Ebs" folder is copied to "app/code" folder then go to <magento base folder>/bin in command line (CLI).
4. Type below listed commands
       4.1. php magento cache:clean
       4.2. php magento setup:upgrade
       4.3. php magento setup:di:compile
5. Once this is done,go to admin panel and STORES--->Configuration
6. Click on "Sales--->Payment Methods" menu in the left panel.
7. Configure "EBS Secure payment" options.
9. 
### Expected result

1. Should be able to see payment method in magento panel.
### Actual result

1. php magento setup:upgrade throws an exception error saying "setup.ser" not found in var directory.

**Comment by veloraven** [comment]
@adityag186 thank you for your feedback.
What does mean 'copy the "Ebs" folder'? Where do you take it from?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
