### ISSUE TITLE
Magento 2.1 visual swatch changes only the first picture of product

### ISSUE THREAD

**Issue by ps202** [magento/magento2#6195]
### Preconditions

Operating System: Ubuntu 15.10

PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper

Magento 2.1.0 CE
### Steps to reproduce
1. Install Magento
2. Create one configurable product with 2 images
3. Create configurations (simple products) for that configurable product (color, size for example)
4. Add 2 images to each simple product
5. Browse to the product and use the visual swatches to change the color
### Expected result
1. Clicking on the swatches should change BOTH images
### Actual result
1. Only the FIRST image changes, second image stays as it was before. Stepping through the images is weird, because first image is for example red, second white...

Configurable product with simple images:
![1](https://cloud.githubusercontent.com/assets/9308353/17731413/71942764-646d-11e6-99de-17b0b69e040a.png)

Images in the configurable product:
![2](https://cloud.githubusercontent.com/assets/9308353/17731418/7eb612a4-646d-11e6-825b-0536c6fb4d0b.png)

Images in the simple product:
![3](https://cloud.githubusercontent.com/assets/9308353/17731444/9e77c024-646d-11e6-9559-4d269e12520a.png)

Default product view:
![4](https://cloud.githubusercontent.com/assets/9308353/17731523/e5575194-646d-11e6-97e6-2b74ca403ef5.png)

Product view after clicking on the swatch:
![5](https://cloud.githubusercontent.com/assets/9308353/17731534/f2015764-646d-11e6-807b-bbe986e25b84.png)

Gallery view after clicking on the swatch:
![6](https://cloud.githubusercontent.com/assets/9308353/17731543/fc0f23bc-646d-11e6-9e8b-9d8abf542394.png)

**Comment by ps202** [comment]
Isssue is similar to this one here:
https://github.com/magento/magento2/issues/4101

**Comment by pboisvert** [comment]
Olena--can you check on this one? Seems like a duplicate.

**Comment by ps202** [comment]
Yeah, it seems to be a duplicate, but I think the other one was closed without providing a real solution. :(

**Comment by JesseEnd** [comment]
I'm having this same issue.

**Comment by tkacheva** [comment]
@JesseEnd @ps202 
Gallery supports several modes to show images from configurable options:
- Replace  images in gallery with the ones from configurable options
- Upend images from configurable option to the images in gallery

Currently the second option is broken. Internal issue MAGETWO-57210

**Comment by erikhansen** [comment]
@tkacheva Where would a merchant customize the gallery modes? Is this something they can do from the admin, or would a developer need to make (possibly in the `etc/view.xml` file)?

I was working with a merchant yesterday and uncovered that the Blank and Luma themes handle this differently: The Luma theme has the issue discussed in this issue. However the Blank theme works as you would expect: when a swatch is selected, all of the images of the simple product are shown in the gallery, not just the first one. So there is clearly something happening in the Luma theme that is causing different behavior from the Blank theme.

**Comment by ps202** [comment]
@tkacheva 
Replace is also not really functioning, because if I have 2 images in the gallery of the configurable product, and also 2 images in the gallery of the simple product (as displayed above), according to your comment, the replace function should replace the existing images in the gallery.
But it is only replacing the first one.
So I would say both options are broken, not only the second one.

**Comment by ps202** [comment]
@erikhansen @tkacheva 
I just tried out what Eric wrote above: I can confirm, that just switching to the Blank theme solves the issue...
Both images are changed, not just the first one.

**Comment by ps202** [comment]
Any update on this one?
Switching to the Blank Theme just raised more issues...

**Comment by tkacheva** [comment]
@ps202 @erikhansen 
Yes, the setting I'm referring to is available only for developers that allows to change it per theme. That's why gallery in Blank and Luma behaves differently. 

Work in progress

**Comment by ps202** [comment]
@tkacheva 
can you provide a workaround for luma?
thanks!

**Comment by ps202** [comment]
@tkacheva 
Does not matter, I found it.
/app/design/frontend/Magento/luma/etc/view.xml

Change these to false:

```
<vars module="Magento_ConfigurableProduct">
    <var name="change_only_base_image">false</var>
</vars>
<vars module="Magento_Swatches">
    <var name="change_only_base_image">false</var>
</vars>
```

**Comment by nelsonvpf** [comment]
@ps202 Well done. It's working now

**Comment by erikhansen** [comment]
@tkacheva I'm glad @ps202 found a workaround. While I understand that it may be easier from a development standpoint to make some settings be configured in `etc/view.xml`, this seems like a feature that would be ideal to have as an admin config setting. Just my two cents.

**Comment by carlowens** [comment]
👍 Thanks for the fix

**Comment by rashidtahir** [comment]
After implementing this solution images are now switching fine when selecting color swatches but we have video that's not showing now.When page load first time its show for couple of seconds and then it goes although we have assign video to simple products as well.

**Comment by thaddeusmt** [comment]
Just FYI, it appears that the way to change this functionality in your theme has changed a bit. The `change_only_base_image` option is gone. Now, in your theme's `view.xml`, you need to add this:

```
    <vars module="Magento_ConfigurableProduct">
        <var name="gallery_switch_strategy">prepend</var>
    </vars>
```

The default is `replace`, which `prepend` is overriding.

It appears that the Swatches module knows to look for this single setting, and you only need to set it on the ConfigurableProduct module.

**Comment by AngeloZou** [comment]
Magento 2.4.2 the same problem exists. Do you have a solution?

**Comment by AngeloZou** [comment]
Hi everyboby,
I found a solution, modify your magento2.4.2 view.xml
app/design/frontend/yourtheme/yourtheme/etc/view.xml
`    <vars module="Magento_ConfigurableProduct">
        <var name="gallery_switch_strategy">prepend</var>
    </vars>`
change into
`    <vars module="Magento_ConfigurableProduct">
        <var name="gallery_switch_strategy">replace</var>
    </vars>`

It works fine.
