### ISSUE TITLE
Magento 2.1 Redis Session Storage

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#6196]
I have followed the instructions here for Redis Session storage - 
http://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-session.html but no keys appear in the database?

**Comment by commcad** [comment]
The correct syntax below; with two ; added

`'session' => 
   array (
   'save' => 'redis',
   'redis' => 
      array (
	'host' => '127.0.0.1',
	'port' => '6379',
	'password' => '',
	'timeout' => '2.5',
	'persistent_identifier' => '',
	'database' => '0',
	'compression_threshold' => '2048',
	'compression_library' => 'gzip',
	'log_level' => '1',
	'max_concurrency' => '6',
	'break_after_frontend' => '5',
	'break_after_adminhtml' => '30',
	'first_lifetime' => '600',
	'bot_first_lifetime' => '60',
	'bot_lifetime' => '7200',
	'disable_locking' => '0',
	'min_lifetime' => '60',
	'max_lifetime' => '2592000'
    ),
),`

**Comment by bondimedical3** [comment]
I have done this already. The whole website crashes if you don't. Is there an xml file which needs active to be set to true?

**Comment by commcad** [comment]
I guessed but try to be a smartazz instead ;)

I use phpredis, you? You ran to the 'key & read' tests that redis recommend after installation? functional redis?

**Comment by commcad** [comment]
Here goes a functional redis env file. Currently in prod and works better than anything else I've tried. 

[env.php.txt](https://github.com/magento/magento2/files/422388/env.php.txt)

Look into phpredis. Simplicity and it works!
Luck2u

**Comment by bondimedical3** [comment]
The backend database has keys in it and Redis is working fine on my 3 other Magento 1 stores.

**Comment by commcad** [comment]
Great for ya, that info will fix everything! Read up, had a few questions for you.

Sorry can't help based on that mate. Sure Mage won't be able too, also

Tc

**Comment by bondimedical3** [comment]
Issue is fixed
