### ISSUE TITLE
Magento 2.0.7 Inserts duplicate duplicate entries of stock items after importing products

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#6197]
I am trying to import the simple products, using add_update behavior, But it inserts duplicate entries in  the table `cataloginventory_stock_item`.

This happens when the product is already there in magento and it is also there in the data being imported.

So instead of updating the stock inventory, it is adding a duplicate entry.

**Comment by palamar** [comment]
Thanks for the reporting.
Please provide Magento version that has an issue (2.0.0, 2.0.7, 2.1.0 etc.).
Also would be great to have sample of the CSV file that generate error (github allow attach files if they packed to zip)

**Comment by Taral-Patoliya** [comment]
@palamar I have already mensioned the magento version in the title of the issue, Which is 2.0.7,
And i am passing the array of the product to the import model, which is as follows.

`Array
        (
            [sku] => T050240606
            [attribute_set_code] => Default
            [product_type] => simple
            [product_websites] => base
            [name] => T050240606
            [price] => 0
            [visibility] => Catalog, Search
            [tax_class_name] => Taxable Goods
            [product_online] => 1
            [weight] => 0
            [short_description] => 
            [description] => SL.KOBL.I.E. ES06A06NM
            [is_in_stock] => 
            [qty] => 0
            [categories] => Hydraulics/Cylinders/Spare parts/Cylinder part - Others (Sub sourced)
        )
`

**Comment by palamar** [comment]
Thanks

**Comment by magento-engcom-team** [comment]
@Taral-Patoliya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
