### ISSUE TITLE
Admin gets redirected to dashboard

### ISSUE THREAD

**Issue by allanpaiste** [magento/magento2#6201]
If user is navigating in front-end and in admin at the same time (say, in different tabs), the user can unexpectedly be redirected to admin dashboard.
### Preconditions
1. have latest M2.1 installed
2. install demo data (using bin/magento demodata installation options)
3. clean browser cookies for the domain you're at (to make sure we start from clean slate)
4. make sure that you start with clean cache 
### Steps to reproduce
1. log into admin
2. [admin] navigate to PRODUCTS » Inventory » Catalog (the main thing here is not to remain on Dashboard)
3. [storefront] Navigate to men/tops-men/jackets-men
4. [admin] reload the page 
5. [admin] reload the page again
### Expected result
1. [admin] You remain on the PRODUCTS » Inventory » Catalog 
### Actual result
1. [admin] You end up on the Admin Dashboard
### Extra notes

This relates to PageCache mechanism that dumps from_key value from form_key cookie to the active session without checking the cookie path, which means that every admin url secure key will get invalidated. This will happen every time the form_key gets a new value.

The form_key replacement happens at the step-4

**Comment by vkorotun** [comment]
Hi @allanpaiste 
Thank you for reporting this issue.
Internal ticket: MAGETWO-57118

**Comment by maderlock** [comment]
Any progress on this? We only seem to have a problem when the admin and the frontend are on different URLS, which is the setup we have for larger clients, i.e. the ones who are more likely to be annoyed by being constantly redirected or even logged out.

**Comment by woutersamaey** [comment]
+1

**Comment by hostep** [comment]
It looks like this is already fixed on the develop branch. I think this commit fixed it: https://github.com/magento/magento2/commit/63bd96e354a11c1393fa17afb1d5c9b76b934c5c

**Comment by veloraven** [comment]
This issue has already been fixed in develop branch.
Internal ticket for version 2.1 - MAGETWO-58519 has also already been fixed. It will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment]
@allanpaiste, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by simonrl** [comment]
@magento-engcom-team could you please link the commit(s) that have fixed this behaviour? We need to backport it to 2.1.8

**Comment by hostep** [comment]
@simonrl: can you try the following commit (which I already referenced above): https://github.com/magento/magento2/commit/63bd96e354a11c1393fa17afb1d5c9b76b934c5c and let us know if this actually fixes the issue? Thanks!
