### ISSUE TITLE
[Magento_Theme] Add page_layout from module

### ISSUE THREAD

**Issue by kassner** [magento/magento2#6204]
Hi!

Looks like there is no way to add a new [page layout](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/layouts/layout-types.html) from a module. The only place that loads `layouts.xml` files is [here](https://github.com/magento/magento2/blob/37692c80f41e556e696803bbac8a93b8eb6837e7/app/code/Magento/Theme/Model/PageLayout/Config/Builder.php#L57-L65), but the method specifically iterate over registered themes and is `protected`, so is not possible to intercept using a plugin.

I'm not sure if we can just make it `public`. Is there another approach to fix this?

Thanks!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-Theme-Add-page-layout-from-module/idi-p/44686).
