### ISSUE TITLE
Missing checkboxes in the "edit address" page

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#6206]
### Preconditions
1. Magento 2.1.0, PHP 7.0.8, Ubuntu 16.04
### Steps to reproduce
1. Log in as a registered user.
2. Try to edit billing or shipping address.
### Expected result
1. At the bottom of the page, checkboxes should appear next to the lines: "Default billing address" and "Default billing address".
### Actual result
1. Checkboxes are not displayed, so the user can not set the address to be also their default billing/shipping address.

When user edits the **billing** address and save, the shipping address is set automatically to that address.
When user edits the **shipping** address and save, the billing address is set automatically to that address.

Therefore there is no way to set different addresses for both billing and shipping.

![edit-address](https://cloud.githubusercontent.com/assets/8398744/17745553/d5619f2a-6471-11e6-939a-7a99edc8c207.jpg)

**Comment by sevos1984** [comment]
What is your locale and what theme do you use? Have you generated static files for your locale?

**Comment by jibrandlr** [comment]
@sevos1984 locale is es_MX. I use a custom theme which inherits from the Blank theme. Static files have been generated for my locale

**Comment by sevos1984** [comment]
To localize problem could try switch to blank theme and/or change locale? I don't have this problem on luma theme and es_ES locale.

**Comment by jibrandlr** [comment]
@sevos1984 I tried changing to luma and blank theme, and to spanish (spain) locale, but the issue still present.
![luma-es_spain](https://cloud.githubusercontent.com/assets/8398744/18330161/9ea90250-751c-11e6-898d-2c7d2959627e.jpg)

**Comment by sevos1984** [comment]
There shouldn't be any checkboxes on page you attached if you have only one address. What if you add two or more addresses?

**Comment by jibrandlr** [comment]
@sevos1984 There is no way to set different addresses for both billing and shipping.
When user edits the **billing** address and save, the shipping address is set automatically to that address.
When user edits the **shipping** address and save, the billing address is set automatically to that address.

**Comment by sevos1984** [comment]
That is correct, as you use one address for billing and shipping. If you add new address and select 'Use as my default shipping address' your addresses will become independent and will be edited separately.

**Comment by jibrandlr** [comment]
@sevos1984 that's correct, i'm closing this issue
