### ISSUE TITLE
Parse error: syntax error, unexpected T_OBJECT_OPERATOR 

### ISSUE THREAD

**Issue by myst67** [magento/magento2#621]
Hi
getting this error while installing magento2 in localhost
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in C:\xampp\htdocs\magento2\app\bootstrap.php on line 65

**Comment by Jeeva-Rathinam** [comment]
> Hi @myst67, was the reason of the issue you experienced in the PHP version as @tzyganu suggested? If yes, please note that the minimum supported version of PHP for Magento 2 is PHP 5.4.
> 
> Please let us know whether the issue is gone now or is still valid for you. Thank you!

I ma using PHP 7.1.29 still i am getting error for install magento 2.3.3
