### ISSUE TITLE
Simple product is available on the swatches even when Quantity is 0 and is out of stock

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#6212]
### Preconditions
1. Magento 2.1.0, PHP 7.0.8, Ubuntu 16.04
### Steps to reproduce
1. Create a configurable product which includes 2 or more simple product configurations (Ex. size S and M)
2. Set the following values for one of the simple products (size M):
- Enable product: Yes
- Quantity: 0
- Stock status: Out of stock
1. Go to product page on front end. 
### Expected result
1. The option (size M) should not appear in the swatches since quantity is 0 and is out of stock.
### Actual result
1. That product option (size M) is available on the swatches even when Quantity is 0 and is out of stock. 
   (If user tries to add it to cart, magento displays the warning: This item is out of stock)

A simple fix is to manually change the status of that simple product from "Enabled" to "Disabled". However this should be done automatically. If there is only 1 unit left of that product and a user buys it, another user should not be able to see it as an available option.

When the last unit available has been sold, the status should be changed automatically to "Disabled" so it's not shown on product page.

**Comment by pboisvert** [comment]
Can you confirm that you haven't set Display Out of Stock products to yes (under Stores > Configuration > Catalog > Inventory)?

**Comment by jibrandlr** [comment]
@pboisvert Just confirmed that "Display Out of Stock Products" is set to **No**

**Comment by victor-v-rad** [comment]
Seems in #5948 described the same issue. Internal ticket MAGETWO-56480 to fix it.

**Comment by lucscu** [comment]
This bug is also present in catalog pages:
when you filter by super attribute like size, magento lists also configurable products that have its simple products for searched size out of stock.

**Comment by magento-engcom-team** [comment]
@lgarridoj, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
