### ISSUE TITLE
Multiple products updating attributes don't save when changing select values

### ISSUE THREAD

**Issue by wildekin** [magento/magento2#6217]
### Preconditions

1. Magento v2.1.0
2. PHP 5.6.20
3. MySQL 5.6.31
### Steps to reproduce

1. Select products from catalog, update attributes
2. Find a multiple selection field, chane that value, ie. Product Type
3. Save
### Expected result

1. Each selected product should reflect those changes made 
### Actual result

1. Products aren't updated with the new values

**Comment by wert2all** [comment]
Closed as copy of #5459
