### ISSUE TITLE
Label 'None' should not be translated in short description of product info

### ISSUE THREAD

**Issue by yariksheptykin** [magento/magento2#6218]
Product view page [contains a block](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml#L92) that displays short product description. This block renders `product/view/attribute.phtml` template and [passes](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml#L97) `at_label` to it set to `"none"`. Magento is however instructed to translate the label before passing it to the template (`translate="true"`). In the template file the label is displayed [only if its value is not](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml#L37) `"none"`. But since it is being translated, this condition only works for English locales.

**Comment by yariksheptykin** [comment]
Getting rid of `translate="true"` solves the problem.

**Comment by andimov** [comment]
@yariksheptykin 
Thank you for reporting!
I think this issue related to #5886.

**Comment by yariksheptykin** [comment]
Yeah, this one is a duplicate. Feel free to close.

**Comment by andimov** [comment]
Ok, thanks! I'll closed this ticket as a duplicate.
