### ISSUE TITLE
Wrong destination directory used to calculate absolute target path for renameFile in Directory Writer

### ISSUE THREAD

**Issue by dmitrisol** [magento/magento2#6219]
In Magento\Framework\Filesystem\Directory::renameFile(), the source directory is used to calculate target path for the file, instead of the destination directory, resulting in wrong target absolute path being calculated and file not moved to target location.
### Preconditions

Magento 2.0.7 to 2.1.0, not checked previous versions.
Any PHP or MySQL versions.
### Steps to reproduce

Sample code to demonstrate the issue

``` php
    /** @var \Magento\Framework\Filesystem $this->filesystem */

    $filename = 'test.csv';                
    $srcDir = $this->filesystem->getDirectoryWrite(DirectoryList::TMP);
    $srcDir->create();

    /** @var \Magento\Framework\Filesystem\Directory\Write $dstDir */
    $dstDir = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);
    $dstDir->create('myexport/orders');
    $srcDir->renameFile( $filename, 'myexport/orders/' . $filename, $dstDir );
```
### Expected result

File `test.csv` should be moved from `var/tmp/` folder to `var/myexport/orders/` folder, with the same name. This does not happen.
### Actual result

File is not moved from source to target directory.
### Proposed fix

``` php
// In vendor/magento/framework/Filesystem/Directory/Write.php:108
// replace:
    $absoluteNewPath = $targetDirectory->driver->getAbsolutePath($this->path, $newPath);
// with:
    $absoluteNewPath = $targetDirectory->driver->getAbsolutePath($targetDirectory->path, $newPath);
```

**Comment by picamator** [comment]
@dmitrisol  thank you for reporting.

Actually it is not an issue. 
The renameFile works with relative path, see `Magento\ImportExport\Model\Import.php` line 523 as example. So if you run `renameFile` from `$dstDir` it will work.

Modified code is bellow:

``` php
    $filename = 'test.csv';
    $srcDir = $this->filesystem->getDirectoryWrite(DirectoryList::TMP);
    $srcDir->create();

    $srcPath = $srcDir->getRelativePath(DirectoryList::TMP) . DIRECTORY_SEPARATOR . $filename;

    /** @var \Magento\Framework\Filesystem\Directory\Write $dstDir */
    $dstDir = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);
    $dstDir->create('myexport/orders');
    $distPath = '/myexport/orders/' . $filename;

    $dstDir->renameFile($srcPath, $distPath);
```

About your proposal solution. Magento 2 has nearly 26 places where `renameFile` is used without taking into account user extensions.
Therefore, changing method behavior would make to break all related code.
So that's why it's hardly seems to apply your suggestion.

Anyway thanks a lot for your research.

**Comment by dmitrisol** [comment]
The error reported is related to moving a file from a folder to another, not renaming it within the same folder, as my first message clearly explains. 

Say you have to move a file from folder A to folder B (not children of each other or even from "var/tmp" to "var"), which I believe the third parameter to renameFile() is for?

May I suggest you to give a little more credit to developers like myself who have to go through your code and debug it, and - at least - try to understand what the problem is about, before dismissing the issue as not existent?
