### ISSUE TITLE
FIX Magento Search Please!

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#622]
The more I think about the unwillingness to repair a major flaw in Magento the more I think about migrating to another platform. I've worked with so many ecommerce platforms that have zero problems with one of the most important storefront features "SEARCH". I've also watch so many customers search a site and leave the site because a search never presented the actually product the customer was looking for but the store possessed.... That is called a flaw!
Now I understand it's quite an undertaking, but putting it off or relying of someone else to provide such capabilities is not the solution either. I say we fix the issue and make it a top priority. NOW before 2.0 is released.
This is a major issue with magento and if you haven't noticed it yet then you haven't run a store... Period

**Comment by choukalos** [comment]
@barbazul - thanks for the insights on the PHPDig library ( http://www.phpdig.net/navigation.php?action=demo );  looks like the code hasn't been updated since late 2005.  I'll ask our search architect to look into it and how we might further change our search indexer/search algorithm to be more accurate.

**Comment by mattisbusycom** [comment]
I have built an ElasticSearch indexer for a client site; It works amazing and I am currently creating the module (learning how to build Magento modules); but I am very experienced with ElasticSearch in general.

**Comment by alankent** [comment]
We would be very interested to hear how successful you are swapping out the default search engine. Have we go the APIs right to make it easy to drop in a different engine? Feedback and suggested changes appreciated. (We don't have much documentation done where the interfaces are, and this is relatively low priority to other documentation. If you are unsure from looking at code, feel free to ask questions.)

**Comment by choukalos** [comment]
Search features currently slated for inclusion in 2.0
- enhanced mysql search accuracy ( many points per comments above )
- APIs for search indexers
- [Enterprise] Support for SOLR 4.x

Search Epics likely in 2.1 - 2.3 release time frame
- MAGETWO-23112 : Search Autocomplete & Preview
- MAGETWO-11439 : Search CMS
- MAGETWO-10479 : Updated Search UX and Control
- MAGETWO-10478 : Manage relative weightings of search terms 
- MAGETWO-10475 : [ EE ] Synonyms & Stop words GUI
- MAGETWO-10480 : [ EE ] Search - Promoted Products
-

**Comment by choukalos** [comment]
Sorry my bad; shouldn't have closed the issue.

**Comment by aoldoni** [comment]
For Enterprise, I would recommend probably to change the roadmap to move straight into Solr 5.3.0?
http://www.apache.org/dyn/closer.lua/lucene/solr/5.3.0

**Comment by choukalos** [comment]
@aoldoni we've decided to move to elastic search instead for enterprise.  You'll see that happen in the Magento 2.1 release.  Elastic search provides more functionality as a stack component than Solr does and gives us the potential to build out the platform on several interesting fronts.

**Comment by aoldoni** [comment]
@choukalos - Given the roadmap above, would you please be able to detail in which version (e.g.: 2.1, 2.2, etc..) these 2 tickets are planned to be released into?

MAGETWO-23112 : Search Autocomplete & Preview
MAGETWO-11439 : Search CMS

Thanks!

**Comment by choukalos** [comment]
Hi @aoldoni we're an agile company so we're constantly revising our roadmap and epics based on customer feedback and how we can maximize the value we deliver in each release as such there's no commitment to a specific release.  All I can say is search is one of our higher priority items and likely to get some attention in 2016.

**Comment by southerncomputer** [comment]
https://github.com/Smile-SA/elasticsuite/tree/feature_magento-2.1-upgrade

https://github.com/Smile-SA/elasticsuite

Smile SA has always produced quality open-source Elasticsearch for magento1 and magento2 now along with their virtual categories and integrated search feedback system.

**Comment by choukalos** [comment]
@southerncomputer yes Smile's got some great Elasticsearch extensions for Magento.  Really happy to see they've started porting their M1 extension to M2.

**Comment by s00071609** [comment]
I am not sure if this is off topic - i did not want to open a new thread. I am using magento 2.1 (upgraded from 2.0 to 2.1) recently. Just realised that the search term shows blank. Havent touched the default footer links and appear fine. But when the search term is clicked, no text - its blank.
Can check - https://jostechecig.com.au
Not sure if its a new bug, i also have a magento 2.0, search term shows all the search terms.

Is anyone having this issue? Any suggestions?

**Comment by Ctucker9233** [comment]
@s00071609 I had an issue after upgrading from 2.0.7 to 2.1.0 where the search bar was missing. I'm not sure if that's what you mean. I ended up deleting the vendor folder entirely and transferred in a clean 2.1.0 vender folder to replace it. It fixed the issue.

**Comment by s00071609** [comment]
No not the search bar. Looks like one issue ends and another pops up with magento. Somewhere something is always going wrong.

My html Head section is also missing. After upgrade the exisiting bundle products dont have bundle option. But the frontend works fine.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/FIX-Magento-Search-Please/idi-p/47042).

**Comment by VladimirZaets** [comment]
Hi @gfxguru. Thank you for your report. 
The issue has been fixed in magento/magento2#25556 by @engcom-Golf in 2.3-develop branch
Related commit(s):
 - [f22905662aeda6a0f2c073d650326dd6c2a6fd93](https://github.com/magento/magento2/commit/f22905662aeda6a0f2c073d650326dd6c2a6fd93)
 - [a07627c9b0c8dcb600cc1109a65c5a08ab375a71](https://github.com/magento/magento2/commit/a07627c9b0c8dcb600cc1109a65c5a08ab375a71)
 - [8e39f49b48692f2e820066815244e8532c247fde](https://github.com/magento/magento2/commit/8e39f49b48692f2e820066815244e8532c247fde)
 - [3be5ac8e2e83415b8cafc340486b298038ed0421](https://github.com/magento/magento2/commit/3be5ac8e2e83415b8cafc340486b298038ed0421)
 - [76a866ec70987dfb0e1c778db472a06c6d738781](https://github.com/magento/magento2/commit/76a866ec70987dfb0e1c778db472a06c6d738781)
 - [26dca1007e2458e29419ae5ecf7b77e0c1560658](https://github.com/magento/magento2/commit/26dca1007e2458e29419ae5ecf7b77e0c1560658)

The fix will be available with the upcoming 2.3.5 release.
