### ISSUE TITLE
Checkout doesn't work for lingual URL

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#6220]
If set Base Link URL with a language code, for example http://website.com/fr/, then checkout isn't working because of AJAX query to /fr/rest/fr_be/V1/carts/mine/estimate-shipping-methods returns 404.

### Preconditions

Magento 2.1.0
### Steps to reproduce

1. Add language code to the Base Link URL e.g. http://website.com/fr/
2. Flush caches
3. Go to checkout, it won't work

**Comment by victor-v-rad** [comment]
Hi @vesan-83 

Could not reproduce the bug. But my AJAX query /fr/rest/fr/V1/carts/mine/estimate-shipping-methods is a bit different. 
your: .../rest/fr_be/V1... 
my:   .../rest/fr/V1...
Can you clarify what you did to have fr_be in query?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
