### ISSUE TITLE
How to authenticate customer via SOAP in Magento2?

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#6223]
### Preconditions

1. Magento 2.1.0 CE & EE
2. MySQL 5.6
### Steps to reproduce

1. Open WSDL via browser or SoapUI tool: `http://{magento-2-base-url}/soap/default?wsdl&services=customerAccountManagementV1`
2. You will only see few methods: `customerAccountManagementV1CreateAccount()`, `customerAccountManagementV1InitiatePasswordReset()`, `customerAccountManagementV1IsEmailAvailable()` & `customerAccountManagementV1ValidateResetPasswordLinkToken()`
3. If you check the code: `$client = new SoapClient('http://{magento-2-base-url}/soap/default?wsdl&services=customerAccountManagementV1', $soapOptionsWithBearerTokens); var_dump($client->__getFunctions());`
4. You can see much more available methods. But still `authenticate()` method which is mentioned in service contract (Magento\Customer\Api\AccountManagementInterface) is missing.
### Expected result

1. I would want to see the `autheticate()` method in the list so that we can authenticate the customer via web service.

May be I am missing something but badly needed the feature to authenticate the customer via Web Service (SOAP).
### Questions:
- Why methods are limited for anonymous users? If this is the case how protected methods can be tested with tools like SoapUI ?
- How customer is authenticated with SOAP web services? Any other workaround? Even we are not getting password_hash in any response.

Waiting for the feedback.

**Comment by TomashKhamlai** [comment]
Hello @MagePsycho! I will try to answer your questions.
Yes, there it's true there are only 4 available methods in SOAP UI. I am not able to answer the question "Why?"

I am able to authentificate via cURL. I suppose that it is easy to adapt my cURL commands to PHP_CURL script.
### Instruction:
1. Create file curlsoap.xml and paste this template:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://__Your_Domain__/soap/default?services=integrationCustomerTokenServiceV1">
   <env:Body>
      <ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenRequest>
         <username>__User_Email__</username>
         <password>__User_Password__</password>
      </ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenRequest>
   </env:Body>
</env:Envelope>
```
2. Fill the actual information instead of __Your_Domain__, __User_Email__, __User_Password__.
3. Copy this to UNIX-friendly CLI:
```
curl -X POST \
-H 'Content-Type: application/soap+xml; charset=utf-8; action="integrationCustomerTokenServiceV1CreateCustomerAccessToken"' \
-d @curlsoap.xml http://__Your_Domain__/soap/default?services=integrationCustomerTokenServiceV1
```
4. Press \<Enter\> to send the request.
Expected result:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://__Your_Domain__/soap/default?services=integrationCustomerTokenServiceV1">
    <env:Body>
        <ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenResponse>
            <result>__Here_is_customer's_token__</result>
        </ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenResponse>
    </env:Body>
</env:Envelope>
```

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
