### ISSUE TITLE
Checkout Agreement validation is broken on payment method change

### ISSUE THREAD

**Issue by shortner** [magento/magento2#6224]
Magento_CheckoutAgreements does not display validation message for Terms and Condition item after change of payment method.

**Preconditions**
1. Install Magento 2.1

**Steps to reproduce**
1. Create a Term and Condition entry under Stores > Terms and Conditions
2. Activate Terms and Conditions for checkout under Stores > Sales > Checkout > Enable Terms and Conditions
3. Enable a second payment method
4. Go through checkout
5. On Review & Payments step select a payment method
6. Click Place Order
7. Validation message for Term and Condition entry appears
8. Select different payment method
9. Click Place Order
10. No validation message appears

**Expected result**
1. Validation message for unaccepted Term and Condition entry appears

**Actual result**
1. No validation message for unaccepted Term and Condition entry appears

**Comment by bka** [comment]
Same issue here. Seems to be in `Magento/CheckoutAgreements/view/frontend/web/js/model/agreement-validator.js`, `errorPlacement` is only called once and places the label after the active checkbox. But every payment method has its own checkboxes.

**Comment by bka** [comment]
This seems to solve the issue for me.

**Comment by victor-v-rad** [comment]
Internal issue MAGETWO-57682 was created to fix this

**Comment by SerhiyShkolyarenko** [comment]
The fix is delivered to develop branch. Closing the issue.

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko Will MAGETWO-57682 be included in 2.1.3?

**Comment by thoho-mpa** [comment]
Now the Checkout-Agreements does not work, I have a Magento 2.1.10 with Checkout-Agreements enabled (Manuel - with Checkbox).

I can Place the order without checking the Agreement.

**Comment by thosch-mpa** [comment]
Now the Checkout-Agreements does not work, I have a Magento 2.1.10 with Checkout-Agreements enabled (Manuel - with Checkbox).

I can Place the order without checking the Agreement.

**Comment by Rekha-periasamy** [comment]
I have upgraded to Magento 2.1.12. I have applied 6224. Still it's not working. I;m able to place order without choosing checkout agreements and it's doesn't show any validation message. I need a fix for this issue urgently. Kindly help

**Comment by david-fiaty-cko** [comment]
is there any progress on this bug? I am on Magento 2.2.5 and the issue is still there. The workarounds suggested above don't fix it.

**Comment by rdudhara** [comment]
Is there any progress to fix into 2.1.9?

**Comment by magento2dev** [comment]
Does anyone has a fix I still have the issue on 2.2.3 and the fix above do not work ?

Thanks
