### ISSUE TITLE
Magento 2.1 Attributes with multiple choice fields cannot be mass updated

### ISSUE THREAD

**Issue by eharvest** [magento/magento2#6226]
### Preconditions

1. Magento 2.1 
### Steps to reproduce

1. Create custom attributes with multiple choice fields
2. Try to select a number of products and update this attribute value (even just two products)
### Expected result

1. The attribute gets updated
### Actual result

1. Update successful but attribute didn't get updated

**Comment by victor-v-rad** [comment]
I have manage to reproduce the bug. Internal ticked is MAGETWO-55054

**Comment by magento-engcom-team** [comment]
@eharvest, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
