### ISSUE TITLE
Why so many unnecessary dependencies?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6229]
I see a lot of unnecessary dependencies in project.
For example, https://github.com/magento/magento2/pull/6228/files.

I propose to remove them.

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by antonkril** [comment]
These dependencies are not created intentionally. We'll think of static test that will check for unused includes.
