### ISSUE TITLE
Double single quotes in product title break tabs on frontend

### ISSUE THREAD

**Issue by devhn** [magento/magento2#6230]
### Preconditions

1. Magento 2.0.7
2. Apache 2.4, PHP7
### Steps to reproduce

1. Create a new product
2. Type a product title with '' at the end (2x single quotes)
3. Save it and check product on frontend
### Expected result

1. The tabs (details, more info, reviews) should not be altered
2. Upon saving the product Magento shouldn't let user save the product if special chars are not permitted
### Actual result

1. The tabs get special error css rules attached (.info selector) which creates repeating light bulbs gif image: [reference image](http://i.imgur.com/zUNZJ2p.jpg)
2. Frontend css get's partially broken
3. No error was shown within administration upon saving the product

**Comment by wert2all** [comment]
I cannot reproduce the issue.
Please try to upgrade Magento or describe all steps you have done in a more detailed way.
