### ISSUE TITLE
Multiple JS errors in Magento 2.1.0 

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#6235]
### Preconditions

1. Install Magento2.1.0 
2. Generating a theme, depending on magento-blank
3. Using your freshly used theme and make some CSS changes 
### Steps to reproduce

1. Check console, thats it. There are the debug logs. 
### Expected result
1. No JS errors and stuff should be running fine (opening side nav, using the minicart, ...)
### Actual result

1. JS errors in require JS

Error-Code from Chrome console:
mixins.js:5 Uncaught ReferenceError: define is not defined(anonymous function) @ mixins.js:5
requirejs-config.js:48 Uncaught TypeError: require.config is not a function(anonymous function) @ requirejs-config.js:48(anonymous function) @ requirejs-config.js:49(anonymous function) @ requirejs-config.js:580
(index):32 Uncaught TypeError: require.config is not a function(anonymous function) @ (index):32

Files I have in mind doing the trouble:
web/requirejs/require.js. 

Content: 

```
var config = {
    map: {
        '*' : {
            'owlcarousel' : 'js/owl-carousel/owl.carousel'
        }
    },
    shim: {
        "owlcarousel": {
            deps: ["jquery"]
        },
    },
};
```

The fun thing is, we are using the very same File in another installation where it runs fine. I know that the is place for a requirejs-config.js in the themes root folder, but anyhow our developer used this file for a long time. Is it bad manner? 

As I write this, I just found out that deleting the folder resolves the bugs. The main question now is: whats wrong with the file. Is there any typo?

**Comment by mrkhoa99** [comment]
@grasdaggel it's better if you should post your issue on http://magento.stackexchange.com/

**Comment by grasdaggel** [comment]
I understand that Github is not a "I have a problem, but its not a bug, but please help me" platform. Anyhow, if there is content, it should be linked by devs or community contributors.

I've just resolved my problem by using this article: http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html

Hope it helps people in the future.
