### ISSUE TITLE
How to redefine interface?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6236]
I need to add custom attributes in Sales Order for REST API.

I finally figured out how to do it.

I need to redefine Magento\Sales\Api\Data\OrderSearchResultInterface

``` php
    /**
     * Get items.
     *
     * @return \Magento\Sales\Api\Data\OrderInterface[] Array of collection items.
     */
    public function getItems();
```

to

``` php
    /**
     * Get items.
     *
     * @return \Vendor\OrderAttributes\Di\Sales\Api\Data\OrderInterface[] Array of collection items.
     */
    public function getItems();
```

How to do it?

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by kassner** [comment]
Not sure if REST API classes work in a different way, but usually you can define which class a particular interface should resolve to using `<preference>`.

http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html#abstraction-implementation-mappings

**Comment by springimport** [comment]
It doesn't work for the interfaces.

Default usage:

``` xml
<preference for="Magento\Core\Model\UrlInterface" type="Magento\Backend\Model\Url" />
```

Interface -> Class

I need to:
Interface -> Interface

**Comment by MagePsycho** [comment]
Friendly Reminder!

**Comment by mbrinton01** [comment]
Hello @springimport, GitHub issues are intended for bug reporting only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to open another issue if you think you have encountered a bug in Magento 2.

**Comment by SerhiyShkolyarenko** [comment]
@springimport redefining interfaces is not supported in Magento 2. Substitution of returned type would break all the extensions which use it.
If you need to add your data to the data interface, please, use extension attributes.

**Comment by MagePsycho** [comment]
Can anyone explain 'How to add new order field for API: `/V1/orders/:id` without using `extension_attributes`?
http://magento.stackexchange.com/questions/137703/adding-new-order-field-for-api-v1-orders-id-without-using-extension-attribute

**Comment by SerhiyShkolyarenko** [comment]
@MagePsycho 
No other way except extension attributes is implied.
