### ISSUE TITLE
Meta description allows too many characters

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#6238]
I'm noticing that my magento setup is allowing any number of characters in the meta description field. It used to automatically cut off the description if I exceeded the maximum amount of characters while typing. Now, it allows any amount and only cuts it off after saving the product.
### Preconditions

Magento 2.1.0
PHP 5.6.22
Upgraded From Magento 2.0.7
### Steps to reproduce
1. Create a new product (type of product doesn't seem to matter)
2. Fill in meta description.
3. Save
### Expected result
1. Meta description automatically cuts off the characters if character limit is exceeded before save.
### Actual result
1. Meta description allows the number of characters to exceed the limit and only cuts off the extra characters on save. See screenshots.

Pre-save
![pre save](https://cloud.githubusercontent.com/assets/19523985/17790978/c84d70ca-654d-11e6-8f11-62d2b756dbce.JPG)

post-save
![post save](https://cloud.githubusercontent.com/assets/19523985/17790992/daf19ee0-654d-11e6-8903-68504c931c39.JPG)

**Comment by sevos1984** [comment]
This is a known issue MAGETWO-3254. Thanks for posting

**Comment by Ctucker9233** [comment]
@sevos1984 Wow! Judging by the magetwo number it's a pretty old known issue. Are we close to a fix?

**Comment by sevos1984** [comment]
Yep, old one, but it has low priority. Not sure it will be fixed soon.

**Comment by Ctucker9233** [comment]
@sevos1984 Man, too bad. It creates a lot of extra work having to go in, tweak the meta description, save, then go back and check. Then repeat as necessary.

**Comment by maderlock** [comment]
It's an easy fix - just add maxlength="255" (or whatever the maximum is) to the textarea. So it's odd that this has not been fixed as low hanging fruit.

**Comment by Ctucker9233** [comment]
@maderlock what file and line does this code go in?

**Comment by magento-engcom-team** [comment]
@Ctucker9233, thank you for your report.
We've created internal ticket(s) MAGETWO-3254 to track progress on the issue.

**Comment by lewisvoncken** [comment]
@magento-engcom-team pull request has been created in the partner github
https://github.com/magento-partners/magento2ce/pull/61

**Comment by lewisvoncken** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release

**Comment by Ctucker9233** [comment]
@okorshenko Great! When will the fix be backported to 2.1?
