### ISSUE TITLE
Unnecessary hardcoded validation of customer/address attributes

### ISSUE THREAD

**Issue by nkajic** [magento/magento2#624]
Hi all,

I am first time here, so sorry if question is stupid but:

I have one concern about validation in Magento/Customer/Model/Address/AbstractAddress.php::validate().

Why are we inside validate() still checking for value of 'telephone' if it can be set as "is_required = false" inside eav_attributes table and it is not required of delivery.

**Comment by maksek** [comment]
@nkajic  If you have additional question, please feel free to reopen the issue with attitudinal comments. For now we are going to close the issue due long time inactivity from creator side.
