### ISSUE TITLE
Change class members from 'private' to 'protected'

### ISSUE THREAD

**Issue by hiephm** [magento/magento2#6241]
@alankent 
Right now there are many classes that usually be inherited but all of their members are private (for example \Magento\Payment\Model\Method\Adapter).
For child classes to use their parent members, we must re-declare constructor and all members again, which is not very convenience.

I know that OOP good practice is keeping member as much private as possible. But given the extensible nature of Magento, I think most of the private member can be safely changed to protected.

**Comment by maderlock** [comment]
I've come across this too, though more often it's just one or two things that are private making them hard to extend.

In addition, there are too many methods protected which means that plugins cannot be used with them, making the plugin mechanism rather less useful than maybe the creators expected.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Change-class-members-from-private-to-protected/idi-p/44967).

**Comment by maderlock** [comment]
Do we have any guarantee that you won't just delete the forums like you did last year?
