### ISSUE TITLE
Promo code label not used

### ISSUE THREAD

**Issue by valibus** [magento/magento2#6244]
When setting a promo code label, it is not displayed in cart but the promocode is used instead
### Preconditions
1. version : magento 2.1 public release
2. Setting a promo code with a name : promocodename
3. seeting a code for this promo with a code : truc
4. Setting a default label : labeltest
   ![image](https://cloud.githubusercontent.com/assets/6961470/17805905/0b966f30-6602-11e6-92a1-513c56aeca86.png)
   ![image](https://cloud.githubusercontent.com/assets/6961470/17805913/15b52b96-6602-11e6-8fc8-fc182157c5ed.png)
   ![image](https://cloud.githubusercontent.com/assets/6961470/17805999/6d7246de-6602-11e6-9835-27ffeb44732d.png)
### Steps to reproduce
1. add the promo code to cart, and watch the result
### Expected result

1. in the session message confirmation in green the right label should be displayed
2. in the cart resumee the right label should be displayed
### Actual result

1. in the session message confirmation in green the promo.code appear
2. in the cart resumee the promo.code appear

![image](https://cloud.githubusercontent.com/assets/6961470/17806051/a5122794-6602-11e6-8719-583066825f4d.png)

**Comment by sevos1984** [comment]
Thanks for reporting, this is a known issue, internal tiket is MAGETWO-48435

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69533
