### ISSUE TITLE
bin/magento content:deploy only minifid css and js files

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#6245]
Hello,
we had run bin/magento content:deploy and get only minifid css and js files on pub folder. Could you please help?
I think it is a bug.

**Comment by bka** [comment]
Check your settings under Stores -> Configuration -> Advanced -> Developer -> Java Scripts / CSS Settings. If minification is enabled there, the task generated minified versions.

**Comment by klarlichter** [comment]
Hello, OK. But it would be more easy if we can do that by command line... if you set that option and design will be destroy you need first login into database...
thats not the best way we need to choose...:S

**Comment by veloraven** [comment]
@klarlichter thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
