### ISSUE TITLE
Request to upgrade jquery cookie JS lib

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#6247]
### Preconditions

Current version used by Magento is depreacted and not maintained anymore.
May we have the new version of it in the next Magento releases ?

Current version used by Magento:
https://github.com/magento/magento2/blob/develop/lib/web/jquery/jquery.cookie.js
in:
https://github.com/magento/magento2/blob/develop/lib/web/mage/cookies.js

Link to deprecated lib:
https://github.com/carhartl/jquery-cookie

Link to new lib:
https://github.com/js-cookie/js-cookie

Thank you

**Comment by veloraven** [comment]
@daniel-ifrim thank you for your feedback.
Internal ticket was created - MAGETWO-57309

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-to-upgrade-jquery-cookie-JS-lib/idi-p/46296).
