### ISSUE TITLE
 404 while saving Footer Miscellaneous HTML

### ISSUE THREAD

**Issue by imbhupendra41** [magento/magento2#6248]
I am trying save the Zopim script on in Miscellaneous HTML into content->design->configuration
I am geting 404 page while saving the script with <script>tag .

![footerscript](https://cloud.githubusercontent.com/assets/5947187/17812979/0806bdda-6647-11e6-9962-be1e270762db.png)
![footerscript](https://cloud.githubusercontent.com/assets/5947187/17813008/28769572-6647-11e6-857f-fda16c658c86.png)

**Comment by sevos1984** [comment]
Could you please share your script to test it? Thanks

**Comment by imbhupendra41** [comment]
Hello Sevos1984

I am using Magento 2.1 and you can try with any code with script tag. Like i also tried to add following code.

<script>
alert("Hello World");
</script>

It is not working with script tag while i am able to save any text inside that field. For temporary solution i have directly added to database and now it is working.

**Comment by veloraven** [comment]
@imbrj please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by imbhupendra41** [comment]
Preconditions
1. Magento CE 2.1.0 with sample data is installed.
2. We are on Nexcess - Apache(Web server)
2. We are trying add the zopim script in general website.

Steps to reproduce
1. Login to Magento2 admin
2. Go to Content->Design->Configuration
3. Then edit any of options from that grid.
4. Once you edit that any option go to Footer section.
5. Then open that section and add following code to  Miscellaneous HTML

```
 <!--Start of Zopim Live Chat Script-->
    <script type="text/javascript">
    alert("Hello World");
    </script>
    <!--End of Zopim Live Chat Script-->
```

Actual and Expected result
    Expected result:
     You saved the configuration.
    Actual result:
     404 error: Page not found.

**Comment by AVoskoboinikov** [comment]
Hi, @imbrj
Unfortunately I am not able to reproduce your issue. Could you check it on clean CE 2.1.0 version with no sample-data and no 3rd party extensions?

I will appreciate for your effort

**Comment by imbhupendra41** [comment]
@andimov  I will check and let you know about once after disabling the modules and sample-data

**Comment by bash522** [comment]
Hi there,

I am getting the same problem any solution will be helpful!
thanks

**Comment by orlangur** [comment]
@bash522 as you can see here issue was not reproducible. Please provide exact steps if you can reproduce it on clean Magento 2 installation.

**Comment by bash522** [comment]
Hello @orlangur 

Please the attachments

![testimage1](https://user-images.githubusercontent.com/30899420/29181324-aac75110-7df2-11e7-9322-f1834efb9023.PNG)
![testimage2](https://user-images.githubusercontent.com/30899420/29181337-aed7f5ca-7df2-11e7-8ead-058e5d519c59.PNG)

**Comment by hturner100** [comment]
We are having the same issue on a completely fresh install of Magento 2.2 // no products, no extensions etc.

Adding the following GA tag into the Scripts & Stylesheets section under Content > Design: Configuration > HTML Head

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111037374-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'UA-111037374-1');
</script>
```

**Comment by ManishKumar1998** [comment]
This seems server issue. I have read it somewhere that by Disabling Mod_Security module in apache configuration we may be able to solve this error.

**Comment by VasylShvorak** [comment]
Hi @imbhupendra41 thank you for your report, i'm not able to reproduce issue by steps you described on clean 2.3-develop.
[Case 1:](https://github.com/magento/magento2/issues/6248#issuecomment-351442607)
![#6248_1](https://user-images.githubusercontent.com/26908019/58880647-12a3d080-86e1-11e9-9e8c-ea0b7ebc2cb7.png)
[Case 2:](https://github.com/magento/magento2/issues/6248#issuecomment-241360112)
![#6248_2](https://user-images.githubusercontent.com/26908019/58880679-2818fa80-86e1-11e9-82cd-41d448d5da3c.png)

**Comment by vipin12117** [comment]
This issue was never solved. I am using latest 2.1.18. Same issue coming.
