### ISSUE TITLE
404 NGINX not found error in "action" column within content > configuration

### ISSUE THREAD

**Issue by SanityLost** [magento/magento2#6251]
Moved site to production server.  After move, when going to content> configuration, everything displays except the action column. It just dipslays 404 not found error within the column.  

Using;
Nginx
php7.0.8
SSL (full site)

![untitled picture](https://cloud.githubusercontent.com/assets/11261705/17820378/8c3d7440-661a-11e6-873d-22a9ea3a702e.png)

**Comment by veloraven** [comment]
@SanityLost thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
Be sure that all required setup steps were performed (cache, folder permissions, etc).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
