### ISSUE TITLE
Multi Select & Dropdown Attribute unable to Save Bug. Magento 2.1 & 2.2Dev

### ISSUE THREAD

**Issue by acidreian666** [magento/magento2#6253]
### Preconditions

1. Magento 2.1 & Magento 2.2Dev
2. Ubuntu 16.04 Nginx1.10 PHP7.08 Mysql5.7
### Steps to reproduce

1. Fresh Install Magento 2.1 or 2.2Dev
2. Create A new Attribute Multi-Select or DropDown
3. Add 10-20 Attributes in the list
4. Select "Manage Labels" and Add Label ex. "Styles"
5. Select "Storefront Properties" Set everything To Yes so it is displayed and filterable and comparable ect..
6. Click save & reindex/Clear cache
7. Re-edit the new Attribute we just added and Delete one of the Attributes from the list in my example I deleted any of them between 1-15 but not the first or last ones.
8. Click Save & reindex/Clear cache
### Expected result

1. Multi-Select /Dropdown Attribute with an Attribute you picked Deleted.
### Actual result

1. Multi-Select /Dropdown Attribute with an Attribute you picked Deleted. But now "Manage Labels" is Blank & "Storefront Properties" wont allow you to change any of the options back to Yes that we set before like filterable or compare on front end ect.. If you change them back and add the Label back to the attribute and Click Save it Says it Saved. But after reopening the New Attribute you can see it was not updated.

**Comment by victor-v-rad** [comment]
Hi, 
I tried to delete an option from multiselect attribute as you wrote but cannot reproduce the issue. Maybe there is some step or precondition you did not mention.

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by nkajic** [comment]
Seems like duplicate of #6281 #7687 #4545
and that this is fixed by
https://github.com/nagno/magento2/commit/b380502570b92449326ab6ed50e6ce0359287240

**Comment by woakley** [comment]
Any update on this?

Possibly the fix works for multi select but not for dropdown.

**Comment by A-1A** [comment]
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this **Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Also Please check this
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444
