### ISSUE TITLE
REST user set to English gets non-English responses

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#6255]
I have a Dutch website. My REST user's language is set to English, but the responses of the REST interface are in Dutch :( 

If I set a users language to x I would also expect the response to be in that language.

Tested on 2.1.0 and 2.2.0-dev
### Steps to reproduce
1.  Install a language pack
2. Set admin user to use that language
3. Deploy everything
4. Create user with password for REST set language to english
5. f.e. check non-existing product via REST wether it exists,
### Expected result
1. English language result
### Actual result
1. Non-English result

**Comment by sevos1984** [comment]
This is language pack issue. Mentioned phrase is not translated in it. You can add translate to your translation file in i18n folder of respective module.

**Comment by thomvanderboon** [comment]
@sevos1984 No.... it is not!

I have a PHP script which query's my erp system for the products and for each product checks on the magento shop via rest wether it exists. If the product does not exist then it is added via REST

The PHP script is on a local server in my company. Magento is hosted externaly.

while($row = $result->fetch_assoc()) {
    // get the sku from the erp system
    $sku = $row["sku"];
    //Use above token into header
    $headers = array("Authorization: Bearer $token");
    $requestUrl="http://shop.domain.tld/index.php/rest/V1/products/".$sku;
    $ch = curl_init();
    $ch = curl_init($requestUrl);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $curl_result = curl_exec($ch);
    curl_close($ch);
    $curl_result=  json_decode($curl_result);
    //print_r($curl_result);

```
if (property_exists($curl_result, 'message')) {
  $return_message = $curl_result->message;
  if  ($return_message == "Gevraagde product bestaat niet") {
    echo "Produkt ".$sku." niet in database\n\n";
    *snip code to add product via rest*
 }
```

So if I get the dutch text back from the magento server "Gevraagde product bestaat niet" then I know the product does not exist. But the restuser is set to the english locale so I would expect English answers

For our information I am using a translation file the magento Crowdin translation project:

A little more steps to reproduce:
1. Clean install of mage 2.2.0-dev
2. build everything that needs to be build, configure every thing that needs to be configured
3. suppose Magento is installed in /var/www/magento2
4. cd /var/www/magento2/var
5. /bin/rm source_nl_NL.csv
6. wget http://107.170.242.99/var/Head/source_nl_NL.csv
7. cd /var/www/magento2
8. find . -name js-translation.json -exec rm -rf {} \;
9. php bin/magento i18n:pack --mode=replace -d var/source_nl_NL.csv nl_NL
10. php bin/magento setup:static-content:deploy en_US nl_NL
11. php bin/magento indexer:reindex
12. php bin/magento cache:clean
13. php bin/magento cache:flush
14. chown -R apache. /var/www/magento2
15. find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento
16. Set the language of the admin user to Dutch
17. php bin/magento indexer:reindex
18. php bin/magento cache:clean
19. php bin/magento cache:flush
20. create rest user with same role as admin; set locale to english for this user
21. Check wether the product exists... if not Dutch answer back on rest interface

PS: The Magento Crowdin Translation project has these strings translated in Dutch

**Comment by sevos1984** [comment]
Thanks for clarification. I've repeated your steps and got the issue. Api uses locale setting from Configuration->General->Locale Options. User language is only for admin panel language. This is desired behavior. If you want to use EN you have to add english storeview and use it you request (e.g. rest/en/V1/products/$sku)

**Comment by sevos1984** [comment]
Closing ticket since this is designed behavior.
