### ISSUE TITLE
Magento 2 Authorize.net Direct Post, after order place page is not redirecting to success page. 

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#6258]
Hi

I am using Magento 2.0.8 and onestepcheckout. When I am going to checkout the product and fill the checkout information and click on Place order button, Order has been placed but its not redirecting the success page instead of its stay on the checkout page.
http://prntscr.com/c82arm

transparent.js:102 Uncaught TypeError: Cannot read property 'success' of null
http://prntscr.com/c84s94

**Comment by poojalimagento** [comment]
I am also facing same issue on my local server in test mode on Magento 2.0.8.
Please help me. 
Thanks

**Comment by bharathi341** [comment]
I am also getting same issue in development server on production mode. Please help me to solve this issue.

Thanks,
Bharathiraja

**Comment by Walters-Kuo** [comment]
I am also getting same issue, but i did some thing and it working.
1. change payment --> authorize.net --> Test Mode to "No"
2. sandbox.authorize.net turn to live. (Your Account is Live and ready to process real transactions.)
3. change website HTTP to HTTPS.

for you reference.

**Comment by poojalimagento** [comment]
![authorize_admin](https://cloud.githubusercontent.com/assets/21255583/18339552/cfa71968-75bd-11e6-82ce-863ab469b790.png)
![authorize](https://cloud.githubusercontent.com/assets/21255583/18339554/d099d23e-75bd-11e6-9992-fd263345a083.png)

I have did same setting as you mention but still it giving error **'(13) The merchant login ID or password is invalid or the account is inactive.' .**
please help  me to solve this error.

**Comment by Walters-Kuo** [comment]
![authorize-net](https://cloud.githubusercontent.com/assets/3149367/18339964/fcd63b96-75d4-11e6-9948-ce7c95dd0696.png)

try this

**Comment by poojalimagento** [comment]
Thanks a lot **Walters-Kuo.**
It working.
But my transaction status is 'Captured/Pending Settlement' when its will complete ? for this transaction i have used the test details of card because of this is in pending ?

**Comment by poojalimagento** [comment]
My issue solved. Now all transactions also settled . 
Very Thanks for the help.

**Comment by iivashchenko** [comment]
Hi @jigar48, thanks for your report. Let us know if your issue still requires our assistance.

**Comment by bharathi341** [comment]
Hi All,
Unable to add associated products for configurable product. I can add by using super admin.
I have created a admin user and allowed catalog and other things but that user unable to access "catalog/product/associated_grid/componentJson" this url, when i try to create associated products that time magento 2 throws "Access Denied" error. Please help me to solve this issue.

Thanks,
Bharathiraja

**Comment by dmcmillin** [comment]
has this issue issue been resolved in 2.1.1? I had a customer tell me it did the same thing today for them. 1st day of launch.

**Comment by bharathi341** [comment]
Hi,

I resolved this issue. I just rewrite Magento\ConfigurableProduct\Controller\Adminhtml\Product\Associated\Grid file and added below function
 protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Magento_Catalog::products');
    }

Now its working fine.

**Comment by iivashchenko** [comment]
@dmcmillin, if you want to report a bug, please, create a new issue.

**Comment by iivashchenko** [comment]
@jigar48, we are closing this issue because it hasn’t been updated in more than two weeks. Please reopen as needed.

**Comment by kartikasodariya17** [comment]
Hello,

I also facing above issue with authorized.net payment process. I am checking with staging site but order successfully place and after place order getting error " An error occurred on the server. Please try to place the order again ". but not getting where i miss something. I have transaction key, api ID and MD5 hash key.
Also set test mode yes and used gateway URL " https://secure.authorize.net/gateway/transact.dll ". Also using http url .

So can you please help to resolve this issue.

**Comment by Jeevachezhiyan** [comment]
Hello,
       I am using magento 2.1.0 the below issue is coming i configured correctly it's working fine in magento 1.9 but in magento2 it's not working.Please check the error below and give solution to resolve this issue.


<html>
    <head>
        <script>
                    window.location="http://xxxx/authorizenet/directpost_payment/redirect/x_invoice_num/000000077/success/0/error_msg/Please enter a transaction ID to authorize this payment./controller_action_name/directpost_payment/";
                </script>
    </head>
    <body></body>
</html>

**Comment by iivashchenko** [comment]
@Jeevachezhiyan, it looks like your Authorize.net Direct Post payment is misconfigured. Please, open a new ticket for that issue and provide us your Authorize.net configuration, debug log and response from authorize.net/gateway/transact.dll, if possible.
