### ISSUE TITLE
Configurable product option is deleted from order view when invoice or shipment is generated - Magento 2.0.9 CE

### ISSUE THREAD

**Issue by Snowball678** [magento/magento2#6263]
When an invoice or shipment is manually generated for an order, the product option(s) of a configurable product in that order disappears form the order/invoice/shipment view both in frontend and admin end. And also on pdf views.

Steps to reproduce
1. Install magento community edition 2.0.9 without sample data
2. Create a configurable product
2. Place an order from frontend
3. Generate invoice for the order

Expected result
1. Configurable product option(s) should be visible

Actual result
1. Configurable product option(s) is not visible

![magento209bug1_02](https://cloud.githubusercontent.com/assets/21159677/17839125/d2184c66-67d6-11e6-85c1-40955a7d624c.jpg)
![magento209bug2_02](https://cloud.githubusercontent.com/assets/21159677/17839126/d93daf04-67d6-11e6-905c-6cbdcce0f804.jpg)
![magento209bug3_02](https://cloud.githubusercontent.com/assets/21159677/17839127/dda86b10-67d6-11e6-93b8-06220c891049.jpg)
![magento209bug4_02](https://cloud.githubusercontent.com/assets/21159677/17839128/e157945c-67d6-11e6-92e7-d7f5292001ce.jpg)

**Comment by veloraven** [comment]
@Snowball678 thank you for your report.
This issue is duplicate for #5686 and we already have internal ticket MAGETWO-56694 for it.

**Comment by magento-engcom-team** [comment]
@Snowball678, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
