### ISSUE TITLE
Error in Admin > products when module Reviews is disabled

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#6264]
After disabeling module Reviews, when editing a product an error is displayed 
### Preconditions
1. Tested and confirmed on 2.1.0 and 2.2.0-dev
### Steps to reproduce
1. Go to Admin panel 
2. Go to Stores > Configuration > Advanced > Advanced
3. Disable module Reviews
4. Go to Products > Products
5. Try to edit a (any) product
### Expected result
1. Hide reviews tab and no errors
### Actual result
1. Error "Something went wrong"
2. Reviews tab shows "wait circle"

**Comment by hostep** [comment]
This was already reported multiple times. Duplicate ticket: https://github.com/magento/magento2/issues/5323
You can find a linked PR in that ticket which should fix it (not tested myself).
