### ISSUE TITLE
Mini Cart return no items

### ISSUE THREAD

**Issue by sstar297** [magento/magento2#6265]
I have a bug with magento 2.1 but i think it is from base. when i add to cart from product detail: ajax is loaded and everything is good, mini cart show 1 item but the bug appear when i add to cart from homepage or extension have button not ajax. minicart does not update and return "No items"

Now, miniCart have a trigger call function load minicart after add to cart by ajax so if i code a button add to cart not run ajax but product is added, no wrong. the trigger is not called so minicart return wrong.

Can you help me to fix it?

**Comment by veloraven** [comment]
@Sonnh290791 thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by soragan** [comment]
1. Magento CE 2.1.0 without sample data installed, Multiple Website/Store on single Magento Instance.
2. Installation on a subfolder
3. Running 2.4.6 CentOS 7, MySQL 5.5.5-10.1.14-MariaDB Centos 7, PHP 5.6.24
4. Tested on multiple fresh installation, problem persist

To reproduce problem:
1. Click on Category in navigation
2. Click on any product to go into product details.
3. Click on "Add to Cart" button
4. The message "You added XXXXX to your shopping cart." appears on top in green colour
5. Top right hand Cart icon shows shopping cart is empty.

There is no problem for clicking on "Add to Cart" button in product list. In fact, after above step, when we click the button in product list, the Shopping Cart will shows all products added previously.

**Comment by slopukhov** [comment]
@soragan thank you for your feedback.

I can't reproduce this issue.
I have fresh installation with one product and one category.
I use these steps:
1. Click on Category in navigation
2. Click on any product to go into product details.
3. Click on "Add to Cart" button
4. The message "You added XXXXX to your shopping cart." appears on top in green colour
5. Top right hand Cart icon shows shopping cart with this product (these data are loaded after a short delay).

Can you check this issue on 2.1.last version?
What browser do you use?

**Comment by soragan** [comment]
i am on 2.1.0 downloaded from magento.com, does this make any different? tried both safari and chrome on macbook.

i have 13 categories (only 4 are filled), 43 products, 3 websites with each 1 store, 1 store view.

additionally, whenever i browse to other pages, the green message persisted from page to page.

**Comment by slopukhov** [comment]
Hi @soragan 

Thank you for reporting the issue. It is reported as `MAGETWO-57430` internally.

**Comment by soragan** [comment]
thanks for the bug confirmation, hopefully this is fixed soon as it's the only thing stopping us from pushing 2.1.0 to replace 1.9

**Comment by developer-lindner** [comment]
Update to 2.1.1. and report back or close ticket otherwise.

**Comment by soragan** [comment]
problem still exist in 2.1.1

perform update from 2.1.0 using compose update and recompile magento. tested on both safari and chrome, on os x 10.11.6

**Comment by deepthit57** [comment]
I face the same issue. I also have the latest version 2.1.1 and did a fresh installation.

**Comment by soragan** [comment]
multiple website installation with different URLs?

**Comment by soragan** [comment]
problem still exist in latest 2.1.2, minicart is not updated after adding product using the button in product details page.

**Comment by rishabhrkrai** [comment]
I face the same issue. If i added the product from product page, mini cart shows no item in cart but if i added product from category page mini cart shown product with previously added product items.
 I use Magento 2.1.1.
Is there any fix for that??

**Comment by PieterCappelle** [comment]
Bug still exists in 2.1.2.

**Comment by TwassistantKeith** [comment]
I have this problem as well. Magento 2.1.2.

**Comment by anisagrebi** [comment]
i have the same issu Magento ver. 2.1.2
the mini cart doesnt refresh 
please is there any fix for this???

**Comment by lietzmk** [comment]
You can disable the mini cart completely until this is fixed.

Stores > Configuration > Sales > Checkout > Shopping Cart Sidebar and change "Display Shopping Cart Sidebar" to No

**Comment by steverobbins** [comment]
Still seeing this issue in 2.1.3.  It seems to be that the `mage-cache-storage` local storage isn't getting set correctly.

"After Adding a Product Redirect to Shopping Cart" set to "No", using Safari on Mac.

**Comment by josefbehr** [comment]
Still experiencing this in 2.1.5

**Comment by scommercemage** [comment]
Any idea when this is going to be fixed?

**Comment by FloWord** [comment]
I have the same issu in magento version 2.1.2, the mini cart doesnt refresh correctly. Have anybody a fix or workaround for that problem?

**Comment by mohsinahmed22** [comment]
Facing this issue any fix on this? Anyone?

**Comment by FloWord** [comment]
My Solution for refresh Problem:
https://github.com/magento/magento2/issues/5377

You simply need to change
"bindSubmit": false
to
"bindSubmit": true

**Comment by rafaelstz** [comment]
This issue is fixed to me when I upgrade my PHP version from 7.0.9 to 7.0.15.

**Comment by magento-engcom-team** [comment]
@Sonnh290791, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by ghost** [comment]
Same problem in magento 2.2.2
Fixed in 2.2x is not true.

If i add a product from the homepage or a category it is the same.
Also this green bar.

@FloWord 

> You simply need to change
> "bindSubmit": false
> to
> "bindSubmit": true_**_**

Is not working because this code is not in the file of magento 2.2.2 version.
Is there a workaround or solution for this?
![minicart issues](https://user-images.githubusercontent.com/15247780/36251417-6ecb8b3e-1241-11e8-9815-d946535b3fd5.png)
