### ISSUE TITLE
DevDoc description has an attribute not necessary in POST endpoints

### ISSUE THREAD

**Issue by girish-happiestminds** [magento/magento2#6269]
In POST calls there are some endpoints which have id as an attribute in the 'request'

for example

{
  "taxClass": {
    "class_id": 0,
    "class_name": "string",
    "class_type": "string",
    "extension_attributes": {}
  }
}

In the above example, class_id should not be part of the 'request' (json/xml) as it is autogenerated during insertion. If we send a request with class_id, we get an error response with status code 404 saying "Request does not match any route" (which implies the request is trying to update an existing class_id).

So, in order to create a new taxClass we should not provide class_id as a parameter as it will be generated automatically.

Below are the list of APIs/Endpoints which have this issue with DevDoc,

catalogAttributeSetManagementV1
post /V1/products/attribute-sets --> Create attribute set from data

catalogCategoryRepositoryV1
post /V1/categories --> Create category service

catalogProductAttributeGroupRepositoryV1 
post /V1/products/attribute-sets/groups --> Save attribute group

catalogProductAttributeMediaGalleryManagementV1 
post /V1/products/{sku}/media --> Create new gallery entry

catalogProductRepositoryV1 
post /V1/products --> Create product

cmsBlockRepositoryV1 
post /V1/cmsBlock --> Save block.

cmsPageRepositoryV1 
post /V1/cmsPage --> CMS page CRUD interface.

configurableProductOptionRepositoryV1 
post /V1/configurable-products/{sku}/options --> Save option

customerAccountManagementV1 
post /V1/customers --> Create customer account. Perform necessary business operations like sending email.

customerGroupRepositoryV1 
post /V1/customerGroups --> Save customer group.

downloadableLinkRepositoryV1 
post /V1/products/{sku}/downloadable-links --> Update downloadable link of the given product (link type and its resources cannot be changed)

eavAttributeSetManagementV1 
post /V1/eav/attribute-sets --> Create attribute set from data

giftMessageCartRepositoryV1 
post /V1/carts/{cartId}/gift-message --> Set the gift message for an entire order.
post /V1/carts/mine/gift-message --> Set the gift message for an entire order.

giftMessageGuestCartRepositoryV1 
post /V1/guest-carts/{cartId}/gift-message --> Set the gift message for an entire order.

giftMessageGuestItemRepositoryV1 
post /V1/guest-carts/{cartId}/gift-message/{itemId} --> Set the gift message for a specified item in a specified shopping cart.

giftMessageItemRepositoryV1 
post /V1/carts/{cartId}/gift-message/{itemId} --> Set the gift message for a specified item in a specified shopping cart.
post /V1/carts/mine/gift-message/{itemId} --> Set the gift message for a specified item in a specified shopping cart.

salesRuleCouponManagementV1 
post /V1/coupons/generate --> Coupon management interface

salesRuleCouponRepositoryV1 
post /V1/coupons --> Coupon CRUD interface

salesRuleRuleRepositoryV1 
post /V1/salesRules --> Save sales rule.

taxTaxClassRepositoryV1 
post /V1/taxClasses --> Create a Tax Class

taxTaxRateRepositoryV1 
post /V1/taxRates --> Tax rate CRUD interface.

taxTaxRuleRepositoryV1 
post /V1/taxRules --> Save TaxRule

**Comment by ghost** [comment]
@keharper Are you aware of this?

**Comment by keharper** [comment]
In the abstract, yes. I've encountered some of them in my tests, and it's known that the way the Magento code is structured that any autogenerated doc system will give misleading results. But now that I know how persistent this particular problem is, I can act on it.

I'll post this information on devdocs and open a Jira ticket in hopes that this can be corrected.

**Comment by magento-engcom-team** [comment]
This issue reopened into the section "devdocs"
[https://github.com/magento/devdocs/issues/1484](url)
