### ISSUE TITLE
Default Store View value of Text Swatch attribute is too short.

### ISSUE THREAD

**Issue by sumihiro** [magento/magento2#6270]
I want to use Text Swatch Attribute with long text.
But Default Store View value cannot be saved correctly. It will be shrink.
### Preconditions

I'm using Magento2.1.0, and MySQL 5.6.30.
### Steps to reproduce
1. Create new Attribute, and select Text Swatch.
2. Set long text to Default Store View in Manage Swatch.
   Like: "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
   "
3. Save Attribute.
### Expected result
1. Default Store View value is saved full length.
### Actual result
1. Value is shrink.
   Like: "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234"

May be, it is caused by limitation of max varchar length (255) of MySQL.

```
mysql> desc eav_attribute_option_value;
+-----------+----------------------+------+-----+---------+----------------+
| Field     | Type                 | Null | Key | Default | Extra          |
+-----------+----------------------+------+-----+---------+----------------+
| value_id  | int(10) unsigned     | NO   | PRI | NULL    | auto_increment |
| option_id | int(10) unsigned     | NO   | MUL | 0       |                |
| store_id  | smallint(5) unsigned | NO   | MUL | 0       |                |
| value     | varchar(255)         | YES  |     | NULL    |                |
+-----------+----------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

How to save value correctly?

**Comment by sumihiro** [comment]
Also, I want to use Default Store View as Text Area not Text Field.

**Comment by sumihiro** [comment]
To work around, I changed table scheme:

```
mysql> alter table eav_attribute_option_value change value value text;
```

It seems working good, but  I don't know what happen when Magento is updated.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Default-Store-View-value-of-Text-Swatch-attribute-is-too-short/idi-p/44964).
