### ISSUE TITLE
Custom multiselect attribute in custom attribute set saving problem

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#6274]
### Preconditions

1. I use Magento 2.1, PHP 7.0. 
### Steps to reproduce

1. On clean Magento install I have created new attribute set, basing on frame of default one. 
2. Then I create custom multiselect attribute with some options and add it only to my custom attribute set.
3. When I create new product and mark some options of mentioned attribute product saves but not the attribute. In that moment, after failure of saving product I run from terminal `bin/magento cache:clean` I can save product with proper option of attribute. Doing it, I have no further problem with saving any value for multiselect for any product.
4. But - while adding attribute to set, I add it to `Default` attribute set as well all works fine. 
5. All follownik steps are done from adminhtml. Programatically it doesn't work as well.
### Expected result

1. Of course, it should save during first attempt.
### Actual result

1. It does not save.

**Comment by veloraven** [comment]
@bartek9007 thank you for the report.
We already have internal ticket MAGETWO-56778 for this issue.

**Comment by magento-engcom-team** [comment]
@bartek9007, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
