### ISSUE TITLE
Transactional Email Logo Not Getting Updated

### ISSUE THREAD

**Issue by k3designs** [magento/magento2#6275]
### Preconditions

1. Magento ver. 2.1.0
2. PHP 7.0
### Steps to reproduce

1. Go to content > Design > Configuration
2. Select Scope:website (Edit) (for multisite setup)
3. Go to Transactional Email setup
4. Try to upload custom logo for email.
### Expected result

1. The new logo should be uploaded 
### Actual result

1. [Screenshot, logs]
   <img width="979" alt="screen shot 2016-08-22 at 7 40 36 pm" src="https://cloud.githubusercontent.com/assets/21137142/17857684/5adc10d6-68a0-11e6-943c-0bd5b32b29e2.png">
2. I have checked on a server side, the folder "email" is not getting generated on the server, under pub > media >

While all other folders are getting generated like "sales", "favicon" etc.

**Comment by kevincream** [comment]
I can confirm this, i have the same issue in 2.1

**Comment by hostep** [comment]
This has been reported multiple times already, please try searching for an issue before creating a new one.
Duplicate: https://github.com/magento/magento2/issues/5352
A fix was already delivered to the develop branch, we just need to wait (very very patiently) until Magento puts this into an official release.

**Comment by sevos1984** [comment]
Thanks for reporting, this issue is fixed in develop branch and will be patched in 2.1 in nearest release (internal ticket MAGETWO-57291)

**Comment by JuliaGosling** [comment]
Is there a work around ahead of the patch being released?

**Comment by JuliaGosling** [comment]
(actually, I just created a header template and referenced my image location absolutely)
Be good to know when the patch is released though. :)

**Comment by peec** [comment]
Can confirm this still, in 2.1.1. Using regular file storage system.

**Comment by jvreeken** [comment]
was not delivered in 2.1.2 ?  I just read the release notes for 2.1.2 and this is still a "Known issue"
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.2CE.html#known-issues

**Comment by Ctucker9233** [comment]
@jvreeken It's disappointing. If anyone on the Magento team is reading this, please take some time to fix all know issues/bugs before releasing 2.1.3 or 2.2. It's just common sense to do so.

**Comment by ihor-sviziev** [comment]
Unfortunately I have this issue too.
In develop branch we already have fix for this issue: https://github.com/magento/magento2/commit/23103c03c527fe1ed3e1a3be691436818b7963fe

Waiting for release that will include it...

**Comment by bardkalbakk** [comment]
It supprising to find that this bug is still pending. Has anyone backported this to 2.1 [23103c0](https://github.com/magento/magento2/commit/23103c03c527fe1ed3e1a3be691436818b7963fe) ?

The commit looks quite simple and isolated.

**Comment by salelsol** [comment]
I´m reciving orders with wrong email logo, if recive from default scope store logo it´s O.K. , but when I recive orders from any other scope language store then logo recived is Luma Logo, I´m configured backend Content/Design/Configuration/Transactional Email/Logo Image, also add language to pub/media/logo/stores/1 /2 and /3 but nothing working.

**Comment by MattDelac** [comment]
Still an issue on Magento 2.1.5
Thank you

**Comment by pguedesbr** [comment]
this has been fixed in 2016, and promised to be released in 2.1
We are in 2.1.5, the fix is ready in develop branch for months. 
Why in the name of God has this not been merged into the MANY latest releases yet?

**Comment by itsgauravjain22** [comment]
This issue should be merged with master branch as its a very high priority issue. Mails are supposed to have  Company logo. Using magento 2.1.5.

**Comment by okorshenko** [comment]
Pull Request https://github.com/magento/magento2/pull/9590 has been merged to 2.1-develop branch. Thank you @hostep for your contribution!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062

**Comment by impunkj** [comment]
I am getting same issues in magento 2.1.7. what should i do for fix.

**Comment by hostep** [comment]
@impunkj: this was fixed in Magento 2.1.8, feel free to upgrade to the latest version (2.1.9 at the moment) and to try it again :)
