### ISSUE TITLE
Customer cannot reorder if the order has been invoiced or shipped

### ISSUE THREAD

**Issue by Snowball678** [magento/magento2#6278]
Customer can only reorder a previous order if the order has not been processed (shipped or invoiced). If the order has been processed, customer gets an error when the reorder button is clicked.
Error: We can't add this item to your shopping cart right now.

Reordering from backend works for orders with simple products only but does not work if the order contains configurable products

Related to #4953 
Possibly related to #6263
### Preconditions

1. Magento 2.0.9 CE
### Steps to reproduce

1. Place an order from magento frontend
2. Invoice or ship the order from backend
3. Reorder the order from frontend
### Expected result

1. Items in the order should be added to cart
### Actual result

1. Items not added to cart. An error message is displayed in cart

**Comment by veloraven** [comment]
@Snowball678 thank you for your report, we created internal ticket MAGETWO-57681.

**Comment by SerhiyShkolyarenko** [comment]
The fix is merge to 2.0.x branch. Will be available on the next release.

**Comment by veloraven** [comment]
This issue has been fixed already in ver. 2.0.11.
Closed.
