### ISSUE TITLE
Feature Request: Parent entities links in child entities grid.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#628]
I think it would be a nice improvement for the user experience if in the backend grids of child entities, where there is a parent identification column, this column to be a link to the parent entity edit page.  
Here are some examples.  
In the shipments grid, the order increment id should be a link to the order edit page. (Same goes for invoice and creditnotes grids).  
In the product grid, the attribute set should be a link to the attribute set edit page.  

This can be taken even further, for sibling entities.  
For example in the category add/edit page, in the 'Associated products' table, the product name can have a link to the product edit page (maybe target="_blank").  
This way the user has all the information one click away.

I admit the idea isn't mine. Someone requested this for one of my extensions for 1.x, but I think this should be a nice out of the box feature.  
There is already a column rendered for links (edit link for example). It just needs a dynamic label depending on the row.

**Comment by Tiurnikova** [comment]
Hello @tzyganu I just wanted to share an update with you.
Unfortunately, you won't see this feature in the upcoming release. However, we already did a lot of improvements in data grids and plan to do more. Here is the number of the ticket for this feature in our internal backlog MAGETWO-41374
You can be sure, we're working on it.

**Comment by amansrivastava** [comment]
Any updates for this ticket ?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Parent-entities-links-in-child-entities-grid/idi-p/47037).
