### ISSUE TITLE
Magento 2.1 Multi Select Attribute doesn't save empty values

### ISSUE THREAD

**Issue by Corefix** [magento/magento2#6281]
### Preconditions

1. Magento 2.1
2. Chrome 52.x
### Steps to reproduce

1. Go to Magento admin
2. Go to Products > Catalog
3. Select a product that have a multi select attribute
4. Find the multi select attribute and set one or more of the options on the product (so it looks like the following image).
   ![screen shot 2016-08-23 at 09 28 09](https://cloud.githubusercontent.com/assets/16081779/17883643/056aabb6-6914-11e6-9e54-1850896aae6d.png)
5. Save the product
6. Go back and edit the same product again.
7. Now deselect all options in the same multi select field
8. Save product again
### Expected result

1. The product should now have no options selected
### Actual result

1. Product have all options still selected.

It looks like the empty fields are not included in the post request, which they should, since removing values is just as important as setting them :-)

**Comment by sevos1984** [comment]
This is a known issue, internal ticket id MAGETWO-57226. Thanks for posting

**Comment by developer-lindner** [comment]
@Corefix Update to 2.1.1. and report back or close this ticket otherwise.

**Comment by nagno** [comment]
It still not works in 2.1.1. I will create a ticket on the partner portal as well. (hopefully it will get more priority)

**Comment by TClilMouse** [comment]
Still not works in 2.1.3

**Comment by nagno** [comment]
@seavenger this patch works for me: https://github.com/magento/magento2/pull/6899

**Comment by roseofgold** [comment]
patch didn't work for me on 2.1.2

**Comment by nagno** [comment]
@roseofgold 
are you sure you applied it correctly?
We are using it in a production system without any issues.

**Comment by roseofgold** [comment]
@nagno No I'm not sure. I just tried applying it again and now I can't use my admin :(

**Comment by nagno** [comment]
@roseofgold your issue is probably not related to this patch or you have an interfering customisation.
If you check the comments on the patch, @wigman created a 2.1.3 compatible version as well.

**Comment by roseofgold** [comment]
@nagno thought you might like to know (and for posterity) that it works for me in IE11 but not in Chrome (v55). It's probably some customization that causing problems as it works differently in different browsers.

**Comment by nagno** [comment]
@roseofgold It is not working for us in any browser (even in a Vanilla Magento environment). It is still not working in 2.1.5.

Progress so far: we got one not working patch from the support team and another one, which was breaking the attribute set change functionality (you wasn't able to select an attribute set for new products as well).

**Comment by roseofgold** [comment]
@nagno Updating to 2.1.6 broke it all browsers and all environments. I believe this issue should not be closed.

**Comment by nkajic** [comment]
Seems like duplicate of #6253  #7687 #4545
and that this is fixed by
https://github.com/nagno/magento2/commit/b380502570b92449326ab6ed50e6ce0359287240

**Comment by hoektoe** [comment]
Still experiencing this issue in 2.1.4

**Comment by magento-engcom-team** [comment]
@Corefix, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by nagno** [comment]
Of course you are not able to reproduce it, because it was fixed in 2.1.8. (See changelog for 2.1.8)
I did report it in October 2016 via the partner portal and after 2 not working patches Magento finally fixed it. It took about 9 months to provide it even with "priority" partner portal support...

**Comment by WilliamChongSDG** [comment]
This issue still persist in Magento ver. 2.2.2

**Comment by A-1A** [comment]
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this **Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Also Please check this
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444

**Comment by yohanespradono** [comment]
this happens in our v2.1.9 intermittently. When saving a product, some attributes has ->getAttributeSetInfo() returns null and some returns empty array. This causes \Magento\Eav\Model\Entity\Attribute\AbstractAttribute::isInSet($setId) to return different values regarding whether getAttributeSetInfo is null or an empty array.
I am proposing on of this patch

in function \Magento\Framework\DataObject::__call
replace
`
            case 'has':
                $key = $this->_underscore(substr($method, 3));
                return isset($this->_data[$key]);
`
with
`
            case 'has':
                $key = $this->_underscore(substr($method, 3));
                return isset($this->_data[$key]) and !empty($this->_data[$key]);
`

or

in function \Magento\Eav\Model\Entity\Attribute\Set::addSetInfo($entityType, array $attributes, $setId = null)
replace
`
                    if (!is_array($attributeSetInfo)) {
                        $attributeSetInfo = [];
                    }
`
with
`
                    if (!is_array($attributeSetInfo)) {
                        $attributeSetInfo = null;
                    }
`
