### ISSUE TITLE
Configurable Product create/update “No data to save” with too many options

### ISSUE THREAD

**Issue by rbncha** [magento/magento2#6282]
I have a strange issue with Magento 2.0.7 - 2.1.0 versions in my vps. When I try to create multiple options (more than 30 variations of color and sizes), it gives me "No data to save" error while trying to save the product. If I create a product with only around 10 child products for a configurable product, it does not give me any error. Attached are the error screenshot and my server's php.ini settings. This vps has 8gb of ram and enough ssd space. Please hint me something I am missing. I tried to increase several php configuration settings max_input_vars, opcache.max_accelerated_files etc. Nothing helped. It seems something related to session. But not sure what it is.
### Preconditions

1. Create/edit configurable product with more than 10 colors/sizes each gives "No data to save error".
### Steps to reproduce

1. Create or edit a configurable product.
2. Add 2 or more configurable options like (Color, Size) with more than 30 variations
3. Add single price and qty for all configurable child products
4. Save the product
### Expected result

1. Configurable product and all options saved successfully
### Actual result

1. Gives "No data to save" error message
   ![image](https://cloud.githubusercontent.com/assets/767121/17884469/2c7102fe-6938-11e6-8d2d-67dc1b92c276.png)

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-57094 and MAGETWO-57095, thanks for reporting

**Comment by rbncha** [comment]
@sevos1984 Do you have any patches to apply for ver 2.1 ?

**Comment by sevos1984** [comment]
Fix is delivered to develop branch https://github.com/magento/magento2/commit/b75fc4f83aa2fdf093ceae25449fa0b95bbc4020. And should be added to nearest patch release

**Comment by rbncha** [comment]
@sevos1984, Surprisingly, I get this error in 2.0.4 to 2.1.1. Is it something related to server settings ? I tried applying the patch didn't work. [https://github.com/magento/magento2/commit/b75fc4f83aa2fdf093ceae25449fa0b95bbc4020](url)

**Comment by sevos1984** [comment]
I don't have that on 2.1.1. Try allocating more memory to magento.

**Comment by Ctucker9233** [comment]
@sevos1984 Any word on when that patch will be ready?

**Comment by suraleb** [comment]
Is any changes? Have same issue for 2.1.2 after data migration from prestashop

**Comment by choukalos** [comment]
This is resolved in 2.1.3 and mainline, please upgrade to 2.1.3.

**Comment by andreaschiffo** [comment]
just encountered this, exactly the same issue in 2.1.3 after migration from a M1 installation with many configurable products and simple products related to them
