### ISSUE TITLE
Class Magento\Email\Model\Source\Variables hard coded

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#6284]
### Preconditions

Affects all Magento2 Versions.

The class `Magento\Email\Model\Source\Variables` cannot be changed or extended as we need to add an additional config path `general/store_information/merchant_vat_number`.
### Steps to reproduce

None
### Expected result

The class `Magento\Email\Model\Source\Variables` should be extensible.
### Actual result

We must hard the VAT number in all templates.

**Comment by fooman** [comment]
This 

```
class MyVariables extends Magento\Store\Model\Store\Variables

    public function __construct()
    {
        parent:: __construct();
        $this->_configVariables[] = ['value' => 'general/store_information/merchant_vat_number', 'label' => 'The Number'],

    }
```

and then setting a DI preference wouldn't work?

**Comment by antboiko** [comment]
Hi @SchumacherFM , did you try the suggestion provided by @fooman ?

**Comment by SchumacherFM** [comment]
Not yet due to lack of time, but on plan

**Comment by SchumacherFM** [comment]
Sorry for opening this issue. @fooman solutions works fine :-) Thank you Christoph!

**Comment by vseager** [comment]
For newer versions on Magento 2:

```
namespace Custom\Module\Model\Config\Structure;

class AvailableVariables extends \Magento\Variable\Model\Config\Structure\AvailableVariables
{
    public function __construct($configPaths = []) {

        $configPaths['social'] = [
            'social/handles/facebook' => '1',
            'social/handles/twitter' => '1',
            'social/handles/pinterest' => '1',
            'social/handles/youtube' => '1'
        ];
        parent:: __construct($configPaths);

    }
}

```
