### ISSUE TITLE
Unable to modify .htaccess in static directory

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#6285]
I have CORS requests issue with fonts when I using CDN. In order to fix it I'm changing my .htaccess. During deployment I do composer install. After that my changes were reverted.
### Preconditions
1. Magento 2.1.0 installed via composer
2. Base Static URL is CDN domain (CloudFront in my case)
### Steps to reproduce
1. Install Magento 2 via composer
2. Change your file pub/static/.htaccess (as example add `Header set Access-Control-Allow-Origin "*"`)
3. Remove vendor directory
4. Do composer install
### Expected result

My pub/static/.htaccess file should not be overridden.
### Actual result

My pub/static/.htaccess file is overridden and my changes were reverted.

Possible solutions:
- Do not add this file to map listing in composer.json of magento2-base package, move it to magento/product-community-edition package
- Add ability to override htaccess

**Comment by hostep** [comment]
I don't know if there is a good solution for this, but here are some related issues:
- https://github.com/magento/magento2/issues/4930
- https://github.com/magento/magento2/issues/6221

[This comment](https://github.com/magento/magento2/issues/6221#issuecomment-240760876) is a possible solution, but Magento will need to change some things before that can happen probably.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-modify-htaccess-in-static-directory/idi-p/45735).
