### ISSUE TITLE
Can't fully deploy using core CLI commands.

### ISSUE THREAD

**Issue by diabeeto076** [magento/magento2#6286]
So i've build a CI/CD process that worked perfectly on Magento 2.0 After upgrading to 2.1, stuff started to collapse.

I use Magento's CLI commands to create env.php dynamically, depending on the stage where it's deployed onto. Unfortunately this does not set the install date, and since Magento 2.1 this seems to be required before Magento includes any other code than it's own. This makes it hard to deploy Magento, because i don't want to install on every deployment. And i don't want any credentials in my VCS either.

Using a template is an option, but i'd rather not if i could deploy fully using the CLI tools that Magento provides.

So my question is, why the check on this date before any custom code is included? And is there a workaround to fully deploy Magento 2.1 (not to install!), using Magento's CLI commands?

**Comment by veloraven** [comment]
@JBleijenberg thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
