### ISSUE TITLE
newsletter_subsciber created date and source

### ISSUE THREAD

**Issue by bsstaveley** [magento/magento2#629]
Hi all,

Bit of a boring request but this issue exists in current Magento but I see this as a problem going forward also.

This newsletter_subscriber table doesnt store the created date for a subscriber or the source e.g. newsletter box or during checkout. With more and more laws coming into play with proving when a person subscribed and the reason why/how they subscribed this will become even more of a problem. A recent Canadian Law CASL which actually covers anyone emailing a recipient located within Canada (so could be anyone) the fine is hefty and proof is key (http://www.dotmailer.com/blog/what-marketers-need-to-know-about-casl-canadian-anti-spam-legislation/#.U-DdG_ldV8E).

So a created date column and source to specify on your site where they subscribed would solve this.

Ben

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28236

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/newsletter-subsciber-created-date-and-source/idi-p/47033).
