### ISSUE TITLE
Magento 2 Apply both promotion and promotion code for order 

### ISSUE THREAD

**Issue by JananiKrishnan** [magento/magento2#6294]
Hi,

I need to apply both promotion and coupon code for an order. It seems we can apply only one at a time. Kindly tell me whether a plugin is available or we can write a custom code?

I can explain you with scenario.

Let us say I have generated a promotion for 10 % off for order and also I have generated coupon code of $5 off for order(SAVE). 

***_Expected Result:**_\* Both 10% and $5 for order should apply if I apply promo code SAVE

***_Actual Result:**_*Either one is applying.

**Comment by tkacheva** [comment]
@JananiKrishnan Are you saying that none of promo applied to shopping cart? or only one?

**Comment by tkacheva** [comment]
Bug MAGETWO-55433

**Comment by JananiKrishnan** [comment]
Only one is applied.. i.e., either promo or promo code is applying

**Comment by tkacheva** [comment]
Thanks @JananiKrishnan  that is what we reproduced.

**Comment by loganathan-r** [comment]
@tkacheva When will the fix be available? or Can you provide a patch for the issue? we need to go live next week with fix

**Comment by tkacheva** [comment]
@loganathan-r we are working on it. Once it's merged, we close the ticket

**Comment by tkacheva** [comment]
@loganathan-r Bugfix is merged to mainline. Please update and check. Closing the ticket

**Comment by tkacheva** [comment]
Commit https://github.com/magento/magento2/commit/d66748032936d4f48c937343a9906fea8acdd132

**Comment by Ctucker9233** [comment]
@tkacheva is this commit safe to integrate into a 2.1.1 production environment or is there a patch pending. If I may also ask a question, I am wondering why all bug fixes get merged into develop instead of into the version the fix is for? I'm just trying to understand the process.

**Comment by tkacheva** [comment]
Hi @Ctucker9233 ,
This issue was back ported to 2.1 and will be available in 2.1.3 patch release once it's out.
