### ISSUE TITLE
Make quick create string connector configurable

### ISSUE THREAD

**Issue by seansan** [magento/magento2#630]
Situation:
When creating configurable product 
and then creating simple associated products (tab)
using quick create
a hash is added between the mother SKU + the identifying attribute (from simple product)

Thus:
config product ML7.08
with quick simple create in SIZE XL
becomes a simple product with SKU ML7.08-XL

http://www.magentocommerce.com/boards%20/viewthread/13793/

Request: make the "-" configurable, or also a field in quick create, because we use DOTS (and many others use others)

ps. I would also log for MAgento 1.x but there is no working bug tool

**Comment by tanya-soroka** [comment]
Thanks for this suggestion, @seansan ! We will consider this during improving Configurable product in the following releases (MAGETWO-4526).

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28237

**Comment by piotrekkaminski** [comment]
@tanya-soroka  can you check if it was done?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Make-quick-create-string-connector-configurable/idi-p/47028).
