### ISSUE TITLE
Is it possible to fetch quantity, is_in_stock value and extension attributes for each product in magento 2 rest api using searchCriteria. I am using the following url http://website_host/index.php/rest/V1/products/?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=keratin&searchCriteria[filter_groups][0][filters][1][field]=sku&searchCriteria[filter_groups][0][filters][1][value]=Inspiring

### ISSUE THREAD

**Issue by omkarambre** [magento/magento2#6301]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 

I am expecting  to get extension_attributes in json object. I am getting custom_attributes but not extension_attributes.

"extension_attributes": {
    "stock_item": {
      "item_id": 2048,
      "product_id": 2048,
      "stock_id": 1,
      "qty": 33,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": false,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": true,
      "low_stock_date": null,
      "is_decimal_divided": false,
      "stock_status_changed_auto": 0
    }
  }

in json object by hitting 

http://website_host/index.php/rest/V1/products/?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=keratin&searchCriteria[filter_groups][0][filters][1][field]=sku&searchCriteria[filter_groups][0][filters][1][value]=Inspiring

The above result i am getting by hitting the below url

http://website/index.php/rest/V1/products/keratin
### Actual result

1. [Screenshot, logs]

I am getting following result

{
  "items": [
    {
      "id": 2097,
      "sku": "Inspiring",
      "name": "Inspiring",
      "attribute_set_id": 4,
      "price": 1.89,
      "status": 1,
      "visibility": 4,
      "type_id": "simple",
      "created_at": "2016-05-09 11:50:26",
      "updated_at": "2016-07-08 13:14:05",
      "product_links": [],
      "options": [],
      "tier_prices": [],
      "custom_attributes": [
        {
          "attribute_code": "description",
          "value": "Inspiring Fragrances & Mild Cleansing"
        },
        {
          "attribute_code": "meta_title",
          "value": "Inspiring"
        },
        {
          "attribute_code": "meta_keyword",
          "value": "Inspiring"
        },
        {
          "attribute_code": "meta_description",
          "value": "Inspiring "
        },
        {
          "attribute_code": "image",
          "value": "/i/n/inspiring.png"
        },
        {
          "attribute_code": "small_image",
          "value": "/i/n/inspiring.png"
        },
        {
          "attribute_code": "thumbnail",
          "value": "/i/n/inspiring.png"
        },
        {
          "attribute_code": "options_container",
          "value": "container2"
        },
        {
          "attribute_code": "required_options",
          "value": "0"
        },
        {
          "attribute_code": "has_options",
          "value": "0"
        },
        {
          "attribute_code": "msrp_display_actual_price_type",
          "value": "0"
        },
        {
          "attribute_code": "url_key",
          "value": "inspiring"
        },
        {
          "attribute_code": "tax_class_id",
          "value": "2"
        },
        {
          "attribute_code": "swatch_image",
          "value": "/i/n/inspiring.png"
        }
      ]
    },
    {
      "id": 2048,
      "sku": "Keratin",
      "name": "Keratin",
      "attribute_set_id": 4,
      "price": 14.55,
      "status": 1,
      "visibility": 4,
      "type_id": "simple",
      "created_at": "2016-05-09 10:05:32",
      "updated_at": "2016-08-22 12:38:57",
      "product_links": [],
      "options": [],
      "tier_prices": [],
      "custom_attributes": [
        {
          "attribute_code": "description",
          "value": "<p>Syoss Keratin Hair Perfection, for improved hair quality with Keratin-Primer. For 100% Repair, Supplness and Shine.&nbsp;</p>"
        },
        {
          "attribute_code": "meta_title",
          "value": "Keratin"
        },
        {
          "attribute_code": "meta_keyword",
          "value": "Keratin"
        },
        {
          "attribute_code": "meta_description",
          "value": "Keratin "
        },
        {
          "attribute_code": "image",
          "value": "/k/e/keratinshampoo_500ml_.png"
        },
        {
          "attribute_code": "small_image",
          "value": "/k/e/keratinshampoo_500ml_.png"
        },
        {
          "attribute_code": "thumbnail",
          "value": "/k/e/keratinshampoo_500ml_.png"
        },
        {
          "attribute_code": "options_container",
          "value": "container2"
        },
        {
          "attribute_code": "required_options",
          "value": "0"
        },
        {
          "attribute_code": "has_options",
          "value": "0"
        },
        {
          "attribute_code": "msrp_display_actual_price_type",
          "value": "0"
        },
        {
          "attribute_code": "url_key",
          "value": "keratin"
        },
        {
          "attribute_code": "tax_class_id",
          "value": "2"
        },
        {
          "attribute_code": "swatch_image",
          "value": "/k/e/keratinshampoo_500ml_.png"
        },
        {
          "attribute_code": "base_image_url",
          "value": "http://14.141.146.129:9292/pub/media/catalog/product"
        }
      ]
    }
  ],
  "search_criteria": {
    "filter_groups": [
      {
        "filters": [
          {
            "field": "sku",
            "value": "keratin",
            "condition_type": "eq"
          },
          {
            "field": "sku",
            "value": "Inspiring",
            "condition_type": "eq"
          }
        ]
      }
    ]
  },
  "total_count": 2
}

**Comment by mbrinton01** [comment]
@omkarambre for performance reasons it is not possible to search for multiple SKUs and return the extension attributes for each.  It requires two types of calls:
1. `rest/V1/products/?searchCriteria` call to get list of Products
2.  `rest/V1/products/{sku}` calls (one for each Product) to get extension attributes for each product

I'm closing the issue.  If you have additional questions related to this topic please post again here.
