### ISSUE TITLE
Calling REST "/V1/carts/mine" does not contain items

### ISSUE THREAD

**Issue by mackelito** [magento/magento2#6303]
### Steps to reproduce
1. Do a GET request to "/V1/carts/mine"
### Expected result
1. "quoteCartManagementV1" in http://devdocs.magento.com/swagger/index.html#/ tells us that it should provide the items in cart... but it does not
### Actual result

Items are not returned
### Note

I assume that the behaviour should be the same when requesting the guest-carts...

**Comment by mbrinton01** [comment]
Hello @mackelito, are you logged in at the time of the call?

**Comment by mackelito** [comment]
Yes... also the guest-cart do not require user to be logged in

An example of the response:'

``` javascript
{
  "id": 738,
  "created_at": "2016-08-17 19:53:19",
  "updated_at": "2016-08-23 13:37:00",
  "is_active": true,
  "is_virtual": false,
  "items_count": 3,
  "items_qty": 3,
  "customer": {
    "email": null,
    "firstname": null,
    "lastname": null
  },
  "billing_address": {
    "id": 1472,
    "region": null,
    "region_id": null,
    "region_code": null,
    "country_id": null,
    "street": [
      ""
    ],
    "telephone": null,
    "postcode": null,
    "city": null,
    "firstname": null,
    "lastname": null,
    "email": null,
    "same_as_billing": 0,
    "save_in_address_book": 0
  },
  "orig_order_id": 0,
  "currency": {
    "global_currency_code": "USD",
    "base_currency_code": "USD",
    "store_currency_code": "USD",
    "quote_currency_code": "USD",
    "store_to_base_rate": 0,
    "store_to_quote_rate": 0,
    "base_to_global_rate": 1,
    "base_to_quote_rate": 1
  },
  "customer_is_guest": false,
  "customer_note_notify": true,
  "customer_tax_class_id": 3,
  "store_id": 1
}
```

**Comment by mbrinton01** [comment]
I can't reproduce this result.  What version are you using?

Here are the steps I am using:
1. Create user account (in FE or admin, doesn't matter)
2. Clear browser cache
3. Login as user
4. Add item to cart
5. Open `http://<hostname>/index.php/rest/V1/carts/mine` in browser
6. Response includes item added to cart:

```
<item>
<item_id>7</item_id>
<sku>24-UG06</sku>
<qty>1</qty>
<name>Affirm Water Bottle</name>
<price>7</price>
<product_type>simple</product_type>
<quote_id>4</quote_id>
</item>
```

**Comment by antboiko** [comment]
Hi @mackelito , is there any update on this issue?

Thanks,
Anton.

**Comment by mackelito** [comment]
We have decided not to use magento api as it doesn't play nice with our expectations as frontend developers and will create custom endpoints.
