### ISSUE TITLE
[2.1.0] Design Configuration - Custom logo upload twice error (db media storage).

### ISSUE THREAD

**Issue by peec** [magento/magento2#6304]
### Preconditions
1. Magento 2.1.0
2. Nginx , PHP 7, Mysql 5.6. Varnish.
3. Production mode
4. Database media storage enabled.
### Steps to reproduce
1. Go into Content -> Design -> Configuration
2. Edit the global or view specific settings for the theme.
3. Under the "Header" pane, try uploading a new logo. Remember the image's name.
4. Save the theme configuration.
5. Edit the same theme settings again.
6. **Try uploading the same logo again. Error is given during ajax upload.**
7. Refresh the page ( when inside configuration still).
8. Try uploading the same logo again. Now it works.
### Expected result

The second time you upload a logo image, it should also work.
1. maybe giving the image a new random name or hash in the end of the file name of the image when upoaded).
2. maybe delete the old image and replace it with the name ( not so good ).
### Actual result

You get error message:

```
The file "/src/src/pub/media/tmp/design/file/pepsi.svg.png" doesn't exist or not a file
```

Note in the start of `/src/src/pub/media/tmp/design/file/pepsi.svg.png`.

Two times /src. My magento install is directly placed in `/src` and not `/src/src`. 
There might be something there.

**Edit to this ticket (26.08.2016):** Database media storage doesn't seem to work. It have tons of bugs like images despairing randomly if you delete files on the filesystem. I'm going back to regular filesystem and try to scale magento 2 in a different way..

**Comment by sevos1984** [comment]
hi! what is set in your Configuration>Web>Base URL for User Media Files? this affects path to media files

**Comment by developer-lindner** [comment]
@peec Update to 2.1.1. and report back if this issue still exists.

**Comment by kiazhi** [comment]
Having the same issue where saving the configuration of the Header logo image seems to be impossible on the Magento ver. 2.2.0-dev

The error message constantly returns back with the below, which does not exist at all:
The path ".:///var/www/magento2/var/www/magento2/" is not writable

**Comment by ArthurTransoftgroup** [comment]
@peec Unfortunately, I could not reproduce the issue as you described it. Please let us know what theme are you using? And is this issue still relevant?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
