### ISSUE TITLE
Current tab can't active after save product

### ISSUE THREAD

**Issue by bachlee89** [magento/magento2#6306]
Steps to reproduce
1. Go to Backend area, Catalog/Product , edit a product
2. Open any tab then input data
3. Click Save 

Expected result
- Current tab that selected should be active after click to save

Actual result
- Tab that selected before not active

**Comment by odubovyk** [comment]
Please specify information of your environment, php version, MySQL, web-server.

**Comment by bachlee89** [comment]
@odubovyk : Thank for your response. Here are my server information:
- Environment: Ubuntu 14.04
- PHP Version 5.6.23-1
- Mysql: 5.6.31
- Web server: Apache

If you need any other information, please let me know. 
Have a nice day!

**Comment by veloraven** [comment]
@bachlee89 please identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
