### ISSUE TITLE
Customer stuck in an endless loop

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#6307]
I am facing below issue in magento 2.0.7

http://magento.stackexchange.com/questions/131978/customer-stuck-in-an-endless-loop

**Comment by sunilit42** [comment]
added product into cart, now i am changing same product in backend like price so it set collect recollect in quote, 

When i am login with same quote then it will go infinite loop of that.

**Comment by odubovyk** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
