### ISSUE TITLE
Feature request: "Pack" of configurable products with stock control

### ISSUE THREAD

**Issue by seansan** [magento/magento2#6309]
Currently it is not possible to create 1 configurable product in a "pack" or "bundle" (from now on: pack) where the pack is seen as _one_ pack and not individual items. 

**Our request in short**: please expand stock control and allow for an attribute "qty in pack" which defaults to 1 piece but can be altered. Any product can be created just like you normally would with own title, sku, price, uri, meta etc... the only difference is that when the field "qty in pack" is populated and larger than 1, that when the product is sold or returned the stock movement is multiplied by "qty in pack"

I've seen this question been asked in a multitude of ways on forums and Stackexchange.

The major element to understand is that one wants to create a new standalone configurable prodcuts (say a T-shirt) where a customer would just like normal select the size and the qty and click add to cart. Only if the product was created as "pack" and the title of the product is "6 pack t-shirts" and the image shows 6 T-shirts etc.etc.: then one would still have to see QTY =1  on the frontend (because we are buying 1 pack) but the backend should now that it should register 6*qty (=6 in this example) when changing the underlying simple products stock 

More details and uses cases can be found here: http://magento.stackexchange.com/questions/111799/magento-products-packs-assortiment-with-size-and-stock-control-like-3-pack-o

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-quot-Pack-quot-of-configurable-products-with/idi-p/44856).

**Comment by shirtsofholl** [comment]
You could label it feature request and leave it in the excellent system called GitHub 

Setting up different flows or a no-flow support systems like a forum sounds a little 1.9x aka 2009. ..... but that's just my opinion
