### ISSUE TITLE
Image Management / Editing

### ISSUE THREAD

**Issue by bsstaveley** [magento/magento2#631]
It would be awesome if Magento had a better form of image management for both product images and content images. So view/edit existing images or re-use a previously uploaded image.

And also providing some form of editing for last minute cropping, rotating etc.

Maybe use something like Aviary for this, instead of building it - https://developers.aviary.com/

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28238

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Image-Management-Editing/idi-p/47023).
