### ISSUE TITLE
Changing products 'this item has weight' using 'Update Attributes' is not possible

### ISSUE THREAD

**Issue by hostep** [magento/magento2#6310]
### Preconditions
1. Magento CE 2.1.0
2. Have some virtual products in your catalogue
### Steps to reproduce
1. Select a couple of virtual products in the product grid in the backend
2. Choose 'Update Attributes' in the 'Actions' dropdown
3. Search for the weight field, you'll find it
4. Search for the 'This item has weight' or 'This item has no weight' dropdown, you won't find it
### Expected result
1. Expected to find the dropdown with the choices 'This item has weight' or 'This item has no weight'
### Actual result
1. No dropdown with choice 'This item has weight' or 'This item has no weight' found

I wanted to change a couple of 100 products which were Virtual Products because the weight setting was set to 'This item has no weight' to Simple Products using Update Attributes.
But this currently doesn't work, I have to open all those products manually one by one to change them to a Simple Product which is no fun :(

**Comment by sevos1984** [comment]
This is a known issue MAGETWO-45066, thanks for reporting

**Comment by flipflap** [comment]
When can we expect this option? It is very important to change config simple products to hast weight as guest checkout fails if they don't have.

**Comment by flipflap** [comment]
Any news about this issue?

**Comment by Jimgitsit** [comment]
Any workaround such as a DB query?

**Comment by flipflap** [comment]
I don't know exactly how to do it with a DB query. I think it should be a part of "update attributes". Other user may also need it.

**Comment by jeanpham** [comment]
Any update on this issue? It's just crazy this bug is still in there

**Comment by tek-moe** [comment]
This is a critical issue since it can easily compound with configurable products. My client has to go through 50+ records at a time just to change from a virtual product to simple product by changing the weight attribute flag to "this item has weight". You can even give that virtual product a weight via mass attribute change and the flag will still display as this item has no weight with an integer assigned to wieght which clearly indicates that there is weight.

**Comment by flipflap** [comment]
Seems not yet fixed in Magento 2.1.4 :-(
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.4CE.html

**Comment by illyalvov** [comment]
What about 2.1.5?

**Comment by flipflap** [comment]
Unfortunately, I think not:

> This release updates the copyright date in every file. It does not contain any functional changes or security improvements.

**Comment by Shimon2** [comment]
I had a similar problem.  I wanted to import them as Virtual products.  The standard import won't do this.  My work around for now was to go into the database and simply set the type_id to "virtual"
I created a CSV that had sku and product_type.
I imported it into the database.  It became TABLE360.
I then ran the following SQL

update catalog_product_entity c
set c.type_id = "virtual"
where c.sku in
(select im.sku
                   from TABLE360 im
                   where
                   im.product_type = "virtual" );


So far so good.

**Comment by Fab-z4qx** [comment]
Still any patch for this issue... What is the schedule for Magento release ?

**Comment by didactica** [comment]
Hi, any ideas how to update "this item has weight" directly into the database? Any help would be appreciated.

**Comment by amcastror** [comment]
Hi, any ideas how to update "this item has weight" directly into the database? Any help would be appreciated.

**Comment by flipflap** [comment]
I used this SQL statement in phpMyadmin and that changed all virtual products to simple products:

`update mg_catalog_product_entity set type_id = ‚simple' where type_id = 'virtual'; `

**Comment by magento-engcom-team** [comment]
@hostep, thank you for your report.
We've created internal ticket(s) MAGETWO-45066, MAGETWO-80256 to track progress on the issue.

**Comment by harshvardhanmalpani** [comment]
This error persists in 2.2.2
Temporary fix - 

> UPDATE `catalog_product_entity` SET `type_id`="simple" WHERE `type_id`="virtual"

**Comment by EujenMerezhka** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@EujenMerezhka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by uwon** [comment]
am working on this #dmcdindia2019

**Comment by uwon** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@uwon thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#26075 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [2506c0824c4db0819ce4e8519992f21cabdd2a59](https://github.com/magento/magento2/commit/2506c0824c4db0819ce4e8519992f21cabdd2a59)
 - [f6f414b7feb964192742795e2a82e2db042d76ae](https://github.com/magento/magento2/commit/f6f414b7feb964192742795e2a82e2db042d76ae)
 - [36738ecd4c8a7ad1f5b445c96d1bcd1289f65cb8](https://github.com/magento/magento2/commit/36738ecd4c8a7ad1f5b445c96d1bcd1289f65cb8)

The fix will be available with the upcoming 2.4.0 release.

**Comment by ajay1987kumar** [comment]
UPDATE `catalog_product_entity` SET `type_id` = 'simple' WHERE `catalog_product_entity`.`type_id` = 'virtual';

this worked for me!!!!!!!
it will make you product with "item has weight"
