### ISSUE TITLE
Not able to set creditmemos collection on a order.

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#6314]
## Preconditions
1. Magento 2 develop branch
2.  php 7 and mysql 5.6
### Steps to reproduce
1. app/code/Magento/Sales/Model/Order.php is missing a setCreditmemosCollection function to be able to add programmatically a creditmemo collection to a order.
### Expected result
1. To be able to set a creditmemo collection on a order programmatically through a setCreditmemosCollection function in app/code/Magento/Sales/Model/Order.php
### Actual result
1. Not able to set a creditmemo collection on a order programmatically through a setCreditmemosCollection function in app/code/Magento/Sales/Model/Order.php

**Comment by vrann** [comment]
@basselalaraaj the drawback of such change is added coupling between order and credit memo and weak encapsulation of the credit memo field.
