### ISSUE TITLE
Category sort position function fails for Widget Catalog Product List

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#6318]
### Preconditions

1. Magento 2.0.9
### Steps to reproduce

1. Ad the Widget Catalog Product List to homepage
2. Ad a condition for a specific category
3. Try to sort products in the category by position
### Expected result

1. Products on homepage should in sort position of category
### Actual result

1. Products on homepage are not sorted at all

**Comment by tkacheva** [comment]
@flipflap Are you trying to sort product in specific Category that is mentioned in the widget and expect products to be sorted in the widget as well as in the corresponding category page? If so, Magento doesn't support this. Products can not be sorted in the product list widget.

**Comment by flipflap** [comment]
@tkacheva thanks. Yes I try to do that. But what sort order does the product list widget list have? Is there really no way to sort them?

**Comment by tkacheva** [comment]
@flipflap Are you referring to _sort order_ option in _storefront properties_ section? It's sort order widgets that are placed in the same container via layout update.

**Comment by flipflap** [comment]
@tkacheva I don't understand exactly. But I use the list widget to show products of a specific category on the homepage and would like to sort this products there on homepage.

**Comment by tkacheva** [comment]
@flipflap I see. This is feature request. Could you add it to [Magento Forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests)?

**Comment by flipflap** [comment]
Ok, thanks!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Category-sort-position-function-fails-for-Widget-Catalog-Product/idi-p/48321).
