### ISSUE TITLE
Customer attribute - values for deleted entities are not removed

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#6319]
### Preconditions

1. I use Magento 2.1 CE, PHP 7.0
### Steps to reproduce

1. I have added some customer attributes programaticaly.
2. It saves and works normally.
3. I have deleted the instance of customer.
### Expected result

1. Values provided for that entity also should be removed.
### Actual result

1. Actually they are not - it' really painful when attribute is unique - I can't add value equal to the one which should have been deleted when removing entity of customer.
2. What is worse, there no message that I am trying to violate unique character of attribute.

**Comment by sevos1984** [comment]
Neither attributes nor values are removed with entity in magento. And uniqueness are respected in scope of one entity only, how do you violating that? Thanks.

**Comment by bartoszkubicki** [comment]
Attributes are not removed, that's clear. 
The problem occurres as I have described it in my report. I add new entity of customer (with custom unique attribute). Value for that attribute is for example `test`. Then I delete this entity and after that I try to add it again with same value - and in that point there is a problem - javascript validation blocks saving entity as it's not unique. I don't think it's desired behaviour - maybe some sort of cascade should be added here or it's some sort of different sort of reason causing this.

**Comment by sevos1984** [comment]
I can't create customer attribute with unique value. This is not native magento behavior.

**Comment by bartoszkubicki** [comment]
I create it programatically, like this:

```
`$customerSetup->removeAttribute(Customer::ENTITY, 'login');
            $customerSetup->addAttribute(
                Customer::ENTITY,
                'login',
                [
                    'type' => 'varchar',
                    'input' => 'text',
                    'frontend_class' => '',
                    'label' => 'Login',
```

```
                'position' => 160,

                'backend' => '',
                'frontend' => '',
                'source' => '',

                'default' => '',

                'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
                'visible' => true,
                'required' => true,
                'user_defined' => true,

                'unique' => true,

                'input_filter' => '',
                'multiline_count' => 0,
                'validate_rules' => '',

                'is_used_in_grid' => false,
                'is_visible_in_grid' => false,
                'is_filterable_in_grid' => false,
                'is_searchable_in_grid' => false,

                'system' => 0
            ]
        );

        $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'login')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer'],
            ]);

        $attribute->save();`
```

In adminhtml I can add to customer value which is unique.

**Comment by skovalenk** [comment]
@bartek9007 You have problems only with JavaScript validation?

**Comment by bartoszkubicki** [comment]
As you can see I don't add any js validation class, but attribute is set as required and to omit this problem I could manually change in `eav_attribute` table value for `is_required` from `1` to `0`. Then problem 'dissapeared'.

**Comment by Kanabist** [comment]
@bartek9007 I just need to know either the problem connect with JavaScript or PHP. Because some JavaScript problems can be resolved with flushing browser cache, cookie and local storage. Have you try this actions?

**Comment by sevos1984** [comment]
Is this still actual in latest release version?

**Comment by bartoszkubicki** [comment]
I am happy to say it is not :)
For example `email` attribute only values in `customer_entity_varchar` are ones connected with existing customer entities.

**Comment by sevos1984** [comment]
Thanks for reply, I will close this ticket
