### ISSUE TITLE
Fix the font size in the backend content area

### ISSUE THREAD

**Issue by mSengera** [magento/magento2#632]
Can you fix the font-size in the content area in backend or replace for example the h3 headlines with a light font? in my opinion it is at all too big. 

If you like i can fix this too and start than a pull request. That are small CSS changes.

Extrem is it in the configuration tabs. I think the ".section-config" headlines are too big.
What is your opinion about that? would we like to fix it or is it in your opinion good?

Best regreats from germany

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28240

**Comment by ilol** [comment]
@mSengera since nobody wrote about related topic I am closing the issue.
Thank you for your opinion and be the same initiative.
