### ISSUE TITLE
Cannot create Customer with Date of Birth in Magento 2.1 (en_GB locale)

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#6323]
### Environment
1. Apache 2.4.17
2. MySQL  5.0.11-dev
3. PHP 5.6.15
4. Magento 2.1.0
### Steps to reproduce
1. In System > All Users > User > [You], set the interface locale to English (United Kingdom):
   ![blog-3](https://cloud.githubusercontent.com/assets/8377620/17434109/7a89183c-5b00-11e6-8c8f-2a30db35c5a7.png)
2. Create a new customer. Make sure to fill in Date of Birth field:
   ![c-1](https://cloud.githubusercontent.com/assets/8377620/17934523/2655ab94-6a10-11e6-9748-4c79a7830eb6.png)
3. Save Customer
### Expected result
1.  Customer saves without error
### Actual result
1.  "Invalid date" exception thrown: 
   ![c-2](https://cloud.githubusercontent.com/assets/8377620/17934534/2c95151c-6a10-11e6-8b35-d4c714c4f346.png)
2. Trying to save the new customer again results in a JS validation error: 
   ![c-3](https://cloud.githubusercontent.com/assets/8377620/17934650/9e16396e-6a10-11e6-9397-6b3d3de1dd8d.png)
### Cause
- The culprit is [Date::inputFilter()](/magento/magento2/blob/2.1.0/lib/internal/Magento/Framework/Data/Form/Filter/Date.php#L55)
- In my case, Date::inputFilter() accepts `08/24/2016` and returns `0,8/2,4/2,016`
- `0,8/2,4/2,016` is not a real date in any locale, causing an exception to be thrown.
### General locale issues in Magento 2.1
- Changing admin locale from en_US to en_GB causes PHP date formats to change, but not JS date formats.
- In the above example, the JS datepicker populated the field with `08/24/2016`, despite the entire UI being in en_GB.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-57835, thanks for reportng

**Comment by slavvka** [comment]
The issue has been fixed and delivered to develop.

**Comment by JacobDrummond** [comment]
@slavvka, thanks! :)

**Comment by sopedro** [comment]
In frontend the date works well, the issue is just in backend and with all dates. The reports don't work too.

**Comment by JacobDrummond** [comment]
@sopedro, Magento2 admin locale is a mess. See, for example, #7888, #9426, #8849.

These, and similar issues, are widely-reported but development seems to slow.

**Comment by vherasymenko** [comment]
Steps to reproduce:
1. Install Magento latest develop version.
2. Go to Admin side
3. System > All Users
4. Choose your user, then set Interface local to United Kingdom
5. Click "Save"
6. Click "Customers > All customers"
7. Click "Add new"
8. Fill all required fields
9. Choose birthday date "Today"
10. In email field enter already existed email address
11. Click "Save"
12. After error change email on non existing and click "Save"

AR: Displayed error about incorrect date
ER: Customer should be saved

Note: but after first saving date changed on other date automatically.

**Comment by nitin700** [comment]
I am working on it..

**Comment by Emadis** [comment]
Issue fixes 1 month ago.
Thank you

**Comment by nitin700** [comment]
@Emadis Thanks for the information.

**Comment by magento-engcom-team** [comment]
@JacobDrummond, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by danharper83** [comment]
Still a issue for 2.2.3

Trying to set "Set Product as New From"

Message "Invalid input datetime format of value '31/05/2018"
