### ISSUE TITLE
Multiple password change requests

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6327]
### Preconditions

When I´m trying to access the admin panel of my magento 2.0.9 I`m asked to change the password. Once I updated the password I`m still not able to access other pages, the same password change request page is displayed again and again. 

Any idea?
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@postmassimo thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
