### ISSUE TITLE
Problem with installing 2.1.0 With Command Line

### ISSUE THREAD

**Issue by wblayney** [magento/magento2#6328]
### Preconditions

1. I'm magento 2.0.9 and I'm trying to update to 2.1.0
2. I've tried using the inbuilt feature to update, but I'm getting an issue that's [already been covered in a separate forum; It cant take that action right now](http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html)
### Steps to reproduce

1. I ran the command `composer require magento/product-community-edition 2.1.0 --no-update
   `
2. and then `composer update`
### Expected result

1.  install the update
### Actual result

1. `_showson@n3plcpnl0052 [~/public_html]$ composer update
   Loading composer repositories with package information
   Updating dependencies (including require-dev)
   Your requirements could not be resolved to an installable set of packages.
   
   Problem 1
   - The requested package magento/product-enterprise-edition could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.`_

my composer.json looks like 

> `{
>     "name": "magento/project-community-edition",
>     "description": "eCommerce Platform for Growth (Community Edition)",
>     "type": "project",
>     "version": "2.0.9",
>     "license": [
>         "OSL-3.0",
>         "AFL-3.0"
>     ],
>     "repositories": [
>         {
>             "type": "composer",
>             "url": "https://repo.magento.com/"
>     }
>     ],
>     "require": {
>         "magento/product-community-edition": "2.1.0",
>         "composer/composer": "@alpha",
>         "magento/product-enterprise-edition": "2.1.0"
>     },
>     "require-dev": {
>         "phpunit/phpunit": "4.1.0",
>         "squizlabs/php_codesniffer": "1.5.3",
>         "phpmd/phpmd": "2.3.*",
>         "pdepend/pdepend": "2.2.2",
>         "sjparkinson/static-review": "~4.1",
>         "fabpot/php-cs-fixer": "~1.2",
>         "lusitanian/oauth": "~0.3 <=0.7.0"
>     },
>     "config": {
>         "use-include-path": true
>     },
>     "autoload": {
>         "psr-4": {
>             "Magento\\Framework\\": "lib/internal/Magento/Framework/",
>             "Magento\\Setup\\": "setup/src/Magento/Setup/",
>             "Magento\\": "app/code/Magento/"
>         },
>         "psr-0": {
>             "": "app/code/"
>         },
>         "files": [
>             "app/etc/NonComposerComponentRegistration.php"
>         ]
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
>             "Magento\\Tools\\": "dev/tools/Magento/Tools/",
>             "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
>             "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
>             "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
>         }
>     },
>     "minimum-stability": "alpha",
>     "prefer-stable": true,
>     "extra": {
>         "magento-force": "override"
>     }
> }
> `

**Comment by wblayney** [comment]
I just ran `composer diagnose`
to which I got `Checking composer.json: FAIL
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/product-community-edition : exact version constraints (2.1.0) should be avoided if the package follows semantic versioning
require.composer/composer : unbound version constraints (@alpha) should be avoided
require.magento/product-enterprise-edition : exact version constraints (2.1.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: Warning: Accessing packagist.org over http which is an insecure protocol.
OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: FAIL
You are not running the latest stable version, run`composer self-update`to update (1.1.1 => 1.2.0)
`
I then ran `composer self-update`
and received `Updating to version 1.2.0 (stable channel).
    Downloading: 100%

  [ErrorException]
  rename(/opt/cpanel/composer/bin/composer): failed to open stream: Permission denied

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]`

**Comment by fooman** [comment]
Do you use Enterprise or Community? 

> I ran the command composer require magento/**product-community-edition** 2.1.0 --no-update 

vs. 

> The requested package magento/**product-enterprise-edition** could not be found in any version, there may be a typo in the package name.

If you are an Enterprise customer contacting Magento support directly might be the better option.

**Comment by Cacasapo** [comment]
> [ErrorException] rename(/opt/cpanel/composer/bin/composer): failed to open stream: Permission denied

You need to be root to update composer.

**Comment by veloraven** [comment]
@wblayney thank you for your feedback.
Was it CE or EE?

**Comment by udhayakumars-react** [comment]
Checking composer.json: FAIL
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance

pls help me

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by veloraven** [comment]
@udhayasuresh please create another issue with full description of your problem according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
