### ISSUE TITLE
Usage of period in html element id attribute 

### ISSUE THREAD

**Issue by will-b** [magento/magento2#6329]
Why do some html elements have dots instead of dashes or underscore in their id attributes? 

```
id="store.links" 
```

This means that you will have to escape the selector when targeting it.
Is there a benefit to this? 

When targeting these ids (not ideal but if you have to) in sass or less this only leads to confusion.

**Comment by veloraven** [comment]
@will-b thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
