### ISSUE TITLE
Product video not display ver. 2.0.2

### ISSUE THREAD

**Issue by krzysztofkacela** [magento/magento2#6331]
Hi,
1. Preconditions
   Magento 2.0.2 CE
2. Steps to reproduce
   Create Product.
   Add Video. https://gyazo.com/55b06263edc0fd663383857ae971b19a
   Go to product view on frontend. Check gallery there is preview image and not video.
3. Expected result
   Video should appear and be able to play.
4. Actual result
   There is preview image and not video.

Best regards,
Krzysztof

**Comment by veloraven** [comment]
@krzysztofkacela thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by krzysztofkacela** [comment]
@veloraven thank you for response.
I've changed format.

**Comment by developer-lindner** [comment]
@krzysztofkacela please update to 2.1.1 and report back or close this issue otherwise.

**Comment by PetraSwed** [comment]
@krzysztofkacela can you explain what you mean you have changed format? I am having the same issue.

**Comment by krzysztofkacela** [comment]
@developer-lindner I've updated magento to 2.1.1 and it's working now, thank you.

@PetraSwed oh I think you misunderstand It's about format of issue. Anyway it work after update to 2.1.1 version.

**Comment by krzysztofkacela** [comment]
@PetraSwed 
@developer-lindner 
Hi There again, I think I found the problem (it's still appear on magento 2.1.1).

When I added my own theme it seems to be buged. And the bug appear when you copy 
module-catalog/view/frontend/layout/catalog_product_view.xml to your own theme (Magento_Catalog/layout/catalog_product_view.xml).

How to fix:
Just edit copied file and remove/comment this part
https://gyazo.com/c0a36ca10d8af4194bebfd43e68a114e

It's seems to work now everything for me.

**Comment by AgenturSchroeder** [comment]
Hi There,

it doesn't work for me.
If I delete all of my custom xml construction from my custom theme catalog_product_view.xml file, than the default xml file construct the page but the video still doesn't work.

I don't have anny script errors and the youtube preview picture is shown but i can't play the video.
There is no button or something to show it and i can't see a embed code.

I think it's not the right way to close this bug if it's still not fixed.
It could not be a reason that I have to go back to the default xml file.

**Comment by henk-hypershop** [comment]
Same here. Added custom theme, made some changes to catalog_product_view.xml and video is not working anymore. Why close this issue when this has not been fixed yet?

**Comment by makanaashish** [comment]
I am facing the same issue, i have installed porto theme and the site is on Magento CE 2.1.1 and the video doesn't appear on the product page

**Comment by AgenturSchroeder** [comment]
Why did you close this report?
The bug is still there.

**Comment by makanaashish** [comment]
Any update on this issue

**Comment by pritam82in** [comment]
I have found a solution for this issue.
1) Open   **catalog_product_view.xml** inside your theme folder(i.e. app/design/frontend/vendor/theme/Magento_Catalog/layout/catalog_product_view.xml).
2) Search for the container Name "**product.info.media**" inside catalog_product_view.xml file
3) Now add **`<block class="Magento\ProductVideo\Block\Product\View\Gallery" name="product.info.media.video" after="product.info.media.image" template="product/view/gallery.phtml"/>`**  under  "product.info.media" container.

"product.info.media" container will look like below xml after updating:
```
<container name="product.info.media" htmlTag="div" htmlClass="product media" after="product.info.main">
                <block class="Magento\Catalog\Block\Product\View\Gallery" name="product.info.media.image" template="product/view/gallery.phtml"/>
                <block class="Magento\ProductVideo\Block\Product\View\Gallery" name="product.info.media.video" after="product.info.media.image" template="product/view/gallery.phtml"/>
</container>

```
4) Now refresh your Magento 2 cache and you should get the product video in product detail page.

**Comment by AgenturSchroeder** [comment]
Thats a nice idea, but i cant edit my custom theme like this without losing my own changes in the xml.
I changed the position to an other block, because I need the block at a different place in the frontend.

**Comment by skynixukraine** [comment]
Hello,

Magento 2.1.7 Video still does not work on mobile

**Comment by anglerthulasiram** [comment]
Hello,

After adding video, there is showing preview image and not video in front end. Magento version as 2.1.2

**Comment by karlsminton** [comment]
I'm experiencing this issue on 2.2.2 currently.

**Comment by AliceAdl** [comment]
I’m having the same issue - uploading videos simply adds a still image

**Comment by RahulRajputana-Dev** [comment]
On default magento theme and solwinnfreego theme video is playing fine. But after installing porto theme just showing thumbnail of youtube video instead of play. Does anyone know how to fix it?
Also non of product view is working. Please check video.
https://youtu.be/6k-caGMy6xw

**Comment by jonathanbray02** [comment]
I have the same issue. I tried code but not working
