### ISSUE TITLE
Magento 2 Transactional Emails

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#6332]
### Preconditions

1. Magento 2.1.0
2. 
### Steps to reproduce

1.  In mail sending settings I used smtp.office365.com and port 587 so that I can use my office 365 account for email communications in magento.
2. I added my sending email address in the "Store email addresses"
### Expected result

1. The order/invoice etc email should go to the customer. 
### Actual result

1. The customer does not receive email.

**Comment by sevos1984** [comment]
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
