### ISSUE TITLE
Magento-2.1 error with queue Newsletter,missing "Class Magento\Newsletter\Model\ResourceModel\Subscriber\CollectionFactory"

### ISSUE THREAD

**Issue by HZSGit** [magento/magento2#6334]
I try to set a Newsletter Template to Newsletter queue.When i choose "Queue Newsletter" option,I am getting error repot "Class Magento\Newsletter\Model\ResourceModel\Subscriber\CollectionFactory does not exist",I can not find file at "<magento install dir>vendor/magento/module-newsletter/Model/ResourceModel/Subscriber"
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@HZSGit thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
