### ISSUE TITLE
Magento CE 2.1.0 : Unable to generate "extra_large" catalog.

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#6336]
### Preconditions

1. Magento Community 2.1.0 freshly installed with composer create-project 
2. Debian Wheezy 
3. PHP Version : PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
   Copyright (c) 1997-2016 The PHP Group
   Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
   with Zend OPcache v7.0.10-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
4. MySQL 5.7.14-7 Percona Server (GPL), Release '7', Revision '083e298'
### Steps to reproduce

1. Fresh install of Magento 2.1.0 : composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition src 2.1.0
2. Once installed, just run  bin/magento setup:perf:generate-fixtures /var/www/magento/src/setup/performance-toolkit/profiles/ce/extra_large.xml
### Expected result

1. The "extra_large" catalog should be generated without errors.
### Actual result

This happens each time I try to launch the generation (I re-create a new empty database and reinstall Magento each time before retrying).

big-magento2:/var/www/magento/src# bin/magento setup:perf:generate-fixtures /var/www/magento/src/setup/performance-toolkit/profiles/ce/extra_large.xml Generating profile with following params:
 |- Websites: 5
 |- Store Groups: 5
 |- Store Views: 5
 |- Categories: 3000
 |- Simple products: 800000
 |- Configurable products: 50000
 |- Customers: 5000
 |- Cart Price Rules: 100
 |- Catalog Price Rules: 100
 |- Orders: 80000
Generating websites, stores and store views...  done in 00:00:00
Generating categories...  done in 00:01:09
Generating simple products... Error in data structure: entity values are mixed

**Comment by sevos1984** [comment]
Thanks for posting, internal ticket created MAGETWO-57699

**Comment by romainruaud** [comment]
Hello @sevos1984 and thanks for your quick reply.

Any chance to get a workaround here while waiting for you to release a branch including this fix ?

**Comment by sevos1984** [comment]
Hi! You can edit any profile that is working and add as many entities as you need, e.g small.xml is working for me.

**Comment by romainruaud** [comment]
Hello @sevos1984 yes the small one is working for me, but I need a huge catalog for testing purposes. So if you have a quickfix for this one or if you can provide me the patch used to fix this issue, I would appreciate so much. 

Regards.

**Comment by sevos1984** [comment]
Sorry but no quick fix. Why you can't extend small with entities you need? Or it will fail as well?

**Comment by romainruaud** [comment]
I am doing tests for "very big" catalog, something like 2 billions of products at the end. Yes, I am pushing to the limits.

So my first test was to use the extra_large profile (800.000 products) to begin, and I planned to write a custom "huge" profile later with 2 billions products.

But since the extra_large profile fails, I can't even begin my tests. The 'small' profile does not help since 800 products is not relevant for my test case.

I have also written a custom profile which uses only 500K products, but it fails too, with a different error this time :  

big-magento2:/var/www/magento/src# bin/magento setup:perf:generate-fixtures /var/www/magento/src/setup/performance-toolkit/profiles/ce/custom.xml 
Generating profile with following params:
 |- Websites: 5
 |- Store Groups: 5
 |- Store Views: 5
 |- Categories: 3000
 |- Simple products: 500000
 |- Configurable products: 50000
 |- Customers: 5000
 |- Cart Price Rules: 100
 |- Catalog Price Rules: 100
 |- Orders: 80000
Generating websites, stores and store views...  done in 00:00:01
Generating categories...  done in 00:01:05
Generating simple products... Warning: Error while sending QUERY packet. PID=1016 in /var/www/magento/src/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

So what I need concretely is : 
- a generator not failing for the extra_large profile
- and if possible, a generator working for bigger than the extra_large profile (which should be OK to do since the generator accepts custom profiles).

Regards,

**Comment by choukalos** [comment]
Please share your insights with us (blog & share link, or you can email me directly - my email is in my profile).  Please share PR's - cc me on them and I can escalate if appropriate.

We haven't run any performance tests with 2B sku's (or anything close to that) on Magento 2.  so I'd caution there's likely to be a few areas that you'll need to tune or customize.  

Some notes/thoughts:
1.  The generator for a large profile takes about a day to create the DB, extra large takes several days to a week (I've got a story in the backlog to make this faster; quick hack is to generate and then save db dump, swizzle the SQL with grep for running different scenarios)
2.  The generator takes up a large chunk of memory when you're generating large profiles, believe we use 16GB when generating an extra large (again part of the story to make faster/reduce ram usage)
3.  Indexing with very large catalogs can take a some time.  @IvanChepurnyi presented the idea of multi-threading indexers as an improvement at Dev Paradise [Link](http://www.developers-paradise.com/wp-content/uploads/2016/05/16-Ivan-C-Indexation.pdf).  Yup, I've got that in backlog.  
4.  Effective catalog size for Magento is a function of sku count, websites/store views, and customer groups.  So if you're going to run 2B sku's for 5 websites, with 5 store views each and the default 3 customer groups the database will see much heavier queries then if you just did 1 website with 1 store view.  Note to that advanced sku's have a higher weight then simple skus.  For example a configurable product with 3 product variants looks to the database like 4 simple products (meta product, ~ 3 simple products for each of the variants), so lots of advanced products results in heavier queries for the database then simple products.  Something to consider when you design your catalog / store.
5.  At a certain point MySQL is likely to require clustering, tuning or perhaps even hit a point where there's significant performance degradation in query performance.  There's a number of Magento 1 sites that have been customized to use Solr or Elasticsearch for very large catalogs and have seen a lot of success with that approach.

-Chuck

**Comment by romainruaud** [comment]
Hello @choukalos and thank you for you long answer. It is nice to see that my question seems interesting to you.

About insights, we already planned to release a blog article or something else to the community after the testing session (if we find something accurate and interesting to share with everybody). 

Regarding the PRs and escalation, I'd gladly appreciate if you could escalate this issue :) So i would be able to begin testing soon if I have a working generator for extra large profile (and able to create a custom profile even bigger).

I will now try to answer you point by point : 
1. _ouch_. I did not expect it would take one day (and one week), but I was planning something like your strategy with the dump to enable fast re-deployment of the database elsewhere.
2. I should have a production-like machine for my testing purposes, so I hope everything will go well regarding the amount of RAM used.
3. Yes, indexing is one of the bottlenecks I need to check against a big catalog. Thank you for the link but I do not see anything related to multi-threading in those slides ? I keep the idea in my mind anyway, thank you for sharing it.
4. Yup, that's something I perfectly know, we made big websites on Magento1 (some with billions of simple products in mono-store, some with 50k configurable/bundle and 300K simple but 7 website / 21 store views, etc ... ) : differents designs, but each time a challenge to manage the big size.
5. You are right indeed about MySQL, we first used SolR in Magento1 to handle such catalogs but we finally released this MongoDB implementation which is running really good in production : https://github.com/Smile-SA/mongogento

Thank you again to have taken some time for answering me.

We'll keep in touch !

Regards,

**Comment by IvanChepurnyi** [comment]
@romainruaud Concerning parallel indexation, it was done in part on parallel indexation workshop and conference talk was about decoupled indexer structure that allows non-blocking implementation and parallelization on large data-sets. In the slides, there is a reference to an example of such an indexer with parallel indexation implementation.

**Comment by IvanChepurnyi** [comment]
@romainruaud thanks for sharing your MongoDb implementation, it looks interesting. I've used MongoDB only as a caching layer between Magento and MySQL but still use EAV for storing the data, as exporting records by ID is almost no overhead to a MySQL DB. But exporting this data to the third-party system from MongoDB is not that fast is it possible to do from MySQL directly. 

Only place where you shouldn't use MySQL is a large database is searched, as it requires the better app for it (Sphinx, Solr, Elastic) and MongoDB serves only as efficient complex data cache in between them, not that good for search.

**Comment by romainruaud** [comment]
Hello @IvanChepurnyi , on M1 we had quite faster exports when reading data from MongoDB instead of MySQL, the simple fact that we were able to avoid many joins to EAV tables to get values was indeed better for us. And as we would have do with MySQL, all exports written with MongoDB were written with an "iterator logic" processing products one by one.

By doing this, we are able to index big catalog (2M simple product) in ~1h30 into ElasticSearch (see our ElasticSearch implementation for M1 here : https://github.com/Smile-SA/smile-magento-elasticsearch ) which is quite good we think (especially regarding that many attributes data have to be reworked during the indexation process).

We also experienced quite better "filtering" usages by using MongoDB : especially back-office product grids, which were quite faster than with MySQL (yes, we could also have plugged the search engine here instead of MongoDB).

On frontend, performances were better with using MongoDB when rendering product lists, especially if you have a lot of attributes to render on the product list (which would result to many joins with a legacy MySQL backend).

But yes, this implied many rework to have several classes to read/write data by using MongoDB instead of MySQL. Maybe we could have do less work by replacing the "flat catalog" index by a MongoDB implementation and keep the data in MySQL.

**Comment by IvanChepurnyi** [comment]
Hey @romainruaud, 1h 30m is a bit too long for export process. I was effectively exporting 200k of skus for a single store view in 40s to external storage. You don't need to use JOINs on EAV structure in order to export it, there are much better ways to export data in a simple and scalable way. Magento itself didn't yet push MySQL to the limits, and if you do build your queries efficiently it can cope with billions of records without huge penalties.

Please refer to this talk of mine during MageTitans in Italy concerning MySQL performance:
https://www.youtube.com/watch?v=U_XSFUJAPe4

**Comment by romainruaud** [comment]
I was not speaking exactly about exporting, but about indexing the catalog in ElasticSearch, which implies that it cannot be "pure SQL" but need to have PHP working on each product to format data properly (casting, exploding if needed, having integer value and text label if attribute is used for filtering, etc...) which is an incompressible time consumer for the indexing process.

But anyway, this is interesting to listen different point of views and thank you for the link to your talk, I will watch it and share it to my colleagues too :)

I think this thread has a little derivated from the initial statement :) But one thing is sure for me : this should not take a week to generate 800K products in Magento as Chuck said above, maybe you should help them to improve their generator ;)

**Comment by choukalos** [comment]
Hey @romainruaud quick update.

We have a pretty simple architecture where our MPAF tool generates everything into memory and then loads in the DB.  Unfortunately that means when generating a large # of product it sucks up a lot of memory.  Our server where we generate a large profile has MySQL tweaked to use up to 24G of ram (yikes).  

We should be doing this via pagination and should be using far less memory.  We've also got a # of improvements we want to introduce.  I've added some requirements around restructuring our tool kit for both memory usage and performance to that ticket (Internal ticket.  MAGETWO-50925; linked to this Github issue).

**Comment by romainruaud** [comment]
Hello @choukalos and thanks for the update. Could you share the MySQL configuration you use on this server ? I am able to use huge servers in my company so I'd gladly give it another try :) 

Nice to see the subject is tracked by an internal ticket, I'm happy to see your team is concerned about it and will provide improvements.

Best regards,

**Comment by southerncomputer** [comment]
I have production import of 700k to 1.4MIL IT products in databases with several thousand searchable attributes and several thousand non-searchable. In both EE and CE flavors. 

I do wonder about using INT(11) as auto-increment now that php-7 64bit is out - shouldn't it be time to move to bigint ? 2B products would overflow entity_id in catalog_product_entity - and no doubt break all _tmp memory indexes used in some variants of indexing. 

catalog_category_product_index_tmp  comes to mind - fails every time you reindex on 700K products due to table is full- have to change table to innodb to complete!

My theory was to store attributes permanently in Elasticsearch - reducing mongodb out of the picture and EAV out of the picture at the same time.

But if you need 700K to 1.4MIL products in 1000's of categories - I can supply that - The reason I use ElasticSuite is that it can handle indexing this without having 16GB of ram for 1 PHP process end up core-dumping due to out of memory (2.1.1 EE and CE)!

**Comment by romainruaud** [comment]
Wow @southerncomputer you are probably the biggest website using ElasticSuite then and have probably gone further than us about catalog size.

Would you mind sharing your experience with the module to us by email ? (our email address is everywhere in the module files)

I faced the "Table is full" issue ! I did not even think to check the table engine... Thank you for the pro tip !

And if you are able to share me one of your dump it would be just ideal ! I am still stuck at creating such a huge one. I do not need customer/sales/cms part then, feel free to remove it before sending me if you think it's too sensitive.

And again, thank you for supporting our search engine :)

**Comment by romainruaud** [comment]
Hello @choukalos 

Just to let you know, I managed to generate by myself a sample catalog of 3 millions products since your tool is quite unusable for doing it.

I have been running many tests on several magento instance last weeks, let me know if you wanna hear about this.

BR.

**Comment by Morgon** [comment]
An additional issue related to this is that I am unable to get the fixtures to work if I change the values. The very first time I ran this, I was able to get products. But for whatever reason, even on a fresh 2.1.2 install (older on purpose), when it gets to the 'Generating simple product' section, it was hanging for hours without adding any products.

I started sniffing the traffic for MySQL and noted that it was sending the following query (and only this query) repeatedly:

```
SELECT `catalog_product_entity`.`entity_id`, `catalog_product_entity`.`type_id`, 
`catalog_product_entity`.`attribute_set_id`, `catalog_product_entity`.`sku`,
 `catalog_product_entity`.`row_id` FROM `catalog_product_entity` WHERE
 (catalog_product_entity.created_in <= 1) AND (catalog_product_entity.updated_in > 1)
```

I don't know what it was expecting to receive from this, as no products had yet been created. But this tool needs to be fixed.

**Comment by magento-engcom-team** [comment]
@romainruaud, thank you for your report.
We've created internal ticket(s) MAGETWO-57699 to track progress on the issue.

**Comment by jissereitsma** [comment]
My 50c: I've run this various times in the past without issues and just days ago with the `extra_large` profile. No issues at all. It might be that the original issue that started this thread has been solved already.

Perhaps for documentation: I ran the data generation on a PC with 16Gb of RAM, no SSD disk, MySQL 5.7 optimized (InnoDB buffer pool cranked to 4Gb and query_cache to 1 Gb) and PHP 7. The generation took about 18 hours and the database is now 17Gb in size. However, no issues at all.

**Comment by magento-engcom-team** [comment]
@romainruaud, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
