### ISSUE TITLE
"Unable to place order. Please try again later" in a clean Magento 2.1.0

### ISSUE THREAD

**Issue by esilvajr** [magento/magento2#6339]
After install a clean Magento 2, my custom payment module doesn't work anymore...

I'm using PHP 7.0.6, MariaDB in a CentOS 6.5

When i try to place the order - by clicking in "Place order" button - i get this error: "Unable to place order. Please try again later."

Expected is redirect to another controller and open a page with the payment methods (cc, debit, boleto). This works in smaller versions then 2.1.0.

I had a trace in Network:

> # 0 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(1, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
> # 1 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
> # 2 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(1, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
> # 3 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
> # 4 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
> # 5 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> # 6 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 7 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> # 8 /var/www/html/uol-pagseguro-moscou.s2it.com.br/public_html/magento2/2.1.0/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> # 9 {main}

I getting none from debug.log and in the system.log i got main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.

I read before open this issue,  all the other similiar issues. But i can't get a solution.

Ty for now.

**Comment by heldchen** [comment]
running in the same thing right now. I was able to trace it back to the data-migration-tool for now. did you migrate your data from 1.x as well?

**Comment by YevSent** [comment]
@esilvajr, you can use [xdebug](https://xdebug.org/) to find the original reason of this exception.
You need to set breakpoint in [PaymentInformationManagement::savePaymentInformationAndPlaceOrder](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71)

**Comment by heldchen** [comment]
@esilvajr in our case, the creditcard payment extension we're using in magento 2 added its own `entity_type` to `sales_sequence_meta` and `sales_sequence_profile`  for transaction id generation. 

the data-migration-tool cleaned out all non-core entries during migration, leading to the payment extension being unable to generate a next transaction id. the solution for us was to re-add the missing  `sales_sequence_meta` and `sales_sequence_profile` data.

**Comment by esilvajr** [comment]
@heldchen and @joni-jones i just change the PHP version to 7.0.10 and works fine again.
