### ISSUE TITLE
[2.1.0] image upload from products fails with symlinked pub/media/ folder.

### ISSUE THREAD

**Issue by peec** [magento/magento2#6341]
Usecase for symlinked media folder: Scalable hosting using nfs for the media folder. Since the database media storage doesn't work...
### Preconditions
1.  Magento 2.1
2.  PHP 7
3. Mysql 5.6
4. Move pub/media folder `mv pub/media ~/testmedia`
5. Make a symlink from pub/media to ~/testmedia `ln -s ~/testmedia pub/media`
### Steps to reproduce
1. See preconditions
2. Try to go into a product and add an image.
3. You get error: We don't recognize or support this file extension type.

Note that uploading e.g. an image in wysiwyg works with symlinked media folder. But not product images..
### Expected result
1. Allow to upload new product image even if pub/media is a symlink to another location.
### Actual result
1. Popup dialog saying that: `We don't recognize or support this file extension type.`

**Comment by peec** [comment]
Seems to be permission problem.. The error is not correct in frontend, look in chrome console and you see that its a permission error. ( Missleading error message. ) . Closing as this issue no longer true.

**Comment by lauzis** [comment]
Magento 2.2 have same issue with apache and media folder  symlinked to different location...
Any ideas how to resolve that?
[Fri Dec 22 14:07:16.178038 2017] [core:error] [pid 24179] [client 10.0.1.74:50848] AH00037: Symbolic link not allowed or link target not accessible: /xxx/xxx/public_html/shop/pub/media
