### ISSUE TITLE
installing magento2 on mac, not loading anything when browsing to /update/setup

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6345]
### Preconditions
1. php version 5.5.23
### Steps to reproduce
1. install magento2 CE via composer CLI 
2. download the router.php for utilizing PHP built in web server via github, and place it in the root project folder
   ![image](https://cloud.githubusercontent.com/assets/1905150/17980783/b9e6ee9a-6ab5-11e6-8b76-666e45ec9d5e.png)
3. bring up php webserver via

``` shell
php -S 127.0.0.1:8080 router.php
```
1. browse to http://127.0.0.1:8080/update/setup
### Expected result
1.  I've never used this software, but there is a blank web page displayed, it's supposed to click on agreement message here:
   ![image](https://cloud.githubusercontent.com/assets/1905150/17980902/37e20bd6-6ab6-11e6-9d29-584014579f2c.png)
### Actual result
1. 
   ![image](https://cloud.githubusercontent.com/assets/1905150/17980917/4716648a-6ab6-11e6-83a0-bf3566bca837.png)

**Comment by veloraven** [comment]
@BardiaAfshin thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please also note that php 5.5 is not supported by Magento 2.1 and newer versions : http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html

**Comment by PascalBrouwers** [comment]
Looks more like a PHP configuration @BardiaAfshin. I have no problem running Magento 2 on a Mac using Apache. Why would you want to use php's build-in web server?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ghost** [comment]
You can leave the issue as closed, but I wanted to use PHP's built in web server for prototyping purposes. I did end up setting up the full working version on Apache 2.4 via cloning the repo and checkout the release to stable 2.1 version.
