### ISSUE TITLE
Free shipping rule with table shipping method breaks checkout 

### ISSUE THREAD

**Issue by Cacasapo** [magento/magento2#6346]
### Preconditions

1.  Magento 2.08 upgraded to 2.1
2. 
### Steps to reproduce

1. Configure table shipping rate
2. Create attribute and rule for free shipping
3. Assign attribute to product and enable
4. Add product to cart
5. Attempt to check out.
### Expected result

1. Shipping Methods should show the table label and $0 for shipping.
### Actual result

1.  Shipping Methods shows: Sorry, no quotes are available for this order at this time
2. Hairs are pulled out.

PS:
Disabling table and enabling fixed works OK with the above procedure.
Adding a product without free shipping, along with a free ship one, to cart allows checkout to proceed.

**Comment by veloraven** [comment]
@Cacasapo thank you for your report.
Could you please provide more detailed steps? 
1. Does your table rate contain option with price = 0?
2. More detailed description for attribute and rule creation.
3. What do you mean as 'Assign attribute to product and enable'?

**Comment by Cacasapo** [comment]
1 - No, the table is basically fixed, per-unit shipping for US and Canada. I've attached it.
2 - Attribute is a Yes/No named "free shipping"
The rule is: If ALL  of these conditions are TRUE : Free Shipping  is  Yes 
                   Fixed amount discount: 0
                   Free shipping: For matching products only
3 - I mean, add the attribute to the default attribute set, then open a product and set free shipping to Yes.

[tablerates.zip](https://github.com/magento/magento2/files/439242/tablerates.zip)

**Comment by miakusha** [comment]
Hi @Cacasapo , thank you for your report.
Created internal issue MAGETWO-58664 to investigate and track this issue.

**Comment by irenelagno** [comment]
Hi, @Cacasapo, thank you for your report.
This issue appears due to incorrect configuration in the your tablerates.zip.
To have ability to  apply free shipping with table rate. you need to add configuration for weight = 0.
{code}

CAN \*   \*   0   21.99
USA \*   \*   0   11.99
{code}

[tablerates1.zip](https://github.com/magento/magento2/files/482195/tablerates1.zip)
I attached modified csv file. 
Please try adding missing configuration to your tablerates.csv

**Comment by Cacasapo** [comment]
@irenelagno The attached CSV is the same I've uploaded. 

I'm using "# of items vs destination" because this is a per-item shipping fee, so I don't see how weight comes into it. Is this the bug?

**Comment by irenelagno** [comment]
@Cacasapo, Thank you for clarification. I'll try with settings # of items vs destination. Because  I have tried with  _Condition_ = "Weight vs Destination" earlier.

**Comment by sdzhepa** [comment]
@Cacasapo Fix for this issue was delivered to develop branch. Pls feel free to chech it in develop and reopen if need
- Fix for Magento 2.1 will be delivered late in scope of internal ticket `MAGETWO-59248`
- Fix for Magento 2.0 will be delivered late in scope of internal ticket `MAGETWO-59249`
