### ISSUE TITLE
Checkout Validation Message is not fully translatable: "Provided Zip/Postal Code seems to be invalid. Example: 12345-6789; 12345. If you believe it is the right one you can ignore this notice."

### ISSUE THREAD

**Issue by bka** [magento/magento2#6347]
Validation text "_Provided Zip/Postal Code seems to be invalid. Example: 12345-6789; 12345. If you believe it is the right one you can ignore this notice._" in checkout is not fully translatable.
### Preconditions
1. Tested with Magento 2.1
### Steps to reproduce

**1. Install or create a language pack.**

**2. To reproduce this a minimal language pack is sufficient**

_app/i18n/xxx/de_DE/registration.php_

```
<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LANGUAGE,
    'xxx_de_de',
    __DIR__
);
```

_app/i18n/xxx/de_DE/language.xml_

```
<?xml version="1.0"?>
<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/Language/package.xsd">
    <code>de_DE</code>
    <vendor>xxx</vendor>
    <package>de_de</package>
</language>
```

_app/i18n/xxx/de_DE/de_DE.csv_

```
Provided Zip/Postal Code seems to be invalid.,"Angegebene Postleitzahl scheint ungültig zu sein."
"Example:","Beispiel:"
If you believe it is the right one you can ignore this notice.,"Wenn sie richtig eingegeben wurde, können Sie diese Warnung ignorieren."
```

To activate:

```
bin/magento setup:static-content:deploy de_DE
php bin/magento setup:upgrade
```

**3. Change your Locale under `Stores -> Configuration -> General -> Locale Options` to e.g. Germany**
**4. Clear your cache**

```
rm -rf Source/var/generation/*
rm -rf Source/var/di/*
rm -rf Source/var/cache/*
rm -rf Source/var/view_preprocessed/*
rm -rf Source/pub/static/_requirejs
rm -rf Source/pub/static/adminhtml
rm -rf Source/pub/static/frontend
```

**5. go to checkout**
**6. type something into Zip/Postal Code**
### Expected result
1. Displayed message is: "_Angegebene Postleitzahl scheint ungültig zu sein. Beispiel:12345. Wenn sie richtig eingegeben wurde, können Sie diese Warnung ignorieren._"
### Actual result
1. Displayed message is: "_Angegebene Postleitzahl scheint ungültig zu sein. Example: 12345. Wenn sie richtig eingegeben wurde, können Sie diese Warnung ignorieren._" 
   (_Note_: _Example_ is not beeing translated)

![auswahl_007](https://cloud.githubusercontent.com/assets/584644/17981463/24736d58-6b04-11e6-8354-d75d3e266d7b.png)
### Additional information

Translation for "_Example:_" is missing in js file:

```
$ cat pub/static/frontend/Magento/luma/de_DE/js-translation.json
{"Provided Zip\/Postal Code seems to be invalid.":"Angegebene Postleitzahl scheint ung\u00fcltig zu sein.","If you believe it is the right one you can ignore this notice.":"Wenn sie richtig eingegeben wurde, k\u00f6nnen Sie diese Warnung ignorieren."}%
```

**Comment by heldchen** [comment]
your de_DE csv example seems to be lacking the whitespace, have you tried `"Example: ","Beispiel: "`?

**Comment by bka** [comment]
You're right, but I think this is not the problem. Because warn message is translated with a leading whitespace `$t(' Example: ')` in `app/code/Magento/Checkout/view/frontend/web/js/model/shipping-rates-validator.js`. But thanks for the hint, I will test again.

**Comment by heldchen** [comment]
right, so test with `" Example: "," Beispiel: "`, that should work. I've checked to make sure that it's how it is used in some of the language bundles we downloaded for our project (example: https://github.com/Imaginaerum/magento2-language-fr-fr). the source strings to be translated through csv have to match exactly what's used in the code.

**Comment by bka** [comment]
Thanks man. That works. However, pretty inconvenient IMHO.

**Comment by heldchen** [comment]
why?

**Comment by sevos1984** [comment]
Is this issue resolved?

**Comment by bka** [comment]
Yes, resolved, thanks
