### ISSUE TITLE
Base folder under some module views folder

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#635]
What is with the base folder under some of the view folders for modules? As far as I can see, according to the documents at https://wiki.magento.com/display/MAGE2DOC/Magento+2+Product+Documentation the folders under view are normally the areas: adminhtml, frontend etc.

I would suggest if these folder can be areas and other items like themse etc that this could cause some confusion.

An example of this is `Mage\Bundle\view\base` here there are layout and template files

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28241

**Comment by piotrekkaminski** [comment]
This is currently not a priority but asked architects for evaluation.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Base-folder-under-some-module-views-folder/idi-p/47016).
