### ISSUE TITLE
Cart rules for products which are not visible on store front

### ISSUE THREAD

**Issue by devhn** [magento/magento2#6352]
### Preconditions

1. Magento 2.0.7 CE
### Steps to reproduce

1. Create a configurable product of choice with at least two simple 
   products inside it (which are not visible on store front)
2. Create a simple product of choice, which is visible on store front
3. Create a cart rule which contains setup from [print screens](http://imgur.com/a/W6ByX). Basically the condition has two statements:
   
   **Condition**: If a product is found from category X and has one of the following attributes && If a product is found from category Y and has one of the following attributes
   **Action**: Apply a defined discount amount to product from category Y
### Expected result

1. When in cart an item from category X with any of specified attributes is 
   found along with a product from category Y with any of specified attributes, then a product from 
   category Y should receive defined discount amount.
### Actual result

1. The discount does not get applied. Instead regular prices are being 
   shown. If we adjust the rule only on categoriy and without attribute 
   scope, then the discount of the rule applies. The rule also applies if 
   we change the simple products within the configurable products to 
   visible on store front.

We are not sure if this is a bug or administrative misconfiguration, but it seems that cart rules are applied only to products which are visible on store front.

**Comment by dthampy** [comment]
internal jira ticket ->MAGETWO-58130 created for this issue.

**Comment by duffner** [comment]
What is the status of this ticket?

**Comment by magento-engcom-team** [comment]
@devhn, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
