### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by shaheerzaheer** [magento/magento2#6353]
The home page is ok but in admin panel all the content is messed up and I can't do anythings the page looks like I attached below , even the links are not working so how can I manage things kindly guide me about this issue.
![issue1](https://cloud.githubusercontent.com/assets/21260888/18004335/13a624e0-6b48-11e6-9e0c-4be08dd31a13.PNG)
![issue2](https://cloud.githubusercontent.com/assets/21260888/18004343/20860bbc-6b48-11e6-8877-c9f377e45e12.PNG)

**Comment by jamesjlw** [comment]
Having a similar issue. Fresh install 2.1.0, seems that pub/static is missing quite a few files - My front end is also missing images, stylesheets etc.

**Edit**. I managed to fix it by following the steps of the accepted answer here:
**It was a fresh install so I had nothing to lose.** - I'm brand new when it comes to Magento so I'm not sure if this will remove any of your custom files.

http://magento.stackexchange.com/questions/95991/local-installation-of-magento-2-doest-not-generate-files-in-the-pub-static-folde

It didn't work the first time around but after closely following the steps again, everything seems to be perfect.

**Comment by veloraven** [comment]
@shaheerzaheer thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version and information if it was clear install or upgrade.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
