### ISSUE TITLE
Catalog attribute filters have disappeared

### ISSUE THREAD

**Issue by arredod** [magento/magento2#6355]
### Preconditions
1.  Magento 2.1.0 (upgraded from magento 2.0.7 and before the first release of magento 2)
### Steps to reproduce

1. product catalog column filters have disappeared and I can't tell if it's because something is broken or it's a Magento bug
### Expected result
1.  I would like to hide assembling column but I can't do that anymore...
### Actual result
1.  ![product](https://cloud.githubusercontent.com/assets/19904060/18004863/ea0e5748-6b96-11e6-9cd4-ff9a21761feb.jpg)

**Comment by veloraven** [comment]
@arredod thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also specify if it was clear install or upgrade from some previous version.

**Comment by hayabusajerry** [comment]
Was a Solution found for this as my search and filters are missing too.

**Comment by Sergeacc** [comment]
Unfortunately, I could not reproduce the issue as you described it.
Please, upgrade Magento and check this issue on the latest Magento 2.1.x version.
