### ISSUE TITLE
Wrong Varnish Cache Settings are killing Burger Menu

### ISSUE THREAD

**Issue by bka** [magento/magento2#6357]
When using Varnish as a Full Page Cache and your connection settings are wrong, the burger menu stops working. I don't understand this behavior at all, because everything else is working fine. It happend because we imported a database dump from production to our local dev machines. It was very confusing and hard to track down but I don't understand the reason for this at all. Does somebody have a reasonable explanation for this?
### Preconditions
1. Tested on Magento 2.1
### Steps to reproduce
1. Activate Varnish Cache under `Stores -> Configuration -> System -> Full Page Cache`
2. Set a random IP .e.g `12.13.14.15`
3. Flush Cache
4. Navigate to storefront

![auswahl_040](https://cloud.githubusercontent.com/assets/584644/18007868/0a76acf6-6ba6-11e6-841b-912ea6747919.png)
### Expected result
1. Burger Menu for mobile theme is clickable
### Actual result
1. Burger Menu for mobile theme is not working anymore

![auswahl_039](https://cloud.githubusercontent.com/assets/584644/18007910/3748f0ea-6ba6-11e6-85dd-cd1be1baa91a.png)

**Comment by boldhedgehog** [comment]
@bka This form's purpose is to generate a configuration file for Varnish, those fields are not the actual Varnish configuration for Magento. As far as I know, the only way to configure Varnish connection is to add the configuration to `etc/env.php` file like this:

``` php
'http_cache_hosts' =>
  array (
    0 =>
    array (
      'host' => 'varnish', // Varnish instance address
      'port' => '6081',
    ),
  ),
```

**Comment by bka** [comment]
@boldhedgehog Thanks, I'm aware of this and thats why I'm wondering why this setting seems to have influence on the burger menu - it just doesn't expand anymore. Did not have time to dive deeper into this.

**Comment by bka** [comment]
I understand this problem a little better now. Chaning _Full Page Cache_ to Varnish instructs to Magento to replace some blocks with ESI tags. Because the Topmenu block is declared with ttl like this:

```
<block class="Magento\Theme\Block\Html\Topmenu" name="catalog.topnav" template="html/topmenu.phtml" ttl="3600" before="-"/>
```

it is replaced by an ESI tag. The `data-mage-init` block for the menu is inside this template making the burger menu not working anymore. 

![auswahl_008](https://cloud.githubusercontent.com/assets/584644/18131613/d06b1aaa-6f93-11e6-85df-6bbd3e2008b8.png)
![auswahl_010](https://cloud.githubusercontent.com/assets/584644/18131626/d614bf56-6f93-11e6-9c61-a6bb99360fda.png)
![auswahl_009](https://cloud.githubusercontent.com/assets/584644/18131624/d3941ea2-6f93-11e6-99e8-a9e8bcd24228.png)

Not really a bug. Makes sense and it only happend because we imported a database dump from production. Would be nice to have some warning in developer mode to prevent me doing this mistake again ;)

**Comment by benheart** [comment]
@bka Hi bka, I had the same problem as you mention above. And I solved the problem by remove ttl="3600", but I also noticed that in the pure Magento2.1.5, ttl="3600" is still exist in the file: vendor/magento/module-theme/view/frontend/layout/default.xml. So I don't understand why "it only happend because we imported a database dump from production." as you wrote above.
