### ISSUE TITLE
Magento 2 improvements from uservoice

### ISSUE THREAD

**Issue by seansan** [magento/magento2#6358]
Hi guys, now that the basis has been built. Bravo!

Would it be an idea to check all of the items here with votes? https://magento.uservoice.com/forums/24441-magento-ecommerce-platform

I can see thousands and thousands of users have contributed. And many things seem easy, logic and can be improved on fast. 

maybe a mini hackathon with the Magento internal team?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
