### ISSUE TITLE
We can't find products matching the selection- after upgrading from 2.0.7 to 2.1.0

### ISSUE THREAD

**Issue by daschenbrener** [magento/magento2#6359]
Preconditions

Php 7.0.6
Mariadb 10.1.14
Ubuntu 16.04
### Steps to reproduce
1. performed a migration from 1.9.2.2 to 2.0.7
2. we performed then an upgrade from 2.0.7 to 2.1.0 using composer
3. at that point we had offset error issues while trying to access orders, products, and the catalog,in the backend. we resolved those.
4. In the front end, we have this error. and not products at all are being displayed.

> We can't find products matching the selection.
### Expected result
1. products and catalog should be able to be displayed on front end.
### Actual result
1. the error message
   > We can't find products matching the selection.

as well as this in the debug log

> [2016-08-26 16:25:40] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://oursiteurl/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
> [2016-08-26 16:25:45] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://oursiteurl","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []

we have tried to reindex.
changed the status in the database on this index to invalid to force a reindex (so we think), but no difference.

**Comment by veloraven** [comment]
@daschenbrener thank you for your report.
Did you check if it worked on ver. 2.0.7 after migration? 
Do you have multi-store instance?

**Comment by daschenbrener** [comment]
Yes it did work. 
yes there are multi stores views

**Comment by rbncha** [comment]
I have the same issue. None of these show any products: category pages, new arrivals, featured, most popular/viewed.

It happened after I upgraded from 2.0.7 to 2.1.1.

**Edited**
One more thing,

The Admin > Product > Categories page giving this error
`a:4:{i:0;s:137:"Notice: Undefined offset: 186 in /home/exampledomain/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:6758:"#0 /home/exampledomain/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/home/suitsandm...', 166, Array)`

**Comment by TommyKolkman** [comment]
I can second this. Upgraded from 2.0.8 to 2.1.0 though.

**Comment by shiftedreality** [comment]
Hi @daschenbrener 

Thank you for your report.
This issue internally tracked and will be fixed with https://github.com/magento/magento2/issues/5222
Closed as duplicate.
