### ISSUE TITLE
magneto2 performance testing issue.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#6361]
We have tried magento performance testing on new created instance then it works.

but on instance who already has orders then it throw errors.

We have used command on application root.
 php bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/small.xml

and this happen : 
![image](https://cloud.githubusercontent.com/assets/6079017/18013545/2662e3b8-6bdc-11e6-99a8-f5a871659300.png)

Please let me know why this duplicate integrity error occur. If we need to do performance testing on existing instance then it will not work why???

**Comment by IvanChepurnyi** [comment]
Please refer to the official documentation page:
http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-perf-data.html#config-cli-perf-prof

This tool always generates some test orders, customers, stores, etc for profiling. So if you don't use clean Magento installation, you will definitely get errors during data generation.

You cannot use this data generator on existing store databases, you better extend it with custom generators. As well it may lead to unexpected results if it just overrides your existing data.

**Comment by ankursachdeva11** [comment]
If we need to test the performance only for creating order with load on working instance which have order. So, what do we do now.
Please let us know.

**Comment by choukalos** [comment]
Hello @ankursachdeva11 - you'd need to customize the benchmark.jmx script.  I'd guess you'd want to use your existing products & categories, but likely create a set of test customers for load testing.

**Comment by ankursachdeva11** [comment]
Hi @choukalos,

My concern is only for order creation because when i run performance script via command line then only this throw error for primary key.

Can you please let me know where i need to change in benchmark.jmx to create order on existing instance which is already having test order or anything so that i do not need to clean magento installation every time to run performance script.

Also i need this testing should start from further. If it has created 80 orders then it start from 81. If it has created 20 categories then it start from 21.

**Comment by choukalos** [comment]
At the top of the JMX file there's a slew of variables defined which tell the benchmark what flows to run.  You can see the equivalent if using the JMX Gui/window.  I believe you can edit those values to just get it to do the order flows.

As far as changing behavior you can search for the flow and it's appropriate test class.  We've made it modular so likely there are several test classes you'll need to change.  You can just change the appropriate classes to change the behavior to start at a higher # or something like that.  

That's about the limit of my knowledge.  I find it's usually easier to dig in via the GUI and edit that way and experiment with the results I get.  That way you can use the ?threaded pane? on the left to find the setup scenarios and the test execution scenarios.  From that pain it's pretty easy to enable/disable and dig into what the test scenario is trying to do to.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
