### ISSUE TITLE
Concurrent checkouts can lead to negative stock

### ISSUE THREAD

**Issue by TWarszawski** [magento/magento2#6363]
### Description:

When two customers check out concurrently for the same product and the total quantity being ordered is greater than the quantity available, the stock can become negative.
### Preconditions
1. Ubuntu 14.04
2. Xampp 5.6.19
3. Magento CE 2.1.0 with sample data.
### Steps to reproduce

1. Start site, create two customers, create/pick test product and allocate some stock.
2. Both customers add the product to their carts such that each cart individually is under (and not equal to) the available stock, but combined they exceed the available stock.
3. Perform a checkout concurrently, making sure both customers finish checkout (click the 'Place Order’ button) as close to the same time as possible.

We have reproduced this behavior on a single machine, by performing the above steps by simulating one customer in one browser window and another customer in a second browser window.
### Expected result

1. One of the two checkouts fails to complete.
### Actual result

1. Both checkouts succeed and the quantity for the product is negative in the admin console.

**Comment by galillei** [comment]
Does any one have solution? We set one product to sale and after that we have quantity of product=-14. We use 18 instances of frontend;

**Comment by Drnutsu** [comment]
anyone have the solution for this issue? I think its critical issues.

**Comment by feronera** [comment]
me too with CE 2.1.5 - 2.1.7

**Comment by veloraven** [comment]
Internal ticket was created for this issue - MAGETWO-69701

**Comment by galillei** [comment]
This solution https://belvg.com/blog/magento-2-oversell-fix.html are working for us

**Comment by magento-engcom-team** [comment]
@TWarszawski, thank you for your report.
We've created internal ticket(s) MAGETWO-69701 to track progress on the issue.

**Comment by bordeo** [comment]
The bug still exists in 2.1.9

**Comment by bordeo** [comment]
Any update on this?

**Comment by sidolov** [comment]
Hi @TWarszawski , current issue was fixed in 2.2-develop branch (commit: f726dacecc92e76d79f1b6319e7813633375cc89)
