### ISSUE TITLE
what's the big difference between the current dev branch and the 2.1 release branch?

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6368]
hi there, I've started building out a store from a clone of the most recent dev branch. what's the biggest feature releases? Also, I notice the current release branch is failing.

**Comment by choukalos** [comment]
Hello @BardiaAfshin 

Dev branch is for development (aka our next release) and should not be considered stable.  I'd recommend that you use the last stable branch (as of this time 2.1) for building out a store.

Please use the dev branch if you want to follow along with changes to the upcoming release, provide feedback, or provide PR's to improve the product.

Thanks!
Chuck

**Comment by ghost** [comment]
I've noticed when I checkout to the release branch 2.1, the head becomes detached. I haven't seen this on other projects I've worked on. That's how I went about it, the installation instructions don't talk about any of this.
