### ISSUE TITLE
magento 2.1

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6369]
ran ./bin/magento run:cron from the command line, still getting the message on the admin panel the indexes are not valid and such.

**Comment by TiEul** [comment]
You need to run `bin/magento indexer:reindex`.

**Comment by veloraven** [comment]
@BardiaAfshin thank you for your feedback.
You can find instruction how to [Configure and Run Cron](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html) here. If you do not want to set up your cron and want to run it manually you have to run _./bin/magento cron:run_ in command line, but you have to do it twice: first time a task to be scheduled and second time to be executed.
Please next time, format issues according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ghost** [comment]
I''ll make it feature request, to append the --re-index for convenience purposes to ./bin/magento cron method

something like this

``` shell
./bin/magento cron:run --re-index
```
