### ISSUE TITLE
Grouped configurable products with one attribute set

### ISSUE THREAD

**Issue by seansan** [magento/magento2#637]
Request for the ability. That when you have a grouped or bundle of products based on configurable products and when the simple product attribute identifier is the same: that you only have to choose it once

So. When you buy a bundle of tshirts. (Where tshirt is configurable product. And per size is simple) that you only have to select the size drop down once - and this counts for all the configurable products in the bundle or group

http://magento.stackexchange.com/questions/5002/multiple-configurable-products-as-a-bundle

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-27714

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Grouped-configurable-products-with-one-attribute-set/idi-p/46215).

**Comment by seansan** [comment]
It was acknowledged ... and I dont believe in a FORUM being the proces and
method to store important feedback and sometimes even code suggestions ...
it will get lost, forgotten - the forum will be killed in 2018 or 2019 just
like the previous one. I never understood why one did not open a simple
uservoice account or JIRA account and log it there.
