### ISSUE TITLE
Undefined index: name in System Upgrade

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6372]
### Preconditions

1. Magento 2.1
### Steps to reproduce

1. Enter Web Setup Wizard
2. Select System Upgrade
### Expected result

1. System Upgrade 😄 
### Actual result

1. Error message 'Undefined index: name' from request to 'setup/index.php/select-version/systemPackage'

**Comment by NadiyaS** [comment]
Hi @rbostan ,
we can not reproduce this bug, please provide us more details which can affect this bug: do you have external extensions, in which way you install magento (git, composer), etc?

**Comment by filipac** [comment]
I have the same error too. I installed and upgraded to 2.1 via composer. Now i get this error.

**Comment by cizgidekiadam** [comment]
It was a composer installation (2.1)
Trying to system upgrade, not modules.

I think i told story detailed.

**Comment by shiftedreality** [comment]
Hi @rbostan 

I was also unable to reproduce this issue on 2.1.0 and 2.1.1
Please, clean your browser cache and try again.

If problem still exists: provide next details:
- PHP version
- OS version
- Apache/nginx
- Caching

**Comment by cizgidekiadam** [comment]
It'is running on Centos 6.5 with;
- PHP 5.6.14
- Apache
- Standart Magento cache, not more.

Now using 2.1.1 and had to update via composer. Can not use backend's System Upgrade

http://prntscr.com/clupk0 - After clicking System Upgrade
http://prntscr.com/clupp5 - Result with error

**Comment by rliukshyn** [comment]
Hi @rbostan ,
Unfortunately i could not reproduce this issue on specified environment.

**Comment by mirmanov** [comment]
I have the exact same issue with Magento 2.0.0.
The environment:
- Ubuntu 14.04.3
- PHP 5.6.17
- Apache

**Comment by djlspeed** [comment]
Which repositories are listed in your composer.json?
Removing all except https://repo.magento.com/ fixed the problem for me.
So my composer.json looks like this:
`...
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
    }
    ],
...
`

**Comment by tabstop** [comment]
I have the same problem, but my error is only:

> Step 1: Select Version
> Undefined index: name 

Magento 2.1, no composer setup
Ubuntu16.04
php-fpm: 7.0.8-0ubuntu0.16.04.3
Apache 2.4.18
caching off

**Comment by djlspeed** [comment]
As mentioned above, I had the same problem.
Removing all repositories (with the exception of repo.magento.com) from the composer.json, proceeding to the next step and reentering the repositories again (as otherwise the readiness check would fail with composer errors) did the trick for me.
Did you try this?

**Comment by trifectavape** [comment]
as guys mentioned, edited composer.json and in repositories i had data-migration-tool which installed during migrating my old to new magento sites, i deleted the lines for it and worked perfectly,
Thanks a lot for providing the solution

**Comment by oshmyheliuk** [comment]
@rbostan Does your problem was resolved by the solution that described above?
Can we close this issue?

**Comment by cizgidekiadam** [comment]
Thanks a lot folks.
 There was an extra repository, remove it, now it says 'You're already using the latest version, there's nothing for us to do.'

You may close it, thanks.
