### ISSUE TITLE
Magento EE 2.1 : Grid in admin, data loaded but loading spinner animation overlay still displayed

### ISSUE THREAD

**Issue by enrico69** [magento/magento2#6374]
### Preconditions
1. **OS** of the server: Debian (Virtualized, with 3GB of memory)
2. **OS of the client**: Windows 7
3. *\* Browser of the client**: Chrome Version 52.0.2743.116 m (64-bit). Also tried with Firefox 44.0.2
4. **MySQL:** Ver 14.14 Distrib 5.6.31
5. **PHP:** PHP 7.0.8-1~dotdeb+8.1 (cli) ( NTS )
### Steps to reproduce
1.  Create a grid in the back office of the application, in order to list elements of custom tables
### Expected result
1. Data should be listed, with filter and actions on the entries.
### Actual result
1. I repoduced the same steps for three differents entities. For the two first ones, with respectively 37 and 106 results, everything works fine. But for the third one, with more than 38,000 results, the data are displayed but the the loading animation is still here. Pagination has been setup. Note that if I manually deleted the loading overlay, the related actions (e.g pagination) work.

![p6laz](https://cloud.githubusercontent.com/assets/6852249/18044619/09b4ed3e-6dcf-11e6-8936-0c6247e46bcd.png)

**Comment by TomashKhamlai** [comment]
@enrico69 if this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by enrico69** [comment]
I don't think it is especially related to the EE...

By then I tried and faced the same problem with the CE: the only workaround I found was to reduce the number of attribute displayed in the grid. 

I never tried again since (10 months ago).

**Comment by magento-engcom-team** [comment]
@enrico69, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
