### ISSUE TITLE
Simple bundled products for inventory

### ISSUE THREAD

**Issue by seansan** [magento/magento2#638]
May we request support for fixed bundles?

Eg you sell cuff links. All types have inventory. And are available as a simple product. 

Now we sell bundles of 3 types together. A new fixed price. And user cannot choose how many of the sub items. That is fixed. 

So you buy the bundle for the bundle price. And the underlying simple products qty is adjusted accordingly for stock. 

 

 

A little along the lines of this
http://stackoverflow.com/questions/7890908/grouped-product-with-fixed-sub-item-quantities

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-27715

**Comment by tanya-soroka** [comment]
Hello @seansan 
Please can you confirm that the following solution is covered you use-cases.
Magento 2 supports ability to create a bundle product with the fixed price for whole set of the sub-products. Also as part of the bunle options Magento has  "User Defined" checkbox option. It provides ability to disallow customer to specify the QTY of the sub-products and only merchant has ability to provide a default QTY value.

Thank you

**Comment by seansan** [comment]
This is indeed an improvement (I know people want that to)

The solution is more in this area: you set QTY per bundle product (there is
no option for selecting QTY *per* subproduct)

So imagine we have these 4 products
product 1 = 9 $ = you can buy per product
product 2 = 9 $ = you can buy per product
product 3 = 9 $ = you can buy per product

product 4 (set of 1,2,3) = 25 $ = you can buy just like a product - so
there is only *1* QTY selector, BUT! when a sale is made in the backend
product QTY for all products 1, 2 and 3 are deducted (so product 4 is a
virtual product not having own qty) + a user can not select the QTY for
individual items 1, 2 and 3 - and actually should not even see it

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Simple-bundled-products-for-inventory/idi-p/47010).

**Comment by springimport** [comment]
@ilol @vpelipenko Don't see any changes in 2.3-develop. Which commit is associated with this issue?

**Comment by Ctucker9233** [comment]
@ilol @vpelipenko @magento-engcom-team Any chance a backport for 2.2 can be created for this? It's a great feature that we would definitely use.

**Comment by ccrothers** [comment]
This feature is part of this extension, but really should be native. Especially considering it is a minimal subset of what bundles are already capable of.
https://ecommerce.aheadworks.com/magento-2-extensions/simple-bundle-product

@ilol @vpelipenko , Also wondering about @springimport 's comment "Which commit is associated with this issue?"... I don't see one that addresses this.

**Comment by seansan** [comment]
Also interested In confirmation

Will it also cover the case where one has only 1 subproduct only the qty differs?

So the simple is 1 cufflink and the bundle is a package of 3 of these cuff links 

So In this case the simple product can have multiple parents. And exist for example in 1 configurable parent being the normal product. A bundle of this configurable (as a pack) of three times the qty. and say a third product with the same only this time a bundle (or pack) of six of the same cuff links as one product.

**Comment by ccrothers** [comment]
Sounds like a question for aheadworks. Haven't tried the extension personally.
