### ISSUE TITLE
Magento EE 2.1 : Product is not saved

### ISSUE THREAD

**Issue by enrico69** [magento/magento2#6381]
### Preconditions

OS of the server: Debian (Virtualized, with 3GB of memory)
OS of the client: Windows 7
*\* Browser of the client**: Chrome Version 52.0.2743.116 m (64-bit). Also tried with Firefox 44.0.2
MySQL: Ver 14.14 Distrib 5.6.31
PHP: PHP 7.0.8-1~dotdeb+8.1 (cli) ( NTS )
### Steps to reproduce
1. In the back end: create a product.
2. Save or Save and close
### Expected result

1. The product should be saved.
### Actual result
1. The product is not saved. No error is displayed

Log: 

`PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/montageEric/mybusiness/mybusiness/vendor/magento/module-admin-gws/Model/Models.php:865`

**Comment by veloraven** [comment]
@enrico69 thank you for your report.
Please provide some more information: was it clear install or upgrade from previous version?
What type of product do you create?

**Comment by enrico69** [comment]
Emptied var/, pub/static, restarted my environment, the problem doesn't occur anymore.
