### ISSUE TITLE
module shows up via module:status but error on module:enable

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6383]
when you run

``` shell
composer require bardiamodule/product-attribute
```

it installs the module , and it shows up under the vendor directory. When I run

``` shell
± |develop ✗| → ./bin/magento module:status
List of enabled modules:
BardiaModule_ProductAttribute
Magento_AdminNotification
Magento_AdvancedPricingImportExport
...
```

it shows the module, at the very top of the list,
but when I run ./bin/module enable:BardiaModule_ProductAttribute I get

``` shell
± |develop ✗| → ./bin/magento module:enable BardiaModule_ProductAttribute
Unknown module(s): 'BardiaModule_ProductAttribute'
```

I get unknown module error, hmm.

**Comment by veloraven** [comment]
@BardiaAfshin thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also specify the used Magento version.

**Comment by BaDos** [comment]
Hi @BardiaAfshin 

Did you run `./bin/magento setup:upgrade` after you had run `composer require bardiamodule/product-attribute`?

**Comment by ghost** [comment]
I honestly don't recall. I believe I tried the upgrade route initially when I was installing the project via the alternative composer install.

**Comment by BaDos** [comment]
@BardiaAfshin 
Could you try to reproduce this issue once again?
What version of Magento are you using?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
