### ISSUE TITLE
Magento 2.1 CE: Unable to Checkout via Paypal Express if Loggedin due to error 404 on API call to /carts/mine/selected-payment-method

### ISSUE THREAD

**Issue by frostshoxx** [magento/magento2#6386]
Hello, 
I'm having some issue making a payment via Paypal Express checkout. If I were to place an order and select the payment while not logged in, it will make a call to /guest-carts/:cartId/set-payment-information and successfully send me to Paypal website. However, if I logged in, it will use the API /carts/mine/selected-payment-method instead, which will throw error 404.

I traced back to the code that is responsible to set up payment method (/vendor/magento/module-paypal/view/frontend/web/js/action/set-payment-method.js) Looks like the logged in and the not logged in are using two separate API calls. Is that normal? Is there something wrong with my Magento or is that /carts/mine/selected-payment-method is obsolete? I was able to call /carts/mine and have it returns my shopping cart just fine.
### Preconditions

1. Magento version 2.1
### Steps to reproduce

1.  Add product to a shopping cart.
2. View the cart.
3.  Proceed to check out.
4. Select Paypal Express Check (already configured properly with Sandbox account) and click "Continue to Paypal"
### Expected result

1. It should send me PayPal website to sign in and make the payment
### Actual result

1.  Stuck on the check out page. The console shows error 404 for not able to make a call to /carts/mine/selected-payment-method. 

[Screenshot, logs]

**Comment by frostshoxx** [comment]
Ok I figured it out.. According to http://devdocs.magento.com/guides/v2.0/rest/list.html, looks like selected-payment-method no longer exist. Instead it hast o be POST   /V1/carts/mine/set-payment-information.

So on /vendor/magento/module-paypal/view/frontend/web/js/action/set-payment-method.js

Change from 

```
     } else {
                serviceUrl = urlBuilder.createUrl('/carts/mine/selected-payment-method', {});
                payload = {
                    cartId: quote.getQuoteId(),
                    method: paymentData
                };
            }
```

to

```
} else {
                serviceUrl = urlBuilder.createUrl('/carts/mine/set-payment-information', {});
                payload = {
                    cartId: quote.getQuoteId(),
                    paymentMethod: paymentData
                };
                method = 'post';
            }
```

**Comment by frostshoxx** [comment]
Link to pull request https://github.com/magento/magento2/pull/6389

**Comment by abdulaziza1981** [comment]
It worked, Thanks
