### ISSUE TITLE
URL key of product doesn't change

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#6391]
### Preconditions

1.  Magento 2.0.9
2. Apache Rewrite is on
### Steps to reproduce

1. Open products > catalog > product > Search Engine Optimization
2. I change the URL Key
3. Delete all cache in Magento Admin, and try all of this

```
./bin/magento setup:di:compile
./bin/magento setup:static-content:deploy
./bin/magento cache:clean
./bin/magento cache:flush
./bin/magento indexer:reindex
```
### Expected result

1.  Product URL should change like URL key
### Actual result

1. There is still the old URL Key in use. The new one doesn't work

**Comment by JacobDrummond** [comment]
I had the same problem in single-store mode: #5929.

The solution was to change to multi-store, then batch-save all the products.

**Comment by flipflap** [comment]
Thanks JacobDrummond, but it doesn't help in my case. Enable Single Store Mode is already No in my Magento.

**Comment by xmav** [comment]
@flipflap 

We've created internal ticket MAGETWO-58387 to address this issue.

Thanks,
Maksym

**Comment by flipflap** [comment]
Ok thanks, do I get feedback here if you have a solution for that?

**Comment by xmav** [comment]
this ticket will be closed as soon as we fix issue.

**Comment by miakusha** [comment]
@flipflap this issue present only in 2.0.x versions. You can try update to 2.1.1 and problem will be solved

**Comment by twistedindustries** [comment]
Has this been fixed?  I can't use 2.1 because of issues with authorize.net.  This is still happening and shouldn't have been closed.

**Comment by flipflap** [comment]
As miakusha said, it should be fixed. But I couldn't test it yet.

**Comment by twistedindustries** [comment]
2.0.6 Issue still exists.

**Comment by shahankitb997** [comment]
Even in 2.1.7 still exists.
