### ISSUE TITLE
Description part comes on above header

### ISSUE THREAD

**Issue by shownak** [magento/magento2#6395]
![selection_002](https://cloud.githubusercontent.com/assets/18438612/18086686/b8d319e4-6ece-11e6-827a-eb0adbb2fb1a.png)
check this.. i am using magento 2.0.0
When i add product manually from admin panel, then the description part also comes on top as shown in screenshot
![selection_003](https://cloud.githubusercontent.com/assets/18438612/18086767/2b526fba-6ecf-11e6-87e4-1f99d8ed0645.png)
and when i change the text of description from admin panel
the upper text remains the one which i entered originally
when i add product through .csv then there is no issue

**Comment by veloraven** [comment]
@shownak thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
