### ISSUE TITLE
Cart Price Rules: Category selection UI for Conditions do not come up.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6396]
M2.1.0
Cart Price Rules: Category selection UI for Conditions do not come up.

Issue
Category selection UI under Conditions does not come up if a rule needs to be edited. The UI will come up only for 1st time. If the rule is saved, and is revisited for editing, the Category selection tree UI wont show up.

Steps:
- Go to marketing > cart price rules. 
- Create a rule, with few categories selected under Conditions.
- Save... come out.
- Go back and edit the rule. Go to to edit the categories.

The categories UI does not pop up again. Clicking on the button does not do anything.

Workaround: Remove all the categories id and the button might work again.

Expected: The category selection UI should properly come up every time the rule is edited. 

Ver: M2.1.0

**Comment by veloraven** [comment]
@apurv-anand thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by apurv-anand** [comment]
The requested steps are provided. Please update and accept the bug.

**Comment by sevos1984** [comment]
This was fixed in https://github.com/magento/magento2/commit/17788dc3e546ef653c0aaca8b1310a45e37f02c7, ensure you have this code and also refresh your static files as well as browser cache.

**Comment by apurv-anand** [comment]
This is NOT fixed in 2.1.1. The same behavior is now seen under Actions category selection as well.

**Comment by Ctucker9233** [comment]
Seems to be fixed in 2.1.1 for me.

**Comment by RomanKrut** [comment]
@apurv-anand Unfortunately, I could not reproduce the issue as you described it. Can you reproduce this issue on latest version of Magento2?

**Comment by koenner01** [comment]
2.1.7 still contains this bug; @apurv-anand fix you are describing is present in 2.1.7 and not working.

Steps to reproduce:

- Create price rule with condition 'category is one of ...'
- Save the rule
- Re-open the rule and try to change the category id value

**Comment by RomanKrut** [comment]
@koenner01 Thank you for your comment, Internal ticket was created MAGETWO-70129.

**Comment by koenner01** [comment]
The problem seems to be a javascript problem, if I check an unchecked value on an existing condition I get:

```
Uncaught ReferenceError: catalog_rule_form is not defined
    at Ext.tree.TreePanel.Enhanced.eval (eval at <anonymous> (legacy-build.min.js:1), <anonymous>:156:9)
    at Ext.util.Event.fire (ext-tree.js:29)
    at Ext.tree.TreePanel.Enhanced.fireEvent (ext-tree.js:29)
    at Ext.tree.CheckboxNodeUI.check (ext-tree-checkbox.js:193)
    at El.Flyweight.<anonymous> (ext-tree.js:9)
    at HTMLInputElement.h (ext-tree.js:33)
    at HTMLInputElement.M (legacy-build.min.js:8)
```

**Comment by koenner01** [comment]
Commits on [MAGETWO-43350](https://github.com/magento/magento2/search?utf8=%E2%9C%93&q=+MAGETWO-43350&type=Commits) might have a potential fix (haven't tried it yet)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70345
