### ISSUE TITLE
log files size constantly increasing even in clean install

### ISSUE THREAD

**Issue by deepanshu27193** [magento/magento2#6399]
### Preconditions

1. Magneto 2.1 with sample data
2. Ubuntu LAMP
### Steps to reproduce

1. Extracted downloaded zip file
2. setup successfully completed and switched to productionn mode by command line.
3. just go through the website samples provided
### Actual result

1. Log file size increasing constantly even to size of 4 MB of debug.log in last 3-4 days.
2. i dont even install any module or theme in it, but still it is annoying in production environment.

My problem is that it is taking my IOPS limit of aws server.

**Comment by choukalos** [comment]
Hi @deepanshu27193,

Cron runs every minute and I believe logs it's output.  Is this really a bug or perhaps an ask to provide slimmer logging for cron in production?  My concern here is that slimmer logging would make it impossible to detect/track down issues if something isn't working right.  Can you provide additional insight as to why you don't want logs to grow by ~ 1M/day and what you're doing with this install so we can better understand the context of this request?

For a production store we're following PSR standards so you can do all sorts of stuff to pipeline the logs to various logging tools and not have to worry about logs on the server.  Some options for logs would be to update your crontab to send them to /dev/null if you don't want any logs.  Alternatively you could configure logrotate [Magento install docs](http://devdocs.magento.com/guides/v2.1/install-gde/install/post-install-config.html#post-install-server) to not keep logs around for very long if you wanted a short period of time to check them out.  The later one won't do much for IOPS limits but would give you a detect/debug window if there was an issue.

CC'ing @piotrekkaminski to the thread.

Thanks,
Chuck

**Comment by stamster** [comment]
The thing is, those logs are full of errors such as 'broken reference' etc. I don't have an example at hand, tomorrow I'll post more. And that is really bad, to have log full of 'broken' stuff even on a clean install - that means lot's of basic bugs are still left unresolved. :100:

**Comment by deepanshu27193** [comment]
Hi @choukalos,
I need to tell you that, i haven't set any kind of cronjob in my server{system}, so, those logs are not output of cron.
Yes, your concern regarding debugging error is right, but we already have separate server for development purpose only, so it will be better magento provides a option to stop log in production environment {BROKEN_REFERENCE, these are specially very annoying}.
Thanks, for providing me a temporary solution {logrotate} for large generated log files, but it is still taking my IOPS limit.

@stamster same as your scenario, i also facing the same problem,

**Comment by Ctucker9233** [comment]
I also have this issue.

**Comment by magento-engcom-team** [comment]
@deepanshu27193, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by shubhamsikarwar** [comment]
I also have same issue. Update.log file size increase to 18GB. Any solution ?
