### ISSUE TITLE
Getting table prefix

### ISSUE THREAD

**Issue by esilvajr** [magento/magento2#6402]
Hello, when i trying to getTableName() in Magento 2.1.0 with prefix using \Magento\Framework\App\ResourceConnection the return is the table name without the prefix.

Code:

$connection  = $this->_resource->getConnection();
$tableName   = $connection->getTableName('sales_order_grid');
var_dump($tableName);
$connection->query('my_update_query with $tableName');

Result:

'sales_order_grid'

Error: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_magento_v2_2_1_0_prefix.sales_order_grid' doesn't exist;

Is a bug? There's other way to do that?

Thanks...

**Comment by esilvajr** [comment]
If i use without getConnection() works!

$tableName = $this->_resource->getTableName('sales_order_grid');

**Comment by SerhiyShkolyarenko** [comment]
@esilvajr it's an extected behavior, because prefix is configured on resource level, connection doesn't work with prefixes.
