### ISSUE TITLE
2.1.1 and 2.0.9 known issue sales API

### ISSUE THREAD

**Issue by plentyhappy** [magento/magento2#6407]
I was about to install 2.1.1 but read your statement.  We use Shipstation which sends us tracking numbers once per day.  This updates our order status to complete which then tells authorize.net to capture funds.  Will this process not work anymore?  If so, any idea how long it will take to fix this known issue?

Known issue

The Sales API does not currently support all the update operations on objects that you can execute from the Admin. (Objects in this context include orders, invoices, shipments, credit memos, and return merchandise authorizations.) The Sales API

supports create, read, delete, and search operations on objects

does not support updates to order status or payment status. (Order status includes changes to processing, shipped, processed, and hold, while payment status includes authorized, charged, reject, and refund.)

You can run these operations from the Admin.

**Comment by choukalos** [comment]
Hi @plentyhappy I'll jump in for @mbrinton01; we've got this partially implemented in mainline now (shipping & invoice transacting).  We're working on getting that into a patch (TBD on date) while the team addresses credit memo/rma functionality (TBD on date for that follow up patch).

**Comment by plentyhappy** [comment]
choukalos - thank you so much for taking the time to answer my question :-)

**Comment by mbrinton01** [comment]
Hello @plentyhappy, this is now fixed.  You can see more detail in our release notes: 
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html
http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.11CE.html

Search for "The Sales module provides two new web API endpoints"

Closing issue.
