### ISSUE TITLE
Magento 2.1.1 upgrade

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#6408]
I upgraded my 2.1.0 store from the Admin and the console log stated the update had completed successfully.
However, my frontend and Admin are displaying a Fatal error - see screenshot. I removed the maintenance flag which was still in the var/ directory but it made no difference.
I have tried manually deleting CollectionFactory.php but it says there is a permissions issue and when you try to change the permissions it refuses stating another error.
![magento](https://cloud.githubusercontent.com/assets/10808588/18117660/9dd2cf8e-6f93-11e6-9aff-2e7149e56e44.jpg)

**Comment by PingusPepan** [comment]
Try and stop the cron jobs, then delete var/generation/\* and start cron back.
At least that worked for me

**Comment by bondimedical3** [comment]
I upgraded with composer and it worked fine. However the links in the Admin are no longer clickable and product images do not show in the frontend.

**Comment by veloraven** [comment]
@bondimedical3 thank you for your report.
Please try to clear browser's cache and let us know if it helped.

**Comment by bondimedical3** [comment]
I did another update with composer and all is good now.

**Comment by bondimedical3** [comment]
I have cleared the cache and run into multiple problems. Same issue has appeared again where Admin links do not open and product images and store logo is not showing on the frontend.
