### ISSUE TITLE
Request to implement INR symbol

### ISSUE THREAD

**Issue by napsterv** [magento/magento2#641]
Change Rs. to  ₹.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-27719

**Comment by piotrekkaminski** [comment]
This is currently not a priority seeing many stores use Rs. It will be considered with other i18n/l10n issues.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-to-implement-INR-symbol/idi-p/47005).
