### ISSUE TITLE
warning caused by foreach-loop in salesrule validation

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#6412]
In `\Magento\SalesRule\Model\Rule\Condition\Product\Combine` in the `validate()` method, the line

```
foreach ($model->getAllItems() as $item)
```

can cause a warning to be thrown in the case that `$model->getAllItems()`  does not return an array. This case can occur, so it needs to be checked against.

Find attached a patch, that adds the check.
[check-whether-items-array-exists-vendor_magento_salesrule_model_rule_condition_product_found.diff.zip](https://github.com/magento/magento2/files/446766/check-whether-items-array-exists-vendor_magento_salesrule_model_rule_condition_product_found.diff.zip)

I do not know anymore how to reproduce the problem, but I didn't write this patch for fun. I'm just putting it here for the issue to be documented. So you can forget about the issue template right smartly. Either you fix it (and help your other clients) or your don't, just don't bother me.

**Comment by veloraven** [comment]
@ktruehl thank you for feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by ktruehl** [comment]
@veloraven You're funny! The Magento version is 2.1. Forgot about the rest. Read the last paragraph of my issue description.

**Comment by PingusPepan** [comment]
Why didn't you create PR then? Much better for everyone else than just throwing in a diff file.

**Comment by ktruehl** [comment]
Am I not allowed my own small moment of frustration and exasperation? Of course it's petty. But after 6 grueling months of working with Magento 2 I think I earned at least that much.

### Preconditions
1. CE 2.1.1

### Steps to reproduce
1. backend: add a cart price rule that checks for a product id
2. frontend: add a product to the cart that does not have getAllItems() populated

### Expected result
1. no php notice should be shown

### Actual result
1. php notice due to invalid foreach on an non-array

Happy now? I hope you notice that it doesn't actually contain any more information than the original issue description. Actually the original issue description has more vital information. But who cares? It didn't have the fancy sections.

**Comment by SerhiyShkolyarenko** [comment]
@ktruehl sorry I didn't understand what you meant in the report.
The latest 2.1 version is 2.1.2, so I performed all checks on it.

> In \Magento\SalesRule\Model\Rule\Condition\Product\Combine in the validate() method

That class doesn't contain a `validate()` method or the call `$model->getAllItems()`. Did you mean another class?

> add a cart price rule that checks for a product id

Please describe step-by-step how you created it or provide a screenshot of the conditions section of that rule.
Is the issue reproducible for you on 2.1.2 or latest develop branch?

**Comment by ktruehl** [comment]
Oh, yes. I'm sorry. The relevant code is in `\Magento\SalesRule\Model\Rule\Condition\Product\Found`, not in `\Magento\SalesRule\Model\Rule\Condition\Product\Combine`.

**Comment by magento-engcom-team** [comment]
@ktruehl, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@ktruehl, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
