### ISSUE TITLE
Shipping rates show 0 when there are more than one item in the cart

### ISSUE THREAD

**Issue by tylerd92vn** [magento/magento2#6414]
### Preconditions

1. Magento 2.0.7
2. PHP 7.0.10-2+deb.sury.org~trusty+1 (cli) ( NTS )
3. mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper
4. nginx version: nginx/1.4.6 (Ubuntu)
### Steps to reproduce

1. Enable flat rate and configure the rate to $20
2. Add an item to the cart. Visit the cart and you will see the flat rate there with the price of $20
3. Add another item into the cart (different product or change the existed item's quantity to more than 1)
4. Visit the cart again and you will see the flat rate is still there, but the price is now $0
### Expected result

![rates - 1 product](https://cloud.githubusercontent.com/assets/4945950/18123680/2a1463fe-6f99-11e6-8c84-733acfd6aee5.png)
### Actual result

![rates - different products](https://cloud.githubusercontent.com/assets/4945950/18123678/2a123bf6-6f99-11e6-9c69-3b4fd05737ac.png)

![rates - quantity 2](https://cloud.githubusercontent.com/assets/4945950/18123679/2a130e82-6f99-11e6-817b-390cceaf393e.png)

**Is there any more information needed? If so, please tell me. Thanks a lot.**

**Comment by developer-lindner** [comment]
@tylerd92vn Update to 2.1.1. and report back or close ticket otherwise.

**Comment by tylerd92vn** [comment]
I would prefer another way of fixing this problem than updating the whole framework. Anyways, thanks for your reply.

**Comment by developer-lindner** [comment]
@tylerd92vn You should always update when possible. There are huge changes between 2.0.7 and 2.1.1. Some changes also may already address your issue. Creating tickets here for outdated versions is absolute nonsense and just a waste of time for everyone.

**Comment by alena-marchenko** [comment]
Hi @tylerd92vn ,

I cannot reproduce this issue.
Please provide more preconditions to reproduce this issue.

**Comment by tylerd92vn** [comment]
I updated some more information @alena-marchenko

**Comment by dyushkin** [comment]
Hi @tylerd92vn! Can you check if some cart price rules is set?
Go to _Admin->Marketing->Promotions->Cart Price Rules_

We still cannot reproduce this issue for 2.0.7 with steps you described.

**Comment by alena-marchenko** [comment]
Hi @tylerd92vn,

Closing this issue due to no response, please create new one when you have an update.

**Comment by tylerd92vn** [comment]
Solved! Thanks to @dyushkin. It's the discount rule that when the price is larger than some amount, the shipping is free!!!. But at least, the front-end must show the discount rules applied. I have banged my head to the table a lot of time. A huge appreciation!

**Comment by tylerd92vn** [comment]
Can anyone mark this as solved?
