### ISSUE TITLE
Question: cookie not working with Full Page Cache enabled

### ISSUE THREAD

**Issue by enrico69** [magento/magento2#6418]
### Preconditions
1. **OS** of the server: Debian (Virtualized, with 3GB of memory)
2. **OS of the client**: Windows 7
3. *\* Browser of the client**: Chrome Version 52.0.2743.116 m (64-bit).
4. **MySQL:** Ver 14.14 Distrib 5.6.31
5. **PHP:** PHP 7.0.8-1~dotdeb+8.1 (cli) ( NTS )
### Steps to reproduce
1. Issue a cookie, with PHP or JavaScript
### Expected result

1.  The cookie should be considered, and its value readable.
### Actual result
1. With full page cache enabled, the cookie is issued, but not considered. With the developer screen in Google Chrome, I can see it in the browser request, but if I want to use it with Magento, it doesn't exist if the full page cache is enabled.

**Comment by heldchen** [comment]
i guess you want to read the cookie value inside a block. but with full page cache, this page (and block) is cached, therefore only the first pageview will actually try to read the cookie. you need read up on fpc hole punching to ensure the block is never cached.

**Comment by enrico69** [comment]
Thank's! I didn't know this feature.
