### ISSUE TITLE
Cart Price Rules: Category selection UI for Actions do not come up.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6421]
M2.1.0
Cart Price Rules: Category selection UI for Actions do not come up.

Issue
Category selection UI under Actions does not come up if when a rule is created. The selection UI will come up.

Steps:
- Go to marketing > cart price rules. 
- Try creating a rule, with few categories selected under Actions.
- The categories UI does not pop up. Clicking on the button does not do anything.

Expected: The category selection UI should properly come up every time the rule is created / edited. 

Ver: M2.1.0

**Comment by sevos1984** [comment]
This is fixed in latest 2.1, could you please update your code base?

**Comment by apurv-anand** [comment]
Do you mean 2.1.1 has the fix? We will be updating it in next 2 days. I will let you know the status.

**Comment by apurv-anand** [comment]
We are currently blocked on upgrading it to 2.1.1 because of this issue:

https://github.com/magento/magento2/issues/6471

**Comment by apurv-anand** [comment]
Also let me know if the following is also fixed. Its a variant of this issue. Fixes might be at different place though.

https://github.com/magento/magento2/issues/6396

**Comment by sevos1984** [comment]
I can't help you with this #6471, but #6396 looks the same to this one

**Comment by apurv-anand** [comment]
Its under different sections - one is under Actions, the other one under Conditions. Even the bug behavior is slightly different so I am guessing its different code base.

**Comment by apurv-anand** [comment]
This is NOT fixed in 2.1.1.

The selections in the UI does not get reflected as part of the rule. Check the rule from UI after closing the rule and revisiting or from the DB: salesrule table.

**Comment by sevos1984** [comment]
This is fixed in develop branch https://github.com/magento/magento2/commit/a86eda34f882d9254f707a09f9e209b5c54ee632. Should be in next 2.1 release.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-58321

**Comment by Ctucker9233** [comment]
@sevos1984 I see this commit wasn't included in the 2.1.2 release. Is it safe to manually merge that code into a 2.1.2 production environment?
