### ISSUE TITLE
Paging, sorting missing in Widget Product List Grid

### ISSUE THREAD

**Issue by skhell** [magento/magento2#6423]
### Preconditions

1. Magento CE 2.1.0
### Steps to reproduce

1. Login to the backend
2. Click the sidebar Content --> Pages
3. Create a new page by adding the widget product list to the content as the image below
4. Activate page controls (show_pager="1")
   ![screen shot 2016-08-31 at 19 35 10](https://cloud.githubusercontent.com/assets/20488700/18139509/277e8bce-6fb2-11e6-876d-e017443f5add.png)
### Expected result

1. To see product grid with pager toolbar for sorting and listing more than X product per page
### Actual result

1. Product appear correctly but without toolbar

![screen shot 2016-08-31 at 19 43 49](https://cloud.githubusercontent.com/assets/20488700/18139809/483a9a00-6fb3-11e6-9dc6-c34b2d476bd5.png)

**Comment by sevos1984** [comment]
After clearing cache pager appeared but still not working. I've created ticket for that MAGETWO-58032. Thanks for reporting.

**Comment by skhell** [comment]
@sevos1984 thank you

**Comment by magento-engcom-team** [comment]
@akamura, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
