### ISSUE TITLE
When cache is enable can't getLastRealOrder()

### ISSUE THREAD

**Issue by esilvajr** [magento/magento2#6425]
Well, i think the subject say farly about the error.

When access the $this->_checkoutSession->getLastRealOrder()->getId() object to get the last order id, return null if my cache was enable

```
var_dump($this->_checkoutSession->getLastRealOrder()->getId()); //returns null
```

If i disable the cache, works fine...

**Comment by veloraven** [comment]
@esilvajr thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by voleye** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by Dhimant** [comment]
I am facing the same issue with magento 2.4.2 E.E any solution for this ?

**Comment by sanjay-codez** [comment]
Issue is still there magento - 2.4.3-p2
