### ISSUE TITLE
Admin w/ limited role unable to add products to cart from sidebar when creating order

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#6427]
When an admin is assigned to a role that limits them to just Sales/Carts/Customer, it is not possible for them to add a product to the cart from the admin order create sidebar:

![magento admin questmark-17fqb](https://cloud.githubusercontent.com/assets/129031/18146939/02946e2e-6f98-11e6-8faf-5aa403ec9627.png)

![magento admin questmark-kmu1w](https://cloud.githubusercontent.com/assets/129031/18147022/71bf7faa-6f98-11e6-8e52-f43ada4de0cf.png)
### Preconditions
1. Install Magento EE 2.1.1 with sample data
### Steps to reproduce
1. On the frontend, login to the roni_cost@example.com customer account
   - Go to the /cassius-sparring-tank.html/cassius-sparring-tank.html product an add it to the wishlist
2. Create admin role with the following resources selected: 
   ![magento admin questmark-abro7](https://cloud.githubusercontent.com/assets/129031/18147105/ca3b43f8-6f98-11e6-8716-51cb9016e14f.png)
3. Create admin user with that role
4. Login to admin with that new admin user
5. Go to _SALES > Orders_ and click _Create New Order_
6. Select the "Veronica Costello" customer
7. In the "wishlist" section left sidebar, find the Cassius product and click the "Gear" icon to add product to cart: 
   ![magento admin-lb69p](https://cloud.githubusercontent.com/assets/129031/18147237/54cff66c-6f99-11e6-9701-90dcb1fb100f.png)
8. Select the required options and click "Ok".
### Expected result
1. The product should be added to cart.
### Actual result
1. The spinner will show and then it will hide, but nothing will happen. If you open the Network tab in Chrome DevTools and click "Ok" again, you will see this error:
   ![magento admin questmark-zyel7](https://cloud.githubusercontent.com/assets/129031/18147331/c7377748-6f99-11e6-9505-2c9a618b4123.png)
2. One important thing to note is that the item IS being successfully added to the cart, but the cart is not being updated due to the error. If the admin does another action that successfully updates the cart, they'll see the item in their cart.

**Comment by sevos1984** [comment]
This is not a bug, if you want to configure product you need access to catalog. The problem is in modules dependencies that is not observed in user roles, so if you forbid access to some module you have to disable all related, in other case user will see such errors. Feel free to reopen if you have objections.

**Comment by erikhansen** [comment]
@sevos1984 I strongly maintain that this is a bug in Magento and should be fixed. How is a merchant to know that they need to enable a Catalog ACL resource in order for a feature in the "Create Order" page to work? One of two things needs to be done:
1. The sections in the "Create Order" sidebar should all work if an admin user has access to the **Sales > Operations > Orders > Actions > Create** resource:
   ![magento admin questmark-l1usw](https://cloud.githubusercontent.com/assets/129031/18280238/fec1ff16-741d-11e6-955c-0c74ca8d32ed.png)
2. The sections in the "Create Order" sidebar that currently require catalog resource permissions should be hidden if they don't full work without those permissions. So for example, if a user has **Sales > Operations > Orders > Actions > Create** permissions, but no "Catalog > ***" permissions, the "Recently Viewed Products", "Recently Compared Products", etc sections should be hidden.

Option 1 makes way more sense to me, even though I realize it may result in some coupling between Magento_Sales and Magento_Catalog. Option 2 is a poor workaround, but is better than the current bug.

**Comment by pboisvert** [comment]
@piotrekkaminski can you work with @elenleonova to determine best path forward.
