### ISSUE TITLE
Unable to set price when adding configurable product through REST API (Magento CE 2.0.7)

### ISSUE THREAD

**Issue by shashanksatpute** [magento/magento2#6428]
I have deployed magento 2.0.7 on XAMP server. I want to add configurable product through rest API.
For that I used  http://host:port/Magento/index.php/rest/default/V1/products API. And post below data
"product": {
                            "sku": "product_name",
                            "name": "product_name",
                            "status": 1,
                            "type_id": "configurable",
                            "price": 500000,
                            "attribute_set_id":4,
                            "weight": 1
                        }

This product is added to magento catalog,but Price for this product is not set.

Please suggest me on it.

![image](https://cloud.githubusercontent.com/assets/21389647/18156804/9edbaa88-7036-11e6-9084-7bab69d59167.png)

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket added MAGETWO-57983

**Comment by magento-engcom-team** [comment]
@shashanksatpute, thank you for your report.
We've created internal ticket(s) MAGETWO-81073 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@shashanksatpute, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
