### ISSUE TITLE
Magento 2.1.1 release seems to be desync from Github.

### ISSUE THREAD

**Issue by Blackskyliner** [magento/magento2#6433]
I got an installation today, which got upgraded to 2.1.1 by the customer.
Problem is, the regression from #5116 is not fixed in this installed version. 

I checked the file dates, they all relate to 31.08.2016 so the system was updated yesterday.
So I checked the composer.json and the module-sales version is 100.1.1 so it should have the fix.

But then I looked into the templates within the module, which were also written on the mentioned date. The also mentioned fix is not applied there...

So I guess one of the available upgrade paths has invalid module files, which do not incorporate all fixes from this github repository. I could inquire more information on how the upgrade was made from the customer (zip, web upgrader or composer) but I would take the guess it was done through the web upgrader.

**Comment by hostep** [comment]
PR #5116 isn't merged in 2.1.1, why do you think it was merged in 2.1.1?

2.1.1 only contains critical bug fixes (well, next to some nice improvements in the static files deploy proces), and PR #5116 is certainly not a critical bug. So I think it makes sense it isn't included.

I highly suspect the PR will be included in a later version (2.1.2, 2.1.3, 2.1.4, ...)

**Comment by Blackskyliner** [comment]
Okay, seems I misread something on Github while reviewing before creating my issue. 2.1.1 does not incorporate the fixes from the #5116 you are right. Maybe I was falsely on the develop branch or such.

But then my question, why is it not considered to be included? The bug itself breaks the administrative interface and if something which should work as intended just throws exceptions at you so I feel like its critical but maybe I am wrong with my POV there. The whole change is also really straightforward so why not include it?

So the earliest version incorporating this fix will be 2.2+ ?

I will then just incorporate the fix manual for now and will have to do so every following upgrade of the 2.1 branch...

So for that I will close that issue as the initial question was indeed based on falsely acquired informations. Would be nice to get an answer on my points though, just to be informed about the reasoning of such fixes in general 😄
