### ISSUE TITLE
WYSIWYG Editor parses out variables, can't link emailadresses

### ISSUE THREAD

**Issue by jwittorf** [magento/magento2#6434]
I'm trying to create a link to the "General Contact Email" in the editor. Just outputting the link as plain text works but there are troubles when using variables in a link.
### Preconditions
1. Magento 2.1.0
2. PHP 5.6.24
3. MySQL Server 5.6.32
4. No sample data installed
### Steps to reproduce
1. Edit a CMS page
2. Show the editor
3. Write some text, optionally use a variable like "General Contact Email" or "Base Secure URL"
4. Use the same variable inside the "Insert/Edit link" function (in combination with something else, e.g. `mailto:{{config path="trans_email/ident_general/email"}}` or `{{config path="web/secure/base_url"}}contact`)
### Expected result
1. Input in editor: `<a href="mailto:{{config path="trans_email/ident_general/email"}}">Send us an email to {{config path="trans_email/ident_general/email"}}</a>`
2. Ouput in Frontend `<a href="mailto:info@example.com">Send us an email to info@example.com</a>`
### Actual result
1. Input in editor: `<a href="mailto:{{config%20path=&quot;trans_email/ident_general/email&quot;}}">Send us an email to {{config path="trans_email/ident_general/email"}}</a>`
2. Ouput in Frontend `<a href="mailto:">Send us an email to info@example.com</a>`

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-57978, thanks for posting.

**Comment by magento-engcom-team** [comment]
@jwittorf, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
