### ISSUE TITLE
Feature request: Way to disable new customer welcome email when creating a customer in admin

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#6436]
### Environment
1. Apache 2.4.17
2. MySQL  5.0.11-dev
3. PHP 5.6.15
4. Magento 2.1.0
### Feature request
1. Way to disable new customer welcome email when creating a customer in admin
### Current behavior
1.  No checkbox to disable welcome email: 
   ![hama-1](https://cloud.githubusercontent.com/assets/8377620/18164857/1a596d96-703a-11e6-94ef-28ba2f82ebbd.png)
### Desired behavior
1. The admin customer form in Magento 1 lets you decide whether or not to send a welcome email: 
   ![hama-2](https://cloud.githubusercontent.com/assets/8377620/18164986/b6cb7872-703a-11e6-80d3-e8db8ecf3548.png)

**Comment by pboisvert** [comment]
@ilol can you file this as a functional regression bug

**Comment by ilol** [comment]
Registered MAGETWO-57988

**Comment by sevos1984** [comment]
This was made intentionally as email is the only way to set customer password after creation from admin.

**Comment by JacobDrummond** [comment]
@sevos1984, I appreciate the security.

However, the use-case for a separate "Send Welcome Email" action is:
1. The client inputs all their existing customers, pre-launch.
2. On launch day they send out welcome emails announcing the new site, and asking customers to input new passwords.

Passwords aside, we find that clients want control over when Magento emails customers. (In the example above, it would be embarrassing to notify customers of a site that isn't ready.)

Can MAGETWO-57988 stay open?

**Comment by ilol** [comment]
Him @JacobDrummond. You suggestions make sense. 57988 is still open. I will update one with new requirements. Think we need some action to push mass notification for delayed messages. Agree?

**Comment by JacobDrummond** [comment]
@ilol,

> Think we need some action to push mass notification for delayed messages. Agree?

Batch-sending welcome/reset emails from the customers grid would be very handy. Thanks!

@sevos1984,

> sevos1984 closed this Sep 13, 2016, 9:25 AM GMT+1

Why has this issue been closed when @ilol says MAGETWO-57988 is still open? (I'm not familiar with Magento's internal/external ticket workflow.)

**Comment by ilol** [comment]
That is our internal process. Bug (issue) was closed, user story was created. 
New tracking number is _MAGETWO-58318_

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Way-to-disable-new-customer-welcome-email-when/idi-p/48428).

**Comment by gx2g** [comment]
I'm using magento 2.1.7 and we are having this issue because we have whole sale customers that are first time buyers but created in-house by our admin team. we don't want to look sloppy by sending out welcome messages to customers that are created by admin group. should be a way to turn welcome email off.

**Comment by pitbulk** [comment]
Any progress with that feature?

**Comment by simonmaass** [comment]
I have the same request - any news?

**Comment by JakobG-dev** [comment]
Any news? I need that feature too.

**Comment by affirmative-pl** [comment]
I can recommend a module that helps control this and other email notifications: 
https://magery-themes.com/disable-email-notifications-magento2.html

**Comment by rav-redchamps** [comment]
You might use this extension as well 

https://redchamps.com/disable-welcome-email-magento-2-extension.html

It can disable welcome email for customers created from admin/api or for specific customer groups
