### ISSUE TITLE
shipping and billing address ids not set on sales_invoice table for paypal express invoices

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#6438]
### Preconditions

1. Magento 2.1.0, PHP 7, Mysql 5.7
2. PayPal Express enabled
### Steps to reproduce

1. Put order through using PayPal Express
2. Visit Invoice Grid
3. Display columns billing name, shipping and billing addresses
### Expected result

1. These columns would be populated
### Actual result

1. These cells are blank for PayPal Express Payments
   ![screenshot 2016-09-01 12 05 36](https://cloud.githubusercontent.com/assets/630320/18165367/c435d2bc-703c-11e6-95e9-29cfc8804128.png)

Looking at the order address details, this information exists. So this is not an issue with the data not being retrieved from PayPal. I can see from the sales_invoice table, however, that the billing_address_id and shipping_address_id are null for PayPal Express orders.

**Comment by maderlock** [comment]
It would appear that at the point of saving the invoice, there is no shipping or billing address available on the order itself, so it may be the order in which these things are being placed.

**Comment by maderlock** [comment]
As I don't want to dive in and work out the ordering of saving orders and invoices, for now I've added an observer to copy address information from the order to the invoice. Here are the important files from our Magento2fix module:
https://gist.github.com/maderlock/2b9a0f4f0badc10db66b9a74163d79b4

**Comment by dyushkin** [comment]
Hi @maderlock! Thank you for reporting, we've created internal ticket MAGETWO-58136 to fix it.

**Comment by SerhiyShkolyarenko** [comment]
MAGETWO-58136 is delivered to develop branch. Closing the issue.

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko What version of Magento is this in or is going to be in?
