### ISSUE TITLE
Magento 2.X version detection

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#6440]
Previous versions of magento (1.7.x-1.9.x) provides API Method that returns current magento store version. Why did you removed this API in Magento2? Please add this method to API!

I'm developing Magento wrapper for .net ([https://www.nuget.org/packages/MagentoAccess/]) and i need this API to  support a lot of Magento's versions.

**Comment by MaximKitsenko** [comment]
@veloraven Hi, can i hope this feature will be implemented soon?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-X-version-detection/idi-p/48426).
