### ISSUE TITLE
Google Analytics Tracking Code cached by Varnish if Cookie Restriction Settings are active

### ISSUE THREAD

**Issue by bka** [magento/magento2#6441]
This one is related to #5596. After working around this issue we discovered a problem when using varnish as a full page cache. 
### Preconditions
1. Tested on Magento 2.1 CE
### Steps to reproduce
1. Enable Varnish Cache
2. Enable Cookie Restriction Mode under General->Web->Default Cookie Settings
3. Enable Google Analytics under Sales -> Google API
4. Visit Store Front 
5. Accept Cookies
### Expected result
1. Tracking Code should be present in DOM
### Actual result
1. Tracking Code is **not** present in DOM, because it was cached by Vanished
### Discussion

We think the block `google_analytics` should be declared as non-cachable. This part should be fetched as an ESI block because it depends on _Cookie Restriction Settings_ and my confirmation to allow cookies. You will not see this behaviour with Magento built-in cache.

![auswahl_043](https://cloud.githubusercontent.com/assets/584644/18166058/2d678aee-7049-11e6-8176-e96b43253c9a.png)

This is, what should happen. Analytics script should be fetched as ESI block when using Varnish to avoid this problem:

![auswahl_054](https://cloud.githubusercontent.com/assets/584644/18166075/3fd35208-7049-11e6-8220-13f0fec7fe9d.png)

**Comment by ishakhsuvarov** [comment]
Reopening, as fix for `2.1` is not implemented yet.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69374
