### ISSUE TITLE
magento/framework depends on zendframework/zend-stdlib but it's missing from composer.json

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#6442]
### Preconditions
1.  Installed magento/framework as composer requirement
### Steps to reproduce

1.  use `\Magento\Framework\Phrase`
### Expected result
1. No fatal error
### Actual result

1. `Fatal error: Interface 'Zend\Stdlib\JsonSerializable' not found`

This is a problem when I run unit tests on an extension without having installed it in a complete Magento environment. `magento/framework` should make its dependencies explicit in `composer.json` and not assume it is installed within a complete Magento project.

**Comment by veloraven** [comment]
@schmengler thank you for report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by schmengler** [comment]
The used `magento/framework` version was `100.1` (via module versions from Magento 2.1.0)

**Comment by BaDos** [comment]
Hi @schmengler 

Thank you for reporting.

The internal ticket MAGETWO-58394 was created to resolve this issue.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11
