### ISSUE TITLE
Cart Price Rule: Category selected under Actions do not get saved completely.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6444]
M2.1.0
Cart Price Rule: Category selected under Actions do not get saved completely.

Issue: While creating cart price rule, the categories selected under actions do not get saved completely. Out of multiple selections, only few are getting saved. Not sure it is about the total variable length issue (we have few tens of categories).

Steps:
- Go to Marketing> Cart Price rule.
- Create a rule, under Actions, select Categories to be included / excluded.
- Have a long list of categories that are selected.
- Save.

Current: Not all categories get saved.
Expected: All selected categories should be saved, even if there are few tens of them.

**Comment by veloraven** [comment]
@apurv-anand thank you for report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by apurv-anand** [comment]
Version has been updated as 2.1.0
Latest updates where used.

**Comment by oleg-onufer** [comment]
Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?

**Comment by magento-engcom-team** [comment]
@apurv-anand thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation.
