### ISSUE TITLE
Newsletter Subscription is cancelled automatically on Account Confirmation

### ISSUE THREAD

**Issue by patrickunic** [magento/magento2#6445]
### Preconditions

Version 2.1.1
### Steps to reproduce

Create a new Account
Select "Sign up for Newsletter"
Open Confirmation Mail and click the Confirmation-Link.

It looks like in site/vendor/magento/module-newsletter/Model/Subscriber.php:_updateCustomerSubscription the subscription parameter is not correctly referenced. Then we get $status = self::STATUS_UNSUBSCRIBED; and later a Mail with the unsubscribe-Information is sent.
The function is called like: $this-_updateCustomerSubscription($customerId, $this-isSubscribed());
It totally makes no sense to check here if the new User has already subscribed...
At first on "create Account" the subscription is correctly set, but because the Account isself is not confirmed, the Status is not updated.
### Expected result

Account should be confirmed
Newsletter should be subscribed
1 Thanks for Registration Mail should be send
### Actual result

Account will be confirmed
Newsletter Subscribtion is removed
1 Thanks for Registration Mail is send
1 Unsubscription Mail is send

**Comment by sevos1984** [comment]
This duplicates https://github.com/magento/magento2/issues/6183

**Comment by msawyers** [comment]
This issue is not closed. Still exist in Magento 2.1.5

**Comment by vajor-saurabh** [comment]
Hello,
I have query when we signup new customer then i getting unsubscribed newsleetr mail.. I am using 2.1.5 version ... please let me know what i do ..?

**Comment by puneetk00** [comment]
This work for me http://pastebin.com/8nnA6AvV.
you need to override core class.
