### ISSUE TITLE
Image import does not work when serving from the `pub/` directory

### ISSUE THREAD

**Issue by leftclickben** [magento/magento2#6449]
When the web server configuration sets the web root to the `pub/` directory, rather than the Magento installation root, importing images does not work.
### Preconditions
1. Magento 2.0.8 via composer, but it looks like the problem is not fixed in 2.1.x
2. PHP 5.6.22
3. MySQL 5.6.30
4. Permissions and file ownership are set as per http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html#mage-owner-about-group (this is not a file permission issue)
5. Ngnix 1.4.6
6. Production mode
7. Site configuration only sets `$MAGE_ROOT` and `$MAGE_MODE` and then includes `nginx.conf.sample`

This could probably also be reproduced in Apache with the web server root set to the `pub/` subdirectory of the Magento installation.
### Steps to reproduce
1. Fresh installation.
2. Perform a product import with images.
### Expected result
1. Products import successfully, with images.
### Actual result
1. Import fails, no error in log.
2. Products exist without images, up until the max number of errors is reached.
3. Error report CSV lists error as: "Imported resource (image) could not be downloaded from external resource due to timeout or access permissions" for all records with an image.
### Details
1. This is caused by the web server root being `$MAGE_ROOT/pub` instead of `$MAGE_ROOT`.  Import works when the web server root is the root of the Magento install.
2. `vendor/magento/module-catalog-import-export/Model/Import/Product.php` line 1761-1762:
   
   ```
       $dirConfig = DirectoryList::getDefaultConfig();
       $dirAddon = $dirConfig[DirectoryList::MEDIA][DirectoryList::PATH];
   ```
3. This results in `$dirAddon` being set to `pub/media`.  This is handled relative to the current working directory, which is the web server root directory.  When the web server root is `$MAGE_ROOT/pub`, this results in a path like `$MAGE_ROOT/pub/pub/media`, which obviously does not exist.  When the web server root is `$MAGE_ROOT` then the result is correct, `$MAGE_ROOT/pub/media`.
### Workarounds / Improvements
1. Changing the web server configuration to use the web server root, however this has certain security implications in production.
2. There are exceptions being swallowed, for example `vendor/magento/module-catalog-import-export/Model/Import/Product.php` line 1812 (I have seen several other examples).  Logging these exceptions would make debugging much easier.

**Comment by BaDos** [comment]
Hi @leftclickben 

Thank you for reporting.
It seems like fixed on [develop branch](https://github.com/magento/magento2/commit/426a43024119450b601edeecf7760ba152b88956)

Could you try to reproduce it on develop branch?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
