### ISSUE TITLE
Login Popup broken on iPad portrait

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#6451]
Login popup is broken on iPad (portrait orientation) when using Magento/blank theme.
### Preconditions
1. Install Magento 2.1.1
2. Use Magento/blank OR Magento/luma theme
3. Disable checkout for guests ( Admin >> Stores >> Configuration >> Sales >> Checkout >> Checkout options >> Allow Guest Checkout  >> Set to "No" >> Save Config button)
4. Flush cache
### Steps to reproduce

1. Go to your website as guest
2. Add to cart any product
3. Click on "Cart icon" in header 
4. Click on "Go To Checkout" button
5. See login popup
### Expected result
1. Design should be same as for desktop (because menu also displaying from desktop)
   ![image](https://cloud.githubusercontent.com/assets/1873745/18176620/066aac42-707f-11e6-91bc-b573dba21033.png)
### Actual result

Design is broken (mix from mobile & desktop versions):

Magenco/blank theme:
![image](https://cloud.githubusercontent.com/assets/1873745/18176559/c4d269dc-707e-11e6-9e26-a9498b9589a0.png)

Magento/luma theme:
![image](https://cloud.githubusercontent.com/assets/1873745/18176989/bd175c14-7080-11e6-870b-0c89b3aae834.png)

**Comment by vil11** [comment]
Hi, thanks for reporting this. Internal ticket **MAGETWO-59902**.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-68774
