### ISSUE TITLE
Cookie Restriction Mode Overlay is cached by Varnish

### ISSUE THREAD

**Issue by bka** [magento/magento2#6455]
Ok, here is another one related to full page caching with varnish. It's related to these other issues: #6441, #5596. Using cookie restriction mode in combination with varnish does not work, because this block is not declared as non-cachable. Having cookie restriction mode enabled, customer is asked by a dialog to accept cookies. This cookie notice block contains the question: _"We use cookies to make your experience better. To comply with the new e-Privacy directive, we need to ask for your consent to set the cookies. Learn more."_ and gives you a button to _"Allow Cookies"_. Using varnish it might happen that this dialog won't appear anymore. Here is how:
## Steps to reproduce
1. Tested on Magento 2.1 CE
2. Use Varnish as Full Page Cache
3. Enable Cookie Restriction Mode under General->Web->Default Cookie Settings
4. Flush Cache
5. Visit Store Front
6. Accept Cookies by clicking on Allow Cookies button
7. Flush Cache
8. Visit Store Front (Your acceptance will be cached)
9. Delete your Cookies
10. Visit Store Front again (I'm an unkown visitor now with no cookies)
## Expected result
1. Cookie notice block should appear again 
## Actual result
1. Cookie notice block **does not** appear (and never will for anybody until you clear cache again)

**Comment by ishakhsuvarov** [comment]
Reopening, as fix for `2.1` is not implemented yet.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69372

**Comment by sydekumf** [comment]
We still experience that in 2.2.6 with normal Magento cache (no varnish). Why?
