### ISSUE TITLE
package module

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6458]
Hi,

I using magento 2.0.0 And i going to made tifin service website and i want to made onew type of package module like rice varity, sabji varity etc.

Actual result:-
Made package module into category page.
Excepted result:- 
![filter](https://cloud.githubusercontent.com/assets/20356638/18192443/e169d9d6-70f1-11e6-9100-bb5cc6cd2dd9.png)

It is possible or not in magento 2.0.0?
Thanks.

**Comment by pboisvert** [comment]
@Aartitops doesn't seem like you are reporting a coding issue with Magento. Questions such as this in terms of how to code to solve a particular problem are best suited for Stack Exchange or the Forums. If so please close and move your question there. If you are reporting an issue, please use the reporting guidelines to state the problem, your system info, and steps to reproduce the error you are seeing.

**Comment by Aartitops** [comment]
Hi,
can you explain me properly what you say?
thnaks.

**Comment by pboisvert** [comment]
In simplest terms:
- if you found a problem with the Magento 2 code=report here as an issue and we will investigate
- if you need to know how to code something in Magento 2 and the developer documentation does not answer your question=post a question in the [Magento Stack Exchange](http://magento.stackexchange.com/?tags=magento2)
