### ISSUE TITLE
order summary no include product tax

### ISSUE THREAD

**Issue by Walters-Kuo** [magento/magento2#6462]
![order_summary](https://cloud.githubusercontent.com/assets/3149367/18194412/09efc2b4-7118-11e6-8867-a7069e41b7ac.png)
![product_tax](https://cloud.githubusercontent.com/assets/3149367/18194411/09ef6a9e-7118-11e6-880a-6633f050f320.png)
![site_tax_config](https://cloud.githubusercontent.com/assets/3149367/18194416/09f0e824-7118-11e6-9643-86bfa6c6f214.png)
![site_tax_config_1](https://cloud.githubusercontent.com/assets/3149367/18194415/09f100fc-7118-11e6-8732-b4b476d281f6.png)
![site_tax_config_2](https://cloud.githubusercontent.com/assets/3149367/18194413/09f0a620-7118-11e6-92ce-62ee15343143.png)

![goods_tax](https://cloud.githubusercontent.com/assets/3149367/18194414/09f0b890-7118-11e6-9bdf-068d8b40ed18.png)
![tax_zones_rates](https://cloud.githubusercontent.com/assets/3149367/18194417/0a10dd50-7118-11e6-985e-be125cbaca25.png)

### Preconditions

1. Magento 2.0.8, php 7.0.9, MySQL 5.6.27
### Expected result

Cart Subtotal $179
Shipping $10.94
Tax $179 \* CA rate (7.5 / 100) = 13.425
Order Total Incl. Tax ($179 + 10.94 + 13.425) = 203.36
### Actual result

Cart Subtotal $179
Shipping $10.94
Tax $0.00
Order Total Incl. Tax ($179 + 10.94 + 0.00) = 189.94

Is this a bug or a wrong configuration?

**Comment by veloraven** [comment]
@Walters-Kuo thank you for your report.
Please describe steps with words, not screenshots only .
To what exact step does you question refer?

**Comment by pboisvert** [comment]
@Walters-Kuo configuration rules at a glance look correct so the one thing to check would be for the products that were in the cart do you have the correct tax class set. It needs to be set to "taxable goods" in order for the rates to be applied in checkout. I don't see a screenshot for that so just offering this as an item to check.

**Comment by Walters-Kuo** [comment]
@pboisvert  those are tax zones and rates info, thanks

![tax_rate](https://cloud.githubusercontent.com/assets/3149367/18235671/5931259a-7350-11e6-924f-862eddb8544d.png)
![tax_zones_reates](https://cloud.githubusercontent.com/assets/3149367/18235769/9d330aa0-7351-11e6-9832-beacd98f2e9e.png)

@pboisvert thanks, add two screenshot about tax rule
![goods_tax](https://cloud.githubusercontent.com/assets/3149367/18235450/8c9d9be6-734d-11e6-9302-7994d2a42b01.png)
![tax_rule](https://cloud.githubusercontent.com/assets/3149367/18235451/8e154d84-734d-11e6-8fd7-672883cc8b78.png)

**Comment by Walters-Kuo** [comment]
@veloraven 
1. first, I open two site, Default Config : sales --> Tax --> Tax Class for Shipping and Default Tax Class for Product status are none.
2. a couple of weeks, I create a new us site, order summary need to plus shipping tax and goods tax, so i modify Tax Class for Shipping and Default Tax Class for Product to "Taxable Goods".
3. and order summary no include product tax

I try to many way, change different tax rule and rate, tax calculation.
but Nothing's changed, it doesn't work.

**Comment by Walters-Kuo** [comment]
@pboisvert tax rate information, thanks
![tax_rate](https://cloud.githubusercontent.com/assets/3149367/18235660/3b0e7c20-7350-11e6-96e8-11d1949e3824.png)

**Comment by senthilengg** [comment]
@Walters-Kuo on a side note, though its not related to issue here. Please correct your folder and file permissions as per http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html.

**Comment by pboisvert** [comment]
@Walters-Kuo thanks for the screenshots but you missed my question. Your rates appear to be set up correctly. However, you will want to ensure that the tax class for any products where you want to charge tax is set correctly. You can check this in your catalog for the products that you placed in the cart. Please confirm that you have set the products as taxable to use the rates that were set up.

**Comment by Walters-Kuo** [comment]
@senthilengg  thank you for the notice.
@pboisvert  it works. 
i forgot set the taxable of products. 
thank for your help.

**Comment by pboisvert** [comment]
closing as this was configuration error and not code issue.
