### ISSUE TITLE
User Roles issue with limited user permission for Content --> pages

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#6463]
### Preconditions

1. Magento 2.1
2. PHP 5.6 , Nginx+PHP-Fpm 
### Steps to reproduce

1. Create a new User Role.
2. Content --> Pages should only be allowed. 
3. Assign the role to any user.
4. Login with the above user credential and make sure you have access to only Pages.
5. Go to Pages
6. Click Add New Page -->  Click Content --> Click Show Hide Editor ( Press F5 or refresh the page )
7. Try Insert Widget --> Select Catalog Product List from drop down --> Click the + icon to select products -- > Click list icon
### Expected result

1. Tiny Mce should be viewed. 
2. Product list should show up for selection.
### Actual result

1. Editor not displayed.
2. Page refreshed.

**Comment by sevos1984** [comment]
Permission for Widget and Products needed in this case. It is not a bug. Please, reopen if there are any objections.

**Comment by senthilengg** [comment]
@sevos if that's the case then I have made it working with the work around of giving access to Marketing --> Catalog price rules alone and not the  catalog. So I would like to reopen this.
