### ISSUE TITLE
Error production mode, dan't save cms page in production mode

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#6464]
### Preconditions

1. PHP 5.6
2. Memory Limit 1024 M
3. Magento 2.0.9
### Steps to reproduce

1. Switch to production mode
2. Skip compile as I get this error as many other people reported already

```
Start compilation
Command returned non-zero exit code:
`php -f /home/zizzowa1/public_html/bin/magento setup:di:compile-multi-tenant 2>&1`
```
1. php bin/magento deploy:mode:set production --skip-compilation
### Expected result

1. Magento should be faster and work
### Actual result

1. Magento is very slow
2. CMS Pages can't be saved anymore, on save loading doesn't stop anymore

**Comment by veloraven** [comment]
@flipflap please specify the used Magento version.

**Comment by flipflap** [comment]
Sorry, Magento 2.0.9

**Comment by sevos1984** [comment]
To run production mode static content should be deployed 'bin/magento setup:static-content:deploy', have you done this?

**Comment by flipflap** [comment]
Hi sevos1984, thanks, yes I have done this, but didn't help.

**Comment by sevos1984** [comment]
Are there any errors in magento logs?

**Comment by sevos1984** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
