### ISSUE TITLE
Braintree not available in multishipping

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#6467]
### Preconditions
1. Magento 2.1.1
2. Braintree configured
### Steps to reproduce
1. Add products to cart
2. Try finalize order using multishipping
3. Go to billing section
### Expected result
1. Braintree available just like in onepage chekout
### Actual result
1. Braintree is not available

**Comment by asemenenko** [comment]
@Bartlomiejsz current implementation is build using hosted fields approach (tiny iFrames). Also we have a 3D Secure that is also build using frame. Existing multi address checkout creates multiple sales orders and requires multiple transactions to be created which can not be integrated seamlessly to Braintree since we need to display total amount for all orders to the client. We have item in the backlog to improve this part of the multiaddress checkout that will allow us to properly integrate BT by having a single payment transaction only.

**Comment by Bartlomiejsz** [comment]
Is there any estimation when you would be able to work on improving this part of checkout?

**Comment by asemenenko** [comment]
@Bartlomiejsz it depends on many variables, can not promise anything right now. I added this ticket number to notification list and it will be updated once it gets resolved.

**Comment by Bartlomiejsz** [comment]
Great, thanks a lot!

**Comment by mehh** [comment]
Any update on this issue? @asemenenko

**Comment by sshymko** [comment]
@asemenenko 
The issue has not been resolved, so no reason to close it.
Both Braintree and multi-shipping checkout are out of the box features of Magento.
However, the first one is incompatible with the latter one.
It's an apparent core bug and a pretty urgent one as it renders the checkout unusable.
Please reopen.

**Comment by sshymko** [comment]
Could you please reopen the ticket as the issue has not been addressed.

**Comment by Bartlomiejsz** [comment]
@asemenenko @veloraven @magento-team could you please reopen this issue as it stil persists?

**Comment by orlangur** [comment]
Well, this sounds more like a feature request rather than a bug report. If you see an easy fix you can try to prepare a pull request.

**Comment by dmitrii-fediuk** [comment]
_(no spam please)_

**Comment by rsranjith** [comment]
Any update on this issue?

**Comment by cristianmalfesi** [comment]
hi. Any progress on this issue??? We need it please :)

**Comment by orlangur** [comment]
@sshymko @Bartlomiejsz @rsranjith @chm1975 
GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
