### ISSUE TITLE
Customer-Data stored in cookie storage not within storeview namespace

### ISSUE THREAD

**Issue by Nilson89** [magento/magento2#6468]
### Preconditions
- Magento 2.1.0
- Magento Installation with a shop, that has more than one store view (de, at, ch)
### Steps to reproduce
1. Create different shops with different domains:
   a. Shop A: www.shop-a.com (also cookie domain with cookie path "/")
   b. Shop B: www.shop-b.com (also cookie domain with cookie path "/")
2. Create store Views for different languages in Shop A
   a. Germany: www.shop-a.com/de (cookie path is "/de")
   b. Austria: www.shop-a.com/at (cookie path is "/at")
3. Go to Shop A/de and add products to cart.
4. Go to shop A/at
5. You will see products in cart that were added while browsing through shop A/de
### Expected result

Switchin from Shop A to Shop B should not display products added to cart in Shop A.
This behaviour should also be seen, if you switch only storeview from Shop A/de to Shop A/at (because the cookie path is different).
### Actual result

At the moment, the cookie path is statically set to "/" although it is configured to "/de" or "/at". See file app/code/Magento/Customer/view/frontend/web/js/customer-data.js Lines 24-27.

**Comment by veloraven** [comment]
@Nilson89 thank you for your report.
Please clarify your steps and expected result:
- What do you mean as 'product of Storeview A'?
- Where should not it be shown at Storeview B?
  Please describe more detailed steps starting with product creation and its parameters.

**Comment by ihor-sviziev** [comment]
@Nilson89 as I know magento allow you to have shared shopping cart betwean store views, so it is not an issue. If you want to have different shopping carts for store views - you should manage it with different domains, where cookies will be not shared.

**Comment by Nilson89** [comment]
@veloraven I hope the description is now more detailed and understandable.

@ihor-sviziev you are right. we are using different domains. But we have also different cookie paths for different store views inside the domains. These different cookie-paths are not used in JS, thats why cookies are shared although we dont want them to be shared.

**Comment by PascalBrouwers** [comment]
@Nilson89 then you should use different Websites within Magento.
Your Stores config page should look like:
| Website                | Store             | Storeview    |
|----------------   |---------  |-------------  |
| www.shop-a.com    | store-a   | storeview-a   |
| www.shop-b.com    | store-b   | storeview-b   |
This way you are using 2 websites, so carts are not shared.

When you use 1 website and multiple stores, the shopping carts can be shared.

**Comment by Nilson89** [comment]
@PascalBrouwers We are already using different websites. But these websites have also different store views.

In the backend I can configure a cookie path. This is not handled for customer-data.
If you look inside magento2/app/code/Magento/Customer/view/frontend/web/js/customer-data.js you will see on lines 24-27, that this is just missing.

**Comment by PascalBrouwers** [comment]
Ah, now I see what you mean. The cookie path gets a fixed value of '/'

**Comment by Nilson89** [comment]
@PascalBrouwers yeah I think that is the problem :)

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-59135. Thanks for reporting

**Comment by slavvka** [comment]
The issue has been fixed for 2.2. Soon it will be ported to previous releases
