### ISSUE TITLE
[2.1.1] Backup tool, issue with symlinked media folder.

### ISSUE THREAD

**Issue by peec** [magento/magento2#6470]
Symlinked `media` folder is often used for high availability clustered setups where mounting the shared resources (such as pub/media) amongst multiple physical machines.
### Preconditions
1. Install Magento 2.1.1 CE
2. Env: PHP 7, Nginx, Varnish, Production mode
3. Using media storage default (file system).
### Steps to reproduce
1. Create /mediastorage folder.
2. Symlink pub/media to . /mediastorage.
3. Create a backup in the admin panel ("Database and Media Backup")
4. Download the backup tar file
5. Unzip and go into the pub directory of the tar archive. 
### Expected result
1. media folder should not be a simple file. The backup routine should acknowledge the media folder as a folder and zip the actual folder.
### Actual result
1. Media folder is a file ( and not a folder ).
2. As a result. No media files is backed up!

![image](https://cloud.githubusercontent.com/assets/131546/18200297/71428c4e-7104-11e6-9dbf-a83754565a99.png)

**Comment by PascalBrouwers** [comment]
I think this is how the 'System Backup' is supposed to work. When you put it back your symlink is there again.
Now for the 'Database and Media Backup' you might have a point.

**Comment by peec** [comment]
I Agree for the "System Backup" - which essentially should copy the installation from the root folder. However, I used "Database and Media Backup" and expected that the contents of the media folder would be backed up.

**Comment by petterkj** [comment]
This is quite important issue. The "Database and Media Backup" does not work atm. It seems just like a "System backup".

**Comment by mbrehme** [comment]
Yeah, we have this issue as well. It would be great to have the option to "Follow Symlinks"

**Comment by RomanKrut** [comment]
@peec Hello, can you check your problem on the latest version Magento 2? I can`t reproduce it

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
