### ISSUE TITLE
M2.1.0: System Upgrade: Component Dependency throws error, does not give any details.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6471]
M2.1.0: System Upgrade:  Component Dependency throws error, does not give any details.

This issue occurred again while upgrading M2.1.0 to M2.1.1

The upgrade triggered from admin interface fails at component dependency. The error does not give any clue which component is facing the issue. No logs (at least I am not able to locate it) has the details. 

Steps:
- Login to M2.1.0 backend.
- Go to System Upgrade.
- Check that 2.1.1 is available.
- Start the upgrade.

The system fails on dependency failure with no clue to user what should be fixed.

Expected: Clear details for the error so that user can take right actions. I am not sure which log would have the details. The log details can be mentioned in the comment for us to move forward as a workaround.
![upgrade](https://cloud.githubusercontent.com/assets/17824537/18201014/3cccf348-7125-11e6-8b8a-357a6cdfb446.PNG)

**Comment by alex-code** [comment]
I've encountered this before, the fix for me was to increase the memory limit in PHP.

**Comment by apurv-anand** [comment]
We have increased the memory limit to 2GB. The issue still exist. Any other pointers to resolve the issue? I am not even sure what the issue is. How do we reach that information first?

**Comment by apurv-anand** [comment]
Guys, any leads on how to debug this issue? If I know which module has the problem, I can try solving it...but how to figure out which one has the issue? Let me know if there are logs that I am missing to look at currently. This is urgent.

**Comment by UKRogue** [comment]
Exactly the same problem here and same versions. Memory increase has no affect. Is there anyone out there who can help us move past this problem?

**Comment by apurv-anand** [comment]
Developers, we need attention on this, or at-least a workaround. Don't have any clue what the problem is, so cannot resolve it. Please take this up on priority.

**Comment by shiftedreality** [comment]
Hi @apurv-anand 

Please provide more details about your environment: OS version, PHP version, Apache/Nginx

**Comment by apurv-anand** [comment]
OS version: Ubuntu 14.04.4 LTS
PHP: PHP 7.0.9 (Zend Engine: v3.0.0.)
Apache:  Apache/2.4.23

**Comment by shiftedreality** [comment]
@apurv-anand 

Could you please also try next approach:
- Go to Readiness check where error is happening
- Open Developer Console
- Go to tab XHR
- Press Try Again button
- Observe action called "componentDependency"
- Provide response that it gives to you

**Comment by apurv-anand** [comment]
Followed your steps. The response tab is blank, but the status code is getting set to 500 Internal Server Error.

Looking at the Apache error logs, I see: AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in .../composer/src/Composer/DependencyResolver/RuleSetGenerator.php
Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in .../magento/framework/Session/SessionManager.php on line 139\n', referer: http://<server>.com/setup/

Are the errors related? What are the next steps?

**Comment by apurv-anand** [comment]
In Component Manager one module is present with all empty fields - name, module, etc. (type = module) and id I try to enable it, the message is similar:

Check Component Dependency
We found conflicting component dependencies. Hide detail
Can not find module name.
For additional assistance, see component dependency help.

Can these be related? how to find which module is this?

**Comment by apurv-anand** [comment]
![upgrade2](https://cloud.githubusercontent.com/assets/17824537/18288761/668c6132-749a-11e6-9d58-2977eb3f6e98.PNG)
I was able to move past the dependency check after changing the max_memory limit from 256MB to 2GB in php-fpm settings and htaccess and restarting php-ftpm.

But now, I am with one more error with no information. 

Backup failed. Error received from server: <blank>

**Comment by apurv-anand** [comment]
In the install.log, backup is successful, but UI throws error (as in the previous attachment) even while the back-up is still going on.

**Comment by apurv-anand** [comment]
@shiftedreality : Please let me know the next steps.

**Comment by shiftedreality** [comment]
Hi @apurv-anand 

It also may be related to your environment settings.
Please, check XHR response and apache logs on backup step.

Update:
Plase also check your environment with http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html

**Comment by apurv-anand** [comment]
503 - Backend fetch failed error.

<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 429618</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by apurv-anand** [comment]
I could not resolve this issue, even after increasing the http_resp_hdr_len as mentioned in Magento: http://devdocs.magento.com/guides/v2.0/config-guide/varnish/tshoot-varnish-503.html 

I had to upgrade without the backup. 

Point here is that none of these issues are shown up in the UI and users takes a lot of time to figure out the reasons for the failure. This needs to be fixed by Magento 2.x

**Comment by Ctucker9233** [comment]
I also have this issue. Prevents me from upgrading magento or installing modules through the web component manager. I'm on Magento 2.1.1. I'm on a hosted server, so increasing the memory limit is pretty much impossible.

**Comment by oshmyheliuk** [comment]
Hi @apurv-anand
Please try to increase varnish timeout, because backup operation take too much time, and varnish can return 503 error if not got a response from the backend for a long time.
first_byte_timeout (default: 60s)  - increase to 300s or even more.
[UNDERSTANDING TIMEOUTS IN VARNISH CACHE](https://info.varnish-software.com/blog/understanding-timeouts-varnish-cache)

**Comment by oshmyheliuk** [comment]
Hi @Ctucker9233 
Magento needs minimum 768MB PHP memory limit (recommended 2G). It's official Magento2 system requirements.
You can ask your hosting provider to increase this parameter.

**Comment by mitulispace** [comment]
![e7fa7f84-824a-11e6-9df8-44e3809bb1d9](https://cloud.githubusercontent.com/assets/16436069/18823621/53cac02c-83d9-11e6-84a8-aad04e7f280d.PNG)

Same Issue Any Solution.... @apurv-anand @Alex-Code @shiftedreality @veloraven @BaDos
