### ISSUE TITLE
Magento 2.1.1 - Authorize.net payment gateway - after order placement spinner keeps spinning

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#6474]
### Preconditions

1. I freshly installed and configured 2.0.9, and then upgraded the store to 2.1.0 and recently to 2.1.1.
2. I am using the PHP 7.0 version.
3. My shop is in developer mode.
4. I enabled the LIVE mode in authorize.net and my backend settings are shown in picture 4 below.
5. I have read all current open issue threads on github regarding authorize.net problems with magento2.
### Steps to reproduce

1. Add products to cart
2. Go to checkout (enter user details, shipping mode...)
3. Enter test credit card number 5424000000000015 or 4111111111111111
4. Proceed with payment
### Expected result

After declining a test credit card number, magento should stop spinning the spinner.
### Actual result

Magento does not stop the spinner. 

[Screenshot, logs]

In the 2 pictures below, you can see the output from console:
![bugreport2](https://cloud.githubusercontent.com/assets/282687/18204423/02fcc394-711d-11e6-995a-e158d910f5f4.PNG)

![bugreport1](https://cloud.githubusercontent.com/assets/282687/18204421/02f8b1dc-711d-11e6-8658-ff92cdc1e834.png)

Magento2 also produces a transaction fail message for a short while. After that, message dissapears, and spinner keeps spinning. 
![bugreport5](https://cloud.githubusercontent.com/assets/282687/18204788/deafb256-711e-11e6-9b41-6737cb36e1c3.PNG)

In the picture below, there are my settings for the authorize.net payment gateway in magento backend. **Magento produces the same situation, regardless if I choose payment action as "authorize and capture" or "authorize only":**
![bugreport3](https://cloud.githubusercontent.com/assets/282687/18204424/03002264-711d-11e6-9eb3-45ca9d548a2e.PNG)

On authorize.net interface, I see can the declined transaction (which is OK, because I used test credit card number). 
![bugreport4](https://cloud.githubusercontent.com/assets/282687/18204422/02fb4316-711d-11e6-9cc2-97648f3e68b4.PNG)

Also, you can check my debug and exception log from var folder (in which I changed all personal data...):
[debug.txt](https://github.com/magento/magento2/files/452130/debug.txt)
[exception.txt](https://github.com/magento/magento2/files/452114/exception.txt)

[Additional note]
Setting the authorize payment gateway is the last step to finally go to production with Magento2, so I am really desperately in a need for some useful feedback. Cheers.

**Comment by alena-marchenko** [comment]
Hi @jernejh 

This is a duplicate issue, MAGETWO-56932 ticket is already created.
 I'm closing this one. Please feel free to reopen if you need.

**Comment by jernejh** [comment]
Are you sure that this is a duplicate issue, since I have https enabled for all my pages?

Will this be fixed in 2.1.2? When is approximate release date? 

I desperately need a patch, in order to go to market with the webstore of my client.

Are there any quick alternative temporary solutions to disable the spinner to load indefinitely?

Thank you!

**Comment by plentyhappy** [comment]
I'm interested if this is a duplicate issue too - my site is all https too.  I am on 2.0.7 presently but want to upgrade to 2.1.2 when it comes out.  We have the spinning issue and it has haunted us since 2.0.

**Comment by jvreeken** [comment]
same problem here... site is fully https, having the exact same issue with success not redirecting to success, failing to show real error messages of declined payments etc...  why is magento 2.1.1 so broken?

**Comment by jernejh** [comment]
problem still persists in 2.1.2 :(

**Comment by jvreeken** [comment]
yes... problem is still happening on 2.1.2 for me too.

**Comment by YevSent** [comment]
Fix from MAGETWO-56932 ticket will be available for 2.1.3 version.

**Comment by abi2** [comment]
@joni-jones  Any ETA on when 2.1.3 will be released?

Thank You

**Comment by Ctucker9233** [comment]
@joni-jones any commit references?

**Comment by erikhansen** [comment]
@joni-jones As [I just asked on #5642](https://github.com/magento/magento2/issues/5642#issuecomment-261084122), can you post the commit(s) where this was fixed? I need to patch this for a merchant and can't wait for 2.1.3 to be released.

**Comment by erikhansen** [comment]
@joni-jones Are you sure you have the MAGETWO ticket number correct? I hunted down the file responsible for hiding/showing the spinner for payments (`app/code/Magento/Payment/view/frontend/web/js/view/payment/iframe.js`) and then looked at the history for that file and found this commit of yours, referencing ticket number MAGETWO-56934 (two digits away from MAGETWO-56932): https://github.com/magento/magento2/commit/2d31571f1bacd11aa2ec795180abf682e0e9aede

I applied that single line patch to my environment and when I placed an invalid Authorize.net order, the spinner did not show forever like it was before.

**Comment by YevSent** [comment]
@erikhansen, the ticket is correct. MAGETWO-56934 contains fix for the develop version, MAGETWO-56932 - for 2.1.3.

**Comment by erikhansen** [comment]
@joni-jones Ok. Can you provide a link to the commit for MAGETWO-56932?

**Comment by YevSent** [comment]
@erikhansen, the for 2.1.3 the same as in https://github.com/magento/magento2/commit/2d31571f1bacd11aa2ec795180abf682e0e9aede .
