### ISSUE TITLE
Link at checkout not working for "What Is PayPal?"

### ISSUE THREAD

**Issue by gazzaf** [magento/magento2#6477]
At the checkout the built-in link **What is PayPal** opens an _empty_ pop-up window. This is bad for customers as the link is supposed to gain their confidence. Using IE11 the window shows the 404 page but is completely blank using Firefox and Chrome.

**Screenshot of checkout page:**

![magento-paypal1](https://cloud.githubusercontent.com/assets/677452/18212286/3cf3a366-713a-11e6-8f4d-aafc4386bcb1.jpg)

**Screenshot of pop-up after clicking on "What is PayPal?":**

![magento-paypal2](https://cloud.githubusercontent.com/assets/677452/18212291/452076ae-713a-11e6-8d64-98f54e7f0851.jpg)

Config: Magento 2.1.0
Theme: Luma (default, unedited)
Payment method: PayPal Website Payments Standard

How can this be fixed please?

**Comment by andimov** [comment]
@gazzaf 
Thank you for reporting this issue!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by gazzaf** [comment]
I've uninstalled Magento 2.1.x because of the enormous number of bugs and slowness that make it unfit for production and "upgraded" to 1.9.x. Sorry.

**Comment by dyushkin** [comment]
Hi @gazzaf! Thank you for your report, we've create internal ticket MAGETWO-58327 to fix this issue.

**Comment by H3dz** [comment]
Quick fix:

In:
- vendor/magento/module-paypal/view/frontend/web/template/payment/payflow-express.html
- vendor/magento/module-paypal/view/frontend/web/template/payment/paypal-express-in-context.html
- vendor/magento/module-paypal/view/frontend/web/template/payment/paypal-express.html

Replace
`<a data-bind="attr: {href: getPaymentAcceptanceMarkHref()}, click: showAcceptanceWindow"`

With
`<a data-bind="attr: {href: getPaymentAcceptanceMarkHref()}" target="_blank"`

Run:
- rm -rf pub/static
- php bin/magento setup:static-content:deploy

**Comment by michaeldyl520** [comment]
Please rewirte paypal-express-abstract.js
```
app/design/frontend/Magento/theme/Magento_Paypal/web/js/view/payment/method-renderer/paypal-express-abstract.js
in line 43:
change
$(event.target).attr('href') 
to
$(event.target).parent().attr('href')
```
You can resolve it.

**Comment by viktym** [comment]
Correct fix should be
`app/design/frontend/Magento/theme/Magento_Paypal/web/js/view/payment/method-renderer/paypal-express-abstract.js
in line 43:
change
$(event.target).attr('href') 
to
$(event.currentTarget).attr('href')`

**Comment by alena-marchenko** [comment]
Hi @gazzaf 

Fix for MAGETWO-58327 is merged to develop branch, closing the issue.
Thank you!

**Comment by ifeltsweet** [comment]
Why is it still broken in 2.1.8 if it was merged to develop in April?

**Comment by Ctucker9233** [comment]
@alena-marchenko Which version of 2.1 will this fix finally be included in?
