### ISSUE TITLE
Column names row_id and entity_id seem mixed up after upgrading to Magento2 EE 2.1 or 2.1.1 possibly due to catalog staging (module magento-catalog-staging)

### ISSUE THREAD

**Issue by malachy-mcconnell** [magento/magento2#6478]
### MySQL error message
- ERROR 1054: 1054: Unknown column 'entity_id' in 'NEW'
### SOLUTION
1. SOLUTION : set reindex mode to realtime (update on save). This deletes all the old triggers. Then set reindex mode to schedule (Update by Schedule)

### Preconditions

1. 'a normal setup' : linux, nginx, PHP 7.0.8, MySQL 5.6.31 (Ver 14.14)
2. Magento EE. Installed Magento 2.0, maybe updated a few times.
3. **Set the indexer mode to `scheduled`**
4. Was at 2.0.7 but then updated to 2.1.0 using `composer update` && `bin/magento setup:upgrade`.
5. Then 12 hours later updated to 2.1.1 also by `composer update` && `bin/magento setup:upgrade` (due to needing `base_grand_total` column in table `sales_invoice_grid`)
6. This is not a live site. There is no front-end traffic nor any admin use.
### Steps to reproduce

1. get some install of Mageneto 2.1.1
2. disable module Magento_CatalogStaging (and the modules that are dependent on it)
3. drop your entire DB schema
4. run `bin/magento setup:install` and `bin/magento setup:upgrade` to get a new DB created without the CatalogStaging module 
5. set the reindex mode to `schedule` for all indexers
6. observe the table `catalog_product_entity_int`. Note the column called `entiy_id`. **Note the triggers read `... VALUES (NEW.`entity_id`);`**
7. now enable module Magento_CatalogStaging (and enable its dependent set of modules)
8. `bin/magento setup:upgrade` 
9. **observe table `catalog_product_entity_int`. Note the column is now called `row_id` and not `entity_id` however the triggers still read `... VALUES (NEW.`entity_id`);`** which is incorrect and wreakign havoc on a number of process eg product import or if a backup of the DB is taken now, then the SQL dump cannot be re-imported into MySQL.
10. ROOT CAUSE: triggers referring to NEW.entity_id need to be deleted from some tables as part of some upgrade path
### Expected result

1. I think that after updating to Magento EE 2.1.1 when a column name is changed then any triggers referring to the column change need to be deleted and re-instated with the new column name.
### Actual result

1. The database is left in a broken state due to triggers referring to NEW.entity_id instead of NEW.row_id
### SOLUTION
1. SOLUTION : set reindex mode to realtime (update on save). This deletes all the old triggers. Then set reindex mode to schedule (Update by Schedule)
### Further observations
1. Recent backups of the database cannot be imported because the sql dump has the triggers containing `NEW.entity_id`
2. The triggers are created when the index mode is set to `scheduled` so this situation would affect any DB of a Magento install that has been set to index on schedule _before_ upgrading to 2.1. The fix is simple but not obvious : toggle the reindex to realtime (update on save) and then put it back to `schedule`. This clears the triggers and then recreates them with the new column name row_id as now required by the Magento_CatalogStaging module
3. Any time you care to disable or enable module Magento_CatalogStaging you will need to remember to toggle the reindexer state to update the triggers.

**Comment by malachy-mcconnell** [comment]
I have read more code. I am understanding more about the history and mechanism that leads to the SQL error message `ERROR 1054: 1054: Unknown column 'entity_id' in 'NEW'`

The triggers on table catalog_product_entity_int are created by the act of turning on or off the 're-index on schedule' flag. eg Magento Admin->System->Index Management->(select all)->(actions dropdown->Update by Schedule).
- Turn off 'reindex on schedule' => triggers are removed.
- Turn on 'reindex on schedule' => triggers are added.

**Comment by andimov** [comment]
@malachy-mcconnnell 
Thank you for reporting!
We already have internal ticket MAGETWO-56052  with the same problem, so I mentioned your report in that ticket.

**Comment by southerncomputer** [comment]
what was odd is that I went through 2.10 EE doing setup:upgrade and not until 2.1.1 came out did the staging database updates apply! 

Breaking changes between CE and EE should be more carefully noted in the future!

**Comment by josephmcdermott** [comment]
See PR https://github.com/magento/magento2/pull/10958, a very simple Command to automate the 'turning off and on again' of the indexers.

**Comment by josephmcdermott** [comment]
FYI this is resolved in develop branch:
https://github.com/magento/magento2/commit/78b796f1cf5df53e2883650cbbec7f36a53d1e8f

The install() method does the 'turn off and turn on' I was proposing, during every setup/install in the RecurringData class.

**Comment by orlangur** [comment]
Closing as the fix for this issue is already available on Magento 2.2.0 branch.

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

@josephmcdermott big thanks for your investigation!
