### ISSUE TITLE
Table Column Headings in Admin are not wrapping

### ISSUE THREAD

**Issue by TenzinNKhando** [magento/magento2#6479]
Issue:
Every table structure in my admin panel is messed up. The heading for all the columns are not wrapping together in one line. Each heading is showing on their own line. Better idea by looking at the image down below.

Setup:
1. Magento version 2.1.0
2. Theme: SM Market by MagenTech
### Expected result

1.  Expected to see the headings of each column on top of the table. 
### Actual result

![image](https://cloud.githubusercontent.com/assets/13293090/18219087/d226fbbe-711b-11e6-849d-6524db29d24f.png)

Also seeing these errors. Not sure if this is related to this but its a bug.
![image](https://cloud.githubusercontent.com/assets/13293090/18219094/e5aa42d6-711b-11e6-814a-33bee78aefe8.png)

**Comment by pboisvert** [comment]
Did you see this error prior to installing the 3rd party theme?

**Comment by PRAKASHSIVASANKAR** [comment]
this error is appear in your local server  or online server?

**Comment by TenzinNKhando** [comment]
This error appears after the theme was installed. I'm on the pursuit to see
what the theme developers have to say. Until then I will close this ticket.

**Comment by PRAKASHSIVASANKAR** [comment]
The same error i have face it on my online server but same file i will execute in local server not show this error. i fix this issue in online.

**Comment by TenzinNKhando** [comment]
The response I have gotten from the theme support is to re-deploy.

> Regarding your issue, please try to execute this command below:
> php bin/magento setup:static-content:deploy
> php bin/magento setup:upgrade
> php bin/magento indexer:reindex
> This hasn't worked.

@PRAKASHSIVASANKAR This is showing up on our online server. I'm curious as to how you fixed this?!?

**Comment by PRAKASHSIVASANKAR** [comment]
This My Code...

Just add the below code your .htaccess file

`<IfModule pagespeed_module> ModPagespeed off </IfModule>`

**Comment by TenzinNKhando** [comment]
@PRAKASHSIVASANKAR Thanks. That worked for me! also the "offset" bug disappeared too.
