### ISSUE TITLE
Blocked while placing order via Magento API due to Issue #6432

### ISSUE THREAD

**Issue by cshabnam** [magento/magento2#6480]
Magento version - 2.0.7
### Steps to reproduce

Step 1 --> http:///rest/default/V1/guest-carts -- 200 OK
Step 2 --> http:///rest/default/V1/guest-carts/{cart id}/items -- 200 OK
Step 3 --> http:///rest/default/V1/guest-carts/{cart id}/shipping-information – 200 OK
Step 4 --> http:///rest/default/V1/guest-carts/{cart id}/set-payment-information -- 400 Bad Request  - refer https://github.com/magento/magento2/issues/6432

Then How to complete the order placement. Please suggest a workaround.

**Comment by YevSent** [comment]
Closed as duplicate to https://github.com/magento/magento2/issues/6432 .
