### ISSUE TITLE
category page: We can't find products matching the selection

### ISSUE THREAD

**Issue by rbncha** [magento/magento2#6483]
After upgrading from 2.0.7 to 2.1.1, I am getting this message in product list page (category). After debugging I found out the join query had wrong website id for inventory. But then still it didn't list the products, there was something else maybe related to tmp search table. 

I'll be very thankful if you can help me solve it. My live store is destroyed.
### Preconditions

1. PHP Version 5.6.24
2. Magento 2.1.1
3. Database imported from 1.9.2.4 to 2.0.4 using data-migration-tool tool > upgraded to 2.0.7 > upgraded to 2.1.1
### Steps to reproduce

1. After upgrade, Admin > Catalog > Categories page gives 500 error
2. After upgrade, Go to Product list page in frontend
### Expected result

1. List of products with layered navigation
### Actual result

1. Message "We can't find products matching the selection"

**Comment by MorganGonzales** [comment]
Try to execute `php bin/magento indexer:reindex` on the project root directory.

**Comment by shiftedreality** [comment]
Hi @rbncha 

Did reindexing solved your problem?

**Comment by monhil** [comment]
reindexing solved the same issue on my category page. Thanks!

**Comment by rbncha** [comment]
@shiftedreality no reindexing didn't solve it.

**Comment by shiftedreality** [comment]
Hi @rbncha 

Please try to reproduce this issue on 2.1.2 after cleaning caches and reindexing.

**Comment by vzabaznov** [comment]
Hi @rbncha , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Comment by intersides** [comment]
any reason why reindexing should be done manually and after each new added entry ?

**Comment by anurag1209** [comment]
Try the following things:
1st reason:- Please check the following for your products
a) Product is out of stock
b) Product status is Disabled
c) Product visibility does not include Catalog
d) Product is not assigned to that particular website

2nd Reason:- Indexing Issue
Go to your root directory via terminal and run ===>>  php bin/magento indexer:reindex

3rd Reason:- Maybe one of the product is stuck via indexing
Go to the database and search for "indexer_state" table. Manually set status = "working" to "valid"/"invalid"

or run ===>>    update magento.indexer_state set status='invalid' where status ='working'

Thanks :)

**Comment by kamal2717** [comment]
> Try the following things:
> 1st reason:- Please check the following for your products
> a) Product is out of stock
> b) Product status is Disabled
> c) Product visibility does not include Catalog
> d) Product is not assigned to that particular website
> 
> 2nd Reason:- Indexing Issue
> Go to your root directory via terminal and run ===>> php bin/magento indexer:reindex
> 
> 3rd Reason:- Maybe one of the product is stuck via indexing
> Go to the database and search for "indexer_state" table. Manually set status = "working" to "valid"/"invalid"
> 
> or run ===>> update magento.indexer_state set status='invalid' where status ='working'
> 
> Thanks :)

I followed 1st reason and made changes, i jumped to 2nd Reason  and done re-indexing Its work for me now. Anurag KUDOS!

**Comment by mdiu12** [comment]
my magento 2.1.7 version is  We can't find products matching the selection. How can i solve the issues
