### ISSUE TITLE
Unable to save certain product properties via Rest API

### ISSUE THREAD

**Issue by cherreman** [magento/magento2#6486]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Create a product via the Rest API, including a price and weight
### Expected result

1. The product is saved with the price and weight
### Actual result

1. The price and weight are not saved and are not returned in the result of the POST request.

I traced this down to the BeforeEntitySave observer, where the price seems to be stripped off the product when $entity->beforeSave() is called. I did not continue research after that.

Workaround is to execute the post request again. During the update of the product, the price seems the be saved correctly.

**Comment by sevos1984** [comment]
Could you please attach payload of your request?

**Comment by cherreman** [comment]
**Request**

{
  "product": {
    "sku": "bugtest",
    "name": "bugtest",
    "price": 12.34,
    "attribute_set_id": 4
  }
}

**Response**

{
  "id": 5991,
  "sku": "bugtest",
  "name": "bugtest",
  "attribute_set_id": 4,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "created_at": "2016-09-06 13:46:56",
  "updated_at": "2016-09-06 13:46:56",
  "extension_attributes": {
    "stock_item": {
      "item_id": 5957,
      "product_id": 5991,
      "stock_id": 1,
      "qty": null,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": false,
      "low_stock_date": null,
      "is_decimal_divided": false,
      "stock_status_changed_auto": 0
    }
  },
  "product_links": [],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [],
  "custom_attributes": [
    {
      "attribute_code": "category_ids",
      "value": []
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "required_options",
      "value": "0"
    },
    {
      "attribute_code": "has_options",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "bugtest"
    }
  ]
}

**Response from second identical post**

{
  "id": 5991,
  "sku": "bugtest",
  "name": "bugtest",
  "attribute_set_id": 4,
  "price": 12.34,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "created_at": "2016-09-06 13:46:56",
  "updated_at": "2016-09-06 13:46:56",
  "extension_attributes": {
    "stock_item": {
      "item_id": 5957,
      "product_id": 5991,
      "stock_id": 1,
      "qty": null,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": false,
      "low_stock_date": "2016-09-06 13:48:37",
      "is_decimal_divided": false,
      "stock_status_changed_auto": 0
    }
  },
  "product_links": [],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [],
  "custom_attributes": [
    {
      "attribute_code": "category_ids",
      "value": []
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "required_options",
      "value": "0"
    },
    {
      "attribute_code": "has_options",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "bugtest"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    }
  ]
}

**Comment by sevos1984** [comment]
This happens when product type_id field is not defined. Created internal ticket MAGETWO-58101. Thanks for reporting.

**Comment by cherreman** [comment]
Thanks for the heads up!

**Comment by magento-engcom-team** [comment]
@cherreman, thank you for your report.
We've created internal ticket(s) MAGETWO-58101 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @cherreman. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1018 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - fa6782f3a22f1185ebd4e71e915962f2a57c199f
 - 9db02736120ce911f670e2a1f31efef5435aca7c
 - 1d37cce45ac025929277dcdbeb44f1889564b23a
 - de673880b16ae39cb4fe5e325f747a9f05b735c1
 - d132c7ec62baccae9ee5ac4272eba2a7d9fdc8e8

The fix will be available with the upcoming patch release.
