### ISSUE TITLE
messages.js breaks minicart item count update in mixed HTTP/HTTPS mode

### ISSUE THREAD

**Issue by torbre16** [magento/magento2#6487]
### Preconditions
1. Magento 2.1.0 (also all release candidates), Magento 2.1.1
### Steps to reproduce
1. Use Magento in mixed HTTP/HTTPS mode (i. e. unsecure base URL uses HTTP, secure base URL uses HTTPS)
2. Add a product to the cart on a product details page
3. Go to the cart page and change the quantity of the previously added product
4. Go back to the product details page (reload it). Sporadically, the number of items in the minicart is not updated correctly.
### Expected result
1. Show the correct number of items in the minicart both on HTTPS and HTTP pages.
### Actual result
1. Sporadically, the number of items in the minicart is not updated correctly when switching between HTTP and HTTPS pages.
### Root cause

The number of items in the minicart is stored in the browser's local storage. As the browser has different local storages for HTTP and HTTPS pages, Magento uses a 'section_data_ids' cookie to remember what local storage keys to invalidate (this is all performed in `module-customer/view/frontend/web/js/customer-data.js`).

The file `module-theme/view/frontend/web/js/view/messages.js` sets the `expires` parameter of the cookie storage globally to `-1` in the `initialize` method. Effectively, this disables the cookie storage feature completely in case a new cookie is set via `$.cookieStorage`, and thus also breaks `$.cookieStorage.set('section_data_ids', [...]);` which is used to update the number of items in the minicart.

In our case, it helped to change the line

`$.cookieStorage.setConf({path: '/', expires: -1}).set('mage-messages', null);`

in `module-theme/view/frontend/web/js/view/messages.js` to

`$.cookieStorage.setConf({path: '/'}).set('mage-messages', null);`

to fix the issue, but I am not completely sure if this breaks something else in regards to the error message handling (not sure why the `expires` parameter has been set to `-1` originally).

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-58182. Thanks for reporting

**Comment by sdzhepa** [comment]
@torbre16
 Fix for this issue was delivered to develop branch. Pls feel free to check it in develop and reopen if need
- Fix for Magento 2.1 will be delivered late in scope of internal ticket `MAGETWO-59211`
- Fix for Magento 2.0 will be delivered late in scope of internal ticket `MAGETWO-59209`

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 as of today.
