### ISSUE TITLE
Able to move forward without shipping address in checkout

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#6488]
Title : Able to move forward without shipping address in checkout 

Preconditions ;
1)  Magento CE 2.1 without sample data is installed.
2) Customer is Login
3) Customer have address

How to generate issue:
Add any product into cart and then go to checkout, and now unselect address from selected address and click on next button.

**Comment by andimov** [comment]
@sunilit42 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by sunilit42** [comment]
Preconditions

Magento CE 2.1 without sample data is installed. 

Steps to reproduce
1) Customer must be login
2) Customer have only one address
3) Unselect the address on checkout and click on next button 

Expected result
Customer can not able to move to next step without selecting customer address.

Actual result
There should be validation for that, without address selection can not able to move next step.

**Comment by pboisvert** [comment]
where does the shopper think the order is going to be sent if they try to proceed with no address? So i agree this is a bug and we should prevent but struggle a bit to understand why a shopper would be actively trying to checkout with putting in an address. 

[update] Is the concern here around fraudulent orders? Someone trying to place an order and saying no cost of shipping was presented?

**Comment by sunilit42** [comment]
@andimov any news on this issue?

**Comment by toddliningerdesign** [comment]
@pboisvert I don't think it would be intentional as much as just a mistake on the customer's part. If their saved address is already displayed they may not realize they need to select it.

**Comment by pboisvert** [comment]
ok--that would be a UX issue. If one address on file there is no reason why it shouldn't be pre-selected such that they do not need to explicitly select.

**Comment by sunilit42** [comment]
@pboisvert  if there is only one address then it should be selected and customer can not do unselect then it will solve our issue

**Comment by SerhiyShkolyarenko** [comment]
@sunilit42 thank you for reporting. Our internal issue is MAGETWO-58673.

**Comment by Frits1980** [comment]
And maybe even select the last used address if their are multiple once.
And still validate if none is selected. Now I can process but at payment get an exception because their is no address...

Anyone have a workaround yet? Old issue.

**Comment by KrystynaKabannyk** [comment]
Fix will be provided under MAGETWO-64544 (MAGETWO-58673 is closed as duplicate).

**Comment by veloraven** [comment]
Original internal ticket was closed as a duplicate.
New internal ticket for ver. 2.1 - MAGETWO-64069

**Comment by mattgreenfield** [comment]
Based on the above change of status, is this fixed? If so how can I get the fix please?

**Comment by magento-engcom-team** [comment]
@sunilit42, @mattgreenfield thank you for your report.
The fix for this issue is already available in the develop branch and upcoming 2.2.0 release. Please see [commits](https://github.com/magento/magento2/search?q=MAGETWO-64544&type=Commits) which mention `MAGETWO-64544`.

**Comment by dakira** [comment]
@magento-engcom-team what commit fixed this? We need a backport for 2.1. We're currently getting several orders without shipping information on a production server, which is really really bad.

**Comment by nbennett25** [comment]
@magento-engcom-team we are still seeing this issue with 2.2.4 - customer has a single address, set as default billing and shipping address, yet the customer was able to place an order that does not have a shipping address.

**Comment by dakira** [comment]
@nbennett25 For us, somehow people were able to create products with 0 weight which were automatically converted to virtual products which don't need shipping. So maybe check the product the customer ordered.
