### ISSUE TITLE
Unable to connect to Magento Marketplace from Web Setup Wizard

### ISSUE THREAD

**Issue by AnastasiyaSAP** [magento/magento2#6489]
### Preconditions:
1. I have installed Magento 2.1 on my OS X and unable to connect to Magento Market Place from my System --> Web Setup Wizard. 
2. Magento Community 2.1.0 without sample data is installed.
3. I have created a Magento Marketplace account and generated a key under My Account--> Marketplace --> My Access Keys
### Steps to reproduce:
1. Logged in as admin user into Magento admin panel, I navigate to System--> Web Setup Wizard
2. It give me 3 options: Component Manager, System Upgrade, System Configuration
3. First clicking on System Configuration, Magento market Plcae private and public keys are inserted and pressed for Save Config --> Message 'Credentials Saved'
### Actual results:

Then when navigated to component manager, sign in and inserted the same public and private key, and pressed 'sign in' --> it hybernates for 2 seconds and nothing happens. 

This is the response I get response for save-auth-json when trying to login: 

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
### Expected result

I should be able to synchronize my magento installation with magento marketplace.

It would be great if anyone has any ideas why this is happening and how to solve it

**Comment by andimov** [comment]
@AnastasiyaSAP 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by AnastasiyaSAP** [comment]
@andimov Hopefully this should be ok? I am not sure what else to add.

Thanks

**Comment by andimov** [comment]
@AnastasiyaSAP 
Thank you, now it's ok.
Did you set 'always_populate_raw_post_data' to '-1' in php.ini?

**Comment by AnastasiyaSAP** [comment]
@andimov just did the above. Restarted apache too. that didn't work

**Comment by shiftedreality** [comment]
Hi @AnastasiyaSAP 

What is your PHP version?

**Comment by AnastasiyaSAP** [comment]
@shiftedreality 

PHP 5.6.25 (cli) (built: Aug 21 2016 17:32:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

Server version: Apache/2.4.18 (Unix)
Server built:   Feb 20 2016 20:03:19

**Comment by shiftedreality** [comment]
@AnastasiyaSAP is it possible that you're using PHP 5.5 for Apache as default on Mac?

Could you please check /etc/apache2/httpd.conf what is your lib in line "LoadModule php5..."

**Comment by AnastasiyaSAP** [comment]
@shiftedreality 
LoadModule php5_module /usr/local/Cellar/php56/5.6.25_1/libexec/apache2/libphp5.so 

I had already configured it to point to 5.6

**Comment by shiftedreality** [comment]
@AnastasiyaSAP, this path looks correct.

Can you also show which path to php.ini do you use and double check that 'always_populate_raw_post_data' to '-1' was really applied?

**Comment by AnastasiyaSAP** [comment]
@shiftedreality 
OK - I appear to have changed a different php.ini file to the one that the command line was using. After finding out the path to the correct php.ini I saw that always_populate_raw_post_data was indeed commented out. We have uncommented it and now all is working. Thank you so much!!!

**Comment by shiftedreality** [comment]
Thank you @AnastasiyaSAP for the reply.

Closed.
