### ISSUE TITLE
Suggestion: Category Image resize

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#649]
I have a suggestion. 
Right now the image associated to the category is used in frontend as it is:

     $url = $this->_storeManager->getStore()->getBaseUrl(
                \Magento\Framework\UrlInterface::URL_TYPE_MEDIA
            ) . 'catalog/category/' . $image;

How about making it resizeable as the product images are?  
Here is a use case when this might be needed:  
One category has the layout 2-columns left. 
I have one image that fits in this format.  
I take the decision to change the layout for that specific category to 3columns.  I have to reupload an image in the correct size, to fit in the new layout. 

But if the image was resizeable, I could just change the resize values.  
The resize values can even be 2 attributes in the backend, so when I change the layout I can change the width and height as well.  

If these attributes are empty then the image is shown at full size.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28058

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Suggestion-Category-Image-resize/idi-p/47164).

**Comment by jalogut** [comment]
I needed exactly that for a project. Also noticed that it would be very convenient to easily resize images on our custom and third party modules depending on the Project design. For that reason, we created a module to resize images just calling a method.
You can check it out here:
https://github.com/staempfli/magento2-module-image-resizer

**Comment by PieterCappelle** [comment]
Thank you @jalogut for your extension. Is working very well.

**Comment by jalogut** [comment]
@PieterCappelle you're welcome. Happy to help. I am glad that people use it :)
