### ISSUE TITLE
Magento 2.1.1. Newly created customers or by frontend or by WEB-API are not visible in the Backend

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#6490]
We have created  a customer by WebAPi, we receive a response and the record is available in the database. The record doesn't appear in the Magento backend.

We did another test by creating an account on the front-end. When this customer is saved it is in table 'customer_entity' , but not visible in the Magento backend.

Refreshing cache doesn't help.

Magento 2.1.1. default install
PHP 5.6.16
MySQL 5.7.9

**Comment by jzahedieh** [comment]
Have you reindex the customer data?

Try `magento indexer:reindex customer_grid`

**Comment by ericahoekerd** [comment]
yes thanks by running the index is working and the customers are visible, this is different behaviour then the previous versions, new customers should always immediateley visible in the backend

**Comment by andimov** [comment]
@tinxit 
Thank you for reporting this issue!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
