### ISSUE TITLE
how t install a template

### ISSUE THREAD

**Issue by rahulsappzorro** [magento/magento2#6491]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by andimov** [comment]
@rahulsappzorro 
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
