### ISSUE TITLE
ProductRepository::getList returns no items

### ISSUE THREAD

**Issue by R4c00n** [magento/magento2#6494]
### Preconditions

Magento Version 2.1
PHP 7.0

I'm, trying to get all products with the `ProductRepository`, but I only get an empty array.

When accessing the `/rest/V1/products?searchCriteria=` REST endpoint, I get the a non-empty array.

For test reasons I added `$product = $this->productRepository->getById(1);` and this returns me the correct product with the id `1`.
### Steps to reproduce

``` php
namespace StackOverflow\Lib;

use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Framework\Api\SearchCriteriaBuilder;

class Demo {
    public function __construct(
        ProductRepositoryInterface $productRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder
    ) {
        $this->productRepository = $productRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
    }

    public function execute() {
        $searchCriteria = $this->searchCriteriaBuilder
            ->create();
        $products = $this->productRepository->getList($searchCriteria)
            ->getItems();
        $product = $this->productRepository->getById(1); // This returns the correct product

        var_dump($products);
    }
}
```
### Expected result

What I expected is an array of Products.

``` php
[ProductInterface]
```
### Actual result

What I got is an empty array

``` php
[]
```

**Comment by R4c00n** [comment]
Is this a bug in Magento or am I doing something wrong?

**Comment by tmvnk** [comment]
Hi, have you found an solution maybe for this issue? @R4c00n 

When using the productRepository via getList I noticed getMediaGalleryEntries() always return NULL  and other info like getId or getName works..
When I use $this->productRepository->getById(1) for example getMediaGalleryEntries() is correct.

**Comment by magento-engcom-team** [comment]
@R4c00n, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
