### ISSUE TITLE
Recently Viewed Products

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#6496]
Hi,

I am using Magento version 2.0.9 price not showing for configurable products

Template file 
Magento_Reports/templates/widget/viewed/content/viewed_grid.phtml

Original File 

/vendor/magento/module-reports/view/frontend/templates/widget/viewed/content/viewed_grid.phtml

**Comment by andimov** [comment]
@ednacool 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
