### ISSUE TITLE
Translations export error [DomainException] Missed Phrase

### ISSUE THREAD

**Issue by skhell** [magento/magento2#6498]
### Preconditions

1. Magento 2.1.0
### Steps to reproduce

1. Login to SSH
2. Switch to user who own Magento directory rights 
3. cd /var/html/magento/bin
4. php magento i18n:collect-phrases -o "/var/html/magento/translation_export.csv" -m
### Expected result

1. Export the CSV file with English base translations to allow me to translate them in my own language.
### Actual result

1. DomainException Missed Phrase

Unfortunately is really hard from the output to understand what file is blocking the export, I have also checked the log folder (var/log) but there is no trace of this error.

![screen shot 2016-09-05 at 16 10 22](https://cloud.githubusercontent.com/assets/20488700/18250479/feb40284-7383-11e6-880d-e84461950538.png)

**Comment by sevos1984** [comment]
I'm getting 'Dictionary successfully processed.' on clean magento. Problem must be in your language pack. Try add '-vvv' option to see broken file.

**Comment by skhell** [comment]
@sevos1984 thanks for the suggestion, I tried adding -vvv and this is the result

>   [DomainException]  
>   Missed phrase      
> 
> Exception trace:
>  () at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php:90
>  Magento\Setup\Module\I18n\Dictionary\Phrase->setPhrase() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php:73
>  Magento\Setup\Module\I18n\Dictionary\Phrase->__construct() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Factory.php:69
>  Magento\Setup\Module\I18n\Factory->createPhrase() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Parser/Contextual.php:79
>  Magento\Setup\Module\I18n\Parser\Contextual->_addPhrase() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Parser/Contextual.php:51
>  Magento\Setup\Module\I18n\Parser\Contextual->_parseByTypeOptions() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Parser/AbstractParser.php:75
>  Magento\Setup\Module\I18n\Parser\AbstractParser->parse() at /var/html/magento/setup/src/Magento/Setup/Module/I18n/Dictionary/Generator.php:83
>  Magento\Setup\Module\I18n\Dictionary\Generator->generate() at /var/html/magento/setup/src/Magento/Setup/Console/Command/I18nCollectPhrasesCommand.php:77
>  Magento\Setup\Console\Command\I18nCollectPhrasesCommand->execute() at /var/html/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
>  Symfony\Component\Console\Command\Command->run() at /var/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php:874
>  Symfony\Component\Console\Application->doRunCommand() at /var/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php:195
>  Symfony\Component\Console\Application->doRun() at /var/html/magento/vendor/magento/framework/Console/Cli.php:96
>  Magento\Framework\Console\Cli->doRun() at /var/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php:126
>  Symfony\Component\Console\Application->run() at /var/html/magento/bin/magento:23
> 
> i18n:collect-phrases [-o|--output="..."] [-m|--magento] [directory]

**Comment by sevos1984** [comment]
I've recreated your issue, it occurs when you have empty strings for translation (e.g 'note' => __('')).

**Comment by skhell** [comment]
Ah, so perhaps somewhere in the template I have empty translation strings? There is a command to output the file containing empty strings? Thanks

**Comment by sevos1984** [comment]
Yes, check your templates. No there is no such command.

**Comment by skhell** [comment]
@sevos1984 thank you very much for the suggestion infact there was a missing translation that I found, now the export works correctly, I close this post as solved.

**Comment by gediminaskv** [comment]
Hello, I have the same issue. Where I can find "empty strings" ? No translations where done, so, from where those empty strings come?
Anyway, it's quite a strange thing because very first time when I ran collect-phrases everything was fine, but now it shows "missed phrase"...

**Comment by benheart** [comment]
@gediminaskv Maybe you can modify setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php file, and comment the DomainException in setPhrase() and setTranslation() methods like this:
```
    public function setPhrase($phrase)
    {
        if (!$phrase) {
//            throw new \DomainException('Missed phrase');
            $this->_phrase = 'Missed phrase';
        } else {
            $this->_phrase = $phrase;
        }
    }
```
```
    public function setTranslation($translation)
    {
        if (!$translation) {
//            throw new \DomainException('Missed translation');
            $this->_translation = 'Missed translation';
        } else {
            $this->_translation = $translation;
        }
    }
```
And this will create .csv successfully, what's more, you can find the module of the "empty strings".

**Comment by nei** [comment]
__('0'); also fails.

**Comment by webspeaks** [comment]
Magento should be able to handle empty phrases. I dont understand why do they not handle such small things.
Such issues cause developers to loose many hours.

**Comment by TimQSO** [comment]
Agreed with @webspeaks tranlating is already a pain in M2, this makes it even worse.

**Comment by TimQSO** [comment]
Err I did not unassign @sevos1984 ?

**Comment by c1gee** [comment]
> Yes, check your templates. No there is no such command.

There is no such command but there is a search that works

Run this in your root folder to find all of the missing  / empty strings

`grep -rnw . -e "__('')" -e '__("")' `

I have used this successfully several times.  

I also like to email the plugin providers to let them know when they have missed a couple.
