### ISSUE TITLE
Translate attributes on system.xml files

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#650]
It seams to me that the `translate`  attribute on elements inside the `system.xml` files is useless and it should be removed.  
From what I found in the code, the labels and comments are translated anyway in `Magento\Backend\Model\Config\Structure\AbstractElement`.  
I also removed for test purposes the `translate` attribute from an element, change the translation for that text from the `i18n` folder and in the backend I got the translated version of the text.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28204

**Comment by piotrekkaminski** [comment]
We will be using an external tool to work on translations. We might then later push them to git or keep separate  - not decided yet. Look for announcement soon.
