### ISSUE TITLE
Can't save Logo Image to Transactional Emails

### ISSUE THREAD

**Issue by bachlee89** [magento/magento2#6502]
On the Magento version 2.1.0 and 2.1.1
I can't save Logo Image to Transactionsal Emails after upload from my local
Steps to reproduce
1. Go to Backend area : Content/Design/Configuration
2. Edit a Store View
3. Scroll to Transactional Emails
4. Click upload logo image then select a image from your computer

Expected result
- Logo image should be saved

Actual result

Image can't uploaded:
![image](https://cloud.githubusercontent.com/assets/5562316/18262170/50cb56da-7429-11e6-901e-3468e28bbc89.png)

Please solve. Thanks

**Comment by pboisvert** [comment]
appears to be a duplicate of #6275  please reopen if truly a separate issue

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
