### ISSUE TITLE
Magento 2.1 CE: Breadcrumbs on homepage and 404 in multistore

### ISSUE THREAD

**Issue by PingusPepan** [magento/magento2#6504]
In Magento 2.1 there is a bug when using multistore and setting different home pages for different store views.
The first store looks fine but second and other store views include breadcrumbs in home page.
I created PR #6503 with a fix
### Preconditions
1. Magento 2.1.1 CE
2. Multistore
3. PHP 7.0.10
### Steps to reproduce
1. Create multiple store views
2. Create multiple home pages for different store views with same identificators (url keys)
3. Assign home pages to store views
### Expected result
1. Each store view home page and 404 page contains no breadcrumbs
### Actual result
1. First homepage contains no breadcrumbs
2. Each other homepage contains breadcrumbs

**Comment by sevos1984** [comment]
I have this problem if I set Design>Layout>Empty to any page in any store. Could you try set some other layout than empty?

**Comment by PingusPepan** [comment]
I am not sure if I have any pages with Design>Layout>Empty. I will have to check tomorrow. Did you look at the PR? That's the fix I used and it works even though I have not edited any page yet.

**Comment by PingusPepan** [comment]
I had two pages with empty layouts and I set them to other layouts. None of the pages were the ones I was having the breadcrumbs problem at. As expected, nothing has changed because the bug is already fixed by applying PR #6503

**Comment by sevos1984** [comment]
Fixed in https://github.com/magento/magento2/pull/6503
