### ISSUE TITLE
Admin Navigation

### ISSUE THREAD

**Issue by arfan456** [magento/magento2#6505]
Admin Navigation linkes are not working

**Comment by andimov** [comment]
@arfan456
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
