### ISSUE TITLE
Admin > Sales > Order: Grid's "Purchase Date" column has wrong times

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6509]
### Preconditions
1. CE 2.1.1
### Steps to reproduce
1. make an order
2. go to admin sales order listing
### Expected result
1. "Purchase Date" should show the correct order date
### Actual result
1. "Purchase Date" shows the correct day, month and year, but time is `xx:09:00`

![image](https://cloud.githubusercontent.com/assets/299636/18279151/cbc02638-7454-11e6-9a0d-c755cf10b53f.png)

real order date of first order in this listing:

![image](https://cloud.githubusercontent.com/assets/299636/18279168/df1256e8-7454-11e6-86c8-0748a81ce370.png)

**Comment by lucscu** [comment]
[Known bug](https://github.com/magento/magento2/issues/5651)
In `app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml` change dateFormat to
`<item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:mm:ss A</item>`

**Comment by heldchen** [comment]
thanks @LucScu I'm closing this one and subscribing to the other issue.

**Comment by bwilmus** [comment]
Hi,

This file has moved to: 
/vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_grid.xml

Do not forget to clear cache after modification of XML file.

**Comment by twistedatrocity** [comment]
The correct format is for non 24 hour time is:
`<item name="dateFormat" xsi:type="string">MMM dd, YYYY, h:mm:ss A</item>`

Note the lower case h for hours.... if upper case you get 24 hour format, if lower case, non 24 hour.

**Comment by goswamimehul** [comment]
This works fine in vendor folder but I am not able to extend /vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_grid.xml. can anyone help me to override this xml.

**Comment by SilvanLaroo** [comment]
I also want to now how to fix this issue without changing core files.

**Comment by nigelcopley** [comment]
Since upgrading to 2.1.7 my fix for this (extending the xml) does not work.  This was a bug a few versions back that should have been fixed, it's not exactly a big job

**Comment by gabriel-sf** [comment]
Is there any update on this without having to change core files?

**Comment by andidhouse** [comment]
why is that one closed? This is present in 2.1.7 - wow what a bug again. I do not know what standards the magento2 team is using...

**Comment by ZenDevMaster** [comment]
still a bug in 2.1.8
