### ISSUE TITLE
After migration from 1.9.2.2 to 2.1.1 - Cannot edit customers

### ISSUE THREAD

**Issue by daschenbrener** [magento/magento2#6510]
performed an upgrade from 1.9.2.2 to 2.1.1 and the migration was successful.

But now when i try to go into the admin side, and edit it customer, the page gives me a error and the magento screen of death. (lol)
### Preconditions

magento 2.1.1
migrated from 1.9.2.2 to 2.1.0 , using the data migration tools
php 7
mariadb 10.1.14
Ubuntu 16.04
### Actual result

here is the first line of the error report

> a:4:{i:0;s:89:"The requested component ("") is not found. Before using, you must add the implementation.";i:1;s:8481:"#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-ui/Model/Manager.php(207): Magento\Framework\View\Element\UiComponent\Config\Provider\Component\Definition->getComponentData('')

Attached is the full error report

[error on no customer display.txt](https://github.com/magento/magento2/files/457276/error.on.no.customer.display.txt)

**Comment by daschenbrener** [comment]
not sure if this is related to this also: #5873

**Comment by daschenbrener** [comment]
is there anyplace where we can see a roadmap or a time that a new update may be released @andimov @mage-core-team

**Comment by victor-v-rad** [comment]
Hi @daschenbrener 
It is hard to figure out the cause of the issue
You could share DB dump (remove all passwords before) of Magento 1 and send it through email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it to reproduce and fix

**Comment by daschenbrener** [comment]
the db is about 6GB, but what might work better is getting you the login and password of the server that this is setup on,

**Comment by daschenbrener** [comment]
or just let me know what would work the best @victor-v-rad

**Comment by victor-v-rad** [comment]
Let's discuss it in skype rad_victor is my

**Comment by victor-v-rad** [comment]
It's the end of my working day. We will get in touch on Monday.

**Comment by daschenbrener** [comment]
ok sounds good then, im just tied up for a bit yet

**Comment by victor-v-rad** [comment]
Do you still have the issue? Feel free to connect with me through skype

**Comment by daschenbrener** [comment]
I do sorry for the delay, ill try to touch base with you tomorrow (Tues) my timezone is MST (-7 GMT)

**Comment by victor-v-rad** [comment]
Hi @daschenbrener 
The reason of the issue is in attribute with code webtoprint_template. Most likely it is from some extension. In particular in eav_attribute table the webtoprint_template record has empty frontend_input field. This cause the error you have.

**Comment by magento-engcom-team** [comment]
Thank you for the report. The issue has been resolved

**Comment by BabliDey** [comment]
I am having the same issue when editing or adding a nwe customer from admin section.
Preconditions
magento 2.1.8
php 7.0.26

Actual result
here is the first line of the error report

a:4:{i:0;s:94:"The requested component ("label") is not found. Before using, you must add the implementation.";i:1;s:8248:"
[396832650227.txt](https://github.com/magento/magento2/files/1789614/396832650227.txt)


Attached is the full error report
