### ISSUE TITLE
Cant create new Products in 2.1.1

### ISSUE THREAD

**Issue by pynej** [magento/magento2#6513]
Clicking Add Product brings up the new window, but the screen is locked with a spinning wheel that never goes away.
### Preconditions

1. v2.1.1
2. Php 5.6
### Steps to reproduce

1. Update from 2.0.x to 2.1.1
2. Go to Catalog and create a new product
### Expected result

1. Editable screen
### Actual result

1. Spinning wheel, following console error.

`Uncaught TypeError: Cannot read property 'replace' of null  import-handler.js:140`
![screen shot 2016-09-06 at 4 37 57 pm](https://cloud.githubusercontent.com/assets/458367/18290161/6c57b098-7450-11e6-92ca-56e41e40cd04.png)

**Comment by pynej** [comment]
Fix for null this.mask.

```
--- vendor/magento/module-catalog/view/adminhtml/web/js/components/import-handler.js.orig   2016-08-25 22:47:02.000000000 -0400
+++ vendor/magento/module-catalog/view/adminhtml/web/js/components/import-handler.js    2016-09-06 16:21:48.637131000 -0400
@@ -137,7 +137,7 @@
                 if (this.values.hasOwnProperty(property)) {
                     placeholder = '';
                     placeholder = placeholder.concat('{{', property, '}}');
-                    str = str.replace(placeholder, this.values[property]);
+                    str = str ?  str.replace(placeholder, this.values[property]) : str;
                     nonEmptyValueFlag = nonEmptyValueFlag || !!this.values[property];
                 }
             }
```

**Comment by terrybakshi** [comment]
And The New products are not showing in the front end, can't find to fix this issue.

**Comment by terrybakshi** [comment]
when i run the command: php bin/magento indexer:reindex all the products show but after when i go to add new product they don't show, i can't keep running command after adding every new product. I think its a Bug in this version

**Comment by pynej** [comment]
Your crib job that rebuilds the index is probably broken. I had to add a missing xsl module to my pho when I updated to 2.1. Check your logs.

**Comment by pynej** [comment]
Also you can add a php script to force reindex from the browser seeing as how they do t have a button in the admin UI.

**Comment by terrybakshi** [comment]
ok found the issue and fixed it, now its all working in the index management i changed to index on save so all the products are showing now as soon as the product is added, before it was set on index on schedule which basically sets to update on cron job, so if the cron job is running once a week the re indexing will occur once a week only.

Thanks

**Comment by sevos1984** [comment]
Since issue is resolved I'm closing it.
