### ISSUE TITLE
Newly created website,store,storeview not listed in Content-->Design-->Configuration

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#6516]
### Preconditions

1. Magento 2.1 , Nginx, Php-fpm 5.6, opcache
### Steps to reproduce

1. Create a new website, store, storeview
2. Navigate to Content --> Design --> Configuration
### Expected result

1. Newly created website,store,storeview should be listed to enable us to change theme.
### Actual result

1. Not listed

**As a workaround, click any of the listed line item in there without changing anything Click Save**
**Newly created website,store,storeview will be listed now**

**Comment by sevos1984** [comment]
After adding website indexer should be run, or cron should be configured as said here http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html. This is expected behavior.
