### ISSUE TITLE
Deploy Sample Data Content to app/code folder instead of vendor

### ISSUE THREAD

**Issue by anarbayramov** [magento/magento2#6517]
Hello, 

I can deploy sample data to vendor folder with with the command  `bin/magento sampledata:deploy` 
however I want to edit this command to deploy sample data to app/code/magento folder instead of vendor.

**Comment by andimov** [comment]
@rodrane
Thanks for reporting. 
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by danslo** [comment]
Why?

**Comment by anarbayramov** [comment]
Because I'm using docker with only app code folder shared. I'm having performance issues with all files synchroned. So I want to edit sample files without login via ssh to my docker image everytime

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
