### ISSUE TITLE
Error price in product page with Tier price and Configurable product

### ISSUE THREAD

**Issue by webagil-kevin** [magento/magento2#6519]
### Preconditions
1. Magento 2.1.0 or 2.1.1
2. Theme Blank or Luma
3. Configurable product with 2 attributes
### Steps to reproduce
1. Sample date installed
2. Add Tier Price for a specific Customer Group

Example for "Inez Full Zip Jacket-XS-Orange", default price is 59,00 € and add  Tier Price:
![tier-price-02](https://cloud.githubusercontent.com/assets/9626689/18306289/6dc67676-74eb-11e6-8107-969903bb7d8c.jpg)
### Expected result
1. In product page, for other customer groups (Not Logged in, General...) show default price 59,00 €.
### Actual result
1. In product page, Wholesaler price configured in Tier Price show for all groups and Not Logged in. Price is ok in Shopping Cart.
   ![tier-price-01](https://cloud.githubusercontent.com/assets/9626689/18306421/112618a8-74ec-11e6-96cd-69d2983b6555.jpg)

**Comment by sevos1984** [comment]
This duplicates https://github.com/magento/magento2/issues/3759 and https://github.com/magento/magento2/issues/5064
