### ISSUE TITLE
\Magento\Ui\Component\Listing\Columns\Column has access to all grid columns

### ISSUE THREAD

**Issue by Dublerq** [magento/magento2#6525]
You can use an extended column class instead of the default `\Magento\Ui\Component\Listing\Columns\Column` in a grid ui component which is great. Less great thing is that when you set a custom class for one column like:

```
<column name="required" class="\Vendor\ModuleName\Ui\Component\Listing\Column\Yesno">
```

In `public function prepareDataSource(array $dataSource)` you get unlimited access to data of all columns.

### Preconditions

1. Tested on Magento 2.1.1
### Steps to reproduce

1. Create an extended column class
2. Dump content of $dataSource in method `public function prepareDataSource(array $dataSource)`
### Expected result
1. An array with element related only to this certain column
### Actual result

1. An array with full access to all data columns.

I just hope that programmers will not overuse this access and keep their code clean.

> Note: changing this behavior may brake many already existing scripts

**Comment by heldchen** [comment]
how would one specify which data elements are needed for this column?  and in this case, what is keeping someone from requesting all columns? in my case, we have some extra columns that depend on other data than just the field that they are representing...

**Comment by Dublerq** [comment]
> how would one specify which data elements are needed for this column?

It should pass only the data of that one column, or give read only access to all columns and r/w to data from specified one.

> and in this case, what is keeping someone from requesting all columns? in my case, we have some extra columns that depend on other data than just the field that they are representing...

It's ok to have read access to other columns, but no the write one. Editing other columns data in class of that specified, one column is a terrible feature leading to badly written code and total mess when overused.

**Comment by magento-engcom-team** [comment]
@Dublerq, thank you for your report.
We've created internal ticket(s) MAGETWO-84572 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@Dublerq, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
