### ISSUE TITLE
PDO DSN generation failes when initStatement contains ;

### ISSUE THREAD

**Issue by tomvlk** [magento/magento2#6526]
### Preconditions

1. Install Magento2 with setup (MySQL), don't change default initStatement.
### Steps to reproduce

1. Edit the `app/etc/env.php`.
2. Change the order of the default db connection configuration.
3. Make sure that `initStatement` is the upper most entry.
4. Reload page or run CLI tool.
### Expected result

1. Working site with selected DB.
### Actual result

1. The DSN will contain the initStatement with `;` sign. Resulting in:

```
mysql:host=localhost;model=mysql4;active=1;initStatements=SET NAMES utf8;;dbname=test_db;engine=innodb;type=pdo_mysql
```

The problem will be between the `initStatements=` and the `dbname=`. The dubble semicolon will result in ignoring everything after it.

By default the Magento setup will add initStatements with the semicolon on the end, which is the failt. The only reason why it isn't failing on all environments is order of the env.php array which will ignore nothing on the end of the generated DSN.

This affects Magento 2.1.1 and (not yet tested) everything < 2.1.1.

**Comment by sevos1984** [comment]
Why do you need to change order of configurations?

**Comment by tomvlk** [comment]
@sevos1984 Because there are deployment tools out there that use un-ordered lists (language limitations) and will output it in a random order. For such environments, it's possible to implement a workaround at the deployment side. But this is definitely a bug with the default value of the initStatements.

It's good configured in your tests (https://github.com/magento/magento2/blob/f2d309a88298886460351c04973a4ff95c7a91c0/lib/internal/Magento/Framework/Model/Test/Unit/ResourceModel/Type/Db/Pdo/MysqlTest.php#L57) but in the default setup config it's including the semicolon which can, together with a different order, result in a exception.

**Comment by sevos1984** [comment]
Thanks for clarification, internal ticket created MAGETWO-58326

**Comment by magento-engcom-team** [comment]
@tomvlk, thank you for your report.
We've created internal ticket(s) MAGETWO-58326 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tomvlk, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by Hailong** [comment]
I'd suggested a PR to fix this issue, since it's kind of a common issue. https://github.com/magento/zf1/pull/24
