### ISSUE TITLE
Instaling magento from command line errors

### ISSUE THREAD

**Issue by caneraydinbey** [magento/magento2#6527]
I follow this guide.

http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html

I tried to run web installatin but it always got stucked so now i try this.

when i go to mysql as root

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0,00 sec)
```

there are not any tables for magento.

So i run this command given in the link

```
magento setup:install --base-url=http://127.0.0.1/magento2/ \
--db-host=localhost --db-name=magento --db-user=magento --db-password=magento \
--admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com \
--admin-user=admin --admin-password=admin123 --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1
```

but mine cant run `magento` so i use `./magento`

```
root@vegan:/var/www/html/magento2/bin# ./magento setup:install --base-url=http://127.0.0.1/magento2/ --db-host=localhost --db-name=magento --db-user=magento --db-password=magento --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1
SQLSTATE[HY000] [1045] Access denied for user 'magento'@'localhost' (using password: YES)



  [InvalidArgumentException]   
  Parameter validation failed  
```

and other green writings

> ```
> setup:install [--backend-frontname="..."] [--key="..."] [--session-save="..."] [--definition-format="..."] [--db-host="..."]
> ```
> 
> [--db-name="..."] [--db-user="..."] [--db-engine="..."]
> [--db-password="..."] [--db-prefix="..."] [--db-model="..."]
> [--db-init-statements="..."] [-s|--skip-db-validation]
> [--http-cache-hosts="..."] [--base-url="..."] [--language="..."]
> [--timezone="..."] [--currency="..."] [--use-rewrites="..."]
> [--use-secure="..."] [--base-url-secure="..."]
> [--use-secure-admin="..."] [--admin-use-security-key="..."]
> [--admin-user="..."] [--admin-password="..."] [--admin-email="..."]
> [--admin-firstname="..."] [--admin-lastname="..."]
> [--cleanup-database] [--sales-order-increment-prefix="..."]
> [--use-sample-data] [--magento-init-params="..."]

it says in informaton

```
--db-user

User name of the Magento database instance owner.

Default is root.
```

so i use my mysql password and admin name for it. this time it works but another errors

```
root@vegan:/var/www/html/magento2/bin# ./magento setup:install --base-url=http://127.0.0.1/magento/ --db-host=localhost --db-name=magentodb --db-user=root --db-password= root --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --cleanup-database help



  [RuntimeException]   
  Too many arguments.  
```

SO, i decrease paramters. but again same

```
root@vegan:/var/www/html/magento2/bin# ./magento setup:install --base-url=http://127.0.0.1/magento/ --db-host=localhost --db-name=magentodb --db-user=root --db-password= root 



  [RuntimeException]   
  Too many arguments. 
```

i can see

http://localhost/magento2/setup/#/landing-install

page here. i think there are no errors. i can run also setup but it stucks at %66 %67. yesterday icompleted this but it was not adding to shoopping card, today i deleted all php 5.6 7.0 in my pc and reinstalle all. BUt now, it cant install..

what can be reason? i downloaded magento from web and extracted to ww/html

directory is

```
/var/www/html/magento2/bin
```

even for this errors

```
root@vegan:/var/www/html/magento2/bin# ./magento setup:install admin-user="root"



  [RuntimeException]   
  Too many arguments.
```

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by caneraydinbey** [comment]
It is an error like that
https://github.com/magento/magento2/issues/2648

i couldnot get answers from that forums.

ALways stucks at %67 

> Module 'Magento_OfflineShippingSampleData':
> Installing data... 
> 
> Module 'Magento_BundleSampleData':
> Installing data... 
> 
> Module 'Magento_ConfigurableSampleData':
> Installing data...
