### ISSUE TITLE
How to remove country separator in Estimate Shipping and Tax Block

### ISSUE THREAD

**Issue by SandaruwanFdo** [magento/magento2#6528]
![image](https://cloud.githubusercontent.com/assets/5012179/18319675/61fd27aa-7544-11e6-9cf6-f1bf12e4b5db.jpg)

How to remove country separator in Estimate Shipping and Tax Block

**Comment by andimov** [comment]
@proxact 
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by flancer64** [comment]
Today is 2017/01/28, country separator still exists in M 2.1.3 and I don't know how I can remove it.

**Comment by damianfabian** [comment]
You can remove it using css, like this 

> select option[value='delimiter'] { display: none; }
