### ISSUE TITLE
Saving a CMS page with parentheses in the SEO meta data fields results in 404 error.

### ISSUE THREAD

**Issue by RobotsPlay** [magento/magento2#6529]
When trying to add a meta description to a CMS page, if the input includes `()` characters, the result is a 404 error.

The following post request returns 404: 

`/admin/cms/page/save/key/xxx...xxxx/back/edit`

### Preconditions

1. Magento CE 2.1.0
### Steps to reproduce

1. Create or Edit a CMS page and enter a string with `()` in it.
2. Click Save
### Expected result

1. The page saves and the meta fields are saved.
### Actual result

1. The form post returns 404 and a 404 message appears on screen.

**Comment by sevos1984** [comment]
Cannot reproduce in 2.1.1, have you tried updating your code to the latest version?

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
