### ISSUE TITLE
Allow for Unicode URL

### ISSUE THREAD

**Issue by sIiiS** [magento/magento2#653]
As you know, many languages use Unicode characters but magento do not support Unicode in URLs.

Please add this feature in Magento2 if possible for Products, Categories, CMS and etc

It is very useful and help to languages like Persian and Arabic for better SEO results

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-28208

**Comment by verklov** [comment]
Closing this ticket as having correspondent issue in the internal tracker.

**Comment by sIiiS** [comment]
any new news ?

**Comment by sIiiS** [comment]
use commits above if can solve the problem!

**Comment by alexcheng1982** [comment]
Any idea when this issue will be fixed? There are already some [solutions](http://killerwhalesoft.com/blog/magento-unicode-url-key-products-categories-cms-pages/) or [extensions](https://github.com/Minglong/Magento-unicode-URL) available. It will be very good if this can be added to the core library.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Allow-for-Unicode-URL/idi-p/47155).
