### ISSUE TITLE
Error On Shipping Information

### ISSUE THREAD

**Issue by rullymartanto** [magento/magento2#6534]
![screenshot_15](https://cloud.githubusercontent.com/assets/5577057/18337356/f9ae53f6-75b9-11e6-903c-26cf32e6931f.png)

Hey I got this issue when check out,.. 
Any Help ?

Thanks for advance

**Comment by danslo** [comment]
And what happened when you checked the log?

**Comment by rullymartanto** [comment]
Log is not there it is confuse me,.. I reinstall it.
Thanks for response
