### ISSUE TITLE
While we are creating Page Show / Hide Editor button is not working

### ISSUE THREAD

**Issue by BhautikAjmera007** [magento/magento2#6539]

**Comment by andimov** [comment]
@BhautikAjmera007 
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by andimov** [comment]
@BhautikAjmera007 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
