### ISSUE TITLE
Custom layout handle for attribute set?

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6543]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Added a custom layout file to layout/catalog_product_view_attribute_set_id_16.xml (AttributeSetId of product is 16)
2. Modify some phtmls, remove some blocks etc ..
3. 
### Expected result

1. Loads pages like what i want
### Actual result

1. No change, still default catalog_product_view.xml blocks loaded.

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-82522 to track progress on the issue.

**Comment by orlangur** [comment]
Hi @rbostan,

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

https://magento.stackexchange.com/questions/107440/magento-2-layout-based-on-attribute-set seems to be what you need.
