### ISSUE TITLE
Store / Configuration / Design right pane sub menu missing

### ISSUE THREAD

**Issue by kamolcu** [magento/magento2#6544]
### Preconditions

1. Magento version 2.1.1 Fresh install with sample data (LUMA theme)
### Steps to reproduce

1. Login to Admin page
2. Select STORES --> Configurations.
3. In GENERAL section, select Design
### Expected result

1. Design Theme, HTML Head, Header, Footer etc. sub menu should be there.
   The picture is from 2.0.6
   ![mage2 0 6-sub-menu](https://cloud.githubusercontent.com/assets/5095235/18355384/1eb8e824-7613-11e6-8ea8-a1c650403dea.png)
### Actual result

1. Only Search Engine Robots sub menu appear.
   ![mage2 1 1-menu-missing](https://cloud.githubusercontent.com/assets/5095235/18355298/dee3252a-7612-11e6-8f47-bde86b00fdf3.png)

**Comment by quienti** [comment]
Not a bug
https://github.com/magento/magento2/issues/5310
