### ISSUE TITLE
setup:static-content:deploy --dry-run incorrectly creates requirejs-config.js files

### ISSUE THREAD

**Issue by davidalger** [magento/magento2#6545]
When running the CLI tool in Magento 2 and specifying the --dry-run flag, nothing should be altered by the tool. This flag fails to suppress creation of the `requirejs-config.js` files when --dry-run is specified.

Versions affected: Magento 2.1.x, 2.0.x.

The following steps to reproduce are run against Magento 2.1.1. 

```
$ rm -rf pub/static
$ magento setup:static-content:deploy --dry-run  --no-javascript --no-css --no-less --no-images --no-fonts --no-html --no-misc --no-html-minify
Requested languages: en_US
Requested areas: frontend, adminhtml
Requested themes: Magento/blank, Magento/luma, Magento/backend
Dry run. Nothing will be recorded to the target directory.
Dry run. Nothing will be recorded to the target directory.
Dry run. Nothing will be recorded to the target directory.
=== frontend -> Magento/luma -> en_US ===
.
Successful: 1 files; errors: 0

---

New version of deployed files: 1473348444
=== frontend -> Magento/blank -> en_US ===
=== adminhtml -> Magento/backend -> en_US ===
..
Successful: 1 files; errors: 0

---

New version of deployed files: 1473348444

Successful: 1 files; errors: 0

---

New version of deployed files: 1473348444
$ tree pub/static
pub/static
└── _requirejs
    ├── adminhtml
    │   └── Magento
    │       └── backend
    │           └── en_US
    │               └── requirejs-config.js
    └── frontend
        └── Magento
            ├── blank
            │   └── en_US
            │       └── requirejs-config.js
            └── luma
                └── en_US
                    └── requirejs-config.js

11 directories, 3 files
$ magento -V
Magento CLI version 2.1.1 
```

As you can see, by removing the entire `pub/static` directory and then running the `setup:static-content:deploy` command with `--dry-run` specified, three files were created by the tool.

**Comment by davidalger** [comment]
@veloraven May be good to address #4961 at the same time as this one.

**Comment by Yablonskiy23** [comment]
Created internal issue MAGETWO-70454 to investigate and track this issue.

**Comment by IlnitskiyArtem** [comment]
@davidalger, thanks for reporting this issue. Created internal issue MAGETWO-70454 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@davidalger, thank you for your report.
We've created internal ticket(s) MAGETWO-70454 to track progress on the issue.

**Comment by enriquei4** [comment]
I can´t run: `bin/magento setup:static-content:deploy --dry-run`  In 2.2.3 I get an exception:
```
[Symfony\Component\Console\Exception\RuntimeException]
  The "--dry-run" option does not exist.
```
Also in 2.2.3, when I use help to see how should be dry run. I see:
<img width="1185" alt="captura de pantalla 2018-04-07 a las 1 22 56" src="https://user-images.githubusercontent.com/31536252/38448126-5ffebe8a-3a02-11e8-97dc-8eb07bbd2954.png">

I see that is deprecated
`    /**
     * Key for dry-run option
     *
     * @deprecated since 2.2.0
     */
    const DRY_RUN = 'dry-run';`

**Comment by magento-engcom-team** [comment]
Hi @davidalger

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@davidalger thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
