### ISSUE TITLE
export does not give proper import

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#6547]
### Preconditions
1. branch develop 
2. php 5.6
### Steps to reproduce

1. export products with no exclusions.  
2. import products
### Expected result

1. should import without any issues 
### Actual result

1. [Screenshot, logs]
   . Value for 'gift_message_available' attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s): 1102

**Comment by NadiyaS** [comment]
Hi @dmcmillin ,
what value for gift_message_available do you have in you export file in row 1102?

**Comment by dmcmillin** [comment]
The same I have in all of them for it. No
I think this is just an extension to the issue of #6449.. I excluded gift_message_available and now it's erroring on pictures. Although I am not running nginx.

**Comment by dmcmillin** [comment]
I just actually hunted through my export and realized that the configurable products are absolutely screwed. All the fields are so screwed from the 1st configurable product onward I can't repair it at all. Anyone have a export for configurable products already done that works so I can diagnose the problem properly? Thanks!!!

**Comment by Ctucker9233** [comment]
I have noticed this behavior as well. For some reason, in the exported .csv every configurable product is followed by a few blank lines or duplicated lines. Not sure why this is.

**Comment by IlnitskiyArtem** [comment]
Hi, @dmcmillin. I cannot reproduce this issue on latest Magento versions (2.2.0, 2.1.7, 2.0.15). Can you please specify exact Magento version you used? Also it would be helpful if you provide some sensitive data from your old .csv file and number of products that you exported and then tried to import.
