### ISSUE TITLE
Issue with merge and minfy js

### ISSUE THREAD

**Issue by umang-ranium** [magento/magento2#6551]
I tried to minify and merge js and have a custom module for checkout as well i am facing an issue. Loading icon shows up on checkout and nothing else shows up, when i checked the console i have follwing error 
bc01984….min.js:193 Uncaught SyntaxError: Unexpected token }
checkout:17 Uncaught TypeError: require.config is not a function(anonymous function) @ checkout:17
checkout:92 Uncaught TypeError: require is not a function 
### Preconditions

1. Using PhP 7
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@umang-ranium thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
