### ISSUE TITLE
Selected SKU's not displayed in Pages (Widget Config ) --> Edit mode

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#6554]
### Preconditions

1. Magento 2.1 Nginx FPM PHP 5.6
### Steps to reproduce

1. Add a page with a widget ( add widget from the TinyMce editor ) and Select Catalog product List with and with condition SKU is one of <some sku />
2. Save & Continue edit.
3. Click on the Folder icon with the text _products_
### Expected result

1. Widget popup will open and the conditions will appear in there 
### Actual result

1. No conditions listed in there.

**Comment by oleg-onufer** [comment]
@senthilengg  Thanks for reporting this issue.
Internal ticket MAGETWO-70105 was created.

**Comment by senthilengg** [comment]
@oleg-onufer Thanks. Finally after long time.

**Comment by magento-engcom-team** [comment]
@senthilengg, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
