### ISSUE TITLE
Unclear error message from command line execution of magento admin:user:create

### ISSUE THREAD

**Issue by monty241** [magento/magento2#6556]
Magento CLI version 2.1.0

See picture too.

when I enter:

magento admin:user:create

I get a lot of " is a required field.

But as a newbie I have no clue at all how to provide those.

Only when I add some random parameter, I get real usable hints including the option names too use, such as --admin-password=

Expected Result:
Suggested change: do not report that something is a missing field, but also tell the user how to add them to the command line.

Actual Result:
Unusable
![2016-08-26 10_33_54-bitnami ip-172-30-0-142_ _opt_bitnami_apps_magento_htdocs_bin](https://cloud.githubusercontent.com/assets/7579444/18386112/fa60730c-7694-11e6-8adc-7e8747d78eaa.png)

[migrated from magentocommerce.com/products/bug-tracking]

**Comment by mbrinton01** [comment]
Hello @monty241, thank you for this report. For console commands you can use `-h` flag for help on the command.  For example:

`magento admin:user:create -h`

returns:

```
Usage:
 admin:user:create [--admin-user="..."] [--admin-password="..."] [--admin-email="..."] [--admin-firstname="..."] [--admin-lastname="..."] [--magento-init-params="..."]

Options:
 --admin-user           (Required) Admin user
 --admin-password       (Required) Admin password
 --admin-email          (Required) Admin email
 --admin-firstname      (Required) Admin first name
 --admin-lastname       (Required) Admin last name
 --magento-init-params  Add to any command to customize Magento initialization parameters
                        For example: "MAGE_MODE=developer&MAGE_DIRS[base][path]=/var/www/example.com&MAGE_DIRS[cache][path]=/var/tmp/cache"
 --help (-h)            Display this help message
 --quiet (-q)           Do not output any message
 --verbose (-v|vv|vvv)  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)         Display this application version
 --ansi                 Force ANSI output
 --no-ansi              Disable ANSI output
 --no-interaction (-n)  Do not ask any interactive question
```

If you have more questions, please open another issue.
