### ISSUE TITLE
M2.1.1 : Rest API V1 error when trying to use the 'useForShipping'-parameter when saving a billing address

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6557]
I try to save a billing address for a quote using the REST API, but when I want to make use of the `useForShipping`-flag (as documented in the original API), I get a strange error:

```
Property "UseForShipping" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressInterface"
```

My request goes to `http://www.domain.com/rest/V1/guest-carts/{masked quote ID}/billing-address`and the payload is:

```
{
    "address": {
        "street": ["Street\n100\n"],
        "postcode": "1234AB",
        "city": "Eindhoven",
        "firstname": "Giel",
        "useForShipping": true
    }
}
```

Link to the API: http://devdocs.magento.com/swagger/index.html#!/quoteBillingAddressManagementV1/quoteBillingAddressManagementV1AssignPost

**Comment by mbrinton01** [comment]
Thank you @kanduvisla for reporting this issue. I was able to reproduce it and we are tracking it internally under issue MAGETWO-58269.

**Comment by SerhiyShkolyarenko** [comment]
MAGETWO-58269 is delivered to develop branch. Closing the issue. Please feel free to leave comments anyway.
