### ISSUE TITLE
ImportExport can't import products with a purely numeric SKU

### ISSUE THREAD

**Issue by paales** [magento/magento2#6559]
### Preconditions

1. 2.1.1
### Steps to reproduce

1. Create an product import with purely numeric SKU's (`12345`)
2. Have other products with SKU's in the system which follow the pattern `12345-AB`
3. Run the import
### Expected result

1. Imports attributes just fine
### Actual result

1. All the attribute information is missing on the product

Here the SKU gets set as an array key:
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1687

Here the SKU gets queried as an int:
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1238

Query difference:
<img width="947" alt="slack-imgs com" src="https://cloud.githubusercontent.com/assets/1244416/18388815/5eafc94e-76a3-11e6-8a62-3d1fd2e23a9a.png">

<img width="943" alt="slack-imgs-1 com" src="https://cloud.githubusercontent.com/assets/1244416/18388816/60315706-76a3-11e6-908a-e476eceedd21.png">

**Comment by ghost** [comment]
@paales this was fixed in https://github.com/magento/magento2/pull/6446.

**Comment by paales** [comment]
@thanks for the reference!
