### ISSUE TITLE
emulateAreaCode don't work as prepared

### ISSUE THREAD

**Issue by galillei** [magento/magento2#6560]
in frontend controller i want to get all products collection, without any filters, only by sku. 

```
  $collection = $this->_productCollectionFactory->create();
  $collection->addAttributeToFilter('sku', ['in' => array_keys($productsRetailOps)]);
```

But when i try do this:
`foreach ($collection as $item)` 
i noticed that frontend' s plugin for productFactory worked. But i run code in emulateAreaCode:
`$state->emulateAreaCode(\Magento\Framework\App\Area::AREA_WEBAPI_REST, [$inventoryApi, 'setInventory'], [$inventoryObject]);`

**Comment by veloraven** [comment]
@Galillei thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
