### ISSUE TITLE
Error checkout with new install

### ISSUE THREAD

**Issue by guillaumecochard** [magento/magento2#6562]
### Preconditions

1. Magento 2.1.1
2. PHP 5.6.18
   3.MySQL 5.6.29
   4.Apache 2.2
### Steps to reproduce

1. Just install a new Magento 2 install on a server where an old Magento is already installed
2. 
3. 
### Expected result

1. Just have to display a front with Luma theme
### Actual result

Just after clicking on the front link, Magento tells me that a product was added to the cart, and the subtotal of the cart was totally false. In addition it's said that they where 3 products in cart but displaying just one.
There no products, no client, no cart rules in the Backend nothing. It's looks like it takes the cache from the old installation with no reason.
1. [Screenshot, logs]
![erreur](https://cloud.githubusercontent.com/assets/7467023/18392388/e4453522-76b1-11e6-8f7b-022aa95318f5.png)
![erreurbo](https://cloud.githubusercontent.com/assets/7467023/18392387/e4434f3c-76b1-11e6-975b-cca4b4f58765.png)
![install](https://cloud.githubusercontent.com/assets/7467023/18392389/e447c99a-76b1-11e6-8270-72a2454bb49d.png)

**Comment by BaDos** [comment]
Hi @guigui51 

Try to clear the cache of  your browser.

Please, write URL of new and old installation.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
