### ISSUE TITLE
Cannot place order if address doesn't have Region ID

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6571]
### Preconditions

Magento 2.1.1 with sample data
### Steps to reproduce
1. Log in as roni_cost@example.com user
2. Add new address which doesn't have Region ID (I used Ukraine address)
3. Add any product to the shopping cart
4. Go to checkout page and choose created address as shipping
5. Go to the home page from the payment step on checkout
6. Try to go to checkout again and place an order
### Expected result
1. There should be ability to place an order
### Actual result
1. Checkout page is broken.
   <img width="1413" alt="screen shot 2016-09-11 at 19 43 15" src="https://cloud.githubusercontent.com/assets/6418650/18418915/174f2ab6-7858-11e6-8c2f-c7007bb06e41.png">

**Comment by dthampy** [comment]
Following your steps that you described , I was not able to reproduce the issue(Magneto Version used: 2.1.1 CE with Sample data) So I might be missing some steps /settings:
1. in the admin, what’s the locale option that you are using
2. Also can you specify the payment method and shipping method ?

**Comment by ytorbyk** [comment]
Hi @dthampy 
1. default value
2.1. payment method you mustn't chose, just open the last step on checkout without placing an order.
2.2 shipping method "Flat Rate" (the only available) 

I retested it on the develop branch and looks like it's fixed. The bug is present only on the 2.1 branch.

**Comment by SerhiyShkolyarenko** [comment]
@ytorbyk I checked it on 2.1.2 and order was placed successfully. Is it reproducible for you on 2.1.2?

**Comment by ytorbyk** [comment]
Hi @SerhiyShkolyarenko,
Yes, looks like the bug is fixed.
Thank you!
