### ISSUE TITLE
Product Availability on a Per Option basis is missing from M2

### ISSUE THREAD

**Issue by epadmin** [magento/magento2#6576]
### Preconditions

In Magento 1, configurable products / options could be displayed with the available QTY on a per option basis.   We cannot find it in M2 and our Theme developer said this was native M1 functionality that is missing from M2.
Magento 2.1.1 PHP 5.6.2
1.  Create a configurable product with various stock levels for each option
2. Settings set to display stock
### Steps to reproduce
1. There is no dropdown on the product page (see attached) for the product qty on a per option basis
### Expected result

Should be able to display the stock available for each option like M1
### Actual result

See attached
![image](https://cloud.githubusercontent.com/assets/20366338/18420644/fc7da106-783c-11e6-8482-890cf712473a.png)

**Comment by sevos1984** [comment]
This is not native magento functionality

**Comment by pboisvert** [comment]
@antboiko can you check if this is a parity issue?

**Comment by epadmin** [comment]
@sevos1984 how can I prove that to the theme author?   I asked them since the M2 theme is supposed to include all the features of their M1 theme and they said its a Magento feature so I need to have them keep their word that the M2 version has the same functionality as their M1 version.

**Comment by antboiko** [comment]
Hi @epadmin , what theme are you referring to? 

In Magento 1 and Magento 2 there is an option in Inventory configuration "Only X Left Threshold". If you set your number (e.g. 15 as on you screenshot), when the product stock drops to this (or lower) number the text “Only X left Threshold” will appear (X stands for the number of products).

It seems to be a customization of displaying configurable product stock when it reaches that threshold with a breakdown of its options.

Regards,
Anton.

**Comment by epadmin** [comment]
we are using the Ultimo theme from Infortis

-------- Original Message --------
Subject: Re: [magento/magento2] Product Availability on a Per Option
basis is missing from M2 (#6576)

**Comment by antboiko** [comment]
Hi @epadmin , it is not a Magento functionality to show a drop-down box with quantities of all products associated with that configurable product. 

I'm closing this ticket since it's not a Magento issue. 

Regards,
Anton.

**Comment by epadmin** [comment]
thanks!

-------- Original Message --------
Subject: Re: [magento/magento2] Product Availability on a Per Option
basis is missing from M2 (#6576)
