### ISSUE TITLE
'header' block name is ambiguous

### ISSUE THREAD

**Issue by tommypyatt** [magento/magento2#6577]
### Preconditions
1. Magento Enterprise 2.1.0
### Steps to reproduce
1. Add custom content to `html/header.phtml` for theme, or perform some sort of action on `header` block in XML via `referenceBlock`.
### Expected result
1. One would expect, based on the naming convention used here, that the affected block would be the page header.
### Actual result
1. This is actually a block that outputs a welcome message within the header.

I'm not entirely certain if this is the correct place for this discussion. Apologies if it's not.

I'm putting together a blank theme at the moment. This naming issue causes me concern because I am finding it difficult to put together something easy to use. It would be nice if I could use the name `header.phtml` for my template and the block name `header` for my page header, as I think this is the most intuituve. I cannot do this however because there is a 'welcome' block in Magento with a template reference hard-coded (not via XML) to my intended template name, and with its block name set to `header`

Maybe a different name for this block, such as `welcome-message`, would be more appropriate?

File where template name is set:
`vendor/magento/module-theme/Block/Html/Header.php`

XML for block, in `default.xml`:

```
<referenceBlock name="top.links">
    <block class="Magento\Theme\Block\Html\Header" name="header" as="header" before="-">
        <arguments>
            <argument name="show_part" xsi:type="string">welcome</argument>
        </arguments>
    </block>
</referenceBlock>
```

**Comment by magento-engcom-team** [comment]
@tommypyatt, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by tommypyatt** [comment]
@magento-engcom-team: You're welcome.

I don't know if changing it would be such a good idea actually, since it would have the potential to cause problems when upgrading themes. I'll have a see if I can think of a way around that, and create a PR if so. Thanks for the feedback.

**Comment by magento-engcom-team** [comment]
Hi @tommypyatt. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/33
