### ISSUE TITLE
[Magento 2.1] Additional customer address attributes is not show in billing payment

### ISSUE THREAD

**Issue by tandih** [magento/magento2#6579]
Magento 2.1
Add customer address attribute and set property _show on storefront_ is **yes** check on the checkout page
**Expected result:**
- The attribute show on shipping address and billing field list

**Actual result:**
- The attribute **not** show in billing address list payment

P/S: Using ui component to sort field in billing working good but on billing .....

Thank you so much

**Comment by veloraven** [comment]
@nagatan  what Magento Edition do you use? Enterprise or Community?
Customer custom address attributes are available in Enterprise edition only.
If you use this one, please contact the Support with your problem.

**Comment by tandih** [comment]
Hi Veloraven, 
Thank you for your reply. I am using Magento EE 2.1.0 and I was updated to 2.1.1 but seem the attribute in Magento 2 using much hard code and todo. Long time to add field to shipping and billing address. Hope reply from support soon.

**Comment by veloraven** [comment]
I'm closing this issue as it is not in scope of GitHub issues and should be resolved via Support.
