### ISSUE TITLE
Can't login to backend when session.save_path value changed

### ISSUE THREAD

**Issue by KrendiL101** [magento/magento2#6580]
### Preconditions

Magento 2.0.7
PHP 5.6
### Steps to reproduce

Change ['session']['save_path'] in file app/etc/env.php to 'var/session' for example
### Actual result

When login to backend, script just return me to login form with no errors or notices.

**Comment by stamster** [comment]
Can you use sessions from other, non-Magento apps? I guess your save path is not writeable.

**Comment by KrendiL101** [comment]
Whe i set not writeble or wrong path, SessionHandler thow me an exeption.

Frontend work fine with 'var/session' param, customer login, add to cart, etc.

**Comment by stamster** [comment]
Then just clear the browser cache. Also, try with Private window / Incognito tab first.

**Comment by KrendiL101** [comment]
I tried in diffrent browsers and incognito tab also.
When i change param to '/var/lib/php/sessions' it works, but folder permissions the same.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
