### ISSUE TITLE
Removing all items from a cart

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6586]
What about new api method like `[DELETE] /V1/carts/{cartId}/items`.
I think this is desired method.

[Documentation](http://devdocs.magento.com/swagger/index.html#/) quoteCartItemRepositoryV1.

**Comment by mbrinton01** [comment]
@springimport, I've marked this issue as an improvement so it will be moved to [Community Forums](https://community.magento.com).  Thank you for your feedback to improve Magento 2.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Removing-all-items-from-a-cart/idi-p/48899).
