### ISSUE TITLE
Some attributes not visible on "Create Product Configurations" on grid of attributes when try to create product like Configurable.

### ISSUE THREAD

**Issue by mantonuk** [magento/magento2#6587]
Some attributes not visible on "Create Product Configurations" on grid of attributes when try to create product like Configurable.

magento2/app/code/Magento/ConfigurableProduct/Model/ConfigurableAttributeHandler.php

public function isAttributeApplicable($attribute)
|-     {
||         **$types = [
||             \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE,
||             \Magento\Catalog\Model\Product\Type::TYPE_VIRTUAL,
||             \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE,
||         ]**;
||         return !$attribute->getApplyTo() || count(**array_diff**($types, $attribute->getApplyTo())) === 0;
||     }

attributes imported from M1 to M2 (2.0.9)
So. Is this bug or feature? =)
Just make update to "simple,virtual,configurable" or "[EMPTY]" and get this as solved? =)

+--------------+-------------------------+-----------+------------+---------------+---------------+---------------+---------------------+--------------------------+-------------------------+-------------------------+-------------------------+------------------+---------------------+-------------------------------+----------+--------------------+-------------------------+----------------------------+-----------------+--------------------+-----------------------+---------------+-----------------+
| attribute_id | frontend_input_renderer | is_global | is_visible | is_searchable | is_filterable | is_comparable | is_visible_on_front | is_html_allowed_on_front | is_used_for_price_rules | is_filterable_in_search | used_in_product_listing | used_for_sort_by | apply_to            | is_visible_in_advanced_search | position | is_wysiwyg_enabled | is_used_for_promo_rules | is_required_in_admin_store | is_used_in_grid | is_visible_in_grid | is_filterable_in_grid | search_weight | additional_data |
+--------------+-------------------------+-----------+------------+---------------+---------------+---------------+---------------------+--------------------------+-------------------------+-------------------------+-------------------------+------------------+---------------------+-------------------------------+----------+--------------------+-------------------------+----------------------------+-----------------+--------------------+-----------------------+---------------+-----------------+
|          245 | NULL                    |         1 |          1 |             0 |             0 |             0 |                   0 |                        1 |                       0 |                       0 |                       0 |                0 | **simple,configurable** |                             0 |        0 |                  0 |                       0 |                          0 |               0 |                  0 |                     0 |             1 | NULL            |
+--------------+-------------------------+-----------+------------+---------------+---------------+---------------+---------------------+--------------------------+-------------------------+-------------------------+-------------------------+------------------+---------------------+-------------------------------+----------+--------------------+-------------------------+----------------------------+-----------------+--------------------+-----------------------+---------------+-----------------+

**Comment by victor-v-rad** [comment]
Hi @mantonuk 
Could you list attribute codes are not visible after migration? 
Buy the way I encourage you to use the latest version of Data Migration Tool and report new issues in the dedicated repository https://github.com/magento/data-migration-tool/issues

**Comment by victor-v-rad** [comment]
Fell free to reopen the issue when you have additional information.

**Comment by mantonuk** [comment]
Hi Victor.
I got all attributes on last version of magento 2.1 using "data migration tool".
I forget to sent answer ;)
sorry
