### ISSUE TITLE
Meta description tag making htmlentities for non latin characters

### ISSUE THREAD

**Issue by hvstudio** [magento/magento2#6588]
### Preconditions

1. Magento ver. 2.1.1
### Steps to reproduce

1. Insert this "ěščřžýáíé" inside any "Meta Description" or "Meta Keywords" tested in "Categories"
### Expected result

1.  ![image](https://cloud.githubusercontent.com/assets/15934350/18457493/936365b6-7959-11e6-8442-d609c52d483c.png)
### Actual result

1. ![image](https://cloud.githubusercontent.com/assets/15934350/18457479/7365cd94-7959-11e6-9f9d-aed9bed23d7f.png)

**Comment by sevos1984** [comment]
Not reproducible, please share your locale settings.

**Comment by hvstudio** [comment]
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./`
`php ./bin/magento setup:install --admin-firstname=*** --admin-lastname=*** --admin-email=*** --admin-user=*** --admin-password=*** --db-name=magento2 --db-user=homestead --db-password=secret --use-secure=1 --use-secure-admin=1 --backend-frontname=admin`
`bin/magento setup:static-content:deploy`

![image](https://cloud.githubusercontent.com/assets/15934350/18490310/b61764b0-7a01-11e6-983b-de9343416c86.png)
![image](https://cloud.githubusercontent.com/assets/15934350/18490462/768cfdae-7a02-11e6-863b-be60f3b4bc4f.png)

### Result

![image](https://cloud.githubusercontent.com/assets/15934350/18490363/e894a54c-7a01-11e6-964a-aa48322f11df.png)

### Broken code part

https://github.com/magento/magento2/blob/2.1.1/lib/internal/Magento/Framework/View/Page/Config.php#L229

### Posible Fix

`$this->metadata[$name] = htmlspecialchars($content);`

**Comment by thanasisgalanis** [comment]
Same issue for categories content, for non Latin characters (i.e. Greek)
Magento CE 2.1.0
PHP 7.0.11
MySQL 5.6.33-log

This is the actual content inside category SEO fields
![category seo content](https://cloud.githubusercontent.com/assets/6130645/19087848/432f7bdc-8a7c-11e6-9497-d3e505b36fd4.png)

This is what stored in database
![category metatag records in database](https://cloud.githubusercontent.com/assets/6130645/19088149/9ea9c2b4-8a7d-11e6-96b4-c60667385f4b.png)

And finally this is what appears in source code
![category metatag records in source code](https://cloud.githubusercontent.com/assets/6130645/19088189/ca7748bc-8a7d-11e6-93fa-615df349e573.png)
Note that title meta is OK
`<title>Ανταλλακτικά για αλυοπρίονα</title>`

**Comment by tomasvinduska** [comment]
still no fix?

**Comment by mepsteinj** [comment]
I also have this problem with magento 2.1.5 "Magento locale is set to es_CL"
Default system (Debian Jessie) locale is set to "none" (I don't know if this is relevant)

Default country: Chile
Time zone: America/Santiago
Regional configuration: Chile

**Default Description:** Electrónicos

Home page **without** "Meta Description" show the correct text encoding: Electrónicos

Hope page **with** "Meta Description" shows incorrect text encoding: `Electr&oacute;nicos`

No problems in the title tag.

**Comment by thanasisgalanis** [comment]
This bug still exist in 2.1.7 CE with local language el_GR.

**Comment by VasylShvorak** [comment]
I cannot reproduce this issue. Please add more details to your description of the steps you followed when identifying this issue.

**Comment by thanasisgalanis** [comment]
To reproduce this issue:

1. Set your system (frontend) to use a language that contain non latin characters (i.e. Greek - el_GR locale)
2. Use non latin characters as values in a category fields (Meta Keywords, Meta Description), you can copy paste this value:
For **Meta Keywords** "καλημέρα, ένα, δύο, τρια"
For **Meta description** "Αγόρασε ποιοτικά προϊόντα στις καλύτερες τιμές"
3. Load that category to your frontend and view the source code of the loaded page, search for the fields `meta name ="descrption` or `"meta name="keywords"` and look its `content=` values.

**Comment by VasylShvorak** [comment]
@sakisplus Please provide more information about your language pack installation including link and type installation.

**Comment by fouli86** [comment]
The issue still exists in 2.1.8 version. I also have the el_GR language pack but I noticed that all keywords and descriptions written in greek characters work fine in homepage. Any news/ideas?

Magento CE 2.1.8
PHP Version 7.0.22
Server version: MySQL 5.6.35

**Comment by magento-engcom-team** [comment]
@hvstudio, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
