### ISSUE TITLE
Untranslatable string "optional"

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#6593]
### Preconditions

Version: _Magento 2.1.1_
### Steps to reproduce

1. When entering personal data during the checkout (if email matches with the user account)
### Expected result

1. The word _optional_ should be translatable, but is not - no such string was generated with _magento i18n:collect-phrases_  tool
### Actual result

![capture](https://cloud.githubusercontent.com/assets/282687/18473516/a6c2168e-79bd-11e6-8cb8-d7dfe77307e7.PNG)

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket created MAGETWO-58378

**Comment by magento-engcom-team** [comment]
@jernejh, thank you for your report.
We've created internal ticket(s) MAGETWO-58378 to track progress on the issue.

**Comment by quisse** [comment]
Fixed in MAGETWO-70235 PR https://github.com/magento/magento2/pull/10056
