### ISSUE TITLE
Impossible to just save the shipping address using the REST v1 API

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6599]
I know there is [an endpoint to save a single billing address](http://devdocs.magento.com/swagger/index.html#!/quoteBillingAddressManagementV1), but there seems to be lack of a way to save a shipping address.

There is an [endpoint that saves shipping-information](http://devdocs.magento.com/swagger/index.html#!/checkoutGuestShippingInformationManagementV1), but this requires you to also already select and send a shipping method, and I don't want that. I just want to be able to save the shipping address. Nothing else.

Even more interesting: when I set the `useForShipping`-flag to true when saving the billing address, there are not 2 records created in the database. Or is this not how it works?
### Preconditions
1. Magento 2.1.1
2. REST API V1
### Steps to reproduce

I'm currently trying to save the shipping method using the shipping-information endpoint, but without the shipping method, but this returns an error stating `Carrier with such method not found`, and it shows to NULL parameters (which makes sense)
### Expected result

Saving a shipping address without a carrier should be possible. 
### Actual result

Saving a shipping address without a carrier is not possible.

**Comment by veloraven** [comment]
@kanduvisla thank you for your report.
Could you please describe steps in a more detailed way? Including exact requests you send.

**Comment by MarkB42** [comment]
Hi, Have you tried 
1) reading the Sales Order with _salesOrderRepositoryV1GetList_ // _salesOrderRepositoryV1Get_ 
2) Make the necessary changes
3) Use _salesOrderRepositoryV1Save_ to send the moded data back to Magento*
- Set the Entity.payment structure to null BEFORE sending it back to Magento or you will get an error "Message: Property "AdditionalInformation" does not have corresponding setter in class "Magento\Sales\Api\Data\OrderPaymentInterface".

The Shipping Address in the one of the Additional Data structures, cannot remember which one. But it is labled as Shipping Address even if it's the same as the Billing addy.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
