### ISSUE TITLE
After upgrade to 2.1.1 I can't set on product edit tab with Advanced Pricing

### ISSUE THREAD

**Issue by OlgaBurtyka** [magento/magento2#6601]
### Preconditions

1. Magento 2.1.1
2. php 7.0.7
3. MariaDB
4. Nginx 
### Steps to reproduce

1. Upgrade magento from 2.0.9 to 2.1.1 via composer update
2. Go edit product in admin - and can't see Advanced Pricing Tab
### Expected result

1. See Advanced Pricing Tab
### Actual result

1. [Screenshot, logs]
   Can't see Advanced Price tab in edit product
   ![apgrade](https://cloud.githubusercontent.com/assets/4771407/18481016/5dbfdf68-79e3-11e6-858a-109fd9eaadef.png)

**Comment by heldchen** [comment]
it's now a link in the top section:

![image](https://cloud.githubusercontent.com/assets/299636/18489604/7ad998e4-79fe-11e6-9bf4-231376fdeae0.png)

**Comment by OlgaBurtyka** [comment]
@heldchen Hi! Yes I know it. But I don't have price field. If I open browser debug - I can find Price and other price attributes - but they not display(. What can influence on it?
![apgrade2](https://cloud.githubusercontent.com/assets/4771407/18502155/171a69a4-7a5e-11e6-8714-63ea36a98d23.png)
![apgrade1](https://cloud.githubusercontent.com/assets/4771407/18502156/171fcfd4-7a5e-11e6-9637-ba6111a4c59b.png)

**Comment by OlgaBurtyka** [comment]
I find why it happend. See screen.
![apgrade_11](https://cloud.githubusercontent.com/assets/4771407/18506196/71407ad0-7a73-11e6-870b-ba46f6f6c5e6.png)

**Comment by oshmyheliuk** [comment]
Hi @OlgaBurtyka
It's not a bug, in new version advanced pricing open as popup when you click on a link below Price field.
Advanced pricing link is a part of Price Field.
If you move Price field to advanced pricing group, a link will not appear.
