### ISSUE TITLE
Catalog list - toolbar,paging,layered navigation, wrong numbers and information of products

### ISSUE THREAD

**Issue by hvstudio** [magento/magento2#6603]
### Preconditions

1. Fresh install
### Steps to reproduce

1. Create 2 products 1 visible in "Catalog,Search" another only "Search" put them in same category
   ![image](https://cloud.githubusercontent.com/assets/15934350/18491633/8ee642fc-7a07-11e6-8f8a-1b2a8f9f6767.png)
### Expected result

1. Expecting 1 product
2. no paging
3. only 1 price range in layered navigation
### Actual result

1. 9 per page
   ![image](https://cloud.githubusercontent.com/assets/15934350/18491752/3f482d54-7a08-11e6-8334-5abae04d4233.png)
2. 1 product per page, screens for both pages
   ![image](https://cloud.githubusercontent.com/assets/15934350/18491848/b63ac14c-7a08-11e6-8193-e4d204f5e0d6.png)
   ![image](https://cloud.githubusercontent.com/assets/15934350/18491867/da869f9e-7a08-11e6-8727-7b088017892a.png)

**Comment by Taral-Patoliya** [comment]
Facing same issue, i have searched a little bit about this, and was going to raise the issue, but found this issue. There is no syncing between the toolbar and products list.

**Comment by dbsdsun** [comment]
I meet the similar issue.

## My problem is:

under CategoryA, there are 3 products,
configProduct1, 
simpleProduct1, simpleProduct2.

simpleProduct1 and simpleProduct2 are children of configProduct1.

all of them are visible.

When I go to category list page,
it says: Items 1-1 of **3**, it should say Items 1-1 of **1**

---

after checking the code, I found 

The total is incorrectly set in the following code (magento 2.1.0):

class Collection extends \Magento\Catalog\Model\ResourceModel\Product\Collection

```
protected function _renderFiltersBefore()
{
   ...
   $this->_totalRecords = $this->searchResult->getTotalCount();
   ...
}
```

The solution is removing this line.

**Comment by Ubeo** [comment]
Sorry @dbsdsun , I can't find that function in \Magento\Catalog\Model\ResourceModel\Product\Collection but I'm having the same issue too.

**Comment by veloraven** [comment]
@hvstudio please identify which version of Magento this issue occurs on.

**Comment by hvstudio** [comment]
@veloraven hi,here
![768cfdae-7a02-11e6-863b-be60f3b4bc4f 1](https://cloud.githubusercontent.com/assets/15934350/18739958/5ec2610e-80a7-11e6-9955-ca5a5ced11c6.png)
i have described installation here https://github.com/magento/magento2/issues/6588

But this issue is in all versions at least same result is on Magento CLI version 2.1.0

**Comment by Taral-Patoliya** [comment]
@veloraven This issue is also present in 2.0.7

**Comment by dbsdsun** [comment]
@veloraven  this problem happens on all magento 2. Please repeat my example mentioned before.

**Comment by Taral-Patoliya** [comment]
@magento-team @veloraven  Do we have any update for this problem, can you suggest how long it would take to get the solution for this problem?

**Comment by veloraven** [comment]
We already have internal ticket MAGETWO-54167 for such issue.

**Comment by shayanhusaini** [comment]
did anyone have a workaround for this issue?

**Comment by ps202** [comment]
I am facing the same issue on 2.2-dev.

**Comment by onepack** [comment]
Same issue here on 2.1.5
In the toolbar the total number is incorrect and Paging in the bottom of the category shows the total number of pages of all products including the simple products that make a CFG and are not visible on category pages.

**Comment by onepack** [comment]
@veloraven Hi Olga,

How is internal ticket MAGETWO-54167 going?
This is kinda critical when customers face a "can't find any products" message.
The go and buy with the other webshops.

**Comment by magento-engcom-team** [comment]
@hvstudio, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by leptoquark1** [comment]
Ok since @magento-engcom-team is unable to reproduce it here step by step for you:

1. Make a clean install of Magento (in my case 2.1.9)
2. Create a Test Category
3. Create 2 Products and assign them to the Test-Category
  - One have Visibility "Catalog"
  - The other have Visibility "Search"
4. Go to Stores -> Configuration -> Catalog -> Storefront
  - set Config Value of "Products per Page on Grid Allowed Values" to "1,9,15,30"
  - set Config Value of "Products per Page on Grid Default Value" to "1"
5. Visit the Test-Category on Frontend and see the Problem:

![bildschirmfoto 2017-10-11 um 16 51 52](https://user-images.githubusercontent.com/13577480/31448410-abedd8f6-aea4-11e7-967a-390d709960ad.png)

**Comment by drew7721** [comment]
IMO this issue is related to the issue on getSize() #7730 that is not returning the proper value. I think this is happening when adding `distinct` or `group` to a collection, for some reason the `totalRecords` propriety does not get updated when needed.

**Comment by onepack** [comment]
Why is this closed? It is not solved and is still an issue until today.
