### ISSUE TITLE
Magento 2.0.7 - Best seller report issue

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#6604]
When I tried to refresh the best seller statics, it shows the error message. But I can refresh other statistics.
### Preconditions
1. Magento 2.0.7
### Steps to reproduce
1. go to admin>report>refresh statistics
2. select "bestseller"
3. select "refresh lifetime statistics" on the top dropdown.
4. submit
### Expected result

Magento refresh the lifetime statics of bestsellers with message like below.
![capture2](https://cloud.githubusercontent.com/assets/13892193/18492618/35841cde-79da-11e6-92c6-12216fc1aa51.PNG)
### Actual resul

see the message like below picture.
![capture](https://cloud.githubusercontent.com/assets/13892193/18492381/07a9ab54-79d9-11e6-838e-56badd110e7f.PNG)

And also found an error in exception log. Please see the attachment.
[ExceptionLog.txt](https://github.com/magento/magento2/files/470854/ExceptionLog.txt)

Thank you.

**Comment by pboisvert** [comment]
@dexteritycc going to need a bit more info to start an investigation. Please use the guidelines you see above to provide info useful to reproducing the info.

**Comment by dexterityzx** [comment]
@pboisvert I have updated the post. Thank you.

**Comment by dexterityzx** [comment]
Anyone has any idea on this issue?

**Comment by vityakopin** [comment]
I cannot reproduce this issue. Can you confirm that the issue is reproducing on latest version of Magento2?
