### ISSUE TITLE
URL Rewrite not working as expected

### ISSUE THREAD

**Issue by skhell** [magento/magento2#6606]
### Preconditions

1. Magento 2.1.0
2. MySQL 5.6.30
3. PHP 7.0.6

After installing Magento and importing some products to test I have missed to enable the Catalog URL Rewrite option in stores-->configuration-->catalog-->catalog-->SEO-->Use Categories Path for Product URLs to YES

After enabling the option I made a rebuild of the index with the command

php bin/magento indexer:reindex

Right after reindexing I navigate to a category and the URL is:
http://www.mywebsite.dev/catalog/category/view/s/t-shirt/id/439/

And the product URL is:
http://www.mywebsite.dev/red-tshirt.html

So the product URL appear to be correct just the category, after another reindex and without solving the problem I truncated database tables:
1. catalog_url_rewrite_product_category
2. url_rewrite

After that I fired again the reindex command, now both tables remain empty and on the fronted both PRODUCT and CATEGORY URL are not rewritten.
### Steps to reproduce

1. Install Magento and create some products
2. Enable the URL rewrite option stores-->configuration-->catalog-->catalog-->SEO-->Use Categories Path for Product URLs to YES
3. php bin/magento indexer:reindex
### Expected result

1. Rewrite category URL's
### Actual result

![catalog_url_rewrite](https://cloud.githubusercontent.com/assets/20488700/18504918/fbce544c-7a64-11e6-95ae-087238272a27.png)

![url_rewrite](https://cloud.githubusercontent.com/assets/20488700/18504920/fd83049a-7a64-11e6-9966-3bd87af9f739.png)

![rebuild](https://cloud.githubusercontent.com/assets/20488700/18504922/ff7afdca-7a64-11e6-9614-7737929d180c.png)

![seo](https://cloud.githubusercontent.com/assets/20488700/18504926/01a478d8-7a65-11e6-8330-a4dc9e7cb55b.png)

**Comment by jtw372** [comment]
Hi Akamura, have you figured this out.  I have a similar problem as well and cannot find a solution

**Comment by skhell** [comment]
hi @jtw372 still not but I will try this week to delete and reimport all the products since I'm still in dev roadmap.

**Comment by jtw372** [comment]
@akamura out of curiosity, how are you importing products?  Through a csv or an integration of some sort?  For me, I used "Store Manager" for the import and have the same issues you do.  However, when I edit the category page and resave it (manually), flush the cache and reindex, the URLs function somewhat correctly, other than the product url adding the suffix twice (.html.html)

**Comment by skhell** [comment]
@jtw372 I have made some tests deleting entire catalog and importing a new one. Products URL now are correctly rewrite but category URL still not they appear in this format:

> catalog/category/view/s/tshirt/id/454/

**Comment by skhell** [comment]
@veloraven 
Olga I made another test within the Magento Backend and console:

### The console method:

`php bin/magento index:reindex`

**Result:**
Reindex is correctly executed but no categories is rewritten, the path remain the same as reported before.

### The backend method
1. login to the backend
2. go to the category menu
3. select the tshirt category
4. press the save button on top right

**Result:**
SUCCESS the category is now SEO optimized.

**Problems:**
1. if I import my CSV catalog again all categories loose the rewrite

**Comment by MattDelac** [comment]
@veloraven 
@akamura 

**Update:**
Magento 2.1.3
Mariadb
PHP 7

**Scenario:**
I want to import my product with a csv. If I specify a "url-key", I would expect to have the product's url update. But it does not. It's like Magento does not go till the end while reindexing

**Steps to reproduce:**
- Create some products (with a csv or manually)
- Create a csv with two columns "sku" & "url_key"
- Specify a new "url_key" for a product

**Actual result:**
- In the backend, the key changed but it has not effect on the frontend
![selection_340](https://cloud.githubusercontent.com/assets/18557047/22011930/cf1c8a6a-dc91-11e6-91e5-d4e214008ca2.png)
- But the key on the frontend did not change at all
![selection_341](https://cloud.githubusercontent.com/assets/18557047/22011933/d8f4e1ae-dc91-11e6-9c6d-20de06be95b1.png)
- And if I enter the new url key on my browser (As it's shown in the backend), I get a 404
![selection_342](https://cloud.githubusercontent.com/assets/18557047/22011949/efdc7d6e-dc91-11e6-8cf6-86f35d78088d.png)


**Result expected:**
- It should update the url key's product in the frontend

**Comment by MattDelac** [comment]
Guys,

Do you have any idea to bypass this problem ? (Like a script or a module)

Thank you
Matt

**Comment by thlassche** [comment]
@MattDelac Yes I have, you can contact me or lookup the Magento Marketplace

**Comment by pixiemediaweb** [comment]
same issue here.  The problem effects products which were migrated using the data migration tool.  You can see in the catalog_product_entity_varchar table, the url key updates, but the url_path remains the same and since the path is used for the url rewrite, it never updates the frontend url. 

@thlassche did you have a solution?

**Comment by thlassche** [comment]
@tomdollarmpd Yes, it's on the Magento Marketplace (look for rewrites)

**Comment by marcie8** [comment]
@thlassche Also for category rewrites?

**Comment by eharvest** [comment]
Any update on this? I have a few hundreds 301 to do, was going to get our data entry person do it in Magento admin, but now have to do it in .htaccess file. If you use ../pub/ as root folder then use /pub/.htaccess file for 301.

**Comment by thlassche** [comment]
@marcie8 Not yet, working on that at the moment. Will update here when it's ready

**Comment by magento-engcom-team** [comment]
@akamura, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by kllee824** [comment]
I have problem reported from administrator, she have update the product such add/delete images, the URL rewrite will be updated as result 404, due to the original url_rewrite record is deleted and insert new record and request_path is '.html'. We are running on EE 2.0.11 
would like to clarify is same issue?

**Comment by OZZlE** [comment]
We upgraded from 2.1.9 to 2.1.12 worked fine at first but then we added new magento websites and storeviews and the new ones all get catalog/category/view/s/[cat]/id/[id]/ even after reindexing and clearing cache.

We've also used the migration tool to get the products. All websites share the same root category.

I have tried to assign all products to the new websites, resaving categories and reindexing multiple times, no luck.

**Comment by donniesg** [comment]
@OZZlE I have the same problem. The same products work fine (shows the SEO URL) on some storeviews and not others (shows the "/catalog/product/view/id/..."). Reindexing does not work. 

However, if I use the admin panel to make a change to the SEO URL of a product for that new storeview, the default SEO URL will now be displayed. Strangely, the new SEO URL at the storeview level is ignored. 

I tried to change the default URL for this product. All the working storeviews shows the change but storeview with the problem is now stuck with the old one. 

FYI. I am also on 2.1.12.

**Comment by donniesg** [comment]
@OZZlE Our problems could be related to https://github.com/magento/magento2/issues/8227

**Comment by OZZlE** [comment]
@donniesg thank you!

**Comment by ovidiucaramida** [comment]
You can rebuild URL rewrites from admin area using this extension. It also allows you to customize the URLs and generate unique URLs by adding for ex the SKU in the URL

https://marketplace.magento.com/webpanda-catalog-url-rewrites.html
