### ISSUE TITLE
Custom theme requirejs-config not loading custom javascript

### ISSUE THREAD

**Issue by Colir** [magento/magento2#6607]
Hi.

I think i'm doing something wrong, but i did'nt see what and i'm going crazy.
I try to load a custom JS file on all my magento (2.1) page.

So, according to the doc, i put my js file in "web/js" of my theme, then i create a requirejs-config.js at the root of my theme.

My config file is correctly merge with all the the requirejs-config file.

But i don't know why : the js file specified did'nt load (no 404, just not load....)

here is my file

```
var config = {
    "map": {
        "*": {

            "plugins": "js/plugins",
            "themeapp": "js/custom"
        }
    }
};
```

and an extract of complete file generated

```
...
require.config(config);
})();
(function() {
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

var config = {
    map: {
        '*': {
            wishlist:       'Magento_Wishlist/wishlist',
            addToWishlist:  'Magento_Wishlist/js/add-to-wishlist',
            wishlistSearch: 'Magento_Wishlist/js/search'
        }
    }
};
require.config(config);
})();
(function() {
var config = {
    "map": {
        "*": {

            "plugins": "js/plugins",
            "themeapp": "js/custom"
        }
    }
};
require.config(config);
})();

})(require);
```

Thanks for you help.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by Colir** [comment]
Ok thanks
