### ISSUE TITLE
Unable to send the cookie. Size of 'mage-messages' error message

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6608]
I'm not sure if this a magento error or because I have added a custom module. Basically we have a book shop and people can buy ebooks. We connect to a third party to get the ebook url. So I have a module that using a preference for Magento\Downloadable\Controller\Download\Link goes to my controller instead. I have everything the same as the original controller except i have some extra bits to connect via soap:

I have extended this part:

```
        if ($linkPurchasedItem->getLinkType() == DownloadHelper::LINK_TYPE_URL) {
            $resource = $linkPurchasedItem->getLinkUrl();
            $resourceType = DownloadHelper::LINK_TYPE_URL;
```

to:

```
        if ($linkPurchasedItem->getLinkType() == DownloadHelper::LINK_TYPE_URL) {
            $resource = $linkPurchasedItem->getLinkUrl();
            $linkPurchased = $this->_objectManager->create('Magento\Downloadable\Model\Link\Purchased')->load($linkPurchasedItem->getPurchasedId());

            if ($resource == '') {
                $this->messageManager->addNotice(__('An error occurred while getting the requested content. Please contact the store owner. (resource id is missing)'));
                return $this->_redirect('*/customer/products');
            }

            try {
                $request = array(
                    'isbn13' => $resource,
                    'formatCode' => strtoupper($linkPurchasedItem->getLinkTitle()),
                    'deliveryId' => $linkPurchased->getOrderIncrementId() . '-' . $linkPurchasedItem->getId(),
                    'user' => $this->username,
                    'password' => $this->password,
                    'securityToken' => $this->securityToken
                );
                $options['cache_wsdl'] = WSDL_CACHE_NONE;
                $client = new \Zend\Soap\Client($this->wsdl,$options);
                $result = $client->getDownloadUrl($request);
                $resource = $result->url;
                $this->logger->info("Downloadable resource id: " . $resource);
                } catch (SoapFault $s) {
                    $this->logger->debug("Downloadable error: " . 'ERROR SOAP: [' . $s->faultcode . '] ' . $s->faultstring);
                    $this->messageManager->addNotice(__('An error occurred while getting the requested content. Please contact the store owner. (INC26s)'));
                    return $this->_redirect('*/customer/products');                 
                } catch (Exception $e) {
                    $this->logger->debug("Downloadable error: " . $e->getMessage());
                    $this->messageManager->addNotice(__('An error occurred while getting the requested content. Please contact the store owner. (INC26e)'));
                    return $this->_redirect('*/customer/products');                 
                }
            $resourceType = DownloadHelper::LINK_TYPE_URL;    
```

But when I click on a link in the my downloadable products section link i get the following error message:

1 exception(s):
Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 12786 bytes.

Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 12786 bytes.
#0 /Users/chris/Sites/git/magento21/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(116): Magento\Framework\Stdlib\Cookie\PhpCookieManager->checkAbilityToSendCookie('mage-messages', '[{"type":"error...')
#1 /Users/chris/Sites/git/magento21/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(98): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie('mage-messages', '[{"type":"error...', Array)
#2 /Users/chris/Sites/git/magento21/vendor/magento/module-theme/Controller/Result/MessagePlugin.php(84): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie('mage-messages', '[{"type":"error...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata))
#3 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(152): Magento\Theme\Controller\Result\MessagePlugin->afterRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Magento\Framework\View\Result\Page\Interceptor))
#4 /Users/chris/Sites/git/magento21/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#5 /Users/chris/Sites/git/magento21/vendor/magento/framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#6 /Users/chris/Sites/git/magento21/vendor/magento/module-downloadable/Controller/Customer/Products.php(59): Magento\Framework\App\View->renderLayout()
#7 /Users/chris/Sites/git/magento21/var/generation/Magento/Downloadable/Controller/Customer/Products/Interceptor.php(37): Magento\Downloadable\Controller\Customer\Products->execute()
#8 /Users/chris/Sites/git/magento21/vendor/magento/framework/App/Action/Action.php(102): Magento\Downloadable\Controller\Customer\Products\Interceptor->execute()
#9 /Users/chris/Sites/git/magento21/vendor/magento/module-downloadable/Controller/Customer/Products.php(44): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Downloadable\Controller\Customer\Products->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Downloadable\Controller\Customer\Products\Interceptor->___callParent('dispatch', Array)
#12 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Downloa...', 'dispatch', Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Array, 'contextPlugin')
#13 /Users/chris/Sites/git/magento21/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#14 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Downloa...', 'dispatch', Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Array, 'customer-app-ac...')
#16 /Users/chris/Sites/git/magento21/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#17 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Downloa...', 'dispatch', Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Array, 'storeCheck')
#19 /Users/chris/Sites/git/magento21/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#20 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Downloa...', 'dispatch', Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Array, 'weee-app-action...')
#22 /Users/chris/Sites/git/magento21/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#23 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Downloa...', 'dispatch', Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Array, 'tax-app-action-...')
#25 /Users/chris/Sites/git/magento21/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Downloadable\Controller\Customer\Products\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#26 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Downloadable\Controller\Customer\Products\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /Users/chris/Sites/git/magento21/var/generation/Magento/Downloadable/Controller/Customer/Products/Interceptor.php(26): Magento\Downloadable\Controller\Customer\Products\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /Users/chris/Sites/git/magento21/vendor/magento/framework/App/FrontController.php(55): Magento\Downloadable\Controller\Customer\Products\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#31 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#32 /Users/chris/Sites/git/magento21/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#33 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 /Users/chris/Sites/git/magento21/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#36 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#38 /Users/chris/Sites/git/magento21/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#39 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#41 /Users/chris/Sites/git/magento21/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#42 /Users/chris/Sites/git/magento21/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /Users/chris/Sites/git/magento21/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#44 /Users/chris/Sites/git/magento21/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /Users/chris/Sites/git/magento21/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#46 /Users/chris/Sites/git/magento21/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#47 {main}

Any ideas why this might be happening or what I've done?
### Preconditions

magento 2.1
php 7.0.9

**Comment by ghost** [comment]
anyone have any ideas?

**Comment by ae-mo** [comment]
What was the problem?
