### ISSUE TITLE
There's a way to add multiple dependences with the <depends>tag in widget.xml file ?

### ISSUE THREAD

**Issue by greg-hoarau** [magento/magento2#6611]
### Preconditions

1. Magento CE ver. 2.1.0 with sample data.
### Steps to reproduce

1. I have a widget.xml file that work properly,
2. `<depends><parameter name="name1" value="1" /></depends>`
### Expected result

1. Need a way to use multiple dependences.
### Actual result

1. Can only use one dependence.

Thanx

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/There-s-a-way-to-add-multiple-dependences-with-the-lt-depends-gt/idi-p/49584).
