### ISSUE TITLE
HTML in Terms and Conditions breaks the editing view

### ISSUE THREAD

**Issue by korhan1** [magento/magento2#6612]
### Preconditions

1. Magento ver. 2.1.0
### Steps to reproduce

1. Go to Stores -> Term and Conditions
2. Create a new condition.
3. Style the text with HTML tags, (p, ul, etc)
4. Save the page
5. Try to open it again
### Expected result

1. You should get into an editing view, the same one you used to create the condition in the first place
### Actual result

1. This error page comes up:
   ![errors](https://cloud.githubusercontent.com/assets/22194207/18511416/3e164aae-7a8c-11e6-98c9-9e627f125bf8.png)

**Comment by veloraven** [comment]
@korhan1 thank you for your report.
Unfortunately I was not able to reproduce  your problem.
Could you please provide exact html code you use as well as full description of all settings of the created Terms and Conditions item (you can use screenshot for it if you like).
Please also specify your system parameters: OS, versions of PHP, MySQL, wev-server, browser.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
