### ISSUE TITLE
Date & Time localized formatting - 09/14/2016 vs. 14.09.2016 (de_DE) doesn't work

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#6613]
### Preconditions
1. Magento 2.0.7
2. Default Country: Germany
3. Backend and frontend translated to german
4. Backend-user default language: de_DE
5. Date sorting: Day / Month / Year
6. Adress and everything regarding the localization is set to Germany
### Steps to reproduce
1. Using Magento2 for a german setup I configured the Store with the settings (3. > 5.) mentioned above.
2. Comparing to Magento1 I expected the date & time formatting to change automatically, based on the default country. But instead the default formatting of en_US is used by Magento.

For Example: New Customer / Birthday (Birthday = "Geburtstag")
![bildschirmfoto 2016-09-14 um 15 03 40](https://cloud.githubusercontent.com/assets/15127451/18513385/8f0bd798-7a8d-11e6-9146-5dc548104625.png)
Expected result: 14.09.2016 (as seen in Magento 1.9)
![bildschirmfoto 2016-09-14 um 15 04 14](https://cloud.githubusercontent.com/assets/15127451/18513398/980c5e44-7a8d-11e6-9f17-62c2c7deb10b.png)
Expected result: 24. Sept. 1987
1. Looking deeper into the vendor folder of the zend-framework I couldn't find any location based formatting file as seen in Magento1.9 (https://github.com/engineyard/magento-ce-1.9/blob/170c1a51387428fb56f3ada2504d52a2b130360a/lib/Zend/Locale/Data/de.xml  | date-formatting begins at line #1019)
### Expected result

Date & Time formatting should change, based on the default country setting
### Actual result

Magento keeps formatting it the en_Us way.
### Additional Info

We had a similar problem regarding formatting the currency (EUR). Magento2 ignored our german configuration and formatted the price in en_US. Overwriting the getlocale variable within the zend-framework to DE for the currency did the trick, but not for formatting the date.

I don't know whether I missed some important settings or it's a Magento Bug.
Thank you in advance!

**Comment by antboiko** [comment]
Hi, @leanderfritsche 

Thanks for reporting. We already have this issue here #6350 so I will close this one because of duplication. You can watch progress on #6350 if you need.

Regards,
Anton.
