### ISSUE TITLE
Configurable Products not saving

### ISSUE THREAD

**Issue by neildavey** [magento/magento2#6614]
Upgraded release at a time from 2.1.0 to 2.1.1 
using bespoke theme on top of Luma theme. No modifications to core files
PHP7 Mysql 5.6.25 10.0.27-MariaDB linux 16.04.2 Apache 2.4.23

**Steps to reproduce**

Upgraded via wizard 2.1.0 to 2.1.1.
Go to Admin
Add Product. Add Configurable Products. Save.

**Expected result**

Configurable products showing after save

**Actual result**

Configurable products disappeared after Saving 

Indexing and Cache clearing and no effect

**Comment by jignesh26** [comment]
@neildavey 

Have you tried to Delete the whole var folder and run the di:compaile comand , setup upgrade and content deploy  ?

**Comment by neildavey** [comment]
Hi,
Thanks for the reply. I appreciate it.

I have only done this:  deleted var/view_preprocessed    and   pub/static then ran the content deploy command only.

I have noticed this though - I’m not sure if this has something to do with it
Running reindex - I get this result - the other indexes are fine

Product Price index is locked by another reindex process. Skipping.

**Comment by oshmyheliuk** [comment]
Hi @neildavey ,

I cannot reproduce this issue. Configurable products are saving and showing without any errors.
Is this issue still actual?

**Comment by neildavey** [comment]
It has just been fixed - thanks very much
