### ISSUE TITLE
configurable_variation_labels not appearing on product page after 2.1.0 upgrade

### ISSUE THREAD

**Issue by shires-boy** [magento/magento2#6615]
### Preconditions

Upgraded one release at a time from CE 2.0.7 to 2.1.1 the issue only shows on releases CE 2.1.0 and 2.1.1 
releases CE 2.0.7 2.0.8 2.0.9 do not have this issue.
using the default Luma theme with no changes
PHP7 Mysql 5.7.13 ubuntu 16.04.2 Apache 2.4.18
### Steps to reproduce
1. Upgrade via cli composer from CE 2.0.9 to 2.1.0 (including the patch MDVA-532)
2. Go to the website 
3. Go to product page where the csv loaded file has configuration_variation_labels column with values. 
### Expected result
1. Configurable product special attributes (the questions) should be narrated with the text in configurable_variation_labels column against that attribute e.g. "Select your fabric combination"
### Actual result
1. Screen shows the attribute default label field i.e. "Colour Option"

Note the configuration_variation_labels data is present in the catalog_product_super_attribute_label table and correctly linked to the product
Re indexing and refreshing the cache does not make any difference

**Comment by nmallepally** [comment]
I have same experience after upgrading from 2.0.7 to 2.1.0.
config attributes disappears and displays back after reindexing again.
![missing attribute](https://cloud.githubusercontent.com/assets/19605497/19924381/9370d014-a0e3-11e6-8963-605a99d3ad01.png)
![after man index](https://cloud.githubusercontent.com/assets/19605497/19924384/95d0fba4-a0e3-11e6-8c78-84922cda0341.png)

Any temporary solution or work around?

**Comment by magento-engcom-team** [comment]
@shires-boy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by shires-boy** [comment]
This is an issue on EE 2.2.0 
I loaded up the super attribute label via the product csv file column configurable_variation_labels i.e. "colour_option=Fabric colour" as you can see it loaded on the database but the product page does not show the label, it shows the attribute label.
![image](https://user-images.githubusercontent.com/22196042/36588290-94791dee-187f-11e8-8d69-8aa600b621c8.png)

**Comment by nige-one** [comment]
This is in fact still a thing in 2.4.1!

The template does not use the `value` of the product specific super attribute configuration from `catalog_product_super_attribute_label` in

https://github.com/magento/magento2/blob/3b397a99a59d300ebf20dcbe7d8fa22e6842b2d1/app/code/Magento/ConfigurableProduct/view/frontend/templates/product/view/type/options/configurable.phtml#L17

but uses the attribute's store label.
Instead of it a
```
<span><?= $block->escapeHtml($_attribute->getLabel()) ?></span>
```
will do the trick.

Of course one should make sure that StoreView stuff is taken into account.
Moreover the UI in the backend is missing for this.
