### ISSUE TITLE
Can't modify product link widget conditions

### ISSUE THREAD

**Issue by Pigau** [magento/magento2#6616]
Hi,
I notice a bug when you create a product list widget in a CMS page. If you try to update your widget parameter the whole conditions tree is reseted.
### Preconditions

In Magento 2.1.0 (community)
### Steps to reproduce
1. Create a new CMS page
2. Add a product list widget on this page
3. Define some condition in the widget parameters
4. Insert the widget and save the page
5. Try to edit your widget on this page
### Expected result
1. The previous set conditions should be shown
### Actual result
1. The condition parameter is empty

Thank you in advance!

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59280. Thanks for reporting.

**Comment by EliasKotlyar** [comment]
We can also confirm, that we can reproduce this Bug.

**Comment by slavvka** [comment]
@Pigau, the issue has been fixed and will be delivered in Patch Release 2.1.5

**Comment by koenner01** [comment]
@slavvka has this been pushed to develop already ? If so could you link us the commit.

**Comment by koenner01** [comment]
Btw, this issue is related with https://github.com/magento/magento2/issues/2913
