### ISSUE TITLE
Redis Full Page Cache causes PHP error on catalog view

### ISSUE THREAD

**Issue by mombrea** [magento/magento2#6617]
### Preconditions

1.  Magento version 2.1.1
2.  Redis Server 3.0.3
3.  Full Page Cache Enabled
4.  PHP 5.6
### Steps to reproduce

1.  Configure Cm_Cache_Backend_Redis
2.  Enable all Caches including Full Page Cache
3.  Visit a category page on the frontend
4.  Blank page or 500 error
### Expected result

1.  The category page should load
### Actual result

1.  500 error
2.  PHP Fatal error:  Call to a member function getIdentities() on null in /vendor/magento/module-catalog/Block/Product/View.php on line 373

**Comment by ihor-sviziev** [comment]
I haven't this issue.
Did you tried to execute `php bin/magento setup:di:compile`?

Could you enable developer mode and provide full exception trace?

**Comment by mombrea** [comment]
Yes, I've tried compiling. I'm unable to get an exception trace from Magento, PHP errors out first and throws a 500. The problem is in the function getIdentities() on the line:
`$identities = $this->getProduct()->getIdentities();`

`$this->getProduct()` is null when Full Page Cache is enabled.

If I wrap the offending function in a null check, I get the attached stack trace:
[stack.txt](https://github.com/magento/magento2/files/474875/stack.txt)

**Comment by mombrea** [comment]
This appears to be theme related. After switching back to Luma the category pages work properly.

**Comment by pantaoran** [comment]
It appears that I'm also having this exact situation after turning on the full page cache.
Even if it was a theme error, could you give any hints as to how you solved it? @mombrea

**Comment by hostep** [comment]
@pantaoran: does this help: https://github.com/magento/magento2/issues/5897?

**Comment by pantaoran** [comment]
I have solved it before I saw your comment, but thanks.

We had a page that worked as an "All categories" page, and since that didn't have a clearly assigned category the getIdentities() didn't work. The solution was to override that function in our block and create some custom cache tags for it.

For understanding this it's very important to understand how the whole full page caching works in M2.
