### ISSUE TITLE
Cannot save swatch attribute in release 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by shires-boy** [magento/magento2#6619]
Get Notice: Undefined offset: 1851 in /var/www/html/xxx/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 177 when saving an attribute with 3,000 swatch options

This worked OK in CE 2.0.7 2.0.8 and 2.0.9 but to get this to work in 2.1.0 and  2.1.1 I need to change the php.ini max_input_vars from 1,000 to 15,000.

I understand this is not desirable from a DOS attack perspective.
### Preconditions

CE 2.1.0
PHP7 Mysql 5.7.13 ubuntu 16.04.2 Apache 2.4.18
### Steps to reproduce
1. Enable attribute for configurable product definition with 3,000 swatch options
2. Upgrade to CE 2.1.0 including mandatory patch
3. Via the back office go stores / product attributes
4. Select attribute with 3,000 swatch options (note the swatches do not need to have a file associated)
5. Click on Save Attribute
### Expected result
1. Attribute Updated
### Actual result
1. Error Notice: Undefined offset: 1851 in /var/www/html/xxx/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 177

![image](https://cloud.githubusercontent.com/assets/22196042/18522818/8439ffea-7aa9-11e6-9756-8162681058c5.png)

**Comment by heldchen** [comment]
what we do on our customers shops:
- the admin backend runs on a different website (admin.store.com) 
- admin.store.com has an additional basic auth login to protect the site from scripted attacks
- admin.store.com runs a different php-fpm instance with much longer timeouts and higher max_input_vars settings etc.
- the frontend admin urls are redirected (store.com/admin -> admin.store.com)

having separated php configs for frontend and backend is something that really saved us several times in the last few years. might be worth considering for your installation as well.

**Comment by shires-boy** [comment]
Many thanks heldchen whilst it is a workaround, it is an acceptable one.

**Comment by shires-boy** [comment]
The workaround has added benefits, so will take that route.
