### ISSUE TITLE
nl2br does not work for ui components (admin grid)

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#6620]
I made a new table in the database and want to show it as a grid in the admin section.
### Steps to reproduce
1. create table in database
2. create UI component for admin grid 
3. add `<item name="nl2br" xsi:type="boolean">true</item>` to column config
### Expected result
1. Column should have data split into lines using `<br>` if there is new line in string
### Actual result

column is displayed as single line.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by kandrejevs** [comment]
@davidalger that is a technical issue. See `vendor/magento/module-review-staging/view/adminhtml/ui_component/stagingreview_listing.xml:101`. This is core functionality that does not work.

**Comment by ClaudiuCreanga** [comment]
@kandrejevs It worked for me if I added                     ```<item name="bodyTmpl" xsi:type="string">ui/grid/cells/html</item>```
