### ISSUE TITLE
Component Manager will hangs

### ISSUE THREAD

**Issue by aarondong2005** [magento/magento2#6621]
Preconditions
1. Fresh installed Magento 2.1.1
2. Data migrated from Old Magento 1.9.0.1
2. PHP 7.0.10 + MySQL 5.6.32

Steps to reproduce
1. After migration everything works fine. But when I want to install plugin from component manager it will hangs on the "Please wait" screen. 
2. If close hangs page and open a backend page. The backend will not load too.
### Actual result
1. ![hangs-1](https://cloud.githubusercontent.com/assets/15516555/18533532/6246e2ec-7a98-11e6-934e-1fa0f8be4104.jpg)

**Comment by aarondong2005** [comment]
Don't know why but the var/di doesn't exist. So I tried to di:compile, then I got error below

`Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 42.0 MiBPHP Fatal error:  Cannot declare class Migration\Step\Version11410to2000Test, because the name is already in use in /chroot/home/dashcamt/yyyyyy.com/html/vendor/magento/data-migration-tool/tests/unit/testsuite/Migration/Step/UrlRewrite/Version11410to2000Test.php on line 109`

**Comment by aarondong2005** [comment]
I tried refresh install Magento only without migrate. The component manager still hangs.

**Comment by stamster** [comment]
Most commonly you have permissions issue. Check your logs, and open F12 developer tool in your browser to see what went wrong during that ajax loading.

**Comment by NadiyaS** [comment]
Hi @aarondong2005 ,
how did you do refresh install? Please use `bin/magento setup:uninstall` (pay attention that after this command your DB will be cleaned) and then try to install Magento again. Or you can clean the cache and run `bin/magento setup:di:compile` again.

**Comment by aarondong2005** [comment]
the di was done without problem. But now the manager still hang. Someone facing the same issue. here https://github.com/magento/magento2/issues/6737

**Comment by BaDos** [comment]
Hi @aarondong2005

How many repositories are there in composer.json?
Do you have some errors in browser console?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
