### ISSUE TITLE
String wont translate: "Please enter a valid number in this field."

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#6622]
### Preconditions

1. Using magento 2.1.1
2. PHP 7.0
### Steps to reproduce

1. When trying to pay with Authorize.net module, string "Please enter a valid number in this field." won't translate, despite having the following lines in my csv file:

"Please enter a valid number in this field.","V to polje vnesite veljavno številko.",module,Magento_Catalog
"Please enter a valid number in this field.","V to polje vnesite veljavno številko.",module,Magento_Ui
### Expected result

1. The string "Please enter a valid number in this field." should translate the same as almost all other strings do.
### Actual result

![capture](https://cloud.githubusercontent.com/assets/282687/18534032/dabf2d0c-7ae7-11e6-8de3-a16b1152f761.PNG)

**Comment by quienti** [comment]
Already fixed in develop branch
Pull Request here : https://github.com/magento/magento2/pull/5725

**Comment by davidalger** [comment]
Closing as fixed in upcoming release. Please re-open if the bug persists on develop branch.

**Comment by Ctucker9233** [comment]
@davidalger this appears to have not been fixed in the 2.1.2 release. Is it safe to manually merge the fixed code on a 2.1.2 production environment?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72249

**Comment by marilena6** [comment]
I am using 2.1.4 and facing this issue, is there a patch or anything?
