### ISSUE TITLE
how to install Extensions in magento 2.1

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#6623]
I  try to This Site  https://www.fastcomet.com/tutorials/magento2/installing-extensions

But Not Work How To solve that  Please Help me...
![error](https://cloud.githubusercontent.com/assets/16436069/18540819/e949c0b0-7b3e-11e6-9e6a-05bd3ce7a5e8.PNG)

Which Site refer  And  comment All Step For Install Extension in magneo 2.1

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
