### ISSUE TITLE
Quote breaks if custom option deleted

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#6627]
If a product is setup with a custom option, the product is added to the cart but then subsequently the custom option is removed from the product then the customers cart is broken and they view there cart, add products, checkout etc...
### Preconditions
1. Magento CE 2.1.*
2. A product with a custom option (drop down)
3. A registered customer
### Steps to reproduce
1. Login as the registered customer
2. Add the product to the cart, selecting a value for the custom option
3. Login as an admin user and remove the custom option from the product and save
4. Try to proceed to the basket as the customer, or add a new product, or even just logout
### Expected result
1. The customers quote is updated with the options removed from the quote item and the customer can continue as normal
### Actual result
1. An error is thrown (depending on what you are trying to do)

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59279. Thanks for reporting

**Comment by IvanRybakov** [comment]
Any update?

**Comment by magento-engcom-team** [comment]
@alexgoodey, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by shakthivelp** [comment]
May I know what are files that has been changed ?

I am using magento 2.1

**Comment by KrishnaK-Z** [comment]
Can I please get the related commits on this issue.
