### ISSUE TITLE
M2.1.1 : REST API V1 "The payment method you requested is not available." when trying to save a payment method for an order

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6628]
I try to set the payment method for an order using the REST API, but without success. If I fetch a list of payment methods using `GET /rest/V1/guest-carts/ac6066cd77d55c224f3e9c0e6bd7e01e/payment-methods`, I get a JSON response with the payment methods available for this quote:

```
[{"code":"checkmo","title":"Check \/ Money order"}]
```

But... When I try to set a payment method for the order using the REST API using the following URL: 
`PUT /rest/V1/guest-carts/ac6066cd77d55c224f3e9c0e6bd7e01e/selected-payment-method` with the following data:

```
{"method":"checkmo"}
```

I get the following response (400 error):

```
{
    "message": "The payment method you requested is not available.",
    "trace": "#0 \/var\/www\/public\/vendor\/magento\/module-quote\/Model\/Quote\/Payment.php(260): Magento\\Payment\\Model\\Info->getMethodInstance()\n#1 \/var\/www\/public\/vendor\/magento\/module-quote\/Model\/Quote\/Payment.php(156): Magento\\Quote\\Model\\Quote\\Payment->getMethodInstance()\n#2 \/var\/www\/public\/vendor\/magento\/module-quote\/Model\/PaymentMethodManagement.php(64): Magento\\Quote\\Model\\Quote\\Payment->importData(Object(Magento\\Framework\\DataObject))\n#3 \/var\/www\/public\/vendor\/magento\/module-quote\/Model\/GuestCart\/GuestPaymentMethodManagement.php(49): Magento\\Quote\\Model\\PaymentMethodManagement->set('3', Object(Magento\\Quote\\Model\\Quote\\Payment))\n#4 [internal function]: Magento\\Quote\\Model\\GuestCart\\GuestPaymentMethodManagement->set('ac6066cd77d55c2...', Object(Magento\\Quote\\Model\\Quote\\Payment))\n#5 \/var\/www\/public\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#6 \/var\/www\/public\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#7 \/var\/www\/public\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/public\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/public\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#10 \/var\/www\/public\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#11 {main}"
}
```
### Preconditions
1. Magento 2.1.1 
2. REST API V1
3. I place the order as a guest
4. Stock installation (no other extensions)
### Steps to reproduce
1. Create an order 
2. Fetch the available payment methods
3. Pick one
4. Set the payment method using the REST API.
### Expected result
1. The payment method should be set for the quote 
### Actual result
1. I get above error that the payment method is not available.

**Comment by mbrinton01** [comment]
@kanduvisla please provide the full body you are using in the `PUT selected-payment-method` call.  It should follow the syntax from Swagger for `PUT /V1/guest-carts/{cartId}/selected-payment-method`:

```
{
  "method": {
    "po_number": "string",
    "method": "string",
    "additional_data": [
      "string"
    ],
    "extension_attributes": {
      "agreement_ids": [
        "string"
      ]
    }
  }
}
```

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new together with an answer for the question above.

**Comment by kanduvisla** [comment]
For anyone who was wondering: it turned out that I was not saving my country code with my address. Therefore the payment method could also not be stored.
