### ISSUE TITLE
improving product options rendering

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#6630]
Product options HTML is generated in two ways:
- by options template 
- by swatch-renderer.js (if you have any swatch attribute on product)

What does it mean?
- extending look of swatches mean complex rewrite of JS renderer (to be able upgrade later)
- if you have any product without any swatch attr (quite usual), you have to also modify options template (doubled work)

Ideas what to do?
- merge logic into UI component 
- some kind of inheritance from non-swatch to swatch approach
- get rid of HTML generation with JS string concats!

Main objective?
- streamlined customization 
- better extendability 
- M2 approach

**Comment by anton-huz** [comment]
Hi, Filip.
Currently, your reported issue is in internal discussion. We will add notes here when will make a decision.

P.S.: personal thanks for raising a problem.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/improving-product-options-rendering/idi-p/48897).
