### ISSUE TITLE
Magento 2.1 Cannot Add New Product in Admin

### ISSUE THREAD

**Issue by jstoel** [magento/magento2#6631]
When trying to manually add a product, the screen laods, is greyed out and the spinning wheel spins indefinately.
### Preconditions

1. Magento v. 2.1.1
2. php 7.0.8
3. MySQL MariaDB 10.0.25
### Steps to reproduce

1. Upgrade to to v 2.1.1
2. Products>Catalog>Add Product
### Expected result

1. New product window loads
### Actual result

1. Greyed out and wheel spins indefinitely
   <img width="1158" alt="screen shot 2016-09-15 at 6 41 56 pm" src="https://cloud.githubusercontent.com/assets/22224049/18572910/224b8fd0-7b74-11e6-8a04-40c3cace9190.png">

**Comment by epadmin** [comment]
I had this same problem.   I had installed the Maintenance Mode extension from Customer Paradigm.   We are not sure if that was it, but I disabled the plugin and also increased my PHP memory.   My server was 758 M by default.  There is somewhere that recommends it is 2G so I upped it and between the PHP memory increase and the extension it is working now.    I am totally not the developer so if this doesn't make sense someone else will have to jump in.   I think the memory setting might have been in an htaccess file?  Its possible there was more than 1 location or file that we changed

**Comment by enrico69** [comment]
Hi.
Is something displayed in the log files?

**Comment by friizu** [comment]
I had same result and problem was disabled module, take a look what your browser console log says:
https://github.com/magento/magento2/issues/6430

**Comment by jstoel** [comment]
I have no disable modules. In fact all I have is a clean install with some products I've added. At first I thought it may be a resource issue but I can load all other parts of the admin just fine, I can duplicate a product just fine, and I can import csv files just fine. I'm stumped.

**Comment by heldchen** [comment]
check the browser's dev tool and see if any request leads in a 50x or javascript error upon page load.

**Comment by veloraven** [comment]
@jstoel thank you for your report.
Could you try to clear browser cache first? Including cookies and offline website data.

**Comment by jstoel** [comment]
I did. I even went on different computers with different browsers. It doesn't appear to be a javascript error either.

**Comment by jstoel** [comment]
I found a solution. @heldchen suggested to look for javascript errors while the page was loading and this error came up: Cannot read property 'replace' of null.

A little google search brought me to this link: http://magento.stackexchange.com/questions/127537/magento-2-1-uncaught-typeerror-cannot-read-property-replace-of-null. I followed the work around instructions and boom, the new product page began to load again.

The field "Mask for SKU" in the catalog>product fields auto-generation was blank in my case and by adding "{{sku}}" in the text field seem to solve the problem. Thanks for all your suggestions.

**Comment by paulespino** [comment]
Just to add to this issue:

I had the same problem as above. What I noticed is that IF ANY OF THESE FIELDS ARE EMPTY, the bug will show up. So make sure that ALL THE FIELDS have a "{{title}}" or "{{sku}}".

![screen shot 2017-01-09 at 9 32 27 am](https://cloud.githubusercontent.com/assets/271239/21774176/eefd8ce2-d64e-11e6-98eb-4703dbce8881.png)

**Comment by ajitwebile** [comment]
i am facing same issue in magento2.1.3, i created multi websites and try to assign products to created new websitesi found an error, No such entity.

**Comment by jstoel** [comment]
@ajitwebile my solution to all of Magento 2's bugs was to roll back to 1.9. I'm not happy about it but M2 is garbage.

**Comment by ajitwebile** [comment]
@jstoel  right bro, but right now i stuck in this issue, if anybody have answer please help.

**Comment by heldchen** [comment]
@ajitwebile have you tried the stackexchange post answer mentioned further above?

**Comment by epadmin** [comment]
we also scrapped the M2 project and went back to 1.9


-------- Original Message --------
Subject: Re: [magento/magento2] Magento 2.1 Cannot Add New Product in
Admin (#6631)
