### ISSUE TITLE
JCB and Diners Club/ Carte Blanch cards are not working in authorize.net Magento 2.1.1

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento/magento2#6633]
We are using magento 2.1.1 as a web store. In that we are using authorize.net payment and configured  sandbox account. On checkout when we try to use JCB and Diners Club/ Carte Blanch cards are showing validation error (http://www.awesomescreenshot.com/image/1586979/10e93825a7ed65e7ff634c5125a16827).

As we have checked the admin configuration seems fine. In authorize.net configuration section we have enabled all the cards(American Express, Visa, MasterCard, Discover, and Others). In the configuration "Others" (http://www.awesomescreenshot.com/image/1586960/911aad21324ba4e419d298791caa3db3) card selection was applicable to the JCB and Diners Club/ Carte Blanch cards. We have used below testing card numbers for testing.

JCB 3088000000000017
Diners Club/ Carte Blanch   38000000000006

Magento2's default authorize.net module itself having an issue.

Does anyone has a solution for this.

**Comment by YevSent** [comment]
Hi, @ewallkrishnaprakash , thanks for reporting, we've created internal ticket MAGETWO-59033.
Few additional comments:
- The `Other` option doesn't allow to use JCB and Diners Club, we are already removed this option, but instead it, we will add JCB and Diners Club to available credit cards list
- Your JCB `3088000000000017` is invalid. This card range doesn't correspond to JCB https://en.wikipedia.org/wiki/Payment_card_number

**Comment by alena-marchenko** [comment]
Hi @ewallkrishnaprakash 

Fix for MAGETWO-59033 ticket is already merged to develop branch.
Closing the issue, feel free to create new one if you experience further issues.
