### ISSUE TITLE
How to integrate cartspan with Sage 50 in magento2

### ISSUE THREAD

**Issue by poojalimagento** [magento/magento2#6636]
Hi,

Anyone can help me in integrating cartspan with 'Sage 50' in magento2 or provide a guide link so i can integrate also provide the link to check.
Please help me.

Thanks

**Comment by veloraven** [comment]
@poojalimagento thank you for your question.
But the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
