### ISSUE TITLE
Varnish Cache 5.0 support?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#6637]
Is M2 2.1.1 compatible with varnish 5.0?

http://varnish-cache.org/docs/5.0/whats-new/changes-5.0.html

**Comment by huayra** [comment]
Varnish 5.0 supports "vcl 4.0", so in theory it should support the artifacts used for that. 

It does not support VCL in Varnish 3.x or earlier.

Hope that helps.

**Comment by pboisvert** [comment]
Closing as this is not a coding issue report. Please direct questions to the Magento Stack Exchange or Community forum. If you do wish to file an issue please follow the guidelines for providing steps to reproduce the issue
