### ISSUE TITLE
Can't disable JS Bundling in adminhtml while keeping it enabled on frontend

### ISSUE THREAD

**Issue by hostep** [magento/magento2#6638]
### Preconditions
1. Magento CE 2.1.0
### Steps to reproduce
1. Disable JS Bundling in the 'Default Config' scope
2. Enable JS Bundling in either a Website or StoreView scope
3. Deploy the static assets
### Expected result

Bundled js files should not be used in the adminhtml
### Actual result

Bundled js files are still being used in the adminhtml
You just can't disable bundling in adminhtml when it is enabled in a lower scope.

**Comment by tkacheva** [comment]
@hostep I'm struggling to understand steps you are following. 
Scope selector that switches magento scopes influence Magento Storefront only. there is no possibility to switch  off JavaScript Bundling only for Admin Panel. 

What you are looking for is a functionality that magento doesn't support. 
Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by hostep** [comment]
Sorry for the late reply, I was away on holiday.

Anyway, @tkacheva, you are incorrect.

Traditionally in Magento (1 and 2) you can define configuration settings for the adminhtml by configuring them in the `Default Config` scope and override them for the frontend in lower scopes (website or storeview).

For example: we always set the `Default Config` locale to `en_US` while configuring the different storeviews to different locale's like `nl_NL`, `fr_FR`, `de_DE`, `es_ES`, `en_US`, ...
Which makes the adminhtml locale `en_US` and the frontend storeviews different locale's. So this use case obviously should work and has always worked traditionally (merging JS files in M1 as another example worked perfectly fine like this).

So @tkacheva: please reopen, tnx! :)

**Comment by hostep** [comment]
I still believe this has been incorrectly closed.
@tkacheva or @veloraven: can you please review this?
The issue is a minor one, but it is still a bug, so I think this should be reopened.

Thanks!
