### ISSUE TITLE
Readiness check fails when trying to install new Marketplace products

### ISSUE THREAD

**Issue by samuellinde** [magento/magento2#6641]
When running the readiness check for installing synced Marketplace products, it fails at the "Check cron scripts" step. It reports that it finds non-writable paths that don't actually exist.
### Preconditions
1. Magento 2.1.1, PHP 7.0.8, Apache 2.4.7
### Steps to reproduce
1. Run the readiness check required to install compontents via the wizard in the backend.
### Expected result
1. It should pass, or at least not complain about non-existent files and folders.
### Actual result
1. <img width="891" alt="screen shot on 2016-09-16 at 14-27-31" src="https://cloud.githubusercontent.com/assets/57992/18585939/4543d262-7c1a-11e6-937a-5160a5b39c8f.png">

**Comment by Ctucker9233** [comment]
Same here, only it fails on component dependency without actually saying what the conflicting dependency is.

**Comment by BaDos** [comment]
@samuellinde thank you for your report.

Cannot reproduce it.

How did you install Magento (via composer or git)?
What extension did you try to install?
Do you have the same issue for other extensions?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
