### ISSUE TITLE
Client side workflow - less file not overwriting same file in blank theme

### ISSUE THREAD

**Issue by helloeverything** [magento/magento2#6642]
### Preconditions

1.  Magento CE 2.1.1
2. Create a custom Theme with blank as parent
### Steps to reproduce
1. Add a _reset.less file into app/design/frontend/Vendor/theme/web/css/source/_reset.less
2. Set the developer workflow to Client Side (store > config > advanced > developer > 
   Frontend Development Workflow)
### Expected result

1. app/design/frontend/Vendor/theme/web/css/source/_reset.less file should override the same file from the blank theme
### Actual result

1. The _reset.less file in the custom theme is ignored and the file from Blank get used
2. This only happens when using the Client Side workflow type.

**Comment by magento-engcom-team** [comment]
@helloeverything, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
