### ISSUE TITLE
New Accounts Report returns empty collection

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#6644]
When viewing new accounts report, it is always empty.
### Preconditions
1.  enterprise edition, version 2.1.1, php 7
### Steps to reproduce
1.  register few customers in FE
2. view new accounts report in BE
3. filter by dates
### Expected result
1.  grid should contain information how many accounts are registered each day
### Actual result
1.  grid is empty

report grid: http://i.imgur.com/zsfAaum.png

customer grid: http://i.imgur.com/ERKSvBn.png

It is caused by exception
`DateTime::__construct(): Failed to parse time string (30/09/2016) at position 0 (3): Unexpected character`

changing `app/code/Magento/Reports/Block/Adminhtml/Grid.php:128`: 

```
$from = $this->_localeDate->scopeDate(null, $this->getFilter('report_from'), false);
$to = $this->_localeDate->scopeDate(null, $this->getFilter('report_to'), false);
$collection->setInterval($from, $to);

```

to

```
$date = new \DateTime();
$from = $date->createFromFormat('d/m/Y', $this->getFilter('report_from'));
$to = $date->createFromFormat('d/m/Y', $this->getFilter('report_to'));
$collection->setInterval($from, $to);
```

fixes the issue.

**Comment by kandrejevs** [comment]
new update, admin user locale was set to en_GB, so this bug is actually magento net being able to handle different locales

**Comment by veloraven** [comment]
@kandrejevs thank you for your report.
If you experience any problems with Enterprise Edition, please address them to Magento Support.
