### ISSUE TITLE
Special Price display issue for configurable product

### ISSUE THREAD

**Issue by praful-rajput** [magento/magento2#6645]
Generally, when we set a special price to any one child product of main product (Configurable).  Magento shows the the label/title like "Regular Price & Special Price" for applicable child product which has set special price. But it should not be display same label (format) to other child products if there is not set any special price.
### Preconditions
1. Magento CE 2.1.1
2. 
### Steps to reproduce
1. Installed Magento CE 2.1.1 with sample data.
2. Admin Panel >> Products >> Catalog :: Go to configurable product e.g."Erika Running Short" 
3. Edit any child product of this main product. Set special price to this child product and save it.
4. Search this main product from front-end.
5. By default it will display special price without selection of any swatches.
6. Select particular swatches,  price reflection will work fine. but the "Regular price & special price " label will display to all child product, where you didn't set special price for it.
   ### Expected result
   
   1.Displaing "Regular Price" label for all those products which have no any special price.
   ![special-2](https://cloud.githubusercontent.com/assets/648859/18588140/d66d1bea-7c42-11e6-90a0-c5923d48d61c.png)
### Actual result

1. It should not be display "Regular Price" label for those product which have no special price has been set. It should be display like as default. 
   ![price](https://cloud.githubusercontent.com/assets/648859/18588256/4ed39d52-7c43-11e6-8b9f-b2855fbbbe24.png)

**Comment by antboiko** [comment]
Hi @vasuscoin , thanks for reporting. This issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

I'm closing this one as a duplicate. Please see the issues below.

https://github.com/magento/magento2/issues/5097
https://github.com/magento/magento2/issues/4442

Regards,
Anton.

**Comment by praful-rajput** [comment]
thank you @antboiko

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.
