### ISSUE TITLE
newly created category not displaying on front-end

### ISSUE THREAD

**Issue by ketankulkarni** [magento/magento2#6652]
1. category  was created by manage category
2. attribute and attribute set was created
3. product was created and  assigned to category
4. all attribute  that causes product to show on front-end side  was set correctly
    e.g. status-enabled , qty > 0 , stock availability - in stock

Problem - after this procedure category was not displaying on front-end side

**Comment by veloraven** [comment]
@ketankulkarni thank you for your feedback.
Please identify which version of Magento you are running.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by ketankulkarni** [comment]
issue has been solved.it was related to custom theme
