### ISSUE TITLE
When i trying to create a new custom module in Magento 2 am getting the below error

### ISSUE THREAD

**Issue by venkyc07** [magento/magento2#6653]

**Comment by venkyc07** [comment]
os: ubuntu16.0.4LTS
apache2: 2.4.18
php: 7.0.8
mysql: 5.7


Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Json/JsonFile.php:152
Stack trace:
#0 /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Factory.php(269): Composer\Json\JsonFile->validateSchema(1)
#1 /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Factory.php(532): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), '/opt/lampp/htdo...', false)
#2 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#4 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformation.php(375): Magento\Framework\Composer\ComposerInformation->getComposer()
#5 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformatio in /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 152

**Comment by pboisvert** [comment]
@venkyc07 can you please follow the issue reporting template and provide full information on preconditions and steps to reproduce the error you are seeing

**Comment by venkyc07** [comment]
I added custom module code to my app folder. In order to display my module in admin panel i run this command "myroot directory# bin/magento setup:upgrade". After runing this command am getting the error. I searched lots n lots in google but am still not solved the issue. plzz any one can help me. Thanksss in advance...!

Magento 2.1.1
PHP: 7.0.8 3.MySql: 5.7 4.Apache2: 2.4.18
os: ubuntu16.0.4LTS
Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Json/JsonFile.php:152
Stack trace:
#0 /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Factory.php(269): Composer\Json\JsonFile->validateSchema(1)
#1 /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Factory.php(532): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), '/opt/lampp/htdo...', false)
#2 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#4 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformation.php(375): Magento\Framework\Composer\ComposerInformation->getComposer()
#5 /opt/lampp/htdocs/Magento/vendor/magento/framework/Composer/ComposerInformatio in /opt/lampp/htdocs/Magento/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 152

**Comment by shiftedreality** [comment]
HI @venkyc07 

It looks like you don't have json_\* functions compiled in your PHP.
Please refer to this advice http://stackoverflow.com/questions/18239405/php-fatal-error-call-to-undefined-function-json-decode

Closed.
