### ISSUE TITLE
Create Product Configurations, References Error in Step 3 and hit button Next

### ISSUE THREAD

**Issue by GuidoHub** [magento/magento2#6657]
I am creating a new configurable product and want to add 1 new configuraions. When I want to go the last step I am getting a script error:

ReferenceError: Unable to process binding "template: function (){return {name:getGridTemplate(),data:{
            grid:gridNew,paging:pagingNew,id:getGridId(),title:$t('New Product Review'),note:$t('Here are the products you\'re about to create.')}} }"
Message: pagingNew is not defined
&nbsp;             grid:gridNew,paging:pagingNew,id:getGridId(),title:$t('New Product Review'),note:$t('Here are the products you\'re about to create.')}} }"()
&nbsp; Message: pagingNew is not defined()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2624:16 template (eval at createBindingsStringEvaluator()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:5023:58 init()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2989:46
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:1249:33 Object.ignore()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2988:48
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:151:17 Object.arrayForEach()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2974:22 applyBindingsToNodeInternal()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2854:37 applyBindingsToNodeAndDescendantsInternal()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:2836:13 applyBindingsToDescendantsInternal()
&nbsp;/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:3052:13 Object.ko.applyBindingsToDescendants()
### Preconditions

1. Magento 2.1.1
2. Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
   Clientversie van database: libmysql - mysqlnd 5.0.12-dev - 20150407
   PHP-uitbreiding: mysqli
   PHP-versie: 7.0.8
3. Servertype: MariaDB, Serverversie: 10.1.13-MariaDB - mariadb.org binary distribution
### Steps to reproduce

1. Create new configurable product
2. Fill in necessary fields
3. Under configuration choose -> create Configurations
4. Choose attribute -> Next
5. Choose value -> Next
6. Everything on skip -> Next
7. Now you get the error as above.
### Expected result

1. Would expect the summary page. When I click on Next again the screen is closed and configuration product is shown but when you save the product it's gone.

**Comment by Andrii-Deineha** [comment]
@GuidoHub  is this issue still actual? Unfortunately, I could not reproduce the issue as you described it

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
