### ISSUE TITLE
Import: Warning!Unlink error when product import file (CSV) has duplicate column

### ISSUE THREAD

**Issue by GuidoHub** [magento/magento2#6658]
When the csv product import file has a duplicate column name you will get error "The file "xxxxxx/catalog_product.csv" cannot be deleted Warning!unlink(xxxxx/catalog_product.csv): Permission denied" when you hit the button Check Data.
### Preconditions

1. Magento 2.1.1
2. Servertype: MariaDB
   Serverversie: 10.1.13-MariaDB - mariadb.org binary distribution
3. Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
   Clientversie van database: libmysql - mysqlnd 5.0.12-dev - 20150407 
   PHP-uitbreiding: mysqli
   PHP-versie: 7.0.8
### Steps to reproduce

1. Create product import file with duplicate column name for ne
2. Go to System -> Import
3. Choose entity Type Products
4. Import behavior Add/Update
5. Errors 10, field separator "," and Multiple value separator ","
6. Select import file
7. Hit button Check Data
### Expected result

1. Validation result: File has duplicate column name
### Actual result

1. "The file "xxxxxx/catalog_product.csv" cannot be deleted Warning!unlink(xxxxx/catalog_product.csv): Permission denied"
   ![permission-denied](https://cloud.githubusercontent.com/assets/22280971/18618733/cf19d31e-7dec-11e6-90c0-a7ee2c935ced.jpg)

**Comment by miakusha** [comment]
Hi @GuidoHub, we cannot reproduce this issue. Its look like wrong permissions on var folder
We need more information about your configuration to reproduce this issue:
- permissions on var folder
- file for import

**Comment by atihomirov** [comment]
Hi @GuidoHub,
check the file - the first line should be the name of the fields.
I got the same error message when I imported a customer address file, without first row (field name)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by vijaymagentone** [comment]
It is problem with the attribute names in .csv file But it is showing error as permission denied

**Comment by DanijelBumbar** [comment]
Put "attribute names" on the top of CSV. 
This error message was misleading.

**Comment by srani95** [comment]
Resource temporarily unavailable during import in magento2
