### ISSUE TITLE
XHTML templates Don't Use Schema URNs

### ISSUE THREAD

**Issue by astorm** [magento/magento2#6661]
### Preconditions

1. Magento 2.1.1 installed via integrator method
### Steps to reproduce

1. Open any XHTML template in the system (`vendor/magento//module-ui/view/base/ui_component/templates/container/default.xhtml, or
   vendor/magento//module-ui/view/base/ui_component/templates/export/button.xhtml, or
   vendor/magento//module-ui/view/base/ui_component/templates/form/collapsible.xhtml, or
   vendor/magento//module-ui/view/base/ui_component/templates/form/default.xhtml, or
   vendor/magento//module-ui/view/base/ui_component/templates/listing/default.xhtml`)
2. Examine the `xsi:noNamespaceSchemaLocation` attribute
### Expected result
1. I see a urn style path (`xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"`)
### Actual result
1. I see an upwards directory traversal path (`../../../../../../Ui/etc/ui_template.xsd`)

**Comment by magento-engcom-team** [comment]
@astorm, thank you for your report.
We've created internal ticket(s) MAGETWO-81748 to track progress on the issue.

**Comment by enriquei4** [comment]
I'm working on this issue for #MM17ES

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @astorm. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1287 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
