### ISSUE TITLE
Impossible to get order by API call (if order placed with vault)

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6662]
### Preconditions

Magento 2.1.1
1. Braintree payment method is configured and enabled Vault
2. Placed order with saved card 
### Steps to reproduce
1. rest call on /rest/V1/orders/{$orderId} endpoint
### Expected result
1. Order information is returned
### Actual result
1. Exception: Internal Error. Details are available in Magento log file. Report ID: webapi-***\* is returned

Details from log file:
main.CRITICAL: exception 'Exception' with message 'Notice: Array to string conversion in /lib/internal/Magento/Framework/Reflection/TypeCaster.php on line 34' in /lib/internal/Magento/Framework/App/ErrorHandler.php:61

**Comment by gastondisacco** [comment]
Same happening when placing with payflowpro method (returns expected placing with checkmo).

**Comment by gabriel-sf** [comment]
Guys, is there any update on this item?

**Comment by olysenko** [comment]
Hi, the fix will be delivered with version 2.1.3. Actually this issue duplicates [6215](https://github.com/magento/magento2/issues/6215). Closed as duplicated
