### ISSUE TITLE
How to add text swatch via REST API?

### ISSUE THREAD

**Issue by cherreman** [magento/magento2#6664]
When a text swatch attribute is created via the management tool, the following happens:
- record in eav_attribute created with backend_type = int, frontend_input = select, source_model = Magento\Eav\Model\Entity\Attribute\Source\Table
- record in catalog_eav_attribute created with additional_data = a:3:{s:17:"swatch_input_type";s:4:"text";s:28:"update_product_preview_image";s:1:"0";s:28:"use_product_image_for_swatch";i:0;}

It is possible to create the first record via the REST API (POST 'products/attributes'), but how can I create the second record? Passing 'additional_data' in the payload results in an error because there is not setter for AdditionalData.

Any ideas?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by syamilijayesh** [comment]
Did you find any solution?

**Comment by alexsergin** [comment]
Have the same trouble. Did you find a solution?
