### ISSUE TITLE
How to define scope in di.xml & Router.php

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#6669]
Please refer to http://magento.stackexchange.com/questions/136627/magento-2-how-to-define-scope-in-di-xml-router-php

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
