### ISSUE TITLE
Issue in the module catalog XML layout file

### ISSUE THREAD

**Issue by Memes11** [magento/magento2#6670]
With Magento 2.1.1

 main.CRITICAL: Broken reference: the 'product.info.price' tries to reorder itself towards 'product.info.review', but their parents are different: 'product.info.main' and 'product.info.price' respectively. [] []

Issue with line 33 of the file vendor/magento/module_catalog/view/frontend/layout/catalog_product_view.xml

it redirects the container product.info.price to its own child. suggest to edit to : after="-"

**Comment by veloraven** [comment]
@Memes11 , thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
