### ISSUE TITLE
The value of custom category image attribute is not removed properly

### ISSUE THREAD

**Issue by Sharmilasrini95** [magento/magento2#6672]
### Steps to reproduce

1.Add a custom image attribute to the category entity: $catalogSetup->addAttribute(\Magento\Catalog\Model\Category::ENTITY, 'menu_image', array( 'label' => 'Menu Image', 'note' => 'Image that is shown for the menu item of current category', 'input' => 'image', 'backend' => \Magento\Catalog\Model\Category\Attribute\Backend\Image::class, 'required' => false, 'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_STORE, 'group' => 'Menu', 'sort_order' => 30, )); 

2.Add/upload an image to a category via admin.

3.Remove the image via admin. (Using the "Delete image" check box.)
### Expected result

The image and the attribute value is removed.
### Actual result

The image is removed, but the attribute value is not.
<img width="733" alt="777bb37a-3314-11e6-96e6-61fd5fe2094b" src="https://cloud.githubusercontent.com/assets/20103861/18660148/922a70b2-7f2c-11e6-9b13-86be0f70ec08.png">

**Comment by Sharmilasrini95** [comment]
Hello ! And also we are using the version Magento2.0.7

**Comment by Stas94** [comment]
@Sharmilasrini95 Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
