### ISSUE TITLE
Selecting products based on category does not work when using a "second" root category

### ISSUE THREAD

**Issue by timbaker1991** [magento/magento2#6674]
### Preconditions
1. Magento CE 2.1.1 without sample data
2. PHP version 7.0.7
### Steps to reproduce
1. Added a new category (2016-05-27) to the "Dates" root category.
   ![image](https://cloud.githubusercontent.com/assets/3218611/18662049/7b82d0f0-7f10-11e6-997a-61cb8fbcd13b.png)
2. In view:

```
  // @var $product \Magento\Catalog\Model\Product\
        $products = $block->getProductsByCatId(22);
        foreach($products as $product){
            echo "<h2>" . $product->getName() . "</h2>";
        }
```

Block:

```
 /*
     * Get products by date info
    */
    public function getProductsByCatId(string $categoryId)
    {
        $category = $this->_categoryFactory->create()->load($categoryId);
        $collection = $this->_productCollectionFactory->create();
        $collection->addAttributeToSelect('*');
        $collection->addCategoryFilter($category);
        $collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
        $collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
        return $collection;
    }
```
1. Loading that view doesn't return any product names.
### Expected result
1. This should return all products of that category.
### Actual result
1. No products are returned and no error is given. I have stepped through it with xdebug and can not see any reason for this to occur. 
2. If you drag the category "2016-05-27" to the original root category "Subscriptions", then products which belong to that category are correctly returned (and if you drag it back to the Dates category it reverts back). 
3. I have studied the different root categories over and over and can not see any difference in them, and why it could stop it.

**Comment by magento-engcom-team** [comment]
@timbaker1991, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
