### ISSUE TITLE
Configurable-type-handler.js disable Stock Availability

### ISSUE THREAD

**Issue by mvistas** [magento/magento2#6675]
I am using Magento 2.0.7

I have Configurable products with "child" products. 
On Advance inventory, the "child" products have "Manage Stock" set to yes.
If, the qty of one "child" product change to 0, the "child" product becames Out of Stock.

When I change the qty of this "out of stock" product to 10000 (example), the product stays as Out of Stock, and the stock availability dropwon is disabled.
I run indexer cataloginventory_stock, and clean cache, and the product continue out-of-stock, and dropdown disabled.

I was checking the code, and Configurable-type-handler.js, check is product is configurable or not. If not, it disable the stock availability dropdown, and backend user can not change the value.

How can the product became "in stock" again, If this dropdown is disabled?

**Comment by veloraven** [comment]
@mvistas thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ghost** [comment]
I am facing same issues.

In magento 2.0.7.
Admin simple product Stock Availability is disabled for edit you can not change after one time add. 

and showing like 

![screenshot 104](https://cloud.githubusercontent.com/assets/6220561/19465125/3346f2ce-951f-11e6-9d9b-37b9b22f18b6.png)

Please help me as soon as possible .

By admin one file configurable-type-handler.js created and on that have on code like 

```

if (productType.type.current === 'configurable') {
                suggestContainer.addClass('disabled').prop('disabled', true);
                $('#inventory_qty').prop('disabled', true);
                $('#inventory_stock_availability').removeProp('disabled');
                this._setElementDisabled($('#qty'), true, true);
                this._setElementDisabled($('#quantity_and_stock_status'), false, false);
            } else {
                suggestContainer.removeClass('disabled').removeProp('disabled');
                $('#inventory_qty').removeProp('disabled');
                $('#inventory_stock_availability').prop('disabled', true);
                this._setElementDisabled($('#quantity_and_stock_status'), true, false);
                this._setElementDisabled($('#qty'), false, true);
            }

```
