### ISSUE TITLE
REST API: Customer/token (login) response with not valid JSON

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#6676]
Magento 2.1.1

REST API

**REQUEST**
POST /V1/integration/customer/token
{
  "username": "EMAIL",
  "password": "PASSWORD"
}

**RESPONSE** - 200 OK, 
HEADER: Content-Type **application/json; charset=utf-8**

but response body is not valid JSON but just "token". 

This is serious bug.

**Comment by veloraven** [comment]
@RUjmiak thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by maghamed** [comment]
There are 2 RFCs which dictate the validity of JSON format.
[RFC7159](http://www.rfc-editor.org/rfc/rfc7159.txt) -  The JavaScript Object Notation (JSON) Data Interchange Format
This document states that:

```
  JSON-text = ws value ws
```

So,  "response" is a valid JSON object according to this RFC

There is also 

[RFC4627](https://tools.ietf.org/html/rfc4627) - The application/json Media Type for JavaScript Object Notation (JSON)
This document states that:

```
   A JSON text is a serialized object or array.

      JSON-text = object / array
```

So, "response" is NOT a valid JSON object according to this RFC]

So, for now there is a problem that using Web API from JavaScript (say, using UI components) we can't specify media type "application/json" for responses which don't represent object/array.

**Comment by VladaPetrovic** [comment]
Hi there, I see that this is still an open issue. Is there any plan for a fix in near future?

**Comment by magento-engcom-team** [comment]
@RUjmiak, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@maghamed thank you for investigation
