### ISSUE TITLE
2.1 Saving a special price sets the product as new

### ISSUE THREAD

**Issue by doug48** [magento/magento2#6678]
I noticed this issue today when setting a special price, it will also save the 'set as new' flag. 

what is strange about this is when you try to save this 'set as new' flag on its own if will not save.
Also noticed the news_from_date and news_to_date are missing in the product admin

Steps to reproduce:
1. Go to a product that is not new and has not special price
2. Take a note of 'set as new' flag it should be un-ticked
3. Set a special price (advanced pricing)
4. save the product

after save you will notice the 'set as new' is now set (ticked). 

The expect result would be that is 'set as new' would remain un-ticked.

**Comment by miakusha** [comment]
I’m closing this issue because it is a duplicate #4387
We have internal ticket MAGETWO-52577
