### ISSUE TITLE
Magento2 js error on Product Detail Page

### ISSUE THREAD

**Issue by omelandr** [magento/magento2#6679]
Magento2 js error on Product Detail Page

I'm using luma theme. Nothing haven't been changed I only installed latest version from Magento connect. Added test category and product. This problem is only on product detail page. Other pages works fine 
On Product Page i have js error:
`knockout.js:3012 Uncaught TypeError: Unable to process binding "attr: function (){return {'data-config-scope':$data.scopeLabel} }"
Message: Cannot read property 'scopeLabel' of undefined`
![147430589901_kiss_92kb](https://cloud.githubusercontent.com/assets/5512114/18668926/0e709c78-7f41-11e6-9209-5c4c6502743b.jpg)
I tried php bin/magento setup:static-content:deploy and clear cache etc but nothing changed.
Is it bug magento?
How can i fix it?

**Comment by melnikovi** [comment]
@omelandr thank you for reporting the issue. Could you, please, clear browser cache and see if you can still reproduce the issue?

**Comment by omelandr** [comment]
Yes, i clear browser cache but nothing changed. It problem is in all browsers

**Comment by mrkhoa99** [comment]
@omelandr this issue may not be a Magento bug: http://magento.stackexchange.com/a/137426/33057. Seem that it's the default WYSIWYG html editor.
