### ISSUE TITLE
Double config.xml value discount_tax

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#6680]
We use a custom module with it's own config.xml to change the default config settings of Magento, this way uppon installation we will have the settings they way it will work for most customers. The problem is that if I try to set a value for tax/calculation/discount_tax in my config.xml the config section of Magento throws an error:

More than one node matching the query: /config/default/tax/calculation/discount_tax in /home/account/domain.nl/vendor/magento/framework/Config/Dom.php:276

It has something to do with a double value in the core of Magento, because if I remove the double value in vendor/magento/module-tax/etc/config.xml the error is gone and my settings are working.

It seems to me like this error should either always occur on xml validation or not occur at all, but most of all the double value should be removed.
### Preconditions

We are using Magento 2.1.1 on a PHP7 server without any custom modules except the config module.
### Steps to reproduce

Create a module with a config.xml and add the xml to change the discount_tax setting.
### Expected result

Tax setting should be the value you are setting in your config.xml
### Actual result

The entire Magento installation throws an error in initalization, so on both front-end and back-end.

**Comment by reviskar** [comment]
Same issue here with Magento 2.1.7. Still no fix to this?

**Comment by orlangur** [comment]
@bartlubbersen thanks for bug report! Closing it in favor of #11000 which contains more detailed steps and PR with bugfix.
