### ISSUE TITLE
Menu scrolling in Admin

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#6682]
### Preconditions
1. CE & EE 2.1.1
### Steps to reproduce

1. Have more items in main admin menu or make your window lower
2. Go to import 
3. Scroll down to page 
4. Do the import 
5. There will be some ajax processing and you will get some result
### Expected result
1. You should be able to scroll to the top of page and see magento logo which is top left
### Actual result

1. http://prntscr.com/ck9upo  - You can't scroll to the top of page and see magento logo. You have to refresh page to be able click on menu items higher. Scrolling is frozen after ajax with import result.

**Comment by oshmyheliuk** [comment]
Hi @magexo 
I can't reproduce this issue on fresh installed magento 2.1.1.
Maybe a problem in custom modules.
Please, open console tab in developer tools of your browser and check if there are any errors if so paste that information here.

**Comment by krejcif** [comment]
Tested on clean 2.1.1 Enterprise. There are no errors in console.

![screenshot_107](https://cloud.githubusercontent.com/assets/11734352/18791122/c0eacbcc-81b1-11e6-9566-8535ac767bb0.png)

I'm using chrome.

**Comment by anton-huz** [comment]
The issue has no relations to Import/Export or any specific module. It can be easily reproduced on any Grid: just change "Custom per page" number to `1`.

The fixing and delivery will be done under the MAGETWO-59532 internal issue.

**Comment by ArthurTransoftgroup** [comment]
Internal ticket MAGETWO-69957 was created;

**Comment by ShirishRam** [comment]
@guz-anton, @oshmyheliuk  Is there any workaround for this? (apart from limiting the number of menu items) This issue is also observed when we are on Dashboard page. Changing "Custom per page" number to 1 doesn't work.
Magento version: 2.1.8

**Comment by magento-engcom-team** [comment]
@magexo, thank you for your report.
We've created internal ticket(s) MAGETWO-69957 to track progress on the issue.

**Comment by jayankaghosh** [comment]
I am working on this

**Comment by jigar48** [comment]
Any update on this ?

I have same issue also when scrolling down then top menu not showing.
http://prntscr.com/jwqszr

**Comment by jigar48** [comment]
any update on this ?

**Comment by raibelbotta** [comment]
Hi all.
In Magento 2.1.10, I solved the problem by overwriting the theme file `vendor/magento/theme-adminhtml-backend/web/js/theme.js`. I inserted the following line after line 98:

menu.css('top', 'auto');

Good luck

![image](https://user-images.githubusercontent.com/2282889/52320676-b503af80-299e-11e9-862e-731c0e2ff2d6.png)

**Comment by jorgehs91** [comment]
Do we have any other option to fix this?
I'm running 2.2.6 and this still occuring.

I think @raibelbotta 's solution may work, but is a little painful override the admin theme for me.

Thanks

**Comment by Govindarajsdkcap** [comment]
I am working on this at #dmdcindia1

**Comment by torhoehn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](https://i-6682-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-6682-2-3-develop.instances.magento-community.engineering/admin](https://i-6682-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
**Merged in commit**: 29cbd2fd3d8a92c81b2b12182f127dfac7a1ea3c

**Comment by robocrax** [comment]
Same issue happening in 2.3.4

Menu has a negative top value instead of 0 when scrolled to the top of the page.
```
 <div class="menu-wrapper" style="top: -136px;">
```

This happens on every instance of every update, it's not a hit or miss for me. It always is `-136px`
