### ISSUE TITLE
Checkout with Braintree authorize and capture not change status to Complete

### ISSUE THREAD

**Issue by drestine** [magento/magento2#6684]
Hi,
I'm already set Authorize and Capture for Braintree payment but when I add Downloadable product and checkout with Braintree, The order not change status to Complete.
Already test on CE 2.1.1.

Thanks,
Drestine

**Comment by veloraven** [comment]
@drestine thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by drestine** [comment]
Hi @veloraven,

**Preconditions**
1. Install Magento CE 2.1
2. Config Braintree payment method with sandbox account (https://sandbox.braintreegateway.com/).
3. Have an downloadable product to test.

**Steps to reproduce**
1. Add an Downloadable product to cart.
2. Go to cart page and click Checkout with logged in.
3. Choose Braintree Credit card with card Visa test (4111111111111111) and click "Place Order" with success order.

**Actual and Expected result**
The Order status should say "Complete" not "Processing"

**Additional information**
Have already set Braintree with "Authorize and Capture" on Backend.

**Comment by YevSent** [comment]
Hi, @drestine, thanks for reporting, this is a known issue and already fixed (internal ticket MAGETWO-57512).
The fix will be available in the Magento 2.1.3 version.

**Comment by drestine** [comment]
Hi @joni-jones, Can you give me a link or package to fix that problem?
Thanks, Drestine

**Comment by YevSent** [comment]
You can check diff changes from this commit https://github.com/magento/magento2/commit/c9f5ca50299a30ba1b34aa28681abf24b9af6ae8.

**Comment by lano-vargas** [comment]
@magento-engcom-team  2.2.2 Still an issue.  
I can see in sandbox Braintree the status of and order changing from 'submitted_for_settlement' then  'settling'  and after 'settled'   but the status for the order in Magento still says 'Processing'.

**Comment by YevSent** [comment]
@drestine, an order will have `Complete` status when `Shipment` and `Invoice` are created.

**Comment by lano-vargas** [comment]
@joni-jones  I was wondering about that thanks for your reply that's helpful.
