### ISSUE TITLE
pub/static url contains deployed version.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#6688]
I have upgraded magento2 instance with latest git code today.

after upgrade and static files deployment.

static files url contains deployed version because of this 404 error comes.

[http://domain]/pub/static/version1474443317/frontend/Magento/luma/en_US/mage/calendar.css

static files exist if we remove version1474443317 from url and check but site all url contains this version1474443317.

Please check this bug.

**Comment by ihor-sviziev** [comment]
@ankursachdeva11 looks like your web server configured incorrectly.
If you're using apache - make sure that your server configured correctly and  reads .htaccess file. Also make sure that you have .htaccess file in pub/static/ directory. Because it contains needed rewrite: https://github.com/magento/magento2/blob/develop/pub/static/.htaccess#L16

If you're using nginx - make sure that it contains following lines:
https://github.com/magento/magento2/blob/develop/nginx.conf.sample#L123

**Comment by veloraven** [comment]
@ankursachdeva11 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also specify Magento versions which you updated from and to.

**Comment by ankursachdeva11** [comment]
@veloraven, I have updated from git repository to "Magento ver. 2.2.0-dev".

and i am using "FPM/FastCGI" Server

**Comment by ankursachdeva11** [comment]
@veloraven ,
1. Magento ver. 2.2.0-dev without sample data is installed.

Steps to reproduce
1. After upgrade i have used command setup:upgrade.
2. Then i have deploy the static content.
3. After doing all this when i tried to open website then all static links include version number in that.
[http://domain]/pub/static/version1474443317/frontend/Magento/luma/en_US/mage/calendar.css

Expected result:
Static Link should be like this:
[http://domain]/pub/static/frontend/Magento/luma/en_US/mage/calendar.css
Actual result:
Now Static link is like this:
[http://domain]/pub/static/version1474443317/frontend/Magento/luma/en_US/mage/calendar.css

Thanks!

**Comment by ihor-sviziev** [comment]
@ankursachdeva11 this is expected behavior. Why don't you want to have static version in URL?
Such URLs will be correctly handled by magento. If you have any issues - check your server configuration (see my prev reply).

This feature needed to prevent any issues for customers that already have cached files in browser from old static version.

**Comment by sevos1984** [comment]
@ankursachdeva11 This is not a bug, this option is set in config Stores>Configuration>Advanced>Developer>Sign Static Files (dev_static_sign).

**Comment by ankursachdeva11** [comment]
Thanks @sevos1984 
I was not able to find this setting because after fresh install UI not working because of version number present in static urls. So, i tried to set this path in database and it works.

**Comment by kienmba** [comment]
@sevos1984 Thank you so much!

**Comment by davidmpaz** [comment]
Thanks @sevos1984 for hinting the proper location to look at.

For us the solution was to point web root dir of server to "pub" dir in magento

**Comment by dimasch** [comment]
Thanks, Guys,

Quick solution:
```
insert core_config_data (config_id, scope, scope_id, path, value) values (null, 'default', 0, 'dev/static/sign', 0); 
```

**Comment by tusharbagal** [comment]
Check below link for same issue:
http://magento.stackexchange.com/questions/150418/static-content-is-not-loading-after-upgrade-to-2-1-3

**Comment by chamath** [comment]
Thanks @ihor-sviziev . It works for me. I have accidentally deleted .htaccess file from static folder

**Comment by nafisakanwal** [comment]
I am using Fedora 25 , having
Apache/2.4.25 (Fedora)
PHP Version 7.0.18
MySql 5.7.18

I have just installed magneto 2.1.6 , after successfull setup run, its getting css and js files not found issue and they are loading from pub/static//version1494143163/frontend/Magento/luma/en_US/css/styles-m.css
version1494143163 is not even existed.
Beside this the admin url is also not accessible .

Can anyone can help me

**Comment by kienmba** [comment]
Hi @nafisakanwal !
You can follow these instructions:
`Stores>Configuration>Advanced>Developer>Sign Static Files(Yes->No)`
Or Access the database and execute the command:
`insert core_config_data (config_id, scope, scope_id, path, value) values (null, 'default', 0, 'dev/static/sign', 0);`
Then remove the cache and reload the page.

**Comment by nafisakanwal** [comment]
Hi @kientran175 
Thankyou so much for replying . i already executed this sql command but no success .
Is there have any other solution to resolve this ?

**Comment by kienmba** [comment]
Hi @nafisakanwal !
Error in running sql command? Or sql command is executed but version1494143163 still exists?
Can you add me on Skype, let me support you!
Skype: trantrungkien175
Regards,
Kiên Trần.

**Comment by ihor-sviziev** [comment]
Please flush cache after disabling version

**Comment by nafisakanwal** [comment]
Oh thankyou guyz @ihor-sviziev @kientran175 
css and js files not loading issue just resolved , but still i am unable to access admin 
it says 404 Not found page

**Comment by kienmba** [comment]
Hi @nafisakanwal !
Check the access path to admin, to make sure the path is correct: 'frontName' in \app\etc\env.php

**Comment by nafisakanwal** [comment]
@kientran175 
i verified i am accessing the correct admin path, but it is saying 404 page Not found

**Comment by nafisakanwal** [comment]
@kientran175 
any other solution to resolve this ?

**Comment by kienmba** [comment]
Hi @nafisakanwal !
Please try Below solutions:
1) Delete var/cache folder
2) Go to database SELECT * FROM core_config_data WHERE path = 'web/seo/use_rewrites' and make it 0
3) Then enter url in your browser magento_base_url/index.php/your_admin_url
Try and let me know if you face any issue.

**Comment by nafisakanwal** [comment]
@kientran175 
tried all of above three steps, but no success

**Comment by kienmba** [comment]
Hi @nafisakanwal !
Try this tutorial to see if it fixes the problem?
https://magento.stackexchange.com/questions/123915/404-error-magento2-admin-page-not-working

**Comment by nafisakanwal** [comment]
Hi @kientran175 
It resolved my issue. Thankyou soo much 👍

**Comment by tgamanov** [comment]
The fix with adding 
insert core_config_data (config_id, scope, scope_id, path, value) values (null, 'default', 0, 'dev/static/sign', 0); 
to DB helps.
Thanks.

**Comment by mengbo123456** [comment]
**# now i know why can't linking style ,but i don't know why this?**
because install path no version1499055289 folder ,and i add it  style work 
![qq 20170703141604](https://user-images.githubusercontent.com/29748690/27780458-9e8f6dfc-5ffb-11e7-9cf7-eaeb3d60d6c7.png)
![qq 20170703141841](https://user-images.githubusercontent.com/29748690/27780461-9f0b7dd4-5ffb-11e7-9a49-e3596576bcd9.png)
![qq 20170703142510](https://user-images.githubusercontent.com/29748690/27780459-9e9a501e-5ffb-11e7-96d0-4aa4b1650e53.png)
but i don't know why it can't add  version1499055289 folder itself in  During the installation process

**Comment by korostii** [comment]
Hi @mengbo123456, please stop flooding unrelated issues.

version1499055289 isn't a real folder, these requests are supposed to get rewritten by the webserver.
In case you're using nginx: There is a `nginx.conf.sample` provided With Magento2. Please update your config accordingly.
Alternatively, you could try using the following SQL query as a workaround: `insert core_config_data (config_id, scope, scope_id, path, value) values (null, 'default', 0, 'dev/static/sign', 0);`

If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE running on a supported platform aren't likely to get resolved in here.

**Comment by mengbo123456** [comment]
@komsitii,my webserver  windows iis7.5 +php7+mysql5.6 how to setting rewritten ？
![image](https://user-images.githubusercontent.com/29748690/27812146-31b7c5d6-609f-11e7-8732-c7224b9a4b3f.png)
about  version1499055289 question

**Comment by mengbo123456** [comment]
iis7 +mysql5.6 +php7.1
![image](https://user-images.githubusercontent.com/29748690/27812777-f0acf52a-60a3-11e7-91e0-bebfd24940c7.png)
![image](https://user-images.githubusercontent.com/29748690/27812790-01e292a0-60a4-11e7-832c-1e8a2a7dee66.png)
install successfull  but no index.php web

**Comment by korostii** [comment]
@mengbo123456 
Magento2 is not guaranteed to run on IIS flawlessly, you'd have to figure it out on your own.
Please consider using one of the [supported platforms](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) instead.

**Comment by franciskim** [comment]
I believe the Nginx rewrite isn't correct in the Magento 2.1.7 Nginx sample config file (and possibly versions before) for the static files. I've had to make an edit:

```
        location /pub/ {

                location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {

                        deny all;
                }
                alias $MAGE_ROOT/pub/;
                add_header X-Frame-Options "SAMEORIGIN";

                location ~ ^/pub/static/version {

                        rewrite ^/pub/static/(version\d*/)?(.*)$ /pub/static/$2 last;
                }
        }
```

**Comment by saschabratton** [comment]
@franciskim: I've had to make the same edit on an install today of version 2.1.8.

It seems the sample file is setup as though static content were residing at `/static/versionXYZ/...` but the frontend file are all written to client as `/pub/static/versionXYZ/...`.

**Comment by ecalimlim7** [comment]
Hi! I encountered a problem with my Magento site...I'm not a developer of Magento. I just edited the "REQUEST PATH" on my /MARKETING/URL RE-WRITE, then i also changed the setup of "SIGN STATIC FILES" to "yes" value. I flush the cache storage, now my website is broken. Please see live site http://www.alohapearls.net/. Maybe you can help me figure out the problem?

Thanks

**Comment by charultyagi18** [comment]
Hi, I had this issue and now resolved steps i took are  :
1. bin/magento setup:upgrade
2. bin/magento setup:di:compile
3. bin/magento setup:static-content:deploy -f
4. sudo chmod -R 777 var

Please try these steps i hope it will be resolved.
Thanks.

**Comment by Tarek-Adra** [comment]
this cmd solved my prob : 
php bin/magento setup:static-content:deploy -f

**Comment by kaydee92** [comment]
@Tarek-Adra When i tried your command "php bin/magento setup:static-content:deploy -f" then i got below error
[RuntimeException]
The "-f" option does not exist.

so can you please check

**Comment by m0ver** [comment]
I'm wondering what's the root cause?

**Comment by LiamKarlMitchell** [comment]
Having this issue on Magento 2.3 via nginx.

Set up following guide here
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/nginx.html

**Comment by ThakurPradeep** [comment]
a)Firstly keep the pub/static .htaceess file backup don't remove this file
b) Remove the cache  pub/static and  generated
php bin/magento rm -rf pub/static/frontend/ var/cache var/composer_home var/page_cache var/view_preprocessed generation
c) Then run compile command
 php bin/magento setup:di:compile
d) run deploy command 
php bin/magento setup:static-content:deploy -f

I hope pub/static/version1474443317 issue will be resolve

**Comment by camslice** [comment]
@charultyagi18 & @ThakurPradeep 's solution worked for me. Magento 2.3.1, nginx 1.17 (alpine)

@Tarek-Adra depending on your OS environment, you might not need the `php` at the start of that command, try just running it as `bin/magento setup:static-content:deploy -f`
