### ISSUE TITLE
[EE] Presence of a "Suggestions Data Provider" should be optional for additional search engines.

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#6690]
Magento is looking for an entry in \Magento\AdvancedSearch\Model\SuggestedQueries for each search engine.
It fails and prevent to obtain catalogsearch results if nothing is found.
### Preconditions

1. Using a custom Search Engine ( https://github.com/Smile-SA/elasticsuite )
2. Use Magento 2.1.1 EE with the module-advanced-search enabled.
### Steps to reproduce

1. Process a search in front office.
### Expected result

1. Search results should appear
### Actual result

1. Notice: Undefined index: elasticsuite in /var/www/magento2ee/vendor/magento/module-advanced-search/Model/SuggestedQueries.php on line 76

The problem here is located in `Magento\AdvancedSearch\Model\SuggestedQueries` on line 76 : 

`$this->dataProvider = $this->objectManager->create($this->data[$currentEngine]);`

`$this->data[$currentEngine]` is undefined index because no data provider is set for our module.

=> Magento should rather fallback to the default (I call it dummy because it does nothing) data provider in this case : `Magento\AdvancedSearch\Model\DataProvider\Suggestions`.

=> Magento should NOT try to instantiate Suggestions Data Provider if the Search Suggestions are not activated in Back-Office. Instead this is delegated to each Data Provider : 
- the Elasticsearch Data Provider `Magento\Elasticsearch\Model\DataProvider\Suggestions` has a `isSuggestionsAllowed()` method which should be on an upper level.
- so does the Solr Data Provider `Magento\Solr\Model\DataProvider\Suggestions`

Best regards,

Romain

**Comment by veloraven** [comment]
@romainruaud thank you for your feedback.
If you experience any problems with Enterprise Edition please address the issue to Magento Support.
