### ISSUE TITLE
Issue with Performance toolkit and configurable product

### ISSUE THREAD

**Issue by jlimodin** [magento/magento2#6691]
When you run the performance toolkit more than one time, I have an error: 
Error happens here: 
if (props.get(&quot;configurable_products_list&quot;) == null) {
    return stopTestOnError(&quot;Cannot find configurable products. Test stopped.&quot;);
}

And I have this error in the magento log file. 

[2016-09-20 13:04:05] main.CRITICAL: Configurable product "Configurable Product 23257" does not have sub-products [] []
[2016-09-21 08:35:39] main.CRITICAL: Configurable product "Configurable Product 23257" does not have sub-products [] []
[2016-09-21 08:51:01] main.CRITICAL: Configurable product "Configurable Product 66" does not have sub-products [] []
[2016-09-21 08:57:26] main.CRITICAL: Configurable product "Configurable Product 23257" does not have sub-products [] []
[2016-09-21 09:01:46] main.CRITICAL: Configurable product "Configurable Product 66" does not have sub-products [] []
Cause it's configurable product option 1 is out of stock. 
### Preconditions

1.  I use Magento 2.1.1 in Linux, PHP 7 and MariaDB 10.0
2. 
### Steps to reproduce

1. Easy run the performance toolkit more than one with a high number of users. 
### Expected result

1. Succeed to run the test several time by sorting the out of stock configurable products and not taken its into account. 
### Actual result

1. [Screenshot, logs]

**Comment by choukalos** [comment]
Hi @jlimodin if you just had a way to reset stock qty quickly would that be sufficient for your uses?  Seems like you're getting those results because the products are going out of stock.

**Comment by jlimodin** [comment]
Hello choukalos, yes it will be great to reset stock qty between each performance runs. Does have it an impact on indexing or caches ? 
Thanks Julien

**Comment by okobchenko** [comment]
Hi, @jlimodin. It is known issue. Unfortunately performance fixture generator does not support re-run or execution on non-empty database as use same entities keys on each generation cycle. Our team plan to address this issue hopefully during nearest month in scope of  task MAGETWO-59614 (if you notice task number in commits list, that means it is already fixed).

**Comment by choukalos** [comment]
59614; is currently in development.

**Comment by magento-engcom-team** [comment]
@jlimodin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
