### ISSUE TITLE
Target Rule - Cross-sell rule

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#6692]
When creating a new target rule (EE) with Products to display having Attribute Product Size is matched product size, causes an error when loading the cart
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'table.entity_id' in 'where clause', query was: SELECT `e`.`entity_id` FROM `catalog_product_flat_1` AS `e`

This is caused because in the newer version of EE, the SQL columns in the entity tables (entity_int, entity_varchar) changed the column name form entity_id to row_id

The following class needs updating
Magento\TargetRule\Model\Actions\Condition\Product\Attributes
Method:getConditionForCollection()

$table = $attribute->getBackendTable();
            $select = $object->select()
                ->from(['table' => $table], 'COUNT(*)')
                ->where('table.entity_id = e.entity_id')
                ->where('table.attribute_id=?', $attribute->getId())
                ->where('table.store_id=?', 0);

table.entity_id needs updating to table.row_id

Please let me know when this would be fixed so we can pull the latest patch version onto our website.

**Comment by veloraven** [comment]
@teuma86 thank you for your report.
If you experience any problems with Enterprise Edition please address the issue to Magento Support.

**Comment by dev-Dhaval** [comment]
@teuma86 , did you get any solution ?
