### ISSUE TITLE
"Group Prices" are no longer displayed in Advanced Pricing configuration

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#6695]
I've just found that there is no "Group Prices" configuration. I've contacted Olena Tkacheva via Skype and she told me that Group Prices should be at product prices configuration. I mean she confirmed that this functionality was not removed from Magento 2.
### Preconditions
1. Tested on Magento 2.0.7, 2.1.0, 2.1.1, both CE and EE, with and without sample data.
### Steps to reproduce
1. Go to Catalog > Products
2. Click on "Add Product" button
3. Click on "Advanced Pricing"
### Expected result
1. Group Prices are available
### Actual result
1. Group Prices are absent (https://gyazo.com/ddccd326f17cc61b2196ec95e2d8d3dd).  I've also checked product attributes and attribute sets. Maybe Group Prices were actually removed because Tier Prices can fulfill that functionality?

**Comment by mbrinton01** [comment]
@stasleo if you would like to set a custom price by Customer Group, you can do this in your screenshot under the tier price section.  Just click on `Add` and complete the fields.

**Comment by mbrinton01** [comment]
One more note: you can set the tier price with `quantity=1` if you only want to change the price for a Customer Group and do not want to vary it by quantity.
