### ISSUE TITLE
Product Auto-Generation

### ISSUE THREAD

**Issue by Arkyden** [magento/magento2#6696]
### Preconditions
1.  Magento 2.1.1
### Steps to reproduce
1. Change product name which in 2.0.x would auto-generate the Meta Information
### Expected result
1. Meta Information should auto-generate
### Actual result
1. Meta Information left empty

Also, I was wondering if there is a way of re-generating meta information in bulk

**Comment by paales** [comment]
I believe this is also only partially implemented on product save from the backend, the importer isn't supported.

**Comment by antboiko** [comment]
Hi @Arkyden , I can't reproduce this issue on 2.1.1. Meta information is auto-generated using Product Name when creating a Product from the Admin. Please note, the editing of product name after the save doesn't affect the Meta description.

> Also, I was wondering if there is a way of re-generating meta information in bulk

I would suggest using Export/Import for this.

Best,
Anton.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
