### ISSUE TITLE
2.0.4.: different languages trigger different bugs on the minicart

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#6697]
### Preconditions

1. Magento2 V.0.4
2. we are using the splendid internet de_DE-CSV
### Steps to reproduce
1.  Install Magento
2. change language
3.  put something in your cart
### Expected result

1. the minicart gets shown correctly no matter what language is selected in the backend
### Actual result

Working on `en_US`:

[![Cart on en_US](http://i.stack.imgur.com/7DvIz.png)](http://i.stack.imgur.com/7DvIz.png)
[![Console on en_US](http://i.stack.imgur.com/sALeI.png)](http://i.stack.imgur.com/sALeI.png)

Working on `de_DE`:

[![Minicart on de_DE](http://i.stack.imgur.com/BcWq5.png)](http://i.stack.imgur.com/BcWq5.png)
[![Console on de_DE](http://i.stack.imgur.com/PSbDA.png)](http://i.stack.imgur.com/PSbDA.png)

We are currently using Magento 2.0.4 and upgrading on this Env is not an option due to the bugs on higher Magento2-Versions. 

The question now is: how can we get rid of those two errors? Our desired language is `de_DE`, so getting it working on `de_DE` would already be a great success.

**Comment by quienti** [comment]
Fixed in Magento 2.1.0
https://github.com/magento/magento2/issues/3102

**Comment by SerhiyShkolyarenko** [comment]
@grasdaggel please clarify precondition "we are using the splendid internet de_DE-CSV"

**Comment by grasdaggel** [comment]
Since Mage2 doesn't provide de_DE you need to utilize something else. We use this: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/

**Comment by SerhiyShkolyarenko** [comment]
Tried both 2.1.2 and 2.0.10 and didn't reproduce errors in console.
@grasdaggel is it reproducible for you after uprading to 2.0.10 and cleaning caches, cookies and static files?

**Comment by grasdaggel** [comment]
Since upgrading triggers a unfunctional shop I cannot reproduce this bug on higher versions due to the ton of different bugs. 

If you can't reproduce it on a 2.1.2 env I'd consider it fixed. Other thoughts about this?

**Comment by SerhiyShkolyarenko** [comment]
@grasdaggel lets' leave this issue in "needs update" state for 14 days. If nobody reproduce it for this period, we'll close it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
