### ISSUE TITLE
Magento 2.1 Associated products being removed from configurable on save

### ISSUE THREAD

**Issue by szerambo** [magento/magento2#6698]
I have import 70,000+ products from Magento 1.9 to 2.1 and everything seemed to be fine until I went into a configurable product, made a minor adjustment and then saved it. At this point, all of the associated products were no longer there and the option to add them back manually was also gone.

**Comment by heldchen** [comment]
known bug, see #6424

**Comment by veloraven** [comment]
@szerambo thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
