### ISSUE TITLE
ImportExport Custom option dropdown with price 0 causing indexer issues

### ISSUE THREAD

**Issue by paales** [magento/magento2#6701]
### Preconditions

1. 2.1.0
### Steps to reproduce

1. Create an import with a dropdown option that is required.
2. Add an option with the price 0
### Expected result

1. The catalog price shouldn't increase.
### Actual result

1. Catalog price increases, because it selects the lowest price from `catalog_product_option_type_price` but the value isn't inserted.

This line should be `isset()` instead of `!empty()`:
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1618

**Comment by asemenenko** [comment]
Needs to be fixed also in #4808  and #4092 at the same time.

**Comment by IlnitskiyArtem** [comment]
@paales, We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue.

**Comment by paales** [comment]
@IlnitskiyArtem  Take a look at the code: https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1617

On this line it checks if the value isn't empty, but the string `'0'` IS empty. It should just check if that value exists instead requiring a truthy value.

**Comment by IlnitskiyArtem** [comment]
@paales, Thanks for the feedback.
We've created internal ticket MAGETWO-70354 to address this issue.

**Comment by magento-engcom-team** [comment]
@paales, thank you for your report.
We've created internal ticket(s) MAGETWO-70354, MAGETWO-73121 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#52
