### ISSUE TITLE
Gray Bars showing up through all images across catalog

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6702]
Magento 2.1.0. Images have previously shown up fine. The only major changes I've made is to go to flat files but I checked after I did this and everything appeared to be fine. 
Anyone have any suggestions on what to look at?
Thank you.

<img width="944" alt="screen shot 2016-09-21 at 2 10 06 pm" src="https://cloud.githubusercontent.com/assets/21045500/18729259/f78cb1e8-8005-11e6-898e-1902738be29f.png">
<img width="723" alt="screen shot 2016-09-21 at 2 10 50 pm" src="https://cloud.githubusercontent.com/assets/21045500/18729260/f985a356-8005-11e6-8c17-180b45b30302.png">

**Comment by veloraven** [comment]
@rosandrest thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is a question and you look for some help from community, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. The GitHub issue tracker is intended for technical issues only.
