### ISSUE TITLE
Something went wrong Error in Product Catalog.

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#6704]
### Steps to reproduce

1.  Disable Reviews Module in magento admin. Stores->Configuration->Advanced->Advanced.
2.  when i disable the Reviews module, i am unable to edit Catalog-> Products.
3.  Error: Something went wrong.
### Expected result

1.  I want to disable the review module and product needs to be edited.
### Actual result

1. Actual error while editing the product is "Something went wrong".

**Comment by miakusha** [comment]
Hi @sasilinux , thank you for your report
We've created internal ticket MAGETWO-58849 to address this issue.

**Comment by ronnybremer** [comment]
Same issue on our installation, CE 2.1.1.

Ronny

**Comment by hostep** [comment]
@miakusha: this issue was already reported multiple times, all the tickets link to this one: https://github.com/magento/magento2/issues/5323 and that one already has a MAGETWO reference assigned to it, maybe it's best to mark these in your internal ticketing system as duplicates?

**Comment by irenelagno** [comment]
@sasilinux , @ronnybremer , @hostep Fix for this issue was delivered to develop branch in the scope of b046944

**Comment by miakusha** [comment]
Closed as already fixed

**Comment by Ctucker9233** [comment]
Does this fix work for 2.1.1 or are we waiting on a port?

**Comment by irenelagno** [comment]
@Ctucker9233, This fix will be delivered to 2.1.x in the scope of MAGETWO-59246

**Comment by ghost** [comment]
No fix in 2.1.2, same issue.

**Comment by Ctucker9233** [comment]
@irenelagno Any idea when that fix will be ready?

**Comment by Mattyweeks** [comment]
Would really like an answer to this too!

**Comment by infoitservit** [comment]
No Fix yet?

**Comment by ghost** [comment]
Technically it has been fixed, its just stalled on the development version. Would be nice to know when these issues are gonna be implemented into the mainline so we don't have to check for them with each magento install/upgrade we do.  Especially since this was marked as fixed a month ago.
