### ISSUE TITLE
Notice undefined index when changes swatch attribute

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#6706]
### Steps to reproduce
1.  Create a text swatch attribute
2.  Change setting 'update product preview image' to 'Yes'
### Expected result
1.  No error
### Actual result
1. A notice error is shown of Swatches/Model/Plugin/EavAttribute.php line 177

**Comment by PascalBrouwers** [comment]
@miakusha Could you get this one going? It has a PR and everything.

**Comment by miakusha** [comment]
Hi @PascalBrouwers, We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue.

**Comment by PascalBrouwers** [comment]
Hmm, can't seem to reproduce it on a clean 2.1.1. install. Ok, closing it.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66417
