### ISSUE TITLE
Google Adwords add ability to provide transaction-specific conversion values in your conversion tracking tag

### ISSUE THREAD

**Issue by XigenDominic** [magento/magento2#6708]
Google Adwords Code does not allow providing transaction-specific conversion values in your conversion tracking tag
### Preconditions
1. Magento V2.1.1
### Steps to reproduce
1. Enable and configure Google Adwords
2. Complete transaction and taken to success page
### Expected result
1. Option and ouput to send google_conversion_currency e.g: var google_conversion_currency = "EUR";
   https://support.google.com/adwords/answer/3419241?hl=en-GB
### Actual result
1. Doesn't send currency.  Therefore doesn't allow for providing transaction-specific conversion values in your conversion tracking tag

**Comment by ArthurTransoftgroup** [comment]
@XigenDominic Unfortunately, I could not reproduce the issue as you described it. Read this article from Google about "How to track transaction-specific values on a website" and let me know if it helped you https://support.google.com/adwords/answer/6095947

**Comment by XigenDominic** [comment]
On that link you sent

Part 3: Add or modify the tag in your website's code

Expand PHP: Hypertext Preprocessor (PHP)

Should see "To add conversion tracking code to PHP pages using your web page editor, look to the code below, then remove from your own code the lines that are crossed out,..."

[...]
if (<? echo $totalValue ?>) {
    var google_conversion_value = <? echo $totalValue ?>;
    var google_conversion_currency = <? echo $currency ?>;
}
[...]

**Comment by XigenDominic** [comment]
Part 3 point 5

(Optional) If you accept different currencies, add a line within the if statement to accept currency: var google_conversion_currency = $currency.  In the noscript section of the tag, be sure to add &currency_code= $currency

**Comment by ArthurTransoftgroup** [comment]
@XigenDominic So in your case, the "if statement" doesn't work?

**Comment by XigenDominic** [comment]
That example is from the google docs.  But okay, in my case the if statement doesn't exist.

**Comment by ArthurTransoftgroup** [comment]
Thank you for your submission. If you are looking for some advice or discussion on that, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
 Feature Requests and Improvements should be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71642
