### ISSUE TITLE
Product Quantity displaying in decimals

### ISSUE THREAD

**Issue by mgomez-dgt** [magento/magento2#6713]
### Preconditions

Magento ver. 2.1.1
### Steps to reproduce

1. Create a Product with Quantity = 1 and Uses Decimals = No
### Expected result

![image](https://cloud.githubusercontent.com/assets/481124/18757831/208662e6-80bb-11e6-8c47-e65d6a55c467.png)
### Actual result

![image](https://cloud.githubusercontent.com/assets/481124/18757869/4eb90d8a-80bb-11e6-9e70-5726e6b2b4b2.png)

![image](https://cloud.githubusercontent.com/assets/481124/18757940/95ce0d4c-80bb-11e6-90e4-ffe805c348c8.png)

**Comment by mgomez-dgt** [comment]
after updated magento 2.1.2 same problem, Fix this please!

**Comment by pboisvert** [comment]
@mgomez-dgt we will need to reproduce the bug before it can be scheduled to be fixed. What is the impact of this bug? In other words what problem does the display of qty 1.00 vs 1 cause for you?

**Comment by mgomez-dgt** [comment]
It has a visual impact customer

![image](https://cloud.githubusercontent.com/assets/481124/19412188/d409115c-92d5-11e6-8a85-4d069b4f3487.png)

![image](https://cloud.githubusercontent.com/assets/481124/19412190/da88f588-92d5-11e6-88e3-7d17832c37c3.png)

**Comment by pboisvert** [comment]
so purely aesthetic impact then?

**Comment by mgomez-dgt** [comment]
yes

**Comment by mgomez-dgt** [comment]
posible solution http://magento.stackexchange.com/questions/109909/magento2-remove-decimal-from-quantity/109913

**Comment by dthampy** [comment]
internal jira ticket - MAGETWO-60074

**Comment by justanewbie00** [comment]
I'm having the same issue. Did you already fixed it? How?

**Comment by MonikaOlah** [comment]
I have the same issue.

**Comment by magento-engcom-team** [comment]
@mgomez-dgt, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by tony-sar** [comment]
this issue still exist in Version 2.2.2

**Comment by amon81** [comment]
this issue still exist in Version 2.2.3

**Comment by ghost** [comment]
This is still an issue in 2.3

**Comment by judin** [comment]
Not just aesthetic, but functional. Very very easy in a busy environment to mis-read this data.
