### ISSUE TITLE
Design Configuration is showing the wrong info 2.1.1

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#6714]
### Preconditions
1. Magento 2.1.1
2. PHP 7.0.9, MySql 5.6.27
### Steps to reproduce
1. Upgrade from 2.1.0 to 2.1.1
2. Admin -> Configuration -> general -> design
### Expected result
1. Showing the design configuration
### Actual result
1. 
   ![screenshot 52](https://cloud.githubusercontent.com/assets/17633236/18761745/0b84c428-80bb-11e6-97d7-d3ceab6d4173.png)

**Comment by ghost** [comment]
Design configuration is now under Admin -> Content -> Design -> Configuration.

**Comment by pboisvert** [comment]
closing as not an issue
