### ISSUE TITLE
Credit Card capture not associated with the Authorization since upgrade to 2.1.1

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#6716]
### Preconditions

Upgrade with sample data to Magento 2.1.1 
On Debian 8  LXC container 4GB ram 6 cores  PHP 7.0.10-1~dotdeb+8.1

Go to Stores --> Configuration --> Sales --> Payment Methods --> Paypal PayflowPro --> Basic Payment Settings and set "Payment Action" to "Authorization"
### Steps to reproduce
1.  Enter a credit card purchase
2. Check PayPal for authorization
3. Invoice the order in Magento 2
4. Check Paypal and see that the original "capture" is still available to be charged
### Expected result
1.  The original Authorization should get charged and no longer be available for "Capture" on the paypal interface.
### Actual result
1.   The Authorization is still in place, and resulting reserved from the customer's account are still reserved and no longer available for the customer until it "times out" or is voided.  A new authorize and capture was initiated unrelated to the original Authorization.
2.  Some transactions that have been previously "Authorized" won't Authorize again when the product is shipped because there is not enough credit on the customer's payment method after the un-attached authorization is not being captured, causing the product not to ship and administrative hassle getting it worked out.

This bug appeared upon the upgrade to 2.1 and was working fine on 2.0.9 previously.

I verified this with PayPal and received the following email from PayPal:

```
Thank you for contacting PayPal.

You are receiving payments from your customers and the customers are being charged twice.

Problem: There is an authorization with no correlating capture of funds and then there is a separate sale for the same customer.

So the Customer is seeing 2 transactions on their accounts.

Example: Authorization XXXXXXXXXXXXXXXX on 9/21. That is still a pending authorization. A sale was processed ZZZZZZZZZZZZZZZZZ on 9/21 for this customer as well. This sale is not associated with that authorization from a processing standpoint.  
Please contact your developer to advise of the issue.

Thank you for being part of the PayPal community.

Sincerely,
Tony
PayPal Business Customer Service
PayPal
```

Is there something related to the upgrade I can fix on this end, or do I have to charge customers when the order is placed?

Thanks for any help

**Comment by viktym** [comment]
Hi @joebusby 
We've created internal ticket MAGETWO-59086 to address this issue.
Thanks for reporting.

**Comment by alena-marchenko** [comment]
Hi @joebusby 

Fix for MAGETWO-59086 is already delivered to develop branch, closing the issue.
Thank you.

**Comment by Ctucker9233** [comment]
@alena-marchenko is there a commit reference?
