### ISSUE TITLE
magento 2.1.1 checkout/cart page empty

### ISSUE THREAD

**Issue by frameworkerrs** [magento/magento2#6717]
i have installed fresh 2.1.1.. and with dummy data.. mini cart working.. but the checkout/cart page shows empty when we have products in minicart..

if we remove all from minicart , the checkout/cart page shows correctly - message below

You have no items in your shopping cart.
Click here to continue shopping.

it seems problem from cart.phtml

if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items'); //RETURN EMPTY
}

any ideas

**Comment by veloraven** [comment]
@frameworkerrs thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
