### ISSUE TITLE
Fatal Error [Interface 'Magento\Store\Api\StoreWebsiteRelationInterface' not found] after Magento 2.1.1 initial setup

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6724]
### Preconditions

1. Magento version: 2.1.1;
2. PHP version: 5.6.24 FPM;
3. Linux distro: Debian 8.6.0;
4. Web server: nginx/1.10.1;
5. MySQL 5.7 running on a CoreOS instance [within a Docker container].
### Steps to reproduce

1.  Install all the pre-requisits;
2. Download [not clone] Magento 2.1.1 from the git repo;
3. Set the file system's permissions;
4. Install the dependencies running composer;
5. Run the magento CLI setup;
6. Check the permissions again.
### Expected result

1. I'm expecting Magento to work since the initial setup was successful and didn't show any warning.
### Actual result

1. When I try to reach the website [after re-enabling the php errors] the returned message I get is: 
   Fatal error: Interface 'Magento\Store\Api\StoreWebsiteRelationInterface' not found in [..] app/code/Magento/Store/Model/StoreManager.php on line 18

Any suggestions?

**Comment by shiftedreality** [comment]
Hi @d4gh0s7 

There is another structure of 2.1.1 https://github.com/magento/magento2/blob/2.1.1/app/code/Magento/Store/Model/StoreManager.php
And it's not using `StoreWebsiteRelationInterface.php`
Could you please re-check which version do you use?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
