### ISSUE TITLE
Dashboard Lifetime Sales, Average Order, Most viewed products do not update.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6725]
Dashboard Lifetime Sales, Average Order, Most viewed products do not update.
Environment:
Ubuntu / Apache / M 2.1.1 / AWS  / Timezone: IST (Indian standard)

Steps:
- Setup M2.1.1 server (upgraded 2.1.1 from 2.1).
- Migrated the data from older cart (This step should be irrelevant for this bug)
- Went live, started selling.

Current behavior: The Lifetime sales and average order show a fixed value that appeared after the data migration got done. New order values do not add up in those figures. The lifetime sale data is anyway wrong.

Also Most viewed products show as blank.

Expected: All these values should be dynamic and should get updated.

**Comment by julienanquetil** [comment]
Same issue here in 2.1.2 in Europe Timezone (Paris)

**Comment by shrff** [comment]
We're also having the same issue. We have multiple websites setup and it doesn't seem to update or add the values together.

**Comment by oshmyheliuk** [comment]
Hi all,

Probably you set configuration option "Sales" -> "Dashboard" -> "Use Aggregated Data"  to YES.
It improves dashboard performance but provides non-realtime data.
Otherwise, data load dynamically.

**Comment by oshmyheliuk** [comment]
> We're also having the same issue. We have multiple websites setup and it doesn't seem to update or add the values together.

It's calculated for each site separately, you need to change site in storeview selector, to see  dashboard for different sites.
![screenshot_4](https://cloud.githubusercontent.com/assets/18550571/20356661/dabf14bc-ac2d-11e6-9bb4-735495a655dc.png)

**Comment by shrff** [comment]
Thanks for looking into this @oshmyheliuk !

I understand that we can change the site to show different values but by default it shows _All Store Views_ and our client, understandably, has an expectation that it should show global sales data. 

Is it supposed to show a global total? If not, is there anyway of disable the All View?

**Comment by oshmyheliuk** [comment]
@shrff,
I have just tested it, by default  sales are calculated globally, if you do not select any store or website.
But orders in some statuses, like "new" or "pending_payment" not calculated in total.
Please specify, do you use Aggregated Data for Dashboard?

**Comment by shrff** [comment]
Hi @oshmyheliuk 

It may help if I fill the bug report in and tell you what we've tried so far. 

## Preconditions
1. Magento 2.1.2
2. Two Magento store views. One aimed at US customers (currency USD), one aimed at UK customers (currency GBP)
3. Sales in both store views.

## Steps to reproduce
1. Login to admin area
2. By default, All Store Views is shown by default. Currently shows lifetime sales of $147.38.
3. Switch Store View to US Store View and lifetime sales shows as $1,394.66.
4. Switch Store View to UK Store View and lifetime sales shows as £147.38. 

## Expected result
1. All Store View to show combined total of US and UK store view. 

## Actual result
1.  Lifetime sales shows as £147.38. 

---

Your previous comment mentioned going to Stores > Config > Sales > Sales > Dashboard and switch use aggregated data to Yes got the following results (previously, this was switched to No):
1. All Store View: $87.43
2. US Store View: $0.00
3. UK Store View: £87.43

Is this all linked to the reports issue that we've posted about also? I assume that this data is based off of data in the reports section? 

https://github.com/magento/magento2/issues/6726

**Comment by oshmyheliuk** [comment]
Hi @shrff ,

Unfortunately, I could not reproduce the issue as you described it on freshly installed Magento 2.1.2.
Lifestyle sales for all store view are equal to sum from US and UK store views, everything work as expected.

Maybe you install custom modules that affect dashboard logic?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
