### ISSUE TITLE
asking for right php version when already there

### ISSUE THREAD

**Issue by to8gal** [magento/magento2#6727]
So I first installed Magento on Mamp, all great except on extension manager fail readiness, say was the cron but the cron was there, etc, after a few trial you guys said no support for a local on osx and mamp, and that I should use homebrew.

Thats waht I did, installed it, all php there, mcrypt there, mysql there, all right version, vhosts neabled but then when I go on the install page say this 👍 
Magento supports PHP 5.6, 7.0.2, and 7.0.6 or later. Please read Magento System Requirements.
### Preconditions

1. Magento 2.1 on osx yosemite with mysql 5.6 and php 5.6 with homebrew latest version
2. ssl enabled
### Steps to reproduce

1. enabled vhosts on mac with apache server
2. installed homebrew, 
3. updated php (mysql already there)
4. installed mcrypt
5. modified php.ini
6. cron checked already there and working
7. downloaded magento package
   installed magento
8. go on .../setup and then warning
### Expected result

1. install starting page of magento2
### Actual result

1. Magento 2.1 on osx yosemite with mysql 5.6 and php 5.6 with homebrew latest version

php info is blank

**Comment by veloraven** [comment]
@to8gal thank you for your feedback.
The problem you described is not Magento issue. 
Your Apache server does not seem to be set up properly.
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions related to using Magento with OS X.
But anyway you will need to set up your Apache server correctly first.

**Comment by to8gal** [comment]
I solved the problem myself, the server was actually configured right, was a missing cron file that I thougth was autogenerated, but obviously was not. thanks
