### ISSUE TITLE
catalogProductAttributeMediaGalleryManagementV1 POST call fails to create new Gallery entry

### ISSUE THREAD

**Issue by Giri-Happiest-Minds** [magento/magento2#6728]
We tried adding a new Gallery entry using the POST call but the API throws below exception (Json response)
,
{
  "message": "The image content must be valid base64 encoded data."
}

Endpoint URL: /V1/products/{sku}/media
API: catalogProductAttributeMediaGalleryManagementV1
Below is the request Json
{
  "entry": {
        "id": 3038,
    "media_type": "image",
    "label": "",
    "position": 1,
    "disabled": false,
    "types": [
      "image",
      "small_image",
      "thumbnail"
    ],
    "file": "/w/t/wt09-yellow_main.jpg",
    "content": {
      "base64_encoded_data": "string",
      "type": "string",
      "name": "string"
    },
    "extension_attributes": {
      "video_content": {
        "media_type": "string",
        "video_provider": "string",
        "video_url": "string",
        "video_title": "string",
        "video_description": "string",
        "video_metadata": "string"
      }
    }
  }
}

**Comment by veloraven** [comment]
@Giri-Happiest-Minds thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
