### ISSUE TITLE
New Setup System

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#673]
I know that the setup system available since alpha 96 is just at the beginning and you already know some issues about it but I thought to add some in here: 

 - The setup page is still accessible after installing Magento
 - If the setup is a kind of a "standalone" application is there any need for the `Magento_Install` module?
 - If I install Magento 2 over an existing database (sample data) that already contains some records in the `authorization_role` table (old `admin_role` table), where the role_name `Administrators` has an other id beside 1 I cannot login in the backend because the parent role is hardcoded in `Magento\Setup\Model\AdminAccount`.
 - Is there really a need to run the data updates with the `exec` command? It seams to me like it introduces an unnecessary dependency. Some servers may not allow this. If it's necessary, maybe a check should be made and notify the user that the server does not allow `exec`. 
 - The install log file is named `install.log`. I think it's better to have a unique name. If I run 2 install processes on the same machine at the same time the file is locked by the first install and I cannot see the progress on my second install. I know this is a rare case, but still....

**Comment by muasir** [comment]
@tzyganu we have fixed most of the issues listed in this post.  I am closing this issue, as fixed.  Feel free to open new issue if we missed anything.

**Comment by tzyganu** [comment]
@muasir everything seams to work now. Thank the team from me for the great job.

**Comment by Janesmith03** [comment]
The issues you’ve mentioned about the Magento 2 setup, such as the accessible setup page post-installation and the use of hardcoded values in setup models, are crucial points that need addressing to ensure a secure and efficient Magento 2 installation. It's important to follow best practices for a secure and optimized Magento 2 setup. For step-by-step instructions and solutions to common setup challenges, you might want to explore detailed [Magento 2 setup](https://devrims.com/blog/how-to-install-magento-2-localhost-xampp/) guides available online.
