### ISSUE TITLE
salesCreditmemoManagementV1 PUT call doesn't cancel credit memo

### ISSUE THREAD

**Issue by Giri-Happiest-Minds** [magento/magento2#6730]
We tried cancelling a credit memo using salesCreditmemoManagementV1 PUT call but the API threw the below warning,

{
  "message": "You can not cancel Credit Memo"
}

API: salesCreditmemoManagementV1 
Endpoint URL: /V1/creditmemo/{id}

There is no JSON request as per DevDoc

**Comment by veloraven** [comment]
@Giri-Happiest-Minds thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by mbrinton01** [comment]
@Giri-Happiest-Minds when reporting an API issue please provide the exact API call including body so our teams can reproduce the issue. Thanks!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
