### ISSUE TITLE
Backend still redirects to 404

### ISSUE THREAD

**Issue by mattcoz** [magento/magento2#6735]
#2278

This is closed but it is still not fixed. The commit is not in the released Magento 2.1.1.

**Comment by veloraven** [comment]
@mattcoz thank you for your feedback.
Please describe this issue this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result, if it is still reproduces.
Please also leave a note about closed duplicate issue.

**Comment by mattcoz** [comment]
Preconditions: Magento installed on ports other than 80 and 443
Steps to reproduce: Try to access backend
Actual result: 404 not found
Expected result: Backend loads

This is a duplicate of #2278 that was closed because they thought it was fixed.
Pull request #2303 fixes it but is not included in the latest release.

I've applied that change to my installed copy and it does fix the issue.

**Comment by shiftedreality** [comment]
Hi @mattcoz 

Fix for issue you linked already included into 2.1.1 https://github.com/magento/magento2/commit/8b807696a9d2451516666c8ce91e982d6d94d6a4
Please create new issue if you still experience this problem on latest 2.1.1

Closed.

**Comment by mattcoz** [comment]
This _was_ the new issue. Fine...
