### ISSUE TITLE
How to solve Check Component Dependency Error in magento 2.1.1

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#6736]
![magento24_9](https://cloud.githubusercontent.com/assets/16436069/18806460/e7fa7f84-824a-11e6-9df8-44e3809bb1d9.PNG)

Any one Help me how To solve ???
please Comment.........

**Comment by veloraven** [comment]
@mitulispace please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by mitulispace** [comment]
Step-1 (I install Extension)
System => Web Setup Wizard => Component Manager(With marketplace)  => Install EXTENSIONS  But This Type Error Show 

Then  
![e7fa7f84-824a-11e6-9df8-44e3809bb1d9](https://cloud.githubusercontent.com/assets/16436069/18827707/d301f532-83f1-11e6-94b0-7d947df14643.PNG)

<h2>Actual Result</h2>

without Error    EXTENSIONS   install How to ??? @veloraven 
Sorry For my English

**Comment by shiftedreality** [comment]
Hi @mitulispace 

Is it Composer or GIT installation?

**Comment by mitulispace** [comment]
Composer

**Comment by mitulispace** [comment]
This issue  Solved    extension Not Support
