### ISSUE TITLE
Component Manager Hangs - Spinning Wheel

### ISSUE THREAD

**Issue by jedhodson** [magento/magento2#6737]
### Preconditions
1.  Magento 2.1.1 CE
2.  Remote MySQL Server (LAN)
3. I have had access to the Component Manager before with it working
4. Dedicated Host (Ubuntu 16.01.1 LTS)
### Steps to reproduce

1. Log in to backend
2.  System > Web Setup Wizard > Component Manager
### Expected result

1.  Access to Magento Component Manager to install and upgrade modules from marketplace
### Actual result

1. Constant loading wheel
2. Errors as show in Screenshot appear
   ![error](https://cloud.githubusercontent.com/assets/4703536/18806773/ce08c214-8279-11e6-82c7-78ddcd53733c.png)

**Comment by jedhodson** [comment]
I have checked the permissions on the setup directory (even gave it the dreaded 777 permission). 
Are there any other directories that permissions affect the component manager?

**Comment by veloraven** [comment]
@jedhodson thank you for your report.
Was it clear install or upgrade from some previous version?

**Comment by jedhodson** [comment]
@veloraven It was a clean install

**Comment by aarondong2005** [comment]
@veloraven Any update for the issue?

**Comment by shanevbg** [comment]
I have the same problem but a different console error
`angular.js:7715 GET https://MYSITE/setup/index.php/componentGrid/components 500 ()(anonymous function) @ angular.js:7715A @ angular.js:7429f @ angular.js:7214D @ angular.js:10168D @ angular.js:10168(anonymous function) @ angular.js:10940$eval @ angular.js:12703$digest @ angular.js:12126$apply @ angular.js:12728f @ angular.js:7321x @ angular.js:7634v.onreadystatechange @ angular.js:7704`

**Comment by BaDos** [comment]
Hi @jedhodson 

I cannot reproduce it.
Please provide your PHP error log and Magento logs.

**Comment by AgenturSchroeder** [comment]
Hi,

I have the same problem with following error:
Error: data.lastSyncData is undefined

```
@http://subdomain.domain.de/setup/pub/magento/setup/component-grid.js:15:20
r/h.success/<@http://subdomain.domain.de/setup/pub/angular/angular.min.js:71:82
ze/e/l.promise.then/D@http://subdomain.domain.de/setup/pub/angular/angular.min.js:98:513
ze/e/l.promise.then/D@http://subdomain.domain.de/setup/pub/angular/angular.min.js:98:513
ze/g/<.then/<@http://subdomain.domain.de/setup/pub/angular/angular.min.js:100:173
Yd/this.$get</h.prototype.$eval@http://subdomain.domain.de/setup/pub/angular/angular.min.js:110:369
Yd/this.$get</h.prototype.$digest@http://subdomain.domain.de/setup/pub/angular/angular.min.js:107:460
Yd/this.$get</h.prototype.$apply@http://subdomain.domain.de/setup/pub/angular/angular.min.js:111:171
f@http://subdomain.domain.de/setup/pub/angular/angular.min.js:71:335
x@http://subdomain.domain.de/setup/pub/angular/angular.min.js:76:181
ve/</v.onreadystatechange@http://subdomain.domain.de/setup/pub/angular/angular.min.js:77:224
```

I thought i write this here to help to find the problem.

**Comment by BaDos** [comment]
Hi @Irvz 

Please, write version of Magento and provide your PHP error log and Magento logs.

**Comment by AgenturSchroeder** [comment]
Hi @BaDos,

I'm sorry for the missing information.

Version: Magento 2.1.2 CE
Errorlogs: Thats the funny part - I don't get errors in the logs from Magento 2. 
(If you mean the ".log" files from magento2.)

PHP error logs:
Well, last but not least, here are the PHP error logs.

```
[18-Nov-2016 15:24:01 UTC] PHP Fatal error:  Allowed memory size of 104857600 bytes exhausted (tried to allocate 4096 bytes) in /kunden/1111111111/webseiten/folder/magentoshop/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php on line 539
[18-Nov-2016 15:24:01 UTC] PHP Fatal error:  Allowed memory size of 104857600 bytes exhausted (tried to allocate 24576 bytes) in /kunden/1111111111/webseiten/folder/magentoshop/vendor/magento/framework/Session/SessionManager.php on line 139
```

There is enought mem space for all scripts. I don't think that this the problem is. But maybe a script running crazzy and push it to the limit.

**Comment by BaDos** [comment]
@Irvz Please, write me value of memory_limit that returned by phpinfo().

**Comment by olafc100** [comment]
Hi, I have the same issue. Is this issue closed? What was/is the solution?
Thanks for the help.

Version: Magento 2.1.2 CE

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
As there was no answer with the information which was asked for, I'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by korostii** [comment]
Note: duplicate of #7958
