### ISSUE TITLE
Reindexing catalog_product_price - On Schedule does not reindex and generate inc Tax pricing

### ISSUE THREAD

**Issue by Buyur** [magento/magento2#6738]
Haivng issues calculating tax 
### Preconditions

Centos 6.8 / Magento 2.1.1  CE / Mysql 5.7.15 / PHP 5.6.26
### Steps to reproduce
1. Set indexers to On Schedule 
2. Execute on SSH :  php  bin/magneto indexer:reindex catalog_product_price
### Expected result
1. Indexer should complete with no erorrs and products should display inc and excl tax 
### Actual result
1. Indexer fails with no erorrs or log entires other than the command line message:
   'Table catalog_product_price_cl does not exist'
2. indexer_state table remains on status 'working' for price index.

Looked for this table and is not in DB Schema - cannot see it in the setup routines.  
All other indexes are working fine - tax is recalculated when setting index to On Save and saving each product individually.  
Setting index to On Save and running reindex on command line results in a rebuilt successfully, but no prices change and the tax inc is the same as tax excl.

**Comment by Buyur** [comment]
After some more reading, it would appear that the missing table is the changelog table which stores the results of fired triggers when prices are changed?  Not only is the table missing, I cant find any triggers in my DB??  I am using a VPS but I have also installed 2.1.1 clean on a dedicated box and still no triggers or table.  Maybe the setup is the area of the bug?

**Comment by Buyur** [comment]
More investigation - completely new installation on a Windows XAMP installation (different to Linux etc) - it appears that the tiggers and ...._cl tables (changelog tables) are created when you change from index On Save to Scheduled.....when I changed this on the admin side, all the triggers appeared in the DB along with the associated tables.

Not sure why happening in Windows but not on my linux installations - will recheck DB user permissions but they have full access etc

**Comment by Buyur** [comment]
ok - now have a situation where multiple updates of a product are creating multiple rows in catalog_product_price_cl - this has a structure where the entity_id can appear multiple times.  It appears that any combination of entity_id (1 or many) results in no actualy recalculation taking place?  Also when I have entered a single row and repeatedly run the reindex, something appears to take longer and then the table is cleared - sadly my product still has no Tax applied to the pricing :(

This is now very frustrating as there appears to be no documentation on this at all - I am reluctant to try and pick apart code of the indexer to try and udnerstand or make this work - any help would be wonderful.

Here's hoping

**Comment by Buyur** [comment]
ok - now have it so the mView is triggered and changes write to the catalog_product_price_cl table - but when the catalog_product_price reindex runs either via SSH or CRON - no price calculation takes place :(  rows are left in the _cl table.

This is a deal breaker as if M2 cannot perform a simple price recalc then its back to 1.9 or maybe time for another eCommerce solution that can calculate prices reliably?

**Comment by Buyur** [comment]
turned out to be a corruption in the M2 tables - repair and repopulate solved this.

**Comment by Tristan-N** [comment]
@Buyur Can you please tell me where you found the corruption? I have no clue where to start searching. I ask this because I have a similar issue.
