### ISSUE TITLE
SOAP api usually returns SOAP 12 but sometimes SOAP11

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#6740]
I add magento 2.1.0 SOAP api service reference to C# project. I use 
POST https://www.xxx.com/soap/default?services=salesOrderRepositoryV1 trying to get orded by id. If orders exists respons is SOAP 12 but if there is no order response is SOAP11

### Preconditions

1. Magento 2.1.0.
2. C#, WebService reference generated by Visual Studio
### Steps to reproduce

1. request:

```
POST https://www.mymagento.com/soap/default?services=salesOrderRepositoryV1 


<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><salesOrderRepositoryV1GetRequest xmlns="https://www.mymagento.com/soap/default?services=salesOrderRepositoryV1"><id xmlns="">432</id></salesOrderRepositoryV1GetRequest></s:Body></s:Envelope>
```
1. 
2. 
### Expected result

1. this is an example of response where magento order exists. Response is SOAP 12. Response body starts from

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://www.mymagento.com/soap/default?services=salesOrderRepositoryV1"><
```
### Actual result

1. Response is SOAP 11. Response body

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" >
   <env:Body>
      <env:Fault>
         <env:Code>
            <env:Value>env:Sender</env:Value>
         </env:Code>
         <env:Reason>
            <env:Text xml:lang="en">Requested entity doesn't exist</env:Text>
         </env:Reason>

      </env:Fault>
   </env:Body>
</env:Envelope>

```

UPDATE:

Another strange thing - is that really this order exists. I received this order `432` from GetList API function

**Comment by stamster** [comment]
Have you tried with REST API?

**Comment by MaximKitsenko** [comment]
I have already implemented SOAP wrapper for magento SOAP API and i want to make sure there is no another way to force magento to work via SOAP before looking into REST

**Comment by MaximKitsenko** [comment]
@veloraven  any updates? 

I have another example:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <catalogInventoryStockRegistryV1GetStockItemBySkuRequest xmlns="https://mystore/soap/default?services=catalogInventoryStockRegistryV1">
            <productSku xmlns="">qwerty
            </productSku>
        </catalogInventoryStockRegistryV1GetStockItemBySkuRequest>
    </s:Body>
</s:Envelope>
```

respnse:

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" >
   <env:Body>
      <env:Fault>
         <env:Code>
            <env:Value>env:Sender</env:Value>
         </env:Code>
         <env:Reason>
            <env:Text xml:lang="en">Product with SKU &quot;%1&quot; does not exist</env:Text>
         </env:Reason>         
      </env:Fault>
   </env:Body>
</env:Envelope>
```

**Comment by magento-engcom-team** [comment]
@MaximKitsenko, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
