### ISSUE TITLE
ComposerInformation.php for new packagename

### ISSUE THREAD

**Issue by tichimura** [magento/magento2#6741]
### Preconditions

1. Magento 2.1.0 CE
2. setup process is failed at PHP Version Check
3. ComposerInformation.php has old package name, which should be not latest
### Steps to reproduce

1. start the magento
2. access to the browser
3. setup process is failed at PHP Version Check
### Expected result

1. At Magento/Framework/Composer/ComposerInformation.php, the line 118 should be changed from 'magento/product-community-edition' to 'magento/community-edition'
   https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Composer/ComposerInformation.php#L118
### Actual result

1. [Screenshot, logs]
   ![image](https://cloud.githubusercontent.com/assets/1793451/18813113/ef156464-8326-11e6-8363-330d516a96ec.png)

$curl http://magento-tichimura.cfapps.haas-27.pez.pivotal.io/setup/index.php/environment/php-version?type=installer
{"responseType":"error","data":{"error":"phpVersionError","message":"Cannot determine required PHP version: Cannot find php version requirement in \u0027composer.lock\u0027 file"}}

**Comment by rliukshyn** [comment]
Hi @tichimura ,
We need more information about this issue in order to successfully investigate potential fixes.
Please describe:
- What is the reason of intentional php check failure?
- What is the reason of changing package name to old in ComposerInformation.php?
- Why do you expect change of code in ComposerInformation.php after php check failure?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
