### ISSUE TITLE
Textarea element cols and rows

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#675]
The values for textarea admin form elements are added after calling the [parent constructor](https://github.com/magento/magento2/blob/master/lib/internal/Magento/Framework/Data/Form/Element/Textarea.php#L51).  
This means that if I add an element in the admin form and specify the cols or rows they will be ignored.

    $fieldset->addField('some_name', 'textarea', array(
            'name'      => 'some_name',
            'label'     => __('Some Label'),
            'title'     => __('Some Label'),
           'rows' => 10,
           'cols' => 40
        ));

I end up with

    <textarea data-ui-id="....-fieldset-element-textarea-some-name" class=" textarea" cols="15" rows="2" title="Some Label" name="some_name" id="some_name"></textarea>
In order to change the cols and rows I need to get the element from the fieldset and set the cols and rows.  
I think the setters in the constructor should be wrapped in an if statement. This should solve the issue.

    if (!$this->getRows()) {
       $this->setRows(2);
    }
    if (!$this->getCols()) {
        $this->setCols(15);
    }

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-29012

**Comment by vpelipenko** [comment]
@tzyganu, we have internal ticket for this fix, but if you want to speed up this, your pull request is very welcome.

**Comment by vpelipenko** [comment]
Pull request #1136 for this is accepted and it is available from 0.74.0-beta3. Thank you, @tzyganu, for contribution.
