### ISSUE TITLE
Special price for the configurable products

### ISSUE THREAD

**Issue by thaopw** [magento/magento2#6752]
### Preconditions

1. Magento CE version 2.1.1
2. PHP 5.6, 7.0.10
3. Mysql version 5.6 & 5.7
4. Nginx
### Steps to reproduce
1. Create an attribute_code is demo_attribute for product
2. Create configurable product A with above attribute includes 2 simple products: A1, A2.
3. Add Special Price for A1, A2 products with range days specific.
4. Special Price of A1 < A2.
5. Special Price of A1 has expired
### Expected result

1. Frontend displays the special price of A2 product.
2. Removed special product of A1, display special product of A2 
### Actual result

1.The Categories/Product details page(in frontend) displays the special price of A1 Product (Although it has expired).
2. Removed the special price of A1. the final price product doesn't get from the special price A2.
1. Catalog category/Product details page(in frontend) displays the special price of A1 Product (Although it has expired).
2. Removed special price of A1. the final price doesn't get from the special price A2

![a1_product](https://cloud.githubusercontent.com/assets/16154068/18830117/815cf4f8-8409-11e6-9ab9-5c9cd1460d1a.png)

![a2_product](https://cloud.githubusercontent.com/assets/16154068/18830118/815fc7aa-8409-11e6-9001-92d249045b0a.png)

![categories_page](https://cloud.githubusercontent.com/assets/16154068/18830146/a1f4f3aa-8409-11e6-9db9-4c2ab801037e.png)

![product_details](https://cloud.githubusercontent.com/assets/16154068/18830119/81602704-8409-11e6-8b4e-191212b1dc66.png)

**Comment by miakusha** [comment]
I’m closing this issue because it is a duplicate #6457
We have internal ticket MAGETWO-58010
