### ISSUE TITLE
Translation order and overwrite

### ISSUE THREAD

**Issue by kassner** [magento/magento2#6753]
Hi!

As defined in [Magento\Framework\Translate](https://github.com/magento/magento2/blob/8931b9c27bd3b446b5774a98f3ee8fd6306c2fb2/lib/internal/Magento/Framework/Translate.php#L179-L182), the language pack a a higher priority than the theme's translations. For system integrations, this means DB translations is the only way to overwrite a translation right now (we can create a language pack, but then I'll need a new language pack for each project).

Also, I think it should be possible to overwrite the translations on `app/i18n`, as the same way we can add project-specific modules and themes.

Any thoughts?

**Comment by hostep** [comment]
Duplicate: https://github.com/magento/magento2/issues/6563
PR with possible fix: https://github.com/magento/magento2/pull/4783
