### ISSUE TITLE
Page number is not reset to 1 after clearing all applied filters

### ISSUE THREAD

**Issue by alexkuk** [magento/magento2#6755]
### Preconditions
1. Magento CE 2.1.1 
2. Luma theme
### Steps to reproduce
1. Go to a category page with available filters
2. Filter by some attribute value
3. Go to page 2
4. Click Clear All
### Expected result
1. First page is displayed
### Actual result
1. Still second page is displayed, that is not relevant anymore

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59171. Thanks for reporting.

**Comment by magento-engcom-team** [comment]
@alexkuk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
