### ISSUE TITLE
EAV Attributes Unit (e.g. mm, ml, oz)

### ISSUE THREAD

**Issue by SRaromicon** [magento/magento2#676]
It would be great to get an extra field for attributes, that  holds the unit of an numeric / decimal attribute.

Now you have to save every attribute, which has an unit like mm, oz or V, as an attribute of type varchar. 
In very large stores with more than 2000 attributes the varchar table becomes very large and the other tables are not used, because you need the unit of meassurement.

**Comment by oisvidi** [comment]
Would be helpful for shipping. 

Unit conversion library you might like: https://github.com/triplepoint/php-units-of-measure
(each carrier defines the unit it uses)

Dimension packaging for shipment: https://github.com/dvdoug/BoxPacker
(each carrier defines boxes with length, width, height and weight).

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-29013

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/EAV-Attributes-Unit-e-g-mm-ml-oz/idi-p/47353).
