### ISSUE TITLE
Cannot trigger gateway's refund function in a custom payment module

### ISSUE THREAD

**Issue by phuctma** [magento/magento2#6760]
### Preconditions

1. Magento ver. 2.2.0-dev
2. PHP 5.6.23
### Steps to reproduce
1. I'm developing a custom payment module for credit card processing
2. The order processed and online invoice created successfully with my custom payment method
3. Open the invoice and click the Refund button
### Expected result

The refund function in the custom payment method model should be triggered
### Actual result

Cannot trigger gateway's refund function in a custom payment module

I found the root cause that the method `$creditmemo->getDoTransaction()` return null.
https://github.com/javilumbrales/magento2-openshift/blob/master/public/app/code/Magento/Sales/Model/Order/Payment.php#L621

Please explain the method `$creditmemo->getDoTransaction()`? How to make it works in this case.
Thanks.

**Comment by mrkhoa99** [comment]
Hello @phuctma,

As far as I know, `$creditmemo->getDoTransaction()` may get value from
`vendor/magento/module-sales/Model/Service/CreditmemoService.php`

```
public function refund(
        \Magento\Sales\Api\Data\CreditmemoInterface $creditmemo,
        $offlineRequested = false
    ) {
       ......
        $creditmemo->setDoTransaction(!$offlineRequested);
      ......

    }
```

As we can see, it's a flag for checking types of transaction(offline or online).
Additionally, for invoice, we also have the same logic for type of capture(offline or online): `$invoiced->setRequestedCaptureCase(self::CAPTURE_ONLINE);`.

**P.S:**  It's better if you post your question on [Magento StackExchange](http://magento.stackexchange.com/).

**Comment by phuctma** [comment]
Thanks @mrkhoa99 

I found that the line `$creditmemo->setDoTransaction(!$offlineRequested);` not exist in the current default repository of magento 2 (even the string `setDoTransaction`) but in the installation package get from Magento download page (under `vendor` directory).

This poses a bug here, right?

**Comment by YevSent** [comment]
Hi, @phuctma, as said @mrkhoa99 , the `getDoTransaction` state depends on selected refund type (offline or online). 
Online refunds only available per invoice, if you will do a refund for all order it will be offline.
If you open invoice for place order, you will see two buttons:  
![refund](https://cloud.githubusercontent.com/assets/2736528/18865323/5a1f6dd6-84a3-11e6-8511-a41e20e81be9.png). Depends of selected button type of refund will be different.

All logic for refund located in the [RefundOperation](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Creditmemo/RefundOperation.php#L117).

**Comment by phuctma** [comment]
Thanks @joni-jones 

I used the correct "Refund" button. Could you please advise why the `setDoTransaction` not exist in whole Magento 2 code (I means the Magento responsitory here) but it has the check `$creditmemo->getDoTransaction())` in the file https://github.com/javilumbrales/magento2-openshift/blob/master/public/app/code/Magento/Sales/Model/Order/Payment.php#L621 ?

**Comment by YevSent** [comment]
The `Capture Operation` doesn't exist because your custom repository is outdated.
Latest commit 8cac4ba  on Dec 4, 2015 @javilumbrales
