### ISSUE TITLE
Some backend pages not loading while inline translate active.

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6761]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Activate inline translation for backend
2. Open product edit or category pages (may be there are more pages)
### Expected result

1. Able to translate
### Actual result

1. Page loader spin and spin and spin ... No result
2. In js console, there was an error:

```
Uncaught SyntaxError: Unexpected token [ in JSON at position 2730
getNodeData @ scripts.js:86
(anonymous function) @ scripts.js:116
apply @ main.js:63
bootstrap @ bootstrap.js:70
fire @ jquery.js:3099
add @ jquery.js:3145
jQuery.fn.ready @ jquery.js:3379
jQuery.fn.init @ jquery.js:2819
jQuery.fn.init @ jquery-migrate.js:225
jQuery @ jquery.js:75
.....
...
..
```

**Comment by veloraven** [comment]
@rbostan thank you for your report.
Was it clear install or upgrade from some previous version?
Did you try to clean browser cache including offline website data?

**Comment by cizgidekiadam** [comment]
I tried clean all kind of cache (browser, magento etc..)
I have upgraded from 2.1 to 2.1.1 via composer.

**Comment by rliukshyn** [comment]
This is a known issue, internal ticket MAGETWO-53913. Thanks for reporting. Duplicates ticket https://github.com/magento/magento2/issues/6299

**Comment by PascalBrouwers** [comment]
@kriby is the the same issue as https://github.com/magento/magento2/issues/6855 ?
veloraven is talking about another ticket but I cannot find it, except this one.
