### ISSUE TITLE
Magento2 can't make a user role   

### ISSUE THREAD

**Issue by Lielcw** [magento/magento2#6769]
index: title in [...]/vendor/magento/module-integration/Helper/Data.php on line 24

**Comment by veloraven** [comment]
@Lielcw please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by Lielcw** [comment]
Hi this is a bug! i think attribute title is not correct?
Magento vesion 2.04 upgraded to 2.09

**Comment by pboisvert** [comment]
@Lielcw thanks for adding the version

Can you provide step by step instructions for what you are trying to do including any error messages that are shown?

**Comment by Lielcw** [comment]
@pboisvert  Thank you for response!
Yes i go in the backend to system >> User Roles and  Push the button "Add New Role" this give directly 
::::Notice: Undefined index: title in /home/xxxxxx/xxxx/xxxxxx/xxxxx/xxxxx/vendor/magento/module-integration/Helper/Data.php on line 24 
:::::::#0 /home/xxx/xxx/xxxx/xxxxl/xxxxx/vendor/magento/module-integration/Helper/Data.php(24): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/xxxxx/xxxxxx...', 24, Array)

Total 93 rows with errors

:::::::#92 /home/xxxxx/xxxxxx/xxxxxx/xxxxx/xxxxxx/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
:::::::::#93 {main}

**Comment by Lielcw** [comment]
Nobody a solution to fix this?

**Comment by refaelgold** [comment]
Its not work for me at magento 2.1.1 
its seems like the acl.xml of specific module is shutting down the whole process. 

its very hard to find which module do it because the log not give any information about it. 

please provide a better log or if the acl.xml not current - skip this module and not throw a fatel  error without any alternative to create a new role .

**Comment by Lielcw** [comment]
Hi,
Thank you for your time!
I have the hole error page perhaps you can see something?

**Comment by Lielcw** [comment]
Hi,
Thank you for your time!
I have the hole error page perhaps you can see something?
Notice: Undefined index: title in /xxxx/vendor/magento/module-integration/Helper/Data.php on line 24
#cd /home/liesmag2/domains/magento2-developer.nl/public_html/bidetdouche.nl/0 /xxxx/vendor/magento/module-integration/Helper/Data.php(24): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/bidetmag2...', 24, Array)
#1 /xxxx/vendor/magento/module-user/Block/Role/Tab/Edit.php(151): Magento\Integration\Helper\Data->mapResources(Array)
#2 /xxxx/vendor/magento/module-user/view/adminhtml/templates/role/edit.phtml(40): Magento\User\Block\Role\Tab\Edit->getTree()
#3 /xxxx/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/bidetmag2...')
#4 /xxxx/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\User\Block\Role\Tab\Edit), '/home/xxxxx…’, Array)
#5 /xxxx/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/xxx…’)
#6 /xxxx/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#7 /xxxx/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#8 /xxxx/vendor/magento/module-backend/Block/Widget/Tabs.php(387): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /xxxx/vendor/magento/module-backend/view/adminhtml/templates/widget/tabs.phtml(57): Magento\Backend\Block\Widget\Tabs->getTabContent(Object(Magento\User\Block\Role\Tab\Edit))
#10 /xxxx/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/xxxxxx…’)
#11 /xxxx/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\User\Block\Role\Edit), '/home/bidetmag2...', Array)
#12 /xxxx/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/bidetmag2...')
#13 /xxxx/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#14 /xxxx/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#15 /xxxx/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /xxxx/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.user....')
#17 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.user....')
#18 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.user....')
#19 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.user....', true)
#20 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.user....')
#21 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('left')
#22 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#23 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#24 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', true)
#25 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#26 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('side.col')
#27 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#28 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#29 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', true)
#30 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#31 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#32 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#33 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#34 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#35 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#36 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#37 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#38 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#39 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#40 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#41 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#42 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#43 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#44 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#45 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#46 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#47 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#48 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#49 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#50 /xxxx/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#51 /xxxx/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#52 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#53 /xxxx/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#54 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#55 /xxxx/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#56 /xxxx/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#57 /xxxx/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#58 /xxxx/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /xxxx/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#60 /xxxx/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /xxxx/vendor/magento/module-user/Controller/Adminhtml/User/Role/EditRole.php(44): Magento\Framework\App\View->renderLayout()
#62 /xxxx/var/generation/Magento/User/Controller/Adminhtml/User/Role/EditRole/Interceptor.php(24): Magento\User\Controller\Adminhtml\User\Role\EditRole->execute()
#63 /xxxx/vendor/magento/framework/App/Action/Action.php(102): Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor->execute()
#64 /xxxx/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#65 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#66 /xxxx/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#67 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor->___callParent('dispatch', Array)
#68 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\User\Co...', 'dispatch', Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Array, 'adminAuthentica...')
#69 /xxxx/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#70 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#72 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\User\Co...', 'dispatch', Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Array, 'designLoader')
#73 /xxxx/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#74 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#75 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#76 /xxxx/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\User\Co...', 'dispatch', Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Array, 'adminMassaction...')
#77 /xxxx/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#78 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#79 /xxxx/vendor/magento/framework/Interception/Interceptor.php(143): call_user_func_array(Array, Array)
#80 /xxxx/var/generation/Magento/User/Controller/Adminhtml/User/Role/EditRole/Interceptor.php(39): Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor->___callPlugins('dispatch', Array, Array)
#81 /xxxx//vendor/magento/framework/App/FrontController.php(55): Magento\User\Controller\Adminhtml\User\Role\EditRole\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#82 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#83 /xxxx/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#84 /xxxx/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#85 /xxxx/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#86 /xxxx/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#87 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#88 /xxxx/vendor/magento/framework/Interception/Interceptor.php(143): call_user_func_array(Array, Array)
#89 /xxxx/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#90 /xxxx/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#91 /xxxx/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#92 /xxxx/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#93 {main}

**Comment by kanduvisla** [comment]
This problem still persists in M2.1.1.

**Comment by endergreen** [comment]
The same error is thrown when trying to add a new Integration as well.

**Comment by slopukhov** [comment]
@Lielcw hank you for your feedback.
Please, recheck it on the latest 2.0 or 2.1 version of Magento.
Also, please, describe the version of: OS, PHP, MySQL, Apache or Nginx.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
