### ISSUE TITLE
Invoice Address Formatting Issue

### ISSUE THREAD

**Issue by gahinton** [magento/magento2#6771]
On the invoices, the address formatting is incorrect. It prints like the following:

Customer Name
54 N. Central Ave Campbell, 
California 95008
United States

It should print as:
Customer Name
54 N. Central Ave
Campbell, California 95008
United States

**Comment by veloraven** [comment]
@gahinton thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by gahinton** [comment]
I'm really not sure what more details I can provide other than this has happened with all version from 2.0 through 2.1.

This is on a default install with PayPal Standard checkout enabled. To see the results, just create a new order, go to the invoice and print it. The address information will be formatted as shown above. 
The city, state, and zip code should all be displayed on the same lines for United States address, not the city on the same lone as the street address.

**Comment by viktym** [comment]
Thanks for the feedback @gahinton 
We've created internal ticket MAGETWO-59112 regarding this.

**Comment by zanilee** [comment]
Hi, @gahinton!
The issue was fixed on develop in 779aa5f and fa9b9f0

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko What version of Magento will include MAGETWO-59112

**Comment by Ctucker9233** [comment]
@magento-engcom-team I created a backport to 2.1.x for this as it appears it hasn't been done yet.
