### ISSUE TITLE
M2.1.1 : PHP Throws Fatal Error when I use a Magento class in my header, but not literally in my class

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6783]
I'm not sure if this is a bug in Magento, or a PHP thing, but I've experienced 2 times already that PHP throws a fatal error in the following conditions:
- I use a Magento class in my header (see code example below)
- I don't literally use it, but only in a comment
### preconditions

See the following code:

```
namespace Vendor\Module\Helper;

use Magento\Catalog\Model\Product;

class Foo {
    public function () {
        // Let's imagine I have a method that returns a product collection.
        // I add this in my code so my IDE knows code-completion for $product:
        /** @var Product $product */           
        foreach ($productCollection as $product) {
            // do some stuff
        }
    }
}
```
### result

However, this will throw the following PHP Fatal Error:

```
Cannot use Magento\Catalog\Model\Product as Product because the name is already in use in ...
```

The same thing also happened to my once with `Magento\Catalog\Model\Entity\Attribute`.
### workaround

This can be fixed by removing the `use`-statement and providing the absolute reference, like so:

```
namespace Vendor\Module\Helper;

class Foo {
    public function () {
        // Let's imagine I have a method that returns a product collection.
        // I add this in my code so my IDE knows code-completion for $product:
        /** @var \Magento\Catalog\Model\Product $product */           
        foreach ($productCollection as $product) {
            // do some stuff
        }
    }
}
```

So is this a Magento thing or a PHP thing? It worked before in earlier Magento version (even in Magento 2.1.1), but all of a sudden it starts throwing errors. I develop in a virtual machine and my PHP version is also not affected in the meantime.

**Comment by FinBoWa** [comment]
It's a php thing:

http://stackoverflow.com/questions/17746481/cannot-use-x-as-y-because-the-name-is-already-in-use-even-though-its-not

But if you have opcache enabled it won't fire the fatal correctly see the bug report at https://bugs.php.net/bug.php?id=66773

**Comment by veloraven** [comment]
@kanduvisla could you please provide information about your environment including PHP version?

**Comment by kanduvisla** [comment]
I think it's what @FinBoWa mentions in his response.

**Comment by veloraven** [comment]
@kanduvisla thank you for your response.
I'm closing this issue then as it is not Magento issue.

@FinBoWa thank you for useful information.
