### ISSUE TITLE
Configuration menu error when change Frontend Development Workflow to Client side

### ISSUE THREAD

**Issue by robinhuy** [magento/magento2#6784]
I'm using Magento 2.1.1 (clone from Github).

When I change Frontend Development Workflow to Client side, menu of configuration page error. It's hard to reading menu item:

![css error](https://cloud.githubusercontent.com/assets/12640832/18904634/599c38c6-8589-11e6-9dc7-e6837450981e.jpg)

**Comment by mrkhoa99** [comment]
@robinhuy you should delete `pub/static/adminhtml` and `pub/static/frontend`, And then, run static deploy command again.

**Comment by robinhuy** [comment]
@mrkhoa99 thank you, it's work. I don't know must to delete `pub/static/adminhtml` after change Frontend Development Workflow.
