### ISSUE TITLE
M2.1 - Media attribute doesn't show in backend

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#6786]
### Preconditions

Magento 2.1 / PHP7.07 / Apache VPS
### Steps to reproduce
1. Add attribute as 'Media image', set Global
2. Add attribute to Attribute Group, assigned to simple product
3. Open simple product, attribute not showing
### Expected result

Attribute showing like other custom attributes I have added before
### Actual result

Attribute showing in column on backend product listing, but the attribute is not visible on the backend product single pages.

I've cleared the /var/, cache, compilation and indexes; no change.

It appears as though normal text-field attributes do show, but the media image attribute doesn't.

**Comment by sevos1984** [comment]
Media image attribute is treated as new role in product video upload. This is not a bug

**Comment by Asitis** [comment]
Okay, that wasn't clear to me, but I still don't understand. I add the attribute to the attribute group between other custom attributes and it doesn't show. You say it's treated as a new role in product video upload, but I don't see anything there either.
Where should I find it? 
Edit, nvm found it. The 'video upload' confused me. It's found in the regular product-images screen.
It's kinda strange though that the attribute can be placed somewhere in the attribute group without it actually showing up there.

**Comment by amenk** [comment]
This should be changed!

**Comment by amenk** [comment]
Maybe not .. you upload a product image and then choose a role - no need to use video upload. But what is not working is to put an image to a different attribute

**Comment by patrypombo** [comment]
I have same problem, when add a custom product attribute of type  Media image and add it to default set of attributes, it can't be showed at product backend page. How can I see it?

**Comment by BPSBiro** [comment]
Agreed with @amenk - I was struggling for good hour trying to find out why my product attribute for an image wasn't showing under a attribute folder in product creation. It wasn't until finding this post that I found out it only adds the attribute as a role - perhaps maybe a section just called "Image + Video Roles" or something similar that allows you to add it this way rather than as an attribute?

**Comment by mdruguet** [comment]
It's a bullshit, the type "media file" must be considered as others king of attribute
