### ISSUE TITLE
Impossible to Edit "Pages" for Super-Admin users in Magento Enterprise Edition

### ISSUE THREAD

**Issue by nuzil** [magento/magento2#6788]
### Preconditions
1. Magento EE - 2.1.1 - Clean Installation
2. System has 2 Websites
3. Was created separate Admin user/role and gave him an access just to 1 website (Magento EE Feature under System -> User Roles -> Role Resources)

<img width="1430" alt="screen shot 2016-09-29 at 13 12 20" src="https://cloud.githubusercontent.com/assets/1667889/18951614/63fed09a-8646-11e6-84fc-983db21e5efc.png">
### Steps to reproduce
1. Logout and Login as this new Creates user 
2. Go To: Content -> Pages -> Edit any page
3. 
### Expected result
1. User have to be able to Edit selected page 
### Actual result
1. Magento error
   In Report files:

`a:4:{i:0;s:966:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store.store_id' in 'where clause', query was: SELECT`main_table`.*,`page_table`.`title`AS`page_title`,`page_table`.`identifier`AS`page_identifier`, IF(clone.node_id IS NULL, 0, 1) AS`page_exists`, IF(main_table.page_id = '2', 1, 0) AS`current_page`, (SELECT GROUP_CONCAT(store_id SEPARATOR ',') AS`store_id`FROM`cms_page_store`AS`store`WHERE (store.row_id = main_table.page_id)) AS`page_in_stores`FROM`magento_versionscms_hierarchy_node`AS`main_table`
 LEFT JOIN`cms_page`AS`page_table`ON main_table.page_id = page_table.page_id AND (page_table.created_in <= 1 AND page_table.updated_in > 1)
 LEFT JOIN`magento_versionscms_hierarchy_node`AS`clone`ON main_table.node_id = clone.parent_node_id AND clone.page_id = '2' WHERE (store.store_id IN (0, '3')) HAVING (main_table.page_id IS NULL OR page_in_stores IS NOT NULL) ORDER BY`main_table`.`level`ASC,`main_table`.`sort_order` ASC
";i:1;s:14430:"#0 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(452): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(507): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection/AbstractDb.php(772): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection/AbstractDb.php(668): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection/AbstractDb.php(572): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Data/Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#13 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-versions-cms/Block/Adminhtml/Cms/Page/Edit/Tab/Hierarchy.php(153): Magento\Framework\Data\Collection->getIterator()
#14 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-admin-gws/Model/Blocks.php(412): Magento\VersionsCms\Block\Adminhtml\Cms\Page\Edit\Tab\Hierarchy->getNodes()
#15 [internal function]: Magento\AdminGws\Model\Blocks->prepareCmsHierarchyNodes(Object(Magento\Framework\Event\Observer))
#16 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-admin-gws/Model/CallbackInvoker.php(42): call_user_func_array(Array, Array)
#17 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-admin-gws/Observer/RestrictBlocks.php(65): Magento\AdminGws\Model\CallbackInvoker->invoke('prepareCmsHiera...', 'Magento\AdminGw...', Object(Magento\Framework\Event\Observer))
#18 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\AdminGws\Observer\RestrictBlocks->execute(Object(Magento\Framework\Event\Observer))
#19 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\AdminGws\Observer\RestrictBlocks), Object(Magento\Framework\Event\Observer))
#20 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#21 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('adminhtml_block...', Array)
#22 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-backend/Block/Template.php(103): Magento\Staging\Model\Event\Manager\Proxy->dispatch('adminhtml_block...', Array)
#23 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#24 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-ui/Component/HtmlContent.php(50): Magento\Framework\View\Element\AbstractBlock->toHtml()
#25 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(148): Magento\Ui\Component\HtmlContent->prepare()
#26 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\HtmlContent))
#27 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Container))
#28 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#29 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(126): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#30 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'cms_page_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#31 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#32 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#33 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#34 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#35 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#36 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#37 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#38 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#39 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#40 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#41 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Version...')
#42 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-versions-cms/Controller/Adminhtml/Cms/Page/Edit.php(24): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Version...')
#43 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php(90): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit->_initAction()
#44 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/VersionsCms/Controller/Adminhtml/Cms/Page/Edit/Interceptor.php(24): Magento\Cms\Controller\Adminhtml\Page\Edit->execute()
#45 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/App/Action/Action.php(102): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor->execute()
#46 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor->___callParent('dispatch', Array)
#49 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Version...', 'dispatch', Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Array, 'adminAuthentica...')
#50 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#51 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Version...', 'dispatch', Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Array, 'log')
#53 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#54 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Version...', 'dispatch', Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Array, 'adminMassaction...')
#56 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#57 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/VersionsCms/Controller/Adminhtml/Cms/Page/Edit/Interceptor.php(39): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#59 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/App/FrontController.php(55): Magento\VersionsCms\Controller\Adminhtml\Cms\Page\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#60 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#61 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#62 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#63 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#64 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#65 /Users/alexlyzun/Projects/code/rothenberg/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#66 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#67 /Users/alexlyzun/Projects/code/rothenberg/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#68 /Users/alexlyzun/Projects/code/rothenberg/www/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#69 {main}";s:3:"url";s:116:"/index.php/admin/admin/cms_page/edit/page_id/2/key/e8f075f58feb56335e1b5708976e30968b16107d814e0f25876e3a9ad9be17cc/";s:11:"script_name";s:10:"/index.php";}`

**Comment by veloraven** [comment]
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by franckgarnier21** [comment]
I report the same problem. EE support ticket just created.

**Comment by IvonWebdev** [comment]
Hello. Any fixes? I have the same issue in EE

**Comment by Rekha-periasamy** [comment]
Hello
 I'm using 2.1.17 Magento verison. I'm also facing the same issue. Let me the solution for this issue.

**Comment by nitish250788** [comment]
Hello Team,

I have fixed this issue via updating the admin user role as administrator. It is an admin permission issue. 
If you cannot see administrator have full access in the admin role grid, then you have to update this from the Database. 
Please go to authorization_role table >> find Administrators in role_name column >> Update gw_is_all column to 1 and set null for last two column as admin have access of all the backend features.

Please let me know still you have this issue.
