### ISSUE TITLE
Admin dashboard tabs.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#679]
I don't know if this is on your todo list but I thought It would be good to throw it in here.  
The tabs (and maybe all the elements) in the admin dashboard could be generated in a more abstract form.  
I mean, the dashboard should be just a list of placeholders that can be filled in by the rest of the modules.  
Right now the `Magento\Backend\Block\Dashboard\Grids::_prepareLayout` contains 4 hardcoded tabs that should be moved in the correct module.  
For example `Bestsellers` and `Most Viewed Products` could be part of the reports module, `New Customers` of course in the customer module and so on.  
Also a way to add custom tabs could be nice. I know about interceptors, but I'm not exactly sure I can intercept a protected method.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-29018

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-dashboard-tabs/idi-p/47150).
