### ISSUE TITLE
code folder missing in magento 2.1

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#6791]
Code Folder Missing in magento 2.1

**Comment by nuzil** [comment]
I guess its not missing, you just installed your system via composer with use vendor folder settings and all your /app/code files are in /vendor folder, just have a look into /vendor/magento ..

**Comment by mitulispace** [comment]
This folder  perfect ??  @nuzil 

![capture1111](https://cloud.githubusercontent.com/assets/16436069/18941033/0f4bb0d8-862b-11e6-9c3e-9541b61daa78.PNG)

**Comment by mitulispace** [comment]
Thanks.... @nuzil    I got it...
