### ISSUE TITLE
illegal string offset 'is_in_stock' when attempting to modify product imported from M2ePro.

### ISSUE THREAD

**Issue by djfordz** [magento/magento2#6797]
### Preconditions

1. CentOS6
2. Percona Server 5.6
3. PHP 7.0
4. Magento 2.1.1
### Steps to reproduce

1. import products via M2EPro
2. Attempt to edit product in Product->Catalog
3. 
### Expected result

1. form should appear to edit product
### Actual result

1. [Screenshot, logs]
   illegal string offset in app/code/Magento/CatalogInventory/Ui/DataProvider/Product/Form/Modifier/AdvancedInventory.php on line 88.

Logged code at location:
is not an array but a value.

To Fix:

```
changed this line in code:
if (isset($stockData['is_in_stock'])) {
        $data[$modelId][self::DATA_SOURCE_DEFAULT][$fieldCode]['is_in_stock'] =
        (int)$stockData['is_in_stock'];
    }

to

if (isset($stockData['is_in_stock'])) {
        $data[$modelId][self::DATA_SOURCE_DEFAULT]['is_in_stock'] =
        (int)$stockData['is_in_stock'];
    }
```

array went one too deep.

CentOS6, Percona Server 5.6, Magento 2.1.1

**Comment by veloraven** [comment]
@djfordz thank you for your feedback.
Could you please explain why do you think this to be Magento issue and not an issue of the extension's import?

**Comment by djfordz** [comment]
Are you saying the product could possibly be imported incorrectly? I will have to look into this, as I just assumed since the product was already imported and disconnected from M2ePro, that it was a Magento issue, however my assumptions do seem to get me in trouble lately.  I'll troubleshoot this issue further and give you an update.

**Comment by lhsatch** [comment]
Can you post your addtocart.phtml file (module-catalog\view\frontend\templates\product\view\addtocart.phtml) or if your module is using a different addtocart file can you upload that.

**Comment by veloraven** [comment]
@djfordz is there any update?
Is this issue still actual?

**Comment by djfordz** [comment]
You can close, I've been sick for over a week and have not had time to do any research, I've fixed the issue for the customer, I am just now getting back to work, most likely an M2Epro deal anyways if no one else is having issue. Thank you.

**Comment by veloraven** [comment]
@djfordz thank you for update.
If you face this issue again and have some proofs that this is Magento's issue, feel free to create the new GitHub issue.
