### ISSUE TITLE
USPS container type must be variable

### ISSUE THREAD

**Issue by aaronallen8455** [magento/magento2#6798]
In store configuration, when USPS container field is set to anything other than 'variable', no methods display in checkout. When set to 'variable' I get all applicable methods displayed but if I set it to 'flat rate box', no methods are displayed even though there are flat rate box methods displaying when I set it to variable.

### Preconditions

Magento 2.1.1, php7

1. USPS web tools account is set up.
2. USPS methods are being successfully displayed in checkout when container is type variable (including flat rate box).
### Steps to reproduce

1. Set container type to 'flat rate box'
### Expected result

1. just the applicable flat rate box methods are displayed in checkout
### Actual result

1. no methods displayed

**Comment by viktym** [comment]
Hi @aaronallen8455 
We've created internal ticket MAGETWO-59149 to address this issue.
Thanks for the feedback.

**Comment by alena-marchenko** [comment]
Hi @aaronallen8455 

Fix for MAGETWO-59149 tickets is merged to develop branch, closing the issue.
Thank you.

**Comment by Ctucker9233** [comment]
@alena-marchenko Will MAGETWO-59149 be included in 2.1.3?
