### ISSUE TITLE
icon not shown on https:// site

### ISSUE THREAD

**Issue by sonywibisono** [magento/magento2#6800]
I was new to install this platform, but I get a problem, that the icons cannot shown, only shown square box...

how to set this platform on https:// properly ...
thx

**Comment by jedhodson** [comment]
Just checked my site. Same issue. I have permanent http > https redirects in place. When I try to navigate to https://[SITE]/favicon.png (I have tried several different extensions including ico) it doesn't load. Just constantly loading. Have tried multiple browsers. Don't think its a permission problem, but will check that. 

Could you update your thread to include more about your Magento installation. I'm using CE 2.1.1 dedicated host.

Thanks

**Comment by jedhodson** [comment]
Ok just checked permissions. No difference, I set them to the dreaded 777 with no change. Word of warning - It did for some reason break the site. Had to refresh cache from a SSH terminal and restart apache

**Comment by jedhodson** [comment]
Here is my final findings on the issue. 
`DOM7009: Unable to decode image at URL: 'https://www.inticdev.com.au/favicon.png' with MIME: 'image/png'. favicon.png`

**Comment by paales** [comment]
Hi @sonywibisono,
1. To get help getting your installation up and running, you can ask questions on http://magento.stackexchange.com/ and https://community.magento.com/.
2. To request a new feature visit https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests
3. To report a bug, create an issue here on GitHub following the format in this file; https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md (else it will be closed without looking into).

**Comment by veloraven** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you have any Magento issues to be reported please create a new GitHub issue report  according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
