### ISSUE TITLE
Dashboard shows invalid currency for multi-currency setup

### ISSUE THREAD

**Issue by ronnybremer** [magento/magento2#6805]
### Preconditions

1. CE 2.1.1
2. PHP 5.6
### Steps to reproduce

1. Install CE 2.1.1
2. change default config: base currency: US-$, default display currency: US-$, allowed currencies: US-$
3. change website config: base currency: Swiss Franc, default display currency: Swiss Franc, allowed currencies: Euro, British Pound Sterling, Swiss Franc, US-$
4. add a single product "TestProduct", set price to 29.99 US-$ on default config and CHF 49.95 for website level.
5. search on the frontend for the product "TestProduct"
6. login to Dashboard
7. make sure to select "All Store Views"
8. click on "Most Viewed Products" tab
### Expected result

1. All amounts are displayed in "US-$"
### Actual result

1. All summary amounts are displayed in "CHF"
2. Only the "Most Viewer Products" are shown in US-$

![screen shot 2016-09-29 at 13 09 57](https://cloud.githubusercontent.com/assets/16883425/18951551/109b6bac-8646-11e6-85a0-86ebbb56bef3.png)

**Comment by ronnybremer** [comment]
as a side note: I changed the display label for CHF to SFr.

**Comment by dio5** [comment]
@ronnybremer I think we are experiencing this issue too. Is there any patch available for this or has the issue been confirmed? The dashboard seems totally confusing.

**Comment by IlnitskiyArtem** [comment]
@ronnybremer Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2?

**Comment by magento-engcom-team** [comment]
@ronnybremer thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation.
