### ISSUE TITLE
Order address edition from the backend disables the "region" field

### ISSUE THREAD

**Issue by vincentwinkel** [magento/magento2#6807]
### Preconditions

1. Magento CE 2.0.9 without sample data is installed
2. Also tested on CE 2.0.7
### Steps to reproduce

1. In backend, go to Sales > Orders
2. Choose an order (not shipped I guess) with at least one address (billing or shipping) containing the "region" field set
3. Edit this address (changing fields or not doesn't matter)
4. Save
### Expected result

1. The address must be correctly set, with the "region" field
### Actual result

1. The "region" field disappears. But if you edit again, the select is correctly set on the good value, because the "region_id" field still exists, instead of the "region" field which is empty
   ![result](http://img4.hostingpics.net/pics/233909ScreenShot20160929at164413.png)

**Comment by olysenko** [comment]
Hi,
this issue duplicates  [#4000](https://github.com/magento/magento2/issues/4000). Fix was delivered into [develop ](https://github.com/magento/magento2/tree/develop) branch.
