### ISSUE TITLE
Payment method filter by Specific Countries doesn't work

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6813]
Magento 2.2.0-dev
### Preconditions
1. Customer is created
2. Braintree payment method is enabled (with test credentials)
3. Braintree payment method is available only for USA 
   (Payment from Applicable Countrie -> Specific Countries,
   Payment from Specific Countries -> [United States])
### Steps to reproduce 1

1. Customer has only one address USA
2. Add at least one product to the shopping cart
3. Go to checkout
4. Create a new Ukraine  address and set it as shipping address
5. Choose shipping method and go to the next step
### Expected result

1. Braintree payment method is available
2. "My billing and shipping address are the same" checkbox is unchecked and disabled (or hidden)
3. Only new address should be entered
4. Only USA is available in country dropdown
### Actual result

1. "My billing and shipping address are the same" is available (or even checked)
2. It's possible to click "Place order" button with selected Ukrainian address

---
### Steps to reproduce 2

1. Customer has only one address USA
2. Add at least one product to the shopping cart 
3. Go to checkout
4. Choose existing USA address as shipping address
5. Choose shipping method and go to the next step
6. Choose Braintree payment method
7. Uncheck "My billing and shipping address are the same" checkbox
### Expected result

1. Only USA is available in country dropdown
### Actual result

1. A list of all countries is available in country dropdown

---
### Steps to reproduce 3

1. Customer has only one address Ukraine
2. Add at least one product to the shopping cart
3. Go to checkout
4. Choose the Ukrainian address as shipping address
5. Choose shipping method and go to the next step
### Expected result

1. Braintree payment method is available
2. "My billing and shipping address are the same" checkbox is unchecked and disabled (or hidden)
3. Only new address should be entered
4. Only USA is available in country dropdown
### Actual result

1. Braintree payment method is not available

---

The issue is not related to Braintree only, it was taken as example.

**Comment by alena-marchenko** [comment]
Hi @ytorbyk 

By default, "Payment from Specific Countries" option works based on shipping address. If you want "Payment from Specific Countries" option  to work based on billing address, there is a work around - set "Display Billing Address On" option to "Payment Page" at Stores > Configuration > Sales > Checkout > Checkout Options.
Please inform us if it solves your issue.

**Comment by alena-marchenko** [comment]
Hi @ytorbyk 

We are closing this issue because it hasn’t been updated in more than two weeks. If the issue still persists, please create a new GitHub issue report.

**Comment by YevSent** [comment]
Hi, @ytorbyk, sorry, I hadn't enough time to give you the complete answer to your question on MageConf.  So, I want to clarify some moments, which I said before.

On the develop branch, payment method uses billing address for country restriction checks [CountryProvider](https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Model/Checks/CanUseForCountry/CountryProvider.php#L34), but Magento 2.1.2 still uses shipping address (that's what @alena-marchenko had in mind), it should be fixed in Magento 2.1.3.

"Display Billing Address On" option is available only on the develop branch and, unfortunately, I can't provide any estimate when it will be available for 2.1.x versions.
