### ISSUE TITLE
wysiwyg Editor problem

### ISSUE THREAD

**Issue by karthigesh** [magento/magento2#6815]
I have installed the magento 2.1.1
It has one issue.

The main issue is if i open a page and the add any widget or image, then the toggle editor is not working it remains in the text editor and not working on the toggle funcitonality.
This causes me to save and go back to the page list and then reopen the page each time. It is annoying as it should not happen, because for a simple change also i have to go back and then reedit the page. Any suggestion to solve this issue is welcome please help on this issus

**Comment by hostep** [comment]
Related: https://github.com/magento/magento2/issues/4828

**Comment by veloraven** [comment]
@karthigesh thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by SerhiyShkolyarenko** [comment]
Fix is delivered to the develop branch. Closing the issue.
Issues for backporting to 2.0.x and 2.1.x branches are MAGETWO-59691 and MAGETWO-59688 correspondingly.

**Comment by royvanos** [comment]
This is still an issue in Magento 2.1.5

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-68903
