### ISSUE TITLE
PageCache gives error "Uncaught TypeError: element.prop is not a function" when there is an iframe

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#6818]
### Preconditions
1. Magento 2.1.0
2. PHP 7.0.11
### Steps to reproduce

1. Install Magento 2.1.0 with module Livechat from https://github.com/livechat/magento-livechat
2. Enable module Livechat: bin/magent module:enable LiveChat_LiveChat
3. Clear cache: bin/magento c:f
4. Go to homepage
### Expected result

1. No JavaScript error
### Actual result
1. JavaScript error: Uncaught TypeError: element.prop is not a function
   ![screen shot 2016-09-30 at 14 03 42](https://cloud.githubusercontent.com/assets/17834386/18991115/c6e98bd4-8716-11e6-9da4-203778d1e25e.png)

**Comment by PascalBrouwers** [comment]
The fix is actually pretty easy.

Change line 40 of page-cache.js
`.prop('href', element.prop('src'))`
To:
`.prop('href', $(element).prop('src'))`

But I see it is already fixed 2.1.1

**Comment by devhn** [comment]
@PascalBrouwers thanks, we applied this fix also within the page-cache.js

**Comment by Tristan-N** [comment]
@devhn @PascalBrouwers 
How come the original file is not fixed yet? I fixed this, last monday I updated to Magento 2.1.3 (from 2.1.2) and now have to apply this fix again. 
I use composer to update, so it can be found in the vendor folder.

**Comment by PascalBrouwers** [comment]
@Tristan-N I was surprised that my 2.1.2 also still has this issue, didn't check 2.1.3 yet.

**Comment by Tristan-N** [comment]
@PascalBrouwers I did too, but didn't pay any attention and just fixed it again, until the update to 2.1.3. It's that simple, so I was a bit surprised too.

**Comment by PascalBrouwers** [comment]
The weirdest thing is: they did fix it in the develop branch: https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js

**Comment by PascalBrouwers** [comment]
@veloraven Can you make sure this get's into the next release?
It was missed in this release as you can see: https://github.com/magento/magento2/blob/2.1.3/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js

**Comment by erfanimani** [comment]
It's still happening on 2.14..

**Comment by petterkj** [comment]
Also happening in 2.1.5.

Hint for fix?  https://mage2.pro/t/topic/999/2

**Comment by Tristan-N** [comment]
@petterkj Magento 2.1.5 doesn't contains any features or patches. It's only to update alle copyright files to the correct year, so this isn't surprising. 

http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.5CE.html

> This release updates the copyright date in every file. It does not contain any functional changes or security improvements. Isolating these changes in a single release is intended to simplify future updates and developer workflow.

**Comment by brendanmckeown** [comment]
When will this fix be included in a release?

**Comment by erfanimani** [comment]
Apparently Magento 2.2 will contain all fixes currently in the develop
branch.

**Comment by shuaiZend** [comment]
It's still happening on 2.1.6

**Comment by PieterCappelle** [comment]
8months and still not yet in 2.1.7. Insane.

**Comment by veloraven** [comment]
@PieterCappelle could you please confirm that you use clear Magento 2.1.7 install and the latest version of the Magento LiveChat Module?
Could you also specify which environment do you use? Like OS, web-server, PHP, MySQL version.
We were not able to reproduce this issue, so some additional information is required: maybe some specific environment, or some additional steps.

**Comment by PieterCappelle** [comment]
The problem is not related to LiveChat, the problem is related to iframes in HTML. See www.sanimarkt.be, is 2.1.7. See the console. 

Error is triggered because the chat integration.

**Comment by korostii** [comment]
@veloraven, the issue appears whenever you have an iframe on the page. 
There is no doubt about its existence, plenty of people here have experienced it.

FYI I believe the two fixes that were implemented in scope of the following two PRs cover the issue completely:
https://github.com/magento/magento2/pull/7914
https://github.com/magento/magento2/pull/8005

As far as I understand those just need to be merged into 2.1-develop and put into the next release.
Could maybe consult with @vrann to verify if this assessment is correct?

**Comment by carb0nknight** [comment]
Can also confirm this issue is in 2.1.7

**Comment by jordanbrauer** [comment]
@PieterCappelle Hilarious. 8 months to fix a simple "_typo_", yet they released an update for just copyright files in `2.1.5`? Brutal!

It's like @veloraven is a bot or something. That is the only response I see her give on every issue ever, ffs :expressionless: 

Off topic: Even funnier - with the `2.1.7` update, I am pretty sure someone screwed up the template blocks in Content > Design > Configuration. The grid is above the filters and options now :laughing:

**Comment by ghost** [comment]
Same issue with a chat that isn't installed as an extension... just added to the page via js... so obviously nothing to do with Livechat module.

I can't believe it hasn't been fixed when the the fixed code has been volunteered. Things like this are putting me off getting enterprise, what good would 24/7 support be if it's this bad?

**Comment by ghost** [comment]
@xAvarice 
Yep agree.

1. Find bug in production
2. Go to Github to report it
3. Find it was reported 12 months ago
4. Bug acknowledged and "fixed" 12 months ago
5. Apply fix manually

Things like the [devbox not working](https://github.com/magento/magento2devbox-web/issues/79) make me feel like Magento are trying to get the Community users to either move to Enterprise or solve issues themselves.

Personally, I will no longer be recommending Magento as a solution and will be looking into alternatives such as Shopify etc.

**Comment by davidverholen** [comment]
@magento-team I see there has been done something. Can we assume, that this is fixed in 2.1.8 and 2.2?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70673

**Comment by evoratec** [comment]
Still in 2.1.8

**Comment by magento-engcom-team** [comment]
The fix will be available with 2.1.10

**Comment by pmoreno1980** [comment]
Here is the solution https://github.com/magento/magento2/blob/4cd69b8/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L40-L70 this works for me

**Comment by abhi2303237** [comment]
Hi All,

Can any one of you help me to analyse the impact of this type ERROR in magento application ?

Thanks,
Abhi

**Comment by udayakumar-ziffity** [comment]
> Can also confirm this issue is in 2.1.7

This issue is still in Magento EE 2.1.9 also.
