### ISSUE TITLE
How I can create a link to page from template?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6824]
Page: `site.com/my-custom-page`.
Template: `module-customer/view/frontend/templates/form/register.phtml`.

**Comment by veloraven** [comment]
@springimport thank you for your question.
However, the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
