### ISSUE TITLE
Cannot check out when browser Autofill is enabled

### ISSUE THREAD

**Issue by melindash** [magento/magento2#6826]
When form Autofill is enabled, the email address field on the onepage checkout is mistaken for a username field.  Even if you replace it with the proper email address, it is autofilled again after you submit your details to proceed to the payment section.  The Place Order button ceases to function and there is no alert displayed to the user in either the document or the console.
### Preconditions

1. Magento 2.1 
2.  Safari or Chrome
3. Autofill enabled (checkout email field must be autofilled)
### Steps to reproduce

1. Enable Autofill
2. check out as guest
3. ensure that the email field on the checkout page is autofilled with an invalid email address (my autofill manager was attempting to enter my admin username there, say 'admin123')
4. Erase 'admin123' and enter a proper email address.  Fill out the rest of the checkout form and proceed to the payment section.
5. Select a payment method and click place order.
### Expected result

1. The order should be submitted, or at least provide a reason why nothing is happening.
### Actual result

1. There is no console error, but nothing happens when you click Place Order.  If you click back to the shipping section you'll see Autofill has replaced your valid email address with 'admin123' again.

I have reproduced this on Mac (Safari) and Windows (chrome).  Issue ceases when autofill is disabled.

**Comment by SerhiyShkolyarenko** [comment]
@melindash thank you for reporting!
Please explain which autofilling way you use. Do you use autofilling for email only? My Chromium autofills addresses only, so I had to enter my email manually. Using "Autofill" extension v 6.12 caused some problems on address form, but order was placed successfully.

**Comment by vasilii-b** [comment]
@SerhiyShkolyarenko  I used email autofill. After pressing button to go to next step, in console was the notification that my filled in email (it was norma) is not an email.

![image](https://cloud.githubusercontent.com/assets/13456702/19890082/36fdf6ec-a041-11e6-900e-5e4f12bb04e5.png)

![image](https://cloud.githubusercontent.com/assets/13456702/19890096/47167220-a041-11e6-8a7c-1d717ae6e2da.png)

**Comment by melindash** [comment]
Sorry for the delay.
@SerhiyShkolyarenko 
I used Chrome's default Autofill, complete with email and address (and usernames passwords).  Safari's autofill had the same behavior.

We had no console messages - only after going back to edit the billing information did I realize that the email field's value had been replaced by my admin username.  Reentering it did not resolve - I had to disable autofill or the email value would be replaced every time I moved on to the payment step.

**Comment by hansvanl** [comment]
I was able to reproduce this issue. Would love to have this fixed. This is very confusing for customers.

**Comment by joshuadegier** [comment]
I can also confirm this is an issue in Magento2, issue occures using OSx with Safari (different versions)

**Comment by kickmowee** [comment]
I can confirm this also on a site i am working on right now.

**Comment by twistedatrocity** [comment]
Shipping quotes (ajax doesn't fire) do not work either if address is autofilled by Chrome. Magento 2.1.6

**Comment by speedupmate** [comment]
this is related to https://github.com/knockout/knockout/issues/1949 issues in knockoutjs itself 

solution is to add data-binding valueUpdate: 'blur' or patch the knockoutjs to listen on blur events also . However to do that in magento2 one must override all form element templates

**Comment by WillWoolley** [comment]
Same issue here using 2.1.7 and Chrome. Took me ages to figure out!! Ca we somehow override the field to turn autocomplete off??

**Comment by skynixukraine** [comment]
Hello,
I confirm, the issue still exists, and it is a blocking issue. It makes impossible to use ecommerce solution where Place Order button does not work.

**Comment by joshuadegier** [comment]
@skynixukraine it's a non-blocking issue, since the issue only occurs for users that have logged in to the admin panel of your webshop(s). For regular visitors of the website, this doesn't occur (luckily).

**Comment by magento-engcom-team** [comment]
@melindash, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by antondkv** [comment]
Confirm 2.3.0

**Comment by fj-sfd** [comment]
I am facing same issue on Magento ver. 2.3.3

when you have multiple addresses saved in Google Chrome, if one or more fields are having similar values like in Address1, if FirstName, LastName etc is same as in Address2

1. Using default Magento Checkout.
2. tried with only Cash On Delivery method.
3. disabled all custom and 3rd-party modules, clear necessary folders, compile
_but still same._

**Comment by amenk** [comment]
As said before (https://github.com/magento/magento2/issues/6826#issuecomment-331636886) this only applies to customers which logged in to the admin panel before.

Still it is super annoying during development and for the merchant testing. A merchant seeing the place order button not working will angrily call their agency and loose trust in the Magento platform.

Can this be reopened?

I think the steps to reproduce miss the step 0. successfully login to admin panel

**Comment by insaneCreations** [comment]
We still have this issue on 2.3.4, and in our case the customer have the problem as well.. so if you Autofill the fields and afterwards want to change the country, the system echo's that country is required.. which is strange because it has value..

![Schermafbeelding-2020-06-25-om-09 59 58](https://user-images.githubusercontent.com/25158886/85681359-7ffb1880-b6cb-11ea-881a-4c53adbc5063.jpg)

We are using the IWD OneStepCheckout, but if i disable this module.. the problem still exists

**Comment by GuiltyNL** [comment]
We are experiencing also issues. We have sometimes issues with guest checkouts. When firstname and lastname fields are autofilled,  Magento says that he needs firstname and lastname to proceed.

Customer has to remove the prefilled fields and fill them out by hand to fix it.


We have alike issues when we use a postcode validator tool. When the customer fills out the postcode and house number, the tool fills out the streetname and the city. The customer will sometimes get the error that city and country needs to be filled out, but they already are.

**Comment by achatpc** [comment]
Same issue. Any update about please?

Thank you.

**Comment by usman786cs** [comment]
I'm facing same issue on one step checkout.
Did anyone fix it?
Please share your suggestions for the fix.
Thanks
