### ISSUE TITLE
JavaScript Bundling breaks JS paths on 2.1.1

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#6828]
JavaScript Bundling breaks JS paths on 2.1.1 without Merging and Minification turned on,.. but Merging and Minification are working as intended.

![image 2016-09-30 16 14 55](https://cloud.githubusercontent.com/assets/8983883/19010243/b3d759b4-8742-11e6-828f-19a5c465d27f.png)
![image 2016-09-30 19 14 08](https://cloud.githubusercontent.com/assets/8983883/19010244/b3e2693a-8742-11e6-9384-c00a6144874f.png)

**Comment by veloraven** [comment]
@devdesco-ceo thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
