### ISSUE TITLE
Magento 2.1.1 (and 2.1.0) Web Installer stuck at "Installing Database Schema"

### ISSUE THREAD

**Issue by frostshoxx** [magento/magento2#6829]
### Preconditions

1. Magento version 2.1.1 (also tried 2.1.0)
2. PHP 7.0.11
3. MySQL 5.6
### Steps to reproduce

1. Download Magento 2 CE from the main website
2. Extract the compressed file on the public_html folder
3. Run the install via the web URL
4. Go through the steps of system req verification, DB setup, admin URL, etc.
5. Start the installer
### Expected result

1. It's supposed to just install Magento system.
### Actual result

1. It stuck at installing database schema
   ![magento2issue](https://cloud.githubusercontent.com/assets/567851/19010405/80e319a2-874d-11e6-8c25-73288fed8cd9.PNG)
2. I then try to rerun the installer again, but got the error message shown on the log file as below.

Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'helloworld_magedb211.core_config_data' doesn't exist, query was: SELECT `main_table`.`config_id`, `main_table`.`path`, `main_table`.`value` FROM `core_config_data` AS `main_table` WHERE (`scope` = 'default') in /home/helloworldety/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /home/helloworldety/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/helloworldety/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /home/helloworldety/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/helloworldety/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /home/helloworldety/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(452): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /home/helloworldety/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(507): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /home/helloworldety/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(772): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(668): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(572): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /home/helloworldety/public_html/vendor/magento/framework/Data/Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#13 /home/helloworldety/public_html/vendor/magento/module-store/Model/Config/Reader/DefaultReader.php(65): Magento\Framework\Data\Collection->getIterator()
#14 /home/helloworldety/public_html/vendor/magento/framework/App/Config/ScopePool.php(112): Magento\Store\Model\Config\Reader\DefaultReader->read()
#15 /home/helloworldety/public_html/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('default', NULL)
#16 /home/helloworldety/public_html/vendor/magento/framework/App/Config.php(58): Magento\Framework\App\Config->getValue('web/secure/use_...', 'default', NULL)
#17 /home/helloworldety/public_html/vendor/magento/module-store/Model/HeaderProvider/Hsts.php(48): Magento\Framework\App\Config->isSetFlag('web/secure/use_...')
#18 /home/helloworldety/public_html/vendor/magento/framework/App/Response/HeaderManager.php(41): Magento\Store\Model\HeaderProvider\Hsts->canApply()
#19 /home/helloworldety/public_html/vendor/magento/framework/Interception/Interceptor.php(123): Magento\Framework\App\Response\HeaderManager->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#20 /home/helloworldety/public_html/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#21 /home/helloworldety/public_html/pub/errors/503.php(12): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#22 /home/helloworldety/public_html/vendor/magento/framework/App/Http.php(261): require('/home/helloworlde...')
#23 /home/helloworldety/public_html/vendor/magento/framework/App/Http.php(157): Magento\Framework\App\Http->handleBootstrapErrors(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#24 /home/helloworldety/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#25 /home/helloworldety/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#26 {main} [] []

**Comment by stamster** [comment]
Try to increase memory_limit to 768MB, and max_execution_time to 600s.
Before doing that, make sure your DB is cleared (i.e. all tables dropped).

**Comment by frostshoxx** [comment]
Hi there.

I made sure that my DB is cleared (also try a new DB altogether). I also set memory_limit to 768MB and max_exceution_time to 600 (on .htaccess and also php.ini files).

I still got the same issue where it's stuck at installing database schema.

Are there anything else that I could try?

Thank you,

**Comment by frostshoxx** [comment]
I just checked with my host provider. Turned out the memory limit configuration has to be done outside the scope of my access. I am able to install Magento 2.1.1 now.

Thank you,
