### ISSUE TITLE
Double URL Suffix 

### ISSUE THREAD

**Issue by jtw372** [magento/magento2#6830]
CE Magento 2.1.1 on Ubuntu 16.04.1 x64  PHP 7.0 (LEMP stack installed by ServerPilot)

Product URLs are generating a double suffix.   Example here:
http://192.2xx.xxx.xx/gbase-8023350515**.htm.htm**
The URL key for this product is gbase-8023350515

I have no suffix checked for category and have it checked for product--changed the product suffix to .htm.  I have also enabled auto rewrites.

This issue was happening before and to make sure there were no extension or theme interference I did a completely new re-install and then imported using the default theme.  

-I have tried to edit the products, save, reindex, and flush cache, nothing seems to work.

**Comment by veloraven** [comment]
@jtw372 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
