### ISSUE TITLE
Template path hints: Small feature request

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#684]
I see that in Magento 2 (opposed to 1) the html elements generated by the template path hints have their own classes and can be easily identified in javascript.  
This goes nicely with the idea I have.  
How about, when the template path hints are activated, to have a small toolbar (or button or whatever) somewhere on the top or bottom of the page that will allow the developers to show/hide certain elements of the template path hints.  
For example calling `jQuery('.debugging-hint-template-file').hide() / show()` will hide/show the template names. The same can be done to hide the block class names using `.debugging-hint-block-class`. or the dotted borders can be hidden by `jQuery('.debugging-hints').css({border:'none'});`.  
Right now the processes that involve template path hints are slow.  
First I need to enable the path hints, identify the class or template, do my modifications, see if they appear in the page, then disable the path hints to see how it looks without them, then enable them again if needed.  

I know that I can create buttons on my browsers with the actions I need but a built in feature would be better.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30427

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Template-path-hints-Small-feature-request/idi-p/47142).
