### ISSUE TITLE
javascript randomly fails to load on 2.1.1

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#6844]
### Preconditions

1. 2.1.1  
2. utilizing luma
3. centos
### Steps to reproduce

1. install CE 2.1.1 
2. utilize luma theme
3. utilize cache
### Expected result

1. javascript should load 100% of the time. 
### Actual result

1. At random times the javascript doesn't load

**Comment by veloraven** [comment]
@dmcmillin thank you for your feedback.
Do you use any extensions?
Are there any errors?
Have you done static deploy? 
_php bin/magento setup:static-content:deploy_

**Comment by devdesco-ceo** [comment]
JS bundling is turned on?
Web Server connection throttling is active?

**Comment by dmcmillin** [comment]
It doesn't display any errors besides that javascript elements were not loaded. 
yes, I have done setup:static-content:deploy
I have never enabled it, I am running in developer mode. Not production.

**Comment by devdesco-ceo** [comment]
The M2 is the beast the World did not see before... But it is way better than M1...
Being honest with you, that's the best eCommerce solution to date, but you need to become a Pro with it... then whole world of eCommerce development is kneeling before you. Good luck!

**Comment by veloraven** [comment]
@dmcmillin can you please provide information about your system? Like operating system used, versions of PHP, MySQL and web server.
And I have to ask again if you use any extensions.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
