### ISSUE TITLE
Creating a New Product Makes Existing Products Not Found

### ISSUE THREAD

**Issue by epadmin** [magento/magento2#6845]
### Preconditions

1. using Magento 2.1.1
2. Every time I add a new product, my existing products disappear for a while and a " We're sorry, an error has occurred while generating this email." message appears where tthe featured products should be shown.
3.  I have the cache settings all turned off.  
4.  I have tried reindexing and it does not solve the problem.  
5. You can tell it still knows the products are there because the number of products for the various filter categories on the LH side still show the number of products
6. The products also do not show up in their related categories.
### Steps to reproduce
1. Create a new product or update an existing product
### Expected result

1. When a new product is created or product is updated, the updates should be displayed
### Actual result

1. Home page featured products no longer display after adding new product or editing existing.
   ![disappearing](https://cloud.githubusercontent.com/assets/20366338/19026109/9574bede-88e7-11e6-862c-d74d4dc278ef.png)

2 Product filters see that the products exist but will not display them
![filter](https://cloud.githubusercontent.com/assets/20366338/19026165/1ea70c20-88e8-11e6-9ab0-bc9f058a8ef6.png)
1. Reindexing does not work to fix the issue.   Waiting, sometimes hours or overnight, seems to be the only thing that fixes it.

**Comment by veloraven** [comment]
@epadmin thank you for your report.
Could you please provide more detailed steps on:
- how you add a new product;
- how do you add 'featured products'.
  Please describe your actions step by step.
  Please also provide information about your environment: operating system, versions of PHP, MySQL and web server.

**Comment by epadmin** [comment]
I wonder if this is the same problem or related to https://github.com/magento/magento2/issues/6799

-------- Original Message --------
Subject: Re: [magento/magento2] Creating a New Product Makes Existing
Products Not Found (#6845)

**Comment by epadmin** [comment]
I tried attaching a .swf video file to show the process but github won't take it.  I can email directly if it would help.   Essentially products>catalog click Add product
Fill out the info hit save
Go to add configurations section and click there, select the attributes, go through that process which takes you back to parent product page and hit save
Change stock status to in stock hit save
Go to each child product, change stock status back to instock and hit save
(note in video I did not add stock quantities but I normally do - which reminds me why doesn't Magento automatically set the stock status to In Stock if the stock QTY is above the threshold you set for out of stock in the admin section?)
After creating/updating a product, the email error message shows up.

I am using a slider to randomly display up to 6 products in the featured product section from Category-id=3

Server: Localhost via UNIX socket
Software: Percona Server
Software version: 5.6.28-76.1 - Percona Server (GPL), Release 76.1, Revision 5759e76
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)
Apache
Database client version: libmysql - 5.5.45-37.4
php 5.6.20

**Comment by veloraven** [comment]
@epadmin do you mean you use some side extension for 'featured products'?

**Comment by epadmin** [comment]
I think I _might_ have figured it out.   When I created the original product and added configurations, they were all set to the DEFAULT attribute set.   I then updated the parent product to a different attribute set expecting the children to automatically be updated but they were still set to default.   I have updated the attribute set of the child products to match the parent product and now everything seems to be showing.As a side note, somehow the children keep disassociating from the parent product.   I noticed that under the configurations section, the Add Products Manually link is only visible if there are existing configurations.   Is this on the list for known bugs?   The add products manually link under the configurations section should always be visible.   A store owner may initially set up products individually and later decide they want them grouped under a parent.I will let you know if the problem comes back or if this is a real fix.   Thanks!

-------- Original Message --------
Subject: Re: [magento/magento2] Creating a New Product Makes Existing
Products Not Found (#6845)

**Comment by epadmin** [comment]
Ok, so that was a short lived victory.   I don't know what it is, but if I disable the configurable product that has been causing the problem everything else shows up but if I enable it they all disappear again.   I have gone over the settings for the configurable product and all looks good, I have checked the simple child products and can't see anything wrong.   It has something to do with being a configurable product just need to figure out what.

-------- Original Message --------
Subject: Re: [magento/magento2] Creating a New Product Makes Existing
Products Not Found (#6845)

**Comment by tobias-forkel** [comment]
I had the same message `We're sorry, an error has occurred while generating this email.` on our production environment and was able to fix the problem by disabling SampleData in `app/etc/config.php` > `'Magento_SampleData' => 0`.

Or simply:

`bin/magento module:disable Magento_SampleData`

More about SampleData in production mode you can find on http://devdocs.magento.com/guides/v2.1/install-gde/install/sample-data-after-composer.html

**Comment by epadmin** [comment]
@tobias awesome thanks for the info.  I will try it and see if it works for us.  Is there a way to do this from the admin panel?

-------- Original Message --------
Subject: Re: [magento/magento2] Creating a New Product Makes Existing
Products Not Found (#6845)

**Comment by veloraven** [comment]
@epadmin is this issue still actual?
If you use some external extension for 'featured products' please explain why do you think it to be an issue on Magento side and not on extension side?

**Comment by epadmin** [comment]
it is not an extension.   it is the built magento slider pulling from a category to display certain products.    Someone said they solved the problem by removing all the sample data.  I have not tried that yet.  I updated to the new release and it immediately fixed the problem, but 10 hours later when I went back it was doing it again.  I am giving up on M2 for now and currently rebuilding everything on M1

-------- Original Message --------
Subject: Re: [magento/magento2] Creating a New Product Makes Existing
Products Not Found (#6845)

**Comment by tobias-forkel** [comment]
Hi @epadmin 

> Someone said they solved the problem by removing all the sample data.

I just disabled the module SampleData in `app/etc/config.php` > `'Magento_SampleData' => 0`. I didn't remove all sample data which was created before. You should try it. It will take you just 2 minutes.

**Comment by oleg-onufer** [comment]
Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?
