### ISSUE TITLE
"Credit memo" button is available for invoice which already is refunded

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6848]
### Preconditions
1. Magento 2.2.0-dev with sample data
2. Braintree payment method configured and enabled (with sandbox credentials)
3. "Authorize only" payment action is set for Braintree
### Steps to reproduce
1. Log in
2. Add to the shopping cart at lead two products
3. Go to checkout and place order with Braintree payment method
4. Go to admin panel
5. Create two separate invoices (partial invoices) for the order
6. Choose the first invoice and create a credit memo for it
7. Open the first invoice again
### Expected result
1. There mustn't be a "Credit memo" button for the invoice (since the invoice is already refunded)
### Actual result
1. There is a "Credit memo" button on the invoice which already is refunded

It could be confusing for merchants.

**Comment by ytorbyk** [comment]
Here is pull request for the issue https://github.com/magento/magento2/pull/6902

**Comment by viktym** [comment]
Hi @ytorbyk 
I’m closing this issue because it is a duplicate https://github.com/magento/magento2/issues/6849.
Thanks for the feedback.

**Comment by ytorbyk** [comment]
@viktym  This isn't a duplicate. The cause of these two issues is the same, but still they are separate issues.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69915

**Comment by ytorbyk** [comment]
Thank you!
Can you please reopen this ticker as well?

**Comment by korostii** [comment]
That @magento-team's comment seems to be automatic. The bot is probably walking through all the internal ticket references it has, no matter the status.
