### ISSUE TITLE
Using the WYSIWYG removes URL in the description

### ISSUE THREAD

**Issue by SahakTadevosyan** [magento/magento2#6851]
We are having a weird issue with the WYSIWYG editor when editing products.
Our magento version is Magento CE 2.1.0.

If we select the "Show / Hide Editor" it will change our default code.

It deletes the value in the "media url" and we are left with a broken image link.

Expected result:
 image src="{{media url="wysiwyg/Products/AudioQuest/audioquest.jpg"}}" 

Actual result:
image src="{{media url=" 

Can someone assist us on this issue? It seems odd, but we can replicate it every time we use the editor.

Thanks.

**Comment by veloraven** [comment]
@SahakTadevosyan thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by SahakTadevosyan** [comment]
@veloraven Thank you for your response. I updated the issue how you mentioned.

**Comment by miakusha** [comment]
Hi @SahakTadevosyan its issue was reported earlier #5811 .
Closed as duplicate

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435
