### ISSUE TITLE
crypt module issue

### ISSUE THREAD

**Issue by naveen433** [magento/magento2#6853]
### Preconditions

1. PHP 7.0.11
2. Mysql 5.7.15
3. httpd 2.4.6
### Steps to reproduce

1. [ERROR] Exception: Warning: mcrypt_module_open(): Could not open encryption module in /var/www/html/magento2/lib/internal/Magento/Framework/Encryption/Crypt.php on line 54 in /var/www/html/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
2. #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'mcrypt_module_o...', '/var/www/html/m...', 54, Array)
3. #1 /var/www/html/magento2/lib/internal/Magento/Framework/Encryption/Crypt.php(54): mcrypt_module_open('blowfish', '', 'ecb', '')
4. #2 /var/www/html/magento2/lib/internal/Magento/Framework/Encryption/Encryptor.php(401): Magento\Framework\Encryption\Crypt->__construct('268a5343c363856...', 'blowfish', 'ecb', false)
   5.#3 /var/www/html/magento2/lib/internal/Magento/Framework/Encryption/Encryptor.php(313): Magento\Framework\Encryption\Encryptor->getCrypt('268a5343c363856...', 0, false)
   6.#4 /var/www/html/magento2/app/code/Magento/Config/Model/Config/Backend/Encrypted.php(109): Magento\Framework\Encryption\Encryptor->decrypt('PayPal')
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@naveen433 please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
