### ISSUE TITLE
[2.1.1CE] C# SOAP/WSDL - Cannot Generate WSDL based Objects in Visual Studio

### ISSUE THREAD

**Issue by MarkB42** [magento/magento2#6854]
The protected SOAP endpoints prevent Visual Studio from generating the necessary intermediate files to write software against
### Preconditions
1. Mage 2.1.1
2. PHP 7.0.11
3. Visual Studio 2015 CE
### Steps to reproduce
1.  Enable "Allow Anonymous Guest Access" against the store
2.  Create an Integration account with "Resource Access: All"
3.  Open Visual Studio -> Add Service Reference.
4.  Use url http://[mystore]/soap/default?wsdl=1&services=salesOrderRepositoryV1
### Expected result
1. The same as using an allowed URL IE http://[mystore]/soap/default?wsdl=1&services=catalogProductAttributeGroupRepositoryV1
### Actual result

There was an error downloading 'http://[mystore]/soap/default?wsdl=1&services=salesOrderRepositoryV1/$metadata'.
The request failed with HTTP status 400: Bad Request.
Metadata contains a reference that cannot be resolved: 'http://[mystore]/soap/default?wsdl=1&services=salesOrderRepositoryV1'.
The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was ''.
The remote server returned an error: (401) Unauthorized.
If the service is defined in the current solution, try building the solution and adding the service reference again.
### Other Things I have tried
1. Using the WSDL.exe tool directly and supplying a the username and AccessToken for the Integration user account and it returns a 401 error
2. Adding a Web Reference instead of a Service Reference and supplying the login credentials in the url IE
   http://[ServiceUserAccount]:[AccessToken]@[mystore]/soap/default?wsdl=1&services=catalogProductAttributeTypesListV1    returns a 401
3. Doing the above in a web browser returns a 401 with no access to %resource page

**Comment by manhao-chen** [comment]
i'm experiencing the same issue, REALLY need to generate the necessary intermediate files to write a software pos integration

i was building an integration on 2.0.2 using soap  c#, now i just updated to 2.1.2 all the soap modules are gone, i've enabled the allow anonymous web api thing, 

i got 
- integrationAdminTokenServiceV1
- storeStoreRepositoryV1
- catalogInventoryStockRegistryV1
- catalogProductRepositoryV1

still missing 
-     customerCustomerRepositoryV1
-     salesOrderRepositoryV1
-     salesOrderManagementV1
-     salesInvoiceRepositoryV1
-     salesInvoiceCommentRepositoryV1
-     salesCreditmemoRepositoryV1
-     salesCreditmemoCommentRepositoryV1

how would you expect anyone to do a full soap integration without the full wsdl structure???

**Comment by ilopez** [comment]
Here is what I have observed. Visual Studio 2015 Professional with the Web Reference Wizard will not have a way to inject the Authorization Bearer Token. Will continue to investigate a workaround for Visual Studio.

VS 2015 Request for WSDL:

```
GET http://DOMAIN/soap/default?wsdl&services=backendModuleServiceV1 HTTP/1.1
Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, */*
Accept-Language: en-US
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 10.0; WOW64; Trident/7.0)
Host: DOMAIN
Connection: Keep-Alive

HTTP/1.1 401 Unauthorized
```

Chrome Browser REST Console Request

```
GET http://DOMAIN/soap/default?wsdl&services=backendModuleServiceV1 HTTP/1.1
Host: DOMAIN
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Authorization: Bearer KEY
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

HTTP/1.1 200 OK

```

Edit: Looks like the best way is to use CURL/Rest Console/SOAPUI to generate the WSDL response from Magento, save the contents to a .WSDL file, and use the Add Service Reference Wizard to generate the clients.

Then follow the guidelines in the link below, to add in the Authorization Bearer Token to the SOAP Requests. http://stackoverflow.com/questions/35481515/how-do-i-configure-the-token-based-authentication-of-magento-2-0-soap-api-object

Then most importantly, if you need to connect to different WebServices (different Stores), manipulating the Namespace in the SOAP Request, Endpoint URL will be difficult. I may find another solution, but keeping all of SOAP/Integration code in the same project seemed to work best.  Your mileage may vary.

**Comment by magento-engcom-team** [comment]
@MarkB42 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
The GitHub issue tracker is intended for Magento Core technical issues only.
