### ISSUE TITLE
Create order via backend doesn't work after using NL translation for order-header

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#6855]
1. Magento version 2.1.0 and 2.1.1
2. PHP 7.0.11
### Steps to reproduce
1. Install Magento with your own language (e.g. nl_NL) and make sure your account is in your language (nl_NL)
2. Add a translate csv for 'order-header' for your own language (nl_NL.csv):
   order-header,orderkop,module,Magento_Sales
3. Run static content for your own language: setup:static-content:deploy nl_NL
### Expected result
1. Create an order in the backend of magento. And select 'Create New Customer'. (Or when you already have a user select a user).
2. You should see the next step 'Please select a store'.
### Actual result
1. Nothing happens because the id 'order-header' gets translated. For an explanation see loadAreaResponseHandler() in Magento_Sales/view/adminhtml/web/order/create/scripts.js

**Comment by veloraven** [comment]
I’m closing this issue because it is a duplicate. Please reopen this issue as needed.

**Comment by PascalBrouwers** [comment]
Would be nice if you would mention the duplicate ;)

**Comment by PascalBrouwers** [comment]
@veloraven what is the duplicate issue?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66428

**Comment by coachdesign** [comment]
It does not look like a duplicate, but a different issue
