### ISSUE TITLE
Shipping Methods show rate 0

### ISSUE THREAD

**Issue by 100php** [magento/magento2#6857]
Magento Version :: 2.1.1
Sample Database 

Admin Shipping methods setting ::

![image](https://cloud.githubusercontent.com/assets/8121471/19039547/16f35ea0-899e-11e6-815a-3f495b933fc6.png)
1. Flat rate has price and handling fee both
2. Free shipping is also enabled 
3. All other methods are disabled 

The API we use in checkout to fetch shipping methods is "rest/V1/carts/6/estimate-shipping-methods" 
The response of the API is as below:

![image](https://cloud.githubusercontent.com/assets/8121471/19039641/6aa05864-899e-11e6-83a2-1b1ff708df76.png)

We are getting Flat rate price as Rs.0

Expected response ::

For the existing cart having 2 items we must get Rs.100 as Flat rate price including handling fees.

The same is case on frontend (checkout) shipping is showing Rs.0 for flat rate and free shipping.

It was working fine in Magento 2.0.7. Can anyone help me with the above issue.

**Comment by miakusha** [comment]
Hi @100php , I cannot reproduce this issue. 
Can you reproduce issue on clean Magento without any extensions?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by nahidacm** [comment]
Probably some cart price rule override the shipping cost.
Please check in:  `Admin->Marketing->Promotions->Cart Price Rules`

**Comment by dipakCrayon** [comment]
@nahidacm You are right.My issue fixed.
