### ISSUE TITLE
Prices always exclusive of tax for shipping estimates in cart

### ISSUE THREAD

**Issue by Danielc3** [magento/magento2#6859]
The estimates for shipping on the cart page are always shown excluding VAT, despite having set the cart to show shipping inclusive of tax.
### Preconditions
- Magento 2.1.0 or 2.1.1
### Steps to reproduce
1. Create a new shipping tax rule, with a 20% tax rate for the country you intend to checkout with. When creating the tax rule, creating a new product tax class named shipping and set the rule to use it.
2. Specify under Sales > Tax > Tax Class to use the new product tax class you just made.
3. Set the following:
   Price Display Settings > Display Shipping Prices = Including Tax
   Shopping Cart Display Settings > Display Shipping Prices = Including Tax.
4. Add a product to the cart, then go to the cart and look at the shipping estimates in the order summary box to the right.
### Expected result
1. I would expect to see the shipping estimates shown inclusive of tax.
### Actual result
1. Shipping estimates are shown excluding tax.

**Comment by sevos1984** [comment]
What is your Calculation Settings>Shipping Prices setting? If it is set to Including Tax price will be shown without tax. And also did you specified Tax Class for Shipping?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by parekhreena** [comment]
@sevos1984  @veloraven  i am facing this same issue and the setting under Calculation Settings>Shipping Prices  is set to "Including tax". You are requested to reopen this ticket as it is still not fixed.

**Comment by spraxis** [comment]
Same as @parekhreena. I set a 6% tax and is only being applied to the Cart Subtotal.

![shipping bug - backend](https://user-images.githubusercontent.com/17143366/34533130-a1ae97c4-f097-11e7-81e8-dcbb35840dc6.png)

![shipping bug - frontend](https://user-images.githubusercontent.com/17143366/34533135-a71672e0-f097-11e7-9754-a7f9261bb387.png)

**Comment by spraxis** [comment]
Well I missed to set the "Tax Class for Shipping". After that is working as expected.

![selection_003](https://user-images.githubusercontent.com/17143366/34573157-1fccf5f0-f152-11e7-86b5-02e69ebb06d0.png)

![selection_004](https://user-images.githubusercontent.com/17143366/34573188-31040ea8-f152-11e7-9121-673a49cdd70d.png)

**Comment by thangasujithas** [comment]
Hi,
 I am facing same problem. I have given the below configurations but now also shipping cost showed exclusive of tax in shopping cart but in checkout page it shows with tax.
Tax Class for Shipping -> Taxable goods
Calculation Settings -> Shipping Prices -> Excluding Tax
Shopping Cart Display Settings -> Display Shipping Amount -> Including Tax.
Can anyone give the solution for this.

**Comment by alias-2k** [comment]
Hi, I am facing the same problem with magento community 2.4.5 p1.
Please fix it
