### ISSUE TITLE
After upgrade to magento 2.1.1 and created another store it will display a reindexing error in Product Price index 

### ISSUE THREAD

**Issue by earlelnar** [magento/magento2#6860]
### Preconditions

1.  Enter your credentials in ssh.
2.  Login to the site using ssh.
### Steps to reproduce

1. Run this command after opening ssh
2. php bin/magento indexer:reindex
3. 
### Expected result

1.  It should display the success message of reindexing every indexes required.
### Actual result

1. [Screenshot, logs]
   php bin/magento indexer:reindex
   Design Config Grid index has been rebuilt successfully in 00:00:06
   Customer Grid index has been rebuilt successfully in 00:00:19
   Product Flat Data index has been rebuilt successfully in 00:00:28
   Category Products index has been rebuilt successfully in 00:00:33
   Product Categories index has been rebuilt successfully in 00:00:00
   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND tad_price_type.store_id = 0
   LEFT JOIN `mg2_catalog_product_entity` AS `tas_' at line 13, query was: INSERT INTO`mg2_catalog_product_index_price_bundle_idx`SELECT`e`.`entity_id`,`cg`.`customer_group_id`,`cw`.`website_id`, IF(IF(IFNULL(tas_tax_class_id.value_id, -1) > 0, tas_tax_class_id.value, tad_tax_class_id.value) IS NOT NULL, IF(IFNULL(tas_tax_class_id.value_id, -1) > 0, tas_tax_class_id.value, tad_tax_class_id.value), 0) AS`tax_class_id`, 1 AS`price_type`, IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) AS`special_price`, tp.min_price AS`tier_percent`, IF(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) IS NULL, 0, IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value)) AS`orig_price`, IF(IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL) < IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value)), IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL), IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))) AS`price`, IF(IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL) < IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value)), IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL), IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))) AS`min_price`, IF(IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL) < IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value)), IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL), IF(IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0) > 0, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) <= cwd.website_date, 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) >= cwd.website_date, 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < 100 , IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), 0)  / 100), 4), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))) AS`max_price`, IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL) AS`tier_price`, IF(tp.min_price IS NOT NULL, ROUND(IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) - (IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value) * (tp.min_price / 100)), 4), NULL) AS`base_tier`FROM`mg2_catalog_product_entity`AS`e`
   CROSS JOIN`mg2_customer_group`AS`cg`
   CROSS JOIN`mg2_store_website`AS`cw`
   INNER JOIN`mg2_store_group`AS`csg`ON csg.group_id = cw.default_group_id
   INNER JOIN`mg2_store`AS`cs`ON cs.store_id = csg.default_store_id
   INNER JOIN`mg2_catalog_product_website`AS`pw`ON pw.product_id = e.entity_id AND pw.website_id = cw.website_id
   INNER JOIN`mg2_catalog_product_index_website`AS`cwd`ON cw.website_id = cwd.website_id
   LEFT JOIN`mg2_catalog_product_index_tier_price`AS`tp`ON tp.entity_id = e.entity_id AND tp.website_id = cw.website_id AND tp.customer_group_id = cg.customer_group_id
   INNER JOIN`mg2_catalog_product_entity_int`AS`tad_status`ON tad_status.entity_id = e.entity_id AND tad_status.attribute_id = 94 AND tad_status.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_int`AS`tas_status`ON tas_status.entity_id = e.entity_id AND tas_status.attribute_id = 94 AND tas_status.store_id = cs.store_id
   LEFT JOIN`mg2_catalog_product_entity_int`AS`tad_tax_class_id`ON tad_tax_class_id.entity_id = e.entity_id AND tad_tax_class_id.attribute_id = 129 AND tad_tax_class_id.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_int`AS`tas_tax_class_id`ON tas_tax_class_id.entity_id = e.entity_id AND tas_tax_class_id.attribute_id = 129 AND tas_tax_class_id.store_id = cs.store_id
   INNER JOIN`mg2_catalog_product_entity`AS`tad_price_type`ON tad_price_type.entity_id = e.entity_id AND tad_price_type.attribute_id =  AND tad_price_type.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity`AS`tas_price_type`ON tas_price_type.entity_id = e.entity_id AND tas_price_type.attribute_id =  AND tas_price_type.store_id = cs.store_id
   LEFT JOIN`mg2_catalog_product_entity_decimal`AS`tad_price`ON tad_price.entity_id = e.entity_id AND tad_price.attribute_id = 74 AND tad_price.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_decimal`AS`tas_price`ON tas_price.entity_id = e.entity_id AND tas_price.attribute_id = 74 AND tas_price.store_id = cs.store_id
   LEFT JOIN`mg2_catalog_product_entity_decimal`AS`tad_special_price`ON tad_special_price.entity_id = e.entity_id AND tad_special_price.attribute_id = 75 AND tad_special_price.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_decimal`AS`tas_special_price`ON tas_special_price.entity_id = e.entity_id AND tas_special_price.attribute_id = 75 AND tas_special_price.store_id = cs.store_id
   LEFT JOIN`mg2_catalog_product_entity_datetime`AS`tad_special_from_date`ON tad_special_from_date.entity_id = e.entity_id AND tad_special_from_date.attribute_id = 76 AND tad_special_from_date.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_datetime`AS`tas_special_from_date`ON tas_special_from_date.entity_id = e.entity_id AND tas_special_from_date.attribute_id = 76 AND tas_special_from_date.store_id = cs.store_id
   LEFT JOIN`mg2_catalog_product_entity_datetime`AS`tad_special_to_date`ON tad_special_to_date.entity_id = e.entity_id AND tad_special_to_date.attribute_id = 77 AND tad_special_to_date.store_id = 0
   LEFT JOIN`mg2_catalog_product_entity_datetime`AS`tas_special_to_date`ON tas_special_to_date.entity_id = e.entity_id AND tas_special_to_date.attribute_id = 77 AND tas_special_to_date.store_id = cs.store_id WHERE (e.type_id='bundle') AND (IF(IFNULL(tas_status.value_id, -1) > 0, tas_status.value, tad_status.value)=1) AND (IF(IFNULL(tas_price_type.value_id, -1) > 0, tas_price_type.value, tad_price_type.value)=1) ON DUPLICATE KEY UPDATE`tax_class_id`= VALUES(`tax_class_id`),`price_type`= VALUES(`price_type`),`special_price`= VALUES(`special_price`),`tier_percent`= VALUES(`tier_percent`),`orig_price`= VALUES(`orig_price`),`price`= VALUES(`price`),`min_price`= VALUES(`min_price`),`max_price`= VALUES(`max_price`),`tier_price`= VALUES(`tier_price`),`base_tier`= VALUES(`base_tier`)
   Product EAV index has been rebuilt successfully in 00:00:30
   Stock index has been rebuilt successfully in 00:00:02
   Catalog Rule Product index has been rebuilt successfully in 00:00:00
   Catalog Product Rule index has been rebuilt successfully in 00:00:00
   Catalog Search index has been rebuilt successfully in 00:03:26

**Comment by earlelnar** [comment]
Hey guys, any Ideas? I'm really having a problem in magento 2.1.1

**Comment by veloraven** [comment]
@mazestricks thank you for you feedback.
Please update your description with steps described in issue title like upgrading from previous version (from which one?) and adding new store.
Did you try to run the same command before the upgrade and before the adding new store?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by SemtexError** [comment]
How was this resloved I'm having the same issue?

EDIT: Found it! eav_attribute price was missing for some reason. 
Check al your eav_attributes to fix this issue
