### ISSUE TITLE
When changing the product image on simple products generated in the Create Configurations wizard, both the original and new images are saved to the simple product.

### ISSUE THREAD

**Issue by mverstraete** [magento/magento2#6861]
When you create a configurable product, and use the Create Configurations wizard to generate the simple products, before saving the configurable product you have the ability to change the image on the simple products.  If you selected an image in the wizard, and then try to change it on the configurable product, both the original and the new image are saved to the simple product.
### Preconditions

1. Magento 2.1.1 CE
2. PHP 5.6
3. MySql 5.6
### Steps to reproduce

1. Create a new configurable product and use the Create Product Configurations wizard to create some simple products.
2. On step 3, apply an image to all SKUs.
3. Click Next to complete the wizard.
4. Click one of the simple product images to bring up a file selection window.  This should let you change the product image.  Select a different image.
5. Press Save on the configurable product.
### Expected result

1. The simple product whose image you changed should only have the most recently chosen image attached to it.
### Actual result

1. The simple product whose image you changed now has both the original and the newly chosen image attached to it.

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket created MAGETWO-60465

**Comment by magento-engcom-team** [comment]
@mverstraete, thank you for your report.
We've created internal ticket(s) MAGETWO-60465 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@mverstraete, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
