### ISSUE TITLE
The system has no function getShowAddressFields()

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6863]
### Steps to reproduce
1. Go to /vendor/magento/module-customer/view/frontend/templates/form/register.phtml
2. Find `<?php if ($block->getShowAddressFields()): ?>`
### Expected result
1. Function in `Magento\Customer\Block\Form\Register`
### Actual result
1. Not found.
### Additional info

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by slavvka** [comment]
This is a magic method. There's setter setShowAddressFields in \Magento\Multishipping\Controller\Checkout\Register
