### ISSUE TITLE
Products in wishlist show $0.00 price

### ISSUE THREAD

**Issue by serzhik** [magento/magento2#6866]
## Preconditions
1. Install EE 2.0.2
2. Upgrade to EE 2.1.1
   or
3. Install CE 2.0.2
4. Upgrade to CE 2.1.0
### Steps to reproduce
1. Sign in
2. Add product to wishlist
3. Go to wishlist
### Expected result
1. Products showed with price
### Actual result
1. Products showed with $0.00 value
   ![chrome_2016-10-03_20-02-35](https://cloud.githubusercontent.com/assets/2320879/19066886/3c98b43a-8a24-11e6-803f-34c70bc5df68.png)

**Comment by pobrassard** [comment]
@Serzhik This happens when you add a configurable/virtual product without selecting the options. When you add a configurable product to the cart, you never really buy the configurable product but the products associated to its options.

Try to selecting a color/size before you add them to your wishlist. You can also try adding a simple product to see if the price shows in the wishlist.

**Comment by Igloczek** [comment]
@pobrassard That's true, but we need to tell about this our clients somehow, b/c this product doesn't cost 0.00$ in any configuration.

So there are few scenarios how it should be fixed:
- disable ability to add configurable product to wishlist, without selecting all options. But it's suck, b/c we can't use simple "heart" button on category view / home page / any other products listing - not so good idea
- hide price for configurable products without selected options - quickest fix
- display price range of all possible configurations instead of 0.00$ - best option

PS. Preconditions are much simpler - it's possible to reproduce on any stable M2 version.
Steps to reproduce - Add configurable product to wishlist from category page.

**Comment by antboiko** [comment]
Hi @Serzhik ,

Thanks for reporting this issue. We've created internal ticket MAGETWO-59512.

Regards,
Anton.

**Comment by serzhik** [comment]
UPD: It's don't work on clean Magento EE 2,1.1 install with sample data.

**Comment by serzhik** [comment]
Look at vendor\magento\module-wishlist\Pricing\ConfiguredPrice\ConfigurableProduct.php

```
    public function getValue()
    {
        $result = 0.;
        /** @var \Magento\Wishlist\Model\Item\Option $customOption */
        $customOption = $this->getProduct()->getCustomOption('simple_product');
        if ($customOption) {
            /** @var \Magento\Framework\Pricing\PriceInfoInterface $priceInfo */
            $priceInfo = $customOption->getProduct()->getPriceInfo();
            $result = $priceInfo->getPrice(self::PRICE_CODE)->getValue();
        }
        return max(0, $result);
    }
```

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Wishlist/Pricing/ConfiguredPrice/ConfigurableProduct.php#L22-L33

**Comment by SerhiyShkolyarenko** [comment]
The fix is delivered to develop branch. Closing the issue.

**Comment by Igloczek** [comment]
It's going to be released as standalone update to Magento_Wishlist module or we have to wait for 2.2 to get this fix?

**Comment by Ctucker9233** [comment]
@Igloczek use the above commits and do a diff comparison on your code.

**Comment by Igloczek** [comment]
I know that I can handle everything on my own, but it's painful when you have ~10-20 modules to just fix something, flying around ~5 projects, with ~20 devs working on them...

I'm pretty sure that there was a plan to release patches to modules independently from main project releases and AFAIK you are talking about doing that after 2.1.2 (same as about smaller, but frequent updates of whole product)

CC @benmarks @piotrekkaminski @pboisvert

**Comment by Ctucker9233** [comment]
@Igloczek I have no doubt they will release it in some up coming patch or upgrade. I don't work for Magento so I don't really know. I assumed you needed a quick fix and that's the only method I know. Sorry for misunderstanding.

**Comment by zzvara** [comment]
I'm using Magento 2.1.6. This is still a problem. Any fix any time soon?

**Comment by korostii** [comment]
@zzvara, not likely

As I understand it, no backport is planned "by default" and closed tasks are not tracked by the core team neither (see [here](https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/ba-p/60088#M15) for an detailed official Magento Inc.'s response about that).

In general, here's what you could do if you're interested to get it backported:
a) create a pull request pointing at 2.1-develop as described [here](https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630)
b) create a new GitHub Issue referencing the original one and asking to backport the fix into 2.1. 

Additionally, mentioning a certain relevant Magento, Inc. employee somewhere in the discussion (just Igloczek did) _might_ help bringing attention to it.

**Comment by dharmendrakothe** [comment]
Main issue fix but still showing  0.00 on sidebar

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69023

**Comment by DaimPiek** [comment]
This problem still occurs in Magento 2.1.7. Both in sidebar as on the 'My account' page. 

I managed to pinpoint the problem in the following function:
\Magento\Wishlist\Pricing\ConfiguredPrice\ConfigurableProduct::getValue

Which checks if a configurable product has an option selected. If that is not the case it just returns 0.0. 

I wrote a plugin for this function returning the Minimum price instead.

```
   /**
     * @param BaseConfigurableProduct $subject
     * @param callable                $proceed
     *
     * @return float
     */
    public function aroundGetValue(BaseConfigurableProduct $subject, callable $proceed)
    {
        /** @var \Magento\Wishlist\Model\Item\Option $customOption */
        $customOption = $subject->getProduct()->getCustomOption('simple_product');
        if ($customOption) {
            /** @var \Magento\Framework\Pricing\PriceInfoInterface $priceInfo */
            $priceInfo = $customOption->getProduct()->getPriceInfo();
            return $priceInfo->getPrice($subject::PRICE_CODE)->getValue();
        }

        return (float)$subject->getProduct()->getMinPrice();
    }
```

This solves both issues ('My account' page and the sidebar).
