### ISSUE TITLE
Widget parameter depends does not work on specified block

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#6868]
### Preconditions
1. Magento 2.1.1
### Steps to reproduce
1. Create Module adding Custom Widget
2. Add Parameter like `<parameter name="catalog_url" xsi:type="block" visible="true" required="true" sort_order="33">
               <label translate="true">Category</label>
               <depends>
                   <parameter name="enable_url" value="1" />
                   <parameter name="target_url" value="1" />
               </depends>
               <block class="Magento\Catalog\Block\Adminhtml\Category\Widget\Chooser">
                   <data>
                       <item name="button" xsi:type="array">
                           <item name="open" xsi:type="string" translate="true">Select Category...</item>
                       </item>
                   </data>
               </block>
           </parameter>`
   ![parameter_depends](https://cloud.githubusercontent.com/assets/22025597/19070025/b0def80e-8a29-11e6-8ab0-2a8ca5a8b0bb.png)
   It is important to use block class="Magento\Catalog\Block\Adminhtml\Category\Widget\Chooser" or block class="Magento\Catalog\Block\Adminhtml\Product\Widget\Chooser".
3. Set any custom depends.
4. Go to admin panel. Add your widget. In widget options change parameter that our parameter depends on.
### Expected result

Our Parameter disappears, if conditions set on depends are not met.
### Actual result

Parameter is visible anyway.

**Comment by biolauri** [comment]
It's also an issue in Magento 2.1.2. And, in my opinion, it is not important which block class you use, as this is a general issue with all parameters of `xsi:type="block"` depending on another parameter.

In #5443, you find detailed info of the expected/actual for the problem (`display:none;` is set on the wrong html element). I can confirm that these are the same for this one!
Maybe, this is a duplicate of #5443 (but the steps to reproduce are a bit different).

**Comment by magento-engcom-team** [comment]
@LordHansolo, thank you for your report.
We've created internal ticket(s) MAGETWO-82054 to track progress on the issue.

**Comment by henk-hypershop** [comment]
What will be the expected fix timeframe? It is quite confusing that all depend labels are still shown.

**Comment by VincentMarmiesse** [comment]
Hello,
Any news on this issue?

**Comment by maartenwolfsen** [comment]
In my case, the problem was that the selected rowElement was the child of the rowElement that was supposed to be hidden. I added the following piece of code to fix this to 
**_lib/web/mage/adminhtml/form.js line 567_**:

`if (rowElement.className === 'admin__field-control control') {`
`      rowElement = target.up(2);`
`}`

I am currently looking for a better solution.

**Comment by OvalMedia** [comment]
For the impatient here is a fix: https://magento.stackexchange.com/questions/176091/magento-2-depends-is-not-working-in-widget-xml. Make sure you consider the first comment as the require-config.js is placed in the wrong directory. I can confirm it works fine on 2.2.9.

**Comment by koenner01** [comment]
I can confirm this issue is still present in 2.3.3.

Fix from @OvalMedia works but I really don't like copying a gigantic javascript and appending 3 lines. This is not very future (= maintainable) proof.

**Comment by Sankarant** [comment]
Found this issue present in Magento 2.3.1.  Please share the patch for this issue.
Fix from @OvalMedia works great.

**Comment by hostep** [comment]
Here's a solution which seems to work in our case, it's strongly based on the [stackexchange proposal](https://magento.stackexchange.com/a/176465/2911) but drops the original PrototypeJS implementation and uses jQuery all the way now: https://github.com/magento/magento2/pull/30570

**Comment by magento-engcom-team** [comment]
Hi @LordHansolo. Thank you for your report. 
The issue has been fixed in magento/magento2#30570 by @hostep in 2.4-develop branch
Related commit(s):
 - [e3789f0906f45b565fdb8d13d28c305917cca1bd](https://github.com/magento/magento2/commit/e3789f0906f45b565fdb8d13d28c305917cca1bd)

The fix will be available with the upcoming 2.4.2 release.

**Comment by DmitryFurs** [comment]
@magento-engcom-team @sidolov the corresponding pull request is merged, but the fix does not cover all possible cases. 2 additional cases are described in the comments to the pull request https://github.com/magento/magento2/pull/30570
