### ISSUE TITLE
Improvement Idea: /var/cache/mage--X

### ISSUE THREAD

**Issue by gstaniforthsessiondigital** [magento/magento2#687]
Instead of storing cache in a serialised array it would be much faster to store it as a native php file and var_export() the array.

If the file is .php it will get picked up via the opcache and be stored in memory but also precompiled and stored in opcache. This would also remove unserialised logic also.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30482

**Comment by vpelipenko** [comment]
@gstaniforthsessiondigital, did you have a chance to look at last comment here posted by @aohorodnyk?

**Comment by orlangur** [comment]
@aohorodnyk,

> For improvement some users can disable check for updated scripts (php files) in opcache for performance improvement. Magento does not know about opcache engines on server. Magento need support all opcache applications (xcache, php opcache, apc and etc.) or use scripts for serializations deserializations

"support all opcache applications" is not relevant for PHP 5.5+. Also, if check for updated PHP files is not disabled on production - it's simply a server misconfiguration which must be fixed.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improvement-Idea-var-cache-mage-X/idi-p/47135).
