### ISSUE TITLE
Shipping address form trying to validate disabled/hidden fields

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6872]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Adding some fields with custom extension to shipping address form. By default, these fields hidden and disabled. These are depends on a select (address_type) input to being visible.
2. Fill the form except custom fields (Still disabled and hidden)
3. Click 'Next' button to submit form
### Expected result

1. Navigate to payment step with shipping address info
### Actual result

1. It is trying to validate hidden and disabled fields, so can not move on.
   If select other address_type option which is enabling and show fields, required validation errors shown up.

**Comment by veloraven** [comment]
@rbostan thank you for your feedback.
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions as it seems to be a problem of a custom extension.
If you think it to be Magento issue please explain your position.

**Comment by cizgidekiadam** [comment]
@veloraven Is it clear? 

There are some fields in address forms (custom or system). 
In my case, some of them should be required only when they are visible. 
But form validator trying to validate them while hidden or disabled. 

It may not to be a bug but may be considered as an improvement. 

Thanks a lot for suggestion, i'll be looking on forums or somewhere else.
