### ISSUE TITLE
Bundle checkbox options - missed qty for every checkbox

### ISSUE THREAD

**Issue by OlgaBurtyka** [magento/magento2#6873]
Hi! Bundle options type checkbox - not display add qty - for every checkbox. 
### Preconditions

1. magento 2.1.1
2. php 7.0.7 
3. nginx
### Steps to reproduce

1. Go to bundle product with checkbox
2. Try check checkbox and add qty for every selected checkbox
### Expected result

1. I can add qty for every checkbox option
### Actual result

1. I can't set for checkbox qty.
   ![checkbox](https://cloud.githubusercontent.com/assets/4771407/19083570/6125dd7c-8a6b-11e6-850e-395b5b7fce68.png)

**Comment by dthampy** [comment]
Internal jira ticket -MAGETWO-59888 has been created for this issue.

**Comment by dthampy** [comment]
@OlgaBurtyka , after discussing with Product Owner,  it was confirmed that "User Defined" quantity is not allowed for checkbox and multiple-select input types by design.
So closing this as Not a Bug

**Comment by benvansteenbergen** [comment]
For anyone looking for a temp solution, check out this repo: https://github.com/Itonomy/magento2-bundle-products-change-qty

**Comment by dsomnionline** [comment]
> For anyone looking for a temp solution, check out this repo: https://github.com/Itonomy/magento2-bundle-products-change-qty

Hi @benvansteenbergen 

This solution is not working when you edit the product from a mini cart. It gives the error can you please check and provide the solution for this.
