### ISSUE TITLE
Address Book - Delete Additional Address not working

### ISSUE THREAD

**Issue by btjackson11** [magento/magento2#6877]
### Preconditions
1. Magento 2.1.1
2. php 5.6.1
### Steps to reproduce
1. Make an account
2. Login to the account
3. Go to the account address book
4. Add an additional address to the address book
### Expected result
1. In the address book under the "Additional Addresses" click "Delete Address"
2. Deletes address from under the "Additional Addresses"
### Actual result
1. In the address book under the "Additional Addresses" click "Delete Address"
2. Does nothing. Has an href="#"...

**Comment by btjackson11** [comment]
I found the reason. In the javascript at the bottom of that page it is looking for the presence of an element with the class of "page-main". This class does not exist on my page so I changed it to look for "customer-address-index" the class on the body element and both links started working properly.

**Comment by dikshugoel786** [comment]
I have checked with Your solution but not working for me

**Comment by xpec-eestrada** [comment]
thank, your solution work for me.

**Comment by versdivers** [comment]
On book.phtml file you will see 
```
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "li.item a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
```

Just change the 'deleteAddress' value to whatever your it represents. I changed the li to div so for me it was 'div.item a...'
