### ISSUE TITLE
Readiness Check fails when installing new component

### ISSUE THREAD

**Issue by MikeMoolenaar** [magento/magento2#6883]
When I try to install a new extension in Magento, it does a Readiness Check first, I get 2 errors which I am trying to fix.

![image](https://cloud.githubusercontent.com/assets/20370521/19109408/99b8a324-8af5-11e6-8166-d0980da6d55b.png)

**Check Cron Scripts**
I Tried to run the cron.php every 5 minutes with Windows Task manager, but it still gives this error.

**PHP Settings Check**
This is what I changed in the php.ini file:
`memory_limit=768M`

But it still says that the memory limit is 128MB.

**Info**
- Magento version: 2.1.1
- OS: Windows 10
- Webserver: Bitnami

Thanks in advance.

**Comment by veloraven** [comment]
@likemike2 thank you for your feedback.
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see  [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) .
