### ISSUE TITLE
In cart page when i am clicking proceed to checkout page is not going to checkout page . 

### ISSUE THREAD

**Issue by KalaiarasanSeetharaman** [magento/magento2#6887]
In cart page when i am clicking proceed to checkout page it is not going to checkout page . 
I  signed in only . I have a added only one product , that product having more than 1000 qty in backend . I have enabled page cache in backend also . I have cleared flush magento cache also and cleared static files and i have refresh page cache also .

**Comment by veloraven** [comment]
@KalaiarasanSeetharaman thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by KalaiarasanSeetharaman** [comment]
### Preconditions




1. Magento CE 2.0.7
2. Our category 
3. Our produts

### Steps to reproduce


1. Added a product whith qty of 500 price as 20 
2. Added minimum order amount as 200
3. Clear cache and i have re-index
4. Page cache alone enabled
5. It is development mode only
6. I have signed in and i have a added product
7. While clicking view cart in minicart it is going correctly to the cart page and it say warning miniorder amount is needed 
8. I also update the cart with more than $200 amount 
9. Warning does not appear and than i proceed with by clicking proceed to checkout . but it come again to cart page itself . 
10. I have encounter the issue .It is checking !$this->validateminiorderamount() in controller.

### Expected result


1. But actually it should to go to checkout page since condition match . miniorder amount is more than $200

### Actual result


1. [Screenshot, logs]

**Comment by SerhiyShkolyarenko** [comment]
@KalaiarasanSeetharaman thank you for the report!
I tried to reproduce on latest develop branch and checked on 2.0.10 too. In both cases issue was not reproducible by these steps.
Is it reproducible for you on 2.0.10?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
