### ISSUE TITLE
Associated products of Grouped products cannot be sorted in multi-page scenario.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#6888]
Associated products of Grouped products cannot be sorted in multi-page scenario.

If a associated products for a grouped product needs to be sorted, Magento 2.1 allows the admin to drag and drop to change the sort orders. The issue is when the list of associated products go in multiple pages, the drag and drop cannot go across the pages - making it impossible to achieve proper sorting.

Magento 2.1.1

Steps:
- Create simple products (many - 30 + or more).
- Create group product.
- Add (associate) products to grouped products. Save.
- Go back to the product (with many associated products, the list of associated products should be paginated). 
- Try to pick the last product from the last page and try to bring it at the top of the list.

Current: The product can be sorted within the page only and not across the page.

Expected: Sort order for associated products should be possible across the page.

Let me know if there is a workaround available now. Even if it is thru DB, I would like to know.

**Comment by sevos1984** [comment]
You can't do this at the moment. You can add them in order you need, or change value in catalog_product_link_attribute_int table.
