### ISSUE TITLE
M2.1.1 Multi currency, wrong value of order total in Order Customer Tab

### ISSUE THREAD

**Issue by tudn9x** [magento/magento2#6890]
### Preconditions

1. Server: ubuntu server 16
2. PHP 7
### Steps to reproduce

1. Create multi currency and checkout with different default currency. (Ex: Viet Nam Dong - đ)
2. In Frontend, Order History page, value of Order Total show perfect with multi currency. But.
3. In Backend, Order History tab of customer, value of Order Total was show wrong. 
### Expected result

1. Rate:
   ![screenshot_3](https://cloud.githubusercontent.com/assets/4941829/19139103/fb5092d4-8bab-11e6-80f3-b879fb71bdf4.png)
2. Frontend:
   ![screenshot_1](https://cloud.githubusercontent.com/assets/4941829/19139111/0335f2be-8bac-11e6-8418-c44307da5a50.png)

3: Backend:
![screenshot_2](https://cloud.githubusercontent.com/assets/4941829/19139116/079a71c2-8bac-11e6-8178-800e9690aa5a.png)
### Actual result

1. Order Total = value instead of the Order Total = value x rate

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59462. Thanks for reporting

**Comment by magento-engcom-team** [comment]
@htmyheart, thank you for your report.
We've created internal ticket(s) MAGETWO-59462 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@htmyheart, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by tudn9x** [comment]
Thank @sevos1984  and @magento-engcom-team show now, I want re-open this issue, if you guys have time please check it again. Thank you so much.
