### ISSUE TITLE
Gd2 opacity handler not effective

### ISSUE THREAD

**Issue by rdeelstra** [magento/magento2#6900]
Hi all,

I was adding a watermark to images and noticed it did not work, so I traced it back to the Gd2 adaptor:
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php

At line 401 method:
public function watermark($imagePath, $positionX = 0, $positionY = 0, $opacity = 30, $tile = false)

Problem:
The $opacity is not taken care of, instead $this->getWatermarkImageOpacity() is being called which returns null.
And then nothing happens because of the function imagecopymerge with an empty pct:
The two images will be merged according to pct which can range from 0 to 100. When pct = 0, no action is taken, when 100 this function behaves identically to imagecopy() for pallete images, except for ignoring alpha components, while it implements alpha transparency for true colour images.
http://php.net/manual/en/function.imagecopymerge.php

**Comment by veloraven** [comment]
@rdeelstra thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by rdeelstra** [comment]
Did you look at the link?

**Comment by veloraven** [comment]
@rdeelstra it is much easier and tales less time to process tickets which are formatted according to templates, when I can at once see what have to be done to reproduce the issue and what is the result. And there is no need to read the whole description to find e.g. expected result. Additionally, different people may process your issue at different steps, and not all of them necessary deal with code.
So, I ask you once more, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
