### ISSUE TITLE
 Shipping Review & Payments 

### ISSUE THREAD

**Issue by janko007** [magento/magento2#6901]
Shipping Review & Payments  not translated
<img width="1199" alt="screen shot 2016-10-06 at 12 45 16" src="https://cloud.githubusercontent.com/assets/9162875/19149560/ba03689e-8bc2-11e6-96c3-a1d937a254ee.png">

**Comment by Tjitse-E** [comment]
Which Magento 2 version are you using? I believe that this issue was fixed in Magento 2.1

**Comment by veloraven** [comment]
@janko007 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
