### ISSUE TITLE
Minicart edit and delete link not working

### ISSUE THREAD

**Issue by amit-agrawal-emorphis** [magento/magento2#6903]
### Preconditions

1. Using Magento version 2.1.1 PHP 7 and MySQL 5.7 . 
### Steps to reproduce

1. Add simple product to cart.
2. Then on top,click cart icon.
3. In Minicart input field qty empty.Edit and delete link are not working.
### Expected result

1. In minicart show quantity .Edit and delete link are working properly.
2. When we click edit link redirect to product detail page for editing product.
   3.When we click delete icon product should be removed from cart. 
### Actual result

1. In Minicart input field qty empty.Edit and delete link are not working.
2. Browser console show below error

``````
Uncaught ReferenceError: Unable to process binding "attr: function (){return {
                           id:'cart-item-'+item_id+'-qty','data-cart-item':item_id,'data-item-qty':qty,'data-cart-item-id':product_sku} }"
Message: product_sku is not defined
```;

<!--- (This may be platform independent comment) -->
``````

**Comment by odubovyk** [comment]
@emorphis-pravesh, please make sure that all cashes are clean. Cannot reproduce this

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
