### ISSUE TITLE
Unable to Create new password from reset password link with Website restrictions turned on 

### ISSUE THREAD

**Issue by wittyvishwas** [magento/magento2#6905]
### Preconditions
1. Magento Version 2.1.0EE , PHP 7 , MySQL 5.7
2. Nginx
### Steps to reproduce

1. Turn on website restrictions 
2. Trigger Forgot password for User 
3. From Email received , click SET PASSWORD  
### Expected result
1. You land on **customer_account_createpost**
### Actual result
1. The user get redirected to Landing page that is set in website restriction settings

**Comment by wittyvishwas** [comment]
Creating new **webrestrictions.xml** in custom module and add  
`<action path="customer_account_createPassword" type="generic" />`
For a temporary fix, as when the email new password link is generated it has Capital P but the view page action is with small p

**Comment by slavvka** [comment]
The issue has been fix as a part of internal MAGETWO-57553 and delivered to mainline. See f4677d7 and 6196e68 EE commtis.
