### ISSUE TITLE
M2.1.1 : Unable to change `resource` in webapi.xml

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6906]
### Preconditions
Magento 2.1.1

I want to be able to change the `<resource ref="self" />` to `<resource ref="anonymous" />` in a non-obstructive way, but there's currently no way of doing this. Take the following snippet from `quote/etc/webapi.xml`:

```
<route url="/V1/guest-carts/:cartId" method="PUT">
    <service class="Magento\Quote\Api\GuestCartManagementInterface" method="assignCustomer"/>
    <resources>
        <resource ref="self" />
    </resources>
</route>
```

I want to be able to make this endpoint accessible anonymously. I thought I'd simply add a `webapi.xml` to my own module and add the following line:

```
<route url="/V1/guest-carts/:cartId" method="PUT">
    <resources>
        <resource ref="anonymous" />
    </resources>
</route>
```

Since Magento flattens all it's configuration, I assumed that `self` would be replaced with `anonymous`.

However... the addition of an extra node to `<resources>` causes an `AND`-condition. So now my API response (error) tells me:

```
"message": "Consumer is not authorized to access %resources",
  "parameters": {
    "resources": "self, anonymous"
  }
```

So instead of changing the permissions, it adds it.

### Expected result
1. I expect that I can change the access permissions.
### Actual result
1. It adds the access permissions.
### Workaround

As a temporary workaround, I now added a new endpoint, pointing to the same methods:

```
<route url="/V1/guest-carts-anonymous/:cartId" method="PUT">
    <service class="Magento\Quote\Api\GuestCartManagementInterface" method="assignCustomer"/>
    <resources>
        <resource ref="anonymous" />
    </resources>
</route>
```

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We've created internal ticket(s) MAGETWO-84534 to track progress on the issue.

**Comment by fireufo** [comment]
Reproduced on 2.2.3, hope to solve it as soon as possible, thanks.

**Comment by wittyvishwas** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@wittyvishwas thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by wittyvishwas** [comment]
Hello @kanduvisla 
Magento is using a node structure for resources (so that you can add multiple resource)
```
 <resources>
        <resource ref="self" />
    </resources>
```  
So if you add multiple nodes to  you can have multiple node under it 
```
 <resources>
        <resource ref="self" />
        <resource ref="Magento_Catalog::products" />
    </resources>
```  
So it will always append nodes .
