### ISSUE TITLE
SID - user is constantly logged out

### ISSUE THREAD

**Issue by wojciechowskid** [magento/magento2#6907]
### Preconditions
1. PHP 5.6.21
2. MySql 5.0.11
3. Magento CE 2.0.9
### Steps to reproduce
1. Generate SID. We do this so:

```
      $this->session->setCustomerDataAsLoggedIn($customer);
      $this->session->regenerateId();
      $sid = $this->session->getSessionId();
```

Where $this->session is set in constructor and got with help of DI (Magento\Customer\Model\Session).
2. We use URL https://secure_base_url/?SID=%genegated sid% and open it
### Expected result

User is authorized and browses webshop independently of whether page cache is turned on or off 
### Actual result
1. If Full Page Cache is Off, a user receives cookies with session id and gets authorized.
2. If Full Page Cache is On, then a user won't get cookies with session id and is authorized only if SID is presented in the URL, i.e. if here clicks any link (e.g. product details page) which doesn't have SID, then he gets logged out

Could you please help with this? TIA

**Comment by wojciechowskid** [comment]
Hello, is there any progress? Do you know the root of the problem?
Thanks

**Comment by magento-engcom-team** [comment]
Hi @wojciechowskid 
This is not a bug. 
You should login customer as it do in
`\Magento\Customer\Controller\Account\LoginPost::execute`

**Comment by magento-engcom-team** [comment]
@wojciechowskid, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
