### ISSUE TITLE
API improvement: CategoryRepositoryInterface should have a getList method

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/magento2#6918]
As a developer you need to be able to retrieve categories by certain conditions e.g. to select categories by their parent ID or by their ID path. Currently this is only possible by using the categorie's resource model directly which is an unclean approach.
The ProductRepositoryInterface provides a getList method which allows a developer to select products by using the SearchCriteriaInterface. For categories this should be possible in the same way.

**Comment by piotrekkaminski** [comment]
@phoenix-bjoern would you be willing to contribute this as a PR?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/API-improvement-CategoryRepositoryInterface-should-have-a/idi-p/51539).

**Comment by mbrinton01** [comment]
Tracking internally as MAGETWO-60018
