### ISSUE TITLE
API improvement: OrderInterface should have a getShippingAddress method

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/magento2#6919]
As a developer who writes an order export for Magento2 you would expect that besides the getBillingAddress there would be also a getShippingAddress method. While all the [g/s]etShipping... methods exists in the Magento\Sales\Model\Order model (which is the actual implementation of the OrderInterface) those elementary shipping-address methods are not part of the API interface.

Example: $order is declared as type Magento\Sales\Api\Data\OrderInterface. Practically the code "$order->getShippingAddress()" works but from a declarative view the method does not exist in the API and the implementation therefore is technically wrong.

While it is understood that not all orders have a shipping address (virtual orders/goods) the majority of orders processed in ecommerce actually have a shipping address. So the shipping-address methods should become part of the OrderInterface like it is already the case for the billing-address methods.

**Comment by pboisvert** [comment]
Thanks Bjorn for the feedback. Will make sure the product owner for APIs sees this

**Comment by phoenix-bjoern** [comment]
Thanks @pboisvert! already in touch with @choukalos :-)

**Comment by pboisvert** [comment]
yes--Chuck knows about this area but owned currently by @mbrinton01

**Comment by piotrekkaminski** [comment]
@phoenix-bjoern would you be willing to contribute this as a PR?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/API-improvement-OrderInterface-should-have-a-getShippingAddress/idi-p/51534).

**Comment by mbrinton01** [comment]
Tracking internally as MAGETWO-60017
