### ISSUE TITLE
Feature Request: i18n files

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#692]
This comes from a real life scenario I'm dealing with right now for Magento1.  
When building a multilanguage website, the first thing I do is get the appropriate language packs. But most of them are not complete. So what I filter the texts that are not translated and send them to the customer to get the translated texts.  
But there is a problem here. There are a lot of texts to translate. usually the customer does not care about the translation of technical texts like "View files fallback" or "Logging from \Magento\Framework\Logger" (examples taken from m2 language files).  
Giving them these texts will just spawn additional questions and make them frustrated.  
My main suggestion is...Split the language files in 2 (or more). one for technical texts and one (or more) for user texts. It would make translations a lot more easier.

I know this looks like hard work, but I want to know if you are at least considering it.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30484

**Comment by buskamuza** [comment]
@tzyganu , how do you think, should such technical phrases be translated at all?

**Comment by tzyganu** [comment]
@buskamuza I didn't think this through. I just stated a problem I had in the past hoping someone would have a solution. 
Now that you mentioned I think this would be the easiest solution. not to translate the exception messages that have no meaning to a non technical person.

**Comment by otoolec** [comment]
Marius, in the real life scenario were the translations meant to help the merchant understand the UI or were they meant to be used on the storefront for customers?

The example you gave "View files fallback" is used as a label in admin, so even if we just focus on exceptions it would still exist. 

Would it help if phrases were split by area?  If we had one file for phrases used by storefront, and one for phrases used by admin, then opening a new store view for a new language can be done by translating only the storefront related files.  No need to translate the admin for the new language being supported by the store view.

**Comment by pronto2000** [comment]
Yeah, keeping frontend and backend translations separate would be great -- it makes it way easier to keep frontend up to date.

**Comment by piotrekkaminski** [comment]
Hey, we have decided not to split by area or have backend separate.
