### ISSUE TITLE
Update category, URL key already exists error

### ISSUE THREAD

**Issue by ngorupaha** [magento/magento2#6920]
### Preconditions

1. Magento version 2.1 ee
### Steps to reproduce

1.  go to admin panel and try to edit url key for already created category 
2. but this issue related only for categories that include 2levels of subcategories.
### Expected result

1. url key for specified store already exists.
### Actual result

1. https://drive.google.com/file/d/0Bz6ZgipDQ-L8UURpa2tCRXEzWWs/view

**Comment by pboisvert** [comment]
@ngorupaha given this is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by Yerokhov** [comment]
This error is also present in version 2.1.1 CE
