### ISSUE TITLE
Sitemap is not working in magento2.0.6

### ISSUE THREAD

**Issue by KalaiarasanSeetharaman** [magento/magento2#6921]
### Preconditions

1. Magento 2.0.6 
### Steps to reproduce

1. I have generate the sitemap by using marketing -> sitemap 
2. cretaed sitemap under the folder sitemap/sitemap.xml also genertaed in that file
3. System configuration also done by going to sytem -> configuration -> catalog-> xml sitemap
4. Set frequncy as daily , generating time as 00 00 00 
5. Page cache also enabled 
6. Cache aslo cleared 
7. I have reindex also and i also cron for reindexing for every min 
### Expected result

1. In frontend sitemap should come when click catalog/seo_sitemap/category/.
### Actual result

1. It tell 404 page

**Comment by stamster** [comment]
You need to put path as `/pub/sitemap/sitemap.xml`. 
So just add `/pub/` in front of your desired directory.

BTW, Magento 2.0.6 is out-of-date, not that 2.1.x is much better but at least some bugs are fixed xD

**Comment by KalaiarasanSeetharaman** [comment]
I have developed project using magento 2.0.6 . How can i upgrade . It will not affect my theme ?

**Comment by KalaiarasanSeetharaman** [comment]
I have generated the sitemap in /pub/sitemap/sitemap.xml . Even though in frontend by clicking this catalog/seo_sitemap/category/. it says 404 not found. please help me

**Comment by antboiko** [comment]
Hi @KalaiarasanSeetharaman , what is catalog/seo_sitemap/category/? 

Can you please navigate to Admin > Marketing >  SEO & Search > Sitemap and tell me what you have in "Link for Google" column?

Thanks,
Anton.

**Comment by KalaiarasanSeetharaman** [comment]
I have in that  http://xxxx.com/pub/sitemap/sitemap.xml

**Comment by antboiko** [comment]
@KalaiarasanSeetharaman  That is the link for your generated sitemap.

Best,
Anton.

**Comment by KalaiarasanSeetharaman** [comment]
In frontend how the user can view the sitemap ? by giving the above link ?

**Comment by cadoworld** [comment]
Hi, does your store is setup on single stone ... 
try to store>configuration>general  Single-Store Mode > No
then reindex.

I had similar problem to see other page on magento 2.1.x
Hope it will work

**Comment by antboiko** [comment]
Hi @KalaiarasanSeetharaman , yes, your XML sitemap is accessible by this link.

Best,
Anton.

**Comment by veloraven** [comment]
As this issue was solved and there have been no new comments from the reporter for more than two weeks, I'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
