### ISSUE TITLE
Category Top Navigation -> Maximal Depth is broken in > 2.1

### ISSUE THREAD

**Issue by pyostrike** [magento/magento2#6925]
It's said at http://docs.magento.com/m2/ce/user_guide/catalog/navigation-top.html that this value controls maximum number of levels that are available in top navigation. Actually it's not.
### Steps to reproduce

Create a 3 level category tree. Set Maximal Depth to 1.
### Expected result

Menu in top navigation will not show sub categories.
### Actual result

Menu in top navigation shows all categories.

**Comment by veloraven** [comment]
@pyostrike thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by pyostrike** [comment]
Хохлы ) Лишь бы не работать.

**Comment by dnadle** [comment]
Please reopen this. It is a fact that setting Maximal Depth -> 1 in v 2.1.2 does not prevent multiple menu levels from displaying. Also it looks like the original post was edited to conform to your guidelines.

**Comment by PascalBrouwers** [comment]
Continue in https://github.com/magento/magento2/issues/7543
