### ISSUE TITLE
Backend: Update product stock not working on save

### ISSUE THREAD

**Issue by FranRoy** [magento/magento2#6926]
## Preconditions
- I'm running Magento 2.1.1 on Centos7 + php7 + nginx 1.10 + mysql 5.6 + redis on a Amazon ec2 stack.
- My website was migrated from a Magento 1.7.2
- My website is configurated to manage stock
- The issue only happens on migrated products
- New products work as expected
## Steps to reproduce
- Go to a simple product (migrated one)
- Change stock qty
- Save
## Expected result

Stock should be updated with the qty introduced
## Actual result

Stock remains the same qty

Also notice that if an order is placed, the order is decreased correctly and if I cancel the order, it is also increased correctly.

**Comment by lbajsarowicz** [comment]
Could you share any Nginx error logs, Magento debug / support logs?
What is more - could you attach any extra information about migrated products?

**Comment by FranRoy** [comment]
Hello Lukasz,

I have been trying all possibilities to narrow the issue, and here is the
conclusion:

The issue has nothing to do with migrated products and payment works fine.
The error *only ocurre *on *configurable products. *Doesn't matter if they
are migrated or new. If someone buys a configurable product, the product is
supposed to be taken from the warehouse assigned to the store but what
happens is that it always tries to take it from the main warehouse too.

To summarize:
- 2 Stores S1 and S2
- 2 Warehouses, W1 and W2. S1 only takes stock from W1 and S2 from W2.
- Warehouse routes are correctly configurated
- If someone buys anything from S1 all works as expected
- If someone buys simple products from S2 it works as expected
- If someone buys a Configurable product from S2, it takes simultaneously
stock from W1 and W2 which triggers an error of the module when W1 stock is
0 (it says that it cannot take stock from a product of stock 0 for that
warehouse). The error is triggered when trying to complete the order in the
backoffice.

What I have been doing as a workaround to this is to add 1 stock on W1
every time a sale is made and then it works as a provisional fix.

Magento version 2.1.7

Best regards,

Fran Roy.

Fran Roy.

2017-09-17 16:45 GMT+02:00 Lukasz Bajsarowicz <notifications@github.com>:

**Comment by magento-engcom-team** [comment]
Hi @FranRoy 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
