### ISSUE TITLE
New Order Email Template Loading Error (Missed JSON structure)

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#6931]
### Preconditions
1.  Magento 2.1.1 Release from archive
### Steps to reproduce
1. Go to Marketing -> Email Templates
2. Select any "New Order" template -> click Load Template
### Actual result

1.Exception log: 
main.CRITICAL: exception 'Zend_Json_Exception' with message 'Decoding failed: Syntax error' in .../vendor/magento/zendframework1/library/Zend/Json.php:97

**Comment by hostep** [comment]
Duplicate: https://github.com/magento/magento2/issues/5101 & PR: https://github.com/magento/magento2/pull/5116
The PR was already merged in the develop branch, so it should appear in one of the next releases hopefully :)

**Comment by veloraven** [comment]
Closed as duplicate.
We have separate internal issue for ver. 2.1 - MAGETWO-57026
