### ISSUE TITLE
Order Grid not showing NEW orders after upgrade from 2.0 to 2.1

### ISSUE THREAD

**Issue by shanevbg** [magento/magento2#6932]
Ever since I upgraded from Magento 2.0 to 2.1 (and now 2.1.1), I haven't been able to see NEW orders in the order grid (old ones show up just fine). I've tried disabling extensions, etc. I can get to the orders by either going to transactions and see them there, or the dashboard, but the order grid doesn't show any entries from after I updated to 2.1.

NEW orders also don't show up in the query
SELECT \* FROM sales_order_grid AS main_table
order by entity_id desc
### Environment
1. Ubuntu 16.04.1
2. Magento 2.1.1
3. PHP 7.0.8
4. MySql 5.7.15
### Steps to reproduce
1. Create a new order
2. Go to dashboard, see order
3. Go to Admin-Sales-orders no order
4. If used a transaction, can find the transaction and order from transaction
### Expected result
1. Should see new orders in the order grid
### Actual result
1. No new orders show in the order grid after upgrading from 2.0 to 2.1, all old orders are still visible however
### Question

Is there someway to run a script/job to update the order_grid, etc?

**Comment by salelsol** [comment]
- Exact same issue, just updated from 2.1.1 to 2.1.2 ,  I´m trying truncate all sale tables, also disable all extensions installed but nothing change about.

**Comment by salelsol** [comment]
- Issue starting just when I´m upgraded from 2.0.7 to 2.10, before everything worked properly.

**Comment by salelsol** [comment]
- Hi shanevbg , are you installed any Onepage checkout extension ?

**Comment by salelsol** [comment]
- Fixed, go to Asynchronous Grid and "Disable" in Advanced/Developer/Grid Settings: Set Asynchronous Indexing to “Disable”, flush cache, and check again.

**Comment by SerhiyShkolyarenko** [comment]
@shanevbg I performed the steps:
set up 2.0.9
created 2 orders
changed code to 2.1.1
`rm -rf var/*`
`./bin/magento setup:upgrade`
`rm -rf var/*`
`./bin/magento cron:run` (twice)
created new order
All 3 orders are displayed in the grid as expected.
Am I doing something wrong? Please, hint me how to reproduce the issue.

**Comment by shanevbg** [comment]
It seems that I had to run the cron job twice (I did not do the other steps you did just to try and figure out if it was something simple).
`sudo -H -u www-data bin/magento cron:run`
This is perplexing because I do have the cron job setup and I  tested running it.
You can close this issue as far as I am concerned.

**Comment by shanevbg** [comment]
**THANKS! THAT WAS IT**
It seems that I had to run the cron job twice (I did not do the other steps you did just to try and figure out if it was something simple).
`sudo -H -u www-data bin/magento cron:run`
This is perplexing because I do have the cron job setup and I  tested running it.

**Comment by SerhiyShkolyarenko** [comment]
@shanevbg thank you for update. I'm happy it worked for you! )

**Comment by ghost** [comment]
We get the same issue in Magento 2.1.6 fresh install with sample data. The solution for us was to go to Asynchronous Grid and "Disable" in Advanced/Developer/Grid Settings: Set Asynchronous Indexing to “Disable”, flush cache, and check again as @salelsol wrote.

**Comment by Ctucker9233** [comment]
@magento-engcom-team I just ran into this issue and I'm on 2.1.7. Please fix this asap or if it has been fixed, what version has the fix?

**Comment by boostify-pro** [comment]
I just updated to 2.3.1 and having same problem, 

I have only PayPal as a payement method.

I already tried @salelsol and @shanevbg solutions but not working for me
   
any fix please.

**Comment by SoCix** [comment]
I just updated to 2.3.1 and having same problem,

I have only PayPal as a payement solution.

any fix please.
