### ISSUE TITLE
Magento 2.1 REST API configurableProductLinkManagementV1 Associating Simple to Configurable Products error

### ISSUE THREAD

**Issue by kcarm8** [magento/magento2#6933]
I'm making a call to REST API configurableProductLinkManagementV1. The first simple product is associated correctly. Any simple product after that is not. The error I receive states "option values are not specified".  I'm passing in the following JSON:

'{"childSKU": "my SKU here"}'

I'm running Magento 2.1.0, PHP version 5.6.25-1+deb.sury.org~trusty+1, Apache/2.4.7, Ubuntu Linux 14.04, MySQL 5.6.33-0ubuntu0.14.04.1. 
### Steps to reproduce
1.  I create all of the simple products using  catalogProductRepositoryV1.
2.  I then create the configurable product using the same REST API.
3.  Next I add the configurable product options using configurableProductOptionRepositoryV1.
4.  Finally I associate all of the simple products to the configurable product using configurableProductLinkManagementV1.
### Expected result
1.  I'm expecting for the configurable product to have its associated simple products. 
### Actual result
1. Only the first simple product has been added to the configurable product.  No other simple products are added to the configurable product.

What are the correct steps when creating simple/configurable products and associating the products to one another?  And is there any where that I can find what the different JSON objects represent?  The REST API documentation doesn't give enough detailed information.

**Comment by lilmuckers** [comment]
Magento Community 2.1.1 here
+1 to this

My behaviour is similar - Except that adding _any_ product to the configurable throws the error `Option values are not specified.` 

I'm following the same steps as above. 
It _looks_ like the option values are dependant on a product being associated, but associating a product with the configurable is dependant on there being an option.

If i comment out where that error is added within `Magento\ConfigurableProduct\Model\OptionRepository` - then the product is added correctly and seems to appear on the frontend for purchase just fine.
this is obviously not a _fix_

**Comment by kcarm8** [comment]
Thanks for your response @lilmuckers.  I've commented out where the errors where added.  Although the errors did go away, the subsequent child products after the first one were not added to the configurable product.

**Comment by RomanKrut** [comment]
@kcarm8 Hello, can you please provide more detailed steps, with all your requests witch have type of request and body?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by coder-pm** [comment]
It happens when simple product associated with configurable one is disabled. I had to deal with this issue in 2.2.3.
