### ISSUE TITLE
SHH Magento upgrade error

### ISSUE THREAD

**Issue by Crustymd** [magento/magento2#6936]
So i am having this strange issue that i can not find on entire web. 

I just installed the freshly 2.1.1 I am running CentOS + ISPmanager php version is 5.6 and MariaDB 10.

All went smoothly with no errors, i manage to clear cache and reindex data with no problem. I uploaded the magento 2.1 theme, and now i have to manuualy install the modules. For example 

"php bin/magento module:enable MGS_Mpanel" and i get an error. Now when i try to upgrade the magento i get the same error. How do i fix it?

I just enter php bin/magento setup:upgrade

and i get this

![image](https://cloud.githubusercontent.com/assets/10128514/19222032/da173baa-8e57-11e6-9a90-227edf30bbb7.png)

**Comment by Crustymd** [comment]
If i try to install them from backend i get this error:

[2016-10-09 17:56:03 UTC] An error occurred while executing job "setup:cache:disable []": Could not complete setup:cache:disable [] successfully: Deployment config file env.php is not writable.
[2016-10-09 17:56:03 UTC] Job "setup:module:enable {"components":[{"name":"MGS_Blog"}]}" has started

[2016-10-09 17:56:03 UTC] An error occurred while executing job "setup:module:enable {"components":[{"name":"MGS_Blog"}]}": Could not complete module:enable successfully: Deployment config file config.php is not writable.
[2016-10-09 17:56:03 UTC] Job "setup:upgrade []" has started

**Comment by Crustymd** [comment]
And this is the error from error log:

[Sun Oct 09 19:06:40.972178 2016] [access_compat:error] [pid 31235] [client 37.143.14.123:37166] AH01797: client denied by server configuration: /var/www/fabi/data/www/***_/app/etc/config.php
[Sun Oct 09 19:30:11.373549 2016] [access_compat:error] [pid 1254] [client 37.143.14.123:35679] AH01797: client denied by server configuration: /var/www/fabi/data/www/**_**/app/etc/config.php
[Sun Oct 09 19:52:49.316988 2016] [access_compat:error] [pid 3326] [client 37.143.14.123:34244] AH01797: client denied by server configuration: /var/www/fabi/data/www/****/app/etc/config.php

**Comment by Crustymd** [comment]
I managed to clear All the issues with permission, setting everything to 775 and 664;

After installing modules with SSH all was good, except when trying to run the update, here i s the var/log

a:4:{i:0;s:209:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
MGS_Luxurysampledata data: current version - none, required version - 1.0.0.0";i:1;s:2645:"#0 /var/www

**Comment by veloraven** [comment]
@Crustymd thank you for your feedback.
As I understand the original problem is solved now.
Did you run "bin/magento setup:upgrade"?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
