### ISSUE TITLE
Paypal shows shipping address instead than billing address

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#6941]
Magento 2.1.1
Plesk 12.5.
Apache 7.08
MySql 5.6.29
Nginx
### Steps to reproduce
1. Add product(s) to the shopping cart
2. Go to the checout process
3. Insert a shipping address
4. pay with paypal
5. Use credit card
### Expected result
1. The invoice address in Paypal shows the billing address
### Actual result
1. The invoice address shows the shipping address

**Comment by YevSent** [comment]
Hi @PierAlex, thanks for reporting and please provide more details about:
1. What type of PayPal integration do you use?
2. Your payment action is `authorization` or `sale`? 
3. Do you use checkout for authorized or guest customer?
4. The billing address the same as shipping?

Also, please, enable debug mode for PayPal integration in the Magento admin configuration and attach debug log with requests and response for your transaction.

**Comment by PierAlex** [comment]
Hi @joni-jones,
1. Website Payments Standard
2. Sale
3. Checout for registered customer
4. No

I can't provide logs, sorry.

Thanks.

P.S. I'm upgrading to the 2.1.2 and it seems that something has chenged.

**Comment by PierAlex** [comment]
...same problem on 2.1.2

**Comment by PierAlex** [comment]
...in addition, on 2.1.2, enabling debug mode for paypal, i can see in the log file that values for:
COUNTRYCODE, STATE, CITY, ADDRESS, ZIP, PHONENUMBER
are the same as
SHIPTOCOUNTRYCODE, SHIPTOSTATE, SHIPTOCITY, SHIPTOADDRESS, SHIPTOZIP, SHIPTOPHONENUMBER
and that those values come from the shipping address provided in Magento.

Billing address is not provided to paypal.

**Comment by YevSent** [comment]
@PierAlex, COUNTRYCODE, STATE, CITY, ADDRESS, ZIP, PHONENUMBER - there are billing address details. By default billing address the same as shipping, do you have different billing address for the customer?

Without debug logs it's hard to understand what happens.

**Comment by PierAlex** [comment]
@joni-jones 
it is exactly what I'm reporting.
In the fields: COUNTRYCODE, STATE, CITY, ADDRESS, ZIP, PHONENUMBER there are values related to the shipping address and not to the billing address.

The customer has 2 addresses, 1 is the default billing address and the other one is the default shipping address.
To Paypal, only shipping address data are sent. In the fields for billing address there are values related to the shipping address. 

This is the debug log, i have modified personal data:

[2016-10-22 07:27:34] main.DEBUG: array (
  'url' => 'https://api-3t.paypal.com/nvp',
  'SetExpressCheckout' => 
  array (
    'PAYMENTACTION' => 'Sale',
    'AMT' => '218.00',
    'CURRENCYCODE' => 'EUR',
    'RETURNURL' => 'http://www.mywebsite.com/paypal/express/return/',
    'CANCELURL' => 'http://www.mywebsite.com/paypal/express/cancel/',
    'INVNUM' => '000000099',
    'SOLUTIONTYPE' => 'Sole',
    'GIROPAYCANCELURL' => 'http://www.mywebsite.com/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'http://www.mywebsite.com/checkout/onepage/success/',
    'BANKTXNPENDINGURL' => 'http://www.mywebsite.com/checkout/onepage/success/',
    'SHIPPINGAMT' => '8.20',
    'ITEMAMT' => '170.49',
    'TAXAMT' => '39.31',
    'BUSINESS' => NULL,
    'NOTETEXT' => NULL,
    'EMAIL' => 'my@email.it',
    'FIRSTNAME' => 'myFirstName',
    'LASTNAME' => 'myLastName',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => 'mySuffix',
    'COUNTRYCODE' => 'IT',
    'STATE' => 'MI',
    'CITY' => 'Milano',
    'STREET' => 'Viale Milano',
    'ZIP' => '22222',
    'PHONENUM' => '+39 3333333333',
    'SHIPTOCOUNTRYCODE' => 'IT',
    'SHIPTOSTATE' => 'MI',
    'SHIPTOCITY' => 'Milano',
    'SHIPTOSTREET' => 'Viale Milano',
    'SHIPTOZIP' => '22222',
    'SHIPTOPHONENUM' => '+39 3333333333',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'myFirstName myLastName mySuffix',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '***_',
    'PWD' => '**__',
    'SIGNATURE' => '_***',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-5YJ0617902452323T',
    'TIMESTAMP' => '2016-10-22T07:27:34Z',
    'CORRELATIONID' => '1cfa00b8336e2',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '26106709',
  ),
) {"is_exception":false} []

As you can see the two addresses are exactly the same and related to the shipping address selected in Magento. The default billing address in Magetno is not present here.

Hope I was clear. Please do not hesitate to ask for further information.
Thanks,
Pierale

**Comment by YevSent** [comment]
Hi, @PierAlex, sorry for a delay with answer.

For now, this is an expected behavior, when a customer selects shipping address, billing address is also selected the same as shipping in the background (even if the customer has default billing address).
But, on the develop branch we added an option, which allow changing a billing address on the Payment step for all available payments.

This option also will be available for 2.1.x version after ticket MAGETWO-55612 will be completed.

**Comment by PierAlex** [comment]
Thanks Ievgen, i'll wait for that release.
PierAle

**Comment by YevSent** [comment]
Fix for this issue already backported and will be available in Magento 2.1.4 version. If issue will be still reproducible, please, be free to reopen it.

**Comment by Styopchik** [comment]
2.1.5. Still having issue.

**Comment by roseofgold** [comment]
2.1.6 Still looking for the ability to have different billing address for the Paypal Payments Standard (Website Payments Standard equivalent)

**Comment by dharake** [comment]
I am experiencing the same issue with a Stripe payment module. I thought it may be the vendor, but is this a Magento issue? V2.1.4

**Comment by Drakhunter** [comment]
V2.1.7 still having this issue. billing address is set to shipping address

**Comment by heyepic** [comment]
Ditto on 2.1.7. Any plans to fix? Is there an available work-around?

**Comment by david-fiaty-cko** [comment]
+1

**Comment by btwq** [comment]
+1

**Comment by michaeltimm81** [comment]
For everybody who needs a quick fix for this, this can be done by adding the following core files to your theme and add these lines:

Magento_Paypal/layout/checkout_index_index.xml:
```
<item name="methods" xsi:type="array">
    ...
    <item name="paypal_express" xsi:type="array">
        <item name="isBillingAddressRequired" xsi:type="boolean">true</item>
    </item>
</item>
```

Magento_Paypal/web/template/payment/paypal-express-in-context.html:
```
<div class="payment-method-content">
    ...
    <div class="payment-method-billing-address">
        <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
        <!-- ko template: getTemplate() --><!-- /ko -->
        <!--/ko-->
    </div>
    <div class="checkout-agreements-block">
    ...
</div>
```

Magento_Paypal/web/js/action/set-payment-method.js (two occurences):
```
payload = {
    ...,
    billingAddress: quote.billingAddress()
```

Note that this will only work for the default checkout page, not for the Paypal Express Checkout page.

**Comment by silversil** [comment]
Is possible that this bug isn't fixed yet? 
I have the same issue on 2.2.2 
This is unacceptable!!
