### ISSUE TITLE
grunt exec:<theme>

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#6943]
according to [Compile LESS with Grunt docs](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html)

```
grunt exec:<theme>
```

Republishes symlinks to the source files to the `pub/static/frontend/<Vendor>/<theme>/<locale>` directory.

If your less file contains an `@import` statement it will copied to `pub/static/frontend/<Vendor>/<theme>/<locale>` instead of being symlinked

**Comment by tkacheva** [comment]
@slackerzz thanks for reporting. What is your Magento version?

**Comment by tkacheva** [comment]
Internal issue MAGETWO-59579

**Comment by slackerzz** [comment]
I'm running 2.1.1

**Comment by eug123** [comment]
Hi @slackerzz,
Files are published as copies in case they were preprocessed somehow, please compare your original less source and its' published copy.

**Comment by slackerzz** [comment]
I've compared the two files and they are different, under `app/code/design/frontend/<Vendor>/<theme>/css/source` my less files contains some:

`@import "dir/_mypartial"`

while in `pub/static/frontend/<Vendor>/<theme>/<locale>` these imports became:

`@import "dir/_mypartial.less"`

but why? It doesn't make sense http://lesscss.org/features/#import-directives-feature

**Comment by eug123** [comment]
@slackerzz yes you are right, you can import files without extension.
But currently magento processes `@import` directives so to find respective file and rebuilds `@import` using actually found file path with extension.
So to have symlinks you need to include .less extension to the path and use single quotes 
(i.e. `@import 'dir/_mypartial.less';`).
Thanks

**Comment by slackerzz** [comment]
Maybe It would be nice to include such information in the docs. I thought I was using standard LESS, instead we have a customized version. Each day I discover a different behavior from the standard LESS language, like https://github.com/magento/magento2/issues/4218 or https://github.com/magento/magento2/issues/2264

**Comment by veloraven** [comment]
I'm closing this issue as it was fixed in develop branch.
