### ISSUE TITLE
Can't overwrite translations with $key === $value

### ISSUE THREAD

**Issue by bpoiss** [magento/magento2#6944]
I have a third party extensions that translates

> "Login","Login-Name"

If I want to override this translation with

> "Login","Login"

it will not work because in `magento/Framework/Translate.php:286` the check `$key === $value` just lets the translation be ignored. So I can not override translations from 3rd party if the resulting translations key should equal the value.

**Comment by veloraven** [comment]
@bpoiss thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
