### ISSUE TITLE
Cannot override standard adminhtml theme in Magento 2.1.1 Enterprise Edition

### ISSUE THREAD

**Issue by trebb0r** [magento/magento2#6947]
### Preconditions

1. Magento 2.1.1 Enterprise Edition
### Steps to reproduce

1. Created an adminhtml theme following these steps: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/admin_theme_create.html
2. Created a module to activate the adminhtml theme following these steps: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/admin_theme_apply.html
3. Set deploy:mode:set to developer (as described in the devdocs guide).
4. Cleared var folder.
5. Went to backend URL.
### Expected result

1. The custom adminhtml theme should load.
### Actual result

1. The custom adminhtml theme did not load, instead only the standard Magento/backend theme via the vendor folder.

I only have this problem since Magento 2.1.1 Enterprise Edition. Previous Magento 2.x Enterprise Editions and also Magento 2.1.1 Community Edition are working fine.

On a side note: I could also not override the standard adminhtml Magento backend files in app/design/adminhtml/Magento/backend as it still would generate static-files via the vendor folder.

**Comment by veloraven** [comment]
@trebb0r thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by trebb0r** [comment]
Ok, thank you for the information, the issue will be reported via the support portal!
