### ISSUE TITLE
Invalid tags in authentication-popup.html

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6949]
The file `module-customer/view/frontend/web/template/authentication-popup.html` has an excess div tag.
This is mistake?
### Info

| Q | A |
| --- | --- |
| Magento version | 2.1.1 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by sevos1984** [comment]
This has a fix in develop branch https://github.com/magento/magento2/pull/6280
