### ISSUE TITLE
Multi-store discrepancy for Braintree Payment gateway

### ISSUE THREAD

**Issue by trichter01** [magento/magento2#6950]
### Preconditions
1. I am using Magento 2 with two active store-fronts. Store 1 and Store 2. Each has a separate Braintree merchant account instant assigned and configured, functioning properly on the front-end of each store. However, when placing an order in the back-end, The payment seems to go to Store 1's instant account even when Store 2 is set as the purchase point.
2. I am using Magento version 2.0.9, PHP 7, Braintree Payment, Fooman Order Number Customiser
### Steps to reproduce

To recreate the issue: 
Login into the site back-end > Sales > Orders > Create New Order > Create New Customer > Select Store View (in this case Store 2) > Add Products > Input Customer information / payment info. > Submit Order

The order gets placed with the next available ID number from Store 1 but shows the purchase point as Store 2. The payment, however, goes into Store 1.
### Expected result

The payment should be going into the instant of Store 2. 
### Actual result

The actual result is the payment goes into the instant of Store 1

**Comment by YevSent** [comment]
Hi, @trichter01, thanks for reporting. We have created internal ticket MAGETWO-59892.

**Comment by trichter01** [comment]
@joni-jones, thanks for the acknowledgement. I have disabled the Order Number Customiser module to make sure the module isn't a factor. In conclusion, that module is irrelevant to the issue here..

**Comment by YevSent** [comment]
@trichter01, after some debugging I've found what `\Magento\Framework\App\Config\ScopePool::getScope` doesn't return correct scope.

**Comment by trichter01** [comment]
@joni-jones, is this possibly the same issue? https://github.com/magento/magento2/issues/2857

**Comment by YevSent** [comment]
No isn't, #2857 relates to php doc types.

**Comment by trichter01** [comment]
ok, what's the next step for a solution?

**Comment by trichter01** [comment]
Has there been any success towards a resolution for this issue?

**Comment by trichter01** [comment]
Since posting this issue, I have updated to Magento 2.1.1. This bug has not been resolved yet.

**Comment by trichter01** [comment]
I have updated again to Magento 2.1.2 but still resolution. Any insights as to when the solution will be provided?

**Comment by YevSent** [comment]
Hi, @trichter01, this issue will be fixed according to priority.

**Comment by magento-engcom-team** [comment]
@trichter01, thank you for your report.
We've created internal ticket(s) MAGETWO-59892 to track progress on the issue.

**Comment by YevSent** [comment]
Fixed in 2.1.11 release.
