### ISSUE TITLE
csv import validation of attribute set

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#6951]
### Preconditions
1. M 2.1.1 
### Steps to reproduce

1. Import some products by CSV
2. Update these products with different attribute set and new attributes
### Expected result

1. Raise error that attribute set change is not supported (or make support for that)
### Actual result

1. Products are updated without any warning. 
2. Products attributes that are only in new attribute set are not modified without any warning

**Comment by Sergeacc** [comment]
@magexo We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
