### ISSUE TITLE
getLastAddedItem() returns an old item(added before needed)

### ISSUE THREAD

**Issue by HellgaM** [magento/magento2#6953]
Hello,
It's appeared that  $this->cart->getQuote()->**getLastAddedItem**() function returns and old value even after cart has been saved.

I've added a log file into \Magento\Checkout\Controller\Cart\Add execute function after
 $this->cart->save(), in case cart was empty getLastAddedItem() returns empty value, 
in other case log will show previously added item but not current one.

### Preconditions

1. Magento version is 2.1.0
2. PHP 7
3. MySql 5.6

### Steps to reproduce

1. add a log file into \Magento\Checkout\Controller\Cart\Add execute function after  $this->cart->save()
2. clear cookies
3. add a few configurable products to the cart
4. check getLastAddedItem() returned item

### Actual result
getLastAddedItem() returns an old item(added before needed)

### Expected result

1. getLastAddedItem()  should return just added item to the cart

Thank you for your time.

**Comment by magento-engcom-team** [comment]
@HellgaM, thank you for your report.
We've created internal ticket(s) MAGETWO-81419 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@HellgaM, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by IsakViste** [comment]
@magento-engcom-team  Having this issue in Magento 2.4.6-p4 and 2.4.7-p3, any updates on the status of MAGETWO-81419 ?
