### ISSUE TITLE
Stores all use same return path when "send email" from Order page

### ISSUE THREAD

**Issue by shanevbg** [magento/magento2#6954]
Using Magento 2.1.1 with multiple stores, when I send a customer email from the order page, it uses the same return path as the default (all other emails get routed correctly, and the correct email is in the order, just not being used as the sender/return path)
### Preconditions
1. PHP Version 7.0.8-0ubuntu0.16.04.3
2. MySql 5.7.15
3. Magento 2.1.1
### Steps to reproduce
1. Have more than one store in Magento setup properly to send email from a different address
2. Make an order from the second store to ensure it uses correct email
3. Go into dashboard to view last orders  and select order from secondary store(or go to <adminURL>/sales/order/view/order_id/<ORDERID>)
4. Send email to customer (I use a test account)
5. Check email that customer received
### Expected result
1. Email should use same email address as in the body of email & the magento store that the order originated from uses for sending emails, not the default email address
### Actual result
1. Email has default website magento email address, not store specific
2. I'd include logs for email, but am unclear as to how to get those.
3. Email body includes links to store 1 as well as store 2 e.g.
   `<a class=3D"logo" href=3D"https://`**[STORE_2]**`/" style=3D"color: #1979c3; text-decoration: none;">`

`<img width=3D"180" height=3D"52" src=3D"https://`**[STORE_1]**`/pub/static/frontend/Magento/luma/en_US/Magento_Email/log=
o_email.png" alt=3D"Kratom Bulk Powders" border=3D"0" style=3D"border: 0; h=
eight: auto; line-height: 100%; outline: 0; text-decoration: none;"></a>
`

**Comment by olysenko** [comment]
Hi, internal ticket was created MAGETWO-59719

**Comment by mohsinahmed22** [comment]
I am also facing this issue ? any fix yet?

**Comment by Sanfam** [comment]
@olysenko , is there a good way to get a status update once a patch is created to address this issue?

**Comment by ntoombs19** [comment]
I can confirm this issue still exists in 2.1.3

**Comment by briannambui** [comment]
Still having issues. Is there a fix?

**Comment by ntoombs19** [comment]
@briannambui - Yes you can find a patch in this issue https://github.com/magento/magento2/issues/8117

**Comment by lee586** [comment]
Experiencing same issue with Magento CE 2.1.8

**Comment by magento-engcom-team** [comment]
@shanevbg, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by aashworth-ldg** [comment]
We are experiencing this issue on EE 2.1.9, following the same steps as outlined in this issue (and a referencing issue #8066).  

Can this be re-opened?

**Comment by kkdg** [comment]
It's still happening, why @magento-engcom-team can't you reproduce it while many others can?

**Comment by jmbatty** [comment]
I too have the same behavior on 2.2.2
I have 3 store fronts / websites under the same magento install, and order confirmations for the store front #2 or #3 will not use the email address of the default (#1) store. which is for me sales@example.com.

**Comment by pickl3d** [comment]
we also have this issue, how are we supposed to run a business when half our customers don't get an order email @magento-engcom-team ?? re-open please!

**Comment by hostep** [comment]
@magento-engcom-team: we can reproduce this on Magento 2.2.3 and 2.1.11.

There is however one crucial configuration missing in the initial post, you have to enable the following setting to be able to reproduce it:
Stores > Configuration > Sales > Sales Emails > General Settings > Asynchronous sending

Can you guys try to reproduce it with this config setting enabled? And then use the cronjobs to trigger sending the mails.
Thanks!

@ all who suffer from this bug, you can avoid it by disabling the above setting, or using the fix from @WMV-SYSTEMS: https://github.com/magento/magento2/issues/8117#issuecomment-272242715

**Comment by zack6849** [comment]
@magento-engcom-team still seeing this issue on our store as well, we have hot patched the code and had it in place for months, but how long are you going to keep a bug such as this in your product? Multistore is a mess in many places and in dire need of better support
