### ISSUE TITLE
product update by csv does not remove image

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#6956]
### Preconditions
1. CE,EE 2.1.1 
### Steps to reproduce

1. Import product by CSV with more additional_images separated by comma
2. Update product by CSV with less images additional_images than before
### Expected result

1. Non existing image in additional_images is removed from product
### Actual result

1. Image is not removed now

**Comment by odubovyk** [comment]
Cannot reproduce. Description is pour and not enough.
You create product with images, then export it? Then modify CSV and import?
What is the _Import Behavior_ add/update or replace and so on.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
