### ISSUE TITLE
"EAV types and attributes" cache type defined but not used

### ISSUE THREAD

**Issue by Marko-M** [magento/magento2#696]
Please allow me to describe EAV cache type situation in current M2 codebase, something I assume was ported from Magento 1 because the same situation exists there.

Issue is that we have "EAV types and attributes" cache type with "EAV" tag and "eav" type identifier defined, but not used. The only code that should be saving cache with this cache tag/identifier is \Magento\Eav\Model\Config::_initEntityTypes():

https://github.com/magento/magento2/blob/master/app/code/Magento/Eav/Model/Config.php#L267-L324

and this function is never referenced. Almost the same situation is with current M1 codebase. Am I missing something?

Thanks

**Comment by vpelipenko** [comment]
This issue was fixed and already available here in public GitHub. Ticket: MAGETWO-30485.

**Comment by vpelipenko** [comment]
We are going to close this issue. If you have any objections, please, let us know.
