### ISSUE TITLE
Custom cronjobs not running without flushing cache

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#6962]
### Preconditions
1.  Magento 2.1.1
2.  PHP 7.0.11
### Steps to reproduce
1. Create a custom cronjob and assign it to default group or create a new group and assign it
2. Set it to run for 1 min
3. Make sure Magento cron is setup correctly and running every 1 min
### Expected result
1. Custom cronjob should run every 1 min
### Actual result
1. Custom cronjob will run only a few times in a row (1-3 in my tests) and then stop running (Magento cron still runs every 1 min)
2. If you flush the cache php bin/magento cache:flush then custom cron starts running again but stops after 1-3 times again
3. After further testing it seems if I assign it to index group it will always run 5 times in a row and then it stops (as well as indexer jobs stop too), once cache is flushed it will restart again but only for 5 times again.

**Comment by stevekem** [comment]
https://github.com/magento/magento2/issues/2672

**Comment by simonrl** [comment]
Are there any news on this issue?

**Comment by magento-engcom-team** [comment]
@stevekem, thank you for your report.
The issue is already fixed in 2.2.1
