### ISSUE TITLE
Admin panel add product is not working when we change attribute set

### ISSUE THREAD

**Issue by sourabhmodi60** [magento/magento2#6967]
I have created a couple of attribute sets and now in Add product section when I switch the product attribute set the loader keeps on loading in Windows 10 edge browser.

The error in console is : Unable to get property 'product_form' of undefined or null reference

Magento version : 2.1

**Comment by veloraven** [comment]
@sourabhmodi60 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please note, that Magento does not support the operating system you've mentioned. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see  [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
