### ISSUE TITLE
Checkout success page not rendering page title

### ISSUE THREAD

**Issue by amansilla** [magento/magento2#6968]
### Preconditions
1. Magento Enterprise 2.1.1 (didn't test the community version but I guess it has the same problem)
2. Luma Theme is set as default
### Steps to reproduce
1. Add product to cart.
2. Go to checkout.
3. Select any payment.
4. Finish the order.
### Expected result
1. A page title with the following text should be rendered: "Thank you for your purchase!"
### Actual result
1. No page title is rendered.

**Comment by SerhiyShkolyarenko** [comment]
Thank you for reporting. Internal issue is MAGETWO-59807.

**Comment by SerhiyShkolyarenko** [comment]
@amansilla MAGETWO-59807 is delivered to develop branch. Closing the issue.
