### ISSUE TITLE
REST call to products of a category in store

### ISSUE THREAD

**Issue by ikdekker** [magento/magento2#6970]
### Preconditions
1. Have Magento 2.1.1 installed
### Steps to reproduce
1. Add products to different stores
2. Place products in the category.
3. Call /rest/V1/categories/:categoryID/products?storeId= + STOREID
### Expected result
1. List of products in this category and this storeid will be returned.
### Actual result
1. Return was empty array, [].

I have altered the code in the module-catalog/Model/CategoryLinkManagement.php. I changed the getAssignedProducts functions first lines to:
        ```
$sId = isset($_GET['storeId']) ? $_GET['storeId'] : null;
        $category = $this->categoryRepository->get($categoryId, $sId);

```

Now it does return a list with the appropriate products.
```

**Comment by olysenko** [comment]
Hi. thanks for your report. 
In general product to category relation is not store or website dependent. So it doesn't make sense to retrieve store ids because we don't have such 3D relation category- product- store. This service filters product list according to products attributes(such as visibility, status), website(specified in request url path) etc. 
You can retrieve the list of assigned products to category in scope of definite website by specifying this website url in request.
This issue is closed

**Comment by ikdekker** [comment]
Why then is there a storeId available parameter in the API?

By specifying the website url in the request, do you mean i can do:

subwebshop.com/rest/V1/categories/:categoryID/products
instead of:
mainwebshop.com/rest/V1/categories/:categoryID/products?storeId=:subwebshopId
because the former request doesn't seem to yield results either.

If my perception is wrong, could you supply me with an example? 

Thank you.

**Comment by olysenko** [comment]
1) Sorry , service  catalogCategoryLinkManagementV1  doesn't contain any store id (see prove in http://devdocs.magento.com/swagger/index.html)
2) Regarding websites filtering:
I meant situation you have Default Website  with url somewebshop.com with some products.  After you add Test Website and assigned some products to it. You can configure url for this Test Website like somewebshop.com/website/test.
As the results:
usage in request url: somewebshop.com/rest/V1/categories/:categoryID/products
returns products assigned for the Default Website and from other side using url
somewebshop.com/website/test/rest/V1/categories/:categoryID/products  
returns products assigned to Test Website
