### ISSUE TITLE
customer order emails are not being sent

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#6975]
### Preconditions
1. Apache 5.6 
2. Magento 2.2.0-dev
### Steps to reproduce
1. order product. 
2. 
3. 
### Expected result

1. Customer should get email 
2. admin should get email. 
   ### Actual result
   
3. no emails are sent for order.

**Comment by veloraven** [comment]
@dmcmillin thank you for your feedback.
Is your mail server set up properly?

**Comment by lhsatch** [comment]
Have you setup your cron.

**Comment by dmcmillin** [comment]
Yes, it works just fine.

**Comment by veloraven** [comment]
@dmcmillin did you answer for my question or for the question from @lhsatch ?
Please provide information about your environment: PHP version, MySQL version, OS. As I can see from the description you use Apache as web server.

**Comment by dmcmillin** [comment]
I found out the issue. My VPS uses Exim and m2 doesn't support it very well. It sends out emails without a true -f flag and my host then sends it out with mixed headers which causes it to be denied by most email host as spam.

**Comment by odubovyk** [comment]
I think this can be closed.

**Comment by dmcmillin** [comment]
Yeah. I thought that it was two different issues but it seems to be only one. Sorry
