### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by JananiKrishnan** [magento/magento2#6976]
### Preconditions
1. Magento CE 2.07 installled
### Steps to reproduce
1. Type "keyword with product name" in search box.
2. In auto suggestions, select suggestion with exact product name
### Expected result
1. The page load with the search results
### Actual result
1. The page loads with previous content not with the current search result

**Comment by NSanthoshpriya** [comment]
Hey, I'm also facing the same issue..
What is the solution for it?
Can you provide the solution ASAP?

**Comment by JananiKrishnan** [comment]
HI ,
This issue is fixed. please refer the following link for fix.

https://github.com/magento/magento2/commit/905c32ae0a2dc57219e5cae50603ca3ada1ffdb5

**Comment by miakusha** [comment]
closed as duplicate #3657.
