### ISSUE TITLE
Performance: Issue with a lot of configurable with lots of images

### ISSUE THREAD

**Issue by paales** [magento/magento2#6979]
### Preconditions

1. 2.1.2
### Steps to reproduce

1. Create a lot of configurables with simples with images.
2. Load a category page.
### Expected result

1. Loads only the media gallery images required and doesn't spend more than a second per query on the media gallery images.
### Actual result

1. Loads all images and spends about a second per query, resulting in 20000ms added to the page load.

Below the following line: https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L2178-L2181

Add

``` PHP
$select->where('entity.entity_id IN(?)', $this->getLoadedIds());
```

**Comment by choukalos** [comment]
Tracking internally as MAGETWO-59138

**Comment by kandy** [comment]
Duplicate #6850

**Comment by paales** [comment]
@kandy Thanks for the reference!
