### ISSUE TITLE
Decoupling of layout definitions

### ISSUE THREAD

**Issue by EliasZ** [magento/magento2#698]
With the whole new spirit of loosely coupling the Magento 2 code base, maybe a good look can be taken at the layout definitions and its dependencies. For example, opening `Magento/Backend/view/adminhtml/layout/default.xml` reveals the following definitions which can be moved:

    <link src="Magento_Rule::rules.js"/>  

The following can be moved to Magento_RequireJS:

        <link src="requirejs/require.js"/>
        <link src="mage/requirejs/resolver.js"/>
    </head>
    [...]
    <block name="require.js" class="Magento\Backend\Block\Page\RequireJs" template="Magento_Backend::page/js/require_js.phtml" />
    [...]
    <referenceContainer name="after.body.start">
        <block class="Magento\RequireJs\Block\Html\Head\Config" name="requirejs-config"/>

More in after.body.start:

    <block class="Magento\Translation\Block\Js" name="translate" template="Magento_Translation::translate.phtml"/> 

And so forth.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30486

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Decoupling-of-layout-definitions/idi-p/47126).
