### ISSUE TITLE
Scheduled Design Update not being applied on product page

### ISSUE THREAD

**Issue by timbits07** [magento/magento2#6980]
Magento 2.1.1 
### Steps to reproduce

1. After building a custom theme create a child theme that uses a different color scheme than the parent. 
2. Apply that child theme to a particular category of products so that it has the alternate color scheme.
3. Either check the box under the category design update that applies the child theme to all products in that category or apply a scheduled design update on said product that applies the child theme to the individual product.
### Expected result

1.  The product should have the same alternate color scheme as the category with the child theme. 
### Actual result

1. The product still uses the parent theme despite entries in the database for product attribute 'custom_design' directing the product to use the child theme.

Am I missing a configuration somewhere.  The use of an alternate theme was easy with the category but it has been impossible at the product level so far.

**Comment by ilol** [comment]
Didn`t you setup cron?

**Comment by timbits07** [comment]
I have a local development environment, a staging environment and a production one.  The only staging and production environments have crons set up and they are not showing the design update on product pages either.

I understand that the scheduled design update would depend on the cron, but the feature in my screenshot below doesn't seem like it would.
https://cl.ly/1g1E2h142W0q

**Comment by sevos1984** [comment]
Apply Design to Products doesn't need cron to be applied. I have tried using default luma and blank themes and everything works fine for me, could you try your case with luma and blank themes?

**Comment by timbits07** [comment]
It works correctly with the Luma theme. So obviously I configured something in my child theme in such a way that it doesn't pick up the design change styles on the product page.

**Comment by sevos1984** [comment]
You're right and will be hard for me to find out. I'd suggest asking [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/) to find where the problem is and if there an issue create a new one. Thanks
