### ISSUE TITLE
Unable to instantiate the catalog import uploader with $filePath set

### ISSUE THREAD

**Issue by brideo** [magento/magento2#6981]
## Preconditions
- Magento 2.0.x or 2.1.0 is installed CE or EE
- Module is setup with class and `Magento\CatalogImportExport\Model\Import\UploaderFactory` in the construct
## Steps to reproduce
- Using the factory pattern you instantiate the class `Magento\CatalogImportExport\Model\Import\Uploader` with `$filePath` defined
## Actual and Expected result
- Exception is thrown because `$this->_directory` is not set
- Class should be instantiated 
## Additional information

So there is a bug in this class:

`Magento\CatalogImportExport\Model\Import\Uploader`:

I am using this and instantiating it within my own class like so:

```
    /**
     * Importer constructor.
     *
     * @param Config\File $file
     */
    public function __construct(File $file, UploaderFactory $uploaderFactory) {
        $this->uploader = $uploaderFactory->create(['filePath' => $file->getFilePath()]);
    }
```

The `__construct` of `Magento\CatalogImportExport\Model\Import\Uploader` looks like this:

```
    public function __construct(
        \Magento\MediaStorage\Helper\File\Storage\Database $coreFileStorageDb,
        \Magento\MediaStorage\Helper\File\Storage $coreFileStorage,
        \Magento\Framework\Image\AdapterFactory $imageFactory,
        \Magento\MediaStorage\Model\File\Validator\NotProtectedExtension $validator,
        \Magento\Framework\Filesystem $filesystem,
        \Magento\Framework\Filesystem\File\ReadFactory $readFactory,
        $filePath = null
    ) {
        if ($filePath !== null) {
            $this->_setUploadFile($filePath);
        }
        $this->_imageFactory = $imageFactory;
        $this->_coreFileStorageDb = $coreFileStorageDb;
        $this->_coreFileStorage = $coreFileStorage;
        $this->_validator = $validator;
        $this->_directory = $filesystem->getDirectoryWrite(DirectoryList::ROOT);
        $this->_readFactory = $readFactory;
    }
```

You can see that the `_setUploadFile` method is called which uses `$this->_directory` which has not been set yet, unless I'm missing something.

Cheers!

**Comment by veloraven** [comment]
@brideo thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by brideo** [comment]
Hey I'm running Magento 2.0.7 EE, I've found a workaround and don't have time to re-format sorry.

**Comment by veloraven** [comment]
@brideo please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by brideo** [comment]
I have a work around so it won't be necessary, however this is an issue on CE too:

https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php#L107

https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php#L173

**Comment by brideo** [comment]
I will update the ticket now.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#51
