### ISSUE TITLE
Swatches from sold out items visible on store front

### ISSUE THREAD

**Issue by ifekaj** [magento/magento2#6982]
### Preconditions

1. Magento 2.1.1
2. PHP 7.0.10
3. Apache 2.4.6
4. MySQL 5.7.16
5. CentOS 7.2.1511
### Steps to reproduce

1. Simple product, which is a part of a configurable product gets sold out, or I manually change stock quantity to 0 and stock status to out of stock
### Expected result

1. Swatch for the item that is out of stock should not be visible on the product page
### Actual result

1. Swatch for the item that is out of stock is still visible on the product page. If I try to add this item to cart I get an error "This product is out of stock."

Disabling the product manually solves this problem. Please note that this issue existed even on version 2.0.9. Products that went out of stock while I was running versions previous to 2.0.9 are working properly and do not need to be manually disabled.

**Comment by olysenko** [comment]
Hi, thank you for report. We already have this issue [#5558](https://github.com/magento/magento2/issues/5558) Internal ticket MAGETWO-58328 already created. 
Closed as an duplicate
