### ISSUE TITLE
Area code is not set

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#6986]
bin/magento setup:upgrade

```

  [Magento\Framework\Exception\SessionException]                       
  Area code not set: Area code must be set before starting a session.  






  [Magento\Framework\Exception\LocalizedException]  
  Area code is not set                              



setup:upgrade [--keep-generated] [--magento-init-params="..."]
```

**Comment by veloraven** [comment]
@craigcarnell thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
