### ISSUE TITLE
Image delete issue

### ISSUE THREAD

**Issue by kumarancontus** [magento/magento2#6987]
I am currently working in Magento2.1.1 for product image delete from frontend but after I deleting the image pro-grammatically from frontend its not removing from media folder. Also I am using the below code

Code : 

 public function removeImageForProduct($productId, $imagesIds) {
        if (count ( $imagesIds ) >= 1) {
            array_unique ( $imagesIds );
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance ();
            $objectGallery = $objectManager->get ( 'Magento\Catalog\Model\ResourceModel\Product\Gallery' );
            $objectGallery->deleteGallery ( $imagesIds );

```
    }
}
```

**Comment by shanevbg** [comment]
@kumarancontus this looks like it's the same as #6955

**Comment by kumarancontus** [comment]
I had done it like below and it worked fine. Please try in your end

Code :

public function removeImageForProduct($productId, $imagesIds) {
if (count ( $imagesIds ) >= 1) {
array_unique ( $imagesIds );
$objectManager = \Magento\Framework\App\ObjectManager::getInstance ();
$product = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);
$images = $product->getMediaGalleryImages();

```
    $objectGallery = $objectManager->get ( 'Magento\Catalog\Model\ResourceModel\Product\Gallery' );
    $objectGallery->deleteGallery ( $imagesIds );
    $mediaDirectory = $objectManager->get('Magento\Framework\Filesystem')->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA);
    $mediaRootDir = $mediaDirectory->getAbsolutePath();
    foreach($imagesIds as $image){
        foreach($images as $productImage){

            if($productImage['id'] == $image){

              $imageFilePath = $productImage['file'];

              $mediaRootDirectory = $mediaRootDir.'catalog/product';
    if ($this->_file->isExists($mediaRootDirectory . $imageFilePath))  {

        $this->_file->deleteFile($mediaRootDirectory . $imageFilePath);
    } }
        }
    }
}
```

}

**Comment by veloraven** [comment]
I'm closing this issue as duplicate, please create a new one with more detailed description if it is needed.
