### ISSUE TITLE
Do not use _addContent in controllers

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#699]
From Magento 1.x we have a lot controllers that use _addContent. This method is fires after running loadLayout. As result we haven't ability to use action directive from layout files to use some manipulations, as example change template file for block (described [there](https://wiki.magento.com/display/MAGE2DOC/Managing+Page+Markup+Using+XML+Layout#ManagingPageMarkupUsingXMLLayout-Task1%3APageColumnsCustomization)).

I propose mark this method as deprecated and replace same places to layout updates.

List of this places:
https://github.com/magento/magento2/search?q=_addContent

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30487

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Do-not-use-addContent-in-controllers/idi-p/47122).
