### ISSUE TITLE
REST API Documentation

### ISSUE THREAD

**Issue by harsh-persistent** [magento/magento2#6991]
### Preconditions

1. Magento version 2.1
2. 
### Steps to reproduce

1. Create a 'product' using /V1/products API with name and sku.
2. It should throw an error.
3. 
   ![image](https://cloud.githubusercontent.com/assets/17979940/19347900/dc7fc358-9168-11e6-8940-e48d0f0c0d10.png)
### Expected result

1. As per the swagger JSON, only sku is mandatory field. So it should have created a product with sku and name.
### Actual result

1. It throws an error
   ![image](https://cloud.githubusercontent.com/assets/17979940/19347916/f9115e78-9168-11e6-8a5e-e0565da97c0a.png)

Does Magento have comprehensive API documentation or swagger JSON returned should be considered as the API doc?

**Comment by keharper** [comment]
The Swagger documentation doesn't list the minimum fields for a request--it includes all the possibilities. At minimum, a `sku`, a `name`, and an `attribute_set_id` must be specified for this call.  For example:

```
{
 "product" : {
   "sku": "xyz123",
   "name": "Something",
   "attribute_set_id": 4
}
}
```

The value 4 represents the default attribute set.

**Comment by geon** [comment]
Then, `sku`, `name`, and `attribute_set_id`should not be marked as optional. I'd like to be able to trust official documentation.

If the requirements are more complicated than that, *please write it down somewhere*.

**Comment by RomanKrut** [comment]
@harsh-persistent Hi, thanks your for reporting this issue. Internal ticket was created MAGETWO-70422.

**Comment by magento-engcom-team** [comment]
@harsh-persistent, thank you for your report.
We've created internal ticket(s) MAGETWO-70422 to track progress on the issue.

**Comment by drpayyne** [comment]
> As per the swagger JSON, only sku is mandatory field.

@keharper Where does the Swagger JSON define the mandatory fields? Or is the issue outdated and fixed?

**Comment by keharper** [comment]
@drpayyne The Swagger UI has changed over time. When you click **Model**, you can see it lists all the possible attributes, but it doesn't say which are required, except for `sku`, which has a red asterisk. The other attributes don't.

![swagger-screen-shot](https://user-images.githubusercontent.com/11652541/66491573-95b2aa00-ea78-11e9-8ebb-0243c1896ba9.png)
