### ISSUE TITLE
Purchase Date is not displaying in sales order admin grid after datamigration from Magento 1.9.2.3 to Magento 2.1.0

### ISSUE THREAD

**Issue by NNarendraReddy** [magento/magento2#6993]
### Preconditions
migrate from Magento 1.9.2.3 to Magento 2.1.0

### Steps to reproduce
I checked in
1.`vendor\magento\module-sales\view\adminhtml\ui_component\sales_order_grid.xml` also

```
<column name="created_at" class="Magento\Ui\Component\Listing\Columns\Date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filter" xsi:type="string">dateRange</item>
                    <item name="component" xsi:type="string">Magento_Ui/js/grid/columns/date</item>
                    <item name="dataType" xsi:type="string">date</item>
                    <item name="label" xsi:type="string" translate="true">Purchase Date</item>
                    <item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:MM:SS A</item>
                </item>
            </argument>
        </column>
```
1. In database level column name is `created_at`.<br/>
2. I did reindex also but its not displaying.<br/>
   ![purchasedate](https://cloud.githubusercontent.com/assets/22813559/19352740/9bb70e2e-917e-11e6-8fbe-b9f8e6bce297.png)

### Actual Result
3. For migrated orders only its not showing Purchase Date. If i create new order then purchase date is coming.

### Expected Result
purchase date is showing for migrated orders

**Comment by magento-engcom-team** [comment]
@NNarendraReddy thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by magento-engcom-team** [comment]
Hi @NNarendraReddy we can not reproduce the issue on clean magento  instance. Please, report the issue to the https://github.com/magento/data-migration-tool repository is there is an issue in the tool
