### ISSUE TITLE
Typo in message when removing coupon from cart

### ISSUE THREAD

**Issue by devonto** [magento/magento2#6994]
There is a typo in the message being displayed to a user when removing a coupon code. One 'l' when it should be two in 'cancelled'.

`\vendor\magento\module-checkout\Controller\Cart\CouponPost.php` line 137 is currently:

`$this->messageManager->addSuccess(__('You canceled the coupon code.'));`

And should be:
`$this->messageManager->addSuccess(__('You cancelled the coupon code.'));`

**Comment by shanevbg** [comment]
http://grammarist.com/spelling/cancel/
In American English, the verb cancel is usually inflected canceled and canceling—with one l. This is not a rule, however, and exceptions are easily found. In varieties of English from outside the U.S., including Canadian, British, and Australian English, cancelled and cancelling are the preferred spellings.

**Comment by devonto** [comment]
@shanevbg Thanks.

Might it then be more appropriate to build an official en_GB translation pack for these nuances?

**Comment by shanevbg** [comment]
@devonto I would think that would make more sense, than claiming it's "consistent" to use British English piecemeal, for example  colour and color (there are many more examples, but I know Magento uses "color" in places).

http://grammarist.com/spelling/color-colour/
Color and colour are different spellings of the same word. Color is the preferred spelling in American English, and colour is preferred in all other main varieties of English.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Typo-in-message-when-removing-coupon-from-cart/idi-p/54648).
