### ISSUE TITLE
payment method custom not to sucess page

### ISSUE THREAD

**Issue by tommoholmes10** [magento/magento2#6996]
I create payment method and Redirect to payment gateway and Redirect to success page
order created but Redirect to shopping cart
**Preconditions**
1. Magento CE Version 2.1.1
2. PHP version 5.6.26-1
3. MySQL version 14.14
4. Macbook pro

**Steps to reproduce**
1. add to cart
2. checkout
3. Redirect to payment gateway
4. Redirect to response page magento
5. Redirect to shopping cart
### Expected result
1. add to cart
2. checkout
3. Redirect to payment gateway
4. Redirect to response page magento
5. Redirect to success page magento
### Actual result

[img]http://i.imgur.com/QK8G5A9.png[/img]
[img]http://i.imgur.com/AJAxkUx.png[/img]
[img]http://i.imgur.com/17d4gxV.png[/img]

**Comment by veloraven** [comment]
@tommoholmes10 thank you for your report.
Could you please describe more detailed steps. As your steps are similar to expected results.
Please also describe actual result.

**Comment by tommoholmes10** [comment]
please check my ss
http://imgur.com/l1hnSQ2
when I check at shopping cart
this item still at shopping cart
http://imgur.com/iVq37U1
I have been add this code
https://github.com/magento/magento2/pull/5625/files
https://github.com/magento/magento2/pull/5807
but still stuck

**Comment by veloraven** [comment]
@tommoholmes10 do I understand correctly that:
**Actual Result:**
(+) Order is created
(+) Success page is open
(-) Ordered product is added to the shopping cart again

**Expected Result:**
(+) Order is created
(+) Success page is open
(+) Shopping cart is empty

If I do not please describe your actual and expected result in this way.
Please also describe your steps in the way like 'open the page', 'click the button'.
Please also note that Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see  [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
