### ISSUE TITLE
suggestion: revise WYSIWYG editor

### ISSUE THREAD

**Issue by phazei** [magento/magento2#700]
Please oh please dump that horrible TinyMCE v3.47.  It produces poorly formatted html that makes it very difficult if you want to edit back and forth via html and wysiwyg.
CKEditor has a much better interface and produces very nice code.

**Comment by verklov** [comment]
Thank you all for your thoughts! Please continue commenting on this as you encounter new ideas. Meanwhile we close this ticket, but continue watching it and taking all your suggestions into consideration.

**Comment by phazei** [comment]
@KLVTZ 
Actually CKeditor supports Code Mirror:
http://ckeditor.com/addon/codemirror
which is pretty slick.

**Comment by KLVTZ** [comment]
@phazei +1 on that! Thanks for pointing that out, that would feel 10x more natural. 
It comes to my attention that maybe we as a community should encourage proper extended code base additions versus just code injections that magento 2 offers in the admin-panel.

**Comment by Frits1980** [comment]
Ok, nice, we all agree. But what is the next step to make this happen? Can I do something to make this happen?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69234

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69234
