### ISSUE TITLE
Braintree doesn't work when PayPal is enabled and no shipping is required

### ISSUE THREAD

**Issue by tehXor** [magento/magento2#7000]
### Steps to reproduce

1. Install Magento 2.1.2
2. Configure Braintree and enable Credit Card as well as PayPal with Braintree
3. In the frontend add only downloadable products to your cart (where no hardware shipping is required)
4. Try to place the order
### Expected result
1. On the selection screen for payment methods you should be able to select credit card as well as PayPal
2. When you select one you should be prompted to enter your billing address
### Actual result
1. On the selection screen for payment methods the loading spinner doesn't finish
2. In the background you can see that none of the braintree methods are loaded
3. There is one error in the javascript log which occurs in /Magento_Braintree/js/view/payment/method-renderer/paypal.js:
   `paypal.js:276 Uncaught TypeError: Cannot read property '0' of undefined`
### Additional Notes
1. When PayPal is disabled but credit card is enabled, credit card works like expected
2. We are in sandbox mode
### Workaround
1. Patch `getShippingAddress` in /Magento_Braintree/js/view/payment/method-renderer/paypal.js in any way that doesn't rely on the existenz of `address.street`
2. Even if the address is completely empty billing data is pulled from PayPal and correctly submitted to Magento, so this workaround seems safe

**Comment by iivashchenko** [comment]
@tehXor, thank you for reporting, but unfortunately, I can't reproduce that issue. I've tried to reproduce it on Google Chrome and, as a result, on checkout I have three payment methods available (PayPal (Braintree),  Credit Card (Braintree) and Check / Money order).

Let me suggest you clear browser cache and try to reproduce that issue again.

**Comment by tehXor** [comment]
Clearing caches doesn't help and when I look at the paypal.js implementation the problem seems logic to me:
When you look at line 298 in the paypal.js ( https://github.com/tehXor/magento2/blob/develop/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/paypal.js#L298 ) you can clearly see, that the shipping address is used as address. And it is also evident, that there are cases, where the system cannot know the shipping address yet: A new/guest user purchases a product where shipping is not required (virtual or downloadable product) and therefore hasn't entered his address anywhere.
In that case line 307 has to throw an exception ( https://github.com/tehXor/magento2/blob/develop/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/paypal.js#L307 ).

Maybe you tested with a logged in user or there was already a shipping address in the session for some other reason?

I have created a super small pull request which fixes the problem: https://github.com/magento/magento2/pull/7077

Let me know if I'm missing something and the reason we are seeing this exception there has a different origin.

**Comment by iivashchenko** [comment]
Hi, @tehXor. Getting back to this issue finally I've reproduced same JS error allowing guest checkout for downloadable products. I've created internal ticket MAGETWO-60572 and linked this GitHub issue to it. Thank you.

**Comment by alena-marchenko** [comment]
Hi @tehXor 

Fix for MAGETWO-60572 tickets is merged to develop branch, closing the issue.
Thank you.

**Comment by saeohioalpha** [comment]
Has this been merged in anywhere? I see it's marked as done in the project: branch [develop] but don't see a merge anywhere. I'm on 2.1.8 and experiencing the same issue. For a guest checkout of a virtual product, going to the checkout page just spins the loader and i get an error (see screenshot).

![screen shot 2017-09-15 at 4 08 52 pm](https://user-images.githubusercontent.com/969559/30501525-da02cc34-9a30-11e7-99d3-f34fb609f7e5.png)

**Comment by korostii** [comment]
Hi @alena-marchenko, Hi @magento-engcom-team, 
Can this be reopened since the bug seems to remain on 2.1.x ?

**Comment by tehXor** [comment]
@korostii last time I check the official fix was in the develop branch, so the question would be if it could be ported to 2.1 branch. Otherwise I guess it will make it 'automatically' to 2.2 and may already be in 2.2 RC. But since this isn't stable I'm also applying my custom patch for every 2.1 update so far which is a little annoying.

**Comment by korostii** [comment]
@tehXor, just a small clarification:
Yes, this fix was merged in  a long time ago and is indeed present on 2.2 RC (one of the commits: https://github.com/magento/magento2/commit/29e6c2e4f4743512cc80c201942696fc78fded9f ).

But when viewing newer fixes please keep in mind that 2.2 branch is now separated and `develop` branch represents the future 2.3 version already.

**Comment by orlangur** [comment]
@korostii according to current processes it shouldn't be reopened but marked with appropriate labels so that anyone interested may work on `2.1-develop` backporting. Thanks for re-checking this on `2.1.x`!

**Comment by korostii** [comment]
@orlangur that sounds rather vague. Is there some kind of guideline in writing or something like that?

The label guide [here](https://github.com/magento/magento2/blob/develop/README.md) seems pretty much obsolete.

**Comment by orlangur** [comment]
> The label guide here seems pretty much obsolete.

Yeah, I already reported that in Slack, there is a separate doc https://github.com/magento/magento2/wiki/Magento-Issue-Gates which is not integrated with README yet. I remember it was announced in some comments processes will be clarified with 2.2 release.

**Comment by korostii** [comment]
Well, here's 2.2 release. 
There goes nothing! =)

**Comment by BrocksiNet** [comment]
If you have set the _**Default Post Code**_ in configuration section **_Default Tax Destination Calculation_** below **_Sales_** > **_Tax_** then you still get this error (!).

**Comment by senders** [comment]
> If you have set the _**Default Post Code**_ in configuration section **_Default Tax Destination Calculation_** below **_Sales_** > **_Tax_** then you still get this error (!).

I can confirm it.
