### ISSUE TITLE
Web setup wizard undefined index: name

### ISSUE THREAD

**Issue by shanevbg** [magento/magento2#7001]
When I try to do a system upgrade using the web interface (not the CLI, that works fine)
I get the following an Undefined index: name error
![image](https://cloud.githubusercontent.com/assets/1959446/19374399/e7df68be-91d3-11e6-8e49-4572aff1abcb.png)
### Preconditions
1. Magento 2.1.2, MySql 5.7.15
2. `php -v`
   `PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
   Copyright (c) 1997-2016 The PHP Group
   Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
   with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies`
3. Response Headers

> cache-control:max-age=0, no-cache, must-revalidate, no-store
> content-encoding:gzip
> content-type:text/html; charset=UTF-8
> pragma:no-cache
> status:200
> strict-transport-security:max-age=0; includeSubDomains; preload
> vary:Accept-Encoding
> x-content-type-options:nosniff
> x-frame-options:SAMEORIGIN
### Steps to reproduce
1. Log in to admin
2. Go to System ->Web Setup Wizard
3. Select System system upgrade
### Expected result
1. Prompts to walk through available upgrades (if any)
### Actual result
1. 

![image](https://cloud.githubusercontent.com/assets/1959446/19373976/d3a3a93a-91d0-11e6-8d79-47dbe9a1f82d.png)
2. Chrome Console.log

`angular.js:8581 The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`
3. for component manager I get `please wait` (as in #6621, #6737)

![image](https://cloud.githubusercontent.com/assets/1959446/19374139/4995d2d4-91d2-11e6-9f82-91e7aabf0fce.png)

`angular.js:7715 GET https://MYSITE/setup/index.php/componentGrid/components 524 ()(anonymous function) @ angular.js:7715A @ angular.js:7429f @ angular.js:7214D @ angular.js:10168D @ angular.js:10168(anonymous function) @ angular.js:10940$eval @ angular.js:12703$digest @ angular.js:12126$apply @ angular.js:12728f @ angular.js:7321x @ angular.js:7634v.onreadystatechange @ angular.js:7704`

then a never ending until I cancel number of
`angular.js:7715 POST https://MYSITE/setup/index.php/session/prolong 524 ()(anonymous function) @ angular.js:7715A @ angular.js:7429f @ angular.js:7214D @ angular.js:10168D @ angular.js:10168(anonymous function) @ angular.js:10940$eval @ angular.js:12703$digest @ angular.js:12126$apply @ angular.js:12728(anonymous function) @ angular.js:8104`

**Comment by shanevbg** [comment]
Duplicate of #6372, resolved by removing extra repositories from composer.json

**Comment by hocomadvies** [comment]
Did this solution resolve the hanging Component Manager as well? If so where to find the mentioned file composer.json ? 
Thanks

**Comment by shanevbg** [comment]
No, this didn't resolve the hanging component manager issue, but there are open issues for that as well (#6621, #6737)
