### ISSUE TITLE
In magento 2.1.1 coupon code doesn't work

### ISSUE THREAD

**Issue by RafalR86** [magento/magento2#7002]
In Magento 2.1.1 the coupon code doesn't work. I've checked it in customer store and clear magento 2.1.1 installation. When i try apply coupon code then i have error "Coupon code is not valid". Below are my shopping cart price rule settings:

"Rule Information" Tab

Rule Name: test
Active: Yes
Websites: Main Website
Customer Groups: all possible groups are checked
Coupon: Specific Coupon
Coupon Code: TST123
Use Auto Generation: unchecked
Uses per Coupon: 100000
Uses per Customer: 3
From: 09/09/2016
To: 12/31/2116
Priority: 0
Public In RSS Feed: Yes

"Conditions" Tab is blank

"Actions" Tab

Apply: Fixed amount discount
Discount Amount: 4.9
Maximum Qty Discount is Applied To: 0
Discount Qty Step (Buy X): 0
Apply to Shipping Amount: No
Discard subsequent rules: No
Free Shipping: No

Tab "Apply the rule only to cart items matching the following conditions" is blank

It looks like something is wrong with query which is generated to get coupons collection:

`SELECT`main_table`.*,`rule_coupons`.`code`FROM`salesrule`AS`main_table`
  INNER JOIN`salesrule_website`AS`website`ON website.website_id = '1' AND main_table.rule_id = website.rule_id
  INNER JOIN`salesrule_customer_group`AS`customer_group_ids`ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 1
  LEFT JOIN`salesrule_coupon`AS`rule_coupons`ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1 WHERE (from_date is null or from_date <= '2016-10-13') AND (to_date is null or to_date >= '2016-10-13') AND (`is_active`= '1') AND ((main_table.coupon_type = 1  OR (main_table.coupon_type = 3 AND rule_coupons.type = 0) OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1) OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)) AND rule_coupons.code = 'TST123' AND (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2016-10-13')) AND (`is_active`= '1') ORDER BY sort_order ASC;`

The rule doesn't return items, but when i remove this 
`AND (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2016-10-13')`

then returns rule. IMO query should return this coupon, but why doesn't do this? This is how coupon row looks in db
<table border="1" style="border-collapse:collapse">
<tr><th>coupon_id</th><th>rule_id</th><th>code</th><th>usage_limit</th><th>usage_per_customer</th><th>times_used</th><th>expiration_date</th><th>is_primary</th><th>created_at</th><th>type</th></tr>
<tr><td>2</td><td>3</td><td>TST123</td><td>100000</td><td>3000</td><td>0</td><td>NULL</td><td>1</td><td>NULL</td><td>0</td></tr>

**Comment by veloraven** [comment]
@Rudolfff thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by sergiojovanig** [comment]
This is fixed in https://github.com/magento/magento2/issues/6762

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
