### ISSUE TITLE
Magento 2.0 REST, Get all option labels for a configurable product 

### ISSUE THREAD

**Issue by muhsin-k** [magento/magento2#7003]
When i call this API,

**Get all options for configurable product**
[{{base_url}}index.php/rest/V1/configurable-products/:sku/options/all
]()
I am getting  a response like this,

```
[
  {
    "id": 9,
    "attribute_id": "93",
    "label": "Color",
    "position": 0,
    "values": [
      {
        "value_index": 15
      },
      {
        "value_index": 16
      },
      {
        "value_index": 17
      }
    ],
    "product_id": 19
  },
  {
    "id": 10,
    "attribute_id": "176",
    "label": "side",
    "position": 1,
    "values": [
      {
        "value_index": 18
      },
      {
        "value_index": 19
      }
    ],
    "product_id": 19
  }
]
```

But i want label for all these value_indexes.Could i get all these values in  a single request

**Comment by veloraven** [comment]
@muhzi4u thank you for your feedback.
If you think this to be an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is a question please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site.
If it is an improvement you want please submit it to the new [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by muhsin-k** [comment]
@veloraven Thanks for your answer:
There is  an api available for getting all the lables `{{base_url}}/index.php/rest/V1/products/attributes/:attribute_id/options`

**Comment by codewithaashir** [comment]
@muhzi4u 
I get Bellow as api response please help me out please

 {
    "message": "\"%fieldName\" is required. Enter and try again.",
    "parameters": {
        "fieldName": "option"
    }
}
