### ISSUE TITLE
mini cart is not working magento 2 (doesn't refresh)

### ISSUE THREAD

**Issue by sebastian-ehrling** [magento/magento2#7004]
### Preconditions

Magento CE 2.1.2 with sample data is installed.
PHP 7.0.10
MySQL 5.6
OS: Mac OS & Cent OS
### Steps to reproduce
1. go to product detail page oder product list
2. press add to cart Button
3. --> Mini cart will not be refreshed
4. open url http://shopdomain/checkout/cart directly --> you will see all items in cart and mini cart is working

No error in browser console, logfiles or anything

**Comment by shanevbg** [comment]
This seems to be similar to #6265

**Comment by sebastian-ehrling** [comment]
yes!

**Comment by shanevbg** [comment]
@ehrling if this is the same issue as #6265 you probably should comment & close this ticket and post a "I have this same problem!" comment to #6265

**Comment by veloraven** [comment]
I’m closing this issue because it is a duplicate.
