### ISSUE TITLE
Can't save order status label

### ISSUE THREAD

**Issue by robmagento** [magento/magento2#7006]
### Preconditions

1. Magento 2.1.1 CE
2. nginx, PHP 7.0.10, MySQL 5.7.11
### Steps to reproduce

1. Admin > Stores > Order Status > click on one from the list > try to add new labels for a certain store view > click save
### Expected result

1. New labels should be stored in db.
### Actual result

1. New label values are not stored in db

**Comment by AntonEvers** [comment]
The problem is that in \Magento\Sales\Controller\Adminhtml\Order\Status\Save::execute after order status load the order status is missing the label data. 

\Magento\Framework\Model\ResourceModel\Db\AbstractDb::save checks if the data that was present on load is changed. It hasn't. But data is added. And that does not count in the isModified check there. So the order status is considered as not modified and the processNotModifiedSave is executed instead of updateObject

**Comment by AntonEvers** [comment]
@robmagento as a workaround you can edit the main label as well and save it with the store labels. Then edit it back once the labels are in place. This will work.

**Comment by AntonEvers** [comment]
I'll see if I can make a pull request so that this code will include the store values of the labels.

\Magento\Sales\Controller\Adminhtml\Order\Status\Save::execute

``` php
$status = $this->_objectManager->create('Magento\Sales\Model\Order\Status')->load($statusCode);
```

**Comment by robmagento** [comment]
Your workaround... works :). Thank you, I did not have the time to investigate this.

**Comment by AntonEvers** [comment]
There you go ;)

**Comment by SerhiyShkolyarenko** [comment]
@robmagento thank you for reporting. Internal issue is MAGETWO-59639

**Comment by SerhiyShkolyarenko** [comment]
@ajpevers thanks for a workaround!

**Comment by salelsol** [comment]
@ajpevers same issue, and afther change code works like a charm.

**Comment by palvinder03** [comment]
Hello 
I have followed the above but it's not working for me. I have stores and when try to save order status it's showing blank.
I have created file 
Fixes #7006, sales_order_status_label does not support version control #7020
https://github.com/magento/magento2/blob/7cceda81d231d071b715068fa58afb3d6ead2af6/app/code/Magento/Sales/Model/ResourceModel/Order/Status.php

I am using magento 2.17

can any one tell what would be the issue?

**Comment by swayoleg** [comment]
On 2.18 it the same 

until Magento\Sales\Model\ResourceModel\Order\Status will extend the \Magento\Framework\Model\ResourceModel\Db\AbstractDb
NOT VersionControl
(\Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb)

**Comment by swayoleg** [comment]
the _afterSave doesnt executed when extention of resource model is from VersionControl

**Comment by swayoleg** [comment]
This fix still helps 
https://github.com/magento/magento2/commit/54e50d660d6834b294e6e0cc930285a35070d090
