### ISSUE TITLE
Unable to create simple variation for configurable product

### ISSUE THREAD

**Issue by valibus** [magento/magento2#7011]
Edit: i guess this is linked to #5648 . This is still waiting for update after a bug created the 14th July (3 month ago => wheen will you fix it)
Anyway, i hope this video i make will help all of you to understand our problem.
### Preconditions
1. Magento version 2.1
2. php 7

We want to create configurable product with a variation on a packaging attribute. Due to SEO constraint we use the same product view for product we sell using packagin of 1 bottle, 3 bottle or more. (sames informations excepted packaging, sku and price for each)
### Steps to reproduce
1. create a configurable product using the back office and create the variation inside the configurable product using the assistant. 
2. you will view only virtual product
   to view full description on how to reproduce, use the swf video in the zip file in attachement
### Expected result
1. be able to create simple product in variation of a configurable one.
### Actual result

[generate-configurable-virtual.zip](https://github.com/magento/magento2/files/529187/generate-configurable-virtual.zip)
it create only virtual product

We can't only have virtual product genereted by the assistant cause according to thee m2 documentation:
[](http://docs.magento.com/m2/ce/user_guide/catalog/product-create-virtual.html)

> => Virtual products are used for non-tangible products such as services, subscriptions, and warranties.
> => Shipping Options do not appear during checkout unless there is a tangible product in the cart.
> =>Virtual products can be sold individually, or included as part of the following product types:
> Grouped Product
> Bundle Product
> According to the documentation the virtual product doesn't belong to configurable product.

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate as we already have internal ticket for this issue.
