### ISSUE TITLE
unable to add a simple product as variation of a configurable product without creating virtual product

### ISSUE THREAD

**Issue by valibus** [magento/magento2#7012]
Edit: i guess this is linked to #5648 . This is still waiting for update after a bug created the 14th July (3 month ago => wheen will you fix it)
Anyway, i hope this video i make will help all of you to understand our problem.
### Preconditions
1. Magento 2.1 CE 
2. PHP 7
3. having already some simple product created for example : variation 1, variation 2
### Steps to reproduce

1. Go to back office
2. Create a configurable product
3. Go to configuration area in the product sheet and start the assistant
4. **there is the problem** : you couldn't select existing production you have to create other product before.
### Expected result
1. Be able to select simple product using a specific attribute for variation (if was OK in magento 1.9)
### Actual result

**there is the problem** : you couldn't select existing production you have to create other product before.
Please check in attachement the video (using internet explorer to read the swf file)
you will see the function to select existing product only appear at 1:30 only after completing the assistant and creating the virtual product we don't need.

linked to issue :
#7011

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/unable-to-add-a-simple-product-as-variation-of-a-configurable/idi-p/51533).
