### ISSUE TITLE
Product Attribute set Visible on Catalog Pages on Storefront to No not working

### ISSUE THREAD

**Issue by sneha-sukumaran** [magento/magento2#7013]
### Preconditions
1.  Install magento 2.0.7 with sample data
2. 
### Steps to reproduce
1. Login to admin 
2. Navigate to Stores->Attribute->Product
3. Select color attribute and  set Visible on Catalog Pages on Storefront to Yes
4. After Saving again  set Visible on Catalog Pages on Storefront to No.
### Expected result
1.   Visible on Catalog Pages on Storefront value as No
### Actual result
1.  Visible on Catalog Pages on Storefront value is Yes

This issue happens only for swatched attribute

**Comment by dthampy** [comment]
Internal ticket to track this : MAGETWO-60694

**Comment by magento-engcom-team** [comment]
@sneha-sukumaran, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
