### ISSUE TITLE
Magento 2.1.2: Uncaught Error: You cannot apply bindings multiple times to the same element.

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#7014]
### Preconditions

1. Upgraded from 2.0.9 to 2.1.2
2. PHP7
### Steps to reproduce

1. upgrade with composer
2. login into backend
3. check cms pages, blocks or products
### Expected result

1. normal view
### Actual result

1. Console output: Uncaught Error: You cannot apply bindings multiple times to the same element.
2. there is no content that loads, just he console output.
3. On the frontend, NO products get loaded. Shop is now not useable anymore.

With _every_ update, there are problems. Don't you test such things? When are you planning to roll out an version of M2 that is useable for production Environments? This is going to be unbearable. Every single update of M2 contained major bugs so far.

**Comment by sevos1984** [comment]
Have you cleared browser cache?

**Comment by grasdaggel** [comment]
Yes, have done that. Can't reproduce the error anymore, because we've purged M2.1.2 from the server and installed 2.0.9 from scratch again.
