### ISSUE TITLE
Performance improvement: Swatches cause a huge slowdown on catalog pages.

### ISSUE THREAD

**Issue by paales** [magento/magento2#7015]
### Preconditions

1. 2.1.2
### Steps to reproduce

1. Create a category/search page with a lot of configurable products with (image?) swatches
2. Make sure the normal cache is loaded (loading another page)
3. Load the category page.
### Expected result

1. Page should load timely
### Actual result

1. It seems underlying product's images are loaded as well. These images aren't used when rendering a category page.

They are loaded here:
https://github.com/magento/magento2/blob/fb6faf5975fd7580eb407f089f8fbcacd5ee42f5/app/code/Magento/ConfigurableProduct/Helper/Data.php#L83

I'm seeing a huge performance boost when I'm disable that line, and it doesn't seem to degrade in functionality (it doesn't use those images).

![schermafbeelding 2016-10-14 om 14 31 05](https://cloud.githubusercontent.com/assets/1244416/19387508/ec08ec84-921a-11e6-86dd-b02845df0e0f.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Performance-improvement-Swatches-cause-a-huge-slowdown-on/idi-p/51532).

**Comment by paales** [comment]
@piotrekkaminski This surely isn't a new feature, just a regular bug, please open.
