### ISSUE TITLE
Catalog Page Layered Navigation Does Not Work As expected with Elasticsearch

### ISSUE THREAD

**Issue by antbates91** [magento/magento2#7017]
### Preconditions

1. PHP 7.0.7
2. MySQL 5.6
3. Magento EE Tag 2.1  
4. Elastic Search 1.1.2
### Steps to reproduce

1. Enable Elasticsearch in the Magento Backend.
2. Flush Cache and Reindex.
### Expected result

1. When I select Size: 7, Colour: Dirty Buck, and Brand: Sanders the result list should contain everything that is Size 7 and a colour of Dirty Buck with a Brand of Sanders.
### Actual result

1. When you use the Layered Navigation on the Category Page the filters are not applied correctly. For example when I select Size: 7, Colour: Dirty Buck, and Brand: Sanders, the result list contains everything that is either Size 7 or of the Colour Dirty Buck or of Brand Sanders.

![image](https://cloud.githubusercontent.com/assets/8401438/19389342/9d4517b6-921b-11e6-9ddb-e8483832a6e9.png)

I have raised this via the EE Support Portal linking to this issue.

**Comment by shanevbg** [comment]
I don't see how a third party product that isn't said to be compatible with Magento 2.1.x is a Magento bug (or even the fault of BubbleShop)
![image](https://cloud.githubusercontent.com/assets/1959446/19411006/b52bae1c-9301-11e6-8697-bfeef301ec25.png)

https://www.bubbleshop.net/magento2-elasticsearch.html

**Comment by antbates91** [comment]
Where do I mention that I am using BubbleShop? I am using the method as outlined in the documentation here. http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html

**Comment by shanevbg** [comment]
@antbates1991 I apologize.  I didn't see there was another thing called ElasticSearch for Magento.

**Comment by romainruaud** [comment]
@antbates1991 if you are looking to a proper implementation of ElasticSearch, you can take a look to our module : https://github.com/Smile-SA/elasticsuite

It bundles many more features than the legacy implementation of Magento and is fully compatible with EE edition.

Regards,

**Comment by veloraven** [comment]
@antbates1991 thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
