### ISSUE TITLE
Products Views Report - one visit adds two views

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#7018]
### Preconditions

1. I use Magento 2.1.1 + PHP 7.0.
### Steps to reproduce

1. I have visited product page. 
2. Then I have refreshed report in admin: `reports/report_product/viewed/`
### Expected result

1. One visit on product page = one view.
### Actual result

1.  Every visit is counted double. If I have visited product three times it is counted as six.
2. In table `report_event` with every visit appears two records with the same type and product and with different timestamps - with a few seconds difference.

**Comment by bartoszkubicki** [comment]
In fact event is triggered two times, so problem is situated in over-dispatching od event.

**Comment by miakusha** [comment]
Hi @bartek9007 ,  I cannot reproduce this issue. 
Can you reproduce issue on clean Magento without custom code?

**Comment by bartoszkubicki** [comment]
I have checked on clean 2.1.2 install - I confirm that I can't reproduce the issue. I am not sure about 2.1.1., but I am not going to check it, as I will soon move to 2.1.2.
