### ISSUE TITLE
ProductRepository always assigns product to default website

### ISSUE THREAD

**Issue by sparrowek** [magento/magento2#7019]
When saving a product through ProductRepository product is always assigned to a default store.
So you cannot have it not assigned to any website like this: $product->setWebsiteIds(array()) - although it is possible through admin interface - you can easily unclick all websites and save. It is also possible through $product->save() method.
The code behind this phenomenon is in the method ProductRepository::assignProductToWebsites() which always merges a currently set website $websiteIds = [$this->storeManager->getStore()->getWebsiteId()];
to those already set to product: $product->setWebsiteIds(array_unique(array_merge($product->getWebsiteIds(), $websiteIds)));
This also means that you cannot have product assigned to some non-default website because the default one is always merge too.

**Comment by veloraven** [comment]
@sparrowek thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
