### ISSUE TITLE
Unable to enter shipping information for an order / Unable to close an open order

### ISSUE THREAD

**Issue by blizzardengle** [magento/magento2#7022]
### Preconditions
1. Magento 2.1.1 that has been incrementally updated from Magento 2.0.1 not using composer (Zip files and SSH)
2. PHP 5.6.24
   3 MySQL 5.6.34
### Steps to reproduce

I only started to test orders once we got to Magento 2.1 and I have no clue when or what triggered this. Simply going into the orders and trying to ship them triggers this error/ bug.

See attached images for the visual step by steps.

![step1](https://cloud.githubusercontent.com/assets/11205240/19395492/11df4d88-91fb-11e6-999b-d9aa0054b8fc.JPG)
![step2](https://cloud.githubusercontent.com/assets/11205240/19395494/11e085e0-91fb-11e6-911e-f4762d6265e1.JPG)
![step3](https://cloud.githubusercontent.com/assets/11205240/19395495/11e0d716-91fb-11e6-8e6e-9ef2c323298f.JPG)

I checked the network status at this point and the whole dashboard gets redirected instead of the shipping page loading into the dashboard.

![step4](https://cloud.githubusercontent.com/assets/11205240/19395496/11e3a04a-91fb-11e6-976b-d9ad4f9531b3.JPG)

This is all that loads. It is the form that should have been added into the dashboard page but instead only the HTML code is redirected to and the rest of the page is lost.

![step5](https://cloud.githubusercontent.com/assets/11205240/19395493/11e08fe0-91fb-11e6-9c28-40f95cba6531.JPG)
### Expected result

I should be able to enter in shipping information and close the order.
### Actual result

The page gets redirected away from the admin dashboard and I am left with only the form that should have been returned from an Ajax request and populated into the dashboard. There is no meta data or header. Just a new web page with only the forms HTML.

![step4](https://cloud.githubusercontent.com/assets/11205240/19395496/11e3a04a-91fb-11e6-976b-d9ad4f9531b3.JPG)

![step5](https://cloud.githubusercontent.com/assets/11205240/19395493/11e08fe0-91fb-11e6-9c28-40f95cba6531.JPG)

Sometimes the "Something happened" error message pops up before the redirect happens but there is no report or log generated so I can never debug what is really happening.

**Comment by veloraven** [comment]
@blizzardengle thank you for your feedback.
Did you try to clear browser cache including offline website data?

**Comment by blizzardengle** [comment]
Yes. I did everything you should do including wiping all caches, my browser included. The error I found out after a lot of digging was by the Shipper HQ extension. I don't know what they had in their code that was breaking the process but fully removing their extension solved my issues.

**Comment by veloraven** [comment]
@blizzardengle thank you for update.
I'm closing this issue then.
