### ISSUE TITLE
DbValidator will fail even if required privileges are granted

### ISSUE THREAD

**Issue by TheNavigat** [magento/magento2#7028]
Magento version: Latest version as I type this. PHP's version and MySQL versions: latest as well.

To reproduce, update Magento's MySQL user's privileges and grant the user all privileges then try using the Magento web platform.

What's expected is that the website will work correctly. What happens is that an exception is raised at https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L181

This happens because of the usage of array_diff. If more privileges are granted on the database than the ones hard-coded in $requiredPrivileges, an exception will be raised.

An appropriate fix would be using array_intersect and comparing the result with $requiredPrivileges itself.

This issue is basically a reopened version of https://github.com/magento/magento2/issues/5783 because unfortunately I couldn't find the time to update it. I apologize.

> Magento version: Latest version as I type this. PHP's version and MySQL versions: latest as well.
> 
> To reproduce, create a MySQL user, grant the user all permissions, and configure Magento accordingly, then try to update the database.
> 
> What's expected is that the database will update correctly. What happens is that it raises an exception at https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L181
> 
> This happens because of the usage of array_diff. If more privileges are granted on the database than the ones hard-coded in $requiredPrivileges, an exception will be raised.
> 
> An appropriate fix would be using array_intersect and comparing the result with $requiredPrivileges itself.

My response to @SerhiyShkolyarenko is the following,

First, I apologize a lot for the bad description. In retrospect, it's very inaccurate.

This issue occurred when one of the system administrators in a company I used to work for updated the MySQL user used by Magento directly. I think it was a migration.

The Magento installation was set up and the administrator was migrating the databases and the users, along with the web application itself, of course. However, upon creating the user and granting it all permissions, the web application failed.

The explanation for why this happen,

> What's expected is that the database will update correctly. What happens is that it raises an exception at https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L181
> 
> This happens because of the usage of array_diff. If more privileges are granted on the database than the ones hard-coded in $requiredPrivileges, an exception will be raised.
> 
> An appropriate fix would be using array_intersect and comparing the result with $requiredPrivileges itself.

I understand that probably if the application was to be installed using the default installer that problem wouldn't occur, but in this case the error is incorrect nonetheless. The error talks of "insufficient privileges" when, in fact, all required privileges are given.

**Comment by veloraven** [comment]
@TheNavigat thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by TheNavigat** [comment]
@veloraven I apologize, the issue is updated!

**Comment by veloraven** [comment]
@TheNavigat thank you for your update.
Could you please do one more? Please add in a comment clear and short steps to reproduce, actual result and expected result. Without explanation who and why did it. Additional explanation may be very useful for understanding of the whole picture but it takes more time to understand what is the exact problem and how someone can reproduce it. Especially taking into account the fact that different people may work on the issue.
So I would be grateful if you can write short variant like:

**Steps:**
1.
2.
3.
...
**Actual Result:*
...
**Expected Result:**
...
**Possible Reason of the issue**
...

**Comment by TheNavigat** [comment]
Alright, there you go.

**Steps**:
1. Install Magento, the normal way
2. Using MySQL directly, grant all permissions to the MySQL magento user
3. Refresh the Magento platform

**Actual Result**: Exception

**Expected Result**: The platform should work

**Possible Reason of the issue**:

> Exception is raised at https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L181
> 
> This happens because of the usage of array_diff. If more privileges are granted on the database than the ones hard-coded in $requiredPrivileges, an exception will be raised.
> 
> An appropriate fix would be using array_intersect and comparing the result with $requiredPrivileges itself.

**Comment by BaDos** [comment]
Hi, @TheNavigat 

I cannot reproduce it.
Could you debug this and write the content of $grantInfo on line 166 and 174?

Function `array_diff` works correctly for this.
See description:

> This function compares the values of two (or more) arrays, and return an array that contains the entries from array1 that are not present in array2 or array3, etc.

**Comment by TheNavigat** [comment]
@BaDos This is freaky... I'm almost sure I debugged this when this problem happened and that was the fix and indeed that was the way we fixed it, by assigning only the required privileges...

I'm not sure what's wrong, but I think you're right. I'm very sorry I wasted your time. I think this issue should be closed.
