### ISSUE TITLE
There is a problem about opening Create New Customer Account page with chrome

### ISSUE THREAD

**Issue by briceyang** [magento/magento2#7029]
### Preconditions

1. The interface will change, when you type first name and  then click TAB key.
2. This case is found with chrome
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by shanevbg** [comment]
I just tried this in 2.1.2, and don't have any problems.  I primarily use chrome.
Maybe the console.log will give some more hints.
However. I have found that many web site optimization tools or services (e.g. javascript merging, minification, image optimizer) outside of Magento tend to cause problems, so if you have any of those enabled (you might not know it if you are using a shared/caching server) that could be an issue.

**Comment by veloraven** [comment]
@briceyang thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
