### ISSUE TITLE
Notice  undefined index all_resource vendor/magento/module-integration/Controller/Adminhtml/Integration.php

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7031]
How To Solve ???
![image001 1](https://cloud.githubusercontent.com/assets/16436069/19409799/f42f1c14-92f9-11e6-9e79-5f9e0736a941.png)

**Comment by pboisvert** [comment]
@mitulispace can you please follow the template in terms of providing steps to reproduce the issue (before you encounter the error) and system configuration info such as OS, PHP version etc..

**Comment by mitulispace** [comment]
Hi 
Thanks for quick reply. In fact, there are 3rd party developers who are trying to set up API account and they got this error. They need to feed product data from their NutriLoader software so they need to set up API account. 

They went to below path to set up API account.
System > Extension (Integrations)

System config details are as below:
PHP 5.6.20 and  OS Linux

**Comment by veloraven** [comment]
@mitulispace please identify which version of Magento is running.

**Comment by mitulispace** [comment]
Magento ver. 2.1.1  @veloraven

**Comment by taylordipentino** [comment]
I am receiving the same error. Leading up to this, I was unable to view the list of resources available when creating or modifying an integration. Selecting Resource Access->Custom would show the title 'Resources' but nothing would load below it. Possibly a separate issue?

I believe the issue started for me when I tried to rename the integration (accidentally to the same name). It immediately showed the error screen. I deleted the integration, now the same error is thrown whenever trying to create a new one.

Also, I am running Magento 2.1.1 on CentOS 6, Apache 2.4, PHP7 via FPM, Percona Server 5.7

**Comment by Frits1980** [comment]
I got the same error.

Magento 2.1.3

Steps to reproduce:
Go to system>integrations>add new integration

Expected result:
Page to configure integration

Actual result:
Error report saying: a:4:{i:0;s:139:"Notice: Undefined index: resources in vendor/magento/module-integration/Controller/Adminhtml/Integration.php on line 129";i:1;s:4839:"#0 vendor/magento/module-integration/Controller/Adminhtml/Integration.php(129): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/data/web/magen...', 129, Array)

**Comment by valentinmanthei** [comment]
Same here. Magento 2.1.5. After clicking "Add new integration" a blank page appears. Only the "back" and "save" buttons are visible.

**Comment by Anshu-Mishra** [comment]
I am getting the same issue on 2.1.3

**Comment by RomanKrut** [comment]
@mitulispace Hey, I try to reproduce your issue, and system->integration page is normal for me, can you recheck your problem on the latest version of Magento 2?

**Comment by RomanKrut** [comment]
@valentinmanthei  I think "Add new integration" page should have only two buttons - "back" and "save" and one option of "save" its "save & activate"

**Comment by korostii** [comment]
Hi @krutkoroma79911, 
> so it isn`t a bug for you

I don't think @valentinmanthei is bothered by the quantity of buttons available.
I think he is saying there's nothing *but* buttons on the page, meaning the form is absent: http://take.ms/JbhfA . At least that's what I'd mean if I'd use the phrase **"blank page"**

**Comment by RomanKrut** [comment]
@korostii Ohh, sorry, options "Integration info" and "API" are missing, but in my instance it work`s correctly.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by jobsmartdesigner1507** [comment]
did tis issue ever get resolved be I am currently having the same issue
