### ISSUE TITLE
Suggestion : 'Used For' column in Email Templates Grid

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7033]
### Preconditions

1. Magento 2.1.2
### Steps to reproduce

1. No needs to reproduce
### Expected result

1. If there is a column named 'Used For' for email templates, we can see our custom email templates more clear.
### Actual result

1. No need.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Suggestion-Used-For-column-in-Email-Templates-Grid/idi-p/51541).
