### ISSUE TITLE
Magento 2.1.2 New order not display on orders list, only last 5 orders on Dashboard.

### ISSUE THREAD

**Issue by zhxcanada** [magento/magento2#7038]
When created a new order, it can't list on Sales > Orders, but only can list the last 5 orders on Dashboard. This issue appeared in the 2.1.1. after updated to 2.1.2, it's still there. Please help how to fix this error, Thank you very much.
1.  Magento 2.1.1  and Magento 2.1.2
2. PHP 5.6.28
### Steps to reproduce
1. Add order from test customer ID or created order from admin.
2. The order can checked on customer dashboard and admin dashboard
### Expected result
1. Sales > Orders should on the list.
### Actual result
1. The orders Not list.
   ![p1](https://cloud.githubusercontent.com/assets/22866700/19416805/344cab10-9357-11e6-9558-7b1abd3ac527.JPG)

![p2](https://cloud.githubusercontent.com/assets/22866700/19416806/3b0877fe-9357-11e6-8f70-70fa0c05c8b6.JPG)

**Comment by shanevbg** [comment]
I had this same problem (Issue #6932)
run 
`sudo -H -u www-data bin/magento setup:cron:run`
two times
That worked for me at least.
@SerhiyShkolyarenko recommended a more through method if that doesn't work

**Comment by SerhiyShkolyarenko** [comment]
@zhxcanada is it reproducible for you on the latest develop branch?
Is it reproducible for clean installation or for upgraded only? Which way do you create an order?
I tried latest develop branch, created orders both from backend and frontend and all of them were displayed in the grid.

**Comment by ghost** [comment]
I've noticed that sometimes the order is there but won't show up in Sales-> Orders until you sort/re-apply a filter. Try hitting the date purchased, for example, and see if the newest order floats up.

**Comment by SerhiyShkolyarenko** [comment]
@zhxcanada @sylink is it dependent on payment or shipping method? Have you tried to analyze that for "lost" orders?

**Comment by SerhiyShkolyarenko** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by Ecksters** [comment]
I know this is closed, but I've gotten the same issue, using only PayPal as the payment option, I have to sort by Date to see the newest ones. Tried recompiling, remaking static assets, clearing cache, running the cron jobs, and only sorting by the date seems to make them show up.

**Comment by UrbanSurfers** [comment]
Same here with 2.1.9 and Braintree. Clearing cache, running cron jobs have no effect. 
Sorting sales by date is the only way I can see new orders.
I come from a 1.7.0.2 using migration tools.

**Comment by Joshua34** [comment]
Same issue with 2.2, migrated from 1.7 using DMT. Clearing cache, running cron jobs are ineffective.
Sorting orders by date is only way to reveal new orders.

**Comment by kovalevandrew** [comment]
Same issue with 2.2.1 upgrade from 2.1.7 
In the database order appear, but not in the grid

**Comment by boostify-pro** [comment]
I just updated to 2.3.1 and having same problem,

I have only PayPal as a payement method.

any fix please.

**Comment by Vishrootways** [comment]
To solve it, please make sure the cron job is set up on your server and also run php bin/magento cron:run from SSH to solve this issue. I solved it by running php bin/magento cron:run from SSH.
