### ISSUE TITLE
Some CSS and JS are not intalled, I am unable to install proper.

### ISSUE THREAD

**Issue by valukiya07** [magento/magento2#7039]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by shanevbg** [comment]
What are the exact steps you took, and what platform, web server, php, etc were you using?

**Comment by valukiya07** [comment]
I am using PHP 7.0.9 in XAMP latest
I've installed via both way
1) using composer
2) using zip extract
I've followed all the installation steps.
I am attaching screenshots of my current issues.

**Comment by veloraven** [comment]
@valukiya07 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by lhsatch** [comment]
Try changing to developer mode and using di compile

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
