### ISSUE TITLE
Trailing Slash in Product URLs No longer working

### ISSUE THREAD

**Issue by sitepodmatt** [magento/magento2#7040]
We imported an M1 store to a fresh M2 (develop branch) with Magento Data Migration Tools. My clients store used /abc-product/ as the product detail URLs,  the information populated correctly, including request_path in url_rewrite (i.e. trailing slash present), however all URLs 404 when clicked.

In my opinion app/code/Magento/UrlRewrite/Controller/Router.php (L132) should not be right trimming trailing slashes before passing to UrlFinder, this is causing problems with product search engine URLs that use the trailing space variety (as M1 supports).

The admin panel allows one to specify 'Product URL suffix' for Catalog as /  Which correctly causes the product URL rendering for category/search pages to contain the trailing slash, however those product pages 404, because the trailing slash is stripped and doesn't match anything request_path in url_rewrite.

Believe this should be ltrim only.

**Comment by veloraven** [comment]
@sitepodmatt thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by henk-hypershop** [comment]
Still issue is still not fixed in Magento 2.1.9. Seems like a very important one. If stores are indexed by Google with a trailing slash, one cannot simply migrate and contain the URL structure. This will be killing for rankings. Why has this not been fixed yet? We are now forced to change this in the vendor file with the risk that this will be overwritten on any update.
