### ISSUE TITLE
Prices including tax / excluding tax not working

### ISSUE THREAD

**Issue by deckside** [magento/magento2#7043]
We need to display VAT a 20% tax at checkout and on invoices.
All product pricing entered via admin already includes VAT tax.
We have the same set up using 1.9.2 and everything works fine. 
We are now building our new site using 2.1.2 and it does not work.

Current version Magento 2.1.2 CE, 

We have created a the tax zone and tax rate and that works fine. 
The problem is the product prices entered into admin are the prices including tax
i.e. 100.00 which is the price including tax in the back end. 
This products price is being display on the front end as 120.00, the tax has been added to the price that already has the tax included.

Under Stores > Configuration > Sales > Tax > Calculations Settings
When we change the "Catalog Prices" and/or "Shipping Prices" to "Including Tax" it has no effect.

The product is a simple product, default attributes.

Full update and step up test below

**Comment by veloraven** [comment]
@deckside thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by deckside** [comment]
We need to display VAT/GST Tax at 10% tax at checkout and on invoices.
All product pricing entered via admin already includes VAT tax.
We have the same set up using 1.9.2 and everything works fine. 
We are now building our new site using 2.1.2 and it does not work.

Current version Magento 2.1.2 , CE

We have created a the tax zone and tax rate and that works fine. 
The problem is the product prices entered into admin are the prices including tax
i.e. 100.00 which is the price including tax in the back end. 
This products price is being display on the front end as 110.00, the tax has been added to the price that already has the tax included.

Under Stores > Configuration > Sales > Tax > Calculations Settings
When we change the "Catalog Prices" and/or "Shipping Prices" to "Including Tax" it has no effect.

The product is a simple product, default attributes.

Steps to reproduce.
Step 1
Products > Catalog > Add Product
Create a simple product with default attributes, Tax class = Taxable Goods, Price = $100.00

Step 2
Stores > Taxes > Tax Zones and Rates > Add New Tax Rate 
Identifier = GST
Zip/Post Code = *
State is shaded out
Country = Australia
Rate Percentage = 10.0000

Step 3
Stores > Taxes > Tax Rules >
Name = GST Australia
Tax Rate = GST
Customer Tax Class = Retail Customer
Product Tax Class = Taxable Goods
Priority = 0
Calculate off subtotal only = not selected
Sort order = 0

Step 5
Stores > Configuration > Sales > Shipping Methods >
Flat Rate = Yes
Title = Flat Rate
Method = Fixed
Type = Per order
Price = 10.00
Calculate Handling Fee = Fixed
Handling Fee = 0
Ship to Applicable Countries = Specific Countries
Ship to Specific Countries = Australia (no others selected)
Show Method if Not Applicable = no

Step 5
Stores > Configuration > Sales > Tax >
Tax Class for Shipping = Taxable Goods
Default Tax Class for Product = Taxable Goods
Default Tax Class for Customer = Retail Customer
Calculation Settings
Tax Calculation Method Based On = Total Price
Tax Calculation Based On = Shipping Address
Catalog Prices = Excluding Tax - This sets whether catalog prices entered from Magento Admin include tax.
Shipping Prices = Excluding Tax - This sets whether shipping amounts entered from Magento Admin or obtained from gateways include tax.
Apply Customer Tax = After Discount
Apply Discount On Prices = Including Tax
Apply Tax On = Custom Price if avaiable
Enable Cross Border Trade = no

Default Tax Destination Calculation
Default Country = Australia
Default State = *
Default Post Code = *
Price Display Settings
Display Product Prices In Catalog = Including Tax
Display Shipping Prices = Including Tax
Shopping Cart Display Settings
Display Prices = Including Tax
Display Subtotal = Including Tax
Display Shipping Amount = Including Tax
Include Tax In Order Total = Yes
Display Full Tax Summary = Yes
Display Zero Tax Subtotal = Yes
Orders, Invoices, Credit Memos Display Settings
Display Prices = Including Tax
Display Subtotal = Including Tax
Display Shipping Amount = Including Tax
Include Tax In Order Total = Yes
Display Full Tax Summary = Yes
Display Zero Tax Subtotal = Yes
Fixed Product Taxes
Enable FPT = No
Display Prices In Product Lists = Including FPT and FPT description
Display Prices On Product View Page = Including FPT and FPT description
Display Prices In Sales Modules = Including FPT and FPT description
Display Prices In Emails = Including FPT and FPT description
Apply Tax To FPT = No
Include FPT In Subtotal =No

Step 6
System > Tools > Cache Management
Select all > Refresh

Step 7
Go to the product in web site 
Product Price = $110.00
Expected Results
Product Price = $110.00
Correct Result

Step 8
Add to cart 
Product Price = $110.00
Shipping Price = $11.00
Expected Results
Product Price = $110.00
Shipping Price = $11.00
Correct Result

Step 9
Stores > Configuration > Sales > Tax >
Change the following settings
Calculation Settings
Catalog Prices = Including Tax - This sets whether catalog prices entered from Magento Admin include tax.
Shipping Prices = Including Tax - This sets whether shipping amounts entered from Magento Admin or obtained from gateways include tax.

Step 10
System > Tools > Cache Management
Flush Magento Cache
Select all > Refresh

Step 11
Go to the product in web site 
Product Price = $110.00
Expected Results
Product Price = $100.00
Changing the setting above should have set the entered product price as the price including the tax.

Step 12
Add to cart 
Product Price = $110.00
Shipping Price = $11.00
Expected Results
Product Price = $100.00
Shipping Price = $10.00

**Comment by deckside** [comment]
I found the problem

Needed to change a setting
Sores> Configuration > Sales > Shipping Settings>Origin

Needed to expand this tab and change the Country.

**Comment by mgfrench** [comment]
Mine was a good one.  

My store view scope was set to be granular and not to default config.  So when I went to update all Attributes for the TAX Class within the item the second time, I ensure the particular store view was selected.

Hope this helps someone.
