### ISSUE TITLE
create new/update category programmatically for specific storeView not working

### ISSUE THREAD

**Issue by bjt1988** [magento/magento2#7047]
### Preconditions
1. Magento 2.1.1 Community Edition
2. one Website two StoreViews: 
   ID: 1 -> [de] -> [Deutsch]
   ID: 2 -> [en] -> [Englisch]
### Steps to reproduce

Create a category in backend or programmatically
Name: Test123
after that in all storeViews the category have the name Test123
if you now want to try to change the name of the category for StoreView: 2 programmatically it is not working.  
Everytime the "Update" is going to StoreView: 1

`<?php`
`include('app/bootstrap.php');`
`$bootstrap = Bootstrap::create(BP, $_SERVER);`
`$objectManager = $bootstrap->getObjectManager();`
`$category = $objectManager->get('\Magento\Catalog\Model\Category')->load(78);`
`$d["updated_at"] = "2016-10-14 10:22:34";`
`$d["entity_id"] = "78";`
`$d["psl_wawi_cat_id"] = "42";`
`$d["position"] = "10";`
`$d["is_active"] = "1";`
`$d["store_id"] = "2";`
`$d["is_anchor"] = "1";`
`$d["name"] = "TESTA-1_ENG";`
`$d["custom_design_from"] = "";`
`$d["custom_design_to"] = "";`
`$d["include_in_menu"] = "1";`
`$d["default_sort_by"] = "";`
`$d["path"] = "1/2/74/78";`
`$d["level"] = "3";`
`$d["url_key"] = "testa-1-eng";`
`$d["attribute_set_id"] = "3";`
`$category->setData($d);`
`$category->setStoreId(2);`
`$categoryFactory=$objectManager->get('\Magento\Catalog\Api\CategoryRepositoryInterface')->save($category);`
`?>`
when i run this the Name for the category is changed for StoreView 1 to "TESTA-1_ENG" but not for StoreView 2. i cant find a way to save the changes to a specific StoreView. Everytime the changes goes to StoreView 1. Also StoreView 0 is not working.

**Comment by koenner01** [comment]
Just a question; Why are you saving the category through the repositoryInterface instead of calling ->save() on the $category object you loaded ?

**Comment by bjt1988** [comment]
mhhh good question. in the last 5 days i tested a lot also with the direct save on the category object. but sometimes i get curious erros like "url_key always in use" or "entity_id not found". A lot of strange things and after googling and googling i found an example where someone do it in this way with the repositoryInterface and my privious erros go away.

But after 5 Days of testing and understanding i can say that all the privious errors that i get comes from my side of wrong data giving. now my script is working also with direct save method of the $category object.

magento 2 acts in some cases very different to magento 1 and some errors are not so clear at the first point of view.

i think this can be closed.

**Comment by routbiplab** [comment]
I did this -
	$categoryModel = $objectManager->create('Magento\Catalog\Model\Category')->load(3);		
			$categoryModel->setData('name', 'electronics-updated');
			$categoryModel->setStoreId(0);
			$categoryModel->save();
	But getting this error:
 Fatal error: Maximum function nesting level of '2000' reached, aborting! in vendor/magento/framework/Config/Scope.php on line 48

**Comment by vesvello** [comment]
How can I programmatically change the value of 'parent_id'?
I tried so far:
$category = $this->_objectManager->get('\Magento\Catalog\Model\Category')->load($id);
$d["entity_id"] = $id;
$d["name"] = $name;
$d["store_id"] = 0;
$d["parent_id"] = 7;
$category->setData($d);
$category->setStoreId(0);
$category->save();
but parent_id is not updated.
Thanks in advance

**Comment by akssaiyad** [comment]
```
> <?php
> //increase the max execution time
> @ini_set('max_execution_time', -1);
> //memory_limit
> @ini_set('memory_limit', -1);
> 
> error_reporting(E_ALL);
> ini_set('display_errors', '1');
> 
> // Start Despaly All Product Meta Title And Description
> require_once('app/Mage.php'); //Path to Magento
> umask(0);
> Mage::app();
> 
> $categories = Mage::getModel('catalog/category')
>                          ->getCollection()
>                          // magic is prepared here..
>                          ->addAttributeToSelect('*')
>                          // then the magic happens here:
>                          ->addAttributeToFilter('level', array('eq'=>4))
>                          ->load();
>     if (count($categories) > 0):
> 
>         foreach($categories as $category):
> 
>             $catId = $category->getId();
>             $category = Mage::getModel('catalog/category')->load($catId);
> 
>             //if($catId==1465):
>                 $CategoryName = $category->getName(); 
>                 $metaTitle = "Buy ".$CategoryName." Online India - RightGifting";
>                 $metaDescription = "Shop your favourite ".$CategoryName." for you or send a gifts purpose from RightGifting online store India. Offers available. 100% Fast & free shipping!";
>                 //$category->setMetaTitle($metaTitle);
>                 //$category->setMetaDescription($metaDescription);
>                 //$category->save();
> 
>                 $category->setData('meta_title', $metaTitle);
>                 $category->save($category, 'meta_title');
>                 $category->setData('meta_description', $metaDescription);
>                 $category->save($category, 'meta_description');
> 
>                 $check = $category->getMetaTitle();
>                 echo "<pre>";
>                 print_r($catId);
>                 echo "<pre>";
>                 print_r($check);
>                 echo "\n";
>             //endif; 
>             
>         endforeach;
>      else: echo "No Results";
>     endif;
> 
> ?>
```
