### ISSUE TITLE
ls -lash

### ISSUE THREAD

**Issue by frozenravage** [magento/magento2#7048]
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@frozenravage please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
