### ISSUE TITLE
Upgrade version issue when change branch

### ISSUE THREAD

**Issue by dzungnt** [magento/magento2#7049]
### Preconditions

1. Magento EE 2.0.1 without sample data is installed.
2. Use git
### Steps to reproduce

1. Create module A in branch 1 with version is 1.0.0
2. Create branch 2 from branch 1 and upgrade A to 1.0.1
3. Switch back to branch 1
### Expected result

1. No error message
### Actual result

1. It's showing error log current version - 1.0.1, required version - 1.0.0

**Comment by veloraven** [comment]
@dzungnt please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
