### ISSUE TITLE
Request: .user.ini files for FPM config

### ISSUE THREAD

**Issue by clockworkgeek** [magento/magento2#705]
On a couple of Magento1 sites I've had to configure nginx and have found [`.user.ini` files](http://php.net/manual/en/configuration.file.per-user.php) to be most reliable.  It is significantly easier than editing the system `php.ini` then restarting PHP-FPM and worrying about automatic updates over writing your work.  Although the exact filename can be changed with `user_ini.filename` setting I have yet to see any server change this.

For Magento 2 I suggest two files, `/.user.ini` and `/pub/.user.ini`, to allow for situations where Magento files are not stored in the web root and are linked to instead.  Their content is derived from the `.htaccess`.

    memory_limit=768M
    max_execution_time=18000
    session.auto_start=off

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30489

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-user-ini-files-for-FPM-config/idi-p/47117).
