### ISSUE TITLE
Cannot see the Static Blocks , Pages in Magento 2

### ISSUE THREAD

**Issue by Dbl0207** [magento/magento2#7050]
I Cannot see the static block section, Pages in Magento 
### Preconditions
1. Magento Version 2.0.9 and this happens in a server.
2. 
### Steps to reproduce
1. I have installed magneto 2.0.9 and this has happened to me. In Local the same code works fine no error happens.
### Expected result

1.  Static Block List and Pages List should be visible as i find in Local Host.
### Actual result
1. Static Blocks and Pages list not visible.

**Comment by veloraven** [comment]
@Dbl0207 thank you for your feedback.
Please add more details to your description of the steps you followed when identifying this issue.

**Comment by Dbl0207** [comment]
![screen shot 2016-10-17 at 6 41 31 pm](https://cloud.githubusercontent.com/assets/22885198/19438819/422d8374-9499-11e6-8308-deb0f555ddea.png)
![screen shot 2016-10-17 at 6 42 26 pm](https://cloud.githubusercontent.com/assets/22885198/19438850/6b23c2a2-9499-11e6-8c1b-ae7c0ad6bb3d.png)

Hi Veloraven, 
   Please visit 
http://www.webnexs.com/demo/mg/adminmg/
User: admin
Pass: admin147

When you login into this store, please go to content -> Static Blocks. There are no static Blocks.

Please Have a check and kindly help us. I have also uploaded screenshot of Static Block, Pages
 which is empty.

**Comment by lhsatch** [comment]
Could it be an issue with your CDN. I noticed that there was an error relating to Cloud flare in the console.

**Comment by Dbl0207** [comment]
Hi Ihsatch,
  Thank you for that. But i have removed the setup with respect to Cloudflare, but still iget this issue.

**Comment by lhsatch** [comment]
Hi,
Have you installed any additional plugins?

**Comment by lhsatch** [comment]
Actually this may be a permissions issue. Ensure that the folders and files have the correct permissions. I am guessing that the files and folders were working correctly locally as there were different permissions set.

**Comment by veloraven** [comment]
@Dbl0207 was it clear install or upgrade from some other version?
Did you try to clear your browser cache including offline website data?

**Comment by Dbl0207** [comment]
@Olga, It was a clean install. Yes i cleared browser cache. We use
cloudflare caching and i switched tht off as well.

@ihsatch Sure i will check that. But when i did install magento 1.9.x it is
perfect. Ill get back once if follow what you have said.​

Regards,

## _Bright Livingstone Davidraj, B.Tech, B.L, M.B.A;_

CEO & Co-Founder - _Brightlivingstone.com_
Google+:         _https://plus.google.com/+BrightLivingstone_
https://plus.google.com/+BrightLivingstone
Twitter\* :          _https://twitter.com/DBRIGHTLIVING
Phone_: _+91 95000 80937 |Gtalk_:\* dbl0207@gmail.com

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please delete it right away or
notify the sender.

**Comment by oshmyheliuk** [comment]
Hi @Dbl0207 ,

I visited a site that you provided above and observe that requires.js don't work properly.
This problem described here [cloudfare + requirejs](https://coderwall.com/p/pd4toq/cloudflare-require-js).

Please, try next solution:

> The way to fix this is to turn off 'full optimizations' in the cloudflare settings for your site. As soon as you do this, your javascript will be back to happy.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
