### ISSUE TITLE
Uncaught Error: Cannot instantiate interface Magento\Catalog\Model\Product\CopyConstructorInterface

### ISSUE THREAD

**Issue by TKlement** [magento/magento2#7056]
Creating an upgrade script for cloning a product with \Magento\Catalog\Model\Product\Copier has a bug.
### Preconditions
1. Magento 2.1.0
2. PHP 7.0.11
### Steps to reproduce

The constructor looks like this:

``` php
public function __construct(
    \Magento\Catalog\Model\Product\Copier $productCopier,
    \Magento\Framework\App\State $appState
) {
    $this->productCopier = $productCopier;
    try {
        $appState->setAreaCode('frontend');
    } catch( \Magento\Framework\Exception\LocalizedException $e ) {
        // intentionally left empty
    }
}
```

Then in console run
`bin/magento/ setup:upgrade`
### Expected result

No failure
### Actual result

`PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Catalog\Model\Product\CopyConstructorInterface in /var/www/m210/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
Stack trace:
#0 /var/www/m210/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Catalog...')
#1 /var/www/m210/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Catalog...')
#2 /var/www/m210/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Catalog...', NULL, 'copyConstructor', 'Magento\Catalog...')
#3 /var/www/m210/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Catalog...', Array, Array)
#4 /var/www/m210/vendor/magento/frame in /var/www/m210/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73`

**Comment by sevos1984** [comment]
Have you tried clearing cache before running upgrade?

**Comment by TKlement** [comment]
Already tried.
I was only able to delete the cache with 
´´´
rm -rf var/cache/*
´´´
because the backend access was not possible due to the problem.
And with bin/magento I had the problem that just that simple call creates a failure.
When I call bin/magento the list of commands ends with a failure after the first two commands.

**Comment by sevos1984** [comment]
Try 'rm -rf var/generation/*'

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by iamserkanyilmaz** [comment]
I guess this error associated with di.xml. 

have this error.
`Fatal Error: 'Uncaught Error: Cannot instantiate interface Future\Test\Api\Data\ShopInterface in /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50`

added this lines in di.xml 
`  <preference for="Future\Test\Api\Data\ShopSearchResultsInterface" type="Magento\Framework\Api\SearchResults" />
<preference for="Future\Test\Api\Data\ShopInterface" type="Future\Test\Model\Shop" />
<preference for="Future\Test\Api\ShopRepositoryInterface" type="Future\Test\Model\ShopRepository" />`

and fixed my problem.

**Comment by useapp** [comment]
I have the same problem "PHP Fatal error: Uncaught Error: Cannot instantiate interface Magento\Catalog\Model\Product\CopyConstructorInterface"
And i can not find the solution. Mage 2.1.7

This code also has the same error
$om = \Magento\Framework\App\ObjectManager::getInstance();     
$productCopier = $om->create('\Magento\Catalog\Model\Product\Copier');

**Comment by vutrankien** [comment]
Try the my solution : 
Create di.xml file in frontend folder with the content below
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Catalog\Model\Product\CopyConstructor\Composite">
        <arguments>
            <argument name="constructors" xsi:type="array">
                <item name="crossSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\CrossSell</item>
                <item name="upSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\UpSell</item>
                <item name="related" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\Related</item>
				<item name="catalog_inventory" xsi:type="string">Magento\CatalogInventory\Model\Product\CopyConstructor\CatalogInventory</item>
				<item name="downloadable" xsi:type="string">Magento\Downloadable\Model\Product\CopyConstructor\Downloadable</item>
            </argument>
        </arguments>
    </type>
    <type name="Magento\Catalog\Model\Product\Copier">
        <arguments>
            <argument name="copyConstructor" xsi:type="object">Magento\Catalog\Model\Product\CopyConstructor\Composite</argument>
        </arguments>
    </type>
</config>`

see image : 
![image](https://user-images.githubusercontent.com/14917460/27477217-b206146c-5835-11e7-8a73-02ba6f569bda.png)

**Comment by bnymn** [comment]
The solution given by @vutrankien works. You just need to copy the configuration to **app/etc/di.xml**.

**Comment by websunil** [comment]
The solution given by @vutrankien worked for me as well. You just need to copy the configuration to app/etc/di.xml.

**Comment by annajersey** [comment]
cache clearing worked for me

**Comment by tomasinchoo** [comment]
\Magento\Catalog\Model\Product\Copier has this on line 10:
`use Magento\Catalog\Api\Data\ProductInterface;`

I believe it should be: 

`use Magento\Catalog\Api\Data\ProductInterface as CopyConstructorInterface`;

**Comment by francescopis** [comment]
@magento-engcom-team any news?

**Comment by drak25** [comment]
pasting the configuration lines to app/etc/di.xml works but it is a bad solution cause this file is overrided during magento upgrade.

Pasting to etc/di.xml in the extension does not work.

Is there any other solution ?

**Comment by vutrankien** [comment]
@daim2k5 you can coppy code to your custom extension.
Example : app/code/Brand/CustomModule/etc/di.xml.
So if upgraded Magento this solution still works.

**Comment by congson95dev** [comment]
Fatal error: Uncaught Error: Cannot instantiate interface Fudu\HelloWorld\Api\Data\StudentsRepositoryInterface in C:\xampp\htdocs\magento\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:50 Stack trace: #0 
---
follow @vutrankien  but doesn't work
here's my di.xml after i follow alot of github, stackexchange, stackoverflow ..: 

`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Fudu\HelloWorld\Api\Data\StudentsRepo" type="Fudu\HelloWorld\Api\Data\StudentsRepositoryInterface" />
</config>`

because StudentsRepositoryInterface is my class

**Comment by dziulius** [comment]
@saxsax1995 

I think you should swap "for" and "type" values:
`
<preference for="Fudu\HelloWorld\Api\Data\StudentsRepositoryInterface" type="Fudu\HelloWorld\Api\Data\StudentsRepo" />
`

**Comment by congson95dev** [comment]
@dziulius nice, thanks :) but i pass that long time ago :)

**Comment by fcastrogiovani** [comment]
I have this error, tried flushing cache and full folder also but it didn't work.

PHP Fatal error: Uncaught Error: Cannot instantiate interface Magento\Customer\Api\GroupManagementInterface in C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:50

Stack trace:
#0 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Custome...')

#1 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Custome...')

#2 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Custome...', NULL, 'groupManagement', 'Magento\\Catalog...')

#3 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Cata in C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php on line 50

**Comment by dziulius** [comment]
@fcastrogiovani, did you run setup:di:compile?

**Comment by fcastrogiovani** [comment]
@dziulius yes, i did. After running composer update i run all this commands.

composer update

rm -rf var/di var/generation
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

Edit.
i run again php bin/magento setup:di:compile
then php bin/magento indexer:reindex and i have a new error.

$ php bin/magento indexer:reindex
PHP Fatal error: Uncaught Error: Cannot instantiate interface Magento\Customer\Api\GroupManagementInterface in C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:50
Stack trace:
#0 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Custome...')
#1 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Custome...')
#2 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Custome...', NULL, 'groupManagement', 'Magento\\Catalog...')
#3 C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Cata in C:\xampp\htdocs\brementools\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php on line 50

Edit2
i did this to solve the errors
enabled Magento modules (bin/magento module:enable --all)
compiled DI (bin/magento setup:di:compile)
and 
bin/magento setup:upgrade

Edit3
Then i got two errors solved by removing data-requiremodule and making ignore remove exception.

Edit4
Now i have a 404 error / Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

it's like a never ending nightmare!
Thanks for you time!

**Comment by ghost** [comment]
Similar issue here, I'm developing a new module that overrides Multishipping.php model and I've got this:

`Cannot instantiate interface Magento\Payment\Model\Method\SpecificationInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50`

Applying similar solution that @vutrankien mentioned in https://github.com/magento/magento2/issues/7056#issuecomment-310625852 should work? based on what? it's different interface, any ideas?

Best,

**Comment by itsbrianburton** [comment]
@bruno-serfe You've probably already resolved it, but here's the solution for anyone else experiencing this problem.

First reference the frontend/di.xml file in the module you want to override and find where that interface is referenced.  For multishipping looks like this:
```
    <type name="Magento\Multishipping\Model\Checkout\Type\Multishipping">
        <arguments>
            <argument name="paymentSpecification" xsi:type="object">multishippingPaymentSpecification</argument>
        </arguments>
    </type>
```
Open your module's frontend/di.xml file and add the following:
```
    <type name="CompanyName\ModuleName\Model\Checkout\Type\Multishipping">
        <arguments>
            <argument name="paymentSpecification" xsi:type="object">multishippingPaymentSpecification</argument>
            <argument name="data" xsi:type="array"></argument>
        </arguments>
    </type>
```

**Comment by termos008** [comment]
I had a similar issue.
Please, check all files in app/etc/ folder.
In my case I didn't have any di.xml in app/etc

**Comment by israelguido** [comment]
> Try the my solution :
> Create di.xml file in frontend folder with the content below
> `<?xml version="1.0"?> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"> <type name="Magento\Catalog\Model\Product\CopyConstructor\Composite"> <arguments> <argument name="constructors" xsi:type="array"> <item name="crossSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\CrossSell</item> <item name="upSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\UpSell</item> <item name="related" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\Related</item> <item name="catalog_inventory" xsi:type="string">Magento\CatalogInventory\Model\Product\CopyConstructor\CatalogInventory</item> <item name="downloadable" xsi:type="string">Magento\Downloadable\Model\Product\CopyConstructor\Downloadable</item> </argument> </arguments> </type> <type name="Magento\Catalog\Model\Product\Copier"> <arguments> <argument name="copyConstructor" xsi:type="object">Magento\Catalog\Model\Product\CopyConstructor\Composite</argument> </arguments> </type> </config>`
> 
> see image :
> ![image](https://user-images.githubusercontent.com/14917460/27477217-b206146c-5835-11e7-8a73-02ba6f569bda.png)



> Try the my solution :
> Create di.xml file in frontend folder with the content below
> `<?xml version="1.0"?> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"> <type name="Magento\Catalog\Model\Product\CopyConstructor\Composite"> <arguments> <argument name="constructors" xsi:type="array"> <item name="crossSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\CrossSell</item> <item name="upSell" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\UpSell</item> <item name="related" xsi:type="string">Magento\Catalog\Model\Product\CopyConstructor\Related</item> <item name="catalog_inventory" xsi:type="string">Magento\CatalogInventory\Model\Product\CopyConstructor\CatalogInventory</item> <item name="downloadable" xsi:type="string">Magento\Downloadable\Model\Product\CopyConstructor\Downloadable</item> </argument> </arguments> </type> <type name="Magento\Catalog\Model\Product\Copier"> <arguments> <argument name="copyConstructor" xsi:type="object">Magento\Catalog\Model\Product\CopyConstructor\Composite</argument> </arguments> </type> </config>`
> 
> see image :
> ![image](https://user-images.githubusercontent.com/14917460/27477217-b206146c-5835-11e7-8a73-02ba6f569bda.png)

This work for me in di.xml
