### ISSUE TITLE
StockItemRepository gets wrong product id if a product has been deleted

### ISSUE THREAD

**Issue by lhsatch** [magento/magento2#7057]
### Preconditions

1. Magento 2.1.0 installed
2. Configurable products created
3. Simple products created
### Steps to reproduce
1. Create  2 configurable products (anything) with 2 attributes (colour and size), and create a simple product. 
2.  Delete a product which isn't the last product in your inventory.
3. Check the cataloginventory_stock_item and the product item_id of the product after you deleted should be different to the product_id.
   4 . Make a call to $this->_stockItemRepository->get($product_id)->getIsInStock() using  \Magento\CatalogInventory\Model\Stock\StockItemRepository
### Expected result
1. In module-catalog-inventory\Model\Stock\StockItemRepository get function should be associating the productid to the product_id column in cataloginventory_stock_item.
### Actual result
1. Within the \Magento\CatalogInventory\Model\Stock\StockItemRepository get function it is calling 
   getItemId which is referencing the item_id instead of the product_id.
   2 - The product_grid image shows a grid for configurable products. The numbers represent the product Ids. If the text boxes are disabled then that product should be out of stock. But the product that is out of stock is the product with the following product id.
   ![product_grid](https://cloud.githubusercontent.com/assets/6516012/19471287/704a7ce0-951a-11e6-8469-18575590c97a.jpg)

3 - After looking in the cataloginventory_stock_item table I can see that the stock of the item is being referenced against the item_id. (See cataloginventory_stock_item image).
![cataloginventory_stock_item](https://cloud.githubusercontent.com/assets/6516012/19471290/74b4fe86-951a-11e6-8a56-6c3d8a272cd0.jpg)

**Comment by lhsatch** [comment]
To get round this issue I have used the \Magento\CatalogInventory\Model\StockState model and getStockQty() function to reference against as this uses the cataloginventory_stock_status table which does reference the product_id.

**Comment by miakusha** [comment]
Hi @lhsatch , fourth step contain issue `$this->_stockItemRepository->get($product_id)` you must pass stock_item_id instead of product_id
For obtain stock_item object by product use `$stockItem = $product->getExtensionAttributes()->getStockItem();` or configure search criteria (\Magento\CatalogInventory\Api\StockStatusCriteriaInterface)  and use `\Magento\CatalogInventory\Api\StockStatusRepositoryInterface::getList`

**Comment by lhsatch** [comment]
Thank you for your response but if this is used to get the Stock item qty by product_id then how do you go about getting the stock qty for a product by product_id ?

Thanks

**Comment by lhsatch** [comment]
Hi Miakusha,
Thank you for getting back to me. Although I have managed to get the stock qty using the StockState class I haven't been able to find a function that will get the product stock state (in stock, out of stock) by product_id. As  `$this->_stockItemRepository->get($product_id)` is used by referencing the stock_item_id what can be used to get the product stock status? I haven't found anywhere in the catalog_inventory module where I could get the stock status of a product by product_id. Any help would be great.

**Comment by maghamed** [comment]
Hi @lhsatch 

Actually \Magento\CatalogInventory\Api\Data\StockStatusInterface
should answer to all your questions.

Long story short: 
Magento has StockItem entity which represents amount (Qty) of specific product (productId) on a concrete stock (stockId).
StockItemInterface should be used when you would like to "write" data into the data storage (like update amount of products to sync up Magento with your ERP system or to make deduction of stock during the checkout process).

StockStatusInterface is opposite to it. It should be used to "read" data for representation (on front-end). Consider StockStatus as an index which contains aggregated stock data for each specific product.

So, if you would like to get product stock status  (in stock, out of stock) by product_id.
You need using StockStatusRepositoryInterface::getList(StockStatusCriteriaInterface $searchCriteria);
get StockStatus entity for specified product

```
            /** @var \Magento\CatalogInventory\Api\StockStatusCriteriaInterfaceFactory $stockStatusCriteriaFactory **/
            $criteria = $stockStatusCriteriaFactory->create();
            $criteria->setProductsFilter($productId);
            /** @var \Magento\CatalogInventory\Api\Data\StockStatusRepositoryInterface $stockStatusRepository **/
            $result = $stockStatusRepository->getList($criteria);
            $stockStatus = current($result->getItems());
            $stockStatus->getProductId();                 // product id
            $stockStatus->getQty();   // quantity of specified product
            $stockStatus->getStockStatus();     // Could be 
    // Magento\CatalogInventory\Model\Stock\Status::STATUS_OUT_OF_STOCK = 0;
    // or
    // Magento\CatalogInventory\Model\Stock\Status::STATUS_IN_STOCK = 1;
```

**Comment by lhsatch** [comment]
Hi Maghamed,
You are a legend!!!!! That has worked perfectly and the getStockStatus() function works for both 0 quantities and for stock status (out of stock).  Thank you.

**Comment by veloraven** [comment]
I'm closing this report as issue was solved.

**Comment by korostii** [comment]
Hi @maghamed 

As of Magento Open Source 2.3, `\Magento\CatalogInventory\Api\Data\StockStatusInterface` is apparently now `@deprecated` (despite also being marked as `@api`) in favor of the MSI.

I tried to consult the links provided, but [one](https://devdocs.magento.com/guides/v2.3/inventory/index.html) of the pages linked near the deprecation notice says I should be using the Read-Only interface (StockItem) to check if a product is in or out of stock while the [other](https://devdocs.magento.com/guides/v2.3/inventory/catalog-inventory-replacements.html) says that StockItem-related classes and methods got deprecated, for example `StockItemRepositoryInterface::getList`

I am now a bit confused. What would be the direct (or nearest) replacement to the code you provided above but using the new APIs provided by MSI?
