### ISSUE TITLE
changing configurable product name in 2.2.0 dev causes undefined index: label error

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#7058]
### Preconditions
1. magento 2.2.0-dev
2. php 5.6
### Steps to reproduce
1. install magento 2.2.0-dev
2. setup multiple configurable products with multiple attributes
3. change product name. 
### Expected result

1. the product name should change
### Actual result

1. Notice: Undefined index: label in app/code/Magento/Catalog/Model/Product/Gallery/CreateHandler.php on line 161

Cleared cache, tried with both  compile mode and not compiled mode. ran setup:upgrade each time. 

```
 if (in_array($attrData, array_keys($existImages))) {
                $product->setData($mediaAttrCode . '_label', $existImages[$attrData]['label']);

```

is the section it errors at.

**Comment by Pagayo** [comment]
I have the exact same problem. Only my php version is 7.0

**Comment by Pagayo** [comment]
When I do this with a product that has no image, there is no error.

**Comment by dthampy** [comment]
Thank you for reporting this. An internal ticket has been created for this issue: MAGETWO-59843

**Comment by Zeeshu1** [comment]
iam facing the same issue and i am using php 7.0.

**Comment by sckogi** [comment]
Same here. I realized the error isn't throw if you open the "Images And Videos" section before save, probably this hint can help.

**Comment by veloraven** [comment]
I'm closing this issue as internal ticket was closed as a duplicate for MAGETWO-59626 which has been fixed already.

**Comment by shadowcomm** [comment]
Can you point me towards the actions taken to fix the issue? I cannot find "MAGETWO-59626" to find the solution. Thank you.
