### ISSUE TITLE
Mistake in product import model

### ISSUE THREAD

**Issue by comdiler** [magento/magento2#7062]
### Preconditions

1. Magento CE, tag 2.1.2
### Steps to reproduce

1. Add several products with a numeric SKU, for example 416242-L, 416242-XL, 416242
2. Turn on debugger
3. Put breakpoint before statement in Magento\CatalogImportExport\Model\Import\Product line 1224
   "->where('sku = ?', $sku)"
4. Import product attributes with a "416242" SKU in CSV file
### Expected result

1. Product attributes should be correctly updated
### Actual result

1. In case of importing numeric SKUs, MySQL can update wrong product.
   See examples on a screenshots.
   Suggested solution: make sure that $sku is always string - like "->where('sku = ?', (string)$sku)" on line 1224 instead of existing
   ![1](https://cloud.githubusercontent.com/assets/1975805/19459189/8025ebca-94d1-11e6-97cc-777910bb4db8.png)
   ![2](https://cloud.githubusercontent.com/assets/1975805/19459191/8373d8dc-94d1-11e6-90f0-ed38758ff5ba.png)
   ![3](https://cloud.githubusercontent.com/assets/1975805/19459194/85b62c76-94d1-11e6-9749-62e8ba983c4d.png)

**Comment by comdiler** [comment]
Support Ticket on Magento portal is #03192334

**Comment by veloraven** [comment]
I'm closing this issue as Github is intended for Community edition reports given no account management for CE users. And support ticket was already created for this issue.

**Comment by comdiler** [comment]
@veloraven I have updated ticket. 
This issues also exists in Magento CE, tag 2.1.2
Information about EE support ticket has been removed.
Please reopen.

**Comment by gorillagroup** [comment]
@veloraven CatalogImportExport module not present in EE code pool. 
This module is used in both CE and EE. 
CatalogImportExport module get's inherited from CE code pool in Magento EE.
Please reopen a ticket.

**Comment by gorillagroup** [comment]
#7089
