### ISSUE TITLE
Always get "Items xxx of 10000" on the toolbar.

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#7063]
### Preconditions

1. Magento 2.1.1
2. PHP 7.0.8 and mysql 5.7.15
3. Ubuntu server 16.0.4 + Apache
### Steps to reproduce

1. Install magento 2.1.1 fresh version
2. Use "Data Generator" to create 20000 simple products and assign them to one category
3. Turn on Flat category and product features
4. Reindex all
### Expected result

1. On FE, should show correct "Items xxx of y" on the toolbar. In my case, there are 10004 products assigned to "Category 1", it should show "Items 1-12 of 10004".
### Actual result

1. On FE, always show " Items 1-12 of 10000" on the toolbar. I also tested some other cases with more products and got same result.
   ![2016-10-18_10-46-31](https://cloud.githubusercontent.com/assets/1607243/19463669/333bc1b4-9520-11e6-8b9a-99f72b9f970f.png)
2. In fact, there are more than 10000 products assigned to that category in BE. All products are available and in stock.
   ![2016-10-18_10-48-00](https://cloud.githubusercontent.com/assets/1607243/19463693/6357611e-9520-11e6-96a3-55d3297ab6ca.png)

**Comment by olysenko** [comment]
Hi, thanks for your request.
You need to increase value of parameter `<size>`  in app\code\Magento\CatalogSearch\etc\search_request.xml  under node    `<request query="catalog_view_container" index="catalogsearch_fulltext">` and issue will be solved.  Please check  this solution and if it helps close the issue

**Comment by phuc128t** [comment]
It works. Thank you! I'm wondering why M2 is set max to 10000 products.
