### ISSUE TITLE
Composer.json location wrong assumption in SampleData module

### ISSUE THREAD

**Issue by mmenozzi** [magento/magento2#7064]
Hi,
here https://github.com/magento/magento2/blob/develop/app/code/Magento/SampleData/Model/Dependency.php#L89, you assume that the composer.json file for every module must be at the same level of the module itself. Even if in core modules this is always true it might not be true for third party modules.
A well known best practice is to have source code in the `src` folder so it could be the root path of a module (look at https://github.com/aleron75/mage2hints or https://github.com/webgriffe/module-config-override).

Can you fix this wrong assumption?

**Comment by mmenozzi** [comment]
It's also assumed that a composer.json exists but for modules in app/code is not required to have a composer.json so there should be a check if the file exists.

**Comment by veloraven** [comment]
@mmenozzi thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
