### ISSUE TITLE
lib-popup() mixin doesn't work

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#7067]
I'm using Magento 2.1.2, following docs i added this markup from `lib/web/css/docs/popups.html` to a phtml file in my template

```
<button type="button" class="action toggle" data-toggle="popup" data-backdrop="true" data-target="#window-popup" aria-expanded="false" aria-controls="window-popup"><span>Show popup</span></button>
<div class="window popup popup-example" id="window-popup" tabindex="-1" role="dialog" aria-labelledby="popup-title" aria-describedby="popup-content" aria-hidden="true">
    <div class="popup actions">
        <div class="secondary">
            <button type="button" class="action close" data-dismiss="popup"><span>Close</span></button>
        </div>
    </div>
    <div class="popup header">
        <strong class="title" id="popup-title"><span>Popup title</span></strong>
    </div>
    <div class="popup content" id="popup-content">
        <p>Popup content</p>
    </div>
    <div class="popup footer"></div>
</div>
```

and this less:

```
.window.popup.popup-example {
    .lib-popup();
}
```

Expected result:
 a button that toggles a popup

Actual result:
a useless button

**Comment by tkacheva** [comment]
@slackerzz could you clarify if you expect less mixin makes pop-up work?

**Comment by slackerzz** [comment]
a less mixin alone cannot add a click handler to the button, but in the docs it ins't specified to init the popup via js.
I'd like to know how it is supposed to work.

**Comment by giacmir** [comment]
I think that the problem is just that @slackerzz says. Docs have a quite extensive descriptions of mixins but zero info on how make something useful with them. 

Some time ago I had to implement a modal window and while the docs were exhaustive on how to style it i had to dig deep in the source in order to find how to make that modal open... 

A collateral effect of this problem is that the docs are a collection of non working items, and this is really disapponting.

**Comment by tkacheva** [comment]
@almarchenko Please check if we can make the doc more clear

**Comment by MomotenkoNatalia** [comment]
Hi @slackerzz
.lib-popup(); mixin works as expected. It is less mixin that set popup styles without JS.
Anyway, I created  internal ticket (MAGETWO-59956) to verify and probably modify our documentation for popup mixin.
Moreover, we have huge epic to improve our documentation of UI library.

**Comment by slackerzz** [comment]
@MomotenkoNatalia ok, so how should it be initialized?

**Comment by samthecarman** [comment]
Hi, Does anyone know how to initialize the popup JS?

**Comment by magento-engcom-team** [comment]
@slackerzz, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by slackerzz** [comment]
@magento-engcom-team what happened to `MAGETWO-59956`? The point here is that that the documentation included inside magento is incomplete.

**Comment by magento-engcom-team** [comment]
@slackerzz According to the `MAGETWO-59956` it is still open.

**Comment by slackerzz** [comment]
So after almost an year the `MAGETWO-59956` internal ticket is still open and you closed the corresponding github issue.
Sorry, but i don't understand.
 :confused:
