### ISSUE TITLE
Incorrect message when adding out of stock product to cart

### ISSUE THREAD

**Issue by udovicic** [magento/magento2#7069]
### Preconditions

1. Magento version CE 2.1.2
2. PHP 7
### Steps to reproduce

1. On a fresh Magento installation create new configurable product with some child products in stock and some out of stock
2. Go to product on frontend
3. Select out of stock option and click 'add to cart'
### Expected result

1. Message "This product is out of stock." should be displayed
### Actual result

1. Message "You need to choose options for your item." is displayed

**Comment by miakusha** [comment]
Hi @udovicic thanks for report
Its known issue with internal ticket MAGETWO-54361

**Comment by ewallkrishnaprakash** [comment]
Hi, 
Am also face this issue.
Is there any update for this issue.
**My Megento version is : 2.1.1**

**Comment by magento-engcom-team** [comment]
@udovicic, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
