### ISSUE TITLE
small request / add the ability to remove or move TAB and MENU items

### ISSUE THREAD

**Issue by seansan** [magento/magento2#707]
Currently extension are clogging up our tab and menu bars. And esp the last couple of years everybody seems to add their company name and extension name in every menubar they can. 

Wlould be nice for the admin to stop or circumvent this. 

Pref. All extensions also in one place in the backend

![image](https://cloud.githubusercontent.com/assets/652395/4787611/c9188fac-5dad-11e4-9dd8-99774fb8a38d.png)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30490

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/small-request-add-the-ability-to-remove-or-move-TAB-and-MENU/idi-p/47105).
