### ISSUE TITLE
.lib-column() mixin strange behaviour

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#7070]
### Preconditions

1. Magento ver. 2.1.2 (from zip) 
2. PHP 7.0.11-1~dotdeb+8.1 
3. mysql  Ver 14.14 Distrib 5.6.34
### Steps to reproduce

1. I use mixin .lib-column(1, 6) to style my blocks in 6 columns (see screenshot)
   ![screen 1](https://cloud.githubusercontent.com/assets/884525/19477753/50183d80-9548-11e6-9b8a-61dcb4e79b90.png)
2.  When i use grunt exec / grunt less commands to compile my less files, everything goes fine but when i use magento setup:static-content:deploy, columns appears twice smaller (see second screenshot)
   ![screen 2](https://cloud.githubusercontent.com/assets/884525/19477847/b3f2a3fe-9548-11e6-994b-8890da7e5540.png)
### Expected result

1.  Grunt and magento less compiling should give same result
### Actual result

1.  it gives different width of columns

**Comment by OleksiiStepanov** [comment]
I have same problem on 2.1.6 
Looks like when less file compiled without grunt .lib-column() mixin ignore any params

**Comment by magento-engcom-team** [comment]
Hi @Styopchik

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@Styopchik, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
