### ISSUE TITLE
 Undefined index on createhandler.php

### ISSUE THREAD

**Issue by Zeeshu1** [magento/magento2#7074]
When I try to edit my product it gives me an error, "Notice: Undefined index: label in /../app/code/Magento/Catalog/Model/Product/Gallery/CreateHandler.php on line 161. 

My product is a configurable product but this error occurs in all type of products.

It's not specific to any attribute also. It will be great if I could get a fix for this.

I am using magento 2.2.0-dev
here is my CreateHandler.php line 161

```
           if (in_array($attrData, array_keys($existImages))) {
/*line 161*/     $product->setData($mediaAttrCode . '_label', $existImages[$attrData]['label']); 
            }

```

**Comment by dthampy** [comment]
@Zeeshu1 , this looks like a duplicate of #7058 . Please close this issue and re-open with detailed steps if needed.

**Comment by sammarcus** [comment]
@Zeeshu1 does this occur on configurable products that have no images?

**Comment by Zeeshu1** [comment]
@sammarcus it occurs on configurable with and without images. 
@dthampy  thank you i didnt saw that post even tho i did a lot of research but couldn't find anything.
