### ISSUE TITLE
Exporting Low Stock Report to csv or xml file does not work

### ISSUE THREAD

**Issue by cdbessig** [magento/magento2#7075]
### Preconditions

1. Magento CE 2.0.6, 2.0.9, 2.0.10 all tested 
2. Mysql 5.6 / php 5.5.24
### Steps to reproduce

1. Log in to admin panel, click on reports, low stock report.
2. On top right of the page, click on Export next to the Export to: dropdown.  Have CSV or Excel XML selected.
3. An error message appears:

```
csv: Fatal error: Call to a member function getCsvFile() on a non-object in /home/user/sites/magento2010.com/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php on line 39

excel xml: 
Fatal error: Call to a member function getExcelFile() on a non-object in /home/user/sites/magento2010.com/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockExcel.php on line 39

```
### Expected result
1. A file download should occur containing the products from the grid.
### Actual result

1. Error messages above.

**Comment by dthampy** [comment]
Thank you for the bug report. Internal jira ticket MAGETWO-59848 has been created.

**Comment by magento-engcom-team** [comment]
@cdbessig, thank you for your report.
We've created internal ticket(s) MAGETWO-62279 to track progress on the issue.

**Comment by michielgerritsen** [comment]
I can reproduce this problem on a 2.1.9 installation, but in 2.2.0 it works as expected. You get an .csv of .xml file.

**Comment by okorshenko** [comment]
Hi @michielgerritsen thank you for research. We will double check this

**Comment by osrecio** [comment]
@okorshenko I can't repdroduce this error with branches: `develop`, `2.1-develop`, `2.2-develop`, `2.3-develop`.
But is true that I can reproduce with M2Commerce 2.19

**Comment by keyurshah070** [comment]
@okorshenko I can not reproduce in fresh 2.2. kindly confirm

**Comment by rajpal-majoka** [comment]
Any update on this?

**Comment by okorshenko** [comment]
Thank you everyone for research

**Comment by ramsampathi** [comment]
We have faced the same issue in Magento 2.3.4 .
How can we fix this issue?

**Comment by thomas-harding** [comment]
Same here on Magento 2.3.4. Would be useful to know if any fix is available.

**Comment by mtoothaker-links** [comment]
I am also seeing it on an upgraded Magento 2.3.5 site
