### ISSUE TITLE
Reports: Low stock csv export not working

### ISSUE THREAD

**Issue by stevenvdp** [magento/magento2#7076]
When you try to export the low stock report you get a error message
Fatal error: Call to a member function getCsvFile() on a non-object in app/code/Magento/Reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php on line 40

Seems that the expected block doesn't existst when trying to retrieve with:

```
 $exportBlock = $this->_view->getLayout()->getChildBlock(
            'adminhtml.block.report.product.lowstock.grid',
            'grid.export'
        );
```
### Preconditions

1. Initially tested on v2.0.7
2. Also broken in v2.1.1
### Steps to reproduce

1. Goto backoffice
2. Reports => Low Stock
3. Click on csv export
### Expected result

1. start downloading a csv file
### Actual result

1. Error message: Fatal error: Call to a member function getCsvFile() on a non-object

**Comment by dthampy** [comment]
@stevenvdp ,isn't this a duplicate #7075 ? 

closing this as duplicate.
