### ISSUE TITLE
Payflow Pro using Payflow Link URLs

### ISSUE THREAD

**Issue by dreucifer** [magento/magento2#7078]
### Preconditions
1. Magento CE 2.1.2 without sample data installed.
2. Configured USPS and FedEx Shipping Methods.
3. Configured PayPal Payflow Pro Payment Method using credentials that work via `curl`.
4. Imported products and categories from a previous shopping cart.
### Steps to Reproduce
1. Navigate to storefront as a guest.
2. Open an imported category.
3. Click "Add to Cart" on an imported product.
4. Open mini shopping cart and click "Go to Checkout".
5. Complete Address and Shipping steps of checkout.
6. Select "Credit Card" for a Payment option.
7. Enter Credit Card details and click "Place Order"
#### Expected Results

PayPal Payflow Pro processes the credit card transaction. I am sent to an order confirmation page and the order shows up in the 'Sales->Orders' section of the cart admin.
#### Actual Results

The checkout page just hangs and nothing loads.
### Additional Information

I checked the network calls via my browser and it looks like the checkout is POSTing a silent redirect to `https://payflowlink.paypal.com` which doesn't seem in line with the PayPal developer documentation. Checking through the source, `vendor/magento/module-paypal/Model/Payflowpro.php` shows the correct payflowpro URL, but `vendor/magento/module-paypal/etc/config.xml` shows `https://payflowlink.paypal.com` as a `cgi_url`.

**Comment by veloraven** [comment]
@dreucifer thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by dreucifer** [comment]
Nevermind, it looks like the issue was with my PayPal account.

**Comment by luism91** [comment]
@dreucifer Can you specify the details with your account? Gladly appreciated

**Comment by mahendrajella** [comment]
@dreucifer  I am facing the same issue, can you please give details about account setup.
