### ISSUE TITLE
Failed to Execute 'atob' on 'Window' The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by zstutzman** [magento/magento2#7079]
In the WYSIWYG
![selection_086](https://cloud.githubusercontent.com/assets/713842/19496938/f0b59bd4-9557-11e6-9e2b-235a1be8c703.png)

**Comment by veloraven** [comment]
@zstutzman thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ghost** [comment]
I have the same error, I believe it may be caused by pasting javascript into the editor, but persists after the offending content is removed...? That's the best I've got.

Consistently having the same issue across many versions of Magento 2.
