### ISSUE TITLE
Consider using namespaces for XML schemas

### ISSUE THREAD

**Issue by joshdifabio** [magento/magento2#708]
I believe Magento 2's XML schemas should each specify a target XML namespace.

The current approach (referencing schemas using the `noNamespaceSchemaLocation` attribute within XML files) requires implementers to know the exact location of a schema relative to the XML file which they are defining, which won't always be practical, even if Magento 2 does impose a rigid directory structure (there will likely be components other than Magento 2 modules which consume those schemas).

If you decide to introduce namespaces for Magento 2's XML schemas then I think there is a choice to be made between using URNs or URLs as XML namespace identifiers, each of which have their own limitations and benefits.

My personal preference would be to use URNs, for example `urn:magento:schemas:config`.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30492
