### ISSUE TITLE
Setting "quantity_and_stock_status" attribute to "Visible On catalog Pages" results in "Additional Information" Tab on Product Page not showing

### ISSUE THREAD

**Issue by qbo-tech** [magento/magento2#7080]
### Preconditions
1. Magento CE 2.1.2 without sample data is installed.
2. PHP 7.0.8
### Steps to reproduce
1. Configurable Product is created, configured and assigned to the a test Category and Default attribute Set.
2. "Additional Info" Tab on Product page properly renders custom attributes on storefront.
3. "quantity_and_stock_status" Attribute is accidentally set to "**Visible on Catalog Pages on Storefront**" by Administrator
4. Reindex Product and Attribute data.
5. Navigate to the product page, and the expected "Additional Info" Tab is gone due to a warning on the following line:  `if (isset($options[$value])) {` which expects $value to be an index and not an array on **vendor/magento/module-eav/Model/Entity/Attribute/Source/AbstractSource.php**, line 74 .
### Expected result

1. Additional Tab on Product Page should be properly rendered.
### Actual result

1. Additional Info Tab on disappears.  
2. A warning rises on system log:
   **Warning: Illegal offset type in isset or empty in vendor/magento/module-eav/Model/Entity/Attribute/Source/AbstractSource.php on line 74** 
### Suggested solution
1. Validate that $value is not an array :+1: 
   http://magento.stackexchange.com/questions/130681/magento2-product-page-returns-error/141489#141489

**Comment by dthampy** [comment]
Thank you for your bug report. Internal ticket MAGETWO-60619 is created to track this.

**Comment by magento-engcom-team** [comment]
@qbo-tech, thank you for your report.
We've created internal ticket(s) MAGETWO-60619 to track progress on the issue.

**Comment by indd01** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@indd01 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by firmsoftware** [comment]
Hi

I'm currently in the midst of writing a new indexer using a process of TDD and this is where I came across this little bug. I hit the issue not from a change from a user but from the Magento supplied Data fixture **Magento/Catalog/_files/product_simple.php**. 

If TDD is to be standard method of development, shouldn't these fixtures work flawlessly? From the log above, it seems, unless I'm mistaken like this issue doesn't seem to matter from it's status being "OPEN" and "unassigned". Or is a case that the original reporter has given up?

**Comment by magento-engcom-team** [comment]
Hi @qbo-tech

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@qbo-tech, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
