### ISSUE TITLE
Notice undefined index all_resource vendor/magento/module-integration/Controller/Adminhtml/Integration.php 

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7081]
Hi 
there are 3rd party developers who are trying to set up API account and they got this error. They need to feed product data from their NutriLoader software so they need to set up API account.

They went to below path to set up API account.
System > Extension (Integrations)

System config details are as below:
PHP 5.6.20 and OS Linux
### Expected result

1.  Without error
### Actual result

![f42f1c14-92f9-11e6-9e79-5f9e0736a941](https://cloud.githubusercontent.com/assets/16436069/19506443/43784e20-95e9-11e6-8067-f13eca711df1.png)

**Comment by veloraven** [comment]
@mitulispace thank you for your feedback.
Please, identify which version of Magento is used.

**Comment by mitulispace** [comment]
@veloraven   thank you for quick response
Magento ver. 2.1.1

**Comment by odubovyk** [comment]
As I understand the problem is that Integrations page is not opened and outputs error.
If it is the case, it is not reproducible.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
