### ISSUE TITLE
Unable to create Plugin for Swatches\Helper\Media

### ISSUE THREAD

**Issue by TKlement** [magento/magento2#7082]
While there is bug with the correct order of the view.xml files [(#6382)](https://github.com/magento/magento2/issues/6382) I tried to create a plugin from the Magento\Swatches\Helper\Media.php.
Unfortunately after reloading the page there is an error.
### Preconditions
1. Magento 2.1.0
2. PHP 7.0.11
### Steps to reproduce
1. Create a plugin for Magento\Swatches\Helper\Media.php
2. Register plugin in your custom module
3. Reload page
### Expected result
1. See the shop/backend
2. For our case we need to set a new size for swatch_image.
### Actual result

```
exception 'Magento\Framework\Exception\LocalizedException' with message 'Invalid Document Element 'type': Character content other than whitespace is not allowed because the content type is 'element-only'. Line: 49
Element 'type': Character content other than whitespace is not allowed because the content type is 'element-only'. Line: 49 ' in
/var/www/m210/vendor/magento/framework/Config/Reader/Filesystem.php:160 
Stack trace: 
#0 /var/www/m210/vendor/magento/framework/Config/Reader/Filesystem.php(127): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator)) 
#1 /var/www/m210/vendor/magento/framework/App/ObjectManager/ConfigLoader.php(69): Magento\Framework\Config\Reader\Filesystem->read('global') 
#2 /var/www/m210/vendor/magento/framework/App/ObjectManager/Environment/Developer.php(77): Magento\Framework\App\ObjectManager\ConfigLoader->load('global') 
#3 /var/www/m210/vendor/magento/framework/App/ObjectManagerFactory.php(194): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array) 
#4 /var/www/m210/vendor/magento/framework/App/Bootstrap.php(385): Magento\Framework\App\ObjectManagerFactory->create(Array) 
#5 /var/www/m210/vendor/magento/framework/App/Bootstrap.php(232): Magento\Framework\App\Bootstrap->initObjectManager() 
#6 /var/www/m210/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...') 
#7 {main}
```
### More information

**di.xml**

``` xml
<type name="Magento\Swatches\Helper\Media">
    <plugin name="correct-config-order" type="Custom\Module\Model\Plugin\MediaPlugin" sortOrder="10"/>
</type>
```

**MediaPlugin.php**

``` php
namespace Custom\Module\Model\Plugin;

use Magento\Framework\App\Area;
use Magento\Catalog\Helper\Image;

/**
 * Class MediaPlugin
 *
 * @package Custom\Module\Model\Plugin
 */
class MediaPlugin
{
    /**
     * Retrieve correct image config
     * Can be removed once Magento fix this
     *
     * @return string
     */
    public function aroundGetImageConfig(\Magento\Swatches\Helper\Media $subject, \Closure $proceed)
    {
        // do something
        return $proceed();
    }
}


```

**Comment by lhsatch** [comment]
Can you show your full di.xml file including the schema declaration and xml tags.

**Comment by palamar** [comment]
Please provide more information, I can't reproduce issue with provided steps.
You can check my code [Custom_Module.zip](https://github.com/magento/magento2/files/551072/Custom_Module.zip)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
