### ISSUE TITLE
Missing REST API info: Order statuses

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#7084]
### Preconditions

1. Magento 2.0.9 here (local test vagrant), but applies to all versions.
### Problem description

- An admin in Magento2 can create custom order statuses.
- I'm making an integration for Magento2 with an external platform.
- I sync orders, and want to take action on order status change to any of a number of order statuses.
- An end user can configure which order status to take action on.
- I cannot access the available order statuses.
### Expected solution

I would expect either the store configuration (since that's where an admin can set it) or a separate REST endpoint to provide information on available order statuses.

**Comment by mbrinton01** [comment]
@fvschie do you mean the status for a particular order, or a list of all possible statuses including custom ones?

**Comment by fvschie** [comment]
I meant the list of all possible statuses.

We want to trigger a campaign, but not all customers assign statuses to states properly, so we'd rather allow them to select statuses that should trigger the campaign.

Should probably be in the same endpoint as the store config, as that's where you configure it in the Admin panel.

**Comment by mbrinton01** [comment]
@misha-kotov please review

**Comment by fvschie** [comment]
Any update?

**Comment by PaulBoss** [comment]
Is there any update on this?

**Comment by magento-engcom-team** [comment]
@fvschie , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by chileap** [comment]
@magento-engcom-team i know the issue should be discussed in  Community Forums or the Magento Stack Exchange site. but i cannot get solution yet. Do magento2 api has this endpoint?

**Comment by mlinuxgada** [comment]
Imao the ReST api endpoint for order statuses is part of the core func - just like listing orders. Statuses are not module functionality, so if you wanna for example be able to update particular order with specific status, you should be able to retrieve all possible order statuses, right ?
So, atm you cant change orders status, because there is no api func to retrieve them.

**Comment by DavidLambauer** [comment]
As far as I can see, there is a REST Endpoint for getting at least the status of a particular order. Trying out this API leads to a 200 response with no body. Not sure what this does...

![image](https://user-images.githubusercontent.com/1841317/106598448-06c47d80-6558-11eb-8d9a-75a4cf1ac187.png)
