### ISSUE TITLE
Layouts from Theme doesn't work for MAGE_RUN_CODE and MAGE_RUN_TYPE Websites

### ISSUE THREAD

**Issue by jk100magnys** [magento/magento2#7088]
### Preconditions

Magento ver. 2.1.1

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04

php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

mysql --version
mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
### Steps to reproduce

1) Create two Websites for one Magento instance (first_site, second_site)
2) Create your own theme
3) Set this theme for each of Websites
4) Add to this theme layout, for example:

> app/design/frontend/Your_theme/your_theme/Magento_Customer/layout/default.xml

with code:

```
<referenceBlock name="register-link" remove="true" />
```

5) Set for you vhost MAGE_RUN_CODE and MAGE_RUN_TYPE for "second_site"

```
#    set $MAGE_RUN_TYPE website;
#    set $MAGE_RUN_CODE second_site;
```

6) Open main page of this (second_site) store 
### Expected result

Block "register-link" will successfully deleted and doesnt show on the page
### Actual result

You can see that "register-link" block wasnt deleted

But, if you create module "Module One" and move this layout to 

> app/code/Local/ModuleOne/view/frontend/layout/default.xml

block "register-link" will successfully deleted

**Comment by sevos1984** [comment]
I've tried that using luma theme and block removed. Could your case with using luma theme?

**Comment by jk100magnys** [comment]
This problem may be visible if you make new theme "MyTheme" via extends (for example) Luma. 
And then, in MyTheme directory 
`
app/design/frontend/MyTheme /mytheme/Magento_Customer/layout/default.xml
`
you try to move some block from Luma Theme.

`
<referenceBlock name="register-link" remove="true" />
`

So, it means that you have to have possibility edit and control Parent's theme blocks from layout in current theme.

Right now i've reproduced this situation with clear CE 2.1.2 + sample data + new "MyTheme" based by Luma  (parent = Luma)

**Comment by magento-engcom-team** [comment]
@jk100magnys, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
