### ISSUE TITLE
Can not update local development products

### ISSUE THREAD

**Issue by SantoDE** [magento/magento2#7091]
When using a local development environment with a "live" database dump, you're not able to edit products if the image is missing. I know this issue was fixed in the past. Did it just come up with 2.1.2 again?
### Preconditions

1. Magento 2.1.2
### Steps to reproduce

1.  Setup local environment
2. Use "live dump"
3. Try to edit a product
### Expected result

1. I should be able to edit the product
### Actual result

1. Edit fails with that error: 

Cannot gather stats! Warning!stat(): stat failed for /var/www/html/pub/media/catalog/product/4/4/44545195-htl1.jpg

**Comment by veloraven** [comment]
I'm closing this issue as duplicate for #7086
