### ISSUE TITLE
Install 2.1.2 - stays on Installing 68% despite completing

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7094]
Install 2.1.2

Screen says "Installing... 68%" and stays on that.

However var/log/install.log shows that it did in fact finish installing:

```
<span class="text-success">[SUCCESS] Magento installation complete.</span><br><span class="text-success">[SUCCESS] Magento Admin URI: /admin</span>
```

I have Varnish 5.0 installed. PHP 7. Nginx. OS X Sierra

**Comment by duhon** [comment]
@craigcarnell 
try to use php.ini.sample, especially important item max_execution_time = 18000
