### ISSUE TITLE
Admin: field labels wrapping poorly

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7099]
### Preconditions

1. Version: 2.1.1
### Steps to reproduce

1. Go to any page that has long input field labels, such as when adding a new product attribute.
### Expected result

1. Labels should not wrap, or if they wrap then they should break at word boundary, not in the middle of a word, which makes it hard to read.
### Actual result

1. Screenshots:

![image](https://cloud.githubusercontent.com/assets/4110567/19553511/1c66b5c0-96e7-11e6-9146-451fc33c08a4.png)

![image](https://cloud.githubusercontent.com/assets/4110567/19553524/27d37fce-96e7-11e6-88ea-2e0bfb5d0cbe.png)

**Comment by dthampy** [comment]
Internal ticket : MAGETWO-60691

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We've created internal ticket(s) MAGETWO-60691 to track progress on the issue.

**Comment by enriquei4** [comment]
I'm working on this issue

**Comment by enriquei4** [comment]
I've fixed it for #SQUASHTOBERFEST in #11727 & #11745

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop and will be available with 2.2.2 release
