### ISSUE TITLE
Minicart refreshes itself when user browses to different pages.

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#7100]
Minicart refreshes itself when user browses to different pages.

Issue: When a user has added few products into the cart, the cart number keeps changing to 0 and then back to the number of products when user moved from one page to another. This is not a good exp for the user as the user would keep seeing 0 in the cart even though there are products. This issue is amplified on a slow network.

Environment:
- Magento 2.1.1
- Ubuntu 14
- Varnish / FPC enabled.
- Apache.

Steps:
- Login to the store.
- Add products to the cart.
- Check that minicart shows the number of products added (Example: 4)
- Now move to other pages, categories or product details of various product.
- Each time the page is changed, the cart will become 0 and then change back to 4

Expected: The cart should not change to 0 even for a small time. This on a slower network would make the 0 stay for longer.

**Comment by PieterCappelle** [comment]
This is correct behaviour. On page load the basket is rendered from cache. After page load ajax call is executed to get cart information. We need this to use full page cache and varnish.

**Comment by apurv-anand** [comment]
How about customer experience? The customer would keep seeing 4 then 0 then 4 and then 0 again... (assuming 4 is the no of items in the cart) while he/she is browsing the site for more products. This is more amplified on a slower network where 0 would stay for longer time.

Technical solutions should cater in a way that customer exp is not affected, not the other way round.

How do you propose to solve this?

**Comment by SerhiyShkolyarenko** [comment]
@apurv-anand thank you for reporting the issue.
I tried Magento 2.1.2 with Varnish installed by official docs(http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish-magento.html) and didn't reproduce the issue. Each time the minicart value was shown, it corresponded items count in the cart.
Which of your steps were different from that manual? Do you use the exported from Magento config? Which Varnish version do you use?

**Comment by SerhiyShkolyarenko** [comment]
@apurv-anand thank you for reporting the issue.
I tried Magento latest with Varnish and didn't reproduce the issue. Each time the minicart value was shown, it corresponded items count in the cart. Minicart never shown 0.
Which Varnish version do you use? Is the issue reproducible without varnish(with FPC)?
Which mode magento works in?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
