### ISSUE TITLE
Magento 2.1.1 Roles Resource Tree not showing

### ISSUE THREAD

**Issue by ivagarfitt** [magento/magento2#7101]
In the backend, going to system->roles, adding a new role and setting it to custom permissions, the resource tree is empty.

`public function getTree()
    {
        $resources = $this->_aclResourceProvider->getAclResources();
        $rootArray = $this->_integrationData->mapResources(
            isset($resources[1]['children']) ? $resources[1]['children'] : []
        );
        return $rootArray;
    }`

The one used for the mapResources-call is Admin_Backend::all with an empty children array. Now in my opinion this leads to the resource tree being empty. Shouldn't there be an extra handling of the this role as it doesn't have explicitly assigned resources to it in the acl.xml? If I change the mapResources to use $resource[2] the tree is shown. 

Using bitnami v.2.1.1

All 3rd party plugins are disabled.

**Comment by veloraven** [comment]
@ivagarfitt thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by redelschaap** [comment]
I created a PR that fixes this issue: https://github.com/magento/magento2/pull/10334
