### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7102]
Hi,

I have a new magento site using nginx + redis cache backend + redis session front end + varnish.

After a while, for no reason and the logs are empty.. the page will render as a blank page.

**Comment by lhsatch** [comment]
Have you turned on developer mode?

**Comment by veloraven** [comment]
@craigcarnell thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by cscd98** [comment]
@veloraven going to close for now as it hasn't happened in 2.1.7
@lhsatch nope it's a live site

**Comment by lhsatch** [comment]
This might be a javascript issue. Open up the console in Chrome and check for any errors. Also sometimes you may have php errors that will may show up either in the blank page if you inspect it or it ajax is involved you can inspect the page and look in the network tab.

**Comment by lhsatch** [comment]
Although it is a live site I would put it into developer mode so that you can see the errors that are being generated
