### ISSUE TITLE
15-45 second page loads on edit product after Upgrade from 2.0.9 to 2.1.2

### ISSUE THREAD

**Issue by webguys911** [magento/magento2#7104]
### Preconditions

2500+ categories still loaded almost instantly on 2.0.9
### Steps to reproduce
1. CLI update from 2.0.9 to 2.1.2

**Comment by philipvandebriel** [comment]
We have same problem with 4000 categories.

**Comment by webguys911** [comment]
It is absolutely unbearable..I thought after merging JS files, minifying, even tried removing about half of them..worst part I think is the spinner freezing up my browser completely until it loads..you can't expect anyone to use that...I felt like it was/is so close.. 2.0.9 would and might still be usable but the top level category filter is an issue for my client..the import process is so slow too with no magmi support for v2 and no plugin on the market remotely close to comparing to magmi. 

The edit product details would load 1-2 seconds max..virtually instantly and I honestly liked the layout on 2.0.9 more than I do the 2.1.1 or 2.1.2.. It seems like its something to do with the UI elements in the newer version for the backend. I tried using php 7 with no difference.. I don't know if I have setup varnish completely correctly yet and even if I did if that would impact the performance of the backend.. I just know something doesn't seem right as like I said.. great in 2.0.9.. terrible with the new versions.

I have even tried stepping from 2.0.9 to 2.0.10 to 2.1.0 etc etc.. I am honestly considering just scratching v2 until I see some major improvements with the next release and more stability/support and extension support. v1x runs a lot faster from what I have seen on far less resources and is so much more stable with more features.. 

I don't know if its the categories for sure or not causing this issue but something leads me to that because with 30k products deleting half or most of the categories results in the page loading with reasonable time. somethings choking it up with the jquery and by god I have never seen so many requests in the console.. 

Really really disappointed 2.1.2 didn't solve this issue and I need to launch by the first.. I can't spend anymore time debugging problem after problem as its been pretty bad up to this point.. so close..

**Comment by choukalos** [comment]
This should be addressed by MAGETWO-56927 which was patched back to 2.1.3.  Please try on 2.1.3 and let us know if this is still an issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
