### ISSUE TITLE
Rest API: unable to clean cart and then unable to assign cart to customer

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#7107]
1. Magento 2.1.2
### Steps to reproduce
1. Create new cart with basic integration token
2. Add product to cart
3. Customer login (for example login before checkout)
4. Than you cant continue with calls (carts/{cartId}..) because Consumer is not authorized to access
5. You need to assign cartId to customer so you can use call PUT carts/{cartId}

{
  "customerId": 124252,
  "storeId":1
}
### Expected result
1. This should working always. So cart should be assigned to customerId
### Actual result
1. When customer have created cart it is not working
   ERROR: Cannot assign customer to the given cart. Customer already has active cart.
   There is no possibility to change this and finish order as logged customer...

**In API is missing call to clear cart something like DELETE carts/mine which is bug.**

Thanks

**Comment by SerhiyShkolyarenko** [comment]
@RUjmiak what do you mean on "basic integration token"?
Please point URL for each step. What are permissions for your integration?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by igorok27** [comment]
Hello guys! I have the same issue. Have you got any progress here?
RUjmiak is right. Either PUT guest-carts/{cartId}, body:{"customerId": 124252, "storeId":1} should reset the customer's cart, either DELETE carts/mine method should be added to the API.

**Comment by Orstio** [comment]
Here is the problem.

The guest-cart endpoint requires you to be logged in as admin, but in module-quote/Model/GuestCartManagement/Plugin/Authorization, it checks to make sure you are logged in as the specified customer:

`    public function beforeAssignCustomer(
        \Magento\Quote\Model\GuestCart\GuestCartManagement $subject,
        $cartId,
        $customerId,
        $storeId
    ) {
        if ($customerId !== (int)$this->userContext->getUserId()) {
            throw new StateException(
                __('Cannot assign customer to the given cart. You don\'t have permission for this operation.')
            );
        }
    }`

You can't pass an admin token and a customer token at the same time.

**Comment by amanraj09** [comment]
Does any one has solution for this?
Basically once I attach a cart with customer with this API `/rest/V1/carts/{cart_id}` and something goes wrong while placing the order, I cannot try placing the order since it throws `Cannot assign customer to the given cart. Customer already has active cart.`. Is there any way to detach the cart from customer?

**Comment by aishwaryasunarc** [comment]
I am facing below issues  when I tries to convert guest to customer using rest api
"message": "Cannot assign customer to the given cart. Customer already has active cart."

**Comment by trimpirim** [comment]
It has been two years, why is it closed if for a lot of us it fails without any further explanation?

**Comment by LovelySetia** [comment]
I am facing below issues when I tries to convert guest to customer using rest api
"message": "Cannot assign customer to the given cart. Customer already has active cart." Please help me to solve it.

**Comment by pankajkmr132** [comment]
I am facing the same issue of convert guest to the customer using rest API.
"message": "Cannot assign customer to the given cart. Customer already has active cart."

**Comment by sangeetajain** [comment]
Any one found the solutions for merge guest cart item to login customer cart.
