### ISSUE TITLE
Unable to run deploy:mode:set production

### ISSUE THREAD

**Issue by toddwolaver** [magento/magento2#7108]
### Preconditions
1. Install from git 
   1. magento/magento2 develop branch
   2. sha: cbe29b04210a99df03813a9840784908220dae1b
2. PHP 7.0.10 (also seen on 5.6.23)
3. MySQL  5.6.30
4. Install via command line, no sample data
### Steps to reproduce
1. run ‘php bin/magento deploy:mode:set production'
### Expected result
1. Run DI compilation and deploy static content 
### Actual result
1. DI compilation is successfully compiled
2. Deploy of static content fails with exception

```
 [Exception]                                                                                                                                                 
  Notice: Undefined index: arguments in /Users/twolaver/GIT/magento2b2b/magento/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php on line 132  

```
### Note
1. After deleting contents of var/di, 'setup:static-content:deploy -f' will run successfully

**Comment by dthampy** [comment]
Thank you for your bug report. Internal ticket MAGETWO-60218 is created to track this.

**Comment by PascalBrouwers** [comment]
Have the same issue, even after removing var/di var/generation first.

**Comment by PascalBrouwers** [comment]
Did a complete reinstall. Still the same issue.

**Comment by convenient** [comment]
Yeah @PascalBrouwers I saw the same, the only ways to bypass this would be to one of the following
1. Merge in the work done in my branch on https://github.com/magento/magento2/pull/7059
2. Comment out the following lines of code: https://github.com/convenient/mtwo/blob/7eca94436239585f8f91e981005db2928b77a1d9/app/code/Magento/Deploy/Console/Command/DeployStaticContentCommand.php#L493

**Comment by PascalBrouwers** [comment]
@convenient Tnx, it seems to have done the trick. Strange that this behaviour started since my last pull from develop on Oct 26, 2016

**Comment by veloraven** [comment]
I'm closing this issue as internal ticket was closed as duplicate.
The issue was fixed in internal ticket MAGETWO-59641 for develop branch and in MAGETWO-60366 for ver. 2.1.
