### ISSUE TITLE
composer and devDependencies

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#7109]
I'm currently running 2.1.2

`composer install --no-dev`
### Expected result

the packages in the `"require-dev"` section of `composer.json` should not be installed
### Actual result

the command installs the packages in the `"require-dev"` section of `composer.json`!

At first i thought it was a problem with composer, but this only happens inside a magento project

**Comment by BaDos** [comment]
Hi @slackerzz 

Thank you for your feedback.

Please, write steps to reproduce more detailed.

Cannot reproduce this issue.

**Comment by slackerzz** [comment]
@BaDos do you want to laugh? Cannot reproduce the issue me too :confused:
