### ISSUE TITLE
Need to trim namespace value in .xml files

### ISSUE THREAD

**Issue by thaopw** [magento/magento2#7116]
### Preconditions
1. Magento CE 2.1.x
### Steps to reproduce
1. Declare a namespace (includes a space character or newline) like value in `.xml` files tags

E.g:
- `<argument name="productDataProvider" xsi:type="object"> Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider </argument>`
### Expected result

1. Similar declare (ignore newline, space in tags value) :
   
   `<argument name="productDataProvider" xsi:type="object">Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider</argument>`

And initialize a class "Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider" in the constructor
### Actual result

1. Magento System initialize an object have namespace like " Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider " and return an error below:

>  Class 
>    Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider does not exist

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Need-to-trim-namespace-value-in-xml-files/idi-p/51526).
