### ISSUE TITLE
Switching cms widget type and then trying to insert into editor fails

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#7118]
### Steps to reproduce

1. Go to Admin => Content => Block => New Block
2. Click the widget add button
3. Select "CMS Page Link"
4. Select "CMS Static Block" (same select element)
5. Configure widget
6. Click "Insert widget"
### Expected result

1. Widget gets inserted
### Actual result

1. Insert fails.

var validationResult is false in "lib/web/mage/adminhtml/wysiwyg/widget.js" because magento tries to validate the "CMS Page Link" form instead of the "CMS Static Block" selected afterwards.

**Comment by veloraven** [comment]
@sippsolutions thank you for your feedback.
Please, identify which version of Magento you are running.

**Comment by sippsolutions** [comment]
@veloraven I'm using 2.1.1 but the bug still exists in the latest version.

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket created MAGETWO-60413

**Comment by magento-engcom-team** [comment]
Hello @sippsolutions. We were not able to reproduce this issue by following the steps you provided on clean Magento installation(v2.1.9). We are attaching a video. Please, let know whether everything is done correctly. 
[#7118.zip](https://github.com/magento/magento2/files/1368265/7118.zip)

**Comment by sippsolutions** [comment]
Hi @magento-engcom-team, try to not choose a CMS Page in the first step in your video and you will see that the second widget will not be inserted.

**Comment by magento-engcom-team** [comment]
@sippsolutions, thank you for your report.
We've created internal ticket(s) MAGETWO-60413 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
