### ISSUE TITLE
Field not sanitizied for HTML tags.

### ISSUE THREAD

**Issue by yariksheptykin** [magento/magento2#7119]
[removed content of security report]

**Comment by pboisvert** [comment]
@piotrekkaminski Piotr--can you validate if this is a potential issue or if other mechanisms are in place to prevent impact.

**Comment by piotrekkaminski** [comment]
reported as APPSEC-1619 and removing here. @yariksheptykin please next time report security issues to security@magento.com. Thanks.

**Comment by yariksheptykin** [comment]
@piotrekkaminski , alright, sorry about that.
