### ISSUE TITLE
It's possible to create multiple products with the same SKU

### ISSUE THREAD

**Issue by joshdifabio** [magento/magento2#7121]
### Preconditions

This issue exists in current HEAD in the develop branch (0c6227d2c0b68f55bc1d7fb0e878a3c597b50653). The bug is very apparent from looking at the code. The environment is irrelevant to the issue.
### Steps to reproduce

Save a non-existent product more than once simultaneously (e.g. via the REST API).
### Expected result

For all but the "winning" save operation (i.e. the one which reaches the database first), either an exception should be raised or updates should be made to the product which was created by the "winning" save operation.
### Actual result

Either:
Multiple products are created with the same SKU.
Or:
Multiple products are created with different SKUs (a number is appended to the end of the SKU to make it unique). THIS IS REALLY BAD! If the application detects a duplicate SKU when creating a product then this should be an error! It is critical that products are created with the actual SKU a business uses, and not some other meaningless SKU.

The cause of this issue is very clear when looking at the code [1] [2]. SKU uniqueness is enforced within the application code but not by a constraint in the database. This is totally not robust enough for an application of Magento's importance. Please add database constraints to enforce SKU uniqueness and remove this damaging `_generateUniqueSku()` method [1].

[1] [Uniqueness is enforced in application code](https://github.com/magento/magento2/blob/0c6227d2c0b68f55bc1d7fb0e878a3c597b50653/app/code/Magento/Catalog/Model/Product/Attribute/Backend/Sku.php#L99)
[2] [There is no uniqueness constraint in the database schema for SKU](https://github.com/magento/magento2/blob/0c6227d2c0b68f55bc1d7fb0e878a3c597b50653/app/code/Magento/Catalog/Setup/InstallSchema.php#L93)

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue MAGETWO-61468 is created.

**Comment by sinisa86** [comment]
Issue in progress @sinisa86

**Comment by sathishrajr** [comment]
I am working on this issue.

**Comment by magento-engcom-team** [comment]
@joshdifabio, thank you for your report.
We've created internal ticket(s) MAGETWO-61468, MAGETWO-62571 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi there

**Comment by dimaperedriy** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@dimaperedriy thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by strell** [comment]
#mageconf

**Comment by strell** [comment]
@dimaperedriy did you start to work on this issue?

**Comment by Winfle** [comment]
#distributed-cd

**Comment by Winfle** [comment]
@mrodespin Hello, do you still work on this issue?

**Comment by ecomchallenger** [comment]
Hello there. I will look at this issue. #WroCD.

**Comment by wokisajn** [comment]
Hi, everybody on #WroCD :)
This issue looks good

**Comment by wokisajn** [comment]
#WroCD

**Comment by magento-engcom-team** [comment]
@wokisajn thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ecomchallenger** [comment]
#WroCD

**Comment by magento-engcom-team** [comment]
@ecomchallenger thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by KalimuthuLakshmanan** [comment]
I am working on this at #dmcdindia1

**Comment by KalimuthuLakshmanan** [comment]
i have run product add script simultaneously but unable to reproduce this issue in magento 2.3
