### ISSUE TITLE
Auto suggestion not working in my account page with https

### ISSUE THREAD

**Issue by sneha-sukumaran** [magento/magento2#7123]
### Preconditions
1.  Magento 2.0.10
2. SSL Certificate
### Steps to reproduce
1. Install magento 2.0.10 with sample data
2. Set https for base secure urls for frontend in admin
3. Login to magento frontend
4. Goto My account page
5. Click on search bar and type a text ex: pan
### Expected result
1. Autosuggestion's for "pan" will be displayed
### Actual result
1. No Suggestions shown

When i checked with chrome developer tools. Cross origin error was thrown in console

**Comment by Sergeacc** [comment]
@sneha-sukumaran Search Suggestions available on Magento Enterprise Edition only.
More detailes: http://docs.magento.com/m2/ee/user_guide/catalog/search-suggestions.html

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
