### ISSUE TITLE
Number input fields have invalid 'maxlength' attribute

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7125]
### Preconditions

1. v2.1.1
### Steps to reproduce

1. Open `module-catalog/view/frontend/templates/product/view/addtocart.phtml`

Note that `addtocart.phtml` is just one example -- there could be other number inputs with the `maxlength` attribute in other templates.
### Expected result

1. Number input fields can have `min` and `max` attributes, but not `maxlength`, which is only applicable to text input fields. Here's the list of permitted attributes for number inputs:

https://www.w3.org/TR/html-markup/input.number.html
### Actual result

1. The `maxlength` attribute is incorrectly used with a number input field.

**Comment by odubovyk** [comment]
Thank you for the report. 
Internal ticket MAGETWO-60127

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
The issue is already fixed in 2.2.0
