### ISSUE TITLE
magento 2.1.2 Configurable product "%1" does not have sub-products

### ISSUE THREAD

**Issue by suraleb** [magento/magento2#7126]
magento 2.1.2 php 5.6
Create product
Create 2 attributes color
Save product

On product page receive exception:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Configurable product "test bag2" does not have sub-products

Exception #0 (Magento\Framework\Exception\LocalizedException): Configurable product "test bag2" does not have sub-products
#0 /media/sf_Projects/svmg2/vendor/magento/module-configurable-product/Pricing/Price/FinalPrice.php(43): Magento\ConfigurableProduct\Pricing\Price\ConfigurablePriceResolver->resolvePrice(Object(Magento\Catalog\Model\Product\Interceptor))
#1 /media/sf_Projects/svmg2/vendor/magento/framework/Pricing/Price/AbstractPrice.php(98): Magento\ConfigurableProduct\Pricing\Price\FinalPrice->getValue()
#2 /media/sf_Projects/svmg2/vendor/magento/module-configurable-product/Model/Product/Type/Configurable/Price.php(28): Magento\Framework\Pricing\Price\AbstractPrice->getAmount()
#3 /media/sf_Projects/svmg2/vendor/magento/module-catalog/Model/Product.php(1156): Magento\ConfigurableProduct\Model\Product\Type\Configurable\Price->getFinalPrice(NULL, Object(Magento\Catalog\Model\Product\Interceptor))
#4 /media/sf_Projects/svmg2/var/generation/Magento/Catalog/Model/Product/Interceptor.php(583): Magento\Catalog\Model\Product->getFinalPrice(NULL)
#5 /media/sf_Projects/svmg2/vendor/magento/module-catalog/view/frontend/templates/product/view/opengraph/general.phtml(17): Magento\Catalog\Model\Product\Interceptor->getFinalPrice()
#6 /media/sf_Projects/svmg2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/media/sf_Proje...')
#7 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/media/sf_Proje...', Array)
#8 /media/sf_Projects/svmg2/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/media/sf_Proje...')
#9 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/media/sf_Proje...')
#10 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#11 /media/sf_Projects/svmg2/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#12 /media/sf_Projects/svmg2/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#13 /media/sf_Projects/svmg2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('opengraph.gener...')
#14 /media/sf_Projects/svmg2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('opengraph.gener...')
#15 /media/sf_Projects/svmg2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('opengraph.gener...')
#16 /media/sf_Projects/svmg2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('opengraph.gener...', true)
#17 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/AbstractBlock.php(503): Magento\Framework\View\Layout\Interceptor->renderElement('opengraph.gener...', true)
#18 /media/sf_Projects/svmg2/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#19 /media/sf_Projects/svmg2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/media/sf_Proje...')
#20 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/media/sf_Proje...', Array)
#21 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/media/sf_Proje...')
#22 /media/sf_Projects/svmg2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#23 /media/sf_Projects/svmg2/vendor/magento/framework/View/Result/Page.php(236): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /media/sf_Projects/svmg2/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#25 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#26 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#27 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#28 /media/sf_Projects/svmg2/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#29 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#30 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#31 /media/sf_Projects/svmg2/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#32 /media/sf_Projects/svmg2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#33 /media/sf_Projects/svmg2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#34 /media/sf_Projects/svmg2/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#35 /media/sf_Projects/svmg2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#36 /media/sf_Projects/svmg2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#37 {main}

**Comment by veloraven** [comment]
@suraleb thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also provide more detailed steps.

**Comment by MaksimPaliy** [comment]
@veloraven Just try to add new configurable product with 2 atributes

**Comment by jzembala** [comment]
Same exception is throwing to support_report.log while displaying category page (with configurable products). 
As I saw in core code, this exception appears when the cheapest product is out of stock (has _stock_status_ != 1 in table _cataloginventory_stock_status_).

Info: 
After upgrade 2.1.0 to 2.1.2 
PHP 7.0.6

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
@MaksimPaliy , @bizzi , if this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
