### ISSUE TITLE
Decimal input validation (for product attributes) fails with some locales (adminhtml)

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#7127]
When using a language that uses a comma as a decimal separator, input fields with decimal validation act weird and fail to validate. This happens with product attributes, I haven't tested it with input fields on other pages.
### Preconditions

Using Magento 2.1.2 on nginx, PHP 7 and MySQL 5.6 with admin language set to Dutch (Nederlands for The Netherlands).
#### Saving a product attribute
1. Go to Stores > Attributes > Product > Edit attribute, e.g. "weight"
2. Expand section "Advanced Attribute Properties"
3. Set "Default Value" to "0,01" (as it should be noted in Dutch)
4. Set "Input Validation for Store Owner" to "Decimal Number"
5. Save and continue to edit the attribute
6. Save the attribute again.
#### Saving a product
1. Go to Products > Catalog > Product > Edit a product
2. Set a decimal validated attribute (e.g. "Weight") to "0,01"
3. Save the product
#### Saving a product attribute
1. The "Default Value" should be displayed as "0,01"
2. The attribute should be saved again successfully
#### Saving a product

The product should be saved successfully
#### Saving a product attribute
1. The "Default Value" is displayed as "0.01"
2. Attribute was not saved and error given: "Invalid default decimal value"
#### Saving a product
1. Product was not saved
2. An error below the field is shown: "Please enter a valid number in this field"
3. Change "0,01" to "0.01"
4. Save and continue to edit the product
5. The value in this field is being displayed as "0,01" again
6. The product cannot be saved without changing this field again

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket MAGETWO-57833

**Comment by magento-engcom-team** [comment]
@redelschaap, thank you for your report.
We've created internal ticket(s) MAGETWO-81462 to track progress on the issue.

**Comment by rodrigowebjump** [comment]
Working on it

**Comment by okorshenko** [comment]
Hi @rodrigowebjump please accept the invite

**Comment by rodrigowebjump** [comment]
@okorshenko Which invite?

**Comment by magento-engcom-team** [comment]
@redelschaap, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
