### ISSUE TITLE
No Puerto Rico in Directory Module

### ISSUE THREAD

**Issue by comdiler** [magento/magento2#7129]
### Preconditions
1. Magento CE. Tag 2.1.2
### Steps to reproduce
1. Open Admin Panel
2. Create New Customer
3. Add New Customer Address
4. Select Country "Puerto Rico"
### Expected result
1. Puerto Rico should be present in list
### Actual result
1. No Puerto Rico in list

![screen shot 2016 10 21 at 15 40 57](https://cloud.githubusercontent.com/assets/1975805/19600382/0de60852-97a5-11e6-903c-ca5692d07d0f.png)

**Comment by sennin32** [comment]
Why this case has been closed?
There's no Puerto Rico in the list...

**Comment by comdiler** [comment]
@sennin32 
![screen shot 2017-03-10 at 10 25 58](https://cloud.githubusercontent.com/assets/1975805/23789646/064f76c4-057c-11e7-9317-5e4282c7de9a.png)
