### ISSUE TITLE
Magento 2.1.0 Admin Front End Pages not Working - Fresh Install

### ISSUE THREAD

**Issue by badtad** [magento/magento2#7130]
Performed an install of Magento 2.1.0 from PLESK Panel.    Website loads with LUMA frontpage which is fine.    When I login to the admin panel, the panel appears ok until I go to:
1. Content -->Design---> Configuration wherein I get a blank screen.
2. Products-->Categories-->Add Subcategory  wherein the frontend does not allow me to input a subcategory
3. Products-->Catalog-->Add Product  where there is no input field

I have cleared all cache and followed the steps in http://docs.magento.com/m2/ce/user_guide/Resources/pdf/Magento_Community_Edition_2.0_User_Guide.pdf

I have PHP setup as per the attached screen shot.

Any assistance or pointers would be appreciated.  Thanks - Mike

Any assistance would be appreciated.    

![screen shot 2016-10-21 at 10 35 25 am](https://cloud.githubusercontent.com/assets/22983232/19602181/3c244498-977a-11e6-95a5-0bff0d723be3.png)
![screen shot 2016-10-21 at 10 33 22 am](https://cloud.githubusercontent.com/assets/22983232/19602183/3c2684c4-977a-11e6-9c82-c067dd0e7c93.png)
![screen shot 2016-10-21 at 10 28 52 am](https://cloud.githubusercontent.com/assets/22983232/19602184/3c271754-977a-11e6-8049-dca82f0f25c0.png)
![screen shot 2016-10-21 at 10 23 58 am](https://cloud.githubusercontent.com/assets/22983232/19602182/3c257ea8-977a-11e6-8d50-724f27db3c94.png)

**Comment by sevos1984** [comment]
Have you cleared browser cache? Check your browser's console for errors as well as magento logs.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
