### ISSUE TITLE
Magento 2.1.2 Private Scope Blocks Caching

### ISSUE THREAD

**Issue by rob1256** [magento/magento2#7131]
### Preconditions
1. Magento 2.1.2
2. PHP 7
3. MySQL 5.6
4. Nginx
### Steps to reproduce
1. Set `$this->_isScopePrivate = true;` in your block constructor (after `parent::__construct()`)
2. Load a page with the block displayed and FPC enabled
3. Change the contents of your block
4. Reload page
### Expected result
1. New block content displayed as content is AJAX'd in via `/page_cache/block/render/`
### Actual result
1. Cached content is still shown, unless you clear browser cache manually.

I was using this in my own project to show/hide a pop-up based on whether a cookie was present or not.  Setting your block scope to private means that Magento will AJAX in the block content after the initial page load and replace some placeholder content with the actual content.  While it does do this, it doesn't work fully because of the following line:
https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L228

This is causing the browser to cache the response from the AJXA, thus nullifying the point of the private scope.

**Comment by orlangur** [comment]
So, why content of private scope block should not be cached for concrete user in browser?

> I was using this in my own project to show/hide a pop-up based on whether a cookie was present or not

This is misuse of private scope block feature. You don't need excessive AJAX call each time cookie is deleted or added.

> Setting your block scope to private means that Magento will AJAX in the block content after the initial page load and replace some placeholder content with the actual content

Yep, and also cache the result on client side so that AJAX call is not performed EACH TIME you open the same page.

**Comment by rob1256** [comment]
Could I ask what the use-case of the private scope block feature is then?  Is it to try and stop any crawlers indexing the content?

At the very least it seems that even if this feature wasn't intended to allow you to stop caching a particular block; it could quite easily be re-appropriated to allow for that use-case.

**Comment by jameshalsall** [comment]
The block will only be loaded in via XHR (AJAX) if your layout does not contain a block with attribute `cacheable="true"`. When it finds a non-cacheable block it won't cache any of the layout (see `Magento\PageCache\Observer\ProcessLayoutRenderElement::execute()` on line 105.

**Comment by orlangur** [comment]
Caching of AJAX requests in browser cache - https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L228 - is correct system behavior.

Note that although some core code is still using `isScopePrivate` it shall not be used in any new code: http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html#config-cache-priv-how-block Please check that article to learn how FPC hole punching should be implemented nowadays.
