### ISSUE TITLE
Magento installs several Magento_TestModule modules

### ISSUE THREAD

**Issue by hamdrew** [magento/magento2#7132]
### Preconditions
1. Magento CE 2.1.0, obtained using Composer: [my composer.json file](https://gist.github.com/hamdrew/6d4eca506e362b318f8e9f0e63ef3729)
2. `{MAGE_ROOT}/app/etc/config.php` exists and does not have any _Magento_TestModule_ modules listed.
### Steps to reproduce
1. Run the Magento CLI installer with an empty database
### Expected result
1. Magento should only install the modules listed in `{MAGE_ROOT}/app/etc/config.php`. No test modules should be installed
### Actual result
1. Magento installs several _Magento_TestModule_ modules
2. Magento complains about a test integration failing when logging in: 
   ![screenshot](https://cloud.githubusercontent.com/assets/4921666/19602918/ad5c44d6-9774-11e6-9173-3ccb4f196ade.png)

**Comment by BaDos** [comment]
Hi @hamdrew 

Thank you for your feedback.

I've installed Magento using your composer.json file.
Cannot reproduce this issue.

Did you upgrade Magento from 2.0.7 to 2.1.0 or installed new version using your composer.json?
Was `{MAGE_ROOT}/app/etc/config.php` file  created by you or created by previous version of Magento?

Please write steps to reproduce more detailed.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
