### ISSUE TITLE
Session Issues

### ISSUE THREAD

**Issue by sharmashashank342** [magento/magento2#7136]
I have faced an unimaginable issue related to Session between 2 Magento 2.1.0 Running on Parallel Folders of Same Server.

1st site URL : http://104.236.212.58/e3donline/
2nd site URL : http://104.236.212.58/splash/

i was facing a bit issues of Minicart Functionalities on my 1st site but was working fine on 2nd Site
so i choose to Debug the issue.

I added the Product Named Nike Dry Team Brazil, (that belongs to my 2nd website) to Cart and Minicart worked Fine.
Then i went to My 1st Website URL and noticed an Item Count 1 in Minicart.
when i inspected the minicart, i got shocked to see that it was the same product Nike Dry Team Brazil that was seen in my Cart.

when i clicked on Edit Item Link, it redirected me to 2nd Website Cart product Configure Page.

shocked to see such a horrible bug.
### Preconditions

1. Magento Version i used on Both website is Magento version 2.1.0
2. PHP version i am using on my Both website is 5.6.24-1+deb.sury.org~xenial+1
3. MySQL version used on both website is 5.6
### Steps to reproduce

1. Just put 2 Magento 2.1 on parallel Folder on Same Server and try adding 1 product to Cart in 1st Magento site.
2. after that you need to Refresh the Page on 2nd Magento site and can check tif the issue arrises.
3. even Can use My E Shop Stores (URL of Both webstores are provided above) for testing purpose.
### Expected result

1. The Sessions should have worked seprately and properly on both websites.
   Not faced this kind of issues in Magento 1.9.
### Actual result

![sessionbug](https://cloud.githubusercontent.com/assets/18499565/19611381/21a23f0a-97ff-11e6-8e4a-74f7cd7c5675.png)
![sessionbughighlighted](https://cloud.githubusercontent.com/assets/18499565/19611382/21db33be-97ff-11e6-82a1-a109a674f845.png)
![splash](https://cloud.githubusercontent.com/assets/18499565/19611558/d79c8f86-97ff-11e6-8f2a-b8017209c9c2.png)

Please make Magento 2 Bug Free as Magento 2 is an awesome update provided from Magento 1 (Talking UI wise).

Thanks 
Shashank Sharma

**Comment by orlangur** [comment]
Hi @sharmashashank342,

Magento 2 is not intended to work in such configuration yet. You cannot have two Magento instances on the same host.

The problem is not in session but that local storage is shared among two of instances. To fix this you can add several aliases pointing to 104.236.212.58 IP address.

I'm not sure why it is not fixed yet by proper namespacing of local storage data as looking into [implementation](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L29) it seems to be trivial change.

There was similar answer by @sidolov or @ishakhsuvarov to similar issue but I couldn't find it quickly.

**Comment by Sergeacc** [comment]
Internal ticket created MAGETWO-70328

**Comment by magento-engcom-team** [comment]
@sharmashashank342, thank you for your report.
We've created internal ticket(s) MAGETWO-70328 to track progress on the issue.

**Comment by sharmashashank342** [comment]
Noted.

Thanks

**Comment by magento-engcom-team** [comment]
@sharmashashank342, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
