### ISSUE TITLE
Rest API V1 on Checkout/cart address request eror 404

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#7137]
When on checkout/cart page, the system shoots 500 error on POST, and 404 on GET request at /rest/frca/V1/carts/mine/estimate-shipping-methods URI.

If I try just GET request on /rest/frca/V1/carts/mine/, proper XML response is generated.

The following exception message is being logged upon the error:

> [2016-10-21 08:46:55] main.CRITICAL: LogicException: Property "Street" does not have corresponding setter in class "Magento\Quote\Api\Data\EstimateAddressInterface". in /var/data/mfs/www/magento/lib/internal/Magento/Framework/Reflecti
> on/NameFinder.php:100
> Stack trace:
> # 0 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Reflection/NameFinder.php(59): Magento\Framework\Reflection\NameFinder->findAccessorMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Street', 'getStreet', 'isStreet'
> 
> )
> # 1 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(158): Magento\Framework\Reflection\NameFinder->getGetterMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Street')
> # 2 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(322): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('Magento\Quote\A...', Array)
> # 3 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(119): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, 'Magento\Quote\A...')
> # 4 /var/data/mfs/www/magento/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php(101): Magento\Framework\Webapi\ServiceInputProcessor->process('Amasty\Shipping...', 'estimateByAddre...', Array)
> # 5 /var/data/mfs/www/magento/app/code/Magento/Webapi/Controller/Rest.php(299): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
> # 6 /var/data/mfs/www/magento/app/code/Magento/Webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
> # 7 /var/data/mfs/www/magento/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> # 8 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 9 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> # 10 /var/data/mfs/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> # 11 {main}
> 
> Next Exception: Report ID: webapi-5809d5ff94402; Message: Property "Street" does not have corresponding setter in class "Magento\Quote\Api\Data\EstimateAddressInterface". in /var/data/mfs/www/magento/lib/internal/Magento/Framework/Web
> api/ErrorProcessor.php:195
> Stack trace:
> # 0 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
> # 1 /var/data/mfs/www/magento/app/code/Magento/Webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
> # 2 /var/data/mfs/www/magento/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> # 3 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 4 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> # 5 /var/data/mfs/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> # 6 {main} [] []

I am running latest M2 2.1.2 under PHP7.0.12 with Nginx in front.

**Comment by veloraven** [comment]
@devdesco-ceo thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also provide exact requests you use.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by shuaiZend** [comment]
M2.1.6 +1

**Comment by themoonwatcher** [comment]
This happened to me with Magento 2.2.6 and 2.3.0. My fix was to add this to Nginx confog:
```
location ~ ^/rest {
  return 307 https://$host/index.php$request_uri;
}
```
