### ISSUE TITLE
Installation fails due to specifying an absolute path: '/usr/bin/php'

### ISSUE THREAD

**Issue by Viveur** [magento/magento2#714]
#### Current Behaviour

MCrypt Extension is loaded as part of MAMP's PHP (phpinfo.php confirms this). 

MAMP's version of PHP is specified in my $path 

Running 'which php -v' returns MAMP's version of PHP.

However as Magento's installer calls /usr/bin/php it forces the use of OS X's built-in version of PHP which does not have the extension loaded.

`
/usr/bin/php -f '/Users/me/Documents/DATA/WWW/magento2/dev/shell/maintenance.php' -- --set='1' 2>&1 
`

This results in the error:

`
[ERROR] exception 'Exception' with message 'exception 'Exception' with message 'Module 'Magento_Core' depends on 'mcrypt' PHP extension that is not loaded.' in /Users/[name]/Documents/WWW/magento2/lib/internal/Magento/Framework/Module/DependencyManager.php:56  
`
#### Suggested Behaviour

Install script should possibly use the the system's preferred version of PHP rather than specifying an absolute path.

**Comment by muasir** [comment]
This issue was present when we used exec.  Now we don't use exec, so this shouldn't be a problem.
