### ISSUE TITLE
Fedex Plugin Doesn't support LTL only Air Freight

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7141]
Fedex Plugin Doesn't support LTL only Air Freight. Only 1 Day, 2 Day, and 3 Day freight work. I called fedex and they said its not sending the appropriate data to there service for this to work.

**Comment by veloraven** [comment]
@joshspivey thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please also explain what do you mean as 'FedEx Plugin'.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
