### ISSUE TITLE
Minicart shows always the base image for configurable product but not the base image for the options selected

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#7144]
Magento 2.1.2
 Plesk 12.5.
 Apache 7.08
 MySql 5.6.29
 Nginx
### Steps to reproduce
1.  Create configurable product with many different color
2.  set different images per color attribute
3.  add product to cart selecting a color that is different from the base image of the product
### Expected result
1. in the minicart i see the base image for the choosen color 
### Actual result
1. in the minicart i see the base product image instead the base image for the color that has been choosen

My personal opinion: this issue must be marked with high priority. Customers that reviews the minicart may be confused and the sale can probably be lost

Thanks,
PierAle

**Comment by orlangur** [comment]
There is an option to control this behavior in Admin UI I believe: https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/etc/config.xml#L12 Not sure why is uses parent product image by default though.

**Comment by PierAlex** [comment]
Hi Vlad,
thank you very much.
I was not able to find the configuration because i was looking for it only in tabs General, Catalog and in the theme config.
This setting is in Sales ->Checkout -> Cart. The default value is the parent image.
