### ISSUE TITLE
Possible to set sales rules/coupons with expiration dates before effective date.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7145]
Magento 2.0.9 and greater
### Steps to reproduce
1. Create a cart price rule (or catalog rule)
2. Set a normal start date
3. Set an expiration date before the date, in our case it was set to some date in 1942
### Expected result

1. Magento 2 shouldn't allow this to begin with, form should validate that you have set the date to something ridiculous.
### Actual result

The rule doesn't work, as expected, but this isn't obvious unless you double check the date, because the first two digits of the year are truncated. Only loading the date selector shows the true year.

So you might see a date like 1/1/15 and the expiration is 1/1/42 and assume its 2042, when its really 1942. This is more obvious on checking salesrule_coupon and the expiration date is 0000-00-00 00:00:00 so the rule doesn't work at all.

**Comment by dthampy** [comment]
internal jira ticket MAGETWO-60259 has been created for this issue.

**Comment by magento-engcom-team** [comment]
@sylink, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
