### ISSUE TITLE
active product_count in categories search

### ISSUE THREAD

**Issue by povesma** [magento/magento2#7147]
It is very useful to know number of active products (status = 1) in the search categories API call. Currently we can see total number of all products (including disabled).
### Preconditions

Magento 2.1.2
### Steps to reproduce
1. /rest/V1/categories?root_category_id=24
### Expected result

{
  "id": 24,
  "parent_id": 23,
  "name": "Best Sellers",
  "is_active": true,
  "position": 2,
  "level": 3,
  "product_count": 5,
  **"active_product_count": 3,** <---- add this one or similar, showing active products only
  "children_data": []
}
### Actual result

{
  "id": 24,
  "parent_id": 23,
  "name": "Best Sellers",
  "is_active": true,
  "position": 2,
  "level": 3,
  **"product_count": 5,** <----  total product count only, which includes disabled products
  "children_data": []
}

**Comment by pboisvert** [comment]
@povesma thanks for the suggestion

@mbrinton01 passing to you until Misha is ramped up

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/active-product-count-in-categories-search/idi-p/54643).
