### ISSUE TITLE
Admin WYSIWYG upgrade to latest Tiny MCE 4.*

### ISSUE THREAD

**Issue by darrenjennings** [magento/magento2#7149]
On latest mangeto version, would love to see TinyMCE upgraded and maintained since Magento is several versions behind latest TinyMCE. https://www.tinymce.com/

Newest version should include integration with image uploading/resizing/editing, magento widget/variable insertion etc.

I've attempted to upgrade the core myself so as to offer a PR, but it broke too many things along the way. :)

**Comment by darrenjennings** [comment]
I was able to get TinyMCE 4 working with Magento 1.7. Will post a PR here if I have time to get it working with Magento2.

**Comment by pboisvert** [comment]
thanks @darrenjennings new features in the latest version look really interesting so I'd imagine a PR would be very valuable for the community

@tkacheva please review in context of upcoming CMS work

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-WYSIWYG-upgrade-to-latest-Tiny-MCE-4/idi-p/54640).

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69234
