### ISSUE TITLE
Hidden fields are not used on the product page

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7150]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Go to /caesar-warm-up-pant.html and select a color and size.
### Expected result

1. The option values should be stored as hidden input fields (`<input type="hidden">`).
### Actual result

1. The option values are stored as normal text input fields and hidden using CSS, which is a bit hacky unless there is a good reason for doing it this way:

```
<input class="swatch-input super-attribute-select" name="super_attribute[93]" type="text" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px">
<input class="swatch-input super-attribute-select" name="super_attribute[184]" type="text" value="" data-selector="super_attribute[184]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px">
```

**Comment by thdoan** [comment]
I see this comment in the source (`swatch-renderer.js`):

> This control shouldn't have "type=hidden", "display: none" for validation work :(

Since the swatches already act as a quasi-validator by nature (i.e., you can't normally select an invalid color or size since only valid ones are rendered), hidden input fields should be used instead. If technically inclined types want to hack the code to add an invalid or out-of-range option, then there is no client-side solution that can stop them, and in such cases Magento would fall back to the backend validation anyway.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We've created internal ticket(s) MAGETWO-81884 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
