### ISSUE TITLE
Error when run code in external file/script in magento 2.1.2 PHP7

### ISSUE THREAD

**Issue by tranductrong92** [magento/magento2#7151]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0
### Steps to reproduce

1. Run code in external file/script in root folder
2. Sample code

require **DIR** . '/app/bootstrap.php';

class App
    extends \Magento\Framework\App\Http
    implements \Magento\Framework\AppInterface
{
    public function launch()
    {
        echo "test";
        // test code here  
        // must return the response
        return $this->_response;
    }

```
public function catchException(\Magento\Framework\App\Bootstrap $bootstrap, \Exception $exception)
{
    return false;
}
```

}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/*\* @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('App');
$bootstrap->run($app);
### Actual result

1. 
   PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\App\Http::__construct() must be an instance of Magento\Framework\Event\Manager, none given, called in ...vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in ...vendor/magento/framework/App/Http.php:85
2. I add code
   protected $manager;
   protected $objectManager;
   
   public function __construct(
       \Magento\Framework\Event\Manager $manager,
       \Magento\Framework\ObjectManager\ObjectManager $objectManager
   
   ) {
       $this->_manager = $manager;
       $this->_objectManager = $objectManager;
   }

but it still error

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App::__construct() must be an instance of Magento\Framework\Event\Manager, instance of Magento\Framework\ObjectManager\ObjectManager given, called in ...vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in...

**Comment by mrkhoa99** [comment]
@tranductrong92 if you want to create a playground, please, see this post: http://magento.stackexchange.com/questions/39981/how-can-i-create-my-dirty-playground-file-in-magento-2

**Comment by tranductrong92** [comment]
@mrkhoa99 I consult to it, but version 2.1.2 is not working and display errors @@.. version 2.0.7 works fine

**Comment by mrkhoa99** [comment]
@tranductrong92 , seem that your constructor arguments not correct, should try:

```
public function __construct(
        \Magento\Framework\ObjectManagerInterface $objectManager,
        \Magento\Framework\Event\Manager $eventManager,
         .....
    )
```

Take a look at **vendor/magento/framework/App/Http.php** in Magento 2.1.2 to see more details.

**Comment by tranductrong92** [comment]
@mrkhoa99 you can fix sample code in **Steps to reproduce**?...I have tried many ways but not correct :(

**Comment by mrkhoa99** [comment]
@tranductrong92  try with my dirty playground: https://gist.github.com/mrkhoa99/b8648168406cb222f5800e7ec0ebc603

**Comment by tranductrong92** [comment]
@mrkhoa99 I found the cause of the error. After run command  bin/magento setup:di:compile then my dirty playground has error, previously, it works fine...why?

**Comment by mrkhoa99** [comment]
@tranductrong92 you should read more here: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html. Please close this issue if your issue solved.

**Comment by tranductrong92** [comment]
@mrkhoa99 I've read it and I don't understand why the issue failed. This command bin/magento setup:di:compile is required.

**Comment by mrkhoa99** [comment]
@tranductrong92 this is because your Magento application is in `production` mode, please, switch to `developer` mode: `deploy:mode:set developer`

http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html
http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html

**Comment by tranductrong92** [comment]
@mrkhoa99 oh thank you very much!...so this command bin/magento setup:di:compile only used developer mode.
