### ISSUE TITLE
Product page validation error message not in correct position

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7152]
### Preconditions

1. Magento v2.1.1
### Steps to reproduce

1. Go to /caesar-warm-up-pant.html
2. Without selecting a color or size, click on 'Add to Bag'
### Expected result

1. The color and size options should be highlighted alerting the customer which fields are incomplete.
### Actual result

1. The color and size options are not highlighted. There's simply two redundant error messages below the add-to-cart button with no context provided:

![image](https://cloud.githubusercontent.com/assets/4110567/19637329/0330012a-9a01-11e6-8f3b-e5af0a54c944.png)

**Comment by dthampy** [comment]
internal jira ticket to track this issue - MAGETWO-60272

**Comment by vkranjith** [comment]
Is it fixed in release 2.1.2 or 2.1.3?

**Comment by veloraven** [comment]
This issue was fixed in ver. 2.1.4 in scope of internal ticket MAGETWO-57832.
Original internal ticket was closed as a duplicate.
Closed.
