### ISSUE TITLE
Incorrect strong password validation

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#7156]
During customer creation I'm trying to put password that should be marked as strong, but validation fails.
### Preconditions
1. Magento 2.1.2 installed via composer
### Steps to reproduce
1. Go to Customer registration page
2. Put in password & confirmation fields following password - "фффФФФ123" (on russian keyboard layout)
3. Click "Sign up" button
### Expected result
1. Password should be marked as valid
### Actual result
1. I'm getting following error:
   "Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters."
   ![image](https://cloud.githubusercontent.com/assets/1873745/19638267/d0a0be90-99db-11e6-8e8e-674f88ed5b25.png)

**Comment by ilol** [comment]
@ihor-sviziev,  Can you use latin alphabet for your purposes?

**Comment by ihor-sviziev** [comment]
@ilol for latin alphabet it works as should, however for non-latin alphabet - validation fails.

**Comment by odubovyk** [comment]
I close this as cyrillic symbols are not supported for the password. Password must use latin symbols
