### ISSUE TITLE
Relative url does not trigger sections update.

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#7160]
### Preconditions
1. Set up an action that will trigger a section refresh
2. Example: test/manage/add
### Steps to reproduce
1. Submit a post request to action url (relative). $.post('test/manage/add'...
### Expected result
1. A call to the section to update.
### Actual result
1. Nothing. Or other sections such as messages, but not the section you desired. Example: cart.

Why does this not function correctly based on a relative url? Why must it be an absolute url? This was one of the most difficult problems to troubleshoot for me.

**Comment by veloraven** [comment]
@LiamFielding thank you for your feedback.
Please identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
