### ISSUE TITLE
Magento upgrade documentation to 2.1 broken

### ISSUE THREAD

**Issue by vanderlee** [magento/magento2#7162]
The 2.0 to 2.1 upgrade process as described in the documentation at http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_21-upgrade.html is badly broken.
### Preconditions
1. Working Magento 2.0.10
### Steps to reproduce
1. Click downloadlink to http://www.magento.com/download for patch MDVA-532 at; redirected to 404-like page at https://www.magentocommerce.com/download
2. Google for MDVA-532; found on https://u.magento.com/downloads/magento/.
3. Try to find link so I can download straight to my webserver. Broken; apparently, can only download from a browser.
4. Select .zip version of MDVA-532, click download link, apparently requires login (p.s. image of login popup broken).
5. Logged in, Select .zip version, click download link. Broken; redirected to same download page without download starting (tried with Chrome, Firefox, Edge).
6. Tried downloading the .gz and .bzip versions; same broken result.
### Expected result
1. For not all (including unnecessary) steps being broken. Especially not for fixing critical security bugs.
### Actual result
1. Thinking about ditching Magento 2 for something that is less broken (perhaps Magento 1.9?).

**Comment by stamster** [comment]
IMHO and from our latest experience, you should stay on 2.0.x stack.
2.1.1. is even more broken. We had a hell of our time to push 2.1.0 into production recently.
M 1.x is going to be deprecated / obsolete, that's why we wanted to use M2 at first place, it turned out that was a big mistake.

**Comment by ghost** [comment]
We'll track this issue in the devdocs repo.

**Comment by ghost** [comment]
@vanderlee I cannot reproduce your issue. I downloaded `zip` and `tar.gz` for CE without issues. Can you try again?

**Comment by vanderlee** [comment]
Tried Chrome, Firefox, Opera, Edge, IE11 and Safari; all failed.

The login screen looks like this:
![image](https://cloud.githubusercontent.com/assets/649240/19730452/94902812-9b9a-11e6-8594-bcf2d89ae648.png)
I'm logged correctly, but then the download simply does not start.

**Comment by vanderlee** [comment]
Just checked on another PC w/ Chrome: the login popup looked okay, but still no download.

**Comment by ghost** [comment]
I logged in the same way as you did on Chrome. I'll see if I can find someone internally who can explain it.

**Comment by vanderlee** [comment]
There seems to be a new download page today: https://magento.com/tech-resources/download, which DOES work. The old URL https://www.magentocommerce.com/download now redirects to that page too.

It's still not ideal, not being able to download to the server directly, but atleast I can download again.

**Comment by ghost** [comment]
@vanderlee You're correct, confirmed by Operations. We had a bad alias for that page. I wonder how it worked for me. Anyway, thanks for reporting this and sorry for the trouble.

It should be fixed now.

**Comment by magento-engcom-team** [comment]
The issue already fixed. @vanderlee thank you for report
