### ISSUE TITLE
Create a dropdown attribute can have unintended effects on eav_entity_attribute_option table

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#7163]
When creating a new attribute of type dropdown you can pass an 'option' key to your array to provide a list of possibile options to show in dropdown.

Usually you do something like:

```
'option' => [
'value' => [
'valueone' => 'one',
'valuetwo' => 'two'
]
]
```

But what if I omit array keys or my keys start with a number?

Here we have a `(int)` casting of the array key to be used as option_id field in db.
https://github.com/magento/magento2/blob/2.1.2/app/code/Magento/Eav/Setup/EavSetup.php#L870

If the (int) casting returns 0 it will fetch the last_insert_id and create a new option, otherwise it will update the existing value.

This means that if I use as key something that can be casted to int it will overwrite the table entry with the same option_id value if it exists.

example

```
'option' => [
'value' => [
'4mm' => '4 mm',
]
]
```

### Preconditions
1.  Magento 2.1.2
2. PHP 7
### Steps to reproduce
1.  Write a setup script thats adds an attribute with options like described in the example above
2. setup:upgrade
3. Look at your eav_entity_attribute_option table
### Expected result
1. A new option is added
### Actual result

1. existing option of another attribute has been overwritten.

**Comment by olysenko** [comment]
Hi, thank you for your request. Magento expects id as key for option array, Please use 
\Magento\Eav\Api\AttributeOptionManagementInterface for attribute options management

**Comment by giacmir** [comment]
@olysenko But if so, why is that method called at the end of `addAttribute` that is meant to add attributes during setup?

```
if (isset($attr['option']) && is_array($attr['option'])) {
            $option = $attr['option'];
            $option['attribute_id'] = $this->getAttributeId($entityTypeId, $code);
            $this->addAttributeOption($option);
        }
```

Should the options be created before the attribute? Should we really use AttributeOptionManagementInterface in setup files? It don't makes sense.

**Comment by olysenko** [comment]
The recommended flow is to use API if it is possible, using API you can create attribute(\Magento\Eav\Api\AttributeRepositoryInterface), manage it options(\Magento\Eav\Api\AttributeOptionManagementInterface) etc

**Comment by giacmir** [comment]
Wait a minute, APIs should be used in setup also? I mean... in InstallData classes too? Why so there still are EavSetup classes?

**Comment by olysenko** [comment]
Usage of API for your extension guarantees compatibility with upcoming versions. Magento code or your extension may rely on private implementation. But with this approach your code may be compatible only with one particular version that selected for development.

**Comment by phoenix128** [comment]
@olysenko , can you please let us understand how you could create an attribute in a **setup** script using API? Are you sure you correctly understand the @giacmir question? I had the same problem and he is talking about **SETUP** classes.

I'm asking you because you do it in a very different way in your original Magento's code.
Take a look in `Magento\Catalog\Setup\InstallData.php::install` (just an example), here you are not using API in the way you say.

Thank you in advantage for your time.

**Comment by olysenko** [comment]
see example

```
class CreateAttributeExample
{

    /**
     * @var \Magento\Eav\Api\AttributeRepositoryInterface
     */
    private $attributeRepository;
    /**
     * @var \Magento\Eav\Api\Data\AttributeInterfaceFactory
     */
    private $attributeFactory;
    /**
     * @var \Magento\Eav\Api\Data\AttributeOptionInterfaceFactory
     */
    private $optionFactory;
    /**
     * @var \Magento\Eav\Api\Data\AttributeOptionLabelInterfaceFactory
     */
    private $labelFactory;
    /**
     * @var \Magento\Eav\Api\AttributeOptionManagementInterface
     */
    private $optionManagement;
    /**
     * @var \Magento\Eav\Model\Config
     */
    private $eavConfig;

    public function __construct(
        \Magento\Eav\Api\AttributeRepositoryInterface $attributeRepository,
        \Magento\Eav\Api\Data\AttributeInterfaceFactory $attributeFactory,
        \Magento\Eav\Api\Data\AttributeOptionInterfaceFactory $optionFactory,
        \Magento\Eav\Api\Data\AttributeOptionLabelInterfaceFactory $labelFactory,
        \Magento\Eav\Api\AttributeOptionManagementInterface $optionManagement,
        \Magento\Eav\Model\Config $eavConfig

    ) {
        $this->attributeRepository = $attributeRepository;
        $this->attributeFactory = $attributeFactory;
        $this->optionFactory = $optionFactory;
        $this->labelFactory = $labelFactory;
        $this->optionManagement = $optionManagement;
        $this->eavConfig = $eavConfig;
    }

    public function createAttribute()
    {
        $entityType = $this->eavConfig->getEntityType(
            \Magento\Catalog\Api\Data\ProductAttributeInterface::ENTITY_TYPE_CODE
        );
        $attribute = $this->attributeFactory->create();
        $attribute->setEntityTypeId($entityType->getEntityTypeId());
        $attribute->setAttributeCode('new-attribute-api');
        $attribute->setBackendType('int');
        $attribute->setFrontendInput('select');
        $attribute->setIsUserDefined(1);
        $attribute->setDefaultFrontendLabel('new attribute api');
        $attribute->setSourceModel(\Magento\Eav\Model\Entity\Attribute\Source\Table::class);
        $this->attributeRepository->save($attribute);

        $option = $this->optionFactory->create();
        /** @var \Magento\Eav\Api\Data\AttributeOptionLabelInterface $label */
        $firstLabel = $this->labelFactory->create();
        $secondLabel = $this->labelFactory->create();


        $firstLabel->setLabel('Test 123');
        $firstLabel->setStoreId(0);
        $secondLabel->setLabel('Test 467');
        $secondLabel->setStoreId(2);


        $option->setLabel('Option Label');
        $labels = [$firstLabel, $secondLabel];
        $option->setStoreLabels($labels);

        $this->optionManagement->add(
            $entityType->getEntityTypeCode(),
            $attribute->getAttributeCode(),
            $option
        );
    }
}
```

**Comment by phoenix128** [comment]
So what you are saying is that Magento's code is wrong in every setup class in its code? Are you sure you correctly understood the question @giacmir asked?

So what **EavSetup** is for? You are using it in every single setup file in original Magento's code.

Thank you.

**Comment by akaplya** [comment]
EavSetup is a private implementation, it can be rewritten or replaced (with moving to declarative schema for example). but API will be supported. Wherever it possible usage of API is preferable;
