### ISSUE TITLE
Adding "out of stock" product confgurations to cart - wrong notification

### ISSUE THREAD

**Issue by jakobfdev** [magento/magento2#7164]
### Preconditions
1. Magento 2.1.2 from composer
2. PHP 5.6, MySQL 5.7
### Steps to reproduce
1. Fresh magento install
2. Create configurable product with a single config attribute and several simple products
3. Set one simple products stock quantity to 0 and to "Out of stock"
4. In the frontend go to the configurable, choose the config value of the "Out of stock" simple product and add it to cart

_Try not to set the first of the configurations out of stock, otherwise you run into_
https://github.com/magento/magento2/issues/6799
### Expected result
1. There should be a message like **"This product is out of stock."**
### Actual result
1. The message says **"You need to choose options for your item."** as no configuration was selected.

**Comment by quienti** [comment]
Duplicate: https://github.com/magento/magento2/issues/7069
