### ISSUE TITLE
Editing checkout agreements throws exception

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7171]
### Preconditions

1. Magento 2.1.2
2. Updated from 2.1 via composer
3. Single Store Mode enabled
### Steps to reproduce

1. Create new checkout agreement.
2. Try to edit
### Expected result

1. Open agreement for edit
### Actual result

1. <pre>Warning: htmlspecialchars() expects parameter 1 to be string, array given in
   /vendor/magento/framework/Data/Form/Element/AbstractElement.php on line 286</pre>

**Comment by palamar** [comment]
Internal ticket MAGETWO-60143 has been created to track this issue.

**Comment by mosesmalone** [comment]
Same problem here on Magento 2.1.2.
Any workaround to delete a term that's been created?
I'd like to remove it, but can't, because editing is not possible :)

**Comment by mosesmalone** [comment]
sorry, found the entry in the database.
Table "checkout_agreement".

**Comment by mosesmalone** [comment]
I was able to fix it by changing **Line 302** in **/vendor/magento/framework/Data/Form/Element/AbstractElement.php** from 
`return $this->_escape($value);`
to
`if(is_string($value)) {
            return $this->_escape($value);
        }`

don't know if this causes any other issues though :)

**Comment by therool** [comment]
I encountered the same issue on magento 2.1.0 and found that the issue lies withing https://github.com/magento/magento2/blob/develop/app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php#L139. Megento expects that the value of hidden field is string but existing aggreement stores property is always array containing all the store ids it it associated with and is overwrites the default store id on https://github.com/magento/magento2/blob/develop/app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php#L186.

The fix is pretty easy - just change the line https://github.com/magento/magento2/blob/develop/app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php#L144 to
`$model->setStores($this->_storeManager->getStore(true)->getId());`

**Comment by KrystynaKabannyk** [comment]
@rbostan, the fix will be provided under MAGETWO-63840 (MAGETWO-60143 is closed as duplicate).

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-63840 to track progress on the issue.

**Comment by ghost** [comment]
I just encountered this on 2.2.1 too. Can someone please give me a diff/patch to fix that? 

edit: switched to another system. so i can not give any more information.

**Comment by ajankuv** [comment]
Do we have a fix yet?

edit: single store is the cause of most of this, i had an issue with a module switching back to multi-store fixed it. My guess is their should be some logic switch from multi to single to fix this for everything. This issue is going to linger until that's fixed.

**Comment by vaso123** [comment]
It still happens in Magento 2.2.4. 

Guys, this ticket opened Oct 25, 2016, so it is 1.5 years old.

**Comment by efimov-ivan** [comment]
Confirm that error still happening in Magento 2.2.4

**Comment by vaso123** [comment]
And still exists in 2.2.5

**Comment by zaibigits099** [comment]
following therool . I added this below this line in function `_prepareForm` of class `vendor/magento/module-checkout-agreements/Block/Adminhtml/Agreement/Edit/Form.php` but i did over-ride to avoid lossing it after upgrade.

`$model->setStores($this->_storeManager->getStore(true)->getId());`

and it worked on Magento 2.2.4 with me.

**Comment by LiamKarlMitchell** [comment]
Can confirm, editing the _escape function work around by pmsteil resolves this.

Not sure if it the call to escape should have multiple argument types in same function?

```
_escape($string : string)
_escape($string : array)
```

Microsoft Office Word text quotes get lost in saving/editing however.
I'm not sure if that is related to this or the way the string is stored/processed.

```“Test”```
Gets returned in this encoding.
```âTestâ```
It does render okay on the front end, but the back end editor does not show correctly.

**Comment by sdzhepa** [comment]
Hello @rbostan 

Thank you for your report.
The issue was fixed and delivered with commits:
- a49f5247902684ed6c19f99285a7015ab4a2507c
- e4353add8d0cbf628a8813bed5377baf700e57b9
