### ISSUE TITLE
proposal: Show missing privileges instead of required

### ISSUE THREAD

**Issue by creative-resort** [magento/magento2#7172]
### Preconditions

using a MySQL DB user with missing privilege e.g. "REFERENCES"
Magento CE 2.1
### Steps to reproduce
1. start the setup process 
2. go to the database check / setup step
### Expected result
1. would like to see which privilege is missing directly, resulting from the array_diff in
   setup/src/Magento/Setup/Validator/DbValidator.php  DbValidator :: checkDatabasePrivileges()
### Actual result
1. the general list of required privileges is shown,
   making it tedious to find out which one is missing.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/proposal-Show-missing-privileges-instead-of-required/idi-p/54639).
