### ISSUE TITLE
Add custom product attribute and assign to particular attribute set

### ISSUE THREAD

**Issue by anilkasar12** [magento/magento2#7177]
Add custom product attribute and assign to particular attribute set
### Preconditions

Magento2.0.2
### Steps to reproduce

Add custom product attribute
### Expected result

Custom attribute should able to assign given attribute set
### Actual result

Custom attribute should assign to all available attribute set.

**Comment by dthampy** [comment]
@anilkasar12 , couple of questions for you.
1.Once you create a product attribute, does that attribute get assigned to all the Attribute Sets  ---> is that the issue? 
2. Also when you create a product that belongs to any Attribute Set, does this attribute show up on the Product edit form?( even though it is not assigned to any specific Attribute set?)
1. Typically, after you create a product attribute , and you go into each one of the Attribute Set you have, you can see that the attribute you just created, is displayed under Unassigned attributes and unless you assign to the attribute Set of your choice, it shouldn’t show up for the product.
   Is that not how it is working for you?

Can you please explain the problem in detail with screenshots?

Thanks.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
