### ISSUE TITLE
Save And Duplicate Product leads to duplicated entity_varchar entries

### ISSUE THREAD

**Issue by schnappenberger** [magento/magento2#7179]
Wen you save and duplicate a product a save on the new product is executed which stores data in entity_varchar. The Duplicate-Method from ResourceModel\Product adds all attribute values from old id. The result are duplicated attributes in entity_varchar
### Preconditions
- Magento 2.1.2
- PHP 7
- Mysql 5
### Steps to reproduce
1. Save and Duplicate a Product
2. Search entity_varchar values in db for duplicated entity
### Expected result
1. There are no duplicated values
### Actual result
1. There are duplicated attribute values

**Comment by olysenko** [comment]
Hi, thank you for your report.  If I understand correctly you mean table "catalog_product_entity_varchar", it doesn't contain duplicated rows. Combination of attribute_id, store_id, entity_id and value differs at least  by entity_id value. Please provide more info to be on the same page.

**Comment by schnappenberger** [comment]
Yes, i mean catalog_product_entity_varchar. By editing products in Backend in a multistore environment we’re getting rows in this table which differ in value_id. But  attribute_id, store_id, entity_id and value are not unique. So we have the same attribute value for a product and a store multiple times.

**Comment by olysenko** [comment]
Hi, sorry but I cannot reproduce issue using your description.
I am always have the unique combination of  attribute_id, store_id, entity_id for each value_id after Save & Duplicate product in admin regardless multistore or not environment. Please provide clear steps how to replicate your issue in format like this
_Steps_
1. Fresh install of Magento 2.1.2 
2. Create Second website in Stores->All Stores menu
3. Create Second store assigned to second website
4, Create Second Store view assigned to second store
5. Open Products->Catalog menu and click Add Product button
6. On New Product page enter Product name,  SKU and Price,  assign product to second website( by selection checkbox near second website in tab Product in Website ) click Save & Duplicate button
7. Enter sql editor and execute query in your db
select _, count(_) as num from catalog_product_entity_varchar group by attribute_id, store_id, entity_id, value having num>1;
_Result_
Empty set. So there are no duplicates

P.S. Table catalog_product_entity_varchar has foreign key CATALOG_PRODUCT_ENTITY_VARCHAR_ENTITY_ID_ATTRIBUTE_ID_STORE_ID so it is impossible to duplicate entry

**Comment by schnappenberger** [comment]
Got it. The table structure doesnt contain the mentioned key CATALOG_PRODUCT_ENTITY_VARCHAR_ENTITY_ID_ATTRIBUTE_ID_STORE_ID. The database was created before the official 2.0 release. Perhaps some version updates havent upgraded the db properly. I will try to fix the table structure.

Sorry for the inconveniences.
