### ISSUE TITLE
[Exception]  Warning: Error while sending QUERY packet.

### ISSUE THREAD

**Issue by HaykDrnoyan** [magento/magento2#7184]
Installing Magento 2.1.2 with Sample data. Downloaded the package from site (no composer install). Both web wizard installation and cli installation hang on Module 'Magento_ConfigurableSampleData': and showing an error: [Exception]  
  Warning: Error while sending QUERY packet. PID=15454 in /home/..../vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228  

### Preconditions

CENTOS 7.2 x86_64 
PHP Version 5.6.25
MariaDB 10.0
max_allowed_packet | 1024000000
connect_timeout=90
wait_timeout=90
interactive_timeout=90
max_execution_time 18000
max_input_time  9000
memory_limit 2G (the same in .htaccess)
### Steps to reproduce

1. Download .tar.zip file with sample data
2. Install via web wizard
3. Install via cli
### Expected result

1. Install
### Actual result

1. Error Warning: Error while sending QUERY packet. PID=15454 in /home/.../vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

**Comment by ghost** [comment]
@HaykDrnoyan CE or EE? I'll assume CE

**Comment by ghost** [comment]
FWIW, could not reproduce with CE 2.1.2 with sample data (`.zip`), CLI install, CentOS 6, MySQL 5.6, PHP 5.6.22

**Comment by ghost** [comment]
Also could not reproduce with same `.zip`, CLI install, CentOS 7, PHP 7.0.6, MySQL 5.7

**Comment by hd1272** [comment]
Thanks for checking, @xcomSteveJohnson Yes, CE, 2.1.2 I installed using CLI and after sampledata:deploy, modeul:enable /_sample data modules_/, on setup:upgrade step I receive this

Module 'Magento_ConfigurableSampleData':

  [Magento\Framework\Exception\SessionException]  
  Area code not set: Area code must be set before starting a session.  

  [Magento\Framework\Exception\LocalizedException]  
  Area code is not set

**Comment by jissereitsma** [comment]
FYI, in my case, increasing the MySQL `max_allowed_packet` solved this issue

**Comment by magento-engcom-team** [comment]
@HaykDrnoyan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
