### ISSUE TITLE
Grouped product - tax class sent multiple times - elasticsearch

### ISSUE THREAD

**Issue by nagrgk** [magento/magento2#7187]
Grouped product  having 3 child products, reindex will send 3 same tax class ids to elastic search and it throws exception.

ps in this set: 6', 8' and 10'. 100% soft and durable cotton. Plastic cinch buckle is easy to use. Choice of three natural colors made from phthalate and heavy metal free dyes.","gender":"89 90 93","image":"\/l\/u\/luma-yoga-strap-set.jpg","is_returnable":"2","material":"41 53","name":"Set of Sprite Yoga Straps","options_container":"container2","options_container_value":"Block after Info Column","quantity_and_stock_status_value":"In Stock","size":"100","size_value":"55 cm","sku":"24-WG085_Group","small_image":"\/l\/u\/luma-yoga-strap-set.jpg","status":"1","status_value":"Enabled",**"tax_class_id":"2 2 2**","thumbnail":"\/l\/u\/luma-yoga-strap-set.jpg","updated_at":"2016-09-29T02:38:07+00:00","url_key":"set-of-sprite-yoga-straps","visibility":"4","visibility_value":"Catalog, Search","image_file_0":"\/l\/u\/luma-yoga-strap-set.jpg","image_position_0":"1","image_disabled_0":"0","image_label_0":"Image","image_title_0":"Image","image_base_image_0":"1","image_small_image_0":"0","image_thumbnail_0":"0","image_swatch_image_0":"0","is_in_stock":1,"qty":"1","price_0_1":"14.000000","price_1_1":"14.000000","price_2_1":"14.000000","price_3_1":"14.000000","category_ids":"2 3 5","position_category_2":"1","name_category_2":"Default Category","position_category_3":"1","name_category_3":"Gear","position_category_5":"1","name_category_5":"Fitness Equipment"}]}

Magento2 has to fix this bug not sending 3 times same class id. This is bug and reindex will fail for grouped products.

**Comment by veloraven** [comment]
@nagrgk thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by nagrgk** [comment]
I have given you all the information. Please take this and resolve issue immediatly.

thanks

**Comment by veloraven** [comment]
@nagrgk 
Please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result.
As formatted description allows to understand what the problem is and how to reproduce it more easier. Also it allows to find the issue when searching for duplicates.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
