### ISSUE TITLE
How To uninstall extension   in Magento ver. 2.1.1

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7190]
How To uninstall extension   in Magento ver. 2.1.1   ????  
Any Step ??

**Comment by southerncomputer** [comment]
in theory: 
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html

in reality (With composer):
php bin/magento module:disable Module_Name
composer remove Composer_Module_Name

In reality: Good luck with either of those actually working, you'll need to clean out app/code and undo all the database install/changes, after you php bin/magento module:disable , plus clean out app/design and pray everything works afterwards!

Disabling a module does not stop Dependency Injection in magento!

**Comment by veloraven** [comment]
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
