### ISSUE TITLE
New Integration Form Not Open 

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7191]
### Steps to reproduce

1. System => Extensions => Integrations 
2. Click On Add New Integration Form Not  Open
### Expected result

1.  Form Open  Proper 
### Actual result

![capture1](https://cloud.githubusercontent.com/assets/16436069/19714183/bdd00c8c-9b69-11e6-9060-ebb3fec39442.PNG)

**Comment by veloraven** [comment]
@mitulispace thank you for your feedback.
Please identify which version of Magento you are running.

**Comment by mitulispace** [comment]
@veloraven  magento ver 2.1.1

**Comment by sevos1984** [comment]
Have you tried clearing browser cache? Do you have any errors is browser's console?

**Comment by mitulispace** [comment]
yes i tried @sevos1984

**Comment by sevos1984** [comment]
So are there any errors in browser console? Could you check magento logs for errors as well?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
