### ISSUE TITLE
Product Edit Page : Category Picker Component too slow if many categories.

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#7193]
### Preconditions

1. Magento 2.1.1
2. 
### Steps to reproduce

1. Build a catalog with many categories (I have 6000 categories, from levels 1 to 8).
2. Access the Product Edit page in back-office.
### Expected result

1. Page is displayed after a reasonable time (3-4 seconds) and the form is accessible for editing. The category picker also works fast.
### Actual result

1. The page is properly displayed quite fast.
2. The spinner remains "loading" while Magento builds up the edit form.
3. This take around 45 secs.
4. The spinner is remove and the form is properly displayed.
5. The component for category assignment is dramatically slow and nearly unusable.

If I shutdown the module-catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php (by returning an empty array or capping it to 10 categories on `getCategoriesTree` function), the problem is gone and the page renders quite fast.

So imho this is a bug related to the Javascript component which is responsible for rendering the category dropdown.

Let me know

**Comment by philipvandebriel** [comment]
Hi,
We have exact the same problem with 4500 categories, this problem start from Magento 2.1.X

**Comment by sevos1984** [comment]
This is already fixed in develop https://github.com/magento/magento2/commit/bebb2ceb000b9296f9b04ecd5424ef66cd723fbf. Soon will be delivered to 2.1.
