### ISSUE TITLE
Registering on checkout success page always generates user with two addresses, even when asked not to

### ISSUE THREAD

**Issue by pronto2000** [magento/magento2#7194]
When a guest registers on checkout success page, the account created has always two addresses assigned to it, even after user explicitly asks to use shipping address for billing. 
### Preconditions

1. Issue manifest on all Magento 2 versions released so far (tested on CE 2.1.2 and EE 2.1.2)
### Steps to reproduce

1. As a guest put something to the shopping cart and complete 1. step of checkout.
2. Use shipping address for billing address
3. Finish checkout, create new account when prompted on success page. 
### Expected result

1. A new user with one address that is assigned to both shipping and billing.
### Actual result

1. A new user with TWO identical addresses, one assigned as default billing address and another as default shipping one.

**Comment by olysenko** [comment]
Hi. thank you for request. Internal ticket  MAGETWO-60255 was created

**Comment by magento-engcom-team** [comment]
@pronto2000, thank you for your report.
We've created internal ticket(s) MAGETWO-60255 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@pronto2000, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
