### ISSUE TITLE
Negative product qty with "-" is not valid in admin panel product page

### ISSUE THREAD

**Issue by HellgaM** [magento/magento2#7197]
Negative product qty with "-" is not valid even if "backorder" is enabled
https://drive.google.com/a/interiorwebdesign.com/file/d/0ByJDgAmB3zgAYk0tQmRhVnZWNms/view?usp=drivesdk
### Preconditions

Magento version is 2.1.0
PHP 7
MySql 5.6
### Steps to reproduce
1. Open product in admin panel
2. Set inventory "-8" 
3. try to save product
### Expected result
1.  Value with "-" should be valid
### Actual result
1. Can't save the product because of not valid qty

**Comment by Sanfam** [comment]
Additional note: While Magento appears to be able to track negative inventory counts and can even export this data as part of a comprehensive Product Data Export, but will error out when attempting to import these negative `qty` values (regardless of whether or not inventory tracking or backorder are enabled)

**Comment by odubovyk** [comment]
@HellgaM, thank you for the report. Internal ticket MAGETWO-60216.

**Comment by joshdavenport** [comment]
Have recently experienced this issue with a client and it sure is a pain. Even setting backorder settings "Allow qty to below 0" which based purely on the language would lead you to believe a negative qty would be valid. Worth noting: setting allow qty decimals allows you to save with a negative qty but that feels hacky.

**Comment by Tristan-N** [comment]
@odubovyk Do you have any updates for us? Or any kind of temporary workaround? Thanks

**Comment by rganin** [comment]
Issue is fixed in scope of MAGETWO-53107.

**Comment by rganin** [comment]
Issue is fixed in MAGETWO-57052 for 2.1.

**Comment by DigiWorksNL** [comment]
Problem still exists in 2.1.6.

**Comment by DigiWorksNL** [comment]
@rganin Please reopen this issue. 	MAGETWO-57052 was related to ' Cannot import negative quantity' this issue hasn't todo anything with the import

**Comment by calvintwr** [comment]
problem still exists with 2.1.7

**Comment by DigiWorksNL** [comment]
@calvintwr look at this issue: https://github.com/magento/magento2/issues/9139
May be you can apply the commits by your self?

**Comment by sippsolutions** [comment]
@rganin Please re-open.

**Comment by jmonschke** [comment]
I have found that this works as expected in 2.1.8.
