### ISSUE TITLE
Reorder functionality is adding disabled products to cart

### ISSUE THREAD

**Issue by gorillagroup** [magento/magento2#7201]
Magento adds products that have been disabled to the cart.
### Preconditions
1. Magento 2.1.2 EE
2. Customer account created
### Steps to reproduce
1. Place Order in Magento for a product
2. Disable the product in the admin panel
3. Log into the My Account section, open the order details for the previously placed order and click "reorder"
4. Disabled item gets added to the cart
### Expected result
1. Error message should appear and item should not be added to the cart
### Actual result
1. Item is added to the cart

Thanks,
Christian

**Comment by veloraven** [comment]
@gorillagroup thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by veloraven** [comment]
I'm closing this issue.
