### ISSUE TITLE
Can't reorder product tabs using any standard way: before, after <move />

### ISSUE THREAD

**Issue by itaymesh** [magento/magento2#7202]
Product tab reordering is not working using any standard way: before, after <move />

For example, if you'd like to move the "Description" tab after any other tab it WILL NOT WORK.
`<move element="product.attributes" destination="product.info.details" after="-" />`

Even if you try to use a before attribute in the original layout XML catalog_product_view.xml
`<block class="Magento\Catalog\Block\Product\View\Description" name="product.info.description" template="product/view/attribute.phtml" group="detailed_info" after="-">`

The reason for that is that the function reordering function **reorderToSibling** in Magento\Framework\Data\Structure is being called before the function that adds the block to the group collection, **addToParentGroup**

Hope it can be solved soon.

Thanks

**Comment by veloraven** [comment]
@itaymesh thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
