### ISSUE TITLE
2.1.2 CE WEBAPI: SOAP empty special price will result in a price 0.0000 bug

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#7205]
Magento 2.1.2
[special_price_product_save.zip](https://github.com/magento/magento2/files/555203/special_price_product_save.zip)

STEPS to reproduce: create an XML request as in the zip
ACTUAL result: special price is set for product to 0
EXPECTED: don't touch special price for an item when no value is sent

If we are sending an empty special price in the productSave method, the price is saved as 0.0000. This is not correct and a bug, an empty value should not result in a zero price.

Check the attached XML request and response.

**Comment by veloraven** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by ericahoekerd** [comment]
all info is in the zip and in the topic

**Comment by veloraven** [comment]
@tinxit 
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
As formatted description allows to understand what the problem is and how to reproduce it more easier. Also it allows to find the issue when searching for duplicates.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ericahoekerd** [comment]
same as this issue:

https://github.com/magento/magento2/issues/8274
