### ISSUE TITLE
"Used in Product Listing" - not implemented?

### ISSUE THREAD

**Issue by OZZlE** [magento/magento2#7208]
### Preconditions
1. Magento CE 2.1.1
2. PHP 7.0.8
3. MySql  Ver 14.14 Distrib 5.6.32-78.0, for debian-linux-gnu (x86_64) using  6.3
### Steps to reproduce
1. Choose an existing product attribute such as Country of manufacturer 
2. Choose: Used in Product Listing: Yes
### Expected result
1. You can see the attribute on frontend in the product listing (category page) beneath each product info when the product has this attribute specified.
### Actual result
1. Nothing changed on frontend.

It seems like this hasn't been implemented at all other than the option in Admin and that it's added to the product collection. You have to implement the listing of the attributes manually? Why.

**Comment by veloraven** [comment]
@OZZlE thank you for your feedback.
Have you update template of your category page in order it shows additional attribute?
The mentioned setting specifies if attribute _can_ be shown on the category page if the category page template supports it.

**Comment by OZZlE** [comment]
I understand but for me it doesn't make sense to have a feature in Admin which you expect to affect the frontend and then it doesn't do anything without development.

**Comment by veloraven** [comment]
@OZZlE you can create an improvement using [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
I'm closing this issue as it is not a technical issue and  GitHub issue tracker is intended for technical issues only.
