### ISSUE TITLE
Gift wrap option for individual items not displayed for grouped items

### ISSUE THREAD

**Issue by deepthit57** [magento/magento2#7209]
Magneto Enterprise Edition
Version: 2.1.2
![gfit_wrap_option_not_displayed_for_item_level](https://cloud.githubusercontent.com/assets/20681023/19763401/76af0ac2-9c5b-11e6-9d48-92a4a496e010.png)

Steps:
1. Go to Magento admin
2. Go to Stores-.Configuration->Sales->Sales
3. Set "yes" for all the options under Gift Options Section
4. Save the config
5. Go to stores->Other Settings->Gift Wraping
6. Add Gift Wrapping
7.Add a grouped product to cart
8.Add a simple and configurable product to cart

Expected result
Gift wrap option for individual item must be displayed below each item with gift wrap options

Actual result
Gift wrap option for individual item is displayed for configurable and simple product but not for grouped item. Gift wrap option is displayed but no options to choose under it

**Comment by veloraven** [comment]
@deepthit57 please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
