### ISSUE TITLE
Should VCL file unset cookies on 404's?

### ISSUE THREAD

**Issue by alankent** [magento/magento2#721]
Ben Lessani (twitter @sonassi) reported: "The default VCL in M2 is alarming. Why is there a cookie unset in vcl_recv - this will cause session/cookie loss on 404's " https://twitter.com/sonassi/status/528250395991490562

Alan: I am not sure why losing a session cookie on a 404 is a major issue - should not be getting 404's in the first place. But recording to make sure it gets looked into.

**Comment by kokoc** [comment]
Addressed in 4393143e925cb855e8a427101b6c957f4f78885b and going to be improved in #988.
