### ISSUE TITLE
Grunt:exec error on Magento 2.1.2 using custom theme

### ISSUE THREAD

**Issue by sam-g-roberts** [magento/magento2#7214]
When running Grunt exec i've just started getting the below error. I've tried clearing out the var and the pub/static folders as well as running grunt:clean before exec. Any help would be much appreciated.

`Processed Area: frontend, Locale: en_US, Theme: vendor/theme, File type: less.

> > [InvalidArgumentException]  
> >   Verify entered values of the argument and options. Unable to resolve the source file for 'frontend/vendor/theme/en_US/css/styles-m.less'  
> > 
> > dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
> > Exited with code: 1.
> > Warning: Task "exec:custom_theme" failed. Use --force to continue.
> > `

**Comment by JoshuaSoileau** [comment]
hey @sam-g-roberts I am getting this same thing, how did you resolve it?

**Comment by kn-wield** [comment]
@sam-g-roberts I'm also having this same issue—how did you resolve, please?

**Comment by gilles6** [comment]
Same problem here.

**Comment by mohammedsalem** [comment]
any update here?!

**Comment by Mustikkamunkki** [comment]
Yes please, could someone comment? I'm getting this and I have no idea where to start digging for the cause.

**Comment by sam-g-roberts** [comment]
Pretty sure this was my own user error and there was no bug. 

If you believe you are experiencing a similar issue please create a separate bug report and follow the correct bug report schema.

**Comment by Mustikkamunkki** [comment]
Well could you kindly outline the error that you had made, I am sure it is something similar for the rest of us, and we would appreciate a pointer in the right direction.

**Comment by pluckrose** [comment]
+1 also having issue and have no idea what's different between an install that is working fine.

**Comment by riconeitzel** [comment]
for possible solutions see #12271
