### ISSUE TITLE
Add to cart error

### ISSUE THREAD

**Issue by umang-ranium** [magento/magento2#7216]
### Preconditions

1. Developer mode , ubuntu, php 7
2. Magento 2.1
### Steps to reproduce

1. Go to product page,
2. Click Add to cart
3. error unable to save quote
### Expected result

1. Should add product to cart
### Actual result

1. [Screenshot, logs]
   Warning: Invalid argument supplied for foreach() in /var/www/vhosts/shop/vendor/magento/module-media-storage/Model/File/Validator/NotProtectedExtension.php on line 86

**Comment by lhsatch** [comment]
Have you installed any other modules?

**Comment by SerhiyShkolyarenko** [comment]
@umang-ranium i used the same environment, but my adding to cart was successful.
Which changes to config have you done after the installation? Do you use the standard theme?
Is the issue reproducible after reinstalling to clean DB?

![added_to_cart](https://cloud.githubusercontent.com/assets/15108140/19809195/e427fdd6-9d30-11e6-9bba-3bf113223cc6.png)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
