### ISSUE TITLE
REST API PUT for Category isn't working

### ISSUE THREAD

**Issue by TenzinNKhando** [magento/magento2#7222]
### Preconditions

1.  Magento 2.0.7
### Steps to reproduce

1. Using Chrome extension ARC 
2. Using endpoint /V1/categories/{id}
3. Set method to PUT
4. Used: 'Content-Type: application/json'
5. Trying to change description to a category that already exist with Raw Payload as:
   {
   "category": {
     "name": "Tenzin",
     "customAttributes": [{
     "attributeCode":"description",
     "value":"<p>This is a test description<\/p>"
   }]
   }
   }
### Expected result

1. The description will update/change to the value I set in the Raw Payload
### Actual result

1. Recieved a "501: Not Implemented"
   ![image](https://cloud.githubusercontent.com/assets/13293090/19784883/3f82e866-9c4c-11e6-8c96-5a6b4421abca.png)

**Comment by olysenko** [comment]
Hi, thank you for your report. I cannot reproduce this issue on the latest 2.0 version. Please upgrade and try again

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
