### ISSUE TITLE
Magento 2.0.7 and 2.1.1 - "Could not save credit memo" 

### ISSUE THREAD

**Issue by btjackson11** [magento/magento2#7223]
I have three sites (two on Magento 2.0.7 and one on Magento 2.1.1), all three cannot process a credit memo refund with orders using Authorize.Net (but can with Paypal orders). When I hit "Refund" on the credit memo page of an order invoice I get an error that says "Could not save credit memo" (see attached image). All three sites have varying extensions and settings with the only major similarity being that they are all on Magento and process orders with Paypal and Authorize.Net.
### Preconditions
1. Magento 2.0.7 and Magento 2.1.1
2. PHP 5.6.1
### Steps to reproduce
1. Place order on site (with Authorize.Net)
2. Go to Magento Admin
3. Sales < Orders < Select Order < Invoices < View Invoice < Credit Memo < Refund
### Expected result
1. Success message with a refund being posted to a customer's account
### Actual result
1. "Could not save credit memo" message (see attached image)

![screen shot 2016-10-27 at 4 57 57 pm](https://cloud.githubusercontent.com/assets/11138810/19789816/a7501cfa-9c67-11e6-80e5-26928e337b29.png)

**Comment by btjackson11** [comment]
@veloraven @alena-marchenko any ideas on a potential fix for this issue?

**Comment by alena-marchenko** [comment]
Hi @btjackson11 

Please ensure that transaction is already settled on Authorize.net side when you are trying to create online credit memo for it, it can take next to 24 hours. If it is not settled, you will not be able to create online credit memo. Please inform us if it was the cause of the issue.

**Comment by btjackson11** [comment]
@alena-marchenko 

Some of the transactions we have been trying to create online credit memo's for are almost 2-3 weeks old. I looked in Authorize.net and they have already settled. Although I see the 24 hour difference between when the order was placed to when it settled. This doesn't seem to be the problem in this case though, any other ideas?

**Comment by btjackson11** [comment]
@alena-marchenko an update: we have disabled all our extensions minus the Authorize.net extension and reverted the theme back to Lora (effectively starting with a fresh install of Magento) and still had this problem persist.

**Comment by btjackson11** [comment]
This looks like a bug with the Authorize.net CIM extension incorrectly passing the transaction id.

**Comment by MonsterEdward** [comment]
How did U solve this problem finally?I have the same problem,and payment method is 
![2yqd9 j1kodpeyh tnu1 0o](https://cloud.githubusercontent.com/assets/22072869/26816012/1cf8d6e6-4ac2-11e7-954b-a091b9c4077e.png)
Authorize.net Direct Post.

**Comment by btjackson11** [comment]
@MonsterEdward I fixed this a long while ago but it required some modification to the Authorize.net extension. The extension was incorrectly passing the transaction ID through one of the methods. Maybe check if the extension has an update or in their forums.
