### ISSUE TITLE
[BUG] [Magento 2.1.2] Programmatically creating an empty dropdown attribute, "apply_to" is set to NULL (from "simple") after adding options through store admin

### ISSUE THREAD

**Issue by rendyep** [magento/magento2#7225]
### Preconditions
1. Magento 2.1.2
2. Windows 10
3. PHP 7.0.12
4. MySQL 5.6.30

### Steps to reproduce
1. Create an empty dropdown product attribute named "price_unit" programmatically through InstallData.php, set "apply_to" to "simple".
2. After setup:upgrade, things are going fine. In store admin, the "price_unit" attribute is shown on simple product create or edit page (an empty dropdown), and is hidden on other products create or edit page. The content of "apply_to" field of the current attribute in database table of "catalog_eav_attribute" is also "simple".
3. After adding attribute options through store admin, the "price_unit" attribute is shown on all products create or edit page (dropdown with added options). The content of "apply_to" field of the current attribute in database table of "catalog_eav_attribute" become "null".

### Expected result
1. The "price_unit" attribute is shown on simple product create or edit page (an empty dropdown), and is hidden on other products create or edit page.
2. The content of "apply_to" field of the current attribute in database table of "catalog_eav_attribute" is also "simple".

### Actual result
1. The "price_unit" attribute is shown on all products create or edit page.
2. The content of "apply_to" field of the current attribute in database table of "catalog_eav_attribute" is "null".

### Possibly related issue(s)
1. #6469 Magento 2.0.2 (different behaviour with same result)

**Comment by magento-engcom-team** [comment]
@rendyep, thank you for your report.
We've created internal ticket(s) MAGETWO-77937 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release
