### ISSUE TITLE
[BUG][Magento 2.1.2] Unable to delete product on store admin

### ISSUE THREAD

**Issue by rendyep** [magento/magento2#7228]
### Preconditions
1. Magento 2.1.2
2. Windows 10
3. PHP 7.0.12
4. MySQL 5.6.30

### Steps to reproduce
1. Go to admin - Products - Catalog
2. Check one or more products on the list
3. Select "Delete" on the action list
4. Confirm delete selected items

### Expected result
1. Response with message "A total of [number of deleted items] record(s) have been deleted."
2. The products which are requested are deleted completely from catalog

### Actual result
1. Response with message "A total of 0 record(s) have been deleted."
2. The products which are requested to delete still exist on catalog

### Additional information
- Do point 1 and 2 on **steps to reproduce**
- Edit file "vendor/magento/module-ui/Component/MassAction/Filter.php", insert dump code after line 153

**code**

``` PHP
    echo '<pre>';
    var_dump($collection->getSelect()->assemble());
    exit;
```

**original**

``` PHP
    protected function applySelection(AbstractDb $collection)
    {
        $selected = $this->request->getParam(static::SELECTED_PARAM);
        $excluded = $this->request->getParam(static::EXCLUDED_PARAM);

        if ('false' === $excluded) {
            return $collection;
        }

        try {
            if (is_array($excluded) && !empty($excluded)) {
                $collection->addFieldToFilter($collection->getIdFieldName(), ['nin' => $excluded]);
            } elseif (is_array($selected) && !empty($selected)) {
                $collection->addFieldToFilter($collection->getIdFieldName(), ['in' => $selected]);
            } else {
                throw new LocalizedException(__('Please select item(s).'));
            }
        } catch (\Exception $e) {
            throw new LocalizedException(__($e->getMessage()));
        }
        return $collection;
    }
```

**modified**

``` PHP
    protected function applySelection(AbstractDb $collection)
    {
        $selected = $this->request->getParam(static::SELECTED_PARAM);
        $excluded = $this->request->getParam(static::EXCLUDED_PARAM);

        if ('false' === $excluded) {
            return $collection;
        }

        try {
            if (is_array($excluded) && !empty($excluded)) {
                $collection->addFieldToFilter($collection->getIdFieldName(), ['nin' => $excluded]);
            } elseif (is_array($selected) && !empty($selected)) {
                $collection->addFieldToFilter($collection->getIdFieldName(), ['in' => $selected]);
            } else {
                throw new LocalizedException(__('Please select item(s).'));
            }
        } catch (\Exception $e) {
            throw new LocalizedException(__($e->getMessage()));
        }

        echo '<pre>';
        var_dump($collection->getSelect()->assemble());
        exit;

        return $collection;
    }
```
- Continue to point 3 and 4 on **steps to reproduce**

**response**

``` SQL
    SELECT `e`.* FROM `catalog_product_entity` AS `e` WHERE (`e`.`entity_id` IN('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')) AND (`e`.`entity_id` IN('2051', '2050', '2049', '2048', '2047'))
```

In my case, the entity_id that I request to delete are 2051, 2050, 2049, 2048, and 2047.

The system is also select entity_id 1 to 20 with **AND** operator. I don't know which code add them to the filter and what is the purpose. That code cause the pre-deleted products collection has no item.

**Comment by olysenko** [comment]
https://github.com/magento/magento2/issues/7228

**Comment by olysenko** [comment]
Hi, thank you for your report. I cannot reproduce the issue by original steps. Please provide more details about extension installed or  non-default configuration  settings

**Comment by rendyep** [comment]
**Magento Modules**
Magento_AdminNotification
Magento_AdvancedPricingImportExport
Magento_Authorization
Magento_Authorizenet
Magento_Backend
Magento_Backup
Magento_Braintree
Magento_Bundle
Magento_BundleImportExport
Magento_BundleSampleData
Magento_CacheInvalidate
Magento_Captcha
Magento_Catalog
Magento_CatalogImportExport
Magento_CatalogInventory
Magento_CatalogRule
Magento_CatalogRuleConfigurable
Magento_CatalogRuleSampleData
Magento_CatalogSampleData
Magento_CatalogSearch
Magento_CatalogUrlRewrite
Magento_CatalogWidget
Magento_Checkout
Magento_CheckoutAgreements
Magento_Cms
Magento_CmsSampleData
Magento_CmsUrlRewrite
Magento_Config
Magento_ConfigurableImportExport
Magento_ConfigurableProduct
Magento_ConfigurableSampleData
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_Customer
Magento_CustomerImportExport
Magento_CustomerSampleData
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_Directory
Magento_Downloadable
Magento_DownloadableImportExport
Magento_DownloadableSampleData
Magento_Eav
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_GoogleOptimizer
Magento_GroupedImportExport
Magento_GroupedProduct
Magento_GroupedProductSampleData
Magento_ImportExport
Magento_Indexer
Magento_Integration
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_Msrp
Magento_MsrpSampleData
Magento_Multishipping
Magento_NewRelicReporting
Magento_Newsletter
Magento_OfflinePayments
Magento_OfflineShipping
Magento_OfflineShippingSampleData
Magento_PageCache
Magento_Payment
Magento_Paypal
Magento_Persistent
Magento_ProductAlert
Magento_ProductLinksSampleData
Magento_ProductVideo
Magento_Quote
Magento_Reports
Magento_RequireJs
Magento_Review
Magento_ReviewSampleData
Magento_Rss
Magento_Rule
Magento_Sales
Magento_SalesRule
Magento_SalesRuleSampleData
Magento_SalesSampleData
Magento_SalesSequence
Magento_SampleData
Magento_Search
Magento_Security
Magento_SendFriend
Magento_Shipping
Magento_Sitemap
Magento_Store
Magento_Swagger
Magento_Swatches
Magento_SwatchesLayeredNavigation
Magento_SwatchesSampleData
Magento_Tax
Magento_TaxImportExport
Magento_TaxSampleData
Magento_Theme
Magento_ThemeSampleData
Magento_Translation
Magento_Ui
Magento_Ups
Magento_UrlRewrite
Magento_User
Magento_Usps
Magento_Variable
Magento_Version
Magento_Vault
Magento_Webapi
Magento_WebapiSecurity
Magento_Weee
Magento_Widget
Magento_WidgetSampleData
Magento_Wishlist
Magento_WishlistSampleData

**3rd Party Modules**
Aheadworks_Rbslider
Amasty_Base
Amasty_Shopby
Amasty_ShopbyBrand
Amasty_ShopbyPage
Amasty_ShopbyRoot
Amasty_ShopbySeo
Ebizmarts_MageMonkey
HelloBrave_CookieCompliance
HelloBrave_Core
Mirasvit_Blog
Mirasvit_Core
Mirasvit_Credit
Mirasvit_Helpdesk
Mirasvit_Profiler
Mirasvit_Rewards
Mirasvit_Rma
Umc_Base

**Comment by olysenko** [comment]
Hi, since it is impossible to reproduce this issue on fresh Magento 2.1.2 installation, please disable all your 3-rd party extensions and try to reproduce the issue. If it wouldn't reproduce the case is in some 3-rd party extension.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
