### ISSUE TITLE
Magento JMeter Performance Testing best practices

### ISSUE THREAD

**Issue by pmouawad** [magento/magento2#723]
Hello,
I reviewed the JMeter samples that you provide at:
https://github.com/magento/magento-performance-toolkit/tree/master/

First, let me say I find it great that you provide such tests which will improve Magento performances and introduce Performance Testing as a best practices.
Second I wanted to provide some feedback that I hope will be useful:
1/ Maintainability : You should not set Implementation on Http Request, leave it blank and set it in HTTP Request Defaults.
2/ Performance/Realistic Tests : Better use HttpClient4 than Java
3/ Performance : Replace Beanshell by JSR223 + Groovy + Use cache key, it performs 10 times better in terms of CPU
4/ Performance : In Assertions, instead of Contains, use Substring as you usually don't need regexp, it will perform way better in terms of CPU
5/ Performance/Maintainability : In "Simple Product 1 View(BrowsAddToCart)", use CSS/JQuery Extractor instead of XPath, it is more suitable for HTML and performs way better than XPath. Apply this everywhere you use XPath for HTML
6/ Performance/Maintainability : In "Checkout start(CustomerChkt)" use CSS/JQuery Extractor instead of Regexp Extractor, it is more maintainable for HTML and performs better
7/ Performance/Maintainability : Avoid XPath assertion like in Login(CustomerChkt), combine CSS/JQuery Extractor  + Response Assertion using Variable
8/ Performance/Maintainability : Disable all Listeners, keep only Simple Data Writer that writes on error and use NON GUI Mode + CSV output
9/ In Test Plan you should check "Run tearDown thread Groups after shutdown of main threads" 
10/ How come there is no "Think time", I think a realistic "Gaussian Timer" should be inserted as a child of Test Action with 0 Sleep . Doing so you can control precisely every pause your put.

More details can be found here:
http://www.ubik-ingenierie.com/blog/magento-performance-toolkit-and-jmeter-best-practices/
Regards
Philippe M. 
@philmdot

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31542

**Comment by VladimirZaets** [comment]
Hi @pmouawad. Thank you for your report. 
The issue has been fixed in magento/magento2#25719 by @serhiyzhovnir in 2.3-develop branch
Related commit(s):
 - [f307e2edce1d04e6e4cff145505d64dcc98047be](https://github.com/magento/magento2/commit/f307e2edce1d04e6e4cff145505d64dcc98047be)

The fix will be available with the upcoming 2.3.5 release.
