### ISSUE TITLE
Shipping cost calulator in cart keeps spinning in every version of IE (9 - 10 - 11) except Edge

### ISSUE THREAD

**Issue by debuysserk** [magento/magento2#7233]
In the cart, there's a shipping cost calculator. By default it's closed. When you open it in Internet Explorer, the box opens but the loader keeps spinning without ever going away. 

The postcode validator works but when entering a valid postcode, nothing happens.
This occurs in Magento 2 versions up until 2.1.2 on Luma theme.
No JS errors visible.
This happens in IE 9, 10, 11 but NOT in Edge. It works fine there.

Only option is to disable it in the cart for IE users through CSS but hardly a preferred solution..
The shipping cost calculator in the checkout steps works just fine.

Thanks.

**Comment by olysenko** [comment]
Hi, thank you for you report. This issue duplicates [7051](https://github.com/magento/magento2/issues/7051) . Please trace this issue in 7051
Closed as an duplicate
