### ISSUE TITLE
Warning: Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by saderra** [magento/magento2#7236]
### Preconditions

1. 2.1.2
2. 
### Steps to reproduce

1.  Upgraded to 2.1.2
2. 
3. 
### Expected result

1. Should load the dashboard
### Actual result

1. getting stuck on error.

**Comment by veloraven** [comment]
@saderra thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
