### ISSUE TITLE
Multistores Dropdown disappear

### ISSUE THREAD

**Issue by brekz** [magento/magento2#7239]
We have 9 multistores ( https://www.dropbox.com/s/40txyw4tcusedzq/Screenshot%202016-10-29%2010.33.33.png?dl=0 ) 

& if I want to select farthest store - I can't, dropdown disappear, because this line is killing http://awesomescreenshot.com/0ed6651r0c

**Comment by veloraven** [comment]
@brekz  thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
