### ISSUE TITLE
Product Price / Name disappear after trying to delete/change photo roles in Multistore

### ISSUE THREAD

**Issue by brekz** [magento/magento2#7240]
Version 2.1.2

Product Price & Name disappear after changing/trying to delete photo in one of the multi stores.
http://awesomescreenshot.com/0086654lea

I found this bug after I tried to delete main photo (just first photo which uploaded), then I got notification - that system can't delete photo, because "The image cannot be removed as it has been assigned to the other image role". In "Store View: All Stores View" that image was unsigned from main image roles - problem is that the same image using only one store role of that image.

To be clear, want to delete photo from All Stores view, but it has different settings for each multistore (I need go through all multistores to unassigned that image roles - to DELETE IT).

But after I unassigned image role from one of multistores - I'm getting another errors: http://awesomescreenshot.com/0086654lea dissapear product name / price.

Guys, did you debugged M2 with multistores?

Sorry for my broken English language, hopes you understood my issue.

**Comment by veloraven** [comment]
@brekz thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
