### ISSUE TITLE
Admin : Sales Order Reports don't work for locales different than en_US

### ISSUE THREAD

**Issue by dcabrejas** [magento/magento2#7244]
**Environment**
I use Magento version 2.1.1
Linux Server
PHP 7 

**Steps to reproduce**
1. Create an admin user and assign him the en_GB locale (or any other locale except en_US)
2. Log in with that user
3. Navigate to Reports/Sales/Orders
4. Fill in all the fields and click Show Report.

**Expected result**
The Report generated and shown.

**Actual result**
The following error is shown
![m2exception](https://cloud.githubusercontent.com/assets/8201815/19851577/94136bb4-9f56-11e6-8887-14f96ed9e047.png)

**Comment by veloraven** [comment]
@dcabrejasazagra thank you for your report, but I'm closing it as it is a duplicate for #7037

**Comment by rahuldhameliya** [comment]
is that resolved? because i am also getting this issue in 2.1.5.

**Comment by vishalnyati** [comment]
I am also having same issue in 2.1.5.
