### ISSUE TITLE
Configuration group is not visible if it does not have fields in default view.

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#7245]
I'm creating a custom module for price import from sftp server. It is multi-store Magento shop, prices for each store are recognised by a unique identifier. I want to assign this identifier to store_id in in Magento configuration. I added new tab and section. I want to show section in all modes- default, website and store because it contains a comment with instructions, how to set up everything properly. This section has 1 field which is visible only in store view and that makes the whole section hidden in default and website view.

### Preconditions
1.  Magento 2.1.2

### Steps to reproduce
1. Create a new module with a system.xml file
2. Add new tab, section, group visible in default, website and store
3. Add 1 field to section that is visible only in store
4. Add comment to section

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Config:etc/system_file.xsd">
    <system>
        <tab id="test" translate="label" sortOrder="200">
            <label>test</label>
        </tab>

        <section id="test_section" translate="label" type="text" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1">
            <label>Integration</label>
            <tab>test</tab>
            <resource>test_test::config</resource>

            <group id="prices" translate="label" type="text" sortOrder="5" showInDefault="1" showInWebsite="1" showInStore="1">
                <label>Price Import Configuration</label>
                <comment>Switch to store view to configure sales organization.</comment>

                <field id="sales_organization" translate="label" type="text" sortOrder="10" showInStore="1" showInWebsite="0" showInDefault="0">
                    <label>Sales Organisation</label>
                </field>
            </group>
        </section>
    </system>
</config>
```

### Expected result
1. section and comment should be visible in all views, but field only in store view

### Actual result
1. The whole section is hidden and displayed only in store view- the user has no clue that this field exists unless he changes to store view.

**Comment by magento-engcom-team** [comment]
@kandrejevs, thank you for your report.
We've created internal ticket(s) MAGETWO-81385 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@kandrejevs, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
