### ISSUE TITLE
Can't apply different templates to input containers on M2 Checkout

### ISSUE THREAD

**Issue by mr-ford** [magento/magento2#7254]
I've been struggling with this for a few days and hope someone can help.

I'm trying to change the wrapper that surrounds each of the form inputs on the Magento 2.1.1 shipping address fields.  The original template is:

 /module-ui/view/frontend/web/templates/form/field.html

I'm trying to add additional templates (e.g. field2.html, field3.html), which I can then specify through checkout_index_index.xml on a per input basis.

In my .xml file, I've tried adding the following under the fields (using company as an example), but with no luck:

`<item name="company" xsi:type="array">
       <item name="config" xsi:type="array">
            <item name="template" xsi:type="string">ui/form/field2</item>
	</item>
  </item>`

Every other change I'm making to the .xml file is working correctly, such as updating the input templates themselves with `<item name="elementTmpl" xsi:type="string">`, but I can't get anything other than field.html to load around the inputs. 

Also, changes to the original field.html template are applied correctly.  It's only adding additional templates that doesn't work.

Hopefully someone can help.  Thanks in advance.

**Comment by veloraven** [comment]
@nlscrw GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think this to be an issue which requires fixing please create new GitHub issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
