### ISSUE TITLE
Magento 2.1.2 Authorize.net Amex Transaction Declined Infinite Spinwheel

### ISSUE THREAD

**Issue by btjackson11** [magento/magento2#7255]
After testing my credit card payment method in my Magento 2.1.2 shop using the Authorize.net test Amex card information I place the order and it shows "Please Wait" infinitely, while in my exception logs it is showing a Transaction Declined (what it should be showing) error.

### Preconditions
1. Magento 2.1.2 
2. Php 5.6.1

### Steps to reproduce
1. Setup Authorize.net Direct Post
2. Place order with test Amex card

### Expected result
1. Should display some sort of error message saying that the transaction has been declined

### Actual result
1. Get this error in my exception log (seems correct): `[2016-10-31 20:39:20] main.CRITICAL: Magento\Framework\Exception\LocalizedException: Gateway error: This transaction has been declined. in /chroot/home/html/shop/vendor/magento/module-authorizenet/Model/Directpost.php:638`
2. This is the page screenshot of the spin wheel after hitting 'Place Order'

![screen shot 2016-10-31 at 1 50 22 pm](https://cloud.githubusercontent.com/assets/11138810/19871172/04129d58-9f71-11e6-9813-faee7968f2d2.png)

**Comment by jernejh** [comment]
possibly related to https://github.com/magento/magento2/issues/5642

**Comment by YevSent** [comment]
Hi, @btjackson11, thanks for reporting.

Please, attach debug log with declined transaction.

**Comment by btjackson11** [comment]
@joni-jones the debug log for the declined transaction is below.

`[2016-11-03 17:15:05] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://WEBSITEURL.com/authorizenet/directpost_payment/place/","invalidateInfo":{"tags":["catalog_product_344","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-03 17:15:05] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://WEBSITEURL.com/authorizenet/directpost_payment/place/","invalidateInfo":{"tags":["catalog_product_345","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-03 17:15:13] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://WEBSITEURL.com/authorizenet/directpost_payment/response","invalidateInfo":{"tags":["catalog_product_345","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-03 17:15:13] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://WEBSITEURL.com/authorizenet/directpost_payment/response","invalidateInfo":{"tags":["catalog_product_345","FPC"],"mode":"matchingTag"},"is_exception":false} []`

and then in the exception log (same as in original post):
`[2016-11-03 17:15:13] main.CRITICAL: Magento\Framework\Exception\LocalizedException: Gateway error: This transaction has been declined. in /chroot/home/ecommast/WEBSITEURL.com/html/shop/vendor/magento/module-authorizenet/Model/Directpost.php:638
`

**Comment by YevSent** [comment]
@btjackson11, thanks, but this is not full log for a transaction. Your debug log should contain authorize.net transaction details. Please, check Authorize.net configuration, debug should be enabled.

**Comment by btjackson11** [comment]
@joni-jones here is the full log for the transaction with the debug turned on

`[2016-11-04 17:14:21] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://WEBSITEURL.com/index.php/authorizenet/directpost_payment/place/","invalidateInfo":{"tags":["catalog_product_344","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-04 17:14:21] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://WEBSITEURL.com/index.php/authorizenet/directpost_payment/place/","invalidateInfo":{"tags":["catalog_product_350","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-04 17:14:21] main.DEBUG: array (
  'request' => 
  array (
    'x_version' => '3.1',
    'x_delim_data' => 'FALSE',
    'x_relay_response' => 'TRUE',
    'x_test_request' => 'FALSE',
    'x_login' => '****',
    'x_method' => 'CC',
    'x_relay_url' => 'http://WEBSITEURL.com/index.php/authorizenet/directpost_payment/response',
    'x_type' => 'AUTH_ONLY',
    'x_fp_sequence' => '109',
    'x_invoice_num' => '000000047',
    'x_amount' => 30.809999999999999,
    'x_currency_code' => 'USD',
    'x_tax' => '1.35',
    'x_freight' => '12.51',
    'x_first_name' => 'Ben',
    'x_last_name' => 'Jackson',
    'x_company' => '',
    'x_address' => '123 Main St',
    'x_city' => 'Huntington Beach',
    'x_state' => 'California',
    'x_zip' => '92648-7101',
    'x_country' => '',
    'x_phone' => '0000000000',
    'x_fax' => '',
    'x_cust_id' => '',
    'x_customer_ip' => '108.38.217.99',
    'x_customer_tax_id' => '',
    'x_email' => 'btjackso@asu.edu',
    'x_email_customer' => '0',
    'x_merchant_email' => '',
    'x_ship_to_first_name' => 'Ben',
    'x_ship_to_last_name' => 'Jackson',
    'x_ship_to_company' => '',
    'x_ship_to_address' => '123 Main St',
    'x_ship_to_city' => 'Huntington Beach',
    'x_ship_to_state' => 'California',
    'x_ship_to_zip' => '92648-7101',
    'x_ship_to_country' => '',
    'x_po_num' => '',
    'x_fp_timestamp' => 1478279661,
    'x_fp_hash' => '8a2df994f181523643be15addb97477f',
  ),
) {"is_exception":false} []
[2016-11-04 17:14:29] main.DEBUG: array (
  'response' => 
  array (
    'x_response_code' => '2',
    'x_response_reason_code' => '3',
    'x_response_reason_text' => 'This transaction has been declined.',
    'x_avs_code' => 'P',
    'x_auth_code' => '5211',
    'x_trans_id' => '8730263308',
    'x_method' => 'CC',
    'x_card_type' => 'American Express',
    'x_account_number' => 'XXXX0002',
    'x_first_name' => 'Ben',
    'x_last_name' => 'Jackson',
    'x_company' => '',
    'x_address' => '123 Main St',
    'x_city' => 'Huntington Beach',
    'x_state' => 'California',
    'x_zip' => '92648-7101',
    'x_country' => '',
    'x_phone' => '0000000000',
    'x_fax' => '',
    'x_email' => 'btjackso@asu.edu',
    'x_invoice_num' => '000000047',
    'x_description' => '',
    'x_type' => 'auth_only',
    'x_cust_id' => '',
    'x_ship_to_first_name' => 'Ben',
    'x_ship_to_last_name' => 'Jackson',
    'x_ship_to_company' => '',
    'x_ship_to_address' => '123 Main St',
    'x_ship_to_city' => 'Huntington Beach',
    'x_ship_to_state' => 'California',
    'x_ship_to_zip' => '92648-7101',
    'x_ship_to_country' => '',
    'x_amount' => '30.81',
    'x_tax' => '1.35',
    'x_duty' => '0.00',
    'x_freight' => '12.51',
    'x_tax_exempt' => 'FALSE',
    'x_po_num' => '',
    'x_MD5_Hash' => '57CF5C5627F7846BB24F30599647FA0C',
    'x_SHA2_Hash' => '762A2A821E58DF461734B2781786C9EE7CF340DF523817FACB5659C6644941310ED46E28789D6901CBC4C3BF54ED9FF1D959EFFA2776D09E5FBB36EE408C53AA',
    'x_cvv2_resp_code' => 'P',
    'x_cavv_response' => '',
    'x_test_request' => 'false',
    'controller_action_name' => 'directpost_payment',
    'is_secure' => '',
  ),
) {"is_exception":false} []
[2016-11-04 17:14:30] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://WEBSITEURL.com/index.php/authorizenet/directpost_payment/response","invalidateInfo":{"tags":["catalog_product_350","FPC"],"mode":"matchingTag"},"is_exception":false} []
[2016-11-04 17:14:30] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://WEBSITEURL.com/index.php/authorizenet/directpost_payment/response","invalidateInfo":{"tags":["catalog_product_350","FPC"],"mode":"matchingTag"},"is_exception":false} []
`

**Comment by duffner** [comment]
Similar Issue, We are not receiving a response back from Authorize.net, and this only happens occasionally.

**Comment by YevSent** [comment]
@btjackson11, your response from Authorize.net contains error code

```
'x_response_code' => '2',
'x_response_reason_code' => '3',
'x_response_reason_text' => 'This transaction has been declined.'
```

Please, re-check your configuration (credentials, sandbox URLs).

**Comment by btjackson11** [comment]
Not sure what changed but this problem seems to not be happening anymore, thank you.
