### ISSUE TITLE
Edit items link on multishipping goes to wrong route

### ISSUE THREAD

**Issue by MaN4thes3t** [magento/magento2#7257]
**Preconditions**

1. Developer mode, ubuntu, php 7
2. Magento 2.1

**Steps to reproduce**

1. Add item to cart
2. Select checkout with multi shipping addresses
3. Click to go to shipping
4. Click to edit items icon

**Expected result**

1. Should go to /checkout/cart page

**Actual result**
Goes to 404 page (/multishipping/cart). 

[Screenshot, logs]
Issue in file vendor/magento/module-multishipping/Block/Checkout/Billing/Items.php in getVirtualProductEditUrl(). Should be:    
public function getVirtualProductEditUrl()
    {
        return $this->getUrl('checkout/cart');
    }

**Comment by dthampy** [comment]
Internal jira ticket to track this issue is : MAGETWO-60523

**Comment by SerhiyShkolyarenko** [comment]
MAGETWO-60523 is delivered to the develop branch. We are closing the issue.

**Comment by KrystynaKabannyk** [comment]
Backports for 2.0.x and 2.1.x are created as well: MAGETWO-61369, MAGETWO-61370.

**Comment by Ctucker9233** [comment]
@KrystynaKabannyk backports have been created? Or are going to be created?

**Comment by Ctucker9233** [comment]
@magento-engcom-team When might this fix be included in 2.1?
