### ISSUE TITLE
Index error after saving same value in multiselect double

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#7258]
### Preconditions
Magento version: 2.1.2
PHP 7

### Steps to reproduce
1. Create or update a product via API
2. Specify a multiselect value with the same ID multiple times in an array
3. Try to reindex Magento

### Expected result
1. Magento should just reindex because the duplicate values should also be filtered by Magento.

### Actual result
1. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8419-139-3-2476' for key 'PRIMARY', query was: INSERT INTO `catalog_product_index_eav_idx` (`entity_id`,`attribute_id`,`store_id`,`value`) VALUES (?, ?, ?, ?)..... etc.

### Comment
I do understand we should also check this before adding the product to the API, and from now on we do. But ofcource it could always happen and I think it would be best if Magento would check if because otherwise the whole index will be broken untill the duplicate values are removed from the database.

**Comment by olysenko** [comment]
Hi , thank you for your reporting. Sorry I cannot reproduce issue. Please, provide information which service you used to update product with attribute and request body content

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
