### ISSUE TITLE
Simple product prices in a configurable product get reset to zero

### ISSUE THREAD

**Issue by samgranger** [magento/magento2#7260]
### Preconditions
1. Magento 2.1.2
2. Chrome

### Steps to reproduce
1. Create a configurable product & make sure the simple products all have a price. Save this product (English/US admin language).
2. Switch your admin language to Dutch.
3. Go to the same configurable product & save it. You will notice that the simple products will change to $0 after doing so.

### Expected result
1. The simple product prices should remain the same.

### Actual result
1. The simple product prices change to zero.

After looking at the payload, we concluded that prices are sent with a comma (Dutch) as a decimal point instead of a dot (English). This seems to cause this issue.

**Comment by dthampy** [comment]
Internal jira ticket MAGETWO-60441 is created to track this issue. Thank you for your bug report.

**Comment by magento-engcom-team** [comment]
@samgranger, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
