### ISSUE TITLE
Sales Orders displayed are not sorted 

### ISSUE THREAD

**Issue by MikeOshadami** [magento/magento2#7261]
### Preconditions

1. Magento 2.1.2
2. PHP 5.6.26
3. MySQL .6.26

### Steps to reproduce

1. Add a new Order
2. Go to dashboard, see order
3. Go to Admin-Sales-orders

### Expected result

1. Should see new orders at the top in the order grid.

### Actual result

1. new orders are not shown at the top, some appears in the middle or next page.
![magento_orders](https://cloud.githubusercontent.com/assets/4987546/19890659/7ea8c92c-a03c-11e6-8bfb-dc597f285746.PNG)

**Comment by veloraven** [comment]
@oshadami thank you fot your feedback.
As I can see from the screenshot, orders are shown in the correct order as two last have '0' as the first digit while all other have '1'. 
You can use sorting by Purchase date to see new orders first.

**Comment by veloraven** [comment]
I'm closing this issue as according to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
