### ISSUE TITLE
Authorized.net "Sorry, but something went wrong. Please contact the seller."

### ISSUE THREAD

**Issue by mvaisberg** [magento/magento2#7265]
**Preconditions**

Magento 2.1.0
PHP 5.6.26
MySQL .6.26

**Steps to reproduce**

Go to checkout and pay with authorized.net (sandbox or production, i tested both)
should see a message "Sorry, but something went wrong. Please contact the seller." 

**Expected result**

Should see success page after pay.

**Actual result**

After click in "placer order" with authorized.net i get that error. I searched about it in the code and appear in the file 

app/code/Magento/Authorizenet/view/frontend/web/js/view/payment/method-renderer/authorizenet-directpost.js

Line 16 : timeoutMessage: 'Sorry, but something went wrong. Please contact the seller.'

The debug.log show me the array sent to authorized, and it seem good.

Do anyone have a clue about how to fix it?

Any clue in any log file

![selection_014](https://cloud.githubusercontent.com/assets/4543889/19897223/e2bedab4-a05f-11e6-8217-310c4c47ad4a.png)

**Comment by jernejh** [comment]
possibly connected with https://github.com/magento/magento2/issues/5642

**Comment by YevSent** [comment]
Hi @mvaisberg, thanks for reporting.
Could you check errors in a browser console, attach debug log and response from `transact.dll` request?

**Comment by mvaisberg** [comment]
Hi @joni-jones thank you for the answer.

This is the response log in the debug.xml:

![selection_017](https://cloud.githubusercontent.com/assets/4543889/19929543/87ce70b2-a10c-11e6-80ae-aefb125a8e62.png)

In my console of the browser i haven't any error, this is the screenshot:

![selection_016](https://cloud.githubusercontent.com/assets/4543889/19929569/9ac9f7fe-a10c-11e6-8887-bdbb14aa5c86.png)

You can try reproduce the error trying to buying in https://billiespecansm2.121getsitdone.com/
I used this sandbox card number: 5424000000000015

In the first screenshot appear my local url but the same log appear in the staging environment (https://billiespecansm2.121getsitdone.com/).

Do you need anything else?

**Comment by YevSent** [comment]
Do you use Authorize.net production or sandbox mode?
Also, your `x_relay_url` looks like URL for a local environment, but authorize don't work for local instances.

**Comment by mvaisberg** [comment]
I tried with sandbox credentials and production credentials, both same issue. The screenshot are from sandbox credentials.

Same error apear in staging enviroment too. 

![selection_018](https://cloud.githubusercontent.com/assets/4543889/19929925/8c352716-a10e-11e6-916d-781887ad7055.png)

**Comment by YevSent** [comment]
For sandbox environment, the `Test Mode` option should be disabled (`x_test_request`), this option only for production mode.

**Comment by mvaisberg** [comment]
I changed test mode to "No" and still not working

![selection_021](https://cloud.githubusercontent.com/assets/4543889/19931445/359b1b2a-a115-11e6-9915-45e24e6cd053.png)

**Comment by YevSent** [comment]
Please, attach response from `transact.dll` request.

**Comment by mvaisberg** [comment]
How can i get it? is there a log or i have to debug the core?

**Comment by YevSent** [comment]
You can get response from browser network console.

**Comment by mvaisberg** [comment]
After click in place order this request response appear

![selection_024](https://cloud.githubusercontent.com/assets/4543889/19931939/ec3881e6-a116-11e6-828f-06a66ee00d31.png)

![selection_023](https://cloud.githubusercontent.com/assets/4543889/19931915/de2a5692-a116-11e6-8a8b-04531f739470.png)

The second one is:

{"success":true,"authorizenet_directpost":{"fields":{"x_version":"3.1","x_delim_data":"FALSE","x_relay_response":"TRUE","x_test_request":"FALSE","x_login":"9J3dXq88rc","x_method":"CC","x_relay_url":"https:\/\/billiespecansm2.121getsitdone.com\/authorizenet\/directpost_payment\/response","x_type":"AUTH_CAPTURE","x_fp_sequence":"64","x_invoice_num":"000000028","x_amount":26.39,"x_currency_code":"USD","x_tax":"0.00","x_freight":"0.00","x_first_name":"Francis","x_last_name":"Spencer","x_company":"","x_address":"14349 Washington Blvd","x_city":"Cleveland","x_state":"Ohio","x_zip":"44118","x_country":"","x_phone":"2165866656","x_fax":"","x_cust_id":"","x_customer_ip":"206.123.129.223","x_customer_tax_id":"","x_email":"francis2@121ecommerce.com","x_email_customer":"0","x_merchant_email":"pablo@121ecommerce.com","x_ship_to_first_name":"Francis","x_ship_to_last_name":"Spencer","x_ship_to_company":"","x_ship_to_address":"14349 Washington Blvd","x_ship_to_city":"Cleveland","x_ship_to_state":"Ohio","x_ship_to_zip":"44118","x_ship_to_country":"","x_po_num":"","x_fp_timestamp":1478095743,"x_fp_hash":"466d2668857d41df686e7f9a4cfe809f","controller_action_name":"directpost_payment","is_secure":"1"}}}

**Comment by YevSent** [comment]
You need a response from `transact.dll`.
![transactdll](https://cloud.githubusercontent.com/assets/2736528/19932137/9489bc7a-a117-11e6-98b2-51f903f50a7a.png)
Also, check if URL for `transact.dll` is correct (`https://test.authorize.net/gateway/transact.dll` for sandbox)

**Comment by mvaisberg** [comment]
ok, changing that for sandbox it works!

should i use "https://secure.authorize.net/gateway/transact.dll" ?

**Comment by YevSent** [comment]
Sandbox URLs:
https://test.authorize.net/gateway/transact.dll - gateway
https://apitest.authorize.net/xml/v1/request.api - transaction details

Production URLs:
https://secure.authorize.net/gateway/transact.dll - gateway
https://api.authorize.net/xml/v1/request.api - transaction details

For more details, please, see [API reference](http://developer.authorize.net/api/reference/) .

**Comment by mvaisberg** [comment]
Thanks, it works perfecto in both sandbox and production now !!!

thanks you very much!!

**Comment by abi2** [comment]
I'm experiencing the same issue,
I'm in production mode and using the correct Production URLs,
Any help?

Thank you!

**Comment by mvaisberg** [comment]
Do you have authorized.net in live mode and Test Mode => No in the configuration of magento?

Attach please the response in var/log/debug.xml

**Comment by abi2** [comment]
authorize.net is in live mode,
(replaced domain with changed.com)
[debug.log.txt](https://github.com/magento/magento2/files/567144/debug.log.txt)

Thanks for your help!

**Comment by spyrule** [comment]
So, we were experiencing this problem over the past 2 weeks, and have hunted for the problem the entire time.  For us, it turns out, that once I asked our Host provider to see if they could see any responses back from authorize.net's network at the time of the timestamp, Auth.net was hitting our maintenance mode flag.

We have been running the site in Maintenance mode with a set of whitelisted IPs to allow us access, but blocking public access.

Well, as soon as I disabled the maintenance flag, re-did a purchase that I have done a bunch of time, the entire sequence suddenly started to work flawlessly (from what we can tell at this time), we actually get a Order# and the message: "We'll email you an order confirmation with details and tracking info.".

On a side note, if you are running multiple stores and store views, the setting at each Store IS NOT being used. It is defaulting to the base website settings. There is a fix (see issue [#7943](https://github.com/magento/magento2/issues/7943))
But these two items combined caused nearly two weeks of troubleshooting to find these resolutions.

Hope this helps somebody.

**Comment by ak5646** [comment]
I have used all the following url for authoirize.net account setup in Magento 2.1.1 but still getting same error "Sorry, but something went wrong. Please contact the seller"

Sandbox URLs:
https://test.authorize.net/gateway/transact.dll - gateway
https://apitest.authorize.net/xml/v1/request.api - transaction details

Production URLs:
https://secure.authorize.net/gateway/transact.dll - gateway
https://api.authorize.net/xml/v1/request.api - transaction details

https://secure2.authorize.net/gateway/transact.dll 
https://api2.authorize.net/xml/v1/request.api

here i am attaching transact.dll  console of my sandbox account

![transact](https://cloud.githubusercontent.com/assets/8587827/23274714/bc697c06-fa29-11e6-961f-896f7bb0660c.PNG)

**Comment by reinvention18** [comment]
did you find a solution? i as well am getting the same issue in 2.1.4

**Comment by spyrule** [comment]
I would like to update this item where we found another item that can cause this problem. If you've got a multi-store configuration and you've got Geo-IP forwarding setup, it seem as though some Geo-IP extensions are preventing the final response back from authorize.net's network that the sale was successful, and so the end user is seeing the "something went wrong..." message, when in fact the order was successful. We disabled our Geo-IP as a quick test and "voila" things started to work again. I'm not going to name the extension vendor, as they are working on resolving the problem, but I thought it would be prudent to tell some people of this situation. Again though, the order is successful (on both M2 backend and in Authorize.net's network), but the buyer is getting the wrong message.

**Comment by Jeevachezhiyan** [comment]
Hi,
     I am getting issue below like this but my credentials working fine in magento1.9 but in magento2 it's not working i configured in sandbox mode please check the error below.

<html>
   <head>
       <script>
                   window.location="http://xxxxx/authorizenet/directpost_payment/redirect/x_invoice_num/000000069/success/0/error_msg/Please enter a transaction ID to authorize this payment./controller_action_name/directpost_payment/";
               </script>
   </head>
   <body></body>
</html>


Debug log:
[2017-07-17 10:16:20] main.DEBUG: array (
  'request' => 
  array (
    'x_version' => '3.1',
    'x_delim_data' => 'FALSE',
    'x_relay_response' => 'TRUE',
    'x_test_request' => 'TRUE',
    'x_login' => '****',
    'x_method' => 'CC',
    'x_relay_url' => 'http://xxxxxx/authorizenet/directpost_payment/response',
    'x_type' => 'AUTH_ONLY',
    'x_fp_sequence' => '129',
    'x_invoice_num' => '000000072',
    'x_amount' => 408,
    'x_currency_code' => 'USD',
    'x_tax' => '0.00',
    'x_freight' => '5.00',
    'x_first_name' => 'Tester',
    'x_last_name' => 'Test',
    'x_company' => 'Test',
    'x_address' => 'Test',
    'x_city' => 'Test',
    'x_state' => 'Armed Forces Canada',
    'x_zip' => '123456',
    'x_country' => '',
    'x_phone' => '1234567890',
    'x_fax' => '',
    'x_cust_id' => '',
    'x_customer_ip' => '182.74.57.131',
    'x_customer_tax_id' => '',
    'x_email' => 'testingteamtest3@gmail.com',
    'x_email_customer' => '0',
    'x_merchant_email' => '',
    'x_ship_to_first_name' => 'Tester',
    'x_ship_to_last_name' => 'Test',
    'x_ship_to_company' => 'Test',
    'x_ship_to_address' => 'Test',
    'x_ship_to_city' => 'Test',
    'x_ship_to_state' => 'Armed Forces Canada',
    'x_ship_to_zip' => '123456',
    'x_ship_to_country' => '',
    'x_po_num' => '',
    'x_fp_timestamp' => 1500286580,
    'x_fp_hash' => '5b364690c3df53ef5b254bc574de09d9',
  ),
) {"is_exception":false} []

**Comment by spyrule** [comment]
@Jeevachezhiyan it looks like your response URL is too long (unless you've modified it): "success/0/error_msg/**Please enter a transaction ID to authorize this payment.**/controller_action_name/directpost_payment/"

it should look something like : "https://www.website.com/authorizenet/directpost_payment/response"

Oh, and your URL MUST use https for authorize.net or it will not respond correctly.

**Comment by Jeevachezhiyan** [comment]
@spyrule that one is default magento response url , i did n't change anything and one more thing in magento 1.9 working fine with http.

**Comment by dinkeronline** [comment]
@joni-jones what if transact.dll doesn't appear in Network Console?
same as @mvaisberg shown

![ec3881e6-a116-11e6-828f-06a66ee00d31](https://user-images.githubusercontent.com/4199068/31357226-78bce1c6-ad5e-11e7-9236-32bd8148c1b4.png)

**Comment by Sairam9519** [comment]
I have used all the following url for authoirize.net account setup in Magento 2.2.3 but still getting same error "Sorry, but something went wrong. Please contact the seller"
Sandbox URLs:
https://test.authorize.net/gateway/transact.dll - gateway
https://apitest.authorize.net/xml/v1/request.api - transaction details

I'm attaching my transaction.dll
![authorizenet](https://user-images.githubusercontent.com/24208561/37853342-48d611dc-2f0c-11e8-819e-9aab3f86329f.png)

And also receiving email from authorize.net as below

Authorize.Net Developer Center Merchant,

Your script timed out while we were trying to post transaction results to it.
   Transaction ID: 0
Transaction Result: This transaction has been approved.

The following message was displayed to the customer:

------------------------------The reporting of this transaction to the Merchant has timed out. An e-mail has been sent to the merchant informing them of the error. The following is the result of the attempt to charge your credit card.

This transaction has been approved.

It is advisable for you to contact the merchant to verify that you will receive the product or service.


------------------------------

and the  response is 

<HTML><BODY><TABLE Width="600"><TR><TD>The reporting of this transaction to the Merchant has timed out. An e-mail has been sent to the merchant informing them of the error. The following is the result of the attempt to charge your credit card. <BR><BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This transaction has been approved.<BR><P>It is advisable for you to contact the merchant to verify that you will receive the product or service.<BR></TD></TR></TABLE></BODY></HTML>

 Help me out to solve the issue 
Thank you!

**Comment by treii28** [comment]
I'm getting this issue on v2.2.2, transactions are showing up on the authorize.net account, but there is nothing in the debug log (as in no transaction details - server is currently in development mode, authorize settings have Debug set to Yes)

We re-ran another test and checked the details of the transact.dll ajax call as one of the posters did above and I was able to validate that magento/jquery is receiving the default timeout response from authorize mentioned in a few of the postings. The x_relay_url looks fine but because we are using a varnish cache, I do not it says x_customer_ip as 127.0.0.1 in the request. I'm assuming this doesn't cause a problem as it appears the transaction is going through but magento is not completing on it's end.



x_customer_ip | 127.0.0.1
...
x_relay_url | https://www.oursite.com/authorizenet/directpost_payment/response

checking the access log I see nothing for a grep of directpost_payment

**Comment by yogeshkarodiya** [comment]
Facing same issue in magento2.2.3. Have any update for it?

**Comment by jarsh88** [comment]
We are trying this:
I understand you are getting an error 14. I am happy to assist you with that today.

This error means that the Referrer or Relay Response URL is invalid. 
If you prefer to have your customer view our receipt page that includes a link to return to your site, you should be submitting the x_receipt_link_url field. Alternately, if you want to use your own receipt page hosted on your site, you should be submitting the x_relay_url field. Error 14 occurs for SIM users when a transaction request is submitted that includes values for x_receipt_link_url or x_relay_url that are not specified in your Default Response/Receipt URL settings in the Merchant Interface.

By designating one or more Default Response/Receipt URLs, you are telling the payment gateway to only allow customers to return to one of the specified URLs after submitting the payment form. If the value of either x_receipt_link_url or x_relay_url does not match one of these designated Default Response/Receipt URLs, Error 14 will occur.

While x_receipt_link_url and x_relay_url will work without specifying a Default Response/Receipt URL, it is strongly suggested that you set Default Response/Receipt URLs if you are sending either of these fields, to ensure that only these URLs can be used.

To add a valid Response/Receipt URL:

1. Log into the Merchant Interface at https://account.authorize.net/. 
2. Click Settings under Account in the main left side menu. 
3. Click Response/Receipt URLs under Transaction Format Settings. 
4. Click Add URL. 
5. Enter your Response URL. 
6. Click Submit.

For additional assistance with your code, you can visit the Developer Forum at: http://community.developer.authorize.net/

You may also want to review this:

https://developer.authorize.net/api/reference/responseCodes.html"

**Comment by jmlaing** [comment]
Just in case someone stumbles in here, this might save you some time - if you've checked everything above, check your sandbox account's "Response/Receipt URLs" under Settings. It's a whitelist as to where the sandbox will accept requests from...make sure you've whitelisted your current testing site.

**Comment by Accurno** [comment]
For anyone using Google's PageSpeed, try disabling it first see if it'll fix the issue. The JS defer was causing the issue in my case and the Magento asset files was mistakenly being loaded relatively to authorize.net

https://secure.authorize.net/static/version1543968498/frontend/custom_template/custom/en_US/css/styles-l.css

Instead of

https://mydomain.com/static/version1543968498/frontend/custom_template/custom/en_US/css/styles-l.css
