### ISSUE TITLE
Magento 2.1.2 Cannot save CMS Page

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#7268]
### Preconditions
1. Magento 2.1.2 Upgraded by CLI from 2.1.1
2. PHP 5.6.x

### Steps to reproduce
1. Navigate to store backend
2. Go to content -> Pages
3. Create new page
4. Add content
5. Save

### Expected result
1. Page saves with no problems

### Actual result
Page does not save. Clicking on the save button or the same and continue button has no results. Reference Issue #5295

I do not have any error logs to suggest where the problem may lie.

**Comment by Ctucker9233** [comment]
Clearing all caches plus var/generation /view_preprocessed /cache doesn't help.

**Comment by ihor-sviziev** [comment]
@Ctucker9233 could you open developer tools (F12) and show console? I think you have JS issue, maybe broken static

**Comment by Ctucker9233** [comment]
@ihor-sviziev yes, you are correct. I cleared pub/static, redeployed static content and the button works again. Thanks for pointing me in the right direction. Closing issue.
