### ISSUE TITLE
Visual swatch preventing the display of the required asterisk for any attributes that's display before it.

### ISSUE THREAD

**Issue by dhx2** [magento/magento2#7270]
When a configurable product has a visual swatch, the required asterisk for all attributes display before it is missing.

Magento CE 2.1.2 with actual products.

**Recreate:**
1. Create some product attributes:
   2. Select Drop Down as it's Catalog Input Type.
   3. Mark it as required
4. Create an attribute using the Visual Swatch Catalog Input Type 
5. Assign all newly created attribute to an attribute set.
6. Create a configurable product with the above attribute set.
7. View the product on the front-end and take note the required asterisk is missing from the attributes.
8. Change the attribute with the visual swatch input type to a drop down.
9. Save, flush cache and refresh the front-end.
10. Take note of the required asterisk for the corresponding attributes.

**Expecting Results:**
The required asterisk should be visible when using a visual swatch attribute.

![image](https://cloud.githubusercontent.com/assets/18651295/19912691/932458a4-a059-11e6-8324-7dcbcb87df56.png)

![image](https://cloud.githubusercontent.com/assets/18651295/19912696/99a8301a-a059-11e6-9013-f613281cd88b.png)

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue was created MAGETWO-60597

**Comment by magento-engcom-team** [comment]
@dhx2, thank you for your report.
We've created internal ticket(s) MAGETWO-60597 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @dhx2

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@dhx2 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
