### ISSUE TITLE
REST API - Unable to authenticate using admin-only domain

### ISSUE THREAD

**Issue by matmarchant** [magento/magento2#7271]
It is not possible to authenticate using the REST API if a store is set up with a different front-end and backend domain - as many international retailers do. e.g. 
www.mystore.com - frontend (mage run code default)
admin.mystore.com/admin - backend (mage run code admin)

### Preconditions
1. Magento ver. 2.0.8
2. PHP 7.0.12 (cli) (built: Oct 15 2016 19:03:00)
3. nginx version: nginx/1.9.15
4. mysql server version: 5.6.32-78.1-56-log Percona XtraDB Cluster

### Steps to reproduce
1. Use POSTMAN to attempt a login to https://admin.mysite.co.uk/rest/V1/integration/admin/token

### Expected result
1. Authentication token should be returned

### Actual result
1. SQLSTATE[42S02]: Base table or view not found: 1146 Table '.catalog_category_flat' doesn't exist, query was: SELECT `main_table`.`entity_id`, `main_table`.`level`, `main_table`.`path`, `main_table`.`position`, `main_table`.`is_active`, `main_table`.`is_anchor`, `main_table`.`url_key`, `main_table`.`name`, `main_table`.`is_anchor` FROM `catalog_category_flat` AS `main_table` WHERE (`entity_id` IN('1')) AND (`is_active` = '1') ORDER BY name ASC

**Comment by flancer64** [comment]
@maximinimus , "catalog_category_flat" is not an authentication related table. Try to re-index your data:

```
$ ./bin/magento indexer:reindex
```

then post your authentication request once again.

**Comment by matmarchant** [comment]
The first thing I tried was a reindex. The results I posted are following the full reindex.
I am also running in developer mode and have cleared my var/generation var/cache and var/page_cache folders.

**Comment by flancer64** [comment]
Is URL "https://admin.mysite.co.uk/V1/integration/admin/token" correct? "_/rest/V1/integration/admin/token_" & "_/rest/default/V1/integration/admin/token_" are correct URLs for me ("default" is a store view code).

**Comment by matmarchant** [comment]
I typed out the address wrong on the ticket, I have since updated it to the correct url - /rest/V1/integration/admin/token

As soon as I change the admin-only domain to use a front-end store code, the webservice will authenticate. Setting it to "website" scope and "admin" run code produces the error.

**Comment by olysenko** [comment]
Please, provide more information in which way you setup your routing (i.e. how you setup mage run codes  backend and default)

**Comment by matmarchant** [comment]
The mage run code is using a config map from nginx:
i.e. 
map $http_host $MAGE_RUN_CODE {
  magento2.loc default;
  admin.magento2.loc admin;
}

Then in my fastcgi settings in the server block:

fastcgi_param  MAGE_RUN_TYPE website;
fastcgi_param  MAGE_RUN_CODE $MAGE_RUN_CODE;

**Comment by olysenko** [comment]
Please set Use Custom Admin URL to Yes in   Stores->Configuration->Advanced->Admin->->Admin Base URL  menu and specify your admin url. It is proper way to configure custom admin Url. In this case REST API authentication  is working

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
