### ISSUE TITLE
Combine widget rule 

### ISSUE THREAD

**Issue by Pigau** [magento/magento2#7274]
Hi,
I have some problem to use combine rule in product list widget.
It seems that the method Magento\CatalogWidget\Model\Rule\Condition\Combine::collectValidatedAttributes is not correct and try to call addToCollection without checking the rule type

### Preconditions
1.  Magento 2.1.1

### Steps to reproduce
1. Add a new widget 'Catalog Product List' on a cms page
2. Add a combine rule condition (ex: product_id=1 or price > 0)
3. Go to the page on front

### Expected result
1. See product list widget

### Actual result
1. Error : Invalide method Magento\CatalogWidget\Model\Rule\Condition\Combine::addToCollection 

Is anyone having the same problem ?
Thank you for your help

**Comment by olysenko** [comment]
Hi, Thank you for your report. Internal issue was created MAGETWO-60602

**Comment by SerhiyShkolyarenko** [comment]
MAGETWO-60602 is delivered to the develop branch. We are closing the issue.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Will there be a backport for 2.1?
