### ISSUE TITLE
Product editing: double buttons for Back and Save

### ISSUE THREAD

**Issue by kirashet666** [magento/magento2#7276]
Hi there,

I just discovered there are some buttons shown double if you edit a product in the magento administration.

See attached file.

### Preconditions

1. Magento 2.1.2

Is there a solution for that?

Thanks,
Ali

Edit: file upload seems broken: http://imgur.com/CwCQYXJ

**Comment by veloraven** [comment]
@kirashet666 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by kirashet666** [comment]
@veloraven Really? Just create a product and edit it. No need to elaborate.

**Comment by veloraven** [comment]
@kirashet666 
Please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result, so that it is easy to see at once what is the problem is. And other users can find this issue if they have the same one.
