### ISSUE TITLE
Order confirmation email send take time

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#7277]
In checkout when click on Place order button take time around 13 seconds.

And when
Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending > Enable.

Then it take 7 seconds.

So it take to much time ,also send email from admin order view page. Also sending custom email using 
 observer "checkout_onepage_controller_success_action".

So email sending very slow.

**Comment by mayankzemiprotech** [comment]
Yes you are right Man I also face the same problem. Checkout really take a too much time just because of send email.

**Comment by KrystynaKabannyk** [comment]
Hello @pareshe, thank you for reporting this issue, the internal ticket is created - MAGETWO-60521.
We will notify you once any changes are made.

**Comment by choukalos** [comment]
Hi @pareshe 

It sounds like you have customizations (order observer) that are sending emails when ever an order is placed in addition to Magento's out of the box emails.  Are you sending those custom emails synchronously?  Are your times also for customers that are creating accounts (we send emails - unfortunately not asynchronously for new registered customers)?

@mayankzemiprotech do you have custom observers/emails being sent or extensions doing that?  Do you know if those emails are being sent synchronously?

Thanks,
Chuck

**Comment by pareshe** [comment]
Hi @choukalos

We have removed out customisation , in fresh magento2  when
Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending > Disabled ,That take much time.

But Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending > Enabled , take to less time.

Customer registration is also taking around 10 seconds.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Order-confirmation-email-send-take-time/idi-p/54633).
