### ISSUE TITLE
Form Input Templates Not Being Applied on M2 Checkout

### ISSUE THREAD

**Issue by mr-ford** [magento/magento2#7278]
My issue was marked as closed without an answer so I'm posting again.

### Preconditions
I'm running Magento 2.1.1.

### Steps to reproduce
1) I'm attempting to update the template used to wrap the form fields on a per field basis via checkout_index_index.xml.

2) I've created new template files saved in the same place as the original template file 
(/module-ui/view/frontend/web/templates/form/field2.html, field3.html, etc.)

3) In my checkout_index_index.xml file, keeping all hierarchy in place, I've added the following under the fields I want to specify a new template for  (using company as an example).

<item name="company" xsi:type="array"> <item name="config" xsi:type="array"> <item name="template" xsi:type="string">ui/form/field2</item> </item> </item>

4) Additionally, input templates are working properly when using the elementTmpl item.

### Expected Result

The new field2 template should be applied to the company input but it isn't.

### Actual Result

The company input continues using the original /module-ui/view/frontend/web/templates/form/field.html template.

**Comment by aakimov** [comment]
Hello @nlscrw,

Thank you for your report and interest in Magento platform. We have confirmed this issue and reported internal ticket MAGETWO-61255 to resolve it.

Also I would like to provide some information that you can use as a work-around. Indeed, **ui/form/field** is hard-coded in *\Magento\Checkout\Block\Checkout\AttributeMerger::getFieldConfig* for all address attributes. But you can still override this value via custom checkout layout processor (*\Magento\Checkout\Block\Checkout\LayoutProcessorInterface*). Processor will receive layout structure as an array and you will be able to replace **template** node. More detailed information can be found on http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_new_field.html 

Thank you once again for your report.
Regards

**Comment by magento-engcom-team** [comment]
@nlscrw, thank you for your report.
We've created internal ticket(s) MAGETWO-61255 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@nlscrw, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
