### ISSUE TITLE
 PHP Parse error:  syntax error, unexpected '.' in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

### ISSUE THREAD

**Issue by pilardo** [magento/magento2#7281]
Preconditions
1. Magento Version: 2.1.2
2. PHP 7.0.12
3. MySql 5.6.33

Steps to reproduce
1. run composer install
2. setup:di:compile
3. setup:upgrade --keep-generated
4. flush cache

Expected result
1. able to load the site. instead of showing http 500 error.

Actual result
1.  PHP Parse error:  syntax error, unexpected '.' in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

Everything in SSH works correctly, upgrade, compile, clear cache, reindex...

**Comment by rganin** [comment]
Please verify you have same PHP version in httpd (by echoing `phpversion()` output or any).

**Comment by pilardo** [comment]
@rganin PHP version in http is 5.5.9-1ubuntu4.20, I also run php -v in command line it shows PHP 7.0.12-1+deb.sury.org.

**Comment by pilardo** [comment]
@rganin thank you for comment. it help to fix the issue.

**Comment by goldsky** [comment]
AbstractFactory.php line 93 is the culprit
```php
    /**
     * Create object
     *
     * @param string $type
     * @param array $args
     *
     * @return object
     *
     */
    protected function createObject($type, $args)
    {
        return new $type(...array_values($args));
    }
```
Let me know if PHP has `...array_values()` function now
