### ISSUE TITLE
_extend.less not merge in themes

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#7282]
Hi,
I have a custom theme, extends the luma theme, everything works properly. My custom less modifications were added in web/css/source/_extend.less

Now I would like to create a subtheme from this custom theme I created previously, but if I add a content to /web/css/source/_extend.less the css modifications added in the parent theme are not taken in consideration.

 Should't they be merged or how can i add elegantly new modifications to this new subtheme without copying over again the ones from the previous one. (I understand that _theme.less is not merged but from what I read _extend.less should be merged)

### Preconditions
1. magento 2.1.2 version was used

### Steps to reproduce

1. Create  a theme that extends for example luma theme
2. Add web/css/source/_extend.less with custom css modifications
3. Create a new subtheme from the previous one (set parent the previously created one)
4. Add web/css/source/_extend.less to this one as well and the previous _extend.less is not used, seems to be overwritten

**Comment by veloraven** [comment]
@ksz2013 thank you for your feedback.
If it is a question please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site. As GitHub issue tracker is intended for technical issues only.
If you think it to be an issue please add expected result and actual result to the description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
