### ISSUE TITLE
Get error when updating Category has a large number of products

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#7287]
### Preconditions

1. Magento 2.1.2, PHP 7.0.8, Mysql 5.7
2. Ubuntu Apache

### Steps to reproduce

1. Create new category (A) with Anchor = Yes, then create some sub categories below it.
2. Add a large of products to A and sub categories. In my case, the total count number of A more than 10000 products.

### Expected result

1. Category can be updated without error

### Actual result

1. Change category description and hit Save button
2. It takes to long to process (more than 10 min) and get memory error.
![2016-11-03_11-04-12](https://cloud.githubusercontent.com/assets/1607243/19955643/b88c6fca-a1b5-11e6-98b5-c9d9b97fbf40.png)

**Comment by rganin** [comment]
Thank you for reporting. Seems like an indexing performance issue. It is highly recommended to use 'Update On Schedule' indexer mode for large catalogs, try to switch it to defer indexing process and reproduce again.
Links to documentation:
- http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-index.html
- http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html

**Comment by phuc128t** [comment]
Still same result. This time it took me more than 20 min.

**Comment by rganin** [comment]
Thank you for clarification. The performance issue is in URLRewrite area, internal ticket created: MAGETWO-52305.

**Comment by choukalos** [comment]
We don't index this right now but sounds like we should be.  Assigning this to myself to see how this lines up with some of the performance and performance issues that are in flight now.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Get-error-when-updating-Category-has-a-large-number-of-products/idi-p/54627).

**Comment by ghost** [comment]
Was there a proper solution for this?
