### ISSUE TITLE
E-mail after Contact Us not in default e-mail layout (plain text)

### ISSUE THREAD

**Issue by PieterCappelle** [magento/magento2#7291]
### Preconditions
1. Magento 2.1.2
2. Default installation no plugins/extensions installed

### Steps to reproduce
1. Browse to the default Contact page with the default Contact form
2. Fill in the Contact Form and submit
3. E-mail will be sent to the email address you configured in the configuration panel

### Expected result
1. Receive e-mail in the Magento default header and footer layout (like orders, invoices, ...)

### Actual result
1. Plain text e-mail

**Comment by smoskaluk** [comment]
@PieterCappelle Hi! You may see that Magento use Default "Contact Form" Email Template (Stores - Configuration - General - Contacts - Email Options) If you want to see and amend this template, you need go to Marketing - Email Templates, click Add New Templates, choose in "Template" dropdawn input "Contact Form" and click "Load Template"

**Comment by magento-engcom-team** [comment]
@PieterCappelle the fix will be available in 2.2.0 release very soon
