### ISSUE TITLE
Managing large number of customer groups and Products.

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#7292]
I am working on a store where i need to import products on a daily basis and the number of products may go up to more then 1,90,000. The Store discount heavily depends on the customer groups which are around 8800 including the core ones in number.

The Products are imported seamlessly, but when trying to reindex the `Catalog Product Price index`, it inserts 130 million records in  `catalog_product_index_price_final_idx` table which takes huge time to complete.

Also the customer groups does not have any alternative. because catalog price rules, and tier prices depend heavily on them.

130 million records are a very huge amount of data on a mysql installations.

**Note** We have 15000 products as of now, but it is expected to increase to 1,90,000. so the number of records in `catalog_product_index_price_final_idx` table may got up to 1.65 billion records.

**Note:** The infrastructure of the server is optimized for high performance, with SSD for storage and MySQL configured using percona db.

**Comment by rganin** [comment]
Thanks for reporting, the performance improvement work for this area is on it's way to implementation. Internal ticket: MAGETWO-54578.

**Comment by choukalos** [comment]
Hello @Taral-Patoliya 

How many websites & store views do you have now and plan to expand to (that'll also have an impact on catalog index)?
Do you expect the # of customer groups to grow over time as well?  What would you expect them to grow to?
What's the longest indexer run time you'd be okay with?  Would you be okay having additional machines (aka workers) enabled to help run the indexer faster?

Would you be willing to do a Skype/video conference call to discuss?  My work email is exposed in my profile - please email me if so with some dates/times and your timezone (I'm in US/CST).

Thanks!
Chuck

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Managing-large-number-of-customer-groups-and-Products/idi-p/54623).
