### ISSUE TITLE
Dynamic rows date column in stores configuration

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#7295]
Date column in dynamic rows stores -> configuration field  throws SyntaxError: Invalid or unexpected token error.

### Preconditions
1. Magento 2.1.1
2. PHP 7

### Steps to reproduce
1. Create a custom module with system.xml containing a dynamic field which uses a class extending Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray
2. Use \Magento\Framework\View\Element\Html\Date as a column renderer

### Expected result
1.  Dynamic rows system config field with date type column

### Actual result
From and To Columns should be date type
1. ![2016-11-03 15_04_12-configuration _ settings _ stores _ magento admin google chrome](https://cloud.githubusercontent.com/assets/20812705/19966968/dabcebe4-a1d6-11e6-9c99-98ecf8050232.png)

**Comment by theodorhanu** [comment]
Adding any javascript to column renderer( like \Magento\Framework\View\Element\Html\Date does   ) will break functionality of dynamic rows

**Comment by theodorhanu** [comment]
A workaround which I found was to extend Magento\Framework\View\Element\Html\Date, override _toHtml method, remove all new lines within <script> tag and replace closing script tag with <'+'/script>.

It's only a workaround for dynamic rows in stores -> configuration.
If you have a better solution please let me know

**Comment by shwetabha** [comment]
Hello, 
I also got same error and remove all new line with change script tag. Error has removed but the time picker is not working. Any suggestion please?

**Comment by shwetabha** [comment]
Hello, 
I also got same error and remove all new line with change script tag. Error has removed but the time picker is not working. Any suggestion please?

**Comment by hallleron** [comment]
I am having the exact same issue right now with Magento 2.1.6. I removed all new lines and modified the closing script tag accordingly, but what I see is a text input and a "0" under it. Also all information from $this->getId() etc. is not present. @theodorhanu  do you have an excerpt o your solution for this issue? I am totally stuck here.

Basically my _toHtml() function looks like this right now:

```
public function _toHtml() {
	    
        //return parent::_toHtml();
        $html = '<input type="text" name="' . $this->getName() . '" id="' . $this->getId() . '" ';
        $html .= 'value="' . $this->escapeHtml($this->getValue()) . '" ';
        $html .= 'class="' . $this->getClass() . '" ' . $this->getExtraParams() . '/> ';
        $calendarYearsRange = $this->getYearsRange();
        $changeMonth = $this->getChangeMonth();
        $changeYear = $this->getChangeYear();
        $maxDate = $this->getMaxDate();
        $showOn = $this->getShowOn();
        
        $html .= '<script type="text/javascript">require(["jquery", "mage/calendar"], function($){console.log("asd");$("#' . $this->getId() . '").calendar({ showsTime: ' . ($this->getTimeFormat() ? 'true' : 'false') . ', ' . ($this->getTimeFormat() ? 'timeFormat: "' . $this->getTimeFormat() . '",' : '') . 'dateFormat: "' . $this->getDateFormat() . '", buttonImage: "' . $this->getImage() . '", ' . ($calendarYearsRange ? 'yearRange: "' . $calendarYearsRange . '",' : '') . 'buttonText: "' . (string)new \Magento\Framework\Phrase('Select Date') . '"' . ($maxDate ? ', maxDate: "' . $maxDate . '"' : '') . ($changeMonth === null ? '' : ', changeMonth: ' . $changeMonth) . ($changeYear === null ? '' : ', changeYear: ' . $changeYear) . ($showOn ? ', showOn: "' . $showOn . '"' : '') . '}) }); <'+'/script>';
        
        return $html;
    }

    /**
     * Sets name for input element
     * 
     * @param string $value
     * @return $this
     */
    public function setInputName($value) {
        return $this->setName($value);
    }
```

My column looks like this:
`$this->addColumn('date', [ 'label' => __('Datum'), 'renderer' => $this->getDatePickerRenderer() ]);`

And the getDatePickerRenderer function looks like this:

```
protected function getDatePickerRenderer() {
        if (!$this->_datePickerRenderer) {
            $this->_datePickerRenderer = $this->getLayout()->createBlock(
                '\Hallleron\Countdown\Block\Adminhtml\Form\Field\DateSelector', '', ['data' => ['is_render_to_js_template' => true]]
            );
        }
        return $this->_datePickerRenderer;
    }
```

**Comment by tristanhofman** [comment]
I have the same issue in Magento 2.1.7 tried the fix and had the same result as @hallleron

**Comment by theodorhanu** [comment]
Hi all! 
Sorry for my ( very ) late response.
It seems like the comment formatter did not helped here. 
Here is a snippet of my code:

    namespace [Your namespace here];
    use Magento\Framework\View\Element\Html\Date;
    class DateField extends Date{

        /**
         * Render block HTML
         *
         * @return string
         * @SuppressWarnings(PHPMD.NPathComplexity)
         */
        protected function _toHtml() {
            $html = '<input type="text" name="' . $this->getInputName() . '" id="' . $this->getInputId() . '" ';
            $html .= 'value="<%- ' . $this->getColumnName() .' %>" ';
            $html .= 'class="' . $this->getClass() . '" ' . $this->getExtraParams() . '/> ';
            $calendarYearsRange = $this->getYearsRange();
            $changeMonth        = $this->getChangeMonth();
            $changeYear         = $this->getChangeYear();
            $maxDate            = $this->getMaxDate();
            $showOn             = $this->getShowOn();

            $html .= '<script type="text/javascript">require(["jquery", "mage/calendar"], function($){ $("#' .
                     $this->getInputId() .
                     '").calendar({showsTime: ' .
                     ( $this->getTimeFormat() ? 'true' : 'false' ) .
                     ',' .
                     ( $this->getTimeFormat() ? 'timeFormat: "' .
                                                $this->getTimeFormat() .
                                                '",' : '' ) .
                     'dateFormat: "' .
                     $this->getDateFormat() .
                     '",buttonImage: "' .
                     $this->getImage() .
                     '",' .
                     ( $calendarYearsRange ? 'yearRange: "' .
                                             $calendarYearsRange .
                                             '",' : '' ) .
                     'buttonText: "' .
                     (string) new \Magento\Framework\Phrase(
                         'Select Date'
                     ) .
                     '"' . ( $maxDate ? ', maxDate: "' . $maxDate . '"' : '' ) .
                     ( $changeMonth === null ? '' : ', changeMonth: ' . $changeMonth ) .
                     ( $changeYear === null ? '' : ', changeYear: ' . $changeYear ) .
                     ( $showOn ? ', showOn: "' . $showOn . '"' : '' ) .
                     '})});<\'+\'/script>';

            return $html;
        }
    }

Please not the last part of the _toHtml method. The backslash is escaped inside string

**Comment by tristanhofman** [comment]
@theodorhanu Thx for your quick answer! It seems to work but when I select a date from the datepicker, the input field remains empty.

**Comment by theodorhanu** [comment]
Here is a snippet of my **system.xml**
    `<group id="production_holidays" translate="label" showInDefault="1" showInWebsite="1" showInStore="1" sortOrder="1">
                <label>Production Holidays</label>
                <field id="interval" translate="label" showInDefault="1" showInWebsite="1" showInStore="1" sortOrder="1">
                    <label>Production Holidays</label>
                    <frontend_model>Namespace\Module\Block\Adminhtml\System\Config\Holidays</frontend_model>
                    <backend_model>Namespace\Module\Model\System\Config\Holidays</backend_model>
                </field>
            </group>`

Now, the **Namespace\Module\Block\Adminhtml\System\Config\Holidays.php** looks like this:

    namespace Namespace\Module\Block\Adminhtml\System\Config;
    use Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray;
    class Holidays extends AbstractFieldArray {

        private $_dateRenderer;

        public function __construct(
            \Magento\Backend\Block\Template\Context $context,
            //\Magento\Framework\View\Element\Html\Date $dateRenderer,
            array $data = []
        ) {
            //$this->_dateRenderer = $dateRenderer;
            parent::__construct( $context, $data );

        }

        protected function _getDateColumnRenderer() {
            if( !$this->_dateRenderer ) {
                $this->_dateRenderer = $this->getLayout()->createBlock(
                    'Namespace\Module\Block\Adminhtml\System\Config\DateField',
                    '',
                    [
                        'data' => [
                            'is_render_to_js_template' => true,
                            'date_format'              => 'dd/mm/Y'
                        ]
                    ]
                );
            }

            return $this->_dateRenderer;
        }

        protected function _prepareToRender() {
            $this->addColumn( 'from', [ 'label' => __( 'From' ), 'renderer' => $this->_getDateColumnRenderer() ] );
            $this->addColumn( 'to', [ 'label' => __( 'To' ), 'renderer' => $this->_getDateColumnRenderer() ] );
            $this->addColumn( 'holiday', [ 'label' => __( 'Holiday' ), 'renderer' => false ] );

            $this->_addAfter       = false;
            $this->_addButtonLabel = __( 'Add' );
        }


        /**
         * Prepare existing row data object
         *
         * @param \Magento\Framework\DataObject $row
         *
         * @return void
         */
        protected function _prepareArrayRow( \Magento\Framework\DataObject $row ) {

            $data = $row->getData();
            if( count( $data['column_values'] ) ) {
                $new_data = [
                    'from'          => $data[0],
                    'to'            => $data[1],
                    'holiday'       => $data[2],
                    '_id'           => $data['_id'],
                    'column_values' => [
                        $data['_id'] . '_from'    => $data[0],
                        $data['_id'] . '_to'      => $data[1],
                        $data['_id'] . '_holiday' => $data[2]
                    ]
                ];
            } else {
                $new_data = [
                    'from'          => '',
                    'to'            => '',
                    'holiday'       => '',
                    '_id'           => $data['_id'],
                    'column_values' => []
                ];
            }
            $row->setData( $new_data );

        }
    }

And the **Namespace\Module\Block\Adminhtml\System\Config\DateField.php** is as posted in previous comment.

LE: I'm using Magento ver. 2.1.4. Did not have time to update to latest magento version, but I don't think it changed that much

**Comment by tristanhofman** [comment]
Awesome! thx man, great help! :)

**Comment by magento-engcom-team** [comment]
@theodorhanu, thank you for your report.
We've created internal ticket(s) MAGETWO-83352 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@theodorhanu, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
