### ISSUE TITLE
M2.1.2 : What are the plans on the URL rewrite module

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7300]
What are the plans for the URL rewrite module? Are there also going to be (API) service contract so it provides an easy interface to programatically add rewrites? Or a repository for example?

Just curious what to expect from Magento, or if I have to write something myself (and perhaps create a pull request for it?)

**Comment by pboisvert** [comment]
No immediate term plans for this. I would suggest posting to Stack Exchange or Community Forums to get some ideas on how others in the community may wish to extend and if you create a pull request we will review. Closing this here though as Issues are meant for reporting defects and not discussion.
