### ISSUE TITLE
M2.1.2: Date Attribute not saving for Products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7301]
### Preconditions

1. Magento CE 2.1.2
2. PHP 7.0.8+, MySQL 5.6+

### Steps to reproduce

1. Install Magento 2 CE from `composer create-project`.
2. Add new Product Attribute with type of "Date".
3. Add the created attribute to any Attribute Set (Default in this case).
4. Either create a new product or edit a current one.
5. Set the date to be any valid date value.
6. Save the product.

### Expected result

1. The new Date field should be filled out with the value input initially.

### Actual result

1. The new Date field is empty post-save.

**Comment by sevos1984** [comment]
This is known issue, internal ticket  MAGETWO-56396. Thanks for reporting

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.
The issue is already fixed in 2.2.0
