### ISSUE TITLE
[2.1.2] Integrity constraint violation error when saving product (google experiments on)

### ISSUE THREAD

**Issue by peec** [magento/magento2#7302]
Had to re-add this issue. Originally posted as #5709 .

### Preconditions

1. Install Magento 2.1.2 (fresh)
2. Go to admin -> Stores -> Configuration -> Sales -> Google API section
3. Change the configuration Enable Content Experiments to "Yes"
4. Save a configurable product and its child product consecutively.

**Environment**
PHP 7
Mysql 5.6
Nginx
Varnish
Production enabled
Google apis enabled
Google Content Experiments to yes
Indexes are on scheduled (all of em). cron.
One store view.

### Steps to reproduce

1. We can save the product successfully with any number of times.

### Expected result
1. Product is not saving properly.
1. Gives an error:

### Actual result

**SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-1383-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: UPDATE googleoptimizer_code SET entity_id = ? WHERE (code_id='50')**

### Workaround fix

Disable content experiments.

**Comment by erikhansen** [comment]
I also experienced this issue on Magento 2.1.2. I saved a configurable product after using the "Edit Configurations" wizard to create new children products. Disabling the Content Experiments fixed the issue.

**Comment by miakusha** [comment]
Hi @peec , @erikhansen  We cannot reproduce this issue as described. Please provide the detailed steps and configurations we must follow to reproduce this issue

**Comment by Will-I4M** [comment]
Did you created your products by duplicating another one ? 
You maybe forgot to change the url key in SEO optimmisation tab..

**Comment by ghost** [comment]
I also experienced same issue with configurable product.
To fix this issue I edit configurations options and its worked for me. please refer this link http://prntscr.com/e7px78

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
As there was no additional information provided, I'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by bartoszkubicki** [comment]
Still an issue in 2.3.5 - Commerce Edition
