### ISSUE TITLE
Magento2 Mini cart not working in icognito on chrome

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7304]
Hi,

I've installed magento2 using composer with version 2.1.1.
I found that minicart is not loading in icognito mode. Product has been successfully added to the cart and can see on the checkout/cart page but its not showing in minicart.
I've cache enabled and checking this issue on localhost wamp with php 7.

Thanks & Regards,
Deepak K.

**Comment by dthampy** [comment]
Internal ticket to track this: MAGETWO-60558

**Comment by magento-engcom-team** [comment]
@deepak-netwin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
