### ISSUE TITLE
Images in Product description disappear

### ISSUE THREAD

**Issue by ferrarinim** [magento/magento2#7306]
### Preconditions

1. Magenyo 2.1.1
2. PHP 5.6.27

### Steps to reproduce

1. Edit a Configurable Product
2. Insert image using the WYSIWYG in Content - Description 
3. Save the product

### Expected result

1. See image in my frontend Product Page

### Actual result

1. The image is visible for some time...maybe since another operation
2.![f](https://cloud.githubusercontent.com/assets/23255766/19999421/94adca8c-a272-11e6-9cec-696d4920df88.PNG)

**Comment by quienti** [comment]
Duplicate and already fixed https://github.com/magento/magento2/issues/6138

**Comment by veloraven** [comment]
@ferrarinim thank you for your report.
We already have internal ticket for fixing this issue in ver. 2.1 - MAGETWO-59690

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435

**Comment by magento-engcom-team** [comment]
@ferrarinim the issue has been fixed in 2.1.8
