### ISSUE TITLE
Magento\Eav\Model\Entity\Attribute\Exception: No such entity with cartId

### ISSUE THREAD

**Issue by HellgaM** [magento/magento2#7308]
### Preconditions

Magento version is 2.1.0
PHP 7
MySql 5.6
Admin session lifetime 15 min
Customer session lifetime 30 days
"checkout/cart/delete_quote_after" value is 30

### Steps to reproduce

1. Add products to a shopping cart, no matter logged in user on not.
2. Make sure you have cron setup and clean quotes job run  (possibly this is an issue condition)
3. Wait until cron jobs run at 0:00

### Expected result

1. Frontend should look as usual.

### Actual result

1.  All products at frontend are 404
2.  Categories are empty, no products are shown
3.  Error message shown on the first cart item
https://drive.google.com/a/interiorwebdesign.com/file/d/0ByJDgAmB3zgANHN4R3F6MlVqU28/view?usp=drivesdk
4. Exception  "No such entity with cartId = 26405"  thrown on each catalog page visit.
5. Exceptions is for "quantity_and_stock_status" attribute
6. Please see error trace below.

During database check, it appeared that there is no quote with id 26405 and no any related value.
The only place where "26405" was found is session file, with proper quote id for frontend,
and value for admin: **adminhtml_quote|a:2:{s:8:"store_id";s:1:"1";s:8:"quote_id";s:5:"26405";}**

It looks buggy when the user is not logged in to admin panel, but validation 
$this->walkAttributes('backend/validate' runs using "adminhtml_quote" which doesn't exist,
at least such an issue should not affect on frontend when all products are 404.

The same issue repeates for guest users which weren't logged in to admin panel before, 
quote id is stored in session but this quote not exist anymore.

Error trace
 main.CRITICAL: Magento\Eav\Model\Entity\Attribute\Exception: No such entity with cartId = 26405 in  public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0  public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Eav\\Mod...', Array)
#1  public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Eav\\Mod...', Array)
#2  public_html/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Eav\\Mod...', Array)
#3  public_html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(655): Magento\Framework\Validator\UniversalFactory->create('Magento\\Eav\\Mod...', Array)
#4  public_html/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(505): Magento\Eav\Model\Entity\AbstractEntity->walkAttributes('backend/afterLo...', Array, NULL)
#5  public_html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1762): Magento\Catalog\Model\ResourceModel\Product\Interceptor->walkAttributes('backend/afterLo...', Array)
#6  public_html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1882): Magento\Eav\Model\Entity\AbstractEntity->_afterLoad(Object(Magento\Catalog\Model\Product\Interceptor))
#7  public_html/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(687): Magento\Eav\Model\Entity\AbstractEntity->afterLoad(Object(Magento\Catalog\Model\Product\Interceptor))
#8  public_html/vendor/magento/framework/EntityManager/Observer/AfterEntityLoad.php(33): Magento\Catalog\Model\ResourceModel\Product\Interceptor->afterLoad(Object(Magento\Catalog\Model\Product\Interceptor))
#9  public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\Framework\EntityManager\Observer\AfterEntityLoad->execute(Object(Magento\Framework\Event\Observer))
#10  public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntityLoad), Object(Magento\Framework\Event\Observer))
#11  public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#12  public_html/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#13  public_html/vendor/magento/framework/EntityManager/EventManager.php(51): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#14  public_html/vendor/magento/framework/EntityManager/Operation/Read.php(124): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'load_after', Array)
#15  public_html/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Product\Interceptor), 279, Array)
#16  public_html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(655): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Product\Interceptor), 279)
#17  public_html/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(258): Magento\Catalog\Model\ResourceModel\Product->load(Object(Magento\Catalog\Model\Product\Interceptor), 279, NULL)
#18  public_html/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Product\Interceptor->load(Object(Magento\Catalog\Model\Product\Interceptor), 279, NULL)
#19  public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->load(279)
#20  public_html/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2301): Magento\Catalog\Model\Product\Interceptor->___callPlugins('load', Array, Array)
#21  public_html/vendor/magento/module-catalog/Model/ProductRepository.php(241): Magento\Catalog\Model\Product\Interceptor->load(279)
#22  public_html/var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(37): Magento\Catalog\Model\ProductRepository->getById(279, false, '1', false)
#23  public_html/var/generation/Magento/Catalog/Api/ProductRepositoryInterface/Proxy.php(111): Magento\Catalog\Model\ProductRepository\Interceptor->getById(279, false, '1', false)
#24  public_html/vendor/magento/module-catalog/Helper/Product.php(417): Magento\Catalog\Api\ProductRepositoryInterface\Proxy->getById(279, false, '1')
#25  public_html/vendor/magento/module-catalog/Helper/Product/View.php(212): Magento\Catalog\Helper\Product->initProduct(279, Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Magento\Framework\DataObject))
#26  public_html/vendor/magento/module-catalog/Controller/Product/View.php(109): Magento\Catalog\Helper\Product\View->prepareAndRender(Object(Magento\Framework\View\Result\Page\Interceptor), 279, Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Magento\Framework\DataObject))
#27  public_html/var/generation/Magento/Catalog/Controller/Product/View/Interceptor.php(24): Magento\Catalog\Controller\Product\View->execute()
#28  public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Product\View\Interceptor->execute()
#29  public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#30  public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Product\View\Interceptor->___callParent('dispatch', Array)
#31  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'contextPlugin')
#32  public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'customer-app-ac...')
#35  public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'storeCheck')
#38  public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#39  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'weee-app-action...')
#41  public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'tax-app-action-...')
#44  public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Catalog\Controller\Product\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45  public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46  public_html/var/generation/Magento/Catalog/Controller/Product/View/Interceptor.php(39): Magento\Catalog\Controller\Product\View\Interceptor->___callPlugins('dispatch', Array, Array)
#47  public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Product\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48  public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#49  public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#50  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#51  public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#52  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#53  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#54  public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#55  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#56  public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#57  public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#58  public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#60  public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#61  public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62  public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#63  public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#64  public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#65  public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

Let us know if you need any further information and thank you for your time.

**Comment by HellgaM** [comment]
Hello, 
the issue "main.CRITICAL: Magento\Eav\Model\Entity\Attribute\Exception: No such entity with cartId = XXX" has been fixed by adding one more condition to vendor/magento/module-sales/Cron/CleanExpiredQuotes.php, line 60

`$quotes->addFieldToFilter('created_at', ['to' => date("Y-m-d", time() - $lifetime)]);`

because previously some new quotes were removed by clean expired quotes cron job.

Thanks

**Comment by paales** [comment]
@HellgaM Which condition did you add? the above seems to already exist?

**Comment by HellgaM** [comment]
@paales I have Magento 2.1.0
there is filter by "updated_at" but not by "created_at" values.

**Comment by paales** [comment]
@HellgaM Hmm, `created_at <= updated_at` right, so not sure what your change would resolve?

**Comment by HellgaM** [comment]
In my case, there are a lot of quotes with correct "created_at" data and "0000-00-00 00:00:00" value of "updated _at", so they were removed by cron even if creating time is yesterday.

**Comment by paales** [comment]
@HellgaM Ahh, I see, that seems to be happening in our database as well! Thanks for the explanation.

**Comment by magento-engcom-team** [comment]
@HellgaM, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
