### ISSUE TITLE
Wrong object passed to collectRates method in collectRatesByAddress method in Shipping model

### ISSUE THREAD

**Issue by pierzakp** [magento/magento2#7309]
### Preconditions

1. Magento CE 2.1.1.

### Steps to reproduce

1. In your custom code call method collectRatesByAddress which is implemented in \Magento\Shipping\Model\Shipping.

### Expected result

1. Expected behavior is to not have fatal error for sure. Be able to get result of collect rates.

### Actual result

1. Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Shipping\Model\Shipping::collectRates() must be an instance of Magento\Quote\Model\Quote\Address\RateRequest, instance of Magento\Shipping\Model\Shipment\Request given
2. In collectRatesByAddress method at the beginning comment which is placed there suggests that factory will create \Magento\Quote\Model\Quote\Address\RateRequest object, which is correct because collectRates method expects this type, but \Magento\Shipping\Model\Shipment\Request is created instead.

**Comment by YevSent** [comment]
Hi @pierzakp, thanks for reporting.
The internal ticket is created (MAGETWO-62662).

**Comment by alena-marchenko** [comment]
Hi @pierzakp 

Fix for MAGETWO-62662 is merged to develop branch, closing the issue.
Thank you.

**Comment by Ctucker9233** [comment]
@alena-marchenko Which version of Magento will have MAGETWO-62662 included?

**Comment by rmilea** [comment]
@alena-marchenko  Can you please let us know the Magento version that will contain the fix for MAGETO-62662.

I'm using version 2.1.7 and is not fixed yet.

**Comment by YevSent** [comment]
@rmilea this issue fixed in 2.2.0 release.

**Comment by rmilea** [comment]
@joni-jones Is there a patch available for 2.1.7 ?

**Comment by YevSent** [comment]
No, the fix didn't backport to 2.1.x.

**Comment by Ctucker9233** [comment]
@joni-jones Will it be backported or does it break BC?
