### ISSUE TITLE
Order Collection Rest API call error for Payflow Pro (Includes Express Checkout)

### ISSUE THREAD

**Issue by mageprakash** [magento/magento2#7312]
Hello Magento team,

I have used rest API to get orders collection. During the implementation, I got an error for order which was placed by Pay Flow Pro (Includes Express Checkout) payment method.

Error :  Message: Notice: Array to string conversion

I have described flow of code for rest API call along with an error.

After debugging a while, I found that pay flow module has saved some information in "additional_information" column in database table "sales_order_payment".

Error was occurred because of multidimensional array passes in "additional_information" field and this value checked in TypeCaster.php while API call.

The solution for the above listed problem is that you need to exclude array and object checking from TypeCaster.php (magento/framework/Reflection/TypeCaster.php)

Column Name : "additional_information" 
Table Name : "sales_order_payment"

stored value : "a:5:{s:14:"token_metadata";a:2:{s:11:"customer_id";i:21;s:11:"public_hash";s:64:"2eaf19919a16bb18f7c31838637c31151edbd8bd8ace0edbdd935c498341b99b";}s:12:"method_title";s:26:"Stored Cards (Payflow Pro)";s:7:"avsaddr";s:1:"Y";s:6:"avszip";s:1:"Y";s:4:"iavs";s:1:"N";}"

Array Form :

array (
  'token_metadata' => 
  array (
    'customer_id' => 21,
    'public_hash' => '2eaf19919a16bb18f7c31838637c31151edbd8bd8ace0edbdd935c498341b99b',
  ),
  'method_title' => 'Stored Cards (Payflow Pro)',
  'avsaddr' => 'Y',
  'avszip' => 'Y',
  'iavs' => 'N',
)

The code in "Typecaster.php"  file is considering token_metadata as string that causes an error. You need use some strict rules to exclude array from code in Typecaster.php

Example of API Call :

$requestUrl='http://test.com/index.php/rest/V1/orders/174';

$ch = curl_init();
$ch = curl_init($requestUrl); 
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);   
$result = curl_exec($ch);

Error:

Next Exception: Report ID: webapi-581c58a69ee20; Message: Notice: Array to string conversion in /var/www/www.mayvillagetrading.com/vendor/magento/framework/Reflection/TypeCaster.php on line 34 in /var/www/www.mayvillagetrading.com/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/www.mayvillagetrading.com/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/www.mayvillagetrading.com/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/www.mayvillagetrading.com/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/www.mayvillagetrading.com/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/www.mayvillagetrading.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/www.mayvillagetrading.com/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by YevSent** [comment]
Hi, @prakash282, thanks for reporting. This is known issue (ticket MAGETWO-57426) and already fixed on the develop branch. For 2.1.x versions fix will be available in Magento 2.1.3.

Closed as duplicate to https://github.com/magento/magento2/issues/6215 .

**Comment by gabriel-sf** [comment]
@joni-jones can you provide the link on where the fix for this issue is located? I cant seem to find this

**Comment by YevSent** [comment]
@gabriel-sf, the `token metadata` was reworked and doesn't use anymore.

The fix affects few classes in the [Vault](https://github.com/magento/magento2/tree/develop/app/code/Magento/Vault) module. The main changes were done in `\Magento\Vault\Observer\PaymentTokenAssigner` and `\Magento\Vault\Model\Method\Vault`.

**Comment by gabriel-sf** [comment]
@joni-jones so how do I update this files? Do I just update them directly in the vendor folder?

I just tried doing that and I still get the same error when connecting through the REST API

**Comment by YevSent** [comment]
You shouldn't change files in the vendor directory. You can use develop branch or wait for 2.1.3, because changes also require some migration for old orders.

**Comment by gabriel-sf** [comment]
@joni-jones Do you know when this is fix is going to be released? You mentioned 2.1.3, but do you have any release date or estimate for this version to be available?
