### ISSUE TITLE
Product Attributes On Product Page Are Displayed In Wrong Order When Uploaded via CSV File

### ISSUE THREAD

**Issue by scottishracer** [magento/magento2#7314]
I need to reorder how attributes are displayed on a product page for a configurable product. This issue was previously closed with the assumption it was fixed in 2.1.1 which is not the case. 

1. I created additional attributes and added those to an attribute set based on Default in the order they should be displayed.

![image](https://cloud.githubusercontent.com/assets/1956910/20006537/58ab94aa-a26e-11e6-8f2e-12aeb69caaea.png)

2. The csv file has the attribute listed in the the order I wish them to be displayed on the frontend in the additional_attributes column and configurable_variations column.

![image](https://cloud.githubusercontent.com/assets/1956910/20006617/beb155aa-a26e-11e6-98f8-f6adcbf8c55d.png)

3. Reviewing the configurable product in admin the attributes appear to be in the correct order
![image](https://cloud.githubusercontent.com/assets/1956910/20006872/f697af90-a26f-11e6-93b8-c7867a4648d1.png)

4. When viewing the product page on the frontend the attributes are new ordered incorrectly

![image](https://cloud.githubusercontent.com/assets/1956910/20007573/46ae996e-a273-11e6-8587-4fb108bc8c79.png)

## **It appears the order of attributes can only be reordered by creating new simple products via the admin interface.**

5. Open configurable product and select Edit Configurations and here you'll see how magento has reordered the attribute.

![image](https://cloud.githubusercontent.com/assets/1956910/20007768/2afed214-a274-11e6-9593-b8d7725c4882.png)

6. So now the only way I have found to correct the order to what I need is to unselect the checkboxes and reselect them in the preferred order.

![image](https://cloud.githubusercontent.com/assets/1956910/20007787/437ae6ac-a274-11e6-9c14-e870cf7aa672.png)

7. In the next step you'll see the attributes are in the correct order.

![image](https://cloud.githubusercontent.com/assets/1956910/20007150/5c42e412-a271-11e6-9f22-6b3a48713d35.png)

8. Moving through step 3 I skipped all the attribute values as these redundant products will be deleted after moving through step 4.

9. Here's a small sample of the product created which I now have to delete.

![image](https://cloud.githubusercontent.com/assets/1956910/20007330/1a0c18c4-a272-11e6-94bd-c6e85c9367f6.png)

10. After the configurable product is saved and refreshing the frontend  the attribute order is correct.

![image](https://cloud.githubusercontent.com/assets/1956910/20007427/9022a42e-a272-11e6-9130-5cb5dd8f2467.png)

So to conclude when a product csv file is imported the order of the attributes in additional_attributes and configurable_variations columns should be honored.

Until this is resolved I cannot consider migrating our store from magento 1.9 to 2.x. Especially when I have over 3000 products to import with many of them requiring the use of a configurable product.

**Comment by dthampy** [comment]
internal jira ticket to track this issue : MAGETWO-60709

**Comment by emmo1210** [comment]
Hello,
Having the exact problem. Have tried many different CSV tweaks without joy. Has there been any progress with this or useful workaround that doesn't involve having to go and edit every product manually to correct the imported order? Imported order should indeed match either that of the CSV or more intuitively the attribute set order - which alas it doesn't.

**Comment by nobuttsalex** [comment]
After digging around the core files (2.1.7) I found a fix. The position field is not being set (it's always 0) so I added a counter in.

adminhtml/di.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\ConfigurableImportExport\Model\Import\Product\Type\Configurable" type="My\Module\Model\Import\Product\Type\Configurable" />
</config>
```

Model/Import/Product/Type/Configurable.php
```
<?php

namespace My\Module\Model\Import\Product\Type;

class Configurable extends \Magento\ConfigurableImportExport\Model\Import\Product\Type\Configurable
{
    protected function _insertData()
    {
        $mainTable = $this->_resource->getTableName('catalog_product_super_attribute');
        $labelTable = $this->_resource->getTableName('catalog_product_super_attribute_label');
        $linkTable = $this->_resource->getTableName('catalog_product_super_link');
        $relationTable = $this->_resource->getTableName('catalog_product_relation');

        $mainData = [];
        foreach ($this->_superAttributesData['attributes'] as $productId => $attributesData) {
            $i = 0;
            foreach ($attributesData as $attrId => $row) {
                $row['product_id'] = $productId;
                $row['attribute_id'] = $attrId;
                $row['position'] = $i;
                $mainData[] = $row;
                $i++;
            }
        }
        if ($mainData) {
            $this->_connection->insertOnDuplicate($mainTable, $mainData);
        }
        if ($this->_superAttributesData['labels']) {
            $this->_connection->insertOnDuplicate($labelTable, $this->_superAttributesData['labels']);
        }
        if ($this->_superAttributesData['super_link']) {
            $this->_connection->insertOnDuplicate($linkTable, $this->_superAttributesData['super_link']);
        }
        if ($this->_superAttributesData['relation']) {
            $this->_connection->insertOnDuplicate($relationTable, $this->_superAttributesData['relation']);
        }
        return $this;
    }
}
```

**Comment by emmo1210** [comment]
Nobuttsalex it works a charm, thanks for this, will make life easier. Would you expect this change to remain after an update?
Thanks again
em

**Comment by Ctucker9233** [comment]
@nobuttsalex This is great! Care to create a pull request against 2.1-develop so this fix might get into 2.1 faster?

**Comment by magento-engcom-team** [comment]
@scottishracer, thank you for your report.
We've created internal ticket(s) MAGETWO-60709 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
