### ISSUE TITLE
Order Comments  not display in front-end

### ISSUE THREAD

**Issue by johnlos** [magento/magento2#7315]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1.  we use  www.customerparadigm.com/magento-2-order-comments-extension-for-checkout/
plugin to enable order comments both front-end and back-end. 
2. Front -end not showing 

### Actual result

1. admin screen: http://awesomescreenshot.com/03766aiccf
2. Front-end: http://awesomescreenshot.com/09166aioe3

**Comment by quienti** [comment]
This is a custom module, not a Magento bug, please contact Customer Paradigm

**Comment by rganin** [comment]
This is not a Magento native module, please contact the module vendor for help.
