### ISSUE TITLE
Facing InvalidArgumentException after creating an customer address attribute

### ISSUE THREAD

**Issue by johnlos** [magento/magento2#7316]
### Preconditions

1. Magento 2.0.7, Zend engine 2.6
2.  PHP 5.6.23

### Steps to reproduce

1. Create an customer address attribute. 
2. After creating add those attributes in frontend
3. Add product to cart
4. Go to checkout
5. Fill shipping address with created attribute
6. Click place order button

### Expected Result
1. Order should be placed

### What happens
Its show error, and stops at the checkout page

Inspecting the error, it was found

[2016-11-04 12:20:25] main.CRITICAL: exception '**InvalidArgumentException**' with message 'Report ID: webapi-581c7d0932698; Message: Each getter must have description with @return annotation. See Magento\Quote\Api\Data\AddressInterface::getSecondaryNumber()' in /opt/lampp/htdocs/sherwaycommerce/latestinstance/vendor/magento/framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /opt/lampp/htdocs/sherwaycommerce/latestinstance/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(InvalidArgumentException))
#1 /opt/lampp/htdocs/sherwaycommerce/latestinstance/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(InvalidArgumentException))
#2 /opt/lampp/htdocs/sherwaycommerce/latestinstance/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /opt/lampp/htdocs/sherwaycommerce/latestinstance/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /opt/lampp/htdocs/sherwaycommerce/latestinstance/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /opt/lampp/htdocs/sherwaycommerce/latestinstance/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by rganin** [comment]
Did you create new attribute by implementing new class with AddressInterface?

**Comment by kumaratratus** [comment]
I have created a customer address attribute with the below code in InstallData.php in a custom module. The attribute is getting displayed in backend, but not getting updated when input is given. Also its not getting displayed in frontend too. Can you please help me in creating a custom attribute for customer address.

```
      $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);

       $attributesInfo = [
                    'secondary_number' => [
                    'label' => 'Secondary number',
                    'type' => 'static',
                    'input' => 'text',
                    'position' => 140,
                    'visible' => true,
                    'required' => false,
                    ]];


            $eavSetup->addAttribute(
                    'customer_address',
                    'secondary_number',
                    [
                    'label' => 'Secondary number',
                    'type' => 'static',
                    'input' => 'text',
                    'position' => 140,
                    'visible' => true,
                    'required' => false,

                    ]
            );
            $sampleAttribute = $this->eavConfig->getAttribute('customer_address', 'secondary_number');
            $sampleAttribute->setData(
                    'used_in_forms',
                    ['adminhtml_customer_address', 'customer_address_edit', 'customer_register_address']

            );
            $sampleAttribute->save();
```

**Comment by veloraven** [comment]
@johnlos thank you for your feedback.
Customer custom address attributes are available in Enterprise edition only.
If you use this one, please contact Magento support instead of posting your issue here.
If you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE amd we can not treat it as an issue
