### ISSUE TITLE
BLOB data type breaks display of UI Grid Component

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7318]
### Preconditions

1. Magento 2.1.1
2. PHP 5.6
3. MySQL Ver 14.14 Distrib 5.7.16, for Linux (x86_64)

### Steps to reproduce

1. Vanilla install with example data set loaded
2. Custom module registered, and setup with custom interfaces, models, resources, routes etc
3. Following table schema used for a custom request object:

```
+---------------+---------------------+------+-----+-------------------+----------------+
| Field         | Type                | Null | Key | Default           | Extra          |
+---------------+---------------------+------+-----+-------------------+----------------+
| request_id    | int(10) unsigned    | NO   | PRI | NULL              | auto_increment |
| message_id    | bigint(20) unsigned | NO   |     | NULL              |                |
| type          | varchar(150)        | NO   |     | NULL              |                |
| operation     | varchar(150)        | NO   |     | NULL              |                |
| reference     | varchar(150)        | NO   |     | NULL              |                |
| request_body  | blob                | NO   |     | NULL              |                |
| response_body | blob                | YES  |     | NULL              |                |
| created_at    | timestamp           | NO   |     | CURRENT_TIMESTAMP |                |
| processed_at  | timestamp           | YES  |     | NULL              |                |
+---------------+---------------------+------+-----+-------------------+----------------
```

3. Admin grid created with the custom request object as the data source configured via XML UI component definition:

### Expected result

1. Added test data to the above table including gzipped XML data within the BLOB columns via gzdeflate
2. Navigating to the admin grid should display the grid with correct data (the BLOB columns are not configured to be displayed via the column definitions of the ui component)

### Actual result

1. Loading of the grid hangs with the following console error reported:
```VM8725:1 Uncaught SyntaxError: Unexpected token } in JSON at position 33```

![broken](https://cloud.githubusercontent.com/assets/349396/20012780/85da84c4-a2a8-11e6-9fa0-30c8fa120eea.png)

### Resolution
1. Currently the only resolution is to remove the content of the BLOB fields from the DB table

![expected](https://cloud.githubusercontent.com/assets/349396/20012731/5544e75a-a2a8-11e6-90b9-c1227d25b885.png)

This is obviously a JSON formatting issue due to the contents of the BLOB fields. However, is this expected behaviour, and is there a method for excluding the retrieval of certain columns from the grid UI component data source? Forgive my ignorance if this is the case.

**Comment by vkorotun** [comment]
Thank you for reporting this issue. Internal ticket: MAGETWO-61313

**Comment by magento-engcom-team** [comment]
Hi @thomb2233 
Thanks for reporting this issue. 
Please share `.xml` file from `view/adminhtml/ui_component`, where you use listing component and all depending `.php` files.

**Comment by magento-engcom-team** [comment]
@thomb2233, thank you for your report.
We've created internal ticket(s) MAGETWO-61313 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@thomb2233, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
