### ISSUE TITLE
Infinite load when I try to create product configurations

### ISSUE THREAD

**Issue by ferrarinim** [magento/magento2#7323]
### Preconditions

1. Magento 2.1.1
2. PHP 5.6.27

### Steps to reproduce

1. Add new Product to Catalog
2. Compile all fields before the section Configurations (like name, sku, description, ...)
3. Go to Configurations

### Expected result

1. I expect that the Tab with attributes opens and I can choose between my attributes in order to create my configurations.

### Actual result

1. Infinite loop, I have to close the tab, click again on New Product and fill again all fields that I've inserted before.
![cattura](https://cloud.githubusercontent.com/assets/23255766/20022520/412acc70-a2db-11e6-9466-a16d52f9bcb9.PNG)

**Comment by veloraven** [comment]
@ferrarinim thank you for your report.
Was it clear install or upgrade from some previous version?
Could you please describe your environment: versions of MySQL, web server used and OS?
Do I understand correct that this issue happens from time to time only and you can create configuration on the second try? If it is can you provide more specific steps when it happens and when it does not.
Also as I can see you use some localization, please specify what exact localization you use.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
