### ISSUE TITLE
possible improvement - Go to last/first page

### ISSUE THREAD

**Issue by ferrarinim** [magento/magento2#7324]
### Preconditions

1. Magento 2.1.1
2. PHP 5.6.27

### Steps to reproduce

1. Go to Products - Catalog

### Expected result

1. It would be nice if there were two buttons in addition to the 2 already existing: one to go to the first page of the pagination of the datatable, and one to go to the last page.

### Actual result

1. nothing

**Comment by veloraven** [comment]
@ferrarinim thank you for your feedback.
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
