### ISSUE TITLE
Missing AdditionalInformation setter in vendor/magento/module-sales/Api/Data/OrderPaymentInterface.php

### ISSUE THREAD

**Issue by matmarchant** [magento/magento2#7331]
**Our use case for this problem is the EE message queues, but the problem also extends to CE**

There is a problem with the OrderPaymentInterface, which has no function for setAdditionalInformation.

The exception thrown is:
Property "AdditionalInformation" does not have corresponding setter in class "Magento\Sales\Api\Data\OrderPaymentInterface"

### Preconditions
1. Magento ver. 2.0.8
2. PHP 7.0.12 (cli) (built: Oct 15 2016 19:03:00)
3. nginx version: nginx/1.9.15
4. mysql server version: 5.6.32-78.1-56-log Percona XtraDB Cluster

### Steps to reproduce
1. Create message queue with Magento\Sales\Api\Data\OrderInterface as the topic
2. Create consumer using OrderInterface as the Payload
3. Exception is thrown when the consumer attempts to decode the messages

### Expected result
1. Consumer should use the OrderInterface object

### Actual result
1. Property "AdditionalInformation" does not have corresponding setter in class "Magento\Sales\Api\Data\OrderPaymentInterface"

**Comment by veloraven** [comment]
@maximinimus thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
Please let me know if you already have reported the issue this way.

**Comment by matmarchant** [comment]
@veloraven 
As I said, my use case is for an EE feature but the problem also exists in CE.

**Comment by veloraven** [comment]
@maximinimus could you then let me know if you have reported this issue to Support? Just to avoid duplicates and double work.
