### ISSUE TITLE
ChromeOS (Chromebook) format problem

### ISSUE THREAD

**Issue by JimDantin** [magento/magento2#7332]
When accessing the Magento 2 Dashboard using a Chromebook, some forms/fields are sized improperly.

Magento version 2.1.2
1. Sign in to Dashboard using a Chromebook
2. Navigate to System...Import (or Export or possibly other areas)
3. Observe that selector boxes (Entity type in screenshot below) are small and pushed to the right edge of the screen

### Expected result
1. Forms should look the same as with Chrome on a Windows PC

### Actual result
1. screenshot --

![screenshot 2016-11-06 at 9 09 51 am](https://cloud.githubusercontent.com/assets/5129185/20038415/2196fcb8-a401-11e6-8b23-92e420b3ba7c.png)

**Comment by sevos1984** [comment]
This is not a bug, as you see chromium is not supported browser http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html

**Comment by JimDantin** [comment]
It says under Supported Browsers:

**"Chrome latest, latest–1 (any operating system)"**

In what possible way does that say that ChromeOS/Chromium is not supported?

**Comment by jfern01** [comment]
I'm with @JimDantin, how does Magento 2 support Chrome but not Chromium? That doesn't make any sense. I found another issue reporting the same problem, only on Chrome/Chromium: #7716

**Comment by jfern01** [comment]
After digging a bit more, it looks like this is a bug in Chromium: #7155

**Comment by JimDantin** [comment]
I just posted a comment on the Chromium bug tracker. The **only** place where I see the problem, however, is the Magento Dashboard.
