### ISSUE TITLE
Unable to set negative custom option fixed price in admin view.

### ISSUE THREAD

**Issue by WaterSlide** [magento/magento2#7333]
In versions 2.1.1 and 2.1.2, setting custom options for a product with fix price settings will not allow a negative value. I'm not sure if this is a simple ui problem or if there is a validator issue. Either way, this was always an option in Magento 1.x in which you can set discounts on an item via custom option. Uploading values via CSV works correctly, however making admin view changes for given product will fail validation via negative values.

### Preconditions

1. Magento 2.1.2
2. PHP 7

### Steps to reproduce

1. Freshly install Magento.
2. Create product with a custom option.
3. Attempt to place a negative value in the custom option price input.

### Expected result

1. Item validates and clients using the custom option allows a price reduction.

### Actual result

1. Cannot save item. Validator fails.

![capture](https://cloud.githubusercontent.com/assets/9472763/20040481/934a3ee0-a426-11e6-8f6c-45a999be81fe.PNG)

**Comment by rganin** [comment]
Thank you for reporting. Internal issue created: MAGETWO-60573

**Comment by SahakTadevosyan** [comment]
Hi @WaterSlide  did you fix this issue?
I have the same issue in Magento 2.1.3

**Comment by WaterSlide** [comment]
I have not tried as of yet. I have had people offer me beer if I did.

I'm waiting for this to be fixed before I launch a new store. I will be
looking at it this weekend, but I have to admit, I'm not terribly familiar
with Magento's framework.

**Comment by WaterSlide** [comment]
I am aware that editing the Magento core is a no-no, however I am pressed for time and needed a very quick fix. I'll be learning how to override things the proper way any day now.... 

A nice gentleman was kind enough to email me what he found:

> vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/CustomOptions.php
>  
> Set false for validate-zero-or-greater
>  
> vendor/magento/module-catalog/Model/Product/Option/Validator/DefaultValidator.php
>  
> protected function isNegative($value)
>     {
>         //return intval($value) > 0;
>         return false;
>     }

The code speaks for itself. The isNegative will always return false. I am not sure what other implications there are for doing it this way, however I have tested that a negative value will still offset the price as intended.

**Comment by EmilyPepperman** [comment]
I have this issue as well! Needs to be solved in core Magento... thank you WaterSlide for the solution for now. :-)

**Comment by iamjonjackson** [comment]
I need this also

**Comment by miro91** [comment]
@WaterSlide I tried your solution but it still give me "Invalid option value" error when I try to set negative price to some custom option.

**Comment by zaaaidi** [comment]
@WaterSlide  Thanks alot. Its really works for me.

**Comment by robgt** [comment]
Any news on a fix for this issue?

**Comment by tejashp77** [comment]
Any news on a fix for this issue?

**Comment by ic3b0x** [comment]
Thanks @WaterSlide for the quick fix! Having one last cosmetic issue, the frontend still shows a + sign before the -. Anyone knows how to remove it?

<img width="252" alt="screen shot 2017-09-21 at 7 00 23 pm" src="https://user-images.githubusercontent.com/15994522/30720764-3aa55ad4-9eff-11e7-84c4-0bf2837603b7.png">

**Comment by magento-engcom-team** [comment]
@WaterSlide, thank you for your report.
We've created internal ticket(s) MAGETWO-60573 to track progress on the issue.

**Comment by seanscott49** [comment]
Thanks for the fix. It works on Radio, but Drop Down adds a +- in front of the number. I really hope this gets fixed soon. I have 2 sites to migrate after the holidays that depend on it.

**Comment by heidiboh** [comment]
I'm running M 2.2.1. This remains an issue. We need to be able to set a negative value for price in the product's "customizable options" section. What is the progress on MAGETWO-60573?... or should I use this solution below?

> vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/CustomOptions.php
> 
> Set false for validate-zero-or-greater
> 
> vendor/magento/module-catalog/Model/Product/Option/Validator/DefaultValidator.php
> 
> protected function isNegative($value)
> {
> //return intval($value) > 0;
> return false;
> }

**Comment by luckyduck** [comment]
I've created a pull request for this issue, for future releases. In case you run into this, here is a fix for 2.1.x (tested on 2.1.9):

https://github.com/luckyduck/negative-option-value

It also solves the cosmetic frontend issue, where negative option values have a plus sign as prefix (like +-3,50)

**Comment by mattryding** [comment]
I tried to use Luckyduck's module on Magento 2.2.5 but this caused a problem in the Admin backend where under Customisable Options there would be no boxes to enter $ values.

To fix this, I edited: 
Ui\DataProvider\Product\Form\Modifier\CustomOptions.php

Modify from line 25 onwards:

```
class CustomOptions extends Options
{
    protected function getPriceFieldConfig($sortOrder)
    {
        return [
            'arguments' => [
                'data' => [
                    'config' => [
                        'label' => __('Price'),
                        'componentType' => Field::NAME,
                        'component' => 'Magento_Catalog/js/components/custom-options-component',
                        'formElement' => Input::NAME,
                        'dataScope' => static::FIELD_PRICE_NAME,
                        'dataType' => Number::NAME,
                        'addbefore' => $this->getCurrencySymbol(),
                        'addbeforePool' => $this->productOptionsPrice->prefixesToOptionArray(),
                        'sortOrder' => $sortOrder,
                        'validation' => [
                            'validate-zero-or-greater' => false
                        ],
                    ],
                ],
            ],
        ];
    }
}
```

**Comment by magento-engcom-team** [comment]
Hi @WaterSlide 

This issue is now fixed and it's expected to be delivered with the upcoming 2.2.6 release. Meanwhile, you may use this commit as a reference 8d4124cc4125e81d4a41ae71aca12c8e12f297a6

Thanks
