### ISSUE TITLE
encrypt /decrypt ccsave module (cc)

### ISSUE THREAD

**Issue by jbpilatre** [magento/magento2#7334]
I created a Credit Card payment module (Save) which works very well.
The encryption feature seems to work correctly.... (but no !)

`$info->encrypt($data->getDataByPath('additional_data/cc_number'))`

but decrypt function always returns an empty field
in Magento\payment\Model\info.php line 76

`public function getData($key = '', $index = null)
{
    if ('cc_number' === $key) {
        if (empty($this->_data['cc_number']) && !empty($this->_data['cc_number_enc'])) {
            $this->_data['cc_number'] = $this->decrypt($this->getCcNumberEnc());
        }
    }
    if ('cc_cid' === $key) {
        if (empty($this->_data['cc_cid']) && !empty($this->_data['cc_cid_enc'])) {
            $this->_data['cc_cid'] = $this->decrypt($this->getCcCidEnc());
        }
    }
    return parent::getData($key, $index);
}`
idem in i use 
`$info->decrypt($info->getCcNumberEnc());`
return nothing.

It's a Magento Bug !

in **quote_payment table**

cc_number_enc => datatype VARCHAR(255)
cc_ss_issue => datatype VARCHAR(255) ...

and in **sales_order_payment table**

cc_number_enc => datatype VARCHAR(32)
cc_ss_issue => datatype VARCHAR(32)

**if you change VARCHAR(255) in sales_order_payment, this fix the problem** 

### Preconditions
Magento 2.0.10
PHP 5.6.27

**Comment by rganin** [comment]
Thanks for reporting. Internal ticket created MAGETWO-60587.

**Comment by alena-marchenko** [comment]
Hi @jbpilatre 

Fix for MAGETWO-60587 is merged to develop branch, closing the issue.
Thank you.

**Comment by Ctucker9233** [comment]
@alena-marchenko What version of Magento will have MAGETWO-60587 included?

**Comment by orlangur** [comment]
@Ctucker9233 the answer is "next major release" unless otherwise specified. For https://github.com/magento/magento2/commit/6593dceda041c4829633f38b2b35a782dcdbfe9d it's 2.2.

**Comment by Ctucker9233** [comment]
@orlangur Right. I'm aware of that part. Was just wondering it there was a plan for backport since it was an issue reported against 2.1.x. Guess I'll have to wait and see.
