### ISSUE TITLE
Print order / invoice shows blank preview and blank pdf in my account order detail page

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento/magento2#7335]
While click the print order / print invoice button in my-account order detail page it shows blank in print preview also the downloaded pdf also shows blank.

### Preconditions

1. My Magento version  is 2.1.1
2. Php Version is 7.0.8

### Steps to reproduce

1. Create an account in magento.
2. Place an order with any kind of product and any kind of payment gateway.
3.Go to order detail page in my account section
4.Click on print order button 
5.It will open a page in new tab with print preview option ( in chrome browser )
6.In print preview it shows blank
7.Also after download the pdf of order , this pdf will not open.

### Expected result

1. It Should show all the contents in print preview like billlin,shipping address, payment methods, order item details.
2.Also the pdf also open properly after download it.

### Actual result

1. It will not show any contents in print preview
2.The pdf also not open after downloading it
Screen-shot : 
http://prnt.sc/d5trgn

**Comment by veloraven** [comment]
@ewallkrishnaprakash thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by mackieee** [comment]
This happens to me on Chrome 76 on the Print Preview, but only sometimes.

Upon pressing "Print Order" it takes the browser to `/sales/order/print/order_id/[id]/` and invokes print screen automatically via Javascript I assume. In Chrome that renders the preview page. 

![image](https://user-images.githubusercontent.com/883702/63441573-8b394400-c429-11e9-9ba4-009a2de5bc0b.png)

For some reason, sometimes. This renders completely blank apart from the outer lines (_See Above_). You press "Cancel" and press Print again - This time it renders with the lines and information fully.

![image](https://user-images.githubusercontent.com/883702/63442289-c12af800-c42a-11e9-9ce3-ec0c80a16f74.png)

Almost as if Chrome has rendered the Print from the undrawn Table. Subsequently this renders perfectly fine on the second attempt (_When pressing print on the `/sales/order/print/order_id/*`_) page. Other tests render fine. May be linked a slow site :')

On Magento 2.3.1

**Comment by PedroTiagoSimao** [comment]
Digging up old stuff... 

I have this happening now. Does it relate to server issues like @MackieeE pointed? Slow server?
