### ISSUE TITLE
Shipping Options Not Updating After Change

### ISSUE THREAD

**Issue by developer-vivacity** [magento/magento2#7336]
Changing zip code on Shipping Address page does not update shipping options correctly after the second change (enter zip code for address (wait for shipping options to update), enter incorrect zip code for address (wait for shipping options to update), re-enter correct zip code for address
### Preconditions

1. Magento 2.1.1

### Steps to reproduce

1. Enter correct zip code for address and wait for shipping options to update. Now It display the availabel shipping method.
2. Now enter incorrect zip code for address and wait for shipping options to update. Now it shows 'Sorry, no quotes are available for this order at this time'.
3. Now re-enter correct zip code for address and wait for shipping options to update. Now it again shows 'Sorry, no quotes are available for this order at this time', 

### Expected result

1. On the third step, It should again display the available shipping options.

### Actual result

1. It is not displaying the available shipping methods after 3rd step even the address is samw hich was in 1st step..

Screenshots:

After Step-1: ![step-1](https://cloud.githubusercontent.com/assets/5985431/20052331/9ee203c2-a4f9-11e6-91b3-b03f57e9b423.png)

After Step-2: ![step-2](https://cloud.githubusercontent.com/assets/5985431/20052337/a51f244a-a4f9-11e6-8488-6034f40ea128.png)

After Step-3: ![step-3](https://cloud.githubusercontent.com/assets/5985431/20052342/abd83b50-a4f9-11e6-84d4-36e3528b44c4.png)

Please check this issue as we have to launch site today but this problem is preventing us to go live.
Thanks

**Comment by SerhiyShkolyarenko** [comment]
@developer-vivacity thank you for report!
As far as I see you work as registered user and have only UPS shipping method configured.
I tried this case on the latest develop branch and shipping worked fine. Is it reproducible for you on the latest commit?

![ups_methods](https://cloud.githubusercontent.com/assets/15108140/20146994/ccfc7b00-a6ae-11e6-8b09-1c60c3434306.png)

**Comment by developer-vivacity** [comment]
@SerhiyShkolyarenko Thanks for your reply. 
I will try with the latest commit. BTW Did you followed all three steps?

**Comment by SerhiyShkolyarenko** [comment]
@developer-vivacity yes, it's the state after third step on the screenshot.
I logged in as a customer with existing address,
I entered new address with invalid ZIP code on checkout,
I switched between these addresses twice,
the result is on the screenshot.

**Comment by developer-vivacity** [comment]
@SerhiyShkolyarenko Hi, Sorry for late response.
I have updated my store to Magento 2.1.2 But the issue still persists. 
You can also check here: https://aws-magento.csnw.com/

Please let me know What can I do now. 
Thanks.

**Comment by SerhiyShkolyarenko** [comment]
@developer-vivacity I clicked that link and saw customized store there. Please confirm if this issue is reproducible for you on the clean magento installation without any custom modules and themes.

**Comment by AirmanAJK** [comment]
I just ran into this issue myself. The first request uses the state abbreviation code <ShipTo><StateProvinceCode>, while the subsequent requests use the state name (ie "Illinois" instead of "IL").

**Comment by AirmanAJK** [comment]
Spent some more time debugging. The file "Magento_Checkout/js/model/address-converter.js" receives data in the format of regionId and regionCode instead of region_id and region_code for shipping updates after page load. This causes region_id to be missing, which Magento then falls back on the description instead of the abbreviation.

**Comment by magento-engcom-team** [comment]
@developer-vivacity, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
