### ISSUE TITLE
Magento2: Can't create bundle product at backend

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7337]
I'm using Magento version 2.1.1 and trying to create a bundle product at backend. By default the product page chooses Default attribute set and when I change it to something other e.g. "Rooms" (my custom attribute set) its just loading and firebug showing the error attached in the file.
![image](https://cloud.githubusercontent.com/assets/19583969/20056284/5bfb28b0-a50b-11e6-934b-fe51404a0b1e.png)

**Comment by veloraven** [comment]
@deepak-netwin thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by deepak-netwin** [comment]
Hi,

Steps:
1) Go to backend and try to create a bundle product.
2) Change the attribute set from Default to Some custom. By default, "Default" attribute set is selected.
3) Its just loading and loading and doesn't refresh the page. When I checked in firebug I saw the above mentioned error.

**Comment by deepak-netwin** [comment]
Any updates?

**Comment by deepak-netwin** [comment]
@veloraven I'm waiting for your reply on this.

**Comment by deepak-netwin** [comment]
@veloraven Are you able to reproduce the issue at your end?

**Comment by deepak-netwin** [comment]
@veloraven I figured it out and solved at my end only. The issue is my custom attribute set don't have group "Bundle Items" in it. So I created it and moved product attribute "shipment_type" under it. Now, I can create bundle product in my custom attribute set. http://prntscr.com/d95zah

@veloraven Thanks for bad support :P

**Comment by lily-PHP** [comment]
> [@veloraven](https://github.com/veloraven) I figured it out and solved at my end only. The issue is my custom attribute set don't have group "Bundle Items" in it. So I created it and moved product attribute "shipment_type" under it. Now, I can create bundle product in my custom attribute set. http://prntscr.com/d95zah
> 
> [@veloraven](https://github.com/veloraven) Thanks for bad support :P

Thanks, your solution solve my problem. I also add "shipment_type" to my attribute set, and can create bundle product. thanks~
