### ISSUE TITLE
Language switcher improvement

### ISSUE THREAD

**Issue by seansan** [magento/magento2#734]
Please find our language switcher improvement for Magento 2 below. 

I think this is how it should work. And if you dont want to loose current method then we can create a backend config option that allows both methods

PLease find full transcript here: http://magento.stackexchange.com/questions/42950/magento-multistore-languages-getting-the-locale-language-name-in-store-selector

```
<!-- LANGUAGES BOF -->
<?php if(count($this->getStores())>1): ?>
<?php
$stores = array();
$_current = null;

$languages = Zend_Locale::getTranslationList('language', Mage::app()->getLocale()->getLocaleCode());

foreach ($this->getStores() as $_lang) {
	
	$_selected = $_selected_option = $_language_name = '';
	$_language_code = substr(Mage::getStoreConfig('general/locale/code', $_lang->getId()),0,2);
	if (isset($languages[$_language_code])) {$_language_name = $languages[$_language_code];} 
	$parts = explode('(', $_language_name);
	$_language_name = trim($parts[0]);

	if ( ($_lang->getId() == $this->getCurrentStoreId()) ) {
	 $_current =  $_lang;
	 $_current_lang = $_language_name;
	 $_selected = ' class="selected"';
	 $_selected_option = ' selected="selected"';
	}

	// $stores[] = '<li'. $_selected .'><a style="background-image:url(\''. $this->getSkinUrl('images/flags/'.$_lang->getCode().'.png') .'\');" href="'. $_lang->getCurrentUrl() .'">'. $this->htmlEscape($_lang->getName()) .'</a></li>';
	$stores[] = '<li'. $_selected .'><a style="background-image:url(\''. $this->getSkinUrl('images/flags/'.$_language_code.'.png') .'\');" href="'. $_lang->getCurrentUrl() .'">'. $this->htmlEscape($_language_name) .'</a></li>';
	$select_stores[] = '<option '.$_selected_option.' value="'. $_lang->getCurrentUrl() .'">'. $this->htmlEscape($_lang->getName()) .'</option>';
}

?>
<div class="header-switch language-switch">
    <span><?php echo $this->__('Your Language:') ?>
        <span class="current"><?php echo $this->htmlEscape($_current_lang); ?></span>
    </span>
	<div class="header-dropdown">
        <ul><?php echo implode('', $stores); ?></ul>
    </div>
</div>
```

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30622

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Language-switcher-improvement/idi-p/47102).
