### ISSUE TITLE
GiftMessage is_available is not a bool if you using "USE_CONFIG" in Backend

### ISSUE THREAD

**Issue by renepenner** [magento/magento2#7342]
If the Store Backend Setting for "GiftMessage allow" is set to false and on a Product level is set to "use config" ... the GiftMessage Option is displayed in frontend.

### Preconditions
1.  GiftMessage Allow is set to "no" in Backend in general context.

### Steps to reproduce
1. Set the Option GiftMessage Allow to "use config" on a Product.
2. Put the Product into the cart in frontend.
3. Go to Cart

### Expected result
GiftMessage Form is  NOT displayed.

### Actual result
 GiftMessage Form is displayed.

### Possible Fix
Use the code from hier:

https://github.com/magento/magento2/blob/develop/app/code/Magento/GiftMessage/Helper/Message.php#L204

to get the right value for is_available hier:

https://github.com/magento/magento2/blob/develop/app/code/Magento/GiftMessage/Model/GiftMessageConfigProvider.php#L183

**Comment by veloraven** [comment]
@renepenner thank you for your report.
Please, identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by andreaskoch** [comment]
The issue does appear in

* Magento 2.1.3 CE
* Magento 2.1.2 EE

The issue can be fixed by rewriting the `getItemLevelGiftMessages()` method of the `\Magento\GiftMessage\Model\GiftMessageConfigProvider` class:


```php
<?php
namespace YourCompany\CoreBugPatcher\Model\GiftMessage;

use Magento\Catalog\Model\Product\Attribute\Source\Boolean;


class GiftMessageConfigProvider extends \Magento\GiftMessage\Model\GiftMessageConfigProvider
{
    protected function getItemLevelGiftMessages()
    {
        $itemLevelConfig = [];
        $quote = $this->checkoutSession->getQuote();
        foreach ($quote->getAllVisibleItems() as $item) {
            $itemId = $item->getId();
            $itemLevelConfig[$itemId] = [];
            $isMessageAvailable = $item->getProduct()->getGiftMessageAvailable();

            if($isMessageAvailable == Boolean::VALUE_USE_CONFIG) {
                $isMessageAvailable =  $this->scopeConfiguration->getValue(
                    \Magento\GiftMessage\Helper\Message::XPATH_CONFIG_GIFT_MESSAGE_ALLOW_ITEMS,
                    \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $item->getStore()
                );
            }

            // use gift message product setting if it is available
            if ($isMessageAvailable !== null ) {
                $itemLevelConfig[$itemId]['is_available'] = (bool)$isMessageAvailable;
            }
            $message = $this->itemRepository->get($quote->getId(), $itemId);
            if ($message) {
                $itemLevelConfig[$itemId]['message'] = $message->getData();
            }
        }
        return count($itemLevelConfig) === 0 ? null : $itemLevelConfig;
    }
}
```

It would be nice of you could reopen this issue.
