### ISSUE TITLE
requirejs-config random context generation

### ISSUE THREAD

**Issue by bardkalbakk** [magento/magento2#7343]
The requirejs-config.js generation in Magento\Framework\RequireJs\Config is not generating content in a consistent way.  

1. requirejs-config.js found in the "secure" folder in frontend/vendor/theme/lang/secure is generated on the first cache miss, and is generated in the current store context. If module output is disabled for some stores you will experience random result based on the first store that is visited. 

2. setup:static-content:deploy is running in context of the default store(store id 1), and requirejs-config is generated in that context.  If module output is disabled for the default store , then this will affect all other stores. 

Magento version 2.1.0

**Comment by veloraven** [comment]
@bardkalbakk thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
