### ISSUE TITLE
Strange things on PNG product image upload (Magento 2.1.1

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#7347]
### Preconditions
1. Magento 2.1.1

### Steps to reproduce

1. In product page uploading PNG photos fails, no error, nothing happen.
2. If add a JPG file first, same PNG Files can be uploaded
3. They work on product page but not in thumb views on catalog list

### Expected result

1. PNG upload should work without JPG upload first
2. Images should appear as thumbs

Here is a sample image:
(https://cloud.githubusercontent.com/assets/6672673/20097716/3051d8c6-a5b0-11e6-84e8-ff88dd236ebe.png)

**Comment by JDavidVR** [comment]
Can you upload images you are testing with

**Comment by flipflap** [comment]
I added an image. The problem with the thumb is solved. It needed to be activated in the image details to become thumb.

**Comment by veloraven** [comment]
@flipflap thank you for your report.
So is the issue solved?
If it is please close this issue.
If it is not please describe more detailed steps and separate Actual Result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
