### ISSUE TITLE
Bug with product images on category page and in admin product grid

### ISSUE THREAD

**Issue by alexber88** [magento/magento2#7358]
Bug with product images
### Preconditions
1. Magento 2.1.2 EE
2. PHP 5.6

### Steps to reproduce
1. Create multiple store views (for instance Netherlands and France)
2. Make Netherlands as default store view
3. Disable English store view
4. Go to admin panel and create new product with selected store view "All store views" and uploaded image
5. Check that product image is appeared in DB in catalog_product_entity_varchar table with store_id=0
6. Check that product appeared in product grid in admin and thumbnail is shown
7. Check that product appeared in the frontend on category page in both store views with image
8. Open product edit page in admin on store view "Netherlands" (or any other store view that you set as Default)
9. Change name of product
10. Save product
11. Go to NL store view on frontend
12. Check that product name on category page has changed
13. Check in catalog_product_entity_varchar table that rows for NL store view with image have appeared
14. Repeat steps 9 - 13 for French store view
15. Go to product edit page in admin on NL store view
16. Delete image
17. Save product
18. Check that message about unable to delete image is appeared
19. Check that product image is shown on NL store view on product edit page in admin
20. Check that product image is shown on "All store views" on product edit page in admin
21. Go to frontend on category page on NL store view and check that image is displayed (It doesn't display)
22. Check in DB in catalog_product_entity_varchar table that image was NOT deleted (it was deleted)
23. Check in product grid in admin that thumbnail is displayed (it doesn't display. Magento now takes image for default store view. In our case it's NL. But image was deleted) 

### Expected result

1. Product image should be displayed on category page in all store views
2. Product thumbnail for "all store views" should be displayed in product grid in admin. Not only for default store view
3. Image shouldn't be deleted from separate store view if it was uploaded with preselected option "All store views"

### Actual result
1. Image is deleted from, but message shows another result
2. Image is not displayed in product grid in admin
3. Image is not displayed on category page on all store views

**Comment by veloraven** [comment]
@alexber88 thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
