### ISSUE TITLE
Password reset as admin on behalf of customer uses incorrect configuration prefix

### ISSUE THREAD

**Issue by markwilson** [magento/magento2#7359]
### Preconditions
1. Magento CE 2.1.2
2. No value for `admin/security/password_reset_protection_type` (defaults to 1 - `ResetMethod::OPTION_BY_IP_AND_EMAIL`)

### Steps to reproduce
1. Set `customer/password/password_reset_protection_type` to `0` - i.e. no reset protection for customers
2. Log in as an admin user
3. Find and edit a customer
4. Click "Reset Password" more than once

### Expected result
1. Password protection for customers is disabled and so multiple emails should be sent

### Actual result
1. First email will be sent without error
2. Subsequent attempts results in the following error: "Something went wrong while resetting customer password."

### Cause

It is because the user is an admin and so the `admin/security/` prefix is applied to the config path, instead of `customer/password/`. The `admin/security/password_reset_protection_type` should relate to the admin login, not customer logins.

In `\Magento\Security\Model\SecurityChecker\Frequency::check()`

**Comment by sevos1984** [comment]
This is fixed in develop branch https://github.com/magento/magento2/commit/7a67ac94dd9a925256f2c94b4ebc597f5e949206. Will be delivered to 2.1 soon
