### ISSUE TITLE
Attributes are unordered if simple product is added to configurable through add products manually link

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7361]
### Preconditions
1. Magento 2.1.2 PHP 5.6

### Steps to reproduce
1. Take a configurable product that already exists with a simple product that associated to it and one simple product that is not associated with it. You can just unassociate a simple product from it to see the same effect. To see the error make sure you unassociate or select a simple product that would be out of order if added in next. For example, if you have S,M,L,XL then deselect the Small or Med or Large.
2. Click the add product manually link and search for the disassociated product.
3. Add it.

### Expected result
1. The product attribute order should fall into the sequence stated in the attribute template. S,M,L,XL

### Actual result
1. Whatever product you just added falls to the bottom in the pull-down

![error](https://cloud.githubusercontent.com/assets/21045500/20111373/c89ace62-a59c-11e6-9a04-1cd88982bfdd.jpg)

The same thing happens if you upload your simple products via csv and try to associate them with the configurable. For instance, if you already have size Large simple product associated and try to upload a Small simple product and associate it to the same configurable it will also come in out of order.

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket id MAGETWO-59803

**Comment by magento-engcom-team** [comment]
@rosandrest, thank you for your report.
We've created internal ticket(s) MAGETWO-81605 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @rosandrest

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@rosandrest thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
