### ISSUE TITLE
Very STRANGE on XAMPP

### ISSUE THREAD

**Issue by frankthoeny** [magento/magento2#7364]
I followed the installation process to the T.  Completes the browser install with success. Now, going to Admin control panel, there are 32 errors in the Chrome console.<F12> All links are broken, images missing, CSS is missing, JS is missing. Does not compile correctly on Windows 10 running XAMPP server. IS this a limitation of Windows 280 character path limitation? After all, I have installed it at the xampp/htdocs-magento directory. do I really need to exclude htdocs-magento for htdocs? Make no sense as to why this is broken. I have been at it for 4 days trying to figure this out.  I need some help please!

**Comment by crantron** [comment]
You need to: build static assets, permissions and user roles are correct. This is should be closed, for it's user error.

**Comment by frankthoeny** [comment]
" You need to: build static assets, permissions and user roles are correct. This is should be closed, for it's user error. "
What do you mean it's user error? 
Can you give me a clue on what to do?

**Comment by frankthoeny** [comment]
I followed all the steps on this link 
https://www.cloudways.com/blog/how-to-install-magento-2-on-localhost/

**Comment by frankthoeny** [comment]
On command-line when I use composer update this never asked me for Username and Password. And I had to update the repository from https://packages.magento.com to https://repo.magento.com

Makes me think Magento is a hack. Otherwise, why do I need to update and change things before I even install Magento on my XAMPP server. I asked for help from someone. This is not closed

**Comment by thlassche** [comment]
It is a user error. When magento is in production mode static assets are not generated on the fly. You used an incomplete guide, please look at the official resources.

Most probably you just need to executed:

```
bin/magento setup:static-content:deploy
```

**Comment by veloraven** [comment]
@frankthoeny thank you for your feedback.
If it is an issue report please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
If it is a question please post it to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice. As GitHub repository is used to capture code and documentation issues.

**Comment by frankthoeny** [comment]
@thlassche I have a Windows computer. Please explain how to execute

`bin/magento setup:static-content:deploy`

@veloraven assumed you already know that I downloaded this version of Magento 2 from github. Just tell me that Magento is an Linux/Mac app then I will leave you alone.

**Comment by thlassche** [comment]
@frankthoeny You should run it on linux, e.g. using vagrant or Virtualbox. Makes your life a whole lot easier.

**Comment by frankthoeny** [comment]
Thank you

**Comment by crantron** [comment]
Excuse me, but really? lol

**Comment by frankthoeny** [comment]
@crantron Please shed some light. What is missing from Magento in order to make it work on Windows?

**Comment by crantron** [comment]
- download virtualbox (https://www.virtualbox.org/wiki/Downloads)
  - install a linux distribution, for example: https://www.centos.org/download/, or https://www.ubuntu.com/download/ 
    -  configure L.A.M.P stack on linux distro, for example: http://howtoubuntu.org/how-to-install-lamp-on-ubuntu
      - couple the latter with, http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html
  - OR download vagrant, here: https://www.vagrantup.com/downloads.html
    - then download: https://github.com/paliarush/magento2-vagrant-for-developers
      - this is a fantastic vagrant box everything is baked in.
- if you have questions after you done all that you can email me at chris@gigasavvy.com. Github issues are not for help, they are to identify core issues. Godspeed.
