### ISSUE TITLE
M2.1.2 - Inserting Image through WYSIWYG Drops HTML in Wrong Field

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7368]
### Preconditions

1. Magento CE 2.1.2
2. PHP 7.0.8+
3. MySQL 5.6+
4. Globally set WYSIWYG to not display by default.

### Steps to reproduce

1. Open up any product/page.
2. Find the "Description" field.
3. Click on "Show Editor" to see WYSIWYG.
4. Click on "Select Image" button.
5. Follow process to insert image into WYSIWYG (or upload new image and select that one).

### Expected result

1. Image should appear in WYSIWYG

### Actual result

1. Image tag appears in "Short Description" field.

### Extra Notes
This seems to be similar to #6138 and #5811, with the added bonus of the image tag being inserted into the wrong field. An ETA as to when this will make it into the production build would be greatly appreciated.

**Comment by dthampy** [comment]
@jeffrenvoy , a new internal ticket has been created to track this issue MAGETWO-60900 since fix for #6138 has already been delivered to mainline-develop.

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.
We've created internal ticket(s) MAGETWO-60900 to track progress on the issue.

**Comment by nmallepally** [comment]
Any quick fix around, having same issue on magento 2.1.8. inset link returns empty value.

**Comment by wehaveaplan** [comment]
Any update on this? Like a temporary fix. Still present in Magento 2.2.

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by PeterEsser** [comment]
Hello @magento-engcom-team 

This issue is still present in Magento 2.2.4, so please review this once more. At the moment you are unable to use the WYSIWYG editor to insert images so the flow is not user friendly anymore.
Would happy to assist on this matter to resolve it.

Peter

**Comment by orionpt** [comment]
I'd like to confirm that the issue is still present. New install with the same behaviour as OP.
Magento CE 2.2.6
PHP 7.1.22
MySQL 5.6
