### ISSUE TITLE
Setup fails at 94% - MacOS X / MAMP PRO 

### ISSUE THREAD

**Issue by MihaiCraciun** [magento/magento2#737]
Hello guys,

I really want to get passed the install phase but I think something is not right.
I tryed installing magento 2 two times . First with a light composer.json found here http://magento.stackexchange.com/questions/41591/magento-2-composer-install/41628#41628

Got an error saying : 

> [ERROR] exception 'Exception' with message ' 
> Fatal error: Class 'Magento\Framework\Stdlib\DateTime\TimezoneInterface' not found in /Users/username/www/magento/vendor/magento/project-community-edition/app/bootstrap.php on line 56' in /Users/username/www/magento/vendor/magento/project-community-edition/lib/internal/Magento/Framework/Shell.php:80 
> Stack trace: 
> # 0 /Users/username/www/magento/vendor/magento/project-community-edition/setup/module/Magento/Setup/src/Model/Installer.php(509): Magento\Framework\Shell->execute('/usr/bin/php -f...', Array)

Quickly abandoned that and tried with the install steps from magento 2 repo : git clone, composer install in both root and setup folders.

I am on Mac OS Mavericks, using MAMP PRO 3.0.7.2, runing PHP 5.5.18
phpinfo says mcrypt is enabled but still when the installer reachers 94% I get this error : 

> Installing data fixtures: 
> /usr/bin/php -f '/Users/username/www/magento/dev/shell/run_data_fixtures.php' -- --bootstrap='MAGE_DIRS[base][path]=/Users/username/www/magento' 2>&1 
> [ERROR] exception 'Exception' with message ' 
> Fatal error: Uncaught exception 'Exception' with message 'Module 'Magento_Core' depends on 'mcrypt' PHP extension that is not loaded.' in /Users/username/www/magento/lib/internal/Magento/Framework/Module/DependencyManager.php:56 
> Stack trace: 
> # 0 /Users/username/www/magento/lib/internal/Magento/Framework/Module/Declaration/Reader/Filesystem.php(107): Magento\Framework\Module\DependencyManager->checkModuleDependencies(Array, Array)
> # 1 /Users/username/www/magento/var/generation/Magento/Framework/Module/Declaration/Reader/Filesystem/Proxy.php(95): Magento\Framework\Module\Declaration\Reader\Filesystem->read('global')
> # 2 /Users/username/www/magento/lib/internal/Magento/Framework/Module/ModuleList.php(56): Magento\Framework\Module\Declaration\Reader\Filesystem\Proxy->read('global')
> # 3 /Users/username/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Factory.php(209): Magento\Framework\Module\ModuleList->__construct(Object(Magento\Framework\Module\Declaration\Reader\Filesystem\Proxy), Object(Magento\Frame in /Users/username/www/magento/lib/internal/Magento/Framework/Module/DependencyManager.php on line 56' in /Users/username/www/magento/lib/internal/Magento/Framework/Shell.php:80
> 
> Stack trace: 
> # 0 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(509): Magento\Framework\Shell->execute('/usr/bin/php -f...', Array)
> # 1 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(377): Magento\Setup\Model\Installer->exec('-f %s -- --boot...', Array)
> # 2 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
> # 3 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(263): call_user_func_array(Array, Array)
> # 4 /Users/username/www/magento/setup/module/Magento/Setup/src/Controller/Install/StartController.php(102): Magento\Setup\Model\Installer->install(Array)
> # 5 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install\StartController->indexAction()
> # 6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 7 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 8 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 9 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 10 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
> # 11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 12 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 13 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 14 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 15 /Users/username/www/magento/setup/index.php(48): Zend\Mvc\Application->run()
> # 16 {main}
> 
> Next exception 'Magento\Framework\Exception' with message 'Command returned non-zero exit code: 
> `/usr/bin/php -f '/Users/username/www/magento/dev/shell/run_data_fixtures.php' -- --bootstrap='MAGE_DIRS[base][path]=/Users/username/www/magento' 2>&1`' in /Users/username/www/magento/lib/internal/Magento/Framework/Shell.php:81 
> Stack trace: 
> # 0 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(509): Magento\Framework\Shell->execute('/usr/bin/php -f...', Array)
> # 1 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(377): Magento\Setup\Model\Installer->exec('-f %s -- --boot...', Array)
> # 2 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
> # 3 /Users/username/www/magento/setup/module/Magento/Setup/src/Model/Installer.php(263): call_user_func_array(Array, Array)
> # 4 /Users/username/www/magento/setup/module/Magento/Setup/src/Controller/Install/StartController.php(102): Magento\Setup\Model\Installer->install(Array)
> # 5 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install\StartController->indexAction()
> # 6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 7 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 8 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 9 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 10 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
> # 11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 12 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 13 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 14 /Users/username/www/magento/setup/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 15 /Users/username/www/magento/setup/index.php(48): Zend\Mvc\Application->run()
> # 16 {main}

What am I doing wrong ?
PS: i checked the Mac version of PHP which is 5.4.30 and that one doesn't have mcrypt but when i ran the installer it showed me the MAMP PHP version 5.5.18 mentioned above so in theory it should run with that version.

**Comment by bitmee** [comment]
Hey GUys,

I am having the same issue. It looks like @kandy solution resolved the problem.

Grateful if you'll could advice me where do I need to change the domain to try the solution and see whether it works for me.

Regards,
Aditya
