### ISSUE TITLE
M2.1.2 : url_key saved incorrect on multistore setup

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7373]
I have a Magento installation, but when I try to change the URL key of a category, it only gets changed for the latter store.

# Steps to reproduce

- Setup Magento 2.1.2
- Create 2 store views (in my case this was dutch and german)
- Create a category and save it
- Change the URL key of the category

# Expected result

- That the URL key is changed for all stores

# Actual result

- The URL key is only changed for that latter store (german in my example).

When I look at the `url_rewrite`-table in my database, I only see 1 record for store_id 2 (which is the german store).

# Workaround

A temporary workaround is to set the url_key manually for each individual store view.

**Comment by Tjitse-E** [comment]
Same issue here on 2.1.2.

**Comment by sevos1984** [comment]
Are you changing url key on all stores scope? Is 'Use Default' chekbox selected near url key on all scopes?

**Comment by kanduvisla** [comment]
Can't seem to reproduce the error now... I do remember I had a previous issue with the LitExtension shop migration that created a lot of additional values for additional store views. But in the meantime I already cleaned up the database. Maybe that was the issue? That `url_key` was saved for different store views in the database?

@Tjitse-E : can you provide steps to reproduce the issue?

**Comment by Tjitse-E** [comment]
@kanduvisla I can confirm that this is probably a LitExtension shop migration issue. I've got the same module installed on one of my Magento store's.

 I've tried to reproduce this issue on a unmodified Magento 2.1.2 store with sample data and everything worked like expected.

**Comment by sevos1984** [comment]
I'm closing this as no longer reproducible. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for more questions.
