### ISSUE TITLE
Magento2: Show price on bundle option summary

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7374]
I want to show selected bundle options price in the summary block at right. By default, it only shows the selected option from the bundle product. Thanks.

**Comment by vasilii-b** [comment]
@deepak-netwin  I guess what you want is a new feature, not a magento 2 bug/issue.

**Comment by deepak-netwin** [comment]
@vasilii-b Oh, so is this not the default feature there. If not, how can I add that, any idea?

**Comment by vasilii-b** [comment]
@deepak-netwin  It can be done by modifying files: 
- `app\code\Magento\Bundle\view\frontend\templates\catalog\product\view\summary.phtml` [(line 48-51)](http://prntscr.com/d5f5v0)
- `app\code\Magento\Bundle\view\frontend\web\js\product-summary.js` [(line 104-110)](http://prntscr.com/d5f5ni) 

_For sure you should modify this files according to 'best practices' - move this files into your theme and modify them._

But, I don't see any reason to do this because selected options [are visible on the left](http://prntscr.com/d5euei).

**Comment by deepak-netwin** [comment]
@vasilii-b Thanks for your reply.
Yes, I've already override those files under my custom theme and trying to modify it. But I'm not getting price variable there in js. Do I need to add any code in block or module files for that.
Please see this how I want it http://prnt.sc/d5f80q

**Comment by vasilii-b** [comment]
@deepak-netwin  look at my previous comment. There are links to screenshots that show how you need to modify these files to see option price.

**Comment by deepak-netwin** [comment]
@vasilii-b Hi,

I managed to add price of selected action when page loads. Code is as below in app\code\Magento\Bundle\view\frontend\web\js\product-summary.js:

_price_: this.cache.currentElement.options[key].selections[row].prices.finalPrice.amount

But, when I select one more option its showing js error as below:
http://prntscr.com/d5foz9

Also, the price is not showing the currency symbol. Please see this http://prnt.sc/d5fpy6

Any further clue will be helpful. Thank you.

**Comment by vasilii-b** [comment]
@deepak-netwin I'll look into it deeper this evening.
And yeah , I know price is not formated correctly. I''ve tried it quikly at this moment. 
Will let you know.

**Comment by deepak-netwin** [comment]
@vasilii-b I want to add a total price of all selected options for that particular product. 
Please see this http://prntscr.com/d5g0d3. Also, need to show currency symbol.
I understand that I need to make changes in [_renderOption function ](http://prntscr.com/d5g0vr)

**Comment by deepak-netwin** [comment]
@vasilii-b 
I've tried few things but couldn't able to get the total price for particular row.
I tried the operations on object "selected" in this.cache.currentElement.
Any help would be appreciated.

**Comment by vasilii-b** [comment]
@deepak-netwin I managed it to show the currency symbol, but not total price per option yet. I will let you know where I'm done with this.

**Comment by deepak-netwin** [comment]
@vasilii-b Ok great. Can you please share the code for currency symbol?

**Comment by vasilii-b** [comment]
In`product-summary.js` add `priceUtils` as dependency. 
Then add it as a parameter in `function($, mageTemplate, priceUtils)`.

For `_price_:` use `priceUtils.formatPrice({{row_price_here}})`

**Comment by vasilii-b** [comment]
@deepak-netwin  Here you go! 

``` html
<!-- file summary.phtml -->

<script data-template="bundle-summary" type="text/x-magento-template">
       <li>
         <strong class="label"><%- data._label_ %>:</strong>
         <strong class="total_price"><%- data._option_total_ %></strong>
         <div data-container="options"></div>
        </li>
</script>

```

``` javascript

// file product-summary.js

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
define([
    'jquery',
    'mage/template',
    'priceUtils', // add here priceUtils as dependency to format price
    'jquery/ui',
    'Magento_Bundle/js/price-bundle'
], function ($, mageTemplate, priceUtils) { // add priceUtils as paramater
    'use strict';

    /**
     * Widget product Summary:
     * Handles rendering of Bundle options and displays them in the Summary box
     */
    $.widget('mage.productSummary', {
        options: {
            mainContainer:          '#product_addtocart_form',
            templates: {
                summaryBlock:       '[data-template="bundle-summary"]',
                optionBlock:        '[data-template="bundle-option"]'
            },
            optionSelector:         '[data-container="options"]',
            summaryContainer:       '[data-container="product-summary"]',
            bundleSummaryContainer: '.bundle-summary'
        },
        cache: {},
        /**
         * Method attaches event observer to the product form
         * @private
         */
        _create: function () {
            this.element
                .closest(this.options.mainContainer)
                .on('updateProductSummary', $.proxy(this._renderSummaryBox, this))
                .priceBundle({})
            ;
        },
        /**
         * Method extracts data from the event and renders Summary box
         * using jQuery template mechanism
         * @param {Event} event
         * @param {Object} data
         * @private
         */
        _renderSummaryBox: function (event, data) {
            this.cache.currentElement = data.config;
            this.cache.currentElementCount = 0;

            // Clear Summary box
            this.element.html('');

            $.each(this.cache.currentElement.selected, $.proxy(this._renderOption, this));
            this.element
                .parents(this.options.bundleSummaryContainer)
                .toggleClass('empty', !this.cache.currentElementCount); // Zero elements equal '.empty' container
        },

        /**
         * @param {String} key
         * @param {String} row
         * @private
         */
        _renderOption: function (key, row) {
            var template;

            if (row && row.length > 0 && row[0] !== null) {

                var optionTotalPrice = 0;

              // start calculate option total price
                var widget = this;
                row.forEach(function(item){
                    optionTotalPrice += widget.cache.currentElement.options[key].selections[item].prices.finalPrice.amount * widget.cache.currentElement.options[key].selections[item].qty;
                });

                this.cache.currentElement.options[key].totalPrice = priceUtils.formatPrice(optionTotalPrice, this.cache.currentElement.priceFormat.pattern); // save it in option object

              // end calculating option total price

                template = this.element
                    .closest(this.options.summaryContainer)
                    .find(this.options.templates.summaryBlock)
                    .html();
                template = mageTemplate($.trim(template), {
                    data: {
                        _label_: this.cache.currentElement.options[key].title,
                        _option_total_: this.cache.currentElement.options[key].totalPrice // add option total price
                    }
                });

                this.cache.currentKey = key;
                this.cache.summaryContainer = $(template);
                this.element.append(this.cache.summaryContainer);

                $.each(row, this._renderOptionRow.bind(this));
                this.cache.currentElementCount += row.length;

                //Reset Cache
                this.cache.currentKey = null;
            }
        },

        /**
         * @param {String} key
         * @param {String} optionIndex
         * @private
         */
        _renderOptionRow: function (key, optionIndex) {
            var template;

            template = this.element
                .closest(this.options.summaryContainer)
                .find(this.options.templates.optionBlock)
                .html();
            template = mageTemplate($.trim(template), {
                data: {
                    _quantity_: this.cache.currentElement.options[this.cache.currentKey].selections[optionIndex].qty,
                    _label_: this.cache.currentElement.options[this.cache.currentKey].selections[optionIndex].name,
                    _price_: priceUtils.formatPrice(this.cache.currentElement.options[this.cache.currentKey].selections[optionIndex].prices.finalPrice.amount * this.cache.currentElement.options[this.cache.currentKey].selections[optionIndex].qty, this.cache.currentElement.priceFormat.pattern) // row price calculation
                }
            });
            this.cache.summaryContainer
                .find(this.options.optionSelector)
                .append(template);
        }
    });

    return $.mage.productSummary;
});

```

![image](https://cloud.githubusercontent.com/assets/13456702/20220544/9a9372a2-a836-11e6-98cc-b86b9bb9e1ec.png)

**Comment by deepak-netwin** [comment]
@vasilii-b GREAT! This worked like a charme.
Thank you so much for the efforts taken.

**Comment by deepak-netwin** [comment]
@vasilii-b I've one more query. I want to list default selected bundle options.
For this, I've created my own block in my custom module and added this block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option in the constructor as below:

 public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option $bundleOption,
        array $data = []
    )
    {        
        $this->_bundleOption = $bundleOption;
        parent::__construct($context, $data);
    }

And then, I'm accessing the core method from the class like this:

public function getSelectedOptions() {
		return $this->_bundleOption->getDefaultValues();
	}

But, its showing error **"Fatal error: Uncaught Error: Call to a member function getDefaultSelection() on null"**.

Can you please tell me what is wrong I'm doing here?

Thanks!

**Comment by vasilii-b** [comment]
@deepak-netwin  move this one on stackoverflow. Let's keep magento2 repo issue channel clean :)

**Comment by vasilii-b** [comment]
@deepak-netwin please close this issue. Thanks.

**Comment by deepak-netwin** [comment]
@vasilii-b Hi, Today, I'm facing some new problem. You remember we did above changes for bundle product but now bundle products not showing selected products on summary block. The current magento version of website is 2.1.7. Any clue, what could be the issue?

**Comment by jstukey** [comment]
This is great. May I ask how to do the same thing in the same place but instead of showing the price of each selection I need to show the product image associated with each selection. I'm stuck. @deepak-netwin

**Comment by Ckaneriya** [comment]
@vasilii-b 
I have added products in bundle options. the input type is radio button. I want to display the product image in summary section
Is there a way to display the product image in the bundle option summary?
