### ISSUE TITLE
Support Varnish cache flushing through management interface 

### ISSUE THREAD

**Issue by Jaap-Jan** [magento/magento2#7375]
As it currently stands, Magento 2 flushes the Varnish cache by performing a HTTP PURGE request.

This makes Magento 2 and Varnish unsuitable for use on a shared hosting environment where every user has their own Varnish instance, since everyone can connect to this port and thus flush the cache of every other user.

In Magento 1 (with the Turpentine extension), the cache is flushed through the management interface and protected by the shared secret.

Are there any plans to develop 'Magento-1-style' cache flushes and disallow flushing through the HTTP port?

**Comment by cscd98** [comment]
Need this 👍

**Comment by x86fantini** [comment]
I'm also interested

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/7296

**Comment by veloraven** [comment]
@Jaap-Jan thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If this is more like an improvement please refer it to  the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by Jaap-Jan** [comment]
Posted as idea: https://community.magento.com/t5/Magento-2-Feature-Requests-and/Varnish-cache-flushing-via-admin-interface/idi-p/53826
