### ISSUE TITLE
Accordion data-mage-init 'active' option not working as expected

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7381]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Change `"multipleCollapsible": false` to `"multipleCollapsible": true` in `Magento_LayeredNavigation/templates/layer/view.phtml` (#narrow-by-list element)
2. Change `"active": false` to `"active": true` in the same template.
3. Go to any category page.

### Expected result

1. All attribute groups should be expanded by default.

### Actual result

1. All attribute groups are still collapsed by default. If setting the `active` value to `false` collapses all attribute groups by default, then it is expected that setting the value to `true` should expand all attribute groups by default. Currently you can only set the value to `false` or an array of individual attribute groups to expand by default. When the value is `true`, all attribute groups should be expanded by default (assuming `multipleCollapsible` is set to `true` as in step 1).

**Comment by palamar** [comment]
Hello
Internal issue MAGETWO-60897 has been created.

But as a quick solution you can reuse accordion in your own implementation, something like

``` js
define([
    "jquery",
    "mage/accordion"
], function($, accordion){
    "use strict";

    $.widget("mage.acc", accordion, {
        options: {
            activeAll: false
        },

        _callCollapsible: function() {
            if((typeof this.options.active) === "string") {
                this.options.active = this.options.active.split(" ").map(function(item) {
                    return parseInt(item, 10);
                });
            }
            var self = this,
                disabled = false,
                active = false;

            $.each(this.collapsibles, function(i) {
                disabled = active = false;
                if($.inArray(i,self.options.disabled) !== -1) {
                    disabled = true;
                }
                if($.inArray(i,self.options.active) !== -1 || self.options.activeAll) {
                    active = true;
                }
                self._instantiateCollapsible(this,i,active,disabled);
            });
        }
    });

    return $.mage.acc;
});
```

import it via requirejs and use it like

``` js
data-mage-init='{"acc":{"openedState": "active", "collapsible": true, "activeAll": true "multipleCollapsible": true}}'
```

in template.

**Comment by thdoan** [comment]
Thanks for the custom accordion override. For now we are OK with using an array from 0 to 9 knowing that we'd never have more than 10 filters per category.

**Comment by lakshitha24** [comment]
this is working for me.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
