### ISSUE TITLE
After deploy in html code added version deploy

### ISSUE THREAD

**Issue by workmi** [magento/magento2#7384]
Hello. Who can help me ?
After php bin/magento setup:static-content:deploy -f 
I see in my code html page:
<head >
        <script>
    var require = {
        "baseUrl": "http://unisel.ru/static/**version1478715401**/frontend/Magento/luma/en_US"
    };
</script>
How delete version ?

**Comment by veloraven** [comment]
@workmi thank you for your submission. 
The Magento 2 GitHub repository is used to capture code and documentation issues. Questions should be posted to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.
