### ISSUE TITLE
images added with WYSIWYG in category description are uploaded into admin-directory

### ISSUE THREAD

**Issue by emil-777** [magento/magento2#7393]
### Preconditions
1. PHP 7 
2. Magento 2.1.2

### Steps to reproduce
When I'm uploading an image with the WYSIWYG-editor for the category description, the image is uploaded - and its' path which is used in the src-attribute of img-tag to the admin directory (domain.com/admin_veuCvtf/...).
I assume it has to be located in pub/media./.. directory. Otherwise the name of the backend login is disclosed. 

### Expected result
The uploaded image is located in /pub/media/... directory.

### Actual result
In the img-src-tag the file is located in domain.com/admin_veuCvtf/.. directory.

**Comment by devhn** [comment]
Similar to #6138?

**Comment by emil-777** [comment]
yes, seems to be similar

**Comment by AbdulKadir-Agoliya** [comment]
I have same issue but i got it solution
in category/description.phtml
  <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>

replace with
  <?php /* @escapeNotVerified */ echo $this->helper('Magento\Cms\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435
