### ISSUE TITLE
Order Comment Email not using site/store scope Sender email address

### ISSUE THREAD

**Issue by ipekerti** [magento/magento2#7395]
### Preconditions
M2.1.0 Community
Although I don't think the following environment info matters, here they are: PHP v 5.6.23-1, nginx v 1.4.6, Mysql v. 5.6.27.

1. Single instance of M2, multiple sites
2. Each site uses its own unique sender email address defined at **Stores > Configuration > General > Store Email Addresses**:
  EXAMPLE:
  -- Default Config scope: CustomerService@MainSite.com
  -- 2nd Site scope: CustSvc@SecondSite.com

### Steps to reproduce
1. Submit order comment via admin **Sales > Orders** for a 2nd site order, with "Notify Customer by Email" enabled.
NOTE: The issue is also recreatable when generating order comment via API.

### Expected result
1. An Email originating from the 2nd site scope sender email address

### Actual result
1. The email incorrectly bears the Default Config (MainSite) scope sender email address, while the rest of the email body correctly uses the 2nd site information.
**[https://dl.dropboxusercontent.com/u/42579357/Ord-comment-email.png](url)**

Workaround:
We were able to work around it by pointing the by setting the **Stores > Configuration > Sales > Sales Emails > Order Comment Email Sender** at the 2nd Site scope to "**Custom Email 2**".
Then define **Stores > Configuration > General > Store Email Addresses > Custom Email 2 Sender** to "CustSvc@SecondSite.com".

**Comment by olysenko** [comment]
Hi, thank you for your report. Your issue duplicates [6954](https://github.com/magento/magento2/issues/6954). Closed as duplicate
