### ISSUE TITLE
Sales sequence prefix and pad length will not change.

### ISSUE THREAD

**Issue by dreucifer** [magento/magento2#7397]
### Preconditions

1. Magento 2.1.2 CE

### Steps to reproduce

1. Opened up the `eav_entity_type` table and modified the rows for `order`, `invoice`, `creditmemo`, and `shipment` so that `increment_pad_length` was 5 instead of 8
2. Cleared cache and re-ran `setup:di:compile`

### Expected result

1. New orders should have shorter order numbers, i.e 0000XX instead of 0000000XX
2. `eav_entity_store` should be populated.

### Actual result

1. New orders still use the default pad length and pattern as defined in `app/code/Magento/SalesSequence/Model/Sequence.php`
2. `eav_entity_store` remains empty.

### Additional Details
It looks like closed issue #5541 also covered this, but the 'solution' was a non-answer. Why doesn't the EAV-model code work correct in regard to orders?

**Comment by olysenko** [comment]
Hi, thank you for your report. In [#5541comment](https://github.com/magento/magento2/issues/5541#issuecomment-249501943) was described the correct solution. You should use di.xml to replace  the default pattern with your pattern. Closed. Feel free to reopen issue if described solution doesn't work for you
