### ISSUE TITLE
The customizable options are not all displayed on the orders

### ISSUE THREAD

**Issue by janeblonde** [magento/magento2#7402]
On some products we have 10 customizable options, each with a price. In testing we find that adding all ten means that on the Order and Invoice screens it looks like we can only see 56 charachters of the customisations. So they cannot be processed correctly. I've also checked and they do appear on the email sent to the client

### Preconditions
Magento ver. 2.1.2
PHP 7
MySQL 5.6

### Recreate

1. Create a product
2. Add some customisation options
3. Order product including all customisations

5. Check Order details in admin
6. Check Order details in customer email

### Expected result
we should be able to see all options on the order

### Actual result
we see that the customisations look to be cut after 65 charachters

![issue](https://cloud.githubusercontent.com/assets/1465071/20214014/7010f0be-a803-11e6-9f5d-c95fdef9fbcd.png)

**Comment by veloraven** [comment]
Internal ticket was created for this issue - MAGETWO-70023

**Comment by magento-engcom-team** [comment]
@janeblonde, thank you for your report.
We've created internal ticket(s) MAGETWO-70023 to track progress on the issue.

**Comment by janeblonde** [comment]
Wow, that was nearly a year ago! Thanks for looking at this all the same

**Comment by magento-engcom-team** [comment]
Hi @janeblonde 
This issue is fixed in 2.2 version
