### ISSUE TITLE
Visual Swatches with Different Pricing Doesn't Change Product Price

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#7407]
### Preconditions

1. Magento 2.1.2
2. PHP version 5.6.27

### Steps to reproduce

1. Create a new simple product
2. Add tier pricing and save
3. Then add configurations, using visual swatches. Making a configurable product.
4. Add a couple different prices to a few of the visual swatches.

### Expected result

1. Product price should change when user clicks on a visual swatch that has a different price.

### Actual result

1. Product price does not change.
2. I noticed if you add a configurable product like mentioned earlier without tier pricing, when a user clicks on the visual swatch with a different price it changes the product price accordingly.

**Comment by olysenko** [comment]
Hi, thank you for your report. It duplicates [3759](https://github.com/magento/magento2/issues/3759) and [5064](https://github.com/magento/magento2/issues/5064). Closed as duplicate
