### ISSUE TITLE
[M2.2-dev] Problem with new theme deployment

### ISSUE THREAD

**Issue by JDavidVR** [magento/magento2#7411]
I'm working on M2.2-dev I have created a new clean theme (parent theme is Magento/luma) I have errors executing command bin/matento setup:static-content:deploy -f

### Preconditions

1. Magento 2.2-dev
2. PHP 7.0.x
3. Mysql 5.6.x
4. Ubuntu 15.x
5. Apach2

### Steps to reproduce

1. Create a new theme
2. Configure parent Magento/luma
3. Open terminal and run: bin/matento setup:static-content:deploy -f

### Expected result

1. Magento should deploy all  theme files

### Actual result

1. getting this error:
 [Exception]                                                                                                        
  Notice: Undefined offset: 5 in <MAGENTO ROOT>/app/code/Magento/Deploy/Model/Deploy/LocaleDeploy.php on line 275 

SOLUTION:
On file https://github.com/magento/magento2/blob/develop/app/code/Magento/Deploy/Model/Deploy/LocaleDeploy.php
Line 175, change

`list($fileArea, $fileTheme, , $module, $filePath, $fullPath) = $info;`
to
`list($fileArea, $fileTheme, $module, $filePath, $fullPath) = $info;`

you can see that there is an extra "," between $fileTheme and $module

**Comment by tkacheva** [comment]
Issue MAGETWO-61207

**Comment by veloraven** [comment]
This issue has already been fixed in develop branch.
Closed.

**Comment by blewinsky** [comment]
This issue i'm getting with an update to Magento EE 2.1.10 within module `"magento/module-deploy": "100.1.6"` someone knows if there is a fix for it?

**Comment by alexdpunkt** [comment]
Having the same issue after upgrading from 2.1.7 to 2.1.10.

Seems like the `$info` Array in `vendor/magento/module-deploy/Model/Deploy/LocaleDeploy.php` on line 288 contains sometimes less than 6 elements, thus the error is thrown. 

In my case the problem was a broken theme in app/design/frontend.

**Comment by korostii** [comment]
Hey @magento-engcom-team , can this issue be looked at again? 
It seems to have resurfaced on 2.1.10

**Comment by royvanos** [comment]
@magento-engcom-team I'm also hitting this issue after upgrading from 2.1.9 to 2.1.10

**Comment by blewinsky** [comment]
I found out that this error is thrown when i have empty theme without files in it. 
Solution that @JDavidVR gave is not working.
So by removing that "empty" theme the problem is solved.

**Comment by medinadato** [comment]
@blewinsky , removing the empty theme worked for me. Tks!

**Comment by forwells** [comment]
yes ,it`s a solution for that Excepection error on the command,very thanks for you~! @JDavidVR
