### ISSUE TITLE
Magento 2 Import Does not upload same name file in different image of different folder

### ISSUE THREAD

**Issue by osmansorkar** [magento/magento2#7412]
I try to import product by magento2 import product option by CSV. I have all product image same name. I create folder for every product image and I upload it media/import directory and try to import my product but magento use only 1st image for all other product. It does not upload my other same name images. 

### Preconditions
Magento 2.1.0
PHP-7.0.12
Server: NGINX
Ubuntu 16.4
MYSQL -5.6

### Steps to reproduce:
1. Create A CSV File for import by same name image within multi directory
2. Upload file in pub/media/import directory with directory
3. Login Backend
4. Got to setting >> import
5. Select "Entity Type" Product 
6.  Select "Import Behavior" Add/Update 
7. Upload CSV File 
8. Click Button "Check Data "
9. Click "Import"
10. Import will be successful but it will be upload only first image and skip all other same name image   

### Expected result 
1. ![screenshot_13](https://cloud.githubusercontent.com/assets/10289018/20239543/a8b2b568-a92c-11e6-89bb-a5853cfeee9e.jpg)
After Enable Rename . It should not rename due to every image belong in different directory
2. ![screenshot_13 - copy](https://cloud.githubusercontent.com/assets/10289018/20348774/6a866002-ac31-11e6-8104-3ad2aebc3032.jpg)
3. ![screenshot_12](https://cloud.githubusercontent.com/assets/10289018/20239518/e3c4e230-a92b-11e6-8b72-a94373146620.png)

### Actual result

1. ![screenshot_11](https://cloud.githubusercontent.com/assets/10289018/20239517/e3c0635e-a92b-11e6-8049-b197b911d638.png)

**Comment by veloraven** [comment]
@osmansorkar thank you for your feedback.
Please describe more detailed steps in format:

**Steps:**
1.
2.
3.

**Comment by osmansorkar** [comment]
Steps:
1. Create A CSV File for import by same name image within multi directory
2. Upload file in pub/media/import directory with directory
3. Login Backend
4. Got to setting >> import
5. Select "Entity Type" Product 
6.  Select "Import Behavior" Add/Update 
7. Upload CSV File 
8. Click Button "Check Data "
9. Click "Import"
10. Import will be successful but it will be upload only first image and skip all other same name image

**Comment by JstrzAtW2M** [comment]
Any way around this or any movement with this bug?

**Comment by franckgarnier21** [comment]
I reproduce the same problem on magento 2.1.x

A workaround is to prefix or suffix image name.

**Comment by magewallet** [comment]
Any update on the same. I am able to reproduce the same in Magento 2.1.8 version as well. It little bit strange that this issue was submitted for 2.1.0 and it still coming in 2.1.8.

**Comment by magento-engcom-team** [comment]
@osmansorkar, thank you for your report.
We've created internal ticket(s) MAGETWO-81573 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#50
