### ISSUE TITLE
Config product: Dynamic weight, this item has no weight (Magento 2.1.2)

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#7419]
### Preconditions

1. Magento 2.1.2
2. Attribut Dynamic Weight default value: Yes

### Steps to reproduce

1. Adding config products get value correct "this item has weight"
2. Adding simple products to the config product gets wrong value "this item has no weight"
3. All simple products must be changed manually as guest check out has missing address for virtual products. Update multiple attributes is missing Dynamic Weight attribute.

### Expected result

1. Should ad "this item has weight" by default for simple products on conf products
2. Dynamic Weight attribute should be there to change by multiple attributes.

### Actual result

1. Ads "this item has no weight" by default for simple products on conf products
2. Dynamic Weight attribute is missing in edit multiple attributes function.

**Comment by veloraven** [comment]
@flipflap thank you for your report.
Please add Actual Result as well.

**Comment by flipflap** [comment]
Ok, done.

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal ticket MAGETWO-62278 was created

**Comment by magento-engcom-team** [comment]
@flipflap, thank you for your report.
We've created internal ticket(s) MAGETWO-62278 to track progress on the issue.

**Comment by inelukipg** [comment]
@magento-engcom-team Great! This issue is a major problem when creating a configurable product with children from options. (Which is the fastest way to create a large number of product combinations). You have to manually edit each product to enable "this item has weight"

**Comment by paengski13** [comment]
@magento-engcom-team I am getting an unexpected product type as well when creating a configurable product. Better yet add this "product has/has no weight" during the creation of product associated with the configurable product.

**Comment by magento-engcom-team** [comment]
@flipflap, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
