### ISSUE TITLE
Dependency check in the static tests fails for non core modules

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#7421]
When trying to run the static tests for a custom module (to ensure its quality) the dependency checks in the static tests `bin/magento dev:tests:run static` always report missing dependencies even if the dependencies are declared in the `composer.json` file of the module.

### Preconditions
Magento version: 2.2.0-dev.

### Steps to reproduce
1.  Create a custom extension that does nothing much, but it depends for example on `Magento_Backend` module.
2. set the module name in `composer.json` anything that does not start with `magento/module-` 
3. add the dependency in composer.json  
```
     "require": {
        "magento/framework": "100.2.*",
        "magento/module-backend": "~100.2.*",
    },
```
4. run `bin/magento dev:tests:run` in console

### Expected result
1. I should not get any dependency errors in the console

### Actual result
I get an error in the console saying that my module has an undeclared hard dependency. 

> Data set: [ROOT]/app/code/[Namespace]/[Module]/etc/di.xml
Module [Namespace]/[Module] has undeclared dependencies: hard [Magento\Backend]
[ROOT]/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:319
[ROOT]/lib/internal/Magento/Framework/App/Utility/AggregateInvoker.php:56
[ROOT]/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:322

### Additional info:  
This happens because of the way the module name is converted from composer.json file to the actual [module name](https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php#L653). It only takes into account values that start with `magento/module-`  or `magento/magento`.  
A more details description can be [found on stackexchange](http://magento.stackexchange.com/q/117626/146)

### Suggestion (feel free to challenge)  
Maybe the module name should be taken from the `registration.php` file that is required anyway for a module to function properly.

**Comment by shiftedreality** [comment]
Hi @tzyganu 

I've created an internal ticket MAGETWO-61364 to investigate and fix this issue.
Thank you.

**Comment by magento-engcom-team** [comment]
@tzyganu, thank you for your report.
We've created internal ticket(s) MAGETWO-61364 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@tzyganu thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
