### ISSUE TITLE
Credit memo negative amounts in totals

### ISSUE THREAD

**Issue by Frits1980** [magento/magento2#7424]
In The Netherlands (and EU also I believe) it is mandatory to provide a customer with a valid credit invoice as some amount is refunded. In this credit invoice the amount should be written in a negative because it's negative revenue.

Magento version 2.1.2

![creditmemo](https://cloud.githubusercontent.com/assets/6774843/20268318/eabcb0be-aa7e-11e6-9a10-445a206e7f33.png)
Screenshot of normal situation. In red I added the expected result.

I'd like to have this not only in the backend, but also in the frontend, e-mail, pdf and in the API results. How can I make this happen?

**Comment by magento-engcom-team** [comment]
@Frits1980 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by Frits1980** [comment]
WOW!!! Almost a year later this is your reaction. Never mind. If you can't understand my initial request you're not the one for the job.

**Comment by magento-engcom-team** [comment]
@Frits1980 thank you for the response. Does the issue still relevant? Have you tried latest Magento release?

**Comment by Frits1980** [comment]
I'm running 2.1.8. Everybody who actualy uses Magento knows what I mean with this. It's there in ALL  version, in 1 and in 2. It's an architectual flaw. Because this differs from the USA market and Magento is made for USA market. Archicectual wise It should really do Magento good to look beyond the USA market for webshop software and look at the needs of other parts of the world.
