### ISSUE TITLE
Feature Request: Custom option identifier

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#743]
**[TL;DR]** Each product custom option needs, in my opinion, a new field called `identifier` or something like that, that should be unique for one product.  
**[Long version]** Many times while working with Magento 1 I had to isolate for different reasons a custom option.  
Here is one scenario. Some of the products have a color custom option. In the cart, I needed to display the selected color not as text, but as a small colored box.  
But since the relation between products and custom options is one to many, the color option has a different, not identifiable ID. So it is hard to isolate only that specific option. I had to do all kinds of workarounds like regex or using a specific name of the option but only for the admin because the label needed to be translated.  
I tried to add myself this identifier field, but the custom option templates are not the easiest to extend or replace. It can be done, but with a lot of work.  
These problems would be solved if the identifier field was there from the start.  
**[Advantages]** for this approach.  
 - identify easily similar custom options
 - easier third party manipulation of custom options: example: Build easily a custom price calculation based on custom options. 

**[Disadvantages]**
 - yet another field to fill in.
 - The devs might get a question from a non-technical admin: "What's this?".

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31583

**Comment by verklov** [comment]
Closing this ticket as having related ticket in the internal tracker.
