### ISSUE TITLE
Min quantity should be seperate from default quantity on addProduct 

### ISSUE THREAD

**Issue by markalston** [magento/magento2#7431]
Currently if there is a min quantity set then the addProduct function defaults to using that when an item is added to cart.  This is probably fine for most use cases but for those of us allowing decimal quantities and minimums less than one this causes items to be added to the cart at the bare minimum. 

We should be able to set the default add to 1 ( or any other number really) while still allowing customers to purchase fractional quantities.  The simple fix which works great for me is to make the following change to addProduct which uses the minimum quantity if it is greater than 1 but uses 1 if the minimum quantity is less than 1.

module-checkout/Model/Cart.php

```
    public function addProduct($productInfo, $requestInfo = null)
    {
        $product = $this->_getProduct($productInfo);
        $request = $this->_getProductRequest($requestInfo);
        $productId = $product->getId();

        if ($productId) {
            $stockItem = $this->stockRegistry->getStockItem($productId, $product->getStore()->getWebsi$
            $minimumQty = $stockItem->getMinSaleQty();
            //If product was not found in cart and there is set minimal qty for it
            if ($minimumQty
                && $minimumQty > 1
                && !$request->getQty()
                && !$this->getQuote()->hasProductId($productId)
            ) {
                $request->setQty($minimumQty);
            }
        }
```

**Comment by veloraven** [comment]
@markalston thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
