### ISSUE TITLE
Custom option price added in Up-sell product also

### ISSUE THREAD

**Issue by Nehace40** [magento/magento2#7434]
I create one product with custom option(Radio Buttons) with different price, In frontend when i select custom option than product price is changed but that make changes in Up-Sell Products also

Magento Version 2.1

<a href="http://imageshack.com/i/plUgHRWNp" target="_blank"><img alt="FireShot Pro Screen Capture" src="http://imagizer.imageshack.com/img921/6756/UgHRWN.png" border="0"></a><br/>

<a href="http://imageshack.com/i/pmLmym2Ij" target="_blank"><img alt="FireShot Pro Screen Capture" src="http://imagizer.imageshack.com/img922/3447/Lmym2I.jpg" border="0"></a><br/>

### Expected result

1. When Product Price is Changed Up-sell product price should be $3,299.00

### Actual result

<a href="http://imageshack.com/i/pmCzmXp0p" target="_blank"><img alt="FireShot Pro Screen Capture" src="http://imagizer.imageshack.com/img922/6105/CzmXp0.png" border="0"></a>

<a href="http://imageshack.com/i/porQUr86j" target="_blank"><img alt="FireShot Pro Screen Capture" src="http://imagizer.imageshack.com/img924/7696/rQUr86.jpg" border="0"></a><br/>

**Comment by veloraven** [comment]
@Nehace40 thank you for your report.
We already have internal ticket for this issue - MAGETWO-57044  (for ver. 2.1)
It should be published in ver. 2.1.3 with commit dbfa7b8f7d7107ab178d3f6c6af773777197cadf

**Comment by magento-engcom-team** [comment]
@Nehace40 Closing this ticket for now. Looks like this issue is already fixed in the latest 2.1. Please reopen if you have any further questions.
