### ISSUE TITLE
Reviews not shown in My Product Reviews

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7435]
### Preconditions

1. Magento 2.1.2
2. Developer mode
3. FPC disabled

### Steps to reproduce

1. Register an account and log in
2. Go to /caesar-warm-up-pant.html and write a review
3. Approve the review in Magento Admin
4. Clear all caches
5. Go to My Account / My Product Reviews

### Expected result

1. The review you just submitted should be listed.

### Actual result

1. No reviews are listed; instead, you get the message "You have submitted no reviews."

**Comment by sevos1984** [comment]
Cannot reproduce. Could you try with FPC enabled?

**Comment by thdoan** [comment]
I just tried with FPC enabled and still don't see reviews in My Account. @sevos1984  can you verify that you are able to write a review, approve it in Admin, and see it in My Account?

**Comment by sevos1984** [comment]
I'm able to proceed all described flow. Could you please check magento logs?

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by sinamiandashti** [comment]
its happening for me 
but fixed automaticaly after a priod of time i checked the page again

its re indexing necessary for showing the reviews in product page ? @sevos1984
