### ISSUE TITLE
BlockRepository::getList() SearchResult Items have wrong type

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#7436]
### Preconditions

1. default magento 2 installation (error in latest release and still in develop)

### Steps to reproduce

1. use getList() function of BlockRepository to load CMS Blocks

### Expected result

1. getItems() function returns an array of BlockInterface

### Actual result

1. getItems() function returns an array of associated arrays

https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Model/BlockRepository.php#L164
https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Api/Data/BlockSearchResultsInterface.php#L19

**Comment by mattwellss** [comment]
Will this issue be resolved in 2.1? I see there's a resolution in 2.2...

**Comment by magento-engcom-team** [comment]
@davidverholen, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
