### ISSUE TITLE
[2.1.2]Error css in customer account with Toolbar-amount and mobile design

### ISSUE THREAD

**Issue by quienti** [magento/magento2#7437]
### Preconditions
1. Magento 2.1.2
2. Chrome Version 54.0.2840.87
3. Mobile simulation

### Steps to reproduce
1. Go to Customer account
2. Go to 'My review product' or 'My downloadable product'

### Expected result
1. Toolbar-amount is correctly positioned

### Actual result
1. Toolbar-amount is not correctly positioned

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/20302480/c8535542-ab27-11e6-9789-a59bfe65142c.jpg)

### Possible correction
Remove `position: absolute;` correct this problem

![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/20302508/dfaa6474-ab27-11e6-8cbe-dcfc8404b66e.jpg)

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket created MAGETWO-61092

**Comment by quienti** [comment]
Fixed: https://github.com/magento/magento2/commit/3e35c70fb9f62bd33a6d37696cc0c97cb4655c75
