### ISSUE TITLE
Sometimes the estimation of shipping showed on checkout/cart: Shipping (undefined - undefined)

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#7438]
### Preconditions

1.  I use Magento 2.1.1, php is 5.6.x
2. I use a custom shipping method of myself, which implement shipping charges based upon cart price.

### Steps to reproduce

1. Add a product and then go to checkout
2. Then click on view and edit cart
3. When come to the checkout/cart page it shows Shipping(undefined - undefined)

### Expected result

1. It shows the custom shipping method title and shipping price.

### Actual result

1. Sometimes it shows correct but sometimes it shows "Shipping(undefined - undefined)"

**Comment by SerhiyShkolyarenko** [comment]
@RishabhRkRai the situation you described doesn't look like Magento bug. Please, check what is returned by `rest/default/V1/carts/mine/estimate-shipping-methods-by-address(-id)` service. It will help you to understand which part(server or client) to debug.
I'm closing the issue, but please feel free to create a new one if you find (unmodified) Magento call which returns incorrect data.
