### ISSUE TITLE
Sales Order Payment  is complicated

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#744]
For now this class is very complicated and hard to understand their logic
https://github.com/magento/magento2/blob/master/app/code/Magento/Sales/Model/Order/Payment.php#L1036

**Comment by vpelipenko** [comment]
Ticket: MAGETWO-31585

**Comment by ihor-sviziev** [comment]
Now this class logic looks much better , but now it still contains ~2600 lines of code, I think we may separate class functionality to two or more classes and use delegation. 
I think first of all we should move methods like place, capture, registerCaptureNotification, refund, registerRefundNotification, accept, deny, update, authorize.

**Comment by vpelipenko** [comment]
@ihor-sviziev, when we have time we try to decrease code complexity and re-implement complicated classes in sales/payment infrastructure, but this work doesn't have high priority, that's why we can't promise that suggested refactoring will be done in the near future.

**Comment by vpelipenko** [comment]
@ihor-sviziev, we've done some work around complicated Sales Order Payment. If you compare this class in develop and master branch, you will see that about 400 lines of code were removed from it. Please, look at our changes. All feedback from your side is welcome.

**Comment by ihor-sviziev** [comment]
@vpelipenko now it looks better, but not enough. What I think we should improve:
1. There is a lot of methods have public methods (not public only), that will receive object, but object type is not declared in method. As result we may got not expected method and fatal error if retrieved null. Example methods: pay(), cancelInvoice(), refund(), cancelCreditmemo(), updateBaseAmountPaidOnlineTotal(), _updateTotals(), prepareCreditMemo(), 
2. In few methods we have comaration "==" instead of "===", as result we may have some unexpected behavior. Examples: updateOrder(), _void(), isCaptureFinal(), isSameCurrency(), _getInvoiceForTransactionId(), setOrderStatePaymentReview(), registerRefundNotification(), 
3. This class still contains a lot of getters, setters and business logic (as example place(), pay(), cancelInvoice() ). Would be great move this business logic to some another class(es) and just execute methods (as it done for capture() method).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Sales-Order-Payment-is-complicated/idi-p/47093).
