### ISSUE TITLE
Authorize transactions using a different currency will ALWAYS enter Suspected Fraud

### ISSUE THREAD

**Issue by shaw-tech** [magento/magento2#7440]
### Preconditions

1. Magento 2.1 
2. A payment method which will AUTHORIZE only e.g. For Braintree:

![image](https://cloud.githubusercontent.com/assets/23167920/20305340/f6e8aede-ab2c-11e6-80f2-a50c5d046fd5.png)

3. Have an additional Allowed Currency on the frontend. E.g. for my testing I have a base currency of USD and an allowed currency of USD and GBP.

### Steps to reproduce

1. Use the currency switcher to change currency from your base currency to another one. E.g. in my case I switch from USD to GBP.
2.  Add a product to your basket and complete the checkout process using a card which will result in a successful authorisation.

### Expected result

1. The order should enter the Processing state
2. There should be a line in the order comment history which says something like "The transaction has been authorised for $X

### Actual result

1. The order moves into Suspected Fraud state.

### Additional information
This is because in vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php:31 you have the following check:

    if (!$isSameCurrency || !$payment->isCaptureFinal($amount)) {
        $payment->setIsFraudDetected(true);
    }

And $payment->isCaptureFinal($amount) has the following implmentation:

    public function isCaptureFinal($amountToCapture)
    {
        $total = $this->getOrder()->getTotalDue();
        return $this->formatAmount($total, true) == $this->formatAmount($amountToCapture, true);
    }

Where `$amountToCapture` is in the base currency and `$total` is in the order currency, so they will never match up!

**Comment by viktym** [comment]
Hi @shaw-tech 
I’m closing this issue because it is a duplicate https://github.com/magento/magento2/issues/4263 . Please reopen this issue as needed.
Thanks for reporting.
