### ISSUE TITLE
Credit Card type not showing in admin order section for magento 2.1.0

### ISSUE THREAD

**Issue by aqua456** [magento/magento2#7444]
Credit cart type not showing in admin->sales->orders->payment information section.

I checked the core code module-payment/Block/Info/Cc.php and in _prepareSpecificInformation() function it seems that $this->getCcTypeName() is called. But the control is not going to that function. I tried by renaming the function getCcTypeName() to getCcTypeNames() and changed $this->getCcTypeName() to $this->getCcTypeNames() and now it is showing Card type. Could you please help to rectify this.

### Preconditions
1. Magento 2.1.0
2. Linux ubuntu

### Steps to reproduce
1. Make checkout thorugh paypal credit card
2. Go to admin->sales->orders->view->Payment information

### Expected result
1. Credit card type will be shown

### Actual result
![capture](https://cloud.githubusercontent.com/assets/23484609/20319826/953a9b0c-ab95-11e6-8273-e85be1fd2738.PNG)

1. Credit card type is not showing

**Comment by jbpilatre** [comment]
look my post encrypt /decrypt ccsave module (cc)  #7334 
https://github.com/magento/magento2/issues/7334

**Comment by aqua456** [comment]
#7334 seems to be for credit card number not for credit card type(Visa, American express etc.)

**Comment by aqua456** [comment]
Did anyone find a solution for this

**Comment by dyushkin** [comment]
Hi @aqua456!

I have found few classes, which override Magento\Paypal\Block\Payment\Info::getCcTypeName method, and return false:
- Magento\Paypal\Block\Payflow\Info
- Magento\Paypal\Block\Hosted\Pro\Info
- Magento\Paypal\Block\Payflow\Link\Info

So if you want to display card type for CC PayPal payment methods, you just need to fix getCcTypeName() method in this classes.

Thank you for reporting, we have created internal ticket MAGETWO-63573. If you have more question, feel free to reopen this issue.
