### ISSUE TITLE
Can't remove "Set Product as New From" value

### ISSUE THREAD

**Issue by sigismund** [magento/magento2#7448]
Once "Set Product as New From" value is set it can not be removed. It can be disabled by setting "To" value, but that value still persists in database. The main problem is, that whenever I change any attribute of the product, the product is set as "New".
I didn't test this on any other version of Magento than mine (2.1.2).

### Preconditions
1. Magento 2.1.2
2. PHP 7
3. MySQL 5.6

### Steps to reproduce

1. Under Catalog > Product > Select any product
2. Set "Set Product as New From" value and Save
3. After trying to change this value, it can't be removed.

### Expected result

1. When date is removed it shouldn't exists or at least it should set To date, so the "New" option is disabled.

### Actual result

1. When date is removed it is re-set to current date.
2. This is specially annoying when we just want to change product's stock and date is changed to current date.

**Comment by sigismund** [comment]
After some research I came to conclusion that this issue is duplicate of issue #4387.

**Comment by olysenko** [comment]
Hi @sigismund, thank for your report. I increase priority for  #4387 fix issue. Your report will be fixed with #4387 . So I closed this as an duplicate

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72252

**Comment by ndslindia** [comment]
What is the solution for this behaviour ?? My magento 2.1.8 too has this issue. Unable to remove "Set Product as New From" on product edit >> save.
