### ISSUE TITLE
Feature request: Support for PostgreSQL

### ISSUE THREAD

**Issue by paales** [magento/magento2#745]
In the light of the new Postgres 9.4 features: indexed JSONB, wouldn't it be awesome if Magento supported it.

- JSONB (brought into mainline in 9.4) -> Ideal replacement for flat tables, performance is on par (or better) than MongoDB.
- Flexible full-text search (brought into mainline in 8.2) -> Ideal for a simple search when SOLR is too much
- Multiple replication options to suit your environment and requirements
- Uses multi-version concurrency control, so concurrent performance rocks
- Fully ACID compliant (innodb is as well)
- Well-documented
- Strong access-control framework
- [Materialized Views](https://wiki.postgresql.org/wiki/Materialized_Views)

There are probably a 1000 more features that I can't think of, but I think you get the point. I understand Magento would like to support MySQL as well because it is more entry level and Magento has some abstract resource methods which should support other databases, but in practice Magento currently only supports MySQL. Better official support and feature integration would be awesome.

**Comment by choukalos** [comment]
I'm tracking some platform epics around introducing a new data access layer later after Magento 2.0 is released.  It's way down there in the backlog; we'd add services & refactor before doing that as that would minimize the disruption of adding a new data access layer to the system to the ecosystem.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31586

**Comment by seanmindarc** [comment]
@vpelipenko Is there anywhere we can see the progress of this internal ticket inside the Magento Partners portal? - MAGETWO-31586

**Comment by zh99998** [comment]
+1 for this request

**Comment by ppKrauss** [comment]
+1 for this request!

PS: [PostgreSQL 9.5 have JSON and JSONB mature support](http://www.postgresql.org/docs/current/static/functions-json.html), so not need other "noSQL" support.

**Comment by ppKrauss** [comment]
@alankent, how to start a _"task force"_ to start this "Doctrine or direct SQL adaptations"? 

PS: even if slowly, we, the interest-group, can start something... Even if very slowly, will be better to do nothing!  ;-)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Support-for-PostgreSQL/idi-p/47343).

**Comment by Vigneshmuthusamy** [comment]
Ah, man. it's been 7 years and is still on the roadmap. I don't see any light at the end of the tunnel.

**Comment by ppKrauss** [comment]
> Ah, man. it's been 7 years and is still on the roadmap. I don't see any light at the end of the tunnel.

Sorry, see the README page, it's not "very open", it is oriented to Adobe, a former [anti-competitive](https://en.wikipedia.org/wiki/Adobe_Inc.#Anti-competitive_practices) and anti-FOSS company.

**Comment by MagePsycho** [comment]
I'd be thrilled to have this, as it would make avoiding MySQL distributions much easier.  
By the way, is there any update on this feature request?

**Comment by rostilos** [comment]
2025. We wait, we hope, we believe ❤

**Comment by frankpinto** [comment]
At this point one of us should just write it, we have generative AI now

**Comment by MagePsycho** [comment]
This would be a game changer for Magento world! Awaiting...
