### ISSUE TITLE
Magento pages, blocks, customers, products not displaying

### ISSUE THREAD

**Issue by bjornharvold** [magento/magento2#7450]
### Preconditions

1.  DigitalOcean Magento droplet w Magento v2.0.7. 2Gb RAM

### Steps to reproduce
1. Go to Content > Pages
2. All pages that do a secondary AJAX call to retrieve either pages, blocks, customers or products are successfully retrieving the content but nothing gets displayed.
2. Tested on all the latest browsers

### Expected result
1. Content for each of these pages should display

### Actual result
1. Nothing happens. Empty page. See attached.
<img width="1248" alt="pages___elements___content___magento_admin___starringmay_com" src="https://cloud.githubusercontent.com/assets/641791/20345849/99862b04-ac2b-11e6-8316-ede91b208be2.png">

**Comment by luismaldonadov** [comment]
I'm having the same problem, my problem is after a fresh install, cant seem to modify any parameters related with the database, but cache management and some other things seem to work well.

**Comment by bjornharvold** [comment]
Upgraded to v2.1.2 and still see the same problem. Installed the latest version of PHP v7.0.13 as well.

**Comment by bjornharvold** [comment]
No errors in the logs either

**Comment by luismaldonadov** [comment]
For me it was a matter of file and directory permissions. Hope that this could help.

**Comment by bjornharvold** [comment]
Hi, can you please be more specific. I am using Magento's suggested directory and file permission scheme here: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by bjornharvold** [comment]
<img width="1280" alt="pages___elements___content___magento_admin___starringmay_com" src="https://cloud.githubusercontent.com/assets/641791/20549220/fcbca442-b15c-11e6-90fe-8569b9ed48af.png">

**Comment by bjornharvold** [comment]
On Firefox WebDeveloper edition I actually see some badly formatted html. I don't see anything on any other browser. Looking in the Firebug console gives me no indication that anything is wrong.

**Comment by luismaldonadov** [comment]
Indeed the issue was caused by incorrect permissions of your site's files and folders, although the ownership was correct. 

I have updated the permissions on my end, using the following two commands over SSH:
Code:
luism342@m78 [~/public_html]# find . -type d -exec chmod 755 {} \;
luism342@m78 [~/public_html]# find . -type f -exec chmod 644 {} \;

**Comment by bjornharvold** [comment]
That did not work for me. It actually broke the install and prevented me from accessing the site. My user and group is magento:www-data for all files and directories. Maybe this differs on your system

**Comment by miakusha** [comment]
Hi @bjornharvold, I cannot reproduce issue. Just now I successfully installed Magento 2.0.7 via  
One-click apps on DO and all content correctly displayed. 
Please reopen as needed.
