### ISSUE TITLE
JSON resultFactory renders empty response

### ISSUE THREAD

**Issue by timneutkens** [magento/magento2#7451]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.6
3. Percona 5.6 (Not relevant)

### Steps to reproduce
```
$result = $this->resultJsonFactory->create();
$result->setData($bigArrayFilledWithEntities);
return $result;
```

### Expected result
JSON should be rendered.

### Actual result
JSON result factory renders empty response when you set a big array of data, for example multiple products that have a long long description.

This is caused by this line: https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Translate/Inline.php#L245

The preg replace is executed on the encoded JSON body, but the JSON string is way longer than the maximum regex input (`pcre.backtrack_limit`). Which causes the regex to return null.

I'm pretty sure doing this kind of regex on the whole output is not feasible, especially on JSON that will never use the inline translator.

#### Temporary fix
Temporarily increase pcre.backtrack_limit

**Comment by magento-engcom-team** [comment]
@timneutkens, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by francesco-di-marcantonio** [comment]
Same on Magento 2.4.6
