### ISSUE TITLE
central cli entry point

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#746]
The adding of console script is currently not modular in magento, causing modules which add new scripts to not think much about form and name of the scripts they add.

Possible Problems from the current State:
* name collisions on file level
* mixing of one script, one script with many actions, multiple scripts for a module, a directory with multiple scripts

A suggestion how it could look, Symfony only has a single console.php, which serves as entry point for every part of the Application.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31596

**Comment by choukalos** [comment]
Converted to an epic we're tracking internally MAGETWO-32719; changing assignment since I'm the owner of the epic.

**Comment by mbrinton01** [comment]
Changing internal owner for this issue

**Comment by mbrinton01** [comment]
Internal link to epic: https://jira.corp.x.com/browse/MAGETWO-32719

**Comment by Flyingmana** [comment]
this github issue could be closed as my requirements are fulfilled trough https://github.com/magento/magento2/blob/0.74.0-beta12/bin/magento and https://github.com/magento/magento2/tree/0.74.0-beta12/lib/internal/Magento/Framework/Console

Is it safe to close Issues opened by myself or would this affect referenced internal epics like MAGETWO-32719; in this case?

**Comment by vpelipenko** [comment]
Closed. @Flyingmana, you can safely close issue opened by yourself in case if it is implemented or in case when you decide that it already doesn't have sense. In another case it can change our priority and there is no guarantee that issue will be fixed.
