### ISSUE TITLE
Catalog Rule price isn't included in Catalog price Index

### ISSUE THREAD

**Issue by maqlec** [magento/magento2#7465]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Set Catalog Rule discount on product in some category
2. Set Special Price on other product in category from point 1
3. Run indexers
4. Try to sort products category list by price.

### Expected result

1. Category list should be sorted by final price including catalog rule price

### Actual result

1. Product with catalog rule price has displayed with discount but sorted by base price 
2. Product with special price has displayed with discount and sorted well.

Catalog Rule prices aren't included in "catalog_product_index_price" table. Category list is building based on this table.
I don't know is it good behavior. Please tell me if I'm wrong.

**Comment by olysenko** [comment]
Hi,thank you for your report, internal ticket was created MAGETWO-61277

**Comment by lucscu** [comment]
@olysenko Any update?

**Comment by magento-engcom-team** [comment]
@maqlec, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by maciekp2** [comment]
Any update on this issue? It's still not fixed in 2.2.x...

**Comment by afoucret** [comment]
Confirm not fixed in 2.2.x

**Comment by sedax90** [comment]
Confirm the issue in 2.2.2... is possibile to have a patch?

**Comment by ShuklinAM** [comment]
Not fixed in 2.2.2

**Comment by johnny-longneck** [comment]
Closed a not fixed ticket? 
Can confirm in 2.2.3.

**Comment by ShuklinAM** [comment]
Can confirm that still not fixed in 2.2.3

**Comment by PublicV0id** [comment]
I have the same issue in 2.2.2

**Comment by arioch1984** [comment]
Hi!
I had the same problem on a 2.1.13.
May this help? 
https://github.com/borasocom-team/module-catalog-rules-list-fix
