### ISSUE TITLE
Apple Pay and Android Pay support

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7466]
I am developing a bespoke custom gateway and it has different methods if you are checking out using apple pay/android pay. Is there plans for a framework to be added to m2 to determine that you are using apple/android pay?

**Comment by veloraven** [comment]
@craigcarnell thank you for you feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
