### ISSUE TITLE
Magento 2.1.0.0  new order email template preview  and save  404 not found issue

### ISSUE THREAD

**Issue by mithname20** [magento/magento2#7470]
Hi in my site when i load new order email template it shows error and Error message appears: The template did not load. Please review the log for details

I updated the line "var order.getShippingDescription()":"Shipping Description", with a comma "," at the end as suggested in some support pages to resolve the template load issue. Now i can load new order email template but the measure problem is that when i click to preview template or save template it goes a 404 page and nothing happen.

Some support page are saying to Install Magento 2.1.0-rc3 using composer.

What stand for Magento 2.1.0-rc3 and where i can get it download and install or there is any other option to resolve this issue . i want to keep the megento 2.1.0 version for my website.

Please reply with the correct solution .

**Comment by veloraven** [comment]
@mithname20 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please format this report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by mitulispace** [comment]
404 error: Page not found.
same issue

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by gagandeep-cueblocks** [comment]
404 error: Page not found.
same issue

**Comment by younkim** [comment]
Still happens on 2.1.3.

**Comment by gagandeep-cueblocks** [comment]
The issue is related to modsecurity please get it fixed from the server team. I got it fixed the same way.
