### ISSUE TITLE
No multi currency support in google analytics module

### ISSUE THREAD

**Issue by sam-g-roberts** [magento/magento2#7471]
There is currently no support for multi currency in the magento google analytics module. It's a 1 minute change and should really be included as default as most stores will use Google analytics and if they have multiple currencies not having multicurrency support will skew their data.

In the google analytics module block Ga.php the below needs to be changed from

```
            $result[] = sprintf(
                "ga('ec:setAction', 'purchase', {
                    'id': '%s',
                    'affiliation': '%s',
                    'revenue': '%s',
                    'tax': '%s',
                    'shipping': '%s'
                });",
                $order->getIncrementId(),
                $this->escapeJsQuote($this->_storeManager->getStore()->getFrontendName()),
                $order->getBaseGrandTotal(),
                $order->getBaseTaxAmount(),
                $order->getBaseShippingAmount()
            );
```

to

```
            $result[] = sprintf(
                "ga('ec:setAction', 'purchase', {
                    'id': '%s',
                    'affiliation': '%s',
                    'revenue': '%s',
                    'tax': '%s',
                    'shipping': '%s',
                    'currency': '%s'
                });",
                $order->getIncrementId(),
                $this->escapeJsQuote($this->_storeManager->getStore()->getFrontendName()),
                $order->getBaseGrandTotal(),
                $order->getBaseTaxAmount(),
                $order->getBaseShippingAmount(),
                $order->getOrderCurrencyCode()
            );
```

**Comment by veloraven** [comment]
@sam-g-roberts thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by sam-g-roberts** [comment]
Magento version is github develop version

You haven't included the google analytics multi currency paramater when sending off a conversion to google analytics.

In this file https://github.com/magento/magento2/blob/develop/app/code/Magento/GoogleAnalytics/Block/Ga.php

lines 130-143 need to be replaced with the below code

```
$result[] = sprintf(
                "ga('ec:setAction', 'purchase', {
                    'id': '%s',
                    'affiliation': '%s',
                    'revenue': '%s',
                    'tax': '%s',
                    'shipping': '%s',
                    'currency': '%s'
                });",
                $order->getIncrementId(),
                $this->escapeJsQuote($this->_storeManager->getStore()->getFrontendName()),
                $order->getBaseGrandTotal(),
                $order->getBaseTaxAmount(),
                $order->getBaseShippingAmount(),
                $order->getOrderCurrencyCode()
            );
```

This means when orders in different currencies go through to google analytics they will not get put in as those different currencies

**Comment by veloraven** [comment]
@sam-g-roberts thank you for update.
But I have to ask you once more to describe this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
You can leave the description and previous comment as they contain valuable information. But please add one more comment with exact steps to reproduce the issue instead of how to fix it.
Like:
**Steps:**
1. Do this action as admin
...
5. Do that action as customer
...
10. Check these values ...

**Actual result:**
* values are ...

**Expected Result:**
* values shoukd be ...

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @sam-g-roberts please feel free to write here/reopen or to open new issue

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71539
