### ISSUE TITLE
TableRates shipping amount not being displayed in Order Creation from admin backend

### ISSUE THREAD

**Issue by andreaschiffo** [magento/magento2#7472]
im using M 2.0.9, and Table Rates is correctly being displayed on frontend, but i'm finding this issue with Table Rate shipping method on admin backend: 

## Preconditions

-having a multistore website
-having enabled tablerates shipping method, price vs destination, not including virtual products in price calculation, no handling fee, for all allowed countries, not showing if not applicable
-(optional) having configured another shipping method (custom extension MatrixRates in my case)

## Steps to reproduce

create a new order from admin backend (doesnt depend wich store or customer you choose, just be careful to insert some data that is good for TableRates shipping), add some simple products, hit the Get shipping methods and rates link

## Actual Result

Table Rates shipping option/cost will not be displayed

## Expected Result

Table Rates shipping option/cost being displayed with amount

## Additional notes
IMHO, having researched for some time, the problem may be in magento\module-offline-shipping\model\carrier\tablerate, precisely under the collectRates method
if we dont have any virtual products, we will rely on $request->getPackageValue() to calculate the order amount and then fetch the Table Rate Shipping configuration, but the problem is that $request->getPackageValue() returns 0 in this phase, and this doesn't allow a proper comparation with the configuration

as a patch i've developed a plugin recalculating the Package Value to make sure it is >0

**Comment by sam-g-roberts** [comment]
We also had this issue and mentioned it to Enterprise support. They're supposedly aware and looking into the issue.

**Comment by danipolo** [comment]
same situation here, just exact like this.

**Comment by SerhiyShkolyarenko** [comment]
@andreaschiffo @danipolo could you please attach tablerates.csv file you use, exact price of product(s) and more order details to make sure we do the same?

**Comment by andreaschiffo** [comment]
[rates_4_serhiy.zip](https://github.com/magento/magento2/files/621639/rates_4_serhiy.zip)

@SerhiyShkolyarenko here you are
the price of the products doesn't matter, you can select any product for any amount

-make sure in order creation you proceed selecting one of the multiple stores, after choosing the customer
-order total should be above 49 eur, infact tablerates is configured for free shipping for orders above 49 eur (for given configuration)
-table rates configuration that i attached refers to italian provinces so maybe you should try a test with country/region matching corresponding configuration in the csv file

**Comment by SerhiyShkolyarenko** [comment]
@andreaschiffo how should I import that tablerates.csv? I've got an error for each row that region not found.
Additional question: Is your table rate shipping method disabled on the global scope but enabled on the website scope?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by Sharmilasrini95** [comment]
Is there any possible to import multiple countries with comma(,) separator in single entry in table rate csv?

**Comment by sudheer-gajjala** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @sudheer-gajjala. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by engcom-Bravo** [comment]
High there. The issue is not reproducible on the latest 2.3-develop version:
![TR](https://user-images.githubusercontent.com/51680745/64851687-92b2ce00-d620-11e9-95f6-34a8df342012.gif)
So I'm closing it for now.

**Comment by rajatkar104** [comment]
> High there. The issue is not reproducible on the latest 2.3-develop version:
> ![TR](https://user-images.githubusercontent.com/51680745/64851687-92b2ce00-d620-11e9-95f6-34a8df342012.gif)
> So I'm closing it for now.

The shared screenshot is related to frontend. We are facing issue while creating Magento Admin with multi store. Please check the issue title "TableRates shipping amount not being displayed in Order Creation from admin backend"

**Comment by engcom-Bravo** [comment]
Here You are @rajatkar104:
![backend](https://user-images.githubusercontent.com/51680745/64864328-85590c00-d63f-11e9-89f4-944b437330da.gif)
Do You take into consideration You need to load csv for each website separately? For example, I had  loaded csv only for Main Web Site. So if I tried to create an order with the customer on another website I wouldn't have Table Rate shipping method being displayed among the other shipping methods:
![anothersite](https://user-images.githubusercontent.com/51680745/64864870-b259ee80-d640-11e9-9036-14b46cd6d5d4.gif)

**Comment by drb-services** [comment]
Hi - I'm having the same issue.
It does work in the default Website/Store in a multistore environment but not in any other sites.
@engcom-Bravo can you please check and verify in an other non-default website?

**Comment by engcom-Bravo** [comment]
Hi @drb-services. Unfortunately I'm not working on the project anymore. Please try to open a new issue if You are still able to reproduce it on 2.4-develop as now Magento team excepts only issues reproduced on that version.
