### ISSUE TITLE
Fax Field is not working

### ISSUE THREAD

**Issue by springimport** [magento/magento2#7477]
### Steps to Reproduce Bugs
1. Go to `/customer/address/edit/` and type any numbers in the `Fax` field.
2. Go to `/admin_xxxxxx/customer/index/edit/id/xxx/.....`.

### Actual result
1. `Fax` in customer account does not save.
2. `Fax` in admin panel (customer addresses) does not show.

| Q | A |
| --- | --- |
| Magento version | 2.1.2 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by sevos1984** [comment]
This ticket duplicates https://github.com/magento/magento2/issues/6158. Closing
