### ISSUE TITLE
2.2.0-dev cart price rule calendar doesn't work properly

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#7479]
### Preconditions

1. 2.2.0-dev
2. 

### Steps to reproduce

1. create a new cart price promo
2. select a from to date.
3. save promo

### Expected result

1. Dates should be whatever you picked.

### Actual result

1. dates switched to the future for both initially.

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue MAGETWO-62195 was created

**Comment by veloraven** [comment]
This issue was fixed in scope of internal ticket MAGETWO-59718.
Closed.
