### ISSUE TITLE
Im already using CentOS 6.8 with Magento 2.1....but im still getting the ssl connect error ?

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7480]
Im trying to connect Magento market place to magento2 through web setup wizard...but having ssl connect error..
![magento2](https://cloud.githubusercontent.com/assets/12715229/20416639/c8b3beda-ad72-11e6-8930-a1bb1061a0a7.PNG)

**Comment by veloraven** [comment]
@SaaqibBhat thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also specify exact Magento version you are running.
Please describe your environment: OS, versions of PHP, MySQL, web-server.

**Comment by ghost** [comment]
Thanks hearing from you. here are the details. this issue still exists
**Title**
Unable to sign in to my magento market place account from Web Setup Wizard.

**Preconditions**
1. installed magento 2.1.2, via web installer without data
2. created market place account with my keys, following this link (http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html)

**Steps to reproduce**
1. System -->web Setup Wizard -->Component Manager
2. Signed in via my access keys public & private
**Actual and Expected result**
i am expecting Sign in and to sync my Magento Marketplace purchases. 
but im getting SSL connect error

**Additional information**
My environment includes:
OS:  CentOS 6.8
PHP: 7.0.13
MySQL: mysql 5.6.34
web-server: apache 2
Magento version: 2.1.2

![access key](https://cloud.githubusercontent.com/assets/12715229/20586681/ea403e6e-b238-11e6-9c80-dd2f1c861a64.PNG)

**Comment by vityakopin** [comment]
Thanks for reporting. Unfortunately, I could not reproduce the issue as you described it. Please identify the version of curl (running 'curl --version' in your CLI). Also provide is it clean install of Magento or upgrade from  previous version?

**Comment by magento-engcom-team** [comment]
@SaaqibBhat please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
