### ISSUE TITLE
Connecting Component Manager Magento 2.1.2 CE with Marketplace Account brings error but not visible

### ISSUE THREAD

**Issue by afrinnusrat** [magento/magento2#7482]
### Preconditions

1. Magento 2.1.2 CE
2. Fresh Install, no other configuration were made 

### Actual result
1. An error appears interrupting the sign in process but not visible.
Please see the screenshot attached below
![magento2marketplace](https://cloud.githubusercontent.com/assets/8726007/20421259/c3a880a4-ad88-11e6-91b7-d87e2a0c64d6.png)

**Comment by shiftedreality** [comment]
Hi @afrinnusrat 

I was unable to reproduce this on 2.1.2 CE.
Please, provide your environment configuration details.

Note: We do not support Windows machines for now, so I suggest you use Vagrant or Docker.

**Comment by vzabaznov** [comment]
Hi @afrinnusrat , close this issue as we don't receive update for more than 2 weeks, please feel free to write here or reopen current / create new issue
