### ISSUE TITLE
[M2.1.1]: Bundling breaks the JS path and throws uncaught-reference error

### ISSUE THREAD

**Issue by apurv-anand** [magento/magento2#7486]
**[M2.1.1]: Bundling breaks the JS path and throws uncaught-reference error**

Environment:
M 2.1.1
Ubuntu
Apache2
Varnish (FPC)

Bundling / Merging / Minify for JS and CSS enabled.

Steps:
- Start with a Magento 2.1.1 server.
- Install and enable few of the modules needed for your site.
- Make sure they are working (js / css files work as expected).
- Enable bundling / merging / minify for js and css.

Current behavior: The module that were working earlier their js starts throwing uncaught-reference error.

Expected: The modules should work even after all 3 options are set to YES.

More information: Just disabling bundling would let the modules work again.

Few errors that we see:
<somepage>.html:985 Uncaught ReferenceError: resetZipcode is not defined(…)onfocus @ <somepage>.html:985

Uncaught ReferenceError: keyEventhandle is not defined(…)onkeypress @ <somepage>.html:985
<somepage>.html:985 Uncaught ReferenceError: keyEventhandle is not defined(…)onkeypress @ <somepage>.html:985

**Comment by atul-nit** [comment]
When I enabled the javascript bundling option from configuration, few jquery functions stopped working.
The jquery file was added using requirejs. In console the error message was that "function is not defined".
When I disable the js bundling option everything starts to work perfectly.

**Comment by apurv-anand** [comment]
More info:
We are on production mode and static content was deployed after making the changes.

**Comment by sjauck** [comment]
Same problem with 2.0.11

**Comment by magento-engcom-team** [comment]
@apurv-anand, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9
