### ISSUE TITLE
[Feature Request] Unified Method for Handling Custom Checkout Field Data

### ISSUE THREAD

**Issue by dreucifer** [magento/magento2#7487]
As it currently stands there is no good way to handle custom checkout fields. Adding the fields is simple (and well documented), but retrieving and storing data from those fields is tricky (and completely undocumented). Most methods I have found revolve around hooking into the `shipping-information` REST target and adding columns to `quote`.

I think a universal 'update-information' REST target would make it easier to decouple custom checkout fields from shipping address data. It also creates a convenient target for sending custom checkout step data.

**Comment by veloraven** [comment]
@dreucifer thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @dreucifer please feel free to write here/reopen or to open new issue
