### ISSUE TITLE
MAGENTO 2 Undefined index: store_id /Store.php on line 82

### ISSUE THREAD

**Issue by Rasmussim** [magento/magento2#7489]
First of all. I'm new on this side so please bear with me. 
And sorry for my bad english.

After deleting the original sides which my themplate in magento 2.0.7 was borne with. this problem came up:

_Notice: Undefined index: store_id in /var/www/magento/public_html/vendor/magento/module-store/Ui/Component/Listing/Column/Store.php on line 82_

Reindexing does not fix it. I have read something about that I maybe can change it in MYSQL. but i don't know how. 

Can any of you maybe help me?

Thank you in advance :)

**Comment by veloraven** [comment]
@Rasmussim thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result, expected result. Please also specify Magento version you are running (do I understand correct that the version is 2.0.7?).

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @Rasmussim please feel free to write here/reopen or to open new issue
