### ISSUE TITLE
Billing Agreement Page Error

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#7490]
Clicking on Billing Agreement link in customer dashboard throws an Uncaught error.
### Preconditions
Magento 2.1.2

### Steps to reproduce
1. Navigate to frontend
2. Sign in as customer
3. Go to customer dashboard
4. Click on Billing Agreements Link
### Expected result
View Billing Agreement

### Actual result
Uncaught error is thrown

Fatal error: Uncaught Error: Class 'BraintreePayPalVaultFacade' not found in /home/tuckersf/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:84 Stack trace: #0 /home/tuckersf/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('BraintreePayPal...', Array) #1 /home/tuckersf/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('BraintreePayPal...', Array) #2 /home/tuckersf/public_html/vendor/magento/module-payment/Model/Method/Factory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('BraintreePayPal...', Array) #3 /home/tuckersf/public_html/vendor/magento/module-payment/Helper/Data.php(138): Magento\Payment\Model\Method\Factory->create('BraintreePayPal...') #4 /home/tuckersf/public_html/vendor/magento/module-paypal/Helper/Data.php(96): Magento\Payment\Helper\Data->getStoreMethods(NULL, NULL) #5 /home/tuckersf/p in /home/tuckersf/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 84

On the off chance this isn't a bug, please point me in the right direction to solve this.

**Comment by YevSent** [comment]
Hi @Ctucker9233, do you have customizations in your Magento code? Magento 2.1.2 doesn't have Vault implementation for Braintree PayPal. So, you code should not have any references to `BraintreePayPalVaultFacade`.

**Comment by Ctucker9233** [comment]
@alena-marchenko @joni-jones You are correct. I don't know how it ended up in my code, but I have been patching my code base with merged commits for other issues I have had. This bit of code must have been in one of those. I have since reverted those changes and it seems the problem is resolved. I will close this for now and if the problem reappears, I will re-open.
