### ISSUE TITLE
Blank page instead of setup

### ISSUE THREAD

**Issue by Naxon** [magento/magento2#7492]
### Preconditions

1. Magento 2
2. PHP 7.0.11, Nginx

### Steps to reproduce

1. Enter setup.
2. 
3. 

### Expected result

Setup wizard
### Actual result

1. [Screenshot, logs]
http://www.screencast.com/t/EHe2lTii6W0
I see a blank page instead of the setup wizard.

**Comment by veloraven** [comment]
@Naxon thank you for your feedback.
Please specify exact Magento version you are running.
Please also provide information about your OS and MySQL version.
Are there any errors present?

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @Naxon please feel free to write here/reopen or to open new issue

**Comment by thanasisgalanis** [comment]
Check you apache erro_log file, if you find a record with mention to **_setup_** folder or **_setup/index.php_** file _**is writable by the group**_

You might, set **_setup_** folder and **_setup/index.php_** file permission, to be 755 and 644 respectively.

**Comment by dharake** [comment]
Hi there, 

Found the solution elsewhere. 

Changed nginx.conf.sample /setup location block to:

location /setup {
    root $MAGE_ROOT;
    location ~ ^/setup/index.php {

        ### This fixes the problem:
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        ################################

        fastcgi_pass   fastcgi_backend;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ ^/setup/(?!pub/). {
        deny all;
    }

    location ~ ^/setup/pub/ {
        add_header X-Frame-Options "SAMEORIGIN";
    }
}

**Comment by Jeeva-Rathinam** [comment]
Does anyone get a solution?
