### ISSUE TITLE
Validate HTML has many errors

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#7493]
### Preconditions

1.  PHP 7.0.10
2. MySQL 5.6+

### Steps to reproduce

1. Install magento 2.1.2 with sampledata
2. Add new Grouped Product
3. Validate HTML on Home Page https://validator.w3.org/nu/
4. Validate HTML on Category Product https://validator.w3.org/nu/
5. Validate HTML on Grouped Product https://validator.w3.org/nu/
### Expected result

1. Validate HTML without error

### Actual result

Validate HTML has many errors:

Home Page and Category Product:
```
Error: The itemprop attribute was specified, but the element is not a property of any item.
From line 904, column 139; to line 904, column 224
ct-id="9"><div class="price-box" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

Error: Attribute attribute-code not allowed on element div at this point.
From line 1518, column 81; to line 1519, column 46
-content"><div class="swatch-attribute swatch-layered size"↩     attribute-code="size" attribute-id="142">

............................     
```

Grouped Product::
```
Error: Attribute maxlength is only allowed when the input type is email, password, search, tel, text, or url.
From line 654, column 17; to line 661, column 25
          <input type="number"↩                       name="qty"↩                       id="qty"↩                       maxlength="12"↩                       value="1"↩                       title="Qty" class="input-text qty"↩                       data-validate="{&quot;required-number&quot;:true,&quot;validate-item-quantity&quot;:{&quot;minAllowed&quot;:1}}"↩                       />

...........................
```

Note: "Error The itemprop attribute was specified, but the element is not a property of any item"
need solve first, because it related Google Rich Snippets

**Comment by dmitriyprime** [comment]
We've created internal ticket MAGETWO-70058 to address this issue.

**Comment by magento-engcom-team** [comment]
@minhluan259, thank you for your report.
We've created internal ticket(s) MAGETWO-70058 to track progress on the issue.

**Comment by victor-martinez87** [comment]
Can you assign me this ticket please? #mmes

**Comment by victor-martinez87** [comment]
Can't reproduce the same issues, it's true that some HTML codel is not 100% validating by https://validator.w3.org/nu/, giving some warnings.

**Comment by minhluan259** [comment]
@victor-martinez-interactiv4 
Itemprop  issue: may be this link can help you 
https://stackoverflow.com/questions/36918465/itemprop-errors

Attribute code issue: I suggest change `attribute-code="size"` to `data-attribute-code="size"`

Can you show the warning of w3?

**Comment by magento-engcom-team** [comment]
Hi @minhluan259

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@minhluan259, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
