### ISSUE TITLE
Grammar Mistake: You don't subscribe to our newsletter.

### ISSUE THREAD

**Issue by abi2** [magento/magento2#7498]
In Dashboard if didn't subscribe to a newsletter it says:
You don't subscribe to our newsletter.

In English grammar it should say:
You haven't subscribed to our newsletter.

Files to change:
https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Customer/view/frontend/templates/account/dashboard/info.phtml Line 176
https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Customer/Block/Account/Dashboard.php Line 4

Thank You!

**Comment by veloraven** [comment]
@abi2 thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by abi2** [comment]
Steps to reproduce:

1. Magento 2.1.2
2. Customer creates an account
3. Customer does not subscribe to newsletter
4. Customer logs in to dashboard

Expected result:
You haven't subscribed to our newsletter.
Actual result:
You don't subscribe to our newsletter.

**Comment by roman-snitko** [comment]
The same goes for the phrase "You subscribe to our newsletter"

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67042
