### ISSUE TITLE
not able to override collapsible.js

### ISSUE THREAD

**Issue by rramiii** [magento/magento2#7501]
### Preconditions

1.  Magento EE 2.1.1
2. php 7.0.8

### Steps to reproduce

try any of the following scenarios:
**Scenario A:**

- created following file: namespace_module_dir/view/frontend/web/js/collapsible-mixin.js

```
define([
    'jquery'
], function ($) {
    'use strict';
    var mixin = {
        activate: function () {
            if (!this.options.disabled) {
                if (this.options.animate) {
                    this._animate(showProps);
                } else {

// my custom code goes here ...
                    this.content.show();
                }
                this._open();
            }
        }
    };

    return function (target) {
         return target.extend(mixin);
    };

});
```

- created requirejs-config file: namespace_module_dir/view/frontend/requirejs-config.js

```
var config = {
    config: {
        mixins: {
            'mage/collapsible': {
                '<namespace_module>/js/collapsible-mixin': true
            }
        }
    }
};
```

**Result A:**
in browser inspector, following error:
Uncaught TypeError: target .extend is not a function(...)

**Scenario B:**

- created requirejs-config file: namespace_module_dir/view/frontend/requirejs-config.js
```
var config = {
    map: {
        '*': {
            collapsible: '<namespace_module>/js/collapsible-map'
        }
    }
};
```

**Result B:**
regardless what is the content of collapsible-map.js, it's not getting loaded (collapsible-map.js file is created) even thought I can see my requirejs-config.js content in the auto generated requirejs-config.js file by magento and the defalut magento collapsible.js file is loaded.

**Scenario C:**

- created following file: namespace_module_dir/view/frontend/web/js/collapsible-map.js
```
define([
    'jquery',
    'jquery/ui',
    'mage/collapsible'
], function ($) {
    "use strict";
    $.widget('<namespace_module>.collapsible', $.mage.collapsible, {
        activate: function () {
            if (!this.options.disabled) {
                if (this.options.animate) {
                    this._animate(showProps);
                } else {

                    // custome code goes here ...

                    this.content.show();
                }
                this._open();
            }
        }
    });
    return $.ctv.collapsible;
});
```

- created requirejs-config file: namespace_module_dir/view/frontend/requirejs-config.js
```
var config = {
        map: {
            '*': {
                'mage/collapsible': '<namespace_module>/js/collapsible-mixin'
            }
        }
    };
```
**Result C:**
in browser inspector, following error:
Uncaught TypeError: base is not a constructor(...)

### Expected result

1. Should be able to extend `activate` method functionality located under lib/web/mage/collapsible.js 

### Actual result

unable to overrid `activate` method functionality.
please refer to each Scenario Result.

**Note:** you can refer to stack over flow [question](http://stackoverflow.com/q/40713696/3056733)

**Comment by veloraven** [comment]
@rramiii thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @rramiii please feel free to write here/reopen or to open new issue
