### ISSUE TITLE
'Undefined variable: orderId'  when checking out with Braintree in Magento 2 MULTISITE

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#7509]
hi guys!
we're having trouble checking out with Braintree after transforming the site in a Magento 2 Multisite.

### Preconditions
Magento ver. 2.1.0
Software version: 5.6.28-76.1 - Percona Server (GPL), Release 76.1, Revision 5759e76
Database client version: libmysql - 5.5.45-37.4

### Steps to reproduce
1. Add product to cart
2. Go to checkout (either as guest or registered)
3. Checkout with credit card (**using Braintree gateway**)
4. Place order
5. 3D secure appears and goes smooth (if enabled)

### Expected result
1.  Thank you, your order has been placed

### Actual result
Unable to place order
Firefox Console: Error 500 "Internal Server Error" (I set an exception printing for the checkout as guest)

**Exception log** (see attachment) 
Note: "mysite" is the main domain, "giustoacquisto.com" the actual domain (the secondary domain) where the problem occurs:
[exception.log.tar.gz](https://github.com/magento/magento2/files/604610/exception.log.tar.gz)

Important: we do not use table prefixing (that caused problems with Braintree in previous Magento 2 versions too)
Important: it works neither with the main domain nor with the secondary domains

thanks,
romeo

**Comment by YevSent** [comment]
Hi, @romeof1980, you need to use xdebug, set breakpoint in `PaymentInformationManagement::savePaymentInformationAndPlaceOrder#L71` or `GuestPaymentInformationManagement::savePaymentInformationAndPlaceOrder#L83` for guest customers and find original exception message.

Now, it looks strange that you get an error for a non-exists variable.

**Comment by romeof1980** [comment]
hi @joni-jones ,
thanks for your reply, appreciate it.
Why do you think I'm getting an error from a non-existing variable?
'orderId' is declared in line 81 of GuestPaymentInformationManagement , just a couple of line before where you advised me to set the breakpoint.
Am I missing something?

thanks a lot,
have a great day,
romeo

**Comment by vzabaznov** [comment]
Hi @romeof1980 , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Comment by romeof1980** [comment]
hi @vzabaznov ,
we're still facing this issue with Magento 2.1.2 and we're trying to get a solution.
By the way, we're waiting for Magento 2.1.3 or 2.1.4 because it seems some modification to the Braintree integration will be present in that upgrade.

thanks,
romeo
