### ISSUE TITLE
Magento REST API Schema (Swagger) is not compatible with Search Criteria

### ISSUE THREAD

**Issue by careys7** [magento/magento2#7511]
### Preconditions
1. Magento 2 CE or EE (all versions)

### Steps to reproduce

1. View Magento-generated Swagger Specification

### Expected result

1. Search criteria described in working format

### Actual result

1. HTTP 400 response from Magento when request sent in described format. 

---

The Magento [dev docs](http://devdocs.magento.com/guides/v2.0/howdoi/webapi/search-criteria.html) correctly describe REST API search criteria field groups and filters usage as needing an index per-field group / filter:

```
searchCriteria[filter_groups][<index>][filters][<index>][field=<field_name>]
searchCriteria[filter_groups][<index>][filters][<index>][value=<search_value>]
searchCriteria[filter_groups][<index>][filters][<index>][condition_type=<operator>]
```

When viewing the [generated Swagger documentation](http://devdocs.magento.com/swagger/), search criteria is described as follows (without a numerical index):

```
searchCriteria[filterGroups][][filters][][field]
```

Sending a request using `searchCriteria` in the format described by schema.json (without the numerical index) produces an HTTP 400 response. It also does not allow a user to define more than one `filterGroup` or `filter`, and breaks [swagger-codegen](https://github.com/swagger-api/swagger-codegen) clients.

The current `searchCriteria` implementation doesn't appear to be compatible with the [Open API Specification](http://swagger.io/specification/) in the current format.

**Comment by olysenko** [comment]
Hi @careysizer , thank you for your report. Internal ticket was created DDOC-11

**Comment by careys7** [comment]
Thanks @olysenko - 

I've just updated the issue to be clear that the input described in the [devdocs description](http://devdocs.magento.com/guides/v2.0/howdoi/webapi/search-criteria.html)  is correct in terms of the input that Magento expects, and it is the [Swagger schema](http://devdocs.magento.com/swagger/) produced by `Magento/Webapi/Model/Rest/Swagger/Generator.php` that is not.

**Comment by konstantinblaesi** [comment]
What's the current status? Is anyone working on fixing the search interface using swagger/swagger-codegen?

**Comment by springimport** [comment]
You can use [my extension](https://github.com/springimport/swagger-magento2-client/tree/fix-searchcriteria-index) with fix for searchcriteria

    "springimport/swagger-magento2-client": "dev-fix-searchcriteria-index"

**Comment by magento-engcom-team** [comment]
@careys7, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by careys7** [comment]
Thanks @magento-engcom-team . This is still an issue so have reopened #11477 with more comments.
