### ISSUE TITLE
Terms and conditions missing from both admin and front end

### ISSUE THREAD

**Issue by janeblonde** [magento/magento2#7519]
When following the guide linked below I notice that we are missing the Store View field. Once Saved we cannot edit the condition and it's not included on the front end.
http://docs.magento.com/m2/ee/user_guide/sales/terms-and-conditions.html

### Preconditions

1. Magento 2.1.2
2. PHP 7.0.13
3. MySqlnd 5.0.12-dev - 20150407
4. Linux dedi3458.your-server.de 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64

### Steps to reproduce

1. go to Stores > Terms and Conditions > Add New Condition
2. Fill out all details
3. save

![page looks like this](https://cloud.githubusercontent.com/assets/1465071/20523629/da5e1c0a-b0ad-11e6-9566-933d2cbd206d.png)

### Expected result

1. It should work!

### Actual result

1. nothing appears on front end
2. editing gives blank details (see screen)
![editing condition](https://cloud.githubusercontent.com/assets/1465071/20523660/08e13f76-b0ae-11e6-8bfb-de4105eef37e.png)

**Comment by SerhiyShkolyarenko** [comment]
@janeblonde thank you for the report!
I tried latest develop branch and it worked good for me. 

Frontend on creation of agreement:
![billing_agreement](https://cloud.githubusercontent.com/assets/15108140/20603328/b6bd77ec-b269-11e6-9054-ac0471f0c769.png)
-------------------------------------------------------------------------
and after editing:
![agreement_edited](https://cloud.githubusercontent.com/assets/15108140/20603963/ae5b9ce8-b26c-11e6-9e89-f59f887a8eef.png)

Is this issue reproducible for you on the develop branch?

**Comment by janeblonde** [comment]
@SerhiyShkolyarenko thanks for looking at this. We're due to go live very shortly, do you know what files are different so I can apply the fix?

**Comment by SerhiyShkolyarenko** [comment]
@janeblonde it works for me on 2.1.2 too, so I have no idea which fix to look for yet.

![terms_2 1 2](https://cloud.githubusercontent.com/assets/15108140/20626235/05d340b6-b321-11e6-9a4d-7fa82656a157.png)

Have you enabled Terms and conditions on Stores->Configuration->Sales->Checkout->Checkout Options->Enable Terms and Conditions?
Is the issue reproducible for you on absolutely clean Magento installation(clean DB and no other modules and themes)?

**Comment by RedEnzian** [comment]
Hello @janeblonde ,

SerhiyShkolyarenko has already pointed to the configuraiton setting which enables the agreement display in the checkout view.

The editing problem seems to be connected with the single store mode. Ive the same problem and posted it in this issue: https://github.com/magento/magento2/issues/7822 
try to switch off single store mode and edit the agreement.

**Comment by magento-engcom-team** [comment]
@janeblonde thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by onepack** [comment]
I added two Terms and conditions. One for each store-view in it's own language but after adding one and saving the condition it won't be visible anymore in the admin. I only see a button where I can add a new condition.
PHP 7.1.23
Magento 2.2.6
It's a fresh install for a dev environment with sample data.

**Comment by Ctucker9233** [comment]
@magento-engcom-team I had the same issue as @onepack. Can you take another look at this?

**Comment by met31** [comment]
@magento-engcom-team I'm having the exact same issue on a brand new install. No themes or extensions installed. Magento 2.3 PHP 7.2. MySQL 5.6.40-84.0. 

FYI tried turning off single store. No effect.

**Comment by LiamKarlMitchell** [comment]
Same problem on 2.2.0 enabled Terms and Conditions in the settings and enabled the Terms and Conditions.

Do have an error trying to place order now about accepting all terms and conditions but I can't actually see any in the DOM!

Any ideas?
