### ISSUE TITLE
Design Theme is missing from admin panel

### ISSUE THREAD

**Issue by mr-amirganishaikh** [magento/magento2#7520]
### Preconditions

1. Magento version 2.1.2
2. php version 5.6

### Steps to reproduce

1. Open Magento admin panel and navigate to Stores > Configuration menu.
2. In the General menu select Design tab.
3. There should be Design Theme tab

### Expected result

1. Design Theme tab should be 
screenshot is attached
![theme-set-2](https://cloud.githubusercontent.com/assets/8222422/20524020/2d45827a-b0de-11e6-9a0d-5cf534cc9e68.jpg)

### Actual result

1.Current output is as follows.
![download 2](https://cloud.githubusercontent.com/assets/8222422/20524004/0af2ccfa-b0de-11e6-9357-11ae153f7d15.png)

**Comment by hostep** [comment]
This has been changed between Magento 2.0 and 2.1.
Please see the documentation for the new place where you can find this in Magento 2.1:
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html
Also please close this issue, because it is not an actual issue :)

**Comment by mr-amirganishaikh** [comment]
Thanks hostep
