### ISSUE TITLE
Can't delete/save products from CLI

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#7528]
From a CLI command, when a product is saved/deleted so that the url_rewrites are updated the deletion query deadlocks.

### Preconditions

1. Magento 2.1.2
2. PHP 7
3. Mysql 5.6

### Steps to reproduce

1. Create a command that deletes a product
2. Launch it
3. Wait until query timeouts.

### Expected result

1. The product is deleted

### Actual result

1. Command fails after timeout

**Comment by slopukhov** [comment]
@giacmir thank you for your feedback.
Could you give an example of a command that you use to delete the product.

**Comment by giacmir** [comment]
Here it is a basic example:

```
<?php

namespace My\Module\Command;

use Magento\Catalog\Api\ProductManagementInterface;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\App\Area;
use Magento\Framework\App\State;
use Magento\Framework\Registry;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DeleteProductsCommand extends Command
{

    protected $productRepository;
    protected $productManagement;
    protected $searchCriteriaBuilder;
    protected $registry;
    protected $state;

    public function __construct(
        ProductManagementInterface $productManagementInterface,
        ProductRepositoryInterface $productRepositoryInterface,
        Registry $registry,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        State $state
    ) {

        $this->productManagement = $productManagementInterface;
        $this->productRepository = $productRepositoryInterface;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->registry = $registry;
        $this->state = $state;

        parent::__construct();
    }

    protected function configure()
    {
        $this->setName('msp:utils:delete-product')
            ->setDescription('Delete all products');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|null|void
     */
    public function execute(InputInterface $input, OutputInterface $output)
    {

        $this->registry->register('isSecureArea', true, true);

        try {
            $this->state->getAreaCode();
        }
        catch (\Exception $e) {
            $this->state->setAreaCode(Area::AREA_ADMINHTML);
        }

        $products = $this->productRepository->getList($this->searchCriteriaBuilder->create());

        foreach ($products->getItems() as $product) {
            $output->writeln('Deleting ' . $product->getSku());
//            $this->productRepository->delete($product);
//            $product->getResource()->delete($product);
            $product->delete();
        }
    }
}
```

in Magento 2.1.2 if you try to launch this you will end with a "Area code not set" error. But as you can see the area code is actually set. And this is the first strangeness.

To avoid this error you can try with a `session_start()` just before the foreach. But then you will have a deadlock on the db.

As you can see I tried three different methods to delete my product: using repository, using product resource model directly and from product. All three method gives the same problem (it's not a surprise given that all three ends up calling `getResource()->delete()`).

Also I noticed that if I use the ObjectManager directly to create the involved classes the error does not appear and the products are successfully deleted.

**Comment by slopukhov** [comment]
@giacmir I tried to run your code on the latest 2.1 version of Magento with Sample Data, and I have it worked without errors.
![result](https://cloud.githubusercontent.com/assets/8982177/20749726/40479768-b6fc-11e6-8b40-5abb7338ec2b.png)
Please, try to recheck it on the latest 2.1 version of Magento with Sample Data and describe your version of: OS, Apache or Nginx.

**Comment by giacmir** [comment]
I didn't tried that on sample data but on a copy of a production site with real products.

I'm using a vagrant vm with Ubuntu 16.04 with php 7.0.8 (cli), Magento is 2.1.2 (upgraded from 2.0, composer installation, developer mode).

webserver is nginx, but it is not concerned since it is a command line script.

**Comment by Codivores** [comment]
I have the same problem here with Magento 2.1.2. 

I use live data with some additional attribute but the error is linked with area code, not with the product itself.

Here is a link that speaks about the same issue : http://magento.stackexchange.com/questions/145698/magento2-delete-product-from-cli

**Comment by giacmir** [comment]
@Codivores I had the area code problem too in the script above (see below the script). It can be mitigated by putting an ugly `session_start()` at the start of the `execute`. But then you will have the db to go deadlock (for no apparent reason). 

There should be some strange behaviour at ObjectManager level when instantiating classes in the constructor.

**Comment by Codivores** [comment]
> Also I noticed that if I use the ObjectManager directly to create the involved classes the error does not appear and the products are successfully deleted.

Can you give me a sample of code for the work around because I cannot have it working ? If I use object manager with or without session_start, I just get the same error.

What I use just now : 

        $this->_productCollection->addAttributeToFilter('date_limite',
                array(
                    'from' => $debut->format('Y-m-d H:i:s'),
                    'to' => $dlc->format('Y-m-d H:i:s'),
                    'date' => true
                )
            );
        $output->writeln("Il y a ".$this->_productCollection->getSize()." produits à supprimer.");
        foreach ($this->_productCollection as $productCol) {
            $output->writeln("   Suppression du produit avec l'identifiant : ".$productCol->getId());
            try {
                $product = $this->objectManager->create("\Magento\Catalog\Model\Product");
                $product->load($productCol->getId());
                $product->delete();
            } catch (\Exception $ex) {
                echo $ex->getMessage();
                echo $ex->getTraceAsString();die();
            }
        }

**Comment by cizgidekiadam** [comment]
Same here with 2.1.3 
After database changed and restored old backup to new one.
In adminhtml, everything is normal but in cli, can not add/remove product 😞

**Comment by cizgidekiadam** [comment]
Solved for me.

If you restore a sql backup to a new database with different user, it reports an error: 
`the user specified as a definer ('user_name'@'%') does not exist`

For me, added old user with grant all, solved issue.

https://stackoverflow.com/questions/10169960/mysql-error-1449-the-user-specified-as-a-definer-does-not-exist

**Comment by magento-engcom-team** [comment]
@giacmir, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
