### ISSUE TITLE
Dashboard grid Last Orders shows guests name instead of actual customer name

### ISSUE THREAD

**Issue by blizzardengle** [magento/magento2#7529]
The dashboard on Magento 2.0+ chooses to display **Guest** in place of the customers actual name on the **Last Orders** grid when the customer checkouts without being logged-in. 

### Preconditions
1. Using Magento 2.0+ (I am using 2.1.2)

### Steps to reproduce
1. Using Magento 2.0+ (I am using 2.1.2) login to a store that has had customers check out as guests.
2. Look at the **Last Orders** grid on the left and it will say **Guest** and not the customers actual name; the original poster (OP) attached an image into their post.
3. This seems to be the offending file but I could be wrong: vendor/magento/module-backend/view/adminhtml/templates/dashboard/grid.phtml

### Expected result
The **Last Orders** grid should show who actually placed the order (Billing Name) instead of guest regardless of the fact that they were logged in or not.

### Actual result
Look at the OP's screenshot. Look at the **Last Orders** grid on the left and it will say **Guest** and not the customers actual name

This issue was raised before but got closed because of formatting and lack of updates, see: #6995

**Comment by SerhiyShkolyarenko** [comment]
@blizzardengle thank you for cooperation! 
Current state corresponds our internal requirements to dashboard, so we don't treat this issue as a bug. Your request was added to a story for dashboard improvement(MAGETWO-11358), but it's not guaranteed to be implemented this way. Please submit this improvement  to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Dashboard-grid-Last-Orders-shows-guests-name-instead-of-actual/idi-p/54615).
