### ISSUE TITLE
Configurable product "%1" does not have sub-products

### ISSUE THREAD

**Issue by kiutisuperking** [magento/magento2#7531]
i use magento 2 ver 2.1.1
I find solution fix this bug from https://github.com/magento/magento2/pull/7030. But it only work if the first child product of configurable is outstock and other childrent of configurable are instock. If the child simple product is listed as the first order, the other child products are out of stock, this error still happens.

**Comment by veloraven** [comment]
@kiutisuperking thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with exact steps to reproduce, expected result and actual result.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @kiutisuperking please feel free to write here/reopen or to open new issue
