### ISSUE TITLE
404 error: Page not found. in Email Templet

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7533]
Step 1 -  Marketing => Communications => Email Templates  

![cnbwmm](https://cloud.githubusercontent.com/assets/16436069/20555869/344ee4ce-b18a-11e6-87fa-31ef18c20ddd.jpg)

Step-2 Click On Save Templet Then  404 error: Page not found. Error sow 
![38fhrz](https://cloud.githubusercontent.com/assets/16436069/20555913/7afda914-b18a-11e6-8116-862fe286ca48.jpg)
How to Solve ?? Please Help Me 
Magento ver. 2.1.2

**Comment by veloraven** [comment]
@mitulispace thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with exact steps to reproduce, expected result and actual result.

**Comment by mitulispace** [comment]
issue solved  Hosting Issue
