### ISSUE TITLE
Magnify.js enabled always evaluates to true, can't disable it

### ISSUE THREAD

**Issue by surfer190** [magento/magento2#7534]
There is a specific line `config.magnifierOpts.enabled` in `/lib/web/magnifier/magnify.js`.
This will always evaluate to true, unless the magnier option is set like below:

```
<var name="magnifier">
            <var name="enabled"></var> <!-- Turn on/off magnifier (true/false) -->
        </var>
```

As it will be a json string of `"false"

### Steps to reproduce

Add the following to `/etc/view.xml`:

```
        <var name="magnifier">
            <var name="enabled">false</var> <!-- Turn on/off magnifier (true/false) -->
        </var>
```

### Expected result

1. The zoom should be disabled

### Actual result

1. It isn't disabled

Even if you set the `magnifier.enabled` to an empty string `" "`, it will not execute that code but it will still pop the zoom up.

**Comment by veloraven** [comment]
@surfer190 thank you for your report.
Please identify which version of Magento you are running.

**Comment by surfer190** [comment]
Magento 2.1.2

**Comment by VasylShvorak** [comment]
@surfer190  thank you for your report.
Is this issue still actual?
We were not able to reproduce it on the ver. 2.1.7

**Comment by magento-engcom-team** [comment]
@surfer190 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation.
