### ISSUE TITLE
Bug product import additional images

### ISSUE THREAD

**Issue by jalogut** [magento/magento2#7535]
There is a bug on the Import/Export module when importing product additional images. The value used to explode the filename values is different during validation and import steps:

Validation Step:
```
\Magento\CatalogImportExport\Model\Import\Product\Validator\Media
public function isValid($value)
{
   //...
   foreach (explode(self::ADDITIONAL_IMAGES_DELIMITER, $value[self::ADDITIONAL_IMAGES]) as $image) {
   //...
   }
}
```
Import Step:
```
\Magento\CatalogImportExport\Model\Import\Product

public function getImagesFromRow(array $rowData)
{
    //...
    $images[$column] = array_unique(
        explode($this->getMultipleValueSeparator(), $rowData[$column])
    );
    //...   
    $labels[$column] = explode($this->getMultipleValueSeparator(), $rowData[$column . '_label']);
    //...   
}
```

When the Value separator configured for the import is different than "," the validation goes through but the import fails because the value separator used for the explode is not a coma.

Please use the same separator for "additional_images" everywhere.

We also noticed that the separator for the export uses another different constant. From my point of view, here we should also use the same constant.

```
\Magento\CatalogImportExport\Model\Export\Product

   private function appendMultirowData(&$dataRow, &$multiRawData)
   {

    //...
    $dataRow['additional_images'] = implode(Import::DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR, $additionalImages);
    $dataRow['additional_image_labels'] = implode(Import::DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR, $additionalImageLabels);
    //...

   } 
```

**Comment by mhauri** [comment]
Same for Magento_GroupedImportExport/Model/Import/Product/Type/Grouped.php in method saveData()

`$associatedSkusAndQtyPairs = explode(Import::DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR, $associatedSkusQty);`

**Comment by veloraven** [comment]
@jalogut thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual and expected results.
Please also specify Magento version you are running.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @jalogut please feel free to write here/reopen or to open new issue

**Comment by jalogut** [comment]
@veloraven @vzabaznov Just opened a new issue with the proper format:
- https://github.com/magento/magento2/issues/7826

I hope that you can now have a look at it. Thanks
