### ISSUE TITLE
setup:di:compile segmentation fault

### ISSUE THREAD

**Issue by fmatovic** [magento/magento2#7539]
Hi im using PHP7, on Magento 2.1.1. 

I have installed a couple of modules, and all was fine, until today when i tried to install module, i moved files to root of magento2 installation. Run command php bin/magento module:enable <module_name>
after that php bin/magento setup:upgrade, and when i tried php bin/magento setup:di:compile
i starts 0/7, then 1/7 and then holds, and breaks, at first it wrote "Segmentation fault" after that when i tried again, no error is displayed and compile stops at 1/7 i tried increasing memory_limit, but nothing.

![screenshot_1](https://cloud.githubusercontent.com/assets/6945393/20572195/c37cd244-b1aa-11e6-907e-9e65d28cef7d.png)

**Comment by fmatovic** [comment]
Here is a line from error_log when i try to run setup:di:compile

`[24-Nov-2016 08:37:14 UTC] PHP Fatal error:  Uncaught exception 'Magento\Framework\Exception\FileSystemException' with message 'Directory "/home/loveispassion/public_html/var/cache/" cannot be created Warning!mkdir(): Permission denied' in /home/loveispassion/public_html/lib/internal/Magento/Framework/Filesystem/Driver/File.php:225
Stack trace:
#0 /home/loveispassion/public_html/lib/internal/Magento/Framework/Filesystem/Driver/File.php(199): Magento\Framework\Filesystem\Driver\File->mkdirRecursive('/home/loveispas...', 511)
#1 /home/loveispassion/public_html/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(88): Magento\Framework\Filesystem\Driver\File->createDirectory('/home/loveispas...', 511)
#2 /home/loveispassion/public_html/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(283): Magento\Framework\Filesystem\Directory\Write->create()
#3 /home/loveispassion/public_html/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(132): Magento\Framework\App\Cache\Frontend\Factory->_getBackendOptions(Array)
#4 /home/loveispass in /home/loveispassion/public_html/lib/internal/Magento/Framework/Filesystem/Driver/File.php on line 225`

**Comment by developer-lindner** [comment]
@fmatovic 'Permission denied'.... so just check your directory permissions. And close this ticket after it...

**Comment by fmatovic** [comment]
@developer-lindner What should permissions on directory be? 755?
