### ISSUE TITLE
Unable to modify products with negative quantity via Magento backend

### ISSUE THREAD

**Issue by Tjitse-E** [magento/magento2#7540]
### Preconditions
Install Magento 2.1.2 with sample data on your local machine. I'm using Vagrant with PHP7

### Steps to reproduce
1. Enable backorders
2. Set the Qty of demo product 24-MB01 to 0
3.  Place an order on the Magento frontend so the Qty changes to -1
4. Try to edit the product via the Magento backend

### Expected result
1. The product opens without an error message.

### Actual result
1.  An error message 'Please enter a valid number in this field.' appears under the field Qty. Because of this you're unable to save this poduct
![joust_duffle_bag___products___inventory___products___magento_admin](https://cloud.githubusercontent.com/assets/14849044/20573516/6716e7f0-b1b0-11e6-8960-a0a46ca69edf.png)

**Comment by quienti** [comment]
Duplicate https://github.com/magento/magento2/issues/7197

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate.
