### ISSUE TITLE
POST /V1/guest-carts/{cartId}/items : No such entity with cartId

### ISSUE THREAD

**Issue by ludovicpages** [magento/magento2#7542]
Hi.
I'm trying to add a product to a guest cart.
First i create a cart using POST /V1/guest-carts:
Then, when trying : POST /V1/guest-carts/{cartId}/items, i've got the following error 

```
{"message":"No such entity with %fieldName = %fieldValue","parameters":{"fieldName":"cartId","fieldValue":null}
```
I tried with Swagger and my own code, same error.

Any idea what's happening ? 
Ludo

**Comment by ludovicpages** [comment]
Ok, i see 2 problems here : 
First the object i need to send to POST /V1/guest-carts/{cartId}/items should be wrapped in a node "cartItem" or "cart_item". 
Something like : 
{ "cartItem": { "quote_id": "382ef56678c2ad30a099a68959bba3bb", "sku": "product_test", "qty": 10 } } works fine.

Second problem ; when doing a POST /V1/guest-carts, i receive a string with doublequotes, something like : "382ef56678c2ad30a099a68959bba3bb".So in order to use this, i had to remove the doublequotes with : 
````
$result = str_replace("\"", "", $result);
`````
Isn't that strange ? Is this normal behavior ? 

However, unless I am mistaken, this isn't mentioned anywhere in the doc.

Ludo

**Comment by veloraven** [comment]
@ludovicpages thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @ludovicpages please feel free to write here/reopen or to open new issue
