### ISSUE TITLE
REST API mandates customer firstname and lastname

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#7545]
### Preconditions

1. Magento REST API

### Steps to reproduce

1. Update Contact specifying only id, email and lastname in JSON

### Expected result

1. I expect customer to be updated, setting email address and lastname, and leaving other fields alone.

### Actual result

1. Error 400, explaining that firstname is a required field.

**Comment by veloraven** [comment]
@fvschie thank you for your report.
Please, also identify which version of Magento you are running.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @fvschie please feel free to write here/reopen or to open new issue
