### ISSUE TITLE
Quote item incorrectly flagged as deleted when the product becomes out of stock

### ISSUE THREAD

**Issue by guvra** [magento/magento2#7546]
### Description

After adding a product to the cart, if the product becomes out of stock (available qty = 0), the item is no longer displayed in the cart/minicart. The quote item is still stored in the database though.

### Preconditions
1. Magento CE 2.1.2 with sample data installed.

### Steps to reproduce
1. Add a product to the cart.
2. In the admin area, set the quantity in stock to 0 for this product.
3. Go to the cart (/checkout/cart).

### Expected result
1. The product is displayed in the cart, with an error message displaying that the item is out of stock.

### Actual result
1. The product isn't displayed in the cart/minicart, but the quote item is still in the database. If this was the only item in the quote, the empty cart template is displayed.

### Reason

In the `_assignProducts` method of `Magento\Quote\Model\ResourceModel\Quote\Item\Collection`, quote items are flagged as deleted if the related product is not found in `$productCollection`.

Out of stock products are removed from this collection by the plugin `Magento\CatalogInventory\Model\AddStockStatusToCollection`, which results in the quote item being flagged as deleted.

**Comment by oleg-onufer** [comment]
Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?

**Comment by korostii** [comment]
Hi @oleg-onufer,
You do know that 2.2.0 isn't even in the alpha yet, right?
The latest released version to date is 2.1.7:
https://github.com/magento/magento2/releases

**Comment by oleg-onufer** [comment]
Hi @https://github.com/korostii 
Yes. I know.

**Comment by oleg-onufer** [comment]
@korostii.
Yes. I know.

**Comment by korostii** [comment]
Ok, cool. Was a bit strange to see 2.2.0 in your original comment ;)
> Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2 (2.2.0)?

**Comment by magento-engcom-team** [comment]
@guvra, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by salmanjaved** [comment]
@magento-engcom-team @veloraven - 
**Magento version** 2.1.9
Guys I am facing the exact same issue. Step to reproduce are:

Add item to cart.
checkout using any payment gateway other than COD.
Set product to out of stock from admin.

When returning from payment gateway on successful transaction order is not placed. Not only this simple product gets deleted from the quote_item table.

Can you please have a look into it?
