### ISSUE TITLE
Something went wrong while resetting customer password.

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#7548]
### Preconditions

1. https://github.com/magento/magento2/issues/5260
2.  Magento 2 CE Version 2.1.2

### Steps to reproduce

1. For 1 User able to Set Reset Password. From Admin.
2. If we do for multiple users 1 by 1 from Admin Can't
3. Admin -> Stores -> Configuration -> Customers -> Customer Configuration -> Password Options
Password Reset Protection Type set to None still issue

### Expected result

1.  Email Should be Sent to All Customers for Reseting Password without Any Interval or Wait.
2. Can send email one by one without any waiting time from Admin

### Actual result

1. [Screenshot, logs]

**Comment by shahankitb997** [comment]
@veloraven When will get patch for this of where this issue will be solved? Website is Live  & Customers are facing this issue. Please provide solution ASAP.

Thanks

**Comment by sevos1984** [comment]
This is not an issue. Time between password resets from admin is configured in Stores->Configuration->Advanced->Admin->Security->Min Time Between Password Reset Requests

**Comment by nawabamit** [comment]
when i enter new password and click to submit button its reload the page and nothing happen. after refresh the page it shows 'Please enter a new password' every time. i create new multiple time but its show same error in magento 2
