### ISSUE TITLE
Magento RequireJs Behaviour Conflicts With Their Documentation

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#7551]
### Preconditions
1. Magento 2.2-dev

### Steps to reproduce
1. Use requirejs to pull in a requirejs custom module from within your module template
2. Do not set jquery to $ sign
3. Add an event listener, such as click.

### Expected result
1. Event listeners loaded asynchronously but always loaded eventually, consistently.

### Actual result
1. Event listeners work most of the time, but sometimes are never attached (script not loaded).

_People using magento2 are using a method of working around this that contradicts with the requirejs documentation.
http://magento.stackexchange.com/questions/146777/jquery-event-listeners-working-most-of-the-time-but-not-sometimes?noredirect=1#comment200292_146777_

**Comment by veloraven** [comment]
@LiamFielding thank you for your feedback.
Please identify which version of Magento you are running.

**Comment by LiamFielding** [comment]
2.20-dev

This is a very hard thing to test because it works nearly all of the time - however sometimes it doesn't. We're testing in a corporate environment so there are many computers clearing their browser cache and loading it as if the first time.

There are no thrown errors or any indication of why it hasn't loaded in the console, the event listeners are simply not attached (I am uncertain that I have confirmed this, but I doubt the script is running at all)

By the time we realise it has happened we refresh to fix it but it has gotten to the point where we need it to work absolutely every time in production.

**Comment by Igloczek** [comment]
I think you need to wait for DOM content to be loaded, because there is a possibility that you are trying to listen for an event on non-existing DOM node.

Try something like this:

```js
define([
  'jquery',
  'domReady!'
], function ($) {
  // your logic here
})
```
