### ISSUE TITLE
Compare on Mobile

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#7553]
Does Magento 2 have a compare option on Mobile?.
I could not find one on backend to enable it?

**Comment by veloraven** [comment]
@nmallepally thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to submit an improvement please use new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
