### ISSUE TITLE
Logged-in user has to re-login before checkout

### ISSUE THREAD

**Issue by sigismund** [magento/magento2#7554]
### Preconditions

1. Magento 2.1.2, 2.1.9 PHP7
2. User is logged in
3. Guest checkout is disabled

### Steps to reproduce

1. Login in
2. Add product to cart
3. In top bar there is text "Welcome Michael Surname", but there is still option to sign-in and sign-up next to it. 
4. Go to cart > checkout
5. Login prompt is displayed

### Expected result

1. When user is logged-in and "Wecome user" is displayed, there shouldn't be any sign in/up link next to it, just sign out. 
2. User should be able to checkout without re-login in checkout process.

### Actual result

1.  User is somehow semi-logged in. Part of Magento detects it, but other part doesn't.

**Comment by SerhiyShkolyarenko** [comment]
@sigismund thank you for the report!
Tried these steps on the develop branch and on v2.1.2 but didn't reproduce it.

> Go to cart > checkout

Does it mean clicking "Go to Checkout" button on minicart?
What were your other steps after installation? Did you perform any configuration changes?

**Comment by SerhiyShkolyarenko** [comment]
> In top bar there is text "Welcome Michael Surname", but there is still option to sign-in and sign-up next to it.

@sigismund it seems you customer session is expired. In such case Magento leaves "Welcome Michael Surname"(it's a bug), but shows "Sign In" link.

**Comment by flnative** [comment]
Same issue with 2.1.2. I cannot checkout. The system thinks I'm logged out even though I login a bunch of times. I get the Welcome (name) on top, but still shows "sign in" link. I cannot make a purchase no matter what I do. Damn, I wish I never installed this version for a production site. It has been a year and I cannot even make an order on the front end.

**Comment by taschert** [comment]
Same issue with 2.1.0. Is there a fix for this issue ?
I found this 2 related issue #6759 & #4589

**Comment by Kentricks** [comment]
Hi, I have the same issue on 2.1.7, did anyone know if a fix is ongoing ?

**Comment by veloraven** [comment]
@Kentricks could you please provide more information then?
Please specify which versions of OS, web-server, PHP, MySQL you use.
Do you use any external extensions?
Do you use persistent shopping cart functionality?
Did you change value for Online Minutes Interval? (Stores > Settings > Configuration > Customers > Customer Configuration -> Online Customers Options)
Could you please provide a screenshot?

**Comment by elisei** [comment]
magento v. 2.1.9 and the problem persists!

**Comment by magento-engcom-team** [comment]
@elisei thank you for update. We updated issue description

**Comment by magento-engcom-team** [comment]
We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, and any other information needed to reproduce your issue.

**Comment by elisei** [comment]
hello follows an error gif.
![sep 21 2017 12-03 pm](https://user-images.githubusercontent.com/1786389/30703169-4f9af000-9ec5-11e7-8b2c-5d1a1311f930.gif)

Process I've already tried based on the guideline here:
- Checkout persistence on/off
- Change session time
- Turn on/off the checkout in anonymous method

I have extra extensions:
smtp - mageplaza
moip (which I'm developing now).
I've tried uninstalling them but the problem continues.

Php v, 7.0.23 ubuntu14.04.1

**Comment by magento-engcom-team** [comment]
@sigismund, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by phronesis** [comment]
I find it really odd when a bug reported in a minor version(semver) is fixed in another minor version without being backported to the version it was reported in. From my experience, If I dare update to 2.2, I'll find much more bugs introduced there. So updating to 2.2 is a 'NO' for some of us. 
Could you point us to the commit that fixed this issue, so we can create a patch for the 2.1.x branch, if Magento does not see this issue as critical enough to be backported? Thank you.

**Comment by ghost** [comment]
I couldn't agree more.  Moving from 2.1.9 to 2.2.0 means being forced to PHP 7.0+ as well.  Which, in our case - on this system, isn't an option.

It would be truly useful to patch 2.1.9- to fix this issue.

**Comment by cristian1991** [comment]
Any updates on the issue? I know that asking for a fix might be too much, but, at least, did anyone find a stack trace for the bug so the community might give it a chance into fixing the issue?

**Comment by VivianWang1993** [comment]
Could you write the code branch that how to fix this bug here, please? We can't update to Magento 2.2 in short period. Thank you very much

**Comment by phronesis** [comment]
For those still experiencing this issue, this is the commit that fixes it:
https://github.com/magento/magento2/commit/861f596371825d9e24672cd613229ae9486c635f
. Digging into the code, this only applies if your request is a 'POST' request -  that makes sense.
If your request for some reason, is not a 'POST' request, you may need to make some modification

**Comment by afourmeaux** [comment]
le commit pointed by phronesis is already in my version and i'm still having the issue in 2.1.10 and we can't afford to pass in 2.2. So it'd be cool to have a clear answer please.

**Comment by iindranil** [comment]
This issue still exists with Magento ver. 2.4.2 

I've tried with @phronesis solution but no luck. Right now, I am using the latest version (2.4.2) of Magento and what I need to do?

Should I wait for the next version release? Lol

**Comment by ziarv** [comment]
This issue still exists with Magento ver. 2.4.2

**Comment by shaileshbhagaliya** [comment]
this issue also came on magento ver 4.2.3 too

**Comment by Mr-Leonerrr** [comment]
The issue still happening in Adobe Commerce 2.4.6-p1

**Comment by magewallet** [comment]
This is still happening 2.4.6-p1

**Comment by FuscaSoftware** [comment]
After multiple updates we repeatly get these problems with customers hanging in a re-login loop. To break out from this loop I did a little dirty customization in `sidebar.js` and `proceed-to-checkout.js` in `[template]/Magento_Checkout/web/js`:

```
            if (!customer().firstname) {
                var sections = ['cart', 'customer'];
                 customerData.invalidate(sections);
                 customerData.reload(sections, true);
            }
```

before:
```
if (!customer().firstname && cart().isGuestCheckoutAllowed === false) {
```
