### ISSUE TITLE
localization, translation in email template

### ISSUE THREAD

**Issue by BeatDirector** [magento/magento2#7555]
Hello,

in some email templates (change email) there are some translation code like this:

` {{trans 'If you have not authorized this action, please contact us immediately at <a href="mailto:%store_email">%store_email</a>' store_email=$store_email |raw}}`

There are nested translation declaration with ' and " for href
{{trans'lorem ipsum href="yxz" '}}

### Preconditions

1. Magento 2.1.2
2. PHP7
3. developer mode
4. German localization in frontend

### Steps to reproduce
1. in Magento backend go to Marketing - Communications - Email Templates
2. Add new Template
3. select Template Change Email
4. click on Load Template
5. Preview Template

### Expected result
1. Text translated in German language as set in locale CSV

### Actual result
1. english text, not transpated

Translation works only if you swap ' and " in nested {{trans }} code.
like this:

` {{trans "If you have not authorized this action, please contact us immediately at <a href='mailto:%store_email'>%store_email</a>" store_email=$store_email |raw}}`

kind regards

**Comment by palamar** [comment]
Thanks for reporting this issue. 

Phrases are matched as strings,  so in case of if you have
```
"If you have not authorized this action, please contact us immediately at <a href=""mailto:%store_email"">%store_email</a>"
```
as key in your CSV file, such pattern will match with *"*

If you have 
```
"If you have not authorized this action, please contact us immediately at <a href='mailto:%store_email'>%store_email</a>"
```
as key in your CSV file, such pattern will match with *'*.

I have checked this issue via https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE and all works as expected.
Match works with double quotes, and doesn't work with single quotes.

Could you check your CSV file, please.

**Comment by vzabaznov** [comment]
Hi @BeatDirector , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue
