### ISSUE TITLE
Check Data function on import doesn't check for sku character size

### ISSUE THREAD

**Issue by ooples** [magento/magento2#7559]
### Preconditions

1. I'm using Magento 2.1.2

### Steps to reproduce

1. I import a file for products with skus that are 68 characters long and it checks and says it is valid
2. I try importing the file and it fails with the attached error
![yugioh_test_import_error](https://cloud.githubusercontent.com/assets/3075685/20609978/efe16a9e-b258-11e6-8780-05db37dc7395.png)

### Expected result

1. During the check data process it should give an error message saying that the sku is over the max size

### Actual result

1. No error message

Here are my files that I used for testing:

Working version:
![test_longsku_doeswork](https://cloud.githubusercontent.com/assets/3075685/20610312/3d6782ea-b25d-11e6-864c-589807bada39.png)

Error version:
![test_longsku_doesntwork](https://cloud.githubusercontent.com/assets/3075685/20610316/49434608-b25d-11e6-8dee-304e9d139cfd.png)

**Comment by Stas94** [comment]
@ooples Created internal issue MAGETWO-70334 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@ooples, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
