### ISSUE TITLE
Error when editing 'Terms and Conditions' in single store mode

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#7564]
After creating a new term and condition and you go and edit it you get an error. See full trace attached.
--
1 exception(s):
Exception #0 (Exception): Warning: htmlspecialchars() expects parameter 1 to be string, array given in vendor/magento/framework/Data/Form/Element/AbstractElement.php on line 286
--

### Preconditions
1. Magento 2.1.2
2. Single store mode enabled

### Steps to reproduce
1. Create a term & condition
2. Edit this term & condition

### Expected result
1. Edit screen

### Actual result
1. See attached

[stacktrace.txt](https://github.com/magento/magento2/files/612826/stacktrace.txt)

**Comment by veloraven** [comment]
@rikwillems thank you for your report.
This is a duplicate for #7171 so I'm closing it.
