### ISSUE TITLE
Something went wrong while saving the category.

### ISSUE THREAD

**Issue by chamola** [magento/magento2#7566]
While Saving category in Magento 2.1.0 getting below mentioned error

Something went wrong while saving the category.

**Comment by veloraven** [comment]
@chamola thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also provide information about your environment: OS, versions of PHP, MySQL and web-server.
Also if there are any errors in browser or log files pleas provide them as well.

**Comment by vzabaznov** [comment]
Hi @chamola , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue
