### ISSUE TITLE
Empty cart page throws an exception when GTM is enabled and Cross-sell Rotation Mode is not Shuffle

### ISSUE THREAD

**Issue by devanhurst** [magento/magento2#7567]
### Preconditions
1. Magento E.E. 2.1.2 installed
2. PHP 5.6.24
3. MySQL 5.6.28

### Steps to reproduce
1. Enable Google Tag Manager in Stores > Configuration > Sales > Google API
2. Set the Cross-sell mode to Do Not Rotate in Stores > Configuration > Catalog > Catalog > Rule-Based-Product Relations
3. View /checkout/cart without any items added, or remove the final item from your cart.

### Expected result
1. The empty cart page is displayed.

### Actual result
1. Two exceptions are thrown. 

[m2-bug-gtm-crosssell.txt](https://github.com/magento/magento2/files/613255/m2-bug-gtm-crosssell.txt)

**Comment by veloraven** [comment]
@devanhurst thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
I'm closing this issue as it refers to EE functionality.
