### ISSUE TITLE
Setup process data

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#757]
I see that the data entered in the setup process, db credentials, base url, locale and others are saved in the `localStorage`.  
This includes the admin email and password that are saved in clear text. 
I don't think that saving the password is a good idea.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31608

**Comment by tzyganu** [comment]
@antonmakarenko this seams to be OK now. Do you plan any other changes regarding the local storage? If not you can close this issue?

**Comment by tanya-soroka** [comment]
Right now all data is saved on the localstorage of the browser memory during installation. After installation this data is cleared. 

I am going to close this ticket. Please feel free to reopen.
