### ISSUE TITLE
Something went wrong error and no table displaying in catalog

### ISSUE THREAD

**Issue by rahwayelectric** [magento/magento2#7572]
When I try to open the catalog, a 'Something went wrong' error comes up, and no table displays. The report reads,
> `a:4:{i:0;s:180:"Warning: strtoupper() expects parameter 1 to be string, array given in /home/<username>/public_html/<installation folder>/vendor/magento/module-ui/Component/Listing/Columns/Column.php on line 136";i:1;s:5984:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'strtoupper() ex...', '/home/rahway5/p...', 136, Array)`

### Preconditions
1. Magento ver. 2.1.2 CE
2. PHP Version 5.6.27
3. MySQL Version 5.6.33

### Steps to reproduce
1. Select Products>Inventory>Catalog
2. Wait.

### Expected result
1. I assume there's supposed to be a table of the products I've entered, but I don't know as it never worked right in this installation, and this is my first installation of Magento. 

### Actual result
'Warning. Something went wrong.'
Generated report starts with, "a:4:{i:0;s:180:"Warning: strtoupper() expects parameter 1 to be string, array given in /home/rahway5/public_html/ecommerce/vendor/magento/module-ui/Component/Listing/Columns/Column.php on line 136";i:1;s:5984:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'strtoupper() ex...', '/home/rahway5/p...', 136, Array)"
![something went wrong](https://cloud.githubusercontent.com/assets/23753797/20637461/eb39c5be-b356-11e6-9783-ad552dfebf51.png)

This photo is what occurs if you select Products>Inventory>Categories, then select Products>Inventory>Catalog. 
![absent table](https://cloud.githubusercontent.com/assets/23753797/20637460/eb2f08c2-b356-11e6-8048-572d07d4bae5.png)

[1034607486992.txt](https://github.com/magento/magento2/files/614015/1034607486992.txt)

**Comment by rahwayelectric** [comment]
Issue was resolved by going over to PHP 7 and reinstalling Magento.

**Comment by veloraven** [comment]
@rahwayelectric thank you for update.
As the issue was resolved I'm closing this report.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
