### ISSUE TITLE
Knockout's getTemplate function being called twice

### ISSUE THREAD

**Issue by ntoombs19** [magento/magento2#7574]
### Preconditions

1. Magento 2.1.2
2. Latest Chrome version

### Steps to reproduce

1. Open up the minicart.js component
2. Add this function to the component
```js
getTemplate: function() {
    console.log('minicart template loaded');
    return this.template;
}
```
3. Open a page in the frontend that includes the minicart.js component
3. Open up the browser's console
4. Refresh the page

### Expected result

1.  The console should show 'minicart template loaded' only once.

### Actual result

1. The console shows 'minicart template loaded' twice.

I am trying to utilize the [afterRender](http://knockoutjs.com/documentation/template-binding.html#note-4-using-afterrender-afteradd-and-beforeremove) to execute some logic that should only be executed once. Due to this bug, I have to set a flag on the first go around and wrap the logic in a conditional that checks that flag. I would prefer this workaround not be necessary.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-61519. Thanks for reporting.

**Comment by ntoombs19** [comment]
I failed to mention that I've seen this with every template I've tested when verifying this bug. So the issue is not isolated to the minicart template.

**Comment by ntoombs19** [comment]
Can I get a status update on this issue?

**Comment by mattgreenfield** [comment]
me too, any progress on this?

**Comment by magento-engcom-team** [comment]
@ntoombs19, thank you for your report.
We've created internal ticket(s) MAGETWO-61519 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @ntoombs19

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@ntoombs19 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
