### ISSUE TITLE
Import product in Magento 2 with custom options

### ISSUE THREAD

**Issue by lexuanchien** [magento/magento2#7575]
Hi.
i have problem when import product in magento 2 is: 
"1. This name is already being used for custom option. Please enter a different name. in row(s)".
Actually i have import 1541 product but can't valid all because receiver error above.
Please help me, how to fix it ?

**Comment by veloraven** [comment]
@lexuanchien thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please create new GitHub issue: format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
