### ISSUE TITLE
CLI issue with bin/magento and exit codes for failure

### ISSUE THREAD

**Issue by sitepodmatt** [magento/magento2#7576]
Magento 2 CLI not setting expected/correct exit codes when an upgrade task fails. 

### Preconditions

Magento ~2.2 tip of develop

### Steps to reproduce

Run a bin/magento setup:upgrade where a data upgrade fails, a simple die("lets hope this isnt tracked internally for the love of community but instead on github issues")  in your modules UpgradeData.php upgrade function will suffice.

### Expected result

Exit code should be non-zero

### Actual result

Exit code is zero
#

**Comment by sitepodmatt** [comment]
There exists a hacky workaround, I post to illustrate others are experiencing the same gripes, ultimately this shouldn't be necessary. http://aleron75.com/2016/08/12/magento2-script-for-setup-upgrade/

**Comment by shiftedreality** [comment]
Hi @sitepodmatt 

Thank you for your report.
I've created an internal ticket MAGETWO-61431 to resolve and fix this issue.

**Comment by choukalos** [comment]
Assigning to @misha-kotov .

**Comment by veloraven** [comment]
This issue has already been fixed.
Closed.
