### ISSUE TITLE
Can't select custom attribute_set in configurable product creation

### ISSUE THREAD

**Issue by developer-lindner** [magento/magento2#7579]
### Preconditions
1. Magento2 Version 2.1.2
2. PHP 7.0.12-1
3. MySQL Percona 5.6.30

### Steps to reproduce
1. Go to Products->Catalog in the Backend.
2. click 'Add product'
3. Try to select a custom Attribute-Set

### Expected result
1. Selected Attribute-Set will be set properly

### Actual result
1. 500 (Internal Server Error) in Ajax Response after selecting a custom attribute set with the following response:

> 1 exception(s):
> Exception #0 (Magento\Framework\Exception\InputException): attribute_set_id is a required field.
> 
> Exception #0 (Magento\Framework\Exception\InputException): attribute_set_id is a required field.
> #0 vendor/magento/module-eav/Model/Attribute/GroupRepository.php(111): Magento\Framework\Exception\InputException::requiredField('attribute_set_i...')
> #1 vendor/magento/module-catalog/Model/ProductAttributeGroupRepository.php(57): Magento\Eav\Model\Attribute\GroupRepository->getList(Object(Magento\Framework\Api\SearchCriteria))
> #2 vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(426): Magento\Catalog\Model\ProductAttributeGroupRepository->getList(Object(Magento\Framework\Api\SearchCriteria))
> #3 vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(241): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->getGroups()
> #4 vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(68): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->modifyMeta(Array)
> #5 vendor/magento/framework/View/Element/UiComponentFactory.php(269): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta()
> #6 vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
> #7 vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
> #8 vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
> #9 vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
> #10 vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
> #11 var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
> #12 vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
> #13 vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
> #14 vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
> #15 vendor/magento/framework/View/Layout.php(935): Magento\Framework\View\Layout->build()
> #16 var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
> #17 vendor/magento/framework/View/Result/Layout.php(181): Magento\Framework\View\Layout\Interceptor->getOutput()
> #18 vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Layout->render(Object(Magento\Framework\App\Response\Http\Interceptor))
> #19 var/generation/Magento/Framework/View/Result/Layout/Interceptor.php(89): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
> #20 vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Layout\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
> #21 vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> #22 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> #23 {main}

**Comment by developer-lindner** [comment]
The request looks like this by the way:
http://example.com/some_other_values_in_between/?set=undefined&isAjax=true

Inside of the ui-select.html the click triggers the function call of 
`$parent.toggleOptionSelected($data, $index(), event);`

where $data is set and seems to have the right value, but the request function can't use it?!

I'll investigate some more here... if anyone has an idea, please contribute!

**Comment by developer-lindner** [comment]
updateValue function in links.js (app/code/Magento/Ui/view/base/web/js/lib/core/element/links.js)
gets called over 20times... At the beginning 'value' is set (which represents the Attribute Set ID)
but gets lost or gets undefined later on?!

Dear Magento2 - what the hell is wrong with you?

**Comment by orderofwigs** [comment]
hey, i have the same problem. i think it is related to migrated attribute set from an older magento version. please let us know if you found out any fixes or specific causes?
thanks

**Comment by developer-lindner** [comment]
@veloraven Hey, any update here? Internal ticket or something?!

**Comment by olysenko** [comment]
Hi, this issue is a duplicate of [5999](https://github.com/magento/magento2/issues/5999). In this [comment](https://github.com/magento/magento2/issues/5999#issuecomment-243791468) you can see workaround. Closed as a duplicate. Feel free to reopen this if you think you have another issue

**Comment by developer-lindner** [comment]
@olysenko Thanks, i've noticed that my issue arised through migrated attribute sets.

**Comment by dunarri** [comment]
I have the same problem, what was the fix?

**Comment by olysenko** [comment]
@dunarri, try this workaround [comment](https://github.com/magento/magento2/issues/5999#issuecomment-243791468).

**Comment by dunarri** [comment]
I saw that, but price was in Product Details and I added Bundle Items.
I believe this is a separate issue as the exception message and stack trace is different. To prove this I created a new attribute set in Magento 2 that was identical to the migrated attribute set. The new one works fine, the migrated one has the error in OP.
Should I create a new issue?

**Comment by developer-lindner** [comment]
@dunarri no, because the issue is introduced by migrated data which doesn't fits the magento2 attribute set structure. the code is fine, just the migrated data (attribute sets) is fucked up. you'll have to create all needed attribute sets in magento2 and allocate all needed attributes to the set manually.

**Comment by ghost** [comment]
This will happen when you have attributes that are migrated but some belong to an old extension.
Mine was the Pre-order extension.  After removing both Attributes from the old Pre-order extension the pages were loading fine. 

Just enable error reporting in app/bootstrap.php error_reporting(E_ALL); 
ini_set("display_errors", 1);

And look for old extension information in the error.
After that remove all the attributes according to that extension.

It works like a charm for me.
I hope it will help someone.
