### ISSUE TITLE
Parameter always required though disabled from depending parameter

### ISSUE THREAD

**Issue by biolauri** [magento/magento2#7580]
This is a reopening of #4672.

### Preconditions
1. Magento 2.1.2
2. Custom widget installed and enabled:
   ```xml
   <?xml version="1.0" encoding="UTF-8"?>
   <widgets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Widget:etc/widget.xsd">
	<widget id="Test_DepPar">
		<label translate="true">Test widget: depending parameters</label>
		<description>Test depending and required parameters</description>
		<parameters>
			<parameter name="display" xsi:type="select" required="true" visible="true" sort_order="10" >
				<label translate="true">Display other parameter</label>
				<options>
					<option name="true" value="true">
						<label translate="true">Yes</label>
					</option>
					<option name="false" value="false">
						<label translate="true">No</label>
					</option>
				</options>
			</parameter>
			<parameter name="other_parameter" xsi:type="text" required="true" visible="true" sort_order="20" >
				<label translate="true">Other parameter</label>
				<depends>
					<parameter name="display" value="true" />
				</depends>
			</parameter>
		</parameters>
	</widget>
   </widgets>
   ```

### Steps to reproduce
1. Insert new widget in CMS page via widget editor
2. Select installed widget above (*Test widget: depending parameters*)
3. Select *No* in parameter *Display other parameter*
4. *Insert widget*

### Expected result
1. The widget gets inserted into the (WYSIWYG) editor
2. Parameter `other_parameter` is not set (disabled by `display` based on `<depends>[…]</depends>` of  `other_parameter`)

### Actual result
1. The widget will not get inserted (nothing happens)
2. This is based on `required="true"`, which is not overwritten by the dependency

---

So, I would appreciate a better function to determine whether a parameter is required or not: Not only based on the attribute `required="true|false"`, but also according to the current state (deactivated based on dependency) of the parameter.

**Comment by magento-engcom-team** [comment]
@biolauri, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
