### ISSUE TITLE
Configurable product: variation descriptions & specifications

### ISSUE THREAD

**Issue by falco456** [magento/magento2#7581]
Hi,

I am facing a problem with configurable products. If you create a configurable product and create some  product variations based on lets say color & size, if you change the price and image for a specific variation and select this variation on the configurable product page, the price and image will change. 

This is a very good feature altough the expected behaviour for me would be that the description and specifications for this selected variation would be shown, in stead of the specifications of the configurable product itself.

**Why does it change the price and image, but not the description and product specifications?**

I attached a screenshot to give you an idea of the issue.

I also used to have this problem in Magento 1 and found a module for this which solved the problem. However this module is not supported for Magento 2.
https://www.magentocommerce.com/magento-connect/sdocp-simple-details-on-configurable-products-1.html

Is there a way this can be done programmatically or fixed in the core?

![magento2_specs_issue](https://cloud.githubusercontent.com/assets/24209185/20649764/f89271ae-b4c6-11e6-8c97-44ac2dadd811.png)

Kind regards,

Falco

**Comment by audexpro** [comment]
I have same problem. Just that from me certain products are available for shipment within 2-4 days, but for others you must wait 4-6 weeks. Behold, this I wanted to specify in the description which unfortunately does not change when you use the switch :(

**Comment by veloraven** [comment]
@falco456 thank you for your feedback.
What you describe is more like improvement than an issue.
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by ritschi72** [comment]
Hi there,
we also face a problem with configurable products and the images of some variations (color and size) in Magento version 2.1.2.
In the process of creating configurations in a product, we added different images to the attribute "color".
So if you click for example color "red" in frontend, the detail images should change and show the specific images that we added by creating the configurations.

But it only takes the base image of this variation and doesn't show the other images.
We testet in version 2.0.1 and there everything worked fine.
Maybe you have got an idea how to solve that.

thanks a lot

**Comment by developer-lindner** [comment]
@ritschi72 Are you able to set a custom attribute set for the configurable product?

**Comment by ritschi72** [comment]
Yes, that is possible

**Comment by falco010** [comment]
@veloraven I created a ticket in the Feature Requests, thanks for your response. Do you have any suggestions on how to do this programmatically as I need this as soon as possible for my client?

@ritschi72 I cannot reproduce this problem and this is not really relevant to my original issue that i described above. I suggest creating a new ticket for this issue.

**Comment by veloraven** [comment]
@ritschi72 please create new GitHub report for your issue as you describe different case than the one described in this report. Please, format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
@falco010 thank you for update.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by audexpro** [comment]
I solved this with AMASTY Extensions **Color Swatches Pro**
