### ISSUE TITLE
Terms and conditions on checkout only validates first agreement

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7584]
Terms and conditions on checkout only validates first agreement. Once you check the first agreement if you click place order it will submit without needing to check the second.

![tandc](https://cloud.githubusercontent.com/assets/19700178/20661677/14ddadaa-b58b-11e6-94e3-9b01aca02613.png)

Preconditions

Magento 2.1.2

Steps to reproduce

Create two Term and Conditions entry under Stores > Terms and Conditions
Activate Terms and Conditions for checkout under Stores > Sales > Checkout > Enable Terms and Conditions
Enable a second payment method
Go through checkout
On Review & Payments step select a payment method
Click Place Order
Validation message for Term and Condition entry appears for first agreement only
No validation message appears for the second agreement
Click place order
Submits order

Expected result

Validation message for unaccepted Term and Condition entry appears
Actual result

No validation message for unaccepted Term and Condition entry appears

**Comment by veloraven** [comment]
@thank you for your feedback.
I'm closing this issue as duplicate for #5632

**Comment by ghost** [comment]
Sorry didn't see that ticket when I was searching earlier.
