### ISSUE TITLE
setOrder does not escape query in SQL

### ISSUE THREAD

**Issue by thaihung38** [magento/magento2#7585]
### Preconditions

1. Ubuntu + PHP7 + MariaDB 10
2. Magento2 up to 2.1.2

### Steps to reproduce

I have set a collection ordering by setOrder('order', ASC|DESC) (I have a column named 'order', same name with a SQL syntax) and it crash with error in SQL syntax.

### Expected result

SELECT \`main_table\`.* FROM \`my_ns_module\` AS \`main_table\` WHERE (\`some_condition\` = \'1\') ORDER BY \`order\` ASC

### Actual result

SELECT \`main_table\`.* FROM \`my_ns_module\` AS \`main_table\` WHERE (\`some_condition\` = \'1\') ORDER BY order ASC

The 'order' field is not escaped and show me a SQL syntax error. I have to escape it by myself with setOrder('\`order\`').

**Comment by magento-engcom-team** [comment]
@thaihung38, thank you for your report.
We've created internal ticket(s) MAGETWO-81604 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@thaihung38, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
