### ISSUE TITLE
Braintree Magento 2 not configurable by store view

### ISSUE THREAD

**Issue by mark166** [magento/magento2#7587]
When using Magento 2.1.2 the Braintree core module is not configurable by store view. We have 3 store views set up.  You can configure the module in default config but when you choose a specific store view the options do not appear.

Steps to reproduce
Navigate to stores>configuration>sales>payment methods>Braintree
1. Select a store view other than default config
2. Press on the configure button

Expected result
1. Configuration options should open for the chosen store view

Actual result
1. Nothing happens, only the configuration button changes to close

**Comment by YevSent** [comment]
Hi, @mark166, this is not an issue, Braintree configuration available per website, not per store view.

**Comment by mark166** [comment]
Hi joni-jones

Thank you for the comment, i though it had to be a bug as couldnt see why the braintree option would be there on store view level with a button saying "configure". If it was not configurable you would expect the entire Braintree section not to be visible when in store view. Thanks anyway.

**Comment by ioliinyk** [comment]
Hi @mark166. The issue you mentioned actually not an issue but expected behavior. The standard store view purpose is customizing view per language and some other local attributes. But payment method doesn`t have to be defined per store view.

**Comment by YevSent** [comment]
Closed as not a bug.

**Comment by michaeldyl520** [comment]
There have a bug, default config set braintree api key, and set another api key to another website(second website), then ordered in the website(second website), then you submit invoice in backend of this order(the seond website order), you can get some went wrong error test.This is a big problem @joni-jones .

**Comment by YevSent** [comment]
@michaeldyl520, this is known issue and already fixed in the 2.2-develop branch, the fix will be available in 2.2.2 and 2.1.11 Magento releases.

**Comment by lano-vargas** [comment]
@joni-jones  I have just installed 2.2.3 and this is still the case as mark166 has reported, is there any other reason why Braintree configuration cannot be set per store view?

**Comment by YevSent** [comment]
Hi, @lano-vargas, I think it's historically designed to support store|website level of payment configuration. There was no a business case to make payment configuration store's view dependable. Also, on API level there are only store and website scopes. But some options like a payment method title in some cases you can configure per store view.
