### ISSUE TITLE
PayPal module, "didgit" misspelling

### ISSUE THREAD

**Issue by djoseph74** [magento/magento2#7591]
### Preconditions

1. Enterprise Edition 2.1

### Steps to reproduce

1. When pulling up an order, the payment information has various AVS street/zip result messages. Example, AV Zip: #Y: Yes. Matched Address and five-didgit ZIP
2. Searching the Magento code base shows several occurrences of "didgit" under vendor/magento/module-paypal

### Expected result

1. Didgit is not how the word is spelled.  It should be "digit".

### Actual result

1.It shows "didgit".

**Comment by alena-marchenko** [comment]
Hi @djoseph74 

We've created MAGETWO-63491 internal ticket regarding this issue.
Thank you!

**Comment by lewisvoncken** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82550

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82657

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82658
