### ISSUE TITLE
Some navigation variables currently not changeable.

### ISSUE THREAD

**Issue by StephaneMangin** [magento/magento2#7592]
I would like to use navigation variables defined in the lib folder and used by the mixin "lib-main-navigation" to easily change navigation presentation. Unfortunately, overriding some of the variables has no effect.
Except for "@navigation__background" which actually works well.

### Preconditions
1. Magento 2.1.2
2. Php 7.0.8

### Steps to reproduce
1. Create a _theme.less file on a new module fully configured (app/design/frontend/{Provider}/{Module}/web/css/source/_theme.less)
2. Add "@navigation-level0-item__active__border-color: red;" and "@navigation__border: 5px solid red"
3. Regenerates static contents

### Expected result
1. Change the border color of the active item of level 0 with the given color and a border conform to the configuration given

### Actual result
1. No result at all :(

**Comment by StephaneMangin** [comment]
Edit:

It appears that level0 common variables do not work. but desktop version does.

//
//  Navigation variables -> No effect
//  _____________________________________________
@navigation-level0-item__font-size: 0.9em;
@navigation-level0-item__active__border-color: black;
@navigation-level0-item__active__border-style: solid;
@navigation-level0-item__active__border-width: 0 0 0 4px;
@navigation-level0-item__line-height: 30px;

//  Desktop navigation -> OK
//  ---------------------------------------------

@navigation-desktop__font-size: 0.9em;
@navigation-desktop-level0-item__active__border-color: black;
@navigation-desktop-level0-item__active__border-style: solid;
@navigation-desktop-level0-item__active__border-width: 0 0 4px;
@navigation-desktop-level0-item__padding: 0;
@navigation-desktop-level0-item__margin: 10px @indent__s + 10px 0 10px;
@navigation-desktop-level0-item__line-height: 30px;

**Comment by Flamestyle** [comment]
There is a solution? I ran into the same problem.

**Comment by pluckrose** [comment]
Having the same issue, just spent an hour trying to figure out why until I googled and came across this.

**Comment by magento-engcom-team** [comment]
@StephaneMangin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
