### ISSUE TITLE
Cannot edit staged campaign times after it has started

### ISSUE THREAD

**Issue by dvanhise** [magento/magento2#7594]
### Preconditions
Using Magento 2.1.2

### Steps to reproduce

1. In the admin, go to Content > Pages
2. Edit Home page
3. Click "Schedule New Update"
4. Add a Name, for Start Date select a time in the next few minutes, select an End Date in the future
5. Save
6. Go to Content > Staging > Dashboard
7. After the start time has passed, select the update you created and click View/Edit
8. Change the End Date to farther in the future
9. Save

### Expected result
1. The update should save with the newly selected end date

### Actual result
1. The update can't be saved because the start date is before the current time, which will always be true for a campaign that has started
2. The following errors appear:
- "Future Update Start Time cannot be earlier than current time."
- "This update not exists."
![m2-staging-error](https://cloud.githubusercontent.com/assets/1975935/20677651/bb45d6e2-b561-11e6-800e-5514ed5bb753.png)

**Comment by rganin** [comment]
@Bobrm2k3 thanks for the feedback.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
