### ISSUE TITLE
Catalog Price Rule on configurable products not working

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7595]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.11

### Steps to reproduce

1. Create a discount rule based on attribute set which have configurable products
(These configurables haven't got default options. In product listing, showing cheapest prices. In product view page load, triggering first option click)
2. Save & Apply rule
3. Wait for cron complete reindexing

### Expected result

1. Discounted configurable options prices shown on store

### Actual result

1. Discount doesn't applied to products.

**Comment by odubovyk** [comment]
Cannot reproduce
Write more detailed steps to reproduce.
Please see steps to reproduce section in https://github.com/magento/magento2/wiki/Issue-reporting-guidelines.

**Comment by andreaskoch** [comment]
I am currently investigating a similar issue reported by our backend agents.
And I found out that conditions of catalog price rules for configurable product **only apply if they match on the configurable product itself - the child products are not considered**.

## Preconditions

- Magento 2.1 CE with sample data
- Magento 2.1 EE with sample data

## Steps to reproduce

1. Create a configurable product with the price 120 €
2. Create child prodcuts with the price 130€ each
3. Put the configurable product into the category `Men/Bottoms/Pants`
4. Enable `Use for Promo Rule Conditions` for the price attribute
5. Add a price condition for the `20% off all Women’s and Men’s Pants` catalog price rule: `Price` `is` `130`
6. Run the cron jobs, reindex and flush the caches
7. Review the product details page of your new product. The catalog price rule did not apply.
8. Change the price condition to `Price` `is` `120`. Run the cron jobs, reindex and flush the caches.
9. Review the product details page of your new product. The catalog price rule did apply.

## Actual Result

The catalog price rule only matches if the conditions match the attributes found on the configurable product. The attributes of the child products are not considered.

**Catalog price rule matches the price of the configurable → The rule applies**

![magento2ee-catalog-price-rules-match-the-configurable-01](https://cloud.githubusercontent.com/assets/247364/20721392/f7742a0e-b662-11e6-9725-578aa80a3a25.png)

![magento2ee-catalog-price-rules-match-the-configurable-02](https://cloud.githubusercontent.com/assets/247364/20721418/fd141154-b662-11e6-9b21-6c55f0f4d5d4.png)

![magento2ee-catalog-price-rules-match-the-configurable-03](https://cloud.githubusercontent.com/assets/247364/20721420/002fd4c2-b663-11e6-9ac2-de355514cc5d.png)

**Catalog price rule matches the price of the simple products → The rule does not apply**

![magento2ee-catalog-price-rules-match-the-simple-01](https://cloud.githubusercontent.com/assets/247364/20721475/2b3ea404-b663-11e6-9f0d-2ca1e81e96ba.png)

![magento2ee-catalog-price-rules-match-the-simple-02](https://cloud.githubusercontent.com/assets/247364/20721480/2e0b8d50-b663-11e6-9084-f920743c14ac.png)

![magento2ee-catalog-price-rules-match-the-simple-03](https://cloud.githubusercontent.com/assets/247364/20721490/318e4eb8-b663-11e6-9adc-7932016ac7d2.png)

## Expected

I am not sure if this is a case of "works as expected", but one could say that it would be desirable if the catalog price rules should apply to the child products of a configurable and not the configurable itself.

**Comment by cizgidekiadam** [comment]
Our products created programmatically and working fine in standart checkout procedure (Select option, add to cart, checkout etc ...).

Also some rules applied on simple products which were created same way and working well.

@andreaskoch's issue may be valid for my situation. 
Because our main configurable product's price are 0$.

So if price rules applies only main product, discount can not be calculated.

**Comment by inelukipg** [comment]
I have the same issue. Catalog Price Rule does not affect "child products" when using an attribute as rule. Doesn't work even if the configurable product has an attribute that match.

In Magento 1.x there was a "enable discount to subproducts" choice...

**Comment by antbates91** [comment]
I have this issue too. I've set a blanket 50% discount to all products in a category. Simple products have the discount but configurables don't.

### Preconditions


1. Magento CE/EE Tag 2.1.3

### Steps to reproduce

1. Create a catalog price rule at 50% choosing Apply as a Percentage of the Original.
2. Apply this rule to a category using Category is 'Category Name'

### Expected result

1. The Original Price and Sale Price should be shown.

### Actual result

1. Only the Original Price (Including Tax) is shown.

#### Category Listing
![category-listing](https://cloud.githubusercontent.com/assets/8401438/22877545/c72ea76a-f1cd-11e6-970a-f8f0e57e2419.png)

#### Configurable Product
![configurable-product](https://cloud.githubusercontent.com/assets/8401438/22877546/c7359ffc-f1cd-11e6-8cf6-b27b8be17059.png)

#### Simple Product
![simple-product](https://cloud.githubusercontent.com/assets/8401438/22877547/c73665ea-f1cd-11e6-8aa0-ac6cacc39d88.png)

**Comment by cizgidekiadam** [comment]
Reason is, applying price rule, doesn't set special price for main product. So in final_price.phtml, it checks 'hasSpecialPrice()' and returns false and it skipping over next html block.

By modifying final_price.phtml, if regular price and final price differs, show it.

Tried setSpecialPrice on the fly but can not achieve this.

If product type configurable, you should use 'base_price' instead of 'regular_price' for priceModel.
In final_price.phtml:
<pre>
/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

if($block->getSaleableItem()->getTypeId()==\Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE)
{
    /** ex: \Magento\Catalog\Pricing\Price\ConfiguredPrice */
    /** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice  $priceModel */
    $priceModel = $block->getPriceType('base_price');
}
</pre>
.....
...
..

Change `if ($block->hasSpecialPrice()):`to `if ($block->hasSpecialPrice() || $priceModel->getAmount()>$finalPriceModel->getAmount()):`

I know it is dirty way but til community fix this issue, may be useful 😄

**Comment by lingwooc** [comment]
This is also related to #7624 & #9322

**Comment by benjamin-garnier** [comment]
Hello, in order to use a cart price rule on a configurable product, there is a little trick that must be done.
You will have to use the SKU of the simple product actually added in your cart (child of your config product) in the condition for your cart price rule, and then use the SKU of your configurable product in the action part of the rule.

**Comment by tanolalano** [comment]
**Precondition**

Magento 2.1.7
PHP 7.0.19

@benjamin-garnier 
I try to use yor trick, but not solves the issue
Here some screenshots:

- Condition
![condition](https://user-images.githubusercontent.com/4384863/28994999-3a753c4c-79dd-11e7-9316-8ca332688231.PNG)

- Action
![action](https://user-images.githubusercontent.com/4384863/28995000-4159223a-79dd-11e7-9520-0b5e3d157bb5.PNG)

- Cart
![cart](https://user-images.githubusercontent.com/4384863/28995002-50b50a78-79dd-11e7-871d-4276430299fa.PNG)

**Comment by benjamin-garnier** [comment]
Hello @tanolalano 
you have put several SKUs on the condition part, with the key word ALL, that means you need to have all these SKUs in your order, and a total quantity of 2 which is impossible (there are at least 3 SKUs listed, as far as I can see), so you should try to click on "ALL" and change it by "ANY". 
I hope this will help.

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by dmikevin** [comment]
But wouldn't our mini-test ($0.25 off Real Salt Lake) not have worked? That test used team, our real promo will use product type - both are attributes that exist on the simple and configurable skus.
