### ISSUE TITLE
updated_at not changing on mass update attributes.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#760]
This is inspired by a [question for Magento 1](http://magento.stackexchange.com/q/43575/146).  
I tested on Magento 2-alpha 104 and it behaves the same as in Magento 1.  
When mass updating products using the `Update attributes` from the product admin grid, the `updated_at` attribute does not change.  
It is only changed when explicitly calling `$product->save()`.  
This may be a philosophical question "Should `updated_at` be changed when bulk updating products?".  
I would say "Yes". It should be changed independent of the source of the modification.  
This is applicable for all EAV entities.  
If you have a different view on the issue, please share.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31537

**Comment by pavlindrom** [comment]
We're currently validating an extension for Magento 2 where we have a products api sync and this issue is causing us to miss data. I hope to resurrect the ticket (it's almost a year since it's been "acknowledged", and as of 2.0.2 there is no change.

We are considering adding a observer to the update action, and set the updated_at for all the affected products, but as it will be hacky, we'd rather have it part of the product.

**Comment by miguelbalparda** [comment]
+1

**Comment by erikhansen** [comment]
I would agree with @tzyganu that the `updated_at` field should get updated regardless of the source of the change.

**Comment by gtaylor44** [comment]
Any updates on this issue? The `updated_at` column should get updated if you change details about a product, etc. Surely this is an oversight?

**Comment by samtay** [comment]
+1

**Comment by RUjmiak** [comment]
@tanya-soroka @vkorotun Product updated_at not changing also on price change. 

Magento: CE2.0.1

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/updated-at-not-changing-on-mass-update-attributes/idi-p/47083).

**Comment by sajidunnar** [comment]
Hello 

I am on Magneto 2.1.2 and facing same issue , like if we update products by mass update or even single it dont change updated_at in db

**Comment by aliomattux** [comment]
Hello,
We are using Magento 2.3.3 and faced this behavior. IMO, this is a bug not an improvement. updated_at is a system feature that should reliably and accurately record the date and time an object is updated, assuming it is not done by an SQL query. By allowing either update attributes or update status features in the admin to not change this timestamp, it defeats the integrity of the data and developers/administrators cannot rely at all on the field.

As an example, the merchandising department is wanting to know why the product is marked disabled when it should be active, however we cannot even tell when the change was made. I tested and verified that the date and time was not updated - as if it wasn't updated at all. Every other enterprise system that I work with has a reliable method of updating the date and time if the feature exists.

**Comment by ioweb-gr** [comment]
I'm in a similar predicament and thinking of adding db triggers for this e.g. but for every eav table required 

```
CREATE TRIGGER trg_update_catalog_product_entity_updated_at
AFTER INSERT ON db_live.catalog_product_entity_decimal
FOR EACH ROW
BEGIN
    UPDATE db_live.catalog_product_entity
    SET updated_at = CURRENT_TIMESTAMP()
    WHERE entity_id = NEW.entity_id;
END;
```

I'm curious to what others have tried for fixing this issue. @aliomattux did you manage to fix it in your case?
