### ISSUE TITLE
Product Repository Shows 'Requested product doesn't exist' After Setting is_in_stock = 0

### ISSUE THREAD

**Issue by rahulvramesh** [magento/magento2#7606]
### Preconditions

1. Magento CE  2.1.2

### Steps to reproduce

1. Load The A Simple Product To Product Repository 
2. Using `setQuantityAndStockStatus` Set `Quantity` 1 And `is_in_stock` 0
3. Save Product
4. Load Product Again 

### Expected result

1. It Should Show Quantity 

### Actual result

1. `</pre>1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested product doesn't exist

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested product doesn't exist
#0 /var/www/youapparel-web/var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(37): Magento\Catalog\Model\ProductRepository->getById(NULL, false, NULL, false)
#1 /var/www/youapparel-web/app/code/Faya/CustomSwatch/Controller/Stock/Request.php(149): Magento\Catalog\Model\ProductRepository\Interceptor->getById(NULL)
#2 /var/www/youapparel-web/var/generation/Faya/CustomSwatch/Controller/Stock/Request/Interceptor.php(24): Faya\CustomSwatch\Controller\Stock\Request->execute()
#3 /var/www/youapparel-web/vendor/magento/framework/App/Action/Action.php(102): Faya\CustomSwatch\Controller\Stock\Request\Interceptor->execute()
#4 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(70): Faya\CustomSwatch\Controller\Stock\Request\Interceptor->___callParent('dispatch', Array)
#6 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Faya\\CustomSwat...', 'dispatch', Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Array, 'customer-app-ac...')
#7 /var/www/youapparel-web/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Faya\\CustomSwat...', 'dispatch', Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Array, 'contextPlugin')
#10 /var/www/youapparel-web/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Faya\\CustomSwat...', 'dispatch', Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Array, 'storeCheck')
#13 /var/www/youapparel-web/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Faya\\CustomSwat...', 'dispatch', Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Array, 'tax-app-action-...')
#16 /var/www/youapparel-web/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Faya\\CustomSwat...', 'dispatch', Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Array, 'weee-app-action...')
#19 /var/www/youapparel-web/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Faya\CustomSwatch\Controller\Stock\Request\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Faya\CustomSwatch\Controller\Stock\Request\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/youapparel-web/var/generation/Faya/CustomSwatch/Controller/Stock/Request/Interceptor.php(65): Faya\CustomSwatch\Controller\Stock\Request\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/youapparel-web/vendor/magento/framework/App/FrontController.php(55): Faya\CustomSwatch\Controller\Stock\Request\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#26 /var/www/youapparel-web/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 /var/www/youapparel-web/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#32 /var/www/youapparel-web/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /var/www/youapparel-web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#35 /var/www/youapparel-web/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /var/www/youapparel-web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /var/www/youapparel-web/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /var/www/youapparel-web/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /var/www/youapparel-web/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#40 /var/www/youapparel-web/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))`

**Comment by rahulvramesh** [comment]
Any Update On The Issue ?

**Comment by magento-engcom-team** [comment]
@rahulvramesh, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
