### ISSUE TITLE
Please add .DS_Store to gitignore

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7608]
This is added by MAC every time

**Comment by veloraven** [comment]
@craigcarnell thank you for your submission. 
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.
What you describe it is not an issue, it is an improvement. So it can not be treated via GitHub.
Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
Another possible solution - if you make a pull request for this task yourself.

**Comment by hostep** [comment]
@craigcarnell: We add this to our global .gitignore file, not for every project separately, see: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by cscd98** [comment]
@hostep Thank you
