### ISSUE TITLE
Suggestion: Better static content deploy with fallback to old files?

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#7609]
### Preconditions
1. Install Magento 2.1.x
2. Run static content deployment

### Steps to reproduce
1. Run static content deploy again

### Expected result
1. The frontend should look nice until the deployment is finished (no downtime)

### Actual result
1. The frontend has no styles since all files have beed deleted

### Possible solution / suggestion

We run a bash script for deployment, which moves the complete pub/static directory to pub/static_old and use a rewrite in pub/.htaccess to check if the file exists in the "backup" if not in the requested url:

```
<IfModule mod_rewrite.c>

    RewriteEngine on

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-l
    RewriteCond %{REQUEST_URI} ^.*/static/.*
    RewriteRule ^static/(.*) static_old/$1 [L]

</IfModule>
```

```
rm -rf pub/static_old/
mv pub/static/ pub/static_old/

php bin/magento setup:static-content:deploy de_DE en_US nl_NL fr_FR
```

With this solution, the frontend isn't missing any styles or other files until the complete process is finished and can be used by the customer the whole time without any issues.

**Comment by veloraven** [comment]
@klein0r     thank you for your submission. 
What you describe is more like improvement than an issue.
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by choukalos** [comment]
Hello @klein0r ,

We've been asked by a # of our SI's doing Capistrano & Docker docker deployments along with our own Cloud team to support a 2 phase deployment process where we can do a build (composer, compile, static asset deploy) on a development machine (so no down time) who's results can be checked in via Git.  Then on your production server you'd take a short downtime to update the code and db schema (git pull, then bin/magento upgrade or install). 

Would that address your needs?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by PivitParkour94** [comment]
Was this made into a feature request in the forum somewhere? Having a backup static assets system would be an absoluter lifesaver in a number of situations.

@veloraven  I understand that having the issue in github is the wrong place, but rather than just closing it, can we ensure this is linked to a feature request in the forum where the discussion can continue?
