### ISSUE TITLE
magento 2.1.0 force sign in customer in admin 

### ISSUE THREAD

**Issue by jothibasuj** [magento/magento2#7610]
I just want to know Force sign in suppose to work in Magento backend under customer edit section. when I try to click force sign in it says 'The customer has no token'.
### Preconditions

Magento 2.1.0
 

### Steps to reproduce

1. Login to Magento backend and click CUSTOMER tab.
2. Edit any one of the customer
3. Click 'Force sign in' in the top navigation

### Expected result

1. We don't know how it supposed to work. We thought it suppose to logout the customer if he already logged in frontend.

### Actual result

The customer has no token

**Comment by veloraven** [comment]
@jothibasuj thank you for your submission.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
