### ISSUE TITLE
Modules - [Zend_Json_Exception] Syntax Error

### ISSUE THREAD

**Issue by Joe-Whitehead** [magento/magento2#7625]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.9
3. Nginx
4. PHP-FPM

### Steps to reproduce

1. Using the command line attempt to enable, disable or uninstall a module
`php bin/magento -c module:enable VendorName_ModuleName`

### Expected result

1. Module successfully enabled, disabled or uninstalled
```
The following modules have been enabled:
- VendorName_ModuleName

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Generated static view files cleared successfully.
```

### Actual result

1. An error is thrown
```
[Zend_Json_Exception]
Decoding failed: Syntax error
```
I have ran the command with the -v flag which gives the following output:
```
Exception trace:
 () at vendor/magento/zendframework1/library/Zend/Json.php:97
 Zend_Json::decode() at vendor/magento/framework/Module/PackageInfo.php:85
 Magento\Framework\Module\PackageInfo->load() at vendor/magento/framework/Module/PackageInfo.php:208
 Magento\Framework\Module\PackageInfo->getRequire() at vendor/magento/framework/Module/DependencyChecker.php:132
 Magento\Framework\Module\DependencyChecker->createGraph() at vendor/magento/framework/Module/DependencyChecker.php:95
 Magento\Framework\Module\DependencyChecker->checkDependencyGraph() at vendor/magento/framework/Module/DependencyChecker.php:82
 Magento\Framework\Module\DependencyChecker->checkDependenciesWhenEnableModules() at vendor/magento/framework/Module/Status.php:95
 Magento\Framework\Module\Status->checkConstraints() at setup/src/Magento/Setup/Console/Command/AbstractModuleManageCommand.php:92
 Magento\Setup\Console\Command\AbstractModuleManageCommand->execute() at vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at bin/magento:23
```

Also, thinking this may be an error with my composer.json file (Although I get this error with the Magento-built modules aswell)
I ran a composer validate on the composer.json file which only shows a warning about naming conventions but the file should still work.
```
composer validate app/code/VendorName/ModuleName/composer.json
app/code/VendorName/ModuleName/composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
Name "VendorName/ModuleName" does not match the best practice
```

This only started happening a few days ago after a composer update. Is anyone else having any issues with this? Any suggestions as to what could be going wrong?

**Comment by shiftedreality** [comment]
Hi @Joe-Whitehead 

I was unable to reproduces this error in composer 2.1.2 version and latest develop brnach.
I also tried `composer self-update --snapshot` with latest Composer version and still no success.

Please, attach your module's `composer.json`

**Comment by Joe-Whitehead** [comment]
Hi @shiftedreality,

Here is one of the modules composer.json
```
{
  "name": "MiModule/Contact",
  "description": "Contact",
  "require": {
      "php": "~5.5.0|~5.6.0|~7.0.0",
      "magento/framework": "100.0.*",
      "magento/module-ui": "100.0.*",
      "magento/module-config": "100.0.*"
  },
  "type": "magento2-module",
  "version": "1.0.1",
  "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
  "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "MiModule\\Contact\\": ""
        }
    }
```

As stated this is also occurring when dealing with Magento modules (for example Magento_Review).

regards,
Joe

**Comment by shiftedreality** [comment]
@Joe-Whitehead 

I have the same issue with naming in your `composer.json`, but no Exception.
Maybe, you have some outdated version of Zend_Decode?
Could you run `composer update` for Magento project?

**Comment by Joe-Whitehead** [comment]
@shiftedreality 

Updated Composer
```
Loading composer repositories with package information 
Updating dependencies (including require-dev)          
  - Removing symfony/stopwatch (v3.1.7)
  - Installing symfony/stopwatch (v3.2.0)
    Downloading: 100%

  - Removing symfony/finder (v3.1.7)
  - Installing symfony/finder (v3.2.0)
    Downloading: 100%

  - Removing friendsofphp/php-cs-fixer (v1.13.0)
  - Installing friendsofphp/php-cs-fixer (v1.13.1)
    Downloading: 100%

Writing lock file
Generating autoload files
```

Same issue still continues.

**Comment by shiftedreality** [comment]
I think, It may be caused by 3rd-party module, after look at
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/PackageInfo.php#L82

Could you please remove all non-Magento modules and try to disable/enable one of Magento's modules?

**Comment by Joe-Whitehead** [comment]
@shiftedreality 
Yes, it was a non-Magento module, the composer.json was incorrect within it.
Must have missed the error when looking through the files when checking them over.

Thanks for your assistance.

**Comment by cmuench** [comment]
I had the same issue with a PSR-4 autoloader. The sources of my magento module are organized in a "src" folder. In this case the module directory is one level higher as the composer.json file.
```
.
├── composer.json
└── src
    ├── etc
    │   └── module.xml
    └── registration.php
```

For me the issue is **not** fixed!
