### ISSUE TITLE
Event customer_data_object_login triggered twice

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#7629]
Event ```customer_data_object_login``` triggered two times on frontend
### Preconditions
1. Magento 2.1.2 installed via composer
2. Module that contains:
- etc/frontend/events.xml file with following content: 
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="customer_data_object_login">
        <observer name="myModule_customer_login" instance="MyNameSpace\MyModule\Observer\LogLogin" />
    </event>
</config>
```
- Observer/LogLogin.php file with following content:

```php

<?php

namespace MyNameSpace\MyModule\Observer;

use Magento\Customer\Api\Data\CustomerInterface;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Psr\Log\LoggerInterface;

/**
 * Plugin for top menu block
 */
class LogLogin implements ObserverInterface
{
    /** @var LoggerInterface */
    protected $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * bindCustomerLogin
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer)
    {
        /** @var CustomerInterface $customer */
        $customer = $observer->getEvent()->getCustomer();

        $this->logger->info('Customer Logged in', [
            'customer_id' => $customer->getId(),
        ]);
    }
}

```
### Steps to reproduce
1. Go to frontend
2. Login to your account

### Expected result
1. We will have one log that customer logged in

### Actual result
1. Log file contains two lines that customer logged in.

Looks like this issue caused by triggering these events in two places:
https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Customer/Model/AccountManagement.php#L480
https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/app/code/Magento/Customer/Model/Session.php#L433

**Comment by ihor-sviziev** [comment]
@okorshenko have you any ideas how we can fix it without braking backward compatibility?

We can remove this line:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/AccountManagement.php#L490

And keep it in https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Session.php#L435
But it will brake backward compatibility

**Comment by ihor-sviziev** [comment]
@okorshenko @slavvka @maghamed I could prepare PR if idea that I described is good. Could you review it?

**Comment by okorshenko** [comment]
I @ihor-sviziev sorry for the delay. I will review the issue ASAP and provide you feedback. Thank you

**Comment by okorshenko** [comment]
Hi @ihor-sviziev 

I agree that we don't need to trigger the same event twice in this case. 
I would recommend to deprecate this event in both places. Introduce 2 different events if needed. We need to analyze the code where events are triggered. We already have some other events there, so may be the information from other events is enough to run the 3rd party logic.

Review the existing observers and subscribe existing observers on the corresponding new event or convert to the plugin if needed. 

So we can not remove the event from the code. We can just deprecate it and provide an alternative solution.

**Comment by magento-engcom-team** [comment]
@ihor-sviziev, thank you for your report.
We've created internal ticket(s) MAGETWO-81725 to track progress on the issue.

**Comment by ihor-sviziev** [comment]
I think it's not worth to fix this issue. I'm closing it.
