### ISSUE TITLE
Can't update state for billing and shipping address at admin order view

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#7632]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.9, MySql 5.6.27

### Steps to reproduce

1. Click on any order in admin
2. click on Edit next to the billing or shipping address.
3. Change the state of the address.
4. Click on save order address

### Expected result

1. updated the state of the address.

### Actual result

1. State disappear
![screenshot 16](https://cloud.githubusercontent.com/assets/17633236/20761053/96077810-b6d6-11e6-92d8-be23b238ef87.png)

**Comment by olysenko** [comment]
Hi, thank you for your report. Your issue duplicates [4000](https://github.com/magento/magento2/issues/4000). The fix was delivered to develop branch. Issue is closed as fixed. Feel free to reopen it if you still have the same problem

**Comment by Ctucker9233** [comment]
@Olysenko will that fix be in 2.1.3?

**Comment by olysenko** [comment]
There is no plans for backporting it into 2.1.x versions, try fix for develop referenced in [4000](https://github.com/magento/magento2/issues/4000).

**Comment by Ctucker9233** [comment]
@olysenko So an issue that was reported as being in a 2.1.x version has a fix that is not planned to make it into a 2.1.x version? What kind of logic is that? 2.1.3 isn't even released yet. Surely there is time to schedule it for one of the 2.1.x releases. How can you expect people to keep upgrading when their issues don't get fixed and released? The develop branch is so broken as it is, it's a risk to even try to implement a fix from there. Believe me, I've tried.
