### ISSUE TITLE
Authorize.net Direct Post: Authorize.net does not return nor receive a response at random 

### ISSUE THREAD

**Issue by duffner** [magento/magento2#7633]
At random, a request made to Authorize.net Direct Post fails.  As seen in the Magento logs, attached Magento records that a request has been made, and no response is received from Authorize.net.  
The customer receives an infinite spinning wheel, which I found three relating tickets 
#6474,#5642, #4813.  These only address the result of no response which is the wheel.  I checked Authorize.net for these failures and Authorize.net never received these transactions even though the Magento logs say otherwise.  Reminder: This issue only occurs at random and I cannot find any inconsistencies that would cause a failure.

### Preconditions
1.  Magento version 2.1.2
2. PHP7, Ngnix 

### Expected result
1.  Magento Sends Request to Authorize.net
2. Magento Receives Post back from Authorize.net 
3.) Order is created

### Actual result
1.  Sadly, I cannot reproduce this error as it's completely random and based on what I'm reading.  My guess is that these infinite wheel spinning is caused from lack of Authorize.net response 
2. Customer goes through transactional process
3. Customer clicks place order 
4. Customer receives infinite spinning wheel
5. Order is created in Magento as Pending
6. In logs no response is received. 

Example Request
[2016-11-04 04:42:10] main.DEBUG: array ( 
'request' => 
array ( 
'x_version' => '3.1', 
'x_delim_data' => 'FALSE', 
'x_relay_response' => 'TRUE', 
'x_test_request' => 'FALSE', 
'x_login' => '****', 
'x_method' => 'CC', 
'x_relay_url' => 'https://www.domain.com/authorizenet/directpost_payment/response', 
'x_type' => 'AUTH_CAPTURE', 
'x_fp_sequence' => '97349', 
'x_invoice_num' => '1000000105', 
'x_amount' => 218.62, 
'x_currency_code' => 'USD', 
'x_tax' => '0.00', 
'x_freight' => '5.62', 
'x_first_name' => 'First Name', 
'x_last_name' => 'Last Name', 
'x_company' => '', 
'x_address' => '17477 Address here', 
'x_city' => 'City', 
'x_state' => 'California', 
'x_zip' => '98265', 
'x_country' => '', 
'x_phone' => 'XXXXXXXXXX', 
'x_fax' => '', 
'x_cust_id' => '', 
'x_customer_ip' => '76.95.XXX.XX', 
'x_customer_tax_id' => '', 
'x_email' => 'email@yahoo.com', 
'x_email_customer' => '0', 
'x_merchant_email' => '', 
'x_ship_to_first_name' => 'First Name', 
'x_ship_to_last_name' => 'Last Name', 
'x_ship_to_company' => '', 
'x_ship_to_address' => '17477 Address here', 
'x_ship_to_city' => 'City', 
'x_ship_to_state' => 'California', 
'x_ship_to_zip' => '92886', 
'x_ship_to_country' => '', 
'x_po_num' => '', 
'x_fp_timestamp' => 1478234530, 
'x_fp_hash' => 'dfd9d85a8f4d76948374507876d6c0fc', 
), 
) {"is_exception":false} []

No response in the logs, even though other transactions have receive a response.

**Comment by dyushkin** [comment]
Hello @duffner!

Can you please show response which is contains in transact.dll on checkout page, when issue appears? Thanks.

**Comment by duffner** [comment]
@dyushkin, I cannot replicate the issue, I only see the result of the error.  Is there a way I can record this data to a log for review on the next occurrence?

**Comment by duffner** [comment]
@dyushkin, According to a recent notice I've found in Authorize.net,  DPM is deprecated.  
http://www.authorize.net/content/dam/authorize/documents/SIM_guide.pdf

What is Magento's plan for this news? 

October 2016 
`Deprecated the DPM method in favor of our newer method, Accept.js, a
JavaScript payment form. Accept.js is a modern implementation that doesn’t
require a post-back. With Accept.js, developers have control over the user
experience without sending PCI data through their servers. Accept.js can be
used like any other payment type in the Authorize.Net API.
We strongly encourage new development using Accept.js instead of DPM,
and developers with existing DPM implementations should consider moving
to Accept.js.`

`We now offer Accept.js, a JavaScript replacement for Direct Post Method
(DPM). Accept.js is a modern implementation that doesn’t require a postback.
With Accept.js, developers have control over the user experience
without sending PCI data through their servers. Accept.js can be used like
any other payment type in the Authorize.Net API.
We strongly encourage new development using Accept.js instead of DPM,
and developers with existing DPM implementations should consider moving
to Accept.js.`

**Comment by YevSent** [comment]
Hi, @duffner, we can't reproduce your issue and need to get more details about it.

>  Is there a way I can record this data to a log for review on the next occurrence?

You can't log response from `transact.dll`, you should check it manually in browser network log.

> What is Magento's plan for this news?

We have plans for Authorize.net API changes, but can't provide any estimate when they will be published.

**Comment by YevSent** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks.
If you can reproduce this issue, please, be free to reopen it.

**Comment by ianfp** [comment]
@joni-jones Is there an open Github issue I can follow to track the progress of the switch to the new Authorize.net API? DPM is not a good option for my organization, and I was shocked to discover that it is the only Authorize.net option in Magento 2!

**Comment by YevSent** [comment]
Hi, @ianfp, there is no any tickets on Github about updating Authorize.net API, only internal ticket `MAGETWO-53511`. However, now we don't develop any new features for Authorize.net (including the API updating) and I can't provide any estimation for these changes.

**Comment by ianfp** [comment]
@joni-jones Is there value in having an open Github issue for `MAGETWO-53511` so you can gauge whether this is a priority for the wider community? I could open one.

**Comment by YevSent** [comment]
I don't think that this issue would make sense because updating this integration depends on arrangements between Magento Inc. and Authorize.net.

**Comment by duffner** [comment]
Has this been solved yet?  This issue also plagues Magento 1.14.x

**Comment by duffner** [comment]
https://magento.stackexchange.com/questions/19826/authorize-net-direct-post-sometimes-fails-in-chrome

A magento 1 example

**Comment by duffner** [comment]
This issue still occurs at random, and is specific to Magento's implementation, as I've never had it occur on other platforms.  I was able to replicate a single time... and the transact.dll is empty within Magento 2

**Comment by valuead** [comment]
magento 2.2.6 
**Card gets captured** but NO thank you screen. QTY goes down. Error.

**Comment by duffner** [comment]
@valuead, So about a week ago, Authorize.net released an update that affected customers, in this case, Magento negatively.  This occurred for a few days until Authorize.net reviewed this behavior.  I only bring this up, because while the symptoms are identical to the case I presented above, your timing aligns with the more recent issue that happened.

**Comment by draganbt** [comment]
Any solution for this.
We have the same problem and sometimes response not receive from Authorize.net but order is created in Mageneto with status Pending, but in Authorize account orders is settled succefulll.
This happen sometimes not on all orders. Also may happen to receive response orders is created in Magento with status Pending instead of Proccessing status.
We use Authorize DPM Authorize and Capture  methot on Magento 2.1

**Comment by frankhdz22** [comment]
I have this very issue and it is so frustrating working with magento. These threads always lead no where. I have the exact same issue with Authorize sometimes the post back to authorizenet/directpost_payment/response never happens. It is random and no clues from the logs. The post back simply never happens randomly.
