### ISSUE TITLE
Disabled "All Store Views" shows product in some other configured StoreViews (and hide it from the correct one)

### ISSUE THREAD

**Issue by JonyD** [magento/magento2#7634]
I found out that a product in "All Store Views" could be configured as "Disabled"  and that fact would not influence its visibility in the other SVs.
It seems the "Default Store View" 'controls' all the other SVs.

### Preconditions
1. Versions: Magento 2.1.2, PHP 5.6.28, mySQL 5.6.33, AWS linux image m2.medium
2. Also, I am using the Luma theme.

### Steps to reproduce
1. Create 2 Store Views (SV), for example, German and French
2. configure the 'Bags' category: in Stores > Attribute Set, drag Unassigned Attribute 'manufacturer' to "Attributes". Set it with the following setup:
3. in Store > Attributes > Product , add a new product with title, image, stock value  > 0, Category  = Bags, mark it as new product
4. in Stores > Attributes > Product, search for the "manufacturer". Configure it as a Dropdown and Add the "Manage Options (Values of Your Attribute)":
Add "Erima" to Admin and German SV
Add "Adidas" to all the 4 SVs (Admin, Default, German French)
Scope: store view
Add to column options: yes
use in filter options: yes
use in search: yes
Visible in Advanced Search: yes
Use in Search Results Layered Navigation: yes
Visible on Catalog Pages on Storefront: yes
Used in Product Listing: yes
Used for Sorting in Product Listing: yes
5. Use the following configuration (in Backend> Products> Inventory > Catalog):

- All Store Views  "enable product" [website] : no
- Default Store View -"enable product" [website] : yes 
- German Store View  -"enable product" [website] : yes 
- French Store View - active: (use default values)

### Expected result
Customer view (the shop frontend) SVs looks like this:
- Default Store View -> product is visible
- German Store View -> product is visible
- French Store View  -> product is not visible

### Actual result
Customer view (the shop frontend) SVs looks like this:
- Default Store View -> product is visible
- German Store View -> **product is not visible**
- French Store View  -> product is not visible

So, I see 2 problems here:

1. The product should be visible in the German Store View.
2. It seems the French SV is using the values form "All Store Views" although it says "Use Default Values".
There is a very confusing naming here. The "Use Default Values" checkbox really uses the values from "All Store Views", when one would expect the values from the Default SV.

If this is no bug, I propose :
- either changing the "Default Store View" name to something that has does not have the word "Default"
- or renaming the string "Use Default Values" to something like "use value from 'All Store Views'

**Comment by veloraven** [comment]
@JonyD thank you for your report.
We were not able to reproduce this issue. Could you confirm that it is still reproduces on the ver. 2.1.7?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
