### ISSUE TITLE
extension attributes doesn

### ISSUE THREAD

**Issue by RafalR86** [magento/magento2#7636]
### Preconditions

1. Magento 2.1.2
2. PHP 5.6.27-1
3. developer mode

### Steps to reproduce

1. Add file extension_attributes.xml to custom module etc directory
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Checkout\Api\Data\PaymentDetailsInterface">
        <attribute code="producer" type="string" />
    </extension_attributes>
</config>
```
2. Clear cache and generation directory

### Expected result

1. New interface PaymentDetailsExtensionInterface.php in directory var/generation/Magento/Checkout/Api/Data

### Actual result

1. no autogenerated PaymentDetailsExtensionInterface.php in  directory var/generation/Magento/Checkout/Api/Data after checkout process

**Comment by RafalR86** [comment]
After many fightings with it solution for this problem was just reediting file extension_attributes.xml. I haven't changed anything, just create the same file with the same content was enough. Now i've autogenerated PaymentDetailsExtensionInterface.php in directory var/generation/Magento/Checkout/Api/Data after checkout process. Here http://magento.stackexchange.com/questions/118281/magento-2-extension-attributes-interface is similar situation

**Comment by magento-engcom-team** [comment]
@Rudolfff, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
