### ISSUE TITLE
Please Add Option "Decimal Enable / Disable"

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#7639]
Hello. This is not an issue. But I think it can be an issue too for Magento 2.1

### Preconditions
Magento 2.1.2
I have a suggestion, if Magento have an option on setting panel for Decimal price to enable or disable. It because, some of currency doesn't need a decimal. Such as for IDR it only price without decimal. 

### Steps to reproduce
No step to reproduce because there is no option on setting panel for disable / enable decimal.

### Expected result
For some currency have decimal such as EUR, USD, GBP.
For some currency without have decimal such as IDR 

### Actual result
No option for disable decimal on homepage or product page. So, for currency without decimal always have 2 zero point behind price.

**Comment by veloraven** [comment]
@jurpro thank you for your submission. 
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
