### ISSUE TITLE
when i click blocks from content menu following error coming

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#764]
Recoverable Error: Argument 2 passed to Magento\Ui\ConfigurationStorage::addDataCollection() must be an instance of Magento\Framework\Data\CollectionDataSourceInterface, ins
Argument 2 passed to Magento\Ui\ConfigurationStorage::addDataCollection() must be an instance of Magento\Framework\Data\CollectionDataSourceInterface, instance of Magento\Cms\Model\Resource\Block\Grid\Collection given, called in /var/www/html/magento2/app/code/Magento/Ui/Listing/View.php on line 139 and defined in /var/www/html/magento2/app/code/Magento/Ui/ConfigurationStorage.php on line 180
#0 /var/www/html/magento2/app/code/Magento/Ui/ConfigurationStorage.php(180): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 2 pass...', '/var/www/html/m...', 180, Array)
#1 /var/www/html/magento2/app/code/Magento/Ui/Listing/View.php(139): Magento\Ui\ConfigurationStorage->addDataCollection('cms_block_listi...', Object(Magento\Cms\Model\Resource\Block\Grid\Collection))
#2 /var/www/html/magento2/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(165): Magento\Ui\Listing\View->prepare()
#3 /var/www/html/magento2/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(150): Magento\Framework\View\Element\UiComponentFactory->prepare(Object(Magento\Ui\Listing\View))
#4 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(120): Magento\Framework\View\Element\UiComponentFactory->createUiComponent('listing', 'cms_block_listi...', Array)
#5 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(94): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'cms_block_listi...', Array)
#6 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(84): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout.php(298): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/html/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(178): Magento\Framework\View\Layout->generateElements()
#9 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(147): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Builder.php(75): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/html/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(81): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config.php(173): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config.php(185): Magento\Framework\View\Page\Config->build()
#14 /var/www/html/magento2/lib/internal/Magento/Framework/App/View.php(188): Magento\Framework\View\Page\Config->publicBuild()
#15 /var/www/html/magento2/lib/internal/Magento/Framework/App/View.php(132): Magento\Framework\App\View->loadLayoutUpdates()
#16 /var/www/html/magento2/app/code/Magento/Backend/Model/View.php(62): Magento\Framework\App\View->loadLayout(NULL, false, true, true)
#17 /var/www/html/magento2/app/code/Magento/Cms/Controller/Adminhtml/Block.php(58): Magento\Backend\Model\View->loadLayout()
#18 /var/www/html/magento2/app/code/Magento/Cms/Controller/Adminhtml/Block/Index.php(38): Magento\Cms\Controller\Adminhtml\Block->_initAction()
#19 /var/www/html/magento2/var/generation/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(113): Magento\Cms\Controller\Adminhtml\Block\Index->execute()
#20 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Action.php(118): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->execute()
#21 /var/www/html/magento2/app/code/Magento/Backend/App/AbstractAction.php(247): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/magento2/var/generation/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(48): call_user_func_array(Array, Array)
#24 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(83): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___callParent('dispatch', Array)
#25 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(76): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Array, 'adminAuthentica...')
#26 /var/www/html/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(113): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(81): call_user_func_array(Array, Array)
#29 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(76): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Array, 'designLoader')
#30 /var/www/html/magento2/app/code/Magento/Core/App/Action/Plugin/Design.php(57): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 [internal function]: Magento\Core\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(81): call_user_func_array(Array, Array)
#33 /var/www/html/magento2/var/generation/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(88): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Array, 'adminMassaction...')
#34 /var/www/html/magento2/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(51): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Cms\Controller\Adminhtml\Block\Index\{closure}(Object(Magento\Framework\App\Request\Http))
#35 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/magento2/var/generation/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(93): call_user_func_array(Array, Array)
#37 /var/www/html/magento2/var/generation/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(128): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___call('dispatch', Array, Array)
#38 /var/www/html/magento2/lib/internal/Magento/Framework/App/FrontController.php(63): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#40 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(48): call_user_func_array(Array, Array)
#41 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(83): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#42 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(88): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#43 /var/www/html/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(93): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
#44 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(93): call_user_func_array(Array, Array)
#46 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(115): Magento\Framework\App\FrontController\Interceptor->___call('dispatch', Array, Array)
#47 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(133): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(270): Magento\Framework\App\Http->launch()
#49 /var/www/html/magento2/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#50 {main}

**Comment by verklov** [comment]
@sivajik34, looks like we have already fixed this issue and delivered the fix to GitHub. Please verify and let us know. Meanwhile we are closing this ticket as resolved. Thank you!
