### ISSUE TITLE
X-Magento-Tags header containing whitespaces causes exception

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#7640]
When the header X-Magento-Tags contains whitespaces, an `Zend\Http\Header\Exception\InvalidArgumentException` is being thrown when the full page cache is enabled. Block IDs can contain whitespaces due to reformatting in layout XML files, because of the 80 character line length limit.

### Preconditions
Using Magento 2.1.2 with nginx and PHP7

### Steps to reproduce
1. Have layout files with `block_id` arguments that contain whitespaces (see image below)
2. Enable full page cache
3. Reload a page

### Expected result
The page should be loaded correctly

### Actual result
An error `Zend\Http\Header\Exception\InvalidArgumentException: Invalid header value detected` is being thrown.

### Possible fix
Filter out whitespaces within `argument` tags when reading XML layout files.

### Attachment
![image](https://cloud.githubusercontent.com/assets/6915990/20785012/1fd0e096-b79e-11e6-9f12-1e300c0cd16c.png)

**Comment by ihor-sviziev** [comment]
We had a lot issues like this in M1, that were caused by automatic xml formatting in PhpStorm. Would be great to add trim values, it will fix this issue.

**Comment by redelschaap** [comment]
It would. I couldn't find the right place to add trim functions so quickly, otherwise I would have made a pull request.

**Comment by magento-engcom-team** [comment]
@redelschaap, thank you for your report.
We've created internal ticket(s) MAGETWO-81249 to track progress on the issue.

**Comment by okorshenko** [comment]
@redelschaap the issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82887

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82983

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82998
