### ISSUE TITLE
Attribute set drop down list broken. 

### ISSUE THREAD

**Issue by safiulrehman** [magento/magento2#7641]
When I tried to add a new product manually in magento 2.1.1 on the very first line there is a drop down list to choose an Attribute set. That drop down list is broken and I can't see any attribute set in there even it became un clickable.  Some times when I clear magento's cache and deploy static content it is starting working but some times it is not.
when this dropdown list not working then below in add Category drop down list is also stoped working.
Please help me to solve this issue.

### Preconditions

1. v2.1.1
2. php v7.0

### Steps to reproduce

1. Go to product
2. Catalog  
3. Add new product

### Expected result

1. 
![image](https://cloud.githubusercontent.com/assets/24288707/20785103/28431ce0-b7c0-11e6-83c1-948f8bd59e75.png)

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/24288707/20785036/d2fe621c-b7bf-11e6-9baa-68a54db923a1.png)

**Comment by olysenko** [comment]
Hi, thank you for your report. We need more information to reproduce this issue. Doyou have any JS errors in Console or some any other error? It will help us a much

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
