### ISSUE TITLE
trigger_recollect never gets reset

### ISSUE THREAD

**Issue by yariksheptykin** [magento/magento2#7643]
When Cart Price Rules are applied to existing shopping carts (quotes) "trigger_recollect" [flag is set to 1](https://github.com/magento/magento2/blob/8d0dc6f55b237e9b181f65815a3383c08f6b8b4c/app/code/Magento/Quote/Model/ResourceModel/Quote.php#L221). This in turn triggers [totals collection](https://github.com/magento/magento2/blob/8d0dc6f55b237e9b181f65815a3383c08f6b8b4c/app/code/Magento/Quote/Model/Quote.php#L2356-L2358) every time when a quote is loaded. This might be OK and necessary as long as Cart Price Rules are active and applied. However after disabling or at least removing the rules, "trigger_recollect" should be reset to avoid unnecessary calculation of totals.

### Preconditions
1. Magento 2.1.2
2. PHP 7.0.8-0ubuntu0.16.04.3
3. mysql  5.7.16, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce
1. Register in the shop.
2. Place anything into the shopping cart.
3. In BE create a Cart Rule that matches you cart contents and apply a shipping discount.
4. Make sure the rules are applied by running the cron job.
5. Now disable the rule and remove it completely in BE
6. Make sure the changes are applied by running the cron job.
7. Now place a breakpoint / or add `throw new \Exception("This should not be run anymore");` [here](https://github.com/magento/magento2/blob/8d0dc6f55b237e9b181f65815a3383c08f6b8b4c/app/code/Magento/Quote/Model/Quote.php#L2357).
8. Observe that the code is executed.

### Expected result
1. The code is not executed after disabling / removing the rules.

### Actual result
1. The code is executed.

**Comment by magento-engcom-team** [comment]
@yariksheptykin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
