### ISSUE TITLE
Creditmemo Refund Online via API cannot work

### ISSUE THREAD

**Issue by BlitzInternet** [magento/magento2#7648]
### Preconditions

1. Mage 2.1.2
2. PHP 7
3. some Payment Gateway Module (in our case https://www.sellxed.com/shop/en/magento-payment-extension-postfinance.html)

### Steps to reproduce

1. Create an order with online creditcard payment (via backend or frontend)
2. Create an invoice for that order (via api or backend)
3. Create a credit memo via API, with offlineRequested : false
[creditmemo-api-request.txt](https://github.com/magento/magento2/files/624410/creditmemo-api-request.txt)

### Expected result

1. Refunded Online

### Actual result

1. Refunded Offline

The problem is, that despite the invoice_id being set, the invoice instance is never loaded and set, and thus the credit memo is always created offline.

**Comment by olysenko** [comment]
Hi, API services for management invoice, shipment, creditmemo which existed in versions  2.1.2/2.0.10 and later create invoice, shipment, creditmemo documents but do not process correctly order statuses, online payments etc

In version 2.1.3/2.0.11 will be presented new services to manage properly(in the same way as  Magento admin user) invoices, shipments and creditmemos.
So in 2.1.3 you can create invoice using POST request /V1/order/:orderId/invoice with very minimum set of parameters like orderId(int) and capture(false/true)
After for that invoice you can create refund online  using POST /V1/invoice/:invoiceId/refund
with minimal set of parameters like invoiceId(int) and isOnline(false/true). 
Please wait approximately two weeks and check these new services. If it works for you close the issue

**Comment by olysenko** [comment]
New services are now available in 2.0.11 and  2.1.3. Closed as fixed
