### ISSUE TITLE
Reports for sales orders gives wrong results.

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#7649]
Sales orders reports under reports tab gives wrong results when compared with the actual orders created.

### Preconditions
Magento 2.1.1
php 7.0.12
mysql 5.7
Did around 32test orders for the month of November.
when checked for exporting the sales orders under reports tab, it only shows 9 orders.
I refreshed life time statistics and flushed cache.
no use. same result again n again.
![32 orders](https://cloud.githubusercontent.com/assets/19605497/20794650/28f8ea2a-b7c5-11e6-8714-42ae392e7101.PNG)
![9 orders](https://cloud.githubusercontent.com/assets/19605497/20794653/2d134268-b7c5-11e6-834a-47e3481cab36.PNG)

**Comment by yaroslavGoncharuk** [comment]
@nmallepally, thanks for reporting this issue.

Please note that unprocessed orders are not treated as sales, so orders in 'Pending' status are not shown in the Orders Report, and there is also no option 'Pending' in 'Order Status' filter.

Could you please re-check your case considering this information?

Thank You.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by nmallepally** [comment]
@yaroslavGoncharuk Thank you. yes it does not count pending orders.
Problem solved. thank you.
