### ISSUE TITLE
Error mergeMetadataElement() in backend product edit or add

### ISSUE THREAD

**Issue by primisuimotori** [magento/magento2#7652]
After updating Magento 2.0.7 to 2.1.0 (2.11 and 2.1.2) when I try to edit a product in backend I got this error:

Recoverable Error: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /var/www/html/[magento_dir]/vendor/magento/framework/View/Element/UiComponentFactory.php on line 337 and defined in /var/www/html/[magento_dir]/vendor/magento/framework/View/Element/UiComponentFactory.php on line 287

**Comment by mrkhoa99** [comment]
@primisuimotori Tried to remove `var/generation` folder?

**Comment by primisuimotori** [comment]
Yes, done. Var and Static (backend) was removed and regenerated, but the errror remains.

**Comment by veloraven** [comment]
@primisuimotori thank you for feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by primisuimotori** [comment]
Solve, delete all database table for catalog (product & category) and eav attribute. After that I Imported the empty tables from a clean Magento 2.1.2 installation.

**Comment by Ctucker9233** [comment]
@primisuimotori That's just not an option if your environment is in production mode with a live site.

**Comment by veloraven** [comment]
I'm closing this issue as it was resolved.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by malachy-mcconnell** [comment]
This issue seems to be the same as issue #5350

**Comment by keevitaja** [comment]
In case anyone comes across with this issue again, then please check if your product does have a valid attribute set. I had the same error when creating products programmatically without attribute set.

**Comment by Usman1493** [comment]
I migrated the data from magento 1.9.3.7 to magento 2.2.5 using the data migration tool. When I click the add product button through admin panle, it showed me the same error. The way I resolved it was to go to `Admin->Store->Attribute Set`. And edited the` Default` and `Migration_Default` Attributes Set. Initially the Migration_Default Attribute had the attribute sets but the Default was empty. I added the attributes to the Default Attribute Set and executed the reindex command

`sudo php bin/magento indexer:reindex`

Also make sure that the Schedule Design Update Group Contains the following attributes:

- custom_design_from
- custom_design_to
- custom_design
- custom_layout

And it worked for me...

**Comment by ghost** [comment]
Encountered in 2.2.5 using the data migration tool.
In my case, the attribute set was missing.

If you get this error, check your attribute set as @Usman1493 and @keevitaja explained

**Comment by omarmohssen** [comment]
products without sku in our case caused the problem

**Comment by Eddcapone** [comment]
Adding

custom_design_from
custom_design_to
custom_design
custom_layout

to the Default Attribute set, was solving it for me :)

**Comment by Jeeva-Rathinam** [comment]
@Eddcapone @Usman1493 I just followed what you said still getting the issue, any help thanks, https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Magento-2-3-After-migrated-from-1-9-2-3-Product-Edit-Page-from/m-p/454147/highlight/false#M5936

**Comment by Jeeva-Rathinam** [comment]
> After updating Magento 2.0.7 to 2.1.0 (2.11 and 2.1.2) when I try to edit a product in backend I got this error:
> 
> Recoverable Error: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /var/www/html/[magento_dir]/vendor/magento/framework/View/Element/UiComponentFactory.php on line 337 and defined in /var/www/html/[magento_dir]/vendor/magento/framework/View/Element/UiComponentFactory.php on line 287

I am getting the same issue, could you pls help me how you solved this issue?
