### ISSUE TITLE
Country Collection error with French language

### ISSUE THREAD

**Issue by quienti** [magento/magento2#7653]
### Preconditions
1. Magento 2.1.2
2. PHP 5.6
### Steps to reproduce
1. Admin in French language
2. Use <source_model>Magento\Directory\Model\Config\Source\Country</source_model> in system.xml
### Expected result
1. No error in JS
### Actual result
1. SyntaxError: missing ) after argument list
### What is the problem
1. In option, there are `Territoire britannique de l'océan Indien`, and this option have an `'`, so, JS are breaken

Old issues: https://github.com/magento/magento2/issues/5862

**Comment by VasylShvorak** [comment]
@quienti  , thank you for your report.
Unfortunately I was not able to reproduce this issue.
Please describe all steps you have done in more detailed way.
And if you can attach screenshot or some logs it may help as well.

**Comment by quienti** [comment]
Unfortunately , I stopped work with Magento 2 since I have changed job
So, I can not test
I am sorry
