### ISSUE TITLE
magento2/admin/reports/report_product/exportLowstockCsv/key/05077e30bdb625d1bbba1b257711106bc2db0e924bc07a6181cefe3d5be40e4c/

### ISSUE THREAD

**Issue by duanyasong** [magento/magento2#7655]
Fatal error: Uncaught Error: Call to a member function getCsvFile() on boolean in /var/www/hollywoodsuits/dev2/magento2/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php:36 Stack trace: #0 /var/www/hollywoodsuits/dev2/magento2/var/generation/Magento/Reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv/Interceptor.php(24): Magento\Reports\Controller\Adminhtml\Report\Product\ExportLowstockCsv->execute() #1 /var/www/hollywoodsuits/dev2/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Reports\Controller\Adminhtml\Report\Product\ExportLowstockCsv\Interceptor->execute() #2 /var/www/hollywoodsuits/dev2/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #3 /var/www/hollywoodsuits/dev2/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /var/www/hollywo in /var/www/hollywoodsuits/dev2/magento2/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php on line 36

**Comment by veloraven** [comment]
@duanyasong thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ChandraRitu** [comment]
I am getting the exact issue and i am using Magento ver. 2.1.0

From  Report > Low Stock Report and then click on export

![lowstockreport](https://cloud.githubusercontent.com/assets/437500/25368161/26d1b1c4-2998-11e7-8a1d-7bcd88e0d8dd.png)

And getting below error

Fatal error: Uncaught Error: Call to a member function getCsvFile() on boolean in /var/www/html/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php:36 Stack trace: #0 /var/www/html/var/generation/Magento/Reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv/Interceptor.php(24): Magento\Reports\Controller\Adminhtml\Report\Product\ExportLowstockCsv->execute() #1 /var/www/html/vendor/magento/framework/App/Action/Action.php(102): Magento\Reports\Controller\Adminhtml\Report\Product\ExportLowstockCsv\Interceptor->execute() #2 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Reports\Controller\Adminhtml\Report\Product\ExportLowst in /var/www/html/vendor/magento/module-reports/Controller/Adminhtml/Report/Product/ExportLowstockCsv.php on line 36

**Comment by saiyadsalma** [comment]
I am getting same error.
