### ISSUE TITLE
"CData section too big" error while accessing configurable product in backend

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7658]
### Preconditions

1. Magento 2.4-develop
2. PHP 7.2

### Steps to reproduce

1. Create a configurable product with ~5000 sub-products
2. Try to access product edit page in the backend

### Expected result

1. Loaded page with success

### Actual result

1. Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : CData section too big found in /vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60

**Comment by ghost** [comment]
I also got same problem.

**Comment by joshspivey** [comment]
@rbostan @prasiddha Do you have any updates on this? I seem to have this error after I ran the migration script from magento 1 to magento 2 and open the product grid. I am guessing the product data for the content needs work.

**Comment by joshspivey** [comment]
I also found this. https://github.com/magento/magento2/issues/4695

**Comment by joshspivey** [comment]
Ok so I narrowed the issue down to having over a certain QTY of orders and extra attributes in the order grid. Its a lib limitation with libxml2 which you should be able to get past with the constant  "LIBXML_PARSEHUGE" by default it has a 10mb limit but parse huge is supposed to allow it to go to 128. I printed the xml to a txt file and it was 25mb.

So line 37 on Template.php doesnt seem to affect it.
$document->loadXML($content, LIBXML_PARSEHUGE);

That error is coming from appendXML not loadXML so sure I can use that constant.

In the actual extension on the server it's coming from parse cdata method.

I am not sure why its not getting the constant from the loader. Any other ideas of where or how to pass that in to make it compatible with appendXML?

```C
xmlParseCDSect(xmlParserCtxtPtr ctxt) {
    xmlChar *buf = NULL;
    int len = 0;
    int size = XML_PARSER_BUFFER_SIZE;
    int r, rl;
    int	s, sl;
    int cur, l;
    int count = 0;

    /* Check 2.6.0 was NXT(0) not RAW */
    if (CMP9(CUR_PTR, '<', '!', '[', 'C', 'D', 'A', 'T', 'A', '[')) {
	SKIP(9);
    } else
        return;

    ctxt->instate = XML_PARSER_CDATA_SECTION;
    r = CUR_CHAR(rl);
    if (!IS_CHAR(r)) {
	xmlFatalErr(ctxt, XML_ERR_CDATA_NOT_FINISHED, NULL);
	ctxt->instate = XML_PARSER_CONTENT;
        return;
    }
    NEXTL(rl);
    s = CUR_CHAR(sl);
    if (!IS_CHAR(s)) {
	xmlFatalErr(ctxt, XML_ERR_CDATA_NOT_FINISHED, NULL);
	ctxt->instate = XML_PARSER_CONTENT;
        return;
    }
    NEXTL(sl);
    cur = CUR_CHAR(l);
    buf = (xmlChar *) xmlMallocAtomic(size * sizeof(xmlChar));
    if (buf == NULL) {
	xmlErrMemory(ctxt, NULL);
	return;
    }
    while (IS_CHAR(cur) &&
           ((r != ']') || (s != ']') || (cur != '>'))) {
	if (len + 5 >= size) {
	    xmlChar *tmp;

            if ((size > XML_MAX_TEXT_LENGTH) &&
                ((ctxt->options & XML_PARSE_HUGE) == 0)) {
                xmlFatalErrMsgStr(ctxt, XML_ERR_CDATA_NOT_FINISHED,
                             "CData section too big found", NULL);
                xmlFree (buf);
                return;
            }
	    tmp = (xmlChar *) xmlRealloc(buf, size * 2 * sizeof(xmlChar));
	    if (tmp == NULL) {
	        xmlFree(buf);
		xmlErrMemory(ctxt, NULL);
		return;
	    }
	    buf = tmp;
	    size *= 2;
	}
	COPY_BUF(rl,buf,len,r);
	r = s;
	rl = sl;
	s = cur;
	sl = l;
	count++;
	if (count > 50) {
	    GROW;
            if (ctxt->instate == XML_PARSER_EOF) {
		xmlFree(buf);
		return;
            }
	    count = 0;
	}
	NEXTL(l);
	cur = CUR_CHAR(l);
    }
    buf[len] = 0;
    ctxt->instate = XML_PARSER_CONTENT;
    if (cur != '>') {
	xmlFatalErrMsgStr(ctxt, XML_ERR_CDATA_NOT_FINISHED,
	                     "CData section not finished\n%.50s\n", buf);
	xmlFree(buf);
        return;
    }
    NEXTL(l);

    /*
     * OK the buffer is to be consumed as cdata.
     */
    if ((ctxt->sax != NULL) && (!ctxt->disableSAX)) {
	if (ctxt->sax->cdataBlock != NULL)
	    ctxt->sax->cdataBlock(ctxt->userData, buf, len);
	else if (ctxt->sax->characters != NULL)
	    ctxt->sax->characters(ctxt->userData, buf, len);
    }
    xmlFree(buf);
}
```

**Comment by joshspivey** [comment]
Found this also https://community.magento.com/t5/Hosting-Performance/Import-of-many-Configurations/m-p/57091

**Comment by ghost** [comment]
I created this ticket.
#8084

**Comment by joshspivey** [comment]
I have a temp fix for this.
Install this plugin https://github.com/mattador/tde-sales-grid
on Collection.php line 87 add in.
$this->getSelect()->limit(1000);

**Comment by ghost** [comment]
@rbostan @prasiddha check out my link I made a grid that works! on ticket 8084

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-80577 to track progress on the issue.

**Comment by ghost** [comment]
@magento-engcom-team thanks for creating internal tickets on this.

**Comment by peterjaap** [comment]
Issue is still relevant in 2.2.2.

**Comment by peterjaap** [comment]
I tried changing append() to;

```
    /**
     * Append
     *
     * @param string $content
     * @return void
     */
    public function append($content)
    {
        $document = new \DOMDocument(static::XML_VERSION, static::XML_ENCODING);
        $document->loadXML($content, LIBXML_PARSEHUGE);
        $this->document->importNode($document->documentElement, true);

        $this->templateNode = $this->document->documentElement;
    }
```

And making document a protected field and adding the document in`__construct` to it. But to no avail. But I think a solution might be somewhere in this direction, where we don't use `append()` to append stuff but combine the XML in a different way.

**Comment by peterjaap** [comment]
The content it tries to append looks like this;

`<script type="text/x-magento-init"><![CDATA[{"*": {"Magento_Ui/js/core/app":  .... etc etc ....}]]></script>`

Maybe we can use an AJAX request to pull in that data from a controller, so it doesn't have to be included in the XML payload.

**Comment by peterjaap** [comment]
Did some further digging.

This UI component is the part that gets added to the main content XML, causing it to break; `vendor/magento/module-configurable-product/view/adminhtml/ui_component/product_form.xml`

This UI component exists of the block `Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix` with the template `vendor/magento/module-configurable-product/view/adminhtml/templates/catalog/product/edit/super/wizard.phtml`.

`wizard.phtml` contains these two function calls;

```
$productMatrix = $block->getProductMatrix();
$attributes = $block->getProductAttributes();
```

This is where all variations are written down, so this is the bulk of the data that makes the CDATA too big.

I would like a way to offload loading this data by getting it from an AJAX request. This way, the data does not need to be inserted in the DOM through an XML blob. We could create the AJAX call directly in `wizard.phtml` (not very clean) or alternatively, find the JS file where the data is actually used and fetch it there. From what I've found, it is either one (or both) of these two JS files;

`vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/product-grid.js`
`vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js`

I don't have any time now to pursue this further. Might pick this up later.

**Comment by peterjaap** [comment]
Apparently, I completely overlooked this workaround; https://github.com/magento/magento2/issues/8084#issuecomment-335239220

This works, although of course it is still terribly slow.

**Comment by peterjaap** [comment]
We've open sourced our solution for using configurable products with an extremely large amount of associated simple products; https://github.com/elgentos/LargeConfigProducts, which has a workaround for this issue.

**Comment by attiquer** [comment]
@peterjaap installed your module on Magento 2.2.3. Backend works fine now (whoopee) however, froontend gives following JS error in console: 

> SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 5 column 35 of the JSON data

Product image and options don't load (continuous loader gif).
Any thoughts ?

**Comment by peterjaap** [comment]
@attiquer could you open an issue [here](https://github.com/elgentos/LargeConfigProducts/issues) ?

**Comment by simonmaass** [comment]
I am still having the same issue in magento 2.2.5 - will this be fixed in the core soon? any updates?

@peterjaap I will try to install your workaround for the time... thank you!

**Comment by rydemods** [comment]
Still have this issue with Magento 2.3

**Comment by simonmaass** [comment]
same here...

**Comment by peterjaap** [comment]
Unfortunately it seems this is not a priority for Magento

**Comment by peterjaap** [comment]
Another thought is to leave out the Product Configuration matrix altogether so this huge JSON blob isn't needed. We'd probably need to modify the controller that handles the post data and the validator as well to make sure the connection with the simple products isn't removed after saving when we remove the matrix.

**Comment by amitebizon** [comment]
> Still have this issue with Magento 2.3

@rydemods Yes, It is in Magento 2.3 too and exist in Magneto 2.3.2 too. Have you get any solution ?

**Comment by simonmaass** [comment]
can confirm - 2.3.2 still having the problem

**Comment by amitebizon** [comment]
It is having in Magento 2.3.2 on **System -> Data Transfer -> Export** page. Unable to export the product.

**Comment by gaurangpadhiyar007** [comment]
![export-index-2019-08-08_7_10](https://user-images.githubusercontent.com/19263771/62708071-3ac8ec00-ba10-11e9-9271-28c8a3031b4d.png)

Check screen shot..

**Comment by gaurangpadhiyar007** [comment]
@magento-engcom-team Please create an instance for me, I have resolved above issue on local machine.
@magento-engcom-team  @magento give me test instance

**Comment by gaurangpadhiyar007** [comment]
@amitebizon 

It is having in Magento 2.3.2 on System -> Data Transfer -> Export page. Unable to export the product.
New Issue created: https://github.com/magento/magento2/issues/24311

**I have resolved this on my Magento instance.**

This is the pull request #24314

Commit: 94e3994

**Comment by engcom-Alfa** [comment]
Reproduced on the fresh 2.4-develop instance.

**Manual testing scenario:**
1.Create a configurable product with ~5000 sub-products;
2. Try to access product edit page in the backend;

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/71400959-06f20a00-2631-11ea-8232-b1669fc7952b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30050` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rbostan. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [a4182bc75797c052e3ffb17735f381f32fb30e3f](https://github.com/magento/magento2/commit/a4182bc75797c052e3ffb17735f381f32fb30e3f)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @rbostan. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [2324d99cd740fd969413aa50096b24c054ecf653](https://github.com/magento/magento2/commit/2324d99cd740fd969413aa50096b24c054ecf653)

The fix will be available with the upcoming `2.4.0` release.

**Comment by WilsonTeles** [comment]
I'm also having this problem in version 2.2.10 but in the customer grid. I have about 70k customers registers and got the "CData section too big". I have implemented the solution for magento\framework\view\templateengine\xhtml\template class, overriding append method but the page locks on spinning and the browser page stops.

**Comment by rydemods** [comment]
you should upgrade to latest version
