### ISSUE TITLE
Backend CMS Widgets: Umlauts and "Catalog Products List"-Conditions fail to insert

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#7661]
### Steps to reproduce
1. Go to Admin => Content => Page => New Page
2. Click the widget add button
3. Select "Catalog Products List"
5. Configure widget (try some umlauts as äöüß or quotation marks)
6. Set one or more "Conditions"
7. Click "Insert widget"
8. Doubleclick the inserted widget to edit its configuration again

### Expected result
1. Umlauts are encoded correctly
2. Quotation marks are possible
3. The configuration of the "Catalog Products List" widget's conditions is editable
4. The widget is displayed in frontend

### Actual result
1. Umlauts are destroyed (happens for all types of widgets)
2. Everything after a quotation mark in a text field has gone (happens for all types of widgets)
3. The configuration of the "Catalog Products List" widget's conditions has gone
4. The widget is not displayed in frontend

Used Magento version: 2.1.1, but also doesn't work with latest version.

**Comment by yaroslavGoncharuk** [comment]
@sippsolutions, thanks for reporting this issue.
We've created internal ticket MAGETWO-62215 to address this issue.

**Comment by larsroettig** [comment]
@yaroslavGoncharuk is a fix available ? if not please prioritize higher.

**Comment by KrystynaKabannyk** [comment]
hi @sippsolutions, the issue has been fixed under MAGETWO-54243 (you can find the fix here c20c8e906bbb74669d5002c116e6a7af54c300f7), backports are scheduled for 2.1.9 and 2.0.17.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70436

**Comment by magento-engcom-team** [comment]
The issue has been fixed in 2.2.0 and 2.1 releases.
@sippsolutions thank you for report
