### ISSUE TITLE
"This site can’t be reached" Error on Cart and Checkout Page

### ISSUE THREAD

**Issue by himansuahm** [magento/magento2#7669]
Hello,
I try to develop new website in Magento 2.1.2.
It's speed is much slower in local server even if i try all things discuss in this forum. All pages takes more than 30s even in admin panel.

I install new Magento with sample data in that when i add products to cart in header mini cart display "cart is empty" and when i navigate to "SITEURL/checkout/cart". it's display "This site can’t be reached" error.

It's working fine if i refreshed page many times but after done any changes in cart same again and also same problem with checkout process.

**Comment by fmd-sav** [comment]
Same problem here. 
Have you solved it?

**Comment by veloraven** [comment]
@himansuahm thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
if you are rather looking for a discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
