### ISSUE TITLE
Text swatch "zero" not shown

### ISSUE THREAD

**Issue by imgali** [magento/magento2#7673]
### Steps to reproduce
1. Create configurable product which has storefront text attribute with value "0" (zero) - let it be size for dress
2. Navigate to category page

### Expected result
1. See the size "0" with other sizes (0, 2, 4, 6 etc)

### Actual result
1. Size "0" (zero) doesn't render

<img width="1311" alt="admin_product" src="https://cloud.githubusercontent.com/assets/21045213/20870790/f37cf2e4-ba5b-11e6-88ab-fb67a976c057.png">
<img width="867" alt="front" src="https://cloud.githubusercontent.com/assets/21045213/20870791/f3837844-ba5b-11e6-8d31-e9850e8cb571.png">

**Comment by wert2all** [comment]
Created internal issue MAGETWO-61828 to investigate and track this issue.

**Comment by imgali** [comment]
@wert2all, we found a solution to this. 

Originally in /module-swatches/Helper/Data.php on line 412 there is a IF statement thats checking $item['value'] and it checks the value like this:

elseif ($item['store_id'] == $currentStoreId && $item['value'])

I think it should be:

elseif ($item['store_id'] == $currentStoreId && $item['value'] != '')

Cause when our swatch value is "0" (zero) it thinks that the second value ($item['value']) is FALSE (zero)

**Comment by vzabaznov** [comment]
Hi @imgali please fell free to create PR for this

**Comment by mkoperator** [comment]
This appears to still be an issue in 2.1.5

**Comment by orozcodiaz** [comment]
@thecrazyrussian I made a pull request already and it was approved. Just use quick fix from @imgali message for now.

**Comment by mkoperator** [comment]
Thank you @oroskodias

**Comment by magento-engcom-team** [comment]
@imgali Closing this issue for now due to [fix](https://github.com/magento/magento2/pull/7743) is already available in `2.2-develop` and `develop` branches. Thank you @oroskodias for the Pull Request and fix.
