### ISSUE TITLE
Incorrect order failure message in checkout_onepage_failure.xml

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7674]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Simulate an order failure in checkout

### Expected result

1. When the order fails, the user should be notified that it failed.

### Actual result

1. The order failure page simply reads "We received your order!"

To fix this, make the following change in `vendor/magento/module-checkout/view/frontend/layout/checkout_onepage_failure.xml`:

Change:
```
<argument translate="true" name="title" xsi:type="string">We received your order!</argument>
```

To:
```
<argument translate="true" name="title" xsi:type="string">
An error occurred while processing your payment. Please try again later.</argument>
```

**Comment by VasylShvorak** [comment]
@thdoan  , thank you for your report.
Unfortunately I was not able to reproduce this issue.Please describe all steps you have done in more detailed way.And if you can attach screenshot or some logs it may help as well.

**Comment by thdoan** [comment]
Sorry, I'm no longer involved with Magento development so cannot provide further update.
