### ISSUE TITLE
Mgento 2.1.1 production errors 

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#7675]
Command returned non-zero exit code:
`/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/magento 2/httpdocs/bin/magento setup:static-content:deploy en_GB en_US`

### Preconditions
Magento 2.1.1
PHP 7.0.13
Mysql 5.7
Debian 8
Apache

### Steps to reproduce
1. Website in Developer Mode
2. Ran php bin/magento deploy:mode:set production
memory limit set to 2048M
3. finished cde compilation successfully
4.generates static content successfully
5. Retuns - Command returned non-zero exit code and stays in developer mode

### Expected result
1.  Should go into production mode.

 please respond or suggest work away, as we are delayed for going live.

**Comment by orlangur** [comment]
You need to find out what went wrong during static content deploy command. Folder permissions problem?

**Comment by nmallepally** [comment]
@orlangur File permission set to 777 on pub/static.
when i run static content deployment seperately, it generates successfully.

**Comment by wert2all** [comment]
Can you provide an output of this command:

`ls -l var/www/vhosts/`

?
As I understand, you have a 'magento 2' folder with a space character?

**Comment by nmallepally** [comment]
@wert2all sorry that was a typo mistake, in original there is no space, i have domain name, just replaced with magento2 for privacy.

**Comment by nmallepally** [comment]
@wert2all @orlangur Did run it again after giving it 4G , again same error
Enabled maintenance mode
Starting compilation
Compilation was started.
%message% 0/7 [>---------------------------]   0% 1 sec 40.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 40.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 40.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 13 secs 146.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 13 secs 146.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 13 secs 146.0 MiB
Application code generator... 3/7 [============>---------------]  42% 13 secs 146.0 MiB
Application code generator... 4/7 [================>-----------]  57% 33 secs 166.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 33 secs 166.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 55 secs 208.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 55 secs 208.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 2 mins 294.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 2 mins 294.0 MiB
Interception cache generation... 7/7 [============================] 100% 2 mins 294.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content
Something went wrong while deploying static content. See the error log for details.
Command returned non-zero exit code:
`/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/xyz/httpdocs/bin/magento setup:static-content:deploy en_GB en_US`

**Comment by wert2all** [comment]
@nmallepally  Can you try to deploy the first locale and second after that.

**Comment by nmallepally** [comment]
@wert2all  How do i do it? It does it automatically.
when i run the command for production. it takes en_GB first and en_US second, how can i change it.

**Comment by wert2all** [comment]
You need to run

/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/xyz/httpdocs/bin/magento setup:static-content:deploy en_GB 

After that

/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/xyz/httpdocs/bin/magento setup:static-content:deploy en_US

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by nmallepally** [comment]
@wert2all Thanks for it.
but when you run production command which is
php bin/magento deploy:mode:set production.
after compiling,  it gives an error with same
Command returned non-zero exit code:
/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/magento 2/httpdocs/bin/magento setup:static-content:deploy en_GB en_US

once it is in production i cannot control, static content deployment while moving to production.
how do i change it or do it?. we are about to go live in 2days, still stuck with production errors.

**Comment by nmallepally** [comment]
Did try again... when i checked on nohup, this showed up
Enabled maintenance mode
Starting compilation
Compilation was started.
%message% 0/7 [>---------------------------]   0% 1 sec 42.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 42.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 42.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 12 secs 150.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 12 secs 150.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 12 secs 152.0 MiB
Application code generator... 3/7 [============>---------------]  42% 12 secs 152.0 MiB
Application code generator... 4/7 [================>-----------]  57% 32 secs 172.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 32 secs 172.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 54 secs 214.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 54 secs 214.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 2 mins 300.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 2 mins 300.0 MiB
Interception cache generation... 7/7 [============================] 100% 2 mins 300.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content
Something went wrong while deploying static content. See the error log for details.
Command returned non-zero exit code:
`/opt/plesk/php/7.0/bin/php -f /var/www/vhosts/xyz/httpdocs/bin/magento setup:static-content:deploy en_GB en_US`
