### ISSUE TITLE
Breadcrumbs work differently between dev and production mode

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#7677]
### Preconditions

1. M2 2.1.2 (both CE and EE)

### Steps to reproduce

1. Visit category page and then navigate through a product page

### Expected result
1. breadcrumbs should contain "Home > Category > Product Name"

### Actual result
1. in developer mode it works as expected
2. in production mode i have "Home > Product Name"

**Comment by wert2all** [comment]
Please provide more steps for reproducing.

**Comment by slackerzz** [comment]
To switch to/from [developer mode](http://devdocs.magento.com/guides/v2.1/config-guide/bootstrap/magento-modes.html#mode-developer) and [production mode](http://devdocs.magento.com/guides/v2.1/config-guide/bootstrap/magento-modes.html#mode-production) you can follow this [doc](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-mode.html)

When Magento is in [developer mode](http://devdocs.magento.com/guides/v2.1/config-guide/bootstrap/magento-modes.html#mode-developer) breadcrumbs contains:
"Home > Category Name > Product Name"

When Magento is in [production mode](http://devdocs.magento.com/guides/v2.1/config-guide/bootstrap/magento-modes.html#mode-production) bredcrumbs for the same product contains:
"Home > Product Name"

@wert2all ok?

**Comment by yumicom** [comment]
I have same problem in production and developer mode

**Comment by Stas94** [comment]
@slackerzz We've created internal ticket MAGETWO-69937 to address this issue.

**Comment by magento-engcom-team** [comment]
@slackerzz, thank you for your report.
We've created internal ticket(s) MAGETWO-69937 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@slackerzz, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
