### ISSUE TITLE
Missing acl.xml for the Magento_Checkout module

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#768]
In the `system.xml` of the Magento_Checkout module there is a resource referenced:  `<resource>Magento_Checkout::checkout</resource>` but the resource is not defined anywhere.  
It seams that the `acl.xml` file is missing.  

And a question on the topic. Why is the `acl.xml` file located directly inside `etc` folder and not `etc/adminhtml` since it is used on the admin area alone?

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31329

**Comment by vpelipenko** [comment]
@tzyganu, we've created internal ticket for fixing this issue, but your pull request is always welcome :-).

**Comment by pboisvert** [comment]
@asemenenko Andrii--is this one your for checkout or for Piotr (security)?

**Comment by tzyganu** [comment]
Any reason why this is not merged yet? Did I do something wrong?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Missing-acl-xml-for-the-Magento-Checkout-module/idi-p/46997).

**Comment by tzyganu** [comment]
@piotrekkaminski This is not a feature request. It's actually a bug.  
I forgot to mention this, maybe because it seamed obvious to me. Now that I think about it it's not that obvious.  
Because the `acl.xml` file is missing in the checkout module, when creating a user role in the backend, I cannot give access to that role to the system->configuration->checkout section.  
But anyway...I see that my PR for this made it to the [develop branch](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/etc/acl.xml).  
Does this mean it will be available in the next version?  
If so, you can leave this closed.
