### ISSUE TITLE
requirejs-config.js generated in wrong folder

### ISSUE THREAD

**Issue by steros** [magento/magento2#7680]
### Preconditions
1. Magento 2.1.2
2. PHP 7.0

### Steps to reproduce
1. activate all security measures during setup
2. Delete pub/static folder
3. run `bin/magento setup:static-content:deploy`

### Expected result
1. requirejs-config.js is requested for "https://www.testing.com/shop/pub/static/_requirejs/adminhtml/Magento/backend/en_US/secure/requirejs-config.js"

### Actual result

1. it is generated one folder above that secure folder and thus not found and thus the backend is not working as expected
(copying the generated requirejs-config.js to the subfolder /secure/ fixes the backend)

**Comment by steros** [comment]
It seems this is a bit more general error. I also have problems with custom css files in my own theme folder.
Sometimes I get a 404 on the css files even though they are there (in the app folder).
For this and same for the require.js file it helps to just run the compilation several times in a row without clearing caches and so on.
I'd guess that it might be a problem due to missing folders? Although there are no errors like such.

**Comment by hostep** [comment]
This is probably a duplicate of https://github.com/magento/magento2/issues/4961?

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by steros** [comment]
I think we can leave this closed, it is most likely a rights problem due to using Mac OSX with VirtualBox and NFS-Folders.

**Comment by medmek** [comment]
> I think we can leave this closed, it is most likely a rights problem due to using Mac OSX with VirtualBox and NFS-Folders.

rights problem as in shell's rights (used to connect to VM) or linux rights ? now I always run git-bash as admin,
NFS the rights are set 
```
config.bindfs.default_options = {
    force_user:   'www-data',
    force_group:  'www-data',
    perms:        'u=rwX:g=rwX:o=rwX'
  }
...
... linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
```
