### ISSUE TITLE
Broken GroupManagementTest in TEST_SUITE=integration INTEGRATION_INDEX=1

### ISSUE THREAD

**Issue by comdiler** [magento/magento2#7683]
### Preconditions
1. Create a branch from develop branch;
2. Change any comment in code;

### Steps to reproduce
1. Create a pull a request from your custom branch to develop;

### Expected result
1. travis-ci tests will be successfully passed, because only one comment was added;

### Actual result
1. Failed TEST_SUITE=integration INTEGRATION_INDEX=1
See the PR #7682 and connected build https://travis-ci.org/magento/magento2/builds/181349467

**Comment by ishakhsuvarov** [comment]
Hi @comdiler 
We are closing this issue now, as it seems that error in the test is fixed some time ago.
As of now there are no failing tests on the Travis CI builds (for example one of the latest runs for now: https://travis-ci.org/magento/magento2/builds/297078546)

Thank you.
