### ISSUE TITLE
quote_address_id not copied when converting quote address to order address

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#7689]
The quote_address_id field is left blank when converting the quote address to an order address.

### Preconditions
1. PHP7.0
2. MG2 CE 2.1.2

### Steps to reproduce
1. Create an order as a guest

### Expected result
1. The quote_address_id column in table sales_order_address should be populated with the value of the quote address where the data was copied from

### Actual result
1. The quote_address_id column has a NULL value

**Comment by 1408sheva** [comment]
the internal ticket was created MAGETWO-70080

**Comment by magento-engcom-team** [comment]
@koenner01, thank you for your report.
We've created internal ticket(s) MAGETWO-70080 to track progress on the issue.

**Comment by mrodespin** [comment]
Can anyone assing me this issue? I am working on it

**Comment by keyurshah070** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by RomaKis** [comment]
This issue was fixed in https://github.com/magento/magento2/issues/7691.
