### ISSUE TITLE
Image Processing Settings: ImageMagick setting has no effect 

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#7690]
### Preconditions

1. Magento 2.1.2 via download
2. PHP7, Nginx, Maria DB, Varnish, Redis

### Steps to reproduce

1. Go to Admin --> Configuration --> Developer --> and Change Image Processing Settings to --> ImageMagick 
2. Clean all Caches ( we also cleaned everything via command line to make shure the setting gets taken into account)

### Expected result

1. Better Image quality 

### Actual result

1. There is absolutely no change in the image size, quality or whatever - it is the exact same image that is created for example as product main image.

Is there a way to prove that imagemagick is working on magento2? We of course installed it on the server.

Thanks!

**Comment by Jrb1x** [comment]
You may need to run `catalog:images:resize` and then clear your cache.

**Comment by wert2all** [comment]
@andidhouse  did you get the answer to your question?

**Comment by andidhouse** [comment]
hi @wert2all 
we are still trying but no luck so for. 
I think a hint would be helpful how to check if the products are really processes via imagemagick. I think it is confusing to activate it in the backend and for a reason it is not working but you do not have any feedback.

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
