### ISSUE TITLE
Code to create downloadable product with samples, files from frontend in magento2

### ISSUE THREAD

**Issue by kumarancontus** [magento/magento2#7692]
Need code to create downloadable product with samples, files from frontend in magento2

**Comment by vzabaznov** [comment]
Hi @kumarancontus please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by vzabaznov** [comment]
@kumarancontus close as no update more than 2 weeks, please feel free to write here or to open new issue if needed
