### ISSUE TITLE
Admin - Order/Ship/Inovice email use Admin default store emails instead of store emails

### ISSUE THREAD

**Issue by mohsinahmed22** [magento/magento2#7693]
M2.1.2 Community

### Preconditions

1. Fresh Installed Magento 2.1.2 with multiple sites and stores.
2. Each website or store uses its own unique sender email address. **(Ex. Sample@store1.com and sample@store2.com)**

### Steps to reproduce

1.  Processing order of site2 via M2 admin with "Notify Customer by Email" selected.

### Expected result

1. An Email originating from the 2nd site scope sender email address

### Actual result

1. conformation email sends successfully but with default store email and default store logo.

**Comment by olysenko** [comment]
Hi, thank you for your report. This issue duplicates [6954](https://github.com/magento/magento2/issues/6954). Closed as a duplicate
