### ISSUE TITLE
Magento2: success/failure message not auto-hiding

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7694]
1) Installed Magento2.1.1 with PHP7 on my localhost wamp
2) Created a custom theme and set it from backend.
3) Deployed content, cleared cache.
4) Navigate to customer login page and entered wrong credentials.
5) Its showing failure message i.e. Invalid login or password.
6) Again entered wrong credentials and now its showing error message 2 times.
7) So attempted again and its showing failure message 3 times.
Please see this http://prntscr.com/dfz0kk

Can someone tell me how these messages auto hidden from the page? 
I think this has been handled by js but I couldn't find the js file.

Please help me.

Thanks & Regards,

Deepak K.

**Comment by quienti** [comment]
I think it's fixed in develop branch with this commit: https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3

**Comment by deepak-netwin** [comment]
@quienti Thanks for your reply.
But this doesn't fix my issue. It still showing error messages on all pages and not disappearing automatically.
Is there any setting at backend OR any other file I need to check/update.

**Comment by deepak-netwin** [comment]
Hey, anyone from Magento team?

**Comment by deepak-netwin** [comment]
I'm really stuck into this. Any help would be appreciated. Thanks!

**Comment by oleg-onufer** [comment]
Написать ему что-то типа
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).

**Comment by oleg-onufer** [comment]
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).
