### ISSUE TITLE
Admin Global Search was build in a hurry

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#7698]
The admin global search is not entirely translatable, extensible and does not take into account the ACL settings for the current user

### Preconditions
Installed Version: 2.2.0-dev
### Steps to reproduce
1. Install any other language pack
2. Create an admin role that does not have access to orders and an admin user assigned to that role
3. Login as the user created in the step above
4. Search for something in the admin global search.

### Expected result
1. I should see the links to " keywords in Products", " keywords in Customers", " keywords in Pages" only and translated in the selected language.
2. I should see results for products, pages and customers matching my keywords (this actually works).

### Actual result
1. I see the link "keywords in Orders" that I should not see because I don't have access to orders. Clicking it takes me to an "Access denied" page.
2. The texts "in products", "in pages"... are not translated  
![image](https://cloud.githubusercontent.com/assets/2447784/20927096/a32d7872-bbc8-11e6-91dc-ec17d0f9b93b.png)

### Additional information.  
The actual results explained above happen because [the template that displays the global search results](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/view/adminhtml/templates/system/search.phtml) contains the hardcoded values for the links to pages, customers, products and orders. (lines 30 to 41) and the texts "in products", "in pages" don't go through the translation function `__`.  

### Additional issues related to the global search.
The global search is partially extensible (without changing the template that renders the results).  
I can add my own entity that can be searchable in the global search but I cannot add a link.  For example if I have an entity called "Article", I can make the instances searchable but I cannot get a link saying "keywords in Articles" without changing the template.  

### Suggestion to make it extensible and to avoid ACL related issues.
The links "keywords in ..." should come from the `di.xml` file and have the ACL for those links checked before displaying the links. Similar to how the actual entity search works.

**Comment by oleg-onufer** [comment]
Thank you, Internal ticket was created for this issue - MAGETWO-70026

**Comment by magento-engcom-team** [comment]
@tzyganu, thank you for your report.
We've created internal ticket(s) MAGETWO-70026 to track progress on the issue.

**Comment by RomaKis** [comment]
Working on this.

**Comment by okorshenko** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1167 by @RomaKis in 2.2-develop branch
Related commit(s):
 - bc345f858b87238501bceb0aebdabf9e122c6c49
 - 5eba0f3f472c3f8191599e855ee8efa96785af5c
 - c5035d42411621128a3d21c431425dec68e2c045
 - f45a75c0112b390aea5fd100136d8e91c5000337

The fix will be available with the upcoming 2.2.4 release.
