### ISSUE TITLE
Shipping and payment doesn't displaying after adding shipping information in shopping cart

### ISSUE THREAD

**Issue by Remishevskiy** [magento/magento2#7699]
Checkout works incorrectly if user go checkout page through shopping car 

### Preconditions
1. Magento 2.1.x
2. Apache 2.4.18
3. PHP 7.0.13
4. MySQL 5.6

### Steps to reproduce
1) Not logged user add product to shopping cart
2) Go to shopping cart
3) Edit shipping information
4) Go to the checkout page.

### Expected result
1. Shipping and payment information displaying and user can edit this information.

### Actual result
1. Shipping and payments not loaded on page.

https://goo.gl/UBlrJs
http://screencast-o-matic.com/watch/cDl1ItQo8d

**Comment by OZZlE** [comment]
This "funny" little bug happens when you disable FPC (+maybe block cache)... If you enable FPC it will work again ^^

**Comment by veloraven** [comment]
@Remishevskiy thank you for your report.
Is this issue still actual?
We were not able to reproduce it on the ver. 2.1.7

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
