### ISSUE TITLE
Magento2: Category Id not showing at backend if selected any category.

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7700]
1) Intsalled Magento2.1.1 on localhost wamp with php7.0
2) Login to backend. Created some categories.
3) When selected any category at backend, it doesn't show id of that category at the top as it was showing in Magento1.x.

**Comment by wert2all** [comment]
Thank you for your submission. The Magento 2 GitHub repository is used to capture code and documentation issues. You can ask your question at Stack Exchange or the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Comment by deepak-netwin** [comment]
@wert2all Thanks for your reply. But this seems to be an issue in core Magento2. Do you have any fix for this?
