### ISSUE TITLE
Unable to load theme by specified key error while creating new store view

### ISSUE THREAD

**Issue by RoAndrei** [magento/magento2#7702]
### Preconditions

1.  Created new store view in Magento 2.0.1, to be used for a different language

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
Got this error on frontend:
![image](https://cloud.githubusercontent.com/assets/11091604/20928865/58389088-bbd0-11e6-813d-b2efeccefb42.png)

And this error on backend, while trying to set the Flexshop Theme, back to the original Default Store view (don't know why the theme was moved from the default store view to the newly created store view, leaving the first one empty  )
![image](https://cloud.githubusercontent.com/assets/11091604/20928917/99f4e6b6-bbd0-11e6-820b-4305d0e4edde.png)

Theme has an id of 4 in the db, not 7

Flushed the cache, redeployed the static files, reindexd the data, ran setup:upgrade, but nothing seems to work.

Thank you

**Comment by Ctucker9233** [comment]
@RoAndrei If you manually change the ID of the theme from 4 to 7 it should work. I had this happen to me once.

**Comment by RoAndrei** [comment]
Hi. Thanks.
 Changed the id, but then was not able to change the other store view's theme.. ended up adding the same theme with two different id's in the theme table and this fixed it.
