### ISSUE TITLE
After Save & Duplicate {{description}}, {{name}} does not change

### ISSUE THREAD

**Issue by tgsergiu** [magento/magento2#7703]
### Preconditions

1. Create a product and click Save&Duplicate the product. The product must have {{description}} {{name}} set 

### Steps to reproduce

1. 

### Expected result

1. It will not auto complete as you type, only for new products the autocomplete works, if is Save & Duplicate does  not work

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@tgsergiu thank you for your feedback
Please update description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result - without messing between different sections.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
