### ISSUE TITLE
Unresponsive Script Dialog Warning in Admin (Firefox)

### ISSUE THREAD

**Issue by mtb2112** [magento/magento2#7704]
### Preconditions

1. Magento 2.1.2
2. A little over 61K items
3. 142 Product Attributes
4. Firefox Version 50.0.2
5. Custom theme inheriting from Blank

### Steps to reproduce

1. Log into admin
2. Go to products->catalog
3. Click Add Product button

### Expected result

1. Page with configs loads properly.

### Actual result

1. An Unresponsive Script Dialog prevents the page from loading.
2. A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

![screen shot 2016-12-06 at 11 28 20 am](https://cloud.githubusercontent.com/assets/7471997/20934177/39ecf51a-bba8-11e6-8721-ec6be5a85da2.png)

**Comment by OlgaBurtyka** [comment]
Same problem

**Comment by OlgaBurtyka** [comment]
@mtb2112 , we got same error, because also have many products - over 71000 and over 4500 categories. It categories tree on product page throw stop script error.

**Comment by magento-engcom-team** [comment]
@mtb2112, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
