### ISSUE TITLE
Wrong download link url in invoice email for purchases

### ISSUE THREAD

**Issue by avra911** [magento/magento2#7707]
`$this->getItem()->getId` returns the id of the invoice, we want the id of download item in `app/code/Magento/Downloadable/Block/Sales/Order/Email/Items/Downloadable.php`.

However my PR did not passed travis, some fails are not even related to my changes: https://github.com/magento/magento2/pull/7705.

Did anyone had same problem here?

Razvan

**Comment by veloraven** [comment]
@avra911 thank you for your feedback.
If you think it to be a Magento issue please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
If you are looking for discussion please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
