### ISSUE TITLE
Import customizable options Js Error

### ISSUE THREAD

**Issue by WinnerStore** [magento/magento2#7713]
Magento CE 2.1.1 without sample data is installed.

Versione Apache	2.4.23
Versione PHP	5.6.28
Versione MySQL	10.0.27-MariaDB-cll-lve
Architettura	x86_64
Sistema operativo	linux

**When I try import customizable options , I get the following error!**

if (this.elems().filter(function (el) {
                    return el.position;//this error
                }).length !== this.getChildItems().length) {

Error
dynamic-rows.js:231 Uncaught RangeError: Maximum call stack size exceeded(…)(anonymous function) @ dynamic-rows.js:231sort @ dynamic-rows.js:230(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380get @ registry.js:224sort @ dynamic-rows.js:238(anonymous function) @ dynamic-rows.js:239_resolveRequest @ registry.js:413_addRequest @ registry.js:380

**Comment by veloraven** [comment]
@WinnerStore thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
