### ISSUE TITLE
when I save the price of customizable options is rounded integer

### ISSUE THREAD

**Issue by WinnerStore** [magento/magento2#7717]
Magento CE 2.1.1 without sample data is installed.

Versione Apache	2.4.23
Versione PHP	5.6.28
Versione MySQL	10.0.27-MariaDB-cll-lve
Architettura	x86_64
Sistema operativo	linux

When I insert several customizable options and put on a fixed price for each one it is rounded down! example if I put the price 0.60(with dot) and upgrade it is ok, when reloading the page the price displayed is 0,60(with comma) at this point if I upgrade again the price is saved at 0! Can someone help me?

Localizzation Italian

Thanks

**Comment by veloraven** [comment]
@WinnerStore thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
