### ISSUE TITLE
Can't load custom extension class

### ISSUE THREAD

**Issue by ghost** [magento/magento2#772]
It appears that you can no longer load customer extension classes from XML files, like this:

```
    <source_model>Inchoo\Stripe\Model\Source\Cctype</source_model>
```

Error is:
Class Inchoo\Stripe\Model\Source\Cctype does not exist

For example, In a custom extension, etc/adminhtml/system.xml there are a few lines like this:

```
            <field id="cctypes" translate="label" type="multiselect" sortOrder="5" showInDefault="1" showInWebsite="1" showInStore="0">
                <label>Credit Card Types</label>
                <source_model>Inchoo\Stripe\Model\Source\Cctype</source_model>
            </field>
```

(File exists, in /app/code/Inchoo/Stripe/Model/Source/Cctype.php, namespace and class name are OK)

See
https://github.com/ivanweiler/Inchoo_Stripe

It used to work in an earlier Magento2 build... what changed?

**Comment by keyurshah070** [comment]
Is there any updates on this issue ?

**Comment by mazhalai** [comment]
@keyurshah070 please avoid posting on closed issues. Start a new one.
