### ISSUE TITLE
Catalog rule contains-condition not saving multiple selection in 2.1.2

### ISSUE THREAD

**Issue by mveldhuizen** [magento/magento2#7723]
### Preconditions
1. Magento version 2.1.2 
2. Installed default sample data

### Steps to reproduce
1. Add new catalog price rule
2. General information doesn't seem to matter
3. Add contains-condition with multiple options
4. Example: Climate contains Spring, Warm
5. Save the rule

### Expected result
1. POST should contain both values for example:
`rule[conditions][1--1][type]:Magento\CatalogRule\Model\Rule\Condition\Product
rule[conditions][1--1][attribute]:climate
rule[conditions][1--1][operator]:{}
rule[conditions][1--1][value][]:208
rule[conditions][1--1][value][]:209`
2. Rule should be saved and condition should state: Climate contains Spring, Warm
![schermafbeelding 2016-12-08 om 11 26 27](https://cloud.githubusercontent.com/assets/971367/21006476/5f2657bc-bd39-11e6-9f3a-fe60fd0683db.png)

### Actual result
1. POST contains only first selected value
`rule[conditions][1--1][type]:Magento\CatalogRule\Model\Rule\Condition\Product
rule[conditions][1--1][attribute]:climate
rule[conditions][1--1][operator]:{}
rule[conditions][1--1][value][]:208`
2. Rule is saved and condition is: Climate contains Spring
![schermafbeelding 2016-12-08 om 11 27 09](https://cloud.githubusercontent.com/assets/971367/21006484/678c0154-bd39-11e6-81c3-b68fe63e7908.png)

**Comment by hatimeria-artur-jewula** [comment]
I can confirm this is happening in 2.1.3 as well. I tested on 2 different installations.

**Comment by Zefiryn** [comment]
I've managed to find and create a fix for the issue. It is now waiting for magento team approval in pull request. If you need quicker solution you can use a module with the fix I prepared at my company:

https://bitbucket.org/hatimeria/m2-fixes

**Comment by jmtakahashi** [comment]
@Zefiryn will this also fix the issue of using multiple sku's?  I.e. SKU "is one of" [sku], [sku].  #8215 That issue seems related.  If this fixes it, it would be awesome.

**Comment by jmtakahashi** [comment]
@antboiko will this also fix the issue of using multiple sku's? I.e. SKU "is one of" [sku], [sku]. #8215 That issue seems related. If this fixes it, it would be awesome.
