### ISSUE TITLE
Error after save product with custom attribute

### ISSUE THREAD

**Issue by sichensol** [magento/magento2#7726]
### Preconditions
1. Magento 2.1.2 EE and CE
2. PHP 7.0.13
3. MySQL 5.7
4. nginx 1.10
5. ubuntu 16.04

### Steps to reproduce
1. Log in to the Magento backend.
2. Select Stores > Attributes > Product in the main navigation.
3. Click the Add New Attribute button.
4. Enter an attribute label, for example: Flavor.
5. Select the tab Frontend Properties.
6. Set Visible on Catalog Pages on Frontend to Yes.
7. Click Save Attribute.
8. Select Stores > Attributes > Attribute Set  in the main navigation.
9. In the list, select an Attribute Set, for example the Bag attribute set.
10. Drag & drop the Flavor attribute icon from the right Unassigned Attributes column onto the Product Details attribute group folder icon.
11. Click Save Attribute Set.
12. Select Products > Inventory > Catalog in the main navigation.
13. In the Attribute Set column filter dropdown, select 'Bag' and click the Search button.
14. Select a product from the list where the Visibility is set to Catalog, Search
15. Enter a value for the Flavor attribute, for example Strawberry.
16. Click the Save button.

### Expected result
1. Get message that 'You saved the product'

### Actual result
1. Get error message 'Required parameter 'theme_dir' was not passed'

**Comment by bartoszkubicki** [comment]
Check if you or someone working with you haven't created custom theme and it should be case with this theme - try to delete it - if you are now on Luma and check if problem persits.

**Comment by sichensol** [comment]
It is very interesting behavior. When I removed all custom themes, I could not get this issue anymore, but when I did, I had enabled the luma theme, and another themes were disabled.  Why it does not work properly with custom themes?

**Comment by 1408sheva** [comment]
@molneek Is this issue still actual? We were not able to reproduce it on ver. 2.1.7.

**Comment by sichensol** [comment]
@1408sheva I've never tried to reproduce it on ver. 2.1.7. So, I think this issue isn't actual at the moment.
