### ISSUE TITLE
swatch color not selected when editing product from cart

### ISSUE THREAD

**Issue by karmickdev** [magento/magento2#7727]
Hi I am using Magento 2. I have added color swatch for a configurable product. After adding that product into cart, when I clicked on "Edit Product", I am redirecting to product details page with selected attributes but color is not selected there.

**Comment by veloraven** [comment]
@karmickdev thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for help and discussion please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
