### ISSUE TITLE
Banner Rotation not getting applied

### ISSUE THREAD

**Issue by alessandrozucca** [magento/magento2#7728]
Version Used: Magento EE 2.1.2

I have migrated (using the data-migration-tool) several Banner Rotation Widgets from M1 EE to M2 EE for a client.

We are facing an issue with the `rotation mode` not being taken into account. So if a Banner has 4 images and we have selected `rotation` `random` we would expect only 1 banner to appear for that widget. Instead, all are getting displayed.

I've looked at the code and looks to me that `\Magento\Banner\Block\Widget\Banner::_getBannersContent` is not getting called and that's the only function that deals with the rotation!

```
    /**
     * Get banners content by specified banners IDs depend on Rotation mode
     * // TODO: Banner functionality must be refactored with moving sorting/display logic to frontend
     * @param array $bannerIds
     * @return array
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _getBannersContent(array $bannerIds)
    {
        ...
            // Choose banner depending on rotation mode
            switch ($this->getRotate()) {
```

What does that `TODO:` means? Does it mean that this functionality getting moved to the front end as we speak, and you are aware that is currently broken?

Looking at he markup I can see that all IDs are showing up on the `data-ids`: `123,128,129,125` which are taken from `\Magento\Banner\Block\Widget\Banner::getWidgetAttributes`

```
<div class="widget block block-banners" data-bind="scope: 'banner'" data-banner-id="9b6e9b6c39d006408bb81ca99dbbd5b4" data-types="" data-display-mode="fixed" data-ids="123,128,129,125,">
</div>
```

Then the Ajax Controller is called `vendor/magento/module-banner/Controller/Ajax/Load.php` which delegates to `\Magento\Banner\Model\Banner\Data::getBannersData` and this only filters the inactive banners, it doesn't apply the rotation at all.

**Comment by veloraven** [comment]
@alessandrozucca thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
Banners functionality is present in Enterprise Edition only.
