### ISSUE TITLE
No Store View Switcher on Backend Product Grid

### ISSUE THREAD

**Issue by hewgim** [magento/magento2#7731]
Magento 2.1.2

There is no store switcher on the Magento 2 product grid, which means that you can't easily see your product data for each store.

Goto to Products -> Catalog. There is no store switcher in the top left corner of the screen.

I manually added a store switcher by adjusting the layout files. This adds ..../store/3 for example to the end of the product grid urls, but the product grid still only displays the information for the default store.

Expected result

The expected behaviour would be that in Magento 1. There would be a store switcher displayed on the backend product grid page. When selecting a store view on the store switcher, the correct product information for that store view would be displayed

**Comment by veloraven** [comment]
@hewgim thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
