### ISSUE TITLE
import not working on magento 2.1.2

### ISSUE THREAD

**Issue by ooples** [magento/magento2#7732]
### Preconditions

1. magento 2.1.2
2. 

### Steps to reproduce

1. I have a csv file that I upload like normal
2. I check the data and I import the file

### Expected result

1. To see the products imported into the inventory

### Actual result

1. No error messages in the log and the import report shows 0 products added
![import_nothing](https://cloud.githubusercontent.com/assets/3075685/21037195/74e17c78-bd91-11e6-98a5-bebfdde47a8e.png)

**Comment by veloraven** [comment]
@ooples thank you for your feedback.
Could you please provide more details? Including more detailed steps and information about your environment: OS, versions of web-server, PHP, MySQL.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ooples** [comment]
Sorry I didn't see that this had a response on it. I discovered that the issue is with using cloudflare and magento 2.1.3 and cloudflare doesn't work when you have certain settings enabled like the rocket loader. Do we fix this issue here or does cloudflare have to fix the issue?
