### ISSUE TITLE
Cannot save product because of required attribute within Advanced pricing but no validation errors shows

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#7735]
### Preconditions
1.  Magento 2.1.2
2. PHP 7.0.12
3. MySQL 5.7.16

### Steps to reproduce
1. Create an attribute that is required (For me this is attribute 'inkoopprijs'):
![bug_product_save_attribute](https://cloud.githubusercontent.com/assets/17834386/21044085/79873268-bdfa-11e6-8028-031cef7894b6.png)

2. Add the attribute to the Pricing group in an attribute set. (For me this is attribute set 'Migration Voetbalsokken':
![bug_product_save_attribute_set](https://cloud.githubusercontent.com/assets/17834386/21044106/8a806742-bdfa-11e6-984f-54e9c27f8ec2.png)

3. Try to add a new product with this attribute set and save it:
![bug_product_save_product](https://cloud.githubusercontent.com/assets/17834386/21044147/b1edd86e-bdfa-11e6-9d31-92a177652ab3.png)

### Expected result
1. A validation error should show that a required field is not filled in under Advanced Pricing so it is clear why a product cannot be saved.

### Actual result
1. No validation error shows so it is not clear why a product cannot be saved. See a video of it here:
http://cloud.h-o.nl/iPK2

This problem is even more problematic if you created a configurable product before you added the attribute to the attribute set. Afterwards the configurable cannot be saved/edited anymore because of the required field that is no longer accessible:
![bug_product_save_configurable_product](https://cloud.githubusercontent.com/assets/17834386/21044287/8110efbe-bdfb-11e6-945b-0b27368b1eb0.png)

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issues MAGETWO-62411 was created

**Comment by PascalBrouwers** [comment]
Thank you @olysenko

**Comment by magento-engcom-team** [comment]
@PascalBrouwers, thank you for your report.
We've created internal ticket(s) MAGETWO-62411 to track progress on the issue.

**Comment by developerzblock** [comment]
I believe I've had a similar issue: https://community.magento.com/t5/Technical-Issues/So-I-moved-the-Price-attribute-to-the-Advanced-Pricing-Group/m-p/89309/thread-id/4363
Something is up with moving things in or around the Advanced Pricing group.

**Comment by magento-engcom-team** [comment]
@PascalBrouwers, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
