### ISSUE TITLE
Event catalog_product_collection_load_before no longet exist 

### ISSUE THREAD

**Issue by KishorkumarKar** [magento/magento2#7737]
Hi 
I need to use **catalog_product_collection_load_before** to filter my product in front end by this event doesn't exist but it was in **1.X** how overcome this.
Thanks
Kishor

**Comment by veloraven** [comment]
@KishorkumarKar thank you for your feedback.
Please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue, please describe it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
