### ISSUE TITLE
Add 'article' to container element 'HtmlTag' attribute

### ISSUE THREAD

**Issue by sidealice** [magento/magento2#7738]
Magento2.1 version:732d445   
I think 2.1 stable and similar should also affected. 

With following layout : 
`<container name="mainOuter" label="Main Outer Content Container" htmlTag="div" htmlClass="weui-tab__panel" />`

Got exception:

> The value 'article' is not an element of the set {'dd', 'div', 'dl', 'fieldset', 'main', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}

If I change Magento/Framework/View/Layout/etc/elements.xsd
I still got exception:

> Html tag "article" is forbidden for usage in containers. Consider to use one of the allowed: dd, div, dl, fieldset, main, header, footer, ol, p, section, table, tfoot, ul, nav.

How to use article or why we can't ?

**Comment by veloraven** [comment]
@sidealice thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
