### ISSUE TITLE
Unable to pass IPv6 MySQL host

### ISSUE THREAD

**Issue by joelvardy** [magento/magento2#774]
I am unable to specify an IPv6 address as the database hostname with the following command line arguments:

```
--db_host=2a01:7e00::xxxx:xxxx:xxxx:xxxx
--db_host="2a01:7e00::xxxx:xxxx:xxxx:xxxx"
```

Error received is:

```
Zend_Db_Adapter_Exception
 SQLSTATE[HY000] [2005] Unknown MySQL server host '2a01' (2)
```

An IPv4 address works as expected.

This was also an issue in Magento 1.x

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31246

**Comment by ilol** [comment]
Comment from @buskamuza :

Here is the problem - lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:314

} else if (strpos($this->_config['host'], ':') !== false) {
    list($this->_config['host'], $this->_config['port']) = explode(':', $this->_config['host']);
}

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-pass-IPv6-MySQL-host/idi-p/46992).
