### ISSUE TITLE
Change Monolog required version

### ISSUE THREAD

**Issue by AlexanderRakov** [magento/magento2#7744]
Hi.
Now Mangento 2 requires monolug 1.16.0. It is cause of incompatibility with google api and, probably, other some packages.

Please, increase required version at least to 1.17.0 in composer.json.

Thank you.

**Comment by veloraven** [comment]
@AlexanderRakov thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
