### ISSUE TITLE
Fix error thrown by TravisCI for develop branch

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#7746]
Anyone who creates a branch off of develop and runs a TravisCI build will experience this error:
1) Magento\Customer\Model\GroupManagementTest::testGetDefaultGroupWithNonDefaultStoreId
Magento\Framework\Exception\NoSuchEntityException: No such entity with groupId = , storeId = 11

### Preconditions
Magento 2 develop branch

### Steps to reproduce
1. Create a branch of Magento Develop
2. Trigger TravisCI Build with a simple pull request, like adding a comment

### Expected result
TravisCI build passes all checks

### Actual result
TravisCI Build fails 1 check for php5.6 and php7 with error: 1) Magento\Customer\Model\GroupManagementTest::testGetDefaultGroupWithNonDefaultStoreId
Magento\Framework\Exception\NoSuchEntityException: No such entity with groupId = , storeId = 11

Proposed solution: a function that checks if groupID and store ID exists and if not, use the default groupID and storeID. The check for groupID and StoreID seems to be in place because a NoSuchEntityException is thrown. So if possible, just add a "use default groupID and storeID" method.

**Comment by xmav** [comment]
This issue is already addressed in internal ticket MAGETWO-62387. I’ve added your report on this issue to that ticket.

**Comment by xmav** [comment]
@Ctucker9233 Thanks for reporting this issue. It is already fixed in develop branch

**Comment by Ctucker9233** [comment]
@xmav Where can I find the commits that fix this issue?

**Comment by xmav** [comment]
@Ctucker9233 
Here you are https://github.com/magento/magento2/commit/e6f24bc
