### ISSUE TITLE
Magento\Setup\Module\I18n\Dictionary\Writer::Csv: __destructor should be __destruct

### ISSUE THREAD

**Issue by kalessil** [magento/magento2#7747]
A small typo in the magic method name: https://github.com/magento/magento2/blob/1ade3b769a937f19682bbbe4e51b6c956147952f/setup/src/Magento/Setup/Module/I18n/Dictionary/Writer/Csv.php#L58

**Comment by vzabaznov** [comment]
Hi @kalessil thank you for reporting, internal ticket MAGETWO-62234

**Comment by vzabaznov** [comment]
Issue has been fixed in fresh magento version, thanks for reporting.
