### ISSUE TITLE
Unable to save Attribute Set

### ISSUE THREAD

**Issue by DaveDennisME** [magento/magento2#7750]
When trying to create and save a new Attribute set. I am presented with a message saying "ATTENTION Sorry, we're unable to complete this request." when trying to save.

### Preconditions
1. Magento CE 2.1.2 installed without sample data through cli
2. Running Apache 2.2.31 (Unix)
3. PHP 5.6.23 with Zend Engine 2.6.0
4. MySQL 5.6.30

### Steps to reproduce
1. Go to Stores -> Attributes -> Attribute Sets
2. Click "Add Attribute Set"
3. Enter Attribute Set name and select base set ("Default" selected) and click "Save"
4. Assign attributes (NOTE: this error happens even if no new attributes are assigned)
5. Click "Save"

### Expected result
Attribute Set should save and I should be returned to the Attribute Set index page

### Actual result
I am presented with a notice "ATTENTION Sorry, we're unable to complete this request" (No errors are shown). I am then allowed to a) Close the modal using the "X", or b) Click "OK", which closes the modal.

![mag_newattributeset](https://cloud.githubusercontent.com/assets/3355682/21081983/d0dafff8-bf9f-11e6-92a6-59b6f74c10c9.jpg)
![mag_newattributeset2](https://cloud.githubusercontent.com/assets/3355682/21081985/d0ddb6d0-bf9f-11e6-87b0-efc06bde27c0.jpg)
![mag_newattributeset3](https://cloud.githubusercontent.com/assets/3355682/21081984/d0db377a-bf9f-11e6-8740-675b78a7e4bd.jpg)

Error shown on saving...
![mag_newattributeset4](https://cloud.githubusercontent.com/assets/3355682/21083673/a6aa41f2-bfc3-11e6-9fa3-2bcf1df4a0ef.jpg)

**Comment by yaroslavGoncharuk** [comment]
@DaveDennisME, thanks for reporting this issue. 

We cannot reproduce this issue as described.
In addition, identify, please:
- the web browser you are using
- application mode
- if you have any extensions
- special options in Magento Configuration
- are you running clear 2.1.2 installation or upgraded from any previous version?

**Comment by DaveDennisME** [comment]
Hi @yaroslavGoncharuk,

**Browser:** Chrome Version 54.0.2840.98 (64-bit)
**App Mode:** Developer
**Extensions:** None
**Special Options:** Not clear on what you mean by this. But, I started creating attributes after the install of magento. I have no extensions, or special options installed.
**Clear 2.1.2 or Upgrade:** No upgrade. Running clear 2.1.2

Thank you

**Comment by nltheme** [comment]
hey @DaveDennisME you got solution ? i have same issue

**Comment by dman311** [comment]
I'm having the same issue.  I can add a new attribute set but even if I try to update the new set I get the same error. Sorry, we're unable to complete this request

Version: 2.0.13
Browser: Microsoft Edge, Internet Explorer, Chrome (Same result on each)
Extensions: apptrian/subcategories, ipragmatech/module-redirection

**Comment by jarnail104** [comment]
Having same issue : https://github.com/magento/magento2/issues/8841

Did you get any solution for this?

**Comment by nltheme** [comment]
yes that was server modsecurity issue.

**Comment by jarnail104** [comment]
Please post the solution if its sorted out

**Comment by nltheme** [comment]
my hosting disable mod security and seems solved it for me. thanks

**Comment by jarnail104** [comment]
is Security Module of magento? I disable that but it also didnt work. Though its not recommended to disable this module but i tired and it didn't work.

**Comment by jarnail104** [comment]
I am quite sure its bug in magento but there is no response or solution for this yet. Its impossible to to create products without attribute set if someone need additional/different attribute set.  Why they are not addressing such issues which are root of system?

**Comment by jarnail104** [comment]
Yes this issue is because of server configuration and it fixed with the help from server support.
