### ISSUE TITLE
How to use the HTTPS protocol for the frontend account and checkout pages only, and the HTTP protocol for all the rest frontend pages? 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#7752]
Let's example i want to make HTTPS for my account and checkout page.

I did setting in backend and now HTTPS working fine.

Now example: i am at home page with https URL, In magento 2 all URL is showing HTTPS like product page,category page, it should be HTTP URL not https.

**Comment by vzabaznov** [comment]
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
