### ISSUE TITLE
Customer attribute gives error of required value

### ISSUE THREAD

**Issue by Nehace40** [magento/magento2#7753]
I am adding two customer attribute programmatically. One attribute is add in customer create form and another one is not adding in that form.

let's guess one Attribute is ABC and the second attribute is XYZ

i am filling the value of ABC field

Now i am trying to create customer from frontend and it gives an error.

> ABC is required field
> XYZ is required field

### Preconditions
Magento 2.1.2

### Steps to reproduce
```
$customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);
        $customerEntity = $customerSetup->getEavConfig()->getEntityType('customer');
        $attributeSetId = $customerEntity->getDefaultAttributeSetId();

        /** @var $attributeSet AttributeSet */
        $attributeSet = $this->attributeSetFactory->create();
        $attributeGroupId = $attributeSet->getDefaultGroupId($attributeSetId);

        $customerSetup->addAttribute(\Magento\Customer\Model\Customer::ENTITY, 'abc', [
            'type' => 'varchar',
            'label' => 'ABC',
            'input' => 'text',
            'required' => true,
            'visible' => true,
            'user_defined' => true,
            'sort_order' => 90,
            'position' => 90,
            'system' => 0,
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(\Magento\Customer\Model\Customer::ENTITY, 'test')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer','customer_account_create'],
            ]);

        $attribute->save();

        $customerSetup->addAttribute(\Magento\Customer\Model\Customer::ENTITY, 'xyz', [
            'type' => 'varchar',
            'label' => 'XYZ',
            'input' => 'text',
            'required' => true,
            'visible' => true,
            'user_defined' => true,
            'sort_order' => 91,
            'position' => 90,
            'system' => 0,
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(\Magento\Customer\Model\Customer::ENTITY, 'test')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer','customer_account_edit'],
            ]);

        $attribute->save();
```
in register.phtml

```
<div class="field abc">
            <label for="abc" class="label"><span><?php /* @escapeNotVerified */ echo __('ABC') ?></span></label>
            <div class="control">
                <input type="text" name="abc" id="abc" value="<?php echo $block->escapeHtml($block->getFormData()->getAbc()) ?>" title="<?php /* @escapeNotVerified */ echo __('ABC') ?>" class="input-text">
            </div>
        </div>
```

### Expected result
It should be registered customer successfully

### Actual result
It gives error "ABC" is required field. "XYZ" is required field.

**Comment by vkalchenko** [comment]
@Nehace40 I think you need either set default value or add "customer_account_create" to 'used_in_forms'

**Comment by Nehace40** [comment]
@vkalchenko In "ABC" attribute i am adding  "customer_account_create" to 'used_in_forms'

**Comment by vkalchenko** [comment]
@Nehace40 I meant to both 'customer_account_create' and 'customer_account_edit' for both attributes. I had similar issue on one of my projects

**Comment by sp185143** [comment]
This is causing us problems too (we are on EE 2.15). It seems that if you mark and attribute as required, Magento expects it to be on all forms but admin panel is supposed to allow us to specify which forms an attribute is on - i.e. Registration vs. My Account. Even if required field for registration, it shouldn't have to be on my account.

**Comment by magento-engcom-team** [comment]
@Nehace40, thank you for your report.
We've created internal ticket(s) MAGETWO-81809 to track progress on the issue.

**Comment by clemblanco** [comment]
Any update on the above?

**Comment by kerlama** [comment]
Yes, this still exists in 2.2.3

**Comment by neetu-mittal** [comment]
I am also facing same issue in magento2. 
Required field error is shown on even login form.
I am using v2.2
Also set default value for my attribute and update same value in table also with update query, but did not help anything.

**Comment by chernenm-zz** [comment]
Hello everyone,

We have investigated the root cause of the issue and came to conclusion that actual result is a by design behavior. 
If custom attribute is set as a required one than it must be configured to be shown on storefront and to be shown in all the forms.
If merchant wants a custom attribute to be required only on some certain forms, then an extension attribute should be used instead. 
Extension attributes are used to extend functionality of custom attributes. Please find more details here https://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html

**Comment by magento-engcom-team** [comment]
Hi @Nehace40 Thank you for reporting.

We are now closing this ticket, as it looks like this is not a Magento technical issue, as described above.

**Comment by Rayleigh3105** [comment]
Hello @chernenm , 
thank´s for sharing you conclusion that helps alot.
is there an tutorial on the web for extension attributes?
