### ISSUE TITLE
special_price.phtml is not found in whole project.

### ISSUE THREAD

**Issue by praful-rajput** [magento/magento2#7754]
I am trying to override special price section according to my theme. Unfortunately,  I didn't find special_price.phtml anywhere.
 
Preconditions
Magento version CE 2.1.2
1. xml layout file : /vendor/magento/module-catalog/view/base/layout/catalog_product_prices.xml line no# 18
2. there is not any physical file found at given location. 

### Steps to reproduce
This is not generating any error. It is just the issue which is calling unavailable file.

### Expected result

1. If you are calling such file it should be present in given location if it is not created by proxy.

### Actual result

1. If you are calling such file it should be present in given location if it is not created by proxy.

**Comment by vzabaznov** [comment]
@vasuscoin can u please update Actual and Expected result, they are the same now

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
