### ISSUE TITLE
product_list_limit=all not working as expected

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7756]
### Preconditions

1. Magento 2.1.2 with sample data

### Steps to reproduce

1. Go to /admin/system_config/edit/section/catalog/ and change "Allow All Products per Page" to Yes.
2. Go to a subcategory page and click on a category attribute with enough products to paginate (e.g., /men/bottoms-men.html?cat=19).
3. Change the page limiter to "All".

### Expected result

1. All 11 products should be displayed. I'm pretty sure this was working in 2.0.x or 2.1.0.

### Actual result

1. It is still showing the paginated results.

**Comment by thdoan** [comment]
I noticed that `limit=all` works, it it seems the param name changed somewhere along the way. I'll close this.

**Comment by thdoan** [comment]
UPDATE: It appears the `limit=all` param doesn't work. When I changed the param to `product_list_limit=all`  things got better, but it still didn't work 100%. Summary:

1. When using `product_list_limit=all`, it shows all products, but the result count (23) is incorrect. I think it's showing the total number of results for the parent category, not the current subcat with the category attribute applied.
2. When using `limit=all`, the result count is correct, but it doesn't show all products (or rather, the result count is correct because it didn't actually do anything).

When did `product_list_limit=all` change to `limit=all`?

**Comment by VasylShvorak** [comment]
@thdoan thank you for your report. Is this issue still actual? We were not able to reproduce it on the ver. 2.1.7

**Comment by thdoan** [comment]
@VasylShvorak  I'm no longer on the M2 project, so sorry I cannot answer your question.

**Comment by sean-zero1** [comment]
Was there a fix for this or was it just randomly closed?
Still getting this on 2.3
