### ISSUE TITLE
Checkout : email address should not be part of the "shipping address" section

### ISSUE THREAD

**Issue by pitangaweb** [magento/magento2#7757]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. As a guest, add a product to your shopping cart and go to checkout
2. Since you are buying a gift that you want to be delivered directly to your friend, enter all your friend's information under the "shipping address" section, including his email address.
3. In the billing section, enter your personal address as the billing address

### Expected result

1. All transactional emails should be sent to you (the one who order), not to the order recipient.
OR
2. The email address field should not be part of the shipping address section, since it has nothing to do with the order recipient.

### Actual result

1. The order recipient receives all transactional emails.

This is very bad, when customers order gifts and want to have them delivered directly to the recipients, since these recipients receive order confirmations with item list and prices.
It should be very clear the email address requested has nothing to do with shipping. So there should be a dedicated section for the email address/login information.

Magento 1 did not have this ambiguity. I think I understand the idea behind this new "reversed" checkout, but customers have a hard time to understand it, between this issue and the fact that no billing address is asked when paying via PayPal Standard.

**Comment by ArthurTransoftgroup** [comment]
@pitangaweb We've created internal ticket MAGETWO-70065 to address this issue.

**Comment by magento-engcom-team** [comment]
@pitangaweb, thank you for your report.
We've created internal ticket(s) MAGETWO-70065 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@pitangaweb, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
