### ISSUE TITLE
 Problem with perfomance in dashboard (on new product page)

### ISSUE THREAD

**Issue by gerti2112** [magento/magento2#7761]
### Preconditions
1.  We have like as ~1700 categories (hierarchical)

### Steps to reproduce
1.  Open New Product Page
### Expected result
Loading is more fast. Error is missed
### Actual result
Browser warning about slow js "A script on this page may be busy..."

### Steps to reproduce
1.  Open New Product Page
2. Click new New Category 
### Expected result
Popup is opened. Loading is more fast. Error is missed
### Actual result
Browser warning about slow js "A script on this page may be busy..."

### Steps to reproduce
1.  Open Category management page
### Expected result
Tree is loaded for a very loooong time
### Actual result
Loading is more fast

**Comment by andimov** [comment]
@gerti2112 please, specify Magento version.
Please provide maximum and average depth in categories also.

**Comment by gerti2112** [comment]
Magento ver. 2.2.0-dev (732d445fe68b2c00a03dda546e3813dea04d441e)
Max deep is 6
Average is 3

**Comment by andimov** [comment]
We've created internal ticket MAGETWO-62129 to address this issue.

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate of #7469
