### ISSUE TITLE
Preferences declared in wrong modules.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#7764]
This is a followup for #1291. I ran some script on the `di.xml` files to identify which preferences are declared in the wrong module and came up with the list below.  
Sorry if this is not reported as requested, with steps to reproduce, because I didn't take any ui or cli actions to reproduce it.  
Please DON'T classify this as an improvement and send it to the forum. This should not be hard to fix (I'm even willing to grab it if you give the OK) and it could help uncouple some modules and prevent issues if some of them are disabled.  

<table border="1"><tr><td>Preference For</td><td>Type</td><td>Should be in</td></tr>
<tr><td colspan="3"><strong>app/etc/di.xml</strong></td></tr>
<tr><td>Magento\Store\Model\StoreManagerInterface</td><td>Magento\Store\Model\StoreManager</td><td>Magento/Store/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Backend</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Backend/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\App\Config\Storage\WriterInterface</td><td>Magento\Framework\App\Config\Storage\Writer</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Backend\Model\Auth\Credential\StorageInterface</td><td>Magento\User\Model\User</td><td>Magento/User/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Authorization\PolicyInterface</td><td>Magento\Framework\Authorization\Policy\Acl</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Acl\AclResource\ProviderInterface</td><td>Magento\Framework\Acl\AclResource\Provider</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento/Backend/etc/adminhtml/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Model\ActionValidator\RemoveAction</td><td>Magento\Framework\Model\ActionValidator\RemoveAction\Allowed</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Catalog</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Catalog/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Pricing\PriceInfoInterface</td><td>Magento\Framework\Pricing\PriceInfo\Base</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Pricing\PriceCurrencyInterface</td><td>Magento\Directory\Model\PriceCurrency</td><td>Magento/Directory/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Pricing\Adjustment\CalculatorInterface</td><td>Magento\Framework\Pricing\Adjustment\Calculator</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Cookie</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Cookie/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Stdlib\CookieManagerInterface</td><td>Magento\Framework\Stdlib\Cookie\PhpCookieManager</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Cron</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Cron/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Shell\CommandRendererInterface</td><td>Magento\Framework\Shell\CommandRenderer</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Customer</strong></td></tr>

<tr><td colspan="3"><strong>Magento/Customer/etc/adminhtml/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Session\SessionManagerInterface</td><td>Magento\Backend\Model\Session</td><td>Magento/Backend/etc/adminhtml/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Developer</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Developer/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\View\Asset\PreProcessor\ChainFactoryInterface</td><td>Magento\Framework\View\Asset\PreProcessor\ChainFactory</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Css\PreProcessor\ErrorHandlerInterface</td><td>Magento\Framework\Css\PreProcessor\ErrorHandler</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\View\Asset\PreProcessor\Helper\SortInterface</td><td>Magento\Framework\View\Asset\PreProcessor\Helper\Sort</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Email</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Email/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Mail\Template\FactoryInterface</td><td>Magento\Framework\Mail\Template\Factory</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Mail\TransportInterface</td><td>Magento\Framework\Mail\Transport</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Mail\MessageInterface</td><td>Magento\Framework\Mail\Message</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Indexer</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Indexer/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Indexer\Table\StrategyInterface</td><td>Magento\Framework\Indexer\Table\Strategy</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_NewRelicReporting</strong></td></tr>
<tr><td colspan="3"><strong>Magento/NewRelicReporting/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Module\ModuleListInterface</td><td>Magento\Framework\Module\ModuleList</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_ProductVideo</strong></td></tr>
<tr><td colspan="3"><strong>Magento/ProductVideo/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Validator\ValidatorInterface</td><td>Magento\Framework\Validator\AllowedProtocols</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Tax</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Tax/etc/di.xml</strong></td></tr>
<tr><td>Magento\Tax\Api\Data\OrderTaxDetailsItemInterface</td><td>Magento\Sales\Model\Order\Tax\Item</td><td>Magento/Sales/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Theme</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Theme/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\View\Element\Message\InterpretationStrategyInterface</td><td>Magento\Framework\View\Element\Message\InterpretationMediator</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\App\View\Deployment\Version\StorageInterface</td><td>Magento\Framework\App\View\Deployment\Version\Storage\File</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Translation</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Translation/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Translate\InlineInterface</td><td>Magento\Framework\Translate\Inline</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Translate\Inline\ProviderInterface</td><td>Magento\Framework\Translate\Inline\Provider</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Translate\Inline\StateInterface</td><td>Magento\Framework\Translate\Inline\State</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Phrase\RendererInterface</td><td>Magento\Framework\Phrase\Renderer\Composite</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento/Translation/etc/adminhtml/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Translate\Inline\ConfigInterface</td><td>Magento\Backend\Model\Translate\Inline\Config</td><td>Magento/Backend/etc/adminhtml/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_Ui</strong></td></tr>
<tr><td colspan="3"><strong>Magento/Ui/etc/di.xml</strong></td></tr>
<tr><td>Magento\Framework\Data\Argument\InterpreterInterface</td><td>Magento\Framework\Data\Argument\Interpreter\Composite</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Config\ConverterInterface</td><td>Magento\Framework\View\Element\UiComponent\Config\Converter</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\View\Element\UiComponent\ContextInterface</td><td>Magento\Framework\View\Element\UiComponent\Context</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Framework\View\Element\UiComponent\LayoutInterface</td><td>Magento\Framework\View\Layout\Generic</td><td>app/etc/di.xml</td></tr>
<tr><td>Magento\Authorization\Model\UserContextInterface</td><td>Magento\Authorization\Model\CompositeUserContext</td><td>Magento/Authorization/etc/di.xml</td></tr>
<tr><td>Magento\Framework\Api\Search\ReportingInterface</td><td>Magento\Framework\View\Element\UiComponent\DataProvider\Reporting</td><td>app/etc/di.xml</td></tr>
<tr><td colspan="3"><strong>Magento_LayeredNavigation</strong></td></tr>
<tr><td colspan="3"><strong>Magento/LayeredNavigation/etc/frontend/di.xml</strong></td></tr>
<tr><td>Magento\Catalog\Model\Layer\AvailabilityFlagInterface</td><td>Magento\Catalog\Model\Layer\Category\AvailabilityFlag</td><td>Magento/Catalog/etc/frontend/di.xml</td></tr>
</table>

**Comment by antonkril** [comment]
These are modularity bugs. Thank you for reporting, @strajeru.

**Comment by KrystynaKabannyk** [comment]
Hello @tzyganu, the task for static tests is created - MAGETWO-63568. It will define all similar issues for di.xml, and then we will be able to fix them.

**Comment by tzyganu** [comment]
@KrystynaKabannyk I picked this up myself. Just one more question. Since I'm cleaning up the di.xml files, do you think it's worth to make them more consistent? I mean, I want to move all `preference` tags at the top, then types with plugins, then types with arguments and in the end the virtual types.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu Thank you for investigation. We are looking for PRs from you! Closing the issue
