### ISSUE TITLE
Filter block on category is still present also mode is to just show "static block"

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#7765]
### Preconditions

1. Magento Versions 2.1.2 via download

### Steps to reproduce

1. Create a category and set it to just show a cms block

### Expected result

1. The layered filter navigation is not shown - as there are no products shown in the category just a cms block

### Actual result

1. The layered navigation block is shown on category site

I think this was reported here some times ago but i can not find it and it is still present on 2.1.2

![bildschirmfoto 2016-12-12 um 17 31 04](https://cloud.githubusercontent.com/assets/16196483/21107225/4bd49434-c091-11e6-9846-8a23d56b66f5.png)

Can someone maybe point us how to exclude this block via XML update on backend category view?

Many thanks!

**Comment by ArthurTransoftgroup** [comment]
We've created internal ticket MAGETWO-70347 to address this issue.

**Comment by george-vlahakis** [comment]
In case it helps anyone in the meantime, I know it is not best way but changing 

`Block\Category\View.php` `isContentMode` function to the following got rid of the side bar for me:

```
    /**
     * Check if category display mode is "Static Block Only"
     * For anchor category with applied filter Static Block Only mode not allowed
     *
     * @return bool
     */
    public function isContentMode()
    {
        $category = $this->getCurrentCategory();
        $res = false;
        if ($category->getDisplayMode() == \Magento\Catalog\Model\Category::DM_PAGE) {
            $res = true;
            if ($category->getIsAnchor()) {
                $state = $this->_catalogLayer->getState();
                if ($state && $state->getFilters()) {
                    $res = false;
                }
            }
        }

        // Added to remove side bar in static block only categories.
        if ($res) {
            $this->getLayout()->unsetChild('columns','div.sidebar.main');
            $this->getLayout()->unsetChild('columns','div.sidebar.additional');
            $this->getLayout()->unsetChild('columns','main');
            $this->getLayout()->unsetChild('main.content','columns');
        }
        return $res;
    }
```

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.
We've created internal ticket(s) MAGETWO-70347 to track progress on the issue.

**Comment by andidhouse** [comment]
@magento-engcom-team thanks for this. 
But to be honest creating a internal ticket to track the issue after 10 month is kind of senseless for us.
It now takes another 3-6 month to fix this? So we are one year later with a small fix - this is not a timeline we can live with to be honest.

**Comment by lano-vargas** [comment]
This is still an issue on 2.1.7 is there any temporary fix for this ?

**Comment by devamitbera** [comment]
In case, i am suggesting to  make   **Anchor  field** Value at **Display Setting**  to **NO** . 

> ,Bcoz by default at magento2Anchor field value is set As YES.

I have also check same scenario     at magento 1.X.If you category has  Products and *Display Setting**  to **YES**  and _**Display setting is only static block**_.Then on left panel ,you will layer navigations and right section CMS static block.

**Comment by lano-vargas** [comment]
@devamitbera  It does not work in *2.1.7** 
I've tested it 2.1.0 I can confirm it works. a reminder that both are clean magento installation.
Now the only solution I've came up with is to remove  with xml update  **catalog.leftnav**  instead of **sidebar.main**

**Comment by RomaKis** [comment]
Working on this.

**Comment by magento-engcom-team** [comment]
Hi @andidhouse. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1159 by @RomaKis in 2.2-develop branch
Related commit(s):
 - [39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9](https://github.com/magento/magento2/commit/39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9)

The fix will be available with the upcoming 2.2.4 release.

**Comment by DigitalStartupUK** [comment]
I considered this a feature carried over from M1. Allowing a Static Block to be displayed in the Main Content area whilst still allowing customers to narrow down their products (in the children categories) via the filter from the sidebar.

I guess to reverse this, I'd just need to override the files in the aforementioned commit?

**Comment by crysix** [comment]
This is not fixed in 2.2.5!

**Comment by priti2jcommerce** [comment]
Hi @crysix ,

this is fixed in 2.2.5
if there is need to remove  leftnav sidebar from category make the changes as below
![2018-09-28_11-42_women id- 20 - categories](https://user-images.githubusercontent.com/18118695/46191311-9d435d00-c314-11e8-8be9-c0e500d2da11.jpg)
and if there is need to remove leftnav sidebar and additional sidebar make the changes as below
![2018-09-28_11-46_women id- 20 - categories](https://user-images.githubusercontent.com/18118695/46191379-e98e9d00-c314-11e8-80b6-30975e7d7f21.jpg)

**Comment by crysix** [comment]
I know, that I can use that XML code, to remove the block (thats what I am doing currently), but that is no "fix"!!!
If you have 1 column, there shouldn't be a left sidebar at all.

**Comment by crysix** [comment]
Still not working in M2.3

**Comment by FL-KJ** [comment]
A simple workaround which works for me: edit line 18 of `/vendor/magento/module-layered-navigation/view/frontend/templates/layer/view.phtml` and change:

    <?php if ($block->canShowBlock()): ?>

to:

    <?php if ($block->canShowBlock() && $block->getLayer()->getCurrentCategory()->getDisplayMode() !== "PAGE"): ?>

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
