### ISSUE TITLE
Cart Hardcoding removing tax from total

### ISSUE THREAD

**Issue by 4DallasC** [magento/magento2#7769]
In file:- vendor/magento/module-checkout/Model/Cart/CartTotalRepository.php at 112
        $amount = $quoteTotals->getGrandTotal() - $quoteTotals->getTaxAmount();
        $amount = $amount > 0 ? $amount : 0;
        $quoteTotals->setCouponCode($this->couponService->get($cartId));
        $quoteTotals->setGrandTotal($amount);

This hard coded removal of tax is in contradiction to the configuration value stored at:- tax/cart_display/grandtotal.

The configuration value should be control the grand total's inclusion of tax, but isn't.

**Comment by choukalos** [comment]
Hello @4DallasC can you update this ticket per our bug submission guide ([link](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)).  In particular the pre-conditions and expected/actual results.

Thanks!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by 4DallasC** [comment]
It's unbelievable the effort you guys go to, to avoid fixing the issue.

**Comment by woxxy** [comment]
Also appears in https://github.com/magento/magento2/issues/5589

**Comment by springerin** [comment]
@4DallasC why don't you do a PR?

**Comment by snez** [comment]
@veloraven This is still an issue and manifests in the checkout front-end code:

![screen_shot_2018-02-27_at_23_20_40](https://user-images.githubusercontent.com/249977/36761016-14f4f64e-1c15-11e8-93e8-e473e2e2839f.jpg)

The grand total excludes the tax whereas the base grand total includes it, even if they are both in the same currency.

**Comment by mirko1989** [comment]
@veloraven still an issue as of version 2.2.5

**Comment by snez** [comment]
@choukalos this issue cannot be easily reproduced at the front-end, in my case I came across it while developing a module that injects the quote JS object in a component. But the issue is that the tax is omitted in the back end where @4DallasC pointed out. There is no step-by-step guide to reproduce this, something custom must be put together to have this manifest.

Possibly load the quote object from within a simple payment method like check/money order. Then dump the object in a log file and try to compare the base_grand_total with the grand_total, which will be different.

Can someone confirm the latest version of Magento where this issue manifests?

**Comment by yeegor** [comment]
Encountered the same issue in 2020. 
![image](https://user-images.githubusercontent.com/46347627/72991911-81ae7080-3dfb-11ea-892f-d1a2b1feb20f.png)
Magento CLI 2.3.3

**Comment by matthewhaworth** [comment]
I'm also experiencing this exact issue in 2.3.5. It's particularly strange because it is removing the tax amount but this code has been here for five years... was it previously working by chance and another bug fix elsewhere has brought it to light?

**Comment by matthewhaworth** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth, here is your [Magento instance](https://i-7769-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-7769-2-4-develop.instances.magento-community.engineering/admin_c448](https://i-7769-2-4-develop.instances.magento-community.engineering/admin_c448)
Login: `30cf1f06` Password: `eaf28056dfb6`
Instance will be terminated in up to 3 hours.

**Comment by 4DallasC** [comment]
> I'm also experiencing this exact issue in 2.3.5. It's particularly strange because it is removing the tax amount but this code has been here for five years... was it previously working by chance and another bug fix elsewhere has brought it to light?

I just gave up reporting bugs like this and just got used to fixing these bugs directly. I suggest you do the same.

**Comment by hoanglan87** [comment]
any idea why the issue still in 2.4 version?

**Comment by oleksiyzestlogic** [comment]
@magento give me 2.4-develop instance
