### ISSUE TITLE
When I place order using Braintree Credit Card Payment Method (Authorize and Capture) for virtual or downloadable product type, Order status show processing instead of complete 

### ISSUE THREAD

**Issue by sanjay-wagento** [magento/magento2#7770]
### Preconditions

1. Magento CE 2.1.1, PHP 7.0.14
2. 

### Steps to reproduce

1. Please configure Braintree CC payment method with Authorize and Capture option 
2. Place order for virtual or downloadable product
3. 

### Expected result

1. For virtual and downloadable product, we do not require shipment so order status must be complete

### Actual result

1. Right now order status is processing for virtual and downloadable product's order

**Comment by YevSent** [comment]
Hi @sanjay-wagento, thanks for reporting.
This is known issue and already fixed on develop branch. Also, this fix will be available in Magento 2.1.3 release.

If issue still will be reproducible, please, be free to reopen it.

**Comment by aishwaryasunarc** [comment]
I want to know files where you changed

**Comment by aishwaryasunarc** [comment]
I want to set virtual order status to processing. I am using Magento 2.2.2 version. According to my requirements, we don't want virtual order status change to complete when creating the invoice. We want processing status of the virtual order.

Please guide me for this
