### ISSUE TITLE
Issue in edit bundle product which added to the cart

### ISSUE THREAD

**Issue by dominicfernando** [magento/magento2#7774]
### Preconditions

1.Version: M2 EE 2.1.2
2. with FPC and cache enabled

### Steps to reproduce

1. Add bundle product to cart
2. Edit added bundle product

### Expected result

1. Changes and details needs to show according to selection(bundle product options)

### Actual result

1. No price change according to the selection

I have investigated the issue

module-bundle/Model/ResourceModel/Option/Collection.php -> appendSelections return wrong item count, when calling options from 
module-bundle/view/frontend/templates/catalog/product/view/type/bundle/options.phtml

After flush the cache its works fine for first load. after refresh page again section not working as expected because when cache flush some price calculations doing by magento but when cached, page is not execute those calculation.

**Comment by vzabaznov** [comment]
Hi @dominicfernando please use support for EE clients to add bug for EE edition

**Comment by magulin** [comment]
This bug also affects Community Edition, please re-open.

**Comment by Jrb1x** [comment]
@vzabaznov Please reopen this. Editing bundles after they've been added to the cart does not work on Magento 2.1.x, especially if its checkboxes.

**Comment by saiwingwu** [comment]
Please re-open, there's no summary and price does not change when editing an already added bundled product in the cart. It's on Magento 2.1.7.
