### ISSUE TITLE
M2.1.2 Cannot rewrite Magento\ConfigurableProduct\Block\Product\View\Type\Configurable

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7775]
This might have some similarities with #4400, but I cannot seem to rewrite `Magento\ConfigurableProduct\Block\Product\View\Type\Configurable` using `di.xml`

### Preconditions

1. Version 2.1.2

### Steps to reproduce

1. Create a `di.xml` with:

```xml
<preference for="Magento\ConfigurableProduct\Block\Product\View\Type\Configurable"
            type="Vendor\Module\Rewrite\Magento\ConfigurableProduct\Block\Product\View\Type\Configurable"/>

```

2. Create the class `Vendor\Module\Rewrite\Magento\ConfigurableProduct\Block\Product\View\Type\Configurable`:

```php
class Configurable extends \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable
{
    /**
     * Override the template.
     * @return string
     */
    protected function _toHtml()
    {
        die;
        return parent::_toHtml();
    }
}
```

### Expected result

1. It should `die()`.

### Actual result

1. It does not.

**Comment by mamsincl** [comment]
Any update? I face the same issue with version 2.1.3 ( try to inject extra bits of data into getJsonConfig() method)

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
