### ISSUE TITLE
CWE-476-1

### ISSUE THREAD

**Issue by AppChecker** [magento/magento2#7776]
We've checked source code of Magento 2.1.2 and found weakness in it. We haven't checked the work of the programm, we scanned only the source code. So we can't write instructions how tp reproduce the problem because it is not reproducable, it's just a weakness in code that should be fixed. Maybe this part of code is never executed but the weekness is the weekness.

in file:
[app/code/Magento/Usps/Model/Carrier.php](https://github.com/magento/magento2/blob/2c22ac4edddb99383d79a0295858c26ba28bf7b5/app/code/Magento/Usps/Model/Carrier.php#L1908)

```
        if ($response === false || $response->getName() == 'Error') {
            $debugData['result'] = [
                'error' => $response->Description,
                'code' => $response->Number,
                'xml' => $response->asXML(),
            ];
...
        }
```

if $response is false, method asXML will be called on false

related to #6715

**Comment by vzabaznov** [comment]
internal ticket created MAGETWO-62187

**Comment by vzabaznov** [comment]
@AppChecker please do not create more related issue, i've created internal issue that contains all your info from https://github.com/magento/magento2/issues/6715 , thanks)

**Comment by vzabaznov** [comment]
@AppChecker will be fixed in https://github.com/magento/magento2/issues/6715, close for now
