### ISSUE TITLE
Inconsistencies in SearchCriteriaBuilder

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7779]
There are currently 2 search criteria builders to choose from:

- `Magento\Framework\Api\SearchCriteriaBuilder`
- `Magento\Framework\Api\Search\SearchCriteriaBuilder`

`Magento\Framework\Api\SearchCriteriaBuilder` has an `addFilter()`-method that accepts a field and a value, which makes it easy to use. However, if you want to add a sort order with `addSortOrder()` you need to add an implementation of `Magento\Framework\Api\SortOrder`.

```php
$this->searchCriteriaBuilder
    ->addFilter('order_id', $orderId)
    ->addSortOrder($sortOrderObject);
```

`Magento\Framework\Api\Search\SearchCriteriaBuilder` is exactly the other way around: If you want to add a filter with `addFilter()` you need to add an implementation of `Magento\Framework\Api\Filter`, but if you want to add a sort order you can add a field and a direction:

```php
$this->searchCriteriaBuilder
    ->addFilter($filterObject)
    ->addSortOrder('created_at', 'ASC');
```

The first question is why are there two and which one to choose?

But secondly, Why are they so strangely inconsistent? Wouldn't it be better to use the same approach for both fields? Or am I missing the greater picture here?

**Comment by magento-engcom-team** [comment]
@kanduvisla, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
