### ISSUE TITLE
Payment methods - add ability to only enable for backend

### ISSUE THREAD

**Issue by seansan** [magento/magento2#778]
Would it be possible to add a config option per payment method that allows us to set and use the payment option for backend only?

http://magentotoolkit.com/code/magento-admin-only-payment-method/

**Comment by asemenenko** [comment]
Hi Seansan,

You can achieve it by configuring payment as Enabled = Yes on Default scope and Enabled = No on each website scope for the selected payment.

/regards

**Comment by seansan** [comment]
Agree that would work. 

Does sound as a workaround








Sent from my iPhone.

On 09 Jan 2015, at 13:51, asemenenko <notifications@github.com> wrote:

Hi Seansan,

You can achieve it by configuring payment as Enabled = Yes on Default scope and Enabled = No on each website scope for the selected payment.

/regards

**Comment by vpelipenko** [comment]
@seansan, thank you for posting this issue. Workaround is found. Closed.

**Comment by seansan** [comment]
euhmmm - with workaround I mean that it would be good to add it by default
as a setting .... I dont think editing on different store levels is the
solution ... (only a workaround)

**Comment by asemenenko** [comment]
Hi Seansan,

An improvement has been created to have the following parameters available for each payment method:
Enable = Yes/No [Website]
Enable for Backend = Yes/No [Global]

[Global] parameter is visible only on "Default" scope which will give an ability to avoid switching off  "Enable" parameter on every website.

/regards
Andrii

**Comment by seansan** [comment]
So enable = no and enable for backend = yes => will show the payment method
in backend only?

**Comment by asemenenko** [comment]
> So enable = no and enable for backend = yes => will show the payment method
in backend only?

Yes.

**Comment by JamesAnelay** [comment]
I agree that allthough this a possible way to do this. Apparently one of the aims of Magento2 is to make the admin freindly for merchants? This is certainly not obvious to a regular user.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Payment-methods-add-ability-to-only-enable-for-backend/idi-p/47333).

**Comment by rav-redchamps** [comment]
Anyone having similar problem might use a pre-built extension 

https://redchamps.com/payment-methods-for-backend-magento2-extension.html

This doesn't have the ability to enable existing payment methods for backend only but it offers 

-  9 offline payment methods which can be used for backend orders only
- It allows you to add payment handling fees(flat/percentage) for these payment methods

P.S. This is a paid extension.
