### ISSUE TITLE
Catalog page shows out of stock configurable products

### ISSUE THREAD

**Issue by sameasterling** [magento/magento2#7781]
Magento 2.0.10

Catalog page displays out of stock configurable item.

Expected result would be for the catalog page to display the product that is still in stock.

**Comment by vzabaznov** [comment]
Hi @sameasterling thank you for reporting, please check https://github.com/magento/magento2/blob/develop/CONTRIBUTING.md , format your issue due to https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md and describe all steps to reproduce issue, we cannot start to work on this ticket with current information

**Comment by sameasterling** [comment]
Steps to Reproduce
1. Create a configurable product.
2. Set the first one in the configurations list of products to out of stock. 

Expected Result
1. Magento should choose from one of the configurations that is in stock to represent the configurable product on the catalog page.

Actual Result
1. Magento chooses the out of stock configuration to represent the configurable product.
2. This creates a situation where customers are wanting to purchase a product that is not available.
3. If pricing is different for different configurations, the customer sees one price on the catalog page and another on the product page.
4. This becomes more confusing for the customer since Magento also does not show the out of stock configuration on the product page. It should be there, but grayed out. I believe there is already an issue opened for this.

**Comment by veloraven** [comment]
@sameasterling thank you for your report.
Could you please confirm if this issue still actual?
We were not able to reproduce it on ver. 2.0.14.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
