### ISSUE TITLE
Newsletter Confirmation Email for Guests

### ISSUE THREAD

**Issue by mtb2112** [magento/magento2#7782]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Enter email in newsletter subscription form as a guest user
2. Click submit button

### Expected result

1. Receive email confirmation of subscription

### Actual result

1. No email is sent to the registered email address.  Also, nothing in the trash/spam folder

**Comment by jaykobi** [comment]
Works  for me without problems in 2.1.2.

**Comment by eldonbite** [comment]
Experiencing this as well. Two scenarios in our site wherein newsletter subscription emails are not being sent:

1. Register with the subscribe to newsletter option ticked: registration email is sent but no newsletter subscription email
2. Subscribe as a Guest user (unregistered email): no newsletter subscription email

**Comment by veloraven** [comment]
@mtb2112 thank you for your feedback.
Is this issue still actual? 
We were not able to reproduce this issue.
Are other letters sent without problems?

**Comment by mtb2112** [comment]
I'm can't answer that as I am no longer working on any Magento platforms.

**Comment by veloraven** [comment]
I'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
