### ISSUE TITLE
Mode:set production fails.

### ISSUE THREAD

**Issue by PGLDK** [magento/magento2#7784]
I really got a annoying problem right now,
When trying to set:
php bin/magento deploy:mode:set production
it returns the following error:
Command returned non-zero exit code:
` -f /home/detintelligen_4/public_html/bin/magento setup:di:compile`

The log says:
[2016-12-13 21:25:49] main.ERROR:  -f /home/detintelligen_4/public_html/bin/magento setup:di:compile 2>&1
sh: 1: -f: not found [] []

If i run setup:di:compile - no error, or run;  php -f /home/detintelligen_4/public_html/bin/magento setup:di:compile 2>&1 = gives no error...
memory limit is -1

What to do?

**Comment by vzabaznov** [comment]
Hi @PGLDK please specify the magento version you are using

**Comment by PGLDK** [comment]
Hi, sorry. Ver. 2.1.1.

**Comment by veloraven** [comment]
@PGLDK thank you for update.
Could you please format the issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)? With steps to reproduce, actual result and expected result.
I understand that this information is already present in your description but it is much easier to see the problem and how to reproduce it when issue description is well-structured.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
