### ISSUE TITLE
Unable to add UI components to a customer edit form tab in backend

### ISSUE THREAD

**Issue by mcjwsk** [magento/magento2#7785]
### Preconditions
1. Magento 2.1.2 CE
2. PHP 7.0.13

### Steps to reproduce
1. Create a grid via ui components.
2. Add a new (ajax or standard) tab to the customer edit form in admin.
3. Add the grid to the tab.
4. Go to the customer edit page in admin and open the tab.

### Expected result
1. Spinner is hidden.
2. Grid is rendered.

### Actual result
1. Spinner is visible all the time.
2. Grid is not rendered:

see screenshot with an ajax tab:
![see a screenshot](https://cloud.githubusercontent.com/assets/284649/21161402/b73bda32-c188-11e6-9bcd-dba543b18c12.png)

see screenshot with a standard tab:
![zrzut ekranu 2016-12-14 14 08 23](https://cloud.githubusercontent.com/assets/284649/21183141/ce2cdccc-c206-11e6-8b27-0bd2ba509bec.png)

**Comment by magento-engcom-team** [comment]
@DariuszMaciejewski, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
