### ISSUE TITLE
Cannot Install Theme / Integral Backend Errors on Install

### ISSUE THREAD

**Issue by LukasAEI** [magento/magento2#7786]
### Preconditions

1.  Sub-domain hosted from a Siteground Apache server, Linux OS, Cpanel
2. Version 2.1.2, MySQL Ver: 5.6.31-77.0 , Tried PHP: 5.6.28 and 7.0.13

### Steps to reproduce

1. Install fresh Magento installation through Softalicious, 
2.Deploy Static Content (Or not, happens either way)
3. Log in to back end.

### Expected result

1. Non functional back-end buttons, developer and host team kept hitting the following errors. 

### Actual result

1. https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/11012286162/original/m0-gUMLCuoeBdORqDpVzLGTC0XIQIqf3UQ.png?1481615408

As some background info we've been trying to install a theme on a fresh and repeatedly reinstalled version of Magento 2, both using the Softalicious installer and the one available from Magento. In all cases the back-end is virtually useless and requires multiple steps to even gather some halting form of functionality. Two independent developers have already failed to find a solution and a third is out of ideas.

**Comment by vzabaznov** [comment]
Hi @LukasAEI seems like you have problem with static assets deployments please check http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html and let me know if it helps?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
