### ISSUE TITLE
REST Api: not returning option_id in any call

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7787]
Hi there,

I cant retrieve option_ids with any call, here below is where i assume the option_id is returned.

Repository: "catalogProductAttributeOptionManagementV1"
URL: "/V1/products/attributes/{attributeCode}/options"
Method: "GET"

**EDIT & FIXED**
the value key from the response is the option_id, 
this is very unclear from my perspective

**Comment by mrkhoa99** [comment]
@SinisterGlitch it's better if you post your question on [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by veloraven** [comment]
@SinisterGlitch thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
