### ISSUE TITLE
Some of magento 2 admin features not displaying

### ISSUE THREAD

**Issue by Uvestudio** [magento/magento2#7788]
Some of my magento admin page panels are not being displayed.

### Preconditions

1. I try to access to modify the logo for the default e-mail templates following Stores-Settings-Configuration-General-Design
2. Once I open "Design" it should display a tab called "E-mails".
3. Only a tab called "Search Engine Robots" is displayed.

### Expected result
From Magento 2.1.1 user Guide:

1. On the Admin sidebar, tap Stores. Then under Settings, choose Configuration.
2. In the panel on the left, under General, choose Design.
3. Expand the Emails section. Then, do the following:
a. To upload your prepared Logo Image, tap Browse. Find the file on your computer, and
select the file.
b. In the Logo Image Alt field, enter alternate text to identify the image.
c. Enter the Logo Width and Logo Height in pixels. Enter each value as a number, without
the “px” abbreviation. These values refer to the display dimensions of the logo in the
header, and not to the actual size of the image.
Step 2: Choose the Header and Footer Templates
If you have custom header and footer templates for your store, or for different stores, you can
specify which templates are used for each, according to the scope of the configuration.
1. Choose the Header Template to be used for all transactional email messages.
2. Choose the Footer Template to be used for all transactional email messages.
3. When complete, tap Save Config.

### Actual result

1. Just the Search Engine Robots tab is displayed.
 ![1](https://cloud.githubusercontent.com/assets/24565189/21178979/3daa1f16-c1f2-11e6-9441-9e795a5ac8e2.png)

**Comment by quienti** [comment]
Not a bug: https://github.com/magento/magento2/issues/7520
