### ISSUE TITLE
[backend] Performance issues with the bulk edit component

### ISSUE THREAD

**Issue by guvra** [magento/magento2#7789]
### Description

The bulk edit component has huge performances issues.
Each time bulk edit mode is enabled (using the "Modify" mass action), the component becomes exponantially slower, up to a point where the browser freezes.

This problem occurs on all grids that rely on the bulk edit component (customers, CMS blocks, CMS pages).

### Preconditions
1. Reproduced on Magento 2.1.2.
2. Tested browsers : Chromium and Firefox

### Steps to reproduce

I can consistently reproduce the bug with the following steps:

1. In the backend, go to a grid that uses the bulk edit component (e.g. CMS blocks). Make sure the grid contains at least 40 records (2 pages of 20 records).
2. Select all records.
3. Enable bulk edit, by selecting the "Modify" mass action (inline editing should work fine here).
4. Go to page 2.

### Expected result
1. The bulk editor should replace records from page 1 with records from page 2.

### Actual result
1. The browser freezes.

We planned to use this component for a custom price management grid, but the performance issues forced us to reconsider this choice :disappointed:

**Comment by magento-engcom-team** [comment]
@guvra, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
