### ISSUE TITLE
php install script help only available after installation

### ISSUE THREAD

**Issue by nyov** [magento/magento2#779]
The README [(Running the Magento 2 installer)](https://github.com/magento/magento2#running-the-magento-2-installer) says

> Before you begin, you can run the following commands to find values for some required options:
> `php -f index.php help languages` [...]

These actually only produce results after an installation, aside from failing without any helpful error messages (`Reason for failure: Invalid arguments or no arguments provided`), which almost had me thinking the installer was broken there for a while.

What made matters worse for me, the script will _always_ "silently" fail, if run from inside the setup directory, while the README explicitely states

> You must install Magento from its setup subdirectory.

The above mentioned README lines should really read something like `php -f setup/index.php help languages`, and fix the notice to say that the script is supposed to be run from the magento root directory.
Unless this is a temporary hiccup and supposed to work differently later.
(version tested 0.1.0-alpha106 / e05a60c2ecbbf94019bc4bdc049b37d5a4094e6a)

Thanks

**Comment by xcomSteveJohnson** [comment]
FWIW, added a note here: http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli.html#instgde-install-cli-first
