### ISSUE TITLE
Composer require develop branch

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7791]
In my composer.json I have:

```
"require": {
        "magento/product-enterprise-edition": "2.1.2",
        "magento/data-migration-tool": "2.1.2",
```

Due to the vast number of bugs with 2.1.2 I would very much like to develop with 2.2 (develop)

Is there any way in composer.json to pull directly from the develop branch of magento2?

In production (which is a while away) I will switch it back to 2.1.2

It's further complicated by the fact I am developing with enterprise.

**Comment by shiftedreality** [comment]
Hi @craigcarnell 

To use unreleased `develop` branch you have to clone it via Git.
Closed.
