### ISSUE TITLE
Checkout error for logged in existing (pre-migration) customer

### ISSUE THREAD

**Issue by lifemaxlimited** [magento/magento2#7793]
### Preconditions
1. Magento 2.1.2 - PHP7

### Steps to reproduce
1. Login in with existing customer
2. Add products to cart
3. Progress to cart

### Expected result
1. Cart should successfully complete

### Actual result
1. At the 'Reviews and Payments' step the cart throws an error when pressing 'Place Order':

'An error occurred on the server, please try to order again.'

On inspection its showing:

'Failed to load resource: the server responded with a status of 400 (Bad Request)'

http://www.mywebsite.com/rest/glg/V1/carts/mine/payment-information

I have my suspsiosns that this is something to do with address formatsd for old account. Maybe the 'street' attribute?

Debugging has given me this:

{message: "An error occurred on the server. Please try to place the order again.",…}
message
:
"An error occurred on the server. Please try to place the order again."
trace
:
"#0 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(9, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#1 /var/www/html/magento/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#2 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(9, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#3 /var/www/html/magento/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)↵#4 /var/www/html/magento/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()↵#5 /var/www/html/magento/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#6 /var/www/html/magento/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#7 /var/www/html/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()↵#8 /var/www/html/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))↵#9 {main}"
Name

I'm seriously lost, have tried everything and cannot get this issue sorted. Please help

**Comment by magento-engcom-team** [comment]
@lifemaxlimited, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by lifemaxlimited** [comment]
I am out of the office until Tuesday 2nd October with limited access to email. If your enquiry is urgent, please contact orders@lifemaxuk.co.uk or call 01635874323.
