### ISSUE TITLE
Buy X Get Y Free not working (also tried with combinations)

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7795]
### Preconditions

1. v2.1.2
2. PHP 7.0.11

### Steps to reproduce

1. Create catalog price rule (Buy 3 Get 1 Free)
2. Add some conditions (Category, attribute etc ..)
<img width="998" alt="scr" src="https://cloud.githubusercontent.com/assets/4427628/21185155/29d26004-c218-11e6-81b8-9ef92b037643.png">

3. Save

### Expected result

1. Saving successful
2. Add 4 product to cart and expect 1 (lowest price) has to be free.

### Actual result

1. Not working. Add 4 products to cart, there is no discount (developer cries silent tears 😢 )

**Comment by jmtakahashi** [comment]
@rbostan when you add conditions in the ACTIONS panel, are they saving properly? After saving, re-open the panel and see if your chosen actions are still there?

I ran into this problem tonite, same environmnet and version as you (v. 2.1.2 and php7) and when I click on the conditions in the actions panel to pick items from a certain category, half the time the category chooser will open, the other half of the time it will not, but even when it allows me to tick a category, it will not save...thus the rule won't work.

Hopefully if I or @rbostan are doing something wrong here, someone can let us know.  If not, this seems to be a bug.

**Comment by cizgidekiadam** [comment]
@jmtakahashi I didn't faced that like you. Everything working fine on ui and indexer side. 
But rule not working on cart or checkout summary.

**Comment by jmtakahashi** [comment]
@rbostan ok, apologies.  I was able to get the rule working on my cart and checkout summary by filling out the Conditions area and leaving the  Actions -> Conditions area blank.  However, it will only give the customer the free item IF it is the same item as the first 2 that are being purchased (same SKU).  I need to find a way to make the lowest priced item in the same CATEGORY to be the free item.

Please update if you find anything about your situation.

Thanks.

**Comment by jmtakahashi** [comment]
@rbostan @veloraven any word on this?  It's been over 2 months.

**Comment by IlnitskiyArtem** [comment]
@rbostan Cart price rule applied if you buy 3 identical products (qty=3), you will get the 1 completely free. (Discount = Product Price)

**Comment by cizgidekiadam** [comment]
@IlnitskiyArtem if that is working like that, not useful for me. We need calculate lowest product to set free.

@veloraven I don't understand 'needs update' label. It's been six months here, how can we 'update' more that ?

**Comment by IlnitskiyArtem** [comment]
@rbostan The GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by shweta2014** [comment]
Hello,
Any update on this issue, I am facing the same issue. I want to apply the rule as Buy 2 Item and get 3rd Item free, which will be of the lowest price. 
Magento Version 2.2.7
PHP 7.0

**Comment by paritsawjani** [comment]
Hey,
Facing same issue. Any fixes? I want to apply the rule as Buy 1 Item and get 1 Item free.
