### ISSUE TITLE
In case you are still stuck: "Cannot change customer groups"; here is the answer

### ISSUE THREAD

**Issue by flnative** [magento/magento2#7796]
Found the answer here when you cannot change a customer to another customer group. Looks like a bug to me. But Magento developers will say it is not.

http://stackoverflow.com/questions/23255545/magento-ce-customer-groups-changing-not-saving

Solved! I had to tick the 'Disable Automatic Group Change Based on VAT ID' box under customer group dropdown under the Account Information tab when you edit a particular customer's information.

**Comment by veloraven** [comment]
I'm closing this issue as solved.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
