### ISSUE TITLE
Add possibility override product image placeholder via theme config xml

### ISSUE THREAD

**Issue by Koc** [magento/magento2#7797]
### Preconditions

1.  Magento 2.1.2, PHP 7.0.11

Currently image placeholders can be changed by uploading in admin panel. This is inconvenient because of:

1. need upload images by hand after site deploy. It is better to ship theme with predefined placeholders
2. no way use different placeholders for different theme

Maybe same thing for watermark image

**Comment by veloraven** [comment]
@Koc thank you for your feedback.
 We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by Koc** [comment]
@veloraven this is technical feature request, can technical feature requests leave here?

**Comment by veloraven** [comment]
@Koc GitHub issue tracker is intended for technical issues only - as an 'issue' it means situation when we have difference between actual result and expected result.
And what you describe - it is lack of functionality. So it should be moved to the mentioned forum.
