### ISSUE TITLE
Magento 2.1 REST API Adding and updating a gift card

### ISSUE THREAD

**Issue by worthige** [magento/magento2#7798]
### Preconditions

1. Magento v2.1
2. C#

Is it possible to create a new gift card using the REST API?
We would like to import new gift card information from an external source and create the record in Magento.  
We would also need to be able to update the remaining balance on a card.
The giftCardAccountGiftCardAccountManagementV1 requires a CartID which doesn't seem relevant for the use case that we are looking for.

**Comment by veloraven** [comment]
@worthige thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an improvement please refer to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
