### ISSUE TITLE
Upgrade 2.0.10 to 2.1.2 - User Account heading at the bottom instead of at the top

### ISSUE THREAD

**Issue by yzhang-bwgroup** [magento/magento2#7800]
Hi,

I got some styling issues after updating to version 2.1.2 from magento 2 v2.0.10,
The heading of the user account page is moved to the bottom instead of staying on top of the page.
The below example shows the "My Orders" page in the user account with the heading at the bottom.
Other pages in the user account also have the same behavior.

If install v2.1.2 from scratch, I do not have this problem.

Both instances of magento are installed on the same machine.

Step to reproduce:

1. Install Magento 2.0.7 (compressed file version)
2. Upgrade using Setup Wizard to Magento 2.0.10
3. Upgrade using Setup Wizard to Magento 2.1.2

Actual Result:
Account Information page headings at the bottom of page 

Expected Result:
Account Information page headings at the top of page

![gtb6x](https://cloud.githubusercontent.com/assets/16341542/21196307/2aa79282-c205-11e6-9051-aaa50aa5b0a3.jpg)

**Comment by veloraven** [comment]
@yzhang-bwgroup thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
