### ISSUE TITLE
Provide command for cleaning generated data and cache

### ISSUE THREAD

**Issue by Koc** [magento/magento2#7802]
### Preconditions

1. Magento 2.1.2 -> 2.1.3
2. PHP 7.0.11
3. redis cache

### Steps to reproduce

1. Upgrade using composer
2. execute `setup:upgrade` comand

### Expected result

1. updation process

### Actual result

1. An error message with suggest removing var/cache, var/page_cache etc

The main problem: I've forgot that my cache stored in redis instead of file. It is better create small command/file inside bin directory which will bootstrap light version of Magento, read config from env.php and clean all needed folders/cache depends on settings. And suggest execute this file instead of remove directories by hand.

**Comment by choukalos** [comment]
Hi @Koc - you can use bin/magento cache:clean or cache:flush commands and they'll clear out the files or redis to clear the caches.

Seems like we can look at this portion of the deploy journey and make it better.  I'll pass on to Misha, our PO for deployment.

**Comment by Koc** [comment]
I cann't call this command because an error. No one console command works after update until cache not flushed

**Comment by misha-kotov** [comment]
Are you saying that once you get the error above, you can't run any other commands until you run "cache:flush"? Were you able to run "setup:upgrade" after that?

**Comment by Koc** [comment]
> Are you saying that once you get the error above, you can't run any other commands until you run "cache:flush"? 

looks like yes

> Were you able to run "setup:upgrade" after that?

cann't check this because already have cleared redis cache by hand and have not possibility recreate 2.1.2 env and upgrade it to 2.1.3 again and check this.

Just say that this part can be improved for future upgrades.

**Comment by magento-engcom-team** [comment]
@Koc please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
