### ISSUE TITLE
Can´t update 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by bbtimx** [magento/magento2#7803]
### Preconditions
Can´t update 2.1.2 to 2.1.3

### Steps to reproduce

1. Backend -> Web Setup Wizard
2. System Upgrade
3. Readiness Check

### Expected result

1.  Successful Readiness Check

### Actual result

![image](https://cloud.githubusercontent.com/assets/4718129/21200118/7d80a37c-c246-11e6-9f01-c211a0e30868.png)

**Comment by elenleonova** [comment]
Hi @bbtimx, 
This isn't an issue with core Magento. In this case your Magento requires a 3rd party extension - deltra/orgamax, which requires magento/framework 100.0.*. However, Magento 2.1.x 
has magento/framework 101. * 

So you need to have this extension updated to work with Magento 2.1.3.

**Comment by bbtimx** [comment]
hi @elenleonova ,
but I haven´t even installed deltra/orgamax.
This Package I can´t install although..
Can you help me out?

Thx bbtimx
