### ISSUE TITLE
product media api in magento 2 for image update by loading product

### ISSUE THREAD

**Issue by lovey11aug** [magento/magento2#7806]
I was using below code to fetch product images using product media api in magento 1.9.X version
**Mage::getModel('catalog/product_attribute_media_api');**

Please help me out that how I can load object of this model in Magento 2.
I only want object of this **"product_attribute_media_api"** model

**Comment by veloraven** [comment]
@lovey11aug thank you for your submission. 
The Magento 2 GitHub repository is used to capture code and documentation issues. Questions should be posted to a question and answer site, such as [Stack Exchange](https://magento.stackexchange.com/) and the [Magento Forums](https://community.magento.com/), where Magento community members can quickly provide recommendations and advice.
