### ISSUE TITLE
Disable add to basket

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7810]
We use Magento 2 for both ecommerce and non-ecommerce store fronts. In previous Magento versions we have had to edit templates to remove add to basket (category page, product page, crosssells, upsells, related products) and remove the basket link.

We've also had to disable the checkout through controllers.

Could we make this a standard magento 2 feature that turns this into an admin setting? rather than editing a bunch of templates.

**Comment by veloraven** [comment]
@craigcarnell thank you for your feedback.
The GitHub issue tracker is intended for technical issues only.
As your proposition seems to be a feature request please transfer it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
