### ISSUE TITLE
Getting error after upgrade magento 2.0.5 to 2.1.2

### ISSUE THREAD

**Issue by bhaiyyalal** [magento/magento2#7812]
1 exception(s):
Exception #0 (InvalidArgumentException): Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery doesn'n extend \Magento\Framework\Data\Form\Element\AbstractElement

**Comment by veloraven** [comment]
@bhaiyyalal thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
