### ISSUE TITLE
Magento 2 - Problem guest cart REST -  rest/V1/guest-carts

### ISSUE THREAD

**Issue by lucav90** [magento/magento2#7814]
Hi,

this is my php code to add a product on guest shopping cart, json response that the product is added on shopping cart but if i go to website (guest access) i don't view the product on cart page. How can do this?

How is wrong in my code?

`// section TOKEN
$userData = array("username" => "admin", "password" => "pass");
$ch = curl_init("http://www.website.it/index.php/rest/V1/integration/admin/token");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($userData));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Content-Lenght: " . strlen(json_encode($userData))));

$token = curl_exec($ch);

// section GUEST CART
$ch = curl_init("http://www.website.it/index.php/rest/V1/guest-carts");

curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));

$result2 = curl_exec($ch);

$quote_id = json_decode($result2, 1);

echo $quote_id;

$ch2 = curl_init("http://www.website.it/index.php/rest/V1/guest-carts/" . $quote_id . "/items");		
$product_option['extension_attributes']['customOptions'][] = array("option_id" => $_GET['option_id'], "option_value" => $_GET['option_value']);
$cartaddData['cart_item'] = array("quote_id" => $quote_id, "sku" => $_GET['sku'], "qty" => $_GET['quantity'], "product_option" => $product_option);

curl_setopt($ch2, CURLOPT_CUSTOMREQUEST, "POST"); 
curl_setopt($ch2, CURLOPT_POSTFIELDS, json_encode($cartaddData));
curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch2, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));
$result = curl_exec($ch2);

$result = json_encode($result);

print_r($result);`

I have Magento ver. 2.0.7

**Comment by lucav90** [comment]
Thereare guides or solutions to solve this problem with webapi REST?

**Comment by veloraven** [comment]
@lucav90 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think there is an issue please feel free to create new GitHub issue formatting it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
