### ISSUE TITLE
(Usability)Bug/Feature Request: Checkout validation message below the button

### ISSUE THREAD

**Issue by clarkeverdel** [magento/magento2#7817]
I am having difficulties with the user experience on the first step of the checkout. 

**Scenario:**
1. User fills out his address information
2. Scrolls down below to submit the form and go to the next step.
3. Hey! The button is not working. Weird...

When the invalid fields are not visible because they are above the fold, the end user is not notified of the problems with his information. In some cases the user may be smart enough to scroll up and see if there are invalid fields, but you may understand that not every user is thinking about doing that.

**Possible solution**
1. Automatically scroll to the first invalid field on the page
2. Notification message below the submit form to inform the user that he has to fill out his invalid forms. 

I am curious about what you guys think of this problem, and maybe already have a solution for me?

Cheers,

Clarke

<img src="http://oi64.tinypic.com/ns09f.jpg" />

**Comment by veloraven** [comment]
@claverwebdesign thank you for your submission.
However it looks like an improvement, not an issue.
Please submit it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)). As  GitHub issue tracker is intended for technical issues only.
