### ISSUE TITLE
After update from 2.1.2 to 2.1.3 CE Additional tabs dissapeared

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#7823]
### Preconditions

After Upgrade 2.1.2 to 2.1.3
### Expected result

1. Additional tabs should be on product page

### Actual result

1. No additional tabs

**Comment by phillipmeyer** [comment]
I think this relates to this issue, seems like editing anything is broken for some people (including me)
https://github.com/magento/magento2/issues/7834

**Comment by veloraven** [comment]
@Tonop thank you for your feedback.
Did you try to clean browser cache including offline website data?

**Comment by Tonop** [comment]
I found the reason-I cant apply customized theme.Default theme overrides tab settings of custom theme.

**Comment by magento-engcom-team** [comment]
@Tonop Closing this issue, as from your comment it looks like the issue you were reporting is already resolved on your side. Please reopen and update information if the issue persists.
