### ISSUE TITLE
Grunt does not compile my Custom Modules

### ISSUE THREAD

**Issue by vjacquemin-sqli** [magento/magento2#7824]
### Preconditions

Magento 2.1.2 & PHP 7 & MySQL 5.6

### Steps to reproduce

1. Install Grunt
2. Configurate Grunt on Magento 2 project
3. Run grunt watch

### Expected result

1. On Less modification on custom modules in app/design/frontend/<MyVendor>/<mytheme>/**<MyVendor>_<Module>**/web/css, grunt watch should compile Less to CSS

### Actual result

1. Nothing. But it works on Less modification on Magento modules in app/design/frontend/<MyVendor>/<mytheme>/**Magento_<Module>**/web/css
2. grunt exec:<my_theme> symlinks only Magento modules and not my custom modules

**Comment by patruvlad** [comment]
Can you provide a folder structure for your module? I have created some custom modules with style files and they compile without any issue

**Comment by magento-engcom-team** [comment]
@vjacquemin-sqli, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10
