### ISSUE TITLE
Bug product import additional images

### ISSUE THREAD

**Issue by jalogut** [magento/magento2#7826]
Import products fails when additional_images uses a value separator different than ","

### Preconditions

1. Magento C.E - 2.3 

### Steps to reproduce

1. Create one Product with several images 
2. Go to `System -> Export` and export all products  
3. Open generated `.csv` file
4. Edit `additional_images` field to separate images using ";" instead.
![additional_images field](https://cloud.githubusercontent.com/assets/6410900/21229468/f98b4512-c2e1-11e6-9d01-50907eb16f01.png)

5. Go to `System -> Import``
6. Edit following configuration: (See screenshot)

    * Allow errors count -> 1
    * Multiple value separator -> `;`
    * Images File Directory -> `pub/media/catalog/product`

7. Press button `Check File`

### Expected result
File check is successful

### Actual result
Error: Wrong url/path used for attribute additional_images
Attached screenshot
![import error](https://cloud.githubusercontent.com/assets/6410900/21229454/f00e1fa0-c2e1-11e6-93a0-33c440511b69.png)

**Comment by jalogut** [comment]
The source of the Bug is the following:

**The value used to explode the filename values is different during validation and import steps**

Validation Step:
```
\Magento\CatalogImportExport\Model\Import\Product\Validator\Media
public function isValid($value)
{
   //...
   foreach (explode(self::ADDITIONAL_IMAGES_DELIMITER, $value[self::ADDITIONAL_IMAGES]) as $image) {
   //...
   }
}
```
Import Step:
```
\Magento\CatalogImportExport\Model\Import\Product

public function getImagesFromRow(array $rowData)
{
    //...
    $images[$column] = array_unique(
        explode($this->getMultipleValueSeparator(), $rowData[$column])
    );
    //...   
    $labels[$column] = explode($this->getMultipleValueSeparator(), $rowData[$column . '_label']);
    //...   
}
```

When the Value separator configured for the import is different than "," the validation goes through but the import fails because the value separator used for the explode is not a coma.

Please use the same separator for "additional_images" everywhere.

We also noticed that the separator for the export uses another different constant. From my point of view, here we should also use the same constant.

```
\Magento\CatalogImportExport\Model\Export\Product

   private function appendMultirowData(&$dataRow, &$multiRawData)
   {

    //...
    $dataRow['additional_images'] = implode(Import::DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR, $additionalImages);
    $dataRow['additional_image_labels'] = implode(Import::DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR, $additionalImageLabels);
    //...

   } 
```

**Comment by nikoelgatito** [comment]
I agree on this one, I was about to import a large file and I was surprised that the `additional_images` column was not using the same delimiter. Although easy to figure out, to prevent confusion the same `Multiple value separator` should be used throughout the CSV file.

**Comment by linyusuomi** [comment]
Yep, got same issue, delimiter for additonal_images is hardcoded => coma. but getImagesFromRow(array $rowData) using $this->getMultipleValueSeparator().

**Comment by cuiyang000** [comment]
Same issue here, the self::ADDITIONAL_IMAGES_DELIMITER is really causing confusing.

**Comment by surfer190** [comment]
So the interim solution is: in `magento/module-catalog-import-export/Model/Import/Product/Validator/Media.php`:

Change the hard coded image delimiter to:

```
    const ADDITIONAL_IMAGES_DELIMITER = '|';
```

Or rewrite that file

**Comment by surfer190** [comment]
@jalogut Can you propose a solution that get's the multiple value delimiter?

**Comment by joachimVT** [comment]
I'm having the same issue in Magento ver. 2.1.4.

My solution was to rewrite the file and edit the 

`    const ADDITIONAL_IMAGES_DELIMITER = '|';`

Rewrite in di.xml:

`<preference for="Magento\CatalogImportExport\Model\Import\Product\Validator\Media" type="Project\Import\CatalogImportExport\Model\Import\Product\Validator\Media" />`

**Comment by PieterCappelle** [comment]
Already 2 PRs are available to fix this one > https://github.com/magento/magento2/pull/6774 &  https://github.com/magento/magento2/pull/5082

**Comment by jalogut** [comment]
As mentioned on PR #5082 this issue is already fixed in current develop branch:

- https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php#L81
