### ISSUE TITLE
DOM schema validation error

### ISSUE THREAD

**Issue by idziakjakub** [magento/magento2#7827]
I have created new payment method and I tried to add custom UI component in "checkout_index_index.xml", but there was problem with DOM schema validation.
This problem appears only when I use developer mode (like in this issue: https://github.com/magento/magento2/issues/4731)

### Preconditions
1. Magento 2.1.2
2. Custom payment method

### Steps to reproduce

1. Add product to cart
2. Enter to checkout

### Expected result

New payment method visible in checkout.

### Actual result

1. Exception:
Warning: DOMDocument::schemaValidate(): Invalid Schema in /home/vagrant/repos/magento2/vendor/magento/framework/Config/Dom.php on line 311

2. After some modifications, error from DOMDocument::schemaValidate method:
complex type 'handleType', attribute 'base': The QName value 'layoutType' does not resolve to a(n) simple type definition.

## Founded solution
I have checked other branches and commits for files:
- magento2/vendor/magento/framework/Config/Dom.php 
- magento2/vendor/magento/framework/View/Layout/etc/layout_merged.xsd

And I see that branch "develop" has some fixed for this: (Issues: MAGETWO-55684, MAGETWO-55689):
https://github.com/magento/magento2/commits/develop/lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd

https://github.com/magento/magento2/commits/2.1/lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd

but this fixes are still not in main version. 

I have added this modifications to my project and that fixed this problem.

**Comment by tmotyl** [comment]
To reproduce, you can just open /layout_merged.xsd in phpstorm with magento xml namespaces loaded, and see that `layoutType` is marked red ;)

**Comment by tmotyl** [comment]
@maksek Would you mind taking a look at it during hackathon? This ticket is really easy to solve, just cherry pick some commits form development branch.
And it is a big pain now that development mode is not working, and validation schema is ... invalid.

**Comment by okorshenko** [comment]
Please, look at:
237e54d79c70d8954f16556a3a8195a8b7b6d942
7bed7ef0277a82552051c769afe054708c56bde7
397fa26f775ebe93c742fe3e4937d68571abf4b5

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70394
