### ISSUE TITLE
After update from 2.1.2 to 2.1.3 no color swatch in catalog view

### ISSUE THREAD

**Issue by MoschenBayern** [magento/magento2#7828]
### Preconditions

1. Magento2.1.3
2. PHP 7.0.14
3. Debian 8.6

### Steps to reproduce

1. Upgrade via Web Setup Wizard from 2.1.2 to 2.1.3
2. No errors
3. Clear all caches
4. Reindex

### Expected result

1. Same catalog view as on 2.1.2. If product has multiple colors the visual color swatch should be shown in catalog view.

![2 1 2](https://cloud.githubusercontent.com/assets/24587516/21231214/b85eca0e-c2e7-11e6-9b4d-ae4ce03c4eef.JPG)

### Actual result

1. No visual color swatch in catalog view. If you go to product page, the visual color swatch is working.

![2 1 3](https://cloud.githubusercontent.com/assets/24587516/21231215/b86102ba-c2e7-11e6-8d1f-a00cf89cfe66.JPG)

How can i fix this problem?

**Comment by magento-engcom-team** [comment]
@MoschenBayern, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
