### ISSUE TITLE
Table Rates not working -- solved!

### ISSUE THREAD

**Issue by thomas-villagers** [magento/magento2#7829]
Hi, 

I have a problem with magento table rates. 

What I want is just the simplest table rate based on Weight vs. Destination. 
Let's start simple with just two rules:

- packages up to 2 Kg have a shipping rate of 5 
- packages 2 kg and above should have a shipping rate of 7.5

Contents of my tablerates.csv:

`Land,Region/Bundesland,Postleitzahl,"Gewicht (und höher)",Versandkosten

DE,*,*,0,5

DE,*,*,2,7.5`

Upload works, as is reflected in the table shipping_tablerate: 

![bildschirmfoto von 2016-12-15 17 38 51](https://cloud.githubusercontent.com/assets/1818737/21232846/631d4b6e-c2ed-11e6-8d84-2e1aa73e8da2.png)

I have 1 product in store with a weight of 1 kg: 

![bildschirmfoto von 2016-12-15 17 42 43](https://cloud.githubusercontent.com/assets/1818737/21233022/fd0a64d2-c2ed-11e6-985c-064b2d00faea.png)

Now, let's put one of those books in the cart:

![bildschirmfoto von 2016-12-15 17 44 09](https://cloud.githubusercontent.com/assets/1818737/21233054/19db0d6e-c2ee-11e6-8fe4-7ae3ec59046f.png)

Yeah, this works. 

Let's try 3 books (with a total weight of 3 kgs):

![bildschirmfoto von 2016-12-15 17 44 46](https://cloud.githubusercontent.com/assets/1818737/21233080/308b7e22-c2ee-11e6-9603-456ee3649a7b.png)

And this does not work! Why on earth 0,00 € ?? This should be 7.5 Euro, not Zero. 

Any ideas what's going wrong? I tried everything, googled for hours, emptied caches a thousand times, rebuilt indexes, did an update to V. 2.1.3, nothing. 

Of course, I triple checked all Shopping Cart rules:

![bildschirmfoto von 2016-12-15 17 49 53](https://cloud.githubusercontent.com/assets/1818737/21233297/f6092d2a-c2ee-11e6-9b11-2e09c8b557e2.png)

Also checked catalog price rules: 

![bildschirmfoto von 2016-12-15 17 49 48](https://cloud.githubusercontent.com/assets/1818737/21233288/ee23199a-c2ee-11e6-8e2e-bc9289653fd8.png)

and deactivated free shipping:

![bildschirmfoto von 2016-12-15 17 51 16](https://cloud.githubusercontent.com/assets/1818737/21233342/172ce35c-c2ef-11e6-95db-7379d14adb81.png)

and looked into /vendor/magento/module-offline-shipping/Model/Carrier/Tablerate.php ....

No Success at all! Magento keeps behaving weird. 

What I think I found out debugging Tablerate.php: 

- the line 

        $request->setPackageWeight($request->getFreeMethodWeight());

seems weird, since it temporarily sets the package weight to zero

- $request->getFreeShipping() is true when the qty exceeds a certain amount  (and I think the method should not return true!)

- value in  $rate['price'] seems to be wrong except for the first rate (up to 2 kgs)
 

So my question boils down to: are table rates in Magento 2.0 buggy and should I avoid them? If yes, what would be the alternative? And why are you telling nobody? 
Or is it just my fault? 

Any help on this issue would be greatly appreciated! 

- thomas

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by thomas-villagers** [comment]
damn! OK, there IS a catalog price rule intervening with my tablerate, see also

http://magento.stackexchange.com/questions/140070/magento-2-shipping-fee-using-table-rates-always-zero-when-adding-more-items-in

Sorry!

**Comment by thomas-villagers** [comment]
OK this explains error #1, which was my fault, sorry.

Still, with three or more books, each weighting 1 kg, I would expect a shipping cost of 7.5, but magento shows 5 Euro:

![bildschirmfoto von 2016-12-15 18 27 34](https://cloud.githubusercontent.com/assets/1818737/21234769/50c94a74-c2f4-11e6-8245-0131ec4aa579.png)

hm ...

**Comment by thomas-villagers** [comment]
Hi there,

I guess i solved it: first i reversed the order such that higher weights appear first in tablerates.csv, after that it was necessary to clean browser caches. Now, table rates seem to work.  :-)
I guess it helped talking about it. Thanks anyway!

**Comment by mbrinton01** [comment]
Glad you were able to solve the issue! Closing issue.
