### ISSUE TITLE
500 Internal Server Error when install in localhost

### ISSUE THREAD

**Issue by vigentocommerce** [magento/magento2#783]
Hey, I got 500 Internal Server Error when start install in localhost http://localhost/magento2-master/setup/ 
What happen, it is localhost in window so no permission wrong here. Please help.

Thank you in advanced!

**Comment by jaatr** [comment]
showing server error 500 in magento 1.9 on a live server please help

**Comment by mazhalai** [comment]
@jaatr please do not post on close issues, also this is only for Magento 2. Please post magento 1 issues in https://community.magento.com/

**Comment by jaatr** [comment]
in magento 2 banner slider not showing only showing please wait plz help

**Comment by davidalger** [comment]
@jaatr I would recommend you head over to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and/or assistance debugging an issue. If you have a bug report with steps to reproduce, then open a new issue with that and environment information, thanks!
