### ISSUE TITLE
TableRates shipping not working after upgrade 2.1.2 -> 2.1.3

### ISSUE THREAD

**Issue by abi2** [magento/magento2#7830]
TableRates was working great in 2.1.2, after upgrade it's not showing.

### Preconditions
- Single store Magento 2.1.2 website
- Update to Magento 2.1.3
- Simple Price vs Destination Settings
- tablerates csv 
[tablerates.csv.txt](https://github.com/magento/magento2/files/655274/tablerates.csv.txt)
- TableRates is enabled in Store View = Main Website and "Ship to Specific Countries" is set correctly

### Steps to reproduce
- Create TableRates
- Enable TableRates

### Expected result
Should show shipping method in checkout

### Actual result
TableRates shipping method not showing

**Comment by thomas-villagers** [comment]
I can confirm table rates do not work with either magento 2.1.1 or 2.1.3 (skipped 2.1.2, so i can't tell),  see my post #7829 just seconds before yours. :-) 

- thomas

**Comment by abi2** [comment]
Guess same issue as 
#7840

**Comment by phillipmeyer** [comment]
I think this relates to this issue too, seems like editing anything is broken.
https://github.com/magento/magento2/issues/7834

**Comment by veloraven** [comment]
@abi2 thank you for your report.
I'm closing this issue as a duplicate of #7840
