### ISSUE TITLE
Magento 2.1.3 can't be downloaded as .zip archive

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#7832]
If you try to download Magento 2.1.3 from https://magento.com/tech-resources/download, you will download 2.1.3 as a "file" type instead of a .zip folder type.
### Preconditions
Magento version is irrelevant. This affects anyone installing Magento 2.1.3 from the compressed archive

### Steps to reproduce
1. Go to https://magento.com/tech-resources/download
2. Download 2.1.3 as compressed .zip archive

### Expected result
1. 2.1.3 downloads as a .zip folder

### Actual result
1. 2.1.3 downloads as an unknown "file" type.

 I checked previous releases and they all download as .zip folders.

**Comment by Ctucker9233** [comment]
@magento-admin @magento-team Your download link for 2.1.3 doesn't download the correct file. Can this get a response please? It should be simple to fix.

**Comment by JohnSparks60** [comment]
We having the  same issue. We downloaded it extracted it and then re-zipped it with 7zip. to work around issues.  But had lost of installation issues.  We are not user if it's corrupted zip file or just lack of magento 2 upgrade know how.   It did creat issues with our theme and we have to recreate everything and go back to 2.1.2...  Good luck I hope this helps.

**Comment by elenleonova** [comment]
Hi All, 
do you have this issue on a version with sample data or without?

**Comment by Ctucker9233** [comment]
@elenleonova This occurred on the version without sample data for me. I didn't try converting it to a .zip because I thought it would corrupt the code.

**Comment by hostep** [comment]
@elenleonova: I think these guys are trying to say that the downloads for 2.1.3 and 2.0.11 have no file extension, see:
![screen shot 2016-12-16 at 19 59 50](https://cloud.githubusercontent.com/assets/85479/21274817/5e117270-c3ca-11e6-94d4-04d39d2617d4.png)
Notice that 2.1.2 does have a file extension.

**Comment by Ctucker9233** [comment]
@hostep that is correct.

**Comment by elenleonova** [comment]
Hi All, 
Thanks a lot for reporting this issue to us. There was a publication error that we have fixed just now. Please, go ahead and download zips. 
Highly appreciate your prompt feedback.

In case you still have any issues, please let us know.

**Comment by Ctucker9233** [comment]
@elenleonova the download works now. Thanks!
