### ISSUE TITLE
Upgrade Magento from 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#7833]
Hello guys,
I am having issue, if someone would help.
I am using this sequence to upgrade it form 2.1.2.
1- composer require magento/product-community-edition 2.1.3 --no-update
2- composer update
3- rm -rf var/di var/generation
4- php bin/magento cache:clean
5- php bin/magento cache:flush
6- php bin/magento setup:upgrade
7- php bin/magento setup:di:compile
8- php bin/magento indexer:reindex

But on step 6 it breaks. It throws an error while upgrading.
Here is an image to see what i am seeing.
![setup-upgrade](https://cloud.githubusercontent.com/assets/17259817/21238357/8b1e2cf0-c324-11e6-89c0-c3a8811ecff6.jpg)

Please help.

**Comment by Ctucker9233** [comment]
Try rm -rf var/di and then try php bin/magento setup:upgrade again.

**Comment by key-dev** [comment]
Its step 3 and the one i am having issue is step 6. I did that but no change.

**Comment by key-dev** [comment]
There are 2 errors i can see on image.

[Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

And

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

Please help

**Comment by Ctucker9233** [comment]
I'll do my best.

**Comment by veloraven** [comment]
@key-dev thank you for your submission.
Can you try to run upgrade without any 3-rd party extensions?

**Comment by key-dev** [comment]
Yep this worked.
I disabled 3rd-party extensions and setup:upgrade ran successfully.
Thank you veloraven

**Comment by deshibazaar24** [comment]
When I  Want to upgrade magento 2.1.2 to 2.1.3 or 2.1.4 The following issues has been seen:
1. Composer has benn updated successfully.
2.  rm -rf var/di var/generation   or  rm -rf var/di  -seen okay
3. php bin/magento cache:flush  - error hown as bellow:

  [Magento\Framework\Exception\NoSuchEntityException]
  Requested store is not found

cache:flush [--bootstrap="..."] [types1] ... [typesN]

Note: after disable 3rd-party extensions & run setup upgrade  ---showing same error.

Kindly help to resolve it.
Thanks
Deshibazaar24

**Comment by SyedMuneebb** [comment]
In the step 6 try this` rm -rf var/di/* var/generation/* var/cache/* var/log/* var/page_cache/*` 

Check this simple and step by step guide: [Update Magento 2](https://magenticians.com/update-magento-2-using-composer/).
