### ISSUE TITLE
configurable products when renamed drop from frontend

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#7836]
### Preconditions

1. magento 2.2.0-dev 
2. centos 6.5

### Steps to reproduce

1. make a configurable product
2. add 10+ simple configurations in it
3. save
4. go back to product
5. rename the product

### Expected result

1. all configurable options should still remain in the configurable products

### Actual result

1. configurable product stops showing up in frontend

**Comment by RomanKrut** [comment]
@dmcmillin I can`t reproduce this issue as you described it. Can you check if issue is still on the latest version Magento 2 ?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
