### ISSUE TITLE
setup:db-data:upgrade breaks on upgrade from 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#7837]
Hello Guys,
I am upgrading Magento 2.1.2 to 2.1.3
It requires setup:upgrade.
It runs but breaks.
Now what i analyse that schema is updated but data install/update throws error on magento customer moduel. Please have a look on image below.

![setup-upgrade](https://cloud.githubusercontent.com/assets/17259817/21242559/c0976d6c-c336-11e6-8eb9-d1e01f024cb0.jpg)

I can not see my website it says there has been error processing your request along with an error number. If i see the error it says:

`a:4:{i:0;s:644:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Customer data: current version - 2.0.7, required version - 2.0.9
Magento_Catalog data: current version - 2.0.7, required version - 2.1.3
Magento_Quote data: current version - 2.0.2, required version - 2.0.3
Magento_Msrp data: current version - 2.0.0, required version - 2.1.3
Magento_CatalogInventory data: current version - 2.0.0, required version - 2.0.1
Magento_Vault data: current version - 2.0.0, required version - 2.0.2
Magento_SalesInventory data: current version - none, required version - 1.0.0";i:1;s:2711:"#0 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#2 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#5 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /home/pullabul/public_html/beta.pullabulla.com/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /home/pullabul/public_html/beta.pullabulla.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /home/pullabul/public_html/beta.pullabulla.com/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}`

I am not able to get updated those modules. Everytime i run setup:upgrade command it breaks as in above image.
Any help guys?

**Comment by ghost** [comment]
I have the same issue... Ran an update to 2.1.3 from the wizard, which failed at the point where it tried to regenerate the static content, with a rollback failing. Now I see a similar error to that above, but when I run setup:upgrade from the command line it doesn't resolve the issue... :(

**Comment by rudik99** [comment]
Try running the update without any 3rd party modules installed - I discovered a 3rd party module which caused that error on database upgrade. Then after upgrade re-install 1 by 1 and you should find the one causing the issues.

**Comment by ghost** [comment]
Yup - that was it! An addon extension for a Cart to Cart tool I had installed. Disable that and the rest works as it should :)

**Comment by veloraven** [comment]
Closed as a duplicate of #7833
