### ISSUE TITLE
Magento 2.1.2 Configurable product "XXX" does not have sub-products

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#7838]
### Preconditions

Magento 2.1.2
1. 
2. 

### Steps to reproduce

1. Open the product "XXX"
2. 
3. 

### Expected result

1. Product page showing.

### Actual result

1. Logs
1 exception(s):
Product page stops showing.
Exception #0 (Magento\Framework\Exception\LocalizedException): Configurable product "XXX" does not have sub-products

**Comment by veloraven** [comment]
@Tonop thank you for your feedback.
Please provide more information about your product settings and detailed steps how you created it.
Please also let us know if you use any localization or external extensions.

**Comment by quienti** [comment]
Duplicate https://github.com/magento/magento2/issues/5762 and https://github.com/magento/magento2/issues/6422

Fixed in develop branch with commot : https://github.com/magento/magento2/commit/1e78fe2e37af0012b7f60b29c658221b8ab8467b

**Comment by staffrob** [comment]
> Fixed in develop branch with commot : 1e78fe2

This commit removes the exception and introduces new issue. Now the price displays as $0.00 until user selects a configurable product attribute

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate.
@quienti thank you for pointing at it.
@staffrob could you please add the same comment about commit to your issue #7908?
