### ISSUE TITLE
Magento 2.1.2 FinalPriceBox does not exist

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#7839]
### Preconditions

1. Magento 2.1.2
2. 

### Steps to reproduce

1. Open product page.
2. 
3. 

### Expected result

1. Product page showing.

### Actual result

Produvt page stops showing.
1. logs
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox
Exception #1 (ReflectionException): Class Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox does not exist

**Comment by veloraven** [comment]
@Tonop thank you for your feedback.
Please provide more information about your product settings and detailed steps how you created it.
Please also let us know if you use any localization or external extensions.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
