### ISSUE TITLE
Magento 2.1.3 Custom theme can not be applied

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#7841]
### Preconditions

1. Magento 2.1.3
2. 

### Steps to reproduce

1. Design Configuration
2. Apply Custom Theme to store view.
3. 

### Expected result

1. Custom theme applied to store view

### Actual result

1. Default store view theme applied

**Comment by borisvankatwijk** [comment]
We are having the same problem with one of our shops upgraded to 2.1.3.

Initially the database was correctly configured, but as we tried to resave the storeview design theme, it changed the value to the default scope value.

**Comment by Ctucker9233** [comment]
Same here.

**Comment by Ctucker9233** [comment]
Editing the store view under content=>configuration makes no difference. It'll tell you it saved the configuration but then it still shows the theme as being default. Part of my problem was that the home page for each store view had somehow become unset. Very uncool @magento-team. Might I suggest pulling 2.1.3 until this problem is fixed? It clearly isn't ready.

**Comment by cadoworld** [comment]
Same Here.

**Comment by cadoworld** [comment]
I managed to change the theme if you change the setting as single shop.

Store > Configuration > General > General > Single-Store Mode > YES

content > Configuration > Edit
Default theme > Smartwave Porto

**Comment by Ctucker9233** [comment]
@cadoworld Does that work if you have more than one store?

**Comment by Ctucker9233** [comment]
I reverted to 2.1.2. Thank goodness that worked!

**Comment by Ctucker9233** [comment]
For version 2.1.3, when you run php bin/magento setup:static-content:deploy, it looks like there is some sort of theme minification script that runs. I wonder if this is what is messing up our custom themes. I'll dig around a little bit.

**Comment by Ctucker9233** [comment]
@magento-team What files get called when php bin/magento setup:static-content:deploy gets run? I think I can figure this out if I know where to look. Otherwise, it's a needle in a haystack.

**Comment by mtuinstra** [comment]
@Ctucker9233 
Module: module-deploy
Class: DeployStaticContentCommand
Path: vendor/magento/module-deploy/console/command/DeployStaticContentCommand.php

Maybe you can catch your result from there ;)

**Comment by pascaladriaansen** [comment]
To me it looks like this issue might also be related to #7815 and #7840. Seems like there is an issue with configuration scope and inheritance at multiple places in the config, [see this comment](https://github.com/magento/magento2/issues/7840#issuecomment-267538266).

**Comment by mtuinstra** [comment]
I've got it to work by doing the following steps:
- Delete rows in db with path 'design/theme/theme_id' from table 'core_config_data'
- Run bin/magento indexer:reindex

When you refresh the design page you should see no-theme set for all the stores.
Now just start resaving/setting your themes on Store View Level, for us the Store Level was giving problems.

Make sure to clear cache if its on ;)!

Let me know if this also works for you guys!

**Comment by lennartbee** [comment]
@mtuinstra this worked for us but the logo's configured in the CMS did not appear. We had to manually add them as described on http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html#logo_declare

**Comment by Tjitse-E** [comment]
Same issue here. We've reverted to Magento 2.1.2, this solved the problem.

**Comment by lennartbee** [comment]
Earlier I wrote that removing the rows from core_config_data worked. It is however not working flawlessly anymore, we have to manually add the config rows to core_config_data after edits.

**Comment by Ctucker9233** [comment]
I'm still digging to see if I can find the problem. Stay tuned guys.

**Comment by yumicom** [comment]
Same problem - Custom theme can not be applied

**Comment by sevos1984** [comment]
@Tonop I don't have this problem in 2.1.3. I have set two storeviews within main website, then set blank theme to second storeview and all works fine. Could you post your stores configuration here?

**Comment by grischunya** [comment]
Perhaps you are using a custom theme to the type of virtual? Try to change the physical and update the cache. It helped me

**Comment by alexpoletaev** [comment]
Guys, you will find a temporary workaround here https://github.com/magento/magento2/issues/7840#issuecomment-268313989 . It will fix the configuration retrieval from the website scope.

**Comment by BvdVen** [comment]
In my situation the theme was already set before upgrading to 2.1.3 after the upgrade all settings in the Design Configuration aren't used and just shows default logo's, mail header, footer etc.

**Comment by yumicom** [comment]
It works in Magento 2.1.4

**Comment by Ctucker9233** [comment]
2.1.4 indeed fixed this issue.

**Comment by maksek** [comment]
As confirmed by  @Ctucker9233 and @yumicom  issue is fixed, is still have the issue, feel free to comment.
