### ISSUE TITLE
Invalid response creating Track with API

### ISSUE THREAD

**Issue by reijervano** [magento/magento2#7842]
When creating a track via the API the response message is incorrect.

### Preconditions
1. Magento 2.1.2

### Steps to reproduce
1. Create order in Magento
2. Add shipment via API
3. Add incorrect track (missing number) to shipment via API

### Expected result
1. Response as described on [Magento REST API documentation](http://devdocs.magento.com/swagger/#!/salesShipmentTrackRepositoryV1)
```
{
  "message": "string",
  "errors": [
    {
      "message": "string",
      "parameters": [
        {
          "resources": "string",
          "fieldName": "string",
          "fieldValue": "string"
        }
      ]
    }
  ],
  "code": 0,
  "parameters": [
    {
      "resources": "string",
      "fieldName": "string",
      "fieldValue": "string"
    }
  ],
  "trace": "string"
}
```

### Actual result
1. 
```
{"message":"Cannot save track:\n%1","parameters":["Number can not be empty"]}
```

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue MAGETWO-62526 was created

**Comment by magento-engcom-team** [comment]
@reijervano, thank you for your report.
We've created internal ticket(s) MAGETWO-73621 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @reijervano

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@reijervano thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
