### ISSUE TITLE
Customer with unique attribute can't be saved

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#7844]
### Preconditions

1. Magento 2.1.3 (Did not test if it is also bugged in earlier versions)
2. PHP7

### Steps to reproduce
1. Add an extra customer attribute, that should be unique. In my case an ERP id. Attribute is correctly added to the form and attribute set and is saving correctly.
2. Set a value for this attribute for a customer and save it.
3. After the value is saved and you will try to save that same customer again you get an error the value should be unique.

### Expected result
1. The customer should be saved cause the value is unique.

### Actual result
1. Error message in admin: 'The value of attribute "Attribute label" must be unique'

### Comment
1. I did some digging in the actual code and the problem seems to be that in the function "checkAttributeUniqueValue" in class "Magento\Eav\Model\Entity\AbstractEntity" in the end it is trying to get the object ID and compare it to the value for which a match was found. However the object->getId always returns null because it is not set.
The reason it is not set I can trace back to "Magento\Customer\Controller\Adminhtml\Index\Validate" where in the "_validateCustomer" function the customer object passed to the validate function already is missing an ID.

**Comment by veloraven** [comment]
@bartlubbersen thank you for your feedback.
Customer custom attributes are available in Enterprise edition only.
If you use this one, please contact Magento support instead of posting your issue here. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
If you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE amd we can not treat it as an issue.

**Comment by bartlubbersen** [comment]
@veloraven we are not using Enterprise functionality but we are not adding the attributes through the back-end either. We are just adding attributes through setup scripts which should work also for community. Otherwise no thirth party extension could ever create a customer attribute. So I think this issue should be reopened. If you agree adding attributes via setup should work please also reopen ticket #7845 because it is about almost the same thing but not about customer, but about customer address.

**Comment by ericrisler** [comment]
@bartlubbersen 
The \Magento\Customer\Controller\Adminhtml\Index\Validate::_validateCustomer() method uses the \Magento\Customer\Model\Metadata\Form::extractData() method to pull out the submitted form data in the admin. This method returns a data array of attribute_code=>values but excludes the 'entity_id' value. Later in the validation call stack, this causes the validation to fail. Set a breakpoint in \Magento\Eav\Model\Entity\AbstractEntity::checkAttributeUniqueValue() to watch. Or just look at the line that looks for an id: `if ($object->getId())`...if the data had contained the entity_id then we would pass validation.

We overrode the \Magento\Customer\Controller\Adminhtml\Index\Validate::_validateCustomer() method and added the entity_id:

```
$this->dataObjectHelper->populateWithArray(
    $customer,
    $data,
    '\Magento\Customer\Api\Data\CustomerInterface'
);

// fix:
$submittedData = $this->getRequest()->getParam('customer');
$entity_id = $submittedData['entity_id'];
$customer->setId($entity_id);

$errors = $this->customerAccountManagement->validate($customer)->getMessages();
```

**Comment by Esraa-AlArmouti** [comment]
I had "The value of Admin must be unique." message whenever I want to save the attribute.
eventually magento 2.1.3 doesn't save the attribute if one of its options under "Manage Options (Values of Your Attribute)" is not a unique value for admin field, so basically admin fields should be unique and make sure if it has capital letters or ever special characters. I've made a collection of small letters and number for each admin field and it has been saved successfully.
p.s.: check if Advanced Attribute Properties > Unique Value is No. if not make it as No.
I hope this solution help somebody.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69373
