### ISSUE TITLE
M2.1.x : Require Customer To Be Logged In To Checkout

### ISSUE THREAD

**Issue by quienti** [magento/magento2#7848]
### Preconditions
1. Magento 2.1.x
2. 

### Steps to reproduce
1. See this commit : https://github.com/magento/magento2/commit/33b4d4f5179d773bbc8c8cc280f67766ebd7e20c

### Expected result
1. The old code need to be removed

### Actual result
1. The code still exist
See:
https://github.com/magento/magento2/blob/67c29c6daecfcc484f11db4c0667a3dab9dbf719/app/code/Magento/Checkout/Helper/Data.php#L23

https://github.com/magento/magento2/blob/67c29c6daecfcc484f11db4c0667a3dab9dbf719/app/code/Magento/Checkout/Helper/Data.php#L391-L403

https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Controller/Onepage.php#L264-L280

https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/DefaultConfigProvider.php#L520-L529

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.
We've created internal ticket(s) MAGETWO-81764 to track progress on the issue.

**Comment by RomaKis** [comment]
@quienti, hi, this code can't be deleted as it will be [backward incompatible changes.](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html). Only "deprecated" tag can be added.
Working on this.
