### ISSUE TITLE
M2.x.x Translation Missing in Checkout for Tax

### ISSUE THREAD

**Issue by quienti** [magento/magento2#7849]
### Preconditions
1. Magento 2.0.x, 2.1.x and 2.2.0-develop

### Step to reproduce
1. Add product to cart
2. Proccess to checkout
3. See image
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/21307271/0ec97a70-c5d5-11e6-8463-9a46604927ac.jpg)

### Expected result
1. Text is translated

### Actual result
1. Not translate

See:

https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/view/frontend/web/js/view/checkout/summary/tax.js#L25

**Comment by veloraven** [comment]
@quienti thank you for your feedback.
Please add steps to reproduce to your description.

**Comment by quienti** [comment]
@veloraven Updated

**Comment by Sergeacc** [comment]
Internal ticket MAGETWO-70071 was created.

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.
We've created internal ticket(s) MAGETWO-82351 to track progress on the issue.

**Comment by RomaKis** [comment]
Working on this.

**Comment by okorshenko** [comment]
Hi @quienti. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1147 by @RomaKis in 2.2-develop branch
Related commit(s):
 - 4d02b99c9912e498847e3658eabee1dd035a7b56

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @quienti. Thank you for your report. 
The issue has been fixed in magento/magento2#19174 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [0566957554fa964f79518b7b93920fe12db39c8a](https://github.com/magento/magento2/commit/0566957554fa964f79518b7b93920fe12db39c8a)

The fix will be available with the upcoming 2.3.1 release.
