### ISSUE TITLE
CLI installation failures should provide more details

### ISSUE THREAD

**Issue by rgranadino** [magento/magento2#785]
I ran into some issue trying to run the installer via CLI. The error message is not helpful at all due to so many options being required: `Reason for failure: Invalid arguments or no arguments provided` 

It would be much better if the list of require and invalid options were listed in the output. I was only able to get the installer to work after finding this issue https://github.com/magento/magento2/issues/779 and looking at @alankent's docker setup script.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32222

**Comment by buskamuza** [comment]
Hi @rgranadino , this issue is already fixed. Please, let us know, if there are any concerns with the current implementation.
