### ISSUE TITLE
Magento 2.1 oauth_consumer_key not present in login request

### ISSUE THREAD

**Issue by fanta** [magento/magento2#7850]
When Magento pops-up a window to redirect Merchant to third party login page, Magento is not sending `oauth_consumer_key`.

Steps:

1. Add new integration.
2. Click Activate.

I do get `oauth_consumer_key` and `oauth_consumer_secret` in the **callback** call, plus some more parameters.

But the `oauth_consumer_key` is missing in the request to login page making impossible to link the logged in user to the right Consumer Key.

The parameters I'm getting are these:

"consumer_id" => "2",
"success_call_back" =>
`http://localhost:4000/admin/admin/integration/loginSuccessCallback/key/9f8c0014bddaf4943d78eec1df3f307b373c6928cffa663f0df5f1d7a1deda02/`

Looks like I'm getting something else(consumer_id) instead of the `oatuh_consumer_key`.

I don't know if the same applies for other Magento versions.

**Comment by fanta** [comment]
Can someone close this please ?, I'm using `2.0.5` and not `2.1` as states in the title. Sorry for the inconveniences.

**Comment by elenleonova** [comment]
@fanta  - closing per your request:)
