### ISSUE TITLE
Remove dependency of Customer module on Review module

### ISSUE THREAD

**Issue by MidnightDesign** [magento/magento2#7852]
### Preconditions 
1. Magento 2.3.2 Community

### Steps to reproduce (*)
1. Run `bin/mage module:disable Magento_Review` in a standard Magento installation

### Actual result (*)
1. The module can't be disabled because `Magento_Customer` depends on it.

### Expected result (*)
The module `Magento_Review` is disabled.

Is it really necessary that the `Customer` module depends on the `Review` module? It's the only reason why I can't disable the `Review` module and a quick search for "Magento\Review" in the Customer module's codebase reveals that only a single file references a class in `Review`: `\Magento\Customer\Block\Adminhtml\Edit\Tab\Reviews`. I'm sure this can be refactored to remove the dependency, right?

**Comment by veloraven** [comment]
@MidnightDesign thank you for your feedback.
The GitHub issue tracker is intended for technical issues only.
If you think this to be an issue please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
However it looks like more as an improvement and  Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
However if you just want to ask a question and get some discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by MidnightDesign** [comment]
I do think this is an issue, and a technical one at that. But I will gladly post this as a feature request if you think GitHub is the wrong place for this.

**Comment by veloraven** [comment]
@MidnightDesign this issue can be left here but please format the description according to template (see the link above). It should look like this:

**Steps:**
1.
2.
...
**Actual Result:**
...
**Expected Result:**
...

It is easier to understand what it is about when description is structured

**Comment by MidnightDesign** [comment]
@veloraven I've updated my original post.

**Comment by mswaidan** [comment]
I'm also experiencing this issue.

**Comment by Sergeacc** [comment]
Certain modules have dependencies on other modules, in which case you might not be able to enable or disable a module because it has dependencies on other modules.
Read Magento devdocs - http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html#instgde-cli-subcommands-enable-modules

**Comment by MidnightDesign** [comment]
@Sergeacc Did you even read my post? It's a proposal to _remove_ the dependency because it's not really necessary.

**Comment by Sergeacc** [comment]
Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by MidnightDesign** [comment]
I created a feature request here:
https://community.magento.com/t5/Magento-2-Feature-Requests-and/Remove-dependency-of-Customer-module-on-Review-module/idi-p/69271

**Comment by joshuaadickerson** [comment]
This is incredibly simple to fix. Just move that block to Magento_Review with the code and config. That should be all that's necessary.

This is *not* a feature request. This is poor design of the module. Not being able to disable a high-level feature is a bug.

**Comment by joshuaadickerson** [comment]
This is preventing me from disabling the Review module. The Review module adds HTML to the extension attributes element of the `product_data_storage` localStorage item. That is filling up localStorage for browsers and causing other issues. So, I’d like to just disable the module altogether since we don’t use reviews.

**Comment by hostep** [comment]
Request makes sense, let's re-open this.

There is also a mentioning of MAGETWO-71228 in the forum thread, so maybe somebody with access to Magento's Jira can leave an update here to tell us what the status is...

**Comment by joshuaadickerson** [comment]
It is reproducible in 2.2 and 2.3. The other component it affects is the Review component.

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by sdzhepa** [comment]
Hello @joshuaadickerson @hostep 

Thank you for raising this issue again!

I have investigated this issue and all related tickets in the internal Jira.
Unfortunately `MAGETWO-71228` this ticket still in Open stage.
I discussed it with Product Managers and Architects related to these modules and everyone agreed that it should be fixed.

By fact, it is backward incompatible changes but based on multiple feedbacks and complaints such changes have a very big chance to be approved to be delivered even in case it will be PR proposed from the community(at least we have "pre-approval", the final decision will be made based on proposed code-changes)

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18314` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by joshuaadickerson** [comment]
How is this backwards incompatible? It removes the Review dependency for Customer. Removing dependencies should not be backwarda incompatible. Then Review is already dependent on Customer. Adding dependencies should be a BC change but this already exists. This could be done in a patch. Considering everyone using Magento is using the Customer module and thus must be using the Review module, nobody has it disabled. This should be non-breaking.

Hmm.... unless someone is targeting that block with it being in customer? Ah, that would be breaking.

**Comment by ayangolenko** [comment]
@magento I am working on it

**Comment by drpayyne** [comment]
Closing issue since fix has already been submitted: https://github.com/magento/magento2/commit/91a4ba542cdfb99da5501468126744d23841d26d.

CC: @krzksz
