### ISSUE TITLE
Transactional email logo wrong location

### ISSUE THREAD

**Issue by perfpcs** [magento/magento2#7853]
This has been broke since 2.0 and still not fixed even in 2.1.3

Content/Configuration/Transactionall Email/Logo Image

It uploads the file but in the wrong place.

Should be:
/pub/media/logo/stores/1/email.gif

In Admin it looks for it in this folder which does not exist and so is broken image link:
/pub/media/email/logo/stores/1/email.gif

Please fix

**Comment by hostep** [comment]
Please search for existing issues before creating a new one, this has been reported multiple times.
See this issue: https://github.com/magento/magento2/issues/5352

Please close and hope the fix will be included in 2.1.4 :)

**Comment by veloraven** [comment]
Closed as duplicate

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
