### ISSUE TITLE
Transactional emails sent from Sales->Orders do not use the email of the right scope (Website/Store/Store_View) in MAGE 2 Multistore

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#7858]
hi folks,

in Magento 2.1.2 **Multistore**, when accessing Sales->Orders and (after selecting a particular order) sending an email (i.e. when you click on "Ship") the email sent to the customer (the Transactional email) is NOT **FROM** the Store_View's email but FROM the Default_Config's email (in a multistore different Websites/Sore_Views correspond to different stores hence the mails received from the customer are from a different shop than expected).

### Preconditions
Magento 2.1.2
Software version: 5.6.28-76.1 - Percona Server (GPL), Release 76.1, Revision 5759e76
Database client version: libmysql - 5.5.45-37.4

### Steps to reproduce (an example)
Let's say we've got 3 Websites:  the Store_Views ozforest.com (Default_Config), giustoacquisto.com ansd cartonito.net 
1.  Place an order in the Store_view giustoacquisto.com
2.  Customer receives the right "Order-confirmation" Transactional email (all the transactional emails are set with variables. Furthermore we've checked Store->Configuration->General->Store_Email_Addresses and the different Websites, Stores and Views have got indeed different Sender-Name and emails)
3.  **IMPORTANT**: At the moment of the shipment of the goods the Store Manager access Sales->Orders, select the order just placed in giustoacquisto.com and click on "Ship": so Magento sends the "Shipment Email". Every Website/Store/Store_view has got different emails that are simply info@domainname so the customer should receive an email from info@giustoacquisto.com
4.  The customer receives instead (INCORRECTLY!) an email from info@ozforest.com (the "Default_Config" email) instead from info@giustoacquisto.com (the Website/Store/Store_View where the order was placed).

We see that the system emails that Magento sends automatically are from the right Website/Sore/Store_view.
The emails that the store manager sends from Magento Sales->Orders are always sent using as sender the Default_Config email

IMPORTANT:
_That's probably due to the impossibility to choose a Website or Store or Store_View when accessing Sales->Orders_
HENCE WHEN IN Sales->Orders the SCOPE remains always the Default_Config (and never the various Websites or Stores or Store_Views)

looks like a bug..

thanks,
romeo

**Comment by olysenko** [comment]
Hi, thank you for report. This issue duplicates [6954](https://github.com/magento/magento2/issues/6954). Closed as a duplicate
