### ISSUE TITLE
Invalid comment for the method __order in Magento\Sales\Model\Order\Payment.php

### ISSUE THREAD

**Issue by denchev** [magento/magento2#7860]
### Preconditions
Does not apply

### Steps to reproduce

1. Open Magento\Sales\Model\Order\Payment.php (Line 1040)
2. Locate method _order
3. Look at the comment

### Expected result

1. Expect to see a proper comment what this method does

### Actual result

1. The comment seems to be cut off "* Order payment either online" and does not continue with the rest of the sentence
2. I think it is just a copy/paste from the authorize method while these two methods (may) differ in functionality.

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue  MAGETWO-62509 was created

**Comment by ishakhsuvarov** [comment]
@denchev The issue has now been fixed with the PR #8769 
Thank you for reporting
