### ISSUE TITLE
Can't change the product description in the admin panel after importing.

### ISSUE THREAD

**Issue by Flamestyle** [magento/magento2#7863]
### Preconditions

1. Magento CE 2.1.3
2. Ubuntu 16.04, NGINX 1.10, PHP 7, MySQL 5.7.

### Steps to reproduce

1. Install Magento CE 2.1.3 using composer
2. Import products.
3. Command line ./magento cron:run
4. Refresh cache.
5. Try change product's description in admin panel.
6. Refresh cache.

### Expected result

I can change description or short description in admin panel and see changes on fronted.

### Actual result

I'm trying to change the text in the description or delete it. But it still remains the same on fronted. Flush and refresh cache don't help. I can change description only import again.

**Comment by zchking** [comment]
Be careful the store view, import products is in scope default store view, and you change it on all site view, so it can't change the default views product description.  You can change the view to default store view when edit on edit product page.
