### ISSUE TITLE
Magento CE 2.1.3 Very slow and have a lag 3-5 seconds to open page. And more then 10 seconds on cart page

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#7865]
After upgrade to 2.1.3 there are some bugs. I just want to report a delay to open page about 3-5 seconds to open and load every page to open.

### Preconditions
1. Browser Mozilla, Edge, Google Chrome.
2. Magento CE 2.1.3

### Steps to reproduce
1. Open homepage 
2. Open product page
3. Open Categories
4. Even on Admin page / backend

### Expected result
1. All page including admin page and all on frontpage, basically loading normally. About 1-3 seconds and browser successfully open the page. Fast. and happy.

### Actual result
1. Admin page, homepage, product pagade, categories page : ====> load 1 second. Stop. Delay 1-2 second. And the 3-5 seconds load its page. Total ===> 5-7 seconds until appear.
2. On cart page and Checkout page ===> More then 10 seconds to appear. 
3. Estimated shipping & Tax on cart page ===> more then 20 seconds to load.

**Comment by kandy** [comment]
Can you verify that all caches are enabled?

**Comment by jurpro** [comment]
hi @kandy Sorry. I disable cache. After enable, the delay is dissappear. Only on cart page, but it look the same with 2.1.2

Thanks for your help

**Comment by jurpro** [comment]
hi @kandy and @shiftedreality sorry for comment again here. But it happend again now. I did cache enable, flush etc. ANd reindex too. But still happened about delay. and the same like I told before.

How to fix?
