### ISSUE TITLE
SessionHandler::read(): open(tcp://10.20.30.40:6379/sess_xxx) failed: No such file or directory (2)

### ISSUE THREAD

**Issue by magenx** [magento/magento2#7868]
### Preconditions
1.  magento 2.1.3
2.  redis 3.2.6
3.  php 7.0.14

### Steps to reproduce
1.  configure redis sessions in php.ini and env.php
2.  start installation.
3.  remove redis settings, then install magento, put back redis settings then can not login to magento admin.

### Expected result
1.  sessions must be stored in redis

### Actual result
1. get error something like this:
SessionHandler::read(): open(tcp://10.20.30.40:6379/sess_xxx) failed: No such file or directory (2)

**Comment by BrocksiNet** [comment]
I had the same problem because redis was set only for backend. But after adding redis also for session in config (see below) then it was working.

```
'session' => 
            array (
            'save' => 'redis',
            'redis' => 
                array (
                    'host' => '127.0.0.1',
                    'port' => '6379',
                    'password' => '',
                    'timeout' => '2.5',
                    'persistent_identifier' => '',
                    'database' => '0',
                    'compression_threshold' => '2048',
                    'compression_library' => 'gzip',
                    'log_level' => '1',
                    'max_concurrency' => '6',
                    'break_after_frontend' => '5',
                    'break_after_adminhtml' => '30',
                    'first_lifetime' => '600',
                    'bot_first_lifetime' => '60',
                    'bot_lifetime' => '7200',
                    'disable_locking' => '0',
                    'min_lifetime' => '60',
                    'max_lifetime' => '2592000'
                )
            ),
```

**Comment by magenx** [comment]
you dont understand, we have redis settings in php.ini and env.php, magento failed to work.
but other applications are ok.

**Comment by magento-engcom-team** [comment]
Hi @magenx 
Could you please let us know if the issue is still actual? Thank you

**Comment by magenx** [comment]
Magento 2.2.1
error is gone. looks like working.

**Comment by magento-engcom-team** [comment]
@magenx Thanks for the feedback.
