### ISSUE TITLE
magento store switcher does not showing after creating store with new  root category

### ISSUE THREAD

**Issue by sanjay003** [magento/magento2#7871]
I am facing problem to creating store view with magento 2.
Problem is that  , when I create a store with different root category and different  website name .
Then my front end store switcher disable. please help me regarding this.

**Comment by veloraven** [comment]
@sanjay003 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
In case you want to report an issue please create new GitHub issue and format it  according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result, expected result and version of Magento you are running specified.
