### ISSUE TITLE
Phantom entries in Design Configuration after deleting site

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#7872]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Create a new Website, Store, and Store View
2. Delete what you created in step 1; choose to make DB backup
3. Go to /theme/design_config/ in Admion

### Expected result

1. The site/store should not be listed.

### Actual result

1. Although the site & store are not listed, I now see two phantom rows:

![image](https://cloud.githubusercontent.com/assets/4110567/21307436/758dcc12-c610-11e6-8db7-c0746cd2d665.png)

I know this is pointing to the same site that I deleted because when I hover over the Edit link I can see that it's the same ID. However, when I click on the Edit link I see this error:

![image](https://cloud.githubusercontent.com/assets/4110567/21307510/bec9ca02-c610-11e6-9c69-4744003ed809.png)

**Comment by AlexWorking** [comment]
Hello @thdoan. We can't reproduce this bug on develop version which for Your case is 2.1.7. In fact the issue can be reproduced exactly as You described while after step 2, the re-indexation and the cache flush (which are required by the system) are not done. Please confirm if You still can reproduce this bug on the actual magento version (2.1.7). Thank's for applying.

**Comment by thdoan** [comment]
@AlexWorking I'm no longer on the M2 project, so sorry I cannot answer your question.
