### ISSUE TITLE
Unable to remove http-cache-hosts configuration from magento setup:config:set

### ISSUE THREAD

**Issue by devonto** [magento/magento2#7873]
I'm attempting to remove the integration of Varnish which required the following command to be run to handle cache clearing
`magento setup:config:set --http-cache-hosts=127.0.0.1:1234`
Now that we have decided not to use Varnish, I wish to remove this link.

### Preconditions
1.  Magento 2.1.1
2.  Varnish cache cache-clearing integration already applied

### Steps to reproduce
1. Run `magento setup:config:set --http-cache-hosts=""` or `magento setup:config:set --http-cache-hosts=`

### Expected result
1. Previously assigned cache hosts should be removed

### Actual result
1. Error is produced `The "--http-cache-hosts" option requires a value.`

**Comment by swieczorek** [comment]
you can remove the http-cache-hosts from app/etc/env.php

**Comment by devonto** [comment]
Thanks.

Should the entire parameter be removed, or should it be an empty array?

Is that all the `setup:config:set` command did? Or is there something more to it?

**Comment by magento-engcom-team** [comment]
@devonto, thank you for your report.
We've created internal ticket(s) MAGETWO-83530 to track progress on the issue.

**Comment by Hajo-Magre** [comment]
@devonto and others coming accross this issue. The end of the env.php file looks like this when there are no cache hosts defined, using Magento 2.2.3:

```
array (
          'debug_logging' => '0',
        ),
      ),
    ),
  ),
);
```

I ran accross the same problem, but was able to recover the previous settings in env.php by examining a backup copy.

**Comment by magento-engcom-team** [comment]
Hi @devonto

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@devonto thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
