### ISSUE TITLE
Product quantity not saved when EAV cache enabled

### ISSUE THREAD

**Issue by mike-happy** [magento/magento2#7876]
When I'm trying to change the quantity of a product in the admin, it will not be stored in the database. This problem only occurs when the EAV cache is enabled.

### Preconditions
1. Magento 2.1.2
2. PHP7

### Steps to reproduce
1. Create a simple product
2. Enable the EAV cache
3. Update the quantity of the simple product
4. Save the product

### Expected result
1. The quantity of the product should change in de database 
2. The product page in the admin should show the new quantity

### Actual result
1. The quantity of the product isn't updated in the database
2. The product page in the admin shows the old quantity
3. The POST request that has been done after saving the product shows 2 quantity values, 1500 is the old one and 1700 should be the new one.
`Content-Disposition: form-data; name="product[quantity_and_stock_status][qty]"`
`1700`
`Content-Disposition: form-data; name="product[stock_data][qty]"`
`1500`

**Comment by vishveskrish** [comment]
Hey @mike-happy , 

Have you get any solution ?

We are facing same issue after upgrading store to Magento 2.1.3.

**Comment by mike-happy** [comment]
Hi @vishveskrish ,

No, I didn't find a solution yet. The quantity can only be updated when the EAV cache is disabled.

**Comment by real34** [comment]
We also have detected this issue with some custom attributes added to the attribute set recently. However the same attribute in another attribute set can be saved with the EAV cache enabled.

**Comment by santhoshnsscoe** [comment]
We are using 2.1.6 and still this bug is present. Please rectify this bug.

**Comment by santhoshnsscoe** [comment]
The problem is inside `Magento\Eav\Model\Entity\Attribute\Set::addSetInfo`  
  
In admin product edit page, when the attribute set of the related/cross-sell/up-sell products are different from the main product. Then the function `Magento\Catalog\Model\ResourceModel\AbstractResource::_isApplicableAttribute` will return false due to `$attribute->isInSet($object->getAttributeSetId())`

**Comment by danipolo** [comment]
Same problem here... in 2.1.6

**Comment by vherasymenko** [comment]
Hi all!
I try to reproduce your bug. That is steps which i use.

1. Install Magento latest develop version (2.1.6)
2. Go to Admin side and create simple product
3. Run command php bin/magento cache:enable eav
4. Then i open created product and change qty.
5. Check qty after changing

AR: Quantity is updated successfully.

Note: I also try add related/upsells/cross-sell/ products which have different attributes set, and in all cases I have positive result.

Could you correct me maybe i use wrong steps.

**Comment by santhoshnsscoe** [comment]
is all your related/upsells/cross-sell/ products are of different attribute set. Check with only different attribute set.
If last one is of same attribute set, then it will work positively.

**Comment by vherasymenko** [comment]
@santhoshnsscoe Hi. Could you please write step by step how i can reproduce this bug for creating internal issue ticket.

**Comment by santhoshnsscoe** [comment]
Steps to reproduce

1. Create a new attribute set "Test" from default attribute set
2. Create a configurable product of attribute set default
3. Create a simple product of attribute set Test and add the configurable product as related product.
4. Now change the quantity or stock status of the simple product.
5. Both the values don't get updated.

This bug comes only if related product is configurable. ``addSetInfo`` is called only if the product is configurable.

**Comment by vherasymenko** [comment]
@santhoshnsscoe  I reproduce your bug.
Thanks for report.
Internal ticket was created MAGETWO-69616

**Comment by Yavonz15** [comment]
if disable cache eav it works

by command line 
`php magento cache:disable eav`

**Comment by Yavonz15** [comment]
if disable cache eav it works

by command line 
`magento cache:disable eav`

**Comment by magento-engcom-team** [comment]
@mike-happy, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by raulsinapsis** [comment]
Any commit we can see, to fix this in older versions?

**Comment by swayoleg** [comment]
Any workaround except disable cache ?
