### ISSUE TITLE
Backend depends on Javascript for saving settings

### ISSUE THREAD

**Issue by nyov** [magento/magento2#788]
If for some reason the backend broke and the styles/scripts can't be found (in this instance I messed up the base url), there is no fixing things from the backend because settings can't be saved anymore.

It would be nice if Javascript wasn't essential there.
(edit; or, if necessary, inline for this one instance)

**Comment by maksek** [comment]
Hi @nyov, do you still face the issue?

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32233

**Comment by vpelipenko** [comment]
@nyov, it is known behavior, it is not resolved and we don't expect to see it fixed in the future. Scripts and styles are required things for both frontend and backend. If scripts are missed for some reason as we see in you case, backend becomes not operable.

**Comment by nyov** [comment]
Well, that's okay. Feel free to close this.

I'm just noticing I didn't say _which_ script I find problematic in the initial ticket.
It's the one that submits a form apparently. I could perfectly navigate the broken, unstyled backend, but when I tried to fix the broken base url, the _save_ button simply didn't work! That was frustrating since it was obviously in the html, and I see no reason why it couldn't have a plain html form element submission fallback.

And to be candid, I feel this proliferation of JS-only pages (for things like static links and form submissions, not generated DOM elements or XHR) bad interface design.
Also, going back to a magento 1 install, the m2 navigation hover effect feels soo slow, (~ .5 seconds waiting for a drop-down to open/unfold, and in some timing cases failing to open at all) when CSS would be totally enough to achieve this effect without unnecessary fancy delays.
Ah, sorry for ranting.
If I get too tired of it, I can build my own backend theme after all :)

Again, feel free to close. Thanks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Backend-depends-on-Javascript-for-saving-settings/idi-p/46961).

**Comment by magento-engcom-team** [comment]
Hi @nyov. Thank you for your report. 
The issue has been fixed in magento/magento2#14634 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [a1db92278162bd02585b31d25f46ffcf593d13a8](https://github.com/magento/magento2/commit/a1db92278162bd02585b31d25f46ffcf593d13a8)
 - [25ee33227c8e44baf976a48eb8e78b65738b50fb](https://github.com/magento/magento2/commit/25ee33227c8e44baf976a48eb8e78b65738b50fb)
 - [9cda5f04e400db1f8a04ea4221dd71096e66006d](https://github.com/magento/magento2/commit/9cda5f04e400db1f8a04ea4221dd71096e66006d)

The fix will be available with the upcoming 2.3.0 release.
