### ISSUE TITLE
Magento 2 "add to cart" not working for configurable products with text/visual swatches

### ISSUE THREAD

**Issue by vikramshivtare** [magento/magento2#7880]
### Preconditions

1. Magento CE 2.1.2
2. PHP Version 5.6
3. Configurable product created with color (visual swatch) and size (text swatch) variations added.
4. Another configurable product added with custom attribute named as "Custom Size" (drop-down) and it is adding to cart perfectly.

### Steps to reproduce

1. Navigate to configurable product from home page.
2. Select the variations color and size and click "Add to Cart" button, it will give "This is a required field." error even if we select the variations.

### Expected result

1. Ideally it should add the current product to cart. 

### Actual result

1. ![image](https://cloud.githubusercontent.com/assets/24654090/21316983/292a51f6-c629-11e6-92d4-b88fad264c9e.png)
2. Even if selecting variations it is giving "This is a required field." error.

**Comment by veloraven** [comment]
@vikramshivtare is this issue still actual?
We were not able to reproduce it on the ver. 2.1.7.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
