### ISSUE TITLE
Grid table in Tab display, but not filtered, sorting, pagination and etc

### ISSUE THREAD

**Issue by OlgaBurtyka** [magento/magento2#7887]
### Preconditions

1. Magento 2.1.2
2. Php 7
3. Maria DB
4. Nginx
5. Docker

### Steps to reproduce

1.  It custom extension, not reproduced on default magento
2. In Tab I have custom grid table, this grid display data from database, but not filtering, sorting and pagination. I am not need serialize this grid table - need simple display grid table and filtering by data.

### Expected result

1.  Grid data filtering in certain tab

### Actual result

1. Nothing filtering and pagination
![1step](https://cloud.githubusercontent.com/assets/4771407/21321750/d864f780-c61e-11e6-9880-258f08d70ea0.png)
![2step](https://cloud.githubusercontent.com/assets/4771407/21321753/d8659d66-c61e-11e6-8a75-da5481f7a7fb.png)
![3step](https://cloud.githubusercontent.com/assets/4771407/21321752/d8655810-c61e-11e6-881a-1a44075f6453.png)
![4step](https://cloud.githubusercontent.com/assets/4771407/21321751/d86544ec-c61e-11e6-88f8-a520ac7aeb93.png)

It some files and part code which take part in display Tab grids:

1) Module\Module\Block\Adminhtml\Feed\EditTabs.php

> 
> protected function _beforeToHtml()
>     {
>         $this->addTab(
>             'general',
>             [
>                 'label'   => __('General'),
>                 'title'   => __('General'),
>                 'content' => $this->getLayout()
>                     ->createBlock(Module\Module\Block\Adminhtml\Feed\Edit\Tab\General')
>                     ->toHtml(),
>                 'active'  => true
>             ]
>         );
>         $this->addTab(
>             'importsetting',
>             [
>                 'label'   => __('Import Settings'),
>                 'title'   => __('Import Settings'),
>                 'content' => $this->getChildHtml('importsetting'),
>             ]
>         );
>          $this->addTab(
>             'feeddata',
>             [
>                 'label'   => __('Feed Data'),
>                 'title'   => __('Feed Data'),
>                 'content' => $this->getLayout()->createBlock('Module\Module\Block\Adminhtml\Feed\Edit\Feed\Data')->toHtml()
>             ]
>         );
>          $this->addTab(
>             'feedlog',
>             [
>                 'label'   => __('Feed Log'),
>                 'title'   => __('Feed Log'),
>                 'content' => $this->getLayout()->createBlock('Module\Module\Block\Adminhtml\Feed\Edit\Feed\Logs')->toHtml()
>             ]
>         );
>         return parent::_beforeToHtml();
>     }

2)  Module\Module\Controller\Adminhtml\Feed\Datagrid.php
 

>  protected $_forwardFactory;
>    protected $resultLayoutFactory;
> 
>     public function __construct(
>         Context $context,
>         ForwardFactory $forwardFactory,
>         \Magento\Framework\View\Result\LayoutFactory $resultLayoutFactory
>     )
>     {
>         $this->_forwardFactory = $forwardFactory;
>         $this->resultLayoutFactory = $resultLayoutFactory;
>         parent::__construct($context);
>     }
> 
>     public function execute()
>     {
>         $resultLayout = $this->resultLayoutFactory->create();
>         return $resultLayout;
>     }
> 

3) Module\Module\Block\Adminhtml\Feed\Edit\Feed\Data.php

> 
> class Data extends \Magento\Backend\Block\Widget\Grid\Extended
> {
>     /**
>      * Sales reorder
>      *
>      * @var \Magento\Sales\Helper\Reorder
>      */
>     protected $_salesReorder = null;
> 
>     /**
>      * Core registry
>      *
>      * @var \Magento\Framework\Registry
>      */
>     protected $_coreRegistry = null;
> 
>     /**
>      * @var  \Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory
>      */
>     protected $collectionFactory;
> 
>     /**
>      * @param \Magento\Backend\Block\Template\Context $context
>      * @param \Magento\Backend\Helper\Data $backendHelper
>      * @param \Magento\Framework\Registry $coreRegistry
>      * @param array $data
>      */
>     public function __construct(
>         \Magento\Backend\Block\Template\Context $context,
>         \Magento\Backend\Helper\Data $backendHelper,
>         \Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory $collectionFactory,
>         \Magento\Framework\Registry $coreRegistry,
>         array $data = []
>     )
>     {
>         $this->_coreRegistry = $coreRegistry;
>         $this->_collectionFactory = $collectionFactory;
>         parent::__construct($context, $backendHelper, $data);
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     protected function _construct()
>     {
>         parent::_construct();
>         $this->setId('datafeed_grid');
>         $this->setDefaultSort('sku', 'desc');
>         $this->setUseAjax(true);
>     }
> 
>     /**
>      * Apply various selection filters to prepare the sales order grid collection.
>      *
>      * @return $this
>      */
>     protected function _prepareCollection()
>     {
> 
>         $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
>         $collection = $objectManager->get('\Module\Module\Model\ResourceModel\Inventorydata\Collection');
> 
>         $collection
>             ->addFieldToSelect(
>                 'sku'
>             )->addFieldToSelect(
>                 'qty'
>             )->addFieldToSelect(
>                 'update_time'
>             )->addFieldToFilter(
>                 'feed_id',
>                 $this->_coreRegistry->registry('current_feed_id')
>             );
> 
>         $this->setCollection($collection);
>         return parent::_prepareCollection();
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     protected function _prepareColumns()
>     {
> 
>         $this->addColumn(
>             'sku',
>             [
>                 'header' => __('Sku'),
>                 'index' => 'sku',
>                 'type' => 'text',
>                 //'filter' => true,
>                 'sortable' => true
>             ]
>         );
> 
>         $this->addColumn(
>             'qty',
>             [
>                 'header' => __('Qty'),
>                 'index' => 'qty',
>                 'type' => 'text',
>                // 'filter' => true,
>                 'sortable' => true
>             ]
>         );
> 
>         $this->addColumn(
>             'update_time',
>             [
>                 'header' => __('Update Time'),
>                 'index' => 'update_time',
>                 'type' => 'datetime',
>                 'format' => \IntlDateFormatter::MEDIUM,
>                 //'filter' => true,
>                 'sortable' => true,
>                 'timezone' => false
>             ]
>         );
> 
>         return parent::_prepareColumns();
>     }
> 
>     public function getGridUrl()
>     {
>         return $this->getUrl('*/*/*', ['_current' => true]);
>     }
> }

if remove '//' from   //'filter' => true, - then write page

I only need display grid table in tab and can filtering by value(not select, not serialize). What I do wrong? Do you have code example for this situation? Can you help, please.
Thanks

**Comment by veloraven** [comment]
@OlgaBurtyka thank you for your feedback.
Could you please clarify if it is your extension or some external existing one?
If you are looking for advise please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
