### ISSUE TITLE
Admin Order Reports throw exception in en_GB locale

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#7888]
### Environment
1. PHP 5.6.16
2. MySQL 5.6.21-log
3. Magento 2.1.3
4. Apache 2.4.17

### Steps to reproduce
1. In System > All Users > User > [You], set the interface locale to English (United Kingdom):
   ![blog-3](https://cloud.githubusercontent.com/assets/8377620/17434109/7a89183c-5b00-11e6-8c8f-2a30db35c5a7.png)
2. In Reports > Sales > Orders, execute a query involving days above 12 e.g. 31/11//2016, but not 10/11/2016: ![hama-1](https://cloud.githubusercontent.com/assets/8377620/21322197/e11aeb46-c60f-11e6-8f62-e3f422eb4a0c.png)
3. Click "Show Report"

### Expected result
1.  Magento generates Order Report between the dates specified

### Actual result
1. (Exception): Invalid input date format '31/12/2015': ![hama-2](https://cloud.githubusercontent.com/assets/8377620/21322246/24d9ddba-c610-11e6-9c2d-792886d54b6b.png)

### General date/locale issues
* Although JS datepickers follow the locale set in "System > Users", PHP doesn't which causes these validation errors.
* #6323, a similar issue, has already been resolved by @slavvka.

**Comment by veloraven** [comment]
@JacobDrummond thank you for your report.
This issue was fixed in developer branch but was not fixed in 2.1 yet.
We have internal ticket for this version: MAGETWO-57839

**Comment by JacobDrummond** [comment]
@veloraven, thanks for your feedback.

When will these develop fixes be included in a release?

In general, what is your develop-to-release workflow?

**Comment by webdevlabo** [comment]
@JacobDrummond It can happen because of locale: try **M/D/Y** format instead and check if it works.

**Comment by JacobDrummond** [comment]
@webdevlabo, yes that's the known fix :)

The whole point of this bug report is that Magento should be implementing locale consistently across JS and PHP.

**Comment by janeblonde** [comment]
@veloraven this has been reported a few times since October, do you have an ETA on when it might be fixed? or is there a way we can see the code that needs to be modified from the developers branch?

**Comment by rogerrogerrogerroger** [comment]
We are based in UK with latest Magento 2.1.3, is there an update on when the fix will be released?

**Comment by marcosdsdba** [comment]
@veloraven I performed the tests and the error persists in versions 2.1.5 and 2.1.6
I opened an issue #9432

**Comment by magento-engcom-team** [comment]
@JacobDrummond, thank you for your report.
The fix for this issue is already available in the `develop` and `2.2-develop` branches. See [commits](https://github.com/magento/magento2/search?p=1&q=MAGETWO-57835&type=Commits) with `MAGETWO-57835` in the title.
