### ISSUE TITLE
3rd party payment gateways not visible in adminhtml anymore on 2.1.3

### ISSUE THREAD

**Issue by danteay** [magento/magento2#7891]
### Preconditions
1. Fresh install of Magento 2.1.3 with tar.gz package
2. 3rd Party payment gateway compatible Magento 2.1.2
3. PHP 7.0.10

### Steps to reproduce
1. Put 3rd Party gateway code inside of app/code folder (for example [https://github.com/compropago/plugin-magento-2](https://github.com/compropago/plugin-magento-2))
2. run bin/magento setup:upgrade
3. run bin/magento setup:di:compile
4. run bin/magento cache:flush
5. run bin/magento indexer:reindex

### Expected result
1. Show gateway config in **Stores -> Configuration -> Sales -> Payment Methods**

### Actual result
1. dont display the config in admin panel
![captura de pantalla 2016-12-19 a la s 16 41 47](https://cloud.githubusercontent.com/assets/9085902/21331814/1fb18064-c60a-11e6-90b5-d69abdca3e94.png)

In the compile and upgrade comand it works, an the observers works to, but the config dosn't show in the panel in any moment

**Comment by petterkj** [comment]
I would say wtf.. A really critical bug. Can reproduce. We use https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin but it doesn't show anymore.

**Comment by hostep** [comment]
~~Yesterday I read this blogpost: https://www.maxpronko.com/blog/magento-2-1-3-payment-changes-overview-and-recommendations~~

~~@mcspronko mentions the payment gateways have to add the `<can_checkout>1</can_checkout>` xml node to their config.xml file. I'm not entirely sure if this has consequences for not displaying the payment methods in the adminhtml itself though?~~

~~The strange thing is that Magento introduced this in a bugfix release, which shouldn't contain backwards incompatible changes, but oh well, it happens all the time unfortunately...
Also this change hasn't been documented in the neither the [release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html) or in the [backwards incompatible changes](http://devdocs.magento.com/guides/v2.1/release-notes/backward-incompatible-changes-2.1.html) page, @xcomSteveJohnson ?~~

**Comment by petterkj** [comment]
I think here is a hint to fix this. sortOrder seems to conflict this. See https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/issues/15#issuecomment-268223025  . Fix would be to not make sortOrder  decide whenever to ignore other payment methods -if thats the issue here.

**Comment by snez** [comment]
I confirm that as @petterkj mentioned, adjusting the **sortOrder** field will fix this. For users of the [Stripe Payments & Subscriptions](http://store.cryozonic.com/magento-2/stripe-payments-subscriptions.html) module, the solution is now documented [here](http://store.cryozonic.com/documentation/magento-2-stripe-payments-subscriptions#magento-2.1.3).

**Comment by vkublytskyi** [comment]
@danteay, thank you for reporting this issue. We confirmed it in 2.1.3 release and develop branch. Internal ticket MAGETWO-62667 is created to address this issue. We understand that such bug is critical and we will take measures to avoid such issues in future.

As reported by @petterkj and @snez, for now, third party payment method configuration would be displayed in admin panel only if group sortOrder specified in `etc/adminhtml/system.xml` file is greater than 4.

**Comment by danteay** [comment]
Tank you @vkublytskyi I try this to fix this error, and I hope that this issue is resolved soon.

**Comment by alena-marchenko** [comment]
Hi @danteay,

Fix for MAGETWO-62667 is merged to develop branch, closing the issue.
Also, this fix will be available in Magento 2.1.4 release.
Thank you.
