### ISSUE TITLE
"real" container doesn't appear in generated html

### ISSUE THREAD

**Issue by steros** [magento/magento2#7895]
### Preconditions
Magento version 2.1.3

### Steps to reproduce
add this code to the ie. `1column.xml`:

```
<referenceContainer name="{YOUR_REFERENCE_CONTAINER}">
    <container name="{YOUR.CONTAINER.NAME}" as="{YOUR_CONTAINER_NAME}" label="{SOME LABEL}" htmlTag="header" htmlId="{YOUR_ID}" htmlClass="{SOME CLASS}"/>
</referenceContainer>
```

### Expected result
An element with the specified html-tag, id and class should appear in the code.

### Actual result

- the element does not appear
- even if you change other things in the same file, like adding classes to other elements, that appear, the container does not appear

### "Solution"
The container needs to have some content to appear. If you add a block to the container it will appear in the generated html.
The documentation doesn't state this and it is unclear if this is a bug or expected behavior.
If it is expected, I don't get the reasons as to why this happens. If I add at least a htmlTag I would expect it to always appear.

**Comment by steros** [comment]
for reference: http://magento.stackexchange.com/questions/150983/adding-a-new-container-to-root

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.
We've created internal ticket(s) MAGETWO-81440 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
