### ISSUE TITLE
in android and iphone the fotoroma zoom effect in magento 2 disables the scrolling behaviour in the product page in luma theme

### ISSUE THREAD

**Issue by karthigesh** [magento/magento2#7896]
In magento 2 default luma theme the zoom effect in product page image affects the scrolling of the website. it detects as the click action and does not allow users to scroll through the site. This was a very big problem i don't know why the developers does not fix this issue till now. It also affects the iphone and android both mobile view.

**Comment by veloraven** [comment]
@karthigesh thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by karthigesh** [comment]
In magento 2 default luma theme the zoom effect in product page image affects the scrolling of the website. it detects as the click action and does not allow users to scroll through the site. This was a very big problem i don't know why the developers does not fix this issue till now. It also affects the iphone and android both mobile view.

To reproduce the issue:

 open   "http://magento2-demo.nexcess.net/gabrielle-micro-sleeve-top.html"  in mobile phone andorid or iphone , and click on the product image it will zoom the image. but when you click and drag on the image nothing happens this is because of the zooming effect in mobiile. but for the mobile there is no need for the zoom effect.
It really affects the scrolling of the website and just accepts the click function and not the dragging of the website. it stops there itself

**Comment by veloraven** [comment]
@karthigesh 
Please identify exact Magento version you are running like 2.1.3, develop, 2.0.10, etc.
Please format this issue according to the template:

**Steps:**
1.
2.
...
**Actual result:**
...
**Expected Result:**
...
It is much easier to understand and reproduce the issue when it is well-structured.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
