### ISSUE TITLE
Magento API fails in a CGI env (zf1 issue)

### ISSUE THREAD

**Issue by nyov** [magento/magento2#790]
```
curl -X POST "http://magento.local/index.php/rest/V1/integration/customer/token" -H "Content-Type:application/json" -d '{"username":"user@local", "password":"pass"}'
{"message":"Content-Type header is empty."}
```
When php is run as (Fast)CGI (issue seen using php-fpm), some HTTP headers can't be found.
Relevant code is in https://github.com/magento/magento2/blob/master/app/code/Magento/Webapi/Controller/Rest/Request.php#L149
The issue lies with ZF1 failing to find the `Content-Type` header when there is no Apache Env.

Filed a patch upstream, at https://github.com/zendframework/zf1/pull/477

**Comment by nyov** [comment]
Reopening this for a potentially "more proper" fix now committed to ZF1, https://github.com/zendframework/zf1/pull/484
This upstream change may or may not clash (I haven't properly looked) with the change done in Magento's codebase, if this zf1 update eventually gets pulled into magento's fork.

Just a heads up. Feel free to close, please.

**Comment by anupdugar** [comment]
Thanks @nyov for the updated fix . We have an internal issue to address this : MAGETWO-31613. We will keep you posted when the fix is applied.

**Comment by anupdugar** [comment]
@nyov We have gone ahead and upgraded to zf 1.12.10 (instead of just taking in the patch) in 0.42.0-beta8. 
This should take care of the issue you reported. Closing it.
Thank you for your contribution!
