### ISSUE TITLE
New Terms and Conditions Refuses to Save

### ISSUE THREAD

**Issue by roseofgold** [magento/magento2#7905]
### Preconditions

1. Magento 2.1.2
2. PHP 7.0.13
3. Terms and Conditions is Enabled in Checkout Configuration

### Steps to reproduce

1.  Store > Settings > Terms and Conditions
2. Click Add New Condition
3. Fill in Required Fields
4. Click Save Condition

### Expected result

1. Condition Saves and you return to the list of all terms and conditions

### Actual result

1. Error that reads 'Something went wrong while saving this condition.'

**Comment by Detzler** [comment]
what do the logs say?

**Comment by roseofgold** [comment]
Sadly I don't have access to logs (or I just don't know where to find them)

Edit: OK, I found it. Looks like I have a missing table. How do I correct this?

[2016-12-21 19:38:13] main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'supersaf_supers.checkout_agreement' doesn't exist,

**Comment by roseofgold** [comment]
Apparently my install wasn't complete. I had to insert 2 tables (checkout_agreement and checkout_agreement_store). Solved my issue.
