### ISSUE TITLE
datetime JS validation for different locales

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#7907]
### Preconditions
1. M EE 2.1.3
2. cs_CZ locale for admin user

### Steps to reproduce
1. Open product edit in admin
2. Schedule new update
3. Fill any date and time in future
4. Save

### Expected result
1. Schedule will be saved

### Actual result
1. You will get "error: : Future Update Start Time cannot be earlier than current time."  (it isn't)
2. This affects all date time inputs in admin

**Comment by veloraven** [comment]
@magexo thank you for your report.
I was not able to reproduce this issue by your steps.
Please provide more information about your locales: for andmin, for storefront, etc, and more detailed steps - what exactly you do including exact date you choose, product type, etc.
Please also provide information about your environment: OS, versions of web-server, PHP, MySQL.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by xtm2005** [comment]
Hi, encountered the same problem interesting thing is it's happening on the validation level, in validator.php. I'm attaching a sample time stamp what it currently returns.  Note that we are running in httpd, at UTC, already set systems time zone to UTC. And it's obtaining the incorrect time stamp. If i set it today, then it will get the exact time that is currently required, it's not exactly a bug but rather an incorrect implementation of the logic, if it's set as today it should be offset to let's say a further 2-3 minutes.
