### ISSUE TITLE
2.1.3 Configurable Product with first product 'out of stock' or qty <0 displays zero price $0.00

### ISSUE THREAD

**Issue by staffrob** [magento/magento2#7908]
Preconditions

Magento 2 CE 2.1.3, PHP7, MYSQL14.14
Have upgraded from 2.1.1 - 2.1.2 - 2.1.3
This issue existed in 2.1.1 [https://github.com/magento/magento2/issues/6799](#6799) however, the actual result has changed in 2.1.3. 
Steps to reproduce

add new configurable product with multiple simple products (ie color red,blue,yellow with qty's >0)
Product is now displaying on frontend as expected
Now go back to admin and mark first (lowest product id) simple product as 'out of stock'.

Expected result

Display configurable product as normal on frontend

Actual result

1. Product is displayed with $0.00 price on product page.
2. Once a configurable option is selected the price is displayed as expected.

https://www.dropbox.com/s/7i0xcrdvhw83ayq/Screenshot%202016-12-21%2011.57.31.png?dl=0
https://www.dropbox.com/s/mtvr2nw6qrvzek3/Screenshot%202016-12-21%2011.58.26.png?dl=0
Products displayed with zero price in catalog pages as well (if first configurable option out of stock)
https://www.dropbox.com/s/m2pp416q0ufxlny/Screenshot%202016-12-21%2012.10.28.png?dl=0

Also, don't know if this issue is related but worth a mention, in this example size 4 is 'out of stock', it is still selectable.
https://www.dropbox.com/s/w5qwj8nr2cyy46y/Screenshot%202016-12-21%2012.03.13.png?dl=0
When you add the 'out of stock' size 4 to cart...
https://www.dropbox.com/s/r537r964izpt46a/Screenshot%202016-12-21%2012.04.28.png?dl=0

**Comment by staffrob** [comment]
> Fixed in develop branch with commit : 1e78fe2

This commit removes the exception and introduces new issue. Now the price displays as $0.00 until user selects a configurable product attribute

**Comment by veloraven** [comment]
@staffrob thank you for your report.
I was not able to reproduce this issue neither on the clean instance nor after upgrade.
So could you please add more detailed steps?
1. How did you create configurable product?
2. How did you upgrade? Please provide exact steps.
3. What was the order of your actions? I mean, did you create some configurable product, upgrade, made simple out of stock? or was it some other order?

**Comment by staffrob** [comment]
Hi Veloraven,

All you need to do is set the first configurable option/simple product qty to 0 and mark out of stock, no special order, just the first simple product (lowest ID).

**Comment by staffrob** [comment]
Also, It is happening on clean install 2.1.3 for me

**Comment by pboisvert** [comment]
@antboiko can you have someone take a look at this issue?

**Comment by EmilyPepperman** [comment]
@veloraven I have this same issue on 2.1.3, I didn't have the issue on 2.1.2

**Comment by EmilyPepperman** [comment]
@staffrob Do you happen to have the extension called Amasty Custom Stock Status? I might have stumbled on something.

**Comment by antboiko** [comment]
@staffrob We cannot reproduce this issue on clean installation 2.1.3. In case you have 3-rd party extensions please disable them and try again. What theme are you using? 

Also please try to clear all caches, including browser cache and let me know if the issue is still present.

Thanks,
Anton.

**Comment by staffrob** [comment]
Thanks for that,

It looks I haven't upgraded correctly. I have just compared files in my upgraded 2.1.3 /app/code/magento/* to fresh files and found they are not updated.

the commands I used to upgrade were `composer require magento/product-community-edition 2.1.3 --no-update
composer update
bin/magento setup:upgrade
`
version shows as 2.1.3
if I run these commands again I get the following...

> Your requirements could not be resolved to an installable set of packages.


>  Problem 1
    - Installation request for magento/magento2ce 2.1.3 -> satisfiable by magento/magento2ce[2.1.3].
    - magento/product-community-edition 2.1.3 requires magento/framework 100.1.3 -> satisfiable by magento/framework[100.1.3].
    - don't install magento/framework 100.1.3|remove magento/magento2ce 2.1.3
    - Installation request for magento/product-community-edition 2.1.3 -> satisfiable by magento/product-community-edition[2.1.3].

**Comment by staffrob** [comment]
Hi @EmilyPepperman, no I don't have Amasty Custom Stock status installed

**Comment by staffrob** [comment]
here is an example of diffmerge CatalogInvetory/Composer.json from my botched upgrade compared with clean 2.1.3
https://www.dropbox.com/s/vhxo127m6p80anr/Screenshot%202016-12-31%2001.28.33.png?dl=0 bin/magento --version returns
Magento CLI version 2.1.3

I now only have backups of this 2.1.3 ish as all 2.1.2 backups have been overwritten over the holidays, any suggestion how I could repair this?

**Comment by staffrob** [comment]
This was resolved by overwriting with fresh 2.1.3 files.
