### ISSUE TITLE
WYSIWYG editor does not update image.

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento/magento2#7910]
WYSIWYG editor does not update the images, If we insert the new image which is working fine, but if we update the existing image which is not update.

### Preconditions

1. Magento version : 2.1.1
2. PHp verion : 7.0.14-1+deb.sury.org~xenial+1

### Steps to reproduce

1.Log in to admin panel
2.Go to Content -> Pages/Blocks
3.Add a new block/page.
4.Add new image via WYSIWYG editor. Now it is inserted perfectly.
5.Save the block.
6.Again Edit the same block.
7.Now the block have a image i want to update the new image for the existing one.
8.Select the image and click button (using wysiwyg toolbar).
9.Update the new images.
10.In preview it's update fine.
11.Save the block.
12.Now edit the block which has a existing image only, the new image not present here.

### Expected result

1. The new images should be updated.

### Actual result

1. The new images not be updated.
2. The old/existing image only present here.
Scree-shots:
http://prnt.sc/dm5avp
http://prnt.sc/dm5bcv
http://prnt.sc/dm5bn1
http://prnt.sc/dm5bwf
http://prnt.sc/dm5dvk

**Comment by veloraven** [comment]
@ewallkrishnaprakash thank you for your report.
Is this issue still actual? We were able to reproduce it only partly on the specified version. 
And we were not able to reproduce it on the latest version (2.1.7).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
