### ISSUE TITLE
emulateAreaCode does not emulate config scope

### ISSUE THREAD

**Issue by krukas** [magento/magento2#7912]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce
Make a console command that load a product for a specefic store and try to get the final price (with rules) of product:

```
$this->_appState->emulateAreaCode(
    \Magento\Framework\App\Area::AREA_FRONTEND,
    [$this, 'getProductPrice'],
    [$product]
);

public function getProductPrice($product){
	var_dump($product->getPriceModel()->getFinalPrice(1, $product));
}
```

### Expected result
Get final price of product with applied rules

### Solution
Make emulateAreaCode also emulate the config scope.

I will make a pull request that fix this problem

**Comment by magento-engcom-team** [comment]
Hi @krukas thank you for the report and pull request. We are closing this issue for now. If you would like to you improve your PR and submit it again. Thank you for your contribution!
