### ISSUE TITLE
Failed to set ini option "session.save_path" to value

### ISSUE THREAD

**Issue by pavelnovitsky** [magento/magento2#792]
Hi,
IspManager and IspManager Light predefine session.save_path in virtual host config as  
`php_admin_value session.save_path "/var/www/dev/data/mod-tmp"`

This prevents from changing session.save_path with ini_set() in SessionManager::initIniOptions().
Value can not be set and result is always «false» that leads to the 
`Failed to set ini option "session.save_path" to value "/var/www/dev/data/www/example.com/magento2/var/session/".`

**Comment by muasir** [comment]
We have committed the fix for this issue.  Please reopen if the fix doesn't work for you.
