### ISSUE TITLE
Order not editable in backend, generated error

### ISSUE THREAD

**Issue by zamocom** [magento/magento2#7920]
When I place a order in the fronted I can see the order in backend sales/orders, I can see the order but I can't edit it, this operation generate errors, if I edit orders generated before the update I can edit it
### Preconditions

1. Magento 2.1.3
2. I use Italian traslate installed for Magento 2.0

### Steps to reproduce

1. Create new order in front office
2. See the order in back office
3. Edit it

### Expected result

1. Edit order in back office

### Actual result

1. Error
![error-order](https://cloud.githubusercontent.com/assets/24704756/21405858/b46a8ce0-c7c8-11e6-919c-ec1627020d29.jpg)

**Comment by veloraven** [comment]
@zamocom thank you for your report.
Do I understand correctly that you upgraded to 2.1.3 from some previous version? Could you please provide exact Mgento version which you upgraded from? 
Also if there are any logs in the var/log folder they can be helpful.

**Comment by zamocom** [comment]
Hi, First version if Magento I install is 2.0.7, then I install all the installation available only by System Update of Magento, I don't have install another module, I install Porto theme. I have the problem from 2.1.2 version, My old order work correctly. I attached the log file. Thanks
[update.log.txt](https://github.com/magento/magento2/files/673736/update.log.txt)
[exception.log.txt](https://github.com/magento/magento2/files/673737/exception.log.txt)


[debug.log.txt](https://github.com/magento/magento2/files/673734/debug.log.txt)

**Comment by zamocom** [comment]
I have have also system log but is too big for send. Thanks

**Comment by zamocom** [comment]
I have the Italian translation installed before the update at 2.1.2 Magento version.

**Comment by zamocom** [comment]
The solution for me is: reinstall all, now all works correctly. Thanks
