### ISSUE TITLE
incorrect special price in frontend 

### ISSUE THREAD

**Issue by tal-girit** [magento/magento2#7925]
### Preconditions

1. Magento version : 2.1.2

### Steps to reproduce

1. create cofigurable product 
2. add simple product to the cofigurable product 
3. set special price to the simple product from date - to date (set date of the past .. !!) 
    the price has to be not active by the period of dates 
4.  check the product in the front end .. you will see old price and new price even when  the dates period passed 

### Expected result

1. in the front end  we expect to see the only the old price if the special period passed 

### Actual result

1. check the product in the front end .. you will see old price and new price even when  the dates period passed

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket id MAGETWO-62649

**Comment by eldonbite** [comment]
Also encountering this issue. It seems the only way to hide the special prices is to remove them completely on each product with expired special prices. Before Magento 2.1.3, I needed to reindex before the special prices in the front-end gets hidden. In 2.1.3, there is no longer a need to reindex, but you still need to remove the special prices even if they already expired.

I've added a comment some time ago to a related issue:

https://github.com/magento/magento2/issues/6457#issuecomment-268730603

**Comment by patruvlad** [comment]
Any update on this issue? We are having the same issue on Magento 2.1.7

**Comment by magento-engcom-team** [comment]
@tal-girit, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by amberarpatech** [comment]
any progress i am facing this issue in 2.1.9 too

**Comment by amberarpatech** [comment]
My scenario is speical price date was set from 2017-09-26 to 2017-09-27 and today is 2017-09-28 and special price is still showing on prodyct listing and product detail page.

I am tired from resolving these kind of issues
