### ISSUE TITLE
Sign in functionality is not working in google chrome browser.

### ISSUE THREAD

**Issue by ajijshekh123** [magento/magento2#7926]
### Preconditions

1. In Existing user > Login functionality is not working.
2. 

### Steps to reproduce

1. First Create new account in open My dashboard.
2. Logout the system.
3. Again login with Same user.

### Expected result

1. Login functionality should be working properly.

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@ajijshekh123 thank you for your submission.
Please specify Magento version you are running.
Please also add actual result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
