### ISSUE TITLE
Endpoint quoteShippingAddressManagementV1 not available

### ISSUE THREAD

**Issue by Nicelabsrl** [magento/magento2#7929]
### Preconditions

1. I am using Magento 2.1.3 CE Version

### Steps to reproduce

1. Request for WSDL http://domain-name/soap/default/default?wsdl&services=quoteShippingAddressManagementV1

### Expected result

1. The response should be the correct WSDL XML schema

### Actual result

1. Actual result is:
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
<env:Body>
<env:Fault>
<env:Code>
<env:Value>env:Receiver</env:Value>
</env:Code>
<env:Reason>
<env:Text xml:lang="it">
Internal Error. Details are available in Magento log file. Report ID: webapi-585b94eb49b5f
</env:Text>
</env:Reason>
</env:Fault>
</env:Body>
</env:Envelope>

In the log error:

Message: The required service is not available: "quoteShippingAddressManagementV1" in /vendor/magento/framework/Webapi/ErrorProcessor.php:195

**Comment by olysenko** [comment]
Hi, thank you for your report. Magento doesn't have service quoteShippingAddressManagementV1 for shipping address now. Only for billing one still exists  - quoteBillingAddressManagementV1. It is a bug of not updated documentation. Internal issue DDOC-12 was created

**Comment by Nicelabsrl** [comment]
Is there another way to assign a shipping address to a quote by webapi now?

**Comment by okorshenko** [comment]
Hi @Nicelabsrl 
SOAP documentation bug. [Documentation](http://devdocs.magento.com/guides/v2.1/soap/bk-soap.html) is already [fixed](https://jira.corp.magento.com/browse/MAGETWO-69838)

**Comment by okorshenko** [comment]
Hi @Nicelabsrl the documentation has been updated. Thank you for report
