### ISSUE TITLE
Enable Content Experiments only possible with active Analytics account

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#7934]
### Preconditions

1. Magento version 2.1.3
2. PHP7, Nginx, Debian, Maria DB

### Steps to reproduce

1. Go to admin --> configuration --> sales --> google api
2. Try to enable "Enable Content Experiments" without activating the google "analytics" area 

### Expected result

1. You can activate "Content Experiments" without entering an google analytics id or activate the analytics section

### Actual result

1. you need to enable whole analytics and also put in a Account Number to the analytics tab to activate content experience. This is very bad as most of the users use not the "standard" google analytics but for example an advanced google analytics over the google tag manager supporting variables etc. 

So there is no option just to activate the "Enable Content Experiments" without activating the "normal" analytics code on the site.

**Comment by andidhouse** [comment]
...not "seo" - analytics is not seo!

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.
We've created internal ticket(s) MAGETWO-81265 to track progress on the issue.

**Comment by brndnu** [comment]
This won't matter soon because Content Experiments is being deprecated by Google and replaced with Google Optimize.

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
