### ISSUE TITLE
User update information lead to "user already exist"

### ISSUE THREAD

**Issue by MattDelac** [magento/magento2#7936]
### Preconditions

1. Version: Magento Community 2.1.2
2. Server: Php7, varnish, redis, mariadb

### Steps to reproduce

1. Connect as an admin user
2. Create a new user (or take an existing one)
3. Change the value 'This account is' from 'Active' to 'Inactive' 
4. Enter your admin password and 'Save user'

### Expected result

1. This should update the user account and desactivate the user

### Actual result

1. This result to an error 'A user with the same user name or email already exists.'
![selection_278](https://cloud.githubusercontent.com/assets/18557047/21428505/997285a4-c85a-11e6-98f8-a76286d20a9b.png)

Moreover, you need the admin password to update any information of a user but we do not need any password to delete an account ... I, personally, do not think that updating user's information should be more restrictive than deleting a user ...

Thank you

**Comment by sevos1984** [comment]
I can't reproduce this on 2.1.3, try update your codebase

**Comment by MattDelac** [comment]
@sevos1984 It's all good after updating to the last version

You can now close this issue,
thanks
