### ISSUE TITLE
The `Magento_Ui/js/lib/knockout/extender/bound-nodes` RequireJS Module does not Work as Intended

### ISSUE THREAD

**Issue by astorm** [magento/magento2#7939]
### Preconditions
Magento 2.1.x installed via `composer create-project`.  Javascript code only, PHP & MySQL versions not relevant.

### Steps to reproduce

1. Install magento
2. Open the home page
2. Run the program mentioned below from the javascript console

### Expected result
1. Program lists DOM nodes scoped to the `customer` view model.

### Actual result

1. Program lists empty array

Here's the program to run

    boundNodes = requirejs('Magento_Ui/js/lib/knockout/extender/bound-nodes');
    reg = requirejs('uiRegistry');    
    viewModel = reg.get('customer');
    console.log( boundNodes.get(viewModel) );

Also, per the community thread, this is definitely a bug, and a not a feature request: https://community.magento.com/t5/Programming-Questions/What-does-the-Magento-Ui-js-lib-knockout-extender-bound-nodes/m-p/55791

**Comment by SerhiyShkolyarenko** [comment]
Thank you for the report! We created internal ticket MAGETWO-62590.

**Comment by magento-engcom-team** [comment]
@astorm, thank you for your report.
We've created internal ticket(s) MAGETWO-62590 to track progress on the issue.
