### ISSUE TITLE
SOAP WSDL Xml Issue

### ISSUE THREAD

**Issue by bschimoler** [magento/magento2#7940]
Receiving an unrecognized document type when trying to process the magento2 soap wsdl with Visual Studio 2015 

### Preconditions

1. Magento v2.1.1 installed and running
2. Visual Studio 2015 

### Steps to reproduce

1. Add a service reference of soap wsdl to visual studio 2015 (http://<magento_host>/soap/default?wsdl_list=1)

### Expected result

1. Parse wsdl xml response

### Actual result

1. Unrecognised document type 
Log from C#
The document at the url http://[removed]/soap/default?wsdl_list=1 was not recognized as a known document type.
The error message from each known type may help you fix the problem:
- Report from 'XML Schema' is 'Data at the root level is invalid. Line 1, position 1.'.
- Report from 'DISCO Document' is 'Data at the root level is invalid. Line 1, position 1.'.
- Report from 'WSDL Document' is 'There is an error in XML document (1, 1).'.
  - Data at the root level is invalid. Line 1, position 1.
Metadata contains a reference that cannot be resolved: 'http://[removed]/soap/default?wsdl_list=1'.
The content type application/json; charset=UTF-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '{"directoryCurrencyInformationAcquirerV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=directoryCurrencyInformationAcquirerV1"},"directoryCountryInformationAcquirerV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=directoryCountryInformationAcquirerV1"},"customerAccountManagementV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=customerAccountManagementV1"},"quoteGuestCartRepositoryV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=quoteGuestCartRepositoryV1"},"quoteGuestCartManagementV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=quoteGuestCartManagementV1"},"quoteGuestShippingMethodManagementV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_english_view?wsdl&services=quoteGuestShippingMethodManagementV1"},"quoteGuestShipmentEstimationV1":{"wsdl_endpoint":"http:\/\/[removed]\/soap\/hdj_englis'.
If the service is defined in the current solution, try building the solution and adding the service reference again.

**Comment by magento-engcom-team** [comment]
@bschimoler, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
