### ISSUE TITLE
Handling fee is not coming in REST API response

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#7944]
### Preconditions

1.  Instance is setup using Magento 2.1.2 CE release and shipping tables are setup with handling fee

### Steps to reproduce

1.  Placed an order with shipping method to have handling fee.
2.  Make a API call GET:/V1/orders/:id or GET:/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=increment_id&searchCriteria[filter_groups][0][filters][0][value]={{increment_id}}&searchCriteria[filter_groups][0][filters][0][condition_type]=eq

### Expected result

1.  Response json should be to give handling fee amount.

### Actual result

1. 
![image](https://cloud.githubusercontent.com/assets/12096540/21449552/513a4afa-c914-11e6-845a-216f4363e2c2.png)

Response for this order

[1091.txt](https://github.com/magento/magento2/files/670451/1091.txt)

**Comment by olysenko** [comment]
Hi, thank you for report. Please provide more detailed steps about  "shipping tables are setup with handling fee" in order to reproduce this issue. For instance if I use Flat/Table Rate shipping methods with Handling fee it goes to the Shipping & Handling result value in order but not to the Handling value alone.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by srinivasanithin** [comment]
@olysenko : We found a custom code which was putting that handling fee and hence it was not showing up in API. We are good to close it. Sorry for delay update
