### ISSUE TITLE
At the Checkout, some fields are required. But Zip/Postal code field always has a red border and the 'required' notification below it.

### ISSUE THREAD

**Issue by parthpatel147** [magento/magento2#7946]
![screenshot_1_11](https://cloud.githubusercontent.com/assets/24734207/21455235/94db655c-c944-11e6-99f4-e6ad04b557c5.png)

**Comment by quienti** [comment]
Duplicate : https://github.com/magento/magento2/issues/7724

**Comment by pboisvert** [comment]
closing as duplicate of #7724
