### ISSUE TITLE
Package Tracking link from Admin Page opens wrong store template

### ISSUE THREAD

**Issue by flnative** [magento/magento2#7947]
### Preconditions
1. Magento 2.1.2
2. Multi Store
3. Built-in Cache, minify HTML

### Steps to reproduce

1. Open customer order from admin panel
2. Click "track order" link" under Shipping & Handling Information
3. view tracking page

### Expected result

1. View tracking information from the active store template from which order was placed. Not sure if this is what the customer will view from any links from their account or elsewhere when tracking their order.

### Actual result

1. Tracking details are shown from wrong store (default store) instead of store where item was sold. Shows from my default template in Store 1; order was from store 2.

**Comment by magento-engcom-team** [comment]
@flnative, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
