### ISSUE TITLE
In Magento 2.0.11, Incorrect Number of Products in Parent Category in Frontend

### ISSUE THREAD

**Issue by perry3181** [magento/magento2#7948]
### Preconditions
Magento 2.0.10
### Steps to reproduce

1. Upgraded from 2.0.10 to 2.0.11
2. My store has 4 layers of category, Default Category --> Parent --> Child_1 --> Child_2
3. Parent category has total 463 products. It shows correct number in backend categories page. 
4. Already tried to clear all cache and reindex, it only happens in Parent category, without any issue in Child_1 and Child_2 categories.
5. My store included many of configurable products

### Expected result

1. Frontend should show 4xx products in Parent category, excluded the "out of stock" products

### Actual result

1. Frontend show only 28 items in Parent category, but Child_1, Child_2 show the correct number of products
![category issue](https://cloud.githubusercontent.com/assets/20721447/21456940/78f2d236-c966-11e6-8aa6-26648ad42afb.png)

**Comment by perry3181** [comment]
Hello @veloraven , do you have temporary solution to fix this issue? Thank you so much!

**Comment by perry3181** [comment]
Hello @veloraven , i tried to rewrite the 'isRangingNeeded' method but it doesn't help.
I think 2.0.11 issue is different from 2.1.3, also I just found that some Child_1 --> Child_2 categories also have this problem.

**Comment by gammacode2** [comment]
Hi @veloraven , i there any solution available ? i think , it is a different to 2.1.3 - there is no rangingNeeded - i looks fine - but one addition:

if disable the loosed product , save and enabled after - the product is show in frontend. 

Restart Index via cli - Product is not available in frontend.

has any other a solution or an idea ?

**Comment by perry3181** [comment]
I just upgraded to 2.0.12 last week, but the problem still exist :(

**Comment by magento-engcom-team** [comment]
@perry3181, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
