### ISSUE TITLE
2.1.3 - Unable to change luma logo, default welcome message or footer copyright

### ISSUE THREAD

**Issue by bfsmith07** [magento/magento2#7949]
I upgraded from 2.1.2 to 2.1.3.  After the upgrade my logo is back to the default luma one, my welcome message is the default and the footer copyright text is default.  They still show correct in settings, but it does not display on my website.

### Preconditions
I am using a custom theme on Magento 2.1.3.  My setup is a follows:
- Fedora Server 24
- MySQL (MariaDB) 15.1
- PHP 5.6.29

### Steps to reproduce
I even tried installing a new version of Magento 2.1.3 from composer.  After installation, i change the config to single store mode and changed my logo.  Still on a brand new installation it didn't show my logo.  It only shows the Luma one.  Also it doesn't change the default welcome msg or footer copyright text.

Please help.

**Comment by cowmix88** [comment]
I'm having the same problem.

All my store views are using the default configuration settings and ignoring the website/store view configuration.

**Comment by Tonop** [comment]
The same issue.

**Comment by Ctucker9233** [comment]
Same here.

**Comment by commcad** [comment]
Same here.

**Comment by veloraven** [comment]
@bfsmith07 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by vishveskrish** [comment]
Is there any patch or fix available ?

**Comment by indilo53** [comment]
Same issue here, even for default meta tags

**Comment by indilo53** [comment]
To fix the logo, I edited Vendor/Theme/Magento_Theme/layout/default.xml : 

```
<referenceBlock name="logo">
    <arguments>
        <argument name="logo_file" xsi:type="string">img/logo.png</argument>
    </arguments>
</referenceBlock>
```

created :  Vendor/Theme/web/img/logo.png
created :  Vendor/Theme/Magento_Email/web/logo_email.png

For the copyright, I created  Vendor/Theme/Magento_Theme/templates/html/copyright.phtml with this content : 

```
<small class="copyright">
    <div class="page-main cback">
        <span>Copyright &copy; 2016 MyCompany</span>
    </div>
</small>
```

For the welcome message, I created  Vendor/Theme/Magento_Theme/templates/html/header.phtml with this content :

```
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind="html:'CUSTOM WELCOME MESSAGE HERE'"></span>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $block->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
```

This is a lot of overhead but as a temporary fix it can be useful

**Comment by veloraven** [comment]
We have created internal ticket MAGETWO-62737

**Comment by mitch2k** [comment]
Hi,

I have the same issue. Is there any timeline for a fix?
It seems that it also influences the favicon and watermark image. In fact, it looks like every setting under Content/Design/Configuration is affected.

**Comment by CreamyG31337** [comment]
This is something to do with enabling single store mode since after disabling it I can edit these fields and see the changes. See #7392

**Comment by mattcoz** [comment]
I'm wondering if this is also the source of the problem I'm having with my Disable Module Output settings not being respected, since they're stored in the same way in the database.

**Comment by mattcoz** [comment]
Following a clue from the other issue, I tried changing the scope value in the database from "websites" to "default" for all design attributes. It works! So, either the admin is incorrectly setting the scope in the database or the frontend is incorrectly picking up the "default" values instead of the "websites" values.

**Comment by BCW-Mike** [comment]
Note: Our site is in development so I'm not sure how feasible this solution will be for those with live and/or multiple stores.

I had the same issue and was able to correct it.  When updating to 2.1.3 I had my site configured in single store mode.   I disabled the single store mode and made logo/theme changes to the all the records (specifically Global) under the Design Configuration.  

Disable single store mode:
Stores -> Configuration -> General -> Single-Store Mode -> No

Update logo:
Content -> Configuration ->Edit

Mike

**Comment by sergetumanov** [comment]
It really worked for me!!!! Thank you!

**Comment by ryrobbo** [comment]
Any updates on this issue? I'm not comfortable switching from single store mode so freely. I am still experiencing this bug after updating to 2.1.3 in January.

**Comment by sergetumanov** [comment]
No luck...

Best regards,
*Sergei Tumanov*

**Comment by mattcoz** [comment]
Has anyone tried with 2.1.4?

- Matt

**Comment by Ctucker9233** [comment]
I can confirm 2.1.4 fixed this issue.

**Comment by mattcoz** [comment]
Fantastic!

- Matt

**Comment by mrjcgoodwin** [comment]
Using 2.2 changing the message does not seem to work in Single Store Mode so either still isn't fixed or is broken again?
