### ISSUE TITLE
Running setup:backup with maintenance mode already on, disables after completion.

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#7951]
If you manually enable maintenance mode, then run setup:backup, when the backup is complete, it doesn't keep the maintenance mode on, it disables it automatically.

### Preconditions

1.  Magento 2.1.3
2. PHP 7
3. nginx (hosted)

### Steps to reproduce

1. run > bin\magento maintenance:enable
2. run > bin\magento setup:backup --db --code --media
3. when backup is complete, you'll get: 
"[SUCCESS]: DB backup completed successfully.
Disabling maintenance mode"

### Expected result

1. When the backup starts, it should check if maintenance mode is already enabled or not. If it is, it should NOT disable it when the backup is complete.

### Actual result

1. It disables the maintenance mode, regardless of its state prior to the backup being taken.
![error_1](https://cloud.githubusercontent.com/assets/15789763/21461326/9ebc2884-c91e-11e6-89aa-f4cb5e512fe1.png)

**Comment by magento-engcom-team** [comment]
@spyrule, thank you for your report.
We've created internal ticket(s) MAGETWO-75973 to track progress on the issue.

**Comment by stevenvdp** [comment]
I'll take a look at this one

**Comment by okorshenko** [comment]
The issue has been fixed by @stevenvdp in PR #11056 and will be available in 2.2.1 release
