### ISSUE TITLE
Not able to delete Tax Rates in Magento 2

### ISSUE THREAD

**Issue by madaank** [magento/magento2#7952]
I deleted all the tax rules related to the tax rates, which I want to delete. 

I'm trying to delete the tax rates and not able to do so. It keeps giving error that tax rate exists in tax the rules, when there is no tax rule there.

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by pboisvert** [comment]
@madaank we will need more info to reproduce such as your system configuration and what version of Magento where you are seeing this error

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
