### ISSUE TITLE
404 error: Page not found in magento 2.2.1

### ISSUE THREAD

**Issue by rab14191** [magento/magento2#7953]
In admin panel when i m edit any  page i got  error 404 error my  site on Cantos server plz help me
404 error: Page not found.

**Comment by veloraven** [comment]
@rab14191 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
