### ISSUE TITLE
2.1.3 - Paypal - We can't place the order, w/ Product Configurations & Customizable Options

### ISSUE THREAD

**Issue by commcad** [magento/magento2#7955]
### Preconditions

1.  Mage 2.1.3
2.  NGINX, PHP 7.0.8-0ubuntu0.16.04.3

### Steps to reproduce

1. Create a new Simple Product
2. Add Customizable Options (e.g. size)
3. Add Configurations (e.g. color)

### Expected result

1.  Able to make a purchase with "product + size + color" choice

### Actual result

1. All goes well until/after Paypal payment.
2. Receiving an error "We can't place the order."

*This is a long lasting BUG that was reported in 2.0.6 I believe and still haven't been fixed until this day. Not sure what to do with this. Please advice if this is likely to be resolved in the upcoming 2.1.4 as we will most likely need to change eCommerce platform if not. Having to add 7x products per configuration is damaging our SEO terribly. *

![scgrab](https://cloud.githubusercontent.com/assets/19387951/21475902/eafc1164-cb6c-11e6-9686-c4fa21cc68a8.jpg)

**Comment by commcad** [comment]
Quick fix, if anyone else is having the same issue:

https://github.com/magento/magento2/commit/b9d96707a7f0d9d7f599812440f20344f1d45b91

**Magento & Co:** Please implement in the next release 2.1.4. Not exactly sure why you keep pushing new versions and missing the core feature fixes. 

Thank you

**Comment by YevSent** [comment]
Hi, @commcad, this is known issue and already fixed on develop branch (internal ticket MAGETWO-56699).

The fix will be available in Magento 2.1.4.

Closed as duplicate to https://github.com/magento/magento2/issues/5938.

**Comment by jer23jk** [comment]
Any solution for this bug?

Magento 2.1.7 > Order Variable product with custom option Date > Pay with Paypal

Transaction in successful, but after redirecting from paypal there is a red statement We can't place the order.

**Comment by steverobbins** [comment]
@joni-jones Can you point us towards the commit that fixes this?  Need to manually patch for now.

**Comment by areoid** [comment]
hi @jer23jk it is also happen on my Magento 2.1.7, are you already have the solution?

**Comment by jer23jk** [comment]
@areoid 
No, I haven't found the solution. It is hard to debug, because it is random.
