### ISSUE TITLE
2.1.3 - Paypal - Minicart is not clearing out after PayPal checkout

### ISSUE THREAD

**Issue by commcad** [magento/magento2#7956]
### Preconditions

1. Mage 2.1.3
2. NGINX, PHP 7.0.8-0ubuntu0.16.04.3

### Steps to reproduce

1. Add Product to cart
2. Checkout with PayPal express
3. Successful order processed, payment capture (all okay)
4. However, the minicart is still showing the product in it (do not clearing out)

### Expected result

1. Minicart clearing out after successful checkout

### Actual result

1. [Screenshot, logs]
This is a long lasting BUG that was initially reported in 2.0.7 I believe. Any ideas why this is still happening? or likely to be taken care of before any time frame?

**Comment by commcad** [comment]
----------------------------------
**FIX MINICART**
----------------------------------
REF: https://github.com/magento/magento2/pull/5807/commits/9093ce9c2f5a4ba8c60ef0dd0769e620b4ce6f18

^ Look at the date on this one guys :/ hmmm

**Comment by ioliinyk** [comment]
Registered MAGETWO-64822

**Comment by viktym** [comment]
Hi @commcad 
We've created internal ticket MAGETWO-64822 to address this issue.
Thank you for reporting.

**Comment by alena-marchenko** [comment]
Hi @commcad 

This issue has been fixed by https://github.com/magento/magento2/pull/9994.
Closing the issue.

**Comment by korostii** [comment]
Hi @alena-marchenko, 
 #9994 isn't merged into the 2.1.x branch yet.
Could you please keep the issue open until the fix is officially released?
