### ISSUE TITLE
2.1.3 - Transactional email logo is taking the LUMA theme logo

### ISSUE THREAD

**Issue by commcad** [magento/magento2#7957]
Won't fill this bug report entirely because I believe the Mage Team is fully aware of this bug since Magento 2.0.x

Any idea why this is still a BUG although having been reported multiple times already?

Please advice; little things like this impact dramatically on the reliability and "credibility" of your application.

**Comment by commcad** [comment]
**QUICK FIX**

 Overwrite logo_email.png with your own company logo in:

/var/www/magento2/vendor/magento/module-email/view/frontend/web
/var/www/magento2/pub/static/frontend/mycustomtheme/plasma/en_US/Magento_Email
/var/www/magento2/pub/static/frontend/Magento/luma/en_US/Magento_Email
/var/www/magento2/vendor/magento/theme-frontend-luma/Magento_Email/web

^ Not exactly sure which one did the trick but now it works, anyway. Overwrite and Recompile and off you go. You'll have to do this each and every time you upgrade your Magento version. Not sure why, don't ask me.

**Comment by veloraven** [comment]
@commcad if you are looking for an advice and discussion please address your question to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. 
if you want this issue to be treated as an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
