### ISSUE TITLE
The 2.1.3 & 2.0 latest version keeps loading but nothing happens

### ISSUE THREAD

**Issue by beenamalla** [magento/magento2#7962]
Hi

I tried to install both versions when i click on  Find Partners & Extensions in Admin panel .. it keeps loading all time and nothing happens . Also All the icons of the admin panel menu dont load properly

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@beenamalla thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please specify your environment: OS, versions of PHP, MySQL, web-server.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
