### ISSUE TITLE
Out of Stock Products Visible after applying filter on Listing Page.

### ISSUE THREAD

**Issue by renu2jcommerce** [magento/magento2#7964]
Hi ,
 Facing issue with Configurable products:
 Required :
 We are assigning the size attributes to configurable products if we filter through size attribute on listing page then the configurable products that has size attribute and the assigned simple products is in stock in that case only it will be visible on frontend.

 Current Result :
  For Example 
we filter the product by size attribute value say size=2.5 now the configurable products which has simple products having size as 2.5 is visible on frontend even though the products are out of stock .

We have checked in Community version 2.1.3 as well in Enterprise version 2.1.0 found same issue .
Can you please look into it ?

Thanks !!
Renu

**Comment by veloraven** [comment]
@renu2jcommerce thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by lewis-dan** [comment]
Hi,
Required :
We are assigning the size attributes to configurable products if we filter through size attribute on listing page then the configurable products that has size attribute and the assigned simple products is in stock in that case only it will be visible on frontend.

Current Result :
For Example
we filter the product by size attribute value say size=2.5 now the configurable products which has simple products having size as 2.5 is visible on frontend even though the products are out of stock .

We have checked in Magento Cloud version 2.1.9 and is is not working at all !!

Thanks,
Dan

**Comment by lewis-dan** [comment]
@igrybkov I checked your points, however, that solution is also NOT working !!
