### ISSUE TITLE
static content deploy is successful however css/js is not applied both for admin and frontend

### ISSUE THREAD

**Issue by kkdg** [magento/magento2#7965]
### Preconditions

1. Magento version CE 2.1.3, downloaded from the official Magento site. PHP 5.6.23, MySQL 5.6.33  

### Steps to reproduce

1. I downloaded the package and decompressed into the folder and ran an install successfully 
2. I finished the install using the web install, however I noticed css is not loaded when I first visited both frontend and admin. 
3. I ran _**php bin/magento setup:static-content:deploy**_ and it ended without any error. 

### Expected result

1. The site as it is intended in its look and design with css applied

### Actual result

1. The site is broken in its css aspect as if there is no css used for the site.
![issue](https://cloud.githubusercontent.com/assets/8462497/21496600/10c6d950-cc63-11e6-8f87-0ec5c5171bd7.png)

**Comment by fooman** [comment]
Are you using nginx ? 
Is your webroot folder the root folder of Magento2 or the pub folder?

**Comment by caseybecking** [comment]
My issue was I removed /pub from the end of the ROOT causing the above issue, may also be yours?

**Comment by magento-engcom-team** [comment]
@kkdg, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
