### ISSUE TITLE
Magento 2.1.3 Products cannot be edited after upgrade from 2.1.2

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#7966]
### Preconditions

1. Magento 2.1.3
2. 

### Steps to reproduce

1. Go to admin->product->catalog-> Click on a product to edit it/
2. 
3. 

### Expected result

1. All attributes should appear for modification

### Actual result

1. Magento window is still open however, no attributes or text comes on the screen related to products.

**Comment by grischunya** [comment]
Clearing the cache and cookies on my browser helped me. Try it and you

**Comment by veloraven** [comment]
@adityag186 thank you for your feedback.
Was it clean install or upgrade from some previous version?
Did you try to clean browser cache including offline website data?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
