### ISSUE TITLE
Magento 2.1.3 all products not displaying after upgrade from 2.1.2

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#7968]
### Preconditions

1. MAgento 2.1.3
2. Since website has been upgraded, products are not showing correctly.

### Steps to reproduce

1. Go to www.atlanticbooks.com.
2. Select Subjects.
3. Select Business Management.

### Expected result

1. 4706 products should be displayed

### Actual result

1. Only 500 products are being displayed

**Comment by grischunya** [comment]
I have the same error after reindex console.
If I add 1 new product it is added and displayed but after manual re-indexing - 500 products again

**Comment by perry3181** [comment]
Same problem in 2.0.11 #7948

**Comment by ndsina** [comment]
Same problem 2.1.3EE.
After investigation found, that the 'selectsByRange' method(\Magento\Framework\DB\Adapter\Pdo\Mysql.php) works incorrectly.

**Comment by adityag186** [comment]
Do you know the fix for the issue?

**Comment by ndsina** [comment]
I've just rewritten the 'isRangingNeeded' method(vendor/magento/module-catalog/Model/Indexer/Category/Product/AbstractAction.php) to return false, but it is temporary solution, I am looking for correct one.

**Comment by adityag186** [comment]
Please update me if a permanent solution is released. Thanks.

**Comment by ndsina** [comment]
Ok

**Comment by perry3181** [comment]
Hello @adityag186, I just go to your store, seems you already fixed the issue.
Could you let me know how to fix it? Thanks!

**Comment by lennartbee** [comment]
@ndsina Thanks, this works perfect for now

**Comment by perry3181** [comment]
@lennartbee, I also tried rewrite 'isRangingNeeded' method to return false. But it's not work for me.

**Comment by lennartbee** [comment]
@perry3181 is your magento crun running? Try reindexing manually also
 `php bin/magento indexer:reindex`

**Comment by perry3181** [comment]
@lennartbee Yes, I tried rewrite and then reindex manually, but it still not work for me.
But I found that if any item changed to "Out of Stock", it will becomes visible in frontend category.

**Comment by refaelgold** [comment]
@ndsina  you save my life! thanks!!!

**Comment by siment** [comment]
Duplicate: #8018

**Comment by shuaiZend** [comment]
@ndsina fixed,thank you for share.

**Comment by xmav** [comment]
I’m closing this issue because it is a duplicate. Please reopen this issue as needed.
https://github.com/magento/magento2/issues/8018
