### ISSUE TITLE
ORDER BY `sort_order` ASC before WHERE

### ISSUE THREAD

**Issue by grischunya** [magento/magento2#7969]
1. After upgrade 2.1.2 to  2.1.3
a:4:{i:0;s:334:"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (`store`.`store_id`='1')' at line 2, query was: SELECT `store`.* FROM `store` ORDER BY `sort_order` ASC
 WHERE (`store`.`store_id`='1')";i:1;s:5280:"#0 /www/site/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by veloraven** [comment]
@grischunya thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
