### ISSUE TITLE
Issues with base url when set use website on store view and website view has different url than default config

### ISSUE THREAD

**Issue by rohit-prjpt** [magento/magento2#7970]
### Preconditions

1.  Magento ver. 2.1.3

### Steps to reproduce

1. default config has url set http://www.example.com
2. website scope has url set http://web1.example.com
3. store view scope - use setting use website 

### Expected result

1. it should use website url as we have configuration set use website 

### Actual result

1. frontend will use base url http://www.example.com but actually it should use http://web1.example.com

**Comment by veloraven** [comment]
@rohit-prjpt thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result, and without external links.

**Comment by rohit-prjpt** [comment]
it is already formatted with steps to reproduce, actual result and expected result, also the external urls are just example.com

**Comment by natebatty** [comment]
Any update on this issue? I'm also having the same issue.

**Comment by korostii** [comment]
I think it's a duplicate of #7815.
A possible fix is suggested [here](https://github.com/magento/magento2/issues/7840#issuecomment-268313989) and [here](https://github.com/magento/magento2/issues/7943#issuecomment-269508822) 
It would be nice though to see it fixed and released on 2.1 branch without having to resort to workarounds, but personally and basing on previous experience, I wouldn't be too optimistic about that.

**Comment by natebatty** [comment]
Thank you 100 times over!

**Comment by IlnitskiyArtem** [comment]
Hi,@rohit-prjpt. I've linked this GitHub issue to internal ticket MAGETWO-70596.

**Comment by magento-engcom-team** [comment]
@rohit-prjpt, thank you for your report.
We've created internal ticket(s) MAGETWO-70596 to track progress on the issue.

**Comment by AndreyRozumny** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@AndreyRozumny thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by AndreyRozumny** [comment]
Seems like suggested solution were implemented in 2.2 and 2.2-develop branch so far.
And after dozens test made a decision it works as expected. can't replicate it anymore.

**Comment by magento-engcom-team** [comment]
Hi @rohit-prjpt 
We are closing this it is was already fixed in `2.2`.
@AndreyRozumny Thank you for your investigation
