### ISSUE TITLE
Paging Magento 2 not correct when using groupByAttribute on custom Collection

### ISSUE THREAD

**Issue by camaech** [magento/magento2#7971]
Perhaps related to #2884 and https://github.com/magento/magento2/commit/e012a481737ba124281581442f57231bee259aa4

Pager total number of pages is incorrect.

### Preconditions

1. Magento version 2.1.3

### Steps to reproduce

1. When creating a custom collection and using groupByAttribute, the pager doesn't display the correct number of pages.

```
	$page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
	$pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 12;

         $productCollection = $this->collectionFactory
			->create()
			->addAttributeToSelect('entity_id')
			->addAttributeToSelect('manufacturer')
			->addAttributeToSelect('image')
			->groupByAttribute('manufacturer')
			->addAttributeToFilter('status', ['in' => $this->productStatus->getVisibleStatusIds()]);

	$productCollection->getSelect()->order('manufacturer');
	$productCollection->setPageSize($pageSize);
	$productCollection->setCurPage($page);

```
and then:

```
protected function _prepareLayout() {
		parent::_prepareLayout();
		$this->pageConfig->getTitle()->set(__('Brands'));

		if ($this->getBrandListCollection()) {
			$pager = $this->getLayout()->createBlock(
				'Magento\Theme\Block\Html\Pager',
				'brandsview.brands.pager'
			)->setAvailableLimit(array(12=>12,24=>24,48=>48))
				->setShowPerPage(true)->setCollection(
				$this->getBrandListCollection()
			);
			$this->setChild('pager', $pager);
			$this->getBrandListCollection()->load();
		}
		return $this;
	}
````

### Expected result

1. Pager should return total number of pages based on pageSize instead of total number of items in the collection.

When I do a count on the productCollection I get the correct number of items grouped by manufacturer.

`
$this->_logger->debug( count($productCollection) );
`
[2016-12-27 17:24:19] report.DEBUG: 973 

### Actual result

1. Current result:
![notify](https://cloud.githubusercontent.com/assets/977957/21505036/4c983c10-cc29-11e6-9164-6d81d45a5be0.png)

Which is 18097/12 = ~1509
(total products divided by 12 items per page)

**Comment by magento-engcom-team** [comment]
@camaech, thank you for your report.
We've created internal ticket(s) MAGETWO-83515 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@camaech, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
