### ISSUE TITLE
Customer area links doesn't work after upgrading from 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#7975]
Hi there guys,
After upgrading magento 2.1.2 to 2.1.3 customer area links aren't working anymore.
customer/account/create/
customer/account/login/

None of these links are working.
Any help?

**Comment by veloraven** [comment]
@key-dev thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by key-dev** [comment]
Sticking with 2.1.2
