### ISSUE TITLE
Magento 2.1.2 to 2.1.3 color swatches no longer change the image in product page.

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#7976]
Hi there guys,
After updating magento from 2.1.2 to 2.1.3 color swatches no more changes the image related to color.
Any help?

**Comment by veloraven** [comment]
@key-dev thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by key-dev** [comment]
It was settings in attribute itself.
