### ISSUE TITLE
Magento2 Default Shipping and Billing Address Not saved when Save the customer

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#7979]
### Preconditions

1.  Version CE 2.1.3 
2. When saving the customer from backend, the default address unchecked (not saved) when we save the customer twice

### Steps to reproduce

1. Create New Customer from backend
2. Create Address and set it as default Billing and Shipping address.
3. Save Customer -> it is ok.
4. Click on save Customer again -> the issue appear and the check boxes of Default billing and Shipping will be unchecked.

### Expected result

1. The default address checkbox should be as it 

### Actual result

1. [Screenshot, logs]

**Comment by sourabh-costrategix** [comment]
You need to overwrite Controller/Adminhtml/Index/Save.php file

**Comment by KrystynaKabannyk** [comment]
Hello @zexperto, is this issue still actual for you?

**Comment by zexperto** [comment]
Hi,
After doing the update to 2.1.4, it looks like the issue was resolved
Many thanks 
Appreciated
