### ISSUE TITLE
Composer install - question

### ISSUE THREAD

**Issue by Crustymd** [magento/magento2#798]
So after running on local machine the command "composer install" it gets quite good but appears to show something interesting at the end

http://prntscr.com/5fltoi

And the setup will not run

http://prntscr.com/5fludt

**Comment by snky1987** [comment]
When I downloaded latest version of Magento2 form Github (using clone) and then composer self-update and composer install it installed all files within magento2 dir but I can't runt composer install in magento2/setup as it doesn't contain composer files. 

So setup route displays just a blank white page.

**Comment by buskamuza** [comment]
@snky1987 , it's not required to run `composer install` in `setup` folder anymore. Installation should work as soon as you run `composer install` in the root directory.
Could you, please, enable PHP errors (`display_errors = On` and `error_reporting = E_ALL` in your `php.ini`) and see if any errors appear on the installation page?
If you have xDebug enabled, please, set `xdebug.max_nesting_level=200` in `php.ini`

**Comment by snky1987** [comment]
@buskamuza Thanks, it was my mistake. I didn't notice that Magento use Angular JS for installation process and before I started to play with Magento I tested my client's travel agency application if works without JS enabled :) This caused white screen on setup.

**Comment by snohe** [comment]
Hi @Crustymd, we haven't heard back from you and, thus, will proceed with closing this issue.  In case you have any additional questions, please don't hesitate to submit a new GitHub issue.
