### ISSUE TITLE
Import custom less file not work.

### ISSUE THREAD

**Issue by Flamestyle** [magento/magento2#7981]
Import costome.less does not work in directory of theme.
### Preconditions

1. Magento ver. 2.1.3, ubuntu 16.04, Nginx 1.10, PHP 7, MySQL 5.7.
2. Costome theme same luma, path: `app/design/frontend/Vendor/theme`
### Steps to reproduce

1. Create _custome.less to `app/design/frontend/Vendor/theme/web/css/source`
```
@nice-blue: #fafafa; 
.slider {
    background-color: @nice-blue;
}
```
2. Add line to _extends.less `@import '_custome.less';`, path: `app/design/frontend/Vendor/theme/web/css/source`
3. 
```
cd /var/www/html
rm -rf pub/static/*
rm -rf var/view_preprocessed/*
php /var/www/html/bin/magento cache:clean
php /var/www/html/bin/magento setup:static-content:deploy en_US ru_RU
php /var/www/html/bin/magento cache:clean
```

### Expected result

See new style for class "slider".

### Actual result

No changes were made.

**Comment by ryantfowler** [comment]
@Flamestyle when I do that it works fine, but I'm using a file named `_extend.less` not `_extends.less`. This may be your issue. Here's a [link](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_approach.html)
