### ISSUE TITLE
Logo email

### ISSUE THREAD

**Issue by magentochile** [magento/magento2#7985]
El logotipo no se puede crear, para la llegada de los correos. Uno sube la imagen, en Contenido/Configuración Configuración de Diseño, se elige el template y en la pestaña "Correos electrónicos transaccionales" uno sube el logotipo, lo guarda, todo ok y al volver a "Correos electrónicos transaccionales" la imagen sale con icono de no encontrado, uno hace clic sobre la imagen y envía una url inexistente en /pub/media/email/logo/stores/1/mi-logotipo.png y los correos siguen llegando con el logotipo de Magento default... ¿La solución? crear el directorio /pub/media/email/logo/stores/1/ y subir la imagen por ftp y listo! los correos llegan con mi-logotipo.png y en "Correos electrónicos transaccionales" ahora muestra mi-logotipo.png. Eso es un bug!

**Comment by pboisvert** [comment]
closing as duplicate of #6275 

this is already fixed and targeted against the 2.1.5 release for early next year

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
