### ISSUE TITLE
Magento 2.1.0 Error while working

### ISSUE THREAD

**Issue by vigneshkk07** [magento/magento2#7986]
### Preconditions

Magento 2.1.0 Error while working 

1. Magento ver. 2.1.0
2. Site Hosted in Amazon Web Server

![ss-error](https://cloud.githubusercontent.com/assets/19967832/21538032/8c0e2ed6-cdbe-11e6-80e6-a9a84c2726a8.JPG)

Sometime giving permission sudo chmod -R 777 /var/www/magento/public_html/subdirectory to the folder then its working fine. 

My store hosted in Amazon web server how to resolve this issue Permanently ?

what kind of error is it related to Amazon web server or Magento 2.1.0 ?

**Comment by veloraven** [comment]
@vigneshkk07 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you have issue with permissions please address them to your hosting provider. 
Please also check [Magento ownership and permissions in development and production ](http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_file-sys-perms.html)section of documentation.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
