### ISSUE TITLE
Typo in variable name: billingAddressFromData vs. billingAddressFormData

### ISSUE THREAD

**Issue by ekuusela** [magento/magento2#7988]
I don't know if this results in any errors but it certainly has the potential to cause some.

`billingAddressFromData` seems to be the one that is used:
https://github.com/magento/magento2/search?utf8=%E2%9C%93&q=billingAddressFromData&type=Code

`billingAddressFormData` is referred to only once: 
https://github.com/magento/magento2/search?utf8=%E2%9C%93&q=billingAddressFormData&type=Code

It seems that that variable deals with **form** data so maybe it (and `shippingAddressFromData`) should be renamed.

**Comment by veloraven** [comment]
@ekuusela thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
We have created internal ticket MAGETWO-63300

**Comment by arshadpkm** [comment]
I am in

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-68877

**Comment by magento-engcom-team** [comment]
Fixed by @arshadpkm Thank you
