### ISSUE TITLE
Paypal through braintree not working

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#7989]
Hello Guys,
I am stuck to make Braintree work on my site. Its in Magento 2.1.2.

I get below error on image.
![untitled-1](https://cloud.githubusercontent.com/assets/17259817/21538940/c18bff16-cdc3-11e6-8df8-d8b925148eeb.jpg)

Here is the response code from paypal.

/**/callback_jsonf681b2cfef1149fcba7de2aaece2fd72({"paymentResource":{"errorName":"VALIDATION_ERROR","errorMessage":"Invalid request - see details","errorDetails":[{"field":"transactions[0].itemList.shippingAddress","issue":"The combination of country and city is invalid"}],"debugId":"7a1630dfdba88","paypalHttpStatus":400},"status":422})

It seems the issue is with city and country combination but it just won't work.
Any help?

**Comment by dyushkin** [comment]
Hi @key-dev! Please check your combination of ZIP + State + City, maybe there is a problem. Based on your screenshot, is there any city Orlando in Georgia?

**Comment by key-dev** [comment]
Hi there, i uploaded that image because i had it first time saved as screenshot. But i have tried all actual addresses but no success. Braintree response below.

"I've checked the attempt you've listed below with Debug ID edb3b3ec17ca2. In our server logs I can see the error as CITY_FIELD_REQUIRED_FOR_COUNTRY.
The parameters I can see sent to us are countryCode=US​ and ​postalCode=32819​. Since the city was not included, this attempt received the mentioned error."

In my magento 2 checkout page there is clearly a City field and its mandatory, so i am confused why its not passing the City value.

**Comment by dyushkin** [comment]
Hi @key-dev! It seems this issue valid for 2.1.2 version, and [was fixed and merged](https://github.com/magento/magento2/issues/3789) in develop branch. Fix will be published in Magento 2.1.5 version, under internal issue MAGETWO-58914 commits. For now, you can use [this solution](https://github.com/magento/magento2/issues/3789#issuecomment-269442392) to solve your problem.

Thank you for reporting, feel free to reopen this ticket if problem still valid for you.
