### ISSUE TITLE
sorting of custom grid in product catalog edit not working

### ISSUE THREAD

**Issue by vijaybokka** [magento/magento2#7991]
sorting of custom product grid not working .I have created one new tab at product->catalog-> edit in admin side.it displays grid of my custom product details.sorting is not working if we create grid as a custom tab in product edit admin 

### Preconditions

1. magento 2.1,3 Community Edition,
2.xampp

### Steps to reproduce

1. create any custom grid in admin panel
2. add this grid as new tab in product->catalog->edit
3. try to search our custom grid

### Expected result

1. our custom grid should be sorted or searched 

### Actual result

1. [Screenshot, logs]
when click on sorting this console error i am getting and that loading symbol keep on going.this kind of error getting only if we add grid under the magento admin product->catalog->edit

grid.js:284 Uncaught TypeError: Cannot read property 'down' of null
    at g.bindFieldsChange (grid.js:284)
    at g.initGrid (grid.js:75)
    at g.initGridAjax (grid.js:89)
    at fire (jquery.js:3099)
    at Object.fireWith (jquery.js:3211)
    at done (jquery.js:9325)
    at XMLHttpRequest.callback (jquery.js:9720)
bindFieldsChange @ grid.js:284
initGrid @ grid.js:75
initGridAjax @ grid.js:89
fire @ jquery.js:3099
fireWith @ jquery.js:3211
done @ jquery.js:9325
callback @ jquery.js:9720
VM11057:2 Uncaught SyntaxError: Unexpected token <
    at http://localhost/Magento2.1/pub/static/adminhtml/Magento/backend/en_US/legacy-build.min.js:1:9075
    at Array.map (native)
    at String.evalScripts (http://localhost/Magento2.1/pub/static/adminhtml/Magento/backend/en_US/legacy-build.min.js:1:9042)
    at http://localhost/Magento2.1/pub/static/adminhtml/Magento/backend/en_US/legacy-build.min.js:1:5450
(anonymous) @ legacy-build.min.js:1
evalScripts @ legacy-build.min.js:1
(anonymous) @ legacy-build.min.js:1

![1](https://cloud.githubusercontent.com/assets/21173379/21541657/203568e4-cdde-11e6-8ff6-8cf00a1f1249.PNG)
![2](https://cloud.githubusercontent.com/assets/21173379/21541663/25fa7b20-cdde-11e6-9f2e-3e964057174b.PNG)

**Comment by veloraven** [comment]
@vijaybokka thank you for your feedback.
Please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): list steps instead of general description.
Please note that  Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html). 
Trash

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
