### ISSUE TITLE
checkout page is empty in magento 2

### ISSUE THREAD

**Issue by karthigesh** [magento/magento2#7992]
https://whosmellsgood.com/checkout/

after adding the product to cart, and went to checkout the checkout page is blank without any data. It even does not shows any error in developer mode with the display errors

I am using the default theme

**Comment by karthigesh** [comment]
i am using the default theme

**Comment by roseofgold** [comment]
I had this issue on 2.1.2 only to find out that 2 tables were missing from my install. checkout_agreement and checkout_agreement_stores. Check your log files on your server. They may tell you other information.

**Comment by veloraven** [comment]
@karthigesh thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by erfanimani** [comment]
@karthigesh , there are a couple issues with a symptom like this. Open up your developer console in Chrome and paste any javascript errors/warnings here.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by karthigesh** [comment]
Yes I got this issue corrected this is because if you does not set the weight for the products it will not give the shipping and it will become empty.
IF you set the product has weight option then the checkout page will show
