### ISSUE TITLE
Don't working template for field in checkout

### ISSUE THREAD

**Issue by springimport** [magento/magento2#7993]
### Preconditions
1. Set my templates for fields in checkout step 1.

### Steps to reproduce
1. Create `/app/design/frontend/Vendor/MyTheme/Magento_Checkout/layout/checkout_index_index.xml`.
2. Add `referenceBlock` from [documentation](http://devdocs.magento.com/guides/v2.1/howdoi/checkout/checkout_edit_form.html).
3. Change elementTmpl => template.

```xml
<item name="shippingAddress" xsi:type="array">
    <item name="children" xsi:type="array">
        <!-- The name of the form the field belongs to -->
        <item name="shipping-address-fieldset" xsi:type="array">
            <item name="children" xsi:type="array">
                <!-- the field you are customizing -->
                <item name="firstname" xsi:type="array">
                    <item name="config" xsi:type="array">
                        <!-- Assigning a new template -->
                        <!--
                        <item name="elementTmpl" xsi:type="string">%Vendor_Module%/form/element/%your_template%</item>
                        -->
                        <item name="template" xsi:type="string">Vendor_Checkout/form/field</item>
                    </item>
                </item>
            </item>
        </item>
    </item>
</item>
```

Templates (2 for testing...):
- `/app/code/Vendor/Checkout/view/web/template/form/field.html`;
- `/app/code/Vendor/Checkout/view/web/templates/form/field.html`.

### Expected result
1. New template.

### Actual result
1. Template from `Magento_Ui`.

JS from html page (`<script type="text/x-magento-init">`):
```json
"firstname": {
  "component": "Magento_Ui\/js\/form\/element\/abstract",
  "config": {
    "customScope": "shippingAddress",
    "customEntry": null,
    "template": "ui\/form\/field",
    "elementTmpl": "ui\/form\/element\/input",
    "tooltip": null
  },
  "dataScope": "shippingAddress.firstname",
  "label": "First Name",
  "provider": "checkoutProvider",
  "sortOrder": "20",
  "validation": {
    "required-entry": true,
    "max_text_length": 255,
    "min_text_length": 1
  },
  "options": [
    
  ],
  "filterBy": null,
  "customEntry": null,
  "visible": true,
  "value": "Mykhailo"
},
```

Problem place:
```json
    "template": "ui\/form\/field",
    "elementTmpl": "ui\/form\/element\/input",
```

`elementTmpl` - can change.
`template` - cannot change.

| Q | A |
| --- | --- |
| Magento version | 2.1.3 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by springimport** [comment]
I think I know what the problem with this. Go to `Magento\Checkout\Block\Checkout\AttributeMerger` line 173. You can see static value for `template`.

I'm not sure of the correctness, but below is my temporary solution:
```php
'template' => isset($additionalConfig['config']['template'])
    ? $additionalConfig['config']['template']
    : 'ui/form/field',
```

Now I try to solve this problem with plugin/[preference](https://gist.github.com/springimport/ef04a8441550145229250ec02ce3bdc1) and I wait bug fix for this.

**Comment by aakimov** [comment]
Hello @springimport 
Thank you for your report. This issue has been already reported by another community member (see https://github.com/magento/magento2/issues/7278) and we are aware of it.

This ticket will be closed as duplicate. Thank you for understanding and sorry for the response delay.
Regards,

**Comment by springimport** [comment]
@aakimov 
> Also I would like to provide some information that you can use as a work-around. Indeed, ui/form/field is hard-coded in \Magento\Checkout\Block\Checkout\AttributeMerger::getFieldConfig for all address attributes. 

Magento 2 devdocs:
> Rather than copy extensive page layout or page configuration code and then modify what you want to change, in the Magento system, you only need to create an extending layout file that contains the changes you want.

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-extend.html

I hope `AttributeMerger` is a temporary solution because it's a crutch.

**Comment by aakimov** [comment]
@springimport,
Yes, as I mentioned in the comment it is a 

> work-around

We will fix the issue with hard-coded *template* property in the future releases.
Regards,

**Comment by springimport** [comment]
@aakimov Thanks.
