### ISSUE TITLE
If you leave as default, shipping lines disappear

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7995]
### Preconditions
Upgraded from M2.1.2 to M2.1.3. Php 5.6

### Steps to reproduce
1.Go into Customer Screen to change the number of address lines required at checkout. Leave it blank for default of 2. 
2. Save
3. Clear Cache

### Expected result

1. there should be the default of 2 lines

### Actual result

1. At checkout there are no lines for street address.
<img width="1196" alt="leaveblanklines" src="https://cloud.githubusercontent.com/assets/21045500/21557742/986a6b32-cde5-11e6-90e9-2cc99428ecff.png">
<img width="1156" alt="missingshippingfield" src="https://cloud.githubusercontent.com/assets/21045500/21557743/986acac8-cde5-11e6-9665-541df53afaf2.png">

**Comment by veloraven** [comment]
@rosandrest thank you for your report
We have created internal ticket MAGETWO-62926

**Comment by magento-engcom-team** [comment]
@rosandrest, thank you for your report.
We've created internal ticket(s) MAGETWO-62926 to track progress on the issue.

**Comment by crissanclick** [comment]
I'm working on this issue at #MM17ES

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83278

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83284

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @rosandrest. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
