### ISSUE TITLE
Shipping Address Overwrites Billing Address in Checkout

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7996]
This isn't so much a bug as a huge usability issue

### Preconditions
upgraded from M2.1.2 to M2.1.3, PHP 5.6

### Steps to reproduce

1. Go to checkout
2. Enter a shipping address
3. Select shipping method
<img width="652" alt="shipping" src="https://cloud.githubusercontent.com/assets/21045500/21557971/3f50154e-cde8-11e6-8d8d-2d7e162205ec.png">
4. Uncheck box that says shipping and billing address are the same
5. Enter new billing address
6. Enter CC info
7. Hit Place Order Button
<img width="890" alt="canplaceorderbeforeupdating" src="https://cloud.githubusercontent.com/assets/21045500/21557972/3f52fe80-cde8-11e6-9564-f0e33ff3b2ed.png">
### Expected result

1. The billing address should be submitted to CC processor without the customer having to hit the update button or the place order button should not be live until the customer has hit the update button.

### Actual result

1. The shipping address overwrites the billing address unless the customer hits the UPDATE button before submitting order.  This is not intuitive and many of my customers have inadvertently written over their billing address with someone else's shipping address. These orders tend to be rejected by the CC processor as the shipping address was submitted instead of the billing address.

Order submitted with shipping address overwriting the billing address:
<img width="958" alt="braintree" src="https://cloud.githubusercontent.com/assets/21045500/21557970/3f4fa9ba-cde8-11e6-93eb-798e950d7ee4.png">

**Comment by smoskaluk** [comment]
@rosandrest Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by Ctucker9233** [comment]
@smoskaluk This is not a feature request! The OP clearly thinks it's a bug and shows clearly that the Billing address gets overwritten by the shipping address. Surely, this is not expected behavior. If it is, what is the rationale for doing that?

**Comment by magento-engcom-team** [comment]
@rosandrest thank you for your report.
The fix for this issue is already available in Magento 2.1.8.

**Comment by cralls** [comment]
I have a 2.2.3 instance where this is still an issue. When I click update the billing address overwrites the shipping address and my shipping calculations are changed based on the billing address instead of what I had selected for my shipping address in the previous step.
