### ISSUE TITLE
Saving a product in a store scope in the backend overwrites enable products "Use default value"

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#7998]
Just saving a product in the backend, when you have selected a store view, overrides the "Use default value" setting of the enable product attribute in the store view.

### Preconditions

1. Magento version 2.1.3
2. A product with "Use default value" for status set in store 1

### Steps to reproduce
1. In the magento backend select Products -> Catalog
2. Select the product
3. Select "Default Store View" as Store View
4. Save the product

### Expected result
1. "Use default value" is checked for "Enable Product"

### Actual result
1. "Use default value" is unchecked for "Enable Product"

**Comment by paalsoberg** [comment]
I've seen this in previous versions of 2.X as well

**Comment by ochnygosch** [comment]
I've discovered that this error was my fault. There was an active observer of a custom module that saved the product. This triggered the behavior described in issue #7879.
