### ISSUE TITLE
ImportExport module produces PHP strict notices

### ISSUE THREAD

**Issue by FiveDigital** [magento/magento2#80]
The ImportExport module especially the model `Mage_ImportExport_Model_Import_Entity_Product` is accessing non existing array keys without checking them first. This leads to a `system.log` full of `Notice: Undefined index`:

```
Notice: Undefined index: sku  in /app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php on line 1717
Notice: Undefined index: _type  in /app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php on line 1240
Notice: Undefined index: _type  in /app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php on line 1241
```

**Comment by dannyxm43** [comment]
_media_lable is still spelled incorrectly in the latest versions of CE and EE.

**Comment by art6495** [comment]
Hello,
I want to remove sku during  product import using csv in magento, Can you please check it??
