### ISSUE TITLE
the new config.php approach

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#800]
I've seen that in the latest alpha versions there is no more `local.xml`. Instead there is a `config.php` that contains the db credentials (and others).  
I've also seen that there is not more `active` attribute in the `module.xml` of every module. Instead this functionality was moved to the same `config.php` mentioned above.  
I see a possible issue with this approach.  
Since `config.php` contains the db credentials, this file is not going to be versioned, but the list of enabled/disabled modules should be versioned.  
In the current implementation, each time I create a new module and want to deploy it, after getting the code from the versioning system I have to manually edit the `config.php` file from the instance where I'm deploying to add declare my new module.  

How about putting the module list in a separate file `modules.php`?.. that can look like this:

```
return array (
    'Magento_Core' => 1,
    'Magento_Authorization' => 1,
    'Magento_Store' => 1,
    ....
 );
```

and in the `config.php` just get the modules like this: 

```
'modules' => require_once 'modules.php';
```

I know that the list of modules is generated on install. This means that in the approach I'm proposing, the setup script needs to check if `modules.php` exists. If it does, move along, if not create it.

Does this make sense?

**Comment by Vinai** [comment]
@antonmakarenko Since we have been in dev beta for a few weeks now, is there a command in the setup CLI tool to manage modules in the config.php file?

**Comment by buskamuza** [comment]
@Vinai , not yet. We were mostly working on bug fixing. But this task is one of the highest priority for us, so it should be available soon.

**Comment by alankent** [comment]
I was going to ask a question, but think I will turn it into a blog post so I can provide more background.

**Comment by Vinai** [comment]
Thanks!

**Comment by alankent** [comment]
https://alankent.wordpress.com/2015/01/08/configuration-settings-deployed-code-or-in-shared-store-quick-note/

**Comment by fooman** [comment]
to everyone who hasn't found it yet - this is now possible:
 
     php -f setup/index.php module-enable Namespace_Module

it updates the `app/etc/config.php` file for you and takes care of the correct order based on the sequence attribute in the `module.xml` file.

**Comment by djallits** [comment]
I am actually looking to leverage vlucas/phpdotenv to manage configurations through several environments. .env files should not be version controlled.
