### ISSUE TITLE
PUT API Call for Update gallery entry and change values of Types field of media image don't work correctly.

### ISSUE THREAD

**Issue by cristianmalfesi** [magento/magento2#8004]
**Problem description:**
When use PUT API calls for change "types" field on one image of product, thera are problems.
For exampe, If we want assing Types="Thumbnail" to image with ID 15 and there is other image in the same product that have alrady assigned "thumbnail" and this last image have higher ID, for example ID 19, then PUT action will not update Types field. In the opossite case, if we try assign "Thumbnail" to image with id 19 and image with ID 15 have assigned this type, PUT action will update them successful.
In resume, PUT media API Call apply change at types values only when ID of image is lower than ID image that have "Types" values assigned before.

### Preconditions
Magento 2
Version: 2.1.x (tested on 2.1.1 and 2.1.3)
EC2 Instance of AWS Amazon with CentOS
PHP v7.0.10
Mysql 5.6
Also was tested on local environment with Vagrant with CentOS.

### Steps to reproduce

1. Create with API new product with sku SUN001
2. Add 3 different images with API Call POST /V1/products/SUN001/media
3. Assing with PUT the Types value "images","small_image","thumbnail". Example:
PUT
{{base_url}}/rest/V1/products/sun-001/media/19
{
  "entry": {
    "id" : "19"
    "media_type": "image",
    "label": "image 3",
    "disabled": false,
    "position" : 0,
    "types": [
      "images",
      "small_images",
      "thumbnail"
    ]
    
  }
}
4. Try now assign types values to image with lower id in the same product, for example:
PUT
{{base_url}}/rest/V1/products/sun-001/media/15
{
  "entry": {
    "id" : "15"
    "media_type": "image",
    "label": "image 3",
    "disabled": false,
    "position" : 0,
    "types": [
      "images",
      "small_images",
      "thumbnail"
    ]
    
  }
}
5. When you check images at backend or with GET of product data at API call, you can see that image with ID 19 and ID 15 is not updated correctly. Image ID 19 keep types value without update.

### Expected result

1. We wait that image with lower ID get the types values assigned and image with higher ID be emtpy at Types field.

### Actual result

1. When you check images at backend or with GET of product data at API call, you can see that image with ID 19 and ID 15 is not updated correctly. Image ID 19 keep types value without update.

**Comment by Piquinikis** [comment]
+1

**Comment by kirkmadera** [comment]
Same. In 2.1.7 both "types" and "position" seem to have no effect. The last image imported shows up first and is marked as thumbnail, small_image, and image no matter what I set these to.

**Comment by ddeppner** [comment]
Would love to see a fix on this!  We need to be able to set "types" via API.

**Comment by magento-engcom-team** [comment]
@chm1975, thank you for your report.
We've created internal ticket(s) MAGETWO-81393 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @chm1975

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@chm1975 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by mhenkel1** [comment]
Problem still exists, it does not matter if the ID is smaller. You simply can not update the types property with the rest api.
It does nothing, you currently have to delete the image and reupload it...

Please reopen and fix this issue. Thank you :)

**Comment by s-oliver** [comment]
The issue apparently still exists, we're also having problem with this

**Comment by AGo444** [comment]
It's really an issue when you wnat to update images and cannot set the type. Please reopen this ticket,
