### ISSUE TITLE
Importing Currency Rates via Webservicex Fails

### ISSUE THREAD

**Issue by tsmith1985** [magento/magento2#8006]
Trying to import exchange rates via Webservicex fails for most rates and results in error messages saying that the service was unable to retrieve the rates.

### Preconditions

- Magento CE v2.1.3
- PHP v7.0.14
- MySQL v14.14 Distrib 5.7.16, for osx 10.12

### Steps to reproduce
1. Log into Admin 
2. Navigate to `Stores > Settings > Configuration > General > Currency Setup`
3. Select `Use system value` for `Base Currency` #8003 
4. Select `Yes` for `Enabled` in the `Scheduled Import Settings` section 
5. Click `Save Config` if necessary and flush the cache
6. Navigate to `Stores > Currency > Currency Rates`
7. Try to import rates via Webservicex

### Expected result
1. The rates should imported successfully

### Actual result
![webservicex_errors](https://cloud.githubusercontent.com/assets/582928/21574671/f787e538-ceab-11e6-96e7-771cd6ed5451.png)

**Comment by veloraven** [comment]
@tsmith1985 thank you for your report.

I was not able to reproduce this issue. I either get the result from #8003 when values are not imported at all, or I get all the values imported.
Can you please check this case once more, if it still reproduces? As it possible that there was some issue on Webservicex  side.

If it does, please provide additional Information:
* Was it clear Magento install or upgrade from some previous version?
* What settings did you use for Scheduled Import Settings?
* Could you provide full description of your currency settings? As I can see from the screenshot there was some trouble with all currencies except Euro and Pounds.

**Comment by hostep** [comment]
@tsmith1985 & @veloraven: it probably is just the external service Webservicex which was down at that time.
I've seen it happen from time to time over the last few years in Magento 1 (where Webservicex is the only service) in Magento 2, luckily there are some alternatives which you can use, I don't really trust Webservicex any longer based on my past experience with it.

So this doesn't look like a Magento issue, but just an issue over at the external Webservicex project.

**Comment by paales** [comment]
Internal advise to customers is to move away from Webservicex and move to Yahoo finance/fixer.io.

**Comment by magento-engcom-team** [comment]
Thank you @hostep  and @paales  for suggestions
