### ISSUE TITLE
M2.1.3 Add to cart bug not completely fixed

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#8007]
When the customer is logged into their account this message is still showing in wrong places.
Steps to reproduce:
1. Use Chrome browser
2. Log into account
3. Add item to cart
4. Proceed to first step of checkout
5. Press Luma logo to go to homepage
![addtocart](https://cloud.githubusercontent.com/assets/10808588/21575611/77649c28-cf66-11e6-952e-23b7bd661eac.jpg)

**Comment by veloraven** [comment]
@bondimedical3 thank you for your report.
I was not able to reproduce this issue.
Could you please provide more information?
* about type of the product added to the cart,
* detailed steps how you logged in and added the product,
* was it clear install or upgrade from some previous version

**Comment by bondimedical3** [comment]
Can you tell me which version of Chrome you used?

**Comment by bondimedical3** [comment]
The issue you are referencing is for an older version of Magento.

Why has this been closed when the bug has not been corrected?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
As there was no answers in responses I'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
