### ISSUE TITLE
Insert Widget in Product Description

### ISSUE THREAD

**Issue by gputignano** [magento/magento2#8008]
This is not a bug but a proposal. Add the ability to insert a widget in the product description for example the link to a page or other product. Static links doesn't update if I change destination url.

**Comment by veloraven** [comment]
@gputignano thank you for your submission.
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by gputignano** [comment]
Ok, I inserted the feature request in the forum. Many thanks.

**Comment by veloraven** [comment]
@gputignano thank you for update!
I will close this issue now.
