### ISSUE TITLE
Magento 2.1.3 Price of simple products does not update with configurable product after adding related/upsell products

### ISSUE THREAD

**Issue by martijnhovinga** [magento/magento2#8010]
I created a configurable product 'Baby bottle 125ml' which is available in a 1-pack or a 2-pack. So I have 2 simple products, each with different price. The attribute is 'units' (1 or 2 bottles per pack). Switching between 1 or 2 units works fine, as in https://babyfair.com.sg/natural-baby-bottle-125ml.html
However when I add a related product or cross-sell product to the configurable product, the price does not change anymore when I change 'units'.

### Preconditions
Magento 2.1.3
### Steps to Reproduce
Create configurable product with text swatch based on attribute 'units' (i.e 1 piece or 2 pieces per pack)
Create 2 simple products with different price 17.90 for 1 unit and 31.90 for 2 units. using 'text swatch' unit attribute
add any Related/Cross-sell/Upsell product to this configurable product
### Expected Result
Price change in front-end when selecting different options > CORRECT (1 unit cost $17.90, 2-pack $31.90)
### Actual Result
NO PRICE CHANGE  when selecting different options and price remains $17.90

**Comment by veloraven** [comment]
@martijnhovinga thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by martijnhovinga** [comment]
To reproduce:
- Magento 2.1.3
- Create configurable product with text swatch based on attribute 'units' (i.e 1 piece or 2 pieces per pack)
- Create 2 simple products with different price 17.90 for 1 unit and 31.90 for 2 units. using 'text swatch' unit attribute

Scenario 1 (without adding related products):  Check price change in front-end when selecting different options > CORRECT (1 unit cost $17.90, 2-pack $31.90)

Scenario 2: Now add any Related/Cross-sell/Upsell product to this configurable product 
Check price change in front-end for respectively 1 and 2 units > NO PRICE CHANGE and price remains $17.90 (expected result: different price per product as in scenario 1)

**Comment by martijnhovinga** [comment]
Probably related issue: pictures of configurable product : does NOT change AFTER adding related product.

To reproduce:

Magento 2.1.3
Create configurable product an attribute (I selected 'dropdown)
Create 2 or more simple products with same price and different image.
Scenario 1 (without adding related products): subsequently select different simple products from drop down and the image will change accordingly
Example: https://babyfair.com.sg/bumwear-one-size-cloth-diaper.html

Scenario 2: Now add any Related/Cross-sell/Upsell product to this configurable product.
Subsequently select different simple products from drop down and the image will NOT change anymore

**Comment by martijnhovinga** [comment]
@veloraven: Any update on this? Basically when adding 'related products' the whole functionality of configurable products is disrupted.

**Comment by martijnhovinga** [comment]
@veloraven @antboiko what is the status? Cross and up-selling is not possible when this is not solved.

**Comment by benjamin-garnier** [comment]
Hello, 
I'm having the same issue. 
When I create a configurable product, everything works fine, the normal price / special price are updated with the option selected for the product, but when we add related products to the configurable, the price no longer takes the values of the options...

**Comment by martijnhovinga** [comment]
Hi @antboiko , what is the status? One of the key features should be to up-sell and cross-sell, Obviously it doesn't work with configurable products at the moment.

**Comment by magento-engcom-team** [comment]
@martijnhovinga, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
