### ISSUE TITLE
Strip Tags from attribute

### ISSUE THREAD

**Issue by gputignano** [magento/magento2#8011]
### Steps to reproduce

1. Create a new attribute ad Dropdown field
2. Set Allow HTML Tags on Storefront to Yes
3. Create a new value for attribute Attribute including tags (<a href="attribute-name">Attribute Name</a>)
4. Insert in a page a new widget Catalog Product List. In conditions select Attribute is Attribute Name

### Expected result

1. I expect in the list the value "Attribute Name"

### Actual result

1. I get "<a href="attribute-name">Attribute Name</a>"
![attribute](https://cloud.githubusercontent.com/assets/77434/21578372/b228944c-cf7d-11e6-9c5d-c9d0101d8f74.png)

**Comment by veloraven** [comment]
@gputignano than you for your report.
Please, identify which version of Magento you are running.

**Comment by gputignano** [comment]
@veloraven Magento v2.1.3

**Comment by veloraven** [comment]
Internal ticket MAGETWO-63012

**Comment by magento-engcom-team** [comment]
@gputignano, thank you for your report.
We've created internal ticket(s) MAGETWO-63012 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
@gputignano We are closing this report now, as issue has been fixed in the `2.2-develop` branch now. This fix will be released with the next functional patch release for the 2.2 release line.
Thank you.
