### ISSUE TITLE
WYSIWYG Editor does not work properly after disabling by default

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#8012]
### Preconditions
1. PHP 5.6.29 (cli) (built: Dec  9 2016 07:40:09)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.7, Copyright (c) 2002-2016, by ionCube Ltd.
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
2. mysql  Ver 14.14 Distrib 5.6.35, for Linux (x86_64) using  EditLine wrapper
3. Magento 2.1.3 Developer Mode

### Steps to reproduce
1. Disable Enable WYSIWYG Editor by default 

### Expected result
1. Enable WYSIWYG Editor works without issues and saved changes with editor reflect on frontend

### Actual result
1. Editor breaks and loses functionality, also changes in frontend do not reflect and are not saved I am assuming sometimes: https://www.screencast.com/t/UYQ3fqOYvm

**Comment by veloraven** [comment]
@GlobalOutsourcing thank you for your report.
However I was not able to reproduce this issue.
Could you please add more information?
1. Describe detailed steps: what exact actions do you do.
2. Describe actual result in more details: which functionality is lost, which changes are not shown on frontend?
3. Is it clear install or upgrade from some previous version?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
