### ISSUE TITLE
Animation images are not showing animation on frontend product details page.

### ISSUE THREAD

**Issue by gauravkhatri99** [magento/magento2#8015]
I have upload a gif image for a product that is showing 360 view of product, after uploading it is working in backend. 
![backend](https://cloud.githubusercontent.com/assets/12871787/21587654/c2081ba2-d104-11e6-8df5-354455e489c0.png)

When I go to frontend on product details page it is not working I mean it is not showing its animated view. 
![frontend](https://cloud.githubusercontent.com/assets/12871787/21587655/c20b147e-d104-11e6-8de4-149e50cd1116.png)

Please help to solve this issue?

.

**Comment by veloraven** [comment]
@gauravkhatri99 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by rav-redchamps** [comment]
@gauravkhatri99 

The native Magento 2 system remove the animation of GIF image when it resize's it. We at RedChamps developed an extension to add this missing support. 

The extension can be found here 

https://redchamps.com/product-animated-gif-images-magento-2-extension.html

P.S. All the downvotes are because the extension is paid.

**Comment by bartoszkubicki** [comment]
Still an issue on 2.4.3-p1
