### ISSUE TITLE
Magento 2 Installation: css/js/images not loading in php-fpm + nginx server

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#802]
I am trying to install Magento2(0.1.0-alpha107 ) in my localhost powered by OSX 10.10 + brew installed php-fpm + mysql + nginx.
Steps that I followed for installation:

``` sh
 $ mkdir /path/to/magento2 && cd /path/to/magento2
 $ git clone git@github.com:magento/magento2.git .
 $ composer install
 $ cd setup
 $ composer install
 $ php -f index.php install --base_url=http://magento2alpha.dev/ --backend_frontname=admin --db_host=localhost --db_name=magento2alpha --db_user=root --db_pass=root --admin_firstname=Raj --admin_lastname=KB --admin_email=magepsycho@gmail.com --admin_username=admin --admin_password=pass123 --language=en_US --currency=USD --timezone=America/Chicago
```

So far everything worked great. But when you load the frontend: http://magento2alpha.dev/ it's showing plain text only (i.e. css/images/js are missing).

View source gives you the path like http://magento2alpha.dev/pub/static/frontend/Magento/blank/en_US/[css/images]/[css/images file] which led to the 404 page
My nginx conf file looks like:

```
server {
    listen 80;
    server_name magento2alpha.dev;
    root /Users/Raj/Sites/magento/magento2alpha;

    location /setup {
        try_files $uri $uri/ @setuphandler;
    }

    # Rewrite Setup's Internal Requests
    location @setuphandler {
        rewrite /setup /magento/magento2alpha/setup/index.php;
    }

    location / {
        index index.php index.html;
        try_files $uri $uri/ @handler;
    }

     # Rewrite Internal Requests
     location @handler {
        rewrite / /magento/magento2alpha/index.php;
     }

     # Rewrite magento2 static files
     #location /pub/static {
     #   rewrite ^/pub/static/(.*)$ /magento/magento2alpha/pub/static.php?resource=$1? last;
     #}

     location /pub/static {
          try_files $uri $uri/ @static;
     }

     location @static {
           rewrite ^/pub/static/(.*)$ /magento/magento2alpha/pub/static.php?resource=$1? last;
     }

     #location ~ .php/ {
     #    rewrite ^(.*.php)/ $1 last;
     #}

    location ~ \.php$ { ## Execute PHP scripts
        try_files $uri =404;
        expires        off;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_read_timeout 900s;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;

        ## Magento 2 Developer mode
        fastcgi_param MAGE_MODE "developer";
    }
}
```

I guess the issue lies in the static files rewrite. But this is what I followed from the github which is not working. Is there any workaround?

**Comment by uchsarath** [comment]
I am using Ubuntu 14.04, after typed my virtualhost domain, magento.dev, then it show blank. Lolzz, there is no any error on Nginx log

**Comment by mazhalai** [comment]
@uchsarath  This issue has been closed and marked as resolved. If it does not solve your issue, please open a new issue. Also, please include what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) magento 2 is running on?

**Comment by LiamKarlMitchell** [comment]
Not working.

**Comment by LiamKarlMitchell** [comment]
I was able to compare a working site with a non working site.

There was extra cruft in the url values in core_config_data.

UPDATE core_config_data SET value = NULL WHERE path IN ('web/unsecure/base_static_url','web/unsecure/base_media_url','web/secure/base_static_url','web/secure/base_media_url');


All of these needed to be NULL.
```
web/unsecure/base_link_url | {{unsecure_base_url}} 
web/unsecure/base_media_url | {{unsecure_base_url}}pub/media/ 
web/unsecure/base_static_url | {{unsecure_base_url}}pub/static/
web/secure/base_link_url | {{secure_base_url}} 
web/secure/base_media_url | {{secure_base_url}}pub/media/ 
web/secure/base_static_url | {{secure_base_url}}pub/static/ 
```

Resolved it for me.
