### ISSUE TITLE
Fresh install on shared server fault: Warning: is_dir(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by lucvdbos** [magento/magento2#8021]
Hi All,

Just installed magento 2.1.3 on my shared server using putty with the following command:

composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition public_html

php bin/magento setup:install --base-url=https://xxx.eu --db-host=localhost --db-name=dbname_basis --db-user=dbuser_db --db-password=Tuink@ --admin-firstname=FirstName --admin-lastname=LastName --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --use-secure=1  --use-secure-admin=1 --admin-use-security-key=1 --backend-frontname=admin --cleanup-database --magento-init-params=“MAGE_MODE=developer”

So far everything went well. But logging in at the admin I get an error after logging in. 

a:4:{i:0;s:324:"Warning: is_dir(): open_basedir restriction in effect. File(/etc/pki/tls/certs) is not within the allowed path(s): (/home/lucvdbos/:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/) in /home/lucvdbos/domains/annarockmilano.eu/public_html/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 914";i:1;s:8901:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'is_dir(): open_...', '/home/lucvdbos/...', 914, Array)

How to solve this?

**Comment by hostep** [comment]
See: https://github.com/magento/magento2/issues/4359#issuecomment-225115951

**Comment by lucvdbos** [comment]
Thanks, 

For anyone else stuck here after upgrading to 2.1, @hostep solution to

`"composer/composer": "@alpha"`
to:
`"composer/composer": "1.1.2 as 1.0.0-beta1"`
works great but required a 

` composer  update` (SSH) afterward.

**Comment by veloraven** [comment]
I'm closing this issue as it was solved.

**Comment by insaurabh** [comment]
I did
 "composer/composer": "@alpha"
to:
"composer/composer": "1.1.2 as 1.0.0-beta1"

but when i run composer update i got another error as in image.

![4e698a19d7c69730dda4031039021b174b35069696dcb59950 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/26545067/25378562/0ff0d194-29c8-11e7-833d-3442e7b62087.png)

**Comment by hostep** [comment]
@maddyBoy, see the documentation: http://devdocs.magento.com/guides/v2.1/install-gde/prereq/integrator_install_ce.html
> When prompted, enter your [authentication keys](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/connect-auth.html). Your public key is your username; your private key is your password.
