### ISSUE TITLE
"Use default value" checkbox of price attribute not displaying the correct value

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#8023]
The "Use default value" checkbox of the price attribute of a product is always unchecked in a store view.

### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Enable website scoped prices in Stores -> Configuration -> Catalog --> Catalog
2. Create a new product with a price
3. Edit the product
4. Select "Default Store View" in Store View

### Expected result

1. The checkbox "Use default value" of the price attribute should be checked as there is no website specific entry set in the database

### Actual result

1. "Use default value" checkbox of the price attribute is unchecked

**Comment by veloraven** [comment]
@ochnygosch thank you for your report.
We have created internal ticket MAGETWO-62923

**Comment by drazulay** [comment]
Any news on this? We still have this issue on Enterprise 2.1.6.

**Comment by misha-kotov** [comment]
The checkbox under the price fields refers to whether or not the value is inherited from the "all store views" scope value (store id=0). If the value is taken from the website scope, the checkbox will be unchecked. When you change the price on a store view level, it changes the value that is stored on the website level, and all other store views under the same website will update to the same value.

**Comment by magento-engcom-team** [comment]
Hi @ochnygosch the internal ticket has been closed as Not a Bug (based on PO decision) 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue or if you would like to change some business flow or feature

**Comment by BenGlassAtlas** [comment]
@magento-engcom-team How is this not a bug when a duplicate ticket has been opened which has the labels of reproduced on 2.1 and 2.2? https://github.com/magento/magento2/issues/9486

I can also reproduce this across several environments:

![price](https://user-images.githubusercontent.com/8895777/31808895-31f67aba-b56d-11e7-89d2-faaaf73c0462.gif)

**Comment by johnniecoder2046** [comment]
for @BenSpace48 problem ,

seems to related to 

https://github.com/magento/magento2/blob/2.1/app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/ConfigurablePrice.php#L64-L67
