### ISSUE TITLE
Order with conf product with custom options is not placed using Auth. NET Direct Post

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#8028]
### Preconditions

1. M 2.1.2, installed using Wizard
2. PHP 5.6, MySQL 5.6

### Steps to reproduce

1. Create configurable product with custom option
2. Go to product page, add it to cart with filled custom option
3. Go to checkout page, choose Credit Card Direct Post (Authorize.net) payment method
4. click Place Order

### Expected result

1. Order should be placed

### Actual result

1. popup with error "An error occurred on the server. Please try to place the order again." appears.
2. If I comment out try/catch  in \vendor\magento\module-authorizenet\Controller\Directpost\Payment\Place.php in method placeCheckoutOrder(), here is part of stacktrace of the error:
![image](https://cloud.githubusercontent.com/assets/10142848/21640307/96fd485e-d27d-11e6-86e3-0d92cd6a6058.png)
3. I didn't notice this error for simple product with custom options, only for configurable  (may also be for all composite product types)

**Comment by YevSent** [comment]
Hi @katesuykovskaya, thanks for reporting. This is known issue (internal ticket MAGETWO-56695) and already fixed on the develop branch.

The fix will be available in Magento 2.1.4.

Also, to use Authorize.net you need to use a  server with public domain or IP, this payment won't work on  a local machine.

Closed as duplicate to https://github.com/magento/magento2/issues/5938.
