### ISSUE TITLE
Magento 2 product url issue with multiple store

### ISSUE THREAD

**Issue by avanish512** [magento/magento2#8029]
Hi,

Anyone can help me to fix Magento 2 Product URL issue with multiple stores.

like: - Some product URL is good and some have URL "catalog/product/view/id/121/s/compartment-organizer/". Also, I have re-index Magento but there no any impact on product URLs

If anyone can help me to fix this issue that would be great for me.

Thanks

**Comment by korostii** [comment]
This generally seems like an issue more appropriate to the [forums](https://community.magento.com/)
If you're sure it's a bug and not a misconfiguration, you probably should provide more details about your application setup (magento, PHP, apache version etc.)

Anyway, if I were to guess: have you checked whether you have the mod_rewrite enabled?

**Comment by veloraven** [comment]
@avanish512 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
