### ISSUE TITLE
Archiving Yearly Sales

### ISSUE THREAD

**Issue by asim-vax** [magento/magento2#8030]
To whom it may concern,

As our data grows(over 5 years worth of sales data) our sales_order (sales_flat_order table in M1) table is exponentially growing - trying to run queries against this is becoming slower. Is there a development path for something like sales_order_2014, sales_order_2015 or any sort of archiving of older data?

Thanks,

Alex

**Comment by pboisvert** [comment]
this Github is for M2 issues. Your report appears to be against M1

**Comment by asim-vax** [comment]
@pboisvert I was asking if there was a plan for something like this in M2? We are in the process of moving our site over from M1 to M2, and there is a huge amount of data in the table
