### ISSUE TITLE
Missing locale timezone Atlantic/Azores

### ISSUE THREAD

**Issue by joaocosta-azores** [magento/magento2#8032]
Hello,

I'm using magento 2.1.3.
It's missing Atlantic/Azores locale timezone. I can't find in backend at stores -> settings-> configurations -> General -> Locale Options -> Timezone.

[http://php.net/manual/en/timezones.atlantic.php](http://php.net/manual/en/timezones.atlantic.php)

**Comment by veloraven** [comment]
@jonnydevv thank you for your feedback.
I checked with ver. 2.1.3 and I can see it as Azores Standard Time (Atlantic/Azores).
If you still do not see this value please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Also please specify if it was clear install or upgrade from some other version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
