### ISSUE TITLE
Magento 2 Internet explorer 11 the cart page image loading keep on spinning without hiding.

### ISSUE THREAD

**Issue by vpiyappan** [magento/magento2#8033]
### Preconditions

1.  Magento 2 website.
2.  IE 11 or Laterst version of Browser 

### Steps to reproduce

1.  Open Magento 2 website in IE Browser. Add product to cart.
2. Navigate to Cart page.
3. Loader image will keep on spinning.

### Expected result

1. The Loader image should disappear after the estimated shipping cost loaded.

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/11790408/21644654/81622410-d2b4-11e6-9356-b407a50c5a17.png)

**Comment by korostii** [comment]
Tried to reproduce on a M2 instance, with success (to my surprise).
You should've probably mention the extra step: clicking on "Estimate Shipping and Tax".
And here's what I got in console, probably related:
![shopping cart - internet explorer 2017-01-06 10_26_22](https://cloud.githubusercontent.com/assets/24894168/21712073/349592d2-d3fb-11e6-9d45-0f0483a9614b.png)

**Comment by vpiyappan** [comment]
Hi,

Thank for your Help.

I don't see any error message like what you attached above. But the loader spinning for me. Could you share what theme your using to reproduce the issue and "cart page" screenshot to me.

**Comment by santoshkverma212** [comment]
thanks

**Comment by antbates91** [comment]
I can also confirm this is an issue on Magento CE 2.1.1, 2.1.2 and 2.1.3.

Using @vpiyappan steps to reproduce

1. Open Magento 2 website in IE Browser. Add product to cart.
2. Navigate to Cart page.
3. Loader image will keep on spinning.

I get the same error `Object doesn't support this action`.
The error happens on the window's dispatch event.
```
shippingService.getShippingRates().subscribe(function () {
                    window.dispatchEvent(new Event('resize'));
                });
```

**Comment by quienti** [comment]
Duplicate https://github.com/magento/magento2/issues/7051

**Comment by antbates91** [comment]
I believe this is the fix for the issue here. https://github.com/magento/magento2/commit/f3d7952805c7b5adc9b47c4d979c49e547a0772e

**Comment by vpiyappan** [comment]
@antbates1991 

Thank you very much your solutions works fine, much appreciated. 

You saved my day.

**Comment by adwivedigit** [comment]
> Tried to reproduce on a M2 instance, with success (to my surprise).
> You should've probably mention the extra step: clicking on "Estimate Shipping and Tax".
> And here's what I got in console, probably related:
> ![shopping cart - internet explorer 2017-01-06 10_26_22](https://cloud.githubusercontent.com/assets/24894168/21712073/349592d2-d3fb-11e6-9d45-0f0483a9614b.png)

Got that same issue in console using version 2.2.6
