### ISSUE TITLE
bin/magento commands not working after upgrade from V2.0.5 to V2.1.2 using composer

### ISSUE THREAD

**Issue by malikt** [magento/magento2#8036]
Recently I upgraded the magento 2 site, from Version 2.0.5 to 2.1.2, using composer, I updated composer.json as below
```
"name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.1.2",
        "composer/composer": "@alpha"
    },
```
and then used the following command:
`composer update`
It all went fine, composer removed and upgraded each component, when it was done. I deleted var files and used following command to upgrade database:
`php bin/magento setup:upgrade`
 but does nothing.

### Preconditions
1. PHP 7.0.13
2.  MySQL 5.6.34
3. Magento V 2.0.5

### Steps to reproduce

1. update composer.json by replacing 2.0.5 with 2.1.2
2.  run `composer update`
3. run command `php bin/magento setup:upgrade`

### Expected result
1.  Should run the commands to upgrade the database

### Actual result

1. The commands just do nothing and show no error nor proceedings but just new line as in attached screenshot below:
![commadsdonothing](https://cloud.githubusercontent.com/assets/24920883/21652915/85559ffe-d2d0-11e6-93bb-061dcf8f090a.PNG)

**Comment by korostii** [comment]
The steps you mention seem okay and usual at a first glance.
Just in case it's simpler than it seems: if the magento is in production mode and you've also cleared var/di and var/generation folders, then I think you might also need the following command
`php bin/magento setup:di:compile`
Also, not showing any error whatsoever is also suspicious.  try running it with maximum verbosity:
`php bin/magento setup:upgrade -vvv`

**Comment by jpratt** [comment]
Same issue happening to me as well. Running an upgrade and once complete, no output from command line. Have tried to clearing var/di and var/generation, and running setup:di:compile. Still get nothing. Also running setup:upgrade -vvv still shows no output.

**Comment by malikt** [comment]
I managed to resolve it, My server has both `php 5 `and` php 7` installed,I need php 5 for other sites and by default php 5 was in action, in M2's 2.0.5 it was ok but in latest v2.1.2, php 7 was required, so i had to put the complete path of php7 to get these commands work, e.g.
`/wamp64/bin/php/php7.0.10/php bin/magento setup:upgrade`
for now its fine for me but to shorten this php7 path, i will try to add it in environmental variables with different name so it becomes just `php7`

**Comment by jpratt** [comment]
@malikt I checked that as well. I have 5.6.27 running in CLI. And the docs here say it should work with php 5.6.5+ http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html

**Comment by malikt** [comment]
were you facing the issue exactly the screenshot i shared above? If yes, try to add complete path of php5.6.27 in commands.

**Comment by veloraven** [comment]
Closed as the issue was solved by the author.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by mohsinahmed22** [comment]
Same issue happens with me  on upgrade of 2.1.5 to 2.2.5 ...
