### ISSUE TITLE
Low priority: magento/magento-composer-installer module uses a non-existing composer class

### ISSUE THREAD

**Issue by hostep** [magento/magento2#8037]
### Preconditions
1. Magento CE 2.1.3
2. PHP 7.0.14

### Steps to reproduce
1. Install [phpstan](https://github.com/phpstan/phpstan#installation) in some directory
2. Let it analyze a vanilla Magento CE 2.1.3 installation:
`/path/to/phpstan/vendor/bin/phpstan analyze -l 0 /path/to/magento`

### Expected result
1. phpstan should run fully

### Actual result
1. phpstan execution stops due to a PHP class which no longer exists:
```
PHP Fatal error:  Class 'Composer\Command\Command' not found in /path/to/magento/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Command/DeployCommand.php on line 21
```

### Discussion
I just ran into that phpstan project, and as an experiment, I tried running it on a Magento installation, just for fun, see what it reported.
But the execution stops, because it finds a class `Composer\Command\Command` being used in the [magento/magento-composer-installer](https://github.com/magento/magento-composer-installer/blob/46a376fd2bdae5c1dfe6c18a7bd010a711066418/src/MagentoHackathon/Composer/Magento/Command/DeployCommand.php#L21) project, which no longer exists as of [composer version 1.0.0-beta1](https://github.com/composer/composer/commit/692a3ed300daaede8f4fcf4176eb8ca2048c6d87), it should be replaced with `Composer\Command\BaseCommand`

I'm pretty sure the code in the `DeployCommand.php` file is never executed in Magento 2, but it would still be nice if this could get cleaned up.

So this is very low priority, but I guess I should mention it anyways.

**Comment by ondrejmirtes** [comment]
Hi, author of PHPStan here :) PHPStan can sometimes stumble upon code that is broken like this. It probably means that the code is old and is not used at all. So one option is to fix this code, but maybe you can use this as a feedback that the broken code should be removed.

Also, to be able to perform the full analysis and print found errors, you can exclude this broken file from the analysis so that it can be finished.

**Comment by ioliinyk** [comment]
Hey @hostep, did you try this solution?

**Comment by hostep** [comment]
@ioliinyk: you mean if I tried to fix Magento's code, by removing that outdated code? Should I create a PR?
I'm not sure what you mean with your question to be quite honest :)

**Comment by magento-engcom-team** [comment]
Hi @hostep 
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by ondrejmirtes** [comment]
@magento-engcom-team I believe this is a technical issue. The OP is trying to improve Magento code itself.

**Comment by VishalParkash** [comment]
Did anyone find the solution to this issue?
