### ISSUE TITLE
Comment about VAT number displayed under different field in Customer Configuration

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#804]
Comment "To show VAT number on frontend, set Show VAT Number on Frontend option to Yes." is displayed under "Enable Automatic Assignment to Customer Group" field in System -> Configuration -> Customers -> Customer Configuration.

It should be displayed under "Show VAT Number on Frontend" field.
![screenshot 2014-12-14 15 50 36](https://cloud.githubusercontent.com/assets/727413/5428653/8b26d52e-83cc-11e4-8e2a-698f2afc2ef5.png)

**Comment by vpelipenko** [comment]
Thank you for reporting this issue. It is addressed to assigned PO.

**Comment by choukalos** [comment]
Tracking in internal ticket - MAGETWO-32869; will close this github issue out when internal ticket is closed.

**Comment by vpelipenko** [comment]
The issue is fixed and will be delivered in the next update.

**Comment by vpelipenko** [comment]
@wojtekn, suggested update is implemented and available from 0.42.0-beta7. Please, check the latest version.

**Comment by vpelipenko** [comment]
Fixed. Closed.

**Comment by wojtekn** [comment]
Thanks @vpelipenko, it looks good now.
