### ISSUE TITLE
Feature Request - AMP

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#8040]
Google is making a big push with AMP pages in mobile search results. I am seeing more and more AMP results in SERPS and I believe if Magento would like to keep a competitive edge in the market it will need to begin to look at adding this feature to Magento 2. Google SERPs are constantly changing with new features and they have even added an AMP carousel in mobile results where if there are more than 3 AMP results on the first page a carousel appears on the top where people can scroll through. In the future this will become a necessity for all e-commerce platforms. https://www.ampproject.org

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-AMP/idi-p/56765).
