### ISSUE TITLE
When i enabled the production mode also cache management, after that customer session is not working perfect. Like when i logged in as customer and go to category page customer session is not there but when i go to my account page it is there.

### ISSUE THREAD

**Issue by parthpatel147** [magento/magento2#8043]

**Comment by cmuench** [comment]
Wow. What a title. And no description.

**Comment by veloraven** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
