### ISSUE TITLE
Adding order/dependency to my custom indexer

### ISSUE THREAD

**Issue by rramiii** [magento/magento2#8044]
### Preconditions
1. Magento 2 is installed and running fine

### Steps to reproduce
1. add your custom indexer to magento 2 and it's running fine

### Expected result
1. to be able to give my custom indexer an order to run after/before some other indexer just like layout updates or the best is adding dependency on other indexer to force the other indexer to run before my custom one. 

### Actual result
1. not able to find a proper way to add order to an indexer in indexer.xml file, can this be added in future? sense sometimes order is important and will make developer life easier.

**Comment by veloraven** [comment]
@rramiii thank you for your submission. 
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
