### ISSUE TITLE
customer_login and customer_logout events on wrong area

### ISSUE THREAD

**Issue by phoenix128** [magento/magento2#8050]
`Magento_Checkout/etc/frontend/events.xml` should be moved to `Magento_Checkout/etc/global/events.xml`.

If you try to perform a login via **WEB API**, `customer_login` and `customer_logout` will not trigger `Magento\Checkout\Observer\LoadCustomerQuoteObserver` and `Magento\Checkout\Observer\UnsetAllObserver`.

This will cause an inconsitency in the `quote` table and current quote without `customer_id` association.

Steps to reproduce:
1. Log-out if you are logged-in
2. Create a cart
3. Login via AJAX

Expected result:
1. Old guest cart removed from `quote` table

Actual result:
1. A new `quote` will be created in `quote` table with `customer_id` set to null

**Comment by veloraven** [comment]
@phoenix128 thank you for your feedback.
Please specify exact Magento version you are running.
Please also provide exact Web API requests you are using.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
