### ISSUE TITLE
Update image on color swatches (size+colour)

### ISSUE THREAD

**Issue by noindie** [magento/magento2#8051]
Hello,

I am trying to setup a product with colour visual swatches and size (text swatch) , is it possible to update the image on just selecting the colour? It works only after I select the size too

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qUenf.png

Magento 2.1.3

thanks

**Comment by noindie** [comment]
Looks like a js error causing this, maybe Cannot read property 'oldPrice' of undefined #7959
Anyone can confirm? any way to fix it?

**Comment by veloraven** [comment]
@noindie thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by ashsmith** [comment]
@noindie I came across this issue, see #7959 I added an comment on how I've resolved.

**Comment by noindie** [comment]
yes, I only solved removing the lines you refer to.
Your solution does not fit my situation. I am using 2.1.3 with ultimo theme.

thanks

**Comment by veloraven** [comment]
@noindie if you are looking for discussion or an advice, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as GitHub issue tracker is intended for technical issues only.
If you want this issue to be treated as an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
