### ISSUE TITLE
Error message on static block

### ISSUE THREAD

**Issue by iokbomkamp** [magento/magento2#8058]
### Preconditions

1.  Magento version 2 in the backend admin - getting error in the static block 'Home Page Block' everytime I try to edit it. The error is: error: error in [unknown object].fireEvent(): event name: tinymceSetContent error message: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

![image](https://cloud.githubusercontent.com/assets/20865162/21692054/1fe90b14-d349-11e6-8315-889998170259.png)

### Steps to reproduce

1. Go to static blocks
2. Click home page block
3. try to edit it

### Expected result

1. No errors when trying to edit my block.

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/20865162/21692078/37b52912-d349-11e6-8035-551a9faa85c4.png)
Error Message:
error in [unknown object].fireEvent(): event name: tinymceSetContent error message: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by Quualudes** [comment]
I have the same issue have you resolved this and how?
thanks
