### ISSUE TITLE
Quotes in product name causes JSON error on product page MAP What's This Popup

### ISSUE THREAD

**Issue by justenpeters** [magento/magento2#8059]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Include single quote ( ' ) or double quote ( " ) in product name 
2. Add an MSRP price
3. View product page

### Expected result

1. Popup opens as expected

### Actual result

1. Unexpected end of JSON input error
![screen shot 2017-01-05 at 4 30 32 pm](https://cloud.githubusercontent.com/assets/368687/21698497/34160be8-d365-11e6-9174-7afc3b99d103.png)
![screen shot 2017-01-05 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/368687/21698562/8f228bce-d365-11e6-8eb4-4fc7a11bc11c.png)

**Comment by veloraven** [comment]
@justenpeters thank you for your report.
I have created internal ticket for it: MAGETWO-63116

**Comment by okorshenko** [comment]
Backport ticket for 2.1-develop: MAGETWO-69708

**Comment by magento-engcom-team** [comment]
@justenpeters thank you for your report.
The fix for this issue is already available in release 2.2.0

**Comment by harrigo** [comment]
This issue seems to have resurfaced for me in Magento 2.2.4. Was not an issue in 2.2.3. Have fixed  by formatting html characters in product name for breadcrumbs.phtml within Catalog module.

**Comment by genyuk** [comment]
Same issue appeared in 2.2.4. @harrigo - Could you please provide the fix you applied to breadcrumbs.phtml file?

**Comment by davidverholen** [comment]
as a workaround you can change the template in your custom theme

`magento/vendor/magento/module-catalog/view/frontend/templates/product/breadcrumbs.phtml`
```phtml
<?php
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$breadCrumbConfig = [
    'breadcrumbs' => [
        'categoryUrlSuffix' => $block->escapeHtml($viewModel->getCategoryUrlSuffix()),
        'useCategoryPathInUrl' => (int)$viewModel->isCategoryUsedInProductUrl(),
        'product' => $viewModel->getProductName()
    ]
]
?>
<div class="breadcrumbs" data-mage-init='<?= $block->escapeHtml(json_encode($breadCrumbConfig)) ?>'></div>
```

however the correct way to to do it would be creating the json config in the `\Magento\Catalog\ViewModel\Product\Breadcrumbs` View Model and use the internal json serializer I think

**Comment by EmilyPepperman** [comment]
Issue is there in Magento 2.2.5 !!!!

**Comment by zakgrindle** [comment]
This issue also breaks Widget conditions in the admin panel if categories have an &amp; in the name

**Comment by inkobject** [comment]
Seeing this issue in 2.2.5
In my use case, I sell plants. Double and single quotes have a definite meaning in naming conventions: species, hybrids, cultivars etc. Not being able to use double quotes makes things problematic for me.

**Comment by aeu** [comment]
I am also seeing this in 2.2.5

**Comment by aeu** [comment]
@inkobject I have the same problem as you, we sell products that are measured in feet and inches.  I was able to work around this by using the Prime and Double Prime Symbols in my product names.

https://en.wikipedia.org/wiki/Prime_(symbol)

Kind of ridiculous that I had to do this, but on the other hand using the Prime symbols is typographically more correct.

**Comment by hostep** [comment]
For the people reporting the issue in Magento 2.2.4 and 2.2.5, it's not the exact same issue as the original issue. Maybe better to watch these issues: https://github.com/magento/magento2/issues/15037 & 
https://github.com/magento/magento2/issues/15268 & https://github.com/magento/magento2/issues/15491 & https://github.com/magento/magento2/issues/15631 & https://github.com/magento/magento2/issues/17967

The real fix is in here: https://github.com/magento/magento2/pull/15521, but that one can't be applied cleanly to Magento 2.2.5. You can find a patch which you can apply cleanly to 2.2.5 in https://github.com/magento/magento2/issues/15631#issuecomment-419523038

Or you can wait for Magento 2.2.6, it should normally also contain the fix. Release date is supposed to be somewhere next week, or maybe the week after (but don't take my word for it).

**Comment by nike1994** [comment]
I have the same problem In Magento 2.4.6 :/
