### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed after php bin/magento setup:di:compile run

### ISSUE THREAD

**Issue by osmansorkar** [magento/magento2#8071]
Hi,
I am create a magento 2 module with a event. It working good before compile run php bin/magento setup:di:compile on production mode. If I deleted di directory from var directory It work good. 
### Preconditions
1.Magento 2.1.1
2.PHP-7.0.12
3.Server: NGINX
4.Ubuntu 16.4
5.MYSQL -5.6

### Steps to reproduce
1.  Create a Module name with one number like- Options2Attribute.
2. Create a Event Observer for "sales_quote_item_set_product" 
3. Create a class for this event with some dependency class
4. Move production mode
5. run  php bin/magento setup:di:compile
6. try add a production on cart

### Expected result

1. It will be add product into cart successfully .
2. Before di compile on product mode
![screenshot_136](https://cloud.githubusercontent.com/assets/10289018/21748679/b578e56a-d5b4-11e6-959a-844f29cc984a.png)

### Actual result

1.  After di compile on production mod
![fireshot capture 90 - - http___mage com_checkout_cart_add_uenc_ahr0cdovl21hz2uuy29tl3rlc3qylmh0b](https://cloud.githubusercontent.com/assets/10289018/21748648/07e9ede0-d5b4-11e6-9c55-7594d5545892.png)

### I have uploaded my module to check on product module with di compile.
[Options2Attribute (5).zip](https://github.com/magento/magento2/files/692002/Options2Attribute.5.zip)

### why this happened

It happen due to module name contain a number . (Is magento 2 suggest use module name without number)

**Comment by xmav** [comment]
@osmansorkar Thank you for your submission.
There is typo in class name. Please rename Quoteitem to QuoteItem (uppercase "I") and run php bin/magento setup:di:compile.
I’m closing this issue. Please reopen this issue as needed.
