### ISSUE TITLE
PCI Compliance - 2 factor authentication?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#8074]
Any plans to add 2 factor authentication to the Magento 2 Admin panel?

**Comment by piotrekkaminski** [comment]
Yes - but with no defined timeline yet.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/PCI-Compliance-2-factor-authentication/idi-p/58752).
