### ISSUE TITLE
Attribute extension and interface inheritance 

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#8088]
It is seems impossible to add extension attribute for \Magento\Catalog\Api\Data\ProductAttribute.
I used two methods for adding custom field (test) to product attribute (no EAV attribute), but all of them are failing.

### Preconditions
1. Magento 2.1.3 stable with sample data
2. My extension is enabled and works, cache disabled, after code changes I always run: rm -rf var
3. I read these docs:
[http://devdocs.magento.com/guides/v2.1/extension-dev-guide/attributes.html](url)
[http://magento.stackexchange.com/questions/91992/magento-2-how-to-save-custom-field-added-in-the-form-of-customer-group/92054#92054](url)

### Steps to reproduce
1. 
app/code/Vendor/Name/etc/extension_attributes.xml
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Catalog\Api\Data\ProductAttributeInterface"/>      
</config>
```
2. 
Custom code for adding custom field to the attribute extension:
```
/** @var \Magento\Catalog\Api\Data\ProductAttributeExtensionFactory */
protected $attributeExtensionFactory;
...
/** @var \Magento\Catalog\Model\ResourceModel\Eav\Attribute $attribute */
$attributeExtension = $attribute->getExtensionAttributes();
if ($attributeExtension === null) {          
   $attributeExtension = $this->attributeExtensionFactory->create();
 }
$attributeExtension->setTest(1);
$attribute->setExtensionAttributes($attributeExtension);
```
3. Class ProductAttributeExtension was successfully generated by magento engine with getTest() / setTest($test) methods.

### Expected result

1. No errors.

### Actual result
1. 
`$attribute->setExtensionAttributes($attributeExtension); ` 
retrieve
`
Recoverable Error: Argument 1 passed to Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor::setExtensionAttributes() must implement interface Magento\Eav\Api\Data\AttributeExtensionInterface, instance of Magento\Catalog\Api\Data\ProductAttributeExtension given
`
2. It is not possible use the attribute extension for product attribute class - because his parental interface hardcoded the extension attribute interface:
\Magento\Catalog\Api\Data\ProductAttributeInterface implements 
 \Magento\Catalog\Api\Data\EavAttributeInterface  
```
/**@return \Magento\Catalog\Api\Data\EavAttributeExtensionInterface|null   */
public function getExtensionAttributes();
```
I want create extension attribute for product attribute, no eav attribute.

But I can't create extension attribute for eav attribute also.
This code:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Eav\Api\Data\AttributeExtensionInterface">
        <attribute code="test" type="string"/>
    </extension_attributes>
</config>
```
Custom code:
```
/** @var \Magento\Catalog\Api\Data\ProductAttributeExtensionFactory  */
protected $attributeExtensionFactory;

...
/** @var \Magento\Catalog\Model\ResourceModel\Eav\Attribute $attribute */
$attributeExtension = $attribute->getExtensionAttributes();
if ($attributeExtension === null) {          
    /** @var \Magento\Eav\Api\Data\AttributeExtension $attributeExtension */
   $attributeExtension = $this->attributeExtensionFactory->create();
 }
$attributeExtension->setTest(1);
$attribute->setExtensionAttributes($attributeExtension);
```
Retrieve error:
`Fatal error: Call to undefined method Magento\Eav\Api\Data\AttributeExtension::setTest() `

Class Magento\Eav\Api\Data\AttributeExtension was generated without any methods...

**Comment by mrkhoa99** [comment]
@sergei-sss it's better if you post your question on [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by magento-engcom-team** [comment]
Hi @sergei-sss 
It is not a bug.
You should add extension attribute like this
```
<extension_attributes for="Magento\Catalog\Api\Data\ProductInterface">
    <attribute code="test" type="string" />
</extension_attributes>
```

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by tylerssn** [comment]
@sergei-sss - do you recall how you eventually resolved this?
