### ISSUE TITLE
Currency price issue in layered navigation in Product list page

### ISSUE THREAD

**Issue by sathishrajr** [magento/magento2#8090]
For Indian country in product listing page, when I filter the product price displays in Indian rupees shows the price in US dollar amount in shop by options .

1.Enter the url in the browser
2.Go to home page
3.Choose any one category and go to product listing page
4.For Indian country choose price filter options  ranges from Rs.0-682 wrongly calculating in dollar as Rs.0-9.99 in shop by options"

**Comment by veloraven** [comment]
@sathishrajr thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
