### ISSUE TITLE
Discount coupon code label need bracket in cart and checkout page.

### ISSUE THREAD

**Issue by sathishrajr** [magento/magento2#8091]
Coupon code should be displayed within bracket after discount text in both cart and checkout page

"1.Enter the url in the browser
2.Go to home page
3.Choose any one category and go to product detailed page
4.Add product to cart
5.In cart page,enter valid coupon code note coupon code will not get displayed within bracket after discount text
5.Click proceed to checkout button
6.Enter shipping address in checkout page
7.Choose shipping and payment method
8.In order review coupon code should be displayed within bracket"

**Comment by veloraven** [comment]
@sathishrajr thank you for your submission.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
