### ISSUE TITLE
Order total details are missing in My account >> order shipment page

### ISSUE THREAD

**Issue by sathishrajr** [magento/magento2#8092]
"1.Enter the url in the browser
2.Go to home page
3.Choose any one category and go to product detailed page
4.Add product to cart
5.Click proceed to checkout button
6.Enter billing and shipping address in checkout page
7.Choose the payment and place an order
8.Login as admin and access sales >> order page
9.Click the particular order and invoice the order
10.Ship the product 
11.Access front end and logging to the site
12.Go to My account section
13.In dashboard page click recent orders
14.Note Order total details are missing in shipment detail page"

**Comment by veloraven** [comment]
@sathishrajr thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
