### ISSUE TITLE
If there is no thumbnail image for a product, product box size should be aligned at the same height of the margin in product detailed page 

### ISSUE THREAD

**Issue by sathishrajr** [magento/magento2#8093]
1.Enter the url in the browser
2.Go to home page
3.Choose any one category and go to product listing page
4.Click any one product and access product detiled page

**Comment by veloraven** [comment]
@sathishrajr than you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
