### ISSUE TITLE
Actions dropdown list  position wrong if Actions Column is not the last column

### ISSUE THREAD

**Issue by dhanjugopi** [magento/magento2#8097]
if Actions Column is not the last column, the dropdown is still shown in last column

![actions dropdown](https://cloud.githubusercontent.com/assets/2108814/21820502/c47627be-d724-11e6-82fa-38fb14368352.png)

**Comment by veloraven** [comment]
@dhanjugopi thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
