### ISSUE TITLE
Magento 2 product url issue with multiple stores

### ISSUE THREAD

**Issue by avanish512** [magento/magento2#8101]
Hi,

Anyone can help me to fix Magento 2 Product URL issue with multiple stores.

like: - Some product URL is good and some have URL "catalog/product/view/id/121/s/compartment-organizer/". Also, I have re-index Magento but there no any impact on product URLs

If anyone can help me to fix this issue that would be great for me.

Thanks

**Comment by veloraven** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report an issue please create new GitHub issue and format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
