### ISSUE TITLE
Overriding Email Templates via a Module

### ISSUE THREAD

**Issue by sankalpshekhar** [magento/magento2#8103]
I am trying to add new fields into the OOB available Contact Us form, after modifying the controller, blocks and templates by overriding the default one, I am unable to override the email template. As per the documentation available, these templates could only be overwritten by placing a template file with similar name into the theme.

Since I am adding a new fields to the template, shouldn't this be overridden by the module?

In M1 we could have easily modified this by specifying a custom file path, but it doesn't seems to be the way here.

**Comment by veloraven** [comment]
@sankalpshekhar thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
