### ISSUE TITLE
Images are not saved while duplicating a product

### ISSUE THREAD

**Issue by JesseGuapa** [magento/magento2#8104]
If you duplicate a product the media gallery images are not saved in the new product. However the product can call the thumbnail, small and base image. But the image isn't shown on the productpage.

### Preconditions

1. PHP 5.6.10
2. Magento 2.1.3

### Steps to reproduce
1. Duplicate a product with multiple images.

### Expected result
1. Images are stored in the new product.

### Actual result
1. Images are not stored in the new product.
2. Thumbnail is shown in the productgrid, but not on the productpage.

**Comment by johnny-longneck** [comment]
Having the same problem with 2.1.3. 
Fix is highly appreciated. We cannot go live without having this solved.

**Comment by Tonop** [comment]
Hi,

Could you pls confirm or not the following similar [issue](https://github.com/magento/magento2/issues/8524).

**Comment by magento-engcom-team** [comment]
@JesseGuapa, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by whxt0901** [comment]
Now, I encountered the same problem, please help me

**Comment by whxt0901** [comment]
> 现在，我遇到了同样的问题，请帮帮我

All of the product images after duplicated is (mysqlhost)/static/version157743xxxx/adminhtml/Magento/backend/en_US/Magento_Catalog/images/product/placeholder/small_image.jpg
