### ISSUE TITLE
Do not publicly disclose store version

### ISSUE THREAD

**Issue by kassner** [magento/magento2#8106]
### Preconditions

1. Magento 2, all versions from 2.0.0 to 2.1.3;

### Steps to reproduce

1. Access the URL /magento_version (example: http://magento2-demo.nexcess.net/magento_version)

### Expected result

1. Magento does not _publicly_ disclose the installed edition and version.

### Actual result

1. `Magento/2.1 (Community)`

---

_Magento_Version_ module exposing the edition and the version might be a security problem, since it will allow attackers to easily identify what version a shop is using (or even if an store is running Magento at all). The module itself hardly will become a vector of attack, but it can help potential attackers to easily know the major version installed. The risk increases when the version disclose is no longer supported by Magento, since it is likely that last security issues were not fixed because Magento is not supporting that version anymore.

Instead, this information could be more valuable to have inside a protected API endpoint, returning a parseable (JSON/XML) format, so external integrations can easily spot the major version of the current store and send requests accordingly, without disclosing the version to the world.

Some motivation about the subject: https://www.troyhunt.com/shhh-dont-let-your-response-headers/

**Comment by korostii** [comment]
I would also mention [Magento_Swagger](http://magento2-demo.nexcess.net/swagger). 
IMHO it should be considered to move these modules into the require-dev section of the global composer.json.

**Comment by piotrekkaminski** [comment]
@kassner this is something we decided to not purse. We consider this endpoint to not be a security risk as it does not expose the patch version, and you could actually fingerprint the Magento version (including patch version sometimes) based on checksums of for example JavaScript files. 

@korostii Swagger - we will consider removing it/hiding it.
