### ISSUE TITLE
Random items added to order

### ISSUE THREAD

**Issue by bat553** [magento/magento2#8109]
### Preconditions

1. Magento 2.2, PHP 5.5,  MySQL 5,6 ( MariaDB )
2. Debain 8 Jessie

### Steps to reproduce

1.  Create a Order and validate it
2.  Go to : My Account -> My Orders -> Click on you're order -> 
![capture11012017](https://cloud.githubusercontent.com/assets/4821770/21863730/e7cb436e-d83e-11e6-97e2-45e1cac196f4.PNG)

I only ordered the last item

### Expected result

1. Only the product ordered appears

### Actual result

1. Uncontrolled products appear in the order.

**Comment by veloraven** [comment]
@bat553 thank you for your report.
Could you confirm that this issue is still actual?
Please note that Magento 2.2. does not support PHP 5.5, please confirm that you can reproduce this issue on a supported environment (PHP ver. 7.0.2, 7.0.4, 7.0.6-7.1.0)

**Comment by bat553** [comment]
@veloraven I migrated to PHP 7.0 and the bug seems to be resolved.

**Comment by veloraven** [comment]
@bat553 thank you for your update.
I'm closing this issue then.
If you can still reproduce this issue, please create a new GitHub issue report.
