### ISSUE TITLE
How to Collection of a table,

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#811]
Please I have a question that how to get all data of a product or categories,
I have tried this,
1.)define variable,
$this->_catalog= $catalog;
2.)define class in the constructor
 \Magento\Catalog\Model\Product $catalog,
3.)Inside that I have write inside the constructor,
 $this->_catalog= $catalog;
4.)then try to create the $product = $this->_catalog->create('Magento\Catalog\Model\Product\View');

But all this not works,so please tell me how to load model class,or get any table from anywhere asap.????

**Comment by verklov** [comment]
@aishwaryacedcoss, we assume @kandy provided you with answers to all questions that you have, so we are closing this ticket now. If you have more questions, please open a new ticket.
