### ISSUE TITLE
Export widget content into a CSV

### ISSUE THREAD

**Issue by kedarjoyner** [magento/magento2#8110]
I'm using Magneto 2 and importing widget and block content using csv files. Reading the [MSP_CmsImportExport](https://github.com/magespecialist/m2-MSP_CmsImportExport) documentation, it appears you can only "import/export CMS pages or blocks." That being said, is there currently a way to export widget content?

**Comment by veloraven** [comment]
@kedarjoyner thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
