### ISSUE TITLE
Zip / postcode has a default value of * in the checkout

### ISSUE THREAD

**Issue by TommyKolkman** [magento/magento2#8115]
### Preconditions

```
+------------------+-----------------------------------------------------+
| name             | value                                               |
+------------------+-----------------------------------------------------+
| Name             | Magento                                             |
| Version          | 2.1.3                                               |
| Edition          | Community                                           |
| Application Mode | production                                          |
| Session          | files                                               |
| Cache Backend    | Cm_Cache_Backend_Redis                              |
| Vendors          | Magento, Amasty, Elephant, Adyen, Nostress, Wyomind |
+------------------+-----------------------------------------------------+
```
PHP 7.0.14-2
MySQL 5.6.33

### Steps to reproduce

1. Clear all relevant browser data to be sure you're in a clean browser.
2. Add a product to the cart on goosecraft.com.
3. Go to the checkout
4. The zip / postcode is pre-filled with a *, causing it to validate straight away.

### Steps I've done to find out more
I have checked Magento_Ui/view/base/web/js/form/element/abstract.js and when I log initConfig(), I get the validate observer that show me a _latestValue of "*". It's very weird, there is no setting that leads to this.

### Expected result

1. The _latestValue should never have a value of *.

### Actual result

1. The _latestValue has  a value of * causing it to validate:

![wrong_latestvalue](https://cloud.githubusercontent.com/assets/837198/21890468/21795094-d8ce-11e6-83d9-5d19f43608bd.png)

**Comment by korostii** [comment]
Might be related: #7724

**Comment by miakusha** [comment]
Hi @TommyKolkman, I cannot reproduce issue
Can you reproduce it on fresh magento without any custom theme or modules ?

**Comment by webspeaks** [comment]
I am having same issue on 2.1.3
Any idea how to remove that?

**Comment by kayintveen** [comment]
Also same issue here.

**Comment by miplazy** [comment]
Simple to fix it is using jQuery:
====> Fix checkout
$('.checkout-cart-index .action.primary.checkout').hover(function(){
		if($('input[name="postcode"]').val() == '*'){
			$('input[name="postcode"]').val('').change();
		}
		
	});
===> Fix cart
	$('.checkout-cart-index #block-shipping .title').click(function(){
		if($('input[name="postcode"]').val() == '*'){
			$('input[name="postcode"]').val('').change();
		}
	}); 
It worked for me.

**Comment by pboisvert** [comment]
@KrystynaKabannyk can you check if this is a known issue in checkout?

**Comment by gweeble** [comment]
It would be great if we just need a control to turn it on or off in the configuration (maybe even per store/website)? some of us may need it if we have no Post Code (ZIP) in our country?

**Comment by vherasymenko** [comment]
@TommyKolkman , Hi, i try to reproduce your bug and it unsuccessfully.
I try on clean magento 2.1.3 in production mode with different locales and local packages.
Maybe you forgot some specific settings for reproduce this issue ??? Thank you.

**Comment by aaronware** [comment]
For everyone having this issue @TommyKolkman @webspeaks @bendraxguy @kayintveen etc be sure to check out Stores -> Configuration -> Sales -> Tax -> Default Tax Destination Calculation and remove the asterisk from the zip/postal code.

**Comment by HellgaM** [comment]
@TommyKolkman asterisk is pulled from Tax configuration, just remove "*" default value:
 
![asterik](https://user-images.githubusercontent.com/10230812/26973072-3fef9dda-4d1d-11e7-92a8-61b1eeee0370.png)

**Comment by magento-engcom-team** [comment]
@TommyKolkman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by peterjaap** [comment]
This also happens when `tax/defaults/postcode` in `core_config_data` has a `NULL` value.

**Comment by goranhorvathr** [comment]
This is still happening on 2.2.5. Gentlemen you are awfully trigger happy with cannot reproduce buttons. Im interested in which version of 2.2.x did you fix this by referencing this https://github.com/magento/magento2/issues/7724 and the 2.2.5 version I can't really see that fix. Thank you very much!

**Comment by PathToLife** [comment]
Can also reproduce.. 

Still exists in 2.3.0. Just have to set a postcode in "Default Tax Destination Calculation"

Which is set here:
http://Base_url/admin/admin/system_config/edit/section/tax/
![postcode set here](https://i.imgur.com/LNSjoKT.png)

Use Xdebug in any active shipping module on calling RateRequest->getDestPostcode(). We observe that:
```php
Magento\Quote\Model\Quote\Address\RateRequest->$_data['dest_postcode'] = Default Tax Destination Calculation
```

**Comment by PathToLife** [comment]
https://github.com/magento/magento2/issues/18630
