### ISSUE TITLE
Placeholder Required On Images

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#8116]
This may have been reported before - but our entire catalogue became broken due to place holders now being required or not if'd/optional - this made our entire product data .csv invalid and it became impossible to export the product data out.

Has this been reported already? If not I'll give more details.

**Comment by veloraven** [comment]
@LiamFielding thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
