### ISSUE TITLE
Problem with shipping and invoice emails from order-backend 2.1.3 (multistore)

### ISSUE THREAD

**Issue by WMV-SYSTEMS** [magento/magento2#8117]
We have set-up a multistore magento 2.1.3 installation. Al works fine. Emailsettings setup in store/website scope. (website+scope A / B / C / D)
Now if a customer orders some items on (website B), the email sent after checkout is ok.
Store name in email, the From address are the data of that store-scope. (website B)

When i go into the backend and select the order to put it on shipping, the next emails "shipping and invoice" are not sent with the data of the store-scope from the order but with the data of the default store.(website A)
but in the view of the order all displayed is (website B)

What is wrong in the code somewere?

(also already had to do the hack on getWebsite function $code = $website['code'];)

**Comment by WMV-SYSTEMS** [comment]
Found a temp. solution!!!

I've changed the following file "/vendor/magento/framework/Mail/Template/TransportBuilder.php" on line: 165 function "setFrom" in:

    public function setFrom($from)
    {	
		/** added by WMV **/
		if(isset($this->templateVars['store'])){
			$scope_id = $this->templateVars['store']->getId();
			$result = $this->_senderResolver->resolve($from, $scope_id);
		}else{
			$result = $this->_senderResolver->resolve($from);
		}

        $this->message->setFrom($result['email'], $result['name']);
        return $this;
    }

**Comment by veloraven** [comment]
@WMV-SYSTEMS thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for an advice and discussion please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by WMV-SYSTEMS** [comment]
Sorry you all, ticket is the same error as https://github.com/magento/magento2/issues/6954 but the fix i put in this issue fixes the problem for me in 2.1.3. all emails are now sent with the right data of a store.

**Comment by veloraven** [comment]
@WMV-SYSTEMS thank you for update.
I'm closing this issue as a duplicate then.
And I have added your comment with temporary solution to our internal ticket.
