### ISSUE TITLE
Mini Cart edit error: Requested product doesn't exist

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#812]
Few things to mention:
 - Logo is not clickable (should redirect to the homepage)
 - Mini cart product edit gives error: Requested product doesn't exist

> #0 /var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(130):
> Magento\Catalog\Model\ProductRepository->getById('3', false, NULL)

**Comment by verklov** [comment]
@MagePsycho, did you try clean install with the fresh code pulled from the repo, not the reinstall after update? I just cloned the repo, installed Magento and tried everything you reported, but everything works fine for me.

**Comment by vpelipenko** [comment]
It can't be reproduced now on the latest version. There is no response from contributor for more then 14 days. Closed.

**Comment by axovel** [comment]
I am also getting this error. Its happening on multiple store views only.
