### ISSUE TITLE
Product Rating: Rating isn't Available in Admin Panel

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#8122]
### Preconditions

1.  2.1.3 CE
2.  PHP 7, MYSQL 5.6
3. Tested on Apache and Litespeed
4. Tested on clean standard install with demo data and can reproduce. 

### Steps to reproduce

1.  Go to Marketing, Reviews, New Review, Choose a product
2.  Complete Review
3.  Detailed star ratings are not available in the admin page, even though the rating attributes are active. 
4. Tested on simple and configurable product

### Expected result

1. Detailed star rating should be available to select in admin.
2. It is available in the front end for customers.

### Actual result

1. Detailed star ratings are not available in the admin page, even though the rating attributes are active.
2. Detailed star ratings are selectable if the review was generated from the product pages and not the admin page.

<img width="1329" alt="screen shot 2017-01-13 at 12 43 55 pm" src="https://cloud.githubusercontent.com/assets/9780829/21916725/24fb27e0-d98e-11e6-8e18-9fb02221563e.png">

<img width="1358" alt="screen shot 2017-01-13 at 12 44 23 pm" src="https://cloud.githubusercontent.com/assets/9780829/21916724/24f99498-d98e-11e6-9de9-b53eec893191.png">

<img width="1337" alt="screen shot 2017-01-13 at 12 44 46 pm" src="https://cloud.githubusercontent.com/assets/9780829/21916726/24fd5fce-d98e-11e6-956b-2a4f3a7f2e5c.png">

Work around by completing the review from the front end as a customer and approve from the backend.

**Comment by korostii** [comment]
Have you tried changing the ratings' "visibility" property? Although as far as I remember, having them active wasn't enough for ratings to appear even on front end.

**Comment by veloraven** [comment]
@rkhoury82 thank you for your report.
Please select Store View(s) for your review - rating stars should appear after it.

**Comment by rudik99** [comment]
@veloraven you are correct - user error - ill close the issue.

**Comment by escounpo** [comment]
and for summary rating? how can i do to change in available?
