### ISSUE TITLE
Fatal Error in Unit Tests

### ISSUE THREAD

**Issue by chougron** [magento/magento2#8125]
When trying to to run Magento2 Unit Tests, I am getting a PHP Fatal Error:

`PHP Fatal error:  Class Magento\Sales\Api\Data\OrderPaymentExtension contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\Sales\Api\Data\OrderPaymentExtensionInterface::getVaultPaymentToken, Magento\Sales\Api\Data\OrderPaymentExtensionInterface::setVaultPaymentToken)`

This error is happening with 3 different modules : module-vault, module-paypal and module-braintree. When disabling the test for those modules, (by renaming the folder Test by Test2 for example) the Unit Tests pass.

### Preconditions

- Magento 2.1.3, installed via composer
- PHP version 7.0.14
- MySQL version 5.6.33
- Ubuntu 14.04

### Steps to reproduce

To reproduce, run the Unit Tests with the command :

`./magento dev:tests:run unit`

### Expected result

I would expect the Unit Tests for a fresh Magento 2 installation to all run and pass.

### Actual result

Instead, I am getting the given PHP Fatal Error.

**Comment by YevSent** [comment]
Hi, @chougron, try to clear `var` directory and rerun tests again. Similar errors might happen if you run unit tests on Magento instance with some already auto-generated code, because if some code is already generated unit test will use it instead mocks.

**Comment by veloraven** [comment]
@chougron thank you for your feedback.
Could you please check that your composer is updated?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by amenk** [comment]
Had the same problem, can confirm that cleaning `var/generation` helps. (in 2.1.8)

**Comment by murtuza1234** [comment]
had a same problem in 2.3 and solved by deleting `generated`
