### ISSUE TITLE
Magento 2.1.3 - Price for Out of Stock Product Dissappear from all page.

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#8128]
Hello. I have a problem with price for 0 quantity product on Magento 2.1.3
Ussually, if out of stock product to show, the price is there as an information price for each products but with "Out of Stock" information replace add to cart button. But on Magento 2.1.3 is no price information.

### Preconditions
1. I need to show 0 quantity products as their catalogue products even no products available. May be it show on frontpage as feature product, category page, and ofcause on product view page.
2. Magento 2.1.3 
 

### Steps to reproduce
1. on Setup product, set to 0 quantity products.
2. Price is set. Example 10 USD.
3. Save

### Expected result
1. On Frontpage is show product with "Out of Stock" information and the price is show too.
2. On Category page, it shows too with the same as on frontpage.
3. On Product page, there is price information, and "out of stock" that replace "add to cart" button.

### Actual result
1. On frontpage only image and "out of stock".
2. On category page only image and "out of stock".
3. on Product view page the price is dissappear.

![01-price-bugs-out-of-stock](https://cloud.githubusercontent.com/assets/5201127/21929746/01ea990c-d9c5-11e6-9712-e9d840a98629.png)

![02-price-bugs-out-of-stock](https://cloud.githubusercontent.com/assets/5201127/21929752/0a491c40-d9c5-11e6-8924-81f6aae10fdf.jpg)

**Comment by naydav** [comment]
Thanks
Internal ticket MAGETWO-62229, which tracks this GitHub issue, is in our issue backlog.

**Comment by jurpro** [comment]
hello. Is there any news and how to fix this? Thanks

**Comment by zamson** [comment]
This is a big problem for us as well. Any updates? Not being able to show prices of a product seems pretty big to me.

**Comment by jurpro** [comment]
Thank you for responding my report. Now on Magento 2.1.4 the price come back showing for out of stock product. 

Thank you so much

**Comment by scottsb** [comment]
@magento-team @veloraven This should be closed, right?

**Comment by magento-engcom-team** [comment]
@jurpro, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
