### ISSUE TITLE
"Old price" is shown in net whilst backend settings states otherwise

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#8129]
### Preconditions

1. Magento 2.1.2
2. PHP7

### Steps to reproduce

1.  Create a new configurable product
2. Enter prices excluding tax in backend
3. configure magento to calculate final prices on the fly when shown (Display: including tax; calculation: excluding tax, see screens)

### Expected result

1. Prices are calculated correctly 

### Actual result

1. Special/old price is shown in net, whilst the final price is correctly shown gross

Final price is correct; old price is in net (which is wrong)
![bildschirmfoto 2017-01-13 um 13 32 09](https://cloud.githubusercontent.com/assets/13021579/21930148/c23347da-d994-11e6-9458-918ab296589e.png)

Backend Settings: 
![bildschirmfoto 2017-01-13 um 13 32 16](https://cloud.githubusercontent.com/assets/13021579/21930147/c230979c-d994-11e6-981f-aed5c3cc7516.png)
![bildschirmfoto 2017-01-13 um 13 32 22](https://cloud.githubusercontent.com/assets/13021579/21930149/c2343b04-d994-11e6-9a50-e87ef52355cb.png)

**Comment by grasdaggel** [comment]
Any updates on this?

**Comment by grasdaggel** [comment]
20 days later, any updates on this?

**Comment by grasdaggel** [comment]
24 days later, still no update on this?

**Comment by Stas94** [comment]
@grasdaggel We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.
