### ISSUE TITLE
Errors when trying to run composer install on PHP5.6

### ISSUE THREAD

**Issue by paales** [magento/magento2#813]
![schermafbeelding 2014-12-17 om 21 58 50](https://cloud.githubusercontent.com/assets/1244416/5478826/f1de7f7a-8637-11e4-8d44-fc18da066c32.png)

In the composer.json file we should allow PHP 5.6, `"php": "~5.4.11|~5.6.0",` seems to work.

**Comment by maksek** [comment]
@paales, let us know if you still have the issue.

**Comment by paales** [comment]
@maksek Well, I managed to install everything, but the composer file hasn't been updated to include 5.6, so the issue is still relevant. :)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32323

**Comment by vpelipenko** [comment]
@paales, composer.json includes PHP 5.6 as supported version now. Could you check the issue again?

**Comment by maksek** [comment]
Closing issue, due no response more then 2 weeks. PHP 5.6 is supported, composer is updated. If you still have the issue feel free to reopen or create new with link to this one.

**Comment by paales** [comment]
@vpelipenko @maksek Didn't have the time to check again, but since the composer.json files are updated, I expect everything to work.
