### ISSUE TITLE
Magento2. Component manager not work.

### ISSUE THREAD

**Issue by deniskonovalov** [magento/magento2#8133]
1. Magento ver. 2.1.2
2. php 5.6

I have a problem. When I'm try go to component manager,  page not load and loader with "Please wait" are endless.

I have 

> 500 Internal Server Error

 on

> /setup/index.php/componentGrid/components

![36972bbfb1](https://cloud.githubusercontent.com/assets/16177030/21936642/9a90793e-d9ba-11e6-89f8-7211bc93c739.jpg)
![1111111111111](https://cloud.githubusercontent.com/assets/16177030/21936645/9e55c880-d9ba-11e6-87f7-635030c4952e.jpg)

**Comment by deniskonovalov** [comment]
anyone haven't this problem??

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate for #6737 and #7958

**Comment by muhammadshakeel** [comment]
I have fixed this issue by following below steps:

 - Open /setup/index.php/componentGrid/components in new tab
 - It showed me actual error, in my case it was last extension installed through composer.
 - I have removed that from composer
 - After updating composer, the error goes away.

https://magento.stackexchange.com/a/182945/56221
