### ISSUE TITLE
Attribute not save after change the attribute set

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#8134]
### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Change product's attribute set
2. Before click on save, change something on multiple select attributes.
3. Click on save

### Expected result

1. Save any change to the attribute.

### Actual result

1. none of the multiple select attributes are saved.

###Work around
If I change the attribute set, then save, then apply attributes, then save a second time, it works.

**Comment by magento-engcom-team** [comment]
@TClilMouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
