### ISSUE TITLE
selecting default options by attribute is not working for configurable item in Magento 2.1.2

### ISSUE THREAD

**Issue by erik-augustin** [magento/magento2#8135]
### Preconditions

1. Magento 2.1.2
2. 

### Steps to reproduce

1. http://ext.magdev.nl/dutch/sidekick-shoe#107=52&272=24&502=46 (sample as working inmagento 1.9)
2. 
3. 

### Expected result

1. default options should be set by attributes link

### Actual result

1. [Screenshot, logs]
no options are set
its not possible to select an individual configuration(simple product) from an configurable product in magento 2.1.2

**Comment by veloraven** [comment]
@erik-augustin thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. 
Please describe exact steps without external links.

**Comment by erik-augustin** [comment]
previously magento 1.9 you could select default values from with link like this http://ext.magdev.nl/dutch/sidekick-shoe#107=52&272=24&502=46
configurable.js script at configurable item page set default values.

How does this work nowdays in Magento 2.1?

**Comment by veloraven** [comment]
@erik-augustin GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. With clear steps described in the issue. Your description should look like:

**Steps:**
1. Step 1....
2. Step 2...
3. ....

**Actual result:**
- actual result you get after described steps

**Expected result:**
+ result you were expecting to get after described steps

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
