### ISSUE TITLE
Singlestore mode issues

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#8137]
### Description
When you set your store to single-store mode and try to customize theme - nothing is happens.

### Preconditions
1. Magento 2.1.3 (production mode)
2. Default Luma theme or custom theme

### Steps to reproduce
1. Set single store mode (Stores - Configuration - General): Enable Single-Store Mode - Yes
2. Modify any field in theme under Content - Design - Configuration

### Expected result
Custom keywords, favicon, logo or transactional email logo

### Actual result
No changes after cache and deploy mode manipulations

**Comment by orozcodiaz** [comment]
Will this issue be fixed soon? We're using bunch of костыли and велосипеды for now :)

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
