### ISSUE TITLE
Missing 'More information' tab

### ISSUE THREAD

**Issue by tukker01** [magento/magento2#8138]
### Preconditions

1. Magento 2.1.3
2.  PHP7
3. Mysql 5.7

### Steps to reproduce

1. After running deplucation from a product the job runs in a loop.
 After stopping Apache en Restarting de 'More information' tab is missing.
 This is a database issue because after restoring a older database problem is gone.

### Expected result

1. 

### Actual result

1.

**Comment by veloraven** [comment]
@tukker01 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with exact steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
