### ISSUE TITLE
Another folder is added after pub/static

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#8139]
When i run command for deploy static files then a hidden file is append in url like **pub/static/version1484397640/frontend/NextByte/default/en_GB/mage/calendar.css**

### Preconditions
1.  I use Magento 2.1.3, Mysql 5.6, nginx.

### Steps to reproduce
1. Install a fresh Magento from zip followed by devdocs documentation.

### Expected result
/pub/static/frontend/NextByte/default/en_GB/mage/calendar.css

### Actual result
A folder is added after the statuc folder.
/pub/static/version1484397640/frontend/NextByte/default/en_GB/mage/calendar.css

Please give me some hints of this error ASAP.

**Comment by lukeconvertdigital** [comment]
Sign Static Files is set to Yes in admin: http://docs.magento.com/m2/ce/user_guide/system/static-file-signature.html

**Comment by fooman** [comment]
This is expected behaviour. Version 2.1.3 has a new default value for
Store > Configuration > Advanced >Developer > Sign Static Files.
Set this to No and the version number won't be added.

**Comment by rishabhrkrai** [comment]
thanks @helloitsluke 
Its really helps me.
