### ISSUE TITLE
Ui form is broken by ui grid if it's added into the form

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#8141]
### Preconditions
1.  Developer branch is used

### Steps to reproduce
1. I try to add ui grid on customer edit page (which is ui form)
2. I created `app/code/Jyt/TestModule/view/adminhtml/ui_component/customer_form.xml` file with contend
```
<?xml version="1.0"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="customer_cms_pages">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">CMS Pages</item>
            </item>
        </argument>
        <insertListing>
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="ns" xsi:type="string">cms_page_listing</item>
                    <item name="autoRender" xsi:type="boolean">true</item>
                </item>
            </argument>
        </insertListing>
    </fieldset>
</form>
```
3. `cms_page_listing` is used for example only.

### Expected result
1. Grid is rendered properly
2. It's posible to save the customer edit form

### Actual result
1. It's impossible to save the form, js error is thrown 
<img width="1420" alt="ui_form_grid_error" src="https://cloud.githubusercontent.com/assets/6418650/21956105/cb094c4a-da81-11e6-843e-566ffcaace79.png">

2. Grid it rendered, but with ui bugs
<img width="1396" alt="ui_grid_in_ui_form_1" src="https://cloud.githubusercontent.com/assets/6418650/21956107/cb3a3f80-da81-11e6-9412-5355bbc13faf.png">
<img width="1429" alt="ui_grid_in_ui_form_2" src="https://cloud.githubusercontent.com/assets/6418650/21956106/cb387cb8-da81-11e6-8879-77228bf69555.png">

Question: Is it possible to pass current customer (from the url or edit form) to grid collection somehow or backend session data should be used here?

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.
We've created internal ticket(s) MAGETWO-81439 to track progress on the issue.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team Any update on it, how to resolve this issue.

**Comment by Jefnull** [comment]
+1 Any progress on a fix to magento? I'm having the exact same issue, and have the same code setup as the issue reports

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
