### ISSUE TITLE
2.1.3 No downloadable link in grouped products

### ISSUE THREAD

**Issue by bhpex** [magento/magento2#8144]
I do not get link to download a downloadable product (no link in email, no link on account).
Downloadable product is located in grouped product.

**Comment by veloraven** [comment]
@bhpex thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
