### ISSUE TITLE
Rest API product update attribute set issue

### ISSUE THREAD

**Issue by ovidiucaramida** [magento/magento2#8146]
My magento 2 website has multiple attribute sets, each with their own required attributes(dropdown attributes).
On REST API product creation everything works fine, but when updating product with REST API, on every product update call it tries to validate all attributes, no matter in which attribute set, and all attributes that are required and have no values set give an error.

Is there something i'm missing? Why would the api not take the attribute set id into account when validating provided data?

**Comment by veloraven** [comment]
@ovidiucaramida thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

If you are rather looking for an advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
