### ISSUE TITLE
The rest call isEmailAvailable should be removed for security reasons

### ISSUE THREAD

**Issue by Bbbrinks** [magento/magento2#8150]
The call /default/V1/customers/isEmailAvailable can be used to check if an email is in use and therefor exists. Spammers/hackers will like this information.

This is not recommended by owasp: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Incorrect_Response_Examples

**Comment by veloraven** [comment]
@sterfpaul thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
