### ISSUE TITLE
Braintree in production modus not working

### ISSUE THREAD

**Issue by amansilla** [magento/magento2#8154]
Braintree not working in production mode, whenever I select "Credit Card (Braintree)" a JS error will occur.

### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Add product to the cart 
2. Go to checkout
3. Select Braintree as payment method

### Expected result

1. Be able to introduce the credit card information

### Actual result

1. Uncaught Error: Braintree API Client Misconfigured: clientToken required.

**Comment by YevSent** [comment]
Hi, @amansilla, looks like you did not configure Braintree payment method in Magento admin panel. Did you specify `Merchant ID`, `Public Key` and `Private Key` for Braintree?

**Comment by amansilla** [comment]
Hi @joni-jones thanks for your quick feedback. Yes, for sure I provided the ´Merchant ID´, ´Public Key´ and ´Private Key´. I'm guessing that JS is not be able to get the clientToken because I'm running it in a VM and Braintreee maybe check the domain name doing the request.

I'll report the result of my test asap.

**Comment by YevSent** [comment]
You can also use `xdebug` to check if [getClientToken](https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/Model/Ui/ConfigProvider.php#L87) method returns token.

**Comment by amansilla** [comment]
Yes, I did it and getClientToken return always `null`. I'm still researching it why right now but I guess it's a bug.

**Comment by YevSent** [comment]
The `\Magento\Braintree\Model\Adapter\BraintreeAdapter::generate` returns `null` if token generation fails with exception. In this method you can find original reason of failing, please, post this exception message with stack trace.

**Comment by amansilla** [comment]
I know but take a look here that the generate is called without params. https://github.com/magento/magento2/blob/2.1.2/app/code/Magento/Braintree/Model/Ui/ConfigProvider.php#L116 😄

**Comment by YevSent** [comment]
So? In 2.1.2 version token generation does not use merchant account id (this param added in 2.1.3 version), but it anyway token will be generated without any params.

**Comment by amansilla** [comment]
In my case and it's important with production credentials it's not being generated. Why? I've no clue.

**Comment by YevSent** [comment]
Did you try to set breakpoint in [BrainteeAdapter::generate](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Braintree/Model/Adapter/BraintreeAdapter.php#L97)?

**Comment by amansilla** [comment]
I debugged the BrainteeAdapter::generate and there during ClientToken::generate a exception will be thrown since a 401 HTTP status is returned back when doing the `POST` request .

**Comment by YevSent** [comment]
401 HTTP status says what request not authorized. Can you check your credentials in request to Braintree, also, you can check direct response from Braintree in `\Braintree\Http::post`.

**Comment by amansilla** [comment]
ok sorry for disturbing here I got this working so you can close this. The problem was not magento related but braintree credential configuration, it seems the checkbox `Authorize API` was not checked.

@joni-jones thx for your help 😉

**Comment by YevSent** [comment]
You are welcome. I'm closing this issue as not a bug.

**Comment by sunilit42** [comment]
@amansilla 
i am facing same issue and there is no setting for like that as you mention like Authorize API checkbox

**Comment by mytran89** [comment]
hi @sunilit42 @amansilla , I'm also having this issue in production mode and didn't see any Authorize API checkbox either. Did you come up with any fix for it then?

**Comment by lano-vargas** [comment]
@amansilla  similar issue  ref: https://github.com/magento/magento2/issues/5910
