### ISSUE TITLE
Attribute disappear after changed attribute set if attribute is in different groups

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#8157]
### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Create a new attribute set 
2. Create a new group in the new attribute set
3. Move attribute "description" to the new group from "Product Details" group
4. Change product attribute set to the new attribute set.

### Expected result

1. All existing description still there just in the new attribute group.

### Actual result

1. Description disappear.

###Workaround
Before change attribute set, create the same group name under the new attribute set and move the attributes to the same attribute group as the new attribute set.

**Comment by magento-engcom-team** [comment]
@TClilMouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
