### ISSUE TITLE
CSS missed in One Page Checkout but its existing in other pages

### ISSUE THREAD

**Issue by alagukannanKumaresan** [magento/magento2#8160]
Hello, 
I got first Magento project. And also version is 2.1.3. and Magento is complete new for me. Is any one suggest me why my theme CSS is missed in onepagecheckout eventhough its showing in other pages. 

### Preconditions
Magento version version is 2.1.3.

### Steps to reproduce
1. created theme.xml

### Expected result
1. Theme CSS also at onepage checkout.

### Actual result
1. No Theme CSS at onepage checkout.

Any idea? Thanks in advance!

Best Regards,
AK

**Comment by alagukannanKumaresan** [comment]
No answers....?????

**Comment by aakimov** [comment]
Hello @alagukannanKumaresan 

Unfortunately the information you have provided is not enough for us to reproduce the issue. Moreover it is even hard to tell where the issue might be. The only thing that we can suggest is referring to our devdocs portal: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html

Also Magento provides two themes out of the box: **blank** and **luma**. You can refer to them for more examples (**luma** adds styles to checkout as well).

**Next time please report an issue if you are sure that there is an issue in the system** If you have some trouble customizing Magento or you are not sure how some particular flow should work, please ask on our community forum https://community.magento.com/t5/Theming-Layout-Design-Questions/bd-p/magento-2-theming 

Thank you for understanding.
Regards,

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
