### ISSUE TITLE
Modern Cryptography for Magento (provided by libsodium)

### ISSUE THREAD

**Issue by paragonie-scott** [magento/magento2#8163]
I'd like to propose the adoption of [sodium_compat](https://github.com/paragonie/sodium_compat) into the next release of Magento, so that everyone can enjoy modern cryptography with misuse-resistant interfaces.

### Preconditions

Before sodium_compat can be trusted, it must be audited by a competent third party. See https://github.com/paragonie/sodium_compat/issues/8 for the discussion about this initiative, and [this SitePoint article](https://www.sitepoint.com/what-would-you-pay-to-make-27-of-the-web-more-secure/) for the answers to the most obvious questions you may have as you're reading this.

(If anyone at Magento Inc. is interested in contributing towards getting sodium_compat audited, please get in touch either publicly at https://github.com/paragonie/sodium_compat/issues/8 or privately at `security at paragonie dot com`.)

**Comment by veloraven** [comment]
@paragonie-scott thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by theofidry** [comment]
@veloraven this is ridiculous

**Comment by paragonie-scott** [comment]
@veloraven Problem: After filling in my idea, it then demands that I log in or create an account. This is a dark pattern; it should require authentication *before* anyone wastes their time filling out a form.

I don't want to create an account. Feel free to add this there if you want.
