### ISSUE TITLE
Sorting of Backend UI Grid generates SQL Error

### ISSUE THREAD

**Issue by U12358** [magento/magento2#8164]
Backend UI Grid has field `ignore` (field from db table)

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ignore ASC LIMIT 20' at line 1, query was: SELECT `main_table`.* FROM `table` AS `main_table` WHERE (`ignore` = '1') ORDER BY ignore ASC LIMIT 20```

works normal when 
```ORDER BY `ignore` ```

**Comment by veloraven** [comment]
@SKovbel thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
