### ISSUE TITLE
Fetch payment transaction info for getaway payment issue

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#8165]
### Preconditions

1. Install Mangeto version 2.1.3

### Steps to reproduce

1. Create a custom gateway payment method
2. Create logic for fetch transaction info
3. Go to Sales -> Transactions -> View Transaction. Click Button "Fetch".
4. Get response (info about transaction) from payment method API. Try to save transaction info into `sales_payment_transaction` table. 

### Expected result

1. Transaction information saved into table `sales_payment_transaction` (field `additional_information`)

### Actual result

1. Function `fetchTransactionInfo` in class `Magento\Payment\Model\Method\Adapter` should return array with information. 
[https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Model/Method/Adapter.php#L404](https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Model/Method/Adapter.php#L404)
2. Function `importTransactionInfo` in class `Magento\Sales\Model\Order\Payment` set this data (get NULL) as additional information for transaction.
[https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Payment.php#L1174](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Payment.php#L1174)
3. I try to save additional information for the transaction in my getaway response handler class, but transaction info will be rewritten in the controller:
[https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Transactions/Fetch.php#L37](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Transactions/Fetch.php#L37)

**Comment by YevSent** [comment]
Hi, @OleksiyOleksiyovych, thanks for your reporting. It's really inconsistent behavior in Sales module.
I have created internal ticket MAGETWO-63239.

You can use payment `additional_information` and set transaction details into additional information. In that case, all data about transaction will be stored in payment details (`sales_order_payment` table).
*Note*, payment additional information should contain only simple key-value data, like
```
$payment->setAdditionalInformation([
    'key1' => `value1`,
    'key2' => 'value2',
    ...
]);
```

Now, you can use follow structure:
```
$payment->setAdditionalInformation([
    'parent_key' => [
        'key1' => `value1`,
        'key2' => 'value2',
    ]
]);
```

But in future releases second example won't work.

**Comment by YevSent** [comment]
Hi, @OleksiyOleksiyovych, the fix merged into the develop branch.
