### ISSUE TITLE
Newsletter queue not working and cronjob for email do not start

### ISSUE THREAD

**Issue by AgenturSchroeder** [magento/magento2#8166]
### Preconditions

1. Create newsletter.
2. Set newsletter to the queue without a date (the problem is still there if i set a date).
3. Start sending the newsletter within the queue.

### Steps to reproduce

1. Start the cronjobs with console (i used PuTTy) with the following rotation:
/usr/local/bin/php7.0.6-cli -d memory_limit=1024M /folder/to/magento2/shopname/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /folder/to/magento2/shopname/var/log/magento.cron.log 

### Expected result

1. The queue should start and the crons should run.

### Actual result

1. Ive got the following message in PuTTy after my console input:

  **[Exception]**
  Rolled back transaction has not been completed correctly.
  cron:run [--group="..."] [--bootstrap="..."]

2. The magento.cron.log file show me:

Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /folder/to/magento2/shopname/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3764 in /folder/to/magento2/shopname/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', '/folder/to...', 3764, Array)
#1 /folder/to/magento2/shopname/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(3764): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in /folder/to/magento2/shopname/vendor/magento/framework/App/ErrorHandler.php on line 61

3. The newsletter queue in the backend still have the status "not sending". 
If you send it by letting the date free and click on "send" in the backend the status is "sending" but no email would send.

4. In the database table "cron_schedule" in the row "job_code" is the "email_send_queue"  with status pending (see attachment).
![queue](https://cloud.githubusercontent.com/assets/23551358/22022309/bb88ecde-dcc1-11e6-8a0b-e3626392cb3d.jpg)

I use Magento 2.1.3.
All other email service from this shop work fine, even the auto email for the succesfull order.

**Comment by Ctucker9233** [comment]
Similar issue on 2.1.2.

**Comment by AgenturSchroeder** [comment]
Some ideas for a workaround?

**Comment by xmav** [comment]
@Irvz newsletter cron job code supposed to be "newsletter_send_all" (app/code/Magento/Newsletter/etc/crontab.xml or vendor/magento/module-newsletter/etc/crontab.xml)
Is there any usefull information in Admin => Reports => Newsletter Problems Report ?

**Comment by AgenturSchroeder** [comment]
@xmav There is no error report.  Normaly the "newsletter_send_all" shouldn't have the status "pending" right? (Like my attachment on the first post.) How did you start your crons? Maybe i made a mistake there. But if i did it wrong, how could magento2 create and start succesfull the other crons?

**Comment by xmav** [comment]
@Irvz You may refer http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html to configure cron jobs.
"pending" status is ok. It means that this job will be processed later.
There is no "newsletter_send_all" job code on your screenshot.
Do you have any extensions that define cron job ?
Unfortunately, I could not reproduce the issue on clean code base(without extensions).
Would be great if you can provide steps to reproduce this issue on clean code base.
Full exception trace will be helpful

**Comment by AgenturSchroeder** [comment]
Ok, well i have found the problem.
There was a wrong cronjob call in my customfile. But this is still a problem for shop owner which don't have the knowledge about cronjobs. I think there should be an out-of-the-box settingt to setup a cron for the magento 2 cronjob. I had to set a own cronfile for the crontabs. This is a realy terrible way to solve it without programming knowledge. 

Cronfile like:
```
#!/bin/bash
env -i /usr/path/to/php/php7.0.13-cli -d memory_limit=1024M -f /root/path/to/shop/shopname/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /root/path/to/shop/shopname/var/log/magento.cron.log
env -i /usr/path/to/php/php7.0.13-cli -d memory_limit=1024M -f /root/path/to/shop/shopname/update/cron.php >> /root/path/to/shop/shopname/var/log/update.cron.log
env -i /usr/path/to/php/php7.0.13-cli -d memory_limit=1024M -f /root/path/to/shop/shopname/bin/magento setup:cron:run >> /root/path/to/shop/shopname/var/log/setup.cron.log
```
