### ISSUE TITLE
Content_>Page not loading

### ISSUE THREAD

**Issue by VIGUMAPS** [magento/magento2#8169]
Admin page not loading Content_>Page -  not loading.

**Comment by veloraven** [comment]
@ivannpaz thank you for you feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please also specify if it was clear install or upgrade from some other version.
Did you try to clean browser cache including offline website data?

**Comment by ivannpaz** [comment]
@veloraven I didn't report anything 😉

**Comment by veloraven** [comment]
@VIGUMAPS please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please also specify if it was clear install or upgrade from some other version.
Did you try to clean browser cache including offline website data?

**Comment by veloraven** [comment]
@ivannpaz sorry for miscomprehension and thank you for pointing at it.

**Comment by VIGUMAPS** [comment]
if i tried to open Content->Pages its showing something went wrong and Cron is not running in your website.

**Comment by veloraven** [comment]
@VIGUMAPS please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please also specify if it was clear install or upgrade from some other version.
Did you try to clean browser cache including offline website data?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
