### ISSUE TITLE
Creating a product via REST API does not assign it to the website.

### ISSUE THREAD

**Issue by geon** [magento/magento2#8173]
### Preconditions
php 7
Percona
Magento 2.1.3
(mageinferno docker image)

### Steps to reproduce
PUT /rest/V1/products/SOME_SKU

### Expected result
The product should be visible in the website.

### Actual result
It is not. 

When investigation, I found that the products created via REST were assigned to the website 0, while products created via the admin GUI are assigned to website 1. (In table `catalog_product_website`.)

**Comment by miakusha** [comment]
Hi @geon, We cannot reproduce this issue on clean Magento instance
Please add more details to your description of the steps you followed when identifying this issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by geon** [comment]
Still not working.

**Comment by misha-kotov** [comment]
@geon are you using PUT to create or update an existing product? If update, is the product previously visible on the website and disappears after update? What is the latest version you tried this on? 
To create, you should be using POST, not PUT.
