### ISSUE TITLE
Product Export doesn't contain any Associated SKU's for Configurable Products

### ISSUE THREAD

**Issue by antbates91** [magento/magento2#8175]
When exporting the product catalog using Magento's export tool no Associated SKU's are exported.

### Preconditions

1. Tag 2.1.3 
2. PHP 7.0.13 / 7.0.7
2. MySQL 5.6.34

### Steps to reproduce

1. Go To System -> Data Transfer -> Export
2. Select Entity Type as Products
3. Hit Export with/without selecting any filters

### Expected result

1. All Products should be exported with Associated SKU's for Configurable Products.

### Actual result

1. All Products are exported but the Associated SKU's column is blank for Configurable Products.
[full-and-filtered-export.zip](https://github.com/magento/magento2/files/713592/full-and-filtered-export.zip)

**Comment by miakusha** [comment]
Hi @antbates1991, "associated_skus" column not related for Configurable Products, it contain SKU for grouped products. Child SKU for Configurable product present in the "configurable_variations" column

**Comment by antbates91** [comment]
@miakusha Thanks for clarifying 👍
