### ISSUE TITLE
Two or more templates do not work together for widget

### ISSUE THREAD

**Issue by sichensol** [magento/magento2#8177]
I do not know it is an issue or not, I just want to know how it should work. When I created custom widget for magento 2 store. In widget.xml I added option to choose the template.
           <parameter name="template" xsi:type="select" required="true" visible="true">
                <label translate="true">Template</label>
                <options>
                    <option name="default" value="widget/test_template.phtml" selected="true">
                        <label translate="true">Products Grid Template</label>
                    </option>
                    <option name="top_products" value="widget/top_products.phtml">
                        <label translate="true">Top Products Template</label>
                    </option>
                </options>
            </parameter>
When I tried to enamble widget for CMS page, I got next. I could configure different layout updates, for any one I could choose different template, but after this I could see only one template for the widget in the same time on different pages. If I understood right it would be possible to configure different templates for different pages for a widget, but only one template works, another does not use as on the one page and on different pages as well.

I'll be very glad if you can explain why it does not work, or it is just a bug.

Best regards.

**Comment by veloraven** [comment]
@molneek thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
