### ISSUE TITLE
Too late for the schedule Cron Jobs 

### ISSUE THREAD

**Issue by ramindas** [magento/magento2#8180]
Magento 2 Cron job not running. when checked cron_schedule table it says "Too late for the schedule"  

### Preconditions
1. Magento 2.1.3 CE
2. PHP 7.0
3. MySQL 5.6.34

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/22808209/22069570/e6da49f2-ddbe-11e6-8270-cde1a9fcebfd.png)

**Comment by veloraven** [comment]
@ramindas thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by SyedMuneebb** [comment]
Create crontab.xml file in app/code/Magenticians/Mymodule/etc and copy this code:

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
<group id="default">
<job name="cron_name" instance="Magenticians\Mymodule\Cron\Run" method="execute">
<schedule>*/1 * * * *</schedule>-->
</job>
</group>
</config>`

Now create Run.php file in app/code/Magenticians/Mymodule/Cron and copy the following code in it:

```
`<?php
namespace Magenticians\Mymodule\Cron;

class Run 
{
   protected $_logger;
   public function __construct(
       \Psr\Log\LoggerInterface $logger
   ) 
    {
     $this->_logger = $logger;
    }

   public function execute()
   {
       //Edit it according to your requirement
       $this->_logger->debug('Cron run successfully');
       return $this;
   }
}`

```
 Run these commands in the root directory:
`php bin/magento cache:flush
php bin/magento cron:run`

To run Cron job for one group only, try this command:
`php bin/magento cron:run --group="your_group_name"`

Source: [Cron Job in Magento 2](https://magenticians.com/setup-cron-job-magento-2/)
