### ISSUE TITLE
Registering a shared service with a custom factory

### ISSUE THREAD

**Issue by AydinHassan** [magento/magento2#8182]
I'm wondering how (if I can) register a shared service with a custom factory.

Consider the following code:

```php

class MyApiFactory {
    private $config;

    public function ___construct(Config $config) {
        $this->config = $config;
    }
   
    //this method could either be __invoke
    //or the class could implement some factory interface
    public function create() {
        return new MyApi($this->config->get('some-value'), $this->config->get('some-other-value'));
    }
   
}

class MyApi {
}

class MyService1 {
    public function __construct(MyApi $api) {}
}

class MyService2 {
    public function __construct(MyApi $api) {}
}
```

With other PHP DI frameworks - I would register `MyApiFactory` as a factory for `MyApi`. If I requested for service `MyService1` the DI container would see that It needs `MyApi` and therefore execute `MyApiFactory` to get `MyApi` - `MyApi` would then be stored as a service (if the container supports sharing).

Then I ask for `MyService2` which also needs `MyApi` - as `MyApi` has already been created before - it just pulls it from the DI container and injects it in `MyService2`.

Therefore `MyApi` in `MyService1` & `MyService2` are the same.

I can't seem to find a way to do this in Magento 2. Basically I want to avoid creating `MyApi` twice.

The only way I can think to do this is to keep a record of the created `MyApi` inside `MyApiFactory` so the second time `MyApiFactory::create` is called it returns the existing instance. Then I would have to inject `MyApiFactory` into `MyService1` & `MyService2` and call `create` within there constructors or wherever.

This (to me) seems wholly unnecessary and quite unintuitive - is this a problem anyone else has come across? Is there some support for shared services with custom factories in Magento 2 ?

Also - if this feature does not exist and is something that would be accepted - i'd be happy to work on it.

**Comment by veloraven** [comment]
@AydinHassan thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report an issue please create new GitHub issue and format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by AydinHassan** [comment]
@olgalytvynenko this was more a question to the developers of Magento 2 than the community, nevertheless I've created a question here on Magento Stack Exchange: http://magento.stackexchange.com/questions/155528/registering-a-shared-service-with-a-custom-factory
