### ISSUE TITLE
products in category [backend] showing simple product, when created in config product

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#8186]
### Preconditions

1.  Magento 2.1.3, Community 
2. PHP7, MYSQL 5.7

### Steps to reproduce

1. Add a configurable product to a category
2.  You will see in the backend view only that configurable product added [Catalog -> Categories -> find category that you added product to]
3. Go to the configurable product and create more variations
4. Those variations now show in the backend category [not the fronted]

### Expected result

1.  I believe the expected behaviour should be that the simple product don't show in the backend product in category listing unless explicitly added. The reason being it makes it difficult to order your product for the frontend.

### Actual result

1. Simple product is also added to listing in the backend. 
2. This makes it particularly difficult when you a few configurable product with a number of variations.

<img width="1250" alt="screen shot 2017-01-19 at 2 49 13 pm" src="https://cloud.githubusercontent.com/assets/9780829/22090488/e0a60c68-de56-11e6-8112-d5d1fb7987bc.png">

**Comment by rganin** [comment]
> The reason being it makes it difficult to order your product for the frontend.

Could you please clarify what difficulties you've had?

**Comment by rudik99** [comment]
If you have 5 configurable product's in a category and they have 100 variations - that is 500 items you need to sort through so you can number the configurable product to determine the front-end order.

Maybe the solution is better filtering of the grid ?

**Comment by rudik99** [comment]
plus its inconsistent

- When you add a configurable product to a category which already has variations, those variations [simple product] do not show in the backend listing

- When you have attached the configurable product do the category then create more variations, it then add's those news ones to the category listing in the backend [as above]

**Comment by veloraven** [comment]
@rkhoury82 thank you for your report.
Currently this functionality works by design so it is an improvement rather than an issue.
Please submit it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)) as GitHub issue tracker is intended for technical issues only.
