### ISSUE TITLE
During Re-indexing process the catalog data disappears from StoreFront

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#8189]
### Preconditions
- Magento Version: 2.1.3 CE
- PHP: 7.0.14
- Database: MySQL 5.6
- OS: CentOS 7
- Caching: Varnish Cache and OPcache

Whenever the re-index process is in progress (Catalog Search catalogsearch_fulltext in particular), the catalog list data disappears from the store end.

So during that time if anyone visits the category page, 
"no products found" is shown to the customer.

Now once the re-indexing process is completed till the 
time page cache is not flushed, the same "no products found" is shown to the customer

### Steps to reproduce

1. Run reindexing, when catalogsearch_fulltext (Catalog Search) indexing is in progress visit any of the category pages (make sure that those pages should not already be cached)
### Expected result

The catalog products should not disappear when indexing process is running in the backend

### Actual result

1. Till the time the **catalogsearch_fulltext** is running all the product present in the catagory listing page disappear
2. During this period if customer visits the category listing it gets cached as "No products found"
3. Even if the reindex process completes, till the 
time page cache is not flushed, the same "no products found" is shown to the customer

**Comment by veloraven** [comment]
@atishgoswami thank you for your report.
This issue has already been fixed in develop branch and we have internal ticket MAGETWO-58467 for branch 2.1.

**Comment by atishgoswami** [comment]
@veloraven which release version will contain the fix for this issue ?

**Comment by eldonbite** [comment]
Hi @veloraven. Are there commits or pull requests for this issue from which we could create a patch?

**Comment by koenner01** [comment]
This is a duplicate of https://github.com/magento/magento2/issues/6754

There a quite a few commits done on internal the MAGETWO-58174 ticket on the develop branch.
https://github.com/magento/magento2/search?q=MAGETWO-58174&type=Commits&utf8=%E2%9C%93

**Comment by magento-engcom-team** [comment]
@atishgoswami, thank you for your report.
The issue is already fixed in develop branch, 2.2.2

**Comment by magento-engcom-team** [comment]
@atishgoswami, thank you for your report.
The issue is already fixed in 2.2.2

**Comment by AveyBD** [comment]
I am facing the issue :(  Magento ver. 2.2.3

**Comment by 0franco** [comment]
It's not fixed on 2.2.2 version

**Comment by visahardik** [comment]
I am facing same issue while upgrade 2.1.9 to 2.2.5.
Every categories page shows "We can't find products matching the selection."
and when accesign direct product its shows out of stock but in backend its already in stcok.

Any  idea ?

**Comment by ytthuan** [comment]
I am facing this too in the version 2.26, the symptom is very similar with yours.

> I am facing same issue while upgrade 2.1.9 to 2.2.5.
> Every categories page shows "We can't find products matching the selection."
> and when accesign direct product its shows out of stock but in backend its already in stcok.
> 
> Any idea ?

**Comment by zdmvk** [comment]
> I am facing this too in the version 2.26, the symptom is very similar with yours.

My solution after migrated from 1.8 to 2.2.6.
The categories displayed the status "We can't find products matching the selection."
Made Export csv, corrected the number of goods, then made Import csv.

**Comment by haresh1211** [comment]
I am facing the same issue while upgrade 2.1.5 to 2.2.6.
Every categories page shows "We can't find products matching the selection."
In backend its already in stock.

Any solution?

**Comment by githuzz** [comment]
migrated from 1.9.x to 2.3.5-p1, all products are  imported, but no product showing up in front end:We can't find products matching the selection.

**Comment by huykon** [comment]
how to fix this problem?

**Comment by Webalpha97** [comment]
Any solution for this
