### ISSUE TITLE
Magento 2.1.3 adding menu.xml in new module causes redirect loop after login

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#8190]
### Preconditions
Adding menu.xml in a new magento 2.1.3 installation causes redirect loop in the admin

I am creating a new module, but when tried to add menu.xml in etc/adminhtml directory in the module directiory, the browser shows error of redirect loop
Magento Version: Magento CE 2.1.3
Mysql Version:  5.6.28
PHP version: 7.0.8

### Steps to reproduce
1. Install new Magento CE 2.1.3 
2. Create new module in app/code with all required files in etc directory of the module
3. Add menu.xml and add items in the menu
```
<?xml version="1.0"?>
<!--
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
    <menu>
    	<add id="Ktpl_Testimonial::menu" title="IntroBrand" translate="title" module="Ktpl_Testimonial" sortOrder="0" resource="Ktpl_Testimonial::menu"/>
    	<add id="Ktpl_Testimonial::testimonial" title="Manage Testimonials" translate="title" module="Ktpl_Testimonial" sortOrder="0" parent="Ktpl_Testimonial::menu" resource="Ktpl_Testimonial::testimonial"/>
    </menu>
</config>

```

acl.xml

```
<?xml version="1.0"?>
<!--
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
	<acl>
		<resources>
			<resource id="Magento_Backend::admin">
				<resource id="Ktpl_Testimonial::menu">
					<resource id="Ktpl_Testimonial::testimonial"/>
				</resource>
			</resource>
		</resources>
	</acl>
</config>

```
### Expected result
It should add a main menu item in the admin menu and a child menu item in the new menu item.

### Actual result
It creates a redirect loop when try to log in to the admin

![screenshot from 2017-01-19 12 44 34](https://cloud.githubusercontent.com/assets/10272277/22097084/32fe90dc-de45-11e6-92c8-f5046f193805.png)

**Comment by nmalevanec** [comment]
@Taral-Patoliya 
Unfortunately, I could not reproduce the issue as you described it. 
![image](https://user-images.githubusercontent.com/11520943/30328357-c2a4ddda-97d7-11e7-931b-60cbd8b20dde.png)

**Comment by magento-engcom-team** [comment]
@Taral-Patoliya thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
