### ISSUE TITLE
Paypal Payment Order Transaction ID Link will result to 404 not found because of this url:https://www..paypal.com/cgi-bin/webscr?cmd=_view-a-trans&id=

### ISSUE THREAD

**Issue by earlelnar** [magento/magento2#8191]
**Preconditions**

1.  Choose a product and add it to your cart.
2.  Checkout the product with paypal.

**Steps to reproduce**

1. Go to the backend of the website. and navigate to this option: 
    stores>order and there in the order information. below in the lower left portion of the page, you can    see  the transaction ID just like the screenshot below.

    
![screenshot_1](https://cloud.githubusercontent.com/assets/14094984/22132343/672fdd98-def4-11e6-8770-766e6caba9e8.jpg)

**Expected Result**

1. If you click the transaction ID link it will open up with no issues at all.

**Actual Result**

1.  If I click the Transaction ID link it will result to 404 page not found. and as I noticed in the url of the   transaction link it has an double dot instead of one. see the screenshot below for reference.

![arrow](https://cloud.githubusercontent.com/assets/14094984/22132235/ba74c064-def3-11e6-8b8a-4a7ea2be2b2a.jpg)

**Why?**

1. Because the link of the transaction ID. has a double dot. like this one **"www.."**

**Comment by veloraven** [comment]
@mazestricks thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by earlelnar** [comment]
Hi @veloraven 

I have now updated my thread with the issue reporting guidelines please correct me if I'm wrong.

Thanks,
MazeStricks

**Comment by alena-marchenko** [comment]
Hi @mazestricks 

We've created MAGETWO-63406 internal ticket regarding this issue.
Thank you!

**Comment by earlelnar** [comment]
Hi @alena-marchenko 

Thanks for acknowledging this one.

Thanks, 
MazeStricks

**Comment by gesell** [comment]
Where does this link get created? I'd like to hotfix it.

Regards,
H

**Comment by earlelnar** [comment]
Hi @gesell 

Whenever there's a successful order of customer through paypal in the store. You can see it under stores>oder and there just like the screenshot that I've posted above.

Thanks,
Mazestricks

**Comment by alena-marchenko** [comment]
Hi @mazestricks 

Fix for MAGETWO-63406 is merged to develop branch, closing the issue.
Thank you.
