### ISSUE TITLE
Issue with curency PRK

### ISSUE THREAD

**Issue by minhnt12081991** [magento/magento2#8192]
I needs to use currency for my store USD, PKR.
With USD , price in product display correct in list and product detail.
But with PKR, in list product, price display correct.
In Product detail, pride display incorrect. 
I test on magento 2.1.3
So, Please guide us to resolve this issue
http://prntscr.com/dxjug2
http://prntscr.com/dxjuci
http://prntscr.com/dxju7y

**Comment by veloraven** [comment]
@minhnt12081991 GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report an issue please create new GitHub issue and according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
