### ISSUE TITLE
Rest API attribute options possible incongruences

### ISSUE THREAD

**Issue by NotAndD** [magento/magento2#8199]
### Preconditions

1. Install Magento 2.1.3 with sample data.
2. Set up Rest integration.

### Steps to reproduce

1. Try to delete an attribute option, using a REST request to delete /V1/products/attributes/{attributeCode}/options/{optionId} using method DELETE. An option_id is asked when, according to documentation of the attribute options, attribute options uses the following schema:
```
[
  {
    "label": "string",
    "value": "string",
    "sort_order": 0,
    "is_default": true,
    "store_labels": [
      {
        "store_id": 0,
        "label": "string"
      }]
  }
]
```
and has no option_id as field.

### Expected result

1. Attribute options should contain an option_id to be identified.

### Actual result

1. Attribute options are identified using the value field as an id. The value can't be set via creation because it acts just as an id.

### Notes
I understand this is no big of a deal, but it did make me lose time when I tried to modify and delete attribute options programmatically and so I feel like I should write this. It should be explained in the documentation that the option id is the value and that the value is not a real value but rather, just an automatic id to identify options. I think that Value is an ambiguous name for an automatic identifier.

**Comment by misha-kotov** [comment]
Thanks for reporting this - we'll work on adding it to our documentation.

**Comment by magento-engcom-team** [comment]
@ziliquas, thank you for your report.
We've created internal ticket(s) MAGETWO-81370 to track progress on the issue.
