### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by alexander-sibert** [magento/magento2#82]
Hi, i hope that is not a wrong place for general suggestions for Magento 2.

What i wish is following:

1. jQuery as JavaScript Framework. The Community of jQuery is bigger, more Plugins ...
2. For default SEO friendly Layered Navigation with no Duplicate Content generation.
3. More Performance. I need a big machine with some optimiziations like Varnish to run Magento fast. The performance is often the reason why people/companies use a other shopsystem than Magento.
4. A better Dataflow Import- and Exportengine with possibility to export easy products with assigned categories.
5. Improved Multilanguage Support. The best solution for Multilanguage i found in Drupal 7. Here you can set a lot of Multilanguage Settings how to handle the Language checking and you can define a prefix for the languages.

For example, i have a german Magento Online-Shop:

http://www.domain.de (German; without Prefix)
http://www.domain.de/en/ (United Kingdom)
http://www.domain.de/fr/ (France)

etc.

6. Germany has specify laws for eCommerce. At the moment we use different german market extensions from the Magento Community to have all these things.

http://www.magentocommerce.com/magento-connect/market-ready-germany.html

It has some bugs or issues. I think that is better for Magento and Users/Developers to have it for default in Magento Core. Germany has a great ecommerce market.

7. A better Translate Engine than the CSV engine. Drupal 7 use a Database Translating Engine which is fast and easy to edit.

Greetings, Alexander

**Comment by piotrekkaminski** [comment]
Thanks for all the suggestion. We are using some of them already. I'm closing this issue. Feel free to provide new suggestions as new issues.
