### ISSUE TITLE
Error: Composer could not find a composer.json file in /setup

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#820]
Unsable to install Magento2 via command line.
```
cd /path/to/magento2/setup
composer install
```
gives the following error:
>Composer could not find a composer.json file in /setup
>To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ >"Getting Started" section

**Comment by verklov** [comment]
@MagePsycho, we'd like to hear from you whether you had your issue resolved using the recommendations in the thread.

**Comment by maksek** [comment]
There is no need to run composer in /setup folder, please refer the doc -http://devdocs.magento.com/guides/v1.0/install-gde/install/install-web.html
Closing the issue
