### ISSUE TITLE
Rest API adding custom option to a product

### ISSUE THREAD

**Issue by NotAndD** [magento/magento2#8200]
### Preconditions

1. Install Magento 2.1.3 with sample data.
2. Set up Rest integration.

### Steps to reproduce

1. Try to create a product custom option, sending a REST request to post /V1/products/options with Method POST correctly, adding a custom option to a product. As store view, tried to both use all and default.
Like this:
```
{
"option": {
   product_sku = "product_test_sku",
   is_require = true,
   title = "Option just to test",
   type = "area",
   sort_order = 0,
   price = 100,
   price_type = "fixed",
   sku = "test_sku"
   }
}
```
2. Receive the correct answer, meaning that the option is created in the product. Check on the web interface from the admin view that the option is there with all the correct values and everything seems correct, the option was correctly created and added to the right product.

### Expected result

1. The new custom option should be visible on frontend when searching the product, available to be used.

### Actual result

1. The new custom option doesn't appear on the frontend, even if it's visible on the the web backend. It doesn't appear on web frontend UNTIL the product is saved from the web interface. Saving the product on web interface as admin immediately make the not-visible option appear on frontend, exactly as it was saved by the rest api.

### Notes
It's probably a problem of indexing on custom options with Rest api, doesn't automatically reindex when they modify or delete or create custom options?
Because Products are automatically modified when updated from rest api, so I expected the same behaviour for custom options also.

**Comment by NotAndD** [comment]
If I reindex from command line using `magento indexer::reindex catalogrule_rule` it works. So this mean that Rest API do not reindex on custom options as they do for other entities.

**Comment by NotAndD** [comment]
I'll add some more infos since I tried various things to see what could be or not be the problem.

First of all, adding a custom option using a Rest API request like I wrote, doesn't reindex automatically. You either need to ask a reindex or save the product modified with the new option added. Doing so by Rest API or web interface or whatever works and the new option is visible on frontend.
This for me is a bug, reindex should be called automatically.

Second thing, adding a custom option to a product doesn't automatically set the `has_option` property in it. So, if the property is not properly set, the options will be not visible until the property will be modified.
This instead is not an error, you can check by yourself the product and update it if needed. But for sure it makes things more slow when programmatically working on custom options.

**Comment by misha-kotov** [comment]
Thanks for reporting the issue. From what I'm seeing, the first issue (seeing the new custom option reflected on frontend) is caused by the second issue (has_options flag). 

If a product already has a custom option created in Admin (has_options=1), and I add a custom option using the API, you can see it immediately on the frontend without reindexing. However, if it's the first option you're adding to the product via API, it won't work until you manually set the has_options flag. I've created an internal ticket for this issue: MAGETWO-64324

**Comment by magento-engcom-team** [comment]
@ziliquas, thank you for your report.
We've created internal ticket(s) MAGETWO-64324 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ziliquas, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
