### ISSUE TITLE
Build/Deployment Performance Issue with setup:static-content:deploy (useless work + disk space)

### ISSUE THREAD

**Issue by OZZlE** [magento/magento2#8201]
Running php bin/magento setup:static-content:deploy creates:
pub/static/[frontend/adminhtml]/[vendor]/[theme]/[===>_all_site_languages<===]/...

which is only nessesary for 1 file (js-translations.js) *assuming each store uses the same theme*.

### Preconditions

1. Latest M2
2. Multiple websites/store groups/storeviews BUT all use the same theme.

### Steps to reproduce

1. run in console: php bin/magento setup:static-content:deploy [[all_languages_used_on_site]]
2. check pub/static/[frontend/adminhtml]/[vendor]/[theme]/[_all_site_languages]/
3. check the size of the project using 10 different languages = ~1GB 

### Expected result

1. All languages could be symlinked (except for the js-translations.js file) to en_US because Less/CSS content translations can use :lang([language_code])  => https://www.w3.org/International/questions/qa-css-lang
2. size of project should be smaller than ~1GB

### Actual result

1. size of the project using 10 different languages = ~1GB

**Comment by OZZlE** [comment]
I have tested this on a site and our customer is happy that it's working ^^

**Comment by OZZlE** [comment]
*maybe* useful if you have different themes for different stores?

**Comment by OZZlE** [comment]
The only file that is actually needed inside every language folder is the js-translation.js where javascript gets it's translations from if all stores share the same theme

**Comment by IlnitskiyArtem** [comment]
Hi, @OZZlE. Please specify the exact version of Magento you use.

**Comment by OZZlE** [comment]
@IlnitskiyArtem I reported it for 2.1.1 but it's relevant for 2.1.7 also, I know that you have implemented parallell static deployment which helps a bit but it's still not useful work and disk space when the site uses the same theme across all stores.

**Comment by IlnitskiyArtem** [comment]
Hi, @OZZlE. I've linked this GitHub issue to internal ticket MAGETWO-70950.

**Comment by hostep** [comment]
@IlnitskiyArtem: This was already sort of fixed in Magento 2.1.3, but a new bug was introduced due to those optimizations: https://github.com/magento/magento2/issues/7862, that last bug looks like was also already fixed on the develop branch, but I haven't checked it out yet...

**Comment by magento-engcom-team** [comment]
@OZZlE, thank you for your report.
We've created internal ticket(s) MAGETWO-70950 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @OZZlE

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@OZZlE, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
