### ISSUE TITLE
Magento 2.1.3 Cart Does not update sometimes

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#8205]
### Preconditions

1. Magento 2.1.3, Luma theme, no changes made in theme
2. 

### Steps to reproduce

1. Add Item to cart
2. 
3. 

### Expected result

1. Item should be added to cart

### Actual result

1. Cart is still empty. We get a message saying item has been added to cart but when you click on cart it says cart is empty.

**Comment by Sanfam** [comment]
@adityag186 , out of curiosity, would you mind confirming the following pieces of information and trying a few things? 

- What environment is this magento instance running on?  Version of PHP and type of caching enabled?
- When attempting to add the item to the cart, did you initially navigate to that product page from another page on the site by clicking a link?
- If not, was this page already loaded for some extended period of time?
- Can this be reproduced if you navigate back to the home page, navigate to the product, wait 5-10 seconds and *only then* click **add to cart**?

**Comment by adityag186** [comment]
1. PHP 5.6, using siteground cloud hosting server, magento inbuilt cache used.
2. I navigated to product page from home page and added to cart.
3. It happens sometimes, not always.

**Comment by veloraven** [comment]
@adityag186 thank you for your report.
Please provide some additional information:
1. Does it happen to products of all types or just to some ones?
2. Please provide information about your environment: OS, versions of MySQL and web server. PHP version is 5.6 as I can see from the previous comment.
3. Information about Magento mode.
4. Are there any corresponding errors in logs?
5. Was it clear install or upgrade from some other version?

**Comment by ghost** [comment]
Same problem. With some Javascript Errors.
![capture](https://cloud.githubusercontent.com/assets/3214981/22517147/7e598d12-e8a8-11e6-8b94-0b3e3b19d4a4.JPG)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
