### ISSUE TITLE
Regarding dropdown for my account signin / create account in magento 2

### ISSUE THREAD

**Issue by manojs229** [magento/magento2#8207]
/guides/v2.0/frontend-dev-guide/layouts/layout-practice.html

Hi Please tell me , its fine working for it show only after login . but i want dropdown for sign in and create an account under my accont text . so i can add in my project . plz let me know how can i do this.

Regards
Manoj Sonawane

**Comment by veloraven** [comment]
@manojs229 thank you for your feedback.
    The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by Prakashraj-asaikanan** [comment]
i cannot find answer............. please share the answer @manojs229
