### ISSUE TITLE
Can't set an image as swatch in my products

### ISSUE THREAD

**Issue by logixio-jp** [magento/magento2#8208]
### Preconditions
1. Magento 2.1.3

### Steps to reproduce
1. In a product, upload an image.
2. Click on it to set the image role

### Expected result
1.  As showed in this screenshot, the image should be used as a "Swatch image" : http://www.magestore.com/magento-2-tutorial/wp-content/uploads/2016/02/5.png

### Actual result
1. On my side, I can only choose between 3 choices instead of 4 : Base, Small, Thumbnail
![image](https://cloud.githubusercontent.com/assets/25106110/22136870/7e5c478a-dea5-11e6-9e00-3011aa3d564f.png)

Thanks!

**Comment by korostii** [comment]
Are you editing a simple product or a configurable one?

**Comment by logixio-jp** [comment]
I'm editing the simple product. And that simple product is linked to a configurable product.

I can't find any documentation about adding a custom swatch for a simple product in the official Magento 2 documentation. I'm asking myself if it's still implemented in the 2.1.3 version. Or maybe it's an issue linked to the importation of my 1.9 data? 

I will try it on a fresh install with simple data tonight.

**Comment by korostii** [comment]
Just checked on a simple product, 2.1.3, seems to work fine.
http://take.ms/Wo5IZ http://take.ms/OKnSF
One thing that comes to mind is that you might need to do some setting up on the attribute(usually "color") first as described here https://www.mageworx.com/wiki/magento2-color-swatches-config/ - that is, on a clean installation, sample data already has it done.

**Comment by korostii** [comment]
> Or maybe it's an issue linked to the importation of my 1.9 data?

On that part, unfortunately, I can't help you, have no experience in such migrating. Although that seems less likely if the link to the configurable product is indeed okay.

**Comment by logixio-jp** [comment]
Got some time to look at it yesterday. The problem is linked to the migration.

When migrating, the "Data migration tool" is creating new attributes set based on the Magento 1 configuration. Migrated attribute set are called "Migration_OLDNAME". The problem is that this old attribute set doesn't contain the attribute "swatch_image".  

Adding this attribute to my attribute set solved the problem!
