### ISSUE TITLE
Catalog Price Rules and wrong faceting / sorting

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#8209]
### Preconditions

1. Magento 2.1.* (tested on 2.1.2 and 2.1.3)
2. PHP 7
3. MySQL 5.6

### Steps to reproduce

1. Install Magento.
2. Use the sample data, since they provide an easy use case.
3. Check that the sample data rule "20% off all Women and Men pants" is enabled.
4. Process a full search reindex
5. Go to the "Men", "Bottom" category
6. Apply sorting by price, Ascendant.
7. Try to filter on the "20 - 29.99" price range

### Expected result

1. For the **6.** step, products should be displayed in the correct order (price, ASC)
2. For the **7.** step, we should see the "Caesar Warmup Pant" which is discounted to **28$** from **35$** base price. See This screen : 
![selection_210](https://cloud.githubusercontent.com/assets/15340849/22146509/2d29b842-df05-11e6-8186-e12a4386c60b.png)

### Actual result

1. For the **6.** step, products are displayed in irrelevant order : 
![selection_211](https://cloud.githubusercontent.com/assets/15340849/22146559/585d195a-df05-11e6-9e11-f6355f92a165.png)

2. For the **7.** step, the "Caesar Warmup pant" does not appear.

For me the issue is clear : since the sorting/faceting only uses the ```catalog_product_index_price``` table for **indexing** 

=> the discounted prices coming from the catalog rule applications are therefore not stored in this index table, and cannot be indexed in the engine, so the sorting and faceting features cannot work properly actually.

PS : This is not only a CE issue, it has been tested KO the same way on a EE version using elasticsearch.

**Comment by Yonn-Trimoreau** [comment]
+++++++1200000

**Comment by miakusha** [comment]
Thanks for report but it's known issue
Closed as duplicate #7465
