### ISSUE TITLE
Rest API get stock_items with low stock not behaving like other get methods

### ISSUE THREAD

**Issue by NotAndD** [magento/magento2#8211]
### Preconditions

1. Install Magento 2.1.3 with sample data.
2. Set up Rest integration.

### Steps to reproduce

1. Retrieve stock_item list of low stock items sending a Rest request to /V1/stockItems/lowStock/ with method GET, query parameters scope_id and qty as specified in the documentation. Rest request like this: `rest/default/V1/stockItems/lowStock/?scopeId=0&qty=10`.

### Expected result

1. As for all other Rest methods available that returns a list taking filter parameters and as the documentation specify, if no page_size is given, all results of the query should be returned.

### Actual result

1. Only one stock item is returned, in addition, search_criteria has a different structure from other methods, with a limit field that is automatically set like this:
```
"limit": [
      "1",
      "0"
    ]
```

### Notes
Either changing the documentation (fast solution) or even better, uniforming this method with all the other available methods, making it accept a filter and not only page filter parameters (page_size and current_page).

### Additional info
- Reproducible on Magento 2.4-develop
- The way it can be reproduced via Swagger 
1. In your web browser open _http://{magento2 instanse}/swagger#/integrationAdminTokenServiceV1/integrationAdminTokenServiceV1CreateAdminAccessTokenPost_ click **Try it out**
![try_it_out](https://user-images.githubusercontent.com/51680745/71408582-6eb34f80-2647-11ea-96ab-7b60f58cd983.png)
2. Set admin User name and Passwod and click Execute 
3. Copy the token from the _Response body_ 
![token](https://user-images.githubusercontent.com/51680745/71408693-c6ea5180-2647-11ea-8cbc-11c279d23c31.png)
and Paste it into _api_key_ field in the top right corner. Click Apply
![api_key](https://user-images.githubusercontent.com/51680745/71408814-25afcb00-2648-11ea-8b20-f038b3d60e7f.png)
4. Open _catalogInventoryStockRegistryV1_  - GET _/V1/stockItemslowStock_ clcik Try in out
![low stock_catalog](https://user-images.githubusercontent.com/51680745/71409005-bc7c8780-2648-11ea-85e1-d0cbe96ca65c.png)
5. Set scopeId to **0** qty to **10**. Click Execute
![scope_qty](https://user-images.githubusercontent.com/51680745/71409143-2bf27700-2649-11ea-8bdf-f91a1a766056.png)

Actual Result: 
![limit](https://user-images.githubusercontent.com/51680745/71409257-96a3b280-2649-11ea-9d33-f1f04d0f2aad.png)

**Comment by magento-engcom-team** [comment]
@ziliquas, thank you for your report.
We've created internal ticket(s) MAGETWO-81168 to track progress on the issue.

**Comment by timpea** [comment]
Is there any update on this bug?

**Comment by atsareva** [comment]
Any updates here?

**Comment by Hexmage** [comment]
A workaround is setting the page_size parameter to a very large number.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30059` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
These API is deprecated, please have a look at the documentation below to get more details on the new APIs that should be used instead:
https://devdocs.magento.com/guides/v2.4/inventory/index.html
https://devdocs.magento.com/guides/v2.4/inventory/catalog-inventory-replacements.html

Thanks.
