### ISSUE TITLE
Magento 2.1.3 Fatal error on some category pages

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#8223]
### Preconditions

1. Magento version 2.1.3
2. 

### Steps to reproduce

1. Go to http://www.dev.atlanticbooks.com/subjects/business-management
OR
2. Go to  http://www.dev.atlanticbooks.com/about-us

Error occuring on some of the category pages only.

### Expected result

1. website should open that page

### Actual result

1. Fatal error: Allowed memory size of 1388314624 bytes exhausted (tried to allocate 83 bytes) in /home/devatlanticbooks/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 293

**Comment by JamesonNetworks** [comment]
You could try upping the PHP memory limits. I believe that has fixed this issue for me in the past.

**Comment by veloraven** [comment]
@adityag186 thank you for your report.
Please provide additional information:
1. Please provide exact steps to reproduce and descriptions of your categories without external links.
2. Please provide information about your environment: OS, versions of PHP, MySQL and web browser.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
