### ISSUE TITLE
Coupon Code doesn't work

### ISSUE THREAD

**Issue by aaronallen8455** [magento/magento2#8224]
Coupon code with a specific coupon and a user defined code (not auto-generated) is not usable.

### Preconditions

1.  Magento 2.1.3

### Steps to reproduce

1. Create a cart price rule coupon with a set code (not auto-generated).

### Expected result

1. Coupon code is usable on frontend.

### Actual result

1. Code is invalid.

I found this workaround - make an auto-generated coupon code, then in the `salesrule_coupon` table change the auto-generated code to the code that you want.

**Comment by pboisvert** [comment]
Can you follow the issue reporting template and provide system configuration info as well?

**Comment by patrickdesroches** [comment]
Hi,

I have the same issue with Enterprise 2.1.3 and PHP 7.0.8.

Coupon codes that are not auto-generated seem to work fine.

Thanks

**Comment by magento-engcom-team** [comment]
@aaronallen8455, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
