### ISSUE TITLE
Why do i see configurations at simple product and how can i remove it in Magento 2?

### ISSUE THREAD

**Issue by petercap** [magento/magento2#8226]
Why do i see configurations at simple product and how can i remove it in Magento 2?

There's a section where i can add Configurations even when i choose to Add Simple Product and i'd like to remove it.

There's another section with a title Downloadble that i was able to disable by change the code in its Composite.php file.

from:

        DownloadableType::TYPE_DOWNLOADABLE,
        CatalogType::TYPE_SIMPLE,
        CatalogType::TYPE_VIRTUAL

to:

        DownloadableType::TYPE_DOWNLOADABLE,
        CatalogType::TYPE_VIRTUAL

i was looking for a similar solution but the code is different.

Thank you

**Comment by veloraven** [comment]
@petercap thank you for your feedback.
    The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report an issue please create new GitHub issue and format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
