### ISSUE TITLE
After upgrade to 2.1.3 url rewrite problem multi store

### ISSUE THREAD

**Issue by philipvandebriel** [magento/magento2#8227]
### Preconditions

1. Magento 2.1.3
2. Nginx/Debian8/Mysql

### Steps to reproduce

1. Add new product or
2. change old url and save product or 
3. delete a url and save product

### Expected result

1. url rewrite like this ( in 2.1.2 everything ok )  www.domain.com/xxxxxxx.html

### Actual result

1. we get an url like this : catalog/product/view/id/7775/s/XXXXXXXXXXXXX/

If we check the url rewrite table in the database then all the url's are deleted with product id 7775
If we save the product nothing change and can not found the urls anymore in de url rewrite table.

If we save a product (from magento 2.1.2) and don't change the url then the rewrite-url is ok.
We use multistore with url store code.

**Comment by naydav** [comment]
Unfortunately, I could not reproduce the issue as you described it on 2.1.3 version. Please provide the detailed steps we must follow to reproduce this issue.
Need more information about:
- Do you have got problem after upgrading from 2.1.2 to 2.1.3 or you use clean 2.1.3 installation?
- Do you have several store views on one website?
- Specify what Product Url key you entered at product creation.
- Specify what Product Url key you entered at product updating. Did you check "Create Permanent Redirect for old URL" checkbox while product url updating?
- What does it mean "delete a url"?
Please provide detailed steps to replicate issue
Thanks in advance

**Comment by philipvandebriel** [comment]
@naydav 
- Yes we did an upgrade from 2.1.2 to 2.1.3
- We have 6 storeviews on 1 website
- We use the name from the product as Pruduct Url, if we delete the url and saved again without url then we can't found the url_key anymore in the table URL_REWRITE. 
- we try with and without check Permanent Redirect 301 url.
- Delete a url means , we delete the url key from the product and save the product again. After we can found anymore the product url in the url_rewrite table. (example product 7775)
- ALso we never delete self something in the URL_REWRITE table.
- Categories url-rewrites everything normally
![schermafdruk 2017-02-01 18 01 47](https://cloud.githubusercontent.com/assets/15958461/22517259/e062363a-e8a8-11e6-9b41-1255f1a8b241.png)
![schermafdruk 2017-02-01 18 02 53](https://cloud.githubusercontent.com/assets/15958461/22517266/e67f6e16-e8a8-11e6-88e7-71eadb998616.png)
![schermafdruk 2017-02-01 18 11 55](https://cloud.githubusercontent.com/assets/15958461/22517588/f2c984c6-e8a9-11e6-8164-c4ddd96f0301.png)

**Comment by naydav** [comment]
I still could not reproduce the issue.

#### Steps to reproduce:
1. Install Magento 2.1.2. Single-Store mode is disabled.
2. Create two store views (store_2, store_3), enable them and assign to Main Website Store (Stores > All Stores)
3. Create two Simple Products (with URL Keys: product-1, product-2). Assign created products to new category Cat-1

Db state after steps:
![8227-1](https://cloud.githubusercontent.com/assets/537688/22547848/500fe056-e94c-11e6-98a7-ffc993f056d4.png)

**Pay attention:**
request_path - it is URL path to reach product on frontend
target_path - it is how to this request_path will be processed in Magento internally

Created products are reacheable on frontend by next urls:

**Product 1:**
*magento2.1.local/product-1.html*
*magento2.1.local/cat-1/product-1.html*

**Product 2:**
*magento2.1.local/product-2.html*
*magento2.1.local/cat-1/product-2.html*

4. Up Magento version to 2.1.3
   * update code via git or composer
   * run "php bin/magento setup:upgrade"
   * update static if needed (php bin/magento setup:static-content:deploy)
   * run "php bin/magento --version". Result is Magento CLI version 2.1.3

5. Open "Product-1" edit page in Magento admin panel. Change "Search Engine Optimization > URL Key" field on "product-1-2" (Create Permanent Redirect for old URL is checked). Save product.
6. Open "Product-2" edit page in Magento admin panel. Delete the value from "Search Engine Optimization > URL Key" (Create Permanent Redirect for old URL is unchecked). Save product.

Db state after steps:
![8227-2](https://cloud.githubusercontent.com/assets/537688/22547856/59072430-e94c-11e6-8ca0-70ef2b6b6615.png)

Our products are reacheable on frontend by next URLs:

**Product 1:**
*magento2.1.local/product-1.html* will be redirected(301) on *magento2.1.local/product-1-2.html*
*magento2.1.local/cat-1/product-1.html* will be redirected(301) on *magento2.1.local/cat-1/product-1-2.html*
*magento2.1.local/product-1-2.html*
*magento2.1.local/cat-1/product-1-2.html*

**Product 2:**
*magento2.1.local/product-2.html*
*magento2.1.local/cat-1/product-2.html*

So, all works properly.

#### Aditional questions:
* Provide "Stores >Configuration > Catalog > Search Engine Optimization" settings (per store)
* How do you perform the Magento update?
* How do you get "catalog/product/view/id/7775/s/XXXXXXXXXXXXX/" URL? Did you click on category menu (or some custom element)?
* Does product have custom settings?

**Comment by philipvandebriel** [comment]
Okay maybe i can explaine it better now ,
**part 1**
- one website 5 storeviews
- product ID 7791
- Storeview 1,2,3,5 have url key with "use default value" check for url_key
![schermafdruk 2017-02-05 10 50 15](https://cloud.githubusercontent.com/assets/15958461/22625287/056dc9b2-eb92-11e6-9b5d-28ebd541c08a.png)
- Last url_rewrite_id is 1241328

**part 2**
- Go to products=>catalog=>edit product 7791=>uncheck use default value and change url_key
- Save product
- Now i have the url key from store 4 in my url_rewrite table
![schermafdruk 2017-02-05 10 50 51](https://cloud.githubusercontent.com/assets/15958461/22625308/9cfc2828-eb92-11e6-9f6e-92f608def2d4.png)
- Last url_rewrite_id is 1241329 ( add 1 url key in my url_rewrite table), everything ok

** Part 3 **
- Go to products=>catalog=>check product 7791=>Actions=>update attributes=>websites=>Add Product To Websites - check main website=>SAVE
- if i open my url_table then i see now 5 url_rewrites deleted and i get 4 new url_rewrites except for store 4. So only if i check default value then i get a url_rewrite.
![schermafdruk 2017-02-05 10 52 57](https://cloud.githubusercontent.com/assets/15958461/22625335/b3d82af0-eb93-11e6-8a5f-17f164dda1e0.png)
- Last url_rewrite_id is 1241330-1241333

**Comment by naydav** [comment]
Thanks
I was able to reproduce the issue.
Created internal issue MAGETWO-64191 to investigate and track this issue.

Thanks in advance

**Comment by philipvandebriel** [comment]
@naydav is there a fix in magento 2.1.4 ?

**Comment by philipvandebriel** [comment]
@naydav Same problem in Magento 2.1.4 !

**Comment by TheBelstrup** [comment]
@naydav I have been debugging this issue, and it is related to how the findOneByData method (called in the \Magento\Catalog\Model\Category:getUrl() method) fetches url paths from the url_rewrite table.

Basically, it grabs one - random - row from the url_rewrite table. In case where one or more url rewrites have been written to the url_rewrite table for a category or a product, you might just as well get a record with a redirect_type of 301 as the current correct url (redirect_type = 0).

A more correct implementation would be to apply a sort order to the records (based on redirect_type ascending), so that the returned row would be the one with redirect_type=0 or - in case that doesn't exist - any other row (usually a 301 redirect one).

**Comment by peterkeijsers** [comment]
I have similar problems. It seems to be related to updating the website attribute of the product. I have a product with 4 url_key values set at storeview scope and 2 url_key values at default scope. At first the product seems oke. All 6 url_keys are stored in the url_rewrite table and all is fine.
When I mass-update this product via the backend, and I allocate the product to my website (again, as it already was allocated to it) then all url_rewrite entries dissappear except for those whose url_key value is set on default scope. 

So triggering an update of this 'website' attribute is causing url_rewrite entries to dissappear somehow.

**Comment by thlassche** [comment]
I developed a solution that can regenerate the rewrites using the CLI, which fixes the above for me. Contact me if you need it.

**Comment by heresh80** [comment]
I need it thlassche!

**Comment by thlassche** [comment]
@heresh80 Can't find your e-mail, please drop me an e-mail on contact@thlassche.nl

**Comment by FranRoy** [comment]
Hi, I'm using magento 2.1.7 with 2 stores and it happens to me to products that are in both websites.
Is there any update?

**Comment by magento-engcom-team** [comment]
@philipvandebriel, thank you for your report.
We've created internal ticket(s) MAGETWO-75585 to track progress on the issue.

**Comment by BarnyShergold** [comment]
We have 2 M2 instances where we are getting this issue -

A product on the M2 instance is allocated to two websites, it has not been modified for nearly a year (the timestamps on catalog_product_entity) and was working fine on both sites. At some point recently the URL of the product has reverted to catalog/product/view/id/1083/s/..... form on ONE of the websites, on the other it is still fine. Checking the url_rewrite table shows that the entries for this product on the affected site are all gone. 

It sounds like our issue is related to this open issue but the rewrites are being deleted without the product being updated - does anyone have any comments?

**Comment by real34** [comment]
Same here!

In our case, the store has been migrated from M1 using the data migration tool. We haven’t yet checked on a fresh M2 install with sample data…

**Comment by magento-engcom-team** [comment]
Hi @philipvandebriel. Thank you for your report. 
The issue has been fixed in magento/magento2#13567 by @adrien-louis-r in 2.2-develop branch
Related commit(s):
 - [1ef4dcc110062612e9971d7f8fb788bef213df3f](https://github.com/magento/magento2/commit/1ef4dcc110062612e9971d7f8fb788bef213df3f)
 - [864f371aed88884fb73082deb0c856819c43a41f](https://github.com/magento/magento2/commit/864f371aed88884fb73082deb0c856819c43a41f)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @philipvandebriel. Thank you for your report. 
The issue has been fixed in magento/magento2#14252 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3](https://github.com/magento/magento2/commit/03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3)
 - [1322d8be3e64695effbfb525a22c3aed02587b1e](https://github.com/magento/magento2/commit/1322d8be3e64695effbfb525a22c3aed02587b1e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by OZZlE** [comment]
@magento-engcom-team those commits you refer to seems to be only test cases rather than the actual fix? I'm trying to backport this to 2.1.12 also...

**Comment by aloross** [comment]
@OZZlE, quoting myself from the associated PR.

> We discovered that, in the 2.2-dev branch, the issue was fixed by side effect in this commit: a0d3a63. This PR just provide the tests we were using when fixing the issue but the fix itself is already merged (see: a0d3a63#diff-4e1fd4e484fc5142fc23f8ef0cde6718L53).

**Comment by OZZlE** [comment]
@adrien-louis-r it was another bug in <2.3

Looks like a bug in catalog-search module.

It uses websiteId instead storeId when building tmp search table.

Here is diff comparing to 2.2.3:

Patching this fixed the issue with missing products in grid.

```--- ./Model/Search/FilterMapper/TermDropdownStrategy.php	(date 1523456583000)
+++ ./Model/Search/FilterMapper/TermDropdownStrategy.php	(date 1523456583000)
@@ -98,7 +98,7 @@
             'search_index.entity_id = %1$s.entity_id AND %1$s.attribute_id = %2$d AND %1$s.store_id = %3$d',
             $alias,
             $attribute->getId(),
-            $this->storeManager->getWebsite()->getId()
+            $this->storeManager->getStore()->getId()
         );
         $select->joinLeft(
             [$alias => $this->resourceConnection->getTableName('catalog_product_index_eav')],```

**Comment by peterjaap** [comment]
@magento-engcom-team that is not the fix, that is just an integration test. Could you refer us to the actual commit that *fixes* it?

**Comment by samuel27m** [comment]
Anyone looking to backport this issue, the workaround that worked for me with Magento 2.1.6 was commeting the line 144 of file vendor/magento/module-catalog-url-rewrite/Model/ProductUrlRewriteGenerator.php or app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php, depends on your folder structure

Still trying to find any problems with this approach, none so far

**Comment by peterjaap** [comment]
~~@samuel27m could you link to that exact line in the Github repo? In my 2.2.5 installation that line is `return $urls;` which I doubt is the line you mean.~~

Found it; https://github.com/magento/magento2/blob/2.1.6/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php#L144

**Comment by samuel27m** [comment]
@peterjaap yes, exactly that one.
Do you know if there any problem that removing that line can bring up? I've ran many tests creating and removing product URL's but no errors so far.

**Comment by jlfguthrie** [comment]
I am experiencing this on 2.2.4. Can anyone confirm if this issue has been resolved in a later release?
Any other workarounds in the meantime?

**Comment by jagoman85** [comment]
This is the easiest and best solution: https://www.ubertheme.com/magento-tutorials/fixing-url-rewrite-after-migrating-magento-2/

**Comment by hirensoni2005** [comment]
I am facing the same issue for the category after upgrading Magento 2.4.0 to Magento 2.4.1
