### ISSUE TITLE
Unable to set weight of virtual products using import

### ISSUE THREAD

**Issue by jeanpham** [magento/magento2#8228]
### Preconditions

1. Magento 2.0.10

### Steps to reproduce

1. Add a configurable product
2. Create a CSV with columns sku and weight
3. Import the CSV 

### Expected result
1. Does this have a weight? should be 'yes' 
2. Weight field is filled

### Actual result
Nothing is updated!

**Comment by KrystynaKabannyk** [comment]
Hello @jeanpham, could you please clarify, are you describing the case with virtual or configurable products? Because you have different title and description.

**Comment by mbrinton01** [comment]
@jeanpham Virtual products do not have weight.  Can you clarify if you are trying to import virtual or simple (actual) products?  Also, please provide .csv file or a sample of rows from the file.

**Comment by jeanpham** [comment]
Hello @KrystynaKabannyk, sorry for my late reply; I'm trying to apply it to virtual products. 

The version mentioned (2.0.10) has been upgraded to 2.1.3, but unfortunately, it doesn't work either. 

@mbrinton01 When I click on a virtual product in the admin, I'm able to set a weight and set "this item has a weight".

**Comment by mbrinton01** [comment]
@jeanpham you are able to do that, but when you save the product, it will convert to a simple product because a virtual product cannot have weight. Does this help?

**Comment by jeanpham** [comment]
@mbrinton01 your point sounds plausible. I just tried to change the product_type of two virtual products (see CSV image) https://snag.gy/Q0R1rL.jpg
It says 'import successfull'. However, the product_type didn't change. I understand why Magento creates the products as Virtual instead of Simple. 

What I will try is delete all virtual products and re-import them with the product_type = 'simple' column. 

Thanks for now

**Comment by jeanpham** [comment]
@mbrinton01 Hi, I have changed all virtual products to simple products and the issue has been solved. 

Many thanks!!

**Comment by thisfiore** [comment]
@jeanpham how do you change from virtual to simple? manual or with csv? I can't do this.

**Comment by Ctucker9233** [comment]
@jeanpham There should be a "has weight" column. Setting it to "yes" or 1(I think) should switch it. The only difference between a virtual and simple product is that it has weight.

**Comment by amcastror** [comment]
Hi @thisfiore, were you able to do this somehow?

**Comment by hawksakr** [comment]
i face the same problem i can not change the product type from virtual to simple using CSV
