### ISSUE TITLE
Factory does not exist

### ISSUE THREAD

**Issue by thatomadihlaba** [magento/magento2#8229]
Im new to Magento and I got a tutorial online. But when I try to test the tutorial code I get a Factory does not exist error.

### Preconditions
class News extends AbstractModel
{
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Tutorial\SimpleNews\Model\Resource\News');
    }
}

namespace Tutorial\SimpleNews\Controller\Index;

use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;
//use Tutorial\SimpleNews\Model\NewsFactory;

class Index extends Action
{
    /**
     * @var \Tutorial\SimpleNews\Model\NewsFactory
     */
    protected $_modelNewsFactory;

    /**
     * @param Context $context
     * @param NewsFactory $modelNewsFactory
     */
    public function __construct(
        Context $context,
        Magento\Cms\Model\NewsFactory $modelNewsFactory
    ) {
        parent::__construct($context);
        $this->_modelNewsFactory = $modelNewsFactory;
    }

    public function execute()
    {
        /**
         * When Magento get your model, it will generate a Factory class
         * for your model at var/generaton folder and we can get your
         * model by this way
         */
        $newsModel = $this->_modelNewsFactory->create();

        // Load the item with ID is 1
        $item = $newsModel->load(1);
        var_dump($item->getData());

        // Get news collection
        $newsCollection = $newsModel->getCollection();
        // Load all data of collection
        var_dump($newsCollection->getData());}
} 

### Steps to reproduce
When I try to test from http://localhost/WithData/news I get the following error.

1 exception(s):
Exception #0 (RuntimeException): Class Magento\Cms\Model\NewsFactory does not exist

Exception #0 (RuntimeException): Class Magento\Cms\Model\NewsFactory does not exist
#0 C:\xampp\htdocs\WithData\vendor\magento\framework\Code\Generator\Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Tutorial\\Simple...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Tutorial\\Simple...')
#2 [internal function]: spl_autoload_call('Tutorial\\Simple...')
#3 C:\xampp\htdocs\WithData\vendor\magento\framework\Code\Reader\ClassReader.php(19): ReflectionClass->__construct('Tutorial\\Simple...')
#4 C:\xampp\htdocs\WithData\vendor\magento\framework\ObjectManager\Definition\Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Tutorial\\Simple...')
#5 C:\xampp\htdocs\WithData\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Tutorial\\Simple...')
#6 C:\xampp\htdocs\WithData\vendor\magento\framework\ObjectManager\ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Tutorial\\Simple...', Array)
#7 C:\xampp\htdocs\WithData\vendor\magento\framework\App\ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Tutorial\\Simple...')
#8 C:\xampp\htdocs\WithData\vendor\magento\framework\App\Router\Base.php(300): Magento\Framework\App\ActionFactory->create('Tutorial\\Simple...')
#9 C:\xampp\htdocs\WithData\vendor\magento\framework\App\Router\Base.php(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#10 C:\xampp\htdocs\WithData\vendor\magento\framework\App\FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#11 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#12 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#13 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#14 C:\xampp\htdocs\WithData\vendor\magento\module-store\App\FrontController\Plugin\RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#17 C:\xampp\htdocs\WithData\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#20 C:\xampp\htdocs\WithData\vendor\magento\module-page-cache\Model\App\FrontController\BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#23 C:\xampp\htdocs\WithData\vendor\magento\module-page-cache\Model\App\FrontController\VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 C:\xampp\htdocs\WithData\vendor\magento\framework\Interception\Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 C:\xampp\htdocs\WithData\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 C:\xampp\htdocs\WithData\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 C:\xampp\htdocs\WithData\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#28 C:\xampp\htdocs\WithData\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main}

**Comment by koenner01** [comment]
Hi, better place to ask this question would be on http://magento.stackexchange.com/ or the https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2.

Magento\Cms\Model\News is not a valid model, that's why you can't create a factory for it.
You probably want something in the line of My\Module\Model\NewsFactory $newsFactory

**Comment by stamster** [comment]
Windows OS is not supported with Magento2, that's the first thing you should try to fix.

**Comment by veloraven** [comment]
@thatomadihlaba thank you for your feedback.
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html). 
If you are looking for advise or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
