### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by askwhyweb** [magento/magento2#823]
Found Bug during installation (possibly Zend Framework bug). Console log from installation setup is as below.

Starting Magento installation:
File permissions check...
Enabling Maintenance Mode...

Installing deployment configuration...
[ERROR] exception 'InvalidArgumentException' with message 'Invalid backend frontname ' in F:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\DeploymentConfig\BackendConfig.php:32

Stack trace:

#0 F:\xampp\htdocs\magento2\setup\module\Magento\Setup\src\Model\Installer.php(343): Magento\Framework\App\DeploymentConfig\BackendConfig->__construct(Array)

#1 F:\xampp\htdocs\magento2\setup\module\Magento\Setup\src\Model\Installer.php(532): Magento\Setup\Model\Installer->createBackendConfig(Array)

#2 [internal function]: Magento\Setup\Model\Installer->installDeploymentConfig(Array)

#3 F:\xampp\htdocs\magento2\setup\module\Magento\Setup\src\Model\Installer.php(296): call_user_func_array(Array, Array)

#4 F:\xampp\htdocs\magento2\setup\module\Magento\Setup\src\Controller\Install.php(79): Magento\Setup\Model\Installer->install(Array)

#5 F:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()

#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))

#7 F:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))

#8 F:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#9 F:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#10 F:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))

#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))

#12 F:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))

#13 F:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#14 F:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#15 F:\xampp\htdocs\magento2\setup\index.php(24): Zend\Mvc\Application->run()

#16 {main}

Composer log is as below (probably requires for full troubleshoot).

F:\xampp\htdocs\magento2>php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing zendframework/zend-stdlib (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-validator (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-escaper (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-uri (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-eventmanager (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-code (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-server (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-soap (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-console (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-modulemanager (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-servicemanager (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-mvc (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-text (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-loader (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-view (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-config (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-filter (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-inputfilter (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-form (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-di (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-math (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-json (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-serializer (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-log (2.3.1)
    Downloading: 100%

  - Installing zendframework/zend-http (2.3.1)
    Downloading: 100%

  - Installing magento/zendframework1 (1.12.9-patch1)
    Downloading: 100%

  - Installing symfony/process (v2.6.1)
    Downloading: 100%

  - Installing symfony/finder (v2.6.1)
    Downloading: 100%

  - Installing symfony/console (v2.6.1)
    Downloading: 100%

  - Installing seld/jsonlint (1.3.0)
    Downloading: 100%

  - Installing justinrainbow/json-schema (1.1.0)
    Downloading: 100%

  - Installing composer/composer (1.0.0-alpha8)
    Downloading: 100%

  - Installing sebastian/version (1.0.3)
    Downloading: 100%

  - Installing sebastian/exporter (1.0.2)
    Downloading: 100%

  - Installing sebastian/environment (1.2.1)
    Downloading: 100%

  - Installing sebastian/diff (1.2.0)
    Downloading: 100%

  - Installing sebastian/comparator (1.1.0)
    Downloading: 100%

  - Installing doctrine/instantiator (1.0.4)
    Downloading: 100%

  - Installing phpunit/php-text-template (1.2.0)
    Downloading: 100%

  - Installing phpunit/phpunit-mock-objects (2.3.0)
    Downloading: 100%

  - Installing phpunit/php-timer (1.0.5)
    Downloading: 100%

  - Installing phpunit/php-file-iterator (1.3.4)
    Downloading: 100%

  - Installing phpunit/php-token-stream (1.3.0)
    Downloading: 100%

  - Installing phpunit/php-code-coverage (2.0.13)
    Downloading: 100%

  - Installing phpunit/phpunit (4.1.0)
    Downloading: 100%

  - Installing squizlabs/php_codesniffer (1.5.3)
    Downloading: 100%

  - Installing symfony/filesystem (v2.5.8)
    Downloading: 100%

  - Installing symfony/config (v2.5.8)
    Downloading: 100%

  - Installing symfony/dependency-injection (v2.5.8)
    Downloading: 100%

  - Installing pdepend/pdepend (2.0.4)
    Downloading: 100%

  - Installing phpmd/phpmd (2.1.3)
    Downloading: 100%

  - Installing league/climate (2.5.0)
    Downloading: 100%

  - Installing sjparkinson/static-review (4.1.1)
    Downloading: 100%

  - Installing symfony/stopwatch (v2.6.1)
    Downloading: 100%

  - Installing symfony/event-dispatcher (v2.6.1)
    Downloading: 100%

  - Installing fabpot/php-cs-fixer (v1.3)
    Downloading: 100%

zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db
component)
zendframework/zend-validator suggests installing zendframework/zend-i18n (Zend\I
18n component to allow translation of validation error messages as well as to us
e the various Date validators)
zendframework/zend-validator suggests installing zendframework/zend-resources (T
ranslations of validator messages)
zendframework/zend-validator suggests installing zendframework/zend-session (Zen
d\Session component)
zendframework/zend-code suggests installing doctrine/common (Doctrine\Common >=2
.1 for annotation features)
zendframework/zend-mvc suggests installing zendframework/zend-authentication (Ze
nd\Authentication component for Identity plugin)
zendframework/zend-mvc suggests installing zendframework/zend-i18n (Zend\I18n co
mponent for translatable segments)
zendframework/zend-mvc suggests installing zendframework/zend-session (Zend\Sess
ion component for FlashMessenger, PRG, and FPRG plugins)
zendframework/zend-mvc suggests installing zendframework/zend-version (Zend\Vers
ion component)
zendframework/zend-view suggests installing zendframework/zend-authentication (Z
end\Authentication component)
zendframework/zend-view suggests installing zendframework/zend-feed (Zend\Feed c
omponent)
zendframework/zend-view suggests installing zendframework/zend-i18n (Zend\I18n c
omponent)
zendframework/zend-view suggests installing zendframework/zend-navigation (Zend\
Navigation component)
zendframework/zend-view suggests installing zendframework/zend-paginator (Zend\P
aginator component)
zendframework/zend-view suggests installing zendframework/zend-permissions-acl (
Zend\Permissions\Acl component)
zendframework/zend-config suggests installing zendframework/zend-i18n (Zend\I18n
 component)
zendframework/zend-filter suggests installing zendframework/zend-crypt (Zend\Cry
pt component)
zendframework/zend-filter suggests installing zendframework/zend-i18n (Zend\I18n
 component)
zendframework/zend-form suggests installing zendframework/zend-captcha (Zend\Cap
tcha component)
zendframework/zend-form suggests installing zendframework/zend-i18n (Zend\I18n c
omponent)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha
(ZendService\ReCaptcha component)
zendframework/zend-math suggests installing ext-gmp (If using the gmp functional
ity)
zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback rando
m byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable
)
zendframework/zend-log suggests installing ext-mongo (*)
zendframework/zend-log suggests installing zendframework/zend-db (Zend\Db compon
ent)
zendframework/zend-log suggests installing zendframework/zend-mail (Zend\Mail co
mponent)
symfony/console suggests installing psr/log (For using the console logger)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (G
enerate service proxies to lazy load them)
sjparkinson/static-review suggests installing sensiolabs/security-checker (Requi
red for ComposerSecurityReview.)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files

**Comment by snky1987** [comment]
@matrixbegins  I had the same error when I tried to test instalation (after successfull install) because I had an file permission error when installer tried to delete installation.log.

When I moved back to admin I notified that my admin details disappeared (after page refresh). When I typed them in error disappeared so one of possible solutions may be to reset all steps on page refresh and let the users get through each step again to make sure that everything is filled in. Or add additional  validation when someone click Install Now.

**Comment by matrixbegins** [comment]
@snky1987 I agree.

**Comment by easingthemes** [comment]
I also had the same error. But when I checked DB, data was there. 

**127.0.0.1** and **without mod_rewrite** helped up to 95% where existing user error occurred. Changing admin username and email fixed this issue. 

But after that new error occurred, again with user, this time from sample data. Installing without sample data finally was a **success**. Also sample data was installed in first try.

In final try I didn't change **localhost** to **127.0.0.1** and still there was no error, so only **mod_rewrite** was necessary.

**Comment by muasir** [comment]
Closing based on the above comment.

**Comment by rahul-avion** [comment]
i have install magento 2 to find below error ..plz give me solution

zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-resources (Translations of validator messages)
zendframework/zend-validator suggests installing zendframework/zend-session (Zend\Session component)
magento/module-theme suggests installing magento/module-theme-sample-data (Sample Data version:100.1.*)
magento/module-catalog suggests installing magento/module-catalog-sample-data (Sample Data version:100.1.*)
magento/module-cms suggests installing magento/module-cms-sample-data (Sample Data version:100.1.*)
magento/module-customer suggests installing magento/module-customer-sample-data (Sample Data version:100.1.*)
magento/module-widget suggests installing magento/module-widget-sample-data (Sample Data version:100.1.*)
magento/module-tax suggests installing magento/module-tax-sample-data (Sample Data version:100.1.*)
magento/module-sales-rule suggests installing magento/module-sales-rule-sample-data (Sample Data version:100.1.*)
magento/module-catalog-rule suggests installing magento/module-catalog-rule-sample-data (Sample Data version:100.1.*)
magento/module-sales suggests installing magento/module-sales-sample-data (Sample Data version:100.1.*)
magento/module-msrp suggests installing magento/module-msrp-sample-data (Sample Data version:100.1.*)
magento/module-grouped-product suggests installing magento/module-grouped-product-sample-data (Sample Data version:100.1.*)
magento/module-wishlist suggests installing magento/module-wishlist-sample-data (Sample Data version:100.1.*)
magento/module-downloadable suggests installing magento/module-downloadable-sample-data (Sample Data version:100.1.*)
magento/module-review suggests installing magento/module-review-sample-data (Sample Data version:100.1.*)
magento/module-configurable-product suggests installing magento/module-configurable-sample-data (Sample Data version:100.1.*)
magento/module-configurable-product suggests installing magento/module-product-links-sample-data (Sample Data version:100.1.*)
magento/module-swatches suggests installing magento/module-swatches-sample-data (Sample Data version:100.1.*)
magento/module-sample-data suggests installing magento/sample-data-media (Sample Data version:100.1.*)
magento/module-offline-shipping suggests installing magento/module-offline-shipping-sample-data (Sample Data version:100.1.*)
magento/module-bundle suggests installing magento/module-bundle-sample-data (Sample Data version:100.1.*)
sjparkinson/static-review suggests installing sensiolabs/security-checker (Required for ComposerSecurityReview.)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 0.5.* to handle lazy initialization of services)
zendframework/zend-log suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-log suggests installing zendframework/zend-mail (Zend\Mail component)
zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
zendframework/zend-code suggests installing doctrine/common (Doctrine\Common >=2.1 for annotation features)
zendframework/zend-form suggests installing zendframework/zend-captcha (Zend\Captcha component)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
zendframework/zend-view suggests installing zendframework/zend-authentication (Zend\Authentication component)
zendframework/zend-view suggests installing zendframework/zend-feed (Zend\Feed component)
zendframework/zend-view suggests installing zendframework/zend-navigation (Zend\Navigation component)
zendframework/zend-view suggests installing zendframework/zend-paginator (Zend\Paginator component)
zendframework/zend-view suggests installing zendframework/zend-permissions-acl (Zend\Permissions\Acl component)
zendframework/zend-i18n suggests installing zendframework/zend-cache (Zend\Cache component)
zendframework/zend-i18n suggests installing zendframework/zend-resources (Translation resources)
zendframework/zend-mvc suggests installing zendframework/zend-authentication (Zend\Authentication component for Identity plugin)
zendframework/zend-mvc suggests installing zendframework/zend-session (Zend\Session component for FlashMessenger, PRG, and FPRG plugins)
zendframework/zend-mvc suggests installing zendframework/zend-version (Zend\Version component)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files

**Comment by korostii** [comment]
@rahul-avion, I don't see any errors in the trace you've posted, it looks perfectly normal
Please create a new issue following the guide and state explicitly what seems to  e the problem for you

**Comment by magento-engcom-team** [comment]
Hi @askwhyweb. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#1002 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [7dc9e6469c34221aabec3ca9083ed62239e0554b](https://github.com/magento/graphql-ce/commit/7dc9e6469c34221aabec3ca9083ed62239e0554b)
 - [f45a6728e44f0e7b347072d77755f166dc953816](https://github.com/magento/graphql-ce/commit/f45a6728e44f0e7b347072d77755f166dc953816)

The fix will be available with the upcoming 2.3.4 release.
