### ISSUE TITLE
Unable to update EE to 2.1.3/unable to install EE 2.1.3

### ISSUE THREAD

**Issue by detco-monacor** [magento/magento2#8234]
I am unable to upgrade magento EE from 2.1.2 to 2.1.3.

Trying to create a new project with 2.1.3 fails.

### Preconditions

1. Magento EE 2.1.2
2. PHP 7.0 (does probably not matter)

### Steps to reproduce

1. replace fixed version requirement "2.1.2" on magento/product-enterprise-edition in composer.json with "^2.1"
2. composer up --dry-run

alternatively:
1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.1.3 magento-test-ee-2.1.3`

### Expected result

There should be updates listed of magento to version 2.1.3 (among potential other third-party-updated)

With "composer create-project", a new directory with magento EE 2.1.3 should be created.

### Actual result

No updates to magento-packages are found/to be installed.

With "composer create-project", an error is thrown:
```                                                                                 
  [InvalidArgumentException]                                                     
  Could not find package magento/project-enterprise-edition with version 2.1.3.  
```                                                                              

On the other hand
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.1.3 magento-test-ce-2.1.3` works as intended.

**Comment by veloraven** [comment]
@detco-monacor thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
