### ISSUE TITLE
CMS blocks are not validated against having same store and identifier

### ISSUE THREAD

**Issue by magemash** [magento/magento2#8236]
### Preconditions

1. version - 2.12
2. PHP7
3. mysql  Ver 15.1 Distrib 10.0.28-MariaDB

### Steps to reproduce

1. save a cms block with a selected identifier and store view
2. save another block with the same identifier and store view
3. 

### Expected result

1. Validation error should appear

### Actual result

1. Block is saved successfully

**Comment by veloraven** [comment]
Internal ticket was created - MAGETWO-69931

**Comment by magento-engcom-team** [comment]
@magemash, thank you for your report.
We've created internal ticket(s) MAGETWO-69931 to track progress on the issue.

**Comment by nemesis-back** [comment]
I will work on it #SQUASHTOBERFEST 2017

**Comment by thiagolima-bm** [comment]
I am working on it

**Comment by thiagolima-bm** [comment]
@veloraven @okorshenko New PR

**Comment by thiagolima-bm** [comment]
I had to create another PR to fix my forked branches.

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release
