### ISSUE TITLE
Not able to add an image into CMS page when the user has custom ACL role resources.

### ISSUE THREAD

**Issue by joost-florijn-kega** [magento/magento2#8238]
### Preconditions
1. Magento 2.0.10

### Steps to reproduce
1. Create a user with a custom role resources.
2. Login as that user
3. Create a new CMS page and insert and add an image to the CMS page.

### Expected result
1. To see a preview of the added image.

### Actual result
1. I see the icon of an broken image.

The reason for this is that when adding a new image, a call is made to the CMS Wysiwyg Directive controller to retrieve an preview of the image. When creating a user with custom ACL role resources, you can't select the role resource Magento_Backend::admin. This role resource is used by the CMS Wysiwyg Directive controller:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Directive.php

Because of this the user doesn't have the rights and won't see the preview.

**Comment by oleg-onufer** [comment]
Internal ticket was created for this issue -- MAGETWO-69961

**Comment by magento-engcom-team** [comment]
@joost-florijn-kega, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
