### ISSUE TITLE
Configurable deal images problem on LUMA

### ISSUE THREAD

**Issue by patrickdesroches** [magento/magento2#8239]
### Preconditions

1. PHP : 7.0.8
2. Magento Enterprise 2.1.3

### Steps to reproduce

1. Create a configurable product
2. Add image to each SKU

### Expected result

1. Main image change to the SKU specific image

### Actual result

1. The main image is displayed when a option is selected.
2. Cart image show the right image.
3. On a previous test, the option image was a image from another product ( product ID just before the current one )

<img width="1271" alt="capture d ecran 2017-01-23 a 11 26 11" src="https://cloud.githubusercontent.com/assets/3430757/22212649/79de47c8-e15f-11e6-9334-e2151cfe4379.png">

<img width="572" alt="capture d ecran 2017-01-23 a 11 26 49" src="https://cloud.githubusercontent.com/assets/3430757/22212663/8d70926e-e15f-11e6-8165-762e3aa162dc.png">

**Comment by magento-engcom-team** [comment]
@patrickdesroches, thank you for your report.
We've created internal ticket(s) MAGETWO-81373 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@patrickdesroches, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
