### ISSUE TITLE
Check Money Order payment method stuck on

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#8243]
Just more frustration with Magento 2. Since updating to 2.1.3 my Paypal Express checkout method isn't showing up and Check/Money Order is now stuck on as the only available payment, even though it is disabled in admin.

### Preconditions

Magento 2.1.3 PHP 7

### Steps to reproduce

1. Turn Paypal Express method on in admin
2. Turn Money Order off in admin
3. Go to checkout
4. Check Money order is the only option available
### Expected result

1. Should have Paypal Express as the checkout optoin

### Actual result

1. Has Check Money order as the payment option

Magento 2 is garbage

**Comment by dapdx** [comment]
Ok, a bit more on this. Looks like Magento 2.1.3 is pulling payment methods from Default Payment method. So if I turn Check Money Order off from default, even if it's set to disabled in the store view it fixes that option. The issue is I don't want Paypal express to have to be set on the default store, as I'm running a multisite. Why do they keep changing stuff that works with each release?

**Comment by dapdx** [comment]
Forget it, rolled back to 2.1.2 to fix it. Moving the site to Magento 1.9

**Comment by xmav** [comment]
@dapdx Is this your case?
https://github.com/magento/magento2/issues/7943

**Comment by veloraven** [comment]
I'm closing this issue.
If you can still reproduce this issue, please create a new GitHub issue report.
