### ISSUE TITLE
Json Factory number conversion

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8244]
In the json result factory 
```
namespace Magento\Framework\Controller\Result;
Json
```
Its not converting numbers to numbers so client side models fail. 

Its converting everything to a string 
```
$this->json = (string)$jsonData;
```

And in the zend framework json encode you need to add option JSON_NUMERIC_CHECK

reference http://php.net/manual/en/json.constants.php

### Preconditions

1. LEMP Stack
2. PHP 7.1w
3. Percona 5.6
4. Mage 2.1.3

### Steps to reproduce

1. Make a result using the json factory with number types and you will see quotes around the data

### Expected result

1. Make a result using the json factory with number types and you should not see quotes around the data.

### Actual result

1. [Screenshot, logs]
<img width="682" alt="screen shot 2017-01-23 at 10 20 21 am" src="https://cloud.githubusercontent.com/assets/2015173/22216902/c2443464-e155-11e6-8c6a-b31ef903d290.png">

**Comment by ghost** [comment]
Until this is fixed I wouldn't use 
```
return  $this->resultJsonFactory->create()->setData($this->getOrders());
```
I would use this instead
```
header('Content-Type: application/json');
echo json_encode($this->getOrders(),  JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_NUMERIC_CHECK);
```
<img width="668" alt="screen shot 2017-01-23 at 10 31 37 am" src="https://cloud.githubusercontent.com/assets/2015173/22217274/29fa020e-e157-11e6-9530-75322f2bcf2f.png">

**Comment by veloraven** [comment]
@joshspivey thank you for your report.
Please, identify which version of Magento you are running.

**Comment by ghost** [comment]
@veloraven  I did its 2.1.3 its listed as number 4 on my list.

**Comment by denisristic** [comment]
I'm working on it

**Comment by magento-engcom-team** [comment]
@joshspivey, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
