### ISSUE TITLE
Magento Role Scopes not visible

### ISSUE THREAD

**Issue by vssenthil11** [magento/magento2#8247]
I am using Magento CE 2.1.3
I tried with latest edition of chrome.
Can find the "Role Scope" section under "Role Resources"

### Preconditions
Magento CE 2.1.3
### Steps to Reproduce
1. Log into the Magento admin portal
2. Navigate to System -> User Role -> Create New Role
3. Then select Role Resources.
### Expected Result
There should be a section called Role Scope, visible on the right side of the page.
### Actual Result
Section  Role Scope is not visible, but only "Resource Access" and "Resources" are visible

![image](https://user-images.githubusercontent.com/31669971/30641851-33704d58-9e11-11e7-8aa2-c2cd0ffeb080.png)

**Comment by veloraven** [comment]
@vssenthil11 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by vssenthil11** [comment]
Steps to reproduce
1. Log into the Magento admin portal
2. Navigate to System -> User Role -> Create New Role
3. Then select Role Resources.
4. There should be a section called **Role Scope**, visible on the right side of the page. But only "Resource Access" and "Resources" are visible

Expected Page( as available in the user guide):
![screen shot 2016-05-29 at 11 31 40 p m](https://cloud.githubusercontent.com/assets/2044865/22279034/ef42de28-e2bf-11e6-85ae-ba1321e070ea.png)

Actual Page:
![rolescopemissing](https://cloud.githubusercontent.com/assets/2044865/22280131/cc3d2f80-e2c6-11e6-9769-98f59cbba604.PNG)

**Comment by oleg-onufer** [comment]
Hi @vssenthil11.
Role scope is only available in EE

**Comment by magento-engcom-team** [comment]
@vssenthil11, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
