### ISSUE TITLE
Configurable product multi base currency setting is not taken over when creating simple/virtual products

### ISSUE THREAD

**Issue by rtk0407** [magento/magento2#8253]
### Preconditions

1. Magento 2.1.3
2. I have three websites and Store A (base currency Japanese YEN) and B and C (base currencies are EURO).

### Steps to reproduce

1. Create a configurable product.  Imput price in Yen (e.g. 30000yen), save, then switch to store B and C and input each prices in EURO (e.g. 250eur).

2. Create associated products (in this case virtual products as I do not use weight) related to it (= size variations) and save them.

3. Simple products are having only 30000yen as value and when I switch stores, store B and C are having 30000eur instead of 250eur. So I manually need to change them.

### Expected result

1. The configurable product on the frontend shows 30000yen in Store A and 250eur in Store B and C.

### Actual result

1. The prices in Store B and C are 30000eur instead of 250eur. So I manually need to change every virtual product.

**Comment by magento-engcom-team** [comment]
@rtk0407, thank you for your report.
We've created internal ticket(s) MAGETWO-81284 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@rtk0407, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
