### ISSUE TITLE
Place Order leads to 'Unable to place Order, Please Try Again' with Paypal Payflow Payment Method in magento 2

### ISSUE THREAD

**Issue by dennisage** [magento/magento2#8254]
### Preconditions

1) Magento 2.1.1

2) Set Payment Method in Stores->Configuration->Sales->Payment Methods->**Paypal** Payflow Pro (Includes Express Checkout)

Give all required configuration information like Email, Partner etc.

### Steps to reproduce

1) Add Configurable product in cart

2) Go to Checkout page

3) Login with email and password

4) Provide Shipping information and choose free shipping method

5) Choose credit card payment method

6) Then click place order

### Expected result

Need to go order success page

### Actual result

I got this error above Payment Method step 

 'Unable to place Order, Please Try Again' 

Page loads for few secs and stops.When I debug error in the console I got these responses.

1) http://mysite.com/rest/default_migrated/V1/carts/mine/set-payment-information

Response : True

2) http://mysite.com/paypal/transparent/requestSecureToken/

{"payflowpro":{"fields":{"result":"0","securetoken":"XXXXXXX","securetokenid":"YYYYYYYY"
,"respmsg":"Approved","result_code":"0"}},"success":true,"error":false}

3) https://payflowlink.paypal.com/

**Reload the page to get source for: https://payflowlink.paypal.com/**

Please check this error and help me how to resolve this paypal error.

**Comment by endergreen** [comment]
@dennisage I am seeing a similar issue and traced it back to this fails when it goes to save the customer to the customerRepository from populateCustomerInfo in Quote\Model\CustomerManagement.php.  Are you able to make a change to the customer and save it?

**Comment by dennisage** [comment]
Yes i can save customer information.

**Comment by YevSent** [comment]
Hi, @dennisage, I've test described issue on Magento 2.1.5 version and all works as expected. Could you enable debug mode for PayPal PayflowPro and post transaction details from debug log?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by mariamghalleb** [comment]
any solution please?
