### ISSUE TITLE
V2 SOAP Web API salesOrderManagementV1AddComment does nothing

### ISSUE THREAD

**Issue by maultby** [magento/magento2#8257]
### Preconditions
1. Mag CE 2.1.3
2. MySQL 5.7.11
3. PHP 5.6.19

### Steps to reproduce
1. VS2015 C#. 
2. Use WSDL to add service reference for salesOrderManagementV1.
3. Use WSDL to add service reference for salesOrderRepositoryV1.
4. Get sales order for an incrementid with salesOrderRepositoryV1GetList() into SalesOrderRepositoryV1GetListResponse.
5. Get sales order comments for an order using salesOrderManagementV1GetCommentsList.items[0].entityId passed to salesOrderManagementV1GetCommentsList() into SalesOrderManagementV1GetCommentsListResponse.
6. Create new SalesOrderManagementV1AddCommentRequest.
7. Create new SalesOrderManagementV1AddCommentRequest.SalesDataOrderStatusHistoryInterface.
8. set statusHistory.comment = "new comment from api".
9. set statusHistory.parentId = SalesOrderRepositoryV1GetListResponse.result.items[0].incremented.
10. set statusHistory.isVisibleOnFront = 1.
11. statusHistory.status = SalesOrderRepositoryV1GetListResponse.result.items[0].status.
12. set SalesOrderManagementV1AddCommentRequest.id=0 or SalesOrderManagementV1AddCommentRequest.id=-1.
13. call salesOrderManagementV1AddComment(SalesOrderManagementV1AddCommentRequest).
Get error id required. Should get new comment added to sales order.
14. set SalesOrderManagementV1AddCommentRequest.id=SalesOrderManagementV1GetCommentsListResponse.result.items[0].entityID.
15) call salesOrderManagementV1AddComment(SalesOrderManagementV1AddCommentRequest).
Get SalesOrderManagementV1AddCommentResponse.result true. But existing comment has not been set to "new comment from api".
### Expected result
1. When passing an existing SalesDataOrderStatusHistoryInterface.entityId to SalesOrderManagementV1AddCommentRequest.id we should see that order comment changed to SalesDataOrderStatusHistoryInterface.comment value.
2. When passing zero or -1 to SalesDataOrderStatusHistoryInterface.entityId we should see a new comment added to the order.

### Actual result
1. Nothing happens, order comments remain unaltered.

### C# code:
        private void SaveV2SoapOrderComment()
        {
            MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1AddCommentResponse Res = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1AddCommentResponse();
            try
            {
                System.Diagnostics.Stopwatch sw1 = new System.Diagnostics.Stopwatch();
                sw1.Start();
                MagV2SoapService.MagV2SoapsalesOrderRepositoryV1.SalesOrderRepositoryV1GetListResponse orderRes=GetV2SoapOrders("000000019");   //("000000020")
                MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1GetCommentsListRequest ReqList = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1GetCommentsListRequest();
                MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1GetCommentsListResponse ResList = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1GetCommentsListResponse();
                ReqList.id = orderRes.result.items[0].entityId;    
                ResList = MagV2SoapService.MagentoSOAP.OrderManagement.salesOrderManagementV1GetCommentsList(ReqList);

                MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1AddCommentRequest Req = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesOrderManagementV1AddCommentRequest();
                Req.statusHistory = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesDataOrderStatusHistoryInterface();
                Req.statusHistory.comment = "new comment from magtest";
                Req.statusHistory.parentId = Convert.ToInt32(orderRes.result.items[0].incrementId);
                //Req.statusHistory.entityId = Convert.ToInt32(orderRes.result.items[0].entityId);
                //Req.statusHistory.entityIdSpecified = true;
                Req.statusHistory.isVisibleOnFront = 1;
                Req.statusHistory.status = orderRes.result.items[0].status;
                //Req.id = 0;  
                Req.id = ResList.result.items[ResList.result.items.Length-1].entityId;
                Res = MagV2SoapService.MagentoSOAP.OrderManagement.salesOrderManagementV1AddComment(Req);
                
                sw1.Stop();
                
                lblResult.Text += String.Format("V2 Soap saved order comment result {0} in {1} hours {2} minutes {3} seconds\r\n", Res.result, sw1.Elapsed.Hours, sw1.Elapsed.Minutes, sw1.Elapsed.Seconds);
            }
            catch (Exception ex)
            {
                ShowError("V2 Soap save saved order comment", ex);
            }
        }

**Comment by maultby** [comment]
I've resolved this:
Problem was due to not providing statusHistory.entityName = "order". Record was written to database but with null in the entityname field and this prevented that record showing in Web UI. 
And SalesOrderManagementV1AddCommentRequest.id needs to be order.entityId, not comment entityid.
With these values it always ADDs an order comment, which is good.
Trying to edit an existing order comment by using:
      statusHistory.entityId=ResList.result.items[ResList.result.items.Length-1].entityId
      statusHistory.entityIdSpecified = true
does nothing. Which I guess is good as the method is named salesOrderManagementV1AddComment not salesOrderManagementV1EditComment.

Revised C# code fragment:
                Req.statusHistory = new MagV2SoapService.MagV2SoapsalesOrderManagementV1.SalesDataOrderStatusHistoryInterface();
                Req.statusHistory.comment = "new comment from magtest";
                Req.statusHistory.parentId = Convert.ToInt32(orderRes.result.items[0].incrementId);
                //jrm - do NOT set these: we cannot edit an existing comment which is fine and consistent with V1.
                //Req.statusHistory.entityId = Convert.ToInt32(ResList.result.items[ResList.result.items.Length-1].entityId);
                //Req.statusHistory.entityIdSpecified = true;
                Req.statusHistory.entityName = "order";
                Req.statusHistory.isVisibleOnFront = 1;
                Req.statusHistory.status = orderRes.result.items[0].status;
                Req.id = Convert.ToInt32(orderRes.result.items[0].entityId);    
                Res = MagV2SoapService.MagentoSOAP.OrderManagement.salesOrderManagementV1AddComment(Req);

**Comment by mbrinton01** [comment]
@maultby if you consider this issue to be resolved, please go ahead and close it.

**Comment by maultby** [comment]
would suggest there is a bug that needs correcting which  is the visibility and requirement of entityName property. it ought to be a hidden property and forced to "order" within the service

**Comment by magento-engcom-team** [comment]
@maultby, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
