### ISSUE TITLE
SID Making Page Load Speed Slow

### ISSUE THREAD

**Issue by atrane21** [magento/magento2#8259]
Working on a new Magento 2.1.3 store and we're having issues with it being extremely slow. We do have some problems with image sizing, etc that we're working out but the biggest lag in the page loading time is the SID. When running the site test from GTmetrix and looking at the waterfall "domain.com/?SID=large number" takes 10 to 20 seconds to load. I have "Session Validation Settings" turned off and it still seems to be trying load the SID.
### Preconditions

1. Magento Version 2.1.3

### Steps to reproduce

1. Turned off "Session Validation Settings"
2. Test page with GTmetrix

### Expected result

1. No SID loaded

### Actual result

1. SID loaded and it takes 10-20 seconds for it to process

**Comment by naydav** [comment]
Created internal issue MAGETWO-64141 to investigate and track this issue.
Thanks

**Comment by magento-engcom-team** [comment]
@atrane21, thank you for your report.
We've created internal ticket(s) MAGETWO-64141 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@atrane21, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
