### ISSUE TITLE
addWebsiteFilter doesn't support an array of website ids

### ISSUE THREAD

**Issue by olgaimproove** [magento/magento2#8260]
\Magento\Rule\Model\ResourceModel\Rule\Collection\AbstractCollection::addWebsiteFilter has an attribute $websiteId, which is described as 
`@param int|int[]|\Magento\Store\Model\Website $websiteId`
But it doesn't support an array of website ids

### Preconditions

1. Magento version: 2.1.2

### Steps to reproduce
1. Give an array to the method \Magento\Rule\Model\ResourceModel\Rule\Collection\AbstractCollection::addWebsiteFilter
Example: `$websiteIds = [2, 0]`

### Expected result
```
SELECT `main_table`.`rule_id` FROM `catalogrule` AS `main_table`
 INNER JOIN `catalogrule_website` AS `website` ON website.website_id = (2, 0) AND main_table.rule_id = website.rule_id WHERE (`name` = 'some-rule');
```

### Actual result

```
SELECT `main_table`.`rule_id` FROM `catalogrule` AS `main_table`
 INNER JOIN `catalogrule_website` AS `website` ON website.website_id = 2, 0 AND main_table.rule_id = website.rule_id WHERE (`name` = 'some-rule');
```

**Comment by magento-engcom-team** [comment]
@olgaimproove, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
