### ISSUE TITLE
Import product csv, how to import categories with slash in name?

### ISSUE THREAD

**Issue by Henrique-Oliveira** [magento/magento2#8261]
### Preconditions

1. Version: Magento CE 2.0.8
2. 

### Steps to reproduce

1. Create a csv file with native import, and in the name of the category use the slash (/). Example: "Movies/Series"

### Expected result

1. Create a category with a name "Movies/Series"

### Actual result

1. Creates a category "Movies" and another category "Series"

### Comments
It is possible to use the slash in the category name when importing by csv?

**Comment by hostep** [comment]
Have you tried `Movies\/Series` ?
I can't say for sure if this will work in Magento 2, but I know this used to work in Magento 1.

**Comment by Henrique-Oliveira** [comment]
Yes, already tested that but didn't work. Create a "Movies\\" and "Series" category

**Comment by koenner01** [comment]
seems to be duplicate of https://github.com/magento/magento2/issues/6948

**Comment by Henrique-Oliveira** [comment]
You right, i didn't find that issue when searching for this problem. Thanks
