### ISSUE TITLE
Error after Install Magento 2

### ISSUE THREAD

**Issue by marti1125** [magento/magento2#8262]
### Preconditions

1. Magengo ver 2.1.3
2. PHP 5.6.29-1+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
3. MySQL v5.7.16

### Steps to reproduce

1. install process 
2. Peru config
3. I can not acces to admin 
http://localhost/magento/admin_615dq6/ not found 

### Expected result

1. show admin panel
2. show index

### Actual result

1. http://localhost/magento/
![selection_016](https://cloud.githubusercontent.com/assets/223240/22256399/93587bc8-e228-11e6-964d-d426fb8a8cc0.png)

**Comment by marti1125** [comment]
I am trying to run: ./bin/magento setup:static-content:deploy

Requested languages: en_US
Requested areas: frontend, adminhtml
Requested themes: Magento/blank, Magento/luma, Magento/backend
PHP Fatal error:  Call to undefined function Magento\Framework\Event\mb_strtolower() in /var/www/html/magento/vendor/magento/framework/Event/Manager.php on line 56

**Comment by veloraven** [comment]
@marti1125 thank you for your report.
Could you please provide more detailed steps for the step "Peru Config"? Please write down exact actions you do. Additionally please let us know if you use any external localization for it.

**Comment by colinspace48** [comment]
Hi @marti1125 is it possible that you're using Nginx and encountering the bug mentioned in this pull request: https://github.com/magento/devdocs/pull/985

**Comment by marti1125** [comment]
I am using Apache Server a LAMP in Elementary OS
SELECT * FROM `core_config_data`
![selection_017](https://cloud.githubusercontent.com/assets/223240/22296266/9a23b106-e2e7-11e6-937e-1eba14746a06.png)

**Comment by veloraven** [comment]
@marti1125  please provide more detailed steps for the step "Peru Config". Please write down exact actions you do. Additionally please let us know if you use any external localization for it.

**Comment by idziakjakub** [comment]
Hi @marti1125, I had the same problem on blank Magento 2.1.3 installation.

On my first installation (local Vagrant machine) with sample nginx configuration (from repository) static URLs path is http://domain.com/static/(...) and there is no problems with static files.

On second installation (on lastest server) with the same sample nginx configuration, files and database path is http://domain.com/pub/static/(...).

Fast fix for this problem is to change location in nginx configuraton for static files from /static/ to /pub/static/:

```

location /pub/static/ {
    # Uncomment the following line in production mode
    # expires max;

    # Remove signature of the static files that is used to overcome the browser cache
    location ~ ^/pub/static/version {
        rewrite ^/pub/static/(version\d*/)?(.*)$ /static/$2 last;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
        expires +1y;

        if (!-f $request_filename) {
            rewrite ^/pub/static/(version\d*/)?(.*)$ /pub/static.php?resource=$2 last;
        }
    }
    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";
        expires    off;

        if (!-f $request_filename) {
           rewrite ^/pub/static/(version\d*/)?(.*)$ /pub/static.php?resource=$2 last;
        }
    }
    if (!-f $request_filename) {
        rewrite ^/pub/static/(version\d*/)?(.*)$ /pub/static.php?resource=$2 last;
    }
    add_header X-Frame-Options "SAMEORIGIN";
}

```

But this is fix but not solution. 
My question is: why Magento sets other paths to static directory on different servers with the same configuration and files?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
