### ISSUE TITLE
Custom URL Rewrite where the request path ends with a forward slash is not matched

### ISSUE THREAD

**Issue by hostep** [magento/magento2#8264]
### Preconditions
1. Magento CE 2.1.3
2. PHP 7.0.15

### Steps to reproduce
1. Set up a clean Magento CE 2.1.3 store
2. In the admin, go to Marketing => URL Rewrites
3. Add a new Custom URL Rewrite like this:
![screen shot 2017-01-24 at 20 10 57](https://cloud.githubusercontent.com/assets/85479/22262630/fa336148-e271-11e6-8c53-db04011da6d6.png)

### Expected result
In the frontend, going to `http://mydomain/test/` redirects you to `http://mydomain/contact/`

### Actual result
In the frontend, going to `http://mydomain/test/` gives you a `404 Not Found`

### Solution
Change the `trim` to `ltrim` in [Magento\UrlRewrite\Controller\Router::getRewrite](https://github.com/magento/magento2/blob/2.1.3/app/code/Magento/UrlRewrite/Controller/Router.php#L130), otherwise the trailing slash will be removed and the url will never match.
(You need to flush your cache after changing this for some reason.)

### Discussion
We want to import a bunch of custom redirects since we want to migrate an old custom build shop to magento 2 and we want to redirect using 301 headers from their old url structure to the new structure. The old structure uses a lot of url's with trailing slashes and this bug prevents it from redirecting properly to the new url structure. If we don't fix it, we would lose a bunch of Link Juice (SEO term) from the old url structure and that would very be bad.

### Credits
Thanks to @LoganGS who discovered this bug and the solution over here: https://github.com/magento/magento2/issues/6700

**Comment by miakusha** [comment]
Hi @hostep , thanks for report.
We've created internal ticket MAGETWO-64348 to address this issue.

**Comment by hostep** [comment]
@miakusha: ok if I close this issue, since it looks like this is a duplicate of https://github.com/magento/magento2/issues/4876 and https://github.com/magento/magento2/issues/7040, correct?

**Comment by vrann** [comment]
In order to make the complete fix next cases should be supported:

|#|redirect|behaviour|
|---|---|---|
|1|"test" => "contact"|http://magento.loc/test/ => http://magento.loc/contact|
|2|"test" => "contact"|http://magento.loc/test => http://magento.loc/contact|
|3|"test/" => "contact/"|http://magento.loc/test/ => http://magento.loc/contact/|
|4|"test/" => "contact/"|http://magento.loc/test => http://magento.loc/contact/|

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70255

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70505

**Comment by magento-engcom-team** [comment]
Fixed in 2.2.0 and 2.1 releases. @hostep thank you for report
