### ISSUE TITLE
Help me understand the problem. Checkout page and false "no items in cart" message

### ISSUE THREAD

**Issue by flnative** [magento/magento2#8266]
### Preconditions

1. Magento 2.1.3
2. opcache turned off on server
3. PHP 5.6.25
4. Multi store

### Steps to reproduce

1. Add 2 items to cart; same product (only product in my case)
2. click small purse/cart icon and select review cart and checkout or just the checkout button
3. Note: If Opcache is turned on then the entire checkout page is blank except headers (non function links)
3. Login
4. Click checkout

### Expected result

1. buy product.

### Actual result

1. Cart has 5 more items automatically add to cart after logging in. For total of 7
2. Click view and edit cart you get the message you have no items in cart on the main page even though 7 are showing in the small icon and also in the subsequent hover dropdown of the icon where you edit or checkout.
3. Impossible to checkout.
4. I curse a thousand times.

**Comment by earlelnar** [comment]
Hi @flnative 

Did you try to enable your cache in the backend?

Thanks,
MazeStricks

**Comment by flnative** [comment]
Mazestricks, I have all items under "cache management" enabled. Is there another cache setting that you are referring to?

**Comment by earlelnar** [comment]
Hi @flnative 

That's what I am referring to the cache management. What theme are you using in your store?

Thanks,
MazeStricks

**Comment by flnative** [comment]
Porto theme.

**Comment by miakusha** [comment]
Hi @flnative, I cannot reproduce issue
Can you reproduce it on fresh magento without any custom theme  or modules?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
