### ISSUE TITLE
Error on API data definition catalogProductRepositoryV1::GET

### ISSUE THREAD

**Issue by albertixcom** [magento/magento2#8270]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

Swagger declare:

catalog-data-product-interface {
id (integer, optional): Id ,
sku (string): Sku ,
name (string, optional): Name ,
attribute_set_id (integer, optional): Attribute set id ,
price (number, optional): Price ,
status (integer, optional): Status ,
visibility (integer, optional): Visibility ,
type_id (string, optional): Type id ,
created_at (string, optional): Created date ,
updated_at (string, optional): Updated date ,
weight (number, optional): Weight ,
extension_attributes (catalog-data-product-extension-interface, optional), <----------- ERROR: shoud be Array[catalog-data-product-extension-interface]
product_links (Array[catalog-data-product-link-interface], optional): Product links info ,
options (Array[catalog-data-product-custom-option-interface], optional): List of product options ,
media_gallery_entries (Array[catalog-data-product-attribute-media-gallery-entry-interface], optional): Media gallery entries ,
tier_prices (Array[catalog-data-product-tier-price-interface], optional): List of product tier prices ,
custom_attributes (Array[framework-attribute-interface], optional): Custom attributes values.
}

framework-attribute-interface {
attribute_code (string): Attribute code ,
value (string): Attribute value <----------- ERROR: shoud be MIXED (not always is string, sometimes is Array)
}

**Comment by NotAndD** [comment]
You are right on value, sometimes is an array of strings instead of a string. It's an error of attribute category_ids. Instead of being formatted like all other attributes with more then one value:
`"value1,value2,value3"` it's in an array of string format. So that's an incongruence with other attributes..

As for extension_attributes. It's not an array but when it's empty, for example when you ask more then one product using a filter to Magento, I noticed it has a default value of an empty array `[ ]`. I think that's the default value for an empty object choosen by magento (Why not an empty object instead of an empty array?)

**Comment by albertixcom** [comment]
ziliquas thx for your comment
Ive resolved using generic "Object" type, after inside on my workflow i testing real type using "instanceof".

**Comment by veloraven** [comment]
@albertixcom thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Or close the issue if it is not actual any more.

**Comment by IgorSteinmetzSige** [comment]
Same problem here...
Magento 2.1.3 im using.
Try to get a product by V1/products/:sku, it brigs the custom_attributes and in the category _ids the type is an array of string and not a string.

**Comment by nepda** [comment]
@veloraven I've created a new issue with hopefully better formatted description: [9366](https://github.com/magento/magento2/issues/9366).

**Comment by veloraven** [comment]
@nepda thank you.
I'm closing this issue as according to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
