### ISSUE TITLE
Visibility save attribute error

### ISSUE THREAD

**Issue by piuga** [magento/magento2#8271]
### Preconditions

1. Magento 2.1.3 

### Steps to reproduce

1. Open 'visibility' attribute and save it will show the load icon because of error: "Notice: Undefined index: value in ...\vendor\magento\module-catalog\Controller\Adminhtml\Product\Attribute\Validate.php on line 155";i:1;s:5369:"#0 ...\vendor\magento\module-catalog\Controller\Adminhtml\Product\Attribute\Validate.php(155): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...'"

### Expected result

1. Attribute should save with success message

### Actual result

1. [Screenshot, logs] https://cl.ly/1L3j350V1M3N

The issue is inside Magento\Catalog\Controller\Adminhtml\Product\Attribute\Validate class, checkUniqueOption() function. Because 'visibility' is a dropdown attribute, the unique values validation is run, but this doesn't have any 'value' inside $options array.

**Comment by bassplayer7** [comment]
This also occurs on `multiselect` attribute types.

**Comment by miakusha** [comment]
hi @piuga, thanks for report
I've linked this GitHub issue to internal ticket MAGETWO-63655

**Comment by pooshok** [comment]
A similar problem here https://github.com/magento/magento2/issues/8202. @cih997 posted temporary workaround

**Comment by magento-engcom-team** [comment]
@piuga, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
