### ISSUE TITLE
Custom Option Price Reset Issue

### ISSUE THREAD

**Issue by priyankbro** [magento/magento2#8272]
I added two custom options in in my product. When ever I change any details in product the custom option price with 4 Digits is reset to 1 Digit. In my example the option 1 value 2 is converted from $1,000 to $1.

```
Option 1 (Radio)
Value 1 ($0) (Fixed)
Value 2 ($1,000) (Fixed)

Option 2 (Checkbox)
Value 1($0) (Fixed)
Value 2($0) (Fixed)
```

### Preconditions
1. Magento v2.1.3

### Steps to reproduce
1. Add Product with at least two custom options and set price to 1000
2. save and continue the product
3. now change some details in product in my case I change 2nd custom option title and save the product

### Expected result
1. The Price should remain same for all custom options as they were unchanged.

### Actual result
1. Price is changed from $1000 to $1

**Comment by miakusha** [comment]
Hi @priyankbro thanks for report
The same issues already exist #6342 #6116 
Closed as duplicate
