### ISSUE TITLE
Usage of configurations in place of hard coded data

### ISSUE THREAD

**Issue by syno-dlr** [magento/magento2#8275]
Hey everybody !

In class Magento\Wishlist\Model\ResourceModel\Item\Collection, at line 287, you are using this code: 

`
        $attributesToSelect = [
            'name',
            'visibility',
            'small_image',
            'thumbnail',
            'links_purchased_separately',
            'links_title',
            'price_type'
        ];
`

It could be better to use the configurations located in <path to wishlist module>/etc/catalog_attributes.xml, isn't it ?

Damien.

**Comment by veloraven** [comment]
@damien-synolia thank you for your feedback.
However it is rather improvement than an issue and GitHub issue tracker is intended for technical issues only. 
 Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by benjamin-volle** [comment]
Hello,

Correction has been made in a new merged Pull Request and will be released in new version (https://github.com/magento/magento2/pull/6723)

You can close this issue, thank you
