### ISSUE TITLE
CatalogImportExport uploader can't handle HTTPS images

### ISSUE THREAD

**Issue by clementbeudot** [magento/magento2#8277]
CatalogImportExport uploader can't handle HTTPS images 

In the case we create a product programmatically and want to use the  Magento\CatalogImportExport\Model\Uploader class, if the URL of the file contained https, it will still use the HTTP Provider to retrieve the image leading to an error.

### Preconditions
Using PHP 5.6, and Magento 2.1.2

### Steps to reproduce
Instanciate class Magento\CatalogImportExport\Model\Uploader and try to move an URL with https

### Expected result
1. File should be downloaded with appropriate driver instead of the default HTTP 

### Actual result
We have an exception  

```
 exception 'Magento\Framework\Exception\FileSystemException' with message 'Fichier "myhttpsfile/6bdc0aa637275ff47b16e87e7535b336.jpg" inexistant' in /var/www/marketplace/vendor/magento/framework/Filesystem/File/Read.php:75
Stack trace:
#0 /var/www/marketplace/vendor/magento/framework/Filesystem/File/Read.php(61): Magento\Framework\Filesystem\File\Read->assertValid()
#1 /var/www/marketplace/vendor/magento/framework/Filesystem/File/Read.php(51): Magento\Framework\Filesystem\File\Read->open()
#2 /var/www/marketplace/vendor/magento/framework/Filesystem/File/ReadFactory.php(40): Magento\Framework\Filesystem\File\Read->__construct('****....', Object(Magento\Framework\Filesystem\Driver\Http))
```

**Comment by clementbeudot** [comment]
![image](https://cloud.githubusercontent.com/assets/7023424/22289995/c72c85da-e2fe-11e6-8121-5e0d3f1172cf.png)

![image](https://cloud.githubusercontent.com/assets/7023424/22290009/d4c6a2e8-e2fe-11e6-8c72-57ca033b3c49.png)

**Comment by clementbeudot** [comment]
I have made a pull request to fix it.

**Comment by wert2all** [comment]
Thanks for the feedback. Created internal issue MAGETWO-63835 to investigate and track this issue.

**Comment by clementbeudot** [comment]
Thank you!!!

**Comment by okorshenko** [comment]
@clementbeudot thank for reporting and fixing the issue! Closing this issue. Pull request has been delivered to develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64902

**Comment by clementbeudot** [comment]
Hey @magento-team, I do not understand how it works for bugfix to go in the release. It is written that it has been merged on March 5th. What is the status on this ?
