### ISSUE TITLE
Menu Management system like Menu Creator Pro or Menu Builder for Magento 2.0?

### ISSUE THREAD

**Issue by vigentocommerce** [magento/magento2#828]
I'm sure other developers will agree with me, we expect a menu management system in magento, such as Menu Creator Pro do it.
Because lot of magento site now need a mega menu or can manage menu easy from backend.
Really expect this feature for magento 2.0

**Comment by verklov** [comment]
Hi all! We are having improvements to the entire CMS system in our backlog including the menu management utility. However, cannot promise you the exact dates it will be released. So please be patient, we are working on it.
