### ISSUE TITLE
Gift card products fail to generate gift card accounts

### ISSUE THREAD

**Issue by Luwdo** [magento/magento2#8281]
When a payment gateway is configured gift card accounts are not being created created. 

In vendor/magento/module-gift-card/Observer/GenerateGiftCardAccounts.php
on line 150 

### Preconditions
1. Centos 6.2
2. Mysql Ver 14.14 Distrib 5.6.29-76.2
3. PHP 7.0.6
4. Apache 2.4.6
5. Magento 2.1.3 EE, no sample data installed.
6. Single category and gift card product created.
7. Authorize.net sandbox configured with direct post.
8. Stores->Configuration->Sales->Gift Cards->Gift Card General Settings->Generate Gift Card Account when Order Item is : set to Invoiced

### Steps to reproduce
1. Logged in Customer or Guest
2. Gift card product added to to cart (gift card product is only in card)
3. Proceed to checkout
4. Fill out shipping information
5. Select Credit Card Direct Post (Authorize.net) Payment Method
6. Fill out Authorize.net test card
7. Place Order

### Expected result
1. If the payment was successful then a gift card account is created and the recipient is emailed with the gift card codes.

### Actual result
1. Checkout is successful, order is invoiced and marked as complete, no gift card account is created, no gift card code email is sent.

I investigated this issue and this is what I have found.

In the gift card module there is an observer for sales_order_save_after

```
<event name="sales_order_save_after">
    <observer name="magento_giftcard_generate_giftcardaccounts" instance="Magento\GiftCard\Observer\GenerateGiftCardAccounts" />
</event>
```

In vendor/magento/module-gift-card/Observer/GenerateGiftCardAccounts.php 

this is the sudo code for the gift card account creation:

```
order items are looped over {
    order items are checked if the the product type is a gift card
        if the required status is set to invoiced {
        invoice items for the order item are fetched
        invoice items are looped over and the parent invoice is checked to be paid
        if the parent invoice has been paid then the invoice item quantity is added to a running total
    } else if the require status is ordered {
        the order item quantity is added to a running total
    }
}
```

The issue is that at this point there is no invoice for the order and when the invoice is created and paid this code is not revisited.

What can I do about this?

A good option is to split this observer into two, one for if you have the setting "Account when Order Item is" set to invoice and one for if you have it set to order.

The sales_order_save_after observer would create accounts for the order items with products that are gift cards if the setting "Account when Order Item is" is set to order

(new observer) The new observer sales_order_invoice_pay would loop over the invoice items get the order items, check if order items product is gift card, then create the gift card account and send out emails.

**Comment by veloraven** [comment]
@Luwdo thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
And Gift cart functionality is present in EE only so we can not treat it as CE issue and can not process it via GitHub.
