### ISSUE TITLE
Import Product by csv: Integrity constraint violation: 1048 Column 'min_qty' cannot be null

### ISSUE THREAD

**Issue by Henrique-Oliveira** [magento/magento2#8282]
### Preconditions

Using Magento 2.0.9 and PHP 7

### Steps to reproduce

Using Import from backoffice, try to import a product using the csv original file.

### Expected result

Create the products and relative categories, or give me some kind of error.

### Actual result

1. Give me the error "Maximum error count has been reached or system error is occurred!", but the product and the categories are created. Checking the detail of the error have something like: 
"Integrity constraint violation: 1048 Column 'min_qty' cannot be null, query was: INSERT INTO `cataloginventory_stock_item` (`manage_stock`,`use_config_manage_stock`,`qty`,`min_qty`,`use_config_min_qty`,`min_sale_qty`,`use_config_min_sale_qty`,`max_sale_qty`,`use_config_max_sale_qty`,`is_qty_decimal`,`backorders`,`use_config_backorders`,`notify_stock_qty`,`use_config_notify_stock_qty`,`enable_qty_increments`,`use_config_enable_qty_inc`,`qty_increments`,`use_config_qty_increments`,`is_in_stock`,`low_stock_date`,`stock_status_changed_auto`,`is_decimal_divided`,`product_id`,`website_id`,`stock_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `manage_stock` = VALUES(`manage_stock`), `use_config_manage_stock` = VALUES(`use_config_manage_stock`), `qty` = VALUES(`qty`), `min_qty` = VALUES(`min_qty`), `use_config_min_qty` = VALUES(`use_config_min_qty`), `min_sale_qty` = VALUES(`min_sale_qty`), `use_config_min_sale_qty` = VALUES(`use_config_min_sale_qty`), `max_sale_qty` = VALUES(`max_sale_qty`), `use_config_max_sale_qty` = VALUES(`use_config_max_sale_qty`), `is_qty_decimal` = VALUES(`is_qty_decimal`), `backorders` = VALUES(`backorders`), `use_config_backorders` = VALUES(`use_config_backorders`), `notify_stock_qty` = VALUES(`notify_stock_qty`), `use_config_notify_stock_qty` = VALUES(`use_config_notify_stock_qty`), `enable_qty_increments` = VALUES(`enable_qty_increments`), `use_config_enable_qty_inc` = VALUES(`use_config_enable_qty_inc`), `qty_increments` = VALUES(`qty_increments`), `use_config_qty_increments` = VALUES(`use_config_qty_increments`), `is_in_stock` = VALUES(`is_in_stock`), `low_stock_date` = VALUES(`low_stock_date`), `stock_status_changed_auto` = VALUES(`stock_status_changed_auto`), `is_decimal_divided` = VALUES(`is_decimal_divided`), `product_id` = VALUES(`product_id`), `website_id` = VALUES(`website_id`), `stock_id` = VALUES(`stock_id`)"

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-69965 was created;

**Comment by byronlbailey** [comment]
I encountered this problem today.  I checked the code, and the field is currently mapped from the csv field named out_of_stock_qty.  You can update that field to a non-null to get around the problem until the code is fixed.

**Comment by andrea-peter** [comment]
I have the same problem with Magento 2.1.1 and php 7.
I tried to set the field to NULLable but then had the same problem with `use_config_manage_stock` and `use_config_min_qty`, after that I stopped trying to edit the database.

**Comment by magento-engcom-team** [comment]
@Henrique-Oliveira, thank you for your report.
We've created internal ticket(s) MAGETWO-69965, MAGETWO-80757 to track progress on the issue.

**Comment by andrea-peter** [comment]
@byronlbailey Could you please point me to the code where the csv-columns -> table-columns mapping happens?

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#46
