### ISSUE TITLE
Rest API customers/me returns error response structure that is different to swagger documented error structure

### ISSUE THREAD

**Issue by maultby** [magento/magento2#8283]
### Precondtions
 1.  Mag CE 2.1.3
 2. MySQL 5.7.11
 3. PHP 5.6.19

### Steps to reproduce
1.VS2015 C#.
2. Note for "customers/me" and all other API calls Swagger doc for BadRequest response has parameters as an array.
3. Force an error by setting Request to "....customers/me x..." and call api.
3. Response content for parameters returned is not an array.

### Expected result
1. Response content should be:
"{"message":"%fieldName is a required field.","parameters":[{"fieldName":"customer"}],"trace":......}"

### Actual result
1. Actual Response content is:
"{"message":"%fieldName is a required field.","parameters":{"fieldName":"customer"},"trace":......}"
2. When deserialised into a c# class we therefore get an empty parameters array, unless we edit the response content.

**Comment by misha-kotov** [comment]
Thanks for reporting this issue. The internal ticket is MAGETWO-64060. 
For now it looks like swagger reference is incorrect - it's not 100% auto-generated from service interfaces and makes some assumptions in some cases. In most cases that I've seen, "parameters" returns an object and not an array. Let me know if your experience is different.

**Comment by magento-engcom-team** [comment]
@maultby, thank you for your report.
We've created internal ticket(s) MAGETWO-64060 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@maultby, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @maultby. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24737` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
