### ISSUE TITLE
Actions in the admin router can bypass authorization checks

### ISSUE THREAD

**Issue by mattwellss** [magento/magento2#8286]
Because #3736 is in progress and is [scheduled](https://github.com/magento/magento2/issues/3736#issuecomment-232920622) for v2.2, I've been creating controllers during the training course by implementing `Magento\Framework\App\ActionInterface`, rather than extending `Magento\Framework\App\Action\Action`. This works *great* on the `frontend`, but brings up security concerns on `admin`. 

Because the backend authorization checks are implemented in `Magento\Backend\App\AbstractAction#dispatch`, a controller that only implements `Magento\Framework\App\ActionInterface` never gets those checks. Of course, a reasonable engineer knowing this would never create an admin controller by implementing the `ActionInterface`–it's just not safe.

However, the spirit of #3736 applies here just the same:
> This is a blocker for third party developers to use the ActionInterface, as a lot of core functionality will be missing or broken unless Action is extended. Developers are forced to extend Action with all it's dependencies, even though most are not needed.

I'd propose that a `Magento\Backend\App\ActionInterface` which extends the Framework's `ActionInterface` and adds a single method "`_isAllowed()`" would allow most of the authorization logic now residing in the Backend `AbstractAction` to be moved into the admin router (or somewhere else?).

Thank you for taking the time to read this, and for all the hard work on Magento 2!

### Preconditions
Magento version 2.1.3
PHP, MySQL, server irrelevant.

### Steps to reproduce
1. Create an Action implementing `Magento\Framework\App\ActionInterface` _but not_ extending `Magento\Backend\App\AbstractAction`
2. Ensure that the new Action is routed using the Backend router
2. See that the action is accessible without authentication

### Expected result
1. Without authentication, an Actions routed by the Backend router shouldn't be allowed to `execute`

### Actual result
1. The action is executed

**Comment by piotrekkaminski** [comment]
Hi @mattwellss 

I have reported it in our security backlog as PRODSECBUG-1779. Please make sure to report security issues through magento.com/security next time. Thanks!

**Comment by mattwellss** [comment]
@piotrekkaminski thank you for following up!

I struggled with how sensitive this issue was for a while, and next time I'll err more to the side of caution!

**Comment by magento-engcom-team** [comment]
@mattwellss, thank you for your report.
We've created internal ticket(s) MAGETWO-71678 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @mattwellss

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@mattwellss, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
