### ISSUE TITLE
InputException while updating cart with Minimum order amount enabled

### ISSUE THREAD

**Issue by sahirzm** [magento/magento2#8287]
### Preconditions
1. Magento CE 2.1.3 
2. PHP 7.0.13
3. OS: Ubuntu 16.10
4. Apache 2.4.18

### Steps to reproduce
1. In Admin, go to Stores->Configuration->Sales->Sales 
2. In Minimum Order Amount, Select Yes for Enable
3. Fill in Minimum Amount and Description Message.
4. Save Config.
5. In Frontend, Add product to cart.
6. Go to Cart, Change Qty and click Update Shopping Cart. 

### Expected result
Cart Should be Updated with new quantity.

### Actual result
Error 500:
[Wed Jan 25 20:23:35.168951 2017] [:error] [pid 9139] [client 127.0.0.1:55620] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\\Framework\\Exception\\InputException::__construct() must be an instance of Magento\\Framework\\Phrase, string given, called in /var/www/vendor/magento/module-quote/Model/ShippingAddressManagement.php on line 121 and defined in /var/www/vendor/magento/framework/Exception/InputException.php:51
Stack trace:
#0 /var/www/vendor/magento/module-quote/Model/ShippingAddressManagement.php(121): Magento\\Framework\\Exception\\InputException->__construct('Kindly place an...')
#1 /var/www/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\\Quote\\Model\\ShippingAddressManagement->assign('3', Object(Magento\\Quote\\Model\\Quote\\Address))
#2 /var/www/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(76): Magento\\Quote\\Model\\Quote\\ShippingAssignment\\ShippingProcessor->s in /var/www/vendor/magento/framework/Exception/InputException.php on line 51, referer: https://localhost/checkout/cart/

**Comment by miakusha** [comment]
Hi @sahirzm thanks for report
We've created internal ticket MAGETWO-64011 to address this issue.

**Comment by okorshenko** [comment]
Closing this issue. It was fixed in https://github.com/magento/magento2/pull/8474 for develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64399

**Comment by DavaGordon** [comment]
Not fixed in 2.2.0 RC3 i have posted a solution here https://github.com/magento/magento2/issues/6151
