### ISSUE TITLE
CI Build Fail 

### ISSUE THREAD

**Issue by drcsystems2** [magento/magento2#8289]
Hello 
I have made pull request but CI Build Always fails. Here is my job https://travis-ci.org/magento/magento2/builds/195441724
Let me know what I am missing in this. 
Thanks.

**Comment by orlangur** [comment]
Not sure what happened to integration tests (really became too slow? random failure?).

For the unit tests, it seems to be a problem in `setup/src/Magento/Setup/Test/Unit/Module/I18n/FactoryTest.php`, I'm going to fix it soon - for the purpose of PR stabilization you can temporary remove it in your branch.

**Comment by davidalger** [comment]
@drcsystems2 CI builds are currently passing on develop. If you have trouble with Travis on a particularly PR, please try rebasing on latest develop and comment on that PR if the trouble persists (and you don't believe it's due to your changes). Closing.
