### ISSUE TITLE
getOrderPlaceRedirectUrl Doesn't redirect to the gateway secure page

### ISSUE THREAD

**Issue by dvirben123** [magento/magento2#8291]
Hi,
I have the following issue, I generate payment module from the website: http://cedcommerce.com/magento-2-module-creator/payment-module
After deploying it and install it on my Magento 2 site, I can see the new payment module in the admin panel and on the checkout page. now I am trying to make a redirect to the secure page of the gateway payment by overriding the method getOrderPlaceRedirectUrl like that:
http://prntscr.com/e0hozl
Now I expect that on the checkout page when I select the new payment I will be redirected to the secure page of the gateway payment, but it didn't happen, I am using Magento 2.1.
Hope you can help me.
Thanks,
Dvir

**Comment by veloraven** [comment]
@dvirben123 
Thank you for your submission. The Magento 2 GitHub repository is used to capture code and documentation issues. Questions should be posted to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.
