### ISSUE TITLE
I can not translate this part (screenshot)

### ISSUE THREAD

**Issue by eTonki** [magento/magento2#8293]
I can not translate this part (screenshot) 
CE 2.1.3

![screenshot 2017-01-26 12 54 06](https://cloud.githubusercontent.com/assets/25365477/22330665/b2eadf08-e3c7-11e6-92a9-d06cf7b15fbd.png)
![screenshot 2017-01-26 12 53 59](https://cloud.githubusercontent.com/assets/25365477/22330666/b2f12a0c-e3c7-11e6-8313-6a28b768e090.png)

**Comment by veloraven** [comment]
@eTonki thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also specify how you installed localization.
You can leave screenshots as additional information.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
