### ISSUE TITLE
Magento Version 1 v2_soap API differences between 1.9 and 1.9

### ISSUE THREAD

**Issue by maultby** [magento/magento2#8294]
Please advise where to post this if this is the incorrect forum.
We need to establish what differences exist, if any, between V2_soap API in Magento 1.9 and Magento 1.7
Thanks

**Comment by thomvanderboon** [comment]
In any case: This is not a forum, but the tracking database for issues ("bugs") of Magento 2. Pls close this issue as it is not relevant as an issue to Magento 2.

**Comment by veloraven** [comment]
@maultby thank you for your feedback.
The GitHub issue tracker is intended for Magento 2 technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
