### ISSUE TITLE
Magento 2 customer address import does not consider PR (Puerto Rico) a valid country code

### ISSUE THREAD

**Issue by JamesonNetworks** [magento/magento2#8295]
### Preconditions

1. Magento 2 - HEAD of develop

### Steps to reproduce

1. Install a clean instance of Magento 2 on PHP 7.0
2. Import customer-example.csv using the Customer Main file import
3. Import customer-address-example.csv using the Customer Address file import

### Expected result

1.  Expect a customer to get created and have their Puerto Rico address

### Actual result

1. import throws "1. Value for country_id attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s): 1"

[customer-import-files.zip](https://github.com/magento/magento2/files/732784/customer-import-files.zip)

**Comment by JamesonNetworks** [comment]
The same goes for Netherland Antilles (AN)

**Comment by ahbyass** [comment]
This is also the case for table rate shipping it does not recognise PRI (Puerto Rico) when uploading table rate shipping

**Comment by nntoan** [comment]
The same goes for Fiji (FJ)

**Comment by RomanKrut** [comment]
@JamesonNetworks Hi. Thanks for your issue, but Puerto Rico in Magento 2 presented as a state of the United States and if you want to add address with it use attached csv file.
[customer_address.zip](https://github.com/magento/magento2/files/1148496/customer_address.zip)

**Comment by kirtinariya1** [comment]
@krutkoroma79911 
Hello,
I have downloaded your attached zip file but for some reasons it is not extracting.
So, please would you attache it again so we can take reference from your file to resolve PRI issue.  

Or just provide us name in place of PRI which you have added in zip.

Thanks in advance.
