### ISSUE TITLE
Wrong php version detected when installing the Data Migration Tool in ssh. MultiPHP envirornment of WHM / cpanel

### ISSUE THREAD

**Issue by neko-in-space** [magento/magento2#8297]
### Preconditions

1. Magento CE 2.1.3 without sample data is installed.
2. MultiPHP envirornment in WHM / cpanel
3. PHP 7.0.14 (however, the default server's php is v.5.5.38)

### Steps to reproduce

1. Create an account on a server with php 5.5.38
2. Apply php v.7.0.14 to the account using MultiPHP Manager in cPanel.
3. Install Magento 2.1.3
4. Start installing Data Migration Tool in ssh

### Expected result

1. It should detect the correct php v.7.0.14 and install the Data Migration Tool.

### Actual result

1. It detects the default server's php v.5.5.38 and exits the install.
![wrong-php](https://cloud.githubusercontent.com/assets/25376344/22353502/a8007896-e485-11e6-882c-ff4da5491b24.png)

**Comment by neko-in-space** [comment]
Anyone?

**Comment by jamescowie** [comment]
Hello, Sorry but it seems your question is very environment specific and as such is better being asked in the forums. However I will say that this is not a Magento error but more a problem with hosting as the version of PHP you have marked to be installed is not being detected. You can confirm this by running `php -v` from the command line and it will report what version of PHP is running on your server.

**Comment by neko-in-space** [comment]
Thanks for the reply, James. How could it be the hosting problem if php -v displays the correct version but when Magento is installing the Migration Tool it shows something else? Doesn't it mean that, perhaps, Magento uses some sort of wrong call when checking the PHP version?

If this cannot be fixed soon on your end, is there a workaround? How to install the Data Migration Tool manually? I cannot find information on what should be placed in the composer.json file. Does anyone know?

**Comment by neko-in-space** [comment]
Figured out that it's not Magento that is checking php version but the Composer! The solution is forcing Composer to ignore requirements with `--ignore-platform-reqs` option. Like so:

`composer config repositories.magento composer https://repo.magento.com`
`composer require magento/data-migration-tool:<version> --ignore-platform-reqs`
