### ISSUE TITLE
I can't edit Or save changes for products anymore after import cvs file

### ISSUE THREAD

**Issue by kathytrac** [magento/magento2#8299]
[Tierprice.txt](https://github.com/magento/magento2/files/736247/Tierprice.txt)

### Preconditions
I use Magento 2.1.3

### Steps to reproduce
By using Magento 2.1.3 after importing tier price cvs file, I can't edit products in backend anymore.The error in backend is

Warning: Illegal string offset 'price_qty' in vendor/magento/module-catalog/Model/Product/Attribute/Backend/Tierprice.php on line 7

### Expected result
Products can be modified in backend about images , or custom options
### Actual result
I recieve always the red Warning 

Warning: Illegal string offset 'price_qty' in vendor/magento/module-catalog/Model/Product/Attribute/Backend/Tierprice.php on line 7
And nothing from products was changed

**Comment by kathytrac** [comment]
I dont have this problem anymore, after deleting some per cvs imported products, whose sku not normal are ( that means their long sku  consist of distance ).

**Comment by ioliinyk** [comment]
Great, I am closing.
Thank you for report.

**Comment by apurv-anand** [comment]
We also have the same issue. What is the workaround, how is the issue solved?
Can you translate the comment to better English? I cannot make sense out of it.

@kathytrac  "I dont have this problem anymore, after deleting some per cvs imported products, whose sku not normal are ( that means their long sku consist of distance )."

**Comment by kathytrac** [comment]
You should check your imported products , if there are some special sku . For example, sku = abc  09   because there is a blank between abc and 09. That may cause error. Then you should delete all of these sku (manuel or with cvs ) . Then you will not have this error more . You should edit these sku to let them have no blank . Sorry for my english if you dont understand.

**Comment by apurv-anand** [comment]
Thanks for reply @kathytrac . We dont have spaces between the SKU names. Also looking at the error, I dont think that should be causing the offset issue. I would want Magento team to look at it, but this ticket is closed even though others are still facing problem around it. I hope https://github.com/magento/magento2/issues/8426 will be addressed with bit more relevant solution.

**Comment by kathytrac** [comment]
http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_opcache.html
Did you try it ?

**Comment by frankandmaven** [comment]
I've found a correlation between the length of the SKU and this issue. I'm not sure how to go about fixing this beyond shortening the length of the SKU BEFORE uploading. I haven't tested enough to find the exact SKU length, but I know up to 20 characters were saving fine but one with 31 characters was getting this error.
