### ISSUE TITLE
Unable to set product weight and product_has_weight value in import

### ISSUE THREAD

**Issue by jeanpham** [magento/magento2#8303]
I try to import the following CSV file using Magento import: 

sku;weight;product_has_weight
sku-11;1;1
sku-12;1;1

It tells me that import was successfull, but nothing was updated!

### Preconditions
1. Magento 2.1.3

### Steps to reproduce
1. Create a simple product with sku sku-11. Put whatever data, but leave the weight blank and keep 'this item has no weight'.  
2. Create a CSV and put: 

    sku;weight;product_has_weight
    sku-11;1;1
3. Import the CSV file using System > Import

### Expected result

1. I expect 'this item has weight' is selected and weight have a value of ''1'

### Actual result

1. The weight is not '1' and 'item has no weight' is selected
See screenshot: https://snag.gy/GH7T04.jpg

**Comment by mbrinton01** [comment]
Appears to relate to #8228

**Comment by veloraven** [comment]
@jeanpham when you create a product without weight you create a virtual product. You can not add a weight to a virtual product via import. You should convert your product to a simple one and then update its weight. You can find more discussion in #8228
