### ISSUE TITLE
Impossible to turn off conversion currency

### ISSUE THREAD

**Issue by strauss69400** [magento/magento2#8305]
Hi
I have two views for my website. A view for Europe and another for the Swiss.

Currencies are different but the problem is i would like to choose prices for each view. Currently, prices for my second view are converted automatically.

So, i would like to know how to turn off this conversion.

Thanks for your help Best regards

**Comment by veloraven** [comment]
@strauss69400 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

If you want to report an issue please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
