### ISSUE TITLE
Fatal error with testSetCache

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#8308]
### Preconditions

1. magento: develop
2. PHP 7.0.15

### Steps to reproduce

1. Run `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist`

### Expected result

1. Tests to complete

### Actual result

1. Test do not complete exit code is 2

When running phpunit in debug mode as `./vendor/bin/phpunit --debug -c dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/Model/Cron/JobSetCacheTest.php` you will see

```
Fatal error: Method Symfony\Component\Console\Input\ArrayInput::__toString() must not throw an exception, caught ErrorException: preg_match() expects parameter 2 to be string, array given in /var/www/html/mage2-github/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 0
```

This seems to be caused by `JobSetCacheTest::setCacheDataProvider` and the multi-level array used in the `$cacheEnable = new ArrayInput(['command' => 'cache:enable', 'types' => ['cache1']]);`

**Comment by orlangur** [comment]
Thanks for your finding, I did not expect `--debug` could be broken when debugged unit tests under PHP 7.1 and it was crashing trying to print data provider before the problematic test execution:

```
Starting test 'Magento\Setup\Test\Unit\Model\Cron\JobModuleTest::testExecuteModuleDisable'.
.
Starting test 'Magento\Setup\Test\Unit\Model\Cron\JobModuleTest::testExecuteModuleEnable'.
[33;1mI[0mPHP Fatal error:  Method Symfony\Component\Console\Input\ArrayInput::__toString() must not throw an exception, caught ErrorException: preg_match() expects parameter 2 to be string, array given in /home/travis/build/orlangur/magento2/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 0
```

Basically, I came here trying to google for stack trace :D
