### ISSUE TITLE
Create Credit Memo for Paypal transactions. Blank screen if fund in Paypal can't cover it.

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#8309]
### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Low balance in Paypal (balance not able to cover the refund)
2. Create a credit memo for paypal express checkout transactions

### Expected result

1. Credit memo created 
2. Paypal refunded.
3. If the fund can't be cover by the balance, Paypal should initial a fund transfer from the bank. 

### Actual result

1. blank screen.

2. error_log
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\\Framework\\Exception\\LocalizedException::__construct() must be an instance of Magento\\Framework\\Phrase, string given, called in /var/www/vhosts/xxxxxx.com/httpdocs/vendor/magento/module-sales/Model/Service/CreditmemoService.php on line 185 and defined in /var/www/vhosts/xxxxxx.com/httpdocs/vendor/magento/framework/Exception/LocalizedException.php:34\nStack trace:\n
#0 /var/www/vhosts/xxxxxx.com/httpdocs/vendor/magento/module-sales/Model/Service/CreditmemoService.php(185): Magento\\Framework\\Exception\\LocalizedException->__construct('PayPal gateway ...')\n
#1 /var/www/vhosts/xxxxxx.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\\Sales\\Model\\Service\\CreditmemoService->refund(Object(Magento\\Sales\\Model\\Order\\Creditmemo\\Interceptor), false)\n
#2 /var/www/vhosts/xxxxxx.com/httpdocs/var/generation/Magento/Sales/Model/Service/CreditmemoService/Interceptor.php(26): Magento\\Sales\\Model\\Service\\CreditmemoSer...\n', referer: https://www.xxxxxx.com/xxxxx/sales/order_creditmemo/new/order_id/223/invoice_id/192/key/53f6587d911461xxxxxxxxxxxxxxxxxxxe66f219a94aab/

**Comment by olekluk** [comment]
I got the same error message.
I believe this is a bug.

Magento 2.1.3
Payment method: Credit Card (Braintree)
Environment: Sandbox
Payment Action: Authorize

1) Create order
2) Create invoice
3) Create credit memo for invoice
4) Press "Refund" button

Expected result
Save credit memo, perform refund action at Braintree

Current result
Magento Admin panel. Error message "We can't save the credit memo right now."
var/log/exception.log 

`[2017-01-29 19:03:35] main.CRITICAL: exception 'Exception' with message 'Recoverable Error: Argument 1 passed to Magento\Framework\Exception\LocalizedException::__construct() must be an instance of
 Magento\Framework\Phrase, string given, called in /home/vippstony/public_html/vendor/magento/module-sales/Model/Service/CreditmemoService.php on line 185 and defined in /home/vippstony/public_html
/vendor/magento/framework/Exception/LocalizedException.php on line 34' in /home/vippstony/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /home/vippstony/public_html/vendor/magento/framework/Exception/LocalizedException.php(34): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/home/vippstony...', 34, Array
)
#1 /home/vippstony/public_html/vendor/magento/module-sales/Model/Service/CreditmemoService.php(185): Magento\Framework\Exception\LocalizedException->__construct('Transaction has...')
#2 /home/vippstony/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(105): Magento\Sales\Model\Service\CreditmemoService->refund(Object(Magento\Sales\Model\Orde
r\Creditmemo), false)
#3 /home/vippstony/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute()
#4 /home/vippstony/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->execute()
#5 /home/vippstony/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /home/vippstony/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent('dispatch', Array)
#8 /home/vippstony/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\S
ales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminAuthentica...')
#9 /home/vippstony/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Ob
ject(Magento\Framework\App\Request\Http))
#10 /home/vippstony/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml
\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento
\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminMassaction...')
#12 /home/vippstony/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interc
eption\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml
\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /home/vippstony/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->__
_callPlugins('dispatch', Array, Array)
#15 /home/vippstony/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch(Object(Magento\Framework\App\Req
uest\Http))
#16 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /home/vippstony/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#18 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\
Framework\App\FrontController\Interceptor), Array, 'install')
#19 /home/vippstony/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(
Magento\Framework\App\Request\Http))
#20 /home/vippstony/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontContr
oller\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /home/vippstony/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /home/vippstony/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/vippstony/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#24 /home/vippstony/public_html/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#25 {main} [] []
`

**Comment by YevSent** [comment]
Hi, guys, thanks for reporting, this is known issue (internal ticket MAGETWO-62428) and fix will be available in Magento 2.1.4 version.

**Comment by jingseow** [comment]
Hi guys, is there any interim solution to this? This is a pretty big roadblock for one of our site launch.

**Comment by YevSent** [comment]
@jingseow, this issue is fixed in Magento 2.1.4 version.

**Comment by wigman** [comment]
For those searching for the fix, this is the commit: https://github.com/magento/magento2/pull/9677/commits/14af54cf091ce21f3cde7676cd7664a760c5de28#diff-bec52ee9b2dae928540b68bcb0479021

**Comment by patrickpeng2091** [comment]
Some email related plugins will cause this problem。
