### ISSUE TITLE
Missing images should return 404 error

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#831]
When editing a product in the backend, if one of the product images is missing I still get a 200 response.  
If I take a look at the url I see an error message 

> Fatal error: Cannot instantiate interface Magento\Framework\App\Config\Scope\ReaderPoolInterface in

Missing images should give back a 404 response without going through the application.

**Comment by otoolec** [comment]
@tzyganu does the response from @buskamuza resolve this issue for you?  If you enable production mode then you should see a 404 error without the application being launched.

Can you confirm that this is the behavior you are seeing and close the issue?  If you disagree, can you provide more information on what you would like to see changed?

**Comment by tzyganu** [comment]
@otoolec @buskamuza It seams to be ok now. On beta 2 I get the correct 404  message even if I'm on the developer mode. I don't know if this was an intentional fix or a side effect for something else. But that's not important. Thanks for it.
