### ISSUE TITLE
PayPal Express Checkout Discards Address Line 2 For Billing and Shipping Addresses

### ISSUE THREAD

**Issue by twoonesixdigital** [magento/magento2#8313]
### Preconditions
1. PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
2. mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
3. Magento CE 2.1.3

### Steps to reproduce
1. Initiate a PayPal Express Checkout.
2. Over on PayPal, select a shipping address that has street address line 2 data such as a company name or apartment number.
3. Confirm your details and payment method over on PayPal and then continue to be returned to Magento's PayPal Express Checkout Order Review page.

### Expected result
1. The quote's shipping and billing addresses should be consistent with the address data provided by PayPal including the street address line 2 data.

### Actual result
1. Address line 2 data returned by PayPal is not saved with the address in the module's returnFromPaypal function.
2. Specifically, in /vendor/magento/module-paypal/Model/Express/Checkout.php, the result of getExportedShippingAddress() does contain the "street2" property, however as Magento's quote_address and sales_order_address tables do not have a separate "street2" column, the data is discarded when the quote is saved.
3. Rather than storing the address line 2 data in a separate "street2" property of the address object, it should be appended to the existing "street" data. 

For a quick hacky fix, I've added the following snippets to the end of the shipping and billing address processing sections of /vendor/magento/module-paypal/Model/Express/Checkout.php

$shippingAddressLineOne = $shippingAddress->getData('street');
				$shippingAddressLineTwo = $shippingAddress->getData('street_2');
				if(strlen($shippingAddressLineTwo) > 0) {
					if(stripos($shippingAddressLineOne, $shippingAddressLineTwo) === false) {
						$shippingAddress->setStreet($shippingAddressLineOne . "\r\n" . $shippingAddressLineTwo);
					}
				}

$billingAddressLineOne = $billingAddress->getData('street');
		$billingAddressLineTwo = $billingAddress->getData('street_2');
		if(strlen($billingAddressLineTwo) > 0) {
			if(stripos($billingAddressLineOne, $billingAddressLineTwo) === false) {
				$billingAddress->setStreet($billingAddressLineOne . "\r\n" . $billingAddressLineTwo);
			}
		}

**Comment by viktym** [comment]
Hi @twoonesixdigital 
We've created internal ticket MAGETWO-64833 to address this issue.
Thank you for reporting.

**Comment by joebusby** [comment]
@twoonesixdigital   Thanks for reporting this.  I hope we can get the fix in the next release, this is a healthy burden, causing us to re-ship many orders that will arrive late.  Some do get detected by our Endicia service, but a fix would be well appreciated.

**Comment by alena-marchenko** [comment]
Hi @twoonesixdigital 

Fix for MAGETWO-64833 is merged to develop branch, closing the issue.
Thank you.

**Comment by mslocock** [comment]
@magento-team we are using v 2.1.7 and still seeing this issue, could you confirm if the fix is part of 2.1.7 or not?

**Comment by valdislav** [comment]
Looks like this is not in 2.1.7.

**Comment by mslocock** [comment]
It looks like this is fixed and the patch is goign to be included in 2.2.

We applied this this patch to 2.1.7 and 2.18 and it solved the problem for us:
https://github.com/magento/magento2/commit/b424fdc22c4d33bf2da38d0033dabb0d7a60ba67 

I hope this helps any else who has this issue.
