### ISSUE TITLE
Error with StdoTest

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#8315]
### Preconditions

1. Magento: develop
2. PHP 7.0.15

### Steps to reproduce

1. Run `./vendor/bin/phpunit --debug -v -c dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/Module/I18n/Dictionary/Writer/Csv/StdoTest.php`

### Expected result

1. Assertion to show as all green

### Actual result

1. PHPUnit cannot output anything as it uses the STDOUT stream which has just been destroyed in the teadown of the test.

I am not even 100% if this testing is actually makes sense. But because of the `__destruct` method in `Magento\Setup\Module\I18n\Dictionary\Writer\Csv` the output will always be closed and then PHPUnit will fail when trying to write the test results to the screen.

**Comment by dmanners** [comment]
This also causes the same issue while running the test `setup/src/Magento/Setup/Test/Unit/Module/I18n/FactoryTest.php`

**Comment by dmanners** [comment]
If you run phpunit with the `--stderr` option then this problem will not occur. Is this the desired option here? I mean it works but to me it seems that there could be deeper issues with closing `STDOUT` that might not be obvious.

Actually that seems to cause issues with the session tests also.

**Comment by dmanners** [comment]
Is this an obsolete class? I found it referenced in `dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php` if that is the case can we remove the class or tests?

**Comment by schmengler** [comment]
"Is this an obsolete class?" I hope so. It can break everything by closing STDOUT...

**Comment by okorshenko** [comment]
@dmanners thank you for reporting the issue. Internal ticket: MAGETWO-64853

**Comment by okorshenko** [comment]
@dmanners @schmengler class `Magento\Setup\Module\I18n\Dictionary\Writer\Csv` is not obsolete. This class replaces removed class `Magento\Tools\I18n\Dictionary\Writer\Csv`.

The file `dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php` has the follwing format: [`Removed\Class\Name`, `Class\Name\To\Use`]

**Comment by orlangur** [comment]
If `setup/src/Magento/Setup/Test/Unit/Module/I18n/FactoryTest.php` really needs to be implemented this way (it is not "unit test" as it implicitly instantiates another object with "bad" destructor) and if `Factory` implementation really needs to instantiate object directly with `new` operator like it does currently then the only way to fix it is to create a stub of `Writer/Csv/Stdo` with not so evil destructor.

@okorshenko, please consider running unit/integration tests with `--debug` option on daily/weekly basis or as a part of release activity.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64462
