### ISSUE TITLE
No method for having both exchange rates applied and sell in same currency that is displayed

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#8316]
There is no default mechanism within M2 to allow a multi store setup to both apply exchange rates AND sell the final product in the same currency that is displayed.

### Preconditions
1. Magento 2.1.3 CE
2. PHP 7
3. NginX (hosted service)

### Steps to reproduce

1. Setup two website/store/store views (as such):
 USA_Website (set this as default) / USA_Store / USA_StoreView 
 CA_Website                                  / CA_Store / CA_StoreView

2. Apply US Currency for all USA_ 
3. Apply CAD for CA_Store/view for both Base Currency and Display Currency
4. Create a test product with the default view price of 100.
5. Set the Allowed currencies to CAD and US for the Default Store View
5. Update the Exchange rate in Stores > Currency Rates (you should have both US and CAD rates)

### Expected result

1. On the CA_StoreView the product should display with the exchange rate applied, AND allow the sale to be processed in the desired CAD currency.

### Actual result

1. Currently, if you need/want the exchange rate to be applied, you need to have the Base Price set to US and the Display price set to CAD. This works fine, until you get to the checkout page, at which point now it wants to process the sale via (authorize.net / paypal) in US funds and not the CAD funds. This is ok in some countries, but in Canada, most banks charge a "double conversion fee" for charging a US item in US funds on a Canadian CC, and usually not on the same day, so many times they buyer can get charged MORE than what they were told on the website.

If however, you then change the BASE and Display rates to CAD, now the products display their Price without any exchange rate being applied, but the sale will be processed in CAD funds. There is no option to force an exchange rate on a particular store view, even if you wanted (without coding a custom extension, which shouldnt be necessary since this is SUCH a common business problem... I've come across 30+ threads describing this exact problem, but no real solution).

**Comment by magento-engcom-team** [comment]
@spyrule, thank you for your report.
We've created internal ticket(s) MAGETWO-82807 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @spyrule

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@spyrule thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
