### ISSUE TITLE
Adding a product to a website with "Default Values" breaks the url key. Inconsistent with creating product in multiple websites up front.

### ISSUE THREAD

**Issue by peterhirn** [magento/magento2#8318]
#### Scenario 1 (working)
1. Add product
2. Check all websites in `Product in Websites`
3. Set `URL Key`
4. Product reachable in all websites with given url key

#### Scenario 2 (broken)
1. Add product
2. Check only one website in `Product in Websites`
3. Set `URL Key`
4. Save product
6. Add product to second website using `Copy Data from` -> `Default Values`
7. Product **not** reachable in second websites with given url key
8. In broken store view checkbox `Use Default Value` for `URL key` can't be saved.

### Preconditions
1. Magento 2.1.3 CE 
2. Multiple websites configured
### Steps to reproduce
1. Add product
2. Check only one website in `Product in Websites`
3. Set `URL Key`
4. Save product
6. Add product to second website using `Copy Data from` -> `Default Values`
### Expected Result
Product is reachable in second websites with given url key
### Actual Result
 Product **not** reachable in second websites with given url key
 In broken store view checkbox `Use Default Value` for `URL key` can't be saved.

**Comment by thomvanderboon** [comment]
This problem might be closely related to the issue I reported earlier when you do the same via the SOAP interface https://github.com/magento/magento2/issues/6256

**Comment by thlassche** [comment]
I developed a workaround for this. If you are interested, please let me know

**Comment by philipvandebriel** [comment]
@thlassche will this work with a multistore en different url keys per store view ?

**Comment by thlassche** [comment]
@philipvandebriel Sure!

**Comment by maderlock** [comment]
What workaround are you using? Please could you post the solution to this issue?

**Comment by thlassche** [comment]
@maderlock Search for rewrites in the Magento Marketplace

**Comment by magento-engcom-team** [comment]
@peterhirn, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
