### ISSUE TITLE
Admin: Error when product image file is missing

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#8322]
Due to issues with my installation I had to revert to a partial re-install and partial restore from a backup. Problem was that some media files (images of products) were not completely restored from backup, but I had a complete restore from the database.

If for some reason the product image is missing, you cannot edit the product from admin.

### Preconditions
1.  Install Magento 2.1.x and make it working

### Steps to reproduce
1.  Create a product and add a image
2.  Delete the image file somewhere in the pub/media folder

### Expected result
1. Product is displayed and produces error that the image file is missing (preferably with option to delete the reference to the deleted image file)

### Actual result
1. Breaking error: Cannot gather stats! Warning!stat(): stat failed for /complete/path/to/image.jpg
2. You cannot edit this product anymore, until you replace the image file with something

**Comment by hostep** [comment]
I'm pretty sure this was fixed in the [2.1.3 release](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html):

> Magento no longer displays an exception when it cannot find a product image file. (GITHUB-5184), (GITHUB-5497), (GITHUB-3545), (GITHUB-5871)

**Comment by thomvanderboon** [comment]
OK.... that might explain everything.... I am unable to run 2.1.3 due to another bug. Searched the issues db, but found nothing..... will reopen it if needed
