### ISSUE TITLE
Admin: Product name in grid not updated for all store views

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#8323]
If a product name is updated for all store views, the product grid keeps showing the "old" product name.

### Preconditions
1.  Magento 2.1.x

### Steps to reproduce
1. Add products via SOAP. Note: My ERP system has a only 35 position "Product Name" field, so a product name of only 35 positions is added
2. Keep the "Store View" scope to "All Store views"
3. Edit the product and change the "Product Name"
4. Save and close the product

### Expected result
1. Edited Product name is displayed correctly in the product grid 

### Actual result
1. Product name (as provided by SOAP) is displayed

**Comment by gvigner** [comment]
Same problem here, either it's updated for a given store (set by attribute_set_id) with "/rest/V1/" or it's set for "All Store Views" (global?) only with "/rest/all/V1/". Is it a bug ? How can I fix it with Magento 2.1.3 ?

**Comment by gvigner** [comment]
Same problem here.

If I use this API:
http://my.website.com/index.php/rest/default/V1/
Only the default store is updated, not the global scope.

Now if I use this API:
http://my.website.com/index.php/rest/all/V1/
Only the global scope is changed, not the default store.

How to fix it ?

**Comment by TomashKhamlai** [comment]
Thanks for reporting this issue.

I can not reproduce this problem on Magento v2.1.7. My actual result is the same as expected.
Technical details of software that was used for testing the issue you reported:
```
CentOS Linux release 7.2.1511 (Core)

Linux version 3.10.0-327.28.2.el7.x86_64 (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9)

PHP 7.0.9 (cli) (built: Jul 20 2016 17:58:41) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

MySQL Server version: 5.6.32 MySQL Community Server (GPL)
```
Do you remember which version of Magento were you using? Please, give us more details.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by unfunco** [comment]
The following comment is to assist anyone that might find this reported issue when searching for a solution to the same problem.

When running in single store mode and creating a product via admin, it is created with store ID 0 (admin) – however; we had a third party creating products via the REST API and they were creating products under both store IDs 0 (admin) and 1 (default), when we manually edited a product via the admin interface, it would update the record for the product under store ID 0 but not the record under store ID 1. Products within the default store view take precedence over those in the admin store view in the grid.

To confirm this is your issue, you should see more than one row if run the following SQL:

```SQL
SELECT entity_id, value, store_id
FROM catalog_product_entity_varchar
WHERE entity_id = <product_id>
AND attribute_id = (
    SELECT attribute_id
    FROM eav_attribute
    WHERE entity_type_id = 4
    AND attribute_code = 'name'
);
```

Similar issues reported here:
magento/magento2#7877
magento/magento2#9874
