### ISSUE TITLE
Upgrade from 2.1.0 to 2.1.3 fatal error on mode:set:production

### ISSUE THREAD

**Issue by cinderblocks** [magento/magento2#8324]
### Preconditions

1. Magento 2.1.3
2. PHP 7.0.15 (also tried 7.0.8)
3. Running in Docker container, php-fpm, nginx, redis extension
4. Docker container running on AWS Elastic Beanstalk Multi-Docker Environment
5. MySQL 5.7.1 RDS instance running on AWS

### Steps to reproduce
1. Upgraded Magento from 2.1.0 to 2.1.3 using `magento setup:upgrade`
2. Run `magento deploy:mode:set production`
3. Observe fatal error upon deployment of static content

### Expected result
I expect Magento to start in deploy mode.

### Actual result
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content
Something went wrong while deploying static content. See the error log for details.
Command returned non-zero exit code:
`/usr/local/php/bin/php -f /data/www/bin/magento setup:static-content:deploy en_US`

From system.log:

New version of deployed files: 1485709152
PHP Fatal error:  Uncaught Exception: Warning: Error while sending QUERY packet. PID=259 in /data/www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228 in /data/www/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Error while sen...', '/data/www/vendo...', 228, Array)
#1 /data/www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#2 /data/www/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#3 /data/www/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /data/www/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /data/www/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `session...', Array)
#6 /data/www/vendor/magento/frame in /data/www/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Stack trace:
PHP   1. {main}() /data/www/bin/magento:0
PHP   2. Symfony\Component\Console\Application->run() /data/www/bin/magento:23 [] []

### What I have tried
1. Increasing RAM in container to 2GB
2. Doubling resources in RDS instances
3. Maxing out all wait timeouts and packet size configuration options in both php-fpm and MySQL
4. Converting the database to aurora
5. Connections to both Redis and MySQL succeed and can be queried from inside the container, including the specific query noted in the call stack 
6. Disabling Redis in Magento config does not help

**Comment by misha-kotov** [comment]
Thanks for the issue report! I've put this issue in the queue for engineering team to investigate.

**Comment by kandy** [comment]
Hi @cinderblocks
Can you try run
/usr/local/php/bin/php -f /data/www/bin/magento setup:static-content:deploy -j 0 en_US? Is issue still here?
Does DB Session Handler is configured?

**Comment by cinderblocks** [comment]
Hello, thank you for the reply @kandy 

Yes, `/usr/local/php/bin/php -f /data/www/bin/magento setup:static-content:deploy -j 0 en_US?` does indeed work where without `-j 0` it fails. Can `-j 0` be passed to the `deploy:mode:set` command as well?

DB Session Handler is configured, yes.

**Comment by kandy** [comment]
No, looks like you cannot passed it to deploy:mode:set :(

**Comment by kandy** [comment]
You can run  `deploy:mode:set -s`, then run `setup:static-content:deploy -j 0`, and  `setup:di:compile` as workaround

**Comment by igrybkov** [comment]
Hi,

Thanks for reporting this issue.

Unfortunately, we cannot reproduce the issue. The workaround provided by @kandy should work, but we still cannot see it on any of our environments.
To proceed we need to know how exactly we may reproduce it not depending on your environment configuration.
Please provide the detailed steps we must follow to reproduce this issue from the scratch.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
