### ISSUE TITLE
DB schema changes default address and billing

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#8326]
### Data integrity issue 
Columns `default_billing` and `default_shipping` in the `customer_entity` table don't have a FK assigned.

If for some reason a record is manually deleted from the `customer_address_entity` table, non-existing references will remain in these columns and an exception will be raised when trying to load default customer addresses

### Preconditions
1. Magento 2.*
 
### Proposed DB Schema changes
```MySQL
ALTER TABLE `customer_entity` ADD INDEX `CUSTOMER_ENTITY_DEFAULT_BILLING` (`default_billing`);

ALTER TABLE `customer_entity` ADD INDEX `CUSTOMER_ENTITY_DEFAULT_SHIPPING` (`default_shipping`);

ALTER TABLE `customer_entity` ADD CONSTRAINT `CUSTOMER_ENTITY_DEFAULT_SHIPPING_ADDRESS_ID` FOREIGN KEY (`default_shipping`) REFERENCES `customer_address_entity` (`entity_id`)   ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE `customer_entity` ADD CONSTRAINT `CUSTOMER_ENTITY_DEFAULT_BILLING_ADDRESS_ID` FOREIGN KEY (`default_billing`) REFERENCES `customer_address_entity` (`entity_id`)   ON UPDATE CASCADE ON DELETE SET NULL;
```

**Comment by veloraven** [comment]
@bvboas thank you for your submission.
Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
