### ISSUE TITLE
customer/create_account/vat_frontend_visibility gets saved using the websites scope while it's being retrieved using the stores scope

### ISSUE THREAD

**Issue by royvanos** [magento/magento2#8328]
### Preconditions

1. Magento 2.1.3 CE
2. PHP 7.0.12
3. MySQL 5.7.11-0ubuntu6

### Steps to reproduce

1. Any Magento 2.1.3 installation
2. Go to Configuration > Customers > Customer Configuration
3. Switch to "Main Website" scope
4. Set the "Show VAT Number on Storefront" value to "Yes"
5. Save Config

### Expected result

1. vendor/magento/module-customer/Helper/Address.php:369 should retrieve customer/create_account/vat_frontend_visibility using the websites scope as the config gets saved in the database using the websites scope.

### Actual result

1. vendor/magento/module-customer/Helper/Address.php:369 retrieves customer/create_account/vat_frontend_visibility using the store scope which (I think) makes it fall back to the default scope.

I worked around this issue by setting the customer/create_account/vat_frontend_visibility using the stores scope manually in the core_config_data table.

**Comment by hostep** [comment]
This is a new bug introduced Magento 2.1.3, it is being tracked over here: https://github.com/magento/magento2/issues/7943

**Comment by OleksandrBurianyk** [comment]
Hi. 
1)Could you check the issue on the last verson of Magento (2.1.7)? 
2) Please provide more information in case that isse still exists about exeprected/actual results. Maybe some visual information/screenshot with the trouble.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
