### ISSUE TITLE
Getting Fatal error when refund method throw exception

### ISSUE THREAD

**Issue by yogeshkarodiya** [magento/magento2#8330]
I am getting below error when any exception throws in refund() method

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Framework\Exception\LocalizedException::__construct() must be an instance of Magento\Framework\Phrase, string given, called in 
/vendor/magento/module-sales/Model/Service/CreditmemoService.php on line 185 and defined in /vendor/magento/framework/Exception/LocalizedException.php on line 34

I know solution but this is core file so how can i handle above error.

**Comment by YevSent** [comment]
The same exception as in https://github.com/magento/magento2/issues/8309. Closing as duplicate.
