### ISSUE TITLE
Product Image not showing in backend and can't upload image

### ISSUE THREAD

**Issue by 12impress** [magento/magento2#8337]
### Preconditions

1. Magento 2.1.3
2. PHP 7.0.8
3. MySQL 5.6.30

### Steps to reproduce

1. Clean install and added products by CSV
2. Everything looks good at the store front
3. By adding a new product manually, image is not uploading.

### Expected result

1. Normally the image has to be upload

### Actual result

1. When Edit or add new product in admin (backend) the product image doen't show up
2. When choosing image to upload, nothing happens

![image](https://cloud.githubusercontent.com/assets/18406773/22436485/971c9ee6-e724-11e6-91c5-587255a4dabf.png)
[Screenshot, logs]

**Comment by 12impress** [comment]
I found the issue and it is a bug in Magento. Also updated to 2.1.4 but still the same issue.

The problem is in the language files. 

I followed the next steps:

Set Configuration -> General -> Locale Options -> Locale

    For Default Config: admin language (English) US

Also check if your admin language is set to en_US.

I did now:
Delete /pub/static/_requirejs
Delete /pub/static/adminhtml
Delete /pub/static/frontend

SSH
php bin/magento setup:static-content:deploy
php bin/magento cache:clean

Now I can add and edit images like normal. But I am missing a lot of tekst om my screen.

![image](https://cloud.githubusercontent.com/assets/18406773/22824040/922f90ea-ef86-11e6-8fa6-b7f2681097bc.png)


When I deploy all languages, I have the issue again....

**Comment by 12impress** [comment]
It looks like this issue, but this is not my solution:
https://github.com/magento/magento2/issues/7862

**Comment by alrayn** [comment]
What we can do ?

It's a major issue.

**Comment by 12impress** [comment]
I solved it..!
I made a clean setup from Magento. Than connect the old database.
Now the problem was solved.

**Comment by magento-engcom-team** [comment]
@carfantasy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by vikktor** [comment]
Same problem uploading product images does not work, nothing happens (however image is uploaded to /pub/media/tmp/catalog/product/... succesfully but it never shows up anywhere) - solved it by doing what @carfantasy suggested - switching back from croatian to original english, but after that I switched back to croatian and now it's working (we'll see for how long...). 

Magento 2.1.8

**Comment by Carcinie** [comment]
Not able to upload on 2.2.0 clean install.

**Comment by ci2014** [comment]
Able to reproduce on 2.2.1 after using Data Migration Tool from Magento 1.9.4

**Comment by 3wlink** [comment]
Hello, I am facing the same issue in version 2.2.4. Category image upload works fine, but product image upload and video does not work, nothing happens, even image is not uploaded to media folder. This is the first time I am using Magento (with default Luma theme), so I don't understand what to do now. Any help will be highly appreciated.

**Comment by cralls** [comment]
Same issue on 2.2.3 after migrating data from 1.9.2.2. @carfantasy solution does not work. Any other work arounds? This is a huge issue

**Comment by JMLucas96** [comment]
Same issue on magento 2.1.8 ce...
@vikktor's solution not working for me.

**Comment by kingkoo13** [comment]
any Solution for this issue ?

**Comment by cralls** [comment]
@kingkoo13 I can't remember what I did but I got around it. Do you have any js errors in your console?

**Comment by kingkoo13** [comment]
No js errors , even on my local its working .

the main issue is on server (centos 7)

**Comment by cralls** [comment]
@kingkoo13 I'm using centos as well. It could be so many things causing it. You need an error message to give yourself some direction. If there's nothing in the JS console then what about on the Network tab of your developer tools (assuming you're using chrome). Open developer tools and refresh the page and see if there are any urls reporting something other than 200. If so that will give you some direction. Then you can look at apache error logs as well as var/log/system.log and var/log/exception.log.

**Comment by kingkoo13** [comment]
i found nothing relevant in logs .

now iam going to check same on fresh Magento2 with same db .
