### ISSUE TITLE
Order Success Page Does Not Display Using Authorize.net Direct Post

### ISSUE THREAD

**Issue by andresrecalde** [magento/magento2#8339]
### Preconditions

1. Magento ver. 2.1.3
2. PHP 7
3. Authorize.net in Production Mode

### Steps to reproduce

1. Create order, select Authorize.net as payment method, attempt to complete order

### Expected result

1.  Page should be routed to Success page

### Actual result

1. Pop-up Displays with "Sorry, but something went wrong. Please contact the seller." - Screenshot attached
2. Payment is posted in Authorize.net as expected
3. Order is created as expected in a status of "Processing"
4. Debug log shows valid request/response (attached)
5. Nothing in Exception log
6. One JS error on page (not sure if related, attached)
<img width="1023" alt="screen shot 2017-01-30 at 11 50 25 pm" src="https://cloud.githubusercontent.com/assets/23403774/22452711/34100db0-e747-11e6-9969-75836ad9fb9f.png">
<img width="1273" alt="screen shot 2017-01-30 at 11 49 49 pm" src="https://cloud.githubusercontent.com/assets/23403774/22452708/340f5a96-e747-11e6-9268-ac778659e5b7.png">
<img width="1278" alt="screen shot 2017-01-30 at 11 50 04 pm" src="https://cloud.githubusercontent.com/assets/23403774/22452712/34107070-e747-11e6-883f-6e18c75b6975.png">
<img width="1279" alt="screen shot 2017-01-30 at 11 50 14 pm" src="https://cloud.githubusercontent.com/assets/23403774/22452710/340fee66-e747-11e6-8075-352bc807f584.png">
<img width="407" alt="screen shot 2017-01-30 at 11 50 39 pm" src="https://cloud.githubusercontent.com/assets/23403774/22452709/340fa762-e747-11e6-81a2-cb801db2eb57.png">

**Comment by viktym** [comment]
Hi @andresrecalde 
We cannot reproduce this issue as described. Please provide a customer type (guest/registered) and product type.
According to your debug.log everything is ok with authorize.net paymet flow.
One of the XMLHttpRequests leads to js error.
This error blocks js redirect to order success page and after some timeout, you see error pop-up (fires automatically if customer isn't redirected to another page after placing an order with authorize.net)
Please take a look at failed XMLHttpRequest list. It might help to define a problem.

**Comment by YevSent** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks.

If you still can reproduce the issue, please, be free to reopen it.
