### ISSUE TITLE
Multishipping Select Shipping method page does not show address id in change link in first address

### ISSUE THREAD

**Issue by ajaysinghrana23** [magento/magento2#8340]
**Preconditions**
1. Magento ver. 2.1.3
2. PHP 7

**Steps to reproduce**
1. Add multiple product to cart (minimum 2 product or 1 product with quantity 2) and  Check Out with Multiple Addresses and select different shipping address for the products you wants to ship and now click on Go to shipping information button. You will reach to Select Shipping Method page.. Now if you see Change link in addresses section (left side) you will see that you do not get address id in first link whereas you get address id in all other addresses except first. for example for first link is formed like this http://abc.com/multishipping/checkout_address/editShipping/
**address id is missing** "/id/6/"

other links are correct like this
http://abc.com/multishipping/checkout_address/editShipping/id/3/

**Expected result**
1. link should be formed like this for change link http://abc.com/multishipping/checkout_address/editShipping/id/6/

**Actual result**
1. Links are formed like in attached screenshot
![magento commerce -magento213_multishipping_checkout_shipping](https://cloud.githubusercontent.com/assets/25449889/22454341/21e2103e-e7ab-11e6-8494-7b6028f6567b.png)

**Comment by veloraven** [comment]
@ajaysinghrana23 thank you for your report.
Please format steps to reproduce section so that looks like:
Steps:
1. Add...
2. Check out ...
3. ...
4. ...
As it's hard to read and understand actual problem when all the steps are in one paragraph.

**Comment by ajaysinghrana23** [comment]
To reproduce sections please follow steps:
1. Add multiple product to cart (minimum 2 product or 1 product with quantity 2) .
2. Check Out with Multiple Addresses.
3. Select different shipping address for the products you wants to ship.
4. Now click on Go to shipping information button. 
5. You will reach to Select Shipping Method page..
6.  Now if you hover on Change link in addresses section (left side).
7. You will see that you do not get address id in first link. 
8. address id is missing "/id/3/" from link , Link is like this http://abc.com/multishipping/checkout_address/editShipping/
9. Whereas you get address id in all other addresses. link is formed like this 
http://abc.com/multishipping/checkout_address/editShipping/id/6/

![21e2103e-e7ab-11e6-8494-7b6028f6567b](https://cloud.githubusercontent.com/assets/25449889/22551328/6bab644c-e97a-11e6-8167-ea8f7e5e0cf7.png)

**Comment by miakusha** [comment]
Hi @ajaysinghrana23 thanks for report. Its acknowledged problem
Fix for issue already pushed to develop branch [2d709874c2af3cd51907](https://github.com/magento/magento2/commit/2d709874c2af3cd5190725e8d84dc0286bb2e3c3).
