### ISSUE TITLE
Getting internal server error when posting wrong parameter in API request

### ISSUE THREAD

**Issue by cedcommerce** [magento/magento2#8342]
I am getting 500 internal server error when I am posting wrong parameter in API request. I was trying to create customer through API while posting customer data, I posted groupid instead of group_id and that shows me 500 internal server error.

**Preconditions**
    Magento 2.1.0 CE (or above)

**Steps to reproduce**

1. Open magento_site_url/swagger  documentation (http://demo.cedcommerce.com/magento2/marketplace/swagger)
2. Open tab customerAccountManagementV1 ->Post /V1/customers to create account
3. Post customer data to create customer account with all correct information, instead of passing group_id pass groupid (we can try with any other parameters too).
4. Click on Try it Out! button

 **Result** 
{
  "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-588f3c623a140"
}

 **Expected Result** 

You had passed invalid parameters in your request, groupid doesn't exist in the request parameters. (Something like this)

As i had the access of server so i got my error but there is no process in magento to handle this error and show a correct/useful message, so that API user will be able to get what exact error they made in their API request. #
![1](https://cloud.githubusercontent.com/assets/11978282/22454743/370eb306-e7ae-11e6-9b27-2cddc2d4025d.png)
![2](https://cloud.githubusercontent.com/assets/11978282/22454746/3c9408ee-e7ae-11e6-8a62-8d32e5234a97.png)

**Comment by misha-kotov** [comment]
Totally understand your case. We have some items on the roadmap to improve error handling in APIs, and I'll add the details of your use case to them as well (specifically MAGETWO-64312)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Getting-internal-server-error-when-posting-wrong-parameter-in/idi-p/60555).
