### ISSUE TITLE
SM coundownslider is not displaying in magento2.1.3 (SM Topshop Theme)

### ISSUE THREAD

**Issue by yogeshraghav-dev** [magento/magento2#8345]
On home page after configuring module SM Countdown Slider,it is not showing and visible.
### Preconditions

1. installed magento 2.1.3 than uploaded SM Topshop theme through filezilla.
2. Run command setup:upgrade than setup:di:compile and than setup:static-content:deploy to deploy the theme

### Steps to reproduce

1. after installing theme i went to stores->configuration->SM Topshop-Sm Countdown product slider
2. configured SM Countdown Product slider theme with proper values and saved
3. went to site,refresh the page and "no item to show" is appearing.

### Expected result

1. SMCountdown Slide show should display along with deals timing and slides.
![smcoundown product slider](https://cloud.githubusercontent.com/assets/10353287/22645266/37c54bba-ec8c-11e6-973e-489fbc3d742f.png)
![result](https://cloud.githubusercontent.com/assets/10353287/22645273/42840758-ec8c-11e6-881e-36aae1ed1067.png)
![expected result](https://cloud.githubusercontent.com/assets/10353287/22645290/53401f78-ec8c-11e6-9400-ce3afa1968a2.png)

### Actual result

1. "no item to show" is coming instead.

**Comment by veloraven** [comment]
@hitman3043 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by yogeshraghav-dev** [comment]
i have updated kindly reply.

**Comment by veloraven** [comment]
@hitman3043 as you problem refers to some external module and external theme please contact their developers.
I'm closing this issue as it not an issue in native Magento functionality.
