### ISSUE TITLE
How to display error message from indexer in CLI

### ISSUE THREAD

**Issue by JanPetr** [magento/magento2#8346]
I have an indexer, which needs to be configured first - requires API credentials.

When I run in a reindex command in CLI: `$ bin/magento indexer:reindex my_reindexer_name` and the API credentials are not set, I want to display an error / warning message telling the user to configure his credentials. Currently I'm doing it like this:

```php
if ($wrongCredentials) {
    $errorMessage = 'You need to configure your credentials';

    if (php_sapi_name() === 'cli') {
        throw new \Exception($errorMessage);
    }

    $this->messageManager->addErrorMessage($errorMessage);

    return;
}
```

The issue with this approach is that when the Magento is installed from CLI (via `$ bin/magento setup:install ...`), the Magento tries to reindex the data, the Exception is thrown (of course, API credentials are not set yet) - so the installation crashes. But I don't want to break the install, simply displaying the message is fine.

When I replace `throw new \Exception(...);` by simple `echo $errorMessage` (which works), Magento Marketplace rejects the extension from technical review (bad `echo` placement).

When I remove the CLI condition completely, `$messageManager` won't display the error message in CLI.

So the question is - how correctly display the error message in CLI without breaking the installation? Thanks!

**Comment by JanPetr** [comment]
Addition: 

In the indexer I don't have access to `OutputInterface`. The "reindex" command [doesn't forward it to the indexers](https://github.com/magento/magento2/blob/b1e56ed3b6f13f1ab780d8eddc33fc04cb6ecf75/app/code/Magento/Indexer/Console/Command/IndexerReindexCommand.php#L44-L78). And `OutputInterface` cannot be instantiated via DI either.

**Comment by veloraven** [comment]
@JanPetr thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
