### ISSUE TITLE
WYSIWYG editor issue 

### ISSUE THREAD

**Issue by Sharmilasrini95** [magento/magento2#8347]
When we are save the static block  with internal styles
(<styles>).The styles are  getting delete out.
 And also sometimes  the breaking images are showing in preview instead of original image.

### Preconditions

1. Magento 2.0.10 
2. PHP 7.7

### Steps to reproduce
1. Login in to admin panel
2. Go to content->Block->Create a new block with internal styles
 For Eg:
```
<style type="text/css">
.page-wrapper {
    padding-top: 0px!important;
}
header {
    margin-top: 30px!important;
}
.sticky-top {
    position: fixed;
    width: 100%;
    margin: 0 auto;
    left: 0;
    top: 0;     
}
}
</style>
<div class="sticky-top" style="background: #1B5F84;">
    <div class="top-shipping-link" style="background: #1B5F84;">
        <a class="springSavings" href="#" target="_self"> <img class="middle_ban" src="{{media url="wysiwyg/3.jpg"}}" alt="test" />
        </a>
    </div> 
</div>
```

3.Save the block.
4.Check the preview of the block.
5.Try to edit the styles of that block.

 ### Expected result
1. We can able to edit the styles.
2. We can able to see the preview  without any breaking. 

 ### Actual result
1. Styles are getting delete out after saved the block and when we click the show/hide editor.We can't able to edit the styles.
2. Some times images are preview is getting break.

**Comment by magento-engcom-team** [comment]
@Sharmilasrini95 thank you for your bug report. We cannot reproduce this issue as described. 
Please provide the detailed steps we must follow to reproduce this issue. Screenshots or logs would be helpful, too.

**Comment by magento-engcom-team** [comment]
@Sharmilasrini95, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
