### ISSUE TITLE
Address duplicate issue when we register the user after guest user checkout

### ISSUE THREAD

**Issue by vipinroy** [magento/magento2#8350]
The customer address is duplicating when we create user account after the guest checkout process.

### Preconditions
Version: Magento 2.1.3

### Steps to reproduce
1. Add an item to the cart as a guest user. 
2. Provide user details and press "Checkout" button.
3. Don't forget to check the checkbox "My billing and shipping address are the same" while selecting the payment method.
4. Place the order.
5. It will redirect to success page.
6. Create an account for that user using "Create Account" button from that page .
7. Activate your account.
8. Sign in to your account using the credentials.
9. Again add an item to the cart and checkout.
10. During the time you can see the address is duplicating.

### Expected result
It will show only one address because I entered a single address and checked that address should use as both shipping and billing address.

### Actual result
But here the address is showing two times.

![issue](https://cloud.githubusercontent.com/assets/25221671/22466322/c18ef22a-e7e5-11e6-919e-b1525deafcaf.png)

**Comment by vipinroy** [comment]
I think the issue is in **/vendor/magento/module-sales/Model/Order/CustomerManagement.php**
The function **public function create($orderId)** is used to add addresses using the code
$customerData['addresses'][] = $customerAddress;

But here they are not checking the scenario getSameAsBilling().

**Comment by vipinroy** [comment]
Hello, 
Any updates about this issue?

**Comment by KrystynaKabannyk** [comment]
Hello @vipinroy, I've put this issue in the queue for engineering team to investigate.

**Comment by vipinroy** [comment]
Thank you @KrystynaKabannyk

**Comment by vipinroy** [comment]
Hello,
Any updates about this issue?

**Comment by veloraven** [comment]
@vipinroy is this issue still actual?
We were not able to reproduce it on ver. 2.1.7.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by sanganb** [comment]
I am facing same issue in storefront - checkout shipping pop up form when we add new address.
![image](https://user-images.githubusercontent.com/73931635/109201220-952ec680-77c7-11eb-96ec-b1a5325e1d2d.png)

when we add new address in checkout shipping form which address already exist is creating new address rather than not allowing

**Comment by sanganb** [comment]
@vipinroy  @veloraven @tristanisginger

**Comment by Satishshaw97** [comment]
hi facing the same issue, is there any update on this fix?
