### ISSUE TITLE
Reviews summary not showing in Products List widget

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#8352]
Working in Magento 2.1.3, the Product List Widget does not show the review summary.

**Comment by veloraven** [comment]
@henk-hypershop  thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by henk-hypershop** [comment]
Has already been resolved. Seemed to be a bug in the template Luma Theme.

**Comment by veloraven** [comment]
@henk-hypershop thank you for your feedback.
I'm closing this issue then.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
