### ISSUE TITLE
Copy of checkout_cart_index.xml from vendor to theme stops tax working on cart page

### ISSUE THREAD

**Issue by thelettuce** [magento/magento2#8357]
### Preconditions

1.  Magento 2.1.3
2.  Standard install
3. have sample data or at least one product in the system
4. Stores -> Configuration -> Sales -> Tax. Price Display and Shopping Cart display all options set to Including & Excluding Tax + turn on Include Tax in Summary + Full Tax Summary.

### Steps to reproduce

1. Create a basic test theme(or use your own) - only need composer.json, registration.php and theme.xml
2. Activate theme and switch to it on frontend.
3. Add item to shopping cart
4. Go to /checkout/cart - see the tax details
5. Create folder app/design/frontend/Test/testing/Magento_Checkout/layout
6. Copy vendor/magento/module-checkout/view/frontend/layout/checkout_cart_index.xml to app/design/frontend/Test/testing/Magento_Checkout/layout 
7. delete pub/static files and clear cache
8. reload cart page /checkout/cart

### Expected result

1. Tax details should remain the same

### Actual result

1. Tax details disappear and only excluding tax prices/subtotal is shown. 
Once you delete checkout_cart_index.xml they come back again, yet it still falls back to "vendor/magento/module-checkout/view/frontend/layout/checkout_cart_index.xml" and that displays the tax correctly.

**Comment by magento-engcom-team** [comment]
@thelettuce, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
