### ISSUE TITLE
iOS private mode fails translations

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#8358]
### Preconditions
1. Safari on iOS (test: iOS 9 & iOS 10)
2. Magento Version 2.1.0, PHP 7
3. Using (at least in my case) the de_DE translation package (https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE)
4. Translation Package is in app/i18n/{namespace}/de_DE/de_DE.csv

### Steps to reproduce

1. Open Safari on iPhone
2. Open Tab in "private mode" and go to website
3. Example: Add Products to Cart and go to Checkout

### Expected result

1. Translation is in german or other language

### Actual result

1. Some Buttons and fields are not translated.
2. Button "Next" (for next step)

**Comment by veloraven** [comment]
@ulftietze thank you for your report.
Please provide more information about your translation. Which translation package do you use? How exactly did you install it?
Does this issue also reproduce on other browsers?
Please provide examples of exact buttons and fields which are not translated.

**Comment by ulftietze** [comment]
Updated Description :)

**Comment by ulftietze** [comment]
So i debugged this a little bit, and my result is, that the iOS Safari Browser does not save information in local storage. That the destination, where Magento saves his translation Information.

For example, Chrome or Firefox saves the Information in private mode.

I don't know, if this is really the issue, but maybe this information will help you.

**Comment by xmav** [comment]
@ulftietze Thanks for reporting this issue. 
This issue is already addressed in internal ticket MAGETWO-63635. I’ve added your report on this issue to that ticket.
This one closed as duplicate https://github.com/magento/magento2/issues/7942
