### ISSUE TITLE
2.1.3 Product variations aren't saved

### ISSUE THREAD

**Issue by Koc** [magento/magento2#8359]
### Preconditions

1. PHP 7.0.13
2. Mage 2.1.3

### Steps to reproduce

1. http://youtu.be/XemTHzgiKc4?hd=1

### Expected result

1. New attribute attached to current attribute set, variations saved and created

### Actual result

1. http://youtu.be/XemTHzgiKc4?hd=1

**Comment by veloraven** [comment]
@Koc thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
You can leave links for videos as additional information but please describe steps to reproduce and actual result inside this GitHub issue without external links.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
