### ISSUE TITLE
idea: how to upgrade to new version using github in howto?

### ISSUE THREAD

**Issue by seansan** [magento/magento2#836]
In readme you explain how to install Mage from scratch
https://github.com/magento/magento2/blob/master/README.md

Now that we are testing and new version probably released, can you add a section how to keep it uptodate?

* Do I just clone again? 
* Do I need to re-run dependencies
* Is there a script that I can run from command line that does it for me? (I mean on initial install there is no code to call, but when you have Mage installed we could add a simple script to just upgrade and clone to the latest version and do all the dependency checks in the background)

**Comment by xcomSteveJohnson** [comment]
Fixed here: http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli.html#instgde-install-magento-reinstall
