### ISSUE TITLE
Issue with create account after checkout - Not receiving email about account instructions

### ISSUE THREAD

**Issue by jkarthickeyan** [magento/magento2#8361]
Hi,
   After placing order in as guest, i've been taken to success page where there is a button showing create account. After clicking on the button shows a message "A letter with further instructions will be sent to your email." . But i'm not receiving any mails. Please someone help me in solving this issue.

The magento version i'm using is 2.0.5

Thank you

**Comment by veloraven** [comment]
@jkarthickeyan thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
