### ISSUE TITLE
Installation of extensions using CLI have issues 

### ISSUE THREAD

**Issue by rizwan4317** [magento/magento2#8367]
The following error are showing tho run the commad  : **composer require igorludgero/outofstocklast**

brasilma@a2ls18 [~/public_html]# composer require igorludgero/outofstocklast
Using version ^1.0 for igorludgero/outofstocklast
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for igorludgero/outofstocklast ^1.0 -> satisfiable by igorludgero/outofstocklast[1.0.0].
    - Conclusion: remove magento/framework 100.1.2
    - Conclusion: don't install magento/framework 100.1.2
    - igorludgero/outofstocklast 1.0.0 requires magento/framework ~100.0.4 -> satisfiable by magento/framework[100.0.10, 100.0.11, 100.0.12, 100.0.13, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.2, 100.0.10].
    - Can only install one of: magento/framework[100.1.2, 100.0.11].
    - Can only install one of: magento/framework[100.1.2, 100.0.12].
    - Can only install one of: magento/framework[100.1.2, 100.0.13].
    - Can only install one of: magento/framework[100.1.2, 100.0.4].
    - Can only install one of: magento/framework[100.1.2, 100.0.5].
    - Can only install one of: magento/framework[100.1.2, 100.0.6].
    - Can only install one of: magento/framework[100.1.2, 100.0.7].
    - Can only install one of: magento/framework[100.1.2, 100.0.8].
    - Can only install one of: magento/framework[100.1.2, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.2) -> satisfiable by magento/framework[100.1.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by korostii** [comment]
Clearly, the module you're trying to install defines itself as compatible only with an older version of Magento. The behavior of the composer is to be expected and Magento itself has nothing to do with it. This is clearly not a bug and the discussion, if any, has to be made with the developer of the 3rd-party extension which you're trying to use.

**Comment by rizwan4317** [comment]
thanks..your are right
