### ISSUE TITLE
Issue when installing with Xdebug enabled

### ISSUE THREAD

**Issue by RMcLeod79** [magento/magento2#837]
If you have Xdebug installed with default parameters then installation will fail with the following errror.

`PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/magento2.development-servers.co.uk/htdocs/vendor/composer/ClassLoader.php on line 318`

To get round this increase the max nesting level for Xdebug

`xdebug.max_nesting_level=500`

**Comment by xcomSteveJohnson** [comment]
Fixed: http://devdocs.magento.com/guides/v1.0/install-gde/trouble/tshoot_xdebug.html
