### ISSUE TITLE
Invalid credentials for 'https://repo.magento.com/packages.json', aborting

### ISSUE THREAD

**Issue by WaPoNe** [magento/magento2#8370]
### Preconditions
Magento 2.1.3

### Steps to reproduce

1. Followed the steps http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html
2. Ran the command: php bin/magento module:uninstall _vendorName_moduleName_

### Expected result

1. Uninstalling Magento _vendorName_moduleName_ module via Composer

### Actual result

Removing code from Magento codebase:

Command "remove" failed: <warning>You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug</warning>
Loading composer repositories with package information
    Authentication required (repo.magento.com):
      Username:       Password: 
Removal failed, reverting ./composer.json to its original content.
                                                                          
  [Composer\Downloader\TransportException]                                     
  Invalid credentials for 'https://repo.magento.com/packages.json', aborting.  

remove [--dev] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [packages1] ... [packagesN]

Please disable maintenance mode after you resolved above issues

**Comment by orlangur** [comment]
Are you sure credentials used are correct?

**Comment by WaPoNe** [comment]
Yes, of course.
I've installed it first via composer (and it worked fine).

**Comment by WaPoNe** [comment]
I solved my issue but the bug remains.

I tried "_php bin/magento module:uninstall vendorName_moduleName_" again.
This time I didn't received any error message and the command didn't complete all its tasks:

```
You are about to remove code and/or database tables. Are you sure?[y/N]y
Enabling maintenance mode
You are about to remove a module(s) that might have database data. Remove the database data manually after uninstalling, if desired.
Removing vendorName_moduleName from module registry in database
Removing vendorName_moduleName from module list in deployment configuration
Removing code from Magento codebase:
```
and it remains in this situation for an infinite time so: CTRL+C
then I ran this command: _composer remove vendorName/packageName_

the module was uninstalled and all worked fine.

**Comment by WaPoNe** [comment]
@veloraven: I verified the issue on 2.1.3. version

**Comment by magento-engcom-team** [comment]
@WaPoNe, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
