### ISSUE TITLE
PUT API Call for configurable Product, have problems to update data partially. Only update having all data.

### ISSUE THREAD

**Issue by cristianmalfesi** [magento/magento2#8371]
Summary:
Working with simple products and configurable products with API calls, we have detected that PUT method on simple products for update only one or some fields work (not sending all fields by json), this work good. But when try update with PUT method on configurable product, if we send only one of some fields, the return sometimes crash or lost data.  
For example: If we need only change name and update status, on simple product we can send only these two fields into json, but if we need update configurable product, have to send complete jason including all attribution options and product links, if not, we lost child products and attribute options.

### Preconditions
Magento 2
Version: 2.1.x (tested on 2.1.1 and 2.1.3)
EC2 Instance of AWS Amazon with CentOS
PHP v7.0.10
Mysql 5.6
Also was tested on local environment with Vagrant with CentOS.

### Steps to reproduce
1. Using the Luma demo with a T-shirt products, create on admin panel one configurable product, with combination of 2 colors and 3 sizes, then you will get a configurable product with 6 product childs.
2. Make a PUT product API call where try update only status or name, for update only one or two fields into configurable product, for example:
```
curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer cl6v1mlxnmr4b3mgvx6936lva7nme4pu" -H "Cache-Control: no-cache" -d '{  
   "product":{  
      "sku":"shirt0001",
      "name":"T-shirt changed",
      "price":0,
      "status":2,
      "custom_attributes":[  
         
         {  
            "attribute_code":"description",
            "value":"<p>changed<\/p>"
         }
      ]
   },
   "saveOptions":true
}' "http://www.yourdomain.com/rest/V1/products/shirt0001"
```

### Expected result

1. We wait configurable product with name and status changed in this case, but with all attribute options and childs information on product links

### Actual result

1. We receive a Json with configurable product data updated, but los all information of produc links and attribute options. If we go to admin panel, then we see that product have no childs.

We think that for reduce large times that take every api call to save products is really necessary that we can send PUT product calls with partial data.

**Comment by TwassistantKeith** [comment]
I am also experiencing this issue in Magento 2.1.3.

**Comment by StefanRijnhart** [comment]
cf. https://github.com/magento/magento2/issues/8371

**Comment by magento-engcom-team** [comment]
Hi @chm1975

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@chm1975 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
