### ISSUE TITLE
Cannot change theme

### ISSUE THREAD

**Issue by dhanjugopi** [magento/magento2#8372]
### Preconditions
Version: Magento 2.1.3
PHP : 5.6.19

### Steps to reproduce
1.  Go to  content ->configuration->Default Edit
2.  Try to change the theme to Blank or any custom theme

### Expected result
1.  The theme should be applied

### Actual result
1. Theme not applied. Returns error shown in below screenshot:
![global design content magento admin](https://cloud.githubusercontent.com/assets/2108814/22520895/ea291ad2-e86a-11e6-835e-ebce9ee53cf4.png)

**Comment by Igloczek** [comment]
This might be related to OS. Windows isn't supported and you shouldn't try to run M2 on them.

Official system requirments - http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html

**Comment by dhanjugopi** [comment]
Same issue in 2.1.4 too

**Comment by orlangur** [comment]
@dhanjugopi still on WIndows OS? This OS is not supported and thus Windows-only bugs are unlikely to be fixed.

**Comment by magento-engcom-team** [comment]
@dhanjugopi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
