### ISSUE TITLE
Cannot access setup after install - redirecting to /setup/index.php/session/unlogin

### ISSUE THREAD

**Issue by t7m** [magento/magento2#8374]
### Preconditions

1. Magento 2.1.3
2. PHP 7, nginx

### Steps to reproduce

1. Trying to access http://localhost/setup/

### Expected result

1. I see a page

### Actual result

1. I am redirected to http://localhost/setup/index.php/session/unlogin

I've narrowed it down to **module-backend/Model/Auth/Session.php** getting NULL values for user and acl as shown below. But that's not very helpful to me.

    public function isAllowed($resource, $privilege = null)
    {
        $user = $this->getUser();
        $acl = $this->getAcl();

I can find dozens of similar issues where users are redirected to /setup/index.php/session/unlogin . I can find no solutions. What else can I check?

**Comment by miakusha** [comment]
Hi @t7m , try to use http://127.0.0.1/setup/ instead http://localhost/setup/

**Comment by t7m** [comment]
Obviously I have tried this. Nope.

**Comment by magento-engcom-team** [comment]
@t7m, thank you for your report.
We've created internal ticket(s) MAGETWO-75581 to track progress on the issue.

**Comment by t7m** [comment]
Wow! Seven and a half months later!

This is why we are not using your horrible product.

**Comment by okorshenko** [comment]
Hi @t7m feel free to submit a pull request with the fix to make the product better for you 👍  and for all other users of the platform.

**Comment by t7m** [comment]
So a reply nine months later is "you fix it."

Magento is a joke. I'm muting this thread. We created something from scratch that works much, much better.

**Comment by magento-engcom-team** [comment]
@t7m, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
