### ISSUE TITLE
Setting price of Customizable Option causes fatal error on frontend

### ISSUE THREAD

**Issue by jeffpreussner** [magento/magento2#8376]
### Preconditions

1. PHP 5.6.21 | OSX10.11.6 | MySQL 5.7.13 | Magento v2.1.3 EE installed using composer

### Steps to reproduce

1. Add Customizable Option and a value with a price to a product.
2. Save, flush cache and visit product page in browser
3. Notice fatal error

### Expected result

1. You can set price for custom option values and it will display correctly on the frontend. 

### Actual result

1. [Screenshot, logs]

( ! ) Fatal error: Uncaught Error: Call to a member function getPriceInfo() on null in /mysite/vendor/magento/module-catalog/Block/Product/View/Options/AbstractOptions.php on line 140

( ! ) Error: Call to a member function getPriceInfo() on null in /mysite/vendor/magento/module-catalog/Block/Product/View/Options/AbstractOptions.php on line 140

When you don't set a price in the value for the option this error does not happen.

**Comment by veloraven** [comment]
@jeffpreussner thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
