### ISSUE TITLE
 When we update product in Magento EE 2.1.3, product updated time not getting updated

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#8379]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0.14 & MySQL 5.7.16

### Steps to reproduce

1. Go to Magento admin
2. Select any product
3. Update any product information other than SKU

### Expected result

1. updated_at field in catalog_product_entity table should be modified

### Actual result

1. updated_at field in catalog_product_entity table not modified if we save product without updating SKU. If we save product by updating SKU, then updated_at field is updating.

**Comment by veloraven** [comment]
@i95devdivya thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by indiebytes** [comment]
It sounds like it's the same issue as #6683.
