### ISSUE TITLE
Catalog Price Rules not applying in Magento EE 2.1.3

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#8380]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0.14 & MySQL 5.7.16

### Steps to reproduce

1. Set any catalog price rule for any product or any category in Magento admin

### Expected result

1. Discount Price should be displayed in Magento frontend catalog 

### Actual result

1. Discount Price not displaying, instead of discount price original price is displaying.

**Comment by veloraven** [comment]
@i95devdivya thank you for your feedback.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
