### ISSUE TITLE
Custom exception message thrown in sales_order_place_before observer not showing

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#8381]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0.14 & MySQL 5.7.16

### Steps to reproduce

1. Use sales_order_place_before event in custom module
2. Throw any exception with custom message for that observer
3. A pop-up will be displayed with message like "An error occurred on the server. Please try to place the order again."

### Expected result

1. A pop-up should displayed with custom message which is provided in sales_order_place_before  observer

### Actual result

1. A pop-up will be displayed with message like "An error occurred on the server. Please try to place the order again."

**Comment by magento-engcom-team** [comment]
@i95devdivya, thank you for your report.
We've created internal ticket(s) MAGETWO-81150 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@i95devdivya, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
