### ISSUE TITLE
Magento incompatible with google api because of fixed monolog version

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#8382]
### Preconditions

1. Magento 2.x

### Steps to reproduce
1. Install Magento 2 (any version)
2. Install google api client with: composer require google/apiclient:^2.1

### Expected result
1. google api client should be installed

### Actual result
1. google api client needs monolog 1.17, but magento has it fixed on 1.60.0
![screen shot 2017-02-02 at 09 59 11](https://cloud.githubusercontent.com/assets/17834386/22542884/4b290fa4-e92e-11e6-997a-c749c9937ad5.png)

Please update the fixed monolog version to at least ^1.17 in https://github.com/magento/magento2/blob/develop/composer.json#L40

Related issue: https://github.com/magento/magento2/issues/7744

**Comment by PascalBrouwers** [comment]
Added a Pull Request for the change: https://github.com/magento/magento2/pull/8383

**Comment by okorshenko** [comment]
@PascalBrouwers thank you for contribution. Your Pull Request has been merged to develop branch. Can we close this issue now?

**Comment by PascalBrouwers** [comment]
Of course. I'll close it then.
