### ISSUE TITLE
Magento Product Grid in backend shows values for default store view instead of default

### ISSUE THREAD

**Issue by JangriX** [magento/magento2#8384]
### Preconditions
1.  Magento 2.1.2, 2.1.3

### Steps to reproduce
1.  Create 1 or more store view under Main Website Store, so that there are at least 2
2.  Set the new one as default in Main Website Store settings.
3.  Go to products grid, and open a product.
4.  Set scope to the store view set as default in step 2.
5.  Change a product attribute such as name in the store view scope.
6.  Go to product grid.

### Expected result
1.  Attribute value from default scope shows

### Actual result
1. Attribute value from the store view from step 2 shows.

**Comment by KrystynaKabannyk** [comment]
Hello @Jangri, could you please provide the details with concrete names?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by parekhreena** [comment]
@KrystynaKabannyk 
This issue persists in 2.3.x and needs to be reopened. Asking for concrete attribute values is just a way to delay the solution. You can use "abc" and "def" for example purpose. This issue is very much evident and problematic when you have different language storeviews.
