### ISSUE TITLE
Unable to delete an attribute on a product through the API

### ISSUE THREAD

**Issue by CatherineLearmonth** [magento/magento2#8385]
### Preconditions

1. Magento 2.1.2 or Magento 2.2.0-dev.
2. Use the PHP api rather than the json one.

### Steps to reproduce

1. A product has a set of custom attributes on it.
2. I want to remove one or more of those custom attributes from the product through the PHP API. I set the attribute I want to remove to have a null value. 
3. I call method saveAttribute in magento/module-eav/Model/Entity/AbstractEntity.php - which inserts/updates/removes an attribute from an object. When an attribute has a null value, this method should remove it. 

### Expected result

1. When a product attribute has a null value, the saveAttribute method should remove it from the product. 

### Actual result

1. The attribute remains on the product -  the update attribute code is called for an attribute with a null value, and the delete code never seems to be called. 

Note: I have got round this issue by creating a method that only deletes an attribute from a product in my own app/code.

**Comment by keevitaja** [comment]
@CatherineLearmonth could you share the code how did you remove the attribute?

**Comment by CatherineLearmonth** [comment]
Sure @keevitaja:

    `/**
	 *
	 * Delete Attribute method
	 * This method deletes an attribute on a product
	 * I couldn't get this to happen through the API so had to do a direct table
	 * update.
	 *
	 * @param \Magento\Framework\DataObject $object
	 * @param AbstractAttribute $attribute
	 */
	public function deleteAttribute(\Magento\Framework\DataObject $object, $attribute)
	{
		$backend = $attribute->getBackend();
		$table = $backend->getTable();
		$entity = $attribute->getEntity();
		$row = $this->getAttributeRow($entity, $object, $attribute);

		$whereArr = [];
		foreach ($row as $field => $value) {
			$whereArr[] = $this->connection->quoteInto($field . '=?', $value);
		}
		$where = implode(' AND ', $whereArr);

		$this->connection->beginTransaction();

		try {
			$select = $this->connection->select()->from($table, 'value_id')->where($where);
			$this->connection->delete($table, $where);
			$this->connection->commit();
		} catch (\Exception $e) {
			$this->connection->rollback();
		}
	}``

**Comment by keevitaja** [comment]
Thank you so much!

I needed to delete the special price attribute. 

```
            $product = $this->product->get($sku);
            $product->setSpecialPrice(null);
            $product->getResource()->saveAttribute($product, 'special_price');
```

`$this->product` is `Magento\Catalog\Api\ProductRepositoryInterface`

**Comment by CatherineLearmonth** [comment]
@keevitaja 
Before calling the method, you will need to do the below code, then pass the $object and $attribute as parameters to the method. Good luck!
` $object = $product->getResource();
$attribute = $object->getAttribute('special_price');`

**Comment by magento-engcom-team** [comment]
Hi @CatherineLearmonth 
The subject calls "Unable to delete an attribute on a product through the API", but API does not use in 
steps description.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by CatherineLearmonth** [comment]
I've updated the issue pre-conditions to have: 
Use the PHP api rather than the json one.

Step 2 of the steps to reproduce references the API as follows:
I want to remove one or more of those custom attributes from the product through the PHP API. I set the attribute I want to remove to have a null value.
Step 3 indicates the method in the API that I am calling. (saveAttribute) 

If there is more information that you need, please tell me exactly what you require, thanks.

**Comment by magento-engcom-team** [comment]
@CatherineLearmonth
Magento shall provide [API](http://devdocs.magento.com/swagger/index_21.html).
Method "saveAttribute" is not present in that list.
Which exactly API method do you use?

**Comment by CatherineLearmonth** [comment]
You can call saveAttribute on a Magento object. 
    
1) Create or get an existing Magento product using \Magento\Catalog\Api\ProductRepositoryInterface. See (https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Api/ProductRepositoryInterface.php) for details of the code - this is what I mean by the PHP API, and it is provided by Magento as an alternative to the JSON API which you have linked to.  Some Magento documentation is available here: http://devdocs.magento.com/guides/v2.2/extension-dev-guide/bk-extension-dev-guide.html

2) Try to delete an attribute on that product by setting the attribute value to null and then calling method saveAttribute. For example, a product has an attribute of special_price - set that to null and then call save attribute on it: 
  
    $product->setSpecialPrice(null);
     $product->getResource()->saveAttribute($product, 'special_price');
     
The saveAttribute method lives in vendor/magento/module/eav/Model/Entity/AbstractEntity.php 
If you look at the code, you would expect an attribute with a null value to be removed using this method, but it is not removed.

**Comment by magento-engcom-team** [comment]
Hi @CatherineLearmonth
I understand your issue.
I try to reproduce it in 2.1.9 and 2.2.0 (Revision number: 07465f8ce879ff0bd0ba72a662c9e2473e49afe4), but attribute was saved correctly.

My steps are:
1. Create simple product With id =1 and Special price = 10
2. Execute: 
```
/** @var ProductRepositoryInterface $productFactory */
$productRepository = ObjectManager::getInstance()->get(ProductRepositoryInterface::class);
$testProduct = $productRepository->getById(1);
$testProduct->setSpecialPrice(null);
$testProduct->getResource()->saveAttribute($testProduct, 'special_price');
```
After this action the field Special price is empty.

Please update you Magento 2.2.0 to latest version and try reproduce it.

**Comment by magento-engcom-team** [comment]
@CatherineLearmonth, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
