### ISSUE TITLE
Customer addresses not saving properly in Magento EE 2.1.3

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#8386]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0.14 & MySQL 5.7.16

### Steps to reproduce

1. Create customer with two addresses in which one is default billing and one more is default shipping from Magento admin
2. Save the Customer
3. Now open the same customer and create new address, then save the customer

### Expected result

1. Customer should have 3 addresses i.e., default billing, default shipping and addition address.

### Actual result

1. Customer have 3 addresses but no address marked as default billing or default shipping. For more information please check below screen-cast
https://www.screencast.com/t/SlroDGqVRbrz

**Comment by veloraven** [comment]
@i95devdivya thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
