### ISSUE TITLE
Magento2 un-expected behaviour for configurable product price when cataloge rule applied

### ISSUE THREAD

**Issue by varun-jyothi** [magento/magento2#8387]
### Preconditions
I am Using Magento 2.1.3 community edition.Here is the issue I am facing

### Steps to reproduce

Step 1 : Created a new customer group and assign one customer to that group

Step 2 : Created a catalog rule that will give 20% discount when choose a "Green" color

Step 3 : Logged In as a customer and just view "Hero Hoodie"

Step 4 : Now it is showing $43.20 as price (Actual price is $54.00) - Perfect

![image1](https://cloud.githubusercontent.com/assets/25455652/22544289/29b3c9a0-e95a-11e6-8e7a-ea6424de14ee.png)

Step 5 : Click on the "Green" color, it will show the price as $54.00 (It must show $43.20)

![image2](https://cloud.githubusercontent.com/assets/25455652/22544278/1eb11954-e95a-11e6-876e-bc134e2605aa.png)

Step 6 : Click on add to cart and now it is showing $43.20

![image3](https://cloud.githubusercontent.com/assets/25455652/22544300/35ad3dea-e95a-11e6-8aea-4841200914cf.png)

### Expected result
When Click on "Green", it must show the price as $43.20

### Actual result
Instead of showing $43.20, it is showing the actual price $54.00

**Comment by magento-engcom-team** [comment]
@varun-jyothi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
