### ISSUE TITLE
magento 2.1.2 component manager is stop on please wait.

### ISSUE THREAD

**Issue by rizwan4317** [magento/magento2#8390]
component manager is working fine but when i install a module https://github.com/emizentech/magento2-countdown  its on  click component manager its going to stop on please wait..
https://screenshot.net/mgqq8c6
now i remove the remove module but problem is still pending?

**Comment by markdh1** [comment]
@rizwan4317 Cleared all caches? Reset perms on folders? If not cd into your install directory and run:
find pub/ -type f ! -perm 0644 -exec chmod 0644 {} \;
find pub/ -type d ! -perm 0755 -exec chmod 0755 {} \;

Clean cache, clean browser cache and log back in. Should load for you then.

**Comment by veloraven** [comment]
@rizwan4317 thank you for your feedback.
    The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

If you want to report an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by rizwan4317** [comment]
@veloraven thanks for your guidance ..
