### ISSUE TITLE
State that Grouped products cannot have catalog price rules applied to theme

### ISSUE THREAD

**Issue by surfer190** [magento/magento2#8391]
**User Guide Documentation Issue**

In the documentation of the [catalog price rules](http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-catalog.html?Highlight=rule) I feel it would be beneficial to point out that grouped products cannot have a discount applied to them.

#### Preconditions:

1. You have a working browser

#### Steps to reproduce:

1. Go to [Catalog Price rules part of documentation](http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-catalog.html)

#### Expected result

 Additional and crucial information regarding catalog price rules is in the documentation, such as specified below.

```
Catalog price rules can be applied to a parent configurable product and the child simple product variations. With smart usage of the priority and `discarding subsequent` rules, you can apply catalog price rules to both, just the simple product or just the parent configurable.

On bundled products a catalog price discount can only be applied to sub products or child products.
It will then reflect in the price of the main product. Ensure the sub products are not visible individually if you only want the discount to apply within bundles.
The same method can be used for grouped products, again ensuring that the product is not visible individually if it is not discounted without the bundle. However in a grouped products there is only a requirement to take a single product so it makes no sense to add a catalog price rule in this case.

In that case a shopping cart price rule is needed.

Catalog price rules can only be applied to the following product types (and results show in the frontend):
* Simple
* Downloadable
* Virtual

```

#### Actual result

No information about the types of products that catalog price rules can be given to and how they work on different product types is specified.

**Comment by veloraven** [comment]
@surfer190 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by surfer190** [comment]
@veloraven Updated

**Comment by magento-engcom-team** [comment]
@surfer190, thank you for your report.
We've created internal ticket(s) MAGETWO-82722 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@surfer190, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
