### ISSUE TITLE
Initial loading of the related-products sorting fails in Edge-Mode

### ISSUE THREAD

**Issue by Abezethibou** [magento/magento2#8392]
### Preconditions

1. Open and login to Magento 2 (2.1.2) Backend with Internet Explorer 10 on Windows 7
2. Edge-Mode has to be activated

### Steps to reproduce

1. Open Magento Backend
2. Click on "Products" in the left Sidenavigation and click on "Catalog" on the flyout
3. Select a product with related articles and click on "Edit"
4. Click on the row "Related Products, Up-Sells, and Cross-Sells"
5. Order the related products (avoid that the IDs are ordered chronological like 1,2,3,4; it should be like 3,1,2,4) and "save and close"
6. Open the edited product again and click on the row "Related Products, Up-Sells, and Cross-Sells" again

### Expected result

1. The related products should be listed like ordered in the 5th step (3,1,2,4)

### Actual result

1. The products are ordered based on the ID (1,2,3,4) and when you move one product some lazy loading script error appears and the products are ordered again like in step 5 (3,1,2,4)

Also the loading time and the time after moving a product to another order position is very very long.

**Comment by okorshenko** [comment]
Closing this issue. Fixed in https://github.com/magento/magento2/pull/8467 for develop branch.
@Abezethibou thank you for reporting this issue and following best practices! Description of this issue is a great example of clear preconditions, steps to reproduce and expected/actual results! Thank you!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64403
