### ISSUE TITLE
Is ISO-636 or ISO-639 needed for deploy static content?

### ISSUE THREAD

**Issue by tzsolti** [magento/magento2#8398]
When I type in the CLI

php magento help setup:static-content:deploy

I get a list of arguments and options.
The language argument has a description like:
"Space-separated list of ISO-636 language codes for which to output static view files."

I've been searching for ISO-636, but couldn't find any useful information regarding language codes. But I've found the ISO-639 which is really all about language codes (and it has many versions, ISO-639-1, ISO-639-2, etc.). I'd like to know which one is the correct standard, maybe someone could give me some example language codes. 

### Preconditions
Magento CE 2.1.3 (downloaded zip from Magento website), PHP 7.0.13

### Steps to reproduce
1. open CLI
2. navigate to magento root / bin
3. php magento help setup:static-content:deploy

### Expected result
1. language argument's description: "Space-separated list of ISO-639 language codes for which to output static view files."

### Actual result
1. language argument's description: "Space-separated list of ISO-636 language codes for which to output static view files."

**Comment by hostep** [comment]
I'd say it's a combination of the ISO-639-1 and ISO-3166-2 standards, joined together with a `_` in the middle.
But there are also these wierd Chinese things, like `zh_Hans_CN`, `zh_Hant_HK`, `zh_Hant_TW`, ...
So I don't think Magento use an official standard.

But to answer your question, you can see the list of supported "codes", when you run this command:
`php bin/magento info:language:list`

And you are definitely correct, that ISO-636 is very incorrect.

**Comment by magento-engcom-team** [comment]
@tzsolti, thank you for your report.
We've created internal ticket(s) MAGETWO-83725 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tzsolti, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
