### ISSUE TITLE
command setup/upgrade not working

### ISSUE THREAD

**Issue by malikt** [magento/magento2#8401]
The CLI commands were working fine till the last time i used, but today when i try to run
`php bin/magento setup:upgrade`
It is not working, i am receiving an exception instead.

### Preconditions
1. PHP 7.0.13
2. MySQL 5.6.34
3. Magento V 2.1.2
4. nginx

### Steps to reproduce

1. ran the cli command `php bin/magento setup:upgrade`

### Expected result

1. Should update the modules.

### Actual result

1. `Fatal error:  Uncaught TypeError: Argument 3 passed to Magento\Framework\Model\ResourceModel\Type\Db\Pdo\Mysql::__construct() must be an instance of Magento\Framework\DB\SelectFactory, array given, called in /public_html/setup/src/Magento/Setup/Module/ConnectionFactory.php on line 36 and defined in /public_html/vendor/magento/framework/Model/ResourceModel/Type/Db/Pdo/Mysql.php:44
Stack trace:
#0 /public_html/setup/src/Magento/Setup/Module/ConnectionFactory.php(36): Magento\Framework\Model\ResourceModel\Type\Db\Pdo\Mysql->__construct(Object(Magento\Framework\Stdlib\StringUtils), Object(Magento\Framework\Stdlib\DateTime), Array)
#1 /public_html/vendor/magento/framework/App/ResourceConnection.php(113): Magento\Setup\Module\ConnectionFactory->create(Array)
#2 /public_html/vendor/magento/framework/App/ResourceConnection.php(92): Magento\Framework\App\ResourceConnection->getConnectionByName('default')
#3 /public_html/vendor/magento/framework/Module/Set in /public_html/vendor/magento/framework/Model/ResourceModel/Type/Db/Pdo/Mysql.php on line 44`

**Comment by digitalpianism** [comment]
Most of the "Argument passed" errors in M2 are caused by the `var/generation` folder not being up to date. Did you try to flush this folder ?

**Comment by malikt** [comment]
I tried that number of times, its not working.

**Comment by malikt** [comment]
any suggestions?

**Comment by romeof1980** [comment]
hi @malikt ,
you could try to remove all content from var/di and var/generation

cheers

**Comment by malikt** [comment]
hi @romeof1980 ,
I am in development mode and there is no var/di however, i have deleted  var/generation number of times but the error persists, I even deleted every folder from var and even static files from pub, but no joy.
thanks,

**Comment by romeof1980** [comment]
hi @malikt ,
are you trying to run `php bin/magento setup:upgrade` because you've just installed/uploaded a new module?

**Comment by malikt** [comment]
hi
i haven't installed new module, but i will soon install new modules. so at least this command should work. I can't even take the risk to upgrade magento version, the whole site will be down until this command runs.
thanks,

**Comment by romeof1980** [comment]
hi @malikt ,
I see the error `Argument 3 passed to Magento\Framework\Model\ResourceModel\Type\Db\Pdo\Mysql::__construct()`

for what I know that argument is the dtb password ( `string $password` )
have a look here:
[http://php.net/manual/it/pdo.construct.php]

are you sure you set user, pw and dtb name correctly?

**Comment by malikt** [comment]
Hi,
The site is working fine, only this command has issues, if this error has to do with wrong user/pass etc, how come the rest of site is working fine. however, where exactly i should check the user/pass other than app/etc/env.php?

**Comment by romeof1980** [comment]
never mind, that's not the problem then. Is it a fresh install?

**Comment by malikt** [comment]
it was fresh install with 2.0.5, then upgraded to 2.1.2, now i wanted to upgrade to 2.1.4 but cant do until this command fixes. 
thanks,

**Comment by romeof1980** [comment]
How did you upgraded? which cmd did you run? You could also run "composer update" to try to resolve dependencies issues. Make a backup prior to do that

---- On Tue, 14 Feb 2017 05:41:18 +0100 notifications@github.com wrote ----

it was fresh install with 2.0.5, then upgraded to 2.1.2, now i wanted to upgrade to 2.1.4 but cant do until this command fixes.
thanks,

**Comment by malikt** [comment]
i used the command "composer update" after updating two lines where version mentioned in composer.json
which folders are required to for the backup?

**Comment by romeof1980** [comment]
Which result did you get? Did it run correctly? Modifying composer.json can lead to problem if not done correctly. 
Please consider to contact your hosting provider and ask they about the backup documentation: you should know how to perform backups and test how to restore prior to do upgrade operations that can brake your site

---- On Tue, 14 Feb 2017 08:14:54 +0100 notifications@github.com wrote ----

i used the command "composer update" after updating two lines where version mentioned in composer.json
which folders are required to for the backup?

**Comment by malikt** [comment]
yes it went smooth, the site kept working for weeks, I used the upgrade command number of time. its just since i posted the issue, the command stopped working.
thanks for suggestions, i will check with the hosting for backups of code and database both.
Can you please share for the record, whats the best method to upgrade to latest version

thanks for your time.

**Comment by romeof1980** [comment]
Hi @Malik,
have a look here: http://devdocs.magento.com/guides/v2.0/comp-mgr/bk-compman-upgrade-guide.html

I'd advise to solve the issue you already have got before upgrading

---- On Tue, 14 Feb 2017 08:25:55 +0100 notifications@github.com wrote ----

yes it went smooth, the site kept working for weeks, I used the upgrade command number of time. its just since i posted the issue, the command stopped working.
thanks for suggestions, i will check with the hosting for backups of code and database both.
Can you please share for the record, whats the best method to upgrade to latest version

thanks for your time.

**Comment by malikt** [comment]
Hi,
Thank you.
This may take a while to take backups and update, you can close the ticket and i will reopen in case the issue persists,
thanks again for your time.

**Comment by magento-engcom-team** [comment]
@malikt, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by suguna-e** [comment]
how to integrate the new theme for magento?
