### ISSUE TITLE
cart subtotal_unformated variable is undefined

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#8403]
Before Magento 2.1.3 js components you can get a numeric amount of the cart subtotal by getting `subtotal_unformated`. Now this variable is undefined.

### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Create a component that uses `'Magento_Customer/js/customer-data'`
2. Add something to cart
3. log customerdata.get('cart')().subtotal_unformated 

### Expected result

1. variable should contain cart subtotal float value.

### Actual result

1. variable is undefined

**Comment by magento-engcom-team** [comment]
@giacmir , thank you for your report.
Unfortunately, I cannot get a numeric amount of the cart subtotal by getting subtotal_unformated in earlier versions. Can You please provide link for code, where it was used in earlier versions?
