### ISSUE TITLE
Sales rule conditions do not work with product variant level attributes

### ISSUE THREAD

**Issue by torreytsui** [magento/magento2#8407]
### Description
Set a catalog price rule with a condition that look up the product attribute, it does not work with variants from configurable product which is not the default variant.

### Preconditions

1. You have at least one configurable product with two simple products as variants

    ![awesome-default-variant](https://cloud.githubusercontent.com/assets/945819/22598181/83df4686-ea2a-11e6-867e-0fd108da4727.png)
    ![awesome-variant](https://cloud.githubusercontent.com/assets/945819/22598180/83dbf742-ea2a-11e6-8947-48fa1503e15e.png)

    Set the variants' visibility to `Note Visible Individually`

    Set the configurable product's visibility to `Catalog, Search`

1. Set one variant to price = 100; set the other to price = 200

    Setting different prices just to make the default variant obvious that the lowest price variant will become the default variant

    `Awesome Default Variant` price = 100

    `Awesome Variant` price = 200

1. Create a price rule to use a product attribute as action condition

    For example, use the product `name` as the product attribute condition

      - Update `name` attribute `Use for Promo Rule Conditions` to Yes

      - Set action condition to `Name` is `Awesome Variant`
        
        ![name-is-awesome](https://cloud.githubusercontent.com/assets/945819/22599110/8e51e530-ea2d-11e6-8f84-bcde7bf8ea1d.png)

      - Set action to the rule for example with `Buy X get Y free (discount amount is Y)` set buy 2 get $10 off

      - Activate the rule

1. Reindex

    `php bin/magento indexer:reindex salesrule_rule catalog_product_flat catalog_product_price`

### Steps to reproduce

1. Go to the PDP of the configurable product
1. Add 2 `Awesome Variant` to basket
1. Go to basket page

### Expected result

The sale rule should apply and there should be $10 discount off on the totals

### Actual result

The sale rule does not apply

**Comment by torreytsui** [comment]
The vanilla did not consider a quote item which added from a configurable product needs to resolve the product data from its quantity options. As a result, only default variant, which is populated to the parent quote item, can pass the condition set by rule

# Workaround

This workaround only tested with configurable and simple products. It assumes `count($model->getQtyOptions())` will always equal to 1.

Quote item created from configurable product will have only one quantity option. It is not sure if bundle or group products will have more than one quantity option

```diff
--- vendor/magento/module-sales-rule/Model/Rule/Condition/Product.php	2017-02-03 15:41:12.000000000 +0000
+++ vendor/magento/module-sales-rule/Model/Rule/Condition/Product-after.php	2017-02-03 15:40:22.000000000 +0000
@@ -1,54 +1,59 @@
 <?php
 /**
  * Copyright © 2016 Magento. All rights reserved.
  * See COPYING.txt for license details.
  */
 namespace Magento\SalesRule\Model\Rule\Condition;
 
 /**
  * Product rule condition data model
  *
  * @author Magento Core Team <core@magentocommerce.com>
  */
 class Product extends \Magento\Rule\Model\Condition\Product\AbstractProduct
 {
     /**
      * Add special attributes
      *
      * @param array $attributes
      * @return void
      */
     protected function _addSpecialAttributes(array &$attributes)
     {
         parent::_addSpecialAttributes($attributes);
         $attributes['quote_item_qty'] = __('Quantity in cart');
         $attributes['quote_item_price'] = __('Price in cart');
         $attributes['quote_item_row_total'] = __('Row total in cart');
     }
 
     /**
      * Validate Product Rule Condition
      *
      * @param \Magento\Framework\Model\AbstractModel $model
      * @return bool
      */
     public function validate(\Magento\Framework\Model\AbstractModel $model)
     {
         //@todo reimplement this method when is fixed MAGETWO-5713
         /** @var \Magento\Catalog\Model\Product $product */
-        $product = $model->getProduct();
-        if (!$product instanceof \Magento\Catalog\Model\Product) {
-            $product = $this->productRepository->getById($model->getProductId());
+        if (($options = $model->getQtyOptions()) && !empty($options)) {
+            // Resolve selected variant from configurable product
+            $product = reset($options)->getProduct();
+        } else {
+            $product = $model->getProduct();
+            if (!$product instanceof \Magento\Catalog\Model\Product) {
+                $product = $this->productRepository->getById($model->getProductId());
+            }
         }
 
         $product->setQuoteItemQty(
             $model->getQty()
         )->setQuoteItemPrice(
             $model->getPrice() // possible bug: need to use $model->getBasePrice()
         )->setQuoteItemRowTotal(
             $model->getBaseRowTotal()
         );
 
         return parent::validate($product);
     }
 }

```

**Comment by vityakopin** [comment]
Hi @torreytsui ! We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify  which version of Magento you are running.

**Comment by torreytsui** [comment]
@vityakopin 

It was EE 2.1.3. Did you manage to get the expected result or the reported incorrect result?

**Comment by vityakopin** [comment]
If this issue is actual for Enterprise Edition only, please address it to Magento Support. My magento is CE 2.1.3. I have created Cart Price Rule with action condition to Name, action is set Buy X get Y free(discount amount is Y). Discount amount configuration is 1 Discount Qty Step (Buy X) is 1. When we put into cart 2 items of one product (f.e. conf1-blue) we have discount 50% (Discount amount is price second product and discount qty step is qty of first product). If i put into cart product with another name attribute (f.e. conf1-red) discount is not applied.

**Comment by torreytsui** [comment]
Hi @vityakopin 

Were the products under test configurable or simple? To trigger the issue, we need the condition triggered by the SIMPLE product's attribute (e.g., name). But add the CONFIGURABLE product which configured to the target simple product to the basket.

To distinguish the simple from configurable, we need them in different name and the name of the configurable must not pass the rule condition.

**Comment by vityakopin** [comment]
Yes, rule condition was on simple product, with name RED. Configurable product name was Test with configurations RED and BLUE. Cart Price Rule configuration is on attached screen. When to cart added 2 configurable product with option "blue" discount wasn't applied. When to cart added 2 configurable product with option "red" discount was applied 50% of products cost.

**Comment by ktruehl** [comment]
Same problem here. On Magento CE 2.1.7.

**Comment by torreytsui** [comment]
@vityakopin

Look like in your test, Red is resolved as the default variant. Please try to set up a different discount for Blue. If Blue's discount cannot apply, the bug is triggered

**Comment by magento-engcom-team** [comment]
@torreytsui, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
