### ISSUE TITLE
Configuration on website level not taking in account

### ISSUE THREAD

**Issue by mpasquin** [magento/magento2#8408]
### Preconditions

1. Magento CE 2.1.3
2. Magento EE 2.1.3

### Steps to reproduce

Commun setting:
1. Set a second website named "My new website" with one or more views

Case 1:
1. Go to Store > Configuration > General > Web > Base URLs
2. Change scope to the website "My new website"
3. Set the URL http://www.mynewurl.com/ and save

Case 2:
1. Go to Store > Configuration > Catalog > Catalog > Price
2. Set Catalog Price Scope to website and save
3. Go to Store > Configuration > General > Currency Setup > Currency Options
4. On the default config scope set Base Currency, Default Display Currency and Allowed Currencies to US Dollar and save.
5. Change scope to "My new website" website
6. Set Base Currency, Default Display Currency and Allowed Currencies to Euro and save.

### Expected result

Case 1:
1. All store views URL which depends on "My new website" are http://www.mynewurl.com/ 

Case 2:
1. In product's configuration, on one of "My new website" scope, price is displayed on Euro.
2. In front, the price setting in back-office is displayed without conversion.

### Actual result

Case 1:
1. All store views URL which depends on "My new website" are URL defined on the default config scope.

Case 2:
1. In product's configuration, the currency is always display in US Dollar regardless the configuration in website scope.
2. Price setting on "My new website" is converted on front.

**Comment by korostii** [comment]
Case 1, at least. seems to be a duplicate of #7815 (see a workaround [here](https://github.com/magento/magento2/issues/7840#issuecomment-268313989) ).
Not sure if the other part is related though, I would recommend applying the fix and then re-testing if other bug disappears as well. Good luck!

**Comment by mpasquin** [comment]
Thank you @korostii. I tried @alexpoletaev's solution describe in #7840 but it doesn't work for me...

**Comment by mpasquin** [comment]
It's seem that the new release 2.1.4 solve the problem.
