### ISSUE TITLE
Translation integration (suggestion)

### ISSUE THREAD

**Issue by nyov** [magento/magento2#841]
Translation integration is hard, since usually oneself isn't that multilingual to ascertain if a certain localization is actually good or not, when integrating it.
In Magento1, even additional translation pack extensions usually had to be gone through with a fine toothcomb to locally fix or override some misses or errors.

With the upcoming changes for more direct github merges to this repository (some bird twittered me), translations are likely to become a lot easier to fix at the source and co-maintain by the community.
That is big.

But there might be an additional level for perfectioning language integrations.
How does a project maintainer know if some PR actually improves a translation instead of breaking it, or worse contains defamatory content, if one doesn't understand it? Is it safe to merge? So there needs to be a review process, which can take time (find someone trustworthy who knows the language, first). This is where crowdsourcing could help for a faster turnaround - if ten people agree a translated string looks good, I can probably trust that.

You might already be aware of [transifex][tx] for collaborating on translations. I only recently looked into it. (They don't seem to strongly announce it, but have a free plan for open-source projects (now?); don't know if this would apply for magento/ebay.)

It's yet another service to register with and check up on, but otherwise I think this might be a nice fit. Might also be interesting for the documentation project.

It can be [integrated with github][tx-git] like a CI, so that newly written or changed source language strings get pushed to transifex, and upon translation and review get commited back to the github project.
The basic workflow is: putting some source language document(s) on transifex, have people translate strings (online or using the API or a transifex client), have others review the strings (locking them),
and then a 100% finished & reviewed translation gets pushed/merged to github by the integration. The reviewed (locked) strings on transifex won't be able to get translated again, until the source string changes.

You'll find there are already [some Magento projects][tx-magento] on it, to see [how this would look][tx-magento1] (requires a login to really see the interface, though :( ).
Also note that you can join a project/team there, but don't need to, to submit translations (similar to GitHub pull requests).

With an intelligent integration bridge (to be written, unless [this one][tx-gh] does it), I believe this can also work okay with the usual git merges to translation files in tandem (API-push them on tx after a git update).
And of course syncing source languages and translations could also be done manually, periodically, in a more immediate use-case.

With a magento-included php script for developers, it could be possible to grab updated, if unfinished, translation files directly through the API for testing/reviewing.

Lastly, they seem to be having some javascripts for direct/live in-website translations. Maybe there's an idea there for an extended Magento in-page translation module with optional transifex sync.

[tx]: https://www.transifex.com/
[tx-git]: http://docs.transifex.com/developer/integrations/#git-and-github
[tx-gh]: http://docs.transifex.com/developer/integrations/github
[tx-magento]: https://www.transifex.com/connect/projects/?search=magento
[tx-magento1]: https://www.transifex.com/projects/p/magento-ce-1x/

**Comment by piotrekkaminski** [comment]
Hello. We will soon open up translations via Crowdin. Please look for announcement soon.
