### ISSUE TITLE
Translations do not work when run via cron

### ISSUE THREAD

**Issue by fooman** [magento/magento2#8412]
### Preconditions

1. Magento 2.1.3 (and earlier)

### Steps to reproduce

1. Install a language pack, for example `composer require imaginaerum/magento2-language-fr-fr`
2. Create a new Store View "French"
3. Select fr_FR locale for this Store View
4. Change Stores > Configuration > Sales > Sales Email > General Settings > Asynchronous sending to Enabled
5. Place a new order from the French store
6. Ensure Magento's cronjob `bin/magento cron:run` is executing and that the order confirmation email has been sent

### Expected result

1. Order Confirmation Email is sent in French

### Actual result

1. 
<img width="661" alt="screen shot 2017-02-04 at 11 30 48" src="https://cloud.githubusercontent.com/assets/455508/22611270/8375c1e4-eace-11e6-85f0-dd1ce41c69b3.png">

Please note that the locale for email is correctly emulated as can be seen by formatting of the currency amounts.

**Comment by thomvanderboon** [comment]
Did you deploy the french language pack?

```
php bin/magento setup:static-content:deploy en_US fr_FR
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```

Thom

**Comment by fooman** [comment]
Yes the email was correctly translated if sending asynchronously is disabled.

**Comment by reindert-vetter** [comment]
I have the same problem. Temporarily resolved with the following solution:
https://github.com/magento/magento2/issues/3805#issuecomment-225160290

``` php
    /**
     * @var \Magento\Framework\App\AreaList
     */
    private $areaList;

    public function __construct(\Magento\Framework\App\AreaList $areaList) {
            $this->areaList = $areaList;
    }

    private function execute() {
            $areaObject = $this->areaList->getArea(\Magento\Framework\App\Area::AREA_ADMINHTML);
            $areaObject->load(\Magento\Framework\App\Area::PART_TRANSLATE);

            var_dump(__('Registered'));
    }
```

**Comment by fooman** [comment]
@reindert-vetter thanks for confirming. I have suggested a fix in this PR #8413 which is the same solution just on a higher level (cron not only the template). If you could confirm that my changes here  https://github.com/magento/magento2/pull/8413/files also work for you that be great.

**Comment by reindert-vetter** [comment]
Done

**Comment by freezable** [comment]
Hallo, I have "solve" this issue with using \Magento\Store\Model\App\Emulation::startEnvironmentEmulation() function before sending and stopping after.

**Comment by mrtuvn** [comment]
Hi just reported in 2.4.5 version

Magento removed part translate from abstract template email
Any ideas why of this changes
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/Model/AbstractTemplate.php#L515
Also cron seem not correct get phase translate
