### ISSUE TITLE
Content Block Administration fails when I delete more than one record

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#8415]
In the content block manager, in the admin panel, I get an error when I try to delete more than one record.

![selezione_022](https://cloud.githubusercontent.com/assets/1553035/22617774/0e07a5e0-eacd-11e6-8e43-fef37de9db89.png)

When I try to delete more than one item in the cms block by the mass action option I get this error:
( ! ) Fatal error: Uncaught Error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in /var/www/html2/magento2.local/app/code/Magento/Cms/Model/ResourceModel/Block/Grid/Collection.php on line 97

# Preconditions
Ubuntu, Standard LAMP (Apache, MySQL, ....)

PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper
HEAD -> develop

# Steps to reproduce
Admin > Content > Blocks
Select the checkboxs in the grid
Set the action DELETE 

# Expected result
Magento must delete the cms block items and then it must show the cms blocks list

# Actual result
( ! ) Fatal error: Uncaught Error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in /var/www/html2/magento2.local/app/code/Magento/Cms/Model/ResourceModel/Block/Grid/Collection.php on line 97

**Comment by dmanners** [comment]
I have added a pull request that will fix this issue. Not sure if it is the best way to fix but I will wait to see what Magento will say.

**Comment by dmanners** [comment]
The pull request has now been merged into develop. Not sure what/when the issue should be closed but thought I would let you know @shinesoftware

**Comment by shinesoftware** [comment]
@dmanners thanks! It works!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64176

**Comment by gritdigital-mibu** [comment]
This error is still happening in Magento 2.1.8 :(

**Comment by bradholmes-studio** [comment]
i have this error wen attempting to deleting a single block

**Comment by knima** [comment]
still happens in 2.1.8.
deleting 1 block at a time works fine.

**Comment by iangoh414** [comment]
Yes this is happening in 2.1.8 for me too

**Comment by nelero** [comment]
still happens in 2.1.9
Can we fix this please ? it's a regression :(

**Comment by dmanners** [comment]
Hi @nelero this fix is in version 2.2.0 and not in 2.1.9 I am sure that it would be available to be backported to the 2.1-develop branch.

**Comment by carylewis** [comment]
@dmanners How can this not be fixed in 2.1.8 or 2.1.9? This is fatal issue. This used to work in 2.1.4 - can the missing method be ported into the 2.1.8 or 2.1.9 branch?

**Comment by orlangur** [comment]
@carylewis anyone can work on backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

Just one method needs to be removed: https://github.com/magento/magento2/pull/8418/files

**Comment by okorshenko** [comment]
Hi @shinesoftware. Thank you for your report. 
The issue has been fixed in magento/magento2#12840 by @duckchip in 2.1-develop branch
Related commit(s):
 - 80595986e1e9e2ee11af759632922777682f302c

The fix will be available with the upcoming patch release.
