### ISSUE TITLE
How is the customer creates a demand notice by sms with rest api 

### ISSUE THREAD

**Issue by dajdouj10** [magento/magento2#8423]

**Comment by mrkhoa99** [comment]
@dajdouj10 I think it's better if you post your question on[ Magento SE](http://magento.stackexchange.com/) because your question doesn't relate to any Magento technical issue.

**Comment by mbrinton01** [comment]
Please use GitHub for bug reports only. With questions such as this E.g. 'how to do X' please post on the Magento 2 [Forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2).
