### ISSUE TITLE
M2.1.3 : Products created with REST API have no price.

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#8427]
When I try to create a product using the REST API, the product has no price. Not zero, just no price at all. A second, identical request adds the price.

### Preconditions

1. Empty, vanilla Magento 2.1.3 installation

### Steps to reproduce

Create a PUT-request to `/rest/V1/products/ABC123` with the following JSON data:

    {
      "product": {
        "sku": "ABC123",
        "name": "Test Product",
        "attribute_set_id": 4,    // Default attribute set for products
        "visibility": 4,
        "price": "100.0000",
        "weight": 1,
        "extension_attributes": {
          "stock_item": {
            "qty": "100",
            "is_in_stock": true
          }
        }
      }
    }

### Expected result

The product should be added with a price of $100.00.

### Actual result

The product is added with no price at all. A lookup in the database also shows that the column `catalog_product_entity_decimal` is empty, as well as any table that handles price-indexing and stuff.

Doing the same request a second time solves this issue, effectively storing the price in the proper table. Doing the same request to `/rest/all/V1/products/ABC123` gives the same result.

An interesting detail: the `weight`-attribute is also not stored during the first request. Also a decimal. Could it be that the problem resides in the storing of decimals?

**Comment by naydav** [comment]
Closed as duplicate 
https://github.com/magento/magento2/issues/8171
