### ISSUE TITLE
Get price in list.phtml takes too much time

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#8428]
Hello,
We have configurable products with ~450 children. Main product has zero price. Default price is the cheapest price from children.

In product list pages (may be also in other areas), it takes too much to load.
Because, while finding lowest price product, it spend much time.

Especially catalogsearch page. It is not cacheable so every search action, block getting & calculating price repeatedly. I tried MySQL & ElasticSearch, no difference. 

Other catalog pages, sake for caching, block loads faster if there is not invalidates. 
Using Redis for FPC backend. So if I can enable cache for catalog pages, problem may be resolved.

I have enabled profiler. Magento didn't lose any time in backend or frontend except price block.

### Preconditions

1. Magento 2.1.2
2. PHP 7.0.14

### Steps to reproduce

1. Create some configurable products with 2 attributes (First attribute has got 10 options, second has got 40 options). So there will be generated about 400 simples.
2. Clean cache & wait or force reindex
3. Try to make a search or load page after disable FPC.

### Expected result

1. Load page fast like other pages

### Actual result

1. Page loads too slow

**Comment by kandy** [comment]
Hi @rbostan 
Can you provide information on how times configurable product page is slower than a simple product page?  Do you use swatches for configurable product?
Thanks

**Comment by cizgidekiadam** [comment]
Hello @kandy 
For example, a catalog category with 36 per page configurables;
- Not FPC, it takes ~24secs
- FPC, it takes ~1.2 secs (Varnish or Redis) <-- This is very good for us

With simples, catalogsearch takes ~3 secs (with Redis)

In catalogsearch, can not use FPC so it takes ~3 mins with [ElasticSuite](https://github.com/Smile-SA/elasticsuite). Same results taken with MySQL search provider.

But, if remove price block from listing, catalogsearch page load falls to ~6 secs.

Strangely, we can not use Varnish with ElasticSuite, got 503 Backend fetch failed. 
So with ElasticSuite, we can do tests with Redis.

It may related about too much cache tags in header. 
In 2.1.3, Varnish header problem resolved but for now, we can't do an upgrade because of [#8061](https://github.com/magento/magento2/issues/8061).

Yes, we use swatches in all configurables, for now. Products species will increase in time.

**Comment by choukalos** [comment]
Tracking internally as MAGETWO-64310 .

**Comment by rbostan** [comment]
I did a trick for this. It is not a solution but workign for me.

In ConfigurablePriceResolver.php -> resolvePrice();
<pre>
public function resolvePrice(\Magento\Framework\Pricing\SaleableInterface $product)
    {
        $price = null;
        $products=$this->getConfigurableOptionsProvider()->getProducts($product)->getData();
        usort($products,function($a,$b){
            return $a['price'] - $b['price'];
        });
        $price=$products[0]['price'];
        /*foreach ($this->getConfigurableOptionsProvider()->getProducts($product) as $subProduct)   {
            $productPrice = $this->priceResolver->resolvePrice($subProduct);
            $price = $price ? min($price, $productPrice) : $productPrice;
        }*/
        if ($price === null) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('Configurable product "%1" does not have sub-products', $product->getSku())
            );
        }
        return (float)$price;
    }
</pre>

Ok, in here, we are asking a product's price (configrables child or native simple etc..) `$this->getConfigurableOptionsProvider()->getProducts($product)`holds products data which include price. So instead of loop in all chilren, get products collection data as array and sort it with compare and get first item price for min price. Sorting in desc, you may get child with max price.

It is really fast rather than looping. (~3mins page load decrease to ~4,5secs) I don't know this patch's affect on system wide for now.

Is that way a problem which not using `$this->priceResolver->resolvePrice($subProduct);` ?

**Comment by cizgidekiadam** [comment]
I have solved this by modifying ConfigurablePriceResolver.php.

<pre>
/** @var \Magento\Catalog\Api\ProductRepositoryInterface */
protected $productRepository;
</pre>

To construct:
<pre>
    public function __construct(
        PriceResolverInterface $priceResolver,
        Configurable $configurable,
        PriceCurrencyInterface $priceCurrency,
+++> ProductRepositoryInterface $productRepository
    ) {
        $this->priceResolver = $priceResolver;
        $this->configurable = $configurable;
        $this->priceCurrency = $priceCurrency;
+++> $this->productRepository=$productRepository;
    }
</pre>

In resolvePrice() method:
<pre>
    public function resolvePrice(\Magento\Framework\Pricing\SaleableInterface $product)
    {
        $price = null;
+++> $products=$this->getConfigurableOptionsProvider()->getProducts($product)->getData();
+++> usort($products,function($a,$b){
+++>    return $a['price'] - $b['price'];
+++> });
+++> $product=$this->productRepository->get($products[0]['sku']);
+++> $price = $this->priceResolver->resolvePrice($product);
--- > /*foreach ($this->getConfigurableOptionsProvider()->getProducts($product) as $subProduct)
--- > {
--- >     $productPrice = $this->priceResolver->resolvePrice($subProduct);
--- >     $price = $price ? min($price, $productPrice) : $productPrice;
--- > }*/
         if ($price === null) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('Configurable product "%1" does not have sub-products', $product->getSku())
            );
        }
        return (float)$price;
    }
</pre>

I know that could not correct solution. Any we shouldn't edit core files but I can not pluginize resolvePrice method or can not override the class. 

Instead of loop in all children, get products collection data as array and sort it with compare and get first item price for min price. Sorting in desc, you may get child with max price.
It is really fast rather than looping. (~3mins page load decreased to ~4,5secs)

Trying to find a alternative solution. 
How can i make a plugin for `Magento\ConfigurableProduct\Pricing\Price\ConfigurablePriceResolver::resolvePrice()` or override `Magento\ConfigurableProduct\Pricing\Price\ConfigurablePriceResolver` ?

**Comment by kandy** [comment]
@rbostan "How to add plugin" described in [official documentation](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html)

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
