### ISSUE TITLE
Bugreport-----Cannot load resource element 'AN'.

### ISSUE THREAD

**Issue by lizhi941** [magento/magento2#8432]
After installing Magento-CE-2_1_3_Zip-2016-12-16-06-04-03.zip version, when I login  in Admin and open the tab PRODUCTS->category, the exception is occoured. The report said "a:4:{i:0;s:203:"Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\xampp\htdocs\Magento213\vendor\magento\framework\Locale\TranslatedLists.php on line ).........".

### Preconditions

windows7,

 1. Magento community Edition 2.1.3 no sampledata
2. ; xampp5.6.24

### Steps to reproduce

1.  installing  Magento community Edition 2.1.3 no sampledata version
2.  I login  in Admin and open the tab PRODUCTS->category,the exception is occoured.
3. The report said "a:4:{i:0;s:203:"Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\xampp\htdocs..........

### Expected result

1. The report said "a:4:{i:0;s:203:"Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\xampp\htdocs........

### Actual result

1. [Screenshot, logs]
Screeshot:
There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 184348402
logs:
a:4:{i:0;s:203:"Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\xampp\htdocs........

no

**Comment by magento-engcom-team** [comment]
@lizhi941, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by satishhit** [comment]
I also facing this error.  
Magento\\Framework\\Locale\\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\\xampp\\htdocs\\swwn\\vendor\\magento\\framework\\Locale\\TranslatedLists.php on line 202",
