### ISSUE TITLE
Reset password doesn't work as well showing the message: "Please enter the same value again"

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#8436]
# Preconditions
Ubuntu, Standard LAMP (Apache, MySQL, ....)

PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper
HEAD -> develop

# Steps to reproduce
Go to the login page 
Click on forgot password link
When the email has been received click on the link in the email content
Set the new password in the both textbox
Click on the below button

# Expected result
Reset the password

# Actual result
Password cannot be reset and same message appear: "Please enter the same value again." 
![selezione_023](https://cloud.githubusercontent.com/assets/1553035/22658056/0ddfe4ba-ec99-11e6-9e0c-c32310c7d96b.png)

https://youtu.be/DE1lQtUjBvM

**Comment by avoelkl** [comment]
Hi,
I just tested the password reset function for an admin user with Magento CE ver. 2.1.3 and it worked fine.

Which version of Magento 2 are you using?

**Comment by shinesoftware** [comment]
The latest devel release has fixed the issue.
I am using the development version of the Magento 2.
