### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ndlinh** [magento/magento2#844]
I got following error when install beta1 from git
> Fatal error: Class 'Magento\Setup\Mvc\Bootstrap\InitParamListener' not found in /Users/xxx/xxx/magento2/setup/config/application.config.php on line 24

Here is my steps:
1. Clone repo
2. Execute ```composer install```
3. Open browser and access http:://virtualhost.name/setup/

**Comment by danharper83** [comment]
I had the same issue, any reason why this happens and can the magento docs be updated?

**Comment by IonutPerfectWeb** [comment]
I have the same issue, and composer self-update and then composer update did not solved the problem. I am using 0.74.0-beta3

**Comment by IonutPerfectWeb** [comment]
It may have to do with this error 
```
[ErrorException]                                                                                                         
  file_put_contents(/var/www/html/project/magento/app/etc/vendor_path.php): failed to open stream: No such file or directory  
```

appearing when first doing composer update after deleting the magento folder ..

also, is there a problem if I changed the 'htdocs' folder in 'magento'?

**Comment by IonutPerfectWeb** [comment]
if I add this:``` 'Magento\\Setup' => array($baseDir . '/magento/setup/src'),``` to ```vendor/composer/autoload_namespaces.php``` it no longer shows error but gives this error in console ```*4 open() "/var/www/html/project/magento/setup/index.php/navigation/menu" failed (20: Not a directory)```

**Comment by mazhalai** [comment]
@IonutPerfectWeb can you explain why you tried `composer install  after deleting the magento folder`.  Also, you shouldnt have to edit the `composer/autoload_namespaces.php`, it already is specified in magento's root [composer.json](https://github.com/magento/magento2/blob/develop/composer.json#L197)

**Comment by IonutPerfectWeb** [comment]
@mazhalai Well, I did a composer install first time, it gave that error, so I started troubleshooting. I deleted the magento folder as I think that something went wrong during the install. I did a composer.json first, it gave that error. the second time it didn't, but the project/setup still gave ``` [ErrorException]                                                                                                         
  file_put_contents(/var/www/html/project/magento/app/etc/vendor_path.php): failed to open stream: No such file or directory  ``` 
Then i modified composer/autoload_namespaces.php and I was able to do the setup via cli. 

If modified back, the cli install would not work..

I managed to get it working editing that file, but I still think its a problem that composer does not update autoloader

**Comment by mazhalai** [comment]
@IonutPerfectWeb are you installing magento using a custom `composer.json` using  `create-project` as opposed to steps mentioned in the first comment (here)[https://github.com/magento/magento2/issues/844#issue-52567903]? If yes, please post your `composer.json` file.

**Comment by IonutPerfectWeb** [comment]
@mazhalai Yes, I am using a custom composer.json. But I guess the important parts are those 

```
   "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/IonutPerfectWeb/zf2sluggenerator"
        },
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ],
    "require": {
       //some other modules
        "magento/magento-composer-installer": "*",
        "magento/product-community-edition": "0.74.0-beta3"
    },
    "extra": {
        "magento-root-dir": "magento",
        "magento-deploystrategy": "copy"
    }
```

**Comment by mazhalai** [comment]
@IonutPerfectWeb  Please add the following to your composer.json
```
"autoload": {
     "psr-4": {
     "Magento\\Framework\\": "htdocs/lib/internal/Magento/Framework/",
     "Magento\\Setup\\": "htdocs/setup/src/Magento/Setup/"
    }
},
```
Please replace `htdocs` with path to magento's root directory, and then CLI should work fine without issues.

**Comment by IonutPerfectWeb** [comment]
Thanks a lot for the help! You can close this:)

**Comment by mazhalai** [comment]
@IonutPerfectWeb Thank you for reporting the issue.

**Comment by dorian90** [comment]
I really dont know what is wrong with my composer.json, I have a composer.json file on server and one magento folder 

the one in magento folder
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.2.3",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.3",
        "composer/composer": "@alpha",
        "magento2translations/language_da_dk": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.2.0",
        "squizlabs/php_codesniffer": "3.2.2",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.2",
        "friendsofphp/php-cs-fixer": "~2.2.0",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": [
    {
    "type": "composer",
    "url": "https://repo.magento.com/"
    }
    ],
    "extra": {
        "magento-force": "override"
}

    
    
--------- the one on the server --------
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha",
        "quickpay/magento2": "^1.1",
        "mageplaza/magento-2-danish-language-pack": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
 }


when I try to install a pay gateway through composer using terminal I get this fault message 
![github](https://user-images.githubusercontent.com/37209358/38100884-e989adb6-337e-11e8-901a-1dd4ee859085.png)


The pay gateway company says I have an invalid .json file and referring to this thread, but i tried to update the composer still same issue

**Comment by ghost** [comment]
Removed vendor folder after composer install, again composer install -vvv and it applied all folders and files.
