### ISSUE TITLE
paypal return blank page after login 

### ISSUE THREAD

**Issue by tal-girit** [magento/magento2#8443]
### Preconditions

1. Magento version 2.1.2 , 2.1.3
2. php 5.6

### Steps to reproduce

1. i created a simple product with Customizable Options ,Option Type file !!
2. i enable paypal express on checkout 
3. try to porches this item with img attachment  

### Expected result

1. i expected to receive order with img attachment   

### Actual result

1. [Screenshot, logs]
![uat goldiejs com-paypal-express-return- token ec-46n49614l7752180j payerid paq89x9lmy9tl - google chrome_008](https://cloud.githubusercontent.com/assets/14885309/22689485/e0629b6c-ed39-11e6-8b45-3be8fdeb72b0.png)
![selection_010](https://cloud.githubusercontent.com/assets/14885309/22689684/b3563eca-ed3a-11e6-899e-ccd83ed3ce48.png)

2. checkout with this item and paypal express returns blank page  (error 500 ) , after i was redirected to paypal login and enter the submit button .
3. i receive token and payerId form paypal (see log )  , all looks   good 
4. and the order  was not created at the admin panel

**Comment by scottsb** [comment]
I think you mean "blank" page. Might want to edit the subject since it's confusing right now. :-)

**Comment by magento-engcom-team** [comment]
@tal-girit, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
