### ISSUE TITLE
Category path in body in one word connected with dash

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#8444]
### Preconditions

1. Magento 2.1.1

### Steps to reproduce

1. View source code in a sublevel category
2. View body class in the source code

### Expected result

1.  Category path should be separeted in single words for each category and not connected with a dash -. That way I can't select in CSS al pages inside a level 2 category for example. 

### Actual result

1. All cattegories are connected in one word which makes no sence for selecting by CSS. Check behaviour of Magento 1, it is well done there.

**Comment by flipflap** [comment]
I found a temporary solution, but I think it is not good for performance:
 
```
[class*="part-of-category-path"] {
}
```

**Comment by magento-engcom-team** [comment]
@flipflap, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
