### ISSUE TITLE
Can not remove item from cart sections is undefined in console 

### ISSUE THREAD

**Issue by nishantbkw** [magento/magento2#8447]
#preconditions
I am running magento version 2.1.8 

#issue
when i add to cart products and then click remove button it;s not working 
i can see the error in console 
Sections is Undefined 
file path : section-config.js 

#Reproduce 

Add a product into cart and click Remove button it does not work

Error in console 
Sections is Undefined

**Comment by K-Projects** [comment]
Same issue here.

The remove button only works when you are fast enough to click the remove button before the page is fully loaded.

**Comment by Tomasz-Silpion** [comment]
I've encountered similar error on another page and fixed it with removing

```
<referenceContainer name="main">
    <container name="content.top" label="Main Content Top"/>
    <container name="content" label="Main Content Area"/>
    <container name="content.aside" label="Main Content Aside"/>
    <container name="content.bottom" label="Main Content Bottom"/>
</referenceContainer>
```

from my custom theme layout default.xml

**Comment by veloraven** [comment]
@nishantbkw thank you for your comment.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@nishantbkw please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
