### ISSUE TITLE
Translate state province Drop-down list on checkout page, and my account, Magneto 2.1.2

### ISSUE THREAD

**Issue by kushtra24** [magento/magento2#8448]
Hi,
I've a shop with 2 different languages German and French,  because this shop is for Switzerland, the states there have different names in French and German, As I saw The file with the states is here:
../web/vendor/magento/module-directory/Setup --> Install_data.php
It looks like this:
            ['CH', 'UR', 'Uri'],
            ['CH', 'VD', 'Vaud'],
            ['CH', 'VS', 'Valais'],
            ['CH', 'ZG', 'Zug'],
            ['CH', 'ZH', 'Zurich'],

I'm using:
1. Magento 2.1.2,
2.  PHP v. 7.

I've used CSV first to translate, and it seemed that it worked for the "my account" page but not for the checkout page. then I translated the php file manually, and run: 
1. magento setup:upgrade
2. magento setup:static-content:deploy
3. magento indexer:reindex
4. magento cache:clean
5. magento cache:flush

Nothing helped the translation is gone and the new manual implementation dons not take place.?
Anyone an idea?

**Comment by veloraven** [comment]
@kushtra24 thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
