### ISSUE TITLE
problem VAT for muti views

### ISSUE THREAD

**Issue by strauss69400** [magento/magento2#8449]
Hi,
My website run with the version 2.1.2 I created two views. one for switzerland and one other for France.

So, i would like to get two VAT different. 8% for switzerland and 20% for France.

But impossible to Put in place this rules. However i created my taxe in Stores > Zones and tax rates. And my rule in System in Stores > Tax rules.

Then, In Stores > Configuration > Sales > Taxes i changed the default country for each views in Estimated default tax.

Nothing there does not work. Regardless of the view, the rate is maintained at 8%.

I know what to do, I tried everything.Hoping someone would have an idea? Thanks

**Comment by shrff** [comment]
Have you tried to rebuild the index in the Magento admin area?

**Comment by strauss69400** [comment]
yes, i rebuilded the index from the console.In Admin , we can't to do!!

**Comment by veloraven** [comment]
@strauss69400 thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@strauss69400 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
