### ISSUE TITLE
Nonce Is not being populated in API call to Braintree

### ISSUE THREAD

**Issue by fgp305** [magento/magento2#8451]
payment method nonce is not being populated in the API call to Braintree, Ive installed a One Page Checkout and also tried the default checkout and this error is occurring. 

Magento version 2.1.3

### Steps to reproduce
Basically just go thru the flow of adding a product to the cart and than trying to checkout. I put in all my information with the CORRECT CVV, card number, address, etc, and I got the error on the screen shot provided below. The error code says the CVV number is incorrect but it was triple checked and all the information entered is correct. 

Parameters: {"transaction"=>{"type"=>"sale", "customer"=>{"first_name"=>"freddy", "last_name"=>"pineda", "company"=>nil, "phone"=>"1234567890", "email"=>"fsb4e@yahoo.com"}, "amount"=>"106.53", "payment_method_nonce"=>nil, "order_id"=>"000000025", "channel"=>"Magento2_Cart_Community_BT", "billing"=>{"first_name"=>"freddy", "last_name"=>"pineda", "company"=>nil, "street_address"=>"1470 SE 18th Terrace", "extended_address"=>nil, "locality"=>"Homestead", "region"=>"FL", "postal_code"=>"33035", "country_code_alpha2"=>"US"}, "shipping"=>{"first_name"=>"fred", "last_name"=>"pineda", "company"=>nil, "street_address"=>"1470 SE 18th Terrace", "extended_address"=>nil, "locality"=>"Homestead", "region"=>"FL", "postal_code"=>"33035", "country_code_alpha2"=>"US"}, "options"=>{"store_in_vault_on_success"=>true, "submit_for_settlement"=>true}}, "merchant_id"=>"x2v3v33wk5pykk4n"}

and here is the error it caused:
 [VALIDATION ERRORS] 91508 (Cannot determine payment method.), 81706 (CVV is required.)
This error was caused because, as you see in the above log, payment_method_nonce​ is nil​. A payment method nonce is a string returned by the client SDK to represent a payment method. In your case, it likely indicates that you have not entered any card information in your checkout form. I'd suggest reviewing your inputs and attempting another test with a valid card. 

The reason you are receiving the error is because a payment method nonce is not being populated in the API call to Braintree, which is something Magento is responsible for generating.

<img width="400" alt="screen shot 2017-01-24 at 11 35 29 pm" src="https://cloud.githubusercontent.com/assets/6978952/22698096/96327e6c-ed21-11e6-82ee-00713d60783d.png">

**Comment by YevSent** [comment]
Hi, @fgp305, thanks for reporting. Unfortunately, I can't reproduce described issue. I've tried to reproduce it on a fresh installation of 2.1.3 version, and all works as expected, payment nonce is present in the request.

Could you provide more details, like browser error log or additional steps?

**Comment by fgp305** [comment]
Hi Joni

Thank you fro the reply. Im sorry if I sound a bit amateurish on this but im not very familiar with magento. But I believe the log is the one I post above. That is what the people from Braintree found when they looked at the date of the order I attempted . Perhaps if I give you my url and you go thru the order steps and see the error your self might give you a better understanding of my issue. 

I also see if I can get the web host to provide me with some error logs as I don't know how to retrieve them my self.

(update) My web host provided this as well 
POST https://www.freezerworkwear.com/development/rest/supermarket_en/V1/guest-carts/29940bfffa2007be4f5551fd0f6c7019/payment-information 400 (Bad Request)

My url is https://www.freezerworkwear.com/development/

Thank you so much for your help.

Fred

**Comment by scottsb** [comment]
@fgp305 You said that you "installed a One Page Checkout." Is this a third-party extension you're referring to? If so, it may help to note what extension that is. This may very well be an bug with the extension rather than with Magento.

**Comment by fgp305** [comment]
Hi Scottsb

Yes its a 3rd party extension. But the people at BSScommerce (extension developer) have been trying to help me with this since its their plugin. They have shared their screen shots and you can see it works. The issue is even with the magento DEFAULT checkout. I get the same error message with the BSScommerce 3rd party check out enabled and with it disabled in order to use the DEFAULT checkout. 

This is their extension https://bsscommerce.com/magento2/magento-2-one-step-checkout.html

**Comment by YevSent** [comment]
@fgp305, please, try to reproduce your issue on the fresh installation of Magento without any extensions.

**Comment by YevSent** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks.

**Comment by ebofi** [comment]
Same we are experiencing on Magento 2.2.7, using the default Magento checkout. 

The error we are getting is below'

'message' => 'Cannot determine payment method.',
      'creditCardVerification' => NULL,
      'transaction' => NULL,
      'subscription' => NULL,
'amount' => '1.00',
          'paymentMethodNonce' => NULL,
          'orderId' => '3700000353',
          'channel' => 'Magento2_Cart_Community_BT',
          'billing' => 

Here the paymentMethodNonce is NULL . Any help

**Comment by 0x15f** [comment]
Having the same issue as @ebofi

**Comment by seungwooc-23** [comment]
hello, i'm experiencing this issue when using braintree + paypal. the payment nonce i pass to the GraphQL API is non-null but `paymentMethodNonce` seems to get sent to braintree as NULL. i'm on magento 2.4.5.

**Comment by Antonio-Bennett** [comment]
@seungwooc-23 Have you gotten a workaround? @joni-jones I am facing this issue with `braintree_paypal` payment method with graphql api same as @seungwooc-23. The payment nonce is populated in `setPaymentMethod` mutation and I receive no errors there.

**Comment by seungwooc-23** [comment]
@Antonio-Bennett we had to use `braintree` as the payment method and call the `placeOrder` mutation in the same GraphQL request

**Comment by Antonio-Bennett** [comment]
@seungwooc-23 Hmmm so you are still using paypal but instead of using the dedicated `braintree_PayPal` payment method you are instead passing the `Braintree` payment method with the PayPal generated nonce?

**Comment by shahroz-musharp** [comment]
Hello,I'm experiencing this issue when using braintree + paypal. the payment nonce i pass to the GraphQL API is non-null but paymentMethodNonce seems to get sent to braintree as NULL. i'm on magento 2.4.4.
@alena-marchenko @seungwooc-23 @scottsb anyone able to find any way around ?

**Comment by seungwooc-23** [comment]
> @seungwooc-23 Hmmm so you are still using paypal but instead of using the dedicated `braintree_PayPal` payment method you are instead passing the `Braintree` payment method with the PayPal generated nonce?

yes, that's correct, we used the `braintree` payment method in our `setPaymentMethodOnCart` mutation. `braintree_paypal` did not work for us. To get things working we combined the `setPaymentMethodOnCart` and `placeOrder` mutations in one GraphQL request

**Comment by shahroz-musharp** [comment]
@seungwooc-23 I have tried but it does not work for me. Do you any example ?

**Comment by seungwooc-23** [comment]
how are you performing the mutation?

**Comment by shahroz-musharp** [comment]
I have custom mutation for the place order to add delivery date in the place order so should call like following.


mutation SetPaymentMethodOnCart {
    setPaymentMethodOnCart(
        input: {
            cart_id: null
            payment_method: {
                braintree: {
                    device_data: null
                    is_active_payment_token_enabler: null
                    payment_method_nonce: null
                }
                code: null
            }
        }
    ) {
        cart {
            email
            id
            is_virtual
            total_quantity
        }
    }
    placeOrder(input: { cart_id: null, delivery_date: null }) {
        order {
            amasty_order_date
            order_id
            order_number
        }
    }
}

**Comment by seungwooc-23** [comment]
looks correct to me.. .have you tried on a more recent version of magento? Ours was working on 2.4.5 and 2.4.6 

> I have custom mutation for the place order to add delivery date in the place order so should call like following.
> 
> `mutation SetPaymentMethodOnCart { setPaymentMethodOnCart( input: { cart_id: null payment_method: { braintree: { device_data: null is_active_payment_token_enabler: null payment_method_nonce: null } code: null } } ) { cart { email id is_virtual total_quantity } } placeOrder(input: { cart_id: null, delivery_date: null }) { order { amasty_order_date order_id order_number } } } `

**Comment by shahroz-musharp** [comment]
Yes, my magento version is 2.4.4.I have tries and I have following error.

Unable to place order: Your payment could not be taken. Please try again or use a different payment method. Unknown or expired payment_method_nonce.

**Comment by seungwooc-23** [comment]
@shahroz-musharp any luck with updating magento to 2.4.5 or 2.4.6 to see if that resolves the issue?
