### ISSUE TITLE
Price outlining in Invoice PDF

### ISSUE THREAD

**Issue by joost-florijn-kega** [magento/magento2#8453]
### Preconditions
1. Magento 2.0.x and 2.1.x

### Steps to reproduce
1. Create an new invoice on an existing order
2. Click the 'Print' button on the invoice detail page

### Expected result
1. Header label 'Price' aligned with the invoice item price

### Actual result
1. The header label 'Price' isn't correctly aligned with the invoice item price:
![screen shot 2017-02-07 at 17 02 08](https://cloud.githubusercontent.com/assets/16535591/22699227/31a6e01a-ed57-11e6-84cb-2be7897e6860.png)

**Comment by VasylShvorak** [comment]
@joost-florijn-kega Thanks for reporting this issue. Created internal issue MAGETWO-70380 to investigate and track this issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-65195

**Comment by magento-engcom-team** [comment]
@joost-florijn-kega, thank you for your report.
We've created internal ticket(s) MAGETWO-80737 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @joost-florijn-kega. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1216 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - 21566e89530af3eda7ff0f11d6cdd3b50eb87c71

The fix will be available with the upcoming patch release.
