### ISSUE TITLE
Grid Sticky header without buttons hides the title block

### ISSUE THREAD

**Issue by cykirsch** [magento/magento2#8455]
### Preconditions

1. Magento 2.1.3 EE

### Steps to reproduce

1. Edit /vendor/magento/module-cms/view/adminhtml/ui_component/cms_block_listing.xml
2. Comment out the `buttons` block. (line 15-22)

### Expected result

1. Go to page `/admin/cms_block`
1. Scroll up, sticky header should look like this
![image](https://cloud.githubusercontent.com/assets/8845299/22700280/bd7b9a1e-ed1f-11e6-8050-27f9cb51c1a9.png)

### Actual result

1. Go to page `/admin/cms_block`
1. Scroll up, sticky header looks like this
![image](https://cloud.githubusercontent.com/assets/8845299/22700230/8322e444-ed1f-11e6-8cc8-5aa739ebc7e7.png)

**Comment by flancer64** [comment]
Magento ver. 2.1.6 CE has the same issue.

**Comment by winds1983** [comment]
Same issue on 2.1.6

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70426 was created.

**Comment by magento-engcom-team** [comment]
@cykirsch, thank you for your report.
We've created internal ticket(s) MAGETWO-70426, MAGETWO-80722 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @cykirsch

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@cykirsch thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by gkroy1982** [comment]
Any update on this issue?
