### ISSUE TITLE
Store email addresses in Magento 2.1.3 CE do not accept four-letter domain extension

### ISSUE THREAD

**Issue by kamaleshdubey** [magento/magento2#8458]
### Preconditions

1. Magento 2.1.3 CE

### Steps to reproduce

1. Login to Magento 2.1.3 CE Admin Panel for the store.
2. In the left panel click on Stores.
3. Go to Configuration (under Settings) > Store email addresses (under General).
4. Try to enter an e-mail address for any of the sections (General Contact, Sales Rep, Customer Support, etc.) with a four-letter domain extension. I tried with .shop and .info (e.g. ornate@ornate.shop, admin@ornate.info).

### Expected result

1. The email address(es) should be saved on clicking Save Config button

### Actual result

1. An error message is returned on a bar at the top asking to correct the e-mail address.
<img width="850" alt="m2 1 3ce store email address issue" src="https://cloud.githubusercontent.com/assets/16374186/22715911/18e651bc-ed8b-11e6-923d-a2c21cddb731.PNG">

2. The email address field returns to its previous state, i.e. the system placeholders and checked Use system value check box are restored.

**Comment by miakusha** [comment]
Closed as duplicate #7867
