### ISSUE TITLE
js-translation.json generation broken in 2.1.4

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#8459]
After update from 2.1.2 (via composer) to 2.1.4 only empty js-translation.json files are generated. It worked great under 2.1.2.

### Preconditions
1. Install 2.1.4
2. Use f.e. the Magento Crowdin Translation package to translate your site

### Steps to reproduce
1. From document root run the following commands

```
cd app/i18n/test/nl_nl
/bin/rm source_nl_NL.csv
wget http://107.170.242.99/var/2.1.0/source_nl_NL.csv
cd /../../../../
#back to document root
find . -name js-translation.json -exec rm -rf {} \;
php bin/magento setup:static-content:deploy en_US nl_NL
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```

### Expected result
1. Correctly generated js-translation.json

### Actual result
1. Empty js-translation.json (contains only [] )

**Comment by thomvanderboon** [comment]
Little bit further testing and I found a work arround. If you run the deploy command with multiple languages, it is broken: f.e.
```
php bin/magento setup:static-content:deploy en_US nl_NL
```

The js-translation.json is generated correctly if invoked as separate commands for each language. f.e.

```
php bin/magento setup:static-content:deploy en_US
php bin/magento setup:static-content:deploy nl_NL
```

**Comment by philipvandebriel** [comment]
This problem started from 2.1.3

**Comment by andidhouse** [comment]
Jep this is a bug since 2.1.3 - before it worked without a problem.

**Comment by hostep** [comment]
This sounds like a duplicate of https://github.com/magento/magento2/issues/7862

**Comment by thomvanderboon** [comment]
This is duplicate of https://github.com/magento/magento2/issues/7862
