### ISSUE TITLE
Creditmemo if order/invoice amount = 0 (zero subtotal checkout)

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#8460]
### Preconditions
1. Magento 2.0.4
2. PHP 5.6

### Steps to reproduce
1. Create a new order with a total discount to subtotal = 0
2. Invoice the order - invoice amount = 0
3. Product gets shipped to the customer
4. Customer sends product back

### Expected result
5. Produkt should be added back to inventory and a creditmemo should be available for the accounting staff.

### Actual result
1. No option to create a creditmemo, due to no amount available to refund.

**Comment by lfritsche** [comment]
Would be great to hear, if you can reproduce this, or is it already solved 'till 2.0.12?

Thank you!

**Comment by Stas94** [comment]
@lfritsche Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
