### ISSUE TITLE
Magento 2.1.0 Checkout braintree issue

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#8464]
We are using Magento version 2.1.0

Getting error in checkout payment area,

We are using braintree credit card and Paypal and when we try to pay with braintree following error show in console area
TypeError: t[n.fieldKey] is undefined (https://js.braintreegateway.com/js/braintree-2.17.6.min.js)

and when we trying using paypal following error showingf in console area.
TypeError: Braintree.checkout is null (http://devm2.opumo.com/pub/static/frontend/Magento/opumo/en_GB/Magento_Braintree/js/view/payment/method-renderer/paypal.js)

**Comment by YevSent** [comment]
Hi, @aasim110, thanks for reporting. Unfortunately, can't reproduce described issue.

The current implementation of js components in Braintree (Magento 2.1.4) payment method is different to Magento 2.1.0 version and contains bug fixes, refactored components and updated version of Braintree js SDK.

Please, try to update your Magento version to the latest and reproduce your issue again.

**Comment by aasim110** [comment]
Hi, @joni-jones thanks for response, I want to ask you that, is that any other way instead of Magento upgrade ?

**Comment by YevSent** [comment]
If you want to get stable version of Magento with bug fixes, it's only way to upgrade your store.

**Comment by aasim110** [comment]
ok @joni-jones thanks for you help.
