### ISSUE TITLE
after migration from magento 1.6 to magento2.x. issue No such entity with id

### ISSUE THREAD

**Issue by magemanish** [magento/magento2#8465]
I'm facing problem in search by category on product listing page after migration from magento 1.6 to magento2.x. Please help me ASAP.

Getting below errors:-

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3
#0 /home/magento2/public_html/vendor/magento/module-catalog/Model/CategoryRepository.php(141): Magento\Framework\Exception\NoSuchEntityException::singleField('id', '3')

SET FOREIGN_KEY_CHECKS=0;
UPDATE `store` SET store_id = 0 WHERE code='admin';
UPDATE `store_group` SET group_id = 0 WHERE name='Default';
UPDATE `store_website` SET website_id = 0 WHERE code='admin';
UPDATE `customer_group` SET customer_group_id = 0 WHERE customer_group_code='NOT LOGGED IN';
SET FOREIGN_KEY_CHECKS=1;

I am Using this but error same
![screenshot from 2017-02-08 17 36 51](https://cloud.githubusercontent.com/assets/25637016/22736566/bb78fb2a-ee24-11e6-9a97-3ffe6d299ac4.png)

Thanks

**Comment by tommikissa** [comment]
Any solution for this? What is causing the error?

**Comment by victor-v-rad** [comment]
Hi @manish10188 

Did you have any errors on the way of migration? Try to migrate with the latest version of the tool. It might help

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by magemanish** [comment]
Hi,
Please check table "customer_entity" and check column 'failures_num',first_failure,lock_expires.
if not available than create
'failures_num', smallint(6) default 0
first_failure timestamp default NULL
lock_expires. imestamp default NULL

after that run reindex command
