### ISSUE TITLE
Calendar trigger buttons loose style after required validation fails

### ISSUE THREAD

**Issue by pguedesbr** [magento/magento2#8466]
### Preconditions

1. Magento 2.1.3 

### Steps to reproduce

1. Create a form in admin
2. Add a date field whith required-entry css class
3. Try to submit the form with the field blank

### Expected result

1. Validation message should show up after both the input and the calendar trigger button (which is  repositioned inside the input)

### Actual result

1. Validation message (label element) is inserted between the input and the calendar trigger button.
2. The calendar trigger button css selector becomes invalid since it uses the + sibling selector.

![image](https://cloud.githubusercontent.com/assets/9370105/22738153/5b0e5e2e-eded-11e6-9948-3155522db505.png)

![image](https://cloud.githubusercontent.com/assets/9370105/22738163/695678ae-eded-11e6-960d-5d6905bcd883.png)

### Possible solution
1. Instead of placing the validation message after the input, append it to the input's div.control container, therefore after all elements including the calendar trigger button

![image](https://cloud.githubusercontent.com/assets/9370105/22738442/a02192a0-edee-11e6-98a4-d82f77a6ee93.png)

**Comment by Stas94** [comment]
@pguedesbr We cannot reproduce this issue. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
