### ISSUE TITLE
Save Attribute after flush cache or cache disabled

### ISSUE THREAD

**Issue by vlauria** [magento/magento2#8468]
**Precondition:**

1. Magento CE 2.1.2, 2.1.3, 2.1.4 without sample data is installed.
2. Create a custom attribute for customer
3. Create a script or controller that save a custom attribute

**Steps to reproduce:**

1. Flsuh the cache
2. Run the script o controller

**Expected result:**
Custom Customer attribute is saved
**Actual result:**
Custom Customer attribute not saved. If you run the script two times it work

**NB. If you have a cache disabled not work  never**

**Comment by magento-engcom-team** [comment]
@vlauria thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by vishalgchetu** [comment]
Hi , 

I am also not able to save attribute without cache flush . 
$customer = $this->customerFactory->create()->load($customerId);
$customer->setLengthTimeIndustry($timeSpent);
                      try{
				$customer->save();
			}
			catch (Exception $e) {
				$message = __('Invalid Parameter.');
				$this->messageManager->addError($message);
			}

When I clear cache or flush cache then it works
