### ISSUE TITLE
ambiguity for cleanup-database option for M2 installation from CLI

### ISSUE THREAD

**Issue by valugi** [magento/magento2#8471]
All options for CLI have a predefined value, or are booleans and are solvable by 1/0. This particular option has none and is activated only by its simple presence, as documented [here](http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html):

> To drop database tables before installing the Magento software, specify this parameter without a value. Otherwise, the Magento database is left intact.

In order to automate the installation (for example using Ansible, but this is by no means required), one wants to loop through all installation options, get their given/default values and create the full install string for CLI without having special cases like the one above. For consistency sake is better to have all options with predefined values, than doing decision only based on the presence of the parameter. 

### Preconditions
1.  Magento CLI version 2.1.3

### Steps to reproduce
N/A.

### Expected result/proposal
Have a default value of 0, that will not drop the databases, and with value of 1 to drop.

**Comment by magento-engcom-team** [comment]
@valugi , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by valugi** [comment]
9 months later?! are you kidding me?
There are no steps to reproduce. 

What I am requesting here is consistency, you are using --cleanup-database as a value instead of being an parameter/value pair.

Expected option will be
--cleanup-database=0 // as a default value
--cleanup-database=1 // if we want to clean up.

**Comment by magento-engcom-team** [comment]
Hi @valugi. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/32
