### ISSUE TITLE
VAT for france don't work!!!

### ISSUE THREAD

**Issue by strauss69400** [magento/magento2#8472]
Hi

I have a big problem about the calculation of VAT for france.
I creatd two views for France and Switzerland.

For Switzerland, no problem, the Vat is good.
but For the view France, impossible to get the good rates.

my website is : http://magento21.coiffuremarket.com
You can see the problem with any products!!

However all is well configured; i am blocked for two days, impossible to resolve the problem.

i created the rates such as :

![image](https://cloud.githubusercontent.com/assets/8798254/22743930/06a92f2e-ee1c-11e6-830e-7b7c5e3ad531.png)

i created the good rule too : 
![image](https://cloud.githubusercontent.com/assets/8798254/22743975/281f3b12-ee1c-11e6-9390-deb4b516fd54.png)

For each view, I have chosen in stores > configuration > general > default country.

In stores > configuration > sales > tax > calculation defaut,
i have chosen the good country for each view too.

i am found, what do?
If someone could help me.
Thanks

Best regards

**Comment by korostii** [comment]
I thought it was deja vu, and then I found this #8449
Creating multiple reports of the same bug won't help much, I'd recommend to add additional info to the original bug instead.

**Comment by avoelkl** [comment]
Hi @strauss69400,
any update to this? if so, can you please add your problem report to the issue mentioned above #8449, thanks!

**Comment by avoelkl** [comment]
Closing this issue as new updates will be posted in #8449.
