### ISSUE TITLE
Magento 2 updated URLs not working

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#8476]
### Preconditions

1. Magento 2.1.3
2. 

### Steps to reproduce

1. Updated URLs of all products through CSV
2. Ran Reindexing
3. 

### Expected result

1. Products should be accessible through new URL

### Actual result

1. Products not accessible through new URLs
2. New URL is visible in backend but every search still leads to old URL

**Comment by EmilyPepperman** [comment]
I can confirm that this happens as well in our 2.1.3. @adityag186 if you save the product in Magento admin does it solve the issue for you. (I know it is a pain to go and resave every product) but try that on a couple of the products and see if that solves that for you.

**Comment by adityag186** [comment]
Hi,

Thanks for your advice. It works fine when I manually save an item from magento backend. 

However, I have 1000000 products. Is there any other way that I can do this? I cannot go on each manually.

**Comment by developer-lindner** [comment]
@adityag186 Maybe this helps: Go to Products->Catalog, select all products (checkbox on the left), and select action "update attribute" (which is a mass-action). Don't change any attribute just hit the save button. This helped me last year when i didn't saw products in some categories. Reindex & clean cache afterwards.

**Comment by adityag186** [comment]
@developer-lindner I tried doing that but when I click on "Update Attribute", it shows the message "no products selected" even though I had done "select all"

**Comment by Stas94** [comment]
@adityag186 We cannot reproduce this issue. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
