### ISSUE TITLE
Bug in validator.js file of module-payment?

### ISSUE THREAD

**Issue by NiteshKuyate** [magento/magento2#8482]
There is a validation of Credit Card Expiry for Month And Year But Magento providing same validation for Month and Year in versions Magento 2.1.1 and 2.1.3. There is only path difference in above versions.

Magento 2.1.1 path:/vendor/magento/module-payment/view/frontend/web/js/model/credit-card-validation/validator.js

Magento 2.1.3 path:/vendor/magento/module-payment/view/base/web/js/model/credit-card-validation/validator.js

### Preconditions

1. Magento 2.1.1 and Magento  2.1.3
2. PHP 7.0.6

### Steps to reproduce

1. We use following credit card validation for year on select
  `<select name="cc_year" id="input-cc-year" class="select-control" data-validate="{'validate-card-year':true}">`

### Expected result

1. Provide validation of expiry-year.

### Actual result

1. Providing validation of expiry-month.

I thought this bug is solved by making following changes on 1 line  in validator.js file.

Magento 2.1.1 path:
`/vendor/magento/module-payment/view/frontend/web/js/model/credit-card-validation/validator.js`

Magento 2.1.3 path:
`/vendor/magento/module-payment/view/base/web/js/model/credit-card-validation/validator.js`
 
For month: code starts from line no 61 Version 2.1.3
```
`'validate-card-date': [

        /**
         * Validate credit card number based on mod 10
         * @param {String} date - month
         * @return {Boolean}
         */
        function (date) {
            return monthValidator(date).isValid;
        },
        $.mage.__('Incorrect credit card expiration month.')
    ],`
```

For year: code starts from line no 87 Version 2.1.3

```
`'validate-card-year': [
        /**
         * Validate credit card number based on mod 10
         * @param {String} date - month
         * @return {Boolean}
         */
        function (date) {
            return monthValidator(date).isValid;
        },
        $.mage.__('Incorrect credit card expiration year.')
    ]`
```
There is need to replace 1 line of code : line no 95

```
function (date) {
            return expirationDateValidator(date).isValid;
        },

```
instead of :

```
function (date) {
            return monthValidator(date).isValid;
        },
```
Please helphow to overcome that problem. Thank you.

**Comment by korostii** [comment]
Well if you have time you cold also create a pull request for this fix, those seem to finally start getting merged (see [here](https://github.com/magento/magento2/projects/3)). Also until it's fixed s a workaround you could override this js file , see [here](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/custom_js.html) for dtails on that.

**Comment by YevSent** [comment]
Hi @NiteshKuyate, thanks for reporting. Created internal ticket (MAGETWO-64413).

**Comment by NiteshKuyate** [comment]
I have created path and copy 

> validator.js

 file:

`/app/code/Nitesh/Module/view/base/web/js/model/validator.js`

and made that 1 line change in that file.

`return expirationDateValidator(date).isValid;`

instead of :

`return monthValidator(date).isValid;`

Now providing correct validation for year.

Solved my issue.

**Comment by alena-marchenko** [comment]
Hi @NiteshKuyate 

Fix for MAGETWO-64413 is merged to develop branch, closing the issue.
Thank you.
