### ISSUE TITLE
I am unable to get Filtrable Attibutes in layered navigation for last level category in newly created store. Please help me on this issue.

### ISSUE THREAD

**Issue by soniyatiwari** [magento/magento2#8483]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by pboisvert** [comment]
@soniyatiwari please follow the reporting guidelines by providing information about the configuration and steps to reproduce. This is not enough information to reproduce the issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
