### ISSUE TITLE
shipping methods dont shown in checkout 

### ISSUE THREAD

**Issue by tal-girit** [magento/magento2#8486]
### Preconditions

1.  magento ver 2.1.3 , 2.14
2. php 5.6

### Steps to reproduce

1. postcode set up as mandatory !
2. add item to cart and move to checkout page prosses the checkout as guest

### Expected result

1.  see the shipping methods without refresh the page 

### Actual result

1. checkout page looks like see : 
![checkout - google chrome_011](https://cloud.githubusercontent.com/assets/14885309/22783954/b7c20c9e-eed6-11e6-85df-5f18ed03eb95.png)
shipping methods are not updated even after fill the fields
2.  after refresh the page it shows the shipping methods see : 
![checkout - google chrome_012](https://cloud.githubusercontent.com/assets/14885309/22784027/07086a3c-eed7-11e6-9384-4dfd09fb13b7.png)

**Comment by romeof1980** [comment]
hi @tal-girit 
in the first screenshot the fields are not filled. Could you please fill them and post the screenshot?
could you also please sent the screenshot of the Firebug-console?

cheers!

**Comment by tal-girit** [comment]
![workspace 1_002](https://cloud.githubusercontent.com/assets/14885309/22860629/4480e01a-f10c-11e6-9b62-06e41e036ca9.png)

no error in console

**Comment by romeof1980** [comment]
hi @tal-girit,
I had a look at the website https://www.kushies.co.il and the shipping methods show up correctly to me.
Are you sure you didn't set up a specific method for the product you tested?

![shows-up](https://cloud.githubusercontent.com/assets/11228308/22878472/c8a13a2a-f18e-11e6-9d1c-5f4befdafb6c.png)

romeo

**Comment by magento-engcom-team** [comment]
@tal-girit, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
