### ISSUE TITLE
Not able to add custom extension

### ISSUE THREAD

**Issue by Morningtime** [magento/magento2#849]
Referring to [#772]

Custom extensions now no longer show up at all in Magento2 0.42.0-beta1, not in the admin.

Also the Mage/Ogone payment extension does not show up under Payment methods. Likewise Authorizenet etc. The only payment methods available now are the OfflineMethods. Everything else vanished.

What changed?

**Comment by Morningtime** [comment]
>> Online payment methods are disabled/removed from the beta to discourage merchants to use the system in production.

Ok... I need to convert my 20+ Magento 1.x payment extensions to 2.x and I'd like to be ready. How/where did you disable the methods, so I can re-enable them myself?

**Comment by benmarks** [comment]
@Morningtime they simply are not present. We are making them available after Dev Beta has concluded in March.

**Comment by verklov** [comment]
@Morningtime, there is no way you can enable them - for the reason mentioned by @mrdevries we temporarily removed them from the code base. Please wait for the future versions when we will get them back. We are closing this ticket now.
