### ISSUE TITLE
Backend order creation items grid calling all children 

### ISSUE THREAD

**Issue by mgeoffray** [magento/magento2#8491]
### Preconditions

1.  Magento 2.1.3

### Steps to reproduce

1.  Add a block to sales order creation items grid in `Foo/Bar/view/adminhtml/layout/sales_order_create_index.xml`    
```xml
<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="items_grid">
            <block class="\Magento\Framework\View\Element\Template" name="foo_bar_block" template="Foo_Bar::template.phtml"/>
        </referenceBlock>
    </body>
</page>

```
2. Create a simple template in `Foo/Bar/view/adminhtml/templates/template.phtml`   
```html
<tbody>
    <tr>
        <td>Custom Block</td>
    </tr>
</tbody>
```
3. Call the child block in `Magento/Sales/view/adminhtml/templates/order/create/items/grid.phtml`    
```
<?php echo $block->getChildHtml('foo_bar_block') ?>
```

### Expected result

1.  The child block appears only once

### Actual result

1. The child block appears twice   
![child_display_twice](https://cloud.githubusercontent.com/assets/1154299/22788411/0a3d9642-eee0-11e6-94f6-65ec7e54dbcc.png)

The block is called in the `order-discounts` div with the line  
```
<div id="order-coupons" class="order-coupons"><?php echo $block->getChildHtml();?></div>
```
The `getChildHtml` call is maybe too broad

**Comment by Andrii-Deineha** [comment]
@mgeoffray Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-71099.

**Comment by magento-engcom-team** [comment]
@mgeoffray, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
