### ISSUE TITLE
[2.1.x] Saving configurable products with (many) assigned images generates Timeout 504.

### ISSUE THREAD

**Issue by petterkj** [magento/magento2#8492]
When saving a configurable product with many images assigned a e.g. the color attribute.  I checked load.. 100 % CPU usage until eventually timeout it seems. There is HUGE amount of CPU usage here. I think ALL the images are resized etc. ? You can't do these things in a single request...

Tested in these environments:

Magento env: production
Nginx, php-fpm, Redis cache, Mysql 5.6, php 7.0.X.

### Preconditions
1. Create a new attribute set
2. Assign two attributes to the set. E.g. size and color.

### Steps to reproduce
1. Add a new configurable product.
2. Chose the attribute set you created in preconditions.
3. Step 2 of Configuration. Create a new configurable product with these two attributes, generate simples based on size[XS,S,M,L,XL] and colors [blue,white,black,green,red,brown].
4. Step 3 ("Bulk Images and Price"): Chose `Apply unique images by attribute to each SKU` and upload two images for every "color". 
5. Click next, next and try to Save the Product.

### Expected result
1. Product should save successfully.

### Actual result
1. 504 timeout after at least 1 minute.

**Comment by petterkj** [comment]
It has to do with the images. If you have no images, saving goes through with no problems. And with images, CPU raises to 100% for a loong time.

**Comment by RonXS** [comment]
I've run into this a lot too, i was able to "workaround" it, by disabling all the timeouts in the php.ini configuration.

When i eventually got the 504, you just wait and refresh the backend product catalog page and see all the products appear until its finally done. 

Its a poor workaround, but it works. Better would be that saving images doesnt take so long.

**Comment by oleg-onufer** [comment]
Hi @petterkj.
I cannot reproduce this issue.
If this issue is actual add setting in  php.ini  
max_execution_time = 18000,
max_input_time = 9000, 
memory_limit = 2G
and memory_limit = 2G in .htaccess too.
Add setting  in  nginx.conf file:
proxy_connect_timeout        600;
proxy_send_timeout             600;
proxy_read_timeout             600;
  send_timeout                      600;
Then restart nginx: "service nginx reload"

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
