### ISSUE TITLE
[2.1.3-2.1.4] "A customer with the same email already exists in an associated website."

### ISSUE THREAD

**Issue by pbologna** [magento/magento2#8494]
Magento 2.1.4 and 2.1.3 trigger error saying email address is already used during Reorder or Submit New Order if at least a single quote (apostrophe) is present in customer data (First name/Last Name/Addresses)

### Preconditions
Magento 2.1.3 installed by the 2.1.3.tar.gz and composer or Magento 2.1.4 (upgraded from 2.1.3)
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
nginx version: nginx/1.10.0 (Ubuntu)
Production Data at the database

### Steps to reproduce
1. Create an Order with a customer whose Firstname/Lastname/any address field at the (Default Addresses) contains at least a single quote (apostrophe: ASCII char 39).
2. Go Backend -> Sales -> Orders -> Pick that Order
3. Try to Reorder - Submit Order page opens
4. Try to Submit Order
5. You'll get "A customer with the same email already exists in an associated website.".

To Avoid this error, it seems that Customer data at customer_address_entity (Default Addresses) should *not* contain the quote *before* the Submit Order page is opened: deleting the quote at the page is not enough to get rid of the error.

### Expected result
Submit Order button should create the new order as there's no point into checking that email is already there: it's a reorder.

### Actual result
Order doesn't get created: it fires up with an error saying "A customer with the same email already exists in an associated website." and inhibit the Reorder and the Submit Order.

**Comment by wert2all** [comment]
Thank you for your response. Internal issue MAGETWO-64875 was created.

**Comment by southerncomputer** [comment]
Any ideas on how to properly escape the single quote from wrecking shipping estimate and 0 for totals issue?

**Comment by southerncomputer** [comment]
Replace 2.1 Escaper.php with development Escaper.php to fix and use EscapeHtmlAttr( ) around the datajson in form.phtml to be like this:

`<form id="edit_form" data-order-config='<?php echo $block->escapeHtmlAttr($block->getOrderDataJson()) ?>' 
`
Otherwise folks will be able to XSS your admin area!

or just use double quotes!

`<form id="edit_form" data-order-config="<?php echo $block->escapeHtml($block->getOrderDataJson()) ?>"`

you'll need to upgrade your AbstractBlock.php in vendor/magento/framework/View/Element/AbstractBlock.php
to developer version too.

**Comment by magento-engcom-team** [comment]
HI @pbologna the issue has been fixed in 2.2.0 . Could you please let us know if you still have an issue

**Comment by Puru2016** [comment]
Please let me know what should is do to fixed this issue in magento 2.1.10?

**Comment by ghanshyam-maurya** [comment]
I am facing the same issue in case of Magento 2.2.0 Version.
Can you provide me the files fixes for this issue for version 2.2.0?

**Comment by ghanshyam-maurya** [comment]
Can you please provide me the updates on this issue for Magento version 2.2.0.

This issue seems closed but we are not getting the files using which we can fix the issue.
