### ISSUE TITLE
Theme not applied to the store

### ISSUE THREAD

**Issue by shoptofit** [magento/magento2#8496]
### Preconditions

1. Majento 2.1.3
[Ultimo1.docx](https://github.com/magento/magento2/files/764826/Ultimo1.docx)

2. Default Luma theme or custom theme

### Steps to reproduce

1. Apply custom Theme
2. 
3. 

### Expected result

1. Theme implemented in Store

### Actual result

1. [Screenshot, logs]

[Ultimo1.docx](https://github.com/magento/magento2/files/764832/Ultimo1.docx)

**Comment by cadoworld** [comment]
Hi,
I think it is a bug from 2.1.3 as was working fine on previous version. If your magento is only for one store. Try to set up as single store, your theme should be implemented.

**Comment by pbologna** [comment]
Hi,
please check if you have any Scheduled Theme: Content - Design - Schedule.
Happened in past have an entry there (imported from 1.x) with NULL date, almost invisible to see on backend, but deleting that Schedule entry did the trick for me.

**Comment by Ctucker9233** [comment]
I had the same problem in 2.1.3 but it works fine now in 2.1.4.

**Comment by magento-engcom-team** [comment]
@shoptofit, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
