### ISSUE TITLE
Reindexing not taking place

### ISSUE THREAD

**Issue by kamaleshdubey** [magento/magento2#8499]
### Preconditions

1. Magento CE 2.1.4

### Steps to reproduce

1. A system message is being displayed on logging into Admin that indexers are invalid and asking to check in cron jobs are running or not
<img width="725" alt="m2 1 4 reindex error_1" src="https://cloud.githubusercontent.com/assets/16374186/22809407/2cfca52a-ef2a-11e6-969f-51c0dadaabea.PNG">

2. However, cron jobs are enabled:
<img width="960" alt="m2 1 4 reindex error_2" src="https://cloud.githubusercontent.com/assets/16374186/22809445/947a2a2e-ef2a-11e6-97dd-82869ef7f332.PNG">
<img width="952" alt="m2 1 4 reindex error_3" src="https://cloud.githubusercontent.com/assets/16374186/22809451/99d019d4-ef2a-11e6-9929-3a6fcbbcacff.PNG">

3. Also indexing is enabled to run as per schedule:
<img width="952" alt="m2 1 4 reindex error_4" src="https://cloud.githubusercontent.com/assets/16374186/22809477/d372972a-ef2a-11e6-824e-7f71284f5048.PNG">

### Expected result

1. Re-indexing should be performed according to schedule.

### Actual result

1. Reindexing does not occur.
2. Unable to install new extensions or update existing ones:
<img width="950" alt="m2 1 4 reindex error_5" src="https://cloud.githubusercontent.com/assets/16374186/22809593/6bacb2c8-ef2b-11e6-83b5-516f4acfa353.PNG">

**Comment by bondimedical3** [comment]
Your cron jobs are not set up correctly

**Comment by xmav** [comment]
@kamaleshdubey Did you setup cron jobs? Please refer http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html for instructions.

**Comment by gman-1986** [comment]
@kamaleshdubey It still won't work with cron jobs setup see issue #5836

**Comment by magento-engcom-team** [comment]
@kamaleshdubey, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
