### ISSUE TITLE
HTML Profiler and `pub/static` Resources

### ISSUE THREAD

**Issue by astorm** [magento/magento2#850]
When a user enabled the HTML profiler, the `pub/static.php` file adds HTML code to the bottom of non-HTML resources.  For example, if you load 

    http://127.0.0.1:8080/pub/static/adminhtml/Magento/backend/en_US/prototype/prototype.js
    
The end of the file will contain code like the following

        findChildElements: function(element, expressions) {
          var selector = expressions.toArray().join(', ');
          return Prototype.Selector.select(selector, element || document);
        }
      });
    })();
    <table border="1" cellspacing="0" cellpadding="2">
    <caption>Code Profiler (Memory usage: real - 7340032, emalloc - 7024160)</caption>
    <tr>

This HTML code causes javascript execution errors, which breaks application functionality.  While this can be worked around using other profiler modes (csvfile), enabling the HTML profiles **should not** break the application's functionality. 

Steps to Reproduce.

1. Add `SetEnv MAGE_MODE developer` to your `.htaccess` file

2. Add `SetEnv MAGE_PROFILER html`

3. Confirm profiler added to the bottom of your root page

4. Load a file through `static.php` via a URL like `pub/static/adminhtml/Magento/backend/en_US/prototype/prototype.js`

**Expected Behavior**: Magento loads executable Javascript, preserving application functionality

**Actual Behavior**: Magento loads Javascript with HTML profiler code at the end, breaking application functionality

**Comment by snohe** [comment]
@astorm, this has been resolved in 0.74.0-beta1.  Thank you again for submitting this issue.  Should you have any other questions, feel free to reach out to us by opening a new issue.
