### ISSUE TITLE
swatches-renderer.js not possible to extend without copying template

### ISSUE THREAD

**Issue by OZZlE** [magento/magento2#8500]
### Preconditions

1. Magento version 2.1.2 (and probably latest?)

### Steps to reproduce

1. Inside your custom theme/module add inside requirejs-config.js the mixin or map feature as:
described here: https://github.com/magento/magento2/issues/1864
or map as here http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/requirejs_concept.html

### Expected result

1. By extending the Magento_Swatches/js/swatch-renderer via requirejs-config.js it should be possible to extend and modify it without copying and changing templates.

### Actual result

1. It is never extended. It doesn't work because inside the module Magento_Swatches the requirejs-config.js file and the path Magento_Swatches/js/swatch-renderer was removed in some version of 2.1. Also it was renamed from swatchRenderer to swatch-renderer without mapping the old name to the new so that also breaks any sites upgrading m2 version if they had extended the swatchesRenderer...

The only way to extend it currenly is like this: http://magento.stackexchange.com/a/136927/6078

**Comment by magento-engcom-team** [comment]
@OZZlE, thank you for your report.
We've created internal ticket(s) MAGETWO-83680 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@OZZlE, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
