### ISSUE TITLE
Category Scope StoreView has no default value or option to reset

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#8502]
### Preconditions

1. Magento 2.1.0 CE

### Steps to reproduce

1. Create Storeview
2. Create Category
3. Switch Scope in Catalog > Category from AllStoreViews to specific StoreView
4. Edit something and save Category for the specific StoreView
5. Try to reset data to default values

### Expected result

1. There should be shown a checkbox: "Use default value" (like in 2.0.x)

### Actual result

1. No button or field appears

### Comment

- For example in Magento 2.0.x there are those config settings

### Images
1. All Scopes
![category_allstoreview](https://cloud.githubusercontent.com/assets/12051528/22822550/32cc657a-ef80-11e6-9867-e315f578671f.png)
2. Scope StoreView
![category_storeview](https://cloud.githubusercontent.com/assets/12051528/22822568/43819c96-ef80-11e6-8b87-ad15c4dd8830.png)
3. Magento 2.0.x
![category_storeview_2 0 x](https://cloud.githubusercontent.com/assets/12051528/22822877/89cdae50-ef81-11e6-9e45-879a607742bd.png)

**Comment by smoskaluk** [comment]
Internal ticket MAGETWO-70425 created

**Comment by magento-engcom-team** [comment]
@ulftietze, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
