### ISSUE TITLE
Cannot unsubscribe customer from newsletter

### ISSUE THREAD

**Issue by vanderlee** [magento/magento2#8506]
Backend user cannot unsubscribe a customer from a newsletter.

### Preconditions
1. Standard Magento 2.1.4 with all updates applied, running on CentOS 6.x
2. Customer with "Subscribed to Newsletter" checked.
3. Newsletter module enabled

### Steps to reproduce
1. Go to `Customers` > `All Customers`
2. Select the subscribed customer
3. Click on `Newsletter` in the Customer information box
4. Uncheck the `Subscribed to Newsletter` checkbox. (see screenshot)
5. Click the `Save Customer` button.

### Expected result
1. Customer unsubscribed in database (`newsletter_subscribers.subscriber_status` = 3)
2. `Subscribed to Newsletter` checkbox unchecked in user interface.

### Actual result
1. Customer still subscribed in MySQL database table `newsletter_subscribers`, where `subscriber_status` still has value `1`.
1. Checkbox remains checked: ![image](https://cloud.githubusercontent.com/assets/649240/22825965/381a541e-ef90-11e6-903b-f7c9aab981b8.png)

**Comment by wert2all** [comment]
Thanks for responce, closed as dublicate of https://github.com/magento/magento2/issues/6313
