### ISSUE TITLE
dev/tools/performance-toolkit/generate.php very slow during url_rewrite generation

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#851]
follow the documentation to setup magento2.

then execute: php dev/tools/performance-toolkit/generate.php --profile dev/tools/performance-toolkit/profiles/medium.xml

now you get as output:
Generating profile with following params:
 |- Websites: 1
 |- Store Groups: 2
 |- Store Views: 2
 |- Simple Products: 16000
 |- Configurable Products: 1000
 |- Categories: 300
 |- Catalog Price Rules: 20
 |- Cart Price Rules: 20
 |- Registered Customers: 200
Generating stores, store views and websites...  done in 00:00:02
Generating categories...  done in 00:01:10
Generating simple products... done in 00:51:59
...(more output not important for this issue)

Most parts run very fast, and even the simple products generating was finished much earlier then the output shows.
The executed sql statements found via the processlist command make me believe, the url_rewrite index update caused most of the needed time.

**Comment by mazhalai** [comment]
For internal tracking: MAGETWO-32335

**Comment by verklov** [comment]
Response from the team:
> This is expected behavior according to current system design. Note that unlike Magento 1 in Magento 2 there is no URL Rewrites indexer, no operations performed in background and if there is collision in URL Key for particular store numeric suffix is not added but merchant should choose another non-conflicting value.
> So, all operations are performed in real-time with integrity checks and that's why url_rewrite table is quite writing-intensive during performance toolkit fixtures installation.
We are closing this ticket now.
