### ISSUE TITLE
Enhancement request to this catalogProductAttributeMediaGalleryManagementV1

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#8511]
Hi 

We want to request for enhancement for a current process of uploading the images files for product via Rest APIs. Can we have public URL of the image send as parameter in the API and then Magento system can use that URL to download that information on server and display it. This make the API communication and processing much faster and less error prone. I see that Magento already have code which is handling the urls while importing item data via CSV. Can this feature also be introduced in the Catalog Media API

Thanks,

**Comment by srinivasanithin** [comment]
Any update if this request is accepted or more information is need from me?

**Comment by magento-engcom-team** [comment]
@srinivasanithin , please refer to the [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)) site for Feature Requests and Improvements. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by okorshenko** [comment]
Hi @srinivasanithin if you would like to improve system behavior, please submit a pull request. The GitHub issue tracker is intended for Magento Core technical issues only.
