### ISSUE TITLE
400 (Bad Request) error on Checkout page during payment-information request

### ISSUE THREAD

**Issue by yuklia** [magento/magento2#8512]
### Preconditions
1. Magento v2.1.2
2. PHP 7.0.10 
3. Mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64)

### Steps to reproduce
1. Add product to cart
2. Go to Checkout page
3. Fill email with test@gmail.comddd
4. Choose payment method: Check / Money order

### Expected result
1. Email validation error

### Actual result
1. {"message":"Unable to save address. Please check input data.","trace":"#0 \/var\/www\/app\/code\/Magento\/Quote\/Model\/GuestCart\/GuestBillingAddressManagement.php(49): Magento\\Quote\\Model\\BillingAddressManagement->assign('1', Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/var\/www\/app\/code\/Magento\/Checkout\/Model\/GuestPaymentInformationManagement.php(102): Magento\\Quote\\Model\\GuestCart\\GuestBillingAddressManagement->assign('ea6125b333d77a1...', Object(Magento\\Quote\\Model\\Quote\\Address))\n#2 \/var\/www\/app\/code\/Magento\/Checkout\/Model\/GuestPaymentInformationManagement.php(79): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformation('ea6125b333d77a1...', 'test@gmail.comd...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#3 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('ea6125b333d77a1...', 'test@gmail.comd...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#4 \/var\/www\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#5 \/var\/www\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#6 \/var\/www\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#9 \/var\/www\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#10 {main}"}

Frontend and backend validation for email are different. Email "test@gmail.comddd " is not valid for Zend_Validate::is.
 ` public function validateBeforeSave()` throw an exception and it wasn't handled anywhere that is why `rest/default/V1/guest-carts/ea6125b333d77a16e106b604f1022219/payment-information` return stack trace in response.

**Comment by oleg-onufer** [comment]
Hi @yuklia.
Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
