### ISSUE TITLE
Downloadable product is available for download even if order state is set canceled.

### ISSUE THREAD

**Issue by pangteypiyush** [magento/magento2#8515]
Downloadable product is available for download even if order state is set canceled.

### Preconditions
1. Magento 2.1.4
2. PHP 5.6.30
3. mysql  Ver 14.14 Distrib 5.6.35

### Steps to reproduce
1. Create an order for a downloadable product.
2. Set order state to STATE_CANCELED programatically.
3. Goto customer account dashboard, it list the order as 'canceled'.
4. Now goto "My Downloadable Products" in customer's dashboard, order state referring to downloadable product is listed as 'Available'.

### Expected result
State of Downloadable product linked to the order should also change according to the state of the order.

### Actual result
Order state changes correctly to "canceled" but inside "My Downloadable Products", the same order is listed as 'Available', allowing customer to download the product even if the order state is cancelled.

**Comment by Winfle** [comment]
Team Forbytes will take it

**Comment by ishakhsuvarov** [comment]
Hi @pangteypiyush
Issue has now been fixed in the `develop` branch with the PR #8917 
Thanks for reporting.

**Comment by pangteypiyush** [comment]
Thanks everyone!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66506
