### ISSUE TITLE
ProductRepository::save assigns the product to all websites

### ISSUE THREAD

**Issue by dunarri** [magento/magento2#8520]
### Preconditions
Magento CE v2.1.1
at least 2 stores and websites
a product to test that is only in 1 of the websites

### Steps to reproduce
1. Create a module with an observer on catalog_product_save_after
2. Trigger this code by saving any product in the admin
3. sample observer code that causes the problem:
```php
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $product = $observer->getProduct();
        if ($product->getSku() != 'TEST-SKU') {
            $product = $this->productRepository->get('TEST-SKU');
            $product->setPrice(9.99);    // or anything you want to change to test
            $this->productRepository->save($product);
        }
    }
```
4. now observe this product you modified, it will have been added to all websites

### Expected result
The products websites should remain unchanged.
This is the behavior when saving a product through the admin, but it is because the Save controller uses the old deprecated $product->save() method.

### Actual result
The product has been added to all websites.
This is due to the assignProductToWebsites method of ProductRepository:
```php
    if ($this->storeManager->getStore()->getCode() == \Magento\Store\Model\Store::ADMIN_CODE) {
        $websiteIds = array_keys($this->storeManager->getWebsites());
```

**Comment by dunarri** [comment]
#7019 ProductRepository always assigns product to default website

**Comment by dunarri** [comment]
If anyone is interested in the workaround, here is the code I use:
```php
$websites = $product->getWebsiteIds();
$savedProduct = $this->productRepository->save($product);
$addedWebsites = array_diff($savedProduct->getWebsiteIds(), $websites);
$this->productWebsiteFactory->create()->removeProducts($addedWebsites, [$product->getId()]);
```

**Comment by robbanl** [comment]
@dunarri Did other fields change as well? For instance, let's assume the product you were loading had "USE DEFAULT" checked for all values on all websites. When setting the price, does the other values go from "USE DEFAULT" to the same value but the "USE DEFAULT" button unchecked?

**Comment by dunarri** [comment]
I don't think so, but I'd have to go back and test again for that when I have time.

**Comment by dunarri** [comment]
@robbanl I'm not sure what you mean, no field on my product edit screen has a use default option. The closest is "Use Config Settings" for "Allow Gift Message".

I've upgraded to the latest Magento 2.1.5 and tested the issue again and the problem still persists. Of course it does because the code in ProductRepository::assignProductToWebsites is still exactly the same.

**Comment by bencorlett** [comment]
I'm having the exact same issue as well.

@robbanl, product data (for example, "name") is not duplicated across scopes, it remains global (being greyed out on a store view scope and showing "use default"):

![screen shot 2017-03-10 at 9 57 06 am](https://cloud.githubusercontent.com/assets/181919/23774500/031413b0-0578-11e7-9502-96c11fe06b96.png)

There is no way, using either `ProductRepositoryInterface`, or `ProductWebsiteLinkRepositoryInterface` to assign a product to any websites if your script is running in an admin website context. The reason we're doing that is so all data is updated on a global scope and not specific to the default website:

![screen shot 2017-03-10 at 9 45 39 am](https://cloud.githubusercontent.com/assets/181919/23774437/bdd681ac-0577-11e7-8e9d-c8e26b8fb2b1.png)

> The above screenshot is from a console command that syncs products back in from a third party service.

**Comment by magento-engcom-team** [comment]
@dunarri, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by mcjwsk** [comment]
@magento-engcom-team I don't think it is a correct behavior because editing through the admin panel doesn't work like that. The product repository shouldn't override product websites (especially two or more websites) if it is set in the object.

**Comment by RomaKis** [comment]
This issue was fixed by the https://github.com/magento/magento2/commit/30c4881 ( PR https://github.com/magento/magento2/pull/11444 ). 
So, I think, @magento-engcom-team, you can close it.

**Comment by magento-engcom-team** [comment]
@RomaKis thank you for investigation. Closing
