### ISSUE TITLE
Place Order button enabled before Customer Updates Address

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8522]
When checking out, whe paying via the Braintree CC option, if the customer chooses is shipping to an address that is different than the billing address and enters a different billing address at checkout, the Place Order button is active before the customer updates the address. 
Because it is not disabled, if the customer does not push update the address (most of the time), the billing address is overwritten by the shipping address causing the credit card to reject the address if AVS is enabled and also causing the customer invoice to display the shipping address for both shipping and billing.
If the customer chooses to pay a different way, the Place Order button is disabled until the customer has pushed the update address button.

### Preconditions
Magento 2.13
I am using a fresh, clean out of the box install with no customizations and no extensions.

### Steps to reproduce

1. Braintree Payment Module is enabled
2. Customer deselects My billing and shipping address are the same 
3. Customer is able to push place order without updating address

### Expected result

1. The Place Order button should be disabled until customer hits Update button.
![cod](https://cloud.githubusercontent.com/assets/21045500/22859583/3525da34-f095-11e6-95b6-01f2beb811a7.jpg)

### Actual result

1. Customer can place order before billing address is updated
![braintree](https://cloud.githubusercontent.com/assets/21045500/22859582/2f4e60cc-f095-11e6-888a-a6474e203f47.jpg)

**Comment by annhudspeth** [comment]
Thanks for the callout - I agree that this is a problem and will pass this along to PM to fix.

**Comment by YevSent** [comment]
Hi, @rosandrest, thanks for reporting, I've created internal ticket MAGETWO-64654.

**Comment by YevSent** [comment]
Hi, @rosandrest, the fix is already merged to develop branch.

**Comment by ghost** [comment]
Do you know what release this will be fixed in?

**Comment by YevSent** [comment]
@rosandrest, this fix should be available in Magento 2.1.10 release.

**Comment by spraxis** [comment]
Still happening in 2.1.7

**Comment by YevSent** [comment]
@spraxis, this fix hasn't been backported to 2.1.7 it present in 2.1.10.

**Comment by gwharton** [comment]
This is still broken in 2.2.3.

**Comment by gwharton** [comment]
Can anyone point me towards the commit in 2.1 that fixed this so I can prepare a backport into 2.2 and 2.3.

**Comment by mjf10** [comment]
I'm having the same issue in 2.2.2. I get several orders each day that show as "Pending" but nothing was ever passed to the gateway (authorize.net)

As far as I can tell, I'm only having the issue on virtual products

**Comment by VadimLugovoy** [comment]
I don`t know is it fixed or no yet, but on 2.3.4-p2 version this bug still happens.
I see that there is no even any check for control visibility (active/disable) of this button - https://prnt.sc/t61fc7
in file vendor/magento/module-vault/view/frontend/web/template/payment/form.html

**Comment by VadimLugovoy** [comment]
@joni-jones , let me know please, does it fixed in any version?

**Comment by andreifurrnica** [comment]
@magento give me 2.4-develop instance
