### ISSUE TITLE
[Magento\Framework\Exception\NoSuchEntityException] Requested store is not found

### ISSUE THREAD

**Issue by deshibazaar24** [magento/magento2#8523]
When I Want to upgrade magento 2.1.2 to 2.1.3 or 2.1.4 The following issues has been seen:

1. Composer has been updated successfully.
2. rm -rf var/di var/generation or rm -rf var/di -seen okay
3. php bin/magento cache:flush - error hown as bellow:
   
 [Magento\Framework\Exception\NoSuchEntityException]
    Requested store is not found

    cache:flush [--bootstrap="..."] [types1] ... [typesN]

5. php bin/magento setup:upgrade ----seen same error

   [Magento\Framework\Exception\NoSuchEntityException]
    Requested store is not found

    cache:flush [--bootstrap="..."] [types1] ... [typesN]

 Note: after disable 3rd-party extensions & run setup upgrade ---showing same error.

Kindly help to resolve it.
Thanks
Deshibazaar24

**Comment by magento-engcom-team** [comment]
@Deshibazaar24, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
