### ISSUE TITLE
Change in the Magento Zend1 Framework

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#8527]
### Preconditions

1. Anything after the merge of https://github.com/magento/magento2/pull/8356

This is a question on how things will progress. In the PR https://github.com/magento/magento2/pull/8356 I was able to remove the Zend1 Captcha from Magento 2, but unless I see it differently the files will still be in the Magento zend1 module they just wont be in use.

My question is how and when will this be updated/removed?

Things to consider:

1. Someone could be using the Zend1 version and removing it could break BC,
2. If Zend Captcha is removed from Magento1 module would it's version get a new major release? If that is the case how would the Magento2 version look like?

**Comment by orlangur** [comment]
> removing it could break BC

Is anything from ZF1 marked with `@api` annotation?

> how and when will this be updated/removed?

I don't think any _part_ of the https://github.com/magento/zf1 will be removed ever. This dependency could be removed completely from core at some point, any third-party module should have ` "magento/zendframework1": "~1.12.16",` explicitly specified if using it directly.

Thus, nothing bad may happen, unless some implementation relied on some things changed in #8356.

**Comment by dmanners** [comment]
Going to close this as I think nothing will change/needs to change here currently.
