### ISSUE TITLE
Setting Tax -> Calculation Settings -> Catalog Prices-> Including Tax don't works

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#8528]
### Preconditions
1. Magento 2.1.3 with sample data
2. Cache disabled

### Steps to reproduce
1. Set Configuration -> Setting Tax -> Calculation Settings -> Catalog Prices in "Including Tax"
2. Set  Configuration -> Setting Tax -> Price Display Settings -> Display Product Prices In Catalog in "Including and Excluding Tax"
3. rm -rf var/cache 
4. php bin/magento indexer:reindex
5. Sign in as roni_cost@example.com

### Expected result
1. If product price in admin product page is 100$, I should see on the front:
- price including tax: 100$
- price excluding tax: (100$ - tax price)

### Actual result
1. Wrong  Calculation:
- price including tax: 100$ + tax price
- price excluding tax: (100$)
2. Screenshots:
https://drive.google.com/file/d/0B__P_POF2b9aVEZQS0ZyM3VBaHc/view?usp=drivesdk
https://drive.google.com/file/d/0B__P_POF2b9aSmJvMUNodmdiY0E/view?usp=drivesdk

**Comment by choukalos** [comment]
This is not a bug.  Please set your shipping origin (Store->Configuration->Sales->Shipping Settings->Origin) to the same location as your store.  Then make sure you have a valid rule and tax rate for your store's location.  Then Magento will interpret the catalog tax rate as the same tax rate as the store's tax rate.
