### ISSUE TITLE
Typo in error message "Table <tablename> is not exists"

### ISSUE THREAD

**Issue by fwolfst** [magento/magento2#8529]
Magento 2.1.4 using the data migration tool (reported there: https://github.com/magento/data-migration-tool/issues/242 - but the text probably stems from magento 'core').

[Zend_Db_Exception]
Table "customgrid_grid" is not exists

Should read ... "does not exist".

**Comment by bvrbanec** [comment]
Issue in progress @bvrbanec

**Comment by magento-engcom-team** [comment]
@fwolfst, thank you for your report.
The issue is already fixed in develop branch, 2.2.1
