### ISSUE TITLE
Doing a product save will set has_options to 0 because of check getCanSaveCustomOptions() in beforeSave and custom options disappear from frontend

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#8531]
### Preconditions
1. Magento 2.1.4

### Steps to reproduce
1. Have a simple product with custom options
2. In code add some data with `$product->addData()`
3. Save the product using it's own save function: `$product->save()`

### Expected result
1. Product should display it's custom options on frontend

### Actual result
1. Custom options are not shown on frontend because of attribute has_options is set to 0.

I know the correct way to save the product is: `$this->productRepository->save($product)` and this problem will not happen. I just want to let other people know about this behaviour so they can get their issue resolved.

**Comment by ishakhsuvarov** [comment]
@PascalBrouwers, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by PascalBrouwers** [comment]
Again: I know the correct way to save the product. I just want to let other people know about this behaviour so they can get their issue resolved, since the first place will be the issue tracker of this github repository.

**Comment by jeffreytony** [comment]
Thanks a lot! I have no idea for this problem already for a long long time. 

> Again: I know the correct way to save the product. I just want to let other people know about this behaviour so they can get their issue resolved, since the first place will be the issue tracker of this github repository.
