### ISSUE TITLE
Cannot read property 'autocomplete' of undefined

### ISSUE THREAD

**Issue by snez** [magento/magento2#8532]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.14
3. MySQL 5.6.22
4. Google Chrome 56.0.2924.87 (Official Build) (64-bit)

### Steps to reproduce

1. Add two products to the shopping cart
2. Navigate to the shopping cart page at /checkout/cart/
3. Click "Checkout with multiple addresses"
4. Follow the steps

### Expected result

1. No javascript crashes
2. No interference with Payment Methods

### Actual result

1. Javascript crash
2. Payment Methods do not appear

![screen shot 2017-02-13 at 15 28 33](https://cloud.githubusercontent.com/assets/249977/22889660/ccc95092-f201-11e6-9613-3d96d0caf669.png)

**Comment by Ctucker9233** [comment]
I have exact same errors on any page. Magento version 2.1.4 and earlier.

**Comment by Ctucker9233** [comment]
@snez Workaround found here http://magento.stackexchange.com/questions/125034/js-errors-magento-2
seems to work.

**Comment by govindarajprevaj** [comment]
I am using magento version 2.1.6 and also getting the same error.

**Comment by dmitriyprime** [comment]
Hi, @snez. Thanks for reporting this issue. We've created internal ticket MAGETWO-70389 to address this issue.

**Comment by 100rabhMisra** [comment]
Getting same issue .. 
![screenshot from 2017-07-17 03 44 37](https://user-images.githubusercontent.com/15998893/28259037-55bfd466-6aa2-11e7-825e-4ce85cb2cba2.png)

**Comment by timbaker1991** [comment]
For what it is worth, I think I have tracked this down as the route cause (a long with https://github.com/magento/magento2/issues/6983) for some issues around gift message fields in basket not loading as the jQuery has an error. This doesn't explain why other elements do work - but fixing this solved the issue after a considerable amount of time looking in to it.

**Comment by mattgreenfield** [comment]
I am also having this issue, does anyone know of a work around? Thanks.

**Comment by peterjaap** [comment]
Still present in 2.1.8; https://github.com/magento/magento2/blob/2.1.8/app/code/Magento/Customer/view/frontend/web/js/view/authentication-popup.js

Appears fixed (or at least changed) in 2.2RC; https://github.com/magento/magento2/blob/2.2.0-rc3.0/app/code/Magento/Customer/view/frontend/web/js/view/authentication-popup.js#L23

**Comment by magento-engcom-team** [comment]
@snez, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by lano-vargas** [comment]
I started having 'autocomplete' of undefined exact same as @snez  described when I was asked to by my team to remove shopping  cart icon completely so I did in my custom theme I added: 
```
<referenceBlock name="top.links">
     <referenceBlock name="minicart" remove="true" />
</referenceBlock> 
```
Didn't see the undefined until I had to look at the chrome console for debugs I got a surprise and spend a few hours trying to figure it out what was causing the issue then gotcha! now I am just using css to display:none .
ref: Magento 2.1.7

**Comment by aimscoder** [comment]
https://magento.stackexchange.com/questions/125034/js-errors-magento-2 

This will work 
**Copy file from** 
vendor/magento/module-customer/view/frontend/web/js/view/authentication-popup.js
**to**
app/design/frontend/<custom_theme_name>/<custom_theme>/Magento_Customer/web/js/view/authentication-popup.js

and replace the below code
**from** 
autocomplete: window.checkout.autocomplete 
**to** 
autocomplete: ((window.checkout && window.checkout.autocomplete) ? window.checkout.autocomplete : null),

Line No : 26 

Please run bin/magento setup:static-content:deploy command.

Hope this will work for you

**Comment by sergiomendonca** [comment]
Same erros on v.2.1.9

**Comment by nshiff** [comment]
In addition to the update from @aimscoder, I had to include the following in the same file. 

```
login: function (formUiElement, event) {
            var loginData = {},
                formElement = $(event.currentTarget),
                formDataArray = formElement.serializeArray();
```

becomes

```
login: function (formUiElement, event) {
            if(!event){
                event = window.event;
            }
            var loginData = {},
                formElement = $(event.currentTarget),
                formDataArray = formElement.serializeArray();
```
