### ISSUE TITLE
Magento 2 Swagger specification invalid, operationID not unique

### ISSUE THREAD

**Issue by bastianccm** [magento/magento2#8533]
### Preconditions

1. Magento 2.1 Latest swagger json, retrieved from http://devdocs.magento.com/swagger/schemas/latest-2.1.schema.json

### Steps to reproduce

1. Download http://devdocs.magento.com/swagger/schemas/latest-2.1.schema.json
2. Run swagger validator from https://goswagger.io/

### Expected result

1. swagger.json valid

### Actual result

1. swagger.json is invalid, the operationId is not unique

According to the official swagger 2.0 specification at http://swagger.io/specification/#fixed-fields-37 the node `operationId` is defined as

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.
consumes	[string]	

However, Magento 2.1 does reuse the same `operationId` for API endpoints having `/me/`-shorthand.

Example: `/V1/customers/me/billingAddress` and `/V1/customers/:customerId/billingAddress` both define `customerAccountManagementV1GetDefaultBillingAddressGet` as their `operationId`.

Even though the online swagger validation does not fail, goswagger and other related tools do.

### Suggested fix

Use some kind of a `Me` suffix or something similiar for the operationID

**Comment by magento-engcom-team** [comment]
@thebod, thank you for your report.
We've created internal ticket(s) MAGETWO-83774 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @thebod

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@thebod thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by bastianccm** [comment]
Will this ever be fixed? Will it ever be possible to follow the Swagger standard and properly use the Magento API?
