### ISSUE TITLE
static folder names translated & space characters in path

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#8534]
### Preconditions

1. Magento 2.0.12
2. PHP 5.6
3. German Translation: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE

### Steps to reproduce

1. Updated from 2.0.4 to 2.0.12
2. rebuild static files (setup:static-content:deploy de_DE en_US)
3. Backend > View Orders:
Console: `GET .../pub/static/adminhtml/Magento/backend/de_DE/UI%20/template/%20Raster/%20Filter%20/%20Elemente%20/%20Ausw%C3%A4hlen.html 403 forbidden`
4. the Folder "UI " for example now contains a space '20%' and several folder names were translated from default en_US to de_DE:
Example from my de_DE CSV: `Select,Auswählen`

### Expected result

1. foldernames should not contain space characters and should not be translated

**Comment by lfritsche** [comment]
Could solve the Problem by replacing `Symlink` with `Copy`

Open up app/etc/di.xml and find the virtualType name="developerMaterialization" section. In that section you'll find an item name="view_preprocessed" that needs to be modified or deleted. You can modify it by changing the contents from Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink to Magento\Framework\App\View\Asset\MaterializationStrategy\Copy
Delete the files under pub/static to get rid of any existing symlinks. You may want to be careful not to delete the .htaccess file.
Credits to: Chris O'Toole > http://magento.stackexchange.com/questions/64802/magento-2-404-error-for-scripts-and-css

Additional Question:
Why does Magento always behave that weird if this preference is set to symlink instead of copy?
I already had that on other projects with Magento2...

**Comment by vzabaznov** [comment]
Hi @lfritsche i've just checked your bug and find out that this is German locale puck problem - 
just look at https://raw.githubusercontent.com/splendidinternet/Magento2_German_LocalePack_de_DE/master/de_DE.csv and find phrase 'ui/grid/filters/elements/select,' you will see that translation for this with redundant spaces - 'UI / Raster/ Filter / Elemente / Auswählen'

Not sure about folder translation, but if you delete redundant spaces from German locale pack al will work as expected

**Comment by lfritsche** [comment]
Hi @vzabaznov thank you for diving deeper into my issue!
I just reported the bug to splendidinternet to delete the line.
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/61
