### ISSUE TITLE
Category Link Anchor Custom Text Encoding

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#8535]
### Preconditions
1. Magento 2.14
2. 

### Steps to reproduce
1. In page layout add widget of type "Catalog Category Link" in content
2. In Anchor Custom Text set the text to be in non-English characters

### Expected result
1. Maintain the UTF-8 charset

### Actual result
1. The text is converted (assuming a db conversion)

**Comment by george-vlahakis** [comment]
If I change the text inside the editor itself and save the page it works, but when I return the page admin again it throws this error.

> Attention
> 
> error: error in [unknown object].fireEvent(): event name: tinymceBeforeSetContent error message: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by ziiljuks** [comment]
It looks like we will have to wait for fix: scheduled for 2.1.9
#4232
