### ISSUE TITLE
Allowed Countries not being recognized for PayPal payments

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8536]
Customers from countries that are not selected in the allowed countries setting are able to checkout and pay with PayPal.

### Preconditions

1. Magento CE 2.1.4
2. PHP 7.0.15
3. MySQL 5.6
4. PayPal Website Payments Standard / PayPal Express

### Steps to reproduce

1. Customer adds products to cart and goes to checkout
2. Checkout payment method is PayPal
3. Customer is sent to the PayPal site to complete the payment
4. Customer is able to checkout and pay from a different country than what is specified in the Magento settings (in this case a customer with a USA address is able to checkout when Magento is set to only allow orders from Canada)

### Expected result

1. Customer **will not** be able to checkout from a country that is not selected in the list of allowed countries

### Actual result

1. Customer **can** checkout and complete the order from a country that is not selected in the list of allowed countries

**Comment by vzabaznov** [comment]
Hi @crtsl please write if 'Enable PayPal Credit' option enabled, if you disable this option, customer form non allowed countries will not be able to proceed payment with PayPal

**Comment by ghost** [comment]
Hello @vzabaznov PyaPal credit is not enabled. This store is based in Canada and PayPal credit is not available in Canada.

This appears to be a bug somewhere with the integration between Magento and PayPal. The allowed countries setting appears to have no effect when a customer completes the order with PayPal.

**Comment by vzabaznov** [comment]
@crtsl i've just checked this functionality on 2.1.4 CE version and find that all works as expected, let me show you my steps: 

**Pre-conditions**:
1. Simple product is created
2. PayPal express checkout is configured with all needed Api data, Enable PayPal Credit - disabled, In Advanced settings 'Payment Applicable From' - 'Specific Countries', Countries Payment Applicable From - e.x. Afghanistan 

**Steps**
1. Go to storefront on product page
2. Add it to cart and go to product placement
3. Specify customer address e.x. from Algeria
4. Go to next step - PayPal is absent as payment method
5. Go back and set address as Afghanistan
6. Go to the next step - PayPal is present as payment method

@crtsl can you please confirm that my steps in valid according to your scenario, or please write what i did wrong

**Comment by ghost** [comment]
@vzabaznov I just did some further testing with this.

**Pre-conditions**

Settings:

Stores -> Settings -> Configuration -> General -> General -> Country Options -> Default Country - Canada

Stores -> Settings -> Configuration -> General -> General -> Country Options -> Allow Countries - Canada

Stores -> Settings -> Configuration -> Sales -> Payment Methods -> PayPal All-In-One Payment Solutions -> Website Payments Standard -> Advanced Settings -> Payment Applicable From - All Allowed Countries

**Steps to reproduce**

1. Add product to cart
2. Checkout with PayPal with US PayPal account and US PayPal shipping address (no shipping address on customer account profile in Magento)
3. Customer is returned to site to select shipping method and is able to checkout successfully with a US address

**Expected result**

Customer is blocked from checking out with a US shipping address

**Actual result**

Customer is able to complete order with US shipping address


After changing the allowed countries setting in the PayPal payment method as follows:

Stores -> Settings -> Configuration -> Sales -> Payment Methods -> PayPal All-In-One Payment Solutions -> Website Payments Standard -> Advanced Settings -> Payment Applicable From - Specific Countries

Countries Payment Applicable From - Canada

The customer is now blocked from completing the order with a US PayPal shipping address.

I would think that with the Payment Applicable From setting set to All Allowed Countries it would get the allowed countries from the general setting but this doesn't appear to be the case. This seems like it could be a bug or is this how it is intended to work?

**Comment by skovalenk** [comment]
Hi @crtsl this is different Allowed Countries settings. 
Customer Allowed Countries are not allowed to create account in specific country
Shipping and Payment allowed countries is used to limit some payments or shipping methods.

So you need to specify correct countries in all settings.

**Comment by erfanimani** [comment]
Weird, I've still got the same problem. Running Magento 2.1.11.

I've even changed `Payment Applicable From - Specific Countries`, and it still lets me checkout using a different country.
