### ISSUE TITLE
nginx issue - CentOS6

### ISSUE THREAD

**Issue by Crustymd** [magento/magento2#854]
MOst of the hosting servers that have SentOS6 installed with or without ISP manager panel have nginx installed on it, you can not disable or delete you will need to reconfigure the server. Anyway by default they have it installed. I run throw the instalaation with no error, when i reach the part when i ahve to go throw Web Installer http://mysite.com/magento2/setup - the page is just BLANK

Server log no errors. With the help of MAX i managed to find the issue, at least he says it's the issue

YOu can see the issue here http://prntscr.com/5jmnfr

You have a nginx.conf.sample in the root folder, so i fi try to make the nginx.conf in the /etc/nginx/nginc.conf to include this nginx.conf.sample from magento root. THe nginx will just stop working on the server, even if i define $MAGE_ROOT; 

The question is how d oyou guys set up nginx correctly on CentOS for magento2? did anybody had nginx issue? 

Thank you

**Comment by maksek** [comment]
Hi @Crustymd, seems like you have resolved the issue?

**Comment by muasir** [comment]
closing this issues as @Crustymd hasn't responded in 15days.  Please reopen if our fix didn't work for you.
