### ISSUE TITLE
can not modify table customer_entity is_active ?

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#8540]
### Preconditions

```
1. Magento2ee 2.1.2
2. php7.0.12
3. mysql5.7
```
### Steps to reproduce

php code like below:
app/code/Test/Test/Controller/Test/test.php
```
<?php
namespace Test\Test\Controller\Test;

class test extends \Magento\Framework\App\Action\Action
{

    protected $resultPageFactory;
    
    protected $customerFactory;

    public function __construct(
        \Magento\Framework\App\Action\Context $context, 
        \Magento\Framework\View\Result\PageFactory $resultPageFactory, 
        \Magento\Customer\Model\CustomerFactory $customerFactory
        )
    {
        $this->resultPageFactory = $resultPageFactory;
        $this->customerFactory = $customerFactory;
        return parent::__construct($context);
    }

    /**
     *
     * {@inheritdoc}
     *
     * @see \Magento\Framework\App\ActionInterface::execute()
     */
    public function execute()
    {
        // TODO Auto-generated method stub
        $customerModel = $this->customerFactory->create();
        $customerModel->load(8110);
        $tmp = $customerModel->getData();
        $customerModel->setData('firstname','firstnamexxxxx');
        $customerModel->setData('is_active','0');
        $customerModel->save();
        return $this->resultPageFactory->create();
    }
}
```
### Expected result

find the table cutomer_entity,the entity_id is 8110 ,is_active change value to 0,firstname change to firstnamexxxxx

### Actual result

firstname can change ,but is_active can not modify,it is also show 1 in the table

why not modify is_active?what`s wrong with me?

**Comment by michaeldyl520** [comment]
I find the step to resolve the problem.
I find use the cutomer module of the system must add eav of the same name in customer_entity,
open backend,go store,below attribute,open customer,add a new attribute,don`t forget choose Customer Registration and Customer Account Edit in Forms to Use In,Then open the table eav_attribute,locate the attribute you added earlier,change backend_type to static,then you can change it use my program.that`s all.

**Comment by magento-engcom-team** [comment]
@michaeldyl520, thank you for your report.
We've created internal ticket(s) MAGETWO-81074 to track progress on the issue.

**Comment by nemesis-back** [comment]
Hey, @magento-engcom-team and @okorshenko , does it makes sense to fix this issue b/c currently is_active attribute is never used in magento 2 core?

**Comment by roychandrasekhar** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@michaeldyl520, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
