### ISSUE TITLE
Automatic shopping cart price rule does not apply if coupon code is applied

### ISSUE THREAD

**Issue by supportstreammarket** [magento/magento2#8541]
### Preconditions

1. Issue for "Automatic shopping cart price rule does not apply if coupon code is applied" is fixed in 2.1.3
2. Please let us know the files changed to solve this

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by pboisvert** [comment]
Going to need you to add more info here. Please follow the reporting guidelines and specify system information as well as full steps to reproduce including the settings for the cart price rule and the coupon. This info is needed to reproduce the configurations to try and reproduce the error.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
