### ISSUE TITLE
DOMDocument::schemaValidate(): Invalid Schema

### ISSUE THREAD

**Issue by rendyep** [magento/magento2#8542]
### Preconditions

1. Windows 10
2. Magento 2.1.2
3. Apache 2.4.23
3. PHP 7.0.10
4. MySQL 5.6.30

### Steps to reproduce
1. Yesterday everything was ok, no errors or warnings.
2. Today when I open my local Magento 2, I get a `Invalid Schema` error. I don't do anything like updating packages, cleaning or flushing cache, or anything else, I don't even touch any files, I just open my local Magento 2 website, and the error is triggered.

### Expected result
1. I'm able to see my local Magento 2 website as usual.

### Actual result

1. The following warning and error is triggered:
`Warning: DOMDocument::schemaValidate(): Invalid Schema in path\to\magento2project\vendor\magento\framework\Config\Dom.php on line 311`
![image](https://cloud.githubusercontent.com/assets/5343517/22919708/4369df26-f2cc-11e6-85ae-e6c1653569cb.png)

I inspected who triggered the errors and warnings, and I found that the errors and warnings are fired when DOM tries to validate `path\to\magento2project\vendor\magento\framework\ObjectManager\etc\config.xsd` line 104, 105, 135 and 141.

**Comment by korostii** [comment]
> DOM tries to validate  path\to\magento2project\vendor\magento\framework\ObjectManager\etc\config.xsd
XSD file usually isn't the file that gets validated, but the schema to which XML files must conform. In this case, my guess would be that you have an invalid "config.xml" file in one of your modules.

I agree though that it's a bit unpredictable and counter-intuitive how Magento2 decides whether to validate these. I believe it is[ supposed to depend on current mode](http://magento-quickies.alanstorm.com/post/149898556055/magento-2-more-plugin-edge-cases) you're in, but some control over it via bin/magento commands certainly wouldn't hurt. The error messages aren't perfect as well: hard to tell what caused it, as evidenced by the case above.

P.S. You might find the following [link](https://alanstorm.com/magento-2-xml-validation-errors/) useful while debugging these.

**Comment by rendyep** [comment]
Hi @korostii, thanks for the links.

Here is what I got when I dumped the errors: [DOMDocument::schemaValidate(): Invalid Schema](https://gist.github.com/rendyep/c00a8e90067c772f9849a6d680e92f6c)

Could you give a check and inspect why is the error triggered?

**Comment by korostii** [comment]
Oh wow, not even sure what am I looking at here. I don't see any info hinting at the cause here.
I would try generating urn links using this command
`bin/magento dev:urn-catalog:generate .idea/misc.xml`
and then inspect any 3rd party XML files via PHPStorm, it should actually highlight the errors.

**Comment by rendyep** [comment]
It solved itself after upgrading to 2.1.5, what a magic.

**Comment by rajpal-majoka** [comment]
apache resart fixes it.
