### ISSUE TITLE
Product import isn't compatible with staging (scheduled updates)

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#8547]
### Preconditions

1. Enterprise 2.1.2+ 

### Steps to reproduce

**Problem 1** - Imported changes are reverted when scheduled update is finished and import was done when an update was active or not started yet:
1. Schedule any update for a product using "Schedule New Update" button
2. When the update isn't finished yet, update the product using the Import (SYSTEM -> Import -> Products)
3. Wait until update is finished
4. You will see that updates done by the import gone like there was no any import

**Problem 2** - Imported changes overwrite an update:
1. Schedule price update for a product using "Schedule New Update" button
2. Import new price for the product when update is active
3. You will see imported price on FE but not scheduled like there is no any scheduled update

**Problem 3** - Imported changes are reverted when scheduled update is active:
1. Schedule any update for a product using "Schedule New Update" button
2. When update isn't started yet, update the product using import
3. Wait until update become active
3. You will see old values on FE like there were no any import 

### Expected result
1) Imported values should become visible after import
2) Any imported value shouldn't be reverted later
3) Import shouldn't touch attributes which were really changed in a scheduled update

**Comment by korostii** [comment]
I've heard the enterprise support tickets might get faster responses from Magento, Inc. rather than GitHub issues. I would kindly suggest that you raise this issue that way as well in order to have a faster resolution.
Here's an example of a response such tickets typically get over here:

> Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users.

**Comment by magento-engcom-team** [comment]
@vesan-83, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by J-Fricke** [comment]
While it makes sense to have Enterprise users report issues there. The issue may affect both versions of the software and the visibility of things getting fixed is really nice in GitHub. I'm curious if these issues are solved as we are finding other things with Scheduled Updates.
