### ISSUE TITLE
Plugins / interception and protected methods

### ISSUE THREAD

**Issue by mage-eag** [magento/magento2#855]
The interception feature seems to be a really interesting alternative to the rewrites of M1 (especially the configuration inheritance part), but as it is not appliable to protected methods (what is understandable), is there still a solution to redefine the behaviour of  protected methods ?

**Comment by orlangur** [comment]
Preferences must not be used for class rewriting, as it was in M1, indeed.

>  is there still a solution to redefine the behaviour of protected methods ?

While technically it is possible via preferences normally you should not rely on internal class implementation and only touch public class methods.
