### ISSUE TITLE
SQL statment at the top of my page for product pages

### ISSUE THREAD

**Issue by mrk-i** [magento/magento2#8550]
### Preconditions

1. Ubuntu 16.04 LTS
2.  aws RDS MySQL 5.6.27

### Steps to reproduce

1.  log as root
2.  bin/magento deploy:mode:set developer
3. bin/magento maintenance:enable
4. bin/magento deploy:mode:set production

### Expected result

1.  there shouldn't be a SQL query on the top of my product pages:

### Actual result

1. <link  rel="shortcut icon" type="image/x-icon" href="https://www.urlofwebsite.com/media/favicon/stores/1/index.png" />
        SELECT `e`.*, `at_product_id`.`product_id` FROM `catalog_category_entity` AS `e`
 INNER JOIN `catalog_category_product` AS `at_product_id` ON (at_product_id.`category_id`=e.entity_id) WHERE (at_product_id.product_id = '1526')<link href='https://fonts.googleapis.com/css?family=Lato:200,200italic,300,300italic,400,400italic,500,500italic,600italic,600italic,700,700italic,800,800italic,900,900italic&amp;subset=latin,cyrillic-ext,cyrillic,greek-ext,greek,vietnamese,latin-ext' rel='stylesheet' type='text/css' />
<script type="text/javascript">
	var ThemeOptions = {
		box_wide: 0,
		rtl_layout: 0,
		sticky_header: 0		
	}; 
	</script>
2. https://snag.gy/QKwUgZ.jpg
3. https://snag.gy/01yRib.jpg

**Comment by will-b** [comment]
@mrk-i 
Are you using a theme that you made your self or a theme bought from a vendor?
Does the error show when switching to the magento lume theme? If not please contact the theme vendor
and please close the ticket as there is a good chance it is to do with your theme are a custom module or a module shipped with the theme.

**Comment by vityakopin** [comment]
Unfortunately, I could not reproduce the issue as you described it. If problem is actual please identify the version of Magento that this issue occurs on. Is this issue reproduced on default Magento theme?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
