### ISSUE TITLE
CSS Minifying not compatible with CSS3 calc() function

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#8552]
### Preconditions
1. I use Magento 2.1.4 and the following extension: https://github.com/Magenerds/PageDesigner
2. CSS Minifying and Merging is enabled in system configuration

### Steps to reproduce
1. Install the extension mentioned above OR inject your own CSS using [calc()](http://caniuse.com/#search=calc). You can [see here](https://github.com/Magenerds/PageDesigner/blob/master/view/adminhtml/web/css/pd-ui.css) the calc() css of the mentioned extension
2. Open the site where this css gets rendered (for the extension it is a cms page in the backend)

### Expected result
1. The minified css should be `calc((100% / 12 * 1) - 10px);`

### Actual result
1. The minified css is instead `calc((100%/12*1)- 10px);` (no whitespaces) and therefore it will not be rendered correctly.

**Comment by sippsolutions** [comment]
Can be reproduced. The magento minifying process seems to remove whitespace inside the calc()-statement.

**Comment by KrystynaKabannyk** [comment]
hello @sydekumf, thank you for the report, the internal ticket is created MAGETWO-66482.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67487
