### ISSUE TITLE
Error while trying to access Store > Configuration

### ISSUE THREAD

**Issue by kamaleshdubey** [magento/magento2#8555]
### Preconditions

1. Magento CE v2.1.4
2. 

### Steps to reproduce

1. Log into Magento 2 Admin.
2. Click on Stores > Configuration.
3. 

### Expected result

1. The Stores Configuration page should be displayed.

### Actual result

1. An error page is displayed with the following message: "Notice: Undefined index: id in //vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 59"
2.  The above-mentioned line states `$this->_lastId = $lastElement['id'];`

How can this issue be resolved?

Regards
Kamalesh.

**Comment by vzabaznov** [comment]
Hi @kamaleshdubey, I've checked this issue and all works correct, seems like you don't install Magento properly, please be sure that all dependencies installed

**Comment by kamaleshdubey** [comment]
@vzabaznov where did you check this issue? I have had to uninstall Magento due to this and other very weird and unexpected happenings (all very frustrating I can assure you) which even a young platform like Grav does not suffer from.

**Comment by korostii** [comment]
@kamaleshdubey if you're looking for a more predictable build to base on, I've heard lots of great stuff about Magento's 1.9 branch. Using it might be a wiser choice until 2.x versions get stable enough for production use.
Which, judging by the current pace of bugfixing, may very well take a few more months, easy.

**Comment by vrann** [comment]
@kamaleshdubey this issue is not reproducible on bare Magento. Please feel free to reopen with more details on the installation:
- was installed with the Composer?
- did you run any tools?
- do you have custom modules?

**Comment by peterjaap** [comment]
We just ran into this and turns out it was an extension that had a `<section>` defined in `etc/adminhtml/system.xml` that pointed to a `<tab>` that didn't exist. Adding the `<tab>` section fixed it;

```
        <tab id="your_tab_id" translate="label">
            <label>Your Tab</label>
        </tab>
```
