### ISSUE TITLE
"customer_index_index: Please correct the XML data and try again" in backend Magento 2

### ISSUE THREAD

**Issue by atul88** [magento/magento2#8556]
Magento2 version - 2.1.4
PHP-7.0.15
MySql - 5.6.33

Steps -  
1 - I have created custom customer attribute by using new module and execute our module using setup:uprade . It executed and newly attribute created and showing in eav_attribute table. 
2 - As I have setted to show newly created attribute in two form -  'adminhtml_customer', 'customer_account_create'. So, attribute respective entry showing in 'customer_form_attribute' table. 
3 -  To do above process I followed the below commands step- 
sudo chmod -R 0777 var/
sudo chmod -R 0777 pub/
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
sudo chmod -R 0777 var/
sudo chmod -R 0777 pub/
php bin/magento cache:flush
4 - All done site is running fine. But as I go to admin->customers->All Customers, its give me 500 error. As I check in log file its showing below error -

```
main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_518574bb8b0fd6fa628f8c37dcd7903e2 and handles default, customer_index_index: Please correct the XML data and try again.  [] []
main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_5cf9ab1b1723bedc1dcd665a812b00335 and handles admin-1column: Please correct the XML data and try again.  [] []
main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] [] 
```

here I am attaching my module that I have created. one more thing If I am deleting newly created attribute from 'eav_attribute' its working fine.
Don't know something I am missing in code or its something else. please help me to sort out this. 

[code.zip](https://github.com/magento/magento2/files/776129/code.zip)

**Comment by voleye** [comment]
Hi @atul88, I see an error `PHP Fatal error:  Call to undefined method Magento\Config\Model\Config\Source\Yesno::setAttribute() in .../app/code/Magento/Eav/Model/Entity/Attribute/AbstractAttribute.php on line 547`

Try to replace `Magento\Config\Model\Config\Source\Yesno` to `Magento\Eav\Model\Entity\Attribute\Source\Boolean`

**Comment by vrann** [comment]
@atul88 please reopen if issue is not fixed by the comment above.
