### ISSUE TITLE
Admin custom settings not moved properly

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#8557]
### Preconditions

1. Magento 2.1.2
2. 

### Steps to reproduce

1. Create custom settings in system.xml
2. Enter some value and save the custom settings.
3. Create a new `<group>` and move one of the `<field>` elements from step 1 into this group.

### Expected result

1. On the admin site the field should be moved from one group to the other.

### Actual result

1. The field is duplicated instead of moved.

It seems like when data is committed to the database already, the field remains instead of getting "moved" to the new group, even if the id remains the same.

**Comment by vrann** [comment]
@thdoan in order to remove the field from the place where it was before, you need to remove the value for that field from the database. Magento cannot just drop the value because it might cause the loss of the data. You can add Data Upgrade script to your module in order to remove the value.

**Comment by thdoan** [comment]
@vrann I delete the duplicate field from `core_config_data` and cleared caches, but the field is still showing in Admin. Is there a step I'm missing?
