### ISSUE TITLE
Docker Magento 2.1.4 Custom Theme not showing in the admin - big issue

### ISSUE THREAD

**Issue by kamleshyaduwanshi** [magento/magento2#8559]
Hello World!

I am working on the Magento 2.1.4 with docker setup, and getting a big issue while creating a custom theme. I am 100% sure that I am adding composer.json, registration.php and theme.xml with the very proper manner as described in the docs.

I am experience following issues:
1. The issue is that the custom theme not showing in the admin section to configure.
2. Under pub folder 'static' directory is not available. even I run the magento setup upgrade, re run compile, cache clear and all.

Please help me to resolve it very quickly.

Thanks in advance.

**Comment by kamleshyaduwanshi** [comment]
Also I have run the static content deploy, flush magento catche, magento setup upgrade, re run compile etc.
It seems the big issue in this version?

**Comment by drkaff** [comment]
I had a similar problem. I built my module in the /vendor/magento/mytheme. 


I just copied it and pasted it into /app/design/frontend/Magento and it worked. 

Maybe I'm silly but there are too many places to have files in this.

**Comment by shavounet** [comment]
I had an issue with the "static content deploy" CLI, which did not list themes that does not contains content in the "web" folder...
Indeed, I used a theme using only layout and templates, but no "web" content... Is that your case ? An empty file in "web" solved my problem

**Comment by veloraven** [comment]
@kamleshyaduwanshi thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
