### ISSUE TITLE
Multiple Copy To Addresses

### ISSUE THREAD

**Issue by Me7z** [magento/magento2#8561]
I wanted to add multiple Copy To Mail Adresses for order confirmation. Magento only takes the first one the others are ignored. Any idea why this is happening ?

**Comment by veloraven** [comment]
@Me7z thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
