### ISSUE TITLE
Magento compatibilty issues with PHP 7.1 

### ISSUE THREAD

**Issue by anujeetphj** [magento/magento2#8569]
My Magento version is 2.1.3
Php version 7.1.1

At first place when I installed Magento with PHP 7.1 ut does not give any errors. But suddenly from today there are warnings coming for depreciatesd functions specifically (mcrypt/mdecrypt) functions in Magento/framework...Crypt.PHP file. If it doesn't support a certain PHP verSion, why didn't it give me warning in the first place while installation?

**Comment by orlangur** [comment]
According to https://github.com/magento/magento2/blob/develop/composer.json#L11 you should not be able to install :) Is there a bug in installer or you did some `composer install --ignore-platform-reqs` ?

> suddenly from today there are warnings coming for depreciatesd functions specifically

Most likely you changed `display_errors` setting. This could be suppressed by something like https://github.com/magento/magento2/issues/5880#issuecomment-268316245.

There are a bunch of issues regarding desired PHP 7.1 support reported already.

**Comment by anujeetphj** [comment]
That's strange.


Completely fed up from Magento2

With Best Regards

Anujeet Kaur

**Comment by anujeetphj** [comment]
I'm having Magento 2.1.3

If you see

"name": "magento/magento2ce",
    "description": "Magento 2 (Community Edition)",
    "type": "project",
    "version": "2.2.0-dev",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],

Its for Magento 2.2.0



With Best Regards

Anujeet Kaur

**Comment by orlangur** [comment]
@anujeetphj any reason to use PHP 7.1 instead of 7.0 at the moment?

**Comment by orlangur** [comment]
I don't see `require` section in your `composer.json`, here is the correct one: https://github.com/magento/magento2/blob/develop/composer.json

2.2.0 is not released yet by the way, only available in dev branch.

**Comment by anujeetphj** [comment]
I'm using Opensuse 42.1 Leap operating system and I faced great
difficulties while installing your specified versions 7.0.2, 7.0.4 , 7.06


These are unstable for openSUSE Leap 42.1

With Best Regards

Anujeet Kaur

**Comment by orlangur** [comment]
For 2.1.3 PHP 7.1 should not pass system requirements check too: https://github.com/magento/magento2/blob/2.1.3/composer.json#L11

**Comment by orlangur** [comment]
Not 7.0.6 is recommended, but 7.0.6 _and higher_. Any version higher than 7.0.6 in 7.0.x will pass `~7.0.6` constraint.

**Comment by anujeetphj** [comment]
I will check the composer.JSON at my end and will update the issue with the
relevant code. So that issue can be resolved.

With Best Regards

Anujeet Kaur

**Comment by avoelkl** [comment]
Why are you using PHP 7.1 @anujeetphj ?

According to the [DevDocs](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) it's not supported yet: 

> Not supported by any 2.1.x version:
> 
> PHP 7.1
> PHP 5.5

**Comment by vrann** [comment]
@anujeetphj closing as an issue with unsupported PHP version. In the latest develop there were couple of fixes related to PHP 7.1

**Comment by markshust** [comment]
This ticket should be reopened. This error still happens when attempting to install 2.1.6:

```                                                                                                                                     
  [Exception]                                                                                                                              
  Deprecated Functionality: Function mcrypt_module_open() is deprecated in /var/www/html/vendor/magento/framework/Encryption/Crypt.php on  
   line 54       
```

**Comment by vrann** [comment]
@markoshust 7.1 is not supported in 2.1.6, please see the link above

**Comment by cscd98** [comment]
This needs to be resolved in 2.1 branch! Who knows how long 2.2 will take?

**Comment by markshust** [comment]
FYI here is the actual ticket to reference now: https://github.com/magento/magento2/issues/5701

I agree with @craigcarnell -- this is a bug/flaw and shouldn't wait for a major release. Considering the above ticket is almost a year old, and PHP 7.1 was released 6 months ago... what is taking so long here? This could be classified as a pretty urgent/security fix. The additional overhead we are seeing of Magento 2 falling behind current versions of PHP is also super concerning.

**Comment by orlangur** [comment]
> This could be classified as a pretty urgent/security fix

Actually, not. Upstream Magento still uses `mcrypt` but suppresses notices so that system is still workable under PHP 7.1. This obviously will not work for PHP 7.2, where `mcrypt_*` functions are going to be removed, but is absolutely fine for now.

Maybe somebody from community is willing to backport such fix to 2.1?

**Comment by southerncomputer** [comment]
You can use the develop patches to insert @ sign in front of every mcrypt* function to stop the warnings, but you have to change the VOID to VOIDACTION controllers as well since void is reserved in 7.1 - same patches for develop work for 2-1!

**Comment by shinji-sakai** [comment]
hello @orlangur 
I am using Magento 2.1.5.
When i install it, I got the `PHP Version Check` at the first step.
My PHP version is 7.1.1
according to you, I can't find `https://github.com/magento/magento2/blob/2.1.3/composer.json#L11`
where can I find it?
plz, help me :)

Thanks,
Shinji 👍

**Comment by southerncomputer** [comment]
there are also a few areas where slack typing fails under php-7.1 iirc. Rendering totals maybe in a non-magento module or customization!

You should not attempt to use php 7.1.x with Magento 2.1.x - if you cannot figure out how to get past the PHP Version check! STOP!

**Comment by shinji-sakai** [comment]
thanks @southerncomputer 
then, which version do i have to use?
can you tell me about it?

Regards, :)

**Comment by southerncomputer** [comment]
PHP 7.0.21 or PHP 5.6.31 have the latest security patches and are compatible with Magento 2.1 - i'd suggest 7.0.21 - btw 7.1.1 is very old and has security issues itself! 7.1.7 is latest!

google how to upgrade to latest version of php 7.0 on centos 7 - for walk through assuming you have centos 7 as an os!

**Comment by shinji-sakai** [comment]
thanks very much! you're good! 👍

**Comment by orlangur** [comment]
@shinji-sakai you looked into the right `composer.json`, but PHP 7.1 support was not backported to 2.1.x (and there are no plans to backport it according to responses from Magento crew here).

@markoshust PHP 7.1 support in Magento 2.2.x has nothing to do with security as it simply suppresses warnings generated by `mcrypt_*` calls. Upgrading to the last PHP 7.0.x and even 5.6.x is the right way to go.

**Comment by ruCyberPoison** [comment]
PHP Version Check
Your PHP version is 7.1.8-1ubuntu1. The required PHP version is ~5.6.5|7.0.2|7.0.4|~7.0.6. 

why i get this issue ? 

some thing to fix this problem ?

**Comment by orlangur** [comment]
@Screamfox, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Most likely you use Magento 2.1.x which does not support PHP 7.1.
