### ISSUE TITLE
Product page video not working on custom theme

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#8572]
### Preconditions
1. Magento CE 2.1.3 & CE 2.1.4
2. PHP 7

### Steps to reproduce
1. Add product video the usual way
2. Create custom catalog_product_view.xml with some modifications (moved elements, new containers etc.)

### Expected result

1. Video will load the correct way.

### Actual result

1. Video will not show, only placeholder is shown
![screen shot 2017-02-15 at 23 10 07](https://cloud.githubusercontent.com/assets/24226635/22997735/f284fbb4-f3d3-11e6-8f64-ae95123f2bb6.png)
![screen shot 2017-02-15 at 23 10 11](https://cloud.githubusercontent.com/assets/24226635/22997736/f2890e34-f3d3-11e6-806d-6bf24baf2b3a.png)

**Comment by magento-engcom-team** [comment]
@henk-hypershop, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
