### ISSUE TITLE
Can't delete item from cart is customer was deleted

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#8579]
### Preconditions
1. Magento 2.1.4 CE
2. FPC enabled

### Steps to reproduce
1. Create a user in Magento storefront
2. Add simple product to cart, go to shopping cart
3. Delete this user from Magento admin
4. Refresh shopping cart page
5. Product is still in the cart. Try to remove the product from cart.

### Expected result
1. Product removed

### Actual result
Product not removed. Error "We can't remove the item." appears.
![bandicam 2017-02-16 18-18-09-651](https://cloud.githubusercontent.com/assets/3024248/23027079/53701dbe-f474-11e6-81e4-8bd398215faa.png)

**Comment by stasleo** [comment]
Please also take a look at the header. It displays "Welcome, John" and "Sign in" and "Create an account" links :)

**Comment by stasleo** [comment]
Also, when I go to Reports > Abandoned Carts, it displays a record, but I click on it, it shows error "Something went wrong while editing the customer."

**Comment by orlangur** [comment]
>  It displays "Welcome, John" and "Sign in" and "Create an account" links :)

Because such data is stored in browser local storage.

> Delete this user from Magento admin

I'm not sure that this functionality has already been implemented (aka "push notifications triggered by admin changes"). @antonkril, can you share some insight on whether it is implemented/planned in some form?

**Comment by antonkril** [comment]
@orlangur, not implemented yet, but planned.

**Comment by magento-engcom-team** [comment]
@stasleo, thank you for your report.
We've created internal ticket(s) MAGETWO-80424 to track progress on the issue.

**Comment by orlangur** [comment]
Let's track this issue under https://github.com/magento/magento2/issues/3625.
