### ISSUE TITLE
Can not edit the copyright footer on magento version 2.1.3

### ISSUE THREAD

**Issue by stephennguyen1803** [magento/magento2#8583]
Copyright on footer is not working
### Preconditions

1. Mangento version 2.1.3
2. PHP Version 7.0.15

### Steps to reproduce

1. go to Content -> Configuration -> Foorter
2. Edit  Copyright
3. Save and clear cache

### Expected result

1. It will display the right copyright (like admin)
http://prntscr.com/e9rmmj

### Actual result

1. But it displays default message
http://prntscr.com/e9rmua

**Comment by pboisvert** [comment]
@stephennguyen1803 is it possible the theme you are using is not referencing the Footer field and is just using a hard coded value in the theme itself? The "default" message is not  Magento default but seemingly that set by the theme provider.

**Comment by stephennguyen1803** [comment]
@pboisvert 
Thank you for you help. But I found the issue, it works normally, when I clear cache server
