### ISSUE TITLE
Magento 2 sites not working according to configuration settings.

### ISSUE THREAD

**Issue by ajaykrshukla** [magento/magento2#8584]
I am getting weird things on my Magento 2.1.4 site.  Many of my configurations that I had set in the back-end is not working on the front-end accordingly. Also, sometimes the configuration settings for e.g. for payment API get lost when I am trying to save other fields on the page.

Can anyone suggest what I can do so that things work according to configuration?

Thanks

**Comment by pboisvert** [comment]
@ajaykrshukla Can you follow the issue reporting guidelines in terms of providing pre-conditions, system information, and clear steps to reproduce the issue you are seeing. This report is not enough for a team to investigate

**Comment by ajaykrshukla** [comment]
Hello @pboisvert,

Thanks for your reply.

Actually I am getting the issue at many instances like when I set the Allowed countries for store 1 to "US" only from the backend and then I see the store on frontend registration page, I am seeing all the countries coming on the country dropdown instead of only one that is "US".

Please check it from the screenshot as well.

I have also checked from the code point of view that is from vendor/magento/module-directory/Model/ResourceModel/Country/Collection.php toOptionArray() method and unfortunately it is also returing the whole list of countries instead of just one that is "US". I have even check from  database config table for store allowed countries and it is showing just US so wondering what is going wrong with the country Collection class!

Please let me know what i can do to fix this. I have migrated from Magento 2.1.2 to Magento 2.1.4

Thanks
![countrydowpdown](https://cloud.githubusercontent.com/assets/25296694/23093529/4e23699e-f60c-11e6-984e-e7ab3c4312a7.png)

**Comment by veloraven** [comment]
@ajaykrshukla if this issue is still actual please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
