### ISSUE TITLE
Admin Language Fallback in 2.1.3

### ISSUE THREAD

**Issue by mhauri** [magento/magento2#8585]
### Preconditions

1. Magento: 2.1.3
2. Application Mode: Production

### Steps to reproduce

1. Login into the Backend/Admin
2. Goto Account Settings and Choose an Interface Locale, like: de_CH
3. Save Account

### Expected result

1. Shows the Backend/Admin with Fallback Language when the selected Language isn't installed/deployed as it was in 2.1.2

### Actual result

1. JS and CSS Resources aren't loaded (Error 404)
<img width="884" alt="bildschirmfoto 2017-02-17 um 10 01 56" src="https://cloud.githubusercontent.com/assets/402069/23059185/8e4dec3e-f4f8-11e6-874a-0ea26b3a70d4.png">

**Comment by rganin** [comment]
Thank you for reporting. Internal ticket: MAGETWO-60631.

**Comment by magento-engcom-team** [comment]
@mhauri, thank you for your report.
We've created internal ticket(s) MAGETWO-60631 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @mhauri 
This issue seems to be fixed now in 2.2 and 2.3.

Closing this ticket now. Please feel free to reopen if the issue persists.
