### ISSUE TITLE
Catalog filter is not display after add custome product_listing.xml in my module

### ISSUE THREAD

**Issue by vnahalpara** [magento/magento2#8586]
I am trying to add new column in magento 2.1.3 admin -> Catalog -> Product grid

I used following code to display sale column in product grid

    <?xml version="1.0" encoding="UTF-8"?>
    
    <listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
        <columns name="product_columns" class="Magento\Catalog\Ui\Component\Listing\Columns">
            <column name="sale">
                <argument name="data" xsi:type="array">
                    <item name="config" xsi:type="array">
                        <item name="filter" xsi:type="string">select</item>
                        <item name="add_field" xsi:type="boolean">true</item>
                        <item name="label" xsi:type="string" translate="true">Sale</item>
                        <item name="options" xsi:type="array">
                            <item name="disable" xsi:type="array">
                                <item name="value" xsi:type="string">1</item>
                                <item name="label" xsi:type="string" translate="true">Active</item>
                            </item>
                            <item name="enable" xsi:type="array">
                                <item name="value" xsi:type="string">0</item>
                                <item name="label" xsi:type="string" translate="true">Deactive</item>
                            </item>
                        </item>
                        <item name="sortOrder" xsi:type="number">75</item>
                    </item>
                </argument>
            </column>
        </columns>
    </listing>

I have put this code in view/adminhtml/ui_component/product_listing.xml
Issue is when i used this product_listing.xml file product grid filter not displayed and when i click on filter icon filter is display on bottom of grid.

See here http://magento.stackexchange.com/questions/160220/filter-is-not-display-after-custome-product-listing-xml

**Comment by veloraven** [comment]
@vnahalpara thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
