### ISSUE TITLE
Magento_Catalog: Image attribute should have different parent class

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#8587]
Currently the 'Magento\Catalog\Model\Product\Attribute\Frontend\Image' model is inheriting from the abstract class 'Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend'.

The class should inherit from 'Magento\Eav\Model\Entity\Attribute\Frontend\DefaultFrontend' instead (which inherits from the abstract). This would be more consistent with other frontend attributes (like datetime) and more flexible in extending the functionalities of the frontend attributes.

### Preconditions
1. PHP7.0
2. MG2.1.2, MG2.1.3, MG2.1.4

### Steps to reproduce
1. Look at file Magento\Catalog\Model\Product\Attribute\Frontend\Image

### Expected result
1. class should inherit from Magento\Eav\Model\Entity\Attribute\Frontend\DefaultFrontend

### Actual result
1. class inherits from Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend

This fix would allow more flexibility when adding functionalities on the frontend attributes. You would not have to provide an extra preference to fix the 'incorrect' parent class for the image attributes.

An example of where this is already done in the core:
Magento\Eav\Model\Entity\Attribute\Frontend\Datetime

**Comment by maghamed** [comment]
@koenner01  Why do you need Image to be successor of DefaultFrontend?

> An example of where this is already done in the core:
> Magento\Eav\Model\Entity\Attribute\Frontend\Datetime

We don't have these neither in 2.0.*
https://github.com/magento/magento2/blob/2.0.13/app/code/Magento/Eav/Model/Entity/Attribute/Frontend/Datetime.php#L11
nor in 2.1.*
https://github.com/magento/magento2/blob/2.1.4/app/code/Magento/Eav/Model/Entity/Attribute/Frontend/Datetime.php#L11
nor in develop branch 
https://github.com/magento/magento2/blob/develop/app/code/Magento/Eav/Model/Entity/Attribute/Frontend/Datetime.php#L11

Actually for now Magento\Eav\Model\Entity\Attribute\Frontend\DefaultFrontend  class doesn't have any successor.

Currently the only place where Default Frontend class is used is in the AbstractAttribute class
```
    /**
     * Retrieve frontend instance
     *
     * @return \Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend
     */
    public function getFrontend()
    {
        if (empty($this->_frontend)) {
            if (!$this->getFrontendModel()) {
                $this->setFrontendModel($this->_getDefaultFrontendModel());
            }
            $this->_frontend = $this->_universalFactory->create($this->getFrontendModel())->setAttribute($this);
        }

        return $this->_frontend;
    }
```

and this behavior looks correct for me.
What customization abilities you are losing, having such hierarchy of inheritance ? 

Magento discourages usage of inheritance. So, a deep inheritance tree is a "smell" from architectural point of view.

**Comment by koenner01** [comment]
Yes, weird. I will check which version I was working on where the DateTime had a different parent class.

The logic behind this was to expose the publics methods so they can have plugins injected, because you can't plugin an abstract class.

We (and probably other people) are inserting custom logic into all EAV attributes and the most logic place to do this was in the DefaultFrontend. Should we set a preference instead on the abstract class ?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-64844

**Comment by magento-engcom-team** [comment]
Hi @koenner01 
We are closing the issue. Related PR has been rejected
