### ISSUE TITLE
Checkout shipping method is not preselected

### ISSUE THREAD

**Issue by sparrowek** [magento/magento2#8588]
### Preconditions

1. M2 v2.1.1

### Steps to reproduce

1.  Add items to cart
2. Go to /checkout/cart
3. Select shipping method

### Expected result

1. Method should be selected on Checkout page

### Actual result

1. None of the methods is selected

I found that the window.checkoutConfig.selectedShippingMethod is properly set but the code in checkout-data-resolver.js first sets it correctly like this:
```
                if (!availableRate && window.checkoutConfig.selectedShippingMethod) {
                    availableRate = true;
                    selectShippingMethodAction(window.checkoutConfig.selectedShippingMethod);
                }
```
but then sets it to true by this lines:
```
          if (!availableRate) {
                    selectShippingMethodAction(null);
                } else {
                    selectShippingMethodAction(availableRate);
                }
```

Commenting out the selectShippingMethodAction(availableRate); line solves the problem

**Comment by sparrowek** [comment]
I have realised now that commenting the line will fix the bug but introduce another :)
The correct code should be:

```
	        if (!availableRate && window.checkoutConfig.selectedShippingMethod) {
	            availableRate = window.checkoutConfig.selectedShippingMethod;
	        }

	        //Unset selected shipping method if not available
	        if (!availableRate) {
	            selectShippingMethodAction(null);
	        } else {
	            selectShippingMethodAction(availableRate);
	        }
```

**Comment by madotto** [comment]
We can't reproduce the issue in Magento 2.2.0-dev

**Comment by magento-engcom-team** [comment]
@sparrowek, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by sergiomendonca** [comment]
> I have realised now that commenting the line will fix the bug but introduce another :)
> The correct code should be:
> 
> ```
> 	        if (!availableRate && window.checkoutConfig.selectedShippingMethod) {
> 	            availableRate = window.checkoutConfig.selectedShippingMethod;
> 	        }
> 
> 	        //Unset selected shipping method if not available
> 	        if (!availableRate) {
> 	            selectShippingMethodAction(null);
> 	        } else {
> 	            selectShippingMethodAction(availableRate);
> 	        }
> ```

I see this problem in Magento 2.1.9. Selected shipping method does not work, this practitice make this thing work but i cant trust this javascript code...
