### ISSUE TITLE
Class Magento\Catalog\Model\Product\Attribute\Backend\Media not found

### ISSUE THREAD

**Issue by quagerty** [magento/magento2#8592]
### Preconditions

1. 2.1.3 CE

### Steps to reproduce

1. Created multi stores
2. Imported products to default store with images
3. Edit product in backend

### Expected result

1. View the product in admin

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/25847347/23070517/31f17566-f523-11e6-9f19-164ca0a0b1f3.png)

**Comment by magento-engcom-team** [comment]
@quagerty, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
