### ISSUE TITLE
Configurable Product in Multi language store - Product Image not updating

### ISSUE THREAD

**Issue by storepeinture** [magento/magento2#8597]
Hello,
I'm running into the following issue:
I have Magento 2.1.4 with two store views, French  (default store view) + English.

I have created a configurable product (paint) with 3 different product sizes (paint bucket sizes). Each product size has a different product image - and I want to sell this configurable product in both stores.
When I change the configurations in the French default store, the product image gets updated as intended.
But it does not update in the English store. And that's why I'm posting this here.

### Preconditions
1. Magento 2.1.4 (brand new installation)
2. Themeforest Porto Template 2.4.5 (latest version)

### Steps to reproduce
1. Setup Magento 2.1.4 with two store views (French and English)
2. **Change Scope: All Store Views**
3. Create a configurable product, with one configurable attribute, e.g. size.
4. Add a few configuration products. I am selling paint, so I have 4 different sizes of the same paint as configurations.
5. **Change Scope: French Store View**
6. Add product images (for the configurable product AND the configurations with a French label)
7. Check the French product page: When selecting a new configuration, the product image should change!
8. **Change Scope: English Store View**
9. Add different product images (for the configurable product AND the configurations with an ENGLISH label)
10. Check the English product page and see behavior

### Expected result
1. On all product pages for all languages: When selecting a new configuration, the product image shall update

### Actual result
1. The product image updates only on the French website
2. Even though the configuration options are available on the English site, the product images are NOT updating accordingly

**You can check live**
**FRENCH product page:** http://77.104.148.57/~peintur0/huile-dure-speciale.html
Here the product image updates with new configuration (wait a little for image update)

**ENGLISH product page:** http://www.organic-paints.com/hard-oil-high-performance.html
Here the product image NEVER updates

**Illustration of the problem with description:**
![multistore configurable product](https://cloud.githubusercontent.com/assets/21140651/23090015/f15d907c-f593-11e6-96ac-2a118935f6be.JPG)

**Comment by Tonop** [comment]
Hi,

Could you pls confirm or not the following similar [issue](https://github.com/magento/magento2/issues/8524).

**Comment by storepeinture** [comment]
Hi Tonop,
Thank you for your response. I have checked on issue #8524.

**In my opinion it is NOT similar. So I don't confirm.**
Why:
In #8524 it seems that there are only images shown from the parent product.

My issue here is different: You are able to see a different image for each store view.
Check the screenshot: In the French store, the product label is written in French!
In the English store, the product label is written in English!

The actual problem is that the **image-updating mechanism** seems broken. But if an image is shown, it actually belongs to the correct store view.

If I had the same problen as in issue #8524, I would only see products with French labels. But this is not the case.

**Comment by Tonop** [comment]
Could you complete steps described in my issue #8524 and post the results?

**Comment by storepeinture** [comment]
Ok, I will have a look and write my response in the other issue.

**Comment by Mizogorou** [comment]
Please check your space character in the English attribute language fields like this. I hope it will solve your problems.

![problem-swatch-image](https://cloud.githubusercontent.com/assets/8059336/23094323/2beeef02-f629-11e6-8a00-d9a6e805679c.PNG)

**Comment by storepeinture** [comment]
Hi Mozogorou,
Thanks for your help! I have checked for spaces at the end of attribute fields. I cannot find any mistake on my side, everything looks ok.
Best,
Michael

**Comment by storepeinture** [comment]
Can anybody confirm this issue?

**Comment by storepeinture** [comment]
I have digged deeper into the issue and it seems as if it's a cross-origin related problem, since both stores run on different domains (URLs).
I still haven't figured out how it might work, but if I find a solution I will post it - or if anybody else has a solution to the cross-origin problem, then I'm of course glad if I get some help ;)

Thank you!

**Comment by IlnitskiyArtem** [comment]
Hi, @storepeinture. Please add more details to your description of the steps you followed when identifying this issue. When I tried to reproduce this issue, the behavior was quite different from your's.
