### ISSUE TITLE
Import results in General Error Message

### ISSUE THREAD

**Issue by mitch-tofi** [magento/magento2#8599]
### Preconditions
1.  Magento Version 2.1,x (at the very least)

### Steps to reproduce
1.  Have a few products in the system with similar sku/url keys (that contain digits) in my case
-1076c
-1076d
-1076ch-n
-1076 <-- this is the important one
2.  attempt to add/update via the import wizard the sku with url key 1076. 
3. you will receive a general  error message

### Expected result
1.  Import successfully

### Actual result
1. Import Fails

### Solution

In the **CatalogImportExport** Module in the **Product.php** file (under **Model/Import**)
The function **checkUrlKeyDuplicates** currently gets url keys however, in the case of skus and url keys with pure numbers eg 1076, the query generated in mysql yields incorrect results

Should return No duplicates returns 3, this is due the the request_path in component of the query containing a number and not a string. 

solution replace **array_keys($urlKeys)** with **array_map('strval',array_keys($urlKeys))**

Example:

**before change**
Note that the request_path params is not quoted

`SELECT url_rewrite.request_path, url_rewrite.store_id, cpe.* 
FROM url_rewrite 
LEFT JOIN catalog_product_entity AS cpe 
ON cpe.entity_id = url_rewrite.entity_id 
WHERE (request_path IN (1076)) 
AND (store_id IN (1)) 
AND (cpe.sku not in ('1076'))`

**after change:**

`SELECT url_rewrite.request_path, url_rewrite.store_id, cpe.* 
FROM url_rewrite 
LEFT JOIN catalog_product_entity AS cpe 
ON cpe.entity_id = url_rewrite.entity_id 
WHERE (request_path IN ('1076')) 
AND (store_id IN (1)) 
AND (cpe.sku not in ('1076'))`
`

**Comment by mitch-tofi** [comment]
@joni-jones  im not sure if anyone has looked at this yet? also not sure who to tag (sorry)

**Comment by Stas94** [comment]
@mitch-tofi Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
