### ISSUE TITLE
Can bypass Minimum Order Amount Logic

### ISSUE THREAD

**Issue by ericrisler** [magento/magento2#8601]
### Preconditions
1. Magento 2.1.1
2. Theme with minicart visible during checkout (not sure if default theme does this)

### Steps to reproduce
1. Enable Minimum Order Amount in system config. (Store / Configuration / Sales / Sales / Minimum Order Amount Enable = Yes)
2. Add products to the cart until you are over min amount.
3. Click on cart and click on "View and Edit Cart"
4. Click "Check Out with Multiple Addresses" on right side of page
5. Remove few product from order, while sum of order will be less than in settings (min order amount)
6.  Then click "Update Qty & Addresses"
7. And finish order.

### Expected result
1. When hitting the Place Order button would expect to see error about min order.

### Actual result
1. Order goes through just fine.

Again, the theme must have the minicart visible during checkout and must allow for removing product.

**Comment by tomislavsantek** [comment]
Unable to reproduce.
Steps taken:

1. Enabled Minimum Order Amount in system config.
2. Added products to the cart until over min amount.
3. Went to Cart page
4. Using the minicart, removed products until the cart total was below the minimum amount.

Received Error "Minimum amount is XY"

Cart items were not changed

**Comment by maghamed** [comment]
@tomislavsantek  steps to reproduce are updated.
Sorry for inconveniences

**Comment by tomislavsantek** [comment]
Working on this @tomislavsantek

**Comment by NikhilCPatil** [comment]
working on this..

**Comment by NikhilCPatil** [comment]
Working on this..

**Comment by magento-engcom-team** [comment]
@ericrisler, thank you for your report.
We've created internal ticket(s) MAGETWO-80740 to track progress on the issue.

**Comment by RomaKis** [comment]
Seems like it is not a bug, but expected Magento behavior . If you turn on Store / Configuration / Sales / Sales / Minimum Order Amount Enable = Yes and Store / Configuration / Sales / Sales / Validate Each Address Separately in Multi-address Checkout = Yes in Magento admin, "Check Out with Multiple Addresses" works as expected.

**Comment by ishakhsuvarov** [comment]
Hi @ericrisler 
Fix for the issue is already delivered to `2.2-develop` with the commit https://github.com/magento/magento2/commit/506d5004e472f3937d4d67fefce62c9e2ce9c403

Thanks
