### ISSUE TITLE
Updating from 2.1.3 to 2.1.4 on magento

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#8605]
Magento:

I am trying to update the magento via Web setup and its giving me error

Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package magento/product-comunity-edition could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

For additional assistance, see component dependency help .

Then i tried the CLI methods too, but this is the error i am getting
[root@eme ~]$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
    - magento/product-community-edition 2.1.0 requires composer/composer 1.0.0-beta1 -> satisfiable by composer/composer[1.0.0-beta1] but these conflict with your requirements or minimum-stability.

**Comment by ebofi** [comment]
There is a typo mistake on the composer.json

**Comment by orlangur** [comment]
You need to use [weaker](https://github.com/magento/magento2/blob/develop/composer.json#L257) `minimum-stability` setting until https://github.com/magento/magento2/issues/4359 is resolved.

**Comment by magento-engcom-team** [comment]
@ebofi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9
