### ISSUE TITLE
Configurable product with custom option "file" can't be added to cart with a file

### ISSUE THREAD

**Issue by malikt** [magento/magento2#8606]
### Preconditions

1. Magento version 2.1.4
2. PHP 7.0.10
3. MySQL 5.7.14
4. Apache

### Steps to reproduce

1. Create a configurable product with custom options text, dropdowns but also add one or more "file" type options
2. reindex
3. load the product page at frontend
4. select all options along with the image file and add product to cart

### Expected result

1.  The product should add to cart, show all selected options, even the image uploaded.

### Actual result

1. The product page reloads with error message "You need to choose options for your item."

I tested the same product on Nginx server with magento version 2.1.2, it works fine but on Apache it fails. If i dont select any image and select other options only and add the product to cart, it works fine. the issue is only with option "file".

**Comment by malikt** [comment]
hi,
any suggestions

**Comment by nobuttsalex** [comment]
My colleague is having the same issue, I think it must be to do with the setup of his environment but haven't worked out what it is yet. Probably a missing PHP library or permissions on a folder.

**Comment by VasylShvorak** [comment]
@malikt  thank you for your report.
Unfortunately I was not able to reproduce this issue.
Please describe all steps you have done in more detailed way.
And if you can attach screenshot or some logs it may help as well.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by malikt** [comment]
its not working on local but works fine on live with exact replica of the site. so not worried much about it.
