### ISSUE TITLE
[Dev][Coding Standard] Hundreds of PHPCS-based static tests violations in mainline

### ISSUE THREAD

**Issue by orlangur** [magento/magento2#8612]
This issue is NOT about `@codingStandardsIgnoreFile` evil annotation appearing quite often: http://prnt.sc/eawtih
The problem is that even except those 666 ignored files there are a lot of not coding standard compliant files due to holes in CI processes and/or bugs in `get_changed_files` mechanism. This is even more strange as "bump copyright year" commit changed all the files and still didn't reveal these violations.

### Preconditions

Use `develop` branch 

### Steps to reproduce

Run PHPCS-based tests against full codebase

### Expected result

PHPCS-based tests are green

### Actual result

https://travis-ci.org/orlangur/magento2/jobs/203250472
```
1) Magento\Test\Php\LiveCodeTest::testCodeStylePsr2
PHP Code Sniffer has found 16 error(s):
2) Magento\Test\Php\LiveCodeTest::testCodeStyle
PHP Code Sniffer has found 176 error(s): 
3) Magento\Test\Php\LiveCodeTest::testAnnotationStandard
PHP Code Sniffer has found 168 error(s): 
```

# Solution
As it turned out, running PHPCS against full codebase takes less than **5 minutes**: https://travis-ci.org/orlangur/magento2/jobs/203222909#L554

I propose to remove buggy `get_changed_files` mechanism for PHPCS-based tests as it does not bring any notable value currently but causes troubles.

I would like to prepare a pull request implementing this approach and eliminating all existing violations if you don't mind.

**Comment by orlangur** [comment]
Regression occurred. Looks like `Magento\Test\Php\LiveCodeTest` is now broken and does not check against the full codebase.

### Steps to reproduce
Run `./vendor/bin/phpcs --standard=dev/tests/static/framework/Magento/ruleset.xml {app,dev,lib/internal} -n --extensions=php,phtml --report=json | less`

### Expected result
PHPCS-based tests are green

### Actual result
`{"totals":{"errors":21638,"warnings":0,"fixable":21467}`

### What needs to be done
1. Fix phpcs-based static test so that it is checking the full codebase again
2. Eliminate coding style violations

I'm going to take care of it this weekend or earlier if I have some spare time.

**Comment by magento-engcom-team** [comment]
@orlangur Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@orlangur Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97233` were created

**Comment by okorshenko** [comment]
Hi @orlangur 
Thank you for working on this. We are looking for your PR
