### ISSUE TITLE
Couldn't get available versions for package magento/framework-foreign-key

### ISSUE THREAD

**Issue by Maddy0404** [magento/magento2#8613]
![2017-02-20_11-30-38](https://cloud.githubusercontent.com/assets/25893578/23113745/2e548d64-f760-11e6-9a96-f203dd14eb30.png)

**Comment by EmilObermayr** [comment]
We are having the same issue. It is a test-installation in a LAN behind a NAT-Router, just in case this is relevant.

**Comment by veloraven** [comment]
@Maddy0404 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by magento-engcom-team** [comment]
@Maddy0404 thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
