### ISSUE TITLE
Apply coupon code button issue on Checkout

### ISSUE THREAD

**Issue by nilesh2jcommerce** [magento/magento2#8618]
### Preconditions

1. Magento CE 2.1.4, PHP Version 7.0.14, MYSQL Version 5.6.31-77.0

### Steps to reproduce

1. On Cart page when Applying Coupon Code it applied successfully and working properly.
2. When Moving to checkout page for placing order on payment section in discount field coupon code present already but it not applied due to that button saying apply coupon.

### Expected result

1. If coupon code applied already on cart page so in checkout payment section coupon code button should say "cancel coupon" not "apply coupon". 

### Actual result

1.Please check Mentioned screenshot of cart and checkout page.
Cart Page : http://my.jetscreenshot.com/demo/20170220-8a34-107kb
Checkout Page: http://my.jetscreenshot.com/demo/20170220-8a34-107kb

**Comment by okorshenko** [comment]
@nilesh2jcommerce thank you for reporting the issue
@mcspronko thank you for fixing this issue in develop branch. PR: magento/magento2#8759

**Comment by nilesh2jcommerce** [comment]
Hi @okorshenko 
Yeah i uploaded patch in my site and its seems working.Thank you @okorshenko to looking into this and @mcspronko to fix this issue.

**Comment by shansari25** [comment]
dear @nilesh2jcommerce , @JamelleG , @mcspronko , @okorshenko - 

how did you fix this issue, we are also facing the same problem in magento 2.2.4 version.
