### ISSUE TITLE
Notice: Array to string conversion in /example.com/vendor/magento/framework/View/Page/Config/Renderer.php on line 321

### ISSUE THREAD

**Issue by spyhunk** [magento/magento2#8619]
### Preconditions

1. Magento 2.1.2
2. PHP 7

### Steps to reproduce

1. Error occurs right after changing front-end development workflow from server side to client side.
2. I already have an issue with products>category page which is showing error 500 page isn't working.
3. Magento also had porto installed but uninstalled it due to some issues in theme via removing files, removing modules/theme row from the database. 

### Expected result

1. Change the front-end development workflow.
2. For customizing Luma for fixing minicart, which will stay blank after adding products or not even move to cart page.

### Actual result

1. Notice: Array to string conversion in /example.com/vendor/magento/framework/View/Page/Config/Renderer.php on line 321

**Comment by alexhadley** [comment]
Was there any solution to this?

I'm getting this when going into production mode.

**Comment by bassplayer7** [comment]
@alexhadley, for production mode, you shouldn't be using client side compilation anyways. You can resolve this issue by turning that off. You can delete the row(s) with this path from the `core_config_data`: `dev/front_end_development_workflow/type`

**Comment by rustsol** [comment]
Thanks @bassplayer7 for the solutions, i have changed the type to server_side_compilation and it worked after cleaning var/cache page_cache and generation.

**Comment by orlangur** [comment]
@bassplayer7, nice catch. I believe some validations needs to be added if they are currently missing:
- disallow chaging compilation to client-side if production mode is turned on
- disallow switching to production mode (or maybe automatically turn on served-side compilation with some warning) in case client-side compilation is turned on

**Comment by hostep** [comment]
@orlangur, that's one of the things which will change in Magento 2.2, according to the devdocs section around the [pipeline deployment](http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/technical-details.html):
> We changed the following behavior in the Magento Admin in production mode:
> - You cannot enable or disable cache types in the Admin
> - Developer settings are unavailable (Stores > Settings > Configuration > Advanced > Developer), including:
> 
>   - Minify CSS, JavaScript, and HTML
>   - Merge CSS and JavaScript
>   - Server-side or client-side LESS compilation
>   - Inline translations
> 
> ...

I'm assuming all those settings will be set to best practices settings once running in production mode.

**Comment by orlangur** [comment]
Closing as the fix for this issue is already available on Magento 2.2.0 branch.

@hostep thanks for your finding 👍

**Comment by nmallepally** [comment]
@orlangur  Hi , I have similar issue on Magento 2.1.8 not sure if this is the same.
I haven't changed any front end development work flow, it has been the same from starting.
I see a lot of them on exception log, can you advise, is there any fix around.

2017-10-13 07:20:01] main.CRITICAL: Exception: Notice: Array to string conversion in /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2929 in /var/www/vhosts/magento2.1.8//httpdocs/vendor/magento/framework/App/ErrorHandler.php:61$
Stack trace:
#0 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2929): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/vhosts...', 2929, Array)
#1 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(168): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Array)
#2 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(728): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Magento\Quote\Model\Quote\Addres$
#3 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(784): Magento\Framework\Model\ResourceModel\Db\AbstractDb->prepareDataForUpdate(Object(Magento\Quote\Model\Quote\Address\I$
#4 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(403): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Magento\Quote\Model\Quote\Address\Intercept$
#5 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Quote\Model\Quote\Address\Interceptor))
#6 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Quote/Model/Quote/Address/Interceptor.php(1649): Magento\Framework\Model\AbstractModel->save()
#7 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/ShippingAddressManagement.php(125): Magento\Quote\Model\Quote\Address\Interceptor->save()
#8 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('1654', Object(Magento\Quote\Model\Quote\Addr$
#9 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(110): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quot$
#10 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentPersister.php(34): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentProcessor->save(Object(Ma$
#11 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(133): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentPersister->save(Object(Magento\Quote\Model\Quote\$
#12 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(106): Magento\Quote\Model\QuoteRepository\SaveHandler->processShippingAssignment(Object(Magento\Quote\Model\Quote\Inte$
#13 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository.php(161): Magento\Quote\Model\QuoteRepository\SaveHandler->save(Object(Magento\Quote\Model\Quote\Interceptor))
#14 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(76): Magento\Quote\Model\QuoteRepository->save(Object(Magento\Quote\Model\Quote\Interceptor))
#15 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-checkout/Model/ShippingInformationManagement.php(156): Magento\Quote\Model\QuoteRepository\Interceptor->save(Object(Magento\Quote\Model\Quote\Interceptor))
#16 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Checkout\Model\ShippingInformationManagement->saveAddressInformation('1654', Object(Magento\Checkout\Model\ShippingIn$
#17 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callParent('saveAddressInfo...', Array)
#18 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'saveAddressInfo...', Object(Magento\Checkout\$
#19 /var/www/vhosts/magento2.1.8/httpdocs/app/code/Amasty/Orderattr/Plugin/Order/ShippingInformationManagement.php(37): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->Magento\Framework\Interception\{closure}$
#20 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Amasty\Orderattr\Plugin\Order\ShippingInformationManagement->aroundSaveAddressInformation(Object(Magento\Checkout\Model\Ship$
#21 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressIn$
#22 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-checkout/Model/GuestShippingInformationManagement.php(44): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->saveAddressInformation('1654', Object$
#23 [internal function]: Magento\Checkout\Model\GuestShippingInformationManagement->saveAddressInformation('17c537ade1cf4e3...', Object(Magento\Checkout\Model\ShippingInformation))
#24 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#25 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#26 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#29 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#30 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#31 /var/www/vhosts/magento2.1.8/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#32 {main} [] []


we are in the production environment.

**Comment by orlangur** [comment]
> 2017-10-13 07:20:01] main.CRITICAL: Exception: Notice: Array to string conversion in /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2929 in 

This is definitely another issue, from stack trace it looks like you need to debug what went wrong during quote address saving.
