### ISSUE TITLE
 Cannot read property 'method_code' of null

### ISSUE THREAD

**Issue by carabationut** [magento/magento2#8622]
### Preconditions

1. Magento Version: 2.2.0
2. PHP -> 5.6.30
3. MySQL -> 5.6.33

### Steps to reproduce

1.  Store filled with products and the proper settings, the customer have a shipping firm that doesn't support this magento version, so I wanted to setup without a shipping form but simple fee if under price in cart.

### Expected result

1.  Should load method_code for shipping. Line 48 from 'frontend/Magento/luma/ro_RO/Magento_Checkout/js/model/cart/totals-processor/default.js'
What's the problem from my build up store?

Error: Uncaught TypeError: Cannot read property 'method_code' of null
Page: /checkout/cart

P.S. Hope for not spamming, but I am new to Magento. Thanks.

**Comment by vrann** [comment]
@carabationut please provide more exact steps to reproduce, it is hard to understand your scenario. Thanks!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
