### ISSUE TITLE
Stock status not coming back after qty update

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#8624]
### Preconditions
1. Magento Version: 2.1.3
2. PHP: 7.0.14-2a
3. MySQL: 5.6.33
4. Automatically Return Credit Memo Item to Stock (this is what I try to achieve) - ON (Stores - Configuration - Catalog - Inventory)

### Steps to reproduce
1. Set simple product qty to zero (and you will see it will turns to **Out of Stock**) & hit **Save**
2. Set same product qty to 1 and save

### Expected result
After insert qty more than zero - changed new stock status **In Stock**

### Actual result
Still **Out of Stock**

**Comment by lucscu** [comment]
Same issue when with a credit memo you return to stock a product correclty went out of stock with qty 0.
It increases its qty, **but it remains in out of stock state**, so i have to cron a script all night that put in stock all products out of stock with qty > 0.
Absolutly crazy.

**Comment by RomanKrut** [comment]
@oroskodias Thanks for reporting this issue, internal ticket was created MAGETWO-70370.

**Comment by ragboyjr** [comment]
It looks like the specific code is right here:

https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/CatalogInventory/Model/Stock/StockItemRepository.php#L165-L167

I think the easiest way to fix is if we added another if statement below like:

```php
if ($stockItem->getManageStock() && $isInStock && !$stockItem->getIsInStock()) { 
    $stockItem->setIsInStock(true)->setStockStatusChangedAutomaticallyFlag(true);
}
```

**Comment by ragboyjr** [comment]
Willing to submit a PR, but curious if anyone has any better ideas.

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.
We've created internal ticket(s) MAGETWO-70370 to track progress on the issue.

**Comment by raumatbel** [comment]
@magento-engcom-team I am working in this issue. Can you assign me please?

**Comment by raumatbel** [comment]
In this way, are you never going to have a product with qty positive and out of stock?

**Comment by RomaKis** [comment]
Working on this.

**Comment by magento-team** [comment]
Hi @oroskodias. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#955 by @RomaKis in 2.2-develop branch
Related commit(s):
 - 15928fbd8c42590187f0613f889cc27d6afabe0d
 - 188ecb36ed86fbd7df58a4826040078eefaad2c6
 - 546a0bb015e977d5ca9d3505d2bcba4a413d3c15
 - 4b585d48857f89abfb9bc4d6fe381ea6dbe3ac85
 - a9a3c197cbdb4d2e8f602b50e6ba3c147a8be061

The fix will be available with the upcoming patch release.

**Comment by ghost** [comment]
Hi @magento-team 
This issue was really fixed, but in the 2.3 the fix has gone, and now it doesn't work again. 
When will this issue fix?

**Comment by JayashreeDCKAP** [comment]
Hi @magento-team,

I am using Magento 2.2.4, but still, the issue is no fixed

**Comment by kennyrassin** [comment]
Same issue in 2.3.2

**Comment by maurixxxx** [comment]
I have the same issue in 2.3.2 are you going to provide a fix?

**Comment by darioruglioni** [comment]
any info about this issue?? I have the same problem in Magento ver. 2.3.3

**Comment by anil1067** [comment]
I am also facing the same issue in Magento 2.3.4. Please let me know if there is any solution.

**Comment by dpdesignthatfits** [comment]
This is still an issue, we have this on vanilla 2.4.3-p1 and 2.4.4

**Comment by Winfle** [comment]
@dpdesignthatfits have you managed to find a fix?
