### ISSUE TITLE
Can't upgrade Magento version to 2.1.4 from Wizard

### ISSUE THREAD

**Issue by skuzmina** [magento/magento2#8625]
I need to upgrade Magento to the latest 2.1.4 version. But when I go to the "Web setup Wizard" and select "System Upgrade" I am getting following message: You're already using the latest version, there's nothing for us to do.

See attached image for version info.

Can you tell how I can upgrade magento version without command line. I upgraded magneto to 2.1.3 from back-end.. maybe here are some old file (flag?) from previous update what tells that magento is up to date?

![magento-version-2-1-3](https://cloud.githubusercontent.com/assets/9421183/23143428/45c01a16-f776-11e6-8fc5-cdb07cbd6a1e.png)

Asked same question here https://magento.stackexchange.com/questions/160361/upgrade-magento-version-to-2-1-4 But I do not what to upgrade magento from Command line

Please advise,
Sandra

**Comment by skuzmina** [comment]
Any advise? 

Sandra

**Comment by skuzmina** [comment]
I still have same issues trying to upgrade from 2.1.3 to 2.1.5 - still showing i have latest version.

**Comment by veloraven** [comment]
@skuzmina thank you for your comment.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@skuzmina  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
