### ISSUE TITLE
Magento 2.1.2 - 2.1.4 email logo image function does not work

### ISSUE THREAD

**Issue by nambss** [magento/magento2#8626]
Preconditions
1. Magento 2.1.2
2. Upload Email logo in path Content -> Configuration -> Transactional Email -> Logo Image
3. Save

Steps to reproduce
1. New Email Logo should show in all email

Actual result
1. Default Magento Logo is used in email
2. Customized logo does not show
3. Logo Image URL Broken in preview under path Content -> Configuration -> Transactional Email -> Logo Image

I find new logo email in pub/media/logo/stores/1/ but not found in pub/media/email/logo/stores/1/
I upload a new logo email into folder: pub/media/email/logo/stores/1/ and deloy static but email logo in pub/static/.../Magento_Email/ is still luma logo
This issue is not solved in 2.1.4. But it is be closed. Why ???

**Comment by nambss** [comment]
ok

**Comment by ghost** [comment]
Feel you pain.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
