### ISSUE TITLE
Location of wishlist.js file is incorrect

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#8632]
In Magento\Wishlist\view\frontend\web there is a wishlist.js file.
This file should be moved to the js directory in the web folder.

### Preconditions
1. PHP7.0 
2. MG2.1.x

### Steps to reproduce
1. Goto Magento\Wishlist\view\frontend\web folder

### Expected result
1. wishlist.js should be in the js directory

### Actual result
1. wishlist.js is in the root of the web folder

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-65000
