### ISSUE TITLE
Cannot install translations with "i18n:pack" command line

### ISSUE THREAD

**Issue by benjamin-volle** [magento/magento2#8634]
Hello,

I just tried to install french translations using the "i18n:pack" commande line.
More precisely : 
bin/magento i18n:pack --mode="replace" -d source_fr_FR.csv fr_FR

And I had an Exception : 
Warning: mkdir(): Permission denied in /home/synbshop/public_html/vfb/setup/src/Magento/Setup/Module/I18n/Pack/Writer/File/AbstractFile.php on line 154

The problem is that Magento tries to create "/i18n" and many servers have not the right to do this (in the "/" directory).

**Comment by thomvanderboon** [comment]
Hi,

This problem was already reported https://github.com/magento/magento2/issues/6260 in August 2016. It has been fixed in the development branch.

Here is the work arround https://github.com/magento/magento2/issues/2951#issuecomment-276552659

Please close this issue


Thom

**Comment by benjamin-volle** [comment]
Hello,

Thanks for your answer, i've already used this method to be able to translate my website.
I didn't find the ticket you talk about, sorry.

I close mine.
