### ISSUE TITLE
Add possibility generate varnish 4 config file 

### ISSUE THREAD

**Issue by butthurt** [magento/magento2#864]
Currently Magento 2 can generate VCL only for varnish 3.* version. But already version of Varnish is higher than 4.0

Can you please add possibility generate Varnish 4.0 or make for admin choose to make vcl 3.0 or 4.0

**Comment by verklov** [comment]
Closing this ticket as the requested functionality will be implemented internally.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32339

**Comment by WilliamAtMagento** [comment]
VCL generation for Varnish 4 is done.  Will be published in next github release.
