### ISSUE TITLE
Sitemap bad urls: http//, but must bee https//

### ISSUE THREAD

**Issue by yumicom** [magento/magento2#8644]
Bad urls in Sitemap.xml : http//..., but must bee https!

### Preconditions
Magento 2.1.4, PHP 7.0.15 & MySQL MariaDB 10.1 

### Steps to reproduce
Admin - Stores - Configuration - General - Web - Use Secure URLs on Storefront - Yes
See /Sitemap.xml

### Expected result
<url><loc>https://...... 

### Actual result
<url><loc>http://......

**Comment by korostii** [comment]
The setting you mention isn't the only requirement. for making links work via https. Please make sure your Secure Base Url also contains https in it.

**Comment by yumicom** [comment]
My Secure Base Url contains https ))

**Comment by mcspronko** [comment]
Tested, fixed in latest develop branch.

**Comment by yumicom** [comment]
Magento 2.1.7, still bad URLs

**Comment by IlnitskiyArtem** [comment]
@yumicom Thanks for reporting this issue. 
This issue is already addressed in internal ticket MAGETWO-61059. I’ve added your report on this issue to that ticket.

**Comment by magento-engcom-team** [comment]
@yumicom, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by saurabhjain929** [comment]
Hello,

I am facing the same problem in 2.1.8 I have tried to found internal ticket MAGETWO-61059 on GIT but not found Anyone provides commit reference id.

**Comment by leegold** [comment]
Issue persists in 2.2.6. Was this supposed to be resolved?
