### ISSUE TITLE
Magento 2.1.4 Admin PayPal iframe all in one solution no credit card option

### ISSUE THREAD

**Issue by importwholesales** [magento/magento2#8645]
### Preconditions

Magento 2.1.4 fresh install.

1. magento 2.1.4
2. php 5.6
3. mysql  5.6
4. nginx

### Steps to reproduce

Admin > Stores > Configuration > Sales > Payment Methods 
PayPal All in one payment solution
Payments Advanced
Accept payments with a PCI-compliant checkout that keeps customers on your site. (Includes Express Checkout)

When this is selected and filled out.   I get the iframe on the customer side.  But when I go to place an admin order I get no credit card option.

When I select 
Payments Pro
Connect your merchant account with a fully customizable gateway that lets customers pay without leaving your site. (Includes Express Checkout)
I get the option for credit cards  on both customer side and admin side.
But not the iframe on customer side.

How do I fix  this so I get the iframe on the customer side and credit card option on the admin side.?

### Expected result

1.   get iframe on customer side and credit card option on admin

### Actual result

1. iframe on customer side and no option for credit cards in admin with paypal advance option

**Comment by magento-engcom-team** [comment]
@importwholesales, thank you for your report.
We've created internal ticket(s) MAGETWO-80636 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@importwholesales, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
