### ISSUE TITLE
Secure url issue in Magento 2.1.0 version

### ISSUE THREAD

**Issue by qwerty7869** [magento/magento2#8651]
On using Secure URL option in Magento 2.1.0 version, the issue is all the redirection links are converted to secure url .

**Preconditions**
1. Magento 2.1.0 version

 **Steps to reproduce**
1. Navigate to the Stores>Configuration>Web 
2. Edit the field **Secure Base URL** by changing url from http:// to https://
3. Set field **Use Secure URLs on Storefront** to Yes

**Expected result**
1. On cart page, product url link should be the insecure url.
2. On catalog search page, again product url link should be the insecure url.

 **Actual result**
1. On cart page, product url link is converted to secure url.
2. On catalog search page, again product url link is converted to secure url.

Please find the attachment for the same

![search_page](https://cloud.githubusercontent.com/assets/2813660/23213207/0bdbfb2e-f930-11e6-81f5-d563804720d0.png)
![cart_page](https://cloud.githubusercontent.com/assets/2813660/23213208/0bf1483a-f930-11e6-90c6-c2ae0ca1ca25.png)

**Comment by orlangur** [comment]
Semi-secure mode is known to be vulnerable to MITM attack thus it was announced that it is going to be removed at some point.

Probably, some places in the system are already working this way.

**Comment by piotrekkaminski** [comment]
@qwerty7869 not sure why you think this is incorrect. With the settings that you have provided (Secure Base URL is https://, Use Secure URLs is Yes), all links will be https.

**Comment by orlangur** [comment]
@piotrekkaminski, please check https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/etc/frontend/di.xml#L12 So, there are still places in module configuration which define "secure" URLs.

@qwerty7869 expectation I believe is that this config should behave similar to Magento 1: in mixed mode links will be unsecure *UNLESS* they are specified in `secureUrlList` explicitly.

If this is not true and all links must be secure with such setting, there is no reason to keep `secureUrlList` configuration and it should be removed all over the codebase.

**Comment by qwerty7869** [comment]
@orlangur @piotrekkaminski  - We require only Cart, Checkout, My account & Login pages to be secure which default Magento provides on performing the above-given settings. 

But here the issue is on secure page, all the redirection links of that page become https which actually should not be. Eg:  PDP page link on Cart come as secure.

In Magento  2.0.5 version, this was not the issue and everything was working smoothly.

**Comment by TomashKhamlai** [comment]
Thanks for reporting this issue! We've created internal ticket MAGETWO-70112 to address this issue.

**Comment by magento-engcom-team** [comment]
@qwerty7869, thank you for your report.
We've created internal ticket(s) MAGETWO-73198 to track progress on the issue.

**Comment by engcom-Charlie** [comment]
Hello @qwerty7869 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
