### ISSUE TITLE
Wrong customizable option price after saving product

### ISSUE THREAD

**Issue by siven76** [magento/magento2#8652]
When updating a product, the customizable option prices are not updated correctly if the price is greater than $999. This is because the price of the customizable option is formatted with comma for thousands separator.

### Preconditions
1. Magento 2.1.3
2. Australia/Melbourne locale

### Steps to reproduce
1. Edit a product with customizable option
2. Set the price (over $999)
3. Save the product
4. Edit the product again. The price will have comma separators.
5. Save the product again.
Check the option's price. It will be $1.

### Expected result
1. The price of the options should be saved correctly (instead of being truncated)

### Actual result
1. The price of the option is truncated (from being converted from string to float)

**Comment by ginnyginny** [comment]
Same problem here. Does it also happen on Magento 2.1.4?

**Comment by siven76** [comment]
No, the problem is fixed in Magento 2.1.4.

On 28 Feb 2017, at 5:41 pm, ginny <notifications@github.com<mailto:notifications@github.com>> wrote:


Same problem here. Does it also happen on Magento 2.1.4?

**Comment by Dorado-John** [comment]
I am working on Magento2 ver 2.1.5 and this problem is occurring for me exactly as described.

**Comment by jer23jk** [comment]
Same problem on Magento 2.1.7

Create dropdown customizable prices - Option Type dropdown

Same as siven76:

Steps to reproduce

Edit a product with customizable option
Set the price (over $999)
Save the product
Edit the product again. The price will have comma separators.
Save the product again.

**Comment by oleg-onufer** [comment]
Hi @siven76.
Thanks for reporting this issue.
Internal ticket MAGETWO-70296 was created.

**Comment by magento-engcom-team** [comment]
@siven76, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by jdovan** [comment]
This is still an issue...Magento ver. 2.1.5

**Comment by gopal2k6** [comment]
Still same issue in 2.1.7. Kindly share solution please
