### ISSUE TITLE
Saving a Product creates AlreadExistsException "URL key for specified store already exists."

### ISSUE THREAD

**Issue by ktomk** [magento/magento2#8657]
Said exception is created despite the URL key for the specified store is valid.

Related existing issue material:

* #8564

### Preconditions
1. Scope of area is "`adminhtml`" (other areas likely behave the same, this is just a precondition in scope of the report)

2. Saving a **\Magento\Catalog\Model\Product** with the same identity (as it is an entity, the same data) via it's public `save` method.

3. Causes the exception if it was previously persistet within the catalog_product_entity table (but not any longer)

### Steps to reproduce
1. Create a test-case
2. Within it create *product entity* and save it by it's own public method 
3. Remove the entity from the catalog_product_entity table by deleting the row
4. Extend the test-case and prior creating the entity fetch it via SKU from the **Repository** and delete it via the **Repository** if it already exists (that is to make it reproducible)

### Expected result

1. Expected is that the entity can be (re-) created (Rationale: as it either does not exists -or- has been deleted)
 
### Actual result

1. Said **Exception**

### Issue comments

This by material is subjective to some extend but with a more differentiated look upon; this is either missing a trigger within the database to remove the rewrite_url entries when the entity is removed - or - when the entity is (re-) created the entry should be updated (I might be wrong on this:).

If *not* there is a missing constraint on the `name` of the entity at least. This would not solve the scenario outlined but at least show the implication as it looks like that Magento requires uniqueness on the product entity name (and if it's only for generating `url_rewirte.request_path` values). At that point (url_rewrite)) the constraint is set, but it's a little late to my taste. I do see that this constraint protects from greater havoc but as  #8564 advocates towards my impression, the said exception breaks into a greater room of expectations the public interface does not offer.

I can work around this violation by taking care of the *rewrites* my own but the schema should match with the public interface as it is mandatory for persistence (in the end) and in my case it's a simple use of the interface.

To come to an end, a better way would be to create a new product entity via the repository, but the repositories' `save()` method does not allow to create new entities *nor* has it a `create` method (CRUD functionality). In the end from a programming perspective, I don't want to care about the persistence layer *if* there is a *Repository*.

**Comment by ktomk** [comment]
Another comment: Not only there is no `create()` method, the **ProductRepository** does not even allow me to perform the deletion operation: "Delete operation is forbidden for current area" (**Magento\Framework\Exception\LocalizedException**).

**Comment by orlangur** [comment]
> Within it create product entity and save it by it's own public method

`save` method in model is deprecated, use `ProductRepository` instead.

> Remove the entity from the catalog_product_entity table by deleting the row

I'm not sure this is valid use case :)

If you bypass https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteRemovingObserver.php anyhow, urlrewrites removal will not occur. Any valid use cases for this should be fixed (for example, they [did not work in API](https://github.com/magento/magento2/commit/149a9363bb33756115cf3076973064c229860835#diff-d4d82d6edde889a674256ff01d58bef3) some time ago).

**Comment by ktomk** [comment]
@orlangur  Yes, the use-case is a bit from testing. I have problems to create a new product entity via the repository which I'd prefer to use. Do you know if the repository can be used to create a new product as well?

**Comment by orlangur** [comment]
You can check integration tests in such situations, from https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple.php#L220 it looks like it can.

**Comment by ktomk** [comment]
That was a missing for me: `$product->isObjectNew(true);`, this allows the creation.

For deletion, I have to set a registry value: `$registry->register('isSecureArea', true);`.

**Comment by ktomk** [comment]
I've seen at some places when storing an entity fails, original exceptions are swallowed. It might be useful to add previous exceptions at these places so that more information is at hand.

**Comment by ktomk** [comment]
For now I close this issue, the point about more information is raised in the other referenced issue.
