### ISSUE TITLE
Clarify supported LESS language version

### ISSUE THREAD

**Issue by mfdj** [magento/magento2#8658]
### Preconditions
1. Magento 2.1.5 (and probably all previous versions)
2. Any version of PHP

### Steps to reproduce
1. `find . -name less.min.js -exec grep 'Leaner CSS' {} \;`
2. `vendor/bin/lessc --version`

### Expected result
1. Equivalent versions

### Actual result
![screen shot 2017-02-22 at 4 51 46 pm](https://cloud.githubusercontent.com/assets/1110910/23240466/8a16570e-f922-11e6-8ef1-7d5fef92a3b7.png)

![screen shot 2017-02-22 at 5 15 45 pm](https://cloud.githubusercontent.com/assets/1110910/23240472/930961bc-f922-11e6-8698-ca99338e0c40.png)

### Related

https://github.com/oyejorge/less.php/issues/340

**Comment by orlangur** [comment]
Both are used: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.html#less_modes

Only `less.php` is used in production and its version explicitly clarified in `composer.json`: https://github.com/magento/magento2/blob/develop/composer.json#L44

Hence no v2 of `less.php` planned soon you think `less.js` needs to be downgraded to 1.7.0 for consistency?

**Comment by hostep** [comment]
I guess this is somewhat related to: https://github.com/magento/magento2/issues/7231

**Comment by mfdj** [comment]
@orlangur Mainly I'm asking for clarification around the LESS language version supported by Magento 2.

I'm new to LESS, so I'm not familiar with the language feature differences between LESS version 1 and version 2 but I've encountered and  documented a known breaking change between v1 and v2 described pretty well at the less.php repo: https://github.com/oyejorge/less.php/issues/340

 I don't feel strongly one way or another about which version of the LESS language is used, v1.7 is pretty full featured, but I do think that *parser version parity* is an easy win for Magento… but I don't know that much about the LESS parser, so take this suggestion with a grain of salt. 

FWIW I have noticed that the `lessc` executable for less.js 1.7 is faster than less.js 2.5 — potentially the client-side render for less 1.7 will be a little faster too :-D

Primarily my hope is that we can be clear about which version of the LESS language is supported, especially since [LESS v3](http://lesscss.org/3.x/) is in the works. 

Magneto 2 users who are newcomers to LESS will likely reference [lesscss.org](lesscss.org) and in the event that LESS v3 becomes the newest stable version than it's important to clearly specify the langue features Magento users may use and which features are not supported when using the Magento 2 / less.php.

**Comment by orlangur** [comment]
> FWIW I have noticed that the `lessc` executable for less.js 1.7 is faster than less.js 2.5

This seems strange even under PHP7 (you can check numbers from benchmark in module from linked issue).

I do agree that if bumping `less.js` version was not intentional and as it is only a developer tool it could be safely downgraded to `1.7.0`. At least, if we even have dedicated [LESS coding standard](http://devdocs.magento.com/guides/v2.1/coding-standards/code-standard-less.html) such a crucial thing as used LESS language version is worth mentioning in documentation.

Next steps really depend on Frontend Development Roadmap. For instance, I saw community-driven SASS project in Magento Forums.

What I recommended long time ago (but unfortunately wasn't heard) is [Assetic](https://github.com/kriswallsmith/assetic/tree/master/src/Assetic/Filter) integration. In such case you would get `LESS` (both `less.php` and `less.js`), `SASS`, `SCSS` support, `CSS/JS` minification/merging out-of-the-box. It would be even possible to leave core styles untouched (for instance, if they rely on `LESS v1.7`), generate a `CSS` out of them, and write your own styles using language of your choice, like `LESS v3`. Didn't spot any reasons to change my mind since then.

**Comment by mfdj** [comment]
Interesting point. While Assetic is a worthwhile library to solve this problem (I've used it before in Symfony 2) I think the Magento solution is workable. For instance. I was able to use [baldwin-agency/magento2-module-less-js-compiler](https://github.com/baldwin-agency/magento2-module-less-js-compiler) to compile my theme using less.js. Experimentally supporting LESS v3 seems pretty doable given the current Magento architecture.

I do see two possibly separate but related issues now:

### Clarify LESS language version used for Blank, Luma, MagentoUI

Since user's have the option of implementing [ContentProcessorInterface](https://github.com/baldwin-agency/magento2-module-less-js-compiler/blob/master/Css/PreProcessor/Adapter/Less/Processor.php#L18) to provide their own LESS processor it would be nice to make it clear which version of the LESS language the themes and component libraries are built against.

Users should be confident about:

- the minimum version of LESS parser needed to compile Magento's less code
- that future releases of less code will stay BC
  - in the event BC change are made they can be done in a clear SEMVER way

While I was able to deduce that Magento was using LESS version 1.7.0 it took me some time and digging to arrive at this conclusion. The differences between client/server versions made this process more complicated, which prompted me to open this issue.

### Clarify provided LESS parser versions

I'd be curious about the popularity of less.js client renderer in Magento 2. If usage is small than it might be worth deprecating the feature, since it adds another level of complexity to this topic.

If the client/server parser versions are different it's inevitable that someone who is using the client renderer for local-development will be surprised when they same code doesn't work when run on their production sever renderer. Related: https://github.com/magento/magento2/issues/7231 

Hunting these kinds of bugs down is really painful for users, and can erode trust in the system.

My main goal in pushing for this clarity is to build confidence in Magento's tooling — engineers should have clear idea of how to build frontend with Magento.

**Comment by orlangur** [comment]
@mfdj, I accidentally found answer regarding SASS here: https://github.com/avoelkl/mage2roadmap 
So, it looks like there is no need to change anything about LESS (besides documentation maybe, PRs can be proposed at https://github.com/magento/devdocs/blob/develop/guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.md).

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Short answer is - just use whatever syntax is supported by `less.php`, JS version was added just to make development more convenient.
