### ISSUE TITLE
Configurable product attribute scope

### ISSUE THREAD

**Issue by chris-brabender** [magento/magento2#866]
When creating a new product attribute that is to be used for configurable products the scope option defaults to Store view and allows you to set Yes to Use To Create Configurable Product.

After you save the attribute and try to create a configurable product based on that, the attribute is not returned in the variations search box.

If you then go and edit the attribute, change the scope to Global, and set Use To Create Configurable Product to Yes, the attribute is visible in the variations search box.

If you select Store view or Website for Scope the Use To Create Configurable Product option is hidden.

When creating a new attribute, by default should the Use To Create Configurable Product option be unavailable when Scope is defaulting to Store view? This is a little confusing as the option is presented but is not actually used correctly.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32341

**Comment by vpelipenko** [comment]
@chris-brabender, internal ticket has been completed and fix will be delivered with the next public GitHub update this week. Please, let us know, if you are not OK with implemented solution.

**Comment by vpelipenko** [comment]
Fixed. Closed.
