### ISSUE TITLE
magento2-base package is copying files will not recreate missing files

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#8661]
### Preconditions

1. Tested on Magento version 2.1.5 and Magento 2.1.3, behaviour is the same in both versions.
2. Have a Magento installation installed
3. In the composer.json file magento-force is not set or set to false. 

### Steps to reproduce
1. Have a Magento installation completely setup
2. Remove the setup directory from the root
3. Remove the Magento2-base package from the vendor directory
4. Run composer update or composer install to install the magento2-base package again. 

### Expected result
1. The setup directory is missing and should be recreated, however it is not. 
2. All other files should not be overwritten since magento-force is set to false. 

### Actual result
1. When checking the exact composer install notifications it says that the .htaccess already exists (which is correct).
2. No other files are checked after this error. It will not check any other files from the composer.json, so missing files are not restored. 

[root@web02 20170223102419]# composer install -vvv
Reading ./composer.json
Loading config file ./composer.json
Loading config file /home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/auth.json
Reading /home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/auth.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt: valid
Executing command (/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419): git branch --no-color --no-abbrev -v
Executing command (/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419): git describe --exact-match --tags
Executing command (/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419): git log --pretty="%H" -n1 HEAD
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/vendor/composer/installed.json
Loading plugin MagentoHackathon\Composer\Magento\Plugin
activate magento plugin
Running 1.3.2 (2017-01-27 18:23:41) with PHP 5.6.29 on Linux / 2.6.32.60xls-domU
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.022 seconds
Analyzed 497 packages to resolve dependencies
Analyzed 3285 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: magento/magento2-base:2.1.3
  - Installing magento/magento2-base (2.1.3)Downloading https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.1.3.0.zip
 Downloading: 100%Writing /root/.composer/cache/files/magento/magento2-base/69d9239857486ba94c32301f3632630de4218137.zip into cache from /home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/vendor/magento/magento2-base/3c7f0f6828b08fa420484552590600ca.zip
 Extracting archiveExecuting command (CWD): unzip -qq '/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/vendor/magento/magento2-base/3c7f0f6828b08fa420484552590600ca.zip' -d '/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/vendor/composer/94dfca04' && chmod -R u+w '/home/cream/domains/postnl.staging.web02.cream.nl/public_html/releases/20170223102419/vendor/composer/94dfca04'

    REASON: Required by the root package: Install command rule (install magento/magento2-base 2.1.3)

Generating autoload files
start magento deploy via deployManager
start magento deploy for magento/magento2-base
**Target ./.htaccess already exists (set extra.magento-force to override)**
jump over deployLibraries as no Magento libraryPath is set

**Comment by skovalenk** [comment]
Hi @dverkade I found code chunk where this logic was implemented
`// If file exists and force is not specified, throw exception unless FORCE is set
        if (file_exists($destPath)) {
            if ($this->isForced()) {
                unlink($destPath);
            } else {
                throw new \ErrorException("Target $dest already exists (set extra.magento-force to override)");
            }
        }`

As we throwing exception we want to stop process of package recovering. 
It is not a bug, and there was a reason for this: 
 If you set magento-force to false and delete only part of package, and then run recovery by composer-update, you can faced with code inconsistency. Because newer (than installed already) magento2-base package can be downloaded and different versions for different parts of one package will presents. 

If we set magento-force to override, than all files will be overrided, and those problem do not appear.

**Comment by skovalenk** [comment]
HI @dverkade is there any update about this issue.
Maybe you need some help with best practices: "How to do one or another thing"

**Comment by dverkade** [comment]
Hi @sereban,

Thanks for figuring this out. I have never thought about this that you could get code inconsistency by restoring it. Maybe it's possible to have composer do a little bit more output for this? Because the behavior is quite unclear and you can only get what's happening when you have the -vvv option enabled. Do you have suggestions on how to improve this?

**Comment by magento-engcom-team** [comment]
Hi @dverkade 
Thank you for your submission.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
