### ISSUE TITLE
Date-Picker in Product Details does not diplay correct date when using other Locale than en_ES

### ISSUE THREAD

**Issue by jmackiol-dotsource** [magento/magento2#8662]
### Preconditions

Magento CE 2.0.12 / EE 2.0.12 EE
PHP 7.0.8+, MySQL 5.6+

### Steps to reproduce
Install Magento 2 CE from composer create-project.
add a new language pack (e.g. de_DE from https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE
Configure the admin user to use the new locale.
Add new Product Attribute with type of "Date".
Add the created attribute to any Attribute Set (Default in this case).
Either create a new product or edit a current one.
Set the date to 2017-01-01.
Save the product.
Reload the product

### Expected result

01.01.2017 is filled. (German Locale of 2017-01-01)

### Actual result
01.01.2016 is filled. (German Locale of 2016-01-01)
Database stored the value correctly:
![image](https://cloud.githubusercontent.com/assets/12070095/23262662/c69582b8-f9db-11e6-8823-fed275fbc317.png)

**Comment by VasylShvorak** [comment]
@jmackiol-dotsource , thank you for your report.
Unfortunately I was not able to reproduce this issue.
Please describe all steps you have done in more detailed way.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
