### ISSUE TITLE
Magento 2.1.4 edit robots.txt fails

### ISSUE THREAD

**Issue by zkliouel** [magento/magento2#8663]
### Preconditions

1. Magento 2.1.4
2. PHP7

### Steps to reproduce

1. On Back-Office
2. Stores -> Configuration -> General -> Design -> Search Engine Robots 
3. Edit custom instruction of robots.txt File

### Expected result

1. Custom instruction are not saved

### Actual result

![robots_ko](https://cloud.githubusercontent.com/assets/1635913/23266380/edae272c-f9e7-11e6-9f55-fa62ba32aaf2.png)

Logs : 

Magento\Framework\Exception\FileSystemException: The path ".:///var/www/gibertjoseph/var/www/gibertjoseph/" is not writable in /var/www/gibertjoseph/vendor/magento/framework/Filesystem/Directory/Write.php:54
Stack trace:
#0 /var/www/gibertjoseph/vendor/magento/framework/Filesystem/Directory/Write.php(248): Magento\Framework\Filesystem\Directory\Write->assertWritable('.:///var/www/gi...')
#1 /var/www/gibertjoseph/vendor/magento/framework/Filesystem/Directory/Write.php(264): Magento\Framework\Filesystem\Directory\Write->openFile('robots.txt', 'w+')
#2 /var/www/gibertjoseph/vendor/magento/module-config/Model/Config/Backend/Admin/Robots.php(86): Magento\Framework\Filesystem\Directory\Write->writeFile('robots.txt', 'User-agent: *\\nD...')

**Comment by vasilii-b** [comment]
The error message says very clear that your directory is not writable.
Make sure your server folders belongs to your user and it has privileges to write in the folder.

This is not a Magento 2 issue but your local machine issue.
Please close this issue and find on google how to fix that. Thanks.

**Comment by zkliouel** [comment]
The main magento folder has not to be writeable for the execution user.
It is not a good practice, and also your wizard setup does not ask for it.

A good solution could be to write the file in pub/media, and to add a rewrite rule in your htaccess file.

**Comment by korostii** [comment]
It's a bit funny and unexpected that robots.txt is now editable from configuration page yet underneath it is still stored on disk in the project root folder. I also wonder, what would happen if you attempt to have different contents inside the robots.txt for different StoreViews? (see store switcher on the screenshot above)

**Comment by RomanKrut** [comment]
@zkliouel Unfortunately, I could not reproduce the issue on fresh install Magento 2.1.7 via composer as you described it. Please can you recheck your problem on the latest version of Magento 2?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by MuneebMagenticians** [comment]
Maybe you are doing something wrong in writing custom instructions. You can check this guide that can help you to understand in a more better way: [Configure Magento 2 Robots.txt](https://magenticians.com/configure-magento-robots-txt/)

Hope it will help you and also others.
