### ISSUE TITLE
Magento 2 catalog search too slow

### ISSUE THREAD

**Issue by farisshindsite** [magento/magento2#8664]
Hi everyone
My website is https://buy.endevco.com/ the products search is too slow.
Before was good but when i added a second website to the same magento 2.1.2 and imported products the search started to be extremely slow in both websites.

I'm using also this extension https://mirasvit.com/magento-2-extensions/sphinx-search-ultimate.html

 Preconditions
1. Magento 2.1.2
2. Multiwebsites created
3. Products imported (1287 products)

 Steps to reproduce
1. Search for anything from header search form
2. Hit enter and wait to open search results page

 Expected result
1. Show the page after 1-2 seconds like the other page requests

 Actual result
1. Wait 30 seconds to load the page

Thanks for your help

**Comment by oleghind** [comment]
Attaching profiler info:
<img width="1580" alt="Profiler" src="https://cloud.githubusercontent.com/assets/3453172/23277570/50ba4cee-f9dc-11e6-8538-cc5bcaabd4f0.png">

**Comment by sambolek** [comment]
Contact extension provider for support, this most likely isn't a Magento issue.
See https://www.sonassi.com/blog/your-misconfigured-magento-search-module-will-hurt-you

**Comment by mbrinton01** [comment]
@farisshindsite for support with this extension, please contact mirasvit directly.

**Comment by 34cnk34** [comment]
@farisshindsite 
I checked your website, your search results are very fast now. How did you solve this issue? my website is https://dev.suppliesontime.com
And i am also using mirasvit spinx search ultimate, mirasvit page cache.. etc..
But search results are still too slow

Can you please help?

**Comment by jagoman85** [comment]
Hi @34cnk34  / @farisshindsite 
Same issue. Slow search, and using Mirasvit.
What was the solution?

**Comment by 34cnk34** [comment]
@jagoman85 
I am still having the issue. Mirasvit keep saying their extension works as expected. I cant figure out what causing this issue. 
We have so many nested categories. I assume issue related that. But so far i couldnt find any solution. If you guys found something, please let me know

**Comment by jagoman85** [comment]
@34cnk34 
I had a couple of issues, but the first issue was the main cause...

1. Upgrade to latest Magento Version (2.4.3+) & Mirasvit Plugin version & Use ElasticSearch 7
2. Other 3rd Party Plugin caused a slow down (BSS Commerce Plugins "Hide Price" & "Multi Wishlist" in my case)
3. Settings for attributes Colour & Size were misconfigured for Layered Navigation (cant remember what the config was)

**Comment by 34cnk34** [comment]
Thank you
I will try your solutions
