### ISSUE TITLE
JS translations aren't working at all in 2.1.4

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#8669]
Translations in *.js and ko are not working at all. js-translation.json is not recreated properly even on clean Magento 2.1.4.

### Preconditions

1. I'm using Magento 2.1.4 and js-translation.json is only 50 bytes and contains only translation for "Choose your bank..." into "Please select your bank".
2. I'm doing regular rm -rf pub/static/* as well as clearing caches using the command 
rm -rf var/generation var/page_cache var/cache var/view_preprocessed

### Steps to reproduce

1. Clearing caches and pub/static as described in Step 2 / Preconditions
2. Running 
 php -d memory_limit=4G bin/magento setup:static-content:deploy en_US de_DE
3. After that, these are the file sizes of js-translation in the web folder:
42331556        8 -rw-rw-r--    1 stephan          admin                   2 24 Feb 13:53 ./pub/static/adminhtml/Magento/backend/de_DE/js-translation.json
42329642        8 -rw-rw-r--    1 stephan          admin                   2 24 Feb 13:53 ./pub/static/adminhtml/Magento/backend/en_US/js-translation.json
42325718        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:52 ./pub/static/frontend/Huge/huge1/de_DE/js-translation.json
42323530        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:52 ./pub/static/frontend/Huge/huge1/en_US/js-translation.json
42313257        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./pub/static/frontend/Magento/blank/de_DE/js-translation.json
42311132        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./pub/static/frontend/Magento/blank/en_US/js-translation.json
42319451        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./pub/static/frontend/Magento/luma/de_DE/js-translation.json
42317303        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./pub/static/frontend/Magento/luma/en_US/js-translation.json
42329641        8 -rw-rw-r--    1 stephan          admin                   2 24 Feb 13:53 ./var/view_preprocessed/source/adminhtml/Magento/backend/en_US/js-translation.json
42323529        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:52 ./var/view_preprocessed/source/frontend/Huge/huge1/en_US/js-translation.json
42311131        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./var/view_preprocessed/source/frontend/Magento/blank/en_US/js-translation.json
42317302        8 -rw-rw-r--    1 stephan          admin                  50 24 Feb 13:51 ./var/view_preprocessed/source/frontend/Magento/luma/en_US/js-translation.json

### Expected result

1. json-Files should be filled with translation strings

### Actual result

1. js-translation.json files don't contain anything "[]" or just 1 translation 
{"Choose your bank...":"Please select your bank."}"

**Comment by thomvanderboon** [comment]
This is duplicate of https://github.com/magento/magento2/issues/7862

Deploy the languages separately:

php -d memory_limit=4G bin/magento setup:static-content:deploy en_US
php -d memory_limit=4G bin/magento setup:static-content:deploy de_DE

Please use work arround and close this issue

Thom

**Comment by nickrigby** [comment]
@thomvanderboon Can confirm that this works (2.1.4 and 2.1.5). Thanks!

**Comment by thomvanderboon** [comment]
That depends.... there are other translation bugs in Magento 2.1.x. You might need an combination of the various work arrounds

Please also check: https://github.com/magento/magento2/issues/2951#issuecomment-276552659 and https://github.com/magento/magento2/issues/8508#issuecomment-279332346

Thom

**Comment by stephansteiner** [comment]
Ok this (https://github.com/magento/magento2/issues/8669#issuecomment-282358485) is a viable way for me. Of course .../en_US/js-translation.json will contain a translated string ONLY if the "translation" differs from the original string. in en_US most of the strings do not need to be translated, thus resulting in a empty json like in ./var/view_preprocessed/source/adminhtml/Magento/backend/en_US/js-translation.json that contains only "[]"
