### ISSUE TITLE
Theme list will not be updated

### ISSUE THREAD

**Issue by Crustymd** [magento/magento2#867]
So if i try to implement a template in Magento to i unzip it in root folder (if the template is full ready) and the files will be copied to needed directory and then after refresh magento cache you can see the template in Store - > Configuration -> Design -> Design Theme 

It will appear in the list. 

Now the issue is, i tried to create own template to see if i make it correctly, so i created a directory

app/design/frontend/crusty/firsttheme/

And in this direcotry i should create the other subdirectories of the teme acording to documentation. BUT i did not continue i just wanted to see how other template works first, so i left this directory Empty and installed a theme, refreshed cache, and the theme WOULD NOT appear in the Design Theme list.. Only the 2 magento default Themes were there... I cleared cache and e.t.c. but nthing would help 

The strange thing is that you could see the Theme in Contect -> Design -> Theme 
But you would not see it in the Design Theme list and you can not select it cause it is not there. 

I just thought what might cause this, i delete my empty directory "app/design/frontend/crusty/" - refreshed cache, and it worked, the theme was in the theme list

So as i have understood, if there is a empty directory or incorectly, managed directory of a theme, Magento will Not update the Theme List. 

Am not sure that you could call this a bug, but anyway i think magento should ignore the empty directory, skip it, and yet update the theme list with those that are correctly setted up.

**Comment by Vinai** [comment]
Hi wojtekn, the PR does not change the behavior you describe. I also manually removed the record from the core_theme table when I changed any value copied there.

**Comment by vpelipenko** [comment]
@Crustymd, we can't reproduce now the issue with processing themes when empty directory exists. Both lists in Content -> Design -> Themes and Store - > Configuration -> Design -> Design Theme are updated. Could your check it again on the latest code? 

@wojtekn, @Vinai, you are right here that there is only manually way to update custom theme in core_theme table. This behavior will be reviewed during next planned work around theme management.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32342

**Comment by vpelipenko** [comment]
There are no updates from participants. Closed.

**Comment by wojtekn** [comment]
@vpelipenko did you make any decision around this? Maybe getting rid of core_theme table completely will do the trick?
