### ISSUE TITLE
Original price not shown crossed out before configurable option chosen in 2.1.3

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#8670]
### Preconditions

1. Magento CE 2.1.3, php 7

### Steps to reproduce

1. Create a configurable product with options
2. Set price and special price the same on all options
3. View product view page of product on frontend

### Expected result

1. Original price to be shown crossed out

### Actual result

1. Original price is hidden until an option is chosen

It looks like this was introduced due to #5097. The new JS code checks the selected option and hides the original price if there is no special price difference for that option. The problem is that it also hides the original price if there is no option selected - as is the case on page load. So none of the original prices are initially showing.

The fix seems to be to remove the "no-display" from the original price, and change the condition to do nothing if there is no option selected.

Given how long ago 2.1.3 came out and how basic this problem, I'm wondering if I'm missing something here...?

**Comment by maderlock** [comment]
My current workaround for this is a module with frontend requirejs-config.js:

    var config = {
    config: {
        mixins: {
            'Magento_ConfigurableProduct/js/configurable': {
                'C3_Magento2Fixes/js/configurable': true
            }
        }
    }
    };

And a mixin in the frontend/web/js of the same module with the following change of logic:

    define([
        'jquery'
    ], function ($) {
        'use strict';
    
        return function (target) {
            /**
             * @mod Change the logic so that 'undefined' optionIds are left showing
             */
            target.prototype._displayRegularPriceBlock = function (optionId) {
                if (typeof optionId == 'undefined'
                    || this.options.spConfig.optionPrices[optionId].oldPrice.amount
                    != this.options.spConfig.optionPrices[optionId].finalPrice.amount
                ) {
                    $(this.options.slyOldPriceSelector).show();
                } else {
                    $(this.options.slyOldPriceSelector).hide();
                }
            };
    
            return target;
        };
    });

The change is really small - the change of '!=' to '=='for optionId == 'undefined', and following it by a || rather than a &&.

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by ladle3000** [comment]
As far as i can tell this issue stands in 2.2.2
