### ISSUE TITLE
Unable to add extension_attributes for ProductCustomOptionValuesInterface

### ISSUE THREAD

**Issue by danbuchal** [magento/magento2#8675]
### Preconditions
I would love to be able be able to add extension attributes to Magento\Catalog\Api\Data\ProductCustomOptionValueInterface
however it does not extend Magento\Framework\Api\ExtensibleDataInterface

Many other related interfaces allow this. Some examples:
 - ProductInterface
 - ProductCustomOptionInterface
 - ProductCustomOptionTypeInterface
 - etc

Is there a reason why this does not exist on ProductCustomOptionValueInterface?

**Comment by ishakhsuvarov** [comment]
Hi @danbuchal 
Currently adding the extension attributes to the interface in question would be a backward incompatible change so we have to be careful with that.
Could you please provide us with an example of the scenario where you would need an extension attributes on that entity?
Thank you!

**Comment by danbuchal** [comment]
Hi @ishakhsuvarov 

We have a need to add new attributes on the products custom options.  Currently I am able to accomplishing this by adding the needed columns to the catalog_product_option_type_value table.
I set these values with a customization to the product admin that has a link for each product option that pops up a modal with a form to set them.
(See: http://magento.stackexchange.com/questions/143584/magento-2-1-custom-product-options-in-slideout-modal/146334#146334)

This all works, however I discovered that I am unable to set these values via an API call (which I would be able to if I could use extension attributes instead)
When I attempt to set via an API call I get a message similar to the following.
 "Property '[new attribute]' does not have corresponding setter in class 'Magento\Catalog\Api\Data\ProductCustomOptionValuesInterface'"

I haven't been able to find a way to work around this just yet.

Can you explain how this is a backwards compatibility issue since something is being added (not removed)? I don't doubt you are correct, I would just like to understand the reason.

Thanks for looking into this.
Dan

**Comment by magento-engcom-team** [comment]
Hi @danbuchal. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/30
