### ISSUE TITLE
Magento 2. White text on white background

### ISSUE THREAD

**Issue by vsolod** [magento/magento2#8680]
On every theme - blank or luma, i have some white text on white background! But this text must be black.
setup:upgrade and static deploy doesnt helps me.
Here the screenshots:
![2017-02-25 05 46 47](https://cloud.githubusercontent.com/assets/26032732/23335800/be0992e2-fbc5-11e6-8bc3-b5e77fe934fb.png)
![2017-02-25 05 46 56](https://cloud.githubusercontent.com/assets/26032732/23335801/be0ffa60-fbc5-11e6-921f-07606deb877d.png)

How i can fix it?

**Comment by Ctucker9233** [comment]
CSS would be the quickest:
.product-info-main .price-box .price-wrapper .price, .product-options-bottom .price-box .price-wrapper .price a{color: #000000;}

**Comment by vsolod** [comment]
Ctucker9233 , sorry for noob question, but where i must put this code?

**Comment by vsolod** [comment]
Also this problem same with text  that have "location"  	"Label for an input element." and  "Span element"

**Comment by vsolod** [comment]
aaand problem is here app/code/Ves/Brand/view/frontend/web/css/b                                                                                                        ootstrap.min.css

**Comment by Ctucker9233** [comment]
@vsolod So it would seem your problem is with this Ves extension. If you use chrome browser, you can right-click on any element and "inspect element". Other browsers have this feature but it's called something different. That'll show you the class of the problem element. Search for that class in the css file you have posted. My guess is you will find that the element has been styled white or #ffffff. Simply change that to black or #000000.

**Comment by Ctucker9233** [comment]
@vsolod The code I used was for vanilla Magento without extensions. So the code will likely be different for you.

**Comment by Ctucker9233** [comment]
@vsolod di this solve your problem?

**Comment by vrann** [comment]
@vsolod can you reproduce it on the latest mainline? Here is what I see with the Luma theme:
<img width="452" alt="screen shot 2017-02-28 at 7 45 13 pm" src="https://cloud.githubusercontent.com/assets/2277722/23442522/9408adcc-fdee-11e6-982b-5962958e94ef.png">

**Comment by vsolod** [comment]
@Ctucker9233  Solved! But i has another one - https://github.com/magento/magento2/issues/8756

**Comment by vrann** [comment]
@vsolod Thanks, closing
