### ISSUE TITLE
clicking action button in backend multiple times results in multiple actions

### ISSUE THREAD

**Issue by steros** [magento/magento2#8687]
If you click an action button in the admin backend multiple times this will result in multiple actions.
This at least applies to the "add block" button in the content menu.
If you create a new block and hit "save block" it takes several seconds to load.
Whilst this time you can click the "save block" button again which will result in multiple added blocks.

### Preconditions
1. Magento 2.1.5

### Steps to reproduce
1. go to "content"
2. go to "blocks"
3. click "add a new block"
4. enter data
5. hit "save block"
6. see page loading
7. hit "save block" like it's hot

### Expected result
1. ONE block should be added 

### Actual result
1. multiple blocks with the same data are added

**Comment by RomanKrut** [comment]
@steros Hello, i tried to reproduce your issue on the latest version of Magento 2 and i can`t. See my result on screenshot with result of many clicks. Also try to reproduce it on your instance on the latest version of Magento 2. If you reproduce it again tell us more information about it.
![block_magento2](https://user-images.githubusercontent.com/27814479/27731850-6ebc043e-5d97-11e7-85be-765a768c449c.png)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
