### ISSUE TITLE
All the exceptions must be logged at some level

### ISSUE THREAD

**Issue by korostii** [magento/magento2#8688]
### Preconditions
1. Magento 2.1.5

### Steps to reproduce

1. Enter checkout as a logged in customer, have some items in cart.
2. Root cause unclear.

### Expected result

Either
1a. No errors shown at all (meaning no errors happened)
Or
1b. If an error does in fact happen, it's _root cause_ is logged somewhere or provided in the REST call response, or shown to the user (but not ignored silently).

### Actual result

1. User receives a meaningless message http://take.ms/kBo9P while accessing REST endpoint `/V1/carts/mine/estimate-shipping-methods-by-address-id` with trace 
`...Magento/Framework/Webapi/ServiceInputProcessor->processInputError(Array)`
2. Actual root cause is ignored silently (not shown to the user, not logged, nothing). 
In my case, it was a `NoSuchEntityException `with message `Requested product doesn't exist` caused by an outdated product_id reference from a cart item to a product that got deleted somewhere in the past, but that's not the point.

### Observations
1. Whenever an endpoint having "/mine/" inside, it usually has a "resource" node "self" attached to it in webapi.xml. In this case, that is the hint that %cart_id% is getting substituted into the webapi call internally. 
2. In the end, that job is being done by \Magento\Quote\Model\Webapi\ParamOverriderCartId. which outright [catches and ignores](https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/Webapi/ParamOverriderCartId.php#L59) any NoSuchEntityException wchich happens to be coming through.
3. This might be an obvious one: in general,catching and ignoring Exceptions is not a good way to go around. You either pass it through to a user or a developer, or you leave for the level above you, otherwise an important issue might get unnoticed.

**Comment by magento-engcom-team** [comment]
@korostii, thank you for your report.
We've created internal ticket(s) MAGETWO-84643 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @korostii

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@korostii thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by korostii** [comment]
I'm confused. It seems a bit unreasonable to close a ticket if it is still a valid, confirmed, planned and unfixed issue.
I mean, it obviously doesn't help clearing your backlog since the issue is [still placed in that TODO column](https://github.com/magento/magento2/projects/14#card-5893339)

Hopefully, your internal ticket ( MAGETWO-84643 ) is still open though, please correct me if it's not?

On an unrelated note, I have doubts regarding this whole triage system of yours, because at first glance it doesn't seem to add any value beside the additional ton of automated notifications to my watched issues. I would gladly see some kind of priority system used instead.
