### ISSUE TITLE
Adminhtml - Category-Tree not working in IE10

### ISSUE THREAD

**Issue by thoho-mpa** [magento/magento2#8693]
The Category Tree is not loading because there is an JavaScript Error:
"Unable to set property 'onreadystatechange' of undefined or null reference." ext-tree.js, line 33 character 605
"Unable to get property 'defaults' of undefined or null reference" defaults.js, line 10 character 5

Browser: Internet Explorer 10

Screenshot of the Error:
![bs_win7_ie_10 0](https://cloud.githubusercontent.com/assets/20966434/23363423/e426581c-fcfa-11e6-9f14-436e6c907c54.jpg)

**Comment by orlangur** [comment]
IE10 is not supported: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html

However, I believe older browsers shall show some incompatibility notice in UI rather than execute incompatible JavaScript.

**Comment by thoho-mpa** [comment]
Oh thanks for this advice.
