### ISSUE TITLE
Dropdown attributes not showing on Product Page

### ISSUE THREAD

**Issue by BuysTooMuch** [magento/magento2#8701]
### Steps to reproduce
1.  Using typical/stock Magento 2.1.2 installation using Luma theme & configurable products (on "color" attribute) 
2.  Upgrade site to 2.1.3 (or 2.1.4?)
3.  View product page

### Expected result
1.  Product page shows color drop-down before upgrade, disappears after

### Actual result
1.  Product page should show color dropdown

Trying to "Add to Cart" correctly shows error (because color choice is not set) but no way to do so

**Comment by BuysTooMuch** [comment]
Afterthought: Possibly related to Javascript/JQuery & Block loading?  https://github.com/magento/magento2/issues/7869

**Comment by BuysTooMuch** [comment]
The data is present but the control does not render.  From page source:

```
<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": {"attributes":{"93":{"id":"93","code":"color","label":"Color","options":[{"id":"4","label":"Red","products":["32"]},{"id":"5","label":"Blue","products":["33"]}],"position":"0"}},"template":"$<%- data.price %>","optionPrices":{"32":{"oldPrice":{"amount":"12.95"},"basePrice":{"amount":"12.95"},"finalPrice":{"amount":"12.95"}},"33":{"oldPrice":{"amount":"18.95"},"basePrice":{"amount":"18.95"},"finalPrice":{"amount":"18.95"}}},"prices":{"oldPrice":{"amount":"12.95"},"basePrice":{"amount":"12.95"},"finalPrice":{"amount":"12.95"}},"productId":"31","chooseText":"Choose an Option...","images":{"32":[{"thumb":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/thumbnail\/88x110\/beff4985b56e3afdbeabfc89641a4582\/i\/m\/img_0649.jpg","img":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/700x560\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0649.jpg","full":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0649.jpg","caption":null,"position":"3","isMain":true}],"33":[{"thumb":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/thumbnail\/88x110\/beff4985b56e3afdbeabfc89641a4582\/i\/m\/img_0651.jpg","img":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/700x560\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0651.jpg","full":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0651.jpg","caption":null,"position":"1","isMain":true},{"thumb":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/thumbnail\/88x110\/beff4985b56e3afdbeabfc89641a4582\/i\/m\/img_0652.jpg","img":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/700x560\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0652.jpg","full":"http:\/\/example.com\/pub\/media\/catalog\/product\/cache\/image\/7c7c2654335b07b056de0daef1e1ef78\/i\/m\/img_0652.jpg","caption":null,"position":"2","isMain":false}]},"index":{"32":{"93":"4"},"33":{"93":"5"}}},
                "jsonSwatchConfig": {"93":[]},
                "mediaCallback": "http://example.com/swatches/ajax/media/",
                "gallerySwitchStrategy": "prepend"
            }
        }
    }
</script>
```

**Comment by BuysTooMuch** [comment]
Found it.  This is a change in how swatches are handled in more recent versions, or perhaps in a multisite environment - whereas in previous versions you could populate "text swatches" by simply typing in a list of values (red, blue, black, etc) when you upgrade you will find that your attribute now has two columns.  The "admin" value will be your old values and the second column (which starts off as blank) will be the "display" value.  Populating this column (copying your colors into the second column) gives the control values to render.  Issue resolved.

**Comment by RonXS** [comment]
One more thing is that you need to select "Show attribute in store front" to make it show up.
Many have stumbled into this in the past.

**Comment by veloraven** [comment]
I'm closing this issue as it was resolved.
If you can still reproduce this issue, please create a new GitHub issue report.
