### ISSUE TITLE
Knockout.js Error During Checkout

### ISSUE THREAD

**Issue by tsmith1985** [magento/magento2#8702]
Knockout.js error occurs during checkout process. Reference to `$parent.getCode()` is not a function.

### Preconditions

- Magento CE v2.1.5
- PHP v7.0.14
- MySQL v14.14 Distrib 5.7.16, for osx 10.12

### Steps to reproduce
1. Sign into Magento store.
2. Add product(s) to cart.
3. Open browser dev tools -> console -> errors.
4. Click `Cart` in upper right nav.
5. Click `Go to Checkout`.

### Expected result
1. Should be able to complete checkout process without errors

### Actual result
1. Get a knockout.js error

```Uncaught TypeError: Unable to process binding "attr: function (){return {id:'billing-address-same-as-shipping-'+ $parent.getCode()} }"
Message: $parent.getCode is not a function
    at attr (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:214)
    at update (knockout.js:3659)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3004)
    at evaluateImmediate (knockout.js:1737)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1946)
    at knockout.js:3002
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:2854)
    at applyBindingsToDescendantsInternal (knockout.js:2836)```
```

![image](https://cloud.githubusercontent.com/assets/1539397/23336057/4733511e-fb78-11e6-9b49-f3c0b0de4e1f.png)

**Comment by strauss69400** [comment]
I have the same problem.
Impossible to resolve it.
Did you manage to find the problem?
Thanks

**Comment by deadlyw1re** [comment]
Did you manage to find the problem?
Got the same error after moving the billing address form

**Comment by strauss69400** [comment]
yes i resolve my problem in changing a parameter in configuration :
 Store > configuration > sales > order >Display Billing Address On

**Comment by deadlyw1re** [comment]
@strauss69400 I think the path you mentioned is incorrect, there is no 'order' option after 'sales'.

**Comment by strauss69400** [comment]
for me the path is correct. My website running with the version 2.1.*

**Comment by magento-engcom-team** [comment]
@tsmith1985, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by adamkaczmar** [comment]
Steps to reproduce are missing one step. So it will be:

## Steps to reproduce
1. In Stores > Configuration > Sales > Checkout, set _Display Billing Address On_ to _Payment page_.
2. Sign into Magento store.
3. Add product(s) to cart.
4. Open browser dev tools -> console -> errors.
5. Go to checkout (step with billing address form).

You will see error as described by @tsmith1985 and billing address form is not rendered properly.

The error still occurs on:

- Magento 2.1.7
- PHP 7.0.25
- Apache 2.4.18 (Ubuntu 16.04)
- MariaDB 10.0.31

**Comment by adamkaczmar** [comment]
Apparently it was theme template issue. In this case `getCode($parent)` should be used instead of `$parent.getCode()`.
