### ISSUE TITLE
unserialize issue on category pages after pulling latest code base

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#8703]
### Preconditions
1. Latest commit 

### Steps to reproduce
1. pull latest develop branch and run setup upgrade /purge cache etc.

### Expected result
1. Product swatches and filters load on category page

### Actual result
1. Product filters are blank and category pages with configured products load blank.

[2017-02-28 01:09:14] main.CRITICAL: Notice: unserialize(): Error at offset 0 of 100 bytes in /var/www/magento2/app/code/Magento/Swatches/Helper/Data.php on line 138 [] []

**Comment by AVoskoboinikov** [comment]
Hi, @caesarcxiv 

Please, have a look at issue https://github.com/magento/magento2/issues/9287 and check comment https://github.com/magento/magento2/issues/9287#issuecomment-294800693
