### ISSUE TITLE
Configurable product not showing without Media / Images

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#8704]
### Preconditions

1. Magento Community 2.1.3, 2.1.4 & 2.1.5 [and others maybe aswell?]
2. PHP 7, MYSQL 5.6 & 5.7
3. Migrated database from Magento Community 1.9

### Steps to reproduce

1. Install new code base from either composer or package from Magento.com
2. Connect new files to existing database - in my case I ran the installer and pointed to the existing database.
3. Use the standard themes to prove that its not a customisation issue - I tested with Luma.
3. Make sure you have some configurable product which are attached to categories.

### Expected result

1. The site should work with the new code base.
2. Navigate to category with configurable product
3. If images are not there, the placeholder should be shown and the product visable - this used to happen in <2.0.6 when I was on that strand. 

### Actual result

1. Configurable product are not shown. Layered navigation is shown. Simple Product are shown.
2. just to confirm, I reindexed, cleared cache, generated static content etc.
3. When I add the images, changed to developer mode and changed back to production mode. the products are shown. 

![screen shot 2017-02-28 at 12 48 35 pm](https://cloud.githubusercontent.com/assets/9780829/23389874/6c42c080-fdb6-11e6-9168-56ca8b0f01b5.png)
![screen shot 2017-02-28 at 1 04 36 pm](https://cloud.githubusercontent.com/assets/9780829/23389961/d788deec-fdb6-11e6-9062-d576b2a38795.png)

**Comment by victor-v-rad** [comment]
Hi @rkhoury82 

I see your configurable products are swatches. Magento Data Migration Tool cannot migrate swatches from Magento 1 right now. Maybe this is the reason.

**Comment by rudik99** [comment]
Hi @victor-v-rad - I migrated back on version 2.0 and configured the swatches post the migration. This issue appeared when I tried to upgrade from 2.06 to 2.1.3+ 
The issue was a critical one [along with some other critical bugs] so I moved my business to another platform as the instability in the CE product was too much for our business. Wish you all the best in making _Magento Great Again_ 😊 ill close the case
