### ISSUE TITLE
Order report bug 

### ISSUE THREAD

**Issue by godfeeder** [magento/magento2#8708]
Hi, 

In Magento EE 2.1.2, when i want to generate an order report, i've the error below : 
![error-order-report](https://cloud.githubusercontent.com/assets/23030465/23400360/13ca77e8-fda4-11e6-9003-7afa5b710063.JPG)

In fact, when the french langage is setted, the date are not formated in the correct format (US). 

Regards,

Gregory

**Comment by veloraven** [comment]
@godfeeder please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
