### ISSUE TITLE
Better di generation error message

### ISSUE THREAD

**Issue by spipu** [magento/magento2#8709]
Hi,

I generate the di with the following command : 

`bin/magento setup:di:compile`

If a error occurs, it display the reflexion error, but it does not give the name of the class that has the error.

Example: just change the asked type of a parameter of any constructor class to one type that does not exist, and launch the  di compilation. You will have that kind of error:

```
[ReflectionException]                            
  Class Smile\Map\Model\Map\string does not exist  
```

The verbose mode does not help.

A good think could be to change this line:

https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Code/Reader/ClassReader.php#L36

by this one: 

`$message = $e->getMessage().' on ['.$className.']';`

Regards,

Laurent

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Better-di-generation-error-message/idi-p/62457).

**Comment by okorshenko** [comment]
@spipu thank you for reporting the issue
@renatocason thank you for fixing this issue in PR: magento/magento2#8768
