### ISSUE TITLE
Replace Symfony2/Yaml in composer

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#871]
Is there any specific reason why we need to do: 

```"symfony/yaml": "2.3.x-dev",``` in composer.json file ?

**Comment by verklov** [comment]
MAGETWO-32346

**Comment by vpelipenko** [comment]
@jamescowie, changes in the source code according issue you placed are already published and available from 0.42.0-beta5. Are you OK with that? Can we close this issue?

**Comment by jamescowie** [comment]
Hello. Thanks for the reply. After testing I am happy for this to be closed now..
