### ISSUE TITLE
Checkout shows strings that isn't even anywhere in the filebase - Magento 2.0.9

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#8715]
### Preconditions

1. As Magento 2.0.9 *still* lacks of a functional translation system you need to copy and edit `*.js`-files in order to rename JS strings 
2. Have Magento 2.0.9. installed
3. have a custom theme and a custom module to extend/replace stuff 

### Steps to reproduce

1. copy `shipping.js` and `payment.js` to your theme (-> `Magento_Checkout/web/js/view/´)
2. change strings to desired content

### Expected result

1. Strings get translated

### Actual result

1.  Strings get not translated

Currently the string "Review & Payment" is nowhere in the whole system, but gets shown on the cart anyway. 

STRING IS IN FRONTEND:
![](https://i.stack.imgur.com/Ro9oo.png)

STRING IS NOWHERE IN FILE SYSTEM:
```
[~/public_html/mageroot]# grep -rl "Review & Payments" *
CHANGELOG.md
vendor/magento/magento2-base/CHANGELOG.md
vendor/splendidinternet/mage2-locale-de-de/de_DE.csv
```

Appearance in de_DE.csv:
```
Review & Payments,Übersicht und Zahlung
Review &amp; Payments,Übersicht und Zahlung
```

The string is still not translated.

**Comment by korostii** [comment]
Well, actually the string is present right there in the code:
https://github.com/magento/magento2/blob/2.0/app/code/Magento/Checkout/view/frontend/web/js/view/payment.js#L54

But there are indeed some unresolved issues with the js translation system. I would guess that you were hit by one of these
https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=is%3Aissue%20js-translation.json%20

**Comment by magento-engcom-team** [comment]
@grasdaggel, thank you for your report.
We've created internal ticket(s) MAGETWO-81812 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@grasdaggel, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
