### ISSUE TITLE
Delete item from minicart on cart page does not reload cart page

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#8717]
### Preconditions

1. Magento 2.1.4 CE
2. PHP 7.0

### Steps to reproduce

1. Add item to cart
2. Go to cart
3. Delete item from minicart

### Expected result

1. Item is removed from minicart and cart

### Actual result

1. Item is removed from minicart but remains in cart

After deleting an item from the minicart, the cart page should reload.

**Comment by henk-hypershop** [comment]
Already referred to in:
https://github.com/magento/magento2/issues/3566

**Comment by veloraven** [comment]
@henk-hypershop thank you for your report and your update.
I'm closing this issue as duplicate.
