### ISSUE TITLE
Store view specific redirects not working 

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#8718]
### Preconditions
1. Magento 2.1.5

### Steps to reproduce
1. Create a custom store view 
2. Create a 302 redirect specific to the store view
![image](https://cloud.githubusercontent.com/assets/19289786/23414390/a0b662dc-fdd3-11e6-9348-485060ff3922.png)

3. reindex
4. change to the store view specified in the redirect
5. go to the page wishlist (request path)

### Expected result
1. page should redirect to the homepage (target path)

### Actual result
1. No redirect occurs, and Magento\UrlRewrite\Controller\Router match() ln 60 is not hit

What i don't understand is that some redirects work and others do not, for example about-us redirects correctly for the custom store view, but contact and checkout do not?

**Comment by orlangur** [comment]
Do you mean "store" by "store view"?

I don't see any store view-specific logic:
https://github.com/magento/magento2/blob/develop/app/code/Magento/UrlRewrite/Setup/InstallSchema.php#L76
https://github.com/magento/magento2/blob/develop/app/code/Magento/UrlRewrite/Controller/Router.php#L81

**Comment by sma09sjb** [comment]
No, I mean store view. I want to create redirects specific to 'Protocol Pad Store VIew'.

![image](https://cloud.githubusercontent.com/assets/19289786/23453955/589e8062-fe62-11e6-8fc3-c6df8ed456a8.png)

When I navigate to Url Rewrites, there is a column Store View in the grid.

I understand in the database that a store view, has a unique store_id

![image](https://cloud.githubusercontent.com/assets/19289786/23454365/e525e7f4-fe63-11e6-82a5-4bcdbf661f06.png)

In the database against the redirect the store_id matches the store_id of 'Protocol Pad Store View'.

When I add debugging code to that method i can see that for some pages, such as /wishlist the method isn't even being hit, it's not that it's not finding the redirect. 

When would that match method not be hit, is it the load order in the etc/config.php I wonder?

**Comment by orlangur** [comment]
Yeah, I see, there is `Store View` column in URLRewrites grid.

It is just the difference between UI and code: `store view` in UI corresponds to `store` in code, `store` in UI - to `store_group` in code or something.

**Comment by sma09sjb** [comment]
Yeah @orlangur thanks for this, i find that a bit confusing myself. I've updated my response above. 

It's not even hitting match() which i find very strange.

**Comment by magento-engcom-team** [comment]
@sma09sjb, thank you for your report.
We've created internal ticket(s) MAGETWO-81743 to track progress on the issue.

**Comment by p-bystritsky** [comment]
Fixed in 2.2-develop branch.
