### ISSUE TITLE
Importing and aliases vs. fully qualified namespaces

### ISSUE THREAD

**Issue by ldusan84** [magento/magento2#872]
I think that Magento2 should import namespaces and use aliases instead of using fully qualified namespaces all over the place. 

Here is an example.

What I suggest is that instead of: 
```
throw new \Magento\Framework\Model\Exception(
    __('Invalid login or password.'),
    self::EXCEPTION_INVALID_EMAIL_OR_PASSWORD
);
```

We could have:
```
use \Magento\Framework\Model\Exception as MagentoException
/* ... */
throw new MagentoException(
    __('Invalid login or password.'),
    self::EXCEPTION_INVALID_EMAIL_OR_PASSWORD
);
```
Here are the benefits from this:

1. With importing namespaces keyword at the first few lines of a class you actually get a nice documentation of your class dependencies. Everything that class uses is in those first few lines. It makes dependencies explicit.

2. If something changes in the future, you would only need to change it in one place, in import declaration and the alias remains. With fully qualified namespaces you would need to find them everywhere in class and change. 

3. Less confusion if you have similar namespaces, you can give them different aliases.

4. All major frameworks use importing/aliases over fully qualified namespaces.

Let me know what you think.

**Comment by verklov** [comment]
MAGETWO-32347

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Importing-and-aliases-vs-fully-qualified-namespaces/idi-p/46716).

**Comment by dresh** [comment]
use PHPstorm
