### ISSUE TITLE
Logo for Transactional Emails not uploading properly

### ISSUE THREAD

**Issue by InternetMedicineMan** [magento/magento2#8722]
When uploading a new logo for Transactional Emails, the logo will look fine and save, but when you return to the setting the logo will show a dead link. Additionally, when testing the email the logo did not change.

After investigating the issue I found that the logo was uploaded on the file system to:
pub/media/logo/stores/1/<filename>
But when I looked at the path of the dead image it was expecting it at:
pub/media/email/logo/stores/1/<filename>

Once I moved the file to the place it appeared to be looking for it, the dead link was no longer an issue and emails now had the proper logo. But every time I change the logo I have to manually move it to the correct location.

### Preconditions
1. Magento 2.1.5
2. PHP 5.6

### Steps to reproduce
1. Visit: Content >> Design >> Configuration >> (Select Store) >> Transactional Emails
2. Upload an image

### Expected result
1. Logo should change in the emails without needing to manually move it.

### Actual result
1. Logo is uploaded to the wrong location and requires manual intervention

**Comment by orlangur** [comment]
See https://github.com/magento/magento2/issues/5916#issuecomment-236513767

**Comment by InternetMedicineMan** [comment]
Sorry, duplicate issue, I did a search but missed it in the open issues.
