### ISSUE TITLE
Magento 2.1.5 - Checkout no notification/error message displayed

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#8726]
**Preconditions**
Magento 2.1.5
PHP version 7.0.8
MySQL version 5.7.13

**Steps to reproduce**
Checkout page
Input sample credit card number: 4111111111111111 / 4012888888881881
with expiry date Dec. 12 2022
with CV Number: 123

**Expected result**
Error message/notification message that will say the card number is a sandbox test number or whatever message that will remind the user that the card is not valid for purchasing an items.

**Actual result**
No message display.

Screenshots:
https://www.screencast.com/t/Iufr1Tu0MENY
https://www.screencast.com/t/zm3MAMCRwF

**Comment by mrkhoa99** [comment]
@noprobz09 should check the Response on the Browser: Inspect Element > Check Network.

**Comment by noprobz09** [comment]
Hello @mrkhoa99 ,

Below are the response from transact.dll and 1/

Screenshots:
https://www.screencast.com/t/DBaOj9mv7k
https://www.screencast.com/t/7ZjCHzwGr

But there is no error message displayed on the frontend.

**Comment by YevSent** [comment]
Hi, @noprobz09, please, specify payment method which you use, it looks like Authorize.net but with some customizations. Also, please, post debug log with transaction details.

**Comment by noprobz09** [comment]
Hello @joni-jones,

Im currently using Authorize.net Direct Post payment method. 

Screenshots:
https://www.screencast.com/t/YZ0nGmhQtci
https://www.screencast.com/t/4WGjj0kK


~Thanks :)

**Comment by YevSent** [comment]
As I understand you are using production mode for Authorize.net. Please, post transaction details from debug log and response from `transact.dll`, without response details from Authorize.net it's hard to understand what happens wrong.

**Comment by YevSent** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks.

If you still can reproduce the issue, please, be free to reopen it.

**Comment by ianfp** [comment]
The problem is that I've scrolled down the screen to enter my credit card info, and so the error message appears off-screen.

To make matters worse, it disappears after a few seconds (!), so if I don't happen to scroll up quickly, I never see it.

@joni-jones I can post the transaction details, etc, if you insist, but it doesn't seem relevant.

**Comment by orlangur** [comment]
@ianfp such issue already reported as https://github.com/magento/magento2/issues/8977, so, there is no need to reopen this one.

**Comment by ianfp** [comment]
Thank you, @orlangur.
