### ISSUE TITLE
Transactional Emails Logo

### ISSUE THREAD

**Issue by radhagobinda** [magento/magento2#8728]
### Preconditions

1. Version: Magento 2.1.3
2. PHP 7
3. MYSQL 5.7

### Steps to reproduce

1. 
![download](https://cloud.githubusercontent.com/assets/19976130/23448448/08e90992-fe77-11e6-9d9d-09b00481e8ed.png)

### Expected result

1. The **Transactional Emails** under Theme-> Configuration tab, when I upload the logo for transaction email then this logo uploaded successfully but this is not appear in back-end. If you check it my screenshot then you can understand the issue. 

The real path of this image is: pub/media/email/logo/stores/1/logo.png
But it saved in pub/media/logo/stores/1/logo.png
 **email** folder is missing. 

Please check this issue. I hope this is a bug of this version. Please check it and let me some solution for this issue.

**Comment by mbrinton01** [comment]
Hello @radhagobinda, thank you for reporting this issue.  The internal ID is MAGETWO-53010 and it has been fixed in the develop branch.  Commit: https://github.com/magento/magento2/commit/23103c03c527fe1ed3e1a3be691436818b7963fe

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
