### ISSUE TITLE
magento 2.0.7 product image magnifier not woring in Internet Explorer 

### ISSUE THREAD

**Issue by kvSanthosh** [magento/magento2#8729]
Hi,

in Internet explorer browser the product image magnifier is not working when we click mouse left button. But its magnifying on right click. Any one can provide a solution?? Thanks.

**Comment by pboisvert** [comment]
Which version  of IE are you using?

**Comment by kvSanthosh** [comment]
IE 11

**Comment by kvSanthosh** [comment]
Sorry It got closed by mistake. Please comment further

**Comment by magento-engcom-team** [comment]
@kvSanthosh, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
