### ISSUE TITLE
Setup Wizard in Magento2 Broken after Composer Update

### ISSUE THREAD

**Issue by gx2g** [magento/magento2#8731]
I installed Magento 2 on GoDaddy server using one click install. Everything is running smoothly, and then I noticed that I needed to update my composer and activate some PHP extensions (xsl, zip) which I seen a notification in command-line while trying to update composer. 

Activated those extensions at GoDaddy then successful ran the composer update. my commands were as followed.

composer require magento/product-community-edition 2.0.5 --no-update
(This created a .json file which I didn't have one before I believe).
composer update
    rm -rf var/di var/generation
    php bin/magento cache:flush
    php bin/magento setup:upgrade
    php bin/magento setup:di:compile
    php bin/magento indexer:reindex

All went well but now when I jump into the admin of Magento 2 and go to setup wizard. it's broken??? All I see is some Angular.js errors. any help fixing this? I didn't mean to mess this one up.

**Comment by dimaportenko** [comment]
@gx2g how did you fix it?

**Comment by gx2g** [comment]
I did a clean install and followed the steps I found in google search to resolve the issue.
