### ISSUE TITLE
The country drop-down list display incorrect after upgrade to 2.1.4 in Admin

### ISSUE THREAD

**Issue by tanloi3004** [magento/magento2#8732]
### Preconditions

1. Magento 2.1.4
2. Setup multiple websites and set Allow Countries(Store => Configuration => General => Country Options) per website are different. 

### Steps to reproduce

1. Go to Admin, All Customers
2. Create/Edit a customer
3. Add/Edit an address, the country drop-down box always shows allowed countries of default store. 

 `/**
     * Retrieve all options
     *
     * @return array
     */
    public function getAllOptions()
    {
        if (!$this->_options) {
            $this->_options = $this->_createCountriesCollection()->loadByStore(
                $this->getStoreResolver()->getCurrentStoreId()
            )->toOptionArray();
        }
        return $this->_options;
    }`

The Function getAllOptions() of class Magento\Customer\Model\ResourceModel\Address\Attribute\Source use default store at here. (Admin Scope) 
### Expected result
The country drop-down box shows the countries matching config value per website(assigned to customer). 
### Actual result

1. [Screenshot, logs]
The country drop-down box always list countries of default store.

**Comment by mimarcel** [comment]
@tanloi3004 This may be the same issue as described and fixed in #9429 .

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70052

**Comment by magento-engcom-team** [comment]
@tanloi3004 thank you for your report.
The fix for this issue is already available in release 2.2.0

**Comment by VonKavalier** [comment]
I see that the TODO is done in the 2.3 branch. Could you provide a link where it's fixed in 2.2 ? I wasn't able to see the fix in my 2.2 local installation, and didn't find anything proving it has been solved in 2.2 except those labels.
