### ISSUE TITLE
The path ".:///var/www/magento2/var/www/magento2/" is not writable

### ISSUE THREAD

**Issue by kiazhi** [magento/magento2#8733]
Unable to Save Content Configuration due to recursive folder path that does not exist at all. This issue will occur when you attempt to save the configuration after making any changes to the configuration.

### Preconditions
1. Magento 2.2.0-Dev
2. PHP 7.0
3. MySQL 5.7.17
4. Apache 2.0
 

### Steps to reproduce
1. Deploy Magento2 using Composer
2. Setup Magento2
3. Login to Admin site
4. Select Content -> Configuration -> Edit Default Store View
5. Select a Theme in dropdown menu
6. Select Save Configuration

### Expected result
1. Save the Configuration without any issue

### Actual result
1. An Error Message is prompted with the following message:
The path ".:///var/www/magento2/var/www/magento2/" is not writable.

**Comment by Fangkey** [comment]
I met the same problem even without step 5.

**Comment by ghost** [comment]
Same here.
I tried to modify the robots.txt at Stores->Configuration->Design
Is there a fix?

**Comment by MalcolmPrince** [comment]
I was about to switch theme, but cannot go any further. I got the same error showing up. Are there any solutions ? Using Magento ver. 2.2.0-dev

**Comment by antviktorov** [comment]
hey guys, the same for me, is anyone have a chance to fix this?
This wrong path is going to make me mad.
Using Magento ver. 2.2.0-dev

**Comment by antviktorov** [comment]
My case was connected with missed robots.txt file, need to set 664 rights for it as well.

> Stack trace
> The path "{path}" is not writable#0 /home/mrmage.com/public_html/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(248): Magento\Framework\Filesystem\Directory\Write->assertWritable('.') #1 
> /home/mrmage.com/public_html/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(264): Magento\Framework\Filesystem\Directory\Write->openFile('robots.txt', 'w+') #2 
> /home/mrmage.com/public_html/app/code/Magento/Config/Model/Config/Backend/Admin/Robots.php(86): Magento\Framework\Filesystem\Directory\Write->writeFile('robots.txt', 'false') #3 
> /home/mrmage.com/public_html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Config\Model\Config\Backend\Admin\Robots->afterSave()

**Comment by johnny-longneck** [comment]
Can confirm this. Magento should fix this for the Nginx configuration sample.

**Comment by magento-engcom-team** [comment]
@kiazhi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0
