### ISSUE TITLE
Tax is not being calculated

### ISSUE THREAD

**Issue by kbrakband** [magento/magento2#8737]
I've tried nearly every single configuration option in my Magento 2 backend, so I think this is a bug. I have a Dutch shop and I'm trying to use 21% tax. My shop keeps showing €0,00 for the tax in the cart and checkout process.

**Here's the tax rule that I use:**
![image](https://cloud.githubusercontent.com/assets/4663689/23458727/abac52aa-fe7d-11e6-854d-80167f328388.png)

**Tax Zones and Rates:**
![image](https://cloud.githubusercontent.com/assets/4663689/23458760/cb309ece-fe7d-11e6-9469-58b4c644ced0.png)

**Tax configuration settings in which I've probably tried every possibility:**
![image](https://cloud.githubusercontent.com/assets/4663689/23458812/0220e65a-fe7e-11e6-955a-7b7a38f99ef8.png)

![image](https://cloud.githubusercontent.com/assets/4663689/23458821/1259935a-fe7e-11e6-9eb1-d0f53f9208f1.png)

![image](https://cloud.githubusercontent.com/assets/4663689/23458828/184f309e-fe7e-11e6-9080-2f741d7dc952.png)

**Shipping Origin:**
![image](https://cloud.githubusercontent.com/assets/4663689/23458853/2ecfdc9c-fe7e-11e6-8067-ce67681ef6a2.png)

**The outcome in my cart**
![image](https://cloud.githubusercontent.com/assets/4663689/23458909/6124f3f8-fe7e-11e6-8bc8-97a1fe2d9523.png)

**Comment by mbrinton01** [comment]
Hello @arvenzis. Please use GitHub for bug reports only. For your question about how to configure the tax settings in Magento, please post on the Magento 2 [Forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2).

**Comment by Ctucker9233** [comment]
@mbrinton01 The first sentence of the report says "I've tried nearly every single configuration option in my Magento 2 backend, so I think this is a bug." Clearly, @arvenzis thinks it's a bug. Can you explain why it's not a bug?

**Comment by mbrinton01** [comment]
@arvenzis What is the customer tax class in this test? You have the rule set for "B2B" but the default class as "Retail Customer"

**Comment by kbrakband** [comment]
Customers cannot order if they're not logged in. The customer I use as a test is in the group General, which is set to Retail Customer.

**Comment by choukalos** [comment]
Tax Rule doesn't look right.  You're showing product tax class = 21%.  In addition your rule is for B2B customer tax class .  Sounds also like your customer group / customer tax class is set incorrectly -> you should change your Tax Rule to use Retail Customer as the customer tax class , likely you'll want to change the product tax class to = 'Taxable Goods' which is the default product tax class.

**Comment by kbrakband** [comment]
Thank you for your comment choukalos. I've tried doing this, but unfortunately nothing changes.

**Comment by annelise83** [comment]
Hi, realize this thread is old but commenting as I struggled with the same for hours and hours.  In my case, turns out I just had to change the setting:

Stores> Configuration > Sales > Shipping Settings > Origin

as my tax rule was configured as "Greece" while my origin was somehow set to "United kingdom".  Flipping it to "Greece" fixed the tax calculation issue for me.
