### ISSUE TITLE
Mageplaza seo module causing issues in adding/editing products or categories in adminbackoffice

### ISSUE THREAD

**Issue by yogeshraghav-dev** [magento/magento2#8739]
### Preconditions

1. I have installed module Mageplaza_Seo.
2. run setup:upgrade and setup:di:compile
3. disabled the module using module:disable Mageplaza_Seo
4. I have deleted the folder from ftp app/code/Mageplaza_Seo
5 run setup:di:compile and logged in backoffice and try adding/editing product iam getting error.
### Steps to reproduce

1. I have deleted the folder Mageplaza_Seo from app/code
2.  when iam adding or editing product or categories from dashboard iam getting error.
3. 

### Expected result

1. I should get extra config from SEO as field like Robots etc

### Actual result

1. error log:
a:4:{i:0;s:54:"Class Mageplaza\Seo\Model\Source\Robots does not exist";i:1;s:10709:"#0 /home/shelltag/public_html/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Mageplaza\\Seo\\M...')
#1 /home/shelltag/public_html/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Mageplaza\\Seo\\M...')
#2 /home/shelltag/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Mageplaza\\Seo\\M...')
#3 /home/shelltag/public_html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Seo\\M...', Array)
#4 /home/shelltag/public_html/magento2/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('\\Mageplaza\\Seo\\...', Array)
#5 /home/shelltag/public_html/magento2/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(537): Magento\Framework\Validator\UniversalFactory->create('\\Mageplaza\\Seo\\...')
#6 /home/shelltag/public_html/magento2/var/generation/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1129): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#7 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(561): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getSource()
#8 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(337): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->setupAttributeMeta(Object(Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor), 'search-engine-o...', 4)
#9 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(309): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->getContainerChildren(Object(Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor), 'search-engine-o...', 4)
#10 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(285): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->addContainerChildren(Array, Object(Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor), 'search-engine-o...', 4)
#11 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(245): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->getAttributesMeta(Array, 'search-engine-o...')
#12 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(68): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav->modifyMeta(Array)
#13 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Element/UiComponentFactory.php(269): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta()
#14 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#15 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#16 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#17 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#18 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#19 /home/shelltag/public_html/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#20 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#21 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#22 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#23 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#24 /home/shelltag/public_html/magento2/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#25 /home/shelltag/public_html/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#26 /home/shelltag/public_html/magento2/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#27 /home/shelltag/public_html/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#28 /home/shelltag/public_html/magento2/vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#29 /home/shelltag/public_html/magento2/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Edit->execute()
#30 /home/shelltag/public_html/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->execute()
#31 /home/shelltag/public_html/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent('dispatch', Array)
#34 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminAuthentica...')
#35 /home/shelltag/public_html/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminMassaction...')
#38 /home/shelltag/public_html/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /home/shelltag/public_html/magento2/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /home/shelltag/public_html/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#44 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#45 /home/shelltag/public_html/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#46 /home/shelltag/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /home/shelltag/public_html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /home/shelltag/public_html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 /home/shelltag/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#50 /home/shelltag/public_html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#51 {main}";s:3:"url";s:110:"/backoffice/catalog/product/edit/id/2047/key/2f31208c6b348979f5044ea8128732a6108f9aa8e8eb7ca983a9b157551ad6b2/";s:11:"script_name";s:10:"/index.php";}

**Comment by mrkhoa99** [comment]
@hitman3043 seem that you're using this extension: https://github.com/mageplaza/magento-2-seo-extension. I think it's better if you open one issue on its Git module.

**Comment by mbrinton01** [comment]
@hitman3043 for support with this extension, please contact mageplaza directly on their GitHub.

**Comment by Ctucker9233** [comment]
@hitman3043 Disabling and deleting a module won't completely remove it. You have to clear your cache pub/static var/cache var/page_cache var/generation

**Comment by joelmats** [comment]
@hitman3043 If this was because you removed the extension, I also had the issue. Had to delete rows in the eav_attribute table.
