### ISSUE TITLE
Invalid design of dev/tools/grunt/configs/combo

### ISSUE THREAD

**Issue by andrew-aladev** [magento/magento2#8741]
### Preconditions

Any magento 2 version.

### Steps to reproduce

1. Add any grunt task that will be a dependency for your theme. For example automatic generation of `sprite.less`.
2. `grunt exec:<theme>`

### Expected result

1. All dependencies should be executed after `clean` and before `dev:source-theme:deploy`.

### Actual result

1. `magento dev:source-theme:deploy` failed because theme is not ready for deployment.
> Unable to get content for '*/sprite.less'

File is [here](https://github.com/magento/magento2/blob/develop/dev/tools/grunt/configs/combo.js#L16).

**Comment by magento-engcom-team** [comment]
@andrew-aladev, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
