### ISSUE TITLE
Customer added in API could not login to Store

### ISSUE THREAD

**Issue by Jen143** [magento/magento2#8745]
I was able to successfully added the Customer through API (POST http://magentohost/api/rest/customers)
and checked it in the Magento Admin. However, then I tried to login using the credential I provided in the API, it says "Invalid login or password". When I tried to reset the password in the Magento Admin website, I could login the store.
Here is the xml code:
`var doc = new XmlDocument();
            XmlDeclaration docNode = doc.CreateXmlDeclaration("1.0", "UTF-8", null);
            doc.AppendChild(docNode);

            XmlNode rootNode = doc.CreateElement("magento_api");
            doc.AppendChild(rootNode);
            _xmlHelper.AddNode(doc, rootNode, "firstname", account.FirstName);
            _xmlHelper.AddNode(doc, rootNode, "lastname", account.LastName);
            _xmlHelper.AddNode(doc, rootNode, "password", "1P@ssw0rd2345");
            _xmlHelper.AddNode(doc, rootNode, "email", account.Email);
            _xmlHelper.AddNode(doc, rootNode, "website_id", "1");
            _xmlHelper.AddNode(doc, rootNode, "group_id", "1");

            return doc.OuterXml;`

And also, I've tried getting all the customer to check if there's something wrong or different with the details but it seems fine with all the website_id and group_id as 1. I would like to ask some help to fix this problem. Furthermore, I would like to know if there's a way to reset the password through API because I want to email the customer created with the credentials however it seems like when a customer is created it does not email the customer the credential but it does email when someone reset the password for that customer.

Thank you.

**Comment by mbrinton01** [comment]
@Jen143 what version of Magento are you using? I could not reproduce this issue. Also, it's not a good practice to email passwords to customers.

The behavior is as follows:

Scenario | Outcome
------------ | -------------
User created without password defined | User is emailed link to create password
User created with password defined | User is emailed notification with statement that password = _"Password you set when creating account"_
Admin Resets Password | User is emailed link to update password

**Comment by mbrinton01** [comment]
Also, you can trigger a password reset email to a user with the route `PUT /V1/customers/password`

**Comment by Jen143** [comment]
Hi mbrinton01,
I am using REST in Magento with this endpoint /api/rest/customers
[http://devdocs.magento.com/guides/m1x/api/rest/introduction.html](url)

**Comment by mbrinton01** [comment]
Which version are you using?

**Comment by Jen143** [comment]
version 1 since the Magento ver. 1.9.3.1

**Comment by mbrinton01** [comment]
Hello @Jen143, this repository is only for reporting bugs in Magento 2.0+.  For questions on all Magento 1.x versions, please post on the [Magento Forums](https://community.magento.com/t5/Core-Technology-Magento-1-x/ct-p/technology).
