### ISSUE TITLE
Can not set tier price to product configurable and it apply to all child product !!!

### ISSUE THREAD

**Issue by goben2489** [magento/magento2#8747]
### Preconditions

1.  Magento version 2.1.4
2. PHP 5.6
3. MySQL 5.6

### Steps to reproduce

1. Create one product configurable
2. Config child product list
3. Set tier price for all child product

### Expected result

1. In magento 1, if i need set tier price to all child product with same price, i set tier price at product configuable, it so easy.

### Actual result
1. In magento 2, if i want set a tier price for all child product, i have to go every child product to config it, if i have 20 30 child product or more than, i have do it 20 30 time ?

![screen shot 2017-03-02 at 10 23 02 am](https://cloud.githubusercontent.com/assets/14970253/23491671/4090f196-ff32-11e6-94e0-21f8cff597a7.png)
If i want set tier price for all child product in image, i have to go every product to config.
how do it easier ?

**Comment by carb0nknight** [comment]
This seems like an essential feature when it comes to configurable products. It's not feasible to individually configure tier pricing on configurable products when there are literally hundreds of product configurations available. When you have a product available in 20+ colors, and 5+ sizes, this quickly gets out of hand.
 
If we can't get the option to configure tier pricing on the configurable products itself, it would be nice to be able to create tier groups, and assign products to those groups.

**Comment by goben2489** [comment]
i have resolved

PHP 5.6
Magento 2.1.5

Create Nomal Product
1. Choose attribute set
2. Set price and tier price because at now advanced price link have showing
3. Setup Configuable Product
4. After setup, advaced price have hidden

Edit Product
1. Add js to show advanced price link
2. Go to edit tier price if you want
3. Save success, tier price have update

**Comment by carb0nknight** [comment]
@goben2489 Coming up with a workaround that fits YOUR needs, is not a resolution to the issue itself. I believe this feature existed in version 1.x, and has existed as a Magento 2 feature request for months (https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-products-tier-prices-and-attributes/idc-p/63815#M2735), so there are many people encountering this issue.

**Comment by lundzern** [comment]
Any progress on this issue?

**Comment by carb0nknight** [comment]
@lundzern unfortunately I haven't heard/seen any updates on this issue at all, and haven't had the time to try and implement something myself yet

**Comment by goben2489** [comment]
i think it have some problem with migrate from magento 1 to magento 2 beacuase magento1 use price and tier price of parent product, but magento 2 use front child product, i think have commnad or setting can change logic cal price of product better.

**Comment by magento-engcom-team** [comment]
@goben2489, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
