### ISSUE TITLE
403 forbidden for "Save Config" button

### ISSUE THREAD

**Issue by ThemePaper** [magento/magento2#8748]
### Preconditions

1. Linux
2. Magento 1.7, PHP 5.6

### Steps to reproduce

1. Admin > System > Configuration > Design > then click "Save Config" button

### Expected result

1. 403 Forbidden

I have transfer magento to another hosting then this issue happen.
All pages is working but not for this page. (Admin > System > Configuration > Design)

Really appreciate for your help

Thank you

**Comment by thlassche** [comment]
Have you deployed the static files and are your folder and file permissions correct?

**Comment by daim2k5** [comment]
@ThemePaper is hat correct that you use magento in version 1.7?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
