### ISSUE TITLE
Custom Email Luma Logo

### ISSUE THREAD

**Issue by Me7z** [magento/magento2#8749]
I created a custom Mail with my own helper class. The mail is send correctly but Magento takes the logo and footer specified in luma theme. I created my own footer.html in my theme but this didn't work. Still takes Luma for custom mails. I got this problem in any project i am sending custom mails.

**Comment by orlangur** [comment]
Try using search: https://github.com/magento/magento2/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20email%20logo%20

**TL;DR:** it is fixed in `develop` but not released in `2.0.x` or `2.1.x` yet, you can cherry-pick commit to your instance.

**Comment by Me7z** [comment]
Can't find the same problem. The results are always because of the transaction emails not for custom mails ?

**Comment by orlangur** [comment]
Sorry, too narrow search, there are also some open issues.

This looks like a way to fix logo: https://github.com/magento/magento2/issues/7949#issuecomment-269307969

>  results are always because of the transaction emails not for custom mails

If behavior is the same then most likely they share some code between each other.

**Comment by vrann** [comment]
@Me7z as far as there is a commit for the same issue, closing current issue.
