### ISSUE TITLE
Multi-domain setup results in 302 redirect loop in backend and frontend

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#8750]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.10

### Steps to reproduce
1. Single website
2. Multi-store
3. Multi-domain

### Expected result
1. When going to the domain of a store view I expect to see that right store view (language).
2) When I go to the default domain backend I expect to see the backend

### Actual result
1. All domains end up in a redirect loop
2. Both frontend and backend

### Temporary solution backend
When I add the following config to the database my backend works, the redirect is not present anymore.

> admin/url/use_custom 1
> admin/url/custom http(s)://example.com

### Temporary solution frontend
Adding the following code to the pub/index.php helps to solve the redirect issue.

$domain2store = array(
	'www.example.com' => 'default',
	'www.example.nl' => 'nl',
);

if (isset($domain2store[$_SERVER['HTTP_HOST']])) {
	$storecode = $domain2store[$_SERVER['HTTP_HOST']];
}

$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = $storecode ?? '';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'store';

if (isset($params['REDIRECT_MAGE_RUN_CODE'])) {
	$params['MAGE_RUN_CODE'] = $params['REDIRECT_MAGE_RUN_CODE'];
}

if (isset($_SERVER['REDIRECT_MAGE_RUN_TYPE'])) {
	$params['MAGE_RUN_TYPE'] = $params['REDIRECT_MAGE_RUN_TYPE'];
}

### Special thanks
After I saw REDIRECT_MAGE_RUN_CODE in $_SERVER this article helped me to the solution.
[https://www.getpagespeed.com/web-apps/magento/magento-multistore-apache
](https://www.getpagespeed.com/web-apps/magento/magento-multistore-apache
)

**Comment by IlnitskiyArtem** [comment]
Hi, @rikwillems .
Thanks for the feedback.
Please add more details to your description of the steps you followed when identifying this issue. How do you configured multidomains/stores before found this temporary solution?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
