### ISSUE TITLE
i want to creatat buynow(chekout)button on productpage ?

### ISSUE THREAD

**Issue by rab14191** [magento/magento2#8752]
i want to create buynow button on product page  add to cart and  buynow both button  requied

i m useing magento 2.1.3 verion  ...

**Comment by mbrinton01** [comment]
Hello @rab14191. Please use GitHub for bug reports only. For your question about how to customize the product page in Magento, please post on the Magento 2 [Forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2).
