### ISSUE TITLE
Configurable variations can't import when delimiter is set as Pipe `|`

### ISSUE THREAD

**Issue by surfer190** [magento/magento2#8754]
When you import products and set the Multiple value separator as a pipe `|`.
The configurable variations will not work.

### Preconditions

Magento Version: `2.1.5`
Php version: 7.0.15`
Mysql version: `5.7.17`
Product set has a `configurable product`

### Steps to reproduce

1. Export products that include a configurable product
2. Change the delimiter within fields to a `pipe` (The `configurable_variations` will be exported as `pipe` seperating multiple key value pairs seperated by a `,`) eg: `sku=shirt-black,color=Black|sku=shirt-red,color=Red`
3. Import the products with  Multiple value separator as a pipe `|`

### Expected result

1. Simple products / variations are associated with the configurable product

### Actual result

1. Simple products are not associated with the configurable product

The issue is the file `magento/module-configurable-import-export/Model/Import/Product/Type/Configurable.php`

It is hardcoded to use the seperator: `ImportProduct::PSEUDO_MULTI_LINE_SEPARATOR` which is a `|`. Then it uses the `$this->_entityModel->getMultipleValueSeparator()` seperator you set as the delimiter of key value pairs. Which is clearly not possible as the delimiters need to be different.

**Comment by magento-engcom-team** [comment]
it is a duplicate #11026

**Comment by surfer190** [comment]
Semantics, but it can't be a duplicate.
If this issue was reported on 2 March and the apparent duplicate in late September.
But whatev's

**Comment by Kipperlenny** [comment]
I got the same error in Magento 2.2.0

**Comment by avoelkl** [comment]
I can confirm this is still an issue in Magento 2.3.2

Field separator: ;
Multiple value separator: |

With this combination configurable attributes are not imported correctly.
Edit: The configurable product is created but simple products are not assigned correctly as the wrong multi value separator makes does a weird expodle() of the variations.

**Comment by erik4github** [comment]
Still happening in 2.3.4.

It's basically impossible with import configurable variations AND product categories at the same time - and if it is the documentation doesn't clearly list how.

Example for a configurable product: 

`config_variations` as `sku=1,color=red,size=Small|sku=2,color=blue,size=Small` 

`categories` as `Default Category|Default Category/Products|Default Category/Products/Shirts|Default Category/SomeOtherCategory`

Field separator: ,
Multiple value separator: |

will lead to the categories being created correctly, but the product variations won't associate with the original configurable SKU. 

If you switch the Multiple value separator to "," - then the product variations will correctly associate with the configurable product, but instead of them being assigned to `Default Category/SomeOtherCategory` - a brand new category at the top of the category hierarchy gets created.

**Comment by notyouranon** [comment]
> Still happening in 2.3.4.
> 
> It's basically impossible with import configurable variations AND product categories at the same time - and if it is the documentation doesn't clearly list how.
> 
> Example for a configurable product:
> 
> `config_variations` as `sku=1,color=red,size=Small|sku=2,color=blue,size=Small`
> 
> `categories` as `Default Category|Default Category/Products|Default Category/Products/Shirts|Default Category/SomeOtherCategory`
> 
> Field separator: ,
> Multiple value separator: |
> 
> will lead to the categories being created correctly, but the product variations won't associate with the original configurable SKU.
> 
> If you switch the Multiple value separator to "," - then the product variations will correctly associate with the configurable product, but instead of them being assigned to `Default Category/SomeOtherCategory` - a brand new category at the top of the category hierarchy gets created.

I have the same problem. Any new item created by scheduled import that is configurable, dose not get the chidden associated with it in Magento.

For your scheduler: 
Field separator: ,
Multiple value separator: |

Now, if I take the same import, pull out all the parent items, the entire row with the configurable associations, create a new .csv file with just the parent. Then take that file and import it through Import>Validation, it passes validation, and them I import right their after validation = the children are now associated with the parents.

Problem is, I don't know when employees here put in new items, so we had lots of products no one could buy. And our photographer for the products dose not know, so she will go in and load the images in the products with out the associations, save it, and......now the product is set too simple. And now we can't fix the item, have to go in the database and cage the simple items that are suppose to be configurable to configurable, and then re-import the data through the validation import. 

:(

My developers have not been able to fix the issue. They are suggesting we spend a bunch of money to get our inventory management company to re-program our overnight export file with out using the "|" for a mother column we have. 

Did you ever get this resolved or have any idea what I could do to get this resolved? Any advice would be greatly appreciated. Thanks!
