### ISSUE TITLE
Widget sort order category pages

### ISSUE THREAD

**Issue by luukschakenraad** [magento/magento2#8755]
Sort order of widgets does not work when having some widgets displayed for all categories and some widgets for specific categories. On a category page the widget for that specific category is placed after the widgets for all categories, despite sort_order is lower

### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Add a Static Block widget
1.1 Set priority 20
1.2 Set "display on" to "Anchor categories
1.3 Choose "All categories"

2. Add a second Static Block widget
2.1 Set priority 10
2.2 Set "Display on" to "Anchor categories"
2.3 set "Categories" to "Specific Categories"
2.4 Choose a category

### Expected result

Second widget should display before first widget, because sort order is lower.

### Actual result

Second widget appears after first widget

**Comment by roman204** [comment]
the sort order is \Magento\Framework\DB\Select::SQL_ASC see [here](https://github.com/magento/magento2/blob/develop/app/code/Magento/Widget/Model/ResourceModel/Layout/Update.php#L101) 
should it be DESC?

**Comment by luukschakenraad** [comment]
No, that is correct. The problem is dat category-specific widgets are placed after "all category" widgets:

Admin:
<img width="1537" alt="screen-capture-4" src="https://cloud.githubusercontent.com/assets/8376948/23528058/b0ef7500-ff98-11e6-96d4-d8de72d6b0a0.png">

Front-end:
<img width="237" alt="screen-capture-5" src="https://cloud.githubusercontent.com/assets/8376948/23528070/b8ee664e-ff98-11e6-8389-d048f8baaed5.png">

Settings:
<img width="1131" alt="screen-capture-7" src="https://cloud.githubusercontent.com/assets/8376948/23528128/01f16db4-ff99-11e6-9bfc-094807a2b63c.png">
<img width="1143" alt="screen-capture-6" src="https://cloud.githubusercontent.com/assets/8376948/23528129/020bb336-ff99-11e6-9db6-baf67d4803d7.png">

**Comment by roman204** [comment]
hmm the query is correct... i have modified the query a bit and add sort_order to the selected fields
    `SELECT 
    layout_update.xml, layout_update.handle, layout_update.sort_order FROM
    layout_update INNER JOIN layout_link AS link ON link.layout_update_id = layout_update.layout_update_id WHERE (link.store_id IN (0 , 1)) AND (link.theme_id = 2)
        AND (link.is_temporary = 0) ORDER BY layout_update.sort_order ASC`

the result is correct sorted by sort_order ASC
![grafik](https://cloud.githubusercontent.com/assets/584168/23542776/48755d44-ffef-11e6-9a02-08c52498d0e9.png)

Also the resultObject is correct sorted ... strange
![grafik](https://cloud.githubusercontent.com/assets/584168/23542903/f19d3f90-ffef-11e6-9b6b-d909df211d7e.png)

**Comment by luukschakenraad** [comment]
If it's not that query, it shoud be something else. 

If I change "Categories" to "all", my widget with order 10 jumps to the top as it should be. As soon as I change "Catgories" back to "specific category" my widgets jump to the bottom.

**Comment by luukschakenraad** [comment]
@roman204 Can I provide you with additional information to solve this issue?

**Comment by roman204** [comment]
i am very busy at the moment ... but i am looking forward to it.
i think this issue is related to the layout-handles and in which order they are thrown.

**Comment by roman204** [comment]
after digging again into it, i think the widgets are only sortable by the same type. the layoutupdates are thrown in a specific order which has nothing to do with sort_order
in my case its:
1. catalog_category_view
2. catalog_category_view_type_layered_without_children
3. catalog_category_view_id_3

maybe a member of @magento-team can clearify

**Comment by oleg-onufer** [comment]
Hi @schakenraadjuh.
I cannot reproduce this issue.
Please add more details to your description of the steps you followed when identifying this issue.
Screenshots would be helpful, too.

**Comment by luukschakenraad** [comment]
What do you want to have clarified? Just add two widgets to your Magento store. Set one to "Display on all categories" with priority 20, set the other one to "DIsplay on specific category" with prioririty 10.

Expected result: Widget "Specific Category" appears before "All categories" because of lower priority

Actual result: Widget "All categories" appears after "Specific category". Ignoring priority.

Priority only works when the display-settings are the same for all widgets.

**Comment by magento-engcom-team** [comment]
Hi @luukschakenraad thank you for the response. We will try to reproduce it one more time

**Comment by magento-engcom-team** [comment]
@luukschakenraad, thank you for your report.
We've created internal ticket(s) MAGETWO-80218 to track progress on the issue.

**Comment by avstudnitz** [comment]
Easy to reproduce, hard to solve. How it works internally:
During creation of a widget instance, there is a layout update xml snippet inserted into the database table `layout_update`, for example like this:

```
    <body>
        <referenceContainer name="page.top">
            <block class="Magento\Catalog\Block\Product\Widget\Link" name="cd3bd336bd36272bce8a714312e65b55"
                   template="product/widget/link/link_block.phtml">
                <action method="setData">
                    <argument name="name" xsi:type="string">anchor_text</argument>
                    <argument name="value" xsi:type="string">All Categories</argument>
                </action>
                <action method="setData">
                    <argument name="name" xsi:type="string">title</argument>
                    <argument name="value" xsi:type="string">All Categories</argument>
                </action>
                <action method="setData">
                    <argument name="name" xsi:type="string">id_path</argument>
                    <argument name="value" xsi:type="string">product/3</argument>
                </action>
            </block>
        </referenceContainer>
    </body>
```

Those layout updates are later merged into the layout in `\Magento\Widget\Model\ResourceModel\Layout\Update::fetchUpdatesByHandle`. 

The problem: we don't have any means to set a sort order in the layout updates except `before` or `after`. And es we don't know at the time of creation which other blocks will be used in a container, we cannot define those. We'd have to change the way how widget instances work in general (go away from layout updates, add child block while rendering) which is out of scope of this ticket.

**Comment by luukschakenraad** [comment]
Thanks for the update, Andreas. Any suggestions for a quick / dirty fix for the time being? And did you put refactoring widgets instances on the roadmap?

**Comment by avstudnitz** [comment]
I don't see any quick solution as we cannot define any sorting for blocks inside a container except with `before` or `after`.
As I am not working for Magento, I don't have any influence on the official roadmap. It's not on my personal roadmap at the moment unfortunately.

**Comment by farancheema** [comment]
Im facing the same problem, any update about this issue??

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30054` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
