### ISSUE TITLE
Cannot change site logo

### ISSUE THREAD

**Issue by vsolod** [magento/magento2#8756]
Cannot change site logo on every theme. Permissions is ok but header and footer of site still static. How i can fix it?

**Comment by Ctucker9233** [comment]
@vsolod Can you post a screenshot of your theme configuration?

**Comment by veloraven** [comment]
@vsolod if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
