### ISSUE TITLE
M2.1.4 : Magento\Catalog\Model\ResourceModel\AbstractResource::getAttributeRawValue() returns false negative

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#8765]
If you have an attribute that is 'falsy' (for example, an empty string or a zero), `\Magento\Catalog\Model\ResourceModel\AbstractResource::getAttributeRawValue()` will return `false` rather than `''` or `0`.

### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. Create an attribute that has the potential to save a falsy value. For example a text input that can be '0' in the database.
2. Get the attribute value using `getAttributeRawValue()`.

### Expected result

You would expect to get `0` as a result, since that is the string stored in the database.

### Actual result

You get `false`. Why is this? Look at the last line of `getAttributeRawValue()`:

    return $attributesData ? $attributesData : false;

This basically makes it impossible to strict-check empty strings or zeros:

    $rawValue = $this->productResource->getAttributeRawValue(
        $productId,
        $attributeCode,
        ScopedAttributeInterface::SCOPE_GLOBAL
    );

    if ($rawValue === false) {
        // the value is not present in the database.
    }

    if ($rawValue === '0') {
        // Do something when it's zero ...
    }

**Comment by magento-engcom-team** [comment]
@kanduvisla thank you for your report.
The fix for this issue is already available in release 2.2.0
