### ISSUE TITLE
"Area code is already set" exception when executing catalog:images:resize command

### ISSUE THREAD

**Issue by cherreman** [magento/magento2#8770]
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Execute the catalog:images:resize command

### Expected result

1. No exception

### Actual result

1.  [Magento\Framework\Exception\LocalizedException] Area code is already set, exception

Code fix: check if the area code is set before setting it

```
if (!$this->appState->getAreaCode()) {
  $this->appState->setAreaCode('catalog');
}
```

**Comment by korostii** [comment]
AFAIK by default, no area code is set when running a console command - unless it sets one itself. Do you happen to have some customized or 3rd-party code which might be setting  the area code (via an observer perhaps) before the execution reaches the Magento\Catalog\Console\Command\ImagesResizeCommand ?
I am pretty sure you're missing some important preconditions here, I doubt this could be reproduced on a clean installation.

**Comment by developer-lindner** [comment]
@cherreman happened to me also while creating some very own cli commands. so check you're code, it isn't Magento2 for sure! (and close this ticket...)

**Comment by eInyzant** [comment]
@cherreman yes in my case it was already set by Iazel\RegenProductUrl\Console\Command extension.

To help you tracking down this Exception, the quickest way is to add a debug_print_backtrace in the method setAreaCode.

In the file : Magento\Framework\App\State::setAreaCode (line 119 (Magento 2.1.6)

```
debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 32);
die();
```

has @developer-lindner  said, this issue should be closed.

**Comment by magento-engcom-team** [comment]
@cherreman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by stvvt** [comment]
Apparently Magento2 instantiates (and thus - calls constructors of) all console commands when executing any console command. So if by chance you have a call to `$appState->setAreaCode()` in the constructor of **any** console command, you will most likely get this exception when executing a console command that calls `setAreaCode()` on its own.

**Comment by bydrei** [comment]
Hey guys I investigated this a while ago so wrote some information about app state here:

https://magento.stackexchange.com/questions/222698/magento-2-how-to-properly-set-app-state-area-code-setareacode-getareacode/222699#222699

**Comment by akosglue** [comment]
2.3.0 same error remains.

**Comment by maartenwolfsen** [comment]
I added an if statement to `Magento/MediaStorage/Console/Command/ImagesResizeCommand.php:66`.

Changed:
```
$this->appState->setAreaCode(Area::AREA_GLOBAL);
```
To:
```
if (!$this->appState->getAreaCode()) {
    $this->appState->setAreaCode(Area::AREA_GLOBAL);
}
```

**Comment by 0x15f** [comment]
Error is persistent on 2.3.3, I've attached a patch from @maartenwolfsen's fix that worked.
[CatalogImagesResize.patch.txt](https://github.com/magento/magento2/files/4016506/CatalogImagesResize.patch.txt)

**Comment by danielpugh** [comment]
still evident on 2.3.5-p2 via standard composer install
the two comments (fix and patch file) resolve the problem
it would be great if problems like this could be incorporated into the offical releases/code!

**Comment by Bowens20832** [comment]
Still present in 2.4

**Comment by danielpugh** [comment]
still evident int 2.3.6

**Comment by nbennett25** [comment]
Seeing this in 2.4.2 as well.

Also seeing the same error with the `catalog:product:attributes:cleanup` command, and looks like a similar fix can be applied:

`vendor/magento/module-catalog/Console/Command/ProductAttributesCleanUp.php` (line 81):

`$this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_GLOBAL);`
to:

`if (!$this->appState->getAreaCode()) {
     $this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_GLOBAL);
}`
