### ISSUE TITLE
Validator Error When Placing Order Using Transparent Redirect (Authorize.net, Payflow Pro)

### ISSUE THREAD

**Issue by mrIntegrator** [magento/magento2#8775]
There is a Javascript error with the validator that occurs when placing an order using a payment method that uses a transparent redirect, requiring manual checkout agreement terms, and having a visible, but empty discount form.

### Preconditions

1. Reproduced on Magento CE 2.1.2 and EE 2.1.4 with sample data.

### Steps to reproduce

1. In the admin, set up a payment method that uses a transparent redirect. Bug reproduced with Authorize.net Direct Post and PayPal Payflow Pro.
2. Enable checkout terms and conditions.
3. Add a new condition that needs to be applied manually.
4. On the storefront, add any item to your cart and proceed to checkout.
5. Fill in shipping information, select a shipping method, and proceed to the payment step.
6. Expand the discount form, but leave the field empty.
7. Fill out the payment form you enabled in step 1, accept the terms created in step 3, and try to place the order.

### Expected result

1. The order should be placed successfully.

### Actual result

1. The order cannot be placed and there is an error in the console.

<img width="673" alt="checkout_transparent_payment_validation_error_console" src="https://cloud.githubusercontent.com/assets/1200334/23538669/121a9846-ffa3-11e6-920d-ee0100e4df33.png">

I'm reporting this bug after having found a solution (or at least a workaround). I discovered two issues: one directly responsible for the Javascript error in the console and another responsible for preventing the order from being placed.

Here's a brief explanation of what I found. Most of the JS logic occurs in `Magento_Payment/view/frontend/web/transparent.js`. Once the "Place Order" button is clicked, the form fields (less the sensitive credit card information) are posted to the server. The server responds with the data to be sent to the payment gateway. The browser then creates a form within an iframe to post to the payment gateway. So far this is all good; it's how it has to work for PCI compliance, etc. Now this line causes the bug by triggering jQuery validation on the checkout forms (currently line 179 of transparent.js, the final line of the _postPaymentToGateway function): 

`$(tmpl).appendTo($(iframeSelector)).submit();`

**First Issue (console error in screenshot):**
The discount form doesn't have it's validator initialized when it's added to the page. In my case, the discount form template had been modified to be expanded by default, but the bug still applies if it loads collapsed and is then expanded. This can be resolved by modifying the form tag to add a mageInit to the data-bind attribute in `Magento_SalesRule/view/frontend/web/template/payment/discount.html`:

`<form class="form form-discount" id="discount-form" data-bind="mageInit: {'validation':[]}, blockLoader: isLoading">`

However, by fixing this, though the console error is fixed, the empty, but visible discount field fails validation and still prevents the order from being placed. So despite the fact that it is not the solution, I still feel that this should be fixed.

**Second Issue (how to really fix the bug):**
I don't understand why submitting the iframe form should trigger jQuery validation. Since this form is constructed and submitted instantly and its contents have not been provided by the user, but have been returned from the server, validation seems pointless. By submitting the form using the browser's native submit rather than jQuery's submit function bypasses the validation and allows the order to be placed. The bug is fixed when line 179 of `transparent.js` becomes this:

`$(tmpl).appendTo($(iframeSelector)).get(0).submit();`

If someone can explain to me anything I've missed here I would appreciate it. If I've found the proper solution to this issue, I'd gladly create the pull request. Hopefully this can save others a few hours of debugging.

**Comment by duffner** [comment]
Appears to be a good solution to me.  @mrIntegrator

**Comment by YevSent** [comment]
Hi @mrIntegrator, this is known issue (internal ticket MAGETWO-57682) and already fixed on develop branch. This fix should be delivered in Magento 2.1.8 release.

Closing as the duplicate to https://github.com/magento/magento2/issues/6224.
