### ISSUE TITLE
1.9.2.4 SOAP API salesOrderInvoiceCreate fails when Bundle product_type has Ship Bundle Items as Together

### ISSUE THREAD

**Issue by maultby** [magento/magento2#8780]
### Preconditions
1. MAG 1.9.2.4 CE
2. C#

### Steps to reproduce
1. Create product with product_type "Bundle", set Bundle Items – “Ship Bundle Items” = "Together"
2. Create order for this Bundle product.
3. Raise shipment for Bundle product using SOAP API salesOrderShipmentCreate, pass the order_item_id for the Bundle product order item.
4. View the shipment in Mag Admin - Order - Shipments. Note the qty shipped correctly shows against the Bundle product order item.
5) Raise invoice for Bundle product using SOAP API salesOrderInvoiceCreate , pass the order_item_id for the Bundle product order item. No error occurs and an invoice id is returned.
6) View the invoice in Mag Admin - Order - Invoices. Note the invoice value for the Bundle item is missing, others items have their invoice values.
7) If an Invoice is raised instead for the Bundle item's constituent Simple products' order_item_ids, their invoice value shows in Mag Admin - Order - Invoices.

### Expected result
1. Invoice create should be consistent with Shipment create. If the "Ship Bundle Items" is Together it should allow the Bundle order_item_id to be passed to salesOrderInvoiceCreate and create an invoice value against the Bundle item in the Order. If the "Ship Bundle Items" is Separately it should allow the Bundle product's constituent order_item_ids to be passed to salesOrderInvoiceCreate and create an invoice value against the Bundle product's constituent in the Order. 

### Actual result

1. It appears that salesOrderInvoiceCreate always requires a Bundle order item's product's constituent simple order_item_ids to be passed whether the Bundle is set as Together or Separately.

**Comment by YevSent** [comment]
Hi, @maultby, this Github repository only for Magento2 issues.

Please, be free to reopen this issue if you have the same problem with Magento2.

**Comment by maultby** [comment]
Please advise where I can raise issues for Mag 1.9.2.4
