### ISSUE TITLE
Price not rounding / displaying properly  - urgent issue

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#8787]
1. Magento2 Latest Commit
2. PHP 7 MariaDB

### Steps to reproduce
1.  git pulled latest commit
2. viewed products in admin / update product and on category pages
3. verified in database that price is stored as 75.6500, editing price has no effect.
4. Base currency and view currency is USD.

###Expected result
1. Product price is displayed correctly

### Actual result
1. Product price is displayed as 75.65000000000000002 instead of 75.65. 

![admin](https://cloud.githubusercontent.com/assets/13050060/23566211/edc3eb88-001e-11e7-8207-d99506626300.PNG)
![product](https://cloud.githubusercontent.com/assets/13050060/23566212/edc5e776-001e-11e7-9b50-8bd7e937eb0a.PNG)

**Comment by magnetic5355** [comment]
Appears to have something to do with currency conversion. Other switching currency causes issue to occur on all price fields.

**Comment by magnetic5355** [comment]
commenting out 

/*  Adjustment of precision value for several versions of PHP */
/*ini_set('precision', 17);
ini_set('serialize_precision', 17);*/

inside of app/bootstrap.php resolved the issue...

**Comment by mbrinton01** [comment]
@caesarcxiv do you consider this issue resolved?  If so please reply back so we can close it.

**Comment by magnetic5355** [comment]
The above fix resolved the issue

**Comment by southerncomputer** [comment]
This happened when I upgraded from 2.1.2 to 2.1.7 - all floats rendered inaccurately. Suggest removing this code since it belongs in php.ini !

**Comment by shinesoftware** [comment]
this happen into the 2.2-develop version too
