### ISSUE TITLE
 Customer getOrigData not available in customer_save_after

### ISSUE THREAD

**Issue by cykirsch** [magento/magento2#8788]
This issue was referenced in https://github.com/magento/magento2/issues/4662 but it has been abandoned twice and closed once, and it still does not work in current versions. @slavvka mentioned back in October (https://github.com/magento/magento2/issues/4662#issuecomment-253540428) that it may be fixed already and should be backported to 2.1 soon. If true, how can I test against that fixed version, and when can I expect to see it in 2.1?

### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Create a test module with the following files (plus `Vendor/Module/etc/module.xml` and `Vendor/Module/registration.php`)

**Vendor/Module/etc/events.xml**
```
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="customer_save_after">
        <observer instance="Vendor\Module\Observer\Customer" name="vendor_module_observer_customer"/>
    </event>
</config>
```
**Vendor/Module/Observer/Customer.php**
```
<?php

namespace Vendor\Module\Observer;

class Customer implements \Magento\Framework\Event\ObserverInterface
{
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $customer = $observer->getEvent()->getCustomer();
        var_dump($customer->getOrigData());
        exit;
    }
}
```
2. Edit a customer on either the website or the admin.
3. Click save.

### Expected result

1. Output unmodified (origData) customer data to the screen, followed by transaction rollback error.

### Actual result

1. Output `NULL` to the screen, followed by transaction rollback error.

**Comment by magento-engcom-team** [comment]
@cykirsch, thank you for your report.
We've created internal ticket(s) MAGETWO-80880 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@cykirsch, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by radub** [comment]
I have this issue on M2.3

**Comment by quterorta** [comment]
still dont work(
