### ISSUE TITLE
Web System Wizard shows wrong php version

### ISSUE THREAD

**Issue by skuzmina** [magento/magento2#8789]
Hi, 

I am trying to upgrade magento 2 with Web System Wizard but I am getting following error:
![memory-limit](https://cloud.githubusercontent.com/assets/9421183/23574610/f70c553e-0034-11e7-944d-de02f1365fa7.png)

But when I look for my memory_limit in php info file I see that memory_limit  is 2000M
![memory-limit-php-info](https://cloud.githubusercontent.com/assets/9421183/23574618/259ce6e8-0035-11e7-855e-25c185f0097f.png)

Also From web system wizard I see that magento detect my php version as 5.6.30. But from php info file, my php version is 7.0.16. See here: http://magento.devsoho.com/info.php

Also when I do "php -v" in command line I am getting 7.0.16 php version.

Why php version on Web System Wizard is different from php.info file? From what file system check php version?

Please advise, 
Sandra

**Comment by veloraven** [comment]
@skuzmina if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@skuzmina magento uses the environment you provided. Please, make sure that php.ini file is the same for CLI and Apache.
