### ISSUE TITLE
Initial enabling of charts kicks you back to admin login screen

### ISSUE THREAD

**Issue by robfico** [magento/magento2#879]
When I clicked the link that says to enable charts, click here, and it takes me to:
Stores -> Configuration -> Admin -> Dashboard

and I enable the charts and click "save config", it kicks me back to the admin login screen. The setting is saved though. After re-logging back in and out, I cannot reproduce this event. 0.42.0-beta2

**Comment by maksek** [comment]
Hi @robfico, looks like base url was incorrect for admin. Can you check DB for base_url.

**Comment by robfico** [comment]
Base URL was correct as far as I can tell, and did not change. I'll try another install just to be sure.

**Comment by maksek** [comment]
@robfico, let me know, if another install works. Thanks.

**Comment by robfico** [comment]
@maksek I re-installed fresh beta3 with sample data, went to:
Configuration -> Admin, changed enabled charts to "Yes", clicked save. booted me to the login screen. After re-logging in, it worked fine switching this setting. It's only on the first time I change this setting in a new store it boots me to the login screen.

Any other functions I tried before switching the chart setting the first time worked without issue, saves, etc... It's just this one action on a fresh store for the first time.

All admin URLs / settings are correct as far as I can tell.

**Comment by verklov** [comment]
MAGETWO-32547

**Comment by kokoc** [comment]
@robfico This bug is fixed and delivered in `0.42.0-beta9`. Could you please update and verify the issue?

**Comment by vpelipenko** [comment]
It is already delivered to public repository.
