### ISSUE TITLE
Missing layered navigation

### ISSUE THREAD

**Issue by vsolod** [magento/magento2#8791]
Version 2.2.0-dev. Magento Luma theme. In category page layered navigation is missing, but it enabled from backend. How it can be made visible?

**Comment by AirmanAJK** [comment]
You will only see the layered navigation in search results or categories set as "Anchor" when there are actual filters to show. If it is an empty search or category without products, or no filterable attributes are relevant, you will not see the layered navigation.

Make sure you are trying this on a category with products using attributes set as filterable, and that there are different filterable values among the products.

**Comment by veloraven** [comment]
@vsolod if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
