### ISSUE TITLE
Blank admin product page

### ISSUE THREAD

**Issue by yabeow** [magento/magento2#8792]
I tried to install magento 2 so many times and got a same error. I login admin successful but can't edit product page (and some other sections) because it got blank.
Here are the screenshot:
http://imgur.com/a/3sPhg

OS: Ubuntu 16.04
PHP: PHP 7.0.16-4
Magento: 2.2.0-dev

**Comment by treestonemedia** [comment]
@yabeow any errors in the console?

**Comment by yabeow** [comment]
@treestonemedia how to view errors in the console?

**Comment by treestonemedia** [comment]
@yabeow right click on webpage and inspect element, then click on the console tab and check there for errors

**Comment by veloraven** [comment]
@yabeow if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
