### ISSUE TITLE
Product Status is not updating properly. 

### ISSUE THREAD

**Issue by netzweltvimal** [magento/magento2#8795]
### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. Enable/Disable any product from Admin product detail page. 
2. Product Grid not showing updated status
3. When we update product status using Grid then also not updating status. 

### Expected result

1. Product status should be changed. 

### Actual result

1. When we change status (Enable/Disable) of any product from Admin product detail page. then it is showing updated. But on Admin Products Grid it is not showing updated. 
2. When we change status using admin product grid, it is not updating product status. Showing same as before.

**Comment by dmitriyprime** [comment]
Hi, @netzweltvimal . Unfortunately I could not reproduce this issue. We need more information about your configuration to reproduce this issue. Please identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by netzweltvimal** [comment]
Hi @dmitriyprime, 
First Step : 
![product-admin](https://user-images.githubusercontent.com/24586548/27721014-277f53ee-5d7b-11e7-9170-8a2b2c98c36f.png)
Second Step : 
![productgrid](https://user-images.githubusercontent.com/24586548/27721021-36582be8-5d7b-11e7-8c86-379df93f3dad.png)

Please refer screenshot.

**Comment by dmitriyprime** [comment]
Hi, @netzweltvimal. I could not reproduce the issue as you described it. May please let me know if this problem reproducible on latest release version of Magento2?

**Comment by elsandkls** [comment]
I have this same issue.  GoDaddy Linux CPanel Platform, PHP Version 5.6.30,
Brand new install of Magento (2.1.6). & Products in the shop, only one is visible, the others are set to disabled, and nothing I try will update it to "Visible". Crons are all running every 5 minutes. 
http://shop.craftedbylittledragons.net/swizzle-sticks.html


![screenshot from 2017-07-01 15-31-39](https://user-images.githubusercontent.com/6315828/27764885-731c38f6-5e72-11e7-89c2-0089e9f2d69a.png)
![screenshot from 2017-07-01 15-33-06](https://user-images.githubusercontent.com/6315828/27764894-9c9bd0ba-5e72-11e7-8d1f-51c46ba89a33.png)



cPanel Shared Hosting
Component 	Version (Subversion)
Apache 	2.4.25
cURL 	7.36.0
MySQL 	5.6.33
PHP 	5.4 (native/default) (5.4.45)
5.5 (5.5.38)
5.6 (5.6.30)
PEAR 	1.9.4
Perl 	5.10.1
phpMyAdmin 	4.0.10.14
Python 	2.6.6
Zend 	2.6.0

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by netzweltvimal** [comment]
Seems working fine with latest version 2.1.7. 
Thanks.

**Comment by creative-git** [comment]
same issue .. am on 2.1.5

**Comment by thecxguy** [comment]
Same issue 2.1.10

**Comment by jorgb90** [comment]
Same issue hier with 2.2.4..

**Comment by pacilondo** [comment]
Hi. In case someone is still having an issue, I have found out that when on the grid view, there is a column saying "Websites" (If you can't see it, you can always add it by clicking on columns on the top right corner below "Add product" button). Check the name of the website and when navigating to the product details page, on the top left on the grey bar, there is a store view. If you change it to the one that is on the grid view, you should be able to apply the changes as they may differ.
You can refer to the screenshot above by @netzweltvimal as it is the perfect example.

**Comment by LiamKarlMitchell** [comment]
Still a problem on 2.3.0
Disabling a product is not removing it from front end and on admin grid it still says enabled despite being disabled in product edit page.

"Websites" column not found site is single store.

![image](https://user-images.githubusercontent.com/1968109/59000841-756fa600-8860-11e9-898f-aa4ea0acb8ae.png)


Smells like a Bug to me.

I ended up just deleting the products using the checkbox and action drop down to delete.
Not ideal, because what if it was a mistake and they want it back on store with same ID :D. (Irrelevant but Products synced from Akeneo via Webkul module).

**Comment by nahidacm** [comment]
Looks like you need to set the "Enable Status" for each store view individually.

**Comment by claybrooks6** [comment]
Hi,
I am experiencing the same issue.

Chaning the status via the Grid does not work properly. The product detail page shows the change, but the products are not visible on the frontend when activated...

Please see video for example: https://we.tl/t-SUYaZwiTRB

Any help how this can fixed is highly appreciated.

Thanks
