### ISSUE TITLE
Importing 'Customers Main File'

### ISSUE THREAD

**Issue by WaPoNe** [magento/magento2#8798]
Error received trying to import the 'Customers Main File' sample file.

### Preconditions

1. Magento Version 2.1.5 or 2.1.4

### Steps to reproduce

1. Go to 'System' > 'Data Transfer' > 'Import'
2. Select 'Customers Main File' as 'Entity Type'
3. Click on 'Download Sample File' link
4. Select the file downloaded to import

### Expected result

1. Import activity worked fine and customers data imported correctly.

### Actual result

'reward_update_notification' and 'reward_warning_notification' are invalid attributes.

![importing customers](https://cloud.githubusercontent.com/assets/11091926/23606378/c01d5220-0260-11e7-8cb2-2227941de019.png)

**Comment by Andrii-Deineha** [comment]
@WaPoNe Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-70369.

**Comment by magento-engcom-team** [comment]
@WaPoNe, thank you for your report.
We've created internal ticket(s) MAGETWO-70369 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#44
