### ISSUE TITLE
mysql.sock error on local development machine

### ISSUE THREAD

**Issue by mikebranderhorst** [magento/magento2#88]
I had a socket error using dev/shell/log.php (not using front- and backend)
After some research I found out there are more developers with this problem.
Solution for me was app/etc/local.xml host from localhost to 127.0.0.1

```
<host><![CDATA[127.0.0.1]]></host>
```

Or leaving it empty:

```
<host><![CDATA[]]></host>
```

Or by adding unix socket:

```
<unix_socket><![CDATA[/path/to/mysql.sock]]></unix_socket>
```

I think the last two are not preferred because of: version control, deploy, production etc.

But the first method should at least be mentioned.

```
<host><![CDATA[localhost]]></host><!-- use 127.0.0.1 when having error 2002 on connecting db -->
```

**Comment by LiamKarlMitchell** [comment]
PHP looks at a different default path for the unix socket location...
setup:upgrade and possibly other areas do not use what I have configured in the etc/env config!

```
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => 'localhost',
                'dbname' => '...',
                'username' => '...',
                'password' => '...',
                'unix_socket' => '/var/run/mysqld/mysqld.sock',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8mb4;',
                'active' => '1'
            ]
        ]
    ],
```

It should use the unix_socket not the PHP default location of the socket.


https://stackoverflow.com/questions/36639014/got-error-while-installing-module-in-magento2-sqlstate-hy000-2000-no-such-f
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

Or configure php.ini to look for that as the socket.

pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock
mysqli.default_socket = /var/run/mysqld/mysqld.sock
mysql.default_socket = /var/run/mysqld/mysqld.sock
