### ISSUE TITLE
Create new product gives exception Magento 2.1.5

### ISSUE THREAD

**Issue by xaiamedia** [magento/magento2#8801]
### Preconditions

1.  PHP Version 7.0.12
2.  Magento 2.1.5

### Steps to reproduce
1. Magento 2.0.6 shop
2. Upgrade from 2.0.6 via commandline to 2.1.5
3. Login to admin
4. Go to catalog
5. Click create new product

### Expected result
1. Create new product

### Actual result
1 exception(s):
Exception #0 (ReflectionException): Class Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImag‌​e does not exist

**Comment by rparsi-commer** [comment]
I'm getting a similar error for my custom module, using web api.
I have one route defined in my webapi.xml that accepts POST.
The data gets saved to the database but I get the ReflectionException on
the returned object (it can't find the interface)

**Comment by dmitriyprime** [comment]
Hi, @xaiamedia. Unfortunately, I could not reproduce the issue as you described it. May please let me know if this problem reproducible on latest release version of Magento2?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
