### ISSUE TITLE
Inventory product quantity not decreasing when ordering from second store

### ISSUE THREAD

**Issue by parththummar** [magento/magento2#8804]
I am having an issue with the inventory quantity not decreasing when ordering from a second store. The magento version I'm currently using is magento 2.0.10.

### Preconditions
We wanted to have 2 stores with different domain names using one Magento installation.The only thing that should be different is the appearance and the menu. However, when ordering products from both stores only the main store decreases the product quantity in the products catalog.
1. Magento Version 2.0.10

### Steps to reproduce

1.  Create two stores setup with different product on each site
2.  Manage stock is set to "Yes" in the "Product Stock Options"
3.  Place an order from Store 1 and from Store 2 also.

### Expected result
1.  after placing an order decreases the catalog inventory on respective store product.

### Actual result
1. On store 1 decreases the catalog inventory, But on Store 2 Still remain the same Qty of product after successfully placing an order

**Comment by vityakopin** [comment]
Hi @parththummar ! I have reproduced this issue on Magento 2.0.10, but it not exist on latest version 2.0.15. Please update your Magento to latest official version 2.0 to solve this problem.

**Comment by veloraven** [comment]
Closed as the issue was fixed.
 If you can still reproduce this issue, please create a new GitHub issue report.
