### ISSUE TITLE
Cannot filter by negative range

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#8806]
When using the filter options in the product Catelog, you cannot filter by negative range.

### Preconditions

1. Magento CE 2.1.3
2. nginx hosted service
3. php 7.0.12

### Steps to reproduce

1. Create two products, and set their stock values to -1001 and -2001
2. Open the Product catelog in the admin panel
3. Filter by -1001 as from and -2001 as to fields, click filter.
4. No results found.

### Expected result
1. It should find all values regardless of positive or negative stock values.

### Actual result

1. No products found
2. However, if you search for a single negative value in the from fields, THOSE items are found. So it seems like a bug in the find range segment, not individual field settings.

**Comment by smoskaluk** [comment]
@spyrule  Try to set filter from -2001 to -1001 - because it should work from smallest to largest amount

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
