### ISSUE TITLE
"You need to choose options for your item" message doesn't go away

### ISSUE THREAD

**Issue by treestonemedia** [magento/magento2#8807]
Running Magento ver. 2.1.5

1. Go to list page
2. Try adding a configurable product without choosing options
3. Magento loads the product page with an error message "You need to choose options for your item."
4. From the product page, choose some options and add the item to cart
5. The page reloads with the item in cart and a success message BUT the error message is still there.

This only happens BEFORE the product page was cached, if I go through the same steps a second time on the same item there's no issue.

![image](https://cloud.githubusercontent.com/assets/5638709/23621422/b2db6e50-0268-11e7-8c90-13b39fe4595c.png)

**Comment by treestonemedia** [comment]
bump?

**Comment by RomanKrut** [comment]
@treestonemedia Thanks for reporting this issue, internal ticket was created MAGETWO-70367.

**Comment by timbaker1991** [comment]
Has any progress been made on this?

**Comment by jehzlau** [comment]
Got the same issue using M2.1.9. :D Good thing I'm not alone.

**Comment by magento-engcom-team** [comment]
@treestonemedia, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by yuvraj993** [comment]
**This is on magento official document**

http://devdocs.magento.com/guides/v2.2/get-started/order-tutorial/order-add-items.html

**magento-host/rest/default/V1/carts/mine/items**

**parameters**
```

{
  "cartItem": {
    "sku": "MH01",
    "qty": 1,
    "quote_id":  4,
    "product_option": {
      "extension_attributes": {
        "configurable_item_options": [
          {
            "option_id": "93",
            "option_value": 52
          },
          {
            "option_id": "141",
            "option_value": 168
          }
        ]
      }
    },
    "extension_attributes": {}
  }
}
```

**Show response "message": "You need to choose options for your item.",**

**Comment by pushpendra07** [comment]
@yuvraj993,

Check attribute id which you are using in api is valid or not.


```
{
  "cartItem": {
    "sku": "MH10",
    "qty": 1,
    "quote_id": "25",
    "price":52,
    "name": "Mach Street Sweatshirt",
    "product_type" : "configurable",
    "product_option": {
      "extension_attributes": {
        "configurable_item_options": [
          {
            "option_id": "93",
            "option_value": 51
          },
          {
            "option_id": "147",
            "option_value": 169
          }
        ]
      }
    }
  }
}
```

You can use above code for configurable product add in cart. It's working well in my side.

**Comment by Ekkoe** [comment]
This bug is appearing for us in version 2.2.2. Cache doesn't seem to affect it.

1. Open page of configurable product
2. Select the configuration (e.g. 'Size XL') from the dropdown menu
3. Press 'add to cart' 

Expected result: the product is added to cart with the appropriate size.

Actual result: the page reloads and the message 'You need to choose options for your item' appears.

**Comment by nmallepally** [comment]
same issue on 2.1.12 any fix around?
