### ISSUE TITLE
Product Bundle: Separate delivery does not work

### ISSUE THREAD

**Issue by jgodart** [magento/magento2#8809]
### Preconditions

1. Magento version 2.1.3 

### Steps to reproduce

1. Create a Bundle Product ( Define ship items Separately) add one or more product in options
![capture d ecran 2017-03-07 a 12 29 06](https://cloud.githubusercontent.com/assets/16555023/23654436/e79d98ac-0330-11e7-9784-909c890de1fc.png)
2. Enable multishipping
3. Add custom bundle product to cart
4. Try to ship in multi address 

### Expected result

1. In logic every element of the product should be able to be assigned an address whereas the I can only define an address for all the product.

### Actual result

![capture d ecran 2017-03-07 a 12 28 08](https://cloud.githubusercontent.com/assets/16555023/23654401/c7593092-0330-11e7-8fb0-857fe343074b.png)

**Comment by mckersten** [comment]
I have a similar issue. When i try to ship a product that is part of a bundle via REST API, I get the response: "We cannot create an empty shipment"

**Comment by smoskaluk** [comment]
@jgodart  May you confirm if this issue is reproducing on latest release of Magento 2 ?

**Comment by jgodart** [comment]
After 2.1.3 version i don't now, for now, we have not touched since March.

**Comment by smoskaluk** [comment]
@jgodart I cannot reproduce this issue as described. Please provide the detailed steps I must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by jgodart** [comment]
Je serai absent(e) du  28/08/2017 au 18/09/2017.

je serais indisponible du 28/08/2017 au 25/08/2017 inclus.
En mon absence vous pouvez contacter le standard au : 02-43-67-86-66.

Cordialement,

**Comment by mareckigit** [comment]
I have the same problem. I tested in on clear Magento 2.2.6 installation with sample data. I can't use different addresses for bundle items.
