### ISSUE TITLE
Id missing in repository getList()

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#8811]
In the cms module the getList() functions are not returning back the id's of the cms_page or cms_block

### Preconditions
1. Magento 2.1.3

### Steps to reproduce
1. using for example the pageRepository, to fetch cms pages
2. Pseudo code example:

 `$searchCriteria = $this->searchCriteriaBuilder->`
`                addFilter('identifier', 'weltpixel-icons')`
`                ->create();`

`            $result = $this->pageRepository->getList($searchCriteria);`
`            $searchCriteria = $this->searchCriteriaBuilder->`
`                addFilter('identifier', 'page-url')`
`                ->create();`

 `           $result = $this->pageRepository->getList($searchCriteria);`

### Expected result
1. This returns an array with the result, but there is no id, or page_id
2. This should return also the id of the page, for those pages which satisfy the condition

### Actual result
1. No id or page_id in the returned result

Should the interfaces contain a setPageId and getPageId functions? In this way the DataObjectHelper populateWithArray function might move the page_id, or block_id to the result as it should?

Regards,
Szabi

**Comment by ksz2013** [comment]
Hi,

Any news on this issue?

Thanks,

**Comment by ProcessEight** [comment]
@ksz2013 I've also come across this issue. Did you find a solution?

**Comment by magento-engcom-team** [comment]
@ksz2013, thank you for your report.
The issue is already fixed in 2.2.0
