### ISSUE TITLE
Unable to create refund for order with cash/check payment method

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#8813]
### Preconditions

1. Magento 2.1.5
2. Php 5.6.21, MySQL 5.6

### Steps to reproduce

1. Create a sales order either using Admin or front end with Cash on delivery as payment method
2. create an invoice for that sales order
3. use that invoice to create refund via Refund api with isOnline property in request as false

### Expected result

1. should be creating a invoice with refund offline.

### Actual result

1. It fails with error stating can't create invoice for this order.
Creditmemo Document Validation Error(s):\\nWe can\'t create creditmemo for the invoice.

This isOnline property should be still allowing the refund to be created using invoice.

**Comment by srinivasanithin** [comment]
Any update

**Comment by ankursachdeva11** [comment]
@veloraven @magento-team @SerhiyShkolyarenko 
Can anyone please take a look on this issue?

Thanks

**Comment by magento-engcom-team** [comment]
@srinivasanithin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by srinivasanithin** [comment]
@magento-engcom-team : I just want to understand when you say your not able to reproduce. Any sales order which was created using cash or check (offline payment), can I create Credit Memo from invoice related to sales order via /invoice/:id api? without any error?

**Comment by magento-engcom-team** [comment]
Hi @srinivasanithin 
We have tested the issue using the steps you provided. Error in testing could occur if some steps to reproduce are not totally clear and can be interpreted in multiple ways. 
If you wish – you may add more details to your report (along with requests and endpoints you used, etc.) and we will check again.

**Comment by korostii** [comment]
@magento-engcom-team well, if you managed to find an API request which happens to work in order to reach the "expected result" given here, would you mind sharing it right away? IMHO that would be the most helpful in this case.
