### ISSUE TITLE
Price subproducts of configurable product set to 0 after editing

### ISSUE THREAD

**Issue by anthonycouckhuyt** [magento/magento2#8819]
### Preconditions
Magento CE 2.1.2 without sample data is installed.
Running on Linux Webserver with PHP 7, MySQL 5.0.12

### Steps to reproduce
1. Create new configurable product
2. Add new configuration to the product listed in step 3.
3. Set different price for different attribute (e.g. Color blue: €12. Color red: €18)
4. Save the product.
5. Confirm prices showing 12 & 18 in the configurations.
6. Don't change anything with the configurations (subproducts), you can edit other stuff like the name,...
7. Save again
8. Prices for configurations show 0 and 0

### Expected result
1. Prices should stay the same as they were configured. 12 and 18 in this case.

### Actual result
1. After editing and saving the configurable product, prices show 0 and 0.
Image here: http://prntscr.com/ehhyuy

**Comment by anthonycouckhuyt** [comment]
Problem on my install was that there was a character before the numbers.

In Magento\Framework\Locale\Format.php. The getNumber function does check for spaces and apostrophe, but not for different characters. In my case there was a character that looked like a space, ascii code showed 194. 

This line should be added to the getNumbers function:
`$value = str_replace(chr(194).chr(160), '', $value);`

I solved this by created an observer because I did not want to mess with the framework code.

**Comment by vityakopin** [comment]
Hi @Koekoet ! I can't reproduce this issue as described in ticket. After changing any attributes for my configurable product (name, weight, stock status) price for my configurations still as designated. Can you reproduce this with MySQL 5.6 as discribed in [Magento 2.1.x technology stack requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html)?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
