### ISSUE TITLE
WEBAPI: Unable to save Product when typeId and status is missing(Magento 2.1.5.)

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#8820]
### Preconditions
Magento 2.1.5 SOAP API

### Steps to reproduce
1. Create a product without typeId and status (see attached XML request)
2. Send the XML to Magento
3. You will receive error;: cannot save product
4. Product is created in backend!

![image](https://cloud.githubusercontent.com/assets/15381778/23710769/2979f89a-041e-11e7-9c9a-f6378cd4caac.png)

### Expected result
1. The product should not be created in the backend
![image](https://cloud.githubusercontent.com/assets/15381778/23710835/53e09d00-041e-11e7-9bd3-299ac025b763.png)

### Actual result
Product is created in backend!

![image](https://cloud.githubusercontent.com/assets/15381778/23710947/b29d68c8-041e-11e7-8806-811a6ebf7fb4.png)

**Comment by magento-engcom-team** [comment]
@tinxit, thank you for your report.
We've created internal ticket(s) MAGETWO-80669 to track progress on the issue.

**Comment by gomencal** [comment]
Hi! There is a problem when trying to save a product with typeId "" (empty string). 
As a workaround you can check this value on the client side for not sending it when empty.

I have a solution for this, can anyone assign me for this ticket?

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @tinxit

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@tinxit thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
