### ISSUE TITLE
how to create configurable product with  bundle product in magento 2

### ISSUE THREAD

**Issue by umang-ranium** [magento/magento2#8828]
### Preconditions

1. Magento 2 

### Steps to reproduce

1. Create configurable product
2. Add bundle product
3. Go to product try to add, unable to add product with msg We don't have as many "Config product" as you requested

### Expected result

1. Should add configurable product bundle option

### Actual result

1. unable to add product with msg We don't have as many "Config product" as you requested

**Comment by RonXS** [comment]
You cant do it like that, nor the other way around in Magento 2 by default. Magento has never taken up the task of implementing the functionality for showing configurables in bundled / grouped products

Maybe you are looking for a way to bundle configurable products, we have created an extension for that called Configurable Bundle.

For example, if you check our demo environment over here, maybe it is exactly how you would expect it to be.

This is a demo:
https://m2.wizdemo.nl/balistico-2-0-with-rashguard.html

You can find the extension here:
https://www.wizkunde.nl/magento-2-configurable-bundle.html

If you have questions or this is not your usecase, feel free to let me know.

**Comment by umang-ranium** [comment]
If that's the case magento should not allow bundle product to be added to configurable product.

**Comment by magento-engcom-team** [comment]
@umang-ranium, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Judder** [comment]
@umang-ranium is correct

If you create a Bundle Product with a attribute used in a Configurable Product, it is possible to select the Bundle Product from the 'Configurations' -> 'Add Products Manually' option on the Configurable Product

This then adds the Bundle Product to the list for the 'Current Variations' on the Configurable Product edit screen

However when you then try and save the Configurable Product, the Bundle Product you have selected as a 'Current Variation' is not saved and ignored

![screen shot 2017-11-27 at 11 33 15](https://user-images.githubusercontent.com/40323/33264960-9befd4bc-d367-11e7-8957-c7cf1ebb0cbe.jpg)

![screen shot 2017-11-27 at 11 33 22](https://user-images.githubusercontent.com/40323/33264961-9c07e732-d367-11e7-83cc-42d94482deca.jpg)

![screen shot 2017-11-27 at 11 37 04](https://user-images.githubusercontent.com/40323/33264962-9c202a54-d367-11e7-95b5-c3400f43a8a9.jpg)

**Comment by shafalibhatia** [comment]
We are not able to add bundle product in configurable product. Is there a way to do it??
