### ISSUE TITLE
Credit on Bundles returns invalid qty_refunded

### ISSUE THREAD

**Issue by Tjab** [magento/magento2#8834]
When retrieving a credit memo via REST, an invalid `qty_refunded` is given.

### Preconditions
1. A bundle (dynamic or static does not matter) with items that are in the bundle more than once (in my example the item is in the bundle 3 times)
2. A credit memo on a order that ordered the bundle (again, in my example, it's ordered 2 times)

### Steps to reproduce
1. Request the credit memo via REST (`index.php/rest/V1/creditmemo/`)

### Expected result
1. On a **dynamic** bundle, the expected result is:
```
"items": [ {
    ...
    "name": "MyDynamicBundle", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "2.0000",
        "qty_ordered": "2.0000",
        "qty_refunded": "2.0000",
        "qty_shipped": "0.0000",
        ...
    ...
    "name": "MySimpleProduct", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "6.0000", // remember, the item is in the bundle 3 times, so 2x3 = 6)
        "qty_ordered": "6.0000",
        "qty_refunded": "6.0000",
        "qty_shipped": "0.0000",
        ...
```
2. On a **static** bundle (basically the same)
```
"items": [ {
    ...
    "name": "MyStaticBundle", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "2.0000",
        "qty_ordered": "2.0000",
        "qty_refunded": "2.0000",
        "qty_shipped": "0.0000",
        ...
    ...
    "name": "MySimpleProduct", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "6.0000", // remember, the item is in the bundle 3 times, so 2x3 = 6)
        "qty_ordered": "6.0000",
        "qty_refunded": "6.0000",
        "qty_shipped": "0.0000",
        ...
```

### Actual result
1. On a **dynamic** bundle, the expected result is:
```
"items": [ {
    ...
    "name": "MyDynamicBundle", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "2.0000",
        "qty_ordered": "2.0000",
        "qty_refunded": "1.0000", // PLEASE NOTE, 1 INSTEAD OF 2
        "qty_shipped": "0.0000",
        ...
    ...
    "name": "MySimpleProduct", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "6.0000",
        "qty_ordered": "6.0000",
        "qty_refunded": "6.0000", // Correct
        "qty_shipped": "0.0000",
        ...
```
2. On a **static** bundle (basically the same)
```
"items": [ {
    ...
    "name": "MyStaticBundle", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "2.0000",
        "qty_ordered": "2.0000",
        "qty_refunded": "2.0000", // Correct
        "qty_shipped": "0.0000",
        ...
    ...
    "name": "MySimpleProduct", 
    "orderItem": {
        ...
        "qty_canceled": "0.0000",
        "qty_invoiced": "6.0000",
        "qty_ordered": "6.0000",
        "qty_refunded": "1.0000", // PLEASE NOTE, 1 INSTEAD OF 6
        "qty_shipped": "0.0000",
        ...
```

Note: When it's a dynamic bundle, the `base_price` of the bundle is set and the `base_price` of the items in the bundle are set to `0`, so it doesn't matter for the total costs (`6x0 = 0` and `1x0 = 0`). It does however matter when booking the credit: my stock isn't updated proper (I've gotten 6 items back, not just 1).

**Comment by VasylShvorak** [comment]
@Tjab Thanks for reporting this issue. Created internal issue MAGETWO-70453 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@Tjab, thank you for your report.
We've created internal ticket(s) MAGETWO-70453 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@Tjab, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
