### ISSUE TITLE
[2.1.5] Changing theme's title via theme.xml has no effect 

### ISSUE THREAD

**Issue by korostii** [magento/magento2#8836]
It seems that theme list and metadata shown in admin at `Content > Design > Themes` is not getting update while running Magento2 in production mode, ever.

### Preconditions

1. Magento 2.1.5, PRODUCTION mode

### Steps to reproduce

1. Open a `theme.xml` file inside any theme folder used by your Magento instance
2. Edit content of the <title> tag ("rename" the theme), save file
2a. (Optional) Try flushing caches - also no effect.
3. Open admin menu `Content > Design > Themes` or `Content > Design > Configuration` 

### Expected result

1. The NEW theme's title shown in admin changes

### Actual result

1. OLD title is being shown instead 

### Additional Information
As far as I can tell, same might probably apply to installing new themes. The theme metadata gets saved into the SQL table called `theme`. Which table, it seems, only gets updated while surfing through admin in developer and default modes:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Theme/Model/Theme/Plugin/Registration.php#L73

A workaround for updating theme list (being a merchant or a developer), thus, would look as following:
1. Enable developer mode (might not be acceptable in some workflows).
2. Open any page in admin.
3. Switch back to production mode.

While it might be argued that frequently updating theme list would slow down admin performance of production mode, same argument goes for developer mode as well. It might be preferable to create an extra easy-to-flush cache for updating this info.

**Comment by magento-engcom-team** [comment]
@korostii Thanks for reporting this issue. 
According to http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html
In order to create or update theme, You should be in developer mode.
We are closing this as non-issue. Please reopen this issue as needed.

**Comment by korostii** [comment]
> According to http://devdocs.magento.com [...] You should be in developer mode

I am aware that the developer mode could be enabled - as a workaround.
However, having this workaround documented doesn't make this bug any less of an issue.

Same page [says](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-install.html#install-a-theme-as-an-extension) it's possible to [install a theme via the Web Setup Wizard without having access to the `bin/magento` CLI utility](http://docs.magento.com/marketplace/user_guide/quick-tour/install-extension.html)
If that's true, the theme you've installed this way should get displayed right away, without having to perform any additional steps. Otherwise this whole "Content > Design > Themes" page is broken and useless (if not harmful) when running in production mode. 

I would be glad to hear if there's some reasonable explanation preventing from fixing this issue (if you're saying it was a concious design decision and such behavior is to be expected).

> Please reopen this issue as needed.

That's currently not possible on Github, if the issue was closed by a maintener or repo owner, see https://github.com/isaacs/github/issues/583 or https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github for details.
