### ISSUE TITLE
Static files and cache

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#884]
With all Magento caches disabled, static elements (images, LESS/CSS) are not re-generated on each page load. 

As a workaround, I am manually clearing pub/static each time. Should this not be automated when caches are off?

**Comment by zivendesign** [comment]
Hi jameswithers,
How to ignore?
Please advice.

**Comment by jameswithers** [comment]
@zivendesign set up grunt with grunt watch and it can be used to automate the process

**Comment by godban** [comment]
@zivendesign you can use local node.js to automate this processes
- make sure that you have node.js installed locally
- do in project folder cmd "npm install" to upload node packages
- and you are ready to go, use:
  - grunt refresh (to start or when you add/remove less files);
  - grunt less (to compile all less files);
  - grunt watch (to watch changes in less files and compile them automatically);
  - grunt clean (to delete all temporary files)
