### ISSUE TITLE
Shopping Cart Pricing Rule - Coupon Code Invalid After Code Changed

### ISSUE THREAD

**Issue by drc-mw2** [magento/magento2#8840]
Several Shopping Cart Pricing Rules were created with specific coupon codes. They were tested to be working as expected. However, the marketing team decided to change the coupon code name, so the coupon code was updated on the existing rule, e.g. originally ALWYNVIP changed to AC30. Once the name change occured on the coupon code, the coupon code would present invalid code when used on the store front.

### Preconditions

1. Magento Enterprise 2.1.2 
2. 

### Steps to reproduce

1. In Admin, Marketing  -->Cart Price Rules
2. Add New Rule
3. Select a store
4. Select all customer groups
5. Select Specific Code
6. Enter coupon code, ALWYNVIP
7. No conditions
8. Action = Percent of product price discount, enter 30.00
9. Save Rule
10. Test coupon code on shopping cart with any product added
11. Go back to Admin
12. Edit the newly created rule
13. Change the coupon code to AC30
14. Save Rule
15. Test new coupon code on shopping cart with any product added

### Expected result

1. Original coupon code is valid in cart prior to change the code
2. Changed coupon code is valid in cart after the change

### Actual result

1. Original coupon code is successfully applied
2. Changed coupon code now give invalid code error and doesn't apply

**Comment by magento-engcom-team** [comment]
@drc-mw2, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
