### ISSUE TITLE
Custom tracking is not handled correctly in popup

### ISSUE THREAD

**Issue by reijervano** [magento/magento2#8842]
When you add a tracking to a shipment you can use the Custom option. The tracking is then an array instead of an object. The popup however uses it as an object which creates an exception.

### Preconditions
1. Magento 2.1.5
2. PHP 7

### Steps to reproduce
1. Create order.
2. Add shipment with custom carrier code.
3. Open the Track pop-up.

### Expected result
1. Pop-up with the tracking information.

### Actual result
1. Pop-up with only the shipping id.
2. Exception in report folder.

I think the fix is easy (vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml):

`<table class="data table order tracking" id="tracking-table-popup-<?php /* @noEscape */ echo is_object($track) ?  $track->getTracking() : null; ?>">`

instead of

`<table class="data table order tracking" id="tracking-table-popup-<?php /* @noEscape */ echo $track->getTracking(); ?>">`

**Comment by epson121** [comment]
Issue in progress @epson121

**Comment by epson121** [comment]
This seems to be solved in the current develop branch (2.2 release)

**Comment by YevSent** [comment]
Already fixed and merged into develop branch.

**Comment by MagentoRize** [comment]
I have changed the code as provided above for getTracking() function issue
Now the **getTracking()** issue was gone and a new one arises as below:

PHP Fatal error:  Call to a member function **getProgressdetail()** on array in /home/magento/public_html/vendor/magento/module-shipping/view/frontend/templates/tracking/popup.phtml on line 34

**Comment by scottsb** [comment]
@MagentoRize See this commit which shows the other changes to make if you have to patch this before upgrading to Magento 2.2: 2c5b4c5

**Comment by gazsmith10** [comment]
I just got this issue on the latest version 2.3
