### ISSUE TITLE
Remove default storeview code Magento2

### ISSUE THREAD

**Issue by fmd-sav** [magento/magento2#8845]
Hello Guys,

I want to remove only the default storeview code from my store.

Now:
testdomain.de/de--> default storeview
testdomain.de/en --> englisch storeview

I want:
testdomain.de --> default storeview
testdomain.de/en --> englisch storeview

I know the option in the backend to enable the storeview code, but it adds the code for both storeviews and i need the code only for the /en storeview.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
