### ISSUE TITLE
Add a "Select All" Option for Product Export Exclude Entity Attributes

### ISSUE THREAD

**Issue by surfer190** [magento/magento2#8847]
### Preconditions
Magento version: Magento 2.1.5

### Steps to Reproduce
1. `System -> Export`
2. Select `Product`

### Expected result
1. Expect there to be a javascript function to select all of the attributes, so I can only uncheck price if I want to export just the product sku and price.

### Actual result
1. There is no `select all` option

[logo]: http://number1.co.za/wp-content/uploads/2017/03/Screenshot-from-2017-03-10-15-38-09.png "No Select All Magento 2 Product Export"

![No Select All](http://number1.co.za/wp-content/uploads/2017/03/Screenshot-from-2017-03-10-15-38-09.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-a-quot-Select-All-quot-Option-for-Product-Export-Exclude/idi-p/64455).

**Comment by aadmathijssen** [comment]
I just clicked 76 attributes to exclude all but 3 attributes from the export. This is not a "feature request", this is a missing piece of functionality. The absence of it is a bug. Please reopen this issue.

**Comment by Kishorchhugani** [comment]
yes this is indeed where there are more then 100 attributes,  because with our 130 attributes it's pain to select everything each time we want to export
