### ISSUE TITLE
HIDE / SHOW EDITOR MAGENTO ERROR , BUTTON D'ONT WORK

### ISSUE THREAD

**Issue by rogersrangel** [magento/magento2#8850]
magento-1.9.3.2-2017-02-07-01-49-34    VERSION

![error magento editor](https://cloud.githubusercontent.com/assets/22354562/23803709/20ae03cc-0596-11e7-8229-094c3b205c4d.png)

**Comment by AirmanAJK** [comment]
This is for Magento 2 issues. This looks like M1.

**Comment by rogersrangel** [comment]
YEa M1.9.3

**Comment by magento-engcom-team** [comment]
Hi @rogersrangel 
Unfortunately this GitHub repository is devoted to the issues related Magento 2. 
Closing, as we are unable to provide any help with this issue here.
