### ISSUE TITLE
Sorting by price on product search via REST API does not return any results

### ISSUE THREAD

**Issue by coleHafner** [magento/magento2#8853]
### Preconditions

- Magento Version: v2.1.3 CE
- Vanilla Install

### Steps to reproduce

Hit this endpoint:
```
GET => <domain name>/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=33&searchCriteria[current_page]=1&searchCriteria[page_size]=5&searchCriteria[sortOrders][0][field]=price&searchCriteria[sortOrders][0][direction]=ASC
```

Search criteria, as returned in the response:
```
{
    "filter_groups": [
        {
            "filters": [
                {
                    "field": "category_id",
                    "value": "33",
                    "condition_type": "eq"
                }
            ]
        }
    ],
    "sort_orders": [
        {
            "field": "price",
            "direction": "ASC"
        }
    ],
    "page_size": 100,
    "current_page": 1
}
```

### Expected result

7 items should be returned (confirmed via the Magento admin section). This is fine if the sorting info is left out of the request or I sort via any other field (name, sku etc).

### Actual result

0 results are returned

I have a feeling it could be data related, but not sure what. There is a price on every item in the category. Not sure what else could be causing it...

**Comment by coleHafner** [comment]
Nevermind. My indexes just needed to get rebuilt. For anyone else running into this issue, here's how I fixed it:

`php bin/magento indexer:reindex`

To check the status of your indexes, run this:

`php bin/magento indexer:status`

**Comment by msliman** [comment]
@coleHafner I am facing the same problem and i rebuilt the indexes in vain. Can you suggest another solution?

**Comment by raoraafe** [comment]
same here. but its only happening on productions server for me.
on my local system i fixed it, oddly, by just converting the string to uppercase for sort order. 
`$sortOrder = $this->_sortOrderBuilder->setField($order)
                ->setDirection(strtoupper($dir))
                ->create();`
like this. and it worked on local but not on production yet.
