### ISSUE TITLE
why there is TWO frontend folder in magento2?

### ISSUE THREAD

**Issue by AndroidDesigner** [magento/magento2#8859]
Hi.I'm confused by file and folder structure in Magento 2.
I downloaded magento 2.1.3 and it works correctly.
now I want to override luma theme (change some html and css codes).
I could override css codes.
but I dont know how change luma html codes.

why there is TWO frontend folder in magento2 and what is it's difference?
1. pub/static/frontend/magento/luma
2. vendor/magento/theme-frontend/luma

please help me...

**Comment by mrkhoa99** [comment]
@AndroidDesigner Shortly, `pub/static` folder contains the static files: html templates (not phtml template), js, css, less files from the theme. In our theme, the static files are under `web` folder. Magento mechanism will get the static files from `pub/static` folder, not from "current" theme folder.

P.S: Better if you post your question on SE: http://magento.stackexchange.com

**Comment by AndroidDesigner** [comment]
thank you for your reply.
your answer is ok. but I don't know why there is a web folder (contains less files & font) in the following path,also:
vendor/magento/theme-frontend/luma/web

in fact,why magento2 does not put these two web folders in one location (or pub folder or vendor folder) and put some of them in pub and others in vendor.
ALSO :
I want to create a module.
some people say that we can create  code folder inside app folder same as magento1, but others say this is not good.
I'm really confused!
there is no any good and updated article about these topics!

**Comment by Yamaha32088** [comment]
@AndroidDesigner it sounds like you would benefit from reading the development documentation on the Magento website. It talks about the architecture along with how to create customizations like what you mentioned in your question. This area is meant for issues relating to Magento2 not for asking questions about how to customize things, a question such as yours belongs on the site @mrkhoa99 mentioned in his comment. Below are some links that should help get you started:

[http://devdocs.magento.com/](http://devdocs.magento.com/)
[http://devdocs.magento.com/guides/v2.0/extension-dev-guide/bk-extension-dev-guide.html](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/bk-extension-dev-guide.html)
[https://www.packtpub.com/web-development/magento-2-developers-guide](https://www.packtpub.com/web-development/magento-2-developers-guide)

**Comment by pboisvert** [comment]
closing as this is not an issue but a question
