### ISSUE TITLE
fatel error

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#886]
when i run application
Fatal error: Class 'Zend\Code\Generator\ClassGenerator' not found in /var/www/html/magento2/lib/internal/Magento/Framework/Code/Generator/CodeGenerator/Zend.php on line 10

**Comment by SchumacherFM** [comment]
Installation guide: http://devdocs.magento.com/guides/v1.0/install-gde/bk-install-guide.html

Please run composer install in the root directory

**Comment by sivajik34** [comment]
I installed already.its working fine before.after latest pull its not working.
