### ISSUE TITLE
APi Order List BUG

### ISSUE THREAD

**Issue by xiangkundavis** [magento/magento2#8860]
I follow the tutorial http://www.magestore.com/magento-2-tutorial/how-to-get-value-of-custom-attribute-on-magento-2-rest-api/ to add order_pay_transaction_id.
This attribute has been added to order detail api.
But it does not show at order list api

**Comment by xiangkundavis** [comment]
![detail](https://cloud.githubusercontent.com/assets/998396/23844342/7d87c87c-07fc-11e7-8e5f-a2cedca7c1c2.png)

**Comment by xiangkundavis** [comment]
![list](https://cloud.githubusercontent.com/assets/998396/23844379/b4c1a920-07fc-11e7-9029-2ba2704706b4.png)

**Comment by veloraven** [comment]
@davissuperman if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@davissuperman thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

Please reopen the issue once ready
