### ISSUE TITLE
Malta zipcode validation incomplete

### ISSUE THREAD

**Issue by wigman** [magento/magento2#8863]
Zip code validation fails on adresses from Malta when containing 4 numbers (ABC 1234).

### Preconditions
On all 2.* versions including development branch.

### Steps to reproduce
go to cart or checkout and insert ABC 1234. Validation fails

### Expected result
Validation should succeed.

### Actual result
Validation fails

### Solution
insert an extra validation rule containing `<code id="pattern_X" active="true" example="ABC 1234">^[a-zA-Z]{3}\s[0-9]{4}$</code>`
at https://github.com/magento/magento2/blob/cec25e1662c8697268f7bcabf1816e2da28fd719/app/code/Magento/Directory/etc/zip_codes.xml#L281

**Comment by mmacinko** [comment]
Issue in progress @mmacinko

**Comment by magento-engcom-team** [comment]
@wigman thank you for your report.
The fix for this issue is already available in release 2.2.0

**Comment by wigman** [comment]
"already"
