### ISSUE TITLE
Creating own Indexers does not work as explained in the documentation

### ISSUE THREAD

**Issue by theCapypara** [magento/magento2#8866]
### Steps to reproduce
1. Follow the steps at http://devdocs.magento.com/guides/v2.1/extension-dev-guide/indexing-custom.html
2. Try to save the Model that belongs to the table subscribed to in mview.xml

### Expected result
1. My indexer get's triggered (one of the execute-methods)

### Actual result
1. Nothing happens

If the indexer is set to "Update on save" (the default!) Magento does not bother using the mview.xml at all. 

Instead if we look at the Search Module for example, you need to write a ton of plugins to get the indexing to work (Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin). 
This is absolutely ridiculous when compared to how easy the documentation makes it seem, and to how Magento 1 did it. Not to mention that this is explained _nowhere_, apart from the diagram at http://devdocs.magento.com/guides/v2.1/extension-dev-guide/indexing.html which still doesn't explicitly tell us how to get the indexer to work with Update on save.

Why is this not explained in the documentation? Why to I need to have to go through such struggle to make indexing on save work?

**Comment by orlangur** [comment]
I do agree that documentation could be improved so that it explains step-by-step how to create indexer which works in both modes.

> Not to mention that this is explained nowhere, apart from the diagram at http://devdocs.magento.com/guides/v2.1/extension-dev-guide/indexing.html

Well, this diagram is essential and one shall understand how partial reindexing works before implementing custom indexer.

> you need to write a ton of plugins to get the indexing to work

There is no other way to say how your particular entity should affect index when saving.
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php#L53 is pretty clear and minimalistic. Probably, reusability of such code could be increased so that we have some basic flow working by default and only add code for what is different. But generally there is no problem with this explicit implementation using interceptor.

**Comment by theCapypara** [comment]
> Well, this diagram is essential and one shall understand how partial reindexing works before implementing custom indexer.

I agree, but sadly if you look up how to create indexers, you don't easily find this diagram. Maybe it could be added to the "Adding a custom indexer" page as well.

I also want to point out, that if you currently look up on how to create Indexers, you basically only find copies of the "Adding a custom indexer" page without any further explanation (eg. https://www.mageplaza.com/magento-2-module-development/magento-2-indexing.html).
And when trying to find out what the issue was, I only stumpled accross some very confused Stack Exchange posts (eg. http://magento.stackexchange.com/questions/103524/custom-indexer-on-magento2), so there really seems to be a problem with the current documentation.

I hope either the "Adding a custom indexer" page get's reworked to include this information OR there is an easy way to force an indexer to be in "Update on Schedule" mode (via XML maybe? ) which could then be documented on this page.

**Comment by korostii** [comment]
By the way, I think it's worth mentioning that devdocs have a separate repo: https://github.com/magento/devdocs
If you have any feedback regarding the documentation, I'd suggest to post it in there as well: it's not as overcrowded as the main repository's issue tracker and your thought might actually get taken into account by someone responsible for the documentation.

**Comment by orlangur** [comment]
@korostii I don't think documenters by themselves can deal with nonworking implementation :)

There is a `DOC` label here: https://github.com/magento/magento2/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20label%3Adoc

So, in case of not purely documentation issue I would recommend to start here and then move to devdocs as necessary, when changes needed to apply become clear.

**Comment by okorshenko** [comment]
@Parakoopa thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Magento version

**Comment by magento-engcom-team** [comment]
Hi @Parakoopa if there is an issue with documentation, please, report an issue to devdocs repository as @korostii suggested

**Comment by victortodoran** [comment]
@orlangur I'm a little confused. Is UpdateOnSave for custom indexers supported out of the box? Or do I need to add custom logic to support it (plugins, observers or anything else).

**Comment by HenKun** [comment]
@victortodoran I think I doesn't work out of the box. However, I am also struggling with that. In https://github.com/magento/devdocs/issues/1596 the progress of the doc is tracked and it seems that one will work on that now.
