### ISSUE TITLE
Typo in Pull Request Template

### ISSUE THREAD

**Issue by okorshenko** [magento/magento2#8871]
There is a typo in Pull Request Template file.

Please, see https://github.com/magento/magento2/blob/develop/PULL_REQUEST_TEMPLATE.md
`magento/magetno2#: Issue title`

magetno2 should be changed on magento2

**Comment by tomislavsantek** [comment]
Issue in progress @tomislavsantek

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66232

**Comment by magento-engcom-team** [comment]
@okorshenko, thank you for your report.
The issue is already fixed in 2.2.0
