### ISSUE TITLE
[Dev][Travis CI] Unit tests build is often truncated not giving a proper feedback

### ISSUE THREAD

**Issue by orlangur** [magento/magento2#8876]
### Preconditions

1. Create a PR
2. Be not lucky enough, issue is not always reproducible, probably depends on `STDERR` output or weather on Mars

### Steps to reproduce

Check Travis CI

### Expected result

For unit tests job I see list of failed due to my changes tests and can do something

### Actual result

https://travis-ci.org/magento/magento2/jobs/210751213

```
..........................................SS........E.....S  1593 / 19047 (  8%)
...
........................................................... 18880 / 19047 ( 99%)
..........................................................
The command "phpunit $TEST_FILTER" exited with 2.
cache.2
store build cache
0.00s
0.49snothing changed, not updating cache
Done. Your build exited with 1.
```

# Solution
Problem is caused by invalid "unit" test `setup/src/Magento/Setup/Test/Unit/Module/I18n/FactoryTest.php` which closes `STDOUT` 😮 

Repeating [my comment](https://github.com/magento/magento2/issues/8315#issuecomment-280965328):
> If `setup/src/Magento/Setup/Test/Unit/Module/I18n/FactoryTest.php` really needs to be implemented this way (it is not "unit test" as it implicitly instantiates another object with "bad" destructor) and if `Factory` implementation really needs to instantiate object directly with `new` operator like it does currently then the only way to fix it is to create a stub of `Writer/Csv/Stdo` with not so evil destructor.

Please help me with defining implementation approach to solve this issue.

As far as I remember, initially this whole `I18n` thingy was implemented in such a way that it does not rely on Magento Framework or application. Although I propose to replace direct objects instantiation  `new Dictionary\Writer\Csv\Stdo` and  `new Dictionary\Writer\Csv` with non-autogenerated factories just like we do in Magento Framework but not relying on it. It will allow us to mock `\Magento\Setup\Module\I18n\Factory` dependencies properly in test.

**Comment by orlangur** [comment]
@okorshenko could you please help me with defining implementation approach?

**Comment by okorshenko** [comment]
@orlangur the class `\Magento\Setup\Module\I18n\Factory` is not unit-testable in current implementation. So, the easiest way for fix it is move all new operator calls to a separate methods and mock this methods. Means, we need to mock object under the test. This is not the best approach, but it will allow to test this class without changing it's behaviour.

**Comment by orlangur** [comment]
Oh :) It sounds a bit Magento1-ish to me but that's an alternative which I overlooked and it do require less efforts. Thanks, will go this way, I'm not insisting on refactoring as I'm not familiar with future plans for this code.

**Comment by orlangur** [comment]
Fixed in https://github.com/magento/magento2/commit/690e6b8db61af8de898d6f679abd094dfec7a57d#diff-b2831a7c3cb270df4d97726202456676 (no need to fix test when bad `Stdo` class was fixed).
