### ISSUE TITLE
Translate checkout page - compile static content

### ISSUE THREAD

**Issue by vlauria** [magento/magento2#8881]
**Precondition:**

1. Magento CE 2.1.5 without sample data is installed.
2. Install package language it_IT
3. Store in italian language

**Steps to reproduce:**

1. compile static content:  **php bin/magento setup:static-content:deploy en_US it_IT**

**Expected result:**
Frontend in italian language

**Actual result:**
Frontend partial in italian. Checkout page is in English.

NB. If you run this command **php bin/magento setup:static-content:deploy it_IT en_US** it's ok.
The problem is the order of language code in command.

**Comment by hostep** [comment]
This is a bug which was introduced in Magento 2.1.3.
See this issue which describes the problem: https://github.com/magento/magento2/issues/7862

Please close the issue, since it is a duplicate of the above issue :)

**Comment by marcosdsdba** [comment]
In version CE 2.1.6 too
