### ISSUE TITLE
Admin order email: Custom theme template modifications not emulated

### ISSUE THREAD

**Issue by jzahedieh** [magento/magento2#8884]
### Preconditions

1. Magento 2.1.4 EE
2. PHP 7
3. Custom Theme

### Steps to reproduce

1. Customise the checkmo.phtml in your theme
1.1 `vendor/vendorname/m2-theme-name/Magento_OfflinePayments/templates/info/checkmo.phtml`
2. Make sure theme defined as main theme for all websites/stores.
3. Go to admin order page
4. In the header click "Send Email"

### Expected result
1. Content of "PAYMENT METHOD" section of email should be customised.

### Actual result

1. Default template rendered
1.1 `vendor/magento/module-offline-payments/view/frontend/templates/info/checkmo.phtml`

### Analysis

In `Magento\Payment\Helper\Data::getInfoBlockHtml()` app emulation is used
See `Magento\Store\Model\App\Emulation::startEnvironmentEmulation()`, the following condition fails:

        if ($storeId == $this->_storeManager->getStore()->getStoreId() && !$force) {
            return;
        }

![screen shot 2017-03-14 at 17 49 26](https://cloud.githubusercontent.com/assets/2098908/23914742/c72d595a-08de-11e7-9133-3b1f1faa92a1.png)

In my example the `$storeId` supplied to the `startEnvironmentEmulation()` method is 1 and the current store in the **admin** area is 1.

![screen shot 2017-03-14 at 17 50 12](https://cloud.githubusercontent.com/assets/2098908/23914757/d1e78fd2-08de-11e7-8a25-8a9fb382a12e.png)

If you look at the `_themes` it thinks it should be using the default Magento/luma theme 

### Workaround

Currently I am forced to override the template definition in a module and use a preference so I am not reliant on the theme being recognised.

    <?php
    namespace NS\Theme\Block\OfflinePayments\Info;
    
    class Checkmo extends \Magento\OfflinePayments\Block\Info\Checkmo
    {
        protected $_template = 'NS_Theme::offlinepayments/info/checkmo.phtml';
    }

### Fix

By passing the `$force = true` option to the `startEnvironmentEmulation()` method it picks up the correct theme and will render the modified template.

The condition needs to be aware of both store _and_ area.

**Comment by magento-engcom-team** [comment]
@jzahedieh, thank you for your report.
We've created internal ticket(s) MAGETWO-82193 to track progress on the issue.

**Comment by sylvainraye** [comment]
I confirm to have the same issue with Magento 2.2.4 while trying to send email from admin and having overwritten the `info.phtml` of the payment method, this one is not taken from the theme of the frontend store but from the default one.

**Comment by Detzler** [comment]
confirm bug

**Comment by diamondavocado** [comment]
Still happening in 2.3.1.

We are unable to override the template at `vendor/magento/module-payment/view/frontend/templates/info/default.phtml` in an order confirmation email which is frustrating.

@alessandroniciforo has already created a solution for this, including unit tests. See related issue: https://github.com/magento/magento2/issues/10402. The solution should be pulled into the official magento2 repository so it can be released.

*Edit:* a pull request has already been opened (but closed, unfinished): https://github.com/magento/magento2/pull/10403

**Comment by engcom-Charlie** [comment]
Hello @jzahedieh 
We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

Looks like the issue was fixed in the scope of d3e32b4e5db80f7c04734f63cfeec83155613222
I'm closing this issue as not relevant. 
Thank you!
