### ISSUE TITLE
Export option is not functional in magento 2.1.3

### ISSUE THREAD

**Issue by R-K-Shrivastaw** [magento/magento2#8888]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@R-K-Shrivastaw please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
