### ISSUE TITLE
[2.1.5] NULL value mishandled by design configs

### ISSUE THREAD

**Issue by korostii** [magento/magento2#8891]
### Preconditions
Magento 2.1.5

### Steps to reproduce 
While editing design configuration it is apparently possible to reach the following situation when there is a NULL entry for :
http://take.ms/1wpVK

### Expected result
Either would suffice:
1a. In admin, for the storeview it shows empty value (denoting the empty value this storeview has stored), the "Restored Default" button appears (denoting that value of this storeview is different from the website's)
OR
1b. Title of pages in this storeview has the website-level suffix present on storefront.

### Actual result
1. In admin, for the storeview it shows the website's value (as if it's getting inherited), the "Use Default Value" button does not appear

And at the same time: 
1. Open frontend (any category page)
2. Title has no suffix.

### Workaround
If the `stores` scope has a different value (in this case a "restore default" button appears http://take.ms/PTBN1 ) - then frontend functionality works as expected.

### Additional Observations
Here's where the config value is being retrieved when used in storefront
https://github.com/magento/magento2/blob/2.1.5/lib/internal/Magento/Framework/View/Page/Title.php#L113

I guess NULL is an okay value to get returned here, as well as converting it to empty string when concatenating, however in this particular explained case it is inconsistent that admin backend shows a different value.

**Comment by magento-engcom-team** [comment]
Hi @korostii.
In latest version (2.1.9) the issue is fixed: you can restored default value in admin.

**Comment by magento-engcom-team** [comment]
@korostii, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10

**Comment by korostii** [comment]
> In latest version (2.1.9) the issue is fixed

Are you certain about that? I don't see any changes between 2.1.5 and 2.1.10 in the code referenced. 
Would you care to point me to a specific commit if the issue was fixed elsewhere?

> you can restored default value in admin.

.. if the store-level value isn't `NULL`. Have you actually tested this with a `NULL` value? 
That is what this ticket is about.

> If you'd like to update it, please reopen the issue.

Reporter cannot reopen an issue if it was closed by a repository owner or contributor. That's just how GitHub works.
