### ISSUE TITLE
Unused dependency in OrderRepository.php

### ISSUE THREAD

**Issue by 4quaternion** [magento/magento2#8895]
Please, remove unused dependency in \Magento\Sales\Model\OrderRepository

https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/OrderRepository.php#L9

**Comment by orlangur** [comment]
Most likely `php-cs-fixer` will remove all such occurrences successfully.

**Comment by ikrs** [comment]
Ill take it

**Comment by okorshenko** [comment]
@ikrs thank you for your fix https://github.com/magento/magento2/pull/8907
