### ISSUE TITLE
Jquery form validation is not working for dynamic form element

### ISSUE THREAD

**Issue by radhagobinda** [magento/magento2#8898]
### Preconditions

1. Magento Version: 2.1.5
2. PHP 7.1 , MYSQL 5.7
3. server UBUNTU 16.06

### Steps to reproduce

1. We have a custom form in front-end. For form validation, we used Magento default jquery form validation. And it's worked perfectly. But problem is that, This form have some dynamic content and this content is not validate.
 **My jquery code**
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){

   var dataForm = $('#custom-form');
   dataForm.mage('validation', {});

});
</script>
### Expected result

![custom-form-error](https://cloud.githubusercontent.com/assets/19976130/23986522/a491ca08-0a4a-11e7-8595-c31decc481b4.png)

this first row is not dynamic. After I click add more button then others row will appeared.
<input name="datepurchased[]" title="Purchase Date" class="input-text pur-cal" type="text" data-validate="{required:true}" aria-required="true">

input name="datepurchased[]" title="Purchase Date" class="input-text pur-cal" type="text" data-validate="{required:true}" aria-required="true"  

This is my input field.

I want to know that, How to validate this dynamic content in that form.
Please help me. Thanks.

**Comment by sibhis** [comment]
I'm facing same issue..Did you find any solution?

**Comment by radhagobinda** [comment]
Hi Sibhis,

Yes I have solved this problem. One thing you can do that remove the ID from every field then try it. Actually problem is that, every field have same ID for every row. that's why they have checked only first row. 

Hopefully now you can solve it.

**Comment by sibhis** [comment]
In my case, there is no id in the element

**Comment by sibhis** [comment]
https://magento.stackexchange.com/questions/154510/magento-2-how-to-make-validation-on-same-name-array-input

This link is helped for the solution...
