### ISSUE TITLE
why home page of child Luma theme is different from Luma?

### ISSUE THREAD

**Issue by AndroidDesigner** [magento/magento2#8899]
Hi.
I have created a custom theme same as magento docs. it works correctly and I can customize it.
but I don't know why the homepage of my theme (child of Luma) and Luma are different.
while I didn't create any customization in my theme folder, yet.
my theme folder has only the following files yet:
registration.php
composer.json (Parent is Luma)
theme.xml (Parent is Luma)

so, I expect that my homepage and it's parent (Luma) be same.but Luma homepage images does not exist in it's child.
in fact, footer and header are same. but body in not same.why?
child of Luma theme homepage :
![1](https://cloud.githubusercontent.com/assets/19887511/23986784/2f5d82c2-0a3b-11e7-8709-97e56b945343.png)

Luma theme homepage:
![2](https://cloud.githubusercontent.com/assets/19887511/23986838/7a96109c-0a3b-11e7-91ee-51e93dd9e270.png)

**Comment by mrkhoa99** [comment]
@AndroidDesigner the good place to start is the Magento dev docs:

- http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-create.html
- http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css-practice.html

Note: we also can see the Css changes after deleting and running static content deploy command.

**Comment by AndroidDesigner** [comment]
@mrkhoa99 what do you mean?
I already read these pages and implement full steps so that I can customize my theme.
but I don't know why child of Luma theme (without any customization), does not have same homepage?!

**Comment by veloraven** [comment]
@AndroidDesigner thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@AndroidDesigner please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by rahulanand77** [comment]
This is by default behaviour, home page will come blank. Solution and reason is:

**Reason**

1) Luma theme has widget called "Home Page", which is applicable to Luma theme only.

**Solution**

1) Create a new widget same as "Home Page" and assign it to your custom theme.
2) Set the layout to "Main content area"
3) Choose "Home Page" block.
4) Save and clear your cache. It will show you the same home page as "Luma" theme.
