### ISSUE TITLE
REST StoreConfig information is incomplete

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#8900]
### Preconditions

1. All versions. Tested on 2.1.4

### Steps to reproduce

1. Change default product link suffix in Stores -> Configuration -> SEO settings.

### Expected result

1. REST enpoint /V1/store/storeConfigs response should contain link suffix, among lots of other settings that can be done on a store. As an integrator, I want to be able to link to products obtained via the REST API.

### Actual result

1. It doesn't contain all the information needed to make a link.

**Comment by RomanKrut** [comment]
@fvschie Hi, I send Rest Api request /V1/store/storeConfigs and i got what is documented on. http://devdocs.magento.com/swagger/index_21.html , refer to the documentations to see how the result of the request should look like. If you think it should give you more information, please submit to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
