### ISSUE TITLE
Installation is incomplete.  Help me!!!

### ISSUE THREAD

**Issue by birdza007** [magento/magento2#8902]
Please....

Installing data...  Installing... 69%

Installation is incomplete. 
Check the console log for errors before trying again.

[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Wrong attribute group ID' in /var/www/health/shop/vendor/magento/module-eav/Setup/EavSetup.php:664
Stack trace:
#0 /var/www/health/shop/vendor/magento/module-eav/Setup/EavSetup.php(1242): Magento\Eav\Setup\EavSetup->getAttributeGroupId('4', '14', 'General')
#1 /var/www/health/shop/vendor/magento/module-eav/Setup/EavSetup.php(841): Magento\Eav\Setup\EavSetup->addAttributeToSet('4', '14', 'General', 'swatch_image', 3)
#2 /var/www/health/shop/vendor/magento/module-swatches/Setup/InstallData.php(65): Magento\Eav\Setup\EavSetup->addAttribute('catalog_product', 'swatch_image', Array)
#3 /var/www/health/shop/setup/src/Magento/Setup/Model/Installer.php(844): Magento\Swatches\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#4 /var/www/health/shop/setup/src/Magento/Setup/Model/Installer.php(796): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#5 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#6 /var/www/health/shop/setup/src/Magento/Setup/Model/Installer.php(344): call_user_func_array(Array, Array)
#7 /var/www/health/shop/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#8 /var/www/health/shop/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/health/shop/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/health/shop/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/health/shop/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/health/shop/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/health/shop/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/health/shop/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/health/shop/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/health/shop/setup/index.php(31): Zend\Mvc\Application->run()
#19  #{main}

**Comment by mzeis** [comment]
Hi,

do you still need help? If yes, please try with the current stable version and provide some more information:

* Which version of PHP / MySQL did you use?
* Which settings did you use for the installation (anything that is different from the default pre-selected versions)?
* Did you try to install Sample Data?

etc.

Thanks!

**Comment by magento-engcom-team** [comment]
Closing this issue. No response from reporter
