### ISSUE TITLE
Backend "insert image" button on static block clickable only once.

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#8905]
The "insert image" button in the backend static block edit page is clickable only once. If you close the overlay and click again nothing happens.

### Preconditions

1. Tested on 2.13

### Steps to reproduce

1. Go to backend
2. Go to static block edit (or add) page
3. Click on "insert image"
4. Close the overlay window
5. Click again on "inser image"

### Expected result

1. Overlay windows reopens

### Actual result

1. Nothing happens

**Comment by russelllogozar** [comment]
We're seeing this as well on 2.1.4 (CE and EE).  It appears that it is throwing a JavaScript error:
```
Uncaught TypeError: Cannot read property 'closed' of undefined
    at Object.openDialog (browser.js:39)
    at HTMLButtonElement.onclick ((index):261)
```

**Comment by russelllogozar** [comment]
@giacmir - See https://github.com/magento/magento2/issues/4884.  This is the same issue.

**Comment by veloraven** [comment]
@giacmir thank you for your report but I'm closing this issue as a duplicate.
Internal ticket - MAGETWO-63824. It was fixed and fix will be available in one of next releases.
@russelllogozar thank you for your note.
