### ISSUE TITLE
Will the description of the goods available for different languages?

### ISSUE THREAD

**Issue by chrom** [magento/magento2#891]
I mean that there will be an opportunity to set description separately on each of the languages that are on the site?

**Comment by Tiurnikova** [comment]
Hey @chrom,
that's one of the features we are thinking about.
It would be very helpfull if you provide some use cases from your experience when you missed this feature. 
Like, how many languages did you manage on your website? How often did you edit the product description? Did you use the same content for different locales or you created unique content for each location?

Thanks

**Comment by Tiurnikova** [comment]
Hey @chrom 
We created a ticket in our internal backlog for a such feature request. It will be handled according to the priorities.
Thank you so much for your answers. Any information is important to us to get a better understanding of the needs of our customers.
