### ISSUE TITLE
Unable to display the cart page when logged in with a product with file option

### ISSUE THREAD

**Issue by clementguillot** [magento/magento2#8916]
### Preconditions
1. Magento 2.1.5 fresh install (also affects 2.1.4)

### Steps to reproduce
1. Go to the administration
2. Create a product with a required Customizable Option which type is « File »
3. Activate the following store configuration “Sales > Sales > Gift Options > Allow Gift Messages on Order Level > Yes”
4. Refresh cache if any
5. Go to the store
6. Add the product to the cart
7. Create an account and log in
8. Go to the cart page (checkout/cart)

=> go the the cart page, logged in, with any product that have a required custom option of type "File"

### Expected result
1. The cart page (items, prices etc.) 

### Actual result
1. The following exception:
`Exception #0 (Magento\Framework\Exception\LocalizedException): Please specify product's required option(s).
#0 /var/www/magento2ce/vendor/magento/module-quote/Model/Quote/Item/CartItemPersister.php(72): Magento\Quote\Model\Quote->updateItem('1', Object(Magento\Framework\DataObject))`

Full stack trace: http://pastebin.com/QrQrn12k

Please let me know if i can do something to help with.

**Comment by Andrii-Deineha** [comment]
@nhx Hi, thanks for reporting this issue.
Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2?

**Comment by clementguillot** [comment]
Hi @Andrii-Deineha , I've just tried with 2.1.7, I no longer have the issue.

**Comment by veloraven** [comment]
@nhx thank you for your comment.
I'm closing this issue.
If you experience the same issue againg please create new GitHub issue for it.
