### ISSUE TITLE
Shipping Table Rate always goes to 0(zero) weight vs destination

### ISSUE THREAD

**Issue by ngherbert** [magento/magento2#8925]
Hi, I'm working with Magento v2.1.5 which I need to use the shipping table rate method. But unfortunately, whatever the total weight is, it will always goes to 0(zero) weight condition.

### Preconditions

1. v2.1.5
2. PHP 7.0.12
3. MySQL 5.5.53

### Steps to reproduce

1.  Setting Tablerate with province/state and weight 
2.  Specific countries
3.  No cart or promotion rules at all

### Expected result

1.  Expected to get the shipping rate as the weight in cart

### Actual result

1.  Rate always goes to 0(zero) weight price, but region working as expected

**Comment by juliandamass** [comment]
Hi there
Is there any information regards this bug as I am experiencing the same issue on version 2.1.5
Thanks

**Comment by ngherbert** [comment]
Hi @juliandamass , till today still not get the workaround yet. Our team still looking the wayout. Probably need to purchase other third party extension to resolved this issue. Hopefully others will looking the way out as well for this issue.

**Comment by wenhaokho** [comment]
I am also facing this issue after upgrading from 2.1.3 to 2.1.5

**Comment by oleg-onufer** [comment]
Hi @ngherbert.
I cannot reproduce this issue.
Please add more details to your description of the steps you followed when identifying this issue. 
Screenshots would be helpful, too.
