### ISSUE TITLE
Update sjparkinson/static-review to latest version

### ISSUE THREAD

**Issue by 4quaternion** [magento/magento2#8932]
Please, update "sjparkinson/static-review": "~4.1", package to lates version ~5.2 in order to support PHP 7.0

https://github.com/sjparkinson/static-review/releases/tag/5.2.0 - latest release

**Comment by magento-engcom-team** [comment]
@4quaternion, thank you for your report.
We've created internal ticket(s) MAGETWO-83001 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @4quaternion 
This dependency was removed now due to redundancy. 
Thanks for collaboration.
