### ISSUE TITLE
Big Trouble Magento 2

### ISSUE THREAD

**Issue by mariorodriguesnt** [magento/magento2#8935]
I was trying to add some templates and Thmes, but suddenly everything has stopped 

when I tried bin/magento setup:upgrade shows this

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Composer\ComposerInformation::__construct() must be an instance of Magento\Framework\Composer\MagentoComposerApplicationFactory, instance of Magento\Framework\Composer\ComposerFactory given, called in /app/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /app/html/vendor/magento/framework/Composer/ComposerInformation.php:92
Stack trace:
#0 /app/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): Magento\Framework\Composer\ComposerInformation->__construct(Object(Magento\Framework\Composer\ComposerFactory))
#1 /app/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#2 /app/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#3 /app/html/vendor/magento/framework/Objec in /app/html/vendor/magento/framework/Composer/ComposerInformation.php on line 92

Could someone help me, please??

**Comment by mrkhoa99** [comment]
@mariorodriguesnt should delete `var/generation` folder.

**Comment by korostii** [comment]
Yep and also make sure you're running in "developer" mode, otherwise you might also need to delete the `var/di` folder and run `setup:di:compile`

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and support. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
