### ISSUE TITLE
No REST API Ability to Get Category ID Given Category Name

### ISSUE THREAD

**Issue by EyalAmir** [magento/magento2#8936]
Should be able to search for a specific category using the name, parent, and other criteria. Otherwise, to sync products to Magento 2 and lookup the proper category IDs, we need to retrieve the full category tree which is costly if you have a large category tree.

**Comment by maghamed** [comment]
Looks like here is the service contract you are looking for 
https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Catalog/Api/CategoryListInterface.php

And here is WebAPI for it
https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Catalog/etc/webapi.xml#L358-L362

**Comment by EyalAmir** [comment]
That doesn't take any parameters does it? My point was that dumping the whole list of categories just to get the ID of one category is very costly so we need a way to be able to search for a specific category.

**Comment by magento-engcom-team** [comment]
@EyalAmir Thank you for the report. Currently this is an expected behavior. Please set up a Pull Request if you have a proposed way to improve this.
