### ISSUE TITLE
'URL key for specified store already exists.' cannot save category and products. 'URL key not generate when save categories or products also when import prducts'.

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento/magento2#8937]
I am facing "URL key for specified store already exists" error when i am trying to update existing category or product for default store view as well as on secondary store view.

I have try to replicate the issue, When i check found problem in the following scenario.

When save the category it will update the category url also the associated products url in url rewrite table.
When update the category if some product not have a url key or some products url key not updated in url rewrite table that time only this issue occurs.

When I am save the product or category the url key is not generated. Also when i import the product that time also the url key is not generated.

### Preconditions

1. Magento Vesrion : 2.1.3
2. Php Version :  7
3. Mysql Version : 5.7

### Steps to reproduce

1. Go to Products > Categories
2. Select the Category 
3. Click Save

**(Or)** 

1. Go to Products > Catalog
2. Select the Products
3. Click Save

### Expected result

1. Successfully save the category and product also url key is generated sucessfully.

### Actual result

1. "URL key for specified store already exists" the error came.
2. Url Key is not generated.

**Comment by veloraven** [comment]
@ewallkrishnaprakash thank you for your report.
Is this issue still actual and reproduces on later version?

**Comment by vikasneoventis** [comment]
0
down vote
	

I was also facing same issue while adding/editing categories.

Firstly I found there was wrong attribute id in "catalog_category_entity_varchar" table for url_key and url_path. Then I checked the exect attribute_id of both attributes ('url_key' and 'url_path').

e.g in "catalog_category_entity_varchar" table it was showing '117' and '118' but exact id was '119' and '120'. Then I found there was some rows in "catalog_category_entity_varchar" table with these (correct id '119','120').

I followed below steps to resolve issue.

    firstly I searched rows in "catalog_category_entity_varchar" where attribute id is in (117,118) and exported the data from table.
    then I searched rows in "catalog_category_entity_varchar" where attribute id is in (117,118,119,120) and deleted these data (rows) from table.
    then I just opened exported file in notpadd++ then I changed attribute ids 117 with 119 and 119 with 120 and import the data again.

Make sure take the backup of the database before doing above steps.

**Comment by magento-engcom-team** [comment]
@ewallkrishnaprakash, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more details regarding your environment, or try to reproduce this
issue on a clean installation.

**Comment by orlangur** [comment]
System behaves normally in current implementation if your data is valid in the first place. If https://github.com/magento/data-migration-tool produces invalid data in some cases, it should be reported.

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.
