### ISSUE TITLE
Please correct the user name or password.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#894]
When i login to admin i'm getting following error.

Please correct the user name or password.
1. i have created admin user ,and assigned to role.but still i'm getting same error(using md5 ).
2.How to re run magento installation? or how to create admin user progratimcally?

**Comment by orlangur** [comment]
> i have created admin user ,and assigned to role.but still i'm getting same error(using md5 ).

You mean directly in database?

> How to re run magento installation?

Just remove `app/etc/config.php`. Also, looking at #892 it seems to me that re-creating of the database could be useful.

**Comment by sivajik34** [comment]
than you.its working fine
