### ISSUE TITLE
@escapeNotVerified through multiple templates

### ISSUE THREAD

**Issue by flagbird** [magento/magento2#8945]
In Magento 2 templates, there are multiple `@escapeNotVerified` annotations added by the commit https://github.com/magento/magento2/commit/1e8ba207b626bfdbff611cbc7a047b6cc74b5cf2. It is mentioned in the commit message, that these are "potentially unsafe outputs", but this was added 2 years ago.

Will this be reviewed somewhere in the future or is this going to stay like it is? What would you suggest when a template has to be overridden because of changes? Shouldn't these values be escaped?

**Comment by magento-engcom-team** [comment]
@claudioflagbit, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
