### ISSUE TITLE
Magento 2.1.1 Payment Issues Authorize.net and PayPal

### ISSUE THREAD

**Issue by SewHappy58** [magento/magento2#8946]
We are trying to go live with a fresh install of Magento 2.1.1.  However, a final test for payment resulted in below errors.  We were able to place an order if using check/money order but not any other form.

We are using PHP ver. 5.6

### Steps to reproduce
Authorize.net 
1. Purchase something on Magento 2.1.1 store
2. Go to cart and select credit card form of payment
3. Enter card information and submit
4. After a short delay, error message appears - Attention: an error on the server.  Please try to place the order again.
5. Payment not process nor is order placed

PayPal 
1. Purchase something on Magento 2.1.1 store
2. Go to cart and select PayPal form of payment
3. Redirected to PayPal site 
3. Enter card information and submit
4. Returns to website with an error 
5. Payment not process nor is order placed

### Expected result
1. complete purchase

### Actual result
1.  Error message  
![screen shot 2017-03-19 at 5 00 44 pm](https://cloud.githubusercontent.com/assets/7072324/24105102/e7057006-0d51-11e7-8b6b-78408c935d08.png)

**Comment by SewHappy58** [comment]
Ok, so I was testing my site and it's now working.  It wasn't working when we updated the DNS A Record.  Not sure why, but I am now closer to finding out the problem.

**Comment by YevSent** [comment]
Hi, @SewHappy58, please, enabled `debug` mode for both payment and post response details from payments. Also, please, post response from Authorize.net `transact.dll`.

**Comment by SewHappy58** [comment]
After further investigation, I noticed when I reverted my DNS back, keeping the default Cloudways URL, the site now works and there is no issue.  So why would PayPal or Authorize.net not work when I propagate my DNS?  I'm updating the A record only and the domain is being hosted elsewhere then server. It makes me wonder if something is happening during the process?  I gave it 24hrs and the site was pulling up correctly with the new domain name, just not able to make a payment.  

 I wasn't able to get response as payment just didn't go through. Because this is an upgraded site, I reverted everything so my old website could still work.

**Comment by YevSent** [comment]
Please, contact with PayPal and Authorize.net support to get more details about your infrastructure problem.

Now, I'm closing this issue as not related to Magento functionality. If after your investigation you will find an issue related to Magento, please, be free to reopen this ticket.
