### ISSUE TITLE
Error While Trying To Load Quote Item Collection Using Magento\Quote\Model\ResourceModel\QuoteItem\Collection::getItems()

### ISSUE THREAD

**Issue by rendyep** [magento/magento2#8954]
### Preconditions
1. Magento 2.1.5

### Steps to reproduce
1. Load Quote Item Collection using Magento\Quote\Model\ResourceModel\QuoteItem\Collection::getItems()

`$quoteItemCollection = $this->quoteItemCollectionFactory->create()->getItems();`

### Expected result
1. I get array of Quote Items

### Actual result
1. Thrown an error:
`Fatal error: Uncaught Error: Call to a member function getStoreId() on null in C:\www\magento2\vendor\magento\module-quote\Model\ResourceModel\Quote\Item\Collection.php:98`
`Stack trace:`
`#0 C:\www\magento2\vendor\magento\module-quote\Model\ResourceModel\Quote\Item\Collection.php(209): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->getStoreId()`
`#1 C:\www\magento2\vendor\magento\module-quote\Model\ResourceModel\Quote\Item\Collection.php(169): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts()`
`#2 C:\www\magento2\vendor\magento\framework\Data\Collection\AbstractDb.php(586): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_afterLoad()`
`#3 C:\www\magento2\vendor\magento\framework\Data\Collection\AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)`
`#4 C:\www\magento2\vendor\magento\framework\Data\Collection.php(333): Magento\Framework\Data\Collection\AbstractDb->load()`
`#5 ----------`

**Comment by magento-engcom-team** [comment]
@rendyep, thank you for your report.
We've created internal ticket(s) MAGETWO-80999 to track progress on the issue.

**Comment by nemesis-back** [comment]
I will work on it #SQUASHTOBERFEST 2017

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83023

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @rendyep. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by sidolov** [comment]
Hi @rendyep. Thank you for your report. 
The issue has been fixed in magento/magento2#15829 by @neeta-wagento in 2.1-develop branch
Related commit(s):
 - [c261156c46b3211564056866cdb436b7cfd2ca9d](https://github.com/magento/magento2/commit/c261156c46b3211564056866cdb436b7cfd2ca9d)
 - [950e3170e5d17a3f420605cec8c07d096d3ccd0a](https://github.com/magento/magento2/commit/950e3170e5d17a3f420605cec8c07d096d3ccd0a)

The fix will be available with the upcoming 2.1.15 release.
