### ISSUE TITLE
Sorting by Tax Class does nothing

### ISSUE THREAD

**Issue by jurgisl** [magento/magento2#8956]
Magento 2.1.4 CE

### Preconditions
At least 2 products with different Tax Class assigned.

### Steps to reproduce
1. Admin > Products > Catalog
2. Add Tax Class column
3. Press on Tax Class column header
4. Press again on Tax Class column header

### Expected result
1. Products should change order

### Actual result
1. Products have the same order.

Actually, if there are more products and the Tax Class is different on one of the products in the middle of the list, then you could see that Order is ignored altogether. The product stays in the middle of the list, though it should be in the start or beginning.

The same happens to our custom Tax Class like attributes (having values in external table, not in EAV).

**Comment by IlnitskiyArtem** [comment]
@jurgisl , Thanks for reporting this issue. 
Created internal issue MAGETWO-70282 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@jurgisl, thank you for your report.
We've created internal ticket(s) MAGETWO-70282 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@jurgisl 
, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
