### ISSUE TITLE
Permanent Redirect for old URL missing via API

### ISSUE THREAD

**Issue by MarcoGrecoIttweb** [magento/magento2#8957]
### Preconditions

Magento 2.1.2 CE
Multiple websites configured

### Steps to reproduce(working):
- go in admin area
- clear url-key field in product
- keep checked "Create Permanent Redirect for old URL"
- changes product name
- save

### Steps to reproduce(broken):
- call myownmagento.test/index.php/rest/all/V1/products with correct authentication token with json data and url_key_create_redirect or save_rewrites_history to 1
example with sample data:

> {"product":{"sku":"WSH10","name":"Ana Running Short changed","attribute_set_id":9,"price":0,"status":1,"visibility":4,"type_id":"configurable","weight":"0.1","extension_attributes":{"configurable_product_links":[2016,2017,2018,2019,2020,2021],"stock_item":{"use_config_enable_qty_inc":false,"manage_stock":true,"is_in_stock":true}},"custom_attributes":[{"attribute_code":"tax_class_id","value":2},{"attribute_code":"required_options","value":1},{"attribute_code":"has_options","value":1},{"attribute_code":"category_ids","value":["254"]},{"attribute_code":"description","value":"Test"},{"attribute_code":"url_key","value":""},{"attribute_code":"url_key_create_redirect","value":1}]}}

### Expected result
1. old product url is redirected to new one 

### Actual result
1. old url go in 404 error

### Some additionals notes:

I noticed that in admin area saving product and import there is a url_key_create_redirect check by code to force the url redirection that missing completely in API feature

**Comment by mengbo123456** [comment]
![image](https://user-images.githubusercontent.com/29748690/27776089-3146de22-5fda-11e7-9ed4-d11214d294c4.png)

**Comment by RomanKrut** [comment]
@MarcoGrecoBitbull Hi. Thanks for reporting this issue. The internal ticket MAGETWO-70831 was created.

**Comment by QuentinHK** [comment]
Hi. Any quick fix for this, please?
We manage URLs and product names on other systems so it is really important to be able to generate redirects and rewrites. Thanks

**Comment by koenner01** [comment]
Hopefully this is picked up soon because this is an SEO nightmare..

**Comment by koenner01** [comment]
So I might have found a solution for this problem. I did some digging and in \Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver there is a function generateForAutogenerated() which checks if the product has data for 'save_rewrites_history'. However if you trace back to were this function is called, products get their data filtered in _populateForUrlGeneration() function and any value set for the 'save_rewrites_history' field will be removed.

```
foreach ($this->vitalForGenerationFields as $field) {
    if (isset($rowData[$field])) {
        $product->setData($field, $rowData[$field]);
    }
}
```
We added a preference on this class and added the 'save_rewrites_history' to the $vitalForGenerationFields array. 

If we now pass in a value through the import data for this 'save_rewrites_history' field, the value will now remain in the data and the if check on $product->getData('save_rewrites_history') in generateForAutogenerated() will not trigger.

A sidenote however; We are running the import through the CatalogImportExport classes of M2, so I cannot confirm this would solve the problem while importing data through the API.

**Comment by QuentinHK** [comment]
@koenner01 Thanks for digging in. What did you change exactly? I'm willing to test it with the API.

**Comment by koenner01** [comment]
Well like I said, I added a preference on the \Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver class in our module. It adds the 'save_rewrites_history' to the vitalForGenerationFields array

```
class AfterImportDataObserver extends \Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver
{
    protected $vitalForGenerationFields = [
        'sku',
        'url_key',
        'url_path',
        'name',
        'visibility',
        'save_rewrites_history'
    ];
}
```

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver"
        type="<ourVendor>\<ourModule>\Observer\CatalogUrlRewrite\AfterImportDataObserver" />
</config>
```

I'm not sure if you are working with a seperate module for your import, but you will need a module to add this preference

**Comment by magento-engcom-team** [comment]
@MarcoGrecoBitbull, thank you for your report.
We've created internal ticket(s) MAGETWO-70831, MAGETWO-73010 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @MarcoGrecoBitbull. Thank you for your report. 
The issue has been fixed in magento/magento2#13567 by @adrien-louis-r in 2.2-develop branch
Related commit(s):
 - [1ef4dcc110062612e9971d7f8fb788bef213df3f](https://github.com/magento/magento2/commit/1ef4dcc110062612e9971d7f8fb788bef213df3f)
 - [864f371aed88884fb73082deb0c856819c43a41f](https://github.com/magento/magento2/commit/864f371aed88884fb73082deb0c856819c43a41f)

The fix will be available with the upcoming 2.2.4 release.

**Comment by kingshukdeb** [comment]
This same issue exists with category too. When you try to update a category via API it doesnt create permanent redirect for old URL.

**Comment by magento-engcom-team** [comment]
Hi @MarcoGrecoBitbull. Thank you for your report. 
The issue has been fixed in magento/magento2#14252 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3](https://github.com/magento/magento2/commit/03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3)
 - [1322d8be3e64695effbfb525a22c3aed02587b1e](https://github.com/magento/magento2/commit/1322d8be3e64695effbfb525a22c3aed02587b1e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by juanremi** [comment]
i think the problem continue in Magento ver. 2.3.4

**Comment by amenk** [comment]
@juanremi which problem? For Products or Categories? For categories see #29174

**Comment by juanremi** [comment]
@amenk for Products updated via api

**Comment by amenk** [comment]
@juanremi  Interesting, I suggest you open a new issue (and link it with this one) with your case and clear steps to reproduce, for us it seems to work in 2.3.3-p1 (for products)
