### ISSUE TITLE
Hint mistake in english language

### ISSUE THREAD

**Issue by JDThralls** [magento/magento2#8958]
### Preconditions

1. Magento 2.1.5 (downloaded from official website with timestamp 2017-02-20)
2. PHP 7 on Apache dedicated server (does not actually matter)

### Steps to reproduce

1. Logged in to admin panel
2. Content -> Configuration
3. Global configuration hint is shown as follows in english:

### Actual result
"Search strings are either normal strings or regular exceptions (PCRE)."

### Expected result
"Search strings are either normal strings or regular expressions (PCRE)."

**Comment by JDThralls** [comment]
This mistake is in the documentation as well:

Example:
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html
Under "Add A Design Exception"
"In the Search String box specify the user-agent using either normal strings or regular exceptions (PCRE). In the Theme Name drop-down list select the theme to be used for matching agent."
where it should say
"In the Search String box specify the user-agent using either normal strings or regular expressions (PCRE). In the Theme Name drop-down list select the theme to be used for matching agent."

**Comment by mbrinton01** [comment]
Thank you @MighT-W315H31T for catching this. Would you be able to create a PR to fix?  We also accept PRs for docs: http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing_docs.html

**Comment by magento-engcom-team** [comment]
@MighT-W315H31T, thank you for your report.
We've created internal ticket(s) MAGETWO-80537 to track progress on the issue.

**Comment by jahvi** [comment]
Just wanted to give this one a go with #11390, I also submitted a PR to fix the docs with https://github.com/magento/devdocs/pull/1450

**Comment by magento-engcom-team** [comment]
Hi @MighT-W315H31T the issue has been fixed in 2.2-develop branch and will be available with release 2.2.1 soon.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81679

**Comment by magento-team** [comment]
Hi @MighT-W315H31T. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
