### ISSUE TITLE
Configurable upsell/linked items zero (0.00) price in admin product edit

### ISSUE THREAD

**Issue by jzahedieh** [magento/magento2#8960]
### Preconditions

1. Magento EE 2.1.4
2. PHP 7.1

### Steps to reproduce

1. Login to admin
2. View configurable product with configurable product upsell products

### Expected result

1. Up-sell price should not be 0

### Actual result

1. Up-sell price is not be 0

_Note: This happens with related + crossell types too._

### Analysis

In the `vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Related.php::modifyData($data)` method the following line is called:

    $data[$productId]['links'][$dataScope][] = $this->fillData($linkedProduct, $linkItem);

Which relates the following method. 

    protected function fillData(ProductInterface $linkedProduct, ProductLinkInterface $linkItem)
    {
        return [
        	...
            'price' => $linkedProduct->getPrice(),
            ...
        ];
    }

Which calls the following in `vendor/magento/module-catalog/Model/Product.php`:

    public function getPrice()
    {
        if ($this->_calculatePrice || !$this->getData(self::PRICE)) {
            return $this->getPriceModel()->getPrice($this);
        } else {
            return $this->getData(self::PRICE);
        }
    }

The `getPriceModel()` method is called which calls the following for a configurable product `vendor/magento/module-configurable-product/Model/Product/Type/Configurable/Price.php`:

    public function getPrice($product)
    {
        if ($product->getCustomOption('simple_product')) {
            return $product->getCustomOption('simple_product')->getProduct()->getPrice();
        } else {
            return 0;
        }
    }

Which is where the 0 value comes from.

### Fix/Workaround

In the `vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Related.php::modifyData($data)` after initilising the `$linkedProduct` the following method can be used to disable calculating a price and return the base price of the configurable product:

	$linkedProduct->setPriceCalculation(false);

I'm unsure of the impact this will have though and is really a work around to this issue.

**Comment by magento-engcom-team** [comment]
@jzahedieh, thank you for your report.
We've created internal ticket(s)  to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@jzahedieh, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
