### ISSUE TITLE
email logo error

### ISSUE THREAD

**Issue by hasan4it** [magento/magento2#8961]
### Preconditions

1. no logo
2. 

### Steps to reproduce

1. upload a logo for email header
2. 
3. 

### Expected result

1. should update the logo name in database and upload the logo on the server

### Actual result

1. logo name updated in the db but no actual logo uploaded into the server, I manually upload the logo the desired location. all directories are set permissions to 777

**Comment by okorshenko** [comment]
Pull Request #9590 has been merged to 2.1-develop branch. Thank you @hostep for your contribution!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
