### ISSUE TITLE
@ magento2 team --> Are you guys on holiday or why is nobody marking and answering tickets here since weeks/month?

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#8963]
@ magento2 team --> Are you guys on holiday or why is nobody marking and answering tickets here since weeks/month?

Really disappointing how you guys handle bugs 👎

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) discussion topics.
