### ISSUE TITLE
Magento 2.1.4 Store View Switching Probelem

### ISSUE THREAD

**Issue by sabarivenkatesankrish** [magento/magento2#8967]
I am having two store views namely "English" and "Arabic". My default store view is "Engilsh". When I switch my store view to "Arabic" from "English", its working. After that If I click any product or category page, it redirects to English.

When I set "Add Store Code to URL" to 'Yes' in Stores > Configuration > General > Web it works properly. 

I need to work my store views by putting "Add Store Code to URL" as 'No' only. Kindly guide me to fix this issue.

### Preconditions:
1. I have installed Magento 2.1.4.
2. Created two store views(English, Arabic)
3. I have set "Add Store Code to URL" to 'No' in Stores > Configuration > General > Web

### Steps to reproduce:
1. Switch store view from English to Arabic by clicking the switcher option on the top.
2. Go to any product or category page, from the switched store view.

### Expected result:
1. Should go the the corresponding product or category page with same store view.

### Actual result:
1. Redirects the the corresponding product or category page with Default store view.

Thanks,

**Comment by korostii** [comment]
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.

**Comment by Ctucker9233** [comment]
@sabarivenkatesankrish I have noticed this behavior as well. Why is it important that you need to do this with "store code in URL" set to no? I believe the official documentation gives guidance on how to do this, although, for the life of me, I can't get it to work. Having the store code in the URL is the only thing that has worked for me. @korostii perhaps this topic can be moved to the documentation GitHub, as the documentation lacks details on how to properly set up a store with multiple views.

**Comment by sabarivenkatesankrish** [comment]
@Ctucker9233 Thanks for your feedback. I explain my exact need. The concept is need to the switch the  store view based on the customer's preferred locale. I am having custom customer attribute for the preferred locale. Based on that value I need to switch the customer's locale when they logged in. And should change to the default store view when they logged out. With the events and observers, I tried this. Since we have store code in the Url itself, I can't able to switch. When I tried without adding store code in Url, it works fine but having above mentioned issue.

In magento community forum someone has posted the same issue, but he has problem in payment gateway due to store code in the Url. 
https://community.magento.com/t5/Technical-Issues/magento-2-1-5-store-view-switching/m-p/63763#M2114 

In magento 1, by default without store code everything works fine. That's why I created this thread. May be with store code, it is possible to do means, I will go for that. Not an issue.

@Ctucker9233 Thanks for spending  your valuable time.

**Comment by Ctucker9233** [comment]
@sabarivenkatesankrish My guess would be that your custom customer attribute is not being read correctly. I found this article that may be useful for you. https://community.magento.com/t5/Admin-Configuration-Questions/How-to-automatically-redirect-to-a-store-view-based-on-the/td-p/10634

**Comment by magento-engcom-team** [comment]
@sabarivenkatesankrish, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
