### ISSUE TITLE
Fotorama zoom buttons don't work

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#8968]
### Preconditions

1. Magento v2.1.2
2. Chrome 58.0.3029.19 beta on Windows 7

### Steps to reproduce

1. Go here: http://magento2-demo.nexcess.net/caesar-warm-up-pant.html
2. Click on image to open zoom overlay
3. Click [+] and [-] buttons to zoom in/out

### Expected result

1. The image should zoom in and out.

### Actual result

1. Nothing happens. You can only zoom using the scrollwheel, which is not acceptable.

**Comment by grafikchaos** [comment]
The example appears to be zooming in/out just fine for me.

**Comment by thdoan** [comment]
Are you viewing it in a tablet or Windows desktop PC? When I click on the +/- buttons using the mouse in Chrome on Windows 7, nothing happens. However, if I use Chrome developer tools to emulate iPad, then tapping on +/- works as intended.

**Comment by thdoan** [comment]
I realized that the +/- buttons are working, but sometimes you have to click them multiple times to register a click.
