### ISSUE TITLE
Magento 2.1.4 Bundle product with simple product option price as "zero"

### ISSUE THREAD

**Issue by sabarivenkatesankrish** [magento/magento2#8969]
Hi all,
I created a simple product with price as "Zero". I add that product to the cart and it works fine. I created a bundle product with above created simple product as "product options". When add this product in to the cart, it shows the error like "We can't add this item to your shopping cart right now". 
When I checked about this issue, I found there is a problem on a method called collectTotals() in Magento\Quote\Model\Quote model.
 
I tested the same in  Magento 1.9.2, it works fine. But issue with Magento 2 as of my knowledge.
 
### Preconditions:
    1. I have installed Magento 2.1.4 

### Steps to reproduce:
    1. Add simple product with zero price.
    2. Add bundle product with above created simple product as bundle options
    3. Add this bundle product to the cart.

### Expected result:
    1. Should be added in to the cart.

### Actual result:
    1. Shows error like "We can't add this item to your shopping cart right now."

Kindly guide me to fix this issue.
Thanks,

**Comment by RonXS** [comment]
The error is most liketly in the discount model.

Magento\Sales\Model\Quote\Discount.php
in that file on line 180
make sure it only divides if there is a price > 0
thats all there is to it i think.

**Comment by smoskaluk** [comment]
Internal ticket MAGETWO-70323 created

**Comment by magento-engcom-team** [comment]
@sabarivenkatesankrish, thank you for your report.
We've created internal ticket(s) MAGETWO-70323 to track progress on the issue.

**Comment by o-iegorov** [comment]
Fixed in 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @sabarivenkatesankrish 
This issue seems to be fixed in 2.2.x already. You may use the following commits as a reference: b66b35c34c31caacb1fbd51579f0ecfb96b07e4b 10e739aa387d91caa1214b397a360900b09202d2

Thank you
