### ISSUE TITLE
Url rewrite not working.

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#898]
SEO friendly url is not genrated.

for example 
http://localhost/gitmagento2/catalog/category/view/s/cell-phones/id/8/

**Comment by Sanuch** [comment]
Are you use sample data?

**Comment by shivkumarsingh7** [comment]
yes

**Comment by snky1987** [comment]
I just checked it. When I generated sample data URL rewrite is generated (exists correctly in DB) but its not pushed to the front end.

**Comment by maksek** [comment]
Did you install M2 to empty DB?

**Comment by shivkumarsingh7** [comment]
no. I used sample database

**Comment by maksek** [comment]
did you try reinstall? if url_rewrite table doesn't exist - seems like some issues during installation.

**Comment by shivkumarsingh7** [comment]
yes I reinstalled in blank DB now url_rewrite table exist and SEO friendly url is generated.
