### ISSUE TITLE
Error/notice messages issue on PDP

### ISSUE THREAD

**Issue by alexpoletaev** [magento/magento2#8984]
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Clear all cache from the admin panel or terminal
2. Open a category page which have at least one product with required options (lets say it will be a configurable product)
3. Click 'Add to Cart' button on product described above
4. You will be redirected to the product details page

### Expected result

1. The notice message 'You need to choose options for your item.' must be shown

### Actual result

1. There are no error/notice messages shown.

After hours of investigating and debugging here is what I found - If you try to clean cache (this bug can't be reproduced if PDP (product details page) already cached) and click 'add to cart' button on category page for a product which has required options, you will be redirected on PDP, but you won't see error/notice message, because Magento_Review module sends ajax request to render reviews and cleans messages from session BEFORE 'messages' section will be invalidated and rendered. If you will try to reproduce this bug with cached PDP, the notice/error message will appears as expected, because the 'reviews' block will be taken from cache and the ajax request won't clear messages from session.

@magento-team, please fix this bug, because it misleads customers every time Magento cache is cleaned. Thanks!

**Comment by alexnos88** [comment]
Same for me at 2.1.3 and 2.1.4

**Comment by Andrii-Deineha** [comment]
@alexpoletaev Hi,  thanks for reporting this issue. Internal ticket was created MAGETWO-70349.

**Comment by magento-engcom-team** [comment]
@alexpoletaev, thank you for your report.
We've created internal ticket(s) MAGETWO-70349 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @alexpoletaev

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@alexpoletaev, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
