### ISSUE TITLE
Select All checkmark behavior is inconsistent in Admin

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#8986]
### Preconditions

1. Magento v2.1.2
2. 

### Steps to reproduce

1. Go to Admin / System / Cache Management
2. Click on the checkmark circled in red below

![image](https://cloud.githubusercontent.com/assets/4110567/24243883/a283db90-0ff7-11e7-8a7f-a55fd1f1abbf.png)

### Expected result

1. All items should be selected, similar to the behavior on Admin / Products / Catalog. Instead, you have to perform one more click (click "Select All" in dropdown). The behavior should be consistent across all pages where there is a list  of items with checkboxes.

### Actual result

1. Dropdown menu opens instead, forcing you to do one more click, which is inconsistent with the behavior in Admin / Products / Catalog.

**Comment by Ctucker9233** [comment]
@thdoan You need to select "all" from that drop-down menu. Then it should work. Would be nice if the logic was the same as the catalog page, though.

**Comment by thdoan** [comment]
Yeah, sorry if I wasn't being clear: I meant the behavior should be consistent across all pages where there is a list of items with checkboxes.

**Comment by magento-engcom-team** [comment]
Hi @thdoan. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/28
