### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 

### ISSUE THREAD

**Issue by sanjayjethva** [magento/magento2#8987]
Hello Friends,
I am having problem with the indexing. I have migrated data from 1.9.3 to Magento 2.1.3 and facing the issue when i an reindex data via ssh.

I using localhost(XAMPP) and Mysql version 5.0 and Php version 5.6.23.

### Steps to reproduce
Reindex Magento via ssh

### Actual result
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') INNER JOIN `catalog_category_product` AS `ccp` ON ccp.category_id = cc2.child' at line 2, query was: SELECT MAX(category_id) as max, COUNT(*) as cnt FROM (SELECT `cc`.`entity_id` AS `category_id`, `ccp`.`product_id`, ccp.position + 10000 AS `position`, 0 AS `is_parent`, 3 AS `store_id`, IFNULL(cpvs.value, cpvd.value) AS `visibility` FROM `catalog_category_entity` AS `cc` INNER JOIN `temp_catalog_category_tree_index_05960efd` AS `cc2` ON cc2.parent_id = cc.entity_id AND cc.entity_id NOT IN () INNER JOIN `catalog_category_product` AS `ccp` ON ccp.category_id = cc2.child_id INNER JOIN `catalog_product_entity` AS `cpe` ON ccp.product_id = cpe.entity_id INNER JOIN `catalog_product_website` AS `cpw` ON cpw.product_id = ccp.product_id INNER JOIN `catalog_product_entity_int` AS `cpsd` ON cpsd.entity_id = cpe.entity_id AND cpsd.store_id = 0 AND cpsd.attribute_id = 97 LEFT JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cpe.entity_id AND cpss.attribute_id = cpsd.attribute_id AND cpss.store_id = 3 INNER JOIN `catalog_product_entity_int` AS `cpvd` ON cpvd.entity_id = cpe. entity_id AND cpvd.store_id = 0 AND cpvd.attribute_id = 99 LEFT JOIN `catalog_product_entity_int` AS `cpvs` ON cpvs.entity_id = cpe.entity_id AND cpvs.attribute_id = cpvd.attribute_id AND cpvs.store_id = 3 INNER JOIN `catalog_category_entity_int` AS `ccad` ON ccad.entity_id = cc.entity_id AND ccad.store_id = 0 AND ccad.attribute_id = 54 LEFT JOIN `catalog_category_entity_int` AS `ccas` ON ccas.entity_id = cc.entity_id AND ccas.attribute_id = ccad.attribute_id AND ccas.store_id = 3 WHERE (cpw.website_id = '3') AND (IFNULL(cpss.value, cpsd.value) = 1) AND (IFNULL(cpvs.value, cpvd.value) IN (2, 3, 4)) AND (IFNULL(ccas.value, ccad.value) = 1) AND (`cc`.`entity_id` > 0) ORDER BY `cc`.`entity_id` ASC LIMIT 500) AS `t`

Let us know if any one has solution of above problem.

Thanks in advance for your answer.

**Comment by ivokund** [comment]
Having the same issue with Magento 2.1.5. 

Solved this with a temporary hack for now, but looking forward to seeing a solution. 

```patch
===================================================================
--- vendor/magento/module-catalog/Model/Indexer/Category/Product/AbstractAction.php	(revision )
+++ vendor/magento/module-catalog/Model/Indexer/Category/Product/AbstractAction.php	(revision )
@@ -373,6 +373,8 @@
         $rootCatIds = explode('/', $this->getPathFromCategoryId($store->getRootCategoryId()));
         array_pop($rootCatIds);
 
+        $rootCatIds[] = '-1';

```

**Comment by victor-v-rad** [comment]
Hi @sanjayjethva Try to migrate with the latest version of the tool. It might help

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository. See you there if Victor's suggestion won't help.
