### ISSUE TITLE
When accessing any category - error report generated

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#899]
When we set 
store->configuration->catalog->catalog->Search Engine Optimization->
Use Categories Path for Product URLs = YES
Use Canonical Link Meta Tag For Categories = YES
Use Canonical Link Meta Tag For Products = YES
we got following error report

a:4:{i:0;s:147:"Warning: Illegal offset type in isset or empty in /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Asset/MinifyService.php on line 100";i:1;s:3797:"#0 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Asset/MinifyService.php(100): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal offset ...', '/var/www/html/g...', 100, Array)
#1 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Asset/MinifyService.php(75): Magento\Framework\View\Asset\MinifyService->isEnabled(Array)
#2 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(216): Magento\Framework\View\Asset\MinifyService->getAssets(Array)
#3 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(100): Magento\Framework\View\Page\Config\Renderer->renderAssets()
#4 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Result/Page.php(232): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#5 /var/www/html/gitmagento2/lib/internal/Magento/Framework/View/Result/Layout.php(161): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http))
#6 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http))
#7 /var/www/html/gitmagento2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(48): call_user_func_array(Array, Array)
#8 /var/www/html/gitmagento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(64): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#9 /var/www/html/gitmagento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(57): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#10 /var/www/html/gitmagento2/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http))
#11 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http))
#12 /var/www/html/gitmagento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(62): call_user_func_array(Array, Array)
#13 /var/www/html/gitmagento2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(90): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#14 /var/www/html/gitmagento2/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(65): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\View\Result\Page\{closure}(Object(Magento\Framework\App\Response\Http))
#15 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http))
#16 /var/www/html/gitmagento2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(95): call_user_func_array(Array, Array)
#17 /var/www/html/gitmagento2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(223): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#18 /var/www/html/gitmagento2/lib/internal/Magento/Framework/App/Http.php(118): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http))
#19 /var/www/html/gitmagento2/lib/internal/Magento/Framework/App/Bootstrap.php(244): Magento\Framework\App\Http->launch()
#20 /var/www/html/gitmagento2/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#21 {main}";s:3:"url";s:54:"/gitmagento2/catalog/category/view/s/cell-phones/id/8/";s:11:"script_name";s:22:"/gitmagento2/index.php";}

**Comment by kokoc** [comment]
@shivkumarsingh7 Thank you for reporting the issue. Appropriate item is placed into internal backlog.
Internal reference: MAGETWO-33450

**Comment by vpelipenko** [comment]
@shivkumarsingh7, Internal ticket is fixed and will be available here with next weekly update.

**Comment by vpelipenko** [comment]
@shivkumarsingh7, fix for this issue is already available after 0.42.0-beta10. Please, check it and provide your feedback.

**Comment by shivkumarsingh7** [comment]
Thank you
