### ISSUE TITLE
Special price is not taken into account when sorting by price on product lists

### ISSUE THREAD

**Issue by TommyKolkman** [magento/magento2#8992]
I'm not absolutely sure it should work like this, but it seems like a weird thing to me. My clients are asking for this too. So, here it goes:

### Preconditions

Magento
```
| Name             | Magento                                                                       |
| Version          | 2.1.5                                                                         |
| Edition          | Community                                                                     |
```
DB
```
| model                  | mysql4                                                                                                                        |
| engine                 | innodb                                                                                                                        |
```
PHP
`PHP 7.0.14-2a`

### Steps to reproduce

1. Add products to a category
2. Add special price to some of the products
3. Sort by price on the frontend

### Expected result

1. Special price should be taken into account when sorting by price

### Actual result

1. Sorting is only done by original price

![result](https://cloud.githubusercontent.com/assets/837198/24258407/ef025d48-0fed-11e7-857f-24462d266e5e.png)

**Comment by TommyKolkman** [comment]
Please, at least acknowledge this. It's been 8 days!

**Comment by paales** [comment]
Related: https://github.com/magento/magento2/issues/6751

**Comment by staniag** [comment]
2.1.8 special price sorting works without problems. Be sure to set special price and not tier price.

**Comment by magento-engcom-team** [comment]
@TommyKolkman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by maderlock** [comment]
I can reproduce this in 2.1.9, so I wonder what is going on here? Does sorting not take into account special prices if set by catalog price rules maybe?

**Comment by maderlock** [comment]
I do need to confirm that this is true on the vanilla 2.0.9 as I am using a layered navigation module and I know they can interfere with ordering sometimes.
