### ISSUE TITLE
magento migrate:data fails if a table name contains a `.`

### ISSUE THREAD

**Issue by markbiek** [magento/magento2#8993]
At some point during the `bin/magento migrate:data` process, the script does a `SHOW CREATE TABLE <table-name>` on each table.

The script attempts to quote the table name in a way that fails if the table name contains a `.`.

For example, a table named `myco_documents_16.01` will generate the following SQL

```
SHOW CREATE TABLE `myco_documents_16`.`01`
```
which fails with a **Base table or view does not exist** PDO exception.

**Comment by scottsb** [comment]
@markbiek Magento will probably be closing this eventually, as this belongs as an issue in this repo:
https://github.com/magento/data-migration-tool

Just a heads up in case you want to submit there before they get to process this one.

**Comment by markbiek** [comment]
Thanks for the tip.

I've added an issue there instead: https://github.com/magento/data-migration-tool/issues/265
