### ISSUE TITLE
Css updates not display in frontend- located in module 

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#900]
Css updates not display in frontend- located in module 
[magento2]/app/code/Magento/[module-name]/view/frontend/web/css/[module.css]

also tried below solution 

trigger recompiling process from console under \dev\tools\Magento\Tools\View\
php -f deploy.php
Or enable developer mode in .htaccess
SetEnv MAGE_MODE "developer"

but no luck

**Comment by buskamuza** [comment]
Could you, please, provide an example?
I just tried on a custom CSS file and it works fine.
If there is some CSS file in a module, it doesn't mean that it will be used on the frontend, unless it's really included by a template or layout.

**Comment by shivkumarsingh7** [comment]
Hi,
Its is included on template (verified)

for example
.block-title strong {
    font-size: 18px;
    font-weight: 300;
}

and i updated it to 

.block-title strong {
    font-size: 20px;
    font-weight: 300;
}
If we change the name of css file than css changes display on frontend. Its look like cacheing issue but I have tried with flushing cache. and it should be display on frontend with new changes.

**Comment by buskamuza** [comment]
Got it.
If you're working with CSS/JS, you should enable `developer` mode from the beginning. Otherwise, you need to cleanup `pub/static` folder to remove published files.

If this is one-time change, just cleanup `pub/static` folder.

**Comment by shivkumarsingh7** [comment]
Thank you @buskamuza
