### ISSUE TITLE
Get MAGETWO-52856 into Magento 2.1.x

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#9007]
### Preconditions
1. Magento 2.1.x

### Steps to reproduce
1. log in as a customer
2. create 581 addresses
3. go to checkout

### Expected result
1. a seamless experience of the checkout (as it did in magento 1 with the same amount of addresses)

### Actual result
1. checkout is handing very long (over a couple of minutes) and in increases with the amount of addresses.

So please get MAGETWO-52856 into Magento 2.1.x
See: https://github.com/magento/magento2/commit/3495e603b5789ff50eb4e33d07b26820d7e759ff

This fix is a huge performance boost, otherwise a checkout lasts more than 2 minutes!

**Comment by veloraven** [comment]
@PascalBrouwers thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by korostii** [comment]
@veloraven, have you even read the report? Looks quite complete to me. 
Your response seems to be a case of bureaucracy in action. 

**Steps to reproduce:** log in as a customer, create 581 addresses, do a checkout.
**Expected result:** sane response time.
**Actual result:** hanging for more than 2 minutes.

Does the report meet your high standards now?

**Comment by PascalBrouwers** [comment]
@veloraven I have updated the issue according to the issue reporting guidelines.

**Comment by okorshenko** [comment]
Hi @PascalBrouwers 
the issue has been fixed and delivered to 2.1-develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82527
