### ISSUE TITLE
Newsletter Email is not sent out to subscribers

### ISSUE THREAD

**Issue by yogeshraghav-dev** [magento/magento2#9010]
**Preconditions**
1. Magento2.1.3

 **Steps to reproduce**
1. Set up the newsletter in queue on specific date from Newsletter template.

**Expected result**
1. Newsletter is suppose to sent out.

**Actual result**
1. Newsletter is not send out.

![mail](https://cloud.githubusercontent.com/assets/10353287/24319915/fd3c018a-114f-11e7-9d46-8d99fbca85f8.png)

**Comment by hitman3043** [comment]
any reply?

**Comment by yogeshraghav-dev** [comment]
any suggestions please?

**Comment by Ctucker9233** [comment]
@hitman3043 I'm in the same boat. Issue #8422

**Comment by yogeshraghav-dev** [comment]
kindly reply please

**Comment by josealgardataborges** [comment]
Just to check, you have the [magento2 cronjobs](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html) running right?

**Comment by yogeshraghav-dev** [comment]
well how to do that sir?i mean iam a newbie so dont know much about it

**Comment by josealgardataborges** [comment]
@hitman3043 You have to follow the oficial instructions on how to enable those cronjobs in the [link](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html) i also gave you in the previous post.

**Comment by Ctucker9233** [comment]
@josealgardataborges The documentation is very general. Is there a specific cron job that has to be enabled in order to send newsletters? What's the syntax in order to enable it via CLI?

**Comment by josealgardataborges** [comment]
read this section: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html


`crontab -u <Magento file system owner user name> -e`

```
* * * * * <path to php binary> <magento install dir>/bin/magento cron:run | grep -v "Ran jobs by schedule" >> <magento install dir>/var/log/magento.cron.log
* * * * * <path to php binary> <magento install dir>/update/cron.php >> <magento install dir>/var/log/update.cron.log
* * * * * <path to php binary> <magento install dir>/bin/magento setup:cron:run >> <magento install dir>/var/log/setup.cron.log
```

And you should be good to go.

**Comment by josealgardataborges** [comment]
@hitman3043 @Ctucker9233 try to run in SSH the following command:

` php bin/magento cron:run`

**Comment by Ctucker9233** [comment]
@josealgardataborges That did the trick! Strange, though, because I have never had to manually run that command before.

**Comment by josealgardataborges** [comment]
@Ctucker9233 and you should not need to, *if* you have your cronjobs correctly setup. It's their 'job' to do it for you :)

**Comment by Ctucker9233** [comment]
@josealgardataborges I have the following cron jobs: actual username is hidden
/usr/local/php56/bin/php-cli /home/username/public_html/bin/magento indexer:reindex
/usr/local/php56/bin/php-cli /home/username/public_html/bin/magento cron:run
/usr/local/php56/bin/php-cli /home/username/public_html/update/cron.php
/usr/local/php56/bin/php-cli /home/username/public_html/bin/magento setup:cron:run

Set to run every five mins. Perhaps one of these is gumming up the works somehow?

**Comment by yogeshraghav-dev** [comment]
i have tried doing it but still its not working.even if i set the queue for newsletter its not sending.status is showing "Not Send"....

**Comment by magento-engcom-team** [comment]
@hitman3043, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
