### ISSUE TITLE
Order email get the wrong (default) language 

### ISSUE THREAD

**Issue by JoostWan** [magento/magento2#9014]
### Preconditions

1. PHP 7.0
2. Magento 2.1.5

### Steps to reproduce
1. Clean Magento 2.1.5 shop with Adyen Payment module
2. Create a extra store with another language (Like Dutch)
3. Place a order on the dutch shop
4. Adyen uses a cron to send a payment conformation to Magento and runs the next code for sending the conformation e-mail: $this->_orderSender->send($this->_order) https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L667;
5. The customer get's the e-mail content in English (default store) and not in Dutch from the store that the customer used to place the order. 

In the log's the StoreID of the order is correct. The title was also in default language, we fixed this with https://github.com/magento/magento2/issues/8117#issuecomment-272242715

But the content of the e-mail is still in default language.

**Comment by rikterbeek** [comment]
Hi Magento,

Any updates about this issue how we can resolve this?

Regards,
Rik
Adyen

**Comment by lancergr** [comment]
@JoostWan this is resolved in #8413 (already merged to develop) but as I can see is included only for Magento >= 2.2.0

**Comment by magento-engcom-team** [comment]
@JoostWan, thank you for your report.
The fix for this issue is already available in the develop branch and upcoming 2.2.0 release. See https://github.com/magento/magento2/pull/8413.
