### ISSUE TITLE
Changed behaviour of before plugins?

### ISSUE THREAD

**Issue by fooman** [magento/magento2#9015]
### Preconditions
Magento 2.1.x

### Steps to reproduce

1. Create before plugin on Magento 2.1
2. Take a look at this commit  https://github.com/magento/magento2/commit/4a233d4ec18cb10931bff5078d8ade1a2a66c58e#diff-7fea50965bcc6aeb72cc4f333e0f9912R123
3. Notice that  
```
$beforeResult = $pluginInstance->$pluginMethod($this, ...array_values($arguments));
if ($beforeResult) {
    $arguments = $beforeResult;
}
```

changed to
```
$beforeResult = $pluginInstance->$pluginMethod($this, ...array_values($arguments));
if ($beforeResult !== null) {
    $arguments = (array)$beforeResult;
}
```

### Expected result

1. Behaviour remains the same

### Actual result

1. Result is cast to array

**Comment by magento-engcom-team** [comment]
@fooman, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Seems like it not break any backward compatibility. Look http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html. You can find here next lines : "You can use before methods to change the arguments of an observed method by returning a modified argument. If there are multiple arguments, the method should return an array of those arguments. Returning null will indicate that the arguments for the observed method should not be modified.".
So before plugin should return array, one argument or null. Now, one argument("some value") will be only converted to ["some value"].

**Comment by fooman** [comment]
Thanks for the comments.
