### ISSUE TITLE
Error while sending QUERY packet. Magento 2 (2.1.5)

### ISSUE THREAD

**Issue by VisheshDev** [magento/magento2#9021]
### I'm trying to install the Magento 2 (2.1.5) on web server with CLI. but its is giving error

> [Exception] Warning: Error while sending QUERY packet. PID=34 in vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

### I searched for the solution and all the solution is that increase the

> max_allowed_packet

### First max_allowed_packet was 33MB but now i increased it to 512MB. But it's still giving me same error with different PID.
CLI commands used to install Magento is

```
magento setup:install --base-url=http://www.example.com \
 --db-host=localhost --db-name=db_name --db-user=db_admin --db-password=db_admin_password \
--admin-firstname=User  --admin-lastname=Magento --admin-email=admin@demo.com \
 --admin-user=admin_site --admin-password=admin_password --language=en_US \
--currency=INR --timezone=Asia/Kolkata --cleanup-database \
--session-save=db  --use-rewrites=1
```

**Comment by veloraven** [comment]
@VisheshDev please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by paginasweb** [comment]
I am experiencing the same with magento 2.1.7, i did change max_allowed_packet from 16 to 512 and is still giving me the same error message, what else could it be?

**Comment by centerax** [comment]
same problem on Enterprise. Any ideas?

**Comment by magento-engcom-team** [comment]
@VisheshDev  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
