### ISSUE TITLE
magent setup:di:compile throwing the error ar 4th step

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#9026]
Hi,
When I am running "php -dmemory_limit=6G bin/magento setup:di:compile" on existing magento project then its throwing the error.

![screen shot 2017-03-27 at 6 02 17 pm](https://cloud.githubusercontent.com/assets/13519944/24356673/903d20b2-1318-11e7-9bd6-1bc441c91711.png)

Current magento version is 2.0.7.

**Comment by southerncomputer** [comment]
rm -rf var/di var/generation
vendor/bin/composer dumpautoload -o
php -dmemory_limit=6G bin/magento setup:di:compile
php -dmemory_limit=6G bin/magento setup:static-content:deploy

That or you munched up a .xml file which will do the same thing!

find . -mtime -3 

Finds all files changed in the last 3 days, if you have to go over changed files/xml files!

**Comment by veloraven** [comment]
@baltechies thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by magento-engcom-team** [comment]
Hi @baltechies unfortunately, we can not reproduce the issue on our side.  We are closing this issue for now. If you'd like to update it, please reopen the issue.
