### ISSUE TITLE
New Store Design Change (date format error)

### ISSUE THREAD

**Issue by josealgardataborges** [magento/magento2#9037]
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Create a New Store Design Change
2. Choose the starting and ending dates, using the calendar popup interface
3. SAVE

### Expected result

1. The form being saved

### Actual result

1. The form errors out with invalid date format.
form -> http://prntscr.com/epii6r
result -> http://prntscr.com/epiie5

**Comment by josealgardataborges** [comment]
This error also appears on every date input field that does not have time in it, ie only the date.

**Comment by VasylShvorak** [comment]
Hello @josealgardataborges . Unfortunately I was not able to reproduce this issue. It is reproducible only if I enter date manually without using Calendar popup interface. Please describe all steps you have done in more detailed way.

**Comment by josealgardataborges** [comment]
As mentioned in the error report, I go to CONTENT / DESIGN CHANGE and when i choose the dates from the calendar popup interface (ie not manually typed) and save the error shows on screen.

I recorded a video of all the steps to reproduce the error: https://drive.google.com/file/d/0B_enga4Hh7bmM2VBbXZyNExpN00/view

im using Magento ver. 2.1.6

**Comment by VasylShvorak** [comment]
@josealgardataborges Your video was helpfull. Thanks for reporting this issue. I've linked this GitHub issue to internal ticket MAGETWO-70340.

**Comment by magento-engcom-team** [comment]
@josealgardataborges, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
