### ISSUE TITLE
Installation Incomplete with XDebug enabled

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#904]
With XDebug enabled /setup/index.php/install route in Google Developer Tools throws an error:
"Maximum function nesting level of '100' reached, aborting!"

Which cause Installation error at 93% in my case.
I resolved this issue using xdebug.max_nesting_level = 200 in my php.ini but it may cause problems in the future with some users. 

using ini_set() function may resolve the problem but it will not work for a users who aren't allowed to override php.ini in PHP code.

Any ideas how to fix it permanently ?

**Comment by orlangur** [comment]
In fact, `xdebug.max_nesting_level = 200` is a system requirement when XDebug enabled.

So, some check similar to, for example, MySQL version check could be implemented to enforce this requirement. Override ini value silently does not seem a viable solution to me, better just describe ways to set the value in hint.

**Comment by snky1987** [comment]
@orlangur I agree. It is something easy to forget for a developer (and certainly hard to find and fix for a newbie user of Magento with just minimum knowledge of PHP). There may be some kind of misc. check to find out this nesting_level issue and also permission level in TEMP directory.

I had this issue few times during installation process tests that Windows 7 for some reason blocked unlink() of install.log in TEMP dir. (permission denied) but it's hard to reproduce this error (I just had it 2 times during 20 installation processes).

So yes. It may be useful to have some kind of Miscellaneous tests as well.

**Comment by monkeysee** [comment]
Reported internal issue: MAGETWO-33027

**Comment by vpelipenko** [comment]
@snky1987, fix is available from 0.74.0-beta9. Please, let us know if it will occur again.
