### ISSUE TITLE
Error when place virtual gift card product using checkout Paypal Express

### ISSUE THREAD

**Issue by nguyetnguyen** [magento/magento2#9042]
### Steps to reproduce
1. Add a virtual gift card product to shopping card
2. Go to checkout page, on step Payment and Review, select payment method "Paypal Express"
3. After redirect to Paypal page, login and Pay Now.

### Expected result
4. It should go to checkout success page without any error. 

### Actual result

4. It return to checkout paypal review with error "Can't not place order." while order is create successful and Paypal marked Invoice as "Complete"

When debuging, I found that after return from Paypal Express, It call updateItem() in cart before submited quote. On function _prepareProduct(), $buyRequest is not correct data. It is currently like this:
array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'getPalDetails' => 
  array (
    'METHOD' => 'getPalDetails',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_Cart_Enterprise',
  ),
  'response' => 
  array (
    'PAL' => 'HDGPKTQJCZ2J6',
    'LOCALE' => 'en_AU',
    'TIMESTAMP' => '2017-03-28T10:38:52Z',
    'CORRELATIONID' => '15c8038b4edf6',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '25237094',
  ),
)
$buyRequest should be included gift_card_amount, gift_card_sender, gift_card_email_sender, ...

**Comment by dyushkin** [comment]
Hi, @nguyetnguyen! Thank you for reporting. I have created internal ticket MAGETWO-66895 to fix this issue.

**Comment by orlangur** [comment]
@dyushkin, EE-specific issues can now be directly reported in GitHub?

**Comment by dyushkin** [comment]
Hi, @orlangur. PayPal is community edition module, this issue affects checkout with the virtual product.

**Comment by orlangur** [comment]
Yeah, but `GiftCard` not :) So, without changes this scenario is not reproducible in Community Edition.

**Comment by alena-marchenko** [comment]
Hi @nguyetnguyen 

Fix for MAGETWO-66895 is merged to develop branch, closing the issue.
Thank you.
