### ISSUE TITLE
Scope - Not working as expected on so many many levels

### ISSUE THREAD

**Issue by johnny-longneck** [magento/magento2#9045]
Magento 2.1.4 with multiple websites, price scope is set to website, different base currency. 
It is so much pain right now. 

### Preconditions

1. Magento 2.1.4, 
2. PHP 7

### Steps to reproduce

1. Install Magento 2.1.4 
2. Setup multiple websites, price scope website, one website is based in USA (USD only), one in Germany (EURO), configure taxes
3. 

### Expected result

1. Price Scope "Website" working on website scope
2. Website taking base currency from website scope not default config
3. Config being inherited from website, store, store view 

### Actual result

1. Base Currency per website is not respected, it takes the currency from default config and adds the currency rate instead of using only the entered value
2. Scope is said on website level but needs to be imported on store view level when running the product import
3. Almost any config is not being inherited: Changed something on Website Scope, needed extra Store View Scope adjustment to take effect.
4. Could not get tax rules for both websites running, it seems it is not setting the correct customer group at all. Ended up setting for both websites customer groups back to General and at least taxes are applied correctly.
5. Setting Customer Group wholesale automatically with correct VAT ID does not seem to work, even configured under Configuration > Customers
6. One website is suppossed to hide the VAT ID field in the checkout, it does not, even configured. I guess it takes the default config here as well.

**Comment by johnny-longneck** [comment]
Another one: 
Changed default sort order in category in default config, it was not applied to all children using "default" settings. Had to change it to all categories to get it work.

**Comment by magento-engcom-team** [comment]
@johnny-longneck, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
