### ISSUE TITLE
SOAP API: inventory qty can't be updated

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#9047]
I'm trying to update inventory iyrm with help of 
`https://www.qwerty.com/soap/default?services=catalogInventoryStockRegistryV1 
catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest [ xmlns=https://www... ]`
but QTY doesn't change

### Preconditions
1. Magento ver. 2.0.8
2. SOAP API

### Steps to reproduce

1. `<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest xmlns="https://www.qwerty.com/soap/default?services=catalogInventoryStockRegistryV1"><productSku xmlns="">xxxx</productSku><stockItem xmlns=""><productId>45223</productId><qty>2</qty><isInStock>true</isInStock><isQtyDecimal>false</isQtyDecimal><showDefaultNotificationMessage>false</showDefaultNotificationMessage><useConfigMinQty>true</useConfigMinQty><minQty>0</minQty><useConfigMinSaleQty>1</useConfigMinSaleQty><minSaleQty>1</minSaleQty><useConfigMaxSaleQty>true</useConfigMaxSaleQty><maxSaleQty>10000</maxSaleQty><useConfigBackorders>true</useConfigBackorders><backorders>0</backorders><useConfigNotifyStockQty>true</useConfigNotifyStockQty><notifyStockQty>1</notifyStockQty><useConfigQtyIncrements>true</useConfigQtyIncrements><qtyIncrements>0</qtyIncrements><useConfigEnableQtyInc>false</useConfigEnableQtyInc><enableQtyIncrements>false</enableQtyIncrements><useConfigManageStock>true</useConfigManageStock><manageStock>true</manageStock><isDecimalDivided>false</isDecimalDivided><stockStatusChangedAuto>1</stockStatusChangedAuto></stockItem></catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest></s:Body></s:Envelope>`
2. `<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://www.qwertyoes.com/soap/default?services=catalogInventoryStockRegistryV1"><SOAP-ENV:Body><ns1:catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse><result>64590</result></ns1:catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>`

3. 

### Expected result
1. QTY updated
2. Correct answer

### Actual result

1. COrrect answer, but qty was not changed

**Comment by ericahoekerd** [comment]
This is working ok with SOAP since version 2.1.3, maybe an idea to upgrade your Magento version? And then test again?

**Comment by springerin** [comment]
Having the same issue on 2.1.7. Can be related to the store?

**Comment by magento-engcom-team** [comment]
@MaximKitsenko, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
