### ISSUE TITLE
[Product page - Additional attributes block] Boolean attributes are not rendered 

### ISSUE THREAD

**Issue by shavounet** [magento/magento2#9048]
### Preconditions
1. Magento 2.1.3 CE
2. PHP 7

### Steps to reproduce
1. Create a new attribute, with type boolean ("Yes/No"), add it to an attribute set and set its value on some products
2. Set the attribute option "Visible on Catalog Pages on Storefront" to Yes

### Expected result
1. On the product page, the attribute should be displayed in the additional informations block with a "Yes" or "No" value

### Actual result
1. On the product page, the attribute is not displayed in the additional informations block
2. Note that it does also not work with the unset value for any other attribute type (it should display "N/A")

### Origin of the bug

In `\Magento\Catalog\Block\Product\View\Attributes::getAdditionalData`, the condition `is_string($value) && strlen($value)` enters in conflict with the type of `$value` which can be a `\Magento\Framework\Phrase` if the product is a boolean or if the value is unset. This condition should take this into account.

**Comment by veloraven** [comment]
@shavounet thank you for your report.
However I'm closing this issue as it is a duplicate for #6634.
We already have internal ticket for it: MAGETWO-59267
