### ISSUE TITLE
Adding New Products Issue, Cant Change "Show/Hide Editor" Only in HTML Format

### ISSUE THREAD

**Issue by Alexgator32** [magento/magento2#9049]
### Preconditions

1. I am trying to add new products to Magneto 2.1.3 and up til last week I could open (2) tabs and both be on the back end of Magento. I would have a previously posted product up on one tab and on the other I would have a New Simple Product. I use this because it would be easy for me to copy of Specs and Tables from one to the other. Up till last week I had no problem doing this and posted 50+ products. As of yesterday when I tried to do this same thing I am running into the "show/hide Editor" not working and I am only seeing everything displayed in a coded format.

What can I do?

Here is a screen shot of what it looks like:

![image](https://cloud.githubusercontent.com/assets/26768495/24456423/f65ec230-1460-11e7-9e8d-be5f748316ac.png)

2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by mombrea** [comment]
This issue persists in 2.1.5, it's intermittent though. If you hold down the shift key and refresh the page, it will usually load the editor the next time.
