### ISSUE TITLE
Magento fails to create new order, but customer still charged in authorize.net

### ISSUE THREAD

**Issue by NMills12** [magento/magento2#9051]
### Preconditions
We have found several cases where customers are being charged for multiple transactions with the same invoice numbers. However, only one of the transactions actually shows in Magento. The other transactions appear to be duplicates that Magento did not process, but authorize.net still created successful transactions and processed payment.
 
It seems that Magento is trying to reuse existing order numbers so this causes the order not to be processed in Magento, but it still goes through in authorize.net.
 
This does not happen with every order and it occurs with both customers who check out as guests and customers who are logged in registered users. The problem has happened with shoppers using various browsers so different web browsers do not seem to be the issue.

We are currently using version 2.0.7 community edition. 

### Steps to reproduce

1. customer shops site and adds item to cart
2. customer enters all checkout details 
3. customer clicks on button to place order

### Expected result
Customer should see the checkout success page with an order number confirming the order was successfully processed

### Actual result
Sometimes the customer gets the order success page with a confirmation number. 

In the problem cases, the confirmation page never loads and the customer is never given an order number. This results in the customer repeatedly trying to submit the order to no avail. The order never shows up in the sales order list in Magento, but authorize.net shows the same order number was assigned to multiple transactions and each went through as a successful charge in authorize.net.

**Comment by YevSent** [comment]
Hi, @NMills12, please, enable debug mode for Authorize.net payment and provide transaction details log, also is it possible attach response from `transact.dll` request (you can find in the browser console log).

**Comment by NMills12** [comment]
[transaction_logs.zip](https://github.com/magento/magento2/files/885972/transaction_logs.zip)
[Morley-Sanders authorize.net transaction examples.xlsx](https://github.com/magento/magento2/files/885973/Morley-Sanders.authorize.net.transaction.examples.xlsx)

Because we are using third party extension for Authorize .Net, we only have the log generated by extension. Those logs are attached in the zipped file. I have also attached transaction details from our authorize.net account showing 4 specific examples where this issue occurred. Thank you.

**Comment by YevSent** [comment]
Please, provide link to your 3d party extension for Authorize.net.

**Comment by NMills12** [comment]
Here is the link.
https://store.paradoxlabs.com/magento2-authorize-net-cim-payment-module.html

**Comment by YevSent** [comment]
I've tested your case on different Magento versions like 2.0.x, 2.1.x and develop branch, and all works as expected. I'll investigate this issue on our environment, but seems this issue in 3d party extension.

I have not an access to source code of this extension but seems it does not use Magento Authorize.net module implementation, also we do not provide support for 3d party extensions and you need contact with Paradox Labs support.

Could you try to reproduce this issue with Magento2 built-in Authorize.net module?

**Comment by NMills12** [comment]
We have also tried to reproduce the issue, but have been unable to do so. We see it is happening, but our team has not been able to determine why. We use the Paradox Labs authorize.net CIM extension to allow for shipping to multiple addresses, which the built-in authorize.net does not support. 

We will reach out to Paradox Labs now.

**Comment by NMills12** [comment]
Paradox Labs believes in the cases where we have a problem at some point between the order creation and sending of the order confirmation email something is causing an error and preventing the order from completing correctly. So when the customer tries to place the order again, the SQL errors occur because that order already exists in the database. 

Paradox Labs also reviewed this issue and said since their extension seems to be working correctly when they try replicating the issue, they do not believe it to be the cause of the errors. 

The only other suggestion Paradox Labs could offer was for us to update to the latest version of the Authorize.net CIM extension. We have 3.0.3.20160722. installed, but the latest version available is 3.1.2.

**Comment by magento-engcom-team** [comment]
@NMills12, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by brnquester** [comment]
@NMills12 did you find a solution for this? We are having big problems because the exact same problem. We would appreciate if you found any solution. Thanks

**Comment by chirag-taraviya** [comment]
@NMills12 @bruno-canada Did you find a solution? we have same problem with Magento 2.3.5-p1

**Comment by alex-ugodnikov** [comment]
same issue here Magento 2.3.3
@chirag-taraviya @NMills12 @bruno-canada did you find the solution?

**Comment by FarzamDS** [comment]
Hello. Did anyone find a solution for this?
