### ISSUE TITLE
Suggestion: Change "adjustment refund" and "adjustment fee"

### ISSUE THREAD

**Issue by calvintwr** [magento/magento2#9053]
For credit memo, the terms "adjustment refund" and "adjustment fee" are confusing. They are neither proper accounting terms nor do they make sense. And the impetus to get terms right is because the actions are irreversible and it is easy to make mistakes if terms don't make sense.

Let me state my case.

"Adjustment Refund"
Any figure entered here is added to the refund total. There are hardly any case which you need to refund a customer more than what he paid for. And the term isn't intuitive at all to tell you what it does is to add the amount to the refund total. Further, to do a partial refund, it makes sense that you are finding a field that says "adjustment to refund", and the closest you have is "Adjustment Refund", which sounds like what you want to do here except it doesn't -- it adds the amount to the refund total.

"Adjustment Fee"
Any figure entered here is subtracted to the refund total. This is actually how you would do a partial refund. However, very few people will understand what is the meaning of an adjustment fee. A partial refund is a partial refund. You would say "I got a partial refund". You wont say "I got a full refund but charged an adjustment fee" -- which is exactly what the box really mean. Because nobody will understand the latter statement, nobody will understand this term "adjustment fee".

The solution is simple.

Provide a box that says "refund" and populate it with the default full product price. Then the admin can choose to refund less than the product price or more than the product price (which I state is rare but yes we may want to allow that to happen).

Then finally, the last line should be "Total amount to refund" instead of "subtotal". And this should be javascript binded to change according to the amounts entered.

Exactly because the process is 1) Very important because you are dealing with money, 2) Irreversible and 3) Error prone at present, therefore it is important to change it and improve with the above recommended features.

### Preconditions
Magento version 2.1.8

### Steps to reproduce
Attempt a refund

### Expected result
Refunding makes sense.

### Actual result
Refunding doesn't make sense.

**Comment by magento-engcom-team** [comment]
@calvintwr thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by calvintwr** [comment]
Preconditions: Magento version 2.1.8

Steps to reproduce

Attempt a refund


Expected result

Refunding makes sense.


 Actual result

Refunding doesn't make sense.

**Comment by magento-engcom-team** [comment]
@calvintwr thank you for the update. we will try to reproduce the issue by the provided information

**Comment by magento-engcom-team** [comment]
@calvintwr, thank you for your report.
We've created internal ticket(s) MAGETWO-80021 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @calvintwr. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/27
