### ISSUE TITLE
Static test runner fails on custom ACL resource names 

### ISSUE THREAD

**Issue by cykirsch** [magento/magento2#9054]
### Preconditions

1. Magento 2.1

### Steps to reproduce

1. Create a controller class and use any vendor name other than Magento, and include an override of the admin resource constant.
```
<?php

namespace Vendor\Module\Controller\Adminhtml;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;

class Foo extends Action
{
    const ADMIN_RESOURCE = 'Vendor_Module::foo_bar';

    public function execute()
    {
        // do anything
    }
}
```

2. Run the static tests: `magento dev:tests:run static`

### Expected result

1. Tests should pass.

### Actual result

1. Tests fail, and one of the errors is
```
Data set: /Users/me/Projects/m2.com/www/app/code/Vendor/Module/Controller/Adminhtml/Foo.php
Incorrect namespace usage(s) found in file /Users/me/Projects/m2.com/www/app/code/Vendor/Module/Controller/Adminhtml/Foo.php:
Vendor_Module
/Users/me/Projects/m2.com/www/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:594
/Users/me/Projects/m2.com/www/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:367
/Users/me/Projects/m2.com/www/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/Users/me/Projects/m2.com/www/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:369
```

### Reason
In `Magento\Test\Integrity\ClassesTest::removeSpecialCases`, it filters out those matching `Magento_*` but no other vendors. So anyone other than Magento creating a custom ACL resource and using it in a PHP file will get these errors when running tests.

**Comment by orlangur** [comment]
I'm not sure this is a real issue as I'm not sure all of the tests are supposed to work for any vendor.

Normally no code should be added to `/app/code` I believe (please point me out to some documentation if I'm wrong), all custom modules should reside in `vendor`. `/app/code/Magento` is placed this way just for the sake of simplicity in this monolithic repo.

Should be not too hard to analyze only enabled/existing modules of any modules though instead of sticking to hardcoded ultimate vendor name.

**Comment by cykirsch** [comment]
For us, the decision to add custom modules to app/code directly was based
mostly on source code management. Alan Kent even suggests to not touch
vendor, and that is one of the reasons.
https://community.magento.com/t5/Just-Ask-Alan/Why-two-locations-to-develop-themes/m-p/30147
(look for his comment 2-24 9:05 am, sorry I'm on mobile right now)

Some will say to develop under app/code directly and then internally
release the package so that it can load via composer and go in vendor. But
that means the tests won't work until you release them, so what's the point?

**Comment by orlangur** [comment]
Thanks for the link! So, `/app/code` is the new `/app/code/local` officially thus all possible tests needs to be adopted to give maximum benefit for custom development.

**Comment by magento-engcom-team** [comment]
@cykirsch, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
