### ISSUE TITLE
bin/magento - missing namespace on last reference to Cli class, line 31

### ISSUE THREAD

**Issue by andrewsladen** [magento/magento2#9058]
On line 31 of bin/magento (looking at Magento 2.1.5), the **Cli** class is referenced without namespace, and there is no **use** statement for the class further up.

Line 31:
`exit(Cli::RETURN_FAILURE);`

### Preconditions
1. CentOS release 6.8 (Final)
2. kernel 2.6.32-642.15.1.el6.x86_64
3. Apache 2.4.6-5.el6
4. PHP 7.0.17
5. Percona server 5.7.17-12.1.el6
6. Magento CE 2.1.5
7. Magento in MultiSite configuration - several Websites, each with Single Store and StoreView

### Steps to reproduce
1. Run a `bin/magento` command which causes an Exception to be thrown

### Expected result

1. the only error output will relate to the Exception that was thrown
2. exit code is **1** (as per line 31, `exit(Cli::RETURN_FAILURE)` )

### Actual result
1. console output will give an extra error (apart from the Exception that was thrown), saying **Fatal error: Uncaught Error: Class 'Cli' not found**.
2. exit code from the process will be **255**

**Comment by korostii** [comment]
Hi. FYI If you're able to submit a pull request along, that will likely speed up the process of pushing that fix to a release.

**Comment by andrewsladen** [comment]
So true, @korostii , I'll do that next time.  Didn't even think.

And thanks @adragus-inviqa for jumping on the pull request - beat me to it :+1:

**Comment by magento-engcom-team** [comment]
@andrewsladen, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
