### ISSUE TITLE
Saving any "Attribute Set" after initial creation fails - 403 Forbidden

### ISSUE THREAD

**Issue by Brandame** [magento/magento2#9063]
Good afternoon, it's my first time here please be gentle! -  I can't figure out how to work around this issue, so I've come to you in the hopes that you may know where things have gone wrong! I suspect a full wipe of the current attributes/attribute sets, and then an import of the vanilla Magento attributes/attribute sets might fix whatever bug has found its way in, what do you think?

Thanks for the help in advance,

### Preconditions
This store is not currently live and only has a few test products in it.
Nexcess Magento Hosting
Magento CE 2.1.5
Apache 2.2.31
PHP 7.0.15
MySQL Percona Server 5.6.35-80.0
Chrome Browser

### Steps to reproduce
After so much configuration up to this point, I can't describe how to reproduce the issue from a blank Magento install, sorry. I have created a number of attributes of my own that I want to place in a new attribute set, and I've possibly modified some of the defaults (I have modified color, for example). I may have even deleted a default attribute, though I doubt that - but I've not got a list of the defaults handy to compare. For me currently, all I have to do to encounter this error is:

1. Log in to admin panel
2. Go to Stores > Attributes > Attribute Set
3. "Add Attribute Set"
4. Name "Test1" based on "Default" (or indeed any attribute set), click "Save".
5. "You saved the attribute set." - all good so far.
6. Attempt to modify anything in the attribute set, e.g. change the name to "Test2".
7. Click "Save".
8. Magento pops up a loading "Please wait..." for about a quarter of a second, then that disappears leaving you on the same page you were on, nothing changed.

### Actual Result
9. Browser console output shows the following error (domain URL unnecessary):

```
legacy-build.min.js:1 POST http://domain.domain/admin/catalog/product_set/save/id/19/key/68ff563b166629c59c70be963787f4d213023cea333cef74129ab6d563c532ba/?isAjax=true 403 (Forbidden)
request @ legacy-build.min.js:1
initialize @ legacy-build.min.js:8
(anonymous) @ legacy-build.min.js:1
g @ legacy-build.min.js:1
request @ ext-tree.js:13
save @ (index):620
onclick @ (index):258
```

### Expected Result
no errors on console output

**Comment by Andrii-Deineha** [comment]
HI @Brandame, Thanks for reporting this issue. Unfortunately, I could not reproduce the issue as you described it. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by giacmir** [comment]
Had this same issue today on an AWS hosted Magento 2.4.2. Turned out it was a WAF rule blocking the request.

The rule was called `sqli-body-001`. We reported the issue to the rule provider.
