### ISSUE TITLE
sort by SKU not working properly if category set Anchor to Yes

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#9067]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0.14 & MySQL 5.7.16

### Steps to reproduce

1.	If category attribute Anchor set to Yes then in frontend category page it display the products of its own and it’s subcategories also.
2.	If you sort any category products by SKU, only that category products position will be changing not subcategory products position.
3.	So, first parent categories products are displaying in the order by SKU, then subcategory products are displaying. 
4.	We can resolve this issue by displaying products by excluding display of sub category products, to make it done we have to set category attribute Anchor to No.
5.	But to layered navigation in category page, categories must Anchor set to Yes .
6.	One of our client asking for both layered navigation and sort by SKU at a time. How we can overcome this situation?

**Comment by piatrouski** [comment]
Same issue :-(

**Comment by piatrouski** [comment]
Same issue!

**Comment by Trython** [comment]
Confirming, I am having the very same situation with 'position' attribute in EE ver. 2.1.3.
Steps to reproduce are the same as per @i95devdivya .

**Comment by koenner01** [comment]
probably a bit related https://github.com/magento/magento2/issues/9002

**Comment by magento-engcom-team** [comment]
@i95devdivya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
