### ISSUE TITLE
Missing required argument $readers of Magento\Framework\MessageQueue\Config\CompositeReader.

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#9071]
### Preconditions

1. Magento2.1.2 EE
2. php7.0.12
3.mysql5.7

### Steps to reproduce

1. in project folder.excuting php bin/magento setup:upgrade

### Expected result

```
 Missing required argument $readers of Magento\Framework\MessageQueue\Config\CompositeReader.
```

What can I do?

**Comment by YevSent** [comment]
The public Github is only for CE version of Magento. To solve your problem, please, create a ticket via [EE support](https://magento.com/support/enterprise-edition), thanks, for reporting.

**Comment by michaeldyl520** [comment]
I sove the problem.Now share for others.
In your project,open vendor/magento/framework/App/Arguments/FileResolver/Primary.php
at line 32,change:
```php
$this->configDirectory = $filesystem->getDirectoryRead(DirectoryList::APP);
```
to
```php
$this->configDirectory = $filesystem->getDirectoryRead(DirectoryList::CONFIG);
```

**Comment by allanpaiste** [comment]
You might encounter this if something went wrong with the installation (you had to re-trigger composer install mid-way through or something) which means that modules like magento2-base, that do a lot of file-mapping might be ignored (if they were already installed), which will mean that certain di.xml's might be missing from the root level initial app configuration.

If you encounter this error, you can fool the composer's installed.json to think that the -base modules (EE has it's own extra module) are not yet installed and trigger **composer install** again.

You can use this in the project root to trigger the re-installation of the packages that map files:

```shell
# Make composer think that the magento2-base module is not installed
sed -i.bak 's|\s"name":\s"magento/magento2-\(.*\)",| "name": "__magento/magento2-\1",|g' vendor/composer/installed.json;rm vendor/composer/installed.json.bak

# Reinstalling with verbosity enabled as base module file mapper fill stop as 
# soon as it encounters a conflict of some file already existing in the file path 
# destination (a'la project has LICENSE.txt).
composer install -vvv
```
Note that you might find this handy also if you encounter the app complaining about missing bootstrap.php

Another thing: this might not actually fix the issue as magento2-base file-mapper will stop as soon as it hits a conflict of some file existing in the project that it is trying to map over (you get more details on this when you re-install magento2-base and run install with -vvv)

**Comment by roman-snitko** [comment]
Thanks @allanpaiste, you are the best!
