### ISSUE TITLE
js-translation.json generation incomplete

### ISSUE THREAD

**Issue by AlexandreKhayrullin** [magento/magento2#9073]
### Preconditions
The Magento used is the "develop" branch.
PHP: PHP 7.0.10-1+deb.sury.org~xenial+1

### Steps to reproduce
1. Install a locale pack on Magento (in this case, the locale is es_ES)
2. Set Magento in production mode.
3. Display a UiComponent on frontend using the installed locale

### Expected result
1. The texts on the UiComponent are correctly translated

### Actual result
1. The texts remain in English (or, rather, use the translation keys)

It seems that the generation of js-translation.json is inconsistent between developer and production modes.
In production mode, the JSON either contains very few values (see js-translation.production.json in the attached ZIP file) or just an empty array. In developer mode, the JSON contains a lot more strings (see js-translation.developer.json in the attached ZIP file) , enough to make the UiComponents translatable.

[js-translation.zip](https://github.com/magento/magento2/files/885270/js-translation.zip)

**Comment by Khaleel** [comment]
I have the same issue with ar-json - not always Arabic files are generated in the JSON.

We expect that updating the CSV file should also update the Knockout JS files and Magento translation but it does not - this include local storage translation API

**Comment by ghost** [comment]
Have the same issue with a clean Magento 2 install with a valid language pack. It's missing a lot of translations.

**Comment by marcosdsdba** [comment]
I've tested and problem persists also in Version 2.1.6

I found the problem mostly in Checkout

**Comment by PascalBrouwers** [comment]
Same problem here. I used the workaround explained here: https://github.com/magento/magento2/issues/2056#issuecomment-181769248

**Comment by Tristan-N** [comment]
Also having trouble with this situation. Especially with the "Place order now" button. Can't get it translated. Not using CSV, not using complete language packs and inline translation doesn't work either.

**Comment by PascalBrouwers** [comment]
I just had it in developer mode too. This happens so often now that I remove the js-translation.json and run setup:static-content:deploy for my local language every time a translation doesn't work.

**Comment by ghost** [comment]
We have created a work-around with a custom script which converts all `.csv` files to `js-translation.json` files and then manually rewrite requests to `js-translation.json` in our web-server to our custom files and it works everytime.

**Comment by Tristan-N** [comment]
@PascalBrouwers Thank you for the information, but that didn't work for me either. It's both in dev mode and in prod mode. I am wondering; does this issue occur in the checkout too? For me it's only in the checkout. Do you use a custom OneStepCheckout by for example Hungersoft or Magestore?

**Comment by PascalBrouwers** [comment]
We do have Magestore OSC, but it doesn't matter where the translation is when the entire js-translation.json file is empty :)

**Comment by Tristan-N** [comment]
Ah, i found out that the translations in our Magestore OSC broke because of $t('string') weren't the same as the data-bind in the span. I solved it by matching the data-binds (see screenshot). Maybe it might help you too. 
![solution](https://user-images.githubusercontent.com/19165453/27436598-0f807208-5760-11e7-8d5f-bba4a9c08fab.png)

**Comment by shanavas786** [comment]
Same issue here, `$t` translations work fine in developer mode, but fails in production mode

**Comment by Khaleel** [comment]
@cjohansson please can you share this solution of making a custom json file as I was considering doing the same. I would really appreciate it - is it a module or snippet that you can opensource?

**Comment by shanavas786** [comment]
```
rm pub/static/<area>/<vendor>/<theme>/<lang>/js-translation.json
setup:static-content:deploy <lang> --theme=<vendor>/<theme>
```
generated proper `js-translation.json` for `<lang>`, and translations work fine.

**Comment by magento-engcom-team** [comment]
@AlexandreKhayrullin, thank you for your report.
We've created internal ticket(s) MAGETWO-84070 to track progress on the issue.

**Comment by Vinai** [comment]
In 2.2.5 the js-translation.json file isn't generated at all any more when running `setup:static-content:deploy`.

To reproduce:
* Install Magento 2.2.5 with sample data
* Run `bin/magento deploy:mode:set production`
* Load homepage, watch the console, and see
  `/static/version1530613742/frontend/Magento/luma/en_US/js-translation.json 404 (Not Found)`
* Run `bin/magento setup:static-contend:deploy`
* Reload again, still the same issue

Seems like JavaScript translation is getting more broken rather than more fixed.

**Comment by henk-hypershop** [comment]
Any update on this issue?

**Comment by LiamKarlMitchell** [comment]
A problem in 2.3 it seems.

**Comment by tuyennn** [comment]
I'm working on a Persian language project and have same issue experience.
Magento 2.2.7 #10860

**Comment by engcom-Bravo** [comment]
Hello @AlexandreKhayrullin 
Unfortunately, I cannot reproduce this issue by steps you described on 2.4-develop
Please feel free to comment, reopen or create a new ticket according to the Issue reporting guidelines
if you are still facing this issue on the latest 2.4-develop branch. Thank you for collaboration.
