### ISSUE TITLE
Does not translate "Track All Shipments" in My Account, view order

### ISSUE THREAD

**Issue by tagesjump** [magento/magento2#9078]
### Preconditions

Does not translate "Track All Shipments" in My Account, view order

### Steps to reproduce

1. create order as client
2. create shipment and add track number
3. go to the my account
4. open order view and chose  tab Order Shipments

### Expected result

1. Translated phrase "Track All Shipments"

### 	Reason: No call to the translation function

1. module-shipping/view/frontend/layout/sales_order_shipment.xml
```
 <block class="Magento\Shipping\Block\Tracking\Link" name="track-all-link" template="tracking/link.phtml">
     <arguments>
           <argument name="label" xsi:type="string">Track All Shipments</argument>
      </arguments>
</block>
```
2. module-shipping/view/frontend/templates/tracking/link.phtml
```
<?php /** @var $block \Magento\Shipping\Block\Tracking\Link */ ?>
<?php $order = $block->getOrder() ?>
<a href="#" class="action track" title="<?php /* @escapeNotVerified */ echo $block->getLabel() ?>"
   data-mage-init='{"popupWindow": {"windowURL":"<?php /* @escapeNotVerified */ echo $block->getWindowUrl($order) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'>
    <span><?php /* @escapeNotVerified */ echo $block->getLabel()?></span>
</a>

```

**Comment by mrkhoa99** [comment]
@tagesjump you can prefer to this pull request: https://github.com/magento/magento2/pull/9095

**Comment by okorshenko** [comment]
@tagesjump thank you for reporting the issue!
@mrkhoa99 thank you for fixing the issue!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67053
