### ISSUE TITLE
"Could not create acl object: Role '100' not found"

### ISSUE THREAD

**Issue by tsuleehyudin** [magento/magento2#9079]
I'm Using magento 2 enterprise version 2.0.9.

I create a new user, role as admin (user_id 2). then i inactive user old user admin (user id 1). but after i inactivate user id 1. i cannot login anymore. the site show this error. please help.

`a:4:{i:0;s:49:"Could not create acl object: Role '100' not found";i:1;s:6556:"#0 --DIRTOSITE--/shared/var/generation/Magento/Framework/Acl/Builder/Proxy.php(95): Magento\Framework\Acl\Builder->getAcl()
#1 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/Model/Auth/Session.php(236): Magento\Framework\Acl\Builder\Proxy->getAcl()
#2 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/Model/Auth.php(156): Magento\Backend\Model\Auth\Session->processLogin()
#3 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(205): Magento\Backend\Model\Auth->login('loginerror', 'passerror')
#4 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(157): Magento\Backend\App\Action\Plugin\Authentication->_performLogin(Object(Magento\Framework\App\Request\Http))
#5 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(125): Magento\Backend\App\Action\Plugin\Authentication->_processNotLoggedInUser(Object(Magento\Framework\App\Request\Http))
#6 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#8 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'log')
#9 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 [internal function]: Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#12 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'designLoader')
#13 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#16 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#17 --DIRTOSITE--/releases/MYSITE/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Interceptor.php(142): call_user_func_array(Array, Array)
#20 --DIRTOSITE--/shared/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#21 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#24 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 --DIRTOSITE--/releases/MYSITE/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
`

**Comment by korostii** [comment]
You should be able to create a new admin record from console if the role has the original name, see [here](https://www.maxpronko.com/blog/how-to-create-admin-user-in-magento-2-via-command-line) for detailed instructions.

On a sidenote, as an enterprise client, you should be able to request support from Magento, Inc. directly through your connected account. You're likely to get a faster response there.
The GitHub issue tracker is intended for technical issues only. If you are looking for a technnical advice, you can also refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by magento-engcom-team** [comment]
@tsuleehyudin, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
