### ISSUE TITLE
Deleting a website/store/storeview that has assigned categories, leaves orphaned data behind

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#9088]
If you create a multi-store website (3 or more website , store and store_view), create several categories under the same catalog, and then delete one of the website/store/store_views, the delete process leaves orphaned data behind in the database across several tables.

### Preconditions

1. CE 2.1.3
2. PHP 7
3. NginX hosted service

### Steps to reproduce

1. Create several website/store/store views withing the same installation using a single catalog (take note of the store_ids for each, lets say 1,2,3 for example).
2. Create several categories, and attach some random products to those categories.
2b. Enable flat catalog and flat categories.
3. Delete the last store_view, store and website that you created (should have the highest store_id in stores, ID = 3)
4. Check your url_rewrites table, you'll find a bunch of entity_type = category and store_id = 3 are left in that table, as well as the catalog_category_flat_store_3 will be left in the database, and in the sales_sequence_meta table if there were any associated orders, invoices, shipping and credit memos.

### Expected result

1. If a website/store/store_view is deleted, it should effectively back-delete all references to those tables as well, since they will no longer be available, and are effectively orphaned data.

### Actual result

1. Orphaned data is left behind in url_rewrites table, catalog_category_flat_store_# table, and sales_sequence_meta table (that I could tell so far anyway)

For further details, here is my specific situation:
I currently have two primary websites
Website A (id:2) , Store A (id: 17) , Store_View A (id:32)
Website B (id:1) , Store B (id: 16) , Store_View B (id: 31)

As a test a few weeks ago, I created a 3rd Website, Store and StoreView, and that store_view ID was 33, I then deleted it a few days later after realizing it wasn't going to be needed.

Here are some queries (and results) to show the problem:

`Select Store_id from store;`  
Store_id
0
31
32

`SELECT count(*) FROM url_rewrite WHERE store_id = 33;`
count(*)
326

the Entire table `catalog_category_flat_store_33` still exists in the database.

`SELECT count(*)  FROM sales_sequence_meta WHERE store_id = 33;`
count(*)
4

If you happen to use phpmyadmin you can search the entire database by searching for the old store_view ID (33 in this instance), search all tables looking in column store_id . This is how I found all the orphaned data.

**Comment by AlexWorking** [comment]
Hello @spyrule. An internal ticked MAGETWO-71184 has been created based on Your issue. As the bug is fixed, You'll be informed about. Thank You for reporting.

**Comment by spyrule** [comment]
Thank you!

**Comment by cizgidekiadam** [comment]
Any update on this ? Same issue in 2.1.8

**Comment by magento-engcom-team** [comment]
@spyrule, thank you for your report.
We've created internal ticket(s) MAGETWO-71184 to track progress on the issue.

**Comment by simonmaass** [comment]
had the same problem and had to delete them manually...

**Comment by magento-engcom-team** [comment]
@spyrule, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
