### ISSUE TITLE
Lots of ESLint errors

### ISSUE THREAD

**Issue by Igloczek** [magento/magento2#9089]
Running ESLint against M2 codebase reports lots of errors:
- `lib` dir - 82090 problems
- `vendor` dir - 37266 problems
- `pub/static/frontend/Magento/blank` - 96870 problems

This linter is not used on CI. Unfortunately current grunt implementation doesn't work too, so for now I'll stick with ESLint CLI command.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Lots-of-ESLint-errors/idi-p/73586).
