### ISSUE TITLE
Manage Titles in popup window front-end issue

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#909]
When you slide down "Manage Titles (Size, Color, etc.)" in Create new attribute set it need more space in the bottom.

Also initially there are 3 "slide down" options. But when you create 2 Attribute options then the last "slide down" disappear form view range. (may be useful to play with this pop up window a bit more)

Currently it cuts input in 3/4 of height.

**Comment by maksek** [comment]
Hi @snky1987, can you share screenshots?

**Comment by vpelipenko** [comment]
Thank you, for your contribution. This issue is confirmed and related ticket has been added to the backlog (MAGETWO-32867).

**Comment by vpelipenko** [comment]
@snky1987, this issue is fixed and will be available on public after the next update.

**Comment by maksek** [comment]
Fixed in beta8.
