### ISSUE TITLE
Update layered navigation behavior to 'or' within a filterset and 'and' multiple filtersets

### ISSUE THREAD

**Issue by brobie** [magento/magento2#9096]
From the Magento Hackathon 2017 (https://github.com/magento-hackathon/Imagine2017/issues/23):

As a customer I should be able to create complex filters using the layered navigation so that I can find what I'm looking for quicker.
Note:

example use case a customer sets category = "shoe', sets color to be both 'brown' and 'black'; results should be filtered as if category = shoe and color in ('brown','black).
AC:

Update behavior of selections within a filterset to be the same as an 'or' of those filterset selections
Update behavior when items are selected among multiple filtersets so that filter sets are 'and' ed together

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Update-layered-navigation-behavior-to-or-within-a-filterset-and/idi-p/73585).
