### ISSUE TITLE
Add information popups for options in admin

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#910]
It's an idea for some improvement that will decrease customer service time after setting up Magento2 store.

In my opinion it would be great to create little "i" icons next to options in Admin panel. Then when you hover over this icon pop up appears with short information about this option.

For example: 

On Create New product with variations add information next to "Include" that says "Is base price included to given price" or something written by someone who knows English better :)

With this set of simple information/instructions customer who will add a new product doesn't have to call Customer Service and ask "What does it mean ?"

**Comment by eleonova** [comment]
Hi @snky1987, thanks for your idea. It's definitely worth doing, but unfortunately, as for now, we don't plan to add to the product. But we have it in our backlog, so we will come back to this question at some point.
