### ISSUE TITLE
Magento 2.1 Product not displaying in frontend

### ISSUE THREAD

**Issue by bmshubham** [magento/magento2#9105]
Hey there,
this is shashank from Abacus Desk,
I'm using magento 2.1.4 with plaza theme "ma_alexa" demo english 2 on my xampp server with PHP version 5.630 and my sql version 5.6.
I created the store successfully and also inserted some products in it. After that I installed Magento 2.1 PayUIndia_PayU Extension  by cmd using commanda given in PayUIndia git website for payment gateway. and after that I insert products again but new inserted products are not displaying in my frontend website.
### Preconditions

1. Magento 2.1.4
2. PHP 5.6.30
3. MySQL 5.6
4. Ma Alexa from Plaza Theme

### Steps to reproduce

1. After my product insertion successfully i changed some code like some CSS and added static block on home page etc nothing in any other page.
2.  Then only installed payu extension 
3. When i insert products again it gets successfully saved in backend admin panel but not displaying in website

### Expected result

1. In this Case Products should get displayed in main website

### Actual result

1. [Screenshot, logs]

**Comment by bmshubham** [comment]
I think due to Reindexing on my server products are not displaying in homepage,
but in local I simply run command in my windows 7 cmd "php bin/magento indexer:reindex"
but here in cpanel, I dont know how to run such commands

**Comment by korostii** [comment]
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
