### ISSUE TITLE
Issue SOAP magento

### ISSUE THREAD

**Issue by WinnerStore** [magento/magento2#9107]
I have try save product wiht SOAP C# in a clean installation 2.1.3
If i find the category work fine if i find a product error

does anyone know how to solve

{System.ServiceModel.FaultException: SOAP-ERROR: Parsing WSDL: Couldn't load from 'data://text/plain;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGRlZmluaXRpb25zIHhtbG5zPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93c2RsLyIgeG1sbnM6d3NkbD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3NkbC8iIHhtbG5zOnRucz0iaHR0cDovL2l0YWxpYW9ubGluZS53aW5uZXJzdG9yZS5pdC9nYWRnZXQvc29hcC9kZWZhdWx0P3NlcnZpY2VzPWNhdGFsb2dQcm9kdWN0QXR0cmlidXRlR3JvdXBSZXBvc2l0b3J5VjElMkNjYXRhbG9nUHJvZHVjdEF0dHJpYnV0ZU1hbmFnZW1lbnRWMSUyQ2NhdGFsb2dQcm9kdWN0QXR0cmlidXRlT3B0aW9uTWFuYWdlbWVudFYxJTJDY2F0YWxvZ1Byb2R1Y3RBdHRyaWJ1dGVSZXBvc2l0b3J5VjElMkNjYXRhbG9nUHJvZHVjdEF0dHJpYnV0ZVR5cGVzTGlzdFYxJTJDY2F0YWxvZ1Byb2R1Y3RSZXBvc2l0b3J5VjElMkNjYXRhbG9nUHJvZHVjdEN1c3RvbU9wdGlvblJlcG9zaXRvcnlWMSIgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3NkbC9zb2FwLyIgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeG1sbnM6c29hcC1lbmM9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW5jb2RpbmcvIiB4bWxuczpzb2FwMTI9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzZGwvc29hcDEyLyIgbmFtZT0iTWFnZW50b1dTREwiIHR

**Comment by korostii** [comment]
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, steps to reproduce, etc. in order simplify attempts in reproducing it. Screenshots and stack trace from browser console (if any) are also helpful.

In this case, the error is likely on C# side: it seems to be unable to the load the WSDL definition. I would guess that you're using an invalid endpoint URL. I suggest that you consult the [devdocs](http://devdocs.magento.com/guides/v2.0/soap/bk-soap.html) in order to find the proper endpoints.

**Comment by WinnerStore** [comment]
Hi,
The problem is magento, if I install a theme default not, specifically "SM REVO" the problem magically resolves, then the problem is definitely on magento clean!
The proble. is on the manage of product, category is ok!

Error PHP

in /home/sviluppo213winne/public_html/random/vendor/magento/module-webapi/Model/Soap/ServerFactory.php on line 46                        

public function create($url, $options)
    {
     	$soapServer = new \SoapServer($url, $options); /* line 46 */
        $soapServer->setObject($this->_soapHandler);
        return $soapServer;
    }


I have installed Magento 2.1.3, I went in the backend i have created token code on integration for SOAP, C # load from magento wsdl
example
http://xxx.xx.it/soap/default?wsdl=1&services=catalogProductAttributeGroupRepositoryV1,catalogProductAttributeManagementV1,catalogProductAttributeOptionManagementV1,catalogProductAttributeRepositoryV1,catalogProductAttributeTypesListV1,catalogProductRepositoryV1,catalogProductCustomOptionRepositoryV1

C#

 public static CatalogDataProductInterface TrovaProdotto(String Chiave, String Sku, Int32 TentativoNumero, Int32 MaxTentativi, Int32 ValoreThreadSleep)
            {
                CatalogProductRepositoryV1GetRequest GetRequest = new CatalogProductRepositoryV1GetRequest();
                GetRequest.sku = Sku;

                catalogProductRepositoryV1PortTypeClient PortTypeClient = new catalogProductRepositoryV1PortTypeClient();
                PortTypeClient.Endpoint.Binding = GetBinding();
                AddAuthorizationHeader(PortTypeClient.InnerChannel, Chiave);

                CatalogDataProductInterface ProductInterface = new CatalogDataProductInterface();

                try
                {
                    ProductInterface = PortTypeClient.catalogProductRepositoryV1Get(GetRequest).result;
                    PortTypeClient.Close();
                }
                catch (Exception Err)
                {
                    if (TentativoNumero == MaxTentativi)
                    {
                        PortTypeClient.Close();
                        throw (Err);
                    }
                    else
                    {
                        try
                        {
                            Thread.Sleep(ValoreThreadSleep);
                            TentativoNumero++;
                            ProductInterface = TrovaProdotto(Chiave, Sku, TentativoNumero, _MaxTentativi, _ValoreThreadSleep);
                            PortTypeClient.Close();
                        }
                        catch (CommunicationException Err2)
                        {
                            PortTypeClient.Close();
                            throw (Err2);
                        }
                        finally
                        { }
                    }
                }

                return ProductInterface;
            }



thanks
