### ISSUE TITLE
Magento 2.1.3 "Catalog Price Rule" is missing status "active/inactive"

### ISSUE THREAD

**Issue by jeo4long** [magento/magento2#9110]
Client uses Magento 2.0.x then upgraded to 2.1.3. They have used "catalog price rule" flawlessly in the past.

But in 2.1.3, we notice there is no "active/inactive button". So far we notice this "status" are not available in: 2.1.2, 2.1.3 and 2.1.5.

Did Magento omit the active/inactive button? Or we installed the incorrect version or missing some files?

![image](https://cloud.githubusercontent.com/assets/727885/24608240/e5b711d8-189f-11e7-9e76-176583a08330.png)

**Comment by josealgardataborges** [comment]
In 2.1.5 (at least in mine) it shows up... http://prntscr.com/erwd0t
