### ISSUE TITLE
grunt exec:<theme> deletes most of static content

### ISSUE THREAD

**Issue by MrDaar** [magento/magento2#9117]
### Preconditions
1. Magento: 2.1.5
2. PHP: 7

### Steps to reproduce
Before `grunt exec:<theme>`:
```
user@hostname: pub/static/frontend/<Vendor>/<theme>/<locale>/css$ ls -alh
_custom.less
docs
email.css
email-fonts.css
email-fonts.less
email-inline.css
email-inline.less
email.less
fonts
print.css
print.less
source
styles-l.css
_styles.less
styles-l.less
styles-m.css
styles-m.less
```
After `grunt exec:<theme>`:
```
user@hostname: pub/static/frontend/<Vendor>/<theme>/<locale>/css$ ls -alh
_custom.less -> app/design/frontend/<Vendor>/<theme>/web/css/_custom.less
source
_styles.less -> vendor/magento/theme-frontend-blank/web/css/_styles.less
styles-l.less
styles-m.less
```
The less files have been symlinked, great!
But where the hell did everything else go?
The parent directory is worse, all the JS has been deleted.

So what do I do?
1. Rerun `php bin/magento setup:static-content:deploy --language <local>`, so that the files come back.
2. Now must rerun `grunt exec:<theme>` to "Republish[es] symlinks to the source files", as per documentation: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html
3. Cry... because now I'm back at the start. Most of `pub/static/frontend` has been deleted...

### Expected result
1. All files other than `.less` should not be deleted.

### Actual result
1. All files other than `.less` are deleted.

**Comment by MrDaar** [comment]
I'm currently working as follows:
1. `php bin/magento setup:static-content:deploy --language <locale>`
2. Must `rm pub/static/frontend/<Vendor>/<theme>/<locale>/css/_custom.less`
3. `php bin/magento dev:source-theme:deploy --type=less --locale=<locale> --area=<area> --theme=<Vendor>/<theme> css/_custom`
4. `grunt watch`

Steps 2. and 3. on multiple files - space separated - the ones you're working on.
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-less-sass.html

**Comment by indiebytes** [comment]
@MrDaar I've been struggling with this as well and this is my approach:

```
$ grunt exec
$ php bin/magento dev:source-theme:deploy --type=less --locale=<locale> --area=<area> --theme=<Vendor>/<theme>
$ php bin/magento setup:static-content:deploy --language <locale> --no-css --no-less
$ grunt watch
```

It's worth mentioning that I've got this issue with Magento CE 2.1.4 as well.

**Comment by hostep** [comment]
@MrDaar & @indiebytes: you should never run `setup:static-content:deploy` on your local development environment, that command is only necessary when deploying to a production server.

And for as far as I am aware, the `dev:source-theme:deploy` command is already ran by the `grunt exec` command, so you shouldn't run that either, but it has been too long since I actually used grunt in a Magento project, so I might be wrong.

And you probably should also run `grunt less:<theme>` before running `grunt watch`.

Maybe the documentation can help you further: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html ?

Also, it's best if you ask these kind of questions on http://magento.stackexchange.com/ or on the Magento forums: https://community.magento.com/, since this isn't a bug which you are reporting :)

**Comment by MrDaar** [comment]
Not a bug.
Thanks @hostep

**Comment by rmtngh** [comment]
Magento 2.2.3
php 7.1.12

I have a similar problem, necessary files and directories are not getting created after grunt exec, this happens in all themes, before grunt exec, if I `ls pub/static/frontend/Magento/blank/en_US` I'll get:
```
Dotdigitalgroup_Email        Magento_Search
FormData.js                  Magento_SendFriend
Magento_AdvancedCheckout     Magento_Shipping
Magento_Authorizenet         Magento_Swagger
Magento_Banner               Magento_Swatches
Magento_Braintree            Magento_Tax
Magento_Bundle               Magento_Theme
Magento_Captcha              Magento_Translation
Magento_Catalog              Magento_Ui
Magento_CatalogEvent         Magento_Ups
Magento_CatalogSearch        Magento_Usps
Magento_Checkout             Magento_Vault
Magento_CheckoutAgreements   Magento_VersionsCms
Magento_Cms                  Magento_Weee
Magento_ConfigurableProduct  Magento_Wishlist
Magento_Cookie               MutationObserver.js
Magento_Customer             Temando_Shipping
Magento_Dhl                  blank.html
Magento_Downloadable         css
Magento_Email                es6-collections.js
Magento_Fedex                extjs
Magento_GiftCard             fonts
Magento_GiftCardAccount      fotorama
Magento_GiftMessage          i18n
Magento_GiftRegistry         images
Magento_GiftWrapping         jquery
Magento_GoogleAnalytics      jquery.js
Magento_GroupedProduct       js
Magento_InstantPurchase      js-translation.json
Magento_Invitation           knockoutjs
Magento_LayeredNavigation    legacy-build.min.js
Magento_Msrp                 less
Magento_MultipleWishlist     lib
Magento_Multishipping        mage
Magento_Newsletter           magnifier
Magento_OfflinePayments      matchMedia.js
Magento_OfflineShipping      modernizr
Magento_PageCache            moment-timezone-with-data.js
Magento_Payment              moment.js
Magento_Paypal               prototype
Magento_Persistent           requirejs
Magento_ProductVideo         requirejs-config.js
Magento_Reports              requirejs-min-resolver.js
Magento_Review               scriptaculous
Magento_Reward               spacer.gif
Magento_Rma                  tiny_mce
Magento_Sales                underscore.js
Magento_SalesRule            varien
```
But after `grunt exec`:
```
Magento_AdvancedCheckout  Magento_GiftMessage       Magento_Review
Magento_Banner            Magento_GiftRegistry      Magento_Reward
Magento_Braintree         Magento_GiftWrapping      Magento_Rma
Magento_Bundle            Magento_GroupedProduct    Magento_Sales
Magento_Catalog           Magento_Invitation        Magento_SalesRule
Magento_CatalogEvent      Magento_LayeredNavigation Magento_SendFriend
Magento_CatalogSearch     Magento_Msrp              Magento_Theme
Magento_Checkout          Magento_MultipleWishlist  Magento_Vault
Magento_Cms               Magento_Multishipping     Magento_VersionsCms
Magento_Customer          Magento_Newsletter        Magento_Weee
Magento_Downloadable      Magento_Paypal            Magento_Wishlist
Magento_GiftCard          Magento_ProductVideo      Temando_Shipping
Magento_GiftCardAccount   Magento_Reports           css
```

Which results in front end not working because of missing files.

**Comment by muneerWebDev** [comment]
grunt less:theme worked for me
