### ISSUE TITLE
transactional email

### ISSUE THREAD

**Issue by hasan4it** [magento/magento2#9118]
Admin panel -> content -> confirmation -> Default Store View
### Preconditions

1.  logo uploaded for emails

### Expected result

1.  email logo should be uploaded and update the database with its file name

### Actual result

1. [Screenshot, logs]
file name updated in database but file is missing in server, every time I have to upload logo file manually using ftp at: /pub/media/email/logo/stores/1

**Comment by okorshenko** [comment]
Pull Request #9590 has been merged to 2.1-develop branch. Thank you @hostep for your contribution!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69062
