### ISSUE TITLE
Just use JSON

### ISSUE THREAD

**Issue by microcipcip** [magento/magento2#9122]
I have a suggestion, I think that the next version of Magento 2.0 should just provide JSON data and a blank page without HTML/CSS.

**Comment by sivajik34** [comment]
@microcipcip what is the necessary just returning json,could you please elaborate usage of json in magento

**Comment by microcipcip** [comment]
I think Magento should return the product fields has a JSON object. Same for categories, etc.

**Comment by orlangur** [comment]
> a blank page without HTML/CSS

This is pretty similar to Blank Theme ;)

I'm not sure I understood your intention, but I dislike current direction of frontend development (jQuery+jQueryUI+KnockoutJS+a lot of reinvented custom wheels) a lot as well. 

I would prefer frontend based on Angular 2 with all data obtained via REST API as JSON. So that having full JSON data anyone can easily replace storefront with SPA based on framework of one's choice.

Some big integrators are already trying this approach: headless Magento 2 + custom frontend.

**Comment by microcipcip** [comment]
I agree that the current frontend landscape is fragmented and unequivocally messy, therefore  Angular2/VueJS integration on Mage2 with REST or possibly GraphQL would be the optimal compromise to circumvent the current magento front-end issues.

**Comment by adragus-inviqa** [comment]
I wouldn't be in a hurry to say `use <JS framework> to circumvent the current magento front-end issues`. I don't know a case in which these stories had a happy ending. But boy do they have a happy beggining!

Sure, let's JS everything, I'm all for it, but let's be realistic, too. By the time you finish JS-fying the footer, half of the npm packages are EOL. And that's just the beginning.

**Comment by vrann** [comment]
@microcipcip there is a large "headless" trend in the Magento development, where Magento is used as a backend service via API, while front-end is built with the third-party javascript libraries and web frameworks. One interesting example of such approach was introduced on Magento Imagine 2017, here is related repository: https://github.com/bobvanluijt/magento-collect

It does not matter what presentation layer Magento have, what matters is how good the Magento APIs for third-party tools and this is where Magento investing the resources.

**Comment by microcipcip** [comment]
I get your point, but can you deploy with Webpack and minify the JS?

**Comment by magento-engcom-team** [comment]
@microcipcip please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
