### ISSUE TITLE
Something went wrong while saving the category

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#9123]
### Preconditions

1. I use Magento 2.1.4
2. PHP 7.x, Nginx, MySQL 5.4
3. max_allowed_packet = 64M
4. wait_timeout = 60000

### Steps to reproduce

1. Login to Magento Admin
2. Go to Category > Click on any category having product more than 700
3. Click on save category
4. But if I have a category with 606 products is save without any error.

### Expected result

1. Category would be save without any error.

### Actual result

1. Gives an error "Something went wrong while saving the category."

**Comment by jimul** [comment]
Faced same issue with Magento2.1.5 EE, when debug issue in detail, found exception "There is no active transaction".So it requires higher server  configuration to make it possible save category with many products assigned under that.  Anyone found reasonable solution to make it working over server with average configuration?

**Comment by rishabhrkrai** [comment]
See the exception.log for the more details. In my case this issue is related with the DB.

I just increase the **max_allowed_packet** to **524288000** and **wait_timeout** to **300** in the DB.

Use the query in DB with root previladge
SET GLOBAL max_allowed_packet = 5242889000
SET GLOBAL wait_timeout = 300
