### ISSUE TITLE
Magento 2 translation issues

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#9135]
Magento_checkout is not translated to Hebrew and its look like some of the string has been deleted
i try to contact with Magento team on crowdin.com and open an issue on official Magento repo but still i get no answer so i open an issue here as well 

### Preconditions
1. Magento 2.1.5

### Steps to reproduce

1.cd <your magento path>
2.composer require magento2translations/language_he_il:dev-master
3.php bin/magento cache:clean
4.checking if the string has been translate in https://crowdin.com/translate/magento-2/1201/enus-he and it is 

### Expected result
1. Magento_checkout need to translated

### Actual result
1. Magento_checkout is not translated to Hebrew and its look like some of the string has been deleted

comment:
i check 
link for the repo :
https://github.com/Magento2Translations/language_he_il

link for the issue :
https://github.com/Magento2Translations/language_he_il/issues/6

**Comment by marcosdsdba** [comment]
## **I've tested and problem persists also Version 2.1.6**

I found the problem mostly in Checkout

**Comment by magento-engcom-team** [comment]
@refaelgold, thank you for your report.
We've created internal ticket(s) MAGETWO-81655 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @refaelgold

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@refaelgold thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
