### ISSUE TITLE
Unable to set negative product's quantity

### ISSUE THREAD

**Issue by daniloargentiero** [magento/magento2#9139]
Hi all,
I'm trying to set a negative value to the product's quantity, but I can't save the product.

### Preconditions
1. Magento version 2.1.4 
2. Set config: Stores->Settings->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products = Yes
3. Set config: Stores->Settings->Configuration->Catalog->Inventory->Product Stock Options->Backorders = Allow *

### Steps to reproduce
1. Create or edit a simple product
2. Set Quantity with a negative value (ex: -200)
3. Save

### Expected result
1. Should allow to save the product

### Actual result
1. The form return an error message: "Please enter a valid number in this field".

### Note
You can order (via Frontend) a quantity greater than that available; then try to edit the product (via Backend), but you can't save it with the negative quantity (see the attachment).

Thank you for your attention.

![screenshot from 2017-04-05 12-25-30](https://cloud.githubusercontent.com/assets/3659574/24701566/33e23250-19fb-11e7-9dac-f543ee643ec9.png)

**Comment by DigiWorksNL** [comment]
I have the same problem here in Magento version 2.1.5, today i'll try 2.1.6 in the hope the problem has been fixed

**Comment by daniloargentiero** [comment]
Ok. let us know, and please put a +1 at my post to get more visibility.

**Comment by DigiWorksNL** [comment]
There are similar posts related to this topic but no solution yet:

Issue https://github.com/magento/magento2/issues/7197
and
Issue https://github.com/magento/magento2/issues/7540

I'm going to update now to 2.1.6. I will write the results here.

**Comment by DigiWorksNL** [comment]
I have updated to 2.1.6 but the problem still exists.

**Comment by DigiWorksNL** [comment]
Today i tried a fresh install but no luck. 

I can confirm that this problem doesn't exists when 'Qty Uses Decimals' is set to Yes. Then a negative QTY is allowed. This could be a workaround but setting this to Yes allows a Qty of 1.25

![image](https://cloud.githubusercontent.com/assets/27339200/24996313/a8980cfe-2032-11e7-8371-83f922d52df4.png)

**Comment by DigiWorksNL** [comment]
Any updates on this problem?

**Comment by lavanyadckap** [comment]
I'm going to start this issue

**Comment by sadeeshmca** [comment]
We are working on this issue

**Comment by sadeeshmca** [comment]
We are unable to reproduce the issue in Magento 2.2. It seems to be fixed. However we are able to reproduce the issue in 2.1.5 and 2.1.6

**Comment by okorshenko** [comment]
Please, look at these commits:
https://github.com/magento/magento2/commit/c5013675717a4c1d9b2773e1334a62e7a5f094f5
https://github.com/magento/magento2/commit/d56f71e5cb73e49db44104b28508ed64df16011d

**Comment by redelschaap** [comment]
@sadeeshmca Will there be a version 2.1.7 that fixes some issues present in 2.1.6 or is 2.1.6 te latest version in the 2.1 mainline?

**Comment by DigiWorksNL** [comment]
I applied the commits to the files locally on my shop. These commits fixed the issue!

**Comment by okorshenko** [comment]
@DigiWorksNL thank you!
Magento 2 community member @sadeeshmca is working on this issue right now to deliver it into 2.1-develop branch. All fixes from 2.1-develop branch will be added to one of the nearest upcoming patch releases.

Thank you @sadeeshmca for working on this! You made some other people happier 👍

**Comment by okorshenko** [comment]
@sadeeshmca do you have any updates on Pull Request?

**Comment by veloraven** [comment]
This issue is a duplicate of #7401
Internal ticket: MAGETWO-60599

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69922

**Comment by orlangur** [comment]
Fix will be released in `2.1.10`.
