### ISSUE TITLE
POST content to "contact us" don't work

### ISSUE THREAD

**Issue by ser86** [magento/magento2#9141]
### Preconditions

1.  Magento CE 2.1.5
2.  PHP 7.0.16, MySQL 5.7.17

### Steps to reproduce

1.  Create a form with POST method and "contact us" page's address as action
2. Add an input tag with "comment" name and some value
3. Submit the form

### Expected result

1. "Comment" text area contain the value of "comment" input

### Actual result

1. POST contain "comment" with value
2. "Comment" text area remain empty

The same happen with every other input name in "contact us" page

**Comment by korostii** [comment]
It seems that you're trying to do some black magic.
Basically, you are making a POST request to the "contact/index/index" action (and not "contact/index/post") - is that correct?
Why would you expect that would pre-populate the contact form's fields?
I am sorry if I missed your point,  I fail to understand what you're trying to achieve.

By the way, if you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by pocallaghan** [comment]
When you say `Create a form with POST method and "contact us" page's address as action`, what URL are you actually referring to specifically? Do you mean `/contact/` or `/contact/post/`?

**Comment by ser86** [comment]
If I send request to contact/post appear a 404 error page, so I send request to contact and appear the problem described above.
With contact/index/post everything works, thanks a lot and sorry for the bug tracking

**Comment by korostii** [comment]
Glad it worked out for you :)
