### ISSUE TITLE
Magento 2 Checkout page shipping issues

### ISSUE THREAD

**Issue by shikhark92** [magento/magento2#9142]
### Preconditions

1. Php 7 
2. Magemojo server
3. Magento 2.1.5

### Steps to reproduce

Hi Guys,
This is the configuration we have set for free shipping : http://prnt.sc/esehrf.

1) Add a product to cart with less than $99 price
2) Proceed to check out and put a zip code so that the shipping prices are calculated. Please note that the price in the cart should be less the $99 without shipping.
3) Now increase the qty of the product in qty till the total goes up to or more than $99.
4) Now again reduce the qty so that the price goes less than $99.
5) You will see that the free shipping is not removed once it has appeared.

### Expected result

1.  When the cart price is below $99 the free shipping method should not be visible

### Actual result

1. http://prnt.sc/esp6up

Can anyone please help me to find a solution for this.

**Comment by phronesis** [comment]
I can see that you are using one-step checkout from Magestore. Can you disable it and see if you have the same behaviour. If the issue does not happen, then you may need to contact Magestore.

**Comment by shikhark92** [comment]
Hi phronesis,

I have tried doing that as well still the problem continues. From what i can understand is that this is due to magento 2 cache build. It seems that magento 2 builds cache even for ajax.

**Comment by Turv** [comment]
I have this issue also, not using Magestore or anything else. Once the Free Shipping threshold is reached, it then stays as free shipping regardless of any other measures.

Same issue reported here #6040

**Comment by magento-engcom-team** [comment]
@shikhark92, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
