### ISSUE TITLE
REST API: URL rewrite only created for default store when creating product

### ISSUE THREAD

**Issue by giano574** [magento/magento2#9146]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.15
3. MySQL 5.6
4. Website/store configuration:

Website | Store | Store view
------------ | ------------- | ------------- 
Danish (id: 2) | Danish Store (id: 2) | Store view (Danish)
English (id: 1) | English Store (id: 3) | Store View (English)

### Steps to reproduce

1. POST the following JSON to {domain.com}/rest/V1/products (catalogProductRepositoryV1)
```
{
	"saveOptions": true,
	"product": {
		"attribute_set_id": 4,
		"visibility": 4,
		"price": 100,
		"type_id": "virtual",
		"name": "Test product",
		"extension_attributes": {
			"stock_item": {
				"manage_stock": false,
				"is_in_stock": true,
				"use_config_manage_stock": false
			}
		},
		"sku": "testproduct",
		"status": 1
	}
}
```
2. POST the following JSON to {domain.com}/rest/V1/products/testproduct/websites (catalogProductWebsiteLinkRepositoryV1)
```
{
	"productWebsiteLink": {
		"sku": "testproduct",
		"website_id": 1
	}
}
```

### Expected result

1. New product should have url rewrites for both websites/stores

### Actual result

1. There is only created a url rewrite for the Danish website/store/store view

**Comment by giano574** [comment]
When creating a product manually for a single website and later adding another website to that product there is an option to "Copy Data from". I think the following two things should be possible

**catalogProductRepositoryV1**
You should be able to specify a `website_ids` array when creating a product (like it's possible to do through salesRuleRuleRepositoryV1 and when manually creating a product).

**catalogProductWebsiteLinkRepositoryV1**
Should have the possibility to "Copy Data from" exactly like when creating the product manually, so that you can copy the default values or values from a store view.

**Comment by magento-engcom-team** [comment]
@giano574, thank you for your report.
We've created internal ticket(s) MAGETWO-81103 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @giano574

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@giano574 thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
