### ISSUE TITLE
Product List Widget - Out of Stock Products not showing

### ISSUE THREAD

**Issue by Joe-Whitehead** [magento/magento2#9147]
Out of Stock products appear when I do not set any conditions on the Widget, but do not appear when set an out of stock condition on the widget...

### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Create a new Static Block and Add a Widget
2. Select Widget Type "Catalog Products List"
3.  Set Conditions of "Quantity" is "Out of Stock"

### Expected result

1. a product grid of all products that are marked as Out of Stock

### Actual result

1. Does not display any products
![widget](https://cloud.githubusercontent.com/assets/23500541/24709446/d4dce108-1a11-11e7-8c69-a666d1858197.png)
![widget_code](https://cloud.githubusercontent.com/assets/23500541/24709453/dc4a8be8-1a11-11e7-9363-8463970a9fb6.png)
![page](https://cloud.githubusercontent.com/assets/23500541/24709455/de5fc0ce-1a11-11e7-87ef-eb5b0c438736.png)

**Comment by IlnitskiyArtem** [comment]
@Joe-Whitehead, Thanks for contributing to this forum.
This issue is a duplicate #4108
This issue is already addressed in internal ticket MAGETWO-57028. I’ve added your report on this issue to that ticket.

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate.
Please note that the issue was fixed. And the fix will be available for ver. 2.1 in one of the next releases.
