### ISSUE TITLE
Error installing sample data with 0.42.0-beta2

### ISSUE THREAD

**Issue by fbrnc** [magento/magento2#915]
There's a dependency issue with the sample data:

* magento/sample-data exists in version 0.42.0-beta2 (and 0.42.0-beta1).
* magento/sample-data requires
  * "magento/framework": "~0.42.0-beta1",
  * "magento/magento-composer-installer": "*",
  * "magento/sample-data-media": "~0.42.0-beta1"
* magento/sample-data-media only exists in version  0.42.0-beta1

This combination seems to make it impossible to install the sample data:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/sample-data-media could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for magento/sample-data 0.42.0.beta2 -> satisfiable by magento/sample-data[0.42.0-beta2].
    - magento/sample-data 0.42.0-beta2 requires magento/sample-data-media ~0.42.0-beta1 -> no matching package found.
```

**Comment by alankent** [comment]
You are correct. I did get it to work using a git clone to get the main code then added sample data afterwards, but I did this by adding dependencies to the root composer.json file. The exact sequence I used personally was:

    $ git clone https://github.com/magento/magento2.git
    $ cd magento2
    $ git checkout tags/0.42.0-beta2
    $ composer install
    $ composer config repositories.foo composer http://packages.magento.com/
    $ composer require magento/sample-data:0.42.0-beta2 magento/sample-data-media:0.42.0-beta1

Maybe explicitly adding the sample-data-meda:0.42.0-beta1 got around the problem.

**Comment by yaronish** [comment]
According to http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html
both packages(sample-data and sample-data-media) must be added to required section for sample data success installation

**Comment by verklov** [comment]
MAGETWO-32358

**Comment by hsuastegui** [comment]
For the 0.42.0-beta2 installation, I updated the composer.json with:
"magento/sample-data": "0.42.0-beta2",        
"magento/sample-data-media": "0.42.0-beta1"
 and it works

**Comment by verklov** [comment]
@fbrnc, did you try to use the recommendation by @yaronish? Was your issue resolved?

**Comment by fbrnc** [comment]
Problem seems to be resolved now. Sorry for not closing this ticket earlier.

**Comment by verklov** [comment]
No problem, @fbrnc. We are glad the issue is resolved :-)

**Comment by alihalabyah** [comment]
Is there updated sample data for `Version 0.74.0-beta2`?

I'm getting the following:

```
- Installation request for magento/sample-data 0.42.0-beta1 -> satisfiable by magento/sample-data[0.42.0-beta1].
```

**Comment by joanhe** [comment]
@alihalabyah Yes. There an updated sample data for Version 0.74.0-beta2. You can find available packages here: http://packages.magento.com/#magento/sample-data. You might need to update composer.json file to require the right version.
