### ISSUE TITLE
Estimate Shipping and Tax

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#9150]
**Preconditions**
Magento 2.1.3
PHP version 7.0.8
MySQL version 5.7.13

**Steps to reproduce**
Checkout page
To show Estimate Shipping and Tax

Expected result
The Estimate Shipping and Tax will show on major browser like Chrome and Firefox.

Actual result
Chrome is OK
Firefox is not OK

Screenshots:
Chrome:  https://www.screencast.com/t/7wywyHZJxACo - OK
Firefox:  https://www.screencast.com/t/sMR8StWl - Not OK, its not showing.

**Comment by vherasymenko** [comment]
hello  @noprobz09  can you write version of OS and Mozilla browser ???

**Comment by korostii** [comment]
If browser console contains any errors when the section fails to load, a screenshot of those would also probably be helpful in order to distinguish this exact bug or deduce the preconditions (if any).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
