### ISSUE TITLE
Unused Shell Utility Requirement : lsof 

### ISSUE THREAD

**Issue by mikeymike** [magento/magento2#9164]
I was hoping to make use of the `support:backup:db` command but got hit with an exception with the error 
```
Error: Utility lsof not found
```
At first I wasn't really sure why we'd need `lsof` to backup a DB so I thought I'd look through the code to see what was happening. 

After debugging through I realised that `\Magento\Support\Helper\Shell::initPaths` was what was actually throwing the exception. 

It looks to me that it's ensuring that a set of utilities are available regardless of whether or not the specific task we want to run requires it or not. 

I was interested in where `lsof` was actually being used so decided to do a few global searches and only came up with test files so I don't actually think it's being used. 

### Preconditions

1. A machine with `lsof` not installed

### Steps to reproduce

1. Run `bin/magento support:backup:db`

### Expected result

1. Should be able to backup the DB

### Actual result

1. Get an error `Error: Utility lsof not found`

---

I think this should be refactored so these utilities are not globally required when trying to use the Shell class, it should be fairly trivial to remove the exception and only throw when a utility requested isn't available.

**Comment by magento-engcom-team** [comment]
@mikeymike, thank you for your report.
We've created internal ticket(s) MAGETWO-67000 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@mikeymike, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
