### ISSUE TITLE
SVG files are not gzip by default Varnish configuration

### ISSUE THREAD

**Issue by shavounet** [magento/magento2#9166]
### Preconditions
1. Magento 2.1
2. Varnish 4 (but might apply on Varnish 3 too)
3. For better visibility use a heavy SVG file (add a bunch of white character at the end)

### Steps to reproduce
1. Create a Varnish4 configuration through Magento's admin
2. Deploy the Varnish configuration
3. Directly request an SVG file placed in pub/static

### Expected result
1. The response request should contain `Content-Encoding :"gzip"`

### Actual result
1. The request is not gzipped

### Correction hint
1. In `sub vcl_backend_response`, the condition that applies the gzip should contain `beresp.http.content-type ~ "xml"` because the SVG Content-Type is `Content-Type :"image/svg+xml"`

**Comment by magento-engcom-team** [comment]
@shavounet, thank you for your report.
We've created internal ticket(s) MAGETWO-83235 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@shavounet, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
