### ISSUE TITLE
Magento 2.1.5 no newsletter queue option in action column

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#9168]
### Preconditions

1. Magento 2.1.5
2. 

### Steps to reproduce

1. Go to Marketing->Newsletter Template
2. Open dropdown menu in Action column
3. 

### Expected result

1. System shows two option Queue and Preview
### Actual result

1. [Screenshot, logs]
System shows onl Preview option
![newsletter](https://cloud.githubusercontent.com/assets/2456408/24810849/6f296266-1bcc-11e7-9813-48100e034e0e.jpg)

**Comment by Tonop** [comment]
Hi! 

Could somebody pls explain what is wrong, maybe I missed to install newsletter extension or it should work out of the box?
Any answers are appreciated.

Best,
Boris

**Comment by Ctucker9233** [comment]
@Tonop It should work out of the box. Assuming you don't use any extensions that would affect the newsletter, it could be a missing file or a caching issue. Trying clearing caches first.

**Comment by Tonop** [comment]
Hi Ctucker9233, thanks for response.

I have just cleared cache using standard tools in Cache Managment menu but it didnt affect on newsletter functions.
Can you pls advise how else it is possible to find the reason of this issue? What files should I check if they are missed or not?

**Comment by Ctucker9233** [comment]
Well, let's say, for example, you have the downloaded .zip archive of 2.1.5. If you have FTP access, you could simply replace vendor/magento/module-newsletter with the equivalent that is in the .zip archive. This would replace all files that are in that module automatically and add in whichever ones might be missing. Then, you would need to clear caches and run php update commands. If you don't have a vendor folder, it would be under app/code.

**Comment by Tonop** [comment]
Dear Ctucker9233 ,

Thank you for your advise.
I replaced all files in vendor/magento/module-newsletter folder and cleared cache as you said above, also I sucessfully updated to 2.1.6 version but it didnt affect again - there is no queue option in Newsletter template menu.
Magento is in development mode. Maybe I should change it to production? 
Or maybe I missed any smpt settings or other settings?
Or where else to look?

**Comment by Ctucker9233** [comment]
@Tonop The only other thing I can think of is to check the console for JS errors. For chrome, it's right-click, "inspect element". On IE/edge, it's F12. It should tell you the location of the file that is throwing the JS error, or if it can't find a file it's looking for. Also check all your error logs to see if there are any clues there. Good luck.

**Comment by Tonop** [comment]
Ctucker9233,

Thanks again. I installed JavaScript Errors Notifier special plugin for chrome and but it doesnt show any errors (see screenshot).
Could you recommend another free newsletter extension?


![js_noerrors](https://cloud.githubusercontent.com/assets/2456408/25034928/e5598b84-20f2-11e7-8100-b6ae842fba6c.jpg)

**Comment by Tonop** [comment]
Guys, any ideas?

**Comment by Ctucker9233** [comment]
@Tonop I'm not sure what else to suggest. Is it possible you have a 3rd party extension that might be interfering?

**Comment by Tonop** [comment]
Ctucker9233,

I have only smtp extension installed and no others that can interfering with newsletters.
Can somebody advise how to trace and find what cause that behavior? I also can give access if somebody can help.

**Comment by Tonop** [comment]
Hi there,

Is it possible to reinstall 2.1.6 version with keeping all settings,stores,attributes,attribute sets,categories,products? 
Could you pls refer me to guides or any other helpful resources?

Boris

**Comment by korostii** [comment]
> Is it possible to reinstall 2.1.6 version with keeping all settings...

Here's the official guide from DevDocs: [Command-line upgrade](http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html)

Please note that if you are looking for some help or an advice regarding setup or development it is advised to refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only. Discussing multiple unrelated issues in a single thread may cause the important bits of information to get lost or mishandled.

**Comment by Ctucker9233** [comment]
@tonop It may be worth it to see if it is the smtp extension. Just disable and run upgrade commands and see if it makes any sort of difference.

**Comment by magento-engcom-team** [comment]
@Tonop, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
