### ISSUE TITLE
File permission error on installation process finish

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#917]
It is really hard to reproduce this error as I had it only 2 times during multiple (over 20 now) installation processes.

At the end of installation process I noticed this error in console:
<br />
<b>Warning</b>:  unlink(foo\bar\AppData\Local\Temp\install.log): Permission denied in <b>foo\bar\\magento2\setup\module\Magento\Setup\src\Model\WebLogger.php</b> on line <b>168</b><br />
{"key":"28bb7d0ff44ef670a980dd0a202811fc","success":true,"messages":["For security, remove write permissions from these directories: \u0027foo\bar\\/magento2\/app\/etc\u0027 "]}

And it also causes Installation Incomplete error on screen. I noticed this error on Windows 7 and I think it may be one of two reasons:

1) Windows just going crazy and block access to file (less probable)
2) File is in use during write process and not yet closed when unlink() function is executed

Will it be a good solution to check directory permission (or file permission) and change it (just in case of first point) and to make sure just fclose() it before unlink(). 

If someone have a better idea just write :) 

As I said it's hard to reproduce this error but I am going to implement solution worked out here and keep trying to break installation process just to make sure that its fixed.

**Comment by snky1987** [comment]
Now I can confirm that error exists every time I install Magento as a first install. To reproduce this error remove all Magento files, restart Windows, clone anew and run composer install.

**Comment by mazhalai** [comment]
We are working on this internally and will have a fix soon.

**Comment by snky1987** [comment]
@mazhalai Thanks

And little offtop: I cant send private messages using github. Is there anyone that I can contact via email (or otherwise) to discuss some minor things that doesn't require github ? (e.g. contribution cases, questions about workflow etc.) I am also PHP Developer and I am willing to help with some issues as well ;)

**Comment by mazhalai** [comment]
@snky1987  Please feel free to post your questions here. Contribution guidelines can be found [here](https://github.com/magento/magento2/wiki/Contribution-Guide).

**Comment by snky1987** [comment]
@mazhalai Hi thanks for resp. I actually have an issue with DateTest. I reported it on #928 but some people doesn't have this issue on commits. Can it be because of systems difference ? (Windows and Unix) ? I am feeling dumb on this issue :)

**Comment by mazhalai** [comment]
@snky1987 The original issue was fixed and contributed in scope of MAGETWO-31850. The DateTest issue was fixed in https://github.com/magento/magento2/pull/913.

**Comment by muasir** [comment]
closing based on @mazhalai comment.
