### ISSUE TITLE
Image attribute type import issue

### ISSUE THREAD

**Issue by jroca22** [magento/magento2#9171]
I've created a custom image attribute and added to my attribute set as image. The thing is that when you try to import the attribute the same way you import images vis csv it only writes the value as text.

### Preconditions
Magento 2.2.0
### Steps to reproduce

1.  Create a custom image attribute and add it to your attribute set (new_image)
2. Go to any product of that attribute set and assign the attribute to any image
3. Export that product it and see the value of the new_image attribute on additional attributes
4. Now let's say you want import a new image and assign to that image the new_image attribute. Let's say the image name is image01.jpg and it has been uploaded to pub/media/import
5. On the csv change the value of new_image=image01.jpg and add image01.jpg to additional images.
6. Import the csv and set the path to /pub/media/import

### Expected result
1. Now if you export the same product the value should be new_image=/i/m/image01.jpg. You expect Magento to copy the image to the product media folder.

### Actual result
1. Actually the attribute value is new_image=image01.jpg if you export the product again

Why is this attributed not treated the same way an image attribute created by the system?

**Comment by EnricoB3** [comment]
Same issue. The image is imported as text.

**Comment by jroca22** [comment]
Ciao EnricoB3,
I've just imported this field with the full final path to image. This attribute value is a string so I did this workaround.
If you find any other solution please share.
Regrds,

**Comment by mukdam** [comment]
I have the same error.
Create an attribute which "Catalog Input Type for Store Owner" media images.
When I add addtional_attributes assign value but not import

**Comment by amaddatu** [comment]
I have experienced a very similar issue. I have had to make a workaround. I overwrote the import class at \Magento\CatalogImportExport\Model\Import\Product with my own class preference in a module. I added a new constructor that calls the function below. My new image attribute was 'some_new_image'. I hope this helps someone out there.

function _initImageArrayKeys(){
		$this->_imagesArrayKeys = ['image', 'small_image', 'thumbnail', 'swatch_image', **'some_new_image'**, '_media_image'];
	}

My guess is that the protected variable _imagesArrayKeys should actually be pulling from image types data instead of hardcoded arrays.

**Comment by okorshenko** [comment]
@jroca22 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version

**Comment by magento-engcom-team** [comment]
@jroca22, thank you for your report.
We've created internal ticket(s) MAGETWO-81719 to track progress on the issue.

**Comment by NormAtHuemor** [comment]
Hi, @amaddatu . Would you mind going into further detail on how you implemented the override of the import class constructor? I've set up an override in an extension based on your comment above. However, during the compile process I receive the following error:

Errors during compilation:
Vendor\Extension\Model\Import\Product
Missed required argument eventManager in parent::__construct call.

**Comment by amaddatu** [comment]
@NormAtHuemor 
I wouldn't mind at all. Here are my Module Files
In the di.xml I created a class preference for my override
/etc/di.xml

I made sure that the Magento_CatalogImportExport module was loaded _before_ my module would override.
/etc/module.xml

Added my new init function in Product.php and created a new constructor override here. The constructor is nearly an exact copy of the one inside of the original class. The Imports at the top of the file were also copied from the original class. What I did add was the init function call as I stated previously that would overwrite the object's variable.
/Model/Import/Product.php

`function _initImageArrayKeys(){
$this->_imagesArrayKeys = ['image', 'small_image', 'thumbnail', 'swatch_image', 'some_new_image', '_media_image'];
}`

You can see my files below.
[ImageImportWorkaround(VendorAgnostic)2.zip](https://github.com/magento/magento2/files/1404754/ImageImportWorkaround.VendorAgnostic.2.zip)

**Comment by amaddatu** [comment]
Also, I have confirmed that the issue does exist in my Magento version 2.1.8, and that my workaround is for that version, however, it may work in others.

Magento ver. 2.1.8

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#42

**Comment by sashas777** [comment]
Hi guys,

I made composer module based on a solution at https://github.com/magento-engcom/import-export-improvements/pull/94/ and it seems works for our store.
It is only for the version from 2.2.4 and less than 2.3 where the assumption that it would be fixed in the 2.3.0 release. If it won't be then I will update composer dependencies.

Feel free to use it it would help your stores: https://github.com/sashas777/magento224-issue9171

**Comment by jruzafa** [comment]
Hello,

this is still happening in CE 2.2.5 I have applied a patch based on the PR I have seen in this and other threads.

https://gist.github.com/jruzafa/61183fe581a6c86b6a06682f905e42c9
