### ISSUE TITLE
Configurable custom options don't show on order/invoice anymore after upgrade to 2.1.4/2.1.5

### ISSUE THREAD

**Issue by martijnhovinga** [magento/magento2#9172]
For configurable product only (it still works in simple products). When adding a configurable custom option it should be displayed on order and invoice after order is placed.
### Preconditions
Magento 2.1.4 and 2.1.5

### Steps to reproduce
1. I used Magento 2.1.3 with configurable custom option in configurable product. After receiving order/creating invoice custom option is visible on order/invoice
2. I upgraded one Magento installation from 2.1.3 to 2.1.4 and another from 2.1.3 to 2.1.5

### Expected result
1.  Custom option visible on order/invoice as it was before when using Magento 2.1.3

### Actual result
Custom option NOT visible anymore after upgrade

**Comment by mike-happy** [comment]
Any solution for this? Can't find a way to add custom options on a invoice.

**Comment by magento-engcom-team** [comment]
@martijnhovinga, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
