### ISSUE TITLE
magento 2 index not invalidated after adding a new product

### ISSUE THREAD

**Issue by matin73** [magento/magento2#9174]
hello,

I am running magento 2.1.5 and can show only new products if running indexer via shell php bin/magento indexer:reindex. the problem is, that index is not set to invalid after saving a new product. cron job are running correct! 

martin

**Comment by hostep** [comment]
This is most likely a duplicate of https://github.com/magento/magento2/issues/5836

**Comment by matin73** [comment]
maybe similar - but cron is working, not setting invalid to indexing after adding a new product! no, i think is not a cron problem! what is solution?

**Comment by 7sbg** [comment]
I'm having the same problem, also in Magento 2.1.5.
I don't want to use the index mode to "update on save".

CronJobs are running but data in "indexer_state" table stays "valid" and "updated" stays at the old date.

I need a fix for this ASAP.

**Comment by magento-engcom-team** [comment]
@matin73, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by somnath12** [comment]
No need to run re indexing. To get instant help please contact here testdevelopworld@gmail.com.
