### ISSUE TITLE
Variations improvement idea

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#918]
There is one thing that I already see in Magento and it's the thing that caused my headache in Opencart before. It's variations system.

When you create product and setup basic price e.g. £8.0 and then create 3 variations with cheapest one for £10.00 in the front end (product listing and product view) it says £10.00 was £8.00 while it's not an offer.

In my opinion "was" should be in use only for special offers or discounts not to display cheapest variation price. Because if someone will work on theme where discounts will be presented as "red" color to mark it then someone will have to write an extension to separate variations from offers.

The other thing is variations prices in drop down which is my second headache in Opencart where I had to write an extension. 

People don't usually wish to see -£10 or +£20 next to variation price. They wish to see Total price of the variation in drop down so they know that Red color costs £10 not £8 + £10 :)

So my proposal is as follows:

1) When create a variation ignore basic price and show only cheapest variation price (unless its discounted)
2) Use "was" only for discounts and offers (valid with most business logic)
3) Use variations as separate products not as "change price"

It will be much more clear, easier for Admin User and also will exclude some calculation in the back  end. In our company we created over 15 e-commerce stores now and every single one works like that (successfully).

**Comment by choukalos** [comment]
Adding improvement to an existing epic ( MAGETWO-4526 ) to address improving how configurable products handle pricing & pricing updates per request.  Re-assigning to Tanya since she owns the epic.
