### ISSUE TITLE
problem saving product with certain short description content

### ISSUE THREAD

**Issue by hezide** [magento/magento2#9181]
Hi,
It's a little difficult to explain but I'll try to simplify it.
When trying to save a product with a short description including certain content the product is not being saved.
I couldn't specify the specific content that makes the problem so I'll attach working and not working content.

### Preconditions
1. magento 2.1.4 CE

### Steps to reproduce
edit a product's short description, below are pairs of 1 html that causes the problem and another which is fine:

1.here the difference is the style tag:
**Good html:**
`<p>תיק שק עשוי בד קנבס (100% כותנה) בשילוב שעם בצבע ירוק תפוח.<br />אפשרות לנשיאה על הגב או כתיק צד בעזרת רצועה פנימית בתיק.&nbsp;</p>`
**Not good html:**
`<p style="direction: rtl;">תיק שק עשוי בד קנבס (100% כותנה) בשילוב שעם בצבע ירוק תפוח.<br />אפשרות לנשיאה על הגב או כתיק צד בעזרת רצועה פנימית בתיק.&nbsp;</p>`

2. here the difference is only one space next to the ' ( ' this is not only in hebrew, but english also:
**Good html:**
`<p style="direction: rtl;">(100% כותנה) </p>`
**Not good html:**
`<p style="direction: rtl;"> (100% כותנה) </p>`
**Also in english Not good html:**
`<p style="direction: rtl;"> (100% cotton) </p>`

### Expected result
1. product being saved successfully

### Actual result

1. the "please wait" is spinning for a second, disappearing and nothing happens, the product is not being saved.

**Comment by ishakhsuvarov** [comment]
Hi @hezide 
I have tried and could not reproduce the issue (with the exact data you provided) neither on `2.1.6` nor on the current `develop` branch. Could you please check if you could have missed any of the preconditions?
Thanks

**Comment by hezide** [comment]
Hi @ishakhsuvarov, thanks for the reply.
I reproduced it as following:
1. created a new simple product.
2. name: test
2. sku: test
3. price 119
4. quantity: 100
5. visibility: not visible individually
6: description: `<p style="direction: rtl;">תיק שק עשוי בד קנבס (100% כותנה) בשילוב שעם בצבע ירוק תפוח.<br />אפשרות לנשיאה על הגב או כתיק צד בעזרת רצועה פנימית בתיק.&nbsp;</p>`
7: short description: `<p style="direction: rtl;">תיק שק עשוי בד קנבס (100% כותנה) בשילוב שעם בצבע ירוק תפוח.<br />אפשרות לנשיאה על הגב או כתיק צד בעזרת רצועה פנימית בתיק.&nbsp;</p>`
8. url key: test
and then tried to save and nothing happens.
if I delete the short description completly it works.

a screen recording below:
https://drive.google.com/open?id=0B1xnpGiLbRyZNjU0eVZiNEFCYnc

**I have found an error in js console:**

> VM11907:628 POST https://ochosbags.com/minimoon_admin/catalog/product/validate/type/simple/s…637be11d6f70efe20183b1cd7161d9729e25d86d00d430d228e6cbf903b7b/?isAjax=true 404 (Not Found)

>

**Comment by hezide** [comment]
fixed the problem.
Resolved this issue by alerting hosting company to issue.
I was tripping modsecurity rules and they fixed it.

thanks for the help!

**Comment by rashidtahir** [comment]
Anyone comment on this issue
https://github.com/magento/magento2/issues/9226
