### ISSUE TITLE
500 Error on sales/order_create/index/ after importing products

### ISSUE THREAD

**Issue by tonybrown85** [magento/magento2#9182]
### Preconditions

1. Magento Version: 2.1.5. 
2. Operating system: Ubuntu Linux 16.04.1
3. MySQL version: 5.7.17
4. PHP version: 7.0

### Steps to reproduce

1. Import products via csv into system using Magento's core importer. (No errors, completely valid csv)
2. Go to sales/order_create/ and click on the "Create New Order" button.
3. Page takes a long time to load and then produces a 500 error.

### Expected result

1. It should go to the backend order creation page so you can then select customer and create order in system backend.

### Actual result

1. 500 error / Memory Leak

Just to provide further insight into this issue this does not happen if there isn't any products / categories in the system, so before I import the products into the system.

Looking in the error logs it says bytes exhausted so there is a massive memory leak. More on this below.

I have this setup on both a xampp environment and also the envinonment as noted above. My local environment is seriously cranked up spec-wise to 6GB memory limit, and although it does not produce a 500 error and loads the page, it loads it without any js or css and I get the following error in the console:

ReferenceError: require is not defined sales/order_create/index/ Line 172

So this is not down to not having enough memory resources as this issue is present on both environments. 

Also looking at the error logs on my local environment I am getting the following, and although not the sales/order_create/index/ page it is the sales/order grid page which could possibly be linked. 

[Sun Apr 09 15:39:09.550560 2017] [:error] [pid 8956:tid 1696] [client 127.0.0.1:5438] PHP 500. Magento\\Framework\\Interception\\PluginList\\PluginList->getNext() C:\\xampp\\htdocs\\m215\\var\\generation\\Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor.php:568, referer: http://127.0.0.1/m215/admin_rjyrr4/sales/order/

Which is the getEntityIdField method. Possibly it cannot retrieve the entity type ID after the products are imported on the order grid page.

Frustratingly I started to move over all of my assets to a fresh installation as I though this problem was due to a composer upgrade that went wrong and somehow corrupted the database. It took a long time of debugging and constantly backing up databases during various key moments in the migration. 

Everything works perfectly until I import products and then this area in the admin backend completely breaks.

This is nothing to do with Cache, Static Content or indexing.

I'm not ruling out that there maybe perhaps an issue with the data that has been prepared and imported. But everything during the import process would suggest this as the file is completely valid. I will add that I have both simple products and bundled products in this import file, so questionably does the Magento import have all the required validation to ensure that column relationship and data is prepared correctly during it's file check.

Any assitance to get this fixed asap would be greatly appreciated as the site was intended to go live at the end of this month and this is a vital component that is broken that the client will need. If anybody has any suggestions on a patch to temporarily fix the problem would be greatly appreciated as well.

Kind regards,
Tony

**Comment by gediminaskv** [comment]
How did you solve this?
