### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT in admin panel magento 2.1

### ISSUE THREAD

**Issue by Hummingtec** [magento/magento2#9183]
### Preconditions

1. installed magento 2.1.5 in linux centos 6 server, 
2. installed redis 3

### Steps to reproduce

1. 

### Expected result

1. page should have loaded in 2.6 sec

### Actual result

1. each time i am trying to load the following error occurs,
2. tried deleting pub/static files cache memory
3. the navigation menu not opening.
![image](https://cloud.githubusercontent.com/assets/24954276/24840177/d4484648-1d85-11e7-9b2c-94b4fc00a9df.png)
>

**Comment by Hummingtec** [comment]
the first time i installed redis it was loading good but later after 5 refreshes the same problem persists.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues (aka bug reports) only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and support. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by korostii** [comment]
Looks like a duplicate of #7869 , please try the workarounds suggested on that issue.

**Comment by korostii** [comment]
@davidalger, wanna see something funny?
https://twitter.com/okorshenko/status/842558135734800386
Expecting to see even more various issues of all sorts reported here on Github once that marvelous admin usability improvement gets released to all the merchants =D
Just wondering: maybe there should be an extra link leading to the Magento Stack Exchange and saying "Ask For Help"?
