### ISSUE TITLE
Rating doesn`t show on related products

### ISSUE THREAD

**Issue by margo-nik** [magento/magento2#9184]
### Preconditions
1. magento 2.1.5
2.  Block of related products on product detail page.

### Steps to reproduce
1.  Call block of related product on pdp
2.  Set `$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;`
2. Go to front and look at the product in block. 

### Expected result
1.  Rating should appear.

### Actual result
1. Rating does not  show.
 Product has rating but in block of related product does not show.

**Comment by magento-engcom-team** [comment]
@MargoNikk, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
