### ISSUE TITLE
Add to product to cart message does not disappear (and stacks)

### ISSUE THREAD

**Issue by chefbuitenhuis** [magento/magento2#9188]
### Preconditions

1. Magento CE 2.1.5
2. PHP 7.0.17 

### Steps to reproduce
1. Disable full page cache
2. Add a product to the cart multiple times
3. See how the 'You've added # to your cart' remains visible and stacks up

### Expected result
The message should be removed from the 'Set-Cookie' response header upon being shown. Each messages should be only shown once.

### Actual result
1. At random occasions the message is stacking up.
2. The 'Set-Cookie' value is being appended (instead of being cleaned after showing the message).

![screen shot 2017-04-10 at 12 45 35](https://cloud.githubusercontent.com/assets/7578636/24858201/9eb308cc-1deb-11e7-96fd-f37dc922a983.png)

**Comment by martijnrmediact** [comment]
Any update on this?

**Comment by antoinekociuba** [comment]
Have the exact same issue, with FPC disabled, on a Magento 2.1.6 CE instance, running on PHP 7.0.17.

**Comment by samy-m-dev** [comment]
Same here any update?

**Comment by dmitriyprime** [comment]
Hi, @chefbuitenhuis . Thanks for the feedback. Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?

**Comment by denchev** [comment]
I have the same issue.

1. Add a product to the cart 
(a success message appears)
2. Add the same product to the cart
( a second success message appears below the first one)
3. Add the same product for a third time
(a third success message appears ...)

Do you guys have any update or workaround? A tried to fix it in various ways with limited success.

Magento 2.1.6

**Comment by magento-engcom-team** [comment]
@chefbuitenhuis, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by tousif12** [comment]
@magento-engcom-team  can you share link of fix ?  facing this issue in 2.1.8
