### ISSUE TITLE
Tax not being applied correctly to shipping discount

### ISSUE THREAD

**Issue by tjack88** [magento/magento2#9190]
### Preconditions
1. Magento 2.1.3

### Steps to reproduce
1. Set up a cart rule with a £40 fixed discount targeting the shipping (I have set the SKU as 'none' in 'Actions' so as to only target shipping"
2. Set up a tax rule of 20%
3. Go to cart with a product added to view the order total

### Expected result
1. VAT should be applied to product total and shipping (after discount has been made to shipping 

### Actual result

1. Tax is correctly applied to product total, however tax is being applied on shipping PRE discount instead of POST discount (So tax is being applied on £160 instead of £120)

Shipping rules: https://imgur.com/a/1Ulrw
Shopping cart view: https://imgur.com/a/zSGth
Tax settings: http://imgur.com/a/DBq4f

I'm not sure if this is a bug, or whether I am doing something wrong here

**Comment by Pigau** [comment]
Same as #8964

**Comment by 1408sheva** [comment]
@gold2040 Is this issue still actual? We were not able to reproduce it on ver. 2.1.7 and [2.2-develop]

**Comment by tjack88** [comment]
I tried this on 2.1.7 a week or so back and still got the error., Maybe my methods are all wrong since your not able to reproduce. I will try and reproduce the error and post screenshots

**Comment by 1408sheva** [comment]
@gold2040 I will be very grateful

**Comment by magento-engcom-team** [comment]
Closing as a duplicate of #8964
