### ISSUE TITLE
Unable to update products using csv file. 

### ISSUE THREAD

**Issue by Nym77** [magento/magento2#9193]
### Preconditions

1. PhP 7 
2. Magento 2.1.x 

### Steps to reproduce

1. Upload a csv file with products 
[PreviousMagentoVersion.csv.zip](https://github.com/magento/magento2/files/910450/PreviousMagentoVersion.csv.zip)
2. update the products using this file 
[QuantityAndPriceRevisitZERO.csv.zip](https://github.com/magento/magento2/files/910444/QuantityAndPriceRevisitZERO.csv.zip)

### Expected result

1. Quantity should change according with the second file 

### Actual result

1. Nothing happen

**Comment by 1408sheva** [comment]
@Nym77 Is this issue still actual? We were not able to reproduce it on ver. 2.1.7 and [2.2-develop]

![default](https://user-images.githubusercontent.com/22118443/27684241-d38ea4fa-5cd1-11e7-9df9-5373fc6b4ce4.PNG)

**Comment by magento-engcom-team** [comment]
@Nym77  If you'd like to update it, please reopen the issue.
