### ISSUE TITLE
"Product in Websites" is not working correctly with Configurable product

### ISSUE THREAD

**Issue by vberthet** [magento/magento2#9194]
### Preconditions

1. Magento2 CE 2.1.5
2. At least 2 Websites, 2 store view
 

### Steps to reproduce

1. Create two shop (Shop1, Shop 2)
2. Create a configurable product A with 3 variation (A1, A2, A3)
3. For subproduct A1 : Under section "Product in Websites" disable "Shop1"
4. For subproduct A2 : Under section "Product in Websites" disable "Shop2"
5. Go on product page

### Expected result

1. On shop1, configuration available should be : A2 + A3
2. On shop2, configuration available should be : A1 + A2
IE : If configuration choice is a swatch we should have only 2 choice on each shop

### Actual result

1. On shop1, configuration available are : A1 + A2 + A3
2. On shop2, configuration available are : A1 + A2 + A3

In addition, flushing cache seems to temporary fix the problem.
It's looks related to indexer (See #8698) but proposed patch doesn't resolve the problem.
### Similar issue
#6388, #6447 could also be interesting as it's still possible to add product in cart.
#7367 : Proposed solution inside this issue seem not to work properly

![selection_056](https://cloud.githubusercontent.com/assets/1115715/24873969/3d41003e-1e23-11e7-80be-6d668948c3f0.png)
Swatches related to product inside green box are disabled in current store.

**Comment by 1408sheva** [comment]
@vberthet Internal ticket MAGETWO-70292 was created;

**Comment by magento-engcom-team** [comment]
@vberthet, thank you for your report.
We've created internal ticket(s) MAGETWO-70292 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @vberthet

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@vberthet thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
