### ISSUE TITLE
Create New CLI command: Collect Magento Information

### ISSUE THREAD

**Issue by vrann** [magento/magento2#9201]
In order to understand the environment configuration of Magento, administrator should collect information about the settings from the different sources: config files, installed services, Admin UI.

Providing CLI command which will output all basic Magento settings can help to understand the particular deployment situation faster and better. CLI command can provide following information:

- Information about Magento version
- number of core business entities
- info on the configuration of the caches, queues, etc
- number of web nodes and db nodes

**Comment by adragus-inviqa** [comment]
Why would the app know - or care - about the number of web nodes available? Ditto for caches and queues. Is this some sort of command that prints helpful information for _support_? Is that the intention?

**Comment by convenient** [comment]
This sounds very much like the good old `backup.sh` bash script i've received a few times from `support@magento.com`. It's never proved very useful as it made many assumptions of how magento was organised on the file system.

Is this the same intended use case?

**Comment by vrann** [comment]
@adragus-inviqa @convenient The intent of this command is to provide the most informative information to the DevOps about the current setup so that he can grasp fast the circumstances in which platform is running. We can discuss more on what makes sense as an output for this tool. As a good example of such functionality I can give ``docker info``and ``docker inspect``

**Comment by convenient** [comment]
@vrann I get it, I think this will be a difficult task for getting settings and stuff as a CLI command may only provide info on the CLI php settings, and may not be able to get nginx or apache or varnish configuration for example?

Or am I missing something? (I'm still jet lagged from Imagine so possible)

**Comment by adragus-inviqa** [comment]
`docker info` only gives you information that docker knows. Sure, such a command could be useful, but you can't really expect M2 to know about its pipeline. But anything in env.php or from phpinfo() or various core_config data? Sure.

**Comment by nshiff** [comment]
For what it's worth, [n98-magerun2](https://github.com/netz98/n98-magerun2) implements a portion of this functionality. 

```
[nshiff@mage2 dev_m]$ ./n98-magerun2.phar sys:info

                              
  Magento System Information  
                              

+------------------+------------------------------------------------------------------------------+
| name             | value                                                                        |
+------------------+------------------------------------------------------------------------------+
| Name             | Magento                                                                      |
| Version          | 2.1.4                                                                        |
| Edition          | Community                                                                    |
| Application Mode | developer                                                                    |
| Session          | files                                                                        |
| Crypt Key        | x                                             |
| Install Date     | Wed, 22 Feb 2017 15:06:05 +0000                                              |
| Cache Backend    | Cm_Cache_Backend_File                                                        |
| Vendors          | Magento, Amasty, HE, Yotpo, IWD, Knowband, LiveChat, MagePal, Astound, Yireo |
| Attribute Count  | 167                                                                          |
| Customer Count   | 495                                                                          |
| Category Count   | 44                                                                           |
| Product Count    | 933                                                                          |
+------------------+------------------------------------------------------------------------------+
```

**Comment by enrico69** [comment]
If not completed or aleady assigned, I would like to contribute to this one.
I am keen on developers tools, I have developed a small module to list plugins, observers implementations and class overriding.

I think this new command is a good idea.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69552

**Comment by peterjaap** [comment]
@okorshenko what's the exact status on this? Just that the PR by @dreamworkers doesn't pass the tests? Or also lacking functionality?

**Comment by KarlDeux** [comment]
@vrann it would be nice to know the exactly data that you're expecting to have with this command.
ie: should information be at a store-view level if apply? 

What are the fields that you would feel comfortable with?
Also, what env information?

@dreamworkers PR seems to be sitting for long now yet it feels like a good start to play with. IMHO not much relevant information there.

**Comment by magento-engcom-team** [comment]
Hi @vrann. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/26
