### ISSUE TITLE
Upgrade components from ZF1 to ZF2

### ISSUE THREAD

**Issue by okorshenko** [magento/magento2#9203]
**Description**
As a long term goal, we would like to eliminate knowledge about 3rd party libraries from Magento code base. Magento code still can use 3rd party libraries, but they must be wrapped by Magento interfaces and classes (adapters) so that 3rd party libraries can be easily substituted by newest versions or alternative implementations.

**_Note_**
_Each component can be implemented separately. It is not a requirement to fix all components in one task/pull request_

**Acceptance Criteria**

1. Magento interfaces are defined and can be used instead of ZF1 classes in Magento code
2. Default implementations for new interfaces are defined and configured as the preferences for new interfaces
3. Client code of the ZF1 components is refactored to use Magento interfaces
4. Zend classes are used as private services in Magento adapters
5. Backward compatibility is preserved
6. ZF1 components are updated to ZF2

**List of the components**

\# | Component Name <br/> (total usages count) | Module Name | Usages Count
------------- | ------------- | ------------- | -------------
1|Zend_Translate (total: 1)|Framework\Translate|1
2|Zend_Service (total: 1)|Framework\CurrencyInterface.php|1
3|Zend_Session (total: 1)|Framework\Session|1
4|Zend_Wildfire (total: 3)|Framework\Profiler|3
5|Zend_Feed (total: 3)|Magento\Rss|3
6|Zend_Controller (total: 6)|Framework\Profiler|6
7|Zend_Oauth (total: 6)|Magento\Integration|2
&nbsp;|&nbsp;|Framework\Oauth|4
8|Zend_Log (total: 7)|Framework\Test|3
&nbsp;|&nbsp;|Framework\Shell.php|4
9|Zend_Json (total: 51)|Framework\DataObject.php|1
&nbsp;|&nbsp;|Framework\Controller|1
&nbsp;|&nbsp;|Framework\Json|2
&nbsp;|&nbsp;|Framework\Module|3
&nbsp;|&nbsp;|Framework\Webapi|3
&nbsp;|&nbsp;|Magento\Weee|6
&nbsp;|&nbsp;|Framework\Data|4
&nbsp;|&nbsp;|Magento\Theme|31

**Comment by dmanners** [comment]
Love this. Probably cannot do all but I am working through the `Zend_Json` stuff slowly

**Comment by okorshenko** [comment]
Closing this issue.
Created separate ticket per component
