### ISSUE TITLE
store view takes wrong url key when using "default value"

### ISSUE THREAD

**Issue by hezide** [magento/magento2#9205]
Hi, I'm editing a product in two store views.
The first store view works fine but there is a bug I think in the second.

### Preconditions
1. Magento 2 CE 2.1.4
2 Two store views are created

### Steps to reproduce
I think that in the past the URL KEY was different in the "all store views" but then I changed it.
In my example, the URL key in "all store views" is "red-dots-sack-bag"
1. Change to "English" store view (that's not the default store view).
2. Go to Search engine optimization. 
3. Change URL-key
4. Check Use Default Value
5. Save

### Expected result
1. Check box is checked and the value is "red-dots-sack-bag"

### Actual result
1. The check box is not checked.
2. Value inside URL KEY is "sack-bag-red-dots"

**Comment by TommyKolkman** [comment]
I have this too and have been searching for a solution, nothing yet. Just to verify - it seems like this happens on products that we have imported via the M2 import function only. Is that the case with you too?

**Comment by luukschakenraad** [comment]
Same issue here. Seems checking "use default value" generates a new slug, based on the products name instead of inheriting it from the parent store view

**Comment by hezide** [comment]
@TommyKolkman No I didn't import any product...

**Comment by Tonop** [comment]
Have the similar [issue](https://github.com/magento/magento2/issues/9305), 
1) checkboxes are not checked after checking and saving of any attribute.
2) Also the value for URL is based on product name of current store view but is not default (parent store view URL).

**Comment by magento-engcom-team** [comment]
@hezide, thank you for your report.
We've created internal ticket(s) MAGETWO-81627 to track progress on the issue.

**Comment by kllee824** [comment]
Hi,
Would like to know which table to save the different store_view to use 'use default value' 'Yes/No'? because i want to be update by SQL to enable this as my application is 'English/Chinese' store view and can't use common parent URL key when save the product

Lun

**Comment by daniel-ifrim** [comment]
Does this makes sense for you guys too ? I'd like your feedback. I haven't tested it too much but it appears to work on Magento 2.2.0.
In
`Magento\CatalogUrlRewrite\Observer\ProductUrlKeyAutogeneratorObserver`

Replace:
```
public function execute(\Magento\Framework\Event\Observer $observer)
{
        /** @var Product $product */
        $product = $observer->getEvent()->getProduct();
        $product->setUrlKey($this->productUrlPathGenerator->getUrlKey($product));
}
```
with:
```
public function execute(\Magento\Framework\Event\Observer $observer)
    {
        /** @var Product $product */
        $product = $observer->getEvent()->getProduct();
        if (!($product->isObjectNew() && $product->getUrlKey() === null)) {
            $this->productUrlPathGenerator->getUrlKey($product);
        } else {
            $product->setUrlKey($this->productUrlPathGenerator->getUrlKey($product));
        }
    }
```

**Comment by patrick-bigbridge** [comment]
I have a temporary fix for this issue:
In Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper, function initializeFromData, below the comment /** Check "Use Default Value" checkboxes values */

replace the code there with

```
        /**
         * Check "Use Default Value" checkboxes values
         */
        $useDefaults = (array)$this->request->getPost('use_default', []);

        foreach ($useDefaults as $attributeCode => $useDefaultState) {
            if ($useDefaultState) {
                $product->setData($attributeCode, null);

// Fix: by setting url_key to false (not null) we prevent ProductUrlPathGenerator::getUrlKey() from creating a new url_key
if ($attributeCode == 'url_key') {
    $product->setData($attributeCode, false);
}

                // UI component sends value even if field is disabled, so 'Use Config Settings' must be reset to false
                if ($product->hasData('use_config_' . $attributeCode)) {
                    $product->setData('use_config_' . $attributeCode, false);
                }
            }
        }
```

The idea behind this is that, even though the function initializeFromData clears the url_key from the form, the url_key is later auto-generated from the name by the plugin ProductUrlKeyAutogeneratorObserver. This plugin checks if the url_key is false; if it is, it does not generate the key.

**Comment by cadencelabs-master** [comment]
See here for a patch: https://www.cadence-labs.com/2018/03/magento-2-use-default-value-store-view-scope-fix/

The associated module should fix the issue which comes from the url_key autogenerator (for url_key attribute) and then the general issue of attributes in non-opened tabs not having their "use_default_value" flag sent to the server

**Comment by luukschakenraad** [comment]
@magento-engcom-team Seems like you've already created a patch voor this issue (at least for Enterprise). Would you mind sharing MDVA-6515_EE_2.1.9_v2.patch here?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30042` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment]
Hi @hezide, 
We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

Please could you take a look?

**Comment by hezide** [comment]
> Hi @hezide,
> We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
> 
> Please could you take a look?

Hello,
For me the issue is not relevant anymore.
If no one else encounters it, you can close.

**Comment by engcom-Charlie** [comment]
Thank you for fast answer. So i've to close it.
