### ISSUE TITLE
Apply Shopping Cart Gift Options without page reload

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/magento2#9206]
Current implementation of the Gift Options for Order and Item in Shopping Cart requires page reload to add and remove a Gift Option. This behavior is confusing to the user, as API request is sent in the background and provides no feedback until page reloads. Additionally this has effect on performance, since cart page is not stored in cache.

**Acceptance Criteria**
* Gift Options for Item and Order are assigned with an Web API request, without page reload.
* Customer can immediately observe the result of the action.
* Blocks on the Shopping Cart Page, which may be affected by this action (e. g. Totals) are updated in asynchronous manner as well.

**Comment by StevenGuapaBV** [comment]
Created pull request for fixing this issue.
Page refresh is now replaced by a XHR request and labels are shown more clearly.

Fixed along with @JesseGuapa, kudos for him

#9626

**Comment by magento-engcom-team** [comment]
Closing the issue due to inactivity
