### ISSUE TITLE
Magento2 Update from 2.1.5 to 2.1.6 faced with errors.

### ISSUE THREAD

**Issue by hyesungs** [magento/magento2#9208]
Magento2 Update from 2.1.5 to 2.1.6 faced with errors,

1.  Magento 2.1.5
2. PHP7

I am trying to upgrade Magento 2.1.5 to 2.1.6 but am faced with errors trying to upgrade from backend admin and also the command line.

1.  I am trying to upgrade Magento2 from 2.1.5 to 2.1.6 from the backend and I given this error "We cannot retrieve information on magento/product-community-edition."

- So I then tried to upgrade from the command line and then I am given this error "[Composer\Downloader\TransportException] The "https://repo.magento.com/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0 failed to open stream: no suitable wrapper could be found)".

The only thing I could find on the forum was to enable allow_url_fopen, which it is already enabled as shown below:

![image](https://cloud.githubusercontent.com/assets/25263158/24936340/619814e0-1f63-11e7-8691-8346280e3a53.png)

Please could I get some help with this. 

Kind regards.

**Comment by vzabaznov** [comment]
HI @hyesungs, i cannot reproduce your issue, please clarify you server configuration, as i can see you are using something like cpanel, do you have direct access to php.ini file?
And please provide the name of the web server you are using.

**Comment by hyesungs** [comment]
Hi there, I am just using Cpanel and yes I have direct access to php.ini this also states that allow_url_fopen is enabled. But still cannot upgrade.

**Comment by vzabaznov** [comment]
We checked upgrade in addition to our update tests and cannot confirm this issue, please provide additional info to help us resolve your problem

1. What web server do you use ?
2. Do you try to upgrade from clear Magento, or you have products/categories, etc..?
3. Do you try to upgrade form Magento Admin panel (System->Tools) ?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
