### ISSUE TITLE
Guests can now add to wish list [v2.1.5]

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#9209]
### Preconditions

1. Magento 2.1.5
2. Developer mode

### Steps to reproduce

1. Click Wish List button on product page as a guest 
2. 
3. 

### Expected result

1. You should be redirected to the account login page (at least that's what the behavior was like in v2.1.2)

### Actual result

1. After upgrading to v2.1.5, now the guest user is able to add the item to the wish list. I'm not sure if this is a new feature or a bug, but generally guests should not be allowed to add products to the wish list (if this is a new feature, then it should be configurable in Admin). The reason why I think this is likely a bug is because there is a "Sign Out" link in the left nav column, which doesn't make sense for guest users.

**Comment by thdoan** [comment]
It turned out this was a caching issue somewhere in the chain.

**Comment by TheRealHunzik** [comment]
@thdoan  i am currently developing extension for guestwishlist for  while i was shocked :P
