### ISSUE TITLE
Change resource ids from Magento_Adminhtml::* to Magento_Backend

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#921]
In the file `/app/code/Magento/Backend/etc/acl.xml` (and all the other `acl.xml` files) the prefix for the resource ids is `Magento_Adminhtml::*`.  Example:

    <resource id="Magento_Adminhtml::myaccount" title="My Account" sortOrder="50" />

It should be 

    <resource id="Magento_Backend::myaccount" title="My Account" sortOrder="50" />

since the `Adminhtml` module does not exist.

**Comment by vpelipenko** [comment]
@tzyganu Thank you for contribution! We have created the issue in our internal bug tracker and will address it once we have it prioritized. But if you want to help with this fix, your pull requests are welcome.

Ticket: MAGETWO-32668

**Comment by vpelipenko** [comment]
@tzyganu, this issue was fixed and available here from 0.42.0-beta9 version. You can checkout it and verify.
