### ISSUE TITLE
Cart price rule "Maximum Qty Discount is Applied To" is applied per product

### ISSUE THREAD

**Issue by giano574** [magento/magento2#9214]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.15
3. MySQL 5.6

### Steps to reproduce

1. Create new cart price rule with the following "Rule Information"

| Attribute | Value |
|------------------------------------|-----------------------|
| Rule Name | Test Rule |
| Active | Yes |
| Websites | All |
| Customer Groups | All |
| Coupon | Specific Coupon |
| Coupon Code | coupon |

2. Open "Actions" tab and apply the following values:

| Attribute                          | Value                 |
|------------------------------------|-----------------------|
| Apply                              | Fixed amount discount |
| Discount Amount                    | 10                    |
| Maximum Qty Discount is Applied To | 1                     |
| Discount Qty Step (Buy X)          | 0                     |
| Apply to Shipping Amount           | No                    |
| Discard subsequent rules           | Yes                   |
| Free Shipping                      | No                    |

Set "Apply the rule only to cart items matching the following conditions (leave blank for all items)" to

| | | | |
|---|---|---|---|            
| If | **ANY** | of these conditions are | **TRUE** |
|  | SKU | **is** | **sku1** |
|  | SKU | **is** | **sku2** |

Where sku1 and sku2 are SKU's of two products that are in the catalog. If SKU is not an option go to STORES > PRODUCT, search for "sku", go to Storefront Properties tab and select "Yes" in "Use for Promo Rule Conditions"

3. Go to the frontend and add 1 of each product to the cart. 
4. Go to the shopping cart and enter "coupon" in the discount code field. 

### Expected result

1. The discount is applied to the cheapest of the two items (qty calculated based on total amount of items in cart that meet the rule requirements).

### Actual result

1. The discount is applied to both items even though "Maximum Qty Discount is Applied To" is set to 1. 

![Coupon Max Qty Error Image](https://www.dropbox.com/s/xr64zibpmffzlus/coupon_error.png?dl=1 "Coupon Max Qty Error")

**Comment by IlnitskiyArtem** [comment]
@giano574, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70428 to address this issue.

**Comment by magento-engcom-team** [comment]
@giano574, thank you for your report.
We've created internal ticket(s) MAGETWO-70428 to track progress on the issue.

**Comment by kwjamieson99** [comment]
What is the current status of this? We are migrating to 2.1 and use this coupon feature regularly.  Is there a fix or another extension that should be used instead?

**Comment by ryanwong123** [comment]
@giano574 
I have faced the same issues and I solve it by using the Special Promotion Pro extension by Amasty
I set the action to apply "Fixed Discount: each 3-d, 6-th, 9-th with 15$ off"
Discount Amount: 10
Maximum Qty Discount is Applied To: 1
Each N-th: 1

Bases on above setting, only $10 dollar will be discounted. 

Hope the solution helps you.

**Comment by orlythatscool** [comment]
Facing the same issue. Would love if this rule actually worked on the total contents of the cart instead of per line item.

**Comment by nbennett25** [comment]
This seems like base functionality of the cart rule - we have a scenario where the conditions look for specific skus, the discount is 100% the price of the product, but since the 'Maximum Qty Discount is Applied To' doesn't work, all skus are discounted 100%.

**Comment by orlythatscool** [comment]
> 
> 
> This seems like base functionality of the cart rule - we have a scenario where the conditions look for specific skus, the discount is 100% the price of the product, but since the 'Maximum Qty Discount is Applied To' doesn't work, all skus are discounted 100%.

In your case, I believe you should be using the Action rules to specify SKUs.

**Comment by nbennett25** [comment]
@orlythatscool  - we do - we have the Actions set to be applied to the same set of skus as the conditions, same result.

**Comment by orlythatscool** [comment]
> 
> 
> @orlythatscool - we do - we have the Actions set to be applied to the same set of skus as the conditions, same result.

Try taking the SKUs out of the Conditions.

**Comment by nbennett25** [comment]
@orlythatscool  - no luck. Removed the skus from the conditions & all skus in the Actions are having the discount applied, even though `Maximum Qty Discount is Applied To` is set to 1.

**Comment by nbennett25** [comment]
@orlythatscool - tinkered with this a bit - seems that the `Maximum Qty Discount is Applied` is set on a _per_sku_ basis, not on the whole cart. 

Ie if I set the action to discount 100%, the `Maximum Qty Discount is Applied` to 1, and assign `Sku is one of S101,S102`. Then put 3 items in my cart: 2x S101 and 1x S102, I will get 100% off _one_ S101 and _one_ S102, whereas I would expect the rule to only apply the discount _one_ time to the first matched sku in the Action conditions.

**Comment by orlythatscool** [comment]
> 
> 
> @orlythatscool - tinkered with this a bit - seems that the `Maximum Qty Discount is Applied` is set on a _per_sku_ basis, not on the whole cart.
> 
> Ie if I set the action to discount 100%, the `Maximum Qty Discount is Applied` to 1, and assign `Sku is one of S101,S102`. Then put 3 items in my cart: 2x S101 and 1x S102, I will get 100% off _one_ S101 and _one_ S102, whereas I would expect the rule to only apply the discount _one_ time to the first matched sku in the Action conditions.

Correct. Now you've stumbled upon the exact issue that this ticket is based. It's a major flaw.

**Comment by Zabien** [comment]
+1 with the same problem. Has this issue been solved for Magento 2 (I see the issue in Magento 1).

**Comment by tookuul-owner** [comment]
+1 having the same problem

**Comment by orlythatscool** [comment]
> +1 with the same problem. Has this issue been solved for Magento 2 (I see the issue in Magento 1).

Not solved

**Comment by mjoraid** [comment]
I see the following two options in my cart rule page:
(1-)Fixed amount discount
(2-)Fixed amount discount for whole cart. 

When I use (1) Fixed amount discount, the discount applies to all items within the condition, regardless of the number I entered in "Maximum Qty Discount is Applied To"
And when I use the (2) Fixed Amount Discount for Whole Cart. , it only applies once per cart with no reference to Maximum Qty Discount is Applied To. 

What is the expected behavior here?

**Comment by inginfinitive** [comment]
I just realised this is not working and end up in this thread.
In my case it's also applying the discount to all product that meet the criteria and not just one, although the "Maximum Qty Discount is Applied To" is set to 1.
Any solution in sight ? 

I find this bug (and Many Magento ones) really hard to believe.. This is ecommerce ABC.

How can this be fixed ?

**Comment by orlythatscool** [comment]
> 
> 
> I see the following two options in my cart rule page:
> Fixed amount discount
> Fixed amount discount for whole cart.
> 
> When I use #1, the discount applies to all items within the condition, not only the one I set in :
> Maximum Qty Discount is Applied To
> And when I use the second, it only applies once per cart with no reference to Maximum Qty Discount is Applied To.
> 
> What is the expected behavior here?

The expected behavior of the  "Maximum Qty Discount is Applied To" field is that the number placed in that field is the maximum cart quantity that the rule may effect.

For example, if a rule is created, which may apply a discount on four different SKUs AND that field is set to 1 ... the discount will be applied to just one of those SKUs (usually the most expensive) even if they are all added to cart.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by swaibar** [comment]
I am facing this issue on 2.3.2, entering "Apply “Maximum Qty Discount is Applied to” to 1 should apply the discount to only one product in the basket - but instead applies to all products.  The goal is "When you buy one product, then you get x% off the second".

Why remove tag for 2.3? Why close due "it did not get much attention from both Magento Community and Core developers for an extended period"?  Clearly there multiple messages from the community stating they have this issue but the only "magento-engcom-team" engagement here seems to be to have tagged and raised confirmed issues and then after many people stating they have the same issue to have just closed this issue with the above strange comment. 

Can this not be addressed? or have I missed something?

**Comment by psdevhh** [comment]
Experiencing the same issue here on 2.3.1 - "Max Qty Discount is Applied to" set to 1 and with multiple products in the cart ALL of them are discounted. So there's no possibility to limit coupon code usage to just one product, unless I'm missing something here.

This should really be fixed IMO. Why was this moved to "Done" is beyond me.

**Comment by Zabien** [comment]
@psdevhh we are not on Magento 2.x yet – could you open a new issue with your case and refer back to this old one? Maybe it gets attention then. Alternatively, this case could be reopened, but I'm not sure who has the rights for that.

**Comment by inginfinitive** [comment]
What is truly amazing is not only that this is apparently not being addressed at all (more than 2 years already) but it's a ridiculous bug in a live product used by thousands of shops. 
If this happens in such a basic out-of-the-box feature I wonder what else happens else where..
I'm greatly disappointed with Magento TBH, it has revealed itself to be very unreliable.

**Comment by mjoraid** [comment]
> discount will be applied to just one of those SKUs (usually the most expensive) even if they are all added to cart.

So could we say that "Maximum Qty Discount is Applied To" is being skipped / ignored ?

**Comment by psdevhh** [comment]
> So could we say that "Maximum Qty Discount is Applied To" is being skipped / ignored ?

It's not ignored, it's just applied on a per product basis.

Example: You have 2 different products in your cart, each with a quantity of 2. If you set "Maximum Qty Discount is Applied To" to 1, your discount will be applied twice, once for every product. So from your 4 products total in the cart, 2 will be discounted.

**Comment by orlythatscool** [comment]
All, it's apparent that this issue will not be resolved, so I would like to share how I've worked around it. This process is scalable, but more busy than if they'd just fix this.

Example. Let's say you want 20% OFF hats that MSRP between $10-$15. There are 5 hat SKUs in your catalog, and you'd like the customer to be able to choose the hat of their liking. The kicker is that you don't want them to be able to purchase more than one at this discount. Without a condition, which would limit the total of this rule to $15 (or a max of one hat), you **cannot** build this promotion for multiple SKUs. Here is what I do...

For each of the five SKUs, you must create a separate Cart Rule, and set the max to 1. Set each rule so that they cannot be used in combination. Also, each rule will need to be an automatic savings in cart, no coupons....or your customers will need to know which coupon to use...for which hat...blah.

It's a busy experience for you, but a perfect and smooth experience for the customer. They'll never know that you're considering jumping off a cliff to build their savings. Enjoy.

**Comment by rohit247** [comment]
facing the sames issue. is this issue still not fixed.

can anyone suggest any solution for it.

Thanks!!

**Comment by orlythatscool** [comment]
> facing the sames issue. is this issue still not fixed.
> 
> can anyone suggest any solution for it.
> 
> Thanks!!

Find an extension that does it.

**Comment by orlythatscool** [comment]
It's BS that this issue is Closed. Why is it so difficult to provision a rule ammendment that limits a discount to a max quantity of total qualified items in cart? Why?

**Comment by oliverde8** [comment]
They changed the documentation so now it's not a bug anymore...
