### ISSUE TITLE
Coupon codes not showing in invoice print out

### ISSUE THREAD

**Issue by brushbaby** [magento/magento2#9216]
The coupon codes and discounts that we have added in cart price rules do not appear on the customer invoice printouts. It just shows as "Discount ()" on the invoice with no code or details. Please advise how this can show up on the invoice correctly

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by brushbaby** [comment]
The coupon codes and discounts that we have added in cart price rules do not appear on the customer invoice printouts. It just shows as "Discount ()" on the invoice with no code or details. Please advise how this can show up on the invoice correctly

**Comment by pragya-tech** [comment]
I am looking into this issue.

**Comment by brushbaby** [comment]
Many Thanks. Presuming this is a bug, so please advise when you have a fix for this so that we can implement.
Many Thanks
Sally Ann Sadler

[cid:image001.jpg@01D2C4D6.C8DD7DD0]

Sally Ann Sadler|  www.brushbaby.co.uk<http://www.brushbaby.co.uk/>  |
 UK: 0345 5202229  INTNL: +44 (0)1962 733829
Brush-Baby Ltd, The Cedar Suite, The Long Barn, Winchester Road, Alresford, Hampshire SO24 9EZ  UK

[cid:image002.png@01CD39A0.FCE6B0E0]<https://www.facebook.com/pages/Brush-Baby/169409253117513>  [cid:image003.png@01CD39A0.FCE6B0E0] <https://twitter.com/#!/brushbabytweet>


[awardlogosignature2016]

**Comment by naouibelgacem** [comment]
looking into this issue. mmSE17

**Comment by anziv** [comment]
Checking the issue MM17SE

**Comment by okorshenko** [comment]
The fix was delivered to develop branch. Thank you @naouibelgacem for your contribution!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69551
