### ISSUE TITLE
REST API catalogProductAttributeGroupRepositoryV1 not working

### ISSUE THREAD

**Issue by sanjayrawat1** [magento/magento2#9222]
Hi everyone,
I'm using Magento 2.1.5. I have a problem with fetching product attribute groups.

**Endpoint**
I am calling below endpoint with my rest client and it produces an error response.
Request method: GET
Request URL: `https://<myShop>/rest/V1/products/attribute-sets/groups/list?searchCriteria=fields&attribute_set_id=12`

Response:
```
{
  "message": "%fieldName is a required field.",
  "parameters": {
    "fieldName": "attribute_set_id"
  }
}
```

Please help me resolved this issue.

Best Regards,
Sanjay.

**Comment by nikolaybaychenko** [comment]
If it's still relevant, try this:
```
rest/V1/products/attribute-sets/groups/list?searchCriteria[filterGroups][0][filters][0][field]=attribute_set_id&searchCriteria[filterGroups][0][filters][0][value]=12
```

**Comment by veloraven** [comment]
@sanjayrawat1 thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
