### ISSUE TITLE
Magento API doesn't return the Product/Category/Page URL's

### ISSUE THREAD

**Issue by paales** [magento/magento2#9227]
### Preconditions
1. Magento 2.1.5

### Steps to reproduce
- Call `catalogProductRepositoryV1 GET /V1/products` or `GET /V1/products/{sku}` and search for a random product.

### Expected result
1. Have a getUrl method defined in the respective interfaces and have it implemented in the models so that you can retrieve the URL of the entities.

### Actual result
1. There doesn't seem to be any getUrl methods available in the Product/Category/Page interfaces.

**Comment by maghamed** [comment]
My answer to this question on Community forum https://community.magento.com/t5/Programming-Questions/Retrieving-the-product-URL-for-the-current-store-from-a/m-p/55387/highlight/true#M1400

Shortly saying, we don't support read-only entity attributes to be part of Data Objects

**Comment by korostii** [comment]
Hi @maghamed,

IMHO the solution you've suggested on the forums ("dedicated URL resolver service which will return URL for specific entity types") would be plenty enough for most use cases (as long as it would accept Store ID as a parameter).

Is there a uniform way that could help to make this suggestion (and other feature requests \ improvements out here, really) more visible to community members? i.e. adding that `up for grabs` or `#SQUASHTOBERFEST` label, or adding the issue to some ["Community Dashboard" project](https://github.com/magento/magento2/projects/13) (not sure which is being preferred nowadays).

Thank you in advance & have a nice day!
