### ISSUE TITLE
Invalidate Index

### ISSUE THREAD

**Issue by xweb4u** [magento/magento2#9228]
### Preconditions

1. Magento ver. 2.1.2
2. MariaDB

When I add a product index are not getting invalidated

### Steps to reproduce

if i run 
bin/magento indexer:reindex after adding a product all products show of frontend

however i have a project in production with the following cron
*/2 * * * * php-cli -q /home/ukwheel/public_html/bin/magento cron:run >> 
*/2 * * * * php-cli -q /home/ukwheel/public_html/bin/magento setup:cron:run >> 
*/2 * * * * php-cli -q /home/ukwheel/public_html/update/cron.php >> 

If i add a product it does not SHOW on FRONTEND until I run
php bin/magento indexer:reset
Then cron triggers fine

also if I add this to the cron it works
*/5 * * * * php-cli -q /home/ukwheel/public_html/ukwheel/bin/magento indexer:reindex
 but this means re-index is done regardless of if it is required. I do not want to run indexes that are not required.

The issue is not the cron but the products index is not getting invalidated.

**Comment by phamngsinh** [comment]
update to lastest then check again, show your log in here

**Comment by xweb4u** [comment]
you mean upgrade to 2.1.6 .. are you saying this was a bug that was fixed. do you want to see debug.log

**Comment by paales** [comment]
@xweb4u 2.1.2 is kinda old in that sense, so it is advised to upgrade anyway :)

**Comment by xweb4u** [comment]
I still get the same issue after upgrade. also after upgrade i get an issue that after re-index it only shows the first 500 records on each page instead of set 6000.

**Comment by xweb4u** [comment]
Hi. 

Not sure if i miss-understand. 

I thought if I run the following commands on cron, that after they run products will automatically show on front end in production environment.

*/2 * * * * php-cli -q "my path"/bin/magento cron:run >> /home/ukwheel/public_html/var/log/magento.cron.log

*/2 * * * * php-cli -q "my path"/bin/magento setup:cron:run >> /home/ukwheel/public_html/var/log/setup.cron.log

*/2 * * * * php-cli -q "my path"/update/cron.php >> /home/ukwheel/public_html/var/log/update.cron.log


but I have to run these commands (or invalidate index on cron) for this to work
5,25,45 * * * * php-cli -q "my path"/bin/magento indexer:reindex

8,28,48 * * * * php-cli -q "my path"/bin/magento cache:flush


I am particularly worried that after I call the index every 20 minutes I then have to clear the cache. I would rather only to have to do this after a product is changed not just as a 20 minute task?

What am i doing wrong?

**Comment by paales** [comment]
@xweb4u In general you _never_ have to reindex. You have to set the indexers to scheduled and it should always _just work_. The `indexer:reindex` command is more of a workaround if the indexer is broken for some reason.

**Comment by xweb4u** [comment]
Ok, so how do i trouble shoot a broken index

**Comment by xweb4u** [comment]
how can i fix broken indexes?

**Comment by ghost** [comment]
What can happen is the indexers are interrupted or stopped in some way. This was common in Magento 1 where an index would be marked as Processing though no indexer was running at all.

Magento 2 has a similar issue, and once stuck Processing it may not update.  A simple fix is to set the stuck indexer, or all indexers, to invalid either in the indexer_state table or from CLI run:

_magento indexer:reset_

Though one would expect Magento to eventually detect this and reset, but it never does.

**Comment by magento-engcom-team** [comment]
@xweb4u, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by SathishDreamorbit** [comment]
@magento-engcom-team 

We are using the Magento version 2.1.9. We set the "indexer" mode as "Update by Schedule".  When we tried to create  new product in the admin. The status of the indexer in the DB is not changing and still showing as "valid". So, that the cron Job is not reindex the table properly. 

Also, I have noticed many of the users are facing the same issue. Could you please check and provide the solution.
