### ISSUE TITLE
 TypeError: require.config is not a function

### ISSUE THREAD

**Issue by jagjeetjossan** [magento/magento2#9229]
I have made the custom theme after activate theme my console showing the " TypeError: require.config is not a function" 

### Preconditions
Magento ver. 2.1.5 ,  PHP Version 5.6.30 , MYSQL 5.6.35
1.  My product page add to cart button is not working .
2.  if try many times then we direct go to checkout/cart then proceed to checkout page is not working.

### Steps to reproduce

1.  I have removed the pub/static content .  deploy static content 
2. clear the cache 

### Expected result

1.  I guess add to cart button is not working because console showing the error " require.config is not a function" so I want fix it so can i continue to next.

### Actual result

![screenshot from 2017-04-13 18 13 00](https://cloud.githubusercontent.com/assets/12082814/25005098/2020b176-2075-11e7-8bb5-94ccd7c11c39.png)

Thanks,
JS

**Comment by mrkhoa99** [comment]
@jagjeetjossan is there any custom js on product page?

**Comment by jagjeetjossan** [comment]
@mrkhoa99 Yes , there is many custom js files on product page . which are include in the my custom theme .
please check screen shot.

![js-issues](https://cloud.githubusercontent.com/assets/12082814/25033058/7cccbb0e-20f7-11e7-88cc-46ce183c5866.png)

**Comment by mrkhoa99** [comment]
@jagjeetjossan It's better if you disable or remove the custom js file and check again. I think your custom js caused this issue.

**Comment by jagjeetjossan** [comment]
Sure.. let me try that..

**Comment by jagjeetjossan** [comment]
I checked in the source and i didn't fount /en_US/requirejs/require.js included on the page. Is this creating problem?

**Comment by jagjeetjossan** [comment]
Also, i tried by remove all custom js and css files..But the issue is still there.

**Comment by jagjeetjossan** [comment]
I fixed the issue.. I manually included require.js file in my theme... And everything is working fine now. 
Thanks for your responses and valuable time :)
