### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getUsername() on null

### ISSUE THREAD

**Issue by ooples** [magento/magento2#9231]
### Preconditions

1. Magento 2.1.6 (happened on 2.1.4 as well)
2. PHP 7.0.17

### Steps to reproduce

1. Try to log back in after 10-15 minutes of inactivity (doesn't happen all the time)

### Expected result

1. It should take me to the login page

### Actual result

1. [Screenshot, logs]
Fatal error: Uncaught Error: Call to a member function getUsername() on null in /var/www/vhosts/ooples.com/httpdocs/vendor/magento/module-backend/view/adminhtml/templates/page/header.phtml:32 Stack trace: #0 /var/www/vhosts/ooples.com/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include() #1 /var/www/vhosts/ooples.com/httpdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Page\Header), '/var/www/vhosts...', Array) #2 /var/www/vhosts/ooples.com/httpdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...') #3 /var/www/vhosts/ooples.com/httpdocs/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml() #4 /var/www/vhosts/ooples.com/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml() #5 /var/www/vhosts/ooples.com/httpdocs/vendor/mage in /var/www/vhosts/ooples.com/httpdocs/vendor/magento/module-backend/view/adminhtml/templates/page/header.phtml on line 32

I haven't changed any magento code at all other than upgrading. This error doesn't happen all the time but it provides the error message as a link that I can click on and it always takes me to the login screen

**Comment by southerncomputer** [comment]
How's your app/etc/env.php look? You using varnish with redis session cache?

**Comment by magento-engcom-team** [comment]
@ooples, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
