### ISSUE TITLE
Magento_CheckoutAgreements uses DOM

### ISSUE THREAD

**Issue by navarr** [magento/magento2#9232]
## Architectural Issue

The Magento_CheckoutAgreements module has two files that are committing some pretty grave architectural mistakes ;)

* view/frontend/web/js/model/agreement-validator
* view/frontend/web/js/model/agreements-assigner

Both of these use a location in the DOM where they expect to find the agreements.  Meaning that, say, if someone wants the agreements moved out of the payment methods - everything breaks.  Worse, due to the way these files are written, such a person then has to override the files completely.  Sad!

## Proposed Solution

Agreements should be pulled from the checkoutConfig, stored in models - there should probably be a list model that is then used by all the JavaScripts that need to access the agreements on the page.  The agreement model would contain variables that declare whether or not it's been accepted and whether or not it's required, and the two aforementioned models should stop caring where the agreements are stored in the DOM.

If I wasn't swamped, I'd propose this with a pull request - but for the meantime, I can only write the issue.

**Comment by magento-engcom-team** [comment]
@navarr please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about the proposal. The GitHub issue tracker is intended for technical issues only.
Thank you for the proposed solution! 👍  We are looking for Pull Request from you!
