### ISSUE TITLE
Jasmine unit test are failing silently on Travis CI

### ISSUE THREAD

**Issue by Igloczek** [magento/magento2#9252]
After merging https://github.com/magento/magento2/commit/50ed592d232b90387ff0f51cdb0215f99e70face  to develop or some previous merge not covered by CI tests, Jasmine unit tests starts throwing lots of errors. Unfortunately, status is still green and failures count is equal to 0, so it's extremely easy to miss that errors.

CI job log of https://github.com/magento/magento2/commit/50ed592d232b90387ff0f51cdb0215f99e70face commit: https://travis-ci.org/magento/magento2/jobs/217182645

The issue is not related to upgrading JS dependencies #9062, b/c it was merged two days ago, but tests are silently failing for 15 days.

**Comment by Igloczek** [comment]
CC @maksek @ishakhsuvarov 😉

**Comment by ishakhsuvarov** [comment]
@Igloczek Thanks for letting us know. We are looking into this issue.

**Comment by omiroshnichenko** [comment]
Hi, @Igloczek! Seems that issue already fixed. Can you recheck this and close issue?

**Comment by Igloczek** [comment]
Looks good now, but the question is, how to prevent this type of issues in the future, b/c a failed test doesn't return 0 when something goes wrong (expect tests itself). This issue exists few weeks and no one even notices, it's dangerous.

**Comment by Igloczek** [comment]
Waiting for response on grunt jasmine wrapper - https://github.com/gruntjs/grunt-contrib-jasmine/issues/64

**Comment by magento-engcom-team** [comment]
Hi @Igloczek 
Looks like gruntjs/grunt-contrib-jasmine#64 is closed with no resolution, or did you get any information? 
Thanks

**Comment by Igloczek** [comment]
No response at all, this project looks to be not maintained anymore.
Probably the safest way will be to stop using this Grunt wrapper and use Jasmine directly through CLI as described here https://jasmine.github.io/setup/nodejs.html

**Comment by magento-engcom-team** [comment]
@Igloczek, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Alfa** [comment]
Hi @Igloczek   thank you for your report,  we are closing this issue due Travis CI is no longer supported. Thanks!
