### ISSUE TITLE
Failed due to line endings

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#926]
Could someone explain me how crucial line endings are that Travis keep throwing an error because in column 1 line 1 /n is expected and /n/r is found ?

If its not really important is it possible to exclude line endings form PHP Standards check please ?
Or if not then please explain how to fix it (I code in Windows 7/8 so far)

**Comment by antonmakarenko** [comment]
PHP coding standard that we use requires UNIX-style (\n) line endings. If you use any modern IDE, you should be able to configure it, so it will use \n line endings.

**Comment by snky1987** [comment]
@antonmakarenko Yes you are right. In NetBeans 8.0 I am able to configure line endings but when i push changes it is automatically translated to Windows style :/ I will try to find a way tomorrow :) There must be something.

**Comment by nyov** [comment]
make sure your `.gitconfig` is set up correctly, specifically the `core.autocrlf` and maybe `core.safecrlf` settings.
```
[core]
	autocrlf = true
```
will force normalization of lineendings. You may want to use `autocrlf = input` and `safecrlf = warn` in your magento repo `.git/config`.

Maybe the team would feel like providing a `.gitattributes` file (http://git-scm.com/docs/gitattributes) in the repo to enforce this convention on `*.php` files (eol=lf)?

**Comment by snky1987** [comment]
Thanks. I found solution here: https://help.github.com/articles/dealing-with-line-endings/
Sometimes all tests are right (even the DateTest) sometimes DtateTest is ok but not PHPstandards etc. Anyway this solution fixed most of issues with line endings. When I run this test in my local machine it still shows line ending error for 99% of project (report xml file is over 2mb at the end) but not files that I push to commit :)

**Comment by snky1987** [comment]
@mage2-team Will it be possible to access report file somehow form Travis CI test about PHP coding standards ?

There are things that I can't test locally (or my coding standards tests are passing correctly) while Travis still throws  TEST_SUITE=static_annotation with PHP 5

I was able to change all line endings to LF when pushing to repo with cache update so CRLF/LF issue is no longer an issue (or shouldn't be) and checked code with recent coding standards (incl. Zend and PEAR). But it's still failing and I wish to know what is the case exactly.

**Comment by magento-engcom-team** [comment]
Hi @snky1987. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#952 by @pmclain in 2.3-develop branch
Related commit(s):
 - [5b32e8ec8d18abddbfe63a1b9bc7482e7a23cb9c](https://github.com/magento/magento2/commit/5b32e8ec8d18abddbfe63a1b9bc7482e7a23cb9c)

The fix will be available with the upcoming 2.3.4 release.
