### ISSUE TITLE
Having large number of product bundles with large number of products in each bundle, under a single bundled product, exhausts local memory

### ISSUE THREAD

**Issue by djfordz** [magento/magento2#9267]
When creating Bundled Product, if more than 20 product bundles are created, with more than 20 configurable products in each bundle, when attempting to edit the bundled product in Magento Admin Product Edit, will exhaust local computer memory as well as take forever to load.

### Preconditions

Vanilla install of Magento 2.1.6
Opcache enabled

1. Magento v. 2.1.6
2. Mysql  Ver 14.14 Distrib 5.6.32-78.1, for Linux (x86_64) using  6.0
3. CentOS 6 : 2.6.32-642.6.2.el6.x86_64 
4. PHP 7.0.18

### Steps to reproduce

1. Create bundled product
2.  add 20+ bundles of products
3. add 20+ products to each bundle
4. Attempt to edit product.

### Expected result

1. Product edit page should load in a reasonable amount of time, and not exhaust local computer memory.

### Actual result

1. Page takes forever to load and if less than 8G memory on local computer, will crash browser and sometimes computer depending on setup.
2. Page does eventually load if local computer has enough memory and performance.

https://lh3.googleusercontent.com/-7F-GCyxubTc/WPNx3F8nK_I/AAAAAAAASQI/tU5F7X0ek_QwS4lQmKlAADmSp8HlLOtmgCL0B/h257/Screenshot%2Bfrom%2B2017-04-16%2B08-29-36.png

It really isn't a bug, but could be a product improvement?

**Comment by choukalos** [comment]
Carrying epic for bundled/grouped product performance optimization - MAGETWO-67515.  Please reply/up vote if this impacts you to help us prioritize.

**Comment by djfordz** [comment]
can close issue #9274 is same issue.
