### ISSUE TITLE
Adding to cart a product quantity higher than available does not show any error message in Firefox

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#9268]
When adding to cart a product quantity higher that the available quantity does not give any error: the requested products aren't neither added to cart nor is a message displayed.

### Preconditions
Server:
Magento 2.1.4
PHP 7.0.15
Desktop:
Firefox 52.0.2 (64-bit)
Ubuntu 16.04

### Steps to reproduce
1. Checking that product is "in stock" and checking the "Quantity in stock"
2. Adding a Quantity higher that available

### Expected result
1. Getting an error message showing that the requested product isn't available in the requested quantity

### Actual result
Using Firefox _nothing happens_: the product is NOT added to cart (neither with the requested quantity nor with the available quantity) and NO error message or other messages are displayed.
Works correctly using Chrome.

https://www.giustoacquisto.com/unguento-al-veleno-d-api-per-massaggi-15ml.html
try to add 100 pieces: using Firefox won't neither add the quantity to cart nor display any error message

cheers!

**Comment by IlnitskiyArtem** [comment]
@romeof1980, Thanks for the feedback. Unfortunately, I could not reproduce the issue. May please let me know if this issue relevant for Firefox latest, latest–1?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
