### ISSUE TITLE
Admin product filter treats underscore same as hyphen

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#9272]
### Preconditions

1. Magento 2.1.5
2. Sample data installed

### Steps to reproduce

1. Create a custom attribute
2. Save some products with custom attribute value containing underscore (e.g., test_123)
3. Save some products with custom attribute value containing hyphen (test-123)
4. Go to Admin / Products / Catalog and filter by custom attribute = "test_123"

### Expected result

1. It should only return products matching custom attribute = "test_123".

### Actual result

1. It returns products matching  custom attribute = "test_123" AND "test-123". This is a problem when you want to, for example, search for all products containing test_123 and do a bulk attribute update to change the value to "test-123".

**Comment by IlnitskiyArtem** [comment]
@thdoan, Thanks for reporting this issue. 
Created internal issue MAGETWO-70234 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We've created internal ticket(s) MAGETWO-70234 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @thdoan

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@thdoan thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
