### ISSUE TITLE
Bundle Product Admin Edit

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#9274]
### Preconditions
Magento 2.1.6 

### Steps to reproduce

1. We have large bundle products in our store.  24 options with 24 selections each.  In M1 this worked fine in admin.  However in m2 opening these products to edit will freeze local computer unless the local computer has equal to or in excess of 24GB RAM.

2. Host has confirmed this issue is only because of local computer environment.  Server handles it fine.

### Expected result

1.  Should work without needing excessive amounts of local RAM.

### Actual result

1. Screenshot of frozen edit page http://www.awesomescreenshot.com/image/2403967/986f115149156b3044ebcdbd0b0c48f8 on a computer with i7 and 8GB RAM

2. Screenshot of it working correctly on a computer with 24 GB RAM https://p5.zdusercontent.com/attachment/738523/jizQA4LR0EJKXf9EOJTbHimSz?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..-B0CfQrG3qGbgyBQwkyT1w.viXEWHgRE_brov2KND-EtUdr4cGkKCiqfsjxZjhuhyeMShQJj485fzZsU5q3nwrLUrIm1Gi3Hs55cnXhxBrn1urexHgh1EPDr2ojely4zn4_8dsxHP6__xW2KJ676ComaSVotTsO19pV7SjK7Qq4WIfZp0HnOD4gkJGSW31HmTyOO5g6J-6XWQElJT2AXE1Uhi_v7i5DRK2h4CZGIowhon-AadVIFpirhX46nfXupl8UZo_vj2DoNtLUnDnVgkDmd8ZnWHCAV9ToCa3r1p4iR3IVcBM7TEbN9MCuhIpfFDk.pMzHYWdAjrWNlNBvUDZwKg

**Comment by choukalos** [comment]
Carrying epic for bundled/grouped product performance optimization - MAGETWO-67515.  Please reply/up vote if this impacts you to help us prioritize.

**Comment by ladle3000** [comment]
@choukalos I'm not sure I understand your response.

**Comment by ladle3000** [comment]
If this will help the reported issue then you have my upvote.

**Comment by magento-engcom-team** [comment]
@snoroozi, thank you for your report.
We've created internal ticket(s) MAGETWO-67515 to track progress on the issue.

**Comment by ladle3000** [comment]
Is this fixed yet? We are ready to migrate soon, but 90% of our business is
larger bundle products.

**Comment by ladle3000** [comment]
@magento-engcom-team Is this STILL unresolved?  I put m2 2.2.2 and am ready to migrate, and still can't work with my bundles...  Please advise

**Comment by densen45** [comment]
We experiencing the same issue in M 2.2.2 and it is really annoying!

We have Bundles with around 10 options and some of these options carrying about 100 products.

Additionally, deleting one of the options (just clicking on the garbage can) of such Bundles freezes the browser's tab as well and took up to 10 minutes. The CPU and RAM usage is very high. We have profiled this delete operation with Chrome's developer tools and experienced for example a "Minor GC (618 MB collected)" every second.

We are not longer able to work with our Bundle products!

We think, the "delete option" issue corresponds to the "load page" issue, so we did not opened a new issue.

**Comment by ladle3000** [comment]
@magento-engcom-team where are we at with this. Don't you guys think it might be a little bit important to manage our bundles from the admin panel?  I don't know, perhaps verging on CRITICAL.

**Comment by danslo** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@danslo thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by densen45** [comment]
Still no progress here?

@magento-engcom-team please, add the "Component: Bundle" label so this issue may get more attention.

@snoroozi did you found any workaround / third-party extension that tackles this issue?

We have - again - profiled the Bundle edit page and found that each row for an option is being added separately (dynamic-rows-grid.js and dynamic-rows.js are responsible for this), instead of all rows are being added at once. This is probably one of the reasons why the page load is so incredibly slow for Bundles with a lot of Simple Products.

**Comment by ladle3000** [comment]
@densen45 I'm using direct database queries as a workaround. I can share if you are interested.  I'm sure it could easily be converted to php scripts.

**Comment by biglier** [comment]
@snoroozi  Hi, can you share yours database query, please.

**Comment by ladle3000** [comment]
@biglier are you still in need of this?

**Comment by lortizcompegps** [comment]
I'm using Magento 2.4.2 with bundle with 1000 o 6000 subproducts... browser, mysql and php are at 100% of cpu.

Is there a solution or workaround?
