### ISSUE TITLE
Create new CLI command: Enable Template Hints

### ISSUE THREAD

**Issue by vrann** [magento/magento2#9278]
In order to help developers to work with the Magento, create new commands which will simplify the debugging of the application. Currently, enabling of these setting require doing that either with the UI or changing the configuration of the di.xml.

Create CLI command which will make possible to enable/disable Template Hinting

**Comment by miguelbalparda** [comment]
@vrann would just changing \Magento\Developer\Model\TemplateEngine\Plugin\DebugHints::XML_PATH_DEBUG_TEMPLATE_HINTS_BLOCK from 1 to 0 and vice-versa do the trick?

**Comment by miguelbalparda** [comment]
Sorry that was an incorrect constant. It seems there is no constant defined for template_hints_storefront which is the correct path for this.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69544
