### ISSUE TITLE
Failed due to DateTest

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#928]
I already fixed this issue with following set of tests locally but ofc it fails Travis so it may be ignored by team (as documentation says).

Issue is that DateTest::testGetValue() fails because '5/18/14 pm' is expected but '5/18/14 PM' is actual.
and the second fail is because '12:08 pm' is expected but '12:08 PM' is actual.

There is a pull request #923 created with lower case am/pm in it.

due to this error I am unable to create pull request about anything from setup directory.

...or maybe I do something wrong ?

**Comment by monkeysee** [comment]
Created internal issue: MAGETWO-33026

**Comment by snohe** [comment]
@snky1987, since this issue has been resolved in #913, we will go ahead and close this issue.  Should you have any questions, please don't hesitate to let us know.
