### ISSUE TITLE
Admin User Account displayed as Moderator when adjusting Reward Points in Customer Admin

### ISSUE THREAD

**Issue by Mike-DHC** [magento/magento2#9283]
### Preconditions

1. M2EE 2.1.5

### Steps to reproduce

1. As Admin user, pull up and edit customer record then view Reward Points balance by going "Reward Points" menu.
2. In "Update Reward Points Balance" area, enter a positive or negative integer in the "Update Points" field.
3. Click "Save Customer".
4. Return to customer record and click "Reward Points" to view Reward Points transactions.
5. Expand "Reward Points History" section.

### Expected result

1. The "Reason" column should display the name of the Admin user account that made the change to the Reward Points balance. For accountability, if an Admin user gives or takes away Reward Points, his/her account name should be tracked. 

### Actual result

1. The "Reason" column shows "Updated by moderator".
![image](https://cloud.githubusercontent.com/assets/27701333/25101344/f23f9172-2381-11e7-95a2-3d76922ca3db.png)

**Comment by magento-engcom-team** [comment]
@Mike-DHC  thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
