### ISSUE TITLE
Erreur setup

### ISSUE THREAD

**Issue by cframery** [magento/magento2#929]
Bonjour,
Après avoir fait : 
- git clone git@github.com:magento/magento2.git
- php composer install

Je vais sur l'url localhost/magento2/setup et j'ai cette erreur : 

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (Magento\Setup) could not be initialized.' in path\magento2\vendor\zendframework\zend-modulemanager\Zend\ModuleManager\ModuleManager.php:189 Stack trace: #0 path\magento2\vendor\zendframework\zend-modulemanager\Zend\ModuleManager\ModuleManager.php(163): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 path\magento2\vendor\zendframework\zend-modulemanager\Zend\ModuleManager\ModuleManager.php(90): Zend\ModuleManager\ModuleManager->loadModule('Magento\\Setup') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 path\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 path\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventMan in path\magento2\vendor\zendframework\zend-modulemanager\Zend\ModuleManager\ModuleManager.php on line 189

**Comment by buskamuza** [comment]
Please, ensure that Apache has permissions to read Magento files.

**Comment by cframery** [comment]
Oui merci
