### ISSUE TITLE
PayPal Pro 2 Step Processing

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#9296]
When pressing the pay button after entering a credit card number, ajax is fired then stops.  Page reloads on desktop browser then fires ajax again and then payment success.  This will leave user confused or prone to press pay now twice.  I have a screen video.

### Preconditions

1.  Magento 2.1.6 Paypal Pro

### Steps to reproduce

1. Add items to cart and checkout with credit card. 

### Expected result

1.  Should fire ajax once and proceed to success like other payment methods. Or if it takes longer than other payment methods, some wait message needs displayed to user.

### Actual result

1. Here is the screen recording http://youtu.be/A1DKdQOZ-tc?hd=1

**Comment by YPyltiai** [comment]
Hello @snoroozi ,

Thank you for bringing this to our attention.
We have created an internal ticket to fix this issue: `MAGETWO-60589`

**Comment by ladle3000** [comment]
Any chance of a patch on this. Was planning to go to production in the next couple weeks.

**Comment by YPyltiai** [comment]
I have requested for a patch for 2.1.x versions but I cannot promise to deliver it before some specific deadline though.

**Comment by ladle3000** [comment]
Ok. Thanks, where should I look for that when it is available?

**Comment by YPyltiai** [comment]
We have the ticket linked to this issue on github, and we will update it when the fix is ready.

**Comment by vishveskrish** [comment]
@YPyltiai  , https://github.com/magento/magento2/issues/7159 

This is the duplicate issue.

**Comment by vishveskrish** [comment]
@snoroozi  : We have applied the workaround patch.

Copy this js in your theme: /Magento_Checkout/web/js/action/set-payment-information.js

Find this code : 

`return storage.post(
                serviceUrl, JSON.stringify(payload)
            ).fail(
                function (response) {
                    errorProcessor.process(response, messageContainer);
                }
            ).always(
                function () {
                    fullScreenLoader.stopLoader();
                }
            );`

and replace with below

`       return storage.post(
                serviceUrl, JSON.stringify(payload)
            ).fail(
                function (response) {
                    errorProcessor.process(response, messageContainer);
                }
            ).always(
                function () {
                     setTimeout(function(){                           
                            fullScreenLoader.stopLoader();
                        }, 6000);
                   
                }
            );`

Hope this works for you.

**Comment by ladle3000** [comment]
[set-payment-information 2.txt](https://github.com/magento/magento2/files/952978/set-payment-information.2.txt)

I have put the attached file (the real js version, not attached txt version) in /public_html/app/design/frontend/Infortis/base/Magento_Checkout/web/js/action

I have refreshed cache, redeployed static files, and checked out on private firefox tab and see no difference.  Please advise what I'm doing wrong here

**Comment by vishveskrish** [comment]
Hey @snoroozi ,

The file is correct. Before deploying static files. You should remove all the pub/static files and then you should run static file deployment.

**Comment by ladle3000** [comment]
Hi, after this patch the loader just spins a really long time.  Order is placed, but confirmation screen not reached.

Processing also takes far too long, it will still seem something is wrong.

**Comment by ladle3000** [comment]
Actually on further tries the order does not get placed. Loader just keeps spinning. 

Perhaps you can provide code again with correct formatting to ensure I have nothing input wrong.

**Comment by vishveskrish** [comment]
[set-payment-information.txt](https://github.com/magento/magento2/files/958053/set-payment-information.txt)

You can check and modified the timeout value which is currently for my site is 6000. You can update based on your site . 

I have attached the code of entire JS.

**Comment by ladle3000** [comment]
I've got it working, but it still takes entirely too long for the actual transaction to process. Do you have any advice on this?

**Comment by vishveskrish** [comment]
@snoroozi  : Am not facing that too much time.

**Comment by ladle3000** [comment]
Will you please try at my store?

**Comment by vishveskrish** [comment]
We dont have any details ! @snoroozi

**Comment by ladle3000** [comment]
m2staging.com

You can use fake cc number


5176994252614657
03/19
123

My time out setting is currently 12000

**Comment by ladle3000** [comment]
I see you tested. What feedback do you have?

**Comment by vishveskrish** [comment]
yes yours taking too much time to load!

**Comment by ladle3000** [comment]
Can I see/test your site to see the difference?

**Comment by vishveskrish** [comment]
@YPyltiai  : Hello When we can get the resolution of this issue ?

**Comment by YPyltiai** [comment]
Hi @vishveskrish,

We already have a fix for current develop branch. It should be delivered to the mainline soon.
I've also created ticket to backport the fix for 2.1.x versions but I am not sure in which patch release it is going to be delivered. As of now it appears to be 2.1.8 but it may change

**Comment by alena-marchenko** [comment]
Hi @snoroozi 

Fix for MAGETWO-60589 is merged to develop branch, closing the issue.
Thank you!

**Comment by ladle3000** [comment]
@alena-marchenko what is the best way to get this fix before release.  Can you tell me specific files to pull?

**Comment by korostii** [comment]
Hi @snoroozi, typically that internal ticket ID is included into the commit messages, so the best guess would be to look it up like the following:
https://github.com/magento/magento2/search?q=MAGETWO-60589&type=Commits

**Comment by korostii** [comment]
Hi @alena-marchenko,

Could you please provide an answer to the following questions:
1. Is there any official timeline for the 2.2 release which you could announce publicly?
2. Could you please briefly explain, what's the recommended way of using the fixes provided for the develop branch if you're a merchant or an integrator currently running 2.1.x CE in production? A link to documentation would be perfect (if available).

**Background for my questions:** 
I've seen numerous issues closed with the reason "merged to develop branch" and as I understand, develop branch corresponds to the future 2.2 version and there seems to be no publicly available date for its release. Many of those bugfixes don't reach 2.1.x releases for months straight.

To be honest, I don't see how is "merged to develop branch" an acceptable resolution to an acknowledged bug. Until the fix is officially released, a lot of the users are still struggling with it.
In my opinion, having these patches added into the nearest 2.1.x (or 2.1.x.x) releases right away would be perfect, but that doesn't seem to be happening for quite a lot of similar issues out here in on Magento2's GitHub. 

Considering that the switch to 2.2 will probably be somewhat resource-heavy and very delayed, it would make sense to have an alternative suggested officially to users of 2.1.x which would help use these numerous fixes in a safe and robust way (of which there seems to be none, to the best of my knowledge).
