### ISSUE TITLE
Plugin Prioritizing(SortOrder)

### ISSUE THREAD

**Issue by gionkoch** [magento/magento2#9297]
The SortOrder Property of a Plugin(Interceptor) doesn't seem to work properly. The sortOrder isn't taken into account or not how it should according to the [Documentation](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/plugins.html).

### Preconditions
1. Magento CE 2.1.0
2. PHP 7.0.8
3. Nginx 1.10.1

### Steps to reproduce
1. Create two plugins for the same class with sortOrder="10" for PluginA and sortOrder="20" for PluginB
```<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
	<type name="\Magento\Customer\Controller\Account\Logout">
		<plugin name="Vendor_Module_PluginA" type="\Vendor\ModuleA\Plugin\LogoutPlugin" sortOrder="10" />
	</type>
</config>
```
and
```<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
	<type name="\Magento\Customer\Controller\Account\Logout">
		<plugin name="Vendor_Module_PluginB" type="\Vendor\ModuleB\Plugin\LogoutPlugin" sortOrder="20" />
	</type>
</config>
```
2. Use **after** as interceptor for the method

### Expected result
1. The code of PluginA should be executed after PluginB

### Actual result
1. The code of PluginB is executed after PluginA

**Comment by DavidLambauer** [comment]
Do I missunderstand the docs or does it says

> Following the execution of the observed method, plugins will be executed from greatest to lowest sortOrder.

This means, Plugins with the execution after will be executed from greatest to lowest. Therefore the behavior would be correct.

**Comment by gionkoch** [comment]
> Do I missunderstand the docs or does it says
> 
> > Following the execution of the observed method, plugins will be executed from greatest to lowest sortOrder.
> 
> This means, Plugins with the execution after will be executed from greatest to lowest. Therefore the behavior would be correct.

The behaviour does not work correctly.
Plugin A has sortOrder 10, while Plugin B has sortOrder 20. Therefore `PluginA::afterXYZ()` **should be executed after** `PluginB::afterXYZ()`.
But currently `PluginB::afterXYZ()` is, on the contrary to the documentation, executed last.

**Comment by magento-engcom-team** [comment]
@gionkoch, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
