### ISSUE TITLE
Flushing cache fails to wipe view_preprocessed dir

### ISSUE THREAD

**Issue by davidalger** [magento/magento2#930]
The CSS pre-processing builds everything into the `view_preprocessed/source` and `view_preprocessed/less` directories. Even in developer mode and all caches disabled, however, the files in `view_preprocessed/less` are not updated correctly when changes are made to the theme and the page refreshed (those in `view_preprocessed/source` are though). This causes even bigger problems because when flushing the cache storage (or cleaning all types) from either the admin or the CLI, these directories are not emptied, resulting in a stale cache which must be manually removed from the file-system to update what's run through the LESS compiler.

**Comment by otoolec** [comment]
David, thanks for reporting this issue.  I've opened up ticket MAGETWO-32705 internally to help the team investigate.

**Comment by mbrinton01** [comment]
Hello @davidalger, this issue should be fixed.  Please verify and if you have any concerns, you may reopen this issue.
