### ISSUE TITLE
Prepopulation of Postcode with "*"

### ISSUE THREAD

**Issue by gweeble** [magento/magento2#9301]
### Preconditions
1. Magento version 2.1.5, PHP Version 7.0.17, Mysql version: 5.6.35-81.0 Percona Server (GPL), Release 81.0, Revision c96c427
2. 

### Steps to reproduce

1.  Add products to cart and checkout without logging in
2. Cart page adds * to postcode and unless getys editied passes to checkout
3. Customers dont always delete and fails transactions SagePay Checkout (Ebizmarts 

### Expected result

1. The Postcode field should remain unpopulated until customer fills in

### Actual result

1. Field gets populated on /checkout/cart with * in postcode field.

**Comment by korostii** [comment]
Possible duplicate of #8115

**Comment by gweeble** [comment]
I am on version 2.1.5. the other post is 2.1.3 and there is no fix between versions.

It would be great if this is a feature/Bug/something else that maybe we just need a control to turn it on or off in the configuration (maybe even per store/website) rather than actually fixing?

**Comment by pboisvert** [comment]
closing as duplicate of #8115
