### ISSUE TITLE
Don't save billing_name, billing_address, shipping_address fields to sales_invoice_grid table for authorize and capture payment method

### ISSUE THREAD

**Issue by polyarush** [magento/magento2#9309]
### Preconditions
1. Magento EE 2.1.5 without sample data is installed.
2. PHP 7.0
3. BrainTree payment method is set up in sandbox mode.
4. AmazonPay payment method is set up in sanbox mode (https://github.com/amzn/amazon-payments-magento-2-plugin)

### Steps to reproduce
1. Enable and configure BrainTree payment method
2. Set "Payment Action" option to "Authorize and Captuce"
3. Place order on front-end using BrainTree payment method

### Expected result
1. Order and Invoice are created
2. "Bill-to Name" column is not empty on the invoice grid
3. billing_name, billing_address, shipping_address in the database table sales_invoice_grid are not empty

### Actual result
1. "Bill-to Name" column is empty on the invoice grid (http://prntscr.com/ey70a5)
2. billing_name, billing_address, shipping_address in the database table sales_invoice_grid are not empty (http://prntscr.com/ey70jd)

During debugging I found out that data is saved in vendor/magento/module-sales/Model/ResourceModel/Grid.php,  function refresh. But it runs before order and invoice are added to the database.

**Comment by korostii** [comment]
Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. Github is intended for the Community Edition issue reports.

**Comment by YevSent** [comment]
Hi, @polyarush, thanks for reporting, this is known issue and already fixed on develop branch.

Closed as the duplicate to https://github.com/magento/magento2/issues/6438.
