### ISSUE TITLE
unmentioned requirement tidy_parse_string

### ISSUE THREAD

**Issue by fooman** [magento/magento2#931]
This code here https://github.com/magento/magento2/blob/develop/dev/tools/Magento/Tools/Migration/System/Configuration/Formatter.php#L16 uses a function which requires another module installed which should be checked/mentioned

> (PHP 5, PECL tidy >= 0.5.2)
> tidy::parseString -- tidy_parse_string — Parse a document stored in a string

**Comment by coldgreentea** [comment]
Thanks for your report - we've created a ticket to look into it. (MAGETWO-32246)

**Comment by ilol** [comment]
Hi @fooman, thank you for this issue. We decided that we don`t need dev/tools/migration any more since that was tool to generate the Magento 2 code from existed code. We used it on initial phase of our project.
So, I have to create task to remove dev/tools/migration from Magento 2.0 code. 
But If you see value of it - please write me.

**Comment by fooman** [comment]
@ilol thanks for the comments. I think any tools that have helped eBay move their code to Magento2 is very valuable for the community as well.

Maybe you can move the code into a new repository? Alternatively if you could let me know the removed tools I will happily create a repository to host them.

**Comment by ilol** [comment]
@fooman, that is good.
May be you could fix the bug? And create pull-request? That code is still in Magento 2

**Comment by vpelipenko** [comment]
@fooman, thanks for feedback. We are going to review existing bunch of tools for migration and provide our vision what of them can be valuable for community developers.

**Comment by piotrekkaminski** [comment]
@fooman we started working on migration tools to help with move from 1.x. It should be on github in the next few days.

**Comment by mazhalai** [comment]
@fooman since there are new migration tools ([for code](https://github.com/magento/code-migration) and [for data](https://github.com/magento/data-migration-tool-ce)) available, closing this issue.
