### ISSUE TITLE
Import can't use add_update as behaviour

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#9310]
When importing products "add update" behaviour is shown among the other options, but if selected the import is done in "append" mode.

### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. Create a csv with a couple of products
2. Put a breakpoint on \Magento\ImportExport\Model\Import\Entity\AbstractEntity::getBehavior
3. select "add update" import mode and import your csv

### Expected result

1. \Magento\ImportExport\Model\Import\Entity\AbstractEntity::getBehavior should return "add_update"

### Actual result

1. Import mode is changed to "append"

This happens because of the check that doesn't allow "add_update" as a valid method.

**Comment by okorshenko** [comment]
Hi @giacmir 
After some investigation we got the following results:
1. Create product which includes few categories, websites, custom options, tier prices, related products, up-sells, cross-sells
2. Create export file.csv with created product.
3. Then remove some relations for created product on admin side
4. Import (file.csv) using "Append" behavior
5. The data was added to the existing data for the existing entries in the database.
6. Remove product
7. Import (file.csv) using "Append" behavior
8. The data was added.
9. Try the same steps with "Add\Update" behavior.

Actual Result: Append and Add\Update have the same behavior.

What is your use case except debugging?

**Comment by giacmir** [comment]
Hi @okorshenko,

When I opened this issue I was developing an automated import procedure from an external source using the Import class as a library, so I was suprised to see that despite setting "add_update" as behaviour the import was actually running in append mode.

in `\Magento\ImportExport\Model\Import` I saw the following behaviours:

- append
- add_update
- replace
- delete

so I assumed that append and add_update should do different things.

based on naming my guess was that:

- append only adds new products while not touching the existing ones
- add_update adds new products and udates existing ones (that is what append actually does)
- replace recreates existing products (with new ids)
- delete deletes products

The fact that append actually behaves the same way as add_update seems wrong to me.

Moreover in \Magento\ImportExport\Model\Source\Import\Behavior\Custom, that is the sourcemodel of the backend selector you see that Magento is offering to set behaviour as add_update when later this behaviour is changed to append. And this is misleading.

It feels like there is something at least incomplete in the import engine if not wrong.

If it is ok that append and add_update do the same, why there are two behaviours?

I see that in the customer import add_update is used while in product import append is used to do the same thing. So I see three possible choices:

1. Differentiate append and add_update behaviour logic (more complex, but then you have a more flexible import system)
2. Change admin selector to directly use append (easy escape)
3. Merge usages of append and add_update to one single behaviour (a good compromise)

**Comment by okorshenko** [comment]
Hi @giacmir 
I believe this is a part of legacy code. 
The documentation shows this very clear:
Documentation: 
M1: http://docs.magento.com/m2/ce/user_guide/system/data-import.html
M2: http://docs.magento.com/m1/ce/user_guide/store-operations/data-import.html

We will take into account your comment. Thank you for feedback

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69910

**Comment by christian-forgacs** [comment]
I think the only thing thats missing is to allow BEHAVIOR_ADD_UPDATE too in \Magento\ImportExport\Model\Import\Entity\AbstractEntity->getBehavior() and its no legacy code...

https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1765

Here you find a difference between this two behaviors... With append you can't overwrite fields with empty values...

Similar you can't overwrite the values with 0 too because the clearEmptyData function check the value with the php empty function and int or string 0 is empty... And I think this is a big mistake too to use php empty function on this place...
