### ISSUE TITLE
CMS getList works not as expected

### ISSUE THREAD

**Issue by DavidLambauer** [magento/magento2#9311]
### Preconditions
1.  Magento EE 2.1.5

The `\Magento\Cms\Model\PageRepository::getList` says it will return `\Magento\Cms\Model\ResourceModel\Page\Collection` but what actually comes back is `\Magento\Framework\Api\SearchResults`. 

This is what's in the code:

``` PHP
/**
     * Load Page data collection by given search criteria
     *
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @param \Magento\Framework\Api\SearchCriteriaInterface $criteria
     * @return \Magento\Cms\Model\ResourceModel\Page\Collection
     */
    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $criteria)
    {
    ... skip unnecessary parts ...

        $searchResults->setItems($pages);
        return $searchResults; // \Magento\Framework\Api\SearchResults
    }
```

I am not entirely sure, what I would expect. A Collection or a SearchResult is excellent but nevertheless either the doc block is not correct or the returning value.

**Comment by DavidLambauer** [comment]
I am not able to receive any PageInterface with the API at the moment. For example:

``` PHP

    /**
     * GetCmsPageByNameService constructor.
     *
     * @param SearchCriteriaBuilder    $searchCriteriaBuilder Search Criteria Builder
     * @param PageRepositoryInterface  $pageRepository        Page Repo
     * @param StoreRepositoryInterface $storeRepository       Store Repo
     */
    public function __construct(
        SearchCriteriaBuilder $searchCriteriaBuilder,
        PageRepositoryInterface $pageRepository,
        StoreRepositoryInterface $storeRepository
    )
    {
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->pageRepository = $pageRepository;
        $this->storeRepository = $storeRepository;
    }

    /**
     * GET for Page API
     *
     * @param string $identifier Url Key
     * @param string $storeCode  Store Code
     *
     * @return PageInterface|array
     * @throws LocalizedException
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function getByIdentifier(string $identifier, string $storeCode) : PageInterface
    {
        $store = $this->storeRepository->get($storeCode);
        $criteriaBuilder = $this->searchCriteriaBuilder;
        $criteriaBuilder->addFilter('identifier', $identifier);
        $criteriaBuilder->addFilter('store_id', $store->getId());
        $criteria = $criteriaBuilder->create();
        $pageCollection = $this->pageRepository->getList($criteria);
        $pages = $pageCollection->getItems();

        return $pages;
    }
```


That's a nice little function which should get a PageInterface by searching it by identifier and storeCode.

**Comment by DavidLambauer** [comment]
Without the CMS API, the only chance to get a Page is by Collection. I guess this is not the recommended way, isn't it?

The method using a collection would look like this:

``` PHP
/**
     * @param string $identifier Identifier/Url-Key
     * @param string $storeCode  Store Code
     *
     * @return \Magento\Cms\Model\Page
     * @throws NoSuchEntityException
     */
    public function getByIdentifierWithCollection(string $identifier, string $storeCode) : \Magento\Cms\Model\Page
    {
        /** @var Store|StoreInterface $store */
        $store = $this->storeRepository->get($storeCode);

        /** @var Collection $collection */
        $collection = $this->collectionFactory->create();
        $collection->addFilter('identifier', $identifier);
        $collection->addFilter('store_id', $store->getId());
        $collection->addStoreFilter($store);
        $collection->setPageSize(1);

        /** @var Page $page */
        $pages = $collection->load();
        $page = $pages->getLastItem();

        return $page;
    }
```

**Comment by korostii** [comment]
Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should get noticed by Magento Inc. faster and will probably get a priority treatment. GitHub is intended for the Community Edition issue reports.

Additionally, the community pull requests are getting some attention lately. If you have the time to suggest a fix in such manner, that might also speed up the process of getting your suggestions included into the Magento.

**Comment by DavidLambauer** [comment]
@korostii Thanks for the advice. As I already mentioned, I am not quite sure if this is a bug or a miss implementation from my side. I want to have an array or a collection of specific PageInterfaces. This is not possible by API at the moment. May the community can help to make things more clear. Maybe there should be a new function getByIdentifier or something. 

At the time the behavior is clear, I will submit a PR.

**Comment by magento-engcom-team** [comment]
Hi @DavidLambauer 
There is already a Pull Request in progress which introduces these methods: https://github.com/magento/magento2/pull/10925
and GitHub issue with the list of duplicates: https://github.com/magento/magento2/issues/10414

We are closing this ticket for now, as a duplicate. You can join the discussion in the Pull Request or https://github.com/magento/magento2/issues/10414 if you wish.

Thank you.
