### ISSUE TITLE
Magento2  URL key for specified store already exists.

### ISSUE THREAD

**Issue by rajanzestard** [magento/magento2#9313]
### Preconditions

1. Magento ver. 2.1.3  

### Steps to reproduce

1.
2.

### Expected result

1. I have multiple store view I generate the product URL keys, on default store view all product URL will be generated but my other store views like the UK, GB there show me the error like **URL key for specified store already exists.**
2. I check in my url_rewrite table with that particular URL key but I found there is a no matching or similar URL like this.
3. I debug and track that file **(DbStorage.php)** I also get the data in **data** variable, in the data variable I get all the array of categories which have that product id, in that array that shows me the URL keys which will be generate and I take one by one URL key from request path key and check it in url_rewrite table I found there is no key like that but still it show me the error like **URL key for specified store already exists.** 

### Actual result

1. If URL key does not exist in the url_rewrite table it should be inserted in the table.

**Comment by orlangur** [comment]
Just analyze constraint violation message of DB adapter to understand where the collision comes from.

**Comment by korostii** [comment]
Not every error message you see is symptomatic of a bug. The exception you mention is in particular considered expected behavior if the URL key you're trying to save is in conflict with a different one. Basically, it just means "try another one".

Therefore, if you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by ericahoekerd** [comment]
Same on Magento 2.1.5 it should be possible to save products with the same name. Now we cannot assign these items to a website because we get the message: 'URL key for specified store already exists.'

**Comment by korostii** [comment]
@tinxit, you do know that you can edit the URL key manually and independently from the product name, right?

**Comment by ncotrona** [comment]
I've come across two options to resolve this this issue.

Resolution 1
https://github.com/magento/magento2/issues/2619
https://github.com/Iazel/magento2-regenurl

Resolution 2
Verify that the URL key attribute of your products does not contain the suffix. Then use this extension to regenerate the rewrites:
https://marketplace.magento.com/thlassche-regeneraterewrites.html

**Comment by Cassie2** [comment]
I have this issue with saving categories using version 2.1.6. The issue persists even after manually changing the URL.

**Comment by orlangur** [comment]
System behaves normally in current implementation if your data is valid in the first place. If https://github.com/magento/data-migration-tool produces invalid data in some cases, it should be reported.

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.
