### ISSUE TITLE
Cannot set Weight Type for product via API

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#9316]
When using REST API to update/insert a product there are no means to set weight type to dynamic or fixed.

### Preconditions
1. Magento 2.1.6 

### Steps to reproduce
1. REST API swagger does not seem to expose anything on this.  

Is there a way to update the weight type? Read that it can be done programmatically but wish to be able to set item "Item has no weight" when weight for item is zero.

**Comment by veloraven** [comment]
@georgios-2317 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by Maenz** [comment]
you must set "typeId": "virtual", then it works!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
