### ISSUE TITLE
Catalog price rule applied configurable products not show oldPrice in product list and Product Detail page

### ISSUE THREAD

**Issue by onepack** [magento/magento2#9322]
I have the exact same issue as closed issue #7624 on a project that has migrated data from a magento 1 store.

Catalog price rules or special prices applied to simple products related to the main configurable products do not show the oldPrice in product list and Product Detail page.

The products are always assigned later to the configurable products and not on the go while creating the configurable product.
When I apply a special price on a simple product or apply a catalog price rule the old price just never shows in the configurable product just the new discounted price of the related simple products.  
  
This way it is not clear for a customer that this is a special/ discounted price.
This happens in the grids and on a product detail page.
Only when I click a color option in the detail page the display of the price box gets updated with the text "regular: xx,xx" under the new "special price".

Magento version 2.1.6
PHP 7

The magento 2 shop is filled with migrated data from a magento 1 webshop.
The bug happens on old CFG's migrated from magento1 and new CFG's created in magento2.

The bug has been reported before in detail here: #7624

**Comment by onepack** [comment]
I checked the file:   vendor\magento\module-configurable-product\view\base\templates\product\price\final_price.phtml
There it was:
<span class="old-price sly-old-price no-display">

This styling makes the old price block invisible/ not even rendered on the frontend.
I removed the styling in my theme copy of this template file and after that the old price shows in the grids.

I need to check further how to fix the display. But at least it is clear now what happens.

Ps. I removed all the discounts from the simples that belong to one mother CFG and now it just keeps on showing "as low as" with an old "special" price that is no longer valid. Reindexing and clearing the cache doesn't seem to help.

**Comment by joebordo** [comment]
Hi, when i remove the styling it does show up, in the product page (detail page), but in the category page it still does not show up. Is it the same with you?

I can't believe it's june and it's not fixed yet.

**Comment by joebordo** [comment]
Hi, Line 22 in the the file: vendor\magento\module-configurable-product\view\base\templates\product\price\final_price.phtml

I replaced This: ` <?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>`
With this: `<?php if ($block->hasSpecialPrice()): ?>`

Now the old price shows up for me. (on the category page)
And for the styling (i just left class old-price" and now it shows up in the product page, (thanks to you).

hope it helps.

**Comment by magento-engcom-team** [comment]
@onepack, thank you for your report.
We've created internal ticket(s) MAGETWO-82627 to track progress on the issue.

**Comment by programmer2-techybirds** [comment]
How to show exclusive price instead of inclusive price in configurable product with tier price.
See below example for more clarification.

![](https://user-images.githubusercontent.com/32291934/32657424-b085ed1e-c63b-11e7-8ee5-66f5663705ad.png)

Here exclusive price is: 5.04
inclusive price is: 6.10

Now when select any single product from dropdown then calculation is upon inclusive price.
Need instead of that exclusive price instead of inclusive price.

Anyone have solution on this?

This is related to here: https://github.com/magento/magento2/issues/5097

**Comment by kfaer** [comment]
is this issue resolved?

**Comment by Brendonwbrown** [comment]
Used @joebordo 's solution - solved for me.

**Comment by darren-halo** [comment]
@joebordo's solution worked for me in 2.2.5. 

Although the change is on line 37 now.
Remove the classes 'sly-old-price  no-display' because these forces the old price to be hidden.
Override in file: THEME/Magento_ConfigurableProduct/templates/product/price/final_price.phtml
