### ISSUE TITLE
REST API Missing Product_Option values for Order Items in salesOrderManagementV1 and  salesOrderItemRepositoryV1

### ISSUE THREAD

**Issue by maultby** [magento/magento2#9326]
### Preconditions
Mag CE 2.1.5
PHP 5.6.19
MySQL 5.7.11 

### Steps to reproduce
In Mag Admin create new Bundle product, add Bundle Items to product, set  Ship Bundle Items option to Separately.
In Mag Admin create new Bundle product, add Bundle Items to product, set  Ship Bundle Items option to Together.
Create and Save a separate Sales Order for each newly added Bundle Product.
Use Swagger or another development app to call salesOrderRepositoryV1 GET /V1/orders for each Sale Order and return the response body. Note that the response body model shows product_option with Order Items structure. But the REST response does not contain the product_option property and its values. The same missing content occurs with salesOrderItemRepositoryV1 GET /V1/orders/items/{id}.
When catalogProductRepositoryV1 GET /V1/products/{sku} is called for the Bundle products the response body correctly shows custom_attributes{"attribute_code": "shipment_type","value": "0"}
With Mag V1.9 SOAP API product_options is populated and the critical value shipment_type is shown. This value is critical for controlling how the sales order is to be handled in our receiving systems.

### Expected result
REST API response body property product_option should be populated with values that include shipment_type.

### Actual result
REST API response body property product_option is not included in response body despite the model_schema showing it and the order containing bundle product with shipment_type.

It is not possible to work around this by getting the product details during order item get because the Ship Bundle Items option may not be the same as when the order was created.

This is a show stopper for our integration project.

**Comment by timtt-zz** [comment]
I am also seeing this issue with 2.1.4

**Comment by RomanKrut** [comment]
@maultby Hi. Thanks for your report. The internal ticket was created MAGETWO-70532

**Comment by phpsyscoder** [comment]
Same issue here.... does anyone have a workaround or "quick-fix"? Would be great. 
Thank you in Advance

**Comment by magento-engcom-team** [comment]
@maultby, thank you for your report.
We've created internal ticket(s) MAGETWO-70532 to track progress on the issue.

**Comment by anupwankhede** [comment]
Hi this is very important issue and we would appreciate if fixed in next 2.1 version :)

**Comment by crowebar** [comment]
Looks like it has been discussed previously 
https://github.com/magento/magento2/pull/9378

but rejected...
vrann suggests using GET V1/orders/items/:id request but that doesn't return them either...

**Comment by AlexandrKozyr** [comment]
managed on my project (2.1.9) by adding 
getProductOptions();
in my own version of vendor/magento/module-sales/Api/Data/OrderItemInterface

**Comment by magento-engcom-team** [comment]
Hi @maultby. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [b3a1cc66df511975ceec0d76447cbfadab35d7f8](https://github.com/magento/magento2/commit/b3a1cc66df511975ceec0d76447cbfadab35d7f8)
 - [7c6ecc33bf6d5707021548e0920650b7feec265c](https://github.com/magento/magento2/commit/7c6ecc33bf6d5707021548e0920650b7feec265c)

The fix will be available with the upcoming `2.3.3` release.

**Comment by philippta** [comment]
As mentioned in #9378 
> The constant KEY_PRODUCT_OPTION is defined as product_option, but the corresponding database field is named product_options (note the plural form).

This is still the case which means when requesting `/V1/order/items/:id` it does not return any product options. Is there anything I am missing?

**Comment by eastern-raviraj** [comment]
I am using the magento 2.3.5 but still I didnt see the product custom options in the response .
Can some one please confirm if this is fixed ?

**Comment by DaliTheCat** [comment]
Any news on this? Both the orders/{order_id} and the orders/items/{item_id} return a list of option_values but they are keys to another table. It would be ideal to get the option string.

"product_option": {
    "extension_attributes": {
        "custom_options": [
            {
                "option_id": "491",
                "option_value": "3057" // This should be the option string to show.
            },
        ],
    },
},

Or is there another way of retrieving this info for each order items?

**Comment by webgility-amazonapi** [comment]
Any update on product_option. We are also facing the same difficulty to get the product_option lables and selected values.

**Comment by mahmoud-abdelmalek** [comment]
reopen the issue

**Comment by mohammedTBB** [comment]
Still not getting product_options from the endpoint `orders/items/{item_id}` and `orders/{order_id}`
in magento 2.4.6-p4
Any fix for this?
