### ISSUE TITLE
Admin fields that use WYSIWYG don't pass the js validation 

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#933]
In the admin add forms, the fields that use the WYSIWYG do not pass the javascript validation until you click show/hide editor.  

**Preconditions:**
 - Magento2 0.42.0-beta2
 - CMS Editor enabled by default

**Steps to reproduce:**
 - Go to CMS->Pages->Add page
 - Fill in all required fields (including the content field)
 - Save Page

**Expected result:**
 - The paged is saved

**Actual result:**
 - There is js validation error message below the button `Show/Hide editor` - Bu the way, I think the error message should go under the editor not under the button.
 - Clicking on "Show/hide editor" once or twice allows me to save the form.

**Comment by mazhalai** [comment]
@tzyganu thank you for reporting this issue. We have created MAGETWO-33484 to track it internally.

**Comment by tzyganu** [comment]
I might add that on the beta11 the editor is not working at all. At least in the CMS->pages section.

**Comment by vpelipenko** [comment]
@tzyganu, issue is fixed. Please, look at the fix and provide your feedback.

**Comment by tzyganu** [comment]
@vpelipenko I confirm that this is fixed. Thank you.
