### ISSUE TITLE
Magento 2 Paypal Reauthorization Issue

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#9336]
1. Using Magento 2.1.6 CE
2. Go to **magento\vendor\magento\module-paypal\Model\Api\Nvp.php**
3.  

```
public function callDoReauthorization()
{
	$request = $this->_export($this->_doReauthorizationRequest);
	$response = $this->call('DoReauthorization', $request);
	$this->_import($response, $this->_doReauthorizationResponse);
}
```
Instead of `$request = $this->_export($this->_doReauthorizationRequest);`
It should Use `$request = $this->__exportToRequest($this->_doReauthorizationRequest);`

&

Instead of `$this->_import($response, $this->_doReauthorizationResponse);`
It should Use `$this->_importFromResponse($this->_doReauthorizationResponse, $response);`

Right would be

```
public function callDoReauthorization()
{
	$request = $this->_exportToRequest($this->_doReauthorizationRequest);
	$response = $this->call('DoReauthorization', $request);
	$this->_importFromResponse($this->_doReauthorizationResponse, $response);
}
```

@magento-admin @magento-team

**Comment by YevSent** [comment]
Hi, @shahankitb997, thanks for reporting. I've created internal ticket (`MAGETWO-67632`).

**Comment by ladle3000** [comment]
Is this issue what causes long checkout time with PayPal pro credit cards?

**Comment by shahankitb997** [comment]
Hi @snoroozi not sure about this. Using Paypal Express Checkout. But #9442 returns needed variable or not. need to check.

Thanks

**Comment by shahankitb997** [comment]
Hi @snoroozi While we do Reauthorization we have new Expiry Date of that Authorized Payment. Where Magento is storing that new expiry date? In `sales_payment_transaction` not able to find

**Is it keep tracking of old & new expiry date. Because you can reauthorize transaction multiple time.**

@magento-admin @magento-team

**Comment by YevSent** [comment]
Hi, @shahankitb997, the fix merged into the develop branch.

**Comment by ladle3000** [comment]
Is this any faster yet?
