### ISSUE TITLE
Migration magento 1.6.2 to magento 2.1.6 issue

### ISSUE THREAD

**Issue by karamdeep-singh** [magento/magento2#9339]
1. PHP 5.6.30
2. Mysql 5.6

After migration my category's not showing on front-end. pls help.

**Comment by tejasvyas1988** [comment]
Can you please explain with screenshots?

**Comment by orlangur** [comment]
With such explanation issue it not reproducible. Please debug on your side to see where the problem comes from, like some fatal error or invalid data in database.

There is a dedicated place for migration problems also: https://github.com/magento/data-migration-tool

**Comment by magento-engcom-team** [comment]
@rajansahota Please refer to https://github.com/magento/data-migration-tool for migration related issues.
Thank you.
