### ISSUE TITLE
if_module_enabled has no effect

### ISSUE THREAD

**Issue by fooman** [magento/magento2#934]
Regression from Magento 1: The system.xml entry [if_module_enabled](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/etc/system_file.xsd#L176) does not have an effect.

**Comment by antonmakarenko** [comment]
Confirmed. Thank you for report. We'll investigate the issue (MAGETWO-32443).

**Comment by mazhalai** [comment]
@fooman closing since this is has been fixed for a while.
