### ISSUE TITLE
Gift Options not showing for virtual products

### ISSUE THREAD

**Issue by giano574** [magento/magento2#9340]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.17
3. MySQL 5.6

### Steps to reproduce

1. Go to Stores > Configuration > Sales > Sales > Gift Options and set "Allow Gift Messages for Order Items" to "Yes".
2. Go to Stores > Configuration > Advanced > Advanced and enable Magento_GiftMessage if disabled.
3. Clear the cache.
4. Create a vritual product and make sure that "Allow Gift Message" in Gift Options is set to Yes.
5. Go to the frontend and add the new product to the cart.
6. Go to the shopping cart.

### Expected result

1. Gift options (message) should be available for the virtual product.

### Actual result

1. The gift options do not appear. 
2. If you change the product to a simple product by setting the weight and then clear the cache, the gift options will show, confirming that it just doesn't work for virtual products.

**Comment by VasylShvorak** [comment]
@giano574 Thanks for reporting this issue. We've created internal ticket MAGETWO-70224 to address this issue.

**Comment by magento-engcom-team** [comment]
@giano574, thank you for your report.
We've created internal ticket(s) MAGETWO-70224 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @giano574
Gift options are not displayed for virtual products by design. Virtual Product may be, for example, a downloadable item, which is not shipped to the customer, thus, there is no way to deliver a gift card as well.
Thank you for collaboration.

**Comment by adamzero1** [comment]
As this isn't a "bug" but we also wanted to use gift messages for virtual orders (orders only containing virtual products) we have made a module to allow this: [zero1/module-gift-message-for-virtual-orders](https://packagist.org/packages/zero1/module-gift-message-for-virtual-orders)
Hope this saves someone some time! :D
