### ISSUE TITLE
 CLI command tools for debugging Magento sql\app

### ISSUE THREAD

**Issue by maghamed** [magento/magento2#9341]
In order to help developers to work with the Magento, create new commands which will simplify the debugging of the application.

Link to the current DB logging tool - https://github.com/magento/magento2/issues/9200

**Request from Magento Performance Team:**
Here is some code we use internally for debugging sql\app which is nice to have in CLI command tool to make it multifunctional like a Swiss Army knife :)

- Adds executed sql queries to the bottom of page, so you can determinate during development which queries are executed on the page https://gist.github.com/mslabko/06b8dd2e80670f8e1abbf19f70ffd99f [how it looks](http://prnt.sc/ez40ex)

- Allows to add watches for specific classes, methods, etc and monitor elapsed time, cpu, sql and more https://gist.github.com/kandy/7ae16d74e2bdc35ffd7b524f089259c2
But this one require installed ``tideways`` extension (https://tideways.io/profiler/docs/setup/installation) and there is no open documentation how it works, so need to dig into [source code](https://github.com/tideways/php-profiler-extension/blob/master/tideways.c) for find some usefull features. [how it looks](http://prnt.sc/ez40mo)

**Comment by enrico69** [comment]
This would be an interesting feature. Recently I had to activate MySQL logs to filter what was going on.
I am volunteer to contribute.

**Comment by magento-engcom-team** [comment]
Pull Request has been merge. Closing the issue
