### ISSUE TITLE
Magento2 New product dates and special price date issue

### ISSUE THREAD

**Issue by sabarivelmks** [magento/magento2#9346]
Hi ,

 I am using Magento2.1.4 Enterprise Edition,I have some issues

1) I can't able to find the new product from date and to date fields  in the admin panel.so,i cant able to set the dates for the products which will be new for a certain period of time
2)When saving the special price date using schedule update ,i am getting the following error.please refer the attached images for the error messages.

I hope someone will help me for the above issues.Thanks in advance.
![new-product](https://cloud.githubusercontent.com/assets/26903925/25285279/4e86e2ac-26d7-11e7-81a0-edf9118a6a22.png)
![specialprice](https://cloud.githubusercontent.com/assets/26903925/25285280/4e923f30-26d7-11e7-9b51-e5ee544925f5.png)

**Comment by korostii** [comment]
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

Additionally, please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. GitHub is intended for the Community Edition issue reports.

**Comment by magento-engcom-team** [comment]
@sabarivelmks, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
