### ISSUE TITLE
Trying to update category through API saves under wrong store id

### ISSUE THREAD

**Issue by mattcoz** [magento/magento2#9349]
I can create a category just fine using the API, and when I do so the store id is correctly set to 0. When I try to update the category, it saves the updated information in new database entries using a store id of 1. Therefore, my changes are never used. I see these kinds of problems all the time and it is maddening.

### Preconditions
Magento 2.1.6
PHP 7.0.10

### Steps to reproduce
1. Create category using API
2. Update same category using API

### Expected result
Existing database entries should be updated.

### Actual result
New entries are created with the wrong store id.

**Comment by mattcoz** [comment]
Getting the same behavior when updating a product. This has essentially broken everything for us.

**Comment by mattcoz** [comment]
I've tried this with and without "single store mode" enabled and I get the same problem. It makes updates in the database and these updates aren't reflected on the website because of the wrong store_id.

**Comment by mattcoz** [comment]
This seems like it is related, I update the "visibility" in the admin and it is not reflected on the website either. It updates the value for store_id of 0, but the website seems to use the value of store_id of 1.

**Comment by magento-engcom-team** [comment]
@mattcoz, thank you for your report.
We've created internal ticket(s) MAGETWO-80962 to track progress on the issue.

**Comment by davidverholen** [comment]
@magento-engcom-team what would be the desired behavior here?

Currently the category values are saved always to store id 1 in a default installation (store resolved via storeManager in CategoryRepository::save()). When calling PUT /V1/categories/:id

1. Should the store be defaulting to 0?
2. Should it be possible, to set the store id. If yes, how would that look like? It could be an additional optional parameter. or maybe you've already had that problem solved somewhere else?

**Comment by mattcoz** [comment]
I would think the desired behavior would be to not have separate sets of values for a single store.

**Comment by davidverholen** [comment]
@mattcoz but you always have the default scope and the store scope. I would expect the api to change the default scope (store id: 0) if not specified otherwise.

Currently it changes the store scope (which is weird anyways, since we should not be in a frontend context when using the api). So this might also be a bug in the store manager, not sure yet

**Comment by mattcoz** [comment]
I guess I just don't understand the need for multiple scopes. I have a single store, I have it in single store mode. If I make changes, whether through the API or through the Admin, I want those changes reflected on the frontend.

**Comment by p-bystritsky** [comment]
Issue already fixed in 2.2-develop branch.
