### ISSUE TITLE
Error "No such entity with cartId =" when import order multi-store by code

### ISSUE THREAD

**Issue by tranductrong92** [magento/magento2#9357]
### Preconditions

1. Magento 2.1.6
2. PHP 7

### Steps to reproduce

1. import order multi-store by code

### Expected result

1. Import success

### Actual result

1. [Screenshot, logs]
Error "No such entity with cartId ="

**Comment by magento-engcom-team** [comment]
@tranductrong92, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
