### ISSUE TITLE
Incorrect type definition in "framework-attribute-interface" for JSON OpenAPI specification

### ISSUE THREAD

**Issue by nepda** [magento/magento2#9366]
I want to build a PHP client from the JSON schema.

### Preconditions
1. Magento ver. 2.1.6
2. Custom attributes configured / used

### Steps to reproduce
1. Download your JSON schema at `https://magento2.local/index.php/rest/[store_code]/schema`
2. Create a PHP client with swagger.io (e.g.: `curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"https://magento2.local/index.php/rest/[store_code]/schema"}' https://generator.swagger.io/api/gen/clients/php`
3. Create a product with the generated API (e.g.: https://gist.github.com/nepda/84d6d68fa92bb96457153b6304097258)
4. See the error
`PHP Notice:  Array to string conversion in /path/to/source/php-client/SwaggerClient-php/lib/ObjectSerializer.php on line 256
`

### Expected result
1. Get a PHP object with the created product.

### Actual result
1. When deserializing the result, you see an error (http://i.imgur.com/3GlkIkh.png)

I think the relevant part in the service specification is here:
`{
...

    "framework-attribute-interface": {
      "type": "object",
      "description": "Interface for custom attribute value.",
      "properties": {
        "attribute_code": {
          "type": "string",
          "description": "Attribute code"
        },
        "value": {
          "type": "object",
          "description": "Attribute value"
        }
      },
      "required": [
        "attribute_code",
        "value"
      ]
    },

}`

The `type` of the value should be `object` or something else.

**Comment by ooxi** [comment]
Any update on this? Swagger/OpenAPI does not support union types, Magento has to either switch to JSON schema or fix it's messages

**Comment by magento-engcom-team** [comment]
@nepda, thank you for your report.
We've created internal ticket(s) MAGETWO-83181 to track progress on the issue.

**Comment by ooxi** [comment]
~~@nepda Is there any way to see progress of MAGETWO-83181 from externally?~~

@magento-engcom-team Is there any way to see progress of MAGETWO-83181 from externally?

**Comment by nepda** [comment]
Nope, there were so many problems with Magento2 we stopped the entire migration.

**Comment by ooxi** [comment]
@nepda I wanted to ping @magento-engcom-team instead of you :-)

Sorry to hear you stopped the migration

**Comment by DavidLambauer** [comment]
Same problem here. Can fully understand @nepda. We try to minimize the usage of M2 as much as possible. Basically not production ready at all....

**Comment by stereoscope** [comment]
I stumbled over this issue myself which does not exist using soap-api. Is this going to be fixed soon? 
Is there a way to override the type by using openapi-generator?
