### ISSUE TITLE
Store URLs incorrect in email templates

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#9369]
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Add this link to Magento_Email/email/footer.phtml: `<a href="{{store url='privacy'}}">Privacy Policy</a>`
2.  Register or complete an order to send out a transactional email.

### Expected result

1. The "Privacy Policy" link should link to http://www.yourstore.com/privacy/

### Actual result

1. The "Privacy Policy" links to http://www.yourstore.com/privacy/index/index/, which results in a 404 error.

**Comment by thdoan** [comment]
UPDATE: As a workaround, I have to use `{{store url=''}}/privacy/` instead of `{{store url='privacy'}}` in email templates.

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70344 was created.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We've created internal ticket(s) MAGETWO-70344 to track progress on the issue.

**Comment by lewisvoncken** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
Hi @thdoan 
Could you please try the following: `<a href="{{store direct_url='privacy'}}">Privacy Policy</a>`
Please let me know if this will work for you

**Comment by magento-engcom-team** [comment]
@thdoan Closing this report now due to inactivity.
Please reopen if you have any updates

**Comment by gerben86** [comment]
Same issue overhere in Magento 2.2.3

`{{store url="customer_service"}}` leads to customer_service/index/index/

I'm now trying the direct_url, in case of an update I'll let you know.

**Comment by gerben86** [comment]
@okorshenko : The direct_url works in my case, so that looks like a workaround for this issue!
