### ISSUE TITLE
Video controls on Internet explorer

### ISSUE THREAD

**Issue by lauriecrt** [magento/magento2#9373]
### Preconditions
1. Magento 2.1.1 

### Steps to reproduce
1. set images plus a Youtube's video to a single product's visuals
2. On Internet explorer 11, go to the product page and play the video.
3. Try to click on the controls (increase, decrease sound or pause button)

### Expected result
1. The video should pause, or the sound should be increase or decrease, according to the control clicked

### Actual result
1. The video stop, the thumbnail of the video is shown 1 second, then the video is restarted from the beggining

I know that's not the last updates but i've read release notes since that version and there is nothing about this bug.

**Comment by magento-engcom-team** [comment]
@lauriecrt, thank you for your report.
We've created internal ticket(s) MAGETWO-80584 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @lauriecrt

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@lauriecrt thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
