### ISSUE TITLE
AbstractSource::getOptionText is giving wrong results when option is deleted

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#9374]
### Preconditions
1. Using Magento 2.1.5 on PHP 7.0

### Steps to reproduce
1. Execute `$attribute->getSource()->getOptionText($value);` on an attribute which works with option arrays, where `$value` is a non-existing option value.

### Expected result
1. `FALSE` should be returned, since that option doesn't exist anymore.

### Actual result
1. An array of a different option is being returned, because another value-label pair exists with the ID of that value, e.g. `Array([label] => "Label", [value] => 12)` for an option with ID 5.

This is happening because of lines 74-76 in [Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php](https://github.com/magento/magento2/blob/develop/app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php). However, I don't know what will happen if we just remove those lines.

**Comment by magento-engcom-team** [comment]
@redelschaap, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
