### ISSUE TITLE
Accept-Encoding in Varnish VCL does not include JS/CSS files

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9375]
### Preconditions
1.  Magento 2 (2.1.6 in this case, but any seems to apply)
 w/ Varnish FPC  (Varnish 4.0)

### Steps to reproduce
1. Enable Varnish FPC
2. Generate VCL (Varnish 4)
3. Check Compression filter section
`    # Compression filter. See https://www.varnish-cache.org/trac/wiki/FAQ/Compression
    if (req.http.Accept-Encoding) {
        if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
            # No point in compressing these
            unset req.http.Accept-Encoding;
        } elsif (req.http.Accept-Encoding ~ "gzip") {
            set req.http.Accept-Encoding = "gzip";
        } elsif (req.http.Accept-Encoding ~ "deflate" && req.http.user-agent !~ "MSIE") {
            set req.http.Accept-Encoding = "deflate";
        } else {
            # unkown algorithm
            unset req.http.Accept-Encoding;
        }
    }
`
4. You should see the file types lack JS files (and css)

### Expected result
It should include JS/CSS, I have read a bit and can't find a reason not to do this? Maybe there is.

So it becomes 
`if (req.url ~ "\.(css|js|jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {....`

### Actual result
1. Does not include JS/CSS , just ``if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {....``

I think this would be a simple fix to roll into the VCL generation for Magento 2. Trivial to edit it in manually.

**Comment by southerncomputer** [comment]
It's unsetting the compression flag for those file types!

if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") { 
# No point in compressing these 
unset req.http.Accept-Encoding; 

I'm pretty sure you want compression on for JS/CSS!

**Comment by magento-engcom-team** [comment]
@sylink, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
