### ISSUE TITLE
Admin UI grid report filters duplicates and unexpected results

### ISSUE THREAD

**Issue by cdiacon** [magento/magento2#9379]
### Preconditions

1. LAMP
2. Magento 2.1.6, php 5.6

### Steps to reproduce

1. Install magento 2.1.6
2. Clicked on Sales->orders admin grid filter and selected "Complete" mode
3. SQL will duplicate the conditions and may provide unexpected results after applying the filters

### Expected result
1. Selected order status "Complete" from the Sales->Orders

### Actual result
1.
```
## 13867 ## QUERY
SQL: SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` WHERE (`store_id` = '1') AND (`status` = 'complete') AND (`status` = 'complete') AND (`status` = 'complete') ORDER BY increment_id DESC
 LIMIT 20 
```

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70364 was created.

**Comment by magento-engcom-team** [comment]
@cdiacon, thank you for your report.
We've created internal ticket(s) MAGETWO-81446 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@cdiacon, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by emb-anuptiw** [comment]
Hi,
I am using 2.1.6 M2. And I am getting same issue. I am not getting your solution, Please provide me :)

Thanks
