### ISSUE TITLE
Admin grid will not filter the null values

### ISSUE THREAD

**Issue by cdiacon** [magento/magento2#9381]
### Preconditions
1. LAMP
2. Magento 2.1.6, php 5.6

### Steps to reproduce

1. Install magento 2.1.6
2. Filter the column values that are "null"
3. In case the column to filter is = "null" when applying the results, SQL will translate to equal

### Expected result

1. Results should filter null values
SELECT `main_table`.* FROM `dummy` AS `main_table` WHERE (`imported` is null) LIMIT 20

### Actual result
1.  
SQL: SELECT `main_table`.* FROM `dummy` AS `main_table` WHERE (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') AND (`imported` = 'null') LIMIT 20

**Comment by 1408sheva** [comment]
@cdiacon Please add more details to your description of the steps you followed when identifying this issue. Screenshots, Video or logs would be helpful, too.

**Comment by cdiacon** [comment]
Hi @1408sheva 

This is similar issue as https://github.com/magento/magento2/issues/9379#issuecomment-312197889 

But if I have a column with "NULL" values and want to filter the sql will be : 

```
imported = 'null'
```

instead of : 
```
imported is null
```

**Comment by 1408sheva** [comment]
@cdiacon Thanks for reporting this issue. 
We've created internal tickets MAGETWO-70529 and MAGETWO-70364 to address this issue.

**Comment by magento-engcom-team** [comment]
@cdiacon, thank you for your report.
We've created internal ticket(s) MAGETWO-70529 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
