### ISSUE TITLE
getDefaultBillingAddress always returns FALSE on customer_save_after event

### ISSUE THREAD

**Issue by rzinnatullin** [magento/magento2#9382]
### Preconditions
1. Magento 2.1.6
2. PHP 7.0.15-0ubuntu0.16.04.4
3. MySQL 5.7.17-0ubuntu0.16.04.1
4. Ubuntu 16.04
5. Apache/2.4.18 (Ubuntu)

### Steps to reproduce
1. Install the sample module [Foo.zip](https://github.com/magento/magento2/files/952380/Foo.zip)
2. Go to http://host/magento and click Create an Account
3. Create new account (suppose email is mail@mail.com)
4. Open system.log and locate "Customer mail@mail.com, has no default billing address" message. The message is correct.
5. Get back to Magento site (http://host/magento/customer/account/) and click Edit Address under Default Billing Address
6. Fill in any valid address, for example:
```
Phone Number: +123456789
Street Address: Address
City: Dulles
State/Province: Virginia
Zip/Postal Code: 20101
Country: United States
```
7. Click Save Address
8. Click Account Information, Edit Account Information area should open
9. Click Save

### Expected result
10. Open system.log again and locate "Customer mail@mail.com, **has** default billing address" message.

### Actual result
10. Open system.log again and locate one more "Customer mail@mail.com, **has no** default billing address" message.

This is the event handler code:
``` php
    public function execute(\Magento\Framework\Event\Observer $observer) {
        /* @var $customer \Magento\Customer\Model\Customer */
        $customer = $observer->getCustomer();
        
        $this->logger->info("Customer " . $customer->getEmail() . ", " . (empty($customer->getDefaultBillingAddress()) ? "has no" : "has") . " default billing address");
    }
```
Note that `$customer->getDefaultBillingAddress()` always returns FALSE.
To workaround the issue I reload the customer
``` php
$cust = $this->customerFactory->create()->load($customer->getId());
```

**Comment by YevSent** [comment]
Hi, @rzinnatullin, thanks for reporting.

I need some clarifications about this issue:

- The `customer_save_after` is it your custom event? Magento has only `customer_save_after_data_object`.
- Observer on the `customer_save_after_data_object` event receives `\Magento\Customer\Model\Data\Customer` NOT the `\Magento\Customer\Model\Customer`.
- The `\Magento\Customer\Model\Data\Customer` implements `\Magento\Customer\Api\Data\CustomerInterface` and has not `getDefaultBillingAddress` but has `getDefaultBilling` method.

**Comment by rzinnatullin** [comment]
Hi @joni-jones,
customer_save_after is generated by Magento 2.

Call stack:
![image](https://cloud.githubusercontent.com/assets/11244866/25393129/1cd233f4-29f4-11e7-85d2-9b7e21bcc370.png)

AbstractionModel.php/afterSave:
![image](https://cloud.githubusercontent.com/assets/11244866/25393203/48ab4dda-29f4-11e7-8d16-a351ec579ae0.png)

Also please refer https://mage2.pro/t/topic/1229

Please reproduce the issue using Foo module I've attached in the reproduction steps above.

**Comment by YevSent** [comment]
@rzinnatullin, I've tested on Magento 2.1.6 and develop branch, the customer billing address is present in observer on `customer_save_after` event.

**Comment by rzinnatullin** [comment]
Hi @joni-jones,
yes, by accident I tested the issue on Magento 2.1.2 (not 2.1.6 as I stated in the description). I've retested it in 2.1.6 and I can see customer billing address. Sorry for bothering you. Closing the ticket.
