### ISSUE TITLE
Images in Body not appearing once signed out of Magento back end

### ISSUE THREAD

**Issue by Alexgator32** [magento/magento2#9383]
Hi,

I am having an issue where I am adding images in the body of my description and I hit save and go to my website it appears perfect but when I sign out of the back end of magento and go to my site again the images look like this:

![image](https://cloud.githubusercontent.com/assets/26768495/25348849/97e6a74e-28ed-11e7-8ec4-bbf5f7c622b7.png)
![image](https://cloud.githubusercontent.com/assets/26768495/25348851/9aaa20dc-28ed-11e7-9a16-130b58a6537b.png)
 
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines-->

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by choukalos** [comment]
Hi @Alexgator32 can you fill out the bug report template?  In particular what version of Magento are you running?  Any particulars about adding images via admin (what size are they, any special format/process to the image, etc)?  Do you have any extensions that impact CMS functionality or images in Magento?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
