### ISSUE TITLE
Magento 2.1.6 shrunk my base images

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#9385]
### Preconditions

1. Magento 2.1.6
2. PHP 7.0.15

### Steps to reproduce

1. Update from Magento 2.1.4 to Magento 2.1.6 via the Web Setup Wizard
2. Update was successful
3. Looked at products and base image was much smaller than previously
4. Could not change the base image size back to normal within the gallery using etc>view.xml. Image size would increase but so would gallery size rendering the image out of alignment

### Expected result

1. Update shouldn't cause the base images to be smaller, because view.xml was not changed (screenshot 1)
![screenshot-1](https://cloud.githubusercontent.com/assets/19981272/25356900/fc6172dc-2909-11e7-9b5a-3e5442c94a34.jpg)

### Actual result

1. All base images are smaller (screenshot 2)
![screenshot-2](https://cloud.githubusercontent.com/assets/19981272/25356906/04770130-290a-11e7-8f21-5e9ed2b06a60.jpg)

2. Size of gallery stage went from 672x437 to 437x437 (screenshot 3)
![screenshot-3](https://cloud.githubusercontent.com/assets/19981272/25356912/0b3d37e6-290a-11e7-86ed-c7e4046207bb.jpg)

**Comment by tigerx7** [comment]
I ran into this issue myself recently... seems that Magento is now setting `<frame></frame>` to default to true now when this didn't used to be the case; at least from the version we updated from.

`<frame></frame>` adds white space around your image to force the exact width/height of the setting in view.xml while preserving aspect ratio. To not have Magento do this, you now have to include `<frame>false</frame>` within that image definition in view.xml

But there's a catch... there's a bug in Magento that reads `<frame>false</frame>` as a string when typecasting to bool, so it keeps it as true. Here's a more detailed discussion on that and how to best patch it: https://github.com/magento/magento2/issues/4622

After updating the view,xml and cleaning cache, you'll have to manually resize all your images with `bin/magento catalog:images:resize` Fair warning, it does take awhile depending on how many images you have.

**Comment by choukalos** [comment]
Tracking internally as MAGETWO-67805

**Comment by korostii** [comment]
@tigerx7, I think it's worth mentioning here that discussion under #4622 also suggests to include `<frame>0</frame>` as a workaround until that bug is fixed.

**Comment by aaronallen8455** [comment]
I'm also having this issue. Not only is the product image shrunken, but the thumbnails for the gallery are now vertically stretched and distorted.
I have tried adding `<frame>0</frame>` to all the product images in `view.xml` and running `bin/magento catalog:images:resize` but it doesn't change anything. This is in developer mode.

**Comment by aaronallen8455** [comment]
I also have this issue after updating to 2.1.6. 
In addition to shrunken product images, the gallery thumbnails are zoomed in so as to vertically fill the entire thumbnail space and are blurred as a result.
I tried adding `<frame>0</frame>` to all the product images in `view.xml` and ran the cache flush and image resize command but this doesn't seem to change anything with the product image or the thumbnails.

**Comment by tigerx7** [comment]
@aaronallen8455 did you apply commit https://github.com/magento/magento2/pull/7262/commits/1bbcff4eb26e63611b2372ff74084cb2afb62a8f? Unfortunately <frame>0</frame> on its own is also being read as true since "0" is typecasted directly from a string thus becomes true. Also make sure to flush the cache after the image resize command.

**Comment by jfrontain** [comment]
@pioneerathletics et al, please check out the Technical Bulletin we've just posted about this issue with 2.1.6. We hope it helps -- if not, send information my way, and we'll try again.

http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_216-imageresize.html

**Comment by aaronallen8455** [comment]
I finally got rid of the white border by going into cache management and using the 'Flush Catalog Images Cache' button before running the resize command. Just running the `cache:clean` command isn't enough.

**Comment by keithbentrup** [comment]
I posted [this](https://github.com/magento/magento2/issues/9395#issuecomment-299210346) on #9395, but it may help here, too.

**Comment by ps3z** [comment]
sites are looking ugly with it, we are waiting new release for fix the issue as soon as possible

**Comment by yumicom** [comment]
I have the same issue with bad resizing of additional small images on product page after upgrading to 2.1.6.  
In my  etc>view.xml :
image id="product_page_image_small" type="thumbnail"
width>50</width
height>50</height
frame>0</frame
/image
Image size is good only if width and height = 90.

**Comment by versdivers** [comment]
I have done everything by now. I tried to make chances to my view.xml. I tried to adjust the helper. I applied the patch and everything. Just nothing works! This is really really horrible. If you have a fix ready just implement it and release it under 2.1.7...

**Comment by margo-nik** [comment]
@jfrontain Agrees with the comment above. After applying the patch and editing view.xml still does not work.

**Comment by luismaldonadov** [comment]
I've just donwloaded the patch but i dont know how to apply it. I've tried giving it permissions to execute and with bash, but it seems that is not a bash script. Can anyone give instructions?.

Thank you.

EDIT

I've just realized is a git patch. I've run this command in the root folder

git apply --stat MAGETWO-67805-2017-05-17-03-04-03.patch

I dont know if its correct.

**Comment by heyepic** [comment]
I've tried everything and cannot fix this - and worse, I'm going live with a site soon. Is there a general ETA of when this will be addressed? Seems like a big issue.

**Comment by mzeis** [comment]
Magento just released 2.1.7 with a "reversion of the changes to image resizing that we introduced in 2.1.6": http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.html

Can you please check if the problem is gone in 2.1.7? Thanks!

**Comment by veloraven** [comment]
@pioneerathletics I'm closing this issue as it was fixed in Magento 2.1.7.
If you still experience this problem please create new GitHub issue.
