### ISSUE TITLE
Wrong Product Pricing in Product Catalog. needs urgent update

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#9388]
### Preconditions

1. After I upgraded my store to Magento 2.1.6, I see there is an issue with product pricing displayed in Product Details page.  In my product category page, products display the price correctly,

I use the different currency in my store, I have added the products in my Magento backend in South Korean Won currency. (₩) 

For Example,
In my product category listing page, a product is shown like
Phone - Cost $152.10

After I click on the product, it takes me to the product details page, now the product price had changed to $0.14

### Steps to reproduce

1. I am using Magento 2.1.6 with Ultimo Theme, I have checked with default theme also, the same issue is there.
2. Add different store currency in my case, SKW(₩), USD, etc. 
2. Create a Simple Product and add the price of the product in SKW, and add custom options like color, size to it.
3. Now go to the product category page, and click on the product you may see that product pricing had changed. 

### Expected result

1. Product Price changes ( in category page the price is listed correct, but when we click on them and we are taken to product details page, now you can see the price of the product had been changed. )

**Comment by userseven77** [comment]
I have the same issue, I'm also using infortis ultimo theme but apparently this doesn't concern them but is a magento issue (according to infortis support).

My problem manifests on any currency that is not the base currency (that seems not affected). Only in the product page the price is CHANGED "live" after the page loads to an incorrect amount. If the customer adds the product to the shopping cart then the price in the shopping cart will be correct, also in the products gallery the prices are correct - this is simply a matter of some script corrupting the displayed number, the numbers run in back-end are correct. If you reload the page you can also clearly see the correct price shown initially and then getting changed.
I've contacted infortis concerning the only scripts that seem linked to the pricebox div (priceReload, priceUpdate seem to affect it) but they pointed out that these methods come from magento directly and can't help.

The problem manifested with magento 2.1.4 and 2.1.6 (no change after update). Infortis ultimo 2.4
.0

_LATER EDIT: By the way, I forgot to point out that the price that gets shown in the end isn't just a random number. It's in fact derived from applying the currency rate against the price that was already calculated by applying the currency rate to the base currency. So in effect it's the base currency price with the currency rate applied TWICE._

Image showing the discrepancy between the data-price-amount (the correct price) and the actual text shown after being altered.
![magento-price-issue](https://cloud.githubusercontent.com/assets/28558674/25841748/03a81c5c-34aa-11e7-8ff4-e921e51e1125.jpg)

**Comment by ebofi** [comment]
Got a fix for this
On Your  View.php in vendor\magento\module-catalog\Block\Product\view,php

on line 237, replace the config array with

`

$config = [
            'productId' => $product->getId(),
            'priceFormat' => $this->_localeFormat->getPriceFormat(),
            'prices' => [
                'oldPrice' => [
                    'amount' => 
                        $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue()
                    ,
                    'adjustments' => []
                ],
                'basePrice' => [
                    'amount' => 
                        $product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount()
                    ,
                    'adjustments' => []
                ],
                'finalPrice' => [
                    'amount' => 
                        $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue()
                    ,
                    'adjustments' => []
                ]
            ],
            'idSuffix' => '_clone',
            'tierPrices' => $tierPrices
        ];

`

**Comment by userseven77** [comment]
So you basically just removed `$this->priceCurrency->convert(...)` from oldPrice, basePrice, finalPrice?
Did you figure out this or is it an "official" fix from magento?

**Comment by ebofi** [comment]
:)

**Comment by userseven77** [comment]
Yup. After flushing the cache the problem disappeared. Thanks.

**Comment by ebofi** [comment]
thanks bro for getting me back...

We are powered by G Suite, Are't you?
<https://gsuite.google.com/intl/en_in/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=hGHC7ABF>
