### ISSUE TITLE
Cannot extend layout in product page of child theme

### ISSUE THREAD

**Issue by besteven** [magento/magento2#9390]
### Precondtions
develop branch

### Steps to reproduce
I've created a 'parent' theme that extends from luma & 2 child themes (child-a & child-b) extends from 'parent' theme
In 'child-b' i've created: 
 - etc
 - media
 - composer.json
 - registration.php
 - theme.xml
 - Magento_Theme/layout/default.xml

After that i created category B and set it's theme to 'child-b'

### Expected result
1. the code in default.xml of 'child-b' effect on category B & products on category B

### Actual result
1. the code in default.xml of 'child-b' effect ONLY on category B, NOT products on it

I've tried to create other layout file such as catalog_product_view.xml ... but still not work.
Please help me,
Best regard!

**Comment by magento-engcom-team** [comment]
@besteven, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
