### ISSUE TITLE
Broken DB compatibility in image cache

### ISSUE THREAD

**Issue by xpoback** [magento/magento2#9392]
I know that this issue doesn't follow the guidelines, but whatever.
I would like to ask you guys to pay more attention on the things you do and, especially, release.

You've declared `_fileExists()` in `app/code/Magento/Catalog/Model/Product/Image.php`, why not to use it everywhere in the class.
Just a little change, absence of which creates big problems to me and other people, that want to save their cache images not on the same server.
https://github.com/magento/magento2/commit/3e3e4f243945a9079f4ac3e2dead1d2e59d0d10f

**Comment by korostii** [comment]
Completely agree with the emotional part, however you could've also create a pull request into 2.1-develop as well, you know.
Just saying :)

**Comment by magento-engcom-team** [comment]
@xpoback Please feel free to create a Pull Request which fixes this issue.

**Comment by magento-engcom-team** [comment]
@xpoback thank you for report. We will consider your suggestion. Also, feel free submit a pull request if this is a critical issue for you

**Comment by xpoback** [comment]
The task, I was working on, has been finished long ago even with the problem described.
Since it wasn't a critical issue (just another plugin was needed), no PR will be created (cuz I'm lazy to look up what I did in April). 
Thanks for your time and have a good day.
