### ISSUE TITLE
Error Creating a new product in 2.1.6

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#9394]
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento_swift`.`hsfd_ae_forms_product_enquiry_config`, CONSTRAINT `ae_forms_product_enquiry_config_ibfk_2` FOREIGN KEY (`enquiry_product_id`) REFERENCES `catalog_product_entity` (`entity), query was: INSERT INTO `hsfd_ae_forms_product_enquiry_config` (`enquiry_product_id`, `enquiry_form_id`) VALUES (?, ?)

Magento 2.1.6
PHP 7
10.0.28-MariaDB-0+deb8u1 (Debian)

### Steps to reproduce
Installed Magento 2.1.5 (resulted in the same error, while creating a new product).
Upgraded to Magento 2.1.6
Gives the below error :
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento_swift`.`hsfd_ae_forms_product_enquiry_config`, CONSTRAINT `ae_forms_product_enquiry_config_ibfk_2` FOREIGN KEY (`enquiry_product_id`) REFERENCES `catalog_product_entity` (`entity), query was: INSERT INTO `hsfd_ae_forms_product_enquiry_config` (`enquiry_product_id`, `enquiry_form_id`) VALUES (?, ?)

It should create a product successfully.
![error create prod](https://cloud.githubusercontent.com/assets/19605497/25385259/666be084-29bb-11e7-9b9c-088d27fabd49.PNG)

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment]
> `hsfd_ae_forms_product_enquiry_config`

I don't think that's Magento's own DB table. You seem to have some kind of 3rd-party modules installed (presumably generating some kind of contact form)? 
You could confirm that it's the cause of the issue by temporarily dsabling that module.
If that's the case, I would suggest that you contact the supplier of the module, maybe they'll be able to provide you with an updated\fixed code.

**Comment by nmallepally** [comment]
@korostii 
Many thanks it solved the issue after I uninstalled the extension, it is coming from a faq extension.
I will close it.
