### ISSUE TITLE
EavSetup can remove attribute group and then get that group even though it is deleted

### ISSUE THREAD

**Issue by DarylForza** [magento/magento2#9397]
If you use the EavSetup to removeAttributeGroup(), you can then call addAttributeGroup() with the same group-code, and it will return you the id of the deleted group.

This seems to be because the SetupCache retains the deleted attribute-group cached values even though they are deleted from the database.

### Preconditions
Magento 2.1.3 CE. PHP 7.

### Steps to reproduce
1. In InstallData, add an attribute group for an entity with a code, like "my_group".
2. In InstallData, get the newly added group id by its code, and remove that group by Id.
3. In InstallData, try to re-add the group -- you'll be given the id of the deleted group.

### Expected result
When you delete a group and re-add it, you should have the old group deleted and the new group added.

### Actual result
When you delete a group and try to re-add it, you end up with the old group deleted but no new group added.

### Reason this happens
This is because the cache can be keyed by the group-id or the group-code. When you delete a group some items are left behind in the setup-cache causing unexpected behavior. I've seen items left in the cache that are in the format data['eav_attribute_group'][group-id][group-code]

I have been able to work around this bug by doing the following after I delete an attribute group:
```
$attributeGroupId = $eavSetup->getAttributeGroupId($entityTypeId, $attributeSetId, self::ATTR_GROUP_CODE);
$eavSetup->removeAttributeGroup($entityTypeId, $attributeSetId, $attributeGroupId);
$eavSetup->getSetup()->getSetupCache()->remove('eav_attribute_group', $attributeSetId, self::ATTR_GROUP_CODE);
$eavSetup->getSetup()->getSetupCache()->remove('eav_attribute_group', $attributeSetId, $attributeGroupId);
```

I suspect the same problem might exist for attribute-sets as well, and perhaps attributes, as these items can be gotten (using the get-methods) by id/name/code depending on the object.

**Comment by magento-engcom-team** [comment]
@DarylForza, thank you for your report.
We've created internal ticket(s) MAGETWO-80945 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@DarylForza, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
