### ISSUE TITLE
MAGENTO 2.1.3

### ISSUE THREAD

**Issue by mariorodriguesnt** [magento/magento2#9398]
MAGENTO 2.1.3

Hey guys, pleased to contact u all.

My question is: When I add a category in Admin panel it appears in Menu bar, fine.. But is there a way I could add annother button that takes me to a non-product page, like "home"?

Other question:

When I have MANY categories, is there a way I could break them into columns? When I try to see it in the main page it appears a big list n I have to scroll all the way down the page to see them all.

That's all I guess, thanks in advance!

**Comment by JDavidVR** [comment]
this comment looks more for magento forums or maybe stackoverflow

https://community.magento.com/
http://magento.stackexchange.com/

a quick answer for your question is, no you can't customize menu so you need a module you can look for one in market place https://marketplace.magento.com/

**Comment by choukalos** [comment]
Closing since this is a question.  Please move to forum if you'd like to continue the discussion.
