### ISSUE TITLE
Configurable product is not working in Magento 2.1.3  

### ISSUE THREAD

**Issue by manaspratim** [magento/magento2#9405]
Its a huge issue, 
Configurable product is not working in Magento 2.1.3 , Need to fix as soon as possible.

Thanks

**Comment by ghost** [comment]
Hi,
Can you provide more details?  I am also working with magento 2.1.3 and I can create a configurable product (I can't display it in front end, but I don't know yet if it's an issue with magento or a problem between my computer and my chair).

**Comment by manaspratim** [comment]
Hi
Same problem here in in magento 2.1.3. I can create it from admin panel but when I am going see it through front end site broke all the site, And then I have to go back to admin panel and delete configurable products or disable it. 

Its a serious issue in Magento 2.1.3

Thanks

**Comment by cizgidekiadam** [comment]
Creating configurable products need to be indexing. 
Blank page shown in listing or product pages until indexer complete it work.

**Comment by veloraven** [comment]
@manaspratim please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment]
@manaspratim thank you for your report.
We were not able to reproduce this issue by following the steps you provided on latest release. Please, try 2.1.8
