### ISSUE TITLE
SearchCriteria in AttributeRepository does not allow `OR` requests

### ISSUE THREAD

**Issue by JulienPradet** [magento/magento2#9406]
### Preconditions
I am using Magento 2.1.6

### Steps to reproduce
1. Use the sample datas
2. Request via the API the following request :
/rest/V1/products/attributes?searchCriteria[filter_groups][0][filters][0][field]=description&searchCriteria[filter_groups][0][filters][0][value]=color&searchCriteria[filter_groups][0][filters][0][condition_type]=in&searchCriteria[filter_groups][0][filters][1][field]=attribute_id&searchCriteria[filter_groups][0][filters][1][value]=93&searchCriteria[filter_groups][0][filters][1][condition_type]=in

(meaning `attribute_code IN ('color') OR attribute_id IN (93)`)

### Expected result
1. Receive the list of items with the color attribute AND the description attribute.

### Actual result
1. The list is empty.

This is broken because of this function `\Magento\Eav\Model\AttributeRepository::addFilterGroupToCollection`.

However, in `develop` this behavior was changed since August ([`a7a5a41bd0f342502e272b3e5b36f326964e7a7b`](https://github.com/magento/magento2/commit/a7a5a41bd0f342502e272b3e5b36f326964e7a7b#diff-f50c64828adc6d8b7238237eeafc81f3)) but is not yet released, even in the latest tag I checked.

I'm opening this issue because I was wondering if this is planned anytime soon ?
If nothing is planned yet, would you like a PR that fixes it temporarly in `2.1-develop` so that the problem is solved in the next release ?

Have a nice day :wave:

**Comment by korostii** [comment]
I am not an employee of Magento Inc., but it seems that the related changes seem to be marked as backward-incompatible and planned for 2.2, please see [here](https://github.com/magento/devdocs/blob/develop/guides/v2.2/release-notes/backward-incompatible-changes.md#changes-in-repositories) for some general information

**Comment by JulienPradet** [comment]
Thank you for the link ! Didn't manage to find it.

I guess I will just need to be patient then. :slightly_smiling_face:
