### ISSUE TITLE
Refactor PaymentTokenFactory interface in Vault\API

### ISSUE THREAD

**Issue by maghamed** [magento/magento2#9407]
The current problems I see are next:
- Usage of Inheritance Based API for AbstractPaymentTokenFactory and its successors
- Violation of Single Responsibility principle by **PaymentTokenFactoryInterface** which contains two methods create() and getType(). And getType has service purposes only (aka protected contract), it's not used by business logic from outside, but instead used for setting correct type for Model\PaymentToken during the instantiation
https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Vault/Model/AbstractPaymentTokenFactory.php#L40
- This code 
```php
        $paymentToken = $this->objectManager->create(PaymentTokenInterface::class);
        $paymentToken->setType($this->getType());
```
also has a "smell" , because in our case instance of Model\PaymentToken doesn't have sense without setting type. But we could potentially create Model\PaymentToken object not specifying one. If we will inject dependency on Model\PaymentToken in Constructor DI of some other object.

So, what I propose to do:
1. Let’s accept $type as a constructor parameter and set it within constructor method of Model\PaymentToken, to make sure that our object is well formed and valid just after instantiation.
2. Let's introduce new interface  
```php
<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\Vault\Api\Data;

/**
 * Interface PaymentTokenFactoryInterface
 */
interface PaymentTokenFactoryInterface
{ 
    /**
     * Create payment token entity
     * @param $type account|card
     * @return PaymentTokenInterface
     */
    public function create($type);
}
```
which will have correct factory contract. Without getType() method, and create method which accepts type as parameter.

3. Old implementation will proxy call to new one like this:
```php
/**
 * Class CreditCardTokenFactory
 * @api
 * @deprecated 
 * @see PaymentTokenFactoryInterface
 */
class CreditCardTokenFactory extends AbstractPaymentTokenFactory
{
    /**
     * @var string
     */
    const TOKEN_TYPE_CREDIT_CARD = 'card';


    public function __construct(
        ObjectManagerInterface $objectManager
        PaymentTokenFactoryInterface $newTokenFactory = null
    ) {
        $this->objectManager = $objectManager;
        $this->tokenFactory = $newTokenFactory ?: \Magento\Framework\App\ObjectManager::getInstance()
            ->get(PaymentTokenFactoryInterface::class);
    }

    /**
     * Create payment token entity
     * @return PaymentTokenInterface
     */
    public function create()
    {
        return $this->tokenFactory->create($this->getType());
    }
    /**
     * @inheritdoc
     */
    public function getType()
    {
        return self::TOKEN_TYPE_CREDIT_CARD;
    }
}
```
 
Doing all of the above, we wouldn't introduce Backward Incompatible changes, and will introduce useful refactoring which moves our Vault Token Factory interface to the desired vision. So, all the 3rd party devs will need to make an upgrade just once.

https://github.com/magento/magento2/pull/9306

**Comment by dverkade** [comment]
Hey @maghamed,

We still have tests failing. That's because we have functions calling the paymentTokenFactory create function with an array. See this function in the PaymentTokenManagement class for instance: 

    public function getByPublicHash($hash, $customerId)
    {
        $tokenData = $this->paymentTokenResourceModel->getByPublicHash($hash, $customerId);
        $tokenModel = !empty($tokenData) ? $this->paymentTokenFactory->create(['data' => $tokenData]) : null;
        return $tokenModel;
    }

So this is now failing. I think it's better to keep this behaviour and change the create function in the AbstractPaymentTokenFactory to something like this: 

    /**
     * Create payment token entity
     * @return PaymentTokenInterface
     */
    public function create()
    {
        return $this->paymentTokenFactory->create(['data' => ['type' => $this->getType()]]);
    }

And then the PaymentTokenFactory should be something like this: 


    public function create($data = null)
    {
        if ($data !== null && in_array($data, 'type') && !in_array($data['type'], $this->tokenTypes, true)) {
            throw new \LogicException('There is no such payment token type: ' . $type);
        }

        return $this->objectManager->create(PaymentTokenInterface::class, $data);
    }

**Comment by maghamed** [comment]
Hey @dverkade ,

sorry for late response. Just noticed that you pointed out this breakage of tests in GitHub issue, but not on Pull Request.

You correct that there is an issue which leads to breaking existing functionality. 
This happens, because we have code you mentioned above.
 ```php
   public function getByPublicHash($hash, $customerId)
    {
        $tokenData = $this->paymentTokenResourceModel->getByPublicHash($hash, $customerId);
        $tokenModel = !empty($tokenData) ? $this->paymentTokenFactory->create(['data' => $tokenData]) : null;
        return $tokenModel;
    }
```

In this code problem is that `paymentTokenFactory` is an instance of PaymentTokenFactory, which is code generated previously. But in our implementation we've added PaymentTokenFactory
https://github.com/magento/magento2/pull/9306/files#diff-4903037ef642a426d5903efb39baf4e5

And it's interface of create method is next:
 ```php
public function create($type = null)
 ```

Agree that we need to preserve this behavior for Backward Compatibility.
To do so, we need to handle a possibility of an `array` passing into PaymentTokenFactory
```php
    public function create($type = null)
    {
        /**
         * This code added for Backward Compatibility reasons only, as previous implementation of Code Generated factory
         * accepted an array as any other code generated factory 
         */
         if(is_array($type)) {
             return $this->objectManager->create(
                 PaymentTokenInterface::class,
                 ['data' => $type]
             );
         }       

         if ($type !== null && !in_array($type, $this->tokenTypes, true)) {
             throw new \LogicException('There is no such payment token type: ' . $type);
         }
 
         return $this->objectManager->create(
             PaymentTokenInterface::class,
             ['data' => [PaymentTokenInterface::TYPE => $type]]
         );
     }
```

**Comment by dverkade** [comment]
Hi @maghamed,

I have made the latest changes to this PR and it is now passing.

**Comment by okorshenko** [comment]
Pull Request has been merged https://github.com/magento/magento2/pull/9306
