### ISSUE TITLE
Low stock report is showing empty grid in magento 2.1.6

### ISSUE THREAD

**Issue by ram10raj** [magento/magento2#9408]
I have installed the last version of magento 2.1.6 CE . I have created product with  0 qty and checked in "Report >> Products >> Low stock "grid is showing empty.

### Preconditions
1. Magento 2.1.6
2.PHP 5.6.28
3.Mysql  5.6

### Steps to reproduce
1. Login to admin panel 
2.  Create product with qty as 0 (Product >> Catalog >> Create new Product)
3. Check the low stock report ("Report >> Products >> Low stock)

![product](https://cloud.githubusercontent.com/assets/5101136/25440603/91b63d2c-2abd-11e7-9a3f-a1a933ec3b02.png)
### Expected result
1. It will show the grid with value.

### Actual result
1. showing as empty gird

![lowstock](https://cloud.githubusercontent.com/assets/5101136/25440616/9b56c824-2abd-11e7-931b-97712878b27a.png)

**Comment by santhoshp** [comment]
I'm working on this

**Comment by ram10raj** [comment]
@santhoshp  any update on this issue ?
I'm waiting for the updated code for lowstock report.

**Comment by ngz82** [comment]
@santhoshp I'm also after an update.

Is this issue related to the low-stock notification emails also not working?

**Comment by ngz82** [comment]
@ram10raj   if you change Scope to just the website you want, does it work?

We had the same issue and I found today by changing scope to "Main website" and it all shows up as expected.

Export still fails though - as referenced in #7075

**Comment by ram10raj** [comment]
@ngz82 after changing website level it was working but default it showing empty gird.
@santhoshp please fix and update the patch. report is showing empty page.

**Comment by miguelbalparda** [comment]
There is a proposed fix for this [here](https://github.com/magento/magento2/pull/10935), can you check it and report back?

**Comment by magento-engcom-team** [comment]
@ram10raj, thank you for your report.
We've created internal ticket(s) MAGETWO-80807 to track progress on the issue.

**Comment by esteban-serfe** [comment]
Hi, I've been able to reproduce this on 2.2.4 Enterprise. 

Using the fix from PR [#14705](https://github.com/magento/magento2/pull/14705) were able to fix the issue. 

Is there a plan to have this merged into next release?

**Comment by mdxacura2011** [comment]
#cdkyiv2019

**Comment by magento-engcom-team** [comment]
@mdxacura2011 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mdxacura2011** [comment]
Cannot reproduce on 2.3-develop branch 
Event: cdkyiv2019
