### ISSUE TITLE
rest-V1-order-orderID-ship - Error Please enter a tracking number

### ISSUE THREAD

**Issue by gweeble** [magento/magento2#9416]
### Preconditions
1. Magento version 2.1.5, PHP Version 7.0.17, Mysql version: 5.6.35-81.0 Percona Server (GPL), Release 81.0, Revision c96c427

### Steps to reproduce
1. Get Token for submission
2. Get order information
3. Set all fields from data collected and information from Shipments system as per documentation
http://devdocs.magento.com/guides/v2.1/mrg/ce/Sales/services.html
Data Collected:
`(
    [items] => Array
        (
            [0] => Array
                (
                    [order_item_id] => 18395
                    [qty] => 1
                )
            [1] => Array
                (
                    [order_item_id] => 18396
                    [qty] => 1
                )
        )
    [tracks] => Array
        (
            [track_number] => 60-082-03-25135-0
            [title] => RM - First Class
            [carrier_code] => custom
        )
)
`
4. Send all data to rest/V1/order/orderID/ship
5. Get error  "...Shipment Document Validation Error(s):\nPlease enter a tracking number..."

/**** FULL CODE ****/
`//retrieve Token from the website
$userData = array("username" => "XXXX", "password" => "XXXX");
$ch = curl_init("https://www.XXXXX.co.uk/index.php/rest/V1/integration/admin/token");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($userData));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Content-Lenght: " . strlen(json_encode($userData))));

$token = curl_exec($ch);
$orderEntityID =  "12650";

//Get the Order Information from $orderEntityID
$ch = curl_init('https://www.XXXXX.co.uk/index.php/rest/V1/orders/' . $orderEntityID);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));

//retrieve order Information from the result
$result = curl_exec($ch);

$result = json_decode($result);
$limit = $result->total_item_count;
$orderIncrementId = $result->increment_id;

//Now get all the item information
// Set the counter
if ($limit === "") {
		$i = 0;
	} else if ($limit === '1') {
		$i = 0;
		$limit = 0;
	} else {
		$i = 0;
		$limit = $limit - 1;
	};
	
$upload = array();

//iterate through records
while ($i <= $limit) {
	$orderItemId{$i} = $result->items[$i]->item_id;
	$orderProductId{$i} = $result->items[$i]->product_id;
	$orderItemSku{$i} = $result->items[$i]->sku;
	$orderItemQty{$i} = $result->items[$i]->qty_ordered;
	$upload2 = ['order_item_id' => $orderItemId{$i}, 'qty' => $orderItemQty{$i} ];
	$upload['items'][$i] = $upload2;
	$i++;
}

$upload1 = [ 'track_number' => '60-082-03-25135-0', 'title' => 'RM - First Class', 'carrier_code' => 'custom']; 
$upload['tracks'] = $upload1;
print_r ($upload);

//Post the Order item Updates
$ch = curl_init('https://www.XXXXX.co.uk/index.php/rest/V1/order/' . $orderEntityID . '/ship');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($upload));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));

//retrieve order Information from the result
$result = curl_exec($ch);
print_r($result);`

/**** Full Response ****/
`{"message":"Shipment Document Validation Error(s):\nPlease enter a tracking number.\nPlease enter a tracking number.\nPlease enter a tracking number.","trace":"#0 [internal function]: Magento\\Sales\\Model\\ShipOrder->execute(12650, Array, false, false, NULL, Array, Array, NULL)\n#1 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#2 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"}`

### Expected result
1. Should return parent_id object of succesful update
2. Update information in shipment information

### Actual result

1. [Screenshot, logs]
`Array
(
    [items] => Array
        (
            [0] => Array
                (
                    [order_item_id] => 18395
                    [qty] => 1
                )

            [1] => Array
                (
                    [order_item_id] => 18396
                    [qty] => 1
                )

        )

    [tracks] => Array
        (
            [track_number] => 60-082-03-25135-0
            [title] => RM - First Class
            [carrier_code] => custom
        )

)
{"message":"Shipment Document Validation Error(s):\nPlease enter a tracking number.\nPlease enter a tracking number.\nPlease enter a tracking number.","trace":"#0 [internal function]: Magento\\Sales\\Model\\ShipOrder->execute(12650, Array, false, false, NULL, Array, Array, NULL)\n#1 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#2 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 \/var\/www\/vhosts\/weedfabricdirect.co.uk\/htdocs\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"}`

**Comment by magento-engcom-team** [comment]
@bendraxguy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
