### ISSUE TITLE
Region field sometimes above other fields in billing form

### ISSUE THREAD

**Issue by Danielc3** [magento/magento2#9420]
### Preconditions
1. Magento 2.1.5

### Steps to reproduce
1. Proceed to checkout.
2. Proceed to billing step.
3. Re-iterate this process a few times.

### Expected result
1. The fields are consistently in the same location each time. 

### Actual result
1. The county field is shown above the first name field on occasional page reloads. This would appear to be a JS race condition, see below.

This is a duplicate of #5849 which was closed down without being fixed. That ticket complained about the sort order generally not having the desired effect within the checkout, so that may or not be related to this problem. I left a comment on that ticket as follows:

This is still an issue for me on 2.1.5. I've have taken a look at debugging the issue it seems to be a race condition.

Looking at magento/module-ui/view/base/web/js/form/element/select.js there is an initInput function that uses magento/module-ui/view/base/web/js/core/renderer/layout.js in order to append an input field. Looking at layout.js we can see that the run function actually gets returned and is what gets used when calling layout in select.js, this then calls the function named iterator which loops and either processes a node or adds it as a child should it be a string. As in this case it's a string it adds it and ultimately ends up using magento/module-ui/view/base/web/js/lib/core/collection.js to do so. The function in this collection.js file that is used is insertChild. Outputting data to the console I could see that in the event that the county (region) field was placed at the top of the form, 'this._elems' or 'container' was actually empty. As this meant it did not contain the field passed in via the position parameter, the function just adds it to the array and then presumably all other fields get added afterwards. In the event this all actually worked and the field was position where it should be, the 'container' / 'this._elems' variable was actually a populated array which included the fields referenced in the 'position' param.

**Comment by EnricoB3** [comment]
Same issue here on Magento 2.1.6

**Comment by BaberAhmed** [comment]
This is also happening on Enterprise 2.1.5. The state/province field is appearing at the top of the form.

**Comment by veloraven** [comment]
@Danielc3 we were not able to reproduce this issue by provided steps.
Please provide more detailed steps or additional preconditions.
Do you use clean install or upgrade from some previous version?
Do you use any external extensions?
Please also provide information about your environment: OS, versions of PHP, MySQL, web-server.

**Comment by EnricoB3** [comment]
The issue for me occurs 1 time every 10 (approximately).
I'm not using any external extensions for the Checkout Process.

### Preconditions
1. OS: Ubuntu 16.04
2. PHP: 7.0.18
3. MySQL: 5.7.18
4. Web Server: Apache 2.4
5. Magento 2.1.7

Screenshot with State/Province in the right position:
![checkout-bug1](https://user-images.githubusercontent.com/14115016/27511329-af4a1cb8-5921-11e7-8846-5abcf734b63a.png)

With State/Province in the wrong position:
![checkout-bug](https://user-images.githubusercontent.com/14115016/27511265-693aba8a-5920-11e7-8fc4-f3be5d6d8432.png)

Hope this helps!

**Comment by BaberAhmed** [comment]
I can confirm that this is still an issue for M2 2.1.7.

**Comment by BaberAhmed** [comment]
Please can I check to see if there is any update on this bug?

**Comment by magento-engcom-team** [comment]
@Danielc3, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by wangqingshen** [comment]
@Danielc3 Hi, Have you solved this problem? I also met this problem in the 2.1.7 version

**Comment by Danielc3** [comment]
@wangqingshen Hi, no sorry, I do not believe we got to the bottom of this.
