### ISSUE TITLE
Inconsistent Gift Options checkbox labels

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/magento2#9421]
### Preconditions

1. All the Gift Options are enabled in Configuration

### Steps to reproduce

1.  Go to Storefront
2. Add any Product to the Cart
3. Proceed to Multishipping Checkout
4. Look at the Gift Options checkboxes

### Expected result

1. All of the checkbox labels should be consistent

### Actual result

1. Checkbox labels are all different

**Comment by vpiyappan** [comment]
I am going to start this issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69153

**Comment by magento-engcom-team** [comment]
@ishakhsuvarov thank you for your report.
The fix for this issue is already available in release 2.2.0
