### ISSUE TITLE
2.1.5 Display Block below Price always shown

### ISSUE THREAD

**Issue by v0gler** [magento/magento2#9422]
### Preconditions

1. Magento 2.1.5 PHP7 
2. Magento Luma oder other Template

### Steps to reproduce

1. Under Stores-->Configuration-->Catalog-->Catalog -> Set Display Block below Price ->No
2. Clear all caches, reindex

### Expected result

1. No Taxes and shipping cost will be shown on Catalog Page

### Actual result

1. Taxes and shipping cost are still shown. 
![taxshipping](https://cloud.githubusercontent.com/assets/25635896/25476508/ae71fb9a-2b3a-11e7-90a8-91a03c75b337.png)

**Comment by Ctucker9233** [comment]
@SirElectro You may need to clear caches and redeploy static content to see the changes.

**Comment by v0gler** [comment]
@Ctucker9233 This dosen't help.

**Comment by magento-engcom-team** [comment]
@SirElectro , This issue affects only Magento Enterprise Edition, please contact Magento support instead of posting your issue here.
