### ISSUE TITLE
Incorrect order date in Orders grid

### ISSUE THREAD

**Issue by potatocommerce** [magento/magento2#9426]
We have noticed that Magento 2.1.4 displaying incorrect order date in the grid. 

### Preconditions
1. Found with Minsk timezone, reproduced on some others
2. Magento 2.1.4 CE

### Steps to reproduce
1. Place an order
2. Go to the orders grid

### Expected result
Correct time in the grid

### Actual result
Incorrect time in the grid. It is displaying correct date on order page though. It is always display time as XX:04:00 AM/PM, even 14:04:00 PM which is already a bug (it should be 02 PM, not 14 PM).
http://i.imgur.com/SyX9QmU.png
http://i.imgur.com/V0NXTUm.png
http://i.imgur.com/h3c6JYf.png

**Comment by YevSent** [comment]
Hi, @potatocommerce, thanks for reporting. I've created internal ticket `MAGETWO-68795`.

**Comment by Tjitse-E** [comment]
@potatocommerce you can try if this pull requests fixes this issue https://github.com/magento/magento2/pull/8336

**Comment by Ctucker9233** [comment]
@joni-jones related issue #8422.

**Comment by YevSent** [comment]
@Ctucker9233 how #8422 is related to this issue? This issue affects only time format in sales order grid and does not relate to the Newsletter.

**Comment by YevSent** [comment]
@Tjitse-E, mentioned PR did not have the full fix for this issue.

**Comment by Ctucker9233** [comment]
@joni-jones I thought this issue had to do with the time stamp not displaying correctly. I have noticed the same behavior in the newsletter module. If you do not think that they are related, then feel free to ignore.

**Comment by korostii** [comment]
Hello @magento-team,
Could you please announce in which version is this fix scheduled to ship?
It's a bit confusing to see the issue closed while the latest (2.1.7) release still has the bug inside.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69909
