### ISSUE TITLE
2.1.6 Receive 500 error when want export Low Stock Report.

### ISSUE THREAD

**Issue by vherasymenko** [magento/magento2#9428]
### Preconditions
1. Magento 2.1.6 version from 2.1-develop branch.
2. LAMP Stack.

### Steps to reproduce
1. Go to Admin side
2. Click "Reports > Low Stock Report "
3. Click "Export" (sometimes need click two times on this button)

### Expected result
1. Report should be exported successfully.

### Actual result
1. Displayed 500 error.

**Comment by vishveskrish** [comment]
@K7Triton : Are you able to resolve this issue ?

**Comment by mikebox** [comment]
I am working on this

**Comment by vishveskrish** [comment]
@mikebox : Do you find any solution ?

**Comment by nmallepally** [comment]
I have the same issue in 2.1.3, fixed after replicating the changes from the commit. but it does not show the products which are low in stock. when i give the range for quantity or sku, it does not show up results. Exports empty csv file.
![low stock error search](https://cloud.githubusercontent.com/assets/19605497/26003943/0dda43e2-372c-11e7-804e-79f2b4020aeb.PNG)

**Comment by mikebox** [comment]
https://github.com/magento/magento2/issues/9408

You can follow this for more information on empty low stock grid

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-68938
