### ISSUE TITLE
Empty value of attribute backend type varchar is not saved in flat catalog product table

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#9434]
### Preconditions
Tested on Magento 2.1.5
On multi store configuration.
Schedule indexer/Mview is not enabled on all indexers.
I used Index on Save indexer mode.

I have an attribute of backend_type varchar in a product.
The attribute has 'used_in_product_listing' = 1 in `catalog_eav_attribute` table.
Flat catalog category and  Flat catalog product is enabled in admin.

### Steps to reproduce

1. If I save any value in this attribute, it will show up in table `catalog_product_flat_[99]`.
2. In the next step I save an empty value (nothing/remove old value)
In the table  `catalog_product_flat_[99]`, the old value is still there. It's not cleaned/set to empty string or null.
3. If I look on category page or other product lists, the old value is displayed.

If change the the value of this attribute in admin edit product from 'something' into 'else',
 `catalog_product_flat_[99]` will have the new value.
The bug only happens when I change the attribute value from any string into empty string.

### Expected result

1. In table  `catalog_product_flat_[99]` there should be empy string or null for the attribute after I do the steps described above.
It's like nothing happens when you edit a product.

### Actual result

1.  `catalog_product_flat_[99]` still has the old value after I do the steps above.

**Workaround:**
do php bin/magento indexer:reindex catalog_product_flat
It will fix the table  `catalog_product_flat_[99]` but should we do it after every save ?
I can't tell now if any redundant cron process fixes it automatically when cron runs.
Like 'invalidate cache' Magento cron job.

**Debugging:**
In `Magento\Catalog\Model\Indexer\Product\Flat\Action\Indexer::write()` flat catalog product table is processed by entity id(s).
Around line 110 - 120 where the SQL query is built to fetch data from catalog_product_entity_* eav tables, the query generated looks like this:

`SELECT `e`.`entity_id`,
       `t`.`attribute_id`,
       IFNULL(`t2`.`value`, `t`.`value`) AS `value`
FROM `catalog_product_entity` AS `e`
LEFT JOIN `catalog_product_entity_varchar` AS `t` ON e.entity_id = t.entity_id
AND t.attribute_id IN (
                      ...
                      [my_attribute_id],
                      ...
                       )
AND t.store_id = [99]
LEFT JOIN `catalog_product_entity_varchar` AS `t2` ON t.entity_id = t2.entity_id
AND t.attribute_id = t2.attribute_id
AND t2.store_id = '1'
WHERE (e.entity_id = [ MY PRODUCT ID])
  AND (t.attribute_id IS NOT NULL)`

After I set empty value to attribute in admin this query does not return any row with my attribute_id included.

It's because this returns no rows:
`SELECT * FROM `catalog_product_entity_varchar` WHERE `attribute_id` = [my_attribute_id] AND `entity_id` = [MY PRODUCT ID]`
**Note:** no store_id in this SQL query.

After I save the attribute value in admin product edit page with nothing (empty string), it will delete the row from `catalog_product_entity_varchar`.

It looks like the flat catalog product table is not filled properly in this case in:
`Magento\Catalog\Model\Indexer\Product\Flat\Action\Indexer::write()`

Thank you

**Comment by korostii** [comment]
Possibly related: #9389

**Comment by daniel-ifrim** [comment]
I've noticed that the empty value is updated in flat table when indexer cron job runs.
Both in MView and normal index mode. I guess it's ok since Magento 2 is optimised not to store NULL value in eav related tables.

**Comment by lewisvoncken** [comment]
@veloraven and @daniel-ifrim this works fine in the develop branch

**Comment by magento-engcom-team** [comment]
@daniel-ifrim, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by PrajapatiChirag** [comment]
Same issue found with Magento 2.1.4.

**Comment by PrajapatiChirag** [comment]
Any solution for this ?

**Comment by deniskaravai** [comment]
Have reproduced the issue on Magento 2.1.17, 2.2.2, 2.2.6
