### ISSUE TITLE
A simple product with configurable products with special price only shows the special price like it is the basic price and not sale from old price to special price

### ISSUE THREAD

**Issue by alainstout** [magento/magento2#9435]
Very simple something and hard to find this solution

Having a simple product with configurable products for the sizes

But somehow he shows the special price as the basic price and not like a sale when you see the old price with a stroke through it and then the special price

Like this:

https://www.takoda.shop/en/test.html

Like you do get at a simple product it does work

Like this:

https://www.takoda.shop/en/stout-dog-tag-necklace-brass.html

Someone please know the answer would help of course a lot

Thanks

**Comment by flipflap** [comment]
I have the same issue.... and can't figure it out. The special price label is missing too on config products. I expect it to come from here but this file didn't change:
vendor/magento/module-catalog/view/base/templates/product/price/amount/default.phtml

Someone know where the special-price for config products is?

**Comment by hellekim** [comment]
I got this same issue.

**Comment by veloraven** [comment]
@alainstout thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by andidhouse** [comment]
I can confirm this on a new magento 2.1.7 system as well. 

There is a class "old-price sly-old-price no-display" which is set inline element to display none!
This element has the old price in it but is not displayed!

@veloraven i would rather suggest acting here and not telling people to format bugs. It is quite simple - test it on your system and if this is really a but (what i think) create an internal ticket.

**Comment by magento-engcom-team** [comment]
@alainstout, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
