### ISSUE TITLE
Import product function error. Importing "product_online" attribute value is applied to the Store but not Store View.

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#9437]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15
### Steps to reproduce

There are two strore views View1 and View2
-There are to subroducts Product1 and Product2
-It is need to have Product1 is eneabled in View1 and disabled in View2
and Products2 iseneabled in View2 and disabled in View1
-Prepare two files with data for import with following attribute values (simplified set):

sku;store_view_code;product_websites;product_online
File 1: Product1 ;View1;store;1
File 2: Product1 ;View2;store;2

1. Import file 1
2. Import file 2
3. 

### Expected result

1. Product1 is eneabled in View1 
2. Product1 is disabled in View2

P.S. I tried set "product_online" values 0 and 1 but it didnt affect.

### Actual result

Product1 is disabled in View1 and disabled in View2
System applies "product_online" attribute to the store but not store view.

1. [Screenshot, logs]

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70330 was created.

**Comment by magento-engcom-team** [comment]
@Tonop, thank you for your report.
We've created internal ticket(s) MAGETWO-70330 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#40
