### ISSUE TITLE
Configurable products do not display visual swatches after a short period of time

### ISSUE THREAD

**Issue by gman-1986** [magento/magento2#9438]
### Preconditions

1. Magento 2.1.5, PHP 5.6 10.0.29-MariaDB-cll-lve
2. Multi store

### Steps to reproduce

1. import products through csv 
2. products display fine with visual swatches
3. then at some point shortly after something triggers the configurable products to lose there simple ones? 

### Expected result

1. configurable products should display visual swatches

### Actual result

1. 
no visual swatches displayed 
![missing swatch](https://cloud.githubusercontent.com/assets/20956325/25500605/98fef202-2b87-11e7-85e3-881c56d24d53.png)

this is the configurable product missing its simple products
![admin config](https://cloud.githubusercontent.com/assets/20956325/25500720/0339532e-2b88-11e7-8b95-a8c79b5db301.png)

also noticed visual swatch attributes are missing image
![swatches](https://cloud.githubusercontent.com/assets/20956325/25501184/b9c1aad2-2b89-11e7-9135-2b096826eeb1.png)

The other day i was faced with an error message when saving attributes similar to this "Undefined index: delete in /var/www/html/magento2/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 177"

I read on multiple sites the solution was to increase max_input_vars to 100000 in the php (from 1000)

I now wonder if this has played a part in the problem and has corrupt my site? what does max_input_vars actually do?

**Comment by korostii** [comment]
Well I've left an explanation regarding max_input_vars issue [here in a comment](https://github.com/magento/magento2/issues/9317#issuecomment-295668804). In short, it just allows to save the attribute in admin after you've added a lot of options, nothing more.

I doubt that it could force the swatches to disappear from the storefront, there's probably something else causing the issue you're experiencing. I would check the browser console and logs under `<your Magento installation dir>/var/log` for errors. 

BTW, do simple products actually disappear from the configurable in admin? Sounds similar to #7588

**Comment by gman-1986** [comment]
yes simple products disappear from config admin,seems similar to that issue.

Found out that one attribute in the visual swatch had the same admin name as another but used a different colour swatch and when imported this knocked the simple products out. not just for that product but for every and any product that uses a visual attribute.
