### ISSUE TITLE
Module version number

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#944]
While creating a module I noticed that the modules version number is generated from:
```
<module name="Jcowie_Helloworld" schema_version="0.0.1">
```
Key part being the `schema_version` is this correct or should there be a option for version / module_version ?

The schema definition indicates that schema_version is the only numerical field that can be used and exploring the values that get inserted into `core_resource` this looks to be correct. However im questioning if the naming of this is correct.

**Comment by buskamuza** [comment]
It's not version of the module. It's version of the schema. It may happen that schema version changes couple times between 2 module versions.
Module version is defined under `version` in `composer.json`. It's not used for the installation, just for composing the code via Composer (if Composer is used).

**Comment by alankent** [comment]
A schema could change several times between two module versions, but I suspect more common will be the schema version will change *less* frequently than the module version (in which case no database schema upgrade is required). This is particularly true for module patches (you don't want the schema to change per patch, and you want to know if you can back out of a patch safely knowing the schema did not change).

**Comment by jamescowie** [comment]
Cool. Thanks for the update. It makes more sense now. So `schema_version` is used to determine the database schema version and is used internally and stored against `core_resource` to check for database changes and apply etc when incremented. 

However code modifications and the code version should be handled via composer.

**Comment by Vinai** [comment]
This touches on the same problem as #840. Is a composer.json required even if a module only will ever be part of a single installation? From my point of view it would be useful to be able to specify a module version in the module.xml and omit the composer.json.
If both files are present and define different version numbers it should trigger a suitably informative exception.

**Comment by buskamuza** [comment]
Why the version is needed for the single installation?

**Comment by Vinai** [comment]
Upgrade Scripts

**Comment by buskamuza** [comment]
Do you mean MageMagentoscripts? They do not use module version.

**Comment by buskamuza** [comment]
*Magento scripts

**Comment by Vinai** [comment]
With Magento 1 they where called "Schema" and "Data" setup scripts, living in the *app/code/[codePool]/[Namespace]/[Module]/* directory within subfolders called *sql* and *data*.

Here is an example schema script directory from Magento 1: 
https://github.com/OpenMage/magento-mirror/tree/magento-1.9/app/code/core/Mage/Core/sql/core_setup

Here is an example setup script from Magento 2. 
https://github.com/magento/magento2/tree/develop/app/code/Magento/Catalog/sql/catalog_setup

**Comment by alankent** [comment]
Personally I prefer always one way to do things. That is always have composer.json file and don't SOMETIMES put that into in module.xml. Remember things module depends on also goes on composer.json file (including third party libraries). I also suspect sometimes a local module may be reused on another project then requiring composer.json.

**Comment by buskamuza** [comment]
@Vinai, yes, those scripts don't rely on a module version, they rely on schema version in module.xml

**Comment by Vinai** [comment]
Ahh, so the "schema" in "schema_version" referes to the database schema.
Will there be a separate version for data setup scripts? Will there even still be data setup scripts?

I'm just asking because I've used setup scripts probably more often to update database content rather then the table schemas.
Some common usecases are to set system config values for example, or automatically create some CMS pages, widget instances, or store views.
If those changes should go in the same files, that is, use the same schema_version number, I think the name "schema_version" is not ideal. Somthing like setup_version that is less focussed on the database schema would be more descriptive and fitting.

**Comment by buskamuza** [comment]
Data setup scripts use same schema_version. You'r right that this name is confusing in this case. Your variant sounds good to me.

As I know we're not going to remove support of data setup scripts, while their representation may change a little bit.

**Comment by jamescowie** [comment]
I think if scema_version in only related to structural changes then the name is fine, However with the case that @Vinai highlighted it does introduce confusion and `setup_version` makes more sense.

**Comment by verklov** [comment]
Internal ticket ID: MAGETWO-33412

**Comment by verklov** [comment]
Thank you all for collaboration on this issue! We created the ticket for analysis and put it to the backlog. Thus, we are closing this ticket now. Please watch the repository for updates!
