### ISSUE TITLE
Magento 2: Reauthorization not returns needed variables

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#9442]
In continue with https://github.com/magento/magento2/issues/9336

Reauthorization Returns

```
'AUTHORIZATIONID' => '45610683DL9281543',
'TIMESTAMP' => '2017-04-28T01:20:31Z',
'CORRELATIONID' => '5a5a4056b1d7',
'ACK' => 'Success',
'VERSION' => '72.0',
'BUILD' => '32996991',
'PAYMENTSTATUS' => 'Pending',
'PENDINGREASON' => 'authorization',
'PROTECTIONELIGIBILITY' => 'Eligible',
'PROTECTIONELIGIBILITYTYPE' => 'ItemNotReceivedEligible, UnauthorizedPaymentEligible'
```

Not returning parent_payment & mainly valid_until.

Not sure wether it's related issue or not

https://developer.paypal.com/docs/api/payments/#authorization_reauthorize

@magento-admin @magento-team

**Comment by YPyltiai** [comment]
Hello @shahankitb997,

Thank you for reporting. Let us check it.
@joni-jones, may you please look into this issue? Check if it is related to #9336 or not, please.

**Comment by YevSent** [comment]
Hi, @shahankitb997, Magento uses NVP API for PayPal Express Checkout and [NVP Reauthorization ](https://developer.paypal.com/docs/classic/api/merchant/DoReauthorization_API_Operation_NVP/) response does not have the `parent_id` and `valid_until` fields.

I'm closing this ticket as not an issue.

**Comment by shahankitb997** [comment]
Hi @joni-jones , Understand can you give me working example of Reauthorization in Magento 2.1.6 CE.

Otherwise Can you help to give answer of below ones?

https://magento.stackexchange.com/questions/172143/magento-2-how-to-reauthorize-paypal-payment-store-all-information

**Comment by YevSent** [comment]
@shahankitb997, Magento has not built-in functionality for PayPal integrations to process reauthorization.

**Comment by shahankitb997** [comment]
Hi @joni-jones, Stuck on reauthorization from so many days. How to perform reauthorization for PayPal authorized transaction programmatically? I hope u read stackexchange question. 

Please help/guide to solve this. In corePHP it also seems not working.
