### ISSUE TITLE
Admin panel stuck on all forms pages

### ISSUE THREAD

**Issue by mornayv** [magento/magento2#9444]
### Preconditions

1. After a fresh install, with all correct file & folder permissions, following exactly as per composer install instructions.
2. Magento 2.1.6, PHP 5.6, MySQL 5.6, CentOS 6.9

### Steps to reproduce

1. Log into Admin Panel
2. Click any menu with forms, eg. Products -> Catalog
3. 

### Expected result

1. Ability to enter data into form

### Actual result

1. Spinning wheel over form, preventing any input.  
![magento-admin-hang](https://cloud.githubusercontent.com/assets/25924218/25520607/c962ecda-2bfc-11e7-8406-edbdab9b8b5b.jpg)

**Comment by sopedro** [comment]
Same issue, this happens when I hit php bin/magneto setup:upgrade.
I have to refresh the page 4 times until the form loads, after this the form loads wells....

**Comment by korostii** [comment]
![tumblr_m3x648wxbj1ru99qvo1_500](https://cloud.githubusercontent.com/assets/24894168/25664674/ffedf5c6-3023-11e7-945d-1f542b26643e.png)

**Comment by israelfaria** [comment]
I can confirm. My case is even worse. I don't see nothing but the spinning wheel.

![nothing-magento](https://cloud.githubusercontent.com/assets/16663/26652223/88c57e66-4625-11e7-8f32-7c7d628a5530.png)

![nothing-magento2](https://cloud.githubusercontent.com/assets/16663/26652262/b1029e2c-4625-11e7-8fbd-3ab80236be48.png)

**Comment by magento-engcom-team** [comment]
@mornayv, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
