### ISSUE TITLE
Cart 860 does not contain item 1204

### ISSUE THREAD

**Issue by niranjanleanswift** [magento/magento2#9445]
### Preconditions

1. Magento version - 2.1.6

### Steps to reproduce

1. When a product is add to cart it produces this error(Cart 860 does not contain item 1204)
2. 860- quote Id, 1204-quote item id.

### Expected result

1. The cart should be added successfully.

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment]
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Please try add as much information as possible, including the environment you use, 3rd party themes and modules installed (if any), preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by cygnet-aamunshi** [comment]
Hello,

We can reproduce this issue. For every fresh quote for the first time when a fresh new session is initialise and if we try to add multiple products programmatically then it will give us the given error after adding the first product to cart.

After the first error is reported it works smoothly for every time we try to add the bunch of products. ut, if we clear browser cache or place an order and then try to add the same bunch of products then it gives the error after adding the first product. 

It seems that after adding the first product, when we go to add the second one and the code that checks for the existing items in cart is creating issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69005

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70267
