### ISSUE TITLE
different URL for front and backend will cause backend to stop working

### ISSUE THREAD

**Issue by ronnybremer** [magento/magento2#9448]
### Preconditions
I am running CE 2.1.6 on PHP 5.6 (CentOS7 with Apache 2.4).

Magento is installed directly in /var/www/html and works fine for both the frontend and backend.
I want to restrict access to the backend to internal IP addresses only, so in preparation I created 2 DNS entries, both pointing to my server: server.test.com and frontend.my.store.
Furthermore I added a custom backend admin URL to the configuration file app/etc/env.php:
  'backend' =>
  array (
    'frontName' => 'secretadm',
  ),

I can access the backend perfectly with http://server.test.com/secretadm/admin and the frontend as http://server.test.com/

Following the guidelines I added two virtual hosts to my apache conf:
<VirtualHost *:80>
    ServerName          server.test.com
    DocumentRoot        /var/www/html/
 </VirtualHost>
 <VirtualHost *:80>
    ServerName          frontend.my.store
    DocumentRoot        /var/www/html/
    SetEnv MAGE_RUN_CODE "ws_xx"
    SetEnv MAGE_RUN_TYPE "website"
 </VirtualHost>

And I change the frontend URL to "http://frontend.my.store/" in the config at the website level.

As soon as I activate this configuration, I can no longer access the backend. I always get a 404 error.

### Steps to reproduce

1. change frontend URL to a different DNS name
2. activate virtual host config in apache
3. restart Apache
4. try to access the backend at http://server.test.com/secretadm/admin

### Expected result

1. login window for backend is shown

### Actual result

1. web server returns a 404

Once I change the entry for the website  baseurl in the core_config_data table back to the http://server.test.com/ setting, all works again.

What am I missing?

Thank you,
Ronny

**Comment by 1408sheva** [comment]
Hi @ronnybremer , I changed the URL through the admin panel, will change the virtual hosts and everything works for me. This a problem actual for you?
![1](https://user-images.githubusercontent.com/22118443/27866624-c9c3deae-619f-11e7-8d2b-081a4375d514.PNG)
![2](https://user-images.githubusercontent.com/22118443/27866623-c9c20c0a-619f-11e7-834f-e443797c0ac8.PNG)

**Comment by ronnybremer** [comment]
Yes, this is still an issue in 2.1.7.
I did some more debugging and ended up with this:
- enabled different apache logs for both the main URL (admin) and the store URL
- enabled "redirect to base url" setting in Magento at the global level

As soon as I change the store URL at the web site level and try to access the admin page, I see the browser redirecting indefinitely between http://server.test.com/secretadm/admin (getting 302) to http://frontend.my.store/secretadm/admin (also getting 302).

There has to be something I miss but I am out of clues.

Yours,

Ronny

**Comment by 1408sheva** [comment]
Hi @ronnybremer, execut this line of code: "cat /etc/httpd/conf.d/*" and send me output;

**Comment by ronnybremer** [comment]
@1408sheva sure, thank you for looking at the config. This is the list of files, I have only modified the catnp.conf:

ll /etc/httpd/conf.d/
total 44
-rw-r--r--. 1 root root 2926 Apr 12 23:03 autoindex.conf
-rw-r--r--. 1 root root 1008 Jul 11 11:13 catnp.conf
-rw-r--r--. 1 root root  401 Jun 10  2014 fcgid.conf
-rw-r--r--. 1 root root  295 Apr 12 15:50 manual.conf
-rw-r--r--. 1 root root 1017 Mar 15 17:15 php.conf
-rw-r--r--. 1 root root  366 Apr 12 23:04 README
-rw-r--r--. 1 root root 9438 Apr 12 15:50 ssl.conf
-rw-r--r--. 1 root root 1252 Apr 12 15:50 userdir.conf
-rw-r--r--. 1 root root  824 Apr 12 15:50 welcome.conf

**Comment by ronnybremer** [comment]
catnp.conf:

<VirtualHost *:80>
    ServerName          server.test.com
    DocumentRoot        /var/www/html/
 </VirtualHost>

 <VirtualHost *:80>
    ServerName          frontend.my.store
    ServerAlias            my.store
    DocumentRoot        /var/www/html/
    SetEnv MAGE_RUN_CODE "ws_mystore"
    SetEnv MAGE_RUN_TYPE "website"
 </VirtualHost>

 <VirtualHost *:80>
    ServerName          frontend.other.store
    ServerAlias            other.store
    DocumentRoot        /var/www/html/
    SetEnv MAGE_RUN_CODE "ws_otherstore"
    SetEnv MAGE_RUN_TYPE "website"
 </VirtualHost>

**Comment by ronnybremer** [comment]
All 5 DNS entires are pointing to the same IPv4 and IPv6 address.

I appreciate your assistance in that matter.

Yours,

Ronny
