### ISSUE TITLE
PHPUnit tests being run on disabled modules

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#9449]
Presuming this is a bug...

Running bin/magento dev:tests:run unit from the root directory is running PHPUnit tests in modules that are disabled.

### Preconditions
[Magento 2.1.5, PHP 7.0]
1. Create custom module
2. Do not run `bin/magento module:enable [custom module name]` or 'bin/magento setup:upgrade`

### Steps to reproduce
1. Create `*Test.php` file in [Vendor]/[Module]/Test/Unit directory with basic PHPUnit test that fails
2. Run `bin/magento dev:test:run unit`

### Expected result
1. PHPUnit tests run, no Failure for test created above

### Actual result
1. PHPUnit tests run, Failure for test created above

**Comment by magento-engcom-team** [comment]
@nbennett25, thank you for your report.
We've created internal ticket(s) MAGETWO-80824 to track progress on the issue.

**Comment by mariuscris** [comment]
Base on the configuration file from "dev/tests/unit/phpunit.xml.dist", you can have tests running on a module even if that module is not enabled. 

The configuration is set to read directories with places where the unit tests files can be located and they do not depend on module status (being enabled or disabled).

I think the main reason for this, it's because unit tests do not need to have the module enabled in order to test a class. I do not think this is an issue,

**Comment by nbennett25** [comment]
What's the rationale of running tests on disabled modules? If your deployment process is dependent on all tests passing, and a disabled module is failing a test, you won't be able to deploy code due to code that isn't even being used.

**Comment by talesh** [comment]
I got this one #squashtoberfest

**Comment by okorshenko** [comment]
Hi @talesh please accept the invite to join magento team on the github

**Comment by orlangur** [comment]
> What's the rationale of running tests on disabled modules?

What's the rationale of keeping disabled modules in codebase? Why it's bad to keep disabled modules in workable state?

I don't see a valid reason to change this behavior for unit tests. For integration and functional tests it makes more sense but they are not stored within a module yet.

If it will be changed, it would be nice to change only `bin/magento dev:test:run unit` behavior and not `./vendor/phpunit/phpunit/phpunit -c dev/tests/unit`.

**Comment by nbennett25** [comment]
@orlangur - so should best practices be to simply remove modules that are not enabled from the codebase? I tend to agree with you - if the code isn't being used it shouldn't be there, but if that's not currently the protocol, I don't see any reason for running unit tests for code that will never be used. (Also, if only enabled modules should be included in the code base, why have an enabled/disabled flag at all?)

**Comment by orlangur** [comment]
That is not what I was saying :) I was saying that it is a good thing to keep **ALL** your modules workable so that they can be enabled at any moment. And if some disabled module does not work, simply remove it from codebase if you're not going to fix it.

**Comment by talesh** [comment]
Hi @okorshenko, as far as I can tell the autoload is fine. This is an issue of just running tests on unused code.

**Comment by orlangur** [comment]
@talesh yeah, PHPUnit is not aware of Magento application, it just runs specified paths: https://github.com/magento/magento2/blob/2.2-develop/dev/tests/unit/phpunit.xml.dist#L15 (and it should not be aware).

Are there any places in documentation saying enabled/disabled status should affect **UNIT** tests execution?

**Comment by talesh** [comment]
Hi @orlangur, no there isn't.

**Comment by okorshenko** [comment]
Hi @nbennett25 
we are closing this ticket as non-issue. Unit tests should not care about application state. If you would like to exclude some folders from the testing, you can use phpunit.xml file for that.
@talesh @orlangur thank you for research!

**Comment by nbennett25** [comment]
@okobchenko - your call, but it seems like bad practice to me.
