### ISSUE TITLE
Included js/css/media file issues

### ISSUE THREAD

**Issue by architech99** [magento/magento2#945]
I set up and installed the core Magento2 files and sample data. Everything went well (except for needing to increase the max_nesting_value parameter for PHP), except as it relates to the document root.
Initially, I set the document root to the project root (in this case a directory "magento2"). When I did this and using the Luma theme, all Javascript resources in "/static/js" were not found (because the URL generated was "/static/js/..." and the files were actually at "/pub/static/...".
For security reasons, I don't like to have all my files available in the DocumentRoot anyway (most modern frameworks put the entry point in a sub-directory of their repository, i.e. "web", "public", etc). I noticed the index.php file that pointed executed the same bootstrap.php file.
I changed my Apache configuration document root to the "pub" directory and tried it. All the files in the "/static" path showed, but now I was getting an error for "/pub/media/styles.css" which caused some other issues.
I ended up pointing my DocumentRoot to magento2/pub/ and creating a symbolic link for magento2/pub/pub/ to magento2/pub/.

I'm not sure if that is the ideal solution or if I missed something in my configuration. Long term, I would prefer "magento2/pub" be the location for the DocumentRoot configurations, so I'm hoping there's a configuration setting I'm missing that would take care of this without the need for creating a symbolic link.

**Comment by alankent** [comment]
Thanks for the feedback. We are still working on refactoring the directory structure, bit by bit. We are not committing to exactly how far we will get, but there is certainly appeal in having the 'pub' directory (or similar) be the document root.  Things in this area are still a bit unstable, and I suspect will be for the next month or so. I have heard a number of people say they would prefer 'pub' or similar be the document root, instead of using .htaccess files to hide things.

**Comment by Vinai** [comment]
:+1:

**Comment by architect0317** [comment]
In general, it would be better to keep them out of Web-visible directories from the very beginning. This is standard practice for most modern application frameworks and would generally reduce the potential attack surface. Thanks for the replies.

Looking forward to seeing how work on Magento2 progresses.

**Comment by patrickpeng2091** [comment]
I use bin/magento setup:static-content:deploy en_US  command

but ,styles.css file not found

**Comment by maksek** [comment]
closing as outdated issue.
