### ISSUE TITLE
Tinymce: error in [unknown object].fireEvent(): event name: tinymceChange error message: URI malformed

### ISSUE THREAD

**Issue by hostep** [magento/magento2#9452]
### Preconditions
1. Magento develop branch (tested with revision: 5ea676e196abcd69e9a4063d5c23e7759b76a2c2)
2. PHP 7.0.18

### Steps to reproduce
1. Setup a brand new Magento project from the develop branch
2. Login to the backend
3. Go to Content => Pages
4. Create a new Page
5. In the Content field, start entering: `10%`

### Expected result
1. No errors should pop up

### Actual result
1. From the moment you type the `%` character, an error pops up:
`error in [unknown object].fireEvent(): event name: tinymceChange error message: URI malformed`

![screen shot 2017-04-28 at 20 55 54](https://cloud.githubusercontent.com/assets/85479/25543215/dc1eaeaa-2c55-11e7-9e68-dbf5427dfd84.png)

### Discussion
This problem was introduced in this commit: https://github.com/magento/magento2/commit/9030e0860abaa93650dd82aaaac42aff081b2378
Removing the line `content = decodeURIComponent(content);` fixes the issue.

The question is: why was the line added?
The commit was part of some other commits to fix issue https://github.com/magento/magento2/issues/6138

But without that line, the issue is fixed as well, in my tests though, but maybe the line was necessary for some other edge case?

It would be great if this could be fixed before Magento 2.2 is released, as this is a really annoying problem :)

Thanks!

**Comment by shiftedreality** [comment]
Internal ticket MAGETWO-66885

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
Closed.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435
