### ISSUE TITLE
Import customizable options adds it to another product if same SKU is filled

### ISSUE THREAD

**Issue by DependencyHell** [magento/magento2#9457]
When creating a new product, if by mistake I set the SKU of an already existing product, and import customizable options from this one, these options will be imported to the first product with same SKU, althougth an error shows that same SKU is existing.

### Preconditions
Magento 2.1.5

### Steps to reproduce
1. Create a simple product with customizable options (i.e SKU : product-test)
2. Create a product and set same SKU
3. Import customizable options from the first product
4. Save

### Expected result
1. Information message indicates that SKU has been changed (should explain it is already in use)
2. Confirmation message indicates that Product is saved
3. Customizables options should be imported in this new product

### Actual result
1. Information message indicates that SKU has been changed 
2. Confirmation message indicates that Product is saved
3. Imported customizable options are saved to the already existing product that had SKU set first

First Product with sku 'product-test', and 2 customizable options :
![create-first-product](https://cloud.githubusercontent.com/assets/9851301/25563707/370fbabe-2da2-11e7-8e5d-9a5598680874.png)

Create a new product and by mistake set same sku 'product-test', then on Customizable Options click on Import Options :
![create-second-product](https://cloud.githubusercontent.com/assets/9851301/25563706/370f7388-2da2-11e7-90c5-612dd270c670.png)

Select first product, and click Import : 
![create-second-product-import-a](https://cloud.githubusercontent.com/assets/9851301/25563708/37110cac-2da2-11e7-903c-6fe40da0fae2.png)

Everything looks fine, click on Save button : 
![create-second-product-import-b](https://cloud.githubusercontent.com/assets/9851301/25563709/3712cc90-2da2-11e7-9421-a69820f3cc1f.png)

Oops, by mistake I set an already existing SKU, the system changes it, no pb. I can leave happy.
Wait NO! Look at the bottom of the product page, check the new custom options, nothing!
![create-second-product-import-c](https://cloud.githubusercontent.com/assets/9851301/25563711/371371c2-2da2-11e7-8ae5-721d2eb340a6.png)

Return to first product, used to import Customizable options, and here it is duplicated...
![final-first-product-is-edited](https://cloud.githubusercontent.com/assets/9851301/25563710/3712f738-2da2-11e7-9387-8cfb66cf6836.png)

**Comment by Andrii-Deineha** [comment]
@DependencyHell  Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-70232.

**Comment by magento-engcom-team** [comment]
@DependencyHell, thank you for your report.
We've created internal ticket(s) MAGETWO-70232 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @DependencyHell

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@DependencyHell thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
