### ISSUE TITLE
Interceptor Chain Error

### ISSUE THREAD

**Issue by fooman** [magento/magento2#946]
I have created the following `etc/adminhtml/di.xml`

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
        <type name="Magento\User\Model\User">
            <plugin name="foomanAuthenticate" type="\Fooman\Authenticate\Model\Plugin\Authenticate" sortOrder="200"/>
        </type>
    </config>

with the following class

    <?php

    namespace Fooman\Authenticate\Model\Plugin;

    class Authenticate
    {

    }

(initially I had an aroundAuthenticate method but the error reproduces without any class content). When I then log into the back-end I get the following error message:

    Fatal error: Call to a member function dispatch() on a non-object in lib/internal/Magento/Framework/Model/AbstractModel.php on line 322

    Call Stack:
        0.0002     242384   1. {main}() pub/index.php:0
        0.8245   25305624   2. Magento\Framework\App\Bootstrap->run() pub/index.php:36
        0.8252   25332160   3. Magento\Framework\App\Http->launch() lib/internal/Magento/Framework/App/Bootstrap.php:244
        1.2897   32883920   4. Magento\Framework\App\FrontController\Interceptor->dispatch() lib/internal/Magento/Framework/App/Http.php:114
        1.3194   32875760   5. Magento\Framework\App\FrontController\Interceptor->___callPlugins() var/generation/Magento/Framework/App/FrontController/Interceptor.php:119
        1.3208   32995072   6. call_user_func_array:{var/generation/Magento/Framework/App/FrontController/Interceptor.php:95}() var/generation/Magento/Framework/App/FrontController/Interceptor.php:95
        1.3208   32995112   7. Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch() var/generation/Magento/Framework/App/FrontController/Interceptor.php:95
        1.3594   33156096   8. Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}() lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php:62
        1.3594   33156488   9. Magento\Framework\Interception\Chain\Chain->invokeNext() var/generation/Magento/Framework/App/FrontController/Interceptor.php:90
        1.3595   33156968  10. Magento\Framework\App\FrontController\Interceptor->___callParent() lib/internal/Magento/Framework/Interception/Chain/Chain.php:65
        1.3595   33157520  11. call_user_func_array:{var/generation/Magento/Framework/App/FrontController/Interceptor.php:48}() var/generation/Magento/Framework/App/FrontController/Interceptor.php:48
        1.3595   33157856  12. Magento\Framework\App\FrontController->dispatch() var/generation/Magento/Framework/App/FrontController/Interceptor.php:48
        1.4740   41062024  13. Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch() lib/internal/Magento/Framework/App/FrontController.php:44
        1.4740   41062528  14. Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:132
        1.4741   41067056  15. call_user_func_array:{var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:95}() var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:95
        1.4741   41067096  16. Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch() var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:95
        1.4741   41067232  17. Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Backend\Controller\Adminhtml\Index\Index\{closure}() app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php:32
        1.4741   41067624  18. Magento\Framework\Interception\Chain\Chain->invokeNext() var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:90
        1.4744   41085184  19. call_user_func_array:{lib/internal/Magento/Framework/Interception/Chain/Chain.php:63}() lib/internal/Magento/Framework/Interception/Chain/Chain.php:63
        1.4744   41085224  20. Magento\Core\App\Action\Plugin\Design->aroundDispatch() lib/internal/Magento/Framework/Interception/Chain/Chain.php:63
        1.5401   41976760  21. Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}() app/code/Magento/Core/App/Action/Plugin/Design.php:38
        1.5401   41977152  22. Magento\Framework\Interception\Chain\Chain->invokeNext() lib/internal/Magento/Framework/Interception/Chain/Chain.php:57
        1.5403   41987168  23. call_user_func_array:{lib/internal/Magento/Framework/Interception/Chain/Chain.php:63}() lib/internal/Magento/Framework/Interception/Chain/Chain.php:63
        1.5404   41987208  24. Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() lib/internal/Magento/Framework/Interception/Chain/Chain.php:63
        1.5405   41987640  25. Magento\User\Model\User\Interceptor->reload() app/code/Magento/Backend/App/Action/Plugin/Authentication.php:85
        1.5405   41987792  26. Magento\User\Model\User->reload() var/generation/Magento/User/Model/User/Interceptor.php:325
        1.5406   41988632  27. Magento\User\Model\User\Interceptor->load() app/code/Magento/User/Model/User.php:621
        1.5406   41988832  28. Magento\Framework\Model\AbstractModel->load() var/generation/Magento/User/Model/User/Interceptor.php:455
        1.5406   41988952  29. Magento\Framework\Model\AbstractModel->_beforeLoad() lib/internal/Magento/Framework/Model/AbstractModel.php:291

There seems to be some clash with https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/etc/adminhtml/di.xml#L55 even though it is a completely different class since if I remove it the error message changes.

**Comment by fooman** [comment]
Same result when the leading \ is removed from type

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
        <type name="Magento\User\Model\User">
            <plugin name="foomanAuthenticate" type="Fooman\Authenticate\Model\Plugin\Authenticate" sortOrder="200"/>
        </type>
    </config>

**Comment by alankent** [comment]
You might need a beforeXXX(), afterXXX(), or aroundXXX() function defined in the class perhaps. You may be tickling a bug due to no plugin method actually defined in the Authenticate class. The method names determines what gets intercepted.

**Comment by alankent** [comment]
Here is a sample plugin class one of the devs sent me earlier:

    class CustomerPlugin {
        /**
         * @param \Magento\Backend\App\AbstractAction $subject
         * @param callable $proceed
         * @return string
         */
        public function aroundGetFirstname(
            \Magento\Customer\Model\Data\Address $subject,
            \Closure $proceed
        ) {
            return 'InterceptedName!';
        }
    }

However note, this was part of diagnosing a bug reported where a generated method had {@noinherit} causing an error message about @returns missing. This bug is being worked on. But the class should be correct.

**Comment by fooman** [comment]
I previously used

    <?php

    namespace Fooman\Authenticate\Model\Plugin;

    class Authenticate
    {
        /**
         * Authenticate user name and password and save loaded record
         *
         * @param \Magento\User\Model\User $user
         * @param callable                 $authenticate
         * @param                          $username
         * @param                          $password
         *
         * @return bool
         * @throws \Magento\Framework\Model\Exception
         * @throws \Magento\Backend\Model\Auth\Exception
         * @throws \Magento\Backend\Model\Auth\Plugin\Exception
        */
        public function aroundAuthenticate(
            \Magento\User\Model\User $user,
            \Closure $authenticate,
            $username,
            $password
        ) {
            return $authenticate($username, $password);
        }
    }

which yields exactly the same error stack.

**Comment by fooman** [comment]
I just tried replacing `return $authenticate($username, $password);` with `return true;` which to my understanding should allow anyone to log all the time however I just get a standard Magento failed login message "Please correct the user name or password."

**Comment by alankent** [comment]
But no stack trace?

I don't know this code, so this will be my last suggestion as I am slightly guessing, but maybe try overriding https://github.com/magento/magento2/blob/0efd237c45d10a5c005da4b6bb722cfe27b885d5/app/code/Magento/Customer/Model/Session.php#L456 instead?  But I am going to leave this to the engineers closer to the code base than I am.

**Comment by fooman** [comment]
Thanks for the help so far. And yes the `return true;` just fails to complete the login. I don't think the customer session would help as I am currently trying to change the admin login only.

**Comment by antonkril** [comment]
Problem happens because of broken unserialization of User instance. This issue is fixed in one of team branches but not in mainline yet. 

You can add 
```php
parent::__wakeup();
```

in Magento\User\Model\User\Interceptor class to fix it or

**Comment by verklov** [comment]
@fooman, did you try the approach suggested by @antonkril? Please let us know whether your issue resolved by this change.

**Comment by fooman** [comment]
I have updated to 0.42.0-beta4 in the meantime and I can confirm that the original stack trace goes away after adding the `parent::__wakeup();` call

**Comment by verklov** [comment]
Great to hear that! As @antonkril mentioned, the fix will be delivered to the repository, most likely during the next update this Friday. Meanwhile, we are closing the ticket.
