### ISSUE TITLE
After 2 times switching store views - ERR_TOO_MANY_REDIRECTS. Delete cookies

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#9460]
### Preconditions
Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15

Multi store: Store 1. Store 2.
Multiple views-multi language for Store 1:English and Russian
Multiple domains for Store 1: English - www.store1.com. Russian- www.store1.ru

### Steps to reproduce

1. Open store1.com
2. Switch to Russian
3. System succesfully redirects to store1.ru
4. Switch to English.
5. System succesfully redirects to store1.com
6. Switch to Russian

### Expected result

 System succesfully redirects to store1.ru

### Actual result

ERR_TOO_MANY_REDIRECTS Error. Delete cookies

**Comment by 1408sheva** [comment]
@Tonop Is this issue still actual? We were not able to reproduce it on ver. 2.1.7 and 2.2.0-develop. Please add more details to your description of the steps you followed when identifying this issue. Screenshots, movie or logs would be helpful, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by Tonop** [comment]
Still actual.
