### ISSUE TITLE
Create faq category form not opened

### ISSUE THREAD

**Issue by DrashtiPandya** [magento/magento2#9462]
When we click for add new Category it shows only blank page.

### Preconditions
magento 2.0
![image](https://cloud.githubusercontent.com/assets/18716964/25576797/309c8152-2e7f-11e7-8d83-e2503e6d745e.png)

**Comment by bap14** [comment]
Do you have any errors in your logs?  What about javascript errors on the page?

**Comment by DrashtiPandya** [comment]
no there is no any errors and and no javascript error also 
![image](https://cloud.githubusercontent.com/assets/18716964/25605393/27b9cc30-2f28-11e7-965f-0bdf8ceda5cd.png)
console showing no error in this image

**Comment by korostii** [comment]
Please also check the log files located under `<your Magento2 installation dir>/var/log` on your web server.

**Comment by korostii** [comment]
Just noticed that it's not a catalog category but some 3rd-party module. 
Is [php-cuong/magento2-faqs-extensions](https://github.com/php-cuong/magento2-faqs-extensions) the one you're using? The issue most likely lies within that module, so please do contact the supplier of that module.

The GitHub issue tracker is intended for technical issues with Magento 2 CE itself only. 
The issues which do not exist on a clean installation of Magento 2 CE aren't likely to get resolved in here.
If you are looking for additional technical advice, you can also refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by magento-engcom-team** [comment]
@DrashtiPandya We are closing this ticket for now as issue originates from the third-party module. Please contact module's vendor regarding this.

Thank you.
