### ISSUE TITLE
THEME CHOOSER NOT SHOWING SOMETIME  I INSTALL 4 TIME 2 Time its not show the theme choose option

### ISSUE THREAD

**Issue by phpworld** [magento/magento2#9463]
STORE > COFIGURATion >  GENRAL 

THERE IS NO THEME CHOOSER 

MANY TIME I FACE THIS ISSUE  IN FRESH MANGENTO 

ANY HELP APRICEATEABLE

**Comment by mikeymike** [comment]
@phpworld are you actually looking for this ?  

`Content > Design > Configuration` 

That lets you configure the themes for each store etc

**Comment by mikeymike** [comment]
Also for reference I would suggest asking in the [Community forums](https://community.magento.com/) or [Stack Exchange](http://magento.stackexchange.com/) for this type of thing in future 👍 

More details on the [issues guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by phpworld** [comment]
Thanks i see that and I found like this mangeti have

Mak fool for configuration link

There is  link for this

**Comment by veloraven** [comment]
I'm closing this issue as it appeared to be not an issue.
