### ISSUE TITLE
After product deleted customer wishlist stopped working.

### ISSUE THREAD

**Issue by jimul** [magento/magento2#9471]
- Create product from magento admin panel.
- Login as customer on front end and add same product to wishlist.
- Delete same product from admin panel.
- For this customer, starting JS error on front side and can add any other product to wish list.

I believe same issue can be with if product contain in compare product, recently view, related product and product deleted, than product id still exist on these entity table. 

Magento version is 2.1.5 EE

**Comment by veloraven** [comment]
@jimul thank you for your feedback.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
