### ISSUE TITLE
Question: Removing a custom attribute from a Product using REST API

### ISSUE THREAD

**Issue by RSpeekenbrink** [magento/magento2#9472]
Hey there,

Is there a way to remove 1 specific custom attribute from a product using the REST API? I searched all documentations and can't find it.

Also I use the (v1/products/SKU) PUT command to add attributes. Is this the most efficient way?

Thanks

Magento Version 2.1.5

**Comment by veloraven** [comment]
@RSpeekenbrink if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
