### ISSUE TITLE
Unable to import "Use config settings" value for "is_returnable" attribute

### ISSUE THREAD

**Issue by benjamin-volle** [magento/magento2#9473]
### Preconditions
1. Magento 2.1.4

### Steps to reproduce
1. Create a file with columns "sku" and "is_returnable"
2. Put "2" or "Use config" or whahever is column "is_retunable"

### Expected result
1. Value of "is_retunable" should be "2" => "Use Config"

### Actual result
1. Value of "is_returnable" doensn't change

Problem is that Magento\Rma\Model\Product\Source::getAllOptions doesn't contain "Use config" value.

**Comment by korostii** [comment]
If I'm not mistaken, Magento_Rma module is only provided in Magento EE. 

Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. GitHub issue tracker is intended for the Community Edition issue reports.

**Comment by magento-engcom-team** [comment]
@synolia-bvo , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
