### ISSUE TITLE
Authorize.net direct post, md5 hash not required

### ISSUE THREAD

**Issue by zstutzman** [magento/magento2#9474]
### Preconditions

1. Magento 2.1.3

### Steps to reproduce

1. Setup the Authorize.net direct post payment method but do not ender a Md5 Hash

### Expected result

1. Magento should require Md5 hash or at least provide a payment gateway error in checkout

### Actual result

1. Magento does show a "server error" message when user tries to submit credit card info in payment step. The issue is that Magento creates and order in pending status but does not notify the customer that an order has been placed.

**Comment by YevSent** [comment]
Hi, @zstutzman, thanks for reporting. I've created internal ticket `MAGETWO-68872`.

**Comment by magento-engcom-team** [comment]
@zstutzman, thank you for your report.
We've created internal ticket(s) MAGETWO-68872 to track progress on the issue.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Any updates on this issue?

**Comment by magento-engcom-team** [comment]
Hi @zstutzman

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@zstutzman thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
