### ISSUE TITLE
varnish cache - odd states, price update question

### ISSUE THREAD

**Issue by robfico** [magento/magento2#948]
I installed latest beta3, installed varnish, set Magento admin to use varnish as caching mode. Set timeout to 5 minutes.

1. Had 2 browsers open - one not logged in, one logged in. Both browsers were on the same product page. Refreshed each a few times, all "HIT" requests. I changed the price of a product, saved, refreshed FPC cache as requested, and both browsers on full refreshes of page (shift-refresh) did not show new price. Is this expected? I don't know if tagging is enabled such that a price update on a product will trigger that page to be invalidated in varnish cache.

2. I refreshed not logged in browser page when cache expired, and price updated. However, in other browser that was logged in, price remained on old price, and on subsequent refreshes showed the old price still. Eventually after a few more refreshes it matched the new price and not logged in browser. On a few more tests, the logged in browser sometimes would show the new price once, and then another refresh would revert to the old price for a while.

Just seeing some odd behavior with varnish enabled and trying various scenarios.

**Comment by robfico** [comment]
As a followup, I am not seeing the purge request in Varnish (v 3.0.6) when a product is updated (I'm updating price as a test). I enabled logging in Varnish, looking for purge requests, and do not see any after a product price is updated and saved. The product page does not update the price until the Varnish cache itself expires. I'm using the generated vcl from Magento admin, verified Hits, see the tags listed, etc...

**Comment by kokoc** [comment]
Purge requests are allowed only for hosts specified in "acl purge" section of varnish configuration file.
Seems like your computer has few network interfaces and Varnish receives PURGE requests from IP, that is not specified in the acl list.

**Comment by robfico** [comment]
Yes, I already had 127.0.0.1 in the acl purge list, but I went ahead and added every IP/address listed in ifconfig for the VPS container. Restarted all services, no change. With verbose logging in Varnish, I do not see any purge requests after updating the price of a product and refreshing the page.

**Comment by robfico** [comment]
fyi, installed beta-4, still not seeing purge requests from Magento when using varnish 3.0.6 and updating price of a product. A recursive grep for "purge" (case insensitive) is not turning up a purge function for varnish as far as I can tell (but I may be missing something).

**Comment by TexanHogman** [comment]
CE supports Varnish integration by providing the vcl file; EE adds the integration to support the purge requests to Varnish.   Hope that clarifies why this is expected behavior for your setup.

**Comment by robfico** [comment]
Ah, that would explain it. This was not clear, as it seemed to imply both built-in FPC and Varnish were fully supported in CE. Odd that hooks in FPC to clear cache of specific items, but not for Varnish in CE...

**Comment by snohe** [comment]
@robfico, thanks for your confirmation.  We'll go ahead and close this GitHub issue.  If you do have any additional questions, please don't hesitate to open a new issue.

**Comment by melnikovi** [comment]
Functionality for purging Varnish cache has been moved from EE to CE

**Comment by magento-engcom-team** [comment]
Hi @robfico. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#949 by @vpodorozh in 2.3-develop branch
Related commit(s):
 - [fda524e2d299e0f325ef70adf72c9a0cfdf4bd1b](https://github.com/magento/magento2/commit/fda524e2d299e0f325ef70adf72c9a0cfdf4bd1b)

The fix will be available with the upcoming 2.3.4 release.
