### ISSUE TITLE
Command Returned non zero exit code while changing mode to production

### ISSUE THREAD

**Issue by abbasalitk** [magento/magento2#9481]
I have changed my backend settings to minify CSS and JS to Yes. Also JS Bundlinng to Yes.
But I was in developer mode. When I saved the setings, my complete backend has crashed.

Later I tried to change mode to production mode using Putty, But it comes "Command returned non-zero exit code:
`/opt/php56/bin/php -f /home/souqom5/public_html/bin/magento setup:di:compile`'

Also i tried to run setup:di:compile, then comes Fatal error: Out of memory (allocated 130547712) (tried to allocate 72 bytes) in    /home/souqom5/public_html/vendor/zendframework/zend-code/src/Scanner/FileScanne   r.php on line 36

I tried to increase memory and the same happens. Plesae help me to get my admin area back.

Thanks

**Comment by ebarchiesi** [comment]
Some time solve it php -d memory_limit=1024M -d set_time_limit=3600 -f .../bin/magento setup:di:compile

**Comment by abbasalitk** [comment]
Tried it..Still comes a fatal error

**Comment by veloraven** [comment]
@abbasalitk if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@abbasalis  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
