### ISSUE TITLE
How to change the scope of product inventory attribute to website or store 

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#9482]
How can I change the product stock attribute website or store wise?

### Steps to reproduce

1.  While creating a new product I am unable to set the stock/quantity attribute to website or store wise

### Expected result

1. If I am maintaining a separate warehouse for separate website or store then I should be able to upload the product quantity website or store wise.

### Actual result
1. Product quantity or stock is always in global scope.

**Comment by korostii** [comment]
It's not a bug, such a behavior is to be expected. 
If you look into the [documentation](http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-inventory.html?Highlight=Global), products stocks are indeed global.
If you'd like to extend the functionality to accommodate multiple warehouses, feel free to either use a 3rd-party extension or customize it on your own.

**Comment by routbiplab** [comment]
Yeah I totally agree with you. We indeed need such kind of customization where inventory can be managed for multiple warehouse or website.

Thanks!

**Comment by veloraven** [comment]
I'm closing this issue as it is not a bug.

**Comment by tejabhagavankollepara** [comment]
@korostii, But the quantity of the products are different for each website. Then what to do?

**Comment by korostii** [comment]
Hi @TejaBhagavan 

If this is still a problem for you, FYI Magento now includes "MultiSource Inventory (MSI)" feature out of the box since version 2.3.0, so maybe try upgrading.
> Merchants can represent multiple locations (sources) for physical inventory in Magento. 
> Sources can be grouped into stocks to create inventory pools that can be defined for one or more websites
( https://magento-devdocs.github.io/devdocs-for-tests/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.html )
