### ISSUE TITLE
Wishlist module can't get image in email template

### ISSUE THREAD

**Issue by tomnyson** [magento/magento2#9483]
### Preconditions

1. magento 2.1.6
2. nginx

### Steps to reproduce

1. Add product to my wishlist
2. Click share wishlist product to list friend
3. 

### Expected result

When I share List product in my wishlist to Friend list, Everything ok, but Image can't render in image 
out HTML 
    {{var items|raw}}
1. 

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/10257765/25650889/2074ab42-300a-11e7-9a09-c3ee5df2b2e7.png)

**Comment by mrkhoa99** [comment]
@tomnyson try to get the current links of images in email by inspecting element browser.  I think the https may be the issue.

**Comment by tomnyson** [comment]
I completed it.

**Comment by keldri** [comment]
Was this resolved?

**Comment by magento-engcom-team** [comment]
@tomnyson, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
