### ISSUE TITLE
Country Kosovo missing

### ISSUE THREAD

**Issue by magentoguyssageone** [magento/magento2#9488]
### Preconditions

1. I have tried to add new country (kosovo country) becuase by default this country not showing in admin Allowed country section and I first insert a new entry in directory_country table with country CODE (XK and XKX) and then edit the vendor/magento/zendframework1/library/Zend/Locale/Data/en.xml file and add new row for <territory type="XK">Kosovo</territory> and save this file clear the cache but still unable to see this new country in admin Allowed Country section and front-end checkout section etc.

2. My Magento ver. 2.1.2

### Steps to reproduce

1. you can try to add new country like kosovo for this need to follow below two steps
2. add new entry in directory_country table with country code  = > XK 	XK 	XKX
3. add new line in territories section like <territory type="XK">Kosovo</territory> and save this file and clear magento cache

### Expected result

1. The New Country kosovo should be show in admin Allowed country section 

### Actual result

1. Newly added Country is not showing in admin Allowed Country Section Please check this screenshot: http://prnt.sc/f3liqv

**Comment by nano1313** [comment]
Currently working on the same, and i can't add a new country. I've already tried what you did.

**Comment by maderlock** [comment]
I notice that Kosovo is actually included in the English locale file as of 2.1.5 (possibly earlier, but that's the version I'm looking at).

This does not help with adding new countries not mentioned in the locale, but that should help in this particular case. You just need to add the entry into the directory table and clear the cache.

**Comment by magentoguyssageone** [comment]
Hi,

Thanks for your info but I have already added this country in directory_country table but still its not showing please update me how can I add this new Country.

Thanks

**Comment by magentoguyssageone** [comment]
Hi
Any update on this I am waiting from last one month for any update
Thanks!

**Comment by nano1313** [comment]
Hi @magentoguyssageone i find a way to add countries. Magento use ICU-DATA resource bundle to read countries, So what i did is  making magento read my custom bundle with my own list of countries.  

I'm a little short of time these days, but soon i will write it down step by step, on how to do it right. 

Thank you!

**Comment by magentoguyssageone** [comment]
Hi
Hello nano1313 it is very good help for me, can you  please give me step by step guide?
Thanks!!

**Comment by magento-engcom-team** [comment]
Hi @magentoguyssageone 
Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by likeweb** [comment]
Hi
why is this issue be closed, the problem is stil there, I use M2 version 2.2.2 and adding new country stil not working.
I think its not a feature, its a issue.

@nano1313 Please can you post your step by step gide for resolving the problem? 

Thanks

**Comment by PascalBrouwers** [comment]
I think the real bug is that the country Kosovo is not listed in Magento. @magentoguyssageone could you edit the issue to reflect this?

**Comment by ghost** [comment]
Hi @magentoguyssageone , @PascalBrouwers , this issue is already fixed in Magento 2.3-dev

![Screenshot from 2019-05-03 13-20-47](https://user-images.githubusercontent.com/40756439/57132054-02799800-6da7-11e9-9788-d0e8c6c30ba7.png)

**Comment by PascalBrouwers** [comment]
Ok, still allot of countries are missing in 2.3 though.
