### ISSUE TITLE
Error while resend account confirmation link with special chars (e.g. "+" in email)

### ISSUE THREAD

**Issue by cviking26** [magento/magento2#9489]
There is an error while click on "resend confirmation mail". The mail address will transfered without special chars like "+". This is important for the new gmail feature which provides simply adding aliases.

### Preconditions

1. Magento 2.1.2
2. Enable Double-OptIn Mails for Customer Registration

### Steps to reproduce

1. Register as a new Customer with email like "firstname.lastname+PARAM@gmail.com" (customer/account/create/)
2. After Redirect to customer/account/login/ click on "Resend Confirmation Link"

### Actual Result
3. This redirect to customer/account/confirmation/email/firstname.lastname+PARAM@gmail.com/ - The Parameter email in url is not urlencoded, so the param is missing in the input field.
Parameter on this page in input field is now "firstname.lastname PARAM@gmail.com" without the plus

### Expected result

1. Click on "Resend Confirmation Link"
2. Get URL encoded mail in input field on  customer/account/confirmation/email/firstname.lastname%2BPARAM@gmail.com/ 
so Parameter in input field is with "+" char e.g. "firstname.lastname+PARAM@gmail.com"

### Solution
**Bug can solved simply adding** "_query" in htdocs/vendor/magento/module-customer/Model/Url.php:221

return $this->urlBuilder->getUrl('customer/account/confirmation', array('_query' => ['email' => $email]));

**Comment by magento-engcom-team** [comment]
Hi @cviking26 it would be very helpful if you can create a pull request for this issue. Looks like you already have a solution 👍

**Comment by cviking26** [comment]
@magento-engcom-team, created pull request in https://github.com/magento/magento2/pull/10848.

**Comment by magento-engcom-team** [comment]
@cviking26, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
