### ISSUE TITLE
Mp4 video not loaded in Mac OsX  Safari 10.1

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#9490]
We are streaming sample videos in the listing and detail page for the downloadable products, using the html5 video tag for frontend and for for streaming we are using the sample download link 
> downloadable/download/linksample/link_id

Every browser supports this across multiple platforms windows, ubuntu, mac osx except the safari 10 in mac os x (and  safari 5 in windows because of the lack of the video element support).

**Comment by avoelkl** [comment]
Hi @Taral-Patoliya,
It seems this is/was a problem of the used browsers and not a Magento 2 problem.

If you think it's a Magento 2 problem, please provide more information on the Magento 2 version used, PHP Version, operating system, etc.

**Comment by Taral-Patoliya** [comment]
@avoelkl Yes, it is the browser's problem. This issue can be closed.
