### ISSUE TITLE
File permissions readiness check issues

### ISSUE THREAD

**Issue by rackyan** [magento/magento2#9493]
I'm installing magento 2.1.6 on Google Computer Engine (GCE). i did everything according to magento 2 installation requirement but at the end i don't know how to solve this error.
Starting Magento installation:
File permissions check...

![pemission error](https://cloud.githubusercontent.com/assets/28351786/25663398/2709ba70-304a-11e7-866d-32af5c9c9ceb.jpg)

I've run the commands : 
1, cd /var/www/html && find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento  ----- not works
2. chown -R apache:apache /var/www/html ------not works
3. chmod -R 777 app/etc && chmod -R 777 pub && chmod -R 777 var  -------not works

Centos 7
mysql 5.7.18
apache 2.4.6
php 7.0.18

Any idea to solve this problem?

**Comment by rparsi-commer** [comment]
@rackyan Are you sure the permssions changed, and the owner and group names are correct?

**Comment by magento-engcom-team** [comment]
@rackyan, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
