### ISSUE TITLE
Enabling JS Bundling on the Default Luma is not working

### ISSUE THREAD

**Issue by Khaleel** [magento/magento2#9504]
### Preconditions

1. Magento 2.1.6 CE
2. Localhost (PHP, mySQL)

### Steps to reproduce

1. Install Magento 2 via AMPPS
2. Install Sample Data via Composer `php bin/magento sampledata:deploy` 
3. Turn on JS Merging, Bundling and CSS merge and minify all the yes

### Expected result

1. The Magento Luma theme should work and show the working homepage
2. The JS should be bundled without any issues

### Actual result

1. I receive JS errors on homepage - admin JS errors too

<img width="1424" alt="screen shot 2017-05-04 at 1 51 03 pm" src="https://cloud.githubusercontent.com/assets/355336/25698699/f0160758-30d0-11e7-9e0f-9e589aac5a9f.png">
<img width="801" alt="screen shot 2017-05-04 at 1 50 54 pm" src="https://cloud.githubusercontent.com/assets/355336/25698700/f01be5ec-30d0-11e7-96ec-16d4eb7eeb08.png">

Note: When I did this without sample data (no data or sample modules) everything worked smoothly.
Note: I cannot login to admin now and restore since the JS is not working
Note: This is with the default Luma, and default sample deploy - no other configurations in admin were made apart from bundling and merging and minifying. I am in production mode.

**Comment by magento-engcom-team** [comment]
@Khaleel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
