### ISSUE TITLE
Unable to checkout

### ISSUE THREAD

**Issue by GianlucaBelardinelli** [magento/magento2#9508]
### Preconditions

1.  PHP 7.0, Magento 2.1.2
2. 

### Steps to reproduce

1.  There are 2 shipping methods. Free shipping if the subtotal is > 100€ and the weight is <= 10kg.
The second method is simply used using the flat rate weight based.
3. 

### Expected result

1.  I should see the Free shipping only if the condition written in 1. is true, otherwise show only the flat rate with the price based on the weight imported by the .csv.

### Actual result

1. 

The translation of the error message says: This shipping method is not available. Contact us for more info. 

![frontend](https://cloud.githubusercontent.com/assets/7030881/25706176/f0b66bc6-30df-11e7-98e8-9353491957da.png)

"Bartolini" is the courier that I'm using following the flat rate rule
"Spedizione Gratuita" is free shipping. 

For the screenshot above I expect to see only Bartolini as the Free shipping rule doesn't match the requirements.

Below you will see the Cart Rule created for the free shipping.
![backend](https://cloud.githubusercontent.com/assets/7030881/25706270/35851dba-30e0-11e7-920e-a4dbd79abed5.png)

Another screenshot below showing the shipping methods avbl.
![log](https://cloud.githubusercontent.com/assets/7030881/25706352/86223b54-30e0-11e7-8dc2-9cd3b10a63c2.PNG)

If I disable the cart rule for the free shipping method and clear magento + browser cache everything works but without the free shipping.

**Comment by marcosdsdba** [comment]
Please Check this steps :

1 - If exists and active Shipment Methods ( Admin --> Stores -> Configuration -> Sales -> Shipping Methods, set initial Zip Code (Origin postal code / From ) 
2 - Insert Zip Code first to calculate  Shipment. 
3 - Check in Catalog of the Product if product weight set correctly ( product configuration)

**Comment by GianlucaBelardinelli** [comment]
@MattBidas Still same issue.

**Comment by GianlucaBelardinelli** [comment]
Up

**Comment by marcosdsdba** [comment]
Check why fields marked in red in the image are null:


![shipping-86223b54-30e0-11e7-8dc2-9cd3b10a63c2](https://cloud.githubusercontent.com/assets/8545697/26418951/7d8879c2-4094-11e7-9603-45149cb6aaee.PNG)

**Comment by oleg-onufer** [comment]
Hi @GianlucaBelardinelli.
Unfortunately, I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?
