### ISSUE TITLE
Bookmarks fail positioning all columns if one column is disabled

### ISSUE THREAD

**Issue by jaykobi** [magento/magento2#9509]
When I remove a colum from a grid by disbling it, the columns are not longer positioned according to my bookmark. I cannt save any postioning at all. 

### Preconditions
1. Create a sales_order_grid.xml in any module 

```
<?xml version="1.0" encoding="UTF-8"?>
<listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <columns name="sales_order_columns">
        <column name="base_grand_total" class="Magento\Sales\Ui\Component\Listing\Column\Price">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="componentDisabled" xsi:type="boolean">true</item>
                </item>
            </argument>
        </column>
    </columns>
</listing>
```

### Steps to reproduce

1.  Open the Sales Order Grid. 
2. Move some columns around. 
3. Save as bookmark.
4. Reload the page

### Expected result

1.  The column should be in the bookmarked order.

### Actual result

1. The columns have default positions

Removing the custom sles_order_grid.xml or just setting `<item name="componentDisabled" xsi:type="boolean">false</item>`  restores the bookmarks abilitiy to sort the columns.

**Comment by bvboas** [comment]
Any news on this?

It's really annoying when you have multiple views to process different tasks and every time you have to change columns position..

**Comment by magento-engcom-team** [comment]
@skymeissner, thank you for your report.
We've created internal ticket(s) MAGETWO-80704 to track progress on the issue.

**Comment by gwharton** [comment]
I have the same issue in 2.2.0. It doesn't seem to matter for me whether I am displaying/hiding columns or not. Remembering ordering on any admin grid appears broken for me.

If I look in the ui_bookmarks table I don't see any entries for position. Here is the bookmark for my sales_order_grid.

`{"views":{"_1509993856713":{"label":"Graham","index":"_1509993856713","editable":true,"data":{"search":{"value":""},"filters":{"applied":{"placeholder":true}},"displayMode":"grid","columns":{"m2eProSMID":{"visible":true,"sorting":false},"increment_id":{"visible":true,"sorting":false},"billing_name":{"visible":true,"sorting":false},"shipping_name":{"visible":true,"sorting":false},"base_grand_total":{"visible":true,"sorting":false},"grand_total":{"visible":true,"sorting":false},"billing_address":{"visible":true,"sorting":false},"shipping_address":{"visible":true,"sorting":false},"shipping_information":{"visible":true,"sorting":false},"customer_email":{"visible":true,"sorting":false},"subtotal":{"visible":true,"sorting":false},"shipping_and_handling":{"visible":true,"sorting":false},"customer_name":{"visible":true,"sorting":false},"total_refunded":{"visible":true,"sorting":false},"gridactions_tracking":{"visible":true,"sorting":false},"ids":{"visible":true,"sorting":false},"created_at":{"visible":true,"sorting":"desc"},"status":{"visible":true,"sorting":false},"customer_group":{"visible":true,"sorting":false},"payment_method":{"visible":true,"sorting":false},"actions":{"visible":true,"sorting":false}},"paging":{"options":{"20":{"value":20,"label":20},"30":{"value":30,"label":30},"50":{"value":50,"label":50},"100":{"value":100,"label":100},"200":{"value":200,"label":200}},"value":20}},"value":"Graham"}}}`

I've cleared bookmarks table, removed all third party modules and still have no ability to save column ordering.

Don't know if it is related, but javascript console shows the following when trying to save/switch bookmarks after changing column orders.

```
JQMIGRATE: jQuery.parseJSON requires a valid JSON string  jquery-migrate.js:41:4
console.trace():  jquery-migrate.js:43
	migrateWarn https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery/jquery-migrate.js:43:5
	jQuery.parseJSON https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery/jquery-migrate.js:232:3
	complete https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/mage/backend/bootstrap.js:65:34
	fire https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery.js:3232:12
	fireWith https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery.js:3362:8
	done https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery.js:9855:5
	callback https://dev.gwharton.me.uk/pub/static/version1509990910/adminhtml/Magento/backend/en_US/jquery.js:10311:9
```

**Comment by Jakhotiya** [comment]
This bug can also be reproduced just by enabling single store mode. On product listing grid in Admin, websites column becomes disabled and hence this bug is reproduced.

It happens because when websites column is disabled 
in app/code/Magento/Ui/view/base/web/js/grid/listing.js
```js
  initElement: function (element) {
            var currentCount = this.elems().length,
                totalCount = this.initChildCount;

            if (totalCount=== currentCount) {
                this.initPositions();
            }

            element.on('visible', this.updateVisible);

            return this._super();
        }
`totalCount=== currentCount)` fails because totalCount is total number of child elements to initialize but currentCount will always be less, because disabled components are never initialised.

`

**Comment by engcom-Echo** [comment]
Hello All,

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions**
1. Create a sales_order_grid.xml in any module 

```
<?xml version="1.0" encoding="UTF-8"?>
<listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <columns name="sales_order_columns">
        <column name="base_grand_total" class="Magento\Sales\Ui\Component\Listing\Column\Price">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="componentDisabled" xsi:type="boolean">true</item>
                </item>
            </argument>
        </column>
    </columns>
</listing>
```
**Steps to reproduce:**

1. Open the Sales Order Grid.
2. Move some columns around.
3. Save as bookmark.
4. Reload the page

**Result**
The column is in the bookmarked order.
![Peek 2019-12-13 14-58](https://user-images.githubusercontent.com/51681435/70802719-db625a80-1dba-11ea-8c58-ee84b99284cf.gif)
So I have to close this issue.
Thanks for your report!

**Comment by adambenovic** [comment]
This issue still exists all these years later (2.4.2-p2).
engcom-Echo tested it obviously wrong, browser bookmark has nothing to do with Magento functionality.
Jakhotiya is absolutely right about the cause of this.
