### ISSUE TITLE
Magento 2 sample module

### ISSUE THREAD

**Issue by nmohanswe** [magento/magento2#951]
Hi 

I have created the new module under app/code with the following structure. But I can't see the module name in backend under 'Advanced' tab.

app/code/Dckap/Welcome/etc/module.xml

<?xml version="1.0"?>
<config>
    <module name="Dckap_Welcome" schema_version="0.0.1" active="true">
        <sequence>
            <module name="Magento_Core"/>
        </sequence>
    </module>
</config>

Thanks
Mohan N

**Comment by choukalos** [comment]
Check out - https://github.com/coldgreentea/m2extension a few of our developers threw this together to show how you'd update the config, composer files and use the installer tool to get a new module to be detected & installed by the system.  

I believe you need to edit the app/etc/config.php , the composer.json file and run the installer tool to get the new module to be detected.

**Comment by tzyganu** [comment]
You can give this a try: https://github.com/tzyganu/Magento2SampleModule. It's something I put up last week. You also have an explanation on how to install. https://github.com/tzyganu/Magento2SampleModule#install

**Comment by antonmakarenko** [comment]
@nmohanswe I tried the sample module that @tzyganu provided -- it works.

Here are 2 ways to make it appear in your system:

For a fresh install:
1. Copy it into ``app/code`` directory
2. Install Magento system via CLI installer or Web Wizard
3. You can observe the module in the module list (``app/etc/config.php``), as well as in the Admin -> Stores -> Configuration -> Advanced -- it happens to be the last item in the list.

For an existing Magento instance:
1. Copy it into ``app/code`` directory
2. Edit ``app/etc/config.php`` and add the module to the list (see 'modules' section)
3. Run upgrade through Setup CLI:
```
cd setup
php -f index.php update
```
Observe the 'Sample_News' at the end of list
