### ISSUE TITLE
Unable to change the Shipping Address Label and to add drop-down value under text box in checkout page Magento 2.x

### ISSUE THREAD

**Issue by kikinbenshakib** [magento/magento2#9513]
I was trying to change the Checkout page shipping address fields label but I can't find the files where I can change them.

I have checked all the files of shipping address files but I am unable to change the Label text.

Please Magento 2.x default checkout shipping address fields label and also check my desire text label for shipping address.
![shipping 2](https://cloud.githubusercontent.com/assets/22374102/25710264/92d236ec-310d-11e7-9a3e-fe82416e7041.png)
![shipping](https://cloud.githubusercontent.com/assets/22374102/25710262/92983352-310d-11e7-8676-6c333a13e6f8.png)

**Comment by korostii** [comment]
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by kikinbenshakib** [comment]
Hello,
I am looking for some help about checkout page.

Could you please help me out.

**Comment by veloraven** [comment]
@kikinbenshakib if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for advice or discussion, please refer to forums specified above.

**Comment by magento-engcom-team** [comment]
@kikinbenshakib  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
