### ISSUE TITLE
South Korea Zip Code Validation incorrect

### ISSUE THREAD

**Issue by wigman** [magento/magento2#9515]
### Issue
Zip code validation fails on adresses from South Korea since it validates against deprecated format.
Current validation is 123-456. This *should be* 12345.

"Postal codes in South Korea are 5-digit numeric, whose system newly introduced in August 1, 2015." (https://en.wikipedia.org/wiki/List_of_postal_codes_in_South_Korea)

### Preconditions
On all 2.* versions including development branch.

### Steps to reproduce
go to cart or checkout, select South Korea and insert postal code 12345

### Expected result
Validation should succeed.

### Actual result
Validation fails

### Solution
Replace:
`    <zip countryCode="KR">
        <codes>
            <code id="pattern_1" active="true" example="123-456">^[0-9]{3}-[0-9]{3}$</code>
        </codes>
    </zip>`
With:
`    <zip countryCode="KR">
        <codes>
            <code id="pattern_1" active="true" example="12345">^[0-9]{5}$</code>
        </codes>
    </zip>`
OR add it as a second pattern (for backwards compatibility ?)

in /app/code/Magento/Directory/etc/zip_codes.xml

**Comment by VasylShvorak** [comment]
@wigman Thanks for reporting this issue. Created internal issue MAGETWO-70281 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@wigman, thank you for your report.
We've created internal ticket(s) MAGETWO-70281 to track progress on the issue.

**Comment by EmilyPepperman** [comment]
I have this same issue. Just had a new South Korean customer try and place an order.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch
