### ISSUE TITLE
Product attribute property "is_visible" does not having a correct value in REST API

### ISSUE THREAD

**Issue by feelinc** [magento/magento2#9520]
### Preconditions
1. Magento 2.1.6
2. PHP 7.0.x

### Steps to reproduce
1. Try GET "/rest/V1/products/attributes/:attributeCode" using Postman; or ---.
2. Try GET "/rest/V1/products/products/attributes?searchCriteria[filterGroups][0][filters][0][field]=is_visible&searchCriteria[filterGroups][0][filters][0][value]=1&searchCriteria[filterGroups][0][filters][0][conditionType]=eq" using Postman.

### Expected result
1. "is_visible" property should return correct value. 
2. Should not return attributes that does not visible.

### Actual result
1. Product Attribute in Magento admin :
![selection_306](https://cloud.githubusercontent.com/assets/345562/25735540/4c625082-3196-11e7-8935-0d28b0dbd41f.jpg)

2. Product Attribute in REST API response :
![selection_305](https://cloud.githubusercontent.com/assets/345562/25735545/5274b7c6-3196-11e7-970c-4886a15cc92b.jpg)

**Comment by RomanKrut** [comment]
@feelinc Hi, the problem as you described is not about "is_visible" type, it`s about "is_visible_on_front" and it has value  "0", if you change visible on admin grid to "Yes" it changes "is_visible_on_front" to value "1".

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
