### ISSUE TITLE
Cart Price Rule can be saved with invalid date

### ISSUE THREAD

**Issue by kozhemyakin** [magento/magento2#9522]
Magento 2.1.6 CE

Steps:
1. Log in to Admin
2. Go to Marketing -> Cart Price Rules -> Click "Add new" button
3. Fill in all required fields
4. Input "111" or "123" numbers in "From"/"To" fields
5. Click "Save" button

Actual result: the rule is successfully saved
Expected result: "Please enter a valid date." message appears below the From/To fields

Best wishes.

**Comment by Andrii-Deineha** [comment]
@kozhemyakin  Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-70202.

**Comment by magento-engcom-team** [comment]
@kozhemyakin, thank you for your report.
We've created internal ticket(s) MAGETWO-70202 to track progress on the issue.

**Comment by p-bystritsky** [comment]
I think it's valid behavior. First two digits are treated as month, next as day, other as year.

**Comment by magento-engcom-team** [comment]
Hi @kozhemyakin

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@kozhemyakin thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
