### ISSUE TITLE
2.1.6 Config Cache Error when switching to production mode/ generating static content

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#9526]
Using php 7.0.18/ centos/nginx/redis/varnish and magento 2.1.6

When running
setup:static-content:deploy

receiving an error:

```
[Exception]                                                                                                                                                          
  Notice: unserialize(): Error at offset 0 of 1 bytes in /home/web/m2test/releases/20170505110400/vendor/magento/module-config/App/Config/Type/System.php on line 214
```

is it a bug in readFromCache()? Or am I doing something wrong?

All possible caches cleaned, folders under var/ removed, etc with the same result.

**Comment by phoenix-bjoern** [comment]
Getting the same error. I can successfully one language (bin/magento setup:static-content:deploy en_US) but when I deploy the second (bin/magento setup:static-content:deploy de_DE) I'm getting an exception:
`
[CredisException]         
  read error on connection 
`

After that I see the `Notice: unserialize()` errors and the static content is not deployed correctly.

**Comment by phoenix-bjoern** [comment]
Guess this is issue can be closed as it is a duplicate of https://github.com/magento/magento2/issues/9287.

**Comment by wintermute-84** [comment]
Thank you for pointing out original thread.
