### ISSUE TITLE
attribute.phtml does not respect translations

### ISSUE THREAD

**Issue by steros** [magento/magento2#9531]
### Preconditions
1. Magento 2.1.5
2. Have some language pack
3. Have some language other than english set for frontend

### Steps to reproduce
1. Enter a product description
2. Call your product detail page

### Expected result
1. Above the product description should be no text

### Actual result
1. A label element with the translation of "none" is placed above the product description

I have made a quickfix here:
update attribute.phtml to respect translation [#9502]

But this will fail if you do not use the translation of "none" as that label. So there should be another way to determine that case.

**Comment by korostii** [comment]
Duplicate of #9161 and #9295

**Comment by steros** [comment]
Thanks for linking!

**Comment by kweij** [comment]
I came here to note the same problem. It's fixed in the 2.2 RC tag:
https://github.com/magento/magento2/blob/2.2.0-RC1.3/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml

**Comment by orlangur** [comment]
Closing as duplicate of https://github.com/magento/magento2/issues/9161.
