### ISSUE TITLE
Grammar error on authentication popup

### ISSUE THREAD

**Issue by brenjt** [magento/magento2#9533]
### Expected result

1. The text in the authentication popup should say ```Checkout as a new customer```

### Actual result

1. Text current says: ```Checkout out as a new customer```

![image](https://cloud.githubusercontent.com/assets/1713885/25761858/8624d36e-3199-11e7-983b-bc270128f25a.png)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71833

**Comment by magento-engcom-team** [comment]
@brenjt thank you for your report.
The fix for this issue is already available in the develop branch. See PR #9533.

**Comment by purpletreesoft** [comment]
When is it going to be GA? well this was irritating for me so I ended up doing some work to fix it. See https://github.com/purpletreesoft/magento-checkout-fix
