### ISSUE TITLE
[Question] Are Spies and/or Mocks supported by JS Test Framework?

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#954]
Is there a built in way to spy on existing objects using the test framework?
I've looked at the qunit cookbook and the api docs but that turned up nothing, I might have missed it though.

What I'm looking for is something like [PHPUnit mocks](https://phpunit.de/manual/current/en/test-doubles.html#test-doubles.mock-objects), or [Jasmine Spies](http://jasmine.github.io/2.0/introduction.html#section-Spies).

```{.js}
var foo = jQuery('#foo');
spyOn(foo, 'setWidth');
// execute function under test
expect(foo.setWidth).toHaveBeenCalledWith(100);
```

Setting the expectations beforehand like in PHPUnit or mockery would work just as well.
Of course its possible to create that functionality manually, but it would be cool if it would be part of the testing framework since its such a common requirement.

**Comment by vkorotun** [comment]
Hi @vinai, unfortunately we do not support such cool features in existing version of our JS Test Framework. These very days our JavaScript experts are working on researching and implementing better testing capabilities. And btw, since you mentioned Jasmine, this framework is an one of the few we consider.

**Comment by Vinai** [comment]
Thank you @vkorotun, great to hear there is work being done in this area! For what its worth, I've had good experiences with karma test runner and jasmine.

**Comment by vkorotun** [comment]
@Vinai : Since we haven't heard back from you for quite some time, we'll go ahead and close this issue. If in case you have any additional questions, feel free to reach out to us by submitting a new issue.

**Comment by Vinai** [comment]
Thanks, that is fine. Thanks for all the updates, I have been taking note!
Right now I'm in the process of getting back into the current state of things, but unfortunately JS testing is not the first thing on the list.
