### ISSUE TITLE
Developer mode slow

### ISSUE THREAD

**Issue by grobx** [magento/magento2#9541]
### Preconditions

1. Magento 2.1.6 installed on macOS 10.12.4
2. PHP 7.0.11

### Steps to reproduce

1. Open/Refresh page (in developer mode)
2. Wait (???)
3. Explore code, make change, invalidate cache, go to 1

### Expected result

1. Processing should be faster than thoughts, otherwise, how can a developer do his work?

**Comment by JDavidVR** [comment]
on terminal run this command bin/magento setup:static-content:deploy -f it will generate al static files and your site will run faster.

**Comment by grobx** [comment]
Thank you @JDavidVR, I ran that command without the -f modifier (The "-f" option does not exist.) and it helps.
