### ISSUE TITLE
Not receiving Email in Magento 2.1.6

### ISSUE THREAD

**Issue by justanewbie00** [magento/magento2#9543]
It was working fine before in Magento 2.0.3 then when I upgraded to 2.1.6, the customer is no longer receiving emails.

### Preconditions
1.Upgraded to Magento 2.1.6

### Steps to reproduce
1. Order product in site
2. Sign in as guest
3. Check Email

### Expected result
1. Customer will receive new order email or other emails.

### Actual result
1. Customer didn't receive new order email or other emails.

**Comment by Tonop** [comment]
Does admin receive new order emails?

**Comment by justanewbie00** [comment]
I made a mistake. I installed a new module that is not compatible with the email transmission.
