### ISSUE TITLE
LogicException: Method 'getExtensionAttributes' must be overridden in the interfaces which extend 'Magento\Framework\Api\ExtensibleDataInterface'

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#9547]
This is driving me crazy. I have only sample data products.
Looks like this started to happen when updated to 2.1.6
But also was persistent after downgrading.

Feels like any manipulation with product is causing this error.

Can someone point out what can cause this?

`LogicException: Method 'getExtensionAttributes' must be overridden in the interfaces which extend 'Magento\Framework\Api\ExtensibleDataInterface'
. Concrete return type must be specified. Please fix :\Magento\Catalog\Api\Data\ProductInterface in /home/web/m2test/releases/20170508094011/vendor/magento/framework/Api/ExtensionAttributesFactory.php:68`

Tested same project locally with same database - don't see an error

### Preconditions

1. Magento 2.1.6
2. PHP 7.0.18
3. Nginx
4. Varnish

I'm including full stack trace if it helps:
[stack.txt](https://github.com/magento/magento2/files/983316/stack.txt)

**Comment by zhangjunwen** [comment]
I Get the same error, have fixed it?

**Comment by ihor-sviziev** [comment]
It looks like it's duplicate of https://github.com/magento/magento2/issues/5750
Please check your opcache config:
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-settings.html#php-required-opcache

**Comment by wintermute-84** [comment]
Yes, this is a duplicate and the problem is resolved in the other thread.
This one can be closed.
