### ISSUE TITLE
Custom free shipping don't work in Backend

### ISSUE THREAD

**Issue by strauss69400** [magento/magento2#9548]
### Preconditions
My website run with the version 2.1.6 It contains two store views.
The version of PHP is 5.6.24
The version of Mysql is 5.6.31

The problem is i create my custom method  which should be displayed only for the backend but it don't work! i get this error : Sorry, no shopping cart available for this order.

I followed several tutorials to create my method and here is the main code :
>     
     namespace Digitgold\Shippingbackend\Model\Carrier;

     use Magento\Quote\Model\Quote\Address\RateRequest; 
     use Magento\Shipping\Model\Rate\Result;
     use Magento\Backend\App\Area\FrontNameResolver;

     class Method extends \Magento\Shipping\Model\Carrier\AbstractCarrier    implements   \Magento  \Shipping\Model\Carrier\CarrierInterface
    {
 
    protected $_code = 'shippingbackend';

        /**
     * @var bool
     */
    protected $_isFixed = true;

    /**
     * @var \Magento\Framework\App\State
     */
    protected $appState;

    /**
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param \Magento\Shipping\Model\Rate\ResultFactory $rateResultFactory
     * @param \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory,
        \Psr\Log\LoggerInterface $logger,
        \Magento\Shipping\Model\Rate\ResultFactory $rateResultFactory,
        \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory,
        \Magento\Framework\App\State $appState,
        array $data = []
    ) {
        $this->_rateResultFactory = $rateResultFactory;
        $this->_rateMethodFactory = $rateMethodFactory;
        $this->appState = $appState;
        parent::__construct($scopeConfig, $rateErrorFactory, $logger, $data);
    }

    /**
     * @return array
     */
    public function getAllowedMethods()
    {
        return ['shippingbackend' => $this->getConfigData('name')];
    }

    protected function isAdmin()
    {
        if ($this->appState->getAreaCode() === \Magento\Backend\App\Area\FrontNameResolver::AREA_CODE) {
            return true;
        }
        return false;
    }

    /**
     * @param RateRequest $request
     * @return bool|Result
     */
    public function collectRates(RateRequest $request)
    {
        if (!$this->getConfigFlag('active')|| !$this->isAdmin()) {
            return false;
        }

    //    if ($this->appState->getAreaCode() == FrontNameResolver::AREA_CODE){
    //        return false;
     //   }

                /** @var \Magento\Shipping\Model\Rate\Result $result */
        $result = $this->_rateResultFactory->create();

        /** @var \Magento\Quote\Model\Quote\Address\RateResult\Method $method */
        $method = $this->_rateMethodFactory->create();

        $method->setCarrier('shippingbackend');
        $method->setCarrierTitle($this->getConfigData('title'));

        $method->setMethod('shippingbackend');
        $method->setMethodTitle($this->getConfigData('name'));

        /*you can fetch shipping price from different sources over some APIs, we used price from config.xml - xml node price*/
        $amount = $this->getConfigData('price');

        $method->setPrice($amount);
        $method->setCost($amount);

        $result->append($method);

        return $result;
    }

    }

I think my code is right.There is no reason for it to be false.
Here is a screenshot of the error returned:

![image](https://cloud.githubusercontent.com/assets/8798254/25804252/1462549a-33fb-11e7-9924-e8debafa18c5.png)

I tried to debug with firebug to see if the ajax request return a error but no error : 

![image](https://cloud.githubusercontent.com/assets/8798254/25804261/25d2589c-33fb-11e7-80b7-d75764505d2d.png)

Impossible to understand my custom method dont' work. If someone can help me solve this problem!!

I thank you for your help Best regards

**Comment by southerncomputer** [comment]
You sure the quote AND sales_order tables have enough space for your shipping method?? Last I checked I had to increase the size of quote columns to equal sales_order sizing!

IIRC quote shipping_method was 40 and sales_order shipping_method is 32 !

Oversized method would cause strange errors!

**Comment by strauss69400** [comment]
i found the problem.there was some parameters missing in adminhtml.xml
