### ISSUE TITLE
category category image show all image in all the category array collection

### ISSUE THREAD

**Issue by parasarora** [magento/magento2#9551]
After assigning Category image for the single category, the category show image to multiple category collection. But database shows a single entry for the image. That means image is displayed to all other categories which come after the category in alphabetical order.

1.  Assigned to single category
2. Alphabetical order of collection in ascending order.

![without image](https://cloud.githubusercontent.com/assets/11785509/25808376/805ed99e-3427-11e7-9e00-dcd5f6272047.png)

![withimage](https://cloud.githubusercontent.com/assets/11785509/25808366/78d90b9a-3427-11e7-9f0a-4d023a9689bd.png)

[category.txt](https://github.com/magento/magento2/files/983749/category.txt)

**Comment by korostii** [comment]
> the category show image to multiple category collection.
I am sorry, but that's just wrong.

The tree you see on the left is the category selector, and it shows multiple collections attached to the current _Store_. The content represented on the right part of the page is attached to the single highlighted category on the left (on your screenshot it's the "What's New" category).

If you click on a different category, you'll see some different content (including the image, if any). Thus, if you'd like to attach the image to multiple images, you'll have to perform multiple uploads for each of the categories separately and consecutively.

There is no issue here, that's exactly the expected behavior.

**Comment by parasarora** [comment]
If there is no content associated with another category, Category collection should not image of its previous category but it is showing image of previous category

**Comment by korostii** [comment]
Are you referring to the code from category.txt ? 
Well, yeah, it gives surprising results (seems to involve some leftover data from a previous category, I presume), but the code itself is just wrong (by Magento2.1 standards).

If you skip category reloading and get the data directly from the iterated item `$_category` instead, the results are okay: categories with no image return empty image URL.

Alternatively, here's how you load the category by ID "the right way":
`$category = $obj->get('Magento\Catalog\Model\CategoryFactory')->create()->load($_category->getId());`
Or, better yet:
`$category = $obj->get('Magento\Catalog\Model\CategoryRepository')->get($_category->getId());`

Direct loading through model is considered deprecated and might be missing important before/after load interceptors etc.

**Comment by magento-engcom-team** [comment]
@korostii Even better way would be not using the implementation of `CategoryRepository` directly but the `\Magento\Catalog\Api\CategoryRepositoryInterface`

**Comment by magento-engcom-team** [comment]
@parasarora, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

If you think this is a core issue anyway please reopen and edit issue description to include the preconditions, the steps required to reproduce, the actual result, and the expected result.

Thank you
