### ISSUE TITLE
Unable to add quantity_and_stock_status attribute to product filter in backend

### ISSUE THREAD

**Issue by wolfpeak** [magento/magento2#9552]
Hi all, I hope that you can help me. Please forgive me being fairly new at this and never having posted here before but I have tried searching with no real success at finding my issue.

### Preconditions
1. Magento 2.1.6
2. PHP 5.6.30

### Steps to reproduce
1. Store > Attributes > quantity_and_stock_status
2. Advanced Attribute Properties
3. Use in Filter Options > Yes
4. Save

### Expected result
1. Should save and then attribute should be visible in the product list filters in the backend

### Actual result
1. After pressing save I just get the spinning "Please Wait" and nothing happens.

![before](https://cloud.githubusercontent.com/assets/20665104/25815822/0264d71c-341a-11e7-9984-3fc2ed1381ab.PNG)
![after](https://cloud.githubusercontent.com/assets/20665104/25815823/026708ca-341a-11e7-8cc6-dc9965d7608d.PNG)

If there are any logs you need, if you could just point me in the right direction and I can retrieve them :)

**Comment by ghost** [comment]
I got same issue in 2.1.4

It looks like the issue that the quantity_and_stock_status attribute option inputs are disable, then when submit the form the option values are not been submitted.  

There is an existed ticket for this issue, https://github.com/magento/magento2/pull/9221

**Comment by ShapesGraphicStudio** [comment]
I'm having the same issue in 2.1.7.

I tried [this solution](https://github.com/magento/magento2/pull/9221/files), but no change.

**Comment by VasylShvorak** [comment]
@wolfpeak Thanks for reporting this issue. This issue is already addressed in internal ticket MAGETWO-69716. I’ve added your report on this issue to that ticket.

**Comment by Radiergummi** [comment]
Any progress on this issue?
Edit - I mean this is a bug breaking the interface and key functionality. We *need* to modify attributes.

**Comment by nei** [comment]
Having same issue on 2.1.7. 🐛

**Comment by ghost** [comment]
it's look that the issue is with some others product not only with quantity_and_stock_status. After pressing save the popup loads endlessly and nothing happen.
Did the issue solved ??

**Comment by Radiergummi** [comment]
This issue has resolved for me in 2.1.8 🎉

**Comment by magento-engcom-team** [comment]
@wolfpeak, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by im-jc** [comment]
Hi!

**Preconditions**
Magento version: 2.1.7
PHP 7.1

I have changed then value from database so now i can see changed value of `Use in Layered Navigation` field with `Filterable (with results)`.

BUT, it is not showing on front end layerd navigation like other dropdown attributes(Price, color).

How can i display 'quantity_and_stock_status' on front end layered navigation?i.e  In Stock and Out of Stock
 Please give suggetions. Thank you.
