### ISSUE TITLE
analytics.js script appears twice

### ISSUE THREAD

**Issue by gweeble** [magento/magento2#9555]
### Preconditions
Magento version 2.1.5, PHP Version 7.0.17, Mysql version: 5.6.35-81.0 Percona Server (GPL), Release 81.0, Revision c96c427

### Steps to reproduce
1. Turn on analytics in admin panel and input GA code
2. Save
3. refresh Frontend page

### Expected result
1. Single instance of ﻿the below code on page
<script>
//<![CDATA[
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXXX-XX', 'auto');
ga('send', 'pageview');
  //]]>
</script>
﻿
### Actual result
1. Get the following second js include inside head at the very top of the page HTML
<script async="" src="//www.google-analytics.com/analytics.js"></script>

Can't find mention of second script include in Vendor>Magento>Google_Analytics.

Happens even in local (Clean) install of Magento 2.1.5

Any help is appreciated.

Guy

**Comment by korostii** [comment]
I am sorry, but it sound a bit ambiguous, so I'd like to clarify this one detail in order to avoid any possible misunderstanding.
Do you, by any chance, mean the a whole actual GA script when you write "GA code"? (looks similar to http://www.lunametrics.com/wp-content/uploads/2012/02/trackingcode1.png )

Magento2 expects just a short identifier in there (like this: http://take.ms/xPBGt ) and generates the appropriate javascript code automatically.

**Comment by gweeble** [comment]
Korostii,

Thanks for getting back to me. I only have the short identifier in the magento admin backend.

In Clarification, on the front end if you look at the Page Source you see the following just inside head

<script async="" src="//www.google-analytics.com/analytics.js"></script>

Much lower down you see the proper "whole" Ga Script as expected.

Annoyingly that means that when we go to the Google Page Speed tool, it lists it as a blocking script, when of course it is set to async and doesn't load before the content.
Any further assistance is greatly appreciated.
Guy

**Comment by magento-engcom-team** [comment]
@bendraxguy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
