### ISSUE TITLE
ISSUE_TEMPLATE.md does account for feature requests

### ISSUE THREAD

**Issue by mpchadwick** [magento/magento2#9556]
[The issue template](https://github.com/magento/magento2/blob/62667cb65d69cd6028c9038dda0087684a3df834/ISSUE_TEMPLATE.md) is currently designed to streamline bug reports.  However, per [CONTRIBUTING.md](https://github.com/magento/magento2/blob/62667cb65d69cd6028c9038dda0087684a3df834/CONTRIBUTING.md), issues can also be used for feature requests...

> For large features or changes, please open an issue and discuss first. This may prevent duplicate or unnecessary effort, and it may gain you some additional contributors.

[Here](https://github.com/influxdata/telegraf/blob/5af985ef5f0824220e04ac47c100f288e4ec54f1/.github/ISSUE_TEMPLATE.md)'s an example of an ISSUE_TEMPLATE from another project I've contributed to that accounts for both bug reports, and feature requests.

### Preconditions

I have an idea for a feature request

### Steps to reproduce

I click the "New Issue" button on the "Issues" tab

### Expected result

There is a template explaining the standard format for feature requests

### Actual result

The template only shows the format for bug reports

**Comment by gsomoza** [comment]
Here's another one that's a bit more brief but covers both bugs and features: https://www.talater.com/open-source-templates/#/page/98

**Comment by korostii** [comment]
Nice idea, except when you actually do post a feature request in here, it might instantly get a response referencing https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96 
And after an issue gets the "improvement" label, then there's a bot handling the issue in the following manner: http://take.ms/KDbuS

**Comment by gsomoza** [comment]
Alright, that puts this idea to rest then :P

**Comment by mpchadwick** [comment]
I see. It might be worth updating the issue template to state that process, then. Also contributing.md says to open an issue, so that should be corrected as well.

**Comment by okorshenko** [comment]
If you would like submit a feature request, please, create it here: https://github.com/magento-engcom/community-features/issues/

**Comment by korostii** [comment]
> If you would like submit a feature request, please, create it here: https://github.com/magento-engcom/community-features/issues/

Wow, that's new. Does that mean the feature requests posted to [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) will be disregarded from now on (unless they have corresponding issues at engcom repo) or will you process those separately somehow?

If https://github.com/magento-engcom/community-features/issues/ is officially the new "go-to place" for feature requests, wold you mind to kindly update the [`Readme.MD`](https://github.com/magento/magento2/blob/2.2-develop/README.md) file for this repository and/or announce this information via other channels (devblog, email newsletter, etc.) ?
