### ISSUE TITLE
Feature Request: Add a "role" column to the users grid in the admin panel

### ISSUE THREAD

**Issue by mpchadwick** [magento/magento2#9557]
It would be useful if the "Users" grid in the admin panel had a column to show the "role" of each user. Without it, you must click into each user individually to see their respective roles. 

I can maybe prepare a pull request if there is agreement that this feature would be useful.

**Comment by magento-engcom-team** [comment]
@mpchadwick please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
We are looking for pull request from you! 👍  Thank you
