### ISSUE TITLE
Magento 2.1.3 payment issue with credit card after rollback

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#9559]
Magento 2.1.3 (production mode)
PHP 7
mysql (Maria DB)

### Steps to reproduce

1.  Updated to the Magento version 2.1.6 
2. errors with configurable products attributes not showing on front end.
3. rolled back to 2.1.3 version which was in production mode, as we could not afford more loss time.
4. minimised CSS, js and merged.
5.  from next day payment issues with credit card payments(Authipay), shows orders cancelled and the message under approval code says: **N:-5003:The order already exists in the database.**
6.Some orders are placed, but most of the orders are cancelled and return above message.

### Expected result

1.  order was placed successfully.

![approval code error](https://cloud.githubusercontent.com/assets/19605497/25846635/6ce74d50-34aa-11e7-8b90-c32d9d0af014.png)
![status cancel](https://cloud.githubusercontent.com/assets/19605497/25846670/94d1d466-34aa-11e7-92f2-b39e6501fea2.PNG)

**Comment by gsomoza** [comment]
> rolled back to 2.1.3 version which was in production mode, as we could not afford more loss time.

What did the rollback process involve, specifically? E.g. did you also roll back the database to the most recent backup prior to the upgrade attempt?

**Comment by nmallepally** [comment]
i did a backup of files, code and database before I started to do the upgrade.
when the upgrade was giving us problems with config product attributes, I rolled back files, media and DB which i took before the upgrade.

**Comment by gsomoza** [comment]
Ok, that sounds about right. Did you also run the post-deployment commands (e.g. "bin/magento setup:di:compile")? In other words: are you sure your environment is 100% how it was before the upgrade attempt?

**Comment by nmallepally** [comment]
Hi gsomoza,
 yes, the environment is 100% same as it was before the upgrade.
I haven't done anything once I rolled back.
I have also raised the issue with authipay, to check if the response is from their side.

**Comment by gsomoza** [comment]
Yes, that's a good idea, let's see what they say.

**Comment by nmallepally** [comment]
@gsomoza  Issue got solved. 
Issue was because the order number from Magento sent to Authipay Database was matching with the order numbers of our previous store woo-commemrce. So, Authipay sent us a repsonse, order already existed in database. I added a pre-fix to the Magento 2 order numbers and its working.

**Comment by gsomoza** [comment]
Great, glad to hear it's fixed!
