### ISSUE TITLE
Magento 2.1.0 Unable to place order. Please try again later.

### ISSUE THREAD

**Issue by khongtoan1991** [magento/magento2#9561]
I have issue when placeholder Credit card, when submit order i received error 
"Unable to place order. Please try again later." and in debug.log have list
array (
    'user' => '****',
    'vendor' => 'ehlerslongboards',
    'partner' => 'PayPal',
    'pwd' => '****',
    'verbosity' => 'HIGH',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'createsecuretoken' => 'Y',
    'securetokenid' => '90e3cf1aa4eb81a304889fda8310fa07',
    'returnurl' => 'https://elkwoodskateboards.com/index.php/paypal/transparent/response/',
    'errorurl' => 'https://elkwoodskateboards.com/index.php/paypal/transparent/response/',
    'cancelurl' => 'https://elkwoodskateboards.com/index.php/paypal/transparent/cancel/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'Dev',
    'lastname' => 'Test',
    'street' => '7501 slater ave, unit A',
    'city' => 'Huntington Beach',
    'state' => 'CA',
    'zip' => '92647',
    'country' => 'US',
    'email' => NULL,
    'shiptofirstname' => 'Dev',
    'shiptolastname' => 'Test',
    'shiptostreet' => '7501 slater ave, unit A',
    'shiptocity' => 'Huntington Beach',
    'shiptostate' => 'CA',
    'shiptozip' => '92647',
    'shiptocountry' => 'US',
  ),
  'result' => 
  array (
    'result' => '0',
    'securetoken' => 'LBTDV7SzLWkGq6134qLMjeQBS',
    'securetokenid' => '90e3cf1aa4eb81a304889fda8310fa07',
    'respmsg' => 'Approved',
    'result_code' => '0',
  ),
) {"is_exception":false} []

but then it came through my paypal but with 0 [dollars.]
![screenshot](https://cloud.githubusercontent.com/assets/20679116/25849805/1ae55f3e-34ea-11e7-8848-301315325bd6.png)

Please help me?

**Comment by gsomoza** [comment]
@khongtoan1991 I recommend you edit those tokens out of your issue just in case...

Have you followed the steps outlined in the [Magento 2 Paypal Setup](http://www.magestore.com/magento-2-tutorial/magento-2-paypal-setup/) tutorial?

**Comment by khongtoan1991** [comment]
@gsomoza i setup Payments Pro (Includes Express Checkout) and merchant info is true, because Paypal great active

**Comment by gsomoza** [comment]
Ok, in that case could you confirm you followed [these docs](http://docs.magento.com/m2/ce/user_guide/payment/paypal-payments-pro.html) carefully?

Are there any other 3rd-party extensions installed in the system which might affect the checkout? Anything dealing with orders, payments, invoices, etc. If the answer is "no": can you duplicate this issue (using the same Paypal account) in a vanilla Magento installation configured with PayPal Payments Pro?

**Comment by khongtoan1991** [comment]
Thanks @gsomoza. I will check guilde with [these docs](http://docs.magento.com/m2/ce/user_guide/payment/paypal-payments-pro.html) and when fixed i will said for you.

**Comment by khongtoan1991** [comment]
@gsomoza can you help me ?

**Comment by khongtoan1991** [comment]
@gsomoza thanks. I fixed this with setup account on paypal. Thanks yoy very much!

**Comment by gsomoza** [comment]
Glad I could help!

**Comment by khongtoan1991** [comment]
thans you! :))
