### ISSUE TITLE
Magento 2 Installation via Composer using Ansible | takes too much time

### ISSUE THREAD

**Issue by eligiable** [magento/magento2#9564]
### Preconditions
1. Ubuntu Server 16.04.2 LTS
2. Magento-EE-2.1.4_2017
3. Nginx 1.10.0
4. php 7.0.15
5. mySQL 5.7.18
6. Composer 1.4.1
7. Ansible 2.0.0.2

### Steps to reproduce
Automated the following steps using Ansible with Composer
(https://www.howtoforge.com/tutorial/how-to-install-magento-with-nginx-on-ubuntu/)

### Expected result
It should not take much time to just install Magento 2

### Actual result
Everything works fine, but it takes too much time, after running the following command to install Magento 2
`bin/magento setup:install --backend-frontname="adminlogin" \`

Thanx in Advance.

**Comment by gsomoza** [comment]
Can you confirm that it took significantly less time when you were NOT using Ansible? And any chance you could post some actual timings?

Provisioning a server will usually take quite some time. And if you're following that tutorial then you're also using Composer to download all packages, installing the database for the first time, etc - all of that *every time* you provision the server from scratch. So it's normal that a first time install takes a while for any project. Just make sure that you're not installing everything from scratch every time you deploy your application and you should be good: there's no reason for deployments to Production to take more than just a few seconds (EDIT: if you have a good CI pipeline).

**Comment by eligiable** [comment]
@gsomoza Thank you for the suggestion, made my life.

**Comment by veloraven** [comment]
@eligiable as I understand the issue was resolved and I can close it?
For future reports: please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
