### ISSUE TITLE
ajax on wysiwyg return "403 Forbidden"

### ISSUE THREAD

**Issue by matart15** [magento/magento2#9567]
### Preconditions

1. Magento 2.1
2. php 7.1
3. mysql 5.6

### Steps to reproduce

1. Fresh install via git clone
2. `composer install`
3. setup from browser
4. install complete with `no error`
5. frontend and backend works. Created category, and Product.
6. Admin -> Pages -> Home page -> edit `http://example.app/magento2/admin_8i3hwr/cms/page/edit/page_id/2/key/33798240ca4d1965118b424471c36c381801569acafb6755c540c6dd3b5f8258/`
7. on `wysiwyg` editor selected `Insert Widget` 
8. Select any widget an Click `Insert Widget` button
9. on chrome dev console ajax tryes to send `POST` request to this url.
 (http://example.app/magento2/admin_8i3hwr/admin/widget/buildWidget/key/a4f0a05cfb62e1c554638244b6d1602f476015b9cbaaecef4856092db94072c8/?isAjax=true)
And it returns `403 restricted`
10. Then if I click save it redirects to this url
(http://example.app/magento2/admin_8i3hwr/cms/page/save/key/3a6cdf3ff25932480c546293db1f9bb21581cc04b015c2c8a7905826dc0777d5/)
But result is `403 Forbidden`

### Expected result

1. `<img id="e3t3aWRnZXQgdHlwZT0iTWFnZW50b1xTYWxlc1xCbG9ja1xXaWRnZXRcR3Vlc3RcRm9ybSIgdGVtcGxhdGU9IndpZGdldC9ndWVzdC9mb3JtLnBodG1sIn19" src="http://127.0.0.1/test/magento2/pub/static/version1494327864/adminhtml/Magento/backend/en_US/Magento_Widget/placeholder.gif" title="{{widget type=&quot;Magento\Sales\Block\Widget\Guest\Form&quot; template=&quot;widget/guest/form.phtml&quot;}}">`

### Actual result

1. [Screenshot, logs]
`403 restricted`
![screen shot 2017-05-09 at 22 37 35](https://cloud.githubusercontent.com/assets/17027219/25854732/04fe7c4c-350c-11e7-9065-16dd7c6afe32.png)
![screen shot 2017-05-09 at 22 38 11](https://cloud.githubusercontent.com/assets/17027219/25854737/0b9113b2-350c-11e7-9238-28a268b940ee.png)

If I hide wysiwyg and write widget by code it works withoud problem.
```
<p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="babycar" show_pager="0" products_count="10" template="product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^]^]"}}</p>
```

My guesses :
1. I think this url is not recognized as route and apache trying to access it as a file.
(http://example.app/magento2/admin_8i3hwr/admin/widget/buildWidget/key/a4f0a05cfb62e1c554638244b6d1602f476015b9cbaaecef4856092db94072c8/?isAjax=true)
2. Or it is just permission of some file or dir which gets required in php code is not right. So apache can't access it. But I have no Idea how to debug it.

Please help

**Comment by gsomoza** [comment]
> I think this url is not recognized as route and apache trying to access it as a file.

You can test that quickly by duplicating the issue with Chrome Dev Tools open, then opening the `public/index.php` file and writing `die();` as the first PHP line (or you can put a breakpoint on the first line if you're using Xdebug) and saving it. Then right-click on the Dev Tools on the AJAX request that failed and choose "Replay XHR". If you still get a 403: that's Apache responding and not Magento. (there might be other ways of testing this too)

If it's Magento responding (the request results in a `200 OK` after you add the `die()` statement), could you check the logs to see if there are any messages there? Make sure all logging is enabled in the settings and that you're running Magento on development mode.

> it is just permission of some file or dir which gets required in php code is not right

This is less likely, because in that case you'd get something like `Fatal error: require(): Failed opening required 'path/to/some/file.php'` in the logs.

**Comment by matart15** [comment]
> "Replay XHR". If you still get a 403: that's Apache responding and not Magento. (there might be other ways of testing this too)

thank you @gsomoza. I tried `die();` in `pub/index.php` file. It return 403. 

But other successful ajax requests does not die. They return `200 OK` with response body. Even front home loads without problem. i flushed cache. result is same.

I thought that would stop magento.

But if i write `var_dump('qwerqwerqwer'); die();` in `app/bootstrap.php` it stoos with `string(12) "qwerqwerqwer"`. So it is accessing to Magento2.

apart from that I changed my .htaccess file. 
Now I got more strange response on `Insert widget` button. Other responses work fine.

response status is still `403 forbidden`. But response body is this image. with empty widget
```
<img id="e3t3aWRnZXQgdHlwZT0iIn19" src="http://videlabo.com/magento2/pub/static/version1494334020/adminhtml/Magento/backend/en_US/Magento_Widget/placeholder.gif" title="{{widget type=&quot;&quot;}}">
```

I double checked my apache error log. There is nothing.

**Comment by matart15** [comment]
OK I managed to get `var_dump` on this line.
https://github.com/magento/magento2/blob/develop/app/code/Magento/Widget/Controller/Adminhtml/Widget/BuildWidget.php#L39

If i add `var_dump([$html,$type,$params, $asIs]);` there with this formbody.

<img width="424" alt="screen shot 2017-05-10 at 15 14 21" src="https://cloud.githubusercontent.com/assets/17027219/25885438/468c814a-3593-11e7-93d2-3ad114f468e6.png">

 result is `403 Forbidden` and body is 
```
array(4) {
  [0]=>
  string(199) "<img id="e3t3aWRnZXQgdHlwZT0iIn19" src="http://videlabo.com/magento2/pub/static/version1494393907/adminhtml/Magento/backend/en_US/Magento_Widget/placeholder.gif" title="{{widget type=&quot;&quot;}}">"
  [1]=>
  NULL
  [2]=>
  array(0) {
  }
  [3]=>
  NULL
}
```

**Comment by gsomoza** [comment]
So the response body seems OK: it has the content, but that's certainly not what one would expect if there was a 403. Just to be thorough: you don't have any custom package requirements in `composer.json`: just a vanilla Magento 2 installation - correct? If you can confirm that then I'll try to duplicate the issue in a local environment.

**Comment by matart15** [comment]
Yes.

`git log`
```
commit 67ec6f98215e2926daa9a0262301baa9950af72e
Merge: b6fb045 a33997c
Author: Alex Paliarush <paliarush@users.noreply.github.com>
Date:   Tue May 9 17:02:25 2017 -0500

    Merge pull request #1080 from magento-okapis/okapis-mainline-2.2-pr

    [okapis] MAGETWO-64944: Product status is always changing back to "Enabled" after "rest/all/V1/products" REST API call

commit a33997c140341b7485749e6a2eb09c090adb1d65
Merge: 38ab4b5 b6fb045
Author: Robert He <rohe@magento.com>
Date:   Tue May 9 09:56:01 2017 -0500

    Merge branch 'develop' of https://github.com/magento/magento2ce into okapis-mainline-2.2-pr
```

`git status`
```
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .htaccess
	modified:   pub/.htaccess

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	composer.phar

no changes added to commit (use "git add" and/or "git commit -a")
```

`git diff`
```
diff --git a/.htaccess b/.htaccess
index 90b9c16..bc6c2f4 100644
--- a/.htaccess
+++ b/.htaccess
@@ -11,6 +11,7 @@

 #    Action php5-cgi /cgi-bin/php5-cgi
 #    AddHandler php5-cgi .php
+AddHandler x-httpd-php71 .php

 ############################################
 ## GoDaddy specific options
@@ -135,7 +136,8 @@
 ############################################
 ## enable rewrites

-    Options +FollowSymLinks
+    #Options +FollowSymLinks
+    Options +SymLinksIfOwnerMatch
     RewriteEngine on

 ############################################
diff --git a/pub/.htaccess b/pub/.htaccess
index bdae9be..e4dd711 100644
--- a/pub/.htaccess
+++ b/pub/.htaccess
@@ -131,7 +131,8 @@
 ############################################
 ## Enable rewrites

-    Options +FollowSymLinks
+    #Options +FollowSymLinks
+    Options +SymLinksIfOwnerMatch
     RewriteEngine on

 ############################################

**Comment by matart15** [comment]
Just after install it on my remote server I changed 2 .htaccess file from `+FollowSymLinks` to `+SymLinksIfOwnerMatch`. 

that is it. I now trying it on my local machine and ajax works. Confusing.

**Comment by matart15** [comment]
var_dump in this line (https://github.com/magento/magento2/blob/develop/app/code/Magento/Widget/Controller/Adminhtml/Widget/BuildWidget.php#L39)
```
$a = $this->getRequest();
        var_dump([
            //$html,
            $type,
            print_r($a->getParams(), true)
            //$params,
            //$asIs
        ]);
```

on my local PC it responds with 
```
array(2) {
  [0]=>
  string(37) "Magento\Sales\Block\Widget\Guest\Form"
  [1]=>
  string(324) "Array
(
    [key] => 30008382d7c5557c1faea488b3c77c853dbea8f904c829f76d35df5535e7d9af
    [isAjax] => true
    [form_key] => umSndNjPI6vK8Y2n
    [widget_type] => Magento\Sales\Block\Widget\Guest\Form
    [parameters] => Array
        (
            [title] => 
            [template] => widget/guest/form.phtml
        )

)
"
}
```

but on my server 
```
array(2) {
  [0]=>
  NULL
  [1]=>
  string(88) "Array
(
    [key] => b789b14faa8621a7f8ae6d4e55d50563506ebbdd20f4a660b5d578d5d2e9791c
)
"
}
```

request headers are very same. `POST` with 
```
isAjax:true
form_key:umSndNjPI6vK8Y2n
widget_type:Magento\Sales\Block\Widget\Guest\Form
parameters[title]:
parameters[template]:widget/guest/form.phtml
```

**Comment by gsomoza** [comment]
Yes, that's what I'm thinking: it definitely looks like an Apache configuration issue on the server. Maybe related to that `SymLinksIfOwnerMatch` change? [Check if this helps](http://stackoverflow.com/questions/11901993/options-followsymlinks-or-symlinksifownermatch-is-off).

**Comment by matart15** [comment]
I tried to add those lines. But I am on shared server and It seems i cant write to httpd.conf. plus server documentation says we have to use `SymLinksIfOwnerMatch` instead of `FollowSymLinks `. Seems like I hit the wall.

`$this->getRequest()->getParams()`. This line seems not getting post params on my server. `$_POST` is empty array on server.
I thought request parameters are not affected by server config. 

Any other suggestions

**Comment by gsomoza** [comment]
You may have already tried it, but just in case: try to see if [this helps](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html#install-apache-403_2.4).

Otherwise I would try to get in touch with your hosting company's support team: they should be able to help fix this quick. If necessary point them to those docs.

**Comment by matart15** [comment]
Yes. it seems apache setting problem.
I try to connect to my hosting company.
Thank you.

**Comment by matart15** [comment]
One thing I don't understand is 

on server other ajax requests like get options tag request could read request params.
(http://example.app/magento2/admin_rxa86v/admin/widget/loadOptions/key/6f21d805d7ce68a9974f9df2b316ae45f02a980972f1d9e092003e2b83622cb4/?isAjax=true)

`$_REQUEST` returns 
```
array(3) {
    ["isAjax"]=>
    string(4) "true"
    ["widget"]=>
    string(72) "{"widget_type":"Magento\\Sales\\Block\\Widget\\Guest\\Form","values":{}}"
    ["form_key"]=>
    string(16) "KjgcXVyygAs5o1I4"
  }
```


but next request returns `$_REQUEST` return empty array.
(http://example.app/magento2/admin_rxa86v/admin/widget/buildWidget/key/f205836a1a8ea2c2a8cc6853faaa66d78e653eadb98637892277cb2fde7e7ccb/?isAjax=true)
```
  array(0) {
  }
```

isn't this code related

**Comment by matart15** [comment]
OK. I found the issue. 
It seems apache mod_rewrite does not redirect POST params.

my dir structure is 
```
/apacheroot
      .htaccess
      /magento2
            /pub
            .htaccess
            index.php
            ... 
```

other ajax requests worked maybe because they were not redirected. But buildWidget ajax request seems redirecting.

Now new question is 
`How can I set magento2 in subdirectory` and let post ajax redirect work

**Comment by gsomoza** [comment]
Oh, of course, I didn't realise you were running Magento 2 in a subdirectory. You should definitely try to set that up in a way that you're not redirecting anything at all - using proxies, apache rewrites, or modifying the file structure. 

Sorry I don't have experience running in a subdirectory, but you could try to see if [this helps](https://magento.stackexchange.com/questions/145401/how-to-run-magento-2-from-a-subdirectory)... Or maybe someone else in the community can help you further. Good luck!

**Comment by matart15** [comment]
@gsomoza thank you for advice.

I tried installing it on root folder. Other functions work same as usual. But this time ` buildWidget ajax request ` returns `404 not found`.

after install it on my remote server I changed 2 .htaccess file from `+FollowSymLinks` to `+SymLinksIfOwnerMatch`.

Now I guess it is apache config problem.

Thanks again.

**Comment by matart15** [comment]
It seems problem is apache redirect related closing the issue
