### ISSUE TITLE
CLI catalog:image:resize command doesn't work for images set as "Hide from Product Page"

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#9569]
### Preconditions
1. Install clean Magento 2.1.6 on PHP7

### Steps to reproduce
1. Create simple product with 2 images. Image A, set as "Base, Small and Thumbnail" and tick "Hide from Product Page". Image B, leave as-is.
2. Clear image cache
3. run bin/magento catalog:image:resize

### Expected result
1. Navigating to the product listing should show image A. Clicking through the product should show an image gallery with only image B.

### Actual result
1. Image A returns 404 on product listings. When clicking through to the product page, image B works as expected.

It seems to me that there's some buggy behaviour with the new `catalog:image:resize` command that doesn't take into account hidden images.

Above demonstrated method is very useful in having a different product image for the product listings, and product pages (due to image ratio, etc.).

**Comment by erfanimani** [comment]
Sorry - this one can be closed; duplicate of #9498

**Comment by choukalos** [comment]
Closing as dup.
