### ISSUE TITLE
Search for products not returning products already defined in dB?

### ISSUE THREAD

**Issue by scheung38** [magento/magento2#9572]
Already defined products in admin page, but when searching for it by name:

Search : Entry Package

Search returns empty?

<img width="931" alt="screen shot 2017-05-09 at 20 38 01" src="https://cloud.githubusercontent.com/assets/1273014/25869244/8e26b51c-34f7-11e7-9b1d-814f0314f60d.png">

**Comment by choukalos** [comment]
Are you doing a quick search from the storefront?

Has cron run a few times or have you triggered a FullText search reindex action after creating the product but before doing the search on the store front?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
