### ISSUE TITLE
Content Tab in Admin is returning 404 error Page not found

### ISSUE THREAD

**Issue by auroralabs** [magento/magento2#9573]
### Preconditions

1. Magento CE2.1.6, 
2. PHP 7.0.17
3. mySQL 5.6.34

### Steps to reproduce

1. Clicking Content tab in Admin
2. Select any Option ie Products, Widgets
3. No pages are retuened

### Expected result

1. Product Listing

### Actual result

1. [Screenshot, logs]
![screen](https://cloud.githubusercontent.com/assets/1214196/25873714/702aaa86-3507-11e7-9a03-611bfc76592e.jpg)

**Comment by nshiff** [comment]
Do you have any custom themes or extensions - does the issue persist with a stock Magento codebase? Beyond that I would try typical frontend fixes:

    composer install
    rm -rf var/di var/generation var/view_preprocessed var/page_cache var/cache
    magento setup:upgrade
    grunt clean && grunt exec && grunt less # or equivalent for snowdog scss
    magento setup:di:compile
    magento setup:static-content:deploy

These commands will take a few minutes to run. If the whole process is taking more than 10 min, then something is wrong.

If the error still persists (with a stock codebase), then I would start suspecting a defect in the framework.

**Comment by magento-engcom-team** [comment]
@auroralabs, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
