### ISSUE TITLE
why magento should not create like prefernce.xml,plugin.xml,type.xml,virutaltype.xml

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#9575]
present di.xml file contains preferences,plugins,types,virtualtypes.i think its better to create separate file for each concept.
advantages: present no idea.i will try to figure it out.just suddenly i got idea like this.because magento following for other xml files like this.for example routes.xml,events.xml.

**Comment by korostii** [comment]
Please post your suggested improvements on the [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests), as instructed [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572).
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
