### ISSUE TITLE
Magento 2 is not support PHP 7.1.4?

### ISSUE THREAD

**Issue by vanloc0301** [magento/magento2#9576]
I using ArchLinux, default PHP version is 7.1.4.

I tried to install Magento 2. But I have an error like this:

> - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.4) does not satisfy that requirement.

What wrong with me? Thanks.

**Comment by korostii** [comment]
The PHP version, obviously. It says that right there.

PHP 7.1 isn't supported by Magento2 (yet).
Please the full list of Magento2 environment requirements [here](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html).

**Comment by vanloc0301** [comment]
@korostii Have any method to resolved my problem?

I tried to downgrade my PHP version but it's not working.

**Comment by korostii** [comment]
Not really. 
You'll need downgrade to a different PHP version (unless you are prepared to wait for the who-knows-when-it-will-be-released Magento 2.2).

**Comment by vanloc0301** [comment]
Thanks @korostii
