### ISSUE TITLE
Issue in different admin user have different Catalog Product search result  -  Magento 2.1.4

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#9578]
We are getting an issue in multiple admin user login, we have more then one admin users, 

> When we tried to search catalog products using first user then result will be fine, it will displays product with enable and disable status (All products in search criteria). 
  
> But if we have logged in with another user and search same thing as per first user then the result was different. Only enabled product showing on that list, disabled products not showing, Also when we tried to sort via Column title then it will be fine.

**Comment by southerncomputer** [comment]
I noticed this exact same bug today! Touching the column sort fixed the mis-applied filter.

Until then there were no filters on admin user 51 and only 1.4M products were showing. After touching the sort-by on any column it expanded to the full 1.65M products!

I will have to see if I can recreate this problem!

**Comment by veloraven** [comment]
@aasim110 please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by aasim110** [comment]
Issue fixed after upgrade version 2.1.7
