### ISSUE TITLE
Checkbox column rendered disabled

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#958]
I discovered this by mistake, because of some issue with my code, but it might be a real issue under some circumstances.  
There is an issue with the `Magento\Backend\Block\Widget\Grid\Column\Renderer\Checkbox::render` method.  
If the result of `$row->getData($this->getColumn()->getIndex())` is `null` and there are no disabled values specified then the checkbox is always disabled because the expression `$value === $this->getColumn()->getDisabledValue()` always evaluates to `true`.  
I think there should be a verification if both values are `null` (or something).  
I reproduced this while working on a sample module, but here is how you can reproduce it with the core code.  

**Preconditions:**
 - Magento2 beta3 installed
 - Sample Data installed.

**Steps**
 - Edit the method `Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Crosssell::_prepareColumns()`
 - Add this code after the first column definition: 

<pre><code>
     $this->addColumn(
            'dummy',
            [
                'type' => 'checkbox',
                'name' => 'dummy',
                'values' => [1,2,3],
                'align' => 'center',
                'index' => 'some_dummy_attribute',
                'header_css_class' => 'col-select',
                'column_css_class' => 'col-select'
            ]
        );
</code></pre>
 - Go to Products->Catalog and edit one product. 
 - Click on the Cross Sells tab. 
 - Click on Reset filter.

**Expected result**
 - I should see a new checkbox column with all checkboxes enabled

**Actual result**
 - in my new column all checkboxes are disabled even if I didn't tell Magento to make them disabled.
![checkboxes](http://i.imgur.com/goVxILE.png)

**Comment by vkorotun** [comment]
Thank you, @tzyganu, this seems to be an issue with render method as you've figured it out.
Thank you for posting this, and we'll proceed with further steps.
P.S. And as you may have noticed already (or will do), we yet do not support additional checkboxes in grids on the client side (JavaScript), so it will be impossible to select/deselect those and submit properly without customizing JavaScript.

**Comment by tzyganu** [comment]
@vkorotun I understand that the js needs to be changed. The purpose of the example was to show the issue with the `render` method.  
But in case I try to use this in a custom module (custom grid) I can control the javascript so this is not an issue.  
I didn't want to post my full module here because it made no sense. I chose a simple example to show the problem (disregarding the side effects).

**Comment by vkorotun** [comment]
Linked to internal ticket: MAGETWO-34163

**Comment by tzyganu** [comment]
This seams to be solved now. I will close the issue. Thanks for the fix.
