### ISSUE TITLE
catalog_url_rewrite_product_category table missing PK

### ISSUE THREAD

**Issue by siliconalchemy** [magento/magento2#9581]
The catalog_url_rewrite_product_category table is missing a PK.  Because of this, it cannot be replicated reliably in Galera based systems (eg. MariaDB, Percona XtradbCluster).  It appears to be the only table without a PK.  This is more of a problem with PXC 5.7 as it recommends enforcing strict mode which will actively break usage of this table.

Magento 2.1.5
Mysql: Percona XtraDBCluster 5.7

### Preconditions
Magento 2.4-develop

### Steps to reproduce
1. Open database table `catalog_url_rewrite_product_category`
2. Check if the table has a Primary Key

### Expected result
The database table `catalog_url_rewrite_product_category` has Primary Key

### Actual result
The database table `catalog_url_rewrite_product_category` doesn't have Primary Key
![primary_key](https://user-images.githubusercontent.com/51680745/103774172-d19a3d80-5034-11eb-8fc5-dbf4cc5372fb.png)

**Comment by veloraven** [comment]
@siliconalchemy please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by siliconalchemy** [comment]
Did you read this?  How much more specific do you want it to be?  Never mind, you can leave your (buggy) project buggy (ier).

**Comment by korostii** [comment]
Hi @veloraven, @magento-team,
The description seems quite extensive. Could you maybe pass this along to someone having some technical expertise in this field?

**Comment by ihor-sviziev** [comment]
@engcom-Golf @engcom-Alfa could you double check if this issue still valid, as we're having bugfix in #25746, so I'm not sure if it's valid

**Comment by siliconalchemy** [comment]
Go away stalebot, this is still a valid issue.

**Comment by engcom-Bravo** [comment]
Hello @siliconalchemy 

Thank you for your report.

We Confirm that the issue is still valid on 2.4-develop, and we have added Precondition, Steps to reproduce, ER and AR to the description.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40317` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
This bug was fixed in scope of internal issue B2B-1663
https://github.com/magento/magento2/commit/ece2528a6f09da1486d63ddd794f746501984413

**Comment by zakdma** [comment]
@siliconalchemy it fixed

**Comment by magento-engcom-team** [comment]
Hi @siliconalchemy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-40317` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by ihor-sviziev** [comment]
@zakdma @joanhe, please check the https://github.com/magento/magento2/issues/33770 that was caused by the fix https://github.com/magento/magento2/commit/ece2528a6f09da1486d63ddd794f746501984413, maybe you could provide some workaround?
