### ISSUE TITLE
Magento 2.1.5 - Dashboard revenue / tax / shipping = zero

### ISSUE THREAD

**Issue by VansonLeung** [magento/magento2#9585]
Is it a bug, and how to fix it?

![2017-05-11 1 18 15](https://cloud.githubusercontent.com/assets/1129695/25911925/206ab2d4-35e8-11e7-9e8f-ccf517fca50c.png)

**Comment by veloraven** [comment]
@VansonLeung please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for advice, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as GitHub issue tracker is intended for technical issues only.
