### ISSUE TITLE
Magenta 2.1.5 - How to change the Magento Admin page title?

### ISSUE THREAD

**Issue by VansonLeung** [magento/magento2#9586]
<img width="1280" alt="2017-05-11 1 18 32" src="https://cloud.githubusercontent.com/assets/1129695/25911944/34558da0-35e8-11e7-8fb9-62fffd7e7861.png">

How to change the above Magento Admin title? Client wants to hide "Magento Admin" from the admin panel, but I tried searching through the /vendor/magento-backend , attempted to change i18n and <title>...</title> but it still shows "Magento Admin". What else should I do?

**Comment by nshiff** [comment]
(Note, this type of question is better suited to [StackOverflow](magento.stackexchange.com). This issues list is more for defects and feature requests in the framework.)

Here is a thread addressing the same question: [How to name the browser tab title magento2](https://magento.stackexchange.com/questions/134979/how-to-name-the-browser-tab-title-magento2). The only difference is that they are probably using a typical frontend theme, where you are trying to modify the backend theme: see `vendor/theme-adminhtml-backend`.

As you can override the default with a custom frontend theme, you can create overrides in a custom backend theme. See thread [How to enable custom admin theme in Magento 2](https://magento.stackexchange.com/questions/124336/how-to-enable-custom-admin-theme-in-magento-2).

Good luck, and happy hacking.

**Comment by veloraven** [comment]
@VansonLeung the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
