### ISSUE TITLE
Admin label of product swatch not used in product editor

### ISSUE THREAD

**Issue by turtlecreations** [magento/magento2#9592]
### Preconditions
Magento version 2.1.6, clean install without any third party extensions installed or active.

### Steps to reproduce

1. create new visual swatch attribute
2. Add values like in the screen shot. in my case I have 3 labels. Admin, storefront "nederlands" and storefront "engels"
3. Add the attribute to an new attribute set
4. create new product with the attribute set
5. pull the dropdown on the created attribute

### Expected result
In the dropdown list I would expect the admin values that where entered in the swatches admin value field. 

### Actual result
Instead there are storefront values.

<img width="957" alt="schermafdruk 2017-05-10 22 12 58" src="https://cloud.githubusercontent.com/assets/15908622/25920440/4723be0e-35d2-11e7-9e14-07b76dff359e.png">
<img width="470" alt="schermafdruk 2017-05-10 22 12 01" src="https://cloud.githubusercontent.com/assets/15908622/25920443/49f89b72-35d2-11e7-83dc-e1ee7b141076.png">

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70225 was created.

**Comment by magento-engcom-team** [comment]
@turtlecreations, thank you for your report.
We've created internal ticket(s) MAGETWO-70225 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@turtlecreations, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
