### ISSUE TITLE
Wrong subtotal when adding 2 or more gift card into cart

### ISSUE THREAD

**Issue by nguyetnguyen** [magento/magento2#9595]
### Preconditions

1. Magento 2 version 2.1.3

### Steps to reproduce

1. Create 2 physical gift card products. One is 50$, one is 100$. 
2. Add the first gift card 50$ into card. Subtotal is 50$ that is correct.
3. Adding the second gift card 100$.

### Expected result

1. Subtotal is 100$. The first gift card is 50$ and the second gift card is 50$.

### Actual result

1. Subtotal should be 150$. The first gift card is 50$ and the second gift card is 100$.

After debugging the problem, I see error on the file Magento\GiftCard\Model\Catalog\Product\Type\Giftcard.php

`protected function _getAllowedAmounts($product)
    {
        if ($this->_giftcardAmounts === null) {
            $allowedAmounts = [];
            foreach ($product->getGiftcardAmounts() as $value) {
                $allowedAmounts[] = $this->priceCurrency->round($value['website_value']);
            }
            $this->_giftcardAmounts = $allowedAmounts;
        }
        return $this->_giftcardAmounts;
    }`
When calling the second time, giftcardAmounts is not null, it returns the amount of the first gift card. Please update this. Thanks!

**Comment by kiranmaip** [comment]
To fix this issue we need to override the  function "prepare" in below path "Magento\Quote\Model\Quote\Item\Processor"

The below solution will resolve the issue 
 /**
     * Set qty and custom price for quote item
     *
     * @param Item $item
     * @param \Magento\Framework\DataObject $request
     * @param Product $candidate
     * @return void
     */
    public function prepare(Item $item, DataObject $request, Product $candidate)
    {
        /**
         * We specify qty after we know about parent (for stock)
         */
        if ($request->getResetCount() && !$candidate->getStickWithinParent() && $item->getId() == $request->getId()) {
            $item->setData(CartItemInterface::KEY_QTY, 0);
        }
        $item->addQty($candidate->getCartQty());
        $customPrice = $request->getCustomPrice();
        if (!empty($customPrice)) {
            $item->setCustomPrice($customPrice);
            $item->setOriginalCustomPrice($customPrice);
        }else {
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $ItemProduct = $objectManager->get('Magento\Catalog\Model\Product')->load($request->getProduct());
            if($ItemProduct->getTypeId() == 'giftcard') {
                $customPrice = $ItemProduct->getFinalPrice();
                if($request->getCustomGiftcardAmount()){
                    $customPrice = $request->getCustomGiftcardAmount();
                }
                $item->setCustomPrice($customPrice);
                $item->setOriginalCustomPrice($customPrice);
            }
        }
    }

**Comment by veloraven** [comment]
@nguyetnguyen thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. This will allow for proper tracking of issues at the account level.
I'm closing this issue because we can not treat it as GitHub issue as GitHub is intended for Community edition reports given no account management for CE users.

**Comment by nguyetnguyen** [comment]
@veloraven,
 I'm a developer of Balance Internet company. We are a gold partner of magento team. :)
About the issue, in the mean time I fixed by adding some code at the class Magento\GiftCard\Model\Catalog\Product\Type\GiftCard
`protected function _getAllowedAmounts($product)
    {
        $allowedAmounts = [];
        foreach ($product->getGiftcardAmounts() as $value) {
            $allowedAmounts[] = $this->priceCurrency->round($value['website_value']);
        }
        $this->_giftcardAmounts = $allowedAmounts;
        return $this->_giftcardAmounts;
    }`
We use magento enterprise version 2.1.3. Thanks!

**Comment by nguyetnguyen** [comment]
@kiranmaip, I tried your code on my instance (magento version 2.1.3) but it doesn't work.
