### ISSUE TITLE
Fotorama thumbnails are not responsive in mobile view.

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#9599]
### Preconditions

1. Magento EE 2.1.5
2. Theme based of blank

### Steps to reproduce

1. Add the following to view.xml
```
<var name="breakpoints">
    <var name="mobile">
        <var name="conditions">
            <var name="max-width">767px</var>
        </var>
        <var name="options">
            <var name="options">
                  <var name="arrows">true</var>
                  <var name="navarrows">true</var>
                  <var name="nav">thumbs</var>
             </var>
       </var>
   </var>
</var>
```
2. Visit a product which has more than 8 images.
3. Set page to mobile view.
4. Product Image slider is not responsive at all.

### Expected result

1. Slider should be responsive even if thumbnails are being.

### Actual result

1. Slider is not responsive.

**Comment by veloraven** [comment]
@ferrazzuk thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by Ctucker9233** [comment]
@veloraven Given that fotorama is also used in CE, doesn't it make sense that @ferrazzuk posted this here? If there is an issue with fotorama it would affect CE as well.

**Comment by Quinten** [comment]
I will try this one.

**Comment by Quinten** [comment]
I can't reproduce this in 2.2-develop branch. The thumbnails and the whole slider seem to be responsive. I can even swipe the thumbnails on my mobile phone and the container isn't sticking out of the page. The thumbnail container is scaling correct with the page.

**Comment by okorshenko** [comment]
@Quinten thank you for investigating the issue.
@ferrazzuk could you please confirm the there is no issue for you on 2.2.0 release?

**Comment by okorshenko** [comment]
@ferrazzuk the issue already fixed in 2.2.0 releases

**Comment by ihor-sviziev** [comment]
@okorshenko how it was fixed? How can I find fix for this issue?

**Comment by ihor-sviziev** [comment]
Looks like it was fixed in following commit: https://github.com/magento/magento2/commit/2e43a805c7921da87986e2e4b29e61b8b09927ae

**Comment by bydrei** [comment]
@okorshenko all good
