### ISSUE TITLE
Option values of Multi-select attribute do not appear in admin(Backend) 

### ISSUE THREAD

**Issue by NanthiniMuralidaran** [magento/magento2#9605]
Option values for Multiselect attribute are not appearing in the backend.

### Preconditions

Ubuntu - 14.04
Magento - 2.1.6
PHP - 7.0.18
MySQL - 5.6
### Steps to reproduce

1. Login to Magento Admin(Backend)
2. Go to Stores-> Product. Then type "Tax class"(Product attibute) in the text box under the column name in "Default Label" column. Click search.
3. Click the resulted row. Go to "Properties" tab. Check the "Manage Options (Values of Your Attribute)" section.

### Expected result

Should be able to see the options under the "Manage Options (Values of Your Attribute)" section.

### Actual result

Empty table is present.
![tax](https://cloud.githubusercontent.com/assets/17905842/25950167/a047b7ec-3677-11e7-9c8e-509df16514de.PNG)

**Comment by magento-engcom-team** [comment]
@NanthiniMuralidaran, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
