### ISSUE TITLE
Magento admin panel not loading content properly

### ISSUE THREAD

**Issue by felipetrevisan** [magento/magento2#9606]
### Preconditions

1. CENTOS 7.3 x86_64
2. Magento version 2.1.6, PHP: 5.6.30, MySQL: 5.6.35

### Expected result

1.  Ajax content rendering and show properly on Catalog (List, Create), Customers (List, Create), Design Configuration, Design Themes, etc.

### Actual result

![screenshot-presentesclick com br-2017-05-11-14-12-32](https://cloud.githubusercontent.com/assets/4295920/25962474/5484784a-3654-11e7-8ecc-17284d2a65da.png)

![screenshot-presentesclick com br-2017-05-11-14-13-47](https://cloud.githubusercontent.com/assets/4295920/25962500/6298823c-3654-11e7-81ac-ac98788de59f.png)

![screenshot-presentesclick com br-2017-05-11-14-14-10](https://cloud.githubusercontent.com/assets/4295920/25962512/6a05b990-3654-11e7-8a83-cef01aa0df87.png)

**Comment by ihor-sviziev** [comment]
Looks like you have some issues with static content. Please run 
```php
 php bin/magento setup:static-content:deploy
```

**Comment by felipetrevisan** [comment]
Solved. 

I'm using Cloudflare and the option to minify HTML was enabled. I changed to disable and its works like a charm!
