### ISSUE TITLE
Error with Tablerate shipping price calculation when using Price vs Weight

### ISSUE THREAD

**Issue by UglyWillDuckling** [magento/magento2#9607]
### Preconditions
1. Magento 2.1.2
2. PHP 7.0.15
 
### Steps to reproduce
1. Use Tablerate shipping method with price vs weight option
2. Set it up so it has more then one condition
3. Set up a cart rule to use freeshipping under certain conditions
4. Go to frontend and get the freeshipping cart rule to be applied, go to checkout
5. Now go back, and create the conditons for the price rule to not be applied, go to checkout

### Expected result

1. The shipping price should be calculated based on the table given to Magento

### Actual result
1. The price calculated being applied is the lowest possible one, meaning it's the one set for 0kg to whatever the first limit is

This was tested on two of our shops, both have the same problem.
It seems that Magento checks the value for free_shipping field that was saved in the shipping address when it was first created. This doesn't seem to get updated later on causing the system to set the package weight for each package to zero.
Check `Magento\Quote\Model\Quote\Address\Total\Shipping` class, line 141

**Comment by vityakopin** [comment]
Hi @UglyWillDuckling ! In step 1 You described that we have to use price vs. weight option. I can't find that option in list. Is this issue reproduced with another option existing in my list?
![screenshot_3](https://user-images.githubusercontent.com/16419284/27833823-070186e0-60dd-11e7-99e9-f99deff68e0a.png)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
