### ISSUE TITLE
Can't add secure keys to setup wizard

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9608]
### Preconditions

1.  Magento CLI version 2.1.4
2. PHP 5.6.30

### Steps to reproduce

1.  Go to Setup Wizard
2.  System Config
3.  Add Secure Keys 

### Expected result

1. Keys saved

### Actual result

![unbenannt](https://cloud.githubusercontent.com/assets/11746412/25966377/1f42c1fa-368b-11e7-869d-da483b365d2d.PNG)

**Comment by devamitbera** [comment]
Have you checked your log files?

**Comment by ghost** [comment]
Yes, nothing in there

**Comment by devamitbera** [comment]
Please enable php  error log and  see what happen?
`
ini_set('display_errors', 1);`

**Comment by ghost** [comment]
No php error's reported.

![unbenannt](https://cloud.githubusercontent.com/assets/11746412/25967916/04fc3d1c-3690-11e7-90d0-17ac9b3ea748.PNG)

**Comment by ghost** [comment]
Couldn't figure it out.
Fresh installation and restoring database did the job :/

**Comment by magento-engcom-team** [comment]
@hanssulo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
