### ISSUE TITLE
customer_grid reindex error after added 3 custom attributes

### ISSUE THREAD

**Issue by cs221313** [magento/magento2#9609]
### Preconditions

1. Magento 2.1.6,  created 3 custom attributes in customer: organization, position, department

### Steps to reproduce

1. run bin/magento indexer:reindex

### Expected result

1. it should give me the success information

### Actual result

1.Following is what I got

Customer Grid indexer process unknown error:
SQLSTATE[42000]: Syntax error or access violation: 1070 Too many key parts specified; max 16 parts allowed, query was: CREATE TABLE IF NOT EXISTS `customer_grid_flat` (
  `entity_id` int UNSIGNED NOT NULL COMMENT 'Entity ID' ,
  `name` text NULL COMMENT 'Name' ,
  `email` varchar(255) NULL COMMENT 'Email' ,
  `group_id` int NULL COMMENT 'Group_id' ,
  `created_at` timestamp NULL default NULL COMMENT 'Created_at' ,
  `website_id` int NULL COMMENT 'Website_id' ,
  `confirmation` varchar(255) NULL COMMENT 'Confirmation' ,
  `created_in` text NULL COMMENT 'Created_in' ,
  `dob` date NULL COMMENT 'Dob' ,
  `gender` int NULL COMMENT 'Gender' ,
  `taxvat` varchar(255) NULL COMMENT 'Taxvat' ,
  `lock_expires` timestamp NULL default NULL COMMENT 'Lock_expires' ,
  `department` varchar(255) NULL COMMENT 'Department' ,
  `organization` varchar(255) NULL COMMENT 'Organization' ,
  `position` varchar(255) NULL COMMENT 'Position' ,
  `billing_full` text NULL COMMENT 'Billing_full' ,
  `billing_firstname` varchar(255) NULL COMMENT 'Billing_firstname' ,
  `billing_lastname` varchar(255) NULL COMMENT 'Billing_lastname' ,
  `billing_telephone` varchar(255) NULL COMMENT 'Billing_telephone' ,
  `billing_postcode` varchar(255) NULL COMMENT 'Billing_postcode' ,
  `billing_country_id` varchar(255) NULL COMMENT 'Billing_country_id' ,
  `billing_region` varchar(255) NULL COMMENT 'Billing_region' ,
  `billing_street` varchar(255) NULL COMMENT 'Billing_street' ,
  `billing_city` varchar(255) NULL COMMENT 'Billing_city' ,
  `billing_fax` varchar(255) NULL COMMENT 'Billing_fax' ,
  `billing_vat_id` varchar(255) NULL COMMENT 'Billing_vat_id' ,
  `billing_company` varchar(255) NULL COMMENT 'Billing_company' ,
  `shipping_full` text NULL COMMENT 'Shipping_full' ,
  PRIMARY KEY (`entity_id`),
  INDEX `CUSTOMER_GRID_FLAT_GROUP_ID` (`group_id`),
  INDEX `CUSTOMER_GRID_FLAT_CREATED_AT` (`created_at`),
  INDEX `CUSTOMER_GRID_FLAT_WEBSITE_ID` (`website_id`),
  INDEX `CUSTOMER_GRID_FLAT_CONFIRMATION` (`confirmation`),
  INDEX `CUSTOMER_GRID_FLAT_DOB` (`dob`),
  INDEX `CUSTOMER_GRID_FLAT_GENDER` (`gender`),
  INDEX `CUSTOMER_GRID_FLAT_BILLING_COUNTRY_ID` (`billing_country_id`),
  FULLTEXT `FTI_A0DB95C08D547A63BEEEE719DCFB0A10` (`name`, `email`, `created_in`, `taxvat`, `department`, `organization`, `position`, `billing_full`, `billing_firstname`, `billing_lastname`, `billing_telephone`, `billing_postcode`, `billing_region`, `billing_city`, `billing_fax`, `billing_company`, `shipping_full`)
) COMMENT='customer_grid_flat' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci

**Comment by cs221313** [comment]
This issue was solved. Just set is_used_in_grid as false.

**Comment by brankoajzele** [comment]
How is this a "solved" issue? I have the same situation, created 5 extra fields, which I want to use in customer grid. Setting is_used_in_grid as false means I don't get to use them at all.

**Comment by cs221313** [comment]
MSSQL only allowed 16 fields could be set as true. You have to choose which one you want to be shown in customer grid.

**Comment by tuyennn** [comment]
This issue was caused by your mysql version. I guess this is 5.6, try to upgrade to Mariadb or 5.7 
Here the [ref](https://dev.mysql.com/doc/refman/5.6/en/multiple-column-indexes.html)

**Comment by deb00t** [comment]
> This issue was caused by your mysql version. I guess this is 5.6, try to upgrade to Mariadb or 5.7
Still causing problems in latest 5.7, fyi

**Comment by aschrammel** [comment]
Same issue here on MySQL5.7.25-1 (Debian)
I totally agree with @ajzele - this issue can't be resolved, as setting `is_used_in_grid` to `false` is no option here!

**Comment by ghost** [comment]
HI @aschrammel i'm not able to reproduce following steps on 2.3-develop branch, seems like this issue not present here, please try upgrading.

**Comment by nelero** [comment]
Hi,
no it's not closed in 2.3.4.
16 fields limit

**Comment by ARemaity** [comment]
I tried to change the three flags ( is_used_in_grid, is_filterable_in_grid, is_searchable_in_grid) but with no luck , even after deleting the whole module i was still getting the error , i check table eav_attribute to get the my eav Primary ID then check again with this id in table customer_eav_attribute and change three column is_used_in_grid ,is_filterable_in_grid,and is_searchable_in_grid to zero and rebuild magento and worked
