### ISSUE TITLE
Wishlist Add grouped Product item error

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#9612]
### Preconditions

1. 
2. 

### Steps to reproduce

1. Add grouped product from the product list with the qty of 3. For ex. added product A to the wishlist.
2. After adding the product, once again add the same product A to the wishlist with the qty of 4.
3. 

### Expected result

1. The qty of product A should be updated to 7. 

### Actual result

1. But it has been added as two separate products. product with qty 3, product with qty 4. in the wishlist items.

**Comment by routbiplab** [comment]
It is not an issue according to me. Since grouped product is a collection of simple products so whenever you different quantities of the same product it will create a separate entity for it. For every new combination i.e for products or quantities a new entity will be created.
For clarification try giving the same quantity for the same product. It won't create a separate product in your wish-list again because same product with the given quantity is already present.

**Comment by sasilinux** [comment]
Yes. I have checked it the same quantity for the same product but it is not added/updated in the wishlist. If i change the quantity and add the product to wishlist and it will be treated us the new one. Please check and confirm.

**Comment by sasilinux** [comment]
For your info, I have added the same product with the different quantity not from the wishlist page, i have added it from the catalog page. So please check this issue from your end. Also i am using the latest magento 2.1.6 version

**Comment by Stas94** [comment]
@sasilinux Thanks for reporting this issue. We've created internal ticket MAGETWO-70221 to address this issue.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@sasilinux May you please let us know, do you add to wishlist your grouped product  from Catalog page or from Product page?  In your previous comment you wrote about catalog page - but we could not add different qty of product to wishlist from there - this why your ticket was closed .
