### ISSUE TITLE
controller overriding in magento 2

### ISSUE THREAD

**Issue by DrashtiPandya** [magento/magento2#9614]
I want to override controller so that I create di.xml in etc and xyz.php in controller.and paste it in app\code\package but it not works

di.xml
-----------------------
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
        <preference for="Magento\Customer\Controller\Account\CreatePost" type="Solwin\Controller\Rewrite\Customer\Account\CreatePost" />
</config>

CreatePost.php
------------------------------------
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Solwin\Controller\Customer\Account;

/**
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class CreatePost extends \Magento\Customer\Controller\Account\CreatePost
{
    public function execute()
    {
        echo "Local controller";exit;
        $this->messageManager->addSuccess('Message from new controller.');      
        return parent::execute();
    }
}

**Comment by korostii** [comment]
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by veloraven** [comment]
@DrashtiPandya if you want to report an issue please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for discussion please see comment above.
