### ISSUE TITLE
Unable to update stock (inventory) using rest api - 500 error

### ISSUE THREAD

**Issue by carsonchynoweth** [magento/magento2#9616]
### Preconditions

1. Magento 2.1.6, PHP 5.6 and MySQL 5.6
2. Hosted on cloudways

### Steps to reproduce

1. Create a simple product in the cart. Then try to update the quantity using the API (V1)
2. 
3. 

### Expected result

1. Not a 500 error

### Actual result

1. [Screenshot, logs]
Logs files are unavailable. Below are the responses from the two means of updating I tried.
-----------------------------------------------------------------------------------------
product update
-----------------------------------------------------------------------------------------
URL: http://magento-92293-260054.cloudwaysapps.com/index.php/rest/V1/products/TEST_SKU_2-1
Method: PUT
Data: {"product":{"id":"6","sku":"TEST_SKU_2-1","name":"test names","price":99.0,"weight":"0","status":"1","visibility":"4","type_id":"simple","attribute_set_id":"4","stock":{"qty":"33","is_in_stock":true},"custom_attributes":[{"attribute_code":"short_description","value":"prod desc"},{"attribute_code":"required_options","value":"0"},{"attribute_code":"tax_class_id","value":"2"},{"attribute_code":"description","value":"details2"},{"attribute_code":"has_options","value":"0"},{"attribute_code":"gift_message_available","value":"0"},{"attribute_code":"options_container","value":"container2"},{"attribute_code":"url_key","value":"test-names-1"}],"extension_attributes":{"stock_item":{"qty":"33","is_in_stock":true}}}}
Response code: 500
Respnose message: {"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-591523cb7e6b1"}

-----------------------------------------------------------------------------------------
stock update
-----------------------------------------------------------------------------------------
URL: http://magento-92293-260054.cloudwaysapps.com/index.php/rest/V1/products/TEST_SKU_2-1/stockItems/6
Method: PUT
Data {"stockItem":{"item_id":6,"qty":"33","is_in_stock":true,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":false,"use_config_max_sale_qty":false,"use_config_backorders":false,"use_config_notify_stock_qty":false,"use_config_qty_increments":false,"useConfigEnableQtyInc":false,"enable_qty_increments":false,"use_config_manage_stock":false,"manage_stock":true,"is_decimal_divided":false,"product_sku":"TEST_SKU_2-1"}}
Response code: 500
Respnose message: {"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5915272c3e64a"}

**Comment by RomanKrut** [comment]
@carsonchynoweth  Please add more details to your description of the steps you followed when identifying this issue. Screenshots of RestApi would be helpful, too. And also you can use this documentation http://devdocs.magento.com/swagger/index.html , it is for Magento 2 EE, but it works on CE, too.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
