### ISSUE TITLE
Impossible to create Text Swatch 0 (Zero)

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#9619]
### Preconditions
1. Magento 2.1.6
2. PHP 7.0.14-2a

### Steps to reproduce
Try to create product attribute text swatch with value "0" (zero)

### Expected result
New value for attribute

### Actual result
`Admin is a required field in the each row`

To see recorded behaviour: http://recordit.co/bUwOLQQ3n2

<img width="666" alt="screen shot 2017-05-12 at 5 30 36 pm" src="https://cloud.githubusercontent.com/assets/24477165/26017686/de262f46-3738-11e7-9919-3086fcf11c55.png">

After saving:

<img width="1308" alt="screen shot 2017-05-12 at 5 30 53 pm" src="https://cloud.githubusercontent.com/assets/24477165/26017698/ed117696-3738-11e7-8433-2b97f87ea85f.png">

### Quick Fix
`module-swatches/Model/Plugin/EavAttribute.php`

Method `isOptionsValid()`
Instead of this:
`if (empty($option[0])) {
                return false;
            }`

Type this:
`if($option[0] != '0'){
				if (empty($option[0])) {
					return false;
				}
			}`

**Comment by smoskaluk** [comment]
@oroskodias Unfortunately, I could not reproduce the issue as you described it. Can you please let me know is this problem is relevant for latest Magento 2 release version?

**Comment by orozcodiaz** [comment]
@smoskaluk I see same code in 2.1.7. Issue is still there

**Comment by korostii** [comment]
See also #10266

**Comment by orlangur** [comment]
This was fixed in https://github.com/magento/magento2/pull/7701 but not backported to 2.1.x yet.

**Comment by okorshenko** [comment]
Fix for develop: MAGETWO-66160

**Comment by okorshenko** [comment]
Fix for 2.1-develop: MAGETWO-70838

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70838

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.
The issue is already fixed in 2.2.0
