### ISSUE TITLE
Full Page Cache Logic in Catalog Module

### ISSUE THREAD

**Issue by sshymko** [magento/magento2#962]
Classes `Magento\Catalog\Plugin\Model\Indexer\Category\Product\Execute` and `Magento\Catalog\Plugin\Model\Resource\Attribute\Save` implement flushing the Full Page Cache. They should belong to the `Magento_PageCache` module, not the `Magento_Catalog`. Utilization of the constant `Magento\PageCache\Model\Cache\Type::TYPE_IDENTIFIER` rather than literal `full_page` would expose that dependency on the code level.

**Comment by orlangur** [comment]
> They should belong to the `PageCache` module, not the `Catalog`

This suggestion is wrong. `PageCache` module composed in such a way would contradict to "true modularity": the intention to have granular and loosely coupled system components.

`PageCache` module in Magento 2 introduces common mechanism for any other module to implement page caching. It must not contain any domain-specific logic.

Other modules, like `Catalog`, may involve this mechanism and implement their own page caching domain-specific logic. Thus `Catalog` module should have soft dependency on `PageCache` meaning that caching ability is optional: if `PageCache` module is present it works and if no nothing bad happens.

Surely, it is possible to go even further and implement such caching as separate module like `CatalogPageCache`. Or collect caching for a bunch of modules in one with no other module depending on this new module. But, again, such code must not be placed in `PageCache` module itself.

**Comment by sshymko** [comment]
Correct, if a dependency of `Catalog` on `PageCache` is permitted, than implementation is correct except for implicit reference to the Full Page Cache constant. Good job on breaking down the monolithic FPC module!

**Comment by sshymko** [comment]
Still, constant `Magento\PageCache\Model\Cache\Type::TYPE_IDENTIFIER` needs to be used to male dependency explicit.

**Comment by orlangur** [comment]
No objections on this from my side. `Catalog` [already depends](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/composer.json#L27) on `PageCache` due to [classes used](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Plugin/Model/Indexer/Category/Product/Execute.php#L27) anyway.

This dependency is logically soft but declared as hard because there is no way to tell "I use classes of some module in plugins only" in dependency declaration currently.

**Comment by verklov** [comment]
MAGETWO-33021

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Full-Page-Cache-Logic-in-Catalog-Module/idi-p/46709).
