### ISSUE TITLE
I got an error after I created new store view on a new theme

### ISSUE THREAD

**Issue by cs221313** [magento/magento2#9620]
### Preconditions

1. version 2.1.6,

### Steps to reproduce

1.  I created a new store view
2. Created new theme and assigned the new theme to the new store view.
3. Load the homepage in browser

### Expected result

1. The homepage should be loaded

### Actual result

1. Got the following error
1 exception(s):
Exception #0 (Exception): Item (Magento\Catalog\Model\Category\Interceptor) with the same ID "4" already exists.

Exception #0 (Exception): Item (Magento\Catalog\Model\Category\Interceptor) with the same ID "4" already exists.
#0 /srv/www/bide/magento2src/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php(304): Magento\Framework\Data\Collection->addItem(Object(Magento\Catalog\Model\Category\Interceptor))
#1 /srv/www/bide/magento2src/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php(1119): Magento\Eav\Model\Entity\Collection\AbstractCollection->addItem(Object(Magento\Catalog\Model\Category\Interceptor))
#2 /srv/www/bide/magento2src/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php(910): Magento\Eav\Model\Entity\Collection\AbstractCollection->_loadEntities(false, false)
#3 /srv/www/bide/magento2src/app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php(175): Magento\Eav\Model\Entity\Collection\AbstractCollection->load(false, false)
#4 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Data/Collection.php(820): Magento\Catalog\Model\ResourceModel\Category\Collection->load()
#5 /srv/www/bide/magento2src/app/code/Magento/Catalog/Plugin/Block/Topmenu.php(81): Magento\Framework\Data\Collection->getIterator()
#6 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Interceptor.php(123): Magento\Catalog\Plugin\Block\Topmenu->beforeGetHtml(Object(Magento\Theme\Block\Html\Topmenu\Interceptor), 'level-top', 'submenu', 0)
#7 /srv/www/bide/magento2src/var/generation/Magento/Theme/Block/Html/Topmenu/Interceptor.php(26): Magento\Theme\Block\Html\Topmenu\Interceptor->___callPlugins('getHtml', Array, Array)
#8 /srv/www/bide/magento2src/app/code/Magento/Theme/view/frontend/templates/html/topmenu.phtml(18): Magento\Theme\Block\Html\Topmenu\Interceptor->getHtml('level-top', 'submenu', 0)
#9 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/srv/www/bide/m...')
#10 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Theme\Block\Html\Topmenu\Interceptor), '/srv/www/bide/m...', Array)
#11 /srv/www/bide/magento2src/var/generation/Magento/Theme/Block/Html/Topmenu/Interceptor.php(167): Magento\Framework\View\Element\Template->fetchView('/srv/www/bide/m...')
#12 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Theme\Block\Html\Topmenu\Interceptor->fetchView('/srv/www/bide/m...')
#13 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#14 /srv/www/bide/magento2src/var/generation/Magento/Theme/Block/Html/Topmenu/Interceptor.php(479): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Theme\Block\Html\Topmenu\Interceptor->toHtml()
#16 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('catalog.topnav')
#17 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('catalog.topnav')
#18 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('catalog.topnav')
#19 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('catalog.topnav', true)
#20 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(503): Magento\Framework\View\Layout\Interceptor->renderElement('catalog.topnav', true)
#21 /srv/www/bide/magento2src/app/code/Magento/Theme/view/frontend/templates/html/container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#22 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/srv/www/bide/m...')
#23 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/srv/www/bide/m...', Array)
#24 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/srv/www/bide/m...')
#25 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#26 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('store.menu')
#28 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('store.menu')
#29 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('store.menu')
#30 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('store.menu', true)
#31 /srv/www/bide/magento2src/app/code/Magento/Theme/view/frontend/templates/html/sections.phtml(26): Magento\Framework\View\Layout\Interceptor->renderElement('store.menu')
#32 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/srv/www/bide/m...')
#33 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/srv/www/bide/m...', Array)
#34 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/srv/www/bide/m...')
#35 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#36 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#37 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('navigation.sect...')
#38 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('navigation.sect...')
#39 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('navigation.sect...')
#40 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('navigation.sect...', true)
#41 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('navigation.sect...')
#42 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.top')
#43 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.top')
#44 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.top')
#45 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.top', true)
#46 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.top')
#47 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#48 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#49 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#50 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#51 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#52 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#53 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#54 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#55 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#56 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#57 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#58 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#59 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#60 /srv/www/bide/magento2src/lib/internal/Magento/Framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#63 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#64 /srv/www/bide/magento2src/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#67 /srv/www/bide/magento2src/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /srv/www/bide/magento2src/lib/internal/Magento/Framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /srv/www/bide/magento2src/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#70 /srv/www/bide/magento2src/lib/internal/Magento/Framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /srv/www/bide/magento2src/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#72 /srv/www/bide/magento2src/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#73 {main}

**Comment by magento-engcom-team** [comment]
@cs221313, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by versdivers** [comment]
Issue occured on Magento 2.2.1
