### ISSUE TITLE
Date picker will not validate formats other than y-MM-dd and inputFormat must match dateFormat

### ISSUE THREAD

**Issue by Ddcdom** [magento/magento2#9631]
### Preconditions

1. Magento version 2.1.4

### Steps to reproduce

1. Create a backend form with a UI component with a formElement type of 'date'
2. add an outputDateFormat with any format other than y-MM-dd
3. add an inputDateFormat with any format
4. add an options array with a dateFormat which does not match the inputDateFormat
5. add validation array with a validate-date

### Expected result

1. Form should pass client side validation when using the date picker, or directly entering a date in outputDateFormat
2. When loading an existing record, the date field should show the date from the record

### Actual result

1. Form fails validation when entering a date in outputDateFormat
2. When loading a form with data containing a date which matches inputDateFormat, the date field doesn't not show this date, but shows todays date.

### Steps to reproduce
1. Edit module-cms/view/adminhtml/ui_component/cms_page_form.xml
2. Add  `<item name="options" xsi:type="array"><item name="dateFormat" xsi:type="string">dd/MM/y</item></item>` to `<field name="custom_theme_from">`
3. Edit any CMS page, eg 404 page
4. Use date picker to set custom theme from date as any date in the future.
5. Save page
6. Edit the page and check the data, which will have incorrectly reverted to today's date, not he saved date.

**Comment by magento-engcom-team** [comment]
@Ddcdom, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
