### ISSUE TITLE
When will EE target rules work again in version 2.1?

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#9634]
Hello Magento team!

I want to upgrade from Magento 2.0.x to 2.1.x for a few months now an I'm waiting for the target rules to be repaired. Especially this line bugs me:

https://github.com/magento/magento2ee/blob/2.1.6/app/code/Magento/TargetRule/Model/Actions/Condition/Product/Attributes.php#L395

The current reference to `table.entity_id` throws the error: 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'table.entity_id' in 'where clause', query was: SELECT `e`.`entity_id` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' WHERE (( (IFNULL((SELECT COUNT(*) FROM `catalog_product_entity_varchar` AS `table` WHERE (table.entity_id = e.entity_id) AND (table.attribute_id='227') AND (table.store_id=0) AND (`table`.`value`=:targetrule_bind_0)), 0)) > 0 AND  (`e`.`type_id`='configurable'))) AND (`e`.`entity_id` NOT IN('1607')) AND (e.created_in <= 1) AND (e.updated_in > 1) LIMIT 20
```

I see that this code is completely revised in the development branch, but the error is still in 2.1.6. When can I expect this to work again?

To test this I made a rule with 

If ALL  of these conditions are TRUE :
- Product Model  is  Matched Product Model    
- Product Type  is  Constant Value  Configurable Product  

Model is a varchar product attribute

**Comment by AntonEvers** [comment]
### Preconditions


1. Magento 2.1.6 EE

### Steps to reproduce

1. Create a target rule, up sells for instance, in `Marketing | Related Product Rules`
2. Leave products to match empty
3. In "products to display" choose a varchar attribute (x) and set it to "is Matched product (x)"
4. flush all caches

### Expected result

1. When visiting the product detail page of a product it should display upsell products

### Actual result

1. [Screenshot, logs]
```
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'table.entity_id' in 'where clause', query was: SELECT `e`.`entity_id` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' WHERE (( (IFNULL((SELECT COUNT(*) FROM `catalog_product_entity_varchar` AS `table` WHERE (table.entity_id = e.entity_id) AND (table.attribute_id='227') AND (table.store_id=0) AND (`table`.`value`=:targetrule_bind_0)), 0)) > 0 AND  (`e`.`type_id`='configurable'))) AND (`e`.`entity_id` NOT IN('1607')) AND (e.created_in <= 1) AND (e.updated_in > 1) LIMIT 20
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'table.entity_id' in 'where clause'
```

**Comment by AntonEvers** [comment]
When I go to the database, open the `magento_targetrule` table and change this query:
```
( (IFNULL((SELECT COUNT(*) FROM `catalog_product_entity_varchar` AS `table` WHERE (table.entity_id = e.entity_id) AND (table.attribute_id='227') AND (table.store_id=0) AND (`table`.`value`=:targetrule_bind_0)), 0)) > 0 AND  (`e`.`type_id`='configurable'))
```

to this query:

```
( (IFNULL((SELECT COUNT(*) FROM `catalog_product_entity_varchar` AS `table` WHERE (table.row_id = e.entity_id) AND (table.attribute_id='227') AND (table.store_id=0) AND (`table`.`value`=:targetrule_bind_0)), 0)) > 0 AND  (`e`.`type_id`='configurable'))
```

Thew page works again. `table.entity_id` is changed to `table.row_id`.

**Comment by southerncomputer** [comment]
You could use the elastic suite (GitHub) target_rules for ee 2.1 which uses percolation to fix this bug and improve performance!

**Comment by AntonEvers** [comment]
@southerncomputer thank you for a good workaround. The fact of the matter is however that we pay thousands of euros for the Enterprise product and we expect it to keep working when the installation is upgraded.

**Comment by veloraven** [comment]
@ajpevers thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
As I know, some issues with target rules were already fixed, for both CE and EE, and will be available in one of the next release. However it's better to check with support if this particular issue will be fixed among them.
Anyway I'm closing this issue as it refers to EE functionality and we can not treat it as GitHub issue.

**Comment by AntonEvers** [comment]
@veloraven thanks. I've already created a pull request which is almost through. This issue will be solved soon.

**Comment by romainruaud** [comment]
@southerncomputer thank you for supporting our great extension :)

@ajpevers here is a link to our implementation of targetrules using Elasticsearch : https://github.com/Smile-SA/magento2-module-elasticsuite-targetrule

Please note that it also greatly improves performances versus the Magento's naive approach ("fill all our tables with potential matching between product_id and rule_id)

**Comment by sanjay-wagento** [comment]
> magento_targetrule

Your solution is working for migrated data
