### ISSUE TITLE
Catalog rules are not visible for customer without re-login after a group change

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#9640]
The admin user changes customer group to one which has catalog price rules applied. Change is not visible in frontend until customer logs out and logs in again.

### Preconditions

1. Install Magento 2.1.5 with sample data
2. PHP 5.6.30

### Steps to reproduce

1. Create customer account (General group) and make sure you are logged in
2. Load product listing page eg. http://local.magento215.com/index.php/gear/bags.html page
4. Note the prices 
5. Log in into admin backend
6. Add catalog price rule:
    * Status: Active
    * Websites: Main Website
    * Customer Groups: Retailer
    * Conditions: empty
    * Actions / Apply: Apply as fixed amount
    * Actions / Discount Amount: 0.3
7. Click "Save and Apply"
8. Edit customer account and change group from General to Retailer
8. Refresh page in frontend

### Expected result
1. Prices on product listing include newly added Catalog Price Rule

### Actual result
1. Prices on product listing DOES NOT include newly added Catalog Price Rule

It works when the customer logs out and logs in again.

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70238 was created.

**Comment by magento-engcom-team** [comment]
@wojtekn, thank you for your report.
We've created internal ticket(s) MAGETWO-70238 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@wojtekn, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by posdevworks** [comment]
Are there any fixes to this? Encountering this issue on Magento 2.3.7
