### ISSUE TITLE
What time to release Magento version 2.2?

### ISSUE THREAD

**Issue by vanloc0301** [magento/magento2#9641]
I can't find in Project or Roadmap of Magento 2.

Can anyone have document reference to this.

**Comment by patrickdesroches** [comment]
Hi

Found those slides from Imagine India

http://magentolive.com/in/wp-content/uploads/sites/6/2017/05/MLI-2017_BO-III_Technical_Powering-Tomorrow_2.2.pdf

2.2 is schedule for the end of July or August

Thanks

**Comment by vanloc0301** [comment]
Thanks @patrickdesroches

**Comment by eharvest** [comment]
It's almost the end of September, and according to the schedule 2.2 GA should be released by now. Doesn't anyone knows how far away before 2.2 GA becomes available?

**Comment by hostep** [comment]
@eharvest: I've heard the date September 27th somewhere, but I don't know for certain...

**Comment by kervin** [comment]
Any official date yet?

**Comment by orlangur** [comment]
https://community.magento.com/t5/News-Announcements/Magento-2-2-Update-Available/m-p/75123#M167 is the most accurate information I have read. There will be no significant changes anymore, so, you can already use `2.2.0-preview` branch to be prepared for GA.
