### ISSUE TITLE
Magento 2.1.6 products not visible on catalog page

### ISSUE THREAD

**Issue by nuwaus** [magento/magento2#9645]
We have a Magento 2 site with multiple stores and we have over 60000 products on our stores. We have Magento version 2.1.6 And we get "`We can't find products matching the selection.`" even after all indexers are completed successfully, We work on our site from Magento 2 beta and still working on it, in some releases it is stable but in some releases, it's not.

And recently we faced a situation mentioned in this post
_https://github.com/magento/magento2/issues/5222_
and, we followed the fixing procedure and did able to get it working, but since the last update which is 2.1.6, no products are visible on the catalog pages at all, but the message "We can't find products matching the selection."
So, what could be the issue? maybe server caching issue or Magento indexer? please be kind enough to provide some clue or suggestions which are similar to this issue so we can test them and report back of the effectiveness.

### Preconditions

1. PHP version 7.0.18
2. Apache 2.4
3. Modpagespeed
4. Varnish 4
5. Nginx
6. SSL

### Steps to reproduce

1. Clear var directory
2. Run di:compile
3. Successfully run all indexers

### Expected result

1. Products visible on catalog pages

### Actual result

1. `We can't find products matching the selection`

**Comment by tsifra** [comment]
Hello, could you try my workarounds? #9656 with individual product re-save after import and what is more important category resave? Probably we've faced the same problem.

**Comment by tsifra** [comment]
I believe problem is localized. Please check #9676 Could you make the same check on your database?

**Comment by nuwaus** [comment]
Hi,

Thank you for your replies and suggestions, I solved it already, it was Varnish, after I disabled the Varnish, it working perfectly again.
