### ISSUE TITLE
CartTotalRepository cannot handle extension attributes in quote addresses

### ISSUE THREAD

**Issue by ekuusela** [magento/magento2#9646]
Extension attributes in quote billing or shipping addresses cause Magento\Quote\Model\Cart\CartTotalRepository::get to throw this error:

    "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Quote\Model\Cart\Totals::setExtensionAttributes() must be an instance of Magento\Quote\Api\Data\TotalsExtensionInterface, instance of Magento\Quote\Api\Data\AddressExtension given

This happens for example when /carts/mine/payment-information is requested while modifying billing address during checkout.

Here's a similar issue with adding extension attributes to CartItemInterface: https://github.com/magento/magento2/issues/3640

### Preconditions

1. Magento 2.1.3 to 2.1.6
2. Extension attributes defined for quote shipping or billing addresses

### Steps to reproduce
Assuming extension attributes for the quote billing address have been defined

1. login as a user who has at least two addresses in his address book
2. add a virtual product to card and proceed to checkout
3. choose or change the billing address, click update

### Expected result
1. no errors, address is changed

### Actual result
1. error is thrown and the checkout loader gets stuck

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69223

**Comment by magento-engcom-team** [comment]
Hi @ekuusela 
Thank you for reporting and fixing the issue with the PR. 
As it is already delivered into `2.1.8` we are closing this issue.
Thank you for collaboration.

**Comment by marius-bica** [comment]
This is still happening in `2.2.2`

From what I tested, commit [aa535e](https://github.com/ekuusela/magento2/commit/aa535ea5d4bf78915bddd4387a9d3c4b39943eea) solves this issue and it's present in `2.1.8` but it's not ported to the `2.2` branch. As soon as it gets ported, everything will work as expected.

**Comment by Vikram0811** [comment]
This issue still exist - https://github.com/magento/magento2/issues/14171

**Comment by ghost** [comment]
This issue still exists in Magento 2.2.3

**Comment by ycancio** [comment]
This is still happening in Magento 2.2.3

**Comment by treii28** [comment]
Still experiencing in Magento 2.2.2

**Comment by alexishughes** [comment]
This *seems* to be still happening in M2.2.3. This is the response I got:

{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Quote\\Model\\Cart\\Totals::setExtensionAttributes() must be an instance of Magento\\Quote\\Api\\Data\\TotalsExtensionInterface, instance of Magento\\Quote\\Api\\Data\\AddressExtension given, called in \/home\/hyperst1\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php on line 125 and defined in \/home\/hyperst1\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/Totals.php:592\nStack trace:\n#0 \/home\/hyperst1\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php(125): Magento\\Quote\\Model\\Cart\\Totals->setExtensionAttributes(Object(Magento\\Quote\\Api\\Data\\AddressExtension))\n#1 \/home\/hyperst1\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php(85): Magento\\Framework\\Api\\DataObjectHelper->_setDataValues(Object(Magento\\Quote\\Model\\Cart\\Totals), Array, 'Magento\\\\Quote\\\\A...')\n#2 \/home\/hyperst1\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/CartTotalRepository.php(103): Magento\\Framework\\Api\\DataObjectHelper->populateWithArray(Object(Magento\\Quote\\Model' in '\/home\/hyperst1\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/Totals.php' on line 592","trace":"Trace is not available."}]}}

**Comment by halitsavafoglu** [comment]
Still in Magento 2.2.3 clear installation
