### ISSUE TITLE
MAGETWO-55896: Storefront: My Orders: Missing an Action column header 

### ISSUE THREAD

**Issue by yariksheptykin** [magento/magento2#9648]
Maybe we should merge MAGETWO-55896 (see https://github.com/magento/magento2/commit/9cb1818f9ad7a7ce7c596be8849a391c486e5a65) into one of the releases. It looks like this trivial change is somehow lost. It's been living in in develop since Jul 28, 2016 but didn't make it into a release version of magento yet. Is this intentional?

**Comment by quienti** [comment]
This commit => MAGETWO-55896 (see 9cb1818)
Is in develop branch, so it is for Magento 2.2

**Comment by yariksheptykin** [comment]
I see! Alright, not an issue then.
Thought it was overseen.
