### ISSUE TITLE
Generated Factory does not implement correct interface

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#9651]
For the sake of having my business-logic not being framework-dependant I've added interfaces for the (to be) generated factories to my code, so I can craft my code by using a service contract of the factory prior before it being automatically created by Magento.

Does this question makes sense? Well let me enlighten it with an example:

### Preconditions

1. Magento 2.1.6

### Steps to reproduce

Create a service contract (interface) for a factory that will be automatically generated by Magento. For example:

    interface StockOptionInterfaceFactory
    {
        /**
         * @param array $data
         * @return StockOptionInterface
         */
        public function create(array $data = []): StockOptionInterface;
    }

This interface is located in my `Api/Data` folder, next to the `StockOptionInterface`. This way I can use an abstract dependency of the factory in my classes. In `di.xml` I have:

    <preference for="Vendor\StockOptions\Api\Data\StockOptionInterfaceFactory"
                type="Vendor\StockOptions\Model\Data\StockOptionFactory"/>

### Expected result

I expect Magento to create the factory and add the proper `implements` to it. Also, the `create()`-method should reflect the signature of the interface. Example:

    class StockOptionFactory implements StockOptionInterfaceFactory
    {

        // some lines of code

        public function create(array $data = []):StockOptionInterface
        {
            // code
        }
    }

### Actual result

The actual generated class does not implement the interface and the return type of the `create()`-method is not correct.

    class StockOptionFactory
    {

        // some lines of code

        public function create(array $data = array())
        {
            // code
        }
    }

### Workaround

I'm guessing that when we're creating a Service Contract for the factories, the factories should reflect this. Or should I not depend on code generation in this scenario and create the factories myself? Because that's the workaround for now.

**Comment by orlangur** [comment]
> I expect Magento to create the factory and add the proper `implements` to it

What is the ground for such expectation?

> This way I can use an abstract dependency of the factory in my classes. In `di.xml` I have:

```
<preference for="Vendor\StockOptions\Api\Data\StockOptionInterfaceFactory"
            type="Vendor\StockOptions\Model\Data\StockOptionFactory"/>
```

Abstract dependency is needed only when you need to swap implementations. Here you have factory which can create only one class instances. You can rely on factory contract (NOT enforced by any interface) considering its autogenerated nature.

The way factory is generated DOES NOT take into consideration any such preferences.

**Comment by kanduvisla** [comment]
So if I understand correctly, the only reason why some modules have interfaces for their factories is because those factories differ from the default Magento implementation, and if the auto-generated factories are good enough there is no need to create an interface for it?

**Comment by rparsi-commer** [comment]
@kanduvisla 

> So if I understand correctly, the only reason why some modules have interfaces for their factories is because those factories differ from the default Magento implementation, and if the auto-generated factories are good enough there is no need to create an interface for it?

Very short answer is "Yes", you use the auto generated factories most of the time as the core magento2 modules do.   In cases where custom behavior is needed you implement your own factory class.

You can use the `ObjectManager` directly to manage instantiation of your custom classes, instead of relying on the constructor injection mechanism.  This is how I've seen the core magento2 modules do it.

**Comment by kanduvisla** [comment]
I'd rather not use the object manager directly. But for now I'm enough informed. Closing this issue as it's by design and not a bug
