### ISSUE TITLE
Cart Price Rule: Edits and usage sets salesrule_coupon expiration date to today

### ISSUE THREAD

**Issue by parkktech** [magento/magento2#9652]
Magento EE 2.1.3 >

**Steps to reproduce**
1. Create a sales rule and add a scheduled change. This will set the Expiration date to be the same date as the last date of your schedule. "This is good" 
2. Make any edit after saving. Simply change the name, place an order, etc.. It will update.  It will update salesrule_coupon expiration_date to today's date. 

**Expected result**
I would expect the expiration date to be pulled from the staging tables  stay into effect until it actually expires.

**Actual result**
After making any edits and saving or placing an order, etc..  It will update salesrule_coupon expiration_date to today's date rendering the rule as expired. 

Before Schedule:
![before-schedule](https://cloud.githubusercontent.com/assets/2937064/26121843/70567526-3a2a-11e7-8fd8-5a1c71e552a7.png)

After Scheduling:
![after-schedule](https://cloud.githubusercontent.com/assets/2937064/26121848/74b773d6-3a2a-11e7-8546-553407ee73ec.png)

After Saving Rule edit OR after purchase: 
![after-save](https://cloud.githubusercontent.com/assets/2937064/26121852/773f9a34-3a2a-11e7-8a14-1e326039c6c0.png)

**Comment by parkktech** [comment]
In case this helps anyone. The temporary solution I have implemented was I made a simple extension to just keep the expiration date as null.  

![temporaryfix](https://cloud.githubusercontent.com/assets/2937064/26122403/33749410-3a2c-11e7-954a-ceefd46cd389.png)

**Comment by ddeppner** [comment]
This looks like a duplicate of https://github.com/magento/magento2/issues/6122

**Comment by veloraven** [comment]
@strattas thank you for your report.
We already have internal ticket for this issue - MAGETWO-58855.
It has already been fixed and the fix will be available in one of the nearest releases.
I'm closing this issue as it refers to EE functionality and we can not treat it as an issue in GitHub which is intended for CE issues only.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant next time.
