### ISSUE TITLE
Reimport does not replace/update visibility 

### ISSUE THREAD

**Issue by Gamewalker** [magento/magento2#9658]
### Preconditions
1. Magento 2.1.6
2. PHP 7.0.6 + 5.6.31 + Apache2

### Steps to reproduce
1. Import a set of data with visibility not "Not Visible Individually"
2. ReImport the data and set article to "Not Visible Individually"
3. Article visibility wont be updated (tested with replace and update)

### Expected result
1. Article should be "Not Visible Individually"

### Actual result
1. It stays the same as before

If I delete my products and reimport them with visibility "Not Visible Individually", its working fine

**Comment by imontaine** [comment]
Before using replace, did you make sure that you removed columns store_view_code and _store from csv file?

**Comment by magento-engcom-team** [comment]
@Gamewalker, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
