### ISSUE TITLE
Wrong Price Calculation with HHVM

### ISSUE THREAD

**Issue by gewaechshaus** [magento/magento2#966]
There seems to be a bug with the price calculation MCE 1.9.1.0 when using HHVM 3.4.2 in fcgi mode, even with enabled  
    
    hhvm.enable_zend_sorting=1

See the related issue
https://github.com/facebook/hhvm/issues/4630

**Tracked down -> Mage_Core_Helper_Data **

    /**
     * Convert and format price value for specified store
     *
     * @param   float $value
     * @param   int|Mage_Core_Model_Store $store
     * @param   bool $format
     * @param   bool $includeContainer
     * @return  mixed
     */
    public static function currencyByStore($value, $store = null, $format = true, $includeContainer = true)
    {
        try {
            if (!($store instanceof Mage_Core_Model_Store)) {
                $store = Mage::app()->getStore($store);
            }
            echo $value.'<br />';
            $value = $store->convertPrice($value, $format, $includeContainer);
            die($value);
        }
        catch (Exception $e){
            $value = $e->getMessage();
        }

        return $value;
    }

**Output**

    1.4800
    14.800.000,00 €

Prices are high atm :)

Will track it down deeper and inspect the convertPrice method.

**Comment by gewaechshaus** [comment]
Deeper trackdown  -> Mage_Core_Model_Store

     /**
     * Format price with currency filter (taking rate into consideration)
     *
     * @param   double $price
     * @param   bool $includeContainer
     * @return  string
     */
    public function formatPrice($price, $includeContainer = true)
    {
        if ($this->getCurrentCurrency()) {
              
              echo $price.'<br />';
              echo $this->getCurrentCurrency()->format($price, array(), $includeContainer).'<<br />';
              die('somewhere over the rainbow');
              
              return $this->getCurrentCurrency()->format($price, array(), $includeContainer);
        }
        return $price;
    }

**Output**

    1,48
    14.800.000,00 €

**Comment by gewaechshaus** [comment]
It appears systemwide, so it has to be deeper in the core...

**Comment by gewaechshaus** [comment]
Damn, this looks like an issue with sprintf in  

Mage_Directory_Model_Currency

     public function formatTxt($price, $options = array())

https://github.com/facebook/hhvm/issues/3725

**Comment by gewaechshaus** [comment]
Zend_Debug::dump(Mage::app()->getLocale()->currency());
--

    object(Zend_Currency)#89761 (1) {
     ["_options":protected] => array(12) {
     ["position"] => int(8)
     ["script"] => NULL
     ["format"] => NULL
     ["display"] => int(2)
     ["precision"] => int(2)
     ["name"] => string(4) "Euro"
     [ "currency"] => string(3) "EUR"
     ["symbol"] => string(3) "€"
     [ "locale"] => string(5) "de_DE"
     ["value"] => int(0)
     ["service"] => NULL
     ["tag"] => string(11) "Zend_Locale"
      }
    }
--

Options array
The following options are available
   * 'position' => Position for the currency sign
   * 'script' => Script for the output
   * 'format' => Locale for numeric output
   * 'display' => Currency detail to show
   * 'precision' => Precision for the currency
   * 'name' => Name for this currency
   * 'currency' => 3 lettered international abbreviation
   * 'symbol' => Currency symbol
   * 'locale' => Locale for this currency
   * 'value' => Money value
   * 'service' => Exchange service to use
     * @var array
     * @see Zend_Locale

**Comment by orlangur** [comment]
Is this bug reproducible in Magento 2? It seems to me that relevant place for Magento 1.x bug reports is http://www.magentocommerce.com/bug-tracking.

As for Magento 2, it is not fully compatible with HHVM currently, but should definitely become compatible some day.

**Comment by gewaechshaus** [comment]
Hi Vlad,

you are right. I posted it here cause i'm unsure if this bug is related to ZF and i know about the future plans with Magento 2 and HHVM. I also think that Alan said that there are no plans to move away from ZF. Another reason, i like github more than the official bug tracker at magentocommerce.com as it seems faster and more productive ;) Found that would be a better place than the hhvm repo.

But to keep things in order, i will also post it in the official bugtracker when things are more clear and reproducable to us. I would like to continue inspecting this and post my results here if there are no problems with that.

Regards,
Jan

**Comment by verklov** [comment]
We created the ticket int he internal tracker with ID: MAGETWO-32945. the team will work on it according to the priorities. Thank you!

**Comment by gewaechshaus** [comment]
Hey Sergey,

thanks. I'll keep you updated. Actually we tracked it down so deep, i 
has to be related to ZF and the some of the currency formating methods. 
Another thing in the background, it could be related to hhvm's parsing 
of php money_format.
*
One thing we could clearly track: *
If this bug appends, the format of the each currency gets broken, 
indepent of which currency you choose. For example, if you choose EUR 
and Zend::dump a helper formated zero price in €, it will become 00,00€ 
instead of it's default 0,00€, the same shizzle happens with $ and so 
on. With this fact in the background, i guess sprintf or some other 
methods will fail and multiply the result with 10mio. We checked some 
other stuff, the localization formats xml from the ZF locale are 
included correctly. So what the f*** is happening here?

It happens in the back- and in frontend (you can clearly see this in DEV 
systems dashboard as the stats are mostly at zero or switch the currency 
programmaticaly in the FE)... All orders are multiplied with 10mio while 
sales_flat_order is still ok. If you dump out the var, without any 
formating, it's ok 2. So it's in fact related to localisation/currency 
converting.

Kind regards,
Jan

**Comment by verklov** [comment]
Thanks a lot for your input, Jan! Unfortunately, I cannot promise you issue handling - you know that we do not officially support hhvm. However, the ticket is in the product backlog and will be handled according to our priorities. Have a good day! :-)

**Comment by AGalico** [comment]
Hi Jan,
have you found any conditions that trigger this behavior? we've had similar issues on a similar stack, (nginx(1.6.2)->hhvm(3.5.0)->magento(1.9.1)) but i've not been able to replicate it or find any evidence of it occuring other than a screenshot that was sent to me.

**Comment by gewaechshaus** [comment]
Hi @AGalico,
not really! We're only able to reproduce this after a bigger bunch of transactions and during traffic peaks... So all you can do actually is bomb the system with orders and traffic. We were able to bring it up with a 5 man team.

Can u post the screen?

**Comment by AGalico** [comment]
![price issue](https://cloud.githubusercontent.com/assets/11153551/6338776/69df2e54-bc05-11e4-912a-3f410b0d38f4.png)

not the most descriptive image, the rrp is coming from the magento database, the customer price is generated by our ERP but goes through the same methods for formatting.

**Comment by gewaechshaus** [comment]
Hey AGalico,

ok, that looks and sounds exactly like in our case and my test cases... 

Could you bring it up again? Maybe we should concentrate our ressources and try to bring it up in one of our or your dev systems.

**Comment by AGalico** [comment]
i've tried simulating a load on the dev environment and haven't been able to get it to occur, if i get some time in the near future i might switch live back to hhvm with a fallback to php-fpm, and build something into view.phtml to trigger it to silently fallback when this issue arises, in turn triggering something to image hhvm and magento cache.

**Comment by gewaechshaus** [comment]
Short version: the bug isn't only affecting the view.phtml, neither one 
template. You'll have to fix it globally in the related method(s). 
Otherwise transactions will fail[f.e. the paypal ipn procedure], one 
values get stored[f.e. in sales_flat_order tbl] and so on.


Am 27.02.2015 um 06:17 schrieb AGalico:

**Comment by jjone** [comment]
![hhvm3 6bug](https://cloud.githubusercontent.com/assets/8607130/6600553/b159a0c4-c7e6-11e4-8824-ee2d1d384de7.png)

Shopping Cart Price Rules failed to apply in the grand total.

server: HHVM 3.6, Magento 1.9.1 and nginx 1.6.2

**Comment by AGalico** [comment]
@jjone i believe this is a different issue, and may be rectifiable by
adding the line:
hhvm.enable_zend_sorting= 1
to hhvm's server.ini

**Comment by gewaechshaus** [comment]
@AGalico that is absolutely correct! 

---- AGalico schrieb ----

**Comment by jjone** [comment]
fixed. Thank you very much AGalico and gewaechshaus !

**Comment by gewaechshaus** [comment]
Another Idea @verklov @orlangur @AGalico 

I didn't check it, but maybe we're just running into a case-insensitive class naming issue
http://docs.hhvm.com/manual/en/hack.unsupported.php

    Case-insensitive function calls (the Hack type checker is case-sensitive). 

or something similar, simple stupid, naturaly not in horizon cause functionable in 99% of all setups issue. Maybe one of you can check the list 2...

**Comment by AGalico** [comment]
http://docs.hhvm.com/manual/en/hack.unsupported.php
>Note:
These are features that the Hack language does not support (i.e., the Hack type checker will give you an error if you try to use them). However, HHVM supports these features just fine when using PHP code.

**Comment by gewaechshaus** [comment]
Damn, i didn't read this good enough I think @AGalico .

But as the fate want, we switched today again to HHVM 3.6.1, and got this
![ahhhhhhhhhhhhhhhhhhhh](https://cloud.githubusercontent.com/assets/7628545/7403433/fd9eb1f2-eed5-11e4-9df7-180712f0474b.jpg)

and something like
![waaaaaaaaaaaaaaaaahhhhhhhhhhhh](https://cloud.githubusercontent.com/assets/7628545/7403448/2bdd4a2e-eed6-11e4-8b4a-4f0b28c7945f.jpg)

My hot candidates causing this
    numfmt_format
    numfmt_format_currency
    numfmt_parse_currency

http://docs.hhvm.com/manual/en/numberformatter.formatcurrency.php
http://php.net/manual/de/numberformatter.formatcurrency.php

**Comment by AGalico** [comment]
are you able to see what happens in Zend_Currency  toCurrency()?

**Comment by gewaechshaus** [comment]
I stopped hhvm to let the fallback be active, we just moved our dev to live... Have to clone it into a new dev, will start tomorow. Still working 20hrs.

**Comment by Krapulat** [comment]
I confirm the bug.

With HHVM active it displays wrong prices.

When using PHP-FPM it works fine.

**Comment by vzabaznov** [comment]
Hi @gewaechshaus  seems like it was fixed in hhvm version 3.9, please check it, and if you think that not, feel free to write here or to open new one
