### ISSUE TITLE
Magento 2 Rest API, PUT catalog request doesn't work

### ISSUE THREAD

**Issue by nikolaybaychenko** [magento/magento2#9667]
I am using Symfony application to send requests to Magento 2 Rest Api. When I send a PUT request to update a catalog, it doesn't change catalog information in Magento, but changes the name and other parameters except parentId on Symfony side. 

Here is the code with request:

    public function updateCategory($id, $name, $parentId, $isActive = true)
    {
        $pageSuffix = "rest/V1/categories/" . $id;
        $headers = ['content-type' => "application/json", 'Authorization' => "Bearer " . $this->adminToken];
        $content = ["category" => ["id" => (int)$id, "name" => $name, "parentId" => (int)$parentId, "isActive" => (bool)$isActive]];
        $response = $this->buzz->put($this->urlBase . $pageSuffix, $headers, json_encode($content));
        print_r(json_decode($response));
        print_r($this->buzz->getLastRequest());
    } 

category tree before I send a request:

    
    [id] => 1
    [parent_id] => 0
    [name] => Root Catalog
    [is_active] => 
    [position] => 0
    [level] => 0
    [product_count] => 0
    [children_data] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 2
                    [parent_id] => 1
                    [name] => root_test_category_1
                    [is_active] => 1
                    [position] => 1
                    [level] => 1
                    [product_count] => 0
                    [children_data] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [id] => 3
                                    [parent_id] => 2
                                    [name] => test_category_1
                                    [is_active] => 1
                                    [position] => 1
                                    [level] => 2
                                    [product_count] => 0
                                    [children_data] => Array
                                        (
                                            [0] => stdClass Object
                                                (
                                                    [id] => 8
                                                    [parent_id] => 3
                                                    [name] => test_category_1_1
                                                    [is_active] => 1
                                                    [position] => 1
                                                    [level] => 3
                                                    [product_count] => 0
                                                    [children_data] => Array
                                                        (
                                                            [0] => stdClass Object
                                                                (
                                                                    [id] => 9
                                                                    [parent_id] => 8
                                                                    [name] => test_category_1_1_1
                                                                    [is_active] => 1
                                                                    [position] => 1
                                                                    [level] => 4
                                                                    [product_count] => 0
                                                                    [children_data] => Array
                                                                        (
                                                                        )

                                                                )

                                                            [1] => stdClass Object
                                                                (
                                                                    [id] => 10
                                                                    [parent_id] => 8
                                                                    [name] => test_category_1_1_2
                                                                    [is_active] => 1
                                                                    [position] => 2
                                                                    [level] => 4
                                                                    [product_count] => 0
                                                                    [children_data] => Array
                                                                        (
                                                                        )

                                                                )

                                                            [2] => stdClass Object
                                                                (
                                                                    [id] => 16
                                                                    [parent_id] => 8
                                                                    [name] => test_category_1_1_3
                                                                    [is_active] => 1
                                                                    [position] => 3
                                                                    [level] => 4
                                                                    [product_count] => 0
                                                                    [children_data] => Array
                                                                        (
                                                                        )

                                                                )

                                                        )

                                                )

                                        )

                                )

                        )

                )

            [1] => stdClass Object
                (
                    [id] => 5
                    [parent_id] => 1
                    [name] => root_test_category_2
                    [is_active] => 1
                    [position] => 2
                    [level] => 1
                    [product_count] => 0
                    [children_data] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [id] => 6
                                    [parent_id] => 5
                                    [name] => test_category_2_1
                                    [is_active] => 1
                                    [position] => 1
                                    [level] => 2
                                    [product_count] => 0
                                    [children_data] => Array
                                        (
                                        )

                                )

                        )

                )

        )

Then I send a request to change test_category_1_1_3, id 16. The command below sends parameters as in function updateCategory() listed above. So it should fetch catalog with id 16 and change it's name and parentId.

    app/console magento:test 16 test_category_1_1_3_test 6 1 -vvv

After running the command and sending request I check this catalog by getting it from Magento Rest API. As the result, it changes it's name but everything else remains the same.

    [id] => 16
    [parent_id] => 8
    [name] => test_category_1_1_3_test
    [is_active] => 1
    [position] => 3
    [level] => 4
    [product_count] => 0
    [children_data] => Array
        (
        )

Response from the request: 

    Buzz\Message\Response Object
    (
        [protocolVersion:Buzz\Message\Response:private] => 
        [statusCode:Buzz\Message\Response:private] => 
        [reasonPhrase:Buzz\Message\Response:private] => 
        [headers:Buzz\Message\AbstractMessage:private] => Array
            (
                [0] => HTTP/1.1 200 OK
                [1] => Date: Wed, 17 May 2017 12:56:23 GMT
                [2] => Server: Apache/2.4.18 (Ubuntu)
                [3] => Set-Cookie: PHPSESSID=56hrlb8nejsnrduk05npemd3n3; expires=Wed, 17-May-2017 13:56:23 GMT; Max-Age=3600; path=/; domain=magento-project.nikolay.localdev; HttpOnly
                [4] => Expires: Thu, 19 Nov 1981 08:52:00 GMT
                [5] => Cache-Control: no-store, no-cache, must-revalidate
                [6] => Pragma: no-cache
                [7] => X-Frame-Options: SAMEORIGIN
                [8] => Content-Length: 739
                [9] => Content-Type: application/json; charset=utf-8
            )
    
        [content:Buzz\Message\AbstractMessage:private] => {"id":16,"parent_id":8,"name":"test_category_1_1_3_test","is_active":true,"position":3,"level":4,"children":"","created_at":"2017-05-17 10:51:17","updated_at":"2017-05-17 10:51:17","path":"1\/2\/3\/8\/16","available_sort_by":[],"include_in_menu":true,"custom_attributes":[{"attribute_code":"display_mode","value":"PRODUCTS"},{"attribute_code":"is_anchor","value":"1"},{"attribute_code":"path","value":"1\/2\/3\/8\/16"},{"attribute_code":"children_count","value":"0"},{"attribute_code":"custom_use_parent_settings","value":"0"},{"attribute_code":"custom_apply_to_products","value":"0"},{"attribute_code":"url_key","value":"test-category-1-1-3"},{"attribute_code":"url_path","value":"test-category\/test-category-1-1\/test-category-1-1-3"}]}
    )
    Buzz\Message\Request Object
    (
        [method:Buzz\Message\Request:private] => PUT
        [resource:Buzz\Message\Request:private] => /rest/V1/categories/16
        [host:Buzz\Message\Request:private] => http://magento-project.nikolay.localdev
        [protocolVersion:Buzz\Message\Request:private] => 1.1
        [headers:Buzz\Message\AbstractMessage:private] => Array
            (
                [0] => content-type: application/json
                [1] => Authorization: Bearer mcq2i97t0t3b15hdmwwhoolp6ma0lyuy
            )
    
        [content:Buzz\Message\AbstractMessage:private] => {"category":{"id":16,"name":"test_category_1_1_3_test","parentId":6,"isActive":true}}
    )

Moreover, nothing at all changes in Magento itself. 

[![screenshot from Magento][1]][1]

  [1]: https://i.stack.imgur.com/eOlkk.png

I tried to debug save() function in (vendor/magento/module-catalog/Model/CategoryRepository.php) but it didn't show me anything that would help. I've been trying to clear cache both on Magento and Symfony sides but that doesn't help as well.

**Comment by rparsi-commer** [comment]
@Nikolay-Baychenko Have you tried invoking the same magento2 Rest Api endpoints with the same data posted here, manually (via browser tool like Postman)?
At least then you can rule out if issue is with magento2 itself.

**Comment by nikolaybaychenko** [comment]
Tested with Postman, gives exactly the same result.
 
Initial data:

```
[id] => 20
[parent_id] => 2
[name] => Clothes
[is_active] => 1
```

Request URL + header:

![screenshot_2017-06-06_15-26-56](https://cloud.githubusercontent.com/assets/13581265/26829081/bab39196-4acc-11e7-993b-2bfd8521c237.png)

body:
`{"category":{"id":20,"name":"Test Category 1","parentId":21,"isActive":true}}`

response:
```
{
    "id": 20,
    "parent_id": 2,
    "name": "Test Category 1",
    "is_active": true,
    "position": 1,
    "level": 2,
    "children": "",
    "created_at": "2017-05-23 06:37:14",
    "updated_at": "2017-05-23 06:37:14",
    "path": "1/2/20",
    "available_sort_by": [],
    "include_in_menu": true,
    "custom_attributes": [
        {
            "attribute_code": "display_mode",
            "value": "PRODUCTS"
        },
        {
            "attribute_code": "is_anchor",
            "value": "1"
        },
        {
            "attribute_code": "path",
            "value": "1/2/20"
        },
        {
            "attribute_code": "children_count",
            "value": "0"
        },
        {
            "attribute_code": "custom_use_parent_settings",
            "value": "0"
        },
        {
            "attribute_code": "custom_apply_to_products",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "clothes"
        },
        {
            "attribute_code": "url_path",
            "value": "clothes"
        }
    ]
}
```

It always shows updated value of the name, but never actually updates it in the store. And, of course, parent_id didn't change. 
![screenshot_2017-06-06_15-34-26](https://cloud.githubusercontent.com/assets/13581265/26829296/a829966e-4acd-11e7-83f6-9f3b488f0622.png)

I also updated Magento version from 2.1.6 to 2.1.7 in case if the problem was fixed. But it seems like the problem persists in both versions.

**Comment by rparsi-commer** [comment]
@Nikolay-Baychenko Try clearing/flushing the magento2 cache and reloading the page displaying the categories.

**Comment by nikolaybaychenko** [comment]
@rparsi-commer I'm afraid I did that.

**Comment by rparsi-commer** [comment]
@Nikolay-Baychenko It's odd, I haven't seen this behavior before.  I think your last resort is to trace the code.

In my local dev environment I'm using VMware, running an instance of CentOS 7
(I prefer Ubuntu server but client requirements forces me to use CentOS 7).

Using combination of PHPStorm, XDebug (configured for PHPStorm) and the Chrome Postman
extension I run traces of webapi endpoints.

That is how I debug things.
It's annoying but sometimes this is only way to figure out what's going on with specific webapi endpoint.

**Comment by rparsi-commer** [comment]
@Nikolay-Baychenko Sorry I just remembered you already tried debugging the code.
Have you tried just setting the `name`?
There are probably other fields that are required, so goal is to construct the minimal json
sent to the magento2 Rest endpoint where the `name` is changed.

Sorry am just thinking off the top of my head here.

**Comment by nikolaybaychenko** [comment]
@rparsi-commer It seems like besides an id as a path variable there has to be at least category mentioned in json. I tried setting only name, parent_id and is_active separately, same result. I am note sure about minimal json, at least it's arguing only if I don't pass anything at all. 
The minimal structure should be like this.
`{"category":{}}`

**Comment by rparsi-commer** [comment]
@Nikolay-Baychenko No that would never work.  Every magento2 entity has some fields that must have a value.  Submitting `{"category":{}}` should return a json with message and/or messages keys containing validation error messages.

**Comment by nikolaybaychenko** [comment]
@rparsi-commer This is what it returns. 
![screenshot_2017-06-08_09-52-46](https://user-images.githubusercontent.com/13581265/26915854-640a4ea6-4c30-11e7-9c6a-db22d8d05574.png)

**Comment by rparsi-commer** [comment]
@addxorsw Try sending this and let me know what happens:

```
{
  "category": {
    "id": 20,
    "parent_id": 2,
    "name": "string",
    "is_active": true,
    "position": 1,
    "level": 2,
    "path": "1/2/20"
  }
}
```

FYI I got the structure from [http://devdocs.magento.com/swagger/](http://devdocs.magento.com/swagger/)

**Comment by nikolaybaychenko** [comment]
@rparsi-commer All the same, nothing changed. In the store it's still called "Clothes". Other parameters didn't change either. 

Here is the response: 
```
{
  "id": 20,
  "parent_id": 2,
  "name": "string",
  "is_active": true,
  "position": 1,
  "level": 2,
  "children": "",
  "created_at": "2017-05-23 06:37:14",
  "updated_at": "2017-05-23 06:37:14",
  "path": "1/2/20",
  "available_sort_by": [],
  "include_in_menu": true,
  "custom_attributes": [
    {
      "attribute_code": "display_mode",
      "value": "PRODUCTS"
    },
    {
      "attribute_code": "is_anchor",
      "value": "1"
    },
    {
      "attribute_code": "path",
      "value": "1/2/20"
    },
    {
      "attribute_code": "children_count",
      "value": "0"
    },
    {
      "attribute_code": "custom_use_parent_settings",
      "value": "0"
    },
    {
      "attribute_code": "custom_apply_to_products",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "clothes"
    },
    {
      "attribute_code": "url_path",
      "value": "clothes"
    }
  ]
}
```

**Comment by rparsi-commer** [comment]
@addxorsw Honestly I'm stumped.  Have you tried disabling cache via the admin UI?  Just to see if the category names change in the customer UI.

**Comment by nikolaybaychenko** [comment]
@rparsi-commer It's been disabled all along.

**Comment by rparsi-commer** [comment]
@addxorsw Sorry, I'm out of ideas.  I'm still in the noob phase of learning magento2 framework.
Hopefully I can actually help you and other devs in the future, after I've learned enough "mag2".

Just my opinion:
The magento dev community seems to almost universally hate "mag2".
I find it very difficult to get real help; I've mostly stumbled my way into how to
do things in mag2.
That being said, your chances of getting actual help is better on the official irc channel
(`#magento2`).  Just beware that you have to indicate all the effort/research you've done
before anyone there will bother to even try to help you, but I have gotten actual help there.

I'm in the channel most of the time from about noon to 4pm EST.

**Comment by nikolaybaychenko** [comment]
@rparsi-commer Thanks for your help and the tips about irc. My purpose of reporting here is just report a bug, if it's an actual bug. What I need to do with the request I can most likely do another way around. 

I will probably close this issue and report it properly by guidelines later.

**Comment by bdandreas** [comment]
@addxorsw Hi, I have the same issue you have and found out the store_id is the issue here.

I use the API rest call rest/V1/categories/{id} as documented in swagger.
On a Post request, all values are correctly updated and working properly on a newly created category.

However, when i do the same request as a Put and added some changes in the values on inserted, the only differences was store_id in table "catalog_category_entity_text".
As it was created at default "all store views" it was saved as store_id=0 in the first place , but after an update it was stored with store_id=2.

I tried to add store_id as a custom_extension in the request but it was totally ignored.
Hopefully you recieved some response on this issue or how to workaround this matter.

**Comment by nikolaybaychenko** [comment]
@bdandreas Hi, thank you for you comment. 
Could you also leave the same message in referenced issue [here](https://github.com/magento/magento2/issues/9949). This problem was already acknowledged as bug and ticked created. You feedback might help developers to understand and solve problem if you report about it there.

**Comment by mzzhmh** [comment]
I have met the same problem, I tried to update isActive value but the mag2 backend won't change the value.
