### ISSUE TITLE
Extension attributes not working for customer address

### ISSUE THREAD

**Issue by dankocherga** [magento/magento2#9668]
Setting an extension attribute for customer address won't assign it to object so it's not validated and saved to database correctly.

### Preconditions
1. Magento CE 2.1.5

### Steps to reproduce
**1. Setup extension attribute:**
_extension_attributes.xml_
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Customer\Api\Data\AddressInterface">
        <attribute code="foo" type="string"/>
    </extension_attributes>
</config>
```

**2. Save extension attribute**

```php
<?php
use Magento\Customer\Api\AddressRepositoryInterface;
use Magento\Customer\Api\Data\AddressInterface;
use Magento\Customer\Api\Data\AddressInterfaceFactory;
use Magento\Framework\Api\ExtensionAttributesFactory;

class Test
{
    private $addressInterfaceFactory;
    private $addressRepository;
    private $extensionFactory;

    public function __construct(
        AddressInterfaceFactory $addressInterfaceFactory,
        AddressRepositoryInterface $addressRepository,
        ExtensionAttributesFactory $extensionFactory
    ) {
        $this->addressInterfaceFactory = $addressInterfaceFactory;
        $this->addressRepository = $addressRepository;
        $this->extensionFactory = $extensionFactory;
    }

    public function test()
    {
        $address = $this->addressInterfaceFactory->create();
        // save required address fields
        /** @var \Magento\Customer\Api\Data\AddressExtensionInterface $extension */
        $extension = $this->extensionFactory->create(AddressInterface::class);
        $extension->setFoo('bar');
        $address->setExtensionAttributes($extension);

        $this->addressRepository->save($address);
    }
}
```

### Expected result
At [this point](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/ResourceModel/AddressRepository.php#L126) of address save in the repository I expect to see `foo` field set in the `$addressModel` object data. Further it would be validated and saved to DB.

### Actual result
Field is not set, object still has it in `extension_attributes`:
```
["extension_attributes"]=>
  array(1) {
    ["foo"]=>
    string(3) "bar"
  }
```

This seems to happen because `DataObjectProcessor` [is used](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address.php#L141-L142) inside of `updateData` method.
`DataObjectProcessor` [does not replace the key](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php#L101-L102) while parsing extension attributes.

**Comment by veloraven** [comment]
@dankocherga thank you for your feedback.
Customer custom address attributes are available in Enterprise edition only.
As you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE and we can not treat it as an issue

**Comment by korostii** [comment]
@veloraven, [extension attributes and EAV attributes aren't the same thing](https://github.com/magento/devdocs/issues/1217#issuecomment-308672200), Are you sure you're not mixing up those?

**Comment by dankocherga** [comment]
OK, closing the issue since it's not going to be fixed by the core team.
I have used custom attribute method to solve the problem:

```php
<?php
$customerAddress->setCustomAttribute('attribute_code', 42);
```

**Comment by davinanaya** [comment]
@dankocherga can you share what did you do ? I'm trying to do the same. Thanks
