### ISSUE TITLE
Giftcard Expiration date of year 2500 renders as year 2000 on Marketing > GiftCard Accounts > GiftCard

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9675]
When dynamically -or- manually creating a Giftcard and the expiration date is set to year 2500, Magento 2.1.3 EE renders the expiration date as year 2000 - and it will not let the given Giftcard to apply on the order during checkout.

### Steps to reproduce

1. Create Giftcard manually on Admin panel Marketing > Gift Card Accounts > Create Gift Card
2. Set the EXPIRATION DATE to any day in year 2500
3. Save the giftcard
4. Reload the same page and check the date - the year now shows to be instead of 2500, it shows year 2000.

### Expected result
1. Magento should be able to render the year 2500 and allow Giftcard to be applied, as year 2500 is still in the future.

### Actual result
1. Magento renders year 2500 as year 2000, therefore setting new Giftcards as already time expired

**Comment by YevSent** [comment]
@paulartifact, this Github repository only for Magento CE versions. Please, create an appropriate ticket via EE support. Thanks for reporting.
