### ISSUE TITLE
Adding product configurations uses sku based name

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#9680]
### Preconditions
1.  Magento 2.x

### Steps to reproduce
1. Create a configurable product with some configurations (simple products)
2. Use name 'NAME'
3. Use sku 'SKU'
4. Create configurations and Generate products

### Expected result
1. Name of the simple products should be based on the parent product

### Actual result
1. Name is based on the sku of the parent product
![image 2017-05-18 at 11 09 39 am](https://cloud.githubusercontent.com/assets/17834386/26195034/b0207b66-3bba-11e7-9dd2-99dca28a2210.png)

**Comment by PascalBrouwers** [comment]
If necessary I can also create a PR for the 2.1-develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69297

**Comment by magento-engcom-team** [comment]
@PascalBrouwers thank you for your report.
The fix for this issue is already available in release 2.2.0
