### ISSUE TITLE
SSL: Handshake timed out Failed to enable crypto failed to open stream: operation failed

### ISSUE THREAD

**Issue by ooples** [magento/magento2#9688]
All of a sudden I started receiving these errors below when running composer update and I have no clue what is wrong. I ran commands using openssl to connect with repo.magento.com and they worked just fine so I'm completely lost

**Comment by gsomoza** [comment]
Do you have the same error when you try this from your local environment?

**Comment by ooples** [comment]
I don't have a local environment with a magento installation to test it on

**Comment by gsomoza** [comment]
You could set one up quite easily using the Magento [DevBox](http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-over.html).

The reason I asked is to discard the possibility of this being an issue with your server or network (I can confirm I set Magento up recently using the DevBox and didn't have this issue).

**Comment by ooples** [comment]
It runs just fine on my other server so it must be a server issue then
