### ISSUE TITLE
Form Problem

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#969]
I have also a Question whether we have to create all the template file for every custom module...
like:-
edit.phtml
tabs.phtml
for each  seperate module.

**Comment by maksek** [comment]
Hi @aishwaryacedcoss, can you provide more descriptive question. Not sure what do you mean here. Thanks.

**Comment by vkorotun** [comment]
Hi @aishwaryacedcoss , the right answer is "it depends" :)
If you need to create a basic interface, then as the most probably you don't need creating your custom templates for Grids and Forms, so you need only to configure those Widgets Blocks properly via layout file. But as @maksek requested, we need more details of your particular case to provide more clarity onto this subject.

Thank you.

**Comment by verklov** [comment]
@aishwaryacedcoss, we'd like to resolve your question. Could you please provide us with the additional details requested?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.
