### ISSUE TITLE
Visa cards with 13 or 19 digits are not working with authorize.net Magento 2.1.6 CE

### ISSUE THREAD

**Issue by charmeleon-zz** [magento/magento2#9691]
We are using magento 2.1.6 CE as a web store and we are using authorize.net for payment processing and configured a sandbox account. While testing using the [authorize.net testing guide](https://developer.authorize.net/hello_world/testing_guide/) using test card number `4012888818888` the frontend validation says that the card number is invalid.

### Steps to reproduce

1. Go to the payment step of the checkout process
2. Enter card number `4012888818888`
3. Click outside the input

### Expected result

1. User should be free to select an expiration date for the card

### Actual result

1. The user sees an error message saying `Please enter a valid credit card type number.`
![image](https://cloud.githubusercontent.com/assets/2086355/26219240/b7c20cea-3bd3-11e7-9689-f54750e6453e.png)

This is not a platform independent issue. It comes from the file `vendor/magento/module-payment/view/base/web/js/model/credit-card-validation/credit-card-number-validator/credit-card-type.js` where starting on line 15 the patterns for credit cards are declared:
```javascript
        var types = [
            {
                title: 'Visa',
                type: 'VI',
                pattern: '^4\\d*$',
                gaps: [4, 8, 12],
                lengths: [16],
                code: {
                    name: 'CVV',
                    size: 3
                }
            },
```
As seen on https://en.wikipedia.org/wiki/Payment_card_number, Visa card numbers can be 13, 16 or 19 digits in length, this `lengths` array is incorrect.

**Comment by YPyltiai** [comment]
Hi @charmeleon,

Thank you for indicating this. I was looking for an official confirmation that these 13 and 19-digit cards are really in use now but I was not able to find a relevant reference.

I have contacted VISA representatives, so if we get the confirmation from their side - we will create an internal ticket to address this issue. I will keep you updated.

Thank you!

**Comment by YPyltiai** [comment]
Hi @charmeleon,

I need to close this ticket, as 13-digit VISA cards are not in use anymore, while 19-digit VISA cards were never issued. Only 16-digit VISA cards are currently in use. If this changes some day, we will edit the validation. For now - the validation is correct.

Thank you!

**Comment by lucasvm** [comment]
Hello Sir, some Discover card type number are also giving error on validation, please try with this:

6011000400000000 Working
6011111111111117 Not Working

leght 16 for both and starting with 6011.

Working on others payment platforms.

**Comment by marilena6** [comment]
Hello,

I am facing the same problem on Magento 2.1.4 for any bank card I use.
Why is this happening? Does any one know the reason?

**Comment by abbasalis** [comment]
Guys, Any update on this issue? This is still happening for me in Magento 2.2.3. Tried with Test mode "yes" too. Not working. 

![Configuration   Settings   Stores   Magento Admin (1)](https://user-images.githubusercontent.com/13479622/54276455-65269280-45b3-11e9-985c-da874ca05114.png)

![Checkout (1)](https://user-images.githubusercontent.com/13479622/54276533-94d59a80-45b3-11e9-99d2-5abf2a7438ff.png)
