### ISSUE TITLE
Error using store-scope attribute values to create configurable product links via REST API

### ISSUE THREAD

**Issue by careys7** [magento/magento2#9693]
### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Create a store-scope attribute via admin
2. Add a store scope attribute value for the product via REST API
2. Use attribute to create a configurable product option via REST API at store scope
3. Attempt to assign a configurable product link to from a configurable product to a simple SKU via REST API (at store scope)

### Expected result

1. Product linked successfully

### Actual result

1. Error returned via API, product not associated:
```
"Child product does not have attribute value %1","parameters":["attribute_code_here"]"
```

It looks like the API is only looking at the attribute value from the default scope

**Comment by veloraven** [comment]
@careys7 thank you for your report.
Please provide exact requests you use.

**Comment by careys7** [comment]
Hi @veloraven - this is being tracked under an Enterprise support ticket now, so I will go ahead and close this issue.
