### ISSUE TITLE
After upgrading from magento 2.1.1 to magento 2.1.6 image resize error occurs

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#9698]
### Preconditions

1.  Run the following command through putty. php bin/magento catalog:images:resize
2. 

### Steps to reproduce

1. After run the php bin/magento catalog:images:resize
2. Got the following error ...Notice: getimagesize(): Read error! in /var/www/html/vendor/magento/module-catalog/Model/Product/Image.php on line 452
3. 

### Expected result

1.  Images have to resize accordingly

### Actual result

1. Command catalog:images:resize throws an error.

**Comment by YPyltiai** [comment]
Hello, @sasilinux,

Please see if this may help you: [Image Resize Issue with Magento version 2.1.6](http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_216-imageresize.html)

**Comment by bhargavmehta** [comment]
To Apply the patch use command

git patch MAGETWO-67805.patch

**Comment by sasilinux** [comment]
I am not using git. So please let me know how to update the mentioned patch in my magento 2.1.6

**Comment by heyepic** [comment]
I also need help fixing this as I'm not using git.

That being said, I read this is still an issue even after the patch?

**Comment by mzeis** [comment]
Magento just released 2.1.7 with a "reversion of the changes to image resizing that we introduced in 2.1.6": http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.html

Can you please check if the problem is gone in 2.1.7? Thanks!

**Comment by heyepic** [comment]
Thanks for the heads up - we will give this a shot!

**Comment by veloraven** [comment]
@sasilinux thank you for report.
Is this issue still actual after Magento 2.1.7 release?

**Comment by heyepic** [comment]
The problem is resolved on latest!

**Comment by pboisvert** [comment]
closing given issue is resolved by 2.1.7 release
