### ISSUE TITLE
When using payment methods with frontend event, just the buttons are removed

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#9699]
### Preconditions
1. Magento 2.1.6

### Steps to reproduce
1. Enable some payment methods in backend configuration
2. Create a new module with **frontend** observer (payment_method_is_active) to filter the active methods
3. Disable every payment method in the observer with the result object (is_available => false)

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="payment_method_is_active">
        <observer name="paymentmethodbycustomergroup_payment_method_is_active" instance="Codex\PaymentMethodByCustomerGroup\Observer\PaymentMethodIsActive" />
    </event>
</config>
```

### Expected result
1. No payment method will be displayed in checkout

### Actual result
1. All payment methods are still available, but the Buttons are removed

When moving the events.xml from frontend-folder to "global" (one directory above), everything works as expected. Seems like some events in Frontend-AJAX-Calls have the wrong area specified and do not hit the frontend observers.

**Comment by YevSent** [comment]
Hi, @klein0r, this is not a bug but an expected behavior.

> Seems like some events in Frontend-AJAX-Calls have the wrong area specified and do not hit the frontend observers.

Magento Checkout uses REST API calls and if you want to use observers in the correct way for the Checkout, you need to specify all events in the `webapi_rest` or in the `global` areas.

**Comment by klein0r** [comment]
Oh, sorry, I've had no idea that there exists an area for webapi_rest. Thanks for the response. Issue solved!
