### ISSUE TITLE
Cart Price Rule doesn't work with 'Shipping Country' condition

### ISSUE THREAD

**Issue by atsareva** [magento/magento2#9703]
**Preconditions:**

Install Magento 2.2.0
Magento 2.4-develop EE

**Steps to reproduce:**

1. Go to **Marketing* -> *Cart Price Rules**
1. Create a coupon code. (see attachments: **CartRuleAdmin*1.png*,*CartRuleAdmin*2.png*) The main issue to set '*Shipping Country*' (e.g Germany) in the *Conditions tab**.
1. Add product and go to shopping cart
1. Try to apply coupon code.(see attachment: **ShoppinCart.png**)
1. Go to the second step of checkout and try to apply coupon code again (see attachment: **checkout.png**)

(/) **Expected result:**

Coupon code should be applied, because the country is the same.

(x) **Actual result:**

'The coupon code "%1" is not valid.' - for both variant: when I set estimated shipping country and also when I logged in with needed address. But when I got to the second step of checkout I can apply this coupon code.

**Comment by Stas94** [comment]
@atsareva We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by atsareva** [comment]
@Stas94 
Recently I've updated magento to version **2.1.7** with sample data and have the same issue
I have **PHP 7.0.18** and **mysql  Ver 14.14 Distrib 5.7.18**

## Steps to reproduce
1. Create coupon code 
![cart_price_coupon](https://user-images.githubusercontent.com/1243876/27490729-107b1c7e-5848-11e7-9935-1e0a2e653051.png)

2. Create a new customer and set address
![customer_addresses](https://user-images.githubusercontent.com/1243876/27490780-4ae23870-5848-11e7-9925-c920c83ac034.png)

3. Add product and go to shopping cart
4. Try to apply coupon code there
![shopping_cart](https://user-images.githubusercontent.com/1243876/27490814-6196cb6c-5848-11e7-94ff-6589c3048d43.png)

5. Go to the second step of checkout and try to apply coupon code again
![checkout](https://user-images.githubusercontent.com/1243876/27490830-711cfade-5848-11e7-8d70-29ad91a2e287.png)

Thanks.

**Comment by Stas94** [comment]
@atsareva Thanks for reporting this issue. We've created internal ticket MAGETWO-70212 to address this issue.

**Comment by ghost** [comment]
I have the same problem with the "shipping country" condition, but in my case it happens without using coupons, we apply a 10% discount if the "shipping country" match the rule.
I noticed that in the second step of the checkout, if we go back to the first step (or do a refresh of the page) and then go to the second step, the discount appears.

**Comment by magento-engcom-team** [comment]
@atsareva, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by rliukshyn** [comment]
@magento-engcom-team This issue is reproducible for Guest. Once you login - coupon applies successfully.

**Comment by duffner** [comment]
@magento-engcom-team, this is still a bug in 2.2.3 as a guest within the cart.

**Comment by jeet-rocktechnolabs** [comment]
its still bug in the 2.2.3 , any solution?

**Comment by magento-engcom-team** [comment]
Hi @atsareva. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24740` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by pauldonnelly** [comment]
@magento-engcom-team I am having the same issue on 2.3.3. Is there a Patch we can apply to fix this ? Promotion going out soon and it's a requirement.

**Comment by badisdib** [comment]
Hello, I have the same problem even connected to magento 2.3.5, the conditions on the shipping country are not taken into account. Any idea please?

**Comment by poojapawar12** [comment]
@magento-engcom-team  I am facing same issue in magento 2.4.5-p1 version that on selecting shipping country in condition my cart price rule is not applying 
![image](https://github.com/magento/magento2/assets/133887565/b7118865-7176-4c63-9840-9a040700ea61)

**Comment by salvatorelapi** [comment]
some issue
