### ISSUE TITLE
Search Synonyms still not working on a fresh 2.1.6 installation.

### ISSUE THREAD

**Issue by martinhetschel** [magento/magento2#9707]
### Preconditions
1. Magento CE 2.1.5 / 6 / 7 without sample data is installed. No customization or custom modules.
2. Created Simple Product with Name "testprodukt" ("k")
3. Created Search Synonyms Group "testproduct,testprodukt,tstproduct"

### Steps to reproduce
Type "testproduct" ("c") in search box, click search icon

### Actual result
Actual result: "Your search returned no Results."

### Expected result
Expected result: show item "testprodukt" ("k")

### Additional information / Images
![image](https://cloud.githubusercontent.com/assets/17616012/26266570/2f1e6870-3ce6-11e7-8410-2ee2b9734787.png)

![image](https://cloud.githubusercontent.com/assets/17616012/26266594/46ffb2be-3ce6-11e7-8d36-2bc946694bff.png)

![image](https://cloud.githubusercontent.com/assets/17616012/26266606/56cc5724-3ce6-11e7-884b-827c5e43129d.png)

**Comment by veloraven** [comment]
@martinhetschel thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by Andrii-Deineha** [comment]
Hi @martinhetschel, Thanks for reporting this issue. Unfortunately, I could not reproduce the issue as you described it. Please provide more information about your Magento installation, including the versions of PHP and MySQL you are using as well as the web server.

**Comment by martinhetschel** [comment]
PHP version is (7.0.23-1+ubuntu16.04.1+deb.sury.org+1)

MySQL 5.7.19-0ubuntu0.16.04.1

**Comment by martinhetschel** [comment]
Apache/2.4.18

**Comment by magento-engcom-team** [comment]
Hello @martinhetschel. Could You without any harm to Your business or other deals reproduce Your issue on 2.1.9?

**Comment by magento-engcom-team** [comment]
@martinhetschel  If so, please try. Thanks.

**Comment by martinhetschel** [comment]
Same issue on 2.1.9
![image](https://user-images.githubusercontent.com/17616012/30749897-21eb69e6-9fb5-11e7-9fb1-57ba8dde8eb7.png)
![image](https://user-images.githubusercontent.com/17616012/30749948-556cd03e-9fb5-11e7-9d04-8aba897b9d79.png)
If you need any further info, just let me hear!
