### ISSUE TITLE
REST API insert doesn't check generated url_key length

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#9708]
When using REST API to insert entities the generated url_key doesn't seem to keep track of the generated request path in url_rewrites. This, on long paths, will generate duplicate keys when, for example, doing a sub-category name change from Admin. Pretty sure the problem lies with products.

### Preconditions
1. Magento 2.1.6 
2. REST API

### Steps to reproduce
1. POST to categories catalog a set categories building a reasonably large request path
2. POST to products catalog product that exceeds the max length for request path

### Expected result
1. An error .

### Actual result
1. Nothing

I imported via REST ~800 categories and ~16000 products. No errors/warning on generated path lengths.

Then went through admin and changed a sub category name triggering a cascade of url rewrite entries to be processed. I got duplicate key errors due to the, now, truncated key being the same with existing product.

**NOTE** It seems that the truncation is done on request path but the target path is not changed. At least in the url_rewrite table.

**Comment by TomashKhamlai** [comment]
Thanks for reporting this issue. I think that the issue is actual and important for us, according to the description, but there are no screenshots and code examples. Please provide code examples or screenshots at least.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
