### ISSUE TITLE
Blank Checkout Page in Magento 2.1.4

### ISSUE THREAD

**Issue by kaurg2516** [magento/magento2#9710]
I am having issue with magento checkout and cart page, everything is working fine but when i add product to cart and click on view cart it shows balnk page. After adding this"ini_set('display_errors', 1);" line of code in index.php it shows this error:
 "Fatal error: Cannot instantiate interface Magento\Vault\Api\Data\PaymentTokenInterfaceFactory in /home/costore/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73"
Don't know what i a doing wrong.
Here is the detail:
theme name: Sm_market
installation type: Quickstart installation
magento version: 2.1.4
php version 5.6
This the url to see the error: http://gemstore.co.in/magento2/checkout/cart/

**Comment by feronera** [comment]
Try to remove all file in var. And setup:upgrade again.

**Comment by kaurg2516** [comment]
Still the same error.

**Comment by YevSent** [comment]
Hi, @kaurg2516, starting from Magento 2.1.3 release, the `PaymentTokenInterfaceFactory` doesn't auto-generated anymore and doesn't have the default implementation. Try to find usages of `PaymentTokenInterfaceFactory` in your code or custom payment integrations and specify the implementation for this factory via `di.xml`.
The [Vault documentation](http://devdocs.magento.com/guides/v2.1/payments-integrations/vault/payment-token.html) contains more details about token factories.

**Comment by kaurg2516** [comment]
Thank you @joni-jones, but i have resolved this error.

**Comment by YevSent** [comment]
Ok, then I'm closing this issue.
