### ISSUE TITLE
Wrong resource model in Observer when using Flat tables

### ISSUE THREAD

**Issue by OZZlE** [magento/magento2#9725]
### Preconditions

1. Latest M2 development head
2. MySQL / PHP version does not matter.

### Steps to reproduce

The core event is triggered when using own custom CMS module so it's not possible to write steps to reproduce as you would need this module installed. Event is probably triggered in other cases also however (don't know when).

### Expected result
No fatal errors.

### Actual result

`[Thu May 18 16:27:38.170239 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Category\Flat::saveAttribute() in ../htdocs/vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php:54, referer: https://.../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170283 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: Stack trace:, referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9
[Thu May 18 16:27:38.170288 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #0 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver->execute(Object(Magento\Framework\Event\Observer)), referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170293 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #1 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver), Object(Magento\Framework\Event\Observer)), referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170298 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #2 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Objec..., referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9`

### Fix ###
I have made a PR with a fix here: https://github.com/magento/magento2/pull/9702

**Comment by andidhouse** [comment]
We just gave flat category and flat product catalog a try. 
CPU of a 8 Core dedicated server is on 98% on all cores after enabling... for over 1 hour now...

I think there a major problems here with this options and they should be removed as long as the problems with this options are not solved.

**Comment by magento-engcom-team** [comment]
Hi @OZZlE 
This event (i mean `CategoryUrlPathAutogeneratorObserver`) execute before save category (app/code/Magento/CatalogUrlRewrite/etc/events.xml:31).
Resource model for category may be `Magento\Catalog\Model\ResourceModel\Category\Flat` only when flat is available. This logic present in app/code/Magento/Catalog/Model/Category.php:316.
In standard magento behavior, the flat may be available only on frontend scope.

In your case you probably save category url on frontend scope. This is not correct behavior. You should save category on adminhtml scope.

**Comment by magento-engcom-team** [comment]
@OZZlE, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by OZZlE** [comment]
@magento-engcom-team Thank you! We were actually saving it from frontend scope but now we have moved the entire CMS into admin instead so this should no longer be an issue.

Great to know why it happened though!
