### ISSUE TITLE
Magento 2 EE : Solr search not working with Apply search weight on dropdown or multiselect field type attribute

### ISSUE THREAD

**Issue by amitphpdeveloper** [magento/magento2#9727]
Preconditions

1. Magento EE 2.1.4 without sample data is installed.
2. PHP 7.0.2, mysql 5.0

Steps to reproduce

Setup Solr as per instruction in magento 2 online documentation. Set solr as an active search engine and make sure connection is successfully. Save configuration setting and Do reindex to import doc on solr search server.
1.  Create attribute for example manufacturer_test with multiselect dropdown. set any 4 values and set search weight 2 or 3 lowest from others attribute's value. and then do index.

2. assign any value for manufacture_test to any one product then do reindex and perform search for manufacturer_test value. It willl not include that item in search result.

Expected result
1. Search Item should include in search list for search team of manufacturer_test value.

### Actual result
1. Product not found in search list.
![screenshot1](https://cloud.githubusercontent.com/assets/5249001/26302786/07c4b2c4-3f03-11e7-923a-d831dd3640eb.png)

![screenshot2](https://cloud.githubusercontent.com/assets/5249001/26302804/13e9c27e-3f03-11e7-9707-5a8bacbc49d5.png)

**Comment by choukalos** [comment]
Solr search engine does not support attribute search weight as configured from the GUI - you'll need to configure that in the Solr XML configuration file.  If you want to use attribute search weight from the GUI you'll need to use MySQL or Elasticsearch as your search engine.

This is a feature request.  We do not plan on continuing development on Solr, please switch to Elasticsearch.
