### ISSUE TITLE
USPS Priority Mail Express for International addresses not showing

### ISSUE THREAD

**Issue by pradeep38mail** [magento/magento2#9728]
### Preconditions

1. Magento Version 2.1.6, PHP 7
2. No Varnish, FPC Enabled

### Steps to reproduce

1. Keep Priority Mail in USPS methods selected in Admin Stores->Configuration->Sales->Shipping Methods->USPS
2. Add Product to the cart
3. Trying to get the shipping(Country->United Kingdom, Region->JS, ZIP->WC2A 2AE)

### Expected result

1. It should return the Priority Mail service, actually it is being returned but isServiceAvailable methods trying to validate the method using it's extra services which is creating issue because the response does not has these services.

### Actual result

1. 
![dreamweaver_2017-05-19_08-46-15](https://cloud.githubusercontent.com/assets/23617777/26303225/8cdfebda-3f04-11e7-9d55-ac245de175ff.png)

Looking forward for any response.

Thanks

**Comment by magento-engcom-team** [comment]
@pradeep38mail, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
