### ISSUE TITLE
[Question] Add jenkins-ci ant build.xml and tool configurations to repository

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#973]
I assume the core team is using some kind of ci besides travis-ci.
If there there is an ant build.xml (plus the configurations for the tools), would it be possible to add them to the repository?
Otherwise, if there are none, would you be open to a PR?

**Comment by maksek** [comment]
We are using Bamboo, and several plans for different testing, but our build.xml (s) has specific env data, and the reason why we don't share. 
Travis is public and thats where you can take a look.
If you have some specific question, and want example - let us know.

**Comment by Vinai** [comment]
It just would be handy to have a local build.
Would you consider merging a PR for a generic jenkins build config?

**Comment by fcapua-summa** [comment]
+1 to the idea of having a generic jenkins build config

**Comment by maksek** [comment]
@Vinai, sure - feel free to create PR config into dev/tools/jenkins/

**Comment by Vinai** [comment]
Thanks, probably will be until after the dev beta forum though. :watch:

**Comment by Vinai** [comment]
Just a quick update. I've based a jenkins build config (as I do most of my build configs) on the template provided at http://jenkins-php.org/.  
It currently includes running php -l, pdepend, phpcs, phpmd, phpdox and the unit and integration tests.
A build takes for ages to complete.
So in practice I keep all but the tests disabled.

I'm having a hard time to make up my mind. What do you think, should a jenkins build include all tools or only the unit and integration tests?

**Comment by maksek** [comment]
@Vinai, closing the feature request, since no progress on it. Let me know if you still up to this.

**Comment by Vinai** [comment]
Thanks Max. I've started to think that anybody who uses jenkins already has a working template that they adjust, and nobody who isn't familiar with jenkins would start using it because a build config was present. So no use adding and maintaining that.

**Comment by magento-engcom-team** [comment]
Hi @Vinai. Thank you for your report. 
The issue has been fixed in magento/magento2#27138 by @drpayyne in 2.4-develop branch
Related commit(s):
 - [945c427b17f9a7199982b10efe73c5f53f1d18cd](https://github.com/magento/magento2/commit/945c427b17f9a7199982b10efe73c5f53f1d18cd)

The fix will be available with the upcoming 2.4.0 release.

**Comment by drpayyne** [comment]
@magento-engcom-team, there's a bug when referencing issues cross repositories. The PR https://github.com/magento/magento2/pull/27138 mentioned issue 978 from the adobe-stock-integration repository, but the bot thinks it's from magento2 repository. It would be great if this was fixed, thanks!
