### ISSUE TITLE
Hello, Why attribute value on "Catalog" page can not same as on "New Product" page???

### ISSUE THREAD

**Issue by glwow** [magento/magento2#9731]
Hello, Why attribute value on "Catalog" page can not same as on "New Product" page???

**Comment by veloraven** [comment]
@glwow please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
