### ISSUE TITLE
Products not showing on listing page correctly

### ISSUE THREAD

**Issue by surabhinsi** [magento/magento2#9735]
We are facing a weird issue on category page, when we see the configurable products in admin for the categories like Women and Men product counts comes as 3000 and 2300 respectively but on frontend count gets decreased to 730 and 650 

1. Magento 2.1.6 
2. Php 7.0.18

1. Check the product count on Admin it is 3000 for one category
2. See the same on frontend it is 730
3. Reindexing no effect
4.Cache clean/flush no effect
5.Static content deploy no effect
6.Went to category disabled is_anchor and then saved the category(is_anchor was enabled for women)
7.Again after save changed is_anchor to yes for the same category and clicked on save category
8.Products coming with correct count on frontend
9.unless and until do not do the changes in attribute and product and do the reindexing product count will remain correct
![is-anchor-no](https://cloud.githubusercontent.com/assets/27842406/26348851/b4ef5134-3fcb-11e7-9f70-1f5fa618b68d.png)
![after-reindexing](https://cloud.githubusercontent.com/assets/27842406/26348850/b4ed4a7e-3fcb-11e7-9c52-608b185e5bf1.png)
![after-isanchor-save](https://cloud.githubusercontent.com/assets/27842406/26348852/b4f6430e-3fcb-11e7-8423-5f5d311348d6.png)

In screen shots you can check the changes in product count of same category only after the changes in is_anchor

10.If you again do the reindexing product count will become incorrect

**Comment by piatrouski** [comment]
Same issue, I think it was related to vendor/magento/module-catalog/Model/Indexer/Category/Product/AbstractAction.php - const RANGE_CATEGORY_STEP = 500;


```
<?php
namespace Blah\FixCatalogIndexer\Model\Indexer\Category\Product\Action;

use Magento\Catalog\Model\Indexer\Category\Product\Action\Full as FullParent;

class Full
    extends FullParent
{
    /**
     * Check whether select ranging is needed
     *
     * @return bool
     */
    protected function isRangingNeeded()
    {
        return false;
    }
}
```

**Comment by magento-engcom-team** [comment]
@surabhinsi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
