### ISSUE TITLE
Delete operation is forbidden for current area when creating account from checkout success page.

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#9736]
When creating an account from the checkout success page the following error is shown.
"Delete operation is forbidden for current area" 

Preconditions
1. Magento 2.1.6
2. PHP 7.0.15-1~dotdeb+8.1 (cli) ( NTS )
3. mysql  Ver 14.14 Distrib 5.6.33, for Linux (i686) using  EditLine wrapper

Steps to reproduce
1. Add products to cart and proceed through checkout while not logged in. 
2. Use a new email that does not match any existing customers.
3. Leave Street Address Line 2 Empty.
4. Complete checkout process.
5. Create an account from the create account button that appears on checkout success page.

Expected result
1. Account is created for user or an error shown to say this account already exists.

Actual result
1. Error is shown "Delete operation is forbidden for current area" 

Console shows:
Failed to load resource: the server responded with a status of 503 (Service Unavailable) /checkout/account/create/

Error in the logs for this page reads:
a:4:{i:0;s:71:"A customer with the same email already exists in an associated website.";i:1;s:10181:"#0 /var/www/deviw/public_html/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(141): Magento\Customer\Model\Acco$
#1 /var/www/deviw/public_html/vendor/magento/module-customer/Model/AccountManagement.php(662): Magento\Customer\Model\AccountManagement\Interceptor->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), NULL, '')
#2 /var/www/deviw/public_html/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(128): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), NULL, '')
#3 /var/www/deviw/public_html/vendor/magento/module-sales/Model/Order/CustomerManagement.php(117): Magento\Customer\Model\AccountManagement\Interceptor->createAccount(Object(Magento\Customer\Model\Data\Customer))
#4 /var/www/deviw/public_html/vendor/magento/module-checkout/Controller/Account/Create.php(78): Magento\Sales\Model\Order\CustomerManagement->create('15')
#5 /var/www/deviw/public_html/var/generation/Magento/Checkout/Controller/Account/Create/Interceptor.php(24): Magento\Checkout\Controller\Account\Create->execute()
#6 /var/www/deviw/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Checkout\Controller\Account\Create\Interceptor->execute()
#7 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Checkout\Controller\Account\Create\Interceptor->___callParent('dispatch', Array)
#9 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Account\Create\Interce$
#10 /var/www/deviw/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Checkout\Controller\Account\Create\Interceptor), Object(Closure), Object(Ma$
#12 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Account\Create\Interc$
#13 /var/www/deviw/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Account\Create\Interceptor), Object(Closure), O$
#15 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Account\Create\Interc$
#16 /var/www/deviw/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Checkout\Controller\Account\Create\Interceptor), Object(Closure), Object$
#18 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Account\Create\Interc$
#19 /var/www/deviw/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Account\Create\Interceptor), Object(Closure), Objec$
#21 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Account\Create\Inter$
#22 /var/www/deviw/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Checkout\Controller\Account\Create\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Account\Create\Interceptor), Object(Closure), Objec$
#24 /var/www/deviw/public_html/var/generation/Magento/Checkout/Controller/Account/Create/Interceptor.php(39): Magento\Checkout\Controller\Account\Create\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/deviw/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Account\Create\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#28 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor$
#29 /var/www/deviw/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\R$
#30 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Clo$
#31 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor$
#32 /var/www/deviw/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Obje$
#34 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor$
#35 /var/www/deviw/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Req$
#36 /var/www/deviw/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closur$
#37 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Intercepto$
#38 /var/www/deviw/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Re$
#39 /var/www/deviw/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closu$
#40 /var/www/deviw/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /var/www/deviw/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /var/www/deviw/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#43 /var/www/deviw/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#44 {main}";s:3:"url";s:25:"/checkout/account/create/";s:11:"script_name";s:10:"/index.php";}

**Comment by vityakopin** [comment]
I cannot reproduce this issue as described. Please provide the detailed steps I must follow to reproduce this issue. Is that clear install or upgrade? Have You installed some custom modules, which can evoke this issue?

**Comment by harrigo** [comment]
This was a fresh 2.1.6 install. I've tried very hard to find under exact what conditions this
happens. I have removed all modules from an installation and it was still
there. I then loaded a fresh sample database and it went away. I then
loaded my database back in and the problem came back. I spent hours trying
to find out maybe certain settings within admin that could cause this
however had no luck. I have launched a site with this issue however and am
not happy but unsure quite how to help you reproduce and fix i'm afraid.

**Comment by vityakopin** [comment]
Can you reproduce this issue on clean install of Magento without sample data? May be that you have installed some modules which made changes in your existing database, because of what arises this issue. Even after you disable or delete those modules, database will not be restored and problem will be repeated.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
