### ISSUE TITLE
Failing unit tests, PHP Fatal error Mock_OrderPaymentExtensionInterface

### ISSUE THREAD

**Issue by adi3009** [magento/magento2#9739]
Vanilla installation with sample data

Magento version: 2.1.6 Community Edition
PHP Version: 7.0.18
MySql version: 5.6.33-0ubuntu0.14.04.1
[test_output.txt](https://github.com/magento/magento2/files/1022240/test_output.txt)

**Comment by YevSent** [comment]
Hi, @adi3009, try to clear the `application/var` directory and run unit tests again.

**Comment by adi3009** [comment]
Thanks @joni-jones, clearing var directory fixed the fatal error.
