### ISSUE TITLE
[Question] Why are the page_layout XML files kept separate from other layout XML files?

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#974]
This question is simply for learning purposes. Any insight into the motivation behind this descision would be much appreciated.

What is the reason the page_layout XML files are kept in the separate directories from the "normal" layout XML files, only to be combined with the regular ones by `Magento\Core\Model\Layout\Merge::_loadFileLayoutUpdatesXml()` and treated the same thereafter?

As far as I can tell (and I very likely could be wrong) they can be referenced just like any other update handle and they can be extended and overridden just like any other layout XML File.

At first I thought that was to be able to easily add new page layouts, a.k.a. convention over configuration, but it turns out the available page layouts for each area come from their respective layouts.xml files.

Thank you for providing some insight!

**Comment by antonmakarenko** [comment]
As you may read my explanation at #976, the "page layouts" and "layouts" have different purposes. Note though that the "layout" directory in fact contains "page configuration" files -- it might be misleading (we didn't want to rename too many files when refactored "layouts" into "page configurations").

These file types have different schemas -- that's a technical reason to keep them separate. Yet they have the same mechanics of merging -- so the concept of "handles" applies to both types. Keeping them separate allows you to have files of different types with the same handle name -- e.g. `page_layout/default.xml` and `layout/default.xml`
