### ISSUE TITLE
Magento messing with  app/etc/env.php content

### ISSUE THREAD

**Issue by seyuf** [magento/magento2#9745]
### Preconditions

1. Magento 2.1.6
2. Php7
3. Debian jessie

Magento is replacing the content of my ```app/etc/env.php``` by this:
```
<?php
return array (
  'cache_types' => 
  array (
    'compiled_config' => 1,
  ),
);
```
Which lead to ```vendor/magento/module-store/Model/Config/Processor/Fallback.php on line 125 ``` exception because no data has been retrieved from db.
This happened after multiple ***module:enable / setup:upgrade***. 
It started failing at the setup:upgrade.

I don't know why is this happening so im posting it here in case someone could share a light on it.

To Fix the issue you have to reset your env.php.

**Comment by renttek** [comment]
Hi, what are the steps to reproduce? Maybe it's the same as Issue https://github.com/magento/magento2/issues/7165 ?

**Comment by seyuf** [comment]
Hi @renttek ,
your right this is seems to be exactly what happened. 
Im closing this issue for its a duplicate of #7165.
Thanks.
