### ISSUE TITLE
Magento 2.1.6 How to show normal price and final price on checkout/cart page

### ISSUE THREAD

**Issue by khongtoan1991** [magento/magento2#9748]
Hello,
In that case show include tax, i want show normal and final price for each item, please help me!
thanks

**Comment by veloraven** [comment]
@khongtoan1991 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by khongtoan1991** [comment]
Hello @veloraven 
i'm fixed it with code.
in file Magento_Checkout/templates/cart/item/default.phtml
`//price
<?php if ($canApplyMsrp): ?>
	<td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
		<span class="pricing msrp">
			<span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
			<?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
			<a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
				<span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
			</a>
		</span>
	</td>
<?php else: ?>
	<td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
		<?php 
			if($product->getPrice() > 0 && $product->getTypeId() !== 'configurable'){
					echo $block->convertPrice($product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue(), true);
			};
		?>
		<?php echo $block->getUnitPriceHtml($_item); ?>
	</td>
<?php endif; ?>
//subtotal
<td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
	<?php if ($canApplyMsrp): ?>
		<span class="cart msrp subtotal">--</span>
	<?php else: ?>
		<?php 					
			if($product->getPrice() > 0 && $product->getTypeId() !== 'configurable'){
					echo $block->convertPrice($block->getQty() * $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue(), true);
			};
		?>
		<?php echo $block->getRowTotalHtml($_item); ?>
	<?php endif; ?>
</td>`
[View image](http://prntscr.com/fmsa6d)
