### ISSUE TITLE
On Search - sort by "Price" for the Products price including tax is not works 

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#9749]
I have some products(lets say 30 with different prices), which have tax of 20%. I configure to show the product price including tax. On search when I used to sort by "Price" the product is not sorted as the price.

### Preconditions

1. Magento 2.1.6
2. MySQL 7.0.18
3. Nginx

### Steps to reproduce

1. Import the 30 products with tax and name of the products have some similar words. I have 9000 products.
2. Not configure the tax for the imported tax class for the products.
3. Search for the products.
4. Used to Sort the result by "Price". Sorting works fine.
5. Go to the following path **Store -> Configuration -> SALES -> Tax -> Price Display Settings -> Display Product Prices in Catalog** and select the option **Including Tax**
6. Flush the cache.
7. Now repeat step number 3 and 4. Now the result is not sorted by Price.

### Expected result

1. Result must be in the sorted order by Price.

### Actual result

1. Results aren't showing in the sorted order by Price.

**Comment by choukalos** [comment]
This is by design, please see this thread on [Stackexchange](https://magento.stackexchange.com/questions/176341/magento-2-layered-navigation-price-without-tax).
