### ISSUE TITLE
CustomerSampleData module inhibits outgoing mails when using areacode emulation

### ISSUE THREAD

**Issue by WilXP** [magento/magento2#9751]
The following code from Magento\CustomerSampleData\Magento\Framework\Mail\Transport\MailPlugin in the SampleData module inhibits sending emails when using area code emulation:

`
public function aroundSendMessage(
        \Magento\Framework\Mail\TransportInterface $subject,
        \Closure $proceed
    ) {
        return $this->appState->isAreaCodeEmulated() ? null : $proceed();
    }
`

This is unexpected behavior.
It sent us in a wild goose chase as to why our emails were not sent on dev.
Is there a special reason for this?

**Comment by veloraven** [comment]
@WilXP thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by WilXP** [comment]
Steps to reproduce:
1) Install and enable CustomerSampleData module.
2) Make your own module where email sending is called from an area code emulation function.

Actual result:
Mail is not sent.

Expected result:
Mail is sent.

Cause:
Take a look in the class Magento\CustomerSampleData\Magento\Framework\Mail\Transport\MailPlugin, I already pointed out the line of code that causes this issue, so you don't have to look for it.

**Comment by veloraven** [comment]
@WilXP thank you for your update.
Please, also identify which version of Magento you are running.

**Comment by tools-utrecht-hh** [comment]
It's this version: https://github.com/magento/magento2-sample-data/blob/develop/app/code/Magento/CustomerSampleData/Magento/Framework/Mail/Transport/MailPlugin.php

**Comment by magento-engcom-team** [comment]
@WilXP, thank you for your report.
We've created internal ticket(s) MAGETWO-80080 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@WilXP, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
