### ISSUE TITLE
AbstractCollection::getAllIds() reset order, why?

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#9758]
### Preconditions
1. Magento 2.2-dev

### Steps to reproduce
I want to use for example the `Magento\Catalog\Model\CategoryList` model to get a list of level 2 categories, sorted by `position`. Here is a code sample:

```
public function getCategories()
{
    $sortOrder = $this->sortOrderBuilder->setField('position')->setAscendingDirection()->create();
    $searchCriteria = $this->searchCriteria
        ->addFilter('level', 2)
        ->addSortOrder($sortOrder)
        ->create();
    return $this->categoryList->getList($searchCriteria)->getItems();
}
```

### Expected result
I should get a list of level 2 categories, sorted by `position`. 

### Actual result
I get a list of level 2 categories, sorted by `entity_id`.

After digging into the code, the `getList` function creates a category collection and then uses `$collection->getAllIds()` to browse them.

The `getAllIds` function call the protected function `_getAllIdsSelect`, which does

```
$idsSelect->reset(\Magento\Framework\DB\Select::ORDER);
```

Is there any reason to reset the order?

I see two potential fixes here:
1. Do not reset the order into `Magento\Eav\Model\Entity\Collection\AbstractCollection::_getAllIdsSelect()`
2. Do not call `$collection->getAllIds()` into `Magento\Catalog\Model\CategoryList::getList()` but just do a foreach on `$collection` instead.

Thanks!

**Comment by levhryhoriev** [comment]
Hi @VincentMarmiesse.
As I can see 
`

        $idsSelect = clone $this->getSelect();

        $idsSelect->reset(\Magento\Framework\DB\Select::ORDER);
  
`
Here we clone select before reseting. Are you sure that issue is here?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
