### ISSUE TITLE
When go checkout,Cart Price Rules 25%test coupon code can go wrong

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#9763]
### Preconditions

1. Magnto2 CE 2.2.0-dev
2. PHP 7.0.12
3.MYSQL 5.7

### Steps to reproduce

1. add cart price like this
![20170526105044](https://cloud.githubusercontent.com/assets/4518013/26478793/578c55a8-4194-11e7-8f33-4b21e09735c8.png)
2. then go frontend,add a product,then go checkout and payment,that can get wrong

### Expected result

1. go normal

### Actual result

![20170526105114](https://cloud.githubusercontent.com/assets/4518013/26478853/c718a2fa-4194-11e7-81cf-8162d71f11be.png)

This is a bug?
How can I fixed it?

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70198 was created.

**Comment by misha-kotov** [comment]
@michaeldyl520 is this issue caused by the special character in the coupon code? specifically `%`

**Comment by magento-engcom-team** [comment]
@michaeldyl520, thank you for your report.
We've created internal ticket(s) MAGETWO-70198 to track progress on the issue.

**Comment by gabrielqs-redstage** [comment]
Hey there, I'm working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82724

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by magento-team** [comment]
Hi @michaeldyl520. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1284 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
