### ISSUE TITLE
Why use search by sku?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#9767]
Catalog > ProductRepository > save.

I see [search by sku](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/ProductRepository.php#L641) and don't understand why.
```php
return $this->get($product->getSku());
```

What about use get by id instead?
```php
return $this->getById($product->getId());
```

**Comment by maksek** [comment]
Please use forum for questions, github is only for issues following issue template.
