### ISSUE TITLE
Admin dashboard Most Viewed Products Tab only gives default attribute set's products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9768]
In magento admin dashboard no products are showing in most viewed product grid if all product are in different attribute sets (not in default attribute set), even with magento sample data this grid is always displaying "We couldn't find any records.".

**Preconditions**

1. Magento ver. 2.1.5 with sample data
2. PHP Version 7.0.8

**Steps to reproduce**

1. Login to Customer Account
2. Visited Product "Minerva LumaTech™ V-Tee"
3. Login to magento admin panel
4. Check magento dashboard "Most Viewed Product" grid

**Expected result**
There should be a row for product "Minerva LumaTech™ V-Tee" as shown in the attached screenshot.
![screenshot_2](https://user-images.githubusercontent.com/14589296/27429588-301576aa-5763-11e7-81dc-efb73281be45.png)

**Actual result**
But no product is showing in the grid as shown in the attached screenshot.
![screenshot_3](https://user-images.githubusercontent.com/14589296/27429595-39380324-5763-11e7-849a-7e797c384005.png)

**Reason**
This result is coming from \Magento\Reports\Model\ResourceModel\Product\CollectionFactory and in this file setProductAttributeSetId set as default attribute set id as given below-
**$this->setProductAttributeSetId($product->getEntityType()->getDefaultAttributeSetId());** at line no. 121, that's why results are not showing for most viewed product if they have added in different attribute sets.
There should not use attribute set id to filter most viewed product collection at line no. 323-326.
So method **"addViewsCount"** of file **\Magento\Reports\Model\ResourceModel\Product\Collection** should be defined as given below.

`   

    public function addViewsCount($from = '', $to = '')
    {
        /**
         * Getting event type id for catalog_product_view event
         */
        $eventTypes = $this->_eventTypeFactory->create()->getCollection();
        foreach ($eventTypes as $eventType) {
            if ($eventType->getEventName() == 'catalog_product_view') {
                $productViewEvent = (int)$eventType->getId();
                break;
            }
        }

        $this->getSelect()->reset()->from(
            ['report_table_views' => $this->getTable('report_event')],
            ['views' => 'COUNT(report_table_views.event_id)']
        )
        ->join(
            ['e' => $this->getProductEntityTableName()],
            'e.entity_id = report_table_views.object_id'
        )
        ->where(
            'report_table_views.event_type_id = ?',
            $productViewEvent
        )->group(
            'e.entity_id'
        )->order(
            'views ' . self::SORT_ORDER_DESC
        )->having(
            'COUNT(report_table_views.event_id) > ?',
            0
        );

        if ($from != '' && $to != '') {
            $this->getSelect()->where('logged_at >= ?', $from)->where('logged_at <= ?', $to);
        }
        return $this;
    }`

**Comment by ghost** [comment]
Is there any update regarding this issue?

**Comment by veloraven** [comment]
@poojawebkul thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by ghost** [comment]
@veloraven thank you for the concern. I updated the issue please check. Thanks!

**Comment by ghost** [comment]
Is there any update regarding this issue?

**Comment by veloraven** [comment]
@poojawebkul we already have internal tickets for this issue:
Internal ticket for ver. 2.0 - MAGETWO-64144
Internal ticket for ver. 2.1 - MAGETWO-63818
They will be fixed in one of next releases.
Also it was fixed in develop branch, you can find corresponding commits in #5660

**Comment by ghost** [comment]
@veloraven  thank you for update.

**Comment by magento-engcom-team** [comment]
Hi @poojawebkul could you please let us know if the issue still exists on latest 2.2.0 release?

**Comment by magento-engcom-team** [comment]
@poojawebkul, thank you for your report.
We've created internal ticket(s) MAGETWO-81371 to track progress on the issue.

**Comment by ghost** [comment]
@magento-engcom-team , thanks for the notification, but issue still exists on latest version 2.2.0. Thanks again for your concern.

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by webkul** [comment]
@okobchenko thanks for update.

**Comment by khanhhuynh11** [comment]
hi, i use magento 2.3.4, i have issue "We couldn't find any records". We hope to help soon, thanks U very much!!!
![image](https://user-images.githubusercontent.com/64239754/80174827-08066880-861e-11ea-82a3-869be9e4cf48.png)
