### ISSUE TITLE
Overriding Minicart.phtml template breaks minicart dropdown content (shows blank/empty)

### ISSUE THREAD

**Issue by RedAtRareCandy** [magento/magento2#9773]
### Preconditions

1. Magento 2.1.6 via latest Magento DevBox Beta

### Steps to reproduce

1. Install Magento DevBox Beta
2. Add minicart.phtml template to your theme in Magento_Checkout/templates/cart/minicart.html (this can be the original code from app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml and it should still break the minicart dropdown).
3. Flush cache and also run bin/magento setup:upgrade
4. Reload homepage and click the cart icon.

### Expected result

1. The cart should display "Your cart is empty" message. Or the items in your cart.

### Actual result

1. Dropdown is empty. Illustrated in the following:
https://cloud.githubusercontent.com/assets/24561107/22732111/fd10552c-ee12-11e6-8cbd-c0deb8592aa5.png

Noticed that the minicart.phtml JavaScript throws errors as if it's not able to reference the right files...

**Comment by RedAtRareCandy** [comment]
I've noticed that in the Magento code for app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml that Ln44 seems to be the problem.

Ln44 is:
`window.checkout = <?php /* @escapeNotVerified */ echo $block->getSerializedConfig(); ?>;`

Updating that to the below works and fixes the issue, but why??
`window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;`

Note: I do not know if the above work-around opens the application up to error/issues (functionality, security, or otherwise).

Can anybody explain why it works though?
I do not understand why the original code from the original minicart.phtml file does not work?

**Comment by magento-engcom-team** [comment]
@RedAtRareCandy this is not a bug.
For 2.1.x versions method `getSerializedConfig()` does not exist in `\Magento\Checkout\Block\Cart\Sidebar`.
This method was introduced since 2.2.0 version.
If you have Magento 2.1.x, You should use method ` \Zend_Json::encode($block->getConfig())`

**Comment by magento-engcom-team** [comment]
@RedAtRareCandy, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by RedAtRareCandy** [comment]
Thanks! Makes sense, glad to know where I was going wrong!
