### ISSUE TITLE
Newsletter Subscription is cancelled automatically on Account Confirmation

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#9787]
Preconditions

Version 2.1.5

Steps to reproduce

Set Config->Customer->Customer Configuration: Require Emails Confirmation = Yes
Create a new Account
Select "Sign up for Newsletter"
Open Confirmation Mail and click the Confirmation-Link.

Expected result

Account should be confirmed
Newsletter should be subscribed
1 Thanks for Registration Mail should be send

Actual result

Account will be confirmed
Newsletter Subscribtion is removed
1 Thanks for Registration Mail is send
1 Unsubscription Mail is send

This is same issue #6445 reported before

**Comment by 1408sheva** [comment]
@msawyers Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70474 to address this issue.

**Comment by magento-engcom-team** [comment]
@msawyers, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
