### ISSUE TITLE
Product import - Data validation failed. Please fix the following errors and upload the file again.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9790]
Hello Team,

I would like to update related products for a SKU. To do it I have created a sample CSV file with columns sku and related_skus. When I try to import, it throws an error "Data validation failed. Please fix the following errors and upload the file again." and "1. Product Type is invalid or not supported in row(s): 1"

### Preconditions
1. I am using Magento ver 2.1.3. 

### Steps to reproduce
1. Create CSV with SKU and related_skus
2. System >> Import >> Entity Type "Products" >> Behavior "Add/Update" >> Select CSV file >> Check Data

### Expected result
1. It should pass validation.

### Actual result

1. Throw Data validation error 

![validation](https://cloud.githubusercontent.com/assets/17194891/26572565/1024a8a8-4538-11e7-9c8e-6582edfbc7bb.PNG)

I tried to create CSV with SKU and description and perform the same action. It worked for one time. After that I added new column related_skus - it started giving Data validation error. Now after removing related_skus and keeping SKU and Description - it still gives the same error. 

Also I tried to add product_type column - it gives next error with attribute_set and next product name. After adding these columns, it is creating a duplicate new product with same SKU name. 

There must be some way to update product attributes and related/crossell/upsell in bulk. Let me know if you require more information from my end.

**Comment by korostii** [comment]
I think I saw reports that the "Add/Update" mode isn't working properly. 
Have you tried choosing the "Replace" behavior instead? That one might better fit your needs.
Detailed info about different behaviors is available in [the user guide](http://docs.magento.com/m2/ce/user_guide/system/data-import.html).

Remember to do backups because this is a potentially destructive operation.

**Comment by ghost** [comment]
@korostii I just need to assign few SKUs in related products means just need to update attributes or related/crossell. 

Doing replace will delete the entire product and create a new entity. That wouldn't work I guess. 

Thank you

**Comment by korostii** [comment]
Well, other than that, it's hard to guess what might go wrong. 
I suspect the SKU are somehow different and double-check if there are any accidental whitespace characters in the SKU column and whether the character encoding is OK (there might be similarly-looking Cyrillic characters used, for example).

Would you be willing to attach the .CSV file you were using to this GitHub issue?

**Comment by ghost** [comment]
[test.xlsx](https://github.com/magento/magento2/files/1037574/test.xlsx)

I am using this file for import. I just converted to XLSX as Github not supporting CSV files. 

All SKUs are in capital letters in Magento as well as in spreadsheet.

**Comment by vityakopin** [comment]
Hi @ravibhalodia ! Thanks for reporting this issue. Unfortunately, I could not reproduce the issue as you described it. I have installed clear 2.1.3 version of Magento, manually created simple products with sku like in your file and tried to import attached file. There was no problems doing the import. Related skus was successfully attached to my main product.  Please add more details to your description of the steps you followed when identifying this issue. Logs would be helpful, too.

**Comment by maderlock** [comment]
Please see https://github.com/magento/magento2/issues/6939 for a possible explanation.

The real bug here is that Magento allows an attribute to be made with the code product_type. If there were actually a system attribute called product_type then this would be checked on creation, but we're supposed to just know that this is a reserved word even though the actual attribute for products is "type_id".

**Comment by valuead** [comment]
same issue. 
trying a single record on 2.2.5 version and can't upload import. The product type is wrong on 75 product dump about half can't pass the validation. please advise


here is the data 
sku;store_view_code;attribute_set_code;product_type;categories;product_websites;name;description;short_description;weight;product_online;tax_class_name;visibility;price;special_price;special_price_from_date;special_price_to_date;url_key;meta_title;meta_keywords;meta_description;created_at;updated_at;new_from_date;new_to_date;display_product_options_in;map_price;msrp_price;map_enabled;gift_message_available;custom_design;custom_design_from;custom_design_to;custom_layout_update;page_layout;product_options_container;msrp_display_actual_price_type;country_of_manufacture;additional_attributes;qty;out_of_stock_qty;use_config_min_qty;is_qty_decimal;allow_backorders;use_config_backorders;min_cart_qty;use_config_min_sale_qty;max_cart_qty;use_config_max_sale_qty;is_in_stock;notify_on_stock_below;use_config_notify_stock_qty;manage_stock;use_config_manage_stock;use_config_qty_increments;qty_increments;use_config_enable_qty_inc;enable_qty_increments;is_decimal_divided;website_id;deferred_stock_update;use_config_deferred_stock_update;related_skus;crosssell_skus;upsell_skus;hide_from_product_page;custom_options;bundle_price_type;bundle_sku_type;bundle_price_view;bundle_weight_type;bundle_values;associated_skus
3301;;Default;simple;"Default Category/Gear;Default Category/Gear/Fitness Equipment";;Sprite Yoga Strap 6 foot;"<p>The Sprite Yoga Strap is your untiring partner in demanding stretches; holds and alignment routines. The strap's 100% organic cotton fabric is woven tightly to form a soft; textured yet non-slip surface. The plastic clasp buckle is easily adjustable; lightweight and urable under strain.</p><ul><li>100% soft and durable cotton.<li>Plastic cinch buckle is easy to use.<li>Three natural colors made from phthalate and heavy metal free dyes.</ul>";;1;1;Taxable Goods;"Catalog; Search";14;;;;sprite-yoga-strap-6-foot;Meta Title;"meta1; meta2; meta3";meta description;"2015-10-25 03:34:20";"2015-10-25 03:34:20";;;Block after Info Column;;;;;;;;;;;Use config;;"has_options=1;quantity_and_stock_status=In Stock;required_options=0";100;0;1;0;0;1;1;0;0;1;1;;1;0;1;1;0;1;0;0;1;0;1;"24-WG087;24-WG086";"24-WG087;24-WG086";"24-WG087;24-WG086";;"name=Custom Yoga Option;type=drop_down;required=0;price=10.0000;price_type=fixed;sku=;option_title=Gold|name=Custom Yoga Option;type=drop_down;required=0;price=10.0000;price_type=fixed;sku=;option_title=Silver|name=Custom Yoga Option;type=drop_down;required=0;price=10.0000;price_type=fixed;sku=yoga3sku;option_title=Platinum";;;;;;
