### ISSUE TITLE
Selecting HK$ as currency strips the "HK" part, resulting in only "$" getting displayed in UI

### ISSUE THREAD

**Issue by diamond-miner** [magento/magento2#9791]
### Preconditions

1. Bitnami AWS AMI

### Steps to reproduce

1. Change base currency to Hong Kong Dollar in Stores -> Configuration -> General -> Currency Setup -> Base Currency

### Expected result

1.  Base currency symbol in UI should be HK$[PRICE] for example, HK$13.00 as defined in Currency Symbol Settings

### Actual result

1. UI displays only "$" as currency symbol, for example $12.300

CURRENT WORKAROUND:

In Currency Symbol settings (Stores -> Currency Symbols), uncheck "Use Standard" and add a space after "HK$", so that the currency symbol become "HK$ ". After these steps, the currency symbol gets displayed, but with a space, resulting in a price such as "HK$ 13.00"

**Comment by veloraven** [comment]
I'm closing this issue as it is a duplicate for #9696.
