### ISSUE TITLE
Couldnot place order "An error occured on the server. Please try to place the order again"

### ISSUE THREAD

**Issue by puples** [magento/magento2#9792]
hello

i have a problem with payment by credit card, I have magento 2.1.5

### Steps to reproduce
i have a redirect to the cart when i add a product.

1. go to the store (not connected to an account)
2.  add a simple product (redirect to the cart)
3. click to checkout (a form login appear)
4. connect and go the checkout
5. enter shipping method & address
6. go to payment (select payment by credit card)

I have nothing in log but i have this in chrome:

POST https://www.XXX.com/rest/default/V1/carts/mine/payment-information 400 ()
send @ jquery-latest.min.js:4
ajax @ jquery-latest.min.js:4
post @ storage.js:39
(anonymous) @ place-order.js:17
(anonymous) @ place-order.js:33
_super @ wrapper.js:73
(anonymous) @ place-order-mixin.js:20
(anonymous) @ wrapper.js:78
getPlaceOrderDeferredObject @ default.js:163
placeOrder @ default.js:140
(anonymous) @ knockout.js:3863
dispatch @ jquery-latest.min.js:3
r.handle @ jquery-latest.min.js:3

if i open "/rest/default/V1/carts/mine/payment-information" in chrome i have this:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<payment_methods>
<item>
<code>checkmo</code>
<title>Chèque</title>
</item>
<item>
<code>systempay_standard</code>
<title>Paiement par carte bancaire</title>
</item>
</payment_methods>
<totals>
<grand_total>33.18</grand_total>
<base_grand_total>35</base_grand_total>
<subtotal>33.18</subtotal>
<base_subtotal>33.18</base_subtotal>
<discount_amount>0</discount_amount>
<base_discount_amount>0</base_discount_amount>
<subtotal_with_discount>33.18</subtotal_with_discount>
<base_subtotal_with_discount>33.18</base_subtotal_with_discount>
<shipping_amount>0</shipping_amount>
<base_shipping_amount>0</base_shipping_amount>
<shipping_discount_amount>0</shipping_discount_amount>
<base_shipping_discount_amount>0</base_shipping_discount_amount>
<tax_amount>1.82</tax_amount>
<base_tax_amount>1.82</base_tax_amount>
<weee_tax_applied_amount/>
<shipping_tax_amount>0</shipping_tax_amount>
<base_shipping_tax_amount>0</base_shipping_tax_amount>
<subtotal_incl_tax>35</subtotal_incl_tax>
<shipping_incl_tax>0</shipping_incl_tax>
<base_shipping_incl_tax>0</base_shipping_incl_tax>
<base_currency_code>EUR</base_currency_code>
<quote_currency_code>EUR</quote_currency_code>
<items_qty>1</items_qty>
<items>
<item>
<item_id>10853</item_id>
<price>33.18</price>
<base_price>33.18</base_price>
<qty>1</qty>
<row_total>33.18</row_total>
<base_row_total>33.18</base_row_total>
<row_total_with_discount>0</row_total_with_discount>
<tax_amount>1.82</tax_amount>
<base_tax_amount>1.82</base_tax_amount>
<tax_percent>5.5</tax_percent>
<discount_amount>0</discount_amount>
<base_discount_amount>0</base_discount_amount>
<discount_percent>0</discount_percent>
<price_incl_tax>35</price_incl_tax>
<base_price_incl_tax>35</base_price_incl_tax>
<row_total_incl_tax>35</row_total_incl_tax>
<base_row_total_incl_tax>35</base_row_total_incl_tax>
<options>[]</options>
<weee_tax_applied_amount/>
<weee_tax_applied/>
<name>Product</name>
</item>
</items>
<total_segments>
<item>
<code>subtotal</code>
<title>Sous-total</title>
<value>35</value>
</item>
<item>
<code>shipping</code>
<title>Frais de port</title>
<value>0</value>
</item>
<item>
<code>tax</code>
<title>Taxe</title>
<value>1.82</value>
<extension_attributes>
<tax_grandtotal_details>
<item>
<amount>1.82</amount>
<rates>
<item>
<percent>5.5</percent>
<title>TVA 5.5</title>
</item>
</rates>
<group_id>1</group_id>
</item>
</tax_grandtotal_details>
</extension_attributes>
</item>
<item>
<code>grand_total</code>
<title>Montant global</title>
<value>35</value>
<area>footer</area>
</item>
</total_segments>
</totals>
</response>

for the checkout work after this i need to return at home, click on cart and go to the checkout.

can you help me please.

regards

**Comment by YevSent** [comment]
Hi, @puples, please provide additional details, like selected payment method and custom extensions.

Also, you need to enable debug mode for the selected payment method and provide transaction details.

To find original reason of fails, you can use xdebug and set breakpoints in the https://github.com/magento/magento2/blob/2.1/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83 and https://github.com/magento/magento2/blob/2.1/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L71 or can use a logger to find original reason of failing like in https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L90

You can find these classes in the `vendor` directory.

**Comment by puples** [comment]
hi thanks for help, the problem come from shipping address. 
I can choose a shipping method with no adress selected (i have a button "Ship Here" but the only address of account is not selectionned) and go to the payment method. 

it is possible to force default shipping address enable ? 

thanks a lot

**Comment by YevSent** [comment]
Please, clarify the issue with shipping address. Does customer have default shipping address?

On Magento 2.1.6 it looks like this:
![one address](https://cloud.githubusercontent.com/assets/2736528/26620155/4a60d49e-45ea-11e7-82e6-25f83b6bd51d.png)
Or two addresses:
![2 addresses](https://cloud.githubusercontent.com/assets/2736528/26620159/50d30c20-45ea-11e7-9995-6252452393db.png)
The default shipping address is always selected.

**Comment by YevSent** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks.

If you still can reproduce the issue, please, be free to reopen it.

**Comment by rab14191** [comment]
i m using magneto 2.1.7   in luma theme
i got same problem   

i m useing Flat Rate shiping method and payment Cash on D

**Comment by puples** [comment]
hello,

sometimes when a customer (not log in) add a product on the cart, clic on "checkout", log in and go to the checkout page the defaut adress was not check in : 

![image](https://user-images.githubusercontent.com/5375534/27998283-1e34003a-650c-11e7-865e-afde1198af1c.png)


the problem, he can select a shipping method go to the payment but he can't go to the bank detail (error). he must become in step 1 clic on ship here and go to step 2. a lot of customer doesn't see the "ship here" button and call us because it doesn't work...

**Comment by Siyadev9** [comment]
This is really irritating
