### ISSUE TITLE
Make bin/magento admin:user:create interactive

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#9794]
### Preconditions

1. All Magento 2 versions

### Steps to reproduce

1. Run `bin/magento admin:user:create`

### Expected result

1. The command should ask for a username, followed by asking for first name, etc etc. Like `magerun2 customer:create` does (see sourcecode [here](https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/Customer/CreateCommand.php));
```
$ magerun2 customer:create
Email: peterjaap@elgentos.nl
Password: etcetc
```

### Actual result

1. You get a ton of warnings for every field not given;
```
$ magerun2 admin:user:create
User Name is a required field.
First Name is a required field.
Last Name is a required field.
Please enter a valid email.
Password is required field.
Your password must be at least 7 characters.
Your password must include both numeric and alphabetic characters.
```

**Comment by steverobbins** [comment]
#2690

**Comment by peterjaap** [comment]
My Github search foo abandoned me once again ..... :disappointed:

**Comment by steverobbins** [comment]
In your defense it's way old.
