### ISSUE TITLE
Installing user configuration... Still showing after complete module installaion

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#980]
Still it  showing Installing user configuration...
 
![capture](https://cloud.githubusercontent.com/assets/7018680/5791746/00e72402-9f12-11e4-946e-824aa185818d.JPG)

**Comment by maksek** [comment]
Hi @chaluvadiswamy, can you please provide more details on the issue.

**Comment by mazhalai** [comment]
@chaluvadiswamy as requested by @maksek please provide what version of Magento, MySQL, Apache/Nginx, PHP and OS you are using.

**Comment by monkeysee** [comment]
Looks like setup is running into a warning or exception and is unable to continue. Unfortunately, there is a problem that not all errors are reported in the Web setup wizard (MAGETWO-31951). You can try the command line install and that should display the error. This is just a guess, but one common problem is having xdebug enabled and xdebug.max_nesting_level set too low : https://github.corp.ebay.com/pages/Magento/devdocs_internal/guides/v1.0/release-notes/release-notes.html#known-devbeta-xdebug

**Comment by chaluvadiswamy** [comment]
@maksek ,please find the below screen
![capture](https://cloud.githubusercontent.com/assets/7018680/5850863/f56cfd40-a222-11e4-92c4-b3335a00c24c.JPG)

@mazhalai ,See the version details as you requested
![version](https://cloud.githubusercontent.com/assets/7018680/5850880/454f8422-a223-11e4-9975-19fb4d4e5426.JPG)

**Comment by Mirogniewa** [comment]
Same issue here.

Check if you have a message like that 
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /vendor/composer/ClassLoader.php on line 318
in your error.log. If so, then the following may work: http://devdocs.magento.com/guides/v1.0/release-notes/release-notes.html#known-devbeta-xdebug

**Comment by mazhalai** [comment]
@chaluvadiswamy can you try @Mirogniewa's suggestion of increasing `xdebug.max_nesting_level` and let us know if installation worked fine? 
Also, what version of Magento did you try to install?

**Comment by RxOuchy** [comment]
Just ran into this same Issue. Disabling xdebug fixed it for me!

**Comment by kassner** [comment]
Increasing `xdebug.max_nesting_level` to `200` worked for me.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-31951

**Comment by mazhalai** [comment]
This issue has been fixed and will be available publicly by the end of this week.

**Comment by chaluvadiswamy** [comment]
Thanks for you support friends

**Comment by snohe** [comment]
@chaluvadiswamy, thanks for your confirmation.  We'll go ahead and close this issue.  Should you notice any other issues, feel free to open another GitHub issue.
