### ISSUE TITLE
Attribute values intermittently duplicating against a product in catalog_product_entity tables

### ISSUE THREAD

**Issue by tonybrown85** [magento/magento2#9800]
### Preconditions

1. PHP Version 7.0.19
2. Linux cPanel VPS
3. Magento 2.1.5

### Steps to reproduce

1. Save product attributes against a product
2. intermittently the filters will display different results of said attribute value on the product grid page in backend.
3. Checking the database will show 2 rows against the attribute and entity id causing the conflicts. Normally with either a store id of 0 or 1

### Expected result

1. After setting an attribute against a product after save the attribute value should only create on row in the appropriate table for the attribute type

### Actual result

1. Intermittently the product will save with two attribute values with the same id but with either store id of 1 or 0

On occasions when saving a product a duplicate row will be created in the entity table for the attribute type with the same id. These will have different values but will also be either set to a store_id of 0 or 1. The configuration scope is always set to "All Store Views". This causes the correct value to be shown on the product edit page but a different value on the product grid page. All products are being edited on the product edit pages as well rather than the product grid page. Also no global actions are undertaken such as update_attributes. So there definitely seems to be a bug with duplicates being created against a attribute_id and entity_id. I have even seen this create a duplicate value in a different attribute type table as well which is even more strange. Any help to resolve this would be greatly appreciated as it's becoming a major issue when populating products.

**Comment by magento-engcom-team** [comment]
@tonybrown85, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
