### ISSUE TITLE
Admin page Stores Hierarchy Editing: Firefox private window bug

### ISSUE THREAD

**Issue by iglaze-kadro** [magento/magento2#9804]
### Preconditions

1. Magento ver. 2.1.5
2. PHP 7
3. MySQL Professional Edition, version 6.2.280

### Steps to reproduce

1. To replicate this issue, start a new "New Private Window" with Firefox, and log in to the admin site.
2. Go to "Content" in the left navigation of the Admin, then click on "Hierarchy" under "Elements".
3. Look at how the page is displayed initially.

### Expected result

1. You should see a tree diagram for the hierarchies at the top of the page, before the CMS Pages section.
![image](https://cloud.githubusercontent.com/assets/29074956/26604969/363e7236-455a-11e7-811c-327beb469719.png)

### Actual result

1. Instead, these sections are present above the CMS Pages section: "Page Properties", "Render Metadata in HTML Head.", "Pagination Options for Nested Pages", "Page Navigation Menu Options", "Main Navigation Menu Options".
![image](https://cloud.githubusercontent.com/assets/29074956/26604949/135d684e-455a-11e7-83c4-45d73bf50dfa.png)

**Comment by Stas94** [comment]
@iglaze-kadro If this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by veloraven** [comment]
@iglaze-kadro please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
As this is not CE functionality we can not treat this issue as GitHub issue.
So I'm closing it.
