### ISSUE TITLE
HTML minifier breaks if php comments are joined with php end tag ?>

### ISSUE THREAD

**Issue by PiimegaOy** [magento/magento2#9806]
### Preconditions

1. tested with 2.1.6 and 2.1.2

### Steps to reproduce

1. add comment like this to any template file
`<?php //This is a test comment?>`

2. In the admin panel enable HTML minification

3. Switch to production deploy mode (minification is not applied in developer mode)

4. Check page.

### Expected result

1. The template should work

### Actual result

1.  The comment + the ‘?>’ will be removed, i.e template will be broken

The error comes from the file Magento\Framework\View\Template\Html\Minifier where it replaces it on the line 131 (version 2.1.2) in the following pattern

`‘#(?<!:|\\\\|\’|“)//(?!\s*\<\!\[)(?!\s*]]\>)[^\n\r]*#‘,`

Let me know if you need any more info

**Comment by hostep** [comment]
This was already reported: https://github.com/magento/magento2/issues/5316 ;)

**Comment by PiimegaOy** [comment]
@hostep Alright thanks, must have missed it.
I'll close this one then :)
