### ISSUE TITLE
Changes in Miscellaneous HTML is not reflecting

### ISSUE THREAD

**Issue by pmjcreations** [magento/magento2#9808]
### Preconditions

1. Magento CE 2.1.6 for both my testing and primary domain.

### Steps to reproduce

1. I tried to install Facebook Messenger code. I pasted the code in Content > Design > Configuration > Footer >  Miscellaneous HTML.

### Expected result

1. I should see the Facebook Messenger icon on the website.

### Actual result

1. I could see Facebook Messenger only on the testing domain. I can't see that on my primary domain.

I did everything that I did with the testing domain, but I can't see the Facebook Messenger at the front end, and the code is not generated when I checked the source code.
The primary domain installed Magento CE 2.1.5 using Softaculous and upgraded to Magento CE 2.1.6 using composer. It was an installation without the sample. 

I have installed the test account with and without sample data and checked both. 

I followed https://github.com/magento/magento2/issues/3333#issuecomment-260294658. However, all the three files are listed there is identical between my test and primary accounts. 

The same issue happened to me while editing Content > Design > Configuration > HTML > Scripts and Style Sheets. Here also, changes are reflecting only on the test account. But other things like changing Copyright and Favicon is working fine.

**Comment by ArthurTransoftgroup** [comment]
Hello, @pmjcreations if you are using a Facebook app to install the widget (Messanger Code), please make sure that you had set up the "App Domains" in your facebook app settings, to be set for both websites (both domains).  Let me know if it worked for you.

**Comment by pmjcreations** [comment]
Hello @ArthurTransoftgroup, the problem here is not with the code and its implementation. The issue is, the Miscellaneous HTML section and Scripts and Style Sheets section are not pushing the code to the front end. So whatever I add to those sections, the changes aren't reflecting.

**Comment by ArthurTransoftgroup** [comment]
@pmjcreations Unfortunately, I can't reproduce this issue, the way you described it. Please open the front end of your website and check your developer tools (browser console) and let me know if you have any errors there. Also, please let me know, what software are you using?  (your browser, extensions, etc.)

**Comment by pmjcreations** [comment]
Yes, @ArthurTransoftgroup. For me this is strange. I have a test domain which produces the output as it should be. All changes are reflecting instantly.
Both my test domain and production domain is using the same theme and same version of Magento.
I guessed this might due to issues with any dependencies or the way I installed (I installed with Softaculous). But I have upgraded two version after the initial installation.
I am using Google Chrome for managing both primary and test domains. And I guess, most of the extensions I am using for my main domain is also installed for my test account.

**Comment by ArthurTransoftgroup** [comment]
@pmjcreations Please provide us your errors from your developer tools (browser console), and if it's possible, attach a couple of screenshots, so we can work together with this problem.

**Comment by pmjcreations** [comment]
Thank you so much for your promise @ArthurTransoftgroup. Will you find it more useful, if I shared the URL with you?
If yes, http://tshirtmacha.xyz/ is the test account. See the Messenger icon bottom right of the page.
https://threadly.store is the primary domain.

**Comment by ArthurTransoftgroup** [comment]
@pmjcreations I was wondering to ask you when you are trying to save the code (your HTML) do you have any errors in your admin panel? And let me know if your code is getting saved in your admin panel?

**Comment by pmjcreations** [comment]
Hello @ArthurTransoftgroup, I tried to add something within the Miscellaneous HTML section. And I found an answer to the question, why the changes are not reflecting.
Please have a look at this [screenshot](https://prnt.sc/fx2ucq).

_Test Domain_
When I edit Miscellaneous HTML of the 1, the changes are getting saved to 1, 2 and 3. I hope this is the right output as I guess 1, 2 and 3 are sharing a parent/child/inheritance relationship. After flushing the cache, I could see the changes at the front end.

_Primary Domain_
When I edit Miscellaneous HTML of the 1, the changes are getting saved to 1 and 2, not in 3. 3's Miscellaneous HTML input box is empty. I have added the same code in 3's Miscellaneous HTML, separately. It got saved without any error. I flushed the cache and saw the changes.

If the Test Domain case is the expected output, then the actual problem with Primary Domain is this missing inheritance.

**Comment by ArthurTransoftgroup** [comment]
@pmjcreations Yes alway make sure that you are editing your current theme (store). I am glad that it worked out for you. We are closing this issue. If you will have any questions or issues in future, feel free to ask. Have a good day.

**Comment by pmjcreations** [comment]
Thank you so much for your support @ArthurTransoftgroup.
Keep on Rocking!
