### ISSUE TITLE
Changing a store isn't saved into quote

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#9811]
### Preconditions

1. Magento Community v2.1.6
2. Have at least two stores

### Steps to reproduce

1. Add a product to cart
2. Change to another store
3. Go to checkout and complete it

### Expected result

The quote and order have the store_id that was last switched to

### Actual result

The store didn't change. It remains the same as when the quote was first created.

The store used in the quote doesn't get updated when one switches the stores. This means translations of shipping methods are wrong since they rely on the store. The order also gets placed in the wrong store because of that.

**Comment by tranductrong92** [comment]
trong

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate for #7582.
We already have internal ticket for it - MAGETWO-70060
