### ISSUE TITLE
Missing placeholder attribute in ui select(with customEntry) element

### ISSUE THREAD

**Issue by MaN4thes3t** [magento/magento2#9814]
Can't add placeholder for input when creating select with customEntry because placeholder attribute is missing in inputNode object.
Also, you can't change the component for this input.
File:
vendor/magento/module-ui/view/base/web/js/form/element/select.js

**Comment by veloraven** [comment]
@MaN4thes3t thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for an advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
