### ISSUE TITLE
System upgrade from Magento 2.1.6 CE to Magento 2.1.7 CE fails

### ISSUE THREAD

**Issue by charmeleon-zz** [magento/magento2#9815]
### Preconditions

I have a site running Magento 2.1.6 CE on PHP 7.0.17. I installed it via `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`

I used the web setup wizard to set it up. I only have one external extension which I installed with composer via these commands:

    composer require magepal/magento2-gmailsmtpapp
    php bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
    php bin/magento setup:upgrade

My `composer config repositories` output:

     {"0":{"type":"composer","url":"https:\/\/repo.magento.com\/"},"packagist":{"type":"composer","url":"https:\/\/packagist.org"}}

### Steps to reproduce

When I try to do a "System Upgrade" (with "Other Components" set to "No") from the admin panel I get this error:

    Check Component Dependency
    
    We found conflicting component dependencies. Hide detail
    
    Command "update" failed: Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.
    
    Problem 1
    - The requested package magepal/magento2-gmailsmtpapp could not be found in any version, there may be a typo in the package name.
    
    Potential causes:
    - A typo in the package name
    - The package is not available in a stable-enough version according to your minimum-stability setting
    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
    
    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
    
    For additional assistance, see component dependency help .

In my `composer.json` these are my dependencies:

    "require": {
        "magento/product-community-edition": "2.1.6",
        "composer/composer": "@alpha",
        "magepal/magento2-gmailsmtpapp": "^1.4"
    },

### Expected result

1. The system should upgrade to 2.1.7

### Actual result

1. Screenshot:
![image](https://cloud.githubusercontent.com/assets/2086355/26653167/e46dc0d8-4617-11e7-8c72-7aafd1b73eb3.png)

Doing a `composer upgrade --dry-run` shows no errors, which leads me to believe this is a platform issue.  I'm required to hand the system upgrade to someone with no knowledge or access to the terminal so running `composer upgrade` isn't a choice for me here.

**Comment by SpikeSpade** [comment]
First of all,
The error states it can not find the package magepal/magento2-gmailsmtpapp.
Add this as a repository: https://github.com/magepal/magento2-gmailsmtpapp

Like this:
{"type": "git", "url": "https://github.com/magepal/magento2-gmailsmtpapp"}


Second
Since you have this line:
"magento/product-community-edition": "2.1.6",
If won't upgrade, but stick with v 2.1.6.

You can either change it to 2.1.7 (then it will update to 2.1.7) or change it to 2.1.* (then it will update to all future 2.1.x versions. 

I recommend changing it to 2.1.7. Because then you won't have any unsuspected updates, when installing a new extension for example.

I hope this helps :)

**Comment by charmeleon-zz** [comment]
@SpikeSpade Thanks for your help, but I think I must amend my bug report: I originally had checked "Other Components: Yes" and that's when it failed the first time; all subsequent attempts failed with the same error. Just now I decided to flush the cache and try again, and the readiness check passed.

So the failure was cached for me, but flushing the cache got me through and I can now upgrade fine from the admin panel. Still very tricky.

**Comment by dmitriyprime** [comment]
Hi, @charmeleon . Thanks for the feedback. Unfortunately, I could not reproduce the issue. Is this issue actual for you or we can close it?

**Comment by charmeleon-zz** [comment]
@dmitriyprime I've moved past it, feel free to close it
