### ISSUE TITLE
Frontend customer order list doesn't page

### ISSUE THREAD

**Issue by Silarn** [magento/magento2#9816]
### Preconditions
Magento 2.1.6 and earlier
PHP version is irrelevant

### Steps to reproduce
Place enough orders to surpass the lower page limit for customer orders.
In other words, you need a customer account with at least 11 orders.

Log into the account and view the order list.

### Expected result
The orders should be paged based on the pager limit

### Actual result
All orders are shown and the pager displays [total order number]/[page limit] orders

After digging into the issue, this problem is due to an oversight in the Magento\Sales\Block\Order\History class in the getOrders function.

```php
    /**
     * @return bool|\Magento\Sales\Model\ResourceModel\Order\Collection
     */
    public function getOrders()
    {
        if (!($customerId = $this->_customerSession->getCustomerId())) {
            return false;
        }
        if (!$this->orders) {
            $this->orders = $this->getOrderCollectionFactory()->create($customerId)->addFieldToSelect(
                '*'
            )->addFieldToFilter(
                'status',
                ['in' => $this->_orderConfig->getVisibleOnFrontStatuses()]
            )->setOrder(
                'created_at',
                'desc'
            );
        }
        return $this->orders;
    }
```

This should include setting the current page based on the default or current params.

```php
    /**
     * @return bool|\Magento\Sales\Model\ResourceModel\Order\Collection
     */
    public function getOrders()
    {
        if (!($customerId = $this->_customerSession->getCustomerId())) {
            return false;
        }
        if (!$this->orders) {
            $this->orders = $this->getOrderCollectionFactory()->create($customerId)->addFieldToSelect(
                '*'
            )->addFieldToFilter(
                'status',
                ['in' => $this->_orderConfig->getVisibleOnFrontStatuses()]
            )->setOrder(
                'created_at',
                'desc'
            );
        }

        $page = $this->getRequest()->getParam('p') ?: 1;
        $num = $this->getRequest()->getParam('limit') ?: 10;
        $this->orders->setPage($page, $num);

        return $this->orders;
    }
```

**Comment by YevSent** [comment]
Hi, @Silarn, this issue already fixed on the develop branch (internal ticket `MAGETWO-56776`). The problem not in the order's block but in the CSS styles.

**Comment by Silarn** [comment]
Actually, the problem I was referencing ended up being caused by a third-party module plugin. So I'm going to close this ticket.
