### ISSUE TITLE
Unable to find product with slash character in name

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#9817]
### Preconditions
Magento 2.1.6

### Steps to reproduce
1. Create product with slash in name (e.g. "Concealer Circle\Delete") and remember SKU
2. Try to search it through admin panel by filtering by name (unsuccessful)
3. Try to search it through admin panel by filtering by SKU (successful)
4. Try to search it through API (by name) (successful)

### Expected result
Result with searched item

### Actual result
Item not found by name but found by SKU

##### Filter by name:
<img width="1341" alt="screen shot 2017-05-31 at 4 50 58 pm" src="https://cloud.githubusercontent.com/assets/24477165/26653600/9199751e-4621-11e7-8e4b-0f3d29c30095.png">

##### Filter by SKU:
<img width="1337" alt="screen shot 2017-05-31 at 4 50 37 pm" src="https://cloud.githubusercontent.com/assets/24477165/26653605/95e75f64-4621-11e7-894f-47bfe2f17b99.png">

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70102 was created.

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.
We've created internal ticket(s) MAGETWO-70102 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @oroskodias

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
