### ISSUE TITLE
Enabling Redis after upgrading to 2.1.7 All custom attributes for Configurable products deleted!

### ISSUE THREAD

**Issue by rbur0425** [magento/magento2#9825]
Had Magento 2.1.6 installed and had 2 configurable products with 2 custom attributes. I upgraded via the command line using composer and following the guide. I then edited the env.php file to enable Redis for caching default and session. I logged back into the Admin section and when I clicked Products > Catalog I was receiving an error. 

a:4:{i:0;s:62:"Attribute with attributeCode "white_box_sizes" does not exist.";i:1;s:8771:"#0 <root>/vendor/magento/module-eav/Model/AttributeRepository.php(143): Magento\Eav\Model\AttributeRepository->get('catalog_product', 'white_box_sizes')

I was able to export all of the products and come to find out none of them had the attribute attached to them any more. However, when I remove the Redis config from the env.php all the products are associated again.

**Comment by veloraven** [comment]
@rbur0425  thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
