### ISSUE TITLE
Product editing Issue and Editor Issue

### ISSUE THREAD

**Issue by jobsmartdesigner** [magento/magento2#9826]
I am having two issues. Using Version 2.1.6 Magento.

1. I am unable to edit the product descriptions when I tell it to save it doesn't.The map you see on the example I've deleted that and added text and video and saved it and cleared the cache and flushed Magento cache and the map is still appearing. The theme developer that is helping me with some theme issues says that its a megento2 issue (ex: http://www.wonderworkstoys.com/store/bright-bugz-evolution.html#product.info.description) and they are all showing up with html tags showing (ex: http://www.wonderworkstoys.com/store/tangle-sport-matrix-nightball-football.html)

2. The editor for pages and products only shows up when using Google chrome and nothing else. Is there a way to fix this issue be not all people use Chrome, I use Firefox a lot and my boss uses explorer. So I am not sure why it won't work

Please help I would really appreciate it a lot

And if any one can point me in a direction of a good tutorial for Magento and how it works including blocks etc that would be great, I have yet to find one that explains everything easily

**Comment by veloraven** [comment]
@jobsmartdesigner thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please also create separate GitHub issue for each issue.
