### ISSUE TITLE
merging does not work without bundling

### ISSUE THREAD

**Issue by steros** [magento/magento2#9827]
### Preconditions
1. Magento 2.1.5 - production mode
2. activate Javascript merging
3. activate Javascript minifying
4. deactivate Javascript bundling

### Steps to reproduce
1. load (i.e.) the product detail page

### Expected result
1. see that a merged javascript file is loaded

### Actual result
1. see that there are +100 javascript files loaded

If I activate bundling I get just one merged javascript file and one or two additional files.

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70154 was created.

**Comment by Igloczek** [comment]
It's not a bug, that's how RequireJS load modules when bundling is disabled. 

Merging in Magento is related only to scripts added though layout files (i.e. libs loaded synchronously), almost all of those 100+ files are loaded from templates using RequireJS AMD modules.

If you want to reduce the number of requests, you have to enable bundling.
...but it doesn't work so good, it will slow down your page.

**Comment by steros** [comment]
Okay thanks for clarification.
