### ISSUE TITLE
Configurable Product with over 125 options breaks indexer

### ISSUE THREAD

**Issue by rbur0425** [magento/magento2#9829]
Magento version: 2.1.7

I have a configurable product that has 2 custom attributes, size and quantity. The size attribute has over 125 options and the quantity attribute has 2 options. When I go to reindex I get the following error Fatal error: Maximum function nesting level of '256' reached, aborting! in <root>/vendor/magento/framework/Session/SaveHandler.php on line 80

I have more options I need to add, how do I raise the limit?

**Comment by korostii** [comment]
That's actually a limitation imposed by the environment you use (namely, php.ini settings).
Try increasing xdebug.max_nesting_level as a workaround. Disabling XDebug completely might do the trick as well.

See more info here, for example: https://stackoverflow.com/questions/8656089/solution-for-fatal-error-maximum-function-nesting-level-of-100-reached-abor

**Comment by rbur0425** [comment]
Issue was resolved by setting xdebug.max_nesting_level=1024 in php.ini file
