### ISSUE TITLE
[Question] Magento 2 or Magento 1.9.1?

### ISSUE THREAD

**Issue by ftbastler** [magento/magento2#983]
Hey,

I am going to create a new shop from scratch with Magento. Which version of Magento should I use/would you recommend (Magento 2 or 1.x)? Is Magento 2 already that stable to be used in a productive shop or how long will it take? I'm planning to setup the shop in the next 1-2 months.

Another question: If I'm going for Magento 1.9.1, can I update the webshop to version 2 later? Will I have to buy a new theme/new extensions then? How much work will that take?

Thanks for your answers! :)

**Comment by choukalos** [comment]
Magento 2 won't hit GA until Q4 of this year; I'd recommend setting up your store now on Magento 1.9.1 so you can use the year to build your business.

We plan on providing data migration scripts for Magento 2 so you can migrate your store from 1.9.1 to Magento 2.0

**Comment by ftbastler** [comment]
Thanks for the answer!

**Comment by gsouf** [comment]
@choukalos What's about magento 2 status now in June ? 

Is it safe to begin to work with magento 2 ?

**Comment by choukalos** [comment]
Hi @gsouf as I stated before we won't launch Magento 2 till Q4 this year.  Currently we're working on merchant features in Magento 2 - i.e. for our up coming Merchant Beta release.  Merchant Beta won't be released until Q3 so still some time before M2 is really ready for merchants to start using it.    

At this point we'd like to get our community developers to start working with the platform ( i.e. porting their extensions over to Magento 2 ) so they can provide us with feedback, bug reports, and pull requests.  That'll help us make sure Magento 2 is addressing the needs of the community and yourself.

**Comment by gsouf** [comment]
@choukalos thanks for you anwser.

What's about the migration. I have a big work to do with magento, migrating a whole current platform to magento, then developping new modules to fit the needing. It's planed for 2016. 

If I begin to work on magento1 and after a few times I will want to migrate to magento 2, I'm worried about having duplicate work to migrate to magento 2.  

In this case, do you think it's safe to begin to wor kith magento 2 ?
