### ISSUE TITLE
Null order in Magento\Sales\Block\Order\PrintShipment.php

### ISSUE THREAD

**Issue by dnadle** [magento/magento2#9830]
Viewing an order in the customer dashboard and clicking the print order link causes the following entry in httpd error_log:

PHP Fatal error: Call to a member function getRealOrderId() on null in <site root>/vendor/magento/module-sales/Block/Order/PrintShipment.php on line 58
 
### Preconditions
Magento 2.1.6

### Steps to reproduce
Log in as customer, go to Account Dashboard. Click My Orders, choose an order and click View Order, then click Print Order.

### Expected result
No error in httpd error_log.

### Actual result
The error described above is logged.

**Comment by YevSent** [comment]
Hi, @dnadle, please, provide additional details to reproduce this issue, like products in the order, shipment, etc. I've checked on Magento 2.1.6 and there are no any errors in Magento and Apache logs.

**Comment by dnadle** [comment]
I stepped through the code. The backend is trying to load the "current" order from a registry but the order is null, and this is not checked before the call to order->getRealOrderId() on line 58. The print version of the order is generated anyway and looks correct.

So, to reproduce the issue one must figure out why the order retrieved from the registry would be null. Regardless of any specific aspects of the order, calling a function on an object that could be null is bad code. It's a bug and should be fixed.

**Comment by bve-9384** [comment]
I experience the same issue, using Magento 2.1.7.
_PHP Fatal error:  Uncaught Error: Call to a member function getRealOrderId() on null in .../magento2/vendor/magento/module-sales/Block/Order/PrintShipment.php:58_

Page URL: /sales/order/print/order_id/123/
Same issue for all orders, but page still looks fine

**Comment by veloraven** [comment]
Internal ticket was created: MAGETWO-69787

**Comment by dnadle** [comment]
This has something to do with full page caching. PrintShipment::_prepareLayout() is called 4 times successfully by an execution chain renders the print version of the order correctly. But then it is called again, by a different chain for which the registry is not properly initialized and this _prepareLayout() call exits with the fatal error. I don't yet know what is triggering this second rendering, but if you disable full page caching it does not occur and there is no error message logged.

**Comment by rogyar** [comment]
This happens because of the incorrect block class definition. The https://github.com/magento/magento2/pull/11631 contains fix for the order items list. Also, it fixes the error mentioned here

**Comment by okorshenko** [comment]
The issue has been fixed in 2.1-develop branch and will be available with next patch release

**Comment by ihor-sviziev** [comment]
@engcom-backlog-nickolas I have this issue on Magento 2.2.5 when built-in Full Page Cache enabled.

I re-opened this issue. Could you re-check if you can reproduce this issue?

This issue appears when Magento sends AJAX request to backend like this (the same steps to reproduce, but just cancel print dialog and wait few seconds):
https://magento2-example.com/page_cache/block/render/order_id/1/?blocks=%5B%22sales.order.print.info%22%5D&handles=%5B%22default%22%2C%22sales_order_print%22%2C%22print%22%5D&originalRequest=%7B%22route%22%3A%22sales%22%2C%22controller%22%3A%22order%22%2C%22action%22%3A%22print%22%2C%22uri%22%3A%22%2Fsales%2Forder%2Fprint%2Forder_id%2F1%2F%22%7D&version=version_id

**Comment by magento-engcom-team** [comment]
@ihor-sviziev Internal ticket reopened. Thanks for investigation.

**Comment by sidolov** [comment]
Hi @dnadle. Thank you for your report. 
The issue has been fixed in magento/magento2#17998 by @MateuszChrapek in 2.2-develop branch
Related commit(s):
 - [9316bd0eae2acc59dcceae09d212836083e93167](https://github.com/magento/magento2/commit/9316bd0eae2acc59dcceae09d212836083e93167)
 - [aaa55287f4be6f2c210d8026b8114f60e8735258](https://github.com/magento/magento2/commit/aaa55287f4be6f2c210d8026b8114f60e8735258)

The fix will be available with the upcoming 2.2.8 release.

**Comment by slavvka** [comment]
Hi @dnadle. Thank you for your report. 
The issue has been fixed in magento/magento2#18272 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [37ff9e94589847f505925add1ed74b6c65a009e2](https://github.com/magento/magento2/commit/37ff9e94589847f505925add1ed74b6c65a009e2)

The fix will be available with the upcoming 2.3.1 release.
