### ISSUE TITLE
Magento 2 SOAP returning Malformed XML ( Spaces and enter characters before XML tag)

### ISSUE THREAD

**Issue by magento2developer** [magento/magento2#9831]
### Preconditions

1. Magento 2.1.7, but has been there for  2.1.5 and 2.1.6
2. PHP 5.6.30
3. mysql  Ver 14.14 

### Steps to reproduce
1. Add referrence to webservice in .NET
2. Call Web service
3. Error, malformed XML

### Expected result
1. XML returned should start with the "<?xml version=" tag, no spaces or enter characters before it.

### Actual result

1. XML has 2 enter characters before the "<?xml version=" tag see below:

HTTP/1.1 200 OK
Date: Fri, 02 Jun 2017 04:02:44 GMT
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: PHPSESSID=zzzzzzz; expires=Fri, 02-Jun-2017 05:02:48 GMT; Max-Age=3600; path=/; domain=example.com; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 81256
X-UA-Compatible: IE=edge
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/soap+xml; charset=utf-8

 <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://example.com/soap/default?services=catalogProductRepositoryV1">

**Comment by magento2developer** [comment]
omw, this post has stripped out the tag, but it goes before the <env tag has an enter and a space before it.

**Comment by magento2developer** [comment]
This was a space at the beginning of a custom module just before the <?php tag. 
for reference, I found it pretty easily by logging the loops in 
vendor/composer/autoload_real.php and  app/etc/NonComposerComponentRegistration.php

**Comment by korostii** [comment]
So the issue was caused by a customization?
Please kindly close the issue if it is resolved for you.
