### ISSUE TITLE
Upgraded to 2.1.7 - color/visual & text swatches replaced with dropdowns for configurable products

### ISSUE THREAD

**Issue by richardmlaws** [magento/magento2#9832]
I upgraded from 2.1.4 to 2.1.7 - when I looked on the product page for my configurable products, all color swatches and text swatches had been replaced with drop downs instead.

However on the category pages the color swatches and text swatches appeared fine on both the product list and layered navigation

**Comment by heldchen** [comment]
same here

**Comment by antboiko** [comment]
Hi @richardmlaws. Can you please provide detailed steps to reproduce this issue?

**Comment by richardmlaws** [comment]
Hi @antboiko - I upgraded from 2.1.4 via command line using steps in http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html

That was it really - as soon as I checked my products, the swatches had been turned in to drop downs.

The drop downs were empty so I tried a reindex/flush and that populated the drop downs (but I didnt want drop downs) - I reverted back to 2.1.4

**Comment by southerncomputer** [comment]
Check for javascript errors only appearing in production mode (when you php bin/magento setup:static-content:deploy -j 1 )! If you find odd missing files - like quote.min.js show up, it is because of the user of relative paths in require code all over the codebase!
or try this patch https://github.com/magento/magento2/commit/b9ddac74c71df89e920c8f62fa59dbf3b0ddc083

**Comment by heldchen** [comment]
@richardmlaws  if you have extended `Magento\Swatches\Block\Product\Renderer\Configurable::getRendererTemplate()` make sure you change `$this->isProductHasSwatchAttribute` to `$this->isProductHasSwatchAttribute()`, the property was converted into a function in 2.1.6

**Comment by veloraven** [comment]
@richardmlaws , @heldchen ,
we were not able to reproduce this issue.
Please provide more information about your Magento installation, including the versions of PHP and MySQL you are using as well as the web server.
Please also specify if you have any extensions which can affect swatches functionality.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by korostii** [comment]
For anyone still running into this issue: it might be a duplicate of #9923, please see [this comment](https://github.com/magento/magento2/issues/9923#issuecomment-311888335) for a possible workaround, hope it helps you.

**Comment by corliving-web** [comment]
@heldchen your suggestion solved it for us.  We bypassed 2.1.6 and so didn't see this issue then.  Thanks!
https://github.com/magento/magento2/issues/9832#issuecomment-306027785

**Comment by csbrou** [comment]
@heldchen you suggestion also solved the problem for us, although the property was being used in a third party plugin.

**Comment by OZZlE** [comment]
It's fixed in 2.1.8 but if you don't want to upgrade then you can patch this in: https://github.com/magento/magento2/commit/b84fe279c2306d74441354899900dc9f124437b6
