### ISSUE TITLE
Configurable products options are not showing after upgrade 2.1.7

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#9833]
Configurable products options are not showing after upgrade 2.1.7

### Preconditions
Linux 2.6.32-696.1.1.el6.x86_64 #1 SMP
PHP Version 7.0.19
MySql mysqlnd 5.0.12-dev
### Steps to Reproduce
Upgrade 2.1.4 to 2.1.7
Run update command
Run upgrade command
run deploy command
### Expected Result
Configurable products options displayed correctly
### Actual Result
1. Before upgrade size option in confugurable is dropdown as per admin setting.
2. After upgrade size dropdown changed to swatches (it was working fine in old version).
Also it is working fine when I change "vendor/module-swatches" directory to old version "vendor/module-swatches"

**Comment by antboiko** [comment]
Hi @aasim110. Can you please provide the detailed steps to reproduce this issue?

**Comment by rbur0425** [comment]
I had similar problem. Try disabling Redis for cache if you have it enabled.

**Comment by southerncomputer** [comment]
try this patch - change default_jobs_amount = 1;

https://github.com/magento/magento2/commit/b9ddac74c71df89e920c8f62fa59dbf3b0ddc083

**Comment by aasim110** [comment]
@rbur0425 how to disable Redis for cache ? I have never enabled this.

**Comment by aasim110** [comment]
@antboiko there are two attributes color and size, I have select "Catalog Input Type for Store Owner" to "Dropdown" for both attributes and it was working fine in before version, but after upgrade both attributes are showing "Swatches" on front end.

**Comment by veloraven** [comment]
@aasim110 thank you for your feedback.
Please format this issue according to [template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines), with exact steps to reproduce, actual result and expected result.
Please also provide additional information:
* from what version did you upgrade?
* exact steps you did  during upgrade
* information about your environment: OS, versions of PHP, MySQL, web-server.

**Comment by aasim110** [comment]
Upgrade 2.1.4 to 2.1.7
1. Before upgrade size option in confugurable is dropdown as per admin setting.
2. After upgrade size dropdown changed to swatches (it was working fine in old version).
3. Also it is working fine when I change "vendor/module-swatches" directory to old version "vendor/module-swatches" 

For upgrade we are using following steps for upgrade
1. Rune update command
2. Run upgrade command
3. run deploy command
 
We are using 
1. Linux 2.6.32-696.1.1.el6.x86_64 #1 SMP
2. PHP Version 7.0.19
3. MySql mysqlnd 5.0.12-dev

**Comment by rafaelrocha007** [comment]
Hi!
I'm new to Magento, and how could I disable Reddis or apply that `default_jobs_amount = 1` fix?
Thanks in advance!

**Comment by aasim110** [comment]
Temperory solution is replace old version default swatch module "vendor/magento/module-swatches" with new one.
it is working fine for me.

**Comment by btwq** [comment]
Hi @aasim110 do you mean, in order to fix this issue, you have replaced the NEW module (that comes with the patch) with the OLD one?

**Comment by aasim110** [comment]
@btwq  Yes exactly!!!

**Comment by mindaji** [comment]
@aasim110 Temperory solution is replace old version default swatch module "vendor/magento/module-swatches" with new one.

I have hit the exact same problem. Could you let me know how to replace it with the new one? Where is the new one?

**Comment by aasim110** [comment]
@mindaji get old module and replace with new one
for example : you had 2.1.5 version before upgrade(2.1.7), then copy files from 2.1.5 "vendor/magento/module-swatches" to latest version files
Note : don't replace files, first remove all files from 2.1.7 and then add 2.1.5 module files.

**Comment by mindaji** [comment]
Dear Sir or Madam:

Thanks a lot!

**Comment by magento-engcom-team** [comment]
@aasim110, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by aasim110** [comment]
@mindaji @btwq @rbur0425 I have fixed issue after Flushing  **"eav_attribute_option_swatch"** table entries corresponding to the attribute (all of them, not just specific to single product or option).
I have tried this on 2.1.7, 2.1.9 and 2.2.1 and its working fine for all.

**Comment by mindaji** [comment]
aasim110: Could you let us know how to flush "eav_attribute_option_swatch"?

**Comment by jmtakahashi** [comment]
@aasim110 could you clarify "flushing 'eav_attribute_option_swatch' table entries corresponding to the attribute (all of them,not just specific to single product or option)".  Did truncate the entire table or only certain columns/values?

**Comment by aasim110** [comment]
@jmtakahashi truncate the entire table except image entries.
