### ISSUE TITLE
update custom option value of products from the cart page

### ISSUE THREAD

**Issue by bouzakherOR** [magento/magento2#9836]
i want to add my two custom option and have posibility to change their value from the shopping cart page.
I added my two custom option (two Checkbox : Accidental Warranty and installation ) to all my products , i can edit them on product page but in shopping cart page it's just listed. i want to add the tow checkbox on the cart page.
an idea how to do this please 
![screenshot from 2017-06-01 11-10-05](https://cloud.githubusercontent.com/assets/12237295/26733609/a45e4a26-47bb-11e7-8c2a-75f6861b8d30.png)
?

**Comment by korostii** [comment]
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
