### ISSUE TITLE
Paypal link error of Transaction ID link

### ISSUE THREAD

**Issue by sennin32** [magento/magento2#9840]
Paypal works fine.
But when in order detail page or transactions page the Transaction ID link will become "www..paypal.com/xxxxxxxxxxxx".
One more extra dot shows up.

### Preconditions

1. Magento 2.1.6 (also happens in previous version)
2. php56

### Steps to reproduce

1. Update from 2.1.2/3/4 maybe.
2. no error shows up, I tried to trace the code, but don't know much about php, can not spot what cause issue.
3. use porto theme

### Expected result

1. click Transaction ID and link to correct paypal transaction.

### Actual result

1. the paypal link has one extra dot like "www..paypal.com/xxxxxxxxxxxx".

**Comment by korostii** [comment]
Confirmed on Magento 2.1.5 CE: http://take.ms/rmuVI

**Comment by sennin32** [comment]
Not sure why I can not find this issue while google it.
This should be an annoy issue.

**Comment by YevSent** [comment]
This issue already fixed on develop branch (internal ticket `MAGETWO-63406`) https://github.com/magento/magento2/commit/09ac7614c46ad4c560625b2354eec208d7b76482#diff-0d7cffeb8920eee50074f81764bd1c8a.
