### ISSUE TITLE
Minicart is empty after adding products and js errors

### ISSUE THREAD

**Issue by whatsnow** [magento/magento2#9843]
When adding items to the cart the following js errors appearing in the console:
Uncaught TypeError: Unable to process binding "foreach: function (){return $parent.getRegion($parent.getItemRenderer(item.product_type)) }"
Message: Cannot read property 'simple' of undefined
    at UiClass.getItemRenderer (minicart.js:127)
    at foreach (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:93)
    at knockout.js:3889
    at Object.init (knockout.js:5023)
    at init (knockout.js:3914)
    at knockout.js:2989
    at Object.ignore (knockout.js:1249)
    at knockout.js:2988
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)
getItemRenderer @ minicart.js:127
foreach @ VM84350:3
(anonymous) @ knockout.js:3889
init @ knockout.js:5023
init @ knockout.js:3914
(anonymous) @ knockout.js:2989
ignore @ knockout.js:1249
(anonymous) @ knockout.js:2988
arrayForEach @ knockout.js:151
applyBindingsToNodeInternal @ knockout.js:2974
applyBindingsToNodeAndDescendantsInternal @ knockout.js:2854
ko.applyBindings @ knockout.js:3065
_super @ wrapper.js:73
applyBindings @ bound-nodes.js:116
(anonymous) @ wrapper.js:78
(anonymous) @ knockout.js:4862
invokeForEachNodeInContinuousRange @ knockout.js:4813
activateBindingsOnContinuousNodeArray @ knockout.js:4860
activateBindingsCallback @ knockout.js:4986
ko.utils.setDomNodeChildrenFromArrayMapping @ knockout.js:5344
ignore @ knockout.js:1249
ko.dependentObservable.disposeWhenNodeIsRemoved @ knockout.js:5007
evaluateImmediate @ knockout.js:1737
ko.computed.ko.dependentObservable @ knockout.js:1946
ko.renderTemplateForEach @ knockout.js:4995
update @ knockout.js:5072
update @ knockout.js:3917
ko.dependentObservable.disposeWhenNodeIsRemoved @ knockout.js:3004
evaluateImmediate @ knockout.js:1737
evaluatePossiblyAsync @ knockout.js:1677
notifySubscribers @ knockout.js:1103
observable.valueHasMutated @ knockout.js:1300
observable @ knockout.js:1285
(anonymous) @ minicart.js:141
(anonymous) @ underscore.js:73
_.each._.forEach @ underscore.js:150
update @ minicart.js:137
(anonymous) @ minicart.js:93
notifySubscribers @ knockout.js:1103
observable.valueHasMutated @ knockout.js:1300
observable @ knockout.js:1285
notify @ customer-data.js:151
(anonymous) @ customer-data.js:166
_.each._.forEach @ underscore.js:150
update @ customer-data.js:161
(anonymous) @ customer-data.js:304
fire @ jquery.js:3232
fireWith @ jquery.js:3362
done @ jquery.js:9840
callback @ jquery.js:10311
jquery.js:10254 XHR finished loading: GET "http://localhost/customer/section/load/?sections=cart%2Cmessages&update_section_id=false&_=1496504808890".
send @ jquery.js:10254
ajax @ jquery.js:9738
jQuery.(anonymous function) @ jquery.js:9890
getJSON @ jquery.js:9871
getFromServer @ customer-data.js:85
reload @ customer-data.js:303
init @ customer-data.js:205
Magento_Customer/js/customer-data @ customer-data.js:336
(anonymous) @ main.js:30
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
callGetModule @ require.js:1170
completeLoad @ require.js:1544
onScriptLoad @ require.js:1671
knockout.js:3012 Uncaught TypeError: Unable to process binding "foreach: function (){return $parent.getRegion($parent.getItemRenderer(item.product_type)) }"
Message: Cannot read property 'simple' of undefined
    at UiClass.getItemRenderer (minicart.js:127)
    at foreach (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:93)
    at knockout.js:3889
    at Object.init (knockout.js:5023)
    at init (knockout.js:3914)
    at knockout.js:2989
    at Object.ignore (knockout.js:1249)
    at knockout.js:2988
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)
getItemRenderer @ minicart.js:127
foreach @ VM84350:3
(anonymous) @ knockout.js:3889
init @ knockout.js:5023
init @ knockout.js:3914
(anonymous) @ knockout.js:2989
ignore @ knockout.js:1249
(anonymous) @ knockout.js:2988
arrayForEach @ knockout.js:151
applyBindingsToNodeInternal @ knockout.js:2974
applyBindingsToNodeAndDescendantsInternal @ knockout.js:2854
ko.applyBindings @ knockout.js:3065
_super @ wrapper.js:73
applyBindings @ bound-nodes.js:116
(anonymous) @ wrapper.js:78
(anonymous) @ knockout.js:4862
invokeForEachNodeInContinuousRange @ knockout.js:4813
activateBindingsOnContinuousNodeArray @ knockout.js:4860
activateBindingsCallback @ knockout.js:4986
ko.utils.setDomNodeChildrenFromArrayMapping @ knockout.js:5344
ignore @ knockout.js:1249
ko.dependentObservable.disposeWhenNodeIsRemoved @ knockout.js:5007
evaluateImmediate @ knockout.js:1737
ko.computed.ko.dependentObservable @ knockout.js:1946
ko.renderTemplateForEach @ knockout.js:4995
update @ knockout.js:5072
update @ knockout.js:3917
ko.dependentObservable.disposeWhenNodeIsRemoved @ knockout.js:3004
evaluateImmediate @ knockout.js:1737
evaluatePossiblyAsync @ knockout.js:1677
notifySubscribers @ knockout.js:1103
observable.valueHasMutated @ knockout.js:1300
observable @ knockout.js:1285
(anonymous) @ minicart.js:141
(anonymous) @ underscore.js:73
_.each._.forEach @ underscore.js:150
update @ minicart.js:137
(anonymous) @ minicart.js:93
notifySubscribers @ knockout.js:1103
observable.valueHasMutated @ knockout.js:1300
observable @ knockout.js:1285
notify @ customer-data.js:151
(anonymous) @ customer-data.js:166
_.each._.forEach @ underscore.js:150
update @ customer-data.js:161
(anonymous) @ customer-data.js:304
fire @ jquery.js:3232
fireWith @ jquery.js:3362
done @ jquery.js:9840
callback @ jquery.js:10311

### Preconditions
1. Magento : 2.1.7
2. PHP 5.6.30
3. MySQL server 5.6

### Steps to reproduce
Adding product tot the cart

### Expected result
I should see the items that are added in the cart
### Actual result
I see only the following text: 1 item, cart subtotaal and go to checkout 

I cant find out why this happens, any one?

**Comment by southerncomputer** [comment]
try setting up a hostname. fully like localhost.com or dyndns.org ! Used to be a problem with single level domain cookies like localhost

**Comment by whatsnow** [comment]
i use a full domain, i use localhost because tot protect my unique idea

**Comment by veloraven** [comment]
@whatsnow thank you for your report.
Please provide some additional information:
* product of what type do you add?
* do you add product as a guest or registered customer?
* was it clear Magento install or upgrade from some previous version?
It also looks like from your log that region field is absent on the shopping cart page however it is supposed to be there. Did you turn it off in some way?

**Comment by whatsnow** [comment]
- product of what type do you add? simple products
- do you add product as a guest or registered customer? both
- was it clear Magento install or upgrade from some previous version? clean install
- It also looks like from your log that region field is absent on the shopping cart page however it is supposed to be there. Did you turn it off in some way?  No i didnt

**Comment by veloraven** [comment]
@whatsnow thank you for your response.
Could you please provide a screenshot?
And do you use any custom extensions or custom theme?
We were not able to reproduce this issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
