### ISSUE TITLE
Empty Cart

### ISSUE THREAD

**Issue by edenreich** [magento/magento2#9847]
### Preconditions

1. XAMPP(Windows 10)
2. PHP 7.0
3. Magento 2 CE

### Steps to reproduce

1. make sure you are on developer mode.
2. Add some products to the cart
3. Go to checkout
4. Dont complete the checkout, go back to home page, and then back to cart.

### Expected result

1. See the ordered products inside the cart, not only on the right side icon.

### Actual result

1. products appears only on the right side icon, but when you go to checkout the cart seems to be empty. do note im using 127.0.0.1 and the cookie is set to a long period of time.

![11](https://cloud.githubusercontent.com/assets/16985712/26763957/dab718c0-495d-11e7-813a-68785b28ee2b.jpg)

to get rid of it, I had to delete a product from the top right icon, then add another product and procceed to checkout lastpage then instead of only 1 products I get the rest of the products I already added before(they appear they appears from nowhere only on the last page of the checkout).

**Comment by abhilashv1985** [comment]
I have this issue in 2.1.7 as well. Add to cart adds a product to the minicart but the checkout page shows empty.

**Comment by veloraven** [comment]
@edenreich thank you for your report.
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
