### ISSUE TITLE
Duplicating Configurable Product With Related Products Not Working Magento 2.1.7 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9851]
### Preconditions

1. Magento 2.1.7
2. PHP 5.6

### Steps to reproduce

Go to admin > products > catalog
Choose for a product that has related products
Click on Save & Duplicate
Replace SKU, TITLE, URL, CONTENT, IMAGE
Remove the currently associated products in the configurable section
Save
Create new related simple products
Save

### Expected result
1. The product should show up on the front end.

### Actual result

1. It does not show up.
Tested duplicating simple products and it works fine. 

Tested deleting duplicated configurable product and creating new simple product, re-associating the simple products to it and it worked fine. 

Tested creating associated simple products of duplicated simple product (turning the duplicated simple product into a configurable) and it works fine. 

It is only when trying to Copy and Save a configurable product with related simple products that the duplication fails.

**Comment by veloraven** [comment]
@rosandrest thank you for your report.
Please clarify several points.
1. Do you mean variations of configurable product at step 7? As related product has different meaning in Magento. 
2. What product do you mean in expected and actual result? Are you waiting to see configurable product or its variation? Please specify it directly.
3. Is this product 'In Stock' or 'Out of Stock'? If you are talking about configurable product is at least one of its variations 'in stock'?

**Comment by ghost** [comment]
1. To clarify, the duplicated configurable product has variations that are related to it so I delete those in step 5. I create new variations in Step 7.
2. I expect to see my new duplicated product with it's new variations that I created in step 7 to show up.
3. The product is in stock as are all it's variations that are associated with it. I have double checked to see that they are products in the store. I have also reindexed.

To note I have tested this on many products. If I remove the variations and then save and duplicate it works fine. It is only when there are variations that it does not duplicate and allow for new variations to be created.

**Comment by smoskaluk** [comment]
Internal ticket created MAGETWO-69738

**Comment by keyurshah070** [comment]
Started investing @okorshenko

**Comment by keyurshah070** [comment]
It seems like I found the problem, could you please assign it to me so I can make a pull request @okobchenko @ishakhsuvarov

**Comment by sdzhepa** [comment]
The issue should be re-verified and Confirmed is it still exists in 2.3 and 2.2.
If no issue should be closed because of the internal Magento team investigated and closed all related internal Jira tickets with resolution `Won't Fix` and comment:
>  Closing this issue as "Won't Fix" since we are not going to backport any functional fixes into 2.1.x release line any more and only the security fixes will be supported.

**Comment by AlexWorking** [comment]
@vinayshah You reopened the issue without comment. Please tell whether it was done by accident. If it was not what is the reason for reopening. Thank You.

**Comment by AlexWorking** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by PascalBrouwers** [comment]
Still does not work. Duplicating configurable product creates a new product with the old simples related to it instead of also duplicating the related simples.
