### ISSUE TITLE
"Use Categories Path for Product URLs" configuration does not work correct

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#9863]
"Use Categories Path for Product URLs" configuration does not work.

### Preconditions
Magento 2.1.6
Php 7.0.18
1. Go to Admin >> Stores >> Configuration >> Catalog >> Catalog
2. Open "SEO" section
3. Change "Use Categories Path for Product URLs" to "No"
4. Flush all magento cache

### Steps to reproduce
1. Navigate to magento frontend
2. Go to any category
3. Go to any product page

### Expected result
1. Product URL should contains only product path, category path should not be in URL

### Actual result
1. Product URL is folliwing http://<domain>/<category_page>/<product_path>.html

**Comment by Stas94** [comment]
@ihor-sviziev I cannot reproduce this issue. It was a clean installation or an upgrade?

**Comment by ihor-sviziev** [comment]
I I mentioned in my PR, this issue reproducing for me after migration from m1, so it might be an issue in m1 that moved to m2 DB. I'm closing this task as I can't provide steps to reproduce.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69748

**Comment by leegold** [comment]
For me I couldn't replicate the issue above on 2.2.6, but I landed here by replicating (and then treating) the symptoms described.

The setting "Stores > Configuration > Catalog > Catalog > Search Engine Optimization > Use Categories Path for Product URLs" only generates aliases for Categories of which the product is directly assigned to, and will not generate aliases for products that are only members of categories via the Category setting "Is Anchor".

For example, the category tree below:

-> Appliances
--> Kitchen
---> Toasters

You might set "Appliances" and "Kitchen" to both be Anchor Categories, and only assign the product to the Toasters category, and let "Is Anchor" automatically define your Toasters are also within both "Kitchen" and "Appliances".

For me this resulted in my Product URLs not getting Category Paths for the categories "Appliances" and "Kitchen", but getting Category Paths for the Product URLs auto-aliased for the "Toasters" path.

Hope someone finds this useful.

**Comment by Webroju** [comment]
I have the same problem after migration from Magento1 to Magento2. In Magento 1 it works as expected, but in Magento 2.2.7 I have in the same category in one product list row: products with no category path, products with a category path only the first level and products with a deeper category path it is very strange
