### ISSUE TITLE
validation does not prevent required field to be NULL

### ISSUE THREAD

**Issue by steros** [magento/magento2#9866]
### Preconditions
1. Magento 2.1.5
2. follow this documentation page: http://devdocs.magento.com/guides/v2.1/howdoi/checkout/checkout_new_field.html
3. set added field to validation required = true

### Steps to reproduce
1. set shop to production mode
2. minify and merge javascript
2. have customers order

### Expected result
1. all customers have to enter your field as it is required

### Actual result
1. more than 30% of all orders can leave the field empty in some way (saved with NULL to the database)

**Comment by steros** [comment]
I found out that I didn't set the field to nullable = true.
So I changed that to nullable = false.
Now there are still 30% of entries that are "null" but now they end up as "0000-00-00" as this is the default value.
Some process doesn't prevent that the field can be not set by the user...

**Comment by steros** [comment]
I can further narrow down the issue:

The problem is with returning customers. If a customer saves an address prior to adding a new field that is required. Upon making a new order he will get to the shipping address step and is able to still choose that old address. Even though this address does not have the new field filled out.
When choosing that address and placing an order the field will be saved with "0000-00-00" (default value) if not nullable or "NULL" if nullable.

If a field is required at the shipping step it should check whether that field is filled or NULL/default and prevent the user to choose that address unless edited.

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.
We've created internal ticket(s) MAGETWO-80466 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @steros

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@steros thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
