### ISSUE TITLE
PHP Fatal error Uncaught Error Call to a member function get() on boolean in

### ISSUE THREAD

**Issue by Bkrishnach** [magento/magento2#9867]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment]
Please provide more details about your issue.

**Comment by Bkrishnach** [comment]
tack trace:
#0 /usr/share/php/PHPUnit/Util/XML.php(225): Magento\Mtf\System\Isolation\Driver\Base->__construct()
#1 /usr/share/php/PHPUnit/Util/Configuration.php(312): PHPUnit_Util_XML::xmlToVariable(Object(DOMElement))
#2 /usr/share/php/PHPUnit/TextUI/TestRunner.php(802): PHPUnit_Util_Configuration->getListenerConfiguration()
#3 /usr/share/php/PHPUnit/TextUI/TestRunner.php(153): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#4 /usr/share/php/PHPUnit/TextUI/Command.php(155): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#5 /usr/share/php/PHPUnit/TextUI/Command.php(106): PHPUnit_TextUI_Command->run(Array, true)
#6 /usr/bin/phpunit(29): PHPUnit_TextUI_Command::main()
#7 {main}
  thrown in /var/www/magento/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/System/Isolation/Driver/Base.php on line 29
