### ISSUE TITLE
 PHPUnit_TextUI_Command::main() #7 {main}   thrown in /var/www/magento/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/System/Isolation/Driver/Base.php on line 29

### ISSUE THREAD

**Issue by Bkrishnach** [magento/magento2#9868]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@Bkrishnach please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
