### ISSUE TITLE
datetime type product attribute showing current date

### ISSUE THREAD

**Issue by pradeep38mail** [magento/magento2#9869]
### Preconditions

1.  Magento 2.1.6, PHP 7.0.10, MYSQL 5.7.14
2. 

### Steps to reproduce

1. Create a date type product attribute 
2. assign that product to the required attribute set
3. you can edit the attribute value in the product edit.
4. create a new product and simply not assign any value to this attribute.
5. save product.

### Expected result

1. in the grid and in product edit if you see that attribute value should show Blank.

### Actual result

1. In the product edit it is showing Blank value.
2. In the product grid, if you see the product attribute it is showing current date time.

![image](https://user-images.githubusercontent.com/23617777/26878448-26dbecfe-4bab-11e7-9a8e-7c5591b57d71.png)
![image](https://user-images.githubusercontent.com/23617777/26878484-3eff7594-4bab-11e7-89ac-cb6e9728085c.png)
![image](https://user-images.githubusercontent.com/23617777/26878549-865016d8-4bab-11e7-8799-c770e80486ca.png)

**Comment by Andrii-Deineha** [comment]
@pradeep38mail , Thanks for reporting this issue. Internal ticket was created MAGETWO-70175.

**Comment by pradeep38mail** [comment]
Hi,
Thanks for considering it, Looking forward for resolution of this issue.

Thanks

**Comment by magento-engcom-team** [comment]
@pradeep38mail, thank you for your report.
We've created internal ticket(s) MAGETWO-70175 to track progress on the issue.

**Comment by enriquei4** [comment]
I've been workin in this issue. https://github.com/magento/magento2/pull/11636

**Comment by okorshenko** [comment]
the issue has been fixed in 2.2-develop branch and will be available in 2.2.2 release

**Comment by vrann** [comment]
#mm17es
