### ISSUE TITLE
Minicart and cart page do not stay in sync

### ISSUE THREAD

**Issue by amandarmitchell** [magento/magento2#9870]
It seems that sometimes, the contents of the cart in the minicart get out of sync with the contents of the cart when you go to the checkout/cart page. Mostly this happens in the form of the minicart showing items, while the cart page shows no items. I've received multiple reports via a client that they and their customers have experienced this, and I can confirm that I have experienced such things myself occasionally, as have other people at my company. Unfortunately I can't remember the circumstances that generated this when I saw it personally, and I cannot intentionally reproduce this issue.

### Preconditions
Magento CE 2.1.4

### Steps to reproduce
Report 1:
1. Add 2 items to cart
2. Leave website for a few minutes
3. Return to website and proceed to checkout
4. Receive "no items in cart" message, even though minicart in header still shows it contains 2 items
![noitems](https://user-images.githubusercontent.com/3641964/26884589-1b7b6124-4b6e-11e7-90ca-98c41cc18e04.png)

Report 2:
1. Sign in to customer account
2. Add items to cart
3. Go to checkout, receive "no items in cart message"
4. Go back and re-add same items to cart
5. Go to checkout, have twice as many items in cart as you intended to add (the original ones plus the ones you re-added)

### Expected result
Minicart and cart page should always show the same content, and added items should appear in both carts immediately.

### Actual result
Minicart shows items, when cart page does not. Items added to cart may only show up after a delay.

**Comment by hoektoe** [comment]
Try this in your dev environment without your customized version / theme or just a clean installation on 2.1.4 on a server. Proceed with the same steps with which you have been having a problem with. If you can replicate the issue on a clean 2.1.4 installation. Then there is a issue, else something might be "breaking" with your customization.

I did quick scenario test 1 on your site and could not replicate. Your CartSummary in header is really slow and might be the Add to Cart ajax your site has which isn't acting as expected.

**Comment by magento-engcom-team** [comment]
@amandamitchell, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by BenGlassAtlas** [comment]
I have witnessed this on most Magento 2 stores I've used and/or worked on, I struggle to replicate it though as a refresh usually resolves it.

![shopping_cart](https://user-images.githubusercontent.com/8895777/42810752-98be90d0-89b0-11e8-8efb-6e025fc739e7.jpg)
