### ISSUE TITLE
Missing image labels/roles in product gallery - always set to null

### ISSUE THREAD

**Issue by magentomaniac** [magento/magento2#9871]
### Preconditions

1. Magento EE v. 2.1.4, PHP 7.0.13-0

### Steps to reproduce

1. Add a simple product, add an image, assign a label/role to it.
2. Check the output of $block->getGalleryImagesJson() either in PHP or via console.log in JS. This is used e.g. in 
`vendor/magento/module-catalog/view/frontend/templates/product/view/gallery.phtml`  which is using `\Magento\Catalog\Block\Product\View\Gallery` block.

### Expected result

1. The JSON should contain the image labels/roles. It's set in /vendor/magento/module-catalog/Block/Product/View/Gallery.php using 
`'caption' => $image->getLabel()` so I'd expect it to contain the image labels/roles.

### Actual result

1. Currently the 'caption' is always set to null. Sample output of 
`json_encode($block->getGalleryImagesJson())`
contains:
`[{"thumb": (...) ,"caption":null,"position":"2","isMain":false}]`

**Comment by veloraven** [comment]
@magentomaniac  thank yuo for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by korostii** [comment]
Hi @veloraven 
Isn't Magento_Catalog module shared with CE?

**Comment by magentomaniac** [comment]
Thanks for your reply @veloraven. We've handled this issue internally so there's no need to escalate to EE support at this point in time.

Although I haven't confirmed this myself I believe @korostii is right and the issue will be reproducible in M2 CR version as well as this is a common module and the functionality it's related to is very much standard.

**Comment by magento-engcom-team** [comment]
Hi @magentomaniac 
Thank you for update

**Comment by lstellway** [comment]
I needed the roles added to the gallery JSON for some custom theme tweaking. I created a quick module to serve as an example of how to implement this in case anybody else needs to:

[Magento 2 Module - Add Roles to Gallery JSON](https://github.com/loganstellway/module-catalog-gallery-roles)
