### ISSUE TITLE
Magento2: REST Product API: updates reflected only on default storeview

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#9874]
### Preconditions

1. Magento 2.1.3
2. Setup Single store and that is default store. 

### Steps to reproduce

1.  Use product rest api PUT:/V1/products/<productSKU> with request body {"id":2058,"sku”:productSKU,”name":"productSKU,"attribute_set_id":19,"price":29,"status":1,"visibility":4,"type_id":"simple","created_at":"2017-06-02 16:37:27","updated_at":"2017-06-02 16:37:27","weight":0.08,"extension_attributes”:[]}
2. Response success 200 and changes are reflected on default store only.

### Expected result

1. This instance is having single store, so anything updated on default store store should be reflected on All store view in UI.
2. As i wanted it to update data for all stores, I am not providing any store details in request. But if I provide the default store view then update only default store view for the item and not reflect on other stores

### Actual result

1. Default store view reflect the price and weight value in UI while All store view doesn't show any value.
![image](https://user-images.githubusercontent.com/12096540/26917406-ce72bf2e-4c4b-11e7-8a8a-c576159e91e4.png)

2. All store view doesn't show any price or weight.
![image](https://user-images.githubusercontent.com/12096540/26917316-72cef174-4c4b-11e7-932e-472233202adf.png)

I think it to be bug as this is single store and there is no way to get the price and weight show up in all store view.

**Comment by srinivasanithin** [comment]
@magento-team Any update ?

**Comment by simpleadm** [comment]
Looks like it's not a bug, it's a feature :)

A workaround currently to make sure it only is updated for store_id = 0 is by adding store to the URL:

`PUT http://<domain>/index.php/rest/<store_id>/V1/products`

Where <store_id> can be **all** or **default**. The all ID is equal to the admin store code 0, while default can be variable in multi-store mode equal to the language code - en, fr, de, etc.

So you can use `PUT http://<domain>/index.php/rest/all/V1/products`

**Comment by smoskaluk** [comment]
@srinivasanithin If you want your changes to be implemented on all scopes - you need add "all" value in your call - like  PUT:(domain)/rest/all/V1/products/(sku)

**Comment by srinivasanithin** [comment]
@smoskaluk : I tested that suggestion and it works fine for me. "all" works for me to update the all storeviews. We are good to close.

**Comment by springimport** [comment]
@simpleadm Ok, I understood.

Use single store mode for 1 store look good. But sometimes magento can work [unexpectedly](https://community.magento.com/t5/Russian/%D0%9A%D0%B0%D0%BA-%D1%80%D0%B5%D1%88%D0%B8%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%83-%D1%81-store-id/m-p/67477/highlight/false#M3400
).

What is correct way to using single store mode?

**Comment by ankursachdeva11** [comment]
@smoskaluk, I was working with @srinivasanithin for this issue.
We are able to update attributes values on store view level using /all/V1/products API. 

but we are facing one issue by using this call. All websites are getting selected to display product on the frontend.

We want the product to be created without selected any website as we are able to create from UI.

Please check this issue and let us know what we can do for this use case.

**Comment by srinivasanithin** [comment]
@smoskaluk : We are facing issue with "all" store api call.

I am re-opening the issue because of the following issue we are facing using all store view in api call.

When I am updating the product without using "all" keyword in api url, it used to updating only default fields on default website. But when I use "all" in place of storeView it is updated all catalog_product fields, but it is also setting product as available on all websites, i.e, setting product on all websites ( even though there is no website field in request body, but this is causing issue in production ).  Can we please have proper way to update only defaults field ways and visible on all store views ( nothing changing on websites fields).

**Comment by ankursachdeva11** [comment]
@smoskaluk , Just following up.

**Comment by magento-engcom-team** [comment]
@srinivasanithin thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
