### ISSUE TITLE
GET /V1/categories only returns Default 

### ISSUE THREAD

**Issue by Augmensis** [magento/magento2#9876]
Looking through the archives, this seems to be a recurrence of issue #4525. 

When making a GET request to V1/categories, the results returned are only for the "Default Category" and it's children_data. Any other categories on the same level as the default are excluded, but can be called successfully individually by their ID.

### Preconditions

1. Using version 2.1.6 hosted with a third party provider

### Steps to reproduce

1. Install Magento
2. Create multiple categories and sub categories
3. Make a REST GET request to V1/categories

### Expected result

1. All categories created would appear in the list of results returned.

### Actual result

1. Categories were created:
![categories](https://user-images.githubusercontent.com/4013639/26924498-fd11cda6-4c3d-11e7-8757-3196854a662d.png)

2. Response received only contains default and it's child:
![response](https://user-images.githubusercontent.com/4013639/26924515-196724ce-4c3e-11e7-9b8a-71c5cebc9bc4.png)

**Comment by moleculech** [comment]
I think that's intentded... for frontend purposes it make sense to get only data from one store, not from every store. You can get the other categories by accessing /index.php/rest/storeviewcode/V1/ . If you need all categories you will have to make 3 API-Calls.

**Comment by Augmensis** [comment]
If that's the case, then is there a request that lists the different available storeviewcodes so that we can get all of the categories programmatically?

**Comment by Augmensis** [comment]
Ok, after a bit more digging and experimenting I've got the following as a reference for anyone else in the same situation:

1.  Assign any root-level categories to a specific site view.
2. Query: `GET /V1/store/storeConfigs` which will return a list of the available store views.
3. Use the resulting `{code}` property in the following query to get the list of categories for that particular view: `GET /rest/{code}/V1/categories`

Thanks for the pointer @moleculech :)
