### ISSUE TITLE
un check return to stock has no effect

### ISSUE THREAD

**Issue by tawfekov** [magento/magento2#9878]
once I needed to create a credit memo , I un checked `return to stock` option and I noticed it  has no effect and magento keeps returning it to stock , is that correct ?  

### Preconditions
1. stock is managed 
2. stock has positive number of items  

### Steps to reproduce
1. qty for an item is 9998  
2. create a credit memo and uncheck the option `Return to Stock` 
3. complete the refund , in my case all my tests was refund offline 

### Expected result

1. qty for this item must stay as  9998  

### Actual result

1. qty for this item is 9999

I noticed it in Magento 2.1.6 

this image only to make it extra clear where is that checkbox 
![credit-memo](https://user-images.githubusercontent.com/94997/26925706-7e8f9b64-4c53-11e7-8ea5-bddcba5962e8.png)

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70170 was created.

**Comment by magento-engcom-team** [comment]
@tawfekov, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by tawfekov** [comment]
@magento-engcom-team, I believe I faced it on `2.1.6` as I mentioned above , maybe it was fixed on newer versions  , I'll try to test it again this weekend on the versions you mentioned , thank you
