### ISSUE TITLE
False prices in product list and product single view on multistore with multi-product-price 

### ISSUE THREAD

**Issue by moleculech** [magento/magento2#9880]
I would like to have different product-prices in different stores. But that doesn't work.

### Preconditions
1. Magento 2.1.7 
2. PHP 7.1
3. Catalog Price Scope must be set to Website
![pricescope](https://user-images.githubusercontent.com/11146294/26927743-62a2f5a4-4c53-11e7-9a38-82b03b6e2147.PNG)

### Steps to reproduce
1. 2 Stores / Websites
2. 2 Currencies

_Default store - Price in backend_
![default_backend](https://user-images.githubusercontent.com/11146294/26927294-92fef010-4c51-11e7-8a6e-33949c996a9e.PNG)

_Chinese store - Price in backend_
![chinese_backend](https://user-images.githubusercontent.com/11146294/26927288-8f0bb9d4-4c51-11e7-9d18-9eb497b5d20c.PNG)

### Expected result
1. Different prices for every store
2. Same prices for Grid-View and Single-View in one store

### Actual result
_Price in chinese frontend Grid-View_
![price1](https://user-images.githubusercontent.com/11146294/26927356-d26528e6-4c51-11e7-8c3f-f90d0fa78db8.PNG)

_Price in chinese frontend Single-View (The Price is replaced by some javascipt)_
![price2](https://user-images.githubusercontent.com/11146294/26927393-f74e714e-4c51-11e7-89ef-5d222a377b56.PNG)

**Comment by veloraven** [comment]
@moleculech thank you for your report.
Unfortunately we were not able to reproduce this issue.
Could you please provide more detailed steps? 
Including but nit limited with:
* Type of the product
* All prices specified for the product at all scope levels
* Which currencies do you use?
* What exact prices do you expect to see at Storefront (as 'Use Default Value' checkbox is ticked on)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
