### ISSUE TITLE
 Uncaught Exception: Invalid Document  Element 'config', attribute '{http://magento.loc/index.php/admin/}noNamespaceSchemaLocation': The attribute '{http://magento.loc/index.php/admin/}noNamespaceSchemaLocation' is not allowed. Line: 28

### ISSUE THREAD

**Issue by Bkrishnach** [magento/magento2#9881]
### Preconditions

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@Bkrishnach please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
