### ISSUE TITLE
Error Something went wrong while saving the category.

### ISSUE THREAD

**Issue by Sandy-Verma** [magento/magento2#9882]
### Preconditions

1. I use Magento 2.1.7
2. PHP 5.6.3  MySQL 5.4

### Steps to reproduce

1. Login to Magento Admin
2. Go to Category > Click on any category having product more than 20000
3. Click on save category

### Expected result

1. Category would be save without any error.

### Actual result

1. Gives an error "Something went wrong while saving the category."

**Comment by veloraven** [comment]
@Sandy-Verma thank you for your report.
Please provide some additional information:
* Is your category anchor or not?
* Are there any subcategories or all products are assigned just to this one category? What is categories structure?
* Do you get specified error at once or after some time? How long do you wait to see it?
* Which values do you us for 
** memory_limit
** max_execution_time
* Was it clear install or upgrade from some previous version?

**Comment by thanasisgalanis** [comment]
I use Magento 2.1.7 and I have the same issue if i copy my database from a production server to a local development server.

When this error appear I search my var/exception.log file and found an excpetion starts with
`[2017-06-14 22:46:39] main.CRITICAL: PDOException: SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('[db_user]'@'localhost') does not exist in ...`

I fix this issue adding the missing user to the copy database.

Take a look gere https://stackoverflow.com/a/19707173 more details

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

@sakisplus what you describe seems to be not Magento issue but settings of the database server.
