### ISSUE TITLE
make build artifacts accessable

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#989]
see: http://docs.travis-ci.com/user/uploading-artifacts/

Reason:
You run several static analyzers like for example the phpcs part.
This generates a report file if it fails. It would be helpfull if people can look into this somehow, for example trough the linked travis feature.

**Comment by verklov** [comment]
Hello @Flyingmana! We already had a request that you mention about. It is contained in the comments to #926.  We created a ticket in the backlog for this improvement MAGETWO-32786. The team will work on this according to the priorities.

According to the new procedure of working with GitHub improvements and feature requests, we are closing GitHub tickets once we have a ticket in the backlog created in internal tracker. Thank you for your request! We are closing this ticket now. Please watch the repository updates.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/make-build-artifacts-accessable/idi-p/46697).

**Comment by magento-engcom-team** [comment]
Hi @Flyingmana. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#990 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [bccd2877b6d42ff9860437426e1cf97509695d35](https://github.com/magento/graphql-ce/commit/bccd2877b6d42ff9860437426e1cf97509695d35)

The fix will be available with the upcoming 2.3.4 release.
