### ISSUE TITLE
Magento Soap Keyword issue

### ISSUE THREAD

**Issue by ashishrvtech** [magento/magento2#9891]
I have a category name soap and its child categories so when i open the link http://localhost/mag2/en_ca/soap/liquid-hand-soap.html 
It instead of opening category download the html page treating soap keyword in url as soap api.

### Preconditions

1. Magento version 2.1.7

### Steps to reproduce

1.  Create a category name soap and create subcategories, Now when you access child categories it will throw error considering soap in url as  Soap API

### Expected result
1. Category may be accessed as expected

### Actual result
1. Category with SOAP in the name is considered to be SOAP API endpoint and displays an error

**Comment by Andrii-Deineha** [comment]
@ashishrvtech 
Internal ticket MAGETWO-69825 was created.

**Comment by magento-engcom-team** [comment]
@ashishrvtech, thank you for your report.
We've created internal ticket(s) MAGETWO-69825, MAGETWO-77448 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @ashishrvtech

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@ashishrvtech thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
