### ISSUE TITLE
Add product to website will reset has_options and required_options

### ISSUE THREAD

**Issue by Jeroenll** [magento/magento2#9896]
### Preconditions

1. Magento v2.1.7
2. PHP v7.0.14
3. MySQL v5.7.16

### Steps to reproduce

1. Create a 2nd website.
2. Create a configurable product with any attribute.
3. Add a Customizable Option (http://cloud.h-o.nl/krY0)
3. Save the product.
4. Open the tab `Product in Websites` and add you configurable to your created website.
5. Save the product.

### Expected result

1. Entry in table `catalog_product_entity` should have `has_options` and `required_options` set to `1`.

### Actual result

1. The columns `has_options` and `required_options` are set to `0`.
2. If you save the product again in the backend it will set `has_options` and `required_options` to `1` again.
3. After you added the product to you newly created website both columns are set to `0`. If you add the product to your cart it will do so without your selected custom option.

### Possible related
1. https://github.com/magento/magento2/pull/8498 (applying this fix won't help).

**Comment by IlnitskiyArtem** [comment]
Thank you, Internal ticket was created for this issue - MAGETWO-69927

**Comment by magento-engcom-team** [comment]
@JeroenVanLeusden, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
