### ISSUE TITLE
Magento all admin grid is stopped working 

### ISSUE THREAD

**Issue by babyasishhira** [magento/magento2#9897]
I am making a website in magento2. First I did some changes on my localhost and there I don't see any issue.

But after move that on a server subfolder I see no admin grids are working. I see that result is coming in json but it is not replacing the html. 

Can you please help me ?

![error](https://user-images.githubusercontent.com/17763698/26977854-f57c6c72-4d46-11e7-825f-0da1c9a9341c.png)

**Comment by veloraven** [comment]
@babyasishhira thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
