### ISSUE TITLE
Price in cart can become zero if backorders are allowed

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#9899]
### Preconditions

1. Magento 2.1.2 CE
2. Backorders allowed with "Allow Backorders below 0"
3. Flat Catalog (Category / Products) = enabled
4. Display out of stock products = enabled
5. Manage Stock is enabled
6. Product XY has inventory > 0 

### Steps to reproduce

1. Buy product XY so it has inventory left < 0
2. Open product detail page
3. Set disable Status of product (in database or with $product->addAttributeUpdate('status', 2);
4. Step to open product detail page and add Product to cart

### Expected result

Here we have to decide between to ways of handling
##### First way:
1. Product is added to cart
2. Product has price equal not equal to 0€
3. You can go to checkout but you get an error message that you can't buy this product
##### Second way:
1. Product can't be added to product
2. Products which are already in cart are removed from cart

### Actual result

1. Product is added to cart
2. Product has price equal to 0€
3. You can go into checkout (but you cant buy this product)
![cartproductwithprice0](https://user-images.githubusercontent.com/12051528/27001576-e7c99a5a-4dcd-11e7-8486-5066ef17e59b.png)
![cartproductwithprice0_productdetailpage](https://user-images.githubusercontent.com/12051528/27001587-31dc3e4a-4dce-11e7-8385-1736546df4af.png)

**Comment by AlexWorking** [comment]
Hello, @ulftietze. Based on Your issue an internal ticket was created - MAGETWO-70213. You'll be informed When the bug is fixed. Thank You for application.

**Comment by magento-engcom-team** [comment]
@ulftietze, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
