### ISSUE TITLE
Composer Integrity tests use hash validation but its deprecated

### ISSUE THREAD

**Issue by barbazul** [magento/magento2#9903]
### Preconditions

1. Composer 1.3.0+ (I am running 1.4.1)
1. Magento installed via Composer

### Steps to reproduce

1. Run static integration tests (more specifically: ComposerLockTest)

### Expected result

1. Tests should pass

### Actual result

Tests fail.

```
λ php vendor\phpunit\phpunit\phpunit -c dev\tests\static\phpunit.xml --filter=ComposerLockTest
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from C:\wamp64\www\magento2\dev\tests\static\phpunit.xml

E

Time: 7.75 minutes, Memory: 333.75MB

There was 1 error:

1) Magento\Test\Integrity\ComposerLockTest::testUpToDate
Undefined property: stdClass::$hash
```

### Additional information
Composer deprecated the hash property in composer.lock and instead uses content-hash to determine if lock file is up to date which is calculated in a different way.

See https://github.com/composer/composer/blob/master/CHANGELOG.md#130-rc---2016-12-11

I think this whole test should be deprecated as the hash is already being (correctly) validated by ComposerTest::testValidComposerJson (which has a bug of its own, but I'll open a new issue for that).

**Comment by veloraven** [comment]
@barbazul thank you for your report.
Please, identify which version of Magento you are running.

**Comment by barbazul** [comment]
I just checked current HEAD  and this was fixed  recently.

I still think the test is redundant with ComposerTest, but this ticket is no longer relevant.
