### ISSUE TITLE
Suggestion to change naming of "plugins"

### ISSUE THREAD

**Issue by airbone42** [magento/magento2#991]
Hi,

I would like to raise the awareness that the usage of "plugins" is quite verbose in the open source industry. So most cms or ecommerce projects reference to plugins as what we in the Magento world call extensions or modules. Especially merchants and not so experienced users might get confused by using the word plugin for something really technically specific and I can already think of a lot confusing discussions about that. :)

So is it still possible to change that naming to something more specific?

**Comment by antonmakarenko** [comment]
@airbone42 
We also use "Interceptor" word as a synonym to plugins. If we change it only in documentation, but keep using "plugin" in the source code -- is that good enough or you'd suggest to completely eliminate this term?

**Comment by TexanHogman** [comment]
Just today I learned it breaks down like this:
Technology: Interception
Developer creates: Plugins
Magento framework: Generates  Interceptors classes to call plugin

So yes we can align on a better non overloaded name.  Suggestions?


-----Original Message-----

**Comment by buskamuza** [comment]
@antonmakarenko , using different terms in the code and in the discussions is a bad idea, as "Domain-Driven Design" book says :)
"Interceptor" sounds good and reflects the idea/behavior.

**Comment by antonkril** [comment]
Interceptor doesn't reflect idea and it's already taken by auto-generated internal class that is used to call plugins.

**Comment by airbone42** [comment]
What do you think about naming it a "hook"?

Anyway I don't care so much about the final name, more that the current name plugin is really ambigious.

**Comment by fooman** [comment]
Maybe we can make it more specific by including `method` in the name - so something like `method hook`.

**Comment by davidalger** [comment]
My 2 cents: plugin is ambiguous as others have stated. There is no difference between a plugin, module, and extension in Magento 2. However, the documentation talks about creating "plugins" acting as if they are their own variety of extension/module which behaves differently in how it's built. But these "plugins" (aka interceptors) are used by core modules to create their functionality in a few cases as well. My recommendation…

1. Plugin/extension/module is: a software package installed into the system to alter/extend/create functionality non-native to the core.

2. Interceptor: a technology used to achieve the desired effect within the confines of a plugin/extension/module (see above definition).

3. Given the above definitions, change the use of "plugin" in the code and XML to "interceptor" to reduce confusion.

**Comment by TexanHogman** [comment]
To add to @davidalger point.

Reviewing Unity, this link https://msdn.microsoft.com/en-us/library/ff660861(v=pandp.20).aspx#_Instance_Interception best describes Magento implementation and uses the following terminology (interception, interceptor and interceptor pipeline) https://msdn.microsoft.com/en-us/library/ff660844(v=pandp.20).aspx#interception_pipeline
UNITY
Interception – is the technology
Interceptor – is the executed code 
Interceptor Pipeline – is the term for the collection of user provided interceptors.

therefore this maps to

MAGENTO
Interception – Magento technology
Interceptor – would be the actual code executed (currently called Plugin)
Interceptor Pipeline – would be Magento framework term for code generated today (currently called Interceptor)

This allows us to drop Plugin from our nomenclature and therefore makes it a bit easier to understand.

**Comment by davidalger** [comment]
@TexanHogman I beg to differ regarding it allowing us to drop "plugin" from our nomenclature.

> Interceptor Pipeline – is the term for the collection of user provided interceptors

This would correlate to the Magento framework actually gathering the interceptors from the many plugins installed in the system, or more specifically, the di.xml system.

Something has to contain that di.xml and provide the "call" to the interceptor pipeline (which is demonstrated in the MSDN link via the call to `pipeline.Add(interceptor);`) and we would then need to call this unit something. What has the interceptor, adds it to the interceptor pipeline, etc? A plugin! Overall I agree though, the correlations between the two are pretty synonymous as written. :)

**Comment by TexanHogman** [comment]
Due to our focus on making functional changes, we have unfortunately missed our opportunity on this naming clarification.  Tomorrow, we are code complete for our Dev RC release and such a change (as simple as it may be) would have developer impact going forward because of changes to di.xml and related schema.   Scrambling to make the code and related documentation changes in time didn't rank high enough. Nevertheless, thanks for the good idea.
