### ISSUE TITLE
configurable product Final Price ignores special date to 

### ISSUE THREAD

**Issue by DJ0815** [magento/magento2#9910]
When set a special price for child products which is outdated it still uses the special price for final price in product list

### Preconditions
1. Community Edition 2.1.6.
2. all caches deactivated, no varnish

### Steps to reproduce
1. creat configurable product with several child products
2. added special price to child products with date range 07/29/2015 to 08/05/2015
3. run indexer

### Expected result
1. Configurable Final Price ($final_price = $_product->getPriceInfo()->getPrice('final_price')->getValue()) should be the same as regular price ($_product->getPriceInfo()->getPrice('regular_price')->getValue())

### Actual result
1. Final Price in product in product list is sale price

**Comment by RomanKrut** [comment]
@DJ0815 Hi, thanks you for reporting this issue. Internal ticket was created MAGETWO-70386.

**Comment by vishveskrish** [comment]
@veloraven 

Do we get any solution?

**Comment by guvra** [comment]
Is there a fix available for this bug yet?

**Comment by Olek89** [comment]
Any Solution?

**Comment by magento-engcom-team** [comment]
@DJ0815, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by dan-advantec** [comment]
Please can you advise the commit ref?
I'm looking to build the fix into a standalone module to patch the issue as I'd rather not use the develop brand in a production environment.

**Comment by guvra** [comment]
Same, we need the commit reference to backport the fix into a website running on Magento 2.1.

**Comment by TonyDeplanque** [comment]
Please need commit ref too.

**Comment by guvra** [comment]
I found the commit ref: https://github.com/magento/magento2/commit/1ab9b26828cd4da268e9a7481d4969bffb1460c1

There's only a single class to rewrite :)

**Comment by babyasishhira** [comment]
@guvra thanks for the commit link, It solve the issue
