### ISSUE TITLE
Inconsistent "checkout_quote_init" event dispatch.

### ISSUE THREAD

**Issue by reviskar** [magento/magento2#9913]
We need a quote to have a unique string as a identifier. So, naturally, it seemed that the event "checkout_quote_init" would suit well for the initiation of our custom parameter. The thing is, this event is ONLY dispatched, when a customer is not logged in (\Magento\Checkout\Model\Session::252)

### Preconditions

1. Magento CE 2.1.7
2. PHP 7

### Steps to reproduce

1. Create a observer class for "checkout_quote_init" event
2. Add a "var_dump" or just a logger to notify the method call to your observers `execute()` method.
3. Add a product to the basket while logged in and not logged in.

### Expected result

1. The observer should dispatch "checkout_quote_init"  with both logged in and not logged in events.

### Actual result

1. The event fires only when the user is not logged in.

It is possible, that I'm not using this event for what it was built for, but as far as I can tell, this event should fire when the quote is initialized regardless of the customer object.

Waiting for any responses,
Rene

**Comment by gsomoza** [comment]
This is not really "inconsistent" – Magento will only initialize the quote once: if the customer is already logged in, then it will try to retrieve an existing quote for that customer.

Since what you're trying to do is closely related to "how" the quote model is created or it's identity (it MUST be created with an unique string identifier), I would consider implementing this as a plugin for `\Magento\Quote\Model\QuoteFactory`. I haven't tried this type of approach yet though (plugin of an automatically generated class), but it should be possible and if it works it would make the most sense IMO.

Another option is to hook to a lower-level event such as `model_load_after ` or `entity_manager_save_before` (EDIT: I haven't checked if those events are the best ones for this use-case).

**Comment by reviskar** [comment]
Thank You very much for the quick response. Will try to change my approach to this. 

Still I don't quite understand that, when I am logged in, and do not have a quote (i.e. have just finished an order and starting another order - therefore initializing a new quote) why isn't this new quote considered as "initialized". As You said, Magento will try to retrieve an existing quote - what if it doesn't exist?

But it is entirely possible I'm looking at this from a very limited point-of-view :).
Thanks again!

**Comment by gsomoza** [comment]
Your thought process is correct from the customer's perspective, but bottom line is that the `checkout_quote_init` event has a slightly different meaning in Magento's internals than it does from a customer experience point of view. I haven't looked at the low-level process with enough detail to be more specific than that.

Glad I could help. Good luck on the implementation!

**Comment by gsomoza** [comment]
Forgot to answer your question:

> Magento will try to retrieve an existing quote - what if it doesn't exist?

In that case it will proceed with the empty quote model [created here](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/Session.php#L213) (and as a consequence probably with `$this->getQuoteId() === null` assuming the default object state). 

If you implement a plugin on the factory using the object manager, then that line that creates the quote should already return the quote with your unique ID (although it won't be saved in the database yet). So no matter what flow goes on, your unique ID will always be added to a quote whenever a new one is created (you'll have to use a data upgrade script if you want to assign unique IDs to past quotes).

**Comment by reviskar** [comment]
So I came back to this now, and the plugin-to-the-factory way seems the most obvious here indeed. Sorry for the trouble, got it working as it was intended after dropping the observer. For me, the case is closed for now :) :+1: 

Many thanks for the trouble.
R

**Comment by ghost** [comment]
The dispatched events are for the developer's benefit customising - so should behave in a way like the customer's perspective. If you cannot specific why this is not so, it seems like the event should be fired but isn't implemented where a developer would reasonably expect it... as the entire issue demonstrates.
