### ISSUE TITLE
stripped-min-length Validation via UI Component Fails with "special" characters

### ISSUE THREAD

**Issue by bap14** [magento/magento2#9920]
When using a UI Component and adding the "stripped-min-length" validation as a rule to an input component, if the user inputs a "special" character (e.g. /, &, etc.) a javascript error is thrown.

### Preconditions
1. Magento EE 2.1.7, Magento CE 2.1.7
2. PHP 7.0.17
3. MySQL 5.7.18

### Steps to reproduce
1. Create a UI Component based form
2. Add the following validation to the XML form element definition

        <item name="validation" xsi:type="array">
            <item name="required-entry" xsi:type="boolean">true</item>
            <item name="no-whitespace" xsi:type="boolean">true</item>
            <item name="stripped-min-length" xsi:type="string">4</item>
        </item>

3. Test in admin using value `a/b` or `ab/` or `a&c`

### Expected result
1. Element should be invalidated due to length restriction

### Actual result
1. Javascript syntax error
![screen shot 2017-06-12 at 11 25 11 am](https://user-images.githubusercontent.com/15036826/27041430-f3c24d94-4f61-11e7-9b1b-fe4e8b8067cc.png)
![screen shot 2017-06-12 at 11 25 46 am](https://user-images.githubusercontent.com/15036826/27041445-ff677912-4f61-11e7-8805-6dafff9b27d4.png)

**Comment by veloraven** [comment]
@bap14 thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by bap14** [comment]
@veloraven  I installed Magento CE 2.1.7 and added my custom module and confirmed this does occur in the CE release as well.  I would prefer to keep this in the public domain in case there are other developers running into this same issue.  I can report it in both if necessary.  I'll update the initial posting to include the CE edition as well.

**Comment by bap14** [comment]
I didn't specify this earlier, but I was working in the admin area, not the frontend.

**Comment by magento-engcom-team** [comment]
@bap14, thank you for your report.
We've created internal ticket(s) MAGETWO-75838 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @bap14 the issue has been fixed in 2.2.1 and will be available soon  (#11084)

**Comment by bap14** [comment]
That's fantastic news!! Thank you!

**Comment by magento-team** [comment]
Hi @bap14. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
