### ISSUE TITLE
Magento 2.1 Rest API save attribute group does not change attribute_set_id

### ISSUE THREAD

**Issue by nikolaybaychenko** [magento/magento2#9921]
### Preconditions

1. Magento 2.1.7

2. PHP 7.0.18

### Steps to reproduce
1. Having a test attribute group:
```
{
  "attribute_group_id": "103",
  "attribute_group_name": "Test",
  "attribute_set_id": 4,
  "extension_attributes": []
}
```
2. Send a Rest API request:

> PUT /rest/V1/products/attribute-sets/4/groups

Headers:

    content-type: application/json
    Authorization: Bearer <authorization token>

Body:

    {
      "group": {
        "attribute_group_id": "103",
        "attribute_group_name": "Test",
        "attribute_set_id": 13,
        "extension_attributes": []
      }
    }

### Expected result

    {
      "attribute_group_id": "103",
      "attribute_group_name": "Test",
      "attribute_set_id": 13,
      "extension_attributes": []
    }

### Actual result

    {
      "attribute_group_id": "103",
      "attribute_group_name": "Test",
      "attribute_set_id": 4,
      "extension_attributes": []
    }

Response 200 OK.

Works if changing "attribute_group_name".

**Comment by veloraven** [comment]
Internal ticket: MAGETWO-69850

**Comment by magento-engcom-team** [comment]
@nikolaybaychenko, thank you for your report.
We've created internal ticket(s) MAGETWO-69850 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @nikolaybaychenko

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@nikolaybaychenko thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
