### ISSUE TITLE
Prefix and suffix are not prefilled in the quote shipping address

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#9924]
### Preconditions

1. enable customer prefix and suffix in the customer config
2. create an account with a prefix and a suffix

### Steps to reproduce

1. start an order, using an account with a prefix and a suffix
2. visit the shipping address step in the checkout

### Expected result

1. shipping address should be prefilled with prefix, firstname, middlename, lastname, suffix

### Actual result

1. shipping address is prefilled with firstname, lastname

the middle name is already added in #8878 (issue #8879)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69848
