### ISSUE TITLE
Subtotal in my account is excluding tax when defined including

### ISSUE THREAD

**Issue by marcojacobsNL** [magento/magento2#9927]
### Preconditions

1. Magento 2.1.7
2. Plesk server
3. PHP 7.0.19
4. 10.1.24-MariaDB

### Steps to reproduce

1. Go to stores->sales->tax
2. Make every field including tax, save & clear cache.
3. Go to store front and login into account and view orders.
4. Subtotal of order is still excluding tax.

### Expected result

1. Subtotal in My Account is expected to show including tax.

### Actual result

1. Subtotal in My Account is showing subtotal excluding tax.

### Configuration screenshots
![screen shot 2017-06-13 at 9 51 18 am](https://user-images.githubusercontent.com/16101434/27071629-092297e0-501e-11e7-8d66-5d5fd5385f61.png)
![screen shot 2017-06-13 at 9 51 27 am](https://user-images.githubusercontent.com/16101434/27071631-0ac36d4a-501e-11e7-8456-f2fe984b4358.png)
![screen shot 2017-06-13 at 9 51 32 am](https://user-images.githubusercontent.com/16101434/27071636-0ea09d34-501e-11e7-9677-e465c1db10d0.png)

### My Account
![screen shot 2017-06-13 at 9 53 34 am](https://user-images.githubusercontent.com/16101434/27071693-319805fc-501e-11e7-9c01-9e696e91b9b6.png)

**Comment by devjsha** [comment]
Did you tried placing new order after changing the configurations ??

**Comment by marcojacobsNL** [comment]
Yes multiple new orders

**Comment by devjsha** [comment]
I think it's correct only because if you check the note in small letters mentioned below the Catalog Prices 
field, it says "This sets whether catalog prices entered from Magento Admin include tax." This means that whatever is the amount of the product is, it is including tax. So this is the reason why the subtotal is showing as excluding tax in my account.

**Comment by marcojacobsNL** [comment]
Okay, so there isn't a way we can show the subtotal without tax conducted?

**Comment by devjsha** [comment]
if you set the configuration settings to Excluding tax then that means your subtotal doesn't include tax amount so in my account the order details will be shown something like this.

Subtotal	                        $100.00
Shipping & Handling	$5.00
Tax	                                $8.25
Grand Total	                $113.25

And if you set the configuration settings to Including tax then that means your subtotal include tax amount so in my account the order details will be shown something like this.

Subtotal	                        $100.00
Shipping & Handling	$5.00
Grand Total	                $105.00

This is the standard way magento uses, hope this clears your doubt.

**Comment by marcojacobsNL** [comment]
I see.

We don't want to show any tax values on our magento shop. So to speak we want to see it like this:

product 1 $5 (incl tax)
product 2 $5 (incl tax)
subtotal $10
Shipping $6
total $16

But at this moment it won't allow that. Is that correct?

**Comment by devjsha** [comment]
Yes it will, set your configuration setting to including tax then it will show like this only. Just check the following

Product 1 100$(incl tax)
Subtotal	$100.00
Shipping & Handling	$5.00
Grand Total	$105.00

The above shown example is similar to your requirement and this can be achieved by setting configuration setting to including tax.

**Comment by veloraven** [comment]
@xeriuk thank you for your report.
Unfortunately we were not able to reproduce this issue.
1. Could you please provide some additional information?
2. Did you clear all cache including Varnish, Redis if used, etc?
3. Was it clear Magento install or upgrade from some previous version?
4. What scope level did you use for tax settings? (Global/website/store/store view)
5. How did you add a localization? 
6. Do you use any external modules?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by Altamash-s-s** [comment]
Hi @marcojacobsNL 
if i setup this in my magento it will work on in my vue storefront 


i want to display tax  excluding in my vue storefront 

![Screenshot 2023-10-21 172429](https://github.com/magento/magento2/assets/142004363/1f5e4a2d-a791-48bc-85ad-7fe2c6fc4f69)
