### ISSUE TITLE
check out page is showing empty magento 2.1.6

### ISSUE THREAD

**Issue by yasirrose** [magento/magento2#9933]
I am having issue with magento checkout page, everything is working fine but when i add product to cart, it is showing empty. 

I have enable the errors but no errors found in logs or checked out page. 

It is showing following warning in console. 

```
[JQMIGRATE: Logging is active
VM10714:9 JQMIGRATE: jQuery is not compatible with Quirks Mode
migrateWarn @ VM10714:9
(anonymous) @ VM10714:12
(anonymous) @ VM10714:50
require.load @ cea356d….min.js:175
load @ cea356d….min.js:112
require.s.contexts._.load @ cea356d….min.js:134
load @ cea356d….min.js:55
(anonymous) @ cea356d….min.js:55
(anonymous) @ cea356d….min.js:11
execCb @ cea356d….min.js:112
check @ cea356d….min.js:56
enable @ cea356d….min.js:73
init @ cea356d….min.js:54
(anonymous) @ cea356d….min.js:97
VM10714:9 console.trace]
```

Page is showing script tag only when i view the source of the page. Not know if it will help anyone to solve my issue.

**Comment by lojasmarques** [comment]
Na página aparece o mesmo problema, não sei  se aconteceu depois que alterei as posições dos Menus do Catálogo, pois não aparece mais nada no Lojas> Configurações> Configuração e também aparece a tela em branco a página do Código-Fonte do Checkout e a mensagem "There has been an error processing your request"  < https://lojasmarques.com/br/checkout/ >
Host: 93.188.160.65
user: u358341845
senha: (por WhatsApp)
http://www.lojasmarques.com/br/gerencia
Magento 2.1.6
PHP 5.6
Alguém que possa me ajudar a corrigir esse erro?
> https://lojasmarques.com/br/gerencia/admin/system_config/index/key/{...} <

Tel: 55 53 981426029
Email: admin@lojasmarques.com

**Comment by veloraven** [comment]
@yasirrose thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by yasirrose** [comment]
it was due to a plugin for page speed which is making it to empty.
