### ISSUE TITLE
Setup:di:compile issue

### ISSUE THREAD

**Issue by coatesjonathan** [magento/magento2#9934]
When I run:

php bin/magento setup:di:compile

I get this error at 71%:

[ReflectionException]                                     
  Class Zend\Cache\Storage\StorageInterface does not exist

How do I fix?

**Comment by jordanbrauer** [comment]
What is your PHP memory limit?
Have you (fully) installed Magento?
Have you recently upgraded Magento? If so, did you run `composer update` to install the new code?

**Comment by coatesjonathan** [comment]
I haven't updated Magento, and Yes it's fully installed, seems all good, I have realised this issue is due to the Magento Stripe Extension I have added.

**Comment by magento-engcom-team** [comment]
@coatesjonathan Closing, as issue is resolved.
Thank you.
