### ISSUE TITLE
EE 2.1.7 layout_merged.xml file missing definition for layoutType

### ISSUE THREAD

**Issue by dfelton** [magento/magento2#9936]
### Preconditions
1. Magento EE 2.1.7

### Steps to reproduce
1. Install Magento EE 2.1.3 or 2.1.7.
2. Turn on developer mode
3. Deploy frontend static files
4. Turn off all cache types
5. Load a frontend page

### Expected result
1. support_report.log should be clean (or not exist at all yet)

### Actual result
- `\Magento\View\Model\Layout\Merge::_validateMergedLayout()` litters `var/log/support_report.log` with errors. Example error message: `Cache file with merged layout: LAYOUT_frontend_STORE1_12a7ccd8094436548b564a588f6303121c and handles 2columns-left: Please correct the XML data and try again.`
- The error is being thrown by `\Magento\Framework\View\Model\Layout\Update\Validator::isValid()`. Within the `try/catch` the `\Exception` catch block is executing.
- `\Exception` message: `Warning: DOMDocument::schemaValidate(): Invalid Schema in vendor/magento/framework/Config/Dom.php on line 311`

### Further Information:
- Inspecting the values of `$value` and `$schema` (inside the `\Magento\Framework\View\Model\Layout\Update\Validator::isValid()` method), I copied the XML and the path to the XSD file and pasted it into my IDE. 
- XSD File: `vendor/magento/framework/View/Layout/etc/layout_merged.xsd`
- The IDE reported not an error in the XML but instead a problem with the XSD file. `layoutType` 
- IDE's Error: `src-resolve: Cannot resolve the name 'layoutType' to a(n) 'type definition component'`
- Comparing the contents of `layout_merged.xsd` in Magento EE 2.1.7 vs Magento EE 2.1.7 I found out that the EE version had fallen behind and has not received recent updates that CE's version has. 

### Resolution:
- Replaced entire contents of EE's version with [Current copy of CE's develop](https://raw.githubusercontent.com/magento/magento2/5affd8aa4c44f2f137bb171887af000b9ef27d09/lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd).

**Comment by dfelton** [comment]
After reading @korostii's [comment](https://github.com/magento/magento2/issues/9946#issuecomment-308493361) regarding the purpose the `2.1-develop` branch vs the `develop` branch, I am lead to believe this XSD file simply has not been updated in the latest version of either EE or CE. [Reviewing 2.1-develop seems to confirm this](https://github.com/magento/magento2/blob/2.1-develop/lib/internal/Magento/Framework/View/Layout/etc/layout_merged.xsd).

**Comment by Stas94** [comment]
@dfelton If this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by dfelton** [comment]
Thanks @Stas94, the issue is for both CE and EE. 

At the time of originally reporting I did not have as good understanding of the different github branches and their purposes.

**Comment by orlangur** [comment]
This was fixed for `2.1-develop` branch in https://github.com/magento/magento2/pull/9718, there are at least two open GitHub issues (see that PR) currently tracking this bug for `2.1.x` already :)
