### ISSUE TITLE
REST | API guest-cart returns Cart Id with quotes.

### ISSUE THREAD

**Issue by DavidLambauer** [magento/magento2#9942]
To use the Magento 2 Checkout, I am starting with getting a Cart Id. Due to that, I run the following request:

```BASEURL/rest/V1/guest-carts```

### Preconditions
1. Magento EE 2.1.6

### Steps to reproduce
1. Enter the following request in your terminal: ```curl --request POST  --url BASE_URL/rest/V1/guest-carts```

### Expected result
1. 9cdb1f51fdc3bfa2313dae65eb231271

### Actual result
1. "9cdb1f51fdc3bfa2313dae65eb231271"

In my opinion, there is no need to have the quotes around the result. Am I wrong?

**Comment by timneutkens** [comment]
Expecting all responses from the api being valid JSON. This is not a bug/issue. Example:

```js
// throws error
JSON.parse('test')
```

```js
// parses to a string
JSON.parse('"test"')
```

**Comment by magento-engcom-team** [comment]
@DavidLambauer Thanks for reporting this issue. Please check BASE_URL/swagger. Also You can check 'Magento\Quote\Api\GuestCartManagementInterface::createEmptyCart()', which is called upon BASE_URL/rest/V1/guest-carts. There You can see, that return type is string. Therefore "9cdb1f51fdc3bfa2313dae65eb231271" - is correct result. 
Please reopen this issue as needed.
