### ISSUE TITLE
Magento admin panel doesn't work correctly

### ISSUE THREAD

**Issue by PVLPM** [magento/magento2#9945]
I've just logged into my Magento admin panel and I can't work properly.

### Preconditions

1. Magento 2 installed on cPanel via Softaculous
2. Magento ver.       2.1.7 
cPanel Version	58.0 (build 49)
Apache Version	2.2.31
PHP Version	        5.4.45
MySQL Version	10.1.22-MariaDB-cll-lve
Architecture	        x86_64
Operating System	linux
Perl Version	        5.10.1
Kernel Version	        2.6.32-673.8.1.lve1.4.3.el6.x86_64

### Steps to reproduce

1. Completed 'php indexer:reindex' via SSH
2. Flushed Magento Cache

### Expected result

1. After those 2 steps it started to crash, but as an example, Magento logo in the panel at the left side didn't work at the start of a day. It should work properly, shows all the symbols and expands hover menus.

### Actual result

1. [Screenshot, logs]
![screenshot from 2017-06-14 16-48-22](https://user-images.githubusercontent.com/19179207/27135954-92e6ff84-5122-11e7-8484-4910ae28ee91.png)

**Comment by InvaderDolan** [comment]
**!!! SOLVED !!!**
I just pressed on these buttons in Cache Management:
**Flush JavaScript/CSS Cache**  (Themes JavaScript and CSS files combined to one file)
**Flush Static Files Cache**  (Preprocessed view files and static files)

If it didn't help, try to reindex and flush all available caches.

**Comment by PVLPM** [comment]
**!!! SOLVED !!!** UPD **NOT SOLVED**
I just pressed on these buttons in Cache Management:
**Flush JavaScript/CSS Cache**  (Themes JavaScript and CSS files combined to one file)
**Flush Static Files Cache**  (Preprocessed view files and static files)

If it didn't help, try to reindex and flush all available caches.

**Comment by PVLPM** [comment]
**OH NO**

Buttons still don't work properly. And icons again are empty rectangles...

**Comment by PVLPM** [comment]
At least, I reinstalled it.

P.S. It could be problem in memory_limit (by default it's 64M or 128M), but I changed it.
