### ISSUE TITLE
503 when trying to access admin route

### ISSUE THREAD

**Issue by MTheProgrammer** [magento/magento2#9947]
The menu block is unable to fetch categories for current store

### Preconditions

1. Magento CE 2.1.6 && EE 2.1.7
2. Set admin panel frontName in etc/env.php different than _admin_

### Steps to reproduce

1. Go to http://domain.com/admin

### Expected result

1. Redirect to 404 page

### Actual result

1. Error in sql selecting from not existing table catalog_category_flat. This is caused by fact that actual store id is 0.

**Comment by Andrii-Deineha** [comment]
@MTheProgrammer Hi, I cannot reproduce this issue. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
