### ISSUE TITLE
Event observers fire from disabled modules

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#9948]
Magento will still fire observers for disabled modules.

Besides simply triggering unwanted functionality, this can also potentially cause fatal errors if the module was disabled before the install scripts ever ran, as the observer will expect the module to be installed (and any schema/data changes to be applied), which it won't be in this case.

### Preconditions
Magento 2.1.3

### Steps to reproduce
1. Add the code for a module that has a setup script with schema changes used by an observer (e.g., Magento_AdminNotification), but do not yet run `setup:upgrade`.
2. Disable the module.
2. Run `setup:upgrade`. Because the module is disabled, schema changes will not be made (correctly so).
3. Perform action on site triggering observer that assumes database schema (e.g., log into admin when there is a pending notification).

### Expected result
Observer is not fired, since module is disabled.

### Actual result
Observer is fired, causing a potentially fatal error if it assumes schema changes have occurred.

**Comment by Stas94** [comment]
@scottsb Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by scottsb** [comment]
Is there a particular area you want clarification on? I already provided the steps to reproduce. (For what it's worth, the example I cite of `Magento_AdminNotification` isn't just hypothetical; it's the actual module we had disabled that caused us to run into this, so you could do the same.)

**Comment by ghost** [comment]
OK

Op 5 jul. 2017 21:59 schreef "Scott Buchanan" <notifications@github.com>:

**Comment by scottsb** [comment]
I did just clarify the problem statement in the issue. The fundamental bug is simply that event observers in disabled modules still run. My steps to reproduce illustrate how this can lead to a fatal error, though obviously there are many ways this could fail since code is running that's supposed to be disabled.

**Comment by magento-engcom-team** [comment]
@scottsb, thank you for your report.
We've created internal ticket(s) MAGETWO-71009 to track progress on the issue.

**Comment by thiagolima-bm** [comment]
I am working on it #SQUASHTOBERFEST

**Comment by sreichel** [comment]
@scottsb do you have example module that you can share?

**Comment by scottsb** [comment]
It's been over a year, and I haven't bumped into this since I reported it. However, as I recall, this came up while doing a Magento upgrade on a store that had `Magento_AdminNotification` disabled.

Note that this can't be demonstrated by a module alone because it has to do with the configured status of the module in `config.php`. See steps to reproduce in the description.

**Comment by nickgraz** [comment]
@magento-engcom-team Any update on this? This is causing issues in 2.3 with the new `MSP_ReCaptcha` module... we have it disabled and we are getting errors like:

```
[2019-01-03 18:22:29] report.ERROR: Class MSP\ReCaptcha\Observer\Frontend\LoginObserver does not exist [] []
[2019-01-03 18:22:44] report.ERROR: Class MSP\ReCaptcha\Observer\Frontend\CreateUserObserver does not exist [] []
[2019-01-03 18:28:27] report.ERROR: Class MSP\ReCaptcha\Observer\Frontend\LoginObserver does not exist [] []
[2019-01-03 18:35:10] report.ERROR: Class MSP\ReCaptcha\Observer\Frontend\CreateUserObserver does not exist [] []
```

...because the Virtual Types are not getting compiled (since the module is disabled) but the events are still firing.

**Comment by nickgraz** [comment]
I just upgraded to 2.3.2 and it seems there are other areas where Magento ignores the fact that a module is disabled. During "Repositories code generation":

```
Fatal error:  Interface 'MSP\ReCaptcha\Model\Provider\FailureProviderInterface' not found in /var/www/magento/vendor/magento/module-paypal-recaptcha/Model/Provider/Failure/PaypalResponseFailure.php on line 25

Fatal error: Interface 'MSP\ReCaptcha\Model\Provider\FailureProviderInterface' not found in /var/www/magento/vendor/magento/module-paypal-recaptcha/Model/Provider/Failure/PaypalResponseFailure.php on line 25
```

Partial trace
```
#0 /var/www/magento/vendor/composer/ClassLoader.php(444): include()
#1 /var/www/magento/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile(\'/var/www/magent...\')
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass(\'Magento\\\\PaypalR...\')
#3 [internal function]: spl_autoload_call(\'Magento\\\\PaypalR...\')
#4 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(125): class_exists(\'Magento\\\\PaypalR...\')
#5 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(111): Magento\\Setup\\Module\\Di\\Code\\Reader\\ClassesScanner->includeClasses(Array, \'/var/www/magent...\')
#6 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(82): Magento\\Setup\\Module\\Di\\Code\\Reader\\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#7 /var/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\\Setup\\Module\\Di\\Code\\Reader\\ClassesScanner->getList(\'/var/www/magent...\')
```

I have the `Magento_PaypalReCaptcha` module disabled though...

```
cat app/etc/config.php | grep Magento_PaypalReCaptcha
        'Magento_PaypalReCaptcha' => 0,
```

Magento even recognizes the module as disabled per the CLI tool.
```
magento module:status | grep -E "(Magento_PaypalReCaptcha|disabled|enabled)"
List of enabled modules:
List of disabled modules:
Magento_PaypalReCaptcha
```

I understand that Magento wants to fill the platform will all kinds of goodies, but the app should certainly respect the decision of a developer to use a core feature that Magento provides (disabling modules).

I will create a ticket for that issue and link it here when I do.

**Comment by cscd98** [comment]
Having this issue on 2.3.2 as well.

**Comment by duckchip** [comment]
@scottsb I tested this on branch 2.3-develop and was not able to reproduce this.
This is the scenario I used:

1. Create a module 'Vendor_Module' with a events.xml file that listens to the event "this_custom_event" linked to an instance "Vendor/Module/Observer/Event".
This observer just does a var_dump.

`<event name="this_custom_event">
        <observer name="vendor_module_event"
                  instance="Vendor\Module\Observer\Event" />
    </event>`

```
<?php

namespace Vendor\Module\Observer;

use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Event\Observer;

class Event implements ObserverInterface
{

    public function execute(Observer $observer)
    {
        var_dump("i got fired");
    }
}

```

2. Dispatch the event "this_custom_event" from a simple Controller.
`$this->eventManager->dispatch("this_custom_event");` 

My results:

The var_dump is only shown when the 'Vendor_Module' is enabled. 

Can you give me some more information on how to reproduce this issue or verify my test? 

thx!

**Comment by shikhamis11** [comment]
I also tried to reproduce this issue on magento 2.3.4 instance but it is not reproducible now 
@scottsb can you confirm the same ?

**Comment by engcom-Bravo** [comment]
As per this comment https://github.com/magento/magento2/issues/9948#issuecomment-617407763 issue is no more reproducible we are closing this issue.

Thanks.
