### ISSUE TITLE
Magento 2 Rest API edit category gives unexpected result

### ISSUE THREAD

**Issue by nikolaybaychenko** [magento/magento2#9949]
This issue was previously reported [here](https://github.com/magento/magento2/issues/9667). The reason for making a new issue is formatting a complaint according to the reporting guidelines. 

### Preconditions

1. Magento 2.1.7
2. PHP 7.0.18

### Steps to reproduce

1.  Having a test category of products:
```
"id": 20,
"parent_id": 2,
"name": "Clothes"
"is_active" => true
```

2. Send a Rest API request:

> PUT /rest/V1/categories/20

Headers:

```
content-type: application/json
Authorization: Bearer <authorization token>
```

Body:
```
{
    "category": {
        "id": 20,
        "parentId": 21,
        "name": "Test Category 1",
        "isActive": true
    }
}
```

### Expected result

```
"id": 20,
"parent_id": 21,
"name": "Test Category 1",
"is_active": true,
```

### Actual result

```
"id": 20,
"parent_id": 2,
"name": "Test Category 1",
"is_active": true,
```

Response 200 OK.

Category name doesn't change, even if response shows that it is changed. 
![a829966e-4acd-11e7-83f6-9f3b488f0622](https://user-images.githubusercontent.com/13581265/27144782-de854766-513b-11e7-8f2e-39ebbd14ab5d.png)

**Comment by AlexWorking** [comment]
Hello, @addxorsw. An internal ticket was created according to Your issue MAGETWO-69902. As the issue is fixed You'll be informed. Thank You for reporting it.

**Comment by magento-engcom-team** [comment]
@nikolaybaychenko, thank you for your report.
We've created internal ticket(s) MAGETWO-69902 to track progress on the issue.

**Comment by rehman0845** [comment]
Hi @magento-engcom-team, Did the update parentId in Category issue resolved ? As I'm using REST API to push data to Magento 2.2 . I got the same issue as @nikolaybaychenko  while updating the parentId in category and its not Updated the parentId.

**Comment by routbiplab** [comment]
Hi, When you update with rest/V1/categories/5 it affects the default store view scope.

**Comment by rehman0845** [comment]
Hi @routbiplab when updating the category, parentId is not updating
I'm using the payload to Create the category
POST rest/v1/categories
{
  "category": {
    "parentId": 2,
    "name": "Sports",
    "isActive": true,
    "includeInMenu": true
    }
}
and  the payload to Update the category
PUT rest/v1/categories/5
{
  "category": {
    "id": 5,
    "parentId": 4,
    "name": "Sports",
    "isActive": true,
    "includeInMenu": true
    }
}
when the parentid is modified it's not updating

**Comment by sagar-vasani** [comment]
Please use following PUT command endpoint to set parent_id of any category.
https://devdocs.magento.com/swagger/#/catalogCategoryManagementV1/catalogCategoryManagementV1MovePut
