### ISSUE TITLE
EntityManager entity's entityType check

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#9958]
When we are loading entity through entity manager following statement calling 7 times:

` $this->typeResolver->resolve($entity); `

1.Magento\Framework\EntityManager\EntityManager :load
2.Magento\Framework\EntityManager\Operation\Read :execute
3.Magento\Framework\EntityManager\Operation\Read\ReadMain :execute
4.Magento\Framework\EntityManager\Hydrator:extract
5.Magento\Framework\EntityManager\Operation\Read\ReadAttributes :execute
6.Magento\Framework\EntityManager\Hydrator:hydrate
7.Magento\Framework\EntityManager\Operation\Read\ReadExtensions :execute

is It really required checking entity type **7 times instead of 1 time** ?
i think we can pass entityType to all classes as a parameter once we call first time. 

```
$categoryModel = $this->_objectManager->create('\Magento\Catalog\Model\CategoryFactory')->create();        
  $categoryResource = $this->_objectManager->create('\Magento\Catalog\Model\ResourceModel\Category');        
  $categoryResource->load($categoryModel, 3);        
  echo $categoryModel->getName();
```

**Comment by korostii** [comment]
I believe the community forums are expected to be used for technical questions.
GitHub Issues, on the other hand, are for the consistently reproducible bugs.

So, unless you have some concrete benchmarks or a pull request to back it up, I am not quite sure what kind of a response are you hoping for here.

**Comment by veloraven** [comment]
@sivajik34 thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
If you want to propose an improvement please refer to [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

@korostii thank you for explanation.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
