### ISSUE TITLE
Unable to save tax_class_id attribute

### ISSUE THREAD

**Issue by JancyAbraham** [magento/magento2#9962]
Unable to edit/save tax_class_id attribute from backend. The page is always loading when I try to save this. All other attributes working fine

**Preconditions**
Magento CE 2.1.7 

**Steps to reproduce**
   1. Go to Admin > Store > Attributes > Product
   2. Edit 'tax_class_id' attribute
   3. Press Save button

**Expected result**
Changes should be saved and display success message

**Actual result**
It shows the loader only. 
http://i.prntscr.com/1XfSOmkxRdGqDL7VJ6AoxA.png
http://i.prntscr.com/CaX_bgHsTGyblS0gm3ga-A.png
Error report - http://i.prntscr.com/SGDeGlVSSy2LhFRErr1k3g.png

**Comment by Andrii-Deineha** [comment]
@JancyAbraham, Thanks for reporting this issue. 
I’m closing this issue because it is a duplicate #9669 
We've created internal ticket MAGETWO-69716 to address this issue.
