### ISSUE TITLE
Some messages in Customer Account Create not translated

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#9967]
Some messages in Customer Account Create not translated

### Preconditions
1. Magento 2.1.7
2. PHP 5.6
3. Use a located version (not en_US nor en_GB)

### Steps to reproduce
1. Go to Create an Account 
2. Insert a small password or a password with only ciphers, insert a not valid email address

### Expected result
1. Warning messages about password validation appears in locale language

### Actual result
1. Warning messages about password validation appear in english language
    - Minimum length of this field must be equal or greater than %1 symbols. Leading and trailing spaces will be ignored.
    - Minimum of different classes of characters in password is %1. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.
2. Warning message about email validation appears in english language
    - Please enter valid email addresses, separated by commas. For example, johndoe@domain.com, johnsmith@domain.com.

I wasn't able to patch the file vendor/magento/module-ui/view/base/web/js/lib/rules.js

**Comment by dmitriyprime** [comment]
Hello, @angelo983 . An internal ticked MAGETWO-55900 was created based on Your issue. You'll be informed as the issue is fixed. Thanks for applying.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71380

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250

**Comment by magento-engcom-team** [comment]
@angelo983, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @angelo983 the issue is already fixed in 2.1.10 and will be available soon
