### ISSUE TITLE
sample data will not install

### ISSUE THREAD

**Issue by rgauny** [magento/magento2#997]
[ERROR] exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_type_id' in 'field list'' in C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array) #5 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array) #6 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1833): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `ca...', Array) #7 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery.php(153): Magento\Framework\DB\Adapter\Pdo\Mysql->insertOnDuplicate('catalog_product...', Array, Array) #8 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery.php(94): Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery->storeImage(Object(Magento\Catalog\Model\Product\Interceptor), Array) #9 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product.php(152): Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery->install(Object(Magento\Catalog\Model\Product\Interceptor)) #10 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup.php(77): Magento\Tools\SampleData\Module\Catalog\Setup\Product->run() #11 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Installer.php(81): Magento\Tools\SampleData\Module\Catalog\Setup->run() #12 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\SampleData.php(75): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User)) #13 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\Installer.php(896): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'admin') #14 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array) #15 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\Installer.php(297): call_user_func_array(Array, Array) #16 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Controller\Install.php(80): Magento\Setup\Model\Installer->install(Array) #17 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction() #18 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #19 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #20 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #21 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #22 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #24 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #25 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #26 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #27 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\index.php(25): Zend\Mvc\Application->run() #28 {main} Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_type_id' in 'field list', query was: INSERT INTO `catalog_product_entity_varchar` (`entity_type_id`,`entity_id`,`attribute_id`,`value`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)' in C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array) #4 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array) #5 C:\Users\rgaunyjr\Documents\GitHub\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1833): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `ca...', Array) #6 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery.php(153): Magento\Framework\DB\Adapter\Pdo\Mysql->insertOnDuplicate('catalog_product...', Array, Array) #7 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery.php(94): Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery->storeImage(Object(Magento\Catalog\Model\Product\Interceptor), Array) #8 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup\Product.php(152): Magento\Tools\SampleData\Module\Catalog\Setup\Product\Gallery->install(Object(Magento\Catalog\Model\Product\Interceptor)) #9 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Module\Catalog\Setup.php(77): Magento\Tools\SampleData\Module\Catalog\Setup\Product->run() #10 C:\Users\rgaunyjr\Documents\GitHub\magento2\dev\tools\Magento\Tools\SampleData\Installer.php(81): Magento\Tools\SampleData\Module\Catalog\Setup->run() #11 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\SampleData.php(75): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User)) #12 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\Installer.php(896): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'admin') #13 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array) #14 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Model\Installer.php(297): call_user_func_array(Array, Array) #15 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\module\Magento\Setup\src\Controller\Install.php(80): Magento\Setup\Model\Installer->install(Array) #16 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction() #17 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #18 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #19 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #20 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Controller\AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #21 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #22 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #23 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #24 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-eventmanager\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 C:\Users\rgaunyjr\Documents\GitHub\magento2\vendor\zendframework\zend-mvc\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #26 C:\Users\rgaunyjr\Documents\GitHub\magento2\setup\index.php(25): Zend\Mvc\Application->run() #27 {main}

**Comment by mazhalai** [comment]
For internal tracking - MAGETWO-33085

**Comment by johnbendi** [comment]
What's the status of this bug? I'm getting the same error.

**Comment by johnbendi** [comment]
Is there any temporary workaround or sample-data one can use for installation at the moment?

**Comment by NZKiwi32** [comment]
Also got the same issue, any patch suggestions?

**Comment by Gaffen** [comment]
+1 Any immediate suggestions before an official push would be appreciated

**Comment by rickstek** [comment]
Running into this as well, when installing sample data for simple products ::
Installing simple products:
[ERROR] exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_type_id' in 'field list'' in /Users/Matt/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228

**Comment by voleye** [comment]
It was fixed in 0.42.0-beta5 (http://packages.magento.com/#magento/sample-data)

**Comment by DavidBruchmann** [comment]
There was a compatibility issue between Magento2 Versions and
Sample-Data-Versions not long time ago.
Look in the mail-Archive, max 2 weeks ago.

**Comment by DavidBruchmann** [comment]
"

There was a compatibility issue between Magento2 Versions and
Sample-Data-Versions not long time ago.
Look in the mail-Archive, max 2 weeks ago

"
The item was : "Error installing sample data with 0.42.0-beta2"


On Sat, Jan 31, 2015 at 12:27 AM, David Bruchmann <david.bruchmann@gmail.com

**Comment by Gaffen** [comment]
Thanks @voleye, documentation on the magento website recommends 0.42.0-beta2.

However I have just pulled the most recent update to master and now get this:

    [ERROR] exception 'ReflectionException' with message 'Class Magento\Store\Model\StoreManagerInterface does not exist' in /Applications/XAMPP/xamppfiles/htdocs/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29

I'm assuming that's a separate issue though...

**Comment by rickstek** [comment]
Guys,

So I did run an update, and was able to finish install. Try dropping the DB and making a new one before running the installer. Since you are installing sample data, dont think there would be an issue starting with a fresh DB.

**Comment by joanhe** [comment]
@rgauny The record indicates that we have fix for this issue. Could you please let us know if this problem is still there for you? Thanks.

**Comment by vpelipenko** [comment]
This issue was fixed and delivered to public repository. Closed. There are no complaints from contributor for more than 2 weeks.
