### ISSUE TITLE
Attribute set info does not persist correctly on product save

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#9977]
### Preconditions

1. Magento CE 2.1.7 with sample data

### Steps to reproduce

1. Go to a product (admin edit product page) and add a configurable product (from other attribute set) as related product, up-sell product or cross-sell product.
I used the first product in catalog, "Joust Duffle Bag" (SKU 24-MB01) and added to related products the configurable product 'Caesar Warm-Up Pant' (SKU MP01). The attribute set of the current product must be different than the product in grouped relation tab.
Please try other other attribute set / product type combination to see if the issue is there.
Save the product to store the related product relations.
2. Set a different value into the multiselect attribute 'Activity' and save the product.

### Expected result

1. The product will have the same value in Activity attribute.

### Actual result

1. It should save the multiselect value into the product.
The case happens in other Magento 2 installation, not only in CE 2.1.7 with sample data.

**Workaround**
If you remove the related product and save the product with a value into the multipleselect  attribute, it will save it correctly. This is the workaround.
What concerns me is that other type of attributes can have a class in `backend_model` column and it may affect severely random functionality in Magento 2 that depends on having accurate product attribute values.
Though, I haven't test and din't looked to other functionalities that depend on backend_model of the attribute in product save.

**Debugging:**
I've debugged the code and exposed the problem but didn't find the exact place that's causing it.
The main problem is that multiselect attributes backend model (Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend) isn't called on product save but it should.
I'm expanding this case from multiselect attributes to all attributes with something in backend_model in `eav_attribute` table (though I didn't tested/debugged the overall case).

In the case of multipleselect products, on product save action, the value is in the product data but it is a string like (option1,option2). The backend class transforms the string into an array (explode("," $string value)); This is why the multiselect value is not saved (the value isn't transformed into an array) in walkAttributes function (see bellow).

After you click save button on admin edit product page, 3 requests are called:
1. product/validate
2. product/save
3. back to product/edit page

The bug happens in product/save action.
3 notes bellow:

**A)** The backend class of the attribute is processed in \Magento\Eav\Model\Entity\AbstractEntity::walkAttributes().
This function is called multiple times for the 2 products in product/save action.
The bug happens when the first parameter $partMethod is 'beforeSave' for the current product (the main product we edit/save). Wich by the case described abive, it has a different attributeSetId than the product in related products tab.

walkAttributes get's called from function `\Magento\Eav\Model\Entity\AbstractEntity::_beforeSave()`.
`$this->walkAttributes('backend/beforeSave', [$object]);`
The problem is in beforeSave 'context'.
In the function walkAttributes there is:

```
foreach ($this->getAttributesByCode() as $attrCode => $attribute) {
    if (isset($args[0]) && is_object($args[0]) && !$this->_isApplicableAttribute($args[0], $attribute)) {
        continue;
    }
```

`_isApplicableAttribute()` function does not see the **multiselect attribute as part of the attribute set**.
Further, the function `Magento\Catalog\Model\ResourceModel\AbstractResource::_isApplicableAttribute()` is called:

```
    protected function _isApplicableAttribute($object, $attribute)
    {
        $applyTo = $attribute->getApplyTo();
        return (count($applyTo) == 0 || in_array($object->getTypeId(), $applyTo))
            && $attribute->isInSet($object->getAttributeSetId());
    }

```

and `$attribute->isInSet($object->getAttributeSetId())` fails to see the attribute as part of the attribute set.

And `\Magento\Eav\Model\Entity\Attribute\AbstractAttribute::isInSet()` checks if the attribute is in set (current $setId) against `$this->getAttributeSetInfo()` magic function.
When beforeSave / walkAttributes checks if the attribute is part of the set, `$this->getAttributeSetInfo()`, it will see an empty array. **This is in the 'beforeSave' debug trace.** So `getAttributeSetInfo()` data for the main product's context, is affected by the configurable product from related. See C).

**B)** How `getAttributeSetInfo()` gets to be set to an empty array when it should not, is the actual problem.
The attribute set info data is retrieved/set with:
`\Magento\Eav\Model\Entity\Attribute\Set::addSetInfo()`:
`$setInfo = $this->_getResource()->getSetInfo($attributeIds, $setId);`
which is:
`\Magento\Eav\Model\ResourceModel\Entity\Attribute\Set::getSetInfo()` that fetches data (or retrieves from cache) and returns arrays with children containing group_id, group_sort and sort.

`\Magento\Eav\Model\Entity\Attribute\Set::addSetInfo()` is called from a couple of places. The relevant is:
`\Magento\Eav\Model\Entity\AbstractEntity::getSortedAttributes()`
which is called from:
`Magento\Catalog\Model\Product\Type\AbstractType::getSetAttributes()`
and I'll stop here in this debug trace because I could not point from this point where the problem actually lies.

**C)** Say, attribute_set_id is 10 for the main product and attribute_set_id is 99 for the related product.
For `activity` attribute,
`Magento\Eav\Model\Entity\Attribute\AbstractAttribute::isInSet()` is called in the context of:
- setId 10: `\Magento_Catalog\Controller\Adminhtml\Product/Initialization\Helper::initializeFromData()`
- setId 99: product 'afterLoad'
- setId 99: product 'afterLoad'
- setId 10: product 'beforeSave'
and here the getAttributeSetInfo is bugged in the context of 'activity' attribute.
But until this point getAttributeSetInfo looks good, especially for the main product (setId 10)
Somehow $attribute has the wrong attributeSetInfo data.
It looks like there are multiple instances of the attribute class in $attribute used and at some point  getAttributeSetInfo is lost by just using other instance and initializing it wrongly.

I saw a questionable use of  $this->getAttributeSetInfo() in `\Magento\Eav\Model\Entity\Attribute\AbstractAttribute::isInSet($setId)`:

```
if (!$this->hasAttributeSetInfo()) {
    return true;
}
```

This tells me that if the attributeSetInfo was not loaded, than go ahead, the attribute is surely in the set.
I guess this works if the attributes are used correctly in the right context of code. But we're in a case that the singletones or the context of the code is not clear or properly used. I would not rely on being in the right context deeply inside the code.
And I saw in other parts of the code like `\Magento\Eav\Model\Entity\Attribute\Set::addSetInfo()` that setting empty array to `$attribute->setAttributeSetInfo($attributeSetInfo)`. But the attribute is fetched/get from eavConfig singleton and using other $attributeIds as parameter coming from other singletons or just instances. Looks to me like a 'false' value should be used instead of init with empty array, if the attribute/attributeSet is not fetched already/correctly. That init with empty array avoids a local function variable ambiguity/PHP notice, but it's set globally into the $attribute.

I'd say this issue is important if you're QA confirms the severity of it. Like not only multiselect attributes feature is affected on product save.

**Comment by behnamshayani** [comment]
also relates to: https://github.com/magento/magento2/issues/7876

**Comment by daniel-ifrim** [comment]
Thank you @behnamshayani 
Yes, I can save when cache is disabled. It's because some of the functions use `$this->eavConfig->getAttribute(...)` and other classes do create different instances of the attribute. The attribute set info is set to any of these and not accessible from the other instances of attribute class.

**Comment by magento-engcom-team** [comment]
@daniel-ifrim, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by xmav** [comment]
@magento-engcom-team Could you add commit hash ? That will help to backport fix for this issue to older versions

**Comment by raulsinapsis** [comment]
Any commit we can see, to fix this in older versions?
