### ISSUE TITLE
Minicart is not getting updated after disabling product from backend

### ISSUE THREAD

**Issue by kaushalsutharhs** [magento/magento2#9979]
### Preconditions

1. Magento ver. 2.1.5 CE
2. PHP 7.0.15-0ubuntu0.16.04.4
3. MySQL version 5.7.17-0ubuntu0.16.04.1

### Steps to reproduce

1. Add any product into cart 
2. Disable added product from backend
3. Item is removed in shopping cart page as expected. However, Product is not removed from Minicart.

### Expected result

1. Once a product is disabled from backend, it should be removed from shopping cart and minicart as well.

### Actual result

1. Result after disabling a product.
![shopping cart](https://user-images.githubusercontent.com/16755576/27273878-949bef72-54ee-11e7-8755-b038fce57811.png)

_Cache is disabled and indexed are updated._

**Comment by Detzler** [comment]
A better approach would be to not remove the products from the quote (minicart and cart page). The user should see the unavailable products on the cart page so that he can react e.g. add an alternative product into cart.
So from my point of view, the minicart has correct functionality. The cart page doesn't.

**Comment by AlexWorking** [comment]
Hello @kaushalsutharhs. According to Your issue an internal ticket is created - MAGETWO-70108. You'll be informed when the bug is fixed. Thanks for applying.

**Comment by kaushalsutharhs** [comment]
Thanks @AlexWorking :+1:

**Comment by magento-engcom-team** [comment]
@kaushalsutharhs, thank you for your report.
We've created internal ticket(s) MAGETWO-70108 to track progress on the issue.

**Comment by rak-dynamo** [comment]
I am facing the same issue,
Is there any solution? Is there any update on ticket #MAGETWO-70108

**Comment by kirtinariya1** [comment]
@magento-engcom-team  Please provide Magento 2.3.1 CE test instance.

**Comment by kirtinariya1** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1, here is your [Magento instance](https://i-9979-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-9979-2-3-develop.instances.magento-community.engineering/admin](https://i-9979-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kirtinariya1** [comment]
Can't reproduces the issue.

**Comment by APanteleychuk** [comment]
Yes,  I'm reproduse this problem. It's because cart section not update after refresh page.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul, here is your [Magento instance](https://i-9979-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-9979-2-3-develop.instances.magento-community.engineering/admin](https://i-9979-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Issue not found, latest 2.3-development branch , This issue need to be closed.

**Comment by ghost** [comment]
I have followed all the steps describe and the issue is not reproducible any more. so closing the issue.

**Comment by atwixfirster** [comment]
@magento-engcom-team give me 2.4-develop instance
