### ISSUE TITLE
Layered Navigation with configurable product

### ISSUE THREAD

**Issue by Scqualo71** [magento/magento2#9980]
Hello,

I think is not correct the layered navigation with configurable product in Magento 2. Configurable products should be visible only if they have associated some SIMPLE PRODUCT that respects ALL applied filters. The same problem is with advantage research.

### Preconditions

1. Magento CE ver. 2.1.7

### Steps to reproduce

1. Insert this products:
![image](https://user-images.githubusercontent.com/29307582/27280140-2dc3d60e-54e7-11e7-8212-f626fdab0097.png)

### Expected result

1. Only configurable product A is visible

### Actual result

1. Both configurable product A and B are visible. So if the customer clicks on the product B does not find the desired combination.
2. you can see this example in:
http://ur2.chelegno.com/scatole-confezione/scatole-automontanti.html

**Comment by RomanKrut** [comment]
@Scqualo71  Hi, thank you for report this issue , internal ticket was created - MAGETWO-70107.

**Comment by magento-engcom-team** [comment]
@Scqualo71, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by ThomVeldpaus** [comment]
Hello, 

It seems Magento 1 has te same issue, does anyone know if there is relatable ticket for that?

**Comment by ikis1520** [comment]
Hi I reviewed the code this is a possible solution :

Modified the file vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php

           if ($isAttributeFilterable && (!$this->isOptionReducesResults($count, $productSize) || $count === 0)) {
            return;
        }
to:

        if ($isAttributeFilterable && $count === 0)) {
            return;
        }
I hope this help you.

**Comment by mbattistini** [comment]
Magento ver. 2.4.5-p1

Magento ver. 2.4.5-p1, PHP 8.1
I keep having the same problem, maybe it has to do with stock.
After selection, products displayed with selected attributes are displayed even if "out of stock".
